[ZH] Add `SB load` `Resnap` `Recalculate` and update `Menu`
ppy/osu-wiki pull request #10021
Opened 2023-09-08 07:50 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-08 18:13 UTC, YumeMuzi requested changes
如果一篇翻译文章完全是通过机器翻译得来，我还不如去看英文原文。

If a translated article is entirely obtained through translation software, I might as well read the original English article.

请以后不要这么做。

2023-09-08 18:13 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +- **尽可能裁剪图像。**实际上 Photoshop 有一个可以帮你裁剪的工具。只要点击图像 -> 裁剪，程序就会给出几个选项，用于裁去图像边角的空白区域。
```suggestion
- **尽可能将图片裁剪得小。**实际上，Photoshop 有一个可以帮你裁剪的工具。只要点击图像 -> 裁剪，程序就会给出几个选项，用于裁去图像边角的空白区域。
```

2023-09-08 18:13 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +- **利用故事板给出的不同“原点”设置。**假设你有一个头部上下摆动的人物。在大多数帧中，精灵图顶部会有大量空白区域，因为你想要所有帧都连起来，对吧？但如果你将原点设为底部中央，不管精灵图高度多少，总会沿底部对齐。这样你就能消灭顶部的空白区域了。
```suggestion
- **利用故事板提供的不同“原点”设置。**假设你有一个头部上下摆动的人物。在大多数帧中，精灵图顶部会有大量透明像素，因为你想要所有帧看起来连贯，对吧？但如果你将原点设为底部中央，不管精灵图高度多少，它总会沿底部对齐。这样你就能减去精灵图顶部的透明像素了。
```

2023-09-08 18:13 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +- **多个小图可能比一个大图好。**这一点大多与具体情况有关。现在假设你有一个很大的精灵图，上面只有五颗小星星。剪裁这个图后，中间会留下很大空白。把这样的精灵图分成很多小图看起来效率很低，但由于 osu! 的负荷来自像素数而非文件数，这实际上会是很大的改善。
```suggestion
- **多张小尺寸图片可能比一张大尺寸图片好。**这一点大多与具体情况有关。现在假设你有一张大尺寸的精灵图，上面只有五颗小星星。即使剪裁这张图片周围的透明像素后，中间还会留下一些可以优化掉的透明像素。看起来，把这样的精灵图分成很多张小精灵图效率很低，但由于 osu! 的渲染负荷主要取决于像素数而非文件数，实际上这能将情况改善很多。
```

2023-09-08 18:13 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +  - 类似地，如果你有一张全屏的“帧”图像，透过其中的大窗户或屏幕可以看到故事板的其余部分，就可以考虑将其裁成 4 个图像，左右上下四边各一个。现在由于只会绘制物品边框，而不会绘制几乎全屏的空像素，空白区域实际上什么都没有。你可能想要图像边角有一点重叠，这样可以避免在某些分辨率下游玩谱面时图像间出现间隙，但要让重叠部分尽量小。
```suggestion
  - 类似地，如果你有一张全屏的“框架”图像，透过其中的大窗户或屏幕可以看到故事板的其余部分，就可以考虑将其裁成 4 个图像，左右上下四边各一个。由于现在，游戏只会绘制图像内实际有效的元素边框，而不会绘制几乎占满全屏的空像素，空白区域实际上什么都没有。如果可以的话，图像边角最好留一点重叠，这样可以避免在某些分辨率下游玩谱面时，图片间出现间隙，但注意要让重叠部分尽量小。
```

2023-09-08 18:13 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +这种效果在故事板中用的并不是很多，因此提到这一点：**看看用脚本编写故事板一文的 "[colour](/wiki/Storyboard/Scripting/Commands#color-/-colour-(c)-command)" 事件代码**。你可以在故事板中，通过在灰阶图或亮色精灵图加上不同颜色来做出很酷的效果。有时当你想要让背景单独渐显时，就可以通过这种方式改变天空和其他素材的颜色。这一点
```suggestion
这种效果在故事板中用的并不是很多，因此提到这一点：**看看用脚本编写故事板一文的 "[colour](/wiki/Storyboard/Scripting/Commands#color-/-colour-(c)-command)" 事件代码**。你可以在故事板中，通过在灰阶或亮色精灵图上叠加不同颜色，来做出很酷的效果。如果你想要让背景单独逐渐显示时，就可以通过这种方式改变天空和其他素材的颜色。这一点也可以考虑一下。
```

2023-09-08 18:13 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +希望这些小提示能对一些人有用。很多人不了解禁用背景这一功能，因此请把这个小技巧告诉别人，尤其是看到他人用黑色空白图像隐藏背景图像时更应如此。
```suggestion
希望这些小提示能对一些人有用。很多人不了解禁用背景这一功能，因此请把这个小技巧告诉别人，尤其是看到他人用纯黑色图片掩盖住谱面背景图片时，更应如此。
```

2023-09-08 18:13 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +- 如果场景很复杂（有大量的重复元素），可以试试在 GIMP/Photoshop 中把它做成单个图像，然后只显示此图像（小心，如果过度使用，会导致文件大小增大）。
```suggestion
### 附加的小提示

- 确保图片在应该完全不可见时，不会仅仅降低了透明度，但图片仍旧作为故事板元素加载在屏幕上。
- 如果图片含有大量透明像素，可以将其分割为多个图像，然后在故事板引擎内拼接起来。
- 如果场景很复杂（有大量的重复元素），可以试试在 GIMP/Photoshop 中把它截取成单张小图片，然后重复显示这张图片（注意，如果过度使用，会导致故事板文件变得很大）。
```

2023-09-08 20:25 UTC, CloneWith commented
事实上，这几篇文章都是我独自完成的成果。


In fact these translations are completed by myself alone.


但出于理解表达能力有限，无法达到机翻水平，我感到很抱歉。


But due to my limited understanding and expressing ability, those might not as good as MT, for which I felt sorry.


谢谢你的建议，我会再次自查修改。


Anyway thanks for your advice and I will arrange a cleanup again.



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 9, 2023 02:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ppy/osu-wiki] [ZH] Add `SB load` `Resnap` `Recalculate` andupdate `Menu` (PR #10021)




 
@YumeMuzi requested changes on this pull request.
 
如果一篇翻译文章完全是通过机器翻译得来，我还不如去看英文原文。
 
If a translated article is entirely obtained through translation software, I might as well read the original English article.
 
请以后不要这么做。

 
In wiki/Client/Beatmap_editor/Recalculate_slider_lengths/zh.md:
 &gt; @@ -0,0 +1,9 @@ +--- +stub: true +--- + +# 重新计算滑条长度 + +**重新计算滑条长度**是[谱面编辑器](/wiki/Client/Beatmap_editor)中 `Timing` 标签页下的一条命令。如果[谱面](/wiki/Beatmap)已经有[滑条](/wiki/Gameplay/Hit_object/Slider)，建议在改变 [BPM](/wiki/Music_theory/Tempo) 后使用此命令。 + +此命令会按新的 BPM 自动调整谱面中所有滑条的长度。尽管如此，由于此工具本质上不精确且是系统化的，许多制图者都推荐检查每个滑条，并手动调整其长度。  ⬇️ Suggested change -此命令会按新的 BPM 自动调整谱面中所有滑条的长度。尽管如此，由于此工具本质上不精确且是系统化的，许多制图者都推荐检查每个滑条，并手动调整其长度。 +这个命令会按新的 BPM 自动调整谱面中所有滑条的长度。然而，因为这个工具不够精确且过于机械呆板，大多数谱师会检查并手动调整谱面中所有滑条。  
 
In wiki/Client/Beatmap_editor/Resnap/zh.md:
 &gt; @@ -0,0 +1,9 @@ +--- +stub: true +--- + +# 重新对齐 + +**重新对齐**指的是[谱面编辑器](/wiki/Client/Beatmap_editor)中 `Timing` 标签页下的一对命令，其中一条命令应用到整张[谱面](/wiki/Beatmap)，另一条只用于当前计时区段。如果谱面只有一个计时区段，这两条命令就是相同的。 + +此命令会自动重新调整时间线上所有[打击物件](/wiki/Gameplay/Hit_object)的位置，以此让其落在节拍细分设置允许的最近的细分线上。建议在偏移量和/或 BPM 在物件放置完毕后改变时使用此命令。由于此工具本质上不精确且是系统化的，许多制图者都推荐手动检查并调整每个物件在[时间线](/wiki/Client/Beatmap_editor/Timelines)上的位置。  ⬇️ Suggested change -此命令会自动重新调整时间线上所有[打击物件](/wiki/Gameplay/Hit_object)的位置，以此让其落在节拍细分设置允许的最近的细分线上。建议在偏移量和/或 BPM 在物件放置完毕后改变时使用此命令。由于此工具本质上不精确且是系统化的，许多制图者都推荐手动检查并调整每个物件在[时间线](/wiki/Client/Beatmap_editor/Timelines)上的位置。 +这个命令会自动重新调整时间线上所有[打击物件](/wiki/Gameplay/Hit_object)的位置，以此让其落在节拍细分设置允许的最近的细分线上。建议在物件放置完毕之后，但还需要调整偏移量、BPM 的时候，使用此命令。然而，因为这个工具不够精确且过于机械呆板，大多数谱师会检查并手动调整物件在[时间线](/wiki/Client/Beatmap_editor/Timelines)上的位置。  
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; +tags: +  - SB +  - SB load +  - load +  - storyboard +  - storyboarding +  - performance +  - 故事板 +  - 负载 +  - 制作故事板 +  - 性能 +--- + +# 故事板负载 + +**SB 负载**（故事板负载的缩写）是[制作故事板](/wiki/Storyboard)时用到的一个参数，指示故事板加载故事板为图形程序带来的负荷大小。这个参数用来估量一帧内整个 640x480 区域需要重新绘制的次数。  ⬇️ Suggested change -**SB 负载**（故事板负载的缩写）是[制作故事板](/wiki/Storyboard)时用到的一个参数，指示故事板加载故事板为图形程序带来的负荷大小。这个参数用来估量一帧内整个 640x480 区域需要重新绘制的次数。 +**故事板负载**（SB load）是[制作故事板](/wiki/Storyboard)时会见到的一个参数，它指示加载故事板时，图形程序的负荷大小。这个参数用来估量一帧内，需要重新绘制整个 640x480 像素的区域数量。  
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; +  - storyboard +  - storyboarding +  - performance +  - 故事板 +  - 负载 +  - 制作故事板 +  - 性能 +--- + +# 故事板负载 + +**SB 负载**（故事板负载的缩写）是[制作故事板](/wiki/Storyboard)时用到的一个参数，指示故事板加载故事板为图形程序带来的负荷大小。这个参数用来估量一帧内整个 640x480 区域需要重新绘制的次数。 + +不使用故事板时，负荷为 1x （640x480 的空间只需要绘制一次）。如果故事板中有单个占用半屏的图像，负荷就是 1.5x；两个完全重合、占用半屏的图像负荷是 2x。 + +谱面的 SB 负载最好不要超过 5x，这样可以确保大多数玩家能在不致显卡压力过大的情况下浏览谱面。  ⬇️ Suggested change -谱面的 SB 负载最好不要超过 5x，这样可以确保大多数玩家能在不致显卡压力过大的情况下浏览谱面。 +谱面的 SB 负载最好不要超过 5x，这样可以确保大多数玩家在游玩谱面时，显卡压力不会过大。  
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; +不使用故事板时，负荷为 1x （640x480 的空间只需要绘制一次）。如果故事板中有单个占用半屏的图像，负荷就是 1.5x；两个完全重合、占用半屏的图像负荷是 2x。 + +谱面的 SB 负载最好不要超过 5x，这样可以确保大多数玩家能在不致显卡压力过大的情况下浏览谱面。 + +[论坛原帖](https://osu.ppy.sh/community/forums/posts/525077) + +## 显示位置 + +- 在[谱面编辑器](/wiki/Client/Beatmap_editor)中测试。 +- 使用[故事板编辑器](/wiki/Client/Beatmap_editor/Design)，数字可能不准确。 + +## 降低负载的建议 + +节选自 [Reducing SB Load](https://osu.ppy.sh/community/forums/topics/55177)： + +下面是关于减少故事板为玩家电脑带来的负担，一些重要的建议。这一部分只是表面上有些冗长、太具体了而已，实际上要点并不复杂，这些要点将会加粗标出。  ⬇️ Suggested change -下面是关于减少故事板为玩家电脑带来的负担，一些重要的建议。这一部分只是表面上有些冗长、太具体了而已，实际上要点并不复杂，这些要点将会加粗标出。 +下面是一些重要的，关于减少故事板为玩家电脑带来负担的建议。表面上，这一部分看似有些冗长、太具体，实际上，这一部分的要点并不复杂。要点将会加粗标出。  
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; +[论坛原帖](https://osu.ppy.sh/community/forums/posts/525077) + +## 显示位置 + +- 在[谱面编辑器](/wiki/Client/Beatmap_editor)中测试。 +- 使用[故事板编辑器](/wiki/Client/Beatmap_editor/Design)，数字可能不准确。 + +## 降低负载的建议 + +节选自 [Reducing SB Load](https://osu.ppy.sh/community/forums/topics/55177)： + +下面是关于减少故事板为玩家电脑带来的负担，一些重要的建议。这一部分只是表面上有些冗长、太具体了而已，实际上要点并不复杂，这些要点将会加粗标出。 + +### 禁用背景图片 + +默认情况下，谱面选择的背景图像会在整首歌期间显示，即使在前面制作故事板也会如此。如果你要做极简故事板，或者谱面背景在故事板中也作为背景显示时，这个功能就很好。  ⬇️ Suggested change -默认情况下，谱面选择的背景图像会在整首歌期间显示，即使在前面制作故事板也会如此。如果你要做极简故事板，或者谱面背景在故事板中也作为背景显示时，这个功能就很好。 +默认情况下，谱面的背景图片会在整首歌播放期间正常显示，即使谱面含有故事板，也会如此。如果你要做非常简单的故事板，或者谱面的背景图片也作为故事板中的一部分元素显示时，这个特性就很合适。  
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; +## 显示位置 + +- 在[谱面编辑器](/wiki/Client/Beatmap_editor)中测试。 +- 使用[故事板编辑器](/wiki/Client/Beatmap_editor/Design)，数字可能不准确。 + +## 降低负载的建议 + +节选自 [Reducing SB Load](https://osu.ppy.sh/community/forums/topics/55177)： + +下面是关于减少故事板为玩家电脑带来的负担，一些重要的建议。这一部分只是表面上有些冗长、太具体了而已，实际上要点并不复杂，这些要点将会加粗标出。 + +### 禁用背景图片 + +默认情况下，谱面选择的背景图像会在整首歌期间显示，即使在前面制作故事板也会如此。如果你要做极简故事板，或者谱面背景在故事板中也作为背景显示时，这个功能就很好。 + +然而，如果在编写故事板时用到别的背景，这就成了个问题。看看，尽管谱面背景前面有别的东西，osu! 也会一直绘制它。故事板的图层越多，osu! 要处理的就越多，因此隐藏图层的存在就是在浪费系统资源。  ⬇️ Suggested change -然而，如果在编写故事板时用到别的背景，这就成了个问题。看看，尽管谱面背景前面有别的东西，osu! 也会一直绘制它。故事板的图层越多，osu! 要处理的就越多，因此隐藏图层的存在就是在浪费系统资源。 +然而，如果在编写故事板时需要用到别的背景图片，这就成了个问题。看看，尽管谱面背景图片的前面有别的东西，osu! 也会一直绘制它。故事板的图层越多，osu! 要处理的就越多，因此无视这个图层的存在，就是在浪费系统资源。  
你这翻译的歧义 misleading 也太严重了把
 
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; +osu! 有一个消除冗余的功能，当你在故事板中用到谱面背景图像时，就会在游玩时自动禁止显示谱面背景。因此如果故事板中只有一个“场景”将谱面背景用作背景，或者谱面背景是幻灯片类元素的一部分，只需要像调用其他图像一样调用背景图像即可，一切会正常显示。 + +但如果想要在整张图期间用不同的故事板元素，只想拿一张图像作为选歌界面的背景、网页上的预览图显示，你就需要将此图像正常设置为背景，然后在 `.osb` （或者 `.osu`，如果每个难度的故事板不同）文件的 “//Storyboard Layer 0 (Background)” 标题下加一行故事板代码。这行代码仅仅调用背景图像，不会做别的事情。 + +**只要将下面一行中 "background.jpg" 用图像文件名替代即可：** + +`Sprite,Background,TopLeft,"background.jpg",0,0` + +这就成了！你的背景会被纯黑色替代，几乎不需要处理即可绘制。特别是与绘制全屏背景后在其上绘制全屏的黑.png 相比，这是个巨大的改善！  ⬇️ Suggested change -osu! 有一个消除冗余的功能，当你在故事板中用到谱面背景图像时，就会在游玩时自动禁止显示谱面背景。因此如果故事板中只有一个“场景”将谱面背景用作背景，或者谱面背景是幻灯片类元素的一部分，只需要像调用其他图像一样调用背景图像即可，一切会正常显示。 - -但如果想要在整张图期间用不同的故事板元素，只想拿一张图像作为选歌界面的背景、网页上的预览图显示，你就需要将此图像正常设置为背景，然后在 `.osb` （或者 `.osu`，如果每个难度的故事板不同）文件的 “//Storyboard Layer 0 (Background)” 标题下加一行故事板代码。这行代码仅仅调用背景图像，不会做别的事情。 - -**只要将下面一行中 "background.jpg" 用图像文件名替代即可：** - -`Sprite,Background,TopLeft,"background.jpg",0,0` - -这就成了！你的背景会被纯黑色替代，几乎不需要处理即可绘制。特别是与绘制全屏背景后在其上绘制全屏的黑.png 相比，这是个巨大的改善！ +osu! 有一个消除冗余的功能：当你在故事板中使用这张谱面的背景图片时，游玩时就会自动卸载谱面背景。因此，如果故事板中只有一个“场景”使用了谱面的背景图片，或者谱面背景图片是故事板元素的一部分，只需要像调用其他图像一样，调用这张背景图片即可，其他一切会正常显示。 + +但如果，你想要在谱面内使用不同的故事板元素，并且只想将一张图片作为选歌界面的背景，以及谱面在网页上的预览图，你就需要将这张照片正常设置为谱面背景，然后在 `.osb`  文件（如果难度之间的故事板不同，则需要在 `.osu` 文件下修改）的 “//Storyboard Layer 0 (Background)” 标题下加一行故事板代码。这行代码仅仅调用背景图像，不会做别的事情。 + +**只要将下面一行中 "background.jpg" 用这个谱面背景图片文件名替代即可：** + +`Sprite,Background,TopLeft,"background.jpg",0,0` + +这就成了！你的背景图片会被纯黑色替代，游戏绘制时几乎不需要处理。相比于直接在背景图片上添加一张全屏的黑色 png 相比，性能有了大幅度的改善！  
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; + +然而，如果在编写故事板时用到别的背景，这就成了个问题。看看，尽管谱面背景前面有别的东西，osu! 也会一直绘制它。故事板的图层越多，osu! 要处理的就越多，因此隐藏图层的存在就是在浪费系统资源。 + +所以应该怎么办呢？ + +osu! 有一个消除冗余的功能，当你在故事板中用到谱面背景图像时，就会在游玩时自动禁止显示谱面背景。因此如果故事板中只有一个“场景”将谱面背景用作背景，或者谱面背景是幻灯片类元素的一部分，只需要像调用其他图像一样调用背景图像即可，一切会正常显示。 + +但如果想要在整张图期间用不同的故事板元素，只想拿一张图像作为选歌界面的背景、网页上的预览图显示，你就需要将此图像正常设置为背景，然后在 `.osb` （或者 `.osu`，如果每个难度的故事板不同）文件的 “//Storyboard Layer 0 (Background)” 标题下加一行故事板代码。这行代码仅仅调用背景图像，不会做别的事情。 + +**只要将下面一行中 "background.jpg" 用图像文件名替代即可：** + +`Sprite,Background,TopLeft,"background.jpg",0,0` + +这就成了！你的背景会被纯黑色替代，几乎不需要处理即可绘制。特别是与绘制全屏背景后在其上绘制全屏的黑.png 相比，这是个巨大的改善！ + +### 避免在图片中出现空白空间  ⬇️ Suggested change -### 避免在图片中出现空白空间 +### 避免使用含有大量透明像素的图片  
 
In wiki/Client/Beatmap_editor/SB_load/zh.md:
 &gt; + +所以应该怎么办呢？ + +osu! 有一个消除冗余的功能，当你在故事板中用到谱面背景图像时，就会在游玩时自动禁止显示谱面背景。因此如果故事板中只有一个“场景”将谱面背景用作背景，或者谱面背景是幻灯片类元素的一部分，只需要像调用其他图像一样调用背景图像即可，一切会正常显示。 + +但如果想要在整张图期间用不同的故事板元素，只想拿一张图像作为选歌界面的背景、网页上的预览图显示，你就需要将此图像正常设置为背景，然后在 `.osb` （或者 `.osu`，如果每个难度的故事板不同）文件 [...]

2023-09-10 05:00 UTC, cdwcgt reviewed
seens `wiki/Client/Beatmap_editor/Menu/zh.md` still outdated?

很奇怪啊，你这个谱面编辑器菜单和原文对不上

2023-09-10 05:05 UTC, cdwcgt requested changes
The last time you updated the Beatmap editor menu was on [July 13th](https://github.com/ppy/osu-wiki/commit/2a5566f108b26bab88c9fd8f7d45e87e23ff49f9)
However, [Beatmap editor menu](https://github.com/ppy/osu-wiki/commits/master/wiki/Client/Beatmap_editor/Menu/en.md) has been updated after Aug 12th

Please confirm the new content of the original text change and update the translation.

2023-09-12 06:16 UTC, CloneWith commented on wiki/Client/Beatmap_editor/SB_load/zh.md
> +- 确保图片在应该完全不可见时，不会仅仅降低了透明度，但图片仍旧作为故事板元素加载在屏幕上。
是的，翻译的过程中出了点小问题

2023-09-17 11:54 UTC, YumeMuzi approved these changes

2023-09-20 13:41 UTC, TicClick approved these changes

2023-09-20 14:29 UTC, merged