[DE] Update `Changelog`
ppy/osu-wiki pull request #10029
Opened 2023-09-09 13:21 UTC by The-Last-Cookie

## Notes

- `category switcher` --> `Auswahlliste`
- `area of effect` --> `Themegebiet`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-10 09:30 UTC, respektive requested changes

2023-09-10 09:30 UTC, respektive commented on wiki/Changelog/de.md
> +Die Änderungsliste unterstützt neben Markdown-Formatierung auch Medien wie statische Bilder, animierte GIFs und eingebettete Videos. Während die Änderungen manuell hinzugefügt werden, werden sie typi
```suggestion
Die Änderungsliste unterstützt neben Markdown-Formatierung auch Medien wie statische Bilder, animierte GIFs und eingebettete Videos. Während die Änderungen manuell hinzugefügt werden können, werden sie typischerweise von GitHub (wo eine Überprüfung der Änderungen stattfindet) abgerufen und automatisch gruppiert, sobald eine neue Version veröffentlicht wird. Standardmäßig wird alles unter einer horizontalen Linie (`---`) in der Beschreibung eines Änderungsvorschlags (Pull Request) als detaillierte Erklärung für die Änderung verwendet.
```

2023-09-11 03:22 UTC, respektive approved these changes

2023-09-13 03:32 UTC, cl8n requested changes

2023-09-13 03:32 UTC, cl8n commented on wiki/Changelog/de.md
>  Das Änderungsprotokoll wurde von peppy am 11. September 2007 in einem dafür gedachten Forum-Thread mit dem Titel "[Official Development Changelog](https://osu.ppy.sh/community/forums/topics/15)" gest
missing link that was added to EN, and potentially minor grammar change (not sure if it applies to this translation)

2023-09-13 05:18 UTC, respektive commented on wiki/Changelog/de.md
>  Das Änderungsprotokoll wurde von peppy am 11. September 2007 in einem dafür gedachten Forum-Thread mit dem Titel "[Official Development Changelog](https://osu.ppy.sh/community/forums/topics/15)" gest
```suggestion
Das Änderungsprotokoll wurde von [peppy](/wiki/People/peppy) am 11. September 2007 in einem dafür gedachten Forum-Thread mit dem Titel "[Official Development Changelog](https://osu.ppy.sh/community/forums/topics/15)" gestartet, in dem er wesentliche Änderungen und Fehlerbehebungen auflisten und manchmal Einblicke in anstehende Pläne geben würde.
```
grammar is fine

2023-09-13 06:33 UTC, cl8n approved these changes

2023-09-13 06:35 UTC, merged