[DE] Update `Tournaments/Official support`, `People/Users qith unique titles` and `Community/osu! community meetings`
ppy/osu-wiki pull request #10034
Opened 2023-09-10 14:12 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-12 11:08 UTC, respektive requested changes

2023-09-12 11:08 UTC, respektive commented on wiki/Community/osu!_community_meetings/de.md
> +| 17 | [21. August 2023](https://youtu.be/O2j00E6AVW8) | [Übersichtsvideo](https://youtu.be/crkT0aaowKQ) | Verlagerung der Entwicklung auf die Fertigstellung von Ranglistenspielen |
```suggestion
| 17 | [21. August 2023](https://youtu.be/O2j00E6AVW8) | [Zusammenfassendes Video](https://youtu.be/crkT0aaowKQ) | Verlagerung des Entwicklungsschwerpunkts auf die Fertigstellung von Ranglistenspielen |
```
Mabye works a bit better

2023-09-12 11:08 UTC, respektive commented on wiki/People/Users_with_unique_titles/de.md
>  Diesen Spielern wurden ihre entsprechenden Titel entweder durch eine verrückte Errungenschaft im Spiel oder durch Abschluss einer spezifischen  Herausforderung vergeben.
```suggestion
Diesen Spielern wurden ihre entsprechenden Titel entweder durch eine verrückte Errungenschaft im Spiel oder durch Abschluss einer spezifischen Herausforderung vergeben.
```

2023-09-12 17:05 UTC, agatemosu commented on wiki/People/Users_with_unique_titles/de.md
> +| ::{ flag=US }:: [UberFazz](https://osu.ppy.sh/users/8646059) | Medal Hunter | War die [erste Person, die die Medaille *Internment* freischaltete](https://twitter.com/osugame/status/1696007320663359
nothing but
```suggestion
| ::{ flag=US }:: [UberFazz](https://osu.ppy.sh/users/8646059) | Medal Hunter | War die [erste Person, die die Medaille *Internment* freischaltete](https://twitter.com/osugame/status/1696007320663359800) |
```

2023-09-17 14:40 UTC, The-Last-Cookie reviewed
The changes are now implemented and can be reviewed.

I've added the comments from the PR's description directly under the corresponding lines to make the review easier.

2023-09-17 14:40 UTC, The-Last-Cookie commented on wiki/Tournaments/Official_support/de.md
> +- Jedes Spiel innerhalb derselben Gruppen- oder Qualifikationsrunde sollte in einem einheitlichen Format sein. In einem Turnier, das zum Beispiel eine Qualifikationsphase und ein Doppeleliminierungsv
- `bracket`: Normally, I would have translated this with `Tunierbaum`. In the case above, this didn't make sense to me, so I used `Gruppe(nphase/runde)`.
- `bracket match`: I'm not entirely sure if this has some special meaning compared to just `match`. I translated it to `Entscheidungsspiel`.

2023-09-17 14:40 UTC, The-Last-Cookie commented on wiki/Tournaments/Official_support/de.md
> +Des Weiteren wird von den Spielern erwartet, dass sie an einem bestimmten Turnier *hinreichend teilgenommen* haben, um sich für etwaige Preise zu qualifizieren — sich einfach als Mitglied eines Siege
**hinreichend teilgenommen**: `reasonably` can be translated as "behaved well" and "put in enough effort". This rule specifically refers to people that qualify together with a team for the badge prizes. Receiving badges without playing enough matches is forbidden.

See [this discussion on Discord](https://discord.com/channels/188630481301012481/867773019015610389/1152574080319492158).

2023-09-17 14:40 UTC, The-Last-Cookie commented on wiki/Tournaments/Official_support/de.md
> +Langjährige Turniere von der Community können sich für zusätzliche Unterstützung qualifizieren, um ihre Reichweite in der Spielergemeinschaft zu erhöhen, sprich Banner im Hauptmenü des Spiels und Öff
Alternatives for the first phrase: `Präsenz`, `Sichtbarkeit bei den Spielern`

2023-09-17 15:18 UTC, respektive approved these changes
:+1:

2023-09-20 13:42 UTC, TicClick approved these changes

2023-09-20 14:44 UTC, merged