Update `Main page`, `Help centre/Beatmapping`, `People/GMT`
ppy/osu-wiki pull request #10033
Opened 2023-09-10 11:57 UTC by githacki

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-10 14:05 UTC, Sclafus requested changes

2023-09-10 14:05 UTC, Sclafus commented on wiki/Main_page/it.md
> +[Il Team](/wiki/People/osu!_team): [Sviluppatori](/wiki/People/Developers) • [Artisti in Primo Piano](/wiki/People/Featured_Artists) • [Team di Moderazione Globale](/wiki/People/Global_Moderation_Tea
```suggestion
[Il Team](/wiki/People/osu!_team): [Sviluppatori](/wiki/People/Developers) • [Artisti in Primo Piano](/wiki/People/Featured_Artists) • [Team di Moderazione Globale](/wiki/People/Global_Moderation_Team) • [Team di Supporto](/wiki/People/Support_Team) • [Team di Valutazione Nomine](/wiki/People/Nomination_Assessment_Team) • [Nominatori di Beatmap](/wiki/People/Beatmap_Nominators) • [osu! Alumni](/wiki/People/osu!_Alumni) • [Team Progetto Amata](/wiki/People/Project_Loved_Team) • [Curatori Beatmap Spotlight](/wiki/People/Beatmap_Spotlight_Curators)
```

2023-09-10 14:11 UTC, Sclafus approved these changes

2023-09-13 03:24 UTC, cl8n approved these changes

2023-09-13 03:26 UTC, merged