Create ranking es.md
ppy/osu-wiki pull request #10031
Opened 2023-09-09 21:52 UTC by Jsanchez100

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-10 19:42 UTC, agatemosu requested changes

2023-09-13 21:08 UTC, UnknownOsu requested changes

2023-09-13 21:08 UTC, UnknownOsu commented on wiki/Ranking/es.md
> +La clasificación de Kudosu compara los [Kudosu](/wiki/Modding/Kudosu) acumulados por los usuarios y los enumera en consecuencia. Esta clasificación no requiere habilidades de juego, ya que los Kudosu
```suggestion
La clasificación por Kudosu compara el [Kudosu](/wiki/Modding/Kudosu) acumulado por los usuarios y los enumera en consecuencia. Esta clasificación no requiere habilidades de juego, ya que el Kudosu se obtiene como parte del [proceso de modding](/wiki/Modding).
```

2023-09-13 21:08 UTC, UnknownOsu commented on wiki/Ranking/es.md
> +La clasificación de puntuación compara la puntuación total de los jugadores y los enumera en consecuencia. Ocupar un lugar destacado en esta clasificación requiere un gran compromiso de tiempo, pero
```suggestion
La clasificación por puntuación compara la puntuación total de los jugadores y los enumera en consecuencia. Ocupar un lugar destacado en esta clasificación requiere un gran compromiso de tiempo, pero se necesita relativamente menos habilidad mecánica que en la clasificación por puntos de rendimiento.
```

2023-09-13 21:08 UTC, UnknownOsu commented on wiki/Ranking/es.md
> +La clasificación de puntos de rendimiento describe el nivel de habilidad de un jugador en comparación con otros jugadores. Esta tabla de clasificación se determina por el número total de puntos de re
```suggestion
La clasificación por puntos de rendimiento describe el nivel de habilidad de un jugador en comparación con otros jugadores. Esta tabla de clasificación se determina por el número total de puntos de rendimiento que tiene un jugador individual, y se puede ver en el perfil de un jugador y en las [tablas de rendimiento](https://osu.ppy.sh/rankings/osu/performance).
```

2023-09-13 21:08 UTC, UnknownOsu commented on wiki/Ranking/es.md
> +## Clasificación de países
```suggestion
## Clasificación por países
```

2023-09-13 21:08 UTC, UnknownOsu commented on wiki/Ranking/es.md
> +La clasificación de países se basan en los puntos de rendimiento de los jugadores de un país.
```suggestion
La clasificación por países se basan en los puntos de rendimiento de los jugadores de un país.
```

2023-09-13 21:08 UTC, UnknownOsu commented on wiki/Ranking/es.md
> +## Clasificación de puntos de rendimiento
Creo que queda mejor `por` en lugar de `de` en algunos casos

2023-09-16 17:03 UTC, agatemosu approved these changes

2023-09-16 18:09 UTC, cl8n approved these changes

2023-09-16 18:11 UTC, merged