[ES] Add `Completionists`
ppy/osu-wiki pull request #10042
Opened 2023-09-11 15:22 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-13 20:47 UTC, UnknownOsu requested changes

2023-09-13 20:47 UTC, UnknownOsu commented on wiki/People/Completionists/es.md
> +Los **completacionistas** son jugadores que han completado todos los [beatmaps](/wiki/Beatmap) [clasificados](/wiki/Beatmap/Category#clasificados) de un [game mode](/wiki/Game_mode) determinado. Debi
```suggestion
Los **completacionistas** son jugadores que han completado todos los [beatmaps](/wiki/Beatmap) [clasificados](/wiki/Beatmap/Category#clasificados) de un [modo de juego](/wiki/Game_mode) determinado. Debido a que la cantidad de beatmaps clasificados aumenta cada día, esta hazaña se vuelve cada vez más difícil de lograr.
```

2023-09-13 20:47 UTC, UnknownOsu commented on wiki/People/Completionists/es.md
> +- ::{ flag=AU }:: [Jaye](https://osu.ppy.sh/users/4841352) recibió el título de usuario *Drum Decimator* por ser el primer completacionista de osu!taiko y conseguir combos completos en cada beatmap d
```suggestion
- ::{ flag=AU }:: [Jaye](https://osu.ppy.sh/users/4841352) recibió el título de usuario *Drum Decimator* por ser el primer completacionista de osu!taiko y conseguir full combo en cada beatmap de osu!taiko clasificado.
```

2023-09-13 20:47 UTC, UnknownOsu commented on wiki/People/Completionists/es.md
> +- Antes de septiembre de 2023, los jugadores solían ganar el título de usuario *osu!completionist*, que se suspendió en favor de las insignias de perfil.
```suggestion
- Antes de septiembre de 2023, los jugadores solían ganar el título de usuario *osu!completionist*, que dejó de utilizarse en favor de las insignias de perfil.
```

2023-09-13 20:47 UTC, UnknownOsu commented on wiki/People/Completionists/es.md
> +- ::{ flag=AU }:: [Jaye](https://osu.ppy.sh/users/4841352) recibió el título de usuario *Drum Decimator* por ser el primer completacionista de osu!taiko y conseguir combos completos en cada beatmap d
Creo que `full combo` queda mejor con el contexto del juego, lo veo más raro decir `combo completo(s)` en lugar de lo ya mencionado

2023-09-20 13:52 UTC, TicClick approved these changes

2023-09-20 16:16 UTC, merged