[ES] Update `osu!supporter`
ppy/osu-wiki pull request #10044
Opened 2023-09-11 20:45 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-13 20:34 UTC, UnknownOsu requested changes

2023-09-13 20:34 UTC, UnknownOsu commented on wiki/osu!supporter/es.md
> +**osu!supporter** (o la ***etiqueta osu!supporter***) es un título temporal dado a los jugadores que apoyan a osu!, de manera voluntaria, con una donación monetaria para ayudarlo a crecer. Los suppor
```suggestion
**osu!supporter** (o la ***etiqueta osu!supporter***) es un título temporal dado a los jugadores que apoyan a osu!, de manera voluntaria, con una donación monetaria para ayudarlo a crecer. Los supporters reciben un puñado de beneficios cosméticos y técnicos, la mayoría solo se presentan cuando el título está presente. Las características extras de osu!supporter no dan ningún tipo de ventaja en el juego, rendimiento o puntuación, y nunca lo hará.
```

2023-09-13 20:38 UTC, UnknownOsu commented on wiki/osu!supporter/es.md
> +**osu!supporter** (o la ***etiqueta osu!supporter***) es un título temporal dado a los jugadores que apoyan a osu!, de manera voluntaria, con una donación monetaria para ayudarlo a crecer. Los suppor
Tal vez puedas cambiar las fotos que están en inglés, acá las dejo: [`1`](https://i.imgur.com/9eGceBO.png), [`2`](https://i.imgur.com/Kp9MM9X.png).

Igual puedes sacar las fotos tú

2023-09-20 21:05 UTC, TicClick approved these changes

2023-09-20 21:08 UTC, merged