[ES] Add `FC` and `Combo multiplier effect` / Native review of `Accuracy` and `Choke`
ppy/osu-wiki pull request #10054
Opened 2023-09-14 19:00 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-20 21:27 UTC, UnknownOsu requested changes

2023-09-20 21:27 UTC, UnknownOsu commented on wiki/Gameplay/Choke/es.md
> +Una característica clave de un choke es su aleatoriedad y rendimiento inconsistente. Esto excluye fallos regulares o específicos de un patrón o la [rotura de un slider](/wiki/Gameplay/Judgement/Slide
```suggestion
Una característica clave de un choke es su aleatoriedad y rendimiento inconsistente. Esto excluye fallos regulares o específicos de un patrón o la [rotura de un slider](/wiki/Gameplay/Judgement/Slider_break), que generalmente están vinculados con el nivel de habilidad de un jugador o de cómo se está construido el beatmap. Los chokes usualmente son causados por el estrés mental y los nervios excesivos durando el juego, así como por una fatiga general.
```

2023-09-20 21:27 UTC, UnknownOsu commented on wiki/Gameplay/Full_combo/es.md
> +**Full combo** o **combo completo** (o *FC* para acortar) es un término usado para describir el [combo](/wiki/Beatmapping/Combo) máximo que puede conseguir un jugador en un [beatmap](/wiki/Beatmap).
```suggestion
**Full combo** o **combo completo** (o *FC* para acortar) es un término usado para describir el [combo](/wiki/Beatmapping/Combo) máximo que puede conseguir un jugador en un [beatmap](/wiki/Beatmap). Los combos completos se consiguen pasando un beatmap sin fallos, [slidersbreaks](/wiki/Gameplay/Judgement/Slider_break) o [slider ends](/wiki/Gameplay/Hit_object/Slider/Slidertail) fallados.
```

2023-09-20 21:27 UTC, UnknownOsu commented on wiki/Gameplay/es.md
> +- [Puntación](/wiki/Gameplay/Score)
```suggestion
- [Puntuación](/wiki/Gameplay/Score)
```

2023-09-20 21:27 UTC, UnknownOsu commented on wiki/Gameplay/Full_combo/es.md
> +**Full combo** o **combo completo** (o *FC* para acortar) es un término usado para describir el [combo](/wiki/Beatmapping/Combo) máximo que puede conseguir un jugador en un [beatmap](/wiki/Beatmap).
Está raro `slider rotos`. Además, `slider ends` tampoco está traducido, así que creo que es mejor que también se quede en su forma original (`sliderbreaks`)

2023-09-20 21:58 UTC, UnknownOsu requested changes

2023-09-20 21:58 UTC, UnknownOsu commented on wiki/Gameplay/Choke/es.md
> +Una característica clave de un choke es su aleatoriedad y rendimiento inconsistente. Esto excluye fallos regulares o específicos de un patrón o la [rotura de un slider](/wiki/Gameplay/Judgement/Slide
```suggestion
Una característica clave de un choke es su aleatoriedad y rendimiento inconsistente. Esto excluye fallos regulares o específicos de un patrón o [sliderbreaks](/wiki/Gameplay/Judgement/Slider_break), que generalmente están vinculados con el nivel de habilidad de un jugador o de cómo está construido el beatmap. Los chokes usualmente son causados por el estrés mental y los nervios excesivos durante el juego, así como por una fatiga general.
```

2023-09-20 21:58 UTC, UnknownOsu commented on wiki/Gameplay/Full_combo/es.md
> +**Full combo** o **combo completo** (o *FC* para acortar) es un término usado para describir el [combo](/wiki/Beatmapping/Combo) máximo que puede conseguir un jugador en un [beatmap](/wiki/Beatmap).
```suggestion
**Full combo** o **combo completo** (o *FC* para acortar) es un término usado para describir el [combo](/wiki/Beatmapping/Combo) máximo que puede conseguir un jugador en un [beatmap](/wiki/Beatmap). Los combos completos se consiguen pasando un beatmap sin fallos, [sliderbreaks](/wiki/Gameplay/Judgement/Slider_break) o [slider ends](/wiki/Gameplay/Hit_object/Slider/Slidertail) fallados.
```

2023-10-09 17:32 UTC, TicClick approved these changes

2023-10-09 17:55 UTC, merged