[KO] Add `OWC/2022`
ppy/osu-wiki pull request #10064
Opened 2023-09-19 16:38 UTC by Chronicler01

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-20 00:32 UTC, Sitoria requested changes
개인적으로 국가 이름도 번역이 되었으면 좋겠네요. (선택사항)

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +| 토너먼트 매니저 | ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578), ::{ flag=US }:: [ChillierPear](https://osu.ppy.sh/users/9501251), ::{ flag=BR }:: [LeoFLT](https://osu.ppy.sh/users/3668779) |
단어가 매니저만 있기도 하고, 토너먼트를 설명하는 것이니 토너먼트는 빼는게 좋을 것 같습니다.
```suggestion
| 매니저 | ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578), ::{ flag=US }:: [ChillierPear](https://osu.ppy.sh/users/9501251), ::{ flag=BR }:: [LeoFLT](https://osu.ppy.sh/users/3668779) |
```

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +| 맵풀 플레이테스터 | ::{ flag=US }:: [\-Arko](https://osu.ppy.sh/users/8802914), ::{ flag=US }:: [chezbananas](https://osu.ppy.sh/users/7941423), ::{ flag=US }:: [fieryrage](https://osu.ppy.sh/users/3533958
이건 그냥 무시하셔도 됩니다만, 테스트플레이어가 한국쪽에는 더 친숙하지 않나 싶네요.
어디까지나 의견이니,원문 따라가시려면 무시하셔도 좋습니다.

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +| 커스텀 매퍼 | ::{ flag=GB }:: [\-Mo\-](https://osu.ppy.sh/users/2202163), ::{ flag=US }:: [Aeril](https://osu.ppy.sh/users/4334976), ::{ flag=GB }:: [Aistre](https://osu.ppy.sh/users/4879380), ::{ flag=
커스텀이라는 단어가 없으므로 매퍼가 맞지 않나 싶습니다.
```suggestion
| 매퍼 | ::{ flag=GB }:: [\-Mo\-](https://osu.ppy.sh/users/2202163), ::{ flag=US }:: [Aeril](https://osu.ppy.sh/users/4334976), ::{ flag=GB }:: [Aistre](https://osu.ppy.sh/users/4879380), ::{ flag=CA }:: [alden](https://osu.ppy.sh/users/3545323), ::{ flag=GB }:: [Altai](https://osu.ppy.sh/users/5745865), ::{ flag=RU }:: [Alvearia](https://osu.ppy.sh/users/6248691), ::{ flag=US }:: [Astronic](https://osu.ppy.sh/users/9320502), ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578), ::{ flag=NO }:: [BarkingMadDog](https://osu.ppy.sh/users/3475189), ::{ flag=US }:: [Bloxi](https://osu.ppy.sh/users/9022451), ::{ flag=GB }:: [CallieCube](https://osu.ppy.sh/users/7535045), ::{ flag=US }:: [Camo](https://osu.ppy.sh/users/5194391), ::{ flag=US }:: [captin1](https://osu.ppy.sh/users/689997), ::{ flag=KR }:: [Cellina](https://osu.ppy.sh/users/2490770), ::{ flag=HK }:: [Chaoslitz](https://osu.ppy.sh/users/3621552), ::{ flag=BR }:: [Dada](https://osu.ppy.sh/users/9119507), ::{ flag=BR }:: [dasdwqdf](https://osu.ppy.sh/users/5403374), ::{ flag=JP }:: [Delis](https://osu.ppy.sh/users/1603923), ::{ flag=GB }:: [DeviousPanda](https://osu.ppy.sh/users/4966334), ::{ flag=KR }:: [Down](https://osu.ppy.sh/users/4694602), ::{ flag=CN }:: [Elayue](https://osu.ppy.sh/users/6400861), ::{ flag=US }:: [Elcheer](https://osu.ppy.sh/users/4420014), ::{ flag=AU }:: [elicz1](https://osu.ppy.sh/users/8039342), ::{ flag=PL }:: [fartownik](https://osu.ppy.sh/users/56917), ::{ flag=CA }:: [Feiri](https://osu.ppy.sh/users/3214844), ::{ flag=RU }:: [fergas](https://osu.ppy.sh/users/3144542), ::{ flag=PH }:: [flake](https://osu.ppy.sh/users/7627157), ::{ flag=MX }:: [funny](https://osu.ppy.sh/users/8473573), ::{ flag=CN }:: [Garden](https://osu.ppy.sh/users/2849992), ::{ flag=US }:: [Halfslashed](https://osu.ppy.sh/users/4598899), ::{ flag=FR }:: [Halgoh](https://osu.ppy.sh/users/4109923), ::{ flag=SG }:: [hehe](https://osu.ppy.sh/users/2123087), ::{ flag=EE }:: [iljaaz](https://osu.ppy.sh/users/8501291), ::{ flag=FR }:: [IsomirDiAngelo](https://osu.ppy.sh/users/7715620), ::{ flag=US }:: [ItsWinter](https://osu.ppy.sh/users/6381153), ::{ flag=US }:: [JeZag](https://osu.ppy.sh/users/3087506), ::{ flag=CA }:: [jonathanlfj](https://osu.ppy.sh/users/270377), ::{ flag=CA }:: [KKipalt](https://osu.ppy.sh/users/6889573), ::{ flag=TW }:: [knowledgeking](https://osu.ppy.sh/users/8022517), ::{ flag=BR }:: [kowari](https://osu.ppy.sh/users/5404892), ::{ flag=CA }:: [ktgster](https://osu.ppy.sh/users/53378), ::{ flag=US }:: [Kurashina Asuka](https://osu.ppy.sh/users/7476493), ::{ flag=KR }:: [Luscent](https://osu.ppy.sh/users/2688581), ::{ flag=BR }:: [maot](https://osu.ppy.sh/users/3914271), ::{ flag=AR }:: [Megafan](https://osu.ppy.sh/users/6632605), ::{ flag=DK }:: [melon boy](https://osu.ppy.sh/users/3053382), ::{ flag=NZ }:: [moph](https://osu.ppy.sh/users/2233878), ::{ flag=DE }:: [Mordred](https://osu.ppy.sh/users/7265097), ::{ flag=KR }:: [Nakagawa\-Kanon](https://osu.ppy.sh/users/87065), ::{ flag=US }:: [Nathan](https://osu.ppy.sh/users/4785223), ::{ flag=BR }:: [Net0](https://osu.ppy.sh/users/5099768), ::{ flag=TR }:: [Nymphe](https://osu.ppy.sh/users/10507407), ::{ flag=HK }:: [Petal](https://osu.ppy.sh/users/7354729), ::{ flag=RU }:: [piroshki](https://osu.ppy.sh/users/7645522), ::{ flag=FR }:: [Raijodo](https://osu.ppy.sh/users/13400075), ::{ flag=FR }:: [Realazy](https://osu.ppy.sh/users/918297), ::{ flag=CN }:: [Ryuusei Aika](https://osu.ppy.sh/users/7777875), ::{ flag=JP }:: [Satellite](https://osu.ppy.sh/users/1661227), ::{ flag=CA }:: [Serenhaide](https://osu.ppy.sh/users/10466315), ::{ flag=LT }:: [Strategas](https://osu.ppy.sh/users/2971837), ::{ flag=US }:: [toybot](https://osu.ppy.sh/users/2848604), ::{ flag=FI }:: [verychill](https://osu.ppy.sh/users/10132936), ::{ flag=PL }:: [Zelq](https://osu.ppy.sh/users/8953955) |
```

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +## 포디엄
podium 영영사전과 예문을 보니 *시상대* 로도 치환이 가능할 것 같습니다.
```suggestion
## 시상대
```

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +    - 채팅 규칙을 위반하면 침묵이 발생할 수 있습니다. 침묵된 플레이어는 멀티플레이 매치에 참가할 수 없으며, 해당 처벌 기간동안 교체되어야 합니다.
silence 는 *사일런스* 로 번역이 된 선례가 있죠.
```suggestion
    - 채팅 규칙을 위반하면 사일런스가 발생할 수 있습니다. 사일런스된 플레이어는 멀티플레이 매치에 참가할 수 없으며, 해당 처벌 기간동안 교체되어야 합니다.
```

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +2. 각 맵풀은 [No Mod](/wiki/Gameplay/Game_modifier#nomod), [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock), [Double Time](/wiki/Gameplay/Game_modifier/D
본문을 따라가려면 이게 맞지 않나 싶네요.
```suggestion
2. 각 맵풀은 [No Mod](/wiki/Gameplay/Game_modifier#nomod), [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock), [Double Time](/wiki/Gameplay/Game_modifier/Double_Time), [FreeMod](/wiki/Gameplay/Game_modifier#freemod)의 5개 모드로 구성되어 있습니다.
```

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +2. 맵풀에는 No Mod, [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock), [Double Time](/wiki/Gameplay/Game_modifier/Double_Time)이 포함됩니다. 프리모드는 해당 스테이지에선 존재하
```suggestion
2. 맵풀에는 No Mod, [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock), [Double Time](/wiki/Gameplay/Game_modifier/Double_Time) 4개의 모드가 포함됩니다. 프리모드는 해당 스테이지에선 존재하지 않습니다.
```

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +   - 쿼터파이널, 세미파이널, 파이널, 그랜드 파이널: 20개의 비트맵
퀄파랑 32 16의 *맵풀* 을 비트맵으로 교체하는게 맞아 보입니다. 맵풀이라고 이야기하진 않았으니까요.

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +4. 경기 일정은 토너먼트 매니저가 관리하게 됩니다. 일정은 스테이지 첫 경기전 일요일에 공개되며, 토너먼트 매니저는 플레이어들의 시간대를 존중하는 스케쥴을 할려고 노력할 것입니다.
맞춤법 오류
```suggestion
4. 경기 일정은 토너먼트 매니저가 관리하게 됩니다. 일정은 스테이지 첫 경기전 일요일에 공개되며, 토너먼트 매니저는 플레이어들의 시간대를 존중하는 스케줄을 할려고 노력할 것입니다.
```

2023-09-20 00:32 UTC, Sitoria commented on wiki/Tournaments/OWC/2022/ko.md
> +6. 캡틴은 팀이 가능한지에 대해 확인해야할 책임이 있습니다.
맞춤법 오류
```suggestion
6. 캡틴은 팀이 가능한지에 대해 확인해야 할 책임이 있습니다.
```

2023-09-20 05:19 UTC, Chronicler01 commented on wiki/Tournaments/OWC/2022/ko.md
> +| 맵풀 플레이테스터 | ::{ flag=US }:: [\-Arko](https://osu.ppy.sh/users/8802914), ::{ flag=US }:: [chezbananas](https://osu.ppy.sh/users/7941423), ::{ flag=US }:: [fieryrage](https://osu.ppy.sh/users/3533958
한국쪽에서도 플레이테스터(플테), 테스트플레이어 둘다 쓰는 표현입니다

2023-09-20 05:22 UTC, Chronicler01 commented on wiki/Tournaments/OWC/2022/ko.md
> +| 커스텀 매퍼 | ::{ flag=GB }:: [\-Mo\-](https://osu.ppy.sh/users/2202163), ::{ flag=US }:: [Aeril](https://osu.ppy.sh/users/4334976), ::{ flag=GB }:: [Aistre](https://osu.ppy.sh/users/4879380), ::{ flag=
그 대회에 사용할 커스텀 맵을 매핑하는 사람을 외국권에서 mapper라고 표시하긴 합니다

2023-09-20 05:25 UTC, Chronicler01 commented on wiki/Tournaments/OWC/2022/ko.md
> +   - 쿼터파이널, 세미파이널, 파이널, 그랜드 파이널: 20개의 비트맵
맵풀에 있는 비트맵 개수를 세는데 ~개의 비트맵 표현은 잘 쓰지 않습니다. 물론 공식대회의 위키다보니 원문표기를 해야하나 한국에서 많이 사용하는 표현을 써야하나의 의문점이 있긴합니다

2023-09-20 05:35 UTC, Chronicler01 commented on wiki/Tournaments/OWC/2022/ko.md
> +2. 각 맵풀은 [No Mod](/wiki/Gameplay/Game_modifier#nomod), [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock), [Double Time](/wiki/Gameplay/Game_modifier/D
내용 전달상 문제없습니다

2023-09-20 06:10 UTC, Sitoria approved these changes
Wait for @sylphi 's 2nd Review
dont merge it thx

2023-09-27 13:46 UTC, TicClick approved these changes

2023-09-27 13:53 UTC, merged