Add `GB Cup 2023 Autumn` wiki articles
ppy/osu-wiki pull request #10075
Opened 2023-09-21 13:45 UTC by HanHan3z

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-21 15:17 UTC, yobrevelc approved these changes

2023-09-22 18:41 UTC, Walavouchey requested changes
partial review

- please don't use code blocks to format random numbers and text. that's not what they're intended for

2023-09-22 18:41 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +2. Following the drafting phase, a swiss stage will be played in both zones, called the *Regular stage*. There will be `16` teams advance in total, and the others get eliminated from the tournament.
```suggestion
2. Following the drafting phase, a Swiss stage will be played in both zones, called the *regular stage*. 16 teams will advance in total, and the others get eliminated from the tournament.
```

2023-09-22 18:41 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +3. Following the Regular stage, the Elimination stage will be played, called *Playoffs*. Top 8 teams in regular stage will get into winner bracket, other teams will get into loser bracket.
```suggestion
3. Following the regular stage, the elimination stage will be played, called *playoffs*. The top 8 teams from the regular stage will advance to a winner bracket, other teams will get into loser bracket.
```

2023-09-22 18:41 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +4. All the losing team in loser bracket will be eliminated from the tournament, the last team will be the winner.
```suggestion
4. All losing teams in the loser bracket will be eliminated from the tournament and the last team will be the winner.
```

2023-09-22 19:18 UTC, HanHan3z commented
All mentioned errors have been fixed.

2023-09-23 18:08 UTC, Walavouchey requested changes

2023-09-23 18:08 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - The tactical timeout may be called on a tiebreaker, provided that both teams' captains agree to it.
this rule conflicts with rule 6. please remove one of them and adjust accordingly

2023-09-23 18:08 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - This might change.
```suggestion
   - Qualifiers will use a separate mappool.
   - Regular stage round 1 and round 2 use mappool #1.
   - Regular stage round 3 and round 4 use mappool #2.
   - Round of 16 and Quarterfinals use mappool #3.
   - Semifinals and Finals use mappool #4.
```

2023-09-23 18:08 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Mappool \#3 & \#4: 17 beatmaps.
```suggestion
   - Mappool #1 & #2: 15 beatmaps
   - Mappool #3 & #4: 17 beatmaps.
```

2023-09-23 18:08 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - **Players that don't pick a time slot by Wednesday, 11 October 23:59 UTC+8 will be disqualified from the competition.**
```suggestion
   - **Players that do not pick a time slot by Wednesday, 11 October 23:59 UTC+8 will be disqualified from the competition.**
```

2023-09-23 18:08 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +     - ... Unless its absolutely necessary, **both** teams request and agree to it, and staff avaliable.
already mentioned in rule 3 above

```suggestion
```

2023-09-23 18:08 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Rescheduling a match to a weekday is only permitted if **both** teams request and agree to it.
```suggestion
   - Rescheduling a match to a weekday is only permitted if absolutely necessary, **both** teams request and agree to it, and staff members are available.
```

2023-09-23 18:10 UTC, Walavouchey requested changes

2023-09-23 18:10 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +2. 选秀结束后，两个赛区的队伍将会分别进行四轮瑞士轮*预选赛*，以决出总计 `16` 支队伍进入淘汰赛，其他队伍将被淘汰。
code blocks shouldn't be used like this

```suggestion
2. 选秀结束后，两个赛区的队伍将会分别进行四轮瑞士轮*预选赛*，以决出总计 16 支队伍进入淘汰赛，其他队伍将被淘汰。
```

2023-09-23 18:10 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +   - 默认名称是`Team {X}`, `{X}`是队长用户名的缩写。
```suggestion
   - 默认名称是 `Team {X}`, `{X}` 是队长用户名的缩写。
```

2023-09-23 18:10 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +   - 两个赛区将分别进行瑞士轮预选赛的比赛，决出指定数量的队伍进入淘汰赛，每个赛区进入淘汰赛的队伍数量由报名人数决定，两个赛区合计固定为 `16` 支队伍进入淘汰赛。
```suggestion
   - 两个赛区将分别进行瑞士轮预选赛的比赛，决出指定数量的队伍进入淘汰赛，每个赛区进入淘汰赛的队伍数量由报名人数决定，两个赛区合计固定为 16 支队伍进入淘汰赛。
```

2023-09-23 18:13 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +**GBC 2023 秋季赛** (***GB 杯 2023 秋季赛***) 是由 GB 组织主办的 3v3 队长选秀制 osu!mania4k 项目赛事。本届比赛是 GBC 系列赛事的第四届正式比赛。
```suggestion
**GBC 2023 秋季赛** (***GB 杯 2023 秋季赛***) 是由 GB 组织主办的 3v3 队长选秀制 osu!mania 4K 项目赛事。本届比赛是 GBC 系列赛事的第四届正式比赛。
```

2023-09-23 18:23 UTC, HanHan3z commented
All mentioned errors have been fixed again.

2023-09-23 18:46 UTC, HanHan3z commented
All mentioned errors have been fixed again.

2023-09-23 19:02 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +| Position | Member(s) |
should be translated

2023-09-23 19:25 UTC, RushFTK requested changes
Quickly reviewed requested by @Walavouchey , semmed fines for me in most cases.

2023-09-23 19:25 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +6. If the captain picks a player, the pick time still has to elapse before the next captain's turn starts, meaning each phase will take 16 minutes.
Untranslated.

2023-09-23 19:25 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Captains are allowed to conduct and coordinate "tryouts", tests to gauge player aptitude, on their own terms.
Untranslated, but dosen't matter i guess. this is just an reminder for captains.

2023-09-23 19:25 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Only players who have already played in the match can be banned.
Untranslated, is this rules changed?

2023-09-23 19:27 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +6. If the captain picks a player, the pick time still has to elapse before the next captain's turn starts, meaning each phase will take 16 minutes.
fixed in 689aebb

2023-09-23 19:27 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Captains are allowed to conduct and coordinate "tryouts", tests to gauge player aptitude, on their own terms.
fixed in 689aebb

2023-09-23 19:39 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Only players who have already played in the match can be banned.
fixed on [3704f72](https://github.com/ppy/osu-wiki/pull/10075/commits/3704f7262ef29ea324bb6e985a23fd11d3930204)

2023-09-23 19:40 UTC, RushFTK approved these changes
All inconsist translation have been fixed now

2023-09-23 20:02 UTC, Walavouchey commented
force-pushed to condense ~40 commits

2023-09-23 20:05 UTC, Walavouchey approved these changes

2023-09-23 20:07 UTC, merged