[ZH] Add `Skinning/osu!`, `osu!catch`, `Sounds`, `Skinner`, `skin.ini`
ppy/osu-wiki pull request #10085
Opened 2023-09-23 03:37 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-23 03:47 UTC, CloneWith commented on wiki/Skinning/Skinner/zh.md
> +# 皮肤制作者
不知道中文论坛上有没有别的称号更适合？

2023-09-23 03:47 UTC, CloneWith commented on wiki/Skinning/skin.ini/zh.md
> +    - 对于 DP 模式，两个舞台间的正中央处用于决定位置。
意味不明

2023-09-23 18:52 UTC, YumeMuzi commented on wiki/Skinning/Skinner/zh.md
> +# 皮肤制作者
就这个吧 this is fine

2023-09-23 18:54 UTC, YumeMuzi commented on wiki/Skinning/skin.ini/zh.md
> +    - 对于 DP 模式，两个舞台间的正中央处用于决定位置。
那个是 IIDX 的 Double Play，这个是决定特殊轨道的位置的，意思是，DP 模式固定是 1P 的特殊轨道在左，2P 的特殊轨在右，这个参数**没有作用**。

2023-09-23 18:59 UTC, YumeMuzi commented on wiki/Skinning/skin.ini/zh.md
> +    - 对于 DP 模式，两个舞台间的正中央处用于决定位置。
the centre between the stages就是指，游戏区域中轴线（osu里是 x=256 osu!px）用于区分内外（这里就是内）

2023-09-23 19:13 UTC, YumeMuzi requested changes

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/skin.ini/zh.md
> +  - 问题：最后一个串应该使用什么颜色？
```suggestion
  - 问题：应该使用什么颜色作为最后一个连击色？
```

以下同理。而且 combo 不应该翻译为串。

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/skin.ini/zh.md
> +  - 问题：总是播放hitnormal 音效吗？
```suggestion
  - 问题：总是播放 hitnormal 音效吗？
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/skin.ini/zh.md
> +    - 此参数只会影响连击提示音效，不会影响连击里程碑。
```suggestion
    - 此参数只会影响完成一组连击后的提示音效，不会影响连击达到一定次数会播放的音效。
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/skin.ini/zh.md
> +  - 问题：不活跃面板的文字应该使用什么颜色？
```suggestion
  - 问题：已选择面板的文字应该使用什么颜色？
  - 值：*RGB*
  - 默认值：`0,0,0`
- `SongSelectInactiveText:`
  - 问题：未选择面板的文字应该使用什么颜色？
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/skin.ini/zh.md
> +    - `StageHint`、`LightingN` 和 `LightingL` 都会绘制在此位置
```suggestion
    - `StageHint`、`LightingN` 和 `LightingL` 都会绘制在此位置。
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![是][true] | ![是][true] |（不同） | 顶部左侧 | 最大宽度：120px |
```suggestion
| 所有 | ![是][true] | ![是][true] | （不同） | 顶部左侧 | 最大宽度：120px |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | - |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | - |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 5x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 5x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 12x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 12x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] |（不同） |（不同） | 10x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | （不同） | （不同） | 10x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 普通模式 |（不同） | 34x40 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 普通模式 | （不同） | 34x40 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 相乘模式 |（不同） | 11x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 相乘模式 | （不同） | 11x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 相乘模式 |（不同） | 11x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 相乘模式 | （不同） | 11x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 相乘模式 |（不同） | 11x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 相乘模式 | （不同） | 11x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 相乘模式 |（不同） | 11x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 相乘模式 | （不同） | 11x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 相乘模式 |（不同） | 11x14 |
```suggestion
| 所有 | ![否][false] | ![是][true] | 相乘模式 | （不同） | 11x14 |
```

2023-09-23 19:13 UTC, YumeMuzi commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 相乘模式 |（不同） | 11x14 |
算了，你自己搜索匹配替换吧。所有（不同）左侧少一个空格。

2023-09-24 06:58 UTC, CloneWith commented on wiki/Skinning/Interface/zh.md
> +| 所有 | ![否][false] | ![是][true] | 相乘模式 |（不同） | 11x14 |
这个comment似乎是在我重新修改过之后，ci已经指出来了。

![image](https://github.com/ppy/osu-wiki/assets/110881926/21ca04b5-e354-4627-b841-0d6f4ab6ff5b)

不过还是谢谢您

2023-09-24 07:00 UTC, CloneWith commented on wiki/Skinning/skin.ini/zh.md
> +    - `StageHint`、`LightingN` 和 `LightingL` 都会绘制在此位置
这里的标点，英文原文本来就不统一，有的地方加有的不加（

我先改过来吧

2023-09-24 17:54 UTC, YumeMuzi approved these changes

2023-09-24 20:48 UTC, TicClick approved these changes

2023-09-24 20:50 UTC, merged