[ES] Clean up `Reporting bad behaviour` and `Silence`
ppy/osu-wiki pull request #10087
Opened 2023-09-23 11:05 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-14 15:15 UTC, agatemosu commented
@UnknownOsu can you say something?

2023-10-14 17:28 UTC, UnknownOsu requested changes

2023-10-14 17:28 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/es.md
> +osu! tiene [un equipo de moderadores](/wiki/People/Global_Moderation_Team) que se adhieren a mantener el juego y su ecosistema limpios y seguros. Si observas una conducta que infringe las reglas o es
```suggestion
osu! tiene [un equipo de moderadores](/wiki/People/Global_Moderation_Team) que se adhieren a mantener el juego y su ecosistema limpios y seguros. Si observas una conducta que infringe las reglas o es contenido inapropiado, repórtala utilizando uno de los métodos que se describen a continuación. Alternativamente, puedes comunicarte directamente con cualquiera de los moderadores en línea si tu reporte no se manejó correctamente dentro de un período de tiempo razonable, hazlo solo como último recurso.
```

2023-10-14 17:30 UTC, UnknownOsu commented
Puede que también la [foto de reportar](https://i.imgur.com/muWO2oA.png) en el chat

2023-10-15 15:49 UTC, TicClick approved these changes

2023-10-15 15:52 UTC, merged