Explain what `Hush-Hush (Expert)` category means in `Medals`
ppy/osu-wiki pull request #10112
Opened 2023-09-27 21:07 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-09-27 21:27 UTC, Walavouchey requested changes

2023-09-27 21:27 UTC, Walavouchey commented on wiki/Medals/en.md
> +Hush-Hush also has its sub-category called "Hush-Hush (Expert)" the difference of which is medals in it don't allow any [difficulty reduction](/wiki/Gameplay/Game_modifier#difficulty-reduction) or [s
```suggestion
Hush-Hush also has its sub-category called "Hush-Hush (Expert)". The difference is that medals in it do not allow usage of any [difficulty reduction](/wiki/Gameplay/Game_modifier#difficulty-reduction) or [special](/wiki/Gameplay/Game_modifier#special) mods.
```

2023-09-28 10:33 UTC, Walavouchey approved these changes

2023-09-28 10:34 UTC, merged

2023-09-28 10:35 UTC, peppy commented
Seems pretty arbitrary to have this separation for conditions which are also applied on many other medals.

2023-09-28 10:38 UTC, chromb commented
> Seems pretty arbitrary to have this separation for conditions which are also applied on many other medals.

From what i know, all of the hush-hush medals that have that requirement are there, can't think of any exceptions off the top of my head.

2023-09-28 10:43 UTC, peppy commented
I meant non-hush-hush cases.

2023-09-28 12:00 UTC, Walavouchey commented
this just explains what the seperation for "expert" hush-hush medals on the site means. for other medals, whether difficulty reduction mods are allowed is indicated by their descriptions on the site