[ZH] Update `Skin.ini`, `Help centre/Beatmapping`, `Reporting bad behaviour` and sub articles
ppy/osu-wiki pull request #10125
Opened 2023-09-30 20:37 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-01 07:46 UTC, CloneWith requested changes

2023-10-01 07:46 UTC, CloneWith commented on wiki/Help_centre/Beatmapping/zh.md
> +## 我的谱面/内容被其他玩家在未经我允许的前提下重新上传了，我想要删除侵权的拷贝！ {id=report-content-dmca}
```suggestion
## 我的谱面/内容被其他玩家在未经我允许的前提下重新上传了，我要求删除侵权的拷贝！ {id=report-content-dmca}
```

“想要删除”偏向于原作者主动去删除内容，但是这里只强调了作者需要内容被删掉的结果。个人认为用“要求”较为合适。

2023-10-01 07:46 UTC, CloneWith commented on wiki/Help_centre/Beatmapping/zh.md
> +如果原作者想要维权，则任何未经原作者允许重新上传的内容都是侵权行为。为了确保诉讼的程序公正，移除侵权的文件要求需要走合法的程序，
```suggestion
如果原作者愿意，则任何未经原作者允许重新上传的内容，都可认定为侵权。为了确保诉讼的程序公正，请求移除侵权的文件需要走合法的程序。
```
原文中原作者愿意认为的内容大体指“未经允许的内容是侵权”这件事。如果没有认定这个前提，也就没有维权的必要。

2023-10-01 07:46 UTC, CloneWith commented on wiki/Reporting_bad_behaviour/Abuse/zh.md
> +如果过了一段时间，贴子还没有被删除，请向 [abuse@ppy.sh](mailto:abuse@ppy.sh) 举报，并且尽可能详细的形容事件。
```suggestion
如果过了一段时间，贴子还没有被删除，请向 [abuse@ppy.sh](mailto:abuse@ppy.sh) 举报，并且尽可能详细的叙述事件。
```

2023-10-01 07:46 UTC, CloneWith commented on wiki/Reporting_bad_behaviour/zh.md
> +在聊天中出现的不当行为是最常见的侵权行为。要举报它，最好在出现侵权消息的频道内，使用 [`!report`](https://osu.ppy.sh/community/forums/topics/34843) 命令。不要感到压力：如果你的举报命令是 `!report` 开头，那么这条举报消息**仅对频道管理员可见**，频道内的其他人都无法看见。如果你仍然担心举报信息会泄露，也可以按照以下的示意，
```suggestion
在聊天中出现的不当行为是最常见的侵权行为。要举报它，最好在出现侵权消息的频道内，使用 [`!report`](https://osu.ppy.sh/community/forums/topics/34843) 命令。不要觉得有压力：如果你的消息以 `!report` 带空格开头，那么这条举报消息**仅对频道管理员可见**，频道内的其他人都无法看见。如果你仍然担心举报信息会泄露，也可以按如下步骤，使用[游戏内覆盖层](#游戏内覆盖层)举报。
```

2023-10-01 07:46 UTC, CloneWith commented on wiki/Reporting_bad_behaviour/zh.md
> +聊天不当行为是最常见的侵权行为。要报告它，请使用！报告命令，最好是在发生侵权的渠道。不要感到压力：如果你的信息开头是！报告和一个空间，它只对主持人可见，聊天中没有其他人。如果您仍然担心，也可以通过游戏内覆盖使用报告功能，如下所示。
冗余行🤔

2023-10-01 07:46 UTC, CloneWith commented on wiki/Reporting_bad_behaviour/zh.md
> +举报命令语法有两种格式：
这里写作“这条命令有两种写法”即可

2023-10-01 07:46 UTC, CloneWith commented on wiki/Reporting_bad_behaviour/zh.md
> +1. 在成绩上悬停光标。
```suggestion
1. 将光标悬停在成绩上。
```
同 L68，应该是表达方式差异。

2023-10-01 07:46 UTC, CloneWith commented on wiki/Reporting_bad_behaviour/zh.md
> +2. 在成绩右侧，按下三个竖直排列点的按钮，并且选择 `举报成绩`。
```suggestion
2. 按下成绩右侧三个竖直排列点的按钮，并且选择 `举报成绩`。
```
同第 100 行

2023-10-01 12:40 UTC, YumeMuzi commented on wiki/Reporting_bad_behaviour/zh.md
> +举报命令语法有两种格式：
按格式输入命令

2023-10-01 12:49 UTC, CloneWith approved these changes

2023-10-02 12:59 UTC, TicClick approved these changes

2023-10-02 13:08 UTC, merged