[DE] Update `People/osu! team`
ppy/osu-wiki pull request #10129
Opened 2023-10-02 12:00 UTC by The-Last-Cookie

I hope there is nothing that I have overlooked. [The diff](https://osu.wiki/status/diff-de-wiki-People-osu!_team) is quite messy.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-02 12:10 UTC, The-Last-Cookie commented on wiki/People/osu!_team/de.md
> +::{ flag=PL }:: [spaceman_atlas](https://osu.ppy.sh/users/3035836) | osu!-Entwickler |
```suggestion
| ::{ flag=PL }:: [spaceman_atlas](https://osu.ppy.sh/users/3035836) | osu!-Entwickler |
```

2023-10-03 18:28 UTC, respektive requested changes

2023-10-03 18:28 UTC, respektive commented on wiki/People/osu!_team/de.md
> +| ::{ flag=US }:: [ChillierPear](https://osu.ppy.sh/users/9501251) | Organisator und Verwalter des [World Cups](/wiki/Tournaments#offizielle-world-cups) |
```suggestion
| ::{ flag=US }:: [ChillierPear](https://osu.ppy.sh/users/9501251) | Organisator und Verwalter des [World Cups](/wiki/Tournaments#offizielle-world-cups) |
| ::{ flag=US }:: [Death](https://osu.ppy.sh/users/3242450) | [Moderator](/wiki/People/Global_Moderation_Team), technische Unterstützung |
```

2023-10-03 18:28 UTC, respektive commented on wiki/People/osu!_team/de.md
> +| ::{ flag=AU }:: [nekodex](https://osu.ppy.sh/users/102) |  osu!web Entwickler, [osu! Featured Artist](https://osu.ppy.sh/beatmaps/artists/1) |
```suggestion
| ::{ flag=AU }:: [nekodex](https://osu.ppy.sh/users/102) |  osu!web Entwickler, [Featured Artist](https://osu.ppy.sh/beatmaps/artists/1) |
```
English version also dropped the `osu!`

2023-10-04 17:54 UTC, respektive approved these changes
looks good now

2023-10-06 17:06 UTC, merged