[TR] Add `Ranking`
ppy/osu-wiki pull request #10152
Opened 2023-10-08 20:09 UTC by SStoney6378

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-08 20:19 UTC, ubinici commented
Please refrain from translating stub articles in the future. There are many proper ones that are either outdated or unavailable. It would be a better practice to handle the outdated ones before delving into the other ones.

I'll drop a review at a later time, please do not merge/close the PR by then.

2023-10-08 20:32 UTC, TicClick commented
> Please refrain from translating stub articles in the future

while it's generally better to translate completed articles first, we have A LOT of stubs. realistically speaking, it's going to be a long time until all of them are fleshed out, so maybe some of stub translations are worth working on (I would advise against translating anything with `needs_cleanup: true` though)

2023-10-08 20:40 UTC, WindowsMeosu requested changes

2023-10-08 20:40 UTC, WindowsMeosu commented on wiki/Ranking/tr.md
> +etiketler:
```suggestion
tags:
```

2023-12-06 07:49 UTC, TicClick approved these changes
merging (no native review for one week or longer)

2023-12-06 07:51 UTC, merged