[ES] Native review of `Circle size`
ppy/osu-wiki pull request #10179
Opened 2023-10-15 15:50 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-18 05:16 UTC, UnknownOsu requested changes

2023-10-18 05:16 UTC, UnknownOsu commented on wiki/Beatmap/Circle_size/es.md
> +*Para conocer las regulaciones relativas al tamaño del circulo, véase: [Criterios de clasificación](/wiki/Ranking_criteria)*
```suggestion
*Para conocer las regulaciones relativas al tamaño del círculo, véase: [Criterios de clasificación](/wiki/Ranking_criteria)*
```

2023-10-18 05:16 UTC, UnknownOsu commented on wiki/Beatmap/Circle_size/es.md
> +El **tamaña del circulo** (***CS***) es una configuración de dificultad de un [beatmap](/wiki/Beatmap) que afecta el tamaño de los [objetos](/wiki/Gameplay/Hit_object). Los valores del tamaño del cír
```suggestion
El **tamaña del círculo** (***CS***) es una configuración de dificultad de un [beatmap](/wiki/Beatmap) que afecta el tamaño de los [objetos](/wiki/Gameplay/Hit_object). Los valores del tamaño del círculo varían de 0 a 10, pero solo se pueden elegir valores de 2 a 7 en el [editor de beatmaps](/wiki/Client/Beatmap_editor). Se pueden usar otros valores editando manualmente el [archivo `.osu`](/wiki/Client/File_formats/osu_(file_format)) de un mapa.
```

2023-10-19 20:55 UTC, TicClick approved these changes

2023-10-19 20:58 UTC, merged