[ES] Clean up `Genre and language`
ppy/osu-wiki pull request #10186
Opened 2023-10-15 17:53 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-30 07:49 UTC, cl8n commented
was this reviewed by someone off-site? i see that box was originally checked

2023-10-30 17:01 UTC, UnknownOsu requested changes

2023-10-30 21:03 UTC, UnknownOsu commented on wiki/History_of_osu!/2007/es.md
> +El menú principal fue actualizado con un nuevo diseño, y el editor recibió un montón de nuevas funcionalidades, incluyendo un soporte para copiar y pegar. Se agregaron la pestaña de menú y el menú co
```suggestion
El menú principal fue actualizado con un nuevo diseño, y el editor recibió un montón de nuevas funcionalidades, incluyendo un soporte para copiar y pegar. Se agregaron la pestaña de menú y el menú contextual, lo que hace que las funciones del editor sean más accesibles que antes; los sliders fueron más ampliamente compatibles con [tics](/wiki/Gameplay/Hit_object/Slider/Slider_tick) presentes; [apilamiento](/wiki/Beatmapping/Mapping_techniques/Stack) de los [círculos](/wiki/Gameplay/Hit_object/Hit_circle) estaban presentes; las puntuaciones locales más altas recibieron un mejor soporte; y el formato de archivo `.osu` se revisó y renovó por completo, pero incluyó la conversión de archivos más antiguos al nuevo formato.
```

2023-10-30 21:14 UTC, UnknownOsu commented on wiki/osu!supporter/es.md
>  **osu!supporter** (o la ***etiqueta osu!supporter***) es un título temporal dado a los jugadores que apoyan a osu!, de manera voluntaria, con una donación monetaria para ayudarlo a crecer. Los suppor
```suggestion
**osu!supporter** (o la ***etiqueta de osu!supporter***) es un título temporal dado a los jugadores que apoyan a osu!, de manera voluntaria, con una donación monetaria para ayudarlo a crecer. Los supporters reciben un puñado de beneficios cosméticos y técnicos, la mayoría solo se presentan cuando el título está presente. Las características extras de osu!supporter no dan ningún tipo de ventaja en el juego, rendimiento o puntuación, y nunca lo hará.
```

2023-10-30 21:15 UTC, UnknownOsu commented on wiki/osu!supporter/es.md
>  La etiqueta osu!supporter podrá ser obtenida desde la [página de la tienda de osu!supporter](https://osu.ppy.sh/store/products/supporter-tag).
```suggestion
La etiqueta de osu!supporter podrá ser obtenida desde la [página de la tienda de osu!supporter](https://osu.ppy.sh/store/products/supporter-tag).
```

2023-11-05 01:59 UTC, cl8n approved these changes

2023-11-05 02:01 UTC, merged