[ES] Update Trivia in `Profile badge`
ppy/osu-wiki pull request #10184
Opened 2023-10-15 17:37 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-18 05:35 UTC, UnknownOsu requested changes

2023-10-18 05:35 UTC, UnknownOsu commented on wiki/Community/Profile_badge/es.md
>  En lugar de apilarlas horizontalmente en un contenedor que abarcaba toda la página, el antiguo sitio web apilaba las insignias verticalmente entre el nombre de usuario de un usuario y la bandera del
```suggestion
En lugar de apilarlas horizontalmente en un contenedor que abarcaba toda la página, el antiguo sitio web apilaba las insignias verticalmente entre el nombre del usuario y la bandera del país.
```

2023-10-18 05:36 UTC, UnknownOsu commented
También, en la línea 32 hay un punto de más al lado de `título`

2023-10-19 21:05 UTC, TicClick approved these changes

2023-10-19 21:06 UTC, merged