[DE] Add `Authentic Beatmap`
ppy/osu-wiki pull request #10199
Opened 2023-10-16 19:24 UTC by FreezyLemon

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-16 22:16 UTC, Deimosu requested changes

2023-10-16 22:16 UTC, Deimosu commented on wiki/Beatmap/Authentic/de.md
> +Eine **authentische [Beatmap](/wiki/Beatmap)** ahmt ein Level aus den [iNiS-Spielen](/wiki/iNiS_games) nach. Der Begriff kommt aus einer Zeit, zu der [Mapping](/wiki/Beatmapping) stark von iNiS inspi
```suggestion
Eine **authentische [Beatmap](/wiki/Beatmap)** ahmt ein Level aus den [iNiS-Spielen](/wiki/iNiS_games) nach. Der Begriff kommt aus einer Zeit, in der das [Mapping](/wiki/Beatmapping) stark von iNiS inspiriert war. Heutzutage hat der Begriff "authentisch" weniger Bedeutung, da Mapper sich nicht von den originalen Spielen, sondern von anderen Mappern inspirieren lassen.
```

2023-10-16 22:42 UTC, Deimosu approved these changes

2023-10-19 20:54 UTC, TicClick approved these changes

2023-10-19 20:56 UTC, merged