Update `Project Loved` with removal process
ppy/osu-wiki pull request #10209
Opened 2023-10-18 09:00 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-10-18 09:16 UTC, Walavouchey requested changes

2023-10-18 09:16 UTC, Walavouchey commented on wiki/Community/Project_Loved/en.md
> +Creators of said beatmaps are also able to request them to be removed from Loved category by reaching out to a Project Loved Team member or by posting in `#osu-loved` channel of the [osu! Discord ser
```suggestion
Creators of said beatmaps are also able to request them to be removed from the Loved category by reaching out to a [Project Loved Team](https://osu.ppy.sh/groups/31) member or by posting in `#osu-loved` channel of the [osu! Discord server](https://discord.gg/ppy). The removal process will take a minimum of 1 week and creator will receive a follow-up when it is finished.
```

2023-10-18 23:43 UTC, cl8n approved these changes
maybe in the wrong place but i cant find a better one without rewriting stuff.

2023-10-19 00:27 UTC, peppy approved these changes

2023-10-19 00:28 UTC, merged