[DE] Add `Background`
ppy/osu-wiki pull request #10200
Opened 2023-10-16 21:44 UTC by FreezyLemon

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-16 22:11 UTC, Deimosu requested changes

2023-10-16 22:11 UTC, Deimosu commented on wiki/Beatmap/Background/de.md
> +Hintergründe werden in der Beatmap-Auflistung, in der [Songauswahl](/wiki/Client/Interface#songauswahl) und beim Spielen angezeigt. Wenn die Schwierigkeitsstufen einer Beatmap unterschiedliche Hinter
```suggestion
Hintergründe werden in der Beatmap-Auflistung, in der [Songauswahl](/wiki/Client/Interface#songauswahl) und beim Spielen angezeigt. Wenn die Schwierigkeitsstufen einer Beatmap unterschiedliche Hintergründe haben, wird der Hintergrund von der Schwierigkeitsstufe mit der niedrigsten [`BeatmapID`](/wiki/Beatmap#identifizierung) gewählt und für die Beatmap-Auflistung und das [Beatmap-Karussell](/wiki/Client/Interface#beatmap-karussell) verwendet.
```

2023-10-16 22:11 UTC, Deimosu commented on wiki/Beatmap/Background/de.md
> +Bilder und Videos können als **Hintergrund** von Beatmaps verwendet werden. Wenn nur "bg" oder "background" geschrieben wird, ist üblicherweise ein Hintergrundbild gemeint.
```suggestion
Bilder und Videos können als **Hintergrund** für Beatmaps verwendet werden. Wenn nur "bg" oder "background" geschrieben wird, ist üblicherweise ein Hintergrundbild gemeint.
```

2023-10-16 22:42 UTC, Deimosu approved these changes

2023-10-19 17:15 UTC, The-Last-Cookie approved these changes

2023-10-19 20:53 UTC, TicClick approved these changes

2023-10-19 20:55 UTC, merged