[ES] Update `Developers`
ppy/osu-wiki pull request #10205
Opened 2023-10-17 21:05 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-18 06:13 UTC, UnknownOsu requested changes

2023-10-18 06:13 UTC, UnknownOsu commented on wiki/People/Developers/es.md
> +Los desarrolladores de osu! se pueden reconocer por sus títulos usuario rosados «osu!dev» o «osu!team», y su insignia de [grupo de usuarios](/wiki/People/User_group) que dice `DEV`.
```suggestion
Los desarrolladores de osu! se pueden reconocer por sus títulos de usuario rosados «osu!dev» u «osu!team», y su insignia de [grupo de usuarios](/wiki/People/User_group) que dice `DEV`.
```

2023-10-18 06:13 UTC, UnknownOsu commented on wiki/People/Developers/es.md
>  El esfuerzo de desarrollo de osu! está liderado por ::{ flag=AU }:: **[peppy](https://osu.ppy.sh/users/2)**, el creador de osu!.
```suggestion
El desarrollo de osu! está liderado por ::{ flag=AU }:: **[peppy](https://osu.ppy.sh/users/2)**, el creador de osu!.
```

2023-10-18 06:13 UTC, UnknownOsu commented on wiki/People/Developers/es.md
>  El esfuerzo de desarrollo de osu! está liderado por ::{ flag=AU }:: **[peppy](https://osu.ppy.sh/users/2)**, el creador de osu!.
Creo que en la línea `87` también quedaría bien quitar `los esfuerzos de` y cambiarlo por `abandonaron el desarrollo`

2023-10-22 20:54 UTC, agatemosu commented on wiki/People/Developers/es.md
>  El esfuerzo de desarrollo de osu! está liderado por ::{ flag=AU }:: **[peppy](https://osu.ppy.sh/users/2)**, el creador de osu!.
yo creo que está bien

2023-10-29 20:17 UTC, TicClick approved these changes

2023-10-29 20:19 UTC, merged