[ES] Add `Layer` and update all subarticles of `Music theory`
ppy/osu-wiki pull request #10219
Opened 2023-10-19 18:32 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-21 21:40 UTC, UnknownOsu requested changes

2023-10-21 21:40 UTC, UnknownOsu commented on wiki/Music_theory/Rhythm/es.md
> +El **ritmo** es «el patrón de sonido, silencio y énfasis en una canción».[^rhythm-ref] Al crear [beatmaps](/wiki/Beatmap), los mappers prestan atención a dónde aterrizan los sonidos en la música para
```suggestion
El **ritmo** es «el patrón de sonido, silencio y énfasis en una canción».[^rhythm-ref] Al crear [beatmaps](/wiki/Beatmap), los mappers prestan atención a la ubicación de los sonidos en la música para determinar dónde colocar los [objetos](/wiki/Gameplay/Hit_object) y los [hitsounds](/wiki/Beatmapping/Hitsound), con el fin de seguir el ritmo y enfatizar ciertas partes del mismo. Al ser un juego de ritmo, el ritmo es una parte intrínseca de cualquier beatmap en osu!.
```

2023-10-21 21:40 UTC, UnknownOsu commented on wiki/Music_theory/Syncopation/es.md
> +Algunos de los patrones de slider, como el primero, siguen la melodía del sintetizador que se sincopa contra las patadas de batería, aterrizando en marcas rojas de la línea de tiempo:
```suggestion
Algunos de los patrones de slider, como el primero, siguen la melodía del sintetizador que se sincopa con los golpes de la batería, aterrizando en marcas rojas de la línea de tiempo:
```

2023-10-21 21:40 UTC, UnknownOsu commented on wiki/Music_theory/Tempo/es.md
> +El **tiempo** se refiere a la velocidad de una canción. Suele medirse en **pulsos por minuto** (***PPM***), es decir, el número de [pulsos musicales enteros](/wiki/Music_theory/Beat) que hay en un mi
```suggestion
El **tempo** se refiere a la velocidad de una canción. Suele medirse en **pulsos por minuto** (***PPM***), es decir, el número de [pulsos musicales enteros](/wiki/Music_theory/Beat) que hay en un minuto de canción. Por ejemplo, un tempo de 60 pulsos por minuto significa un pulso por segundo, mientras que un tempo de 120 pulsos por minuto es el doble de rápido, lo que significa dos pulsos cada segundo. El tempo afecta directamente a muchos aspectos del juego, como la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity), o el [kiai time](/wiki/Gameplay/Kiai_time). Las páginas de información de los beatmaps muestran el tempo junto a un símbolo de [metrónomo](https://es.wikipedia.org/wiki/Metrónomo), un dispositivo utilizado por los músicos que ayuda a tocar con un pulso regular.
```

2023-10-21 21:40 UTC, UnknownOsu commented on wiki/Music_theory/Time_signature/es.md
> +Una **signatura de compás** es un término musical que define el número de [pulsoss](/wiki/Music_theory/Beat) en un único [compás](/wiki/Music_theory/Measure) de la canción (el número superior), y qué
```suggestion
Una **signatura de compás** es un término musical que define el número de [pulsos](/wiki/Music_theory/Beat) en un único [compás](/wiki/Music_theory/Measure) de la canción (el número superior), y qué nota indica un solo tiempo (el número de abajo). Para una signatura de compás de 4/4 (también conocido como «tiempo común»), caben 4 1/4 notas (*negras*) en un compás, mientras que una signatura de compás de 3/4 (también conocido como «vals») significa que caben 3 1/4 notas en un compás.
```

2023-10-21 21:40 UTC, UnknownOsu commented on wiki/Music_theory/Time_signature/es.md
> +El [editor de beatmaps](/wiki/Client/Beatmap_editor) de osu! ofrece varias signaturas de compás para [mapping](/wiki/Beatmapping), que se pueden seleccionar desde el [menú Timing](/wiki/Client/Beatma
```suggestion
El [editor de beatmaps](/wiki/Client/Beatmap_editor) de osu! ofrece varias signaturas de compás para el [mapping](/wiki/Beatmapping), que se pueden seleccionar desde el [menú Timing](/wiki/Client/Beatmap_editor/Timing). Estos incluyen 3/4, 4/4, 5/4, 6/4, y 7/4.
```

2023-10-21 23:12 UTC, UnknownOsu requested changes

2023-10-21 23:12 UTC, UnknownOsu commented on wiki/Music_theory/Time_signature/es.md
> +*Para más información sobre la signatura de compás en teoría musical, véase: [Compás (música)](https://en.wikipedia.org/wiki/Time_signature)*
```suggestion
*Para más información sobre la signatura de compás en teoría musical, véase: [Compás (música)](https://es.wikipedia.org/wiki/Compás_(música))*
```

2023-10-22 20:58 UTC, agatemosu commented on wiki/Music_theory/Measure/es.md
> +Un **compás** en teoría musical se refiere a una sola unidad de tiempo que incluye un número específico de [pulsos](/wiki/Music_theory/Beat) (determinado por la [signatura de compás](/wiki/Music_theo
nota: en femenino

2023-10-29 20:14 UTC, TicClick approved these changes

2023-10-29 20:16 UTC, merged