[ZH-TW] Update `Main_page`
ppy/osu-wiki pull request #10214
Opened 2023-10-19 13:17 UTC by 5idereal

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-24 05:49 UTC, YumeMuzi requested changes
Forum 还是可以翻译一下的

2023-10-24 05:49 UTC, YumeMuzi commented on wiki/Main_page/zh-tw.md
> +平台：[Forum](/wiki/Community/Forum) • [IRC](/wiki/Community/Internet_Relay_Chat) • [Discord 伺服器](/wiki/Community/Discord_servers)
```suggestion
平台：[論壇](/wiki/Community/Forum) • [IRC](/wiki/Community/Internet_Relay_Chat) • [Discord 伺服器](/wiki/Community/Discord_servers)
```

2023-10-24 13:37 UTC, 5idereal commented on wiki/Main_page/zh-tw.md
> +平台：[Forum](/wiki/Community/Forum) • [IRC](/wiki/Community/Internet_Relay_Chat) • [Discord 伺服器](/wiki/Community/Discord_servers)
沒檢查到🙇 
感謝 review!

2023-10-27 14:16 UTC, rucker122 commented on wiki/Main_page/zh-tw.md
> +[提交](/wiki/Beatmapping/Beatmap_submission) • [Mod 圖](/wiki/Modding) • [審核流程](/wiki/Beatmap_ranking_procedure) • [製圖者公會 (Mappers' Guild)](/wiki/Community/Mappers_Guild) • [Project Loved](/wiki/Communi
Modding 可翻成摸圖

2023-10-27 14:16 UTC, rucker122 commented on wiki/Main_page/zh-tw.md
> +[錦標賽](/wiki/Tournaments) • [圖譜聚光燈](/wiki/Beatmap_Spotlights) • [製圖競賽](/wiki/Contests) • [社群師徒計畫](/wiki/Community/Community_Mentorship_Program)
Tournament 翻成賽事或比賽比較直接

2023-10-27 14:16 UTC, rucker122 commented on wiki/Main_page/zh-tw.md
> +[osu! 歷史](/wiki/History_of_osu!) • [線上排行榜歷史](/wiki/History_of_osu!/Online_rankings) • [osu! wiki 歷史](/wiki/History_of_osu!/osu!_wiki) • [製圖及 Mod 圖時間線](/wiki/History_of_osu!/Mapping_and_modding_timeli
玩家用語可能 排名 會比 排行榜 常見, 但不太一定
這裡用排名歷史看起來比較順

2023-10-31 14:52 UTC, 5idereal commented
@rucker122 已按照您的建議做修改了，感謝 review!

2023-10-31 16:26 UTC, rucker122 approved these changes

2023-11-01 12:47 UTC, TicClick approved these changes

2023-11-01 12:49 UTC, merged