[GR] Updated the two outdated translations
ppy/osu-wiki pull request #10244
Opened 2023-10-21 16:06 UTC by JohnVictoryz

Updated the two outdated translations as shown in https://osu.wiki/status/el

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-21 16:12 UTC, agatemosu requested changes

2023-10-21 16:12 UTC, agatemosu commented on wiki/Rules/el.md
>  ---
remove it, do not put "false"

2023-10-21 16:15 UTC, JohnVictoryz commented on wiki/Rules/el.md
>  ---
kk

2023-10-21 16:17 UTC, JohnVictoryz commented on wiki/Rules/el.md
>  ---
solved it :)

2023-10-22 09:48 UTC, agatemosu commented
> * Refrain from continually updating the branch with `master` yourself. A [maintainer](https://osu.ppy.sh/wiki/People/osu%21_wiki_maintainers) will do this before merging anyway.

this line refers to that button, do not press that button

2023-10-22 13:15 UTC, JohnVictoryz commented
> > * Refrain from continually updating the branch with `master` yourself. A [maintainer](https://osu.ppy.sh/wiki/People/osu%21_wiki_maintainers) will do this before merging anyway.
> 
> this line refers to that button, do not press that button

srry i pressed it now :((((

2023-10-29 04:48 UTC, cl8n commented
has this been reviewed by another speaker of the language off-site?

2023-10-29 07:06 UTC, JohnVictoryz commented
Yes on the discord server

2023-10-29 07:07 UTC, JohnVictoryz commented
And here is the same link I send on discord for confirmation https://drive.google.com/file/d/1svgQkZtYAysVLJS3dodhyT3uzS0EhvGF/view?usp=drivesdk

2023-10-29 07:09 UTC, JohnVictoryz commented
Also he misspelled something in the English version of the message srry but he basically said everything is okay

2023-10-30 05:34 UTC, cl8n approved these changes

2023-10-30 05:37 UTC, merged