[UK] Add `Bot Account`
ppy/osu-wiki pull request #10249
Opened 2023-10-21 20:21 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-21 21:33 UTC, JyJyJ4JyJ requested changes

2023-10-21 21:33 UTC, JyJyJ4JyJ commented on wiki/Bot_account/uk.md
> +Якщо ви хочете створити чат-бота, будь ласка, почніть з його запуску на вашому власному акаунті osu!, і обов'язково слідуйте лімітам персональних акаунтів у списку вище. По мірі того як ваш сервіс зр
```suggestion
Якщо ви хочете створити чат-бота, будь-ласка, почніть з його запуску на вашому власному акаунті osu!, і обов'язково слідуйте лімітам персональних акаунтів у списку вище. З розширенням вашого сервісу у вас буде можливість відправити запит команді підтримки акаунтів для отримання окремого бот аккаунту.

```

2023-10-21 21:33 UTC, JyJyJ4JyJ commented on wiki/Bot_account/uk.md
> +Надішліть електронний лист до [accounts@ppy.sh](mailto:accounts@ppy.sh) з назвою `Bot Account Request`. Він має бути відправлений з електронної пошти прив'язаної до вашого акаунту osu!.
```suggestion
Надішліть електронний лист до [accounts@ppy.sh](mailto:accounts@ppy.sh) з назвою `Bot Account Request`. Він має бути відправлений з електронної пошти, прив'язаної до вашого акаунту osu!.

```

2023-10-21 21:33 UTC, JyJyJ4JyJ commented on wiki/Bot_account/uk.md
> +- Нікнейм який ви хочете дати бот акаунту
```suggestion
- Нікнейм, який ви хочете дати бот акаунту

```

2023-10-21 21:33 UTC, JyJyJ4JyJ commented on wiki/Bot_account/uk.md
> +- Дата коли ваш бот почав працювати
```suggestion
- Дата, коли ваш бот почав працювати

```

2023-10-21 21:33 UTC, JyJyJ4JyJ commented on wiki/Bot_account/uk.md
> +[Команда підтримки акаунтів](/wiki/People/Account_support_team) перевірить ваш запит. Якщо ваш запит буде відхилено, вони дадуть вам знати, чому. Якщо ваш запит буде схвалено, вони створять бот акаун
```suggestion
[Команда підтримки акаунтів](/wiki/People/Account_support_team) перевірить ваш запит. Якщо його буде відхилено, вони дадуть вам знати чому. Якщо ваш запит буде схвалено, вони створять бот акаунт для вас та нададуть вам подальші інструкції щодо його використання.

```

2023-10-21 21:33 UTC, JyJyJ4JyJ commented on wiki/Bot_account/uk.md
> +- Деякі персональні акаунти знаходяться в групі чат ботів через те, що власники не хотіли або не запросили окремий бот акаунт для їх сервісу, наприклад ::{ flag=DE }:: [Tillerino](https://osu.ppy.sh/
```suggestion
- Деякі персональні акаунти знаходяться в групі чат ботів через те, що власники не хотіли або не запросили окремий бот акаунт для їх сервісу, наприклад, ::{ flag=DE }:: [Tillerino](https://osu.ppy.sh/users/2070907) та ::{ flag=FR }:: [ThePooN](https://osu.ppy.sh/users/718454). Це налаштування більше не пропонується, та нові боти, які приєднуються до групи, завжди отримують ексклюзивний акаунт.

```

2023-10-21 22:28 UTC, JyJyJ4JyJ approved these changes

2023-10-22 07:17 UTC, TicClick requested changes

2023-10-22 07:17 UTC, TicClick commented on wiki/Bot_account/uk.md
> +tags:
original tags must also be preserved

2023-10-22 11:52 UTC, Hiviexd approved these changes

2023-10-22 11:58 UTC, merged