[ES] Add `Judgement/osu!`
ppy/osu-wiki pull request #10248
Opened 2023-10-21 19:10 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-21 20:44 UTC, UnknownOsu requested changes

2023-10-21 20:44 UTC, UnknownOsu commented on wiki/Gameplay/Judgement/osu!/es.md
> +- Tocar la cabeza del slider demasiado pronto (antes de la ventana de golpeo de MEH), saltarse una marca del slider, o saltarse un repetidor no incurre en un MISS, pero causará una [rotura del combo]
```suggestion
- Tocar la cabeza del slider demasiado pronto (antes de la ventana de golpeo de MEH), saltarse una marca del slider, o saltarse un repetidor no incurre en un MISS, pero causará una [rotura del combo](/wiki/Gameplay/Judgement/Combobreak). Las otras partes del slider pueden seguir siendo golpeadas si se mantiene pulsada una tecla. Esto se conoce coloquialmente como [slider break](/wiki/Gameplay/Judgement/Slider_break).
```

2023-10-21 20:45 UTC, agatemosu commented on wiki/Gameplay/Judgement/osu!/es.md
> +- Tocar la cabeza del slider demasiado pronto (antes de la ventana de golpeo de MEH), saltarse una marca del slider, o saltarse un repetidor no incurre en un MISS, pero causará una [rotura del combo]
yep

2023-10-21 20:49 UTC, UnknownOsu commented on wiki/Gameplay/Judgement/osu!/es.md
> +- Tocar la cabeza del slider demasiado pronto (antes de la ventana de golpeo de MEH), saltarse una marca del slider, o saltarse un repetidor no incurre en un MISS, pero causará una [rotura del combo]
También algunos cambios en `Notelock`:
- Línea `15`: Después de `osu!`, creo que queda mejor `la`, ya que antes se está hablando de la mécanica y no del notelock en sí.
- Línea `22`: Tal vez cambiar `deslizadores` y `ruletas`
- Línea `26`: Está de más `la ventana de` al principio de la línea
- Línea `31`: Tal vez cambiar `grandes` por `altas`

2023-10-21 20:55 UTC, agatemosu commented
one more tag to the PR 😄

2023-11-04 04:45 UTC, cl8n approved these changes

2023-11-04 04:47 UTC, merged