[ES] Add `osu!catch` and `osu!taiko`
ppy/osu-wiki pull request #10257
Opened 2023-10-22 11:31 UTC by agatemosu

Supersedes #9916 (applied my review + my review that was not sent)

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-22 21:24 UTC, UnknownOsu requested changes

2023-10-22 21:24 UTC, UnknownOsu commented on wiki/Game_mode/osu!taiko/es.md
> +  - las notas rojas grandes necesitan un hitound final.
```suggestion
  - las notas rojas grandes necesitan un hitsound final.
```

2023-10-22 21:24 UTC, UnknownOsu commented on wiki/Game_mode/osu!taiko/es.md
> +- Las notas azules deben tener un sonido de silbido/aplauso en ese círculo,
```suggestion
- Las notas azules deben tener un hitsound de silbido/aplauso en ese círculo,
```

2023-10-22 21:24 UTC, UnknownOsu commented on wiki/Game_mode/osu!taiko/es.md
> +  - las notas azules grandes necesitan un sonido final y un silbido juntos.
```suggestion
  - las notas azules grandes necesitan un hitsound final y un silbido juntos.
```

2023-10-22 21:24 UTC, UnknownOsu commented on wiki/Game_mode/osu!taiko/es.md
> +Cuando se produce una conversión de mapa (jugando un mapa de osu! en modo osu!taiko), los sliders muy cortos (normalmente menos de un beat) se convierten automáticamente en notas rojas o azules, depe
```suggestion
Cuando se produce una conversión de mapa (jugando un mapa de osu! en el modo osu!taiko), los sliders muy cortos (normalmente menos de un beat) se convierten automáticamente en notas rojas o azules, dependiendo del hitsound utilizado.
```

2023-10-22 21:24 UTC, UnknownOsu commented on wiki/Game_mode/osu!taiko/es.md
> +  - 4 veces la longitud del slider, o
```suggestion
  - 4 veces la longitud del slider, u
```

2023-10-22 21:24 UTC, UnknownOsu commented on wiki/Game_mode/osu!taiko/es.md
> +- A diferencia de los otros modos de juego, el *Kiai Time* tiene un efecto en las puntuaciones porque se refiere al *«Go-Go Time»* en *Taiko no Tatsujin*. Mientras *Kiai Time* está activo, el tambor
```suggestion
- A diferencia de los otros modos de juego, el *Kiai Time* tiene un efecto en las puntuaciones porque se refiere al *«Go-Go Time»* en *Taiko no Tatsujin*. Mientras el *Kiai Time* está activo, el tambor de la parte superior izquierda cambia de animación (llamado *pippidon* o *Don*/*Katsu* en *Taiko no Tatsujin*), el campo de juego tiene un degradado de fondo y el área de golpe gana un gráfico de fuego a su alrededor.
```

2023-10-22 21:24 UTC, UnknownOsu commented on wiki/Game_mode/osu!taiko/es.md
> +- La opción `Utilizar la skin de Taiko para Taiko` en la barra lateral de opciones en la sección de skins utilizará los elementos de la carpeta `taiko` cuando juegue en *osu!taiko*, independientement
```suggestion
- La opción `Utilizar la skin de Taiko para Taiko` en la barra lateral de opciones en la sección de skins utilizará los elementos de la carpeta `taiko` cuando juegues en *osu!taiko*, independientemente de los elementos taiko de la skin actual. La carpeta usada para mantener la skin *[Taiko por LuiginHann](https://osu.ppy.sh/community/forums/topics/41319)*, que se puede descargar desde el ahora obsoleto `osume.exe` (un archivo para actualizar osu! para cuando sea necesario actualizar) en la pestaña `Skin`.
```

2023-10-22 21:31 UTC, UnknownOsu commented
Tal vez también poner la foto en español en `controles` en `osu!catch`

2023-11-05 04:25 UTC, UnknownOsu approved these changes

2023-11-05 04:50 UTC, cl8n approved these changes

2023-11-05 04:51 UTC, cl8n commented
> Tal vez también poner la foto en español en `controles` en `osu!catch`

for a needs_cleanup article it's probably fine.

2023-11-05 04:54 UTC, merged