fix "vocaloid version" link
ppy/osu-wiki pull request #10264
Opened 2023-10-22 23:12 UTC by Copperbug

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-22 23:21 UTC, Blooshing commented
Yeah, new link seems to be the correct one. Old link sends to a 404 

![Blushing20231022-1698016857](https://github.com/ppy/osu-wiki/assets/90729492/a3411959-9984-41bd-8a8c-5b2b0383f840)

2023-10-22 23:26 UTC, Blooshing requested changes
this seems to be the correct link?

2023-10-22 23:26 UTC, Blooshing commented on news/2023/2023-10-22-new-featured-artist-will-stetson.md
> +Or try mapping [the VOCALOID version](https://assets.ppy.sh/artists/385/Koala/Will%20Stetson%20-%20Koala.osz)!
```Suggestion
Or try mapping [the VOCALOID version](https://assets.ppy.sh/artists/385/Koala/Will%20Stetson%20-%20Koala%20(Self%20Cover).osz)!
```

2023-10-23 00:01 UTC, pishifat commented on news/2023/2023-10-22-new-featured-artist-will-stetson.md
> +Or try mapping [the VOCALOID version](https://assets.ppy.sh/artists/385/Koala/Will%20Stetson%20-%20Koala.osz)!
op's link is right?

2023-10-23 00:01 UTC, pishifat approved these changes

2023-10-23 00:04 UTC, merged