[ES] Clean up `Twitter`
ppy/osu-wiki pull request #10273
Opened 2023-10-23 16:14 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-23 17:11 UTC, MChecaH commented on wiki/Twitter/es.md
> +| ![Dean Herbert avatar](img/ppy.jpg?2) | [@ppy](https://twitter.com/ppy "Twitter") | La cuenta personal de Twitter del [creador de osu!](/wiki/People/peppy), que no es estrictamente sobre osu!, pero
In the original article, the last `it` is making reference to the game, not the account. If we're implicitly going to refer to it (the game), it'd be more correct if the correct gendered pronoun was used (El Juego, not La Juego).
```suggestion
| ![Dean Herbert avatar](img/ppy.jpg?2) | [@ppy](https://twitter.com/ppy "Twitter") | La cuenta personal de Twitter del [creador de osu!](/wiki/People/peppy), que no es estrictamente sobre osu!, pero de todas maneras cubre la mayoría de él. |
```

2023-10-25 18:20 UTC, UnknownOsu requested changes

2023-10-25 18:20 UTC, UnknownOsu commented on wiki/Twitter/es.md
> +| ![Avatar de osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport "Twitter") | Ayuda con tu cuenta y/o problemas de la comunidad. Manejado por el [equipo de soporte de cu
```suggestion
| ![Avatar de osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport "Twitter") | Ayuda con tu cuenta y/o problemas de la comunidad. Manejada por el [equipo de soporte de cuentas](/wiki/People/Account_support_team). |
```

2023-10-25 18:20 UTC, UnknownOsu commented on wiki/Twitter/es.md
> +| ![Avatar del NAT](img/osu_nat.png) | [@osu_nat](https://twitter.com/osu_nat "Twitter") | Noticias, anuncios, y breves encuestas comunitarias realizadas por el [NAT](/wiki/People/Nomination_Assessme
```suggestion
| ![Avatar del NAT](img/osu_nat.png) | [@osu_nat](https://twitter.com/osu_nat "Twitter") | Noticias, anuncios, y breves encuestas comunitarias realizadas por el [NAT](/wiki/People/Nomination_Assessment_Team) (no manejada por [el osu! team](/wiki/People/osu!_team)). |
```

2023-10-25 18:20 UTC, UnknownOsu commented on wiki/Twitter/es.md
> +| ![Avatar del commité de pp](img/ppcommittee.png) | [@pp_committee](https://twitter.com/pp_committee) | Anuncios de cálculo de dificultad para todos los modos de juego, manejado por el [comité de pu
```suggestion
| ![Avatar del commité de pp](img/ppcommittee.png) | [@pp_committee](https://twitter.com/pp_committee) | Anuncios de cálculo de dificultad para todos los modos de juego, manejada por el [comité de puntos de rendimiento](/wiki/People/Performance_Points_Committee). |
```

2023-10-25 21:33 UTC, cl8n approved these changes

2023-10-25 21:35 UTC, merged