[UK] Add `Support Team`
ppy/osu-wiki pull request #10287
Opened 2023-10-25 20:43 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-25 21:25 UTC, WindowsMeosu requested changes
newlines should be in LF, not CRLF

2023-10-25 22:54 UTC, JyJyJ4JyJ commented on wiki/People/Support_Team/uk.md
> +*Для команди, що адмініструє акаунти дивіться: [Команда підтримки акаунтів](/wiki/People/Account_support_team)*
```suggestion
*Детальніше про команду, що адмініструє акаунти: [Команда підтримки акаунтів](/wiki/People/Account_support_team)*
```

2023-10-25 22:54 UTC, JyJyJ4JyJ commented on wiki/People/Support_Team/uk.md
> +**Команда Підтримки**, також відома як **Команда Підтримки Redux**, є членами команди osu!, які зосереджені на модерації кількох підфорумів: [Development](https://osu.ppy.sh/community/forums/2), [Gam
```suggestion
**Команда Підтримки**, також відома як **Команда Підтримки Redux**, є частиною команди osu!, яка зосереджена на модерації кількох підфорумів: [Development](https://osu.ppy.sh/community/forums/2), [Gameplay & Rankings](https://osu.ppy.sh/community/forums/13) (за виключенням [Tournaments](https://osu.ppy.sh/community/forums/55) та [Mapping Techniques](https://osu.ppy.sh/community/forums/61)), [Skinning](https://osu.ppy.sh/community/forums/15), [Feature Requests](https://osu.ppy.sh/community/forums/4) і [Help](https://osu.ppy.sh/community/forums/5).
```

2023-10-25 22:54 UTC, JyJyJ4JyJ commented on wiki/People/Support_Team/uk.md
> +**Команда Підтримки**, також відома як **Команда Підтримки Redux**, є членами команди osu!, які зосереджені на модерації кількох підфорумів: [Development](https://osu.ppy.sh/community/forums/2), [Gam
команду чи команди osu! не чіпав, сам вже розбирайся, скільки їх

2023-10-25 22:54 UTC, JyJyJ4JyJ commented on wiki/People/Support_Team/uk.md
> +1. Тестування та/або підтвердження баг репортів, щоб повідомити про них розробників і щоб вони могли їх усунути.
```suggestion
1. Тестування та/або підтвердження баг репортів, щоб повідомити про них розробників, а ті могли їх усунути.
```

2023-10-25 22:54 UTC, JyJyJ4JyJ commented on wiki/People/Support_Team/uk.md
> +1. Тестування та/або підтвердження баг репортів, щоб повідомити про них розробників і щоб вони могли їх усунути.
баг-репортів або звітів про баги, згоден з будь-яким,бо друге більш "українське", а перше звичніше

2023-10-25 22:54 UTC, JyJyJ4JyJ commented on wiki/People/Support_Team/uk.md
> +*Примітка: Усі члени Команди Підтримки говорять на англійській у додаток до мов, перелічених нижче, якщо не зазначено інше.*
```suggestion
*Примітка: Усі члени Команди Підтримки говорять англійською на додачу до мов, перелічених нижче, якщо не зазначено інше.*
```

2023-10-25 23:00 UTC, minusQuantumNeko commented on wiki/People/Support_Team/uk.md
> +1. Тестування та/або підтвердження баг репортів, щоб повідомити про них розробників і щоб вони могли їх усунути.
```suggestion
1. Тестування та/або підтвердження баг-репортів, щоб повідомити про них розробників, а ті могли їх усунути.
```

2023-10-25 23:03 UTC, JyJyJ4JyJ approved these changes

2023-10-26 03:42 UTC, cl8n approved these changes

2023-10-26 03:42 UTC, merged