[UK] Add all file formats articles
ppy/osu-wiki pull request #10299
Opened 2023-10-27 23:07 UTC by JyJyJ4JyJ

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-03 22:16 UTC, minusQuantumNeko requested changes

2023-11-03 22:16 UTC, minusQuantumNeko commented on wiki/Client/File_formats/osu_(file_format)/uk.md
> +### Довгі ноти (лише osu!mania)
```suggestion
### Довгі ноти (лише в osu!mania)
```

2023-11-03 22:16 UTC, minusQuantumNeko commented on wiki/Client/File_formats/osu_(file_format)/uk.md
> +- Повторюється раз
```suggestion
- Повторюється один раз
```

2023-11-03 22:16 UTC, minusQuantumNeko commented on wiki/Client/File_formats/osu_(file_format)/uk.md
> +Так само, як і в osu!catch, об'єкти в osu!mania не використовують `y`. `x` використовується для визначення колонки; дивіться [розділ про довгі ноти](#довгі-ноти-(лише-osu!mania)).
```suggestion
Так само, як і в osu!catch, об'єкти в osu!mania не використовують `y`. `x` використовується для визначення колонки; дивіться [розділ про довгі ноти](#довгі-ноти-(лише-в-osu!mania)).
```

2023-11-03 23:06 UTC, minusQuantumNeko approved these changes

2023-11-04 01:35 UTC, Walavouchey approved these changes

2023-11-04 01:36 UTC, merged