Project loved article spanish translation
ppy/osu-wiki pull request #10309
Opened 2023-10-28 22:22 UTC by Kazuorz

- Added es.md to the Community / Project Loved wiki article

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +**Todas las reglas son exactamente eso: reglas.** Éstas no son simples guías y por ende no deben ser rotas bajo ninguna circunstancia
```suggestion
**Todas las reglas son exactamente eso: reglas.** No son pautas y no pueden romperse bajo ninguna circunstancia.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El mapa debe cumplir con las [reglas de publicación de mapas](/wiki/Rules#beatmap-submission-rules).**
```suggestion
- **El beatmap debe cumplir con las [reglas de envío de beatmaps](/wiki/Rules#beatmap-submission-rules).**
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El mapa debe estar fuera de las categorías de Calificados, Clasificados o Aprobados.** Idealmente, un mapa no debería apuntar a entrar a la categoría de Clasificados y Amados al mismo tiempo, ya
```suggestion
- **El beatmap debe estar fuera de las categorías Calificados, Clasificados o Aprobados.** Idealmente, un mapa no debería apuntar a entrar a la categoría Clasificados y Amados al mismo tiempo, ya que son mutualmente exclusivos.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El mapa debe haber sido publicado al menos un año antes de su nominación a Amados, con la excepción de los mapas que rompen el Ranking Criteria con su concepto.** Publicar un mapa con el objetivo
```suggestion
- **El beatmap debe haberse enviado al menos un año antes de su nominación a Amados, con la excepción de los mapas que rompen los criterios de clasificación con su concepto.** Publicar un beatmap con el objetivo de entrar en la categoría Amados no es recomendado, especialmente cuando la categoría Clasificados es una mejor opción. Las excepciones suelen incluir usos de sliderator, mapas Aspire, mapas con mecánicas de juego en el storyboard, etc.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El mapa debe tener al menos 30 favoritos.** Este es un límite minimo para indicar la existencia de una reacción positiva por parte de la comunidad. Se recomienda no coordinar grupos para aumentar
```suggestion
- **El beatmap debe tener al menos 30 favoritos.** Este es un límite mínimo para indicar la existencia de una reacción positiva por parte de la comunidad hacia el beatmap. Se recomienda no coordinar grupos para aumentar los favoritos, aunque los capitanes no pueden verificar si esto ocurre.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Todas las personas involucradas en el mapa deben estar de acuerdo con que entre en Amados.** Esto incluye a los creadores invitados y a los creadores de hitsounds, skins y storyboards. Si cualqui
```suggestion
- **Todas las personas involucradas en el beatmap deben estar de acuerdo con que entre en Amados.** Esto incluye a los creadores de dificultades de invitado y a los creadores de hitsounds, skins y storyboards. Si cualquier usuario involucrado en el beatmap esta en desacuerdo con que su contribución sea parte de Amados, esta debe ser eliminada del beatmap tras su nominación.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El anfitrión del mapa no puede estar restringido.** En el caso de las dificultades de creadores invitados restringidos, los capitanes tendrán la última palabra en cuanto a permitirlos o no tras s
```suggestion
- **El anfitrión del beatmap no puede estar restringido.** En el caso de que los creadores de dificultades de invitado estén restringidos, los capitanes tendrán la última palabra en cuanto a permitirlos o no tras ser nominados.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Es posible pasar al menos una de las dificultades del mapa.** Las tablas de clasificación no tienen sentido en mapas en los que es imposible publicar un puntaje. Por esta razón, son también prohi
```suggestion
- **Es posible pasar al menos una de las dificultades del beatmap.** Las tablas de clasificación no tienen sentido en beatmaps en los que es imposible enviar una puntuación. Por esta razón, también son prohibidos los beatmaps que son relevantes solo por una dificultad imposible de pasar, incluso si tienen otras dificultades. Si el mapa tiene una dificultad imposible de pasar, una nueva dificultad que elimine los elementos problemáticos debe ser incluida, de preferencia reemplazando la original.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Cada dificultad del mapa debe tener un mínimo de 20 segundos de duración.** Esto es mas bajo que el mínimo de 30 segundos que aplica el Ranking Criteria, con el objetivo de ser mas flexibles.
```suggestion
- **Cada dificultad del beatmap debe tener un mínimo de 20 segundos de duración.** Esto es más bajo que el mínimo de 30 segundos que se aplica en los criterios de clasificación, con el objetivo de ser más flexibles.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Un mapa debe tener al menos alguna contribución de la persona que lo publica.** Esto evita de manera específica las "compilaciones de mapas", las cuales incluso con el permiso del creador origina
```suggestion
- **Un beatmap debe tener al menos alguna contribución de la persona que lo publica.** Esto evita de manera específica las «compilaciones de beatmaps», las cuales incluso con el permiso del creador original, no representan el contenido original exhibido en la categoría Amados.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El timing del mapa no debe tener un impacto negativo en la jugabilidad.** A diferencia del Ranking Criteria, que requiere un timing preciso para todos los mapas, hay una pequeña flexibilidad para
```suggestion
- **La temporización del beatmap no debe tener un impacto negativo en la jugabilidad.** A diferencia de los criterios de clasificación, que requieren una temporización precisa para todos los beatmaps, hay una pequeña flexibilidad para canciones complejas. Si estás inseguro de si la temporización de un beatmap es apropiada, puedes contactar a alguno de los capitanes.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Los mapas cuyos conceptos que dependen del storyboard no deben ser fácilmente explotables por los jugadores a través de editar archivos.** Esto es evaluado caso a caso para asegurar una competici
```suggestion
- **Los beatmaps cuyos conceptos dependen del storyboard no deben ser fácilmente explotables por los jugadores a través de editar archivos.** Esto es evaluado caso a caso para asegurar una competición justa para aquellos que juegan el beatmap de la manera prevista. Los problemas pueden ser mitigados usando una tasa de aproximación de 0, haciendo que las notas invisibles se sientan más naturales, a la vez que puedes hacer el storyboard de manera específica para la dificultad usando el archivo `.osu` en lugar del `.osb`. 
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +#### Guías
```suggestion
#### Pautas
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +**Las guías pueden ser ignoradas en circunstancias específicas.** Estas excepciones pueden ser justificadas con una explicación del por qué se han ignorado y cómo no ignorarlas interfieren con la cal
```suggestion
**Las pautas pueden ignorarse en circunstancias excepcionales.** Estas circunstancias excepcionales deben justificarse mediante una explicación exhaustiva de por qué se ha ignorado la pauta y por qué no ignorarla interferirá con la calidad general de la creación.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Todas las reglas y guías del Ranking Criteria que no han sido explícitamente mencionadas acá se consideran guías.** La aplicación de estas ocurre dependiendo del caso durante el proceso de nomina
```suggestion
- **Todas las reglas y pautas de los criterios de clasificación que no han sido explícitamente mencionadas aquí se consideran pautas.** La aplicación de estas ocurre dependiendo del caso durante el proceso de nominación a Amados, por lo que el creador será contactado en caso de cualquier cambio requerido. Ten en cuenta que contar con dificultades para cada nivel no es necesario excepto en la categoría de *Ranked Rejects*.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El metadata del mapa debe ser tan preciso como sea posible.** Los mapas que son nominados a Amados pasan por una comprobación final por parte de miembros especializados de la comunidad. Tener una
```suggestion
- **Los metadatos del beatmap deben ser tan precisos como sea posible.** Los beatmaps que son nominados a Amados pasan por una comprobación final por parte de miembros especializados de la comunidad. Tener unos metadatos correctos ayuda a encontrar el beatmap fácilmente. Ante cualquier duda, contacta a un capitán de Project Loved.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Los puntos de timing deben ser iguales en todas las dificultades de un mapa.** Esto se puede ignorar en el caso de ciertas mecánicas de juego que involucran cambiar el BPM, velocidad de las notas
```suggestion
- **Los puntos de tiempo no heredados deben ser iguales en todas las dificultades de un mapa.** Esto se puede ignorar en el caso de ciertas mecánicas de juego que involucran cambiar el PPM, velocidad del slider u otros factores que no son relevantes en todas las dificultades.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Todas las dificultades del mapa deben estar terminadas.** Esto significa completar de principio a fin la cancion, excluyendo secciones irrelevantes como intros u outros. Por ejemplo, en una canci
```suggestion
- **Todas las dificultades del beatmap deben estar terminadas.** Esto significa completar de principio a fin la canción, excluyendo secciones irrelevantes como intros u outros. Por ejemplo, en una canción de 5 minutos con múltiples dificultades, si las dificultades Hard y Extra duran 4:30, la dificultad Insane no puede durar solo 1 minuto. Si todas las dificultades tienen una gran porción de la cancion sin mapear, el archivo de audio debe ser recortado de manera acorde.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +#### Prioridad de Nominación
```suggestion
#### Prioridad de nominación
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +No hay reglas estrictas que establezcan que mapas debe nominar un capitán, pero de manera general los mapas nominados suelen ser conocidos y apreciados por la comunidad (tal y como el título "Amado"
```suggestion
No hay reglas estrictas que establezcan que mapas debe nominar un capitán, pero de manera general los mapas nominados suelen ser conocidos y apreciados por la comunidad (tal y como el título «Amado» implica). Algunas veces un beatmap puede ser preferido por el capitán si es significativamente más antiguo que otros o contiene dificultades con estilos únicos o de alta calidad.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +## Nás información
```suggestion
## Más información
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +La organización y planificación de Project Loved se realiza principalmente en el canal `#osu-loved` del [Servidor de Discord de osu!](https://discord.gg/ppy). Además, hay un canal de `#project-loved`
```suggestion
La organización y planificación de Project Loved se realiza principalmente en el canal `#osu-loved` del [servidor de Discord osu!](https://discord.gg/ppy). Además, hay un canal de `#project-loved` en el [servidor de Discord de la comunidad de osu!](https://discord.gg/0Vxo9AsejDkGlk3H). Cualquier consulta, inquietud o sugerencia puede ser realizada allí.
```

2023-10-28 23:29 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- [Servidor de Discord de Project Loved osu!mania](https://discord.gg/Ededv7m)
```suggestion
- [Servidor de Discord osu! Project Loved](https://discord.gg/gn58Uk5sTE)
- [Servidor de Discord osu!taiko Project Loved](https://discord.com/invite/GhfjtZ6)
- [Servidor de Discord osu!catch Project Loved](https://discord.gg/phgtyS4UCh)
- [Servidor de Discord osu!mania Project Loved](https://discord.gg/Ededv7m)
```

2023-10-29 00:36 UTC, MChecaH requested changes

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +Los miembros del Project Loved Team llamados **capitanes** regularmente nominan mapas para un modo de juego específico. Estos mapas casi siempre vienen de las sugerencias de la comunidad.
La última frase era innecesariamente larga.

```suggestion
Los miembros del Project Loved Team son llamados **capitanes** y nominan regularmente beatmaps para un modo de juego específico. Estos beatmaps casi siempre son sugeridos la comunidad.
```

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +Para sugerir un mapa a la categoría Amados, puedes hacerlo desde el [formulario para enviar un mapa](https://loved.sh/submit) a la página de Project Loved. Tu sugerencia será añadida a la lista de su
Modificada la última frase para ser más fiel a la original.

```suggestion
Para sugerir un beatmap a la categoría Amados, puedes hacerlo desde la [página de envío de beatmaps](https://loved.sh/submit) de la página del Project Loved. Tu sugerencia será añadida a la lista de su respectivo modo de juego junto a las demás. Abajo se encuentran las listas donde se pueden ver estas sugerencias:
```

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +Los mapas nominados son publicados en el [foro de Project Loved](https://osu.ppy.sh/community/forums/120), donde los miembros de la comunidad pueden votar si quieren que el mapa sea Amado o no. Los m
```suggestion
Los beatmaps nominados son publicados en el [foro Project Loved](https://osu.ppy.sh/community/forums/120), donde los miembros de la comunidad pueden votar si quieren que el beatmap sea Amado o no. Los mapas que alcancen el 80 % de los votos «Sí» al final de las encuestas serán promovidos a la categoría Amados.
```

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +Cada mes, los mapas son elegidos acorde a 9 categorías, con el objetivo de asegurar variedad de mapas en cada selección de los capitanes.
La oración sin artículo es difícil de entender.

```suggestion
Cada mes, los beatmaps son elegidos acorde a 9 categorías, con el objetivo de asegurar una variedad de beatmaps en cada selección de los capitanes.
```

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +| Popular Playcounts | Mapas populares en la comunidad, jugado al menos 100,000 veces. |
La segunda oración es dependiente de la segunda, por lo tanto requiere seguir la sintaxis de la primera y mantener la forma del substantivo en plural.

```suggestion
| Popular Playcounts | Beatmaps populares en la comunidad, jugados al menos 100 000 veces. |
```

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +| Ranked Rejects | Mapas con el formato adecuado para la sección de Clasificados que nunca lo alcanzaron. |
Falta comentar el requisito de Full spread, del cuál no se dispone ahora.

```suggestion
| Ranked Rejects | Beatmaps que disponen de una distribución de dificultades completa y que cumplen con los criterios de clasificación. |
```

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +| Outstanding Oldies | Mapas publicados hace mas de seis años. |
Ambiguo. El lector puede leerlo como si el beatmap haya habido de ser enviado a la página de sugerencias con un año de antelación, cuando queremos que sepa que el mapa ha de estar publicado en la página.

```suggestion
| Outstanding Oldies | Beatmaps publicados hace más de seis años. |
```

2023-10-29 00:36 UTC, MChecaH commented on wiki/Community/Project_Loved/es.md
> +- **El mapa debe haber sido publicado al menos un año antes de su nominación a Amados, con la excepción de los mapas que rompen el Ranking Criteria con su concepto.** Publicar un mapa con el objetivo
Sigue mejor la oración en Inglés para saber que el mapa a priori está más preparado para ser Calificado en vez de amado.

```suggestion
- **El beatmap debe haberse enviado al menos un año antes de su nominación a Amados, con la excepción de los mapas que rompen los criterios de clasificación con su concepto.** No se recomienda publicar un beatmap con el objetivo de entar en la categoría Amados cuando la categoría Clasificados sea una mejor opción. Las excepciones suelen incluir usos de sliderator, mapas Aspire, mapas con mecánicas de juego en el storyboard, etc.
```

2023-10-29 07:00 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **El mapa debe haber sido publicado al menos un año antes de su nominación a Amados, con la excepción de los mapas que rompen el Ranking Criteria con su concepto.** Publicar un mapa con el objetivo
me parece bien pero creo que es mejor usar "es" y no "sea"

```suggestion
**El beatmap debe haberse enviado al menos un año antes de su nominación a Amados, con la excepción de los mapas que rompen los criterios de clasificación con su concepto.** No se recomienda publicar un beatmap con el objetivo de entar en la categoría Amados cuando la categoría Clasificados es una mejor opción. Las excepciones suelen incluir usos de sliderator, mapas Aspire, mapas con mecánicas de juego en el storyboard, etc.
```

2023-10-29 07:04 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +| Outstanding Oldies | Mapas publicados hace mas de seis años. |
no creo, a los beatmaps enviados en la página se les llama sugerencias

2023-10-29 07:08 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +| Ranked Rejects | Mapas con el formato adecuado para la sección de Clasificados que nunca lo alcanzaron. |
```suggestion
Beatmaps con una distribución completa que siguen los criterios de clasificación, pero que nunca alcanzaron el estado de clasificación.
```

2023-10-29 07:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +| Popular Playcounts | Mapas populares en la comunidad, jugado al menos 100,000 veces. |
oración compuesta coordinada

2023-10-29 07:20 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +Para sugerir un mapa a la categoría Amados, puedes hacerlo desde el [formulario para enviar un mapa](https://loved.sh/submit) a la página de Project Loved. Tu sugerencia será añadida a la lista de su
```suggestion
Para sugerir un beatmap a la categoría Amados, puedes hacerlo desde la [página de envío de beatmaps](https://loved.sh/submit) de la página del Project Loved. Tu sugerencia será añadida a la lista de su respectivo modo de juego junto a las demás. A continuación se encuentran las listas donde se pueden ver estas sugerencias:
```

2023-10-29 18:03 UTC, agatemosu reviewed
These are the MChecaH reviews that you did not apply

2023-10-29 18:03 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +Los miembros del Project Loved Team son llamados **capitanes** y nominan regularmente beatmaps para un modo de juego específico. Estos casi siempre vienen de las sugerencias de la comunidad.
```suggestion
Los miembros del Project Loved Team son llamados **capitanes** y nominan regularmente beatmaps para un modo de juego específico. Estos beatmaps casi siempre son sugeridos la comunidad.
```

2023-10-29 18:03 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +Para sugerir un beatmap a la categoría Amados, puedes hacerlo desde la [página de envío de beatmaps](https://loved.sh/submit) de la página del Project Loved. Tu sugerencia será añadida a la lista de
```suggestion
Para sugerir un beatmap a la categoría Amados, puedes hacerlo desde la [página de envío de beatmaps](https://loved.sh/submit) de la página del Project Loved. Tu sugerencia será añadida a la lista de su respectivo modo de juego junto a las demás. A continuación se encuentran las listas donde se pueden ver estas sugerencias:
```

2023-10-29 18:03 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +Los beatmaps nominados son publicados en el [foro Project Loved](https://osu.ppy.sh/community/forums/120), donde los miembros de la comunidad pueden votar si quieren que el beatmap sea Amado o no. Lo
```suggestion
Los beatmaps nominados son publicados en el [foro Project Loved](https://osu.ppy.sh/community/forums/120), donde los miembros de la comunidad pueden votar si quieren que el beatmap sea Amado o no. Los mapas que alcancen el 80 % de los votos «Sí» al final de las encuestas serán promovidos a la categoría Amados.
```

2023-10-29 18:03 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +Cada mes, los beatmaps son elegidos acorde a 9 categorías, con el objetivo de asegurar variedad de beatmaps en cada selección de los capitanes.
```suggestion
Cada mes, los beatmaps son elegidos acorde a 9 categorías, con el objetivo de asegurar una variedad de beatmaps en cada selección de los capitanes.
```

2023-10-29 18:03 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +| Popular Playcounts | Beatmaps populares en la comunidad, jugado al menos 100 000 veces. |
```suggestion
| Popular Playcounts | Beatmaps populares en la comunidad, jugados al menos 100 000 veces. |
```

2023-10-29 18:03 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +| Ranked Rejects | Beatmaps con el formato adecuado para la categoría Clasificados que nunca lo alcanzaron. |
```suggestion
| Ranked Rejects | Beatmaps con una distribución completa que siguen los criterios de clasificación, pero que nunca alcanzaron el estado clasificado. |
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- [Algunos puntos de la seccion Metadatos de los criterios de clasificación](/wiki/Ranking_criteria#metadata):
```suggestion
- [Algunos puntos de la sección Metadatos de los criterios de clasificación](/wiki/Ranking_criteria#metadata):
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- [Reglas del contenido de las canciones](/wiki/Rules/Song_content_rules)
```suggestion
- [Reglas del contenido de canciones](/wiki/Rules/Song_content_rules)
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- [Consideraciones sobre el contenido visual](/wiki/Rules/Visual_content_considerations)
```suggestion
- [Consideraciones de contenido visual](/wiki/Rules/Visual_content_considerations)
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +Cualquier problema con estas reglas suele ser solucionado mientras el beatmap esta en su período de votación.
```suggestion
Cualquier problema con estas reglas suele ser solucionado mientras el beatmap está en su período de votación.
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Todas las personas involucradas en el beatmap deben estar de acuerdo con que entre en Amados.** Esto incluye a los creadores de dificultades de invitado y a los creadores de hitsounds, skins y st
```suggestion
- **Todas las personas involucradas en el beatmap deben estar de acuerdo con que entre en Amados.** Esto incluye a los creadores de dificultades de invitado y a los creadores de hitsounds, skins y storyboards. Si cualquier usuario involucrado en el beatmap está en desacuerdo con que su contribución sea parte de Amados, esta debe ser eliminada del beatmap tras su nominación.
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Es posible pasar al menos una de las dificultades del beatmap.** Las tablas de clasificación no tienen sentido en beatmaps en los que es imposible enviar una puntuación. Por esta razón, también s
```suggestion
- **Es posible pasar al menos una de las dificultades del beatmap.** Las tablas de clasificación no tienen sentido en beatmaps en los que es imposible enviar una puntuación. Por esta razón, también son prohibidos los beatmaps que son relevantes solo por una dificultad imposible de pasar, incluso si tienen otras dificultades. Si el mapa tiene una dificultad imposible de pasar, una nueva dificultad que elimine los elementos problemáticos debe ser incluida, de preferencia, reemplazando la original.
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Un beatmap debe tener al menos alguna contribución de la persona que lo publica.** Esto evita de manera específica las «compilaciones de beatmaps», las cuales incluso con el permiso del creador o
```suggestion
- **Un beatmap debe tener al menos alguna contribución de la persona que lo publica.** Esto evita de manera específica las «compilaciones de beatmaps», las cuales, incluso con el permiso del creador original, no representan el contenido original exhibido en la categoría Amados.
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Todas las reglas y pautas de los criterios de clasificación que no han sido explícitamente mencionadas aquí se consideran pautas.** La aplicación de estas ocurre dependiendo del caso durante el p
```suggestion
- **Todas las reglas y pautas de los criterios de clasificación que no han sido explícitamente mencionadas aquí se consideran pautas.** La aplicación de estas ocurre dependiendo del caso durante el proceso de nominación a Amados, por lo que el creador será contactado en caso de cualquier cambio requerido. Ten en cuenta que contar con dificultades para cada nivel no es necesario, excepto en la categoría de *Ranked Rejects*.
```

2023-10-29 19:19 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Los puntos de tiempo no heredados deben ser iguales en todas las dificultades de un mapa.** Esto se puede ignorar en el caso de ciertas mecánicas de juego que involucran cambiar el PPM, velocidad
```suggestion
- **Los puntos de tiempo no heredados deben ser iguales en todas las dificultades de un mapa.** Esto se puede ignorar en el caso de ciertas mecánicas de juego que involucran cambiar los PPM, velocidad del slider u otros factores que no son relevantes en todas las dificultades.
```

2023-10-29 20:52 UTC, agatemosu commented on wiki/Community/Project_Loved/es.md
> +- **Los puntos de tiempo no heredados deben ser iguales en todas las dificultades de un mapa.** Esto se puede ignorar en el caso de ciertas mecánicas de juego que involucran cambiar el BPM, velocidad
https://es.wikipedia.org/wiki/Pulsaciones_por_minuto

```suggestion
- **Los puntos de tiempo no heredados deben ser iguales en todas las dificultades de un mapa.** Esto se puede ignorar en el caso de ciertas mecánicas de juego que involucran cambiar los PPM, velocidad del slider u otros factores que no son relevantes en todas las dificultades.
```

2023-11-03 20:23 UTC, Kazuorz commented on wiki/Community/Project_Loved/es.md
> +Existen unos criterios mínimos que deben ser cumplidos por los beatmaps que son nominados a Amados. Cada modo de juego tiene sus propios criterios específicos de nominación y prioridad, pero todos lo
```suggestion
Existen unos criterios mínimos que deben cumplir los beatmaps que son nominados a Amados. Cada modo de juego tiene sus propios criterios específicos de nominación y prioridad, pero todos los modos de juego siguen las siguientes reglas: 
```

2023-11-03 20:23 UTC, Kazuorz commented on wiki/Community/Project_Loved/es.md
> +Los beatmaps nominados son publicados en el [foro Project Loved](https://osu.ppy.sh/community/forums/120), donde los miembros de la comunidad pueden votar si quieren que el beatmap sea Amado o no. Lo
```suggestion
Los beatmaps nominados se publican en el [foro Project Loved](https://osu.ppy.sh/community/forums/120), donde los miembros de la comunidad pueden votar si quieren que el beatmap sea Amado o no. Los mapas que alcancen el 80 % de los votos «Sí» al final de las encuestas serán promovidos a la categoría Amados.
```

2023-11-03 20:34 UTC, agatemosu approved these changes

2023-11-10 22:09 UTC, Walavouchey submitted a review, later dismissed

2023-11-11 03:16 UTC, MChecaH approved these changes
Should be better now. More faithful to the original article.

2023-11-11 07:06 UTC, cl8n approved these changes

2023-11-11 07:08 UTC, cl8n commented
in the future try to use commit names that explain what you're changing in that commit, rather than generic messages like "Update es.md"

otherwise looks good thx o/

2023-11-11 07:08 UTC, merged