[ES] Add `Legal/Copyright`
ppy/osu-wiki pull request #10313
Opened 2023-10-29 11:44 UTC by agatemosu

RandomeLoL wants this

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-23 10:54 UTC, MChecaH requested changes
Proper "Designated Agent" capitalization + One grammar related change.

2023-11-23 10:54 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +La información de contacto del agente designado por osu! para recibir notificaciones de presuntas infracciones («agente designado») figura al final de esta política y está archivada en la Oficina de
En el contexto legal, dicho agente ha de capitalizarse como nombre propio que es. Lo otro puede seguir en minúsculas ya que transliterar la cláusula entera no tiene mucho sentido.
```suggestion
La información de contacto del agente designado por osu! para recibir notificaciones de presuntas infracciones («Agente Designado») figura al final de esta política y está archivada en la Oficina de Derechos de Autor de Estados Unidos (<https://www.copyright.gov/dmca-directory/>). osu! se toma muy en serio los derechos de autor y otros derechos de propiedad intelectual.
```

2023-11-23 10:54 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +Si crees que el contenido que reside o es accesible a través del sitio web o el servicio de osu! infringe tus derechos de autor, envía una notificación de presunta infracción de derechos de autor que
```suggestion
Si crees que el contenido que reside o es accesible a través del sitio web o el servicio de osu! infringe tus derechos de autor, envía una notificación de presunta infracción de derechos de autor que contenga la siguiente información al Agente Designado que se indica a continuación (consulta a un asesor jurídico o consulta 17 U.S.C. 512(c) para confirmar estos requisitos):
```

2023-11-23 10:54 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +Una vez que el agente designado reciba una notificación completa y adecuada de la presunta infracción de los derechos de autor, o si osu! llega a creer de buena fe que un archivo del servicio de osu!
```suggestion
Una vez que el Agente Designado reciba una notificación completa y adecuada de la presunta infracción de los derechos de autor, o si osu! llega a creer de buena fe que un archivo del servicio de osu! puede contener material que infringe los derechos de autor:
```

2023-11-23 10:54 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +2. notificar al proveedor del contenido, miembro o usuario que ha eliminado o inhabilitado el acceso al contenido; y
```suggestion
2. notificar al proveedor del contenido, miembro o usuario que se ha eliminado o inhabilitado el acceso al contenido; y
```

2023-11-23 10:54 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +Si el proveedor del contenido, miembro o usuario cree que el contenido que fue eliminado o al cual el acceso fue inhabilitado no está infringiendo, o si el proveedor del contenido, miembro o usuario
```suggestion
Si el proveedor del contenido, miembro o usuario cree que el contenido que fue eliminado o al cual el acceso fue inhabilitado no está infringiendo, o si el proveedor del contenido, miembro o usuario cree que tiene el derecho de publicar y usar tal contenido por parte del titular de los derechos de autor, su agente o conforme a la ley, el proveedor del contenido, miembro o usuario puede enviar una contranotificación que contenga la siguiente información al Agente Designado que se detalla a continuación:
```

2023-11-23 10:54 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +Si el agente designado recibe una contranotificación, osu! podrá enviar una copia de la misma a la parte denunciante original informándole de que puede sustituir el contenido eliminado o dejar de inh
```suggestion
Si el Agente Designado recibe una contranotificación, osu! podrá enviar una copia de la misma a la parte denunciante original informándole de que puede sustituir el contenido eliminado o dejar de inhabilitarlo en un plazo de 10 días laborables. A menos que el propietario de los derechos de autor interponga una demanda judicial contra el proveedor del contenido, miembro o usuario, el contenido retirado podrá ser sustituido, o el acceso al mismo restaurado, en un plazo de 10 a 14 días laborales o más tras la recepción de la contranotificación, a discreción exclusiva de osu!.
```

2023-11-23 10:54 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +## Datos de contacto del agente designado
```suggestion
## Datos de contacto del Agente Designado
```

2023-11-24 19:54 UTC, agatemosu commented on wiki/Legal/Copyright/es.md
> +2. notificar al proveedor del contenido, miembro o usuario que ha eliminado o inhabilitado el acceso al contenido; y
no le veo sentido a añadir eso, si el proveedor/miembro/usuario es el que ha eliminado el contenido

2023-11-24 20:39 UTC, MChecaH commented on wiki/Legal/Copyright/es.md
> +2. notificar al proveedor del contenido, miembro o usuario que ha eliminado o inhabilitado el acceso al contenido; y
Se puede resolver pues.

2023-11-24 20:39 UTC, MChecaH approved these changes

2023-11-29 11:45 UTC, TicClick approved these changes

2023-11-29 11:47 UTC, merged