Hype es
ppy/osu-wiki pull request #10319
Opened 2023-10-29 14:26 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-29 17:02 UTC, DoryanR commented
The file you've translated is `en.md`, not `es.md`. Moreover, it contains the same changes from #10317

2023-10-29 17:02 UTC, agatemosu commented
thanks

2023-10-29 17:04 UTC, agatemosu commented
> Moreover, it contains the same changes from #10317

because this branch is based on a commit of that PR

2023-10-29 20:04 UTC, UnknownOsu requested changes

2023-10-29 20:04 UTC, UnknownOsu commented on wiki/Beatmap/Hype/es.md
> +Cada [beatmap](/wiki/Beatmap) [pendiente](/wiki/Beatmap/Category#trabajos-en-progreso-y-pendientes) tiene un **tren del hype** que representa aproximadamente cuántas personas están interesadas en ver
```suggestion
Cada [beatmap](/wiki/Beatmap) [pendiente](/wiki/Beatmap/Category#trabajos-en-progreso-y-pendientes) tiene un **tren del hype** que representa aproximadamente cuántas personas están interesadas en ver el mapa [clasificado](/wiki/Beatmap/Category#clasificados). Los usuarios pueden publicar [discusiones de beatmaps](/wiki/Beatmap_discussion) especiales en la pestaña `General (Todas las dificultades)` con la opción `¡Hype!` para contribuir al tren del hype de un mapa.
```

2023-10-29 20:04 UTC, UnknownOsu commented on wiki/Beatmap/Hype/es.md
> +Los beatmaps necesitan al menos 5 hypes (una barra completa del tren de hype) para ser elegibles para la [nominación](/wiki/Beatmap_ranking_procedure#nominations), un paso para clasificar el mapa.
```suggestion
Los beatmaps necesitan al menos 5 hypes (una barra completa del tren del hype) para ser elegibles para la [nominación](/wiki/Beatmap_ranking_procedure#nominations), un paso para clasificar el mapa.
```

2023-11-03 17:13 UTC, UnknownOsu approved these changes

2023-11-04 14:29 UTC, Hiviexd approved these changes

2023-11-04 14:30 UTC, merged