[ES] Add `Rules/Song_content_rules` and `Rules/Visual_content_considerations`
ppy/osu-wiki pull request #10322
Opened 2023-10-29 19:38 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-29 19:50 UTC, agatemosu commented on wiki/Rules/Song_content_rules/es.md
> +# Reglas de contenido de la canción
```suggestion
# Reglas del contenido de canciones
```

2023-10-29 19:50 UTC, agatemosu commented on wiki/Rules/Song_content_rules/es.md
> +No nos adherimos a ningún «final» particular de un espectro político: osu! es estrictamente apolítico y queremos que la gente se divierta, no que inicie rencillas o riñas sobre política.
```suggestion
No nos adherimos a ningún «final» particular de un espectro político; osu! es estrictamente apolítico y queremos que la gente se divierta, no que inicie rencillas o riñas sobre política.
```

2023-10-29 19:50 UTC, agatemosu commented on wiki/Rules/Song_content_rules/es.md
> +Cada vez que se elimine su envío, el miembro que preside el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (NAT) o el [Global Moderation Team](/wiki/People/Global_Moderation_Te
```suggestion
Cada vez que se elimine tu envío, el miembro que preside el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (NAT) o el [Global Moderation Team](/wiki/People/Global_Moderation_Team) (GMT) te dará una explicación responsable de la eliminación con razonamientos que justifiquen la eliminación.
```

2023-10-29 19:50 UTC, agatemosu commented on wiki/Rules/Song_content_rules/es.md
> +Puedes impugnar esto con ellos a través de un mensaje privado si así lo deseas, o buscar las opiniones de otros para fundamentar tu afirmación sobre la idoneidad de la canción. Si aún no puede encont
```suggestion
Puedes impugnar esto con ellos a través de MP si así lo deseas, o buscar las opiniones de otros para fundamentar tu afirmación sobre la idoneidad de la canción. Si aún no puedes encontrar puntos en común en este frente, tu reclamo puede elevarse a una votación de consenso entre los miembros actuales del NAT, quienes decidirán colectivamente si su camino es aceptable o no.
```

2023-10-29 19:55 UTC, agatemosu commented on wiki/Rules/Visual_content_considerations/es.md
> +- beatmaps enviados, **incluso aquellos etiquetados como [explícito](/wiki/Rules/Explicit_content)**
```suggestion
- beatmaps enviados, **incluso aquellos etiquetados como [explícitos](/wiki/Rules/Explicit_content)**
```

2023-10-29 19:55 UTC, agatemosu commented on wiki/Rules/Visual_content_considerations/es.md
> +Con el fin de mantener las cosas lo más limpias posible, la regla comunitaria 5 se aplica a cualquier cosa que pueda considerarse razonablemente «cuestionable».
```suggestion
Con el fin de mantener las cosas lo más limpias posible, la quinta regla de la comunidad se aplica a cualquier cosa que pueda considerarse razonablemente «cuestionable».
```

2023-10-29 19:55 UTC, agatemosu commented on wiki/Rules/Visual_content_considerations/es.md
> +Además, las imágenes o los elementos visuales que puedan considerarse razonablemente de mala calidad (ya sea en cuanto a la calidad objetiva de la imagen o a la composición/creación subjetiva) tambié
```suggestion
Además, las imágenes o los elementos visuales que puedan considerarse razonablemente de mala calidad (ya sea en cuanto a la calidad objetiva de la imagen o a la composición/creación subjetiva) también podrán no usarse en un beatmap en los casos en que no estén directamente relacionados con ningún tema relevante.
```

2023-10-29 19:55 UTC, agatemosu commented on wiki/Rules/Visual_content_considerations/es.md
> +Las imágenes que se utilizan en cualquier parte del sitio fuera de un beatmap (avatares, portadas de perfiles, páginas de usuario, etc.) **no** están sujetas al procedimiento de votación que se expli
```suggestion
Las imágenes que se usan en cualquier parte del sitio fuera de un beatmap (avatares, portadas de perfiles, páginas de usuario, etc.) **no** están sujetas al procedimiento de votación que se explica a continuación y pueden eliminarse en cualquier momento a discreción del Global Moderation Team.
```

2023-10-29 19:55 UTC, agatemosu commented on wiki/Rules/Visual_content_considerations/es.md
> +Si no estás seguro acerca de una imagen que se incluirá en un beatmap de alguna manera, **envía una solicitud a través de [la página de envíos de informes de los Beatmap Nominators](https://bn.mapper
```suggestion
Si no estás seguro acerca de una imagen que se incluirá en un beatmap de alguna manera, **envía una solicitud a través de [la página de envíos de reportes de los Beatmap Nominators](https://bn.mappersguild.com/reports).** La imagen será sometida a votación que deberá ser aprobada por una mayoría considerable, o será automáticamente denegada.
```

2023-10-29 20:19 UTC, agatemosu approved these changes
maybe review from randomelol since he asked for this

2023-10-29 20:21 UTC, agatemosu reviewed
\+ the CI fix

2023-10-29 20:21 UTC, agatemosu commented on wiki/Rules/Song_content_rules/es.md
> +Con el fin de mantener un juego sobre el ritmo estrictamente sobre el ritmo y de acuerdo con la [regla de la comunidad](/wiki/Rules#community-rules) n.º 3, el contenido que la administración consider
```suggestion
Con el fin de mantener un juego sobre el ritmo estrictamente sobre el ritmo y de acuerdo con la [regla de la comunidad](/wiki/Rules#reglas-de-la-comunidad) n.º 3, el contenido que la administración considere excesivamente político no está permitido.
```

2023-10-29 20:21 UTC, agatemosu commented on wiki/Rules/Visual_content_considerations/es.md
> +Según la [regla de la comunidad n.º 5](/wiki/Rules#community-rules), todo el contenido visual enviado o subido a osu! debe considerarse apropiado para un juego para todas las edades.
```suggestion
Según la [regla de la comunidad n.º 5](/wiki/Rules#reglas-de-la-comunidad), todo el contenido visual enviado o subido a osu! debe considerarse apropiado para un juego para todas las edades.
```

2023-11-23 11:26 UTC, MChecaH requested changes
Unos pocos cambios a hacer.

2023-11-23 11:26 UTC, MChecaH commented on wiki/Rules/Song_content_rules/es.md
> +- Extremadamente e insoportablemente ruidosas
Esta cláusula quiere evitar canciones que sean insoportablemente altas en el contexto de volumen. Teniendo en cuenta que hay canciones que son ruidosas de por si pero no necessariamente altas, esto debería de dejar más claro que se intenta evitar.
```suggestion
- Extremadamente e insoportablemente estridentes
```

2023-11-23 11:26 UTC, MChecaH commented on wiki/Rules/Song_content_rules/es.md
> +Con el fin de mantener un juego sobre el ritmo estrictamente sobre el ritmo y de acuerdo con la [regla de la comunidad](/wiki/Rules#reglas-de-la-comunidad) n.º 3, el contenido que la administración c
Queda algo raro decir un `juego sobre el ritmo` implícitamente en Español. Podemos mantener el segundo siempre y cuando mencionemos que es un `juego de ritmo`.
```suggestion
Con el fin de mantener un juego de ritmo estrictamente sobre el ritmo y de acuerdo con la [regla de la comunidad](/wiki/Rules#reglas-de-la-comunidad) n.º 3, el contenido que la administración considere excesivamente político no está permitido.
```

2023-11-23 11:26 UTC, MChecaH commented on wiki/Rules/Song_content_rules/es.md
> +Cada vez que se elimine tu envío, el miembro que preside el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (NAT) o el [Global Moderation Team](/wiki/People/Global_Moderation_Te
`responsible` en este contexto no es que la explicación sea "responsable", si no que el miembro responsable de la eliminación se hará cargo de la explicación. Reformatearía esta oración un poco.
```suggestion
Cada vez que se elimine tu envío, el miembro que preside el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (NAT) o el [Global Moderation Team](/wiki/People/Global_Moderation_Team) (GMT) responsable de la eliminación te dará una explicación con razonamientos que justifiquen la eliminación.
```

2023-11-23 11:26 UTC, MChecaH commented on wiki/Rules/Song_content_rules/es.md
> +Puedes impugnar esto con ellos a través de MP si así lo deseas, o buscar las opiniones de otros para fundamentar tu afirmación sobre la idoneidad de la canción. Si aún no puedes encontrar puntos en c
```suggestion
Puedes impugnar esto con ellos a través de MP si así lo deseas, o buscar las opiniones de otros para fundamentar tu afirmación sobre la idoneidad de la canción. Si aún no puedes encontrar puntos en común en este frente, tu reclamo puede elevarse a una votación de consenso entre los miembros actuales del NAT, quienes decidirán colectivamente si su canción es aceptable o no.
```

2023-11-23 11:26 UTC, MChecaH commented on wiki/Rules/Song_content_rules/es.md
> +Excluyendo las cargas muy inapropiadas, todos los usuarios tienen un **margen de libertad para un envío** antes de que se impongan sanciones debido a la naturaleza incierta de esta decisión. Una vez
Traducir Uploads a Cargar queda algo difícil de entender. Cambiaría la oración un poco.
```suggestion
Excluyendo las canciones muy inapropiadas, todos los usuarios tienen un **margen de libertad para un envío** antes de que se impongan sanciones debido a la naturaleza incierta de esta decisión. Una vez transcurrido este margen, los usuarios que continuamente opten por subir canciones inapropiadas se enfrentarán a un [silencio](/wiki/Silence) de 42 horas de duración junto con la eliminación de su envío.
```

2023-11-23 11:26 UTC, MChecaH commented on wiki/Rules/Visual_content_considerations/es.md
> +Además, las imágenes o los elementos visuales que puedan considerarse razonablemente de mala calidad (ya sea en cuanto a la calidad objetiva de la imagen o a la composición/creación subjetiva) tambié
Más "akin" al significado original, ya que esto es una posibilidad.
```suggestion
Además, las imágenes o los elementos visuales que puedan considerarse razonablemente de mala calidad (ya sea en cuanto a la calidad objetiva de la imagen o a la composición/creación subjetiva) también podrían no permitirse en un beatmap en los casos en que no estén directamente relacionados con ningún tema relevante.
```

2023-11-23 22:14 UTC, MChecaH approved these changes

2023-11-24 07:44 UTC, TicClick approved these changes

2023-11-24 07:49 UTC, merged