[ES] Add `Ranking criteria`
ppy/osu-wiki pull request #10320
Opened 2023-10-29 16:39 UTC by agatemosu

por fin

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-29 22:07 UTC, UnknownOsu requested changes

2023-10-29 22:20 UTC, agatemosu commented on wiki/Ranking_criteria/es.md
> +  - Nota: Si un corte no oficial contiene secciones coincidentes en el mismo orden y tiene aproximadamente la misma duración que el tamaño oficial para televisión, una versión corta o una versión par
ya es correcto, cover viene de cubrir y el término correcto es "versión". los dos están en femenino

2023-11-10 07:14 UTC, MChecaH requested changes
Quick, tiny comments to be made to grammar and ensuring it stays true to the original article.

2023-11-10 07:14 UTC, MChecaH commented on wiki/Ranking_criteria/es.md
> +- **Los objetos deben encajar com menos de 2 ms de cualquier marca de la línea de tiempo.** [AiMod](/wiki/Client/Beatmap_editor/AiMod) informará de estos problemas, así como de los raros falsos posit
```suggestion
- **Los objetos deben encajar con menos de 2 ms de cualquier marca de la línea de tiempo.** [AiMod](/wiki/Client/Beatmap_editor/AiMod) informará de estos problemas, así como de los raros falsos positivos. Los falsos positivos se producen principalmente en los extremos de los sliders y en los repetidores, y deben verificarse manualmente o con otras herramientas. Los objetos de una sección musical que requieran divisores de tiempo no compatibles (p. ej. 1/11) pueden:
```

2023-11-10 07:14 UTC, MChecaH commented on wiki/Ranking_criteria/es.md
> +- **El archivo de audio y los archivos de hitsounds de un beatmap no deben presentar distorsiones de sonido audibles e injustificadas**, como recortes, silenciamientos o crujidos que claramente no ha
`ni` por si solo ya actua como conjunción. El `o` es redundante en tal caso.
```suggestion
- **El archivo de audio y los archivos de hitsounds de un beatmap no deben presentar distorsiones de sonido audibles e injustificadas**, como recortes, silenciamientos o crujidos que claramente no han sido intencionados por el artista ni forman parte de la identidad de la canción. Esto se determina mejor escuchando el audio que usando un programa informático.
```

2023-11-20 16:01 UTC, agatemosu commented
i forgot sorry i'm looking at the rest

2023-11-23 17:42 UTC, TicClick approved these changes

2023-11-23 17:43 UTC, TicClick commented
(approved to get this merged in sooner rather wait another period of time for the PR from https://github.com/ppy/osu-wiki/pull/10320#issuecomment-1784162379 to become ready)

2023-11-23 17:45 UTC, merged

2023-11-23 17:55 UTC, agatemosu commented
> (approved to get this merged in sooner rather wait another period of time for the PR from [#10320 (comment)](https://github.com/ppy/osu-wiki/pull/10320#issuecomment-1784162379) to become ready)

OK so the unknownosu review will be in other pr