[ES] Retranslate `Rules` and clean up `Update Help centre/Account restrictions`
ppy/osu-wiki pull request #10321
Opened 2023-10-29 16:50 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-10-31 01:33 UTC, UnknownOsu requested changes

2023-10-31 01:33 UTC, UnknownOsu commented on wiki/Rules/es.md
> +1. **Cada jugador solo puede tener *UNA* cuenta, siempre**. La *primera* cuenta que crees al registrarte será tu única cuenta osu! desde el momento de su creación y para siempre. Esta cuenta eres TÚ.
```suggestion
1. **Cada jugador solo puede tener *UNA* cuenta, siempre**. La *primera* cuenta que crees al registrarte será tu única cuenta de osu! desde el momento de su creación y para siempre. Esta cuenta eres TÚ. No es de nadie más —ni de tu hermano, ni de tu madre, ni de tu hermana, ni de tu amigo—, eres TÚ. No compartas tu cuenta con nadie más. No podrás crear una nueva si pierdes el acceso a ella. Mantenla a salvo.
```

2023-11-16 03:14 UTC, UnknownOsu requested changes

2023-11-16 03:14 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  Una restricción es un tiempo fuera en la comunidad forzada a cuentas que exihiben comportamiento anormal, sospechoso o que rompe las reglas.
```suggestion
Una restricción es un tiempo fuera en la comunidad forzada a cuentas que exhiben una conducta anormal, sospechosa o que rompe las reglas.
```

2023-11-16 17:33 UTC, UnknownOsu approved these changes

2023-11-21 17:00 UTC, TicClick approved these changes

2023-11-21 17:02 UTC, merged