Update GBC 2023 Autumn wiki page (ZH+EN)
ppy/osu-wiki pull request #10336
Opened 2023-11-01 09:33 UTC by yobrevelc

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-02 01:51 UTC, untitledunrevised commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +The GB Cup 2022 Autumn was run by the Team GB and various community members.
```suggestion
The GB Cup 2023 Autumn was run by the Team GB and various community members.
```

2023-11-02 02:13 UTC, untitledunrevised requested changes
纯细节上的排版问题修整

2023-11-02 02:13 UTC, untitledunrevised commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| *All the other qualified players* | 2$ |
```suggestion
| *1st place* | $16 |
| *2nd place* | $13 |
| *3rd place* | $10 |
| *4-8th place* | $8 |
| *9–16th place* | $6 |
| *All the other qualified players* | $2 |
```

2023-11-02 02:13 UTC, untitledunrevised commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "季军") | 猫猫bot缎带, ¥120 |
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "冠军") | 个人资料页缎带，猫猫 bot 缎带，¥150 |
| ![Silver crown](/wiki/shared/crown-silver.png "亚军") | 猫猫 bot 缎带，¥150 |
| ![Bronze crown](/wiki/shared/crown-bronze.png "季军") | 猫猫 bot 缎带，¥120 |
```

2023-11-02 02:13 UTC, untitledunrevised commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +| *其他所有入选的选手* | ¥20 CNY |
```suggestion
| *冠军* | ¥200 |
| *亚军* | ¥150 |
| *季军* | ¥100 |
| *第 7-8 名* | ¥75 |
| *第 9-24 名* | ¥50 |
| *其他所有入选的选手* | ¥20 |
```

2023-11-02 02:13 UTC, untitledunrevised commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "季军") | ¥120 CNY |
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "冠军") | 个人资料页缎带，¥150 |
| ![Silver crown](/wiki/shared/crown-silver.png "亚军") | ¥150 |
| ![Bronze crown](/wiki/shared/crown-bronze.png "季军") | ¥120 |
```

2023-11-02 02:13 UTC, untitledunrevised commented on wiki/Tournaments/GBC/GBC_2023_Autumn/zh.md
> +| *其他所有入选的选手* | 2$ |
```suggestion
| *每场常规赛比赛胜利* | $6 |

| 资格赛排名 | 奖励 |
| :-: | :-- |
| *冠军* | $16 |
| *亚军* | $13 |
| *季军* | $10 |
| *第 4-8 名* | $8 |
| *第 9-16 名* | $6 |
| *其他所有入选的选手* | $2 |
```

2023-11-02 02:32 UTC, untitledunrevised commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Every Winning Match in Regular Stage | 6$ |
```suggestion
| Every Winning Match in Regular Stage | $6 |
```

2023-11-02 04:44 UTC, untitledunrevised approved these changes

2023-11-03 00:05 UTC, Walavouchey requested changes

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Every Winning Match in Regular Stage | ¥50 CNY |
what does "Every Winning Match in Regular Stage" this mean? it doesn't make sense rn
it should also be in sentence case

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Qualifier Placing | Prizes |
```suggestion
| Qualifier placing | Prizes |
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +### QQ Division
```suggestion
### QQ division
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +### Discord Division
```suggestion
### Discord division
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Team Placing | Prizes |
```suggestion
| Team placing | Prizes |
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Every Winning Match in Regular Stage | $6 |
same as above

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| *4-8th place* | $8 |
```suggestion
| *4–8th place* | $8 |
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Qualifier Placing | Prizes |
```suggestion
| Qualifier placing | Prizes |
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +The GB Cup 2023 Autumn was run by the Team GB and various community members.
why is this in past tense now? isn't the tournament still ongoing?

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Custom Mapper | *TBA* |
```suggestion
| SV mappool selector | ::{ flag=CN }:: [\[GB\]Mafufu](https://osu.ppy.sh/users/10884561), ::{ flag=VE }:: [Lott](https://osu.ppy.sh/users/13821222) |
| Custom mapper | *TBA* |
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +### QQ Division
```suggestion
### QQ division
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +### Discord Division
```suggestion
### Discord division
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Players need to choose a division according to their chat software, i.e. the Discord division or QQ division. Both the QQ division and Discord division will have an independent tournament, but u
```suggestion
   - Players need to choose a division according to their chat software, i.e. the Discord division or QQ division. The QQ division and Discord division will each have an independent tournament, but use same mappool.
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +3. Following the regular stage, the elimination stage will be played in both zones, called *playoffs*. The top 8 teams from the regular stage will advance to a winner bracket, other teams will get in
```suggestion
3. Following the regular stage, the elimination stage will be played in both divisions, called *playoffs*. The top 8 teams from the regular stage will advance to a winner bracket, other teams will get into loser bracket.
```

2023-11-03 00:05 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +1. The regular phase will be divided into two division, the Discord division and the QQ division.
```suggestion
1. The regular phase will be divided into two divisions, the Discord division and the QQ division.
```

2023-11-03 01:12 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Every Winning Match in Regular Stage | ¥50 CNY |
```suggestion
| *For every match won in the regular stage* | ¥50 CNY |
```

2023-11-03 01:12 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| Every Winning Match in Regular Stage | $6 |
```suggestion
| *For every match won in the regular stage* | $6 |
```

2023-11-03 01:28 UTC, Walavouchey commented
force-pushed to combine 40+ commits
in the future, apply reviews in batches as described in https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#applying-reviews

2023-11-03 01:28 UTC, Walavouchey approved these changes

2023-11-03 01:30 UTC, merged