[ES] Update `Client/Interface`
ppy/osu-wiki pull request #10343
Opened 2023-11-02 20:57 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-03 18:09 UTC, agatemosu commented on wiki/Client/Interface/es.md
> +| [`Precisión`](/wiki/Gameplay/Accuracy) | Con qué precisión jugaste el beatmap. Esto solo se cuenta cuando se supera tu puntuación anterior. |
```suggestion
| [`Precisión`](/wiki/Gameplay/Accuracy) | Con qué precisión jugaste el beatmap. Esto solo se cuenta cuando superas tu puntuación anterior. | Un promedio ponderado de la precisión de tus mejores puntuaciones. |
```

2023-11-03 18:27 UTC, agatemosu commented on wiki/Client/Interface/es.md
> +| `General` | Tu posición en la tabla de clasificación del mapa. Ten en cuenta que las puntuaciones con [mods](/wiki/Gameplay/Game_modifier) también aparecen en esta misma tabla de clasificación. | T
```suggestion
| `General` | Tu posición en la tabla de clasificación del mapa. Ten en cuenta que las puntuaciones con [mods](/wiki/Gameplay/Game_modifier) también aparecen en esta misma tabla de clasificación. | Tu [clasificación global](/wiki/Ranking#clasificación-por-puntos-de-rendimiento) contra todos en el mundo. |
```

2023-11-03 18:47 UTC, agatemosu commented on wiki/Client/Interface/es.md
>  ## Selección de canciones
Selector de canciones

2023-11-05 04:22 UTC, cl8n requested changes

2023-11-05 04:22 UTC, cl8n commented on wiki/Client/Interface/es.md
> +Artículo principal: [Búsqueda de beatmaps](/wiki/Beatmap_search)
```suggestion
*Artículo principal: [Búsqueda de beatmaps](/wiki/Beatmap_search)*
```

2023-11-05 04:28 UTC, cl8n approved these changes

2023-11-05 04:30 UTC, merged