[ES] Update `Contests`
ppy/osu-wiki pull request #10345
Opened 2023-11-02 20:58 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-02 22:48 UTC, agatemosu requested changes

2023-11-02 22:48 UTC, agatemosu commented on wiki/Contests/es.md
> +| Concurso n.º | Canción | Modo | ![Corona dorada][GCrown] | ![Corona de plata][SCrown] | ![Corona de bronce][BCrown] | Resultados |
Concurso núm.
Corona de oro

2023-11-02 22:48 UTC, agatemosu commented on wiki/Contests/es.md
> +| Iteración del concurso | Artista destacado | Modo | ![Corona dorada][GCrown] | ![Corona de plata][SCrown] | Equipo de screening #1 | Resultados |
que es screening

2023-11-02 22:48 UTC, agatemosu commented on wiki/Contests/es.md
> +| Concurso n.º  | Canción remezclada | ![Corona dorada][GCrown] (Ganador general) | ![Corona de plata][SCrown] (Subcampeón general) | Ganador de la votación de la comunidad | Resultados |
doble espacio

2023-11-02 22:48 UTC, agatemosu commented on wiki/Contests/es.md
> +**Best of/Community Choice** es un concurso de votación pública que se lleva a cabo anualmente para determinar los beatmaps más populares <!-- https://osu.ppy.sh/home/news/2021-02-05-community-choice
no hace falta el comentario para traducir

2023-11-02 22:48 UTC, agatemosu commented on wiki/Contests/es.md
> +| Concurso n.º  | Tema | ![Corona dorada][GCrown] | ![Corona de plata][SCrown] | ![Corona de bronce][BCrown] | Resultados |
doble espacio

2023-11-02 22:48 UTC, agatemosu commented on wiki/Contests/es.md
> +| [#10 (Summer 2017)](https://osu.ppy.sh/home/news/2017-06-15-mocha-fanart-contest-now-open) | Mocha en verano | ::{ flag=FR }:: [Sylux6](https://osu.ppy.sh/users/2607507) | ::{ flag=PL }:: [sh00p](h
prefiero que las temporadas del año estén en español

2023-11-02 22:58 UTC, UnknownOsu commented on wiki/Contests/es.md
> +| Iteración del concurso | Artista destacado | Modo | ![Corona dorada][GCrown] | ![Corona de plata][SCrown] | Equipo de screening #1 | Resultados |
Es más usado para torneos, pero [acá](https://osu.ppy.sh/wiki/es/Tournaments/Official_support#tournament-screening) puedes ver de qué trata.

Diría que es un proceso de selección para hacer cumplir las reglas del torneo, en este caso, concurso

2023-11-02 23:04 UTC, UnknownOsu commented on wiki/Contests/es.md
> +| [#10 (Summer 2017)](https://osu.ppy.sh/home/news/2017-06-15-mocha-fanart-contest-now-open) | Mocha en verano | ::{ flag=FR }:: [Sylux6](https://osu.ppy.sh/users/2607507) | ::{ flag=PL }:: [sh00p](h
¿Segura? Es el nombre del concurso, además al lado se explica de que va el tema del concurso

2023-11-03 17:37 UTC, agatemosu commented on wiki/Contests/es.md
>  | [#2](https://osu.ppy.sh/community/forums/topics/206852) | osu! Alrededor del mundo | ::{ flag=ID }:: [TapponNANA](https://osu.ppy.sh/users/2496203) | ::{ flag=PH }:: [hews](https://osu.ppy.sh/users
```suggestion
| [#2](https://osu.ppy.sh/community/forums/topics/206852) | osu! alrededor del mundo | ::{ flag=ID }:: [TapponNANA](https://osu.ppy.sh/users/2496203) | ::{ flag=PH }:: [hews](https://osu.ppy.sh/users/1715930) | ::{ flag=US }:: [gendo0032](https://osu.ppy.sh/users/3191089) | [#1](https://osu.ppy.sh/home/news/2014-07-04-second-official-osu-fanart-contest-results) |
```

2023-11-03 18:27 UTC, agatemosu approved these changes

2023-11-05 03:40 UTC, cl8n approved these changes

2023-11-05 03:40 UTC, merged