[ES] Clean up `Beatmap/Approach rate`
ppy/osu-wiki pull request #10356
Opened 2023-11-03 19:34 UTC by agatemosu

again

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-03 19:43 UTC, UnknownOsu requested changes

2023-11-03 19:43 UTC, UnknownOsu commented on wiki/Beatmap/Approach_rate/es.md
>  En [osu!taiko](/wiki/Game_mode/osu!taiko) y [osu!mania](/wiki/Game_mode/osu!mania), la configuración de la velocidad de aproximación no tiene efecto. La velocidad de desplazamiento en ambos modos est
```suggestion
En [osu!taiko](/wiki/Game_mode/osu!taiko) y [osu!mania](/wiki/Game_mode/osu!mania), la configuración de la velocidad de aproximación no tiene efecto. La velocidad de desplazamiento en ambos modos está controlada por la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity), que depende del [BPM](/wiki/Music_theory/Tempo) y del multiplicador de la velocidad del slider. Además, en osu!mania puede ser personalizada [por el propio jugador](/wiki/Game_mode/osu!mania#cambio-de-velocidad).
```

2023-11-03 19:43 UTC, UnknownOsu commented on wiki/Beatmap/Approach_rate/es.md
>  Consulte la infografía y las fórmulas a continuación para obtener una descripción general:
```suggestion
Consulta la infografía y las fórmulas a continuación para obtener una descripción general:
```

2023-11-03 19:43 UTC, UnknownOsu commented on wiki/Beatmap/Approach_rate/es.md
> +Si bien Half Time y Double Time no cambian el valor de AR, la diferencia de velocidad conduce a un cambio aparente de AR. Las AR de HT/DT se denominan comúnmente en términos de su valor percibido. Po
```suggestion
Si bien Half Time y Double Time no cambian el valor de AR, la diferencia de velocidad conduce a un cambio aparente de AR. Los AR de HT/DT se denominan comúnmente en términos de su valor percibido. Por ejemplo, «AR 8 + DT» también se puede escribir como «AR 9,6».
```

2023-11-03 19:43 UTC, agatemosu commented on wiki/Beatmap/Approach_rate/es.md
> +Si bien Half Time y Double Time no cambian el valor de AR, la diferencia de velocidad conduce a un cambio aparente de AR. Las AR de HT/DT se denominan comúnmente en términos de su valor percibido. Po
las tasas de aproximación

2023-11-03 19:43 UTC, agatemosu commented on wiki/Beatmap/Approach_rate/es.md
>  En [osu!taiko](/wiki/Game_mode/osu!taiko) y [osu!mania](/wiki/Game_mode/osu!mania), la configuración de la velocidad de aproximación no tiene efecto. La velocidad de desplazamiento en ambos modos est
los pulsos por minuto

2023-11-03 19:49 UTC, UnknownOsu commented on wiki/Beatmap/Approach_rate/es.md
>  En [osu!taiko](/wiki/Game_mode/osu!taiko) y [osu!mania](/wiki/Game_mode/osu!mania), la configuración de la velocidad de aproximación no tiene efecto. La velocidad de desplazamiento en ambos modos est
Creo que nadie traduce lo que lee cuando se supone que está en español, así que creo que es mejor darle coherencia a lo que está puesto en lugar de poder causar confusión. Igual habla de singular en el original y no de varios BPM

Lo mismo con el AR en la primera parte

2023-11-03 20:06 UTC, agatemosu commented on wiki/Beatmap/Approach_rate/es.md
>  En [osu!taiko](/wiki/Game_mode/osu!taiko) y [osu!mania](/wiki/Game_mode/osu!mania), la configuración de la velocidad de aproximación no tiene efecto. La velocidad de desplazamiento en ambos modos est
no creo que se refiera a 1 bpm, acepto cambiar AR

2023-11-03 20:19 UTC, UnknownOsu commented on wiki/Beatmap/Approach_rate/es.md
>  En [osu!taiko](/wiki/Game_mode/osu!taiko) y [osu!mania](/wiki/Game_mode/osu!mania), la configuración de la velocidad de aproximación no tiene efecto. La velocidad de desplazamiento en ambos modos est
Ok.

Si quieres, puedes agregar el `la`, creo que le da más sentido

2023-11-03 20:53 UTC, UnknownOsu approved these changes

2023-11-04 14:18 UTC, Hiviexd approved these changes

2023-11-04 14:20 UTC, merged