[ES] Add missing Disambiguation articles
ppy/osu-wiki pull request #10367
Opened 2023-11-04 11:08 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-05 04:55 UTC, UnknownOsu requested changes

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Fail/es.md
> +- No superar un [beatmap](/wiki/Beatmap)
```suggestion
- No pasar un [beatmap](/wiki/Beatmap)
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Fail/es.md
> +- Estar en [estado fallido](/wiki/Storyboard/Scripting/General_Rules#layers) durante una [pausa](/wiki/Beatmap/Break) de un beatmap
```suggestion
- Estar en [estado fallido](/wiki/Storyboard/Scripting/General_Rules#layers) durante un [descanso](/wiki/Beatmap/Break) de un beatmap
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Rank/es.md
> +- A [letter grade](/wiki/Gameplay/Grade)
```suggestion
- La [letra de un grado](/wiki/Gameplay/Grade)
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Score/es.md
> +- El propio [algoritmo de puntuación](/wiki/Gameplay/Score)
```suggestion
- El propio [algoritmo de la puntuación](/wiki/Gameplay/Score)
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Snapping/es.md
> +- [Anclaje al ritmo](/wiki/Beatmapping/Snapping), la posición de un objeto dentro de un único compás musical, que se divide automáticamente usando el [beat snap divisor](/wiki/Client/Beatmap_editor/B
```suggestion
- [Ajuste de ritmo](/wiki/Beatmapping/Snapping), la posición de un objeto dentro de un único compás musical, que se divide automáticamente usando el [divisor de ritmo](/wiki/Client/Beatmap_editor/Beat_snap_divisor)
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Snapping/es.md
> +- [Anclaje a la rejilla](/wiki/Beatmapping/Grid_snapping), la posición de un objeto en el campo de juego
```suggestion
- [Ajuste a la rejilla](/wiki/Beatmapping/Grid_snapping), la posición de un objeto en el campo de juego
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Snapping/es.md
> +## Gameplay
```suggestion
## Jugabilidad
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Snapping/es.md
> +- [Dash snapping](/wiki/Gameplay/Dash_snapping), un término de [osu!catch](/wiki/Game_mode/osu!catch) que describe el movimiento requerido por un jugador para coger la siguiente fruta
```suggestion
- [Dash snapping](/wiki/Gameplay/Dash_snapping), un término de [osu!catch](/wiki/Game_mode/osu!catch) que describe el movimiento requerido por un jugador para atrapar la siguiente fruta
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Star/es.md
> +   - Algunos ejemplos son ajustes en el tiempo, espaciado incorrecto de los tiempos en algunas zonas o creación de versiones de dificultad adicional.
```suggestion
   - Algunos ejemplos son los ajustes en la temporización, espaciado de ritmo incorrecto en algunas zonas o la creación de versiones de dificultad adicional.
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Star/es.md
> +2. Otro término para «clasificación por estrellas».
```suggestion
2. Otro término para «calificación por estrellas».
```

2023-11-05 04:55 UTC, UnknownOsu commented on wiki/Disambiguation/Star/es.md
> +4. Otro término para «[Star Priority](/wiki/Modding/Star_priority)».
```suggestion
4. Otro término para «[prioridad de estrellas](/wiki/Modding/Star_priority)».
```

2023-11-21 21:28 UTC, UnknownOsu approved these changes

2023-11-29 15:50 UTC, UnknownOsu requested changes

2023-11-29 15:50 UTC, UnknownOsu commented on wiki/Beatmapping/Beat_snapping/es.md
> +El **ajuste de ritmo** (a menudo simplemente *snapping*) es la posición de un [objeto](/wiki/Gameplay/Hit_object) en la [línea de tiempo de los objetos](/wiki/Client/Beatmap_editor/Timelines#hit-obje
```suggestion
El **ajuste de ritmo** (a menudo simplemente *snapping*) es la posición de un [objeto](/wiki/Gameplay/Hit_object) en la [línea de tiempo de los objetos](/wiki/Client/Beatmap_editor/Timelines#hit-objects) en el [editor de beatmaps](/wiki/Client/Beatmap_editor). Cambiar el [divisor del ajuste de ritmo](/wiki/Client/Beatmap_editor/Beat_snap_divisor) permite que los objetos se ajusten a diferentes marcas cuando se mueven en la línea de tiempo.
```

2023-11-29 15:50 UTC, UnknownOsu commented on wiki/Beatmapping/Beat_snapping/es.md
>  El concepto de anclaje se basa en los principios comunes de la [cuantización musical](https://es.wikipedia.org/wiki/Cuantificación_(procesado_de_audio)) y estructura musical. Según ellos, las notas e
```suggestion
El concepto de snapping se basa en los principios comunes de la [cuantización musical](https://es.wikipedia.org/wiki/Cuantificación_(procesado_de_audio)) y estructura musical. Según ellos, las notas en la mayoría de las canciones tienen posiciones predecibles, que se basan en la duración de las fracciones de un [tempo único](/wiki/Music_theory/Beat). Al usar una división de ritmo adecuada, que puede variar a lo largo de una canción, los mappers alinean los objetos con las notas de una pieza musical.
```

2023-11-29 15:50 UTC, UnknownOsu commented on wiki/Disambiguation/Rank/es.md
> +# Rango (disambiguation)
```suggestion
# Rango (desambiguación)
```

2023-11-29 21:42 UTC, UnknownOsu approved these changes

2023-12-06 07:57 UTC, TicClick approved these changes

2023-12-06 07:57 UTC, merged