[ES] Native review of missing `G` articles
ppy/osu-wiki pull request #10365
Opened 2023-11-03 23:54 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Native review of G articles listed in the `No native review` section according to osu! wiki status in spanish

2023-11-14 19:31 UTC, agatemosu requested changes

2023-11-14 19:31 UTC, agatemosu commented on wiki/Gameplay/Hit_object/Spinner/es.md
> +El número máximo de giros por minuto que se puede lograr es 477, que también es la velocidad a la que el modificador del juego [Auto](/wiki/Gameplay/Game_modifier/Auto) gira mientras que el modificad
```suggestion
El número máximo de giros por minuto que se puede lograr es 477, que también es la velocidad a la que el modificador del juego [Auto](/wiki/Gameplay/Game_modifier/Auto) gira, mientras que el modificador del juego [Spun Out](/wiki/Gameplay/Game_modifier/Spun_Out) gira más lento a 287 giros por minuto.
```

2023-11-14 22:18 UTC, agatemosu reviewed
tags, this Was for who put the stable term

2023-11-14 22:18 UTC, agatemosu commented on wiki/Gameplay/Hit_object/Slider/Sliderbody/es.md
> +  - slider
```suggestion
  - deslizador
```

2023-11-14 22:18 UTC, agatemosu commented on wiki/Gameplay/Hit_object/Slider/Slider_velocity/es.md
>  ---
```suggestion
  - velocidad del slider
  - deslizador
 ---
```

2023-11-14 22:18 UTC, agatemosu commented on wiki/Gameplay/Hit_object/Slider/Sliderhead/es.md
> +  - slider
```suggestion
  - deslizador
```

2023-11-14 22:18 UTC, agatemosu commented on wiki/Gameplay/Hit_object/Slider/Slidertail/es.md
> +  - slider
```suggestion
  - deslizador
```

2023-11-15 07:24 UTC, agatemosu commented on wiki/Gameplay/Hit_object/Slider/Slider_velocity/es.md
> + ---
mi móvil 😡😡
```suggestion
---
```

2023-11-15 19:26 UTC, agatemosu approved these changes

2023-11-15 22:14 UTC, Hiviexd approved these changes

2023-11-15 22:17 UTC, merged