[ES] Native review of `History_of_osu!/2015`
ppy/osu-wiki pull request #10390
Opened 2023-11-06 00:03 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-02-06 12:33 UTC, JuanM4T requested changes

2024-02-06 12:33 UTC, JuanM4T commented on wiki/History_of_osu!/2015/es.md
> +El 31 de marzo de 2015, se agregaron las [osu!coins](/wiki/History_of_osu!/April_Fools#osu!coins) como moneda de broma en el juego para osu! como parte de una broma del día de los Inocentes. Las mone
```suggestion
El 31 de marzo de 2015, se agregaron las [osu!coins](/wiki/History_of_osu!/April_Fools#osu!coins) como moneda de broma en el juego para osu! como parte de una broma del día de los Inocentes. Las monedas se crearon para parodiar a los juegos móviles [free-to-play](https://es.wikipedia.org/wiki/Videojuego_gratuito) y su uso común de monedas en el juego y [microtransacciones](https://es.wikipedia.org/wiki/Microtransacción). Las osu!coins se retiraron rápidamente al día siguiente.
```

2024-02-10 13:56 UTC, JuanM4T approved these changes

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +El [canal de YouTube de osu!news](https://www.youtube.com/channel/UCZKQIqv9O2tddMNUMAxWaqQ) subió su [primer vídeo](https://www.youtube.com/watch?v=KQbudVxEjr8) al público el 8 de mayo de 2015. El ca
```suggestion
El [canal de YouTube osu!news](https://www.youtube.com/channel/UCZKQIqv9O2tddMNUMAxWaqQ) subió su [primer vídeo](https://www.youtube.com/watch?v=KQbudVxEjr8) al público el 8 de mayo de 2015. El canal estaba a cargo de varios miembros de la comunidad y tenía como objetivo crear vídeos sobre exhibiciones de skins, torneos, mapping, concursos y otras noticias de la comunidad.[^osu-weekly-9][^osu-news-welcome]
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +El teclado osu! (también conocido como el «teclado osu! 'nono'») se agregó a la osu!store el 30 de mayo de 2015, con un precio de venta minorista de alrededor de $40 en el lanzamiento. Anunciado inic
```suggestion
El teclado osu! (también conocido como el «teclado osu! 'nono'») se agregó a la osu!store el 30 de mayo de 2015, con un precio de venta minorista de alrededor de 40 $ en el lanzamiento. Anunciado inicialmente en un [tuit de peppy](https://twitter.com/ppy/status/603797988742336512) el 28 de mayo de 2015, solo había 100 teclados disponibles en el lanzamiento y se parecían más a un keypad que a un teclado de tamaño completo.[^osu-weekly-12][^ppy-tweet-osu-keyboards]
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
en la línea 50 pon `4 $`/`100 $`

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
56 osu team

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +*Nota: También existía un equipo privado de Slack que el osu! team utilizó para comunicaciones internas, que no era accesible o visible para usuarios externos; estos dos equipos eran independientes e
```suggestion
*Nota: También existía un equipo privado de Slack que el osu! team usó para comunicaciones internas, que no era accesible o visible para usuarios externos; estos dos equipos eran independientes entre sí.*
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +No obstante, el nuevo equipo era completamente público y estaba disponible para que cualquiera se uniera, lo que provocó que muchos usuarios no deseados inundaran los canales. Esto obligó a peppy a «
```suggestion
No obstante, el nuevo equipo era completamente público y estaba disponible para que cualquiera se uniera, lo que provocó que muchos usuarios no deseados inundaran los canales. Esto obligó a peppy a «bloquear» el nuevo equipo hasta el día siguiente. A pesar de esto, peppy siguió haciendo uso del equipo durante el resto del año y, a menudo, invitaba a los usuarios a venir y unirse cuando estaban probando nuevas funciones o implementaciones.[^ppy-blog-july-16][^ppy-blog-july-20]
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +El antiguo contador de FPS fue reemplazado por una nueva «pantalla de actualización y latencia» el 2 de septiembre de 2015. Esta nueva pantalla aún mostraría los FPS actuales (fotogramas por segundo)
```suggestion
El antiguo contador de FPS fue reemplazado por una nueva «pantalla de actualización y latencia» el 2 de septiembre de 2015. Esta nueva pantalla aún mostraría los FPS (fotogramas por segundo) actuales, pero el nuevo cambio hizo que se ocultara de la vista si superaba los 500 FPS. Además, se agregó un nuevo contador debajo del contador de FPS que mostraría exactamente cuánta latencia se estaba introduciendo durante la representación de cuadros (medida en milisegundos). Los fotogramas «tartamudeados» o «caídos» se mostrarían como rectángulos de colores a la izquierda del contador para visualizar mejor exactamente cuánta latencia de procesamiento de fotogramas estaba experimentando un usuario.[^ppy-blog-sep-mwr][^osu-weekly-29]
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
>  ![](img/cysmix-album-cover-1.jpg "La portada del álbum para el primer lanzamiento de canciones oficiales de osu! de cYsmix")
```suggestion
![](img/cysmix-album-cover-1.jpg "La portada del álbum para el primer lanzamiento de canciones oficiales de osu! por cYsmix")
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +Además de esto, se creó una «recompensa abierta» llamada «Mapping With Rewards» para este evento, que permitía a cualquiera mapear una de las pistas antes mencionadas, ponerla en un estado clasificab
```suggestion
Además de esto, se creó una «recompensa abierta» llamada «Mapping With Rewards» para este evento, que permitía a cualquiera mapear una de las pistas antes mencionadas, ponerla en un estado clasificable y, si era lo suficientemente impresionante, esa persona podría recibir una recompensa por ello. La recompensa ofrecida en ese momento era la siguiente: una canción incluida con el cliente (por un período de tiempo limitado), crédito de 50 $ en la osu!store, 6 meses de supporter y una insignia de perfil única. Según los informes, esta recompensa abierta se creó debido a la necesidad de recompensar a los jugadores por beatmaps de calidad y para celebrar las nuevas pistas sin tener que pasar por la molestia que conlleva la ejecución de concursos de mapping tradicionales.[^ppy-blog-sep-mwr]
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +Sin embargo, a pesar de [las promesas de peppy en su blog](https://blog.ppy.sh/post/132009865043/mapping-with-rewards-oct-2015), los resultados del Mapping With Rewards no se publicaron al final del
```suggestion
Sin embargo, a pesar de [las promesas de peppy en su blog](https://blog.ppy.sh/post/132009865043/mapping-with-rewards-oct-2015), los resultados de Mapping With Rewards no se publicaron al final del año.
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +Después de meses de trabajo, se completó la migración de [DirectX](https://es.wikipedia.org/wiki/DirectX) a [OpenGL](https://es.wikipedia.org/wiki/OpenGL) y se envió a todos los usuarios en el flujo
```suggestion
Después de meses de trabajo, se completó la migración de [DirectX](https://es.wikipedia.org/wiki/DirectX) a [OpenGL](https://es.wikipedia.org/wiki/OpenGL) y se envió a todos los usuarios en el flujo de lanzamiento Stable el 16 de octubre de 2015. Sin embargo, los usuarios que no pudieron ejecutar la nueva actualización debido a problemas de compatibilidad cambiaron a un nuevo canal de lanzamiento llamado «Stable (Fallback)», que usaba el antiguo renderizado de gráficos de DirectX. Estaba destinado a ser compatible continuamente junto con el lanzamiento de Stable hasta que el osu! team confiara lo suficiente en la compatibilidad del renderizado OpenGL para todos los usuarios.[^ppy-blog-june-11][^ppy-blog-july-31][^ppy-blog-august-12][^ppy-blog-september-04][^ppy-blog-october-16]
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +Otro lote de canciones oficiales de osu! fueron lanzadas por cYsmix el 27 de octubre de 2015, y también se abrió un concurso similar de «estilo de recompensa abierta». Las tres canciones fueron [«Fri
```suggestion
Otro lote de canciones oficiales de osu! fueron lanzadas por cYsmix el 27 de octubre de 2015, y también se abrió un concurso similar al del «estilo de recompensa abierta». Las tres canciones fueron [«Fright March»](https://soundcloud.com/olemlanglie/cysmix-fright-march-osu), [«Moonlight Sonata»](https://soundcloud.com/olemlanglie/cysmix-moonlight-sonata-osu) y [«Classic Pursuit»](https://soundcloud.com/olemlanglie/cysmix-classic-pursuit-osu).[^ppy-blog-oct-mwr][^osu-weekly-34]
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
>  ![](img/cysmix-album-cover-2.jpg "La portada del álbum para el segundo lanzamiento de canciones oficiales de osu! de cYsmix")
```suggestion
![](img/cysmix-album-cover-2.jpg "La portada del álbum para el segundo lanzamiento de canciones oficiales de osu! por cYsmix")
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +Al igual que el [concurso de Mapping With Rewards del mes anterior](#septiembre), los resultados no se publicaron antes de fin de año.
```suggestion
Al igual que el [concurso Mapping With Rewards del mes anterior](#septiembre), los resultados no se publicaron antes de fin de año.
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +> Me ha llamado la atención que en los últimos días una gran cantidad de streamers de osu! han sido hackeados. El vínculo común parece ser que todos tenían cuentas xsplit activas (que fue hackeado en
```suggestion
> Me ha llamado la atención que en los últimos días una gran cantidad de streamers de osu! han sido hackeados. El vínculo común parece ser que todos tenían cuentas de xsplit activas (que fue hackeado en 2013, filtrando todas las contraseñas). Esto significa que dichos usuarios estaban usando la misma contraseña en twitch, twitter, osu! y más. En primer lugar, si estás haciendo algo como esto, SAL AHORA MISMO Y CAMBIA TUS CONTRASEÑAS. ¡Obtén un administrador de contraseñas y configura una contraseña por servicio!
```

2024-02-10 14:50 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
>  Unos días después (19 de noviembre de 2015), peppy actualizó a los usuarios sobre la situación en [otra publicación de blog](https://blog.ppy.sh/post/133524244723/20151119), en la que explicó la situ
```suggestion
Unos días después (19 de noviembre de 2015), peppy actualizó a los usuarios sobre la situación en [otra publicación en su blog](https://blog.ppy.sh/post/133524244723/20151119), en la que explicó la situación y mantuvo su postura igual:
```

2024-02-14 20:53 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
> +Se agregó soporte para el [Wii Remote](https://es.wikipedia.org/wiki/Wii_Remote) para [osu!taiko](/wiki/Game_mode/osu!taiko) el 26 de marzo de 2015.[^osu-weekly-3]
```suggestion
Se agregó soporte para el [Wii Remote](https://es.wikipedia.org/wiki/Wii_Remote) en [osu!taiko](/wiki/Game_mode/osu!taiko) el 26 de marzo de 2015.[^osu-weekly-3]
```

2024-02-14 20:53 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
>  ---
en la línea 30 pon "no clasificable"

2024-02-14 21:34 UTC, agatemosu commented on wiki/History_of_osu!/2015/es.md
>  ---
en el 36 pon ...que anunciaba el nuevo sistema de...

2024-02-18 12:07 UTC, agatemosu approved these changes

2024-02-19 09:30 UTC, TicClick approved these changes

2024-02-19 09:34 UTC, merged