Rename "Support Team" to "Technical Support Team"
ppy/osu-wiki pull request #10425
Opened 2023-11-10 13:50 UTC by Hiviexd

2023-11-10 13:59 UTC, venix12 requested changes
Could probably just update lists in the language articles rather than outdating them.

2023-11-10 13:59 UTC, venix12 commented on wiki/People/Technical_Support_Team/en.md
> +The **Technical Support Team**, also known as **Support Team Redux**, are members of the osu! staff whom are focused at forum moderation on several subforums: [Development](https://osu.ppy.sh/communi
```suggestion
The **Technical Support Team**, also known as **Support Team** or **Support Team Redux**, are members of the osu! staff whom are focused at forum moderation on several subforums: [Development](https://osu.ppy.sh/community/forums/2), [Gameplay & Rankings](https://osu.ppy.sh/community/forums/13) (excluding [Tournaments](https://osu.ppy.sh/community/forums/55) and [Mapping Techniques](https://osu.ppy.sh/community/forums/61)), [Skinning](https://osu.ppy.sh/community/forums/15), [Feature Requests](https://osu.ppy.sh/community/forums/4), and [Help](https://osu.ppy.sh/community/forums/5).
```

2023-11-10 14:07 UTC, Walavouchey requested changes

2023-11-10 14:07 UTC, Walavouchey commented on wiki/People/Technical_Support_Team/en.md
> +The **Technical Support Team**, also known as **Support Team Redux**, are members of the osu! staff whom are focused at forum moderation on several subforums: [Development](https://osu.ppy.sh/communi
i believe this is more accurate

```suggestion
The **Technical Support Team**  (formerly Support Team, also known as Support Team Redux), are osu! staff members focused on forum moderation on several subforums: [Development](https://osu.ppy.sh/community/forums/2), [Gameplay & Rankings](https://osu.ppy.sh/community/forums/13) (excluding [Tournaments](https://osu.ppy.sh/community/forums/55) and [Mapping Techniques](https://osu.ppy.sh/community/forums/61)), [Skinning](https://osu.ppy.sh/community/forums/15), [Feature Requests](https://osu.ppy.sh/community/forums/4), and [Help](https://osu.ppy.sh/community/forums/5).
```

2023-11-10 14:07 UTC, Walavouchey commented on wiki/People/Technical_Support_Team/en.md
> +If someone needs any assistance on the said subforums, members of this team are available to help.
```suggestion
If someone needs any assistance in the aforementioned subforums, members of this team are available to help.
```

2023-11-10 14:07 UTC, Walavouchey commented on wiki/People/Technical_Support_Team/en.md
> +*Note: All Technical Support Team members speak English in addition to the language(s) listed below unless noted otherwise.*
this note should be right below the heading, so these two paragraphs should be swapped

2023-11-10 14:10 UTC, Walavouchey commented on wiki/People/Technical_Support_Team/en.md
> +*For a team that administers accounts, see: [Account support team](/wiki/People/Account_support_team)*
```suggestion
*Not to be confused with [Account support team](/wiki/People/Account_support_team).*
```

2023-11-10 14:19 UTC, Hiviexd commented
> Could probably just update lists in the language articles rather than outdating them.

idk, there's tons of languages there that i'm not confident with, even with translation tools

2023-11-10 14:31 UTC, venix12 commented
i mean, modifying members list just boils down to removing 4 lines without adding anything

2023-11-10 14:45 UTC, Walavouchey commented
idk how ci isn't catching it but this needs a redirect to not break links

2023-11-10 16:29 UTC, agatemosu commented on wiki/redirect.yaml
I think that these lines should be moved (I don't know how the redirect works)
https://github.com/ppy/osu-wiki/blob/35e7dea93bce239da083bb63287ff385fb550d35/wiki/redirect.yaml#L593-L596
https://github.com/ppy/osu-wiki/blob/35e7dea93bce239da083bb63287ff385fb550d35/wiki/redirect.yaml#L2087

2023-11-10 16:31 UTC, agatemosu commented on wiki/People/Technical_Support_Team/en.md
> +The **Technical Support Team**  (formerly *Support Team*, also known as *Support Team Redux*) is a group of osu! staff members focused on forum moderation on several subforums: [Development](https://
```suggestion
The **Technical Support Team** (formerly *Support Team*, also known as *Support Team Redux*) is a group of osu! staff members focused on forum moderation on several subforums: [Development](https://osu.ppy.sh/community/forums/2), [Gameplay & Rankings](https://osu.ppy.sh/community/forums/13) (excluding [Tournaments](https://osu.ppy.sh/community/forums/55) and [Mapping Techniques](https://osu.ppy.sh/community/forums/61)), [Skinning](https://osu.ppy.sh/community/forums/15), [Feature Requests](https://osu.ppy.sh/community/forums/4), and [Help](https://osu.ppy.sh/community/forums/5).
```

2023-11-10 19:20 UTC, Hiviexd commented on wiki/redirect.yaml
would it be sufficient to update the redirect on each one of those?

2023-11-10 19:30 UTC, agatemosu commented on wiki/redirect.yaml
I mean moving the redirects to the bottom and updating them

2023-11-10 20:52 UTC, Walavouchey commented on wiki/redirect.yaml
crash course on updating redirects:

- add redirect for the moved or renamed article
- update all redirects that point to the old article
- keys (left) are all lowercase, values (right) are case-sensitive
- keys don't support `#section-links`, but values do

you can move them to the bottom if you want

2023-11-10 21:50 UTC, agatemosu commented
https://github.com/ppy/osu-wiki/blob/faccea893cc4c935e241c54c0c89a7cf1f119f69/meta/group-info/en.yaml#L10
should be updated?

2023-11-10 23:26 UTC, RockRoller01 commented
Probably should also update the forum list on the wiki article, as its now limited to help and FR according to the group listing

2023-11-13 02:35 UTC, Sitoria commented
https://github.com/ppy/osu-wiki/blob/master/wiki/People/Account_support_team/en.md
seems to change first line too

> *For a team that moderates certain subforums, see: [Technical Support Team](/wiki/People/Technical_Support_Team)*

2023-11-13 20:56 UTC, Walavouchey submitted a review, later dismissed

2023-11-13 21:34 UTC, cl8n approved these changes

2023-11-13 21:35 UTC, merged