[ES] Update `MWC 2014`
ppy/osu-wiki pull request #10429
Opened 2023-11-10 20:51 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-11 03:28 UTC, UnknownOsu requested changes

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +La **osu!mania World Cup 2014** (***MWC 2014***) fue un torneo por paises organizado por [osu! team](/wiki/People/osu!_team). Estaba separado en una categoría de 4 teclas y otra de 7 teclas y fue la
```suggestion
La **osu!mania World Cup 2014** (***MWC 2014***) fue un torneo por países organizado por el [osu! team](/wiki/People/osu!_team). Estaba separado en una categoría de 4 teclas y otra de 7 teclas y fue la primera entrega de la osu!mania 4K World Cup y la osu!mania 7K World Cup.
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +| ::{ flag=NL }:: | **Países Bajos** | *retired* |
```suggestion
| ::{ flag=NL }:: | **Países Bajos** | *retirado* |
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +| ::{ flag=ES }:: | **España** | *disbanded* |
```suggestion
| ::{ flag=ES }:: | **España** | *disuelto* |
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +| Equipo 1 |  |  | Equipo 2 | Enlace al partido |
```suggestion
| Equipo 1 |  |  | Equipo 2 | Enlace del partido |
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +| Equipo 1 |  |  | Equipo 2 | Enlace al partido |
Creo que queda mejor así, lo mismo en los demás

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +## Set de reglas
```suggestion
## Reglamento
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +2. Los selectores del conjunto de mapas anunciarán con antelación los mapas de cada ronda el domingo anterior a la celebración de los partidos. Solo estos se usarán durante los respectivos partidos.
```suggestion
2. Los selectores de los conjuntos de mapas anunciarán con antelación los mapas de cada ronda el domingo anterior a la celebración de los partidos. Solo estos se usarán durante los respectivos partidos.
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +   - Revivir y sobrevivir durante un mapa se considera como superarlo.
```suggestion
   - Revivir y sobrevivir durante un mapa se considera como pasarlo.
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +6. Se permite el uso de las opciones de [configuración visual](/wiki/Client/Interface/Visual_settings).
```suggestion
6. Se permite el uso de las opciones de la [configuración visual](/wiki/Client/Interface/Visual_settings).
```

2023-11-11 03:28 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +7. Los selectores del conjunto de mapas no podrán participar como jugadores en este torneo.
```suggestion
7. Los selectores de los conjuntos de mapas no podrán participar como jugadores en este torneo.
```

2023-12-08 13:50 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +| Estadístico | ::{ flag=PL }:: [Marcin](https://osu.ppy.sh/users/722665) |
```suggestion
| Estadísticas | ::{ flag=PL }:: [Marcin](https://osu.ppy.sh/users/722665) |
```

2023-12-08 13:56 UTC, agatemosu commented on wiki/Tournaments/MWC/2014/es.md
> +| Estadístico | ::{ flag=PL }:: [Marcin](https://osu.ppy.sh/users/722665) |
por qué?

2023-12-08 14:02 UTC, UnknownOsu commented on wiki/Tournaments/MWC/2014/es.md
> +| Estadístico | ::{ flag=PL }:: [Marcin](https://osu.ppy.sh/users/722665) |
Creo que queda mejor de manera general en lugar de uno solo, ya que las estadísticas son varios datos y no uno solo

2023-12-09 15:28 UTC, TicClick approved these changes

2023-12-09 15:28 UTC, merged