Fix wikilinks
ppy/osu-wiki pull request #10438
Opened 2023-11-11 19:15 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

`SKIP_OUTDATED_CHECK`

2023-11-13 05:36 UTC, cl8n requested changes
i also dont think any of the text in translations should be changed. which happens in the following files
wiki/Disambiguation/ko.md
wiki/Client/Menu_tips/zh.md
wiki/Client/Beatmap_editor/fr.md

2023-11-21 17:22 UTC, agatemosu commented on wiki/Disambiguation/ko.md
> +일반적인 문서에서 제목이 유사한 경우, 반드시 ["다른 의미를 찾으려면" 햇노트](/wiki/Article_styling_criteria/Formatting#다른-의미를-찾으려면)에 동음이의어 페이지 링크를 첨부해야 합니다.
this refers to a section of the article so should be changed too

2023-11-21 17:22 UTC, agatemosu commented on wiki/Client/Menu_tips/zh.md
> +- 如果你在作图期间调整时间轴，切记要使用[`全部重新对齐`](/wiki/Client/Beatmap_editor/Menu#测定时间轴-(timing))功能，重新将所有物件对齐在时间轴上。这个功能位于 `测定时间轴 (Timing)` 选项卡的下拉菜单里。注意未对齐的[继承时间点（绿线）](/wiki/Client/Beatmap_editor/Timing#继承时间点（绿线）)——它们
this is not the editor tip of the localisation in the game, and this refers to the button that does not exist, I only changed the name of the button that it's in game

2023-11-21 17:22 UTC, agatemosu commented on wiki/Client/Beatmap_editor/fr.md
> +# Éditeur de beatmap
doryanr said that it is correct

2023-11-22 10:17 UTC, cl8n approved these changes

2023-11-22 10:57 UTC, Walavouchey approved these changes

2023-11-22 11:05 UTC, merged