[DE] Add `Title text`
ppy/osu-wiki pull request #10439
Opened 2023-11-11 19:21 UTC by FreezyLemon

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-19 16:44 UTC, The-Last-Cookie commented
- [ ] Requesting self-review. I already began with the review in the PR, though I want to take another look later.

2023-11-27 20:51 UTC, The-Last-Cookie requested changes

2023-11-27 21:19 UTC, FreezyLemon commented on wiki/Beatmap/Title_text/de.md
> +"Zeile 1" fängt ab dem Zeitpunkt 1100 ms an, eingeblendet zu werden (als Erinnerung: `wait` verzögert die Startzeit um 500 ms, wenn nicht anders festgelegt). Die Zeile wird in rot, fett und mit Schri
That is what I mean, but I am a bit confused now. The `hold` documentation says `How long the line will display before starting to fade out, in milliseconds`. This seems pretty clear (it is **not** `The time in the song when this line will start to fade out`, so I am positive this is meant in a relative context).

However, the default value is stated as `3600 + 800n`. In this case, `n = 2`, so it should be `3600 + 800 * 2`, no? Not sure where the `4000` comes from, and I don't see any interval of 400 that would be relevant here.

2023-12-02 15:29 UTC, The-Last-Cookie commented on wiki/Beatmap/Title_text/de.md
> +"Zeile 1" fängt ab dem Zeitpunkt 1100 ms an, eingeblendet zu werden (als Erinnerung: `wait` verzögert die Startzeit um 500 ms, wenn nicht anders festgelegt). Die Zeile wird in rot, fett und mit Schri
Judging from the last part (`after 2000ms pass`), this seems to be meant as

> 2000 ms später

and not

> nachdem 2000 ms vergangen sind (von t = 0 bzw. dem Start der Beatmap ausgesehen)

Thus, my question may be closed.

2023-12-02 21:29 UTC, FreezyLemon commented on wiki/Beatmap/Title_text/de.md
> +## Den Titeltext anpassen
Seems I was behind the times. It was already caught by CI

2023-12-03 10:15 UTC, The-Last-Cookie approved these changes

2023-12-06 08:16 UTC, TicClick approved these changes

2023-12-06 08:17 UTC, merged