[DE] Add `Bit rate`
ppy/osu-wiki pull request #10445
Opened 2023-11-11 20:40 UTC by FreezyLemon

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-19 16:00 UTC, The-Last-Cookie requested changes

2023-11-19 21:08 UTC, FreezyLemon commented on wiki/Bit_rate/de.md
> +*Für Hilfe zum Reenkodieren von Audio in einer anderen Bitrate, siehe: [Anleitung zum Bearbeiten von Audio](/wiki/Guides/Audio_editing)*
Well, `Enkodieren` isn't in the Duden and `Enkoding`/`Encoding` is, so I guess we should prefer one of those. Technically, all reencoding could be covered with the word encoding, but the "re" contains more information and it's also closer to the english terminology. So I'd prefer `Reencoding` or maybe `Reenkoding` here.

Yeah, I chose Anleitung after looking at the article too. I'll keep it for now.

2023-11-27 11:30 UTC, FreezyLemon commented on wiki/Bit_rate/de.md
> +*Für Hilfe zum Reenkodieren von Audio in einer anderen Bitrate, siehe: [Anleitung zum Bearbeiten von Audio](/wiki/Guides/Audio_editing)*
After some discussion on Discord, `Rekodierung` is used instead (see commit msg for more details).

2023-11-27 18:38 UTC, The-Last-Cookie approved these changes

2023-11-29 20:22 UTC, cl8n approved these changes

2023-11-29 20:32 UTC, merged