[ES] Add `B` missing stubs (1)
ppy/osu-wiki pull request #10441
Opened 2023-11-11 20:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Missing B stubs from the `Missing stubs (up-to-date in English)` section according to the osu! wiki status in spanish.

32 stubs in total, divided into 4 pull requests of 8 articles each. Continued in:

2023-11-11 20:50 UTC, agatemosu requested changes

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/Authentic/es.md
> +Un **[beatmap](/wiki/Beatmap)** auténtico es aquel que emula un nivel de los [juegos iNiS](/wiki/iNiS_games). El término se origina en una época en la que el [mapping](/wiki/Beatmapping) se inspiró e
```suggestion
Un **[beatmap](/wiki/Beatmap)** auténtico es aquel que emula un nivel de los [juegos de iNiS](/wiki/iNiS_games). El término se origina en una época en la que el [mapping](/wiki/Beatmapping) se inspiró en gran medida en iNiS. Hoy en día, el término «auténtico» tiene poco significado, ya que generaciones de mappers se han inspirado unos de otros en lugar de los juegos originales.
```

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/Background/es.md
> +Los fondos se muestran en las tarjetas de los beatmaps, en la [pantalla del selector de canciones](/wiki/Client/Interface#selector-de-canciones) y durante el juego. Si las dificultades en un beatmap
```suggestion
Los fondos se muestran en las tarjetas de los beatmaps, en la [pantalla de selección de canciones](/wiki/Client/Interface#selector-de-canciones) y durante el juego. Si las dificultades en un beatmap tienen diferentes fondos, se selecciona la dificultad con el [`BeatmapID`](/wiki/Beatmap#identificación) más bajo para la tarjeta del beatmap y los iconos del [carrusel de beatmaps](/wiki/Client/Interface#carrusel-de-beatmaps).
```

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/Break/es.md
> +**Los descansos** son secciones de un [beatmap](/wiki/Beatmap) que no tienen [objetos](/wiki/Gameplay/Hit_object). Durante este tiempo, el [drenaje de salud](/wiki/Gameplay/Health) se detiene tempora
```suggestion
Los **descansos** son secciones de un [beatmap](/wiki/Beatmap) que no tienen [objetos](/wiki/Gameplay/Hit_object). Durante este tiempo, el [drenaje de salud](/wiki/Gameplay/Health) se detiene temporalmente. Los descansos generalmente le permiten al jugador descansar el brazo por un momento y reposicionar su [dispositivo de entrada](/wiki/Gameplay/Input_device).
```

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/Break/es.md
> +Dependiendo de la [configuración](/wiki/Client/Beatmap_editor/Song_setup) habilitada, pueden aparecer letterboxes cuando se inicia un descanso. Además de esto, puede aparecer un gráfico y un sonido d
```suggestion
Dependiendo de la [configuración](/wiki/Client/Beatmap_editor/Song_setup) habilitada, pueden aparecer letterboxes cuando se inicia un descanso. Además de esto, puede aparecer un gráfico y un sonido de pasado o fallado para indicarle al jugador si le está yendo bien o no. Esto solo aparecerá si hay tiempo suficiente para que se muestre el gráfico.
```

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/HP_drain_rate/es.md
> +La **tasa de drenaje de HP** (***HP***) es una configuración de dificultad de un [beatmap](/wiki/Beatmap) que controla cuánta [salud](/wiki/Gameplay/Health) se pierde pasivamente en el [drenaje de sa
```suggestion
La **tasa de drenaje de HP** (***HP***) es una configuración de dificultad de un [beatmap](/wiki/Beatmap) que controla cuánta [salud](/wiki/Gameplay/Health) se pierde pasivamente en el [drenaje de salud](/wiki/Gameplay/Health). También afecta la gravedad en la penalización de un jugador por fallar notas y la cantidad de salud que se recupera al golpear [objetos](/wiki/Gameplay/Hit_object) con precisión.
```

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/HP_drain_rate/es.md
> +- [Half Time](/wiki/Gameplay/Game_modifier/Half_Time): El valor de HP no se ve afectado, pero debido a la disminución del 25 % en la velocidad de juego, el drenaje de salud ocurre un 25 % más lento.
```suggestion
- [Double Time](/wiki/Gameplay/Game_modifier/Double_Time): El valor de HP no se ve afectado, pero debido al aumento del 50 % en la velocidad de juego, el drenaje de salud ocurre un 50 % más rápido.
- [Half Time](/wiki/Gameplay/Game_modifier/Half_Time): El valor de HP no se ve afectado, pero debido a la disminución del 25 % en la velocidad de juego, el drenaje de salud ocurre un 25 % más lento.
```

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/Marathon/es.md
> +Los beatmaps de maratón también debían tener su única dificultad llamada «Marathon» para evitar que el sistema de envío de beatmaps en ese momento hiciera que el beatmap ingrese a la categoría [pendi
```suggestion
Los beatmaps de maratón también debían tener su única dificultad llamada «Marathon» para evitar que el sistema de envío de beatmaps en ese momento hiciera que el beatmap ingrese a la categoría [pendientes](/wiki/Beatmap/Category#trabajo-en-progreso-y-pendientes). Al clasificarlos, los beatmaps de maratón ingresarían en la categoría [aprobados](/wiki/Beatmap/Category#aprobados) en lugar de la categoría [clasificados](/wiki/Beatmap/Category#clasificados) para indicar que se trataba de mapas de maratón. Posteriormente, la categoría se abandonó en favor de la categoría clasificados.
```

2023-11-11 20:50 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!/Jump/es.md
> +Un **jump** es un [patrón](/wiki/Beatmap/Pattern) de [osu!](/wiki/Game_mode/osu!) donde dos [objetos](/wiki/Gameplay/Hit_object) están muy separados en el campo de juego en comparación con el espacio
```suggestion
Un **jump** es un [patrón](/wiki/Beatmap/Pattern) de [osu!](/wiki/Game_mode/osu!) donde dos [objetos](/wiki/Gameplay/Hit_object) están muy separados en el campo de juego en comparación con el espacio entre otros objetos. Los jumps generalmente indican alta intensidad en una canción y generalmente se ajustan a las marcas 1/2 en la [línea de tiempo](/wiki/Client/Beatmap_editor/Timelines#hit-objects).
```

2023-11-11 21:40 UTC, agatemosu commented on wiki/Beatmap/Marathon/es.md
> +Los mapas de maratón se cambiaron posteriormente para incluir mapas con [tiempos de drenaje](/wiki/Beatmap/Drain_time) de cinco minutos y que permitieran el [nombrado de dificultad personalizada](/wi
```suggestion
Los mapas de maratón se cambiaron posteriormente para incluir mapas con [tiempos de drenaje](/wiki/Beatmap/Drain_time) de cinco minutos y que permitieran el [nombramiento de dificultad personalizada](/wiki/Ranking_criteria/Difficulty_naming). Esto duró hasta que se introdujeron reglas de distribución más indulgentes en 2019.
```

2023-11-11 21:40 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!/Jump/es.md
> +Un **jump** es un [patrón](/wiki/Beatmap/Pattern) de [osu!](/wiki/Game_mode/osu!) donde dos [objetos](/wiki/Gameplay/Hit_object) están muy separados en el campo de juego en comparación con el espacio
```suggestion
Un **jump** o *salto* es un [patrón](/wiki/Beatmap/Pattern) de [osu!](/wiki/Game_mode/osu!) donde dos [objetos](/wiki/Gameplay/Hit_object) están muy separados en el campo de juego en comparación con el espacio entre otros objetos. Los jumps generalmente indican alta intensidad en una canción y generalmente se ajustan a las marcas 1/2 en la [línea de tiempo](/wiki/Client/Beatmap_editor/Timelines#hit-objects).
```

2023-11-12 10:26 UTC, agatemosu approved these changes

2023-11-12 13:03 UTC, Hiviexd approved these changes

2023-11-12 13:04 UTC, merged