[ES] Add `B` missing stubs (2)
ppy/osu-wiki pull request #10442
Opened 2023-11-11 20:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Missing B stubs from the `Missing stubs (up-to-date in English)` section according to the osu! wiki status in spanish.

32 stubs in total, divided into 4 pull requests of 8 articles each. Continued in:

2023-11-12 10:40 UTC, agatemosu requested changes

2023-11-12 10:40 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!mania/Stream/es.md
> +Los **jumpstreams** son streams que involucran [jumps](/wiki/Beatmap/Pattern/osu!mania/Chord#jump). Por lo general, el stream en sí se realiza en ajustes de 1/4, mientras que los jumps aterrizan en a
```suggestion
Los **jumpstreams** son streams que involucran [jumps](/wiki/Beatmap/Pattern/osu!mania/Chord#jump). Por lo general, el stream en sí se realiza en ajustes de 1/4, mientras que los jumps aterrizan en ajustes más altos. Este es el tipo de stream más común usado en osu!mania 4K.
```

2023-11-12 10:40 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!mania/Stream/es.md
> +Este término se utiliza principalmente en osu!mania 4K.
```suggestion
Este término se usa principalmente en osu!mania 4K.
```

2023-11-12 10:40 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!mania/Stream/es.md
> +Este término también se utiliza principalmente en osu!mania 4K.
```suggestion
Este término también se usa principalmente en osu!mania 4K.
```

2023-11-12 10:40 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!mania/Stream/es.md
> +Los **chordstreams** son un tipo de stream que involucra diferentes tamaños de chords. El stream suele ser de 1/4, con chords en cada intervalo de ajuste de 1/1 o 1/2. En los modos fuera de 4K, «chor
```suggestion
Los **chordstreams** son un tipo de stream que involucra diferentes tamaños de chords. El stream suele ser de 1/4, con chords en cada intervalo de ajuste de 1/1 o 1/2. En los modos fuera de 4K, «chordstream» generalmente se refiere a streams que involucran 3 o más notas dentro de los chords. Por lo tanto, el término se usa casi exclusivamente en modos que no son 4K.
```

2023-11-14 16:44 UTC, agatemosu requested changes

2023-11-14 16:44 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!mania/Chord/es.md
> +## Nota de gracia
```suggestion
## Grace note
```

2023-11-14 16:44 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!mania/Chord/es.md
> +Las **notas de gracia** son dos o más notas en columnas diferentes que deben tocarse en rápida sucesión una de otra. Esto se hace comúnmente con ajustes superiores a 1/6. Durante el juego, se parecen
```suggestion
Las **grace notes** son dos o más notas en columnas diferentes que deben tocarse en rápida sucesión una de otra. Esto se hace comúnmente con ajustes superiores a 1/6. Durante el juego, se parecen mucho a los chords.
```

2023-11-14 16:44 UTC, agatemosu commented on wiki/Beatmap/Pattern/osu!mania/Hold_note/es.md
> +Las **salidas** se refiere a los extremos de las notas mantenidas, es decir, la parte que requiere que se suelte la tecla. Tienen un significado especial debido a que en el momento de soltar se tiene
```suggestion
Los **releases** son los extremos de las notas largas, es decir, la parte que requiere que se suelte la tecla. Tienen un significado especial debido a que en el momento de soltar se tiene en cuenta en el [sistema de juicio de osu!mania](/wiki/Gameplay/Judgement/osu!mania).
```

2023-11-14 17:23 UTC, agatemosu approved these changes

2023-11-14 22:56 UTC, Hiviexd approved these changes

2023-11-14 22:57 UTC, merged