[ZH] translated `/Beatmapping/Combo`
ppy/osu-wiki pull request #10454
Opened 2023-11-13 14:21 UTC by Proxyerium

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-14 03:11 UTC, CloneWith requested changes
👍 

诸如标点、中英文格式之类的要求可以参照 wiki 里的[相关标准](https://osu.ppy.sh/wiki/Article_styling_criteria)。

2023-11-14 03:11 UTC, CloneWith commented on wiki/Beatmapping/Combo/zh.md
> +[osu!catch](/wiki/Game_mode/osu!catch)中，每种[水果](/wiki/Gameplay/Hit_object/Fruit)都由给定的顺序来决定颜色，划条末的[水果串](/wiki/Gameplay/Hit_object/Juice_stream)和水果总是和开头水果的颜色相同，但[香蕉](/wiki/Gameplay/Hit_object/Banana)总是黄
```suggestion
[osu!catch](/wiki/Game_mode/osu!catch) 中，每种[水果](/wiki/Gameplay/Hit_object/Fruit)的颜色由给定的顺序决定，[水果串](/wiki/Gameplay/Hit_object/Juice_stream)和滑条末水果的颜色总是和开头水果相同，但[香蕉](/wiki/Gameplay/Hit_object/Banana)总是黄色的。当一组连击完成，堆在小人盘子里的水果会爆炸散开。
```

这里说的是两种情况：水果串末端的果和滑条最后的果，其颜色都是与一开始的水果相同的。

2023-11-14 04:21 UTC, Proxyerium commented on wiki/Beatmapping/Combo/zh.md
> +*对于更多义项, 参阅 [连击 (消歧义)](/wiki/Disambiguation/Combo).*
眼拙没看见😖

2023-11-14 04:27 UTC, CloneWith commented
不用在意。我也会犯这样的错误&nbsp;:heart:


---Original---
From: ***@***.***&gt;
Date: Tue, Nov 14, 2023 12:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ppy/osu-wiki] [ZH] Add `/Beatmapping/Combo` (PR #10454)




 
@Proxyerium commented on this pull request.
 
 
In wiki/Beatmapping/Combo/zh.md:
 &gt; @@ -0,0 +1,26 @@ +--- +tags: +  - combo color +  - combo colour +  - NC +  - new combo +  - comboset +  - 连击 +  - 连击组 +--- + +# 连击 + +*对于更多义项, 参阅 [连击 (消歧义)](/wiki/Disambiguation/Combo).*  
眼拙没看见😖
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2023-11-14 04:30 UTC, Proxyerium commented
@CloneWith 
❤ 感谢建议！
顺便再请教一下 `followpoints` 有更合适的词吗，很多皮肤把followpoint做成一条线了，感觉翻译成 `示踪点` 太花哨了，读者可能第一时间都不知道在说什么 XD

2023-11-14 04:37 UTC, CloneWith commented
> @CloneWith ❤ 感谢建议！ 顺便再请教一下 `followpoints` 有更合适的词吗，很多皮肤把followpoint做成一条线了，感觉翻译成 `示踪点` 太花哨了，读者可能第一时间都不知道在说什么 XD

设置面板里好像有一个，**“物件间轨迹”**来着，可能会好一点

有时间我们可以在 osu! 里加一下好友什么的，交流方便

2023-11-14 04:38 UTC, CloneWith approved these changes

2023-11-15 15:59 UTC, Hiviexd approved these changes

2023-11-15 15:59 UTC, merged