[DE] Add "Beatmap description"
ppy/osu-wiki pull request #10468
Opened 2023-11-14 23:48 UTC by FreezyLemon

I invented `Gastschwierigkeit` as a contraction of `Gastschwierigkeitsgrad`/`-stufe`, because the translation for that article doesn't exist yet. I don't think that's going to be a problem.

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-19 16:45 UTC, The-Last-Cookie commented
- [ ] Requesting self-review. I'm not sure exactly when I get to do a review on this one.

2023-12-02 14:02 UTC, The-Last-Cookie requested changes

2023-12-03 12:07 UTC, The-Last-Cookie commented on wiki/Beatmap/Beatmap_description/de.md
> +- Eine Liste aller [Gastschwierigkeiten](/wiki/Beatmap/Guest_difficulty) und ihrer Ersteller
Well, I already pushed out a change to edit a list in `Explicit content.` Both is fine to me.

2023-12-06 08:23 UTC, TicClick approved these changes

2023-12-06 08:25 UTC, merged