[ES] Add `Featured Artist playlists`
ppy/osu-wiki pull request #10464
Opened 2023-11-14 18:39 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-14 21:36 UTC, UnknownOsu requested changes

2023-11-14 21:36 UTC, UnknownOsu commented on wiki/People/Featured_Artists/Featured_Artist_playlists/es.md
> +Las **listas de juego de artistas destacados** se publican en [osu!(lazer)](/wiki/Client/Release_stream/Lazer) y resaltan el contenido de [artistas destacados](/wiki/People/Featured_Artists) en todos
```suggestion
Las **listas de juego de artistas destacados** se publican en [osu!(lazer)](/wiki/Client/Release_stream/Lazer) y resaltan el contenido de los [artistas destacados](/wiki/People/Featured_Artists) en todos los [modos de juego](/wiki/Game_mode). Las listas de juego evitan un formato estricto, por lo que los parámetros de la lista de juego, las selecciones de beatmaps y los criterios de premios varían en cada lista de juego.
```

2023-11-14 21:36 UTC, UnknownOsu commented on wiki/People/Featured_Artists/Featured_Artist_playlists/es.md
> +![Lobby de lista de juego de artistas destacados](img/playlist.jpg "osu!(lazer) Lobby de lista de juego de artistas destacados")
```suggestion
![Sala de una lista de juego de artistas destacados](img/playlist.jpg "osu!(lazer) Sala de una lista de juego de artistas destacados")
```

2023-11-14 23:07 UTC, UnknownOsu approved these changes

2023-11-15 00:32 UTC, Hiviexd approved these changes

2023-11-15 00:33 UTC, merged