[ES] Rename "Support Team" to "Technical Support Team"
ppy/osu-wiki pull request #10460
Opened 2023-11-14 16:21 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-14 16:59 UTC, agatemosu commented
thanks, lately I forget to put [ES]

2023-11-14 18:36 UTC, UnknownOsu requested changes

2023-11-14 18:36 UTC, UnknownOsu commented on wiki/Main_page/es.md
> +[osu! team](/wiki/People/osu!_team) • [Desarrolladores](/wiki/People/Developers) • [Global Moderation Team](/wiki/People/Global_Moderation_Team) • [Featured Artists](/wiki/People/Featured_Artists) •
```suggestion
[osu! team](/wiki/People/osu!_team) • [Desarrolladores](/wiki/People/Developers) • [Global Moderation Team](/wiki/People/Global_Moderation_Team) • [Artistas destacados](/wiki/People/Featured_Artists) • [Equipo de soporte técnico](/wiki/People/Technical_Support_Team) • [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) • [Beatmap Nominators](/wiki/People/Beatmap_Nominators) • [osu! Alumni](/wiki/People/osu!_Alumni) • [Project Loved Team](/wiki/People/Project_Loved_Team) • [Beatmap Spotlight Curators](/wiki/People/Beatmap_Spotlight_Curators)
```

2023-11-24 20:15 UTC, agatemosu commented
force pushed because of the resolve conflicts commit reverting the change in user groups

2023-11-29 15:35 UTC, UnknownOsu approved these changes

2023-11-29 20:25 UTC, cl8n approved these changes

2023-11-29 20:37 UTC, merged