[ZH] Add `/People/Featured_Artists`
ppy/osu-wiki pull request #10475
Opened 2023-11-16 15:26 UTC by Proxyerium

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-11-17 08:12 UTC, CloneWith requested changes

2023-11-17 08:12 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +如果精选艺术家里提供的`.osz`文件有任何问题，可在[这个论坛主题](https://osu.ppy.sh/community/forums/topics/783985)中提交反馈
```suggestion
如果精选艺术家里提供的 `.osz` 文件有任何问题，可在[这个论坛帖](https://osu.ppy.sh/community/forums/topics/783985)中提交反馈。
```

论坛里的话题一般称作“帖子”

2023-11-17 08:12 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +[精选艺术家群组页](https://osu.ppy.sh/groups/35)列出的是有osu!账号的精选艺术家；[精选艺术家列表](https://osu.ppy.sh/beatmaps/artists)列出的是所有精选艺术家。
```suggestion
[精选艺术家用户组页面](https://osu.ppy.sh/groups/35)列出的是有 osu! 账号的精选艺术家，而[精选艺术家列表](https://osu.ppy.sh/beatmaps/artists)列出了所有精选艺术家。
```

2023-11-17 08:12 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +| User | Artist |
```suggestion
| 用户 | 艺术家 |
```

2023-11-17 08:12 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +| ::{ flag=SE }:: [Helblinde](https://osu.ppy.sh/users/48053) | [Helblinde](https://osu.ppy.sh/beatmaps/artists/5), [Fractal Dreamers](https://osu.ppy.sh/beatmaps/artists/15) (member of) |
```suggestion
| ::{ flag=SE }:: [Helblinde](https://osu.ppy.sh/users/48053) | [Helblinde](https://osu.ppy.sh/beatmaps/artists/5), [Fractal Dreamers](https://osu.ppy.sh/beatmaps/artists/15) （成员） |
```

2023-11-17 08:12 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +除了osu!社区间接选择的精选艺术家之外，如果有谱师用一位艺术家的音乐制作的谱面成功上架了，osu!团队可能会与那位艺术家取得联系并讨论精选艺术家的事宜。偶尔还会有一些艺术家因为其他因素而入选，比如有听众呼吁他们加入。
```suggestion
除了 osu! 社区间接选择的精选艺术家之外，如果有谱师用一位艺术家的音乐制作的谱面成功上架了，osu! 团队可能会与那位艺术家取得联系并讨论精选艺术家的事宜。偶尔还会有一些艺术家因为其他因素而入选，比如有听众呼吁他们加入。
```

2023-11-17 08:12 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +精选艺术家里的所有歌曲都不是osu!独占的。对该项目感兴趣的艺术家，可参阅[音乐版权](/wiki/Legal/Music_licensing)了解更多详情。
```suggestion
精选艺术家里的所有歌曲都不是 osu! 独占的。对该项目感兴趣的艺术家，可参阅[音乐版权](/wiki/Legal/Music_licensing)了解更多详情。
```

2023-11-17 08:12 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +精选艺术家的账号有一个青色的"Featured Aritst"[玩家头衔](/wiki/Community/User_title)和一个 `FA` 的[用户组别](/wiki/People/User_group)，体现出他们对osu!的贡献。
```suggestion
精选艺术家的账号有青色的 "Featured Artist" [玩家头衔](/wiki/Community/User_title)和 `FA` [用户组](/wiki/People/User_group)标签，体现出他们对 osu! 的贡献。
```

2023-11-17 08:31 UTC, Proxyerium commented
@CloneWith 
太感谢了 🌹我真是太不走心了漏那么多地方，感谢建议

2023-11-17 08:33 UTC, CloneWith reviewed
啊 还有两处，忘记加了 xD

2023-11-17 08:33 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +| ::{ flag=JP }:: [xorsizer](https://osu.ppy.sh/users/20466752) | [Symholic](https://osu.ppy.sh/beatmaps/artists/130) (member of) |
```suggestion
| ::{ flag=JP }:: [xorsizer](https://osu.ppy.sh/users/20466752) | [Symholic](https://osu.ppy.sh/beatmaps/artists/130) （成员） |
```

2023-11-17 08:33 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +| ::{ flag=ES }:: [sotuiofficial](https://osu.ppy.sh/users/14779258) | [Rising Sun Traxx](https://osu.ppy.sh/beatmaps/artists/41) (founder) |
```suggestion
| ::{ flag=ES }:: [sotuiofficial](https://osu.ppy.sh/users/14779258) | [Rising Sun Traxx](https://osu.ppy.sh/beatmaps/artists/41) （建立者） |
```

2023-11-17 08:42 UTC, CloneWith approved these changes

2023-11-17 20:54 UTC, CloneWith requested changes
![Screenshot_2023-11-18-04-45-23-209_com microsoft emmx](https://github.com/ppy/osu-wiki/assets/110881926/90c3a423-915d-4f2a-bcd4-8259623e9baa)

又看了一下这个更改，原来的链接没错，不需要修改。对应的中文翻译中，要使用对应的分节标题。

2023-11-17 20:54 UTC, CloneWith commented on wiki/People/Featured_Artists/zh.md
> +**精选艺术家**（简称 ***FA*** ）是同 osu! 合作的音乐制作人，他们授权的音乐可以用在[谱面](/wiki/Beatmap)和 [osu! 世界杯](/wiki/Tournaments/OWC)直播的背景音乐中。
```suggestion
**精选艺术家**（简称 ***FA*** ）是同 osu! 合作的音乐制作人，他们授权的音乐可以用在[谱面](/wiki/Beatmap)和 [osu! 世界杯](/wiki/Tournaments#osu!-世界杯)直播的背景音乐中。
```

2023-11-18 00:33 UTC, Proxyerium commented on wiki/People/Featured_Artists/zh.md
> +**精选艺术家**（简称 ***FA*** ）是同 osu! 合作的音乐制作人，他们授权的音乐可以用在[谱面](/wiki/Beatmap)和 [osu! 世界杯](/wiki/Tournaments/OWC)直播的背景音乐中。
> 
原来如此，这才发现/OWC是个孤立的页面🤯

2023-11-18 03:26 UTC, CloneWith approved these changes

2023-11-18 16:07 UTC, Hiviexd approved these changes

2023-11-18 16:07 UTC, merged