[KO] Delete Outdated Tag `People/Account Support Team`
ppy/osu-wiki pull request #10528
Opened 2023-11-23 17:57 UTC by Chronicler01

2023-11-23 17:59 UTC, agatemosu commented
https://osu.wiki/status/diff/0df11d00415c24fe6867239d75ec1cd3b575162b/wiki/People/Account_support_team/en.md

2023-11-23 18:02 UTC, agatemosu commented
same in main page

2023-11-24 03:47 UTC, Sitoria commented
pr crashed 💀

2023-11-24 03:49 UTC, Sitoria requested changes
메인페이지랑 people에 있는 ko.md도 아웃데이트 제거해주시면 감사하겠습니다 🙏

more info) en.md PR'd -> i PR'd -> en.md merged with outdated tag -> my PR merged -> outdated not deleted

!! sorry !!

2023-11-24 04:00 UTC, Sitoria requested changes
layout

2023-11-24 04:00 UTC, Sitoria commented on wiki/Main_page/ko.md
> -layout: main_page
아웃데이트 true랑
since만 지워줍시다

2023-11-24 04:06 UTC, Sitoria requested changes
no_native_review issue

2023-11-24 04:06 UTC, Sitoria commented on wiki/People/Account_support_team/ko.md
> -no_native_review: true
이거는 지우면 안 됩니다
https://github.com/ppy/osu-wiki/pull/10210 에 의거하면 리뷰 없이 머지된거라서
1번줄
2번줄 살리고
3번줄은 작대기 3개 둡시다

2023-11-24 04:12 UTC, Sitoria approved these changes
why this PR opened: merged #10436 but outdated tags are not deleted

2023-11-24 07:28 UTC, TicClick approved these changes

2023-11-24 07:30 UTC, merged