[ES] Fix all aparitions of "contributor"
ppy/osu-wiki pull request #10533
Opened 2023-11-24 20:08 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-09 15:50 UTC, UnknownOsu requested changes

2023-12-09 15:50 UTC, UnknownOsu commented on wiki/Article_styling_criteria/es.md
> +Estos artículos son herramientas para ayudar durante el proceso de revisión y representan al consenso formado por los contribuidores de la osu! wiki a lo largo de los años. Dado que la wiki es un esf
```suggestion
Estos artículos son herramientas para ayudar durante el proceso de revisión y representan al consenso formado por los contribuidores de la osu! wiki a lo largo de los años. Dado que la wiki es un esfuerzo colaborativo llevado a cabo a través de dicho proceso, no es necesario leer o memorizar todo el ASC a la vez. Si estás buscando contribuir, revisa la [guía de contribución](/wiki/osu!_wiki/Contribution_guide).
```

2023-12-09 15:50 UTC, UnknownOsu commented on wiki/Article_styling_criteria/es.md
>  Para sugerir cambios con respecto a los criterios de estilo para artículos, [abra una incidencia en GitHub](https://github.com/ppy/osu-wiki/issues/new).
```suggestion
Para sugerir cambios con respecto a los criterios de estilo para artículos, [abre una incidencia en GitHub](https://github.com/ppy/osu-wiki/issues/new).
```

2023-12-18 20:01 UTC, UnknownOsu requested changes

2023-12-18 20:04 UTC, UnknownOsu approved these changes

2023-12-27 14:16 UTC, TicClick approved these changes

2023-12-27 14:19 UTC, merged