[ES] Update `Client/Beatmap_editor/AiMod`
ppy/osu-wiki pull request #10535
Opened 2023-11-24 20:19 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

SKIP_WIKILINK_CHECK

#10342 split into three separate pull request for better review

2023-11-24 20:29 UTC, agatemosu requested changes

2023-11-24 20:29 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| <!-- Can't confirm -->Kiai is toggled very frequently! | ¡El kiai se activa con mucha frecuencia! | Reduce la cantidad de ocurrencias del kiai en todo el mapa. | También conocidos como *kiai flashe
```suggestion
| Easy/Normal diff contains too many speed changes. | La dificultad Easy/Normal presenta una cantidad frecuente de cambios de velocidad de los sliders, lo cual no se recomienda en los [criterios de clasificación](/wiki/Ranking_criteria). | Reduce el número de cambios de velocidad de los sliders en la dificultad Easy/Normal en cuestión. |  |
| Kiai is toggled very frequently! | ¡El kiai se activa con mucha frecuencia! | Reduce la cantidad de ocurrencias del kiai en todo el mapa. | También conocidos como *kiai flashes*. Esta advertencia se puede ignorar con seguridad si se pretende el uso del kiai en cuestión. |
```

2023-11-25 13:18 UTC, agatemosu reviewed
check 1

2023-11-25 13:18 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
>  | More than 6 notes simultaneously is not allowed. | Uno o más patrones en el mapa requieren que el jugador presione activamente más de 6 teclas a la vez. En ciertos casos, los [criterios de clasific
```suggestion
| More than 6 notes simultaneously is not allowed. | Uno o más patrones del mapa requieren que el jugador pulse activamente más de 6 teclas a la vez. En ciertos casos, los [criterios de clasificación de osu!mania](/wiki/Ranking_criteria/osu!mania) lo desaconsejan, ya que la mayoría de los teclados solo permiten pulsar hasta 6 teclas a la vez debido a un fenómeno conocido como [ghosting](https://nelson-miller.com/what-is-keyboard-ghosting-and-how-do-you-prevent-it/). | Revisa tu beatmap para asegurarte de que cada columna tiene como máximo 6 pulsaciones de nota simultáneas. | ![](/wiki/shared/mode/mania.png) solo mapas de osu!mania |
```

2023-11-25 13:18 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| File missing:{0} | A tu mapa le faltan ciertos archivos. | Recupera los archivos que faltan o asegúrate de que el beatmap no esté tratando de usar archivos que no existen. |  |
```suggestion
| File missing:{0} | A tu beatmap le faltan ciertos archivos. | Recupera los archivos que faltan o asegúrate de que el beatmap no esté tratando de usar archivos que no existen. |  |
```

2023-11-25 13:18 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| All timing sections have a volume below 5%. | Todas las secciones de temporización tienen un volumen inferior al 5 %. | Configura al menos una sección de temporización para que tenga un volumen de
```suggestion
| All timing sections have a volume below 5%. | Todas las secciones de tiempo tienen un volumen inferior al 5 %. | Configura al menos una sección de tiempo para que tenga un volumen de sonido de 5 % o más. |  |
```

2023-11-25 13:18 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Drain time should be over 30 seconds. | La duración de tu mapa de principio a fin, sin incluir los tiempos de descanso, es inferior a 30 segundos. | Intenta usar un spinner para terminar el mapa si
```suggestion
| Drain time should be over 30 seconds. | La duración de tu mapa de principio a fin, sin incluir los descansos, es inferior a 30 segundos. | Intenta usar un spinner para terminar el mapa si tu canción lo admite. De lo contrario, tu canción puede ser demasiado corta. En tal caso, intenta extender tu archivo .mp3 para alcanzar la marca de 30 segundos. | AiMod no detecta los spinners que pueden sobrepasar los 30 segundos de drenaje. |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Audio bitrate is lower than 128 kbps. Consider finding a better quality source. | El archivo .mp3 del beatmap está codificado en una [tasa de bits](https://es.wikipedia.org/wiki/Tasa_de_bits) infer
```suggestion
| Audio bitrate is higher than 192 kbps. Consider recompressing to CBR 192 kbps or VBR ~1.0. | El archivo `.mp3` del beatmap está codificado en una [tasa de bits](https://es.wikipedia.org/wiki/Tasa_de_bits) superior a 192 kbps, que supera lo permitido en los [criterios de clasificación](/wiki/Ranking_criteria). | Vuelve a codificar el archivo `.mp3` para que su tasa de bits esté entre 128 kbps y 192 kbps (siendo 192 kbps la opción recomendada). | Aunque esta advertencia existe en el juego, AiMod nunca muestra la advertencia debido a limitaciones técnicas. |
| Audio bitrate is lower than 128 kbps. Consider finding a better quality source. | El archivo .mp3 del beatmap está codificado en una [tasa de bits](https://es.wikipedia.org/wiki/Tasa_de_bits) inferior a 128 kbps, que está por debajo de lo permitido en los [criterios de clasificación](/wiki/Ranking_criteria). | Cambia el archivo .mp3 a uno con una tasa de bits más alta. | Aunque esta advertencia existe en el juego, AiMod nunca muestra la advertencia debido a limitaciones técnicas. |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| The mp3 you are using is a lot longer than the part which is mapped. Consider cropping it to reduce filesize. | El mp3 que estás utilizando es mucho más largo que la parte mapeada. Considera recort
```suggestion
| The mp3 you are using is a lot longer than the part which is mapped. Consider cropping it to reduce filesize. | El mp3 que estás usando es mucho más largo que la parte mapeada. Considera recortarlo para reducir el tamaño del archivo. | Extiende el beatmap o corta la canción. |  |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| {0} out of {1} timing sections have a volume below 5%. | {0} de {1} secciones de temporización tienen un volumen inferior al 5 %. | Establece el volumen de los hitsounds de las secciones de tempori
```suggestion
| {0} out of {1} timing sections have a volume below 5%. | {0} de {1} secciones de tiempo tienen un volumen inferior al 5 %. | Establece el volumen de los hitsounds de las secciones de tiempo silenciosas en un 5 % o más. |  |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| More than 1/2 of the TV Size map is Kiai time. Consider reducing this. | Más de la mitad del mapa TV Size es Kiai time. Considera reducir esto. | Reduce el uso del kiai en todo el mapa. | Esta adve
```suggestion
| More than 1/3 of the map is Kiai time. Consider reducing this. | Más de 1/3 del mapa es kiai time. Considera reducir esto. | Reduce el uso del kiai en todo el mapa. | Esta advertencia se puede ignorar con seguridad si se pretende el uso del kiai en cuestión. |
| More than 1/2 of the TV Size map is Kiai time. Consider reducing this. | Más de la mitad del mapa TV Size es kiai time. Considera reducir esto. | Reduce el uso del kiai en todo el mapa. | Esta advertencia se puede ignorar con seguridad si se pretende el uso del kiai en cuestión. |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Kiai's end isn't snapped! | El punto final del kiai especificado no se ajusta a la línea de tiempo. | Ajusta correctamente el punto final del kiai a su posición deseada en la línea de tiempo. |  |
```suggestion
| Kiai's end isn't snapped! | El punto de finalización del kiai especificado no se ajusta a la línea de tiempo. | Ajusta correctamente el punto de finalización del kiai a su posición deseada en la línea de tiempo. |  |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Breaktime is not suggested for mania maps. | No se sugiere tiempo de descanso para los mapas de mania. | Mapea la parte donde ocurre el tiempo de descanso. | ![](/wiki/shared/mode/mania.png) solo m
```suggestion
| Breaktime is not suggested for mania maps. | No se sugiere tiempo de descanso para los mapas de mania. | Mapea la parte donde ocurre el tiempo de descanso. | ![](/wiki/shared/mode/mania.png) solo mapas de osu!mania. Esta advertencia se puede ignorar con seguridad si se pretende usar el tiempo de descanso en cuestión, o si la sección de la canción no se puede mapear. |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Easy/Normal diff contains too many speed changes. | La dificultad Easy/Normal presenta una cantidad frecuente de cambios de velocidad de los sliders, lo cual no se recomienda en los [criterios de c
```suggestion
| Easy/Normal diff contains too many speed changes. | La dificultad Easy/Normal presenta una cantidad frecuente de cambios de velocidad en los sliders, lo cual no se recomienda en los [criterios de clasificación](/wiki/Ranking_criteria). | Reduce el número de cambios de velocidad en los sliders en la dificultad Easy/Normal en cuestión. |  |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Letterboxing is not allowed in mania mode. | El Letterboxing no está permitido en el modo mania. | Desmarca la opción `Letterbox during breaks` en la pestaña Design de [Song Setup](/wiki/Client/Bea
```suggestion
| Letterboxing is not allowed in mania mode. | El letterboxing no está permitido en el modo mania. | Desmarca la opción `Letterbox during breaks` en la pestaña Design de [Song Setup](/wiki/Client/Beatmap_editor/Song_setup). | ![](/wiki/shared/mode/mania.png) solo mapas de osu!mania |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Audio file conflicts with {0} diff. | El archivo .mp3 utilizado en el mapa difiere entre una dificultad y otra. | Asegúrate de que todas las dificultades utilicen el mismo archivo .mp3 como base. |
```suggestion
| Audio file conflicts with {0} diff. | El archivo .mp3 usado en el mapa difiere entre una dificultad y otra. | Asegúrate de que todas las dificultades usen el mismo archivo .mp3 como base. |  |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Beatmap exceeds allowed upload size ({0}kb allowed) | El archivo `.osz` comprimido es demasiado grande. | Elimina los archivos no utilizados de la carpeta del mapa y comprime los activos (imágenes,
```suggestion
| Beatmap exceeds allowed upload size ({0}kb allowed) | El archivo `.osz` comprimido es demasiado grande. | Elimina los archivos no usados de la carpeta del mapa y comprime los recursos (imágenes, vídeos, hitsounds, etc.) que tengan un tamaño inflado. | Consulta [este artículo](/wiki/Beatmapping/Beatmap_submission#limitaciones) para obtener más información sobre las limitaciones de envío de osu!. |
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
>  - **AiMod no puede detectar una gran cantidad de problemas** que se consideran imposibles de clasificar según los [criterios de clasificación](/wiki/Ranking_criteria), como objetos potencialmente mal
```suggestion
- **AiMod no puede detectar una gran cantidad de problemas** que se consideran imposibles de clasificar según los [criterios de clasificación](/wiki/Ranking_criteria), como objetos potencialmente mal encajados, hitsounds retrasados, imagen de fondo superior a 2,5 MB, etc.
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
>  - **AiMod puede advertirle de problemas que no son**, como que el conjunto de mapas necesita dos dificultades estándar en un mapa de [maratón](/wiki/Beatmap/Marathon) y que el [kiai time](/wiki/Gamep
```suggestion
- **AiMod puede advertirte de problemas que no son**, como que el conjunto de mapas necesita dos dificultades estándar en un mapa de [maratón](/wiki/Beatmap/Marathon) y que el [kiai time](/wiki/Gameplay/Kiai_time) se activa por menos de 15 segundos.
```

2023-12-06 13:26 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +Es recomendable usar otros programas como [Mapset Verifier](https://github.com/Naxesss/MapsetVerifier/releases) hecho por ::{ flag=SE }:: [Naxess](https://osu.ppy.sh/users/8129817) en conjunto con Ai
```suggestion
Es recomendable usar otros programas como [Mapset Verifier](https://github.com/Naxesss/MapsetVerifier/releases) por ::{ flag=SE }:: [Naxess](https://osu.ppy.sh/users/8129817) en conjunto con AiMod si lo que buscas es [clasificar](/wiki/Beatmap/Category#ranked) tu beatmap. Otros programas están más actualizados con los criterios de clasificación y pueden detectar muchos más problemas que AiMod. No obstante, no ignores completamente a AiMod, ya que algunas reglas en los criterios de clasificación las evalúa dicho programa.
```

2023-12-18 13:49 UTC, agatemosu commented on wiki/Client/Beatmap_editor/AiMod/es.md
> +| Your beatmap is shorter than 45 seconds. Consider making it longer. | Tu beatmap tiene menos de 45 segundos. Considera hacerlo más largo. | Mapea más partes de la canción. | Esta advertencia se pue
```suggestion
| Your beatmap is shorter than 45 seconds. Consider making it longer. | Tu beatmap dura menos de 45 segundos. Considera hacerlo más largo. | Mapea más partes de la canción. | Esta advertencia se puede ignorar con seguridad si la longitud del mapa en cuestión es la prevista. |
```

2023-12-18 17:55 UTC, agatemosu approved these changes

2023-12-18 18:00 UTC, agatemosu reviewed
ok no

2023-12-18 18:02 UTC, agatemosu approved these changes

2023-12-27 13:01 UTC, TicClick approved these changes

2023-12-27 14:09 UTC, merged