[FR] Update `Client\Options`
ppy/osu-wiki pull request #10530
Opened 2023-11-24 10:45 UTC by DoryanR

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) > **No contributor**

2023-11-29 20:18 UTC, cl8n commented
for the images you can just use the English ones. no need to have duplicates

2023-11-29 20:18 UTC, cl8n requested changes
^

2023-11-30 17:53 UTC, DoryanR commented
> for the images you can just use the English ones. no need to have duplicates

My bad, fixed.

2023-11-30 23:52 UTC, cl8n approved these changes

2023-11-30 23:54 UTC, merged