[ES] Update `Health`
ppy/osu-wiki pull request #10594
Opened 2023-12-03 11:35 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-03 19:14 UTC, UnknownOsu requested changes

2023-12-03 19:14 UTC, UnknownOsu commented on wiki/Gameplay/Health/es.md
>  Aparecerán ráfagas de puntuación después de golpear un círculo, cambiando la puntuación y los valores de salud dependiendo de la precisión del golpe. Un golpe perfectamente sincronizado (300) recuper
```suggestion
Aparecerán ráfagas de puntuación después de golpear un círculo, cambiando la puntuación y los valores de salud dependiendo de la precisión del golpe. Un golpe perfectamente sincronizado (300) recuperará más salud que un golpe mal sincronizado (50). El jugador también recibirá mejoras más grandes, si logran un katu o un geki al final del combo. Un fallo provocará una caída instantánea de salud. Si los spinners son completados antes de tiempo, seguir girando recuperará salud adicional. Para obtener una descripción general de la recuperación y pérdida de salud, consulta a continuación:
```

2023-12-09 15:31 UTC, UnknownOsu approved these changes

2023-12-09 15:43 UTC, TicClick approved these changes

2023-12-09 15:50 UTC, agatemosu commented
@TicClick

2023-12-09 18:19 UTC, TicClick submitted a review, later dismissed

2023-12-09 18:20 UTC, TicClick approved these changes

2023-12-09 18:21 UTC, merged