[KO] Update Grand Final results for the `owc 2023`
ppy/osu-wiki pull request #10597
Opened 2023-12-03 16:07 UTC by Chronicler01

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-03 23:52 UTC, Sitoria requested changes
native review via request

2023-12-03 23:52 UTC, Sitoria commented on wiki/Tournaments/OWC/2023/ko.md
11번 줄이 과거형으로 변환되었으므로 `주최하는` 보다는 `주최한` 이 맞아 보입니다.

2023-12-03 23:52 UTC, Sitoria commented on wiki/Tournaments/OWC/2023/ko.md
29번 줄에 `최소`라는 단어는 어디서 나왔나요? 
이 문장은 과거형 변환을 포함하여 다시 해석해야 할 것 같습니다.

suggested 
> osu! 월드컵 2023은 $5000의 상금과 한정판 상품을 제공하였습니다.

2023-12-03 23:52 UTC, Sitoria commented on wiki/Tournaments/OWC/2023/ko.md
`merch` 라는 단어를 `굿즈`로 치환하신 것 같은데 `굿즈`와 `상품, 물품`은 엄연히 다른 의미입니다.

`상품` 으로 변경하는 것이 좋아보이네요.

2023-12-03 23:52 UTC, Sitoria commented on wiki/Tournaments/OWC/2023/ko.md
> +## Podium
포디엄은 owc 2022에서 `시상대`로 번역이 되었습니다.

2023-12-03 23:52 UTC, Sitoria commented on wiki/Tournaments/OWC/2023/ko.md
> +![](img/podium.jpg "OWC 2023 podium")
`owc 2023 시상대` 로 번역

2023-12-03 23:52 UTC, Sitoria commented on wiki/Tournaments/OWC/2023/ko.md
>  [^qualifiers-tiebreaker]: 두 팀의 SUM 값이 동일할 경우 타이브레이커로 사용합니다
원문에 온점이 없지만 한국어로 번역시 문법 상 문장에 끝엔 온점이 있어야 합니다.

2023-12-03 23:52 UTC, Sitoria commented on wiki/Tournaments/OWC/2023/ko.md
>  [^qualifiers-tiebreaker]: 두 팀의 SUM 값이 동일할 경우 타이브레이커로 사용합니다
윗줄도 온점 찍어주세요.

2023-12-05 12:02 UTC, iSlodinxOsu requested changes
remove this outdated link
![image](https://github.com/ppy/osu-wiki/assets/112963750/6da49a5d-3cfe-4583-998c-1901dcd8d52a)

2023-12-06 05:05 UTC, Sitoria approved these changes
seems ok
![](https://cdn.discordapp.com/emojis/1163056134769352724.gif)

2023-12-06 05:06 UTC, Walavouchey approved these changes

2023-12-06 05:08 UTC, merged