[ZH] Add `Gameplay/Judgement`
ppy/osu-wiki pull request #10606
Opened 2023-12-04 16:08 UTC by Proxyerium

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

## Changes
- Add `Gameplay/Judgement/zh.md`
- Add `Gameplay/Judgement/osu!/zh.md`

2023-12-04 16:09 UTC, Proxyerium commented
翻译相关的疑问 question about my translation:
- `Hit window` 指的是圆环收缩至圆圈的动画期间，还是代码判定误差的逻辑期间？因为不确定所以弄出来`判定区域`、`判定范围`、`判定区间`，不懂怎么决定😥。

2023-12-05 02:53 UTC, CloneWith reviewed
> 翻译相关的疑问 question about my translation:
- `Hit window` 指的是圆环收缩至圆圈的动画期间，还是代码判定误差的逻辑期间？因为不确定所以弄出来`判定区域`、`判定范围`、`判定区间`，不懂怎么决定😥。 

个人建议用`判定区间`。本文提及的区间是和**整体难度(OD)**对应的。
圆环收缩的动画过程由**缩圈速度(AR)**控制。

2023-12-05 02:53 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +# osu!判定系统
```suggestion
# osu! 判定系统
```

2023-12-05 02:55 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +打击误差和最大打击误差会四舍五入，这意味着相较上述计算公式，判定范围的两端可能会有至多1.5ms的缩短。
```suggestion
打击误差和最大打击误差经过四舍五入处理，这意味着相较上述计算公式，判定范围的两端至多可能缩短1.5ms。
```

2023-12-05 02:56 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +### 激 喝
```suggestion
### “激”和“喝”
```

这里强调一下是两个判定对应的名词

2023-12-05 02:57 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +根据连击的准确程度，[圆圈](/wiki/Gameplay/Hit_object/Hit_circle) 的判定可分为GREAT，OK，MEH 和 MISS。在MISS判定区间之前的点击不会生效（或者触发 [物件锁](/wiki/Gameplay/Judgement/Notelock) ）；在MEH判定区间结束前未点击会判定为MISS。
```suggestion
根据连击的准确程度，[圆圈](/wiki/Gameplay/Hit_object/Hit_circle) 的判定可分为GREAT，OK，MEH 和 MISS。在MISS判定区间之外的点击不会生效（此时会触发 [物件锁](/wiki/Gameplay/Judgement/Notelock) ）；在MEH判定区间结束前未点击会判定为MISS。
```

2023-12-05 02:59 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +[滑条](/wiki/Gameplay/Hit_object/Slider) 由多个部分组成：[滑条头](/wiki/Gameplay/Hit_object/Slider/Sliderhead) 、[滑条尾](/wiki/Gameplay/Hit_object/Slider/Slidertail) 、[滑条点](/wiki/Gameplay/Hit_object/Slider/Slider_ti
```suggestion
[滑条](/wiki/Gameplay/Hit_object/Slider) 由多个部分组成：[滑条头](/wiki/Gameplay/Hit_object/Slider/Sliderhead) 、[滑条尾](/wiki/Gameplay/Hit_object/Slider/Slidertail) 、[滑条点](/wiki/Gameplay/Hit_object/Slider/Slider_tick) 和 [折返点](/wiki/Gameplay/Hit_object/Slider/Reverse_slider) 组成。整个滑条的判定结果依据玩家对各部分的命中情况得出，大致如下：
```

2023-12-05 03:00 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +每个 [转盘](/wiki/Gameplay/Hit_object/Spinner) 都有一组规定完成该物件所需的数，这个数由铺面的 [总体难度](/wiki/Beatmap/Overall_difficulty#滑条和转盘) 决定。转盘转速是根据光标移速计算的，所以不需要数清楚到底转了多少圈。
```suggestion
每个 [转盘](/wiki/Gameplay/Hit_object/Spinner) 都有一组规定完成该物件所需的转数，这个数由谱面的 [总体难度](/wiki/Beatmap/Overall_difficulty#滑条和转盘) 决定。转盘转速是根据光标移速计算的，所以不需要数清楚到底转了多少圈。
```

2023-12-05 03:01 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +| 最小每秒转速[^minimum-sps] | `1.5 + 0.2 × OD` 若 OD < 5, `1.25 + 0.25 × OD` 若 OD ≥ 5 |
```suggestion
| 最小每秒转速[^minimum-sps] | 若 OD < 5：`1.5 + 0.2 × OD`,若 OD ≥ 5：`1.25 + 0.25 × OD`  |
```

2023-12-05 03:02 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +如果一个转盘非常短，所需转数可能会算出0，那么该转盘总会判定为GREAT。
```suggestion
如果一个转盘非常短，计算得出的所需转数可能是0，那么该转盘总会判定为GREAT。
```

2023-12-05 03:02 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +转盘的判定算法曾在 [20190513.2 Stable 发布](https://osu.ppy.sh/home/changelog/stable40/20190513.2)有重大改动。变化如下：
```suggestion
转盘的判定算法曾在 [20190513.2 稳定版](https://osu.ppy.sh/home/changelog/stable40/20190513.2)中发生重大改动。变化如下：
```

2023-12-05 03:03 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +2019年5月10日（此变化 [加进 Cutting Edge 版本](https://osu.ppy.sh/home/changelog/cuttingedge/20190510.1) 的时候）之前的回放会用以前的算法，而不是现在正在使用的。
```suggestion
2019年5月10日（此变化 [被引入测试版](https://osu.ppy.sh/home/changelog/cuttingedge/20190510.1) 的时候）之前的回放会用以前的算法，而不是现在正在使用的。
```

2023-12-05 03:04 UTC, CloneWith requested changes
全文相关的都要改成`打击区间`，因为是同一个意思

2023-12-05 10:07 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +根据连击的准确程度，[圆圈](/wiki/Gameplay/Hit_object/Hit_circle) 的判定可分为GREAT，OK，MEH 和 MISS。在MISS判定区间之前的点击不会生效（或者触发 [物件锁](/wiki/Gameplay/Judgement/Notelock) ）；在MEH判定区间结束前未点击会判定为MISS。
可以，按你说的改🎉

2023-12-06 01:09 UTC, Proxyerium commented on wiki/Gameplay/Judgement/osu!/zh.md
> +根据连击的准确程度，[圆圈](/wiki/Gameplay/Hit_object/Hit_circle) 的判定可分为GREAT，OK，MEH 和 MISS。在MISS判定区间之前的点击不会生效（或者触发 [物件锁](/wiki/Gameplay/Judgement/Notelock) ）；在MEH判定区间结束前未点击会判定为MISS。
🤔物件锁点在其他物件上才发生，这里的意思也是说两种情况，那就不应该用“此时”了。

2023-12-06 03:39 UTC, CloneWith approved these changes

2023-12-06 03:40 UTC, CloneWith commented on wiki/Gameplay/Judgement/osu!/zh.md
> +根据连击的准确程度，[圆圈](/wiki/Gameplay/Hit_object/Hit_circle) 的判定可分为GREAT，OK，MEH 和 MISS。在MISS判定区间之前的点击不会生效（或者触发 [物件锁](/wiki/Gameplay/Judgement/Notelock) ）；在MEH判定区间结束前未点击会判定为MISS。
**resolved in new commits**

2023-12-06 08:37 UTC, TicClick approved these changes

2023-12-06 08:39 UTC, merged