[ES] Update `Distance snap`
ppy/osu-wiki pull request #10617
Opened 2023-12-08 20:40 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-08 21:35 UTC, UnknownOsu requested changes

2023-12-08 21:35 UTC, UnknownOsu commented on wiki/Client/Beatmap_editor/Distance_snap/es.md
> +El ajuste de distancia se puede alternar desde la pestaña [`Compose`](/wiki/Client/Beatmap_editor/Compose) presionando `Y` o —temporalmente— manteniendo presionada la tecla `Alt` (lo cual puede ser m
```suggestion
El ajuste de distancia se puede alternar desde la pestaña [`Compose`](/wiki/Client/Beatmap_editor/Compose) presionando `Y` o —temporalmente— manteniendo presionada la tecla `Alt` (lo cual puede ser más preferible, ya que la herramienta limita la ubicación del objeto a un círculo de cierto radio). El multiplicador de distancia de espaciado se puede cambiar manteniendo presionada la tecla `Alt` y usando la rueda del ratón o arrastrando el control deslizante de `Distancia entre notas` en la esquina superior izquierda.
```

2023-12-08 21:42 UTC, UnknownOsu approved these changes

2023-12-09 15:29 UTC, TicClick approved these changes

2023-12-09 15:33 UTC, merged