[ES] Retranslate `osu!mania ranking criteria`
ppy/osu-wiki pull request #10615
Opened 2023-12-08 20:19 UTC by agatemosu

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-21 16:51 UTC, UnknownOsu requested changes

2023-12-21 16:51 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!mania/es.md
> +- **Estilo de juego**: El estilo previsto por un mapper de [combinaciones de teclas](/wiki/Game_mode/osu!mania#controles) o posiciones de manos usado para jugar una dificultad.
```suggestion
- **Estilo de juego**: El estilo previsto por un mapper en las [combinaciones de teclas](/wiki/Game_mode/osu!mania#controles) o posición de las manos para jugar una dificultad.
```

2023-12-21 16:51 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!mania/es.md
> +Consulta la [guía de mapping de osu!mania](/wiki/Guides/osu!mania_mapping_guide) para obtener más terminología de patrones.
```suggestion
Consulta la [guía de mapping de osu!mania](/wiki/Guides/osu!mania_mapping_guide) para obtener más información sobre la terminología de los patrones.
```

2023-12-21 16:51 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!mania/es.md
> +- **Las dificultades que utilicen un [estilo de juego N+1](#términos-comunes) deben activar la opción `Use special style (N+1 style) for mania` en la pestaña `Advanced` de la ventana `Song Setup`. El
```suggestion
- **Las dificultades que usen un [estilo de juego N+1](#términos-comunes) deben activar la opción `Use special style (N+1 style) for mania` en la pestaña `Advanced` de la ventana `Song Setup`. El beatmap también debe incluir la etiqueta «N+1».** A efectos de esta regla, solo los estilos de juego con un cantidad de teclas inferior a 10 pueden considerarse «N+1».[^n-plus-1]
```

2023-12-21 16:51 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!mania/es.md
> +- **Evite usar más de 9 notas en split-jumptrills.** Estos son más agotadores físicamente que otros patrones de densidad similar.
```suggestion
- **Evita usar más de 9 notas en split-jumptrills.** Estos son más agotadores físicamente que otros patrones de densidad similar.
```

2023-12-21 16:51 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!mania/es.md
> +  - ... 1/1, no debe haber más de 3 notas, excepto al principio/final de una stream, cuando 4 es aceptable.
```suggestion
  - ... 1/1, no debe haber más de 3 notas, excepto al principio/final de un stream, cuando 4 es aceptable.
```

2024-01-14 21:17 UTC, UnknownOsu approved these changes

2024-01-14 21:57 UTC, Walavouchey approved these changes

2024-01-14 21:58 UTC, merged