[ZH] Add `Interface/Multiplayer`
ppy/osu-wiki pull request #10660
Opened 2023-12-17 06:08 UTC by CloneWith

* Todo: Add missing images

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-24 06:10 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +**多人游戏** （**Multiplayer**，有时简写为 *Multi*）是一个游戏模式，最多允许 16 位玩家参加，他们可以单独或组队对抗，也可以一起合作游玩，游玩的谱面由房主决定。
```suggestion
**多人游戏** （**Multiplayer**，有时简写为 *Multi*）是最多允许 16 位玩家进行个人对抗、团队对抗或合作游玩的游戏模式，游玩的谱面由房主决定。
```

我觉得**概述句**不宜用太多不同的主语，主要信息集中到一句话就好。

2023-12-24 07:22 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +*注意：需要 [osu! 账号](/wiki/Registration)来参加多人游戏，[已禁言](/wiki/Silence)的玩家无法参加。*
```suggestion
*注意：需要 [osu! 账号](/wiki/Registration)来参加多人游戏，[被禁言](/wiki/Silence)的玩家无法参加。*
```

2023-12-24 07:33 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +在创建或进入比赛房间后，会显示比赛配置页。本文下面几节会按从上到下、从左到右的顺序，着重讲解此页面的不同部分。
```suggestion
在创建或进入比赛房间后，会显示比赛配置页。下文会按从上到下、从左到右的顺序，着重讲解此页面的各个部分。
```

2023-12-24 07:37 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +光标悬停在表中玩家上时，会显示对应玩家的等级、国家或地区及[整体准确率](/wiki/Gameplay/Accuracy)。
```suggestion
光标悬停在表中玩家上时，会显示对应玩家的等级、国家或地区和[整体准确率](/wiki/Gameplay/Accuracy)。
```

2023-12-24 07:40 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +| **红色（没有地图）** | 玩家没有谱面，在下载好谱面前都会显示 `[没有地图]` 通知。 |
```suggestion
| **红色（没有此图）** | 玩家没有谱面，在下载好谱面之前都会显示 `[没有此图]` 。 |
```

2023-12-24 07:44 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +| **浅蓝色（游玩中）** | 玩家正在游玩，在比赛结束前都会显示 `[游玩中]` 通知。 |
```suggestion
| **浅蓝色（游玩中）** | 玩家正在游玩，在比赛结束前都会显示 `[游玩中]` 。 |
```

`notice`不太好翻译啊，干脆直接扔了😎

2023-12-24 07:52 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +| `Not uploaded or not up-to-date（未上传或非最新）` | 无法下载此谱面。如果问题仍然存在，房主应该帮玩家找到（[谱面列表](https://osu.ppy.sh/beatmapsets)中的）链接。 |
```suggestion
| `Not uploaded or not up-to-date（未上传或非最新）` | 无法下载此谱面。如果问题无法解决，房主应该帮玩家找到（[谱面列表](https://osu.ppy.sh/beatmapsets)中的）链接。 |
```

2023-12-24 07:59 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +| `Tag co-op` （仅限 osu! 模式，不计入排名） | 一起完成谱面，一次打一串连击。 |
```suggestion
| `Tag co-op` （仅限 osu! 模式，不计入排名） | 一起完成谱面，每位玩家一次打一组连击。 |
```

2023-12-24 07:59 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +| `Tag-team VS` （仅限 osu! 模式，不计入排名） | 与 `Tag co-op` 相同，但是有两支队伍相互对立。 |
```suggestion
| `Tag-team VS` （仅限 osu! 模式，不计入排名） | 与 `Tag co-op` 相同，但是有两支队伍相互对抗。 |
```

2023-12-24 08:01 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +如果组队模式是 `Tag co-op` 或 `Tag-team VS`，则会显示 `Tag Colour（Tag 颜色）: (combo colour)` 小节，让每位玩家可以选择自定义颜色。如果颜色设置为 `Default（默认）`，则会使用谱面原有的连击组颜色。
```suggestion
如果组队模式是 `Tag co-op` 或 `Tag-team VS`，则会显示 `Tag Colour（Tag 颜色）: (combo colour)` 选项，让每位玩家可以选择自定义颜色。如果颜色设置为 `Default（默认）`，则会使用谱面原有的连击颜色。
```

2023-12-24 08:04 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +左边的橙色 `离开房间` 按钮的作用不言自明。当房主离开房间时，房主资格会按槽位自动转移给剩余玩家。房间里没有玩家时会自动关闭，但由 [`!mp` 命令](/wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands)建立的房间除外，这类房间会在 30 分钟后关闭。
```suggestion
左边的橙色 `离开房间` 按钮的作用顾名思义。当房主离开房间时，房主资格会按槽位自动转移给剩余玩家。房间里没有玩家时会自动关闭，但由 [`!mp` 命令](/wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands)建立的房间除外，这类房间会在 30 分钟后关闭。
```

2023-12-24 08:05 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +蓝色按钮用于控制玩家的准备状态，也可以使比赛开始。
```suggestion
蓝色按钮用于控制玩家的准备状态，以及开始比赛。
```

2023-12-24 08:45 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +当玩家的血条完全清空时，玩家仍然可以继续游玩，但会被视作失败，其分数不会出现在排行榜上。在没有使用 [Sudden Death (SD)](/wiki/Gameplay/Game_modifier/Sudden_Death) 游戏模组的情况下，玩家在血条回满时就会复活。
```suggestion
当玩家的血条掉光时，玩家仍然可以继续游玩，但会被视作失败，其分数不会出现在排行榜上。在没有使用 [Sudden Death (SD)](/wiki/Gameplay/Game_modifier/Sudden_Death) 游戏模组的情况下，玩家在血条回满时就会复活。
```

2023-12-24 08:46 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +#### 结果
```suggestion
#### 结算
```

2023-12-24 08:51 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +| ![](img/Playerbox/Multi_PB_B.jpg "正常") | 正常 | 玩家剩余血量超过一半。取决于血量变化，颜色可能会变亮，也可能变成红色。 |
```suggestion
| ![](img/Playerbox/Multi_PB_B.jpg "正常") | 正常 | 玩家剩余血量超过一半。颜色会根据血量变为亮蓝色或亮红色。 |
```

2023-12-24 08:52 UTC, Proxyerium commented on wiki/Client/Interface/Multiplayer/zh.md
> +| ![](img/Playerbox/Multi_PB_R.jpg "危险") | 危险 | 玩家剩余血量不到一半。取决于血量变化，颜色可能会变亮，也可能变成蓝色。 |
```suggestion
| ![](img/Playerbox/Multi_PB_R.jpg "危险") | 危险 | 玩家剩余血量少于一半。颜色会根据血量变为亮蓝色或亮红色。 |
```

2023-12-24 12:31 UTC, Proxyerium reviewed
这回看完了

2023-12-24 14:25 UTC, Proxyerium approved these changes

2023-12-27 14:55 UTC, TicClick requested changes
please retake the screenshots, they need to be 1280x720: https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#screenshots-of-gameplay

2023-12-28 14:17 UTC, CloneWith commented
@TicClick
have planned for image updating, but busy with other work 🔥 
so I deleted those images and may upload them later in another PR

2023-12-31 11:05 UTC, TicClick approved these changes

2023-12-31 11:07 UTC, merged