[ES] Add `Judgement/osu!catch`
ppy/osu-wiki pull request #10679
Opened 2023-12-23 17:55 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-23 21:28 UTC, UnknownOsu requested changes

2023-12-23 21:28 UTC, UnknownOsu commented on wiki/Gameplay/Judgement/osu!catch/es.md
> +- La precisión en osu!catch se calcula como la proporción de frutas, gotas y gotitas capturadas.
```suggestion
- La precisión en osu!catch se calcula como la proporción de frutas, gotas y gotitas atrapadas.
```

2023-12-23 21:28 UTC, UnknownOsu commented on wiki/Gameplay/Judgement/osu!catch/es.md
> +- Las frutas y las gotas aumentan el combo y provocan fallos, mientras que las gotas y los plátanos no tienen ningún efecto.
```suggestion
- Las frutas y las gotas aumentan el combo y provocan fallos, mientras que las gotitas y los plátanos no tienen ningún efecto.
```

2023-12-23 21:34 UTC, UnknownOsu approved these changes

2023-12-27 12:14 UTC, TicClick approved these changes

2023-12-27 12:18 UTC, merged