[ES] Rename `comportamiento` to `conducta`
ppy/osu-wiki pull request #10684
Opened 2023-12-23 19:37 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-23 20:27 UTC, UnknownOsu requested changes

2023-12-23 20:27 UTC, UnknownOsu commented on wiki/History_of_osu!/Mapping_and_modding_timeline/es.md
> +- **26/8/2016:** El [código de conducta](/wiki/Rules/Code_of_conduct_for_modding_and_mapping) se implementó para establecer las expectativas de conducta en modding.
```suggestion
- **26/8/2016:** El [código de conducta](/wiki/Rules/Code_of_conduct_for_modding_and_mapping) se implementó para establecer las expectativas de conducta en el modding.
```

2023-12-23 20:27 UTC, UnknownOsu commented on wiki/People/Global_Moderation_Team/es.md
> +2. Demostrar actividad en el juego participando en el chat y/o los foros. [Reporta cualquier mala conducta](/wiki/Reporting_bad_behaviour) y problemas a través del sistema de reportes. Responder preg
```suggestion
2. Demostrar actividad en el juego participando en el chat y/o los foros. [Reportar cualquier mala conducta](/wiki/Reporting_bad_behaviour) y problemas a través del sistema de reportes. Responder preguntas y ayudar a otros con problemas.
```

2023-12-23 20:27 UTC, UnknownOsu commented on wiki/Tournaments/OWC/2021/es.md
> +16. Se espera que los jugadores mantengan el juego fluido y sin retrasos. Los retrasos excesivos en los partidos por parte de los jugadores pueden dar lugar a la aplicación de sanciones a discreción
```suggestion
16. Se espera que los jugadores mantengan el juego fluido y sin retrasos. Los retrasos excesivos en los partidos por parte de los jugadores pueden dar lugar a la aplicación de sanciones a discreción del árbitro. Interrumpir el partido con juego sucio, insultar o provocar a otros jugadores o al personal, retrasar el partido u otra conducta inapropiada deliberada está estrictamente prohibida y será sancionada en consecuencia.
```

2023-12-23 20:31 UTC, agatemosu commented on wiki/People/Global_Moderation_Team/es.md
> +2. Demostrar actividad en el juego participando en el chat y/o los foros. [Reporta cualquier mala conducta](/wiki/Reporting_bad_behaviour) y problemas a través del sistema de reportes. Responder preg
lee toda la frase

2023-12-23 20:31 UTC, agatemosu commented on wiki/Tournaments/OWC/2021/es.md
> +16. Se espera que los jugadores mantengan el juego fluido y sin retrasos. Los retrasos excesivos en los partidos por parte de los jugadores pueden dar lugar a la aplicación de sanciones a discreción
haré otra cosa

2023-12-27 13:30 UTC, UnknownOsu approved these changes

2023-12-27 23:17 UTC, TicClick approved these changes

2023-12-27 23:17 UTC, merged