Update wiki page of GBC 2023 Autumn
ppy/osu-wiki pull request #10710
Opened 2023-12-27 07:43 UTC by yobrevelc

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-27 07:55 UTC, RushFTK approved these changes

2023-12-27 09:04 UTC, Walavouchey requested changes

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| **Q12: Team 12** | **7** | 5 | Q3: 兰州拉面专业培训班 | [#2](https://osu.ppy.sh/community/matches/111750301) |
the match links should all be `#1`. it's just a formatting thing. if there are two multiplayer lobbies for one match, it'd be `[#1](), [#2]()`

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +| **D2: viets sing** | **0** | -1 | D1: ChatGBC | Win by default |
on all of these

```suggestion
| **D2: viets sing** | **0** | -1 | D1: ChatGBC | *win by default* |
```

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +3. Following the regular stage, the elimination stage will be played in both divisions, called *playoffs*. The top 8 teams from the regular stage in each zones will advance to a winner bracket, other
```suggestion
3. Following the regular stage, the elimination stage will be played in both divisions, called *playoffs*. The top 8 teams from the regular stage in each zone will advance to a winner bracket, other teams will get into loser bracket.
```

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - From the mappool #1 in regular stage round 1, every mappool will change half of the pool from the previous one. Mappool #2 will change all the RC map from mappool #1, and mappool #3 will change
```suggestion
   - From the mappool #1 in regular stage round 1, every mappool will change half of the pool from the previous one. Mappool #2 will change all the RC maps from mappool #1, and mappool #3 will change all the HB + LN map from mappool #2. This process will repeat until the last mappool.
```

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - SV map will also follow that rules, mappool #2 will change SV1, mappool #3 will change SV2, so on until the last mappool.
```suggestion
   - SV maps also follow the same rule: mappool #2 will change SV1, mappool #3 will change SV2, and so on until the last mappool.
```

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - TB map will always be changed in each mappools.
```suggestion
   - TB maps will always be changed in each mappool.
```

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Per Quarterfinals mappool size expansion, there will be an extra RC map released in that mappool than round 4.
```suggestion
   - Due to the Quarterfinals mappool size expansion, there will be an extra RC map in that mappool compared to round 4.
```

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Qualifiers: 8 beatmaps
```suggestion
   - Qualifiers: 8 beatmaps
```

2023-12-27 09:04 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Mappool in elimination phase: 17 beatmaps.
```suggestion
   - Mappool in the regular phase: 15 beatmaps
   - Mappool in the elimination phase: 17 beatmaps.
```

2023-12-27 11:11 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Autumn/en.md
> +   - Due to the Quarterfinals mappool size expansion, there will be an extra RC map in that mappool compared to round 4.
following explanation on discord

```suggestion
   - The mappool size expands by 1 slot in the Quarterfinals, adding one extra RC map to the pool. For this round, the rest of the RC maps are kept from the previous round, while the HB + LN maps are switched to new ones.
```

2023-12-29 06:57 UTC, RushFTK approved these changes

2023-12-29 19:05 UTC, Walavouchey requested changes

2023-12-30 01:22 UTC, Walavouchey approved these changes

2023-12-30 01:24 UTC, merged