[KO] Add `Beatmap/TAG`
ppy/osu-wiki pull request #10718
Opened 2023-12-28 01:56 UTC by Sitoria

## Check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] @sylphi or @CivilWiki 
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-28 04:38 UTC, CivilWiki requested changes

2023-12-28 04:38 UTC, CivilWiki commented on wiki/Beatmap/TAG/ko.md
> +TAG [난이도](/wiki/Beatmap/Difficulty)는 보통 비트맵 난이도 이름에 TAG라는 용어를 사용해 표시합니다. TAG 뒤에 숫자가 붙는 경우가 대다수이며, 이 숫자는 보통 해당 난이도를 몇 명의 플레이어를 요구하는지를 나타냅니다. (예를 들면 2인일 때, TAG2, 4인 플레이 요구시 TAG4 등)
TAG 뒤에 숫자가 붙는 경우가 대다수이며 -> 주로 TAG 뒤에 숫자가 붙고,

2023-12-28 04:38 UTC, CivilWiki commented on wiki/Beatmap/TAG/ko.md
> +이런 이유로 인해, TAG 난이도는 unranked 상태가 되거나 [러브드](/wiki/Beatmap/Category#loved) 상태로 바뀌었습니다. 솔로 플레이에서는 클리어가 불가능하도록 의도적으로 설계되었기 때문입니다.
옛날에는 TAG 비트맵이 랭크가능한 시절이었던 경우를 생각하면 이미 랭크되었던 비트맵을 unranked로 되돌리는것은 무리기에 unranked 상태로 다시 되돌아가진 않습니다. 또한 이 라인에서의 "either"는  뒤에 카테고리 2개 이상이 있기에, "둘 중 하나"로 볼 수 있습니다. 
고로 아래 번역을 제안합니다.

이러한 특성으로 인해, TAG 난이도는 한 플레이어로는 거의 불가능하도록 설계되어 있기에, 현재 unranked 혹은 Loved 상태입니다.

2023-12-28 04:40 UTC, CivilWiki requested changes
sorry for adding additional review

2023-12-28 04:40 UTC, CivilWiki commented on wiki/Beatmap/TAG/ko.md
> +이 모드에서는, 각 플레이어가 하나의 [콤보셋](/wiki/Beatmapping/Combo)을 담당하며, 곡이 진행되는 동안 플레이어는 콤보셋트가 바뀔때마다 지정되어 플레이합니다. 이러한 이유로 TAG 비트맵은 콤보셋이 보통의 비트맵보다 훨씬 멀리 떨어져있고 복잡하게 배치되어 플레이어 혼자서는 비트맵을 플레이하는 것이 거의 불가능합니다.
플레이어 혼자서는 ~ 에서 "는"은 빼셔도 괜찮을 것 같아요

2023-12-28 07:35 UTC, Sitoria reviewed
Applied 1st review

2023-12-28 07:35 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +**태그**는 [협동 태그 혹은 태그 팀전](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs) 멀티플레이어 모드를 설명하는 단어로, 플레이어가 협동하여 [비트맵](/wiki/Beatmap)을 완료하는 것을 뜻합니다. 이 모드를 위해 특별히 제작된 비트맵을 보통 **TAG 비트맵/난이도**라고 부릅니
re-sentenced
```suggestion
**TAG**는 멀티 플레이 팀 모드 내 [TAG Co-op 혹은 TAG Team vs](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs)를 말하며, 플레이어가 협력하여 [비트맵](/wiki/Beatmap)을 클리어하는 것을 목표로 합니다. 이 모드를 위해 특별히 제작된 비트맵을 보통 **TAG 비트맵/난이도**라고 부릅니다.
```

2023-12-28 07:35 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +# 태그 (TAG)
revert 태그 to TAG

2023-12-28 07:35 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +이 모드에서는, 각 플레이어가 하나의 [콤보셋](/wiki/Beatmapping/Combo)을 담당하며, 곡이 진행되는 동안 플레이어는 콤보셋트가 바뀔때마다 지정되어 플레이합니다. 이러한 이유로 TAG 비트맵은 콤보셋이 보통의 비트맵보다 훨씬 멀리 떨어져있고 복잡하게 배치되어 플레이어 혼자서는 비트맵을 플레이하는 것이 거의 불가능합니다.
changed log
```suggestion
이 모드에서는, 각 플레이어가 하나의 [콤보셋](/wiki/Beatmapping/Combo)을 담당하며, 곡이 진행되는 동안 콤보셋이 바뀔때마다 플레이어가 교대로 플레이합니다. 이러한 이유로 TAG 비트맵은 콤보셋이 일반적인 비트맵보다 훨씬 멀리 떨어져있고 복잡하게 배치되어 플레이어 혼자서 비트맵을 플레이하는 것이 거의 불가능합니다.
```

2023-12-28 07:35 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +TAG [난이도](/wiki/Beatmap/Difficulty)는 보통 비트맵 난이도 이름에 TAG라는 용어를 사용해 표시합니다. TAG 뒤에 숫자가 붙는 경우가 대다수이며, 이 숫자는 보통 해당 난이도를 몇 명의 플레이어를 요구하는지를 나타냅니다. (예를 들면 2인일 때, TAG2, 4인 플레이 요구시 TAG4 등)
applied

2023-12-28 07:35 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +이런 이유로 인해, TAG 난이도는 unranked 상태가 되거나 [러브드](/wiki/Beatmap/Category#loved) 상태로 바뀌었습니다. 솔로 플레이에서는 클리어가 불가능하도록 의도적으로 설계되었기 때문입니다.
changed log
```suggestion
TAG 난이도는 솔로 플레이에서 클리어가 불가능하도록 의도적으로 설계되었기 때문에 현재는 unranked 상태이거나 [Loved](/wiki/Beatmap/Category#loved) 상태로 남아있습니다. 
```

2023-12-28 13:09 UTC, Chronicler01 commented on wiki/Beatmap/TAG/ko.md
> +**TAG**는 멀티 플레이 팀 모드 내 [TAG Co-op 혹은 TAG Team vs](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs)를 말하며, 플레이어가 협력하여 [비트맵](/wiki/Beatmap)을 클리어하는 것을 목표로 합니다. 이 모드를 위해 특별히 제작된 비트맵을 보통 **TAG 비
태그에도 협동을 넣었는데 여기에서만 협력하여 ~것을 목표로 합니다 하는 이유가 있을까요?

플레이어들이 협동해서 ~ 라는 방식은 어떤가요

2023-12-29 00:32 UTC, CivilWiki commented on wiki/Beatmap/TAG/ko.md
> +**TAG**는 멀티 플레이 팀 모드 내 [TAG Co-op 혹은 TAG Team vs](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs)를 말하며, 플레이어가 협력하여 [비트맵](/wiki/Beatmap)을 클리어하는 것을 목표로 합니다. 이 모드를 위해 특별히 제작된 비트맵을 보통 **TAG 비
네, 협력이라는 단어를 의도적으로 사용하였습니다. "협동하다"가 서로 힘과 마음을 합치다라면, "협력하다"는 힘을 합하여 서로 돕다라는 의미를 가지고 있기 때문에, TAG의 목적인 Tag Team VS와 Tag Co-op 모드 내에서 비트맵을 각 플레이어의 힘을 합하여 클리어를 시도한다는 뉘앙스로 협력이 더 옳다 생각하여 위와 같이 제시하였습니다 👌

2023-12-29 00:37 UTC, CivilWiki commented on wiki/Beatmap/TAG/ko.md
> +TAG 난이도는 솔로 플레이에서 클리어가 불가능하도록 의도적으로 설계되었기 때문에 현재는 unranked 상태이거나 [Loved](/wiki/Beatmap/Category#loved) 상태로 남아있습니다.
2. 현재는 < 이거는 be 동사의 쓰임새 중 시간의 상태의 의미로서 확대해석을 했습니다. 원문에서는 TAG difficulties are ~ 로 되어있기 때문에 그걸 따라가서 현재는 ~ 이라는 의역을 제시했구요.

3. 그럼 저희 원문에서도 의견 제시를 해야하는 부분인가요? 이럴 때 어떻게 조치해야 하는지 경험이 없어서 선뜻 말하기 힘든 파트네요.

2023-12-29 07:53 UTC, Sitoria reviewed
Apply 2nd Review

2023-12-29 07:53 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +TAG [난이도](/wiki/Beatmap/Difficulty)는 보통 비트맵 난이도 이름에 TAG라는 용어를 사용해 표시합니다. 주로 TAG 뒤에 숫자가 붙으며, 이 숫자는 보통 해당 난이도를 몇 명의 플레이어를 요구하는지를 나타냅니다. (예를 들면 2인일 때, TAG2, 4인 플레이 요구시 TAG4 등)
applied

2023-12-29 07:53 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +TAG 난이도는 솔로 플레이에서 클리어가 불가능하도록 의도적으로 설계되었기 때문에 현재는 unranked 상태이거나 [Loved](/wiki/Beatmap/Category#loved) 상태로 남아있습니다.
4번 적용하면 2변 적용해도 괜찮네요
어차피 TAG가 어프나 랭크였던건 옛날이고 지금은 다 럽드니 오래된 유저 아니면 모르니까 그냥 `현재는` 지우겠습니다.

2024-01-14 02:30 UTC, Sitoria commented on wiki/Beatmap/TAG/ko.md
> +**TAG**는 플레이어끼리 협력하여 [비트맵](/wiki/Beatmap)을 클리어하는 멀티 플레이 팀 모드 [TAG Co-op 혹은 TAG Team vs](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs)를 설명하는 용어입니다. 이 모드를 위해 특별히 제작된 비트맵을 보통 **TAG 비트맵/난이도
d

2024-01-14 02:30 UTC, Sitoria commented
Ready to Merge

2024-01-14 02:35 UTC, Walavouchey approved these changes

2024-01-14 02:37 UTC, merged