Update lazer download link in `Help centre`
ppy/osu-wiki pull request #10729
Opened 2023-12-29 18:42 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-12-29 18:43 UTC, Walavouchey requested changes

2023-12-29 18:43 UTC, Walavouchey commented on wiki/Help_centre/Upgrading_to_lazer/en.md
> +You can find it for download [here](https://osu.ppy.sh/home/download). In the near future, you will be able to switch to lazer from stable (from the `Release stream` setting) and find the download li
```suggestion
You can find it for download [here](https://osu.ppy.sh/home/download). In the near future, you will be able to switch to lazer from stable (from the `Release stream` setting).
```

2023-12-29 18:43 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/en.md
> +You can find it for download [here](https://osu.ppy.sh/home/download). In the near future, you will be able to switch to lazer from stable (from the `Release stream` setting) and find the download li
how fast

2023-12-29 19:06 UTC, Walavouchey approved these changes

2023-12-29 19:07 UTC, The-Last-Cookie approved these changes
German is okay :+1:

2023-12-29 19:30 UTC, agatemosu commented
@CloneWith plz review

2023-12-30 00:46 UTC, CloneWith commented
Chinese translation is ok ✅

2023-12-30 00:53 UTC, CloneWith approved these changes

2023-12-30 17:28 UTC, Sclafus commented
Italian looks good

2024-01-01 00:36 UTC, cl8n approved these changes

2024-01-01 16:19 UTC, peppy approved these changes

2024-01-01 16:19 UTC, merged