[ES] Add `Community` and `Video series`
ppy/osu-wiki pull request #10738
Opened 2023-12-30 15:28 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-30 19:11 UTC, UnknownOsu requested changes

2023-12-30 19:11 UTC, UnknownOsu commented on wiki/Community/es.md
> +Esta página enumera formas para que personas de todo osu! se pongan en contacto entre sí. Si estás buscando oportunidades de contribución, pero no sabes por dónde empezar, asegúrate de leer [¡Cómo pu
```suggestion
Esta página enumera las formas en que las personas de todo osu! pueden ponerse en contacto entre sí. Si estás buscando formas para contribuir, pero no sabes por dónde empezar, asegúrate de leer [¡Cómo puedes ayudar!](/wiki/Community/How_you_can_help!)
```

2024-01-14 22:42 UTC, UnknownOsu approved these changes

2024-01-25 10:57 UTC, TicClick approved these changes

2024-01-25 11:02 UTC, merged