[ES] Upgrading to lazer
ppy/osu-wiki pull request #10731
Opened 2023-12-30 00:11 UTC by Ladwick

**Add article** -  _Actualizando a lazer_

Added a note explaining the _"What is sharper than cutting edge?"_ joke.
I didn't translated _Classic_ or _Difficulty Adjust_ since mods aren't localized in lazer yet and it could bring confusion.

This article will see some changes soon with lazer ranked play release coming so I'll be on the lookout.

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-12-30 02:50 UTC, UnknownOsu requested changes

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Si importo mis beatmaps a lazer, ¿Usará el doble de espacio en disco?
```suggestion
#### Si importo mis beatmaps a lazer, ¿usará el doble de espacio en disco?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Si borro lazer, ¿Dañará mi instalación de stable?
```suggestion
#### Si borro lazer, ¿dañará mi instalación de stable?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Si establezco una puntuación en lazer, ¿Se mostrará en mi perfil?
```suggestion
#### Si establezco una puntuación en lazer, ¿se mostrará en mi perfil?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Las puntuaciones se mostraran debajo de "jugadas recientes" pero no en "mejor rendimiento" aún.
```suggestion
Las puntuaciones se mostrarán debajo de «jugadas recientes» pero no en «mejor rendimiento» aún. 
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Si establezco una puntuación en lazer, ¿Dará puntos de rendimiento?
```suggestion
#### Si establezco una puntuación en lazer, ¿dará puntos de rendimiento?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +La sección de "jugadas recientes" de las páginas de perfil muestra puntuaciones establecidas en lazer con puntos de rendimiento calculados y la cantidad total se puede ver al pasar el cursor sobre el
```suggestion
La sección de «jugadas recientes» de las páginas de perfil muestra puntuaciones establecidas en lazer con los puntos de rendimiento calculados, y la cantidad total se puede ver al pasar el cursor sobre el total de puntos de rendimiento regular.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +De hecho, ¡Puedes cambiar la configuración `Modo de visualización de la puntuación` a `Clásico` para recuperar el explosivo estilo de puntuación en todo el juego! No estará perfectamente igualado, pe
```suggestion
¡De hecho, puedes cambiar la configuración `Modo de visualización de la puntuación` a `Clásico` para recuperar el explosivo estilo de puntuación en todo el juego! No estará perfectamente igualado, pero te dará la misma sensación de la puntuación clásica y se aplicará en todos los lugares que esperarías que esté.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Si establezco una puntuación en lazer, ¿Permanecerá por siempre?
```suggestion
#### Si establezco una puntuación en lazer, ¿permanecerá por siempre?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Mientras que intentamos preservar la mayor cantidad de puntuaciones posibles, **no ofrecemos garantía de que las puntuaciones permaneceran indefinidamente**. En algún punto puede que elijamos limpiar
```suggestion
Mientras que intentamos preservar la mayor cantidad de puntuaciones posibles, **no ofrecemos garantía de que las puntuaciones permaneceran indefinidamente**. En cualquier momento podemos optar por borrar un subconjunto o todas las puntuaciones para preservar el balance del juego.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Por favor, intenta aplicar el mod "Classic", el cual restaura mucho del viejo comportamiento al que estás acostumbrado. También asegúrate de comprobar las configuraciones ofrecidas por el mod Classic
```suggestion
Por favor, intenta aplicar el mod «Classic», el cual restaura mucho del viejo comportamiento al que estás acostumbrado. También asegúrate de comprobar las configuraciones ofrecidas por el mod Classic, ya que te permitirá personalizar tu experiencia más allá y también te permitirá entender qué cambios están siendo aplicados (ya que están listados ahí).
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Las skins antiguas servirán en las pantallas de elección de canción y resultados en algún momento?
```suggestion
#### ¿Las skins antiguas servirán en las pantallas del selector de canciones y resultados en algún momento?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Lazer sondea para una entrada de 1.000 Hz sin importar el limitador de FPS, razón por la cual la configuración máxima del limitador también se limita a 1.000 FPS.
```suggestion
Lazer sondea para una entrada de 1000 Hz sin importar el limitador de FPS, razón por la cual la configuración máxima del limitador también se limita a 1000 FPS.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Si tienes curiosidad acerca de como esto afecta la latencia de entrada y quieres probar tu propia percepción, por favor ejecuta el "certificador de latencia" integrado al final de las configuraciones
```suggestion
Si tienes curiosidad acerca de como esto afecta la latencia de entrada y quieres probar tu propia percepción, por favor ejecuta el «certificador de latencia» integrado al final de las configuraciones.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Si la entrada está sondeada a solo 1.000 Hz, ¿Qué hay acerca de mi ratón gaming de 8.000 hz?
```suggestion
#### Si la entrada está sondeada a solo 1000 Hz, ¿qué hay acerca de mi ratón gaming de 8000 Hz?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +El sistema operativo todavía sondeará a una tasa más alta, aunque los beneficios han probado ser insignificantes. Sondear a tales altas tazas puede tener desgastes imprevistos y recomendamos limitar
```suggestion
El sistema operativo todavía sondeará a una tasa más alta, aunque los beneficios han probado ser insignificantes. Sondear a tales altas tazas puede tener desgastes imprevistos y recomendamos limitar los dispositivos a 1000 Hz para la estabilidad del sistema.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Mientras que en la mayor parte del hardware moderno vemos como lazer supera a stable en rendimiento, siempre hay casos extremos cuando cada usuario tiene una configuración de hardware distinta. En nu
```suggestion
Mientras que en la mayor parte del hardware moderno vemos como lazer supera a stable en rendimiento, siempre hay casos extremos cuando cada usuario tiene una configuración de hardware distinta. En nuestros planes a corto plazo estamos intentando dar soporte a DirectX (también conocido como «modo compatibilidad» en stable) y Vulkan, ambos con mejor soporte de drivers que OpenGL en todo el hardware. Una vez que esto haya sido implementado, el rendimiento en hardware tal como chipsets integrados de Intel mejorará enormemente.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¡Una característica de la que dependo no está! / Algo ha cambiado y no me gusta. / Encontré un bug, ¿Cuál es la mejor manera de reportarlo?
```suggestion
#### ¡Una característica de la que dependo no está! / Algo ha cambiado y no me gusta. / Encontré un bug, ¿cuál es la mejor manera de reportarlo?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Por favor, ten en cuenta que ya estamos rastreando más de 1.000 problemas de diversas prioridades y puede que nos tome algo de tiempo arreglar problemas que solo afectan a un pequeño número de usuari
```suggestion
Por favor, ten en cuenta que ya estamos rastreando más de 1000 problemas de diversas prioridades y puede que nos tome algo de tiempo arreglar problemas que solo afectan a un pequeño número de usuarios.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Por qué se llama "lazer"?
```suggestion
#### ¿Por qué se llama «lazer»?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +¿Qué es más filoso que un filo cortante[^filo]?
```suggestion
¿Qué es más afilado que un filo cortante?[^filo]
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Por qué está tomando tanto tiempo para que se convierta en el lanzamiento "principal"?
```suggestion
#### ¿Por qué está tomando tanto tiempo para que se convierta en la versión «principal»?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Otra área que ha tomando una ingente cantidad de esfuerzo es la preservación histórica — asegurándose de que los beatmaps se comporten exactamente igual a como deberían, incluyendo casos extremos que
```suggestion
Otra área que ha requerido un gran esfuerzo es la conservación histórica — asegurándose de que los beatmaps se comporten exactamente igual a como deberían, incluyendo casos extremos que no fueron planeados originalmente. osu! es un ecosistema vibrante y los usuarios se han tomado la libertad de extender el juego más allá de su alcance planeado y estamos dando lo mejor para abarcar y soportar esto a medida que avanzamos.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Finalmente, a diferencia de la última iteración, estamos dedicando tiempo y diligencia para asegurar que el código base nos servirá bien en el futuro. Hemos hecho el trabajo de preparación para facil
```suggestion
Finalmente, a diferencia de la última iteración, estamos dedicando tiempo y diligencia para asegurar que el código base nos servirá bien en el futuro. Hemos hecho el trabajo de preparación para facilitar la conexión de nuevas características a velocidad vertiginosa mientras se avanza. ¡Esto incluirá nuevos componentes de IU, nuevas maneras de personalizar la apariencia del juego, nuevos sistemas multijugador y no olvidemos la capacidad de cargar y jugar todos tus beatmaps existentes en modos de juego completamente nuevos (también conocidos como rulesets)! 
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +¡No hay carpeta de canciones en lazer! Esto nos permite hacer cosas geniales como no requerir de presionar `F5` en la pantalla de elección de canción para actualizar los beatmaps (porqué los beatmaps
```suggestion
¡No hay carpeta de canciones en lazer! Esto nos permite hacer cosas geniales como no requerir de presionar `F5` en la pantalla del selector de canciones para actualizar los beatmaps (porque los beatmaps siempre están en buen estado) y reduce el espacio en disco usado por beatmaps en un 20 y 40 %. Puedes leer más sobre [la manera en la que lazer almacena archivos](/wiki/Client/Release_stream/Lazer/File_storage).
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Ahora que "osu!direct" está disponible para todos los jugadores, ¿Tendrán algún nuevo beneficio los supporters?
```suggestion
#### Ahora que «osu!direct» está disponible para todos los jugadores, ¿los supporters tendrán algún nuevo beneficio?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Pretendemos buscar nuevos beneficios en el futuro, pero nuestro enfoque está actualmente en la paridad de características con stable así que por favor, usa la compra de tu etiqueta de supporter como
```suggestion
Pretendemos buscar nuevos beneficios en el futuro, pero nuestro enfoque está actualmente en la paridad de características con stable así que por favor, usa la compra de tu etiqueta de supporter como una manera de... ¡apoyar el desarrollo del juego!
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Si hago trampa en lazer seré baneado?
```suggestion
#### ¿Si hago trampa en lazer me banearán?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Si encuentro a alguien haciendo trampa en lazer cómo debería reportarlo?
```suggestion
#### Si encuentro a alguien haciendo trampa en lazer, ¿cómo debería reportarlo?
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^hold-for-hud]: Manten presionado `Ctrl` para ver el HUD momentáneamente cuando esté oculto.
```suggestion
[^hold-for-hud]: Mantén presionado `Ctrl` para ver el HUD momentáneamente cuando esté oculto.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^offset-calibration-stable]: Ajustable manualmente mediante fijaciones de teclas.
```suggestion
[^offset-calibration-stable]: Ajustable manualmente mediante las teclas asignadas.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^offset-calibration-lazer]: Al reintentar un mapa, puedes calibrar la compensación basándote en tu última jugada.
```suggestion
[^offset-calibration-lazer]: Al reintentar un beatmap, puedes calibrar la compensación basándote en tu última jugada.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^score-reset-balance]: Las puntuaciones serán reseteadas para garantizar balance.
```suggestion
[^score-reset-balance]: Las puntuaciones serán restablecidas para garantizar balance. 
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^score-reset-isolated]: Las puntuaciones serán reseteadas, actualmente se encuentran aisladas de las puntuaciones de stable.
```suggestion
[^score-reset-isolated]: Las puntuaciones serán restablecidas, actualmente se encuentran aisladas de las puntuaciones de stable.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^editor-precise-rotation]: Rotación de angulo preciso faltante.
```suggestion
[^editor-precise-rotation]: Rotación de ángulo preciso faltante.
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^queue-modes]: Actívalos para permitir a cualquiera en la sala solicitar nuevos beatmaps, también conocidos como "rotación de host".
```suggestion
[^queue-modes]: Actívalos para permitir a cualquiera en la sala solicitar nuevos beatmaps, también conocido como «host rotate».
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| "Bloqueo de nota" amigable con el jugador | ![No][false] | ![Sí][true][^note-lock] |
```suggestion
| «Note lock» amigable con el jugador | ![No][false] | ![Sí][true][^note-lock] |
```

2023-12-30 02:50 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^difficulty-adjust]: Cambia el CS/AR/OD/HP de un beatmap directamente desde la pantalla de elección de canción mediante el mod Difficulty Adjust.
```suggestion
[^difficulty-adjust]: Cambia el CS/AR/OD/HP de un beatmap directamente desde la pantalla del selector de canciones mediante el mod Difficulty Adjust.
```

2023-12-30 09:39 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +¿Qué es más afilado que un filo cortante?[^filo]
```suggestion
¿Qué es más afilado que un filo?[^filo]
```

2023-12-30 09:39 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^filo]: Este es un juego de palabras en inglés con el nombre de la versión experimental del cliente stable, `cutting edge`.
```suggestion
Filo es la traducción de [cutting edge](/wiki/Client/Release_stream).
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Lazer sondea para una entrada de 1000 Hz sin importar el limitador de FPS, razón por la cual la configuración máxima del limitador también se limita a 1000 FPS.
```suggestion
Lazer sondea la entrada a 1000 Hz sin importar el limitador de FPS, razón por la cual la configuración máxima del limitador también se limita a 1000 FPS.
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Si tienes curiosidad acerca de como esto afecta la latencia de entrada y quieres probar tu propia percepción, por favor ejecuta el «certificador de latencia» integrado al final de las configuraciones
```suggestion
Si tienes curiosidad acerca de como esto afecta la latencia de entrada y quieres probar tu propia percepción, por favor ejecuta el «certificador de latencia» integrado al final de la configuración.
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### Si la entrada está sondeada a solo 1000 Hz, ¿qué hay acerca de mi ratón gaming de 8000 Hz?
```suggestion
#### Si la entrada solo se sondea a 1000 Hz, ¿qué pasa con mi ratón gaming de 8000 Hz?
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +El sistema operativo todavía sondeará a una tasa más alta, aunque los beneficios han probado ser insignificantes. Sondear a tales altas tazas puede tener desgastes imprevistos y recomendamos limitar
```suggestion
El sistema operativo seguirá sondeando a la tasa más alta, aunque se ha demostrado que los beneficios son insignificantes. Sondear a tasas tan altas puede tener desgastes imprevistos y recomendamos limitar los dispositivos a 1000 Hz para la estabilidad del sistema.
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +### Proporcionando retroalimentación
```suggestion
### Proporcionar retroalimentación
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Otra área que ha requerido un gran esfuerzo es la conservación histórica — asegurándose de que los beatmaps se comporten exactamente igual a como deberían, incluyendo casos extremos que no fueron pla
```suggestion
Otra área que ha requerido un gran esfuerzo es la conservación histórica; asegurándose de que los beatmaps se comporten exactamente igual a como deberían, incluyendo casos extremos que no fueron planeados originalmente. osu! es un ecosistema vibrante y los usuarios se han tomado la libertad de extender el juego más allá de su alcance planeado y estamos dando lo mejor para abarcar y soportar esto a medida que avanzamos.
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Tenemos una enorme reserva de características y mejoras solicitadas por usuarios que continuaremos agregando a la velocidad de la luz. Para aquellos que se han unido a nosotros recientemente y no han
```suggestion
Tenemos una enorme reserva de características y mejoras solicitadas por usuarios que continuaremos agregando a la velocidad de la luz. Para aquellos que se han unido a nosotros recientemente y no han experimentado el momentum del desarrollo de osu!, preparaos para recibir una sorpresa.
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +¡No hay carpeta de canciones en lazer! Esto nos permite hacer cosas geniales como no requerir de presionar `F5` en la pantalla del selector de canciones para actualizar los beatmaps (porque los beatm
```suggestion
¡No hay carpeta de canciones en lazer! Esto nos permite hacer cosas geniales como no requerir de presionar `F5` en la pantalla del selector de canciones para actualizar los beatmaps (porque los beatmaps siempre están en buen estado) y reduce el espacio en disco usado por beatmaps en un 20 y 40 %. Puedes leer más sobre [la manera en la que lazer almacena archivos](/wiki/Client/Release_stream/Lazer/File_storage).
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Algunos filtros en el listado de mapas siguen siendo solo para supporters.
```suggestion
Algunos filtros en el listado de beatmaps siguen siendo solo para supporters.
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^incompatibilities]: Algunas características del editor causarán que el beatmap se reproduzca de manera incorrecta en stable — será arreglado pronto.
```suggestion
[^incompatibilities]: Algunas características del editor causarán que el beatmap se reproduzca de manera incorrecta en stable; será arreglado pronto.
```

2023-12-30 10:16 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^queue-modes]: Actívalos para permitir a cualquiera en la sala solicitar nuevos beatmaps, también conocido como «host rotate».
```suggestion
[^queue-modes]: Actívalos para permitir a cualquiera en la sala solicitar nuevos beatmaps, también conocido como «rotación del anfitrión».
```

2023-12-30 10:46 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +¿Qué es más filoso que un filo cortante[^filo]?
eso es muy inglés de tu parte

2023-12-30 15:11 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +# Actualizando a lazer
```suggestion
# Actualizar a lazer
```

2023-12-30 15:38 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +### Notas
```suggestion
## Notas
```

2023-12-30 16:40 UTC, Ladwick commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Tenemos una enorme reserva de características y mejoras solicitadas por usuarios que continuaremos agregando a la velocidad de la luz. Para aquellos que se han unido a nosotros recientemente y no han
No entiendo muy bien la razón de esta sugerencia, ¿Hay algún sentido ortográfico detrás del cambio más allá de la localización?

2023-12-30 17:25 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Serpenteo de sliders al arrastrar | ![No][false] | ![Sí][true][^can-disable] |
dejalo como yo lo he dicho por favor

2023-12-30 17:26 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Listas de juego (tablas de clasificación curadas por los usuarios) | ![No][false] | ![Sí][true] |
de hecho había puesto esto antes de editarlo

2023-12-30 18:52 UTC, UnknownOsu requested changes

2023-12-30 18:52 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Mantener presionado para HUD | ![No][false] | ![Sí][true][^hold-for-hud] |
```suggestion
| Mantener presionado para ver el HUD | ![No][false] | ![Sí][true][^hold-for-hud] |
```

2023-12-30 18:52 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Comentarios de la repetición en desplazamiento estilo [Niconico](https://es.wikipedia.org/wiki/Niconico) | ![Sí][true] | ![No][false] |
```suggestion
| Comentarios de las repeticiones en desplazamiento estilo [Niconico](https://es.wikipedia.org/wiki/Niconico) | ![Sí][true] | ![No][false] |
```

2023-12-30 18:52 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Características | stable | lazer |
```suggestion
| Característica | stable | lazer |
```

2023-12-30 18:52 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Sobre cierto límite no hay motivo para usar tasas de refresco mayores. Lazer emplea varias tecnologías nuevas para asegurar que una menor latencia sea posible sin requerir altas tazas de refresco. Es
```suggestion
Sobre cierto límite no hay motivo para usar tasas de refresco mayores. Lazer emplea varias tecnologías nuevas para asegurar que una menor latencia sea posible sin requerir altas tazas de refresco. Esto continuará mejorando en el futuro, ya que nos quedan algunas mejoras por implementar.
```

2023-12-30 19:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Cambios de configuración inmediatos durante el juego | ![No][false] | ![Sí][true] |
los dos sirven

2023-12-30 19:27 UTC, Ladwick commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Tenemos una enorme reserva de características y mejoras solicitadas por usuarios que continuaremos agregando a la velocidad de la luz. Para aquellos que se han unido a nosotros recientemente y no han
```suggestion
Tenemos una enorme reserva de características y mejoras solicitadas por usuarios que continuaremos agregando a la velocidad de la luz. Para aquellos que se han unido a nosotros recientemente y no han experimentado el momentum del desarrollo de osu!, estén preparados para recibir una sorpresa.
```

2023-12-30 19:29 UTC, Ladwick commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Cambios de configuración inmediatos durante el juego | ![No][false] | ![Sí][true] |
Lo cambié principalmente para variar un poco porqué la palabra juego se usa 24 veces en el artículo.

2023-12-30 19:36 UTC, Ladwick commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^filo]: Es la traducción de [cutting edge](/wiki/Client/Release_stream).
```suggestion
[^filo]: «Filo» es una de las traducciones de [cutting edge](/wiki/Client/Release_stream), este es el resultado de un juego de palabras del artículo original.
```

2023-12-30 19:44 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Tenemos una enorme reserva de características y mejoras solicitadas por usuarios que continuaremos agregando a la velocidad de la luz. Para aquellos que se han unido a nosotros recientemente y no han
```suggestion
Tenemos una enorme reserva de características y mejoras solicitadas por usuarios que continuaremos agregando a la velocidad de la luz. Para aquellos que se han unido a nosotros recientemente y no han experimentado el momentum del desarrollo de osu!, estad preparados para recibir una sorpresa.
```

2024-01-04 11:47 UTC, agatemosu commented
do not merge master

2024-01-04 11:53 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Soporte móvil | ![No][false] | ![Sí][true] |
```suggestion
| Soporte para moviles | ![No][false] | ![Sí][true] |
```

2024-01-04 11:53 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Soporte de skins | ![Sí][true] | ![Parcial][partial][^gameplay-only] |
```suggestion
| Soporte para skins | ![Sí][true] | ![Parcial][partial][^gameplay-only] |
```

2024-01-04 11:53 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| «Serpenteado» de sliders al arrastrar | ![No][false] | ![Sí][true][^can-disable] |
```suggestion
| «Serpenteo» de sliders al arrastrar | ![No][false] | ![Sí][true][^can-disable] |
```

2024-01-04 11:58 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^soft-deletion]: Restaura beatmaps y otros datos desde las configuraciones. Las eliminaciones solo se vuelven permanentes al reiniciar.
```suggestion
[^soft-deletion]: Restaura beatmaps y otros datos desde la configuración. Las eliminaciones solo se vuelven permanentes al reiniciar.
```

2024-01-04 11:59 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^difficulty-adjust]: Cambia el CS/AR/OD/HP de un beatmap directamente desde la pantalla del selector de canciones mediante el mod Difficulty Adjust.
```suggestion
[^difficulty-adjust]: Cambia el CS/AR/OD/HP de un beatmap directamente desde el selector de canciones con el mod Difficulty Adjust.
```

2024-01-04 12:00 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^can-disable]: Puede ser desactivado
```suggestion
[^can-disable]: Se puede desactivar.
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Actualmente, beatmaps, skins, puntuaciones, repeticiones y colecciones pueden ser importadas a lazer. Como nota, **las configuraciones no se pueden importar todavía** así que tendrás que establecerla
```suggestion
Actualmente, beatmaps, skins, puntuaciones, repeticiones y colecciones pueden ser importadas a lazer. Como nota, **las configuraciones todavía no se pueden importar** así que tendrás que establecerlas desde cero.
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^difficulty-adjust]: Cambia el CS/AR/OD/HP de un beatmap directamente desde la pantalla del selector de canciones mediante el mod Difficulty Adjust.
```suggestion
[^difficulty-adjust]: Cambia el CS/AR/OD/HP de un beatmap directamente en el selector de canciones mediante el mod Difficulty Adjust.
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^soft-deletion]: Restaura beatmaps y otros datos desde las configuraciones. Las eliminaciones solo se vuelven permanentes al reiniciar.
```suggestion
[^soft-deletion]: Restaura beatmaps y otros datos desde la configuración. Las eliminaciones solo se vuelven permanentes al reiniciar.
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +[^can-disable]: Puede ser desactivado
```suggestion
[^can-disable]: Se puede desactivar.
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| «Serpenteado» de sliders al arrastrar | ![No][false] | ![Sí][true][^can-disable] |
```suggestion
| «Serpenteo» de sliders al arrastrar | ![No][false] | ![Sí][true][^can-disable] |
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Soporte de skins | ![Sí][true] | ![Parcial][partial][^gameplay-only] |
```suggestion
| Soporte para skins | ![Sí][true] | ![Parcial][partial][^gameplay-only] |
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +| Soporte móvil | ![No][false] | ![Sí][true] |
```suggestion
| Soporte para moviles | ![No][false] | ![Sí][true] |
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Si tienes tanto lazer como stable en el mismo disco, los [enlaces duros](/wiki/Client/Release_stream/Lazer/File_storage#a-través-de-enlaces-duros) son usados para evitar ocupar espacio extra en disco
```suggestion
Si tienes tanto lazer como stable en el mismo disco, se usarán [enlaces duros](/wiki/Client/Release_stream/Lazer/File_storage#a-través-de-enlaces-duros) para evitar ocupar espacio extra en disco.
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Si instalo lazer seré capaz de volver a stable?
```suggestion
#### Si instalo lazer, ¿seré capaz de volver a stable?
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Si borro lazer se dañará mi instalación de stable?
```suggestion
#### Si borro lazer, ¿se dañará mi instalación de stable?
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Si borro stable se dañará el contenido en lazer que fue importado desde stable?
```suggestion
#### Si borro stable, ¿se dañará el contenido en lazer que fue importado desde stable?
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +#### ¿Si hago trampa en lazer me banearán?
```suggestion
#### Si hago trampa en lazer, ¿me banearán?
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Por favor, intenta aplicar el mod «Classic», el cual restaura mucho del viejo comportamiento al que estás acostumbrado. También asegúrate de comprobar las configuraciones ofrecidas por el mod Classic
```suggestion
Por favor, intenta aplicar el mod «Classic», el cual restaura mucho del viejo comportamiento al que estás acostumbrado. También asegúrate de comprobar las configuraciones ofrecidas por el mod Classic, ya que te permitirá personalizar tu experiencia más allá y también te permitirá entender qué cambios están siendo aplicados (ya que están enumerados ahí).
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Otra área que ha requerido un gran esfuerzo es la conservación histórica; asegurándose de que los beatmaps se comporten exactamente igual a como deberían, incluyendo casos extremos que no fueron plan
```suggestion
Otra área que ha requerido un gran esfuerzo es la conservación histórica; asegurándonos de que los beatmaps se comporten exactamente igual a cómo deberían, incluyendo casos extremos que no fueron planeados originalmente. osu! es un ecosistema vibrante y los usuarios se han tomado la libertad de extender el juego más allá de su alcance planeado y estamos dando lo mejor para abarcar y soportar esto a medida que avanzamos.
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +¡No hay carpeta de canciones en lazer! Esto nos permite hacer cosas geniales como no requerir de presionar `F5` en la pantalla del selector de canciones para actualizar los beatmaps (porque los beatm
```suggestion
¡No hay carpeta de canciones en lazer! Esto nos permite hacer cosas geniales como no requerir de presionar `F5` en la pantalla del selector de canciones para actualizar los beatmaps (porque los beatmaps siempre están en buen estado) y reduce el espacio en disco usado por beatmaps en un 20-40 %. Puedes leer más sobre [la manera en la que lazer almacena archivos](/wiki/Client/Release_stream/Lazer/File_storage).
```

2024-01-04 12:18 UTC, agatemosu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Pretendemos buscar nuevos beneficios en el futuro, pero nuestro enfoque está actualmente en la paridad de características con stable así que por favor, usa la compra de tu etiqueta de supporter como
```suggestion
Pretendemos buscar nuevos beneficios en el futuro, pero nuestro enfoque está actualmente en la paridad de características con stable así que, por favor, usa la compra de tu etiqueta de supporter como una manera de... ¡apoyar el desarrollo del juego!
```

2024-01-05 15:17 UTC, agatemosu approved these changes

2024-01-05 21:35 UTC, UnknownOsu requested changes

2024-01-05 21:35 UTC, UnknownOsu commented on wiki/Help_centre/Upgrading_to_lazer/es.md
> +Mientras que intentamos preservar la mayor cantidad de puntuaciones posibles, **no ofrecemos garantía de que las puntuaciones permaneceran indefinidamente**. En cualquier momento podemos optar por bo
```suggestion
Mientras que intentamos preservar la mayor cantidad de puntuaciones posibles, **no ofrecemos garantía de que las puntuaciones permanecerán indefinidamente**. En cualquier momento podemos optar por borrar un subconjunto o todas las puntuaciones para preservar el balance del juego.
```

2024-01-05 23:53 UTC, UnknownOsu approved these changes

2024-01-06 10:10 UTC, agatemosu approved these changes

2024-01-13 00:06 UTC, TicClick approved these changes

2024-01-13 00:08 UTC, merged