[ES] Add `Gameplay differences in osu!(lazer)`
ppy/osu-wiki pull request #10779
Opened 2024-01-13 01:36 UTC by Ladwick

**Article translation** – `Diferencias de jugabilidad en osu!(lazer)`

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-01-13 05:11 UTC, UnknownOsu requested changes

2024-01-13 05:11 UTC, UnknownOsu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +Algunos beatmaps con velocidades de slider trucadas como teletransportaciones o detenimientos no se ven como deberían, pero son jugables.
```suggestion
Algunos beatmaps con trucos de SV, como teletransportes o detenimientos, no tienen el aspecto deseado, pero son jugables.
```

2024-01-13 05:11 UTC, UnknownOsu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +### La ventana de tiempo para juicios PERFECTOS escala con el OD
```suggestion
### La ventana de tiempo para los juicios PERFECT escala con el OD
```

2024-01-13 05:11 UTC, UnknownOsu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +En stable, beatmaps convertidos desde el modo de juego osu! en osu!mania tenían una [ventana de tiempo diferente](/wiki/Gameplay/Judgement/osu!mania).
```suggestion
En stable, los beatmaps convertidos desde el modo de juego osu! a osu!mania tenían una [ventana de tiempo diferente](/wiki/Gameplay/Judgement/osu!mania).
```

2024-01-13 06:21 UTC, Ladwick commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +En lugar de un límite de velocidad, los spinners ahora tienen un límite de puntuación determinado por la cantidad total de rotaciones que pueden ser logradas al girar el spinner a ciertas RPM dependi
Consideré bastante si dejarlo así, ¿pero RPM no se refería a Revoluciones Por Minuto?
```suggestion
En lugar de un límite de velocidad, los spinners ahora tienen un límite de puntuación determinado por la cantidad total de rotaciones que se pueden conseguir haciendo girar todo el spinner a una cantidad determinada de RPM dependiendo del OD.
```

2024-01-13 06:21 UTC, Ladwick commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +La cantidad de RPM requerida para obtener la máxima puntuación se muestra a continuación:
¿Igual que con la anterior? Aunque esto esta incluye una corrección para mí mismo también.
```suggestion
La cantidad de RPM requeridas para obtener la máxima puntuación se muestra a continuación:
```

2024-01-18 19:15 UTC, agatemosu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +| C | ≥60% | ≥85% | ≥70% |
```suggestion
| Grado | osu! / osu!taiko | osu!catch | osu!mania |
| :-: | :-- | :-- | :-- |
| SS | 100 % | 100 % | 100 % |
| S | ≥90 % (≤1% MEH/50, sin fallos) | ≥98 % | ≥95 % |
| A | ≥80 % (sin fallos) o ≥90 % | ≥94 % | ≥90 % |
| B | ≥70 % (sin fallos) o ≥80 % | ≥90 % | ≥80 % |
| C | ≥60 % | ≥85 % | ≥70 % |
```

2024-01-18 19:15 UTC, agatemosu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +| C | ≥70% | ≥85% |
```suggestion
| Grado | osu! / osu!taiko / osu!mania | osu!catch |
| :-: | :-- | :-- |
| SS | 100 % | 100 % |
| S | ≥95 % | ≥98 % |
| A | ≥90 % | ≥94 % |
| B | ≥80 % | ≥90 % |
| C | ≥70 % | ≥85 % |
```

2024-01-25 10:53 UTC, agatemosu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +### Todos los modos de juego a excepción de osu!catch usan el mismo sistema de grados
```suggestion
### Todos los modos de juego, a excepción de osu!catch, usan el mismo sistema de grados
```

2024-01-25 10:53 UTC, agatemosu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +Cuando se asesta un golpe justo en el límite de la ventana de tiempo, se puede recibir un juicio diferente dependiendo de la versión del cliente.
```suggestion
Cuando un golpe aterriza justo en el límite de la ventana de tiempo, se puede recibir un juicio diferente dependiendo de la versión del cliente.
```

2024-01-25 10:55 UTC, agatemosu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +Hay dos modos de visualización para las puntuaciones: *estandarizado* y *clásico*. El sistema estandarizado limita la puntuación a un máximo de 1000000 de puntos + bonificación y multiplicadores de p
```suggestion
Hay dos modos de visualización para las puntuaciones: *estandarizado* y *clásico*. El sistema estandarizado limita la puntuación a un máximo de 1 000 000 de puntos + bonificación y multiplicadores de puntuación (similar a ScoreV2), mientras que el sistema clásico es lo mismo que el estandarizado, pero escalado cuadráticamente con la cantidad de objetos en un beatmap (similar a ScoreV1). Estos pueden ser seleccionados desde las configuraciones, todos los lugares en el juego donde se muestra puntuación cambian correspondientemente.
```

2024-01-25 10:57 UTC, agatemosu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +En lazer, no golpear un slider head dará un juicio de MISS para el slider completo. Luego de fallar un slider head; combo, puntuación y precisión todavía pueden ser obtenidos de las marcas de los sli
```suggestion
En lazer, no golpear un slider head dará un juicio de MISS para el slider completo. Luego de fallar un slider head; el combo, la puntuación y la precisión todavía pueden ser obtenidos de las marcas de los sliders, sliders inversos y slider ends.
```

2024-01-26 12:01 UTC, agatemosu commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/es.md
> +En lazer, no golpear un slider head dará un juicio de MISS para el slider completo. Luego de fallar un slider head; el combo, la puntuación y la precisión todavía pueden ser obtenidos de las marcas d
```suggestion
En lazer, no golpear un slider head dará un juicio de MISS para el slider completo. Después de fallar un slider head, todavía se puede obtener combo, puntuación y precisión de las marcas de los sliders, sliders inversos y slider ends.
```

2024-01-27 07:17 UTC, agatemosu approved these changes

2024-01-29 12:27 UTC, TicClick approved these changes

2024-01-29 13:52 UTC, merged