[ZH] Update `Ranking criteria` and sub articles
ppy/osu-wiki pull request #10785
Opened 2024-01-13 16:23 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-01-15 00:37 UTC, CloneWith requested changes
wiki/Ranking_criteria/zh.md 更新一下 96 行的链接

2024-01-15 01:15 UTC, CloneWith approved these changes

2024-01-19 11:42 UTC, CloneWith approved these changes

2024-01-26 11:16 UTC, TicClick commented
> Apply changes in https://github.com/ppy/osu-wiki/pull/10815

I think that PR shouldn't block yours, which would be the case with pishifat's intention to wait until all four game modes are covered in simple terms

2024-01-26 11:19 UTC, TicClick approved these changes

2024-01-26 11:20 UTC, merged