[ES] Add `osu!catch Ranking Criteria`
ppy/osu-wiki pull request #10790
Opened 2024-01-14 15:46 UTC by O1CDeif

Article translation - `Criterios de clasificación de osu!catch`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-01-14 19:00 UTC, UnknownOsu requested changes

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **La tasa de marcas de slider (slider tick rate) debe establecerse según la canción.** Por ejemplo, si tu canción solo utiliza un ritmo ternario 1/3, no encajaría el usar una tasa de marcas de 2 o
```suggestion
- **La tasa de marcas del slider debe establecerse según la canción.** Por ejemplo, si tu canción solo usa un ritmo de 1/3, usar una tasa de marcas de 2 o 4 no sería adecuado.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Usa la misma tasa de marcas de slider (slider tick rate) en todas las dificultades,** ya que es una propiedad de la música y no del beatmap. Sin embargo, las dificultades bajas pueden usar tasas
```suggestion
- **Usa la misma tasa de marcas del slider en todas las dificultades,** ya que es una propiedad de la música y no del mapping. Sin embargo, las dificultades bajas pueden usar tasas de marcas menores para reducir los requisitos de precisión para los jugadores nuevos, teniendo en cuenta que se sigue el ritmo de la canción. No tiene sentido usar una tasa de marcas del slider para solamente incrementar la puntuación, el combo, o el nivel de dificultad.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Evita usar [colores de combo](/wiki/Beatmapping/Combo_colour) con una luminosidad de ~220 o mayor si se usa un tiempo de Kiai.** Los colores luminosos crean pulsaciones brillantes en los tiempos
```suggestion
- **Evita usar [colores de combo](/wiki/Beatmapping/Combo_colour) con una luminosidad de ~220 o mayor si se usa un Kiai time.** Los colores luminosos crean pulsaciones brillantes en los Kiai time, lo cual puede ser incómodo para la vista.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los objetos personalizados tienen que incluir todos los elementos necesarios y estar coloreados en una escala de grises.** Esto es para asegurar que tus imágenes estén definidas claramente y con
```suggestion
- **Los objetos personalizados tienen que incluir todos los elementos necesarios y estar coloreados en una escala de grises.** Esto es para asegurar que tus imágenes estén definidas claramente y con una calidad aceptable. Los elementos necesarios pueden ser encontrados en [Skinning/osu!catch](/wiki/Skinning/osu!catch). Además, es recomendable usar elementos transparentes para las superposiciones.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los elementos del skin tienen que tener el mismo tamaño que los elementos correspondientes del skin por defecto.** Esto es para representar el área de impacto (hitbox) apropiadamente y no alterar
```suggestion
- **Los elementos de la skin tienen que tener el mismo tamaño que los elementos correspondientes de la skin por defecto.** Esto es para representar el área de impacto apropiadamente y no alterar la dificultad. Las dimensiones usadas en la skin por defecto son 128x128 píxeles para las [frutas](/wiki/Gameplay/Hit_object/Fruit), 82x103 para las [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) y 306x320 para el catcher.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los catchers personalizados deberían también incluir el elemento `lighting.png` para completar el conjunto del skin.** Este elemento es opcional y tiene por defecto dimensiones de 184x184 píxeles
```suggestion
- **Los catchers personalizados deberían también incluir el elemento `lighting.png` para completar el conjunto de la skin.** Este elemento es opcional y tiene por defecto dimensiones de 184x184 píxeles, aunque puede variar dependiendo de la visibilidad deseada de este elemento.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +Las reglas y pautas para las dificultades específicas solo aplican al nivel que está estipulado y por ende *no aplica a **todas** las dificultades de osu!catch*. Reglas y pautas relacionadas al ritmo
```suggestion
Las reglas y pautas para las dificultades específicas solo aplican al nivel de dificultad que se indica y, por lo tanto, *no se  aplican a **todas** las dificultades de osu!catch*. Reglas y pautas relacionadas al ritmo aplican para beatmaps de aproximadamente 180 BPM. Si tu canción es drásticamente más rápida o lenta, algunas variables pueden ser diferentes, como se detalla en [Escalado de BPM en los criterios de clasificación](/wiki/Ranking_criteria/Scaling_BPM).
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Debe haber al menos 250 ms de espacio entre círculos/sliders y el inicio y final de [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```suggestion
- **Debe haber al menos 250 ms de espacio entre círculos/sliders y el inicio y final de los [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 8 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 8 objetos, incluyendo los finales y repetidores de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Velocidad de Aproximación ([Approach Rate](/wiki/Beatmap/Approach_rate)) / Dificultad General ([Overall Difficulty](/wiki/Beatmap/Overall_difficulty)) deberían ser entre 4 y 6.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían ser entre 4 y 6.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Tasa de Drenaje de HP ([HP Drain Rate](/wiki/Beatmap/HP_drain_rate)) debería ser entre 2 y 3.
```suggestion
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería ser entre 2 y 3.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Velocidad de Aproximación ([Approach Rate](/wiki/Beatmap/Approach_rate)) / Dificultad General ([Overall Difficulty](/wiki/Beatmap/Overall_difficulty)) deberían ser entre 6 y 7.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían ser entre 6 y 7.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Tasa de Drenaje de HP ([HP Drain Rate](/wiki/Beatmap/HP_drain_rate)) debería ser entre 3 y 4.
```suggestion
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería ser entre 3 y 4.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El Tamaño del Círculo ([Circle Size](/wiki/Beatmap/Circle_size)) debería ser entre 2.5 y 3.5.
```suggestion
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 2,5 y 3,5.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no pueden usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#drop) individuales y/o repeticiones de sliders.** La precisión y control requeridos
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no pueden usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) individuales y/o sliders repetidos.** La precisión y control requeridos son poco razonables en este nivel y pueden crear una situación donde el jugador potencialmente no pueda leer la trayectoria del slider.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [edge dashes](/wiki/Gameplay/Edge_dash) no deben ser utilizados.** Requieren una sincronización extremadamente precisa que no se puede esperar de jugadores menos experimentados.
```suggestion
- **Los [edge dashes](/wiki/Gameplay/Edge_dash) no deben ser usados.** Requieren una sincronización extremadamente precisa que no se puede esperar de jugadores menos experimentados.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Debe haber al menos 125 ms de espacio entre círculos/sliders y el inicio de [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```suggestion
- **Debe haber al menos 125 ms de espacio entre círculos/sliders y el inicio de los [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Debe haber al menos 250 ms de espacio entre círculos/sliders y el final de [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```suggestion
- **Debe haber al menos 250 ms de espacio entre círculos/sliders y el final de los [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **No se deben usar [hyperdashes](/wiki/Gameplay/Hyperdash) fuertes.** Para hyperdashes de [snap básico](/wiki/Gameplay/Dash_snapping#basic-snapped) se recomienda un límite de 1.5 veces la [distanci
```suggestion
- **No se deben usar [hyperdashes](/wiki/Gameplay/Hyperdash) fuertes.** Para hyperdashes de [snap básico](/wiki/Gameplay/Dash_snapping#basic-snapped) se recomienda un límite de 1,5 veces la [distancia de activación](/wiki/Beatmapping/Trigger_distance). En cambio, para hyperdashes de [snap alto](/wiki/Gameplay/Dash_snapping#higher-snapped), se recomienda un límite de 1,3 veces la distancia de activación.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap básico](/wiki/Gameplay/Dash_snapping#basic-snapped) pueden usarse junto con patrones de [antiflujo](/wiki/Beatmapping/Mapping_techniques/Antif
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap básico](/wiki/Gameplay/Dash_snapping#basic-snapped) pueden usarse junto con patrones de [antiflow](/wiki/Beatmapping/Mapping_techniques/Antiflow).** Si se usan, el espacio no debe exceder una distancia ajustada de 1,2 veces la [distancia de activación](/wiki/Beatmapping/Trigger_distance) cuando sea seguido por un [walk](/wiki/Gameplay/Walk), o 1,1 veces la distancia de activación cuando sea seguido por un [dash](/wiki/Gameplay/Dash) de snap básico.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap alto](/wiki/Gameplay/Dash_snapping#higher-snapped) no deben ir seguidos de patrones de [antiflujo](/wiki/Beatmapping/Mapping_techniques/Antifl
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap alto](/wiki/Gameplay/Dash_snapping#higher-snapped) no deben ir seguidos de patrones de [antiflow](/wiki/Beatmapping/Mapping_techniques/Antiflow).** Si se usan, el espacio no debe exceder una distancia ajustada de 1,1 veces la [distancia de activación](/wiki/Beatmapping/Trigger_distance).
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **No se deben usar [trampas de spinner](/wiki/Gameplay/Spinner_trap).**
```suggestion
- **No se deben usar [spinner traps](/wiki/Gameplay/Spinner_trap).**
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 12 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 12 objetos, incluyendo los finales y repetidores de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Velocidad de Aproximación ([Approach Rate](/wiki/Beatmap/Approach_rate)) / Dificultad General ([Overall Difficulty](/wiki/Beatmap/Overall_difficulty)) deberían ser entre 7 y 8.2.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían ser entre 7 y 8,2.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Tasa de Drenaje de HP ([HP Drain Rate](/wiki/Beatmap/HP_drain_rate)) debería ser entre 4 y 5.
```suggestion
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería ser entre 4 y 5.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El Tamaño del Círculo ([Circle Size](/wiki/Beatmap/Circle_size)) debería ser entre 3 y 4.
```suggestion
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 3 y 4.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Debe haber al menos 125 ms de espacio entre círculos/sliders y el inicio y final de [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```suggestion
- **Debe haber al menos 125 ms de espacio entre círculos/sliders y el inicio y final de los [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#drop) y/o repeticiones de sliders.**
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) y/o sliders repetidos.**
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap básico](/wiki/Gameplay/Dash_snapping#basic-snapped) no deben usarse consecutivamente cuando se utilizan ritmos diferentes.** Por ejemplo, un h
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap básico](/wiki/Gameplay/Dash_snapping#basic-snapped) no deben usarse consecutivamente cuando se usan ritmos diferentes.** Por ejemplo, un hyperdash de 1/1 seguido de un hyperdash de 1/2.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap alto](/wiki/Gameplay/Dash_snapping#higher-snapped) no deben usarse junto con [dashes](/wiki/Gameplay/Dash) de snap alto.** Si se usan, estos n
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap alto](/wiki/Gameplay/Dash_snapping#higher-snapped) no deben usarse junto con [dashes](/wiki/Gameplay/Dash) de snap alto.** Si se usan, estos no pueden involucrar [antiflow](/wiki/Beatmapping/Mapping_techniques/Antiflow) y el dash debe usarse antes del hyperdash.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap alto](/wiki/Gameplay/Dash_snapping#higher-snapped) no deben ir seguidos de [dashes](/wiki/Gameplay/Dash) [antiflujo](/wiki/Beatmapping/Mapping
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) de [snap alto](/wiki/Gameplay/Dash_snapping#higher-snapped) no deben ir seguidos de [dashes](/wiki/Gameplay/Dash) [antiflow](/wiki/Beatmapping/Mapping_techniques/Antiflow) con un espacio inferior a 250 ms.**
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **No se deben usar [trampas de spinner](/wiki/Gameplay/Spinner_trap).**
```suggestion
- **No se deben usar [spinner traps](/wiki/Gameplay/Spinner_trap).**
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y repetidores de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Velocidad de Aproximación ([Approach Rate](/wiki/Beatmap/Approach_rate)) / Dificultad General ([Overall Difficulty](/wiki/Beatmap/Overall_difficulty)) deberían ser entre 7 y 9.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían ser entre 7 y 9.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Tasa de Drenaje de HP ([HP Drain Rate](/wiki/Beatmap/HP_drain_rate)) debería ser entre 5 y 6.
```suggestion
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería ser entre 5 y 6.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El Tamaño del Círculo ([Circle Size](/wiki/Beatmap/Circle_size)) debería ser entre 3.5 y 4.5.
```suggestion
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 3,5 y 4,5.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Debe haber al menos 62 ms de espacio entre círculos/sliders y el inicio de [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```suggestion
- **Debe haber al menos 62 ms de espacio entre círculos/sliders y el inicio de los [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Debe haber al menos 125 ms de espacio entre círculos/sliders y el final de [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```suggestion
- **Debe haber al menos 125 ms de espacio entre círculos/sliders y el final de los [spinners](/wiki/Gameplay/Hit_object/Spinner).** Esto es para garantizar una buena legibilidad.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) solo deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#drop) y/o repeticiones de sliders cuando la trayectoria del slider sea simple y fác
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) solo deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) y/o sliders repetidos cuando la trayectoria del slider sea simple y fácil de seguir.** Esto es para evitar movimientos caóticos o irrazonablemente difíciles de hacer un dash, ya que la transición dentro y fuera de formas complejas de sliders con hyperdash suele ser incómoda para jugar, y conlleva a una penalización significativa en la precisión por poco beneficio.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y repetidores de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Velocidad de Aproximación ([Approach Rate](/wiki/Beatmap/Approach_rate)) / Dificultad General ([Overall Difficulty](/wiki/Beatmap/Overall_difficulty)) deberían ser entre 8 y 10.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían ser entre 8 y 10.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- La Tasa de Drenaje de HP ([HP Drain Rate](/wiki/Beatmap/HP_drain_rate)) debería ser entre 5 y 7.
```suggestion
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería ser entre 5 y 7.
```

2024-01-14 19:00 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El Tamaño del Círculo ([Circle Size](/wiki/Beatmap/Circle_size)) debería ser entre 3 y 6.
```suggestion
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 3 y 6.
```

2024-01-14 20:25 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +***Aviso: Este artículo es una extensión de los [criterios generales de clasificación](/wiki/Ranking_criteria).***
```suggestion
***Aviso: Este artículo es una extensión de los [criterios de clasificación generales](/wiki/Ranking_criteria).***
```

2024-01-14 20:30 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Asegúrate de que los [combos](/wiki/Beatmapping/Combo) no sean extremadamente largos.** Las [frutas](/wiki/Gameplay/Hit_object/Fruit) capturadas se apilarán en el plato y pueden obstruir la vista
repeticiones de slider tiene más sentido, no son más de uno

2024-01-14 20:33 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) solo deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#drop) y/o repeticiones de sliders cuando la trayectoria del slider sea simple y fác
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) solo deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) y/o repeticiones de sliders cuando la trayectoria del slider sea simple y fácil de seguir.** Esto es para evitar movimientos caóticos o irrazonablemente difíciles de hacer un dash, ya que la transición dentro y fuera de formas complejas de sliders con hyperdash suele ser incómoda para jugar, y conlleva a una penalización significativa en la precisión por poco beneficio.
```

2024-01-14 20:33 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#drop) y/o repeticiones de sliders.**
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no deben usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#drop) y/o repeticiones de **sliders.**
```

2024-01-14 20:34 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no pueden usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#drop) individuales y/o repeticiones de sliders.** La precisión y control requeridos
```suggestion
- **Los [hyperdashes](/wiki/Gameplay/Hyperdash) no pueden usarse en [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) individuales y/o repeticiones de sliders.** La precisión y control requeridos son poco razonables en este nivel y pueden crear una situación donde el jugador potencialmente no pueda leer la trayectoria del slider.
```

2024-01-14 20:35 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **No utilices keysounds sin el soporte de sonidos hitnormal.** Si los sonidos se mezclan perfectamente con la canción, el feedback recibido por capturar notas es mínimo.
```suggestion
- **No uses keysounds sin el soporte de sonidos hitnormal.** Si los sonidos se mezclan perfectamente con la canción, la retroalimentación al capturar las notas es mínima.
```

2024-01-14 20:36 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Tu beatmap debe ser teóricamente posible de obtener una SS.** Esto significa que debe ser posible capturar absolutamente todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gamepla
```suggestion
- **Tu beatmap debe ser teóricamente posible de obtener una SS.** Esto significa que debe ser posible capturar absolutamente todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) y [gotitas](/wiki/Gameplay/Hit_object/Juice_stream#gotita)
```

2024-01-14 21:09 UTC, O1CDeif commented
Both reviews have been applied + tackled some things manually that just fixed partially some of the suggestions

2024-01-14 21:09 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Intenta incluir al menos un [spinner](/wiki/Gameplay/Hit_object/Spinner) en cada dificultad para crear variedad en el beatmap y fluctuación entre las puntuaciones obtenidas.** Sin embargo, si un
@O1CDeif aplica esto, en la versión en inglés pone "map"

2024-01-14 21:13 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +Las reglas y pautas para las dificultades específicas solo aplican al nivel que está estipulado y por ende *no aplica a **todas** las dificultades de osu!catch*. Reglas y pautas relacionadas al ritmo
"aplica" en plural, falta coma después de "ende"; me gusta más la opción sugerida

2024-01-14 22:01 UTC, UnknownOsu requested changes

2024-01-14 22:04 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **[La Dificultad General](/wiki/Beatmap/Overall_difficulty) debería tener el mismo valor que la [velocidad de aproximación](/wiki/Beatmap/Approach_rate).** Este es un valor estandarizado, ya que la
```suggestion
La **[dificultad general](/wiki/Beatmap/Overall_difficulty) debería tener el mismo valor que la [velocidad de aproximación](/wiki/Beatmap/Approach_rate).** Este es un valor estandarizado, ya que la dificultad general no afecta a la jugabilidad ni a la cantidad de [frutas](/wiki/Gameplay/Hit_object/Fruit) que tiene un [spinner](/wiki/Gameplay/Hit_object/Spinner). La dificultad general solo afecta a la puntuación máxima de una dificultad.
```

2024-01-15 11:19 UTC, O1CDeif commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Asegúrate de que los [combos](/wiki/Beatmapping/Combo) no sean extremadamente largos.** Las [frutas](/wiki/Gameplay/Hit_object/Fruit) atrapadas se apilarán en el plato y pueden obstruir la vista
Los plátanos como término no tiene mucho uso entre mappers, solamente si se asocian con spinners. El resto lo cambié.

2024-01-15 21:10 UTC, UnknownOsu requested changes

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Tu beatmap debe ser teóricamente posible de obtener una SS.** Esto significa que debe ser posible atrapar absolutamente todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gameplay
```suggestion
- **Debe ser teóricamente posible obtener una SS en tu beatmap.** Esto significa que debe ser posible atrapar absolutamente todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota) y [gotitas](/wiki/Gameplay/Hit_object/Juice_stream#gotita).
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **No uses keysounds sin el soporte de sonidos hitnormal.** Si los sonidos se mezclan perfectamente con la canción, la retroalimentación al atrapar las notas es mínima.
```suggestion
- **No uses keysounds sin el soporte de un hitnormal.** Si los sonidos se mezclan perfectamente con la canción, la retroalimentación al atrapar las notas es mínima.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +  - **...entre 3:15 y 4:00**, la dificultad más baja no puede ser más difícil que una Rain.
```suggestion
  - **... menos de 2:30**, la dificultad más baja no puede ser más difícil que una Salad.
  - **... entre 2:30 y 3:15**, la dificultad más baja no puede ser más difícil que una Platter.
  - **... entre 3:15 y 4:00**, la dificultad más baja no puede ser más difícil que una Rain.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +  - **Los [descansos](/wiki/Beatmap/Break) pueden ser combinados con el [tiempo de drenaje](/wiki/Beatmap/Drain_time) para alcanzar los umbrales mencionados anteriormente.** Para la dificultad más al
```suggestion
  - **Se puede combinar los [descansos](/wiki/Beatmap/Break) con el [tiempo de drenaje](/wiki/Beatmap/Drain_time) para alcanzar los umbrales mencionados anteriormente.** Para la dificultad más alta, esto está limitado a 30 segundos de descanso como máximo. Esto no se aplica a dificultades con menos de 30 segundos de tiempo de drenaje.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar 1/4, 1/8 y 1/16. Si la canción usa
```suggestion
- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se debe usar 1/4, 1/8 y 1/16. Si la canción usa un ritmo swing/ternario, se debe usar 1/6 o 1/12. Si la canción tiene un sonido en un ajuste diferente al recomendado, el ajuste a un ritmo adecuado siempre tiene prioridad.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Asegúrate de que los [combos](/wiki/Beatmapping/Combo) no sean extremadamente largos.** Las [frutas](/wiki/Gameplay/Hit_object/Fruit) atrapadas se apilarán en el plato y pueden obstruir la vista
```suggestion
- **Asegúrate de que los [combos](/wiki/Beatmapping/Combo) no sean extremadamente largos.** Las [frutas](/wiki/Gameplay/Hit_object/Fruit) atrapadas se apilarán en el plato y pueden obstruir la vista del jugador. Ten en cuenta que los finales y las repeticiones de slider, así como los [plátanos](/wiki/Gameplay/Hit_object/Banana) del [spinner](/wiki/Gameplay/Hit_object/Spinner) también cuentan como «frutas». Los combos nuevos deben ser puestos regularmente para vaciar el plato y evitar esto.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Intenta incluir al menos un [spinner](/wiki/Gameplay/Hit_object/Spinner) en cada dificultad para crear variedad en el beatmap y fluctuación entre las puntuaciones obtenidas.** Sin embargo, si un
```suggestion
- **Intenta incluir al menos un [spinner](/wiki/Gameplay/Hit_object/Spinner) en cada dificultad para crear variedad en el mapa y fluctuación entre las puntuaciones obtenidas.** Sin embargo, si un spinner no encaja en ninguna parte de la canción, no es necesario forzar su uso.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **[Dashes](/wiki/Gameplay/Dash) e [hyperdashes](/wiki/Gameplay/Hyperdash) de cualquier tipo no están permitidos.** Esto es para garantizar una experiencia de inicio fácil para los jugadores princip
```suggestion
- **[Dashes](/wiki/Gameplay/Dash) e [hyperdashes](/wiki/Gameplay/Hyperdash) de cualquier tipo no están permitidos.** Esto es para garantizar una experiencia de inicio fácil para los jugadores principiantes. Con el fin de probar esto, debe ser posible alcanzar un grado SS en la dificultad sin hacer uso de la tecla de dash.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 8 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 8 objetos, incluyendo los finales y las repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **La densidad de las notas debe seguir principalmente un patrón 1/1.** Los patrones 1/2 y/o 1/3 deben usarse con moderación.
```suggestion
- **La densidad de las notas debe seguir principalmente un patrón de 1/1.** Los patrones de 1/2 y/o 1/3 deben usarse con moderación.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 10 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 10 objetos, incluyendo los finales y las repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 12 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 12 objetos, incluyendo los finales y las repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y las repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```suggestion
- **Los [combos](/wiki/Beatmapping/Combo) no deben exceder los 16 objetos, incluyendo los finales y las repeticiones de los sliders.** Los [spinners](/wiki/Gameplay/Hit_object/Spinner) son una excepción.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los [edge dashes](/wiki/Gameplay/Edge_dash) pueden usarse con precaución para un máximo de tres objetos consecutivos y no deben usarse después de [hyperdashes](/wiki/Gameplay/Hyperdash).**
```suggestion
- **Los [edge dashes](/wiki/Gameplay/Edge_dash) pueden usarse con precaución para un máximo de tres objetos consecutivos, y no deben usarse después de [hyperdashes](/wiki/Gameplay/Hyperdash).**
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 2 y 3.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían estar entre 4 y 6.
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería estar entre 2 y 3.
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería estar entre 2 y 3.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 2,5 y 3,5.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían estar entre 6 y 7.
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería estar entre 3 y 4.
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería estar entre 2,5 y 3,5.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 3 y 4.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían estar entre 7 y 8,2.
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería estar entre 4 y 5.
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería estar entre 3 y 4.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 3,5 y 4,5.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían estar entre 7 y 9.
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería estar entre 5 y 6.
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería estar entre 3,5 y 4,5.
```

2024-01-16 19:29 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 3 y 6.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían estar entre 8 y 10.
- La [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería estar entre 5 y 7.
- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería estar entre 3 y 6.
```

2024-01-16 22:39 UTC, O1CDeif commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar 1/4, 1/8 y 1/16. Si la canción usa
Tiene más sentido en plural, ya que se refiere a los diferentes tipos de snaps. En singular suena raro.

2024-01-16 22:48 UTC, O1CDeif commented on wiki/Ranking_criteria/osu!catch/es.md
> +- El [tamaño del círculo](/wiki/Beatmap/Circle_size) debería ser entre 2 y 3.
Ser encaja algo mejor que estar en este contexto, ya que son valores estáticos. El RC de osu!mania también utiliza el verbo ser refiriéndose al mismo tema.

2024-01-19 19:49 UTC, UnknownOsu requested changes

2024-01-19 19:49 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar 1/4, 1/8 y 1/16. Si la canción usa
```suggestion
- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar snaps de 1/4, 1/8 y 1/16. Si la canción usa un ritmo swing/ternario, se deben usar snaps de 1/6 o 1/12. Si la canción tiene un sonido en un ajuste diferente al recomendado, el ajuste a un ritmo adecuado siempre tendrá prioridad.
```

2024-01-19 19:49 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar 1/4, 1/8 y 1/16. Si la canción usa
Creo que queda mejor así. Ya que dices que se refiere a los snaps, no vendría mal mencionarlos y que no quede al aire por decir `se deben usar 1/4...`. Aunque si lees el artículo es porque ya debes estar un poco familiarizado con el editor, pero creo que no está de más hacer saber al lector que se refiere a estos

2024-01-19 20:03 UTC, O1CDeif commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar 1/4, 1/8 y 1/16. Si la canción usa
+1

2024-01-19 20:23 UTC, UnknownOsu commented
Pues, para mí, ya está. Te diría que le pidas una revisión a agatem, puede que a ella no le parezca algo y quiera sugerir otra cosa

2024-01-19 20:49 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar snaps de 1/4, 1/8 y 1/16. Si la can
unknown actualizó el mensaje, aunque en lugar de compás sería divisor creo yo
y no sé si lo del beat es correcto, lo puso Antalf en el rc de mania, 
```suggestion
- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la estructura de la canción usa una métrica derecha, se deben usar divisores de 1/4, 1/8 y 1/16. Si la canción usa la métrica de swing, se deben usar divisores de 1/6 o 1/12. Si la canción tiene un sonido en un ajuste diferente al recomendado, el ajuste a un pulso real siempre tendrá prioridad.
```

2024-01-19 20:57 UTC, O1CDeif commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar snaps de 1/4, 1/8 y 1/16. Si la can
* Métrica derecha no es un término musical. La frase como está ahora se entiende mejor.
* `Snap` es más correcto en este contexto. Aunque es un anglicismo, es un término bastante aceptado por los modders/mappers de habla hispana.
* La última frase con el término `pulso real` no tiene mucho sentido.

2024-01-24 19:35 UTC, agatemosu commented on wiki/Ranking_criteria/osu!catch/es.md
> +- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un ritmo básico/cuaternario, se deben usar snaps de 1/4, 1/8 y 1/16. Si la can
```suggestion
- **Los finales de sliders extendidos deben sincronizarse según la estructura rítmica de la canción.** Si la canción usa un [compás cuaternario](https://es.wikipedia.org/wiki/Compás_(música)#Compases_cuaternarios), se deben usar snaps de 1/4, 1/8 y 1/16. Si la canción usa un [compás ternario](https://es.wikipedia.org/wiki/Compás_(música)#Compases_ternarios), se deben usar snaps de 1/6 o 1/12. Si la canción tiene un sonido en un ajuste diferente al recomendado, el ajuste a un ritmo adecuado siempre tendrá prioridad.
```

2024-01-24 21:43 UTC, agatemosu approved these changes

2024-01-25 10:02 UTC, TicClick approved these changes

2024-01-25 10:03 UTC, merged