[RO] Add `Beatmapping` and `Installation and registration`
ppy/osu-wiki pull request #10806
Opened 2024-01-17 16:24 UTC by 28edx

Translation for the `Beatmapping` and `Installation and registration` articles

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-01-26 11:32 UTC, NiceAesth requested changes

2024-01-26 11:32 UTC, NiceAesth commented on wiki/Help_centre/Beatmapping/ro.md
> +Fiecare utilizator are un număr limitat de beatmap-uri pe care le poate încărca simultan. Lăsarea unui beatmap inactiv timp de o lună (28 de zile), prin neactualizarea ei, o va trimite în [Beatmap-ur
```suggestion
Fiecare utilizator are un număr limitat de beatmap-uri pe care le poate încărca simultan. Lăsarea unui beatmap inactiv timp de o lună (28 de zile), prin neactualizarea lui, îl va trimite în [Beatmap-uri inactive](/wiki/Beatmap/Category#graveyard). Pentru a readuce un beatmap din inactivitate înapoi în statusul de În așteptare sau În lucru, actualizează-l.
```

2024-01-26 11:32 UTC, NiceAesth commented on wiki/Help_centre/Beatmapping/ro.md
> +Dacă nu este, modifică manual asta pentru fiecare dificultate a beatmap-ului tău, reîncarcă beatmap-ul și ar trebui să o poți încărca.
```suggestion
Dacă nu este, modifică manual asta pentru fiecare dificultate a beatmap-ului tău, după care reîncarcă beatmap-ul și ar trebui să funcționeze.
```

2024-01-26 11:32 UTC, NiceAesth commented on wiki/Help_centre/Beatmapping/ro.md
> +Dacă încă întâmpini probleme sau vrei mai multe informații despre asta, citește [pagina de probleme BSS](/wiki/Guides/BSS_issues).
```suggestion
Dacă încă întâmpini alte probleme sau dorești mai multe informații, citește [pagina de probleme BSS](/wiki/Guides/BSS_issues).
```

2024-01-26 11:32 UTC, NiceAesth commented on wiki/Help_centre/Beatmapping/ro.md
> +## Beatmap-ul/conținutul meu a fost reîncărcat de către alt utilizator fără consințământul meu, și vreau ca copia să fie dată jos! {id=report-content-dmca}
```suggestion
## Beatmap-ul/conținutul meu a fost reîncărcat de către alt utilizator fără consințământul meu și doresc să fie dată jos copia! {id=report-content-dmca}
```

2024-01-26 11:32 UTC, NiceAesth commented on wiki/Help_centre/Beatmapping/ro.md
> +Orice fel de conținut încărcat fără permisiune poate fi considerat ca o încălcare a drepturilor de autor dacă proprietarul original dorește asta. Solicitarea eliminării necesită o procedură legală pe
```suggestion
Orice fel de conținut încărcat fără permisiune poate fi considerat o încălcare a drepturilor de autor dacă proprietarul original dorește asta. Solicitarea eliminării necesită o procedură legală pentru a asigura o procedură corectă.
```

2024-01-26 11:32 UTC, NiceAesth commented on wiki/Help_centre/Beatmapping/ro.md
> +Te rugăm să **nu** depui o reclamare folosind fie [comanda din joc `!report`](/wiki/Reporting_bad_behaviour#in-game-chat) sau [site-ul osu!](/wiki/Reporting_bad_behaviour#website), deoarece membrii [
```suggestion
Te rugăm să **nu** depui o reclamare folosind fie [comanda din joc `!report`](/wiki/Reporting_bad_behaviour#in-game-chat) sau [site-ul osu!](/wiki/Reporting_bad_behaviour#website), deoarece membrii [NAT](/wiki/People/Nomination_Assessment_Team) și [GMT](/wiki/People/Global_Moderation_Team) care gestionează aceste sesizări nu sunt în măsură să se ocupe de probleme juridice.
```

2024-01-26 11:32 UTC, NiceAesth commented
Suggestions can be applied wholesale

2024-01-27 19:01 UTC, NiceAesth approved these changes

2024-01-29 12:05 UTC, TicClick approved these changes

2024-01-29 12:07 UTC, merged