[FR] Update `Tournaments/Official support`
ppy/osu-wiki pull request #10818
Opened 2024-01-19 09:54 UTC by DoryanR

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) > **No contributor**

2024-01-21 16:14 UTC, Ganondorf-1 requested changes

2024-01-21 16:14 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
>  - [Des récompenses sous forme de badges de profil](#badges-de-profil) pour les gagnants de la première place.
```suggestion
- [Des récompenses sous forme de badges de profil](#badges-de-profil) pour les vainqueurs du tournoi.
```

2024-01-21 16:14 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
>  - La prise en compte potentielle d'une [bannière publicitaire dans le menu principal](#demande-de-soutien-pour-les-bannières-en-jeu-et-les-messages-d'information) lors des grands matchs.
```suggestion
- La possibilité d'envisager une [bannière publicitaire dans le menu principal](#demande-de-soutien-pour-les-bannières-en-jeu-et-les-messages-d'information) lors des grands matchs.
```

2024-01-21 16:14 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +- Possibilité d'envisager un [post de news](#demande-de-soutien-pour-les-bannières-en-jeu-et-les-messages-d'information), un message annonçant les inscriptions et un autre résumant les résultats fina
```suggestion
- Possibilité d'envisager un [article de news](#demande-de-soutien-pour-les-bannières-en-jeu-et-les-messages-d'information), un message annonçant les inscriptions et un autre résumant les résultats finaux.
```

2024-01-21 16:14 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Une liste de tous les membres du personnel du tournoi doit être publiquement visible dans un endroit facilement accessible. Cette liste peut être contenue dans un message du forum, sur le site web ou
```suggestion
Une liste de tous les membres du staff du tournoi doit être publiquement visible dans un endroit facilement accessible. Cette liste peut être contenue dans un message du forum, sur le site web ou dans une feuille de calcul.
```

2024-01-25 10:27 UTC, TicClick approved these changes

2024-01-25 10:29 UTC, merged