[FR] Update `Game mode/osu!mania` and `osu!`
ppy/osu-wiki pull request #10819
Opened 2024-01-19 09:54 UTC by DoryanR

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) > **No contributor**

2024-01-21 15:45 UTC, Ganondorf-1 requested changes

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +![terrain de jeu d'osu!mania](/wiki/shared/Mania_playfield.jpg "terrain de jeu d'osu!mania")
```suggestion
![Écran de jeu d'osu!mania](/wiki/shared/Mania_playfield.jpg "Écran de jeu d'osu!mania")
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Par défaut, le flux des notes va du haut vers le bas du tapis (la flèche de départ indique où les notes vont s'écouler), avec le contrôle des touches en bas et la ligne de jugement au-dessus du contr
```suggestion
Par défaut, le flux des notes va du haut vers le bas de l'écran (la flèche de départ indique où les notes vont s'écouler), avec le contrôle des touches en bas et la ligne de jugement au-dessus du contrôle des touches. Pour changer le flux du terrain de jeu de bas en haut, il peut être modifié dans la barre latérale `Options` ; cliquez sur le bouton `Paramètres osu!mania` pour régler les paramètres des touches osu!mania et activez manuellement `Défilement de bas en haut (à la DDR)`.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +La barre de santé est située à droite du tapis. Veuillez noter que le health drain est désactivé dans osu!mania, donc seuls les objets affecteront la barre de santé. Le combo ne se brisera pas si vou
```suggestion
La barre de santé est située à droite de la scène. Veuillez noter que le drain de santé passif est désactivé dans osu!mania, donc seuls les objets affecteront la barre de santé. Le combo ne se brisera pas si vous appuyez sur les touches d'une ligne de jugement vide.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +**La vitesse de défilement des beats** peut être modifiée en appuyant sur `Ctrl` (ou `Shift`) avec `+` (plus rapide) / `-` (plus lent) ou simplement `F3` (plus rapide) / `F4` (plus lent).
```suggestion
**La vitesse de défilement des notes** peut être modifiée en appuyant sur `Ctrl` (ou `Shift`) avec `+` (plus rapide) / `-` (plus lent) ou simplement `F3` (plus rapide) / `F4` (plus lent).
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Une note est attribuée lorsque l'on tape une touche correcte correspondant à la note de la ligne de jugement.
```suggestion
Une note est attribuée lorsque l'on appuie sur la touche correspondant à la note de la ligne de jugement.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Les hold notes sont les sliders et les spinners d'osu!mania. Lorsque la hold note atteint la ligne de jugement, tapez la note de départ en rythme avec la touche correcte, maintenez-la et relâchez-la
```suggestion
Les hold notes sont les sliders et les spinners d'osu!mania. Lorsqu'une hold note atteint la ligne de jugement, appuyez sur en rythme la touche correspondant à la note, maintenez-la, puis relâchez-la à la fin de la hold note.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +![Section du clavier des options](/wiki/shared/Options_keyboard.jpg "Options Icône de saisie, section Clavier")
```suggestion
![Icône Contrôles dans les options, section Clavier](/wiki/shared/Options_keyboard.jpg "Icône Contrôles dans les options, section Clavier")
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Il y avait auparavant deux styles de fixation différents, *Symétrique* et *Gauche à droite* :
```suggestion
Il y avait auparavant deux styles de paramétrage des touches différents, *Symétrique* et *Gauche à droite* :
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- Le style *Symétrique* imite le placement des boutons de *DJMAX*, dans lequel la touche centrale est `Espace` pour simuler la sensation d'appuyer sur la pédale comme dans la version arcade. La touch
```suggestion
- Le style *Symétrique* imite le placement des boutons de *DJMAX*, dans lequel la touche centrale est `Espace` pour simuler la sensation d'appuyer sur la pédale comme dans la version arcade. La touche centrale correspond à la colonne du milieu (nombre de touches impairs uniquement) et l'autre colonne correspond aux touches à son emplacement correspondant.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +  - Cependant, l'option de choix a été supprimée et le style actuel est basé sur le style "Symétrique". Pour des raisons d'héritage, le style "De gauche à droite" est conservé ici.
```suggestion
  - Cependant, l'option de choix a été supprimée et le style actuel est basé sur le style "Symétrique". Pour des raisons de préservation, le style "De gauche à droite" est conservé ici.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Attribution de touches *Symétrique* (pour le style *DJMAX*)
```suggestion
Attribution des touches *Symétrique* (pour le style *DJMAX*)
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- De bas en haut, puis de bas en haut à nouveau : (K1)`Z`, (K2)`S`, (K3)`X`, (K4)`D`, (K5)`C`, (K6)`F`, (K7)`V`, (K8)`G`, (K9)`B` \[K9 is not used\]
```suggestion
- De bas en haut, puis de bas en haut à nouveau : (K1)`Z`, (K2)`S`, (K3)`X`, (K4)`D`, (K5)`C`, (K6)`F`, (K7)`V`, (K8)`G`, (K9)`B` \[K9 n'est pas utilisée\]
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +| Key | Attribution |
```suggestion
| Nombre de touches | Attribution |
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +La **[Mise à jour du 05 mars 2015 (05/03/2015)](https://osu.ppy.sh/home/changelog)** a donné à osu!mania un nouveau mod appelé [Co-Op](/wiki/Gameplay/Game_modifier/Co-op). Avec ce mod activé, un deux
```suggestion
La **[Mise à jour du 5 mars 2015 (05/03/2015)](https://osu.ppy.sh/home/changelog)** a donné à osu!mania un nouveau mod appelé [Co-Op](/wiki/Gameplay/Game_modifier/Co-op). Avec ce mod activé, un deuxième ensemble de touches différent sera donné en même temps que l'ensemble de touches principal comme ci-dessus.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +**Le tableau ci-dessous est basé sur le mod xK utilisé en conjonction avec le modding Co-Op.**
```suggestion
**Le tableau ci-dessous est basé sur le mod xK utilisé en conjonction avec le mod Co-Op.**
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +| Key | PL | PC | PR | SL | SC | SR |
```suggestion
| Nombre de touches | PL | PC | PR | SL | SC | SR |
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +1. Le score de base, qui est centré sur le [jugement](/wiki/Gameplay/Judgement/osu!mania). Le jugement détermine le score de base d'un objet (MAX, 300, 200, 100, 50, ou 0 en cas de miss).
```suggestion
1. Le score de base, qui est centré sur le [jugement](/wiki/Gameplay/Judgement/osu!mania). Le jugement détermine le score de base d'un objet (MAX, 300, 200, 100, 50, ou 0 en cas de note manquée).
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +2. Le score du bonus, qui est basé sur le jugement et un multiplicateur de bonus flottant, qui augmente lorsque l'on obtient un MAX ou un 300, et diminue lorsque l'on obtient un 200 ou moins.
```suggestion
2. Le score bonus, qui est basé sur le jugement et un multiplicateur de bonus flottant, qui augmente lorsque l'on obtient un MAX ou un 300, et diminue lorsque l'on obtient un 200 ou moins.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- La [précision](/wiki/Gameplay/Accuracy#osu!mania) dépend du jugement et indique la précision des coups. Les appuis tardifs ou anticipés sur les touches, ainsi que les miss, diminuent la précision g
```suggestion
- La [précision](/wiki/Gameplay/Accuracy#osu!mania) dépend du jugement et indique la précision avec laquelle les notes ont été touchées. Appuyer trop tôt, trop tard, ou manquer des notes, diminueront la précision globale.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) indique combien d'objets ont été frappés à la suite. Il n'a aucun effet sur le score total et peut être [cassé](/wiki/Gameplay/Judgement/Combobre
```suggestion
- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) indique combien d'objets ont été touchés à la suite. Il n'a aucun effet sur le score total et peut être [brisé](/wiki/Gameplay/Judgement/Combobreak) par une note manquée.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- Si le nombre de touches est identique après l'utilisation du modificateur xK ou Co-Op, aucune réduction de score n'est accordée.
```suggestion
- Si le nombre de touches est identique après l'utilisation du modificateur xK ou Co-Op, le score ne subira pas de réduction.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +  - Respectivement, pour une beatmap de 5K, l'utilisation du modificateur 5K n'entraînera pas non plus de réduction de score.
```suggestion
  - Respectivement, pour une beatmap 5K, l'utilisation du modificateur 5K n'entraînera pas non plus de réduction de score.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- Lorsque le jeu est joué par [Auto](/wiki/Gameplay/Game_modifier/Auto), le nom du joueur sera *osu!topus*.
```suggestion
- Si le mod [Auto](/wiki/Gameplay/Game_modifier/Auto) est utilisé, le nom du joueur sera *osu!topus*.
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +![le logo d'osu!mania dans les modes spéciaux](img/Mania_logo.png "le logo d'osu!mania dans les modes spéciaux")
```suggestion
![Le logo d'osu!mania dans les modes spéciaux](img/Mania_logo.png "le logo d'osu!mania dans les modes spéciaux")
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- osu!mania a été publié le [08 octobre 2012 (08/10/2012), principalement mis en œuvre par woc2006](https://osu.ppy.sh/community/forums/posts/1825880).
```suggestion
- osu!mania a été publié le [8 octobre 2012 (08/10/2012), principalement mis en œuvre par woc2006](https://osu.ppy.sh/community/forums/posts/1825880).
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- La première beatmap réservée à osu!mania à être officiellement classée est [fripSide - only my railgun (TV Size) (DJPop)](https://osu.ppy.sh/beatmapsets/63089).
```suggestion
- La première beatmap spécifique à osu!mania à être officiellement classée est [fripSide - only my railgun (TV Size) (DJPop)](https://osu.ppy.sh/beatmapsets/63089).
```

2024-01-21 15:45 UTC, Ganondorf-1 commented on wiki/Ranking_criteria/osu!mania/fr.md
> +- **Colonne** : Couloirs verticaux du [terrain de jeu](/wiki/Game_mode/osu!mania#terrain-de-jeu) où les notes sont placées. Notez que les [timestamps de l'éditeur](/wiki/Modding/Timestamp) se réfèren
```suggestion
- **Colonne** : Couloirs verticaux de l'[écran de jeu](/wiki/Game_mode/osu!mania#écran-de-jeu) où les notes sont placées. Notez que les [timestamps de l'éditeur](/wiki/Modding/Timestamp) se réfèrent aux colonnes par leur position à l'index zéro en partant de la gauche.
```

2024-01-21 16:21 UTC, DoryanR commented on wiki/Beatmapping/osu!mania_10K_plus_playstyles/fr.md
> +Dans ce contexte, un **style de jeu** est un ensemble suggéré de [touches](/wiki/Game_mode/osu!mania#contrôles) et d'ordre des touches dans le [terrain de jeu](/wiki/Game_mode/osu!mania#terrain-de-je
```suggestion
Dans ce contexte, un **style de jeu** est un ensemble suggéré de [touches](/wiki/Game_mode/osu!mania#contrôles) et d'ordre des touches sur [l'écran de jeu](/wiki/Game_mode/osu!mania#écran-de-jeu). La plupart des beatmaps d'osu!mania avec plus de 10 touches sont mappées avec un style de jeu particulier à l'esprit - le joueur a moins de doigts qu'il n'y a de touches. Une attention particulière est alors nécessaire concernant l'endroit où les mains du joueur seront positionnées sur le [clavier](/wiki/Gameplay/Input_device/Keyboard) tout au long de la beatmap.
```

2024-01-21 16:21 UTC, DoryanR commented on wiki/Game_mode/osu!/fr.md
> +### Sélection de la musique
```suggestion
### Sélection de la beatmap
```

2024-01-21 16:26 UTC, DoryanR commented on wiki/Game_mode/osu!mania/fr.md
> +### Sélection de la musique
```suggestion
### Sélection de la beatmap
```

2024-01-21 16:26 UTC, DoryanR commented on wiki/Game_mode/osu!mania/fr.md
> +Dans l'écran de sélection de la musique, le nombre à côté de *K* indique le nombre de touches qui seront utilisées pour le jeu. La beatmap sera jouée avec un jugement plus souple si le symbole "↓" a
```suggestion
Sur l'écran de sélection de la beatmap, le nombre à côté de *K* indique le nombre de touches qui seront utilisées pour le jeu. La beatmap sera jouée avec un jugement plus souple si le symbole "↓" a été ajouté à la droite du *K*.
```

2024-01-21 16:31 UTC, DoryanR commented on wiki/Ranking_criteria/osu!mania/fr.md
> +- **Colonne** : Couloirs verticaux du [terrain de jeu](/wiki/Game_mode/osu!mania#terrain-de-jeu) où les notes sont placées. Notez que les [timestamps de l'éditeur](/wiki/Modding/Timestamp) se réfèren
```suggestion
- **Colonne** : Couloirs verticaux de [l'écran de jeu](/wiki/Game_mode/osu!mania#écran-de-jeu) où les notes sont placées. Notez que les [timestamps de l'éditeur](/wiki/Modding/Timestamp) se réfèrent aux colonnes par leur position à l'index zéro en partant de la gauche.
```

2024-01-25 10:30 UTC, TicClick approved these changes

2024-01-25 10:32 UTC, merged