[ES] Add `Organisations`
ppy/osu-wiki pull request #10826
Opened 2024-01-20 13:46 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-01-20 22:07 UTC, UnknownOsu requested changes

2024-01-20 22:07 UTC, UnknownOsu commented on wiki/Community/Organisations/es.md
> +- [osu! en UCSD](osu!_at_UCSD)
```suggestion
- [osu! at UCSD](osu!_at_UCSD)
```

2024-01-20 22:07 UTC, UnknownOsu commented on wiki/Community/Organisations/es.md
> +- [osu! en UCSD](osu!_at_UCSD)
Es un nombre propio, creo que es mejor dejarlo en su forma original

2024-01-20 22:16 UTC, agatemosu commented on wiki/Community/Organisations/es.md
> +- [osu! en UCSD](osu!_at_UCSD)
pero es un club de osu! en la universidad de california

2024-01-20 22:54 UTC, UnknownOsu commented on wiki/Community/Organisations/es.md
> +- [osu! en UCSD](osu!_at_UCSD)
Por eso, ese es el nombre del club, ¿no? Sería mejor dejarlo sin traducir ya que es el nombre de este

2024-01-21 11:04 UTC, agatemosu commented on wiki/Community/Organisations/es.md
> +- [osu! en UCSD](osu!_at_UCSD)
yo me imagino que el club se llamará "osu!"

2024-01-25 10:20 UTC, TicClick approved these changes

2024-01-25 10:21 UTC, merged