Improve 2007 history page
ppy/osu-wiki pull request #10840
Opened 2024-01-25 15:58 UTC by Tanza3D

For the first change: Judging by the fact that the song select has the "Play Level", it's easy to make the assumption that this is in fact the level select itself, and not just the edit level select. This is also proven by [this version on Osekai Snapshots](https://osekai.net/snapshots/?version=81)

For the second change: For the version shown in the image just above, the same selection carousel was used inside the edit menu, once again shown in [this version](https://osekai.net/snapshots/?version=185), and also judging by the fact that this UI was never used solely as the edit level select. This orange version was however used for a few days as the primary song select, still, so unsure about entirely removing it.

First actual PR on osu-wiki so hope I've done things right here :)

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-01-25 16:12 UTC, agatemosu reviewed
spanish and french can be changed to that

2024-01-25 16:12 UTC, agatemosu commented on wiki/History_of_osu!/2007/es.md
Selección de canciones

2024-01-25 16:12 UTC, agatemosu commented on wiki/History_of_osu!/2007/fr.md
Sélection de musiques

2024-01-25 23:33 UTC, cl8n commented
the orange one should probably not be deleted here, just moved if necessary and given a more accurate description

2024-02-19 17:53 UTC, JuanM4T requested changes
the other languages can also be swapped with those.

idk why Portuguese keeps the English but I've kept it in English for coherence's sake with the original.

2024-02-19 17:53 UTC, JuanM4T commented on wiki/History_of_osu!/2007/id.md
Pemilihan Lagu

2024-02-19 17:53 UTC, JuanM4T commented on wiki/History_of_osu!/2007/ru.md
Выбор песни

2024-02-19 17:53 UTC, JuanM4T commented on wiki/History_of_osu!/2007/pt-br.md
Song Selection

2024-02-19 17:53 UTC, JuanM4T commented on wiki/History_of_osu!/2007/nl.md
Muziekselectie

2025-03-17 11:17 UTC, TicClick approved these changes

2025-03-17 11:18 UTC, merged