Add `Mapper's Choice Awards / A Year In Mapping 2023` news post
ppy/osu-wiki pull request #10869
Opened 2024-01-31 22:54 UTC by Hiviexd

2024-01-31 23:16 UTC, Walavouchey commented on news/2024/2024-02-01-mappers-choice-awards-2023.md
> +date: 2023-02-01 00:00:00 +0000
```suggestion
date: 2024-02-01 00:00:00 +0000
```

2024-01-31 23:19 UTC, Hiviexd commented on news/2024/2024-02-01-mappers-choice-awards-2023.md
> +date: 2023-02-01 00:00:00 +0000
2nd time this year...

2024-01-31 23:25 UTC, Walavouchey requested changes
bold **mappers' choice awards** and **a year in mapping**

2024-01-31 23:25 UTC, Walavouchey commented on news/2024/2024-02-01-mappers-choice-awards-2023.md
> +Just like the previous editions of MCA, there are three stages: nomination, voting, and results. See below to know when the deadlines for nomination and voting are, and when to expect the final resul
```suggestion
Just like the previous editions of MCA, there are three stages: nomination, voting, and results. [See below](#schedule) to know when the deadlines for nomination and voting are, and when to expect the final results!
```

2024-01-31 23:25 UTC, Walavouchey commented on news/2024/2024-02-01-mappers-choice-awards-2023.md
> +- **Results:** Will be based off of the results of voting and feature a livestream announcing each podium of every category.
```suggestion
- **Results:** These will be based on the voting tallies and feature a livestream announcing the podium of each category.
```

2024-01-31 23:25 UTC, Walavouchey commented on news/2024/2024-02-01-mappers-choice-awards-2023.md
> +Per usual, A Year in Mapping features all the coolest statistics of the year all in [one place](https://ayim.corsace.io/2023/). Want to know who ranked the hardest or easiest map this year? Who ranke
a big link on one line would be better

2024-01-31 23:25 UTC, Walavouchey commented on news/2024/2024-02-01-mappers-choice-awards-2023.md
> +Now that you're all caught up on the schedule and the events, it's time to get to the important part: nominating and voting! Head on over to the [website](https://mca.corsace.io/2023/) to get started
here too

2024-02-01 00:01 UTC, Walavouchey approved these changes

2024-02-01 00:01 UTC, merged