[ES] `Add History of osu! 2022`
ppy/osu-wiki pull request #10897
Opened 2024-02-05 23:14 UTC by JuanM4T

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-02-05 23:26 UTC, Dariito0xx approved these changes
Everything looks fine

2024-02-06 02:31 UTC, UnknownOsu requested changes

2024-02-06 02:31 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +osu! superó los 4,294,967,296 puntajes, lo que significa que el antiguo sistema de base de datos ha alcanzado su límite. Cada puntuación se guarda con un entero sin signo de 32 bits único, lo que sig
```suggestion
osu! superó las 4 294 967 296 puntuaciones, lo que significa que el antiguo sistema de base de datos ha alcanzado su límite. Cada puntuación se guarda con un entero único sin signo de 32 bits, lo que significa que la base de datos no puede almacenar más de 2^32 puntuaciones. La infraestructura de la base de datos ampliada ya estaba planeada meses antes y se migró con unas semanas de antelación.[^score-limit][^osu-death][^score-submission] La última puntuación enviada en el antiguo sistema fue [\*namirin - Kanzen Shouri\*Esper Girl](https://osu.ppy.sh/scores/osu/4294967295) jugada por [ElDanetex](https://osu.ppy.sh/users/18930084).
```

2024-02-06 02:31 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +Las mentes creativas demostraron su talento en el concurso de skinning [Chromatic Alteration](https://osu.ppy.sh/home/news/2022-07-18-skinning-contest-chromatic-alteration-announcement). El desafío d
```suggestion
Las mentes creativas demostraron su talento en el concurso de skinning [Chromatic Alteration](https://osu.ppy.sh/home/news/2022-07-18-skinning-contest-chromatic-alteration-announcement). El desafío de este concurso tenía un giro interesante porque los tipos de colores debían ser de uno de los tres espectros de color especificados que corresponden a las deficiencias visuales [protanopia, deuteranopia y tritanopia](https://en.wikipedia.org/wiki/Color_blindness). [Los ganadores de este concurso](/wiki/Contests/Skinning_Contest/3#podium) que se llevaron el primer, segundo y tercer lugar fueron [thetasigma](https://osu.ppy.sh/users/6234482), [Corne2Plum3](https://osu.ppy.sh/users/15646039) y [koomo](https://osu.ppy.sh/users/2168518) respectivamente.[^chromatic-alt-results]
```

2024-02-06 02:31 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +Una actualización del sitio web de osu! permitió mostrar el rango más alto que un jugador ha alcanzado cuando se pasa el cursor sobre el rango de un jugador en su perfil.[^highest-rank]
```suggestion
Una actualización del sitio web de osu! permitió mostrar la clasificación más alta que un jugador ha alcanzado cuando se pasa el cursor sobre la clasificación de un jugador en su perfil.[^highest-rank]
```

2024-02-06 02:31 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +Otra skin incorporada se añadió a osu!(lazer) llamada "argon pro", una variante de la skin "argon" destinada a contener elementos de juego más minimalistas, comenzando con un nuevo conjunto de hitsou
```suggestion
Se agregó otra skin incorporada a osu!(lazer) llamada «argon pro», una variante de la skin «argon» destinada a contener elementos de juego más minimalistas, comenzando con un nuevo conjunto de hitsounds para el modo de juego osu!.[^argon-pro] Las skins con menos distracciones visuales suelen ser las preferidas por los top players.
```

2024-02-06 02:31 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +En el último concurso de arte del año, [New Beginnings](https://osu.ppy.sh/home/news/2022-11-27-new-beginnings-art-contest), los participantes tenían que dibujar a las mascotas de osu! dando la bienv
```suggestion
En el último concurso de arte del año, [New Beginnings](https://osu.ppy.sh/home/news/2022-11-27-new-beginnings-art-contest), los participantes tenían que dibujar a las mascotas de osu! dando la bienvenida al 2023 en la víspera de Año Nuevo. El ganador de este concurso fue [Dreamxiety](https://osu.ppy.sh/users/13103233) con 2203 votos.[^new-beginnings]
```

2024-02-06 10:14 UTC, JuanM4T commented on wiki/History_of_osu!/2022/es.md
> +Después de 5 años, [Reddit](https://www.reddit.com/) organizó por segunda vez el evento de April Fools r/place. Desde el 1 de abril hasta el 4 de abril, los usuarios podían colocar píxeles de colores
me preocupa un poco usar día de los Inocentes para nombrar el 1 de abril porque hace algo de overlap con el día de los Santos Inocentes el 28 de diciembre, pero 👍

2024-02-06 10:20 UTC, JuanM4T commented on wiki/History_of_osu!/2022/es.md
> +Desde la creación de osu!, hace 15 años, se ha cultivado una comunidad animada con muchos colaboradores voluntarios. A raíz de este evento, el equipo de osu! organizó un concurso de arte en celebraci
tuve una pequeña discusión con @Dariito0xx sobre esta línea. En español no es usual hablar de "desde <duración>", y, de hecho, no me suena haber visto una frase así nunca antes. Me parece que la frase queda algo dificil de entender de pasada. De cualquier manera, este cambio es una transliteración que a mí personalmente no me suena del todo bien pero es consistente con lo que hay en inglés, supongo.

2024-02-06 10:24 UTC, JuanM4T commented on wiki/History_of_osu!/2022/es.md
> +En el último concurso de arte del año, [New Beginnings](https://osu.ppy.sh/home/news/2022-11-27-new-beginnings-art-contest), los participantes tenían que dibujar a las mascotas de osu! dando la bienv
creo que queda mejor integrado Nochevieja, pues es una expresión más común pero también el cambio tiende a ser más neutral asi que 👍

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +Más artistas se unieron al programa de los [artistas destacados](/wiki/People/Featured_Artists) a principios de año, siendo estos: [NIWASHI](https://osu.ppy.sh/beatmaps/artists/228), [DGK](https://os
```suggestion
Más artistas se unieron al programa de los [artistas destacados](/wiki/People/Featured_Artists) a principios de año, siendo estos: [NIWASHI](https://osu.ppy.sh/beatmaps/artists/228), [DGK](https://osu.ppy.sh/beatmaps/artists/229), [Haywyre](https://osu.ppy.sh/beatmaps/artists/230), [satella](https://osu.ppy.sh/beatmaps/artists/231), [Vansire](https://osu.ppy.sh/beatmaps/artists/232), [Boom Kitty](https://osu.ppy.sh/beatmaps/artists/233), [Annabel](https://osu.ppy.sh/beatmaps/artists/234) y [Maduk](https://osu.ppy.sh/beatmaps/artists/235).
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
reunión comunitaria -> reunión con la comunidad

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
las fechas con este formato: dd/mm/aaaa

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^halloween]: [Publicación de noticias de Ephemeral (2022-10-29) «Resultados del concurso de fanart de Halloween 2022»](https://osu.ppy.sh/home/news/2022-10-29-halloween-fanart-results)
```suggestion
[^halloween]: [Publicación de noticias de Ephemeral (2022-10-29) «Halloween 2022 Fanart Contest Results»](https://osu.ppy.sh/home/news/2022-10-29-halloween-fanart-results)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^osu-mania-sr-pp]: [Publicación de noticias del comité de pp de osu!mania (2022-10-09) «Cambios en la calificación estelar y los puntos de rendimiento de osu!mania»](https://osu.ppy.sh/home/news/202
```suggestion
[^osu-mania-sr-pp]: [Publicación de noticias del comité de pp de osu!mania (2022-10-09) «Changes to osu!mania Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-10-09-changes-to-osu-mania-sr-and-pp)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^triangles-results]: [Publicación de noticias de pishifat (2022-10-06) «Resultados - triangles»](https://osu.ppy.sh/home/news/2022-10-06-results-triangles)
```suggestion
[^triangles-results]: [Publicación de noticias de pishifat (2022-10-06) «Results - triangles»](https://osu.ppy.sh/home/news/2022-10-06-results-triangles)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^medals-september]: [Publicación de noticias de 0x84f, Pisapou y RandomeLoL (2022-10-02) «osu!monthly, septiembre de 2022»](https://osu.ppy.sh/home/news/2022-10-02-osumonthly-3)
```suggestion
[^medals-september]: [Publicación de noticias de 0x84f, Pisapou y RandomeLoL (2022-10-02) «osu!monthly, September 2022»](https://osu.ppy.sh/home/news/2022-10-02-osumonthly-3)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^osu-taiko-sr-pp]: [Publicación de noticias del comité de pp de osu!taiko (2022-09-28) «Cambios en la calificación estelar y los puntos de rendimiento de osu!taiko»](https://osu.ppy.sh/home/news/202
```suggestion
[^osu-taiko-sr-pp]: [Publicación de noticias del comité de pp de osu!taiko (2022-09-28) «Changes to osu!taiko Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-09-28-changes-to-osu-taiko-sr-and-pp)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^osu-sr-pp]: [Publicación de noticias del comité de pp de osu! (2022-09-30) «Cambios en la calificación estelar y los puntos de rendimiento de osu!»](https://osu.ppy.sh/home/news/2022-09-30-changes-
```suggestion
[^osu-sr-pp]: [Publicación de noticias del comité de pp de osu! (2022-09-30) «Changes to osu! Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-09-30-changes-to-osu-sr-and-pp)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^15-anniversary-results]: [Publicación de noticias de Ephemeral (2022-09-15) «Resultados del concurso de arte del 15 aniversario»](https://osu.ppy.sh/home/news/2022-09-15-anniversary-art-contest-res
```suggestion
[^15-anniversary-results]: [Publicación de noticias de Ephemeral (2022-09-15) «15th Anniversary Art Contest Results»](https://osu.ppy.sh/home/news/2022-09-15-anniversary-art-contest-results)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^roundtable-winners]: [Publicación de noticias de Soetch, Blushing, Wowcake, 0x84f y Hubz (2022-08-01) «osu!monthly regresa, julio de 2022»](https://osu.ppy.sh/home/news/2022-08-01-osumonthly-1#what
```suggestion
[^monthly-quiz]: [Publicación de noticias de Soetch, Blushing, Wowcake, 0x84f y Hubz (2022-08-01) «osu!monthly returns, July 2022»](https://osu.ppy.sh/home/news/2022-08-01-osumonthly-1#monthly-community-quiz)
[^roundtable-winners]: [Publicación de noticias de Soetch, Blushing, Wowcake, 0x84f y Hubz (2022-08-01) «osu!monthly returns, July 2022»](https://osu.ppy.sh/home/news/2022-08-01-osumonthly-1#what's-new-in-osu!?)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^aptb-results]: [Publicación de noticias de Ephemeral (2022-05-08) «Resultados del concurso de fanart A Place To Belong»](https://osu.ppy.sh/home/news/2022-05-08-aptb-fanart-results)
```suggestion
[^aptb-results]: [Publicación de noticias de Ephemeral (2022-05-08) «A Place To Belong Fanart Contest Results»](https://osu.ppy.sh/home/news/2022-05-08-aptb-fanart-results)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^tides-of-winter]: [Publicación de noticias de RockRoller (2022-02-25) «Concurso de skinning: Tides of Winter - Resultados»](https://osu.ppy.sh/home/news/2022-02-25-skinning-contest-tides-of-winter-
```suggestion
[^tides-of-winter]: [Publicación de noticias de RockRoller (2022-02-25) «Skinning Contest: Tides of Winter - Results»](https://osu.ppy.sh/home/news/2022-02-25-skinning-contest-tides-of-winter-results)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^score-pin-reorder]: [Pull request de nanaya (2021-12-24) «Agregar soporte para reorganizar puntuaciones fijadas»](https://github.com/ppy/osu-web/pull/8468)
```suggestion
[^score-pin-reorder]: [Solicitud de cambos por nanaya (2021-12-24) «Add support to rearrange pinned scores»](https://github.com/ppy/osu-web/pull/8468)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^new-beginnings]: [Publicación de noticias de Ephemeral (2022-12-31) «Concurso de arte New Beginnings: Resultados»](https://osu.ppy.sh/home/news/2022-12-31-new-beginnings-results)
```suggestion
[^new-beginnings]: [Publicación de noticias de Ephemeral (2022-12-31) «New Beginnings Art Contest: Results»](https://osu.ppy.sh/home/news/2022-12-31-new-beginnings-results)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^makeship]: [Publicación de noticias del osu! team (2022-12-10) «Makeship x osu!: Peluches de edición limitada»](https://osu.ppy.sh/home/news/2022-12-10-makeship-x-osu-plushies)
```suggestion
[^makeship]: [Publicación de noticias del osu! team (2022-12-10) «Makeship x osu!: Limited Edition Plushies»](https://osu.ppy.sh/home/news/2022-12-10-makeship-x-osu-plushies)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^medals-november]: [Publicación de noticias de 0x84f, Junihuhn, Pisapou y RandomeLoL (2022-12-01) «osu!monthly, noviembre de 2022»](https://osu.ppy.sh/home/news/2022-12-01-osumonthly-5#new-medals)
```suggestion
[^medals-november]: [Publicación de noticias de 0x84f, Junihuhn, Pisapou y RandomeLoL (2022-12-01) «osu!monthly, November 2022»](https://osu.ppy.sh/home/news/2022-12-01-osumonthly-5#new-medals)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^editor-rotate]: [Pull request de bdach (2022-01-08) «Add tooltip with relative rotation in degrees to rotation handles»](https://github.com/ppy/osu/pull/16371)
```suggestion
[^editor-rotate]: [Solicitud de cambos por bdach (2022-01-08) «Add tooltip with relative rotation in degrees to rotation handles»](https://github.com/ppy/osu/pull/16371)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^score-pin]: [Pull request de nanaya (2021-12-14) «Add pinning scores»](https://github.com/ppy/osu-web/pull/8442)
```suggestion
[^score-pin]: [Solicitud de cambos por nanaya (2021-12-14) «Add pinning scores»](https://github.com/ppy/osu-web/pull/8442)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^hold-off]: [Pull request de Spooghetti420 (2022-01-27) «Add "Hold Off" mod (no long notes)»](https://github.com/ppy/osu/pull/16658)
```suggestion
[^aim-assist]: [Solicitud de cambos por MaxOhn (2019-08-20) «Add "Aim Assist" mod»](https://github.com/ppy/osu/pull/5774)
[^aim-assist-rename]: [Solicitud de cambos por peppy (2022-04-01) «Rename "Aim Assist" to "Magnetised" to better suit the mod's behaviour»](https://github.com/ppy/osu/pull/17588)
[^alternate]: [Solicitud de cambos por LeNitrous (2022-01-29) «Add "Alternate" mod for osu! ruleset»](https://github.com/ppy/osu/pull/16701)
[^hold-off]: [Solicitud de cambos por Spooghetti420 (2022-01-27) «Add "Hold Off" mod (no long notes)»](https://github.com/ppy/osu/pull/16658)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^strict-tracking]: [Pull request de apollo-dw (2022-03-20) «Implement "Strict Tracking" mod in osu!»](https://github.com/ppy/osu/pull/17356)
```suggestion
[^adaptive-speed]: [Solicitud de cambos por hlysine (2022-03-02) «Implement Adaptive Speed mod»](https://github.com/ppy/osu/pull/17054)
[^strict-tracking]: [Solicitud de cambos por de apollo-dw (2022-03-20) «Implement "Strict Tracking" mod in osu!»](https://github.com/ppy/osu/pull/17356)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^repel]: [Pull request de ggliv (2022-06-07) «Add repel mod to the osu ruleset»](https://github.com/ppy/osu/pull/18607)
```suggestion
[^lazer-chat]: [Solicitud de cambos por jai-x (2022-05-23) «Integrate new chat into game»](https://github.com/ppy/osu/pull/18377)
[^lazer-mod-select]: [Solicitud de cambos por bdach (2022-05-05) «Replace old mod overlay with new design»](https://github.com/ppy/osu/pull/18111)

[^repel]: [Solicitud de cambos por ggliv (2022-06-07) «Add repel mod to the osu ruleset»](https://github.com/ppy/osu/pull/18607)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^presets]: [Pull request de bdach (2022-08-07) «Add mod preset column to solo mod select overlay»](https://github.com/ppy/osu/pull/19622)
```suggestion
[^single-tap]: [Solicitud de cambos por tsunyoku (2022-07-13) «Add "Single Tap" mod for osu! ruleset, abstract Alternate & Single Tap into InputBlockingMod»](https://github.com/ppy/osu/pull/19089)

[^coe-osu-infra]: [Vídeo de YouTube por peppy (2022-08-07) «"osu! infrastructure" dev talk at #COE2022"»](https://www.youtube.com/watch?v=HVBVqvpFVL4)
[^presets]: [Solicitud de cambos por bdach (2022-08-07) «Add mod preset column to solo mod select overlay»](https://github.com/ppy/osu/pull/19622)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^argon]: [Pull request de peppy (2022-09-19) «Add new default "argon" skin»](https://github.com/ppy/osu/pull/20377)
```suggestion
[^argon]: [Solicitud de cambos por peppy (2022-09-19) «Add new default "argon" skin»](https://github.com/ppy/osu/pull/20377)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^highest-rank]: [Pull request de cl8n (2022-10-18) «Show highest achieved rank on user profile»](https://github.com/ppy/osu-web/pull/9388)
```suggestion
[^freeze-frame]: [Solicitud de cambos por mk56-spn (2022-09-16) «Add "Freeze Frame" mod»](https://github.com/ppy/osu/pull/20345)
[^highest-rank]: [Solicitud de cambos por cl8n (2022-10-18) «Show highest achieved rank on user profile»](https://github.com/ppy/osu-web/pull/9388)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^argon-pro]: [Pull request de nekodex (2022-12-20) «Add argon "pro" skin»](https://github.com/ppy/osu/pull/21735)
```suggestion
[^argon-pro]: [Solicitud de cambos por nekodex (2022-12-20) «Add argon "pro" skin»](https://github.com/ppy/osu/pull/21735)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^realm]: [Pull request de peppy (2022-01-12) «Migrate scores and beatmaps to realm»](https://github.com/ppy/osu/pull/16428)
```suggestion
[^realm]: [Solicitud de cambos por peppy (2022-01-12) «Migrate scores and beatmaps to realm»](https://github.com/ppy/osu/pull/16428)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^btmc-peppy-interview]: [Video de YouTube de BTMC (2022-03-01) «INTERVIEW WITH PEPPY: THE DIRECTION OF OSU!LAZER»](https://www.youtube.com/watch?v=3sVvC1FCTzs)
```suggestion
[^btmc-peppy-interview]: [Vídeo de YouTube por BTMC (2022-03-01) «INTERVIEW WITH PEPPY: THE DIRECTION OF OSU!LAZER»](https://www.youtube.com/watch?v=3sVvC1FCTzs)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^score-limit]: [Video de YouTube de Willy (2022-10-17) «osu! has run out of scores»](https://www.youtube.com/watch?v=EKaVzjD3ckg)
```suggestion
[^score-limit]: [Vídeo de YouTube por Willy (2022-10-17) «osu! has run out of scores»](https://www.youtube.com/watch?v=EKaVzjD3ckg)
```

2024-02-06 17:18 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^15-celebration]: [Video de YouTube de 2th - osu! Archive (2022-09-18) «[Live] ppy | celebrating 15 years of osu! {09-17-2022}»](https://www.youtube.com/watch?v=xEfXbNbkIvw)
```suggestion
[^15-celebration]: [Vídeo de YouTube por 2th - osu! Archive (2022-09-18) «[Live] ppy | celebrating 15 years of osu! {09-17-2022}»](https://www.youtube.com/watch?v=xEfXbNbkIvw)
```

2024-02-06 17:39 UTC, JuanM4T commented on wiki/History_of_osu!/2022/es.md
> +[^editor-rotate]: [Pull request de bdach (2022-01-08) «Add tooltip with relative rotation in degrees to rotation handles»](https://github.com/ppy/osu/pull/16371)
No sabía que traduciamos pull request; anyway, imagino que has cometido una errata en todas las sugerencias estas con "cambos" en lugar de "cambios"

2024-02-06 17:48 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^editor-rotate]: [Pull request de bdach (2022-01-08) «Add tooltip with relative rotation in degrees to rotation handles»](https://github.com/ppy/osu/pull/16371)
watafa es verdad

2024-02-06 17:52 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^score-pin-reorder]: [Solicitud de cambios por nanaya (24/12/2021) «Agregar soporte para reorganizar puntuaciones fijadas»](https://github.com/ppy/osu-web/pull/8468)
```suggestion
[^score-pin-reorder]: [Solicitud de cambios por nanaya (24/12/2021) «Add support to rearrange pinned scores»](https://github.com/ppy/osu-web/pull/8468)
```

2024-02-06 17:52 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^coe-osu-infra]: [Video de YouTube de peppy (07/08/2022) «"osu! infrastructure" dev talk at #COE2022"»](https://www.youtube.com/watch?v=HVBVqvpFVL4)
```suggestion
[^coe-osu-infra]: [Vídeo de YouTube por peppy (07/08/2022) «"osu! infrastructure" dev talk at #COE2022"»](https://www.youtube.com/watch?v=HVBVqvpFVL4)
```

2024-02-06 17:52 UTC, JuanM4T commented on wiki/History_of_osu!/2022/es.md
> +[^coe-osu-infra]: [Video de YouTube de peppy (2022-08-07) «"osu! infrastructure" dev talk at #COE2022"»](https://www.youtube.com/watch?v=HVBVqvpFVL4)
```suggestion
[^coe-osu-infra]: [Vídeo de YouTube por peppy (2022-08-07) «"osu! infrastructure" dev talk at #COE2022"»](https://www.youtube.com/watch?v=HVBVqvpFVL4)
```

2024-02-06 20:30 UTC, UnknownOsu requested changes

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^halloween]: [Publicación de noticia de Ephemeral (29/10/2022) «Halloween 2022 Fanart Contest Results»](https://osu.ppy.sh/home/news/2022-10-29-halloween-fanart-results)
```suggestion
[^halloween]: [Publicación de noticia por Ephemeral (29/10/2022) «Halloween 2022 Fanart Contest Results»](https://osu.ppy.sh/home/news/2022-10-29-halloween-fanart-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^pp-survey]: [Publicación de noticia del osu! team (7/2/2022) «Results - osu!taiko & osu!mania Performance Points & Star Rating Surveys»](https://osu.ppy.sh/home/news/2022-02-07-taiko-mania-survey-r
```suggestion
[^pp-survey]: [Publicación de noticia por el osu! team (7/2/2022) «Results - osu!taiko & osu!mania Performance Points & Star Rating Surveys»](https://osu.ppy.sh/home/news/2022-02-07-taiko-mania-survey-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^community-meeting-questions]: [reunión con la comunidad #10 (6/2/2022) en Google Docs](https://docs.google.com/document/d/1IM8LlHTrU9aIBkS-WTfbpLrMMrq2eRgRl7EAo_chDYE/edit)
```suggestion
[^community-meeting-questions]: [Reunión con la comunidad #10 (6/2/2022) en Google Docs](https://docs.google.com/document/d/1IM8LlHTrU9aIBkS-WTfbpLrMMrq2eRgRl7EAo_chDYE/edit)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^community-meeting-mod]: [Publicación de noticia del osu! team (7/3/2022) «Community Meetings Recap & Scoring Survey»](https://osu.ppy.sh/home/news/2022-03-07-community-meetings-recap)
```suggestion
[^community-meeting-mod]: [Publicación de noticia por el osu! team (7/3/2022) «Community Meetings Recap & Scoring Survey»](https://osu.ppy.sh/home/news/2022-03-07-community-meetings-recap)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^tides-of-winter]: [Publicación de noticia de RockRoller (25/2/2022) «Skinning Contest: Tides of Winter - Results»](https://osu.ppy.sh/home/news/2022-02-25-skinning-contest-tides-of-winter-results)
```suggestion
[^tides-of-winter]: [Publicación de noticia por RockRoller (25/2/2022) «Skinning Contest: Tides of Winter - Results»](https://osu.ppy.sh/home/news/2022-02-25-skinning-contest-tides-of-winter-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^community-meeting-leaderboard]: [Publicación de noticia del osu! team (7/3/2022) «Community Meetings Recap & Scoring Survey»](https://osu.ppy.sh/home/news/2022-03-07-community-meetings-recap)
```suggestion
[^community-meeting-leaderboard]: [Publicación de noticia por el osu! team (7/3/2022) «Community Meetings Recap & Scoring Survey»](https://osu.ppy.sh/home/news/2022-03-07-community-meetings-recap)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^monstercat]: [Publicación de noticia de pishifat (6/4/2022) «New Featured Artist: Stonebank»](https://osu.ppy.sh/home/news/2022-04-06-new-featured-artist-stonebank)
```suggestion
[^monstercat]: [Publicación de noticia por pishifat (6/4/2022) «New Featured Artist: Stonebank»](https://osu.ppy.sh/home/news/2022-04-06-new-featured-artist-stonebank)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^community-meeting-survey-1]: [«Notas de la reunión con la comunidad de osu! 2022-04-03» en Google Docs](https://docs.google.com/document/d/1LzKpXwIKxcpYgEAK4zdEIVuMNJckoo9SWN-UoAvOto8/edit)
```suggestion
[^community-meeting-survey-1]: [«osu! community meeting notes 2022-04-03» en Google Docs](https://docs.google.com/document/d/1LzKpXwIKxcpYgEAK4zdEIVuMNJckoo9SWN-UoAvOto8/edit)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^community-meeting-survey-2]: [Publicación de noticia del osu! team (17/4/2022) «Scoring Survey Results»](https://osu.ppy.sh/home/news/2022-04-17-scoring-survey-results)
```suggestion
[^community-meeting-survey-2]: [Publicación de noticia por el osu! team (17/4/2022) «Scoring Survey Results»](https://osu.ppy.sh/home/news/2022-04-17-scoring-survey-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^aptb-results]: [Publicación de noticia de Ephemeral (8/5/2022) «A Place To Belong Fanart Contest Results»](https://osu.ppy.sh/home/news/2022-05-08-aptb-fanart-results)
```suggestion
[^aptb-results]: [Publicación de noticia por Ephemeral (8/5/2022) «A Place To Belong Fanart Contest Results»](https://osu.ppy.sh/home/news/2022-05-08-aptb-fanart-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^community-contributor]: [Publicación de noticia del osu! team (30/6/2022) «Community Contributors: 2021»](https://osu.ppy.sh/home/news/2022-06-30-community-contributors-2021)
```suggestion
[^community-contributor]: [Publicación de noticia por el osu! team (30/6/2022) «Community Contributors: 2021»](https://osu.ppy.sh/home/news/2022-06-30-community-contributors-2021)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^osu-weekly]: [Publicación de noticia de Nyquill (7/6/2017) «osu!weekly #106»](https://osu.ppy.sh/home/news/2017-06-07-osu-weekly-106)
```suggestion
[^osu-weekly]: [Publicación de noticia por Nyquill (7/6/2017) «osu!weekly #106»](https://osu.ppy.sh/home/news/2017-06-07-osu-weekly-106)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^place-canvas]: [Publicación de Reddit de u/Vavik (5/4/2022) «Actual Final Image of Place 2022 (High Res)»](https://www.reddit.com/r/place/comments/twkdw7/actual_final_image_of_place_2022_high_res/)
```suggestion
[^place-canvas]: [Publicación de Reddit por u/Vavik (5/4/2022) «Actual Final Image of Place 2022 (High Res)»](https://www.reddit.com/r/place/comments/twkdw7/actual_final_image_of_place_2022_high_res/)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^monthly-quiz]: [Publicación de noticia de Soetch, Blushing, Wowcake, 0x84f y Hubz (1/8/2022) «osu!monthly returns, July 2022»](https://osu.ppy.sh/home/news/2022-08-01-osumonthly-1#monthly-community
```suggestion
[^monthly-quiz]: [Publicación de noticia por Soetch, Blushing, Wowcake, 0x84f y Hubz (1/8/2022) «osu!monthly returns, July 2022»](https://osu.ppy.sh/home/news/2022-08-01-osumonthly-1#monthly-community-quiz)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^roundtable-winners]: [Publicación de noticia de Soetch, Blushing, Wowcake, 0x84f y Hubz (1/8/2022) «osu!monthly returns, July 2022»](https://osu.ppy.sh/home/news/2022-08-01-osumonthly-1#what's-new-
```suggestion
[^roundtable-winners]: [Publicación de noticia por Soetch, Blushing, Wowcake, 0x84f y Hubz (1/8/2022) «osu!monthly returns, July 2022»](https://osu.ppy.sh/home/news/2022-08-01-osumonthly-1#what's-new-in-osu!?)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^15-anniversary-results]: [Publicación de noticia de Ephemeral (15/9/2022) «15th Anniversary Art Contest Results»](https://osu.ppy.sh/home/news/2022-09-15-anniversary-art-contest-results)
```suggestion
[^15-anniversary-results]: [Publicación de noticia por Ephemeral (15/9/2022) «15th Anniversary Art Contest Results»](https://osu.ppy.sh/home/news/2022-09-15-anniversary-art-contest-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^osu-sr-pp]: [Publicación de noticia del comité de pp de osu! (30/9/2022) «Changes to osu! Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-09-30-changes-to-osu-sr-and-pp)
```suggestion
[^osu-sr-pp]: [Publicación de noticia por el comité de pp de osu! (30/9/2022) «Changes to osu! Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-09-30-changes-to-osu-sr-and-pp)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^osu-taiko-sr-pp]: [Publicación de noticia del comité de pp de osu!taiko (28/9/2022) «Changes to osu!taiko Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-09-28-changes-to-osu-t
```suggestion
[^osu-taiko-sr-pp]: [Publicación de noticia por el comité de pp de osu!taiko (28/9/2022) «Changes to osu!taiko Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-09-28-changes-to-osu-taiko-sr-and-pp)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^medals-september]: [Publicación de noticia de 0x84f, Pisapou y RandomeLoL (2/10/2022) «osu!monthly, September 2022»](https://osu.ppy.sh/home/news/2022-10-02-osumonthly-3)
```suggestion
[^medals-september]: [Publicación de noticia por 0x84f, Pisapou y RandomeLoL (2/10/2022) «osu!monthly, September 2022»](https://osu.ppy.sh/home/news/2022-10-02-osumonthly-3)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^triangles-results]: [Publicación de noticia de pishifat (6/10/2022) «Results - triangles»](https://osu.ppy.sh/home/news/2022-10-06-results-triangles)
```suggestion
[^triangles-results]: [Publicación de noticia por pishifat (6/10/2022) «Results - triangles»](https://osu.ppy.sh/home/news/2022-10-06-results-triangles)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^osu-mania-sr-pp]: [Publicación de noticia del comité de pp de osu!mania (9/10/2022) «Changes to osu!mania Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-10-09-changes-to-osu-m
```suggestion
[^osu-mania-sr-pp]: [Publicación de noticia por el comité de pp de osu!mania (9/10/2022) «Changes to osu!mania Star Rating & Performance Points»](https://osu.ppy.sh/home/news/2022-10-09-changes-to-osu-mania-sr-and-pp)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^chromatic-alt-results]: [Publicación de noticia de RockRoller (20/10/2022) «Skinning Contest: Chromatic Alteration - Results»](https://osu.ppy.sh/home/news/2022-10-20-skinning-contest-chromatic-alt
```suggestion
[^chromatic-alt-results]: [Publicación de noticia por RockRoller (20/10/2022) «Skinning Contest: Chromatic Alteration - Results»](https://osu.ppy.sh/home/news/2022-10-20-skinning-contest-chromatic-alteration-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^medals-november]: [Publicación de noticia de 0x84f, Junihuhn, Pisapou y RandomeLoL (1/12/2022) «osu!monthly, November 2022»](https://osu.ppy.sh/home/news/2022-12-01-osumonthly-5#new-medals)
```suggestion
[^medals-november]: [Publicación de noticia por 0x84f, Junihuhn, Pisapou y RandomeLoL (1/12/2022) «osu!monthly, November 2022»](https://osu.ppy.sh/home/news/2022-12-01-osumonthly-5#new-medals)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^new-beginnings]: [Publicación de noticia de Ephemeral (31/12/2022) «New Beginnings Art Contest: Results»](https://osu.ppy.sh/home/news/2022-12-31-new-beginnings-results)
```suggestion
[^new-beginnings]: [Publicación de noticia por Ephemeral (31/12/2022) «New Beginnings Art Contest: Results»](https://osu.ppy.sh/home/news/2022-12-31-new-beginnings-results)
```

2024-02-06 20:30 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^makeship]: [Publicación de noticia del osu! team (10/12/2022) «Makeship x osu!: Limited Edition Plushies»](https://osu.ppy.sh/home/news/2022-12-10-makeship-x-osu-plushies)
```suggestion
[^makeship]: [Publicación de noticia por el osu! team (10/12/2022) «Makeship x osu!: Limited Edition Plushies»](https://osu.ppy.sh/home/news/2022-12-10-makeship-x-osu-plushies)
```

2024-02-06 20:46 UTC, UnknownOsu requested changes

2024-02-06 20:46 UTC, UnknownOsu commented on wiki/History_of_osu!/2022/es.md
> +[^community-meeting-survey-1]: [«Notas de la reunión con la comunidad de osu! (3/4/2022)» en Google Docs](https://docs.google.com/document/d/1LzKpXwIKxcpYgEAK4zdEIVuMNJckoo9SWN-UoAvOto8/edit)
```suggestion
[^community-meeting-survey-1]: [«osu! community meeting notes 2022-04-03» en Google Docs](https://docs.google.com/document/d/1LzKpXwIKxcpYgEAK4zdEIVuMNJckoo9SWN-UoAvOto8/edit)
```

2024-02-06 20:49 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[^community-meeting-survey-1]: [«Notas de la reunión con la comunidad de osu! 2022-04-03» en Google Docs](https://docs.google.com/document/d/1LzKpXwIKxcpYgEAK4zdEIVuMNJckoo9SWN-UoAvOto8/edit)
ya está bien

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +Más artistas se unieron al programa de los [artistas destacados](/wiki/People/Featured_Artists) a principios de año, siendo estos: [NIWASHI](https://osu.ppy.sh/beatmaps/artists/228), [DGK](https://os
```suggestion
Más artistas se unieron al programa de [artistas destacados](/wiki/People/Featured_Artists) a principios de año, siendo estos: [NIWASHI](https://osu.ppy.sh/beatmaps/artists/228), [DGK](https://osu.ppy.sh/beatmaps/artists/229), [Haywyre](https://osu.ppy.sh/beatmaps/artists/230), [satella](https://osu.ppy.sh/beatmaps/artists/231), [Vansire](https://osu.ppy.sh/beatmaps/artists/232), [Boom Kitty](https://osu.ppy.sh/beatmaps/artists/233), [Annabel](https://osu.ppy.sh/beatmaps/artists/234) y [Maduk](https://osu.ppy.sh/beatmaps/artists/235).
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +Se añadió una nueva función al editor de osu!(lazer) que le permite a los mappers rotar contenido seleccionado mediante un botón.[^editor-rotate] Mientras tanto, se implementó en el cliente un nuevo
```suggestion
Se añadió una nueva función al editor de osu!(lazer) que permite a los mappers rotar contenido seleccionado mediante un botón.[^editor-rotate] Mientras tanto, se implementó en el cliente un nuevo sistema de base de datos llamado [Realm](https://realm.io/), que proporciona mayor eficacia y fiabilidad. Se agregó una barra de progreso al comienzo del juego mientras se realizaba la migración, ya que podría llevar un tiempo si había grandes cantidades de beatmaps y otros datos.[^realm]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[bill wurtz](https://osu.ppy.sh/beatmaps/artists/236), [Atavistia](https://osu.ppy.sh/beatmaps/artists/237), [HEAD PHONES PRESIDENT](https://osu.ppy.sh/beatmaps/artists/238), [MisoilePunch](https://o
```suggestion
[bill wurtz](https://osu.ppy.sh/beatmaps/artists/236), [Atavistia](https://osu.ppy.sh/beatmaps/artists/237), [HEAD PHONES PRESIDENT](https://osu.ppy.sh/beatmaps/artists/238), [MisoilePunch](https://osu.ppy.sh/beatmaps/artists/239), [Good Kid](https://osu.ppy.sh/beatmaps/artists/240), [Riya](https://osu.ppy.sh/beatmaps/artists/241), [Rabbit House](https://osu.ppy.sh/beatmaps/artists/242) y [MisomyL](https://osu.ppy.sh/beatmaps/artists/243) se convirtieron en artistas destacados.
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +El 6 de febrero se realizó la tercera reunión con la comunidad del año, dedicada a diversas preguntas de la comunidad.[^community-meeting-questions] El 20 de febrero, se llevó a cabo otra reunión con
```suggestion
El 6 de febrero se realizó la tercera reunión con la comunidad del año, dedicada a diversas preguntas de la comunidad.[^community-meeting-questions] El 20 de febrero, se llevó a cabo otra reunión con la comunidad sobre los multiplicadores y la puntuación de los mods, debido a que osu!(lazer) permite ajustes de tasa variable para algunos mods. Por ejemplo, Double Time puede ser ajustado para dar una velocidad de 1,01x, en lugar de solo 1,5x como en stable. Esto le daría a los jugadores una ventaja injusta en las tablas de clasificación, ya que los jugadores aún recibirían el multiplicador de puntuación fijo de 1,12x. Como consecuencia, los multiplicadores de los mods se desactivaron temporalmente. El osu! team quiere trabajar en una solución más sólida en el futuro.[^community-meeting-mod]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +Después de la primera iteración en mayo del año pasado, hubo otro concurso de skinning, esta vez con [Tides of Winter](https://osu.ppy.sh/home/news/2021-12-02-skinning-contest-tides-of-winter-announc
```suggestion
Después de la primera iteración en mayo del año pasado, hubo otro concurso de skinning, esta vez con [Tides of Winter](https://osu.ppy.sh/home/news/2021-12-02-skinning-contest-tides-of-winter-announcement) como tema. El concurso concluyó con [thetasigma](https://osu.ppy.sh/users/6234482), [BPChingu](https://osu.ppy.sh/users/4236855) y [Redo_](https://osu.ppy.sh/users/7122165) obteniendo el tercer, segundo y primer lugar respectivamente.[^tides-of-winter]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +El 6 de marzo se llevó a cabo otra reunión con la comunidad para determinar cómo se gestionarían las tablas de clasificación y la visualización de puntuaciones. La solución implementada fue mostrar p
```suggestion
El 6 de marzo se llevó a cabo otra reunión con la comunidad para determinar cómo se gestionarían las tablas de clasificación y la visualización de puntuaciones. La solución implementada fue mostrar puntuaciones de stable en lazer con el mod Classic aplicado. Sin embargo, no se resolvió la posibilidad de mostrar puntuaciones de lazer en stable, ya que los nuevos mods de lazer definitivamente no se implementarían en stable y, por lo tanto, mostrar dichas puntuaciones en stable solo sería posible con ciertas restricciones. Para integrar a la comunidad en este proceso, se realizó una [encuesta sobre marcadores en lazer](https://docs.google.com/forms/d/1jAWlFkjECDftXJ7iZFgipH1sJuwYDvPtF0CuaciFiW8/viewanalytics). Si bien preservar la historia era y sigue siendo una prioridad, la cuestión de dividir o fusionar las tablas de clasificación antiguas y nuevas se dejó en manos de la comunidad.[^community-meeting-leaderboard] El 20 de marzo se organizó otra reunión con la comunidad para dar a conocer el desarrollo en curso.[^community-meeting-dev-2]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +9 nuevos artistas formaron parte del programa de los artistas destacados: [A.SAKA](https://osu.ppy.sh/beatmaps/artists/253), [Stonebank](https://osu.ppy.sh/beatmaps/artists/254), [Archspire](https://
```suggestion
9 nuevos artistas formaron parte del programa de los artistas destacados: [A.SAKA](https://osu.ppy.sh/beatmaps/artists/253), [Stonebank](https://osu.ppy.sh/beatmaps/artists/254), [Archspire](https://osu.ppy.sh/beatmaps/artists/256), [in love with a ghost](https://osu.ppy.sh/beatmaps/artists/257), [Mage](https://osu.ppy.sh/beatmaps/artists/258), [Aethral](https://osu.ppy.sh/beatmaps/artists/259), [Nile](https://osu.ppy.sh/beatmaps/artists/260), [MUZZ](https://osu.ppy.sh/beatmaps/artists/261) y [Mitsuki / RINYA](https://osu.ppy.sh/beatmaps/artists/262). Además, la discográfica [Monstercat](https://osu.ppy.sh/beatmaps/artists/255) también se unió a osu!, aportando muchos artistas nuevos a la comunidad.[^monstercat]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +En este mes, [Ardolf](https://osu.ppy.sh/beatmaps/artists/263), [Allegaeon](https://osu.ppy.sh/beatmaps/artists/264), [Tenchio](https://osu.ppy.sh/beatmaps/artists/265), [Neko Hacker](https://osu.ppy
```suggestion
En este mes, [Ardolf](https://osu.ppy.sh/beatmaps/artists/263), [Allegaeon](https://osu.ppy.sh/beatmaps/artists/264), [Tenchio](https://osu.ppy.sh/beatmaps/artists/265), [Neko Hacker](https://osu.ppy.sh/beatmaps/artists/266), [JOYLESS](https://osu.ppy.sh/beatmaps/artists/267), [69 de 74](https://osu.ppy.sh/beatmaps/artists/268), [Origami Angel](https://osu.ppy.sh/beatmaps/artists/269) y [Rameses B](https://osu.ppy.sh/beatmaps/artists/270) se unieron a osu! como artistas destacados.
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +En el concurso de fanart [A Place To Belong](https://osu.ppy.sh/home/news/2022-04-11-place-to-belong-fanart-contest), a los artistas se les pidió que dibujaran a las mascotas de osu! yendo de aventur
```suggestion
En el concurso de arte de fans [A Place To Belong](https://osu.ppy.sh/home/news/2022-04-11-place-to-belong-fanart-contest), a los artistas se les pidió que dibujaran a las mascotas de osu! yendo de aventuras a lugares a los que nunca habían ido. [Dreamxiety](https://osu.ppy.sh/users/13103233) ganó el concurso con 3713 votos.[^aptb-results]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +osu! dio la bienvenida a [Ponchi](https://osu.ppy.sh/beatmaps/artists/271), [Hino Isuka](https://osu.ppy.sh/beatmaps/artists/272), [SAMString](https://osu.ppy.sh/beatmaps/artists/273), [Kanpyohgo](ht
```suggestion
osu! dio la bienvenida a [Ponchi](https://osu.ppy.sh/beatmaps/artists/271), [Hino Isuka](https://osu.ppy.sh/beatmaps/artists/272), [SAMString](https://osu.ppy.sh/beatmaps/artists/273), [Kanpyohgo](https://osu.ppy.sh/beatmaps/artists/274), [:Poin7less](https://osu.ppy.sh/beatmaps/artists/275), [Tokyo Machine](https://osu.ppy.sh/beatmaps/artists/276), [Beach Bunny](https://osu.ppy.sh/beatmaps/artists/277), [NILFRUITS](https://osu.ppy.sh/beatmaps/artists/278) y [Toromaru](https://osu.ppy.sh/beatmaps/artists/279) como artistas destacados.
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +9 artistas más se unieron al programa de los artistas destacados, siendo estos: [Rootkit](https://osu.ppy.sh/beatmaps/artists/280), [Grant](https://osu.ppy.sh/beatmaps/artists/281), [aran](https://os
```suggestion
9 artistas más se unieron al programa de los artistas destacados, siendo estos: [Rootkit](https://osu.ppy.sh/beatmaps/artists/280), [Grant](https://osu.ppy.sh/beatmaps/artists/281), [aran](https://osu.ppy.sh/beatmaps/artists/282), [Liar-soft](https://osu.ppy.sh/beatmaps/artists/283), [Blind Guardian](https://osu.ppy.sh/beatmaps/artists/284), [Exyl](https://osu.ppy.sh/beatmaps/artists/285), [NOISZ](https://osu.ppy.sh/beatmaps/artists/286), [Pegboard Nerds](https://osu.ppy.sh/beatmaps/artists/287) y [ZxNX](https://osu.ppy.sh/beatmaps/artists/288).
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +En este mes, osu! logró contar con la colaboración de [Hamu](https://osu.ppy.sh/beatmaps/artists/289), [Darkney](https://osu.ppy.sh/beatmaps/artists/290), [Waterflame](https://osu.ppy.sh/beatmaps/art
```suggestion
En este mes, osu! logró contar con la colaboración de [Hamu](https://osu.ppy.sh/beatmaps/artists/289), [Darkney](https://osu.ppy.sh/beatmaps/artists/290), [Waterflame](https://osu.ppy.sh/beatmaps/artists/291), [Mitsukiyo](https://osu.ppy.sh/beatmaps/artists/292), [Koven](https://osu.ppy.sh/beatmaps/artists/293), [Abuse](https://osu.ppy.sh/beatmaps/artists/294), [DJ Genki / Gram](https://osu.ppy.sh/beatmaps/artists/295), [Aiyru](https://osu.ppy.sh/beatmaps/artists/296) y [-45](https://osu.ppy.sh/beatmaps/artists/297) para convertirse en artistas destacados.
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +[Nashimoto Ui](https://osu.ppy.sh/beatmaps/artists/298), [Nitro Fun](https://osu.ppy.sh/beatmaps/artists/299), [Rezonate](https://osu.ppy.sh/beatmaps/artists/300), [AAAA](https://osu.ppy.sh/beatmaps/
```suggestion
[Nashimoto Ui](https://osu.ppy.sh/beatmaps/artists/298), [Nitro Fun](https://osu.ppy.sh/beatmaps/artists/299), [Rezonate](https://osu.ppy.sh/beatmaps/artists/300), [AAAA](https://osu.ppy.sh/beatmaps/artists/301), [Andy Gillion](https://osu.ppy.sh/beatmaps/artists/302), [Vorso](https://osu.ppy.sh/beatmaps/artists/303), [Alestorm](https://osu.ppy.sh/beatmaps/artists/304), [Ritorikal](https://osu.ppy.sh/beatmaps/artists/305) y [Feint](https://osu.ppy.sh/beatmaps/artists/306) se unieron a osu! como artistas destacados.
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +En este mes, [Mono.](https://osu.ppy.sh/beatmaps/artists/307), [Tokyo.MeltiMelt](https://osu.ppy.sh/beatmaps/artists/308), [Ata](https://osu.ppy.sh/beatmaps/artists/309), [Hybrid Minds](https://osu.p
```suggestion
En este mes, [Mono.](https://osu.ppy.sh/beatmaps/artists/307), [Tokyo.MeltiMelt](https://osu.ppy.sh/beatmaps/artists/308), [Ata](https://osu.ppy.sh/beatmaps/artists/309), [Hybrid Minds](https://osu.ppy.sh/beatmaps/artists/310), [GLORYHAMMER](https://osu.ppy.sh/beatmaps/artists/311), [Au5](https://osu.ppy.sh/beatmaps/artists/312), [Fractal](https://osu.ppy.sh/beatmaps/artists/313), [Kikuo](https://osu.ppy.sh/beatmaps/artists/314), [Hinkik](https://osu.ppy.sh/beatmaps/artists/315) y [Zenpaku](https://osu.ppy.sh/beatmaps/artists/316) fueron anunciados como los nuevos artistas destacados.
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +El concurso de beatmapping y storyboard [triangles](https://osu.ppy.sh/home/news/2022-05-31-triangles) concluyó este mes, con el equipo Crazy Thursday formado por [yf_bmp](https://osu.ppy.sh/users/12
```suggestion
El concurso de beatmapping y storyboarding [triangles](https://osu.ppy.sh/home/news/2022-05-31-triangles) concluyó este mes, con el equipo Crazy Thursday formado por [yf_bmp](https://osu.ppy.sh/users/1243669), [TtmnZk](https://osu.ppy.sh/users/2495509), [Yugu](https://osu.ppy.sh/users/3161834), [Chaoslitz](https://osu.ppy.sh/users/3621552) y [Yumeno Himiko](https://osu.ppy.sh/users/1806962) llevándose el primer lugar. Su beatmap se incluirá en cada instalación de osu!(lazer) como el gran premio del concurso.[^triangles-results]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +Entre otros cambios, osu!mania ahora utiliza la precisión en lugar de la puntuación al calcular los puntos de rendimiento, debido a cambios en los sistemas de clasificación por estrellas y de puntos
```suggestion
Entre otros cambios, osu!mania ahora usa la precisión en lugar de la puntuación para calcular los puntos de rendimiento, debido a cambios en los sistemas de clasificación por estrellas y de puntos de rendimiento.[^osu-mania-sr-pp]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +osu! superó las 4 294 967 296 puntuaciones, lo que significa que el antiguo sistema de base de datos ha alcanzado su límite. Cada puntuación se guarda con un entero único sin signo de 32 bits, lo que
```suggestion
osu! superó las 4 294 967 296 puntuaciones, lo que significa que el antiguo sistema de base de datos ha alcanzado su límite. Cada puntuación se guarda con un entero único sin signo de 32 bits, lo que significa que la base de datos no puede almacenar más de 2^32 puntuaciones. La infraestructura de la base de datos ampliada ya estaba planeada meses antes y se migró con unas semanas de antelación.[^score-limit][^osu-death][^score-submission] La última puntuación enviada en el antiguo sistema fue [\*namirin - Kanzen Shouri\*Esper Girl](https://osu.ppy.sh/scores/osu/4294967295) jugada por [ElDanetex](https://osu.ppy.sh/users/18930084).
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +Para Halloween de este año, hubo un [concurso de fanart](https://osu.ppy.sh/home/news/2022-10-10-halloween-fanart-contest) una vez más donde se animaba a los artistas a dibujar a las mascotas de osu!
```suggestion
Para Halloween de este año, hubo un [concurso de arte de fans](https://osu.ppy.sh/home/news/2022-10-10-halloween-fanart-contest) una vez más donde se animaba a los artistas a dibujar a las mascotas de osu! con disfraces espeluznantes. [Dreamxiety](https://osu.ppy.sh/users/13103233) ganó el primer lugar en el concurso con 3749 votos.[^halloween] Una entrada fue revocada porque se consideró demasiado terrorífica y el autor recibió en su lugar una insignia personalizada.[^grin-reddit][^grin-twitter][^grin-badge]
```

2024-02-10 10:36 UTC, agatemosu commented on wiki/History_of_osu!/2022/es.md
> +osu! dio la bienvenida a 8 nuevos artistas destacados, siendo estos: [happy30](https://osu.ppy.sh/beatmaps/artists/317), [Massive New Krew](https://osu.ppy.sh/beatmaps/artists/318), [HoneyComeBear](h
```suggestion
osu! dio la bienvenida a 8 nuevos artistas destacados, siendo estos: [happy30](https://osu.ppy.sh/beatmaps/artists/317), [Massive New Krew](https://osu.ppy.sh/beatmaps/artists/318), [HoneyComeBear](https://osu.ppy.sh/beatmaps/artists/319), [Ensou](https://osu.ppy.sh/beatmaps/artists/320), [Crywolf](https://osu.ppy.sh/beatmaps/artists/321), [E0ri4](https://osu.ppy.sh/beatmaps/artists/322), [Innocent Key](https://osu.ppy.sh/beatmaps/artists/323) y [Noisestorm](https://osu.ppy.sh/beatmaps/artists/324).
```

2024-02-10 13:14 UTC, agatemosu approved these changes

2024-02-14 11:10 UTC, TicClick approved these changes

2024-02-14 11:11 UTC, merged