[ES] Update `Guest difficulty`
ppy/osu-wiki pull request #10910
Opened 2024-02-08 08:50 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-02-09 17:42 UTC, UnknownOsu requested changes

2024-02-09 17:42 UTC, UnknownOsu commented on wiki/Beatmap/Guest_difficulty/es.md
> +Aunque no es obligatorio, tener dificultades de invitado puede ser beneficioso en muchas ocasiones, ya que a menudo presentan estilos de mapping completamente diferentes entre sí, lo que diversifica
```suggestion
Aunque no es obligatorio, tener dificultades de invitado puede ser beneficioso en muchas ocasiones, ya que a menudo presentan estilos de mapping completamente diferentes entre sí, lo que diversifica al conjunto de mapas y ayuda a reducir el agotamiento del mapping. Comúnmente, las dificultades de invitados se solicitan a través de mensajes privados entre mappers, aunque también se pueden solicitar por otros medios, como el canal `#mapping` del juego o las [colas de modding](/wiki/Community/Forum/Modding_Queues).
```

2024-02-10 16:36 UTC, UnknownOsu approved these changes

2024-02-11 13:48 UTC, TicClick approved these changes

2024-02-11 13:50 UTC, merged