[EN+ZH] Add / Update `Guides/Audio editing`
ppy/osu-wiki pull request #10919
Opened 2024-02-09 02:30 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

## Changed files

- **M** /wiki/Guides/Audio_editing/en.md
  - **A** /wiki/Guides/Audio_editing/zh.md

2024-02-14 05:30 UTC, YumeMuzi requested changes

2024-02-14 05:30 UTC, YumeMuzi commented on wiki/Guides/Audio_editing/zh.md
> +大多数 Linux 发行版在安装 Audacity 时会提供 LAME，但某些可能不会，因此 Linux 用户应当阅读 [Audacity 参考手册](https://manual.audacityteam.org/man/installing_and_updating_audacity_on_linux.html#linlame)获取更多信息。
```suggestion
大多数 Linux 发行版会提供安装 Audacity 所需的 LAME，但某些版本也可能不会提供。因此 Linux 用户应当阅读 [Audacity 参考手册](https://manual.audacityteam.org/man/installing_and_updating_audacity_on_linux.html#linlame)获取更多信息。
```

2024-02-14 05:30 UTC, YumeMuzi commented on wiki/Guides/Audio_editing/zh.md
> +*绝非你只能使用这些软件，本文只列出了作者添加的。如果你了解其他可用工具，并且能解释如何将它们用于以下小节，也请添加进来。*
```suggestion
*本文只列出了作者添加的软件，你并不是只能使用这些软件。如果你了解其他可用工具，并且能解释如何将它们用于以下小节，也请添加进来。*
```

2024-02-22 07:23 UTC, YumeMuzi approved these changes

2024-02-27 23:27 UTC, TicClick requested changes
while I generally agree that the guide can be simplified, `[Export](#lowering-bit-rate) the audio file` takes the reader to the section about bit rate lowering, and while it covers the export process, I would say it's confusing -- you need to either make a small section dedicated to the export procedure, or keep duplicated steps as below in the mp3directcut part of the article

2024-02-27 23:27 UTC, TicClick commented
(also, what does your "Sync changes with the English article" checkbox mean -- is there still something you wanted to backport from Chinese to English and forgot?)

2024-02-28 01:38 UTC, CloneWith commented
> what does your "Sync changes with the English article" checkbox mean

since the changes in the English article haven't been reviewed yet, I left Chinese translation unchanged

2024-02-28 14:05 UTC, CloneWith commented
> you need to either make a small section dedicated to the export procedure, or keep duplicated steps as below in the mp3directcut part of the article

some issues encountered when setting mp3DirectCut up:

- It complains `ACM not found`, even after I installed this library
- For LAME library, I'm unsure about which bitrate to use (Constant, Variable, Average) and which is used by our RC
- It only runs on Windows (requires x86 libraries) and Android, and hasn't been updated since 2022/01
- If we have the need to change the bitrate, we need either of the two libraries mentioned above

It seems kinda unfriendly for regular mappers. Maybe there is a better approach to edit MP3 files, but I'll try update current ones first.

2024-09-11 11:34 UTC, TicClick commented
this has been going on for quite a while, so let's try and finally get it in. please make sure the Chinese translation you added follows the updated version of the guide, and I'll merge it

2024-09-12 19:27 UTC, TicClick approved these changes

2024-09-12 19:29 UTC, merged