[ZH] Add `Changing the artist or title` and cleanup `Livestreaming osu!`
ppy/osu-wiki pull request #10918
Opened 2024-02-09 00:25 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

## Changed files

- **A** /wiki/Guides/Changing_the_artist_or_title/zh.md
- **M** /wiki/Guides/Livestreaming_osu!/zh.md (Formatting fix)

2024-02-14 05:26 UTC, YumeMuzi requested changes

2024-02-14 05:26 UTC, YumeMuzi commented on wiki/Guides/Changing_the_artist_or_title/zh.md
> +*[Full Submission with Title/Artist Change -- Mistakes，作者 NoHitter（已由 peppy 控制）](https://osu.ppy.sh/community/forums/topics/24443)*
```suggestion
*[Full Submission with Title/Artist Change -- Mistakes，作者 NoHitter（已被 peppy 接手）](https://osu.ppy.sh/community/forums/topics/24443)*
```

2024-02-14 05:26 UTC, YumeMuzi commented on wiki/Guides/Changing_the_artist_or_title/zh.md
> +如果你有谱面重复了，请联系[审核评估团队 (NAT)](/wiki/People/Nomination_Assessment_Team) 的成员寻求解决方案。
```suggestion
如果你上传了重复的谱面，请联系[审核评估团队 (NAT)](/wiki/People/Nomination_Assessment_Team) 的成员解决。
```

2024-02-22 07:23 UTC, YumeMuzi approved these changes

2024-02-26 23:41 UTC, Hiviexd approved these changes

2024-02-26 23:43 UTC, merged