[ES] Add `History of osu! 2009`
ppy/osu-wiki pull request #10989
Opened 2024-02-18 13:49 UTC by JuanM4T

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-02-18 15:16 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +En una gran actualización el 26 de enero, osu! recibió muchas funciones nuevas.[^stable-b593a] Entre esos cambios se incluyen los nuevos modos de multijugador [Tag VS](/wiki/Client/Interface/Multipla
```suggestion
En una gran actualización el 26 de enero, osu! recibió muchas funciones nuevas.[^stable-b593a] Entre esos cambios se incluyen los nuevos modos de multijugador [Tag VS](/wiki/Client/Interface/Multiplayer#team-vs) y [Tag Team VS](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs), además de protección con contraseña para las salas de multijugador. Los objetos en el editor de storyboard se podrían modificar de nuevas maneras mediante las opciones de transfomación de escalado vectorial y volteo. Jugando, efectos de iluminación de golpeo enfatizarían un golpe mediante la salpicadura de colores en el playfield. Además, la barra de progreso de la canción también se hizo visible en forma de gráfico circular. Adicionalmente, un nuevo tipo de clasificación de mapas, «Last Played», fue añadido a la pantalla de [selección de canciones](/wiki/Client/Interface#selector-de-canciones).
```

2024-02-18 15:16 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +![](img/2009-01_05.jpg "Selección de canción")
```suggestion
![](img/2009-01_05.jpg "Selección de canciones")
```

2024-02-18 15:16 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +Las actualizaciones este mes integraron nuevas funciones, entre las cuales estaban el soporte para pantallas panorámicas en la selección de canción,[^stable-b904a] soporte para amigos en la página we
```suggestion
Las actualizaciones este mes integraron nuevas funciones, entre las cuales estaban el soporte para pantallas panorámicas en la selección de canciones,[^stable-b904a] soporte para amigos en la página web,[^custom-changelog] y la mascota de Taiko [pippidon](/wiki/Mascots#pippi), que ahora se mostraría en la esquina superior izquierda mientras se juega.[^stable-b898]
```

2024-02-18 18:13 UTC, UnknownOsu requested changes

2024-02-18 18:13 UTC, UnknownOsu commented on wiki/History_of_osu!/2009/es.md
> +Este mes, el [Mapping Assistance Team](/wiki/People/Mapping_Assistance_Team) (MAT) fue creado. El MAT fue responsable para seleccionar [beatmaps pendientes](/wiki/Beatmap/Category#wip-and-pending) de
```suggestion
Este mes, el [Mapping Assistance Team](/wiki/People/Mapping_Assistance_Team) (MAT) fue creado. El MAT fue responsable de seleccionar [beatmaps pendientes](/wiki/Beatmap/Category#wip-and-pending) de calidad aceptable y recomendarlos para ser clasificados en el sistema de [modding del foro](/wiki/Modding/Forum_modding) por el [BAT](/wiki/People/Beatmap_Appreciation_Team).[^mat]
```

2024-02-18 18:13 UTC, UnknownOsu commented on wiki/History_of_osu!/2009/es.md
> +Una actualización a osu! introdujo los [hyperdashes](/wiki/Gameplay/Hyperdash) para saltos imposibles en Catch the Beat, donde los jugadores ganarian velocidad adicional por un pequeño periodo de tie
```suggestion
Una actualización a osu! introdujo los [hyperdashes](/wiki/Gameplay/Hyperdash) para jumps imposibles en Catch the Beat, donde los jugadores ganarían velocidad adicional por un pequeño período de tiempo tras recolectar una [hiperfruta](/wiki/Gameplay/Hit_object/Hyperfruit). Adicionalmente, se implementó una vista previa de un listado de usuarios en línea en la [consola de chat extendida](/wiki/Client/Interface/Chat_console#consola-de-chat-ampliada).[^stable-b1209]
```

2024-02-18 18:13 UTC, UnknownOsu commented on wiki/History_of_osu!/2009/es.md
> +## References
```suggestion
## Referencias
```

2024-02-18 18:13 UTC, UnknownOsu commented on wiki/History_of_osu!/2009/es.md
> +El foro de [Community Voice](https://osu.ppy.sh/community/forums/65) fue añadido con el objetivo de preguntar a la comunidad sobre varios temas donde los usuarios serían capaces de votar en encuestas
```suggestion
El foro [Community Voice](https://osu.ppy.sh/community/forums/65) se agregó con el objetivo de hacerle a la comunidad varias preguntas donde los usuarios pudieran votar en encuestas semanales.[^weekly-polls]
```

2024-02-18 18:30 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +![](img/2009-01_14.jpg "Récord!")
```suggestion
![](img/2009-01_14.jpg "¡Puntuación más alta!")
```

2024-02-18 18:30 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +Además de otros cambios, osu! tuvo una actualización este mes añadiendo soporte para pantallas panorámicas y el mod [Autopilot](/wiki/Gameplay/Game_modifier/Autopilot). Habilitar el mod Autopilot se
```suggestion
Además de otros cambios, osu! tuvo una actualización este mes, agregando soporte para pantallas anchas y el mod [Autopilot](/wiki/Gameplay/Game_modifier/Autopilot). Habilitar el mod Autopilot se haría cargo del movimiento del cursor y el jugador solo tendría que realizar la pulsación de las teclas.[^stable-b674]
```

2024-02-18 18:30 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +osu! recivió un nuevo parámetro, `LoopType`, para iterar sobre objetos del storyboard y el mod [Relax](/wiki/Gameplay/Game_modifier/Relax) para el modo de juego de Taiko, en una actualización el 12 d
```suggestion
osu! recibió un nuevo parámetro, `LoopType`, para poner en bucle los objetos del storyboard y el mod [Relax](/wiki/Gameplay/Game_modifier/Relax) para el modo de juego Taiko, en una actualización el 12 de agosto. Adicionalmente, se publicó una versión preliminar de [AiMod](/wiki/Client/Beatmap_editor/AiMod), una herramienta para detectar problemas en los beatmaps.[^stable-b825]
```

2024-02-18 18:30 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +Se agregó una nueva pantalla de información de clasificación que sentó las bases para el sistema de gráficos de clasificación implementado en un momento posterior.[^stable-b1077][^custom-changelog]
```suggestion
Se agregó una nueva pantalla de información sobre la clasificación que sentó las bases para el sistema de tablas de clasificación que se implementaría más adelante.[^stable-b1077][^custom-changelog]
```

2024-02-18 18:30 UTC, agatemosu commented on wiki/History_of_osu!/2009/es.md
> +Se alcanzaron dos hitos este mes. 50 000 000 puntuaciones clasificadas en total fueron realizadas el 15 de noviembre y, el 20 de noviembre, osu! alcanzó los 200 000 usuarios registrados.[^play-count]
```suggestion
Se alcanzaron dos hitos este mes. El 15 de noviembre se alcanzaron 50 000 000 de puntuaciones clasificadas en total y, el 20 de noviembre, osu! tenía 200 000 usuarios registrados.[^play-count][^user-count-2]
```

2024-02-19 17:17 UTC, UnknownOsu requested changes

2024-02-27 00:06 UTC, UnknownOsu requested changes

2024-02-27 00:06 UTC, UnknownOsu commented on wiki/History_of_osu!/2009/es.md
> +La cuenta de Twitter [@osustatus](https://twitter.com/osustatus) fue creada para informar a los jugadores de problemas con [Bancho](/wiki/Bancho_(server)) y el sitio web.[^osustatus]
```suggestion
La cuenta de Twitter [@osustatus](https://twitter.com/osustatus) fue creada para informar a los jugadores si había algún problema con [Bancho](/wiki/Bancho_(server)) y el sitio web.[^osustatus]
```

2024-02-27 12:35 UTC, TicClick approved these changes

2024-02-27 12:37 UTC, merged