[ES] Add `Music Theory`
ppy/osu-wiki pull request #11033
Opened 2024-02-28 13:40 UTC by JuanM4T

Mucho vocabulario musical, me he guiado por las estrellas y un video de jaime altozano. Lo siento mucho.
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-02-28 14:41 UTC, agatemosu commented
todo gracias a jaime, grande jaime

2024-02-28 14:43 UTC, agatemosu commented on wiki/Music_theory/es.md
> +osu!, principalmente, es un juego de música, y los beatmaps suelen ser creados con la idea de ajustarse a la música, en lugar de adaptarse a un cierto BPM. En este breve ensayo trataré la teoría musi
movería el ", principalmente," después del "es"

2024-02-28 14:44 UTC, agatemosu commented on wiki/Music_theory/es.md
> +Un contratiempo, en inglés «upbeat», es una acentuación sincopada en el pulso desplazado. En un ritmo simple de 4/4, estos son los tiempos 2 y 4... En la música popular actual, generalmente se utiliz
usa en utiliza

2024-02-28 14:45 UTC, agatemosu commented on wiki/Music_theory/es.md
> +![Teoría musical](img/MusicTheory1-ES.png "Music Theory")
lo que está entre comillas también se traduce

2024-02-28 14:46 UTC, agatemosu commented on wiki/Music_theory/es.md
> +Aquí es donde el downbeat (usualmente) se omite o se "deja caer". Al omitir el downbeat en una canción más rápida, generalmente se crea tensión. A menudo, solo un instrumento en particular dejará cae
```suggestion
Aquí es donde el downbeat (usualmente) se omite o se «deja caer». Al omitir el downbeat en una canción más rápida, generalmente se crea tensión. A menudo, solo un instrumento en particular dejará caer el ritmo, mientras que los demás tocan normalmente. Dejar caer el ritmo puede ser una forma interesante de crear un ritmo, pero no debería usarse en exceso. Otra forma de simular esto es mediante el uso de sliders en el upbeat o el offbeat.
```

2024-02-28 14:47 UTC, agatemosu commented on wiki/Music_theory/es.md
> +Aquí es donde el downbeat (usualmente) se omite o se "deja caer". Al omitir el downbeat en una canción más rápida, generalmente se crea tensión. A menudo, solo un instrumento en particular dejará cae
downbeat antes habias puesto acento

2024-02-28 14:53 UTC, JuanM4T commented on wiki/Music_theory/es.md
> +Un contratiempo, en inglés «upbeat», es una acentuación sincopada en el pulso desplazado. En un ritmo simple de 4/4, estos son los tiempos 2 y 4... En la música popular actual, generalmente se utiliz
> usa en utiliza
imo es igual de una manera o la otra pero bueno si te parece mejor yo lo cambio
```suggestion
Un contratiempo, en inglés «upbeat», es una acentuación sincopada en el pulso desplazado. En un ritmo simple de 4/4, estos son los tiempos 2 y 4... En la música popular actual, generalmente se usa el tambor de caja para tocar el patrón de contratiempo. Por eso, poner palmadas en los tiempos 2 y 4 suena bien. La mayoría de la música contemporánea usa un contratiempo de caja. Algunas canciones añadirán un bombo al contratiempo moviendo el segundo tiempo hacia arriba medio tiempo (entonces, los tiempos 2 y 3,5).
```

2024-02-28 14:54 UTC, JuanM4T commented on wiki/Music_theory/es.md
> +osu!, principalmente, es un juego de música, y los beatmaps suelen ser creados con la idea de ajustarse a la música, en lugar de adaptarse a un cierto BPM. En este breve ensayo trataré la teoría musi
```suggestion
osu! es, principalmente, un juego de música, y los beatmaps suelen ser creados con la idea de ajustarse a la música, en lugar de adaptarse a un cierto BPM. En este breve ensayo trataré la teoría musical en cuanto concierne a un beatmap en osu!, además de explicar por qué ciertas cosas suenan mal (al menos para mí). De ninguna manera se deben considerar estos asuntos como «pautas». Más bien, trátalos como teoría. La mayoría de las veces se aplicarán a algunas partes de las canciones, pero hay muchas excepciones. Todo lo que digo aquí es una opinión personal basada en más de 12 años de experiencia en bandas sinfónicas o tomada directamente de Wikipedia. No se puede aplicar a todas las formas de música, especialmente a cosas de vanguardia y a la mayoría de la música de Touhou (¿así que, la mitad de osu?)
```

2024-02-28 14:56 UTC, JuanM4T commented on wiki/Music_theory/es.md
> +Aquí es donde el downbeat (usualmente) se omite o se "deja caer". Al omitir el downbeat en una canción más rápida, generalmente se crea tensión. A menudo, solo un instrumento en particular dejará cae
```suggestion
Aquí es donde el downbeat (usualmente) se omite o se «deja caer». Al omitir el acento en una canción más rápida, generalmente se crea tensión. A menudo, solo un instrumento en particular dejará caer el ritmo, mientras que los demás tocan normalmente. Dejar caer el ritmo puede ser una forma interesante de crear un ritmo, pero no debería usarse en exceso. Otra forma de simular esto es mediante el uso de sliders en el contratiempo o a destiempo.
```

2024-02-28 17:13 UTC, UnknownOsu requested changes

2024-02-28 17:13 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +Mi definición de [overmapping](/wiki/Beatmapping/Overmapping) es colocar una nota o el final de un slider donde no hay una nota en el fondo. Hay algunas razones para prácticar el overmapping:
```suggestion
Mi definición de [overmapping](/wiki/Beatmapping/Overmapping) es colocar una nota o el final de un slider donde no hay una nota en el fondo. Hay varias razones para realizar el overmapping:
```

2024-02-28 17:13 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +- El ritmo es muy dificil para ser divertido o casual de jugar.
```suggestion
- El ritmo es muy difícil para ser divertido o casual de jugar.
```

2024-02-28 17:13 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +- La canción está en un compás de tiempo swing, pero el mapeador odia el 1/6.
```suggestion
- La canción está en un compás de tiempo swing, pero el mapper odia el 1/6.
```

2024-02-28 17:13 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +Si realmente quieres hacer overmapping debido a dificultad/diversión (la excusa más común), asegúrate de que no haya alguna otra forma de mapear las notas correctamente (como usando un slider inverso
```suggestion
Si realmente quieres hacer overmapping por razones de dificultad/diversión (la excusa más común), entonces asegúrate de que no hay otra forma de mapear las notas correctamente (como usar un slider inverso). Mapear un redoble de 1/6 con un slider inverso de 1/4 o 1/8 es simplemente incorrecto. Todos se juegan de manera idéntica, y la única diferencia es cómo suena y el impacto en la puntuación.
```

2024-02-28 18:30 UTC, JuanM4T commented on wiki/Music_theory/es.md
> +El acento es el impulso que ocurre al principio de un compás en la música medida. Su nombre en inglés, «downbeat», se deriva del golpe descendente del bastón del director o del conductor en el primer
no, si borras la referencia al nombre en inglés hablar de que el nombre deriva de llevar la batuta hacia abajo no tiene sentido alguno. preferiria dejar acento para mantener coherencia con la imagen

2024-02-28 18:33 UTC, JuanM4T commented on wiki/Music_theory/es.md
> +![Importante teoría musical](img/Music_Theory_Important.jpg "Importante teoría musical")
el inglés también estaba escrito de esta forma "Music theory important"

2024-02-28 18:49 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +El acento es el impulso que ocurre al principio de un compás en la música medida. Su nombre en inglés, «downbeat», se deriva del golpe descendente del bastón del director o del conductor en el primer
Ok, cambié lo que señalas.

Puse `tiempo fuerte` porque el texto se parece al [artículo](https://osu.ppy.sh/wiki/es/Music_theory/Downbeat), pero no se le llama `acento`

2024-04-28 21:25 UTC, UnknownOsu requested changes

2024-04-28 21:25 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +Los sliders inversos pueden ser muy interesantes, pero normalmente se tiende a añadir multiples repeticiones. Considero a los sliders inversos con más de una repetición confusos, porque normalmente l
```suggestion
Los sliders inversos pueden ser muy interesantes, pero normalmente se les tiende a añadir múltiples repeticiones. Considero a los sliders inversos con más de una repetición confusos, porque muchas veces la cuarta repetición no se muestra hasta que ya has pulsado el propio slider. Los sliders cortos y los largos no tienen este problema porque los sliders cortos se pueden predecir con facilidad, y los sliders largos te dan suficiente tiempo para reaccionar. Hay muy pocos casos en los que un slider inverso de 2 repeticiones funciona mejor que 2 sliders normales o 4 círculos.
```

2024-04-28 21:25 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +Una obvia excepción es en los streams largos donde un slider inverso es usado para reemplazar 4 círculos. Esto es probablemente mejor que usar sliders inversos de una repetición.
```suggestion
Una obvia excepción es en los streams largos, donde un slider inverso es usado para reemplazar 4 círculos. Esto es probablemente mejor que usar sliders inversos de una repetición.
```

2024-04-28 21:25 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +La mayoría de la música funciona en grupos de 2 o 4. 4 pulsos por compás, 4 compases por frase, etc. Mientras coloques un slider al inicio o un círculo en el acento (marca blanca larga) y a veces en
```suggestion
La mayoría de la música funciona en grupos de 2 o 4. 4 pulsos por compás, 4 compases por frase, etc. Mientras coloques un slider al inicio o un círculo en el acento (marca blanca larga) y a veces en medio de la frase, puedes poner cualquier cantidad de sliders a contratiempo o fuera de ritmo con patrones fuera de lo común, sliders muy cortos y streams a lo tonto en el mapa, incluso si no encajan con la canción. Es en serio. Obviamente no es del todo recomendable, ya que entonces podrías tomar cualquier canción con el mismo BPM y estructura, copiar y pegarla y obtener el mismo mapa de baja calidad. También es importante mapear junto a la música, pero la mayoría de la música simplemente se repite una y otra vez, así que es bueno incluir algo diferente de vez en cuando.
```

2024-04-28 21:25 UTC, UnknownOsu commented on wiki/Music_theory/es.md
> +Es sabido que al tocar la línea de bajo con cualquier instrumento, puedes crear casi cualquier ritmo y tocar cualquier nota siempre y cuando toques el acento en cada compás en la tonalidad adecuada.
```suggestion
Es sabido que al tocar la línea de bajo con cualquier instrumento, puedes crear casi cualquier ritmo y tocar cualquier nota, siempre y cuando toques el acento en cada compás en la tonalidad adecuada. Así de importante es el acento. Obviamente, no siempre es perfecto, pero al menos es aceptable.
```

2024-04-29 15:32 UTC, UnknownOsu approved these changes

2024-05-02 22:18 UTC, TicClick approved these changes

2024-05-02 22:21 UTC, merged