Add `MCNC/4K2023`] tournament article
ppy/osu-wiki pull request #11052
Opened 2024-03-01 03:18 UTC by cdwcgt

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] ~~*(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)~~

2024-03-01 10:26 UTC, iSlodinxOsu requested changes

2024-03-01 10:26 UTC, iSlodinxOsu commented on wiki/Tournaments/MCNC/4k2023/en.md
> +- [Discord Server](https://discord.gg/uBHK5vq)
```suggestion
- [Discord server](https://discord.gg/uBHK5vq)
```

2024-03-02 05:40 UTC, cdwcgt commented
is this really larger than 1MB?

2024-05-27 21:16 UTC, TicClick approved these changes
no visible issues, this should have been merged rather early -- apologies.
next time, don't hesitate to ping any maintainer in the `#osu-wiki` channel

2024-05-27 21:17 UTC, merged