Add current MWC and former MWC winners in `Users with unique titles`
ppy/osu-wiki pull request #11050
Opened 2024-02-29 23:55 UTC by iSlodinxOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-03-11 22:26 UTC, Walavouchey requested changes

2024-03-11 22:26 UTC, Walavouchey commented on wiki/People/Users_with_unique_titles/en.md
>  | [MWC 7K 2022](/wiki/Tournaments/MWC/2022_7K) | Former osu!mania 7K Champion: 2022 | ::{ flag=KR }:: [0133](https://osu.ppy.sh/users/12346181), ::{ flag=KR }:: [dressurf](https://osu.ppy.sh/users/75
gotta remove these too

```suggestion
| [MWC 7K 2022](/wiki/Tournaments/MWC/2022_7K) | Former osu!mania 7K Champion: 2022 | ::{ flag=KR }:: [0133](https://osu.ppy.sh/users/12346181), ::{ flag=KR }:: [Estonians](https://osu.ppy.sh/users/7014697) |
```

2024-03-12 02:42 UTC, Walavouchey commented
(in the translations too)

2024-03-12 04:55 UTC, iSlodinxOsu commented
> (in the translations too)

I forgot... will do that later

2024-03-12 15:30 UTC, Walavouchey approved these changes

2024-03-12 15:32 UTC, merged