Add Spring 2024 Mentorship Signups newspost
ppy/osu-wiki pull request #11059
Opened 2024-03-02 22:52 UTC by yaspo

Will be updated to contain the relevant forum post shortly, another team member is in the process of creating it

2024-03-02 23:04 UTC, iSlodinxOsu requested changes

2024-03-02 23:04 UTC, iSlodinxOsu commented on news/2024/2024-03-05-community-mentorship-program-spring-2024-signups-now-open.md
> +Over the course of a cycle, you'll have the opportunity to learn from your mentor, participate in various mentorship events (like contests), hang out with fellow mentees, and more! Even guests can ta
```suggestion
Over the course of a cycle, you'll have the opportunity to learn from your mentor, participate in various mentorship events (like contests), hang out with fellow mentees, and more! Even guests can take part in the learning process. [Our Discord server](https://discord.gg/EvHqwvD) has feedback and question channels dedicated to helping newcomers to our community.
```

2024-03-04 13:53 UTC, Walavouchey requested changes

2024-03-04 13:53 UTC, Walavouchey commented on news/2024/2024-03-05-community-mentorship-program-spring-2024-signups-now-open.md
> +Throughout this cycle, the organization team will host various events on the Mentorship Discord server, engaging and offering events for mentees and mentors to participate in. These include feedback
```suggestion
Throughout this cycle, the organisation team will host various events on the Mentorship Discord server, engaging and offering events for mentees and mentors to participate in. These include feedback lobbies, mapping contests, and more! Some of our previous mapping puzzles can be found here in [this thread](https://osu.ppy.sh/community/forums/topics/565382), and previous discussions can be found [here](https://osu.ppy.sh/community/forums/topics/514122).
```

2024-03-04 13:53 UTC, Walavouchey commented on news/2024/2024-03-05-community-mentorship-program-spring-2024-signups-now-open.md
> +-Mentorship Organisation Team
```suggestion
—the Mentorship Organisation Team
```

2024-03-04 18:30 UTC, Walavouchey approved these changes

2024-03-04 20:13 UTC, merged