[ZH] Update `Upgrading_to_lazer`
ppy/osu-wiki pull request #11074
Opened 2024-03-07 09:46 UTC by Proxyerium

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-03-07 09:48 UTC, Proxyerium commented
模组那边的一些名词没有翻译，打算先等lazer翻译後在跟进

2024-03-09 11:14 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +- Difficulty reduction
`Difficulty reduction / increase` 在稳定版及相关文章 (`Gameplay/Game modifier`) 中已有翻译（降低/增加难度），可以考虑使用

2024-03-09 11:14 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +- System
这个是内部计算分数时自动添加的模组分类，可译为“系统”

2024-03-09 11:14 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +  - Hard Rock (不适用osu!mania)
```suggestion
  - Hard Rock (osu!mania 不适用)
```

2024-03-09 11:28 UTC, CloneWith requested changes

2024-03-09 11:28 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +我们会尽量地多保留成绩，但我们**不保证能永久保留成绩**。我们随时可能会删除一小部分分数，为确保游戏平衡，比如发现了滥用或作弊得来的分数。
```suggestion
我们会尽量地多保留分数，但我们**不保证能永久保留分数**。为确保游戏平衡，我们随时可能会删除一小部分分数，比如发现了滥用或作弊得来的分数时。
```

分数和成绩都是同一个概念，这里应选用其一。

2024-03-09 11:28 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +  - Half Time (仅 0.75 倍速，可以调整 `Adjust pitch `)
```suggestion
  - Half Time (仅 0.75 倍速，可以调整 `Adjust pitch`)
```

2024-03-09 11:28 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
缺少一行 L223

“除非特别指出，只有模组的自定义设置为默认值时才有资格获得表现分。”

2024-03-09 13:30 UTC, CloneWith approved these changes

2024-03-11 23:48 UTC, TicClick approved these changes

2024-03-11 23:50 UTC, merged