[ZH] Update `Game mode/osu!taiko`
ppy/osu-wiki pull request #11071
Opened 2024-03-06 14:04 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-03-06 16:45 UTC, RushFTK requested changes
Review translations

2024-03-06 16:45 UTC, RushFTK commented on wiki/Game_mode/osu!taiko/zh.md
> +osu!taiko 是 osu! 中的，基于日本节奏游戏[太鼓达人](https://zh.wikipedia.org/wiki/Taiko_no_Tatsujin)系列（在北美的发行名为[Taiko: Drum Master](https://zh.wikipedia.org/wiki/Taiko:_Drum_Master)）的游戏模式。
```suggestion
osu!taiko 是基于日本节奏游戏[太鼓达人](https://zh.wikipedia.org/wiki/Taiko_no_Tatsujin)系列（在北美的发行名为[Taiko: Drum Master](https://zh.wikipedia.org/wiki/Taiko:_Drum_Master)）的 osu! 游戏模式。
```

2024-03-06 16:45 UTC, RushFTK commented on wiki/Game_mode/osu!taiko/zh.md
> +屏幕会分成两个不同部分；上半部分含有游戏元素，而下半部分含有谱面的背景图片或视频。上半部分有血条，它不像其他游戏模式一样，而在开始时是空的，必须填到至少 50% 满才能通过难度。血条下方的中上区域左侧有一个太鼓，旁边是传送带，将打击物件从右侧输送到左侧。期间，打击物件会通过太鼓旁的判定圈。太鼓上方是太鼓的动画吉祥物（也被叫做 pippidon 或咚），它会根据谱面是否处于 Kiai 段落，以及连
```suggestion
屏幕会分成两个不同部分；上半部分含有游戏元素，而下半部分含有谱面的背景图片或视频。在上半部分，有一个与其他游戏模式不一样的血条，其在开始时是空的，必须填到至少 50% 满才能通过难度。血条下方的中上区域左侧有一个太鼓，旁边是传送带，将打击物件从右侧输送到左侧。期间，打击物件会通过太鼓旁的判定圈。太鼓上方是太鼓的动画吉祥物（也被叫做 pippidon 或咚），它会根据谱面是否处于 Kiai 段落，以及连击数达到里程碑时做出相应的反应。如果在 Kiai 时间内出现失误，则传送带背景会变换颜色。最后，右上角有常见的分数、准确度和谱面计时器。
```

2024-03-06 16:45 UTC, RushFTK commented on wiki/Game_mode/osu!taiko/zh.md
> +请注意，osu!taiko 中，是不存在自然掉血的，因此，只有打击物件会影响到血条。不像 osu! 模式一样，osu!taiko 模式的连击里程碑是每 50 连击出现一次。打击物件的分数会从连击数大于 10 之后开始增长，但这个增长趋势会在连击数大于 100 后停止（被当前最大连击限制）。如果断连，打击物件的分数会回到基础分。在 *Kiai 时间*内，玩家能获得额外的 20% 物件分数。通过打击
```suggestion
请注意，osu!taiko 中不存在自然掉血，因此，只有打击物件会影响到血条。不像 osu! 模式一样，osu!taiko 模式的连击里程碑是每 50 连击出现一次。打击物件的分数会从连击数大于 10 之后开始增长，但这个增长趋势会在连击数大于 100 后停止（能获得的最高奖励分的最大连击）。如果断连，打击物件的分数会回到基础分。在 *Kiai 时间*内，玩家能获得额外的 20% 物件分数。通过打击物件获得的单一物件分能够在右上角准确度下方的红色数字看到。
```

2024-03-06 16:45 UTC, RushFTK commented on wiki/Game_mode/osu!taiko/zh.md
> +请注意，osu!taiko 中，是不存在自然掉血的，因此，只有打击物件会影响到血条。不像 osu! 模式一样，osu!taiko 模式的连击里程碑是每 50 连击出现一次。打击物件的分数会从连击数大于 10 之后开始增长，但这个增长趋势会在连击数大于 100 后停止（被当前最大连击限制）。如果断连，打击物件的分数会回到基础分。在 *Kiai 时间*内，玩家能获得额外的 20% 物件分数。通过打击
>...The base score will be boosted after obtaining a combo that is a multiple of 10, ***but stops at 100 (max combo limit for the boost)*** If the combo is broken, the boost resets back to the base score. ...
guess "max combo" here refers to the 100.
not means if a diff's max combo lower 500 the bonus won't reach 100.
我认为这里更多指100是最高连击奖励分。

2024-03-06 16:45 UTC, RushFTK commented on wiki/Game_mode/osu!taiko/zh.md
> +  - 红色大音符对应使用了镲 (Finish) 音效的圆圈。
```suggestion
  - 红色大音符需添加镲 (Finish) 音效。
```

2024-03-06 16:45 UTC, RushFTK commented on wiki/Game_mode/osu!taiko/zh.md
> +  - 蓝色大音符对应同时使用了镲 (Finish) 和哨声/掌声音效的圆圈。
```suggestion
  - 蓝色大音需同时添加镲 (Finish) 和哨声/掌声音效。
```

2024-03-06 19:20 UTC, YumeMuzi commented on wiki/Game_mode/osu!taiko/zh.md
> +  - 蓝色大音符对应同时使用了镲 (Finish) 和哨声/掌声音效的圆圈。
你自己都掉东西了？符呢？

2024-03-06 19:24 UTC, YumeMuzi commented on wiki/Game_mode/osu!taiko/zh.md
> +  - 红色大音符对应使用了镲 (Finish) 音效的圆圈。
我个人认为这里翻译成对应关系更好，因为音效和音符颜色并不是原文中的那种关系。

2024-03-06 20:13 UTC, RushFTK commented on wiki/Game_mode/osu!taiko/zh.md
> +  - 红色大音符对应使用了镲 (Finish) 音效的圆圈。
那换个语序呢，例如:  
普通圆圈为红色音符  
添加音效为红色大音符  
(手机不好回复review)

2024-03-12 16:19 UTC, YumeMuzi commented on wiki/Game_mode/osu!taiko/zh.md
> +  - 红色大音符对应使用了镲 (Finish) 音效的圆圈。
其实差不多的
no difference

2024-03-12 19:54 UTC, RushFTK approved these changes

2024-03-12 19:56 UTC, TicClick approved these changes

2024-03-12 19:58 UTC, merged