[ES] Add `osu! tournament client/osu!tourney/Multiplayer usage`
ppy/osu-wiki pull request #11093
Opened 2024-03-10 21:48 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-03-22 15:38 UTC, agatemosu requested changes
image not necessary, the image shows the order, not the text

2024-04-16 21:59 UTC, TicClick approved these changes
@agatemosu @UnknownOsu as long as ^ was the only comment, you can merge this one in freely

2024-04-16 23:16 UTC, UnknownOsu commented
I still think the image was fine.

In the end, the wiki is being translated into Spanish, I think it wouldn't hurt if the images had as much Spanish as possible. But well, as you see best.

I checked it again to see if there is any error, but I didn't see anything serious that requires a change. I don't know if agatem is going to review it to see if there is anything that seems wrong in the article, so... I guess someone can merge it when they can

2024-04-18 07:56 UTC, TicClick approved these changes

2024-04-18 08:01 UTC, merged