[ES] Update `Language Surveillance Division`
ppy/osu-wiki pull request #11115
Opened 2024-03-16 10:27 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-03-16 19:13 UTC, UnknownOsu requested changes

2024-03-16 19:13 UTC, UnknownOsu commented on wiki/People/Language_Surveillance_Division/es.md
> +# Language Surveillance Division
```suggestion
# División de Vigilancia Lingüística
```

2024-03-16 19:13 UTC, UnknownOsu commented on wiki/People/Language_Surveillance_Division/es.md
> +# Language Surveillance Division
Creo que queda mejor en español

2024-03-16 19:13 UTC, UnknownOsu commented on wiki/People/Language_Surveillance_Division/es.md
> +La **Language Surveillance Division** (coloquialmente conocida como *LSD*) era un grupo de usuarios responsable de la moderación de comunidades de idiomas específicos dentro de osu!. Cada uno de sus
```suggestion
La **División de Vigilancia Lingüística** (coloquialmente conocida como *LSD*) era un grupo de usuarios responsable de la moderación de comunidades de idiomas específicos dentro de osu!. Cada uno de sus miembros tenía un área de enfoque dedicada: un canal de idioma en el que estaban presentes principalmente y las secciones respectivas del foro que podían administrar (como lugares como [Help](https://osu.ppy.sh/community/forums/5) u [Off-Topic](https://osu.ppy.sh/community/forums/52)).
```

2024-03-16 19:13 UTC, UnknownOsu commented on wiki/People/Language_Surveillance_Division/es.md
> +El LSD también sirvió como un grupo intermediario para miembros prometedores pendientes de admisión en el [Global Moderation Team](/wiki/People/Global_Moderation_Team) en ocasiones, ya que los dos gr
```suggestion
La LSD también sirvió como un grupo intermediario para miembros prometedores pendientes de admisión en el [Global Moderation Team](/wiki/People/Global_Moderation_Team) en ocasiones, ya que los dos grupos generalmente compartían un objetivo común y conjuntos de habilidades similares.
```

2024-03-16 19:13 UTC, UnknownOsu commented on wiki/People/Language_Surveillance_Division/es.md
> +Después de una [reestructuración del personal](https://osu.ppy.sh/community/forums/topics/123510) en 2013, la Language Surveillance Division pasó a llamarse **Chat Moderators** y recibió su propia li
```suggestion
Después de una [reestructuración del personal](https://osu.ppy.sh/community/forums/topics/123510) en 2013, la División de Vigilancia Lingüística pasó a llamarse **Chat Moderators** y recibió su propia lista de miembros.
```

2024-03-16 19:13 UTC, UnknownOsu commented on wiki/People/Language_Surveillance_Division/es.md
> +El [20 de agosto de 2015](/wiki/People/Staff_log/2015#agosto), los equipos Chat Moderators y Global Moderation [se fusionaron](https://osu.ppy.sh/community/forums/posts/4435972), dando efectivamente
```suggestion
El [20 de agosto de 2015](/wiki/People/Staff_log/2015#agosto), los equipos de Chat Moderators y Global Moderation [se fusionaron](https://osu.ppy.sh/community/forums/posts/4435972), dando efectivamente a todos los moderadores apodos rojos distintivos en el chat y poder de administración sobre todo el foro.
```

2024-04-13 17:10 UTC, UnknownOsu requested changes

2024-04-13 17:10 UTC, UnknownOsu commented on wiki/People/Language_Surveillance_Division/es.md
> +La **División de Vigilancia Lingüística** (coloquialmente conocida como *LSD*) era un grupo de usuarios responsable de la moderación de comunidades de idiomas específicos dentro de osu!. Cada uno de
```suggestion
La **División de Vigilancia Lingüística** (coloquialmente conocida como *LSD*) era un grupo de usuarios responsable de la moderación de comunidades de idiomas específicos dentro de osu!. Cada uno de sus miembros tenía un área de enfoque dedicada: un canal de idioma en el que estaban presentes principalmente y las secciones respectivas del foro que podían administrar (lugares como [Help](https://osu.ppy.sh/community/forums/5) u [Off-Topic](https://osu.ppy.sh/community/forums/52)).
```

2024-04-13 17:41 UTC, UnknownOsu approved these changes

2024-04-15 14:50 UTC, Walavouchey approved these changes

2024-04-15 14:56 UTC, merged