Staff page updates for March 2024
ppy/osu-wiki pull request #11128
Opened 2024-03-19 07:55 UTC by Laurakko

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-03-19 07:59 UTC, Walavouchey requested changes

2024-03-19 07:59 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/es.md
> +<!-- NOTE FOR TRANSLATORS: Translating this section is different from other parts of the osu! wiki. See https://github.com/ppy/osu-wiki/blob/master/meta/group-info/TRANSLATING.md#group-articles. -->
revert

2024-03-19 07:59 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/fr.md
> +<!-- NOTE FOR TRANSLATORS: Translating this section is different from other parts of the osu! wiki. See https://github.com/ppy/osu-wiki/blob/master/meta/group-info/TRANSLATING.md#group-articles. -->
revert

2024-03-19 07:59 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/zh.md
> +<!-- NOTE FOR TRANSLATORS: Translating this section is different from other parts of the osu! wiki. See https://github.com/ppy/osu-wiki/blob/master/meta/group-info/TRANSLATING.md#group-articles. -->
revert

2024-03-19 08:56 UTC, Walavouchey requested changes

2024-03-19 08:56 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/en.md
> +| ::{ flag=UK }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
wrong flag, should be GB

2024-03-19 08:56 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/en.md
> +| ::{ flag=TW }:: [MuChin](https://osu.ppy.sh/users/9834516) | Chinese |
should be Muchin

2024-03-19 17:57 UTC, RoanH commented on wiki/People/Global_Moderation_Team/en.md
> +[^task-mao]: While not actually being part of the GMT itself, mangomizer is in the user group by technicality due to needing GMT-level permissions for access to internal forums.
I assume the name needs to be updated:
```suggestion
[^task-mao]: While not actually being part of the GMT itself, Mao is in the user group by technicality due to needing GMT-level permissions for access to internal forums.
```

2024-03-21 03:26 UTC, Laurakko commented on wiki/People/Beatmap_Nominators/en.md
> +| ::{ flag=UK }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
fixed

2024-03-21 03:26 UTC, Laurakko commented on wiki/People/Beatmap_Nominators/en.md
> +| ::{ flag=TW }:: [MuChin](https://osu.ppy.sh/users/9834516) | Chinese |
fixed

2024-03-21 03:27 UTC, Laurakko commented on wiki/People/Global_Moderation_Team/en.md
> +[^task-mao]: While not actually being part of the GMT itself, mangomizer is in the user group by technicality due to needing GMT-level permissions for access to internal forums.
changed to be correct

2024-03-21 14:22 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/es.md
> +| ::{ flag=UK }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
```suggestion
| ::{ flag=GB }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
```

2024-03-21 14:22 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/fr.md
> +| ::{ flag=UK }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
```suggestion
| ::{ flag=GB }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
```

2024-03-21 14:22 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/zh.md
> +| ::{ flag=UK }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
```suggestion
| ::{ flag=GB }:: [ckharv](https://osu.ppy.sh/users/9967026) |  |
```

2024-03-21 14:22 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/es.md
> +| ::{ flag=TW }:: [MuChin](https://osu.ppy.sh/users/9834516) | Chino |
```suggestion
| ::{ flag=TW }:: [Muchin](https://osu.ppy.sh/users/9834516) | Chino |
```

2024-03-21 14:22 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/fr.md
> +| ::{ flag=TW }:: [MuChin](https://osu.ppy.sh/users/9834516) | Chinois |
```suggestion
| ::{ flag=TW }:: [Muchin](https://osu.ppy.sh/users/9834516) | Chinois |
```

2024-03-21 14:22 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/zh.md
>  | ::{ flag=TW }:: [MuChin](https://osu.ppy.sh/users/9834516) | 汉语 |
```suggestion
| ::{ flag=TW }:: [Muchin](https://osu.ppy.sh/users/9834516) | 汉语 |
```

2024-03-21 14:37 UTC, Walavouchey commented on wiki/People/osu!_Alumni/en.md
> +| ::{ flag=US }:: [-NoName-](https://osu.ppy.sh/users/10400730) |  | GMT |
one cell too many, applies to all translations too

```suggestion
| ::{ flag=US }:: [-NoName-](https://osu.ppy.sh/users/10400730) | GMT |
```

2024-03-21 20:36 UTC, Walavouchey approved these changes

2024-03-21 20:37 UTC, merged