add `zh.md`
ppy/osu-wiki pull request #11139
Opened 2024-03-20 08:06 UTC by Proxyerium

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-03-22 01:23 UTC, YumeMuzi requested changes
记得中英文之间加空格。
it's necessary to add an extra space between EN and ZH text.

2024-03-22 01:23 UTC, YumeMuzi commented on wiki/Beatmap/Converts/zh.md
> +**转谱** 是指 osu! 客户端按照规则，将一个[谱面](/wiki/Beatmap)的特定[模式](/wiki/Game_mode)，转换成本没有的其他模式的谱面。所有转谱都是基于原谱呈现的参数自动生成的。
```suggestion
**转谱** 是指 osu! 客户端按照规则，将一张特定[游戏模式](/wiki/Game_mode)的[谱面](/wiki/Beatmap)，转换成原本没有的，其他模式的谱面。所有转谱都是基于原谱呈现的参数自动生成的。
```

2024-03-22 01:23 UTC, YumeMuzi commented on wiki/Beatmap/Converts/zh.md
> +目前, osu! 支持由[osu!standard](/wiki/Game_mode/osu!)转换成[osu!taiko](/wiki/Game_mode/osu!taiko)、[osu!catch](/wiki/Game_mode/osu!catch)和 [osu!mania](/wiki/Game_mode/osu!mania)。
```suggestion
目前, osu! 支持由 [osu!standard](/wiki/Game_mode/osu!) 转换成 [osu!taiko](/wiki/Game_mode/osu!taiko)、[osu!catch](/wiki/Game_mode/osu!catch) 和 [osu!mania](/wiki/Game_mode/osu!mania)。
```

2024-03-22 01:23 UTC, YumeMuzi commented on wiki/Beatmap/Converts/zh.md
> +  - **既**设置了结束音效，**也**设置了哨声、掌声或两者的，转换成大蓝色音符；
```suggestion
  - **既**设置了结束音效，**也**设置了哨声、掌声（或哨声掌声均含有）的，转换成大蓝色音符；
```

2024-03-22 01:23 UTC, YumeMuzi commented on wiki/Beatmap/Converts/zh.md
> +- 圆圈和短滑条（例如[1/4时值的滑条](/wiki/Client/Beatmap_editor/Beat_snap_divisor)）转换为普通音符；
```suggestion
- 圆圈和短滑条（例如 [1/4 时值的滑条](/wiki/Client/Beatmap_editor/Beat_snap_divisor)）转换为普通音符；
```

2024-03-22 01:23 UTC, YumeMuzi commented on wiki/Beatmap/Converts/zh.md
> +此外， osu!mania 的转谱还会特别地根据原谱的难度转成[4K，5K或7K](/wiki/Gameplay/Game_modifier/xK)。
```suggestion
此外， osu!mania 的转谱还会特别地根据原谱的难度转成 [4K，5K 或 7K](/wiki/Gameplay/Game_modifier/xK)。
```

2024-03-22 14:06 UTC, Proxyerium commented
总会在某些地方眼瞎。
forgive my carelessness.

2024-03-23 15:08 UTC, YumeMuzi approved these changes

2024-03-26 17:48 UTC, TicClick approved these changes

2024-03-26 17:50 UTC, merged