[ES] Update `Writting`
ppy/osu-wiki pull request #11165
Opened 2024-03-24 17:57 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-03-24 18:29 UTC, UnknownOsu approved these changes

2024-03-24 18:35 UTC, UnknownOsu requested changes

2024-03-24 18:35 UTC, UnknownOsu commented on wiki/Article_styling_criteria/Writing/es.md
> +- `Free Mod` `FM`
```suggestion
- `Free Mod` o `FM`
```

2024-03-24 18:36 UTC, UnknownOsu commented on wiki/Article_styling_criteria/Writing/es.md
> +- `Free Mod` `FM`
Si quieres, puedes cambiar los `utilizar` por `usar`.

También hay un `%` que está junto a un número

2024-03-27 11:58 UTC, Walavouchey submitted a review, later dismissed

2024-03-27 11:59 UTC, agatemosu commented
wait

2024-03-27 11:59 UTC, agatemosu commented
he sent a patch on discord

2024-03-27 12:04 UTC, agatemosu commented on wiki/Article_styling_criteria/Writing/es.md
> +Se debe evitar `tú` y `tu`. No se debe usar `yo`. No se debe usar `nosotros`, `él` y `ella` (consulta arriba para otros términos).
@UnknownOsu

2024-03-27 14:46 UTC, UnknownOsu commented on wiki/Article_styling_criteria/Writing/es.md
>  > pls disfrutar juego
Queda raro como está puesto, los otros idiomas también lo tradujeron para darle mejor coherencia

2024-03-27 14:51 UTC, agatemosu commented on wiki/Article_styling_criteria/Writing/es.md
>  > pls disfrutar juego
en inglés está así, se entiende pero está mal escrito

2024-03-27 14:58 UTC, UnknownOsu commented on wiki/Article_styling_criteria/Writing/es.md
>  > pls disfrutar juego
Lo único que está "mal" escrito en el artículo inglés es el `plz`, no lo demás.

Si no te convence y te parece mucha formalidad, puedes al menos darle una mejor coherencia; algo como: `pls disfruta el juego` o similar

2024-04-13 08:22 UTC, agatemosu commented on wiki/Article_styling_criteria/Writing/es.md
>  > pls disfrutar juego
a "enjoy game" le faltaría un "the" para que esté bien

2024-04-13 16:44 UTC, UnknownOsu commented on wiki/Article_styling_criteria/Writing/es.md
>  > pls disfrutar juego
Yo lo decía más por la coherencia, porque está traducido de manera literal y no queda tan bien leerlo de esa manera.

Los otros idiomas también le dieron coherencia a la frase para que no quede tan "mal" redactada al momento de traducirla

2024-04-13 17:10 UTC, UnknownOsu approved these changes

2024-04-15 14:58 UTC, Walavouchey approved these changes

2024-04-15 15:00 UTC, merged