Add `The Followpoint: DigitalHypno, the osu! Professor` news post
ppy/osu-wiki pull request #11200
Opened 2024-04-03 18:03 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-04-03 18:36 UTC, Walavouchey requested changes

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +*What is the story behind the symmetrical play count graph in your profile?*
should include an image

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +> There was one time where I even flagged osu!'s auto-restriction for gaining play count too quickly, causing my account to be restricted for a few hours and disabled for a few minutes. Shoutout to [
any mention of restrictions has historically been a no-go

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +*You've got a lot of badges from tournaments, what made you start playing tournaments and do you feel like you have encouraged others to start playing tournaments as well?*
```suggestion
*You've got a lot of badges from tournaments. What made you start playing tournaments and do you feel like you have encouraged others to start playing tournaments as well?*
```

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +> To help solve this problem, I designed a seeding system in 2018 called Badge Weighted Seeding (BWS), a seeding formula that artificially increases your rank based on how many tournament badges you
```suggestion
> To help solve this problem, I designed a seeding system in 2018 called [Badge Weighted Seeding (BWS)](/wiki/Tournaments/Badge-weighted_seeding), a seeding formula that artificially increases your rank based on how many tournament badges you have. Tournament badges come from winning tournaments, so the idea is that the more badges you have, the more likely it is that you shouldn't be playing in rank restricted tournaments anymore. Despite not being a perfect solution, I believe it solves a lot of the problems that used to exist.
```

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +> It's absolutely possible, especially with recent developments such as the [Tournament Committee](/wiki/People/Tournament_Committee), a group of seasoned tournament staff members that work to improv
```suggestion
> It's absolutely possible, especially with recent developments such as the [Tournament Committee](/wiki/People/Tournament_Committee), a group of seasoned tournament staff members that work to improve the quality of osu! tournaments, and people like [BTMC](https://osu.ppy.sh/users/3171691) that are always finding ways to take competitive osu! to the next level.
```

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +>I'm sure I'll be back to playing osu! more regularly one day. This community will always feel like home to me, and as with most people who have been around here long enough, I'm forever indebted to
```suggestion
> I'm sure I'll be back to playing osu! more regularly one day. This community will always feel like home to me, and as with most people who have been around here long enough, I'm forever indebted to this game for all the people I've met and all the experiences I've had. Thank you for the interview!
```

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +*Bonus question: Can you cook a steak?*
colons aren't like periods, as in they don't end sentences

```suggestion
*Bonus question: can you cook a steak?*
```

2024-04-03 18:36 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +
```suggestion

For the three people who are out of the loop regarding who this "BTMC" person mentioned here is, you'll probably want to read [his interview](https://osu.ppy.sh/home/news/2024-03-13-the-followpoint-btmc-the-face-of-osu). More likely though, if you're out of the loop regarding this "steak" business, [this YouTube video](https://www.youtube.com/watch?v=0B6TyWML0zg) (and its comment section) may clarify that.

```

2024-04-03 18:38 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +Welcome or welcome back to The Followpoint, a "Community Spotlight" series where we interview various players and community figures to get to know them better!
```suggestion
Welcome or welcome back to The Followpoint, a "community spotlight" series where we interview various players and community figures to get to know them better!
```

2024-04-03 19:26 UTC, Walavouchey commented on news/2024/2024-04-04-the-followpoint-digitalhypno-the-osu-professor.md
> +Today we are joined by DigitalHypno (a.k.a. honmi), who is known for their achievements and contributions, such as winning many tournaments, their content about osu!, as well as their contributions t
```suggestion
Today we are joined by [DigitalHypno](https://osu.ppy.sh/users/4384207) (a.k.a. honmi), who is known for their achievements and contributions, such as winning many tournaments, their content about osu!, as well as their contributions to Project Loved, Beatmap Spotlights and the osu! tournaments scene.
```

2024-04-03 20:03 UTC, Walavouchey requested changes
i'm usually not too picky to proofread interviewee answers but digitalhypno said it's ok

2024-04-03 21:05 UTC, DigitalHypno reviewed
some minor wording changes

2024-04-04 03:00 UTC, peppy approved these changes

2024-04-04 03:00 UTC, merged