all usergroup changes until uberzolik alumni
ppy/osu-wiki pull request #11209
Opened 2024-04-06 21:22 UTC by Laurakko

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-04-06 21:42 UTC, Walavouchey commented on wiki/People/Beatmap_Nominators/es.md
> +<!-- NOTE FOR TRANSLATORS: Translating this section is different from other parts of the osu! wiki. See https://github.com/ppy/osu-wiki/blob/master/meta/group-info/TRANSLATING.md#group-articles. -->
again <.<

2024-04-06 23:45 UTC, aceticke requested changes
Noticed some errors, but because of GitHub's review system I can't put comments on some of the lines that need fixing. Please don't merge until I can work with Laurakko one-to-one.

2024-04-07 03:18 UTC, aceticke approved these changes

2024-04-07 21:50 UTC, Walavouchey approved these changes

2024-04-07 21:53 UTC, merged