[ZH] Update `How you can help!`
ppy/osu-wiki pull request #11214
Opened 2024-04-07 20:59 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-08 03:28 UTC, CloneWith approved these changes
一些段落开头的单空格缩进等等是之前已有的问题，这里先提出来了，可以改

2024-04-08 03:28 UTC, CloneWith commented on wiki/Community/How_you_can_help!/zh.md
> +- 尽量调解负能量，并将其转变为正能量。
“调解”用在这里不是很合适（对双方/争论或纠纷），可以换成“消解”或“消减”

2024-04-08 03:28 UTC, CloneWith commented on wiki/Community/How_you_can_help!/zh.md
> +- [举报你看到的作弊玩家](/wiki/Reporting_bad_behaviour/Handling_foul_play)。不要填写模糊不清的备注，这无法在几分钟到几小时内解决你的问题，比如 `!report <某人> 好像在作弊`。
没看到原文有这样改，不过也没错？

```
这无法在几分钟到几小时内解决你的问题，比如 `!report <某人> 好像在作弊`。
```
这里有些奇怪，如果语意正确，可改成“这无法及时解决问题”。

---

原文 @ 20240329：
Please do not complain about them through other mediums as a simple `!report <username> seems to be cheating` can fix your problems within minutes to hours.

2024-04-08 03:28 UTC, CloneWith commented on wiki/Community/How_you_can_help!/zh.md
>  古人有云：你应该成为解决问题的方案，而不是成为问题本身。只要能做到这点，你就是在帮助 osu! 社区变得更加积极向上！抱怨的人总会有的，但你仍然能用很多方式来点亮社区的心情：
“你应该成为问题解决方案的一部分”
“点亮社区的心情”，建议改成“改善...氛围”

2024-04-08 03:37 UTC, CloneWith requested changes
点错了（

2024-04-08 03:37 UTC, CloneWith commented on wiki/Community/How_you_can_help!/zh.md
> +## 帮助或加入玩家自发组织的社区项目：
```suggestion
## 帮助或加入玩家自发组织的社区项目
```

2024-04-08 03:37 UTC, CloneWith commented on wiki/Community/How_you_can_help!/zh.md
>  大家都乐于进步，并且时常需要游玩上的反馈。玩家们经常会在[游戏与排名板块](https://osu.ppy.sh/community/forums/13)征询自己游戏表现的反馈，还有人会在[制作中皮肤板块](https://osu.ppy.sh/community/forums/119)急切等待自己崭新皮肤的相关反馈。
```suggestion
大家都乐于进步，并且时常需要反馈。玩家们经常会在[游戏与排名板块](https://osu.ppy.sh/community/forums/13)征询自己游戏表现的反馈，还有人会在[制作中皮肤板块](https://osu.ppy.sh/community/forums/119)急切等待关于自己新近制作皮肤的反馈。
```
“latest skin creation”，自己最近制作的皮肤

2024-05-27 21:10 UTC, TicClick commented
hey, is there something else remaining to be done here?

2024-06-20 01:10 UTC, CloneWith commented
There are some suggestions waiting for his opinions, either to be resolved or dismissed.

@YumeMuzi would you like to have a look on this?

2024-06-24 07:02 UTC, YumeMuzi commented
> hey, is there something else remaining to be done here?

I'm not busy now, and it's time to push it

2024-06-24 07:04 UTC, CloneWith approved these changes

2024-07-12 20:43 UTC, TicClick approved these changes

2024-07-12 20:43 UTC, merged