Update `Contest points` and `Official beatmapping contest support`
ppy/osu-wiki pull request #11218
Opened 2024-04-08 19:27 UTC by Hiviexd

changes were discussed and approved by the contest committee

2024-04-08 19:34 UTC, MChecaH requested changes
Change to a more appropriate preposition.

2024-04-08 19:34 UTC, MChecaH commented on wiki/Contests/Contest_points/en.md
> +For solo contests, contest points are based on how many valid submissions are created. These are the general guidelines for point distribution, and exceptions may be granted on a case-by-case basis w
```suggestion
For solo contests, contest points are based on how many valid submissions are created. These are the general guidelines for point distribution, and exceptions may be granted on a case-by-case basis at the discretion of the [Contest Committee](/wiki/People/Tournament_Committee#contest-committee) when requesting official beatmapping contest support.
```

2024-04-08 19:34 UTC, MChecaH commented on wiki/Contests/Official_support/en.md
> +- [^exception-note]: Exceptions may be granted on a case-by-case basis with the discretion of the [Contest Committee](/wiki/People/Tournament_Committee#contest-committee).
```suggestion
- [^exception-note]: Exceptions may be granted on a case-by-case basis at the discretion of the [Contest Committee](/wiki/People/Tournament_Committee#contest-committee).
```

2024-04-08 19:48 UTC, MChecaH approved these changes

2024-04-09 09:34 UTC, Walavouchey requested changes

2024-04-09 09:34 UTC, Walavouchey commented on wiki/Contests/Official_support/en.md
> +- [^exception-note]: Exceptions may be granted on a case-by-case basis at the discretion of the [Contest Committee](/wiki/People/Tournament_Committee#contest-committee).
incorrect formatting

```suggestion
[^exception-note]: Exceptions may be granted on a case-by-case basis at the discretion of the [Contest Committee](/wiki/People/Tournament_Committee#contest-committee).
```

2024-04-09 09:35 UTC, Walavouchey approved these changes

2024-04-09 09:38 UTC, merged