[IT] Update `Upgrading_to_lazer`
ppy/osu-wiki pull request #11241
Opened 2024-04-13 16:25 UTC by marcostudios

PP on lazer is real 🎉

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-13 16:33 UTC, Sclafus requested changes

2024-04-13 16:33 UTC, Sclafus commented on wiki/Help_centre/Upgrading_to_lazer/it.md
> +Anche se cercheremo di preservare il maggior numero possibile di punteggi, **non garantiamo che i punteggi rimarranno a tempo indeterminato**. In qualsiasi momento potremmo decidere di cancellare un
```suggestion
Anche se cercheremo di preservare il maggior numero possibile di punteggi, **non garantiamo che i punteggi rimarranno a tempo indeterminato**. In qualsiasi momento potremmo decidere di cancellare un sottoinsieme di punteggi per preservare l'equilibrio del gioco, come quando vengono scoperti exploit o comportamenti scorretti.
```

2024-04-13 16:33 UTC, Sclafus commented on wiki/Help_centre/Upgrading_to_lazer/it.md
> +#### I punteggi impostati in lazer saranno visualizzati in stable?
```suggestion
#### I punteggi fatti su lazer sono visibili su stable?
```

2024-04-13 16:33 UTC, Sclafus commented on wiki/Help_centre/Upgrading_to_lazer/it.md
> +Però, solo le seguenti mod daranno punti performance per ora:
```suggestion
Però, solo le seguenti mod garantiscono punti performance per ora:
```

2024-04-13 16:33 UTC, Sclafus commented on wiki/Help_centre/Upgrading_to_lazer/it.md
> +- Conversione (osu!mania only)
```suggestion
- Conversione (solo osu!mania)
```

2024-04-13 16:33 UTC, Sclafus commented on wiki/Help_centre/Upgrading_to_lazer/it.md
> +- Automazione (osu! only)
```suggestion
- Automazione (solo osu!)
```

2024-04-13 16:35 UTC, marcostudios reviewed
Ty :3

2024-04-13 16:39 UTC, Sclafus approved these changes
LGTM :3

2024-04-16 21:28 UTC, TicClick approved these changes

2024-04-16 21:30 UTC, merged