[IT] Updated miscellaneous articles
ppy/osu-wiki pull request #11242
Opened 2024-04-13 17:57 UTC by Sclafus

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-13 18:08 UTC, marcostudios requested changes

2024-04-13 18:08 UTC, marcostudios commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=US }:: [BTMC](https://osu.ppy.sh/users/3171691) | Contributo eccezionale ai tornei offline e alla crescita della community in generale.
```suggestion
| ::{ flag=US }:: [BTMC](https://osu.ppy.sh/users/3171691) | Contributo eccezionale ai tornei offline e alla crescita della community in generale. |
```

2024-04-13 18:10 UTC, marcostudios approved these changes
LGTM

2024-04-15 14:50 UTC, Walavouchey approved these changes

2024-04-15 14:52 UTC, merged