[RU] Add `Client/Beatmap_editor/Menu`
ppy/osu-wiki pull request #11248
Opened 2024-04-14 17:37 UTC by yukenao

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-18 22:41 UTC, TicClick requested changes

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Настройки тайминга (`F6`) | Открыть окно [`Тайминг-секций`](/wiki/Client/Beatmap_editor/Timing). |
это просто фраза, описывающая суть окна, а значит, особое форматирование не нужно
```suggestion
| Настройки тайминга (`F6`) | Открыть [окно настройки тайминга](/wiki/Client/Beatmap_editor/Timing). |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Шаг сетки (`G`) | Отрегулировать [шаг сетки](/wiki/Beatmapping/Grid_snapping) игрового поля, используемой для [привязки нот](/wiki/Beatmapping/Snapping). |
лучше «размер», так понятнее будет, как по мне
```suggestion
| Шаг сетки (`G`) | Отрегулировать [размер сетки](/wiki/Beatmapping/Grid_snapping) игрового поля, используемой для [привязки нот](/wiki/Beatmapping/Snapping). |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Dim Background | Затемнить задний фон в [режиме тестирования](/wiki/Client/Beatmap_editor/Test_mode), чтобы сделать объекты более заметными. |
```suggestion
| Dim Background | Затемнить задний фон в [режиме тестирования](/wiki/Client/Beatmap_editor/Test_mode), чтобы объекты были более заметными. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Показывать название сэмплов | Показывать [название сэмплов кейсаундов](/wiki/Beatmapping/Hitsound#keysound), прикреплённых к нотам для сложностей osu!mania. |
```suggestion
| Показывать названия сэмплов | Показывать названия [кейсаундов](/wiki/Beatmapping/Hitsound#keysound), назначенных на ноты в osu!mania. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Ползущие слайдера | Слайдеры разворачиваются из своей начальной точки. |
какое-то бухгалтерское ударение получилось — «слайдера́»
```suggestion
| Ползущие слайдеры | Включить «выползание» слайдеров из начальной точки в момент появления. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Анимация попадания | Объекты будут исчезать так же, как во время игры, не оставляя следов. |
```suggestion
| Анимация попадания | Включить такую же анимацию бесследного пропадания объектов, как при игре. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Показывать стеки | Как и во время игры, расположенные в одной точке объекты будут объединяться в стек.[^stacking-note] |
```suggestion
| Показывать стеки | Объединять объекты, расположенные в одной точке, в стек — как при игре.[^stacking-note] |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Шаг временной шкалы | Изменить делитель [шага звуковой шкалы](/wiki/Beatmapping/Grid_snapping), для отображения большего или меньшего количества тиков на [временно́й шкале](/wiki/Client/Beatmap_edi
кто-то копипастит
```suggestion
| Шаг временно́й шкалы | Сделать [шаг временно́й шкалы](/wiki/Client/Beatmap_editor/Beat_snap_divisor) более крупным или мелким, чтобы на [верхней шкале](/wiki/Client/Beatmap_editor/Timelines) отображалось больше или меньше тиков. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Прикреплять ноты к сетке (T) | Прикреплять игровые объекты к [сетке](/wiki/Beatmapping/Grid_snapping) игрового поля. |
надо бы поправить в оригинале тоже, но это уже потом
```suggestion
| Прикреплять ноты к сетке (`T`) | Прикреплять игровые объекты к [сетке](/wiki/Beatmapping/Grid_snapping) игрового поля. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Создать многоугольник (`Ctrl` + `Shift` + `D`) | Создать многоугольник, состоящий из нот, используя для размещения активный делитель [шага звуковой шкалы](/wiki/Beatmapping/Grid_snapping). |
```suggestion
| Создать многоугольник (`Ctrl` + `Shift` + `D`) | Добавить многоугольник, используя для размещения нот текущий шаг временно́й шкалы. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Преобразовать слайдер в стрим... | Преобразовать [тело](/wiki/Gameplay/Hit_object/Slider/Sliderbody) выбранного слайдера в [стрим](/wiki/Beatmap/Pattern/osu!/Stream) из нот. **By object count:** ис
```suggestion
| Преобразовать слайдер в стрим... | Преобразовать [тело](/wiki/Gameplay/Hit_object/Slider/Sliderbody) выбранного слайдера в [стрим](/wiki/Beatmap/Pattern/osu!/Stream) из нот. **By object count:** использовать определённое число нот. **By distance snap:** использовать определённый [множитель расстояния](/wiki/Client/Beatmap_editor/Distance_snap). |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Режим лайв-маппинга (`Ctrl` + `Tab`) | Ставить [ноты](/wiki/Gameplay/Hit_object/Hit_circle) для osu!/osu!taiko/osu!mania или [фрукты](/wiki/Gameplay/Hit_object/Fruit) в osu!catch используя геймплей
```suggestion
| Режим лайв-маппинга (`Ctrl` + `Tab`) | Включить режим расстановки объектов под музыку с помощью игровых клавиш ([нот](/wiki/Gameplay/Hit_object/Hit_circle) в osu!taiko или osu!mania, либо [фруктов](/wiki/Gameplay/Hit_object/Fruit) в osu!catch).[^live-mapping-note] |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Автобаланс звука | **(доступно только для редактора osu!mania)** Сбалансировать звучание хитсаундов у всех игровых объектов в зависимости от их количества на одном тике временно́й шкалы и настроек
не, это надо добавить сначала в оригинальную статью (отдельно), а уже потом — в перевод, так что давай откатим
```suggestion
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Размер такта | Выбрать [размер такта](/wiki/Music_theory/Time_signature) 4/4 (обычная) или 3/4 (вальс) для текущей тайминг-секции. Для использования другого тактового размера воспользуйтесь окном [
```suggestion
| Размер такта | Выбрать [размер такта](/wiki/Music_theory/Time_signature) текущей тайминг-секции (обычный — 4/4, вальс — 3/4). Для использования другого тактового размера воспользуйтесь [окном настройки тайминга](/wiki/Client/Beatmap_editor/Timing). |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Звук метронома | Включить звук [метронома](/wiki/Client/Beatmap_editor/Timing#метроном) во вкладке `Тайминг`. |
здесь неправильное форматирование
```suggestion
| Звук метронома | Включить звук [метронома](/wiki/Client/Beatmap_editor/Timing#метроном) во вкладке тайминга. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Сбросить текущую секцию | Сбросить [BPM](/wiki/Music_theory/Tempo) и [оффсет](/wiki/Offset) текущей красной тайминг-секции для [повторного тайминга](/wiki/Beatmapping/Timing). Сохранение удалит все
так понятнее, что́ именно удалится
```suggestion
| Сбросить текущую секцию | Сбросить [BPM](/wiki/Music_theory/Tempo) и [оффсет](/wiki/Offset) текущей красной тайминг-секции для [повторного тайминга](/wiki/Beatmapping/Timing). Все сброшенные таким образом секции будут удалены при сохранении карты. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Подогнать ноты текущей секции | [Подогнать](/wiki/Beatmapping/Snapping) все игровые объекты текущей красной тайминг-секции к шагу временно́й шкалы. |
```suggestion
| Подогнать ноты текущей секции | [Подогнать](/wiki/Beatmapping/Snapping) все игровые объекты текущей красной тайминг-секции под видимые тики временно́й шкалы. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Настройка тайминга (`F6`) | Открыть окно [`настройки тайминга`](/wiki/Client/Beatmap_editor/Timing). |
это просто фраза, описывающая суть окна, а значит, особое форматирование не нужно
```suggestion
| Настройка тайминга (`F6`) | Открыть [окно настройки тайминга](/wiki/Client/Beatmap_editor/Timing). |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Подогнать все ноты | Подогнать все игровые объекты к шагу временно́й шкалы. |
```suggestion
| Подогнать все ноты | Подогнать все игровые объекты под видимые тики временно́й шкалы. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Пересчитать длины слайдеров | Автоматически пересчитать[^recalculate-lengths-note] все [длины слайдеров](/wiki/Gameplay/Hit_object/Slider/Slidertail) на ближайшую отметку шага временно́й шкалы, **ч
```suggestion
| Пересчитать длины слайдеров | Автоматически пересчитать[^recalculate-lengths-note] все [длины слайдеров](/wiki/Gameplay/Hit_object/Slider/Slidertail), чтобы они заканчивались на ближайшем к ним тике временно́й шкалы. **Это может привести к их укорочению** и потребовать ручной перепроверки всей карты. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Удалить все тайминг-секции | Удалить все красные и зелёные тайминг-секции в этой сложности. |
```suggestion
| Удалить все тайминг-секции | Удалить все красные и зелёные тайминг-секции в сложности. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +![Веб меню](img/M_Web-RU.png "Веб меню")
может, так лучше? «веб меню» звучит как набор слов, «веб-меню» — словно внутри будут действия, что-то модифицирующие в интернете (что неправда — они просто открывают ссылки в браузере)
```suggestion
![Меню ссылок](img/M_Web-RU.png "Меню ссылок")
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Страница этой карты | Открыть страницу этой карты<!-- TODO(TicClick): link after https://github.com/ppy/osu-wiki/issues/3122 is completed --> на веб-сайте osu!. |
и так понятно, что «этой» — какой же ещё?
(если бы мог — удалил бы и из названия пункта меню, но увы)
```suggestion
| Страница этой карты | Перейти на страницу карты<!-- TODO(TicClick): link after https://github.com/ppy/osu-wiki/issues/3122 is completed --> на веб-сайте osu!. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Тема на форуме | Открыть страницу с темой этой карты на форуме. |
```suggestion
| Тема на форуме | Перейти в форумную тему, связанную с картой. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +![Меню помощи](img/M_Help-RU.png "Меню помощи")
```suggestion
![Справочное меню](img/M_Help-RU.png "Справочное меню")
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +![Edit menu](img/M_Edit-RU.png "Меню редактирования")
```suggestion
![Меню редактирования](img/M_Edit-RU.png "Меню редактирования")
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +![View menu](img/M_View-RU.png "Меню вида")
```suggestion
![Меню вида](img/M_View-RU.png "Меню вида")
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +![Compose menu](img/M_Compose-RU.png "Меню редактора")
```suggestion
![Меню редактора](img/M_Compose-RU.png "Меню редактора")
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Показать справку | Показать оверлей справки с горячими клавишами и краткими пояснениями.[^help-note] |
```suggestion
| Показать справку | Показать внутриигровую справку со списком горячих клавиш и краткими пояснениями к интерфейсу редактора.[^help-note] |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Посмотреть FAQ... | Открыть статью о [Маппинге](/wiki/Beatmapping) на вики. |
```suggestion
| Посмотреть FAQ... | Перейти к статье про [маппинг](/wiki/Beatmapping) на osu! wiki. |
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +[^osz2-note]: Это действие отключено для обычных `osz` карт.
```suggestion
[^osz2-note]: Это действие отключено для обычных карт формата `osz`.
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +[^exit-note]: Это действие иногда игнорирует изменения, внесённые во вкладке `Дизайн`.
```suggestion
[^exit-note]: Это действие иногда игнорирует изменения, внесённые во вкладке «Дизайн».
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +[^stacking-note]: Степень наложения стеков определяется параметром [stack leniency](/wiki/Beatmap/Stack_leniency) в сложности.
мне кажется, так корректнее будет
```suggestion
[^stacking-note]: Агрессивность формирования стеков в каждой отдельной сложности определяется её параметром [stack leniency](/wiki/Beatmap/Stack_leniency).
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +[^live-mapping-note]: osu!, osu!taiko и osu!catch используют клавиши назначенные для osu!taiko.
```suggestion
[^live-mapping-note]: Во всех трёх режимах для расстановки объектов будут использоваться клавиши, назначенные для игры в osu!taiko.
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +[^recalculate-lengths-note]: Полезно, если был изменён BPM или [скорость слайдера](/wiki/Gameplay/Hit_object/Slider/Slider_velocity).
```suggestion
[^recalculate-lengths-note]: Пригождается при изменении BPM или [скорости слайдера](/wiki/Gameplay/Hit_object/Slider/Slider_velocity).
```

2024-04-18 22:41 UTC, TicClick commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +[^help-note]: Это действие больше не работает.
```suggestion
[^help-note]: Это действие отключено.
```

2024-04-19 01:47 UTC, yukenao commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Ползущие слайдера | Слайдеры разворачиваются из своей начальной точки. |
Я не заметил XD

2024-04-19 02:44 UTC, yukenao commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Автобаланс звука | **(доступно только для редактора osu!mania)** Сбалансировать звучание хитсаундов у всех игровых объектов в зависимости от их количества на одном тике временно́й шкалы и настроек
Эх, а я так старался узнать как она работает D:

2024-04-19 02:46 UTC, yukenao commented on wiki/Client/Beatmap_editor/Menu/ru.md
> +| Страница этой карты | Открыть страницу этой карты<!-- TODO(TicClick): link after https://github.com/ppy/osu-wiki/issues/3122 is completed --> на веб-сайте osu!. |
Я был немного не уверен, какую будет лучше использовать формулировку, поэтому везде использовал "этой"

2024-04-19 04:50 UTC, yukenao reviewed
почему-то*

2024-04-19 23:33 UTC, TicClick approved these changes
wish I could rebase and squash 50+ commits down to 2-3, but I don't feel like fighting with conflict resolution at the moment if simple rebase doesn't work out, and it doesn't

2024-04-19 23:33 UTC, merged