[ES] Add `Featured Artists` & `Featured Artist showcase beatmaps`
ppy/osu-wiki pull request #11276
Opened 2024-04-18 22:56 UTC by Ladwick

**Article translation** – `Artistas Destacados` & `Beatmaps de exhibición de Artista Destacado`

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-19 02:22 UTC, UnknownOsu requested changes

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +El [osu! team](/wiki/People/osu!_team) a veces colabora con artistas para crear nuevas pistas llamadas [osu! originals](/wiki/osu!_originals) que se utilizan en osu!. Estas son etiquetadas como tal e
```suggestion
El [osu! team](/wiki/People/osu!_team) a veces colabora con artistas para crear nuevas pistas para usar en osu!, llamadas [osu! originals](/wiki/osu!_originals). Estas son etiquetadas como tal en el catálogo de los artistas destacados.
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Las adiciones a la librería de Artista Destacado son seleccionadas indirectamente por la comunidad de osu!. Si los mappers crean y clasifican beatmaps con la música de un artista, el osu! team puede
```suggestion
Las adiciones a la librería de los artistas destacados son seleccionadas indirectamente por la comunidad de osu!. Si los mappers crean y clasifican beatmaps con la música de un artista, el osu! team puede ponerse en contacto con dicho artista para hablar sobre el programa de artista destacado. Sin embargo, algunos artistas son ocasionalmente invitados a convertirse en artistas destacados basándose en otros factores, como el atractivo que puedan tener para la audiencia de mappers de osu!.
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Todas las canciones del programa de Artista Destacado tienen licencia no exclusiva para su uso en osu!. Más detalles para músicos que deseen unirse a los Artistas Destacados pueden ser encontrados en
```suggestion
Todas las canciones del programa de artista destacado tienen licencia no exclusiva para su uso en osu!. Más detalles para músicos que deseen unirse a los artistas destacados pueden ser encontrados en el artículo de [licenciamiento de música](/wiki/Legal/Music_licensing).
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Nuevos lanzamientos de Artista Destacado por año:
```suggestion
Nuevos lanzamientos de un artista destacado por año:
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Nuevos Artistas Destacados son anunciados semanalmente en el [sitio de noticias](https://osu.ppy.sh/home/news) de osu!. La mayoría de los anuncios incluyen una lista de las canciones licenciadas del
```suggestion
Los nuevos artistas destacados son anunciados semanalmente en el [sitio de noticias](https://osu.ppy.sh/home/news) de osu!. La mayoría de los anuncios incluyen una lista de las canciones licenciadas del artista y un enlace a su página de artista destacado, aunque algunos anuncios se emparejan con concursos de mapping o beatmaps creados por el [Mappers' Guild](/wiki/Community/Mappers_Guild).
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Se anima a los beatmappers a crear mapas para las pistas en Artista Destacado. Estas pistas se suministran con datos de [temporización](/wiki/Client/Beatmap_editor/Timing) y ya están autorizadas para
```suggestion
Se anima a los beatmappers a crear mapas para las pistas de los artistas destacados. Estas pistas se suministran con datos de [temporización](/wiki/Client/Beatmap_editor/Timing) y ya están autorizadas para su uso en osu!, permitiendo a los usuarios pasar inmediatamente al mapping sin preocupaciones. El cliente en desarrollo de osu!, apodado [osu!(lazer)](/wiki/Client/Release_stream/Lazer), marcará estos mapas prominentemente en el juego.
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Todos los concursos de mapping publicados en el [listado de concursos de la comunidad](https://osu.ppy.sh/community/contests), tales como el [Monthly Beatmapping Contest](/wiki/Contests/Monthly_Beatm
```suggestion
Todos los concursos de mapping publicados en el [listado de concursos de la comunidad](https://osu.ppy.sh/community/contests), tales como el [Monthly Beatmapping Contest](/wiki/Contests/Monthly_Beatmapping_Contest) y el [Mapping Olympiad](/wiki/Contests/Mapping_Olympiad), requieren que los participantes creen mapas con canciones de un artista destacado. Algunos concursos dirigidos por la comunidad también usan estas canciones.
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Para promocionar el mapping de contenido de Artista Destacado, los miembros de la comunidad crearon el [Mappers' Guild](/wiki/Community/Mappers_Guild), dándole a los mappers un sistema de misiones es
```suggestion
Para promocionar el mapping del contenido de los artistas destacados, los miembros de la comunidad crearon el [Mappers' Guild](/wiki/Community/Mappers_Guild), dándole a los mappers un sistema de misiones estilo MMO en el cual pueden participar junto a otros mappers. Los premios se conceden por crear y clasificar beatmaps, incluyendo tres niveles de insignias de perfil. Los mappers pueden unirse al gremio visitando el [sitio web del Mappers' Guild](https://mappersguild.com/). A partir de [abril de 2023](https://osu.ppy.sh/home/news/2023-04-09-new-featured-artist-chon), los mappers también pueden discutir todo lo relacionado a la creación de beatmaps de artistas destacados en el canal `#featured-artists` en el [servidor de Discord osu!](/wiki/Community/osu!_Discord_server).
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Si un `.osz` pre-temporizado del listado de Artista Destacado tiene errores de cualquier tipo, pueden ser reportados en este [hilo del foro](https://osu.ppy.sh/community/forums/topics/783985).
```suggestion
Si un `.osz` pre-temporizado del listado de los artistas destacados tiene errores de cualquier tipo, pueden ser reportados en este [hilo del foro](https://osu.ppy.sh/community/forums/topics/783985).
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +## Artistas Destacados con cuentas de osu!
```suggestion
## Artistas destacados con cuentas de osu!
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +Los Artistas Destacados con una cuenta de osu! pueden ser identificados por un [título de usuario](/wiki/Community/User_title) cyan de «Artista Destacado» y una insignia de [grupo de usuario](/wiki/P
```suggestion
Los artistas destacados con una cuenta de osu! pueden ser identificados por un [título de usuario](/wiki/Community/User_title) cian «Featured Artist» y una insignia de [grupo de usuario](/wiki/People/User_group) que dice `FA` para exhibir su participación.
```

2024-04-19 02:22 UTC, UnknownOsu commented on wiki/People/Featured_Artists/es.md
> +La [página de grupo de Artista Destacado](https://osu.ppy.sh/groups/35) enumera todas estas cuentas, mientras que el [listado de Artista Destacado](https://osu.ppy.sh/beatmaps/artists) enumera a todo
```suggestion
La [página de grupo de los artistas destacados](https://osu.ppy.sh/groups/35) enumera todas estas cuentas, mientras que el [listado de los artistas destacados](https://osu.ppy.sh/beatmaps/artists) enumera a todos los artistas destacados.
```

2024-04-19 08:43 UTC, iSlodinxOsu requested changes
add Cinamoro

2024-05-02 22:17 UTC, TicClick approved these changes

2024-05-02 22:19 UTC, merged