Add `Project Prism 2024` tournament article
ppy/osu-wiki pull request #11272
Opened 2024-04-18 17:04 UTC by Walavouchey

[web preview](https://osu3.roanh.dev/wiki/en/Tournaments/Project_Prism/2024)

2024-04-18 18:09 UTC, iSlodinxOsu requested changes
perhaps it should be with vanity URL instead?

2024-04-18 18:09 UTC, iSlodinxOsu commented on wiki/Tournaments/Project_Prism/2024/en.md
> +3. Players **must** join the [Discord server](https://discord.com/invite/sJK3rMdfwC) to be eligible for the tournament.
```suggestion
3. Players **must** join the [Discord server](https://discord.com/invite/osutaikomy) to be eligible for the tournament.
```

2024-04-19 09:42 UTC, 0x84f commented on wiki/Tournaments/Project_Prism/2024/en.md
> +7. Each player will be given a maximum of 2 minutes to select their picks. If a pick has not be decided before the countdown timer ends, the map will be randomised with `!roll`.
```suggestion
7. Each player will be given a maximum of 2 minutes to select their picks. If a pick has not been decided before the countdown timer ends, the map will be randomised with `!roll`.
```

2024-04-19 09:42 UTC, 0x84f commented on wiki/Tournaments/Project_Prism/2024/en.md
> +14. In the unlikely event that both players get a tied score twice in a row on the same map, the map will be nullified and another map needs to be picked by the other player.
```suggestion
14. In the unlikely event that both players get a tied score twice in a row on the same map, the map will be nullified, and another map needs to be picked by the other player.
```

2024-04-19 11:02 UTC, merged