[ES] Update `Registration`, `Skinning/Guides and important threads`, and `Storyboard`
ppy/osu-wiki pull request #11283
Opened 2024-04-19 21:45 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-19 22:16 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-19 22:16 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Guides_and_important_threads/es.md
> +- [Plantilla de skin (en inglés)](https://osu.ppy.sh/community/forums/topics/923143) por [Galvit](https://osu.ppy.sh/users/7629682)
```suggestion
- [Plantilla de una skin (en inglés)](https://osu.ppy.sh/community/forums/topics/923143) por [Galvit](https://osu.ppy.sh/users/7629682)
```

2024-04-19 22:16 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Guides_and_important_threads/es.md
> +- [Plantilla para la selección de canciones (en inglés)](https://tutorial.skinship.xyz/resources/song_selection) por [RockRoller](https://osu.ppy.sh/users/8388854)
```suggestion
- [Plantilla del selector de canciones (en inglés)](https://tutorial.skinship.xyz/resources/song_selection) por [RockRoller](https://osu.ppy.sh/users/8388854)
```

2024-04-19 22:16 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Guides_and_important_threads/es.md
> +- [Plantilla para la skin de osu! predeterminada](https://osu.ppy.sh/community/forums/topics/129191) por [peppy](https://osu.ppy.sh/users/2)
```suggestion
- [Plantilla de la skin predeterminada de osu!](https://osu.ppy.sh/community/forums/topics/129191) por [peppy](https://osu.ppy.sh/users/2)
```

2024-04-19 22:16 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Guides_and_important_threads/es.md
>  - [Reglas del foro de skinning](https://osu.ppy.sh/community/forums/topics/318193)
```suggestion
- [Reglas del foro skinning](https://osu.ppy.sh/community/forums/topics/318193)
```

2024-04-19 22:16 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/es.md
> +El *storyboarding* es el proceso de hacer un storyboard, donde la persona detrás del proceso se llama *storyboarder*. La creación de storyboards suele ser muy difícil y requiere un tiempo y una exper
```suggestion
El *storyboarding* es el proceso de crear un storyboard, donde la persona detrás del proceso se llama *storyboarder*. La creación de storyboards suele ser muy difícil y requiere mucho tiempo y experiencia en animación estándar y creación gráfica. osu! ofrece un [editor incorporado](/wiki/Client/Beatmap_editor/Design) dentro del [editor de beatmaps](/wiki/Client/Beatmap_editor) para ayudar en la creación de storyboards, aunque la mayoría de los storyboarders ávidos optan por programar a través de las [secuencias de comandos](/wiki/Storyboard/Scripting) directamente. Muchos creadores optan por escribir programas en lenguajes de programación completos para generar secuencias de comandos para el storyboard, ya que los efectos visuales complejos pueden requerir una gran cantidad de código en el storyboard para su producción.
```

2024-04-19 22:18 UTC, Unnombredeusuarioextremadamentelargo approved these changes

2024-04-24 20:14 UTC, TicClick approved these changes

2024-04-24 22:01 UTC, merged