[ES] Add `Storyboard/Scripting/Cheat Sheet`
ppy/osu-wiki pull request #11288
Opened 2024-04-20 01:33 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 03:26 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-20 03:26 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Cheat_Sheet/es.md
> +Sprite,«capa»,«origen»,"ruta del archivo",x,y
Deja las comillas inglesas para que no haya confusión al momento de leer los ejemplos

2024-04-20 03:26 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Cheat_Sheet/es.md
> +Animation,«capa»,«origen»,"ruta del archivo",x,y,frameCount,frameDelay,looptype
```suggestion
Animation,"capa","origen","ruta del archivo",x,y,frameCount,frameDelay,looptype
```

2024-04-20 03:26 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Cheat_Sheet/es.md
> +**Para animaciones, especifica un nombre de archivo como «sliderball.png», y asigna a tus archivos el nombre «sliderball0.png» a «sliderball9.png» para obtener una animación de 10 fotogramas.**
```suggestion
**Para las animaciones, especifica un nombre de archivo como «sliderball.png», y asígnale a tus archivos el nombre «sliderball0.png» a «sliderball9.png» para obtener una animación de 10 fotogramas.**
```

2024-04-20 03:26 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Cheat_Sheet/es.md
> +**starttime, endtime**: los tiempos en milisegundos entre los cuales se animará el evento
```suggestion
**starttime, endtime**: los períodos de tiempo en milisegundos en los que se animará el evento
```

2024-04-20 03:26 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Cheat_Sheet/es.md
> +El soporte primitivo para variables ya está disponible. Puedes definir cualquier cantidad de variables incluyendo una sección \[Variables\] en el archivo .osb (actualmente no se admite en los storybo
```suggestion
El soporte primitivo para las variables ya está disponible. Puedes definir cualquier cantidad de variables incluyendo una sección \[Variables\] en el archivo .osb (actualmente no se admite en los storyboards específicos del archivo .osu).
```

2024-05-02 22:41 UTC, TicClick approved these changes

2024-05-02 22:46 UTC, merged