[ES] Add `Storyboard/Scripting/Commands`
ppy/osu-wiki pull request #11289
Opened 2024-04-20 01:33 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +dónde:
```suggestion
en donde:
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +- _ puede ser un espacio en lugar de un guión bajo.
```suggestion
- _ puede ser un espacio en lugar de un guion bajo.
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +Por ejemplo, para desvanecer un objeto en 1 segundo (comenzando 1 segundo después de que comienza el mapa), esperar 2 segundos en la mitad de la transparencia y luego desvanecerlo en 1 segundo, escri
```suggestion
Por ejemplo, para desvanecer un objeto en 1 segundo (comenzando 1 segundo después de que comience el mapa), esperar 2 segundos en la mitad de la transparencia y luego desvanecerlo en 1 segundo, escribiríamos algo como:
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +Como mover, pero solo cambia la coordenada X. La coordenada Y permanece igual. Por ejemplo, para mover un objeto de la izquierda de la pantalla a la derecha:
```suggestion
Como el comando mover, pero solo cambia la coordenada X. La coordenada Y permanece igual. Por ejemplo, para mover un objeto de la izquierda de la pantalla a la derecha:
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +Como mover, pero solo cambia la coordenada Y. La coordenada X permanece igual. Por ejemplo, para mover un objeto desde la parte inferior de la pantalla hasta la parte superior:
```suggestion
Como el comando mover, pero solo cambia la coordenada Y. La coordenada X permanece igual. Por ejemplo, para mover un objeto desde la parte inferior de la pantalla hasta la parte superior:
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +| La cantidad de rotación de un objeto desde su imagen original, en radianes, en el sentido de las agujas del reloj. | Cualquier número real; el negativo es la rotación en el sentido contrario de las
```suggestion
| La cantidad de rotación de un objeto desde su imagen original, en radianes, en el sentido de las agujas del reloj. | Cualquier número real; el negativo es la rotación en el sentido contrario de las agujas del reloj/antihorario, el positivo es en el sentido de las agujas del reloj. Exceder 2*pi en cualquier sentido seguirá girando tantas veces como desees. | 0 |
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +### Comando de parámetro (P)
```suggestion
### Comando parámetro (P)
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +A diferencia de los otros comandos, que pueden verse como la configuración de puntos finales a lo largo de valores de seguimiento continuo, el comando parámetro se aplica SOLO mientras están activos;
```suggestion
A diferencia de los otros comandos, que pueden verse como el establecimiento de puntos finales a lo largo de valores de seguimiento continuo, el comando parámetro se aplica SOLO mientras están activos; es decir, no se puede colocar un comando desde las marcas de tiempo 1000 a 2000 y esperar que el valor se aplique en el tiempo 3000, incluso si los otros comandos del objeto no han terminado en ese momento.
```

2024-04-20 05:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Commands/es.md
> +- [Comando de bucle (L)](/wiki/Storyboard/Scripting/Compound_Commands)
```suggestion
- [Comando bucle (L)](/wiki/Storyboard/Scripting/Compound_Commands)
```

2024-05-02 22:41 UTC, TicClick approved these changes

2024-05-02 22:44 UTC, merged