[ES] Update `Ranking criteria`
ppy/osu-wiki pull request #11286
Opened 2024-04-20 01:12 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 01:14 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-20 01:14 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/es.md
> +- **Las versiones cortadas no oficiales de las canciones deben añadir un marcador `(Cut Ver.)` al final del título actual.** Si ya hay un marcador de duración en el título de la canción, `(Cut Ver.)`
```suggestion
- **Las versiones cortadas no oficiales de las canciones deben añadir un marcador `(Cut Ver.)` al final del título actual.** Si ya hay un marcador de duración en el título de la canción, `(Cut Ver.)` debe reemplazarlo. Esto se hace para distinguir los cortes no oficiales de una canción de las versiones completas.
```

2024-04-20 01:14 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/es.md
> +- **Las versiones extendidas no oficiales de las canciones deben añadir un marcador `(Extended Edit)` al final del título actual.** Si ya hay un marcador de duración en el título de la pista, `(Exten
```suggestion
- **Las versiones extendidas no oficiales de las canciones deben añadir un marcador `(Extended Edit)` al final del título actual.** Si ya hay un marcador de duración en el título de la pista, `(Extended Edit)` debe reemplazarlo. Esto se hace para distinguir las versiones extendidas no oficiales de una canción de las versiones extendidas oficiales.
```

2024-04-20 08:26 UTC, agatemosu approved these changes

2024-04-20 08:29 UTC, agatemosu commented on wiki/Ranking_criteria/es.md
> +- **Las versiones extendidas no oficiales de las canciones deben añadir un marcador `(Extended Edit)` al final del título actual.** Si ya hay un marcador de duración en el título de la pista, `(Exten
```suggestion
- **Las versiones extendidas no oficiales de las canciones deben añadir un marcador `(Extended Edit)` al final del título actual.** Si ya hay un marcador de duración en el título de la pista, `(Extended Edit)` debe sustituirlo. Esto se hace para distinguir las versiones extendidas no oficiales de una canción de las versiones extendidas oficiales.
```

2024-04-20 08:29 UTC, agatemosu commented on wiki/Ranking_criteria/es.md
> +- **Las versiones cortadas no oficiales de las canciones deben añadir un marcador `(Cut Ver.)` al final del título actual.** Si ya hay un marcador de duración en el título de la canción, `(Cut Ver.)`
```suggestion
- **Las versiones cortadas no oficiales de las canciones deben añadir un marcador `(Cut Ver.)` al final del título actual.** Si ya hay un marcador de duración en el título de la canción, `(Cut Ver.)` debe sustituirlo. Esto se hace para distinguir los cortes no oficiales de una canción de las versiones completas.
```

2024-04-20 08:30 UTC, agatemosu reviewed
podrías cambiar la línea 20 y 214 también

2024-04-20 17:27 UTC, agatemosu approved these changes

2024-04-24 20:14 UTC, TicClick approved these changes

2024-04-24 21:34 UTC, merged