[ES] Add `Storyboard/Scripting/Audio`
ppy/osu-wiki pull request #11287
Opened 2024-04-20 01:33 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 02:56 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-20 02:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Audio/es.md
> +- `<número de la capa>` es un *valor numérico* correspondiente a la capa en la que desea que esté el sonido. Los valores válidos se enumeran a continuación.
```suggestion
- `<número de la capa>` es un *valor numérico* correspondiente a la capa en la que deseas que esté el sonido. Los valores válidos se enumeran a continuación.
```

2024-04-20 02:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Audio/es.md
> +- `<ruta del archivo>` es el mismo concepto que con los sprites, solo que se refiere a los archivos .wav, .mp3 u .ogg.
```suggestion
- `<ruta del archivo>` es el mismo concepto que con los sprites, solo que se refiere a los archivos .wav, .mp3 o .ogg.
```

2024-04-20 02:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Audio/es.md
> +Los valores válidos para capas son:
```suggestion
Los valores válidos para las capas son:
```

2024-05-02 22:40 UTC, TicClick approved these changes

2024-05-02 22:42 UTC, merged