[ES] Update `osu! wiki/Contribution guide`
ppy/osu-wiki pull request #11282
Opened 2024-04-19 21:43 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-19 21:53 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-19 21:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!_wiki/Contribution_guide/es.md
> +- **Estructura y formato**: obtén una vista previa de tu artículo con una herramienta como [Markdown Editor de jbt](https://jbt.github.io/markdown-editor/) para asegurarte de que se ve exactamente co
```suggestion
- **Estructura y formato**: obtén una vista previa de tu artículo con una herramienta como [Markdown Editor de jbt](https://jbt.github.io/markdown-editor/) para asegurarte de que se ve exactamente como querías.
```

2024-04-19 21:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!_wiki/Contribution_guide/es.md
>  - **Todas las imágenes y otros archivos** que no sean de texto deben tener [menos de 1 megabyte](/wiki/Article_styling_criteria/Formatting#tamaño-del-archivo). Las **capturas de pantalla** deben usar
```suggestion
- **Todas las imágenes y otros archivos** que no sean de texto deben tener [menos de 1 megabyte](/wiki/Article_styling_criteria/Formatting#tamaño-del-archivo). Las **capturas de pantalla** deben usar la skin predeterminada de osu! y las [configuraciones específicas](/wiki/Article_styling_criteria/Formatting#capturas-de-pantalla-del-juego), incluyendo las dimensiones máximas de 1280×720.
```

2024-04-19 21:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!_wiki/Contribution_guide/es.md
> +1. En **tu bifurcación** de la osu! wiki, busca el menú desplegable que dice `master↓` y seleccione la rama con tus cambios.
```suggestion
1. En **tu bifurcación** de la osu! wiki, busca el menú desplegable que dice `master↓` y selecciona la rama con tus cambios.
```

2024-04-19 21:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!_wiki/Contribution_guide/es.md
> +Todos los cambios en la osu! wiki son moderados. Durante esa etapa, otros colaboradores señalan posibles errores y formas de solucionarlos, ya sea de forma libre o sugiriendo ediciones directas a la
```suggestion
Todos los cambios en la osu! wiki son moderados. Durante esa etapa, otros colaboradores señalan posibles errores y formas de solucionarlos, ya sea de forma libre o sugiriendo ediciones directas a la solicitud de cambios. Al igual que con cualquier otra revisión por pares, debes abordar los comentarios [aplicando las revisiones](/wiki/osu!_wiki/Contribution_guide/Best_practices#aplicar-revisiones) o explicando por qué prefieres mantener las cosas como están.
```

2024-04-19 21:54 UTC, Unnombredeusuarioextremadamentelargo approved these changes

2024-04-20 08:34 UTC, agatemosu approved these changes

2024-04-20 13:54 UTC, TicClick approved these changes

2024-04-20 13:58 UTC, merged