[ES] Add `Content usage permissions`
ppy/osu-wiki pull request #11298
Opened 2024-04-20 03:30 UTC by Ladwick

**Article translation** – `Permisos de uso de contenido`

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 05:01 UTC, UnknownOsu requested changes

2024-04-20 05:01 UTC, UnknownOsu commented on wiki/Rules/Content_usage_permissions/es.md
> +[partial]: /wiki/shared/partial.png "Allowed, with exceptions"
```suggestion
[partial]: /wiki/shared/partial.png "Permitido, con excepciones"
```

2024-04-20 08:02 UTC, agatemosu commented on wiki/Rules/Content_usage_permissions/es.md
> +Todo trabajo visual debe estar debidamente atribuido e incluir enlaces apropiados a su fuente. Si un enlace directo no puede ser usado por cualquier razón, otro enlace que apunte a la presencia princ
```suggestion
Todo trabajo visual debe estar debidamente atribuido e incluir enlaces apropiados a su fuente. Si un enlace directo no puede ser usado por cualquier razón, en su lugar, se debe usar otro enlace que apunte a la presencia principal del artista visual en su plataforma más activa. 
```

2024-04-20 17:36 UTC, agatemosu commented on wiki/Rules/Content_usage_permissions/es.md
> +Al buscar canciones fuera del catálogo de los artistas destacados de osu!, verifica si su artista indicó términos de uso explicitamente. Esta información puede ser encontrada a menudo en la sección d
```suggestion
Al buscar canciones fuera del catálogo de los artistas destacados de osu!, verifica si su artista indicó términos de uso explicitamente. Esta información puede ser encontrada a menudo en la sección de descripción de las plataformas de lanzamiento de música de un artista (p. ej. Bandcamp, SoundCloud, Youtube) o su sitio web personal. Si una canción está bajo una [licencia Creative Commons](https://creativecommons.org/about/cclicenses/) o está disponible para su uso no comercial, puedes crear y enviar un beatmap que la use.
```

2024-04-25 00:03 UTC, UnknownOsu requested changes

2024-04-25 00:03 UTC, UnknownOsu commented on wiki/Rules/Content_usage_permissions/es.md
> +Al buscar canciones fuera del catálogo de los artistas destacados de osu!, verifica si su artista indicó términos de uso explicitamente. Esta información puede ser encontrada a menudo en la sección d
```suggestion
Al buscar canciones fuera del catálogo de los artistas destacados de osu!, verifica si su artista indicó términos de uso explicitamente. Esta información puede ser encontrada a menudo en la sección de descripción de las plataformas de lanzamiento de música de un artista (p. ej., Bandcamp, SoundCloud, Youtube) o su sitio web personal. Si una canción está bajo una [licencia Creative Commons](https://creativecommons.org/about/cclicenses/) o está disponible para su uso no comercial, puedes crear y enviar un beatmap que la use.
```

2024-04-26 19:58 UTC, UnknownOsu requested changes

2024-04-26 19:58 UTC, UnknownOsu commented on wiki/Rules/Content_usage_permissions/es.md
> +Sin permiso, los [beatmaps](/wiki/Beatmap) subidos están en riesgo de ser removidos y sus creadores corren el riesgo de que se les deniegue el acceso al sistema de envíos según la [política de derech
```suggestion
Sin permiso, los [beatmaps](/wiki/Beatmap) subidos corren el riesgo de ser eliminados y sus creadores corren el riesgo de que se les deniegue el acceso al sistema de envíos según la [política de derechos de autor de osu!](/wiki/Legal/Copyright). Esto significa que los usuarios deben crear beatmaps usando cualquier recurso que cumpla con lo siguiente:
```

2024-04-26 19:58 UTC, UnknownOsu commented on wiki/Rules/Content_usage_permissions/es.md
> +- De uso permitido por su(s) creador(es)
```suggestion
- Permitido su uso por parte de sus creadores
```

2024-04-26 20:33 UTC, UnknownOsu approved these changes

2024-04-26 21:11 UTC, agatemosu approved these changes

2024-05-02 22:35 UTC, TicClick approved these changes

2024-05-02 22:37 UTC, merged