[ES] Add `Storyboard/Scripting/Compound Commands`
ppy/osu-wiki pull request #11290
Opened 2024-04-20 01:34 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 16:56 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-20 16:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Compound_Commands/es.md
> +# Comandos compuestos para un storyboard
```suggestion
# Comandos compuestos de un storyboard
```

2024-04-20 16:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Compound_Commands/es.md
> +## Comando de bucle (L)
```suggestion
## Comando bucle (L)
```

2024-04-20 16:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Compound_Commands/es.md
> +Por lo tanto, un bucle que aparece y desaparece, tomando un total de 1 segundo cada vez, durante 30 segundos en total (por lo tanto, 30 bucles), comenzando en el tiempo 60000:
```suggestion
Por lo tanto, un bucle que aparece y desaparece, tomando un total de 1 segundo cada vez, durante 30 segundos en total (por lo tanto, 30 bucles), comenzando en el tiempo 60 000:
```

2024-04-20 16:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Compound_Commands/es.md
> +Además de la retroalimentación «implícita» del jugador a través de las capas separadas [Pass/Fail](/wiki/Storyboard/Scripting/General_Rules), puedes usar una de varias **condiciones de activación** p
```suggestion
Además de la retroalimentación «implícita» del jugador a través de las capas separadas [Pass/Fail](/wiki/Storyboard/Scripting/General_Rules), puedes usar una de varias **condiciones de activación** para causar una serie de [eventos](/wiki/Storyboard/Scripting/Commands) que ocurrirán siempre que esa condición se cumpla dentro de un cierto periodo de tiempo. La especificación oficial los denomina «bucles de activación» debido a su similitud sintáctica con los bucles (L), pero no son bucles en absoluto, por lo que aquí se denominan simplemente «activadores».
```

2024-04-20 16:56 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/Compound_Commands/es.md
> +Por ejemplo, en Elite Beat Agents, la pantalla superior (es decir, el storyboard) suele cubrirse de blanco durante una fracción de segundo durante una transición entre estados. Podemos hacer lo mismo
```suggestion
Por ejemplo, en Elite Beat Agents, la pantalla superior (es decir, el storyboard) suele cubrirse de blanco durante una fracción de segundo durante una transición entre estados. Podemos hacer lo mismo con una imagen completamente blanca de 640x480, suponiendo que una sección jugable en particular va de 20 000 a 40 000:
```

2024-05-02 22:53 UTC, TicClick approved these changes

2024-05-02 22:58 UTC, merged