[ES] Add `Storyboard/Scripting/General Rules`
ppy/osu-wiki pull request #11291
Opened 2024-04-20 01:34 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 17:12 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-20 17:12 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/General_Rules/es.md
> +Ten en cuenta que las capas «Fail» y «Pass» nunca aparecen en pantalla simultáneamente, a diferencia de lo que ocurre en la pestaña de diseño.
```suggestion
Ten en cuenta que las capas «Fail» y «Pass» nunca aparecen en la pantalla simultáneamente, a diferencia de lo que ocurre en la pestaña de diseño.
```

2024-04-20 17:12 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/General_Rules/es.md
> +    - Ejemplo A: Obtener una precisión de 96,5 % mientras la barra de HP todavía está al 40 % dará un Pass en lugar de un Fail.
```suggestion
    - Ejemplo A: Obtener una precisión de 96,5 % mientras la barra de HP todavía está al 40 % dará un Pass en lugar de un Fail.
```

2024-04-20 17:12 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/General_Rules/es.md
> +    - Ejemplo B: Obtener demasiados 100 en aproximadamente 30 notas y obtener una D mientras la barra de HP todavía está alrededor del 30 % resultará en un Fail en lugar de un Pass (en este caso, con
```suggestion
    - Ejemplo B: Obtener demasiados 100 en aproximadamente 30 notas y obtener una D mientras la barra de HP todavía está alrededor del 30 % resultará en un Fail en lugar de un Pass (en este caso, consulta [ZUN - Maiden's Cappricio ~ Dream Battle](https://osu.ppy.sh/beatmapsets/18005#taiko/69556)).
```

2024-04-20 17:12 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/General_Rules/es.md
> +  - En el primer caso, se mostrará al usuario el botón `Skip`. Al hacer clic en él o al presionar `Barra espaciadora` saltará al tiempo 0. El juego vuelve al comportamiento normal de salto previo al
```suggestion
  - En el primer caso, se mostrará al usuario el botón `Skip`. Al hacer clic en él o al presionar `Barra espaciadora` saltará al tiempo 0. El juego vuelve al comportamiento normal de salto previo al mapa (por ejemplo, presionar `Skip` nuevamente para ir directamente a la cuenta regresiva, a diferencia de [Elite Beat Agents](https://es.wikipedia.org/wiki/Elite_Beat_Agents), donde reiniciar el beatmap lleva al jugador hasta el inicio, no hasta el tiempo 0).
```

2024-04-20 17:12 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Storyboard/Scripting/General_Rules/es.md
> +    - Ejemplo: si el storyboard de Fail termina en el tiempo 20 000 y el storyboard de Pass termina en el tiempo 25 000, el juego esperará hasta el momento 25 000 incluso si el jugador está en estado
```suggestion
    - Ejemplo: si el storyboard de Fail termina en el tiempo 20 000 y el storyboard de Pass termina en el tiempo 25 000, el juego esperará hasta el momento 25 000 incluso si el jugador está en estado Fail (todos los objetos desaparecerán). Por lo tanto, es mejor asegurarse de que las variantes de finalización de Pass y Fail tarden la misma cantidad de tiempo en completarse.
```

2024-05-22 05:15 UTC, cl8n approved these changes

2024-05-22 05:17 UTC, cl8n commented
wont block this one for it but I think if you add new images in a way that they aren't literal translations of the English ones, then English should also be updated

2024-05-22 05:19 UTC, merged