[ES] Add `osu!mania 10K+ playstyles`
ppy/osu-wiki pull request #11302
Opened 2024-04-20 09:27 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 16:41 UTC, UnknownOsu requested changes

2024-04-20 16:41 UTC, UnknownOsu commented on wiki/Beatmapping/osu!mania_10K_plus_playstyles/es.md
> +Este artículo documenta estilos de juego comunes usados por [beatmaps](/wiki/Beatmap) de [osu!mania](/wiki/Game_mode/osu!mania) con 10 o más teclas.
```suggestion
Este artículo documenta los estilos de juego comunes usados por los [beatmaps](/wiki/Beatmap) de [osu!mania](/wiki/Game_mode/osu!mania) con 10 o más teclas.
```

2024-04-20 16:41 UTC, UnknownOsu commented on wiki/Beatmapping/osu!mania_10K_plus_playstyles/es.md
> +En este contexto, un **estilo de juego** es conjunto sugerido de [atajos de teclado](/wiki/Game_mode/osu!mania#controles) y orden de teclas en el [campo de juego](/wiki/Game_mode/osu!mania#campo-de-j
```suggestion
En este contexto, un **estilo de juego** es un conjunto sugerido de [atajos de teclado](/wiki/Game_mode/osu!mania#controles) y orden de teclas en el [campo de juego](/wiki/Game_mode/osu!mania#campo-de-juego). La mayoría de los beatmaps de osu!mania con más de 10 teclas se mapean con un estilo de juego en particular; el jugador tiene menos dedos que teclas, por lo que suele ser necesario tener en cuenta dónde colocará las manos el jugador en el [teclado](/wiki/Gameplay/Input_device/Keyboard) a lo largo del mapa.
```

2024-04-20 16:41 UTC, UnknownOsu commented on wiki/Beatmapping/osu!mania_10K_plus_playstyles/es.md
> +**DP** o **Double Play**, llamado así por el modo de juego en *[beatmania IIDX](https://es.wikipedia.org/wiki/Beatmania_IIDX_(serie) "\"beatmania IIDX\" en Wikipedia")*, es un estilo de juego de 14 t
```suggestion
**DP** o **Double Play**, llamado así por el modo de juego en *[beatmania IIDX](https://es.wikipedia.org/wiki/Beatmania_IIDX_(serie) "\"beatmania IIDX\" en Wikipedia")*, es un estilo de juego de 14 teclas o 16 teclas donde cada mano es responsable de 7 teclas, organizadas en filas inferiores de 4 teclas y filas superiores de 3 teclas. Las filas inferiores y superiores están intercaladas de manera que la primera tecla es inferior, la segunda superior, la tercera inferior, y así sucesivamente. Una tecla *scratch* adicional puede incluirse en cada borde exterior del escenario.
```

2024-04-20 17:22 UTC, UnknownOsu requested changes

2024-04-20 17:22 UTC, UnknownOsu commented on wiki/Beatmapping/osu!mania_10K_plus_playstyles/es.md
> +Cada estilo de juego requiere que el jugador ajuste sus [atajos de teclado](/wiki/Game_mode/osu!mania#controles) apropiadamente, y fomenta el uso de [skins](/wiki/Skin) personalizadas. En este artícu
```suggestion
Cada estilo de juego requiere que el jugador ajuste sus [asignaciones de teclas](/wiki/Game_mode/osu!mania#controles) apropiadamente, y fomenta el uso de [skins](/wiki/Skin) personalizadas. En este artículo, las imágenes del juego usarán la skin predeterminada un poco modificada para ayudar a ilustrar varios estilos de juego.
```

2024-04-20 17:22 UTC, UnknownOsu commented on wiki/Beatmapping/osu!mania_10K_plus_playstyles/es.md
> +Mientras 10K es tratado por el [cliente del juego](/wiki/Client) como modo «[co-op](/wiki/Game_mode/osu!mania#co-op)», los mappers normalmente lo tratan como un modo de teclas normal. Esto es porque
```suggestion
Mientras 10K es tratado por el [cliente del juego](/wiki/Client) como modo «[co-op](/wiki/Game_mode/osu!mania#co-op)», los mappers normalmente lo tratan como un modo de teclas normal. Esto se debe a que cada tecla puede ser presionada por un único dedo, y no es necesario tener en cuenta ninguna colocación especial o asignación de teclas.
```

2024-04-20 17:40 UTC, UnknownOsu approved these changes

2024-04-24 20:12 UTC, TicClick approved these changes

2024-04-24 20:14 UTC, merged