[ES] Add `TAG beatmaps`
ppy/osu-wiki pull request #11300
Opened 2024-04-20 05:38 UTC by Ladwick

**Article translation** – `Beatmaps TAG`

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-20 06:41 UTC, UnknownOsu requested changes

2024-04-20 06:41 UTC, UnknownOsu commented on wiki/Beatmap/TAG_beatmaps/es.md
> +*No confundir con etiquetas, que son [parte de los metadatos de un beatmap](/wiki/Client/Beatmap_editor/Song_setup).*
```suggestion
*No confundir con las etiquetas, que son [parte de los metadatos de un beatmap](/wiki/Client/Beatmap_editor/Song_setup).*
```

2024-04-20 06:41 UTC, UnknownOsu commented on wiki/Beatmap/TAG_beatmaps/es.md
> +**Beatmaps TAG** (o simplemente *TAG*) son beatmaps que han sido hechos específicamente para los [modos Tag co-op o Tag-team VS](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs) en [salas
```suggestion
Los **beatmaps TAG** (o simplemente *TAG*) son beatmaps que han sido creados específicamente para los [modos Tag co-op o Tag-team VS](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs) de las [salas multijugador](/wiki/Client/Interface/Multiplayer). Por lo tanto, estos beatmaps a menudo requieren el juego cooperativo entre dos o más jugadores en la sala para poder ser completados.
```

2024-04-20 06:41 UTC, UnknownOsu commented on wiki/Beatmap/TAG_beatmaps/es.md
> +En estos modos, cada jugador es responsable de un [comboset](/wiki/Beatmapping/Combo), y a lo largo de la canción, los jugadores cambian entre combosets. Por esta razón, los beatmaps TAG están diseña
```suggestion
En estos modos, cada jugador es responsable de una cadena de un [combo](/wiki/Beatmapping/Combo), y a lo largo de la canción, los jugadores alternan entre las distintas cadenas de combo. Por esta razón, los beatmaps TAG están diseñados de tal manera que sus cadenas de combo están colocadas muy separadas entre sí, lo que hace casi imposible que un solo jugador pase el beatmap.
```

2024-04-20 06:41 UTC, UnknownOsu commented on wiki/Beatmap/TAG_beatmaps/es.md
> +Las [dificultades](/wiki/Beatmap/Difficulty) TAG suelen indicarse mediante el uso del término `TAG` en el nombre de la dificultad del beatmap. La mayoría de las veces, `TAG` irá seguido de un número,
```suggestion
Las [dificultades](/wiki/Beatmap/Difficulty) TAG suelen indicarse mediante el uso del término `TAG` en el nombre de la dificultad del beatmap. La mayoría de las veces, `TAG` irá seguido de un número, que generalmente indica para cuántos jugadores está destinada la dificultad (por ejemplo, `TAG2` para dos jugadores o `TAG4` para cuatro jugadores).
```

2024-04-20 06:41 UTC, UnknownOsu commented on wiki/Beatmap/TAG_beatmaps/es.md
> +Debido a sus características, las dificultades TAG no suelen estar clasificadas o son [aprobadas](/wiki/Beatmap/Category#approved) o [amadas](/wiki/Beatmap/Category#loved). Sin embargo, en contadas o
```suggestion
Debido a sus características, las dificultades TAG suelen ser no clasificadas, [aprobadas](/wiki/Beatmap/Category#approved) o [amadas](/wiki/Beatmap/Category#loved). Sin embargo, en raras ocasiones, un beatmap TAG que siga los [criterios de clasificación](/wiki/Ranking_criteria) y sea considerado adecuado para ser clasificado por los [Beatmap Nominators](/wiki/People/Beatmap_Nominators) puede llegar a la sección de [clasificados](/wiki/Beatmap/Category#ranked).
```

2024-04-20 07:56 UTC, agatemosu commented on wiki/Beatmap/TAG_beatmaps/es.md
> +En estos modos, cada jugador es responsable de una cadena de un [combo](/wiki/Beatmapping/Combo), y a lo largo de la canción, los jugadores alternan entre las distintas cadenas de combo. Por esta raz
```suggestion
En estos modos, cada jugador es responsable de una [cadena de combo](/wiki/Beatmapping/Combo), y a lo largo de la canción, los jugadores alternan entre las distintas cadenas de combo. Por esta razón, los beatmaps TAG están diseñados de tal manera que sus cadenas de combo están colocadas muy separadas entre sí, lo que hace casi imposible que un solo jugador pase el beatmap.
```

2024-04-20 07:57 UTC, agatemosu commented on wiki/Beatmap/TAG_beatmaps/es.md
> +Las [dificultades](/wiki/Beatmap/Difficulty) TAG suelen indicarse mediante el uso del término `TAG` en el nombre de la dificultad del beatmap. La mayoría de las veces, `TAG` irá seguido de un número,
```suggestion
Las [dificultades](/wiki/Beatmap/Difficulty) TAG suelen indicarse mediante el uso del término `TAG` en el nombre de la dificultad del beatmap. La mayoría de las veces, `TAG` irá seguido de un número, que generalmente indica para cuántos jugadores está destinada la dificultad (p. ej. `TAG2` para dos jugadores o `TAG4` para cuatro jugadores).
```

2024-04-24 21:43 UTC, UnknownOsu approved these changes

2024-04-26 19:21 UTC, TicClick approved these changes

2024-04-26 19:23 UTC, merged