[ES] Add `Skinning/skin.ini`
ppy/osu-wiki pull request #11317
Opened 2024-04-24 01:29 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Esto tiñe los números que se muestran en la superposición de entrada.
```suggestion
    - Esto tiñe los números que se muestran en la superposición de las teclas.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿De qué color debería colorearse todos los cuerpos de los sliders?
```suggestion
  - Pregunta: ¿De qué color deberían colorearse todos los cuerpos de los sliders?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Por defecto: *usar el color del combo actual*
```suggestion
  - Por defecto: *usa el color del combo actual*
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿De qué color debería colorearse la bola del slider predeterminada?
```suggestion
  - Pregunta: ¿De qué color deberían colorearse las bolas predeterminadas de los sliders?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Qué color se debería añadir al fondo del spinner?
```suggestion
  - Pregunta: ¿Qué color se debería añadir al fondo de los spinners?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +- Si deseas personalizar completamente el escenario de osu!mania, usa la versión de skin `2.5` o superior.
```suggestion
- Si deseas personalizar completamente el escenario de osu!mania, usa la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: On which height should the stage lights be drawn at?
```suggestion
  - Pregunta: ¿A qué altura deberían trazarse las luces del escenario?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Requiere la versión de skin `2.5` o superior.
```suggestion
    - Requiere la versión de skin `2.5` o versiones superiores.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen de la tecla no presionada de la columna?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de las teclas no presionadas de la columna?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Esto es para la imagen de la tecla inactiva de la columna específica.
```suggestion
    - Esto es para la imagen de las teclas inactivas de la columna específica.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen de la tecla presionada de la columna?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de las teclas presionadas de la columna?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Esto es para la imagen de la tecla presionada de la columna específica.
```suggestion
    - Esto es para la imagen de las teclas presionadas de la columna específica.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen de la nota de la columna?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de las notas de la columna?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Esto es para la imagen de la nota de la columna específica.
```suggestion
    - Esto es para la imagen de las notas de la columna específica.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen de la cabeza de la nota larga de la columna?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de las cabezas de las notas largas de la columna?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Esto es para la imagen de la cabeza de la nota larga de la columna específica.
```suggestion
    - Esto es para la imagen de las cabezas de las notas largas de la columna específica.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen del cuerpo de la nota larga de la columna?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de los cuerpos de las notas largas de la columna?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Esto es para la imagen del cuerpo de la nota larga de la columna específica.
```suggestion
    - Esto es para la imagen de los cuerpos de las notas largas de la columna específica.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen de la cola de la nota larga de la columna?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de las colas de las notas largas de la columna?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +    - Esto es para la imagen de la cola de la nota larga de la columna específica.
```suggestion
    - Esto es para la imagen de las colas de las notas largas de la columna específica.
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen de abajo del escenario?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen abajo del escenario?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen de la iluminación de la nota?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de la iluminación de las notas?
```

2024-04-24 02:28 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/skin.ini/es.md
> +  - Pregunta: ¿Cuál será el nombre de la imagen luminosa de la nota larga?
```suggestion
  - Pregunta: ¿Cuál será el nombre de la imagen de la iluminación de las notas largas?
```

2024-05-02 22:53 UTC, TicClick approved these changes

2024-05-02 23:02 UTC, merged