[ES] Add `Skinning/osu!taiko`
ppy/osu-wiki pull request #11319
Opened 2024-04-24 01:29 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| Versiones | Animable | Skinnable para los beatmaps | Modo de mezcla | Origen | Tamaño SD sugerido |
```suggestion
| Versiones | Animable | Personalizable para los beatmaps | Modo de mezcla | Origen | Tamaño SD sugerido |
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| Versiones | Animable | Skinnable para los beatmaps | Modo de mezcla | Origen | Tamaño SD sugerido |
Queda mejor así, te da a entender que se puede personalizar el archivo (o no) para los beatmaps.

Lo mismo para los otros

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +- Esto sustituye a `pippidonkiai` si el jugador falla una nota durante el [kiai time](/wiki/Gameplay/Kiai_time).
```suggestion
- Esto sustituirá a `pippidonkiai` si el jugador falla una nota durante el [kiai time](/wiki/Gameplay/Kiai_time).
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +- `pippidonfail.png` lo sustituye si el jugador falla una nota durante el kiai time.
```suggestion
- `pippidonfail.png` lo sustituirá si el jugador falla una nota durante el kiai time.
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| Todas | ![No][false] | ![Sí][true] | Multiplicative | Centro | 118x118 |
```suggestion
| Todas | ![No][false] | ![Sí][true] | Multiplicativo | Centro | 118x118 |
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| Todas | ![No][false] | ![Sí][true] | Multiplicative | Centro | 118x118 |
```suggestion
| Todas | ![No][false] | ![Sí][true] | Multiplicativo | Centro | 118x118 |
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| v2.1+ | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 90x200 |
```suggestion
| v2.1 o posteriores | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 90x200 |
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v1-v2.0: (29,266) (y (86,266) cuando se refleja)
```suggestion
  - Versión 1.0 - versión 2.0: (29,266) (y (86,266) cuando se refleja)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v2.1+: (0,216) (y (90,216) cuando se refleja)
```suggestion
  - Versión 2.1 o versiones posteriores: (0,216) (y (90,216) cuando se refleja)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| v2.1+ | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 90x200 |
```suggestion
| v2.1 o posteriores | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 90x200 |
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v1-v2.0: (85,253) ((13,253) cuando se refleja)
```suggestion
  - Versión 1.0 - versión 2.0: (85,253) ((13,253) cuando se refleja)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v2.1+: (90,216) (y (0,216) cuando se refleja)
```suggestion
  - Versión 2.1 o versiones posteriores: (90,216) (y (0,216) cuando se refleja)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v2.1+: (0,216)
```suggestion
  - Versión 2.1 o versiones posteriores: (0,216)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v2.1+: (0,216)
```suggestion
  - Versión 2.1 o versiones posteriores: (0,216)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| v2.1+ | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 1024x200 |
```suggestion
| v2.1 o posteriores | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 1024x200 |
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v1.0-v2.0: (181,216)
```suggestion
  - Versión 1.0 - versión 2.0: (181,216)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +  - v1.0-v2.0: (181,216)
```suggestion
  - Versión 1.0 - versión 2.0: (181,216)
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +| v2.1+ | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 1024x200 |
```suggestion
| v2.1 o posteriores | ![No][false] | ![No][false] (véase las notas) | Normal | Arriba a la izquierda | 1024x200 |
```

2024-04-24 02:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!taiko/es.md
> +- El ancho de la imagen SD debe tener exactamente 1 px de ancho.
```suggestion
- El ancho de la imagen SD debe tener exactamente 1 píxel de ancho.
```

2024-05-02 22:54 UTC, TicClick approved these changes

2024-05-02 23:08 UTC, merged