[ES] Add `Skinning/osu!mania`
ppy/osu-wiki pull request #11320
Opened 2024-04-24 01:29 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-24 03:02 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-24 03:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!mania/es.md
> +| Todas | ![No][false] (véase las notas) | ![Sí][true] | Normal | Abajo a la izquierda | Altura máxima: 768px |
```suggestion
| Todas | ![No][false] (véase las notas) | ![Sí][true] | Normal | Abajo a la izquierda | Altura máxima: 768 píxeles |
```

2024-04-24 03:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!mania/es.md
> +| Todas | ![No][false] | ![No][false] | Normal | Abajo a la derecha | Altura máxima: 768px |
```suggestion
| Todas | ![No][false] | ![No][false] | Normal | Abajo a la derecha | Altura máxima: 768 píxeles |
```

2024-04-24 03:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!mania/es.md
> +| Todas | ![No][false] | ![No][false] | Normal | Abajo a la derecha | Altura máxima: 768px |
```suggestion
| Todas | ![No][false] | ![No][false] | Normal | Abajo a la derecha | Altura máxima: 768 píxeles  |
```

2024-04-24 03:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!mania/es.md
> +- Este elemento debe estar adaptado a una altura para un campo de juego de 480px.
```suggestion
- Este elemento debe estar adaptado a una altura para un campo de juego de 480 píxeles .
```

2024-04-24 03:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!mania/es.md
> +| Todas | ![Sí][true] | ![No][false] | Multiplicativo | Abajo | Altura máxima: 768px |
```suggestion
| Todas | ![Sí][true] | ![No][false] | Multiplicativo | Abajo | Altura máxima: 768 píxeles  |
```

2024-05-02 22:56 UTC, TicClick approved these changes

2024-05-02 23:14 UTC, merged