[ES] Add `Skinning/Sounds`
ppy/osu-wiki pull request #11323
Opened 2024-04-24 01:29 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-24 18:18 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-24 18:18 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Sounds/es.md
> +- Se reproduce al pulsar `Atrás` en el menú principal.
```suggestion
- Se reproduce al hacer clic en `Atrás` en el menú principal.
```

2024-04-24 18:18 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Sounds/es.md
> +- A pesar de lo anterior, a esto se le puede poner un audio para el asistente de compensación y los plátanos en osu!catch (el tono sube por cada plátano capturado).
```suggestion
- A pesar de lo anterior, a esto se le puede poner un audio para el asistente de compensación y los plátanos en osu!catch (el tono sube por cada plátano atrapado).
```

2024-04-24 18:18 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Sounds/es.md
> +### Para la cuenta atrás
```suggestion
### Para la cuenta regresiva
```

2024-05-02 22:59 UTC, TicClick approved these changes

2024-05-02 23:25 UTC, TicClick approved these changes

2024-05-02 23:26 UTC, merged