[ES] Add `Skinning/osu!catch`
ppy/osu-wiki pull request #11321
Opened 2024-04-24 01:29 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-04-24 03:06 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-04-24 03:06 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!catch/es.md
> +| 2.3 o superiores | ![Sí][true] | ![Sí][true] | Normal | Arriba | Anchura mínima: 302px |
```suggestion
| 2.3 o superiores | ![Sí][true] | ![Sí][true] | Normal | Arriba | Anchura mínima: 302 píxeles  |
```

2024-04-24 03:06 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/osu!catch/es.md
> +- En la versión 2.2 o anteriores, se usará `comboburst.png` en su lugar.
```suggestion
- En la versión 2.2 o versiones anteriores, se usará `comboburst.png` en su lugar.
```

2024-05-02 22:56 UTC, TicClick approved these changes

2024-05-02 23:15 UTC, merged