[ES] Add `Community/osu!monthly`
ppy/osu-wiki pull request #11379
Opened 2024-05-11 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 16:18 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 16:18 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/osu!monthly/es.md
> +La edición original del osu!monthly, fundada por ::{ flag=US }:: [jjrocks](https://osu.ppy.sh/users/30985) y ::{ flag=GB }:: [Corin](https://osu.ppy.sh/users/639270), se publicó de marzo a octubre de
```suggestion
La edición original de osu!monthly, fundada por ::{ flag=US }:: [jjrocks](https://osu.ppy.sh/users/30985) y ::{ flag=GB }:: [Corin](https://osu.ppy.sh/users/639270), se publicó de marzo a octubre de 2011. Comenzó como un documento de Google, pero rápidamente evolucionó a un formato PDF parecido a una revista impresa. Esta edición fue bien conocida por su amplia variedad de artículos, así como por su dirección artística distintiva y creativa.
```

2024-05-13 16:18 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/osu!monthly/es.md
> +Puedes encontrar más información en el [sitio web de jjrocks](https://web.archive.org/web/20201112030400/http://jjwanda.com/projects/osumonthly.html) (archivado). Varios enlaces sobre el proyecto se
```suggestion
Puedes encontrar más información en el [sitio web de jjrocks](https://web.archive.org/web/20201112030400/http://jjwanda.com/projects/osumonthly.html) (archivado). Varios enlaces sobre el proyecto se encuentran en la parte inferior del [sitio web de osu!monthly](https://osumonthly.com/).
```

2024-05-13 16:18 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/osu!monthly/es.md
> +Inspirado en la primera edición del osu!monthly, ::{ flag=GB }:: [mangomizer](https://osu.ppy.sh/users/1893718) y ::{ flag=US }:: [clayton](https://osu.ppy.sh/users/3666350) fundaron un nuevo equipo
```suggestion
Inspirado en la primera edición de osu!monthly, ::{ flag=GB }:: [mangomizer](https://osu.ppy.sh/users/1893718) y ::{ flag=US }:: [clayton](https://osu.ppy.sh/users/3666350) fundaron un nuevo equipo con el objetivo de continuar el proyecto donde lo dejaron. Se publicaron nuevas versiones de la revista desde octubre de 2017 hasta febrero de 2018.
```

2024-05-22 05:48 UTC, cl8n approved these changes

2024-05-22 05:50 UTC, merged