[ES] Add `Community/osu! Talk Event`
ppy/osu-wiki pull request #11381
Opened 2024-05-11 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 16:31 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 16:31 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/osu!_Talk_Event/es.md
> +Las charlas también se transmiten en vivo en el [canal de Twitch osu! University](https://twitch.tv/osuuniversity) y las grabaciones de cada charla están disponibles en su [canal de YouTube](https://
```suggestion
Las charlas también se transmiten en vivo en el [canal de Twitch de osu! University](https://twitch.tv/osuuniversity) y las grabaciones de cada charla están disponibles en su [canal de YouTube](https://www.youtube.com/c/osuuniversity).
```

2024-05-13 16:31 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/osu!_Talk_Event/es.md
> +Los oradores realizan sus charlas en un canal escenario en el [servidor de Discord osu!](/wiki/Community/osu!_Discord_server). Durante el evento, se abren hilos de debate en el canal `#community-meet
```suggestion
Los oradores realizan sus charlas en un canal escenario en el [servidor de Discord osu!](/wiki/Community/osu!_Discord_server). Durante el evento, se abren hilos de discusión en el canal `#community-meetings`.
```

2024-05-22 04:55 UTC, cl8n approved these changes

2024-05-22 04:59 UTC, merged