[ES] Add `Community/osu! Talk Event/Overcoming Obstacles`
ppy/osu-wiki pull request #11382
Opened 2024-05-11 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 16:34 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 16:34 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/es.md
> +Los oradores dieron sus charlas en un canal escenario en el [servidor de Discord osu!](/wiki/Community/osu!_Discord_server). Durante el evento se abrieron hilos de debate en el canal `#community-meet
```suggestion
Los oradores dieron sus charlas en un canal escenario en el [servidor de Discord osu!](/wiki/Community/osu!_Discord_server). Durante el evento se abrieron hilos de discusión en el canal `#community-meetings`.
```

2024-05-13 16:34 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/es.md
> +Las charlas también se transmitieron en vivo por [canal de Twitch osu! University](https://twitch.tv/osuuniversity) y las grabaciones de cada charla están disponibles en en su [canal de YouTube](http
```suggestion
Las charlas también se transmitieron en vivo por [canal de Twitch de osu! University](https://twitch.tv/osuuniversity) y las grabaciones de cada charla están disponibles en en su [canal de YouTube](https://www.youtube.com/c/osuuniversity).
```

2024-05-22 04:58 UTC, cl8n approved these changes

2024-05-22 05:27 UTC, merged