[ES] Add `Community/Video series/osu!talk`
ppy/osu-wiki pull request #11385
Opened 2024-05-11 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 17:13 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 17:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!talk/es.md
> +La serie de podcasts está preparada para que cualquiera pueda participar en la sesión en directo y hacer preguntas durante la parte de [preguntas y respuestas](https://en.wikipedia.org/wiki/Q&A) del
```suggestion
La serie de podcasts está preparada para que cualquiera pueda participar en la sesión en directo y hacer preguntas durante la parte de [preguntas y respuestas](https://en.wikipedia.org/wiki/Q&A) del episodio. No se transmiten en vivo en ningún sitio, ya que preferimos animar a los usuarios a que se unan y participen ellos mismos.
```

2024-05-13 17:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!talk/es.md
> +| 4 | [dkun](https://osu.ppy.sh/users/154400) | BAT/miembro retirado del osu!monthly | [Enlace](https://www.youtube.com/watch?v=_nFI71fG7-c) |
```suggestion
| 4 | [dkun](https://osu.ppy.sh/users/154400) | BAT/miembro retirado de osu!monthly | [Enlace](https://www.youtube.com/watch?v=_nFI71fG7-c) |
```

2024-05-22 05:44 UTC, cl8n approved these changes

2024-05-22 05:46 UTC, merged