[ES] Add `Community/cavoe's osu! event`
ppy/osu-wiki pull request #11383
Opened 2024-05-11 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 16:46 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 16:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/cavoe's_osu!_event/es.md
> +Como un evento llamado simplemente «osu! event» con solo unas 35 personas y que duró 3 días, COE comenzó en 2017 como una «reunión nacional holandesa con algunos visitantes de otros países» en el caf
```suggestion
Como un evento llamado simplemente «osu! event» con solo unas 35 personas y que duró 3 días, COE comenzó en 2017 como una «reunión nacional neerlandés con algunos visitantes de otros países» en el café De Hangar en Eindhoven.
```

2024-05-13 16:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/cavoe's_osu!_event/es.md
> +En 2022, COE se hizo aún más grande y contó con 750 personas, una sala de juegos de ritmo, más socios, incluso más eventos escénicos y la introducción de las «cuevas de jugadores», salas privadas que
```suggestion
En 2022, COE se hizo aún más grande y contó con 750 personas, una sala de juegos de ritmo, más socios, incluso más eventos escénicos y la introducción de las «gamer caves», salas privadas que los asistentes podían alquilar con anticipación. También introdujo un torneo de osu! con un premio total de 3000 euros.
```

2024-05-22 05:00 UTC, cl8n approved these changes

2024-05-22 05:08 UTC, merged