[ES] Add `Community/Video series/osu!mapping`
ppy/osu-wiki pull request #11386
Opened 2024-05-11 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 17:22 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 17:22 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!mapping/es.md
> +osu!mapping comenzó como respuesta a [una publicación de reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) en la que se pedía a los mappers que crearan vídeos
```suggestion
osu!mapping comenzó como respuesta a [una publicación de reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) en la que se le pedía a los mappers que crearan vídeos de comentarios sobre el mapping. El 31 de julio de 2016, pishifat subió el primer vídeo: [osu!mapping: concepts](https://www.youtube.com/watch?v=oL3az8FhlB4). En el vídeo, explica cómo iba a crear el comentario como el redditor sugirió, pero finalmente decidió no hacerlo porque un comentario directo sobre el proceso de pensamiento al crear un mapa no haría un buen trabajo de introducción a la amplia variedad de conceptos del mapping para los nuevos mappers. En su lugar, optó por iniciar una serie de vídeos en la que cada episodio se centraría en un concepto específico, profundizando en sus usos e importancia por separado.
```

2024-05-13 17:22 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!mapping/es.md
> +Al principio, la serie se centraba en este tipo de contenido de tipo tutorial, pero a los pocos meses empezó a diversificarse para incluir debates sobre el estado del mapping y el modding, comentario
```suggestion
Al principio, la serie se centraba en este tipo de contenido de tipo tutorial, pero a los pocos meses empezó a diversificarse para incluir debates sobre el estado del mapping y el modding, comentarios personales/opiniones y entrevistas. También se han presentado algunos proyectos de investigación en un formato similar a los vídeos de osu!mapping, entre los que destaca [un estudio sobre las influencias de los mappers](https://www.youtube.com/watch?v=TigwDc5iOcw).
```

2024-05-22 05:40 UTC, cl8n approved these changes

2024-05-22 05:42 UTC, merged