[ES] Add `Community/cavoe's osu! event/2023`
ppy/osu-wiki pull request #11384
Opened 2024-05-11 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 17:09 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 17:09 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/cavoe's_osu!_event/2023/es.md
> +The Global Taiko Showdown team hosted a 1v1 osu!taiko LAN tournament at the event, with a fully custom-made mappool complete with original compositions for each beatmap. osu!taiko players of any rank
```suggestion
El equipo del Global Taiko Showdown organizó un torneo LAN de 1v1 de osu!taiko en el evento, con una mappool totalmente personalizada con composiciones originales para cada beatmap. Podían participar jugadores de osu!taiko de cualquier rango, siempre y cuando estuvieran presentes durante todo el torneo.
```

2024-05-13 17:09 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/cavoe's_osu!_event/2023/es.md
> +### Torneo 1v1 de osu! en COE
```suggestion
### Torneo de 1v1 de osu! en COE
```

2024-05-13 17:09 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/cavoe's_osu!_event/2023/es.md
> +*Página principal: [Torneo 1v1 de osu! en COE 2023](/wiki/Tournaments/COE/COE_2023)*
```suggestion
*Página principal: [Torneo de 1v1 de osu! en COE 2023](/wiki/Tournaments/COE/COE_2023)*
```

2024-05-13 17:09 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/cavoe's_osu!_event/2023/es.md
> +![Banner del torneo 1v1 de osu! en COE](/wiki/Tournaments/COE/COE_2023/img/banner.png)
```suggestion
![Banner del torneo de 1v1 de osu! en COE](/wiki/Tournaments/COE/COE_2023/img/banner.png)
```

2024-05-13 17:09 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/cavoe's_osu!_event/2023/es.md
> +| Último superviviente | 3 de agosto (12:30) | Un juego de trivia en el que se eliminaban a los jugadores que más se alejaban del número correcto |
```suggestion
| Survivor | 3 de agosto (12:30) | Un juego de trivia en el que se eliminaban a los jugadores que más se alejaban del número correcto |
```

2024-05-22 05:05 UTC, cl8n approved these changes

2024-05-22 05:06 UTC, merged