[ES] Add `Community/Video series/osu!academy`
ppy/osu-wiki pull request #11393
Opened 2024-05-11 20:30 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-13 17:45 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-13 17:45 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!academy/es.md
> +| 4 | [Introduction to CtB](https://www.youtube.com/watch?v=6WKZE2HPOK8) | [ztrot](https://osu.ppy.sh/users/6347) repasa los conceptos básicos de osu!catch, incluidos los controles, jugabilidad, obje
```suggestion
| 4 | [Introduction to CtB](https://www.youtube.com/watch?v=6WKZE2HPOK8) | [ztrot](https://osu.ppy.sh/users/6347) repasa los conceptos básicos de osu!catch, incluidos los controles, la jugabilidad, los objetos y más. |
```

2024-05-13 17:45 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!academy/es.md
> +| 23 | [Community Modding](https://www.youtube.com/watch?v=MxlB__wjt9A) | [ztrot](https://osu.ppy.sh/users/6347) y [Shiro](https://osu.ppy.sh/users/113005) explican el concepto del modding comunitari
```suggestion
| 23 | [Community Modding](https://www.youtube.com/watch?v=MxlB__wjt9A) | [ztrot](https://osu.ppy.sh/users/6347) y [Shiro](https://osu.ppy.sh/users/113005) explican el concepto del modding comunitario, un modding basado en el trabajo en equipo. |
```

2024-05-13 17:45 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!academy/es.md
> +| 26 | [Closing the Game](https://www.youtube.com/watch?v=y61v2QCHlpY) | [ztrot](https://osu.ppy.sh/users/6347) explica cómo salir de osu!. |
```suggestion
| 26 | [Closing the Game](https://www.youtube.com/watch?v=y61v2QCHlpY) | [ztrot](https://osu.ppy.sh/users/6347) explica cómo dejar de jugar osu!. |
```

2024-05-13 17:45 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Video_series/osu!academy/es.md
> +**[Academy Bytes](https://www.youtube.com/playlist?list=PLmWVQsxi34bMq9xkL8affDZpUzSTXa5_r)** es una serie de vídeos cortos realizados por [ztrot](https://osu.ppy.sh/users/6347) en los que se explica
```suggestion
**[Academy Bytes](https://www.youtube.com/playlist?list=PLmWVQsxi34bMq9xkL8affDZpUzSTXa5_r)** es una serie de vídeos cortos realizada por [ztrot](https://osu.ppy.sh/users/6347) en los que se explica la disposición y el uso de técnicas de mapeo útiles y de uso común.
```

2024-05-20 09:53 UTC, agatemosu commented on wiki/Community/Video_series/osu!academy/es.md
> +| 26 | [Closing the Game](https://www.youtube.com/watch?v=y61v2QCHlpY) | [ztrot](https://osu.ppy.sh/users/6347) explica cómo dejar de jugar osu!. |
```suggestion
| 26 | [Closing the Game](https://www.youtube.com/watch?v=y61v2QCHlpY) | [ztrot](https://osu.ppy.sh/users/6347) explica cómo cerrar osu!. |
```
```suggestion
| 26 | [Closing the Game](https://www.youtube.com/watch?v=y61v2QCHlpY) | [ztrot](https://osu.ppy.sh/users/6347) explica cómo salir de osu!. |
```

2024-05-20 13:42 UTC, UnknownOsu commented on wiki/Community/Video_series/osu!academy/es.md
> +| 26 | [Closing the Game](https://www.youtube.com/watch?v=y61v2QCHlpY) | [ztrot](https://osu.ppy.sh/users/6347) explica cómo dejar de jugar osu!. |
Diría que el vídeo está hecho en forma de sátira sobre el `Quit` por como está hecho.

El vídeo en sí hace referencia al `Quitting` y dejar de jugar por un rato; el cerrar el juego (literalmente) es un paso a seguir si quieres hacer "quit".

Igual puedo aceptar el cambio, pondría el de `cerrar`

2024-05-20 18:03 UTC, agatemosu approved these changes

2024-05-22 05:38 UTC, cl8n approved these changes

2024-05-22 05:40 UTC, merged