[ZH] Update osu!_tournament_client/osu!tourney/Tournament_management_commands
ppy/osu-wiki pull request #11402
Opened 2024-05-14 06:25 UTC by ChickenGoldSS

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

## Changed Files

+ Added translation about "!mp ban" command

2024-05-14 07:05 UTC, YumeMuzi approved these changes

2024-05-15 05:40 UTC, CloneWith requested changes

2024-05-15 05:40 UTC, CloneWith commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/zh.md
> +- `!mp ban <username>` - 禁用指定的玩家。
“禁用”玩家，这句话不通。
我没用过这个命令，但是从字面上来看类似于“禁止玩家进入房间”。

2024-05-15 06:10 UTC, ChickenGoldSS commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/zh.md
> +- `!mp ban <username>` - 禁用指定的玩家。
已修改为“禁止指定的玩家进入房间”。

2024-05-15 06:10 UTC, CloneWith approved these changes

2024-05-22 04:39 UTC, cl8n commented
this is missing some changes still (see <https://osu.wiki/status/diff/a4e45cf0738ff0ce2327cba8b9efe89d53e1ef9f/wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/en.md>)

2024-05-22 04:40 UTC, cl8n commented
actually I guess it's fine since you're keeping the outdated marker.

2024-05-22 04:43 UTC, cl8n approved these changes

2024-05-22 04:44 UTC, merged