[VI] add `community/how you can help`
ppy/osu-wiki pull request #11439
Opened 2024-05-22 14:37 UTC by summyvn

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-22 14:39 UTC, summyvn commented
If the translation is wrong, I will correct it when I wake up tomorrow morning

2024-05-23 09:26 UTC, avariation requested changes
Review from native speaker.

2024-05-23 09:26 UTC, avariation commented on wiki/Community/How_you_can_help!/vi.md
> +- Làm cho [wedsite](https://github.com/ppy/osu-web) ngày càng tốt hơn.
```suggestion
- Làm cho [trang web](https://github.com/ppy/osu-web) ngày càng tốt hơn.
```

2024-05-23 09:26 UTC, avariation commented on wiki/Community/How_you_can_help!/vi.md
> +Có một câu nói cổ rằng :*“bạn nên trở thành một phần của giải pháp chứ không phải của vấn đề”*. Chỉ cần làm theo câu nói cổ này, bạn sẽ giúp được osu! bằng cách làm cho cộng đồng trở thành một nơi tư
```suggestion
Người xưa có câu "hãy là một phần của giải pháp, đừng là một phần của vấn đề". Chỉ cần làm theo câu nói này, bạn sẽ giúp được osu! bằng cách làm cho cộng đồng trở thành một nơi tươi sáng hơn. Mọi người sẽ luôn phàn nàn, nhưng vẫn có rất nhiều việc bạn có thể làm để giúp cải thiện tâm trạng của mọi người:
```

2024-05-23 09:26 UTC, avariation commented on wiki/Community/How_you_can_help!/vi.md
> +- [Báo cáo những kẻ gian lận khi bạn nhìn thấy chúng](/wiki/Reporting_bad_behaviour/Handling_foul_play). Vui lòng không phàn nàn về chúng thông qua các phương tiện khác vì có một cách đơn giản là`!re
```suggestion
- [Báo cáo những kẻ gian lận khi bạn nhìn thấy chúng](/wiki/Reporting_bad_behaviour/Handling_foul_play). Vui lòng không phàn nàn về những người này thông qua các phương tiện khác vì chỉ cần một câu đơn giản là `!report <username> seems to be cheating` là đủ để vấn đề của bạn đi khuất mắt chỉ trong vài phút đến vài giờ.
```

2024-05-23 09:26 UTC, avariation commented on wiki/Community/How_you_can_help!/vi.md
> +**Mặc dù bài viết này không thể đề cập đến việc bạn có thể giúp được bao nhiêu trong cộng đồng osu!, chỉ cần chơi game cũng có thể giúp osu! thậm chí còn tuyệt vời hơn nữa!**( đừng nghiện game quá, l
```suggestion
**Mặc dù bài viết này không thể đề cập tất cả các cách để bạn có thể đóng góp cho cộng đồng của osu!, nhưng chỉ cần chơi game thôi cũng có thể giúp osu! thậm chí còn tuyệt vời hơn nữa!**
```

2024-05-23 10:35 UTC, avariation requested changes
Minor changes

2024-05-23 10:35 UTC, avariation commented on wiki/Community/How_you_can_help!/vi.md
> + - [skinning](https://osu.ppy.sh/community/forums/15)
```suggestion
 - [Skinning](https://osu.ppy.sh/community/forums/15)
```

2024-05-23 10:35 UTC, avariation commented on wiki/Community/How_you_can_help!/vi.md
> +-Sử dụng nút `Mark forum as read` ở trên cùng.
```suggestion
- Sử dụng nút `Mark forum as read` ở trên cùng.
```

2024-05-23 10:35 UTC, avariation commented on wiki/Community/How_you_can_help!/vi.md
> +- Theo dõi tất cả các chủ đề mới, đọc từng chủ đề và trợ giúp khi có thể  — bạn có thể sử dụng biểu tượng chưa đọc để chắc chắn rằng bạn bắt kịp với mọi thông tin.
```suggestion
- Theo dõi tất cả các chủ đề mới, đọc từng chủ đề và trợ giúp khi có thể — bạn có thể sử dụng biểu tượng chưa đọc để chắc chắn rằng bạn bắt kịp với mọi thông tin.
```

2024-05-23 11:48 UTC, avariation approved these changes

2024-05-28 23:37 UTC, TicClick approved these changes

2024-05-28 23:37 UTC, merged