[ID] Standardise writing of index pages
ppy/osu-wiki pull request #11430
Opened 2024-05-21 07:21 UTC by Nivalyx

rn the translations of the index pages (e.g. `http://osu.ppy.sh/legal/id` and `http://osu.ppy.sh/wiki/id/Client`) are done quite differently from one another, so i thought i'd try to introduce some consistency here since in the original `en.md` pages the variations are rather minimal

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-06-16 09:07 UTC, cl8n requested changes

2024-06-16 09:07 UTC, cl8n commented on wiki/Beatmap/Pattern/osu!/id.md
> +
missing title

2024-06-19 17:52 UTC, Nivalyx commented on wiki/Beatmap/Pattern/osu!/id.md
> +
whoops

2024-06-19 20:35 UTC, cl8n approved these changes

2024-06-19 20:36 UTC, merged