[ES] Add `Offset`
ppy/osu-wiki pull request #11466
Opened 2024-05-26 02:27 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-26 17:47 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-26 17:47 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Offset/es.md
> +- [Compensación en línea](/wiki/Offset/Online_offset), un cambio de temporización aplicado por el [NAT](/wiki/People/Nomination_Assessment_Team) a beatmaps [clasificados](/wiki/Beatmap/Category#ranke
```suggestion
- [Compensación en línea](/wiki/Offset/Online_offset), un cambio de temporización aplicado por el [NAT](/wiki/People/Nomination_Assessment_Team) a los beatmaps [clasificados](/wiki/Beatmap/Category#ranked) con una compensación incorrecta para ajustarla.
```

2024-05-26 17:47 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Offset/es.md
> +- [Punto de tiempo heredado](/wiki/Client/Beatmap_editor/Timing#puntos-de-tiempo-heredados) («línea verde»), una [sección de tiempo](/wiki/Client/Beatmap_editor/Timing) que controla ajustes como el [
```suggestion
- [Punto de tiempo heredado](/wiki/Client/Beatmap_editor/Timing#puntos-de-tiempo-heredados) («línea verde»), una [sección de tiempo](/wiki/Client/Beatmap_editor/Timing) que controla los ajustes del [kiai](/wiki/Gameplay/Kiai_time), los [conjuntos de muestras](/wiki/Beatmapping/Sampleset), la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity), y el nivel de volumen de los hitsounds.
```

2024-05-26 17:47 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Offset/es.md
> +- Compensación del beatmap, la cantidad de tiempo entre el inicio del archivo de audio y el primer [tiempo fuerte](/wiki/Music_theory/Downbeat) de la canción, controlado por puntos de tiempo.
```suggestion
- Compensación del beatmap, la cantidad de tiempo entre el inicio del archivo de audio y el primer [tiempo fuerte](/wiki/Music_theory/Downbeat) de la canción, controlado por los puntos de tiempo.
```

2024-06-15 09:25 UTC, agatemosu approved these changes

2024-06-16 09:14 UTC, merged