[ES] Add `Offset/Online offset`
ppy/osu-wiki pull request #11468
Opened 2024-05-26 02:27 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-26 17:54 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-26 17:54 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Offset/Online_offset/es.md
> +La compensación en línea se implementó en septiembre de 2008[^changelog-add] para el [Beatmap Appreciation Team](/wiki/People/Beatmap_Appreciation_Team) para hacer posible arreglar la temporización d
```suggestion
La compensación en línea se implementó en septiembre de 2008[^changelog-add] para el [Beatmap Appreciation Team](/wiki/People/Beatmap_Appreciation_Team) para hacer posible arreglar la temporización de un beatmap sin desclasificarlo. Con el paso del tiempo, se hizo accesible a los miembros de los diferentes equipos que supervisaban el proceso de clasificación, como el [Quality Assurance Team](/wiki/People/Quality_Assurance_Team) (QAT), el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (NAT) y el [Global Moderation Team](/wiki/People/Global_Moderation_Team), debido a la similitud de los permisos de los grupos.
```

2024-05-26 17:54 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Offset/Online_offset/es.md
> +En abril de 2022 se añadieron los controles de compensación en línea[^new-website-offset] al nuevo sitio web, pero una semana después se limitaron únicamente a los administradores para evitar usos in
```suggestion
En abril de 2022 se añadieron los controles de la compensación en línea[^new-website-offset] al nuevo sitio web, pero una semana después se limitaron únicamente a los administradores para evitar usos indebidos.[^new-website-offset-restriction]
```

2024-05-27 21:59 UTC, TicClick submitted a review, later dismissed

2024-05-27 22:04 UTC, UnknownOsu commented
I was waiting for the Spanish image ;(

2024-06-16 09:12 UTC, cl8n approved these changes

2024-06-16 09:42 UTC, merged