[ES] Add `Modding/Bubble`
ppy/osu-wiki pull request #11473
Opened 2024-05-26 02:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-28 17:23 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-28 17:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Bubble/es.md
> +Después de que el [sistema de discusiones para los beatmaps](/wiki/Beatmap_discussion) se implementara por completo y se convirtiera en la interfaz principal para el modding en noviembre de 2017, los
```suggestion
Después de que el [sistema de discusiones de los beatmaps](/wiki/Beatmap_discussion) se implementara por completo y se convirtiera en la interfaz principal para el modding en noviembre de 2017, los controles de gestión de los beatmaps basados ​​en los foros se eliminaron gradualmente y las burbujas fueron naturalmente reemplazadas por nominaciones.
```

2024-05-28 17:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Bubble/es.md
> +- El requisito para que un beatmap fuera considerado para la categoría [clasificado](/wiki/Beatmap/Category#ranked) era tener una sola burbuja.
```suggestion
- El requisito para que un beatmap fuera considerado para la categoría [clasificados](/wiki/Beatmap/Category#ranked) era tener una sola burbuja.
```

2024-05-28 17:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Bubble/es.md
> +- Los beatmaps de la categoría [aprobado](/wiki/Beatmap/Category#approved) debían tener dos burbujas consecutivas colocadas por dos miembros diferentes del BAT. El 2 de junio de 2017, este límite se
```suggestion
- Los beatmaps de la categoría [aprobados](/wiki/Beatmap/Category#approved) debían tener dos burbujas consecutivas colocadas por dos miembros diferentes del BAT. El 2 de junio de 2017, este límite se cambió a una sola burbuja.
```

2024-05-28 17:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Bubble/es.md
> +En ambos casos, el icono del hilo del beatmap se establecería en una burbuja reventada (![Icono de la burbuja reventada](/wiki/shared/icon/bubble-pop.gif)). Si se reventaba una burbuja manualmente, s
```suggestion
En ambos casos, el icono del hilo del beatmap se establecería en una burbuja reventada (![icono de la burbuja reventada](/wiki/shared/icon/bubble-pop.gif)). Si se reventaba una burbuja manualmente, se suponía que el miembro del BAT o el MAT que había colocado el icono se aseguraría de que se realizaran los cambios necesarios en el mapa antes de que continuara con el proceso de clasificación.
```

2024-06-16 10:43 UTC, cl8n submitted a review, later dismissed

2024-06-16 10:53 UTC, cl8n approved these changes

2024-06-16 10:54 UTC, merged