[ES] Add `Rules/Code of conduct for modding and mapping`
ppy/osu-wiki pull request #11474
Opened 2024-05-26 02:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-28 17:58 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-28 17:58 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/es.md
> +  - Si eres nuevo, no tengas miedo de decirlo. Así, los miembros más experimentados de la comunidad podrán orientarte. ¡Todo el mundo fue nuevo y estuvo en tu lugar alguna vez!
```suggestion
  - Si eres nuevo, no tengas miedo de decirlo. De esta manera, los miembros más experimentados de la comunidad podrán orientarte. ¡Todo el mundo fue nuevo y estuvo en tu lugar alguna vez!
```

2024-05-28 17:58 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/es.md
> +  - **Problemas intersubjetivos** - No están prohibidos por las reglas, pero son considerados «incorrectos» por la mayoría de las personas. Debería arreglarse en la mayoría de los casos, a menos que
```suggestion
  - **Problemas intersubjetivos** - No están prohibidos por las reglas, pero son considerados «incorrectos» por la mayoría de las personas. Deberían arreglarse en la mayoría de los casos, a menos que haya argumentos intersubjetivos opuestos de igual importancia, o si el mapper puede explicar exhaustivamente por qué cree que es aceptable.
```

2024-05-28 17:58 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/es.md
> +  - **Problemas subjetivos** - Algo que crees o piensas a nivel personal. Podría volverse intersubjetivo si mucha gente está de acuerdo con ello.
```suggestion
  - **Problemas subjetivos** - Algo que crees o piensas a nivel personal. Podrían volverse intersubjetivos si muchas personas están de acuerdo con ellos.
```

2024-06-16 10:44 UTC, cl8n submitted a review, later dismissed

2024-06-16 11:03 UTC, cl8n approved these changes

2024-06-16 11:04 UTC, merged