[ES] Update `Client/Beatmap editor/Timing`
ppy/osu-wiki pull request #11477
Opened 2024-05-26 06:42 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-26 18:48 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-26 18:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Beatmap_editor/Timing/es.md
>  | `BPM` | [Tempo](/wiki/Music_theory/Tempo) del punto de tiempo actual, medido en pulsos por minuto (BPM). |
```suggestion
| `BPM` | [Tempo](/wiki/Music_theory/Tempo) del punto de tiempo actual, medido en pulsaciones por minuto (BPM). |
```

2024-05-26 18:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Beatmap_editor/Timing/es.md
> +- Para seleccionar múltiples puntos de tiempo diferentes, mantén presionada la tecla `Ctrl` mientras haces clic en ellos
```suggestion
- Para seleccionar varios puntos de tiempo por separado, mantén presionada la tecla `Ctrl` mientras haces clic en ellos
```

2024-05-26 18:48 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Beatmap_editor/Timing/es.md
> +- Para seleccionar varios puntos de tiempo seguidos, haz clic en el primero y luego haz clic en el último mientras mantienes presionada la tecla `Mayús`
```suggestion
- Para seleccionar varios puntos de tiempo a la vez, haz clic en el primero y luego haz clic en el último mientras mantienes presionada la tecla `Mayús`
```

2024-06-15 10:19 UTC, agatemosu commented on wiki/Client/Beatmap_editor/Timing/es.md
> +  - compensación roja
```suggestion
  - offset rojo
  - compensación roja
```

2024-06-15 10:19 UTC, agatemosu commented on wiki/Client/Beatmap_editor/Timing/es.md
> +  - compensación no heredada
```suggestion
  - offset no heredado
  - compensación no heredada
```

2024-06-15 10:19 UTC, agatemosu commented on wiki/Client/Beatmap_editor/Timing/es.md
> +  - compensación verde
```suggestion
  - offset verde
  - compensación verde
```

2024-06-15 10:19 UTC, agatemosu commented on wiki/Client/Beatmap_editor/Timing/es.md
> +  - compensación heredada
```suggestion
  - offset heredado
  - compensación heredada
```

2024-06-15 19:05 UTC, agatemosu approved these changes

2024-06-16 10:44 UTC, cl8n approved these changes

2024-06-16 11:21 UTC, cl8n approved these changes

2024-06-16 11:22 UTC, merged