[ES] Add `Modding/Nuke`
ppy/osu-wiki pull request #11471
Opened 2024-05-26 02:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-26 18:02 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-26 18:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Nuke/es.md
> +# Símbolos nucleares
```suggestion
# Iconos nucleares
```

2024-05-26 18:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Nuke/es.md
> +Los **símbolos nucleares** fueron una herramienta de moderación para los [beatmaps](/wiki/Beatmap) en los primeros años de osu! y el sistema de [modding en los foros](/wiki/Modding/Forum_modding). Cu
```suggestion
Los **iconos nucleares** fueron una herramienta de moderación para los [beatmaps](/wiki/Beatmap) en los primeros años de osu! y el sistema de [modding en los foros](/wiki/Modding/Forum_modding). Cualquier beatmap que se considerara que incumplía las reglas (o que el creador ignoraba el [código de conducta](/wiki/Rules/Code_of_conduct_for_modding_and_mapping)) podría ser destruido por el [Beatmap Appreciation Team (BAT)](/wiki/People/Beatmap_Appreciation_Team) o el [Global Moderation Team (GMT)](/wiki/People/Global_Moderation_Team).
```

2024-05-26 18:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Nuke/es.md
> +Cuando un beatmap era destruido, aparecía un símbolo nuclear ![](/wiki/shared/icon/nuke.gif) en el hilo del beatmap. Este servía para indicarles a los demás miembros del BAT/GMT que el beatmap no se
```suggestion
Cuando un beatmap era destruido, aparecía un icono nuclear ![](/wiki/shared/icon/nuke.gif) en el hilo del beatmap. Este servía para indicarles a los demás miembros del BAT/GMT que el beatmap no se consideraría para ser [clasificado](/wiki/Beatmap_ranking_procedure#clasificados) hasta que se hubieran realizado cambios significativos. Si un beatmap hiciera los cambios correspondientes, el icono se eliminaría y podría continuar con el [proceso de clasificación](/wiki/Beatmap_ranking_procedure).
```

2024-05-26 18:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Nuke/es.md
> +![](img/forum-listing-nuke.png "Beatmaps con el símbolo nuclear y sus hilos en el subforo Graveyard")
```suggestion
![](img/forum-listing-nuke.png "Beatmaps con el icono nuclear y sus hilos en el subforo Graveyard")
```

2024-05-26 18:02 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Nuke/es.md
> +Técnicamente, los símbolos nucleares todavía existen en los foros, pero con la adición del [Modding v2](/wiki/Beatmap_discussion) y los [vetos](/wiki/People/Beatmap_Nominators/Beatmap_Veto) han sido
```suggestion
Técnicamente, los iconos nucleares todavía existen en los foros, pero con la adición del [Modding v2](/wiki/Beatmap_discussion) y los [vetos](/wiki/People/Beatmap_Nominators/Beatmap_Veto) han sido efectivamente reemplazados y no tienen uso en el sistema actual del modding.
```

2024-06-16 09:41 UTC, cl8n approved these changes

2024-06-16 09:56 UTC, agatemosu approved these changes

2024-06-16 10:42 UTC, merged