[ES] Add `Modding/Forum modding`
ppy/osu-wiki pull request #11472
Opened 2024-05-26 02:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-28 17:17 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-05-28 17:17 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Forum_modding/es.md
> +El **modding en los foros**, también conocido como *Modding v1*, es un nombre coloquial del sistema de clasificación y [modding](/wiki/Modding) basado en los foros que se usó principalmente hasta el
```suggestion
El **modding en los foros**, también conocido como *Modding v1*, es un nombre coloquial del sistema de clasificación y [modding](/wiki/Modding) basado en los foros que se usó principalmente hasta el [4 de noviembre de 2017](https://osu.ppy.sh/community/forums/topics/650961?n=7), cuando todos los [beatmaps](/wiki/Beatmap) nuevos e inactivos se cambiaron a las [discusiones de beatmaps](/wiki/Beatmap_discussion) de forma predeterminada.
```

2024-05-28 17:17 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Forum_modding/es.md
> +- ![](/wiki/shared/icon/bubble.gif) **[Burbuja](/wiki/Modding/Bubble)**: el beatmap había sido revisado por un miembro del MAT, BAT o un BN, y podría ser clasificado después de otra revisión.
```suggestion
- ![](/wiki/shared/icon/bubble.gif) **[Burbuja](/wiki/Modding/Bubble)**: el beatmap había sido revisado por un miembro del MAT, el BAT o un BN, y podría ser clasificado después de otra revisión.
```

2024-05-28 17:17 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Forum_modding/es.md
> +- Según la gravedad del problema, algunos modders usaban [código de colores](/wiki/BBCode#color) en sus publicaciones para resaltar problemas no clasificables o puntos clave.
```suggestion
- Según la gravedad del problema, algunos modders usaban un [código de colores](/wiki/BBCode#color) en sus publicaciones para resaltar problemas no clasificables o puntos clave.
```

2024-05-28 17:17 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Modding/Forum_modding/es.md
> +![](img/mod-response.png "Un ejemplo de respuesta a un mod")
```suggestion
![](img/mod-response.png "Un ejemplo de una respuesta a un mod")
```

2024-06-16 10:42 UTC, cl8n approved these changes

2024-06-16 10:44 UTC, merged