[ES] Add `Ranking_criteria/osu!`
ppy/osu-wiki pull request #11502
Opened 2024-05-30 01:24 UTC by Pacuwu

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-05-30 01:27 UTC, summyvn commented
The translation is fine, wait for the merge, I won't bother you anymore

2024-06-02 01:53 UTC, UnknownOsu requested changes

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +  - Los **[descansos](/wiki/Beatmap/Break) se pueden combinar con el [tiempo de drenaje](/wiki/Beatmap/Drain_time) para alcanzar los umbrales anteriores.** Para la dificultad más alta, esto se limita
```suggestion
  - Los **[descansos](/wiki/Beatmap/Break) se pueden combinar con el [tiempo de drenaje](/wiki/Beatmap/Drain_time) para alcanzar los umbrales anteriores.** Para la dificultad más alta, esto se limita a como máximo 30 segundos de descanso. Esto no se aplica a las dificultades con menos de 30 segundos de tiempo de drenaje.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- La **[tasa de las marcas de los sliders](/wiki/Beatmapping/Slider_tick_rate) deben establecerse siguiendo el ritmo de la canción.** Por ejemplo, si tu canción contiene una sección que solo usa ritm
```suggestion
- La **[tasa de las marcas de los sliders](/wiki/Beatmapping/Slider_tick_rate) debe establecerse siguiendo el ritmo de la canción.** Por ejemplo, si tu canción contiene una sección que solo usa ritmos de 1/3, usar una tasa de 2 para las marcas de los sliders no sería adecuada para todo el beatmap. En estos casos, se debe usar una tasa de 1 para las marcas de los sliders.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita los picos de dificultad innecesarios.** La dificultad debe ser representativa de acuerdo a la intensidad de la canción
```suggestion
- **Evita los picos de dificultad innecesarios.** La dificultad debe ser representativa de acuerdo a la intensidad de la canción.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Se debe seleccionar un color para el borde de los sliders cuando un beatmap contenga elementos de skin de los conjuntos de círculos o sliders.** Esto es para evitar que el borde predeterminado de
```suggestion
- **Se debe seleccionar un color para el borde de los sliders cuando un beatmap contenga elementos de skin de los conjuntos de círculos o sliders.** Esto es para evitar que el borde predeterminado de los sliders o el borde personalizado de los sliders de la skin de un jugador entren en conflicto con el esquema de color específico del beatmap. Esto se hace añadiendo `SliderBorder: <Valor RGB>` en la sección `[Colours]` en un archivo `.osu`.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son p
```suggestion
- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son poco visibles. La posición final de un slider debe ser visible en el supuesto de que el jugador disponga de una skin que haga totalmente transparentes los círculos finales de los sliders.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita usar sliders inferiores a 1/2 pulso.** Son demasiado rápidos para ser comprendidos por los nuevos jugadores.
```suggestion
- **Evita usar sliders inferiores a 1/2 compás.** Son demasiado rápidos para ser comprendidos por los nuevos jugadores.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **No se recomienda manipular con frecuencia la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity).** La velocidad del slider solo debe cambiarse para las secciones de la músic
```suggestion
- **No se recomienda manipular con frecuencia la [velocidad de los sliders](/wiki/Gameplay/Hit_object/Slider/Slider_velocity).** La velocidad de los sliders solo debe cambiarse para las secciones de la música con diferentes ritmos y no debe ser drásticamente variable.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son p
```suggestion
- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son poco visibles. La posición final de un slider debe ser visible en el supuesto de que el jugador disponga de una skin que haga totalmente transparentes los círculos finales de los sliders.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **No se recomienda manipular con frecuencia la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity).** La velocidad del slider solo debe cambiarse para las secciones de la músic
```suggestion
- **No se recomienda manipular con frecuencia la [velocidad de los sliders](/wiki/Gameplay/Hit_object/Slider/Slider_velocity).** La velocidad de los sliders solo debe cambiarse para las secciones de la música con diferentes ritmos y no debe ser drásticamente variable.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son p
```suggestion
- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son poco visibles. La posición final de un slider debe ser visible en el supuesto de que el jugador disponga de una skin que haga totalmente transparentes los círculos finales de los sliders.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evite uar un espaciado visualmente similar para ritmos diferentes.** Se recomienda la variación del espaciado mediante [jumps](/wiki/Beatmap/Pattern/osu!/Jump) en los puntos de énfasis, pero solo
```suggestion
- **Evita usar un espaciado visualmente similar para ritmos diferentes.** Se recomienda la variación del espaciado mediante [jumps](/wiki/Beatmap/Pattern/osu!/Jump) en los puntos de énfasis, pero solo si estos jumps son claramente diferentes de otros intervalos del ritmo.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son p
```suggestion
- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son poco visibles. La posición final de un slider debe ser visible en el supuesto de que el jugador disponga de una skin que haga totalmente transparentes los círculos finales de los sliders.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son p
```suggestion
- **Cada slider debe tener una trayectoria clara y visible que seguir de principio a fin.** No se pueden usar sliders que se superponen sin bordes claros ni sliders cuyas secciones individuales son poco visibles. La posición final de un slider debe ser visible en el supuesto de que el jugador disponga de una skin que haga totalmente transparentes los círculos finales de los sliders.
```

2024-06-02 01:53 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían ser 8 o superior.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) debería ser 8 o superior.
```

2024-06-02 02:12 UTC, UnknownOsu commented
En el caso que no sepas aceptar las sugerencias, te vas a `Files changed` y ahí le das al botón al lado de la sugerencias que dice `Add suggestion to batch` y vas seleccionando las sugerencias.

Luego de que hayas seleccionado todas, le das a `Commit suggestions` en la parte de arriba a la derecha y le das a `Commit changes`. 

Debería ser algo parecido a esto:

![214177263-b6ead137-e7e0-43a0-9aec-00f81894ebf7](https://github.com/ppy/osu-wiki/assets/130007516/ca3bbf5e-af85-4919-b003-a85335efa5e1)

2024-06-03 00:09 UTC, UnknownOsu requested changes

2024-06-03 00:09 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +Este conjunto de **los criterios de clasificación de osu!** establece las [reglas y pautas](/wiki/Ranking_criteria#términos-generales) que los [beatmaps](/wiki/Beatmap) específicos de [osu!](/wiki/Ga
```suggestion
Este conjunto de **criterios de clasificación de osu!** establece [reglas y pautas](/wiki/Ranking_criteria#términos-generales) que los [beatmaps](/wiki/Beatmap) específicos de [osu!](/wiki/Game_mode/osu!) deben seguir para avanzar en el [procedimiento de clasificación](/wiki/Beatmap_ranking_procedure).
```

2024-06-03 03:08 UTC, UnknownOsu requested changes

2024-06-03 03:08 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita los picos de dificultad innecesarios.** La dificultad debe ser representativa de acuerdo a la intensidad de la canción.
```suggestion
- **Evita los picos de dificultad injustificados.** La dificultad debe ser representativa de la intensidad de la canción.
```

2024-06-03 13:07 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- La [dificultad general](/wiki/Beatmap/Overall_difficulty) / [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería ser entre 1 y 3.
```suggestion
- La [dificultad general](/wiki/Beatmap/Overall_difficulty) y la [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) deberían ser entre 1 y 3.
```

2024-06-03 13:07 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- La [dificultad general](/wiki/Beatmap/Overall_difficulty) / [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) debería ser entre 3 y 5.
```suggestion
- La [dificultad general](/wiki/Beatmap/Overall_difficulty) y la [tasa de drenaje de HP](/wiki/Beatmap/HP_drain_rate) deberían ser entre 3 y 5.
```

2024-06-03 13:08 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) / [dificultad general](/wiki/Beatmap/Overall_difficulty) debería ser 8 o superior.
```suggestion
- La [velocidad de aproximación](/wiki/Beatmap/Approach_rate) y la [dificultad general](/wiki/Beatmap/Overall_difficulty) deberían ser 8 o superior.
```

2024-06-03 13:55 UTC, UnknownOsu requested changes

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Los objetos separados por 1 compás o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente.**
```suggestion
- **Los objetos separados por 1 pulso o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente.**
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Se debe usar la [igualdad de tiempo-distancia](/wiki/Beatmapping/Mapping_techniques/Time-distance_equality).** Las variaciones son aceptables si son claramente diferentes del espaciado usado para
```suggestion
- **Se debe usar la [igualdad de tiempo-distancia](/wiki/Beatmapping/Mapping_techniques/Time-distance_equality).** Las variaciones son aceptables si son claramente diferentes del espaciado usado para diferentes ritmos. Cuando los objetos están a más de 2 pulsos de distancia y tienen un espaciado relativamente alto en el campo de juego, la igualdad de tiempo-distancia no necesita ser tan precisa.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita usar sliders inferiores a 1/2 compás.** Son demasiado rápidos para ser comprendidos por los nuevos jugadores.
```suggestion
- **Evita usar sliders inferiores a 1/2 pulso.** Son demasiado rápidos para ser comprendidos por los nuevos jugadores.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Debe haber al menos 4 compases entre el final de un spinner y el siguiente objeto.** Esto es para asegurar el tiempo adecuado para hacer clic en un objeto después de un spinner.
```suggestion
- **Debe haber al menos 4 pulsos entre el final de un spinner y el siguiente objeto.** Esto es para asegurar el tiempo adecuado para hacer clic en un objeto después de un spinner.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita poner spinners de menos de 4 compases.** Los jugadores necesitan tiempo para reconocer que tienen que empezar a girar.
```suggestion
- **Evita poner spinners de menos de 4 pulsos.** Los jugadores necesitan tiempo para reconocer que tienen que empezar a girar.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita cubrir completamente las flechas inversas de los sliders con objetos dentro de los 4 compases en los que se alcanza la flecha inversa.** Esto les da a los jugadores tiempo suficiente para r
```suggestion
- **Evita cubrir completamente las flechas inversas de los sliders con objetos dentro de los 4 pulsos en los que se alcanza la flecha inversa.** Esto les da a los jugadores tiempo suficiente para reconocer la flecha inversa.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 4 compases.** Hacer esto puede hacer que los sliders se interpreten er
```suggestion
- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 4 pulsos.** Hacer esto puede hacer que los sliders se interpreten erróneamente como un círculo debido a la oscuridad del cuerpo del slider.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Los objetos separados por 1 compás o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente.**
```suggestion
- **Los objetos separados por 1 pulso o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente.**
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Se debe usar la [igualdad de tiempo-distancia](/wiki/Beatmapping/Mapping_techniques/Time-distance_equality).** Las variaciones son aceptables si son claramente diferentes del espaciado usado para
```suggestion
- **Se debe usar la [igualdad de tiempo-distancia](/wiki/Beatmapping/Mapping_techniques/Time-distance_equality).** Las variaciones son aceptables si son claramente diferentes del espaciado usado para diferentes ritmos. Cuando los objetos están a más de 1 pulso de distancia y tienen un espaciado relativamente alto en el campo de juego, la igualdad de tiempo-distancia no necesita ser tan precisa.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Debe haber al menos 2 compases entre el final de un spinner y el siguiente objeto.** Esto es para asegurar el tiempo adecuado para hacer clic en un objeto después de un spinner.
```suggestion
- **Debe haber al menos 2 pulsos entre el final de un spinner y el siguiente objeto.** Esto es para asegurar el tiempo adecuado para hacer clic en un objeto después de un spinner.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita poner spinners de menos de 3 compases.** Los jugadores necesitan tiempo para reconocer que tienen que empezar a girar.
```suggestion
- **Evita poner spinners de menos de 3 pulsos.** Los jugadores necesitan tiempo para reconocer que tienen que empezar a girar.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita cubrir completamente las flechas inversas de los sliders con objetos dentro de los 3 compases en los que se alcanza la flecha inversa.** Esto les da a los jugadores tiempo suficiente para r
```suggestion
- **Evita cubrir completamente las flechas inversas de los sliders con objetos dentro de los 3 pulsos en los que se alcanza la flecha inversa.** Esto les da a los jugadores tiempo suficiente para reconocer la flecha inversa.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 3 compases.** Hacer esto puede hacer que los sliders se interpreten er
```suggestion
- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 3 pulsos.** Hacer esto puede hacer que los sliders se interpreten erróneamente como un círculo debido a la oscuridad del cuerpo del slider.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Los objetos separados por 1/2 compás o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente.** Las cabezas o colas de los sliders totalmente superpuestas por
```suggestion
- **Los objetos separados por 1/2 pulso o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente.** Las cabezas o colas de los sliders totalmente superpuestas por las colas de los sliders están exentas, siempre que los cuerpos de los sliders sean visibles.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Debe haber al menos 1 compás entre el final de un spinner y el siguiente objeto.** Esto es para asegurar el tiempo adecuado para hacer clic en un objeto después de un spinner.
```suggestion
- **Debe haber al menos 1 pulso entre el final de un spinner y el siguiente objeto.** Esto es para asegurar el tiempo adecuado para hacer clic en un objeto después de un spinner.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita poner spinners de menos de 2 compases.** Los jugadores necesitan tiempo para reconocer que tienen que empezar a girar.
```suggestion
- **Evita poner spinners de menos de 2 pulsos.** Los jugadores necesitan tiempo para reconocer que tienen que empezar a girar.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita cubrir completamente las flechas inversas de los sliders con objetos dentro de los 2 compases en los que se alcanza la flecha inversa.** Esto les da a los jugadores tiempo suficiente para r
```suggestion
- **Evita cubrir completamente las flechas inversas de los sliders con objetos dentro de los 2 pulsos en los que se alcanza la flecha inversa.** Esto les da a los jugadores tiempo suficiente para reconocer la flecha inversa.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 2 compases.** Hacer esto puede hacer que los sliders se interpreten er
```suggestion
- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 2 pulsos.** Hacer esto puede hacer que los sliders se interpreten erróneamente como un círculo debido a la oscuridad del cuerpo del slider.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Los objetos separados por 1/4 de compás o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente,** especialmente en las dificultades Insane más sencillas.
```suggestion
- **Los objetos separados por 1/4 de pulso o menos no deben [superponerse](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente,** especialmente en las dificultades Insane más sencillas.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita cubrir completamente las flechas inversas de los sliders con círculos, cabezas o colas de los sliders a 1/2 compás en el que se alcanza la flecha inversa.** Esto les da a los jugadores tiem
```suggestion
- **Evita cubrir completamente las flechas inversas de los sliders con círculos, cabezas o colas de los sliders a 1/2 pulso en el que se alcanza la flecha inversa.** Esto les da a los jugadores tiempo suficiente para reconocer la flecha inversa.
```

2024-06-03 13:55 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 1/2 compás.** Hacer esto puede hacer que los sliders se interpreten er
```suggestion
- **Evita [superponer](/wiki/Beatmapping/Mapping_techniques/Overlap) completamente los cuerpos de los sliders en un intervalo de 1/2 pulso.** Hacer esto puede hacer que los sliders se interpreten erróneamente como un círculo debido a la oscuridad del cuerpo del slider.
```

2024-06-03 14:02 UTC, UnknownOsu commented
No es necesario estar fusionando la rama master a cada rato, eso lo hará un mantenedor cuando vaya a fusionar tu rama con la rama master

2024-06-03 14:04 UTC, Pacuwu commented
> No es necesario estar fusionando la rama master a cada rato, eso lo hará un mantenedor cuando vaya a fusionar tu rama con la rama master

No entendí, sólo ando aplicando los cambios que me dices en el archivo

2024-06-03 14:07 UTC, UnknownOsu commented
Lo decía por [esto](https://i.imgur.com/jkSGO6u.png). Debería salirte [un botón abajo del todo](https://i.imgur.com/FLnLFBz.png), no sé si le estés dando, pero no es necesario

2024-06-03 14:08 UTC, Pacuwu commented
> Lo decía por [esto](https://i.imgur.com/jkSGO6u.png). Debería salirte [un botón abajo del todo](https://i.imgur.com/FLnLFBz.png), no sé si le estés dando, pero no es necesario

Aaaah, si si le doy, le voy dando para que se actualice

2024-06-03 14:19 UTC, UnknownOsu commented
Bueno, no es necesario estar dándole a cada rato.

Ya revisé todo y no veo nada raro. No sé si agatem quiera darle un vistazo para ver si encuentra algo que no le parezca

2024-06-03 14:20 UTC, Pacuwu commented
> Bueno, no es necesario estar dándole a cada rato.
> 
> Ya revisé todo y no veo nada raro. No sé si agatem quiera darle un vistazo para ver si encuentra algo que no le parezca

Esta bien, yo seguiré esperando a que se fusione

2024-06-11 16:52 UTC, Walavouchey commented
> Bueno, no es necesario estar dándole a cada rato.
> 
> Ya revisé todo y no veo nada raro. No sé si agatem quiera darle un vistazo para ver si encuentra algo que no le parezca

is this waiting on @agatemosu's review or is this good to go?

2024-06-11 16:53 UTC, Pacuwu commented
> > Bueno, no es necesario estar dándole a cada rato.
> > Ya revisé todo y no veo nada raro. No sé si agatem quiera darle un vistazo para ver si encuentra algo que no le parezca
> 
> @UnknownOsu is this waiting on @agatemosu's review or is this good to go?

Creo que no revisó, sigo esperando

2024-06-11 17:07 UTC, UnknownOsu commented
> @UnknownOsu is this waiting on @agatemosu's review or is this good to go?

Well, from my side, the article is fine. It's up to you if you want to wait for agatem's review; I told her if she wanted to review the article the same day I posted that message

2024-06-11 17:09 UTC, Pacuwu commented
> > @UnknownOsu is this waiting on @agatemosu's review or is this good to go?
> 
> Well, from my side, the article is fine. It's up to you if you want to wait for agatem's review; I told her if she wanted to review the article the same day I posted that message

Por mi no esperaría pero si es obligado esperaré

2024-06-14 18:40 UTC, UnknownOsu requested changes

2024-06-14 18:40 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +Las reglas y pautas generales se aplican a cualquier tipo de dificultad de osu!. Las reglas y pautas relacionadas con el ritmo se aplican a beatmaps de aproximadamente 180 BPM con compases de 4/4. Si
```suggestion
Las reglas y pautas generales se aplican a cualquier tipo de dificultad de osu!. Las reglas y pautas relacionadas con el ritmo se aplican a beatmaps de aproximadamente 180 BPM con compases de 4/4. Si tu canción es drásticamente más rápida o más lenta, algunas variables pueden ser diferentes, como se detalla en [Escalado del BPM según los criterios de clasificación](/wiki/Ranking_criteria/Scaling_BPM).
```

2024-06-14 18:40 UTC, UnknownOsu commented on wiki/Ranking_criteria/osu!/es.md
> +- La **[tasa de las marcas de los sliders](/wiki/Beatmapping/Slider_tick_rate) debe establecerse siguiendo el ritmo de la canción.** Por ejemplo, si tu canción contiene una sección que solo usa ritmo
```suggestion
- La **[tasa de las marcas de los sliders](/wiki/Beatmapping/Slider_tick_rate) debe establecerse siguiendo el ritmo de la canción.** Por ejemplo, si tu canción contiene una sección que solo usa ritmos de 1/3, usar una tasa de 2 para las marcas de los sliders no sería adecuado para todo el beatmap. En estos casos, se debe usar una tasa de 1 para las marcas de los sliders.
```

2024-06-14 18:52 UTC, agatemosu commented on wiki/Ranking_criteria/osu!/es.md
> +Las reglas y pautas generales se aplican a cualquier tipo de dificultad de osu!. Las reglas y pautas relacionadas con el ritmo se aplican a beatmaps de aproximadamente 180 BPM con compases de 4/4. Si
to match others
```suggestion
Las reglas y pautas generales se aplican a todo tipo de dificultad de osu!. Las reglas y pautas relacionadas con el ritmo se aplican a beatmaps de aproximadamente 180 BPM con compases de 4/4. Si tu canción es drásticamente más rápida o más lenta, algunas variables pueden ser diferentes, como se detalla en [Escalado del BPM según los criterios de clasificación](/wiki/Ranking_criteria/Scaling_BPM).
```

2024-06-14 18:53 UTC, agatemosu commented on wiki/Ranking_criteria/osu!/es.md
> +  - **... inferior a 3:30**, la dificultad más baja no puede ser más difícil que un Normal.
```suggestion
  - **... menos de 3:30**, la dificultad más baja no puede ser más difícil que un Normal.
```

2024-06-14 18:53 UTC, agatemosu commented on wiki/Ranking_criteria/osu!/es.md
> +  - **... entre 3:30 y 4:15**, la dificultad más baja no puede ser más difícil un Hard.
```suggestion
  - **... entre 3:30 y 4:15**, la dificultad más baja no puede ser más difícil que un Hard.
```

2024-06-14 18:57 UTC, agatemosu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita usar sliders inferiores a 1/2 pulso.** Son demasiado rápidos para ser comprendidos por los nuevos jugadores.
```suggestion
- **Evita usar sliders inferiores a 1/2 compás.** Esto es demasiado rápido para los nuevos jugadores.
```

2024-06-14 18:59 UTC, agatemosu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Cuando uses el [ajuste de distancia](/wiki/Client/Beatmap_editor/Distance_snap), intenta mantenerlo entre 0,8x y 1,2x.** Los valores demasiado altos o bajos pueden hacer que la diferencia entre l
```suggestion
- **Cuando uses el [ajuste de distancia](/wiki/Client/Beatmap_editor/Distance_snap), intenta mantenerlo entre 0,8x y 1,2x.** Los valores demasiado altos o bajos pueden hacer que la diferencia entre la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity) y el espaciado sea poco intuitiva. Se puede usar una distancia mayor para evitar la [superposición](/wiki/Beatmapping/Mapping_techniques/Overlap), pero la velocidad del slider debe aumentarse si haces esto con frecuencia.
```

2024-06-14 19:00 UTC, agatemosu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Evita usar sliders inferiores a 1/2 compás.** Esto es demasiado rápido para los nuevos jugadores.
```suggestion
- **Evita usar sliders inferiores a 1/2 de un pulso.** Esto es demasiado rápido para los nuevos jugadores.
```

2024-06-14 19:01 UTC, agatemosu commented on wiki/Ranking_criteria/osu!/es.md
> +- **Cuando uses el [ajuste de distancia](/wiki/Client/Beatmap_editor/Distance_snap), intenta mantenerlo entre 0,8x y 1,3x.** Los valores demasiado altos o bajos pueden hacer que la diferencia entre l
```suggestion
- **Cuando uses el [ajuste de distancia](/wiki/Client/Beatmap_editor/Distance_snap), intenta mantenerlo entre 0,8x y 1,3x.** Los valores demasiado altos o bajos pueden hacer que la diferencia entre la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity) y el espaciado sea poco intuitiva. Se puede usar una distancia mayor para evitar la [superposición](/wiki/Beatmapping/Mapping_techniques/Overlap), pero la velocidad del slider debe aumentarse si haces esto con frecuencia.
```

2024-07-05 09:23 UTC, closed without merging

2024-07-05 09:23 UTC, Pacuwu commented
Ya me cansé de esperar, casi 2 meses para una fusión, espero comprendan el motivo por el que cerré esto, gracias por su ayuda y hasta luego