[VI] Add `Rules/Code of conduct for modding and mapping`
ppy/osu-wiki pull request #11510
Opened 2024-06-01 00:40 UTC by summyvn

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-06-03 13:41 UTC, vietng322611 commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/vi.md
> +**Quy tắc ứng xử đối với modding và mapping** là quy tắc và cũng là hướng dẫn áp dụng cho toàn bộ cộng đồng [modding](/wiki/Modding) và [mapping](/wiki/Beatmapping) cũng như phần mở rộng cho [Quy tắc
**Quy tắc ứng xử đối với modding và mapping** là những quy tắc, hướng dẫn được áp dụng cho toàn bộ cộng đồng [modding](/wiki/Modding) và [mapping](/wiki/Beatmapping), cũng như là phần mở rộng cho [Quy tắc cộng đồng osu!](/wiki/Rules) và [Tiêu chí xếp hạng chung](/wiki/Ranking_criteria). Để đảm bảo rằng các cuộc thảo luận về mapping và modding ở các chủ đề diễn ra trong môi trường mang tính xây dựng, tích cực và hiệu quả, các quy tắc ứng xử là rất quan trọng để mọi người ở cùng một chủ đề. Khi tham gia vào cộng đồng modding và mapping, bắt buộc phải tuân theo các quy tắc ứng xử này. Hành vi vi phạm các quy tắc này có thể dẫn đến [hình phạt đối với tài khoản của bạn](/wiki/Silence).

2024-06-03 13:49 UTC, vietng322611 commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/vi.md
> +- Mục đích của modding là giúp người lập bản đồ cải thiện công việc giúp beatmap của họ lên trạng thái [xếp hạng](/wiki/Beatmap/Category#ranked) nếu người lập bản đồ chọn làm như vậy. Nếu bạn không t
- Mục đích của modding là giúp người tạo beatmap cải thiện beatmap của họ để có thể đưa lên trạng thái [xếp hạng](/wiki/Beatmap/Category#ranked) (nếu muốn). Nếu bạn không muốn giúp đỡ người khác, xin hãy tránh xa các cuộc thảo luận để tránh *làm tổn thương họ*.

2024-06-03 13:52 UTC, vietng322611 commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/vi.md
> +  - Đừng né tránh những người lập bản đồ và người sửa đổi mới — những người này là những người cần nhiều kiến thức nhất từ ​​ý kiến ​​đóng góp của bạn và mọi người! Hãy kiên nhẫn, thấu hiểu và đưa ra
- Đừng né tránh những người mới tham gia mapping và modding  — họ rất cần những ​​ý kiến ​​đóng góp của bạn và mọi người! Hãy kiên nhẫn, thấu hiểu và đưa ra càng nhiều lời giải thích càng tốt để họ có thể học hỏi và tiến bộ nhanh hơn.

2024-06-03 13:55 UTC, vietng322611 commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/vi.md
> +- Hãy đối xử với người khác như cách bạn muốn được đối xử. Mọi người dễ tiếp thu những lời đề nghị tử tế, hữu ích hơn những lời tục tĩu. Cố gắng hiểu quan điểm của người khác thay vì tấn công nó - kh
- Hãy đối xử với người khác như cách bạn muốn được đối xử. Mọi người dễ tiếp thu những lời đề nghị tử tế, hữu ích hơn những lời tục tĩu. Cố gắng hiểu quan điểm của người khác thay vì tấn công nó - không ai thích cảm thấy mình vô dụng, kém cỏi hay ngu ngốc. Nếu bạn thích bị công kích, nhớ rằng không phải ai cũng giống bạn.

2024-06-03 14:04 UTC, vietng322611 commented on wiki/Rules/Code_of_conduct_for_modding_and_mapping/vi.md
> +Nếu bạn tải xuống một bản đồ và tìm ra một số điều khiến bạn không hài lòng — giờ là lúc bạn bày tỏ suy nghĩ của mình và giúp cải thiện bản đồ. Nhưng làm cách nào bạn có thể khiến người lập bản đồ hi
Bạn tải xuống một beatmap và tìm ra một số điều khiến bạn không hài lòng — đó là lúc bạn bày tỏ suy nghĩ của mình và giúp cải thiện nó. Nhưng làm cách nào để người tạo beatmap hiểu, thử và đưa ra phản hồi cho các đề xuất của bạn? Suy cho cùng, không ai thích cảm giác rằng thời gian của mình bị lãng phí.

2024-06-03 14:18 UTC, vietng322611 requested changes
> Beatmap/map cannot be translated as "bản đồ", it's a term in osu, not an actual word in English. This make your translation look like it came from google translator.
> Many words/phrases are wrongly translated, I have fixed some but there still a lot of them.
> And please don't use google translator, that's the last resort. Use the word in English directly if there are no alternatives.

2024-06-05 02:16 UTC, summyvn commented
> * Beatmap/map cannot be translated as "bản đồ", it's a term in osu, not an actual word in English. This make your translation look like it came from google translator.
> * Many words/phrases are wrongly translated, I have fixed some but there still a lot of them.
> * And please don't use google translator, that's the last resort. Use the word in English directly if there are no alternatives.

I fixed it

2024-06-05 13:29 UTC, closed without merging