[ES] Update `People/Tournament Committee`
ppy/osu-wiki pull request #11517
Opened 2024-06-01 21:50 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-06-07 19:41 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-06-07 19:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Tournament_Committee/es.md
> +- Investigar los informes del [formulario de informes de torneos](https://pif.ephemeral.ink/tournament-reports).
```suggestion
- Investigar los reportes del [formulario de reportes de torneos](https://pif.ephemeral.ink/tournament-reports).
```

2024-06-07 19:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Tournament_Committee/es.md
> +Los torneos pueden ser denunciados por violación de los criterios oficiales de soporte a través del [formulario de denuncias de torneos](https://pif.ephemeral.ink/tournament-reports). Para los torneo
```suggestion
Los torneos pueden ser reportados por violación de los criterios oficiales de soporte a través del [formulario de reportes](https://pif.ephemeral.ink/tournament-reports). Para los torneos finalizados que hayan enviado un correo electrónico de soporte, el comité de torneos tomará el siguiente curso de acción si hay reportes procesables:
```

2024-06-07 19:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Tournament_Committee/es.md
> +Cuando se reciba un correo electrónico solicitando una noticia para un torneo, se notificará al comité de torneos. Si el torneo satisface todos los criterios de elegibilidad para publicaciones de not
```suggestion
Cuando se reciba un correo electrónico solicitando una noticia para un torneo, se notificará al comité de torneos. Si el torneo cumple todos los criterios de elegibilidad para la publicación de una noticia y el consenso en la discusión es positivo después de 48 horas, el comité de torneos reenviará la solicitud al equipo de noticias para su aprobación.
```

2024-06-07 19:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Tournament_Committee/es.md
> +La comunicación pública por parte del comité de torneos se maneja a través de varios canales. Los propósitos de estos a veces se superponen, pero todos son fuentes oficiales de información que el com
```suggestion
La comunicación pública por parte del comité de torneos se maneja a través de varios canales. Los propósitos de estos canales a veces se superponen, pero todos son fuentes oficiales de información que el comité de torneos mantiene actualizadas.
```

2024-06-07 19:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Tournament_Committee/es.md
> +El [rastreador del estado de los torneos de la comunidad](https://docs.google.com/spreadsheets/d/1bV5MyrJZI0F52Bx9EcYxdfRu8qGnhWRBKdXHK9uPbO0/edit?usp=sharing) es una hoja de cálculo de acceso públic
```suggestion
El [rastreador del estado de los torneos de la comunidad](https://docs.google.com/spreadsheets/d/1bV5MyrJZI0F52Bx9EcYxdfRu8qGnhWRBKdXHK9uPbO0/edit?usp=sharing) es una hoja de cálculo de acceso público en la que se detalla el estado de todos los torneos que han solicitado soporte oficial. Esta hoja muestra todos los torneos desde el 20 de junio de 2023 y muestra su estado a través del proceso de soporte oficial, incluyendo si una insignia fue aplicada o denegada.
```

2024-06-07 19:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Tournament_Committee/es.md
> +| Restricciones de torneos | 3 | 50% |
```suggestion
| Restricciones de torneos | 3 | 50 % |
```

2024-06-20 00:28 UTC, cl8n approved these changes

2024-06-20 00:30 UTC, merged