Add `Touhou Mania Cup 3rd` tournament article
ppy/osu-wiki pull request #11511
Opened 2024-06-01 02:17 UTC by YuEastOMMap

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

## Descriptions
- Add article for [Touhou Mania Cup 3rd (THMC3)](https://osu.ppy.sh/community/forums/topics/1751979)
- Updated List of Tournaments for THMC3

2024-06-01 08:01 UTC, iSlodinxOsu requested changes

2024-06-01 08:01 UTC, iSlodinxOsu commented on wiki/Tournaments/TMC/3rd/en.md
> +The **Touhou Project Mania Cup 3nd** (***THMC 3nd***) was a team-based 2v2 osu!mania 4K tournament hosted by ::{ flag=CN }:: [\[GB\]Sanae](https://osu.ppy.sh/users/11238501). The main theme of this t
```suggestion
The **Touhou Project Mania Cup 3nd** (***THMC 3nd***) was a team-based 2v2 osu!mania 4K tournament hosted by ::{ flag=CN }:: [\[GB\]Sanae](https://osu.ppy.sh/users/11238501). The main theme of this tournament the Touhou Project. The pool used for THMC 3rd is 100% based on original and fan-made Touhou music. It was the third instalment of the Touhou Project Mania Cup.
```

2024-06-24 15:34 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +18. All players and staff must be treated with respect. Instructions of the referees and the Tournament Management are to be followed. Decisions labelled as final are not to be objected.
```suggestion
18. All players and staff must be treated with respect. Instructions of the referees and the tournament management are to be followed. Decisions labelled as final are not to be objected.
```

2024-06-24 15:35 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +22. The Tournament Management reserves the right to modify these rules at any moment. Any such changes will be announced in advance.
```suggestion
22. The tournament management reserves the right to modify these rules at any moment. Any such changes will be announced in advance.
```

2024-06-24 15:35 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +1. Please complete the [registration form](https://forms.gle/NUEf7Mwv94UvSpzu7) to registrate.
```suggestion
1. Please complete the [registration form](https://forms.gle/NUEf7Mwv94UvSpzu7) to register.
```

2024-06-24 15:37 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +2. The qualifier pool contains 5 maps, all of which will use FreeMod rules. There will be no tiebreakers for this stage.
```suggestion
2. The qualifier pool contains 5 maps, all of which will use Free Mod rules. There will be no tiebreakers for this stage.
```

2024-06-24 15:38 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +2. Teams in the losers bracket must play 2 matches each weekend starting from the Quarterfinals.
```suggestion
2. Teams in the losers' bracket must play 2 matches each weekend starting from the Quarterfinals.
```

2024-06-24 15:39 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +     - For a pick timer: a random map will be chosen from the mappool using `!roll X`, where X is the number of maps that were neither picked nor banned, excluding the Tiebreaker.
```suggestion
     - For a pick timer: a random map will be chosen from the mappool using `!roll X`, where X is the number of maps that were neither picked nor banned, excluding the tiebreaker.
```

2024-06-24 15:39 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +   - Repeat offenders may receive further sanctions from the Tournament Management.
```suggestion
   - Repeat offenders may receive further sanctions from the tournament management.
```

2024-06-24 15:39 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +   - Each team will receive one "tactical timeout" of two minutes, to be used as extra time to pick or ban a beatmap. *The tactical timeout is optional*.
when bolding, italicising or linking a whole sentence, the terminating punctuation goes on the inside

```suggestion
   - Each team will receive one "tactical timeout" of two minutes, to be used as extra time to pick or ban a beatmap. *The tactical timeout is optional.*
```

2024-06-24 15:41 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +     - The tactical timeout may be called on a tiebreaker, provided that both team's captains agree to it.
```suggestion
     - The tactical timeout may be called on a tiebreaker, provided that both teams' captains agree to it.
```

2024-06-24 15:41 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +2. Each mappool consists of a fixed amount of maps each stage which will all be played under FreeMod conditions. This means that there is a unique FreeMod bracket.
```suggestion
2. Each mappool consists of a fixed amount of maps each stage which will all be played under Free Mod conditions. This means that there is a unique Free Mod bracket.
```

2024-06-24 15:45 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +     - Containing: 7 Rice maps, 4 LN maps, 3 Hybrid maps, 1 Tiebreaker.
```suggestion

| Stage | Beatmaps | Types |
| :-: | :-- | :-- |
| Qualifiers | 6 |  |
| Round of 32 & Round of 16 | 11 | 4 Rice, 2 LN, 2 Hybrid, 1 Tiebreaker |
| Quarterfinals & Semifinals | 13 | 5 Rice, 3 LN, 2 Hybrid, 1 Tiebreaker |
| Finals | 13 | 6 Rice, 3 LN, 3 Hybrid, 1 Tiebreaker |
| Grand Finals | 15 beatmaps | 7 Rice, 4 LN, 3 Hybrid, 1 Tiebreaker |

```

2024-06-24 15:46 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +5. Possible mod choices for all maps are [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [FadeIn](/wiki/Gameplay/Game_modifier/Fade_In), [Flashlight](/wiki/Gameplay/Game_modifier/Flashlight), and [Mir
```suggestion
5. Possible mod choices for all maps are [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [Fade In](/wiki/Gameplay/Game_modifier/Fade_In), [Flashlight](/wiki/Gameplay/Game_modifier/Flashlight), and [Mirror](/wiki/Gameplay/Game_modifier/Mirror).
```

2024-06-24 15:46 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +6. The tiebreaker will be played under FreeMod conditions.
```suggestion
6. The tiebreaker will be played under Free Mod conditions.
```

2024-06-24 15:46 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +4. Scheduling will be handled by the Tournament Management. Schedules will be released on the Sunday before the first matches of the stage. The Tournament Management will try to create the schedule t
```suggestion
4. Scheduling will be handled by the tournament management. Schedules will be released on the Sunday before the first matches of the stage. The tournament management will try to create the schedule to respect the participants' time zones.
```

2024-06-24 15:47 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +   - In the Semifinals and subsequent stages, team captains may inform the Tournament Management if they expect a specific time slot to be unavailable in the following week. Schedule updates will be
```suggestion
   - In the Semifinals and subsequent stages, team captains may inform the tournament management if they expect a specific time slot to be unavailable in the following week. Schedule updates will be granted to the best of the tournament management's ability.
```

2024-06-24 15:47 UTC, Walavouchey commented on wiki/Tournaments/TMC/3rd/en.md
> +6. Captains are responsible for their teams' availability. Any mishaps resulting from a lack of transparency from a team are to be resolved internally, the Tournament Management will not intervene.
```suggestion
   - **Do not ask for a reschedule unless it is absolutely needed. The tournament management reserves the right to deny any rescheduling request.**
6. Captains are responsible for their teams' availability. Any mishaps resulting from a lack of transparency from a team are to be resolved internally, the tournament management will not intervene.
```

2024-06-26 02:23 UTC, YuEastOMMap commented
oops forgot to resolve

2024-07-10 10:12 UTC, Walavouchey approved these changes

2024-07-10 10:14 UTC, merged