[KO]Apply 6/2 updates `Tournaments/Official_support`
ppy/osu-wiki pull request #11541
Opened 2024-06-09 06:54 UTC by Chronicler01

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-11-13 18:22 UTC, Albionthegreat commented
Missing changes from #12417 & #12419

2024-11-18 21:31 UTC, Albionthegreat requested changes
Since I'm not a native speaker, I'm unable to review the language used. Will leave that to sylphi or others.

2024-11-18 21:31 UTC, Albionthegreat commented on wiki/Tournaments/Official_support/ko.md
> +- LAN 토너먼트는 최소 8강 더블 엘리미네이션 또는 16강 싱글 엘리미네이션으로 진행되어야 합니다.
```suggestion
  - LAN 토너먼트는 최소 8강 더블 엘리미네이션 또는 16강 싱글 엘리미네이션으로 진행되어야 합니다.
```
Should be indented.

2024-11-18 21:31 UTC, Albionthegreat commented on wiki/Tournaments/Official_support/ko.md
> +모든 토너먼트 스태프의 명단은 쉽게 접근할 수 있는 위치에 공개되어야 합니다. 이 명단은 토너먼트 포럼 게시물, 위키 페이지, 웹사이트 혹은 스프레드시트에 포함해야 할 수도 있습니다.
Missing the "If there are multiple lists of staff, they must all be up to date and in sync with one another." change here.

2024-12-09 15:08 UTC, TicClick approved these changes

2024-12-09 15:10 UTC, merged