[ES] Update `Client/Beatmap editor/Distance snap`
ppy/osu-wiki pull request #11617
Opened 2024-06-20 10:56 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-06-20 14:20 UTC, UnknownOsu requested changes

2024-06-20 14:20 UTC, UnknownOsu commented on wiki/Client/Beatmap_editor/Distance_snap/es.md
> +El ajuste de distancia se puede activar desde la pestaña [Compose](/wiki/Client/Beatmap_editor/Compose) presionando `Y`, o —temporalmente— manteniendo presionada la tecla `Alt` (lo que puede ser más
```suggestion
El ajuste de distancia se puede activar desde la pestaña [Compose](/wiki/Client/Beatmap_editor/Compose) presionando `Y`, o manteniendo presionada la tecla `Alt` temporalmente (lo que puede ser más preferible, ya que la herramienta limita la ubicación del objeto a un círculo de cierto radio). El multiplicador de distancia se puede cambiar manteniendo presionada la tecla `Alt` y usando la rueda del ratón o arrastrando el control deslizante `Distancia entre notas` en la esquina superior derecha. Además, si mantienes presionada la tecla `Mayús` después de `Alt` y desplazas la rueda del ratón o arrastras el control deslizante de la parte superior derecha, podrás ajustar la distancia con una precisión de dos dígitos.
```

2024-06-29 17:32 UTC, UnknownOsu approved these changes

2024-07-12 21:05 UTC, TicClick approved these changes

2024-07-12 21:05 UTC, merged