[ES] Update `Beatmap/Beatmap collaborations`
ppy/osu-wiki pull request #11619
Opened 2024-06-20 11:17 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-06-20 13:18 UTC, UnknownOsu requested changes

2024-06-20 13:18 UTC, UnknownOsu commented on wiki/Beatmap/Beatmap_collaborations/es.md
> +Los mappers completan sus partes colocando [objetos](/wiki/Gameplay/Hit_object), aplicando [hitsounds](/wiki/Beatmapping/Hitsound), usando [puntos de tiempo heredados](/wiki/Client/Beatmap_editor/Tim
```suggestion
Los mappers completan sus partes colocando [objetos](/wiki/Gameplay/Hit_object), aplicando [hitsounds](/wiki/Beatmapping/Hitsound), usando [puntos de tiempo heredados](/wiki/Client/Beatmap_editor/Timing#puntos-de-tiempo-heredados) cuando sea necesario, para luego devolver su trabajo al anfitrión, quien combina los cambios en una sola dificultad editando cuidadosamente su [archivo `.osu`](/wiki/Client/File_formats/osu_(file_format)).
```

2024-06-20 13:18 UTC, UnknownOsu commented on wiki/Beatmap/Beatmap_collaborations/es.md
> +Aunque los mappers generalmente suelen basarse en las partes ya completadas para que las transiciones de juego sean lo más fluidas posible, existen las llamadas *colaboraciones ciegas* como [Mitose N
```suggestion
Aunque los mappers generalmente suelen basarse en las partes ya completadas para que las transiciones de juego sean lo más fluidas posible, existen las llamadas *colaboraciones ciegas* como [Mitose Noriko - Unreal Player](https://osu.ppy.sh/beatmapsets/828563#osu/1735958) organizada por ::{ flag=DE }:: [Mao](https://osu.ppy.sh/users/2204515), en la que los mappers no pueden ver las partes del otro hasta que el beatmap esté terminado. En estos casos, se suelen colocar objetos al final de cada sección para indicar desde dónde continuar.
```

2024-06-20 13:39 UTC, UnknownOsu approved these changes

2024-06-22 06:42 UTC, cl8n approved these changes

2024-06-22 06:50 UTC, merged