[ES] Update `Beatmap discussion`
ppy/osu-wiki pull request #11625
Opened 2024-06-20 12:30 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-06-20 14:00 UTC, UnknownOsu requested changes

2024-06-20 14:01 UTC, UnknownOsu commented
Tal vez puedas quitar el `outdated` de arriba

2024-08-03 18:40 UTC, TicClick commented
@agatemosu hey, what's the status of this PR?

2024-08-03 19:08 UTC, UnknownOsu commented on wiki/Beatmap_discussion/es.md
> +Es importante tener en cuenta algunas cosas para usar las páginas de discusión de beatmaps de manera efectiva:
@agatemosu

2024-08-04 10:23 UTC, agatemosu commented
its ok

2024-08-04 16:52 UTC, UnknownOsu approved these changes

2024-08-13 20:14 UTC, TicClick approved these changes

2024-08-13 20:17 UTC, merged