[ES] Update `Beatmap/Lead-in time`
ppy/osu-wiki pull request #11622
Opened 2024-06-20 11:57 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-06-20 13:26 UTC, UnknownOsu requested changes

2024-06-20 13:26 UTC, UnknownOsu commented on wiki/Beatmap/Lead-in_time/es.md
>  El tiempo de entrada mínimo utilizado automáticamente por osu! es de 1.8 segundos. Con la [velocidad de aproximación](/wiki/Beatmap/Approach_rate) más baja de 0, esta es la cantidad de tiempo que un
```suggestion
El tiempo de entrada mínimo usado automáticamente por osu! es de 1,8 segundos. Con la [velocidad de aproximación](/wiki/Beatmap/Approach_rate) más baja de 0, esta es la cantidad de tiempo que un objeto es visible antes de que necesite ser golpeado. Cualquier [storyboard](/wiki/Storyboard) o vídeo que se reproduzca antes del primer objeto puede extender el tiempo de entrada.
```

2024-06-20 13:27 UTC, UnknownOsu commented
Tal vez puedes poner en los tags `tiempo de entrada`, `entrada`, `tiempo de entrada del audio` o así

2024-06-20 13:39 UTC, UnknownOsu approved these changes

2024-06-22 06:48 UTC, cl8n approved these changes

2024-06-22 06:54 UTC, merged