Add `Donut Cup` wiki article
ppy/osu-wiki pull request #11688
Opened 2024-07-04 17:38 UTC by Nivalyx

wiki article for the currently ongoing [Donut Cup](https://osu.ppy.sh/community/forums/topics/1910425).

for [Rentai](http://osu.ppy.sh/u/11033243) and [KKipalt](http://osu.ppy.sh/u/6889573) 🪼 

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-07-04 17:44 UTC, Nivalyx commented
a few things to note :

- yes the tournament offers actual donuts as their prizes
- yes the tournament refers to their finals and grand finals stage as "friend" and "girl friend" interchangeably

![image](https://github.com/ppy/osu-wiki/assets/36564236/8f51470a-45f3-43be-ba40-637fc540a268)
![image](https://github.com/ppy/osu-wiki/assets/36564236/a1a47fc0-ecae-47d9-8389-f7d336e0d088)

- there was a discussion

2024-07-05 04:47 UTC, Walavouchey requested changes
skimmed, ok afterwards

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | 1 month of osu!supporter for each team member, custom-made profile banner, a batch of freshly-baked donuts (conditional according to feasibi
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | 1 month of osu!supporter for each team member, custom-made profile banner, a batch of freshly baked donuts (conditional according to feasibility of the delivery) |
```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +   - Barring the tiebreaker, there are no restrictions as to which maps may and may not be banned in a match.
more natural

```suggestion
   - Barring the tiebreaker, there are no restrictions as to which maps may or may not be banned in a match.
```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +   - If a team is unable to come up with a pick within a 90–second time window of their picking turn, the pick will be given to the other team.
```suggestion
   - If a team is unable to come up with a pick within a 90-second time window of their picking turn, the pick will be given to the other team.
```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +   - No Mod doesn't count as an unique mod combination.
```suggestion
   - No Mod does not count as an unique mod combination.
```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +
```suggestion

## Notes

```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +  3. [paraoka - rampage (kiri09) \[9\]](https://osu.ppy.sh/beatmapsets/113359#osu/294086)
```suggestion
  3. [paraoka - rampage (kiri09) \[9\]](https://osu.ppy.sh/beatmapsets/113359#osu/294086)
```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +  2. [Kikuo - Yousei no Kiri (Vararaup) \[Damnjelly's Magical\]](https://osu.ppy.sh/beatmapsets/1880072#osu/3870421)
```suggestion
  2. [Kikuo - Yousei no Kiri (Vararaup) \[Damnjelly's Magical\]](https://osu.ppy.sh/beatmapsets/1880072#osu/3870421)
```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +  2. [inabakumori - Tokoshizume  (xyperX) \[Kard's Insane\]](https://osu.ppy.sh/beatmapsets/1777533#osu/3657734)
```suggestion
  2. [inabakumori - Tokoshizume (xyperX) \[Kard's Insane\]](https://osu.ppy.sh/beatmapsets/1777533#osu/3657734)
```

2024-07-05 04:47 UTC, Walavouchey commented on wiki/Tournaments/Donut_Cup/1/en.md
> +  2. [yanaginagi - Sentimental (defiance) \[Insane\]](https://osu.ppy.sh/beatmapsets/1562788#osu/3191336)
```suggestion
  2. [yanaginagi - Sentimental (defiance) \[Insane\]](https://osu.ppy.sh/beatmapsets/1562788#osu/3191336)
```

2024-07-05 12:31 UTC, Walavouchey approved these changes

2024-07-05 12:33 UTC, merged