[ES] Add `Client/Beatmap editor/Design`
ppy/osu-wiki pull request #11684
Opened 2024-07-02 18:38 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-10 17:32 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-10 17:32 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Beatmap_editor/Design/es.md
> +Para las lecturas, **x/y** son las *propias* coordenadas de tu ratón en el beatmap y cambiarán frenéticamente a medida que muevas el ratón. **{número}ms** es la marca de tiempo en milisegundos. **SB
```suggestion
Para las lecturas, **x/y** son las *propias* coordenadas de tu ratón en el beatmap y cambiarán frenéticamente a medida que muevas el ratón. **{número}ms** es la marca de tiempo en milisegundos. **SB Load** es la cantidad de potencia de procesamiento necesaria para reproducir *solo* el storyboard. Generalmente, mantén la carga SB lo más baja posible (1,00~2,00) durante el tiempo de juego y déjala rodar durante el tiempo de descanso/introducción/finalización.
```

2024-07-10 17:32 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Beatmap_editor/Design/es.md
> +- No hay soporte para efectos de sonido, esto no es un gran problema ya que los efectos de sonido pueden distraer a los jugadores, especialmente si están cerca de [objetos](/wiki/Gameplay/Hit_object)
```suggestion
- No hay soporte para efectos de sonido. Esto no es un gran problema, ya que los efectos de sonido pueden distraer a los jugadores, especialmente si están cerca de [objetos](/wiki/Gameplay/Hit_object). El uso de efectos de sonido debe ser realizado únicamente por mappers avanzados y con la guía de un BAT.
```

2024-07-10 17:32 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Beatmap_editor/Design/es.md
> +- La coordenada del sprite es *siempre* 320,240. Deberás usar el comando Move una vez para establecer la ubicación (no se requiere punto final).
```suggestion
- La coordenada del sprite es *siempre* 320,240. Deberás usar el comando Mover una vez para establecer la ubicación (no se requiere punto final).
```

2024-07-12 21:23 UTC, TicClick approved these changes

2024-07-12 21:23 UTC, merged