[ES] Add `Client/Interface/Multiplayer`
ppy/osu-wiki pull request #11699
Opened 2024-07-06 01:08 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-12 19:00 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-12 19:00 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Interface/Multiplayer/es.md
> +En este modo, el orden en el que juegan los jugadores depende de la posición de sus posiciones en la sala.
```suggestion
En este modo, el orden en el que juegan los jugadores depende de la posición que ocupen en la sala de la partida.
```

2024-07-12 19:00 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Interface/Multiplayer/es.md
> +La pantalla de resultados `Tag-team VS` es idéntica a la [pantalla de resultados de Team VS](#pantalla-de-resultados-de-Team-VS), excepto en que los resultados individuales se pueden ver en diferente
```suggestion
La pantalla de resultados de `Tag-team VS` es idéntica a la [pantalla de resultados de Team VS](#pantalla-de-resultados-de-Team-VS), excepto en que los resultados individuales se pueden ver en diferentes pestañas para cada equipo.
```

2024-08-02 22:28 UTC, TicClick approved these changes

2024-08-02 22:28 UTC, merged