[ES] Add `Client/Program files/User configuration file`
ppy/osu-wiki pull request #11698
Opened 2024-07-06 01:08 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-10 18:34 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-10 18:34 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Program_files/User_configuration_file/es.md
> +| `SeasonalBackgrounds` | Cadena | Seasonal backgrounds |
```suggestion
| `SeasonalBackgrounds` | Cadena | Seasonal backgrounds (fondos de temporada) |
```

2024-07-10 18:34 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Program_files/User_configuration_file/es.md
> +| `keyPause` | Pausa el juego |
```suggestion
| `keyPause` | Pausar el juego |
```

2024-07-10 18:34 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Client/Program_files/User_configuration_file/es.md
> +| `EditorGridSizeDesign` | Entero | Diseño del tamaño de la rejilla en [osu! píxeles](/wiki/Client/Beatmap_editor/osu!_pixel) |
```suggestion
| `EditorGridSizeDesign` | Entero | Diseño del tamaño de la rejilla en [osu! pixels](/wiki/Client/Beatmap_editor/osu!_pixel) |
```

2024-07-12 21:35 UTC, TicClick approved these changes

2024-07-12 21:35 UTC, merged