[ES] Add `Community/Forum/Off-Topic`
ppy/osu-wiki pull request #11696
Opened 2024-07-06 01:08 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-10 18:16 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-10 18:16 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Forum/Off-Topic/es.md
> +El **exilio** es un concepto de moderación no oficial introducido por [Ephemeral](https://osu.ppy.sh/users/102335) en [the grand edict thread](https://osu.ppy.sh/community/forums/topics/604424) como
```suggestion
El **exilio** es un concepto de moderación no oficial introducido por [Ephemeral](https://osu.ppy.sh/users/102335) en el hilo [the grand edict](https://osu.ppy.sh/community/forums/topics/604424) como respuesta a la gente que repetidamente hacía spam en el subforo y creaba contenido molesto. El sistema de exilio se aplica eliminando los hilos y, a veces, las publicaciones de la persona exiliada. Sirve como indicador de que la persona está a punto de ser fuertemente sancionada por medios más oficiales de moderación.
```

2024-07-10 18:16 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Forum/Off-Topic/es.md
> +**OT Lore** es un proyecto iniciado por [abraker](https://osu.ppy.sh/users/4635891) y continuado por otros denizens para crear una narrativa global a partir de los diversos hilos que la gente ha crea
```suggestion
**OT Lore** es un proyecto iniciado por [abraker](https://osu.ppy.sh/users/4635891) y continuado por otros denizens para crear una narrativa global a partir de los diversos hilos que la gente ha creado en OT. La culminación de este proyecto se recopiló en [OT!Chronicles](https://osu.ppy.sh/community/forums/posts/6230570), que dio lugar a un periodo de tiempo en OT compuesto por muchos hilos improvisados relacionados con los juegos de rol.
```

2024-07-12 21:30 UTC, TicClick approved these changes

2024-07-12 21:30 UTC, merged