Add the `COE X YUKI AIM 2024 1v1 Tournament: Registrations are live!` news post
ppy/osu-wiki pull request #11744
Opened 2024-07-15 13:35 UTC by 0x84f

- [ ] make sure yt vid is correct
- [ ] meyer/cavoe approval

2024-07-15 13:56 UTC, 0x84f commented on news/2024/2024-07-17-coe-x-yukiaim-1v1-tournament.md
> +If you are somehow not familiar COE, or it's 1v1 tournament, [COE](/wiki/Community/cavoe%27s_osu%21_event) is osu!'s largest community-hosted event, hosted by [Meyer](https://osu.ppy.sh/users/5452367
```suggestion
If you are somehow not familiar with COE, or it's 1v1 tournament, [COE](/wiki/Community/cavoe's_osu!_event) is osu!'s largest community-hosted event, hosted by [Meyer](https://osu.ppy.sh/users/5452367) and [cavoeboy](https://osu.ppy.sh/users/7361815) from July 30th up until August 4th. Along with the event itself, for the 3rd year in a row the largest LAN tournament of the year will be held there as well, with hundreds of live viewers and even more online on [Twitch](https://www.twitch.tv/COEvent)!
```

2024-07-15 13:56 UTC, 0x84f commented on news/2024/2024-07-17-coe-x-yukiaim-1v1-tournament.md
> +The total prize pool of &euro;3000 will be divided among the top 3 players, along with physical prizes also being handed out.
```suggestion
The total prize pool of €3000 will be divided among the top 3 players, along with physical prizes also being handed out.
```

2024-07-15 16:16 UTC, iSlodinxOsu requested changes

2024-07-15 16:16 UTC, iSlodinxOsu commented on news/2024/2024-07-17-coe-x-yukiaim-1v1-tournament.md
> +If you are somehow not familiar with COE, or it's 1v1 tournament, [COE](/wiki/Community/cavoe's_osu!_event) is osu!'s largest community-hosted event, hosted by [Meyer](https://osu.ppy.sh/users/545236
```suggestion
If you are somehow not familiar with COE, or it's 1v1 tournament, [COE](/wiki/Community/cavoe's_osu!_event) is osu!'s largest community-hosted event, hosted by [Meyer](https://osu.ppy.sh/users/5452367) & [cavoeboy](https://osu.ppy.sh/users/7361815) from July 30th up until August 4th. Along with the event itself, for the 3rd year in a row the largest LAN tournament of the year will be held there as well, with hundreds of live viewers and even more online on [Twitch](https://www.twitch.tv/COEvent)!
```

2024-07-15 17:55 UTC, 0x84f commented on wiki/Community/cavoe's_osu!_event/en.md
> +[Website](https://cavoeboy.com/) * [Twitter](https://twitter.com/CavoesOsuEvent) * [YouTube](https://www.youtube.com/@coevent) * [Twitch](https://www.twitch.tv/coevent) * [Discord](https://discord.co
```suggestion
[Website](https://cavoeboy.com/) • [Twitter](https://twitter.com/CavoesOsuEvent) • [YouTube](https://www.youtube.com/@coevent) • [Twitch](https://www.twitch.tv/coevent) • [Discord](https://discord.com/invite/d6ru6PVcSY)
```

2024-07-15 17:55 UTC, 0x84f commented on wiki/Community/cavoe's_osu!_event/es.md
> +[Sitio web](https://cavoeboy.com/) * [Twitter](https://twitter.com/CavoesOsuEvent) * [YouTube](https://www.youtube.com/@coevent) * [Twitch](https://www.twitch.tv/coevent) * [Discord](https://discord.
```suggestion
[Sitio web](https://cavoeboy.com/) • [Twitter](https://twitter.com/CavoesOsuEvent) • [YouTube](https://www.youtube.com/@coevent) • [Twitch](https://www.twitch.tv/coevent) • [Discord](https://discord.com/invite/d6ru6PVcSY)
```

2024-07-15 17:56 UTC, 0x84f commented on wiki/Community/cavoe's_osu!_event/fr.md
> +[Site web](https://cavoeboy.com/) * [Twitter](https://twitter.com/CavoesOsuEvent) * [YouTube](https://www.youtube.com/@coevent) * [Twitch](https://www.twitch.tv/coevent) * [Discord](https://discord.c
```suggestion
[Site web](https://cavoeboy.com/) • [Twitter](https://twitter.com/CavoesOsuEvent) • [YouTube](https://www.youtube.com/@coevent) • [Twitch](https://www.twitch.tv/coevent) • [Discord](https://discord.com/invite/d6ru6PVcSY)
```

2024-07-15 18:15 UTC, iSlodinxOsu requested changes

2024-07-15 18:15 UTC, iSlodinxOsu commented on wiki/Community/cavoe's_osu!_event/en.md
replace the letter case on chocomint from uppercase to lowercase on both en.md and es.md

2024-07-15 19:05 UTC, 0x84f commented on wiki/Community/cavoe's_osu!_event/en.md
done ty

2024-07-17 23:25 UTC, Walavouchey requested changes

2024-07-18 08:15 UTC, 0x84f commented on news/2024/2024-07-19-coe-x-yukiaim-1v1-tournament.md
> +COE is also the perfect time to meet your favourite osu! players and content creators, either at the karaoke night, sushi dinner, or just roaming in and around the venue. With familiar faces such as
i wouldnt say its a selling point cuz the pitch has already been done above, but i like how you worded this more so adding it

2024-07-18 16:21 UTC, Walavouchey requested changes

2024-07-19 09:28 UTC, 0x84f commented on news/2024/2024-07-19-coe-x-yukiaim-1v1-tournament.md
> +title: "COE X YUKI AIM 2024 1v1 Tournament: Registrations are live!"
ill change the file name separately but yeah this is fine

2024-07-19 18:31 UTC, Walavouchey approved these changes

2024-07-19 18:57 UTC, merged