[ES] Update `osu!supporter`
ppy/osu-wiki pull request #11748
Opened 2024-07-15 23:36 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-19 11:37 UTC, agatemosu reviewed
1

2024-07-19 11:37 UTC, agatemosu commented on wiki/osu!supporter/es.md
> +## Conseguir un osu!supporter
```suggestion
## Conseguir osu!supporter
```

2024-07-19 11:37 UTC, agatemosu commented on wiki/osu!supporter/es.md
> +### Regalar un osu!supporter
```suggestion
### Regalar osu!supporter
```

2024-07-19 11:37 UTC, agatemosu commented on wiki/osu!supporter/es.md
> +![](img/profile-gift-supporter-ES.png "Botón con menú desplegable en una página de perfil para regalarle a alguien un osu!supporter")
```suggestion
![](img/profile-gift-supporter-ES.png "Botón con menú desplegable en una página de perfil para regalarle osu!supporter a alguien")
```

2024-08-09 10:06 UTC, agatemosu commented on wiki/osu!supporter/es.md
> +- Haz clic en el icono del lápiz en la esquina inferior derecha de la portada del perfil.
```suggestion
- Haz clic en el icono del lápiz situado en la esquina inferior derecha de la portada del perfil.
```

2024-08-09 10:08 UTC, agatemosu commented on wiki/osu!supporter/es.md
> +**osu!supporter** (o la ***etiqueta osu!supporter***) es un título temporal dado a los jugadores que apoyan a osu! de manera voluntaria con una donación monetaria para ayudarlo a crecer. Los supporte
```suggestion
**osu!supporter** (o la ***etiqueta de osu!supporter***) es un título temporal dado a los jugadores que apoyan a osu! de manera voluntaria con una donación monetaria para ayudarlo a crecer. Los supporters reciben un puñado de beneficios cosméticos y técnicos, la mayoría solo se presentan cuando el título está presente. Las características extras de osu!supporter no dan ningún tipo de ventaja en el juego, rendimiento o puntuación, y nunca lo hará.
```

2024-08-09 10:08 UTC, agatemosu commented on wiki/osu!supporter/es.md
>  La etiqueta osu!supporter podrá ser obtenida desde la [página de la tienda de osu!supporter](https://osu.ppy.sh/store/products/supporter-tag).
```suggestion
La etiqueta de osu!supporter podrá ser obtenida desde la [página de la tienda de osu!supporter](https://osu.ppy.sh/store/products/supporter-tag).
```

2024-08-09 19:57 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-08-09 19:57 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!supporter/es.md
> +La etiqueta de osu!supporter podrá ser obtenida desde la [página de la tienda de osu!supporter](https://osu.ppy.sh/store/products/supporter-tag).
```suggestion
La etiqueta de osu!supporter puede obtenerse en la [página de la tienda de osu!](https://osu.ppy.sh/store/products/supporter-tag).
```

2024-08-09 19:57 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!supporter/es.md
> +- Haz clic en el icono del lápiz en la esquina inferior derecha de la portada del perfil.
```suggestion
- Haz clic en el icono del lápiz situado en la esquina inferior derecha de la portada del perfil.
```

2024-08-09 19:57 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!supporter/es.md
> +Después, haz clic en `Añadir al carrito` para agregar tu etiqueta de osu!supporter al carrito de la osu!store. Para finalizar la compra, ve al [carrito](https://osu.ppy.sh/store/cart) y haz clic en `
```suggestion
Después, haz clic en `Añadir al carrito` para añadir tu etiqueta de osu!supporter al carrito de la osu!store. Para finalizar la compra, ve al [carrito](https://osu.ppy.sh/store/cart) y haz clic en `Pagar`, luego sigue las indicaciones de la pantalla.
```

2024-08-09 19:57 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!supporter/es.md
> +![](img/profile-gift-supporter-ES.png "Botón con menú desplegable en una página de perfil para regalarle osu!supporter a alguien")
```suggestion
![](img/profile-gift-supporter-ES.png "Botón con menú desplegable en una página de perfil para regalarle un osu!supporter a alguien")
```

2024-08-09 21:15 UTC, agatemosu approved these changes

2024-08-13 19:48 UTC, TicClick approved these changes

2024-08-13 19:48 UTC, merged