[ES] Add `Guides/Compressing files`
ppy/osu-wiki pull request #11759
Opened 2024-07-16 23:33 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-21 18:41 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-21 18:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Compressing_files/es.md
> +3. Selecciona la pestaña `Audio` y elimine todas las pistas de audio. Haz lo mismo con los subtítulos entrando en la pestaña `Subtítulos` y eliminando todas las opciones.
```suggestion
3. Selecciona la pestaña `Audio` y elimina todas las pistas de audio. Haz lo mismo con los subtítulos entrando en la pestaña `Subtítulos` y eliminando todas las opciones.
```

2024-07-21 18:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Compressing_files/es.md
> +En general, OGG (Vorbis) ofrece mejor calidad que MP3 para una tasa de bits determinada.
```suggestion
En general, OGG (Vorbis) ofrece una mejor calidad que MP3 para una tasa de bits determinada.
```

2024-07-21 18:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Compressing_files/es.md
> +- `-q:a 5`: Usa el mismo rango de tasa de bits variable que en el ejemplo de Audacity, **donde un número más alto significa mayor tasa de bits**. Si quieres una tasa de bits constante, usa, por ejemp
```suggestion
- `-q:a 5`: Usa el mismo rango de tasa de bits variable que en el ejemplo de Audacity, **donde un número más alto significa una mayor tasa de bits**. Si quieres una tasa de bits constante, usa, por ejemplo, `-b:a 128k` para una tasa constante de 128kbps
```

2024-08-02 22:59 UTC, TicClick approved these changes

2024-08-02 22:59 UTC, merged