[ES] Add `Guides/Beginner's tutorial`
ppy/osu-wiki pull request #11757
Opened 2024-07-16 23:33 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-21 18:23 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-21 18:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Beginner's_tutorial/es.md
> +Cada objeto del juego tiene un círculo de aproximación; un anillo grande que se acerca lentamente al círculo. Cuando el anillo llega al círculo, ¡es el momento de pulsarlo! Si les prestas atención co
```suggestion
Cada objeto del juego tiene un círculo de aproximación; un anillo grande que se acerca lentamente al círculo. Cuando el anillo llega al círculo, ¡es el momento de pulsarlo! Si les prestas atención con cuidado, te ayudarán a reconocer si algunas notas están en medio pulso o en pulso completo, o si tienes que esperar a la siguiente nota.
```

2024-07-21 18:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Beginner's_tutorial/es.md
> +La música funciona en pulsos y ritmos. Cuando empieces un mapa (o incluso antes de jugar) presta atención a cómo suena la canción, y podrás hacerte una idea bastante aproximada de la melodía a la que
```suggestion
La música funciona en pulsos y ritmos. Cuando empieces un mapa (o incluso antes de jugar) presta atención a cómo suena la canción, y podrás hacerte una idea bastante aproximada de la melodía a la que vas a pulsar los círculos. Seguir la música más de cerca te ayudará a conseguir una mejor coordinación y sincronización con ella.
```

2024-07-21 18:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Beginner's_tutorial/es.md
> +La mejor manera de mejorar es desafiarte a ti mismo. La única forma de que te acostumbres a dificultades cada vez más difíciles es explorando más allá de tus límites. Jugar en un mapa que te hace fal
```suggestion
La mejor manera de mejorar es desafiarte a ti mismo. La única forma de que te acostumbres a dificultades cada vez más difíciles es explorando más allá de tus límites. Jugar un mapa que te hace fallar bastantes veces otorga, en definitiva, más experiencia de juego que jugar muchos en los que puedes conseguir un combo completo o incluso obtener un rango SS. Esto funciona de forma muy parecida a un MMORPG: cuanto más fuerte sea el enemigo, más experiencia obtendrás por él.
```

2024-07-21 18:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Beginner's_tutorial/es.md
> +Dependiendo de los dispositivos que uses para jugar a osu!, puede que los círculos no sigan el ritmo de la música. Para corregir esto, puede cambiar el valor de la compensación global en las [opcione
```suggestion
Dependiendo de los dispositivos que uses para jugar a osu!, puede que los círculos no sigan el ritmo de la música. Para corregir esto, puedes cambiar el valor de la compensación global en las [opciones](/wiki/Client/Options). La compensación global cambiará cuando la primera nota aparezca en los beatmaps (antes o después de lo predeterminado), lo que a su vez retrasará el resto de las notas en la misma cantidad. Un valor negativo en la compensación hará que las notas aparezcan ligeramente más tarde, y un valor positivo hará que aparezcan antes.
```

2024-07-21 18:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Beginner's_tutorial/es.md
> +Cuando estés jugando un beatmap notarás el gráfico de error de los golpes en la parte inferior de la pantalla. Al pulsar una nota, aparece una línea blanca a lo largo de ella, dependiendo de lo preci
```suggestion
Cuando estés jugando un beatmap, notarás el gráfico de error de los golpes en la parte inferior de la pantalla. Al pulsar una nota, aparece una línea blanca a lo largo de ella, dependiendo de lo preciso que hayas sido. Si todos tus golpes están a la izquierda del centro, prueba a aumentar ligeramente la compensación global. Si están todos en el lado derecho, prueba a disminuirla.
```

2024-08-02 23:24 UTC, TicClick approved these changes

2024-08-02 23:24 UTC, merged