[ES] Add `Guides/Changing the artist or title`
ppy/osu-wiki pull request #11758
Opened 2024-07-16 23:33 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-21 18:29 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-21 18:29 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Changing_the_artist_or_title/es.md
> +  3. Ve al editor. Asegúrate de que el menú «Web» está activado (no en gris).
```suggestion
  3. Ve al editor. Asegúrate de que el menú «Web» esté activado (no en gris).
```

2024-07-21 18:29 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Changing_the_artist_or_title/es.md
> +  4. Ve al editor. Asegúrate de que el menú «Web» está activado (no en gris).
```suggestion
  4. Ve al editor. Asegúrate de que el menú «Web» esté activado (no en gris).
```

2024-08-02 22:54 UTC, TicClick approved these changes

2024-08-02 22:54 UTC, merged