[ES] Add `Guides/Getting your map modded`
ppy/osu-wiki pull request #11765
Opened 2024-07-16 23:34 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-19 11:29 UTC, agatemosu commented on wiki/Guides/Getting_your_map_modded/es.md
> +Preguntar directamente a otros usuarios también es una excelente manera de obtener mods. Generalmente, si un modder no tiene una cola de modding, lo más probable es que tenga su información de moddin
```suggestion
Preguntar directamente a otros usuarios también es una excelente manera de obtener mods. Generalmente, si un modder no tiene una cola de modding, lo más probable es que tenga su información de modding en la sección «¡yo!» de su perfil. Después de leer la información que tiene allí, puedes enviarle un mensaje en el chat de osu! con tu solicitud. Aunque estos modders son más difíciles de encontrar, todavía hay algunos por ahí, muchos de los cuales tienen colas privadas fuera de la plataforma y tal.
```

2024-07-19 11:29 UTC, agatemosu commented on wiki/Guides/Getting_your_map_modded/es.md
> +Por lo general, es aceptable publicar en varias colas de modding a la vez, así que no dudes en repetir este proceso si es necesario, o si quieres aumentar tus posibilidades de recibir un mod. Sin emb
```suggestion
Por lo general, es aceptable publicar en varias colas de modding a la vez, así que no dudes en repetir este proceso si es necesario, o si quieres aumentar tus posibilidades de recibir un mod. Sin embargo, ten en cuenta que el hecho de que hayas publicado en una cola de modding no significa que el modder esté obligado a modear tu beatmap; lo modeará si así lo desea.
```

2024-07-27 18:37 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-27 18:37 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Getting_your_map_modded/es.md
> +`#modreqs` no tiene la misma funcionalidad y base de usuarios que tenía en el pasado, pero sigue siendo un método útil para obtener mods, por lo que vale la pena intentarlo. Si bien en la actualidad
```suggestion
`#modreqs` no tiene la misma funcionalidad y base de usuarios que tenía en el pasado, pero sigue siendo un método útil para obtener mods, por lo que vale la pena intentarlo. Si bien en la actualidad se trata sobre todo de solicitudes de mods normales, también se suele usar para los otros tipos de solicitudes mencionados [más arriba](#tipos-de-mods).
```

2024-08-03 18:22 UTC, TicClick approved these changes

2024-08-03 18:22 UTC, merged