[ES] Add `Guides/Custom sample overrides`
ppy/osu-wiki pull request #11763
Opened 2024-07-16 23:34 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-22 16:23 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-22 16:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Custom_sample_overrides/es.md
> +Las tres muestras siguientes son aditivas, lo que significa que cuando golpees un whistle obtendrás un hitnormal + hitwhistle.
```suggestion
Las siguientes tres muestras son aditivas, lo que significa que cuando golpees un whistle obtendrás un hitnormal + hitwhistle.
```

2024-07-22 16:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Custom_sample_overrides/es.md
> +Las tres muestras siguientes son aditivas, lo que significa que cuando golpees un whistle obtendrás un hitnormal + hitwhistle.
```suggestion
Las siguientes tres muestras son aditivas, lo que significa que cuando golpees un whistle obtendrás un hitnormal + hitwhistle.
```

2024-07-22 16:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Custom_sample_overrides/es.md
> +Las tres muestras siguientes son aditivas, lo que significa que cuando golpees un whistle obtendrás un hitnormal + hitwhistle.
```suggestion
Las siguientes tres muestras son aditivas, lo que significa que cuando golpees un whistle obtendrás un hitnormal + hitwhistle.
```

2024-08-02 23:19 UTC, TicClick approved these changes

2024-08-02 23:19 UTC, merged