[ES] Add `Guides/Cropping with complex backgrounds`
ppy/osu-wiki pull request #11760
Opened 2024-07-16 23:33 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-21 18:46 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-21 18:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Cropping_with_complex_backgrounds/es.md
> +Si has terminado tu selección principal, ahora podemos ocuparnos de cualquier fondo que haya sido seleccionado junto con nuestro personaje. Continúa usando la herramienta lazo, pero cambia su modo a
```suggestion
Si has terminado tu selección principal, ahora podemos ocuparnos de cualquier fondo que haya sido seleccionado junto con nuestro personaje. Continúa usando la herramienta lazo, pero cambia su modo a «Extraer de la selección actual», es decir, eliminar la selección. Y ahora haz lo mismo que al principio al deseleccionar cualquier fondo que estuviera entre el pelo, piernas, etc.
```

2024-07-21 18:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Cropping_with_complex_backgrounds/es.md
> +Está terminado. No queda muy bien, sobre todo en las puntas, pero es porque no fui muy preciso al hacerlo.
```suggestion
Está terminado. No quedó muy bien, sobre todo en las puntas, pero es porque no fui muy preciso al hacerlo.
```

2024-08-02 23:04 UTC, TicClick approved these changes

2024-08-02 23:04 UTC, merged