Add benefits to `Project Loved Team`
ppy/osu-wiki pull request #11791
Opened 2024-07-19 13:38 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-07-21 21:41 UTC, cl8n requested changes
feels cringe to present this as a "benefit" but I guess w/e cuz other pages say the same thing

also the "5 years" note on the last line of the article is wrong now. that whole last sentence can just be removed

2024-07-21 21:41 UTC, cl8n commented on wiki/People/Project_Loved_Team/es.md
> +outdated_translation: true
`outdated_since` as well

2024-07-21 21:41 UTC, cl8n commented on wiki/People/Project_Loved_Team/en.md
> +- **Tenure badge**: A [profile badge](/wiki/Community/Profile_badge) that displays the number of years they have been in the LVD, ranging from 1 to 6.
```suggestion
- **Tenure badge**: A [profile badge](/wiki/Community/Profile_badge) that displays the number of years they have been helping run Project Loved.
```

2024-07-21 21:41 UTC, cl8n commented on wiki/People/Project_Loved_Team/en.md
> +Project Loved Team members are granted the following benefits:
"Project Loved Team members are given profile badges that display the number of years [...]"
no need for 1-item list

2024-07-21 21:53 UTC, minusQuantumNeko commented
I do agree it's not the best to present it as a benefit, but yes, I used the same thing other teams pages use

2024-07-21 22:00 UTC, minusQuantumNeko commented on wiki/People/Project_Loved_Team/en.md
> +- **Tenure badge**: A [profile badge](/wiki/Community/Profile_badge) that displays the number of years they have been helping run Project Loved.
Maybe this?
```suggestion
Project Loved Team members are given a tenure [profile badge](/wiki/Community/Profile_badge) that displays the number of years they have been helping run Project Loved.
```

2024-07-25 08:09 UTC, cl8n approved these changes

2024-07-25 08:12 UTC, merged