[ES] Add `Guides/How to time songs`
ppy/osu-wiki pull request #11818
Opened 2024-07-23 20:07 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-27 19:13 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-27 19:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/How_to_time_songs/es.md
> +Además de conseguir juicios de 300s, tienes que echar un vistazo a la parte izquierda de la ventana del modo de prueba. Hay una línea que se parece a esto en la imagen: **Mistimed Hits: 69% (ave 25ms
```suggestion
Además de conseguir juicios de 300, tienes que echar un vistazo a la parte izquierda de la ventana del modo de prueba. Hay una línea que se parece a esto en la imagen: **Mistimed Hits: 69% (ave 25ms late).**
```

2024-07-27 19:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/How_to_time_songs/es.md
> +Al final del juego de prueba, comprueba los resultados. Si las notas tienen grandes errores de temporización (adelantadas/atrasadas en 25 ms, por ejemplo) y ves que el error sigue creciendo a lo larg
```suggestion
Al final del juego de prueba, comprueba los resultados. Si las notas tienen grandes errores de temporización (por ejemplo, adelantadas/atrasadas en 25 ms) y ves que el error sigue creciendo a lo largo de la prueba, aumenta/disminuye el BPM respectivamente. Cambia el valor gradualmente por décimas, centésimas, etc. (no olvides conservar los ajustes originales como reserva). Con el tiempo, después de varias pruebas y errores, el error de acierto será tan pequeño que podrá omitirse de forma segura sin tener un efecto perjudicial. El porcentaje de aciertos fuera de tiempo debe ser inferior al 5 %, la temporización no debería ser superior a 5 ms antes/después.
```

2024-07-27 19:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/How_to_time_songs/es.md
> +Hay situaciones en las que una línea roja no es suficiente (algunos ejemplos serían [Bad Apple](https://osu.ppy.sh/beatmapsets/18260), [DJ Amuro's A](https://osu.ppy.sh/beatmapsets/2997) o [kemu's Ik
```suggestion
Hay situaciones en las que una línea roja no es suficiente (algunos ejemplos serían [Bad Apple](https://osu.ppy.sh/beatmapsets/18260), [DJ Amuro's A](https://osu.ppy.sh/beatmapsets/2997) o [kemu's Ikasama Life Game](https://osu.ppy.sh/beatmapsets/59792)). Admítelo, puede ser desde hard rock, metal, cualquier composición de guitarra, conciertos en vivo, canciones con aceleración/deceleración/pausa audibles ([Black∞Hole's Pluto](https://osu.ppy.sh/beatmapsets/45074)), etc. Incluso usando el metrónomo, ciertas partes de una canción (probablemente en el clímax o en la sección final) ya no encajan con el ritmo anterior. El tempo de la canción sube/baja repentinamente, el cantante empieza a cantar de forma frenética/melódica y se apaga, y los instrumentos musicales suenan mucho/acústicamente. En este caso, desplazar o cambiar la primera línea roja para adaptarla al tempo no servirá de nada.
```

2024-07-27 19:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/How_to_time_songs/es.md
> +   - Si hay un cambio notable en el tempo y **no** es el resultado de un golpe temprano o tardío, añade una nueva compensación (también conocido como puntero de tiempo para anular la base) y cámbialo
```suggestion
   - Si hay un cambio notable en el tempo y **no** es el resultado de un golpe temprano o tardío, añade una nueva compensación (también conocido como puntero de tiempo para anular la base) y cámbiala por un número apropiado de milisegundos (el error de aciertos lo dirá).
```

2024-07-27 19:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/How_to_time_songs/es.md
> +   - Si no hay ningún cambio, pero ves que el error empieza a aumentar, como si hubieras ajustado mal el BPM (excepto que estaba bien todo el tiempo antes de llegar a ese punto), añade una nueva comp
```suggestion
   - Si no hay ningún cambio, pero ves que el error empieza a aumentar, como si hubieras ajustado mal el BPM (excepto que estaba bien todo el tiempo antes de llegar a ese punto), añade una nueva compensación no heredada y modifica su BPM. Haz esto en la pestaña Timing. (F3) Es decir, usa el metrónomo de osu! y trata de captar un cambio, luego pruébalo como una compensación individual normal. A diferencia de las canciones tradicionales y monótonas, el nuevo valor del BPM puede diferir del promedio. Lo importante es determinarlo con la mayor precisión posible.
```

2024-08-02 23:51 UTC, TicClick approved these changes

2024-08-02 23:51 UTC, merged