[ES] Add `Guides/How to use the Offset Wizard`
ppy/osu-wiki pull request #11819
Opened 2024-07-23 20:07 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-27 20:23 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-27 20:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/How_to_use_the_Offset_Wizard/es.md
> +3. Ajústalo hasta que escuches que el metrónomo se alinea perfectamente con la canción, usando las barras de desplazamiento en la pantalla para ayudarte.
```suggestion
3. Ajústala hasta que escuches que el metrónomo se alinea perfectamente con la canción, usando las barras de desplazamiento en la pantalla para ayudarte.
```

2024-07-27 23:09 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-27 23:09 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/How_to_use_the_Offset_Wizard/es.md
> +3. Ajústala hasta que escuches que el metrónomo se alinea perfectamente con la canción, usando las barras de desplazamiento en la pantalla para ayudarte.
```suggestion
3. Ajusta la compensación hasta que escuches que el metrónomo se alinea perfectamente con la canción, usando las barras de desplazamiento en la pantalla para ayudarte.
```

2024-08-02 23:54 UTC, TicClick approved these changes

2024-08-02 23:54 UTC, merged