[ES] Add `Guides/Timing songs with 8-signatures`
ppy/osu-wiki pull request #11827
Opened 2024-07-23 20:08 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-27 22:40 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-27 22:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Timing_songs_with_8-signatures/es.md
> +De vez en cuando, se mapean canciones cuyo compás no está dividido en negras (por ejemplo, `3/4`, `4/4`, `7/4`, ...), sino en corcheas (por ejemplo, `6/8`, `7/8`, ...). El editor actual no admite est
```suggestion
De vez en cuando, se mapean canciones cuyo compás no está dividido en negras (por ejemplo, `3/4`, `4/4`, `7/4`, ...), sino en corcheas (por ejemplo, `6/8`, `7/8`, ...). El editor actual no es compatible con este tipo de compás de #/8, pero lo hará en el futuro.
```

2024-07-27 22:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Timing_songs_with_8-signatures/es.md
> +Al menos así funciona para compases de `#/4`. La diferencia fundamental con los compases `#/8` es que un pulso no siempre contiene solo dos corcheas ♪, ¡también puede contener tres ♪s! Un buen ejempl
```suggestion
Al menos así funciona para los compases de `#/4`. La diferencia fundamental con los compases de `#/8` es que un pulso no siempre contiene solo dos corcheas ♪, ¡también puede contener tres ♪! Un buen ejemplo de ello es la diferencia entre compases de `3/4` y `6/8`: Ambos contienen seis ♪, pero mientras que `3/4` las divide en tres grupos de dos (♪♪+♪♪+♪♪, \[2+2+2\]) acentuando la primera nota de cada par, `6/8` las divide en dos grupos de tres (♪♪♪+♪♪♪, \[3+3\]). Estos «grupos» también se llaman «subdivisiones». Los compases que solo contienen subdivisiones de tres corcheas (como en `6/8`) se llaman «compuestos», mientras que los que contienen subdivisiones con cantidades variables de corcheas se llaman «complejos» o «irregulares» (por ejemplo, `7/8`, sobre el que hablaremos más adelante). Cuando un determinado patrón formado por diferentes compases se repite con regularidad, se llama «compás mixto».
```

2024-07-27 22:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Timing_songs_with_8-signatures/es.md
> +Ahora, para darte un primer ejemplo de esto en osu!, mira la dificultad de `3/4` en el conjunto de mapas proporcionado de «America» de Leonard Bernstein. En esta dificultad, temporicé todo usando un
```suggestion
Ahora, para darte un primer ejemplo de esto en osu!, mira la dificultad de `3/4` en el conjunto de mapas proporcionado de «America» de Leonard Bernstein. En esta dificultad, temporicé todo usando un compás de `3/4`, lo que significa que cada compás está dividido en tres pulsos por marcas blancas. Cuando cambias el divisor de ritmo a `1/2`, cada pulso se divide en dos por las marcas rojas en la línea de tiempo; una marca roja representa una corchea ♪. Esto funcionaría perfectamente para una canción en `3/4`, pero si escuchas atentamente podrás oír algo especial en esta canción: Mientras que el tempo general se mantiene (aproximadamente) igual, la agrupación rítmica de las ♪ cambia casi en cada compás. El primer compás de la parte mapeada en `00:03:662` se divide en \[3+3\], ya que solo tiene una acentuación más en la marca roja en `00:04:232`. El segundo compás, que comienza en `00:04:801`, está agrupado en \[2+2+2\], ya que tiene dos acentuaciones más en las marcas blancas en `00:05:181` y `00:05:561`. En otras palabras, todos los compases son igual de largos (6♪), pero la mitad de ellos solo tienen dos pulsos (compás de `6/8`), mientras que la otra mitad tiene tres pulsos (compás de `3/4`), ¡lo que lo convierte en un compás mixto! Hay diferentes maneras de manejar esto en osu!, cada una con sus ventajas y desventajas, las cuales mostraré en el siguiente segmento.
```

2024-08-03 18:10 UTC, TicClick approved these changes

2024-08-03 18:11 UTC, merged