[ES] Add `Guides/Tablet purchase`
ppy/osu-wiki pull request #11826
Opened 2024-07-23 20:08 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-27 21:42 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-27 21:42 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Tablet_purchase/es.md
> +El mayor atractivo de las tabletas para osu! es este seguimiento absoluto. Todos los demás parámetros, como los niveles de presión, la sensibilidad a la inclinación, la rotación del cuerpo del lápiz,
```suggestion
El mayor atractivo de las tabletas para osu! es este seguimiento absoluto. Todos los demás parámetros, como los niveles de presión, la sensibilidad a la inclinación, la rotación del cuerpo del lápiz, etc., no afectarán a tu juego con osu!. Estas funciones son para el arte digital, donde la tableta puede detectar cosas como la presión que estás aplicando para hacer una marca de lápiz más oscura, por ejemplo. La única especificación que puede afectar a tu juego es el LPI (líneas por pulgada).
```

2024-07-27 21:42 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Tablet_purchase/es.md
> +Huion es una empresa proveedora de la osu!tablet. Son más conocidas por ser más baratas que las tabletas Wacom por un gran margen, pero algunos dirían que sus tabletas se sienten más frágiles, y que
```suggestion
Huion es una empresa proveedora de la osu!tablet. Son más conocidas por ser más baratas que las tabletas Wacom por un gran margen, pero algunos dirían que sus tabletas se sienten más frágiles, y que al pasar un lápiz sobre una tableta Huion, se sentiría como si estuvieras escribiendo sobre papel (en comparación, algunos dicen que en Wacom es como si estuvieras escribiendo sobre vidrio). Los lápices de sus tabletas requieren una batería o deben cargarse, a diferencia de los lápices de las tabletas Wacom, y es posible que sus puntas deban reemplazarse con más frecuencia que las puntas de Wacom. Aparte de eso, realmente no hay diferencias notables entre las tabletas Wacom y Huion.
```

2024-08-03 18:12 UTC, TicClick approved these changes

2024-08-03 18:12 UTC, merged