[ES] Add `Guides/Making properly centred spinners`
ppy/osu-wiki pull request #11821
Opened 2024-07-23 20:08 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-27 20:45 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-07-27 20:45 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Making_properly_centred_spinners/es.md
> +Cansa ver spinners tambaleantes. Por favor, si quieres hacer un spinner, asegúrate de que está perfectamente centrado.
```suggestion
Cansa ver spinners tambaleantes. Por favor, si quieres hacer un spinner, asegúrate de que esté perfectamente centrado.
```

2024-07-27 20:45 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Guides/Making_properly_centred_spinners/es.md
> +Técnicamente, ya has terminado, pero si quieres hacer que el fondo se «rellene» con un medidor de fondo, entonces puedes usar el de la plantilla de la skin, o hacerlo tú mismo. Trae la plantilla del
```suggestion
Técnicamente, ya has terminado, pero si quieres hacer que el fondo se «rellene» con un medidor de fondo, entonces puedes usar el de la plantilla de la skin, o hacerlo tú mismo. Trae la plantilla del spinner-meter. Para recolorearlo, desactiva el canal alfa seleccionándolo, de modo que no modifiques en absoluto la transparencia. Luego usa el relleno de cubeta y llena toda el área con un color gris o el color que quieras.
```

2024-08-02 23:57 UTC, TicClick approved these changes

2024-08-02 23:57 UTC, merged