[IT] Update `osu!supporter`
ppy/osu-wiki pull request #11834
Opened 2024-07-24 17:22 UTC by githacki

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-25 12:50 UTC, Sclafus requested changes

2024-07-25 12:50 UTC, Sclafus commented on wiki/osu!supporter/it.md
> +### Profile colour
```suggestion
### Colore del profilo
```

2024-07-25 12:50 UTC, Sclafus commented on wiki/osu!supporter/it.md
> +- Premi sull'icona a forma di matita nell'angolo della copertina in basso a destra.
```suggestion
- Premi sull'icona a matita nell'angolo della copertina in basso a destra.
```

2024-07-25 12:50 UTC, Sclafus commented on wiki/osu!supporter/it.md
> +Una volta che l'osu!supporter scade, il colore personalizzato rimarrà, ma potrà essere modificato solo ripristinando quello predefinito.
```suggestion
Alla scadenza dell'osu!supporter, il colore personalizzato rimarrà, ma potrà essere solamente ripristinato a quello predefinito.
```

2024-07-25 13:21 UTC, Sclafus approved these changes

2024-08-02 23:44 UTC, TicClick approved these changes

2024-08-02 23:44 UTC, merged