[ES] Update `People/Project Loved Team`
ppy/osu-wiki pull request #11848
Opened 2024-07-25 18:38 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-07-25 18:40 UTC, agatemosu commented on wiki/People/Project_Loved_Team/es.md
> +![Insignia de 1 año en LVD](https://assets.ppy.sh/profile-badges/loved1y.png "Insignia de 1 año en LVD") ![Insignia de 2 años en LVD](https://assets.ppy.sh/profile-badges/loved2y.png "Insignia de 2 a
añade "el" antes de LVD

2024-07-25 18:43 UTC, UnknownOsu commented on wiki/People/Project_Loved_Team/es.md
> +![Insignia de 1 año en LVD](https://assets.ppy.sh/profile-badges/loved1y.png "Insignia de 1 año en LVD") ![Insignia de 2 años en LVD](https://assets.ppy.sh/profile-badges/loved2y.png "Insignia de 2 a
¿Segura? Quedaría `Insignia de 4 años en el LVD (loved)`

2024-08-13 19:46 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-08-13 19:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Project_Loved_Team/es.md
> +- A partir del 28 de abril de 2023, los miembros del equipo recibirán insignias en función de su permanencia en el equipo.
```suggestion
- A partir del 28 de abril de 2023, los miembros del equipo recibirán insignias según la duración de su permanencia en el equipo.
```

2024-08-21 10:58 UTC, agatemosu commented on wiki/People/Project_Loved_Team/es.md
> +![Insignia de 1 año en LVD](https://assets.ppy.sh/profile-badges/loved1y.png "Insignia de 1 año en LVD") ![Insignia de 2 años en LVD](https://assets.ppy.sh/profile-badges/loved2y.png "Insignia de 2 a
no sé de donde te sacas el ` (loved)`

2024-08-21 11:56 UTC, UnknownOsu commented on wiki/People/Project_Loved_Team/es.md
> +![Insignia de 1 año en LVD](https://assets.ppy.sh/profile-badges/loved1y.png "Insignia de 1 año en LVD") ![Insignia de 2 años en LVD](https://assets.ppy.sh/profile-badges/loved2y.png "Insignia de 2 a
Pues esa es la abreviación [según el artículo](https://osu.ppy.sh/wiki/en/People/User_group), aunque este dice project loved, por eso propuse poner `en el Project Loved Team`

2024-09-17 20:39 UTC, agatemosu approved these changes

2024-09-26 17:55 UTC, TicClick approved these changes

2024-09-26 17:56 UTC, merged