[ES] Add `People/Beatmap Nominators/Rules`
ppy/osu-wiki pull request #11875
Opened 2024-07-31 19:30 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-07 17:53 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-08-07 17:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Beatmap_Nominators/Rules/es.md
> +- **No nomines un beatmap sin haber revisado adecuadamente todas las dificultades de las modalidades que estás nominando.** Una revisión inadecuada incluye simplemente ejecutar una herramienta de mod
```suggestion
- **No nomines un beatmap sin haber revisado adecuadamente todas las dificultades de los modos que estás nominando.** Una revisión inadecuada incluye simplemente ejecutar una herramienta de modding antes de nominar o ni siquiera descargar el beatmap.
```

2024-08-07 17:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Beatmap_Nominators/Rules/es.md
> +- **No nomines a un beatmap si no estás seguro de algo.** En estos casos, solicita ayuda a otros nominadores antes de tomar decisiones apresuradas. Esto incluye modos de juego con los que no estés fa
```suggestion
- **No nomines un beatmap si no estás seguro de algo.** En estos casos, solicita ayuda a otros nominadores antes de tomar decisiones apresuradas. Esto incluye modos de juego con los que no estés familiarizado, problemas sospechosos en zonas grises/no clasificables, problemas de calidad o temporización compleja.
```

2024-08-07 17:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Beatmap_Nominators/Rules/es.md
> +- **Al restablecer las nominaciones de un beatmap, la primera línea del mensaje debe contener una breve razón para el restablecimiento.** No basta con enlazar a las publicaciones, debes intentar resu
```suggestion
- **Al restablecer las nominaciones de un beatmap, la primera línea del mensaje debe contener una breve razón para el restablecimiento.** No basta con enlazar las publicaciones, debes intentar resumir las publicaciones relevantes. En el caso de las descalificaciones, tampoco basta con escribir que se ha solicitado. Debes enlazar cualquier problema relacionado publicado en la discusión del beatmap, a menos que hayan demasiados para publicar.
```

2024-08-07 17:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Beatmap_Nominators/Rules/es.md
> +- **Las descalificaciones deben hacerse principalmente para beatmaps con problemas no clasificables, o si el propietario del beatmap lo solicita.**
```suggestion
- **Las descalificaciones deben hacerse principalmente para los beatmaps con problemas no clasificables, o si el propietario del beatmap lo solicita.**
```

2024-08-07 17:53 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Beatmap_Nominators/Rules/es.md
> +- **No vetes beatmaps de los modos de juego para los que no estás debidamente autorizado.** No puede nominarlos, por lo que bloquear una nominación sin la posibilidad de volver a nominar el beatmap n
```suggestion
- **No vetes beatmaps de los modos de juego para los que no estás debidamente autorizado.** No puedes nominarlos, por lo que bloquear una nominación sin la posibilidad de volver a nominar el beatmap no tiene sentido. Esto no se aplica a los vetos relativos al audio, los fondos u otro contenido que no esté directamente relacionado con el modo de juego del beatmap.
```

2024-08-13 19:37 UTC, TicClick approved these changes

2024-08-13 19:37 UTC, merged