[ES] Add `People/Nomination Assessment Team/NAT meetings`
ppy/osu-wiki pull request #11897
Opened 2024-08-04 00:31 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-07 18:21 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-08-07 18:21 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Nomination_Assessment_Team/NAT_meetings/es.md
> +| Dejar que los BN influyan en las solicitudes y/o en las evaluaciones actuales de los BN | El alcance es muy amplio y debería hacerse primero una propuesta por escrito |
```suggestion
| Dejar que los BN influyan en las solicitudes y/o en las evaluaciones de los BN actuales | El alcance es muy amplio y debería hacerse primero una propuesta por escrito |
```

2024-08-09 10:12 UTC, agatemosu commented on wiki/People/Nomination_Assessment_Team/NAT_meetings/es.md
> +  - Reuniones del equipo de evaluación de nominaciones
Reuniones en minúsculas

2024-08-09 10:12 UTC, agatemosu commented on wiki/People/Nomination_Assessment_Team/NAT_meetings/es.md
> +Las **reuniones del NAT** son discusiones directas organizadas por el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (*NAT*) en el canal `#modding` del [servidor de Discord osu
```suggestion
Las **reuniones del NAT** son discusiones directas organizadas por el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (*NAT*) en el canal `#modding` del [servidor de Discord osu!](/wiki/Community/osu!_Discord_server). Los temas de las reuniones están relacionados con el ecosistema de [mapping](/wiki/Beatmapping) y [modding](/wiki/Modding), e incluyen problemas, posibles soluciones, nuevas ideas e informes de progreso. Si bien la mayoría de los que contribuyen a las discusiones son los miembros del NAT o los [Beatmap Nominators](/wiki/People/Beatmap_Nominators), cualquiera puede participar.
```

2024-08-09 10:12 UTC, agatemosu commented on wiki/People/Nomination_Assessment_Team/NAT_meetings/es.md
> +Las reuniones suelen anunciarse con más de una semana de anticipación en el canal `#modding`.
```suggestion
Las reuniones suelen anunciarse con más de una semana de antelación en el canal `#modding`.
```

2024-08-09 22:33 UTC, agatemosu approved these changes

2024-08-13 19:55 UTC, TicClick approved these changes

2024-08-13 19:55 UTC, merged