[ES] Add `People/Nomination Assessment Team/SEV rating`
ppy/osu-wiki pull request #11898
Opened 2024-08-04 00:32 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-07 18:46 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-08-07 18:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +El SEV es un sistema de puntuación usado por el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (*NAT*) para determinar la relevancia del [restablecimiento de una nominación](/w
```suggestion
El SEV es un sistema de puntuación usado por el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) (*NAT*) para determinar la relevancia del [restablecimiento de una nominación](/wiki/Beatmap_ranking_procedure#restablecimientos-de-nominaciones) para las evaluaciones de las nominaciones de los [Beatmap Nominators](/wiki/People/Beatmap_Nominators) (*BN*), proporcionando transparencia y consistencia. Este sistema de puntuación se divide en dos valores y se muestra como *obviedad/severidad*. Ambos valores varían entre 0 y 2, lo que lo convierte en un sistema fácil de entender y rápido de usar.
```

2024-08-07 18:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +    - Para una temporización simple, alrededor de 6-12 ms
```suggestion
    - Para una temporización simple, alrededor de 6 a 12 ms
```

2024-08-07 18:46 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +    - Un objetos mal ajustado en una parte de un stream, burst o triple (que no se puede simplificar)
```suggestion
    - Un objeto mal ajustado en una parte de un stream, burst o triple (que no se puede simplificar)
```

2024-08-11 14:23 UTC, agatemosu commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +# Puntuación SEV
Yo diría "calificación"

2024-08-11 14:23 UTC, agatemosu commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +# Puntuación SEV
Yo diría "calificación"

2024-08-11 14:25 UTC, agatemosu commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +# Puntuación SEV
o "nota"?

2024-08-11 19:32 UTC, UnknownOsu commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +# Puntuación SEV
Me convence más `calificación`

2024-08-11 19:35 UTC, agatemosu commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +# Puntuación SEV
pues esa

2024-08-11 19:43 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-08-11 19:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +| Valoración | Definición | Explicación |
```suggestion
| Calificación | Definición | Explicación |
```

2024-08-11 19:43 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/People/Nomination_Assessment_Team/SEV_rating/es.md
> +| Valoración | Definición | Explicación |
```suggestion
| Calificación | Definición | Explicación |
```

2024-08-16 19:23 UTC, TicClick approved these changes

2024-08-16 19:23 UTC, merged