Update tournament bans to "indefinite" and enforce VCC on badges/banners
ppy/osu-wiki pull request #11908
Opened 2024-08-05 17:01 UTC by Userlog2

Permanent tournament bans were revised to make them "indefinite" somewhat recently.

I believe it's common sense that badges and official banners have to follow the same rules as any other image on osu!.

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-08-05 17:43 UTC, peppy commented
Not sure where this change is coming from so going to need context.

2024-08-05 21:16 UTC, Walavouchey commented
for the tournament ban wording, context is https://github.com/ppy/osu-wiki/pull/9552 and https://github.com/ppy/osu-wiki/pull/9770. seems like updating here was missed

vcc applies everywhere anyway (as mentioned in the first line of [the article](https://osu.ppy.sh/wiki/en/Rules/Visual_content_considerations)), it just hasn't been relevant in areas like news and probably tournament badges/menu banners

cc @tournament-committee

2024-08-06 07:59 UTC, Userlog2 commented
I was primarily thinking of [this](https://osu.ppy.sh/community/forums/topics/1798871) when updating the wording to "indefinite".

As for the VCC, while it feels a bit obvious, it's also stated in, for example, the RC and fanart contest news posts. I don't think it hurts to mention VCC for tournament banners/badges as well.

2024-08-06 18:38 UTC, MChecaH commented
Brought it up to the other Tournament Committee members. Though this is just my opinion.

In short, the inclusion of the VCC is kind of redundant as *all* visual content in the platform is subject to it. The wording change from permanent to indefinite seems alright. Semantics, but I see how people could be confused otherwise.

2024-08-06 19:50 UTC, MChecaH approved these changes
Changes look good. TComm seems OK with them likewise.

2024-08-06 20:00 UTC, Albionthegreat requested changes

2024-08-06 20:00 UTC, Albionthegreat commented on wiki/Tournaments/Official_support/en.md
> +At the account support team's discretion, offending players may be issued timed or indefinite tournament bans depending on the severity of their behaviour. Repeat offenders may risk incurring an inde
```suggestion
At the account support team's discretion, offending players may be issued timed or indefinite [tournament bans](/wiki/Help_centre/Tournament_bans) depending on the severity of their behaviour. Repeat offenders may risk incurring an indefinite tournament ban or a restriction.
```
Linking to the tournament bans article in help centre would be a worthwhile addition.

2024-08-08 12:25 UTC, merged