[ES] Update `Play style`
ppy/osu-wiki pull request #11944
Opened 2024-08-13 18:40 UTC by Ladwick

Article update –  `Estilo de juego`

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-13 18:43 UTC, agatemosu commented on wiki/Gameplay/Play_style/es.md
> +También conocido como *solo ratón*, los jugadores que emplean este método desplazan el cursor con un ratón mientras pulsan las notas, siguen los sliders y giran los spinners usando solamente los boto
```suggestion
También conocido como *ratón puro*, los jugadores que emplean este método desplazan el cursor con un ratón mientras pulsan las notas, siguen los sliders y giran los spinners usando solamente los botones izquierdo y derecho del ratón.
```

2024-08-13 18:45 UTC, agatemosu commented on wiki/Gameplay/Play_style/es.md
> +Era considerado un estilo de juego *ridículo* por la mayoría de jugadores hasta que en mayo de 2013, el jugador canadiense ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578) empezó a obtener gr
```suggestion
Era considerado un estilo de juego *ridículo* por la mayoría de jugadores hasta que en mayo de 2013, el jugador canadiense ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578) empezó a obtener grandes puntuaciones como [Hatsune Miku - With a Dance Number (val0108)](https://osu.ppy.sh/beatmapsets/29691) y [The Quick Brown Fox - The Big Black (Blue Dragon)](https://osu.ppy.sh/beatmapsets/41823) mientras jugaba con dos ratones.
```

2024-08-14 10:02 UTC, agatemosu commented on wiki/Gameplay/Play_style/es.md
> +Los dance pads son controladores para juegos como la serie [Dance Dance Revolution](https://wikipedia.org/wiki/Dance_Dance_Revolution) (DDR), y la serie [Pump It Up](https://en.wikipedia.org/wiki/Pum
```suggestion
Los dance pads son controladores para juegos como la serie [Dance Dance Revolution](https://es.wikipedia.org/wiki/Dance_Dance_Revolution_(serie)) (DDR), y la serie [Pump It Up](https://es.wikipedia.org/wiki/Pump_It_Up_(serie_de_videojuegos)) (PIU). ([StepMania](https://es.wikipedia.org/wiki/StepMania) es un clon semi-conocido de estos dos juegos, mantenido por la comunidad).
```

2024-08-14 10:06 UTC, agatemosu commented on wiki/Gameplay/Play_style/es.md
> +El control de taiko es el estilo de juego por defecto y el control en la serie de juegos [Taiko no Tatsujin](https://wikipedia.org/wiki/Taiko_no_Tatsujin) ([Taiko Drum Master](https://wikipedia.org/w
```suggestion
El control de taiko es el estilo de juego por defecto y el control en la serie de juegos [Taiko no Tatsujin](https://es.wikipedia.org/wiki/Taiko_no_Tatsujin) ([Taiko Drum Master](https://en.wikipedia.org/wiki/Taiko:_Drum_Master) en los Estados Unidos).
```

2024-08-17 00:36 UTC, UnknownOsu requested changes

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +*Nota: Para más información acerca de teclados mecánicos, véase [guía externa para teclados mecánicos (en inglés)](http://www.daskeyboard.com/blog/mechanical-keyboard-guide/).*
```suggestion
*Nota: Para más información acerca de los teclados mecánicos, véase la [guía externa para teclados mecánicos (en inglés)](http://www.daskeyboard.com/blog/mechanical-keyboard-guide/).*
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +Para jugar con teclado, los jugadores deben presionar las teclas correspondientes a su ubicación en el teclado del juego. Por defecto estas teclas son `D`, `F`, `J`, y `K`. La ventaja de este estilo
```suggestion
Para jugar con teclado, los jugadores deben presionar las teclas correspondientes en el teclado del juego. De forma predeterminada, estas teclas son `D`, `F`, `J`, y `K`. La ventaja de este estilo de juego es que se puede adaptar a básicamente cualquier configuración de teclas.
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +Los controladores de arcade de otros juegos rítmicos tales como DJMAX, O2Jam, Beatmania IIDX, etc. son un estilo de juego hecho para veteranos experimentados en juegos rítmicos de tipo transportador.
```suggestion
Los controladores de arcade de otros juegos de ritmo como DJMAX, O2Jam, Beatmania IIDX, etc., son un estilo de juego hecho para veteranos experimentados en juegos de ritmo de tipo transportador.
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +*Nota: Ya que el uso de 8 teclas requiere la decisión del mapper o el uso de modificadores del juego, la mayoría de jugadores que tienen estos controles de arcade pueden manejar hasta 7 teclas (máxim
```suggestion
*Nota: Ya que el uso de 8 teclas requiere la decisión del mapper o el uso de modificadores del juego, la mayoría de jugadores que tienen estos controles de arcade pueden manejar hasta 7 teclas (como máximo de forma predeterminada) y 1 especial.*
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +### Dance pad
```suggestion
### Pad de baile
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +Los dance pads son controladores para juegos como la serie [Dance Dance Revolution](https://es.wikipedia.org/wiki/Dance_Dance_Revolution_(serie)) (DDR), y la serie [Pump It Up](https://es.wikipedia.o
```suggestion
Los pad de baile son controles para juegos como la serie [Dance Dance Revolution](https://es.wikipedia.org/wiki/Dance_Dance_Revolution_(serie)) (DDR) y la serie [Pump It Up](https://es.wikipedia.org/wiki/Pump_It_Up_(serie_de_videojuegos)) (PIU). ([StepMania](https://es.wikipedia.org/wiki/StepMania) es un clon semiconocido mantenido por la comunidad de estos dos juegos).
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +Para jugar con un dance pad, los jugadores «bailan» en el dance pad para introducir comandos. Los pads DDR tienen 4 paneles: Arriba, Abajo, Izquierda y Derecha. Los pads DDR Solo añaden paneles Super
```suggestion
Para jugar con un pad de baile, los jugadores «bailan» en el pad de baile para introducir comandos. Los pads DDR tienen 4 paneles: Arriba, Abajo, Izquierda y Derecha. Los pads DDR Solo añaden paneles Superior Izquierdo y Superior Derecho. Los pads PIU tienen 5 paneles: Superior Izquierdo, Superior Derecho, Inferior Izquierdo, Inferior Derecho y Centro. También existen pads de 9 paneles con el fin de ser compatibles tanto con PIU como con DDR sin tener que cambiar el pad. Los paneles DDR y PIU normales son usados a menudo en modo doble en sus respectivos juegos, donde un jugador usa 2 pads para una canción. Los juegos DDR Solo eran únicamente de un jugador, por lo que no son dobles.
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +Una gran desventaja de usar un dance pad es que puede ser difícil presionar varias teclas a la vez. Para pulsar 4 notas en un pad DDR, tendrías que usar tus manos y pies, o posicionar tus pies en 2 p
```suggestion
Una gran desventaja de usar un pad de baile es que puede ser difícil presionar varias teclas a la vez. Para pulsar 4 notas en un pad DDR, tendrías que usar tus manos y pies, o posicionar tus pies en 2 paneles a la vez.
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +Otro inconveniente es que los mapas de osu!mania pueden haberse diseñado sin tener en cuenta el movimiento de las animaciones de los juegos de baile, lo que limita la cantidad de canciones que se pue
```suggestion
Otro inconveniente es que los mapas de osu!mania pueden haberse diseñado sin tener en cuenta el movimiento de las animaciones de los juegos de baile, lo que limita la cantidad de canciones que se pueden bailar (cómodamente). Los juegos de baile a menudo están diseñados con el movimiento de un flujo de animaciones de baile. Una de las reglas más importantes de un juego de baile como DDR es poder alternar de pie en cada nota (con algunas excepciones). Ya que algunos mapas de osu!mania no siguen realmente esas reglas, puede resultar realmente incómodo jugar muchos mapas en un pad de baile.
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +- **Set de guitarra/batería**(5/6K): El controlador por defecto de ([Guitar Hero](https://es.wikipedia.org/wiki/Guitar_Hero_(serie))) o ([Drummania](https://es.wikipedia.org/wiki/GITADORA_(serie))).
```suggestion
- **Conjunto de guitarra/batería** (5/6K): El mando predeterminado de ([Guitar Hero](https://es.wikipedia.org/wiki/Guitar_Hero_(serie))) o ([Drummania](https://es.wikipedia.org/wiki/GITADORA_(serie))). Los jugadores usan los botones de la guitarra o la batería. Los jugadores que usen la batería tendrán la desventaja de que solo pueden usar dos notas a la vez sin un pedal especial.
```

2024-08-17 00:36 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +- **Controlador de Para Para**(5K): Este es el controlador por defecto de la serie de juegos [Para Para Paradise](https://es.wikipedia.org/wiki/ParaParaParadise_(serie)). Los jugadores mueven sus bra
```suggestion
- **Mando de Para Para** (5K): Este es el mando predeterminado de la serie de juegos [Para Para Paradise](https://es.wikipedia.org/wiki/ParaParaParadise_(serie)). Los jugadores mueven sus brazos, codos y manos frente a los sensores de proximidad para introducir comandos basados en la posición a través de dichos sensores. La desventaja es la sensibilidad del receptor de entrada y la limitación física del jugador.
```

2024-08-17 13:06 UTC, agatemosu commented
46

2024-08-21 21:51 UTC, UnknownOsu requested changes

2024-08-21 21:51 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +Otro inconveniente es que los mapas de osu!mania pueden haberse diseñado sin tener en cuenta el movimiento de las animaciones de los juegos de baile, lo que limita la cantidad de canciones que se pue
```suggestion
Otro inconveniente es que los mapas de osu!mania pueden haberse diseñado sin tener en cuenta los movimientos que se realizan en los juegos de baile, lo que limita la cantidad de canciones que se pueden bailar (cómodamente). Los juegos de baile a menudo están diseñados con los movimientos de un flujo de animaciones de baile. Una de las reglas más importantes de un juego de baile como DDR es poder alternar de pie en cada nota (con algunas excepciones). Ya que algunos mapas de osu!mania no siguen realmente esas reglas, puede resultar realmente incómodo jugar muchos mapas en un pad de baile.
```

2024-08-21 21:51 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +- **Conjunto de guitarra/batería** (5/6K): El mando predeterminado de ([Guitar Hero](https://es.wikipedia.org/wiki/Guitar_Hero_(serie))) o ([Drummania](https://es.wikipedia.org/wiki/GITADORA_(serie))
```suggestion
- **Conjunto de guitarra/batería** (5/6K): El mando predeterminado de ([Guitar Hero](https://es.wikipedia.org/wiki/Guitar_Hero_(serie))) o ([Drummania](https://es.wikipedia.org/wiki/GITADORA_(serie))). Los jugadores tocan la guitarra o la batería y los platillos para introducir una serie de comandos. Los que tocan la batería están en desventaja en comparación con los que tocan la guitarra, porque solo pueden introducir dos comandos a la vez sin un pedal especial.
```

2024-08-21 21:51 UTC, UnknownOsu commented on wiki/Gameplay/Play_style/es.md
> +# Estilo de juego
```suggestion
# Estilos de juego
```

2024-08-23 20:23 UTC, TicClick approved these changes

2024-08-23 20:25 UTC, merged