[ES] Update `Target Practice (mod)`
ppy/osu-wiki pull request #11943
Opened 2024-08-13 18:35 UTC by Ladwick

**Article update** – `Target Practice (mod)`

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-13 20:33 UTC, UnknownOsu requested changes

2024-08-13 20:33 UTC, UnknownOsu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +El mod **Target Practice** es un [modificador del juego](/wiki/Gameplay/Game_modifier) experimental para [osu!](/wiki/Game_mode/osu!) que elimina todos los [objetos](/wiki/Gameplay/Hit_object) asigna
```suggestion
El mod **Target Practice** es un [modificador del juego](/wiki/Gameplay/Game_modifier) experimental para [osu!](/wiki/Game_mode/osu!) que elimina todos los [objetos](/wiki/Gameplay/Hit_object) y los reemplaza por un conjunto simplificado de «dianas». Se usa principalmente por diversión, pero también puede ser útil para practicar un tempo constante y mejorar la precisión de las pulsaciones.
```

2024-08-13 20:33 UTC, UnknownOsu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +Cuando el mod Target Practice está activado, osu! oculta la barra de salud y el medidor de precisión. El jugador debe intentar golpear el centro de los objetivos que aparecerán gradualmente en el [ca
```suggestion
Cuando el mod Target Practice está activado, osu! oculta la barra de salud y el medidor de precisión. El jugador tiene que pulsar las dianas que van apareciendo gradualmente por el [campo de juego](/wiki/Client/Playfield). Para mantener un ritmo constante, los jugadores pueden seguir el metrónomo que suena de fondo.
```

2024-08-13 20:33 UTC, UnknownOsu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +## Objetivos
```suggestion
## Dianas
```

2024-08-13 20:33 UTC, UnknownOsu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +Un objetivo puede considerarse como un tipo especial de [hit circle](/wiki/Gameplay/Hit_object/Hit_circle) sin un [número de combo](/wiki/Beatmapping/Combo). La puntuación y precisión del golpe depen
```suggestion
Una diana puede considerarse un tipo especial de [círculo](/wiki/Gameplay/Hit_object/Hit_circle) sin un [número de combo](/wiki/Beatmapping/Combo). La puntuación y la precisión del golpe dependen de la posición y la velocidad del golpe: cuanto más preciso y exacto sea, más puntos se obtendrán. La puntuación ideal es de 250 puntos. En el campo de juego, las dianas se colocan en grupos, con un nuevo grupo comenzando cada dos [pulsos completos](/wiki/Music_theory/Beat). La separación dentro de un grupo permanece constante e incrementa ligeramente con cada grupo nuevo.
```

2024-08-13 20:33 UTC, UnknownOsu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
>  ![Jugabilidad de TP](img/TP-gameplay.jpg "Jugabilidad de osu! con el mod Target Practice activado")
```suggestion
![Una jugada con el mod TP](img/TP-gameplay.jpg "Una jugada con el mod Target Practice activado")
```

2024-08-13 20:33 UTC, UnknownOsu commented
No me deja pedir cambios en estas líneas:
`Línea 17`: Cambia `Para una lista completa de mods` a `Para la lista completa de los mods`
`Línea 20`: Creo que queda mejor algo como `Información adicional`
`Línea 29`: Cambia `partida sin clasificar` a `jugada no clasificada`
`Línea 45`: Queda mejor `El mod Target Practice usará los [colores de combo](/wiki/Beatmapping/Combo_colour) del skin.ini de la skin activa.`
`Línea 46`: `Al fallar una jugada con Target Practice, el jugador será dirigido a la pantalla de resultados en lugar de a la pantalla de fallo.`

2024-08-21 21:21 UTC, UnknownOsu requested changes

2024-08-21 21:21 UTC, UnknownOsu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +- El mod Target Practice usará los [colores de combo](/wiki/Beatmapping/Combo_colour) del skin.ini de la skin activa.
```suggestion
- El mod Target Practice usará los [colores de combo](/wiki/Beatmapping/Combo_colour) del [skin.ini](/wiki/Skinning/skin.ini) de la skin activa.
```

2024-08-22 20:38 UTC, UnknownOsu approved these changes

2024-08-23 20:28 UTC, TicClick approved these changes

2024-08-23 20:28 UTC, merged