`Tournaments/Official_Support` new enforcement of content usage permissions
ppy/osu-wiki pull request #11974
Opened 2024-08-15 19:20 UTC by hburn7

- [ ] Tournament Committee review

This change is the result of an internal discussion between the Tournament Committee and @peppy regarding how content usage rules should be enforced in tournaments. We propose the following content usage framework for tournaments:

- Use of DMCA'd beatmaps in any form is prohibited.
- Tournaments may not create new content (e.g. custom beatmaps) or use graveyard/pending/etc. beatmaps using songs that go against artists' wishes based on the `Rules/Content_usage_permissions#artist-permissions` page.
- Ranked, Approved, and Loved beatmaps are grandfathered in and will bypass the content usage permissions (DMCA still prohibited).

Also tacks on a missing `via [tournaments@ppy.sh](mailto:tournaments@ppy.sh)` in another portion of the page.

2024-08-15 19:30 UTC, Walavouchey requested changes

2024-08-15 19:30 UTC, Walavouchey commented on wiki/Tournaments/Official_support/en.md
> +  - The creation or reuse of any beatmaps that are not **Ranked, Approved, or Loved** and violate the [content usage permissions](/wiki/Rules/Content_usage_permissions#artist-permissions) page is str
violating a page doesn't sound right
reordering to make it easier to understand

```suggestion
  - The creation or reuse of any beatmaps that violate [content usage permission rules](/wiki/Rules/Content_usage_permissions#artist-permissions) is strictly prohibited, except if they are **Ranked, Approved, or Loved**.
```

2024-08-15 23:12 UTC, Walavouchey submitted a review, later dismissed

2024-08-16 00:01 UTC, cl8n submitted a review, later dismissed

2024-08-16 11:09 UTC, Albionthegreat approved these changes
The changes have been discussed and approved by the tournament committee.

2024-08-17 04:19 UTC, cl8n approved these changes

2024-08-17 04:20 UTC, merged