[ES] Add `Reporting_bad_behaviour/Handling_foul_play`
ppy/osu-wiki pull request #11987
Opened 2024-08-17 16:20 UTC by JuanM4T

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-17 18:30 UTC, UnknownOsu requested changes

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +El equipo de soporte no te proporcionará «pruebas» sobre restricciones, pero todas se hacen con sospechas con buena base. Los usuarios normales son extremadamente poco suceptibles de ser marcados por
```suggestion
El equipo de soporte no te proporcionará ninguna «prueba» sobre las restricciones, pero todas se realizan con sospechas bien fundamentadas. Es muy poco probable que los usuarios normales sean blanco de este tipo de acciones.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Lo siento, pero si has sido restringido el equipo de soporte ya está seguro de que estás haciendo trampas. Un vídeo no ayudará, pues estos también pueden ser manipulados.
```suggestion
Lo sentimos, pero si has sido restringido, el equipo de soporte ya está seguro de que estás haciendo trampa. Un vídeo no ayudará, ya que estos también pueden ser manipulados.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## He encontrado a alguien que definitivamente está haciendo trampas. ¡Puedo darme cuenta por su repetición/puntuación! ¿Qué debería hacer?
```suggestion
## He encontrado a alguien que definitivamente está haciendo trampa. ¡Puedo darme cuenta por su repetición/puntuación! ¿Qué debería hacer?
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Mantén la calma y **no discutas sus puntuaciones en chats públicos**. No le des atención no deseada o le pidas a otros que hagan de espectador. Deberías reportar al usuario y no mencionarlos en ningú
```suggestion
Mantén la calma y **no hables de sus puntuaciones en chats públicos**. No le des atención no deseada o le pidas a otros que hagan de espectador. Deberías reportar al usuario y no mencionarlos en ningún lado. Hay tres formas de hacerlo.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +**Esta es la mejor forma de reportar tus sospechas de juego sucio, pues provee mayor información a los miembros del equipo de soporte.**
```suggestion
**Esta es la mejor forma de reportar tus sospechas de juego sucio, ya que proporciona la mayor cantidad de información a los miembros del equipo de soporte.**
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +En el perfil del usuario, un botón de `Reportar` aparecerá cuando cliques en los tres puntos al lado del botón de `Mensaje`. Escribe cualquier información que pueda probar que el usuario está haciend
```suggestion
En el perfil del usuario, al hacer clic en los tres puntos que hay junto al botón de `Mensaje`, aparecerá un botón de `Reportar`. Escribe cualquier tipo de información que pueda demostrar que el usuario está realizando una mala acción.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +### Página de beatmap
```suggestion
### Páginas de los beatmaps
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +En las páginas de los beatmaps, puedes reportar a un usuario en las clasificaciones haciendo click en el botón de `Report` a la derecha de su puntuación.
```suggestion
En las páginas de los beatmaps, puedes reportar a un usuario en las clasificaciones haciendo clic en el botón de `Reportar` a la derecha de su puntuación.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Esta forma de reportar **no se recomienda** porque los reportes dentro del juego son, normalmente, relacionados al chat.
```suggestion
Esta forma de reportar **no es recomendable**, ya que los reportes dentro del juego están relacionados casi siempre con el chat.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Formato: !report <nombre de usuario> <razon>
```suggestion
Formato: !report <nombre de usuario> <razón>
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Tu ayuda para reportar juego sucio es muy apreciada. Revisamos todos los reportes que recibimos, ¡pero eso no significa que todos ellos nos lleven a tomar acción! También puedes enviar un correo dire
```suggestion
Apreciamos mucho tu ayuda para reportar el juego sucio. Revisamos todos los reportes que recibimos, ¡pero eso no significa que todos nos lleven a tomar medidas! También puedes enviar un correo electrónico directamente a [osu@ppy.sh](mailto:osu@ppy.sh) para una respuesta relativamente rápida.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿Se considera el uso de hardware especializado hacer trampas?
```suggestion
## ¿El uso de hardware especializado se considera como hacer trampa?
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Periféricos como tabletas gráficas o pantallas táctiles están permitidos. Cualquier cosa que disminuya la habilidad necesaria para jugar (por ejemplo usar fidget spinners en una tableta gráfica) o ca
```suggestion
Periféricos como tabletas gráficas o pantallas táctiles están permitidos. Cualquier cosa que disminuya la habilidad necesaria para jugar (por ejemplo, usar fidget spinners en una tableta gráfica) o cancela/anula el efecto de los modificadores del juego no lo están. Esto significa que el uso de varios ordenadores, divisores de entrada, o cualquier otra cosa de ese estilo es considerado un no rotundo.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +El equipo de soporte espera que los usuarios den un historal entero de sus acciones y den razones de porque no volverán a ofender en el futuro.
```suggestion
El equipo de soporte espera que los usuarios presenten un historial completo de sus acciones y den razones por las que no volverán a infringir las reglas en el futuro.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿Qué puedo hacer si he roto las reglas?
```suggestion
## ¿Qué puedo hacer si he infringido las reglas?
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Si has roto las reglas y quieres confesar, contacta con [accounts@ppy.sh](mailto:accounts@ppy.sh) y explica lo que has hecho. La honestidad es altamente apreciada y esto probablemente no acabe en un
```suggestion
Si has infringido las reglas y quieres confesar, ponte en contacto con [accounts@ppy.sh](mailto:accounts@ppy.sh) y explica lo que has hecho. La honestidad es muy apreciada y es probable que esto no resulte en un castigo permanente.
```

2024-08-17 18:30 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Cuidadosamente lee y sigue las [reglas](/wiki/Rules).
```suggestion
Lee atentamente y sigue las [reglas](/wiki/Rules).
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Mal comportamiento continuo a pesar de cuantas faltas acumulen.
```suggestion
- Mala conducta continua dependiendo de cuantas faltas se hayan acumulado.
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Multi-cuentas.
```suggestion
- Multicuentas.
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampas.
```suggestion
- Pirateo o uso de trampas (consulta a continuación).
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿Qué es considerado multi-cuentas?
```suggestion
## ¿Qué se considera multicuenta?
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿Qué es considerado hacer trampas?
```suggestion
## ¿Qué se considera uso de trampas?
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Las [reglas](/wiki/Rules) exponen que cualquier forma de manipulación del cliente, tal y como puede ser el hacking de puntuaciones, secuencias de full-combo habilitadas por macros, auto-apuntado y cu
```suggestion
Las [reglas](/wiki/Rules) exponen que cualquier tipo de modificación del cliente, tal y como puede ser la manipulación de puntuaciones, secuencias de combo completo habilitadas por macros, apuntado automático y cualquier otra cosa que juegue por el jugador se considera hacer trampas.
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Prueba que yo/él/ella estaba haciendo trampas! ¡Cuéntanos cómo lo sabes!
```suggestion
## ¡Prueba que no usé/usó trampas! ¡Cuéntanos cómo lo sabes!
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Ejemplo: !report este_usuario suspected cheating
```suggestion
Ejemplo: !report this_user suspected cheating
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Periféricos como tabletas gráficas o pantallas táctiles están permitidos. Cualquier cosa que disminuya la habilidad necesaria para jugar (por ejemplo usar fidget spinners en una tableta gráfica) o ca
```suggestion
Periféricos como tabletas gráficas o pantallas táctiles están permitidos. Cualquier cosa que disminuya la habilidad necesaria para jugar (por ejemplo, usar fidget spinners en una tableta gráfica) o cancela/anula el efecto de los modificadores de juego no lo están. Esto significa que usar multiples PC, divisores de entrada, o cualquier otra cosa de ese estilo se considera un no-no.
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +El equipo de soporte espera que los usuarios den un historal entero de sus acciones y den razones de porque no volverán a ofender en el futuro.
```suggestion
El equipo de soporte espera que los usuarios den un historal entero de sus acciones y den razones de porque no volverán a hacerlo en el futuro.
```

2024-08-17 18:35 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Cuidadosamente lee y sigue las [reglas](/wiki/Rules).
```suggestion
Lee y sigue las [reglas](/wiki/Rules) cuidadosamente.
```

2024-08-17 18:36 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +# Gestionando el juego sucio
shatapai wars reveisng to

2024-08-17 18:51 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampas.
en el inglés se distingue entre cheating y hacking (aunque no sé muy bien a que se refiere con hacking)

2024-08-17 18:51 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampas.
hacking != pirateo

2024-08-17 18:51 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Ejemplo: !report este_usuario suspected cheating
este_usuario se traduce para que se entienda porque es un ejemplo de un usuario que no existe y alguien que sepa español lo entenderá mejor, mientras que la segunda parte se deja igual porque los reports de esta índole son mejor en inglés

2024-08-17 19:20 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampas.
Pues podría ser algo como cambiar los archivos del juego. Por ejemplo, ponerle una imagen a la osu! cookie te podría restringir por modificar los archivos del juego y no estarías usando cheats en sí.

Igual y puedes poner `Modificar los archivos del juego o hacer trampa` o algo parecido

2024-08-17 19:24 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampas.
En cada traducción cada uno hace lo que le parece así que por ser fiel al original voy a dejar hacking
```suggestion
- Hacking o hacer trampa.
```

2024-08-17 21:10 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampa.
```suggestion
- Jaqueo o hacer trampa.
```

2024-08-17 21:10 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Las [reglas](/wiki/Rules) indican que cualquier forma de manipulación del cliente, como el manejo indebido de las puntuaciones, secuencias de full combo habilitadas por macros, autoapuntado y cualqui
no entiendo esta frase, que pone ahí?

2024-08-17 21:10 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
que raro

2024-08-17 21:10 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿El uso de hardware especializado se considera como hacer trampa?
que es hardware

2024-08-17 21:12 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampa.
no se usa "jaqueo"

2024-08-17 21:13 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿El uso de hardware especializado se considera como hacer trampa?
se explica dentro de la sección (tablets, teclados, pantallas...)

2024-08-17 21:19 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Las [reglas](/wiki/Rules) indican que cualquier forma de manipulación del cliente, como el manejo indebido de las puntuaciones, secuencias de full combo habilitadas por macros, autoapuntado y cualqui
> The [rules](https://github.com/ppy/osu-wiki/blob/bad-behaviour/wiki/Rules) state that any form of manipulation of the client such as score hacking, macro-enabled full-combo sequences, auto-aim and anything else that plays the game for the player is considered cheating.
lo que peor se entiende es lo que respecta a score hacking, acepto sugerencias

2024-08-17 21:20 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
se entiende bien esto imo

2024-08-17 21:29 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
lo que puse yo era mejor

2024-08-17 21:30 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿El uso de hardware especializado se considera como hacer trampa?
```suggestion
## ¿El uso de periféricos especializados se considera como hacer trampa?
```

2024-08-17 21:32 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampa.
```suggestion
- Tener conocimientos de informática o hacer trampa.
```

2024-08-17 21:50 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampa.
sigue sin convencerme, estaría bien también saber a que se refiere el artículo con "hacking" primero

2024-08-17 21:53 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
me gustaría desviarme lo menos posible del original, usan I/They con el they como neutro de otra persona, puse originalmente yo/él/ella como transliteración, me gustaría dejarlo al menos con pronombres si es posible

2024-08-17 22:03 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +- Hacking o hacer trampa.
eso tambien esta bien

2024-08-17 22:04 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Las [reglas](/wiki/Rules) indican que cualquier forma de manipulación del cliente, como el manejo indebido de las puntuaciones, secuencias de full combo habilitadas por macros, autoapuntado y cualqui
```suggestion
Las [reglas](/wiki/Rules) indican que cualquier forma de manipulación del cliente, como el manejo indebido de las puntuaciones, secuencias de combo completo habilitadas por macros, autoapuntado y cualquier otra cosa que juegue por el jugador, se considera hacer trampa.
```

2024-08-18 10:29 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
```suggestion
## ¡Demuéstrame que hice/hicieron trampas! ¡Quisiera saber cómo lo sabes!
```

2024-08-18 17:46 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
```suggestion
## ¡Demuéstrame que yo/otro estaba haciendo trampa! ¡Quisiera saber cómo lo sabes!
```
opinión

2024-08-18 19:08 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
parece forzado

2024-08-18 19:29 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
me acabo de dar cuenta que como no somos sucios ingleses podemos hacer esto
```suggestion
## ¡Demuéstrame que estaba haciendo trampa! ¡Quisiera saber cómo lo sabes!
```

2024-08-19 08:52 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que yo/otros usuarios estaban haciendo trampa! ¡Quisiera saber cómo lo saben!
ahi si

2024-08-19 21:54 UTC, UnknownOsu requested changes

2024-08-19 21:54 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrame que estaba haciendo trampa! ¡Quisiera saber cómo lo sabes!
```suggestion
## ¡Demuéstrame que estaba haciendo trampa! ¡Quisiera saber cómo lo saben!
```

2024-08-20 12:37 UTC, UnknownOsu requested changes

2024-08-20 12:37 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +[^restriction-length]: El tiempo que has de esperar antes de apelar depende de la razón por la que estás restringido. Si no estás seguro de cuánto dura tu restricción, envia un correo a [accounts@ppy
```suggestion
[^restriction-length]: El tiempo que tendrás que esperar antes de volver a apelar dependerá del motivo de la restricción. Si no estás seguro de cuánto dura tu restricción, envia un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh). Para más información, consulta [Restricciones de cuenta](/wiki/Help_centre/Account_restrictions).
```

2024-08-20 12:37 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +The length of time you will have to wait before appealing depends on the reason for the restriction. If you're not sure how long your restriction lasts, email [accounts@ppy.sh](mailto:accounts@ppy.sh
```suggestion

```

2024-08-20 12:40 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +[^restriction-length]: El tiempo que has de esperar antes de apelar depende de la razón por la que estás restringido. Si no estás seguro de cuánto dura tu restricción, envia un correo a [accounts@ppy
no es volver a apelar

2024-08-20 12:43 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +[^restriction-length]: El tiempo que has de esperar antes de apelar depende de la razón por la que estás restringido. Si no estás seguro de cuánto dura tu restricción, envia un correo a [accounts@ppy
Ok, ya lo cambié

2024-09-01 19:04 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +Espera al menos tres meses después de la última restricción aplicada antes de apelar[^restriction-length]. Envía tus correos a [accounts@ppy.sh](mailto:accounts@ppy.sh) y usa el asunto de `Restrictio
```suggestion
Espera al menos tres meses después de la última restricción aplicada antes de apelar[^restriction-length]. Envía tus correos a [accounts@ppy.sh](mailto:accounts@ppy.sh) y usa el asunto `Restriction Appeal: <nombre de usuario>`
```

2024-09-01 19:05 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demostradme que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tenéis!
```suggestion
## ¡Demuéstrenme que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tienen!
```

2024-09-02 09:00 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demostradme que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tenéis!
no

2024-09-02 09:01 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrenme que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tienen!
```suggestion
## ¡Demostradme que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tenéis!
```

2024-09-03 19:08 UTC, UnknownOsu requested changes

2024-09-03 19:08 UTC, UnknownOsu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +[^restriction-length]: El tiempo que tendrás que esperar antes de apelar dependerá del motivo de la restricción. Si no estás seguro de cuánto dura tu restricción, envia un correo a [accounts@ppy.sh](
```suggestion
[^restriction-length]: El tiempo que tendrás que esperar antes de apelar dependerá del motivo de la restricción. Si no estás seguro de cuánto dura tu restricción, envía un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh). Para más información, consulta [Restricciones de cuenta](/wiki/Help_centre/Account_restrictions).
```

2024-09-03 19:15 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrenme que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tienen!
```suggestion
## ¡Demuéstrame que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tienes!
```
o
```suggestion
## ¡Demuéstrame que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tienen!
```
no usan la segunda persona del plural en latam

2024-09-03 21:58 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¡Demuéstrenme que estaba haciendo trampa! ¡Me gustaría saber qué pruebas tienen!
pes pon la tuya (primera) que mas da

2024-09-04 08:05 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿Qué puedo hacer si he roto las reglas?
por qué lo revertiste? @JuanM4T

2024-09-04 08:15 UTC, agatemosu commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿Qué puedo hacer si he roto las reglas?
lo arreglas

2024-09-04 09:00 UTC, JuanM4T commented on wiki/Reporting_bad_behaviour/Handling_foul_play/es.md
> +## ¿Qué puedo hacer si he roto las reglas?
pero si lo rompe en otro sitio

2024-09-04 12:22 UTC, agatemosu approved these changes

2024-09-09 20:34 UTC, TicClick approved these changes

2024-09-09 20:38 UTC, merged