[ES] Add `Staff logs` from `2007` to `2023`
ppy/osu-wiki pull request #11981
Opened 2024-08-16 05:13 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

In case there is a problem with so many articles in a single PR, I can open a PR for each article.

I did it this way because practically everything is copy and paste

2024-08-16 11:05 UTC, agatemosu commented
SKIP_OUTDATED_CHECK?

2024-08-21 10:53 UTC, agatemosu approved these changes

2024-08-21 10:55 UTC, agatemosu requested changes
Move the 2013, 2014, 2021 and 2022 to another PR

2024-08-23 20:04 UTC, TicClick commented
I'd say it's a minor change -- as long as it's more or less isolated without seeping into other areas, it can be tolerated

2024-08-23 20:11 UTC, TicClick approved these changes

2024-08-23 20:11 UTC, merged