Add ``osu! Philippines Nationals 2024 - osu!mania 4K/7K`` tournament article
ppy/osu-wiki pull request #11985
Opened 2024-08-17 05:34 UTC by SurfChu85

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-08-17 12:02 UTC, iSlodinxOsu requested changes

2024-08-17 12:02 UTC, iSlodinxOsu commented on wiki/Tournaments/oPHN/2024_mania/en.md
> +The osu! Philippines Nationals 2024 - osu!mania 4K/7K tournament is ran by various community members.
```suggestion
The osu! Philippines Nationals 2024 - osu!mania 4K/7K tournament was run by various community members.
```

2024-08-19 21:56 UTC, TicClick approved these changes
surprisingly for me, "Philippine ..." also seems to be a valid phrase

2024-08-19 21:58 UTC, merged

2024-08-22 00:14 UTC, epic-githubber-2-em2 commented
Heyo, this is "epic man 2" -- sorry if this seems abrupt but I think there is a small misconception in the wiki page here.

![image](https://github.com/user-attachments/assets/327a2217-eb98-4746-a36a-1cb59e484a85)

On here (This is the "Qualifiers" for the 4K side of this tournament) it says that my map (The Contortionist - Reimagined) was used on 1.05x rate, although it was only the base rate that was used and the ID that is used on the map link would originally redirect to the base rate diff, although because I added rates a week after the qualifiers were done the ID swapped to being on the 1.05x rate specifically instead of the original difficulty that was used. Would it be possible to make a small correction here so the information is a bit more accurate and to avoid confusion?