[ES] Update `Skinning/Sounds` and `Guides/Custom sample overrides`
ppy/osu-wiki pull request #11982
Opened 2024-08-16 19:05 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-17 21:13 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-08-17 21:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Sounds/es.md
> +### Sonidos al presionar teclas
```suggestion
### Sonidos al presionar las teclas
```

2024-08-17 21:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Skinning/Sounds/es.md
>  - Este sonido puede modularse de unos 500 hz a 80 000 hz.
```suggestion
- Este sonido puede modularse de unos 500 hz a 80 000 hz.
```

2024-08-20 10:25 UTC, TicClick approved these changes

2024-08-20 10:26 UTC, merged