Add `4 Digit Player Tournament wiki` and `2024 Tournament Article`
ppy/osu-wiki pull request #11992
Opened 2024-08-18 08:45 UTC by Ekseff

**First time creating this, not sure if i did it correctly..**

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-18 08:51 UTC, iSlodinxOsu requested changes

2024-08-18 08:51 UTC, iSlodinxOsu commented on wiki/Tournaments/4DPT/2024/en.md
> +- [Discord Server](https://discord.gg/PTB8WuVTfB)
```suggestion
- [Discord server](https://discord.gg/PTB8WuVTfB)
```

2024-08-18 08:51 UTC, iSlodinxOsu commented on wiki/Tournaments/4DPT/2024/en.md
> +- [Challonge Bracket](https://challonge.com/4dpt6)
```suggestion
- [Challonge bracket](https://challonge.com/4dpt6)
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +| Screening Phase | 2024-02-16/2024-02-22 |
```suggestion
| Screening phase | 2024-02-16/2024-02-22 |
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +| Quarter Finals | 2024-03-22/2024-03-24 |
```suggestion
| Quarterfinals | 2024-03-22/2024-03-24 |
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +| Semi Finals | 2024-03-29/2024-03-31 |
```suggestion
| Semifinals | 2024-03-29/2024-03-31 |
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +The full final standings for the Qualifier stage can be found on the following [website](https://wybin.xyz/tournaments/4dpt6/stats#qualifiers).
```suggestion
The full final standings for the Qualifier stage can be found on [this website](https://wybin.xyz/tournaments/4dpt6/stats#qualifiers).
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +  1. [general_r6 - Cupid x Angle Grinder  (e wong) \[cupid if it was a good song\]](https://osu.ppy.sh/beatmapsets/2022815#fruits/4213160) (Sightread)[^sightreading]
```suggestion
  1. *(various maps)* (Sightread)[^sightreading]
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +2. The player must be between the rank range of #1000 to #5000 until the end of registration. After the registration phase has ended, players are allowed to rank up out of the rank range.
```suggestion
2. Each player must be in between the rank range of #1,000 to #5,000 at the end of the registration period. After the registration has ended, players are allowed to rank up or down out of the rank range.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +3. The player registering should not have any related 4 digit player touranemnt badges from past iterations. This rule is in place to ensure fairness and provide equal opportunities.
```suggestion
3. Each player must not have any related 4-digit player tournament badges from past iterations. This rule is in place to ensure fairness and provide equal opportunities.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +4. Staff are allowed to play with the exception of Admins, Mappoolers and Custom Mappers. Eliminated players are eligible to be enlisted as Playtesters, Replay Creators and Referees as per the [Offic
```suggestion
4. Staff members are allowed to play with the exception of Admins, Mappoolers and Custom Mappers. Eliminated players are eligible to be enlisted as Playtesters, Replay Creators and Referees as per the [Official Tourament Support](https://osu.ppy.sh/wiki/en/Tournaments/Official_support) page.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +### Mappool Format
```suggestion
### Mappool format
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +2. Mystery Mod will not be from another gamemode.
```suggestion
2. The Mystery Mod pool will not feature maps that are [converted](/wiki/Beatmap/Converts) from another game mode.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +3. The mappool format for each of the following rounds are as follows:
```suggestion
3. The mappool format and win condition for each of the following rounds are as follows:
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +- Quarter Finals
```suggestion
- Quarterfinals
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +- Semi Finals
```suggestion
- Semifinals
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +1. Players will have to sign up for a Qualifier lobby that has been prepared by the tournament hosts listed on the [website](https://wybin.xyz/tournaments/4dpt6/schedule#qualifiers).
```suggestion
1. Each player will have to sign up for a Qualifier lobby that has been prepared by the tournament management as listed on the [tournament's website](https://wybin.xyz/tournaments/4dpt6/schedule#qualifiers).
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +5. Players are to join their selected qualifiers lobby on time. In the event you are late to the lobby, you are allowed to reschedule to a later lobby.
```suggestion
5. Players are expected to join their selected qualifiers lobby on time. In the event that a player is late to the lobby, the said player is allowed to reschedule to a later lobby.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +5. Players are to join their selected qualifiers lobby on time. In the event you are late to the lobby, you are allowed to reschedule to a later lobby.
(the word "you" should be avoided as much as possible while dictating rules)

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +7. Between each map, all players have **120 seconds** to ready up.
```suggestion
7. Between each map, players have **120 seconds** to ready up.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +3. Maximum Reschedule time is **6 hours** before your match. For an emergency reschedule or late schedule, it may not be accepted depending on host and referee availability and discretion.
```suggestion
3. Reschedules have to be agreed on at most **6 hours** before the match. Emergency and late reschedules may or may not be accepted depending on the hosts' and the referee's availability and discretion.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +[^tester] Enlisted as map tester after being knocked out in Semifinals.
```suggestion
[^tester] This player was brought in as a map tester after being knocked out in the bracket stage.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +[^sightreading] Placeholder map for sightread during the stream and showcase.
```suggestion
[^sightreading] Maps for this slot were revealed upon being picked at the match.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +1. The hosts will schedule a time for the match. It will take place on a Friday/Weekend unless a special request is to be played Midweek.
```suggestion
1. The hosts will pre-determine a scheduled time for the matches, which will take place on a Friday or a weekend day unless a special request is placed in advance for a match to be played mid-week.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +2. In the event that you are unable to make it for your scheduled time, contact your opponent andd apply for a reschedule at the `#reschedule` channel in the tournament's Discord server. Screenshot i
```suggestion
2. In the event that a player are unable to make it for your scheduled time, said player is advised to contact their opponent and apply for a reschedule at the `#reschedule` channel in the tournament's Discord server. Screenshot is required for valid reschedule proof.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +4. For the duration of the tournament, players must be in the discord server at all times.
```suggestion
4. For the duration of the tournament, players are required to be present in the Discord server at all times.
```

2024-08-29 17:51 UTC, Nivalyx commented on wiki/Tournaments/4DPT/2024/en.md
> +3. Nofail will be enforced during matches and on every map.
```suggestion
3. NoFail will be enforced during matches and on every map.
```

2024-08-29 17:53 UTC, Nivalyx commented
i think you should add a footnote for every gimmick featured in the Mystery mod pool tbh, as a good amount of them are not really... self-explanatory

2024-11-05 15:47 UTC, Walavouchey requested changes

2024-11-05 15:47 UTC, Walavouchey commented on wiki/Tournaments/4DPT/2024/en.md
> +   - For example, malfunctioning peripherals, disconnects and network outages.
complete sentence

```suggestion
   - Valid reasons include malfunctioning peripherals, disconnects, network outages, etc.
```

2024-11-05 15:47 UTC, Walavouchey commented on wiki/Tournaments/4DPT/2024/en.md
> +4. Players will be given **120 seconds** for every action (picking & banning). Failure to do so will lead to a random map to be picked by the referee in charge of the match.
```suggestion
4. Players will be given **120 seconds** for every action (picking and banning). Failure to do so will lead to a random map to be picked by the referee in charge of the match.
```

2024-11-05 15:47 UTC, Walavouchey commented on wiki/Tournaments/4DPT/2024/en.md
> +   - After a player reaches 3 points (in the Semi Finals, Finals, and Grand Finals), the opposing player is then given a chance to **ban another beatmap** from the mappool that has neither been picke
```suggestion
   - After a player reaches 3 points (in the Semifinals, Finals, and Grand Finals), the opposing player is then given a chance to **ban another beatmap** from the mappool that has neither been picked nor banned up until that point as a comeback mechanic.
```

2024-11-05 15:47 UTC, Walavouchey commented on wiki/Tournaments/4DPT/2024/en.md
> +### Match Procedures
headings should be in sentence case

```suggestion
### Match procedures
```

2024-11-05 15:47 UTC, Walavouchey commented on wiki/Tournaments/4DPT/2024/en.md
> +### Scheduling Rules
```suggestion
### Scheduling rules
```

2024-11-13 12:38 UTC, Walavouchey approved these changes

2024-11-13 12:40 UTC, merged