[ES] Update `Help_centre/Account_restrictions`
ppy/osu-wiki pull request #12006
Opened 2024-08-20 10:39 UTC by JuanM4T

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-20 21:49 UTC, UnknownOsu requested changes

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **¡Sigue disfrutando del juego!** Mientras tu cuenta está restringida y en tiempo de espera, eres más que bienvenido a seguir jugando el juego (¡siempre y cuando juegues en tu cuenta original!). La
```suggestion
- **¡Sigue disfrutando del juego!** Mientras tu cuenta esté restringida y en tiempo de espera, eres más que bienvenido a seguir jugando al juego (¡siempre y cuando juegues en tu cuenta original!). Las puntuaciones que consigas mientras tu cuenta esté restringida se enviarán y, a menos que tu cuenta se revierta, se mantendrán una vez que tu cuenta deje de estar restringida.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  Cuando una cuenta es restringida, es incapaz de interactuar con la comunidad hasta que la restricción sea levantada. Los jugadores restringidos pueden seguir jugando el juego, descargar beatmaps y su
```suggestion
Cuando una cuenta es restringida, es incapaz de interactuar con la comunidad hasta que la restricción sea levantada. Los jugadores restringidos pueden seguir jugando al juego, descargar beatmaps y subir puntuaciones, pero su perfil será invisible para los demás.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - **Mantener una buena conducta.** Entendemos que ser restringido puede ser frustrante, pero tómalo como una oportunidad de tomar un descanso, lejos de la comunidad. Intenta evitar interactuar con la
```suggestion
- **Mantener una buena conducta.** Entendemos que estar restringido puede ser frustrante, pero piensa que es una oportunidad para tomarte un descanso, lejos de la comunidad. Intenta evitar interactuar con la comunidad durante al menos unos días (ya sea a través de Discord, las redes sociales u otras formas de contacto) para calmarte y reflexionar sobre las acciones que pueden haber provocado la restricción de tu cuenta.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +**Hacer trampa o compartir cuenta durante un torneo oficial o torneo con insignia llevará al veto indefinido del usuario en futuros torneos.** Este veto podrá ser apelado pasados dos años, pero solo
```suggestion
**Hacer trampa o compartir una cuenta durante un torneo oficial o torneo con insignia llevará al veto indefinido del usuario en futuros torneos.** Este veto podrá ser apelado después de dos años, pero solo se le otorgará el perdón de esta condición si ha demostrado un esfuerzo significante para mejorar los torneos de la comunidad.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **Contacta a nuestro [equipo de soporte de cuentas](/wiki/People/Account_support_team).** Si tu cuenta sigue restringida después de ese tiempo, por favor, envía un correo a [accounts@ppy.sh](mailto
```suggestion
- **Contacta a nuestro [equipo de soporte de cuentas](/wiki/People/Account_support_team).** Si tu cuenta sigue restringida después de ese tiempo, por favor, envía un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh) **desde el correo electrónico enlazado a tu cuenta** para más detalles de tu restricción. Asegúrate de incluir tu nombre de usuario, junto con cualquier detalle que puedas proporcionar sobre por qué crees que has sido restringido. Cuanto más nos cuentes, más fácil nos resultará resolver el problema.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  Si tu cuenta ha sido restringida por romper las [reglas](/wiki/Rules), debes esperar un mínimo de **tres meses** antes de poder enviar una apelación. Nosotros nos referimos a este período de tiempo c
```suggestion
Si tu cuenta ha sido restringida por romper las [reglas](/wiki/Rules), debes esperar un mínimo de **tres meses** antes de poder enviar una apelación. Nosotros nos referimos a este periodo de tiempo como *tiempo de espera*, y si has hecho trampa, son seis meses.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **No es tu primera cuenta.** Las multicuentas están en contra de las reglas. Cualquier cuenta que no sea la cuenta original de un jugador será permanentemente restringida, pero su cuenta original e
```suggestion
- **No es tu primera cuenta.** Las multicuentas están en contra de las reglas. Cualquier cuenta que no sea la cuenta original de un jugador será permanentemente restringida, pero su cuenta original en la mayoría de los casos seguirá abierta y el jugador es alentado a seguir jugando en ella. Si el uso de multicuentas es severo o abusivo, se aplicará un silencio a la cuenta original como advertencia para que deje de crear nuevas cuentas, y se restringirá la cuenta principal si el uso de multicuentas continúa. Si tu cuenta es restringida y sabes que tienes otras cuentas, por favor no continúes accediendo a las cuentas restringidas que tienes y continúa jugando en tu cuenta original. Si tienes problemas para acceder o para verificarla, envíanos un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh) para que podamos ayudarte a recuperar el acceso a ella.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **Has permitido que alguien juegue en tu cuenta.** Compartir cuentas también va en contra de las reglas. Si permites que alguien más juegue en tu cuenta, será restringida, y al otro jugador probabl
```suggestion
- **Has permitido que alguien juegue en tu cuenta.** Compartir cuentas también va contra de las reglas. Si permites que alguien use tu cuenta, será restringida, y el jugador que la usó probablemente recibirá un silencio o una restricción en su cuenta. Si esto ha sucedido accidentalmente, háznoslo saber lo antes posible enviando un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh).
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - **Por qué rompiste las reglas.** Una explicación sobre lo que te llevó a decidir crear más cuentas, prestar tu cuenta, hacer trampa, etc. nos ayudará (y a ti) a determinar si está en riesgo de infr
```suggestion
- **Por qué rompiste las reglas.** Una explicación sobre lo que te llevó a decidir crear más cuentas, prestar tu cuenta, hacer trampa, etc. nos ayudará (y a ti) a determinar si estás o no en riesgo de infringir las reglas otra vez. Si continuaste infringiendo las reglas mientras estabas restringido, también nos interesa saber por qué.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - **Cómo conseguiste los medios para hacerlo.** Esto aplica principalmente al hacer trampas, queremos saber dónde conseguiste la herramienta que usaste, cómo la encontraste, y si sigue o no presente
```suggestion
- **Cómo conseguiste los medios para hacerlo.** Esto aplica principalmente al hacer trampa, queremos saber dónde conseguiste la herramienta que usaste, cómo la encontraste, y si sigue o no presente en tu ordenador.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - **Por qué deberíamos permitirte regresar.** La mayor parte del tiempo, esto se enlaza con el segundo punto. ¡Solo queremos asegurarnos de que no romperás las reglas de nuevo! Por favor, entiende qu
```suggestion
- **Por qué deberíamos permitirte regresar.** La mayor parte del tiempo, esto se enlaza con el segundo punto. ¡Solo queremos asegurarnos de que no romperás las reglas de nuevo! Por favor, entiende que entre más infracciones haya en el historial de tu cuenta, más esperaremos en esta sección de la apelación.
```

2024-08-20 21:49 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - **Cualquier mala conducta mayor resultará en una restricción inmediata.** Esto incluye silenciamientos importantes.
```suggestion
- **Cualquier mala conducta mayor resultará en una restricción inmediata.** Esto incluye silencios importantes.
```

2024-08-21 22:53 UTC, UnknownOsu requested changes

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  Si tu cuenta ha sido restringida, no entres en pánico. Por favor sigue los siguientes pasos:
```suggestion
Si tu cuenta ha sido restringida, no entres en pánico. Por favor, sigue los siguientes pasos:
```

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - Si crees fuertemente que tu restricción fue errónea, por favor contáctanos inmediatamente para que podamos discutir tu caso.
```suggestion
- Si crees firmemente que tu restricción fue errónea, ponte en contacto con nosotros inmediatamente para que podamos discutir tu caso.
```

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **No es tu primera cuenta.** Las multicuentas están en contra de las reglas. Cualquier cuenta que no sea la cuenta original de un jugador será permanentemente restringida, pero su cuenta original e
```suggestion
- **No es tu primera cuenta.** Las multicuentas están en contra de las reglas. Cualquier cuenta que no sea la cuenta original de un jugador será permanentemente restringida, pero su cuenta original en la mayoría de los casos seguirá abierta y el jugador es alentado a seguir jugando en ella. Si el uso de multicuentas es severo o abusivo, se aplicará un silencio a la cuenta original como advertencia para que deje de crear nuevas cuentas, y se restringirá la cuenta principal si el uso de multicuentas continúa. Si tu cuenta es restringida y sabes que tienes otras cuentas, por favor, no continúes accediendo a las cuentas restringidas que tienes y continúa jugando en tu cuenta original. Si tienes problemas para acceder o para verificarla, envíanos un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh) para que podamos ayudarte a recuperar el acceso a ella.
```

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - **No dudes en contactarnos si tienes alguna pregunta.** Mientras no intentes salvarte del castigo, ¡felizmente contestaremos cualquier pregunta que tenga sobre la restricción de tu cuenta!
```suggestion
- **No dudes en contactarnos si tienes alguna pregunta.** Mientras no intentes salvarte del castigo, ¡felizmente contestaremos cualquier pregunta que tengas sobre la restricción de tu cuenta!
```

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +Puedes apelar enviando un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh) incluyendo el nombre de tu cuenta. Asegúrate de enviar el correo desde la dirección de correo asociada a tu cuenta. Despué
```suggestion
Puedes apelar enviando un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh) incluyendo el nombre de tu cuenta. Asegúrate de enviar el correo desde la dirección de correo asociada a tu cuenta. Después de que envíes tu apelación, espera una respuesta en el plazo de una semana. Si no has recibido una para ese entonces, contáctanos vía correo o twitter, es posible que no la hayamos recibido.
```

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +Los participantes que regresan bajo los términos estándar anteriores también [están excluidos de los torneos oficiales y con insignia](/wiki/Help_centre/Tournament_bans), tanto como competidores como
```suggestion
Los jugadores que regresen al juego mediante una apelación, según los términos estándar anteriores, también [estarán vetados de los torneos oficiales y con insignia](/wiki/Help_centre/Tournament_bans), tanto como competidores como miembros del equipo organizador del torneo. La duración de este veto es de un año (si es la segunda apelación del usuario, el veto dura 2 años). El correo electrónico del levantamiento de la restricción aclarará la duración de esta prohibición.
```

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
>  - **Fue enviada demasiado pronto.** Si el tiempo de espera de tu cuenta no ha pasado, tu apelación será denegada. Si no estás seguro de cuando puedes apelar realmente, por favor responde a nuestra re
```suggestion
- **Fue enviada demasiado pronto.** Si el tiempo de espera de tu cuenta no ha pasado, tu apelación será denegada. Si no estás seguro de cuándo puedes apelar, responde a nuestra respuesta y te daremos la fecha correcta.
```

2024-08-21 22:53 UTC, UnknownOsu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **Has estado evadiendo o jugando en la cuenta de otro.** Crear otra cuenta para poder jugar en línea mientras tu cuenta está restringida es considerado un intento de evadir la restricción y restabl
```suggestion
- **Has estado evadiendo o jugando en la cuenta de otro.** Crear otra cuenta para poder jugar en línea mientras tu cuenta está restringida es considerado un intento de evadir la restricción y restablecerá tu tiempo de espera a al menos **tres meses** desde la fecha en la que creaste la cuenta. Si intentas evadirla muchas veces, tu apelación puede ser denegada permantemente. Si sigues accediendo o jugando en tus multicuentas mientras estás restringido, tu tiempo de espera se restablecerá. Recuerda que las multicuentas están en contra de las [reglas](/wiki/Rules) y se espera que juegues solo en tu cuenta original. ¡Si no estás seguro de cuál cuenta es considerada tu cuenta original, envíanos un correo y te lo haremos saber!
```

2024-08-21 22:54 UTC, UnknownOsu commented
En la línea 12 puedes poner: `y ser parte del personal en torneos patrocinados oficialmente`
En la 89: `tu apelación puede ser denegada permanentemente.`
En la 102: `envíanos un correo`, o sea, quitar el `por el favor`
Línea 113: Poner una coma después del `Por favor`
Línea 117: `Razón de la restricción`

2024-09-03 10:15 UTC, TicClick approved these changes

2024-09-03 10:17 UTC, merged