[ES] Add `Legal/Terms`
ppy/osu-wiki pull request #12009
Opened 2024-08-21 10:50 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-08-21 19:14 UTC, UnknownOsu requested changes

2024-08-21 19:14 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +## ENVÍOS DE USUARIOS Y ELIMINACIÓN DE CONTENIDOS
```suggestion
## ENVÍOS DE USUARIOS Y ELIMINACIÓN DE CONTENIDO
```

2024-08-21 19:14 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +osu! no permite actividades que infrinjan los derechos de autor y los derechos de propiedad intelectual en su Sitio web, y osu! eliminará todos los Contenidos y Envíos de Usuario si se le notifica de
```suggestion
osu! no permite actividades que infrinjan los derechos de autor y los derechos de propiedad intelectual en su Sitio web, y osu! eliminará todo el Contenido y Envíos de Usuario si se le notifica debidamente que dicho Contenido o Envíos de Usuario infringen los derechos de propiedad intelectual de terceros.
```

2024-08-21 19:14 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +osu! se reserva el derecho a eliminar Contenidos y Envíos de Usuario sin previo aviso.
```suggestion
osu! se reserva el derecho a eliminar Contenido y Envíos de Usuario sin previo aviso.
```

2024-08-21 19:14 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +El envío de cualquier tipo de información personal se realiza únicamente con su consentimiento (sitio web) o de forma automática (software cliente del juego) cuando es necesario para proporcionar dia
```suggestion
El envío de cualquier tipo de información personal se realiza únicamente con su consentimiento (sitio web) o de forma automática (software del cliente del juego) cuando es necesario para proporcionar diagnósticos y comentarios.
```

2024-08-21 19:14 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +osu! puede usar cookies como parte del proceso de seguimiento, pero las cookies no se usarán para identificarle personalmente sin su consentimiento previo.
```suggestion
osu! puede usar cookies como parte del proceso de seguimiento, pero las cookies no se usarán para identificarlo personalmente sin su consentimiento previo.
```

2024-08-21 19:14 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +## DERECHOS DE PROPIEDAD DE LOS CONTENIDOS
```suggestion
## DERECHOS DE PROPIEDAD DEL CONTENIDO
```

2024-08-22 08:45 UTC, agatemosu commented on wiki/Legal/Terms/es.md
> +EN NINGÚN CASO osu!, SUS FUNCIONARIOS, DIRECTORES, EMPLEADOS O AGENTES, SERÁN RESPONSABLES ANTE USTED POR NINGÚN DAÑO DIRECTO, INDIRECTO, INCIDENTAL, ESPECIAL, PUNITIVO O CONSECUENTE QUE RESULTE DE (
Hice un reemplazar todo y se perdieron las mayusculas xd

2024-09-03 18:50 UTC, UnknownOsu requested changes

2024-09-03 18:50 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +El usuario reconoce y acepta que osu! no es responsable de la disponibilidad de dichos sitios o recursos externos, y no respalda ni es responsable de ningún contenido, publicidad, productos u otros m
```suggestion
El Usuario reconoce y acepta que osu! no es responsable de la disponibilidad de dichos sitios o recursos externos, y no respalda ni es responsable de ningún contenido, publicidad, productos u otros materiales en dichos sitios o recursos o disponibles a través de ellos.
```

2024-09-03 18:50 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +El usuario acepta que osu! no será responsable, directa o indirectamente, de ningún daño o pérdida causados o supuestamente causados por o en conexión con el uso o la confianza depositada en cualquie
```suggestion
El Usuario acepta que osu! no será responsable, directa o indirectamente, de ningún daño o pérdida causados o supuestamente causados por o en conexión con el uso o la confianza depositada en cualquier contenido, bien o servicio disponible en dichos sitios o recursos externos.
```

2024-09-03 18:53 UTC, UnknownOsu commented on wiki/Legal/Terms/es.md
> +osu! puede usar cookies como parte del proceso de seguimiento, pero las cookies no se usarán para identificarle personalmente sin su consentimiento previo.
@agatemosu También este

2024-09-10 13:20 UTC, UnknownOsu approved these changes

2024-09-12 19:35 UTC, TicClick approved these changes

2024-09-12 19:38 UTC, merged