[ES] Add `Ranking criteria/Skin set list`
ppy/osu-wiki pull request #12041
Opened 2024-08-25 19:56 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +| hit0{-n}.png | debería distinguirse claramente de todas los demás hit bursts | requerido | - |
```suggestion
| hit0{-n}.png | debería distinguirse claramente de todos los demás hit bursts | requerido | - |
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +| hit50{-n}.png | debería distinguirse claramente de todas los demás hit bursts | requerido | - |
```suggestion
| hit50{-n}.png | debería distinguirse claramente de todos los demás hit bursts | requerido | - |
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +| hit100{-n}.png | debería distinguirse claramente de todas los demás hit bursts | requerido | - |
```suggestion
| hit100{-n}.png | debería distinguirse claramente de todos los demás hit bursts | requerido | - |
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +| hit100k{-n}.png | debería distinguirse claramente de todas los demás hit bursts | requerido | - |
```suggestion
| hit100k{-n}.png | debería distinguirse claramente de todos los demás hit bursts | requerido | - |
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +| hit300{-n}.png | debería distinguirse claramente de todas los demás hit bursts | requerido | - |
```suggestion
| hit300{-n}.png | debería distinguirse claramente de todos los demás hit bursts | requerido | - |
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +| hit300g{-n}.png | debería distinguirse claramente de todas los demás hit bursts | requerido | - |
```suggestion
| hit300g{-n}.png | debería distinguirse claramente de todos los demás hit bursts | requerido | - |
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +| hit300k{-n}.png | debería distinguirse claramente de todas los demás hit bursts | requerido | - |
```suggestion
| hit300k{-n}.png | debería distinguirse claramente de todos los demás hit bursts | requerido | - |
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +El estilo nuevo de los spinners solo funcionará si la skin específica del usuario no usa el antiguo y es compatible con la versión 2 o posteriores de las skin, o si la skin predeterminada está forzad
```suggestion
El estilo nuevo de los spinners solo funcionará si la skin específica del usuario no usa el antiguo y es compatible con la versión 2 o posteriores de las skins, o si la skin predeterminada está forzada en el beatmap.
```

2024-09-01 18:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Ranking_criteria/Skin_set_list/es.md
> +La totalidad de este conjunto es relevante para el juego. Este conjunto no debe usarse si el beatmap no usa cuentas regresivas.
```suggestion
La totalidad de este conjunto es relevante para el juego. Estos elementos no deben usarse si el beatmap no usa cuentas regresivas.
```

2024-09-03 10:23 UTC, TicClick approved these changes

2024-09-03 10:56 UTC, merged