[IT] Add `Disambiguation/osu!`
ppy/osu-wiki pull request #12098
Opened 2024-09-05 01:09 UTC by G3ntl3m4n10

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [  ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-05 01:17 UTC, hhacki approved these changes
LGTM

2024-09-05 10:24 UTC, hhacki requested changes

2024-09-05 10:24 UTC, hhacki commented on wiki/Disambiguation/osu!/it.md
> +- [Osu! Tatakae! Ouendan!](/wiki/iNiS_games), un giocodi ritmo sviluppatofa iNiS per il Nintendo DS
```suggestion
- [Osu! Tatakae! Ouendan!](/wiki/iNiS_games), un gioco di ritmo sviluppato da iNiS per il Nintendo DS
```

2024-09-05 10:29 UTC, hhacki commented on wiki/Disambiguation/osu!/it.md
> +# osu! (disambiguation)
```suggestion
# osu! (disambiguazione)
```

2024-09-05 10:31 UTC, hhacki approved these changes

2024-09-09 20:35 UTC, TicClick approved these changes

2024-09-09 20:36 UTC, merged