[ES] FAQ - Added "Controls" and "Change Gamemode" Sections
ppy/osu-wiki pull request #12121
Opened 2024-09-10 01:29 UTC by Mikes-Play

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-10 17:04 UTC, agatemosu commented on wiki/FAQ/es.md
> +Los Hit Objects en Osu! aceptarán cualquier entrada proveniente de cualquier dispositivo siempre y cuando los Hit Objects sean presionados en el momento correcto
```suggestion
Los objetos en osu! aceptarán cualquier entrada proveniente del dispositivo y cuando los objetos sean presionados en el momento correcto.
```

2024-09-10 17:04 UTC, agatemosu commented on wiki/FAQ/es.md
> +Si se está usando el modificador [Relax](/wiki/es/Gameplay/Game_modifier/Relax), solo funcionará el cursor y se deshabilitarán los botones del teclado/mouse/lapiz. Usa el cursor para seguir a los Hit
```suggestion
Si se está usando el modificador del juego [Relax](/wiki/Gameplay/Game_modifier/Relax), solo funcionará el cursor y se deshabilitarán los botones del teclado/ratón/lápiz. Usa el cursor para seguir a los objetos mientras estos se presionan automaticamente. Sin embargo, los spinners deberán ser completados normalmente.
```

2024-09-10 17:04 UTC, agatemosu commented on wiki/FAQ/es.md
> +Si se está usando el modificador [Auto Pilot](/wiki/es/Gameplay/Game_modifier/Autopilot), solo funcionará la entrada de teclado/mouse/lapiz pero se deshabilitará el movimiento del cursor. Usa los bot
```suggestion
Si se está usando el modificador del juego [Auto Pilot](/wiki/es/Gameplay/Game_modifier/Autopilot), solo funcionará la entrada del teclado/ratón/lápiz pero se deshabilitará el movimiento del cursor. Usa los botones para presionar a tiempo los objetos mientras el cursor los sigue automaticamente. Los spinners seguirán la velocidad del mod [Spun Out](/wiki/Gameplay/Game_modifier/Spun_Out)
```

2024-09-10 17:04 UTC, agatemosu commented on wiki/FAQ/es.md
> +### Cambiando el Modo de Juego
```suggestion
## Otros modos de juego

### Cambiando el modo de juego
```

2024-09-10 17:04 UTC, agatemosu commented on wiki/FAQ/es.md
> +![Mode change interface](/wiki/shared/Interface_mode.png "Mode toolbox in Song Selection (Solo)")
```suggestion
![Interfaz del cambio de modo](/wiki/shared/Interface_mode.png "Cambio de modo en el selector de canciones (Solo)")
```

2024-09-10 17:04 UTC, agatemosu commented on wiki/FAQ/es.md
> +Cliquea en el boton de `Modo` para **abrir una lista con los modos de juego disponibles en Osu!**. Cliquea en el modo de juego deseado y Osu! cambiará al estilo del modo de juego deseado. Tambien pue
```suggestion
Haz clic en el boton de `Mode` para **abrir una lista con los modos de juego disponibles en osu!**. Haz clic en el modo de juego deseado y osu! cambiará al modo de juego deseado. También puedes presionar las teclas `Ctrl` y `1` (![][osu!] *[osu!](/wiki/Game_mode/osu!))* / `2` ( ![][osu!taiko] *[osu!taiko](/wiki/Game_mode/osu!taiko)*) / `3` (![][osu!catch] *[osu!catch](/wiki/Game_mode/osu!catch)*) / `4` (![][osu!mania] *[osu!mania](/wiki/Game_mode/osu!mania)*) para cambiar rápidamente entre los modos de juego
```

2024-09-11 16:01 UTC, UnknownOsu requested changes

2024-09-11 16:44 UTC, agatemosu commented on wiki/FAQ/es.md
> +| Clic izquierdo(M1) / Clic derecho(M2) | `Z`(K1) / `X`(K2) | Tocar la pantalla/tableta(M1) |
así sale en el original

2024-09-11 17:02 UTC, UnknownOsu commented on wiki/FAQ/es.md
> +| Clic izquierdo(M1) / Clic derecho(M2) | `Z`(K1) / `X`(K2) | Tocar la pantalla/tableta(M1) |
Ya, pero se ve más bonito así

2024-09-11 20:49 UTC, agatemosu commented on wiki/FAQ/es.md
> +![Interfaz para cambiar el modo de juego](/wiki/shared/Interface_mode.png "Menú desplegable para la selección de los modos de juego en el selector de canciones (Solo)")
```suggestion
![Menú de cambio de modo en el selector de canciones (Solo)](/wiki/shared/Interface_mode.png "Menú de cambio de modo en el selector de canciones (Solo)")
```

2024-09-12 09:06 UTC, agatemosu approved these changes

2024-09-12 16:42 UTC, UnknownOsu approved these changes

2024-09-26 17:54 UTC, TicClick approved these changes

2024-09-26 17:54 UTC, merged