[ZH] Add and update `Gameplay`
ppy/osu-wiki pull request #12124
Opened 2024-09-11 01:43 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-27 09:28 UTC, SamHou0 requested changes
- `score multiplier`我认为应该翻译为连击乘数，而不是连击因数。
- 修复了错误的维基百科链接
- 修改了几处不通顺的语句，以及错误的翻译

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/Spectating/zh.md
> +如果用户要旁观其他玩家，则要下载对方正在游玩的同一谱面。当被旁观玩家开始玩新谱面，且旁观者没有这张谱面时，则会在 `#spectator` 私密频道中发出新谱面。但如果旁观者拥有 [osu! 支持者](/wiki/osu!supporter)标签的话，则会通过 osu!direct 自动下载谱面，并在游戏内自动处理。
```suggestion
如果用户要旁观其他玩家，必须先下载对方正在游玩的同一谱面。当被旁观玩家开始玩新谱面，且旁观者没有这张谱面时，则会在 `#spectator` 私密频道中发出新谱面。但如果旁观者拥有 [osu! 支持者](/wiki/osu!supporter)标签的话，则会通过 osu!direct 自动下载谱面，并在游戏内自动处理。
```
 `need to have downloaded`是完成式，译为在什么之前必须下载。

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/Spinner_trap/zh.md
> +**转盘陷阱** (**Spinner trap**) 是 [osu!catch](/wiki/Game_mode/osu!catch) 游戏模式中的术语，指的是在香蕉雨<!-- TODO: link -->（在 osu!catch 中相当于[转盘](/wiki/Gameplay/Hit_object/Spinner)）后，紧接着放置了一般不容易接住的[大果](/wiki/Gameplay/Hi
```suggestion
**转盘陷阱** (**Spinner trap**) 是 [osu!catch](/wiki/Game_mode/osu!catch) 游戏模式中的术语，指的是在香蕉雨<!-- TODO: link -->（在 osu!catch 中，这与[转盘](/wiki/Gameplay/Hit_object/Spinner)相当）后，紧接着放置了一般不容易接住的[大果](/wiki/Gameplay/Hit_object/Fruit)。有几种原因可能会导致这种情况出现：
```
有歧义，osu!catch 中没有转盘，要表述的应该是香蕉雨和转盘相当。

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/Spinner_trap/zh.md
> +- 当按照最优路径接住转盘最后一个[香蕉](/wiki/Gameplay/Hit_object/Banana)后，到这个大果的距离过远，以至于无法接到。
```suggestion
- 当按照最优路径接住最后一个[香蕉](/wiki/Gameplay/Hit_object/Banana)后，到这个大果的距离过远，以至于无法接到。
```
原文没有转盘的意思。

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/Unstable_rate/zh.md
> +  - 打击偏差
```suggestion
  - 打击偏差
  - 计时
```
少翻译了 Timing 标签

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/Unstable_rate/zh.md
> +**不稳定率** (**Unstable rate**, ***UR***) 是用来衡量一次游玩中打击偏差<!-- TODO: link -->变化程度的数值。这个值等于打击偏差的[标准差](https://zh.wikipedia.org/wiki/Standard_deviation)，单位为十分之一毫秒。UR 值越低，则玩家打击的偏差值越集中，反之则越分散。
```suggestion
**不稳定率** (**Unstable rate**, ***UR***) 是用来衡量一次游玩中打击偏差<!-- TODO: link -->变化程度的数值。这个值等于打击偏差的[标准差](https://zh.wikipedia.org/wiki/%E6%A8%99%E6%BA%96%E5%B7%AE)，单位为十分之一毫秒。UR 值越低，则玩家打击的偏差值越集中，反之则越分散。
```
链接错误，指向的内容不存在。

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/Unstable_rate/zh.md
> +请注意，UR 度量的是打击偏差之间的一致程度，而不是偏差值。尽管低 UR 通常来自于高准确率的游玩，但准确率非常低时也有可能获得低 UR。举个例子，玩家可以在足够晚的时间，在偏差保持一定的情况下点击每个[物件](/wiki/Gameplay/Hit_object)来获得 [50](/wiki/Gameplay/Judgement/osu!) 判定。
```suggestion
请注意，UR 度量的是打击偏差之间的一致程度，而不是偏差值。尽管低 UR 通常来自于高准确率的游玩，但准确率非常低时也有可能获得低 UR。举个例子，玩家可以在足够晚的时间点击每个[物件](/wiki/Gameplay/Hit_object)来获得 [50](/wiki/Gameplay/Judgement/osu!) 判定，而保持打击偏差一致。
```
句子强调的是打击偏差，所以把`保持打击偏差一致`放在最后强调。

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/Unstable_rate/zh.md
> +## 结算屏幕显示
```suggestion
## 结算屏幕上的不稳定率
```
原文是`On the results screen`，结合语境看这里指的是`UR on the results screen`。

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/zh.md
> +- [连击（分数因数）](/wiki/Gameplay/Combo_(score_multiplier))
```suggestion
- [连击（分数乘数）](/wiki/Gameplay/Combo_(score_multiplier))
```

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/zh.md
> +- [连击因数效应](/wiki/Gameplay/Combo_multiplier_effect)
```suggestion
- [连击乘数效应](/wiki/Gameplay/Combo_multiplier_effect)
```

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/zh.md
> +- [Grade](/wiki/Gameplay/Grade)
```suggestion
- [评价](/wiki/Gameplay/Grade)
```

2024-09-27 09:28 UTC, SamHou0 commented on wiki/Gameplay/zh.md
> +- [数位板](/wiki/Gameplay/Tablet_cover)
```suggestion
- [数位板膜](/wiki/Gameplay/Tablet_cover)
```
翻译错误，这里是数位板上覆盖的膜

2024-09-27 09:50 UTC, CloneWith commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +# 连击（得分因数）
你说得对
当时这里我也考虑了一段时间

2024-09-27 12:21 UTC, CloneWith commented on wiki/Gameplay/Pass/zh.md
> +**通过** (**Pass**) 指的是在不使用避免失败的[模组](/wiki/Gameplay/Game_modifier)（例如 [No Fail](/wiki/Gameplay/Game_modifier/No_Fail)）的情况下，完成一张[谱面](/wiki/Beatmap)或是特定的谱面区段，亦或是在进入[休息](/wiki/Beatmap/Break)时段时[血量](/wiki/
可以，这里指的是休息期间会闪动几下的中间图片

2024-09-27 12:27 UTC, CloneWith commented on wiki/Gameplay/zh.md
> +- [数位板](/wiki/Gameplay/Tablet_cover)
查完没补是这样的（

2024-09-30 09:53 UTC, SamHou0 commented
@CloneWith 检查了一下，似乎还有不少连击`因数`没有被替换为`乘数`，我觉得直接批量替换一下比较好

2024-10-01 01:40 UTC, SamHou0 requested changes
修改8处遗留的`因数`

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况会将得分因数归零：**
```suggestion
**下列情况会将得分乘数归零：**
```

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况对得分因数没有影响：**
```suggestion
**下列情况对得分乘数没有影响：**
```

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况会将得分因数归零：**
```suggestion
**下列情况会将得分乘数归零：**
```

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况对得分因数没有影响：**
```suggestion
**下列情况对得分乘数没有影响：**
```

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况会将得分因数归零：**
```suggestion
**下列情况会将得分乘数归零：**
```

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况对得分因数没有影响：**
```suggestion
**下列情况对得分乘数没有影响：**
```

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况会将得分因数归零：**
```suggestion
**下列情况会将得分乘数归零：**
```

2024-10-01 01:40 UTC, SamHou0 commented on wiki/Gameplay/Combo_(score_multiplier)/zh.md
> +**下列情况对得分因数没有影响：**
```suggestion
**下列情况对得分乘数没有影响：**
```

2024-10-01 07:41 UTC, SamHou0 approved these changes

2024-10-18 16:08 UTC, TicClick approved these changes

2024-10-18 16:08 UTC, merged