[ES] Add `osu!stream`
ppy/osu-wiki pull request #12148
Opened 2024-09-16 22:23 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +A diferencia del osu! normal, osu!stream presenta un sistema de juego completamente nuevo con elementos únicos como los círculos para mantener pulsados y los ritmos conectados. No es compatible con l
```suggestion
A diferencia del osu! normal, osu!stream presenta un sistema de juego completamente nuevo con elementos únicos como los círculos mantenidos y los objetos conectados. No es compatible con los beatmaps clásicos de osu! sin conversión manual. En su lugar, los mapas son creados por un equipo especial de mappers para aprovechar los nuevos elementos y adherirse a un [nivel más estricto de estándares](https://docs.google.com/document/d/1FYmHhRX-onR-osgTS6uHSOZuu_0JEbfRZePVySvvr9g).
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +El juego se presentó por primera vez a través de [un críptico vídeo de YouTube](https://www.youtube.com/watch?v=6Jyzgm_-joM) en junio de 2011. Tras su lanzamiento público un par de meses después, se
```suggestion
El juego se presentó por primera vez a través de [un críptico vídeo de YouTube](https://www.youtube.com/watch?v=6Jyzgm_-joM) en junio de 2011. Tras su lanzamiento público un par de meses después, se detallaron los pormenores del juego en el [osu!monthly \#5](https://osu.ppy.sh/community/forums/topics/59924) junto con una entrevista a peppy.
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +#### Indicadores de dedos en pantalla
```suggestion
#### Indicadores de dedos en la pantalla
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +![](img/Os-FG.jpg "Indicadores de dedos en pantalla")
```suggestion
![](img/Os-FG.jpg "Indicadores de dedos en la pantalla")
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +#### Ritmos conectados
```suggestion
#### Objetos conectados
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +![](img/Os-CB.png "Ritmos conectados")
```suggestion
![](img/Os-CB.png "Objetos conectados")
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +- Los ritmos conectados, como sugiere el título, requieren que el jugador pulse los dos objetos al mismo tiempo.
```suggestion
- Los objetos conectados, como sugiere el título, requieren que el jugador pulse los dos objetos al mismo tiempo.
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +  - Los ritmos conectados no se limitan a «círculo-círculo», sino que pueden ser «círculo-slider», «círculo mantenido-slider», etc.
```suggestion
  - Los objetos conectados no se limitan a «círculo-círculo», sino que pueden ser «círculo-slider», «círculo mantenido-slider», etc.
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +- Los ritmos conectados pueden identificarse por tener una línea blanca recta que conecta con otro objeto.
```suggestion
- Los objetos conectados pueden identificarse por tener una línea blanca recta que conecta con otro objeto.
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +#### Círculo mantenido
```suggestion
#### Círculos mantenidos
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +El modo Stream es un modo exclusivo de osu!stream. En este modo, los jugadores empiezan con una «segunda» barra de vida llena hasta la mitad y con un nivel de dificultad normal. A continuación, el ju
```suggestion
El modo Stream es un modo exclusivo de osu!stream. En este modo, los jugadores empiezan con una «segunda» barra de vida llena hasta la mitad y con un nivel de dificultad normal. Luego, el jugador debe llenarla para activar el modo «Stream Up!», que básicamente aumenta la dificultad (añadiendo objetos y cambiando a la dificultad Hard del mapa), pero sigue siendo bastante menos difícil que el modo Expert. Cuando los jugadores entran en el modo «Stream Up!», aparece una nueva barra de vida y «Stream Down!» se activará si esa barra de vida se agota, volviendo a la dificultad Normal o Easy y a la barra de vida anterior.
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +Ten en cuenta que el jugador **debe conseguir al menos un grado A (>80 % de precisión) en este modo para desbloquear el modo experto de la canción**. Una precisión inferior al 80 % aunque sea combo c
```suggestion
Ten en cuenta que el jugador **debe conseguir al menos un grado A (>80 % de precisión) en este modo para desbloquear el modo Expert de la canción**. Una precisión inferior al 80 % aunque sea combo completo no cuenta como A (se contará como B como de costumbre).
```

2024-09-25 19:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/osu!stream/es.md
> +- No poder pulsar simultáneamente los ritmos conectados. (Pulsar uno y fallar el otro)
```suggestion
- No poder pulsar simultáneamente los objetos conectados. (Pulsar uno y fallar el otro)
```

2024-10-18 16:48 UTC, TicClick approved these changes

2024-10-18 16:48 UTC, merged