added zh.md for History-of-osu! 2007
ppy/osu-wiki pull request #12140
Opened 2024-09-15 15:37 UTC by jimmy-sketch

# Self Check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] (translations only) The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-16 09:01 UTC, jimmy-sketch reviewed
I've cleaned all of the wrong wiki links.

2024-09-18 15:31 UTC, CloneWith requested changes
你好呀，欢迎来为咱们的 osu-wiki 中译做贡献！
第一次在这里翻译这么长的文章属实不易，辛苦辛苦\~

翻译的同时，留心下面这些会让你的翻译更好些：

- 链接格式与路径引用：链接一般是保留原样，尤其是站内链不要用相对路径，使用`/wiki`这样的*绝对路径*链接，连接符用斜杠`/`，是各平台通用的。
- 概念与术语：目前很多文章里的术语（比如像 `Beatmap Editor` 这样的）在wiki都有过比较常用的翻译，可以尝试在站内搜搜，或者看看[术语表](https://osu-atri.github.io/osu-dictionary)。
- 风格与语法：翻译时可以试试多想想，一个词可能在释义方面过于晦涩，但是经一定的理解与转义之后，通常会让读者更好懂；英语中使用的语法也要转成中文惯用的形式。

一会儿我会再看看的，有啥问题欢迎来交流交流\~

2024-09-18 15:31 UTC, CloneWith commented on wiki/History_of_osu!/2007/zh.md
> +本篇文章的内容是osu! 从其诞生以来的大事记。感谢[Sinistro](https://osu.ppy.sh/users/5530)对于2007年至2008年之间发生的事件的补充。
```suggestion
本文记载了 osu! 自其诞生以来的重大事件。感谢 [Sinistro](https://osu.ppy.sh/users/5530) 编写 2007 年至 2008 年部分的内容。
```

- `内容`是`大事记`？这里不太通，可以换种形式，例如`记载`
- `compile` 记得是`编译，编写（报告、书）`之类的意思，
- 我们这边一般的习惯是在英文单词两边各加一个空格

2024-09-18 15:31 UTC, CloneWith commented on wiki/History_of_osu!/2007/zh.md
> +# osu! 在2007年的历史
感觉这边有点怪？可以改成 `osu! 2007 历史` 或者 `osu! 2007 大事记` 之类的，后者是意译

2024-09-18 15:31 UTC, CloneWith commented on wiki/History_of_osu!/2007/zh.md
> +![](img\2007.jpg)
上方缺空行

2024-09-18 15:31 UTC, CloneWith commented on wiki/History_of_osu!/2007/zh.md
> +![](img\2007-12_01.jpg "")
空描述文本？
```suggestion
![](img/2007-12_01.jpg)
```

2024-09-18 15:43 UTC, CloneWith commented on wiki/History_of_osu!/2007/zh.md
> +[^3]:在osu!razor于2024年6月25日的更新中，制谱器加入了对于休息段的（添加）编辑功能
这里建议保留原来以单词做脚注引用的格式，维护起来也更加方便

2024-09-18 15:43 UTC, CloneWith commented on wiki/History_of_osu!/2007/zh.md
> +[^3]:在osu!razor于2024年6月25日的更新中，制谱器加入了对于休息段的（添加）编辑功能
这里讲的是 osu!lazer 吧（

2024-09-18 16:10 UTC, YumeMuzi requested changes
请按照文章风格规范 https://osu.ppy.sh/wiki/zh/Article_styling_criteria 编写翻译。目前翻译问题非常多，烦请逐行修改。

强烈推荐先看一遍 https://osu.ppy.sh/wiki/zh/Article_styling_criteria/Writing 。

Please check your translated text and make sure it follows ASC. The current translation is not accurate or fluent enough.

2024-09-18 16:10 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +[^3]:在osu!razor于2024年6月25日的更新中，制谱器加入了对于休息段的（添加）编辑功能
在 2007 的历史页中，不要添加 2024 年的内容（除非原文有）

2024-09-19 21:54 UTC, jimmy-sketch commented
> 你好呀，欢迎来为咱们的 osu-wiki 中译做贡献！ 第一次在这里翻译这么长的文章属实不易，辛苦辛苦~
> 
> 翻译的同时，留心下面这些会让你的翻译更好些：
> 
> * 链接格式与路径引用：链接一般是保留原样，尤其是站内链不要用相对路径，使用`/wiki`这样的_绝对路径_链接，连接符用斜杠`/`，是各平台通用的。
> * 概念与术语：目前很多文章里的术语（比如像 `Beatmap Editor` 这样的）在wiki都有过比较常用的翻译，可以尝试在站内搜搜，或者看看[术语表](https://osu-atri.github.io/osu-dictionary)。
> * 风格与语法：翻译时可以试试多想想，一个词可能在释义方面过于晦涩，但是经一定的理解与转义之后，通常会让读者更好懂；英语中使用的语法也要转成中文惯用的形式。
> 
> 一会儿我会再看看的，有啥问题欢迎来交流交流~

这里的话如果我用`/wiki`的绝对路径的话，那么Visual Studio Code 和这边的检查器会一直给我报错，不知道是什么问题。不过，我还是会尽量按照你们给出的建议进行修改的。

2024-09-19 22:00 UTC, CloneWith commented
呃我可能说错了？
其实也不算是绝对路径，更类似于相对于项目目录的相对路径
比如osu-wiki文件夹本身表示为`/`，谱面编辑器的路径就是`/wiki/Client/Beatmap_editor`，后面不需要加上md文件
我这边这么写是不会报错的）

2024-09-19 22:07 UTC, jimmy-sketch commented on wiki/History_of_osu!/2007/zh.md
> +[^3]:在osu!razor于2024年6月25日的更新中，制谱器加入了对于休息段的（添加）编辑功能
我已经不止一次打错这个字了（

2024-09-20 09:34 UTC, SamHou0 requested changes
- 格式存在问题，部分句子不完整或翻译有误。
- 在中文和英文间，应该添加空格。

2024-09-20 09:34 UTC, SamHou0 commented on wiki/History_of_osu!/2007/zh.md
> +游戏体验通过[连击特效](/wiki/Gameplay/Combo_fire)、[血条](/wiki/Gameplay/Health)、鼠标尾迹和更好看的滑条得到了加强。此时，osu!已经有了一个由5人左右的测试团队所做的大概10张谱面所组成的一个谱面库。
```suggestion
游戏体验通过[连击特效](/wiki/Gameplay/Combo_fire)、[血量](/wiki/Gameplay/Health)条、鼠标尾迹和更好看的滑条得到了加强。此时，osu!已经有了一个由5人左右的测试团队所做的大概10张谱面所组成的一个谱面库。
```
链接指向的是血量，因此应将“条”字独立开来

2024-09-20 09:34 UTC, SamHou0 commented on wiki/History_of_osu!/2007/zh.md
> +选曲界面则有了两个改进：一个是难度分组，一个是更加直观的”轮式选曲“的动画。”软件示例集“、基于键盘的控制方式和游戏内搜索在这个月中加入。玩家们首次可以制作全局[皮肤](/wiki/Skinning)和对于特定谱面的皮肤。同时，对于平板（触屏）电脑的完整支持也得到了实现。
```suggestion
选曲界面则有了两个改进：一个是难度分组，一个是更加直观的滚动选歌动画。软件示例集，基于键盘的控制方式和游戏内搜索在这个月中加入。玩家们首次可以制作全局[皮肤](/wiki/Skinning)和针对特定谱面的皮肤。同时，对于平板（触屏）电脑的完整支持也得到了实现。
```
不要随意使用引号（况且引号也用反了）

2024-09-20 09:34 UTC, SamHou0 commented on wiki/History_of_osu!/2007/zh.md
> +![](img/2007-11_03.jpg "测试IRC功能")
```suggestion
![](img/2007-11_03.jpg "测试 IRC 功能")
```

2024-09-20 10:48 UTC, jimmy-sketch commented on wiki/History_of_osu!/2007/zh.md
> +![选曲界面](img/2007-07_01.jpg "选曲界面")
这个在实际的呈现上其实并未更改，我认为这其实不是对于原文的一种“修改”。这里其实是我在写markdown的时候的一个失误。

2024-09-29 14:10 UTC, jimmy-sketch commented
I think the text is right now.

2024-09-29 15:16 UTC, closed without merging

2024-09-29 15:17 UTC, Y2nn1c commented
> I think the text is right now.

But if it's correct now, why did you close it?

2024-09-29 15:18 UTC, jimmy-sketch commented
I have some problems on git and the changes in this have been incorrectly merge into other PRs

2024-09-29 15:19 UTC, Y2nn1c commented
> I have some problems on git and the changes in this have been incorrectly merge into other PRs

ooh i see