[ES] Add `Help centre/Account`
ppy/osu-wiki pull request #12157
Opened 2024-09-16 22:24 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-26 01:38 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-26 01:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Account/es.md
> +Si el cambio se hizo con el cambio gratuito que viene con la etiqueta de supporter, no podemos ofrecer cambiarlo de nuevo.
```suggestion
Si el cambio se hizo con el cambio gratuito que viene con la etiqueta de supporter, no podemos ofrecerte cambiarlo de nuevo.
```

2024-09-26 01:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Account/es.md
> +Estamos considerando la posibilidad de añadir compras de para el «restablecimiento de las puntuaciones» en la osu!store para los jugadores más exigentes que solo desean la perfección en sus estadísti
```suggestion
Estamos considerando la posibilidad de añadir compras para el «restablecimiento de las puntuaciones» en la osu!store para los jugadores más exigentes que solo desean la perfección en sus estadísticas, pero actualmente no podemos eliminar las estadísticas de una cuenta por ti.
```

2024-09-26 01:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Account/es.md
> +*Para más información sobre la eliminación de cuentas, véase: [Política de privacidad de osu! § Sus derechos y control](/wiki/Legal/Privacy#sus-derechos-y-control).*\
```suggestion
*Para más información sobre la eliminación de las cuentas, véase: [Política de privacidad de osu! § Sus derechos y control](/wiki/Legal/Privacy#sus-derechos-y-control).*\
```

2024-09-26 01:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Account/es.md
> +*Advertencia: La eliminación de la cuenta es permanente y, por lo tanto, no se puede deshacer.*
```suggestion
*Advertencia: La eliminación de una cuenta es permanente y, por lo tanto, no se puede deshacer.*
```

2024-09-26 01:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Account/es.md
> +**Si tienes una etiqueta de supporter activa**, puedes ver todos los mapas en los que has enviado una puntuación accediendo al [listado de beatmaps](https://osu.ppy.sh/beatmapsets), haciendo clic en
```suggestion
**Si tienes una etiqueta de supporter activa**, puedes ver todos los mapas en los que has enviado una puntuación accediendo al [listado de beatmaps](https://osu.ppy.sh/beatmapsets), haciendo clic en `Más opciones de búsqueda` y seleccionando el filtro `Ya jugado`. Como alternativa, puedes acceder directamente a [la lista filtrada de beatmaps](https://osu.ppy.sh/beatmapsets?played=played).
```

2024-10-18 16:41 UTC, TicClick approved these changes

2024-10-18 16:41 UTC, merged