[ES] Add `Tournaments/Official support`
ppy/osu-wiki pull request #12150
Opened 2024-09-16 22:23 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-25 20:40 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-25 20:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournaments/Official_support/es.md
> +  - Los torneos que tengan un formato draft podrán funcionar con un bracket de doble eliminación de octavos de final siempre y cuando el torneo cumpla los siguientes criterios adicionales:
```suggestion
  - Los torneos que tengan un formato draft podrán funcionar con un bracket de doble eliminación de octavos de final, siempre y cuando el torneo cumpla los siguientes criterios adicionales:
```

2024-09-25 20:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournaments/Official_support/es.md
> +Si su torneo cumple los [criterios de elegibilidad](#eligibilidad), puedes hacer una solicitud de soporte enviando un correo electrónico al equipo de soporte de cuentas a través de [tournaments@ppy.s
```suggestion
Si tu torneo cumple los [criterios de elegibilidad](#eligibilidad), puedes hacer una solicitud de soporte enviando un correo electrónico al equipo de soporte de cuentas a través de [tournaments@ppy.sh](mailto:tournaments@ppy.sh) con la siguiente información:
```

2024-09-25 20:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournaments/Official_support/es.md
> +Una vez que recibamos su solicitud, el equipo de soporte de cuentas le devolverá una lista de los usuarios que no pueden participar en torneos. Por favor, espera un tiempo suficiente para recibir una
```suggestion
Una vez que recibamos tu solicitud, el equipo de soporte de cuentas te enviará una lista de los usuarios que no pueden participar en torneos. Por favor, espera un tiempo suficiente para recibir una respuesta. Haremos todo lo posible por atender todas las solicitudes en el plazo de una semana, pero de vez en cuando tenemos grandes picos de trabajo que pueden hacerlo imposible.
```

2024-09-25 20:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournaments/Official_support/es.md
> +- Si un usuario cumple los criterios de inscripción (si los hay) y no es [filtrado](#filtrado-y-agrupación-de-jugadores-registrados) por otros procedimientos, el torneo no deberá impedir la participa
```suggestion
- Si un usuario cumple los criterios de inscripción (si los hay) y no es [filtrado](#filtrado-y-agrupación-de-los-jugadores-registrados) por otros procedimientos, el torneo no deberá impedir la participación de aquellos que pasen la selección sin que se presenten públicamente amplias pruebas en su contra y sin la aprobación del equipo de soporte de cuentas.
```

2024-09-25 20:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournaments/Official_support/es.md
> +El filtrado de jugadores registrados, que no debe confundirse con el [proceso de selección](#proceso-de-selección), es el proceso de usar cualquier programa, algoritmo, fórmula matemática u otro medi
```suggestion
El filtrado de los jugadores registrados, que no debe confundirse con el [proceso de selección](#proceso-de-selección), es el proceso de usar cualquier programa, algoritmo, fórmula matemática u otro medio objetivo para eliminar de un torneo a los jugadores que de otro modo serían aptos. Esto se usa comúnmente para reducir la varianza en la habilidad dentro de un torneo, por ejemplo, con el [BWS](/wiki/Tournaments/Badge-weighted_seeding).
```

2024-09-25 20:40 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournaments/Official_support/es.md
> +  - Se podrán hacer excepciones a discreción del equipo de osu! y del comité de torneos dependiendo de varios factores, como el tamaño, el propósito, el alcance y el tamaño de los equipos de apoyo de
```suggestion
  - Se podrán hacer excepciones a discreción del osu! team y del comité de torneos dependiendo de varios factores, como el tamaño, el propósito, el alcance y el tamaño de los equipos de apoyo de un torneo determinado. Un buen ejemplo de este tipo de excepción sería un evento como The Roundtable.
```

2024-10-03 06:37 UTC, agatemosu commented on wiki/Tournaments/Official_support/es.md
> +- Los hilos del foro asociados con el torneo (incluidos los hilos de cualquier evento preliminar) **DEBEN** contener un enlace claramente visible en un tipo de letra de tamaño normal al [formulario d
```suggestion
- Los hilos del foro asociados con el torneo (incluidos los hilos de cualquier evento preliminar) **DEBEN** contener un enlace claramente visible en un tamaño de letra normal al [formulario de reportes de torneos](https://pif.ephemeral.ink/tournament-reports) como último contenido del mensaje original.
```

2024-10-03 06:41 UTC, agatemosu commented on wiki/Tournaments/Official_support/es.md
> +  - El hilo del foro situado en el [foro Tournaments](https://osu.ppy.sh/community/forums/55) que anuncia/detalla tu torneo.
```suggestion
  - El hilo situado en el [foro Tournaments](https://osu.ppy.sh/community/forums/55) que anuncia/detalla tu torneo.
```

2024-10-03 06:42 UTC, agatemosu commented on wiki/Tournaments/Official_support/es.md
> +Además, todo el material promocional o cualquier servicio asociado a un torneo que reciba soporte oficial deberá cumplir las [reglas de la comunidad de osu!](/wiki/Rules). Esto incluye cosas como cue
```suggestion
Además, todo el material promocional o cualquier servicio asociado a un torneo que reciba soporte oficial deberá cumplir las [reglas de la comunidad de osu!](/wiki/Rules). Esto incluye cosas como cuentas de Twitter, servidores de Discord, etc.
```

2024-10-03 06:47 UTC, agatemosu commented on wiki/Tournaments/Official_support/es.md
> +- Todos los partidos de un mismo grupo o fase de clasificación deben tener un formato igual. Por ejemplo, en un torneo con una fase de clasificación y un bracket de doble eliminación, todos los parti
```suggestion
- Todos los partidos de un mismo grupo o fase de clasificación deben tener un formato uniforme. Por ejemplo, en un torneo con una fase de clasificación y un bracket de doble eliminación, todos los partidos del bracket deben jugarse de forma sincrónica o asincrónica, pero no ambas.
```

2024-10-04 21:09 UTC, agatemosu approved these changes

2024-10-06 21:26 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-10-06 21:26 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournaments/Official_support/es.md
> +Este artículo se actualizó por última vez el 17 de agosto de 2024. Para consultar la lista completa de cambios, consulta el [hilo de actualizaciones sobre el soporte para torneos](https://osu.ppy.sh/
```suggestion
Este artículo se actualizó por última vez el 17 de agosto de 2024. Para ver la lista completa de cambios, consulta el [hilo de actualizaciones sobre el soporte oficial para torneos](https://osu.ppy.sh/community/forums/topics/1715676). Para cualquier duda o aclaración, consulta el canal `#tournaments` en el [servidor de Discord osu!](https://discord.com/invite/ppy) o envía un correo electrónico al [equipo de soporte de cuentas](/wiki/People/Account_support_team) a través de [tournaments@ppy.sh](mailto:tournaments@ppy.sh).
```

2024-10-06 21:33 UTC, Unnombredeusuarioextremadamentelargo approved these changes

2024-10-18 16:11 UTC, merged