[ES] Add `Help centre/Website`
ppy/osu-wiki pull request #12151
Opened 2024-09-16 22:23 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Website/es.md
> +En raras circunstancias, los tiquetes de soporte al usuario crónicamente ofensivos pueden ser ignorados a propósito, aunque el [equipo de soporte](/wiki/People/The_Team/Account_support_team) **siempr
```suggestion
En raras circunstancias, los tiquetes de soporte al usuario crónicamente ofensivos pueden ser ignorados a propósito, aunque el [equipo de soporte](/wiki/People/Account_support_team) **siempre** te dirá primero que ya no te responderá. Si no has recibido una notificación de este tipo, no tienes por qué preocuparte.
```

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Website/es.md
> +Ya no verás los mensajes de chat públicos de ningún usuario de esa lista, ni recibirás mensajes privados de ellos.
```suggestion
Ya no verás los mensajes públicos de los usuarios incluidos en esa lista ni recibirás mensajes privados de ellos.
```

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Website/es.md
> +#### Bloquear el envío de mensajes privados en el juego a quienes no sean amigos {id=ignore-strangers-in-game}
```suggestion
#### Cómo bloquear el envío de mensajes privados en el juego a quienes no sean amigos {id=ignore-strangers-in-game}
```

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Website/es.md
> +1. Haz clic en el botón `Options` del menú principal o pulsa `Ctrl` + `O`.
```suggestion
1. Haz clic en el botón `Options` del menú principal o presiona `Ctrl` + `O`.
```

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Website/es.md
> +2. Escribe `block` para filtrar el listado de opciones a la sección `Chat en juego`.
```suggestion
2. Escribe `bloquear` para filtrar el listado de opciones a la sección `Chat en juego`.
```

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Website/es.md
> +#### Bloquear a un usuario para que no se ponga en contacto contigo en el juego {id=ignore-user-in-game}
```suggestion
#### Cómo bloquear a un usuario para que no se ponga en contacto contigo en el juego {id=ignore-user-in-game}
```

2024-09-25 20:55 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Website/es.md
> +#### Evitar que te lleguen nuevos mensajes privados desde el sitio web {id=ignore-strangers-website}
```suggestion
#### Cómo evitar que te lleguen nuevos mensajes privados desde el sitio web {id=ignore-strangers-website}
```

2024-10-18 16:43 UTC, TicClick approved these changes

2024-10-18 16:43 UTC, merged