[ES] Update `Game mode/osu!taiko`
ppy/osu-wiki pull request #12162
Opened 2024-09-17 19:13 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-25 21:20 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-25 21:20 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Game_mode/osu!taiko/es.md
> +No incrementan el contador de combo, ni recupera la barra de salud de ninguna manera. Cada golpe de denden exitoso solo otorga una puntuación estática de 300, y la finalización del denden dará una no
```suggestion
No incrementan el contador del combo, ni recupera la barra de salud de ninguna manera. Cada golpe de denden exitoso solo otorga una puntuación estática de 300, y la finalización del denden dará una nota perfecta (GREAT).
```

2024-09-25 21:20 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Game_mode/osu!taiko/es.md
> +El mando de tambor *TaTaCon* se creó principalmente para las versiones caseras de *Taiko no Tatsujin* y *Taiko: Drum Master*, pero no es tan común en osu!taiko.
```suggestion
El mando *TaTaCon* se creó principalmente para las versiones caseras de *Taiko no Tatsujin* y *Taiko: Drum Master*, pero no es tan común en osu!taiko.
```

2024-10-18 16:00 UTC, TicClick approved these changes

2024-10-18 16:00 UTC, merged