[ZH] add history of osu!2008
ppy/osu-wiki pull request #12186
Opened 2024-09-22 10:21 UTC by jimmy-sketch

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-29 15:13 UTC, YumeMuzi requested changes
请继续修改。否则我不会通过。

Please go ahead and revise the entire writing. Otherwise I won't approve.

2024-09-29 15:13 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +![](img/2007-09_01.jpg "作图器中的滑块创建器")
```suggestion
![](img/2007-09_01.jpg "谱面编辑器中的滑条创建器")
```

能不能不要用机翻了？为什么不用统一的术语？
Can we stop using stupid translator? Why not use consistent terms?

2024-09-29 15:13 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +将音乐拖入osu!的窗口可以编辑它；主界面和制谱器中的每个按钮加入了对应的提示；一些新的优质皮肤由一些早期的[皮肤制作者](/wiki/Skinning/Skinner)([Holiday by LgigiHann](https://osu.ppy.sh/community/forums/topics/1139), [WindWaker by awp](https://osu.ppy.sh/co
```suggestion
将音乐拖入 osu! 窗口可以编辑它；主界面和谱面编辑器中的每个按钮加入了对应的提示；一些早期的[皮肤制作者](/wiki/Skinning/Skinner)制作了一些新的优质皮肤 ([Holiday by LgigiHann](https://osu.ppy.sh/community/forums/topics/1139), [WindWaker by awp](https://osu.ppy.sh/community/forums/topics/761))；选曲界面有了新的排序方式；peppy 可以给所有 osu! 玩家发公告；游玩模式做出了一些小更改（比如暗化未点击的音符）.
```

2024-09-29 15:13 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +[^2]:[论坛中peppy发的帖子（2007年8月28日）"pUpdater（又名osume）"](https://osu.ppy.sh/community/forums/topics/4?n=1)
```suggestion
[^2]: [论坛中，peppy 发的帖子（2007年8月28日）"pUpdater（又名osume）"](https://osu.ppy.sh/community/forums/topics/4?n=1)
```

2024-09-29 15:13 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +[^1]: [@ppy发的推特（2019年6月19日）](https://twitter.com/ppy/status/1141394137637249025?s=20)
```suggestion
[^1]: [@ppy 发的推特（2019年6月19日）](https://twitter.com/ppy/status/1141394137637249025?s=20)
```

2024-09-29 15:13 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +在2007年12月17日至2008年1月20日之间， peppy 在日本失踪了。他以某种方式离开了 osu! 的开发工作整整一个月，这也导致了这段时间内没有任何大更新。（当然，osu! 社区的发展在这段时间内也相当停滞）。
咱能加空格吗？？
Please add a space between English and Chinese

2024-09-29 15:13 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +本月，编辑器、多人游戏、故事板、图形和聊天控制台都得到了大量改进。 设置界面采用了新的布局，并引入了[自定义按键绑定](/wiki/Client/Options/Keyboard_bindings)功能。
```suggestion
本月，编辑器、多人游戏、故事板、图形和聊天控制台都得到了大量改进。设置界面采用了新的布局，并引入了[自定义按键绑定](/wiki/Client/Options/Keyboard_bindings)功能。
```

2024-09-29 15:13 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +像七月份一样，本月很难找到 osu! 没有改进或优化的方面。 在全新添加的内容方面，节拍图中添加了标签，并试验性地实现了多显示器支持。 一种新的取消暂停的方法，也就是要求玩家将光标对齐在暂停时光标的位置，被加入到游戏中。而其目的就是防止玩家滥用暂停功能。
为什么句号后有空格？您是用的全局替换吗？

Why is there a space after the period? Are you using a global replacement?

2024-09-29 15:22 UTC, jimmy-sketch commented on wiki/History_of_osu!/2007/zh.md
> +![](img/2007-09_01.jpg "作图器中的滑块创建器")
我在不同的地方看到了不同的对于 "beatmap editor"的不同翻译……
我可能有点弄混了

2024-09-29 15:29 UTC, jimmy-sketch commented on wiki/History_of_osu!/2008/zh.md
> +在2007年12月17日至2008年1月20日之间， peppy 在日本失踪了。他以某种方式离开了 osu! 的开发工作整整一个月，这也导致了这段时间内没有任何大更新。（当然，osu! 社区的发展在这段时间内也相当停滞）。
![屏幕截图 2024-09-29 232733](https://github.com/user-attachments/assets/f3c02e90-8737-4508-a265-58b0c4666320)
从我这里看是有空格的？

2024-11-06 14:14 UTC, jimmy-sketch commented
对于2007年的内容，我已经做出了一些适当的更改。

2024-11-07 08:09 UTC, YumeMuzi requested changes
我们很感谢您的翻译贡献，但是质量低的翻译是不可接受的...

We appreciate your translation contributions, but not sufficiently fluent translations with format/term errors are unacceptable...

2024-11-07 08:09 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +[提交谱面](/wiki/Beatmapping/Beatmap_submission)功能（BSS）对公众开放，使得用户可以轻松的上传、分享他们的劳动成果。而这也带来了[待定](/wiki/Beatmap/Category#wip-and-pending)和[已进榜](/wiki/Beatmap/Category#ranked)两个分类。它们有助于分类曲库中疯狂增长的用户上传的谱面。而游戏内的
```suggestion
[提交谱面](/wiki/Beatmapping/Beatmap_submission)功能（BSS）对公众开放，使得用户可以轻松的上传、分享他们的劳动成果。而这也带来了[待定](/wiki/Beatmap/Category#wip-and-pending)和[上架](/wiki/Beatmap/Category#ranked)两个分类。它们有助于分类曲库中疯狂增长的用户上传的谱面。而游戏内的聊天室则是一个从零搭起的 [IRC](/wiki/Community/Internet_Relay_Chat) (互联网中继聊天)客户端，并且连接到一个标准的不包含 [Bancho](/wiki/Bancho_(server)) 的 IRC 服务器；全局聊天是可见的；头像和用户的基本信息也在游戏中使用一种基于 http 的通讯方式显示出来；一个会在启动时自动随机播放一首歌的播放器也被加入主菜单；无论是本地的还是在线的[回放](/wiki/Gameplay/Replay)都可以被观看。同时，玩家们也可以旁观别的玩家（旁观者的数据会以未加密的形式通过 IRC 来发送）。
```

2024-11-07 08:09 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +在2007年12月17日至2008年1月20日之间， peppy 在日本失踪了。他以某种方式离开了 osu! 的开发工作整整一个月，这也导致了这段时间内没有任何大更新。（当然，osu! 社区的发展在这段时间内也相当停滞）。
```suggestion
在 2007 年 12 月 17 日至 2008 年 1 月 20 日之间， peppy 在日本失踪了。他以某种方式离开了 osu! 的开发工作整整一个月，这也导致了这段时间内没有任何大更新。（当然，osu! 社区的发展在这段时间内也相当停滞）。
```
..........英文和中文之间，数字和中文之间要加空格......

2024-11-07 08:09 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +尽管这需要对数据库进行相当大的优化，但选歌界面中终于加入了个人最佳成绩的显示，也满足了玩家们长期以来的要求。排名屏幕和默认皮肤的各种元素进行了图形改进，使其感觉比以前更加简洁明快。滑块得分精灵（10/30）的显示得以实现。多人游戏功能的设置得到了提升，并且允许转移房主。为了提升玩家们的便利性，许多新的[聊天命令](/wiki/Client/Interface/Chat_console#命令列表)
```suggestion
尽管这需要对数据库进行相当大的优化，但选歌界面中终于加入了个人最佳成绩的显示，也满足了玩家们长期以来的要求。排名屏幕和默认皮肤的各种元素进行了图形改进，使其感觉比以前更加简洁明快。滑条点分数 (10/30) 的显示得以实现。多人游戏功能的设置得到了提升，并且允许转移房主。为了提升玩家们的便利性，许多新的[聊天命令](/wiki/Client/Interface/Chat_console#命令列表)被加入。
```

滑块得分精灵？

2024-11-08 14:23 UTC, jimmy-sketch commented
我对07年和08年的又进行了一些修改。

2024-11-29 11:58 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +osu! 在最开始其实是一个叫做 “应援测试（ ouentest ）”[^ouentest] 的概念验证产品。它的第一个版本面向 [peppy](https://osu.ppy.sh/users/2) 的很小一部分挚友于 2007 年 7 月 1 日发布，包含一个简单的[谱面编辑器](/wiki/Client/Beatmap_editor)以及游玩谱面的功能。这个制谱器也只能创建*非常*基本的不
```suggestion
osu! 在最开始其实是一个叫做 “应援测试 (ouentest)”[^ouentest] 的概念验证产品。它的第一个版本面向 [peppy](https://osu.ppy.sh/users/2) 的很小一部分挚友于 2007 年 7 月 1 日发布，包含一个简单的[谱面编辑器](/wiki/Client/Beatmap_editor)以及游玩谱面的功能。这个制谱器也只能创建*非常*基本的不包含预览或者[网格对齐](/wiki/Disambiguation/Snapping)等诸如此类的功能，而游玩模式中的[谱面](/wiki/Beatmap)也没有滑条或者转盘，而只有最基本的普通音符以及分数和连击的计数器。第一个发布版只用了大概 16 个小时用于编码，并且它在*一个通宵*之内就完成了。`pUpdater`（也就是之后为人所知的 `osume`）[^osume]也跟着发布，用于负责将游戏自动更新至最新版本。
```

2024-11-29 16:25 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +Bancho 和[扩展聊天](/wiki/Client/Interface/Chat_console#扩展聊天面板)功能同时在四月份上线并不是一个愚人节玩笑。用户现在可以在自己的用户面板上看到其他用户在做什么，也可以通过点击旁观按钮与他们互动。自动错误提交系统首次亮相，xfire 兼容性得以实现，主菜单和谱面编辑器的界面也由 [LuigiHann](https://osu.ppy.sh/user
```suggestion
Bancho 和[扩展聊天](/wiki/Client/Interface/Chat_console#扩展聊天面板)功能同时在四月份上线。这并不是一个愚人节玩笑。用户现在可以在自己的用户面板上看到其他用户在做什么，也可以通过点击旁观按钮与他们互动。自动错误提交系统首次亮相，xfire 兼容性得以实现，主菜单和谱面编辑器的界面也添加了 [LuigiHann](https://osu.ppy.sh/users/1079) 制作的新图标，焕然一新。聊天界面新增了"显示聊天"按钮、标签自动补全和[昵称高亮](/wiki/Client/Interface/Chat_console/Highlight)提示。等级界面现在会显示达到下一等级所需的分数。
```

2024-11-29 16:25 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +![](img/taiko.png "Taiko Mod")
```suggestion
![](img/taiko.png "Taiko 模式")
```

2024-11-29 16:26 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +随着[多人游戏](/wiki/Client/Interface/Multiplayer)模式的加入，osu! 达到了一个重要的里程碑。皮肤选项在图形和声音方面都得到了进一步扩展。最后，跨频道聊天首次成为可能。
```suggestion
随着[多人游戏](/wiki/Client/Interface/Multiplayer)模式的加入，osu! 达到了一个重要的里程碑。皮肤的图形和声音设置方面都得到了进一步扩展。最后，跨频道聊天首次成为可能。
```

2024-11-29 16:27 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +像七月份一样，本月很难找到 osu! 没有改进的方面。从新功能方面来讲，谱面中添加了标签，并试验性地实现了多显示器支持。一种新的结束暂停的方法，也就是要求玩家将光标瞄准在暂停时光标的位置，为了防止玩家滥用暂停功能，而被加入到游戏中。
```suggestion
像七月份一样，本月很难找到 osu! 没有改进的方面。从新功能方面来讲，谱面中添加了标签，并试验性地实现了多显示器支持。添加一种新的暂停结束恢复游玩的方法，也就是要求玩家将光标瞄准在之前暂停时光标的位置，这是为了防止玩家滥用暂停功能，才被加入到游戏中。
```

2024-11-29 16:28 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +选歌界面中终于加入了个人最佳成绩的显示。这一功能的加入满足了玩家们长期以来的要求，也要求着对于数据库进行大量激进的优化。排名屏幕和默认皮肤的各种图形元素进行了改进，使其令人感觉比以前更加的简洁明快。滑条点得分（ 10 / 30 ）的显示得以实现。多人游戏房间的设置得到了改进，并且允许变更房主。为了提升玩家们的便利性，许多新的[聊天命令](/wiki/Client/Interface/Chat_c
```suggestion
选歌界面中终于加入了个人最佳成绩的显示。这一功能的加入满足了玩家们长期以来的要求，也要求着对于数据库进行大量激进的优化。排名屏幕和默认皮肤的各种图形元素进行了改进，让它的感觉比之前更加简洁明快。滑条点得分（10/30）的显示得以实现。多人游戏房间的设置得到了改进，并且允许变更房主。为了方便玩家使用，加入了许多新的[聊天命令](/wiki/Client/Interface/Chat_console#命令列表)。
```

2024-11-29 16:30 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +本月推出了一系列新的模组：[Flashlight](/wiki/Gameplay/Game_modifier/Flashlight)、[Spun Out](/wiki/Gameplay/Game_modifier/Spun_Out) 和 [Auto](/wiki/Gameplay/Game_modifier/Auto)。Auto 是一个人机，能以完美的[准确率](/wiki/Gameplay/A
```suggestion
本月推出了一系列新的模组：[Flashlight](/wiki/Gameplay/Game_modifier/Flashlight)、[Spun Out](/wiki/Gameplay/Game_modifier/Spun_Out) 和 [Auto](/wiki/Gameplay/Game_modifier/Auto)。Auto 是一个机器人，能以完美的[准确率](/wiki/Gameplay/Accuracy)完成（几乎）所有谱面，也可以通过编辑器试玩模式进入。通过添加更多可作为皮肤的一部分同时更换的元素（包括[连击提示 (Combo burst)](/wiki/Gameplay/Comboburst)图、默认的打击音、为单个滑块端点分配打击音的功能以及计时区间的继承部分），提高了作图的效果上限。选歌界面也做出了全面的更新。
```

2024-11-29 16:31 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +在私测中，OpenGL 实现和即将登场的游戏模式（[Catch the Beat](/wiki/Game_mode/osu!catch)）取得了进展。总共修改了 4000 多行代码，并且对 osu! 的许多内部功能都进行了重写。这只是为了使游戏模式更加模块化，同时也可以更方便地添加新的游戏模式。由于改动较大，十月份并没有公布更新。
```suggestion
在私测中，OpenGL 实现和即将登场的游戏模式（[Catch the Beat](/wiki/Game_mode/osu!catch)）取得了进展。总共修改了 4000 多行代码，并且重写了 osu! 的许多内部功能。这只是为了使游戏模式更加模块化，同时也可以更方便地添加新的游戏模式。由于改动较大，十月份并没有公布更新。
```

2024-11-29 16:31 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +由于下载了大量谱面的用户抱怨 osu！的加载时间太长，peppy 花了不少时间进行了极限的优化，从而使性能得到了令人难以想象的提高（大约提升了 9000 倍）。加载界面所需要时间从原来的一分钟以上缩短到了现在的几毫秒以内。
```suggestion
由于下载了大量谱面的用户抱怨 osu！的加载时间太长，peppy 花了不少时间作出极致的优化，从而使性能得到了令人难以想象的提高（大约提升了 9000 倍）。加载界面所需要时间从原来的一分钟以上缩短到了现在的几毫秒以内。
```

2024-11-29 16:32 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +在 2008 年的最后一个月， osu! 的开发有了不少的成果。在 osu! 历史中的第二个圣诞节，故事板编辑器的第一个版本得到改进，使得用户更容易使用故事板功能。第二个多人游戏模式被添加进来："鬼抓人"。这是一种合作模式，玩家轮流玩谱面。而多人游戏的另一个新增功能是 "准确率高者得胜利"。同时，游戏集成了 MSN 和雅虎状态，并且此时用户可以完全地自定义按键绑定和聊天高亮触发词。
tag coop? 这个是专有名词，不适合翻译

2024-11-29 16:34 UTC, YumeMuzi commented on wiki/History_of_osu!/2008/zh.md
> +[Hard rock](/wiki/Gameplay/Game_modifier/Hard_Rock)、[Sudden Death](/wiki/Gameplay/Game_modifier/Sudden_Death) 和 [Double Time](/wiki/Gameplay/Game_modifier/Double_Time) 这三个[模组](/wiki/Gameplay/Game_mod
```suggestion
[Hard rock](/wiki/Gameplay/Game_modifier/Hard_Rock)、[Sudden Death](/wiki/Gameplay/Game_modifier/Sudden_Death) 和 [Double Time](/wiki/Gameplay/Game_modifier/Double_Time) 这三个[模组](/wiki/Gameplay/Game_modifier)加入游戏，带给了玩家们更多的挑战。通过添加倒计时图像和声音、自定义连击数字和颜色、O/X（通过/失败）段落评价，对于每个计时部分的独立音量控制，以及（恐怕是最重要的）对于[使用脚本制作故事板](/wiki/Storyboard/Scripting)的支持等功能，游戏体验得到了极大的加强。曾有人试图将 osu! 转移到 XNAv2 框架上，但 peppy 认为这个新版本毫无用处，而且降低了整体性能。但是，从这时起，osu！开始使用根据 osu! 的需求进行了数千行重写和“修改”的 XNA1.1 框架。这个框架使得 osu! 成为了现在的样子。此外 osu! 还采用了新的文本渲染引擎，可以在任何大小的情况下显示非常清晰的字体。这样[谱面编辑器](/wiki/Client/Beatmap_editor)就可以现实更多信息；同时这个字体渲染引擎也使得游戏整体看起来更好。
```

2024-11-29 16:34 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +现在，将音乐拖入 osu! 的窗口就可以直接为它制作谱面；主界面和制谱器中的每个按钮都加入了与其相对应的提示；一些新的优质皮肤由一些早期的[皮肤制作者](/wiki/Skinning/Skinner)([Holiday by LgigiHann](https://osu.ppy.sh/community/forums/topics/1139), [WindWaker by awp](https:
```suggestion
现在，将音乐拖入 osu! 的窗口就可以直接为它制作谱面；主界面和作图器中的每个按钮都加入了与其相对应的提示；一些新的优质皮肤由一些早期的[皮肤制作者](/wiki/Skinning/Skinner)([Holiday by LgigiHann](https://osu.ppy.sh/community/forums/topics/1139), [WindWaker by awp](https://osu.ppy.sh/community/forums/topics/761))所提交；选曲界面有了新的排序方式；现在，peppy 可以给所有玩家发公告；游玩模式做出了一些小更改（比如给当前未处于被击打状态的打击圈添加暗化效果）。
```

2024-11-29 16:36 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +新的SS等级被加入了评分系统，用于替换在这之前达到AP的S级评分。 [No Video](/wiki/Gameplay/Game_modifier/No_Video) 和 [Hidden](/wiki/Gameplay/Game_modifier/Hidden) 两个模组和配套的 SH (银 S )和 SSH（银 SS ）两个等级加入游戏。也是第一次，玩家们可以基于每一段计时部分来进行换肤。现在
```suggestion
新的 SS 评价被加入了评分系统，用于替换在这之前达到完美的 S 级评价。 [No Video](/wiki/Gameplay/Game_modifier/No_Video) 和 [Hidden](/wiki/Gameplay/Game_modifier/Hidden) 两个模组和配套的 SH (银 S) 和 SSH (银 SS) 两个评价加入游戏。也是第一次，玩家们可以基于每一段计时部分来切换皮肤。现在可以通过双击或将其拖动到 osu! 的图标或窗口中来加载 `.osz` 谱面。
```

2024-11-29 16:36 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +而选曲界面则有了两个改进：一个是基于难度的分组方式，一个是看起来更加直观的“轮式选曲”的动画。软件示例集、基于键盘的控制方式和游戏内搜索在这个月中加入。玩家们首次可以制作全局[皮肤](/wiki/Skinning)和对于特定谱面的皮肤。同时，对于平板（触屏）电脑的完整支持也得到了实现。
```suggestion
而选曲界面则有了两个改进：一个是基于难度的分组方式，一个是看起来更加直观的“滚轮式”选图动画。软件示例集、基于键盘的控制方式和游戏内搜索在这个月中加入。玩家们首次可以制作全局[皮肤](/wiki/Skinning)和对于特定谱面的皮肤。同时，对于平板（触屏）电脑的完整支持也得到了实现。
```

2024-11-29 16:37 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +2007年9月17日是 osu! 被大众所公认的"生日"。我们今日所熟知的论坛在此日开通，并且托管于 peppy 的主域名(  `ppy.sh`  )。[这条新闻](https://web.archive.org/web/20071221020801/http://www.bemanistyle.com/index.php?news_id=483)被一家叫做 [bemanstyle](http:
```suggestion
2007 年 9 月 17 日是 osu! 被大众所公认的"生日"。我们今日所熟知的论坛在此日开通，并且托管于 peppy 的主域名(  `ppy.sh`)。[这条新闻](https://web.archive.org/web/20071221020801/http://www.bemanistyle.com/index.php?news_id=483)被一家叫做 [bemanstyle](http://bemanistyle.com/) 的媒体发现并且发布了出来，而这条新闻则吸引了一些些对这有兴趣的音游玩家的注意力。
```

2024-11-29 16:37 UTC, YumeMuzi commented on wiki/History_of_osu!/2007/zh.md
> +[连击特效](/wiki/Gameplay/Combo_fire)、[血量](/wiki/Gameplay/Health)条、鼠标尾迹和更好看的滑条使游戏体验得到了加强。此时，osu! 已经有了一个由一个五人测试团队所制作的大约 10 张谱面所组成的一个谱面库。
```suggestion
[连击特效](/wiki/Gameplay/Combo_fire)、[血量](/wiki/Gameplay/Health)条、鼠标尾迹和更好看的滑条改良了游戏体验。此时，osu! 已经有了一个由一个五人测试团队所制作的大约 10 张谱面所组成的一个谱面库。
```

2024-11-29 22:38 UTC, jimmy-sketch commented on wiki/History_of_osu!/2007/zh.md
> +现在，将音乐拖入 osu! 的窗口就可以直接为它制作谱面；主界面和制谱器中的每个按钮都加入了与其相对应的提示；一些新的优质皮肤由一些早期的[皮肤制作者](/wiki/Skinning/Skinner)([Holiday by LgigiHann](https://osu.ppy.sh/community/forums/topics/1139), [WindWaker by awp](https:
所以谱面编辑器的简称是`作图器`？
这有点怪吧…`制谱器`真的不行？

2024-11-30 00:25 UTC, jimmy-sketch commented on wiki/History_of_osu!/2008/zh.md
> +在 2008 年的最后一个月， osu! 的开发有了不少的成果。在 osu! 历史中的第二个圣诞节，故事板编辑器的第一个版本得到改进，使得用户更容易使用故事板功能。第二个多人游戏模式被添加进来："鬼抓人"。这是一种合作模式，玩家轮流玩谱面。而多人游戏的另一个新增功能是 "准确率高者得胜利"。同时，游戏集成了 MSN 和雅虎状态，并且此时用户可以完全地自定义按键绑定和聊天高亮触发词。
所以直接保留原文即可？

2024-12-16 13:33 UTC, TicClick approved these changes

2024-12-16 13:35 UTC, merged