[ES] Add `Gameplay/Replay`
ppy/osu-wiki pull request #12199
Opened 2024-09-24 01:09 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-29 23:23 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-29 23:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Gameplay/Replay/es.md
> +En la pantalla de fin del juego, presiona la tecla `F1` para repetir la jugada fallida.
```suggestion
En la pantalla de fin del juego, presiona la tecla `F1` para ver la repetición de la jugada fallida.
```

2024-09-29 23:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Gameplay/Replay/es.md
> +Asegúrate de tener la **misma** dificultad/beatmap que el jugador, o aparecerá un pequeño recuadro rojo de advertencia en la parte inferior derecha por no tener la dificultad/beatmap especificado, po
```suggestion
Asegúrate de tener la **misma** dificultad/beatmap que el jugador, o aparecerá un pequeño recuadro rojo de advertencia en la parte inferior derecha por no tener la dificultad/beatmap especificado, por lo que no habrá una repetición para el espectador.
```

2024-09-29 23:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Gameplay/Replay/es.md
> +Las repeticiones en el servidor están reservadas para las 50 mejores puntuaciones en la tabla de clasificación global de una dificultad/beatmap.
```suggestion
Las repeticiones en el servidor están reservadas para las 1000 mejores puntuaciones en la tabla de clasificación global de una dificultad/beatmap.
```

2024-09-29 23:23 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Gameplay/Replay/es.md
> +Si se añade una nueva puntuación en el top 50 global, se eliminará la repetición del servidor del anterior poseedor de la posición \#50.
```suggestion
Si se añade una nueva puntuación en el puesto 1000 global, se eliminará la repetición del servidor del anterior poseedor de la posición \#1000.
```

2024-10-18 16:30 UTC, TicClick approved these changes

2024-10-18 16:30 UTC, merged