Disambiguation it 1-8
ppy/osu-wiki pull request #12194
Opened 2024-09-22 21:20 UTC by G3ntl3m4n10

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-22 22:09 UTC, hhacki requested changes

2024-09-22 22:09 UTC, hhacki commented on wiki/Disambiguation/Combo/it.md
> +- Una [breve catena di oggetti colpiti](/wiki/Beatmapping/Combo) che condividono lo stesso [colore](/wiki/Beatmapping/Combo_colour)
```suggestion
- Una [breve catena di oggetti](/wiki/Beatmapping/Combo) che condividono lo stesso [colore](/wiki/Beatmapping/Combo_colour)
```

2024-09-22 22:09 UTC, hhacki commented on wiki/Disambiguation/Combo/it.md
> +- Il [moltiplicatore di punteggio attivo](/wiki/Gameplay/Combo_(score_multiplier)) visibile durante il gameplay, o il numero di oggetti colpiti di seguito senza sbagliare
```suggestion
- Il [moltiplicatore di punteggio](/wiki/Gameplay/Combo_(score_multiplier)) visibile durante il gameplay, o il numero di oggetti colpiti di seguito senza sbagliare  
```

2024-09-22 22:09 UTC, hhacki commented on wiki/Disambiguation/Mod/it.md
> +- Un moderatore, come un membro [NAT](/wiki/People/Nomination_Assessment_Team) o[GMT](/wiki/People/Global_Moderation_Team)
```suggestion
- Un moderatore, come un membro del [NAT](/wiki/People/Nomination_Assessment_Team) o del [GMT](/wiki/People/Global_Moderation_Team) 
```

2024-09-22 22:09 UTC, hhacki commented on wiki/Disambiguation/Mod/it.md
> +- [Un feedback](/wiki/Modding) dato da una persona che guarda una beatmap
```suggestion
- [Il feedback](/wiki/Modding) dato da una persona che revisiona una beatmap
```

2024-09-22 22:13 UTC, hhacki requested changes

2024-09-22 22:13 UTC, hhacki commented on wiki/Disambiguation/NM/it.md
> +- [Modalità normale](/wiki/Modding/Normal_mod)
```suggestion
- [Mod normale](/wiki/Modding/Normal_mod)
```

2024-09-22 22:13 UTC, hhacki commented on wiki/Disambiguation/NM/it.md
> +- La [ddifficoltà](/wiki/Beatmap/Difficulty) di una beatmap:
```suggestion
- La [difficoltà](/wiki/Beatmap/Difficulty) di una beatmap:
```

2024-09-22 22:20 UTC, hhacki commented on wiki/Disambiguation/NC/it.md
> +- [La modalità Nightcore ](/wiki/Gameplay/Game_modifier/Nightcore)
```suggestion
- [La mod Nightcore ](/wiki/Gameplay/Game_modifier/Nightcore)
```

2024-09-22 22:36 UTC, hhacki requested changes
fix remark

2024-09-22 22:36 UTC, hhacki commented on wiki/Disambiguation/NC/it.md
> +- [La mod Nightcore ](/wiki/Gameplay/Game_modifier/Nightcore)
```suggestion
- [La mod Nightcore](/wiki/Gameplay/Game_modifier/Nightcore)
```

2024-09-22 22:36 UTC, hhacki commented on wiki/Disambiguation/NM/it.md
> +  - ![](/wiki/shared/diff/normal-c.png?20211215) Salad, per osu!catch.
```suggestion
  - ![](/wiki/shared/diff/normal-c.png?20211215) Salad, per osu!catch.
  
```

2024-09-22 23:11 UTC, hhacki requested changes

2024-09-22 23:28 UTC, hhacki approved these changes
lgtm

2024-09-26 18:03 UTC, TicClick approved these changes

2024-09-26 18:03 UTC, merged