[ES] Add `Tournament drawings`
ppy/osu-wiki pull request #12196
Opened 2024-09-24 01:08 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-29 22:27 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-29 22:27 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournament_drawings/es.md
> +  - Esto iniciará el proceso de aleatorización, haciendo que las banderas de la pantalla se desplacen.
```suggestion
  - Este iniciará el proceso de aleatorización, haciendo que las banderas de la pantalla se desplacen.
```

2024-09-29 22:27 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournament_drawings/es.md
> +  - Esto detendrá el proceso de aleatorización, haciendo que el desplazamiento se ralentice hasta que finalmente se detenga y se centre en una bandera en el centro de la pantalla.
```suggestion
  - Este detendrá el proceso de aleatorización, haciendo que el desplazamiento se ralentice hasta que finalmente se detenga y se centre en una bandera en el centro de la pantalla.
```

2024-09-29 22:27 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Tournament_drawings/es.md
> +  - Esto recargará el archivo `drawings.txt`.
```suggestion
  - Este recargará el archivo `drawings.txt`.
```

2024-10-18 16:35 UTC, TicClick approved these changes

2024-10-18 16:35 UTC, merged