[ES] Add `Beatmapping/Mapping techniques/Formations`
ppy/osu-wiki pull request #12202
Opened 2024-09-24 01:09 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-30 00:27 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-30 00:27 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Formations/es.md
> +*También conocido como: **Formación blanket***
```suggestion
*También conocidos como: **Formación blanket***
```

2024-09-30 00:27 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Formations/es.md
> +*También conocido como: **Formación con estilo de flor***
```suggestion
*También conocidos como: **Formación con estilo de flor***
```

2024-09-30 00:27 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Formations/es.md
> +*También conocido como: **Formación triangular***
```suggestion
*También conocidos como: **Formación triangular***
```

2024-09-30 00:27 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Formations/es.md
> +*También conocido como: **Formación zigzag***
```suggestion
*También conocidos como: **Formación zigzag***
```

2024-10-18 16:24 UTC, TicClick approved these changes

2024-10-18 16:24 UTC, merged