[ES] Add `Community/Projects`
ppy/osu-wiki pull request #12200
Opened 2024-09-24 01:09 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-29 23:38 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-29 23:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Projects/es.md
> +- [osu! (OS X)](https://osu.ppy.sh/community/forums/topics/56460) — osu! on OS X (results will vary).
```suggestion
- [osu! (OS X)](https://osu.ppy.sh/community/forums/topics/56460) — osu! en OS X (los resultados pueden variar).
```

2024-09-29 23:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Projects/es.md
> +- [osu!StreamCompanion](https://osu.ppy.sh/community/forums/topics/209616) — extractor de información de osu! para streamers en vivo.
```suggestion
- [osu!StreamCompanion](https://osu.ppy.sh/community/forums/topics/209616) — Extractor de información de osu! para streamers en vivo.
```

2024-09-29 23:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Projects/es.md
> +- [OMISM](https://osu.ppy.sh/community/forums/topics/664319) — Un conversor de beatmaps de osu!mania a Stepmania (y un copiador de keysound de osu!mania).
```suggestion
- [OMISM](https://osu.ppy.sh/community/forums/topics/664319) — Un conversor de beatmaps de osu!mania a Stepmania (y un copiador de keysounds de osu!mania).
```

2024-09-29 23:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Projects/es.md
> +- [osu!HitsoundManager](https://osu.ppy.sh/community/forums/topics/385832) — Una herramienta de hitsounding para osu!mania que copia archivos de hitsound y volumen de los objetos a los objetos y stor
```suggestion
- [osu!HitsoundManager](https://osu.ppy.sh/community/forums/topics/385832) — Una herramienta de hitsounding para osu!mania que copia archivos de hitsounds y volumen de los objetos a los objetos y storyboards. Originalmente llamado osu!MagiCopy.
```

2024-09-29 23:38 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Community/Projects/es.md
> +- [Mapset Verifier](https://osu.ppy.sh/community/forums/topics/943895) — Automatizar la detección de problemas según los [criterios de clasificación](/wiki/Ranking_criteria).
```suggestion
- [Mapset Verifier](https://osu.ppy.sh/community/forums/topics/943895) — Automatiza la detección de problemas según los [criterios de clasificación](/wiki/Ranking_criteria).
```

2024-10-18 16:28 UTC, TicClick approved these changes

2024-10-18 16:28 UTC, merged