[ES] Add `Beatmapping/Mapping techniques/Basics`
ppy/osu-wiki pull request #12201
Opened 2024-09-24 01:09 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-30 00:15 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-30 00:15 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Basics/es.md
> +Si un jugador quiere referirse a un stream de objetos con una separación de medio pulso entre sí, lo suele llamar «1/2 stream».
```suggestion
Si un jugador quiere referirse a un stream de objetos con una separación de medio pulso entre sí, lo suele llamar «stream de 1/2».
```

2024-09-30 00:15 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Basics/es.md
> +Deberías notar que los instrumentos frecuentemente tienen 3 notas separadas 1/4 una de la otra.
```suggestion
Deberías notar que los instrumentos frecuentemente tienen 3 notas separadas a 1/4 una de la otra.
```

2024-10-18 16:26 UTC, TicClick approved these changes

2024-10-18 16:26 UTC, merged