[ES] Add `Beatmapping/Mapping techniques/Sliders`
ppy/osu-wiki pull request #12206
Opened 2024-09-24 01:09 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-30 01:13 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-30 01:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Sliders/es.md
> +Suelen hacerse con [sliders de Etna](#sliders-de-etna), pero también pueden usarse con sliders de 3 a 4 o más pulsos de duración.
```suggestion
Suelen hacerse con [sliders de Etna](#sliders-de-etna), pero también pueden usarse con sliders de 3, 4 o más pulsos de duración.
```

2024-09-30 01:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Sliders/es.md
> +*No debe confundirse con los [sliders mantenidos](/wiki/Beatmapping/Mapping_techniques/Unrankable#sliders-mantenidos).*
```suggestion
*No deben confundirse con los [sliders mantenidos](/wiki/Beatmapping/Mapping_techniques/Unrankable#sliders-mantenidos).*
```

2024-09-30 01:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Sliders/es.md
> +### Crumpled Sliders
```suggestion
### Sliders arrugados
```

2024-09-30 01:13 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Sliders/es.md
> +Los sliders **switch-back** están formados por un slider curvo de medio pulso.
```suggestion
Los **sliders switch-back** están formados por un slider curvo de medio pulso.
```

2024-09-30 16:50 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-30 16:50 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Sliders/es.md
> +### Sliders con forma de molino de viento
```suggestion
### Sliders en forma de molino de viento
```

2024-09-30 16:50 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/Sliders/es.md
> +Un **slider con forma de molino de viento** es una serie de cuatro sliders que parten de un punto central común.
```suggestion
Los **slider en forma de molino de viento** son una serie de cuatro sliders que parten de un punto central común.
```

2024-10-18 16:17 UTC, TicClick approved these changes

2024-10-18 16:17 UTC, merged