[ES] Add `Beatmapping/Mapping techniques`
ppy/osu-wiki pull request #12209
Opened 2024-09-24 01:10 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-30 16:51 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-30 16:51 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/es.md
> +- [Spider Sliders](Sliders#spider-sliders)
```suggestion
- [Sliders en forma de araña](Sliders#sliders-en-forma-de-araña)
```

2024-09-30 16:51 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/es.md
> +- [Sliders en forma de araña](Sliders#sliders-en-forma-de-araña)
```suggestion
- [Sliders en espiral](Sliders#sliders-en-espiral)
```

2024-09-30 16:51 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmapping/Mapping_techniques/es.md
> +- [Sliders con forma de molino de viento](Sliders#sliders-con-forma-de-molino-de-viento)
```suggestion
- [Sliders en forma de molino de viento](Sliders#sliders-en-forma-de-molino-de-viento)
```

2024-10-18 16:15 UTC, TicClick approved these changes

2024-10-18 16:15 UTC, merged