[ES] Add `Help centre/Store/Store archive`
ppy/osu-wiki pull request #12232
Opened 2024-09-27 17:19 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-09-30 16:59 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-09-30 16:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Store/Store_archive/es.md
> +Si tiene algún otro problema, no dudes en enviar un tiquete a [support@ppy.sh](mailto:support@ppy.sh) detallando tu problema.
```suggestion
Si tienes algún otro problema, no dudes en enviar un tiquete a [support@ppy.sh](mailto:support@ppy.sh) detallando tu problema.
```

2024-09-30 16:59 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Help_centre/Store/Store_archive/es.md
> +Descomprime el archivo que te pedimos que descargaras antes (osu!go.zip) en la unidad osu!go y ¡listo!
```suggestion
Descomprime el archivo que te pedimos que descargaras antes (osu!go.zip) en la unidad osu!go y ya habrás terminado.
```

2024-10-18 16:13 UTC, TicClick approved these changes

2024-10-18 16:13 UTC, merged