Add COE x Yuki Aim 2024 1v1 Tournament article
ppy/osu-wiki pull request #12267
Opened 2024-10-04 03:00 UTC by ThePooN

Added the wiki page for the COE x Yuki Aim 2024 1v1 tournament.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-10-04 08:23 UTC, iSlodinxOsu requested changes

2024-10-04 08:23 UTC, iSlodinxOsu commented on wiki/Tournaments/COE/COE_2024/en.md
> +The COE x Yuki Aim 2024 1v1 Tournament offered a total cash prize pool of 3350€, keyboards provided by [Wooting](https://wooting.io/) and several merch from Yuki Aim, including stickers, posters, gla
```suggestion
The COE x Yuki Aim 2024 1v1 Tournament offered a total cash prize pool of 3350€, keyboards provided by [Wooting](https://wooting.io/) and several merch from [Yuki Aim](https://yuki.gg/), including stickers, posters, glasspad / clothpad
```

2024-10-04 08:23 UTC, iSlodinxOsu commented on wiki/Tournaments/COE/COE_2024/en.md
> +| Mapper | ::{ flag=HK }:: [Kurashina Asuka](https://osu.ppy.sh/users/7476493), ::{ flag=SK }:: [Atipir](https://osu.ppy.sh/users/8991722), ::{ flag=UK }:: [DeviousPanda](https://osu.ppy.sh/users/496
```suggestion
| Mapper | ::{ flag=HK }:: [Kurashina Asuka](https://osu.ppy.sh/users/7476493), ::{ flag=SK }:: [Atipir](https://osu.ppy.sh/users/8991722), ::{ flag=GB }:: [DeviousPanda](https://osu.ppy.sh/users/4966334), ::{ flag=EE }:: [iljaaz](https://osu.ppy.sh/users/8501291), ::{ flag=AT }:: [Seamob](https://osu.ppy.sh/users/10840806) |
```

2024-10-04 08:23 UTC, iSlodinxOsu commented on wiki/Tournaments/COE/COE_2024/en.md
> +| Commentator | ::{ flag=UK }:: [Bubbleman](https://osu.ppy.sh/users/5182050), ::{ flag=US }:: [ChillierPear](https://osu.ppy.sh/users/9501251),  ::{ flag=GB }:: [Doomsday](https://osu.ppy.sh/users/1
```suggestion
| Commentator | ::{ flag=GB }:: [Bubbleman](https://osu.ppy.sh/users/5182050), ::{ flag=US }:: [ChillierPear](https://osu.ppy.sh/users/9501251),  ::{ flag=GB }:: [Doomsday](https://osu.ppy.sh/users/18983), ::{ flag=NO }:: [NINERIK](https://osu.ppy.sh/users/10549880), ::{ flag=GB }:: [Malteser](https://osu.ppy.sh/users/5218178), ::{ flag=US }:: [n3rdiness](https://osu.ppy.sh/users/16537481), ::{ flag=DE }:: [himejoshi](https://osu.ppy.sh/users/6754508), ::{ flag=GB }:: [SadShiba](https://osu.ppy.sh/users/10747626), ::{ flag=IT }:: [Spazza17](https://osu.ppy.sh/users/3516241), ::{ flag=MK }:: [sst3w](https://osu.ppy.sh/users/13337202) |
```

2024-10-04 08:27 UTC, iSlodinxOsu commented on wiki/Tournaments/COE/COE_2024/en.md
> +The COE x Yuki Aim 2024 1v1 Tournament offered a total cash prize pool of 3350€, keyboards provided by [Wooting](https://wooting.io/) and several merch from Yuki Aim, including stickers, posters, gla
I guess this should be fine to link their website aswell?

2024-10-05 18:26 UTC, Joehuu commented
Needs to be added to tournament index.

2024-10-08 17:10 UTC, Joehuu commented on wiki/Tournaments/COE/en.md
> +- [COE x Yuki Aim 2024 1v1 Tournament 2024](COE_2024)
```suggestion
- [COE x Yuki Aim 2024 1v1 Tournament](COE_2024)
```

2024-10-09 23:03 UTC, ThePooN commented
Regarding the badges and banners, I rebased this MR and edited the original commits in order not to inflate the repo, given it's not using Git LFS.

2024-10-09 23:52 UTC, Joehuu reviewed
Not gonna nitpick the ruleset as much. Seems fine.

2024-10-09 23:52 UTC, Joehuu commented on wiki/Tournaments/COE/COE_2024/en.md
> +### 5\. Code of Conduc
```suggestion
### 5\. Code of Conduct
```

2024-10-09 23:52 UTC, Joehuu approved these changes

2024-10-11 22:26 UTC, merged

2024-10-12 01:59 UTC, ThePooN commented
Thanks @iSlodinxOsu and @Joehuu for the reviews and merge.

IMHO, I think some improvements could be done to the scripts and workflows to facilitate this process. Had no idea about the indexes, getting dates to match and properly formatted on every page was a nightmare, could add checks for image dimensions. I had actually bothered to set up and run the scripts and feel a little betrayed :stuck_out_tongue: