[ES] Update `osu! originals`
ppy/osu-wiki pull request #12273
Opened 2024-10-05 04:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-10-05 16:10 UTC, agatemosu commented on wiki/osu!_originals/es.md
> +| [![SoundCloud](/wiki/shared/link/SoundCloud.png)](https://soundcloud.com/nekodex/welcome-to-osu "SoundCloud") |  | nekodex - welcome to osu\![^fa] | Tema antiguo de osu! |
```suggestion
| [![SoundCloud](/wiki/shared/link/SoundCloud.png)](https://soundcloud.com/nekodex/welcome-to-osu "SoundCloud") |  | nekodex - welcome to osu\![^fa] | Antiguo tema de osu! |
```

2024-10-05 16:15 UTC, agatemosu commented on wiki/osu!_originals/es.md
> +| [![SoundCloud](/wiki/shared/link/SoundCloud.png)](https://soundcloud.com/ii-l/ufo3 "SoundCloud") [![YouTube](/wiki/shared/link/YouTube.png)](https://www.youtube.com/watch?v=vhsfT7PCp8A "YouTube") [
pon gran final como antes

2024-10-13 04:00 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-10-13 04:11 UTC, Unnombredeusuarioextremadamentelargo approved these changes

2024-10-18 15:48 UTC, TicClick approved these changes

2024-10-18 15:48 UTC, merged