[ES] Add `Contests/Contest points`
ppy/osu-wiki pull request #12281
Opened 2024-10-06 20:09 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-10-13 03:50 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-10-13 03:50 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Contests/Contest_points/es.md
> +## Puntos clave
```suggestion
## Distribución de los puntos
```

2024-10-13 03:50 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Contests/Contest_points/es.md
> +Para los concursos individuales, los puntos se basan en el número de envíos válidos creados. Estas son las pautas generales para la distribución de puntos, y se pueden hacer excepciones dependiendo d
```suggestion
Para los concursos individuales, los puntos se basan en el número de envíos válidos creados. Estas son las pautas generales para la distribución de los puntos, y se pueden hacer excepciones dependiendo de cada caso y a discreción del [comité de concursos](/wiki/People/Tournament_Committee#comité-de-concursos) cuando se solicite soporte oficial para concursos de beatmapping.
```

2024-10-13 03:50 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Contests/Contest_points/es.md
> +A partir de enero de 2023, la elegibilidad para los puntos de los concursos se ha perfilado en base a los [puntos clave](#puntos-clave). Los puntos obtenidos antes de este cambio no se ajustarán.
```suggestion
A partir de enero de 2023, la elegibilidad para los puntos de los concursos se ha perfilado en base a la [distribución de los puntos](#distribución-de-los-puntos). Los puntos obtenidos antes de este cambio no se ajustarán.
```

2024-10-18 15:50 UTC, TicClick approved these changes

2024-10-18 15:50 UTC, merged