[ES] Add `Contests/Official support`
ppy/osu-wiki pull request #12282
Opened 2024-10-06 21:28 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-10-13 03:41 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-10-13 03:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Contests/Official_support/es.md
> +Este artículo se actualizó por última vez el 30 de septiembre de 2024. Para ver la lista completa de cambios, consulta el hilo de [actualizaciones sobre el soporte para concursos de beatmapping](http
```suggestion
Este artículo se actualizó por última vez el 30 de septiembre de 2024. Para ver la lista completa de cambios, consulta el hilo de [actualizaciones sobre el soporte oficial para concursos de beatmapping](https://osu.ppy.sh/community/forums/topics/1907886). Para cualquier duda o aclaración, consulta el canal `#tournaments` en el [servidor de Discord osu!](https://discord.com/invite/ppy) o envía un correo electrónico al [equipo de soporte de cuentas](/wiki/People/Account_support_team) a través de [tournaments@ppy.sh](mailto:tournaments@ppy.sh).
```

2024-10-13 03:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Contests/Official_support/es.md
> +Los premios en forma de insignia de perfil deben solicitarse como máximo dos meses después de la finalización del concurso. **Las insignias no se aprobarán hasta después de la finalización del concur
```suggestion
Los premios en forma de insignia de perfil deben solicitarse como máximo dos meses después de la finalización del concurso. **Las insignias no se aprobarán hasta después de la conclusión del concurso.**
```

2024-10-13 03:41 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Contests/Official_support/es.md
> +Para las noticias, la creación de listas para los concursos o cualquier otra consulta, ponte en contacto con nosotros lo antes posible antes de las inscripciones, idealmente con al menos un mes de an
```suggestion
Para las noticias, la creación de las listas para los concursos o cualquier otra consulta, ponte en contacto con nosotros lo antes posible antes de las inscripciones, idealmente con al menos un mes de antelación, para que tengamos tiempo de considerarlo.
```

2024-10-18 15:52 UTC, TicClick approved these changes

2024-10-18 15:52 UTC, merged