[ES] Add `Past osu!store items`
ppy/osu-wiki pull request #12293
Opened 2024-10-08 19:56 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-10-13 03:32 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-10-13 03:32 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Past_osu!store_items/es.md
> +*Para conocer los pasos de solución de los problemas relacionados con el producto, véase: [Archivo de la osu!store § osu!tablet](/wiki/Help_centre/Store/Store_archive#osu-tablet)*
```suggestion
*Para conocer los pasos a seguir para solucionar los problemas relacionados con el producto, véase: [Archivo de la osu!store § osu!tablet](/wiki/Help_centre/Store/Store_archive#osu-tablet)*
```

2024-10-13 03:32 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Past_osu!store_items/es.md
> +Los **planos para crear beatmaps de osu!** eran un conjunto de pegatinas reutilizables con varios elementos del juego, como círculos, sliders, círculos de aproximación, [juicios](/wiki/Gameplay/Judge
```suggestion
Los **planos para crear beatmaps de osu!** eran un conjunto de pegatinas reutilizables con varios elementos del juego, como círculos, sliders, círculos de aproximación, [juicios](/wiki/Gameplay/Judgement/osu!) y el propio logo de osu!. El producto se vendió en 2015 como un medio para que los usuarios crearan «beatmaps a tamaño real en la vida real».
```

2024-10-13 03:32 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Past_osu!store_items/es.md
> +*Para conocer los pasos de solución de los problemas relacionados con el producto, véase: [Archivo de la osu!store § osu!keyboard](/wiki/Help_centre/Store/Store_archive#osu!keyboard)*
```suggestion
*Para conocer los pasos a seguir para solucionar los problemas relacionados con el producto, véase: [Archivo de la osu!store § osu!keyboard](/wiki/Help_centre/Store/Store_archive#osu!keyboard)*
```

2024-10-13 03:32 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Past_osu!store_items/es.md
> +*Para conocer los pasos de solución de los problemas relacionados con el producto, véase [Archivo de la osu!store § osu!go](/wiki/Help_centre/Store/Store_archive#osu!go)*
```suggestion
*Para conocer los pasos a seguir para solucionar los problemas relacionados con el producto, véase: [Archivo de la osu!store § osu!go](/wiki/Help_centre/Store/Store_archive#osu!go)*
```

2024-10-18 15:54 UTC, TicClick approved these changes

2024-10-18 15:54 UTC, merged