[ZH] Update `BanchoBot` and `Bancho (server)`
ppy/osu-wiki pull request #12308
Opened 2024-10-14 07:50 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-10-20 07:07 UTC, SamHou0 requested changes

2024-10-20 07:07 UTC, SamHou0 commented on wiki/Bancho_(server)/zh.md
>  # Bancho (游戏服务器)
这里原文特意把 game 去掉了，翻译是不是也去掉游戏比较好（或许功能不止提供游戏服务？）
```suggestion
# Bancho （服务器）
```

2024-10-20 07:07 UTC, SamHou0 commented on wiki/Bancho_(server)/zh.md
> +![](img/connection-warning.png "连接状态不佳时，主菜单截图（右下角最左端图标）")
```suggestion
![](img/connection-warning.png "连接状态不佳时，主菜单截图（右下角左数第一个图标）")
```
`右下角最左端`感觉不太清晰，换成和原文意思一样的左数第一个比较好

2024-10-21 11:00 UTC, SamHou0 approved these changes

2024-10-22 18:21 UTC, RushFTK approved these changes

2024-11-26 22:48 UTC, Hiviexd approved these changes

2024-11-26 22:50 UTC, merged