[DE] Add `Past osu!store items`
ppy/osu-wiki pull request #12352
Opened 2024-10-25 18:22 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-10-25 22:48 UTC, The-Last-Cookie commented on wiki/Past_osu!store_items/de.md
> +In diesem Artikel werden verschiedene Produkte gezeigt, die mal im [osu!store](https://osu.ppy.sh/store/listing) verfügbar waren, mittlerweile aber nicht mehr produziert werden und auch nicht zum Ver
```suggestion
Auf dieser Seite werden verschiedene Produkte gezeigt, die mal im [osu!store](https://osu.ppy.sh/store/listing) verfügbar waren, mittlerweile aber nicht mehr produziert werden und auch nicht zum Verkauf stehen.
```

2024-11-04 17:21 UTC, FreezyLemon requested changes
Few small mistakes, looks good otherwise

2024-11-04 17:21 UTC, FreezyLemon commented on wiki/Past_osu!store_items/de.md
> +**osu! goods** war eine Kollektion von offiziellen osu!-Markenartikeln, die über den Onlinehändler [CafePress](https://en.wikipedia.org/wiki/CafePress) zwischen 2009 und 2012 verkauft wurden. Alle Ar
The link for "supporting the game" is a bit unfortunate in that position

Maybe

```suggestion
**osu! goods** war eine Kollektion von offiziellen osu!-Markenartikeln, die über den Onlinehändler [CafePress](https://en.wikipedia.org/wiki/CafePress) zwischen 2009 und 2012 verkauft wurden. Alle Artikel wurden von CafePress gedruckt und produziert, wobei ein Teil der Einnahmen [in die Spielentwicklung flossen](https://osu.ppy.sh/store/listing).
```

or alternatively

```suggestion
**osu! goods** war eine Kollektion von offiziellen osu!-Markenartikeln, die über den Onlinehändler [CafePress](https://en.wikipedia.org/wiki/CafePress) zwischen 2009 und 2012 verkauft wurden. Alle Artikel wurden von CafePress gedruckt und produziert. Ein Teil der Einnahmen wurde zur [Unterstützung der Spielentwicklung](https://osu.ppy.sh/store/listing) verwendet.
```

2024-11-04 17:21 UTC, FreezyLemon commented on wiki/Past_osu!store_items/de.md
> +Das **osu!tablet** war ein von osu! offiziell vertriebenes Grafiktablett, das in Zusammenarbeit mit der Elektronikfirma [HUION](https://www.huion.com/) entstand. Es wurde von ::{ flag=MY }:: [flyte](
It was an official tablet being sold, not a tablet being sold officially :P

```suggestion
Das **osu!tablet** war ein offizielles, von osu! vertriebenes Grafiktablett, das in Zusammenarbeit mit der Elektronikfirma [HUION](https://www.huion.com/) entstand. Es wurde von ::{ flag=MY }:: [flyte](https://osu.ppy.sh/users/3103765) entworfen und als eine erschwingliche Alternative für die, die einfach ein Grafiktablett für osu! haben wollten, herausgebracht.
```

2024-11-04 17:21 UTC, FreezyLemon commented on wiki/Past_osu!store_items/de.md
> +Die **osu! beatmap blueprints** (zu Deutsch Beatmap-Vorlagen) waren wieder verwendbare Aufkleber mit verschiedenen Spielelementen wie Hit-Circles, Slider, Approach-Circles, [hit judgements](/wiki/Gam
```suggestion
Die **osu! beatmap blueprints** (zu Deutsch Beatmap-Vorlagen) waren wiederverwendbare Aufkleber mit verschiedenen Spielelementen wie Hit-Circles, Slider, Approach-Circles, [hit judgements](/wiki/Gameplay/Judgement/osu!)<!--TODO: translate--> und dem osu!-Logo selbst. Das Produkt wurde 2015 verkauft, damit Spieler "lebensgroße Beatmaps im echten Leben" kreieren können.
```

2024-11-04 17:21 UTC, FreezyLemon commented on wiki/Past_osu!store_items/de.md
> +Die **limitierte Edition der osu!-Plüschtiere** waren ein Trio aus Plüschtieren bestehend aus [pippi](/wiki/Mascots#pippi), [Taikonator](/wiki/Mascots#taikonator) und dem [osu!-Cookie](/wiki/Client/I
```suggestion
Die **limitierte Edition der osu!-Plüschtiere** war ein Trio aus Plüschtieren bestehend aus [pippi](/wiki/Mascots#pippi), [Taikonator](/wiki/Mascots#taikonator) und dem [osu!-Cookie](/wiki/Client/Interface/Cookie). Die Produkte konnten im Frühjahr 2023 im Rahmen von Vorbestellungen erworben werden und wurden in Zusammenarbeit mit der Crowdfunding-Plattform [Makeship](https://www.makeship.com/) hergestellt.
```

2024-11-10 09:42 UTC, The-Last-Cookie commented on wiki/Past_osu!store_items/de.md
> +Die **osu! beatmap blueprints** (zu Deutsch Beatmap-Vorlagen) waren wiederverwendbare Aufkleber mit verschiedenen Spielelementen wie Hit-Circles, Slider, Approach-Circles, [hit judgements](/wiki/Game
```suggestion
Die **osu! beatmap blueprints** (zu Deutsch Beatmap-Vorlagen) waren wiederverwendbare Aufkleber mit verschiedenen Spielelementen wie Hit-Circles, Slider, Approach-Circles, [Trefferbeurteilungen](/wiki/Gameplay/Judgement/osu!) und dem osu!-Logo selbst. Das Produkt wurde 2015 verkauft, damit Spieler "lebensgroße Beatmaps im echten Leben" kreieren können.
```

2024-11-10 12:57 UTC, FreezyLemon approved these changes

2024-11-26 22:08 UTC, Hiviexd approved these changes

2024-11-26 22:14 UTC, merged