Add `GB Cup 2024 IRL` wiki articles
ppy/osu-wiki pull request #12371
Opened 2024-10-30 15:33 UTC by yobrevelc

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [X] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

`SKIP_OUTDATED_CHECK`

2024-10-30 20:36 UTC, Walavouchey requested changes
the GBC index page needs an update

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +3. The top 16 players in the qualifier will enter the main competition. They will be divided into 4 tiers according to the player ranking and randomly assigned into 4 quarter zones, while every quart
```suggestion
3. The top 16 players in the qualifier will enter the main competition. They will be divided into 4 tiers according to the player ranking and randomly assigned into 4 quarter zones, where every quarter will forcibly include 1 player from each tier. The first round of the game is fixed as tier 1 vs. tier 4, and tier 2 vs. tier 3.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +4. After the qualifier round, if any qualified player withdraws, his ranking will be replaced by the next player, and so on.
```suggestion
4. After the qualifier round, if any qualified player withdraws, their ranking will be replaced by the next player, and so on.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +2. The main competition is a single-elimination knockout competition with a total of 16 players. The round of 16 is a best-of-seven game, the quarterfinals and semifinals are a best-of-nine game, and
```suggestion
2. The main competition is a single-elimination knockout competition with a total of 16 players. The Round of 16 is a best-of-7 game, the Quarterfinals and Semifinals are a best-of-9 game, and the Final is a best-of-11 game.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +3. There are three maps for each slot in the mappool. When selecting a map, you can only select the position. The specific map to be used will be determined by random roll on the spot.
```suggestion
3. There are three maps for each slot in the mappool. When selecting a map, you can only select the position. The specific map to be used will be determined by random `!roll` on the spot.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +4. During the protect phase, both players choose a slot and assign it to a specific map. The map of this slot will not be randomized in subsequent selections, if this slot got piced the map will dire
```suggestion
4. During the protect phase, both players choose a slot and assign it to a specific map. The map of this slot will not be randomised in subsequent selections. If this slot gets picked, the map will directly be selected. Additionally, this slot cannot be banned.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +6. When the two sides are tied and the last point is decided, the last map will use Tie-breaker. At this time, both sides will ban one map at the same time through the referee. If different maps are
```suggestion
6. When the two sides are tied and the last point is decided, the last map will be a tiebreaker. At this time, both sides will ban one map at the same time through the referee. If different maps are banned, the remaining one will be the map played; if the same map is banned, one map will be randomly selected from the remaining two maps.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +7. Each side will have 2 minutes to choose a map. If the timeout is reached, the referee will randomly select an unselected map from the mappool. After the map is selected, both players have 2 minute
written out elsewhere in this article

```suggestion
7. Each side will have two minutes to choose a map. If the timeout is reached, the referee will randomly select an unselected map from the mappool. After the map is selected, both players have two minutes to get ready.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +# # GB Cup 2024 In Real Life
```suggestion
# GB Cup 2024 In Real Life
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +9. There are no restrictions on whether both players can choose or not choose a certain map, except that the selected map must be in the game map pool, and you cannot choose a map that has been selec
```suggestion
9. There are no restrictions on whether both players can choose or not choose a certain map, except that the selected map must be in the game mappool, and you cannot choose a map that has been selected in the game, and you cannot choose the tiebreaker.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +11. Players are allowed to rematch if any player disconnects early on during a beatmap. Send a message as soon as poosible in the match room chat to notify the referee to restart the match.
```suggestion
11. Players are allowed to rematch if any player disconnects early on during a beatmap. Send a message as soon as possible in the match room chat to notify the referee to restart the match.
```

2024-10-30 20:36 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +12. If necessary, the referee has the right to decide the implementation of the rules at his own discretion and has the final say on events that occur during the game.
```suggestion
12. If necessary, the referee has the right to decide the implementation of the rules at their own discretion and has the final say on events that occur during the game.
```

2024-10-31 02:03 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +**GBC 2024 IRL** (***GB Cup 2024 In Real Life***) is hosted by [\[GB\]yobrevelc](https://osu.ppy.sh/users/14128407) and organized by GB. It is an osu!mania 4k event that was held offline at the Kulul
according to my knowledge there is no link of Kululu Music Game Carnival, only some videos I guess

2024-10-31 12:12 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +**GB Cup 2024 In Real Life** (***GBC 2024 IRL***) is a LAN osu!mania 4-key solo tournament hosted by [\[GB\]yobrevelc](https://osu.ppy.sh/users/14128407) and organized by GB. It was the sixth instalm
```suggestion
**GB Cup 2024 In Real Life** (***GBC 2024 IRL***) is a osu!mania 4-key solo LAN tournament hosted by [\[GB\]yobrevelc](https://osu.ppy.sh/users/14128407) and organised by Team GB. It was the sixth instalment of the GB Cup series and the first instalment of the GB Cup IRL. This LAN tournament was held offline at the Kululu Music Game Carnival in Shanghai, China.
```

2024-10-31 12:12 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +![Badge Image](img/gbc2024irl-winner.png)
```suggestion
![Trophy image](img/gbc2024irl-cups.jpg "GBC 2024 IRL trophies")

![Badge image](img/gbc2024irl-winner.png)
```

2024-11-01 11:44 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +![GB杯2024线下赛图片](img/gbc2024irl-banner.png)
```suggestion
![GB Cup 2024 IRL banner](img/gbc2024irl-banner.png)
```

2024-11-01 12:41 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2024_IRL/en.md
> +![Badge image](img/gbc2024irl-winner.png)
mind updating the translation for this part too

```suggestion
![Badge image](img/gbc2024irl-winner.png "GBC 2024 IRL winner badge")
```

2024-11-01 12:47 UTC, Walavouchey commented
in the future, please don't pr from the `master` branch. create a new branch before making changes. see https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#making-edits

2024-11-02 13:50 UTC, yobrevelc commented
> in the future, please don't pr from the `master` branch. create a new branch before making changes. see https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#making-edits

ok I see

2024-11-02 19:35 UTC, Walavouchey approved these changes

2024-11-02 19:37 UTC, merged