[ES] Add `Converts`
ppy/osu-wiki pull request #12386
Opened 2024-11-02 19:16 UTC by Ladwick

**Article translation** – `Converts`

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-11-04 05:32 UTC, UnknownOsu requested changes

2024-11-04 05:32 UTC, UnknownOsu commented on wiki/Beatmap/Converts/es.md
> +Las conversiones de osu!catch se generan según el ritmo y el *posicionamiento horizonal* (p. ej. la coordenada del eje x) de los [objetos](/wiki/Gameplay/Hit_object) en un beatmap de la siguiente man
```suggestion
Las conversiones de osu!catch se generan según el ritmo y el *posicionamiento horizontal* (por ejemplo, la coordenada del eje x) de los [objetos](/wiki/Gameplay/Hit_object) en un beatmap de la siguiente manera:
```

2024-11-04 05:32 UTC, UnknownOsu commented on wiki/Beatmap/Converts/es.md
> +Las conversiones de osu!mania se generan mayormente según el ritmo del beatmap e hipotéticamente son mucho más aleatorias que las conversiones en otros modos de juego. Aunque no hay una definición ex
```suggestion
Las conversiones de osu!mania se generan principalmente según el ritmo del beatmap, y se supone que son mucho más aleatorias que las conversiones en otros modos de juego. Si bien no hay una definición exacta de cómo funcionan las conversiones de osu! a osu!mania, generalmente ocurren de la siguiente manera:
```

2024-11-04 05:32 UTC, UnknownOsu commented on wiki/Beatmap/Converts/es.md
> +- Los círculos y sliders cortos (p. ej. [sliders 1/4](/wiki/Client/Beatmap_editor/Beat_snap_divisor)) son convertidos en notas regulares.
```suggestion
- Los círculos y sliders cortos (por ejemplo, [sliders de 1/4](/wiki/Client/Beatmap_editor/Beat_snap_divisor)) se convertirán en notas regulares.
```

2024-11-04 05:32 UTC, UnknownOsu commented on wiki/Beatmap/Converts/es.md
> +- Los spinners y sliders más largos son convertidos en notas largas.
```suggestion
- Los spinners y sliders más largos se convertirán en notas largas.
```

2024-11-04 05:32 UTC, UnknownOsu commented on wiki/Beatmap/Converts/es.md
> +Además de lo anterior mencionado, las conversiones a osu!mania son únicas en el sentido de que la conversión resultante puede ser [4K, 5K, o 7K](/wiki/Gameplay/Game_modifier/xK) dependiendo de la dif
```suggestion
Además de lo mencionado anteriormente, las conversiones a osu!mania son únicas en el sentido de que la conversión resultante puede ser de [4K, 5K o 7K](/wiki/Gameplay/Game_modifier/xK), dependiendo de la dificultad del beatmap original.
```

2024-11-04 20:50 UTC, UnknownOsu approved these changes

2024-11-09 10:17 UTC, agatemosu commented on wiki/Beatmap/Converts/es.md
> +Las conversiones de osu!taiko se generan según la colocación de los [hitsounds](/wiki/Beatmapping/Hitsound), el ritmo, y los cambios de velocidad de los sliders en un beatmap. Dependiendo de los tipo
```suggestion
Las conversiones de osu!taiko se generan según la posición de los [hitsounds](/wiki/Beatmapping/Hitsound), el ritmo, y los cambios de velocidad de los sliders en un beatmap. Dependiendo de los tipos de [objetos](/wiki/Gameplay/Hit_object) y sus hitsounds correspondientes, la conversión generalmente ocurre de la siguiente manera:
```

2024-11-09 18:55 UTC, agatemosu approved these changes

2024-11-26 22:06 UTC, Hiviexd approved these changes

2024-11-26 22:12 UTC, merged