[EN/ZH] Update `Performance points`
ppy/osu-wiki pull request #12403
Opened 2024-11-07 07:45 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

changes:

- bonus pp correction: whether [source code](https://github.com/ppy/osu-queue-score-statistics/blob/3ac03768bb93cb2568d1b87f02c5c35953b48c74/osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs#L80) or [news post](https://osu.ppy.sh/home/news/2024-03-19-changes-to-performance-points), the upper limit of bonus pp is set to 413.894 (1000 scores)
- rearrange the `history` chapter: It should be placed at the back of the article, as they are not directly related to the presentation or introduce of the pp.
- apply recently [pp system changes](https://osu.ppy.sh/home/news/2024-10-28-performance-points-star-rating-updates)

2024-11-07 08:00 UTC, CloneWith requested changes

2024-11-07 08:00 UTC, CloneWith commented on wiki/Performance_points/zh.md
> +  - 调整精确缩放因子
```suggestion
  - 调整精度缩放因子
```
可以考虑加一个*度*之类的修饰词，明确修饰的对象

2024-11-07 08:24 UTC, CloneWith approved these changes
除了这个之外就没别的了

2024-11-07 08:24 UTC, CloneWith commented on wiki/Performance_points/zh.md
> +  - 在精确计算中调整 [Hidden](/wiki/Gameplay/Game_modifier/Hidden) 和 [Flashlight](/wiki/Gameplay/Game_modifier/Flashlight) 的奖励分
```suggestion
  - 在精度计算中调整 [Hidden](/wiki/Gameplay/Game_modifier/Hidden) 和 [Flashlight](/wiki/Gameplay/Game_modifier/Flashlight) 的奖励分
```

2025-02-04 20:58 UTC, Walavouchey commented on wiki/Performance_points/en.md
> +  - Improvement rhythm complexity
```suggestion
  - Improve rhythm complexity
```

2025-02-12 15:44 UTC, Walavouchey approved these changes

2025-02-12 16:00 UTC, tsunyoku reviewed
Information itself is accurate, just a couple suggestions.

2025-02-12 16:41 UTC, YumeMuzi commented on wiki/Performance_points/en.md
> +  - Adjust LN value scaling to address overweighted LN maps
the news post link has already been provided on top of this, imo using a link for each section isn't necessary. and these links may override other links to the terms.

2025-02-12 16:47 UTC, YumeMuzi commented on wiki/Performance_points/en.md
> +On January 16, 2021, changes were made to the ppv2 system that aimed to more accurately award pp to more difficult aspects of maps. These changes were made in large part by the help of various indivi
getting exact older news posts can be difficult, so I've added a note to indicate readers.

2025-02-12 17:59 UTC, Walavouchey commented on wiki/Performance_points/en.md
> +It continued to exist in this capacity for more than a year of service until [Tom94](https://osu.ppy.sh/users/1857058), the creator of the *osu!tp* scoring metric, joined the [osu! team](/wiki/People
wrong tense

```suggestion
It continued to exist in this capacity for more than a year of service until [Tom94](https://osu.ppy.sh/users/1857058), the creator of the *osu!tp* scoring metric, joined the [osu! team](/wiki/People/osu!_team) and implemented his design into the system. The resulting system was titled *ppv2*, and became live on January 27, 2014, therefore renaming the old system to *[ppv1](/wiki/Performance_points/ppv1)*. Since then, the system was continuously maintained. but no major updates were made.
```

2025-02-12 18:02 UTC, tsunyoku commented on wiki/Performance_points/en.md
> +It continued to exist in this capacity for more than a year of service until [Tom94](https://osu.ppy.sh/users/1857058), the creator of the *osu!tp* scoring metric, joined the [osu! team](/wiki/People
I feel like it might make more sense for this sentence to lead into the changes below.

`no major updates were made` followed by a bunch of major changes feels a bit strange, but maybe I'm reading into it too much.

If we're keeping the sentence here though, should at least correct the incorrect punctuation (on top of Wala's suggestion):

```suggestion
It continued to exist in this capacity for more than a year of service until [Tom94](https://osu.ppy.sh/users/1857058), the creator of the *osu!tp* scoring metric, joined the [osu! team](/wiki/People/osu!_team) and implemented his design into the system. The resulting system was titled *ppv2*, and became live on January 27, 2014, therefore renaming the old system to *[ppv1](/wiki/Performance_points/ppv1)*. Since then, the system has been continuously maintained, but no major updates have been made.
```

2025-02-13 10:58 UTC, tsunyoku requested changes

2025-02-13 10:58 UTC, tsunyoku commented on wiki/Performance_points/en.md
> +  - Sliders now contribute to accuracy pp
```suggestion
  - Sliders now contribute to accuracy pp for scores set on osu!(lazer)
```

Missed this at first, feels like an important clarification

2025-02-15 13:50 UTC, Walavouchey approved these changes

2025-02-15 13:51 UTC, merged