Update `Official tournament support`
ppy/osu-wiki pull request #12419
Opened 2024-11-10 20:31 UTC by Albionthegreat

## Changelog

- Update the minimum size requirement for tournaments and add the requirements for LAN tournaments.
- Remove conflicting information regarding automated refereeing.
- Update required information to be sent upon tournament conclusion to include links to publicly viewable documents with qualifier results, mp links and mappools.
- Update terminology, eliminating the term 'cooldown' from the official support page.

## Checklist

- [ ] Approval from the tournament committee.

2024-11-10 22:25 UTC, hburn7 requested changes
semantics

2024-11-10 22:25 UTC, hburn7 commented on wiki/Tournaments/Official_support/en.md
> +  - The qualifier results — for tournaments that use qualifiers.
```suggestion
  - The tournament's qualifier results, where applicable.
```

2024-11-10 22:25 UTC, hburn7 commented on wiki/Tournaments/Official_support/en.md
> +At the support team's discretion, staff members whose conduct directly results in a tournament losing its official support may not fulfil the same roles in, nor be the host or admin of, another badge
```suggestion
At the support team's discretion, staff members whose conduct directly results in a tournament losing its official support may not fulfil the same roles in, nor be the host or admin of, another officially-supported tournament for at least 4 months. In the event a staffing ban is applied to a user, they will be informed directly through the [tournament team](mailto:tournaments@ppy.sh).
```

2024-11-12 01:12 UTC, hburn7 commented
These changes have been approved by the Tournament Committee.

2024-11-12 09:45 UTC, Hiviexd submitted a review, later dismissed

2024-11-12 09:55 UTC, Hiviexd approved these changes

2024-11-12 09:57 UTC, merged