Add personal information collection framework in `Tournaments/Official_support`
ppy/osu-wiki pull request #12417
Opened 2024-11-10 20:01 UTC by hburn7

## Self-check

- [ ] Tournament Committee approval

This PR adds a framework regarding the collection and use of personal information which tournament organizers must abide by. Edits to language and structure are appreciated.

2024-11-10 22:03 UTC, hburn7 commented
Updated to use the term 'registrants' instead of 'users' to avoid accidentally lumping in staff members with this change. Staff members are not affected by this rule change. For example, tournament hosts do not need to explain why they are collecting emails from staff members as this is an extremely common practice.

2024-11-11 00:21 UTC, hburn7 commented on wiki/Tournaments/Official_support/en.md
> +  - Any users, organizations, or other entities who can view this information.
Could also be written as "Who can view the information" - open to feedback on the wording.

2024-11-11 20:21 UTC, Albionthegreat requested changes
UK English. Also addresses a small typo.

2024-11-11 20:21 UTC, Albionthegreat commented on wiki/Tournaments/Official_support/en.md
> +- The tournament organisers do not collect, allow the submission of, or utilize any personal information[^personal-information] from any registrants for any reason outside of these defined exceptions
```suggestion
- The tournament organisers do not collect, allow the submission of, or utilise any personal information[^personal-information] from any registrants for any reason outside of these defined exceptions.
```

2024-11-11 20:21 UTC, Albionthegreat commented on wiki/Tournaments/Official_support/en.md
> +  - Any users, organizations, or other entities who can view this information.
```suggestion
  - Any users, organisations, or other entities who can view this information.
```

2024-11-12 01:12 UTC, hburn7 commented
These changes have been approved by the Tournament Committee.

2024-11-12 10:02 UTC, Hiviexd commented on wiki/Tournaments/Official_support/en.md
> +  - What the information is used for.
consistency with above point
```suggestion
  - What the information will be used for.
```

2024-11-12 13:41 UTC, Walavouchey approved these changes

2024-11-12 18:37 UTC, Hiviexd approved these changes

2024-11-12 18:39 UTC, merged