[ES] Update `Beatmap/Packs`
ppy/osu-wiki pull request #12497
Opened 2024-11-28 18:40 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-12-06 17:33 UTC, Unnombredeusuarioextremadamentelargo requested changes

2024-12-06 17:33 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmap/Packs/es.md
> +`F2` indica que es el segundo paquete de beatmaps disponible en la categoría Artista Destacado, mientras que `Rohi Pack` se refiere al nombre del paquete que aparece en el [listado de paquetes de bea
```suggestion
`F2` indica que es el segundo paquete de beatmaps disponible en la categoría Artista destacado, mientras que `Rohi Pack` se refiere al nombre del paquete que aparece en el [listado de paquetes de beatmaps](https://osu.ppy.sh/beatmaps/packs/F2). En concreto, este paquete contiene exclusivamente mapas de las canciones de [Rohi](https://osu.ppy.sh/beatmaps/artists/82).
```

2024-12-06 17:33 UTC, Unnombredeusuarioextremadamentelargo commented on wiki/Beatmap/Packs/es.md
> +| **P** | Torneo | Mappools para [torneos oficiales](https://osu.ppy.sh/community/tournaments) |
```suggestion
| **P** | Torneo | Mappools de [torneos oficiales](https://osu.ppy.sh/community/tournaments) |
```

2024-12-08 09:21 UTC, TicClick approved these changes

2024-12-08 09:21 UTC, merged