retranslated /wiki/beatmap/packs/ru.md
ppy/osu-wiki pull request #12536
Opened 2024-12-08 13:41 UTC by TemSedar

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) - not, because I happen to be banned from the official osu! discord server (I don't even remember what for)

2024-12-08 15:32 UTC, stysan requested changes
everything else is probably fine

2024-12-08 15:32 UTC, stysan commented on wiki/Beatmap/Packs/ru.md
> +`F2` значит, что это второй набор карт, доступный в категории "Рекомендованные Исполнители" ("Featured Artist"), когда как `Rohi Pack` относится к названию набора в [списке наборов карт](https://osu.
когда как isn't correct here, you should instead write тогда как

2024-12-08 16:33 UTC, TemSedar commented on wiki/Beatmap/Packs/ru.md
> +`F2` значит, что это второй набор карт, доступный в категории "Рекомендованные Исполнители" ("Featured Artist"), когда как `Rohi Pack` относится к названию набора в [списке наборов карт](https://osu.
i barely use that word combo sorry ;w;

2025-01-16 19:57 UTC, stysan requested changes

2025-01-16 19:57 UTC, stysan commented on wiki/Beatmap/Packs/ru.md
> +В среднем, наборы карт размером примерно 100 МБ и содержат все доступные объекты карты, включая видео.
you should add a full stop at the end (.)

2025-01-22 16:19 UTC, TEMSEDAR commented on wiki/Beatmap/Packs/ru.md
> +В среднем, наборы карт размером примерно 100 МБ и содержат все доступные объекты карты, включая видео.
i accidentally requested a review from you btw sorry I Dont Know how this platform works

2025-01-22 16:24 UTC, TEMSEDAR reviewed
reviewed stysan's change and hopefully modified the line with the missing full stop in the past

2025-01-22 16:31 UTC, TEMSEDAR commented on wiki/Beatmap/Packs/ru.md
> +В среднем, наборы карт размером примерно 100 МБ и содержат все доступные объекты карты, включая видео.
there is/was a full stop though ... ? at least in the fork of mine there has been, the entire time. i forgot how did i commit that the last time but istg there Is a full stop at line 5
help im so lost

2025-02-05 22:30 UTC, TicClick commented on wiki/Beatmap/Packs/ru.md
> +В среднем, наборы карт размером примерно 100 МБ и содержат все доступные объекты карты, включая видео.
should be fixed now

2025-02-05 22:32 UTC, TicClick approved these changes
hey, apologies for reviewing this so late -- should have checked and/or edited your PR earlier

2025-02-05 22:32 UTC, merged