[EN][FR] Update articles related to gamemodes and gameplay, add missing links
ppy/osu-wiki pull request #12539
Opened 2024-12-08 21:43 UTC by sbnh1

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2024-12-08 21:55 UTC, sbnh1 commented
did I do anything wrong?
What can I do ?

2024-12-09 22:40 UTC, LeZozoien commented
If you click on "Details" in "osu-wiki continuous integration", you'll find what the errors are
If i'm not mistaken you have to 
- Outdate the other translations because you updated the english article
- Remove some lines where there are 2 consecutive blank lines
- Change the level of some titles (you can't go from level 1 to level 3 directly)
- Remove the trailing slash in a wiki link

It is also written in "changed files"

2025-01-27 15:55 UTC, Walavouchey requested changes

2025-01-27 15:55 UTC, Walavouchey commented on wiki/Gameplay/Hit_object/Hit_circle/en.md
> +*Hit circle* are a type of colored, circular [hit object](/wiki/Gameplay/Hit_object) present in [osu!](/wiki/Game_mode/osu!) and [osu!taiko](/wiki/Game_mode/osu!taiko) [beatmaps](/wiki/Beatmap). They
we use british english
some of these words are incorrectly put into singular forms <.<

```suggestion
*Hit circles* are a type of coloured, circular [hit objects](/wiki/Gameplay/Hit_object) present in [osu!](/wiki/Game_mode/osu!) and [osu!taiko](/wiki/Game_mode/osu!taiko) [beatmaps](/wiki/Beatmap). They are core gameplay elements, requiring players to click on/tap them in time with the music to [score](/wiki/Gameplay/Score) points. Clicking hit circles more [accurately](/wiki/Gameplay/Accuracy) awards more score, as well as providing a very small boost to the [health bar](/wiki/Gameplay/Health) and a larger one at the end of a [combo](/wiki/Beatmapping/Combo).
```

2025-01-27 15:55 UTC, Walavouchey commented on wiki/Gameplay/Hit_object/Hit_circle/en.md
> +Hit circles are customizable through osu! [skins](/wiki/Skin), allowing player to modify their appearance.
again, british english

```suggestion
## Customisation and skinning

Hit circles are customisable through [skins](/wiki/Skin), allowing players to modify their appearance. 
```

2025-01-27 15:55 UTC, Walavouchey commented on wiki/Gameplay/Hit_object/Hit_circle/en.md
> +
...osu!taiko doesn't have hit circles. it has different hit objects called "dons" and "kats"

```suggestion
```

2025-02-01 10:03 UTC, sbnh1 commented on wiki/Gameplay/Hit_object/Hit_circle/en.md
> +
I haven't changed the osu taiko part, it was like this before. So have i the right to remove this ? 
If you think so, I will

2025-03-05 08:43 UTC, Walavouchey approved these changes

2025-03-06 21:28 UTC, Joehuu approved these changes

2025-03-06 21:30 UTC, merged