[KO] Update `Ranking Criteria`
ppy/osu-wiki pull request #12578
Opened 2024-12-18 10:23 UTC by Rurvker

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2025-01-17 10:14 UTC, Sitoria requested changes
[!] need addition

2025-01-17 10:14 UTC, Sitoria commented on wiki/Ranking_criteria/ko.md
> +
`이 문서의 규칙과 ~` 부터 `~이러한 제안은 환영입니다.` 까지는 원문 뒷 편에 위치합니다. 

`각 게임모드 별 랭킹 크리테리아` 밑 문단에 넣어주세요.

2025-01-17 10:14 UTC, Sitoria commented on wiki/Ranking_criteria/ko.md
> +
원문 23번 줄인 `### General ranking criteria` 부분이 누락되어 있습니다.

2025-01-17 10:14 UTC, Sitoria commented on wiki/Ranking_criteria/ko.md
>  - **`Letterbox during breaks` 세팅은 같은 모드의 난이도가 브레이크를 포함하고, 같은 스토리보드를 사용한다면 일관되게 적용되어야 합니다.**
이 밑의 <!-- 뒤에 적혀있는 메모는 삭제해도 됩니다.

2025-01-19 01:44 UTC, Sitoria approved these changes

2025-01-19 01:50 UTC, Sitoria commented
erased is correct

2025-01-27 12:09 UTC, TicClick approved these changes

2025-01-27 12:09 UTC, merged