Expand Difficulty Reduction mod articles
ppy/osu-wiki pull request #12600
Opened 2024-12-26 16:07 UTC by Anax2i

original thread https://osu.ppy.sh/community/forums/topics/1959149?n=1

2025-01-27 16:50 UTC, Walavouchey requested changes

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/Daycore/en.md
> +- **Speed decrease** (0,50x-0,99x, default 0,75x): The speed at which the map is played.
```suggestion
- **Speed decrease** (0.50x–0.99x, default 0.75x): The speed at which the map is played.
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/No_Fail_(lazer)/en.md
> +The **No Fail** mod prevents the player from failing on any [beatmap](/wiki/Beatmap), which means that although the [health bar](/wiki/Client/Interface/Health_bar) reaches the bottom, you won't be ab
```suggestion
The **No Fail** mod prevents the player from failing on any [beatmap](/wiki/Beatmap), even if the [health bar](/wiki/Client/Interface/Health_bar) reaches zero or no points were scored. This mod has the same effect across all [game modes](/wiki/Game_mode).
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/No_Fail_(lazer)/en.md
> +**This mod can't be customised through Customisation.**
for wiki articles, contractions should be expanded

```suggestion
**This mod cannot be customised.**
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/No_Release/en.md
> +**This mod can't be customised through Customisation.**
```suggestion
**This mod cannot be customised.**
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/Easy_(lazer)/en.md
> +The **Easy** mod attempts to make the gameplay on any [beatmap](/wiki/Beatmap) played easier by halving the difficulty settings. In all [game modes](/wiki/Game_mode) except [osu!taiko](/wiki/Game_mod
shouldn't use "you" on the wiki

```suggestion
The **Easy** mod attempts to make the gameplay on any [beatmap](/wiki/Beatmap) played easier by halving each difficulty setting. In all [game modes](/wiki/Game_mode) except [osu!taiko](/wiki/Game_mode/osu!taiko), the mod gives two extra lives in case the [health bar](/wiki/Client/Interface/Health_bar) drops to zero, which instead refills it instantly.
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/Easy_(lazer)/en.md
> +- **Extra Lives** (0–10, default 2): Lets you choose the number of lives you want to obtain when starting a beatmap.
```suggestion
- **Extra Lives** (0–10, default 2): The number of extra lives when starting a beatmap.
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/Half_Time_(lazer)/en.md
> +The **Half Time** mod decreases the BPM of any beatmap by 75% as well as increasing the length of the song by 33%. It also can reduce the [approach rate (AR)](/wiki/Beatmap/Approach_rate), [overall d
"decrease by 75%" means "multiply by 0.25"

```suggestion
The **Half Time** mod decreases the BPM of any beatmap to 75%, increasing the length of the song by 33%. It also can reduce the [approach rate (AR)](/wiki/Beatmap/Approach_rate), [overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) or both at once depending on the [game mode](/wiki/Game_mode).
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/Half_Time_(lazer)/en.md
> +- **Speed decrease** (0,50x-0,99x, default 0,75x): The speed at which the map is played.
```suggestion
- **Speed decrease** (0.50x–0.99x, default 0.75x): The speed at which the map is played.
```

2025-01-27 16:50 UTC, Walavouchey commented on wiki/Gameplay/Game_modifier/Half_Time_(lazer)/en.md
> +- **Adjust pitch** (default disabled): Changes the audio frequency depending on the chosen speed. *Enabling this option doesn't make the mod unrankable.* (playing with the default speed will have the
```suggestion
- **Adjust pitch** (disabled by default): Changes the audio frequency depending on the chosen speed. Enabling this option does not make the play unranked. (Enabling pitch adjustment with the default speed will have the same effect as [Daycore](/wiki/Gameplay/Game_modifier/Daycore).)
```

2025-02-05 22:37 UTC, TicClick approved these changes

2025-02-05 22:37 UTC, TicClick commented
@Walavouchey back to you

2025-02-06 01:06 UTC, Walavouchey approved these changes

2025-02-06 09:26 UTC, Walavouchey approved these changes

2025-02-06 09:28 UTC, merged