Tournaments/anzt
ppy/osu-wiki pull request #12616
Opened 2024-12-29 14:33 UTC by JWWolstenholme

This PR adds an article for the [ANZT6W tournament](https://osu.ppy.sh/community/forums/topics/928661).

There have been a bunch of ANZT tournaments since this one that are undocumented in this wiki. I'm planning on documenting them all in one big pull request in the future. Let me know if that's not a good idea. They are:
- [ANZT7S](https://osu.ppy.sh/community/forums/topics/1007139)
- [ANZT7W](https://osu.ppy.sh/community/forums/topics/1086888)
- [ANZT8S](https://osu.ppy.sh/community/forums/topics/1204722)
- [ANZT8W](https://osu.ppy.sh/community/forums/topics/1346048)
- [ANZT9S](https://osu.ppy.sh/community/forums/topics/1488646)
- [ANZT9W](https://osu.ppy.sh/community/forums/topics/1601049)
- [ANZT10S](https://osu.ppy.sh/community/forums/topics/1699251)
- [ANZT10W](https://osu.ppy.sh/community/forums/topics/1785325)
- [ANZT11S](https://osu.ppy.sh/community/forums/topics/1865121)
- [ANZT11W](https://osu.ppy.sh/community/forums/topics/1943093)

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-12-30 12:02 UTC, Albionthegreat requested changes
When adding a tournament to the tournament listings in other languages, make sure to adjust the date formats. They're currently all using the English format.

I suggest adding all ANZT tournaments to the index page and tournament listings in this PR already. Once the full articles are PR'd, you then only need to add in the links. This will also avoid any merge conflicts that arise when doing multiple PR's for the same index page.

I will also suggest doing a new PR for each tournament, or PR's for each year (so bundle the summer and winter tournaments). Large PR's with tons of tournaments all at once are a daunting task to review.  By separating them into smaller chunks, they can be reviewed and taken care of 1 by 1. Divide and Conquer type of deal.

2025-03-02 13:24 UTC, JWWolstenholme commented
@Albionthegreat Thanks for the feedback. I've:
- Corrected the dates on the translated pages using the changes you suggest
- Added entries, but not dead links, to all the other ANZT tourneys since 6W.
  - I made sure to follow each translation's date format.
- Rebased this PR onto master since I've left this PR sitting for so long

I'll follow your advice and use smaller PRs for each tournament or two. Apologies for all the force pushes, hopefully that's not an issue.

2025-03-02 13:53 UTC, JWWolstenholme commented
I've also included links to tourneys 1 through 4 which were already included in the main tourney index page, but missing from the ANZT tourney index page. Forum links:

- [ANZT1](https://osu.ppy.sh/community/forums/topics/317172)
- [ANZT2](https://osu.ppy.sh/community/forums/topics/309684)
- [ANZT3](https://osu.ppy.sh/community/forums/topics/463813)
- [ANZT4](https://osu.ppy.sh/community/forums/topics/587374)

2025-03-06 13:39 UTC, JWWolstenholme commented
Just to clarify, this PR is ready for anyone to review it. I'm done making changes for now.

2025-03-06 15:03 UTC, Albionthegreat requested changes
I'll take a look at the tournament page itself later. The listings and index pages look good!

2025-03-06 15:10 UTC, JWWolstenholme commented on wiki/Tournaments/de.md
> +| Aus/NZ osu!standard Tournament 12 - Summer | 25-01-2025 | 23-03-2025 | *TBD* | *TBD* | *TBD* |
My bad! Good spot. Implemented.

2025-03-12 23:12 UTC, Albionthegreat requested changes

2025-03-12 23:12 UTC, Albionthegreat commented on wiki/Tournaments/ANZT/2019_Winter/en.md
> +- This is an osu!standard tourney for Australian/New Zealand players only. Participants must have an Australian or New Zealand flag on their osu profile.
```suggestion
- This is an osu! game mode tournament for Australian/New Zealand players only. Participants must have an Australian or New Zealand flag on their osu! profile.
```

2025-03-12 23:12 UTC, Albionthegreat commented on wiki/Tournaments/ANZT/2019_Winter/en.md
> +- Matches will be **Head to Head** with **Score V2**.
```suggestion
- Matches will be **Head-to-head** with **ScoreV2**.
```

2025-03-12 23:12 UTC, Albionthegreat commented on wiki/Tournaments/ANZT/2019_Winter/en.md
> +| Semifinals, Losers Bracket Rounds 4 & 5 | Win six maps (Best-of-11) |
```suggestion
| Round of 16 | Win five maps (Best-of-9) |
| Quarterfinals | Win six maps (Best-of-11) |
| Semifinals | Win six maps (Best-of-11) |
```

2025-03-12 23:12 UTC, Albionthegreat commented on wiki/Tournaments/ANZT/2019_Winter/en.md
> +- Highest !roll has first warmup, ban and pick.
```suggestion
- Highest `!roll` has first warmup, ban and pick.
```

2025-03-12 23:12 UTC, Albionthegreat commented on wiki/Tournaments/ANZT/2019_Winter/en.md
> +- In a FreeMod pick, each player **must select a mod(s)** (HD/HR/HDHR). **NoMod is not allowed**.
```suggestion
- One player may not pick from the same mod pool twice in a row (HD/HR/DT/Free Mod). This does not apply to No Mod.
- In a Free Mod pick, each player **must select a mod(s)** (HD/HR/HDHR). **No Mod is not allowed**.
```

2025-03-12 23:12 UTC, Albionthegreat commented on wiki/Tournaments/ANZT/2019_Winter/en.md
> +- If the match ends in a tie, players will play the tiebreaker. The tiebreaker will be played under FreeMod conditions, allowing NoMod.
```suggestion
- If the match ends in a tie, players will play the tiebreaker. The tiebreaker will be played under Free Mod conditions, allowing No Mod.
```

2025-03-13 04:34 UTC, JWWolstenholme commented
Thanks for the feedback @Albionthegreat. 

Looks like I'm out-dated on new styling since I was last here 6-7 years ago.

2025-03-17 11:45 UTC, Albionthegreat approved these changes
Looks good to me!

2025-03-17 12:00 UTC, TicClick approved these changes

2025-03-17 12:01 UTC, merged