Update `Tournament drawings`
ppy/osu-wiki pull request #12613
Opened 2024-12-27 12:11 UTC by CloneWith

This is about the osu! tournament client, and we can consider moving this article these if possible.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2024-12-27 18:35 UTC, iSlodinxOsu requested changes
some improvements?

2024-12-27 18:35 UTC, iSlodinxOsu commented on wiki/Tournament_drawings/en.md
> +If you have never used the osu! tournament client before, open it once by creating a shortcut on the desktop, whose location is set to `%LOCALAPPDATA%/osulazer/osu!.exe --tournament`.
```suggestion
If you never used the osu! tournament client before, open it once by creating a shortcut on the desktop, whose location is set to `%LOCALAPPDATA%/osulazer/osu!.exe --tournament`.
```

2024-12-27 18:35 UTC, iSlodinxOsu commented on wiki/Tournament_drawings/en.md
> +Then, restart the tournament client, and ensure `default` is selected as the current tournament in the setup screen.
```suggestion
Then restart the tournament client, and ensure `default` is selected as the current tournament in the setup screen.
```

2024-12-27 18:35 UTC, iSlodinxOsu commented on wiki/Tournament_drawings/en.md
> +There are three sections to this screen: the sidebar on the left, the main section, and the control panel section on the right. Please **avoid** livestreaming the sidebar and the control panel.
```suggestion
There are three sections to this screen: the sidebar on the left, the main section and the control panel section on the right. Please **avoid** livestreaming the sidebar and the control panel.
```

2025-01-27 12:40 UTC, TicClick approved these changes

2025-01-27 12:42 UTC, merged

2025-01-27 16:10 UTC, CloneWith commented
> > we can consider moving this article there if possible
> 
> can you create a follow-up PR later please, so that we check it separately?

Yes. This PR is focused on contant update, and its new position is still undecided.