[DE] Add `Gameplay/Score`
ppy/osu-wiki pull request #12619
Opened 2024-12-30 12:00 UTC by Malternative3772

My first time doing translations on here so forgive me if I've made any blatant mistakes; I'm not 100% sure on if the number formatting is correct and I wasn't really sure about the terms "Match Setup" and "Win condition" used in the last line.

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2025-01-08 22:10 UTC, The-Last-Cookie commented
Hello, great that you want to contribute to the wiki! I will take a look at your article in the coming days.

2025-01-22 20:04 UTC, The-Last-Cookie requested changes
I have more ideas but they need to be fleshed out first.

In the meantime, I wanted to get this out.

2025-01-24 16:48 UTC, Malternative3772 commented on wiki/Gameplay/Score/de.md
> +Neben der von ScoreV2 erreichten Standardisierung zwischen den Spielmodi umgeht dieses neue Punktzahlsystem auch ein [Integer Overflow](https://de.wikipedia.org/wiki/Arithmetischer_%C3%9Cberlauf#Ganz
`...sein kann, kommt es bei der Überschreitung der maximal darstellbaren Zahl von 2.147.483.647 Punkten, die mit 32 Bit dargestellt werden kann...` this sounds a bit ackward to me

```suggestion
Neben der von ScoreV2 erreichten Standardisierung zwischen den Spielmodi umgeht dieses neue Punktzahlsystem auch ein [Überlaufproblem (Integer Overflow)](https://de.wikipedia.org/wiki/Arithmetischer_%C3%9Cberlauf#Ganzzahl%C3%BCberlauf), von dem lange, bzw. Combo-intensive Beatmaps betroffen sein können. Da die Gesamtpunktzahl als eine 32-Bit-Ganzzahl gespeichert wird und die Punktzahl durch ScoreV1 theoretisch unendlich hoch sein kann, kommt es bei der Überschreitung der maximal mit 32 Bit darstellbaren Zahl von 2.147.483.647 Punkten, zu einem Überlauf in den negativen Zahlenbereich (ergo, die Punktzahl nimmt ab diesem Punkt wieder ab). Für lange Beatmaps mit einem theoretischen Punktzahlmaximum über dem Grenzwert für 32-Bit-Ganzzahlen wird in der Praxis automatisch ScoreV2 verwendet.
```

2025-01-29 20:24 UTC, The-Last-Cookie requested changes

2025-01-29 20:24 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +Neben der von ScoreV2 erreichten Standardisierung zwischen den Spielmodi umgeht dieses neue Punktzahlsystem auch ein [Integer Overflow](https://de.wikipedia.org/wiki/Arithmetischer_%C3%9Cberlauf#Ganz
Yes I agree, your suggestion sounds better 👍

2025-02-12 11:19 UTC, Malternative3772 commented on wiki/Gameplay/Score/de.md
> +# Punktzahl
So I wouldn't use `Punktevergabe` as that would be more equivalent to the english `Scoring`, which would be a slightly different word. `Punktestand` sounds nice.

2025-03-09 18:25 UTC, The-Last-Cookie requested changes

2025-03-09 18:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +# Punktzahl
Sorry for my late response.

Personally, I would use `Punktevergabe` as I find it more intuitive when reading. Taking the freedom in translation here is not an issue to me. The disambiguation article for `score` links to this page with "scoring algorithm". I will leave the decision in your hand.

2025-03-09 18:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +Die Punktzahl eines Spielers nach dem erfolgreichen Abschluss einer [Beatmap](/wiki/Beatmap) hängt von den [Beurteilungen](/wiki/Gameplay/Judgement), die der Spieler bei jedem [Hit-Objekt](/wiki/Game
```suggestion
Die Punktzahl eines Spielers nach dem erfolgreichen Abschluss einer [Beatmap](/wiki/Beatmap) hängt von den [Beurteilungen](/wiki/Gameplay/Judgement), die der Spieler bei jedem [Hit-Objekt](/wiki/Gameplay/Hit_object) erzielt, ab. Allgemein gibt es zwei Hauptversionen des Punktesystems.
```

2025-03-09 18:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +ScoreV1 ist die umgangssprachliche Bezeichnung für das ursprüngliche Punktzahlsystem in osu!. Der genutzte Punktzahlalgorithmus kann sich je nach [Spielmodus](/wiki/Game_mode) jedoch deutlich untersc
```suggestion
ScoreV1 ist die umgangssprachliche Bezeichnung für das ursprüngliche Punktesystem in osu!. Der genutzte Bewertungsalgorithmus kann sich je nach [Spielmodus](/wiki/Game_mode) jedoch deutlich unterscheiden:
```

2025-03-09 18:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +- osu!taiko orientiert sich grob am Punktzahlsystem von *Taiko no Tatsujin* und zeichnet sich durch einen Ausgangswert, der durch Combo-Boni beeinflusst wird, aus.
```suggestion
- osu!taiko orientiert sich grob am Punktesystem von *Taiko no Tatsujin* und zeichnet sich durch einen Ausgangswert, der durch Combo-Boni beeinflusst wird, aus.
```

2025-03-09 18:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +ScoreV2 bezeichnet die neue Version des Punktzahlsystems. Die Idee hinter der Weiterentwicklung ist die Standardisierung der Systeme aller Spielmodi, sodass eine perfekte Punktzahl mit einem 1,00-fac
```suggestion
ScoreV2 bezeichnet die neue Version des Punktesystems. Die Idee hinter der Weiterentwicklung ist die Standardisierung der Systeme aller Spielmodi, sodass eine perfekte Punktzahl mit einem 1,00-fachen Mod-Multiplikator immer 1.000.000 Punkte ergibt. Darüber hinaus können zusätzliche Punkte im osu!-Spielmodus durch Spinner-boni, in osu!taiko durch Drumrolls und in osu!catch durch Bananen erlangt werden. Das Punktesystem legt durch die Skalierung auf das Limit von 1.000.000 einen stärkeren Fokus auf Proportionalität und nimmt damit Abstand von der ursprünglichen Idee, jedes einzelne Hit-Objekt zu bewerten.
```

2025-03-09 18:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +Neben der von ScoreV2 erreichten Standardisierung zwischen den Spielmodi umgeht dieses neue Punktzahlsystem auch ein [Überlaufproblem (Integer Overflow)](https://de.wikipedia.org/wiki/Arithmetischer_
```suggestion
Neben der von ScoreV2 erreichten Standardisierung zwischen den Spielmodi umgeht dieses neue Punktesystem auch ein [Überlaufproblem (Integer Overflow)](https://de.wikipedia.org/wiki/Arithmetischer_%C3%9Cberlauf#Ganzzahl%C3%BCberlauf), von dem lange, bzw. Combo-intensive Beatmaps betroffen sein können. Da die Gesamtpunktzahl als eine 32-Bit-Ganzzahl gespeichert wird und die Punktzahl durch ScoreV1 theoretisch unendlich hoch sein kann, kommt es bei der Überschreitung der maximal mit 32 Bit darstellbaren Zahl von 2.147.483.647 Punkten, zu einem Überlauf in den negativen Zahlenbereich (ergo, die Punktzahl nimmt ab diesem Punkt wieder ab). Für lange Beatmaps mit einem theoretischen Punktzahlmaximum über dem Grenzwert für 32-Bit-Ganzzahlen wird in der Praxis automatisch ScoreV2 verwendet.
```

2025-04-12 07:15 UTC, The-Last-Cookie commented
@Malternative3772 Do you still want to work on this? The article is good to go I think except my suggestions above.

2025-04-22 10:28 UTC, Malternative3772 commented
> @Malternative3772 Do you still want to work on this? The article is good to go I think except my suggestions above.

Alright, commited it. I have a slight procrastination problem, but oh well 🫠
does this mean I can tick the checkbox for the review?
Thanks for your help!

2025-04-23 20:25 UTC, The-Last-Cookie requested changes
> Alright, commited it. I have a slight procrastination problem, but oh well 🫠

Don't worry. Quality over quantity as I like to say.

> does this mean I can tick the checkbox for the review?

I found a few more grammar nitpicks, but after that you can.

Thank you for translating this article!

2025-04-23 20:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +Neben der von ScoreV2 erreichten Standardisierung zwischen den Spielmodi umgeht dieses neue Punktesystem auch ein [Überlaufproblem (Integer Overflow)](https://de.wikipedia.org/wiki/Arithmetischer_%C3
```suggestion
Neben der von ScoreV2 erreichten Standardisierung zwischen den Spielmodi umgeht dieses neue Punktesystem auch ein [Überlaufproblem (Integer Overflow)](https://de.wikipedia.org/wiki/Arithmetischer_%C3%9Cberlauf#Ganzzahl%C3%BCberlauf), von dem lange bzw. Combo-intensive Beatmaps betroffen sein können. Da die Gesamtpunktzahl als eine 32-Bit-Ganzzahl gespeichert wird und die Punktzahl durch ScoreV1 theoretisch unendlich hoch sein kann, kommt es bei der Überschreitung der maximal mit 32 Bit darstellbaren Zahl von 2.147.483.647 Punkten zu einem Überlauf in den negativen Zahlenbereich (ergo, die Punktzahl nimmt ab diesem Punkt wieder ab). Für lange Beatmaps mit einem theoretischen Punktzahlmaximum über dem Grenzwert für 32-Bit-Ganzzahlen wird in der Praxis automatisch ScoreV2 verwendet.
```

2025-04-23 20:25 UTC, The-Last-Cookie commented on wiki/Gameplay/Score/de.md
> +ScoreV2 bezeichnet die neue Version des Punktesystems. Die Idee hinter der Weiterentwicklung ist die Standardisierung der Systeme aller Spielmodi, sodass eine perfekte Punktzahl mit einem 1,00-fachen
```suggestion
ScoreV2 bezeichnet die neue Version des Punktesystems. Die Idee hinter der Weiterentwicklung ist die Standardisierung der Systeme aller Spielmodi, sodass eine perfekte Punktzahl mit einem 1,00-fachen Mod-Multiplikator immer 1.000.000 Punkte ergibt. Darüber hinaus können zusätzliche Punkte im osu!-Spielmodus durch Spinner-Boni, in osu!taiko durch Drumrolls und in osu!catch durch Bananen erlangt werden. Das Punktesystem legt durch die Skalierung auf das Limit von 1.000.000 einen stärkeren Fokus auf Proportionalität und nimmt damit Abstand von der ursprünglichen Idee, jedes einzelne Hit-Objekt zu bewerten.
```

2025-04-24 07:58 UTC, Malternative3772 commented
Finished it is then, nice!

2025-04-24 20:36 UTC, The-Last-Cookie approved these changes

2025-04-28 08:52 UTC, TicClick approved these changes

2025-04-28 08:54 UTC, merged