[ZH] Update `Gameplay/Game modifier`
ppy/osu-wiki pull request #12611
Opened 2024-12-27 00:43 UTC by CloneWith

Mainly added links to lazer mods here.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2025-01-01 04:23 UTC, SamHou0 requested changes
删除多余英文句号，保持译文统一

2025-01-01 04:23 UTC, SamHou0 commented on wiki/Gameplay/Game_modifier/Easy/zh.md
>  *对于更多义项，参见：[Easy（消歧义）](/wiki/Disambiguation/Easy).*\
```suggestion
*对于更多义项，参见：[Easy（消歧义）](/wiki/Disambiguation/Easy)*\
```
原文去掉了句号

2025-01-01 04:23 UTC, SamHou0 commented on wiki/Gameplay/Game_modifier/zh.md
>  *对于更多义项，参见 [Mod（消歧义页）](/wiki/Disambiguation/Mod).*
```suggestion
*对于更多义项，参见 [Mod（消歧义）](/wiki/Disambiguation/Mod)*
```

2025-01-02 14:12 UTC, SamHou0 approved these changes

2025-01-27 12:01 UTC, TicClick approved these changes

2025-01-27 12:01 UTC, merged