[RU] Create "Hit object" page
ppy/osu-wiki pull request #3993
Opened 2020-08-07 01:11 UTC by Moltanicaa

2020-08-12 23:06 UTC, Moltanicaa commented
А как мне применить изменения?

2020-08-12 23:12 UTC, TicClick commented
надо перейти на вкладку `Files changed` наверху и найти первую правку, у неё будет кнопка с названием `Add suggestion to batch`. когда все нужные изменения прокликаешь, сделай коммит: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request

2020-08-12 23:13 UTC, Moltanicaa commented
Спасибо, сделаю позднее

2020-08-13 20:59 UTC, TicClick commented on wiki/Hit_object/ru.md
> +В osu!standard следующий круг для нажатия или слайдер, по которому нужно коснуться, выделяется немного с повышенной яркостью по сравнению с другими объектами на игровом поле. Однако подсветка не буде
> следующий

следующий после чего?

> которому нужно коснуться

который нужно сыграть

> выделяется немного с повышенной яркостью

имеет чуть более яркий цвет

> Однако подсветка не будет видна, если значение Скорость сужения слишком высока

этот эффект не проявляется, если скорость появления нот достаточно высока

2020-08-13 23:44 UTC, Moltanicaa commented on wiki/Hit_object/ru.md
> +# Объекты для ударов
У меня в голове был сбой в попытках придумать другое название для этого словосочетания

2020-08-13 23:45 UTC, Moltanicaa commented on wiki/Hit_object/ru.md
> +В osu!standard следующий круг для нажатия или слайдер, по которому нужно коснуться, выделяется немного с повышенной яркостью по сравнению с другими объектами на игровом поле. Однако подсветка не буде
Внесу днем

2020-08-15 08:10 UTC, breadx333 commented on wiki/Hit_object/ru.md
> +| [Спиннеры](/wiki/Hit_object/Spinner) (Spinners)| dendens | Бананы (bananas) | x |
```suggestion
| [Спиннеры](/wiki/Hit_object/Spinner) (spinners) | dendens | Бананы (bananas) | x |
```
Раз пишем все англ термины с маленькой буквы, то
"Spinners" -> "spinners", также добавлен пробел после него.

2020-08-29 01:33 UTC, TicClick commented
my review still needs to be applied

2020-08-29 01:47 UTC, Moltanicaa commented
Какое? Где?

2020-08-29 02:34 UTC, TicClick commented
> Какое? Где?

то, на которое ты отвечаешь «внесу днём», правок я так и не увидел: https://github.com/ppy/osu-wiki/pull/3993#pullrequestreview-466825704

2020-08-29 02:36 UTC, Moltanicaa commented
Упс, щас внесу

2020-08-29 02:39 UTC, Moltanicaa commented on wiki/Hit_object/ru.md
> +В osu!standard следующий круг для нажатия или слайдер, по которому нужно коснуться, выделяется немного с повышенной яркостью по сравнению с другими объектами на игровом поле. Однако подсветка не буде
Исправлено

2020-08-29 02:42 UTC, TicClick requested changes
там больше одного замечания же

2020-08-29 02:42 UTC, TicClick commented on wiki/Hit_object/ru.md
> +# Объекты для ударов
не исправлено

2020-08-29 02:42 UTC, TicClick commented on wiki/Hit_object/ru.md
> +*Объекты для ударов* это объекты на [карте](/wiki/Beatmaps/), с которыми игроки могут взаимодействовать во время игры. Каждый [игровой режим](/wiki/Game_Modes) имеет свой собственный набор элементов,
не исправлено

2020-08-29 02:42 UTC, TicClick commented on wiki/Hit_object/ru.md
> +| [Круглые ноты](/wiki/Hit_object/Hit_circle) (hit circles) | Круглые ноты (hit circles) | Фрукты (fruits) | Ноты (notes) |
не исправлено

2020-08-29 02:42 UTC, TicClick commented on wiki/Hit_object/ru.md
> +| [Слайдеры](/wiki/Hit_object/Slider) (Sliders) | drumrolls | Фруктовые тропы (fruit trails) | Длинные ноты (long notes) |
не исправлено

2020-08-29 02:42 UTC, TicClick commented on wiki/Hit_object/ru.md
> +С точки зрения программирования, длинные ноты в osu!mania не эквивалентны слайдерам в osu!standart, хотя для упрощения они сгруппированы в этой таблице. Другие элементы, с которыми игрок не взаимодей
не исправлено

2020-08-29 02:43 UTC, Moltanicaa commented
Странно это все работает, придется вручную вносить

2020-08-29 02:44 UTC, Moltanicaa commented
Это все было исправлено, но правки будто испарились. Либо я что-то делаю не так.

2020-08-29 02:47 UTC, TicClick commented
если не закоммитить изменения, ничего не сохранится, может, ты это упускаешь?

2020-08-29 02:48 UTC, Moltanicaa commented
Возможно, я что-то делаю не так с массовыми правками. Вручную вроде нормально получилось

2020-08-29 02:50 UTC, Moltanicaa commented
Теперь точно должно быть все

2020-08-29 02:57 UTC, TicClick requested changes
ещё немного, и сойдёт

2020-08-29 02:57 UTC, TicClick commented on wiki/Hit_object/ru.md
> +*Игровые объекты* это элементы [карты](/wiki/Beatmaps/), с которыми игрок может взаимодействовать, и которые влияют на результат игры. Каждый [игровой режим](/wiki/Game_Modes) имеет свой собственный
```suggestion
*Игровые объекты* — это элементы [карты](/wiki/Beatmaps/), с которыми игрок может взаимодействовать, и которые влияют на результат игры. Каждый [игровой режим](/wiki/Game_Modes) имеет свой собственный набор элементов, отличающий его от других режимов (термины без перевода не имеют аналога в русском языке):
```

2020-08-29 02:57 UTC, TicClick commented on wiki/Hit_object/ru.md
> +В osu!standard каждый следующий круг для нажатия или слайдер, который нужно сыграть, имеет чуть более яркий цвет по сравнению с другими объектами на игровом поле. Этот эффект не проявляется, если ско
```suggestion
В osu!standard каждая следующая нота или слайдер, который нужно сыграть, имеет чуть более яркий цвет по сравнению с остальными объектами на игровом поле. Этот эффект не проявляется, если [скорость появления нот](https://osu.ppy.sh/help/wiki/Beatmapping/Approach_rate) достаточно высока.
```

2020-08-29 02:58 UTC, TicClick commented
а, ещё тебе нужно ошибки от линтера исправить (нажми на мелкий красный крест около своего коммита)

2020-08-29 03:02 UTC, TicClick approved these changes
looks good to me

2020-08-29 03:04 UTC, Moltanicaa commented
Я не понимаю, на что жалуется эта проверка, она указывает на какой-то пробел, который я не понимаю как исправить, ибо он все равно его видит. В целом документ нормальный

2020-08-29 03:07 UTC, TicClick requested changes
надо сделать так

2020-08-29 03:07 UTC, TicClick commented on wiki/Hit_object/ru.md
> +*Игровые объекты* - это элементы [карты](/wiki/Beatmaps/), с которыми игрок может взаимодействовать, и которые влияют на результат игры. Каждый [игровой режим](/wiki/Game_Modes) имеет свой собственны
```suggestion
<!-- TODO: should also have articles for each hit object -->

# Игровые объекты

*Игровые объекты* - это элементы [карты](/wiki/Beatmaps/), с которыми игрок может взаимодействовать, и которые влияют на результат игры. Каждый [игровой режим](/wiki/Game_Modes) имеет свой собственный набор элементов, отличающий его от других режимов (термины без перевода не имеют аналога в русском языке):
```

2020-08-29 03:07 UTC, TicClick commented on wiki/Hit_object/ru.md
> +<!-- TODO: Add links to other articles when they're available -->
```suggestion

<!-- TODO: Add links to other articles when they're available -->
```

2020-08-29 03:11 UTC, Moltanicaa commented
Получается, все вернулось как и было. Короче, на структуру документа это вообще никак не влияет.

2020-08-29 03:11 UTC, TicClick approved these changes
take 2 of "looks good to me"

2020-08-30 20:11 UTC, TPGPL approved these changes

2020-08-30 20:12 UTC, merged