[RU] Beatmapping
ppy/osu-wiki pull request #4044
Opened 2020-08-15 15:13 UTC by Esutarosa

Correct mistakes and help with translation

2020-08-18 19:41 UTC, breadx333 requested changes
Исправления статьи

2020-08-18 19:41 UTC, breadx333 commented on wiki/Beatmapping/ru.md
> +Во вкладке «Дизайн» редактора, можно добавить фон карты, видео или создать простой сториборд. В зависимости от того, что Вы делаете, эта вкладка может вообще не пригодиться.
```suggestion
Во вкладке `Design`, можно добавить фоновое изображение или видео для карты, или же создать простой сториборд. В зависимости от того, что Вы делаете, эта вкладка может часто использоваться, или вообще не использоваться, если вы работаете с [SBS](wiki/Storyboard_Scripting).
```
В игре же вкладки написны на англ.
"Во вкладке «Дизайн» редактора, можно добавить фон карты, видео или создать простой сториборд. В зависимости от того, что Вы делаете, эта вкладка может вообще не пригодиться." -> "Во вкладке Design, можно добавить фоновое изображение или видео для карты, или же создать простой сториборд. В зависимости от того, что Вы делаете, эта вкладка может часто использоваться, или вообще не использоваться, если вы работаете с [SBS](wiki/Storyboard_Scripting)."
1. "Дизайн" -> "Design"
2. "фон" -> "фоновое изображение"
3. слово "видео" был перемещен на перед "карты"
4. Варианты использования вкладки
5. Также выделил "`Design`"

2020-08-18 19:41 UTC, breadx333 commented on wiki/Beatmapping/ru.md
> +Чтобы создать карту, перейдите в режим редактирования, затем перетащите аудиофайл в osu!. (Кроме того, его можно переместить в папку `Songs`). Новый трек будет находиться внизу списка карт. Если ауди
```suggestion
Чтобы создать карту, перейдите в режим редактирования, затем перетащите аудиофайл в osu!. (Кроме того, его можно переместить в папку `Songs`). Новый трек будет находиться внизу списка карт. Если аудиофайл по какой-либо причине отсутствует, нажмите `F5`, чтобы сбросить кэш, после чего песня появится.

Далее по ознакомлению нажмите на аудиофайл, это откроет редактор карты [Beatmap editor](/wiki/Beatmap_Editor) и диалоговое окно `Song Setup`.
```
1. "аудио" -> "аудиофайл"
2. Мне кажется ты работаешь со старой статьей
3. "`F5`"

2020-08-18 19:41 UTC, breadx333 commented on wiki/Beatmapping/ru.md
> +Введя требуемую информацию в окне, нажмите «ОК», и начните создание битмапа. Следующим шагом будет добавление тайминга.
```suggestion
Введя требуемую информацию в окне, нажмите `OK`, и начните создание битмапа. Следующим шагом будет добавление тайминга.
```
`OK`

2020-08-27 11:43 UTC, UristMcKobold requested changes

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +**Beatmapping** это процесс создания [карт](/wiki/Beatmaps) для игроков.
Тире после «beatmapping» не хватает.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Маппинг включает в себя выбор песни, настройку [тайминга](/wiki/Timing), размещение [игровых объектов](/wiki/Hit_Objects) и (необязательно) добавление [скина](/wiki/Skinning) или [сториборда](/wiki/S
```suggestion
Маппинг включает в себя выбор музыкального трека, настройку [тайминга](/wiki/Timing), размещение [игровых объектов](/wiki/Hit_Objects) и (необязательно) добавление [скина](/wiki/Skinning) или [сториборда](/wiki/Storyboarding).
```
Так как под песней имеется в виду в русском языке именно музыка с голосовым сопровождением.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Когда мапперы хотят ранкнуть свои [карты](/wiki/Beatmaps), они придерживаются [критерий ранкинга](/wiki/Beatmap_ranking_procedure).
```suggestion
Если маппер хочет ранкнуть свои [карты](/wiki/Beatmaps), то он в обязательном порядке следует по [шагам](/wiki/Beatmap_ranking_procedure), необходимым для достижения ранкеда. 
```
Ты тут переврал перевод. Они придерживаются критерий ранкинга, это правда, но ссылка-то ведёт на процесс ранкинга, а не соблюдение правил для ранкеда. Но само выражение «процесс ранкинга» не очень, поэтому надо немного менять перевод.
А ещё мне лично не нравится структура «когда мапперы хотят …», но это на твоё усмотрение. В единственном числе однозначно лучше звучит.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Можно и не соблюдать эти правила. Есть достаточно много игроков, которые делают мапы для себя, ради удовольствия.
А это ты откуда взял? Я не вижу в оригинальной статье этой строчки. Очевидно, что предыдущий абзац с «если они хотят» подразумевает, что это необязательная штука.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Если Вы только начали заниматься маппингом, то не стоит браться за музыку с частой сменой BPM. Возьмитесь за что-то легкое, и короткое, пока не наберетесь опыта в создании мап.
```suggestion
Если Вы только начали заниматься маппингом, то не стоит браться за музыку с частой сменой BPM, а также за слишком медленные треки. Возьмитесь за что-нибудь легкое и короткое, пока не наберетесь опыта в создании карт. 
```
Пропустил оригинальный совет про «медленную» музыку. Запятая лишняя, а «мап» — это ненужный англицизм. 
«что-то» в данном контексте мне просто не нравится, «что-нибудь» лучше.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Чтобы создать карту, перейдите в режим редактирования, затем перетащите аудиофайл в osu!. (Кроме того, его можно переместить в папку `Songs`). Новый трек будет находиться внизу списка карт. Если ауди
```suggestion
Чтобы создать карту, перейдите в режим редактирования, затем перетащите аудиофайл в osu! или просто переместите его в папку `Songs`. Новый трек будет находиться внизу списка карт. Если аудиофайл по какой-либо причине отсутствует, нажмите `F5`, чтобы сбросить кэш, после чего песня появится.
```
Мне здесь не нравятся скобки ОТДЕЛЬНЫМ предложением, плюс osu! с точкой в конце выглядит так себе.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Далее по ознакомлению нажмите на аудиофайл, это откроет редактор карты [Beatmap editor](/wiki/Beatmap_Editor) и диалоговое окно `Song Setup`.
```suggestion
После этого нажмите на аудиофайл, это откроет редактор карты [Beatmap editor](/wiki/Beatmap_Editor) и диалоговое окно `Song Setup`.
```
Что за «далее по ознакомлению»? Очень плохо звучит.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Эти данные можно изменить позже, если хотите.
```suggestion
Эти данные можно будет изменить позже.
```
Лишнее «если хотите», оно тут не добавляет никакой полезной информации.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Введя требуемую информацию в окне, нажмите `OK`, и начните создание битмапа. Следующим шагом будет добавление тайминга.
```suggestion
Введя требуемую информацию в окне, нажмите `OK` и начните создание карты. Следующим шагом будет настройка тайминга.
```
Снова лишний англицизм (и запятая). До этого ты писал «настройка тайминга», тут это тоже уместно будет.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Прежде чем добавлять [игровые объекты](/wiki/Hit_Objects), убедитесь, что настроили идеальный тайминг.
```suggestion
Прежде чем добавлять [игровые объекты](/wiki/Hit_Objects), убедитесь, что идеально настроили тайминг. 
```
Идеальный тайминг? Если его настроили, то он и должен быть идеальным.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Если сомневаетесь в точности настройки, обратитесь за помощью в раздел [Modding Queues](https://osu.ppy.sh/community/forums/60) или [Beatmap Help](https://osu.ppy.sh/community/forums/10). (Можно на р
```suggestion
Если сомневаетесь в точности настройки, обратитесь за помощью в раздел [Modding Queues](https://osu.ppy.sh/community/forums/60) или [Beatmap Help](https://osu.ppy.sh/community/forums/10). Можно на русском [сюда](https://osu.ppy.sh/community/forums/topics/22770).
```
Лишние скобки. Зачем?

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Правильная настройка избавит вас (и сообщество модераторов) от множества хлопот в дальнейшем.
```suggestion
Правильная настройка избавит вас (и сообщество моддеров) от множества хлопот в будущем.
```
Под модераторами имеют в виду ГМТ, а тут моддеры. «дальнейшем» ты уже употреблял в статье, так лучше будет с синонимом.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Во вкладке `Design`, можно добавить фоновое изображение или видео для карты, или же создать простой сториборд. В зависимости от того, что Вы делаете, эта вкладка может часто использоваться, или вообщ
```suggestion
Во вкладке `Design` можно добавить фоновое изображение и видео для карты или же создать простой сториборд. В зависимости от того, что Вы делаете, эта вкладка может часто использоваться или вообще не использоваться, если вы работаете с [SBS](wiki/Storyboard_Scripting).
```
Лишняя запятая. Даже три! Если тебя смущает два «или», то можно вот так.

2020-08-27 11:43 UTC, UristMcKobold commented on wiki/Beatmapping/ru.md
> +Внимание: карты с неправильным таймингом не будут ранкнуты.
```suggestion
Внимание: тайминг очень важен! Карты с неправильным таймингом не рассматриваются для ранка.
```
Поменял так, чтобы сохранить «Timing is vital!» из оригинала.

2020-09-06 14:33 UTC, TicClick approved these changes

2020-09-06 14:34 UTC, merged