[RU] Storyboarding
ppy/osu-wiki pull request #4059
Opened 2020-08-18 18:13 UTC by breadx333

Translate into RU

2020-08-19 03:37 UTC, UristMcKobold requested changes

2020-08-19 03:37 UTC, UristMcKobold commented on wiki/Storyboarding/ru.md
> +Редактор [Storyboard Editor](/wiki/Beatmap_Editor/Design) (SBE) находится во вкладке `Design` (клавиша `F2`) в `Beatmap Editor`. По сути, редактор сторибординга дает пользователям легкий способ контр
Всегда лучше начинать с подробного названия, а потом употреблять сокращённое. Вначале пишешь «редактор сториборда», потом просто «редактор». Редактор «сторибординга» звучит не очень. 
Запятая после «неэффективным» не нужна. 
«базовых вещей сторибординга» звучит коряво. Тут лучше как в оригинале сделать «кроме простых сторибордов».

2020-08-19 03:37 UTC, UristMcKobold commented on wiki/Storyboarding/ru.md
> +Пользователи, имеющие опыт в сторибординге, часто используют сгенерированный внутренний код от SBE - [Storyboard Scripting](/wiki/Storyboard_Scripting) (SBS), поскольку с помощью него, можно точнее к
Я не эксперт, но никто не говорит «сгенерированный внутренний код». «Бэкэнд» не переводят. 
«от SBE» странно звучит, лучше просто «созданный SBE».
Откуда там запятая после «него»? «точнее контролировать появление спрайтов» — отсебятина, его не только для появления спрайтов используют. В оригинале всё просто: «поскольку с помощью него они обладают большим контролем над сторибордом».
Не в «этой статье», а в «вышеупомянутой статье».

2020-08-25 14:15 UTC, UristMcKobold approved these changes

2020-08-26 00:18 UTC, TPGPL approved these changes

2020-08-26 00:18 UTC, merged