[RU] Account Restrictions
ppy/osu-wiki pull request #4065
Opened 2020-08-20 17:08 UTC by Airkek

Translate into russian language

2020-08-25 15:36 UTC, UristMcKobold requested changes

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Продолжайте наслаждаться игрой!** Пока ваш аккаунт ограничен и вы ждёте окончания времени наказания, вы можете продолжать играть в игру (конечно же на основном аккаунте!). Все скоры, которые вы п
Пропустил запятую перед «и» в предложении «и вы ждёте окончания времени наказания».
Пропустил запятую после «конечно же» в скобках.
«если аккаунт не будет сброшен» без контекста звучит страшно. Сброшен со скалы? Лучше поточнее сказать. Аккаунт подвергнется ресету? Информация аккаунта будет удалена? Что-то такое.

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Ведите себя правильно.** Мы понимаем, что быть ограниченным может быть обидным или болезненным, но думайте об ограничении как возможности взять небольшой перерыв от сообщества. Попробуйте не связ
Не правильно себя ведите, а «ведите себя примерно». 
Лучше не «может быть обидным или болезненным», а «может быть обидно или неприятно».
Пропустил запятую перед «чтобы». Дальше, непонятно, кто такие «им» в последнем предложении. Кому не дать повлиять? Эмоциям, возможно? Или людям в сообществе? Уточнить надо.

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Вы можете подать апелляцию посредством отправки письма на адрес электронной почты [accounts@ppy.sh](mailto:accounts@ppy.sh) указывая ваше имя пользователя. Обратите внимание на то, что апелляция долж
Пропустил запятую перед «указывая ваше имя пользователя».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **История аккаунта.** Она не должна быть детализированной. История должна включать моменты нарушения главных правил (мульти-аккаунт, передача аккаунта третьим лицам, читерство или другие крупные на
Не «детализированной», а «подробной». Не «главных» правил, а «основных». 
Предпоследнее предложение топорно звучит. Моя переделка: «Вы не обязаны помнить точные даты, каждый свой сайленс или все созданные вами аккаунты, но ваши ответы должны быть честными».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Зачем вы нарушали правила.** Объясните, что сподвигло вас нарушить правила. Это поможет нам (и вам) определить, насколько вероятно то, что вы нарушите правила снова. Если вы продолжали нарушать п
Лишняя запятая перед «почему». Ну или дальше развивай мысль: «нам бы хотелось узнать, почему вы их нарушили».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Откуда у вас появились средства для нарушения правил.** Это в большинстве своем относится к читерству. Мы хотим знать, где вы нашли программы, которые вы использовали, как вы с ними столкнулись и
Пропустил запятую перед «имеются ли они». Ну и в целом конструкция не очень. «как вы с ними  столкнулись, и хранятся ли они на вашем компьютере до сих пор» — лучше.

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Почему мы должны позволить вам вернуться в сообщество.** В большинстве случаев, мы просто хотим быть уверенными, что вы не нарушите правила снова. Пожалуйста, поймите, что чем больше нарушений на
Не «тем сильнее мы будем ждать данный пункт», а «тем больше мы будем смотреть на данный пункт». Ну или типа того. Акцент на том, что они будут пристально смотреть на то, что написано в этом пункте.

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +## Что будет если мою апелляцию одобрят?
Пропустил запятую перед «если».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вы не будете создавать другие аккаунты, будь это для себя или кого-то другого.**
Не «будь это», а «будь они».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вы не будете играть на чужих аккаунтах** включая игру на общем компьютере.
Пропустил запятую перед «включая».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +В некоторых случаях, для разблокированных аккаунтов может быть запрещено участие в турнире, в котором есть значки, как со стороны организатора турнира, так и со стороны другого игрока. Длительность з
Лишняя запятая после «в некоторых случаях». 
Насчёт перевода «значки» не скажу, но мне лично не нравится такой перевод. Я бы не переводил и оставил «бейджи». Ну или хотя бы уточни, что «значки в профиле».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Некоторые аккаунты могут снова получить ограничения после игры! Это результат автоматического процесса и ограничение будет снято в течении 24 часов. Не стесняйтесь задавать вопросы в Twitter [@osusup
Пропустил запятую перед «если» в конце.

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Некоторые нарушения спровоцируют откат статистики вашего аккаунта после снятия ограничений. Это сделано для удаления нечестных скоров, которые были отправлены на сервер с вашего аккаунта **на любом м
«нечестных скоров» звучит по-детски. Скорее уж «нарушающих правила скоров». А ещё не «на любом моде», а «в любом режиме». 
Тут лучше употребить не «также как», а «включая разблокированные медали и значки в профиле».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Она была отправлена слишком рано.** Если время наказания для вашего аккаунта еще не прошло, ваша апелляция будет отклонена. Если вы не знаете, когда вы можете отослать апелляцию - ответьте на наш
Пропустил запятую в конце перед «и мы дадим вам точную дату».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вашей апелляции было недостаточно или она не была полной.** Если апелляция не покрывает 4 пункта, описанные выше, мы попросим вас написать более полное письмо. Это не отматывает время наказания о
Пропустил запятую перед «или она не была полной».
«не покрывает 4 пункта» тоже странно звучит. Лучше «не затрагивает описанные выше пункты».
«отматывает время наказания обратно»? Так не говорят же, скорее «не обнуляет время наказания». 
В скобках я бы написал «(чаще всего это связано с …)».
«стать уверенным» коряво тоже звучит. «подумать над вашими поступками и увериться в том, что вы ничего не забыли».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вы избегали блокировки или играли на других аккаунтах.** Создание другого аккаунта, чтобы играть в онлайне, пока ваш основной аккаунт находится в ограниченном доступе является попыткой избежания
Второе предложение чересчур громоздкое. Переделаю:
`Создание другого аккаунта для игры в онлайне, в то время как ваш основной аккаунт ограничен (рестриктнул), является попыткой обхода блокировки. Подобное действие обнулит время вашего наказания до трёх месяцев с момента создания последнего аккаунта.`
И в целом тут лучше не «избегать», а «обходить». Чаще используется в этом смысле. 

Дальше, «если вы продолжите получать доступ». Не совсем понятно, что ты имел в виду под этим. Тут лучше «если вы продолжаете заходить или играть на мультиаккаунтах».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Ваша история слишком серьезная.** В случаях экстремальных нарушений или игроков, кто снова был ограничен после недавней успешной разблокировки, мы можем просто решить, то ваша история является сл
Не «серьёзная» точно. Но тут сложно, стоит подумать. Грубая?  
Дальше тоже плывёт конструкция предложения. «в случаях экстремальных нарушений, или когда игроки получают рестрикт после недавней разблокировки, мы …».
Опечатка во второй строке, там «что ваша история». 
Последние два предложения на русский язык не похожи. Сейчас перепишу:
`Если это к вам относится, мы советуем вам подождать **значительный срок** перед тем, как снова отправлять обжалование. Убедитесь, что вы больше не будете нарушать правила`

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если вы считаете, что ваши письма не читаются или не рассматриваются должным образом, отправьте нам электронное письмо по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh) содержащее следующ
Пропустил запятую перед «содержащее».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Все письма, отправленные на адрес для отзывов о рассмотрениях апелляций, будут изучены третьими лицами, которые не участвуют в повседневной работе службы поддержки, и помечены для проверки или дальне
Последняя часть предложения не вписывается. Перепишу:
`Все письма, отправленные на этот адрес, будут изучены третьими лицами, которые не участвуют в повседневной работе службы поддержки, а также помечены для проверки или дальнейшего рассмотрения.`

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Вы должны понимать, что отправка писем на этот адрес гарантирует только повторное рассмотрение вашей апелляции, это не гарантирует изменение результата рассмотрения если станет известно, что вы наруш
Пропустил запятую перед «если станет известно».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +**Мы будем отвечать на запросы о рассмотрении/перерассмотрении апелляции только по электронной почте, отправленной на адрес [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** Пожалуйста, не пытай
«только по электронной почте, отправленной на адрес»? Только по письмам тогда уж, почты же не отправляют. 
В скобках «или» с маленькой буквы». 
Лучше не «эту политику», а «эту систему».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Наша ошибка | Нету | Если найдена ошибка, не влияет на аккаунт. |
Ну, «нету» использовать в официальной статье — моветон. «Нет» же. 
Дальше, «если найдена ошибка, она не влияет на аккаунт».

2020-08-25 15:36 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Читерство | 3 месяца | Применение условий апелляции, запрет на участие в турнирах в течение 1 года и полный сброс аккаунта |
Тоже тут лучше не «читерство», а «использование читов». И опять же, «сброс аккаунта» откуда? Со скалы?!

2020-09-01 23:31 UTC, TicClick commented
краткий комментарий: большинство предложений написаны так, что их нужно перевести заново — сумбурно, или косноязычно, или громоздко. в дискорде я озвучил план, по которому я сделаю перевод заново, а этот.. не знаю, честно говоря, что с ним сделать, видимо, отбросить придётся. предлагаю перед переводом относительно длинных статей спрашивать и оценивать свои силы, либо браться за статьи небольшого размера, потому что ревью для них будет более коротким (потому что придётся править меньше) и более полезным

2020-09-02 08:11 UTC, closed without merging