[TR] Add User Configuration File
ppy/osu-wiki pull request #4076
Opened 2020-08-21 17:41 UTC by zeusminus

Add Turkish translations for `User_Configuration_File` article

2020-09-06 19:44 UTC, ahmetuyuklu commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `Width` | Tamsayı | Çözünürlük (`Tam Ekran` modunda `0`) |
"tamsayı" yerine "tam sayı" olmalı

2020-09-06 19:45 UTC, ahmetuyuklu commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `FrameSync` | Metin | Frame kısıtlayıcısı |
16. ve 19. satırdaki "Frame", 131. ve 215. satırda da kullanıldığı gibi "kare" şeklinde çevirilmeli

2020-09-06 19:48 UTC, zeusminus commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `FrameSync` | Metin | Frame kısıtlayıcısı |
Doğru söylüyorsun, ancak bunları böyle yazmamın sebebi oyunun Türkçe lokalizasyonunda böyle yer almaları. Maalesef, teknik sebeplerden dolayı, oyunun çevirilerini de değiştirmenin imkanı yok. 🤷

2020-09-07 10:05 UTC, Lxran requested changes

2020-09-07 10:05 UTC, Lxran commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `ScoreMeterScale` | Decimal | Skor-metre boyutu |
```suggestion
| `ScoreMeterScale` | Ondalık | Skor-metre boyutu |
```

2020-09-07 10:05 UTC, Lxran commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `DisplayStarsMinimum` | Decimal | Haritaları şu zorluktan |
```suggestion
| `DisplayStarsMinimum` | Ondalık | Haritaları şu zorluktan |
```

2020-09-07 10:05 UTC, Lxran commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `DisplayStarsMaximum` | Decimal | şu zorluğa kadar görüntüle |
```suggestion
| `DisplayStarsMaximum` | Ondalık | şu zorluğa kadar görüntüle |
```

2020-09-07 10:05 UTC, Lxran commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `CursorSize` | Decimal | İmleç boyutu |
```suggestion
| `CursorSize` | Ondalık | İmleç boyutu |
```

2020-09-07 10:05 UTC, Lxran commented on wiki/osu!_Program_Files/User_Configuration_File/tr.md
> +| `MouseSpeed` | Decimal | Fare hassasiyeti |
```suggestion
| `MouseSpeed` | Ondalık | Fare hassasiyeti |
```

2020-09-07 11:22 UTC, TicClick approved these changes

2020-09-07 11:22 UTC, merged