[TR] Add Project Loved
ppy/osu-wiki pull request #4078
Opened 2020-08-22 13:05 UTC by ubinici

Add Turkish translations for `Project_Loved` article

2020-09-03 15:21 UTC, 3dsosu commented on wiki/Project_Loved/tr.md
> +**Kaptanlar** olarak bilinen Project Loved Takımı üyeleri spesifik bir oyun modu için beatmap setlerini düzenli olarak aday gösterirler. Neredeyse her zaman için, bu setler osu! topluluğundan gelen g
```suggestion
**Kaptanlar** olarak bilinen Project Loved Takımı üyeleri spesifik bir oyun modu için beatmap setlerini düzenli olarak aday gösterirler. Neredeyse her zaman, bu setler osu! topluluğundan gelen gönderilerden seçilir. Mevcut Sevilen gönderi formlarına ve listelerine aşağıdaki linklerden ulaşılabilir:
```

2020-09-03 15:21 UTC, 3dsosu commented on wiki/Project_Loved/tr.md
> +- [Nitelikli](/wiki/Beatmaps#qualified), [Dereceli](/wiki/Beatmaps#ranked) or [Onaylı](/wiki/Beatmaps#approved) kategorilerinde olmamalı.
```suggestion
- [Nitelikli](/wiki/Beatmaps#qualified), [Dereceli](/wiki/Beatmaps#ranked) ya da [Onaylı](/wiki/Beatmaps#approved) kategorilerinde olmamalı.
```

2020-09-07 09:50 UTC, Lxran requested changes
Minor edits to better reflect the source text. Good work.

2020-09-07 09:50 UTC, Lxran commented on wiki/Project_Loved/tr.md
> +**Project Loved** beatmapleri [Sevilen](/wiki/Beatmaps#loved) kategorisine kazandıran bir oylama plaformudur. Bu proje birincil olarak [Project Loved Takımı](/wiki/People/The_Team/Project_Loved_Team)
```suggestion
**Project Loved** beatmapleri [Sevilen](/wiki/Beatmaps#loved) kategorisine kazandıran oylama plaformudur. Bu proje birincil olarak [Project Loved Takımı](/wiki/People/The_Team/Project_Loved_Team) tarafından yürütülür.
```

2020-09-07 09:50 UTC, Lxran commented on wiki/Project_Loved/tr.md
> +Sevilen kategorisine giren beatmapler birtakım kuralları takip etmek zorundadır:
```suggestion
Sevilen kategorisine giren beatmapler birtakım ek kuralları takip etmek zorundadır:
```

2020-09-07 11:21 UTC, TicClick approved these changes

2020-09-07 11:21 UTC, merged