Ru rules visual content considerations
ppy/osu-wiki pull request #4120
Opened 2020-09-01 12:54 UTC by GoodbyeShin

ru.md created and added RU translation

2020-09-01 14:55 UTC, UristMcKobold requested changes

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Изображения, имитирующие половой акт, содержащие объекты или манерность, имитирующие или ссылающиеся на гениталии (например, имитация пениса), и другие подобные материалы — запрещены.
```suggestion
Запрещены изображения, имитирующие половой акт или гениталии (например, объекты фаллической формы) и другие подобные материалы.
```
Использование «имитация» три раза в одном предложении — чрезмерно много! Ну и сильно запутал там предложение.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Детская порнография
```suggestion
### Сексуальный контент с участием несовершеннолетних
```
Ну так явно не надо, там не только порнография в оригинале.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Если возраст персонажа на картинке очевиден не сразу (например, из-за внешнего вида), то отсутствие вторичных половых признаков, вероятно, укажет на несовершеннолетнего персонажа. Подобный контент, к
```suggestion
Если возраст персонажа на картинке очевиден не сразу (например, из-за внешнего вида), то отсутствие вторичных половых признаков, вероятно, укажет на несовершеннолетнего персонажа. Подобный контент, если его можно воспринять как сексуальный, запрещен.
```

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Эротический контент и сексуальность
```suggestion
### Эротический и сексуальный контент
```
"graphic sexuality" — это всё же не просто сексуальность.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +С точки зрения эротической небрежности это также распространяется на женское бельё и откровенную одежду, включая её атрибуты, которые разработаны и предназначены специально для секса. Иными словами,
```suggestion
Это также распространяется на нижнее бельё и откровенную одежду, включая её атрибуты, которые разработаны и предназначены специально для секса. Иными словами, сюда входит всё, что используют ради секса, то есть различные предметы фетиша и откровенное нижнее бельё.
```
Непростой абзац, но «эротическая неброжность» точно не должна использоваться.
И не только женское, мужское тоже. Почему «расстройствам сексуального предпочтения»?! Странный термин.
Честно, в последнем предложении не могу здраво перевести «full depiction of lingerie», поэтому получается отсебятина. Но дух передал!

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Кроме того, под запрет подпадет так называемый шок-контент — провокационные произведения искусства.
```suggestion
Кроме того, под запрет попадают изображения целиком, если общая атмосфера в них может быть расценена неприличной или вовсе сексуальной.
```
Откуда там шок-контент? Произведения искусства? В оригинале совсем другой смысл.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Изготовление и употребление наркотических веществ
```suggestion
### Изготовление или употребление наркотических веществ
```
Мелочь, но важно.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Контент с изображением применения приспособлений (к примеру, бонги, ложечки для коки, использованные иглы и другая атрибутика) или их наличия, использующихся в контексте введения наркотиков.
```suggestion
Запрещены изображения с приспособлениями, которые используются в контексте введения наркотиков (к примеру, бонги, ложечки для кокаина, использованные иглы и другая атрибутика).
```
«контент с изображением» — усложнение ненужное. «применение» тут тоже особо не нужно, достаточно просто указать, что запрещено их показывать, это подразумевает и применение в том числе.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Этим правилом запрещаются частично или полностью легальные вещества (например, марихуана), даже если они разрешены в некоторых странах. Относящиеся к этим наркотикам материалы и связанные с ними сооб
```suggestion
Этим правилом запрещаются частично или полностью легальные вещества (например, марихуана), даже если они разрешены в некоторых странах. Также запрещены относящиеся к этим наркотикам ресурсы и связанные с ними сообщества.
```

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Провокация и подстрекательское содержание
```suggestion
### Провокационный контент
```
До этого у тебя везде «контент», а тут вдруг «содержание». Подстрекающий в общем-то то же самое, что и провокационный в контексте этого правила.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сюда входят изображения осквернения культурных и религиозных ценностей, предназначенные для преднамеренного разжигания ненависти, например, использование нацистской или фашистской символики (свастики
```suggestion
Сюда входит осквернение культурных и религиозных ценностей, предназначенное для преднамеренного разжигания ненависти. Например, использование нацистской или фашистской символики (свастики), антисемитских материалов и терминологии, или того, что поддерживает вред по отношению к любой социальной, расовой, культурной или политической группе или дискриминирует её.
```
Немного поменял, чтобы читалось проще, а то перемудрил.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +## Допустимое визуальное содержание
```suggestion
## Допустимый визуальный контент
```
Тоже содержание, а не контент почему-то.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Безвредный контент, который подходит для всех возрастов — идеален для osu! Если сомневаетесь, загляните в местные ресурсы, чтобы не ошибиться — если содержание подходит для аудитории 12+ (PEGI 12 или
```suggestion
Безвредный контент, который подходит для всех возрастов — идеален для osu!. Если сомневаетесь, загляните в различные местные ресурсы, чтобы не ошибиться — если содержание приемлемо для аудитории 12+ (PEGI 12 или рейтинг PG-13 в США и странах Содружества), то  проблем возникнуть не должно.
```

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сильно не увлекайтесь, однако, используя здравый смысл, **разрешается** использовать следующее:
```suggestion
При условии, что вы подходите к вопросу добросовестно и со здравым смыслом, **разрешается** использовать следующее:
```
Мне кажется, что «сильно не увлекайтесь» тут всё же лишнее.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Изображения купальных костюмов в «разумных» пределах не запрещены. Однако, следует знать меру. Убедитесь, что картинка не нарушает правила позирования и намеков, перечисленные в предыдущих разделах.
```suggestion
Изображения купальных костюмов в «разумных» пределах не запрещены. Однако, следует знать меру. Убедитесь, что картинка не нарушает правила позирования и намёков, перечисленные в предыдущих разделах.
```
Ё.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чрезмерными будут считаться изображения, выходящие далеко за пределы сомнительного содержания, например, когда персонаж носит купальник слишком маленького размера, чтобы адекватно скрыть наготу от по
```suggestion
Чрезмерными будут считаться изображения, выходящие далеко за пределы спорного содержания, например, когда персонаж носит купальник слишком маленького размера, который не может адекватно скрыть наготу от посторонних глаз. Чрезмерный — довольно обширный термин, но обычно он означает, что купальник плохо скрывает «причиндалы» персонажей.
```

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Слишком откровенные купальники, оставляющие мало пространства для фантазии, как правило, не допускаются. В сложных случаях учитывается мнение большинства, а решение остается за модерацией.
```suggestion
Слишком откровенные или маленькие купальники, как правило, не допускаются. В сложных случаях учитывается мнение большинства, а решение остается за модерацией.
```
Разве не наоборот? Такие купальники должны оставлять много пространства для фантазии. Но мне вообще оборот этот не нравится.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Легкое или умеренное насилие
```suggestion
### Лёгкое или умеренное насилие
```

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Разрешается использовать изображения, на которых присутствуют сцены военных действий, драки, а также физическая активность с мелкими ранами или травмами. Правда, всё это при условии, что отсутствует
```suggestion
Разрешается использовать изображения, на которых присутствуют сцены военных действий, драки, а также физическая активность с мелкими ранами или травмами. Правда, всё это при условии, что отсутствует явно выраженное насилие, расчленёнка или тяжкие телесные повреждения.
```
Снова "горе" не так перевёл.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чтобы этого добиться, художественная нагота должна подходить по смыслу к другому контенту в каждом конкретном случае.
```suggestion
Чтобы этого добиться, использование художественной наготы должно иметь смысл в конкретной карте с конкретной музыкой, она должна подходить ей тематически. 
```
Последняя часть предложения как-то лишена смысла. Но предложение непростое. Мой вариант включает немного отсебятины, так что думай сам.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Романтика, флирт или интимная привязанность
```suggestion
### Романтика, флирт или близкие отношения
```
Впервые слышу выражение «интимная привязанность».

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Шутки ради, если вам легко и комфортно показать рисунок семье или тому, кого вы считаете авторитетом, то скорее всего, проблем не возникнет.
```suggestion
На практике, вы можете воспользоваться следующим принципом: если вы в состоянии спокойно показать изображение своей семье или тому, кого вы считаете авторитетом, то, скорее всего, проблем не возникнет.
```
«anecdotal» в данном контексте не относится к нашим «анекдотам», слово идёт в значении: субъективно, основано только на собственном опыте.

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Предусматривалось, что решение будет окончательным и не может быть оспорено, но есть исключение, например, при добросовестной попытке внести изменения и исправить спорные моменты. Если нет сомнений в
```suggestion
Предусматривается, что решение будет окончательным и не может быть оспорено, но бывают исключения, например, при добросовестной попытке внести изменения и исправить спорные моменты. Подобные запросы можно делать в любом количестве, но в разумных пределах.
```

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +еределанный контент может быть отклонен в дальнейших запросах на оценку и, таким образом, признан непригодным для использования в карте, если считается выполненным недобросовестно (например, чрезмерн
```suggestion
Переделанный контент может быть отклонен при дальнейших запросах на оценку и, таким образом, признан непригодным для использования в карте, если считается выполненным недобросовестно (например, чрезмерная или плохо проведённая цензура). Данное решение уже не оспорить.
```

2020-09-01 14:55 UTC, UristMcKobold commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Не передавайте и не обсуждайте с администрацией игры (также известной как команда osu!) совершенно неприемлемый контент, если он признан непригодным. Спорить с администрацией в таких случаях нельзя,
```suggestion
Вышеперечисленные действия не будут выполняться, если администрация игры (также известная как команда osu!) посчитает, что вы использовали совершенно неприемлемый контент. Спорить с администрацией в таких случаях нельзя, а решение будет окончательным и не может быть оспорено в дальнейшем. За подобные попытки будут наказаны все участники дискуссии.
```

2020-09-01 15:35 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Не передавайте и не обсуждайте с администрацией игры (также известной как команда osu!) совершенно неприемлемый контент, если он признан непригодным. Спорить с администрацией в таких случаях нельзя,
targeting, readability

2020-09-01 15:37 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чтобы не возникло недопонимания, это правило действует на сомнительный или вызывающий контент, а также контент 18+ (NSFW).
revision

2020-09-01 15:38 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +## Допустимое визуальное содержание
слишком много повторов, но не всегда это нужно менять

2020-09-01 15:39 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +## Допустимое визуальное содержание
revision

2020-09-01 15:42 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Этим правилом запрещаются частично или полностью легальные вещества (например, марихуана), даже если они разрешены в некоторых странах. Относящиеся к этим наркотикам материалы и связанные с ними сооб
отлично, переписал свой собственный вариант в нечто

2020-09-01 15:44 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сильно не увлекайтесь, однако, используя здравый смысл, **разрешается** использовать следующее:
familiarity with text

2020-09-01 15:45 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Безвредный контент, который подходит для всех возрастов — идеален для osu! Если сомневаетесь, загляните в местные ресурсы, чтобы не ошибиться — если содержание подходит для аудитории 12+ (PEGI 12 или
better readability

2020-09-01 15:46 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Контент с изображением применения приспособлений (к примеру, бонги, ложечки для коки, использованные иглы и другая атрибутика) или их наличия, использующихся в контексте введения наркотиков.
way better readability

2020-09-01 15:47 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Изготовление и употребление наркотических веществ
поменял собственный вариант на нечто

2020-09-01 15:47 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Кроме того, под запрет подпадет так называемый шок-контент — провокационные произведения искусства.
отсебятина, которая каким-то образом просочилась

2020-09-01 15:52 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +С точки зрения эротической небрежности это также распространяется на женское бельё и откровенную одежду, включая её атрибуты, которые разработаны и предназначены специально для секса. Иными словами,
термин применяется в психиатрии, можно избавиться!

2020-09-01 15:52 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Эротический контент и сексуальность
уточнение

2020-09-01 15:53 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Детская порнография
поменял зачем-то собственный хороший вариант на нечто

2020-09-01 15:55 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сюда относятся имитации половых актов, похоть или домогательства. Контент подобного рода в контексте аниме часто называют «эччи».
overall better readability, good change

2020-09-01 15:56 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +### Намек на секс
Большой разницы здесь не вижу

2020-09-01 15:58 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Картинки с изображением запекшейся крови, расчленёнка, увечья, тяжелые ранения или визуальное отображение очевидных причин мучительной смерти (к примеру, удушье, повешение или кровотечение), неприемл
Как правило, gore — это как раз разчленёнка better readability overall

2020-09-01 15:59 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сюда относится насилие по отношению к людям, гуманоидным персонажам или животным.
поменял зачем-то собственный хороший вариант на нечто (3)

2020-09-01 16:05 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +В графическом контенте (например, фон карты, скины и другие объекты, или связанные с видео ресурсы, распространяемые с мапсетом) **НЕДОПУСТИМО** следующее:
better readability overall

2020-09-01 16:16 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +В основе оценки визуального контента лежит непосредственно то, что представлено на изображении, а не его источник.
отсебятина, но смысл передаёт полностью, не вижу проблемы. а вот дополнение можно оставить, как в оригинале

2020-09-01 16:20 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +В первую очередь, придерживайтесь [категории PEGI 12](https://ru.wikipedia.org/wiki/Pan_European_Game_Information) как описано ниже, с некоторыми дополнениями. Если рейтинговые системы конфликтуют, п
внутренние правила, скорее всего, просочились из оригинала, можно было опустить или переписать

2020-09-01 16:28 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чтобы этого добиться, художественная нагота должна подходить по смыслу к другому контенту в каждом конкретном случае.
better readability overall, good change

2020-09-01 16:33 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +еределанный контент может быть отклонен в дальнейших запросах на оценку и, таким образом, признан непригодным для использования в карте, если считается выполненным недобросовестно (например, чрезмерн
minor fixes

2020-09-01 22:59 UTC, ryuu requested changes

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Изображения полового акта, прелюдии и полной фронтальной наготы с чётко видимыми гениталиями — запрещены без исключений.
не фронтальная, а полная
в русском full frontal -- это про наготу в целом
https://en.wikipedia.org/wiki/Full_Frontal

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Это также распространяется на нижнее бельё и откровенную одежду, включая её атрибуты, которые разработаны и предназначены специально для секса. Иными словами, сюда входит всё, что используют ради сек
специально для **секса**.. всё, что используют ради **секса**

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Этим правилом запрещаются частично или полностью легальные вещества (например, марихуана), даже если они разрешены в некоторых странах. Также запрещены относящиеся к этим наркотикам ресурсы и связанн
мне кажется, что частично = даже если они разрешены в некоторых странах
поэтому, наверное, часть после скобок можно убрать

ресурсы -> сайты, потому что можно неоднозначно прочитать

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Проще говоря, любое упоминание наркотических веществ, как правило, недопустимо. По возможности избегайте этого.
у тебя _как правило_ совершенно недавно было в тексте
можно заменить на «обычно» или что-то похожее

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сюда входит осквернение культурных и религиозных ценностей, предназначенное для преднамеренного разжигания ненависти. Например, использование нацистской или фашистской символики (свастики), антисемит
последнее предложение написано коряво, потому что два раза стоит _или_

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Безвредный контент, который подходит для всех возрастов — идеален для osu!. Если сомневаетесь, загляните в различные местные ресурсы, чтобы не ошибиться — если содержание приемлемо для аудитории 12+
различные местные ресурсы? а какие? нужна конкретика
двойной пробел в «то проблем возникнуть не должно»

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чрезмерными будут считаться изображения, выходящие далеко за пределы спорного содержания, например, когда персонаж носит купальник слишком маленького размера, который не может адекватно скрыть наготу
умоляю, замени «причиндалы» на что-нибудь, потому что это просторечие

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Слишком откровенные или маленькие купальники, как правило, не допускаются. В сложных случаях учитывается мнение большинства, а решение остается за модерацией.
это уже написано выше
>например, когда персонаж носит купальник слишком маленького размера, который не может адекватно скрыть наготу от посторонних глаз

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Разрешается использовать изображения, на которых присутствуют сцены военных действий, драки, а также физическая активность с мелкими ранами или травмами. Правда, всё это при условии, что отсутствует
умеренное насилие звучит странно, предлагаю на что-нибудь заменить
расчленёнка -> расчленение

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чтобы этого добиться, использование художественной наготы должно иметь смысл в конкретной карте с конкретной музыкой, она должна подходить ей тематически.
может, _она_ заменить на _и_? тогда предложение будет проще читаться

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сюда также относятся «кокетливые» изображения, которые оправданно считаются игривыми, при условии что они не впадают в крайность и не нарушают другие пункты.
после «при условии» нужна запятая

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +На практике, вы можете воспользоваться следующим принципом: если вы в состоянии спокойно показать изображение своей семье или тому, кого вы считаете авторитетом, то, скорее всего, проблем не возникне
>кого вы считаете авторитетом

(условно) мой авторитет может любить гуро
это не значит, что ему можно доверять
нужно написать о том, что это должен быть человек, который критически относится к таким вещам
ну или может просто адекватно оценить картинку

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Если сомневаетесь в том, не нарушает ли контент правила, лучше отправить официальный запрос номинатору карт, который затем передаст проблему команде модерации для дальнейшей оценки и принятия решения
после «официальный запрос номинатору карт» предлагаю поставить точку, после чего _который_ заменить на _он_, потому что предложение перегруженное

>при этом учитывается мнение большинства (>70%)

звучит как-то оторванно от всего прошлого предложения

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Предусматривается, что решение будет окончательным и не может быть оспорено, но бывают исключения, например, при добросовестной попытке внести изменения и исправить спорные моменты. Подобные запросы
у тебя тут сразу два предложения звучат как противоречия 
если первое ещё можно оставить, то второе точно нет
потому что любое количество подразумевает ... любое количество
а разумные пределы -- это уже ограничение

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Переделанный контент может быть отклонен при дальнейших запросах на оценку и, таким образом, признан непригодным для использования в карте, если считается выполненным недобросовестно (например, чрезм
>если считается выполненным недобросовестно (например, чрезмерная или плохо проведённая цензура)

я бы поставила это после «может быть отклон***ё***н при дальнейших запросах на оценку», потому что сразу хочется конкретики, а почему именно-то?

очень субъективная придирка, но в конце было бы лучше написать «данное решение уже не оспаривается»

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Вышеперечисленные действия не будут выполняться, если администрация игры (также известная как команда osu!) посчитает, что вы использовали совершенно неприемлемый контент. Спорить с администрацией в
«вышеперечисленные процедуры» звучит лучше, как мне кажется
но, опять же, это очень субъективная придирка

2020-09-01 22:59 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Согласно [правилу сообщества №5](/wiki/Rules#community-rules), визуальный контент в загруженных на сервер картах должен быть приемлем для всех возрастов, включая элементы скинов, фоны для карт, элеме
включая **элементы** скинов, фоны для карт, **элементы** сториборда 
лучше будет, если написать «включая фоны для карт, элементы скинов и сториборда»

2020-09-01 23:25 UTC, TicClick requested changes
переведено достаточно неплохо — переписывать большую часть точно не нужно

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Безвредный контент, который подходит для всех возрастов — идеален для osu!. Если сомневаетесь, загляните в различные местные ресурсы, чтобы не ошибиться — если содержание приемлемо для аудитории 12+
+1, немного расшифрую: мне понадобилось время (причём достаточно большое по моим меркам), чтобы осознать, что здесь под ресурсами понимаются гайдлайны и своды правил типа PEGI/ESRB

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Кроме того, под запрет попадают изображения целиком, если общая атмосфера в них может быть расценена неприличной или вовсе сексуальной.
```suggestion
Кроме того, под запрет попадают изображения целиком, если общая атмосфера в них может быть расценена как неприличная или сексуальная.
```

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Запрещены изображения с приспособлениями, которые используются в контексте введения наркотиков (к примеру, бонги, ложечки для кокаина, использованные иглы и другая атрибутика).
введение у меня почему-то только с инъекциями связано, но как же почтовые марки!
```suggestion
Запрещены изображения с объектами, которые используются в контексте потребления наркотиков (к примеру, бонги, ложечки для кокаина, использованные иглы и другая атрибутика).
```

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Неоднозначные случаи упоминания наркотических веществ, внесённых в списки легальных в большинстве стран (например, злоупотребление кодеиносодержащими смесями с прометазином и т.п.), здесь, как правил
> _кодеиносодержащими смесями с прометазином_

это слишком специфично, лучше переделать на _так называемые аптечные наркотики_, чтобы потребителю (этой статьи) было более понятно, либо на _лекарства, содержащие наркотические вещества_

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Этим правилом запрещаются частично или полностью легальные вещества (например, марихуана), даже если они разрешены в некоторых странах. Также запрещены относящиеся к этим наркотикам ресурсы и связанн
добавлю к замечанию, что в оригинале, похоже, речь про самих наркоманов и драг-дилеров как людей, а «сообщества» звучит слишком обтекаемо

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Изображения купальных костюмов в «разумных» пределах не запрещены. Однако, следует знать меру. Убедитесь, что картинка не нарушает правила позирования и намёков, перечисленные в предыдущих разделах.
- средство выразительности — это курсив, а не кавычки;
- второе предложение звучит рвано, склей с первым через запятую;
- _правила позирования и намёков_, я уверен, можно переформулировать лучше

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чрезмерными будут считаться изображения, выходящие далеко за пределы спорного содержания, например, когда персонаж носит купальник слишком маленького размера, который не может адекватно скрыть наготу
+1, кроме того, изображения не могут быть чрезмерными, это прилагательное относится к чему-то, обозначающему свойство, нежели предмет. как насчёт _Неприемлемыми_ или _Так, не подойдут ..._?

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Разрешается использовать изображения, на которых присутствуют сцены военных действий, драки, а также физическая активность с мелкими ранами или травмами. Правда, всё это при условии, что отсутствует
+1, и ещё отсутству**ю**т

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Обложка альбома «Immersion» группы Pendulum — хороший пример применения этого правила. На фото присутствуют обнаженные мужчина и женщина, сжимающие друг другу руки. Такое использовать можно, поскольк
- когда я читаю _сжимающие друг другу руки_, я думаю точно не том, что происходит на той обложке.
- _Такое_ -> _Подобные изображения_, и тогда от второго _изображения_ нужно избавиться;
- _а также_ -> _которое также_

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +На практике, вы можете воспользоваться следующим принципом: если вы в состоянии спокойно показать изображение своей семье или тому, кого вы считаете авторитетом, то, скорее всего, проблем не возникне
после «на практике» не должно быть запятой.

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Если сомневаетесь в том, не нарушает ли контент правила, лучше отправить официальный запрос номинатору карт, который затем передаст проблему команде модерации для дальнейшей оценки и принятия решения
да, плюс _Если **вы** сомневаетесь_

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Переделанный контент может быть отклонен при дальнейших запросах на оценку и, таким образом, признан непригодным для использования в карте, если считается выполненным недобросовестно (например, чрезм
фраза в целом корявая, надо переписать бы

2020-09-01 23:25 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Вышеперечисленные действия не будут выполняться, если администрация игры (также известная как команда osu!) посчитает, что вы использовали совершенно неприемлемый контент. Спорить с администрацией в
хотя aka — это как раз also known as, _также известная как команда osu!_ тут звучит плохо, лучше написать _иными словами, ..._

2020-09-01 23:28 UTC, ryuu commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +На практике, вы можете воспользоваться следующим принципом: если вы в состоянии спокойно показать изображение своей семье или тому, кого вы считаете авторитетом, то, скорее всего, проблем не возникне
аж с точкой написал!

2020-09-02 20:02 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Несмотря на то, что изображения в старых картах могут нарушать эти правила, вы не можете использовать их как аргумент для разрешения собственных конфликтных ситуаций. Редактирование визуальной состав
поторопился принять правку кобольда, здесь очевидная ошибка и нужно переписать

2020-09-02 23:54 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Безвредный контент, который подходит для всех возрастов — идеален для osu!. Если сомневаетесь, загляните в различные местные ресурсы, чтобы не ошибиться — если содержание приемлемо для аудитории 12+
данный момент исправить очень просто

2020-09-03 00:10 UTC, GoodbyeShin commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Неоднозначные случаи упоминания наркотических веществ, внесённых в списки легальных в большинстве стран (например, злоупотребление кодеиносодержащими смесями с прометазином и т.п.), здесь, как правил
мы не ищем лёгких путей

2020-09-06 13:38 UTC, TicClick requested changes
надеюсь, последняя порция замечаний, постарался исправить все шероховатости в формулировках и стилистике. они достаточно важные, по возможности прими их все

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сюда относятся различные свидетельства нарушения этих правил (например, из-за недостатка внимания).
громоздко, поэтому нужно переписать на, например, такое
```suggestion
Кроме того, не ссылайтесь на уже существующие карты с подобным контентом, имеющие таблицы рекордов. Обстоятельства и правила, при которых их разрешили, отличаются от сегодняшних.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Изображение сцен насилия, расчленения, увечий, тяжёлых ранений, или визуальное отображение очевидных причин недавней смерти (к примеру, от удушья, повешения или кровотечения).
два предложения нужно связать.
```suggestion
Сюда относится насилие по отношению к людям, человекоподобным существам или любым животным. Примеры включают в себя изображение сцен насилия, расчленения, увечий, тяжёлых ранений, или визуальное отображение очевидных причин недавней смерти (к примеру, от удушья, повешения или кровотечения).
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Имитации полового акта или гениталии (например, объекты фаллической формы), и другие подобные материалы.
```suggestion
Сюда относятся имитирование полового актаа и физический контакт непристойного или похотливого характера, а также имитация гениталий (например, с помощью объектов фаллической формы), и другие подобные вещи.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Запрещены откровенные визуальные образы, которые подразумевают или намекают на сексуальное намерение или желание. Не используйте откровенные визуальные образы, которые приглашают или иным образом нед
```suggestion
Запрещены изображения, которые подразумевают или намекают на сексуальное намерение или желание. Не используйте визуальные образы, которые приглашают или иным образом недвусмысленно намекают на секс, в частности, содержат приглашающие или подманивающие жесты.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Это также относится к «случайному» позированию, например, при изображении персонажей, застигнутых врасплох во время купания, или в других неловких ситуациях.
```suggestion
Это также относится к «случайному» позированию, например, при изображении персонажей, застигнутых врасплох во время купания или в других неловких ситуациях.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Изображения полового акта, прелюдии и полной наготы с чётко видимыми гениталиями, запрещены без исключений.
```suggestion
Изображения полового акта, прелюдии и полной наготы с чётко видимыми гениталиями запрещены без исключений.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Это также распространяется на нижнее бельё и откровенную одежду, включая её атрибуты, которые разработаны и предназначены специально ради секса. Иными словами, сюда входит всё, что используют ради се
```suggestion
Это также распространяется на нижнее бельё и откровенную одежду, включая её атрибуты или самостоятельные предметы, которые разработаны и предназначены для секса.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Запрещены изображения с объектами, которые используются в контексте потребления наркотиков (к примеру, бонги, ложечки для кокаина, использованные иглы и другая атрибутика).
```suggestion
Запрещены изображения с объектами, которые используются в контексте употребления наркотиков (к примеру, бонги, ложечки для кокаина, использованные иглы и другая атрибутика).
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Этим правилом запрещаются частично или полностью легальные вещества (например, марихуана). Также запрещены визуальные образы подобных наркотиков или людей, задействованных в их распространении.
пожалуйста, давайте не будем забывать про наркоманов
```suggestion
Этим правилом запрещаются частично или полностью легальные вещества (например, марихуана). Также запрещены визуальные образы наркотиков или людей, задействованных в их употреблении или распространении.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Сюда входит осквернение культурных и религиозных ценностей, предназначенное для преднамеренного разжигания ненависти. Например, использование нацистской или фашистской символики (свастики), антисемит
читается лучше
```suggestion
Сюда входит осквернение культурных и религиозных ценностей, предназначенное для преднамеренного разжигания ненависти. К примерам подобного относятся использование нацистской или фашистской символики (свастики), антисемитских материалов и терминологии, а также ресурсы или высказывания, способствующие дискриминации по отношению к любой социальной, расовой, культурной или политической группе.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Безвредный контент, который подходит для всех возрастов — идеален для osu!. Если вы сомневаетесь, чтобы не ошибиться, сверьтесь с системами рейтинга контента (например, PEGI 12 или рейтинг PG-13 в СШ
```suggestion
Безвредный контент, который подходит для всех возрастов, идеален для osu!. Если вы сомневаетесь, сверьтесь с системами рейтинга контента (например, PEGI 12 или рейтинг PG-13 в США и странах Содружества): то, что разрешено ими, разрешено почти повсеместно.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Изображения купальных костюмов в *разумных* пределах не запрещены. Также необходимо учитывать правила позирования, перечисленные в предыдущих разделах.
```suggestion
Изображения купальных костюмов в *разумных* пределах не запрещены. При этом необходимо учитывать правила позирования, перечисленные в предыдущих разделах.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +В спорных моментах учитывается мнение большинства, а решение остаётся за модерацией.
ты так написал, как будто публика может не только отклонить, но и одобрить сомнительные картинки, в то время как в оригинале — только про запрет:
_Swimsuits ... are generally not allowed if they are in good faith, considered questionable by a reasonable quantity of users._

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Чтобы этого добиться, использование художественной наготы должно иметь смысл в конкретной карте с конкретной музыкой, и должна подходить ей тематически.
```suggestion
Чтобы этого добиться, использование художественной наготы должно иметь смысл в конкретной карте с конкретной музыкой и подходить ей тематически. 
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Обложка альбома «Immersion» группы Pendulum — хороший пример применения этого правила. Напротив друг друга на фото присутствуют обнаженные мужчина и женщина. Разрешается использовать подобные образы,
```suggestion
Обложка альбома «Immersion» группы Pendulum — хороший пример применения этого правила. Напротив друг друга на фото присутствуют обнаженные мужчина и женщина, но интимных частей тела там нет, само изображение небольшое, не носит сексуальный характер и подходит карте в контексте треков с этого альбома.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +На практике вы можете воспользоваться следующим способом: если вы в состоянии спокойно показать изображение своей семье или гораздо более опытному человеку с критическим мышлением, то, скорее всего,
```suggestion
На практике вы можете воспользоваться следующим способом: если вы в состоянии спокойно показать изображение своей семье или более опытному человеку с критическим мышлением, то, скорее всего, проблем не возникнет.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Если вы сомневаетесь в том, не нарушает ли контент правила, лучше отправить официальный запрос номинатору карт. Он передаст вашу проблему команде модерации для дальнейшей оценки, а решение будет прин
```suggestion
Если вы сомневаетесь в том, не нарушает ли контент правила, лучше отправить официальный запрос номинатору карт. Он передаст вашу проблему команде модерации для дальнейшей оценки, а решение будет принято с учётом мнения большинства модераторов (>70 %).
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Визуальный контент, который вернули вам на доработку, может быть признан выполненным недобросовестно (например, в случае чрезмерной или плохо проведённой цензуры). В таком случае вам могут отказать в
```suggestion
Модераторы могут попросить вас изменить сомнительное изображение, чтобы оно соответствовало правилам. Если такие будут признаны недобросовестными (например, в случае чрезмерной или плохо проведённой цензуры), вам могут отказать в дальнейших запросах на его оценку, и оспорить это будет невозможно.
```

2020-09-06 13:38 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/ru.md
> +Если контент признан совершенно непригодным администрацией игры (иными словами, командой osu!), то вся вышеперечисленная последовательность действий осуществляться не будет. В таком случае решение бу
```suggestion
Если администрация игры (иными словами, команда osu!) признаёт контент совершенно неприемлемым, то все описанные действия проводиться не будут. В таком случае решение будет окончательным, а за попытки его оспорить будут наказаны все участники дискуссии.
```

2020-09-06 17:38 UTC, TicClick approved these changes

2020-09-06 17:40 UTC, merged

2020-09-06 17:44 UTC, TicClick commented
я и @ryuu внесли последние правки перед публикацией (бо̀льшая часть предложений и исправлений — от неё), теперь всё готово