[ID] Rules/Content Usage Guidelines
ppy/osu-wiki pull request #4134
Opened 2020-09-03 18:48 UTC by fajar13k

Add Bahasa Indonesia translation to `Rules/Content Usage Guidelines` article

2020-09-04 03:58 UTC, troke12 commented on wiki/Rules/Song_Content_Rules/id.md
> +# Song content rules
Peraturan Konten Musik

2020-09-04 04:02 UTC, troke12 commented on wiki/Rules/Song_Content_Rules/id.md
> +Tidak sedikit genre musik yang mengandung lirik eksplisit dengan tujuan artistik atau mengikuti genre yang dialiri, dan meskipun konten yang tidak senonoh dan eksplisit tidak secara langsung dilarang
Tidak banyak genre musik yang mengandung lirik eksplisit dengan tujuan artistik atau mengikuti genre yang dialiri, dan meskipun terdapat konten yang tidak senonoh dan eksplisit tidak secara langsung dilarang, trek yang mengandung vulgaritas ekstrem atau dibuatnya memang sengaja untuk mengejutkan atau memancing emosi orang lain sangat tidak diperbolehkan.

2020-09-04 04:04 UTC, troke12 commented on wiki/Rules/Song_Content_Rules/id.md
> +Jika kamu masih belum yakin bagaimana penggunaan lagu yang ingin kamu gunakan berdasarkan pedoman ini, ajukan pertanyaan kepada anggota [Nomination Assessment Team](/wiki/People/The_Team/Nomination_A
Jika kamu masih bingung dengan pedoman penggunaan lagu ini, kamu bisa mengajukan pertanyaan kepada anggota

2020-09-04 04:13 UTC, fajar13k commented on wiki/Rules/Song_Content_Rules/id.md
> +# Song content rules
Ya gusti judul sampe kelewat

2020-09-04 15:26 UTC, troke12 commented on wiki/Rules/id.md
> +2. **Bermain adil.** Menggunakan utilitas pihak ketiga dalam bentuk apa pun demi memperoleh keuntungan apa pun tidak diperbolehkan. Hal ini meliputi program makro, program yang membantu sasaran kurso
2. **Bermain adil.** Menggunakan program pihak ketiga dalam bentuk apa pun demi memperoleh keuntungan apa pun sangat tidak diperbolehkan. Hal ini meliputi program makro, program yang membantu sasaran kursor, modifikasi skala waktu, dan sebagainya. Jika suatu program melakukan sesuatu untuk membantumu memainkan permainan yang seharusnya kamu lakukan sendiri, hal itu tidak baik!

2020-09-04 15:29 UTC, troke12 commented on wiki/Rules/id.md
>  3. **Bersikap baik satu sama lain.** Pelecehan atau hal buruk lainnya tidak diterima di dalam komunitas osu!. Kita di sini untuk mengeklik lingkaran, memukul drum, menangkap buah, dan menekan hingga
3. **Bersikap baik dan saling menghormati satu sama lain.** Pelecehan atau hal buruk lainnya tidak diterima di dalam komunitas osu!. Kita di sini untuk menekan note irama musik yang berbentuk lingkaran, memukul drum, menangkap buah, dan menekan hingga delapan belas kunci sekaligus, dan bukan untuk menjadi bajingan.

2020-09-04 15:34 UTC, troke12 commented on wiki/Rules/id.md
>  6. **Jika peraturan tidak berlaku, akal sehat harus.** Bagian Administrasi memiliki kebijaksanaan spesifik untuk menerapkan penilaian mereka atas hal ini sesuai keinginan mereka.
6. **Jika peraturan tidak berlaku, atau sudah dilanggar** Bagian Administrasi memiliki kewenangan spesifik untuk memberi penilaian mereka atas terhadap pelanggaran spesifik sesuai keinginan mereka.

gk ngerti apa maskudnya akal sehat harus

2020-09-04 15:45 UTC, fajar13k commented on wiki/Rules/id.md
>  6. **Jika peraturan tidak berlaku, akal sehat harus.** Bagian Administrasi memiliki kebijaksanaan spesifik untuk menerapkan penilaian mereka atas hal ini sesuai keinginan mereka.
Ini kalo dari artikel aslinya common sense sih.
Gatau nerjemahinnya gimana, paling jadi, 
> Jika peraturan di atas tidak berlaku, pakai akal sehat (common sense)

Gitu aja?

2020-09-04 16:34 UTC, troke12 commented on wiki/Rules/id.md
>  6. **Jika peraturan tidak berlaku, akal sehat harus.** Bagian Administrasi memiliki kebijaksanaan spesifik untuk menerapkan penilaian mereka atas hal ini sesuai keinginan mereka.
boleh itu pakailah akal sehatmu

2020-09-05 02:30 UTC, troke12 submitted a review, later dismissed

2020-09-05 03:22 UTC, TicClick requested changes

2020-09-05 03:22 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/id.md
> +Perlu diingat bahwa ini merupakan gim ritme dan secara ketat membahasa membahas hal itu sesuai dengan [Peraturan Komunitas](/wiki/Rules#community-rules) #3, konten yang diangap terlalu politis oleh p
```suggestion
Perlu diingat bahwa ini merupakan gim ritme dan secara ketat membahasa membahas hal itu sesuai dengan [Peraturan Komunitas \#3](/wiki/Rules#peraturan-komunitas), konten yang diangap terlalu politis oleh pemerintah dilarang digunakan.
```

2020-09-05 03:22 UTC, TicClick commented on wiki/Rules/Visual_Content_Considerations/id.md
> +Sesuai dengan [Peraturan Komunitas No. 5](/wiki/Rules#community-rules), semua konten visual dalam beatmap yang dikirimkan harus memenuhi kriteria untuk aman digunakan di segala kalangan usia. Konten-
```suggestion
Sesuai dengan [Peraturan Komunitas \#5](/wiki/Rules#peraturan-komunitas), semua konten visual dalam beatmap yang dikirimkan harus memenuhi kriteria untuk aman digunakan di segala kalangan usia. Konten-konten ini meliputi latar belakang beatmap, elemen skin, aset storyboard, dan lainnya.
```

2020-09-05 03:24 UTC, TicClick approved these changes
nice

2020-09-05 03:25 UTC, merged