[RU] Update "BanchoBot"
ppy/osu-wiki pull request #4136
Opened 2020-09-04 07:09 UTC by Styml

2020-09-04 16:03 UTC, UristMcKobold requested changes

2020-09-04 16:03 UTC, UristMcKobold commented on wiki/BanchoBot/ru.md
> +`!stats` показывает краткую статистику указанного пользователя. Эта команда показывает статистику только по игровому режиму, в который указанный пользователь играл в последний раз, но при этом Bancho
```suggestion
`!stats` показывает краткую статистику указанного пользователя. Работает она по тому игровому режиму, в который указанный пользователь играл в последний раз, но при этом БанчоБот не сообщает, про какой игровой режим идёт речь. Если указанный пользователь еще ни разу не сыграл в osu!, то БанчоБот выведет `User not found` (`Пользователь не найден`), даже если пользователь существует. Ниже приведен пример использования команды:
```
Опять повторения повторений.

2020-09-04 16:03 UTC, UristMcKobold commented on wiki/BanchoBot/ru.md
> +*О том, в каких случаях жаловаться, можно прочесть тут: [Жалобы на других пользователей](/wiki/Reporting_Bad_Behaviour).*
```suggestion
*О том, в каких случаях жаловаться, вы можете прочесть тут: [Жалобы на других пользователей](/wiki/Reporting_Bad_Behaviour).*
```

2020-09-04 16:03 UTC, UristMcKobold commented on wiki/BanchoBot/ru.md
> +Команда `!report` отправляет жалобу на игрока [глобальным модераторам](/wiki/Global_Moderation_Team) о его неподобающем поведении . Если ник пользователя содержит пробелы, замените их на подчёркивани
```suggestion
Команда `!report` отправляет жалобу на игрока [глобальным модераторам](/wiki/Global_Moderation_Team) о его неподобающем поведении. Если ник пользователя содержит пробелы, замените их на подчёркивания - например, `really cool username` станет `really_cool_username`. Если же вы хотите пожаловаться на действия самого модератора, вместо `!report` напишите на почту [support@ppy.sh](mailto:support@ppy.sh). Ниже приведён пример жалобы с помощью команды:
```
Опечатка.

2020-09-04 16:03 UTC, UristMcKobold commented on wiki/BanchoBot/ru.md
> +- В аккаунте БанчоБота в дате регистрации стоит "Here since the beginning" ("Здесь с самого начала").
```suggestion
- У БанчоБота в дате регистрации написано "Here since the beginning" ("Здесь с самого начала").
```

2020-09-04 19:24 UTC, TicClick requested changes

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +*Не путать с [Bancho(сервер)](/wiki/Bancho)*
предлагаю сделать так, чтобы примечания во всех статьях строились по определённому формату
```suggestion
*См. также: [Bancho (сервер)](/wiki/Bancho)*
```

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +![Карточка пользователя БанчоБота](img/BanchoBot.jpg "Карточка пользователя БанчоБота")
мы тут по-быстрому договорились, что в статье можно оставить английское написание, упомянув русское один раз в первом абзаце, если согласен — поправь везде, пожалуйста

```suggestion
![Карточка пользователя BanchoBot](img/BanchoBot.jpg "Карточка пользователя BanchoBot")
```

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
>  *Вы также можете ознакомиться с [полным списком команд чата](/wiki/Chat_Console#Список-комманд).*
```suggestion
*См. также: [Полный список команд чата](/wiki/Chat_Console#Список-комманд)*
```

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +BanchoBot может отвечать игроку, если он напишет команду в чат. Все команды для БанчоБота, начинаются с `!`(без пробела после) и не чувствительны к регистру. Команды можно отправлять БанчоБоту в личн
немножно подправил замечание про пробел и сообщения

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +Если обычный пользователь отправит команду в общий чат, то команда не будет видна другим пользователям, а BanchoBot ответит в личных сообщениях. Пользователи также могут отправить в чат команду `/bb`
убрал повторение до конца

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +Команда `!help` покажет вам список всех доступных команд для BanchoBot. Ниже пример использования этой команды.
```suggestion
Команда `!help` покажет вам список всех доступных команд для BanchoBot. Пример:
```

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +
лучше убрать, для русского редактора комментарий бесполезен
```suggestion
```

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
лишнее
```suggestion
```

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +!roll <аргумент>/<число>
ох, господи, пиздец, кто-то всё-таки это испортил. сделай пока так, пожалуйста:
```suggestion
!roll <аргумент или число>
```

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +`!stats` показывает краткую статистику указанного пользователя. Эта команда показывает статистику только по игровому режиму, в который указанный пользователь играл в последний раз, но при этом Bancho
предлагаю поменять _Ниже приведен пример использования команды:_ на _Пример:_

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +*О том, в каких случаях жаловаться, можно прочесть тут: [Жалобы на других пользователей](/wiki/Reporting_Bad_Behaviour).*
добавь _Примечание:_ в начало предложения, пожалуйста

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +Команда `!report` отправляет жалобу на игрока [глобальным модераторам](/wiki/Global_Moderation_Team) о его неподобающем поведении . Если ник пользователя содержит пробелы, замените их на подчёркивани
- предлагаю проще читаемое (порядок слов тоже важен, да):
```markdown
Команда `!report` отправляет [глобальным модераторам](/wiki/Global_Moderation_Team) жалобу о неподобающем поведении игрока.`
```
- _Ниже приведён пример жалобы с помощью команды:_ -> _Пример:_

2020-09-04 19:24 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +- В аккаунте БанчоБота в дате регистрации стоит "Here since the beginning" ("Здесь с самого начала").
предлагаю не _в дате регистрации_, а _вместо даты регистрации_, и не просто у банчобота, а _В профиле BanchoBot_

2020-09-04 23:23 UTC, Styml commented on wiki/BanchoBot/ru.md
Хмм, ну в примере ведь действительно опечатка, я потому и оставил.

2020-09-04 23:41 UTC, Styml commented on wiki/BanchoBot/ru.md
> +!roll <аргумент>/<число>
Ну, там же не только число можно написать, хоть это и не аргумент.

2020-09-05 00:16 UTC, TicClick requested changes
последние штрихи

2020-09-05 00:16 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +**БанчоБот** (иногда называемый просто *Банчо*) — чат-бот в osu!, созданный для помощи игрокам в чате и показывающий игровые оповещения (например, о количестве повторных попыток или о перезапуске сер
```suggestion
**BanchoBot** *(БанчоБот)*, иногда называемый просто *Банчо*, — чат-бот в osu!, созданный для помощи игрокам в чате и показывающий игровые оповещения (например, о количестве повторных попыток или о перезапуске сервера). Помимо этого, он обеспечивает работу [Bancho IRC](/wiki/Internet_Relay_Chat) (Internet Relay Chat). Автором бота является [Echo](https://osu.ppy.sh/users/431).
```

2020-09-05 00:16 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +*См. также: [Полный список команд чата](/wiki/Chat_Console#Список-комманд)*
лол, какой ужас. ладно, сейчас сделаем правку

2020-09-05 00:16 UTC, TicClick commented on wiki/BanchoBot/ru.md
два примечания подряд — не очень хорошо, тем более что конкретно это покрыто в отдельном разделе про репорт

2020-09-05 00:16 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +`!stats` показывает краткую статистику указанного пользователя. Работает она по тому игровому режиму, в который указанный пользователь играл в последний раз, но при этом BanchoBot не сообщает, про ка
слишком много пользователей и указаний
```suggestion
`!stats` показывает краткую статистику пользователя. Работает она по тому игровому режиму, в который указанный пользователь играл в последний раз, но при этом BanchoBot не сообщает, про какой игровой режим идёт речь. Если пользователь еще ни разу не сыграл в osu!, то BanchoBot выведет `User not found` (`Пользователь не найден`), даже если игрок с таким ником существует. Пример:
```

2020-09-05 00:16 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +Показывает, где сейчас находится игрок. По умолчанию указывает только страну пользователя, но если у него включена настройка `Share your city location with others`, то вы узнаете ещё и город. Пример:
```suggestion
Сообщает, где сейчас находится игрок. По умолчанию указывает только страну пользователя, но если у него включена настройка `Share your city location with others`, то вы узнаете ещё и город. Пример:
```

2020-09-05 00:16 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +Первый вариант покажет содержимое справочной `<статьи>`, второй — список всех доступных статей. По умолчанию ответ приходит на английском, но если перед названием статьи добавить [префикс языка](/wik
```suggestion
Первый вариант покажет содержимое справочной `<статьи>`, второй — список всех доступных статей. По умолчанию ответ приходит на английском, но если перед названием статьи добавить [префикс языка](/wiki/Article_Styling_Criteria#локали), то BanchoBot выдаст локализованную версию статьи. Примеры:
```

2020-09-05 00:16 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +  - Официальная дата регистрации аккаунта BanchoBot — 27 августа 2007, 22:09:14 по UTC-5.
```suggestion
  - Официальная дата регистрации аккаунта BanchoBot — 27 августа 2007 (22:09:14 UTC-5).
```

2020-09-05 02:17 UTC, TicClick approved these changes

2020-09-05 02:17 UTC, merged