[ZH] Update Banchobot
ppy/osu-wiki pull request #4140
Opened 2020-09-04 08:17 UTC by Kotoki1337

2020-09-22 13:08 UTC, kj415j45 requested changes

2020-09-22 13:08 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +- 如果你把网页语言调为英文，在 BanchoBot 个人资料下的注册日期中可以看到 “这里是一切的开始”（Here since the beginning）。
这个实际上是给所有早期玩家（2008年前[1]注册）的标识，对应 osu-web 中的翻译键 `users.show.first_members`，目前的翻译为“元老玩家”

[1] [osu-web 中的源码（已选中为当前版本）](https://github.com/ppy/osu-web/blob/842378b/resources/assets/coffee/react/profile-page/links.coffee#L60-L63)

2020-09-22 13:08 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +- [FAQ](#faq)
faq -> 常见问题

2020-09-22 13:17 UTC, kj415j45 reviewed
漏了命令的翻译

2020-09-22 13:17 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +!roll <argument>/<number>
```suggestion
!roll <参数>/<数字>
```

2020-09-22 13:17 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +!stats <username>
```suggestion
!stats <用户名>
```

2020-09-22 13:17 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +!where <username>
```suggestion
!where <用户名>
```

2020-09-22 13:17 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +!faq <entry>
```suggestion
!faq <条目名>
```

2020-09-22 13:17 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +!report <user> <reason>
```suggestion
!report <用户名> <原因（最好用英文）>
```

2020-09-22 15:26 UTC, Kotoki1337 commented on wiki/BanchoBot/zh.md
> +**BanchoBot**（有时被称为 *Bancho*）是一个专为 osu! 设计的游戏内聊天机器人，它会在聊天频道内发布一些游戏相关的信息（比如你的游玩次数，重试次数等），并回应某些指令。它由 [Echo](https://osu.ppy.sh/users/431) 编写，是 [Bancho IRC](/wiki/Internet_Relay_Chat) （互联网中继聊天）的本体。
“that assists people in the in-game chat”没翻译是因为我认为把这句话合进目前的翻译有些绕，而且原文表达的意思就是bot会在chat中发布游戏相关的消息，所以我无视没翻。有什么更好的译文吗

2020-09-22 15:30 UTC, Kotoki1337 commented on wiki/BanchoBot/zh.md
> +- 如果你把网页语言调为英文，在 BanchoBot 个人资料下的注册日期中可以看到 “这里是一切的开始”（Here since the beginning）。
哦，抱歉。核对了一下，我开始以为 BanchoBot 的这个 string 和元老玩家的原文不同

2020-09-22 15:41 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +- 如果你把网页语言调为英文，在 BanchoBot 个人资料下的注册日期中可以看到 “这里是一切的开始”（Here since the beginning）。
如果直译的话，在 web 我感觉有点奇怪，实际意思对不上，如果只是 bancho 和 ppy 的话我觉得没问题，所以早期提交 osu-web 翻译的时候我选定了现在的译法。

另外，web 对于这些玩家的的注册日期显示方案是光标悬停，也许原文可以一起改一下（x

2020-09-22 15:44 UTC, Kotoki1337 commented on wiki/BanchoBot/zh.md
> +- 如果你把网页语言调为英文，在 BanchoBot 个人资料下的注册日期中可以看到 “这里是一切的开始”（Here since the beginning）。
我想到两种，一个是翻成元老玩家，另一个是保留原文。因为Banchobot确实符合这句话，主要是这个东西出现在Tips里说是元老玩家有点怪

2020-09-22 15:45 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +**BanchoBot**（有时被称为 *Bancho*）是一个专为 osu! 设计的游戏内聊天机器人，它会在聊天频道内发布一些游戏相关的信息（比如你的游玩次数，重试次数等），并回应某些指令。它由 [Echo](https://osu.ppy.sh/users/431) 编写，是 [Bancho IRC](/wiki/Internet_Relay_Chat) （互联网中继聊天）的本体。
```suggestion
**BanchoBot**（有时被称为 *Bancho*）是一个专为 osu! 设计的游戏内聊天机器人，它会在聊天频道内发布一些游戏相关的信息（比如你的游玩次数，重试次数等），并回应某些指令来帮助玩家。它由 [Echo](https://osu.ppy.sh/users/431) 编写，是 [Bancho IRC](/wiki/Internet_Relay_Chat) （互联网中继聊天）的本体。
```
我认为翻译为“本体”会使得 BanchoBot 具有二义性（一是机器人，二是整个Bancho IRC的代称），不过我也没有什么更好的方案。

2020-09-22 15:49 UTC, kj415j45 commented on wiki/BanchoBot/zh.md
> +- 如果你把网页语言调为英文，在 BanchoBot 个人资料下的注册日期中可以看到 “这里是一切的开始”（Here since the beginning）。
可以写个译注解释一下？

2020-09-22 15:53 UTC, Kotoki1337 commented on wiki/BanchoBot/zh.md
> +**BanchoBot**（有时被称为 *Bancho*）是一个专为 osu! 设计的游戏内聊天机器人，它会在聊天频道内发布一些游戏相关的信息（比如你的游玩次数，重试次数等），并回应某些指令。它由 [Echo](https://osu.ppy.sh/users/431) 编写，是 [Bancho IRC](/wiki/Internet_Relay_Chat) （互联网中继聊天）的本体。
```suggestion
**BanchoBot**（有时被称为 *Bancho*）是一个专为 osu! 设计的游戏内聊天机器人，它会在聊天频道内发布一些游戏相关的信息（比如你的游玩次数，重试次数等），并回应某些指令来帮助玩家。它由 [Echo](https://osu.ppy.sh/users/431) 编写，同时也提供了 Bancho 的 [IRC](/wiki/Internet_Relay_Chat) （互联网中继聊天）服务器。
```

2020-09-25 09:00 UTC, Kotoki1337 commented on wiki/BanchoBot/zh.md
> +- 如果你把网页语言调为英文，在 BanchoBot 个人资料下的注册日期中可以看到 “这里是一切的开始”（Here since the beginning）。
那我强调一下调为英文和 Here since the beginning 吧

2020-09-26 17:07 UTC, TPGPL approved these changes

2020-09-26 17:07 UTC, merged