[RU/EN] Article Styling Criteria
ppy/osu-wiki pull request #4148
Opened 2020-09-04 23:52 UTC by TicClick

- for the original version, I've made a few minor improvements, such as adding missing examples.
- for Russian, there is a full-fledged translation now.

2020-09-04 23:54 UTC, TPGPL commented
might conflict with #3734

2020-09-05 00:02 UTC, TicClick commented
@TPGPL I can probably discard the changes in `en.md`, but even with that, I wouldn't want to be blocked by the split -- even if the translation is outdated the day after the merge, it still will do (not to mention I'll return to it shortly)

2020-09-05 00:17 UTC, Styml commented on wiki/Article_Styling_Criteria/ru.md
> +Крмое того, в названиях директорий разрешены только следующие символы:
```suggestion
Кроме того, в названиях директорий разрешены только следующие символы:
```
очепятка

2020-09-05 00:57 UTC, UristMcKobold requested changes

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +Крмое того, в названиях директорий разрешены только следующие символы:
```suggestion
Кроме того, в названиях директорий разрешены только следующие символы:
```

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +*Примечание: имя pippi пишется со строчной буквы «p», так же, как и peppy.*
```suggestion
*Примечание: имя pippi пишется со строчной буквы «p», так же как и peppy.*
```
Запятая выглядит лишней, так как «так же как и» — это союз.

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +В примечании такого типа явно указано, кому оно предназначено, с помощью союза «для». Оно начинается с тех же слов, что и более общие типы примечаний:
```suggestion
В примечании такого типа с помощью союза «для» явно указано, кому оно предназначено. Оно начинается с тех же слов, что и более общие типы примечаний:
```
Небольшое изменение, но так лучше восприниматься будет смысл.

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +*Примечание для пользователей API: в osu!catch пойманные дроплеты обозначаются термином `count50`, пропущенные дроплеты — термином `countkatu`.*
```suggestion
*Примечание для пользователей API: в osu!catch пойманные дроплеты обозначаются термином `count50`, а пропущенные — термином `countkatu`.*
```
Меньше повторений!

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +Чтобы применить курсив, используйте одинарные звёздочки (`*`). Курсивом выделяются названия видеоигр и произведений (например, шрифтов, песен или изображений), исключение из этого — упоминание osu! к
```suggestion
Чтобы применить курсив, используйте одинарные звёздочки (`*`). Курсивом выделяются названия игр и произведений (например, шрифтов, песен или изображений), исключение из этого — упоминание osu! как игры.
```
Я бы не использовал термин «видеоигра», у нас это не принято.

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +Название статьи должно находиться на первой строке файла, если у статьи нет [метаданных](#метаданные), в противном случае сначала пишутся метаданные и только затем, после пустой строки, — название.
```suggestion
Если у статьи нет [метаданных](#метаданные), название статьи должно находиться на первой строке файла. В противном случае сначала пишутся метаданные и только затем, после пустой строки, — название.
```
Тут немного сложно понять, о чём идёт речь, в основном из-за «если у статьи нет метаданных», отгороженной запятыми. Непонятно, к первой или последней части относится эта часть.

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +Имя pippi пишется со строчной буквы «p», так же, как и peppy.
```suggestion
Имя pippi пишется со строчной буквы «p», так же как и peppy.
```
Уже писал выше, что лишнее.

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +## Правописание и пунктуация
```suggestion
## Орфография и пунктуация
```
«Правописание» — какое-то слишком просторечное слово, особенно если его ставить вместе с «пунктуацией». Запрос «орфография и пунктуация» выдал больше результатов, чем вариант с правописанием.

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +Название игры, osu!, должно писаться в нижнем регистре, без использования курсива и вместе с восклицательным знаком. Если osu! заканчивает восклицание, предложение нужно переформулировать, чтобы двух
```suggestion
Название игры (osu!) должно писаться в нижнем регистре, без использования курсива и вместе с восклицательным знаком. Если osu! заканчивает восклицание, предложение нужно переформулировать, чтобы двух восклицательных знаков рядом не стояло. В остальных случаях относитесь к этому слову, как к любому другому: восклицательный знак в названии не должен исключать других знаков препинания. Примеры:
```
Выделение запятыми — лишнее.

2020-09-05 00:57 UTC, UristMcKobold commented on wiki/Article_Styling_Criteria/ru.md
> +EZ (Easy) — самый лучший игровой режим, за исключением SD (Sudden Death).
```suggestion
EZ (Easy) — самый лучший мод, за исключением SD (Sudden Death).
```
Это же не игровой режим, а мод.

2020-09-05 01:11 UTC, TicClick commented on wiki/Article_Styling_Criteria/ru.md
> +*Примечание для пользователей API: в osu!catch пойманные дроплеты обозначаются термином `count50`, пропущенные дроплеты — термином `countkatu`.*
Меньше повторений, говоришь?

2020-09-05 01:13 UTC, TicClick commented on wiki/Article_Styling_Criteria/ru.md
> +Название игры, osu!, должно писаться в нижнем регистре, без использования курсива и вместе с восклицательным знаком. Если osu! заканчивает восклицание, предложение нужно переформулировать, чтобы двух
не лишнее, обособление же, но пускай

2020-09-05 01:19 UTC, UristMcKobold submitted a review, later dismissed

2020-09-06 00:46 UTC, WalterToro approved these changes

2020-09-06 00:46 UTC, merged