[ZH] Beatmapsets
ppy/osu-wiki pull request #4154
Opened 2020-09-06 01:44 UTC by lixiangwuxian

translated from en.md.
翻译自en.md。

2020-09-11 08:39 UTC, Kotoki1337 commented
之前人们都把 `Beatmapsets` 翻成 `谱面集`。可以参考 osu!translate-zh 的 [专有名词对照表（Google Docs）](https://docs.google.com/spreadsheets/d/1zhUP0qekKRUWb1Mu-P89mwu_HcPBen5FoGPqD2MkI7k)。

2020-09-11 17:04 UTC, Kotoki1337 requested changes
图片和链接的注释需要翻译，merge之前英文的审查人员会要求这个，

2020-09-11 17:04 UTC, Kotoki1337 commented on wiki/Beatmaps/Beatmapsets/zh.md
> +![一张在游戏内选歌界面显示的谱面集的截屏](img/in-game.jpg "Sing's beatmapset of \"nanobii - popsicle beach\"")
``Sing's beatmapset of \"nanobii - popsicle beach\"`` 需要翻译

2020-09-12 04:10 UTC, lixiangwuxian commented on wiki/Beatmaps/Beatmapsets/zh.md
> +![一张在游戏内选歌界面显示的谱面集的截屏](img/in-game.jpg "Sing's beatmapset of \"nanobii - popsicle beach\"")
谢谢提醒！

2020-09-26 14:45 UTC, MegaApplePi approved these changes

2020-09-26 14:45 UTC, merged