I translated some of the pages on the wiki into Chinese
ppy/osu-wiki pull request #4158
Opened 2020-09-06 12:34 UTC by WNCX

I didn't see any translations in the wiki skin Chinese, so I did the translation actually, hoping to contribute to the encyclodedi of "osu!"

2020-09-11 08:31 UTC, Kotoki1337 requested changes
中英之前最好相隔一个空格

2020-09-11 08:31 UTC, Kotoki1337 commented on wiki/Skinning/zh.md
> +**仅限beatmaps，** 如果beatmap外观包含“排名标准”中列出的集合中的单个元素，则它必须包含所述外观集内的所有其他元素。这仅适用于Beatmap皮肤，但其他皮肤爱好者可能也要考虑这些列表。`这段的翻译并不准确！我们希望您能帮助纠错！`
```suggestion
**仅限谱面，** 如果谱面外观包含“皮肤组列表”中列出的单个元素，则它必须包含所述皮肤组内的所有其他元素。这仅适用于谱面皮肤，但其他皮肤也需要考虑这些列表。
```

2020-09-11 08:31 UTC, Kotoki1337 commented on wiki/Skinning/zh.md
> +## 皮肤集
```suggestion
## 皮肤组
```

2020-09-11 08:31 UTC, Kotoki1337 commented on wiki/Skinning/zh.md
> +- [mania皮肤](/wiki/Skinning/osu!mania)
```suggestion
- [osu!standard 皮肤](/wiki/Skinning/osu!)
- [osu!taiko 皮肤](/wiki/Skinning/osu!taiko)
- [osu!catch 皮肤](/wiki/Skinning/osu!catch)
- [osu!mania 皮肤](/wiki/Skinning/osu!mania)
```

参考[文章风格指南](https://osu.ppy.sh/help/wiki/Article_Styling_Criteria)，游戏模式请保留全称

2020-09-11 08:31 UTC, Kotoki1337 commented on wiki/Skinning/zh.md
> +- [指南与重要的线索](/wiki/Skinning/Guides_and_Important_Threads)
```suggestion
- [指南与论坛帖子](/wiki/Skinning/Guides_and_Important_Threads)
```

2020-10-10 09:08 UTC, kj415j45 requested changes

2020-10-10 09:08 UTC, kj415j45 commented on wiki/Skinning/zh.md
> +- [皮肤变更历史](/wiki/Skinning/History) -旧皮肤元素列表 skinning elements
```suggestion
- [皮肤变更历史](/wiki/Skinning/History) - 旧皮肤元素列表
```

2020-10-10 09:08 UTC, kj415j45 commented on wiki/Skinning/zh.md
> +- [摘要](https://osu.ppy.sh/community/forums/topics/686664) - 已完成的皮肤元素列表
```suggestion
- [汇总](https://osu.ppy.sh/community/forums/topics/686664) - 已完成的皮肤列表
```

2020-10-10 09:08 UTC, kj415j45 commented on wiki/Skinning/zh.md
> +- [指南与论坛帖子](/wiki/Skinning/Guides_and_Important_Threads)
```suggestion
- [指南与重点论坛帖](/wiki/Skinning/Guides_and_Important_Threads)
```

2020-10-10 09:08 UTC, kj415j45 commented on wiki/Skinning/zh.md
> +**仅限谱面，** 如果谱面外观包含“皮肤组列表”中列出的单个元素，则它必须包含所述皮肤组内的所有其他元素。这仅适用于谱面皮肤，但其他皮肤也需要考虑这些列表。
```suggestion
**仅限谱面**，如果谱面用皮肤包含了“皮肤组列表”中列出的某个元素，则必须同时包含所在皮肤组内的所有其他元素。这仅适用于谱面用皮肤，但其他皮肤作者也可能需要参考这些列表。
```

2020-10-16 18:59 UTC, TPGPL approved these changes

2020-10-16 18:59 UTC, merged