[ID] Background / Latar belakang beatmaps
ppy/osu-wiki pull request #4182
Opened 2020-09-15 02:05 UTC by HerendraTJ

Untuk background harap mohon bantuannya untuk mengkoreksi kalau misalkan ada salah. Terima kasih atas perhatiannya.

2020-09-15 02:26 UTC, fajar13k commented on wiki/Beatmaps/Background/id.md
> +Latar belakang ditampilkan di kartu beatmap , di bagian [Pemilihan Lagu](/wiki/Interface#song-selection-screen), dan selama permainan.
```suggestion
Latar belakang ditampilkan di kartu (*card*) informasi beatmap, di menu [pemilihan lagu](/wiki/Interface#song-selection-screen), dan selama dalam gameplay.
```

2020-09-15 02:26 UTC, fajar13k commented on wiki/Beatmaps/Background/id.md
> +**Background/Latar Belakang** (***BG***) gambar atau video dapat ditambahkan ke [beatmaps](/wiki/Beatmaps). Ketika hanya ditulis "background" atau "bg", Hal tersebut biasanya mengacu pada gambar lata
```suggestion
**Background/Latar belakang** (***BG***) berbentuk gambar atau video dapat ditambahkan ke dalam [beatmap](/wiki/Beatmaps). Ketika sebuah file hanya diberi nama "background" atau "bg", Hal tersebut biasanya mengacu pada gambar latar belakang yang digunakan dalam beatmap. 
```

2020-09-15 02:26 UTC, fajar13k commented on wiki/Beatmaps/Background/id.md
> +*Untuk ketentuan berkaitan dengan latar belakang , lihat: [Kriteria_Ranking](/wiki/Ranking_Criteria)*
```suggestion
*Untuk ketentuan yang berkaitan dengan penggunaan latar belakang, lihat: [Kriteria Ranking](/wiki/Ranking_Criteria)*
```

2020-09-17 11:54 UTC, fajar13k approved these changes
Let's push it!

2020-09-21 11:10 UTC, TicClick requested changes

2020-09-21 11:10 UTC, TicClick commented on wiki/Beatmaps/Background/id.md
> +Latar belakang ditampilkan di kartu (*card*) informasi beatmap, di menu [pemilihan lagu](/wiki/Interface#song-selection-screen), dan selama dalam gameplay.
```suggestion
Latar belakang ditampilkan di kartu (*card*) informasi beatmap, di menu [pemilihan lagu](/wiki/Interface#layar-pemilihan-lagu), dan selama dalam gameplay.
```

2020-09-21 11:11 UTC, TicClick approved these changes

2020-09-21 11:11 UTC, merged