Fix wording of spinner readability rules in osu!catch RC
ppy/osu-wiki pull request #4186
Opened 2020-09-15 05:43 UTC by cl8n

https://osu.ppy.sh/community/forums/topics/1144293

2020-09-15 06:54 UTC, peppy commented
This is no clearer to me. Where is the definition of "active object"? I read the thread but still don't really understand..

2020-09-15 06:59 UTC, dorothy3242 commented
Active object is already in the catch criteria's glossary, so it was not changed in the pull request.

2020-09-15 07:02 UTC, peppy commented
That's *such* a shit term. Ask 10 people what it means and 0 will know.

2020-09-15 07:07 UTC, peppy commented
This is not getting merged, by the way. The term needs to change right here and now.

2020-09-15 07:07 UTC, peppy requested changes
decide on better term

2020-09-20 18:15 UTC, O1CDeif requested changes
Using just "circles/sliders" to specify those cases would be more clear for the casual reader, as they are much more common terms than "active objects". That'd also formally allow the spinner-spinner situation, which doesn't have an impact in gameplay or combo, but only alter the banana density under certain conditions. Discussion on using "circles/sliders" was taken within the NAT and the change was accepted by the catch BNs after a highlight.

2020-09-20 18:15 UTC, O1CDeif commented on wiki/Ranking_Criteria/osu!catch/en.md
> +- **At least 250 ms must be left between active objects and the start and end of spinners to ensure readability.** As an example, a 1/3 gap would be required at 80 BPM, whereas a 1/2 gap would be req
```suggestion
- **At least 250 ms must be left between circles/sliders and the start and end of spinners to ensure readability.** As an example, a 1/3 gap would be required at 80 BPM, whereas a 1/2 gap would be required at 120 BPM.
```

2020-09-20 18:15 UTC, O1CDeif commented on wiki/Ranking_Criteria/osu!catch/en.md
> +- **At least 250 ms must be left between active objects and the start and end of spinners to ensure readability.** As an example, a 1/3 gap would be required at 80 BPM, whereas a 1/2 gap would be req
```suggestion
- **At least 250 ms must be left between circles/sliders and the start and end of spinners to ensure readability.** As an example, a 1/3 gap would be required at 80 BPM, whereas a 1/2 gap would be required at 120 BPM.
```

2020-09-20 18:15 UTC, O1CDeif commented on wiki/Ranking_Criteria/osu!catch/en.md
> +- **At least 125 ms must be left between active objects and the start of spinners to ensure readability.** As an example, a 1/4 gap would be required at 120 BPM, whereas a 1/3 gap would be required a
```suggestion
- **At least 125 ms must be left between circles/sliders and the start of spinners to ensure readability.** As an example, a 1/4 gap would be required at 120 BPM, whereas a 1/3 gap would be required at 160 BPM.
```

2020-09-20 18:15 UTC, O1CDeif commented on wiki/Ranking_Criteria/osu!catch/en.md
> +- **At least 250 ms must be left between active objects and the end of spinners to ensure readability.** As an example, a 1/3 gap would be required at 80 BPM, whereas a 1/2 gap would be required at 1
```suggestion
- **At least 250 ms must be left between circles/sliders and the end of spinners to ensure readability.** As an example, a 1/3 gap would be required at 80 BPM, whereas a 1/2 gap would be required at 120 BPM.
```

2020-09-20 18:15 UTC, O1CDeif commented on wiki/Ranking_Criteria/osu!catch/en.md
> +- **At least 125 ms must be left between active objects and the start and end of spinners to ensure readability.** As an example, a 1/4 gap would be required at 120 BPM, whereas a 1/3 gap would be re
```suggestion
- **At least 125 ms must be left between circles/sliders and the start and end of spinners to ensure readability.** As an example, a 1/4 gap would be required at 120 BPM, whereas a 1/3 gap would be required at 160 BPM.
```

2020-09-20 18:15 UTC, O1CDeif commented on wiki/Ranking_Criteria/osu!catch/en.md
> +- **At least 62 ms must be left between active objects and the start of spinners to ensure readability.** As an example, a 1/6 gap would be required at 160 BPM, whereas a 1/4 gap would be required at
```suggestion
- **At least 62 ms must be left between circles/sliders and the start of spinners to ensure readability.** As an example, a 1/6 gap would be required at 160 BPM, whereas a 1/4 gap would be required at 240 BPM.
```

2020-09-20 18:15 UTC, O1CDeif commented on wiki/Ranking_Criteria/osu!catch/en.md
> +- **At least 125 ms must be left between active objects and the end of spinners to ensure readability.** As an example, a 1/4 gap would be required at 120 BPM, whereas a 1/3 gap would be required at
```suggestion
- **At least 125 ms must be left between circles/sliders and the end of spinners to ensure readability.** As an example, a 1/4 gap would be required at 120 BPM, whereas a 1/3 gap would be required at 160 BPM.
```

2020-09-21 03:33 UTC, peppy commented
in lazer we call them "fruit" and "juice streams", for reference

2020-09-21 15:49 UTC, O1CDeif commented
Until lazer is stable enough to be used by mappers/modders (as in, having a functional editor) I'd rather stick to the terms I proposed. When the moment comes, we can adjust the Ranking Criteria and revamp it with the new terminology.

2020-09-26 08:03 UTC, peppy commented
circles and sliders works fine for now, sure.

2020-09-29 23:35 UTC, cl8n commented
"active object" can't be replaced by "circles/sliders" while keeping same meaning for some other places in RC, I'm not gonna attempt to fix that in this PR and I don't even play catch o_ o

2020-09-30 02:41 UTC, peppy approved these changes

2020-09-30 02:41 UTC, merged