[WIP] Add .osb .osk .osz .db
ppy/osu-wiki pull request #4223
Opened 2020-09-19 13:23 UTC by PercyDan54

Suprised that nobody had translated these.
Translation for .db is WIP.

2020-09-19 22:47 UTC, PercyDan54 commented
Finished

2020-09-21 11:19 UTC, kj415j45 requested changes
标点在替换的时候没有去掉英文标点的尾缀空格，需要去除，此外还有其他中西文混用时的一些排版问题。

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| Int-Double pair* | 一个指示接下来Int-Double pair的数量的Int， 随后是上述的 Int-Double pair。osu! standard中的星级，每个Int-Double pair中， Int是Mod组合，Double是星级。 仅在高于20140609的版本存在。 |
为描述清晰，建议改成 `Int + Int-Double pair` 或者拆分成两行 `Int`, `Int-Double pair`，下同，并可以同步到原文修改。

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| Timing point+ | 一个指示接下来Timing point的数量的Int， 随后是上述的Timing point 。 |
同上

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| Single | Stack leniency |
这是什么

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +**collection.db** 包含了用户的谱面收藏夹数据。这个文件可以从一个osu!安装迁移到另一个osu!安装。但是除非该电脑有收藏夹内的所有谱面，否则它不会生效
```suggestion
**collection.db** 包含了用户的谱面收藏夹数据。该文件可以从一个 osu! 迁移到另一个。然而，若该电脑没有收藏夹内的所有谱面，它将不会生效
```

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| Timing Point | 17 | 包含一个代表BPM的双精度浮点， 和一个代表偏离（以毫秒为单位）的双精度浮点，和一个布尔值； 如果为false， 则该计时点是继承的。 见[Osu 文件](/wiki/osu!_File_Formats/Osu_(file_format))以获得更多关于计时点的信息。 |
```suggestion
| Timing Point | 17 | 包含一个代表 BPM 的双精度浮点，和一个代表偏移量（以毫秒为单位）的双精度浮点，和一个布尔值；如果为 false，则该 Timing Point 是继承的。查阅 [.osu（文件格式）](/wiki/osu!_File_Formats/Osu_(file_format)) 以获得更多关于 Timing Point 的信息。 |
```

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +# .db 文件
```suggestion
# .db （文件格式）
```

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| Boolean | Visual override |
这是什么

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +|
```suggestion
```

2020-09-21 11:19 UTC, kj415j45 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +|
```suggestion

```

2020-09-21 12:03 UTC, PercyDan54 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| Boolean | Visual override |
> 
> 
> 这是什么

这些不知道咋翻

> 
> 
> 这是什么

未找到标准翻译

2020-10-18 04:50 UTC, kj415j45 requested changes
鸽

2020-12-08 17:37 UTC, TicClick commented
@kj415j45 @PercyDan54 what's the status of this PR, is it ready, or does it need more work/polishing?

2020-12-09 11:37 UTC, PercyDan54 commented
> @kj415j45 @PercyDan54 what's the status of this PR, is it ready, or does it need more work/polishing?

Dunno if I should open this PR again since [my repo](https://github.com/PercyDan54/osu-wiki/tree/edited) is marked as "unknown repository" for some reason.
I think I need to check it again.

2020-12-10 04:04 UTC, TicClick commented
> Dunno if I should open a new PR for this since [my repo](https://github.com/PercyDan54/osu-wiki/tree/edited) is marked as "unknown repository" for some reason.
> I think I need to check it again.

have you ever removed the branch and created it from scratch, or removed and cloned the repo itself? that might be the reason.

2021-01-19 10:56 UTC, TicClick commented
going to close the PR for now to hide it from a list of open pulls, please don't hesitate to reopen it or create a new one once when you solve the repository-related issues

2021-01-19 10:56 UTC, closed without merging