Update shortcut reference
ppy/osu-wiki pull request #4260
Opened 2020-09-27 19:56 UTC by dorothy3242

Add double right click to the list of mouse commands in the editor.

2020-09-27 20:05 UTC, Joehuu commented
Isn't it double left click?

2020-09-27 20:09 UTC, hypercyte commented
double right click is correct (it teleports you to any object selected)

2020-09-27 22:56 UTC, Joehuu commented on wiki/Shortcut_key_reference/en.md
> +| `Double Right Click` | Jump to selected objects' position on the timeline from any point in the song. |
```suggestion
| `Double Right Click` | Jump to selected objects' position on the timeline or playfield from any point in the song. |
```

2020-09-28 07:54 UTC, peppy commented
I'm confused. It should be double left click? If double right-click works that's an oversight, and won't be supported in lazer editor (while double left-click will be).

2020-09-28 12:52 UTC, dorothy3242 commented
Yes it is definitely currently double right click, which is strange since the first click would delete objects if your cursor is above them. If it gets changed now to double left click or gets changed in lazer this shortcut reference could be updated again then I'd think.

2020-09-28 12:54 UTC, peppy commented
I've checked and it is, beyond doubt, double left click.

2020-09-28 12:55 UTC, peppy requested changes
is wrong.

2020-09-28 12:56 UTC, dorothy3242 commented
In another build or?  I checked this several times and double left did not do anything. My mouse settings are not customized. It's double clicking the same mouse key that removed objects.

2020-09-28 13:00 UTC, peppy commented
Again, you must have some custom setup. I'm telling you what the shortcuts are, as the developer of the game.

2020-09-28 13:07 UTC, dorothy3242 commented
Ok so this confusion is because **both** in fact are correct.
Double left click if you click the start of the objects in the selection 
Double right if you click anywhere else.
I'll update the PR soon.

2020-09-28 16:04 UTC, peppy commented
If double right-click works that's an oversight, and won't be supported in lazer editor (while double left-click will be).

As in it should not be listed. Remove it or this cannot be merged.

2020-09-28 17:49 UTC, dorothy3242 commented
I see. Ok, I've now removed double right click and renamed double left click to just double click, as it appears left clicking is just referred to as clicking in other portions of the existing page.

2020-09-29 01:59 UTC, peppy approved these changes

2020-09-29 01:59 UTC, merged