[TH] Performance points
ppy/osu-wiki pull request #4263
Opened 2020-09-28 14:20 UTC by C0NS03L

2020-09-28 15:05 UTC, DatPanDat requested changes
I'll continue checking soon.

2020-09-29 09:47 UTC, C0NS03L commented on wiki/Performance_points/th.md
> +มันมีจุดมุ่งหมายที่จะแสดงความสามารถของผู้เล่นตามการเวลาจากเวลาที่เล่นไปทั้งหมด ค่านี้นั้นได้มาจากการคำนวน ที่คิดจากคะแนนที่ผู้เล่นได้ และระดับความยากใน[บีทแมพ(beatmap)](/wiki/Beatmaps)นั้นๆ
Changed ...มุ่งหมายที่จะแสดง... to มุ่งหมายเพื่อที่จะแสดง. It seems more smooth

And changed the other 2

2020-09-30 15:40 UTC, DatPanDat requested changes

2020-09-30 15:40 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +การนำมาใช้ครั้งแรกที่ถูกเปิดเผยต่อสาธารณะคือช่วงเดือนเมษายน ปี 2012 และผู้คนนั้นรู้แค่มันถูกเรียกว่า โปรเจค *'???'* และระบบนี้ก็ได้รับการตั้งชื่อในเวลาไม่นานหลังจากนั้น
การนำมาใช้ครั้งแรกที่ถูกเปิดเผยต่อสาธารณะคือ... -> ระบบนี้มีการนำมาใช้แบบเปิดเผยครั้งแรกในช่วง...

...และผู้คนนั้นรู้แค่มันถูกเรียกว่า... -> ...ซึ่งในตอนนั้นคนรู้จักระบบนี้ในนามว่า...

...และระบบนี้ก็ได้รับการตั้งชื่อในเวลาไม่นานหลังจากนั้น -> ...เท่านั้น และระบบนี้ก็มีการตั้งชท่อไม่นานหลังจากนั้น

2020-09-30 15:40 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +ซึ่งหลังจากนั้นระบบนี้เป็นที่รู้จักกันว่า pp (ตัวย่อของคำว่า "performance points") ระบบใหม่นี้นั้นเปลี่ยนมาตรฐานของผู้เล่น จากการนับความสามารถของผู้เล่นอย่างง่ายๆด้วย [คะแนน](/wiki/Score)รวมทั้งหมด เ
ซึ่งหลังจากนั้นระบบนี้เป็นที่รู้จักกันว่า pp (ตัวย่อของคำว่า "performance points")... -> หลังจากนั้น ระบบนี้ก็เป็นที่รู้จักกันในนามว่า pp (ที่ย่อมาจาก "performance points")...

...ระบบใหม่นี้นั้นเปลี่ยนมาตรฐานของผู้เล่น จากการนับความสามารถของผู้เล่นอย่างง่ายๆด้วย [คะแนน](/wiki/Score)รวมทั้งหมด เปลี่ยนเป็น... -> ...ระบบใหม่นี้จุดมุ่งหมายที่จะเปลี่ยนการนับคะแนนจากการดู[คะแนน](/wiki/Score)รวมเฉย ๆ เป็น...

...สิ่งที่แสดงความสามรถของผู้เล่นได้อย่างแม่นยำ ระบบใหม่นี้เป็นที่แพร่หลายเป็นอย่างมาก และมีเสียงตอบรับอย่างดีโดยฐานผู้เล่นในระยะเวลานั้น -> ...สิ่งที่แสดงความสามารถที่แท้จริงของผู้เล่น หลังจากการเปิดตัว ระบบนี้ก็ได้รับการตอบรับอย่างดีจากฐานผู้เล่นในระยะเวลานั้น

2020-09-30 15:40 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +ไม่กี่เดือนหลังจากที่ระบบนั้นถูกประกาศ การอัปเดต osu! 20120722-24 นั้นได้นำระบบนั้นมาใช้อย่างเต็มที่ เพื่อที่จะแทนทีระบบคะแนน [Ranked](/wiki/Beatmaps#ranked) แบบเก่า คะแนนใหม่จะถูกคำนวนทุกๆ 30 นาที แ
ไม่กี่เดือนหลังจากที่ระบบนั้นถูกประกาศ... -> ไม่กี่เดือนหลังจากการเปิดตัว...

...การอัปเดต osu! 20120722-24 นั้นได้นำระบบนั้นมาใช้อย่างเต็มที่... -> ....ระบบนี้ก็ได้มีการมาใช้อย่างเต็มที่ในอัปเดต osu! 20120722-24...

...เพื่อที่จะแทนทีระบบคะแนน [Ranked](/wiki/Beatmaps#ranked) แบบเก่า... -> ....เพื่อนำมาใช้แทนระบบคะแนน [Ranked](/wiki/Beatmaps#ranked) แบบเก่า...

...คำนวนทุกๆ 30 นาที... -> ...คำนวนทุก ๆ 30 นาที...

2020-10-13 11:44 UTC, DatPanDat requested changes
Please change all "คำนวน" into "คำนวณ"

2020-10-13 11:44 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +บีทแมพที่มีจำนวนโน้ตเยอะในเวลาสั้น ๆ ส่วนมากจะมีค่าความเร็วที่สูงมาก ในมุมมองนี้ยิ่งบีทแมพเร็วมากเท่าไหร่ การยากมากขึ้นเท่านั้น ดังนั้นจำทำให้ได้ pp เยอะขึ้น
...การยากมากขึ้นเท่านั้น... -> ...ความยากก็จะมากขึ้นเท่านั้น...

2020-10-13 11:44 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +*ความแม่นยำ* คือหน่วยวัดว่าผู้เล่นสามารถกด [hit objects(โน้ต)](/wiki/Hit_object) ได้ตรงเวลาขนาดไหน ซึ่งมีหน่วยเป็นเปอร์เซ็น และในมุมมองของระบบคิด pp มันเป็นค่าหลักที่กำหนดว่าผู้เล่นทำได้ดีแค่ไหนในบีท
...เปอร์เซ็น... -> ...เปอร์เซ็นต์...

2020-10-13 11:44 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +คะแนนที่มีความแม่นยำสูง จะถูกระบบคิดว่าเป็นคะแนนที่น่าประทับใจและจะได้คะแนนสูง การ [full combo](/wiki/Glossary#fc) ที่ได้ความแม่นยำ 80% นั้นบางครั้งอาจจะได้คะแนนแค่ 2/3 ของความแม่นยำ 95% เนื่่องจากสู
...นั้นบางครั้งอาจจะได้คะแนนแค่ 2/3 ของความแม่นยำ 95%... -> ...นั้นอาจจะได้คะแนนแค่ 2/3 ของความแม่นยำ 95% ในบางครั้ง...

2020-10-13 11:44 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +*ความเครียด* เป็นค่าหลักที่นับว่า กี่ครั้ง, และ นานเท่าไหร่ที่ผู้เล่นนั้นต้องเล่นส่วนที่มีความยากสูงในบีทแมพนั้น
...ค่าหลักที่นับว่า กี่ครั้ง, และ นานเท่าไหร่ที่ผู้เล่นนั้นต้องเล่นส่วนที่มีความยากสูงในบีทแมพนั้น -> ...เป็นค่าหลักที่จะดูว่าผู้เล่นนั้นต้องเล่นส่วนที่มีความยากสูงในบีทแมพนั้น ๆ นานแค่ไหน และกี่ครั้ง

2020-10-13 11:44 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +วิธีที่ดีที่สุดในการเพิ่มอันดับของคุณคือการเล่นได้คำแนนที่ดี บนแมพที่มีความยาก หรือ การเล่นบีทแมพที่หลากหลายThe
Remove the "The" at the end.

2020-10-13 11:44 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +คุณสามารถเรียนรู้เกี่ยวกับระบบชั่งน้ำหนักได้[ด้านบน](#ระบบการชั่งน้ำหนัก).
Remove the fullstop at the end.

2020-10-15 15:05 UTC, C0NS03L commented on wiki/Performance_points/th.md
> +การคำนวน Performance points จะขึ้นอยู่กับระดับความยากของบีทแมพ ซึ่งจะถูกคำนวนโดยอัลกอริทึมที่จะแตกต่างกันไปในแต่ละ [เกมโหมด](/wiki/Game_mode).
I think "เกมโหมด" should be separated since its specific terms that contain a link to another article.

2020-10-15 15:38 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +การคำนวน Performance points จะขึ้นอยู่กับระดับความยากของบีทแมพ ซึ่งจะถูกคำนวนโดยอัลกอริทึมที่จะแตกต่างกันไปในแต่ละ [เกมโหมด](/wiki/Game_mode).
Point taken and accepted.

2020-10-15 15:52 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +มันมีจุดมุ่งหมายที่จะแสดงความสามารถของผู้เล่น โดยจะดูจากเวลาที่ใช้เล่นไปทั้งหมด จนถึงการคำนวณความสามารถจริง ๆ ของผู้เล่น คซึ่งค่านี้จะนำมาจากการคำนวณคะแนนที่ขึ้นอยู่กับระดับความยากและคะแนนที่ผู้เล่นไ
"คซึ่งค่านี้จะ" Fix the ค that seems to be an unintentional happy accident.

2020-10-15 15:53 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +ระดับความยากของบีทแมพที่ผู้เล่น เล่นอยู่จะเป็นตัวกำหนด pp ที่ได้ตอนท้าย ตามการออกแบบสูตรคำนวณจะใช้ 4 ค่าหลัก ซึ่งประกอบไปด้วย **[การเล็ง](#การเล็ง)** **[ความเร็ว](#ความเร็ว)** **[ความแม่นยำ](#ความแม่
This wasn't overlooked on my part. Apologies.

...และท้ายสุด **[ความเครียด](#ความเครียด)**... -> ...และ **[ความเครียด](#ความเครียด)**...

2020-10-15 15:55 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +หลังจากนั้น คะแนนจะถูกนำมา "ชั่งน้ำหนัก" กับคะแนนอื่น ๆ เพื่อที่จะมั่นใจว่าคะแนนที่ดีที่สุดเท่านั้น ที่จะมีผลกับค่าประสิทธิภาพรวมของผู้เล่น [*การชั่งน้ำหนัก*](#ระบบการชั่งน้ำหนัก) เป้าหมายของมันคือกา
...[*การชั่งน้ำหนัก*](#ระบบการชั่งน้ำหนัก) เป้าหมายของมันคือการป้องกัน... -> ...เป้าหมายของ[*การชั่งน้ำหนัก*](#ระบบการชั่งน้ำหนัก) คือป้องกัน...

2020-10-15 15:58 UTC, DatPanDat commented on wiki/Performance_points/th.md
> +ในบีทแมพที่มีส่วนต่าง ๆ ที่ต้องการความเร็วสูงหรือมี [pattern](/wiki/Beatmaps/Pattern) ที่มีความยากนั้นจะเพิ่มค่าความเครียด เช่น บีทแมพที่มี [stream](/wiki/Beatmaps/Pattern/Stream) ที่เยอะ หรือการ jum
...ที่เยอะ... -> ...เยอะ ๆ...

2020-10-15 16:16 UTC, DatPanDat approved these changes
Seems good.

2020-10-17 00:05 UTC, TPGPL approved these changes

2020-10-17 00:05 UTC, merged