Create 2020-10-04-global-moderation-team-applications-open.md
ppy/osu-wiki pull request #4291
Opened 2020-10-03 12:49 UTC by osuChaos

newspost for gmt applications

2020-10-03 20:55 UTC, cl8n requested changes

2020-10-03 20:55 UTC, cl8n commented on news/2020-10-04-global-moderation-team-applications-open.md
> +- General requirements to join the GMT have not changed. You can read in detail about what we expect on [the GMT wiki page](https://osu.ppy.sh/help/wiki/People/The_Team/Global_Moderation_Team#becomin
```suggestion
- General requirements to join the GMT have not changed. You can read in detail about what we expect on [the GMT wiki page](/wiki/People/The_Team/Global_Moderation_Team#becoming-a-global-moderation-team-member), but in summary: you must be active in the in-game chat and/or the forums, you must demonstrate good behaviour by treating fellow community members with respect, you must possess a strong understanding of [osu!'s community rules](/wiki/Rules) and follow them, and you must already be contributing to bettering the community (by assisting other users, submitting reports for other users breaking the rules, etc.).
```

2020-10-03 20:55 UTC, cl8n commented on news/2020-10-04-global-moderation-team-applications-open.md
> +- You must have no major infractions on your account. This means any recent restrictions, multiaccount offenses, extended history of misbehaviour, etc will disqualify you from consideration from the
```suggestion
- You must have no major infractions on your account. This means any recent restrictions, multiaccount offenses, extended history of misbehaviour, etc. will disqualify you from consideration from the team.
```

2020-10-03 20:55 UTC, cl8n commented on news/2020-10-04-global-moderation-team-applications-open.md
> +We are not looking to fulfill any particular quota of new team members so any number of qualified applicants may be added. While we are accepting applications from everyone, we are actively seeking n
```suggestion
We are not looking to fulfill any particular quota of new team members, so any number of qualified applicants may be added. While we are accepting applications from everyone, we are actively seeking new members who are able to help us with these languages: **Arabic, Czech, Dutch, Finnish, Greek, Hebrew, Hungarian, Indonesian, Italian, Malaysian, Romanian, Portuguese, Spanish, Thai, and Vietnamese**.
```

2020-10-03 20:55 UTC, cl8n commented on news/2020-10-04-global-moderation-team-applications-open.md
> +—Chaos, Nathanael
```suggestion
—Chaos and Nathanael
```

2020-10-04 01:40 UTC, osuChaos commented on news/2020-10-04-global-moderation-team-applications-open.md
> +![](https://assets.ppy.sh/media/gmt_generic.jpg)
need @Ephemeralis to change this I believe

2020-10-04 03:02 UTC, Ephemeralis commented on news/2020-10-04-global-moderation-team-applications-open.md
> +![](https://assets.ppy.sh/media/gmt_generic.jpg)
no harm in leaving it on assets for now

2020-10-04 03:10 UTC, Ephemeralis commented on news/2020-10-04-global-moderation-team-applications-open.md
> +![](https://assets.ppy.sh/media/gmt_generic.jpg)
that being said i've moved it across anyway

2020-10-04 05:04 UTC, cl8n approved these changes

2020-10-04 12:18 UTC, Ephemeralis approved these changes

2020-10-04 12:18 UTC, merged