[ZH] Update Performance Poinra
ppy/osu-wiki pull request #4305
Opened 2020-10-06 11:26 UTC by PercyDan54

2020-10-09 06:13 UTC, kj415j45 requested changes
先歇会，后面还没看

2020-10-09 06:13 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +它的目标是把技术进步的中心从玩的时长变为玩家技术的一种体现。由根据谱面的难度和玩家表现计算玩家在[谱面](/wiki/Beatmaps)中的分数达成。
```suggestion
它的目标是把玩家水平的焦点从游玩的时长转变为玩家技术的实际体现。通过将[谱面](/wiki/Beatmaps)的难度与玩家在该谱面上的表现计算得出一个特有分数来达到这一目标。
```

2020-10-09 06:13 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +之后被称为 "pp"（"performance points"的缩写）。这个新系统寻找着代替玩家总 [分数](/wiki/Score) 准确表现玩家技术的标准。这个新系统在当时受到了玩家的广泛好评。
```suggestion
之后被称为 "pp"（"performance points"的缩写）。这个新系统寻求的是将先前简单基于玩家总分来判断水平的标准，转变为某种更能准确反映技巧的东西。在当时该系统受到了玩家群体的广泛赞誉。
```

2020-10-09 06:13 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +*住: ppv1，原始的pp系统也有一个更新日志，你可以通过它的[论坛主题](https://osu.ppy.sh/community/forums/topics/92185)查看。*
```suggestion
*注: ppv1，原始的 pp 系统也有一个更新日志，你可以通过它的[论坛主题](https://osu.ppy.sh/community/forums/topics/92185)查看。*
```

2020-10-09 13:49 UTC, PercyDan54 commented on wiki/Performance_points/ppv1/zh.md
改了，你看看

2020-10-18 04:18 UTC, kj415j45 approved these changes
md格式符前后的空格应该是不必要的，除非本身格式需求（比如中英混排？）

2020-10-18 04:18 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +玩家玩的谱面难度决定了成绩的最终pp值。公式被设计为根据四个主要数值： **[瞄准](#瞄准)**，**[速度](#速度)**，**[准确率](#准确率)**，和 **[耐力](#耐力)**。上述所有的值以不同的权重组合在一起，得到一个关于谱面特定的 [难度](/wiki/Difficulties)，和玩家在上谱面的个人表现。
```suggestion
玩家玩的谱面的难度决定了成绩的最终pp值。公式被设计为根据四个主要数值：**[瞄准](#瞄准)**，**[速度](#速度)**，**[准确率](#准确率)**，和**[耐力](#耐力)**。上述所有的值以不同的权重组合在一起，得到一个关于谱面特定的[难度](/wiki/Difficulties)，和玩家在上述谱面的个人表现。
```

2020-10-22 22:50 UTC, kj415j45 submitted a review, later dismissed

2020-10-23 08:21 UTC, TPGPL commented on wiki/Performance_points/zh.md
> +
a line is missing:
```md
Known thereafter as "pp" (an abbreviation for "performance points"), this new system sought to change the previous standard of player performance from simply total [score](/wiki/Score) to something that accurately reflected skill. The new system was met to widespread acclaim among the player base at the time.```

2020-10-23 16:34 UTC, TPGPL approved these changes

2020-10-23 16:35 UTC, merged