[ZH] OWC2020 Teams participating
ppy/osu-wiki pull request #4329
Opened 2020-10-12 17:25 UTC by Kotoki1337

#4323

2020-10-12 17:34 UTC, zeusminus commented
Netherlands (line 92), South Korea (line 102), and the United Kingdom (line 110) were left untranslated. Is it intentional?

2020-10-12 23:04 UTC, Kotoki1337 commented
> Netherlands (line 92), South Korea (line 102), and the United Kingdom (line 110) were left untranslated. Is it intentional?

No, just typo. I will fix soon

2020-10-16 12:55 UTC, WalterToro requested changes

2020-10-16 12:55 UTC, WalterToro commented on wiki/Tournaments/OWC/2020/zh.md
> +| ![][flag_PE] | **秘鲁** | **[Arnold24x24](https://osu.ppy.sh/users/2291265)**, [Meiph](https://osu.ppy.sh/users/2367544), [Mordo](https://osu.ppy.sh/users/4192805), [Judani](https://osu.ppy.sh/users/
```suggestion
| ![][flag_PE] | **秘鲁** | **[Hasaki](https://osu.ppy.sh/users/9037054)**, [Arnold24x24](https://osu.ppy.sh/users/2291265), [Meiph](https://osu.ppy.sh/users/2367544), [Mordo](https://osu.ppy.sh/users/4192805), [Judani](https://osu.ppy.sh/users/6787898), [Nkiad](https://osu.ppy.sh/users/13684411) |
```

2020-10-16 15:27 UTC, WalterToro approved these changes

2020-10-16 15:27 UTC, merged