[RU] update Russian country names and group info metadata
ppy/osu-wiki pull request #4343
Opened 2020-10-16 20:52 UTC by TicClick

2020-10-17 07:33 UTC, UristMcKobold requested changes

2020-10-17 07:33 UTC, UristMcKobold commented on meta/flag-references/ru.md
> +[flag_ME]: /wiki/shared/flag/ME.gif "Монтенегро"
```suggestion
[flag_ME]: /wiki/shared/flag/ME.gif "Черногория"
```

2020-10-17 07:33 UTC, UristMcKobold commented on meta/flag-references/ru.md
> +[flag_MA]: /wiki/shared/flag/MA.gif "Морокко"
```suggestion
[flag_MA]: /wiki/shared/flag/MA.gif "Марокко"
```

2020-10-17 07:33 UTC, UristMcKobold commented on meta/flag-references/ru.md
> +[flag_MD]: /wiki/shared/flag/MD.gif "Молдова"
```suggestion
[flag_MD]: /wiki/shared/flag/MD.gif "Молдавия"
```
или
```suggestion
[flag_MD]: /wiki/shared/flag/MD.gif "Республика Молдова"
```

2020-10-17 07:33 UTC, UristMcKobold commented on meta/flag-references/ru.md
> +[flag_TH]: /wiki/shared/flag/TH.gif "Тайланд"
```suggestion
[flag_TH]: /wiki/shared/flag/TH.gif "Таиланд"
```

2020-10-17 07:33 UTC, UristMcKobold commented on meta/group-info/ru.yaml
> +  ms: Малазийский
```suggestion
  ms: Малайзийский
```
или
```suggestion
  ms: Малайский
```

2020-10-17 09:31 UTC, GoodbyeShin requested changes

2020-10-17 09:31 UTC, GoodbyeShin commented on meta/flag-references/ru.md
> +[flag_MP]: /wiki/shared/flag/MP.gif "Марианские острова"
Марианские острова - это просто название группы островов. 
Скорее всего, должно быть "Северные Марианские Острова", перепроверь на всякий случай.

2020-10-17 19:24 UTC, TicClick commented on meta/flag-references/ru.md
> +[flag_BY]: /wiki/shared/flag/BY.gif "Беларусь"
оставлю так

2020-10-17 19:28 UTC, TicClick commented on meta/flag-references/ru.md
> +[flag_MP]: /wiki/shared/flag/MP.gif "Марианские острова"
```suggestion
[flag_MP]: /wiki/shared/flag/MP.gif "Северные Марианские Острова"
```

2020-10-17 19:28 UTC, TicClick commented on meta/flag-references/ru.md
> +[flag_TN]: /wiki/shared/flag/TN.gif "Тунисия"
```suggestion
[flag_TN]: /wiki/shared/flag/TN.gif "Тунис"
```

2020-10-18 13:58 UTC, UristMcKobold requested changes
Read through it again, looks good.

2020-10-18 13:58 UTC, UristMcKobold commented on meta/flag-references/ru.md
> +[flag_CY]: /wiki/shared/flag/CY.gif "Кипр"
```suggestion
[flag_CY]: /wiki/shared/flag/CY.gif "Республика Кипр"
```
Просто Кипр — это остров всё же, там ещё есть турецкие территории.

2020-10-18 14:25 UTC, UristMcKobold approved these changes

2020-10-18 14:32 UTC, TPGPL approved these changes

2020-10-18 14:32 UTC, merged