[ZH] Add seasonal information to Beatmap Spotlights
ppy/osu-wiki pull request #4346
Opened 2020-10-17 05:07 UTC by Kotoki1337

2020-10-18 04:33 UTC, kj415j45 commented on wiki/Beatmap_Spotlights/zh.md
> +| ![](img/badges/autumn_2020/osu/diamond_2.png) ![](img/badges/autumn_2020/osu/diamond_3.png) | 钻石（Diamond） | Top 51 – 3% |
为何使用 `U+2013 [–]`，我认为应该使用原来的 `U+002D [-]`，下同。

2020-10-18 04:33 UTC, kj415j45 commented on wiki/Beatmap_Spotlights/zh.md
> +| ![](img/badges/autumn_2020/osu/ri_2.png) ![](img/badges/autumn_2020/osu/ri_3.png) | 人乐合一（Rhythm Incarnate） | Top 50 |
Rhythm Incarnate 有其他翻译吗，“人乐合一”第一眼看不出是“音乐”的“乐”，或许改用“韵律”的“韵”？

2020-10-18 06:52 UTC, cl8n commented on wiki/Beatmap_Spotlights/zh.md
> +| ![](img/badges/autumn_2020/osu/diamond_2.png) ![](img/badges/autumn_2020/osu/diamond_3.png) | 钻石（Diamond） | Top 51 – 3% |
en dashes usually signify ranges when using arabic numerals , I think this is slightly better than hyphens (not that it really matters though..)

2020-10-18 07:23 UTC, Kotoki1337 commented on wiki/Beatmap_Spotlights/zh.md
> +| ![](img/badges/autumn_2020/osu/ri_2.png) ![](img/badges/autumn_2020/osu/ri_3.png) | 人乐合一（Rhythm Incarnate） | Top 50 |
> Rhythm Incarnate 有其他翻译吗，“人乐合一”第一眼看不出是“音乐”的“乐”，或许改用“韵律”的“韵”？

可以，人韵合一。我文盲了，实在想不出好的了

2020-10-19 04:12 UTC, kj415j45 submitted a review, later dismissed

2020-10-29 05:50 UTC, cl8n requested changes
overall:

- decide if you want to translate "Beatmap Spotlights" or not, and apply it consistently (so this might contradict some of my comments depending on what u choose)
- you can translate the season names/titles too
- does "Playlist" have a translation?
- I think you should use china's timezone like you did for some other articles
- for tags, check that /Beatmap_Spotlights has the correct ones, then copy it to the other articles

2020-10-29 05:50 UTC, cl8n commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/zh.md
> +| Event | 时间 |
"Event" should be translated, also on summer 2020 same thing

2020-10-29 05:50 UTC, cl8n commented on wiki/Beatmap_Spotlights/zh.md
> +**月赛**（Beatmap Spotlights，也被称为 *Ranking Charts*）是一个定期举办的活动系统，用于推荐或突出玩家制作的拥有出色或独特玩法设计的[谱面](/wiki/Beatmaps)。它有一个[赛季排行榜](#赛季)，并为所有参与的玩家提供奖励。
"Beatmap Spotlights" should be italics, since you're pointing out a title for the first time

2020-10-29 05:50 UTC, cl8n commented on wiki/Beatmap_Spotlights/zh.md
> +![Beatmap Spotlights logo](/wiki/shared/news/banners/beatmap-spotlights.jpg)
here Beatmap Spotlights should be translated

2020-10-29 05:50 UTC, cl8n commented on wiki/Beatmap_Spotlights/zh.md
>    - 月赛
this tag doesn't need to appear here, since it's already in the title.

2020-10-29 05:50 UTC, cl8n commented on wiki/Beatmap_Spotlights/Seasons/zh.md
> +- [Autumn 2020](2020_Autumn)
whole thing can use translated titles

2020-12-01 19:38 UTC, cl8n reviewed
there's [this new paragraph](https://github.com/ppy/osu-wiki/pull/4531/files#diff-008eaf93539330f66fd7e64221f5c86b6e996c4e0dec208257d960c1bdfcb8e0R179) in EN, I applied the rest of the updates

2020-12-01 19:38 UTC, cl8n commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/zh.md
> +| Intermission | 2020-11-06/2020-11-13 |
I updated this schedule for you but idk how to translate "Intermission"

2021-01-19 10:58 UTC, TicClick commented
@Kotoki1337 what's the status of this PR?

2021-01-19 11:20 UTC, Kotoki1337 commented
> @Kotoki1337 what's the status of this PR?

In discussing, but we already have a result. I'm working on the pr those days, so I think it can be done tomorrow. Also keep this translation article up to date.

2021-01-24 17:01 UTC, cdwcgt approved these changes

2021-01-25 12:11 UTC, TicClick approved these changes

2021-01-25 12:13 UTC, merged