Add SOL2 tournament article
ppy/osu-wiki pull request #4353
Opened 2020-10-18 19:38 UTC by ItsMestro

2020-10-20 15:56 UTC, TPGPL requested changes

2020-10-20 15:56 UTC, TPGPL commented on wiki/Tournaments/SOL/2019/en.md
change `It was the first installment of the Speed of Light Mania Tournament.` in line 10 to `It was the first installment of the Speed of Light.`

2020-10-20 15:56 UTC, TPGPL commented on wiki/Tournaments/SOL/2020/en.md
> +**Speed of Light 2: Lucha Libre Edition** (***SOL2***) is a double-elimination 1v1 osu!mania 4K tournament hosted by ![][flag_US] [stupud man](https://osu.ppy.sh/users/2141612), ![][flag_MX] [\[Crz\]
```suggestion
**Speed of Light 2: Lucha Libre Edition** (***SOL2***) is a double-elimination 1v1 osu!mania 4-key tournament hosted by ![][flag_US] [stupud man](https://osu.ppy.sh/users/2141612), ![][flag_MX] [\[Crz\]Crystalize](https://osu.ppy.sh/users/3072763), ![][flag_US] [ZeroRam](https://osu.ppy.sh/users/8454732), ![][flag_US] [Penguinosity](https://osu.ppy.sh/users/10235296) and ![][flag_US] [Logan636](https://osu.ppy.sh/users/9423766). It is the second installment of the Speed of Light.
```

2020-10-22 18:22 UTC, cl8n approved these changes

2020-10-23 17:14 UTC, TPGPL approved these changes

2020-10-23 17:15 UTC, merged