[UA] Main Page
ppy/osu-wiki pull request #4356
Opened 2020-10-19 18:47 UTC by atimonder1

Translation of the Main Page of the wiki into Ukrainian language

2020-10-19 21:09 UTC, TicClick commented
suprisingly, it's UK for Ukrainian locale. ugh
do you know anyone proficient in Ukrainian to toss this to for a review?

2020-10-19 21:31 UTC, atimonder1 commented
> suprisingly, it's UK for Ukrainian locale. ugh
> do you know anyone proficient in Ukrainian to toss this to for a review?

yeah, I have, he will check this afternoon, in theory

2020-10-25 16:01 UTC, Andrey08083 requested changes

2020-10-25 16:01 UTC, Andrey08083 commented on wiki/Main_Page/uk.md
> +Организаторы: [osu! UCI](/wiki/Organisations/osu!_UCI)
Організатори

2020-10-25 16:42 UTC, TicClick approved these changes

2020-10-25 16:42 UTC, merged