Cleanup and unify the style of the OWC articles
ppy/osu-wiki pull request #4365
Opened 2020-10-23 02:57 UTC by fajar13k

- Some maps are missing/deleted
- Some players are missing/restricted/banned
- Will keep updating until ready
- Add flag name references
- Optimize image to use `.jpg` if there aren't Alpha Channels used

2020-10-26 05:01 UTC, fajar13k commented
Ready for review

2020-10-30 19:20 UTC, TPGPL requested changes
bracketES.jpg for OWC 2014 should be renamed to bracket-ES.jpg according to ASC

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/2016/en.md
>  | Finals - Week 1 | 2016-12-10/2016-12-11 |
```suggestion
| Finals week 1 | 2016-12-10/2016-12-11 |
```

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/2016/en.md
> +| Finals - Week 2 | 2016-12-18 |
```suggestion
| Finals week 2 | 2016-12-18 |
```

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/2016/en.md
> +**This mappool was played during the Finals - Week 1 and Finals - Week 2.**
```suggestion
**This mappool was played during the Finals week 1 and Finals week 2.**
```

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/2016/en.md
>  ### Grand Finals
```suggestion
### Finals week 2
```

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/2016/en.md
>  ### Finals
```suggestion
### Finals week 1
```

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/2018/en.md
>  ---
should rename Grand Finals -> Finals week 2 and Finals -> Finals week 1 
like in previous installments

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/2019/en.md
Finals -> Finals week 1
Grand Finals - > Finals week 2

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/3/en.md
> +| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | 6 months of osu!supporter tag, unique profile badge, T-Shirt |
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | 6 months of osu!supporter tag, unique profile badge, T-shirt |
```

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/3/en.md
> +  - [Nishino Kana - Distance (Magicphoenix) \[Normal\]](https://osu.ppy.sh/beatmapsets/43016#osu/137219)
not intentional

2020-10-30 19:20 UTC, TPGPL commented on wiki/Tournaments/OWC/3/en.md
> +  - [yonji - Waruku nai ne (Reiji-RJ) \[BSY\]](https://osu.ppy.sh/beatmapsets/33692#osu/109757)
broken diff names

2020-10-31 17:28 UTC, TPGPL requested changes

2020-10-31 17:28 UTC, TPGPL commented on wiki/Tournaments/OWC/3/en.md
> +  - [Hatsune Miku - Kimi ni Uso (KanaRin) \[Clare\]](https://osu.ppy.sh/beatmapsets/25000#osu/87645)
all links still broken?

2020-10-31 19:57 UTC, fajar13k commented on wiki/Tournaments/OWC/2/en.md
> +  - [Kuripurin - Jutenija (qinche) \[Jutenija\]](https://osu.ppy.sh/beatmapsets/25500#osu/86377)
Mapper might rename it to Jutenija, Id's still the same, but diff'll be renamed to Insane again in the next commit

2020-10-31 20:05 UTC, TPGPL commented on wiki/Tournaments/OWC/2/en.md
> +  - [Kuripurin - Jutenija (qinche) \[Jutenija\]](https://osu.ppy.sh/beatmapsets/25500#osu/86377)
nvm, it may stay as it is, i thought there was a diff called Insane in the beatmapset

2020-10-31 20:11 UTC, fajar13k commented on wiki/Tournaments/OWC/2/en.md
> +  - [Kuripurin - Jutenija (qinche) \[Jutenija\]](https://osu.ppy.sh/beatmapsets/25500#osu/86377)
Will also declare some diffs have evolved and get renamed example OWC2013 L227 and OWC2016 L125

2020-10-31 20:30 UTC, TPGPL approved these changes

2020-10-31 20:32 UTC, merged