[RU] upppy
ppy/osu-wiki pull request #4373
Opened 2020-10-25 19:14 UTC by Randelman4ik

2020-10-27 18:15 UTC, UristMcKobold requested changes

2020-10-27 18:15 UTC, UristMcKobold commented on wiki/upppy/ru.md
> +**[upppy](https://up.ppy.sh)** это сервис по загрузке файлов, организованный ![][flag_AU] [peppy](https://osu.ppy.sh/users/2). В основном он используется для выгрузки фотографий, чтобы делиться ими с
```suggestion
**[upppy](https://up.ppy.sh)** — это сервис по загрузке файлов, организованный ![][flag_AU] [peppy](https://osu.ppy.sh/users/2). В основном он используется для выгрузки картинок, чтобы делиться ими с сообществом osu!.
```
Тире обязательно. 
«организованный» не передаёт смысла оригинала, но я не знаю, как это лучше описать. Хостящийся у пеппи?
 Не фотографий, а картинок.

2020-10-27 18:19 UTC, atimonder1 commented on wiki/upppy/ru.md
> +**[upppy](https://up.ppy.sh)** это сервис по загрузке файлов, организованный ![][flag_AU] [peppy](https://osu.ppy.sh/users/2). В основном он используется для выгрузки фотографий, чтобы делиться ими с
Не было бы более красноречиво сделать наподобие:
`upppy является сервисом по загрузке файлов, организованным peppy`?

2020-10-27 18:29 UTC, Randelman4ik commented on wiki/upppy/ru.md
> +**[upppy](https://up.ppy.sh)** это сервис по загрузке файлов, организованный ![][flag_AU] [peppy](https://osu.ppy.sh/users/2). В основном он используется для выгрузки фотографий, чтобы делиться ими с
@UristMcKobold  Сам не знаю, как грамотно это описать. Твой вариант "хостящийся у пеппи" мне не очень нравится.
"фотографий" -> "картинок" - согласен
А насчет тире.. Облажался тупо :)  

@atimonder1 не думаю

2020-10-27 21:34 UTC, TicClick requested changes

2020-10-27 21:34 UTC, TicClick commented on wiki/upppy/ru.md
> +**[upppy](https://up.ppy.sh)** — это сервис по загрузке файлов, организованный ![][flag_AU] [peppy](https://osu.ppy.sh/users/2). В основном он используется для выгрузки картинок, чтобы делиться ими с
```suggestion
**[upppy](https://up.ppy.sh)** — это сервис для загрузки файлов, организованный ![][flag_AU] [peppy](https://osu.ppy.sh/users/2). В основном он используется для хранения и передачи картинок внутри сообщества osu!.
```

2020-10-27 21:34 UTC, TicClick commented on wiki/upppy/ru.md
> +# upppy
это по-прежнему заготовка, тег нужно оставить:

```suggestion
---
stub: true
---

# upppy
```

2020-10-28 15:06 UTC, TicClick approved these changes

2020-10-28 15:06 UTC, merged