[RU] Star_rating
ppy/osu-wiki pull request #4374
Opened 2020-10-26 17:19 UTC by Randelman4ik

2020-10-28 09:54 UTC, ryuu commented
переведено настолько плохо, что править что-то бесполезно
всё время было ощущение, что текст просто вбили в гугл переводчик
пожалуйста, не беритесь за переводы, если не уверены в их качестве

2020-10-28 14:58 UTC, TicClick requested changes
я согласен, это больше похоже на машинный или дословный перевод и подлежит переписыванию

2020-10-28 17:29 UTC, Randelman4ik commented
Полностью согласен с Вами, надеюсь сейчас стало гораздо лучше.

2020-10-31 01:50 UTC, TicClick requested changes
стало получше, но всё равно не очень:
- названия сложностей не надо переводить;
- название термина тоже не надо переводить, а нужно лишь дать расшифровку;
- от машинного перевода ты всё равно не избавился: *Этапы звёздного рейтинга* и некоторые неестественные формулировки предложений.

я считаю, тебе нужно ещё потренироваться, прежде чем переводить, а этот пулл-реквест закрыть. пока что мне вместо ревью проще перевести статью с нуля, потому что ревью сведётся к переписыванию (см. раздел «как?» в [треде про перевод](https://osu.ppy.sh/community/forums/topics/566978))

2020-10-31 09:39 UTC, closed without merging