[UK] Getting Started
ppy/osu-wiki pull request #4376
Opened 2020-10-27 13:06 UTC by atimonder1

- [x] Help Centre
- [ ] Help Centre (Account Restrictions)
- [x] Installation
- [ ] Installation (macOS)
- [x] Registration
- [x] Welcome
- [ ] FAQ

2020-10-30 20:25 UTC, atimonder1 commented
I'm a little dumb in terms of translating the FAQ, I just don't understand how to choose the correct words lmao. PR is ready for review

2020-11-10 04:03 UTC, sr229 requested changes
We already established that `en.md` is British English so you might want to merge your changes there.

2020-11-11 04:08 UTC, MegaApplePi commented
@sr229 UK is Ukrainian.

2020-11-13 16:53 UTC, TicClick requested changes
I don't know Ukrainian, but these are my findings so far. I'll also see if I can find someone proficient to give it a read.

2020-11-13 16:53 UTC, TicClick commented on wiki/Help_Centre/uk.md
> +- [Microsoft core web fonts](https://web.archive.org/web/20020124085641/http://www.microsoft.com/typography/fontpack/default.htm) (особливо Arial, Times New Roman, Trebuchet MS, and Verdana)
```suggestion
- [Microsoft core web fonts](https://web.archive.org/web/20020124085641/http://www.microsoft.com/typography/fontpack/default.htm) (особливо Arial, Times New Roman, Trebuchet MS i Verdana)
```

2020-11-13 16:53 UTC, TicClick commented on wiki/Help_Centre/uk.md
> +- [Microsoft JhengHei](https://microsoft.com/en-us/download/details.aspx?&id=12072) (微軟正黑體) (Традиційний Chinese UI шрифт)
_Традиційний Chinese UI шрифт_ — это шрифт для традиционного китайского, переведи фразу целиком

2020-11-13 16:53 UTC, TicClick commented on wiki/Help_Centre/uk.md
> +#### Що за 'log files' і як я можу зробити їх?
log files нужно перевести

2020-11-13 16:53 UTC, TicClick commented on wiki/Help_Centre/uk.md
> +1. Відкрийте *osu*.
```suggestion
1. Відкрийте osu!.
```

2020-11-17 23:51 UTC, TicClick commented
(English for clarity)

I've asked a native speaker to proof-read this, and the feedback was less than satisfactory (not a quote):
- half-assed, sound more like a machine translation;
- would take quite some time to get it into appropriate shape;
- highly recommended to use Russian articles as a basis for translation, as they share most of grammar rules.

make of that what you will, with that I don't feel the pull request is good enough. you probably want to wait for a guy himself to show up either with improved translation, or with a new review, at least he claimed he'd do so.

2020-11-18 06:42 UTC, closed without merging