[RU] Как решить проблему с публикацией карты
ppy/osu-wiki pull request #4380
Opened 2020-10-28 18:56 UTC by Esutarosa

2020-10-28 19:32 UTC, Randelman4ik commented on wiki/Guides/BSS_Issues/ru.md
> +1. Экспортируйте битмап с помощью редактора.
мне кажется, что вместо "битмап" следует использовать "карту"

2020-10-28 19:32 UTC, Randelman4ik commented on wiki/Guides/BSS_Issues/ru.md
> +7. Убедитесь что название папки с битмапом не начинается с цифр.
"битмапом" -> "картой"

2020-10-28 19:34 UTC, Randelman4ik commented on wiki/Guides/BSS_Issues/ru.md
> +7. В поле `Creator` впишите любой ник но не используйте свой.
```suggestion
7. В поле `Creator` впишите любой ник, но не используйте свой.
```

2020-10-28 19:39 UTC, atimonder1 requested changes
Не знаю, но мне кажется, что это всё было проделано машинным переводом или попросту дословно.

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +Если при **[публикации карты](/wiki/Submission)** на сервер возникает ошибка «Вы не являетесь владельцем этой карты», то выполните эти действия:
Эм, перевод не соответствует оригиналу, лучше сделай так:
```suggestion
Если **[система публикаций карт](/wiki/Submission)** не даёт вам выгрузить свою карту, так как она говорит, что она не ваша, выполните следующие действия:
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +   - Зайдите в [редактор](/wiki/Beatmap_Editor), выберите `Файл` затем `Открыть папку с песней`.
Забыл запятую:
```suggestion
   - Зайдите в [редактор](/wiki/Beatmap_Editor), выберите `Файл`, а затем `Открыть папку с песней`.
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +4. В поле `Creator` введите свой ник (если в нике имеются пробелы, то их тоже используйте).
Ты немного странно написал в скобках предложение, давай исправим это:
```suggestion
4. В поле `Creator` введите свой ник (если в нике имеются пробелы, используйте их тоже).
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +9. Откройте игру и попробуйте еще раз загрузить карту.
Тавтология + некоторые странности, связанные с текстом:
```suggestion
8. Удалите файл(ы) в папке `SubmissionCache`. Они находятся в директории, где установлена osu!.
9. Откройте игру и попробуйте еще раз выгрузить карту.
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +2. Удалите карту в osu!.
Не битмап, а карту, забыл запятую + ты сломал markdown дополнительным апострофом, не "в", а "из":
```suggestion
1. Экспортируйте карту с помощью редактора.
   - `Файл` затем `Экспортировать в .osz`.
2. Удалите эту же карту из osu!.
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +5. Распакуйте файл `.zip`.
Почему именно "файл"? Это же архив:
```suggestion
5. Распакуйте `.zip` архив.
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +7. В поле `Creator` впишите любой ник но не используйте свой.
Забыл запятую:
```suggestion
7. В поле `Creator` впишите любой ник, но не используйте свой.
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +10. После заархивируйте файлы обратно в файл `.zip`.
"После **этого**...", тавтология:
```suggestion
10. После этого, заархивируйте файлы обратно в `.zip`.
```

2020-10-28 19:39 UTC, atimonder1 commented on wiki/Guides/BSS_Issues/ru.md
> +13. Если это не поможет, то вы можете попросить помощи [тут](https://osu.ppy.sh/community/forums/5), разумеется на английском.
Эм?
```suggestion
13. Если это не помогло вам, вы можете попросить помощи [тут](https://osu.ppy.sh/community/forums/5), разумеется на английском языке.
```

2020-10-31 01:53 UTC, TicClick reviewed
перевод и правда по-прежнему похож либо на небрежный, либо на машинный. в любом случае, его нужно переделывать, вместо ревью тут тоже будет переписывание, как и в #4374.

предлагаю закрыть пулл-реквест и поупражняться в а) переводе и б) владении русским языком

2020-10-31 13:18 UTC, Esutarosa commented
> перевод и правда по-прежнему похож либо на небрежный, либо на машинный. в любом случае, его нужно переделывать, вместо ревью тут тоже будет переписывание, как и в #4374.
> 
> предлагаю закрыть пулл-реквест и поупражняться в а) переводе и б) владении русским языком

ок, я закрываю пулл-реквест.

2020-11-02 18:26 UTC, closed without merging