[TH] Tournaments
ppy/osu-wiki pull request #4406
Opened 2020-11-04 09:02 UTC by C0NS03L

2020-11-06 16:48 UTC, Trigonoculus reviewed
พวกตารางดูผ่านๆ แล้วคิดว่าโอเคนะครับ

2020-11-06 16:48 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +ส่วนนี้มีไว้สำหรับ ทัวร์นาเมนต์ osu! ทัวร์นาเมนต์นั้นมีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่ [ลิ้งค์นี้](https://osu.ppy.sh/community/forums/55)
```suggestion
ส่วนนี้มีไว้สำหรับ ทัวร์นาเมนต์ osu! โดยทัวร์นาเมนต์มีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่ [ลิ้งค์นี้](https://osu.ppy.sh/community/forums/55)
```
More clarity

2020-11-06 16:48 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +- [osu!tourney](/wiki/osu!tourney) (Client used for tournament streaming)
```suggestion
- [osu!tourney](/wiki/osu!tourney) (โปรแกรมที่ใช้สำหรับถ่ายทอดสดทัวร์นาเมนต์)
```

2020-11-06 16:48 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +## Official World Cups
```suggestion
## การแข่งขัน World Cup อย่างเป็นทางการ
```

2020-11-06 16:48 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +- [รายการประเทศที่เข้าร่วมในทัวร์ทัวร์นาเมนต์](Countries_that_participated_in_osu!_tournaments)
```suggestion
- [รายการประเทศที่เข้าร่วมในทัวร์นาเมนต์](Countries_that_participated_in_osu!_tournaments)
```

2020-11-08 10:58 UTC, Trigonoculus requested changes

2020-11-08 10:58 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +ทัวร์นาเมนต์ Official ที่ถูกจัดขึ้นโดยทีมงานทัวร์นาเมนต์ของ osu!
```suggestion
ทัวร์นาเมนต์อย่างเป็นทางการที่ได้จัดขึ้นโดยทีมงานทัวร์นาเมนต์ของ osu!
```

2020-11-08 10:58 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +ส่วนนี้มีไว้สำหรับ ทัวร์นาเมนต์ osu! โดยทัวร์นาเมนต์มีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่ [ลิ้งค์นี้](https://osu.ppy.sh/community/forums/55)
```suggestion
ส่วนนี้มีไว้สำหรับ ทัวร์นาเมนต์ osu! โดยทัวร์นาเมนต์มีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่[ลิ้งค์นี้](https://osu.ppy.sh/community/forums/55)
```

2020-11-08 10:58 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +การแข่งขัน/ทัวร์ทัวร์นาเมนต์ ที่จัดขึ้นโดยคนในชุมชน
```suggestion
การแข่งขัน/ทัวร์นาเมนต์ ที่จัดขึ้นโดยคนในชุมชน
```

2020-11-08 10:58 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +| ชื่อ | เริ่มต้น | จบ | ![Gold crown][GCrown] | ![Silver crown][SCrown] | ![Bronze crown][BCrown] |
Find & Replace พวก Gold crown / silver crown / ... เป็นภาษาไทยด้วยดีมั้ยครับ

2020-11-08 11:01 UTC, C0NS03L commented on wiki/Tournaments/th.md
> +| ชื่อ | เริ่มต้น | จบ | ![Gold crown][GCrown] | ![Silver crown][SCrown] | ![Bronze crown][BCrown] |
อยู่ใต้ไฟล์ครับ พวกนี้เป็นชื่อ tooltips ที่จะ reference มาจากใต้ไฟล์

2020-11-08 11:02 UTC, C0NS03L commented on wiki/Tournaments/th.md
> +ส่วนนี้มีไว้สำหรับ ทัวร์นาเมนต์ osu! โดยทัวร์นาเมนต์มีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่ [ลิ้งค์นี้](https://osu.ppy.sh/community/forums/55)
เอาจริง ๆ สะกดผิดด้วย มันต้อง ลิงก์

2020-11-08 11:04 UTC, C0NS03L commented on wiki/Tournaments/th.md
> +ส่วนนี้มีไว้สำหรับ ทัวร์นาเมนต์ osu! โดยทัวร์นาเมนต์มีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่ [ลิ้งค์นี้](https://osu.ppy.sh/community/forums/55)
แล้วก็ imo ผมว่าควรใส่ space ไว้

2020-11-10 15:36 UTC, Trigonoculus requested changes

2020-11-10 15:36 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +ส่วนนี้มีไว้สำหรับ ทัวร์นาเมนต์ osu! โดยทัวร์นาเมนต์มีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่ [ลิ้งก์นี้](https://osu.ppy.sh/community/forums/55)
```suggestion
ส่วนนี้มีไว้สำหรับทัวร์นาเมนต์ osu! โดยทัวร์นาเมนต์มีฟอรั่มของตัวเองซึ่งสามารถหาได้ที่[ลิ้งก์นี้](https://osu.ppy.sh/community/forums/55)
```

2020-11-10 15:36 UTC, Trigonoculus commented on wiki/Tournaments/th.md
> +osu! World Cup นั้นจะแบ่งทีมเป็นประเทศ ซึ่งจะแข่งเป็น 4v4 Team VS โดยทำตามกฎ Double Elimination ซึ่งเป็นการแข่งระหว่างประเทศ และจะถูกจัดขึ้นทุก ๆ ปี โดยที่ชุมชน osu! ทั่วโลกนั้นช่วยกันจัดทัวร์นาเมนต์
```suggestion
osu! World Cup นั้นจะแบ่งทีมเป็นประเทศ ซึ่งจะแข่งเป็น 4v4 Team VS ตามกฎ Double Elimination ซึ่งเป็นการแข่งระหว่างประเทศ และจะถูกจัดขึ้นทุก ๆ ปี โดยที่ชุมชน osu! ทั่วโลกนั้นช่วยกันจัดทัวร์นาเมนต์นี้ขึ้นมา
```
คำว่าโดย ซ้ำ

2020-11-12 19:19 UTC, TicClick approved these changes

2020-11-12 19:20 UTC, merged