Recheck unification in TWC, CWC, MWC
ppy/osu-wiki pull request #4413
Opened 2020-11-06 07:53 UTC by fajar13k

- Leftover map links
- Some missing players
- Reformat tables
- Minor naming change
- Replace pictures to `.jpg` except it has alpha channels
- Will keep updating until it is ready for review

2020-11-07 00:19 UTC, TPGPL commented on wiki/Tournaments/TWC/3/en.md
> +[flag_VE]: /wiki/shared/flag/VE.gif "Venezuela"
unify Group Stage headers in mappool section (`Group Stage (Week X)` -> `Group Stage week X`)

2020-11-10 17:58 UTC, TPGPL requested changes
maybe if the beatmap is unaccessable even through bloodcat, then maybe remove the link completely?

2020-11-10 17:58 UTC, TPGPL commented on wiki/Tournaments/CWC/2016/en.md
>    - [Seiryu - Ultramarine (ZiRoX) \[Spec's Abyss\]](https://osu.ppy.sh/beatmapsets/275991#fruits/635701)
L151 escape strikethrough

2020-11-10 22:23 UTC, fajar13k commented
Sure we can remove them, but I may include its beatmaps id in the comment
e.g.: `<!-- map is missing (beatmaps id) -->`

2020-11-10 22:52 UTC, TPGPL approved these changes

2020-11-10 22:52 UTC, merged