Add Indonesia Convert Cup 2020 wiki article
ppy/osu-wiki pull request #4431
Opened 2020-11-10 04:00 UTC by Nivalyx

wiki article for the recently concluded Indonesia Convert Cup 2020 tournament

2020-11-10 16:33 UTC, TPGPL requested changes

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +The **Indonesia Convert Cup 2020** (***ICC 2020***) was a double-elimination 1v1 osu!catch tournament hosted by ![][flag_ID] [Eum](https://osu.ppy.sh/users/16552751), ![][flag_ID] [Kazuyo](https://os
```suggestion
The **Indonesia Convert Cup 2020** (***ICC 2020***) was a double-elimination 1v1 osu!catch tournament hosted by ![][flag_ID] [Eum](https://osu.ppy.sh/users/16552751), ![][flag_ID] [Kazuyo](https://osu.ppy.sh/users/5604201), and ![][flag_ID] [Dapuluous](https://osu.ppy.sh/users/8140944) in which, all beatmaps played in the tournament were converted osu! beatmaps. The tournament was open to all osu!catch players from Indonesia with over 5,000 osu!catch playcount regardless of rank. It was the first installment of the Indonesia Convert Cup.
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +| Finals Week | 2020-11-02/2020-11-08 |
```suggestion
| Finals | 2020-11-02/2020-11-08 |
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | IDR 450.000,- + 20% of the raised prize pool |
```suggestion
| Placing | Prizes |
| :-: | :-- |
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | IDR 1.000.000, ~50% of the raised prize pool, unique profile badge |
| ![Silver crown](/wiki/shared/crown-silver.png "2nd place") | IDR 600.000, ~30% of the raised prize pool |
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | IDR 450.000, ~20% of the raised prize pool |
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +![Profile badge](img/badge.png)
```suggestion
![ICC 2020 winner badge](img/badge.png)
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +| Map selector | ![][flag_ID] [Constantine](https://osu.ppy.sh/users/3221898), ![][flag_ID] [Yuri-](https://osu.ppy.sh/users/4983719), ![][flag_ID] [Toka](https://osu.ppy.sh/users/1595221) |
```suggestion
| Mappool selector | ![][flag_ID] [Constantine](https://osu.ppy.sh/users/3221898), ![][flag_ID] [Yuri-](https://osu.ppy.sh/users/4983719), ![][flag_ID] [Toka](https://osu.ppy.sh/users/1595221) |
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +- [Livestream](https://www.twitch.tv/osuIndonesia/)
```suggestion
- [Livestream](https://www.twitch.tv/osuIndonesia)
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +Sunday, 8 November 2020, Grand Final:
```suggestion
Sunday, 8 November 2020 (Grand Finals):
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +| Grand Final | [Galaxi](https://osu.ppy.sh/users/2552435) ![][flag_ID] | 3 | **7** | ![][flag_ID] **[dika312](https://osu.ppy.sh/users/741613)** | [#1](https://osu.ppy.sh/community/matches/69502037)
```suggestion
| Grand Finals | [Galaxi](https://osu.ppy.sh/users/2552435) ![][flag_ID] | 3 | **7** | ![][flag_ID] **[dika312](https://osu.ppy.sh/users/741613)** | [#1](https://osu.ppy.sh/community/matches/69502037) |
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +| Grand Final (Bracket Reset) | **[dika312](https://osu.ppy.sh/users/741613)** ![][flag_ID] | **7** | 3 | ![][flag_ID] [Galaxi](https://osu.ppy.sh/users/2552435) | [#1](https://osu.ppy.sh/community/m
```suggestion
| Grand Finals (Bracket Reset) | **[dika312](https://osu.ppy.sh/users/741613)** ![][flag_ID] | **7** | 3 | ![][flag_ID] [Galaxi](https://osu.ppy.sh/users/2552435) | [#1](https://osu.ppy.sh/community/matches/69505076) |
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +### Match Regulations
```suggestion
### Match regulations
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +### Knock-Out Stage Rules
```suggestion
### Knockout Stage rules 
```

2020-11-10 16:33 UTC, TPGPL commented on wiki/Tournaments/ICC/2020/en.md
> +### Group Stage Rules
```suggestion
### Group Stage rules
```

2020-11-11 02:17 UTC, Nivalyx commented
applied most of TPGPL's suggestions

the only one that i didn't apply was the "osu!standard" -> "osu!" suggestion as i think "osu!standard" has more clarity for the context but aside from that everything else have been applied and resolved 👍

2020-11-11 13:57 UTC, TPGPL approved these changes

2020-11-11 13:58 UTC, merged