Editing BBCode wiki article
ppy/osu-wiki pull request #4436
Opened 2020-11-11 01:22 UTC by GalaxyOsu

I resolved some of the missing tests in the bbcode (also deleted "google" and "lucky" because they are not working anymore) and updated images

2020-11-11 03:45 UTC, C0NS03L commented on wiki/BBCode/en.md
>  # BBCode
```suggestion
# BBCode
```
Remove 2 lines before the BBCode line

2020-11-11 04:06 UTC, MegaApplePi requested changes
Because of how images are cached on the website, you will either need to rename the images you updated or append a query string to the image link on the article itself.

2020-11-11 04:06 UTC, MegaApplePi commented on wiki/BBCode/en.md
> +<!-- Deleted "Google" and "Lucky" because they doesnt work no more in the new website -->
```suggestion
```
You shouldn't need a note here to say why it was removed.

2020-11-11 04:32 UTC, paper-toaster commented
I am currently working on a half-rewrite half-cleanup of the bbcode article. It'd be best to keep the Google and lucky tags for historical purposes

2020-12-29 01:08 UTC, TPGPL commented
Superseded by #4600

2020-12-29 01:08 UTC, closed without merging