Add FA/Mappers Guild updates news post
ppy/osu-wiki pull request #4441
Opened 2020-11-11 19:48 UTC by pishifat

waiting on a few more medals

2020-11-12 01:34 UTC, peppy submitted a review, later dismissed

2020-11-12 04:46 UTC, Nivalyx commented on news/2020-11-12-featured-artist-beatmap-updates-from-the-mappers-guild.md
> +- **MIMI single (osu!)**: [MIMI - Nani mo Nai Youna](https://osu.ppy.sh/beatmapsets/1151466#osu/2403536) &
umm, this line is broken i think :(

2020-11-12 08:18 UTC, peppy submitted a review, later dismissed

2020-11-15 04:14 UTC, cl8n requested changes

2020-11-15 04:14 UTC, cl8n commented on news/2020-11-12-featured-artist-beatmap-updates-from-the-mappers-guild.md
> +For the **Metal pack (osu!taiko, osu!, osu!catch)** quest designed by **[Raiden](https://osu.ppy.sh/users/2239480)**, the mappers had to create and rank at least 8 mapsets from any of the following m
```suggestion
For the **Metal pack (osu!taiko, osu!, osu!catch)** quest designed by **[Raiden](https://osu.ppy.sh/users/2239480)**, the mappers had to create and rank at least 8 mapsets from any of the following metal artists: Aether Realm, BLANKFIELD, Imperial Circus Dead Decadence, Inferi, Loki, Native Construct, Nekrogoblikon, Rivers of Nihil, or UNDEAD CORPORATION.
```

2020-11-15 04:14 UTC, cl8n commented on news/2020-11-12-featured-artist-beatmap-updates-from-the-mappers-guild.md
> +This quest was completed by **[Raiden](https://osu.ppy.sh/users/2239480)**, **[Greenshell](https://osu.ppy.sh/users/8693851)**, **[SILENCE PLAYER](https://osu.ppy.sh/users/6381153)**, **[radar](https
all of the quest completed paragraphs are missing punctuation

2020-11-20 05:57 UTC, Ephemeralis approved these changes

2020-11-20 06:01 UTC, merged