[RU] Add disambiguation articles for Mod, NC, NM, and osu!
ppy/osu-wiki pull request #4474
Opened 2020-11-16 18:58 UTC by TicClick

2020-11-17 21:58 UTC, UristMcKobold requested changes

2020-11-17 21:58 UTC, UristMcKobold commented on wiki/Disambiguation/Mod/ru.md
> +- Модератор — человек, следящий за порядком в игре (например, [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) или [GMT](/wiki/People/The_Team/Global_Moderation_Team)).
Мне здесь построение фраз не нравится. Может означать: модератор, моддер, игровой модификатор. В родительном падеже звучало бы лучше. То есть, «может означать: модератора, моддера, игровой модификатор». Последнее в родительном падеже, конечно, не очень.

```suggestion
- Модератора — человека, следящего за порядком в игре (например, [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) или [GMT](/wiki/People/The_Team/Global_Moderation_Team)).
```

2020-11-17 21:58 UTC, UristMcKobold commented on wiki/Disambiguation/Mod/ru.md
> +- [Моддер](/wiki/Modding) — человек, дающий советы по улучшению карты.
```suggestion
- [Моддерf](/wiki/Modding) — человека, занимающегося критикой и исправлением карт.
```
Объяснение некритично, но поближе к оригиналу.

2020-11-17 21:58 UTC, UristMcKobold commented on wiki/Disambiguation/Mod/ru.md
> +- [Игровой модификатор](/wiki/Game_modifier) — механика osu!, влияющая на игровой процесс.
```suggestion
- [Игровой модификатор](/wiki/Game_modifier) — механика osu!, изменяющая игровой процесс.
```
Очень непонятно звучит «влияющая», можно поточнее выразиться.

2020-11-17 21:58 UTC, UristMcKobold commented on wiki/Disambiguation/NC/ru.md
> +- [Nightcore](/wiki/Game_modifier/Nightcore) — игровой мод (модификатор).
```suggestion
- [Nightcore](/wiki/Game_modifier/Nightcore) — игровой модификатор.
```
Зачем тут «мод (модификатор)»? Одно лучше уж оставить, предпочтительнее полный вариант.

2020-11-17 21:58 UTC, UristMcKobold commented on wiki/Disambiguation/NM/ru.md
> +- [Normal mod](/wiki/Modding/Normal_mod) (обыкновенный мод) — мод-пост, ни к чему не обязывающий его получателя.
```suggestion
- [Normal mod](/wiki/Modding/Normal_mod) (обыкновенный мод) — мод, ни к чему не обязывающий его получателя.
```
Устарело же, никаких постов больше нет.

2020-11-17 23:58 UTC, TicClick commented on wiki/Disambiguation/Mod/ru.md
> +- Модератор — человек, следящий за порядком в игре (например, [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) или [GMT](/wiki/People/The_Team/Global_Moderation_Team)).
я следую оформлению и построению фраз в русской Википедии, где каждый термин даётся в именительном падеже, чтобы не было разночтений, как если бы он был помещён в название страницы [(пример статьи-зонтика)](https://ru.wikipedia.org/wiki/Ключ).

 построение самой первой фразы, `**ASDF** может означать`, обсуждаемо, а вот перечисление я хочу оставить в покое

2020-11-18 00:05 UTC, TicClick commented on wiki/Disambiguation/NM/ru.md
> +- [Normal mod](/wiki/Modding/Normal_mod) (обыкновенный мод) — мод-пост, ни к чему не обязывающий его получателя.
будет «ехал мод через мод», ну и далее по тексту, но у меня есть вариант

2020-11-18 13:30 UTC, UristMcKobold submitted a review, later dismissed

2020-11-18 13:42 UTC, TicClick commented
(that was me fixing `Co-authored-by:` marker, as per https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line)

2020-11-18 14:06 UTC, WalterToro approved these changes

2020-11-18 14:06 UTC, merged