[TH] Add Beatmap Nominators
ppy/osu-wiki pull request #4480
Opened 2020-11-17 09:55 UTC by Trigonoculus

- Translate Beatmap Nominators to Thai

User list *should* be up-to-date. Please verify just in case.

2020-11-17 10:11 UTC, C0NS03L requested changes
Beatmap nominators ทับไปเลยครับ ไม่ต้องแปล

2020-11-17 10:22 UTC, Trigonoculus commented
> Beatmap nominators ทับไปเลยครับ ไม่ต้องแปล

@C0NS03L updated, still probably some changes where we need to fix between "Beatmap Nominator" and "Beatmap Nominators"

2020-11-26 10:44 UTC, C0NS03L commented on wiki/People/The_Team/Beatmap_Nominators/th.md
> +*ดูสิ่งนี้ด้วย: [กฎของ Beatmap Nominators](Rules), [ความคาดหวังสำหรับ Beatmap Nominators](Expectations), [ข้อมูลทั่วไปสำหรับ Beatmap Nominators](General_Information), และ [การมาเป็น Beatmap Nominator
```suggestion
*ดูสิ่งนี้ด้วย: [กฎของ Beatmap Nominator](Rules), [ความคาดหวังสำหรับ Beatmap Nominators](Expectations), [ข้อมูลทั่วไปสำหรับ Beatmap Nominators](General_Information), และ [การมาเป็น Beatmap Nominator](Becoming_a_Beatmap_Nominator)*
```
From original article

2020-11-26 10:44 UTC, C0NS03L commented on wiki/People/The_Team/Beatmap_Nominators/th.md
> +สมาชิกของกลุ่ม Beatmap Nominators รับผิดชอบหลัก ๆ ในการ[วิจารณ์บีทแมพ](/wiki/Modding)ที่อยู่ในสถานะ [pending](/wiki/Beatmaps#work-in-progress-and-pending) และอนุมัติไปในการแรงค์ โดย Beatmap Nominator
```suggestion
สมาชิกของกลุ่ม Beatmap Nominators รับผิดชอบหลัก ๆ ในการ[วิจารณ์บีทแมพ](/wiki/Modding)ที่อยู่ในสถานะ [pending](/wiki/Beatmaps#work-in-progress-and-pending) และอนุมัติไปในการแรงค์ โดย Beatmap Nominators เป็นผู้คนที่สามารถถามได้เกี่ยวกับคำแนะนำ หรือคำขอต่าง ๆ เกี่ยวกับเรื่องใด ๆ ก็ได้ที่เกี่ยวกับการแมพหรือการวิจารณ์บีทแมพ Beatmap Nominator คนใดก็ได้สามารถยับยั้งการแรงค์บีทแมพ ([veto](Beatmap_Veto)) หากเขารู้สึกว่าแมพที่ถูกเสนอมีปัญหา หรือมีข้อกังวลที่ต้องถูกแก้ ที่ไม่ได้ละเมิดกฎการแรงค์แบบตรง ๆ
```

2020-11-26 10:44 UTC, C0NS03L commented on wiki/People/The_Team/Beatmap_Nominators/th.md
> +การภาคทัณฑ์ถูกใช้เพื่อการสังเกตการณ์ Beatmap Nominators ใหม่ หรือที่มีพฤติกรรมน่ากังวล อย่างใกล้ชิด โดยหน้าที่หลักของ Beatmap Nominators ภาคทัณฑ์คือการสร้างรากฐานในการเป็น Beatmap Nominators โดยการเส
```suggestion
การภาคทัณฑ์ถูกใช้เพื่อการสังเกตการณ์ Beatmap Nominators ใหม่ หรือที่มีพฤติกรรมน่ากังวล อย่างใกล้ชิด โดยหน้าที่หลักของ Beatmap Nominators ภาคทัณฑ์คือการสร้างรากฐานในการเป็น Beatmap Nominator โดยการเสนอบีทแมพ (อย่างเดียว) ในกระบวนการแรงค์ โดยในการเลื่อนขั้นบีทแมพ Beatmap Nominators เต็มรูปแบบต้องมีส่วนร่วมอย่างน้อยหนึ่งคน ดังนั้น Beatmap Nominators ภาคทัณฑ์จึงไม่สามารถเป็นคนสุดท้ายที่เสนอบีทแมพที่ได้รับการเสนอจาก Beatmap Nominators ภาคทัณฑ์คนอื่น สำหรับเกมโหมดนั้น ๆ
```

2020-11-30 06:50 UTC, C0NS03L approved these changes

2020-11-30 18:12 UTC, TPGPL approved these changes

2020-11-30 18:13 UTC, merged