[TH] Add Nomination Assessment Team
ppy/osu-wiki pull request #4492
Opened 2020-11-18 09:41 UTC by Trigonoculus

- Translate Nomination Assessment Team to Thai

All up-to-date.

2020-11-18 10:43 UTC, C0NS03L requested changes

2020-11-18 10:43 UTC, C0NS03L commented on wiki/People/The_Team/Nomination_Assessment_Team/th.md
> +สมาชิกของ NAT ถูกจำแนกโดยชื่อสีแดงของพวกเขา และตำแหน่งยศ เช่นเดียวกับ[ทีมผู้ดูแล](/wiki/People/The_Team/Global_Moderation_Team) พวกเขามีสิทธิ์ในการดูแลกรั่นกรองทั่วเว็บไซต์ และมีชื่อสีแดงเข้มในช่องแช
GMT ทับไปเลยครับ ไม่ต้องแปล

2020-11-19 11:10 UTC, C0NS03L commented on wiki/People/The_Team/Nomination_Assessment_Team/th.md
> +นอกเหนือจากความสามารถในการดูแลกรั่นกรองแล้ว NAT ยังมีความสามารถในการ[เสนอ](/wiki/Beatmap_ranking_procedure#nominations) [qualify](/wiki/Beatmap_ranking_procedure#qualification) และ[รีเซ็ตการเสนอ](/wi
```suggestion
นอกเหนือจากความสามารถในการดูแลกรั่นกรองแล้ว NAT ยังมีความสามารถในการ [เสนอ](/wiki/Beatmap_ranking_procedure#nominations) [qualify](/wiki/Beatmap_ranking_procedure#qualification) และ [รีเซ็ตการเสนอ](/wiki/Beatmap_ranking_procedure#nomination-resets) บนบีทแมพ ในบริเวณนี้พวกเขา ส่วนใหญ่ถูกถือว่าเหมือนกับ [BN เต็มรูปแบบ](/wiki/People/The_Team/Beatmap_Nominators#full-beatmap-nominators) และกฎทุกอย่างของ BN และความคาดหวัง (ยกเว้นกิจกรรม) ถูกใช้กับสมาชิก NAT เหมือนกัน โดยสมาชิก NAT ไม่ถูกคาดหวังให้เสนอแมพอย่างสม่ำเสมอเหมือน BN เนื่องจากมีความรับผิดชอบเพิ่มเติมในชุมชนแมปและวิจารณ์แมพ
```

2020-11-19 11:10 UTC, C0NS03L commented on wiki/People/The_Team/Nomination_Assessment_Team/th.md
> +สมาชิกของ NAT ที่ช่วยเหลือในหัวข้อย่อยการประเมิน มีความรับผิดชอบในการวิจารณ์แมปอย่างน้อย 3 บีทแมพในทุก ๆ เดือน ซึ่งรับรองว่า NAT มีความเท่าทันกับชุมชนการวิจารณ์แมปเวลาประเมิน Beatmap Nominators โดยสม
```suggestion
สมาชิกของ NAT ที่ช่วยเหลือในหัวข้อย่อยการประเมิน มีความรับผิดชอบในการวิจารณ์แมพอย่างน้อย 3 บีทแมพในทุก ๆ เดือน ซึ่งรับรองว่า NAT มีความเท่าทันกับชุมชนการวิจารณ์แมพเวลาประเมิน Beatmap Nominators โดยสมาชิกที่มีกิจกรรมการวิจารณ์แมพไม่ถึงเกณฑ์ที่กำหนดไว้ จะได้รับการเตือน และถ้าหากกิจกรรมของพวกเขาไม่ดีขึ้นในเดือนถัดไป เขาจะถูกปลดออกจาก NAT ทั้งนี้ สมาชิกของ NAT ที่ทำงานเกี่ยวกับโครงการอื่น ๆ ที่เกี่ยวกับการแมพ อาจจะได้รับการยกเว้นในข้อพิจารณานี้เป็นกรณี ๆ ไป
```

2020-11-19 11:10 UTC, C0NS03L commented on wiki/People/The_Team/Nomination_Assessment_Team/th.md
> +ก่อนเข้าร่วม NAT ผู้ใช้ต้องเป็นสมาชิก Beatmap Nominators เต็มรูปแบบ หรือเคยเป็นสมาชิก NAT มาก่อน และยังมีส่วนร่วมในชุมชน โดยผู้สมัคร NAT ส่วนใหญ่จะถูกพิจารณาเป็นอย่างแรกจากความมุ่งมั่นในการช่วยเหลือช
```suggestion
ก่อนเข้าร่วม NAT ผู้ใช้ต้องเป็นสมาชิก Beatmap Nominators เต็มรูปแบบ หรือเคยเป็นสมาชิก NAT มาก่อน และยังมีส่วนร่วมในชุมชน โดยผู้สมัคร NAT ส่วนใหญ่จะถูกพิจารณาเป็นอย่างแรกจากความมุ่งมั่นในการช่วยเหลือชุมชนการแมปและการวิจารณ์แมพ และการแสดงให้เห็นถึงความสามารถในการช่วยเหลือเกี่ยวกับทั้งสี่หัวข้อย่อยของ NAT ย่อมเป็นมูลฐานสำหรับการเลื่อนขั้น
```

2020-11-19 11:31 UTC, Trigonoculus commented on wiki/People/The_Team/Nomination_Assessment_Team/th.md
> +
Added

2020-11-26 10:31 UTC, C0NS03L approved these changes

2020-11-26 16:15 UTC, MegaApplePi approved these changes

2020-11-26 16:16 UTC, merged