[ES] Translation of "Contributor Covenant Code of Conduct" to spanish.
ppy/osu-wiki pull request #4499
Opened 2020-11-19 17:40 UTC by Panchosauriooo

2020-11-25 22:12 UTC, MagoSimon commented on wiki/Contributor_Code_of_Conduct/es.md
> +Este Código de Conducta es adapto de [Contributor Covenant][homepage], disponible en [https://www.contributor-covenant.org/version/2/0/code_of_conduct.html][v2.0].
Este Código de Conducta se adapto de [Contributor Covenant][homepage], disponible en [https://www.contributor-covenant.org/version/2/0/code_of_conduct.html][v2.0].

2020-12-12 14:45 UTC, TPGPL requested changes

2020-12-12 14:45 UTC, TPGPL commented on wiki/Rules/es.md
> +5. **Estamos en una comunidad para todas las edades.** Esto significa que todo contenido para mayores de 18 años (18+) o inapropiado para espacios públicos (NSFW) como uso de drogas o tópicos de cont
```suggestion
5. **Estamos en una comunidad para todas las edades.** Esto significa que todo contenido para mayores de 18 años (18+) o inapropiado para espacios públicos ([NSFW](https://es.wikipedia.org/wiki/NSFW)) como uso de drogas o tópicos de contenido sexual no son bienvenidos aquí.
```

2020-12-12 14:45 UTC, TPGPL commented on wiki/Rules/es.md
>  2. **Juega limpio.** Usar herramientas de terceros de cualquier tipo para obtener cualquier forma de ventaja no está bien. Esto incluye cosas como macros, programas de asistencia de puntería, modific
- Check if the article is fully up-to-date with the English version
   - If yes, delete the `outdated` mark at the beginning
- Link at line 22 to `Reporting Bad Behaviour` is missing
- `Reglas de Envio de Beatmaps` header is outdated
- Link at line 68 is missing (the whole header might be outdated?)

2020-12-12 14:45 UTC, TPGPL commented on wiki/Contributor_Code_of_Conduct/es.md
> +Las Directrices del Impacto en la Comunidad fueron inspiradas por [Mozilla's code of conduct enforcement ladder][Mozilla CoC].
"Mozilla's code of conduct enforcement ladder" should be possible to translate

2020-12-12 14:45 UTC, TPGPL commented on wiki/Reporting_Bad_Behaviour/Abuse/es.md
> +Lo investigaremos tan pronto como podamos.
one header is missing

```md
## Someone I know is being abused by a member of the volunteer teams (NAT, GMT) but is too afraid to speak up!

Send an email to [abuse@ppy.sh](mailto:abuse@ppy.sh) containing everything you know with as much evidence as you can get.

If you don't have any evidence but only stories or rumors that you believe are substantial enough to act on, please send us an email anyway. We take complaints like this very seriously and will look deeply into every report.```

2020-12-30 15:08 UTC, TPGPL commented on wiki/Reporting_Bad_Behaviour/Abuse/es.md
> +Haz click en los tres puntos en la parte superior del tweet conteniendo el problema y haz click en 'Reportar Tweet'. Asegúrate de seguir los formularios y de leerlos cuidadosamente. Quizás también qu
```suggestion
Haz click en los tres puntos en la parte superior del tweet conteniendo el problema y haz click en 'Reportar Tweet'. Asegúrate de seguir los formularios y de leerlos cuidadosamente. Quizás también quieras leer [La guía de Twitter acerca de cómo reportar comportamiento abusivo](https://help.twitter.com/es/safety-and-security/report-abusive-behavior) para más información acerca del proceso.
```

2020-12-30 15:08 UTC, TPGPL commented on wiki/Reporting_Bad_Behaviour/Abuse/es.md
> +Después, puedes ya sea bloquear o silenciar al usuario en cuestión haciendo click en los tres puntos en la parte superior derecha del su tweet (si estas usando la página web o el cliente móvil). Cons
```suggestion
Después, puedes ya sea bloquear o silenciar al usuario en cuestión haciendo click en los tres puntos en la parte superior derecha del su tweet (si estas usando la página web o el cliente móvil). Consulta [La guía de Twitter acerca de cómo bloquear cuentas](https://help.twitter.com/es/using-twitter/blocking-and-unblocking-accounts) para más información.
```

2020-12-30 15:08 UTC, TPGPL commented on wiki/Reporting_Bad_Behaviour/Abuse/es.md
> +Send an email to [abuse@ppy.sh](mailto:abuse@ppy.sh) containing everything you know with as much evidence as you can get.
```suggestion
```

2020-12-30 15:16 UTC, TPGPL approved these changes

2020-12-30 15:16 UTC, merged