[PT-BR] Update People
ppy/osu-wiki pull request #4500
Opened 2020-11-19 18:19 UTC by Flantsune

Updated all country translations on changed articles.
Changes made to:
- Community Contributors
- Users with unique title: Updated missing information and users
- The Team: Updated missing information, new changes for NAT and GMT based on Conduct update [BN, GMT, NAT, Dev, ALM and Loved articles]

2020-11-21 04:09 UTC, pimpG commented on wiki/People/Community_Contributors/pt-br.md
> +[flag_CH]: /wiki/shared/flag/CH.gif "Suiça"
Suíça

2020-11-21 04:17 UTC, pimpG commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Os **Nomeadores de Beatmap** (***BN***) é um grupo no comando da [nomeação de beatmap](/wiki/Beatmap_ranking_procedure). Eles tem um nome roxo nos fórums e discussões de beatmap.
acho que "grupo responsável pela [nomeação de beatmaps]" seria mais apropriado.

2020-11-21 04:36 UTC, pimpG commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Em adição, todos os Nomeadores de Beatmap são esperados a aderir a um livre conjunto de ideais focados em volta do serviço para a comunidade maior em direcionar sua atenção a uma grande variedade de
o texto original é um pouco chato de interpretar, acredito que uma tradução literal não é o ideal aqui pois nosso jogo de palavras é diferente. que tal pegar mais opiniões sobre isso?

trocaria "comunidade maior" por algo tipo "ampla comunidade"
"em direcionar" o certo seria "ao direcionar"
"arte" acho que é um termo exagerado, acho que algo tipo "criação" seria mais apropriado

2020-11-21 04:45 UTC, Flantsune commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Em adição, todos os Nomeadores de Beatmap são esperados a aderir a um livre conjunto de ideais focados em volta do serviço para a comunidade maior em direcionar sua atenção a uma grande variedade de
Tive bastante problema em achar algo para 'comunidade maior', ampla comunidade é bem melhor mesmo.
Que tal 'melhorar suas criações' no plural então? E adicionarei "assim _como_ mencionado" antes da menção do link.

2020-11-21 04:49 UTC, pimpG commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +- Em 22 de Agosto, 2014, os BAT deixaram de ser considerados como membros da equipe. Isso fez-se com que perdessem sua habilidade de moderação dentro do jogo e seus nomes vermelhos dentro do jogo e n
"fez-se" acho que é melhor usar um termo mais conhecido, como "fez".

2020-11-21 04:53 UTC, pimpG commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Em adição, todos os Nomeadores de Beatmap são esperados a aderir a um livre conjunto de ideais focados em volta do serviço para a comunidade maior em direcionar sua atenção a uma grande variedade de
fica melhor sim, mas eu ainda acho que essa linha inteira deveria ser revisada por mais pessoas pela diferença entre as línguas etc.

2020-11-21 05:05 UTC, pimpG commented on wiki/People/The_Team/Project_Loved_Team/pt-br.md
> +- ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) criou a equipe de capitães original em Setembro 2017 junto do sistema de [Captain's Pick](/wiki/Beatmaps/History_of_Loved#captain's-pick-and-pro
gerenciou

2020-11-21 20:02 UTC, Flantsune commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Em adição, todos os Nomeadores de Beatmap são esperados a aderir a um livre conjunto de ideais focados em volta do serviço para a comunidade maior em direcionar sua atenção a uma grande variedade de
Antes que eu dê um commit, eu dei uma reformulada na interpretação e ainda contém a mesma ideia geral que o texto original quer passar. Que tal:
```suggestion
Além disso, é esperável de todos os Nomeadores de Beatmap a aderirem a um conjunto esparso de ideais focados no serviço para a comunidade como um todo ao direcionar sua atenção a uma ampla variedade de mapas e mappers, e se esforçando para continuamente melhorar suas criações, assim como mencionado no [Artigo de Expectativas dos Nomeadores de Beatmap](Expectations).
```

2020-11-21 20:38 UTC, pimpG commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Em adição, todos os Nomeadores de Beatmap são esperados a aderir a um livre conjunto de ideais focados em volta do serviço para a comunidade maior em direcionar sua atenção a uma grande variedade de
que tal "é esperado que todos" "vão aderir a um conjunto"

2020-11-21 20:43 UTC, Flantsune commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Em adição, todos os Nomeadores de Beatmap são esperados a aderir a um livre conjunto de ideais focados em volta do serviço para a comunidade maior em direcionar sua atenção a uma grande variedade de
`Além disso, todos os Nomeadores de Beatmap vão aderir a um conjunto esparso [...]` certo?
Simplificado, mas sinceramente melhor de se entender.

2020-11-21 20:55 UTC, pimpG commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Em adição, todos os Nomeadores de Beatmap são esperados a aderir a um livre conjunto de ideais focados em volta do serviço para a comunidade maior em direcionar sua atenção a uma grande variedade de
sim

2020-11-21 21:05 UTC, pimpG submitted a review, later dismissed

2020-11-22 02:20 UTC, TPGPL commented on wiki/People/The_Team/pt-br.md
> -no_native_review: true
missing WalterToro in the listing

2020-11-22 17:36 UTC, TPGPL requested changes

2020-11-22 17:36 UTC, TPGPL commented on wiki/People/The_Team/Developers/pt-br.md
> +### Contas de bot
should remove no native review mark

2020-11-22 17:36 UTC, TPGPL commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +Membros dos Nomeadores de Beatmap são divididos em dois grupos: membros fixos e membros em teste.
missing link at L25

2020-11-23 22:09 UTC, TPGPL approved these changes

2020-11-23 22:09 UTC, merged