[RU] BanchoBot translation update
ppy/osu-wiki pull request #4509
Opened 2020-11-21 13:12 UTC by Styml

2020-11-21 19:52 UTC, TicClick requested changes

2020-11-21 19:52 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +`!stats` показывает краткую статистику пользователя и его текущий статус. Работает она по тому игровому режиму, в который указанный пользователь играл в последний раз, но при этом BanchoBot не сообща
менее громоздкие конструкции
```suggestion
`!stats` показывает краткую статистику игрока и его текущий статус. Статистика будет показана для последнего режима, в который играл пользователь, но название самого режима BanchoBot не сообщает. Если пользователь еще ни разу не играл в osu!, то BanchoBot выведет `User not found` (`Пользователь не найден`), даже если игрок с таким ником существует. Пример:
```

2020-11-21 19:52 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +Команда `!stats` может отобразить один из семи статусов: Editing (Редактирует), Idle (Не занят), Lobby (Ищет лобби), Modding (Делает мод), Multiplayer(В лобби), Multiplaying(Играет в лобби) и Playing
различие в форматировании с оригиналом, но так лучше и нагляднее читается
```suggestion
Команда `!stats` показывает один из семи статусов игрока:
- `Editing` — редактирование карты;
- `Idle` — бездействие;
- `Lobby` — поиск лобби (комнаты для мультиплеера);
- `Modding` — просмотр чужой карты в редакторе;
- `Multiplayer` — игрок находится в лобби;
- `Multiplaying` — игра в мультиплеере;
- `Playing` — игра в одиночном режиме.

Пример вызова команды для пользователя, играющего прямо сейчас:
```

2020-11-21 19:54 UTC, ryuu commented on wiki/BanchoBot/ru.md
> +`!stats` показывает краткую статистику пользователя и его текущий статус. Работает она по тому игровому режиму, в который указанный пользователь играл в последний раз, но при этом BanchoBot не сообща
показывает краткую **статистику** игрока и его текущий статус. **Статистика**...
я думаю, что можно заменить второе на "она", не?

2020-11-21 20:23 UTC, TicClick commented on wiki/BanchoBot/ru.md
> +`!stats` показывает краткую статистику пользователя и его текущий статус. Работает она по тому игровому режиму, в который указанный пользователь играл в последний раз, но при этом BanchoBot не сообща
да, обновил, спасибо

2020-11-23 10:05 UTC, TicClick requested changes
помимо этого,
- нужно поставить оригинальные названия категорий (Pending/Ranked/...);
- Project Loved, как и Loved, нужно тоже оставить без перевода по всей статье (включая заголовок), кроме начала. там стоит дать перевод и, наверное, транскрипцию один раз: https://github.com/ppy/osu-wiki/blob/master/wiki/Article_Styling_Criteria/ru.md#%D1%83%D1%81%D1%82%D0%BE%D0%B9%D1%87%D0%B8%D0%B2%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D0%B8

2020-11-23 10:05 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +Не существует строгих правил, которые определяют, какие карты капитан должен номинировать для категории «Любимые», но обычно номинированные карты хорошо известны и очень ценятся сообществом (как след
попытался переписать предложение хоть как-нибудь
```suggestion
Строгих правил и критериев нет, но обычно номинированные карты хорошо известны и ценятся сообществом, что следует из названия категории. Кроме того, шанс попадания в Loved повышается, если мапсет давно существует или содержит оригинально замапанные сложности высокого качества.
```

2020-11-24 01:08 UTC, TicClick requested changes
вот ещё порция, дело близится к концу

2020-11-24 01:08 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +- Создатель карты не против того, чтобы его карта попала в категорию «Loved».
```suggestion
- Она не находится в категориях [Qualified](/wiki/Beatmaps#qualified), [Ranked](/wiki/Beatmaps#ranked) или [Approved](/wiki/Beatmaps#approved).
- Создатель карты согласен с тем, чтобы его карта попала в категорию Loved.
```

2020-11-24 01:08 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +## Продвижение карты в «Loved»
здесь и далее: кавычки вокруг слов, написанных латиницей, не ставятся
```suggestion
## Продвижение карты в Loved
```

2020-11-24 01:08 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +Карты получают статус «Loved» путём номинирования и голосования.
```suggestion
Карты получают статус Loved путём номинирования и голосования.
```

2020-11-24 01:08 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +Карта, которую номинируют на добавление в «Loved», должна соответствовать перечисленным требованиям:
```suggestion
Карта, которую номинируют на добавление в Loved, должна соответствовать перечисленным требованиям:
```

2020-11-24 01:08 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +Несмотря на то, что почти все карты из категории ["Ожидающие"](/wiki/Beatmaps#ожидающие) соответствуют этим критериям, из-за более строгих требований к номинации не все попадают в категорию «Loved».
```suggestion
Несмотря на то, что почти все карты из категории [Pending](/wiki/Beatmaps#pending) соответствуют этим критериям, из-за более строгих требований к номинации далеко не все из них попадают в категорию Loved.
```

2020-11-24 01:08 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +Карты, входящие в категорию «Loved» также должны соответствовать нескольким наборам правил:
```suggestion
Карты, входящие в категорию Loved, также должны соответствовать нескольким наборам правил:
```

2020-11-24 01:08 UTC, TicClick commented on wiki/Project_Loved/ru.md
> +- [Правила содержимого песни](/wiki/Rules/Song_Content_Rules),
> правила содержимого песни

можно оставить так, пока лучший вариант не найдётся. @GoodbyeShin когда-то обещал подогнать перевод, может, у него есть идеи

2020-11-24 07:57 UTC, Styml commented on wiki/Project_Loved/ru.md
> +Затем номинированые карты будут выложены на [форумe Project Loved](https://osu.ppy.sh/community/forums/120), где участники сообщества могут проголосовать, хотят ли они видеть карту в категории «Loved
```suggestion
После сбора заявок номинированные карты будут выложены на [форумe Project Loved](https://osu.ppy.sh/community/forums/120), где остальные игроки смогут проголосовать, хотят ли они видеть карту в категории Loved. Карты, достигшие определенного процента голосов «за» к концу голосования, будут перемещены в категорию Loved.
```

2020-11-25 01:37 UTC, TicClick commented on wiki/Project_Loved/ru.md
>  ### Приемлемость
```suggestion
### Требования
```

2020-11-25 01:38 UTC, TicClick approved these changes

2020-11-25 01:38 UTC, merged