[RU] [EN] Update Modding, Beatmap Ranking Procedure and add its translation
ppy/osu-wiki pull request #4518
Opened 2020-11-23 15:31 UTC by Shmiklak

2020-11-26 23:41 UTC, TicClick requested changes
нужно много переписывать

2020-11-26 23:41 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Представители BN и NAT иногда накладывают [вето](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto) на карты, которые по их мнению имеют серьезные проблемы с качеством, но они никак не связаны с
```suggestion
Номинации сбрасываются при обновлении карты её создателем, или когда номинатор или NAT находят там проблему. Номинации также могут быть сброшены [глобальными модераторами](/wiki/People/The_Team/Global_Moderation_Team), если в карте присутствует что-то неприемлемое (например, сомнительный фон или текст песни). Если в момент сброса мапсет находился в категории Qualified, он будет дисквалифицирован и убран из очереди ранкинга.

Номинаторы и члены NAT иногда накладывают [вето](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto) на карты, которые они считают недостаточно качественными, но при этом не нарушающими критерии ранкинга.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Рейтинговые карты могут быть анранкнуты только лишь в исключительных случаях, когда проблемы были найдены сразу, после завершения процесса ранкинга.
```suggestion
## Ranked

Карты, успешно прошедшие через стадию квалификации и очередь ранкинга, попадают в категорию Ranked. В этот момент они получают таблицу рекордов и начинают влиять на статистику игроков.

Такие карты убираются из Ranked только в редких случаях — когда проблемы были найдены вскоре после ранкинга.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +**Моддинг** процесс проверки чьих-либо [карт](/wiki/Beatmaps) с целью ее улучшения. Пользователя, который пишет мод называют *моддером* и совокупность их постов на странице обсуждения карты *модом*.
```suggestion
**Моддинг** — процесс проверки чьих-либо [карт](/wiki/Beatmaps) с целью их улучшения. Пользователя, который пишет мод, называют *моддером*, а его посты на странице обсуждения карты — *модом*.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Моды чаще всего пишут для того, чтобы улучшить качество карт, нацеленных на получение [статуса рейтинговой](/wiki/Beatmaps#рейтинговые). Так как моддинг довольно детальный процесс и требует длительно
```suggestion
Чаще всего моды пишут для повышения качества карты, идущей в категорию [Ranked](/wiki/Beatmaps#ranked). Так как моддинг — довольно тщательный процесс, требующий долгого анализа карты, пользователи часто занимаются им, чтобы лучше понимать маппинг.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Существуют тоны способов найти карты для моддинга, вот некоторые из самых популярных:
```suggestion
Существует много способов найти карты для моддинга. Вот некоторые из них:
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +- [Форум моддинг очередей](https://osu.ppy.sh/community/forums/60) является самой активной платформой для поиска карт для моддинга, а также получения модов на свои работы. Пользователь может создать
```suggestion
- [Modding Queues](https://osu.ppy.sh/community/forums/60) (форум для очередей моддинга) — первое место, куда идут в поиске карт для моддинга, а также для получения модов. В этом форуме можно создать тему, которая будет работать как очередь: другие люди будут оставлять в ней ссылки на карты, для которых они хотят получить моды.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +  Владелец каждой очереди может иметь свои собственные правила по тому, какие карты и при каких условиях получат его мод. Очереди обычно открыты для двух видов модов:
```suggestion
  У каждой очереди свои условия для моддинга. Обычно предлагаются два вида модов:
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +  - **Mod for mod (M4M):** В таких случаях моддер просит маппера также написать ему мод, оказывая услугу за услугу.
```suggestion
  - **Normal mod (NM):** обыкновенный мод, не требующий от маппера никаких действий в отношении владельца очереди.
  - **Mod for mod (M4M):** мод, для получения которого нужно написать ответный мод на чью-нибудь карту (обговаривается заранее).
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +- Известные моддеры часто указывают на то, принимают ли они просьбы на моддинг или нет, в их профилях.
```suggestion
- Известные моддеры часто пишут, принимают они просьбы о моддинге или нет, в своих профилях.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +- Поиск карт с помощью библиотеки карт **не** рекомендуется, так как большинство загруженных карт не расчитаны на получение Ранкеда, из-за чего их создатели вряд-ли ответят на ваш мод.
вот тут в оригинале тоже логическая ошибка, которую нужно исправить (убрать пункт из списка): перечисляются способы поиска карт для моддинга, а не то, что не рекомендуется делать.
```suggestion

Просто так искать карты для моддинга в категории [Pending](/wiki/Beatmaps#pending] **не** рекомендуется: авторы большинства из них не планируют их ранкать, и ваш мод вряд ли будет применён.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Чтобы начать писать мод, загрузите самую последнюю версию карты и откройте ее [страницу с обсуждением](/wiki/Beatmap_Discussion). Сыграйте [сложность](/wiki/Difficulties), для которой вы хотите напис
```suggestion
Загрузите самую последнюю версию карты и откройте её [страницу с обсуждением](/wiki/Beatmap_Discussion). Сыграйте [сложность](/wiki/Difficulties), для которой вы хотите написать мод, отмечая про себя найденные проблемы и недочёты. После этого откройте карту в редакторе и просмотрите её на наличие других проблем.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Когда вы обнаружили проблему, выберите связанные с ней объекты в редакторе, а затем скопируйте их временной код как текст используя горячие клавиши (`Ctrl` + `C`). На странице обсуждения карты, встав
```suggestion
Когда вы обнаружили проблему, выделите связанные с ней объекты в редакторе, а затем скопируйте их таймкод, нажав `Ctrl` + `C`. Вставьте этот таймкод на странице обсуждения карты в одну из вкладок, нажав `Ctrl` + `V`, и напишите после него свои мысли и идеи. Если замечание связано с конкретными частями сложности, оставьте его на вкладке `Timeline`, если с обширными участками или всей сложностью в целом — на вкладке `General (This difficulty)`, а для всего, что применимо ко всем сложностям в карте, используйте вкладку `General (All difficulties)`. 
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Все посты в моде должны явно показывать что проблема, почему это проблема и как ее исправить. Прочитайте [Нормы поведения в моддинге и маппинге](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping#ma
```suggestion
Все моды должны явно указывать, что именно является недостатком, почему это — недостаток, и как его исправить. Более подробно о том, как оформлять мод-посты, написано в статье «[Нормы поведения в моддинге и маппинге](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping#making-a-mod-post)».
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Мапперы регулярно дают [кудосу](/wiki/Glossary#kudosu!) мод постам, которые они посчитали полезными нажимая на *палец вверх* справа от поста. Количество кудосу сохраняется в профилях моддеров и их ко
```suggestion
Если маппер посчитал мод полезным, он может выдать его автору [кудосу](/wiki/Glossary#kudosu!), нажав на *большой палец вверх* справа от поста. Число полезных модов показано в профиле каждого игрока на вкладке `modding`; оно учитывается в случае подачи заявки в группу [номинаторов](/wiki/People/The_Team/Beatmap_Nominators).
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Цель каждой `Проблемы` или `Предложения` в обсуждении карты объяснить что-либо относительно карты в контексте ее дизайна.
```suggestion
Моды бывают двух видов: `Problem` (ошибка, которую нужно исправить) и `Suggestion` (то, что можно улучшить). В зависимости от сути замечания в адрес карты, можно использовать тот или иной вид. 
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Многие мод посты показывают ошибки в карте. Например, пропущенный звук хлопка, который должен был быть там учитывая логику расстановки хитсаундов в карте, скорее всего ошибка.
```suggestion
Многие мод-посты указывают на ошибки в карте. Например, пропущенный звук хлопка, который должен быть на ноте, если следовать логике расстановки хитсаундов в карте, скорее всего, является ошибкой.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Предложение других путей, чтобы замапать какой-то кусок карты, также распространенный тип мод постов. В то время как часть карты может быть приемлемой, моддер может объяснить как ее улучшить изменив
```suggestion
Другой распространённый тип мод-поста — предложение. Участок карты может не иметь ошибок, но при этом её можно сделать ещё лучше. В этом случае моддер поможет раскрыть потециал карты, указав, как переделать такой участок.
```

2020-11-26 23:41 UTC, TicClick commented on wiki/Modding/ru.md
> +Карты, которые созданы для ранкеда, обязаны следовать [критериям ранкинга](/wiki/Ranking_Criteria). Моды часто упоминают проблемы, вытекающие из этих критериев.
```suggestion
Кроме того, часть модов посвящена [критериям ранкинга](/wiki/Ranking_Criteria), которым должны следовать все карты, идущие на ранкинг. Данные моды также помечаются как указания на ошибки.
```

2020-12-03 17:10 UTC, Shmiklak commented on wiki/Beatmap_ranking_procedure/ru.md
> +[Карты](/wiki/Beatmaps) могут быть представлены большой части сообщества с помощью полного прохождения процедуры ранкинга и попадением в [Рейтинговые](/wiki/Beatmaps#ranked).
подправил

2020-12-03 17:10 UTC, Shmiklak commented on wiki/Beatmap_ranking_procedure/ru.md
> +## Отзывы
и это тоже

2020-12-03 17:10 UTC, Shmiklak commented on wiki/Beatmap_ranking_procedure/ru.md
> +Создатель карты может отметить свою работу как `В разработке` или `Ожидающая`. Карты в обеих категориях предназначены для получения отзывов и мнений от сообщества игры.
да

2020-12-05 22:20 UTC, TicClick requested changes

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +[Карты](/wiki/Beatmaps) могут быть представлены большой части сообщества с помощью полного прохождения процедуры ранкинга и попадением в [Ranked](/wiki/Beatmaps#ranked).
мне кажется, тут нужно раскрыть мысль (и переписать странную формулировку про попадение)
```suggestion
[Карты](/wiki/Beatmaps) в osu! можно сделать более популярными и известными сообществу, если ранкнуть их — выполнить ряд действий, после которых карта может попасть в специальную категорию [Ranked](/wiki/Beatmaps#ranked) и получить таблицу рекордов.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Создатель карты может пометить свою работу как `WIP (в разработке)` или `Pending (готова для ранка)`. Карты в обеих категориях предназначены для получения отзывов и мнений от сообщества игры.
ну вот нет, карты предназначены для игры, а не для всего этого
```suggestion
Маппер может пометить свою карту как `WIP` (в разработке) или `Pending` (готова для ранка). Подразумевается, что другие мапперы и игроки будут комментировать, тестировать и модить карты, находящиеся в этих двух категориях.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Картам мапперов-новичков зачастую необходим тщательный моддинг для соответствия стандартам качества ранкнутых карт. В отдельных случаях такие работы переделываются целиком.
```suggestion
Картам мапперов-новичков зачастую необходим тщательный моддинг для соответствия определённым стандартам качества. В отдельных случаях такие карты переделываются целиком.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +[Номинаторы](/wiki/People/The_Team/Beatmap_Nominators), или *БНы* (от англ. *BN*) — это опытные моддеры, имеющие возможность номинировать чужие карты на ранк. Их задача — убедиться, что карта соответ
```suggestion
[Номинаторы](/wiki/People/The_Team/Beatmap_Nominators) (также *БНы* или *BN*, от англ. *beatmap nominator*) — это опытные моддеры, имеющие возможность номинировать чужие карты на ранк. Их задача — убедиться, что карта соответствует [критериям ранкинга](/wiki/Ranking_Criteria), а также их личным стандартам качества.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Хотя рекомендуется получить несколько модов от обычных пользователей, прежде чем просить у их номинаторов, единственным обязательным условием для номинации является наличие 5 хайпов.
```suggestion
Несмотря на то, что перед отправкой карты номинатору рекомендуется получить несколько модов от обычных пользователей, единственным обязательным условием для номинации является наличие 5 хайпов.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Категория Qualified существует для выявления в карте недочётов, не замеченных моддерами и номинаторами: чем больше людей её сыграют, тем выше шанс нахождения ошибок. Замечания, связанные с картой, мо
```suggestion
Категория Qualified существует для выявления в карте недочётов, не замеченных моддерами и номинаторами: чем больше людей её сыграют, тем выше шанс нахождения ошибок. Замечания, связанные с картой, можно сообщить номинаторам и NAT через страницу обсуждения карты. В отличие от карт категории Pending, карты в Qualified не могут быть обновлены их создателями, поэтому все замечания могут быть исправлены лишь после [сброса номинации](#сброс-номинации).
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Сброс номинаций помогает моддерам, номинаторам и NAT проверять самую последнюю версию карты до того, как она попадёт в очередь ранкинга.
```suggestion
С помощью сброса номинаций гарантируется, что моддеры, номинаторы и NAT проверяют самую лучшую и последнюю версию карты до того, как она попадёт в очередь ранкинга. 
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Modding/ru.md
> +Чаще всего моды пишут для повышения качества карты, идущей в категорию [Ranked](/wiki/Beatmaps#ranked). Так как моддинг — довольно тщательный процесс, требующий долгого анализа карты, пользователи ча
```suggestion
Чаще всего моды пишут для повышения качества карты, идущей в категорию [Ranked](/wiki/Beatmaps#ranked). Так как моддинг — довольно тщательный процесс, требующий долгого анализа карты, пользователи часто модят, чтобы лучше понимать маппинг.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Modding/ru.md
> +- [Modding Queues](https://osu.ppy.sh/community/forums/60) (форум для очередей моддинга) — первое место, куда идут в поиске карт для моддинга, а также для получения модов. В этом форуме можно создать
```suggestion
- [Modding Queues](https://osu.ppy.sh/community/forums/60) (очереди моддинга) — первое место, куда идут за картами для моддинга, а также для получения модов. В этом форуме можно создать тему, которая будет работать как очередь: другие люди будут оставлять в ней ссылки на карты, на которые они хотят получить моды.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Modding/ru.md
> +Просто так искать карты для моддинга в категории [Pending](/wiki/Beatmaps#Ожидающие) **не** рекомендуется: авторы большинства из них не планируют их ранкать, и ваш мод вряд ли будет применён.
```suggestion
Просто так искать карты для моддинга в категории [Pending](/wiki/Beatmaps#pending) **не** рекомендуется: авторы большинства из них не планируют их ранкать, и ваш мод вряд ли будет применён.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Modding/ru.md
> +Загрузите самую последнюю версию карты и откройте её [страницу с обсуждением](/wiki/Beatmap_Discussion). Сыграйте [сложность](/wiki/Difficulties), для которой вы хотите написать мод, отмечая про себя
```suggestion
Загрузите самую последнюю версию карты и откройте [страницу с её обсуждением](/wiki/Beatmap_Discussion). Сыграйте [сложность](/wiki/Difficulties), для которой вы хотите написать мод, отмечая про себя найденные проблемы и недочёты. После этого откройте карту в редакторе и проверьте её на наличие других проблем.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Modding/ru.md
> +Когда вы обнаружили проблему, выделите связанные с ней объекты в редакторе, а затем скопируйте их таймкод, нажав `Ctrl` + `C`. Вставьте этот таймкод на странице обсуждения карты в одну из вкладок, на
```suggestion
Если вы обнаружили проблему, выделите в редакторе относящиеся к ней объекты, а затем скопируйте их таймкод, нажав `Ctrl` + `C`. Вставьте этот таймкод на странице обсуждения карты в одну из вкладок, нажав `Ctrl` + `V`, и напишите после него свои мысли и идеи. Если замечание связано с конкретными частями сложности, оставьте его на вкладке `Timeline`, если с обширными участками или всей сложностью в целом — на вкладке `General (This difficulty)`, а для вещей, применимых ко всем сложностям в карте, используйте вкладку `General (All difficulties)`. 
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Modding/ru.md
> +Другой распространённый тип мод-поста — предложение. Участок карты может не иметь ошибок, но при этом её можно сделать ещё лучше. В этом случае моддер поможет раскрыть потециал карты, указав, как пер
```suggestion
Другой распространённый тип мод-поста — предложение. Участок карты может не иметь ошибок, но при этом его можно улучшить. В этом случае моддер поможет раскрыть потециал карты, указав, что и как переделать.
```

2020-12-05 22:20 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/ru.md
> +Карты, которые получили по две номинации в каждом игровом режиме, имеющемся в мапсете, перемещаются в категорию [Qualified](/wiki/Beatmaps#qualified). Такие карты имеют таблицу рекордов, но не дают [
```suggestion
Карты, которые получили по две номинации в каждом игровом режиме, имеющемся в мапсете, перемещаются в категорию [Qualified](/wiki/Beatmaps#qualified). Такие карты имеют таблицу рекордов, но не дают [очки производительности](/wiki/Performance_Points) за прохождение. После пребывания в Qualified в течение хотя бы 7 дней карта переместится в категорию [Ranked](#ranked), если в [очереди ранкинга](Ranking_queue) перед ней нет других карт.
```

2020-12-11 22:54 UTC, TicClick approved these changes
fine by me. marking as blocked since @UristMcKobold wanted to drop a review as well

2020-12-14 16:17 UTC, TicClick commented
or not. no need to hold it back

2020-12-14 16:19 UTC, merged