Update ru.md
ppy/osu-wiki pull request #4551
Opened 2020-12-01 22:52 UTC by ldtty

Bug fixes and minor adjustments

2020-12-01 23:21 UTC, UristMcKobold requested changes

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +6. **Соблюдайте чистоту в сообществе.**
```suggestion
6. **Ведите себя прилично.**
```
«Чистота в сообществе» звучит крайне странно, особенно в контексте этого пункта, слишком буквальный перевод.

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +osu! - это не место для свиданий или флирта. Использование сексуального языка, изображений или нежелательное заигрывание с другими членами сообщества на публике или в частном порядке-это **НЕ** норма
```suggestion
osu! — это не место для свиданий или флирта. Использование непристойных выражений и изображений или нежелательное заигрывание друг с другом на публике или тет-а-тет — это **НЕ** нормально. Если вы когда-нибудь начнёте чувствовать дискомфорт от разговора с кем-либо, [сообщите нам об этом конфиденциально](https://osu.ppy.sh/wiki/en/Reporting_Bad_Behaviour/Abuse), чтобы мы могли помочь вам (и, возможно, защитить других).
```
1) Сексуального языка? У меня при этих словах в голове только язык в плане мышца во рту.
2) Пробелы пропустил и тире некрасивое.
3) Частный порядок — что-то непонятное, впервые слышу такое выражение.
4) «Ненормально» слитно пишется, но тут ладно.
5) Переписал часть предложения, чтобы лучше звучало.

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +Притеснениям или другому антагонизму нет места в osu! сообществе.
```suggestion
Притеснениям и враждебному поведению не место в osu!.
```
Мне слово «антагонизм» не нравится жутко, крайне редко используется в русском языке, его мало кто поймёт.
«Сообщество» убрал, так как и так понятно, что имеется в виду сообщество, больше нигде нельзя себя так вести.
«Нет места» коряво звучит, как по мне.

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +Примечание: эти правила распространяются на все представленные карты, а не только на ранковые. Более подробные правила, касающиеся ранковых карт, см. в разделе [критерии ранкинга](https://osu.ppy.sh/
```suggestion
Примечание: эти правила распространяются на все карты, которые были загружены на сайт, а не только на ранкнутые. Для более подробных правил, относящихся именно к ранкнутым картам, обратитесь к разделу [критериев ранкинга](https://osu.ppy.sh/wiki/en/Ranking_Criteria).
```
Тут в терминах ошибся, так не говорят в ру-сообществе. Какое-то неуместное сокращение «смотрите», слишком книжно. Ну и чутка переворошил структуру.

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +Если вы не знаете, где взять бесплатный контент, загляните в нашу растущую библиотеку [Featured Artist](https://osu.ppy.sh/beatmaps/artists) для музыки, 100% лицензированной для osu! и [Правила испол
Прошлый вариант лучше смотрится. Надо ли было его вообще менять?

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +Если вы нарушите правила, то с вашим аккаунтом случится что-то плохое.
Масло масляное. В шапке уже написано про то, «что случится, если я нарушу правила», зачем повторяться?
**Что случится, если я нарушу правила? С вашим аккаунтом случится что-то плохое.**
ПРОТИВ
**Что случится, если я нарушу правила? Если вы нарушите правила, то с вашим аккаунтом случится что-то плохое.**

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +В это плохое может входить следующее *(не ограничиывается только этим)*:
Тоже тут не вижу смысла в смене перевода. Ради чего? У тебя в итоге одна и та же мысль повторяется дважды. 
1) Может входить, то есть это неполный список.
2) Не ограничивывается только этим, то есть это неполный список.

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +Длительность сайленса и других нарушений **автоматически** увеличивается почти экспоненциально с каждым нарушением.
```suggestion
Длительность сайленса и других нарушений **автоматически** увеличивается в два раза после каждого нарушения.
```
Идея хорошая, но мы люди простые, таких сложных слов не знаем. Собственно, возникает вопрос: а нужно ли было менять перевод?

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +Определенные правонарушения имеют минимальную продолжительность (обычно 48 часов или более), но если они достаточно серьезные, то срок блокировки будет большим.
Лишняя строчка, там следующая переводит то же самое.

2020-12-01 23:21 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +Если после нескольких нарушений вы продолжите нарушать правила, ваша учетная запись может быть навсегда и безвозвратно заблокирована.
То же самое, лишняя строчка.

2020-12-02 15:07 UTC, ldtty commented on wiki/Rules/ru.md
> +Если вы нарушите правила, то с вашим аккаунтом случится что-то плохое.
Соглашусь, что звучит лучше, переводил оригинал почти дословно

2020-12-02 15:14 UTC, ldtty commented
> 
> 
> @ldtty прокликай resolve conversation в ревью там, где ты полностью согласен с замечаниями, и напиши комментарии там, где ты решил что-то оставить

Спасибл

2020-12-02 15:24 UTC, UristMcKobold requested changes

2020-12-02 15:24 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +osu! — это не место для свиданий или флирта. Использование непристойных выражений и изображений или нежелательное заигрывание друг с другом на публике или тет-а-тет — это **НЕ** нормально. Если вы ко
```suggestion
osu! — это не место для свиданий или флирта. Использование непристойных выражений и изображений или нежелательное заигрывание друг с другом на публике или тет-а-тет — это **НЕ** нормально. Если вы ощущаете дискомфорт от разговора с кем-либо, [сообщите нам об этом конфиденциально](https://osu.ppy.sh/wiki/en/Reporting_Bad_Behaviour/Abuse), чтобы мы могли помочь вам (и, возможно, защитить других).
```
Я тут поправил немного свой вариант, но не зафиксировалось, видимо.

2020-12-02 15:24 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +4. **Соблюдайте [правила содержания песен](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) и [рекомендации по визуальному содержанию](https://osu.ppy.sh/wiki/en/Rules/Visual_Content_Consideratio
```suggestion
4. **Соблюдайте [правила содержания песен](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) и [критерии визуального содержания](https://osu.ppy.sh/wiki/en/Rules/Visual_Content_Considerations)**
```
Переводить тут нужно так же, как переводили раньше, то есть как перевели заголовки самих статей, а то будет вечно непостоянство.
Первую статью не перевели, правда, поэтому можно так оставить.

2020-12-02 15:39 UTC, UristMcKobold requested changes

2020-12-02 15:39 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +4. **Соблюдайте [правила содержания песен](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) и [критерии визуального содержания содержанию](https://osu.ppy.sh/wiki/en/Rules/Visual_Content_Consider
```suggestion
4. **Соблюдайте [правила содержания песен](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) и [критерии визуального содержания](https://osu.ppy.sh/wiki/en/Rules/Visual_Content_Considerations)**
```
Опечатка.

2020-12-02 15:46 UTC, UristMcKobold requested changes

2020-12-02 15:46 UTC, UristMcKobold commented on wiki/Rules/ru.md
> +4. **Соблюдайте [правила содержания песен](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) и [критерии визуального содержания содержания](https://osu.ppy.sh/wiki/en/Rules/Visual_Content_Consider
```suggestion
4. **Соблюдайте [правила содержания песен](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) и [критерии визуального содержания](https://osu.ppy.sh/wiki/en/Rules/Visual_Content_Considerations)**
```
Нажми просто коммит саджестед (или как оно там называется?) рядом с моим комментарием, а то так и будут опечатки на опечатках.

2020-12-02 15:55 UTC, UristMcKobold approved these changes
Looks good.

2020-12-02 17:28 UTC, TicClick requested changes
когда всё исправишь, удали первые три строчки из начала статьи:
```
---
outdated: true
---
```

2020-12-02 17:28 UTC, TicClick commented on wiki/Rules/ru.md
> +Притеснениям и враждебному поведению не место в osu!.
лучше взять более естественный порядок слов
```suggestion
В osu! нет места притеснению и враждебному поведению.
```

2020-12-02 17:28 UTC, TicClick commented on wiki/Rules/ru.md
>  Существуют редкие исключения вроде чёрного юмора, но постарайтесь обойтись без них.
это нужно удалить как часть апдейта
```suggestion
```

2020-12-02 17:28 UTC, TicClick commented on wiki/Rules/ru.md
>  Это означает, что 18+ ([NSFW](https://ru.wikipedia.org/wiki/NSFW)) материалы здесь не приветствуются (например, обсуждения интимных вещей или наркотиков).
```suggestion
Это означает, что 18+ ([NSFW](https://ru.wikipedia.org/wiki/NSFW)) материалы здесь не приветствуются (например, обсуждение интимных вещей или наркотиков).
```

2020-12-02 17:28 UTC, TicClick commented on wiki/Rules/ru.md
> +osu! — это не место для свиданий или флирта. Использование непристойных выражений и изображений или нежелательное заигрывание друг с другом на публике или тет-а-тет — это **НЕ** нормально. Если вы ощ
в русском столько местоимений не нужно, они неявно включены в контекст
```suggestion
osu! — это не место для свиданий или флирта. Использование непристойных выражений и изображений или нежелательное заигрывание друг с другом на публике или тет-а-тет — это **НЕ** нормально. Если вы ощущаете дискомфорт во время общения с кем-либо, [сообщите об этом конфиденциально](/wiki/Reporting_Bad_Behaviour/Abuse), чтобы мы могли помочь (и, возможно, защитить других игроков).
```

2020-12-02 17:28 UTC, TicClick commented on wiki/Rules/ru.md
> +4. **Соблюдайте [правила содержания песен](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) и [критерии визуального содержания](https://osu.ppy.sh/wiki/en/Rules/Visual_Content_Considerations)**
точку теряешь, плюс линтер жалуется на полные ссылки
```suggestion
4. **Соблюдайте [правила содержания песен](/wiki/Rules/Song_Content_Rules) и [критерии визуального содержания](/wiki/Rules/Visual_Content_Considerations).**
```

2020-12-02 17:28 UTC, TicClick commented on wiki/Rules/ru.md
> +Длительность сайленса и других нарушений **автоматически** увеличивается в два раза после каждого нарушения.
сайленс — это не нарушение, а фразу можно упростить
```suggestion
Длительность сайленса и других ограничений **автоматически** удваивается после каждого нарушения.
```

2020-12-02 17:28 UTC, TicClick commented on wiki/Rules/ru.md
>  Если вы собираетесь ранкнуть карту, то она должна следовать более строгим правилам — [критериям ранкинга](/wiki/Ranking_Criteria).
курсив потерян, последнее предложение лишнее, плюс всё можно сильно упростить, чтобы легче читалось
```suggestion
*Примечание: эти пункты распространяются на **все загруженные карты**, включая не ранкнутые. На карты, идущие на ранк, дополнительно действуют [критерии ранкинга](/wiki/Ranking_Criteria).*

Эти правила применяются к картам, загруженным через [систему публикации карт](/wiki/Glossary#bss) — форумные темы и обсуждения для них создаются автоматически при публикации из [редактора](/wiki/Beatmap_Editor).
```

2020-12-02 18:50 UTC, TicClick approved these changes

2020-12-02 18:51 UTC, merged