[RU] Add Accuracy
ppy/osu-wiki pull request #4558
Opened 2020-12-03 07:36 UTC by Styml

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +Точность (*аккураси*, *акка*) – это процентное выражение способности игрока нажимать на [ноты](/wiki/Hit_object) вовремя. У игроков есть всего три точности: точность на карте, которая зависит от полу
усложнённое предложение, можно упростить своими словами
```suggestion
Точность (*аккураси*, *акка*) — это оценка того, насколько вовремя игрок нажимает на [ноты](/wiki/Hit_object). Она измеряется в процентах и бывает трёх видов:

1. Точность на конкретной сложности, которая зависит от полученных очков за нажатия.
2. Общая точность, которая складывается из всех рекордов (у каждого из них — свой вес в сумме, чтобы лучшие рекорды сильнее влияли на точность).
3. Точность по [очкам производительности (pp)](/wiki/Performance_Points), которая складывается из точности результатов, принёсших больше всего PP.
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +В osu!taiko точность рассчитывается как сумма точностей нот, разделенная на общее количество нот. Точность ноты может быть либо GREAT (良) (cчитается как 100%), GOOD (可) (cчитается как 50%), или MISS/
```suggestion
В osu!taiko точность рассчитывается как сумма точностей нот, делённая на их общее количество. Точность ноты может быть GREAT (良) (cчитается как 100%), GOOD (可) (cчитается как 50%), или MISS/BAD (不可) (считается как 0%, а также сбрасывает комбо). Слайдеры (drum roll) и спиннеры не влияют на точность.
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +В osu!catch точность рассчитывается как количество всех собранных объектов, разделенное на количество всех объектов (бананы при этом нигде не учитываются). Все объекты, кроме бананов имеют одинаковое
```suggestion
В osu!catch точность рассчитывается как количество собранных объектов, делённое на их общее количество (бананы при этом нигде не учитываются). Все объекты, кроме бананов, имеют одинаковое значение точности.
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +*Примечание для API пользователей: если вам нужно рассчитать точность в osu!catch, количество капелек объявлено как `count50`, а количество пропущенных капелек `countkatu`.*
```suggestion
*Примечание для пользователей API: если вам нужно рассчитать точность в osu!catch, общее количество дроплетов в ответе API названо `count50`, а количество пропущенных дроплетов — `countkatu`.*
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +*Примечание: Дополнительная информация может быть отображена только после того, как вы сыграли карту или посмотрели её реплей. После выхода со [страницы результатов](/wiki/results_screen) эту информа
исправь ссылку в оригинале тоже, пожалуйста, раз уж я заметил
```suggestion
График производительности показывает полосу здоровья игрока в течение игры. Если навести на него курсор, будет показана дополнительная информация.

*Примечание: эта информация будет показана только после того, как вы сыграли карту или посмотрели её реплей, и пропадёт, если уйти со [страницы результатов](/wiki/Interface#ranking-screen).*
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +В связи с тем, как реализованы моды [DT](/wiki/DT) (Double Time) и [HT](/wiki/HT) (Half Time), значения `Error` и `Unstable Rate` будут соответственно умножены на множитель мода. Чтобы получить истин
```suggestion
При наведении курсора на график всплывает окошко со значениями `Error` (отклонение) и `Unstable Rate` (разброс нажатий).

В связи с тем, как реализованы моды [DT](/wiki/DT) (Double Time) и [HT](/wiki/HT) (Half Time), значения `Error` и `Unstable Rate` будут умножены на коэффициент мода. Чтобы получить истинные значения при игре с DT, разделите их на 1.5. Аналогично, при игре с HT умножьте их на 1.33.
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +`Error` всегда показывает два значения, которые представляют собой насколько раньше и насколько позже вы в среднем нажимаете на ноты. Чем выше [Overall Difficulty](/wiki/Overall_Difficulty) карты, те
из-за формулировки получается, что, во-первых, это отклонения сами играют, а во-вторых, что сначала считается значение ошибки, а потом уже оно гарантирует (или не гарантирует) хорошую игру, хотя зависимость тут противоположная
```suggestion
#### Error (отклонение)

`Error` показывает два числа: среднее значение всех ранних и всех поздних ударов по нотам. Чем выше [Overall Difficulty](/wiki/Overall_Difficulty) карты, тем меньше вы должны отклоняться от идеальных нажатий, чтобы набрать высокую точность.
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +`Unstable Rate` отражает то, как стабильно вы нажимаете на ноты, и чем меньше это значение, тем лучше (лучшие игроки часто имеют значение ниже 100). Обратите внимание, что это отображает именно стаби
постарался прояснить
```suggestion
#### Unstable Rate (разброс нажатий)

`Unstable Rate` отражает то, как стабильно вы нажимаете на ноты, и чем ниже это значение, тем лучше (у игроков высокого ранга оно почти всегда меньше 100). Обратите внимание, что разброс нажатий показывает **не** точность, а насколько размеренно вы ударяете по нотам. Если вы всегда попадаете по ним очень поздно, но опаздываете примерно на одно и то же время, это число будет таким же низким, как при стабильных нажатиях вовремя. По сути, разброс нажатий — это их [стандартное отклонение](https://ru.wikipedia.org/wiki/Среднеквадратическое_отклонение "Wikipedia") в миллисекундах, умноженное на 10. С тем, как оно считается в стабильной версии osu!, можно ознакомиться с помощью [кода, выложенного peppy](https://gist.github.com/peppy/3a11cb58c856b6af7c1916422f668899).
```

2020-12-05 23:46 UTC, TicClick commented on wiki/Accuracy/ru.md
> +`Speed` представляет собой средний RPM (revolutions per minute - обороты в минуту) на всех спиннерах карты. `Max`  показывает самый высокий RPM, которого достиг игрок на карте.
```suggestion
### Spin

*Примечание: Spin отображается только для [osu!standard](/wiki/Game_mode/osu!).*

Вместе с информацией о точности можно посмотреть статистику по спиннерам.

#### Speed (скорость вращения)

`Speed` — это средняя скорость вращения, или RPM ([число оборотов в минуту](https://ru.wikipedia.org/wiki/Оборот_в_минуту "Wikipedia")) на всех спиннерах карты. Значение с припиской `Max`  показывает самую быструю скорость вращения, которогй достиг игрок на карте.
```

2020-12-05 23:47 UTC, TicClick requested changes
даже вот так

2020-12-06 07:16 UTC, Styml commented
idk how to name pull now... `[RU/EN] Add Accuracy & Update links?

2020-12-06 17:01 UTC, TicClick requested changes

2020-12-06 17:01 UTC, TicClick commented on wiki/Accuracy/ru.md
> +`Unstable Rate` отражает то, как стабильно вы нажимаете на ноты, и чем ниже это значение, тем лучше (у игроков высокого ранга оно почти всегда меньше 100). Обратите внимание, что разброс нажатий пока
```suggestion
`Unstable Rate` отражает то, как стабильно вы нажимаете на ноты, и чем ниже это значение, тем лучше (у игроков высокого ранга оно почти всегда меньше 100). Обратите внимание, что разброс нажатий показывает **не** точность, а насколько размеренно вы нажимаете на ноты. Если вы всегда попадаете по ним очень поздно, но опаздываете примерно на одно и то же время, это число будет таким же низким, как и при стабильных нажатиях вовремя. По сути, разброс нажатий — это их [стандартное отклонение](https://ru.wikipedia.org/wiki/Среднеквадратическое_отклонение "Wikipedia") в миллисекундах, умноженное на 10. С тем, как оно считается в стабильной версии osu!, можно ознакомиться с помощью [кода, выложенного peppy](https://gist.github.com/peppy/3a11cb58c856b6af7c1916422f668899).
```

2020-12-06 17:03 UTC, TicClick approved these changes

2020-12-06 17:03 UTC, merged