[ZH]Add visual settings translate
ppy/osu-wiki pull request #4583
Opened 2020-12-09 07:51 UTC by cdwcgt

complete and add a image

2020-12-09 07:58 UTC, cdwcgt reviewed
It seems that there is something wrong with the explanation here in the original English, but as it is a translation, it will work just as well

2020-12-09 07:58 UTC, cdwcgt commented on wiki/Visual_Settings/zh.md
> +*注意: 视觉设置的的更改会保存在每张谱面上，但是会在关闭osu!后还原设置。 请在[设置](/wiki/options)侧边栏中进行全局（和永久）设置*
这个关闭osu!后还原设置感觉是错误的，但是[原版](/ppy/osu-wiki/blob/master/wiki/Visual_Settings/en.md)是这样写的，我也就这样翻了（
```suggestion
*注意: 视觉设置的的更改会保存在每张谱面上。 请在[设置](/wiki/options)侧边栏中进行全局（和永久）设置*
```
实际我觉得应该是这样

2020-12-09 11:32 UTC, cdwcgt commented on wiki/Visual_Settings/zh.md
> +*注意: 视觉设置的的更改会保存在每张谱面上，但是会在关闭osu!后还原设置。 请在[设置](/wiki/options)侧边栏中进行全局（和永久）设置*
https://github.com/ppy/osu-wiki/pull/4585

2020-12-10 05:12 UTC, kj415j45 requested changes

2020-12-10 05:12 UTC, kj415j45 commented on wiki/Visual_Settings/zh.md
> +| `禁用故事板` | 如果存在故事板，将删除所有故事板元素。 这个选项不不会影响kiai效果和背景视频。 | 如果显示癫痫警告，推荐有癫痫问题的玩家启用这个选项。 如果这个谱面没有故事板，这个选项将被禁用。 |
```suggestion
| `禁用 Storyboard` | 如果存在故事板，将删除所有故事板元素。 这个选项不不会影响kiai效果和背景视频。 | 如果显示癫痫警告，推荐有癫痫问题的玩家启用这个选项。 如果这个谱面没有故事板，这个选项将被禁用。 |
```

2020-12-28 23:24 UTC, TPGPL commented on wiki/Visual_Settings/zh.md
> +| `禁用 Storyboard` | 如果存在故事板，将删除所有故事板元素。 这个选项不不会影响kiai效果和背景视频。 | 如果显示癫痫警告，推荐有癫痫问题的玩家启用这个选项。 如果这个谱面没有故事板，这个选项将被禁用。 |
missing Kiai time link, for reference:

```md
| `Disable storyboard` | Remove all storyboard elements. This does not affect [Kiai Time](/wiki/Kiai_time) and the background video, if any. | This is recommended for players with epilepsy issues for when the beatmap displays an epilepsy warning. This option is disabled if there is no storyboard to play. |
```

2020-12-29 17:25 UTC, TPGPL approved these changes

2020-12-29 17:26 UTC, merged