[KR] Add translation for some articles related to beatmapping
ppy/osu-wiki pull request #4593
Opened 2020-12-10 13:52 UTC by inix1257

Add korean translation for:
- Beatmap ranking procedure
- Modding
- osu! Ranking criteria
- Submission

2020-12-10 15:22 UTC, hikizisa commented
file name should be ko.md

2020-12-10 15:40 UTC, hikizisa requested changes
checked translation with some other people on discord chat and fixed things,
some were not fixed by mistake so left those as a comment

2020-12-10 15:40 UTC, hikizisa commented on wiki/Ranking_Criteria/osu!/ko.md
> +- **슬라이더 틱 히트사운드는 권장되지 않습니다.** 만약 사용하고 싶다면, 볼륨이 제대로 맞춰져 있는지 확인해보세요 (다른 히트사운드보다 너무 작은 경우 등). 너무 시끄러운 슬라이더 틱, 특히 한 번이나 두 번 정도밖에 쓰이지 않으면 듣기에 매우 불편할 수 있습니다.
> - **슬라이더 틱 히트사운드는 권장되지 않습니다.** 만약 사용하고 싶다면, 볼륨이 제대로 맞춰져 있는지 확인해보세요 (다른 히트사운드보다 너무 작은 경우 등). 너무 시끄러운 슬라이더 틱은, 특히 한 번이나 두 번 정도밖에 쓰이지 않으면 듣기에 매우 불편할 수 있습니다.

2020-12-10 15:40 UTC, hikizisa commented on wiki/Ranking_Criteria/osu!/ko.md
> +- **슬라이더 틱 히트사운드는 권장되지 않습니다.** 만약 사용하고 싶다면, 볼륨이 제대로 맞춰져 있는지 확인해보세요 (다른 히트사운드보다 너무 작은 경우 등). 너무 시끄러운 슬라이더 틱, 특히 한 번이나 두 번 정도밖에 쓰이지 않으면 듣기에 매우 불편할 수 있습니다.
> - **슬라이더 틱 히트사운드는 권장되지 않습니다.** 만약 사용하고 싶다면, 볼륨이 제대로 맞춰져 있는지 확인해보세요 (다른 히트사운드보다 너무 작은 경우 등). 너무 시끄러운 슬라이더 틱은, 특히 한 번이나 두 번 정도밖에 쓰이지 않으면 듣기에 매우 불편할 수 있습니다.

same thing

2020-12-12 07:05 UTC, hikizisa submitted a review, later dismissed

2020-12-28 21:36 UTC, TPGPL requested changes
looks fine otherwise

2020-12-28 21:36 UTC, TPGPL commented on wiki/Submission/ko.md
> +![](img/bss_warning.png "Beatmap Submission System screen")
image tooltip needs to be translated

2020-12-28 21:36 UTC, TPGPL commented on wiki/Submission/ko.md
> +![](img/bss_submitting.png "Beatmap Submission System uploading screen")
image tooltip needs to be translated

2020-12-29 00:01 UTC, inix1257 commented on wiki/Submission/ko.md
> +![](img/bss_warning.png "Beatmap Submission System screen")
fixed both

2020-12-29 00:05 UTC, TPGPL approved these changes

2020-12-29 00:05 UTC, merged