ua.md
ppy/osu-wiki pull request #4638
Opened 2020-12-16 19:13 UTC by GeraldAzgore

i make a ukrainian translate for "Project Loved"

2020-12-16 19:53 UTC, atimonder1 requested changes
Много ошибок, серьёзно :/

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Мапи отримують статус Loved шляхом номінування та голосування.
```suggestion
Карти отримують статус Loved шляхом номінування та голосування.
```
Думаю, лучше будет звучать, да и более красиво

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Члени команди Project Loved, названні **капітанами**, регулярно номінують мапи для різних ігрових режимів. Майже завжди ці карти пропонуються спільнотою osu!. Актуальні форми заявок та списки мап, вж
```suggestion
Члени команди Project Loved, названні **капітанами**, регулярно номінують мапи для різних ігрових режимів. Майже завжди ці карти пропонуються спільнотою osu!. Актуальні форми заявок та списки біткарт, котрі вже знаходяться в Loved, можна знайти по наступним посиланням:
```
?? Очевидные ошибки, как-будто машинный перевод

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +- [Список улюблених мап у osu!mania](https://docs.google.com/spreadsheets/d/1sjkTwUSvQ5Me-6rK61rToTg2bU-yX9X29CXdzttvhtM/edit).
```suggestion
- [Список улюблених карт у osu! и osu!catch](https://docs.google.com/spreadsheets/d/1HgHwtO3kIzT8R4ocEJMZTosADrGJRJOFL-TZI97tZS4/edit);
- [Список улюблених карт у osu!taiko](https://docs.google.com/spreadsheets/d/1Nk96z_xat_7ypsDF1sCTDO4i_CnHarcrCbGoTmgwHHE/edit);
- [Список улюблених карт у osu!mania](https://docs.google.com/spreadsheets/d/1sjkTwUSvQ5Me-6rK61rToTg2bU-yX9X29CXdzttvhtM/edit).
```
Личные придирки, но лучше звучит

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +*Примітка: якщо у вас обмежений доступ до Google Форм, ви можете зв'язатися з будь-яким членом [команди Project Loved](/wiki/People/The_Team/Project_Loved_Team#члены-команды), щоб мапу представили ві
```suggestion
*Примітка: якщо у вас обмежений доступ до Google Форм, ви можете зв'язатися з будь-яким членом [команди Project Loved](/wiki/People/The_Team/Project_Loved_Team#члены-команды), щоб мапу представили від вашого імені.*
```
Правила украинского языка

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Після сбору заявок номінованні мапи будуть викладені на [форумі Project Loved](https://osu.ppy.sh/community/forums/120), де інші гравці зможуть проголосувати, чи хотять вони бачити цю мапу у категорі
```suggestion
Після сбору заявок номінованні мапи будуть викладені на [форум Project Loved](https://osu.ppy.sh/community/forums/120), де інші гравці зможуть проголосувати за те, чи хочуть вони бачити цю мапу у категорії Loved. Карти, котрі досягли відповідного проценту голосів «за» до кінця голосування, будуть переміщенні до категорії Loved.
```
Исправлены некоторые ошибки

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Мапа, яку номинують на додавання у Loved, повинна відповідати переліченим вимогам:
```suggestion
Карта, яку номінують на додавання у Loved, повинна відповідати переліченим критеріям:
```
"Критеріям" будет лучше звучать, думаю, да и более красноречиво

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +- Творець мапи не заблокований або не має рестрикт.
```suggestion
- Творець мапи не заблокований, або не має ніяких [обмежень облікового запису](/wiki/uk/Help_Centre#restriction).
```
"Рестрикт" - нет такого слова, добавлена ссылка на вики, добавлена запятая

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +- Як минімум одна сложність може бути пройдена.
```suggestion
- Як мінімум одна складність може бути пройдена.
```
??

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Не дивлячись на те, що майже усі мапи з категорії [Pending](/wiki/Beatmaps#pending) відповідають цим крітеріям, из-за більш строгих вимог до номинації далеко не всі з них потрапляють у категорію Love
```suggestion
Не дивлячись на те, що майже усі мапи з категорії [Pending](/wiki/Beatmaps#pending) відповідають цим крітеріям, із-за більш строгих вимог до номінації далеко не всі з них потрапляють у категорію Loved.
```

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Мапи,які входять у категорію Loved, також повинні відповідати кільком наборам правил:
```suggestion
Карти, які входять у категорію Loved, також повинні відповідати кільком критеріям:
```

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +- [Розділ «Метаданні» у крітеріях ранкингу](/wiki/Ranking_Criteria#метаданные),
```suggestion
- [Розділ «Метаданні» у крітеріях ранкінгу](/wiki/uk/Ranking_Criteria#metadata),
```

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +- [Крітерії визуального вмісту](/wiki/Rules/Visual_Content_Considerations).
```suggestion
- [Критерії візуального вмісту](/wiki/Rules/Visual_Content_Considerations).
```

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Будь-які проблеми, зв'язанні з цими правилами, зазвичай вирышуються під час голосування.
```suggestion
Будь-які проблеми, зв'язанні з цими правилами, зазвичай вирішуються під час голосування.
```

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +### Приорітет номинації
```suggestion
### Приорітет номінації
```

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +Строгих правил та крітеріїв немає, але зазвичай номінованні мапи добре відомі та цінуються спільнотою, що слідує з назви категорії. Крім того, шанс потрапляння у Loved повищується, якщо мапсет існує
```suggestion
Строгих правил та крітеріїв немає, але зазвичай номіновані карти добре відомі та цінуються спільнотою, що слідує з назви категорії. Крім того, шанс потрапляння у Loved підвищується, якщо мапсет існує давно або вміщує оригінально замапанні складності високої якості.
```

2020-12-16 19:53 UTC, atimonder1 commented on wiki/Project_Loved/ru.md
> +## Додаткова Інформація
```suggestion
## Додаткова інформація
```

2020-12-16 20:01 UTC, GeraldAzgore commented
@TPGPL why "state:Blocked"?

2020-12-16 20:04 UTC, TPGPL commented
because you made changes to the Russian translation (`ru.md`) instead of making a new `ua.md` file; will remove the label after you apply the reviews above and I fix that problem on my end

2020-12-16 21:28 UTC, atimonder1 commented
> because you made changes to the Russian translation (`ru.md`) instead of making a new `ua.md` file; will remove the label after you apply the reviews above and I fix the problem on my end

*`uk.md`, since the Ukrainian locale is "uk", but not "ua"

2020-12-16 21:47 UTC, TPGPL commented
> > because you made changes to the Russian translation (`ru.md`) instead of making a new `ua.md` file; will remove the label after you apply the reviews above and I fix the problem on my end
> 
> *`uk.md`, since the Ukrainian locale is "uk", but not "ua"

oh right i forgot about that, thanks for correcting me out

2021-01-04 17:20 UTC, TicClick commented
the reviewer says the translation is okay now

2021-01-04 17:20 UTC, TicClick approved these changes

2021-01-04 17:21 UTC, merged

2021-01-05 21:22 UTC, atimonder1 commented
> the reviewer says the translation is okay now

I forgot - in the "load more" tab he did not accept my reviews, can you accept them, please?

2021-01-05 21:59 UTC, TicClick commented
> I forgot - in the "load more" tab he did not accept my reviews, can you accept them, please?

this pull request is now merged and inactive, so someone needs to make the edits and open a new one. that could be you, @GeraldAzgore, or me myself for not checking that the review is fully applied

2021-01-05 22:25 UTC, TicClick commented
> I forgot - in the "load more" tab he did not accept my reviews, can you accept them, please?

fixed in #4638