[ZH] Add Project Loved
ppy/osu-wiki pull request #4640
Opened 2020-12-17 09:52 UTC by cdwcgt

Add Project Loved Chinese translation

2020-12-21 13:32 UTC, kj415j45 requested changes

2020-12-21 13:32 UTC, kj415j45 commented on wiki/Project_Loved/zh.md
> +然而，尽管几乎所有的[Pending和Working-in-progress](/wiki/Beatmaps#work-in-progress-and-pending)地图都符合这些标准，但由于g更选择性的提名和投票要求，很少有地图被投票到受欢迎的类别中。
```suggestion
虽然几乎所有的[Pending和Working-in-progress](/wiki/Beatmaps#work-in-progress-and-pending)地图都符合这些标准，但出于更挑剔的提名条件与投票要求，只有少数谱面才能进入Loved。
```

2020-12-21 13:32 UTC, kj415j45 commented on wiki/Project_Loved/zh.md
> +谱面需要满足一些很小的规定以使它可以被Loved提名。队长认为谱面集需要符合以下条件:
```suggestion
谱面需要满足一些要求才能被提名为Loved，队长会考虑以下条件:
```

2020-12-21 13:32 UTC, kj415j45 commented on wiki/Project_Loved/zh.md
> +所有Project Loved的组织和计划都在[osu!dev Discord server](https://discord.gg/ppy)的`#osu-loved`频道。也有个位于[osu! Community Discord server](https://discord.gg/0Vxo9AsejDkGlk3H)的`#project-loved`频道。如果有任何问题、担忧或建议都可以到那里
```suggestion
所有Project Loved的组织和计划都在[osu!dev Discord server](https://discord.gg/ppy)的`#osu-loved`频道进行，此外还有一个位于[osu! Community Discord server](https://discord.gg/0Vxo9AsejDkGlk3H)的`#project-loved`频道。如果有任何疑虑或建议都可以到那里提出。
```

2020-12-22 02:19 UTC, cdwcgt commented on wiki/Project_Loved/zh.md
> +然而，尽管几乎所有的[Pending和Working-in-progress](/wiki/Beatmaps#work-in-progress-and-pending)地图都符合这些标准，但由于g更选择性的提名和投票要求，很少有地图被投票到受欢迎的类别中。
？这里竟然有个字母落了，一会就改

2020-12-22 02:46 UTC, cdwcgt commented on wiki/Project_Loved/zh.md
> +谱面需要满足一些很小的规定以使它可以被Loved提名。队长认为谱面集需要符合以下条件:
很小的规定是原文的说法，我觉得就算不用很小的也应该用点别的词修饰？

2020-12-22 05:30 UTC, kj415j45 commented on wiki/Project_Loved/zh.md
> +谱面需要满足一些很小的规定以使它可以被Loved提名。队长认为谱面集需要符合以下条件:
我认为 minimal 只是说“要求很低”，不应该翻译为“很小的”。

2020-12-22 07:14 UTC, cdwcgt commented on wiki/Project_Loved/zh.md
> +谱面需要满足一些很小的规定以使它可以被Loved提名。队长认为谱面集需要符合以下条件:
那就改成很低的要求好了

2021-01-05 02:17 UTC, TPGPL approved these changes

2021-01-05 02:17 UTC, merged