Add osu! South East Asia Tournament 4 (oSEAT4) wiki article
ppy/osu-wiki pull request #4642
Opened 2020-12-17 16:00 UTC by Nivalyx

wiki article for the currently ongoing osu! South East Asia Tournament 4

2020-12-17 18:48 UTC, TPGPL requested changes

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +The **osu! South East Asia Tournament 4** (***oSEAT4***) is a double-elimination 1v1 osu!standard tournament hosted by ![][flag_SG] [phox](https://osu.ppy.sh/users/772295). The tournament is open to
```suggestion
The **osu! South East Asia Tournament 4** (***oSEAT4***) is a double-elimination 1v1 osu! tournament hosted by ![][flag_SG] [phox](https://osu.ppy.sh/users/772295). The tournament is open to all players from all ten [ASEAN member states](https://asean.org/asean/asean-member-states/) (![][flag_BN] Brunei Darussalam, ![][flag_KH] Cambodia, ![flag_ID] Indonesia, ![flag_LA] Laos, ![flag_MY] Malaysia, ![flag_MM] Myanmar, ![flag_PH] The Phillipines, ![flag_SG] Singapore, ![flag_TH] Thailand, and ![flag_VN] Vietnam) regardless of rank. It is the 4th installment of the osu! South East Asia Tournament.
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +| Group stage (week 2) | 2020-12-14/2020-12-20 |
```suggestion
| Group Stage week 1 | 2020-12-07/2020-12-13 |
| Group Stage week 2 | 2020-12-14/2020-12-20 |
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +| Finals (week 2) | 2021-01-24/2021-01-30 |
```suggestion
| Finals week 1 | 2021-01-18/2021-01-23 |
| Finals week 2 | 2021-01-24/2021-01-30 |
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +| 5th place | 1 month of osu!supporter tag |
```suggestion
| *4th place* | 2 months of osu!supporter tag |
| *5th place* | 1 month of osu!supporter tag |
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +![Profile badge](img/Badge.png)
```suggestion
![](img/Badge.png "oSEAT4 winner badge")
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +oSEAT4 was run by various osu! community members predominantly hailing from South East Asian countries.
```suggestion
oSEAT4 is run by various osu! community members predominantly hailing from South East Asian countries.
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +| Position | Members |
```suggestion
| Position | Member(s) |
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +| Map selector | ![][flag_SG] [phox](https://osu.ppy.sh/users/772295), ![][flag_SG] [Fragmented](https://osu.ppy.sh/users/847434), ![][flag_TH] [Seaweed](https://osu.ppy.sh/users/5151214), ![][flag_S
```suggestion
| Mappool selector | ![][flag_SG] [phox](https://osu.ppy.sh/users/772295), ![][flag_SG] [Fragmented](https://osu.ppy.sh/users/847434), ![][flag_TH] [Seaweed](https://osu.ppy.sh/users/5151214), ![][flag_SG] [Ayucchi](https://osu.ppy.sh/users/7823498), ![][flag_US] [Not A Function](https://osu.ppy.sh/users/4773094) |
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +| Group | Player 1 (Seed A) | Player 2 (Seed B) | Player 3 (Seed C) | Player 4 (Seed D) | Player 5 (Seed E) | Player 6 (Seed F) |
```suggestion
| Group | Seed A | Seed B | Seed C | Seed D | Seed E | Seed F |
```
should be fine this way

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +### Group stage (week 2)
```suggestion
### Group Stage week 2
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +### Group stage (week 1)
```suggestion
### Group Stage week 1
```

2020-12-17 18:48 UTC, TPGPL commented on wiki/Tournaments/oSEAT/4/en.md
> +### Group stage (week 1)
```suggestion
### Group Stage week 1
```

2020-12-18 04:10 UTC, Nivalyx commented
applied everything + fixed the remark check

2020-12-18 12:09 UTC, TPGPL approved these changes

2020-12-18 12:09 UTC, merged