[ID] Add Beatmap Spotlights Group Articles
ppy/osu-wiki pull request #4667
Opened 2020-12-22 11:21 UTC by SeverinoAji

2020-12-24 05:48 UTC, hikikuman requested changes
Sepertinya ada kata2 yang kurang konsisten sama yang di `wiki/Beatmap_Spotlights` yang kamu bikin waktu itu. Disana itu pakenya `timeshift lobby` sementara disini `timeshift lobi` (beda sama yang yang `lobi` doang ya). Termasuk `timeshift multiplayer lobi` (di 2020_Summer/id.md, di 31, 32, 33) yang menurutku nggak perlu diubah, tetep keep `timeshift multiplayer lobby` aja sama kaya kamu keep `timeshift lobby` di `wiki/Beatmap_Spotlights/id.md`.

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/id.md
> +| Event | Waktu |
```suggestion
| Pertandingan | Waktu |
```

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +| Event | Waktu |
```suggestion
| Pertandingan | Waktu |
```

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +# Beatmap Spotlights Test Run (Musim Panas 2020)
```suggestion
# Uji Coba Beatmap Spotlights (Musim Panas 2020)
```
Diubah jadi `Uji Coba` menurut ku gapapa, kecuali kalo misalnya diubah tapi jadi kurang umum kata2nya. Penempatannya juga diubah, kalo `Beatmap Spotlights Uji Coba` itu rasanya gimana ya, kaya kurang enak dan struktur kata2nya kurang pas. Mungkin sebagai referensi, sama kaya wiki Beatmap Spotlights yang kamu terakhir kamu bikin: `Spotlights Season` jadi `Musim Spotlights`, bukan `Spotlights Musim`.

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/id.md
> +# Beatmap Spotlights Musim 2 (Musim Gugur 2020)
```suggestion
# Musim ke-2 Beatmap Spotlights (Musim Gugur 2020)
```
Sama seperti yang udah ku jelasin di `2020_Summer/id.md` juga.

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +Papan peringkat berikut juga tersedia dalam [Google Spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vRF46ZtScaNWb5KLAF0-CwJhTySle5r3xVhg15x1nTOXYrMWNpRx8HbsRizaQ2AwJpKARJRTtyHbdxs/pubhtm
```suggestion
Papan peringkat berikut juga tersedia di [Google Spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vRF46ZtScaNWb5KLAF0-CwJhTySle5r3xVhg15x1nTOXYrMWNpRx8HbsRizaQ2AwJpKARJRTtyHbdxs/pubhtml#).
```

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +*Catatan: Anda dapat [mengunduh semua daftar putar osu! ](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```suggestion
*Catatan: Anda dapat [mengunduh semua daftar putar osu!](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```
kelebihan spasi

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +*Catatan: Anda dapat [mengunduh semua daftar putar osu! ](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```suggestion
*Catatan: Anda dapat [mengunduh semua daftar putar osu!](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +*Catatan: Anda dapat [mengunduh semua daftar putar osu! ](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```suggestion
*Catatan: Anda dapat [mengunduh semua daftar putar osu!](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +*Catatan: Anda dapat [mengunduh semua daftar putar osu! ](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```suggestion
*Catatan: Anda dapat [mengunduh semua daftar putar osu!](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
```

2020-12-24 05:48 UTC, hikikuman commented on wiki/Beatmap_Spotlights/Seasons/id.md
> +# Beatmap Spotlights seasons
```suggestion
# Musim Beatmap Spotlights
```

2020-12-25 12:01 UTC, SeverinoAji commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/id.md
> +| Event | Waktu |
yang ini ga lebih baik di keep jadi Event aja ? kok agak kurang gimana ya menurut gw kalo pake nya Pertandingan (?)

2020-12-25 14:28 UTC, SeverinoAji commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/id.md
> +# Beatmap Spotlights Musim 2 (Musim Gugur 2020)
lebih nyambung yg ini awkwk ok applied

2020-12-25 14:28 UTC, SeverinoAji commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +*Catatan: Anda dapat [mengunduh semua daftar putar osu! ](https://osu.ppy.sh/beatmaps/packs/1992) secara terpisah.*
aaaaaaaaa spasi link qqqqqqqqqqqqq

2020-12-25 14:30 UTC, SeverinoAji commented on wiki/Beatmap_Spotlights/Seasons/id.md
> +# Beatmap Spotlights seasons
gw kira buat hal ginian ga perlu di translate wkwk applied , thanks sies

2020-12-26 08:14 UTC, SeverinoAji commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/id.md
> +| Event | Waktu |
setelah di pikir2 kayanya lebih pas di translate ke Pertandingan wkwk

2020-12-26 08:16 UTC, SeverinoAji commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/id.md
> +| Event | Waktu |
sipp

2020-12-29 04:54 UTC, hikikuman requested changes
Better to use `kamu` instead of `Anda` as this isn't a formal article (ex: rules, ranking criteria). Also, please add an additional explanation or description when you commit a changes (ex: `fix typo`, `changed 'Anda' to 'kamu'` on the `Update id.md` section or `Add an optional extended description...` section.)

2021-01-03 05:58 UTC, hikikuman approved these changes
Checked yesterday and today. Should be fine for now.

2021-01-04 08:16 UTC, TicClick approved these changes

2021-01-04 08:16 UTC, merged