[ID] Add Beatmap Discussion
ppy/osu-wiki pull request #4672
Opened 2020-12-24 09:56 UTC by CodeTrojan

Add Indonesian translation and images

2020-12-26 10:45 UTC, hikikuman requested changes
I prefer to use `kamu` instead of `Anda` since this isn't a formal article (ex: rules).

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Hype train melacak berapa banyak [hypes](/wiki/Beatmaps/Hype) mapset yang telah di hype. Setelah 5 hypes dicapai, beatmap dapat dinominasikan oleh [Beatmap Nominators](/wiki/People/The_Team/Beatmap_N
```suggestion
Hype train melacak berapa banyak [hypes](/wiki/Beatmaps/Hype) mapset yang telah di hype. Setelah 5 hype dicapai, beatmap dapat dinominasikan oleh [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators). Hype hanya dapat diberikan dengan membuka tab `Umum (Semua tingkat kesulitan)`, karena hype tidak akan berfungsi jika diakses melalui tab `Umum` atau `Linimasa`. Meng-klik tombol `Hype` akan otomatis memindahkan Anda ke tab yang benar.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Bar status nominasi melacak nominasi-nominasi beatmap. Setelah beatmap menerima dua nominasi, maka akan masuk ke qualified. <!--TODO: Insert 'Qualified' link-->
```suggestion
Status bar nominasi akan melacak nominasi dari sebuah beatmap. Setelah beatmap tersebut menerima dua nominasi, maka beatmap tersebut akan dikualifikasikan. <!--TODO: Insert 'Qualified' link-->
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Informasi umum menunjukkan pembuat beatmapset, tanggal pengiriman, dan tanggal terakhir diperbarui. [Perubahan status](/wiki/Beatmaps), seperti beatmap yang mendapatkan Ranked, Loved atau Graveyarded
```suggestion
Informasi umum menunjukkan pembuat beatmapset, tanggal pengiriman, dan tanggal terakhir diperbarui. [Perubahan status](/wiki/Beatmaps), seperti beatmap yang mendapatkan status Ranked, Loved atau Graveyard, juga dianggap sebagai pembaruan dan akan ditampilkan di sini.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Tombol `Amati` dan` Tidak amati` mengijinkan untuk ikuti/tidak mengikuti perkembangan beatmap. Jika beatmap diikuti, postingan baru dan balasan di laman diskusi beatmap akan membuat notifikasi di osu
```suggestion
Tombol `Amati` dan` Tidak amati` mengijinkan untuk mengikuti/tidak mengikuti perkembangan beatmap. Jika beatmap diikuti, postingan baru dan balasan di laman diskusi beatmap akan membuat notifikasi di osu!web. Langganan dapat dikelola melalui [modding watchlist](https://osu.ppy.sh/beatmapsets/watches), yang dapat ditemukan melalui menu laman beranda.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Tombol `Beatmap Page` akan mengarah ke laman info beatmap. Ini juga dapat dilakukan dengan mengklik [beatmap header](#beatmap-header).
```suggestion
Tombol `Laman Beatmap` akan mengarahkan pengguna menuju ke laman info beatmap. Ini juga dapat dilakukan dengan mengklik [beatmap header](#beatmap-header).
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +`Umum (Semua tingkat kesulitan)` menunjukkan post yang berlaku untuk semua tingkat kesulitan. Common posts di tab ini mencakup metadata, catatan, dan diskusi di beatmapset secara keseluruhan.
```suggestion
`Umum (Semua tingkat kesulitan)` menunjukkan postingan yang berlaku untuk semua tingkat kesulitan. Postingan yang umum di tab ini mencakup metadata, catatan, dan diskusi di beatmapset secara keseluruhan.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +`Linimasa` menampilkan postingan pada titik-titik tertentu dari suatu kesulitan menurut timestamp pertama yang ditempatkan. Setiap postingan di tab ini harus menyertakan timestamp untuk diposting. Ti
```suggestion
`Linimasa` menampilkan postingan pada titik-titik tertentu dari suatu kesulitan menurut timestamp pertama yang ditempatkan. Setiap postingan di tab ini harus menyertakan timestamp untuk diposting. Timestamp apa pun tidak akan mempengaruhi urutan postingan.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +`Riwayat` mencatat semua perubahan ke laman diskusi dalam urutan kronologis. Perubahan diberi kode warna; dengan hijau menjadi postingan yang diselesaikan dan perubahan status, merah menjadi masalah
```suggestion
`Riwayat` mencatat semua perubahan ke laman diskusi dalam urutan kronologis. Perubahan diberi kode warna; dengan hijau yang merupakan postingan yang diselesaikan dan perubahan status, merah merupakan masalah baru setelah nominasi, dan biru merupakan hal-hal yang lainnya. Meng-klik nomor referensi mana pun akan membuka postingan tertentu. Tab riwayat tidak digunakan saat modding, tetapi berguna untuk [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators) dan staf lain untuk memeriksa masalah tersebut.
```
daripada pakai `menjadi`, lebih baik pakai `merupakan`, lebih sesuai penggunaannya berdasarkan konteks yang ada.

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +## Submission field
```suggestion
## Tempat pengajuan
```
inconsistency translation: `Submission field` and `Tempat pengajuan`

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Submission field adalah tempat [mods](/wiki/Modding) ditulis. Setelah ditulis, mod harus diserahkan ke laman diskusi. Ini dapat dilakukan dengan menekan salah satu dari tiga tombol jenis; `Pujian`, `
```suggestion
Tempat pengajuan adalah sebuah tempat untuk menulis [mod](/wiki/Modding). Setelah ditulis, mod harus di-submit ke laman diskusi. Ini dapat dilakukan dengan menekan salah satu dari tiga tombol jenis; `Pujian`, `Saran` atau `Masalah`.
```
penggunaan `diserahkan` kurang familiar, jadi menurutku lebih baik pakai `di-submit` aja.

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +`Pujian` digunakan untuk pujian dan dorongan. `Saran` digunakan untuk postingan yang tidak secara langsung bertentangan dengan aturan apa pun. `Masalah` digunakan untuk postingan yang berkonflik lang
```suggestion
`Pujian` digunakan untuk pujian dan dorongan. `Saran` digunakan untuk postingan yang secara langsung tidak bertentangan dengan aturan apa pun. `Masalah` digunakan untuk postingan yang berkonflik langsung dengan [Kriteria Ranking](/wiki/Ranking Criteria), atau yang dianggap salah secara intersubjektif. Setelah tombol ditekan, mod akan dikirim ke laman diskusi.
```
ya sebenarnya aku juga coba buat memahami apa itu `intersubjektif` disini, masih agak membingungkan soalnya blm dapet kata2 yang pas.

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Jika Anda memposting di tab `Linimasa`, Anda harus menyertakan timestamp di postingan Anda. Jika timestamp Anda dekat dengan mod lain, Anda harus konfirmasi bahwa timestamp tersebut tidak mengatasi m
```suggestion
Jika Anda memposting di tab `Linimasa`, Anda harus menyertakan timestamp di postingan Anda. Jika timestamp Anda dekat dengan mod lain, Anda harus konfirmasi bahwa timestamp tersebut tidak berhubungan dengan mod yang ada didekat timestamp Anda. **Periksa setiap postingan sebelum mencentang kotaknya!** Ini mungkin bermanfaat untuk `Pin` di tempat modding sambil memeriksa masalah lain. Mengaktifkan pin akan memungkinkan tempat pengajuan untuk pindah langsung ketempat yang sudah di pin.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Diskusi adalah postingan dimana [tempat pengajuan](#submission-field) ditaruh ketika di submit. Pengguna mengunjungi laman diskusi bisa melihat postingan yang dibuat oleh semua pengguna lainnya, dan
```suggestion
Diskusi adalah postingan dimana [tempat pengajuan](#submission-field) ditaruh ketika di-submit. Pengguna yang sedang mengunjungi laman diskusi bisa melihat postingan yang dibuat oleh semua pengguna lainnya, dan bisa ikut partisipasi dalam postingan diskusi. Diskusi bisa diselesaikan dengan mengklik tombol `Tanggapi` atau `Balas` dibawah postingan dan tulis sebuah tanggapan. Setelah selesai menanggapi, tekan `Enter` atau mengklik `Balas` untuk men-submit ke dalam diskusi.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Pembuat beatmapset dan penulis modpost, memiliki kemampuan untuk menutup postingan masalah dengan tombol `Ditandai sebagai telah terjawab`. Ini menandai bahwa masalah telah ditangani oleh pengguna la
```suggestion
Pembuat beatmapset dan penulis dari postingan mod, memiliki kemampuan untuk menutup postingan masalah dengan tombol `Ditandai sebagai telah terjawab`. Ini menandai bahwa masalah telah ditangani oleh pengguna lain dan menghapusnya dari [opsi pengurutan](#sorting-options) `Belum terjawab`. Postingan mod dapat dibuka kembali oleh pengguna mana pun dengan menambahkan balasan lebih lanjut ke sebuah postingan dan mengklik `Balas dan Buka kembali`. Balasan ini digunakan ketika modder merasa kesalahan yang telah ditutup belum diperbaiki sepenuhnya, atau topik tersebut perlu didiskusikan lebih lanjut.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Diskusi dapat diurut dengan tombol di bawah judul `Diskusi`. Awalnya, postingan tab `Linimasa` akan diurutkan secara kronologis berdasarkan timestamp pertama yang diberikan. Postingan `Umum (Semua ti
```suggestion
Diskusi dapat diurut dengan tombol di bawah judul `Diskusi`. Awalnya, postingan tab `Linimasa` akan diurutkan secara kronologis berdasarkan timestamp pertama yang diberikan. Postingan `Umum (Semua tingkat kesulitan)` dan `Umum (Tingkat kesulitan ini)` akan diurutkan berdasarkan pembaruan terakhir. Perhatikan bahwa [opsi pengurutan](#sorting-options) yang dipilih juga akan mengubah apa yang ditampilkan di sini. Tombol lain di bagian atas tempat diskusi yang mengubah cara diskusi dilihat termasuk `Ciutkan semua` dan `Lebarkan semua` yang dimana masing-masing akan menampilkan/menyembunyikan postingan.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Jika modpost sangat membantu [Kudosu!](/wiki/Modding/Kudosu) dapat diberikan. Ini bisa diselesaikan oleh siapapun termasuk pembuat postingan dengan memberikan postingan sebuah jempol ke atas. Ini ber
```suggestion
Jika terdapat sebuah postingan mod yang sangat membantu, [Kudosu!](/wiki/Modding/Kudosu) dapat diberikan. Kudosu dapat diberikan oleh siapapun dengan memberikan sebuah jempol ke atas, kecuali pengguna yang membuat postingan tersebut. Ini berguna bagi modder yang dimana Kudosu! diperlukan untuk masuk ke [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators). Jika fitur Kudosu! disalahgunakan, anggota [BN](/wiki/People/The_Team/Beatmap_Nominators), [NAT](/wiki/People/The_Team/Nomination_Assessment_Team), dan [GMT](/wiki/People/The_Team/Global_Moderation_Team) dapat memberi jempol ke bawah untuk menyangkal Kudosu! yang telah diberikan. Jika penyalahgunaan dilakukan dengan niat jahat, hukuman juga dapa diberikan kepada pelaku.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +### Linimasa diskusi
```suggestion
### Diskusi linimasa
```
sepertinya ini seharusnya `Diskusi linimasa`, bukan `Linimasa diskusi`.

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Linimasa di sebelah kiri diskusi menunjukkan timestamp alamat postingan. Ini hanya tersedia di bagian `Linimasa`. Jika tidak, linimasa diskusi akan dikosongkan.
`timestamp alamat postingan` ini sebenernya kata2nya kaku banget, mungkin bisa diubah jadi `postingan timestamp terkait`.

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Tag menampilkan [peran penting](/wiki/People/The_Team) di bawah nama pengguna. Hanya peran-peran yang relevan saja untuk diskusi beatmap yang ditampilkan. Ini termasuk anggota `MAPPER`,`BN`, `NAT`,`G
```suggestion
Tag menampilkan [peran penting](/wiki/People/The_Team) di bawah nama pengguna. Hanya peran-peran yang relevan saja untuk diskusi beatmap yang ditampilkan. Ini termasuk `MAPPER`, anggota dari `BN`, `NAT`,`GMT`, dan `DEV` yang memiliki lebih banyak opsi daripada pengguna biasa di laman diskusi.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Pemilik postingan di laman diskusi dapat menggunakan alat pemformatan agar penggunaan lebih mudah. Ini termasuk tautan permanen, pengeditan, dan penghapusan.
```suggestion
Pemilik postingan di laman diskusi dapat menggunakan alat pemformatan agar penggunaannya lebih mudah. Ini termasuk tautan, penyuntingan, dan penghapusan.
```

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +`Edit` memungkinkan pengguna untuk mengedit kiriman mereka jika terjadi kesalahan. Ini tidak dimaksudkan untuk digunakan untuk membalas pesan. Disarankan buat balasan baru sebagai gantinya.
```suggestion
`Sunting` memungkinkan pengguna untuk mengedit kiriman mereka jika terjadi kesalahan. Ini tidak dimaksudkan untuk digunakan untuk membalas pesan. Disarankan buat balasan baru sebagai gantinya.
```
lupa sini ini aku emang betul `Sunting` atau sebenarnya di laman diskusi beatmap nya itu ditulis `Edit`.  Coba di re-check lagi laman diskusi beatmap versi bahasa Indonesianya.

2020-12-26 10:45 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +![](img/sorting-options_id.jpg "Untuk pengurutan yang Anda butuhkan")
```suggestion
![](img/sorting-option_id.jpg "Untuk pengurutan yang Anda butuhkan")
```

2020-12-28 17:34 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +`Pujian` digunakan untuk pujian dan dorongan. `Saran` digunakan untuk postingan yang secara langsung tidak bertentangan dengan aturan apa pun. `Masalah` digunakan untuk postingan yang berkonflik lang
```suggestion
`Pujian` digunakan untuk pujian dan dorongan. `Saran` digunakan untuk postingan yang secara langsung tidak bertentangan dengan aturan apa pun. `Masalah` digunakan untuk postingan yang berkonflik langsung dengan [Kriteria Ranking](/wiki/Ranking_Criteria), atau yang dianggap salah secara intersubjektif. Setelah tombol ditekan, mod akan dikirim ke laman diskusi.
```

2021-01-01 17:09 UTC, hikikuman requested changes
Maybe you can change `submit` to `kirim` (`mengirim`, `dikirim`, `mengirimkan`, etc.) as I just finished looking for a reference in another article. Also, there is an inconsistent translation between `mengklik` and `meng-klik`. Use `mengklik` instead of `meng-klik` the same as done in other articles.

2021-01-04 09:25 UTC, hikikuman requested changes
Penggunaan kata `di` dan `ke` beberapa masih kurang konsisten. Masih ada yang seharusnya disambung tetapi ditulis terpisah, dan sebaliknya. Contoh: kata `di kirim` pada baris ke-14 yang seharusnya ditulis `dikirim` (sumber: https://kbbi.web.id/kirim), kata `diatas` pada baris ke-27 yang seharusnya ditulis `di atas` (sumber: https://kbbi.kemdikbud.go.id/entri/di%20atas), kata `ketempat` pada baris ke-131 yang seharusnya ditulis `ke tempat` (sumber: https://id.wiktionary.org/wiki/Lampiran:Kata_Indonesia_yang_sering_salah_dieja#Awalan_di-/ke-_dan_kata_depan_di/ke), dll.

Simpelnya, `di` yang disambung itu adalah awalan, dan `di` yang dipisah itu adalah kata depan. Awalan `di` berfungsi membentuk kata kerja dan menyatakan makna pasif . Sedangkan kata depan `di` menyatakan keterangan tempat.

2021-01-06 13:44 UTC, hikikuman requested changes
Masih terdapat beberapa kata `di` dan `ke` yang spasinya kurang konsisten pada kata yang sama.

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +### Jempol keatas/kebawah
```suggestion
### Jempol ke atas/ke bawah
```

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Diskusi beatmap bertujuan untuk memberikan antarmuka yang jelas dan dapat dimengerti, yang dimana peningkatan pada beatmap menjadi hal yang utama.
```suggestion
Diskusi beatmap bertujuan untuk memberikan antarmuka yang jelas dan dapat dimengerti, yang di mana peningkatan pada beatmap menjadi hal yang utama. 
```

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +![](img/discussion_id.jpg "Dimana diskusi berlangsung!")
```suggestion
![](img/discussion_id.jpg "Di mana diskusi berlangsung!")
```

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Diskusi adalah postingan dimana [tempat pengajuan](#submission-field) ditaruh ketika dikirim. Pengguna yang sedang mengunjungi laman diskusi bisa melihat postingan yang dibuat oleh semua pengguna lai
```suggestion
Diskusi adalah postingan di mana [tempat pengajuan](#submission-field) ditaruh ketika dikirim. Pengguna yang sedang mengunjungi laman diskusi bisa melihat postingan yang dibuat oleh semua pengguna lainnya, dan bisa ikut partisipasi dalam postingan diskusi. Diskusi bisa diselesaikan dengan mengklik tombol `Tanggapi` atau `Balas` di bawah postingan dan tulis sebuah tanggapan. Setelah selesai menanggapi, tekan `Enter` atau mengklik `Balas` untuk mengirimkan ke dalam diskusi.
```

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Diskusi dapat diurut dengan tombol di bawah judul `Diskusi`. Awalnya, postingan tab `Linimasa` akan diurutkan secara kronologis berdasarkan timestamp pertama yang diberikan. Postingan `Umum (Semua ti
```suggestion
Diskusi dapat diurut dengan tombol di bawah judul `Diskusi`. Awalnya, postingan tab `Linimasa` akan diurutkan secara kronologis berdasarkan timestamp pertama yang diberikan. Postingan `Umum (Semua tingkat kesulitan)` dan `Umum (Tingkat kesulitan ini)` akan diurutkan berdasarkan pembaruan terakhir. Perhatikan bahwa [opsi pengurutan](#sorting-options) yang dipilih juga akan mengubah apa yang ditampilkan di sini. Tombol lain di bagian atas tempat diskusi yang mengubah cara diskusi dilihat termasuk `Ciutkan semua` dan `Lebarkan semua` yang di mana masing-masing akan menampilkan/menyembunyikan postingan.
```

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Jika terdapat sebuah postingan mod yang sangat membantu, [Kudosu!](/wiki/Modding/Kudosu) dapat diberikan. Kudosu dapat diberikan oleh siapapun dengan memberikan sebuah jempol ke atas, kecuali penggun
```suggestion
Jika terdapat sebuah postingan mod yang sangat membantu, [Kudosu!](/wiki/Modding/Kudosu) dapat diberikan. Kudosu dapat diberikan oleh siapapun dengan memberikan sebuah jempol ke atas, kecuali pengguna yang membuat postingan tersebut. Ini berguna bagi modder yang di mana Kudosu! diperlukan untuk masuk ke [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators). Jika fitur Kudosu! disalahgunakan, anggota [BN](/wiki/People/The_Team/Beatmap_Nominators), [NAT](/wiki/People/The_Team/Nomination_Assessment_Team), dan [GMT](/wiki/People/The_Team/Global_Moderation_Team) dapat memberi jempol ke bawah untuk menyangkal Kudosu! yang telah diberikan. Jika penyalahgunaan dilakukan dengan niat jahat, hukuman juga dapa diberikan kepada pelaku.
```

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Kamu dapat memilih [tingkat kesulitan](/wiki/difficulties) yang berbeda melalui dropdown menu. Ini akan memunculkan semua tingkat kesulitan yang tersedia saat ini, bersama dengan yang lama, dan mengh
```suggestion
Kamu dapat memilih [tingkat kesulitan](/wiki/difficulties) yang berbeda melalui dropdown menu. Ini akan memunculkan semua tingkat kesulitan yang tersedia saat ini, bersama dengan yang lama, dan menghapus tingkat kesulitan yang memiliki saran/masalah. Angka yang muncul di samping nama tingkat kesulitan adalah angka postingan yang belum terselesaikan berdasarkan tingkat kesulitan tertentu. Ini penting untuk memeriksa kembali menu ini sebelum melakukan pengiriman mod apa pun.
```

2021-01-06 13:44 UTC, hikikuman commented on wiki/Beatmap_Discussion/id.md
> +Opsi pengurutan merubah cara pandang diskusi beatmap dilihat. Ketika sebuah opsi di pilih, opsi pengurutan merubah modding timeline dan modding section hanya menyertakan jenis postingan yang dipilih.
```suggestion
Opsi pengurutan merubah cara pandang diskusi beatmap dilihat. Ketika sebuah opsi dipilih, opsi pengurutan merubah modding timeline dan modding section hanya menyertakan jenis postingan yang dipilih. Opsi pengurutan juga sangat berguna untuk melihat postingan yang belum terjawab di laman diskusi. Opsi yang berbeda meliputi:
```

2021-01-06 14:05 UTC, hikikuman submitted a review, later dismissed
Re-checked. So far, everything is fine.

2021-01-06 16:14 UTC, TPGPL approved these changes

2021-01-06 16:15 UTC, merged