[KO] Add No Fail
ppy/osu-wiki pull request #4679
Opened 2020-12-26 08:52 UTC by Ge-n-z

I will work on the modes with less content first.

2021-01-09 02:11 UTC, TPGPL requested changes

2021-01-09 02:11 UTC, TPGPL commented on wiki/Game_modifier/No_Fail/ko.md
> +태그:
```suggestion
tags:
```

2021-01-09 02:11 UTC, TPGPL commented on wiki/Game_modifier/No_Fail/ko.md
> +![NF mod icon](/wiki/shared/mods/NF.png "불사 모드(NF) 아이콘")
`NF mod icon` needs to be translated

2021-01-09 02:11 UTC, TPGPL commented on wiki/Game_modifier/No_Fail/ko.md
> +만약 플레이어가 비트맵을 플레이하는 도중 점수를 조금도 내지 않았다면, *실패* 하게 됩니다.
```suggestion
**불사 모드**는 플레이어가 [비트맵](/wiki/Beatmaps)을 플레이할 때 실패하는 것을 막아주는 [모드](/wiki/Game_modifier)입니다. 불사 모드를 활성화한 플레이어는 [비트맵](/wiki/Beatmaps)을 플레이하는 도중 [체력바](/wiki/Glossary#life-bar)가 0이 되더라도 실패하지 않습니다. 만약 플레이어가 비트맵을 플레이하는 도중 점수를 조금도 내지 않았다면, *실패* 하게 됩니다.
```

2021-01-09 02:16 UTC, Garalulu commented on wiki/Game_modifier/No_Fail/ko.md
> +## 불사 모드
'불사'는 원래 없는 내용을 의역하신 듯 한데 실제 유저들이 이 모드를 부를 때 차용하는 단어는 아니네요. 그냥 영어 그대로 '노페일' 모드로 하는게 많이들 쓰고 자연스럽습니다.

2021-01-10 02:46 UTC, Ge-n-z commented on wiki/Game_modifier/No_Fail/ko.md
> +## 불사 모드
알겠습니다!

2021-01-10 02:49 UTC, Ge-n-z commented on wiki/Game_modifier/No_Fail/ko.md
> +![NF mod icon](/wiki/shared/mods/NF.png "불사 모드(NF) 아이콘")
Done :)

2021-01-10 22:06 UTC, TPGPL approved these changes

2021-01-10 22:06 UTC, merged