[KO] Add Autopilot
ppy/osu-wiki pull request #4680
Opened 2020-12-26 09:10 UTC by Ge-n-z

Native Comment please.

2021-01-09 02:17 UTC, TPGPL requested changes

2021-01-09 02:17 UTC, TPGPL commented on wiki/Game_modifier/Autopilot/ko.md
> +태그:
```suggestion
stub: true
tags:
```

2021-01-09 02:17 UTC, TPGPL commented on wiki/Game_modifier/Autopilot/ko.md
> +![AP mod icon](/wiki/shared/mods/AP.png "오토 파일럿(AP) 모드 아이콘")
`AP mod icon` needs to be translated

2021-01-10 02:45 UTC, Ge-n-z commented on wiki/Game_modifier/Autopilot/ko.md
> +![AP mod icon](/wiki/shared/mods/AP.png "오토 파일럿(AP) 모드 아이콘")
Done :)

2021-01-10 14:52 UTC, TPGPL approved these changes

2021-01-10 14:52 UTC, merged