[KO] Add Spun Out
ppy/osu-wiki pull request #4682
Opened 2020-12-26 09:28 UTC by Ge-n-z

2021-01-09 02:18 UTC, TPGPL requested changes

2021-01-09 02:18 UTC, TPGPL commented on wiki/Game_modifier/Spun_Out/ko.md
> +태그:
```suggestion
stub: true
tags:
```

2021-01-09 02:18 UTC, TPGPL commented on wiki/Game_modifier/Spun_Out/ko.md
> +![SO mod icon](/wiki/shared/mods/SO.png "스핀 아웃(SO) 모드 아이콘")
`SO mod icon` needs to be translated

2021-01-09 02:18 UTC, TPGPL commented on wiki/Game_modifier/Spun_Out/ko.md
> +이 모드는 모든 비트맵의 스피너를 시계 방향으로 분당 회전수(SPM)를 정확히 286.48로 맞추며 돌립니다. 이 수치는 477.26 SPM의 3/5입니다.
```suggestion
**스펀 아웃**은 [osu!standard](/wiki/Game_mode/osu!)의 플레이어가 [비트맵](/wiki/Beatmaps)을 플레이할 때 성공적으로 스피너를 돌릴 수 있게 도와주는 [모드](/wiki/Game_modifier)입니다. 이 모드는 모든 비트맵의 스피너를 시계 방향으로 분당 회전수(SPM)를 정확히 286.48로 맞추며 돌립니다. 이 수치는 477.26 SPM의 3/5입니다.
```

2021-01-10 02:42 UTC, Ge-n-z commented on wiki/Game_modifier/Spun_Out/ko.md
> +![SO mod icon](/wiki/shared/mods/SO.png "스핀 아웃(SO) 모드 아이콘")
Done :)

2021-01-10 14:47 UTC, TPGPL approved these changes

2021-01-10 14:48 UTC, merged