Translate "Storyboards" into Ukrainian
ppy/osu-wiki pull request #4719
Opened 2021-01-02 17:34 UTC by Esutarosa

2021-01-03 12:31 UTC, atimonder1 requested changes

2021-01-03 12:31 UTC, atimonder1 commented on wiki/Storyboards/uk.md
> +![Це видно, коли ви пропускаєте або отримуєте 50 в раніше зігранному комбо.](img/Sbfailing.png "This is shown when you missed or got a 50 in the previously played combo.")
```suggestion
![Це показано під час пропускання або отримування 50 в раніше зігранному комбо.](img/Sbfailing.png "This is shown when you missed or got a 50 in the previously played combo.")
```

2021-01-03 12:31 UTC, atimonder1 commented on wiki/Storyboards/uk.md
> +**Сторіборди** (СБ) — це спеціально створений анімований фон, який супроводжує [бітмапу](/wiki/Beatmaps), часто для декоративних, а іноді й для ігрових цілей. Вони можуть складатися майже з усього, а
```suggestion
**Сторіборд** (СБ) — це спеціально створений анімований фон, який супроводжує [бітмапу](/wiki/Beatmaps), часто для декоративних або ігрових цілей. Вони можуть складатися майже з усього, але зазвичай містять візуальні ефекти, котрі призначені зробити карту більш естетично привабливою та самобутньою. Ця ідея прийшла з гри [Osu! Tatakae! Ouendan](/wiki/Glossary#ouendan). Залежачи від натхнення, сторіборд може підлаштовуватись під продуктивність користувача при грі і відображати різні речі в залежності від того, наскільки добре гравець справляється.
```

2021-01-03 12:31 UTC, atimonder1 commented on wiki/Storyboards/uk.md
> +Сторіборди складно робити, і на їх створення йде багато часу та знань у галузі стандартної анімації та створення графіки. osu! пропонує в [редакторі карт](/wiki/Beatmap_Editor) розділ [дизайну](/wiki
```suggestion
Сторіборди не так і просто робити, на їх створення йде багато часу та знань у галузі стандартної анімації та створення графіки. osu! пропонує в [редакторі карт](/wiki/Beatmap_Editor) розділ [дизайну](/wiki/Beatmap_Editor/Design) (F2), де і відбувається створення сторібордів. Більшість завзятих творців обирають натомість програмувати безпосередньо за допомогою [скриптів](/wiki/Storyboard_Scripting). Багато хто вирішує писати програми в повнофункціональному програмуванні для створення сценаріїв, оскільки для створення складних візуальних ефектів потрібна велика кількість коду.
```

2021-01-04 17:21 UTC, TicClick approved these changes
the reviewer says the translation is okay now

2021-01-04 17:21 UTC, merged