[RU] Retranslate GMT
ppy/osu-wiki pull request #4745
Opened 2021-01-08 15:09 UTC by TicClick

2021-01-13 13:51 UTC, TicClick commented
temporarily putting this on hold, as I want to improve the original article first

2021-01-29 23:56 UTC, UristMcKobold requested changes

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +**Команда глобальной модерации** (ранее — администраторы, неформально — «зелёные BAT»), или **GMT**, — группa пользователей, которые следят за поведением игроков в сообществе osu!, а также решают раз
```suggestion
**Команда глобальной модерации** (ранее — администраторы, неформально — «зелёные BAT»), или **GMT**, — группa пользователей, которые следят за поведением игроков в сообществе osu!, а также решают различные связанные с этим проблемы. Модераторы отличаются от остальных пользователей наличием титула и ника, который имеет цитрусовый цвет на форуме и кирпично-красный — в клиенте osu!.
```
Я бы добавил уточнение, а то не сразу понятно, где именно. В оригинале уточнение присутствует!

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +***Примечание: если модератор нарушает правила, злоупотребляет полномочиями или иным образом нарушает кодекс профессиональной этики, на него можно пожаловаться в [службу поддержки](/wiki/People/The_T
```suggestion
***Примечание: если модератор переступает через правила, злоупотребляет полномочиями или иным образом нарушает профессиональную этику, на него можно пожаловаться в [службу поддержки](/wiki/People/The_Team/Account_support_team#support@ppy.sh).***\
```
Как и в соседнем ПРе.

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +Модераторы отвечают за порядок в сообществе в целом. Им стоит писать по поводу любых вещей, связанных с правилами и их нарушением, к примеру (список неполный):
```suggestion
Модераторы отвечают за порядок на форуме и в чате, а также следят за происходящим в сообществе. Им стоит писать по поводу любых вещей, связанных с правилами и их нарушением, к примеру (список неполный):
```
«в целом» тут больше как вводное, нежели что-то, имеющее смысл. Ближе к оригиналу переделал первое предложение.

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +- модерирование профилей (всё, что нарушает правила и находится на странице пользователя).
Некоторые мысли: оригинально в третьем примере нет таких подробностей, там просто общие моменты. Ну и к тому же, у тебя повторяется дважды «спам и оскорбления» в этом списке, но рифмуется неплохо: 1-3 строчки со «спамом и оскорблениями», 2-4 с «нарушением правил».

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +В модераторы обычно берут тех, кто уже вносит вклад в поддержание порядка в игре. Таких пользователей часто замечают за их помощь остальным, активность в сообществе и прилежное поведение. Знание каки
```suggestion
В модераторы обычно берут тех, кто уже своим силами пытается поддерживать порядок в игре. Таких пользователей часто замечают за их помощь остальным, активность в сообществе и прилежное поведение. Знание языков помимо английского также будет значительным плюсом. Все кандидаты в модераторы обсуждаются внутри команды и оцениваются с разных сторон, чтобы было понятно, как они могут себя проявить в новой должности.
```
«вклад в поддержание порядка в игре» — странное выражение какое-то. И вообще, отсебятина же, в оригинале мысль такая: «Для становления модератором требуется приложить немало усилий». Но я не против.
«каких-то» не добавляет ничего в предложение, и без него оно прекрасно понимается.

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +1. Будьте вежливы и относитесь к другим пользователям с уважением. Не нарушайте правил, не получайте сайленсов, имейте хорошую репутацию.
```suggestion
1. Будьте вежливы и относитесь к другим пользователям с уважением. Не нарушайте правил, не получайте сайленсов, не имейте плохую репутацию.
```
Изменил концовку, так как у тебя везде «не» в этом предложении, плюс «хорошая репутация» — это не для всех достижимо, это может отпугнуть некоторых.

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +3. Знайте [правила](/wiki/Rules), что они означают и как и когда применяются. Очень важно уметь провести границу между допустимым и неприемлемым поведением.
```suggestion
3. Знайте [правила](/wiki/Rules), а также как и когда их применять. Очень важно уметь проводить границу между допустимым и неприемлемым поведением.
```
«что они означают» несёт пустой смысл какой-то. Это же подразумевается в «знайте правила». И мне не нравится переход из первой части во вторую, лучше связочное слово добавить.

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +В общем случае за кандидатами наблюдают в течение нескольких недель или месяцев, чтобы убедиться, что они стоят добавления в команду. Не спешите. Если у вас есть какие-то вопросы относительно правил,
```suggestion
В общем случае за кандидатами наблюдают в течение нескольких недель или месяцев, чтобы убедиться, что они стоят добавления в команду. Не спешите. Если у вас есть какие-то вопросы относительно правил, поведения в чате, репортов и подобных вещей, задавайте их любому модератору.
```
Репорт = отправить жалобу, отправка отправки жалобы? Глагол тут не нужен, так как репорты можно только отправлять.

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +1. Не стоит регулярно спрашивать модераторов о своей кандидатуре. В GMT не добавляют в качестве «награды» за помощь и что-то полезное, это работает в другом направлении. Помогайте, чтобы помогать, а
```suggestion
1. Не стоит регулярно спрашивать модераторов о своих шансах стать модератором. В GMT не добавляют в качестве «награды» за помощь и что-то полезное, это работает в другом направлении. Помогайте, чтобы помогать, а не чтобы куда-то продвинуться.
```
«не спрашивайте о своей кандидатуре» можно понять в другом смысле, вроде «не спрашивайте про себя». Мой вариант более точный.

2021-01-29 23:56 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +4. Не переусердствуйте с помощью. Модерирование — это процесс, а не результат, и он требует выносливости и долговременного вклада, а не всплесков активности. От чрезмерных усилий можно выгореть и пот
```suggestion
4. Не переусердствуйте с помощью. Лучше регулярно помогать по чуть-чуть, а не занимать этим делом всё своё время. От чрезмерных усилий можно выгореть и потерять мотивацию. Относитесь ко всему проще!
```
Если честно, меня смущает второе предложение очень сильно, о его смысле я понял только в последующем предложении.

2021-01-30 00:14 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +Модераторы отвечают за порядок в сообществе в целом. Им стоит писать по поводу любых вещей, связанных с правилами и их нарушением, к примеру (список неполный):
мне не нравится, что здесь дублируются формулировки во вступлении и в списке ниже, поэтому я хочу чат и форум выкинуть конкретно из этого параграфа. если убрать «в целом», получится лучше?

2021-01-30 00:14 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +- модерирование профилей (всё, что нарушает правила и находится на странице пользователя).
это — вынужденная мера: я хочу перечислить большинство областей, но в параграфе выше написано «стоит писать по поводу любых вещей, связанных с правилами и их нарушением». чат, форум и прочее с правилами не связаны, в отличие от нарушений, поэтому вот так.

если ты придумаешь вариант лучше, я буду рад

2021-01-30 00:14 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +В модераторы обычно берут тех, кто уже вносит вклад в поддержание порядка в игре. Таких пользователей часто замечают за их помощь остальным, активность в сообществе и прилежное поведение. Знание каки
всё так

2021-01-30 00:14 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +1. Будьте вежливы и относитесь к другим пользователям с уважением. Не нарушайте правил, не получайте сайленсов, имейте хорошую репутацию.
пускай, но «имейте хорошую», вообще говоря, не равно «не имейте плохую»

2021-01-30 00:14 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +3. Знайте [правила](/wiki/Rules), что они означают и как и когда применяются. Очень важно уметь провести границу между допустимым и неприемлемым поведением.
> Это же подразумевается в «знайте правила».

ха, ну я бы, судя по тому, что иногда происходит, так не сказал бы

2021-01-30 00:14 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +4. Не переусердствуйте с помощью. Модерирование — это процесс, а не результат, и он требует выносливости и долговременного вклада, а не всплесков активности. От чрезмерных усилий можно выгореть и пот
пускай так, тоже хороший вариант

2021-01-30 00:15 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +Модераторы отвечают за порядок в сообществе в целом. Им стоит писать по поводу любых вещей, связанных с правилами и их нарушением, к примеру (список неполный):
Тогда я бы сделал «Модераторы следят за порядком в сообществе». Всё-таки ответственность пассивная, а слежка активная.

2021-01-30 00:25 UTC, UristMcKobold commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +- модерирование профилей (всё, что нарушает правила и находится на странице пользователя).
Можно просто разбить на две части верхнюю строчку: «Им стоит писать по всему, что связано с правилами и их нарушением. Это касается следующих областей в сообществе: чат, форум, комментарии и обсуждение карты, профили».
Или можешь вот такой вариант сделать: 
```suggestion
- беспорядок в чае (спам, оскорбления);
- беспредел на форуме;
- бесчинства в комментариях или обсуждении карты;
- бессовестные профили (всё, что нарушает правила на странице пользователя).
```

2021-01-30 13:37 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +***Примечание: если модератор переступает через правила, злоупотребляет полномочиями или иным образом нарушает профессиональную этику, на него можно пожаловаться в [службу поддержки](/wiki/People/The
```suggestion
***Примечание: если модератор переступает правила, злоупотребляет полномочиями или иным образом нарушает профессиональную этику, на него можно пожаловаться в [службу поддержки](/wiki/People/The_Team/Account_support_team#support@ppy.sh).***\
```

2021-01-30 13:38 UTC, TicClick commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
> +- модерирование профилей (всё, что нарушает правила и находится на странице пользователя).
беспорядок в чае — это когда пакетик рвётся

2021-01-30 13:46 UTC, UristMcKobold approved these changes

2021-01-30 14:46 UTC, TPGPL commented on wiki/People/The_Team/Global_Moderation_Team/ru.md
>    - moderators
```suggestion
  - moderators
  - chat mod
```

2021-01-30 14:47 UTC, TPGPL approved these changes

2021-01-30 14:48 UTC, merged