[RU] Update osu! Installation on Windows
ppy/osu-wiki pull request #4785
Opened 2021-01-16 22:04 UTC by HibanaSama

2021-01-16 22:41 UTC, UristMcKobold requested changes

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +Эта страница расскажет вам, как заставить работать osu! на вашем устройстве под управлением Windows. Также в [osu!academy](/wiki/osu!academy) есть [видеоурок](https://www.youtube.com/watch?v=0V5GwzmM
```suggestion
В этой статье вы можете узнать, как успешно запустить osu! на вашем устройстве под управлением Windows. Также, в [osu!academy](/wiki/osu!academy) есть [видеогайд](https://www.youtube.com/watch?v=0V5GwzmMhpU), объясняющий процесс установки osu! на Windows.
```
Поменял страницу на статью, так как это ближе к русскому языку. "заставить" работать звучит как-то слишком жёстко. "видеоурок" какой-то слишком буквально перевод, чаще слышу про видеогайды.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +- Неплохая видеокарта.
```suggestion
- Подходящая видеокарта.
```
Ну какая там неплохая…

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +1. Откройте [страницу загрузки](https://osu.ppy.sh/home/download) и скачайте установщик.
```suggestion
1. Откройте [эту страницу](https://osu.ppy.sh/home/download) и скачайте установщик.
```
Не говорят же «загрузка», чаще говорят «скачать». Но если поменять загрузку на скачку, то будет повторение во второй части, что не есть хорошо.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +   - Если вы хотите изменить его, нажмите на текст под словом `Привет.` и выберите своё место установки.
```suggestion
   - Если вы хотите изменить его, нажмите на текст под словом `Привет!` и выберите своё место установки.
```
В русском переводе серьёзно точка, а не восклицательный знак, как в оригинале?

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +   - osu! будет установлена в то место после истечения таймера.
```suggestion
   - osu! будет установлена в выбранное место после истечения таймера.
```

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +Если вы используете 64-битную версию Windows 7, у вас могут возникнуть проблемы с правильной установкой osu!. Попробуйте установить 64-битный .NET Framework, в случае, если этой версии нет в комплект
```suggestion
Если вы используете 64-битную версию Windows 7, у вас могут возникнуть проблемы с правильной установкой osu!. Попробуйте установить 64-битный .NET Framework в случае, если этой версии нет в комплекте с установщиком osu!. [Скачать его можно отсюда.](https://download.microsoft.com/download/2/0/e/20e90413-712f-438c-988e-fdaa79a8ac3d/dotnetfx35.exe)
```
Запятую убрал, так как она не нужна. В оригинале точки нет в конце, конечно, а надо бы.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +**Если же установщик показывает ошибки при попытке установки, вы можете попробовать несколько вещей:**
```suggestion
**Если же установщик показывает ошибки при попытке установки, вы можете попробовать следующее:**
```
В данном контексте «вещи» — это жуткий перевод английского things.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +- Попробуйте переустановить .NET Framework на последнюю версию. [Вы можете найти её здесь](https://dotnet.microsoft.com/download)
```suggestion
- Попробуйте переустановить последнюю версию .NET Framework. [Вы можете найти её здесь](https://dotnet.microsoft.com/download)
```
В оригинале нет «на последнюю», есть только "try reinstalling the latest version", то есть попробовать переустановить последнюю версию.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +- Очистите свой ПК. Проверьте его антивирусной программой, очистите реестр. Хорошая программа для очистки системы - CCleaner. Просканируйте ей ваши файлы и ваш реестр. Установщик может прекратить сво
```suggestion
- Почистите свой ПК. Проверьте его антивирусной программой, очистите реестр. Для этого есть хорошая программа - CCleaner. Просканируйте ей ваши файлы и реестр. Установщик может прекратить свою работу, если в реестре остались записи от прошлой копии osu!.
```
«Очистить» слишком тотально звучит, тут лучше помягче слово выбрать. Третье предложение слишком деревянно выглядит с позиции перевода, поменял его. Два раза «ваш» повторять нет необходимости.
Не совсем понял, откуда взялось "которая ранее была в вашей системе", в оригинале "still present on your system", то есть совсем другое. Эту часть можно перевести одним словом «остались».

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +Есть два способа добавить карты: через сайт или через osu!direct (требуется тег [osu!supporter](/wiki/osu!supporter)).
```suggestion
Есть два способа добавить карты в клиент: через сайт или через osu!direct (для последнего потребуется [osu!supporter](/wiki/osu!supporter)).
```
Вот тут ты оставил без изменений про саппорт, а ведь это чуть ли не машинный перевод! Уточнил про клиент, так как слишком странно звучит про просто добавить. Добавить куда? Зачем? В оригинале тоже, конечно, но оставим это на их совести.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +2. Найдите песню, которую вы хотите сыграть.
```suggestion
2. Найдите песню, которую вы хотели бы сыграть.
```
you would like в данном случае не «вы хотите» уж точно.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +3. Нажмите на иконку загрузки, чтобы сохранить набор карт на свой компьютер.
```suggestion
3. Нажмите на иконку загрузки, чтобы скачать карту на свой компьютер.
```
"набор карт" — несущствующий термин. Тут не надо перегружать новичка, оставь просто "карту".

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +4. Найдите и откройте файл с набором карт, у него будет расширение `.osz`.
```suggestion
4. Найдите и откройте файл карты с расширением `.osz`.
```

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +   - В качестве альтернативы, вы можете поместить файл с набором карт в папку `Songs`, которая находится в месте установки osu!.
```suggestion
   - Или же вы можете поместить файл карты в папку `Songs`, которая находится в месте установки osu!.
```
Сократил, так как «в качестве альтернативы» слишком много места занимает, а смысл тот же.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +5. osu! автоматически обработает оставшуюся часть набор карт и выгрузит их для вас.
```suggestion
5. osu! автоматически сделает всё остальное и установит карту.
```
Поменял тут, так как довольно далеко от оригинала ты ушёл.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +   - Если по какой-либо причине вы не видите скачанных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для повторной обработки.
```suggestion
   - Если по какой-либо причине вы не видите установленных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для их повторной обработки.
```
В оригинале нет "скачанных", но там вообще нет наводки. Думаю, имелось скорее установленных, так как отсутствие скачанных карт не связаны с осу, тут скорее вина браузера.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +*Примечание: Чтобы использовать osu!direct, вам нужно иметь тег osu!supporter и интернет-соединение.*
```suggestion
*Примечание: Чтобы использовать osu!direct, вам нужно иметь osu!supporter и соединение с интернетом.*
```
Тут тоже "тег", который не употребляется в русской терминологии осу.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +2. Найдите песню, которую вы хотите сыграть.
```suggestion
2. Найдите песню, которую вы хотели бы сыграть.
```

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +   - Если вы не хотите скачивать видео, которое идёт вместе с набором карт, нажмите вместо этого - `DL NoVideo`.
```suggestion
   - Если вы не хотите скачивать видео, которое идёт вместе с картой, нажмите вместо этого `DL NoVideo`.
```
Тире лишнее, к слову.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +4. Когда osu! закончит скачивать набор карт, она автоматически выгрузит его.
```suggestion
4. Карта автоматически установится после того, как osu! её скачает.
```
Переписал, чтобы лучше звучало.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +   - Если по какой-либо причине вы не видите скачанных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для повторной обработки.
```suggestion
   - Если по какой-либо причине вы не видите установленных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для их повторной обработки.
```

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +1. Перейдите на [форум по скинам](https://osu.ppy.sh/community/forums/15) и найдите скин, который вам понравится.
```suggestion
1. Зайдите на [подфорум скинов](https://osu.ppy.sh/community/forums/15) и найдите скин, который вам понравится.
```
Поправил словосочетание, именно так говорят.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +3. В зависимости от того, как создатель запаковал свой скин, вам придётся делать разные вещи.
```suggestion
3. В зависимости от того, как создатель запаковал свой скин, вам может потребоваться попробовать разные методы.
```
Тут тоже «вещи» — это слишком грубый перевод things.

2021-01-16 22:41 UTC, UristMcKobold commented on wiki/Installation/ru.md
> +   - Если скин сжат (используя `.7z`, `.rar`, `.zip` и т.д.):
```suggestion
   - Если скин сжат (используя `.7z`, `.rar`, `.zip` и т. д.):
```
Вообще-то пробел нужен.

2021-01-17 00:50 UTC, TicClick requested changes

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +В этой статье вы можете узнать, как успешно запустить osu! на вашем устройстве под управлением Windows. Также, в [osu!academy](/wiki/osu!academy) есть [видеогайд](https://www.youtube.com/watch?v=0V5G
```suggestion
В этой статье вы узнаете, как запустить osu! на устройстве под управлением Windows. Кроме того, в [osu!academy](/wiki/osu!academy) есть [видеогайд](https://www.youtube.com/watch?v=0V5GwzmMhpU), объясняющий процесс установки osu! на Windows.
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +- Подходящая видеокарта.
```suggestion
- .NET framework 4+ (предлагается установщиком osu!, но также можно взять [с сайта Microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=48130 "Microsoft"))
- Хорошая видеокарта.
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +1. Откройте [эту страницу](https://osu.ppy.sh/home/download) и скачайте установщик.
```suggestion
1. Скачайте установщик со [страницы загрузки](https://osu.ppy.sh/home/download).
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +5. osu! предложит вам войти в аккаунт или зарегистрироваться.
```suggestion
3. В течение 10 секунд после запуска можно поменять путь установки osu!.
   - Чтобы это сделать, нажмите на текст под словом `Привет.` и выберите желаемое место установки.
   - Когда 10 секунд пройдут, osu! будет установлена по выбранному пути.
4. После завершения установки osu! сразу же запустится и скачает несколько начальных карт через osu!direct.
5. osu! предложит вам войти в аккаунт или зарегистрироваться.
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +- Почистите свой ПК. Проверьте его антивирусной программой, очистите реестр. Для этого есть хорошая программа - CCleaner. Просканируйте ей ваши файлы и реестр. Установщик может прекратить свою работу
более полные и правильные предложения
```suggestion
При использовании 64-битной версию Windows 7 у вас могут возникнуть проблемы с правильной установкой osu!. Попробуйте установить [64-битную версию .NET Framework](https://download.microsoft.com/download/2/0/e/20e90413-712f-438c-988e-fdaa79a8ac3d/dotnetfx35.exe "Microsoft") в случае, если этой версии нет в комплекте с установщиком osu!.

---

**Если установщик показывает ошибки, можно попробовать следующее:**

- Переустановите последнюю версию .NET Framework (её можно скачать со [страницы загрузок Microsoft](https://dotnet.microsoft.com/download "Microsoft")).
- Почистите свой ПК: проверьте его антивирусной программой, очистите реестр. Для этого может подойти, к примеру, CCleaner: просканируйте им жёсткий диск и реестр. Установщик может прекратить свою работу, если в реестре остались записи от прошлой копии osu!.
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +Есть два способа добавить карты в клиент: через сайт или через osu!direct (для последнего потребуется [osu!supporter](/wiki/osu!supporter)).
```suggestion
Есть два способа добавить карты в osu!: скачать их с сайта или через osu!direct (для последнего потребуется [osu!supporter](/wiki/osu!supporter)).
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +   - Если по какой-либо причине вы не видите установленных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для их повторной обработки.
```suggestion
1. Откройте [страницу со списком карт](https://osu.ppy.sh/beatmapsets) и войдите в свой аккаунт.
2. Найдите песню, которую вы хотели бы сыграть.
3. Нажмите на иконку загрузки, чтобы скачать карту на свой компьютер.
4. Найдите и откройте файл карты с расширением `.osz`.
   - Скачанную карту также можно переместить в папку `Songs`, которая находится в месте установки osu!.
5. osu! автоматически сделает всё остальное и установит карту.
   - Если по какой-то причине вы не видите установленных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для их повторной обработки.
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +*Примечание: Чтобы использовать osu!direct, вам нужно иметь osu!supporter и соединение с интернетом.*
```suggestion
*Примечание: чтобы использовать osu!direct, понадобится osu!supporter и подключание к интернету.*
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +   - Если по какой-либо причине вы не видите установленных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для их повторной обработки.
```suggestion
1. Откройте osu! и нажмите на кнопку `osu!direct` в правой части главного меню.
2. Найдите песню, которую вы хотели бы сыграть.
3. Кликните два раза по песне в списке или нажмите на кнопку `Download` справа, чтобы скачать её.
   - Если вы не хотите скачивать видео, которое идёт вместе с картой, нажмите вместо этого на кнопку `DL NoVideo`.
4. Карта автоматически установится после скачивания.
   - Если по какой-то причине вы не видите установленных карт, нажмите `F5` на [экране выбора песен](/wiki/Interface#song-selection-screen) для их повторной обработки.
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
>  2. Как только найдёте скин, скачайте его.
давай это тоже переформулируем, что-нибудь типа «Скачайте понравившийся скин» (вторую часть первого пункта тогда можно удалить, всю после ссылки), а то глупо звучит

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
> +3. В зависимости от того, как создатель запаковал свой скин, вам может потребоваться попробовать разные методы.
```suggestion
3. Распакуйте скин с помощью одного из способов ниже.
```

2021-01-17 00:50 UTC, TicClick commented on wiki/Installation/ru.md
>       1. Распакуйте его.
вот это тоже коряво переведено, надо исправить

2021-01-17 16:16 UTC, TicClick approved these changes

2021-01-17 16:16 UTC, merged