[RU] Song Content Rules
ppy/osu-wiki pull request #4809
Opened 2021-01-19 15:53 UTC by GoodbyeShin

adding Russian translation of the article

2021-01-19 16:09 UTC, HibanaSama commented on wiki/Rules/Song_Content_Rules/ru.md
> +Прежде чем загружать ваш трек, убедитесь, что он соответствует вышеперечисленным критериям. Если вы в чём-то не уверены, спросите совета у члена группы оценки номинаций ([NAT](/wiki/ru/People/The_Tea
```suggestion
Прежде чем загружать ваш трек, убедитесь, что он соответствует вышеперечисленным критериям. Если вы в чём-то не уверены, спросите совета у члена группы оценки номинаций ([NAT](/wiki/ru/People/The_Team/Nomination_Assessment_Team)) или команды модерации osu! ([GMT](/wiki/ru/People/The_Team/Global_Moderation_Team)).
```
лишний пробел

2021-01-21 21:31 UTC, TicClick requested changes
ну Шин, блин, у тебя хорошие предложения с ужасно раздутыми и странными чередуются (а иногда вторые идут прямо подряд), почему так? ты же так не разговариваешь, или разговариваешь?

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +- Упоминание наркотических веществ и их злоупотребления, а также обсуждение подобного контента или его поощрение. Кроме того, тексты, глубоко затрагивающие тематику убийств, суицида и [селфхарма](htt
можно просто «употребления», **кроме того**, у тебя второе предложение не связано с первым (а ещё тут нужно проставить подпись к ссылке: `[blah](http://blah.com "Wikipedia")`)

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +- Пропаганда расовой сегрегации или социальной напряжённости в целом
так-так, в оригинале оба пункта только про расу

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +- Невыносимо громкие, резкие звуки и треки, состоящие из беспорядочно склеенных кусков
excessively clipped — это не беспорядочно склеенные куски, а когда у тебя аудиоволна жёстко обрезается до какого-то значения, и там появляется [треск, блипы, хрипение и прочие искажения (на 0:09)](https://www.youtube.com/watch?v=SXptusF7Puo)

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Тем не менее, существует исключение: запрещается использовать в качестве превью к карте часть песни или её куплет, содержащие мат. Также обязательно отметьте наличие чувствительного контента в описан
во-первых, в другом порядке, во-вторых, речь применительно к превью не только про мат, а и про 18+ тоже

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +В разумных пределах разрешается загружать музыкальные треки, содержащие откровенную лирику, если они не нарушают вышеперечисленные критерии.
откровенную лирику и мат!

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Разумеется, то, что приемлемо для одних, может быть совсем неприятно другим.
во-*первых*, первое слово нужно выкинуть, во-вторых, указательными местоимениями не обойтись: для одних **людей**

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +В процессе оценки трека, воспользуйтесь **правилом 20%**. Скорее всего, ваш контент сочтут непригодным для osu!, если более 20% текста ссылается на материалы откровенного или сомнительного характера.
вот тут насчёт «описывает» не уверен, нужен глагол получше. но в целом сокращение предложения очень необходимо
```suggestion
При оценке трека пользуйтесь **правилом 20%**: скорее всего, песня не подойдёт для osu!, если более 20% текста в ней описывает темы из начала статьи.
```

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Стоит понимать, что строго соблюдать это правило не нужно — оно существует лишь как способ помочь вам с выбором в той или иной ситуации.
заметка: хуёво, что при переводе guideline превратилось в правило, конечно, вот тут это и вылезло
```suggestion
Стоит понимать, что строго соблюдать это правило не нужно: оно существует лишь для помощи в выборе в той или иной ситуации.
```

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Многие артисты в своих произведениях используют нецензурную лексику в художественных и стилистических целях и, хотя формально мат не запрещён, не допускаются чрезмерно пошлые треки, а также запрещено
перед «и» лучше точку поставить, целее будет. про закон, ненависть и прочее — чистая отсебятина, в оригинале же про шок-контент в целом

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Прежде чем загружать ваш трек, убедитесь, что он соответствует вышеперечисленным требованиям. Если вы в чём-то не уверены, спросите совета у члена группы оценки номинаций ([NAT](/wiki/ru/People/The_T
напоминание: трек -> песня по всей статье
```suggestion
Прежде чем загружать трек, убедитесь, что он соответствует вышеперечисленным требованиям. Если вы в чём-то не уверены, спросите совета у члена [группы оценки номинаций (NAT)](/wiki/People/The_Team/Nomination_Assessment_Team) или [у модератора (GMT)](/wiki/People/The_Team/Global_Moderation_Team)).
```

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +## Всё, что затрагивает политику
здесь же отсылка к последнему пункту списка в начале
```suggestion
## Что такое излишне политизированный контент?
```

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +В соответствии с **правилом сообщества №3**, контент, который руководство osu! посчитает излишне политизированным, запрещён.
ты тут ссылку на правила потерял, и вместо «руководства» я бы пользовался термином «команда»

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Не создавайте проблем себе и другим, какие-то определённые политические взгляды держите при себе — поймите, osu! далека от политики. Наслаждайтесь игрой и не мешайте отдыхать остальным.
без непрошенных советов лучше
```suggestion
osu!, её команда и сообщество далеки от политики. Наслаждайтесь игрой и не мешайте отдыхать остальным.
```

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +## Что случится, если мою заявку с треком отклонят?
скорее так
```suggestion
## Что случится, если песня не подходит для osu!?
```

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +В каждом таком случае вам предоставят объяснение с указанием причины удаления. Обычно за это отвечают ребята из команды оценки номинаций (NAT) или команды модерации osu! (GMT).
remember, no `ребята` (а ещё, во-первых, можно упростить, а во-вторых, возьми про GMT формулировку чуть выше из моего предложения)

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Если вы уверены в своей правоте и хотели бы оспорить это решение, во-первых, напишите личное сообщение модератору и изложите суть претензии. Кроме того, можно попросить других игроков поддержать вашу
второе предложение — не про игроков, а про то, что можно других GMT/NAT попросить, а не только одного человека

ну и да, *консенсусное голосование* как термин, может, и существует, но здесь это будет просто голосованием (и да, «текущих» — лишнее, иначе бы они не были в NAT)

2021-01-21 21:31 UTC, TicClick commented on wiki/Rules/Song_Content_Rules/ru.md
> +Поскольку данное правило носит довольно неопределённый характер, каждому пользователю даётся **один шанс избежать наказания** (за исключением серьёзных нарушений). Не пытайтесь повторно загрузить зап
```suggestion
Поскольку данное правило носит довольно неопределённый характер, каждому пользователю даётся **одно право на ошибку** (за исключением серьёзных нарушений). Не пытайтесь повторно загрузить запрещённые треки — их всё равно удалят, а нарушители будут наказаны минимум на 42 часа.
```

2021-01-23 19:40 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +Стоит понимать, что строго соблюдать это правило не нужно — оно существует лишь как способ помочь вам с выбором в той или иной ситуации.
на что по-твоему его заменить? или всё снести и оставить только англицизм? в русском варианте нормально звучит "правило 20-ти процентов"

2021-01-23 19:41 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +Многие артисты в своих произведениях используют нецензурную лексику в художественных и стилистических целях и, хотя формально мат не запрещён, не допускаются чрезмерно пошлые треки, а также запрещено
честно говоря, изначально текст написан скудно, пришлось подключать воображение

2021-01-23 19:43 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +Прежде чем загружать ваш трек, убедитесь, что он соответствует вышеперечисленным требованиям. Если вы в чём-то не уверены, спросите совета у члена группы оценки номинаций ([NAT](/wiki/ru/People/The_T
это довольно странное замечание, поскольку правила покрывают далеко не только "песни", а наполнение и музыку в целом, в принципе, я не против все "треки" заменить на "песни" (в том числе и заголовок)

2021-01-23 19:47 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +Если вы уверены в своей правоте и хотели бы оспорить это решение, во-первых, напишите личное сообщение модератору и изложите суть претензии. Кроме того, можно попросить других игроков поддержать вашу
"не про игроков, а про то, что можно других GMT/NAT попросить"
проглядел этот момент, исправлю
"консенсусное голосование как термин, может, и существует, но здесь это будет просто голосованием"
пусть так

2021-01-23 19:51 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +В процессе оценки трека, воспользуйтесь **правилом 20%**. Скорее всего, ваш контент сочтут непригодным для osu!, если более 20% текста ссылается на материалы откровенного или сомнительного характера.
Вариант "темы из начала статьи", честно говоря, мне не нравится. Надо бы переписать

2021-01-23 19:51 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +Тем не менее, существует исключение: запрещается использовать в качестве превью к карте часть песни или её куплет, содержащие мат. Также обязательно отметьте наличие чувствительного контента в описан
перепишу данное предложение

2021-01-23 19:53 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +- Невыносимо громкие, резкие звуки и треки, состоящие из беспорядочно склеенных кусков
у меня были сомнения в переводе данной фразы, теперь понятно почему

2021-01-23 19:54 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +Современная музыка отличается огромным разнообразием жанров, и большинство музыкальных треков без проблем подойдут для osu!, но кое-что загружать всё же не стоит, а именно:
понял, перепишу этот вариант

2021-01-30 18:16 UTC, UristMcKobold requested changes

2021-01-30 18:16 UTC, UristMcKobold commented on wiki/Rules/Song_Content_Rules/ru.md
> +В соответствии с [**правилом сообщества №3**](wiki/Rules#правила-сообщества), контент, который команда osu! посчитает излишне политизированным, запрещён.
```suggestion
Чтобы уберечь простую ритм-игру от политики и в соответствии с [**правилом сообщества №3**](wiki/Rules#правила-сообщества), если команда osu! посчитает контент излишне политизированным, то он будет запрещён.
```
Тут структура не самая удачная. Слово 1, длинное объяснение, слово 2. А ещё ты пропустил важный тезис из оригинала.

2021-01-30 18:16 UTC, UristMcKobold commented on wiki/Rules/Song_Content_Rules/ru.md
> +## Что случится, если песня не подходит для osu!?
```suggestion
## Что случится, если выбранная мной песня недопустима для использования в osu!?
```
«не подходит» как-то слишком технически звучит, даже в контексте этой статьи. А ещё пропустил «*my* track». Немного длинно получилось у меня, но зато понятно.

2021-01-30 18:16 UTC, UristMcKobold commented on wiki/Rules/Song_Content_Rules/ru.md
> +С сайта будет удалена любая карта, содержащая запрещённый музыкальный трек.
```suggestion
С сайта будет удалена любая карта, содержащая запрещённый музыкальный трек.
```
А вот тут использование «музыкальный трек» уместно, так как тут более техническая сторона вопроса затрагивается.

2021-01-30 18:16 UTC, UristMcKobold commented on wiki/Rules/Song_Content_Rules/ru.md
> +В каждом таком случае вам предоставят объяснение с указанием причины удаления. Обычно за это отвечают члены команды оценки номинаций (NAT) или модераторы (GMT).
```suggestion
В каждом таком случае вам предоставят объяснение с указанием причины удаления. За это отвечают члены команды оценки номинаций (NAT) и модераторы (GMT).
```
В оригинале нет «обычно», по своему опыту тоже могу сказать, что это лежит на плечах ГМТ/НАТ. И тут не или, обе команды за это отвечают.

2021-02-01 15:16 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +- Излишне политизированный контент
Так, с пунктуацией согласен, кажется, кто-то намудрил с ASC.
Эм, теперь будем переписывать все непонятные слова? Весьма сомнительно.

2021-02-01 15:21 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +В разумных пределах разрешается загружать песни, содержащие откровенную лирику и мат, если они не нарушают вышеперечисленные критерии.
Непонятно, как можно "немного нарушить" затронутую тему сегрегации. А вариант-то неплохой предложен.

2021-02-01 15:26 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +Обязательно отметьте наличие чувствительного контента в описании к мапсету. Также существует исключение: запрещается использовать в качестве превью к карте часть песни или её куплет, содержащие мат и
Суть претензии ясна, но «может иметь» — это что-то не то, надо бы переписать. Насчёт контента согласен.

2021-02-01 21:21 UTC, GoodbyeShin commented on wiki/Rules/Song_Content_Rules/ru.md
> +При оценке трека пользуйтесь **правилом 20%**: скорее всего, песня не подойдёт для osu!, если более 20% текста в ней затрагивает откровенные темы, упомянутые выше.
Да, только повтор песни нужно убрать.

2021-02-11 22:05 UTC, TicClick commented
давай это отложим, пока #4942 не будет влит, чтобы не делать двойную работу

2021-03-05 20:26 UTC, TicClick commented
уже можно возвращаться

2021-03-11 15:50 UTC, TicClick commented
as of now, it's outdated and has too many comments that are now irrelevant. please make a new pull request once you're back in business

2021-03-11 15:50 UTC, closed without merging