Link to a list of important skinning guides and threads from Guides; update the Russian translation of Guides
ppy/osu-wiki pull request #4819
Opened 2021-01-20 18:08 UTC by TicClick

2021-01-20 18:34 UTC, UristMcKobold requested changes

2021-01-20 18:34 UTC, UristMcKobold commented on wiki/Guides/ru.md
> +Здесь приведён список руководств за авторством разных игроков osu!. Большинство из этих статей были сперва опубликованы на форуме osu! в отдельных темах, а затем викифицированы.
```suggestion
Здесь приведён список руководств за авторством разных игроков osu!. Большинство из этих статей было сперва опубликовано в отдельных темах на форуме osu!, а затем викифицировано.
```
Большинство было. "в отдельных темах" пораньше, чтобы не сбивать фокус из-за восклицательного знака, плюс так читается более приятно.

2021-01-20 18:37 UTC, UristMcKobold approved these changes
Russian part of the PR looks good to go.

2021-01-20 19:21 UTC, RockRoller01 commented
I forgot to mention this when I talked to you yesterday, but "How to make properly centered spinners" is in both places. The /Guides page links to the ported wiki article, while the "Guide and Important Threads" article links to the original forum post.
The link to the forum post should probably be removed and all 3 guides on /Guides should be moved to "Guide and Important Threads" as the information is currently spread in 2 different places.

2021-01-20 19:27 UTC, TicClick commented
for now, I've made `Skinning/Guides and important threads` refer to the wiki pages where possible.

ideally -- as I see it -- this article should disappear in favor of `Guides#Skinning` acting as a starting point (with the project links moved to https://github.com/ppy/osu-wiki/blob/master/wiki/Projects/en.md, because some links are already there)

2021-01-20 19:36 UTC, RockRoller01 commented
Oh sorry, I have somehow overlooked the changes done to "Skinning/Guides and important threads", which are exactly what I said.

2021-01-21 18:04 UTC, Joehuu approved these changes

2021-01-21 18:04 UTC, merged