[ZH] Add osu file formats
ppy/osu-wiki pull request #4824
Opened 2021-01-21 12:35 UTC by PercyDan54

Finished rebasing my repo of #4223. I was a noob using git back then.

2021-01-21 12:40 UTC, TicClick commented
cool. does [kj415j45's comment](https://github.com/ppy/osu-wiki/pull/4223#pullrequestreview-511033198) mean the approval?

2021-01-21 12:42 UTC, PercyDan54 commented
> cool. does [kj415j45's comment](https://github.com/ppy/osu-wiki/pull/4223#pullrequestreview-511033198) mean the approval?

Nope. He means he's busy and can't review now.

2021-01-21 12:42 UTC, TicClick requested changes

2021-01-21 12:42 UTC, TicClick commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| ULEB128 | 可变 | 整数; 见[此处](https://en.wikipedia.org/wiki/LEB128) |
```suggestion
| ULEB128 | 可变 | 整数; 见[此处](https://en.wikipedia.org/wiki/LEB128 "Wikipedia") |
```

2021-01-21 12:42 UTC, TicClick commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| String | 可变 | 分为三部分：一个单独的字节，可能为 0x00，表示接下来两个部分不存在，或 0x0b（十进制 11），表示下面两个部分存在。若为 0x0b，第二部分将有一个 ULEB128，表示第三部分的字符串字节长度，然后是字符串本身，经 UTF-8 编码。见 [此处](https://en.wikipedia.org/wiki/UTF-8)。 |
```suggestion
| String | 可变 | 分为三部分：一个单独的字节，可能为 0x00，表示接下来两个部分不存在，或 0x0b（十进制 11），表示下面两个部分存在。若为 0x0b，第二部分将有一个 ULEB128，表示第三部分的字符串字节长度，然后是字符串本身，经 UTF-8 编码。见 [此处](https://en.wikipedia.org/wiki/UTF-8 "Wikipedia")。 |
```

2021-01-21 12:42 UTC, TicClick commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +| DateTime | 8 | 一个代表日期和时间的 64 位刻。刻是从 UTC 时间 1 年 1 月 1 日午夜 0 点开始的 100 纳秒间隔量。 详见 [.NET Framework 关于刻的文档](https://docs.microsoft.com/zh-cn/dotnet/api/system.datetime.ticks?view=netframework-4.7.2)。 |
```suggestion
| DateTime | 8 | 一个代表日期和时间的 64 位刻。刻是从 UTC 时间 1 年 1 月 1 日午夜 0 点开始的 100 纳秒间隔量。 详见 [.NET Framework 关于刻的文档](https://docs.microsoft.com/zh-cn/dotnet/api/system.datetime.ticks?view=netframework-4.7.2 "Microsoft Docs")。 |
```

2021-01-21 12:50 UTC, TicClick commented
alright. do you want to wait for someone to pick this up within 2 weeks, or should I consider that these 2 weeks have passed (because #4223 was sitting there for the whole time)

2021-01-21 13:04 UTC, PercyDan54 commented
> alright. do you want to wait for someone to pick this up within 2 weeks, or should I consider that these 2 weeks have passed (because #4223 was sitting there for the whole time) and merge this right away?

I think I might want to wait for a while.

2021-01-21 13:48 UTC, TicClick commented
that's totally alright, it's your feature branch after all

2021-01-25 17:14 UTC, Kotoki1337 reviewed
中英之前要不要加下空格format一下

2021-01-25 17:14 UTC, Kotoki1337 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +### osu!.db format
这里是没翻还是要保留原文？

2021-01-27 14:06 UTC, PercyDan54 commented on wiki/osu!_File_Formats/Db_(file_format)/zh.md
> +### osu!.db format
漏了

2021-02-03 11:59 UTC, Kotoki1337 approved these changes

2021-02-03 12:47 UTC, TicClick approved these changes

2021-02-03 12:47 UTC, merged