[RU] Update BanchoBot
ppy/osu-wiki pull request #4869
Opened 2021-01-29 20:18 UTC by TicClick

2021-01-29 21:00 UTC, atimonder1 requested changes

2021-01-29 21:00 UTC, atimonder1 commented on wiki/BanchoBot/ru.md
> +*У этого термина существуют и другие значения, см [Bancho (значения)](/wiki/Disambiguation/Bancho).*
```suggestion
*У этого термина существуют также и другие значения, см [Bancho (значения)](/wiki/Disambiguation/Bancho).*
```

2021-01-29 21:00 UTC, atimonder1 commented on wiki/BanchoBot/ru.md
> +Команда `!report` отправляет [глобальным модераторам](/wiki/People/The_Team/Global_Moderation_Team) жалобу о неподобающем поведении игрока.. Если ник пользователя содержит пробелы, замените их на под
```suggestion
Команда `!report` отправляет [глобальным модераторам](/wiki/People/The_Team/Global_Moderation_Team) жалобу о неподобающем поведении игрока.. Если ник пользователя содержит пробелы, замените их на подчёркивания - например, `really cool username` станет `really_cool_username`. Чтобы пожаловаться на действия модератора, свяжитесь со [службой поддержки](/wiki/People/The_Team/Account_support_team#support@ppy.sh). Ниже показан пример репорта на обычного пользователя:
```

2021-01-30 12:08 UTC, atimonder1 approved these changes

2021-01-30 15:50 UTC, TPGPL approved these changes

2021-01-30 15:50 UTC, merged