[RU] Update NAT
ppy/osu-wiki pull request #4870
Opened 2021-01-29 20:19 UTC by TicClick

2021-01-29 20:49 UTC, UristMcKobold requested changes

2021-01-29 20:49 UTC, UristMcKobold commented on wiki/People/The_Team/Nomination_Assessment_Team/ru.md
> +***Примечание: если член NAT нарушает правила, злоупотребляет полномочиями или иным образом нарушает кодекс профессиональной этики, на него можно пожаловаться в [службу поддержки](/wiki/People/The_Te
```suggestion
***Примечание: если член NAT переступает через правила, злоупотребляет полномочиями или иным образом нарушает профессиональную этику, на него можно пожаловаться в [службу поддержки](/wiki/People/The_Team/Account_support_team#support@ppy.sh).***
```
Кодекс — лишнее, потому что можно успешно нарушать этику, эти два слова тут взаимозаменяемы.
А ещё тут два раза «нарушать». Я не уверен, устроит ли тебя мой вариант, но что-то с этим делать надо!

2021-01-29 23:20 UTC, UristMcKobold approved these changes

2021-01-30 07:37 UTC, GoodbyeShin commented on wiki/People/The_Team/Nomination_Assessment_Team/ru.md
> +***Примечание: если член NAT переступает через правила, злоупотребляет полномочиями или иным образом нарушает профессиональную этику, на него можно пожаловаться в [службу поддержки](/wiki/People/The_
```suggestion
***Примечание: если член NAT переступает правила, злоупотребляет полномочиями или иным образом нарушает профессиональную этику, на него можно пожаловаться в [службу поддержки](/wiki/People/The_Team/Account_support_team#support@ppy.sh).***
```
неплохой вариант, но в таком случае слово "через" лишнее

2021-01-30 13:36 UTC, TicClick commented on wiki/People/The_Team/Nomination_Assessment_Team/ru.md
> +***Примечание: если член NAT переступает через правила, злоупотребляет полномочиями или иным образом нарушает профессиональную этику, на него можно пожаловаться в [службу поддержки](/wiki/People/The_
таки да

2021-01-30 14:58 UTC, TPGPL approved these changes

2021-01-30 14:58 UTC, merged