Add Modding Mentorship: Cycle 2 Signups newspost
ppy/osu-wiki pull request #4907
Opened 2021-02-04 07:33 UTC by venix12

we have no banner, not sure if we can go live without one 🤔 
deadlines need to be readjusted depending on when the post goes live

2021-02-04 07:55 UTC, zeusminus commented
> we have no banner, not sure if we can go live without one 🤔 
why don't you use the one used for the previous mentorship newsposts?

![community-mentorship-program.jpg](https://user-images.githubusercontent.com/52823712/106861857-65643580-66d7-11eb-9501-46ed3b6e5e90.jpg)

2021-02-04 08:02 UTC, venix12 commented
this is CMP banner, modding mentorship is a different thing so don't think that works well

2021-02-04 10:43 UTC, Ephemeralis commented
your options are:

- cajole a designer into making a newsbanner that someone from news-approval (me or peppy) signs off on
- use the generic media banner (same one used in contest page headers for the MBCs, etc)

2021-02-04 15:09 UTC, venix12 commented
hmm, see no harm in going with the generic banner i guess

2021-02-04 16:23 UTC, zeusminus requested changes
There isn't much to suggest, nonetheless skimmed through the article as best as I can. However, you seem to have forgotten to add `.md` extension after the filename, thus the contents were parsed as plain text.

2021-02-04 16:23 UTC, zeusminus commented on news/2021-02-04-modding-mentorship-cycle-2-signups-now-open
> +The Modding Mentorship is a place where new and promising modders of each gamemode can improve their modding skills under the supervision of pre-selected pool of modding experts serving as mentors.
```suggestion
The Modding Mentorship is a place where new and promising modders of each gamemode can improve their modding skills under the supervision of a pre-selected pool of modding experts serving as mentors.
```

2021-02-04 16:23 UTC, zeusminus commented on news/2021-02-04-modding-mentorship-cycle-2-signups-now-open
> +If you believe you've got what it takes to teach a new generation of modders, don't hesitate, and try yourself as a mentor! [The information thread](https://osu.ppy.sh/community/forums/topics/1218245
```suggestion
If you believe you've got what it takes to teach a new generation of modders, don't hesitate and try yourself as a mentor! [The information thread](https://osu.ppy.sh/community/forums/topics/1218245) will guide you on how to apply right away! If you are just taking your first steps in the modding community, though, consider applying as a mentee!
```

2021-02-04 16:23 UTC, zeusminus commented on news/2021-02-04-modding-mentorship-cycle-2-signups-now-open
> +- Mentee signups will open on **18th February, 2021** and close on **25th February**
```suggestion
For this cycle, the application deadlines will go as follows:
- Mentor signups will be open until **February 18, 2021**
- Mentee signups will open on **February 18, 2021** and close on **February 25**
```
these are the correct date & time formatting according to the [Article Styling Criteria](https://osu.ppy.sh/wiki/en/Article_styling_criteria/Writing#date-and-time)

2021-02-04 16:23 UTC, zeusminus commented on news/2021-02-04-modding-mentorship-cycle-2-signups-now-open
> +Greetings, modders! With the new year starting, we want to announce the second run of Modding Mentorship! If you ever wanted to polish your modding abilities or assist newer members of modding commun
```suggestion
Greetings, modders! With the new year starting, we want to announce the second run of Modding Mentorship! If you ever wanted to polish your modding abilities or assist novice modders in their way to achieving the needed modding skills, this is your time to shine!
```
the sentence sounds a little weird when read carefully, you might want to simplify it the way I suggested

2021-02-24 06:58 UTC, Ephemeralis commented
this sort of fell into the ether, will it still be relevant after a redate? @venix12

2021-03-03 19:47 UTC, venix12 commented
yes

2021-03-04 04:23 UTC, Ephemeralis commented
rejuggle the dates around to whatever fits and ping/dm me on Discord and we can slot this in on any date that isn't Wed/Sat

2021-03-29 12:10 UTC, TicClick commented
today isn't Wed/Sat

2021-07-20 15:35 UTC, closed without merging