[TR] Add Game Mode osu!
ppy/osu-wiki pull request #4925
Opened 2021-02-08 13:19 UTC by Drops-P

a

2021-02-11 18:51 UTC, zeusminus requested changes
Maalesef düzeltilmesi gereken çok yer var, yine de emeklerin ve katkıların için teşekkürler! Aşağıda dikkat etmen gereken şeyleri üstünkörü bir biçimde listeliyorum:
- "Beatmap" sözcüğü bir oyun terimi olduğundan çevirilmemesi gerekmektedir, sitede de olduğu gibi.
- Aynı makale içerisinde çeşitli tutarsızlıklar farkettim. Kimi yerde "vuruş objesi" kullanmışsın, kimi yerde ise "vurulan nesneler".
- Başlık altında italik yazılan *wikisel* ifadelerde tutarlı olmak adına çevirisi mevcut diğer makalelere göz gezdir. Aynısı yine terimsel ifadeler için de geçerli.
- Çeviriyi orijinal makalenin formatına uygun bir biçimde kaleme almalısın. Noktalama işaretlerine, büyük-küçük harf kullanımına dikkat etmelisin.

Çeviri işlemini tamamladıktan sonra bir self-proofread uygulasan bunları kendin de farkedeceksin aslında. Kısacası daha ihtiyatlı bir çaba gösterirsen çok memnun olurum, aksi halde ben gözden geçirip tek tek düzeltmek zorunda kalıyorum. :(

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Slider topunun başarılı şekilde slider dönüşüne değmesi.
```suggestion
- Slider topunun başarılı şekilde sliderın sonuna veya ters okuna değmesi.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Spinner dairesi tatmin edici bir boyuta getirememek.
```suggestion
- Spinner dairesini tatmin edici bir boyuta getirememek.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +  - v1 tema davranışı: Spinner ölçüsünün en az  yarısını dolduramamak.
```suggestion
  - v1 tema davranışı: Spinner ölçüsünün en az yarısını dolduramamak.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Slider çubuğu sliderın sonuna veya ters okuna başarıyla dokunmuşsa (slider tiklerinin sonunda daha iyi değerlendirme, daha çok can kazanımına yok açar).
```suggestion
- Slider topunun sliderın sonuna veya ters okuna başarıyla dokunması (slider tiklerinin sonunda daha iyi değerlendirme, daha çok can kazanımına yok açar).
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Bir slider tiki veya slider dönüşü ıskalamak.
```suggestion
- Bir slider tiki veya slider ters oku ıskalamak.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +*Ayrıntılı bilgi için [osu!nun Skinning sayfasına](/wiki/Skinning/osu!) bakın*
```suggestion
*Bilgi için [osu!'nun Tema oluşturma sayfasına](/wiki/Skinning/osu!) bakın.*
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +*Tüm bilgiler için [Beatmapping sayfasına](/wiki/Beatmapping) bakın.*
```suggestion
*Bilgi için [Beatmap oluşturma sayfasına](/wiki/Beatmapping) bakın.*
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +## Önemsiz şeyler
```suggestion
## Ek bilgiler
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +![osu! duman ayarları](/wiki/shared/osu_smoke_set.jpg "Tuş Bağlamalarda Duman")
```suggestion
![osu! duman ayarları](/wiki/shared/osu_smoke_set.jpg "Tuş seçeneklerinde duman")
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Slider topunun, gizli veya görünür kaydırma çizgileri olmadan boş slider yolunda serbest bırakılması, kombo kırılmasına ya da  herhangi bir puan verilmesine neden olmaz. Slider değerlendirmesi sade
```suggestion
- Slider topunun, gizli veya görünür kaydırma çizgileri olmadan boş slider yolunda serbest bırakılması, kombo kırılmasına ya da herhangi bir puan verilememesine neden olmaz. Slider değerlendirmesi sadece çemberin tıklanıp tıklanmadığını, slider tikinin alınıp alınmadığını, ve bitiş çemberinin başarılı bitirilip bitirilmediğini kontrol eder.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Spinnerı döndürürken döndürme yönünü değiştirmek spinnerın yavaşlamasına sebep olur. (dakika başına çevirme, döndürme oryantasyonunu sıfırlamak için 0'a iner) Sonrasında doğru yöne doğru çevrilir.
```suggestion
- Spinnerı döndürürken döndürme yönünü değiştirmek spinnerın yavaşlamasına sebep olur (dakika başına çevirme, döndürme oryantasyonunu sıfırlamak için 0'a iner), ardından doğru yöne doğru dönmeye başlar. Yeniden yönlendirme sırasında dönüş ilerlemesi kaybedilmez (ancak artmaz da), ve ters dönüşte artmaya devam eder.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Spinnerı merkezinin etrafında döndürmemek geçerli dönüş **sayılmayaz**.
```suggestion
- Spinnerı merkezinin etrafında döndürmemek geçerli bir dönüş **sayılmaz**.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- osu!nun maskotu [pippi](/wiki/Mascots#-pippi)dir.
```suggestion
- [pippi](/wiki/Mascots#-pippi), osu! modunun maskotudur.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- osu!nun eski versiyonu, değiştirilmeden veya kaldırılmadan önce *ouendan* serisindeki bazı özellikleri taklit ederdi.
```suggestion
- osu!'nun eski versiyonu, değiştirilmeden veya kaldırılmadan önce *ouendan* serisindeki bazı özellikleri taklit ederdi.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +  - Yeni kombo dönüm noktalarına gelindiğinde Kombo Alevinin çıkması.
```suggestion
  - Yeni kombo eşiklerine ulaşıldığında kombo alevinin çıkması.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +    - Performans sorunları nedeniyle 05 Mart 2013'te (2013-03-05) kaldırıldı.
```suggestion
    - Performans sorunları nedeniyle 05 Mart 2013'te kaldırıldı.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +  - v1 tema özelliklerini kullanan varsayılan temanın ilk versiyonu, adı *osu!default olup peppy tarafından yapılmış* tema, *ouendan* arayüzünün neredeyse birebir kopyasını sağlar.
```suggestion
  - Adı *osu!default by peppy* olan, v1 tema özelliklerini kullanan varsayılan temanın ilk versiyonu *ouendan* arayüzünün neredeyse birebir kopyasını içerirdi.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +    - v2 tema davranışı kullanılan daha güzel bir mevcut varsayılan tema ile değiştirildi.
```suggestion
    - v2 tema özelliklerini kullanan daha güzel bir varsayılan tema ile değiştirildi.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +  - v1 ve v2 temaları arasındaki en önemli davranış farkı, spinnerdir.
```suggestion
  - v1 ve v2 temaları arasındaki en önemli davranış farkı, spinnerdır.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +    - v2 temanın spinnere olan davranışı spinner çemberinin en büyük durumuna ulaşması ve bittiğinde parlaması olur.
```suggestion
    - v2 temanın spinner davranışı spinner çemberinin en büyük durumuna ulaşması ve bittiğinde parlaması şeklindedir.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +      - Zamanlayıcı çeviricinin renk değiştiren dış çemberidir. Spinner çemberinin rendi tamamen değiştiğinde spinner bitmiş olur.
```suggestion
      - Zamanlayıcı, spinnerın renk değiştiren dış çemberidir. Spinner çemberinin rengi tamamen değiştiğinde spinner tamamlanmış olur.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Çevrimiçi liderlik tablosunun yayınlandığı aynı gün (07 Ekim 2007, 2007-10-07) sıralamaya açılan ilk 3 harita:
```suggestion
- Çevrimiçi liderlik tablosunun yayınlandığında aynı gün içerisinde dereceli olan (07 Ekim 2007) ilk üç beatmap aşağıdakilerdi:
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +- Özellikle, eski klasörlerin kendi adlandırma kuralları vardır (klasör adları yalnızca *çok eski* harita paketlerinde bulunabilir) ve zorunlu `{HaritaSetiIDsi} {SanatçıAdı} - {HaritaAdı}` formatına
```suggestion
- Özellikle, eski klasörlerin kendi adlandırma kuralları vardır (klasör adları yalnızca *çok eski* beatmap paketlerinde bulunabilir) ve zorunlu `{BeatmapSetID} {SanatçıAdı} - {BeatmapAdı}` formatına sıkı sıkıya uymaz.
```

2021-02-11 18:51 UTC, zeusminus commented on wiki/Game_mode/osu!/tr.md
> +  - Doğrudan osu! web sitesindeki harita listesinden indirmek, ne olursa olsun geçerli zorunlu adlandırma biçimini takip eder.
```suggestion
  - Doğrudan osu! web sitesindeki beatmap kataloğundan indirmek, ne olursa olsun geçerli zorunlu adlandırma biçimini takip eder. 
```

2021-02-12 11:45 UTC, zeusminus approved these changes
LGTM

2021-02-12 11:47 UTC, TicClick approved these changes

2021-02-12 11:47 UTC, merged