[ID] Update Bot Account
ppy/osu-wiki pull request #4934
Opened 2021-02-09 04:44 UTC by AncuL001

2021-02-09 04:46 UTC, AncuL001 commented on wiki/Bot_account/id.md
> +Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan me
```suggestion
Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan mereka dalam berinteraksi dengan lebih banyak pengguna tanpa risiko membuat akun tersebut [dibungkam](/wiki/Glossary#silence).
```

2021-02-09 04:46 UTC, AncuL001 commented on wiki/Bot_account/id.md
> +Badan email tersebut harus meliputi hal - hal berikut:
```suggestion
Badan email tersebut harus meliputi hal-hal berikut:
```

2021-02-09 09:46 UTC, hikikuman requested changes

2021-02-09 09:46 UTC, hikikuman commented on wiki/Bot_account/id.md
> +Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan me
```suggestion
Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan mereka dalam berinteraksi dengan lebih banyak pengguna tanpa risiko membuat akun tersebut [di-silence](/wiki/Glossary#silence).
```
`silence` shouldn't be translated to `bungkam`.

2021-02-09 09:46 UTC, hikikuman commented on wiki/Bot_account/id.md
> +- Bot digunakan demi kepentingan dan keuntungan komunitas.
```suggestion
- Bot digunakan demi kepentingan dan keuntungan komunitas
```

2021-02-25 10:32 UTC, TicClick commented
@hikikuman is this good to go?

2021-02-25 11:18 UTC, hikikuman commented on wiki/Bot_account/id.md
> +Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan me
```suggestion
Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan mereka dalam berinteraksi dengan lebih banyak pengguna tanpa risiko membuat akun tersebut [di-silence](/wiki/Glossary#silence):
```

2021-02-25 11:50 UTC, AncuL001 commented on wiki/Bot_account/id.md
> +Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan me
```suggestion
Perbedaan utama antara akun pribadi dan akun bot terdapat pada batas pengiriman pesan dalam [obrolan](/wiki/Chat_Console). Akun bot memiliki batas pengiriman pesan yang lebih tinggi supaya layanan mereka dapat berinteraksi dengan lebih banyak pengguna tanpa risiko membuat akun tersebut [di-silence](/wiki/Glossary#silence):
```

2021-02-25 11:53 UTC, hikikuman approved these changes
Checked.

2021-02-27 15:08 UTC, TPGPL approved these changes

2021-02-27 15:12 UTC, merged