[ID] Update and retranslate Visual Settings; [KO/NL/PL/PT-BR/TR] Add per-language in-game screenshot to corresponding Visual Settings article
ppy/osu-wiki pull request #4945
Opened 2021-02-10 08:48 UTC by Nivalyx

an update (as well as an overhaul) to the Indonesian translation of the Visual Settings (`/Visual_Settings/id.md`) wiki article as promised to @hikikuman in [#4943](https://github.com/ppy/osu-wiki/pull/4943).

also added per-language in-game screenshots to the ID/KO/NL/PL/PT-BR/TR pages of the article.

2021-02-15 09:07 UTC, hikikuman requested changes
Btw, yang en.md nya nggak sekalian di update juga? kata `Visual settings` di en.md seharusnya ditulis `Visual Settings`. Mungkin penggunaan huruf kapitalnya bisa disamain sama yang di id.md (sebagai acuan utamanya).

2021-02-15 09:07 UTC, hikikuman commented on wiki/Visual_Settings/id.md
> +*Catatan: osu! menyimpan nilai-nilai pengaturan Visual Settings secara terpisah untuk masing-masing beatmap. Untuk mengatur nilai-nilai pengaturan Visual Settings secara global, gunakan opsi pengatur
```suggestion
*Catatan: osu! menyimpan nilai-nilai pengaturan Visual Settings secara terpisah untuk masing-masing beatmap. Untuk mengatur nilai-nilai pengaturan Visual Settings secara umum, gunakan opsi pengaturan yang tersedia pada menu [Options](/wiki/Options).*
```
Penggunaan kata `global` lebih baik diganti jadi `umum` supaya lebih mudah dicerna aja. Pakai kata `global` itu rasanya kurang nyambung dengan konteks yang ada disini (secara keseluruhan atau pengaturan lainnya gitu).

2021-02-22 06:58 UTC, Nivalyx commented
ah, iya, di sini bentukan kalimatnya agak aneh ya... sip2, ini udah gw benerin hehe 

untuk artikel bahasa inggris aslinya kayanya gw biarin begitu dulu aja deh, gw nggak terlalu yakin juga itu harus diapain soalnya. ada beberapa artikel yang tulisan visual settings-nya ditulis pakai huruf kapital ([di halaman ini contohnya](http://osu.ppy.sh/wiki/en/Game_modifier/No_Video)) tapi ada juga yang ditulis pakai huruf kecil D:

thanks as always for the review btw 👍

2021-02-22 12:33 UTC, TicClick approved these changes

2021-02-22 12:33 UTC, merged