[ZH] User_title
ppy/osu-wiki pull request #4948
Opened 2021-02-13 06:04 UTC by kj415j45

2021-02-16 14:23 UTC, TicClick requested changes

2021-02-16 14:23 UTC, TicClick commented on wiki/User_title/en.md
> +*You could find the title at the buttom of this [old osu! forum post \(Internet Archive\)](https://web.archive.org/web/20131107133826/https://osu.ppy.sh/forum/t/141240)*
this contributes nothing to the article and is only used as a reference for these who edit the page, please put the HTML comment back

2021-02-17 01:50 UTC, kj415j45 commented on wiki/User_title/en.md
> +*You could find the title at the buttom of this [old osu! forum post \(Internet Archive\)](https://web.archive.org/web/20131107133826/https://osu.ppy.sh/forum/t/141240)*
```suggestion
<!-- the bottom post on https://web.archive.org/web/20131107133826/https://osu.ppy.sh/forum/t/141240 -->
```

2021-02-17 01:50 UTC, kj415j45 commented on wiki/User_title/zh.md
> +*你可以在[互联网档案馆](https://web.archive.org/web/20131107133826/https://osu.ppy.sh/forum/t/141240)中看见这个头衔出现在侧边栏。*
```suggestion
<!-- 位于链接底部的那个帖子：https://web.archive.org/web/20131107133826/https://osu.ppy.sh/forum/t/141240 -->
```

2021-02-27 02:05 UTC, TPGPL approved these changes

2021-02-27 02:06 UTC, merged