[ZH] Update Beatmapping.md
ppy/osu-wiki pull request #4962
Opened 2021-02-16 15:18 UTC by lixiangwuxian

Translated from en.md. Removed unused line breaks. Fixed some invalid wiki links in en.md
译自en.md。 移除了原文中无意义的换行符，并更正了一些已经无效的wiki链结。

2021-03-22 08:33 UTC, Gennadiyev requested changes
感觉第二人称使用有一点点点多orzz

能不能稍微修改看看呢。

2021-03-22 08:33 UTC, Gennadiyev commented on wiki/Beatmapping/zh.md
> +谱师们一般都会希望他们的谱面可以进入 [rank类别](/wiki/Beatmap)，而这便要通过[谱面 rank 流程](/wiki/Beatmap_ranking_procedure)来实现。
`而这便要通过[谱面 rank 流程](/wiki/Beatmap_ranking_procedure)来实现。` 这一句有点奇怪。

2021-03-22 08:33 UTC, Gennadiyev commented on wiki/Beatmapping/zh.md
> +因为 osu! 是一款基于节奏感的音乐游戏，所以你在制谱时应当选择一些节奏感较强且快慢变化不大的歌曲或乐曲。如果你是个制谱新手，那么就尽量不要选用有节拍（或速度）变化的歌曲，节奏较慢的歌曲也是一样。
`节奏较慢的歌曲也是一样` 是怎样？疑似有歧义。

2021-03-22 08:33 UTC, Gennadiyev commented on wiki/Beatmapping/zh.md
> +虽然现在你也可以修改其他标签页中的选项，但是那些稍后再弄也不成问题。点一下 `OK`，开启你的制谱之旅吧！你接下来要做的便是对歌曲进行校时（Timing）。
`Timing` 的使用与上文 `校准节奏与偏移量` 相矛盾。

2021-03-22 08:33 UTC, Gennadiyev commented on wiki/Beatmapping/zh.md
> +如果你对校时还有些疑问，不妨另寻他人来帮你查查谱面中的毛病，你也可以把你的谱面提交至[谱面帮助论坛区（Beatmap Help forum）](https://osu.ppy.sh/community/forums/10)。无论是对你还是对整个查谱社群（Modding Community），这样做都能省去不少麻烦。
原文 `mod` 翻译作 `他人` 不是非常恰当。

`查谱社群` 有点奇怪。

2021-03-22 08:33 UTC, Gennadiyev commented on wiki/Beatmapping/zh.md
> +你可以在谱面的背景设计界面中设置背景图片，添加背景视频，和/或创作一个基本的故事板。不过如果你会用 [SBS](/wiki/Storyboard_Scripting)（故事板脚本编写）的话，你可能几乎或完全用不到这个界面。
`[SBS](/wiki/Storyboard_Scripting)（故事板脚本编写）` 效果上和上文有些不符，不妨统一为 `中文（英文）` 的格式？或许是因为缩写所以有特别的考虑？可讨论。

2021-03-22 12:21 UTC, lixiangwuxian commented on wiki/Beatmapping/zh.md
> +谱师们一般都会希望他们的谱面可以进入 [rank类别](/wiki/Beatmap)，而这便要通过[谱面 rank 流程](/wiki/Beatmap_ranking_procedure)来实现。
现在看着确实比较奇怪，当时感觉还挺正常的。改了一下。

2021-03-22 12:46 UTC, lixiangwuxian commented on wiki/Beatmapping/zh.md
> +虽然现在你也可以修改其他标签页中的选项，但是那些稍后再弄也不成问题。点一下 `OK`，开启你的制谱之旅吧！你接下来要做的便是对歌曲进行校时（Timing）。
感谢，这里没注意到，添加了一句解释。主要Timing一个单词指的是调BPM与Offset两个动作，个人为方便简译为校时

2021-03-22 12:46 UTC, lixiangwuxian commented on wiki/Beatmapping/zh.md
> +如果你对校时还有些疑问，不妨另寻他人来帮你查查谱面中的毛病，你也可以把你的谱面提交至[谱面帮助论坛区（Beatmap Help forum）](https://osu.ppy.sh/community/forums/10)。无论是对你还是对整个查谱社群（Modding Community），这样做都能省去不少麻烦。
这里修改了一下,确实不够恰当

2021-03-22 12:46 UTC, lixiangwuxian commented on wiki/Beatmapping/zh.md
> +你可以在谱面的背景设计界面中设置背景图片，添加背景视频，和/或创作一个基本的故事板。不过如果你会用 [SBS](/wiki/Storyboard_Scripting)（故事板脚本编写）的话，你可能几乎或完全用不到这个界面。
谢谢指出，之前没有注意到这里，`中文（英文）`效果确实好些，已修正

2021-03-22 12:46 UTC, lixiangwuxian commented on wiki/Beatmapping/zh.md
> +因为 osu! 是一款基于节奏感的音乐游戏，所以你在制谱时应当选择一些节奏感较强且快慢变化不大的歌曲或乐曲。如果你是个制谱新手，那么就尽量不要选用有节拍（或速度）变化的歌曲，节奏较慢的歌曲也是一样。
这里英文原文为`slow song`，确实有些歧义，修改附上了原文。个人认为指的应该是节拍。

2021-03-22 12:53 UTC, lixiangwuxian commented
> 感觉第二人称使用有一点点点多orzz
> 
> 能不能稍微修改看看呢。

关于这点，英文的原文就用了挺多`You`的。试着改掉了一些

2021-03-22 15:23 UTC, lixiangwuxian commented on wiki/Beatmapping/zh.md
> +因为 osu! 是一款基于节奏感的音乐游戏，所以你在制谱时应当选择一些节奏感较强且快慢变化不大的歌曲或乐曲。如果你是个制谱新手，那么就尽量不要选用有节拍（或速度）变化的歌曲，节奏较慢的歌曲也是一样。
哦我可能理解错你的意思了😂不过新提交也顺便改了这里，应该没有歧义了

2021-03-25 16:09 UTC, TicClick commented
what's the status of this? is it good to go? does it need more reviews?

2021-03-28 08:55 UTC, PercyDan54 commented on wiki/Beatmapping/zh.md
> +校时指为谱面校准歌曲对应的节奏与偏移量这一过程。**校时十分重要！** 校时不准的谱面不会成为 rank 状态。务必确保歌曲的校时准确了，再添加[击打物件](/wiki/Hit_object)。
```suggestion
校时指为谱面校准歌曲对应的节奏与偏移量这一过程。**校时十分重要！** 校时不准的谱面不会成为 rank 状态。务必确保歌曲的校时准确了，再添加[物件](/wiki/Hit_object)。
```

2021-03-28 08:55 UTC, PercyDan54 commented on wiki/Beatmapping/zh.md
> +一般说来，你在谱面编辑器中的物件编排（Compose）界面里花费的时间是最多的。在这个界面中，你可以放置击打物件并调整它们的[击打音效](/wiki/Beatmapping/Hitsound)。
```suggestion
一般说来，你在谱面编辑器中的物件编排（Compose）界面里花费的时间是最多的。在这个界面中，你可以放置物件并调整它们的[击打音效](/wiki/Beatmapping/Hitsound)。
```

2021-03-28 08:55 UTC, PercyDan54 commented on wiki/Beatmapping/zh.md
> +要创建一个新谱面，请在主界面点击 “Edit” 进入编辑模式，然后从别处向 osu! 界面里拖进去一个音频文件（另一种方式是将音频文件拖入 `Songs` 文件夹）。在音频文件拖进去后，osu! 的选曲焦点就应该会自动跳转到与拖入的音频文件所对应的谱面编辑项。刚刚选择的新歌曲会在谱面列表的底部以紫色高亮显示。若拖入的歌曲没有出现，那么按一下 `F5` 刷新谱面缓存，这样它应该就能显示出来了。显示
感觉有点啰嗦，而且和原文差别有点大
```suggestion
要创建一个新谱面，请在主界面点击 “Edit” 进入编辑模式，然后向 osu! 界面里拖放一个音频文件（另一种方式是将音频文件放入 `Songs` 文件夹）。然后 osu! 将会自动跳转到拖入的音频文件对应的谱面编辑界面。刚刚选择的新歌曲会在谱面列表的底部以紫色高亮显示。若拖入的歌曲没有出现，那么按一下 `F5` 刷新谱面缓存，这样它应该就能显示出来了。之后，点击歌曲，就会进入[谱面编辑器](/wiki/Beatmap_Editor) 并且弹出 `Song Setup` 界面。
```

2021-03-28 12:48 UTC, PercyDan54 commented
Please don't spam commits.
You can batch apply suggestions [here](https://github.com/ppy/osu-wiki/pull/4962/files)

2021-03-28 12:54 UTC, lixiangwuxian commented
Thanks a lot. I'm not very skill at using Github.

2021-04-25 11:04 UTC, kj415j45 submitted a review, later dismissed

2021-04-25 15:56 UTC, TPGPL requested changes

2021-04-25 15:56 UTC, TPGPL commented on wiki/Beatmapping/zh.md
> +在创建一个新的[难度](/wiki/Difficulties)之前，首先应当填写对话框中的信息。这样，这个谱面所有难度所对应的元数据就必定是一致的了。
```suggestion
在创建一个新的[难度](/wiki/Beatmap/Difficulty)之前，首先应当填写对话框中的信息。这样，这个谱面所有难度所对应的元数据就必定是一致的了。
```

2021-04-25 16:10 UTC, TPGPL approved these changes

2021-04-25 16:10 UTC, merged