[ID] Add Mapping and modding timeline
ppy/osu-wiki pull request #4964
Opened 2021-02-17 11:29 UTC by Nivalyx

Indonesian translation of the Mapping and modding timeline wiki article.

*((ngl translating this was like a journey of its own, whew ;~;))*

2021-02-20 06:08 UTC, hikikuman requested changes

2021-02-20 06:08 UTC, hikikuman commented on wiki/Mapping_and_Modding_Timeline/id.md
> +Secara keseluruhan, terdapat **200 beatmap** yang di-rank sepanjang tahun 2017.
```suggestion
Secara keseluruhan, terdapat **200 beatmap** yang di-rank sepanjang tahun 2007.
```

2021-02-21 19:09 UTC, Nivalyx commented on wiki/Mapping_and_Modding_Timeline/id.md
> +Secara keseluruhan, terdapat **200 beatmap** yang di-rank sepanjang tahun 2017.
whoops, nice catch

2021-03-25 12:20 UTC, hikikuman approved these changes
checked

2021-03-25 16:10 UTC, TicClick approved these changes

2021-03-25 16:10 UTC, merged