[FR] Multi page
ppy/osu-wiki pull request #4975
Opened 2021-02-22 22:35 UTC by Ganondorfosu

French translation of osu! wiki - Multi page

2021-02-24 16:41 UTC, Pachiru requested changes
Je pense qu'une fois que tout ça est appliqué, ce sera bon!

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +| **Tag/Verte** | *Tag Coop and Tag Team Vs seulement*. **C'est la couleur durant tout le match et ne changera pas selon la barre de vie**. Une flèche pointera le joueur actuellement en train de joue
```suggestion
| **Tag/Verte** | Disponible uniquement en *Tag Coop et Tag Team Vs*. **Cette couleur reste la même durant tout le match et ne change pas selon la barre de vie**. Une flèche pointe le joueur actuellement en train de jouer avec une petite lueur blanche. |
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +| **Skipped/Blanche** | **Le joueur demande à passer l'introduction de la map si celle-ci en a une**. Les joueurs ayant appuyé sur le bouton `Skip` en bas à droite de l'écran auront une petite boîte
```suggestion
| **Skipped/Blanche** | **Le joueur demande à passer l'introduction de la map si celle-ci en a une**. Les joueurs ayant appuyé sur le bouton `Skip` en bas à droite de l'écran auront une petite rectangle jaune avec écrit "Skipped" en blanc en bas à droite de leur pseudo. **Tous les joueurs doivent demander à passer l'introduction pour que celle-ci soit passée**. |
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +| **Quit/Dépend** | **Le joueur a quitté le match**. Deux possibilités d'avoir ce statut: (1) Appuyer sur `Echap` deux fois ou (2) se déconnecter de Bancho. La couleur du pseudo du joueur passera du
```suggestion
| **Quit/Dépend** | **Le joueur a quitté le match**. Il y a deux possibilités d'obtenir ce statut: (1) Appuyer sur `Echap` deux fois ou (2) se déconnecter de Bancho. La couleur du pseudo du joueur passera du blanc au rouge, avec un `[Quit]` écrit près du pseudo. La couleur de la boîte dépend de la vie qu'avait le joueur avant de quitter la partie. |
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Le Head to Head est un type de partie dans lequel les joueurs jouent chacun pour soi pour avoir le meilleur score de la salle.
```suggestion
Le Head to Head est un type de partie dans lequel les joueurs jouent chacun pour soi pour obtenir le meilleur score de la salle.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Il s'agit du type de partie par défaut et n'a pas de caractéristique spéciale, il s'agit simplement d'avoir le meilleur score.
```suggestion
Il s'agit du type de partie par défaut et n'a pas de caractéristiques particuliers, il s'agit simplement d'avoir le meilleur score.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Chaque joueur recevra le rang qu'il a obtenu au classement dans l'onglet privé `#userlog` de la console de chat.
```suggestion
Chaque joueur reçoit dans l'onglet privé `#userlog` du chat le rang qu'il a obtenu au classement de chaque partie.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Le mode Team Vs fait s'affronter deux équipes (Rouge et Bleue) selon la condition de victoire choisi par l'hôte.
```suggestion
Le mode Team Vs fait s'affronter deux équipes (Rouge et Bleue) selon différentes conditions de victoire choisies par l'hôte.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Elle bougera de gauche à droite selon l'équipe qui remplit le mieux la condition de victoire.
```suggestion
Cette couronne bouge de gauche à droite selon l'équipe qui remplit le mieux la condition de victoire.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Quand ce mode est sélectionné, tous les joueurs dans la salle recevront une couleur rouge ou bleue.
```suggestion
Quand ce mode est sélectionné, tous les joueurs dans la salle reçoivent une couleur au hasard entre rouge ou bleue.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Il est possible de commencer un match avec une seule équipe, et il n'y a pas de bonus pour l'équipe ayant moins de membres.
```suggestion
Il est possible de commencer un match avec une seule équipe et il n'y a pas de bonus pour l'équipe ayant moins de membres.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Il n'y a pas de rôle (tel que "Leader" ou "Capitaine") dans les équipes; le but est simplement de s'affronter pour avoir le meilleur score de l'équipe et battre le score total de l'équipe adverse.
```suggestion
Il n'y a pas de rôle (tel que "Leader" ou "Capitaine") dans les équipes; le but est simplement de s'affronter pour avoir le meilleur score de l'équipe et battre le score total adverse.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Les membres étant dans le statut Echoué seront placés en bas du classement de leur équipe et ne contribueront pas au total de leur équipe.
```suggestion
Les membres étant dans le statut Échoué sont placés en bas du classement de leur équipe et ne contribuent pas au score total de leur équipe.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Le membre survivant de chaque équipe ayant le meilleur score sera affiché comme `1er` dans son équipe.
```suggestion
Le membre survivant de chaque équipe ayant le meilleur score est affiché comme `1er` dans son équipe.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Dans l'écran de résultat, le gagnant du match dépendra du total des équipes et est annoncé au milieu de l'écran avec la couleur de l'équipe gagnante. Le total de l'équipe bleue se trouve à gauche et
```suggestion
Dans l'écran de résultat, le gagnant du match dépend du score total des équipes et est annoncé au milieu de l'écran avec la couleur de l'équipe gagnante. Le total de l'équipe bleue se trouve à gauche et le total de l'équipe rouge à droite.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +**Seul le score des membres survivants sera compté**; il est possible que l'équipe rouge soit déclarée gagnante même si l'équipe bleue a plus de score parce que certains des joueurs de l'équipe bleue
```suggestion
**Seul le score des membres survivants est compté**; il est possible que l'équipe rouge soit déclarée gagnante même si l'équipe bleue a plus de score parce que certains des joueurs de l'équipe bleue obtiennent le statut Échoué (ou si tous les membres de l'équipe bleue ont échoué).
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +L'onglet `Total`  montrera le total des 300, 100, etc obtenus par toute l'équipe et la moyenne de précision de l'équipe.
```suggestion
L'onglet `Total` montre le total des 300, 100, 50 et ratés obtenus par toute l'équipe ainsi que la moyenne de précision de l'équipe.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Le combo de l'équipe ne sera pas compté dans l'onglet `Total` .
```suggestion
Le combo de l'équipe n'est pas compté dans l'onglet `Total` .
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Le rang obtenu ne sera pas affiché dans l'onglet  `Total` mais sera affiché affiché sur l'écran de résultat des joueurs (s'ils n'ont pas échoué).
```suggestion
Le rang obtenu n'est pas affiché dans l'onglet `Total` mais sera affiché sur l'écran de résultat des joueurs (s'ils n'ont pas échoué).
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Dans ce mode, le placement des joueur allant de haut en bas est important car il détermine l'ordre du tour des joueurs
```suggestion
Dans ce mode, le placement des joueurs allant de haut en bas est important car il détermine l'ordre du tour des joueurs
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Une flèche verte montrera quel joueur est actuellement en train de jouer le combo de la beatmap.
```suggestion
Une flèche verte montre quel joueur est actuellement en train de jouer le combo de la beatmap.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Le pseudo du joueur sera affiché en bas à droite de l'écran.
```suggestion
Le pseudo du joueur est affiché en bas à droite de l'écran.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Il y aura des flèches d'avertissements prévenant le joueur qu'il doit jouer et le combo sera en couleur jusqu'à ce que le combo se finisse
```suggestion
Il y aura des flèches d'avertissements prévenant le joueur qu'il doit jouer et le combo est en couleur jusqu'à ce que le combo se finisse
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +**Tous les joueurs doivent jouer les spinners**.
```suggestion
**Tous les joueurs doivent jouer les spinners**. Ne pas jouer/réussir le spinner brisera le combo actuel.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Ne pas jouer/réussir le spinner brisera le combo actuel.
Supprime cette ligne pour la remplacer au dessus.

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Si un joueur quitte durant le match, [Auto](/wiki/Game_modifier/Auto) jouera à sa place.
```suggestion
Si un joueur quitte durant le match, le mode [Auto](/wiki/Game_modifier/Auto) prend le relais.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +En Tag Coop, tous les joueurs partageront la même barre de vie.
```suggestion
En Tag Coop, tous les joueurs partagent la même barre de vie.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Si la barre de vie est entièrement vidée (Echec), le match se termine et tous les joueurs sont renvoyés dans la salle immédiatement sans résultat
```suggestion
Si la barre de vie est entièrement vidée (Échec), le match se termine et tous les joueurs sont renvoyés dans la salle immédiatement sans résultat.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +En Tag Team Vs, chaque équipe a sa propre barre de vie qui n'est visible que par les mêmes membres d'une équipe.
```suggestion
En Tag Team Vs, chaque équipe a sa propre barre de vie qui est visible uniquement par les membres de l'équipe.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Les joueurs utilisant le mod [Sudden Death (SD)](/wiki/Game_modifier/Sudden_Death)/[Perfect (PF)](/wiki/Game_modifier/Perfect) auront une interface différente des autres joueurs, plus particulièremen
```suggestion
Les joueurs utilisant le mod [Sudden Death (SD)](/wiki/Game_modifier/Sudden_Death)/[Perfect (PF)](/wiki/Game_modifier/Perfect) ont une interface différente des autres joueurs, plus particulièrement quand le mod prend effet.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Si un coéquipier n'utilise **pas** ce mod et a fait une erreur suffisante pour causer l'effet du mod, la beatmap continuera normalement, et les joueurs utilisant le mod auront leur barre de vie rédui
```suggestion
Si un coéquipier n'utilise **pas** ce mod et fait une erreur suffisante pour causer l'activation du mod, la beatmap continuera normalement et les joueurs utilisant le mod auront leur barre de vie réduite et bloquée à 0 sans causer l'effet du mod (seuls les effets visuels apparaîtront).
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Si le joueur **utilisant** le mod a fait une erreur suffisante pour causer l'effet du mod, celui-ci s'activera et l'échec sera immédiat.
```suggestion
Si le joueur **utilisant** le mod fait une erreur suffisante pour causer l'activation du mod, celui-ci s'active et l'échec est immédiat.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Si vous jouez en fenêtré, notez que le curseur ne sera **pas** confiné dans la fenêtre du jeu pendant les pauses ou pendant le tour des autres joueurs.
```suggestion
Si vous jouez en fenêtré, notez que le curseur n'est **pas** confiné dans la fenêtre du jeu pendant les pauses ou pendant le tour des autres joueurs.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Comme précisé avant, le score ne sera pas compté pour le score classé et les points de performance car il s'agit d'une partie *non-classée*.
```suggestion
Comme précisé plus haut dans l'article, le score n'est pas compté pour le score classé et les points de performance car il s'agit d'une partie *non-classée*.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +En Tag Coop, le résultat affiché est le score total, les 300, 100, etc et la précision moyenne de l'équipe
```suggestion
En Tag Coop, le résultat affiché comprend le score total, les 300, 100, 50 et ratés ainsi que la précision moyenne de l'équipe.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Les résultats individuels ne seront pas montrés, et ne peuvent qu'être vus dans l'historique des matchs
```suggestion
Les résultats individuels ne sont pas montrés, et ne peuvent qu'être visionnés dans l'historique des matchs.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +L'écran de résultat n'apparaîtra que si la beatmap a été réussie.
```suggestion
L'écran de résultat n'apparait que si la beatmap a été réussie.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +Pour l'écran de résultats en Tag Team Vs, voir l'explication de l'écran de résultats en Team Vs.
```suggestion
*Pour l'écran de résultats en Tag Team Vs, voir l'explication de l'écran de résultats en Team Vs.*
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +## Trivia
```suggestion
## Le Saviez-vous?
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +- "No Video" était le seul mod autorisé pour les joueurs; cependant, ce mod a été supprimé en faveur de son placement dans les paramètres visuels.
```suggestion
- Le mod "No Video" était le seul mod autorisé pour les joueurs; cependant, ce mod a été supprimé afin d'être directement intégré dans les paramètres visuels.
```

2021-02-24 16:41 UTC, Pachiru commented on wiki/Multi/fr.md
> +- le mode de jeu osu!mania était noté `3` dans le lobby pour les joueurs qui n'avaient pas encore mis à jour leur jeu (qui active le mode osu!mania n'ayant pas encore de support de classement).
```suggestion
- Le mode de jeu osu!mania était noté `3` dans le lobby pour les joueurs qui n'avaient pas encore mis à jour leur jeu (qui active le mode osu!mania n'ayant pas encore de support de classement).
```

2021-02-26 20:53 UTC, Pachiru requested changes
Apply ça et normalement c'est bon

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +Le Multi (aussi connu en tant que *Multijoueur*) a été mis en œuvre le 3 Juin 2008 sous la version b335 d'osu!, et s'agit d'un mode de jeu dans le lequel jusqu'à 16 joueurs peuvent s'affronter sur un
```suggestion
Le Multi (aussi connu en tant que *Multijoueur*) a été introduit le 3 Juin 2008 sous la version b335 d'osu!, et s'agit d'un mode de jeu dans lequel jusqu'à 16 joueurs peuvent s'affronter sur une beatmap choisie par l'hôte.
```

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +Les filtres sont expliqués ci-dessous:-
```suggestion
Les filtres sont expliqués ci-dessous:
```

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +  - Pas de couleur signifie que la place est verrouillée.
```suggestion
  - Aucune couleur signifie que la place est verrouillée.
```

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +| **Max players** | **Nombre de joueurs max. autorisé.** Par défaut à 8 joueurs, peut être de 2 à 16 joueurs, l'hôte de la partie étant inclus. Cela peut être changé après la création de la salle en
```suggestion
| **Max players** | **Nombre de joueurs maximum autorisé.** Par défaut, le nombre autorise jusqu'a à 8 joueurs maximum, mais peut en réalité être modifié pour autoriser 2 à 16 joueurs, l'hôte de la partie étant inclus. Cela peut être changé après la création de la salle en déverrouillant/verrouillant les places dans la salle. |
```

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +Celle-ci montrera l'image, le symbole du mode de jeu, le titre, l'artiste de la musique, le créateur de la beatmap, la difficulté sélectionnée ainsi que la difficulté en étoiles de la beatmap.
```suggestion
Celle-ci montre l'image, le symbole du mode de jeu, le titre, l'artiste de la musique, le créateur de la beatmap, la difficulté sélectionnée ainsi que la difficulté en étoiles de la beatmap.
```

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +#### Type de partie, Condition de victoire, Couleur
```suggestion
#### Type de partie, Condition de victoire et Couleur
```

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +Si le mod [Easy (EZ)](/wiki/Game_modifier/Easy) est utilisé et que l'équipe échoue, les deux vies supplémentaires seront bien présentes mais les barres de vie seront immédiatement vidées afin d'échou
```suggestion
Si le mod [Easy (EZ)](/wiki/Game_modifier/Easy) est utilisé et que l'équipe échoue, les deux vies supplémentaires seront bien présentes mais les barres de vie seront immédiatement vidées afin de terminer immédiatement la beatmap.
```

2021-02-26 20:53 UTC, Pachiru commented on wiki/Multi/fr.md
> +- Le mode de jeu osu!mania était noté `3` dans le lobby pour les joueurs qui n'avaient pas encore mis à jour leur jeu (qui active le mode osu!mania n'ayant pas encore de support de classement).
```suggestion
- Le mode de jeu osu!mania était noté `3` dans le lobby pour les joueurs qui n'avaient pas encore mis à jour leur jeu (qui active le mode osu!mania qui n'avait pas encore de support de classement).
```

2021-02-26 21:40 UTC, Pachiru approved these changes
LGTM

2021-03-08 19:37 UTC, TicClick approved these changes
while I assume the translation is ok, I highly advise against translating the articles marked as outdated or in need of cleanup for obvious reasons (you'll have to update it once again when the original article is reworked)

2021-03-08 19:37 UTC, merged