[FR] Replay
ppy/osu-wiki pull request #4977
Opened 2021-02-23 18:23 UTC by Ganondorfosu

French translation of osu! wiki - Replay page

2021-03-22 17:12 UTC, DoryanR requested changes
After changes, it will be good for me.

2021-03-22 17:12 UTC, DoryanR commented on wiki/Replay/fr.md
> +Trying to restart the beatmap to directly play the beatmap again in this state is not possible.
```suggestion
Essayer de redémarrer la beatmap pour le relancer directement dans cet état n'est pas possible.
```

2021-03-22 17:12 UTC, DoryanR commented on wiki/Replay/fr.md
> +Format et exemple de la liste que le joueur voit:-
```suggestion
Format et exemple de la liste que le joueur voit :
```

2021-03-22 17:12 UTC, DoryanR commented on wiki/Replay/fr.md
> +Format exemple de ce texte:-
```suggestion
Format et exemple de ce texte :
```

2021-03-22 17:12 UTC, DoryanR commented on wiki/Replay/fr.md
> +Bien qu'il soit possible d'exporter un replay en mode spectateur, c'est une mauvaise si vous avez rejoint en plein milieu ou à la fin de la map.
```suggestion
Bien qu'il soit possible d'exporter un replay en mode spectateur, c'est une mauvaise idée si vous avez rejoint en plein milieu ou à la fin de la map.
```

2021-03-22 17:12 UTC, DoryanR commented on wiki/Replay/fr.md
> +Cependant, en osu!taiko, si Auto ne peut pas remplir la barre de vie à au moins 50%, le replay sera bloqué dans une _boucle infinie_.
Il faudra rajouter une ligne vide en fin de document, car cela bloque la vérification de GitHub.

2021-03-22 17:14 UTC, DoryanR commented on wiki/Replay/fr.md
> +---
Fait un saut de page entre "---" et le TODO, car cela bloque la vérification de GitHub.

2021-03-23 18:02 UTC, DoryanR commented
Also, for each italicization (with the `_`), you have to use `*` by putting this at the beginning of the place where you have to italicize, and at the end too, as `_` doesn't work, for conformity and formatting concerns between articles I guess.

2021-03-25 15:16 UTC, DoryanR requested changes
Still some things to work on.

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +Dans le backend, une paire de fichiers sera créé dans le dossier caché, `Data/r`: `.osr` (osu! replay; le fichier du replay), et `.osg` (précision et combo en temps réel: utilisé uniquement pour les
```suggestion
Dans le backend, une paire de fichiers sera créé dans le dossier caché, `Data/r`: `.osr` (osu! replay ; le fichier du replay), et `.osg` (précision et combo en temps réel : utilisé uniquement pour les replays en mode spectateur) avec le même nom de fichier crypté.
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +Sur cet écran, une alternative à la touche d'exportation `F2`  est d'activer le bouton `Save replay to Replays folder` situé sur la partie supérieure droite.
```suggestion
Sur cet écran, une alternative à la touche d'exportation `F2` est d'activer le bouton `Save replay to Replays folder` situé sur la partie supérieure droite.
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +### Echec
```suggestion
### Échec
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +Voir un replay échoué ne fonctionnera pas avec les mods [No Fail(NF)](/wiki/Game_modifier/No_Fail)/[Relax(RL)](/wiki/Game_modifier/Relax)/[Auto Pilot(AP)](/wiki/Game_modifier/Autopilot) puisqu'il est
```suggestion
Voir un replay échoué ne fonctionnera pas avec les mods [No Fail(NF)](/wiki/Game_modifier/No_Fail)/[Relax(RL)](/wiki/Game_modifier/Relax) et [Auto Pilot(AP)](/wiki/Game_modifier/Autopilot) puisqu'il est impossible d'échouer.
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +Format :-
```suggestion
Format :
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +Exemple:-
```suggestion
Exemple :
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +Spectateurs (#):
```suggestion
Spectateurs (#) :
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +Spectateurs (2):
```suggestion
Spectateurs (2) :
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +La vitesse du replay n'affecte pas la vitesse de défilement de la notice `REPLAY MODE/SPECTATOR MODE` .
```suggestion
La vitesse du replay n'affecte pas la vitesse de défilement de la notice `REPLAY MODE/SPECTATOR MODE`.
```

2021-03-25 15:16 UTC, DoryanR commented on wiki/Replay/fr.md
> +## Trivia
```suggestion
## Anecdotes
```

2021-03-26 14:56 UTC, Ganondorfosu commented on wiki/Replay/fr.md
> +### Playback Speed
Je le laisse comme ça parce que c'est ce qui est écrit en jeu (même avec le jeu en français)

2021-03-26 14:58 UTC, DoryanR commented on wiki/Replay/fr.md
> +### Playback Speed
Ok pas de soucis

2021-03-26 15:27 UTC, DoryanR approved these changes
After checking the file, I approve the changes.

2021-03-26 20:38 UTC, TicClick approved these changes
in future, please avoid translating articles that have `needs_cleanup` and `outdated` tags. it's very often a wasted effort, because you'll have to translate them twice.

2021-03-26 20:38 UTC, merged