[FR] Users_with_unique_titles
ppy/osu-wiki pull request #4980
Opened 2021-02-24 09:50 UTC by Airwam

French translation of osu! wiki - Users with unique titles Page

2021-02-27 15:18 UTC, Pachiru requested changes
Très bonne traduction! Une fois que tu auras modifié ça, je pense qu'on sera bon!

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +Depuis 2020, l'activité des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et des membres de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team)  dans le
```suggestion
Depuis 2020, la contribution des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et des membres de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) dans le système de ranking a été récompensée avec le titre **Elite Nominator**. Ce titre est attribué en début d'année pour les contributions apportées durant l'année précédente et est retiré lorsque l'utilisateur quitte l'équipe.
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +![][flag_US] [Charles445](https://osu.ppy.sh/users/85000) a reçu ce titre en ayant déjà le titre Elite Mapper, il a donc été "amélioré" vers **Elite Mapper II : Aspirant**. ![][flag_KR][Spectator](ht
```suggestion
![][flag_US] [Charles445](https://osu.ppy.sh/users/85000) a reçu ce titre en ayant déjà le titre Elite Mapper, il a donc été "amélioré" vers **Elite Mapper II : Aspirant**. ![][flag_KR][Spectator](https://osu.ppy.sh/users/702598) utilise actuellement le titre **osu!catch Champion** à la place.
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +La compétition de mapping Aspire possède une variation spéciale du titre Elite Mapper appelée **Elite Mapper : Aspirant** en tant que prix.
```suggestion
La compétition de mapping Aspire possède une variation spéciale du titre Elite Mapper appelée **Elite Mapper : Aspirant** en tant que prix pour la première place.
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +La compétition osu!remix attribue le titre **osu!mixer** en tant que premier prix.
```suggestion
La compétition osu!remix attribue le titre **osu!mixer** en tant que prix pour la première place.
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +La osu!team a tenu des compétitions d'art pour que les membres de la communauté aient une chance de dessiner ou redessiner certaines mascottes du jeu. Les gagnants de ces compétitions, ainsi que les
```suggestion
L'osu!team a tenu des compétitions d'art permettant aux membres de la communauté de dessiner ou redessiner certaines mascottes du jeu. Les gagnants de ces compétitions, ainsi que les personnes pour qui les dessins ont finalement été choisis comme officiels ont reçu le titre **osu!artist**.
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +Ces joueurs ont gagné leurs titres à travers soit des accomplissements fous, ou la complétion d'un défi spécifique.
```suggestion
Ces joueurs ont gagnés leurs titres à travers des prouesses exceptionnelles, ou la complétion d'un défi spécifique.
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +| Utilisateur | Titre | Accomplissement |
```suggestion
| Utilisateur | Titre | Prouesse |
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_AU] [Jaye](https://osu.ppy.sh/users/4841352) | Drum Decimator | A FC toutes les maps osu!taiko classées avant le 3 novembre 2019 |
```suggestion
| ![][flag_AU] [Jaye](https://osu.ppy.sh/users/4841352) | Drum Decimator | A complété à 100% toutes les beatmaps du mode osu!taiko classées avant le 3 novembre 2019 |
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_US] [xasuma](https://osu.ppy.sh/users/3172980) | The First Completionist | A joué toutes les maps osu!standard classée avant le 27 avril 2019 |
```suggestion
| ![][flag_US] [xasuma](https://osu.ppy.sh/users/3172980) | The First Completionist | A joué toutes les beatmaps du mode osu!standard classée avant le 27 avril 2019 |
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +Ces trois utilisateurs ont été récompensés du titre **osu! Hall of Famer** pour avoir joué au jeu au niveau le plus haut, et contribué lorsque la communauté était encore jeune.
```suggestion
Ces trois utilisateurs ont été récompensés du titre **osu! Hall of Famer** pour avoir joué au jeu au niveau le plus haut, et énormément contribué lorsque la communauté était naissante.
```

2021-02-27 15:18 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +Les titres utilisateurs sont généralement associés avec des [groupes d'utilisateurs](/wiki/People/The_Team#user-groups), mais les utilisateurs listés ci-dessous ont reçu leurs titres pour d'autres ra
```suggestion
Les titres utilisateurs sont généralement associés avec des [groupes d'utilisateurs](/wiki/People/The_Team#user-groups), mais les utilisateurs listés ci-dessous ont reçu leurs titres pour d'autres raisons. La plupart de ces titres sont des récompenses pour des contributions remarquables ou l'accomplissement de succès uniques, le reste étant des preuves de l'histoire iconique d'osu!.
```

2021-02-28 19:20 UTC, Pachiru requested changes

2021-02-28 19:20 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +### Gagnants de compétition de mapping officielles
```suggestion
### Gagnants de compétitions de mapping officielles
```

2021-02-28 19:20 UTC, Pachiru commented on wiki/People/Users_with_unique_titles/fr.md
> +### Gagnants de compétition de design des mascottes
```suggestion
### Gagnants de compétitions de design des mascottes
```

2021-02-28 20:22 UTC, Pachiru commented
LGTM

2021-02-28 20:22 UTC, Pachiru submitted a review, later dismissed
LGTM

2021-03-08 19:33 UTC, TicClick approved these changes

2021-03-08 19:33 UTC, merged