[FR] Article styling criteria
ppy/osu-wiki pull request #4983
Opened 2021-02-24 11:44 UTC by Ganondorfosu

French translation of osu! wiki - Article styling criteria

2021-03-22 16:23 UTC, DoryanR requested changes
After modifications, it will be good for me.

2021-03-22 16:23 UTC, DoryanR commented on wiki/Article_styling_criteria/fr.md
> +Tous les articles doivent avoir une bonne grammaire, une bonne orthographe et une information correcte.
```suggestion
Tous les articles doivent avoir une bonne grammaire, un bon orthographe et une information correcte.
```

2021-03-25 17:20 UTC, DoryanR approved these changes
After checking the file, I approve the changes.

2021-03-26 20:46 UTC, TicClick approved these changes

2021-03-26 20:46 UTC, merged