[FR] Project Loved Team
ppy/osu-wiki pull request #4991
Opened 2021-02-25 00:32 UTC by Zekao

Translation of  osu! wiki - Project Loved Team

2021-02-27 14:03 UTC, Pachiru requested changes
Apply this and it'll be good!

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_CL]: /wiki/shared/flag/CL.gif "Chile"
```suggestion
[flag_CL]: /wiki/shared/flag/CL.gif "Chili"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_CN]: /wiki/shared/flag/CN.gif "China"
```suggestion
[flag_CN]: /wiki/shared/flag/CN.gif "Chine"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_DE]: /wiki/shared/flag/DE.gif "Germany"
```suggestion
[flag_DE]: /wiki/shared/flag/DE.gif "Allemagne"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_GB]: /wiki/shared/flag/GB.gif "United Kingdom"
```suggestion
[flag_GB]: /wiki/shared/flag/GB.gif "Royaume-Uni"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_JP]: /wiki/shared/flag/JP.gif "Japan"
```suggestion
[flag_JP]: /wiki/shared/flag/JP.gif "Japon"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_LT]: /wiki/shared/flag/LT.gif "Lithuania"
```suggestion
[flag_LT]: /wiki/shared/flag/LT.gif "Lithuanie"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_LV]: /wiki/shared/flag/LV.gif "Latvia"
```suggestion
[flag_LV]: /wiki/shared/flag/LV.gif "Lettonie"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_NL]: /wiki/shared/flag/NL.gif "Netherlands"
```suggestion
[flag_NL]: /wiki/shared/flag/NL.gif "Pays-Bas"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_PL]: /wiki/shared/flag/PL.gif "Poland"
```suggestion
[flag_PL]: /wiki/shared/flag/PL.gif "Pologne"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_SG]: /wiki/shared/flag/SG.gif "Singapore"
```suggestion
[flag_SG]: /wiki/shared/flag/SG.gif "Singapour"
```

2021-02-27 14:03 UTC, Pachiru commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +[flag_US]: /wiki/shared/flag/US.gif "United States"
```suggestion
[flag_US]: /wiki/shared/flag/US.gif "États-Unis"
```

2021-03-22 16:07 UTC, DoryanR commented
The translation needs to be revised, since changes have been made to the English version in the meantime.

2021-03-22 16:10 UTC, DoryanR requested changes
The translation needs to be revised, since changes have been made to the English version in the meantime.

2021-04-24 09:45 UTC, DoryanR commented
@Zekao Are you still on the job?

2021-04-25 13:22 UTC, Zekao commented
> @Zekao Are you still on the job?

I really don't have time to fix it for now so if you want to do a new pull you can ^^

2021-05-20 16:48 UTC, DoryanR commented
This PR can be closed, following #5520

2021-05-20 19:53 UTC, closed without merging