[FR] How you can help
ppy/osu-wiki pull request #5000
Opened 2021-02-28 10:56 UTC by almaloste

French translation of how you can help page

2021-02-28 21:14 UTC, Pachiru requested changes

2021-02-28 21:14 UTC, Pachiru commented on wiki/How_you_can_help!/fr.md
> +Démarrer en 2017, le projet osu!lazer est  le centre d'interêt actuel de l'équipe d'osu!, avec le nouveau site web, qui est celui que vous voyez aujourd'hui ! Si vous voulez aider a rendre ces projet
```suggestion
Démarré en 2017, le projet osu!lazer est le centre d'interêt actuel de l'équipe d'osu!, accompagné du nouveau site web, qui est celui que vous voyez actuellement ! Si vous voulez aider à améliorer ces projets, ci-dessous voici quelques exemples-type de contributions :
```

2021-02-28 21:14 UTC, Pachiru commented on wiki/How_you_can_help!/fr.md
> +- Aidez le projet [osu!lazer](https://github.com/ppy/osu). Il y a beaucoup a implémenter sur la nouvelle version d'osu!, et vous pouvez aider a le faire !
```suggestion
- Aidez le projet [osu!lazer](https://github.com/ppy/osu). Il y a encore beaucoup de fonctionnalités à implémenter sur la nouvelle version d'osu!, et vous pouvez nous aider !
```

2021-02-28 21:14 UTC, Pachiru commented on wiki/How_you_can_help!/fr.md
> +## Évitez d'être négatif ! Rendez les gens heureux !
```suggestion
## Évitez d'être négatif !
```

2021-02-28 21:14 UTC, Pachiru commented on wiki/How_you_can_help!/fr.md
> +Il y a un vieil adage selon lequel vous devriez faire partie de la solution, pas du problème. En le suivant vous aidez osu! en faisant de la communauté un endroit meilleur. Les gens vont toujours se
```suggestion
Il y a un vieil adage selon lequel vous devriez faire partie de la solution, pas du problème. En le suivant, vous aidez osu! en faisant de la communauté un endroit meilleur. Les gens se plaindront toujours, mais il y aura toujours des manières de remonter le moral de la communauté :
```

2021-02-28 21:14 UTC, Pachiru commented on wiki/How_you_can_help!/fr.md
> +- [Reportez les tricheurs quand vous les voyez](/wiki/Reporting_Bad_Behaviour/Handling_Foul_Play). Veuillez ne pas vous plaindre à leur sujet par d'autres moyens, car un simple `!report <username> se
```suggestion
- [Signalez les tricheurs quand vous les voyez](/wiki/Reporting_Bad_Behaviour/Handling_Foul_Play). Veuillez ne pas vous plaindre à leur sujet ou en parler sur les canaux de discussions, car un simple `!report <username> semble tricher` peut résoudre vos problèmes assez rapidement. 
```

2021-02-28 21:14 UTC, Pachiru commented on wiki/How_you_can_help!/fr.md
> +**Bien que cet article ne puisse pas couvrir tous les points sur lequels vous pouvez aider la communauté osu!, le simple fait de jouer au jeu peut aussi rendre osu! encore plus génial!**
```suggestion
**Bien que cet article ne puisse pas couvrir tous les points sur lesquels vous pouvez aider la communauté osu!, le simple fait de jouer au jeu peut aussi rendre osu! encore plus génial!**
```

2021-03-19 21:43 UTC, TPGPL approved these changes

2021-03-19 21:43 UTC, merged