[PT-BR] osu!tourney
ppy/osu-wiki pull request #5001
Opened 2021-02-28 19:33 UTC by daviirodrig

Add pt-br translation of osu!tourney articles

2021-03-09 22:13 UTC, maotovisk requested changes
The grammar is really good and well-written, just a minor typo here and there.
I would suggest taking a look over the italic names rule, name such as trademarks, product names etc. doesn't need to be in italic.
Besides that everything seems to be okay.

2021-03-10 13:51 UTC, daviirodrig commented
@maotovisk Thanks for the review! I applied everything because I thought it was appropriate

By the way, next time it's better if you do the review [suggesting changes](https://haacked.com/archive/2019/06/03/suggested-changes/) directly in the comment, that way I can apply the changes in a more efficiently and you receive the co-authoring in the commit.

2021-03-10 23:33 UTC, maotovisk approved these changes

2021-03-13 10:22 UTC, TicClick approved these changes

2021-03-13 10:22 UTC, merged