[ZH] Add TWC 2021/Fix language in MWC4K/OWC 2020
ppy/osu-wiki pull request #5020
Opened 2021-03-04 04:33 UTC by Kotoki1337

2021-03-07 22:51 UTC, kj415j45 requested changes

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/MWC/2020_4K/zh.md
> +   - !roll 输的队伍进行先 Ban。
```suggestion
   - !roll 胜的队伍先 Pick。
   - !roll 输的队伍先 Ban。
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/OWC/2020/zh.md
> +5. 如果没有可用的工作人员或裁判，比赛将被推迟。
```suggestion
5. 如果没有空闲的工作人员或裁判，比赛将被推迟。
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/OWC/2020/zh.md
> +    - **如果重赛，两个队伍的上场选手不能进行改变，不会因为重赛而允许队伍改变上场选手。如果之前上场的队员不可用，可作例外处理，这由裁判决定。**
```suggestion
    - **如果重赛，两个队伍的上场选手不能进行改变，不会因为重赛而允许队伍改变上场选手。如果之前上场的队员无法参加，可作例外处理，由裁判决定。**
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/OWC/2020/zh.md
> +   - !roll 输的队伍进行先 **Ban**。
```suggestion
   - !roll 胜的队伍先 **Pick**。
   - !roll 输的队伍先 **Ban**。
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/TWC/2021/zh.md
> +   - **除非绝对必要，否则不要要求重新排程。比赛管理团队仍有权拒绝该请求。**
```suggestion
6. **只有队长才能申请重新排程。**
   - **除非绝对必要，否则不要申请重新排程。比赛管理团队仍有权拒绝该请求。**
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/TWC/2021/zh.md
> +   - !roll 输的队伍进行先 Ban。
```suggestion
   - !roll 胜的队伍先 Pick。
   - !roll 输的队伍先 Ban。
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/TWC/2021/zh.md
> +   - 多人游戏房间设置为 osu!taiko，Team-Vs，获胜条件：ScoreV2。房间名称必须为 “TWC 2021: (TeamRed) vs (TeamBlue)”。
```suggestion
   - 多人游戏房间设置为 osu!taiko，Team-Vs，获胜条件：ScoreV2。房间名称一定是 “TWC 2021: (TeamRed) vs (TeamBlue)”。
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/TWC/2021/zh.md
> +5. 如果没有可用的工作人员或裁判，比赛将被推迟。
```suggestion
5. 如果没有空闲的工作人员或裁判，比赛将被推迟。
```

2021-03-07 22:51 UTC, kj415j45 commented on wiki/Tournaments/TWC/2021/zh.md
> +   - **如果重赛，两个队伍的上场选手不能进行改变，不会因为重赛而允许队伍改变上场选手。如果之前上场的队员不可用，可作例外处理，这由裁判决定。**
```suggestion
   - **如果重赛，两个队伍的上场选手不能进行改变，不会因为重赛而允许队伍改变上场选手。如果之前上场的队员无法参加，可作例外处理，由裁判决定。**
```

2021-03-12 14:01 UTC, WalterToro approved these changes

2021-03-12 14:01 UTC, merged