[FR] Mapping Techniques
ppy/osu-wiki pull request #5028
Opened 2021-03-07 21:09 UTC by Slyyme

French translation of osu! wiki - Mapping Techniques

2021-03-22 16:00 UTC, DoryanR requested changes
After modifications, it will be good for me.

2021-04-01 14:35 UTC, DoryanR commented
@Slyyme Need you to apply the proposed changes

2021-04-12 07:31 UTC, DoryanR requested changes

2021-04-12 07:31 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +Les techniques de Mapping sont des méthodes de placements/patterns qui sont largement utilisés par les beatmappers connus dans leurs maps.
```suggestion
Les **techniques de mapping** sont des méthodes de placements/patterns qui sont largement utilisés par les mappers connus dans leurs beatmaps.
```

2021-04-12 07:31 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +# Techniques de Mapping
```suggestion
# Techniques de mapping
```

2021-04-12 07:31 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +Ces pages sont ici comme guides pour débutant, pour aider à expliquer comment faire de telles techniques jusqu'à ce que vous ayez développé votre propre style de mapping. Pour commencer, il est recom
```suggestion
Ces pages sont un guide pour les débutant, pour leurs expliquer comment réaliser de telles techniques jusqu'à ce que vous ayez développé votre propre style de mapping. Pour commencer, il est recommandé d'observer et de copier ces techniques de mapping à partir de mappers expérimentés tout en permettant à votre créativité de circuler librement petit-à-petit. Beaucoup de grands mappers ont aiguisé leurs compétences à leurs débuts en imitant les autres qu'ils admiraient, il n'y a donc aucune honte à ce que vous le faites vous-même.
```

2021-04-12 07:31 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +Vous trouverez ci-dessous des liens vers certaines techniques de mapping connues, et toutes largements utilisées par les mappers.
```suggestion
Vous trouverez ci-dessous des liens vers certaines techniques de mapping connues, et toutes largement utilisées par les mappers.
```

2021-04-12 07:31 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +Si nécessaire, vous pourriez également obtenir un essentiel des techniques de mapping à [Techniques de Mapping/Notions de base](Basics/).
```suggestion
Si nécessaire, vous pourriez également obtenir un essentiel des techniques de mapping sur l'article [techniques de mapping/Notions de base](Basics/).
```

2021-04-12 07:31 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +#### Hit Circle
```suggestion
#### Cercles
```

2021-04-24 09:47 UTC, DoryanR commented
@Slyyme Are you still on the job?

2021-05-13 10:01 UTC, DoryanR requested changes

2021-05-13 10:01 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +#### Effets Additionnels
```suggestion
#### Effets additionnels 
```

2021-05-13 10:01 UTC, DoryanR commented on wiki/Mapping_Techniques/fr.md
> +#### Variaions de Spinners
```suggestion
#### Variations de spinners
```

2021-05-13 10:01 UTC, DoryanR commented
@TicClick I think we can apply the suggestions and merge, because it's been too long since the person gave up their PR.

2021-05-21 15:29 UTC, TicClick approved these changes

2021-05-21 15:29 UTC, merged