[RU] Update Beatmap/Category
ppy/osu-wiki pull request #5059
Opened 2021-03-13 18:23 UTC by TicClick

2021-03-19 18:48 UTC, UristMcKobold requested changes

2021-03-19 18:48 UTC, UristMcKobold commented on wiki/Beatmap/Category/ru.md
> +В категорию Graveyard попадают карты, которыми больше никто не занимается. Они автоматически перемещаются сюда из категорий [Work in Progress и Pending](#work-in-progress-и-pending), если их не обнов
```suggestion
В категорию Graveyard попадают карты, которые были заброшены их создателем. Они автоматически перемещаются сюда из категорий [Work in Progress и Pending](#work-in-progress-и-pending), если их не обновляли в течение 4 недель. У таких карт нет таблиц рекордов, но их по-прежнему можно скачать и сыграть, плюс они влияют на [статистику при прохождении](#unranked-beatmaps-statistics). В списке карт в клиенте они отмечены знаком вопроса (![](/wiki/shared/status/graveyard.png)).
```
Первое предложение неоднозначно может быть воспринято, в оригинале всё просто. 
Теперь они влияют на статистику, и в оригинале про это написано. И не хватает ссылки  на https://osu.ppy.sh/wiki/en/Beatmap/Category#unranked-beatmaps-statistics
Только эту ссылку перевести надо, но это уже сам давай!

2021-03-19 18:48 UTC, UristMcKobold commented on wiki/Beatmap/Category/ru.md
> +### Неранкнутые карты и число очков
```suggestion
### Статистика неранкнутых карт
```
Так как плейкаунт ещё дают, а не только очки. Да и в целом непонятно, что за число очков.

2021-03-19 18:48 UTC, UristMcKobold commented on wiki/Beatmap/Category/ru.md
> +Категория Qualified — последний этап [процедуры ранкинга](/wiki/Beatmap_ranking_procedure). Карты, находящиеся здесь, проверены как минимум двумя [номинаторами](/wiki/People/The_Team/Beatmap_Nominato
```suggestion
Категория Qualified — последний этап [процедуры ранкинга](/wiki/Beatmap_ranking_procedure). Карты, находящиеся здесь, проверены как минимум двумя [номинаторами](/wiki/People/The_Team/Beatmap_Nominators) на соответствие [критериям ранкинга](/wiki/Ranking_Criteria). При попадании в Qualified карта также встаёт в [очередь ранкинга](/wiki/Beatmap_ranking_procedure/Ranking_queue) и в конечном счёте попадает в категорию [Ranked](#ranked) при условии, что её не [дисквалифицируют](/wiki/Beatmap_ranking_procedure#сброс-номинации). Это последний этап перед ранком, в течение которого все недостатки и ошибки карты, упущенные моддерами и номинаторами, должны быть исправлены.
```
Тире тут смущает.
И переврал, в оригинале «any flaws and mistakes», а у тебя стало «серьёзным».

2021-03-19 18:48 UTC, UristMcKobold commented on wiki/Beatmap/Category/ru.md
> +Карты категории Loved почти всегда нарушают [критерии ранкинга](/wiki/Ranking_Criteria), но, тем не менее, игровое сообщество их *любит* и каждый месяц пополняет эту категорию в рамках [Project Loved
```suggestion
Карты категории Loved могут нарушать [критерии ранкинга](/wiki/Ranking_Criteria), но, тем не менее, игровое сообщество их *любит* и каждый месяц пополняет эту категорию в рамках [Project Loved](/wiki/Project_Loved). У таких карт есть таблицы рекордов, но они не приносят [очков производительности](/wiki/Performance_points) за прохождение, более того, все рекорды обнуляются при убирании карт из Loved (что обычно случается только по просьбе их создателей). В списке карт в клиенте они отмечены сердцем (![](/wiki/shared/status/loved.png)).
```
Снова переврал. Оригинал: "**may** not meet the ranking criteria"
У тебя же "почти всегда нарушают". 
«Автор» мне не нравится по отношению к мапперам.

2021-03-19 18:48 UTC, UristMcKobold commented on wiki/Beatmap/Category/ru.md
> +Начиная с [7 августа 2020 года](https://osu.ppy.sh/home/changelog/stable40/20200807.3), карты из категории Graveyard, как и [Work in Progress, и Pending](#work-in-progress-и-pending), стали влиять на
```suggestion
Начиная с [7 августа 2020 года](https://osu.ppy.sh/home/changelog/stable40/20200807.3), карты из категории [Graveyard](#graveyard), как и [Work in Progress, и Pending](#work-in-progress-и-pending), стали влиять на число игр пользователя и его общее число очков. Помимо этого, на странице таких карт можно посмотреть игровую статистику (число игр, процент успешных прохождений и наиболее сложные участки), до этого присущую только картам из категорий [Qualified](#qualified) и [Ranked](#ranked).
```

2021-03-20 00:02 UTC, TicClick commented on wiki/Beatmap/Category/ru.md
> +В категорию Graveyard попадают карты, которыми больше никто не занимается. Они автоматически перемещаются сюда из категорий [Work in Progress и Pending](#work-in-progress-и-pending), если их не обнов
вот что значит лениться вычитывать. спасибо

2021-03-20 00:06 UTC, TicClick commented on wiki/Beatmap/Category/ru.md
> +Work in Progress (обычно сокращается до *WIP*) и Pending — категории, куда карты попадают сразу после загрузки. Отсюда их путь лежит в категорию [Qualified](#qualified) в случае [номинации](/wiki/Bea
```suggestion
Work in Progress (обычно сокращается до *WIP*) и Pending — категории, куда карты попадают сразу после загрузки. Отсюда их путь лежит в категорию [Qualified](#qualified) в случае [номинации](/wiki/Beatmap_ranking_procedure#номинация) как минимум двумя [номинаторами](/wiki/People/The_Team/Beatmap_Nominators). Перед этим они проходят стадию [моддинга](/wiki/Modding), когда другие пользователи в роли [моддеров](/wiki/Glossary#modder) вносят свои замечания и предложения по улучшению. У карт в Work in Progress и Pending нет таблиц рекордов, но при прохождении они влияют на [игровую статистику](#статистика-неранкнутых-карт). В списке карт в клиенте они отмечены знаком вопроса (![](/wiki/shared/status/pending.png)).
```

2021-03-20 09:41 UTC, UristMcKobold requested changes

2021-03-20 09:41 UTC, UristMcKobold commented on wiki/Beatmap/Category/ru.md
> +Карты категории Loved могут нарушать [критерии ранкинга](/wiki/Ranking_Criteria), но, тем не менее, игровое сообщество их *любит* и каждый месяц пополняет эту категорию в рамках [Project Loved](/wiki
```suggestion
Карты категории Loved могут нарушать [критерии ранкинга](/wiki/Ranking_Criteria), но, тем не менее, игровое сообщество их *любит* и каждый месяц пополняет эту категорию в рамках [Project Loved](/wiki/Project_Loved). У таких карт есть таблицы рекордов, но они не приносят [очков производительности](/wiki/Performance_points) за прохождение, более того, все рекорды обнуляются при удалении карт из Loved (что обычно случается только по просьбе их создателей). В списке карт в клиенте они отмечены сердцем (![](/wiki/shared/status/loved.png)).
```
«убирание» слишком разговорно звучит.

2021-03-20 09:41 UTC, UristMcKobold commented on wiki/Beatmap/Category/ru.md
> +Категория [Qualified](#qualified) была добавлена в августе 2014 года в рамках [реформирования BAT](https://osu.ppy.sh/home/news/2014-08-21-restructuring-of-the-bat), чтобы только что ранкнутые карты
```suggestion
Категория [Qualified](#qualified) была добавлена в августе 2014 года в рамках [реформирования BAT](https://osu.ppy.sh/home/news/2014-08-21-restructuring-of-the-bat), чтобы только что ранкнутые карты были более заметны. Если такую карту дисквалифицировали и перемещали назад в Pending, это никак не отражалось на статистике игроков: Qualified с самого начала задумывалась как категория с временными рекордами. Такой метод позволял игрокам не рассчитывать на гарантированный ранк, а также сильно уменьшил их негативное отношение к анранку карт.
```
Два раза «временно» не нужно, да и категория-то не временная, она уже столько лет с нами.
«сформировать правильные ожидания» звучит не по-русски. Оригинальное «set correct expectations» в моём варианте раскрыл.

2021-03-20 11:01 UTC, TicClick commented on wiki/Beatmap/Category/ru.md
> +Категория [Qualified](#qualified) была добавлена в августе 2014 года в рамках [реформирования BAT](https://osu.ppy.sh/home/news/2014-08-21-restructuring-of-the-bat), чтобы только что ранкнутые карты
чуть подправил (метод -> подход) и принял

2021-03-20 15:38 UTC, TPGPL approved these changes

2021-03-20 15:38 UTC, merged