[RU] Update Beatmap/Difficulty
ppy/osu-wiki pull request #5060
Opened 2021-03-13 18:24 UTC by TicClick

2021-03-19 18:25 UTC, UristMcKobold requested changes

2021-03-19 18:25 UTC, UristMcKobold commented on wiki/Beatmap/Difficulty/ru.md
> +**Сложность** карты — это игровой уровень, хранящийся в текстовом файле [формата `.osu`](/wiki/osu!_File_Formats/Osu_(file_format)). Он состоит из [игровых объектов](/wiki/Hit_object), которые принад
```suggestion
**Сложность** карты — это игровой уровень, хранящийся в текстовом файле [формата `.osu`](/wiki/osu!_File_Formats/Osu_(file_format)). Он состоит из [игровых объектов](/wiki/Hit_object), относящихся к отдельному [режиму игры](/wiki/Game_mode) и расположенные в соответствии с [таймингом](/wiki/Glossary#timing-section) песни. У сложности есть несколько компонентов, влияющих на игровой процесс. По названию и количеству [звёзд](/wiki/Beatmapping/Star_rating) обычно можно сказать, какой уровень навыков она требует.
```
Мне тут не нравится связка «объекты» и «принадлежат», как будто они имущество какое-то. 
Я бы не стал тут уточнять, что это «звёзды сложности», потому что звёзды в осу почти всегда относятся к звёздам сложности, иногда к паттернам, но тут очевиден контекст. И мне лично не нравится словосочетание «число звёзд», но можешь оставить.

2021-03-19 18:25 UTC, UristMcKobold commented on wiki/Beatmap/Difficulty/ru.md
> +Игровые объекты объединяются в [паттерны](/wiki/Beatmap/Pattern), также зависящие от игровых режимов и определяющие общий стиль, внешний вид сложности и процесс её прохождения. На процесс игры также
```suggestion
Игровые объекты объединяются в [паттерны](/wiki/Beatmap/Pattern), также зависящие от игровых режимов и определяющие общий стиль, внешний вид сложности и процесс её прохождения. На процесс игры также влияют [настройки сложности](/wiki/Beatmap_Editor/Song_Setup#difficulty), установленные её создателем или изменённые с помощью [игровых модификаторов](/wiki/Game_modifier).
```
Когда дело касается мапперов, «автор» не очень подходит, как по мне.

2021-03-19 18:25 UTC, UristMcKobold commented on wiki/Beatmap/Difficulty/ru.md
> +[Визуальные элементы](/wiki/Beatmap), в отличие от паттернов и игровых объектов, служат для украшения карты; почти все из них можно отключить в [визуальных настройках](/wiki/Visual_Settings). Некотор
```suggestion
[Визуальные элементы](/wiki/Beatmap), в отличие от паттернов и игровых объектов, служат для украшения карты; почти все из них можно отключить в [визуальных настройках](/wiki/Visual_Settings). Некоторые из таких элементов, например, [сториборды](/wiki/Storyboards) или [скины](/wiki/Skinning), относятся ко всей карте, но большинство меняются от одной сложности к другой (к примеру, [киаи](/wiki/Kiai_time) и [цвета комбо](/wiki/Glossary/Combo_colour)).
```
Киаи — это и так участки. Я бы ещё уточнил, что цвета комбо, потому что «комбо-цвета» вызывает ощущение, что это какие-то сообо цвета, а на самом деле это просто цвета, которые относятся к комбо.

2021-03-19 23:47 UTC, TicClick commented on wiki/Beatmap/Difficulty/ru.md
> +**Сложность** карты — это игровой уровень, хранящийся в текстовом файле [формата `.osu`](/wiki/osu!_File_Formats/Osu_(file_format)). Он состоит из [игровых объектов](/wiki/Hit_object), которые принад
я немного подправил на свой лад, спасибо, так в любом случае лучше. и да, 5.3, 7.11 и так далее — это числа, не количества

2021-03-20 09:16 UTC, UristMcKobold submitted a review, later dismissed

2021-03-20 15:36 UTC, TPGPL approved these changes

2021-03-20 15:37 UTC, merged