[RU] Add Ranking queue
ppy/osu-wiki pull request #5062
Opened 2021-03-13 18:57 UTC by TicClick

2021-03-19 18:53 UTC, UristMcKobold requested changes

2021-03-19 18:53 UTC, UristMcKobold commented on wiki/Beatmap_ranking_procedure/Ranking_queue/ru.md
> +**Очередь ранкинга** отвечает за перемещение [карт](/wiki/Beatmap) из [Qualified](/wiki/Beatmap/Category#qualified) в [Ranked](/wiki/Beatmap/Category#ranked). Ежедневно попасть в Ranked могут по 10 к
```suggestion
**Очередь ранкинга** отвечает за перемещение [карт](/wiki/Beatmap) из [Qualified](/wiki/Beatmap/Category#qualified) в [Ranked](/wiki/Beatmap/Category#ranked). Ежедневно попасть в Ranked могут по 10 карт из каждого [игрового режима](/wiki/Game_mode), если они провели в Qualified как минимум 7 дней. Время перемещения определяется случайным образом
```
В оригинале each помогает понять, что имеется в виду по 10 из каждого.

2021-03-19 18:53 UTC, UristMcKobold commented on wiki/Beatmap_ranking_procedure/Ranking_queue/ru.md
> +Когда карту [дисквалифицируют](/wiki/Beatmap_ranking_procedure#cброс-номинации), то время, которое она провела в Qualified, сохраняется и учитывается при повторной квалификации и попадании в очередь
```suggestion
Когда карту [дисквалифицируют](/wiki/Beatmap_ranking_procedure#cброс-номинации), то время, которое она провела в Qualified, сохраняется и учитывается при повторной квалификации и попадании в очередь ранкинга. Время, которое карта может таким образом «сэкономить», ограничено шестью днями, чтобы все карты проводили в Qualified как минимум полные сутки.
```
Сутки — это и так одни сутки.

2021-03-19 23:48 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/Ranking_queue/ru.md
> +Когда карту [дисквалифицируют](/wiki/Beatmap_ranking_procedure#cброс-номинации), то время, которое она провела в Qualified, сохраняется и учитывается при повторной квалификации и попадании в очередь
всё так.

2021-03-20 09:25 UTC, UristMcKobold approved these changes

2021-03-20 15:32 UTC, TPGPL approved these changes

2021-03-20 15:32 UTC, merged