[RU] add BBCode
ppy/osu-wiki pull request #5063
Opened 2021-03-13 21:31 UTC by TicClick

2021-03-25 18:10 UTC, UristMcKobold requested changes

2021-03-25 18:35 UTC, TicClick commented on wiki/BBCode/ru.md
> +Тег `[url]` создаёт кликабельную ссылку с указанным названием.
не лишние, это широко распространённый термин, потому что по ссылкам кликают. единственное, что я могу принять, это _активную_ ссылку.

2021-03-25 20:08 UTC, UristMcKobold commented on wiki/BBCode/ru.md
> +Тег `[url]` создаёт кликабельную ссылку с указанным названием.
А надо ли вообще уточнять, что ссылка кликабельная? Очевидно, что если ссылка, то кликабельная, надо уточнять только в случае, если она НЕ кликабельная.

2021-03-25 20:23 UTC, TicClick commented on wiki/BBCode/ru.md
> +Тег `[url]` создаёт кликабельную ссылку с указанным названием.
ну, ссылка так-то может быть и некликабельной (неактивной): `https://ya.ru`, так что нет, не очевидно, это не эквивалентно.

другое дело, что слово и правда лучше выбросить

2021-03-25 20:28 UTC, UristMcKobold approved these changes

2021-03-27 20:59 UTC, TPGPL approved these changes

2021-03-27 20:59 UTC, merged