[RU] Retranslate Beatmap
ppy/osu-wiki pull request #5066
Opened 2021-03-14 18:23 UTC by TicClick

2021-03-14 19:54 UTC, HibanaSama reviewed
мини-ревью

2021-03-14 19:54 UTC, HibanaSama commented on wiki/Beatmap/ru.md
> +*Примечание: некоторые из аудио- или визуальных компонент карты можно отключить на [панели визуальных настроек](/wiki/Visual_Settings).*
```suggestion
*Примечание: некоторые из аудио- или визуальных компонентов карты можно отключить на [панели визуальных настроек](/wiki/Visual_Settings).*
```
потерянное окончание

2021-03-14 19:54 UTC, HibanaSama commented on wiki/Beatmap/ru.md
> +**Карта** (иногда *мапсет*) — это набор игровых уровней ([сложностей](#сложность)), сделанных для одной и той же песни и состоящих из различных [объектов](/wiki/Hit_object). В состав карты, помимо сл
```suggestion
**Карта** (иногда *мапсет*) — это набор игровых уровней ([сложностей](#сложность)), сделанных для одной и той же песни и состоящих из различных [объектов](/wiki/Hit_object). В состав карты, помимо сложностей, входят и другие компоненты, упакованные в архив с [расширением `.osz`](/wiki/osu!_File_Formats/Osz_(file_format)):
```
упакованные *(куда?)* в архив

2021-03-14 19:54 UTC, HibanaSama commented on wiki/Beatmap/ru.md
> +Beatmaps can be obtained through a few different ways:
английский ¯\\_(ツ)\_/¯

2021-03-19 19:35 UTC, UristMcKobold requested changes

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +**Сложность** — это файл с [расширением `.osu`](/wiki/osu!_File_Formats/Osu_(file_format)), который описывает расположение игровых объектов, хитсаундов и эффектов вроде [киаи](/wiki/Kiai_time). В нём
```suggestion
**Сложность** — это файл с [расширением `.osu`](/wiki/osu!_File_Formats/Osu_(file_format)), который содержит в себе расположение игровых объектов, хитсаундов и эффектов вроде [киаи](/wiki/Kiai_time). В нём также указаны [настройки сложности](/wiki/Beatmap_Editor/Song_Setup#difficulty) и другие параметры, влияющие на игровой процесс. Разные сложности имеют разную структуру и иногда созданы только для одного [игрового режима](/wiki/Game_mode). Для оценки требуемого уровня игровых навыков стоит воспользоваться [звёздами сложности](/wiki/Beatmapping/Star_rating).
```
Файл "описывает"?

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +## Публикация карты
```suggestion
## Загрузка карты на сервер
```
У тебя и в других статьях используется «публикация», но я бы подумал над этим переводом. Вариант с «загрузкой» ближе по смыслу, но может быть истолкован иначе, из-за чего приходится добавлять «на сервер» или «на сайт», однако и «публикациия карты» вызывает немного не те ассоциации.

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +После того, как работа над картой завершена, её можно [опубликовать](/wiki/Glossary#bss) в [списке карт](https://osu.ppy.sh/beatmapsets) на сайте. Несмотря на то, что формально у каждой карты [только
```suggestion
После того, как работа над картой завершена, её можно [опубликовать](/wiki/Glossary#bss) в [список карт](https://osu.ppy.sh/beatmapsets) на сайте. Несмотря на то, что формально у каждой карты [только один автор](/wiki/Beatmap/Beatmap_host), над ней зачастую может работать несколько человек. Они могут как объединять свои усилия, работая над [коллабами](/wiki/Beatmap/Beatmap_collaborations), так и в одиночку создавать [гостевые сложности](/wiki/Beatmap/Guest_difficulty).
```
Поменял падеж, так как карта публикуется В список карт, а не ИЗ списка карт.

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +Некоторые категории имеют отдельные [критерии для публикации](/wiki/Ranking_Criteria), а для карт, находящихся в них, действуют временные или постоянные [таблицы рекордов](#таблицы-рекордов). Чтобы у
```suggestion
Некоторые категории имеют отдельные [критерии для публикации](/wiki/Ranking_Criteria), а для карт, находящихся в них, действуют временные или постоянные [таблицы рекордов](#таблицы-рекордов). Чтобы у карты появилась такая таблица, ей нужно пройти [процедуру ранкинга](/wiki/Beatmap_ranking_procedure) (другой способ — получить поддержку сообщества и попасть в [категорию Loved](Category#loved)).
```
Откуда ты знаешь, что менее популярный?! В оригинале такого нет, да.

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +Все опубликованные карты содержатся в [списке на сайте osu!](https://osu.ppy.sh/beatmapsets). Там их можно отфильтровать по требуемым критериям (например, только карты для [osu!taiko](/wiki/Game_mode
```suggestion
Все опубликованные карты содержатся в [списке на сайте osu!](https://osu.ppy.sh/beatmapsets). Там их можно отфильтровать по заданным критериям (например, только карты для [osu!taiko](/wiki/Game_mode/osu!taiko), сделанные определённым маппером) и по очереди скачать. У обладателей [osu!supporter](/wiki/osu!supporter) есть доступ к расширенным фильтрам, к примеру, поиску карты по ранку поставленного на ней рекорда.
```
Требуемых кем?

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +Карты, ранкнутые в одном и том же месяце или объединённые общей тематикой (например, у них один и тот же артист), можно скачать одним архивом, который называется *подборкой*. Список официальных подбо
```suggestion
Карты, ранкнутые в одном и том же месяце или объединённые общей тематикой (например, у них один и тот же исполнитель), можно скачать одним архивом, который называется *подборкой*. Список официальных подборок расположен [на сайте osu!](https://osu.ppy.sh/beatmaps/packs).
```

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +Карты, которые имеют таблицы рекордов, позволяют игрокам разных режимов набирать [очки производительности (pp)](/wiki/Performance_points) и [соревноваться друг с другом](/wiki/Ranking). В osu! есть н
```suggestion
Карты, которые имеют таблицы рекордов, позволяют игрокам разных режимов набирать [очки производительности (pp)](/wiki/Performance_points) и [соревноваться друг с другом](/wiki/Ranking). В osu! есть несколько типов таблиц, почти все из которых, кроме первого, доступны для просмотра только обладателям [osu!supporter](/wiki/osu!supporter):
```
Вообще не понимаю, что такое ранкинги.

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +- Ранкинг среди друзей.
```suggestion
- Глобальная таблица рекордов, в которой участвуют все активные игроки;
- Глобальная таблица рекордов для разных комбинаций [игровых модификаторов](/wiki/Game_modifier);
- Таблица рекордов в рамках одной страны (участвуют игроки с одним и тем же флагом);
- Таблица рекордов среди друзей.
```
Не наборы, а комбинации, так как HD+FL — это скорее комбинация, а не набор. Впрочем, разница минимальна.

2021-03-19 19:35 UTC, UristMcKobold commented on wiki/Beatmap/ru.md
> +С самых ранних дней существования osu! как игроки, так и мапперы старались выделить уникальные и идеально выполненные карты среди остальных. Один из первых достоверно известных подходов — ежемесячные
```suggestion
С самых ранних дней существования osu! как игроки, так и мапперы старались выделить уникальные и отлично сделанные карты среди остальных. Один из первых достоверно известных подходов — ежемесячные и сезонные чарты, где в качестве приза за первые места выдавали [osu!supporter](/wiki/osu!supporter).
```
Какой-то слишком большой прыжок от оригинального "excellent"  в "идеально" у тебя.

2021-03-19 23:49 UTC, TicClick commented on wiki/Beatmap/ru.md
> +*Примечание: некоторые из аудио- или визуальных компонентов карты отключаются на [панели визуальных настроек](/wiki/Visual_Settings).*
пускай

2021-03-19 23:50 UTC, TicClick commented on wiki/Beatmap/ru.md
> +## Публикация карты
ну смотри

2021-03-19 23:52 UTC, TicClick commented on wiki/Beatmap/ru.md
> +Некоторые категории имеют отдельные [критерии для публикации](/wiki/Ranking_Criteria), а для карт, находящихся в них, действуют временные или постоянные [таблицы рекордов](#таблицы-рекордов). Чтобы у
а оттуда, что я взял и ~~посчитал число карт в ranked и loved и вычислил процентное соотношение мапперов, занимающихся тем и другим.~~ прикинул, сколько карт каждый месяц попадает в Loved, а сколько — в Ranked.

алсо оригинал тоже я писал.

но, пожалуй, это не лучший оборот для статьи

2021-03-19 23:53 UTC, TicClick commented on wiki/Beatmap/ru.md
> +Все опубликованные карты содержатся в [списке на сайте osu!](https://osu.ppy.sh/beatmapsets). Там их можно отфильтровать по требуемым критериям (например, только карты для [osu!taiko](/wiki/Game_mode
ну, точно так же можно сказать и про «заданным», и про «необходимым» — кем, кому?. пользователем, пользователю. но вообще да.

2021-03-19 23:54 UTC, TicClick commented on wiki/Beatmap/ru.md
> +С самых ранних дней существования osu! как игроки, так и мапперы старались выделить уникальные и идеально выполненные карты среди остальных. Один из первых достоверно известных подходов — ежемесячные
не знаю, о чём я думал.

2021-03-22 20:34 UTC, UristMcKobold approved these changes

2021-03-22 21:09 UTC, TPGPL approved these changes

2021-03-22 21:12 UTC, merged