Add TKBC2 Article
ppy/osu-wiki pull request #5080
Opened 2021-03-16 09:06 UTC by Hoshikuz

The process is all done.

2021-03-16 10:32 UTC, Nivalyx reviewed
the whole pr seems to be alright but i would like to specifically point out that right now you're missing the flags which are supposed to be attached to the corresponding staffs/winners username as follows :

![image](https://user-images.githubusercontent.com/36564236/111294510-fc2ff480-867c-11eb-8cfb-76fa2c1cf39b.png)

``![][flag_KR]``
``[flag_KR]: /wiki/shared/flag/KR.gif "South Korea"``

2021-03-16 10:32 UTC, Nivalyx commented on wiki/Contests/TKBC/2/en.md
> +The Taiko Korean Beatmap Contest #2 is run by members of the Korean osu!taiko mapping community.
```The Taiko Korean Beatmap Contest #2 was run by members of the Korean osu!taiko mapping community.```

2021-03-16 10:32 UTC, Nivalyx commented on wiki/Contests/TKBC/2/en.md
> +| Manager | [[Karcher] 2](https://osu.ppy.sh/users/9892196), [Civil oath](https://osu.ppy.sh/users/3216107) |
a lot of [escape characters](http://bookdown.org/yihui/rmarkdown-cookbook/special-chars.html) are seeming to be missing on these tables at the moment, namely :

- `[[Karcher] 2]` should be --> `[\[Karcher\] 2]`
- `[4_4]` should be --> `[4\_4]`

2021-03-17 15:20 UTC, TPGPL requested changes

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +| Submitting Phase | 2020-11-30/2020-12-27 |
```suggestion
| Submission phase | 2020-11-30/2020-12-27 |
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +| Results Announcement | 2021-01-17 |
```suggestion
| Judging phase | 2020-12-28/2021-01-17 |
| Results announcement | 2021-01-17 |
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +- When submitting your map, include the metadata in the email.
```suggestion
- While submitting your beatmap, include the metadata in the email.
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +- Only Koreans can participate this contest.
```suggestion
- Only users from South Korea can participate in this contest.
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +- You can't submit what you uploaded already.
```suggestion
- You can't submit a beatmap you have already uploaded.
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +- You should not reveal your map before the results announcing.
```suggestion
- You should not reveal your map before the results announcement.
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +- If you submit several maps, the last one would be your entry.
```suggestion
- If you submit several beatmaps, the last one will be your entry.
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +- The drain time should be not less than 80 and not more than 150.
```suggestion
- The drain time should not be less than 80 and more than 150.
```

2021-03-17 15:20 UTC, TPGPL commented on wiki/Contests/TKBC/2/en.md
> +- This contest is for osu!taiko mode.
```suggestion
- This contest is for osu!taiko mode.
- The theme for this installment is "Snow" or "Star".
```

2021-03-19 11:12 UTC, TPGPL commented
English article looks fine now, you should apply the changes to the Korean translation

2021-04-03 23:39 UTC, TPGPL commented
@Hoshikuz could you apply the changes to the Korean translation as well, please?

2021-04-04 00:50 UTC, Hoshikuz commented
I forgot this
sorry :c

2021-04-05 18:08 UTC, TPGPL requested changes

2021-04-05 18:08 UTC, TPGPL commented on wiki/Contests/TKBC/2/ko.md
> +[flag_KR]: /wiki/shared/flag/KR.gif "South Korea"
```suggestion
[flag_KR]: /wiki/shared/flag/KR.gif "대한민국"
```

2021-04-05 18:08 UTC, TPGPL commented on wiki/Contests/TKBC/2/ko.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | ![][flag_KR] [ddm](https://osu.ppy.sh/users/7910282) |
the alt texts and tooltips of images have to be translated

for reference:

`![alt-text](image-path "tooltip")`

2021-04-05 18:08 UTC, TPGPL commented on wiki/Contests/TKBC/2/ko.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | 서포터 1개월 |
the alt texts and tooltips of images have to be translated

2021-04-05 18:08 UTC, TPGPL commented on wiki/Contests/TKBC/2/ko.md
> +![TKBC2 logo](img/logo.png)
`TKBC2 logo` has to be translated

2021-04-05 18:08 UTC, TPGPL commented on wiki/Contests/TKBC/2/ko.md
> +| Judge | ![][flag_KR] [\[Karcher\] 2](https://osu.ppy.sh/users/9892196), ![][flag_KR] [Petit](https://osu.ppy.sh/users/4637369), ![][flag_KR] [Ozu](https://osu.ppy.sh/users/980092) |
i think the position names can be translated as well

2021-04-07 08:37 UTC, TPGPL requested changes

2021-04-07 08:37 UTC, TPGPL commented on wiki/Contests/TKBC/2/ko.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3위") | ![][flag_KR] [ddm](https://osu.ppy.sh/users/7910282) |
`Gold crown`, `Silver crown`, `Bronze crown` needs to be translated

2021-04-07 08:37 UTC, TPGPL commented on wiki/Contests/TKBC/2/ko.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3위") | 서포터 1개월 |
`Gold crown`, `Silver crown`, `Bronze crown` needs to be translated

2021-04-08 14:05 UTC, TPGPL approved these changes

2021-04-08 14:05 UTC, merged