[TH] Update Do you want to really ask peppy
ppy/osu-wiki pull request #5088
Opened 2021-03-17 06:49 UTC by Trigonoculus

No longer outdated.

2021-03-30 14:19 UTC, C0NS03L requested changes

2021-03-30 14:19 UTC, C0NS03L commented on wiki/Do_you_really_want_to_ask_peppy/th.md
> +สำหรับปัญหาที่เกี่ยวกับบัญชีของคุณ, ปัญหาด้านการจ่ายเงิน, การแบน, เรื่องเกี่ยวกับทัวร์นาเมนต์ และ **อะไรก็ตามที่เกี่ยวกับการช่วยเหลือบน osu!** กรุณาติิดต่อ[ทีมช่วยเหลือด้านบัญชี](/wiki/People/The_Tea
```suggestion
สำหรับปัญหาที่เกี่ยวกับบัญชีของคุณ, ปัญหาด้านการจ่ายเงิน, การแบน, เรื่องเกี่ยวกับทัวร์นาเมนต์ และ **อะไรก็ตามที่เกี่ยวกับการช่วยเหลือบน osu!** กรุณาติดต่อ[ทีมช่วยเหลือด้านบัญชี](/wiki/People/The_Team/Account_support_team) โดยการส่งอีเมลไปที่ [accounts@ppy.sh](mailto:accounts@ppy.sh) (เรื่องเกี่ยวกับบัญชี) หรือ [osu@ppy.sh](mailto:osu@ppy.sh) (เรื่องอื่น ๆ )
```

2021-03-30 14:32 UTC, Trigonoculus commented on wiki/Do_you_really_want_to_ask_peppy/th.md
> +สำหรับปัญหาที่เกี่ยวกับบัญชีของคุณ, ปัญหาด้านการจ่ายเงิน, การแบน, เรื่องเกี่ยวกับทัวร์นาเมนต์ และ **อะไรก็ตามที่เกี่ยวกับการช่วยเหลือบน osu!** กรุณาติิดต่อ[ทีมช่วยเหลือด้านบัญชี](/wiki/People/The_Tea
thanks, nice catch!

2021-03-30 15:15 UTC, C0NS03L approved these changes

2021-04-02 02:42 UTC, HelloYeew approved these changes

2021-04-03 07:51 UTC, TicClick approved these changes

2021-04-03 07:52 UTC, merged