[ID] Add Game Modifier
ppy/osu-wiki pull request #5100
Opened 2021-03-19 06:57 UTC by hikikuman

Add Indonesian translation.

2021-03-24 12:32 UTC, wowcake requested changes

2021-03-24 12:32 UTC, wowcake commented on wiki/Game_modifier/id.md
> +**Game modifier** (disingkat menjadi "mod") adalah modifikasi opsional terhadap elemen dan pengaturan dari sebuah [beatmap](/wiki/Beatmaps) dimana pengguna dapat mengaktifkannya melalui `Layar Piliha
```suggestion 
**Game modifier** (disingkat menjadi "mod") adalah modifikasi opsional terhadap elemen dan pengaturan dari sebuah [beatmap](/wiki/Beatmaps) dimana pengguna dapat mengaktifkannya melalui `Layar Pilihan Mod` (diatas). Mod dapat membuat beatmap menjadi lebih mudah, lebih sulit, atau hanya untuk kesenangan biasa.
```
untuk pengartian yang lebih baik agar lebih mudah dimengerti

2021-03-24 12:32 UTC, wowcake commented on wiki/Game_modifier/id.md
> +Pengguna dapat mengakses `Layar Pilihan Mod` pada layar pemilihan lagu dengan mengklik tombol `Mods` di pojok kiri bawah layar atau dengan menekan `F1`. Setelah memasuki `Layar Pilihan Mod`, juga ter
```suggestion 
Pengguna dapat mengakses `Layar Pemilihan Mod` pada layar pemilihan lagu dengan mengklik tombol `Mods` di pojok kiri bawah layar atau dengan menekan `F1`. Setelah memasuki `Layar Pemilihan Mod`, juga terdapat shortcut untuk memilih mod secara spesifik. Shortcut tersebut dapat diubah melalui pengaturan.
```
Kenapa untuk teks "Mod Selection", lebih memilih menggunakan "Pilihan" daripada "Pemilihan", Apakah ada alasan tertentu?

2021-03-24 12:32 UTC, wowcake commented on wiki/Game_modifier/id.md
> +*Catatan: Mod ini digunakan dan tersedia beberapa waktu lalu, tetapi sekarang sudah tidak tersedia.*
```suggestion
*Catatan: Mod ini pada dulunya hanya digunakan dan tersedia beberapa waktu yang lalu, tetapi sekarang sudah tidak tersedia.*
```

2021-03-25 13:02 UTC, hikikuman commented on wiki/Game_modifier/id.md
> +*Catatan: Mod ini digunakan dan tersedia beberapa waktu lalu, tetapi sekarang sudah tidak tersedia.*
Agak boros kata itu. `pada dulunya` dan `beberapa waktu yang lalu` punya makna yang sama.

2021-03-25 13:26 UTC, wowcake commented on wiki/Game_modifier/id.md
> +*Catatan: Mod ini digunakan dan tersedia beberapa waktu lalu, tetapi sekarang sudah tidak tersedia.*
Memang sama sih, tapi tujuannya untuk mempersederhana katanya, agar bisa langsung dicerna

Tapi pakai ```beberapa waktu yang lalu``` juga boleh (dengan "yang"-nya telah dimasukkan, sebelumnya dia ```hanya beberapa waktu lalu```)

2021-03-27 11:14 UTC, ZeroPyrozen commented on wiki/Game_modifier/id.md
> +*Untuk penggunaan lainnya, lihat [[Mod (disambiguasi)](/wiki/Disambiguation/Mod).*
Ada typo di `[[Mod (disambiguasi)](/wiki/Disambiguation/Mod).*` seharusnya `[Mod (disambiguasi)](/wiki/Disambiguation/Mod).*`

2021-03-27 11:33 UTC, ZeroPyrozen requested changes
Mohon diubah terlebih dahulu typo pada baris 15.

2021-03-27 11:33 UTC, ZeroPyrozen commented on wiki/Game_modifier/id.md
> +*Untuk penggunaan lainnya, lihat [[Mod (disambiguasi)](/wiki/Disambiguation/Mod).*
Ada typo di `[[Mod (disambiguasi)](/wiki/Disambiguation/Mod).*` seharusnya `[Mod (disambiguasi)](/wiki/Disambiguation/Mod).*`

2021-03-27 14:43 UTC, wowcake submitted a review, later dismissed

2021-03-27 14:43 UTC, wowcake commented on wiki/Game_modifier/id.md
> +Setiap mod dibawah, mempunyai ikon dari mode permainan yang cocok (![][o!s] ![][o!t] ![][o!c] ![][o!m]) di samping kanan masing-masing mod.
```suggestion
Setiap mod yang berada dibawah, mempunyai ikon dari game mode yang sesuai (![][o!s] ![][o!t] ![][o!c] ![][o!m]) di samping kanan masing-masing mod.

2021-03-27 14:43 UTC, wowcake commented on wiki/Game_modifier/id.md
> +Pengguna dapat mengakses `Layar Pilihan Mod` pada layar pemilihan lagu dengan mengklik tombol `Mods` di pojok kiri bawah layar atau dengan menekan `F1`. Setelah memasuki `Layar Pilihan Mod`, juga ter
```suggestion
Pemain dapat mengakses `Layar Pilihan Mod` pada layar pemilihan lagu dengan mengklik tombol `Mods` di pojok kiri bawah layar atau dengan menekan `F1`. Setelah memasuki `Layar Pilihan Mod`, Shortcut untuk memilih mod tertentu juga tersedia. Shortcut tersebut dapat diubah melalui pengaturan.

2021-03-27 14:43 UTC, wowcake commented on wiki/Game_modifier/id.md
> +**Game modifier** (disingkat menjadi "mod") adalah modifikasi opsional terhadap elemen dan pengaturan dari sebuah [beatmap](/wiki/Beatmaps) dimana pengguna dapat mengaktifkannya melalui `Layar Piliha
```suggestion
**Game modifier** (disingkat menjadi "mod") adalah sebuah modifikasi opsional terhadap elemen dan kesulitan dari sebuah [beatmap](/wiki/Beatmaps) dimana pemanin dapat mengaktifkannya melalui `Layar Pemilihan Mod` (diatas). Mod dapat membuat beatmap menjadi lebih mudah, lebih sulit, atau hanya kesenangan biasa.

2021-03-27 14:43 UTC, wowcake commented on wiki/Game_modifier/id.md
> +**Game modifier** (disingkat menjadi "mod") adalah modifikasi opsional terhadap elemen dan pengaturan dari sebuah [beatmap](/wiki/Beatmaps) dimana pengguna dapat mengaktifkannya melalui `Layar Piliha
cuma pendapat aja sih dibagian ```kesulitan dari sebuah beatmap``` nya

2021-03-30 04:48 UTC, hikikuman commented on wiki/Game_modifier/id.md
> +Setiap mod dibawah, mempunyai ikon dari mode permainan yang cocok (![][o!s] ![][o!t] ![][o!c] ![][o!m]) di samping kanan masing-masing mod.
seperti yang udah didiskusiin di `#osu-webノdevelopment` discord osu! indo, `game mode` diterjmahkan jadi `mode permainan` secara general (atau `jenis permainan`).

2021-03-30 04:52 UTC, ZeroPyrozen submitted a review, later dismissed

2021-03-31 09:21 UTC, wowcake submitted a review, later dismissed

2021-03-31 09:21 UTC, wowcake commented on wiki/Game_modifier/id.md
> +**Game modifier** (disingkat menjadi "mod") adalah modifikasi opsional terhadap elemen dan pengaturan dari sebuah [beatmap](/wiki/Beatmaps) dimana pengguna dapat mengaktifkannya melalui `Layar Pemili
```suggestion
**Game modifier** (disingkat menjadi "mod") adalah sebuah modifikasi opsional terhadap elemen dan kesulitan dari sebuah [beatmap](/wiki/Beatmaps) dimana pemain dapat mengaktifkannya melalui `Layar Pemilihan Mod` (diatas). Mod dapat membuat beatmap menjadi lebih mudah, lebih sulit, atau hanya untuk kesenangan biasa.

2021-03-31 09:21 UTC, wowcake commented on wiki/Game_modifier/id.md
> +Pengguna dapat mengakses `Layar Pemilihan Mod` pada layar pemilihan lagu dengan mengklik tombol `Mods` di pojok kiri bawah layar atau dengan menekan `F1`. Setelah memasuki `Layar Pemilihan Mod`, juga
```suggestion
Pemain dapat mengakses `Layar Pemilihan Mod` pada layar pemilihan lagu dengan mengklik tombol `Mods` di pojok kiri bawah layar atau dengan menekan `F1`. Setelah memasuki `Layar Pemilihan Mod`, Shortcut untuk memilih mod tertentu juga tersedia. Shortcut tersebut dapat diubah melalui pengaturan.

2021-03-31 09:32 UTC, wowcake approved these changes
checked 👍

2021-03-31 09:34 UTC, ZeroPyrozen submitted a review, later dismissed
All good!

2021-04-02 00:38 UTC, TPGPL approved these changes

2021-04-02 00:38 UTC, merged