[FR] Abandoned wasteland
ppy/osu-wiki pull request #5113
Opened 2021-03-23 16:33 UTC by DoryanR

Proposal for the French translation of the wiki page "Abandoned wasteland".

2021-04-07 22:51 UTC, Airwam requested changes

2021-04-07 22:51 UTC, Airwam commented on wiki/Abandoned_wasteland/fr.md
> +Le **Abandoned wasteland** est un [sous-forum](https://osu.ppy.sh/community/forums) privé utilisé pour cacher les forums et les sujets du forum de la vue de tous. Ce sous-forum est uniquement accessi
```suggestion
Le **Abandoned wasteland** est un [sous-forum](https://osu.ppy.sh/community/forums) privé utilisé pour cacher les forums et les sujets du forum de la vue de tous. Ce sous-forum est uniquement accessible aux modérateurs qui ont les droits pour modifier les forums. Les instructions aux modérateurs le concernant sont : `Mettez les choses dont nous n'avons pas vraiment besoin ici.`.
```

2021-04-07 22:51 UTC, Airwam commented on wiki/Abandoned_wasteland/fr.md
> +Les forums et les sujets sont dits "Wastelanded" lorsqu'ils seront déplacés vers ce forum.
```suggestion
Les forums et sujets sont dits "Wastelanded" lorsqu'ils sont déplacés vers ce forum.
```

2021-04-28 16:07 UTC, DoryanR commented
@Airwam Need a recheck from you

2021-05-06 16:26 UTC, Airwam approved these changes
Seems good to me

2021-05-11 20:02 UTC, merged