[FR] Update Accuracy
ppy/osu-wiki pull request #5114
Opened 2021-03-23 17:49 UTC by DoryanR

Proposal to update the French translation of the wiki page "Accuracy".

2021-03-27 12:23 UTC, Ganondorfosu requested changes

2021-03-27 12:23 UTC, Ganondorfosu commented on wiki/Accuracy/fr.md
> +La Vitesse représente les tr/min (tours par minute) de toutes les toupies de la beatmap. `Max` est la valeur de tr/min le plus élevé que le joueur a atteint dans n'importe quel spinner de la beatmap.
```suggestion
`Speed (Vitesse)` représente le RPM (Tours par minute) moyen de tous les spinners de la beatmap. `Max` est la valeur de RPM la plus élevée que le joueur a atteint tous spinners confondus lors de la partie.
```

2021-03-27 12:48 UTC, DoryanR commented on wiki/Accuracy/fr.md
> +`Taux instable` représente la cohérence du timing des hits, les chiffres les plus bas étant les meilleurs (les meilleurs joueurs obtiennent souvent un score inférieur à 100). Notez que la valeur mesu
Je retire `(Taux d'instabilité)` car on a la traduction dans le titre de la section.

2021-03-27 12:48 UTC, DoryanR commented on wiki/Accuracy/fr.md
> +La Vitesse représente les tr/min (tours par minute) de toutes les toupies de la beatmap. `Max` est la valeur de tr/min le plus élevé que le joueur a atteint dans n'importe quel spinner de la beatmap.
Pareil ici

2021-03-27 12:56 UTC, Ganondorfosu commented on wiki/Accuracy/fr.md
> +Dans osu!taiko, la précision est calculée en prenant la somme de la précision des notes (à quel point vous étiez proche de hit la note à temps) divisée par le nombre total de notes marquées jusqu'à p
```suggestion
Dans osu!taiko, la précision est calculée en prenant la somme de la précision des notes (à quel point vous étiez proche de toucher la note à temps) divisée par le nombre total de notes marquées jusqu'à présent. Les précisions des notes sont étiquetées comme tel : GREAT (良) compte pour 100%, GOOD (可) compte pour 50% (half), et MISS/BAD (不可) compte pour 0% (ce qui casse aussi le combo). Les Drum rolls et spinners n'influencent pas la précision.
```

2021-04-01 14:28 UTC, DoryanR commented
@Ganondorfosu Need a recheck from you

2021-05-12 09:32 UTC, osuShiro commented on wiki/Accuracy/fr.md
> +La valeur `Error` affichera toujours deux valeurs qui représentent l'écart moyen entre les premiers résultats et les derniers résultats. Plus la valeur [Overall Difficulty (OD)](/wiki/Beatmapping/Ove
"premiers résultats et derniers résultats" est pas clair du tout (l'article anglais lui-même est pas clair pour être honnête)

2021-05-21 16:50 UTC, TicClick submitted a review, later dismissed

2021-05-21 16:51 UTC, TicClick approved these changes

2021-05-21 16:52 UTC, TicClick commented
Shiro won't be able to recheck this in the meantime, so here we are

2021-05-21 16:52 UTC, merged