[FR] Update BanchoBot
ppy/osu-wiki pull request #5118
Opened 2021-03-24 17:36 UTC by DoryanR

Proposal to update the French translation of the wiki page "BanchoBot".

2021-03-27 22:38 UTC, Ganondorfosu requested changes

2021-03-27 22:38 UTC, Ganondorfosu commented on wiki/BanchoBot/fr.md
> +Il y a un total de 7 statuts qui peuvent être affichés par la commande `!stats` : Editing, Idle, Lobby, Modding, Multiplayer, Multiplaying et Playing. Un exemple d'envoi de cette commande pour un uti
```suggestion
Il y a un total de 7 statuts qui peuvent être affichés par la commande `!stats` : Editing, Idle, Lobby, Modding, Multiplayer, Multiplaying et Playing. Un exemple d'envoi de cette commande pour un utilisateur en train de jouer est montré ci-dessous :
```

2021-04-01 14:28 UTC, DoryanR commented
@Ganondorfosu Need a recheck from you

2021-05-12 09:44 UTC, osuShiro commented on wiki/BanchoBot/fr.md
> +`!report` notifie aux membres de la [Global Moderation Team](/wiki/Global_Moderation_Team) sur le comportement inapproprié d'un utilisateur. Si un utilisateur a des espaces dans son nom d'utilisateur
```suggestion
`!report` notifie les membres de la [Global Moderation Team](/wiki/Global_Moderation_Team) du comportement inapproprié d'un utilisateur. Si un utilisateur a des espaces dans son nom d'utilisateur, remplacez-les par des traits de soulignement (par exemple, `nom d'utilisateur super cool` devient `nom_d'utilisateur_super_cool`). Pour signaler un modérateur, contactez l'[équipe d'assistance aux comptes](/wiki/People/The_Team/Account_support_team#support@ppy.sh). Un exemple de signalement d'un utilisateur normal par BanchoBot est présenté ci-dessous :
```

2021-05-12 09:45 UTC, osuShiro approved these changes

2021-05-12 09:46 UTC, merged