[FR] Beatmap stubs
ppy/osu-wiki pull request #5130
Opened 2021-03-27 15:55 UTC by DoryanR

Translation of the following wiki pages:

- Beatmap/Authentic
- Beatmap/Background
- Beatmap/Beatmap_collaborations
- Beatmap/Beatmap_description
- Beatmap/Beatmap_host
- Beatmap/Break
- Beatmap/Guest_difficulty
- Beatmap/Hype
- Beatmap/Marathon/
- Beatmap/Pattern
- Beatmap/TAG
- Beatmap/Technical_maps

2021-04-07 20:56 UTC, Airwam commented on wiki/Beatmap/Background/fr.md
> +Les arrière-plans sont affichés sur les beatmaps, sur l'[écran de sélection des chansons](/wiki/Interface#song-selection-screen), et pendant le jeu.
Les arrière-plans sont affichés sur les beatmaps, sur l'[écran de sélection des musiques](/wiki/Interface#song-selection-screen), et pendant le jeu.

2021-04-07 21:00 UTC, Airwam commented on wiki/Beatmap/Beatmap_collaborations/fr.md
> +# Beatmap collaborations
# Collaborations de beatmap

2021-04-07 21:01 UTC, Airwam commented on wiki/Beatmap/Beatmap_collaborations/fr.md
> +*Pour obtenir de l'aide pour démarrer une collaboration, voir : [Comment démarrer une beatmap collaboration](/wiki/Guides/Collab_Information)*.
*Pour obtenir de l'aide pour démarrer une collaboration, voir : [Comment démarrer une collaboration de beatmap](/wiki/Guides/Collab_Information)*.

2021-04-07 21:05 UTC, Airwam commented on wiki/Beatmap/Beatmap_collaborations/fr.md
> +Les **beatmap collaborations**, ou ***collabs***, sont des [beatmaps](/wiki/Beatmap) créées par plusieurs personnes. Le terme "collab" peut désigner une difficulté unique ou des [beatmapsets](/wiki/G
Les **collaborations de beatmap**, ou ***collabs***, sont des [beatmaps](/wiki/Beatmap) créées par plusieurs personnes. Le terme "collab" peut désigner une difficulté unique ou des [beatmapsets](/wiki/Glossary#beatmapset) avec des [difficultés d'invités](/wiki/Glossary#guest-difficulté).

2021-04-07 21:06 UTC, Airwam commented on wiki/Beatmap/Beatmap_collaborations/fr.md
> +Les collaboration difficulty sont généralement marquées par "collab" ou la présence de plusieurs noms d'utilisateur dans le nom de la difficulté.
Les difficultés provenant d'une collaboration sont généralement marquées par "collab" ou la présence de plusieurs noms d'utilisateur dans le nom de la difficulté.

2021-04-07 21:08 UTC, Airwam commented on wiki/Beatmap/Beatmap_description/fr.md
> +Les **descriptions de beatmap** sont de petites zones sous la page d'une [beatmap](/wiki/Beatmap) qui donnent aux joueurs des informations sur ladite beatmap en utilisant le [BBCode](/wiki/BBCode). L
```suggestion
Les **descriptions de beatmap** sont de petites zones sous la page d'une [beatmap](/wiki/Beatmap) qui donnent aux joueurs des informations sur ladite beatmap en utilisant le [BBCode](/wiki/BBCode). La plupart des beatmaps [Classées](/wiki/Beatmap/Category#ranked) utilisent au moins une image, un nombre (dépendant du nombre de beatmaps classées par le créateur) et une section de difficulté.
```

2021-04-07 21:12 UTC, Airwam commented on wiki/Beatmap/Beatmap_description/fr.md
> +*Attention : Pour qu'un beatmap soit classé, il est recommandé aux créateurs d'avoir une bonne description du beatmap, mais ce n'est pas obligatoire*.
```suggestion
*Attention : Pour qu'une beatmap soit classée, il est recommandé aux créateurs d'avoir une bonne description de la beatmap, mais ce n'est pas obligatoire*.
```

2021-04-07 21:13 UTC, Airwam commented on wiki/Beatmap/Beatmap_description/fr.md
> +Les descriptions populaires du beatmap comprennent souvent les éléments suivants :
```suggestion
Les descriptions populaires d'une beatmap comprennent souvent les éléments suivants :
```

2021-04-07 21:51 UTC, Airwam requested changes

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Beatmap_description/fr.md
> +- Des informations qui aideraient un joueur à décider s'il veut télécharger le beatmap ou non.
```suggestion
- Des informations qui aideraient un joueur à décider s'il veut télécharger la beatmap ou non.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Beatmap_description/fr.md
> +De nombreuses descriptions de beatmap contiennent au moins une image (souvent un [GIF animé](https://fr.wikipedia.org/wiki/GIF "Wikipédia") d'une certaine sorte), qui est utilisée pour exprimer et il
```suggestion
De nombreuses descriptions de beatmap contiennent au moins une image (souvent un [GIF animé](https://fr.wikipedia.org/wiki/GIF "Wikipédia") d'une certaine sorte), qui est utilisée pour exprimer et illustrer le créateur, la musique et/ou la beatmap d'une manière rapide. Elles peuvent également prendre la place d'un titre ou d'un en-tête pour ajouter du flair et de la qualité. Pour apprendre à ajouter une image à l'aide du BBCode, consultez le [tutoriel de l'article BBCode sur les images](/wiki/BBCode#images).
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Break/fr.md
> +Les **Breaks** sont des sections d'une [beatmap](/wiki/Beatmap) qui n'ont pas de [hit objects](/wiki/Hit_object). Pendant ce temps, le health drain est temporairement interrompue. Les pauses permette
```suggestion
Les **Pauses** sont des sections d'une [beatmap](/wiki/Beatmap) qui n'ont aucun [objet](/wiki/Hit_object). Pendant ce temps, le drain de vie est temporairement interrompu. Les pauses permettent généralement au joueur de reposer son bras pendant un court instant et de repositionner son périphérique d'entrée.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Break/fr.md
> +Selon les paramètres activés, des letterboxes peuvent apparaître lorsqu'une pause est initiée. En outre, un graphique et un son de réussite ou d'échec peuvent apparaître pour indiquer si un joueur s'
```suggestion
Selon les paramètres activés, des letterboxes peuvent apparaître lorsqu'une pause est initiée. En outre, un graphique et un son de réussite ou d'échec peuvent apparaître pour indiquer si le joueur s'en sort bien ou non. Cela n'apparaîtra que s'il y a suffisamment de temps pour que le graphique s'affiche.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Break/fr.md
> +# Break
```suggestion
# Pause
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Une **guest difficulty** (abrégé en *GD*) est une [difficulté](/wiki/Beatmap/Difficulty) d'une [beatmap](/wiki/Beatmap) qui n'est pas créée par l'[hôte de la beatmap](/wiki/Beatmap/Beatmap_host). Ils
```suggestion
Une **guest difficulty** (abrégé en *GD*) est une [difficulté](/wiki/Beatmap/Difficulty) d'une [beatmap](/wiki/Beatmap) qui n'est pas créée par l'[hôte de la beatmap](/wiki/Beatmap/Beatmap_host). Elles peuvent généralement être identifiés par leur nom de difficulté contenant le nom d'utilisateur du créateur invité. Une beatmap comportant plusieurs créateurs est également appelée [collaborative difficulty](/wiki/Beatmap/Beatmap_collaborations).
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Hype/fr.md
> +Chaque [pending](/wiki/Beatmap/Category#pending) d'une [beatmap](/wiki/Beatmap) a un **hype train** qui représente grossièrement le nombre de personnes intéressées à voir la carte [ranked](/wiki/Beat
```suggestion
Chaque [beatmap](/wiki/Beatmap) [en attente](/wiki/Beatmap/Category#pending) a un **hype train** qui représente grossièrement le nombre de personnes intéressées à voir la carte [classée](/wiki/Beatmap/Category#ranked). Les utilisateurs peuvent poster des [discussions sur le thème de la beatmap](/wiki/Beatmap_Discussion) dans l'onglet `Général (Toutes les difficultées)` avec l'option `Hype!` pour contribuer à la Hype d'une beatmap.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Hype/fr.md
> +Les beatmap doivent avoir au moins 5 hype (une mesure complète du train de hype) pour être éligibles à la nomination<!-- TODO: link me -->, un pas vers le classement de la carte.
```suggestion
Les beatmaps doivent avoir au moins 5 hype (une mesure complète du train de hype) pour être éligibles à la nomination<!-- TODO: link me -->, un pas de plus vers le classement de la carte.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Marathon/fr.md
> +Le terme **Marathon** est utilisé pour décrire les [beatmaps](/wiki/Beatmap) d'une durée de cinq minutes ou plus. Il s'agit souvent d'efforts collaboratifs, car le mapping de morceaux plus longs peut
```suggestion
Le terme **Marathon** est utilisé pour décrire les [beatmaps](/wiki/Beatmap) d'une durée de cinq minutes ou plus. Il s'agit souvent d'efforts collaboratifs, car le mapping de morceaux plus longs peut être fatigante lorsque réalisée seule.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Marathon/fr.md
> +Lors de l'introduction des beatmaps marathon, ils devaient à l'origine durer au moins *six* minutes et ne pouvaient inclure qu'une seule difficulté (à l'exception du fait que chaque beatmapset pouvai
```suggestion
Lors de l'introduction des beatmaps marathons, elles devaient à l'origine durer au moins *six* minutes et ne pouvaient inclure qu'une seule difficulté (à l'exception du fait que chaque beatmapset pouvait également inclure une seule difficulté [osu!taiko](/wiki/Game_mode/osu!taiko).
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Marathon/fr.md
> +Les beatmaps marathon devaient également avoir leur difficulté unique nommée "Marathon" pour contourner le système de soumission des beatmap marathon de l'époque et empêcher les beatmapsets marathon
```suggestion
Les beatmaps marathon devaient également avoir leur difficulté unique nommée "Marathon" pour contourner le système de soumission des beatmaps marathon de l'époque et empêcher les beatmapsets marathon d'entrer dans la catégorie [En attente](/wiki/Beatmap/Category#pending). Lors du classement, les beatmaps marathon entrent dans la catégorie Approuvée au lieu de la catégorie [Classée](/wiki/Beatmap/Category#ranked) pour signaler qu'il s'agit d'une beatmap marathon. Cette catégorie a ensuite été abandonnée au profit de la catégorie Classée.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Marathon/fr.md
> +Les beatmaps marathon ont ensuite été modifiées pour inclure des beatmaps avec des drain time de cinq minutes et permettant de nommer les difficultés personnalisées. Cela a duré jusqu'à ce que les rè
```suggestion
Les beatmaps marathon ont ensuite été modifiées pour inclure des beatmaps avec des drain time de cinq minutes et permettant de nommer les difficultés personnalisées. Cela a duré jusqu'à ce que des règles de propagation plus indulgentes soient introduites en 2019.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Pattern/fr.md
> +Un **pattern** est un petit ensemble de [hit objects](/wiki/Hit_Objects) dans une [beatmap](/wiki/Beatmap) arrangé d'une manière significative.
```suggestion
Un **pattern** est un petit ensemble d'[objets](/wiki/Hit_Objects) dans une [beatmap](/wiki/Beatmap) arrangés d'une manière significative.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/TAG/fr.md
> +Le terme **TAG** est utilisé pour décrire les modes faite pour le mode [multijoueur](/wiki/Multi) appelés [Tag Coop ou Tag Team Vs](/wiki/Multi#tag-coop-/-tag-team-vs) où les joueurs essaient de comp
```suggestion
Le terme **TAG** est le terme utilisé pour décrire les modes de jeu en [multijoueur](/wiki/Multi) appelés [Tag Coop ou Tag Team Vs](/wiki/Multi#tag-coop-/-tag-team-vs) où les joueurs essaient de compléter une [beatmap](/wiki/Beatmap) en coopération. Les beatmaps qui sont spécifiquement conçues pour ces modes sont généralement appelés **TAG beatmaps/difficultés**.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/TAG/fr.md
> +Dans ces modes, chaque joueur est responsable d'un [comboset](/wiki/Beatmapping/Combo), et tout au long du morceau, les joueurs passent d'un comboset à l'autre. Pour cette raison, les beatmaps TAG so
```suggestion
Dans ces modes, chaque joueur est responsable d'un [comboset](/wiki/Beatmapping/Combo), et tout au long du morceau, les joueurs passent d'un comboset à l'autre. Pour cette raison, les beatmaps TAG sont conçus de telle manière que leurs combosets sont placés beaucoup plus loin les uns des autres et plus complexes que d'habitude, ce qui les rend presque impossible a jouer seul.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/TAG/fr.md
> +Les [difficultés](/wiki/Beatmap/Difficulty) TAG sont généralement indiquées par l'utilisation du terme "TAG" dans le nom de la difficulté de la beatmap. Le plus souvent, "TAG" est suivi d'un chiffre,
```suggestion
Les [difficultés](/wiki/Beatmap/Difficulty) TAG sont généralement indiquées par l'utilisation du terme "TAG" dans le nom de la difficulté de la beatmap. Le plus souvent, "TAG" est suivi d'un chiffre, qui indique le nombre de joueurs pour laquelle la beatmap est destinée (par exemple, "TAG2" pour deux joueurs ou "TAG4" pour quatre joueurs).
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/TAG/fr.md
> +En raison de leur nature, les difficultés des TAG sont soit non classées, soit Loved, car elles sont intentionnellement conçues pour être presque impossibles pour un seul joueur.
```suggestion
En raison de leur nature, les difficultés des TAG sont soit non classées, soit Aimée, car elles sont intentionnellement conçues pour être presque impossibles pour un seul joueur.
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +*Attention : La définition "la plus large" ne requiert qu'un ou deux des aspects énumérés pour définir une beatmap comme étant une technologie.*
```suggestion
*Attention : La définition "la plus large" ne requiert qu'un ou deux des aspects énumérés pour définir une beatmap comme étant technique.*
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +Voici de bons exemples de cartes technologiques qui correspondent à cette définition : [Silentroom - Nhelv (Nyxa) \[iniquitatem\]](https://osu.ppy.sh/beatmapsets/917915#osu/2009432) et [RUMI - Denset
```suggestion
Voici de bons exemples de cartes techniques qui correspondent à cette définition : [Silentroom - Nhelv (Nyxa) \[iniquitatem\]](https://osu.ppy.sh/beatmapsets/917915#osu/2009432) et [RUMI - Densetsu no Matsuri (Net0) \[Oni\]](https://osu.ppy.sh/beatmapsets/781683#osu/1641637).
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +![Flow dur (Densetsu no Matsuri)](img/beatmap_hard_flow.jpg "Modèle Beatmap avec un flow dur")
```suggestion
![Flow dur (Densetsu no Matsuri)](img/beatmap_hard_flow.jpg "Modèle de Beatmap avec un flow dur")
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +*Attention : La définition "la plus restrictive/spécifique" exige que **tous** les aspects énumérés soient présents afin de définir un beatmap comme étant de la technologie.*
```suggestion
*Attention : La définition "la plus restrictive/spécifique" exige que **tous** les aspects énumérés soient présents afin de définir un beatmap comme étant technique.*
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +- Des pattern de la beatmap difficiles à lire (souvent décrits comme ayant un "flux" difficile) (exemple ci-dessous).
```suggestion
- Des patterns de la beatmap difficiles à lire (souvent décrits comme ayant un "flow" difficile) (exemple ci-dessous).
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +- Des pattern de la beatmap difficiles à lire (souvent décrits comme ayant un "flux" difficile) (exemple ci-dessous).
```suggestion
- Des patterns de la beatmap difficiles à lire (souvent décrits comme ayant un "flow" difficile) (exemple ci-dessous).
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +![Un pattern difficile à lire (Camelia)](img/difficult_to_read_beatmap.jpg "Un pattern difficile à lire")
```suggestion
![Un pattern difficile à lire (Camellia)](img/difficult_to_read_beatmap.jpg "Un pattern difficile à lire")
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +![Forme irrégulière du slider (MARENOL)](img/irregular_slider.jpg "Forme irrégulière du slider (SV slider)")
```suggestion
![Forme irrégulière de slider (MARENOL)](img/irregular_slider.jpg "Forme irrégulière de slider (SV slider)")
```

2021-04-07 21:51 UTC, Airwam commented on wiki/Beatmap/Technical_maps/fr.md
> +Voici de bons exemples de cartes technologiques qui correspondent à cette définition [Camelia - Exit This Earth's Atomosphere (Camellia's "PLANETARY//200STEP" Remix) (ProfessionalBox) \[Primordial Nu
```suggestion
Voici de bons exemples de cartes techniques qui correspondent à cette définition [Camellia - Exit This Earth's Atomosphere (Camellia's "PLANETARY//200STEP" Remix) (ProfessionalBox) \[Primordial Nucleosynthesis\]](https://osu.ppy.sh/beatmapsets/855677#osu/1787848) et [LeaF - MARENOL (Yugu) \[Extra\]](https://osu.ppy.sh/beatmapsets/1136149#osu/2404722). Les captures d'écrans au dessus proviennent d'ailleurs de ces cartes.
```

2021-04-28 16:06 UTC, DoryanR commented
@Airwam Need a recheck from you

2021-05-06 16:54 UTC, Airwam requested changes

2021-05-06 16:54 UTC, Airwam commented on wiki/Beatmap/Beatmap_description/fr.md
> +Une **section de difficulté** est une liste de toutes les difficultés des invités et de leurs créateurs située dans la description d'un beatmap. Elle est surtout utilisée pour présenter les difficult
```suggestion
Une **section de difficulté** est une liste de toutes les difficultés des invités et de leurs créateurs située dans la description d'une beatmap. Elle est surtout utilisée pour présenter les difficultés d'une beatmap. Les sections de difficulté ont généralement des images pour les icônes.
```

2021-05-06 16:54 UTC, Airwam commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Les **difficultés d'invités** (abrégé en *GD*) sont des [difficultés](/wiki/Beatmap/Difficulty) d'une [beatmap](/wiki/Beatmap) qui ne sont pas créée par l'[hôte de la beatmap](/wiki/Beatmap/Beatmap_h
```suggestion
Les **difficultés d'invités** (abrégé en *GD*) sont des [difficultés](/wiki/Beatmap/Difficulty) d'une [beatmap](/wiki/Beatmap) qui ne sont pas créée par l'[hôte de la beatmap](/wiki/Beatmap/Beatmap_host). Elles peuvent généralement être identifiées par leur nom de difficulté contenant le nom d'utilisateur du créateur invité. Une beatmap comportant plusieurs créateurs est également appelée [difficulté collaborative](/wiki/Beatmap/Beatmap_collaborations).
```

2021-05-06 16:54 UTC, Airwam commented on wiki/Beatmap/Hype/fr.md
> +Chaque [beatmap](/wiki/Beatmap) dans le status [en attente](/wiki/Beatmap/Category#pending) ont un **train de la hype** qui représente grossièrement le nombre de personnes intéressées à voir la beatm
```suggestion
Chaque [beatmap](/wiki/Beatmap) dans le statut [en attente](/wiki/Beatmap/Category#pending) ont un **train de la hype** qui représente grossièrement le nombre de personnes intéressées à voir la beatmap [classée](/wiki/Beatmap/Category#ranked). Les utilisateurs peuvent poster des discussions sur la [page de discussion de la beatmap](/wiki/Beatmap_Discussion) dans l'onglet `Général (Toutes les difficultés)` avec l'option `Hype!` pour contribuer à la hype d'une beatmap.
```

2021-05-06 16:54 UTC, Airwam commented on wiki/Beatmap/Marathon/fr.md
> +Le terme **Marathon** est utilisé pour décrire les [beatmaps](/wiki/Beatmap) d'une durée de cinq minutes ou plus. Il s'agit souvent d'efforts collaboratifs, car le mapping de morceaux plus longs peut
```suggestion
Le terme **Marathon** est utilisé pour décrire les [beatmaps](/wiki/Beatmap) d'une durée de cinq minutes ou plus. Il s'agit souvent d'efforts collaboratifs, car le mapping de morceaux plus longs peut être fatigante lorsque réalisé seul.
```

2021-05-06 16:54 UTC, Airwam commented on wiki/Beatmap/TAG/fr.md
> +Dans ces modes, chaque joueur est responsable d'un [comboset](/wiki/Beatmapping/Combo), et tout au long du morceau, les joueurs passent d'un comboset à l'autre. Pour cette raison, les beatmaps TAG so
```suggestion
Dans ces modes, chaque joueur est responsable d'un [comboset](/wiki/Beatmapping/Combo), et tout au long du morceau, les joueurs passent d'un comboset à l'autre. Pour cette raison, les beatmaps TAG sont conçues de telle manière que leurs combosets sont placés beaucoup plus loin les uns des autres et plus complexes que d'habitude, ce qui les rend presque impossible a jouer seul.
```

2021-05-12 10:32 UTC, Satsukel requested changes

2021-05-12 10:32 UTC, Satsukel commented on wiki/Beatmap/Technical_maps/fr.md
> +Les **beatmaps techniques** (abrégé en "tech map") est un terme qui n'a pas de définition claire et acceptée par la communauté d'osu!. Selon l'utilisateur, une "beatmap technique" peut être aussi lar
On peut remplacer "la définition d'une "beatmap technique"" par "elle" afin d'éviter la répétition avec la phrase d'avant s'il le faut mais pour moi il faut en tout cas éviter de laisser "beatmap technique" tout seul.
```suggestion
Les **beatmaps techniques** (abrégé en "tech map") est un terme qui n'a pas de définition claire et acceptée par la communauté d'osu!. En fonction de chaque utilisateur, la définition d'une "beatmap technique" peut être aussi large qu'une [beatmap](/wiki/Beatmap) qui contient simplement des [patterns](/wiki/Beatmap/Pattern) non génériques, ou aussi spécifique qu'une beatmap dense en [objets](/wiki/Hit_object) et contenant de nombreuses formes irrégulières de [slider](/wiki/Hit_object/Slider) qui changent rapidement et radicalement de vitesse (souvent à haute intensité).
```

2021-05-12 10:32 UTC, Satsukel commented on wiki/Beatmap/Technical_maps/fr.md
> +*Attention : La définition "la plus restrictive/spécifique" exige que **tous** les aspects énumérés soient présents afin de définir un beatmap comme étant technique.*
```suggestion
*Attention : La définition "la plus restrictive/spécifique" exige que **tous** les aspects énumérés soient présents afin de définir une beatmap comme étant technique.*
```

2021-05-18 20:06 UTC, Satsukel approved these changes

2021-05-21 18:34 UTC, TicClick commented
please adjust your translation to 596efd8dff27df4ce19401c51c3f809562ea6e95

2021-05-21 18:57 UTC, TicClick approved these changes

2021-05-21 18:58 UTC, merged