[FR] Test mode and [EN] fixing a spelling mistake
ppy/osu-wiki pull request #5134
Opened 2021-03-28 09:18 UTC by DoryanR

Proposal for the French translation of the wiki page "Test mode".

Also fixing a spelling mistake in EN file.

2021-04-10 11:23 UTC, Airwam requested changes

2021-04-10 11:23 UTC, Airwam commented on wiki/Beatmap_Editor/Test_mode/fr.md
> +*Note : La lecture d'un beatmap en test mode est connue pour provoquer un certain décalage ou des baisses notables du framerate pour certains utilisateurs.*
```suggestion
*Note : La lecture d'une beatmap en test mode est connue pour provoquer un certain décalage ou des baisses notables du framerate pour certains utilisateurs.*
```

2021-04-10 11:23 UTC, Airwam commented on wiki/Beatmap_Editor/Test_mode/fr.md
> +Jouer un beatmap en test mode diffère du jeu normal, car il ne soumet aucun score, n'affiche aucun classement, ne permet pas aux utilisateurs d'échouer les beatmaps, et affiche toujours les informati
```suggestion
Jouer une beatmap en test mode diffère du jeu normal, car il ne soumet aucun score, n'affiche aucun classement, ne permet pas aux utilisateurs d'échouer les beatmaps, et affiche toujours les informations suivantes sur le côté gauche de l'écran :
```

2021-04-10 11:23 UTC, Airwam commented on wiki/Beatmap_Editor/Test_mode/fr.md
> +- Le nombre total de 300s, 100s, 50s et de miss obtenues
```suggestion
- Le nombre total de 300s, 100s, 50s et de miss obtenus
```

2021-04-10 11:23 UTC, Airwam commented on wiki/Beatmap_Editor/Test_mode/fr.md
> +- Le délai moyen (en millisecondes) dans lequel les hits mal placées sont en retard
```suggestion
- Le délai moyen (en millisecondes) dans lequel les hits mal placés sont en retard
```

2021-04-10 11:23 UTC, Airwam commented on wiki/Beatmap_Editor/Test_mode/fr.md
> +- Le [star ranting](/wiki/Beatmapping/Star_rating) de la beatmap
```suggestion
- Le [star rating](/wiki/Beatmapping/Star_rating) de la beatmap 
```

2021-04-28 16:05 UTC, DoryanR commented
@Airwam Need a recheck from you

2021-05-06 16:25 UTC, Airwam requested changes

2021-05-22 18:29 UTC, Satsukel requested changes

2021-05-22 18:29 UTC, Satsukel commented on wiki/Beatmap_Editor/Test_mode/fr.md
> +Le **test mode** est une fonctionnalité de l'[éditeur de beatmap](/wiki/Beatmap_Editor) qui permet aux créateurs de jouer leurs propres [beatmaps](/wiki/Beatmap) à partir de l'éditeur de beatmap à de
J'ai changé la fin de la phrase pour que ça fasse un peu plus français courant même si on s'éloigne un peu de la version originale.
```suggestion
Le **test mode** est une fonctionnalité de l'[éditeur de beatmap](/wiki/Beatmap_Editor) qui permet aux créateurs de jouer leurs propres [beatmaps](/wiki/Beatmap) à partir de l'éditeur de beatmap afin de les tester. Le mode est accessible via le bouton `Test` en bas à droite de l'éditeur.
```

2021-05-22 18:29 UTC, Satsukel commented on wiki/Beatmap_Editor/Test_mode/fr.md
> +Le mode test diffère également de la lecture standard d'une beatmap car il exige que les utilisateurs sauvegardent leur beatmap avant de le jouer, et permet aux utilisateurs de regarder la beatmap en
```suggestion
Le test mode diffère également de la lecture standard d'une beatmap car il exige que les utilisateurs sauvegardent leur beatmap avant de la jouer, et permet aux utilisateurs de regarder la beatmap en "autoplay", qui joue la beatmap comme le ferait le mod [Auto](/wiki/Game_modifier/Auto).
```

2021-05-23 08:04 UTC, Satsukel approved these changes

2021-05-25 13:26 UTC, TicClick approved these changes

2021-05-25 13:26 UTC, merged