[FR] History of osu!
ppy/osu-wiki pull request #5135
Opened 2021-03-28 15:50 UTC by Airwam

French translation of osu! wiki - History of osu! page.

2021-03-28 16:02 UTC, DoryanR requested changes
After changes, it will be good for me.

2021-03-28 16:02 UTC, DoryanR commented on wiki/History_of_osu!/fr.md
> +- [2016](/wiki/History_of_osu!/2016) - scorev2, osu! open-source annoncé (osu!lazer), et osu! wiki (refonte)
```suggestion
- [2016](/wiki/History_of_osu!/2016) - scorev2, osu! open-source annoncé (osu!lazer), et osu!wiki (refonte)
```

2021-03-28 16:15 UTC, DoryanR requested changes
Still some things to work on.

2021-03-28 16:15 UTC, DoryanR commented on wiki/History_of_osu!/fr.md
> +- [2015](/wiki/History_of_osu!/2015) - jizz (osu!web repensé), osu!weekly, and osu!coins
```suggestion
- [2015](/wiki/History_of_osu!/2015) - jizz (osu!web repensé), osu!weekly, et osu!coins
```

2021-03-28 16:15 UTC, DoryanR commented on wiki/History_of_osu!/fr.md
> +A noter que le osu! wiki a un peu de son histoire détaillée éparpillée à travers les pages.
```suggestion
A noter que le osu!wiki a un peu de son histoire détaillée éparpillée à travers les pages.
```

2021-03-28 18:59 UTC, DoryanR approved these changes
After checking the file, I approve the changes.

2021-03-29 11:43 UTC, TicClick approved these changes

2021-03-29 11:43 UTC, merged