[FR] Beatmapping stubs
ppy/osu-wiki pull request #5136
Opened 2021-03-28 17:27 UTC by DoryanR

Translation of the following wiki articles:

- Beatmapping/Beats_per_minute
- Beatmapping/Colourhaxing
- Beatmapping/Countdown
- Beatmapping/HP_drain_rate
- Beatmapping/Health_drain
- Beatmapping/Hitsound
- Beatmapping/New_combo
- Beatmapping/Offset
- Beatmapping/Overmapping
- Beatmapping/Sampleset
- Beatmapping/Slider_tick
- Beatmapping/Slider_tick_rate
- Beatmapping/Snapping
- Beatmapping/Song_compilation
- Beatmapping/Star_rating
- Beatmapping/Time_signature
- Beatmapping/Timing_section

Also fixing a spelling mistake in `Beatmapping/Slider_tick` file.

2021-05-18 12:28 UTC, Satsukel requested changes

2021-05-18 12:28 UTC, Satsukel commented on wiki/Beatmapping/Star_rating/fr.md
> +Le **star ranting** (***SR***) décrit la difficulté d'une [beatmap](/wiki/Beatmap), qui est automatiquement calculée par le client d'osu!. Le star ranting joue un rôle important dans l'attribution de
```suggestion
Le **star rating** (***SR***) décrit la difficulté d'une [beatmap](/wiki/Beatmap), qui est automatiquement calculée par le client d'osu!. Le star rating joue un rôle important dans l'attribution des [points de performance](/wiki/Performance_Points). Ce nombre peut être vu sur l'[écran de sélection des chansons](/wiki/Interface#song-selection-screen) et sur la page d'information d'une beatmap.
```

2021-05-18 12:28 UTC, Satsukel commented on wiki/Beatmapping/Time_signature/fr.md
> +osu! offre deux signatures temporelles alternatives pour le [mapping](/wiki/Beatmapping), qui peuvent être sélectionnées à partir du menu `Timing` dans l'[éditeur de beatmap](/wiki/Beatmap_editor). I
```suggestion
osu! offre deux alternatives de signatures temporelles pour le [mapping](/wiki/Beatmapping), qui peuvent être sélectionnées à partir du menu `Timing` dans l'[éditeur de beatmap](/wiki/Beatmap_editor). Il s'agit du 4/4 (signature "common time") et du 3/4 (signature "Waltz" ou "three-four-time"). osu! n'empêchera pas les utilisateurs de mapper des chansons écrites dans des signatures différentes, bien qu'il ne soit pas garanti que la beatmap soit alignée avec la musique si cela est fait.
```

2021-05-18 12:28 UTC, Satsukel commented on wiki/Beatmapping/Timing_section/fr.md
> +Lorsque la tempo d'une musique change, les créateurs sont tenus d'ajouter une nouvelle section de timing pour accompagner la nouvelle tempo. Une beatmap qui utilise un timing incorrect ne sera pas co
```suggestion
Lorsque le tempo d'une musique change, les créateurs sont tenus d'ajouter une nouvelle section de timing pour accompagner le nouveau tempo. Une beatmap qui utilise un timing incorrect ne sera pas considérée comme classable.
```

2021-05-18 20:04 UTC, Satsukel approved these changes

2021-05-21 17:04 UTC, TicClick approved these changes

2021-05-21 17:04 UTC, merged