[FR] Community Mentorship Program
ppy/osu-wiki pull request #5143
Opened 2021-03-29 16:45 UTC by DoryanR

Proposal for the French translation of the wiki page "Community Mentorship Program".

**Notify me if the PR is merge without review, that I self-review before.**

2021-03-31 11:11 UTC, Pachiru requested changes

2021-03-31 11:11 UTC, Pachiru commented on wiki/Community_Mentorship_Program/fr.md
> +# Programme de mentorat communautaire
Je pense que c'est mieux de garder "Community Mentorship Program" dans tout l'article, étant donné que le programme s'appelle ainsi et que ce sera plus facile pour les joueurs de se retrouver et de comprendre si ils en entendent parler. Un peu le même principe que le "Projet Loved"

2021-03-31 11:11 UTC, Pachiru commented on wiki/Community_Mentorship_Program/fr.md
> +Le programme est organisé via Discord et est géré par cycles saisonniers. Chaque cycle est annoncé par un message sur le forum et les cycles occasionnels sont annoncés par des messages sur la page d'
```suggestion
Le programme est organisé via Discord et est géré par cycles saisonniers. Chaque cycle est annoncé via un message sur le forum et les cycles occasionnels sont annoncés via des messages sur la page d'accueil.
```

2021-03-31 11:11 UTC, Pachiru commented on wiki/Community_Mentorship_Program/fr.md
> +Entre 2010 et 2013, un mentorat communautaire a été mis en place pour que les mappeurs inexpérimentés puissent apprendre directement des membres de la [Beatmap Appreciation Team (*BAT*)](/wiki/Moddin
```suggestion
Entre 2010 et 2013, un mentorat communautaire était mis en place afin d'aider les mappeurs inexpérimentés à s'intégrer dans la communauté du mapping. L'équipe de collaborateurs était principalement composée de membres de la [Beatmap Appreciation Team (*BAT*)](/wiki/Modding/Beatmap_Appreciation_Team) et de la [Mapping Assistance Team (*MAT*)](/wiki/Modding/Mapping_Assistance_Team).
```

2021-04-26 15:15 UTC, osuShiro approved these changes

2021-04-26 15:15 UTC, merged