[TH] Add "abandoned wasteland" and "upppy"
ppy/osu-wiki pull request #5144
Opened 2021-03-29 17:46 UTC by HelloYeew

Add Thai translation for

- Abandoned wasteland
- upppy

2021-03-30 11:12 UTC, Trigonoculus requested changes
ฟอรัม -> ฟอรั่ม (จากบทความก่อน ๆ)

นอกนั้นโอเคเลยครับ มีอีกจุดนึงที่อธิบายใน comment

2021-03-30 11:12 UTC, Trigonoculus commented on wiki/Abandoned_wasteland/th.md
> +**Abandoned wasteland** (ไทย: ดินแดนแห่งความสูญเปล่าที่ถูกทิ้งร้าง) เป็น [ฟอรัมย่อย](https://osu.ppy.sh/community/forums) เพื่อใช้ในการซ่อนฟอรัมและหัวข้อฟอรัมจากสาธารณะ ฟอรัมย่อยนี้สามารถเข้าถึงได้แค
```suggestion
**Abandoned wasteland** (ไทย: ดินแดนแห่งความสูญเปล่าที่ถูกทิ้งร้าง) เป็น [ฟอรั่มย่อย](https://osu.ppy.sh/community/forums) เพื่อใช้ในการซ่อนฟอรั่มและหัวข้อฟอรั่มจากสาธารณะ ฟอรั่มย่อยนี้สามารถเข้าถึงได้แค่จาก [ผู้ดูแล](/wiki/People/The_Team/Global_Moderation_Team) ที่มีสิทธิ์แก้ไขฟอรั่มเท่านั้น วิธีการของผู้ดูแลคือ `ใส่สิ่งที่เราไม่ต้องการลงไปในนี้`
```

2021-03-30 11:12 UTC, Trigonoculus commented on wiki/Abandoned_wasteland/th.md
> +ฟอรัมและหัวข้อจะถูกกล่าวว่าเป็น "wastelanded" (ดินแดนแห่งความสูญเปล่า) เมื่อพวกมันถูกย้ายมาฟอรัมนี้
```suggestion
ฟอรั่มและหัวข้อจะถูกกล่าวว่าถูก "wastelanded" เมื่อพวกมันถูกย้ายมาฟอรั่มนี้
```
คิดว่าไม่ต้องมีคำอธิบายอีกรอบก็ได้นะครับ เพราะว่าเขียนไปแล้วตอนต้นบทความ

2021-03-30 11:14 UTC, Trigonoculus commented
อีกอย่างนึง แนะนำว่าเวลาแปลครั้งหน้า สามารถสร้าง branch ใหม่ใน fork ของเรา (จาก `master` ที่ up-to-date) เวลาแปลบทความนะครับ จะได้ทำหลาย ๆ อันพร้อมกันได้ครับผม

2021-03-30 15:52 UTC, HelloYeew commented on wiki/Abandoned_wasteland/th.md
> +ฟอรัมและหัวข้อจะถูกกล่าวว่าเป็น "wastelanded" (ดินแดนแห่งความสูญเปล่า) เมื่อพวกมันถูกย้ายมาฟอรัมนี้
โอเคครับ

2021-03-30 15:55 UTC, HelloYeew commented on wiki/upppy/th.md
> +**[upppy](https://up.ppy.sh)** เป็นบริการอัพโหลดไฟล์ที่ให้บริการโดย ![][flag_AU] [peppy](https://osu.ppy.sh/users/2) ใช้ในการแบ่งปันรูปภาพกับชุมชน osu! เป็นหลัก
โอเคครับ อันนี้ผมก็ไม่แน่ใจเหมือนกันตอนแรก

2021-03-30 15:58 UTC, HelloYeew commented on wiki/upppy/th.md
> +[flag_AU]: /wiki/shared/flag/AU.gif "ออสเตรเลีย"
ok thx

2021-04-02 08:30 UTC, Trigonoculus requested changes
ลืมอีกจุดครับ แก้ละโอเคแล้ว

2021-04-02 08:30 UTC, Trigonoculus commented on wiki/Abandoned_wasteland/th.md
> +**Abandoned wasteland** (ไทย: ดินแดนแห่งความสูญเปล่าที่ถูกทิ้งร้าง) เป็น [ฟอรั่มย่อย](https://osu.ppy.sh/community/forums) เพื่อใช้ในการซ่อนฟอรั่มและหัวข้อฟอรั่มจากสาธารณะ ฟอรั่มย่อยนี้สามารถเข้าถึงไ
```suggestion
**Abandoned wasteland** (ไทย: ดินแดนแห่งความสูญเปล่าที่ถูกทิ้งร้าง) เป็น[ฟอรั่มย่อย](https://osu.ppy.sh/community/forums) เพื่อใช้ในการซ่อนฟอรั่มและหัวข้อฟอรั่มจากสาธารณะ ฟอรั่มย่อยนี้สามารถเข้าถึงได้แค่จาก[ผู้ดูแล](/wiki/People/The_Team/Global_Moderation_Team) ที่มีสิทธิ์แก้ไขฟอรั่มเท่านั้น วิธีการของผู้ดูแลคือ `ใส่สิ่งที่เราไม่ต้องการลงไปในนี้`
```

2021-04-02 16:03 UTC, HelloYeew commented on wiki/Abandoned_wasteland/th.md
> +**Abandoned wasteland** (ไทย: ดินแดนแห่งความสูญเปล่าที่ถูกทิ้งร้าง) เป็น [ฟอรั่มย่อย](https://osu.ppy.sh/community/forums) เพื่อใช้ในการซ่อนฟอรั่มและหัวข้อฟอรั่มจากสาธารณะ ฟอรั่มย่อยนี้สามารถเข้าถึงไ
เคครับ commit ละ

2021-04-02 16:05 UTC, Trigonoculus approved these changes
Looks good 👍

2021-04-03 03:06 UTC, C0NS03L approved these changes

2021-04-03 07:49 UTC, TicClick approved these changes

2021-04-03 07:49 UTC, merged