[FR] Full combo
ppy/osu-wiki pull request #5148
Opened 2021-03-30 16:30 UTC by DoryanR

Proposal for the French translation of the wiki page "Full combo".

2021-03-31 11:29 UTC, Pachiru requested changes

2021-03-31 11:29 UTC, Pachiru commented on wiki/Full_combo/fr.md
> +Le **full combo** (ou *FC* pour faire court) est un terme utilisé pour décrire un joueur obtenant le maximum de combo possible<!-- TODO : link --> sur une [beatmap](/wiki/Beatmap). Les combos complet
```suggestion
Le **full combo** (abrégé en *FC*) est un terme utilisé pour décrire un joueur obtenant le maximum de combo possible<!-- TODO : link --> sur une [beatmap](/wiki/Beatmap). Un joueur obtient un *FC* si celui-ci complète une beatmap sans aucun raté<!-- TODO : link -->, ni [sliderbreak](/wiki/Gameplay/Slider_break) ou [slider-end](/wiki/Hit_object/Slidertail).
```
Est-ce que les <!-- TODO : link --> sont important? Si ils ne sont pas important, je pense que l'on peu les retirer.

2021-03-31 11:29 UTC, Pachiru commented on wiki/Full_combo/fr.md
> +Les scores qui ne perdent pas de combo uniquement en raison de la chute des slider ends sont largement considérés par la communauté comme des combos complets. Cela diffère de l'affichage du client du
```suggestion
La communauté considère généralement les scores où le joueur n'a pas obtenu de *full combo* suite à un slider-ends raté comme un *full combo* malgré tout. Cependant, sur le client ainsi que sur le site web du jeu, le score ne sera pas affiché comme tel.
```

2021-03-31 11:29 UTC, Pachiru commented on wiki/Full_combo/fr.md
> +![Capture d'écran des scores de combo complet et de combo brisé](img/combo-comparison.png "Le score du dessus est un combo complet, et le score du dessous est un combo cassé.")
```suggestion
![Capture d'écran des scores de full combo et de combo brisé](img/combo-comparison.png "Le score du dessus est un full combo, et le score du dessous est un combo cassé.")
```

2021-03-31 11:29 UTC, Pachiru commented on wiki/Full_combo/fr.md
> +Grâce à l'[effet multiplicateur de combo](/wiki/Glossary/Combo_multiplier_effect), les combos complets rapportent le plus de [score](/wiki/Score) dans les [modes de jeu](/wiki/Game_mode) [osu!standar
```suggestion
Grâce à l'[effet multiplicateur de combo](/wiki/Glossary/Combo_multiplier_effect), les full combos rapportent le plus de [score](/wiki/Score) dans les [modes de jeu](/wiki/Game_mode) [osu!standard](/wiki/Game_mode/osu!), [osu!taiko](/wiki/Game_mode/osu!taiko), et [osu!catch](/wiki/Game_mode/osu!catch). 
```

2021-03-31 12:51 UTC, DoryanR commented on wiki/Full_combo/fr.md
> +Le **full combo** (ou *FC* pour faire court) est un terme utilisé pour décrire un joueur obtenant le maximum de combo possible<!-- TODO : link --> sur une [beatmap](/wiki/Beatmap). Les combos complet
C'était de base dans la version anglaise, mais je pense qu'on peut les enlever sans soucis

2021-04-26 15:23 UTC, osuShiro requested changes

2021-04-26 15:23 UTC, osuShiro commented on wiki/Full_combo/fr.md
> +La communauté considère généralement les scores où le joueur n'a pas obtenu de *full combo* suite à un slider-ends raté comme un *full combo* malgré tout. Cependant, sur le client ainsi que sur le si
```suggestion
La communauté considère généralement les scores où le joueur n'a pas obtenu de *full combo* suite à un slider-end raté comme un *full combo* malgré tout. Cependant, sur le client ainsi que sur le site web du jeu, le score ne sera pas affiché comme tel.
```

2021-04-26 15:23 UTC, osuShiro commented on wiki/Full_combo/fr.md
> +Le **full combo** (abrégé en *FC*) est un terme utilisé pour décrire un joueur obtenant le maximum de combo possible sur une [beatmap](/wiki/Beatmap). Un joueur obtient un *FC* si celui-ci complète u
```suggestion
Le **full combo** (abrégé en *FC*) est un terme utilisé pour décrire un joueur obtenant le maximum de combo possible sur une [beatmap](/wiki/Beatmap). Un joueur obtient un *FC* si celui-ci complète une beatmap sans aucun miss, [sliderbreak](/wiki/Gameplay/Slider_break), ni [slider-end](/wiki/Hit_object/Slidertail) raté.
```

2021-05-11 15:28 UTC, TicClick commented
@osuShiro I assume this is ready

2021-05-12 09:27 UTC, osuShiro approved these changes

2021-05-12 09:27 UTC, merged