[FR] Beatmap editor
ppy/osu-wiki pull request #5158
Opened 2021-04-01 08:48 UTC by TLuzrod

French translation of the Beatmap editor page.

2021-04-01 14:21 UTC, DoryanR requested changes
Add `Update` after `Beatmap editor` in your title, because otherwise it can be confused with adding a page.

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +*Pour les raccourcis de l'éditeur de beatmap, voir: [Reférence sur les raccourcis clavier § Éditeur de Beatmap](/wiki/Shortcut_key_reference#beatmap-editor)*
```suggestion
*Pour les raccourcis de l'éditeur de beatmap, voir: [Reférence sur les raccourcis clavier & Éditeur de Beatmap](/wiki/Shortcut_key_reference#beatmap-editor)*
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'**éditeur de beatmap** est l'interface graphique inclue dans le client utilisée pour créer les [beatmaps](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création de beatmap
```suggestion
L'**éditeur de beatmap** est l'interface graphique incluse dans le client utilisée pour créer des [beatmap](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création des beatmap sur osu!.
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'éditeur de beatmap est séparé en 4 sections qui peuvent être vues dans le coin supérieur gauche de l'éditeur:
```suggestion
L'éditeur de beatmap est séparé en 4 sections qui peuvent être vues dans le coin supérieur gauche de l'éditeur :
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +La création des [objets cliquables](/wiki/Hit_Objects) et des autres éléments de jeux est gérée dans l'onglet [Compose](/wiki/Beatmap_Editor/Compose). C'est pour cette raison que la plupart des créat
```suggestion
La création des [hit objects](/wiki/Hit_Objects) et des autres éléments de jeux est gérée dans l'onglet [Compose](/wiki/Beatmap_Editor/Compose). C'est pour cette raison que la plupart des créateurs de beatmap passent plus de temps dans cet onglet que dans les autres.
```

J'aurais laisser `hit object`, je pense que cela rend mieux

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'éditeur de beatmap inclus également:
```suggestion
L'éditeur de beatmap inclus également :
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- [AiMod](AiMod): Un système automatisé qui signale les problèmes dans une beatmap.
```suggestion
- [AiMod](AiMod) : Un système automatisé qui signale les problèmes dans une beatmap.
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- [Diviseur de mesure](Beat_Snap_Divisor): Détermine comment les objets sont fixés à la timeline.
```suggestion
- [Beat snap divisor](Beat_Snap_Divisor) : Détermine comment les objets sont fixés à la timeline.
```

Je laisserais aussi la traduction original ici

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- [Distance snap](Distance_Snap): Détermine la distance entre 2 objets consécutifs en prenant en compte le rythme de la musique.
```suggestion
- [Distance snap](Distance_Snap) : Détermine la distance entre 2 objets consécutifs en prenant en compte le rythme de la musique.
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- [Kiai time](Kiai_Time): Des sections spécifiques du timing qui aident à mettre en valeur une partie de la beatmap.
```suggestion
- [Kiai time](Kiai_Time) : Des sections spécifiques du timing qui aident à mettre en valeur une partie de la beatmap.
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- [Menu](Menu): Aide à naviguer à travers l'éditeur de beatmap.
```suggestion
- [Menu](Menu) : Aide à naviguer à travers l'éditeur de beatmap.
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- [SB load](SB_Load): Un nombre indiquant à quel point le storyboard est lourd en terme de performances.
```suggestion
- [SB load](SB_Load) : Un nombre indiquant à quel point le storyboard est lourd en terme de performances.
```

2021-04-01 14:21 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- [Timelines](Timelines): Affiche les objets cliquables, les pauses et autres.
```suggestion
- [Timelines](Timelines) : Affiche les hits objects, les pauses et autres.
```

2021-04-01 15:25 UTC, DoryanR requested changes
Still some things to work on.

2021-04-01 15:25 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +*Pour les raccourcis de l'éditeur de beatmap, voir: [Reférence sur les raccourcis clavier & Éditeur de Beatmap](/wiki/Shortcut_key_reference#beatmap-editor)*
```suggestion
*Pour les raccourcis de l'éditeur de beatmap, voir : [Reférence sur les raccourcis clavier & Éditeur de Beatmap](/wiki/Shortcut_key_reference#beatmap-editor)*
```

2021-04-01 15:25 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- Compose (Composition)
```suggestion
- Compose
```

On peut omettre la traduction je pense, car sur l'éditeur on a aucune différence entre Anglais et Français

2021-04-01 15:25 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- Song setup (Paramètres de la musique)
```suggestion
- Song setup
```

Pareil que le précédent

2021-04-01 15:25 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'onglet [Song setup](/wiki/Beatmap_Editor/Song_Setup) permet de renseigner les [métadonnées](/wiki/Beatmap_Editor/Song_Setup#song-and-map-metadata) et d'autres choses universelles au [beatmapset](/w
```suggestion
L'onglet [Song setup](/wiki/Beatmap_Editor/Song_Setup) permet de renseigner les [métadonnées](/wiki/Beatmap_Editor/Song_Setup#song-and-map-metadata) et d'autres choses universelles d'une [beatmapset](/wiki/Beatmap/Beatmapsets). Cela inclus le titre de la musique, l'artiste, le nom de la difficulté, la couleur des combos, etc...
```

2021-04-01 17:02 UTC, DoryanR submitted a review, later dismissed
After checking the file, I approve the changes.

2021-04-02 19:31 UTC, Pachiru requested changes
Once this changes are applied, it can be merged

2021-04-02 19:31 UTC, Pachiru commented on wiki/Beatmap_Editor/fr.md
> +L'**éditeur de beatmap** est l'interface graphique incluse dans le client utilisée pour créer des [beatmap](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création des beatma
```suggestion
L'**éditeur de beatmap** est l'interface graphique intégrée au client et est utilisée pour créer des [beatmaps](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création de beatmap sur osu!.
```

2021-04-02 19:31 UTC, Pachiru commented on wiki/Beatmap_Editor/fr.md
> +L'onglet [Design](/wiki/Beatmap_Editor/Design) permet de réaliser les [storyboards](/wiki/Storyboards), cet-à-dire les animations qui accompagnent les beatmaps. Étant donné que les storyboards contie
```suggestion
L'onglet [Design](/wiki/Beatmap_Editor/Design) permet de réaliser les [storyboards](/wiki/Storyboards), c’est-à-dire les animations qui accompagnent les beatmaps. Étant donné que les storyboards contiennent des effets complexes justifiant l'utilisation d'un nombre conséquent de commandes de storyboard, les mappers utilisent également le [storyboard scripting](/wiki/Storyboard_Scripting) sans entrer dans l'onglet design.
```

2021-04-03 07:37 UTC, DoryanR requested changes
Still some things to work on.

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +*Pour les raccourcis de l'éditeur de beatmap, voir : [Reférence sur les raccourcis clavier & Éditeur de Beatmap](/wiki/Shortcut_key_reference#beatmap-editor)*
```suggestion
*Pour les raccourcis de l'éditeur de beatmap, voir : [Référence sur les raccourcis clavier & éditeur de beatmap](/wiki/Shortcut_key_reference#beatmap-editor)*
```

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'**éditeur de beatmap** est l'interface graphique intégrée au client et est utilisée pour créer des [beatmaps](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création de bea
```suggestion
L'**éditeur de beatmap** est l'interface graphique intégrée au client qui est utilisée pour créer des [beatmaps](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création des beatmaps sur osu!.
```

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- Compose
```suggestion
- [Compose](#compose)
```

Je verrais bien ça pour relier les différents points étudier dans l'article, ce qui permettrais à ceux qui cherche spécifiquement une section de la trouver rapidement.

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- Design
```suggestion
- [Design](#design)
```

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- Timing
```suggestion
- [Timing](#timing)
```

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +- Song setup
```suggestion
- [Song setup](#song-setup)
```

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +La création des [hit objects](/wiki/Hit_Objects) et des autres éléments de jeux est gérée dans l'onglet [Compose](/wiki/Beatmap_Editor/Compose). C'est pour cette raison que la plupart des créateurs d
```suggestion
La création des [hit objects](/wiki/Hit_Objects) et des autres éléments de jeu est gérée dans l'onglet [Compose](/wiki/Beatmap_Editor/Compose). C'est pour cette raison que la plupart des créateurs de beatmap passent le plus de temps dans cet onglet que dans les autres.
```

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'onglet [Design](/wiki/Beatmap_Editor/Design) permet de réaliser les [storyboards](/wiki/Storyboards), c’est-à-dire les animations qui accompagnent les beatmaps. Étant donné que les storyboards cont
```suggestion
L'onglet [Design](/wiki/Beatmap_Editor/Design) permet de réaliser des [storyboards](/wiki/Storyboards), c’est-à-dire les animations qui accompagnent les beatmaps. Étant donné que les storyboards contiennent des effets complexes justifiant l'utilisation d'un nombre conséquent de commandes de storyboard, les mappers utilisent également le [storyboard scripting](/wiki/Storyboard_Scripting) sans entrer dans l'onglet design.
```

2021-04-03 07:37 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'onglet [Timing](/wiki/Beatmap_Editor/Timing) gère le timing des sections de la musique et contrôle les hitsounds de la map. C'est essentiel car une beatmap a besoin d'avoir un timing correct ainsi
```suggestion
L'onglet [Timing](/wiki/Beatmap_Editor/Timing) gère le timing des sections de la musique et contrôle les hitsounds de la map. C'est essentiel car une beatmap a besoin d'avoir un timing correct ainsi qu'un retour audio approprié pour que l'expérience de jeu correspondent au rythme de la musique.
```

2021-04-03 09:36 UTC, TLuzrod commented on wiki/Beatmap_Editor/fr.md
> +L'onglet [Timing](/wiki/Beatmap_Editor/Timing) gère le timing des sections de la musique et contrôle les hitsounds de la map. C'est essentiel car une beatmap a besoin d'avoir un timing correct ainsi
Le sujet de "correspondre" c'est "l'expérience de jeu" donc c'est la troisième personne du singulier il me semble.

2021-04-03 09:42 UTC, TLuzrod commented on wiki/Beatmap_Editor/fr.md
> +L'**éditeur de beatmap** est l'interface graphique intégrée au client et est utilisée pour créer des [beatmaps](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création de bea
Le verbe utiliser est conjugué à la voix passive donc il faut mettre le participe passé.

2021-04-03 09:51 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'**éditeur de beatmap** est l'interface graphique intégrée au client et est utilisée pour créer des [beatmaps](/wiki/Beatmap). Le [Beatmapping](/wiki/Beatmapping) est le processus de création de bea
Si ça te semble mieux on peut laisser comme c'était

2021-04-03 09:51 UTC, DoryanR commented on wiki/Beatmap_Editor/fr.md
> +L'onglet [Timing](/wiki/Beatmap_Editor/Timing) gère le timing des sections de la musique et contrôle les hitsounds de la map. C'est essentiel car une beatmap a besoin d'avoir un timing correct ainsi
Si ça te semble mieux on peut laisser comme c'était

2021-04-03 17:14 UTC, DoryanR approved these changes
After checking the file, I approve the changes.

2021-05-02 10:52 UTC, geshii requested changes

2021-05-02 10:52 UTC, geshii commented on wiki/Beatmap_Editor/fr.md
> +L'éditeur de beatmap inclus également :
inclut*

2021-05-02 12:02 UTC, TLuzrod commented on wiki/Beatmap_Editor/fr.md
> +L'éditeur de beatmap inclus également :
Fait!

2021-05-02 12:02 UTC, DoryanR submitted a review, later dismissed

2021-05-02 13:00 UTC, geshii submitted a review, later dismissed

2021-05-11 18:46 UTC, merged