[ID] Add Ouendan
ppy/osu-wiki pull request #5162
Opened 2021-04-02 04:33 UTC by mousesalt

Add Indonesian translation of [Ouendan](https://osu.ppy.sh/wiki/en/Ouendan) content wiki article.

2021-04-02 05:20 UTC, wowcake requested changes

2021-04-02 05:20 UTC, wowcake commented on wiki/Ouendan/id.md
> +Ouendan dapat memiliki banyak arti:
```suggestion
Ouendan dapat memiliki berbagai-bagai arti:

2021-04-03 03:29 UTC, hikikuman commented on wiki/Ouendan/id.md
> +- Dalam budaya Jepang, sebuah regu pemandu sorak yang mirip dengan pemandu sorak barat, menggalang tim olahraga menggunakan drum, terompet, spanduk, dan sorakan penyemangat.
```suggestion
- Dalam budaya Jepang, sekelompok regu pemandu sorak yang mirip dengan pemandu sorak barat, menggalang tim olahraga menggunakan drum, terompet, spanduk, dan sorakan penyemangat.
```
Ini regu pemandu soraknya kalo isinya orang-orang, lebih pas pake `sekelompok`.

2021-04-03 04:07 UTC, mousesalt commented on wiki/Ouendan/id.md
> +- Dalam budaya Jepang, sebuah regu pemandu sorak yang mirip dengan pemandu sorak barat, menggalang tim olahraga menggunakan drum, terompet, spanduk, dan sorakan penyemangat.
`regu` dan `kelompok` punya arti yang sama

2021-04-03 05:12 UTC, hikikuman submitted a review, later dismissed
checked

2021-04-03 05:17 UTC, hikikuman commented
Ahh ya, didn't notice you were planning to delete en.md. Anyway, the id.md looks fine for me.

2021-04-03 07:48 UTC, TicClick commented
please check carefully which changes you are proposing. if you rename `en.md` into `id.md` and push that as a change, the original gets removed: [`6411207` (#5162)](https://github.com/ppy/osu-wiki/pull/5162/commits/64112073215862e409fd4149ce58a23e3ddd49b0)

anyway, I restored it

2021-04-03 07:48 UTC, TicClick approved these changes

2021-04-03 07:48 UTC, merged

2021-04-03 07:56 UTC, mousesalt commented
thanks for info
i did a mistake