[FR] Geki
ppy/osu-wiki pull request #5170
Opened 2021-04-03 19:11 UTC by DoryanR

Proposal to update the French translation of the wiki page "Geki".

2021-04-03 20:03 UTC, Baguette2Pain reviewed
utiliser (line 12) → "utilisé"
idée (line 13) → "notion" maybe
de la nintendo ds (line 13) → "sur Nintendo DS" feels more french

2021-04-04 08:32 UTC, DoryanR commented
> utiliser (line 12) → "utilisé"
> idée (line 13) → "notion" maybe
> de la nintendo ds (line 13) → "sur Nintendo DS" feels more french

Fait, cependant j'ai pas changer `idée` et `de la Nintendo DS`, car ça me semble bien comme tel.

2021-04-10 11:36 UTC, osuShiro requested changes

2021-04-10 11:36 UTC, osuShiro commented on wiki/Geki/fr.md
> +Le terme **Geki (激)**, ou *Elite Beat!* est utilisé pour qualifier la qualité du [score](/wiki/Score) lorsqu'un joueur a complété un comboset avec la plus grande [précision](/wiki/Gameplay/Accuracy)
Comme sur la review pour Katu, remplace "chaque note" par "toutes les notes", et "Cette idée" par "Ce terme". Pour rester cohérent avec l'autre article, remplace aussi "est issue" par "provient"

2021-04-20 17:40 UTC, TicClick commented
I've just merged the updated article (it's no longer a stub) in #4242, please retranslate it

2021-04-20 17:55 UTC, DoryanR commented
> I've just merged the updated article (it's no longer a stub) in #4242, please retranslate it

Done

2021-04-26 15:11 UTC, osuShiro requested changes

2021-04-26 15:11 UTC, osuShiro commented on wiki/Geki/fr.md
> +- L'événement "Passing" est déclenché, si l'état précédent était "Fail"..
```suggestion
- L'événement "Passing" est déclenché, si l'état précédent était "Fail".
```

2021-04-26 15:12 UTC, osuShiro approved these changes

2021-04-26 15:13 UTC, merged