[ZH-TW] Add Graphics tablet
ppy/osu-wiki pull request #5181
Opened 2021-04-04 13:03 UTC by SiderealArt

2021-04-19 18:01 UTC, DoryanR requested changes
In line with the new standards

2021-04-19 18:01 UTC, DoryanR commented on wiki/Gameplay/Input_device/Graphics_tablet/zh-tw.md
> +***繪圖板***，原先被用於電繪及設計領域，但在 [osu!standard](/wiki/Game_mode/osu!) 中也被當作控制游標的輸入裝置。在 osu!standard 中是最常見的遊玩風格。
```suggestion
***繪圖板***，原先被用於電繪及設計領域，但在 [osu!](/wiki/Game_mode/osu!) 中也被當作控制游標的輸入裝置。在 osu! 中是最常見的遊玩風格。
```

2021-04-25 11:15 UTC, kj415j45 approved these changes

2021-04-25 16:13 UTC, TPGPL approved these changes

2021-04-25 16:13 UTC, merged