[ZH-TW] Add osu! wiki Contribution Guide
ppy/osu-wiki pull request #5184
Opened 2021-04-04 13:08 UTC by SiderealArt

2021-04-25 11:42 UTC, kj415j45 requested changes

2021-04-25 11:42 UTC, kj415j45 commented on wiki/osu!_wiki_Contribution_Guide/zh-tw.md
> +**當你閱讀完 *GitHub Web Interface* or *GitHub Desktop* 的頁面後，你就可以繼續前往下個章節了。**
```suggestion
**當你閱讀完 *GitHub 網頁介面* 或 *GitHub Desktop* 的頁面後，你就可以繼續前往下個章節了。**
```

2021-05-25 13:56 UTC, TicClick approved these changes

2021-05-31 11:21 UTC, kj415j45 approved these changes

2021-05-31 22:19 UTC, TicClick commented
aaaand we're live

2021-05-31 22:19 UTC, merged