[FR] Hit object stubs
ppy/osu-wiki pull request #5186
Opened 2021-04-04 14:31 UTC by DoryanR

Translation of the following wiki pages:

- Hit_object/Approach_circle
- Hit_object/Hit_circle
- Hit_object/Juice_stream
- Hit_object/Reverse_slider
- Hit_object/Slider_anchor
- Hit_object/Slider_velocity
- Hit_object/Sliderbody
- Hit_object/Sliderhead
- Hit_object/Slidertail
- Hit_object/Spinner

2021-04-22 23:30 UTC, osuShiro requested changes

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Approach_circle/fr.md
> +Les *approach circle* sont des cercles de couleur qui se rétrécissent autour des [hit circles](/wiki/Hit_object/Hit_circle) dans les [beatmaps](/wiki/Beatmap) du mode [osu!](/wiki/Game_mode/osu!). Il
```suggestion
Les *approach circle* sont des cercles de couleur qui se rétrécissent autour des [hit circles](/wiki/Hit_object/Hit_circle) dans les [beatmaps](/wiki/Beatmap) du mode [osu!](/wiki/Game_mode/osu!). Ils aident les joueurs à déterminer quand cliquer pour gagner le plus de [score](/wiki/Score) en se superposant au hit circle au bon moment dans une chanson. Le temps nécessaire à un approach circle pour atteindre un hit circle est déterminé par l'[approach rate (AR)](/wiki/Beatmapping/Approach_rate) d'une beatmap, qui est défini par le mappeur. La couleur des approach circle est également déterminée par les combo colours utilisées par le mappeur d'une beatmap.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Hit_circle/fr.md
> +Les *hit circles* sont des [hit objects](/wiki/Hit_object) colorés et circulaires présents dans les [beatmaps](/wiki/Beatmap) des modes [osu!](/wiki/Game_mode/osu!) et [osu!taiko](/wiki/Game_mode/osu
```suggestion
Les *hit circles* sont des [hit objects](/wiki/Hit_object) colorés et circulaires présents dans les [beatmaps](/wiki/Beatmap) des modes [osu!](/wiki/Game_mode/osu!) et [osu!taiko](/wiki/Game_mode/osu!taiko). Leur apparence varie d'un mode de jeu à l'autre, mais le joueur doit généralement cliquer sur le hit circle ou le toucher à temps pour gagner un [score](/wiki/Score) en fonction de sa [précision](/wiki/Accuracy) (par exemple, s'il clique trop tôt, ses points seront réduits). Toucher les hit circles remplit un peu la barre de santé, et un peu plus à la fin d'un combo.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Hit_circle/fr.md
> +Dans osu!, les hit circles apparaissent avec un numéro en haut, indiquant leur place dans un combo. Les hit circles sont également entourés de [approach circle](/wiki/Hit_object/Approach_circle), qui
```suggestion
Dans osu!, les hit circles apparaissent avec un numéro, indiquant leur place dans un combo. Ils sont également entourés de [approach circle](/wiki/Hit_object/Approach_circle), qui rétrécissent autour d'eux. Le joueur doit cliquer lorsque le approach circle recouvre le hit circle, pour gagner le maximum de points.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Juice_stream/fr.md
> +Les **juice streams** sont un élément du mode [osu!catch](/wiki/Game_Modes/osu!catch) qui comprend à la fois des drops et des droplets. Les drops donnent un score de 100, équivalent aux slider ticks
les deux sont équivalents aux slider ticks? C'est bizarre. Probablement une erreur dans l'article de base

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Reverse_slider/fr.md
> +Un *reverse slider* est un [hit objects](/wiki/Hit_object) dans le mode [osu!](/wiki/Game_mode/osu!), qui agit exactement comme un [slider](/wiki/Hit_object/Slider) avec l'avantage supplémentaire de
```suggestion
Un *reverse slider* est un [hit objects](/wiki/Hit_object) dans le mode [osu!](/wiki/Game_mode/osu!), qui agit exactement comme un [slider](/wiki/Hit_object/Slider) mais qui s'inverse au lieu de finir. Ceci est indiqué dans le gameplay par une flèche inversée à l'endroit où se trouverait le slidertail. Les sliders peuvent être inversés en cliquant sur la slidertail et en la faisant glisser sur la timeline de l'[éditeur de beatmap](/wiki/Beatmap_Editor). Cela peut être fait plusieurs fois sur le même slider pour créer un slider avec plusieurs inversions.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Slider_anchor/fr.md
> +Les *slider anchors* ou **anchor points**, modifient la forme des [sliderbodies](/wiki/Hit_object/Sliderbody). Il existe deux types d'ancres : les ancres blanches et les ancres rouges. Les ancres bla
```suggestion
Les *slider anchors* ou **anchor points**, modifient la forme des [sliderbodies](/wiki/Hit_object/Sliderbody). Il existe deux types d'anchors : les anchors blanches et les anchors rouges. Les anchors blanches créent des courbes douces et affectent les autres anchors blanches jusqu'à ce que le slider se termine ou qu'une anchor rouge soit placée. Les anchors rouges sont des points d'arrêt et peuvent être utilisées pour créer des angles aigus.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Slider_velocity/fr.md
> +Le *slider velocity* est un nombre qui décrit la distance parcourue par un [slider](/wiki/Hit_object/Slider) en un temps complet. Une vitesse de base peut être assignée par l'intermédiaire de l'ongle
```suggestion
Le *slider velocity* est un nombre qui décrit la distance parcourue par un [slider](/wiki/Hit_object/Slider) en un battement de mesure. Une vitesse de base peut être assignée par l'intermédiaire de l'onglet `Timing` dans l'[éditeur de beatmap](/wiki/Beatmap_Editor) de la fenêtre principale. Un multiplicateur de cette valeur peut ensuite être défini pour les différentes sections d'une beatmap en ajoutant des [inheriting timing points](/wiki/Beatmap_Editor/Timing) et en modifiant la valeur du multiplicateur du slider velocity.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Slider_velocity/fr.md
> +Le slider velocity est mesurée en *centaines d'[osupixels](/wiki/Glossary#osupixel) par battement,* ainsi un slider avec une vitesse de 1.00 parcourra 100 osupixels (ou, 100 pixels à une résolution d
```suggestion
Le slider velocity est mesurée en *centaines d'[osupixels](/wiki/Glossary#osupixel) par battement.* Un slider avec une vitesse de 1.00 parcourra 100 osupixels (ou 100 pixels à une résolution de 640x480) en un battement complet. Comme la vitesse dépend de la longueur d'un battement, les sliders avec le même paramètre de vitesse se déplaceront plus rapidement avec un BPM plus élevé.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Slider_velocity/fr.md
> +Une ancienne technique de mapping utilise des slider velocity qui sont des multiples de 0,16 (par exemple, 1,60, 1,76, 1,92, etc.). Cela a pour effet d'aligner les extrémités des sliders droits avec
```suggestion
Une ancienne technique de mapping utilise des slider velocity qui sont des multiples de 0,16 (par exemple, 1,60, 1,76, 1,92, etc.). Cela a pour effet d'aligner les extrémités des sliders droits avec la grille d'osu! lorsque les sliders utilisent le snapping 1/1 ou 1/2.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Sliderbody/fr.md
> +Un *sliderbody* constitue le chemin entre un [sliderhead](/wiki/Hit_object/Sliderhead) et un [slidertail](/wiki/Hit_object/Slidertail) dans les [beatmaps](/wiki/Beatmap) du mode [osu!](/wiki/Game_mod
```suggestion
Un *sliderbody* constitue le chemin entre un [sliderhead](/wiki/Hit_object/Sliderhead) et un [slidertail](/wiki/Hit_object/Slidertail) dans les [beatmaps](/wiki/Beatmap) du mode [osu!](/wiki/Game_mode/osu!). Le joueur doit suivre le sliderbody le long de son chemin une fois que le sliderhead a été cliqué jusqu'à ce que le slidertail soit atteint. Le sliderbody est la partie la plus polyvalente des sliders car il peut être manipulé avec les changements de [slider anchors](/wiki/Hit_object/Slider_anchor) et de [slider velocity](/wiki/Hit_object/Slider_velocity). La couleur des sliderbodies est déterminée par les combo colours que les mappeurs d'une beatmap utilisent.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Sliderhead/fr.md
> +Les *slidersheads* ou **sliderstarts** sont les points de départ de tous les [sliders](/wiki/Hit_object/Slider) trouvés dans les [beatmaps](/wiki/Beatmap) du mode [osu!](/wiki/Game_mode/osu!) . Une f
```suggestion
Les *slidersheads* ou **sliderstarts** sont les points de départ de tous les [sliders](/wiki/Hit_object/Slider) trouvés dans les [beatmaps](/wiki/Beatmap) du mode [osu!](/wiki/Game_mode/osu!) . Après avoir cliqué sur un sliderhead, le joueur doit suivre le [sliderbody](/wiki/Hit_object/Sliderbody) avec son périphérique de saisie, jusqu'à ce que le [slidertail](/wiki/Hit_object/Slidertail) soit atteint et qu'il puisse relâcher son bouton. La couleur des sliderheads est déterminée par le combo colours utilisées par les mappeurs d'une beatmap.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Spinner/fr.md
> +Un *spinner* est un [hit object](/wiki/Hit_object) dans [osu!](/wiki/Game_mode/osu!) qui occupe toute la surface de jeu. Pour effacer un spinner, maintenez le bouton de la souris ou du clavier enfonc
```suggestion
Un *spinner* est un [hit object](/wiki/Hit_object) dans [osu!](/wiki/Game_mode/osu!) qui occupe toute la surface de jeu. Pour compléter un spinner, maintenez le bouton de la souris ou du clavier enfoncé (ou maintenez le stylet sur la tablette). À partir de là, utilisez la souris (ou le stylet) et faites tourner le spinner (dans un des deux sens) jusqu'à ce que le cercle du spinner s'agrandisse complètement. Un avis *Clear* apparaîtra pour indiquer que le spinner est terminé. Si le spinner a été terminé plus tôt que prévu, continuez à tourner pour obtenir un bonus de [score](/wiki/Score) supplémentaire et regagner un peu de santé.
```

2021-04-22 23:30 UTC, osuShiro commented on wiki/Hit_object/Spinner/fr.md
> +Le cercle blanc extérieur indique le temps restant pour compléter le spinner. Ce cercle devient rouge pour indiquer que le temps est presque écoulé. Les anciennes beatmaps, utilisant la *skin version
```suggestion
Le cercle blanc extérieur indique le temps restant pour compléter le spinner. Ce cercle devient rouge pour indiquer que le temps est presque écoulé. Les anciennes beatmaps, utilisant la *skin version 1.0*, auront un compteur/jauge pour indiquer à quel point le joueur est proche de terminer le spinner. La petite case sous le compteur indique le nombre de tours par minute. Le chiffre à l'intérieur de cette case correspond au nombre de tours possibles si l'on continue à faire tourner la roulette à cette vitesse pendant une minute. Si le bouton de la souris ou du clavier a été relâché (ou si le stylet n'a pas touché la tablette) au début du tour, le compteur s'arrête de lire le tour.
```

2021-04-23 08:06 UTC, DoryanR commented on wiki/Hit_object/Juice_stream/fr.md
> +Les **juice streams** sont un élément du mode [osu!catch](/wiki/Game_Modes/osu!catch) qui comprend à la fois des drops et des droplets. Les drops donnent un score de 100, équivalent aux slider ticks
Alors si j'ai bien compris, les drops ce sont les sliderhead et les slidertail, et les droplets ce sont les slider tick. Après ça parle des score que donne les deux, donc je sais pas trop effectivement, y'a une erreur dans la version anglaise a mon avis, car ça me semble bizarre

2021-04-26 15:03 UTC, osuShiro requested changes

2021-04-26 15:03 UTC, osuShiro commented on wiki/Hit_object/Slider_velocity/fr.md
> +Le *slider velocity* est un nombre qui décrit la distance parcourue par un [slider](/wiki/Hit_object/Slider) en un battement de mesure. Une vitesse de base peut être assignée par l'intermédiaire de l
"par l'intermédiaire de l'onglet `Timing` dans l'éditeur de beatmap de la fenêtre principale"

Je me rends compte que cette phrase est vraiment bizarre. Tous voulais peut-être dire "la fenêtre principale de l'onglet timing"?

2021-04-26 15:10 UTC, DoryanR commented on wiki/Hit_object/Slider_velocity/fr.md
> +Le *slider velocity* est un nombre qui décrit la distance parcourue par un [slider](/wiki/Hit_object/Slider) en un battement de mesure. Une vitesse de base peut être assignée par l'intermédiaire de l
Oula oui effectivement, c'est plus simple avec ce que tu me propose, je change ça

2021-04-26 15:18 UTC, osuShiro approved these changes

2021-04-26 15:18 UTC, merged