[FR] Mapping techniques stubs
ppy/osu-wiki pull request #5188
Opened 2021-04-04 17:12 UTC by DoryanR

Translation of the following wiki pages:

- Mapping_Techniques/Blanket
- Mapping_Techniques/Overlap
- Mapping_Techniques/Stack
- Mapping_Techniques/Time-distance_equality

2021-04-22 23:15 UTC, osuShiro requested changes

2021-04-22 23:15 UTC, osuShiro commented on wiki/Mapping_Techniques/Blanket/fr.md
> +Un **blanket** est l'effet créé lorsqu'un [sliderbody](/wiki/Hit_object/Sliderbody) s'enroule autour de la forme d'un autre [objet](/wiki/Hit_object). le blanket peut être réalisée de plusieurs façon
```suggestion
Un **blanket** est l'effet créé lorsqu'un [sliderbody](/wiki/Hit_object/Sliderbody) s'enroule autour de la forme d'un autre [objet](/wiki/Hit_object). Le blanket peut être réalisé de plusieurs façons pour s'adapter au style visuel d'une [beatmap](/wiki/Beatmap). Vous trouverez un guide pour les réaliser dans l'article sur les [techniques de mapping](/wiki/Mapping_Techniques/Making_Good_Sliders#beat-blankets).
```

2021-04-22 23:15 UTC, osuShiro commented on wiki/Mapping_Techniques/Overlap/fr.md
> +Un **overlap** apparaît lorsque des [objets](/wiki/Hit_Objects) se touchent sans créer de [stacking](/wiki/Mapping_Techniques/Stack).
"chevauchent" plutôt que "touchent" me semble plus clair?

2021-04-22 23:15 UTC, osuShiro commented on wiki/Mapping_Techniques/Stack/fr.md
> +![](img/stack.jpg "Un exemple de deux cercle empilés sur un sliderhead.")
```suggestion
![](img/stack.jpg "Un exemple de deux cercles empilés sur un sliderhead.")
```

2021-04-22 23:15 UTC, osuShiro commented on wiki/Mapping_Techniques/Stack/fr.md
> +Un **stack** est un ensemble d'[objets](/wiki/Hit_Objects) qui sont en [overlap](/wiki/Mapping_Techniques/Overlap) les uns sur les autres dans le champ de jeu. Les objets les plus courants qui sont e
```suggestion
Un **stack** est un ensemble d'[objets](/wiki/Hit_Objects) qui sont en [overlap](/wiki/Mapping_Techniques/Overlap) les uns sur les autres dans le champ de jeu. Les objets les plus courants qui sont stackés sont les [cercles](/wiki/Hit_Objects#hit-circle).
```

2021-04-22 23:15 UTC, osuShiro commented on wiki/Mapping_Techniques/Stack/fr.md
> +Les stacks sont automatiquement créées lorsque les objets sont proches de se chevaucher parfaitement. Le temps entre les objets pour que cela se produise est déterminé par l'indulgence du stacking de
```suggestion
Les stacks sont automatiquement créés lorsque les objets sont proches de se chevaucher parfaitement. Le temps entre les objets pour que cela se produise est déterminé par l'indulgence du stacking de la [beatmap](/wiki/Beatmap).
```

2021-04-22 23:15 UTC, osuShiro commented on wiki/Mapping_Techniques/Time-distance_equality/fr.md
> +Dans les [difficultés](/wiki/Beatmap/Difficulty) inférieures, le time-distance equality est utilisée pour rendre le jeu plus intuitif pour les nouveaux joueurs.
```suggestion
Dans les [difficultés](/wiki/Beatmap/Difficulty) inférieures, le time-distance equality est utilisé pour rendre le jeu plus intuitif pour les nouveaux joueurs.
```

2021-04-23 08:32 UTC, DoryanR commented on wiki/Mapping_Techniques/Overlap/fr.md
> +Un **overlap** apparaît lorsque des [objets](/wiki/Hit_Objects) se touchent sans créer de [stacking](/wiki/Mapping_Techniques/Stack).
Oui, ce sera plus clair a mon avis

2021-04-26 14:57 UTC, osuShiro approved these changes

2021-04-26 14:57 UTC, merged