[FR] Modding stubs
ppy/osu-wiki pull request #5189
Opened 2021-04-04 19:46 UTC by DoryanR

Translation of the following wiki pages:

- Modding/BAT_Managers
- Modding/Beatmap_Appreciation_Team
- Modding/MAT_Leaders
- Modding/Mod_for_mod
- Modding/Mod_request
- Modding/Modder
- Modding/Normal_mod
- Modding/Nuke
- Modding/Proto-bubble
- Modding/Star_priority

2021-04-22 23:12 UTC, osuShiro requested changes

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Nuke/fr.md
> +Les **Nukes** étaient un outil de modération des [beatmaps](/wiki/Beatmap) dans les premières années d'osu!. Toute beatmap qui était considéré comme ne respectant pas les règles (ou dont le créateur
```suggestion
Les **Nukes** étaient un outil de modération des [beatmaps](/wiki/Beatmap) dans les premières années d'osu!. Toute beatmap qui était considérée comme ne respectant pas les règles (ou dont le créateur ne respectait pas le [Code de conduite](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping)) pouvait être "nuked" par le [Beatmap Appreciation Team (BAT)](/wiki/Modding/Beatmap_Appreciation_Team) ou la [Global Moderation Team (GMT)](/wiki/People/The_Team/Global_Moderation_Team).
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Nuke/fr.md
> +Lorsqu'une beatmap était "nuked", il avait un symbole radioactif ![](/wiki/shared/icon/nuke.gif) sur son fil de discussion. Cela signalait aux autres membres du BAT/GMT qu'il ne devait pas être consi
```suggestion
Lorsqu'une beatmap était "nuked", il avait un symbole radioactif ![](/wiki/shared/icon/nuke.gif) sur son fil de discussion. Cela signalait aux autres membres du BAT/GMT qu'elle ne devait pas être considérée pour la section [Classée](/wiki/Beatmap_ranking_procedure#ranked) sans changements importants. Si une beatmap a effectué les modifications correspondantes, l'icône sera supprimée et elle pourra poursuivre le [processus de classement](/wiki/Beatmap_ranking_procedure).
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Nuke/fr.md
> +- Ne pas respecter les principes de base des [Critères de classement](/wiki/Ranking_Criteria).
```suggestion
- Le non respect des principes de base des [Critères de classement](/wiki/Ranking_Criteria).
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Nuke/fr.md
> +  - Contenant des sections mal cadencées
```suggestion
  - La présence de sections mal cadencées
```

Je dois avouer que je ne comprends pas le terme "cadencées" ici. Si "timing" n'a pas été traduit dans les autres pages, remplace ça par "mal timées" ou "avec un mauvais timing"

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Nuke/fr.md
> +  - Contenant des [objets](/wiki/Hit_object) placés de manière aléatoire sur la grille et/ou la timeline.
```suggestion
  - La présence [d'objets](/wiki/Hit_object) placés de manière aléatoire sur la grille et/ou la timeline.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Nuke/fr.md
> +- Ne pas respecter le [Code de conduite de modding et de mapping](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping).
```suggestion
- Le non respect [Code de conduite de modding et de mapping](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping).
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Proto-bubble/fr.md
> +La **proto-bubble** (***pubble***) était une icône de message de forum utilisée par les membres de la [Mapping Assistance Team (*MAT*)](/wiki/Modding/Mapping_Assistance_Team) dans les itérations préc
```suggestion
La **proto-bubble** (***pubble***) était une icône de message de forum utilisée par les membres de la [Mapping Assistance Team (*MAT*)](/wiki/Modding/Mapping_Assistance_Team) dans les itérations précédentes du [beatmap ranking process](/wiki/Beatmap_ranking_procedure). Elle a été conçue pour indiquer les [beatmaps](/wiki/Beatmap) dont la qualité est jugée suffisamment élevée pour être [classée](/wiki/Beatmap/Category#ranked) par les membres de la [Beatmap Appreciation Team (*BAT*)](/wiki/Modding/Beatmap_Appreciation_Team), qui pouvaient alors placer une bulle complète si la beatmap rencontrait leur approbation.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Proto-bubble/fr.md
> +La proto-bubble a été retirée le 23 avril 2013, avec la dissolution du MAT et la promotion de tous les membres actuels de l'équipe au BAT.
```suggestion
La proto-bubble a été retirée le 23 avril 2013, avec la dissolution du MAT et la promotion de tous les membres de l'équipe au BAT.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +Le star priority à deux significations :
```suggestion
Le terme **star priority** a deux sens:
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +1. Une méthode pour aider les Beatmap Nominators à trouver des beatmaps dignes d'être mis en bulles et d'être classés ultérieurement.
```suggestion
1. Une méthode pour aider les Beatmap Nominators à trouver des beatmaps dignes de recevoir une bubble et d'être classées ultérieurement.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +   - Le star priority d'un beatmap est déterminée par le nombre de messages de mods qui ont obtenu des kudosu dans le fil de discussion du beatmap, la somme des étoiles de kudosu que la beatmap a reç
```suggestion
   - La star priority d'une beatmap est déterminée par la somme du nombre de messages de mods qui ont obtenu des kudosu dans le fil de discussion de la beatmap et du total étoiles de kudosu que la beatmap a reçues.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +   - Une étoile de kudosu peut être donnée par n'importe quel utilisateur à n'importe quel beatmap, bien que tirer une étoile de kudosu se fasse au prix d'un kudosu.
```suggestion
   - Une étoile de kudosu peut être donnée par n'importe quel utilisateur à n'importe quel beatmap, chaque étoile coûtant un kudosu.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +   - Le taux de conversion était auparavant de trois kudosu pour une étoile kudosu qui augmentait la priorité d'étoile de deux.
```suggestion
   - Le taux de conversion était auparavant de trois kudosu pour une étoile kudosu qui augmentait la star priority de deux.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +   - Plus la priorité de l'étoile est élevée, plus le fil de discussion du beatmap apparaît dans le sous-forum Work in Progress ou Pending.
```suggestion
   - Plus la star priority était élevée, plus le fil de discussion de la beatmap apparaissait haut dans le sous-forum Work in Progress ou Pending.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +   - Plus la priorité de l'étoile est élevée, plus vite elle est remarquée.
```suggestion
   - Plus la star priority est élevée, plus vite elle est remarquée.
```

2021-04-22 23:12 UTC, osuShiro commented on wiki/Modding/Star_priority/fr.md
> +   - Les utilisateurs qui ont le statut de supporter actif au moment du vote tireront une étoile rose (![Kudosu](/wiki/shared/Kudos.png)) qui augmente la priorité des étoiles de 2 chacune, tandis qu'
```suggestion
   - Les utilisateurs qui ont le statut de supporter actif au moment du vote donnent une étoile rose (![Kudosu](/wiki/shared/Kudos.png)) qui augmente la star priority de 2 chacune, tandis qu'un utilisateur sans supporter donne une étoile bleue (![Star](/wiki/shared/icon/star.gif)) qui n'augmente la star priority que de 1. Les utilisateurs peuvent donner plusieurs étoiles en fonction du nombre de votes qu'il leur reste.
```

2021-04-23 07:44 UTC, DoryanR commented on wiki/Modding/Normal_mod/fr.md
> +Un **normal mod (*NM*)** est un [modding](/wiki/Modding) qui est fourni sans nécessiter de travail de la part du créateur demandeur. Les mods normaux sont généralement réalisés pour obtenir un deuxiè
Faute d'inattention, je corrige ça

2021-04-26 14:56 UTC, osuShiro requested changes
HL moi dès que tu as fait les changements que je puisse merge, désolée d'avoir loupé ces deux trucs ><

2021-04-26 14:56 UTC, osuShiro commented on wiki/Modding/Mod_for_mod/fr.md
> +Le mod for mod ont historiquement été préférés aux mods réguliers, car les deux parties bénéficient de cet accord, mais ils sont devenus moins courants ces dernières années.
```suggestion
Le mod for mod ont historiquement été préférés aux mods réguliers, car les deux partis bénéficient de cet accord, mais ils sont devenus moins courants ces dernières années.
```

Je sais pas comment j'ai manqué ça

2021-04-26 14:56 UTC, osuShiro commented on wiki/Modding/Nuke/fr.md
> +Les **Nukes** étaient un outil de modération des [beatmaps](/wiki/Beatmap) dans les premières années d'osu!. Toute beatmap qui était considérée comme ne respectant pas les règles (ou dont le créateur
```suggestion
Les **Nukes** étaient un outil de modération des [beatmaps](/wiki/Beatmap) dans les premières années d'osu!. Toute beatmap qui était considérée comme ne respectant pas les règles (ou dont le créateur ne respectait pas le [Code de conduite](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping)) pouvait être "nuked" par la [Beatmap Appreciation Team (BAT)](/wiki/Modding/Beatmap_Appreciation_Team) ou la [Global Moderation Team (GMT)](/wiki/People/The_Team/Global_Moderation_Team).
```

2021-04-26 15:04 UTC, osuShiro approved these changes

2021-04-26 15:04 UTC, merged