add ID "osu!_File_Formats"
ppy/osu-wiki pull request #5200
Opened 2021-04-05 15:31 UTC by mousesalt

2021-04-05 15:38 UTC, wowcake requested changes

2021-04-05 15:38 UTC, wowcake commented on wiki/osu!_File_Formats/Osz_(file_format)/id.md
> +**.osz** adalah sebuah arsip file yang mengandung tingkat kesulitan beatmap dan sumber daya lainnya, seperti skin maupun hitsounds.
```suggestion
**.osz** adalah sebuah arsip file yang mengandung tingkat kesulitan beatmap dan sumber daya lainnya, seperti skin maupun hitsound.
```

2021-04-05 15:38 UTC, wowcake commented on wiki/osu!_File_Formats/Osz_(file_format)/id.md
> +**.osz** adalah sebuah arsip file yang mengandung tingkat kesulitan beatmap dan sumber daya lainnya, seperti skin maupun hitsounds.
remove the s

2021-04-06 05:07 UTC, ZeroPyrozen requested changes

2021-04-06 05:07 UTC, ZeroPyrozen commented on wiki/osu!_File_Formats/Osb_(file_format)/id.md
> +.osb adalah sebuah file arsip yang mengandung informasi mengenai tentang storyboard osu!.
```suggestion
.osb adalah sebuah format file yang mengandung informasi mengenai tentang [storyboard osu!](/wiki/Storyboards).
```

2021-04-06 05:07 UTC, ZeroPyrozen commented on wiki/osu!_File_Formats/Osk_(file_format)/id.md
> +**.osk** adalah file arsip yang berisi folder dari [skin osu!](/wiki/Skinning).
```suggestion
**.osk** adalah file arsip yang berisi folder [skin osu!](/wiki/Skinning).
```

2021-04-06 09:36 UTC, ZeroPyrozen approved these changes
All good 👍

2021-04-09 12:36 UTC, TicClick approved these changes

2021-04-09 12:37 UTC, merged