[FR] "solo" stubs
ppy/osu-wiki pull request #5206
Opened 2021-04-05 17:57 UTC by DoryanR

_"Solo stubs" referring to those that are in the /wiki root or that are in a folder, but being the only stub in the folder._

Translation of the following wiki pages:

- Ouendan
- Pass
- People/peppy
- Ranking
- Recalculate_slider_lengths
- Resnap
- Silence
- Skinning/Skinner
- Star
- Storyboarding/Storyboarder
- Universal_offset
- iNiS_games
- osu!coin
- osupixel
- upppy

And in [EN] iNiS_games : fix external link

2021-04-22 22:49 UTC, osuShiro commented
Pense à mettre la branche à jour pour résoudre les conflits avant de pouvoir ajouter la traduction!

2021-04-23 07:41 UTC, DoryanR commented
> Pense à mettre la branche à jour pour résoudre les conflits avant de pouvoir ajouter la traduction!

Les conflits sont résolu normalement, j'ai mit a jour la branche

2021-04-24 14:10 UTC, Ganondorfosu requested changes

2021-04-24 14:10 UTC, Ganondorfosu commented on wiki/iNiS_games/fr.md
> +Le [mode de jeu](/wiki/Game_mode) [osu!standard](/wiki/Game_mode/osu!) et osu! lui-même étaient à l'origine basés sur des jeux de rythme développés par **[iNiS](https://fr.wikipedia.org/wiki/INiS "Wi
```suggestion
Le [mode de jeu](/wiki/Game_mode) [osu!standard](/wiki/Game_mode/osu!) et osu! lui-même étaient à l'origine basés sur des jeux de rythme développés par **[iNiS](https://fr.wikipedia.org/wiki/INiS "Wikipédia")** pour la [Nintendo DS](https://fr.wikipedia.org/wiki/Nintendo_DS "Wikipédia") au début des années 2000. ![][flag_AU] [peppy](https://osu.ppy.sh/users/2) a construit osu! pour être un simulateur et un éditeur de niveaux pour les jeux iNiS, et les premiers membres de la communauté en étaient généralement fans aussi. Les anciennes [beatmaps](/wiki/Beatmap) ont été fortement influencées par la conception des niveaux d'iNiS.
```

2021-04-24 14:10 UTC, Ganondorfosu commented on wiki/osu!coin/fr.md
> +- premier enfant à naître = une infinités d'osu!coins (l'enfant à naître fonctionne pour osu!)
```suggestion
- premier enfant à naître = une infinité d'osu!coins (l'enfant travaillera pour osu!)
```

2021-04-24 14:20 UTC, DoryanR commented on wiki/Silence/fr.md
> +- Envoyer/recevoir des messages privés
T'es sur qu'on peut juste en recevoir, mais pas en envoyer ?

2021-05-12 14:56 UTC, Satsukel requested changes
Fixing typos and mistakes

2021-05-12 14:56 UTC, Satsukel commented on wiki/Star/fr.md
> +   - Ils sont donnés aux modder de beatmap et peuvent être utilisés pour élever une beatmap au-dessus des autres.
```suggestion
   - Ils sont donnés aux modders de beatmap et peuvent être utilisés pour élever une beatmap au-dessus des autres.
```

2021-05-12 14:56 UTC, Satsukel commented on wiki/Star/fr.md
> +   - Ces étoiles sont attribuées aux [supporters d'osu](/wiki/osu!support) et sont utilisées dans les [Feature Requests](https://osu.ppy.sh/community/forums/4)..
```suggestion
   - Ces étoiles sont attribuées aux [supporters d'osu](/wiki/osu!support) et sont utilisées dans les [Feature Requests](https://osu.ppy.sh/community/forums/4).
```

2021-05-12 14:56 UTC, Satsukel commented on wiki/iNiS_games/fr.md
> +Les jeux auxquels il est fait référence sont :
```suggestion
Les jeux auxquels il fait référence sont :
```

2021-05-12 15:49 UTC, DoryanR commented on wiki/Silence/fr.md
> +- Envoyer/recevoir des messages privés
@osuShiro possible de confirmer ce point ? je suis pas sur qu'on puissent recevoir des mp quand on est silence

2021-05-13 16:06 UTC, Satsukel submitted a review, later dismissed

2021-05-17 14:36 UTC, TicClick requested changes

2021-05-17 14:36 UTC, TicClick commented on wiki/Universal_offset/fr.md
> +<!-- TODO: needs some explanation of the confusing negative/positive behavior and links to guide how to set it correctly -->
this translation is outdated, check with the original

2021-05-17 14:36 UTC, TicClick commented on wiki/iNiS_games/en.md
> +The [osu!](/wiki/Game_mode/osu!) [game mode](/wiki/Game_mode) and osu! itself were originally based on rhythm games developed by **[iNiS](https://en.wikipedia.org/wiki/INiS_Corporation "iNiS on Wikip
this is unnecessary -- the original link is a redirect to `/wiki/INiS_Corporation` anyway

2021-05-17 14:36 UTC, TicClick commented on wiki/Star/fr.md
> +---
I've just moved it to `/wiki/Disambiguation/Star` in #5457, please do so accordingly

2021-05-17 15:37 UTC, TicClick commented on wiki/Star/fr.md
> +---
same goes for `Ouendan`: #5451

2021-05-18 20:03 UTC, Satsukel approved these changes

2021-05-21 16:01 UTC, TicClick approved these changes

2021-05-21 16:05 UTC, merged