[FR] Performance points stubs
ppy/osu-wiki pull request #5207
Opened 2021-04-05 18:13 UTC by DoryanR

Translation of the following wiki pages:

- Performance_points/Total_performance_points
- Performance_points/Weighting_system
- Performance_points/ppv2

2021-04-16 13:18 UTC, osuShiro requested changes

2021-04-16 13:18 UTC, osuShiro commented on wiki/Performance_points/Total_performance_points/fr.md
> +  - rank
ajoute une ligne avec "tags:" pour corriger le header

2021-04-16 13:18 UTC, osuShiro commented on wiki/Performance_points/Total_performance_points/fr.md
> +Le **total des points de performances** est une valeur qui détermine le [ranking](/wiki/Ranking) d'un joueur par rapport aux autres. Il est calculé sur la base des scores obtenus, de l'algorithme [pp
le mot "valeur" ne correspond pas ici; il s'agit simplement d'un nombre

2021-04-16 13:18 UTC, osuShiro commented on wiki/Performance_points/Total_performance_points/fr.md
> +Le classement des points de performance de tous les joueurs se trouve sur le [classement mondial](https://osu.ppy.sh/rankings/osu/performance). Il est également possible d'y accéder en passant la sou
plutôt que "Le classement des points de performance de tous les joueurs", mets plutôt quelque chose du genre "Le classement des joueurs selon leurs points de performance"

2021-04-16 13:18 UTC, osuShiro commented on wiki/Performance_points/Weighting_system/fr.md
> +Le **weighting system** détermine le [total des points de performances](/wiki/Performance_Points/Total_Performance_Points) d'un joueur en pondérant chaque valeur individuelle de [points de performanc
"améliorer ses capacités de jeu" -> "s'améliorer"

2021-04-16 13:18 UTC, osuShiro commented on wiki/Performance_points/Weighting_system/fr.md
> +- `pp[n]` décrit la valeur pp de la `n`ième note après que les notes aient été triées de manière décroissante.
"note" n'est pas la bonne traduction ici - pp[n] fait référence aux top plays (en order descendant). "Performance" marche, mais ça dépend de comment "best performances" a été traduit dans d'autres articles. "Score" marche aussi et est cohérent avec le mot utilisé plus bas

2021-04-16 13:18 UTC, osuShiro commented on wiki/Performance_points/ppv2/fr.md
> +**ppv2** est l'algorithme actuel du système de [points de performance](/wiki/Performance_points), et vise à représenter la difficulté de réaliser un jeu donné sur une [beatmap](/wiki/Beatmap). Il a é
Je comprends pas du tout la présence du mot "jeu" ici. C'est pour définir un score?

2021-04-16 19:43 UTC, DoryanR commented on wiki/Performance_points/ppv2/fr.md
> +**ppv2** est l'algorithme actuel du système de [points de performance](/wiki/Performance_points), et vise à représenter la difficulté de réaliser un jeu donné sur une [beatmap](/wiki/Beatmap). Il a é
Hmm effectivement c'est bizarre, je vais voir ce que je peut faire pour modifier ça.

Je pense que j'ai voulu dire ça par rapport à quoi l'algorithme ce base pour calculer les pp, en évoquant le "jeu".

2021-04-22 22:47 UTC, osuShiro requested changes

2021-04-22 22:47 UTC, osuShiro commented on wiki/Performance_points/Total_performance_points/fr.md
> +Le rang individuel d'un joueur peut également être vu un peut partout dans l'[interface](/wiki/Interface) du client d'osu!.
```suggestion
Le rang individuel d'un joueur peut également être vu un peu partout dans l'[interface](/wiki/Interface) du client d'osu!.
```

2021-04-22 22:47 UTC, osuShiro commented on wiki/Performance_points/Weighting_system/fr.md
> +Le **weighting system** détermine le [total des points de performances](/wiki/Performance_Points/Total_Performance_Points) d'un joueur en pondérant chaque valeur individuelle de [points de performanc
```suggestion
Le **weighting system** détermine le [total des points de performances](/wiki/Performance_Points/Total_Performance_Points) d'un joueur en pondérant chaque valeur individuelle de [points de performance](/wiki/Performance_Points) par rapport aux autres. Le système attribue ainsi un montant de plus en plus faible pour la deuxième meilleure valeur, la troisième meilleure valeur, et ainsi de suite. Cela garantit qu'un joueur doit s'améliorer pour progresser dans le système de points de performance. Pour une explication plus précise, voir la formule suivante :
```

"Ensuite" n'est pas le bon mot; la phrase explique la méthode de pondération

2021-04-22 22:47 UTC, osuShiro commented on wiki/Performance_points/Weighting_system/fr.md
> +- `n` va de 1 à `m`, où `m` est défini comme le nombre de scores d'un joueur.
```suggestion
- `n` va de 1 à `m`, où `m` est le nombre de scores d'un joueur.
```

2021-04-22 22:47 UTC, osuShiro commented on wiki/Performance_points/Weighting_system/fr.md
> +Le weighting system permet à un joueur de gagner jusqu'à 416,6667 points de performance supplémentaires pour avoir réalisé un grand nombre de scores. Le montant maximum est atteint à environ 25397 sc
```suggestion
Le weighting system permet à un joueur de gagner jusqu'à 416,6667 points de performance supplémentaires pour avoir réalisé un grand nombre de scores. Le montant maximum est atteint à 25397 scores totaux.
```

2021-04-26 14:45 UTC, osuShiro approved these changes

2021-04-26 14:45 UTC, merged