[FR] Play style stubs
ppy/osu-wiki pull request #5208
Opened 2021-04-05 20:01 UTC by DoryanR

Translation of the following wiki pages:

- Play_style/Alternating
- Play_style/Double_tapping
- Play_style/Drag
- Play_style/Hover
- Play_style/Hybrid
- Play_style/Single-tapping
- Play_style/Tapping_style
- Play_style/Tapx

2021-04-10 11:16 UTC, osuShiro commented
Let me know when you're done with this (highlight me in discord) so that I can have a look

2021-04-15 13:55 UTC, osuShiro requested changes
De manière générale, les traductions sont très littérales - ce n'est pas un défaut si c'est seulement une étape dans la traduction des articles. Pense à adapter les mots, les tournures de phrase, les expressions, et le vocabulaire utilisé dans la langue cible.

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +L'**Alternating** est un style de jeu pour le mode [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, font glisser des sliders et font tourner des spinners en alte
Toute cette traduction est assez littérale - elle marche et est compréhensible, mais n'est pas exactement du bon français (il faut retravailler la tournure de la phrase). Remplace par ça:

L'**Alternating** est une méthode de jeu qui consiste à cliquer sur les cercles, faire glisser les sliders, ou faire tourner les spinners, en alternant entre les deux touches de leur clavier (`Z` et `X` par défaut) d'un objet à l'autre, d'où le nom. Cette méthode est plus courante chez les joueurs plus expérimentés, étant plus difficiles à apprendre.

("every other" - "chaque autre" littéralement ne veut pas dire tous les deux, mais une fois sur deux)
("adapt to" veut dire "s'adapter à", mais ce verbe ne fonctionne pas dans ce context, il faut le remplacer par un autre qui garde le même sens)

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +L'Alternating a une grande variété d'utilisations et ses formes peuvent varier d'un joueur à l'autre. Par exemple, de nombreux joueurs qui alternent passent généralement de `Z` à `X` une note (ou obj
"a une grande variété d'utilisations" -> "peut être utilisé de diverses manières"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +Dans le même ordre d'idées, certains joueurs préfèrent taper sur leurs touches avec l'index et le majeur, tandis que d'autres utilisent l'index et l'annulaire. Les joueurs qui utilisent l'index et l'
"Dans le même ordre d'idées" -> "De même"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +Les arguments en faveur de l'alternating mentionnent généralement que l'alternating est beaucoup plus rapide car elle réduit le temps entre les pressions de touche par rapport au [single-tapping](/wi
"et permet ainsi" -> mets une virgule après "se reposer" et "permettant ainsi". La phrase est juste une succession de "et" et c'est lourd à lire

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +Les arguments contre l'alternating mentionnent généralement qu'il est beaucoup plus difficile de rester cohérent parce qu'un doigt est généralement plus fort/rapide que l'autre, tandis que d'autres a
"entraîner une confusion" -> "être déroutant"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Le **Double tapping** est un style de jeu pour le mode [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, font glisser des sliders et font tourner des spinners en
Si tu as fait le changement sur l'autre article, remplace "style" par "méthode"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Le **Double tapping** est un style de jeu pour le mode [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, font glisser des sliders et font tourner des spinners en
Ajoute "en même temps" après (`Z` et `X` par défaut)?

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Le **Double tapping** est un style de jeu pour le mode [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, font glisser des sliders et font tourner des spinners en
"Ce style est le plus souvent utilisé comme un style de frappe de substitution temporaire" -> "Cette méthode est le plus souvent temporaire" (si tu as fait le changement, sinon garde "ce style"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Le **Double tapping** est un style de jeu pour le mode [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, font glisser des sliders et font tourner des spinners en
Plutôt que "le moins précis", je mettrais "pour avoir la pire précision" pour faire référence directement à la mécanique de jeu - autrement "précis" peut être compris de différentes manières

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Le double tapping remplace généralement le style de jeu principal d'un joueur en raison de sa facilité d'exécution et de l'augmentation de la "vitesse" (même si le joueur ne frappe pas plus vite). Ce
si tu as remplacé "style" avant, remplace aussi celui-ci

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Les arguments en faveur du double tapping font généralement référence au fait qu'il s'agit d'un moyen rapide de permettre au joueur d'apprendre les mouvements de la beatmap qui viennent après le moti
"le" n'a pas de sens ici, puisqu'aucun pattern n'a été défini auparavant. Remplace-le par "un".

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Les arguments en faveur du double tapping font généralement référence au fait qu'il s'agit d'un moyen rapide de permettre au joueur d'apprendre les mouvements de la beatmap qui viennent après le moti
plutôt que "troublant", mets "difficile"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Les arguments en faveur du double tapping font généralement référence au fait qu'il s'agit d'un moyen rapide de permettre au joueur d'apprendre les mouvements de la beatmap qui viennent après le moti
"cheap" ne veut pas dire bon marché ici, mais "facile", "sans mérite"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Drag/fr.md
> +Le terme **drag** est utilisé pour décrire l'action de naviguer (ou de "viser") un stylo de [tablette](/wiki/Glossary#tablet) en touchant physiquement le stylo à la surface de la tablette et en le fa
ajoute "avec" après "viser" (dans les guillemets)

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Drag/fr.md
> +Le terme **drag** est utilisé pour décrire l'action de naviguer (ou de "viser") un stylo de [tablette](/wiki/Glossary#tablet) en touchant physiquement le stylo à la surface de la tablette et en le fa
"en touchant physiquement le stylo à la surface de la tablette" est mal tourné. Remplace-le par "en touchant la surface de la tablette avec le stylo"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Drag/fr.md
> +Les arguments en faveur du drag sont souvent que c'est plus confortable/naturel et qu'il est beaucoup plus difficile de "dépasser" sur les [jumps](/wiki/Beatmap/Pattern/Jump). D'autres affirment égal
"dépasser" -> "aller trop loin"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Drag/fr.md
> +Les arguments en faveur du drag sont souvent que c'est plus confortable/naturel et qu'il est beaucoup plus difficile de "dépasser" sur les [jumps](/wiki/Beatmap/Pattern/Jump). D'autres affirment égal
Je t'avouerais que je n'ai aucune idée de ce que cette deuxième phrase veut dire. Même dans l'article de base, c'est flou.

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Hover/fr.md
> +Le terme **hovering** est utilisé pour décrire l'action de naviguer (ou de "viser") un stylo de [tablette](/wiki/Glossary#tablet) sur une tablette en tenant le stylo au-dessus de la surface de la tab
le mot "tablette" est répété trois fois en un phrase, c'est assez lourd. Tu devrais probablement essayer de reformuler pour enlever la répétition.

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +L'Alternating a une grande variété d'utilisations et ses formes peuvent varier d'un joueur à l'autre. Par exemple, de nombreux joueurs qui alternent passent généralement de `Z` à `X` une note (ou obj
"passent généralement" -> "changent de touche" (et remplace le deuxième "changent de touchent" par "ne le font que"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +L'Alternating a une grande variété d'utilisations et ses formes peuvent varier d'un joueur à l'autre. Par exemple, de nombreux joueurs qui alternent passent généralement de `Z` à `X` une note (ou obj
"Il est à noter" -> "il faut souligner"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +L'Alternating a une grande variété d'utilisations et ses formes peuvent varier d'un joueur à l'autre. Par exemple, de nombreux joueurs qui alternent passent généralement de `Z` à `X` une note (ou obj
je remplacerais "prend au dépourvu" par simplement "surprend" aussi

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +Dans le même ordre d'idées, certains joueurs préfèrent taper sur leurs touches avec l'index et le majeur, tandis que d'autres utilisent l'index et l'annulaire. Les joueurs qui utilisent l'index et l'
"taper sur" -> "frapper", reste cohérent avec les mots choisis avant

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +Dans le même ordre d'idées, certains joueurs préfèrent taper sur leurs touches avec l'index et le majeur, tandis que d'autres utilisent l'index et l'annulaire. Les joueurs qui utilisent l'index et l'
"par opposition à" -> "au lieu de"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Hybrid/fr.md
> +- Certains joueurs hybrides tapent sur des [objets](/wiki/Hit_object) en changeant la touche avec laquelle ils tapent (`Z` et `X` par défaut) à intervalles réguliers tout au long d'une beatmap. Tout
fais attention que le vocabulaire soit cohérent d'un article à l'autre - parfois tu utilises "cliquer" pour les objets, parfois "taper"

de même tu as parfois "frapper" et parfois "taper" pour les touches du clavier

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Single-tapping/fr.md
> +Le **Single-tapping** est un style de jeu pour le mode [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, font glisser des sliders et font tourner des spinners en
si tu as remplacé "style" par "méthode" avant, fais-le aussi ici

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Single-tapping/fr.md
> +Le **Single-tapping** est un style de jeu pour le mode [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, font glisser des sliders et font tourner des spinners en
"celui auquel il est le plus facile de s'adapter." -> "le plus facile à apprendre"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Single-tapping/fr.md
> +Malgré leur nom, la plupart des joueurs qui utilise le single-tapping ne tapent pas toujours avec une seule touche. La plupart d'entre eux préfèrent taper sur une seule touche pour presque tout, sauf
"leur" -> "son"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Single-tapping/fr.md
> +Dans le même ordre d'idées, de nombreux joueurs affirment que l'utilisation d'un seul doigt est plus lente car il y a un délai nécessaire avant de pouvoir appuyer sur ce même doigt, tandis que d'autr
"Dans le même ordre d'idées" -> "De même"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Tapping_style/fr.md
> +Le terme **tapping style** est utilisé pour décrire une méthode de frappe des touches ou d'envoi des entrées sur le périphérique d'entrée pour toucher les [objets](/wiki/Hit_objects) dans osu!. Les t
"osu!standard" -> "osu!"

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Tapx/fr.md
> +*Avis : Ce style de jeu nécessite l'utilisation d'une tablette graphique.*
Tu peux enlever "avis" - ce n'est pas utile dans le contexte de l'article

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Tapx/fr.md
> +Le **tapx** est un style de jeu pour les joueurs de [tablette uniquement](/wiki/Play_style#tablet-only) dans [osu!standard](/wiki/Game_mode/osu!) dans lequel les joueurs cliquent sur des cercles, fon
osu!standard -> osu!

2021-04-15 13:55 UTC, osuShiro commented on wiki/Play_style/Tapx/fr.md
> +Le streaming via tapx s'effectue en alternant le tapotement d'un stylo sur une tablette et l'appui rapide sur une autre touche secondaire assignée (`Z` et `X` par défaut). Certains joueurs peuvent tr
stylo -> stylet

2021-04-16 19:23 UTC, DoryanR commented on wiki/Play_style/Drag/fr.md
> +Les arguments en faveur du drag sont souvent que c'est plus confortable/naturel et qu'il est beaucoup plus difficile de "dépasser" sur les [jumps](/wiki/Beatmap/Pattern/Jump). D'autres affirment égal
J'ai envie de l'enlever cette phrase, car elle embrouille plus qu'autre chose je pense

2021-04-22 22:42 UTC, osuShiro requested changes
Je me demande si on devrait pas changer toutes les mentions de "Z et X" pour "W et X" pour faire référence au clavier français. Je ne sais pas si le jeu détecte la langue de saisie automatiquement et ajuste les touches par défaut. Je vais voir.

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Alternating/fr.md
> +L'Alternating peut être utilisé de diverses manières et ses formes peuvent varier d'un joueur à l'autre. Par exemple, de nombreux joueurs qui pratique l'alternating changent de touche, passant de `Z`
```suggestion
L'Alternating peut être utilisé de diverses manières et ses formes peuvent varier d'un joueur à l'autre. Par exemple, de nombreux joueurs qui pratiquent l'alternating changent de touche, passant de `Z` à `X` une note (ou objet) sur deux, tandis que d'autres ne le font que tous les deux ou trois objets. Il faut souligner que certains joueurs le pratiquent la plupart du temps, mais frappent parfois deux fois la même touche si un objet les surprend. C'est une question de préférence personnelle.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Le **Double tapping** est une méthode de jeu pour le mode [osu!](/wiki/Game_mode/osu!) qui consiste à cliquer sur les cercles, faire glisser les sliders, ou faire tourner les spinners en appuyant sur
```suggestion
Le **Double tapping** est une méthode de jeu pour le mode [osu!](/wiki/Game_mode/osu!) qui consiste à cliquer sur les cercles, faire glisser les sliders, ou faire tourner les spinners en appuyant sur les deux touches du clavier (`Z` et `X` par défaut) en même temps. Cette méthode est le plus souvent temporaire pour les [stacks](/wiki/Mapping_Techniques/Stack) et les [streams](/wiki/Beatmap/Pattern/Stream) extrêmement rapides qui sont autrement trop difficiles pour certains joueurs. Ce style est connu pour avoir la pire précision.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Double_tapping/fr.md
> +Le double tapping remplace généralement la méthode de jeu principal d'un joueur en raison de sa facilité d'exécution et de l'augmentation de la "vitesse" (même si le joueur ne frappe pas plus vite).
```suggestion
Le double tapping remplace généralement la méthode de jeu principale d'un joueur en raison de sa facilité d'exécution et de l'augmentation de la "vitesse" (même si le joueur ne frappe pas plus vite). Cette augmentation de la vitesse est obtenue en tirant parti des hit windows qui se chevauchent le plus souvent dans les stacks et les streams. Ainsi, lorsque l'entrée d'une touche est enregistrée comme ayant frappé un cercle dans un stack, le cercle suivant sera également enregistré comme ayant été frappé car leurs hit windows sont si proches qu'elles se chevauchent. En conséquence, il est presque impossible de contrôler le timing de ces frappes, ce qui peut nuire à la [précision](/wiki/Accuracy) du joueur.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Drag/fr.md
> +Le terme **drag** est utilisé pour décrire l'action de naviguer (ou de "viser avec") un stylo de [tablette](/wiki/Glossary#tablet) en touchant sa surface avec le stylo et en le faisant "glisser" jusq
```suggestion
Le terme **drag** (littéralement: "trainer") est utilisé pour décrire l'action de naviguer (ou de "viser avec") un stylet de [tablette](/wiki/Glossary#tablet) en touchant sa surface avec le stylet et en le faisant "glisser" jusqu'à l'endroit souhaité (à l'inverse de l'[hover](/wiki/Play_style/Hover)). Ce style est utilisé par les joueurs de tous niveaux et est facile à apprendre.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Drag/fr.md
> +Les arguments en faveur du drag affirment que c'est plus confortable/naturel et qu'il est beaucoup plus difficile d'"aller trop loin" sur les [jumps](/wiki/Beatmap/Pattern/Jump).
```suggestion
Les arguments en faveur du drag affirment que c'est plus confortable/naturel et qu'il est beaucoup plus difficile "d'aller trop loin" sur les [jumps](/wiki/Beatmap/Pattern/Jump).
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Drag/fr.md
> +De même, de nombreux joueurs qui s'opposent au drag affirment qu'elle peut endommager la surface de la tablette sans l'utilisation d'une housse, qu'elle nécessite l'achat de plumes de rechange (en ra
```suggestion
De même, de nombreux joueurs qui s'opposent au drag affirment qu'il peut endommager la surface de la tablette sans l'utilisation d'une housse, qu'elle nécessite l'achat de plumes de rechange (en raison de l'usure des plumes) et que la friction est (techniquement) "plus lente".
```

Les autres méthodes de jeu été mentionnées comme "il" dans les autres articles

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Hover/fr.md
> +Le terme **hovering** utilisé pour décrire l'action de naviguer (ou de "viser avec") un stylet de [tablette](/wiki/Glossary#tablet) sur sa surface en tenant le stylet au-dessus tout en restant dans l
```suggestion
Le terme **hovering** utilisé pour décrire l'action de naviguer (ou de "viser avec") un stylet de [tablette](/wiki/Glossary#tablet) sur sa surface en tenant le stylet au-dessus tout en restant dans la zone de l'écran. Vous faites donc "planer" le stylet au-dessus de la tablette. Il s'agit d'une méthode de jeu au stylet qui s'oppose au [dragging](/wiki/Play_style/Drag). On la retrouve chez les joueurs de tous les niveaux de compétence, bien qu'il soit le plus souvent associé aux joueurs hautement qualifiés.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Hover/fr.md
> +Les arguments en faveur de l'hovering prétendent souvent qu'il réduit/supprime le besoin d'acheter des plumes de rechange, supprime le besoin d'une couverture de tablette, et est (techniquement) "plu
```suggestion
Les arguments en faveur de l'hovering prétendent souvent qu'il réduit/supprime le besoin d'acheter des plumes de rechange, supprime le besoin d'une couverture de tablette, et est (techniquement) "plus rapide" en raison d'un manque de friction, alors que les arguments contre le hovering prétendent souvent qu'il est beaucoup plus difficile de s'arrêter ou de tourner avec précision sur les [jumps](/wiki/Beatmap/Pattern/Jump) et les angles droits.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Single-tapping/fr.md
> +Le **Single-tapping** est une méthode de jeu pour le mode [osu!](/wiki/Game_mode/osu!) qui consiste à cliquer sur les cercles, faire glisser les sliders, ou faire tourner les spinners en utilisant un
```suggestion
Le **Single-tapping** est une méthode de jeu pour le mode [osu!](/wiki/Game_mode/osu!) qui consiste à cliquer sur les cercles, faire glisser les sliders, ou faire tourner les spinners en utilisant une seule touche du clavier (`Z` ou `X` par défaut). Ce style est commun à tous les joueurs, quel que soit leur niveau, et c'est le plus facile à apprendre.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Single-tapping/fr.md
> +Malgré son nom, la plupart des joueurs qui utilise le single-tapping ne frappent pas toujours avec une seule touche. La plupart d'entre eux préfèrent frapper sur une seule touche pour presque tout, s
```suggestion
Malgré son nom, la plupart des joueurs qui utilisent le single-tapping ne frappent pas toujours avec une seule touche. La plupart d'entre eux préfèrent frapper sur une seule touche pour presque tout, sauf pour les [streams](/wiki/Beatmap/Pattern/Stream), les [stacks](/wiki/Mapping_Techniques/Stack) et les streams rapides. Dans ce cas, ils opteront souvent pour un style [alternating](/wiki/Play_style/Alternating) et/ou [double tapping](/wiki/Play_style/Double_tapping).
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Single-tapping/fr.md
> +De même, de nombreux joueurs affirment que l'utilisation d'un seul doigt est plus lente car il y a un délai nécessaire avant de pouvoir appuyer sur ce même doigt, tandis que d'autres affirment que l'
```suggestion
De même, de nombreux joueurs affirment que l'utilisation d'un seul doigt est plus lente car il y a un délai nécessaire avant de pouvoir appuyer à nouveau avec ce même doigt, tandis que d'autres affirment que l'utilisation d'un seul doigt peut fatiguer le joueur beaucoup plus rapidement.
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Tapping_style/fr.md
> +Le terme **tapping style** est utilisé pour décrire une méthode de frappe des touches ou d'envoi des entrées sur le périphérique d'entrée pour frapper les [objets](/wiki/Hit_objects) dans osu!. Les t
```suggestion
Le terme **tapping style** est utilisé pour décrire une méthode de frappe des touches ou d'envoi des entrées sur le périphérique d'entrée pour frapper les [objets](/wiki/Hit_objects) dans osu!. Les tapping styles courants pour le mode [osu!](/wiki/Game_mode/osu!) comprennent l'[alternating](/wiki/Play_style/Alternating), le [single-tap](/wiki/Play_style/Single-tap), le [double tap](/wiki/Play_style/Double_tapping), l'[hybrid](/wiki/Play_style/Hybrid), ou encore le [tapx](/wiki/Play_style/Tapx).
```

2021-04-22 22:42 UTC, osuShiro commented on wiki/Play_style/Tapx/fr.md
> +Le **streaming** via tapx s'effectue en alternant le tapotement d'un stylet sur une tablette et l'appui rapide sur une autre touche secondaire assignée (`Z` et `X` par défaut). Certains joueurs peuve
```suggestion
Le **streaming** via tapx s'effectue en alternant le tapotement d'un stylet sur une tablette et l'appui rapide sur une autre touche secondaire assignée (`Z` et `X` par défaut). Certains joueurs peuvent trouver du réconfort en alternant le tapotement de la tablette et la touche secondaire entre chaque [objet](/wiki/Hit_objects), de la même manière que les joueurs qui utilisent l'[alternating](/wiki/Play_style/Alternating) déterminent les pressions de touche entre chaque objets.
```

2021-04-23 07:25 UTC, DoryanR commented
> Je me demande si on devrait pas changer toutes les mentions de "Z et X" pour "W et X" pour faire référence au clavier français. Je ne sais pas si le jeu détecte la langue de saisie automatiquement et ajuste les touches par défaut. Je vais voir.

Je sais pas si tu est aller voir, mais je suis quand même aller vérifier par moi même, et effectivement les touches ne change pas.

2021-04-26 14:44 UTC, osuShiro approved these changes

2021-04-26 14:44 UTC, merged