[ID] Add "Full combo", "Combo multiple effect", "Slidertails"
ppy/osu-wiki pull request #5242
Opened 2021-04-10 14:57 UTC by mousesalt

Add Indonesian [Full combo](https://osu.ppy.sh/wiki/en/Full_combo), [Combo multiple effect](https://osu.ppy.sh/wiki/en/Glossary/Combo_multiplier_effect), [Slidertails](https://osu.ppy.sh/wiki/en/Hit_object/Slidertail)

2021-04-14 18:12 UTC, Nivalyx commented on wiki/Glossary/Combo_multiplier_effect/id.md
> +**Efek pengganda kombo** adalah sebuah bug di dalam [scoreV1](/wiki/Score/ScoreV1) yang mana [skor](/wiki/Score) diizinkan untuk dihitung secara mundur. Ini adalah sebuah kecacatan *integer* (bilanga
the word "accounting" in the og article here doesn't literally translate to "akuntansi" orz D:

i'd say if any you can just delete the `,bukan pengubah akuntansi.` part of the sentence here

2021-04-14 18:12 UTC, Nivalyx commented on wiki/Full_combo/id.md
> +  - full kombo
might leave every instance of "full combo" untranslated here tbh, genuinely speaking i have never seen anyone referring to fc as `full kombo` or `kombo penuh` or the likes of it

2021-04-14 18:12 UTC, Nivalyx commented on wiki/Full_combo/id.md
> +**Full combo** (atau **Full kombo**, kependekannya adalah *FC*) merupakan istilah yang digunakan untuk menggambarkan pemain-pemain yang memperoleh kombo semaksimal mungkin pada suatu [beatmap](/wiki/
`**Full combo** (atau yang umum disingkat sebagai *FC*) merupakan istilah yang...`

2021-04-14 18:12 UTC, Nivalyx commented on wiki/Glossary/Combo_multiplier_effect/id.md
> +Efek pengganda kombo terjadi pada [osu!standard](/wiki/Game_mode/osu!), [osu!taiko](/wiki/Game_mode/osu!taiko), dan [osu!catch](/wiki/Game_mode/osu!catch) saja. Ini disebabkan karena mode permainan t
would suggest `dari arus pemain` to be deleted altogether for sentence cohesion

also the words `broken combo` here are actually something that was derived from the term `combobreak` and doesn't literally translate into `kombo yang pecah` or the likes of it; for the second sentence, you can consider sth like `Dengan kata lain, seorang pemain yang memperoleh [full combo (FC)](/wiki/Glossary#fc) akan mendapatkan skor yang lebih tinggi daripada pemain lainnya yang memainkan beatmap yang sama tanpa rangkaian kombo yang sempurna.`

2021-04-15 18:29 UTC, DoryanR requested changes

2021-04-15 18:29 UTC, DoryanR commented on wiki/Full_combo/id.md
> +Dikarenakan [efek pengganda combo](/wiki/Glossary/Combo_multiplier_effect), full combo akan memberikan [skor](/wiki/Score) paling banyak di dalam [mode permainan](/wiki/Game_mode) [osu!standard](/wik
```suggestion
Dikarenakan [efek pengganda combo](/wiki/Glossary/Combo_multiplier_effect), full combo akan memberikan [skor](/wiki/Score) paling banyak di dalam [mode permainan](/wiki/Game_mode) [osu!](/wiki/Game_mode/osu!), [osu!taiko](/wiki/Game_mode/osu!taiko), dan [osu!catch](/wiki/Game_mode/osu!catch).
```

2021-04-15 18:29 UTC, DoryanR commented on wiki/Glossary/Combo_multiplier_effect/id.md
> +Efek pengganda kombo terjadi pada [osu!standard](/wiki/Game_mode/osu!), [osu!taiko](/wiki/Game_mode/osu!taiko), dan [osu!catch](/wiki/Game_mode/osu!catch) saja. Ini disebabkan karena mode permainan t
```suggestion
Efek pengganda kombo terjadi pada [osu!](/wiki/Game_mode/osu!), [osu!taiko](/wiki/Game_mode/osu!taiko), dan [osu!catch](/wiki/Game_mode/osu!catch) saja. Ini disebabkan karena mode permainan tersebut menggunakan [kombo](/wiki/Glossary/kombo_(score_multiplier)) dari sebagai bagian dari perhitungan skor. Dengan kata lain, seorang pemain yang memperoleh [full combo (FC)](/wiki/Glossary#fc) lebih tinggi daripada pemain lainnya pada beatmap yang sama akan mendapatkan skor yang lebih tinggi tanpa rangkaian kombo yang sempurna.
```

2021-04-15 18:29 UTC, DoryanR commented on wiki/Hit_object/Slidertail/id.md
> +*Slidertail* atau **sliderend**, atau yang umum dirujuk sebagai *akhir slider*, merupakan suatu bagian dari [slider](/wiki/Hit_object/Slider) yang mengharuskan pemain untuk melepaskan tombol setelah
```suggestion
*Slidertail* atau **sliderend**, atau yang umum dirujuk sebagai *akhir slider*, merupakan suatu bagian dari [slider](/wiki/Hit_object/Slider) yang mengharuskan pemain untuk melepaskan tombol setelah mengikuti sebuah [sliderbody](/wiki/Hit_object/Sliderbody). Slidertail hanya bisa ditemukan di dalam [beatmap](/wiki/Beatmap) [osu!](/wiki/Game_mode/osu!). Slidertail bisa juga dilihat secara penuh sebagai sebuah circle atau tidak dapat dilihat sebagai bagian dari sliderbody, tergantung pada versi skin yang kamu gunakan. Warna dari slidertail ditentukan dari warna kombo yang digunakan oleh mapper pada beatmap mereka.
```

2021-04-16 08:41 UTC, Nivalyx commented
should be alright for me 👍

2021-04-16 08:41 UTC, Nivalyx approved these changes

2021-04-16 13:21 UTC, TicClick approved these changes

2021-04-16 13:21 UTC, merged