[RU] Add "Beatmap/Genre & Language"
ppy/osu-wiki pull request #5273
Opened 2021-04-18 21:08 UTC by TicClick

2021-04-18 21:33 UTC, UristMcKobold requested changes
А ещё у тебя из жанров пропала строчка с Аниме.

2021-04-18 21:33 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +| Unspecified | Этот жанр ни к чему не относится и используется в качестве заглушки. |
```suggestion
| Unspecified | Этот жанр ни к чему не относится и используется в качестве временной меры, пока не поставят другой. |
```
Плейсхолдер в виде «заглушки» совсем не нравится, передаёт другой смысл. Да и вообще человек вряд ли поймёт, что тут имеется в виду.

2021-04-18 21:33 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +| Video Game | Музыкальное сопровождение игр (вне зависимости от того, самостоятельная это песня или нет), а также различные ремиксы и аранжировки подобных композиций. |
```suggestion
| Video Game | Музыка из игр (вне зависимости от того, самостоятельная это песня или нет), а также различные ремиксы и аранжировки подобных композиций. |
```
«сопровождение игр» навевает мысли о том, что это что-то фоновое. И в целом «музыкальное сопровождение игр» слишком официально звучит, можно куда проще выразиться.

2021-04-18 21:33 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +| Pop | [Развлекательная музыка](https://ru.wikipedia.org/wiki/Поп-музыка "Wikipedia"). Признаки: относительно простая инструментальная часть, ритмичность, ориентировка на вокал, лёгкость восприятия.
Зачем тут переводить «поп-музыка» и вообще кидать ссылку на википедию? «Развлекательная музыка» выглядит лишним. Абсолютно все прекрасно понимают, что такое поп-музыка.

2021-04-18 21:33 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +| Novelty | Комичные или необычные песни. В osu! сюда попадают, к примеру, различные [мэшапы](https://ru.wikipedia.org/wiki/Мэшап_(музыка) "Wikipedia") и музыка из рекламы. |
Не нравится, что ты убрал из оригинала ютуб пупы (которые очень близки и рунету), никонико и мемную музыку (тут пояснений не нужно), но добавил музыку из рекламы(?!) и мэшапы, которые часто записывают в электронный жанр.

2021-04-19 20:55 UTC, TicClick commented on wiki/Beatmap/Genre_and_language/ru.md
> +| Pop | [Развлекательная музыка](https://ru.wikipedia.org/wiki/Поп-музыка "Wikipedia"). Признаки: относительно простая инструментальная часть, ритмичность, ориентировка на вокал, лёгкость восприятия.
потому что цель — это не написать `| Pop | Поп-музыка. <...> |`, а дать краткую характеристику, и это не перевод, а полусправочный кусок

2021-04-19 20:55 UTC, TicClick commented on wiki/Beatmap/Genre_and_language/ru.md
> +| Novelty | Комичные или необычные песни. В osu! сюда попадают, к примеру, различные [мэшапы](https://ru.wikipedia.org/wiki/Мэшап_(музыка) "Wikipedia") и музыка из рекламы. |
я открыл список карт в категории и посмотрел, что туда отправляют

2021-04-20 20:41 UTC, UristMcKobold requested changes

2021-04-20 20:41 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +**Жанр** и **язык исполнения** песни — поля с метаданными<!-- TODO: link -->, которые можно заполнить после публикации [карты](/wiki/Beatmap). Искать по ним можно через веб-сайт и в osu!lazer<!-- TOD
```suggestion
**Жанр** и **язык** песни — поля с метаданными<!-- TODO: link -->, которые можно заполнить после публикации [карты](/wiki/Beatmap). Искать по ним можно через веб-сайт и в osu!lazer<!-- TODO: link me --> (но не в стабильной версии osu!).
```
Я не уверен, что тут нужно уточнять, что язык *исполнения* по двум причинам. Во-первых, и так в общем-то понятно, что язык песни — это язык, на котором исполняется песня. Во-вторых, на самом деле не всегда язык карты — это язык именно исполнения. К примеру, в песне могут быть сэмплы на каком-нибудь языке, а также просто речь какая-то, которая будет относиться к песне, но не будет являться исполнением песни.
А ещё довольно топорно звучит «язык исполнения», как-то не по-русски.

2021-04-20 20:41 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +Фильтры по языку исполнения и жанру в [списке карт](https://osu.ppy.sh/beatmapsets) скрыты за надписью `More Search Options`.
```suggestion
Фильтры по языку и жанру в [списке карт](https://osu.ppy.sh/beatmapsets) скрыты за надписью `More Search Options`.
```

2021-04-20 20:41 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +Чтобы поменять у карты жанр или язык исполнения, откройте страницу карты и наведите курсор на область со словами `Genre` и `Language`. При наличии прав доступа там появится иконка карандаша, на котор
```suggestion
Чтобы поменять у карты жанр или язык, откройте страницу карты и наведите курсор на область со словами `Genre` и `Language`. При наличии прав доступа там появится иконка карандаша, на которую нужно нажать. Возможность редактирования зависит от [групп](/wiki/People/The_Team#группы-пользователей), в которых вы состоите, и от [категории](/wiki/Beatmap/Category#существующие-категории) карты:
```

2021-04-20 20:41 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +# Жанр и язык исполнения
```suggestion
# Жанр и язык
```

2021-04-20 20:41 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +Если у карты не выбраны жанр или язык исполнения (вместо них стоит `Unspecified`), её нельзя номинировать<!-- TODO: link -->.
```suggestion
Если у карты не выбраны жанр или язык (вместо них стоит `Unspecified`), её нельзя номинировать<!-- TODO: link -->.
```

2021-04-20 20:41 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +| Anime | Музыка из какого-нибудь аниме (не обязательно для него написанная). |
```suggestion
| Anime | Музыка из аниме (не обязательно для него написанная). |
```
«какого-нибудь» тут звучит слишком разговорно, язык у статьи сравнительно серьёзный.

2021-04-20 21:42 UTC, TicClick commented on wiki/Beatmap/Genre_and_language/ru.md
> +**Жанр** и **язык исполнения** песни — поля с метаданными<!-- TODO: link -->, которые можно заполнить после публикации [карты](/wiki/Beatmap). Искать по ним можно через веб-сайт и в osu!lazer<!-- TOD
второй пункт я обобщаю, подразумевая, что сэмпл и так является частью песни. с первым соглашусь

2021-04-20 21:44 UTC, UristMcKobold requested changes

2021-04-20 21:44 UTC, UristMcKobold commented on wiki/Beatmap/Genre_and_language/ru.md
> +- Other (если языка песни нет в списке, либо если она исполнена на двух и более языках)
```suggestion
- Other (если языка нет в списке, либо если она исполнена на двух и более языках)
```
Два раза повторяется «язык» в предложении, плюс называется этот список «список языков» просто.

2021-04-20 21:48 UTC, UristMcKobold approved these changes

2021-04-21 13:21 UTC, osuShiro approved these changes

2021-04-21 13:21 UTC, merged