[TH] Add "Ouendan", "Twitter" and update "Bancho (server)"
ppy/osu-wiki pull request #5290
Opened 2021-04-21 04:14 UTC by HelloYeew

Add Thai translation for

- Ouendan
- Twitter

and update translation that outdated for

- Bancho (server)

2021-04-24 11:33 UTC, Trigonoculus requested changes
👍 suggest แก้นิดเดียวครับ

2021-04-24 11:33 UTC, Trigonoculus commented on wiki/Bancho_(server)/th.md
> +*สำหรับการใช้งานอื่นๆ ดู [Bancho (คำคลุมเครือ)](/wiki/Disambiguation/Bancho)*
```suggestion
*สำหรับการใช้งานอื่น ๆ ดู [Bancho (คำคลุมเครือ)](/wiki/Disambiguation/Bancho)*
```

2021-04-24 11:33 UTC, Trigonoculus commented on wiki/Bancho_(server)/th.md
> +**osu!bancho** เป็นเซิฟเวอร์ที่ใช้จัดการสถานะผู้ใช้, แชท และ บริการผู้เล่นหลายคน
```suggestion
**osu!bancho** คือเซิฟเวอร์ที่ใช้จัดการสถานะผู้ใช้, แชท และ บริการผู้เล่นหลายคน
```

2021-04-24 11:33 UTC, Trigonoculus commented on wiki/Ouendan/th.md
> +- ในวัฒนธรรมญี่ปุ่นเป็นกลุ่มเชียร์คล้ายๆในวัฒนธรรมตะวันตกคือการให้กำลังใจทีมกีฬาโดยการใช้กลอง แตร ป้าย และเสียงเชียร์ <!-- I try not to change a meaning and make it easier to read.-->
```suggestion
- ในวัฒนธรรมญี่ปุ่น เป็นกลุ่มเชียร์คล้าย ๆ ในวัฒนธรรมตะวันตก คือการให้กำลังใจทีมกีฬาโดยการใช้กลอง แตร ป้าย และเสียงเชียร์ <!-- I try not to change a meaning and make it easier to read.-->
```

2021-04-24 16:14 UTC, HelloYeew commented
Complete 👍

2021-04-25 16:04 UTC, Trigonoculus approved these changes
Looks good to me

2021-04-25 16:19 UTC, C0NS03L approved these changes

2021-05-11 15:08 UTC, TicClick approved these changes

2021-05-11 15:08 UTC, merged