[ID] Update "How you can help!"
ppy/osu-wiki pull request #5334
Opened 2021-04-28 08:21 UTC by mousesalt

2021-05-03 10:38 UTC, wowcake requested changes

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +osu! memiliki komunitas yang sangat dinamis yang terdiri dari orang-orang dari seluruh dunia. Dan siapa pun dapat menjadi bagian dari komunitas dengan caranya sendiri!
```suggestion
osu! memiliki komunitas yang sangat dinamis yang terdiri dari orang-orang dari seluruh dunia. Dan siapa pun dapat menjadi bagian dari komunitas itu dengan caranya sendiri!
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +## Membantu wiki
```suggestion
## Membantu dalam wiki
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +[Wiki](https://github.com/ppy/osu-wiki) adalah basis pengetahuan resmi kami yang berisi apa saja dan segalanya tentang osu!. Oleh karena itu, wiki selalu mencari lebih banyak kontributor untuk memban
```suggestion
[Wiki](https://github.com/ppy/osu-wiki) adalah basis pengetahuan resmi kami yang berisi apa saja dan segalanya tentang osu!. Oleh karena itu, wiki selalu membutuhkan lebih banyak kontributor untuk membantu menjaga situs tetap mutakhir dengan pengetahuan maupun terjemahan yang baru dan segar.
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +- Jika Kamu melihat sesuatu terjadi yang tidak pantas atau mengganggu, gunakan perintah `!report` dalam obrolan dalam gim untuk memberi tahu moderator.
```suggestion
- Jika Kamu melihat sesuatu yang tidak pantas atau mengganggu terjadi, gunakan perintah `!report` dalam obrolan dalam gim untuk memberi tahu moderator.
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +Jika Kamu menemui seseorang yang memiliki masalah mengenai gim, bantulah mereka! Apakah itu masalah pada driver, pertanyaan beatmap, atau pertanyaan gameplay, jika Kamu dapat menjawabnya, Kamu dapat
```suggestion
Jika Kamu menemui seseorang yang memiliki masalah dengan osu!, bantulah mereka! Apakah itu masalah pada driver, pertanyaan beatmap, atau pertanyaan gameplay, jika Kamu dapat menjawabnya, Kamu dapat membantu orang tersebut memecahkan masalah mereka.
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +Secara garis besar, berikut ini beberapa cara Kamu dapat membantu orang lain:
```suggestion
Secara garis besar, berikut ini adalah beberapa cara Kamu dapat membantu orang lain:
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +- Ikuti utas baru apa pun, baca masing-masing utas dan bantu bila Kamu bisa; Kamu dapat menggunakan *unread icon* untuk memastikan Kamu mengikuti.
```suggestion
- Ikuti thread-thread yang terbaru, baca masing-masing thread itu dan bantu bila Kamu bisa; Kamu dapat menggunakan *unread icon* untuk memastikan Kamu mengikutinya.
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +- Baca [panduan](/wiki/Guides) yang tersedia untuk menyempurnakan pengetahuan osu!. Jika menurutmu panduan tidak memuaskan, maka Kamu dapat mencoba berkontribusi untuk mereka!
```suggestion
- Baca [panduan](/wiki/Guides) yang tersedia untuk menyempurnakan pengetahuan osu!. Jika menurutmu panduan tersebut tidak memuaskan, maka Kamu dapat mencoba berkontribusi pada panduan itu!
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +osu! memiliki tim peninjau yang berdedikasi untuk memeriksa apakah beatmap-beatmap siap untuk dipindahkan ke bagian peringkat dan dimainkan oleh semua orang. Kamu juga dapat itu berkontribusi di sekt
```suggestion
osu! memiliki tim peninjau yang berdedikasi untuk memeriksa apakah beatmap-beatmap siap untuk dipindahkan ke bagian peringkat dan dimainkan oleh semua orang. Kamu juga dapat ikut berkontribusi di sektor ini:
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +- Mainkan beatmap [Pending atau Work-in-progress](/wiki/Beatmap/Category#work-in-progress-and-pending) dan tinggalkan umpan balik di utas diskusi beatmap.
```suggestion
- Mainkan beatmap [Pending atau Work-in-progress](/wiki/Beatmap/Category#work-in-progress-and-pending) dan tinggalkan umpan balik di thread diskusi beatmap.
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +- jika Kamu punya waktu dan dedikasi untuk gim, buat sebuah utas [Modding Queue](https://osu.ppy.sh/community/forums/60) untuk memberikan tempat kepada pembuat beatmap meminta mod dari Kamu.
```suggestion
- Jika Kamu punya waktu dan dedikasi untuk gim, cobalah membuat sebuah [Modding Queue](https://osu.ppy.sh/community/forums/60) thread untuk memberikan tempat bagi para pembuat beatmap meminta mod dari Kamu.
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +- Jelajahi forum [Turnaments](https://osu.ppy.sh/community/forums/55). Turnamen membutuhkan banyak waktu dan pekerjaan untuk dapat diatur tanpa hambatan, dan Kamu dapat membantu dengan menjadi juri p
```suggestion
- Jelajahi forum [Turnamen](https://osu.ppy.sh/community/forums/55). Turnamen membutuhkan banyak waktu dan pekerjaan untuk dapat diatur tanpa hambatan, dan Kamu dapat membantu dengan menjadi juri penonton dalam beberapa kasus.
```

2021-05-03 10:38 UTC, wowcake commented on wiki/How_you_can_help!/id.md
> +- Jangan mengeluhkan jika terdapat pemain yang melakukan kecurangan. [Laporkan saja dan lanjutkan harimu](/wiki/Reporting_Bad_Behaviour/Handling_Foul_Play), sederhananya menggunakan perintah `!report
```suggestion
- Jangan mengeluh tentang pemain yang melakukan kecurangan. [Laporkan saja mereka dan lanjutkan harimu](/wiki/Reporting_Bad_Behaviour/Handling_Foul_Play), sederhananya menggunakan perintah `!report <username> sepertinya melakukan kecurangan` dapat memperbaiki masalah Kamu dalam beberapa menit hingga jam.
```

2021-05-03 14:10 UTC, mousesalt commented on wiki/How_you_can_help!/id.md
> +- Jelajahi forum [Turnaments](https://osu.ppy.sh/community/forums/55). Turnamen membutuhkan banyak waktu dan pekerjaan untuk dapat diatur tanpa hambatan, dan Kamu dapat membantu dengan menjadi juri p
i will keep this same to main web page

2021-05-11 14:13 UTC, ZeroPyrozen requested changes

2021-05-11 14:13 UTC, ZeroPyrozen commented on wiki/How_you_can_help!/id.md
> +- Jika Kamu punya waktu dan dedikasi untuk osu!, cobalah membuat sebuah utas [Modding Queue](https://osu.ppy.sh/community/forums/60) untuk memberikan tempat bagi para pembuat beatmap meminta mod dari
```suggestion
- Jika Anda punya waktu dan dedikasi untuk osu!, cobalah membuat sebuah utas [Modding Queue](https://osu.ppy.sh/community/forums/60) untuk memberikan tempat bagi para pembuat beatmap meminta mod dari Anda.
```

2021-05-11 14:13 UTC, ZeroPyrozen commented on wiki/How_you_can_help!/id.md
> +osu! memiliki komunitas teknis dan kompetitif yang berkembang pesat. Mulai dari penggemar, hobi, hingga veteran berpengalaman rhythm gim. Ada banyak proposal dan proyek yang dibuat khusus untuk osu!
```suggestion
osu! memiliki komunitas teknis dan kompetitif yang berkembang pesat. Mulai dari penggemar, hobi, hingga veteran berpengalaman gim ritme. Ada banyak proposal dan proyek yang dibuat khusus untuk osu! dan Anda dapat membantu mereka, atau mendorong masa depan osu! dengan proposal/proyek Anda sendiri!
```

2021-05-11 14:13 UTC, ZeroPyrozen commented on wiki/How_you_can_help!/id.md
> +- Jelajahi forum [Turnaments](https://osu.ppy.sh/community/forums/55). Turnamen membutuhkan banyak waktu dan pekerjaan untuk dapat diatur tanpa hambatan, dan Kamu dapat membantu dengan menjadi juri p
```suggestion
- Jelajahi forum [Turnaments](https://osu.ppy.sh/community/forums/55). Turnamen membutuhkan banyak waktu dan pekerjaan untuk dapat diatur tanpa hambatan, dan Anda dapat membantu dengan menjadi juri penonton dalam beberapa kasus.
```

2021-05-11 15:36 UTC, ZeroPyrozen approved these changes
All good 👍

2021-05-11 15:52 UTC, TicClick approved these changes

2021-05-11 15:52 UTC, merged