[RU] Add "Rules/Explicit Content"
ppy/osu-wiki pull request #5335
Opened 2021-04-28 09:49 UTC by GoodbyeShin

add ru.md and RU translation of the article

2021-04-28 10:21 UTC, HibanaSama commented on wiki/Rules/Explicit_Content/ru.md
> +![Screenshot of a beatmap that contains explicit content](img/explicit-tag.jpg "Пример карты, отмеченной «откровенным» тегом.")
```
![Screenshot of a beatmap that contains explicit content]
```
вот это, кажется, должно быть переведено

2021-05-31 22:22 UTC, TicClick commented
sorry for setting you back, I have a partially complete review which I hope to finish in a day or so

2021-06-13 21:43 UTC, TicClick requested changes
еле домучал

2021-06-13 21:43 UTC, TicClick commented on wiki/Rules/Explicit_Content/ru.md
> +Сюда также относится подробное и продолжительное обсуждение проблемных тем или чего-либо ещё, что разумный человек сочтёт "чрезмерным". Некоторые примеры (но не все):
опять слишком расплывчиво, ну

2021-06-13 21:43 UTC, TicClick commented on wiki/Rules/Explicit_Content/ru.md
> +Хороший способ определить, следует ли что-то помечать «откровенным» тегом или нет, — подсмотреть, как классифицируют какие-то конкретные треки на крупных стриминговых сервисах потокового аудио. Spoti
ссылку потерял, ну и второе предложение плохо клеится к первому

2021-07-16 17:58 UTC, TicClick commented
как дела?

2021-07-19 14:28 UTC, GoodbyeShin commented
> как дела?

Sorry for the huge delay, this month's been kinda crazy.

2021-08-03 14:15 UTC, TicClick requested changes
как-то так, это я сам применю

2021-08-03 14:15 UTC, TicClick commented on wiki/Rules/Explicit_Content/ru.md
> +Если карта загружена на сайт osu!, можно указать наличие в ней откровенного содержания, поставив флажок в настройках её языка и жанра.
```suggestion
Если карта загружена на сайт osu!, можно указать наличие в ней откровенного содержания, поставив в настройках её языка и жанра соответствующий флажок.
```

2021-08-03 14:15 UTC, TicClick commented on wiki/Rules/Explicit_Content/ru.md
> +С появлением нового тега «Откровенное содержание» большинство музыки теперь можно использовать. Основные условия — наличие соответствующих тегов и отсутствие грубых нарушений данных правил.
```suggestion
С появлением нового тега «Откровенное содержание» большинство музыки теперь можно использовать для маппинга. Основные условия — наличие соответствующих тегов и отсутствие грубых нарушений данных правил.
```

2021-08-03 14:15 UTC, TicClick commented on wiki/Rules/Explicit_Content/ru.md
> +Также сюда относится всё, что разумный человек счёл бы "чрезмерным", например, подробное обсуждение на спорную тематику. Некоторые (но не все) примеры:
```suggestion
Также сюда относится всё, что разумный человек счёл бы чрезмерным, например, подробное обсуждение спорной тематики. Некоторые примеры:
```

2021-08-03 14:15 UTC, TicClick commented on wiki/Rules/Explicit_Content/ru.md
> +Хороший способ определить, следует ли что-то помечать «откровенным» тегом или нет, — подсмотреть, как классифицируют какие-то конкретные треки на крупных стриминговых сервисах потокового аудио. Загля
```suggestion
Хороший способ определить, следует ли что-то помечать «откровенным» тегом или нет, — подсмотреть, как классифицируют какие-то конкретные треки на крупных стриминговых сервисах потокового аудио, например, [Spotify](https://www.spotify.com "Spotify").
```

2021-08-03 14:16 UTC, TicClick approved these changes
please hit me up on Discord if I don't respond for an arbitrarily long period of time, I'm not on good terms with GitHub's notifications system

2021-08-03 14:17 UTC, merged