[RU] Update osu! Program Files
ppy/osu-wiki pull request #5342
Opened 2021-04-29 17:01 UTC by HibanaSama

2021-05-18 18:32 UTC, TicClick requested changes
плохо, но терпимо (можно довести до нужного состояния)

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +В папке Replays хранятся файлы реплеев игрока. Файл реплея не работает, когда связанные с ним карты отсутствуют. Реплей содержит результаты игрока, а также оживляет движения курсора игрока во время в
прямой перевод — зло

```suggestion
В папке Replays находятся файлы реплеев, сохранённые пользователем. Их можно воспроизвести только при наличии карт, использовавшихся для записи. В каждом реплее содержится итоговая статистика игры, а также движения курсора и нажатия клавиш. Чтобы создать реплей, нажмите `F2` на экране с результатами или кликните по кнопке «Сохранить реплей» (есть только в одиночном режиме).
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +*Игрокам, которые хотят загрузить свои реплеи на YouTube, см.: [публичный релиз Osr2mp4. Автоматическая конвертация файла с реплеем в видео.](https://osu.ppy.sh/community/forums/topics/1104243)*
```suggestion
*Примечание: для загрузки реплеев на YouTube может пригодиться [Osr2mp4: автоматическая конвертация реплея в видео](https://osu.ppy.sh/community/forums/topics/1104243).*
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Структура имени файла: `{Никнейм локального игрока} - {Исполнитель} - {Название} {[Сложность]}{(ГГГГ-ММ-ДД)} {Игровой режим}`. Ниже показан пример этого:
```suggestion
Названия реплеев имеют формат `{ник игрока} - {исполнитель песни} - {название песни} {[сложность]}{(ГГГГ-ММ-ДД)} {режим игры}`. Пример:
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +В папке Screenshots хранятся скриншоты, созданные игроком в osu!. По умолчанию скриншот сохраняется в расширении файла `.jpg`, однако его можно изменить на `.png` в настройках.
```suggestion
В папке Screenshots хранятся скриншоты, сделанные игроком. По умолчанию скриншоты имеют расширение `.jpg`, однако его можно изменить на `.png` в настройках клиента.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +*Заметка: чтобы сделать скриншот, нажмите клавишу скриншота (по умолчанию F12).*
```suggestion
*Примечание: чтобы сделать скриншот, нажмите горячую клавишу (`F12` по умолчанию).*
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Структура имени файла: `screenshot###`, где "###" — номер скриншота.
```suggestion
Названия скриншотов имеют формат `screenshot###`, где "###" — номер скриншота.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +В папке Skins хранятся скины, созданные игроками, которые можно использовать для изменения игрового интерфейса. Игроки могут скачать скины с [подфорума скинов](https://osu.ppy.sh/community/forums/15)
```suggestion
В папке Skins хранятся скины, созданные другими игроками и предназначенные для смены оформления клиента. Их можно скачать из [соответствующего форума](https://osu.ppy.sh/community/forums/15) и установить, кликнув два раза по скачанному скину в файловом менеджере. «osu! by peppy» — единственный скин, у которого нет отдельной папки и который нельзя удалить.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +*Предупреждение: будьте осторожны с этими файлами. Вы можете сломать osu!, если не будете осторожны.*
кажется, это вообще тут не к месту, я удалю потом из оригинала
```suggestion
*Предупреждение: будьте осторожны с этими файлами. Вы можете сломать osu!, если не будете осторожны.*
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +В папке Songs хранятся пользовательские карты osu!. Папка с картой обычно содержит: `.osu` (сложности), `.mp3`/`.ogg` (аудиофайлы), `.jpg`/`.png`/`.gif` (фоновые изображения), `.osb` (файлы со сториб
```suggestion
В папке Songs хранятся карты для osu!. В каждой из них обычно находятся файлы форматов `.osu` (сложности), `.mp3`/`.ogg` (аудиофайлы), `.jpg`/`.png`/`.gif` (фоновые изображения), `.osb` (файлы со сторибордом) и `.mp4`/`.flv` (видеофайлы). Карта также может содержать `.wav`/`.ogg` (файлы с хитсаундами) и другие вложенные папки (например, со скином или спрайтами для сториборда).
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +**Пример:** [57950 SOUND HOLIC - Drive My Life](https://osu.ppy.sh/beatmapsets/57950)
```suggestion
Имена папок имеют формат `{номер карты} {исполнитель} - {название песни}`. Пример: [57950 SOUND HOLIC - Drive My Life](https://osu.ppy.sh/beatmapsets/57950).
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Обратите внимание, что очень старые карты (например, [Kenji Ninuma - DISCO PRINCE](https://osu.ppy.sh/beatmapsets/1) или [Dudelstudios - Angry Video Game Nerd Theme [MATURE CONTENT]](https://osu.ppy.
```suggestion
Обратите внимание, что если карта сделана очень давно (например, [Kenji Ninuma - DISCO PRINCE](https://osu.ppy.sh/beatmapsets/1) или [Dudelstudios - Angry Video Game Nerd Theme [MATURE CONTENT]](https://osu.ppy.sh/beatmapsets/66)) или в принципе не опубликована, имя её папки не будет соответствовать этому формату.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Файлы данных osu!. Содержат некоторый кэш osu!, такие как кэши фоновых изображений карты и аватаров.
```suggestion
Файлы данных osu!. Содержат кэшированные данные, например, фоновые изображения карт и аватарки других игроков.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +*Предупреждение: будьте осторожны с этими файлами. Вы можете сломать osu!, если не будете осторожны.*
```suggestion
*Предупреждение: изменение этих файлов может помешать корректной работе osu! или привести к потере ваших локальных данных.*
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Файлы базы данных — базы данных, которые требуются osu!, чтобы правильно работать. В файлах содержатся важная информация, которая требуется osu!, например: сохранённые скоры и кэшированный список кар
использую это замечание, чтобы отметить тошнотно-тавтологически низкое качество оригинала
```suggestion
В файлах формата `.db` хранятся базы данных, необходимые для работы osu!. К примеру, в них записаны копии рекордов игрока и список доступных карт.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +- `scores.db`: хранит локальные таблицы рекордов.
```suggestion
- `collections.db`: внутриигровые коллекции карт;
- `osu!.db`: база данных карт osu!;
- `presence.db`: кэш для пользователей, зашедших в чат;
- `scores.db`: локальные таблицы рекордов.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +## .cfg (Файлы конфигурации)
```suggestion
## .cfg (файлы настроек)
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Файлы конфигурации настраивают начальные параметры для работы osu!. Эти файлы можно открыть с помощью текстового редактора.
```suggestion
Файлы настроек содержат параметры, влияющие на работу osu!. Их можно открыть с помощью текстового редактора.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +- `osu!.<имя пользователя в операционной системе>.cfg`: хранит данные [настроек](/wiki/Options) и другие игровые настройки. См. [Файл конфигурации](/wiki/osu!_Program_Files/User_Configuration_File).
какой-то трэш, перепишу потом
```suggestion
- `osu!.cfg`: информация о файлах osu! и текущей ветке обновлений. Этот файл никогда не стоит редактировать.
- `osu!.<имя пользователя в операционной системе>.cfg`: хранит [настройки](/wiki/Options) osu!. Подробнее: [Файл конфигурации](/wiki/osu!_Program_Files/User_Configuration_File).
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Главный компонент. Кликните по нему для запуска (работает только на Windows). Файлы .exe можно безопасно открывать, если игрок для установки osu! использовал установщик osu!, скачанный с официального
```suggestion
Главный компонент osu!. Дважды кликните по такому файлу, чтобы запустить игру (работает только на Windows). Запуск `.exe` — безопасная операция, если установщик osu! был скачан с официального сайта игры.
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +#### .dll (Расширения приложения)
```suggestion
#### .dll (динамические библиотеки)
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +### .exe (Приложение)
```suggestion
### .exe (приложение)
```

2021-05-18 18:32 UTC, TicClick commented on wiki/osu!_Program_Files/ru.md
> +Файлы .dll — зависимости и компоненты osu!.
```suggestion
Файлы формата `.dll` — это зависимости и компоненты osu!.
```

2021-05-20 19:45 UTC, HibanaSama commented on wiki/osu!_Program_Files/ru.md
> +### Localisation
тут нет ошибки, а вот в оригинале есть
<details>

![Screenshot 2021-05-21 at 00 26 23](https://user-images.githubusercontent.com/48864283/119039028-3dba8400-b9cd-11eb-9a48-2bb81792f7ff.png)

</details>

2021-05-20 19:48 UTC, HibanaSama commented on wiki/osu!_Program_Files/ru.md
> +Папка Exports появляется, когда игрок использует опцию [«Экспортировать в .osk» в меню выбора скинов](/wiki/Options) или [«Экспортировать в .osz» в редакторе карт](/wiki/Beatmap_Editor/Menu). В ней б
есть переводы этих пунктов
<details>

![Screenshot 2021-05-21 at 00 32 09](https://user-images.githubusercontent.com/48864283/119039858-292abb80-b9ce-11eb-93d5-ec463c5c3168.png)
![Screenshot 2021-05-21 at 00 31 50](https://user-images.githubusercontent.com/48864283/119039866-2b8d1580-b9ce-11eb-8174-e96de60088f1.png)

</details>

2021-05-20 20:05 UTC, HibanaSama commented on wiki/osu!_Program_Files/ru.md
> +Папка Chat появляется только в том случае, когда у игрока в настройках включен параметр «Вести логи личных сообщений» или если игрок выполнит команду `/savelog` в [окне чата](/wiki/Chat_Console).
изменил на опцию

2021-05-21 15:48 UTC, TicClick approved these changes

2021-05-21 15:48 UTC, merged