Fix syntax errors on osu!weekly #95–#99, 103
ppy/osu-wiki pull request #5346
Opened 2021-04-30 20:32 UTC by MilkyIQ

Fixes the header syntax errors as described in [this message (Discord)](https://discord.com/channels/188630481301012481/218677502141399041/837767574161850378) as well as a forgetton forward slash on osu!weekly #103

Apologies in advance if I messed anything up, I'm not extremely well versed in HTML or CSS

2021-04-30 20:39 UTC, Joehuu commented
Is there a reason not to convert these headings to markdown?

2021-04-30 20:40 UTC, MilkyIQ commented
No there isn't. Probably should've done that in the first place

2021-04-30 20:40 UTC, TPGPL commented on news/2017-03-09-osuweekly-95.md
> +<h2 name="news" id="news" class="osu-md__header osu-md__header--2">Weekly news</h2>
couldnt it be 
d
```suggestion
## <a id="news"></a>Weekly news
```

2021-04-30 20:43 UTC, bdach commented
There is a reason to not convert, and it's the table of contents in the aforementioned posts. Note that they use anchors, so the `id` in the `h2` tags is actually used to link to those headings.

As far as I can see osu-web does not autogenerate anchor names for markdown headings, so you'd have to remove the table of contents, if you want to convert, as it'd be useless.

2021-04-30 20:51 UTC, MilkyIQ commented
If there's no advantage to changing to markdown headers, then should we just leave that job up to a different pr? There are quite a few other newsposts that use this same method, if I'm not mistaken

2021-05-01 05:20 UTC, cl8n requested changes
use @TPGPL's suggestion for the headers, that's the standard workaround for it used in other news posts. also adding classnames to html like this is not good as they could change any time on osu-web

2021-05-01 05:20 UTC, cl8n commented on news/2017-03-17-osuweekly-96.md
> +[Ekoro](https://osu.ppy.sh/users/284905), currently participating in TWC 2017, is not just capable of whacking those drums. He pulled off a mindblowing EZFL 98.50% FC on [9mm Parabellum Bullet - Infe
```suggestion
[Ekoro](https://osu.ppy.sh/users/284905), currently participating in TWC 2017, is not just capable of whacking those drums. He pulled off a mindblowing EZFL 98.50% FC on [9mm Parabellum Bullet - Inferno](https://osu.ppy.sh/beatmapsets/482090#osu/1028733) on The Eclipse difficulty, giving him 385pp. Ekoro has been super capable in playing FL, and this score is nothing short of breathtaking.
```

2021-05-01 05:20 UTC, cl8n commented on news/2017-03-30-osuweekly-98.md
> +[WubWoofWolf](https://osu.ppy.sh/beatmapsets/405167#osu/941254) makes the SS rank feel like a joke to him as he pulled that out of [Kuroneko Dungeon - Ryoushi no Umi no Lindwurm](https://osu.ppy.sh/b
```suggestion
[WubWoofWolf](https://osu.ppy.sh/users/39828) makes the SS rank feel like a joke to him as he pulled that out of [Kuroneko Dungeon - Ryoushi no Umi no Lindwurm](https://osu.ppy.sh/beatmapsets/405167#osu/941254) on yf & Crystal's Extra with HDHR to gain 312pp. No one in the leaderboards are remotely close to him. See this flawless play for yourself!
```
copy and paste with care :^)

2021-05-01 05:27 UTC, cl8n commented
> As far as I can see osu-web does not autogenerate anchor names for markdown headings, so you'd have to remove the tables of contents, if you want to convert, as they'd be useless.

jsyk it's done on wiki but not news. I think it's because news has no contents sidebar

2021-05-01 21:15 UTC, cl8n approved these changes

2021-05-03 06:38 UTC, peppy approved these changes

2021-05-03 06:39 UTC, merged