Add o!BWC2021 Registrations Open newspost & update wiki article
ppy/osu-wiki pull request #5352
Opened 2021-05-01 23:11 UTC by zeusminus

*The third time is the charm!* 🗺️ 

- Add osu! Beatmapping World Championship 2021 Registrations Open newspost
- Update prizes, staff listing on the wiki
- Add judging criteria and a link to the official website to the wiki

2021-05-01 23:23 UTC, MilkyIQ reviewed
Some grammatical changes

2021-05-01 23:23 UTC, MilkyIQ commented on news/2021-05-02-osu-beatmapping-world-championship-2021-registrations-open.md
> +Once their Team Captain selects team members, each member will need to accept the invitation to join that team. Contest staff will later finalize the team creation once everyone accepts their invitat
```suggestion
Once their Team Captain selects team members, each member will need to accept the invitation to join that team. Contest staff will later finalise the team creation once everyone accepts their invitation and the team name is approved. Before that, Captains are free to change members and the team name.
```

2021-05-01 23:23 UTC, MilkyIQ commented on news/2021-05-02-osu-beatmapping-world-championship-2021-registrations-open.md
> +As mentioned above, only the highest-scoring team of a particular country will participate in the second round. Therefore, we will announce the results of the first round. However, the rest results w
```suggestion
As mentioned above, only the highest-scoring team of a particular country will participate in the second round. Therefore, we will announce the results of the first round. However, the rest of the results will be kept confidential and will only be announced after the conclusion of the final round, during our livestream. There will be no eliminations after the first round.
```

2021-05-01 23:23 UTC, MilkyIQ commented on news/2021-05-02-osu-beatmapping-world-championship-2021-registrations-open.md
> +Each round, teams will be awarded a certain amount of points by the judges evaluating their entries. Obviously, these hard-earned points will not go to waste! Behind the scenes, these points will be
```suggestion
Each round, teams will be awarded a certain amount of points by the judges evaluating their entries. Obviously, these hard-earned points will not go to waste! Behind the scenes, these points will be added up with one another in the leaderboard, and the grand total will determine the final placement of the respective team.
```

2021-05-01 23:23 UTC, MilkyIQ commented on news/2021-05-02-osu-beatmapping-world-championship-2021-registrations-open.md
> +If you'd recall, we were looking for judges, details of which can be found in [this newspost](https://osu.ppy.sh/home/news/2021-04-11-osu-beatmapping-world-championship-2021-call-for-judges). We have
```suggestion
If you recall, we were previously looking for judges, details of which can be found in [this newspost](https://osu.ppy.sh/home/news/2021-04-11-osu-beatmapping-world-championship-2021-call-for-judges). We have received dozens of applicants over the span of a few weeks, and for that, we would like to thank you for your interest! Unfortunately, we have closed the osu! mode judge applications for this edition as of today, so if you're a latecomer, try to make it earlier next year! For multi-mode judges (osu!taiko, osu!catch, and osu!mania), applications are still open! If you're interested, fill out the [application form](https://forms.gle/Yu2M2ZiwhapJYc7K7 "Google Forms") right away!
```
"we were" by itself just sounded a little awkward to me

2021-05-01 23:23 UTC, MilkyIQ commented on news/2021-05-02-osu-beatmapping-world-championship-2021-registrations-open.md
> +Done reading and looking for where to register? You're at the right place! If you want to take part as a contestant, all you need to do is to login our website!
```suggestion
Done reading and looking for where to register? You're at the right place! If you want to take part as a contestant, all you need to do is to log in to our website!
```

2021-05-02 10:03 UTC, Ephemeralis requested changes
some minor wording changes, otherwise looks ok

2021-05-02 10:03 UTC, Ephemeralis commented on news/2021-05-02-osu-beatmapping-world-championship-2021-registrations-open.md
> +If you recall, we were previously looking for judges, details of which can be found in [this newspost](https://osu.ppy.sh/home/news/2021-04-11-osu-beatmapping-world-championship-2021-call-for-judges)
```suggestion
If you recall, we were previously looking for judges, details of which can be found in [this newspost](https://osu.ppy.sh/home/news/2021-04-11-osu-beatmapping-world-championship-2021-call-for-judges). We have received dozens of applicants over the span of a few weeks, and for that, we would like to thank you for your interest.

We have closed the osu! mode judge applications for this edition as of today, so if you're a latecomer, try to make it earlier next year. For multi-mode judges (osu!taiko, osu!catch, and osu!mania), applications are still open - if you're interested, fill out the [application form](https://forms.gle/Yu2M2ZiwhapJYc7K7 "Google Forms") right away!
```

2021-05-02 14:07 UTC, Ephemeralis approved these changes

2021-05-02 14:08 UTC, merged