[FR] ASC/Formatting
ppy/osu-wiki pull request #5357
Opened 2021-05-02 09:26 UTC by DoryanR

Proposal for the French translation of the wiki page "Article styling criteria/Formatting".

2021-05-02 09:35 UTC, geshii requested changes

2021-05-02 09:35 UTC, geshii commented on wiki/Article_styling_criteria/Formatting/fr.md
> +| Maria | No Contest | Mocha |  |
Tu as oublié de traduire le tableau?

2021-05-02 09:35 UTC, geshii commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Lorsque vous créez un lien vers une beatmapset, utilisez ce format pour le texte du lien :
Pourquoi pas remplacer par "sets de beatmaps" ? idk

2021-05-02 09:35 UTC, geshii commented on wiki/Article_styling_criteria/Formatting/fr.md
> +### À puces
Listes à puces* non?

2021-05-02 09:35 UTC, geshii commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les traductions sont soumises à une stricte parité de contenu avec leur article anglais, en ce sens qu'elles doivent avoir le même message, indépendamment de la grammaire et de la syntaxe. Toute modi
> en ce sens qu'elles doivent avoir le même message

pourquoi pas "ce qui signifie qu'elles doivent..." ?

2021-05-02 09:35 UTC, geshii commented on wiki/Article_styling_criteria/Formatting/fr.md
> +| Nom du fichier | Nom en local | Écriture native |
Nom en local ? Ca fait pas très français je trouve. Pourquoi pas "Nom en Français?"

2021-05-02 10:10 UTC, DoryanR commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Lorsque vous créez un lien vers une beatmapset, utilisez ce format pour le texte du lien :
C'est le terme de base, je laisse comme tel donc

2021-05-02 10:10 UTC, DoryanR commented on wiki/Article_styling_criteria/Formatting/fr.md
> +### À puces
Je suit la logique avec en haut `Listes`, donc  je pense que c'est pas trop mal comme ça.

2021-05-02 10:11 UTC, geshii commented on wiki/Article_styling_criteria/Formatting/fr.md
> +### À puces
le "### À puces" fait bizarre après, non?

2021-05-02 10:15 UTC, DoryanR commented on wiki/Article_styling_criteria/Formatting/fr.md
> +### À puces
Pas tant que ça, vu que on a en section de niveau 2 `Listes`, et en niveau 3 on à `À puces`, `Numéroté`, `Mixte`, etc... Perso je trouve ça pas mal, et ça suit cette logique de hiérarchie avec les niveau de sections.

2021-05-02 10:41 UTC, Ganondorfosu requested changes

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +- les underscore (`_`)
```suggestion
- les traits de soulignement (`_`)
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les articles de [désambiguïsation](/wiki/Disambiguation) doit être placé dans le dossier`/wiki/Disambiguation`. La page principale doit être mise à jour pour inclure l'article de désambiguïsation. Vo
```suggestion
Les articles de [désambiguïsation](/wiki/Disambiguation) doivent être placés dans le dossier`/wiki/Disambiguation`. La page principale doit être mise à jour pour inclure l'article de désambiguïsation. Voir l'exemple de [Désambiguïsation/Mod](/wiki/Disambiguation/Mod).
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les redirections doivent être mises à jour pour que le ou les mots clés ambigus soient redirigés vers l'article de désambiguïsation.
```suggestion
Les redirections doivent être mises à jour afin que les mots clés ambigus soient redirigés vers l'article de désambiguïsation.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +*Note : Ne pas traduire les commentaires, car ces derniers sont destiner à des changements sur la version anglaise, il n'a pas lieu de les traduire.*
```suggestion
*Note : Ne pas traduire les commentaires, car ces derniers sont destinés à des changements sur la version anglaise, il n'y a pas lieu de les traduire.*
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +La syntaxe Markdown doit être espacés si nécessaire. Toutefois, les titres des articles sont analysés en tant que texte brut et ne doivent donc pas être espacés.
```suggestion
La syntaxe Markdown doit être espacée si nécessaire. Toutefois, les titres des articles sont analysés en tant que texte brut et ne doivent donc pas être espacés.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les hatnotes doivent être en italique et être placées immédiatement après le titre. Si plusieurs hatnotes sont utilisées, elles doivent figurer dans le même paragraphe et être séparées par un saut de
```suggestion
Les hatnotes doivent être en italique et placées immédiatement après le titre. Si plusieurs hatnotes sont utilisées, elles doivent figurer dans le même paragraphe et être séparées par un saut de ligne.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +La hatnote *Page principale* dirigent le lecteur vers l'article principal d'un sujet. Lorsque cette hatnote est utilisée, elle implique que la section sur laquelle elle se trouve est un résumé de ce
```suggestion
La hatnote *Page principale* dirige le lecteur vers l'article principal d'un sujet. Lorsque cette hatnote est utilisée, elle implique que la section sur laquelle elle se trouve est un résumé de ce dont traite la page liée. Cette hatnote ne doit comporter qu'un seul lien. Ils doivent être formatés comme suit :
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Une note doit être placé à l'endroit approprié dans une section, mais doit commencer le paragraphe et utiliser l'italique. Les avis peuvent contenir des caractères gras lorsque cela est approprié, ma
```suggestion
Une note doit être placée à l'endroit approprié dans une section, mais doit commencer le paragraphe et utiliser l'italique. Les avis peuvent contenir des caractères gras lorsque cela est approprié, mais doivent être limités au minimum. Les notes doivent être rédigées sous forme de phrases complètes. Ainsi, contrairement à la plupart des [hatnotes](#hatnote), elles doivent utiliser un point (`.`) ou un point d'exclamation (`!`) si nécessaire. Tout ce qui se trouve dans le même paragraphe d'un avis doit également être en italique. Ils doivent être formatés comme suit :
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +- `Note` doit être utilisé pour les détails factuels ou triviaux.
```suggestion
- `Note` doit être utilisé pour les détails factuels ou anecdotiques.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +L'italique peut également être utilisé pour mettre l'accent ou faciliter la lecture.
```suggestion
L'italique peut également être utilisée pour mettre l'accent ou faciliter la lecture.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les rubriques doivent utiliser le style [ATX (dièse)](https://github.github.com/gfm/#atx-headings "GitHub") et doivent être précédés et suivis d'une ligne vide. Le titre est une exception lorsqu'il s
```suggestion
Les rubriques doivent utiliser le style [ATX (dièse)](https://github.github.com/gfm/#atx-headings "GitHub") et doivent être précédées et suivies d'une ligne vide. Le titre est une exception lorsqu'il se trouve sur la première ligne. Dans ce cas, il suffit de laisser une ligne vide après le titre.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les rubriques ne doivent pas dépasser un niveau d'en-tête de 5 et ne doivent pas être utilisés pour styliser ou formater le texte.
```suggestion
Les rubriques ne doivent pas dépasser un niveau d'en-tête de 5 et ne doivent pas être utilisées pour styliser ou formater le texte.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +L'intitulé du titre doit figurer sur la première ligne, sauf si la [page de garde](#page-de-garde) est utilisé. Si c'est le cas, l'intitulé du titre doit être placé à la suite de celui-ci et une lign
```suggestion
L'intitulé du titre doit figurer sur la première ligne, sauf si la [page de garde](#page-de-garde) est utilisée. Si c'est le cas, l'intitulé du titre doit être placé à la suite de celui-ci et une ligne vide doit précéder l'intitulé du titre.
```

2021-05-02 10:41 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Lors de la traduction d'images annotées, la version localisée de l'image doit être placée dans le même répertoire que la version originale (c'est-à-dire la version anglaise). Le nom de fichier d'une
```suggestion
Lors de la traduction d'images annotées, la version localisée de l'image doit être placée dans le même répertoire que la version originale (c'est-à-dire la version anglaise). Le nom de fichier d'une version localisée de l'image doit commencer par le nom de la version originale, suivi d'un tiret, puis du nom local (en lettres majuscules). Voir les exemples suivants :
```

2021-05-02 12:45 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les citations en bloc est limité à la citation du texte d'une personne. Elle ne doit pas être utilisée pour formater le texte autrement.
Je pense qu'il faut reformuler cette phrase

2021-05-02 12:51 UTC, Ganondorfosu commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les citations en bloc sont limité à la citation du texte d'une personne. Elle ne doit pas être utilisé pour formater le texte.
```suggestion
Les citations en bloc sont limitées à la citation du texte d'une personne. Elle ne doit pas être utilisé pour formater le texte.
```

2021-05-04 16:30 UTC, geshii approved these changes
sounds good for me

2021-05-12 08:01 UTC, osuShiro requested changes

2021-05-12 09:01 UTC, geshii commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les liens doivent utiliser le style en ligne s'ils ne sont référencés qu'une seule fois. Le style inline entre crochets doit être évité. Les références aux liens de référence doivent être placées en
je trouve que c'est pas facilement compréhensible, faudrait reformuler la phrase non?

2021-05-12 14:12 UTC, DoryanR commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les liens doivent utiliser le style en ligne s'ils ne sont référencés qu'une seule fois. Le style inline entre crochets doit être évité. Les références aux liens de référence doivent être placées en
Je vois pas trop comment mieux la formuler

2021-05-13 10:07 UTC, Satsukel requested changes

2021-05-13 16:07 UTC, Satsukel approved these changes

2021-05-21 17:01 UTC, TicClick commented
please adapt your translation to 596efd8dff27df4ce19401c51c3f809562ea6e95

2021-05-21 17:05 UTC, TicClick approved these changes

2021-05-21 17:06 UTC, merged