[FR] ASC/Writing
ppy/osu-wiki pull request #5358
Opened 2021-05-02 18:28 UTC by DoryanR

Proposal for the French translation of the wiki page "Article styling criteria/Writing".

I don't think it's necessary to translate it, since it concerns the creation of articles in English, but I did it anyway, trying to adapt it for the French.

2021-05-13 08:37 UTC, Satsukel requested changes

2021-05-13 08:37 UTC, Satsukel commented on wiki/Article_styling_criteria/Writing/fr.md
> +Les expressions `vous` et `votre` sont à éviter. Le `je` ne doit pas être utilisé. Les termes `nous`, `il` ou `sa` et `elle` ou `son` ne doivent pas être utilisés (voir ci-dessus pour les autres term
ça serait pas plus "tu" et "ton" qui ne peuvent pas être utilisés ?

2021-05-13 08:37 UTC, Satsukel commented on wiki/Article_styling_criteria/Writing/fr.md
> +Les articles doivent utiliser de préférence une grammaire et une [syntaxe américaines plus simples](https://www.thepunctuationguide.com/british-versus-american-style.html "Le Guide de la ponctuation"
```suggestion
Les articles doivent utiliser de préférence une grammaire et une [syntaxe américaines plus simple](https://www.thepunctuationguide.com/british-versus-american-style.html "Le Guide de la ponctuation").
```

2021-05-13 08:57 UTC, DoryanR commented on wiki/Article_styling_criteria/Writing/fr.md
> +Les expressions `vous` et `votre` sont à éviter. Le `je` ne doit pas être utilisé. Les termes `nous`, `il` ou `sa` et `elle` ou `son` ne doivent pas être utilisés (voir ci-dessus pour les autres term
Ouais effectivement, j'ai modifier

2021-05-13 16:09 UTC, Satsukel approved these changes

2021-05-21 17:02 UTC, TicClick commented
please adapt your translation to 596efd8dff27df4ce19401c51c3f809562ea6e95

> I did it anyway, trying to adapt it for the French.

that is the spirit -- I've done the same for its Russian version

2021-05-21 18:56 UTC, TicClick approved these changes

2021-05-21 18:56 UTC, merged