[FR] Beatmaps articles
ppy/osu-wiki pull request #5363
Opened 2021-05-03 16:42 UTC by DoryanR

Translation of the following wiki pages:

- `Beatmap/Genre_and_language`
- `Beatmap/Online_offset`
- `Beatmap/Primary_metadata_source`

Update of the translations of the following wiki pages:

- `Beatmap/Category`
- `Beatmap/Difficulty`

Also : 

- Addition of the French images for the article `Genre and language`
- Update `beatmap-listing.png` for the English side, because the line `Explicit Beatmaps` was missing in image.

2021-05-12 20:02 UTC, Satsukel requested changes

2021-05-13 16:04 UTC, Satsukel requested changes

2021-05-13 16:04 UTC, Satsukel commented on wiki/Beatmap/Category/fr.md
> +Les [beatmaps](/wiki/Beatmap) soumises en ligne sont répartis en catégories en fonction de leurs activités récentes, de leurs [nomination](/wiki/Beatmap_ranking_procedure#qualification) et de leurs p
Je sais pas comment je l'ai raté celle-là
```suggestion
Les [beatmaps](/wiki/Beatmap) soumises en ligne sont réparties en catégories en fonction de leurs activités récentes, de leurs [nomination](/wiki/Beatmap_ranking_procedure#qualification) et de leurs popularités.
```

2021-05-13 17:15 UTC, Satsukel submitted a review, later dismissed

2021-05-17 15:23 UTC, TicClick approved these changes

2021-05-17 15:25 UTC, merged