[FR] Beatmapping Combo
ppy/osu-wiki pull request #5385
Opened 2021-05-07 16:30 UTC by Satsukel

French translation of the wiki page Beatmapping/Combo

2021-05-07 16:42 UTC, DoryanR requested changes

2021-05-07 16:42 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +Le **Combo** (ou **comboset**) se réfère à un ensemble de hit circles et de sliders dans les [beatmaps](/wiki/Beatmap) [osu!](/wiki/Game_mode/osu!) et [osu!catch](/wiki/Game_mode/osu!catch). Les [hit
```suggestion
Le **Combo** (ou **comboset**) se réfère à un ensemble de cercles et de sliders dans les [beatmaps](/wiki/Beatmap) des modes [osu!](/wiki/Game_mode/osu!) et [osu!catch](/wiki/Game_mode/osu!catch). Les [objets](/wiki/Hit_Objects) du même combo ont la même [couleur de combo](/wiki/Glossary/Combo_Colour), et sont connectés par des followpoints. La fin d'un combo donne un bonus de [vie](/wiki/Beatmapping/Health) s'il est terminé avec succès. Chaque combo commence par un objet marqué d'un nouveau combo.
```

2021-05-07 16:42 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +[osu!taiko](/wiki/Game_mode/osu!taiko) et [osu!mania](/wiki/Game_mode/osu!mania) n'utilisent pas de combos.
```suggestion
Les modes [osu!taiko](/wiki/Game_mode/osu!taiko) et [osu!mania](/wiki/Game_mode/osu!mania) n'utilisent pas de combos.
```

2021-05-07 16:42 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +Dans [osu!](/wiki/Game_mode/osu!), chaque hit object dans un combo a son propre numéro de combo, en plus d'une couleur de combo. Les nouveaux combos commencent à partir de 1 et augmentent de plus en
```suggestion
Dans le mode [osu!](/wiki/Game_mode/osu!), chaque objet dans un combo a son propre numéro de combo, en plus d'une couleur de combo. Les nouveaux combos commencent à partir de 1 et augmentent progressivement, et les spinners forcent l'objet suivant à commencer un nouveau combo. Plus de vie est récupérée avec les scores [Geki et Katu](/wiki/Score#osu!), qui peuvent être donnés par le dernier objet d'un combo.
```

2021-05-07 16:42 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +Dans [osu!catch](/wiki/Game_mode/osu!catch), chaque types de fruit est colorié dans un ordre donné. Les juice streams et les fruits à la fin des sliders auront toujours la même couleur que le fruit d
```suggestion
Dans le mode [osu!catch](/wiki/Game_mode/osu!catch), chaque fruit est colorié dans un ordre donné. Les juice streams et les fruits de fin de sliders auront toujours la même couleur que le fruit de départ, en revanche les bananes auront toujours une teinte jaune. Quand un combo est réalisé, les fruits empilés sur l'attrapeur explosent vers l'extérieur.
```

2021-05-07 16:54 UTC, DoryanR requested changes

2021-05-07 16:54 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +Dans le mode [osu!](/wiki/Game_mode/osu!), chaque objet dans un combo a son propre numéro de combo, en plus d'une couleur de combo. Les nouveaux combos commencent à partir de 1 et augmentent progress
```suggestion
Dans le mode [osu!](/wiki/Game_mode/osu!), chaque objet dans un combo a son propre numéro de combo, en plus d'une couleur de combo. Les nouveaux combos commencent à partir de 1 et augmentent progressivement, et les spinners forcent l'objet suivant à commencer un nouveau combo. Plus de vie est récupérée grâce aux [Geki et Katu](/wiki/Score#osu!), qui peuvent être donnés par le dernier objet d'un combo.
```

2021-05-07 16:54 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +Dans le mode [osu!catch](/wiki/Game_mode/osu!catch), chaque fruit est colorié dans un ordre donné. Les juice streams et les fruits de fin de sliders auront toujours la même couleur que le fruit de dé
```suggestion
Dans le mode [osu!catch](/wiki/Game_mode/osu!catch), chaque fruit est colorié dans un ordre donné. Les juice streams et les fruits de fin de sliders auront toujours la même couleur que le fruit de départ. En revanche, les bananes auront toujours une teinte jaune. Quand un combo est réalisé, les fruits empilés sur l'attrapeur explosent vers l'extérieur.
```

2021-05-07 17:00 UTC, DoryanR requested changes

2021-05-07 17:25 UTC, Satsukel commented on wiki/Beatmapping/Combo/fr.md
> +Dans le mode [osu!](/wiki/Game_mode/osu!), chaque objet dans un combo a son propre numéro de combo, en plus d'une couleur de combo. Les nouveaux combos commencent à partir de 1 et augmentent progress
Je suis assez d'accord pour la deuxième suggestion mais le "à" je pense pas que ce soit correct

2021-05-07 17:38 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +Dans le mode [osu!](/wiki/Game_mode/osu!), chaque objet dans un combo a son propre numéro de combo, en plus d'une couleur de combo. Les nouveaux combos commencent à partir de 1 et augmentent progress
J'ai remodifier la suggestion, tu peut l'appliquer

2021-05-07 20:33 UTC, DoryanR requested changes

2021-05-07 20:33 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +*Pour d'autres utilisations, voir [Combo (désambiguïsation)](/wiki/Disambiguation/Combo).*
```suggestion
*Pour d'autres utilisations, voir : [Combo (désambiguïsation)](/wiki/Disambiguation/Combo).*
```

2021-05-07 20:33 UTC, DoryanR commented on wiki/Beatmapping/Combo/fr.md
> +Dans le mode [osu!catch](/wiki/Game_mode/osu!catch), chaque fruit est colorié dans un ordre donné. Les juice streams et les fruits de fin de sliders auront toujours la même couleur que le fruit de dé
```suggestion
Dans le mode [osu!catch](/wiki/Game_mode/osu!catch), chaque fruit est coloré dans un ordre donné. Les juice streams et les fruits de fin de sliders auront toujours la même couleur que le fruit de départ. En revanche, les bananes auront toujours une teinte jaune. Quand un combo est réalisé, les fruits empilés sur l'attrapeur explosent vers l'extérieur.
```

2021-05-11 17:19 UTC, TicClick approved these changes

2021-05-11 18:30 UTC, TicClick approved these changes

2021-05-11 18:32 UTC, merged