[FR] Update "AiMod"
ppy/osu-wiki pull request #5394
Opened 2021-05-08 17:22 UTC by DoryanR

Proposal to update the French translation of the wiki page "AiMod".

- Addition of the French images

2021-05-12 17:42 UTC, Satsukel requested changes

2021-05-12 17:42 UTC, Satsukel commented on wiki/Beatmap_Editor/AiMod/fr.md
> +| Les timing point non hérités entrent en conflit avec la difficulté {0}. |  |  |
```suggestion
| Les timing points non hérités entrent en conflit avec la difficulté {0}. |  |  |
```

2021-05-12 17:42 UTC, Satsukel commented on wiki/Beatmap_Editor/AiMod/fr.md
> +- **AiMod ne peut pas détecter un grand nombre de problèmes** qui sont considérés comme non classables par les [critères de classement](/wiki/Ranking_Criteria), tels que les objets potentiellement ma
"Manqués" me semble bizarre je pense qu'il faut trouver autre chose, ce que je suggère est la première traduction qui m'est venu à l'esprit.
```suggestion
- **AiMod ne peut pas détecter un grand nombre de problèmes** qui sont considérés comme non classables par les [critères de classement](/wiki/Ranking_Criteria), tels que les objets potentiellement mal rythmés, les hitsounds retardés, les fichiers d'arrière-plan de plus de 2,5 Mo, etc.
```

2021-05-12 20:07 UTC, Satsukel approved these changes

2021-05-13 16:06 UTC, Satsukel approved these changes

2021-05-17 14:51 UTC, TicClick approved these changes

2021-05-17 14:52 UTC, merged