[JA] Add Ranking_Criteria/osu!mania
ppy/osu-wiki pull request #5395
Opened 2021-05-08 19:20 UTC by ViaSnake

Add `Ranking_Criteria/osu!mania` in japanese.
This translation is based on the thread [日本語版 osu!mania ranking criteria](https://osu.ppy.sh/community/forums/topics/1285567) posted by RuberusuScarlet in the osu!forum
I have exchanged messages with RuberusuScarlet and received his permission to add this translation.

2021-05-14 02:38 UTC, peppy requested changes

2021-05-14 02:42 UTC, peppy requested changes
re-review for updated terminology

2021-05-14 02:42 UTC, peppy commented on wiki/Ranking_Criteria/osu!mania/ja.md
> +- **スライダーの速度の変更は、曲に使用されてるビートに応じて合わせる必要があります。** ストレートビートを使用している場合は、1/4、1/8、1/16を使用する必要があります。スウィングビートを使用している場合は、1/6または1/12を使用する必要があります。曲のビートが推奨位置と異なる場合は、該当するビートを使用が優先されます。
```suggestion
- **スライダーの速度の変更は、曲に使用されてるビートに応じて合わせる必要があります。** ストレートビートを使用している場合は、1/4、1/8、1/16を使用する必要があります。スウィングビートを使用している場合は、1/6または1/12を使用する必要があります。曲のビートが推奨位置と異なる場合は、該当するビートが優先して使用されます。
```

2021-05-14 09:34 UTC, ViaSnake commented
Please wait a bit before merging. I may still need to clean up this article.
I will self-review words and grammar, and replace it with more wiki-friendly words.

2021-05-15 03:42 UTC, ViaSnake commented
Done.

2021-05-21 04:21 UTC, peppy requested changes
Just a minor one

2021-05-24 03:40 UTC, merged