[FR] Beatmap editor articles (part 1)
ppy/osu-wiki pull request #5397
Opened 2021-05-09 10:07 UTC by DoryanR

Proposal to update the French translation of the wiki page "Compose".

- Addition of the French images for the article `Compose`

Also:

- In `Beat Snap Divisor/fr.md` and `en.md` : convert standard > osu!, and lowercase title in `fr.md`

2021-05-11 14:44 UTC, Satsukel requested changes
Correction de certaines fautes/coquilles

2021-05-11 14:44 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +**Représentation visuelle du mappage basée sur l'horodatage actuel** Mappez votre design ici et ol apparaîtra exactement comme vous l'avez mappé pendant le jeu. Il s'agit d'un mappage WYSIWYG (what y
Coquille
```suggestion
**Représentation visuelle du mappage basée sur l'horodatage actuel** Mappez votre design ici et il apparaîtra exactement comme vous l'avez mappé pendant le jeu. Il s'agit d'un mappage WYSIWYG (what you see is what you get > ce que vous voyez est ce que vous obtenez). Pour un mapping en texte (généralement pour un réglage fin), vous pouvez ouvrir le fichier `.osu` directement en utilisant Notepad.
```

2021-05-12 09:45 UTC, Satsukel approved these changes

2021-05-21 17:20 UTC, Satsukel requested changes

2021-05-21 17:20 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Nouveau combo (`Q`) | **Clic droit :** Changez la note actuelle pour la couleur combinée suivante. | Note du combo. C'est l'équivalent d'un couplet/une mesure dans une chanson/un instrument. Une fo
```suggestion
| Nouveau combo (`Q`) | **Clic droit :** Change la note actuelle en la couleur du combo suivant. | Note du combo. C'est l'équivalent d'un couplet/une mesure dans une chanson/un instrument. Une fourchette acceptable est d'environ 5 à 20. |
```

2021-05-21 17:20 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Grid Snap (`T`) | **`Shift` (Maintenir):** On/Off temporaire. **`Ctrl` (Maintenir):** Désactiver temporairement l'angle du snapping. | Par défaut, les notes sont fixées à la grid. |
```suggestion
| Grid Snap (`T`) | **`Shift` (Maintenu):** On/Off temporaire. **`Ctrl` (Maintenu):** Désactiver temporairement l'angle du snapping. | Par défaut, les notes sont fixées à la grid. |
```

2021-05-21 17:20 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Distance Snap (`Y`) | **`Alt` (Maintenir):** On/Off temporaire. Bascule Beat Snap Divisor en Distance Snap **`Alt` + Molette de souris :** Ajustez le multiplicateur de distance snap | La distance e
```suggestion
| Distance Snap (`Y`) | **`Alt` (Maintenu):** On/Off temporaire. Bascule Beat Snap Divisor en Distance Snap **`Alt` + Molette de souris :** Ajustez le multiplicateur de distance snap | La distance entre des notes consécutives sera cassée en fonction de leur différence rythmique. A utiliser de préférence lorsque la timeline est en pause. |
```

2021-05-21 17:20 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Lock Notes (`L`) | ("Select" sur une note) **Clic gauche :** Verrouille cette note | Verrouille la note sélectionnée à la position et à l'horodatage actuels. |
```suggestion
| Lock Notes (`L`) | ("Select" sur une note) **Clic gauche :** Verrouiller cette note | Verrouille la note sélectionnée à la position et à l'horodatage actuels. |
```

2021-05-21 17:20 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Hold (`3`) | **Clic gauche (maintien):** Placez une hold note et ajustez la longueur. **Relâcher à la fin:** Définir une longueur de hold | Ajoute une hold note à la colonne actuelle en fonction de
```suggestion
| Hold (`3`) | **Clic gauche (maintenu):** Place une hold note et ajuste la longueur. **Relâcher à la fin:** Définit la longueur de la hold note | Ajoute une hold note à la colonne actuelle en fonction de la position de la souris. |
```

2021-05-21 17:20 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Lock Notes (`L`) | ("Select" sur une note) **Clic gauche :** Verrouiller cette note | Verrouille la note sélectionnée à la position et à l'horodatage actuels. |
```suggestion
| Lock Notes (`L`) | ("Select" sur une note) **Clic gauche :** Verrouille cette note | Verrouille la note sélectionnée à la position et à l'horodatage actuels. |
```

2021-05-21 17:20 UTC, Satsukel commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Slider (`3`) | **Clic gauche/droit :** Début/Fin de slider. Ajouter/supprimer des sliderpoints (carré blanc). **Clic gauche x2 :** Nouvelle section de courbe (carré rouge). | Slider. |
```suggestion
| Slider (`3`) | **Clic gauche/droit :** Début/Fin de slider. Ajoute/supprime des sliderpoints (carré blanc). **Clic gauche x2 :** Nouvelle section de courbe (carré rouge). | Slider. |
```

2021-05-21 17:41 UTC, DoryanR commented on wiki/Beatmap_Editor/Compose/fr.md
> +| Hold (`3`) | **Clic gauche (maintien):** Placez une hold note et ajustez la longueur. **Relâcher à la fin:** Définir une longueur de hold | Ajoute une hold note à la colonne actuelle en fonction de
```suggestion
| Hold (`3`) | **Clic gauche (maintenu) :** Place une hold note et ajuste la longueur. **Relâcher à la fin: ** Définit la longueur de la hold note | Ajoute une hold note à la colonne actuelle en fonction de la position de la souris. |

```

2021-05-21 18:34 UTC, Satsukel approved these changes

2021-05-21 19:05 UTC, TicClick approved these changes

2021-05-21 19:06 UTC, TicClick approved these changes

2021-05-21 19:06 UTC, merged