[FR] Beatmap editor articles (part 2)
ppy/osu-wiki pull request #5398
Opened 2021-05-09 17:17 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Beatmap_Editor/Design`
- `Beatmap_Editor/SB_Load`

Also:

- Addition of the French images for the article `Design`

2021-05-12 09:42 UTC, Satsukel requested changes

2021-05-12 09:42 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Flèches `Haut`/`Bas` en bas à gauche | Faites défiler vers le haut/bas la timelie de transformation (pour voir la timeline des mouvements/couleurs). |
```suggestion
| Flèches `Haut`/`Bas` en bas à gauche | Faites défiler vers le haut/bas la timeline de transformation (pour voir la timeline des mouvements/couleurs). |
```

2021-05-12 09:42 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +#### Contrôle des keyframe
```suggestion
#### Contrôle des keyframes
```

2021-05-12 09:42 UTC, Satsukel commented on wiki/Beatmap_Editor/SB_Load/fr.md
> +Pour chaque png que vous utilisez dans votre storyboard, osu! doit dessiner l'ensemble. Même les pixels transparents doivent être "dessinés", de sorte que les images comportant beaucoup d'espace vide
Je chipotte un peu pour le "en" là j'avoue
```suggestion
Pour chaque png que vous utilisez dans votre storyboard, osu! doit en dessiner l'ensemble. Même les pixels transparents doivent être "dessinés", de sorte que les images comportant beaucoup d'espaces vides imposent un stress inutile à l'ordinateur. C'est un problème facile à résoudre, en général :
```

2021-05-13 16:07 UTC, Satsukel approved these changes

2021-05-21 17:28 UTC, Satsukel requested changes

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Boutons `+`/`-` à gauche | Augmenter/diminuer le zoom de la timeline |
```suggestion
| Boutons `+`/`-` à gauche | Augmente/diminue le zoom de la timeline |
```

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Flèches `Haut`/`Bas` en bas à gauche | Faites défiler vers le haut/bas la timeline de transformation (pour voir la timeline des mouvements/couleurs). |
```suggestion
| Flèches `Haut`/`Bas` en bas à gauche | Fait défiler vers le haut/bas la timeline de transformation (pour voir la timeline des mouvements/couleurs). |
```

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Boutons `+`/`-` | Ajouter/supprimer des points d'ancrage pour la transformation sélectionnée. |
```suggestion
| Boutons `+`/`-` | Ajoute/supprime des points d'ancrage pour la transformation sélectionnée. |
```

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Flèches `Gauche`/`Droite` | Sauter en arrière/en avant vers le point d'ancrage le plus proche de la transformation sélectionnée. |
```suggestion
| Flèches `Gauche`/`Droite` | Saute en arrière/en avant vers le point d'ancrage le plus proche de la transformation sélectionnée. |
```

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Flèches `Gauche`/`Droite` | Sauter en arrière/en avant vers le point d'ancrage le plus proche de la transformation sélectionnée. |
Ou sinon la variante à laquelle j'ai pensé aussi
```suggestion
| Flèches `Gauche`/`Droite` | Saute vers le point d'ancrage en arrière/en avant le plus proche de la transformation sélectionnée. |
```

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Rotation | Faire pivoter un certain nombre de "radian" (et non de degrés). |
```suggestion
| Rotation | Fait pivoter un certain nombre de "radian" (et non de degrés). |
```

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Style d'animation | Commencez lentement/rapidement puis vite/lent vers le point final. Utile avec le Fade In. |
```suggestion
| Style d'animation | Commence lentement/rapidement puis vite/lent vers le point final. Utile avec le Fade In. |
```

2021-05-21 17:28 UTC, Satsukel commented on wiki/Beatmap_Editor/Design/fr.md
> +| Spécifique à cette diff | Sauvegardez tous les SB dans le fichier `.osu` de cette difficulté au lieu du fichier `.osb`. |
```suggestion
| Spécifique à cette diff | Sauvegarde tous les SB dans le fichier `.osu` de cette difficulté au lieu du fichier `.osb`. |
```

2021-05-21 18:33 UTC, Satsukel approved these changes

2021-05-21 19:04 UTC, TicClick approved these changes

2021-05-21 19:04 UTC, merged