[ZH] Account Restrictions
ppy/osu-wiki pull request #5400
Opened 2021-05-10 00:42 UTC by mcendu

2021-05-18 15:14 UTC, PercyDan54 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +- **联系我们的[账号支持团队](*/wiki/People/The_Team/Account_support_team)**。如果这之后你的账号依然被限制了，请**通过您的账号所绑定的邮箱**给 [`accounts@ppy.sh`](mailto:accounts@ppy.sh) 发送一封邮件。请保证您将您的用户名，以及任何具体的您认为和您被限制有关的情节写到邮件中。您说的越多，我们就更容
```suggestion
- **联系我们的[账号支持团队](*/wiki/People/The_Team/Account_support_team)**。如果这之后您的账号依然被限制了，请**通过您的账号所绑定的邮箱**给 [`accounts@ppy.sh`](mailto:accounts@ppy.sh) 发送一封邮件。请保证您将您的用户名，以及任何您认为和您被限制有关的具体情节写到邮件中。您说的越多，我们就更容易解决问题。
```

2021-05-18 15:14 UTC, PercyDan54 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +- 如果您坚定的认为您是被误封的，请立刻通知我们以便讨论。
```suggestion
- 如果您坚定地认为您是被误封的，请立刻通知我们以便讨论。
```

2021-05-18 15:14 UTC, PercyDan54 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +如果您最初的账号没有被限制，您可以登录回去继续游玩，但应当从此不再使用小号登录，否则您会收到更多的处罚。
```suggestion
如果您最初的账号没有被限制，您可以登录回去继续游玩，但应当从此不再使用小号登录，否则您会受到更多的处罚。
```

2021-05-18 15:14 UTC, PercyDan54 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +- **这不是您的第一个帐号。** 使用多个账号是被明令禁止的。一个人第一个账号（主账号）以外的任何账号会被永久限制，但他的主账号一般不会被封并可以继续游玩。如果某人使用多个账号的情节很严重，他的主账号会被禁言以作为警告，而如果再犯，主账号也会被连带限制。如果您的账号被封，而且您知道您还有其它账号，请转到您的主账号上，并不要再使用被封的小号。如果您登陆不了您的主账号，请给 [`accounts@
```suggestion
- **这不是您的第一个帐号。** 使用多个账号是被明令禁止的。每个人除第一个账号（主账号）以外的任何账号会被永久限制，但他的主账号一般不会被封并可以继续游玩。如果某人使用多个账号的情节很严重，他的主账号会被禁言以作为警告，而如果再犯，主账号也会被连带限制。如果您的账号被封，而且您知道您还有其它账号，请转到您的主账号上，并不要再使用被封的小号。如果您登陆不了您的主账号，请给 [`accounts@ppy.sh`](mailto:accounts@ppy.sh) 发送邮件，让我们能够帮您找回它。
```

2021-06-04 23:18 UTC, kj415j45 requested changes

2021-06-04 23:18 UTC, kj415j45 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +- **任何重大的恶行都将立即导致您再次被限制。** 这包括重大禁言。
```suggestion
- **任何严重违规行为都将立即导致您再次被限制。** 包括严重的禁言。
```

2021-06-04 23:18 UTC, kj415j45 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +- **您不应和其它的账号相关联**——这包括在学校机房、网吧等的公用电脑上游玩。
原文也很怪，暂无修改意见。

2021-06-04 23:18 UTC, kj415j45 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +- **您试图逃避处罚，或者使用其它账号。** 为了能够在线游玩而建立一个新账号的行为会被视为逃避限制，并会导致您的冷却被重置为三个月。如果您逃避的次数太多，您的申诉可能会被永久拒绝。如果您还在使用小号游玩，您的冷却也会被重置。要记住，使用多个账号是被[规则](/wiki/Rules)禁止的，而您应当只使用您的第一个账号游玩。如果您不知道您的第一个账号是哪一个，请给我们发邮件，我们会让您知道！
```suggestion
- **您试图逃避处罚，或者使用其它账号。** 为了能够在线游玩而建立一个新账号的行为会被视为逃避限制，并会导致您的冷却被重置为三个月。如果您逃避的次数太多，您的申诉可能会被永久拒绝。如果您还在使用小号游玩，您的冷却也会被重置。要记住，使用多个账号是被[规章制度](/wiki/Rules)禁止的，而您应当只使用您的第一个账号游玩。如果您不知道您的第一个账号是哪一个，请给我们发邮件，我们会让您知道！
```

2021-06-04 23:18 UTC, kj415j45 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +请知道向这个地址发邮件只能保证对您的申诉的复审或应答。如果您被发现不符合申诉过程的期望，复审不会保证申诉结果的改变。
```suggestion
请您知晓：向这个地址发邮件只能保证对您的申诉的复审或应答。如果您被发现不符合申诉过程的期望，复审不会保证申诉结果的改变。
```

2021-06-04 23:18 UTC, kj415j45 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +**我们只会对发送至 [`appeal-review@ppy.sh`](mailto:appeal-review@ppy.sh) 的复审或审阅请求进行答复。** 不要试图通过推特，Discord，QQ 等方式联系开发人员（以及 GMT、NAT 等志愿者团队）来绕过这个政策——他们帮不了您。
```suggestion
**我们只会对发送至 [`appeal-review@ppy.sh`](mailto:appeal-review@ppy.sh) 的复审或调查请求进行答复。** 不要试图通过推特，Discord，QQ 等方式联系开发人员（以及 GMT、NAT 等志愿者团队）来绕过这个政策——他们帮不了您。
```

2021-06-04 23:18 UTC, kj415j45 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +| 限制原因 | 冷却时长 | 申诉信息 |
```suggestion
| 限制原因 | 冷却时长 | 注意事项 |
```

2021-06-04 23:18 UTC, kj415j45 commented on wiki/Help_Centre/Account_Restrictions/zh.md
> +| 严重的不当行为 | 视情节而定 | 需遵守申诉条款 |
```suggestion
| 严重的不当行为 | 可变 | 需遵守申诉条款，冷却期视情节而定 |
```

2021-06-05 03:18 UTC, kj415j45 approved these changes

2021-06-12 22:58 UTC, cl8n approved these changes

2021-06-12 22:58 UTC, merged