[FR] Beatmapping articles
ppy/osu-wiki pull request #5409
Opened 2021-05-11 11:09 UTC by Satsukel

Providing French translation to the following Beatmapping wiki articles:
- Approach rates
- Health
- Overall Difficulty

2021-05-12 08:57 UTC, geshii requested changes

2021-05-12 08:57 UTC, geshii commented on wiki/Beatmapping/Approach_rate/fr.md
> +  - temps d'approche
met approach rate dans les tags aussi je pense

2021-05-12 08:59 UTC, geshii commented on wiki/Beatmapping/Approach_rate/fr.md
> +# Taux d'approche
@DoryanR tu peux m'éclairer ?

2021-05-12 12:48 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +
Par rapport à ton erreur lint, regarde si tu a pas mit un espace sur cette ligne, car sinon il prend pas ça comme un saut de ligne.

2021-05-12 15:15 UTC, DoryanR requested changes

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- Une tape réussie sur le cercle (un meilleur jugement permet de gagner plus de vie ; le dernier cercle de tir d'un combo de couleur donne plus de vie).
```suggestion
- Une frappe réussie sur le cercle (un meilleur jugement permet de gagner plus de vie ; le dernier cercle de tir d'un combo de couleur donne plus de vie).
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- Une tape réussie sur un début de slider
```suggestion
- Une frappe réussie sur un début de slider
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- La balle du slider a réussi à collecter une marque du slider
ça fait bizarre je trouve, je pense que c'est mieux de garder des termes anglais

```suggestion
- La slider ball a réussi à collecter un slider tick
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- La balle du slider a touché la fin du slider ou une flèche inversée avec succès (un meilleur jugement à la marque de fin permet de gagner plus de vie)
```suggestion
- La slider ball a touché la fin du slider ou une flèche inversée avec succès (un meilleur jugement à la marque de fin permet de gagner plus de vie)
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Perte de vie:
```suggestion
Perte de vie :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- Taper la tête d'un slider trop tôt
```suggestion
- Frapper un sliderhead trop tôt
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- Manquer une marque ou la flèche inversée d'un slider
```suggestion
- Manquer un tick ou la flèche inversée d'un slider
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Aucun effet:
```suggestion
Aucun effet :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Dans le mode [osu!taiko](/wiki/Game_mode/osu!taiko), la barre de vie est vide au départ et doit être remplie à au moins 50% pour passer une beatmap. Pour cela, il faut taper la bonne combinaison de t
```suggestion
Dans le mode [osu!taiko](/wiki/Game_mode/osu!taiko), la barre de vie est vide au départ et doit être remplie à au moins 50% pour passer une beatmap. Pour cela, il faut frapper la bonne combinaison de touches en rythme avec la musique.
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Des bursts de score apparaîtront après avoir tapé des notes,  modifiant les valeurs de score et de vie en fonction de la précision à laquelle la note est tapée. Une note tapée parfaitement en rythme
```suggestion
Des bursts de score apparaîtront après avoir frappé des notes, modifiant les valeurs de score et de vie en fonction de la précision à laquelle la note est frappée. Une note frappée parfaitement en rythme (300) permettra de récupérer plus de vie qu'une note mal frappée en rythme (50). Les joueurs reçoivent également des boosts plus importants s'ils réalisent un Katu ou un Geki à la fin d'un combo. Un miss, à l'inverse, lui fera perdre de la vie. Les roulements de tambours peuvent être ignorés sans pénalité au niveau de la vie car ils n'ont aucune influence sur la barre de vie. Pour un aperçu de la récupération et de la perte de vie, voir ci-dessous :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Récupération de santé:
```suggestion
Récupération de santé :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Perte de santé:
```suggestion
Perte de santé :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Aucun effet:
```suggestion
Aucun effet :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +*Note: Il est complètement possible qu'une beatmap ne passe jamais à cause de son design si elle contient uniquement des roulements de tambours et/ou des dendens/shakers.*
```suggestion
*Note: Il est complètement possible qu'une beatmap ne soit jamais classée à cause de son design si elle contient uniquement des roulements de tambours et/ou des dendens/shakers.*
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Dans le mode [osu!catch](/wiki/Game_mode/osu!catch), la vie diminue à un rythme régulier appelé  [drain de vie](/wiki/Beatmapping/Health_drain), mais peut être récupérée en attrapant des fruits et de
```suggestion
Dans le mode [osu!catch](/wiki/Game_mode/osu!catch), la vie diminue à un rythme régulier appelé [drain de vie](/wiki/Beatmapping/Health_drain), mais peut être récupérée en attrapant des fruits et des drops.
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Des bursts de score apparaîtront après avoir attrapé des fruits,  modifiant les valeurs de score et de vie en fonction de l'objet attrapé. Les joueurs reçoivent également des boosts plus importants s
Je crois pas qu'il y aient de Geki sur osu!catch

```suggestion
Des bursts de score apparaîtront après avoir attrapé des fruits, modifiant les valeurs de score et de vie en fonction de l'objet attrapé. Rater un fruit, à l'inverse, lui fera perdre de la vie. Les bananes peuvent être ignorés sans pénalité au niveau de la vie. Pour un aperçu de la récupération et de la perte de vie, voir ci-dessous :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Des bursts de score apparaîtront après avoir tapé des notes,  modifiant les valeurs de score et de vie en fonction de la précision à laquelle la note est tapée. Une note tapée parfaitement en rythme
```suggestion
Des bursts de score apparaîtront après avoir tapé des notes, modifiant les valeurs de score et de vie en fonction de la précision à laquelle la note est frappée. Une note frappée parfaitement en rythme (300) permettra de récupérer plus de vie qu'une note mal frappée en rythme (50). Un miss, à l'inverse, lui fera perdre de la vie. La barre de vie se régénère peu à peu pendant qu'une long note est maintenue. Pour un aperçu de la récupération et de la perte de vie, voir ci-dessous :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +Récupération de vie:
```suggestion
Récupération de vie :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- Obtenir un 300 Arc-en-ciel, un 300, ou un 200 (de la plus grande à la plus petite valeur de vie récupérée)
```suggestion
- Obtenir un 300 MAX, un 300, ou un 200 (de la plus grande à la plus petite valeur de vie récupérée)
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- OD < 5: `5 - 2 * (5 - OD) / 5`
```suggestion
- OD < 5 : `5 - 2 * (5 - OD) / 5`
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- OD = 5: `5`
```suggestion
- OD = 5 : `5`
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- OD > 5: `5 + 2.5 * (OD - 5) / 5`
```suggestion
- OD > 5 : `5 + 2.5 * (OD - 5) / 5`
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +Dans osu!, le système de timing n'autorise pas qu'un objet soit tapé avant que l'objet précédent ne le soit (ou manqué après que la hit window soit passée). Cela peut conduire à des cas de **notelock
```suggestion
Dans osu!, le système de timing n'autorise pas qu'un objet soit frappé avant que l'objet précédent ne le soit (ou manqué après que la hit window soit passée). Cela peut conduire à des cas de **notelock** où les joueurs manqueront une note même s'ils la frappent parfaitement en rythme avec la musique. Cela se produit plus souvent sur les beatmaps avec de faibles valeurs d'OD, car les hit windows des objets se chevauchent plus fréquemment.
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +Il existe quatre mods qui modifient l'OD lorsqu'ils sont activés:
```suggestion
Il existe quatre mods qui modifient l'OD lorsqu'ils sont activés :
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- [Easy](/wiki/Game_modifier/Easy): Réduit de moitié la valeur de l'OD.
```suggestion
- [Easy](/wiki/Game_modifier/Easy) : Réduit de moitié la valeur de l'OD.
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- [Hard Rock](/wiki/Game_modifier/Hard_Rock):  Multiplie la valeur de l'OD par 1,4, jusqu'à un maximum de 10.
```suggestion
- [Hard Rock](/wiki/Game_modifier/Hard_Rock) : Multiplie la valeur de l'OD par 1,4, jusqu'à un maximum de 10.
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- [Double Time](/wiki/Game_modifier/Double_Time): La valeur de l'OD n'est pas affectée, mais en raison de l'augmentation de 50 % de la vitesse de jeu, les hit windows sont 33% plus courtes.
```suggestion
- [Double Time](/wiki/Game_modifier/Double_Time ): La valeur de l'OD n'est pas affectée, mais en raison de l'augmentation de 50 % de la vitesse de jeu, les hit windows sont 33% plus courtes.
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- [Half Time](/wiki/Game_modifier/Half_Time): La valeur de l'OD n'est pas affectée, mais en raison de la diminution de 25 % de la vitesse de jeu, les hit windows sont 33% plus longues.
```suggestion
- [Half Time](/wiki/Game_modifier/Half_Time) : La valeur de l'OD n'est pas affectée, mais en raison de la diminution de 25 % de la vitesse de jeu, les hit windows sont 33% plus longues.
```

2021-05-12 15:15 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +L'OD est visible lors de l'affichage des informations de la beatmap osu!catch, mais elle n'affecte en rien le gameplay.
```suggestion
L'OD est visible lors de l'affichage des informations de la beatmap, mais elle n'affecte en rien le gameplay.
```

2021-05-12 16:13 UTC, Satsukel commented on wiki/Beatmapping/Health/fr.md
> +- Obtenir un 300 Arc-en-ciel, un 300, ou un 200 (de la plus grande à la plus petite valeur de vie récupérée)
J'avoue que celui-là j'hésite parce qu'en soit sur le wiki anglais c'est "rainbow 300" mais c'est vrai qu'on appelle ça des "max" donc à voir

2021-05-12 16:16 UTC, Satsukel commented on wiki/Beatmapping/Health/fr.md
> +- Maintenir une long note avec la bonne touche
J'aurai dû m'en douter mais ici le "long" c'était en anglais et je sais pas lequel est mieux entre "longue note" et "note longue"

2021-05-12 16:17 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- Obtenir un 300 Arc-en-ciel, un 300, ou un 200 (de la plus grande à la plus petite valeur de vie récupérée)
Ils appellent ça `rainbow 300` et parfois `300 MAX`, alors je dirait de mettre `300 MAX`, car j'ai peur qu'avec le rainbow, des gens ne comprennent pas qu'on parle des 300 MAX. Et en plus je crois que sur le jeu on parle bien de 300 MAX, pas de rainbow.

2021-05-12 16:18 UTC, DoryanR commented on wiki/Beatmapping/Health/fr.md
> +- Maintenir une long note avec la bonne touche
`longue note` fait plus français je trouve

2021-05-12 18:01 UTC, DoryanR requested changes

2021-05-12 18:01 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +L'overall difficulty affecte également les spinners, dans la mesure où il faut les faire tourner davantage pour remplir la jauge à temps. Dans le mode [osu!taiko](/wiki/Game_mode/osu!taiko), le dende
```suggestion
L'overall difficulty affecte également les spinners, dans la mesure où il faut les faire tourner davantage pour remplir la jauge à temps. Dans le mode [osu!taiko](/wiki/Game_mode/osu!taiko), le denden aura également besoin de plus de coups pour être complété. Le nombre de tours par minutes nécessaires pour compléter un spinner est défini par la formule suivante :
```

Tours par minutes non ?

2021-05-12 18:01 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +- [Double Time](/wiki/Game_modifier/Double_Time ): La valeur de l'OD n'est pas affectée, mais en raison de l'augmentation de 50 % de la vitesse de jeu, les hit windows sont 33% plus courtes.
```suggestion
- [Double Time](/wiki/Game_modifier/Double_Time) : La valeur de l'OD n'est pas affectée, mais en raison de l'augmentation de 50 % de la vitesse de jeu, les hit windows sont 33% plus courtes.
```

2021-05-12 18:01 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +Alors que le Half Time et le Double Time ne modifient pas la valeur de l'OD, la différence de vitesse y entraîne un changement dans les hit windows. Comme la mise à l'échelle est différente pour chaq
```suggestion
Alors que le Half Time *(HT)* et le Double Time *(DT)* ne modifient pas la valeur de l'OD, la différence de vitesse y entraîne un changement dans les hit windows. Comme la mise à l'échelle est différente pour chaque valeur de score, le DT fait que les intervalles pour 100 et 50 sont plus resserrés que d'habitude par rapport au 300, et le HT les fait devenir plus indulgents. 
```

2021-05-12 20:15 UTC, Satsukel commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +Des valeurs d'OD plus élevées signifient une hit window plus courte pour frapper les [objets](/wiki/Hit_Objects), à la fois en général et pour obtenir des scores élevés. La largeur de l'intervalle po
Pour moi hit window c'est mieux de laisser au féminin vu que window = fenêtre

2021-05-13 08:45 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +Des valeurs d'OD plus élevées signifient une hit window plus courte pour frapper les [objets](/wiki/Hit_Objects), à la fois en général et pour obtenir des scores élevés. La largeur de l'intervalle po
Exact

2021-05-13 09:07 UTC, DoryanR approved these changes

2021-05-13 16:23 UTC, DoryanR requested changes

2021-05-13 16:23 UTC, DoryanR commented on wiki/Beatmapping/Approach_rate/fr.md
> +Alors que le Half Time *(HT)* et le Double Time *(DT)* ne modifient pas la valeur de l'AR, la différence de vitesse y entraîne un changement notable. Les AR de HT/DT sont généralement désignés en fon
```suggestion
Alors que le les mods Half Time *(HT)* et le Double Time *(DT)* ne modifient pas la valeur de l'AR, la différence de vitesse y entraîne un changement notable. Les AR de HT/DT sont généralement désignés en fonction de leur valeur perçue. Par exemple, "AR8+DT" peut également être écrit "AR9.6".
```

2021-05-13 16:23 UTC, DoryanR commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +Alors que le Half Time *(HT)* et le Double Time *(DT)* ne modifient pas la valeur de l'OD, la différence de vitesse y entraîne un changement dans les hit windows. Comme la mise à l'échelle est différ
```suggestion
Alors que les mods Half Time *(HT)* et le Double Time *(DT)* ne modifient pas la valeur de l'OD, la différence de vitesse y entraîne un changement dans les hit windows. Comme la mise à l'échelle est différente pour chaque valeur de score, le DT fait que les intervalles pour 100 et 50 sont plus resserrés que d'habitude par rapport au 300, et le HT les fait devenir plus indulgents. 
```

2021-05-13 17:15 UTC, Satsukel commented on wiki/Beatmapping/Approach_rate/fr.md
> +Alors que le Half Time *(HT)* et le Double Time *(DT)* ne modifient pas la valeur de l'AR, la différence de vitesse y entraîne un changement notable. Les AR de HT/DT sont généralement désignés en fon
assez d'accord avec toi mais dans ce cas on enlève le "le" dans "et le Double Time" avec non ? Et pareil avec la deuxième suggestion

2021-05-13 17:15 UTC, DoryanR commented on wiki/Beatmapping/Approach_rate/fr.md
> +Alors que le Half Time *(HT)* et le Double Time *(DT)* ne modifient pas la valeur de l'AR, la différence de vitesse y entraîne un changement notable. Les AR de HT/DT sont généralement désignés en fon
Oui on peut l'enlever, je vais modif la suggestion

2021-05-14 14:57 UTC, DoryanR approved these changes

2021-05-17 14:49 UTC, TicClick approved these changes
I've combined your changes, but please follow these best practices in your future PRs:
- make [commits with meaningful descriptions](https://osu.ppy.sh/wiki/en/osu%21_wiki_Contribution_Guide/Common_Issues#someone-told-me-to-use-meaningful-commit-messages!);
- for a single logically scoped change, such as applying a review, make a single commit (`Apply review from <someone>` or so), as opposed to 10 small commits titled `Update Path/To/Article/en.md`

2021-05-17 14:50 UTC, merged