[ID] Add "How to resolve BSS issues" Article
ppy/osu-wiki pull request #5449
Opened 2021-05-12 16:01 UTC by mousesalt

https://osu.ppy.sh/wiki/en/Guides%2FBSS_Issues

2021-05-13 02:46 UTC, ZeroPyrozen requested changes

2021-05-13 02:46 UTC, ZeroPyrozen commented on wiki/Guides/BSS_Issues/id.md
> +   - Secara singkat dapat melalui [beatmap editor](/wiki/Beatmap_Editor) pada menu `File` lalu tekan `Open Song Folder`.
```suggestion
   - Secara singkat dapat melalui [beatmap editor](/wiki/Beatmap_Editor) pada menu `File` lalu pilih opsi `Open Song Folder`.
```

2021-05-13 02:46 UTC, ZeroPyrozen commented on wiki/Guides/BSS_Issues/id.md
> +4. Masukkan nama pengguna ke kotak `Creator`. (Gunakan spasi jika nama pengguna mempunyai spasi.)
```suggestion
4. Masukkan nama pengguna ke kotak `Creator`. (Jika nama Anda memiliki spasi, maka gunakan spasi.)
```

2021-05-13 05:25 UTC, ZeroPyrozen approved these changes
All good 👍

2021-05-16 15:09 UTC, TicClick approved these changes

2021-05-16 15:09 UTC, merged