[ID] Add "Summary" and "Spun out"
ppy/osu-wiki pull request #5452
Opened 2021-05-13 06:31 UTC by wowcake

2021-05-13 07:09 UTC, mousesalt requested changes

2021-05-13 07:09 UTC, mousesalt commented on wiki/Game_modifier/Spun_Out/id.md
> +- Mode-mode game yang cocok: ![][osu!]
```suggestion
- Mode permainan yang cocok: ![][osu!]
```

2021-05-19 12:46 UTC, mousesalt approved these changes

2021-05-19 19:27 UTC, TicClick approved these changes

2021-05-19 19:27 UTC, merged