[ID] Add "xK" and "Sudden Death"
ppy/osu-wiki pull request #5453
Opened 2021-05-13 06:33 UTC by wowcake

2021-05-13 07:19 UTC, mousesalt commented on wiki/Game_modifier/Sudden_Death/id.md
> +- Mode-mode game yang cocok: ![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania]
```suggestion
- Mode-mode permainan yang cocok: ![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania]
```

2021-05-13 07:19 UTC, mousesalt commented on wiki/Game_modifier/Sudden_Death/id.md
> +Mod **Sudden Death** adalah sebuah [game modifier](/wiki/Game_modifier) yang akan membuat pemain gagal dalam sebuah [beatmap](/wiki/Beatmap) ketika meleset dalam mengenai sebuah [hit object](/wiki/Hi
```suggestion
Mod **Sudden Death** adalah sebuah [game modifier](/wiki/Game_modifier) yang akan membuat pemain gagal dalam sebuah [beatmap](/wiki/Beatmap) ketika meleset dalam mengenai sebuah [hit object](/wiki/Hit_Objects) atau gagal untuk mengumpulkan sebuah slidertick, atau pemain memperoleh miss di dalam permainan. Mod ini sangat berguna bagi pemain yang ingin mendapatkan [full combo (FC)](/wiki/Glossary#fc). Meskipun ada beberapa perdebatan tentang apakah penggunaan Sudden Death atau tindakan untuk percobaan ulang pada poin [combo break](/wiki/Glossary#combobreak) pertama dapat membantu atau tidak, baik bagi pemain yang ingin meningkatkan skillnya dengan cepat.
```

2021-05-13 07:19 UTC, mousesalt commented on wiki/Game_modifier/Sudden_Death/id.md
> +- Tidak menahan /mengumpulkan pada jalur kosong slider.
```suggestion
- Tidak menahan/mengumpulkan pada jalur kosong slider.
```

2021-05-13 07:19 UTC, mousesalt commented on wiki/Game_modifier/Sudden_Death/id.md
> +Tidak seperti variasi dari Sudden Death, [Perfect](/wiki/Game_modifier/Perfect), Beatmap tidak akan diulangi secara otomatis. Pemain hanya akan diberikan layar fail yang biasa saat meleset dalam meng
```suggestion
Tidak seperti variasi dari Sudden Death, mod [Perfect](/wiki/Game_modifier/Perfect) tidak akan mengulangi permainan secara otomatis. Pemain hanya akan diberikan layar fail yang biasa saat meleset dalam mengenai sebuah not.
```

2021-05-13 07:19 UTC, mousesalt commented on wiki/Game_modifier/xK/id.md
> +- Mode-mode game yang cocok: ![][osu!mania]
```suggestion
- Mode permainan yang cocok: ![][osu!mania]
```

2021-05-24 19:10 UTC, DoryanR requested changes

2021-05-24 19:10 UTC, DoryanR commented on wiki/Game_modifier/Sudden_Death/id.md
> +Mod **Sudden Death** adalah sebuah [game modifier](/wiki/Game_modifier) yang akan membuat pemain gagal dalam sebuah [beatmap](/wiki/Beatmap) ketika meleset dalam mengenai sebuah [hit object](/wiki/Hi
```suggestion
Mod **Sudden Death** adalah sebuah [game modifier](/wiki/Game_modifier) yang akan membuat pemain gagal dalam sebuah [beatmap](/wiki/Beatmap) ketika meleset dalam mengenai sebuah [hit object](/wiki/Hit_Objects) atau gagal untuk mengumpulkan sebuah slidertick, atau pemain memperoleh miss di dalam permainan. Mod ini sangat berguna bagi pemain yang ingin mendapatkan [full combo (FC)](/wiki/Full_combo). Meskipun ada beberapa perdebatan tentang apakah penggunaan Sudden Death atau tindakan untuk percobaan ulang pada poin [combo break](/wiki/Glossary/Combobreak) pertama dapat membantu atau tidak, baik bagi pemain yang ingin meningkatkan skillnya dengan cepat.
```

2021-05-30 05:58 UTC, mousesalt approved these changes

2021-06-13 22:37 UTC, TicClick approved these changes

2021-06-13 22:37 UTC, merged