[ID] Update IRC
ppy/osu-wiki pull request #5461
Opened 2021-05-13 13:46 UTC by Fhoxydeo

reupload from : https://github.com/ppy/osu-wiki/pull/5275

2021-05-14 09:52 UTC, mousesalt reviewed
should be fine after this

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
>  [Internet Relay Chat](https://id.wikipedia.org/wiki/IRC), dikenal juga sebagai IRC, adalah sebuah protokol standar yang sering digunakan untuk mengobrol dengan banyak pengguna lain yang tersedia.
```suggestion
**Internet Relay Chat**, dikenal juga sebagai IRC, adalah sebuah protokol standar yang sering digunakan untuk mengobrol dengan banyak pengguna lain yang tersedia.
```

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +*Catatan: server ini hanya menyediakan sebagian penerapan dari protokol IRC. beberapa fitur tak berdasar seperti [HexChat](https://hexchat.github.io/) mungkin tidak bekerja dengan baik atau tidak sam
```suggestion
*Catatan: server ini hanya menyediakan sebagian penerapan dari protokol IRC. Beberapa fitur pada client IRC yang tak berdasar seperti di [HexChat](https://hexchat.github.io) mungkin tidak bekerja dengan baik atau tidak sama sekali.*
```

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +*Catatan: Kata sandi IRC Anda berbeda dengan kata sandi akun osu! Anda. **Jangan dibagikan kepada orang lain**.*
```suggestion
*Peringatan: Kata sandi IRC Anda berbeda dengan kata sandi akun osu! Anda. ***Jangan dibagikan kepada orang lain***.
```

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +*Catatan: Kata sandi IRC Anda berbeda dengan kata sandi akun osu! Anda. **Jangan dibagikan kepada orang lain**.*
next time please using **warning** translation as bolding sentence instead

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +Pada dasarnya, beberapa klien IRC memberitahumu ketika pengguna bergabung atau pergi meninggalkan kanal. Untuk jaringan seperti osu!Bancho dengan ribuan pengguna yang sering bergabung dan pergi, pesa
```suggestion
Pada dasarnya, beberapa klien IRC memberitahumu ketika seorang pengguna bergabung atau meninggalkan kanal. Untuk jaringan seperti osu!Bancho dengan ribuan pengguna yang sering bergabung dan pergi, pesan semacam itu menjadi spam, yang mungkin ingin Anda sembunyikan. Beberapa daftar klien IRC yang umum dan cara menonaktifkan pesan tersebut dijelaskan di bawah ini:
```

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +## Pertanyaan yang sering diajukan
```suggestion
## Pertanyaan yang sering diajukan (FAQ)
```

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +## Pertanyaan yang sering diajukan
we still using FAQ btw

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +osu!Bancho menggunakan otentikasi teks biasa - pastikan tidak ada mode otentikasi khusus yang dipilih dalam pengaturan klien IRC Anda.
```suggestion
osu!Bancho menggunakan otentikasi *plain text* - pastikan tidak ada mode otentikasi khusus yang dipilih dalam pengaturan klien IRC Anda.
```

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +osu!Bancho menggunakan otentikasi teks biasa - pastikan tidak ada mode otentikasi khusus yang dipilih dalam pengaturan klien IRC Anda.
dont even know what is teks biasa while commonly use to plain text.

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +2. Jika nama penggunamu menggunakan spasi, gantilah dengan garis bawah (contoh: `This Username` menjadi `This_Username`).
```suggestion
2. Jika nama pengguna Anda menggunakan spasi, gantilah dengan garis bawah (contoh: `Username ini` menjadi `Username_ini`).
```

2021-05-14 09:52 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> +- `@`, or "chat operator status": pengguna adalah seorang moderator ([GMT](/wiki/GMT) atau [NAT](/wiki/NAT))
```suggestion
- `@`, atau "chat operator status": pengguna adalah seorang moderator ([GMT](/wiki/GMT) atau [NAT](/wiki/NAT))
```

2021-05-15 12:32 UTC, wowcake requested changes

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +*osu!Bancho* (sering disingkat menjadi *Bancho*) menawarkan untuk mengakses IRC (in-game chat). Anda dapat menggunakan klien IRC apa pun untuk terhubung ke osu!Bancho (lihat daftar IRC di bawah yang
```suggestion
*osu!Bancho* (sering disingkat menjadi *Bancho*) menawarkan untuk mengakses IRC (in-game chat). Anda dapat menggunakan klien IRC apapun untuk terhubung ke osu!Bancho (lihat daftar IRC di bawah yang paling umum digunakan).
```

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +*osu!Bancho* (sering disingkat menjadi *Bancho*) menawarkan untuk mengakses IRC (in-game chat). Anda dapat menggunakan klien IRC apa pun untuk terhubung ke osu!Bancho (lihat daftar IRC di bawah yang
according to kkbi
https://kbbi.web.id/apapun

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +Setelah Anda memiliki klien, Anda perlu mengatur pengaturan server (Anda mungkin perlu untuk menambah server dahulu) .
```suggestion
Setelah Anda memiliki sebuah klien IRC, Anda perlu mengatur pengaturan server (Anda mungkin perlu untuk menambah server dahulu).
```

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +Setelah Anda memiliki klien, Anda perlu mengatur pengaturan server (Anda mungkin perlu untuk menambah server dahulu) .
make things clearer things a bit

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +- **Username:** Nama pengguna osu! Anda, contoh (`beppy master 1000` menjadi `beppy_master_1000`)
```suggestion
- **Username:** Nama pengguna osu! Anda. (ganti spasi dengan garis bawah, contoh `beppy master 1000` menjadi `beppy_master_1000`)
```

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +- **Username:** Nama pengguna osu! Anda, contoh (`beppy master 1000` menjadi `beppy_master_1000`)
what happened to the part where it explains regarding name with underscore?

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +Pengguna yang terhubung melalui klien osu! atau website tidak mempunyai prefix.
```suggestion
Pengguna yang terhubung melalui klien osu! atau website tidak akan mempunyai prefix.
```

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +Pengguna yang terhubung melalui klien osu! atau website tidak mempunyai prefix.
readers could misread it just as "website tidak mempunyai prefix"

2021-05-15 12:32 UTC, wowcake commented on wiki/Internet_Relay_Chat/id.md
> +Mereka menggunakan [versi web chat](https://osu.ppy.sh/community/chat) atau terhubung via [osu!lazer](https://github.com/ppy/osu "GitHub").
```suggestion
Mereka menggunakan [versi web chat](https://osu.ppy.sh/community/chat) atau terhubung melalui klien [osu!lazer](https://github.com/ppy/osu "GitHub").
```

2021-05-21 09:36 UTC, mousesalt commented on wiki/Internet_Relay_Chat/id.md
> -*osu!Bancho* (sering disingkat menjadi *Bancho*) menawarkan untuk mengakses IRC (in-game chat). Anda dapat menggunakan klien IRC apa pun untuk terhubung ke osu!Bancho (lihat daftar IRC di bawah yang
this actually correct grammar, no need to change it.

2021-05-21 09:39 UTC, mousesalt approved these changes
overall looks good :+1

2021-05-21 15:32 UTC, TicClick approved these changes

2021-05-21 15:32 UTC, merged