[FR] Beatmap editor articles (part 3)
ppy/osu-wiki pull request #5464
Opened 2021-05-13 16:53 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Beatmap_Editor/Menu`
- `Beatmap_Editor/Song_Setup`

Also : 

- Addition of the French images for the article `Menu`

2021-05-14 18:27 UTC, DoryanR commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Tester la beatmap (F5) | Testez la beatmap. Les modifications actuelles seront sauvegardées afin de pouvoir la tester. |
```suggestion
| Tester la beatmap (`F5`) | Testez la beatmap. Les modifications actuelles seront sauvegardées afin de pouvoir la tester. |
```

2021-05-14 19:36 UTC, Satsukel requested changes

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Dim Background | Affiche le son des touches attaché aux notes. Très utile dans osu!mania. |
```suggestion
| Afficher le nom des bruitages | Affiche le son des touches attaché aux notes. Très utile dans osu!mania. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Sliders progressifs | Animez les sliders comme si vous jouiez dans le jeu. |
```suggestion
| Sliders progressifs | Anime les sliders comme si vous jouiez dans le jeu. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Animation des élements comme dans le jeu | Animez les cercles comme s'ils étaient cliqués (lorsque l'horodateur passe le cercle) dans le jeu. |
```suggestion
| Animation des élements comme dans le jeu | Anime les cercles comme s'ils étaient cliqués (lorsque l'horodateur passe le cercle) dans le jeu. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| "Follow points" | Affichez (et animez) les follow points comme dans le jeu. |
```suggestion
| "Follow points" | Affiche (et anime) les follow points comme dans le jeu. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Empilage des notes | Stack the overlaid hitcircles as if in-game (dependent on difficulty settings) |
```suggestion
| Empilage des notes | Empile les cercles superposés comme si vous étiez en jeu (en fonction des paramètres de difficulté). |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Insérer des notes en cercle... (`Ctrl` + `Shift` + `D`) | Créez un flow circulaire de cercles. Vous pouvez ajuster le Distance Snap (0.1x - 2.0x) {Espacement entre les notes}, l'angle Offset (0° -
```suggestion
| Insérer des notes en cercle... (`Ctrl` + `Shift` + `D`) | Crée un flow circulaire de cercles. Vous pouvez ajuster la Distance Snap (0.1x - 2.0x) {Espacement entre les notes}, l'angle Offset (0° - 180°) {Angle de rotation}, la répétition et les points (3 - 14/282) {Nombre de cercles}. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Convertir un slider en stream... | (Sélectionnez un slider) Changez le curseur en flow de cercles. Vous pouvez choisir entre deux options : Par nombre d'objets ou Par distance instantanée. **Par no
```suggestion
| Convertir un slider en stream... | (Sélectionnez un slider) Change le curseur en flow de cercles. Vous pouvez choisir entre deux options : Par nombre d'objets ou Par distance instantanée. **Par nombre d'objets :** Ajustez le slider flow avec la quantité donnée de cercles (1 - 17/100). **Par la distance instantanée :** Ajuste le slider flow avec une distance donnée entre deux notes (0.10x - 5.00x). Peut résulter en une quantité absurde de cercles, puisqu'il s'appuie sur le diviseur de mesure (un temps = une note). **Beat Snap Divisor :** Ajusteur de timing des notes. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Activer le live mapping (`Ctrl` + Tab) | Maps osu!/osu!catch/osu!taiko : utilisez les touches osu!taiko pour saisir des cercles/fruit/taiko, tout en jouant le morceau dans l'éditeur. Placé par l'em
Difficile cette partie car je pense qu'il faut s'éloigner un peu de la version originale pour que ça ait du sens en français.
```suggestion
| Activer le live mapping (`Ctrl` + Tab) | Maps osu!/osu!catch/osu!taiko : utilisez les touches osu!taiko pour saisir des cercles/fruit/taiko, tout en jouant le morceau dans l'éditeur. Les notes sont placées selon l'emplacement du curseur. Différents sons en fonction de la touche osu!taiko sur laquelle vous avez appuyée. maps osu!mania : utilisez les touches osu!mania pour placer des cercles, tout en jouant un morceau dans l'éditeur. La note est placée selon la touche sur laquelle vous avez appuyée. Ne fonctionne pas pour les sliders/holds. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Métronome | Autoriser/refuser le son "tic, tic, (tic) , toc" du métronome. |
```suggestion
| Métronome | Active/désactive le son "tic, tic, (tic) , toc" du métronome. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Ajouter une section temporelle (`Ctrl` + `P`) | Ajouter un décalage rouge (Nouveau BPM) |
```suggestion
| Ajouter une section temporelle (`Ctrl` + `P`) | Ajoute un décalage rouge (Nouveau BPM) |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Ajouter une section héritée (`Ctrl` + `Shift` + `P`) | Ajout d'un décalage vert (Nouvel ajusteur) |
```suggestion
| Ajouter une section héritée (`Ctrl` + `Shift` + `P`) | Ajoute un décalage vert (Nouvel ajusteur) |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Réinitialiser la section actuelle  | Supprimez tout les élements de la section actuelle |
```suggestion
| Réinitialiser la section actuelle  | Supprime tous les élements de la section actuelle |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Supprime la section (`Ctrl` + `I`) | Supprimer le décalage rouge/vert (supprimer un avant la double ligne) |
```suggestion
| Supprime la section (`Ctrl` + `I`) | Supprime le décalage rouge/vert (supprime un avant la double ligne) |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Repositionner les élements de la section actuelle | Repositionnez la section actuelle avec le nouveau timing actuel. |
```suggestion
| Repositionner les élements de la section actuelle | Repositionne la section actuelle avec le nouveau timing. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Repositionner tous les élements | Repositionnez toutes les notes à leurs sections respectives. |
```suggestion
| Repositionner tous les élements | Repositionne toutes les notes à leurs sections respectives. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Déplacer tout les élements de... | Déplacer toutes les notes par #ms |
```suggestion
| Déplacer tout les élements de... | Déplace toutes les notes par #ms |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Recalculer la longueur des sliders | Laissez osu! recalculer la longueur des sliders. (Il est préférable de l'utiliser si le bpm/la vitesse du curseur/le multiplicateur de vitesse du curseur a chan
```suggestion
| Recalculer la longueur des sliders | Fait recalculer la longueur des sliders à osu!. (Il est préférable de l'utiliser si le bpm/la vitesse du slider/le multiplicateur de vitesse du slider a changé.) **Attention :** Faire cela peut raccourcir la longueur de tous les sliders ! Vérifiez votre map après utilisation ! |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Supprimer toutes les sections temporelles | Purgez le timing |
```suggestion
| Supprimer toutes les sections temporelles | Purge le timing |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Définir le point de prévisualisation à la position actuelle | Définir ce timestamp comme marque jaune (extrait de démonstration pour Song Selection). |
```suggestion
| Définir le point de prévisualisation à la position actuelle | Définit ce timestamp comme marque jaune (extrait de démonstration pour Song Selection). |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Page web de la beatmap | Allez à la page d'information de cette beatmap. Le lien est `https://osu.ppy.sh/beatmapsets/###` où "###" est l'ID de la beatmap. |
```suggestion
| Page web de la beatmap | Ouvre la page d'information de cette beatmap. Le lien est `https://osu.ppy.sh/beatmapsets/###` où "###" est l'ID de la beatmap. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Topic de la beatmap | Allez sur le fil de discussion de la beatmap |
```suggestion
| Topic de la beatmap | Ouvre le fil de discussion de la beatmap |
| Réponse rapide | Poste une réponse au fil de discussion beatmap. |
```

2021-05-14 19:36 UTC, Satsukel commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Ouvrir la FAQ... | Liens vers [Beatmapping](/wiki/Beatmapping). |
Pas sûr de celui-là mais normalement ça devrait être ça
```suggestion
| Ouvrir la FAQ... | Ouvre [Beatmapping](/wiki/Beatmapping). |
```

2021-05-17 17:39 UTC, Satsukel requested changes

2021-05-17 17:39 UTC, Satsukel commented on wiki/Beatmap_Editor/Song_Setup/fr.md
> +Configuration pour les hitsounds. Cependant, en utilisant les sections [timing](/wiki/Beatmap_Editor/Timing) (`F6`), le créateur peut changer les deux ensembles de hitsounds ou le volume individuelle
Je trouvais qu'"à travers" ça fait bizarre même si théoriquement ça ressemble plus à la version originale, à toi de voir
```suggestion
Configuration pour les hitsounds. Cependant, en utilisant les sections [timing](/wiki/Beatmap_Editor/Timing) (`F6`), le créateur peut changer les deux ensembles de hitsounds ou le volume individuellement grâce à des points de timing. Les sections `Sample Set Selection` et `Sample Set Volume` seront inaccessibles si des ajustements de volume sensibles au timing sont utilisés dans la beatmap. Cliquer sur le bouton `Reset Settings` supprimera tous les ajustements de volume personnalisés.
```

2021-05-17 17:39 UTC, Satsukel commented on wiki/Beatmap_Editor/Song_Setup/fr.md
> +Configurez les couleurs des combinaisons et la couleur de fond du terrain de jeu.
```suggestion
Configurez les couleurs des combos et la couleur de fond du terrain de jeu.
```

2021-05-17 17:39 UTC, Satsukel commented on wiki/Beatmap_Editor/Song_Setup/fr.md
> +La liste déroulante `Preferred Skin` est utilisée pour définir le skin préférée pour la beatmap. L'utilisation de cette option suppose que le joueur possède le skin que vous souhaitez qu'il utilise.
```suggestion
La liste déroulante `Preferred Skin` est utilisée pour définir le skin préféré pour la beatmap. L'utilisation de cette option suppose que le joueur possède le skin que vous souhaitez qu'il utilise. Cependant, si le joueur n'a pas le skin, une notification apparaîtra pour le joueur, indiquant que le skin demandé est manquant, mais que le skin actuel du joueur sera utilisé à la place. Par défaut, `User's preference (No Change)` est utilisé.
```

2021-05-17 17:39 UTC, Satsukel commented on wiki/Beatmap_Editor/Song_Setup/fr.md
> +![Cependant, pendant le jeu, le jeu les inclinera pour le joueur.](img/stacking-playtest.jpg "Objets empilés frappés pendant le jeu")
```suggestion
![Cependant, pendant la partie, le jeu les inclinera pour le joueur.](img/stacking-playtest.jpg "Objets empilés frappés pendant le jeu")
```

2021-05-17 17:39 UTC, Satsukel commented on wiki/Beatmap_Editor/Song_Setup/fr.md
> +`Allowed Modes` est une liste déroulante pour confirmer que la beatmap ne peut être joué que par le mode spécifié. Le paramètre par défaut est `All`, ce qui signifie que le créateur créera une beatma
```suggestion
`Allowed Modes` est une liste déroulante pour confirmer que la beatmap ne peut être jouée que par le mode spécifié. Le paramètre par défaut est `All`, ce qui signifie que le créateur créera une beatmap du mode osu! qui pourra être converti dans les autres modes de jeu. Ce paramètre peut être modifié pour être spécifique à osu!taiko, osu!catch, ou osu!mania ; mais **gardez à l'esprit que ce changement supprimera tous les objets dans la beatmap**.
```

2021-05-18 19:35 UTC, DoryanR commented on wiki/Beatmap_Editor/Song_Setup/fr.md
> +- [Hard Rock](/wiki/Game_modifier/Hard_Rock) :  Multiplie la valeur AR par 1,40, jusqu'à un maximum de AR10. (par exemple, AR3→AR4.2 ou AR9→AR10)
```suggestion
- [Hard Rock](/wiki/Game_modifier/Hard_Rock) :  Multiplie la valeur d'AR par 1,40, jusqu'à AR10 au maximum. (par exemple, on passe de AR3 à AR4.2 ou de AR9 à AR10)
```

2021-05-18 19:37 UTC, DoryanR commented on wiki/Beatmap_Editor/Menu/fr.md
> +| Publier la beatmap... (`Ctrl` + `Shift` + `U`) | Télécharge la beatmap dans la section [WIP](https://osu.ppy.sh/community/forums/10). Nécessite un osu!account connecté au site pour voir le forum "B
```suggestion
| Publier la beatmap... (`Ctrl` + `Shift` + `U`) | Télécharge la beatmap dans la section [WIP](https://osu.ppy.sh/community/forums/10). Nécessite un osu!account connecté au site pour voir le forum "Beatmaps". |
```

2021-05-18 19:37 UTC, DoryanR commented on wiki/Beatmap_Editor/Song_Setup/fr.md
> +- L'onglet `Design` était auparavant appelé "Storyboarding"..
```suggestion
- L'onglet `Design` était auparavant appelé "Storyboarding".
```

2021-05-18 20:00 UTC, Satsukel approved these changes

2021-05-21 16:30 UTC, TicClick commented
is this good to go?

2021-05-21 16:31 UTC, DoryanR commented
Yes

2021-05-21 16:55 UTC, TicClick commented on wiki/Beatmap_Editor/Menu/en.md
> -| Set Current Position as Preview Point | Set this timestamp as yellow mark (demo excerpt for Song Selection). |
to except is omit; an excerpt is a short extract

2021-05-21 16:57 UTC, TicClick approved these changes

2021-05-21 16:58 UTC, merged