[FR] Beatmap editor articles (part 4)
ppy/osu-wiki pull request #5473
Opened 2021-05-14 18:40 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Beatmap_Editor/Timelines`
- `Beatmap_Editor/Timing`

Also:

- Addition of the French images for both articles
- Update images in `Beatmap_Editor/Timing`, and fix links in othens articles.

This PR is the last part of the other PRs concerning beatmap editor.

2021-05-15 22:10 UTC, AirOne01 submitted a review, later dismissed
Ok ! 👍

2021-05-17 20:41 UTC, Satsukel requested changes

2021-05-17 20:41 UTC, Satsukel commented on wiki/Beatmap_Editor/Timing/fr.md
> +*Voir aussi : [How to time songs](/wiki/Guides/How_to_Time_Songs)*
Il faut une traduction pour  les crochets mais j'ai pas d'autre traduction qui me vient à l'esprit à part remplacer "synchroniser" par "timer".
```suggestion
*Voir aussi : [Comment synchroniser les musiques](/wiki/Guides/How_to_Time_Songs)*
```

2021-05-17 20:41 UTC, Satsukel commented on wiki/Beatmap_Editor/Timing/fr.md
> +Les points de timing peuvent être ajoutés à partir de la fenêtre `Timing and Control Points` de l'éditeur (raccourci par défaut `F6`). Les points de synchronisation divisent un morceau en sections de
Est-ce que points de timing = points de synchronisation ? Si oui, autant choisir une forme et tout unifier pour éviter toute confusion.

2021-05-18 19:40 UTC, DoryanR commented on wiki/Beatmap_Editor/Timing/fr.md
> +Les points de timing peuvent être ajoutés à partir de la fenêtre `Timing and Control Points` de l'éditeur (raccourci par défaut `F6`). Les points de synchronisation divisent un morceau en sections de
```suggestion
Les points de timing peuvent être ajoutés à partir de la fenêtre `Timing and Control Points` de l'éditeur (raccourci par défaut `F6`). Les points de timing divisent un morceau en sections de synchronisation pour refléter précisément les changements de timing d'un morceau.
```

2021-05-18 19:59 UTC, Satsukel approved these changes

2021-05-21 18:19 UTC, TicClick approved these changes
I've reverted `Timing_base.jpg` and its French version back to JPEG, as it shaves ~500kb off the article and does not harm the quality

2021-05-21 18:20 UTC, merged

2021-05-21 18:20 UTC, DoryanR commented
> I've reverted `Timing_base.jpg` and its French version back to JPEG, as it shaves ~500kb off the article and does not harm the quality

Ok no problem