[FR] Account support team
ppy/osu-wiki pull request #5480
Opened 2021-05-16 11:05 UTC by Ganondorfosu

French translation of osu! wiki - Account support team

2021-05-16 12:20 UTC, DoryanR requested changes

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +*Pour une équipe qui modère certains sous-forums, voir: [Équipe du support](/wiki/People/The_Team/Support_Team)*
```suggestion
*Pour l'équipe qui modère certains sous-forums, voir : [Équipe du support](/wiki/People/The_Team/Support_Team)*
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +**L'équipe de support aux comptes** est un groupe d'utilisateurs administrant les comptes utilisateurs et les appels concernant les silences et les restrictions.
```suggestion
L'**équipe de support aux comptes** est un groupe d'utilisateurs administrant les comptes utilisateurs et les demandes appels concernant les silences et les restrictions.
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +Cela prend habituellement quelques jours avant que l'équipe arrive à votre mail. Si vous ne recevez pas de réponse en moins d'une semaine, vous pouvez renvoyer un message sous le premier.
```suggestion
Cela prend habituellement quelques jours avant que l'équipe prête attention à votre mail. Si vous ne recevez pas de réponse en moins d'une semaine, vous pouvez renvoyer un message sous le premier.
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +*Article principal: [Centre d'Aide](/wiki/Help_Centre)*
```suggestion
*Page principale : [Centre d'aide](/wiki/Help_Centre)*
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +*Voir également: [Restriction de comptes](/wiki/Help_Centre/Account_Restrictions)*
```suggestion
*Voir également : [Restriction de comptes](/wiki/Help_Centre/Account_Restrictions)*
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +- [Appel concernant les restrictions placées sur votre compte](/wiki/Help_Centre/Account_Restrictions), incluant:
```suggestion
- [Appel concernant les restrictions placées sur votre compte](/wiki/Help_Centre/Account_Restrictions), incluant :
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +  - Les suppressions de posts forum et commentaires.
```suggestion
  - Les suppressions de posts sur le forum et commentaires.
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +- De la mauvaise conduite que vous [souhaitez admettre](/wiki/Reporting_Bad_Behaviour/Handling_Foul_Play#what-can-i-do-if-i've-broken-the-rules?).
```suggestion
- De la mauvaise conduite que vous [souhaitez avouer](/wiki/Reporting_Bad_Behaviour/Handling_Foul_Play#what-can-i-do-if-i've-broken-the-rules?).
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +*Note: Pour signaler un cas extrême de mauvaise conduite ou d'abus sexuel de n'importe quel utilisateur (modérateur inclus), voir [Signaler un abus](/wiki/Reporting_Bad_Behaviour/Abuse).*
```suggestion
*Note : Pour signaler un cas extrême de mauvaise conduite ou d'abus sexuel de n'importe quel utilisateur (modérateur inclus), voir : [Signaler un abus](/wiki/Reporting_Bad_Behaviour/Abuse).*
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +- [Problèmes de paiement](/wiki/en/Help_Centre#supporter) pour les commandes du [osu!store](https://osu.ppy.sh/store/listing).
```suggestion
- [Problèmes de paiement](/wiki/en/Help_Centre#supporter) pour les commandes concernant l'[osu!store](https://osu.ppy.sh/store/listing).
```

2021-05-16 12:20 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +- [Requêtes de suppression de compte](/wiki/Legal/Privacy#your-rights-and-control) **permanente** pour les utilisateurs résidant dans l'UE ([RGPD](https://fr.wikipedia.org/wiki/Règlement_général_sur_
```suggestion
- [Requêtes de suppression de compte](/wiki/Legal/Privacy#your-rights-and-control) **permanente** pour les utilisateurs résidant dans l'Union Européenne ([RGPD](https://fr.wikipedia.org/wiki/Règlement_général_sur_la_protection_des_données "Wikipédia")).
```

2021-05-22 10:07 UTC, DoryanR requested changes

2021-05-22 10:07 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +Vous devriez contacter cette équipe pour les sujets concernant votre compte qui sont hors de votre contrôle. Veuillez fournir le plus de contexte possible sur votre problème et envoyer un mail à l'ad
```suggestion
Vous devriez contacter cette équipe pour les sujets concernant votre compte qui sont hors de votre contrôle. Veuillez fournir le plus de détails possible sur votre problème et envoyer un mail à l'adresse associée à votre problème.
```

2021-05-22 10:07 UTC, DoryanR commented on wiki/People/The_Team/Account_support_team/fr.md
> +*Note : Pour signaler un cas extrême de mauvaise conduite ou d'abus sexuel de n'importe quel utilisateur (modérateur inclus), voir : [Signaler un abus](/wiki/Reporting_Bad_Behaviour/Abuse).*
```suggestion
*Remarque : Pour signaler un cas extrême de mauvaise conduite ou d'abus sexuel de n'importe quel utilisateur (modérateur inclus), voir : [Signaler un abus](/wiki/Reporting_Bad_Behaviour/Abuse).*
```

2021-05-23 10:49 UTC, DoryanR approved these changes

2021-05-25 13:28 UTC, TicClick approved these changes

2021-05-25 13:28 UTC, merged