[ID] Add "Article styling criteria"
ppy/osu-wiki pull request #5483
Opened 2021-05-16 17:30 UTC by mousesalt

Add Indonesia translation for **[Article styling criteria](https://osu.ppy.sh/wiki/en/Article_styling_criteria)**.

2021-05-17 05:17 UTC, ZeroPyrozen requested changes
Everything else looks good just need 1 change. I had to checked if "Article styling criteria" translation is ambiguous but it doesn't since "Wikipedia style guidelines" translated into "Pedoman gaya Wikipedia".

2021-05-17 05:17 UTC, ZeroPyrozen commented on wiki/Article_styling_criteria/id.md
> +  - wiki standar
```suggestion
  - standar wiki
```

2021-05-17 06:37 UTC, ZeroPyrozen approved these changes

2021-05-24 04:41 UTC, wowcake approved these changes

2021-05-25 13:29 UTC, TicClick approved these changes

2021-05-25 13:29 UTC, merged