Update "Beatmap Spotlights"
ppy/osu-wiki pull request #5487
Opened 2021-05-17 06:24 UTC by mousesalt

Update Indonesian translation for **[Beatmap Spotlights](https://osu.ppy.sh/wiki/en/Beatmap_Spotlights)**.

2021-05-17 16:20 UTC, ZeroPyrozen requested changes

2021-05-17 16:20 UTC, ZeroPyrozen commented on wiki/Beatmap_Spotlights/id.md
> +**Program Beatmap Spotlights saat ini masih berjalan dalam tahapan uji coba dan masih terdapat berbagai fitur yang belum sepenuhnya diimplementasikan.** Sistem-sistem spesifik seperti perhargaan, pap
```suggestion
**Program Beatmap Spotlights saat ini masih berjalan dalam tahapan uji coba dan masih terdapat berbagai fitur yang belum sepenuhnya diimplementasikan.** Seluk-beluk dari sistem ini seperti penghargaan, papan peringkat musiman, dan fitur-fitur permainan lainnya masih bersifat tentatif dan dapat berubah kapan saja.
```

2021-05-17 16:20 UTC, ZeroPyrozen commented on wiki/Beatmap_Spotlights/id.md
> +**Beatmap Spotlights** (dikenal juga sebagai *Spotlights* atau *Ranking Charts*) adalah sebuah program kurasi berulang untuk merekomendasikan dan menyoroti [beatmap](/wiki/Beatmap) karena desain dan
```suggestion
**Beatmap Spotlights** (dikenal juga sebagai *Spotlights* atau *Ranking Charts*) adalah sebuah program kurasi berulang untuk merekomendasikan dan menyoroti [beatmap](/wiki/Beatmap) karena desain dan permainannya yang luar biasa dan unik. Spotlights disertai dengan [liga musiman](#musim-spotlights) yang mana akan memberi penghargaan kepada seluruh pemain yang turut berpartisipasi.
```

2021-05-18 08:52 UTC, ZeroPyrozen approved these changes
Looks good 👍

2021-05-21 16:00 UTC, TicClick approved these changes

2021-05-21 16:01 UTC, merged