Rule change - Monthly nomination cap per Beatmap Nominator
ppy/osu-wiki pull request #5501
Opened 2021-05-19 07:11 UTC by NoffyNoffeh

This would be posted + announced additionally when / if merged. In depth reasoning for the rule change can be found on https://github.com/ppy/osu-web/issues/7621 .
Would like feedback on if this is a clear way to format + easy to understand.

Please review but don't merge just yet. Thank you.

2021-05-19 07:27 UTC, Walavouchey commented on wiki/People/The_Team/Beatmap_Nominators/Rules/en.md
> +- **Beatmap Nominators can not exceed 20 unique nominations per month, on a calendar month basis.** Nominators exceeding this amount will first be warned and then removed if they do not manage their
Sounds like a tautology

```suggestion
- **Beatmap Nominators can not exceed 20 unique nominations per calendar month.** Nominators exceeding this amount will first be warned and then removed if they do not manage their activity accordingly.
```

2021-05-19 09:20 UTC, cl8n requested changes

2021-05-19 09:20 UTC, cl8n commented on wiki/People/The_Team/Beatmap_Nominators/Rules/en.md
> +- **Beatmap Nominators can not exceed 20 unique nominations per calendar month.** Nominators exceeding this amount will first be warned and then removed if they do not manage their activity according
"can not" => "cannot"

2021-05-19 09:20 UTC, cl8n commented on wiki/People/The_Team/Beatmap_Nominators/Rules/en.md
> +- **Beatmap Nominators can not exceed 20 unique nominations per calendar month.** Nominators exceeding this amount will first be warned and then removed if they do not manage their activity according
rest of this article seems to be written like BN is the reader, so use "you" instead of "Beatmap Nominators" and reword accordingly

2021-06-24 19:09 UTC, cl8n approved these changes

2021-07-02 00:37 UTC, merged