[FR] Mappers' Guild
ppy/osu-wiki pull request #5507
Opened 2021-05-19 18:10 UTC by Exanc

French translation of the "Mappers' Guild" page for osu!wiki.

2021-05-19 18:38 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Les taches de création d'une difficilté rapportent plus de points à un utilisateur si la beatmap est associée à une quête. Finir une quête avant la date limite rapportera des points bonus pour chaque
```suggestion
Les tâches de création d'une difficulté rapportent plus de points à un utilisateur si la beatmap est associée à une quête. Finir une quête avant la date limite rapportera des points bonus pour chaque difficulté mappée et un bonus plat pour chaque utilisateur participant à la quête. Ce bonus fixe est perdue une fois la date limite dépassée, néanmoins, les bonus de difficultés sont gardé avec une certaine décroissance après des incréments de 0, 20 et 40 jours au-delà de la date limite.
```

2021-05-19 18:39 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +La Mappers' Guild a été lancer avec un groupe de moins de 10 joueurs vers la fin de 2017. Compte tenu des informations qu'ont leurs avait fourni sur un nouvel artiste associé, [MOtOLOiD](https://osu.
```suggestion
La Mappers' Guild a été lancer avec un groupe de moins de 10 joueurs vers fin 2017. Compte tenu des informations qu'ont leurs avait fourni sur un nouvel artiste associé, [MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19), ils étaient chargés de créer 5 beatmaps pour accompagner [la publication](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid) sur l'artiste.
```

2021-05-19 18:40 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Pour promouvoir d'anciens artistes associés, le groupe recrutat de nouveaux membres et classa 8 beatmaps de différents artistes. Ces beatmaps furent publier dans un [poste](https://osu.ppy.sh/home/ne
```suggestion
Pour promouvoir d'anciens artistes associés, le groupe recrutait de nouveaux membres et classa 8 beatmaps de différents artistes. Ces beatmaps furent publier dans un [post](https://osu.ppy.sh/home/news/2018-03-17-new-mappers-guild-pack-release) accompagné d'un pack de beatmaps téléchargeable.
```

2021-05-19 18:41 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Alors que le plan initial de la Mappers' Guild était d'avoir des éléments MMO tel que des quêtes, cela c'est avéré peut pratique à gérer tout en gérant manuellement les date limite pour le nombre lim
```suggestion
Alors que le plan initial de la Mappers' Guild était d'avoir des éléments MMO tel que des quêtes, cela c'est avéré peu pratique à gérer tout en gérant manuellement les date limite pour le nombre limité de participants à la guilde. ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418) et ![][flag_CL] [Milan-](https://osu.ppy.sh/users/1052994) commencèrent donc le développement d'un site web pour automatiser la Mappers' Guild vers la fin de l'année 2018, permettant une gestion plus adéquate des récompenses et du système de quête/parties.
```

2021-05-19 18:42 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depui sont ouvertures au p
```suggestion
Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depuis son ouverture au public, la guilde a atteint un nombre de membres supérieurs à 500 et à publier des [articles de mise à jour](https://osu.ppy.sh/home/news/2019-11-29-featured-artist-beatmap-updates-from-the-mappers-guild) pour garder le reste de la communauté d'osu! à jour sur le contenu de mapping d'artistes associés.
```

2021-05-19 18:42 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +[flag_CL]: /wiki/shared/flag/CL.gif "Chile"
```suggestion
[flag_CL]: /wiki/shared/flag/CL.gif "Chili"
```

2021-05-19 18:42 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +[flag_US]: /wiki/shared/flag/US.gif "United States"
```suggestion
[flag_US]: /wiki/shared/flag/US.gif "États-Unis"
```

2021-05-24 14:32 UTC, Ganondorfosu requested changes

2021-05-24 14:32 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +Chaque quête à ses propres spécifications en therme de taille de partie, de rang, de prix d'acceptation et de date limite. Tous les membres d'une partie doivent payer le prix indiqué pour accepter la
```suggestion
Chaque quête a ses propres spécifications en termes de taille de groupe et de rang, de prix d'acceptation et de date limite. Tous les membres d'une partie doivent payer le prix indiqué pour accepter la quête. Les prix sont souvent assez élevés pour les quêtes fantaisistes ou en solo.
```

2021-05-24 14:32 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +Les quêtes expirent apret 3 mois d'inactivité. N'importe quel utilisateur pour rouvrir une quête en dépensant leur réserve disponible de points de la Mappers' Guild.
```suggestion
Les quêtes expirent après 3 mois d'inactivité. N'importe quel utilisateur peut rouvrir une quête en dépensant sa réserve disponible de points de la Mappers' Guild.
```

2021-05-24 14:32 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +La participation aux quêtes n'est pas requise pour les membres de la Mapper's Guild. Si un utilisateur le souhaite, il peut créer une beatmap seul pour obtenir des récompenses.
```suggestion
La participation aux quêtes n'est pas requise pour les membres de la Mappers' Guild. Si un utilisateur le souhaite, il peut créer une beatmap seul pour obtenir des récompenses.
```

2021-05-24 14:32 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +Les récompenses sont basées sur le total de points d'un utilisateur. Les points disponibles d'un utilisateur sont une sous-section de leur total de points en suivant le même principe que les réserves
```suggestion
Les récompenses sont basées sur le total de points d'un utilisateur. Les points disponibles d'un utilisateur sont une sous-section de son total de points en suivant le même principe que les réserves de [kudosu](/wiki/Modding/Kudosu) "reçus au total" et "disponibles" d'osu!
```

2021-05-24 14:32 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +La Mappers' Guild a été lancer avec un groupe de moins de 10 joueurs vers la fin de 2017. Compte tenu des informations qu'ont leurs avait fourni sur un nouvel artiste associé, [MOtOLOiD](https://osu.
```suggestion
La Mappers' Guild a été lancée avec un groupe de moins de 10 joueurs vers fin 2017. Compte tenu des informations qui leur ont été fournies sur un nouvel artiste associé, [MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19), ils étaient chargés de créer 5 beatmaps pour accompagner [la publication](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid) sur l'artiste.
```

2021-05-24 14:32 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +Alors que le plan initial de la Mappers' Guild était d'avoir des éléments MMO tel que des quêtes, cela c'est avéré peut pratique à gérer tout en gérant manuellement les date limite pour le nombre lim
```suggestion
Alors que le plan initial de la Mappers' Guild était d'avoir des éléments MMO tels que des quêtes, cela s'est avéré peu pratique à gérer tout en gérant manuellement les dates limites pour le nombre limité de participants à la guilde. ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418) et ![][flag_CL] [Milan-](https://osu.ppy.sh/users/1052994) commencèrent donc le développement d'un site web pour automatiser la Mappers' Guild vers la fin de l'année 2018, permettant une gestion plus adéquate des récompenses et du système de quêtes/groupes.
```

2021-05-24 14:32 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depui sont ouvertures au p
```suggestion
Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depuis son ouverture au public, la guilde a atteint un nombre de membres supérieur à 500 et a publié des [articles de mise à jour](https://osu.ppy.sh/home/news/2019-11-29-featured-artist-beatmap-updates-from-the-mappers-guild) pour garder le reste de la communauté d'osu! à jour sur le contenu de mapping d'artistes associés.
```

2021-05-26 18:41 UTC, Ganondorfosu requested changes

2021-05-26 18:41 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +La Mappers' Guild a été lancer avec un groupe de moins de 10 joueurs vers fin 2017. Compte tenu des informations qu'ont leurs avait fourni sur un nouvel artiste associé, [MOtOLOiD](https://osu.ppy.sh
```suggestion
La Mappers' Guild a été lancée avec un groupe de moins de 10 joueurs vers fin 2017. Compte tenu des informations qui leur ont été fournis sur un nouvel artiste associé, [MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19), ils étaient chargés de créer 5 beatmaps pour accompagner [la publication](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid) sur l'artiste.
```

2021-05-26 18:41 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +Alors que le plan initial de la Mappers' Guild était d'avoir des éléments MMO tel que des quêtes, cela c'est avéré peu pratique à gérer tout en gérant manuellement les date limite pour le nombre limi
```suggestion
Alors que le plan initial de la Mappers' Guild était d'avoir des éléments MMO tels que des quêtes, cela s'est avéré peu pratique à gérer tout en gérant manuellement les date limites pour le nombre limité de participants à la guilde. ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418) et ![][flag_CL] [Milan-](https://osu.ppy.sh/users/1052994) commencèrent donc le développement d'un site web pour automatiser la Mappers' Guild vers la fin de l'année 2018, permettant une gestion plus adéquate des récompenses et du système de quête/groupes.
```

2021-05-26 18:41 UTC, Ganondorfosu commented on wiki/Mappers_Guild/fr.md
> +Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depuis son ouverture au pu
```suggestion
Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depuis son ouverture au public, la guilde a atteint un nombre de membres supérieur à 500 et a publié des [articles de mise à jour](https://osu.ppy.sh/home/news/2019-11-29-featured-artist-beatmap-updates-from-the-mappers-guild) pour garder le reste de la communauté d'osu! à jour sur le contenu de mapping d'artistes associés.
```

2021-05-26 18:51 UTC, DoryanR requested changes

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +La **Mappers' Guild** est un groupe de mappeurs responsables de la création des [beatmaps](/wiki/Beatmap) pour les [artistes associés](/wiki/Featured_Artists) d'osu! En utilisant un style de guilde M
```suggestion
La **Mappers' Guild** est un groupe de mappeurs responsables de la création des [beatmaps](/wiki/Beatmap) pour les [artistes associés](/wiki/Featured_Artists) d'osu!. En utilisant un style de guilde MMO, elle permet aux mappeurs de gagner des récompenses en participant au procédé de classement des beatmaps des artistes associés et en coopérant dans des quêtes en lien avec le mapping.
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +## Le système
```suggestion
## Fonctionnement
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Les mappeurs avec 3 maps classées ou plus peuvent rejoindre la guilde à tout moment via le [site web de la Mappers' Guild](https://mappersguild.com/) en authentifiant leur compte osu!. N'importe qui
```suggestion
Les mappeurs avec 3 maps classées ou plus peuvent rejoindre la guilde à tout moment via le [site web de la Mappers' Guild](https://mappersguild.com/) en authentifiant leur compte osu!. N'importe qui est libre d'observer les activités de mapping et les quêtes sur le site web.
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Les parties sont des groupes de mappeurs qui s'inscrivent pour compléter une quête ensemble. Les mappeurs peuvent rejoindre autant de parties en même temps qu'il le souhaite.
```suggestion
Les **parties** sont des groupes de mappeurs qui s'inscrivent pour compléter une quête ensemble. Les mappeurs peuvent rejoindre autant de parties en même temps qu'il le souhaite.
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Les quêtes récompensent les mappeurs pour avoir suivi certaines exigences pendant la création de leurs maps d'artistes associés. Le plus souvent, les quêtes impliquent qu'un certain nombre de beatmap
```suggestion
Les **quêtes** récompensent les mappeurs pour avoir suivi certaines exigences pendant la création de leurs maps d'artistes associés. Le plus souvent, les quêtes impliquent qu'un certain nombre de beatmaps pour un artiste associé soit crée, cependant les quêtes impliquent aussi quelques petits gadgets.
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +### Les parties
```suggestion
### Parties
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +### Les quêtes
```suggestion
### Quêtes
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +### Les récompenses
```suggestion
### Récompenses
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Les récompenses sont distribuées au travers d'un système de points. Quand un utilisateur atteint un seuil de points spécifié, il peut gagner un rang différent signifié par un badge de profil. Il y a
```suggestion
Les **récompenses** sont distribuées au travers d'un système de points. Quand un utilisateur atteint un seuil de points spécifié, il peut gagner un rang différent signifié par un badge de profil. Il y a trois niveaux de badges de profil : 100, 250 et 500 points respectivement.
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Les récompenses sont basées sur le total de points d'un utilisateur. Les points disponibles d'un utilisateur sont une sous-section de son total de points en suivant le même principe que les réserves
```suggestion
Les récompenses sont basées sur le total de points d'un utilisateur. Les points disponibles d'un utilisateur sont une sous-section de son total de points en suivant le même principe que les [kudosu](/wiki/Modding/Kudosu) "reçus au total" et "disponibles" d'osu!
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +### L'Automatisation
```suggestion
### Automatisation
```

2021-05-26 18:51 UTC, DoryanR commented on wiki/Mappers_Guild/fr.md
> +Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depuis son ouverture au pu
```suggestion
Le [site web de la Mappers' Guild](https://mappersguild.com/) fut lancer le 1er Mars 2019 et c'est ici que tout ce qui concerne la Mappers' Guild est actuellement contrôlé. Depuis son ouverture au public, la guilde a atteint un nombre de membres supérieur à 500 et a publié des [articles de mise à jour](https://osu.ppy.sh/home/news/2019-11-29-featured-artist-beatmap-updates-from-the-mappers-guild) pour garder le reste de la communauté d'osu! à jour sur le contenu de mapping des artistes associés.
```

2021-05-26 19:05 UTC, DoryanR approved these changes

2021-06-09 14:39 UTC, DoryanR approved these changes
Can be merge 👍

2021-06-25 20:33 UTC, DoryanR approved these changes
Can be merge

2021-06-25 20:38 UTC, TicClick approved these changes
merging under the assumption that the three unresolved comments were addressed in one way or another

2021-06-25 20:38 UTC, merged