[FR] Add `Ranking Queue`, update `Beatmap ranking procedure`
ppy/osu-wiki pull request #5508
Opened 2021-05-19 18:26 UTC by DoryanR

Proposal for the French translation of the wiki page `Ranking queue`.

Proposal to update the French translation of the wiki page `Beatmap ranking procedure`.

2021-05-21 16:29 UTC, TicClick commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les membres du groupe des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) (*BNs*) sont des moddeurs expérimentés capables de proposer des beatmaps classable. Leur rôle est de s'assurer
please replace `beatmapset` with an equivalent of `beatmap` in French as I did recently

2021-05-24 14:50 UTC, Ganondorfosu requested changes

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/Ranking_queue/fr.md
> +La **file de classement** gère le passage des [beatmaps](/wiki/Beatmap) de [qualifié](/wiki/Beatmap/Category#qualified) à [classé](/wiki/Beatmap/Category#ranked). Chaque jour, 10 beatmaps de chaque [
```suggestion
La **file de classement** gère le passage des [beatmaps](/wiki/Beatmap) de [qualifié](/wiki/Beatmap/Category#qualified) à [classé](/wiki/Beatmap/Category#ranked). Chaque jour, 10 beatmaps de chaque [mode de jeu](/wiki/Game_mode) peuvent passer de la catégorie qualifiée à la catégorie classée, à condition d'avoir été dans la catégorie qualifiée pendant au moins 7 jours. Le moment de la journée où les beatmaps sont classées est aléatoire.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/Ranking_queue/fr.md
> +Lorsqu'un beatmap est [disqualifié](/wiki/Beatmap_ranking_procedure#nomination-resets), le temps qu'il a passé dans la catégorie qualifié est sauvegardé. Si elle est requalifiée, elle entrera dans la
```suggestion
Lorsqu'une beatmap est [disqualifiée](/wiki/Beatmap_ranking_procedure#nomination-resets), le temps qu'il a passé dans la catégorie qualifiée est sauvegardé. Si elle est requalifiée, elle entrera dans la file d'attente comme si elle avait déjà été dans la file d'attente pendant cette durée. Cette possibilité de "sauter" le temps passé dans la file d'attente est plafonnée à 6 jours afin de garantir que les beatmaps restent toujours dans la file d'attente qualifiée pendant au moins une journée entière.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les [beatmaps](/wiki/Beatmap) peuvent être promus dans la communauté en suivant la procédure de classement des beatmaps et en entrant dans la catégorie [classé](/wiki/Beatmap/Category#ranked).
```suggestion
Les [beatmaps](/wiki/Beatmap) peuvent être promues dans la communauté en suivant la procédure de classement des beatmaps et en entrant dans la catégorie [classée](/wiki/Beatmap/Category#ranked).
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Le créateur d'un beatmap peut marquer ses soumissions comme `Work in Progress` ou `En attente`. Les beatmaps de ces deux catégories sont destinés à recevoir les commentaires de la communauté d'osu!
```suggestion
Le créateur d'une beatmap peut marquer ses soumissions comme `Work in Progress` ou `En attente`. Les beatmaps de ces deux catégories sont destinées à recevoir les commentaires de la communauté d'osu!
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Le [modding](/wiki/Modding) est le processus qui consiste à recevoir des critiques constructives sur un beatmap et qui permet d'en améliorer la qualité. Les utilisateurs publient généralement leurs c
```suggestion
Le [modding](/wiki/Modding) est le processus qui consiste à recevoir des critiques constructives sur une beatmap et qui permet d'en améliorer la qualité. Les utilisateurs publient généralement leurs commentaires sur la page de discussion d'une beatmap ou discutent directement avec le créateur de la beatmap.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Avant d'être proposés au classement, les beatmaps doivent recevoir des messages de [hype](/wiki/Glossary#hype) d'au moins cinq utilisateurs différents.
```suggestion
Avant d'être proposées au classement, les beatmaps doivent recevoir des messages de [hype](/wiki/Glossary#hype) d'au moins cinq utilisateurs différents.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les membres du groupe des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) (*BNs*) sont des moddeurs expérimentés capables de proposer des beatmaps classable. Leur rôle est de s'assurer
```suggestion
Les membres du groupe des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) (*BNs*) sont des moddeurs expérimentés capables de proposer des beatmaps classables. Leur rôle est de s'assurer qu'une beatmap répond aux [critères de classement](/wiki/Ranking_Criteria) ainsi qu'à leurs propres critères de qualité.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les membres de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (*NAT*) peuvent également nommer des beatmaps, mais ce n'est pas leur rôle principal.
```suggestion
Les membres de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (*NAT*) peuvent également nominer des beatmaps, mais ce n'est pas leur rôle principal.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les beatmaps qui reçoivent deux nominations pour chaque mode de jeu disponible dans la beatmap sont déplacés dans la catégorie des beatmaps [qualifiés](/wiki/Beatmap/Category#qualified). Les beatmaps
```suggestion
Les beatmaps qui reçoivent deux nominations pour chaque mode de jeu disponible dans la beatmap sont déplacées dans la catégorie des beatmaps [qualifiées](/wiki/Beatmap/Category#qualified). Les beatmaps qualifiées disposent d'un classement des scores, mais ne récompensent pas les joueurs avec des [points de performance](/wiki/Performance_Points). Lorsqu'une beatmap reste dans la catégorie qualifiée pendant au moins 7 jours, la [file d'attente de classement](Ranking_queue) peut la faire passer dans la catégorie [classée](#classée).
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Cette catégorie de beatmap existe pour offrir aux beatmaps une plus grande exposition à la communauté d'osu! dans l'espoir de découvrir des problèmes potentiels. Les problèmes peuvent être signalés a
```suggestion
Cette catégorie de beatmap existe pour offrir aux beatmaps une plus grande exposition à la communauté d'osu! dans l'espoir de découvrir des problèmes potentiels. Les problèmes peuvent être signalés aux BN et aux membres de la NAT à partir de la page de discussion d'une beatmap. Contrairement aux beatmaps en attente, les beatmaps qualifiées ne peuvent pas être mises à jour par leurs créateurs. Les commentaires ne peuvent donc être appliqués qu'après avoir demandé une [réinitialisation de la nomination](#réinitialisation-de-la-nomination).
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les réinitialisations des nominations permettent de s'assurer que les modérateurs, les BN et les membres du NAT vérifient la version la plus récente d'une beatmap avant qu'il n'entre dans la file d'a
```suggestion
Les réinitialisations des nominations permettent de s'assurer que les modérateurs, les BN et les membres de la NAT vérifient la version la plus récente d'une beatmap avant qu'elle n'entre dans la file d'attente de classement.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les nominations peuvent être réinitialisé lorsque le créateur met à jour sa beatmap ou lorsqu'un membre du BN ou du NAT trouve un problème dans une difficulté nommé. Elles peuvent également être réin
```suggestion
Les nominations peuvent être réinitialisées lorsque le créateur met à jour sa beatmap ou lorsqu'un BN ou un membre de la NAT trouve un problème dans une difficulté nommée. Elles peuvent également être réinitialisées par les membres de la [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team) lorsque la raison est un contenu inapproprié. Si une difficulté est qualifiée lorsque ses nominations sont réinitialisées, elle sera disqualifiée, ce qui la supprimera de la file d'attente de classement.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les membres du BN et du NAT opposent parfois leur [veto](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto) aux difficultés qui, selon eux, présentent des problèmes de qualité sans rapport avec l
```suggestion
Les BN et les membres de la NAT opposent parfois leur [veto](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto) aux difficultés qui, selon eux, présentent des problèmes de qualité sans rapport avec les critères de classement.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les beatmaps qui ont franchi l'étape de qualification ont terminé la procédure de classement. Ils disposent de tableaux de classement des scores et récompensent les joueurs par des points de performa
```suggestion
Les beatmaps qui ont franchi l'étape de qualification ont terminé la procédure de classement. Elles disposent de tableaux de classement des scores et récompensent les joueurs par des points de performance.
```

2021-05-24 14:50 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les beatmaps classés ne sont déclassés que dans des circonstances exceptionnelles, lorsque des problèmes sont découverts peu après qu'ils aient atteint le statut classé.
```suggestion
Les beatmaps classées ne sont déclassées que dans des circonstances exceptionnelles, lorsque des problèmes sont découverts peu après qu'ils aient atteint le statut classé.
```

2021-05-24 18:59 UTC, DoryanR commented on wiki/Beatmap_ranking_procedure/fr.md
> +Avant d'être proposées au classement, les beatmaps doivent recevoir des messages de [hype](/wiki/Glossary#hype) d'au moins cinq utilisateurs différents.
```suggestion
Avant d'être proposées au classement, les beatmaps doivent recevoir des messages de [hype](/wiki/Beatmap/Hype) d'au moins cinq utilisateurs différents.
```

2021-05-25 18:40 UTC, TicClick commented
if @Ganondorfosu approves, this can be merged

2021-05-25 18:58 UTC, Ganondorfosu requested changes

2021-05-25 18:58 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/Ranking_queue/fr.md
> +La **file de classement** gère le passage des [beatmaps](/wiki/Beatmap) de [qualifié](/wiki/Beatmap/Category#qualified) à [classé](/wiki/Beatmap/Category#ranked). Chaque jour, 10 beatmaps de chaque [
```suggestion
La **file de classement** gère le passage des [beatmaps](/wiki/Beatmap) de la catégorie [qualifiée](/wiki/Beatmap/Category#qualified) à la catégorie [classée](/wiki/Beatmap/Category#ranked). Chaque jour, 10 beatmaps de chaque [mode de jeu](/wiki/Game_mode) peuvent passer de la catégorie qualifiée à la catégorie classée, à condition d'avoir été dans la catégorie qualifiée pendant au moins 7 jours. Le moment de la journée où les beatmaps sont classées est aléatoire.
```

2021-05-25 18:58 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/Ranking_queue/fr.md
> +Lorsqu'une beatmap est [disqualifiée](/wiki/Beatmap_ranking_procedure#nomination-resets), le temps qu'il a passé dans la catégorie qualifiée est sauvegardé. Si elle est requalifiée, elle entrera dans
```suggestion
Lorsqu'une beatmap est [disqualifiée](/wiki/Beatmap_ranking_procedure#nomination-resets), le temps qu'elle a passé dans la catégorie qualifiée est sauvegardé. Si elle est requalifiée, elle entrera dans la file d'attente comme si elle avait déjà été dans la file d'attente pendant cette durée. Cette possibilité de "sauter" le temps passé dans la file d'attente est plafonnée à 6 jours afin de garantir que les beatmaps restent toujours dans la file d'attente qualifiée pendant au moins une journée entière.
```

2021-05-25 18:58 UTC, Ganondorfosu commented on wiki/Beatmap_ranking_procedure/fr.md
> +Les beatmaps classées ne sont déclassées que dans des circonstances exceptionnelles, lorsque des problèmes sont découverts peu après qu'ils aient atteint le statut classé.
```suggestion
Les beatmaps classées ne sont déclassées que dans des circonstances exceptionnelles, lorsque des problèmes sont découverts peu après qu'elles aient atteint le statut classé.
```

2021-05-25 18:59 UTC, Ganondorfosu approved these changes

2021-05-25 19:01 UTC, TicClick approved these changes

2021-05-25 19:01 UTC, merged