[FR] Add `Project Loved Team`
ppy/osu-wiki pull request #5520
Opened 2021-05-20 16:46 UTC by DoryanR

Proposal for the French translation of the wiki page `Project Loved Team`.

I re-translated the article, despite #4991 because the PR author could not update the file, which had been updated during the review. As he gave his permission to redo a PR for this article, I did so.

2021-05-22 10:28 UTC, Ganondorfosu requested changes

2021-05-22 10:28 UTC, Ganondorfosu commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +Le **Project Loved Team** est composée de membres de la communauté d'osu! qui gèrent le [Project Loved](/wiki/Project_Loved), la plateforme de vote qui promeut les [beatmaps](/wiki/Beatmap) dans la c
```suggestion
La **Project Loved Team** est composée de membres de la communauté d'osu! qui gèrent le [Project Loved](/wiki/Project_Loved), la plateforme de vote qui promeut les [beatmaps](/wiki/Beatmap) dans la catégorie [loved](/wiki/Beatmap/Category#loved).
```

2021-05-22 10:28 UTC, Ganondorfosu commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +Le Project Loved Team se compose principalement de *capitaines* pour chaque [mode de jeu](/wiki/Game_mode). Les capitaines sont responsables de la nomination des beatmaps dans la catégorie loved et a
```suggestion
La Project Loved Team se compose principalement de *capitaines* pour chaque [mode de jeu](/wiki/Game_mode). Les capitaines sont responsables de la nomination des beatmaps dans la catégorie loved et agissent en tant que représentants de la communauté en ayant une bonne idée des beatmaps à choisir. Ils rédigent également de courtes descriptions des beatmaps nominées afin d'aider les lecteurs à se faire une idée de chaque beatmap s'ils ne les ont pas vues ou jouées auparavant.
```

2021-05-22 10:28 UTC, Ganondorfosu commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +Les vérificateurs des métadonnées vérifient chaque beatmap qui sera soumis au vote, et travaillent avec les mappeurs pour corriger les éventuelles erreurs avant que les beatmaps ne soient potentielle
```suggestion
Les vérificateurs des métadonnées vérifient chaque beatmap qui sera soumise au vote, et travaillent avec les mappeurs pour corriger les éventuelles erreurs avant que les beatmaps ne soient potentiellement déplacées vers la catégorie loved.
```

2021-05-22 10:28 UTC, Ganondorfosu commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +- ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) a créé l'équipe originale de capitaines en septembre 2017 ainsi que le système [Captain's Pick](/wiki/Beatmap/History_of_Loved#captain's-pick-an
```suggestion
- ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) a créé l'équipe originelle de capitaines en septembre 2017 ainsi que le système [Captain's Pick](/wiki/Beatmap/History_of_Loved#captain's-pick-and-project-loved-(sep-2017---present)) qui a ensuite été renommé Project Loved. Jusqu'à fin 2019, il a supervisé et géré l'ensemble du projet.
```

2021-05-22 10:28 UTC, Ganondorfosu commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +- Il y a un groupe d'utilisateurs Project Loved sur le site web avec l'ID de groupe 31, mais la liste n'est pas publique. Il est utilisé pour les autorisations de modérer le [forum Project Loved](htt
```suggestion
- Il y a un groupe d'utilisateurs Project Loved sur le site web avec l'ID de groupe 31, mais la liste n'est pas publique. Il est utilisé pour leur donner l'autorisation de modérer le [forum Project Loved](https://osu.ppy.sh/community/forums/120) et de promouvoir les beatmaps dans la catégorie Loved.
```

2021-05-22 10:28 UTC, Ganondorfosu commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +  - Jusqu'au 16 avril 2021, les seules personnes qui avaient fait partie du groupe étaient ![][flag_US] [clayton](https://osu.ppy.sh/users/3666350), ![][flag_LT] [huu](https://osu.ppy.sh/users/604423
```suggestion
  - Jusqu'au 16 avril 2021, les seules personnes qui faisaient partie du groupe étaient ![][flag_US] [clayton](https://osu.ppy.sh/users/3666350), ![][flag_LT] [huu](https://osu.ppy.sh/users/6044237), ![][flag_SG] [Shoegazer](https://osu.ppy.sh/users/2520707), et ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689). Maintenant, tous les utilisateurs faisant partie de la Project Loved Team appartiennent au groupe.
```

2021-05-24 14:57 UTC, Ganondorfosu requested changes

2021-05-24 14:57 UTC, Ganondorfosu commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +La Project Loved Team se compose principalement de *capitaines* pour chaque [mode de jeu](/wiki/Game_mode). Les capitaines sont responsables de la nomination des beatmaps dans la catégorie loved et a
```suggestion
La Project Loved Team se compose principalement de *capitaines* pour chaque [mode de jeu](/wiki/Game_mode). Les capitaines sont responsables de la nomination des beatmaps dans la catégorie loved et agissent en tant que représentants de la communauté en ayant une bonne idée des beatmaps à choisir. Ils rédigent également de courtes descriptions des beatmaps nominées afin d'aider les lecteurs à se faire une idée de chaque beatmap s'ils ne les ont pas vu ou joué auparavant.
```

2021-05-24 15:03 UTC, Ganondorfosu approved these changes

2021-05-25 13:33 UTC, TicClick approved these changes

2021-05-25 13:33 UTC, merged