[ID] Add "peppy"
ppy/osu-wiki pull request #5531
Opened 2021-05-21 18:04 UTC by hikikuman

Add Indonesian translation for [peppy](https://osu.ppy.sh/wiki/en/People/peppy) article.

2021-05-23 14:36 UTC, mousesalt requested changes
small change else is fine to get approval. good job! :+1:

2021-05-23 14:36 UTC, mousesalt commented on wiki/People/peppy/id.md
> +**peppy** (ditulis dengan huruf "p" kecil) adalah nama lain dari Dean herbert yang merupakan pencipta dari osu! dan juga [pengembang](/wiki/People/The_Team/Developers) utamanya.
```suggestion
**peppy** (ditulis dengan huruf "p" kecil) adalah nama lain dari Dean Herbert yang merupakan pencipta dari proyek osu! dan juga seorang [pengembang](/wiki/People/The_Team/Developers) utama.
```

2021-05-23 14:36 UTC, mousesalt commented on wiki/People/peppy/id.md
> +**peppy** (ditulis dengan huruf "p" kecil) adalah nama lain dari Dean herbert yang merupakan pencipta dari osu! dan juga [pengembang](/wiki/People/The_Team/Developers) utamanya.
oh no, don't forget about to capitalized the person's name next time.

2021-05-25 13:32 UTC, TicClick approved these changes

2021-05-25 13:32 UTC, merged