[ID] Update "BN General Information"
ppy/osu-wiki pull request #5533
Opened 2021-05-21 18:15 UTC by hikikuman

Update outdated Indonesian translation for [General information for Beatmap Nominators](https://osu.ppy.sh/wiki/en/People/The_Team/Beatmap_Nominators/General_Information) article.

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +**Tombol ini memungkinkan kamu untuk menominasi beatmap.** Untuk menominasi sebuah beatmap, mapset harus memiliki setidaknya 5 Hype dan tidak ada tanda Masalah atau Saran yang saat ini belum terseles
```suggestion
**Tombol ini memungkinkan kamu untuk menominasi beatmap.** Untuk menominasi sebuah sebuah beatmap, mapset harus memiliki setidaknya 5 Hype dan tidak ada tanda Masalah atau Saran yang saat ini belum terselesaikan. Sebelum memberikan nominasi, pastikan kamu puas dengan semua tingkat kesulitan, bahkan untuk mode permainan lainnya. Jika beatmap sebelumnya pernah diveto, kamu harus memastikan veto tersebut sudah diselesaikan sebelum meneruskan mapset. Ketika sebuah beatmap memiliki 2 nominasi, beatmap tersebut akan menuju ke bagian kualifikasi dan masuk ke antrian ranking.
```

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +**Tombol ini memungkinkan kamu untuk menominasi beatmap.** Untuk menominasi sebuah beatmap, mapset harus memiliki setidaknya 5 Hype dan tidak ada tanda Masalah atau Saran yang saat ini belum terseles
this probably wayyyy better

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
>  ![tombol diskualifikasi dan reset](img/reset_dq_id.png)
```suggestion
![tombol diskualifikasi dan tombol reset](img/reset_dq_id.png)
```

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
>  ![tombol diskualifikasi dan reset](img/reset_dq_id.png)
could it get the own word since it's doesn't have to attach with `diskualifikasi `

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Langkah-langkah untuk Mendiskualifikasi Beatmap:
```suggestion
Langkah-langkah untuk mendiskualifikasi beatmap:
```

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Langkah-langkah untuk Mendiskualifikasi Beatmap:
should be lowercase

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Full BN dapat melakukan Quality Assurance dengan mengecek beatmap-beatmap yang telah dikualifikasi kapan pun. Papan Quality Assurance dapat dilihat pada [situs BN](https://bn.mappersguild.com/quality
```suggestion
Full BN dapat melakukan Quality Assurance dengan mengecek masalah pada beatmap-beatmap yang telah dikualifikasi kapan pun. Papan Quality Assurance dapat dilihat pada [situs BN](https://bn.mappersguild.com/qualityassurance).
```

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Full BN dapat melakukan Quality Assurance dengan mengecek beatmap-beatmap yang telah dikualifikasi kapan pun. Papan Quality Assurance dapat dilihat pada [situs BN](https://bn.mappersguild.com/quality
you forgot that one

2021-05-23 15:16 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Semua BN dapat berkontribusi dalam memoderasi lagu-lagu dan gambar-gambar dengan mengirimkan konten untuk ditinjau atau memberikan suara pada konten tersebut. Proses pemungutan suara secara utuh dan
```suggestion
Semua BN dapat berkontribusi ke dalam moderasi lagu dan gambar dengan mengirimkan konten untuk ditinjau atau diberikan suara pada konten tersebut. Proses pemungutan suara secara utuh dan bagaimana suara-suara tersebut dihitung dapat dibaca di [artikel proses pengkajian konten](/wiki/Rules/Content_Voting_Process).
```

2021-06-05 04:26 UTC, wowcake requested changes
rest looks good

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Apakah kamu seorang [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators) *(BN)*, atau tertarik menjadi salah satunya? jika ya, kamu datang ke tempat yang tepat! Artikel ini berisi semua info
```suggestion
Apakah kamu seorang [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators) *(BN)*, atau tertarik menjadi salah satunya? Jika ya, kamu datang ke tempat yang tepat! Artikel ini berisi semua informasi umum yang perlu kamu ketahui sebagai seorang Beatmap Nominator baru.
```

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Apakah kamu seorang [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators) *(BN)*, atau tertarik menjadi salah satunya? jika ya, kamu datang ke tempat yang tepat! Artikel ini berisi semua info
better capitalized

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +- [Peraturan Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators/Rules): Garis besar bagaimana cara melakukan berbagai tindakan, serta bagaimana cara untuk tidak melakukan sesuatu yang dapat
```suggestion
- [Peraturan Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators/Rules): Garis besar cara untuk melakukan berbagai tindakan, serta bagaimana cara untuk tidak melakukan sesuatu yang dapat melanggar ketentuan-ketentuan yang telah diberikan dalam situasi apa pun, jadi pastikan untuk membacanya dengan cermat! Kamu selalu dapat bertanya kepada seorang anggota dari [Nomination Assessment Team](The_Team/Nomination_Assessment_Team) *(NAT)* jika kamu tidak yakin tentang sesuatu, dan mereka akan membantu kamu dengan senang hati.
```

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +- [Kode Etik untuk Mapping dan Modding](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping): Sebagai seorang BN, kamu diharapkan dapat menjadi sosok yang patut dicontoh di dalam komunitas, menjadi s
```suggestion
- [Kode Etik untuk Mapping dan Modding](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping): Sebagai seorang BN, kamu diharapkan dapat menjadi sosok yang patut dicontoh di dalam komunitas, menjadi seorang yang orang lain kagumi dan hormati, jadi perbuatan yang melanggar pengaturan dapat membuat kamu ditegur atau bahkan dikeluarkan.
```

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +- [Ranking Criteria](/wiki/Ranking_Criteria): Jika kamu sudah menjadi seorang BN, kamu harus terbiasa dengan ini. Pada dasarnya, ini berfungsi untuk menjelaskan aspek mapping yang diperbolehkan dan t
```suggestion
- [Ranking Criteria](/wiki/Ranking_Criteria): Jika kamu sudah menjadi seorang BN, kamu seharusnya sudah terbiasa dengan ini. Pada dasarnya, hal ini berfungsi untuk menjelaskan aspek mapping yang diperbolehkan dan tidak diperbolehkan di bagian Ranked, serta beberapa pedoman umum yang harus diikuti dalam kebanyakan kasus.
```

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +- [Informasi Beatmap Veto](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto): Untuk beatmap dengan masalah kualitas secara objektif yang sebetulnya tidak melanggar aturan dan pedoman dari Rankin
```suggestion
- [Informasi Beatmap Veto](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto): Untuk beatmap dengan masalah kualitas secara objektif yang sebetulnya tidak melanggar aturan dan pedoman dari Ranking Criteria, tetapi yang menurut kamu membuat beatmap tersebut tidak sesuai untuk bagian Ranked, beatmap veto memungkinkan kamu untuk menahan beatmap dari bagian Qualification.
```

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +Sebagai perpanjangan dari kemampuan ini, kamu juga bisa [memveto sebuah beatmap](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto), mencegah sebuah beatmap dinominasi kembali sampai kamu memberi
```suggestion
Sebagai tambahan dari kemampuan ini, kamu juga bisa [memveto sebuah beatmap](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto), mencegah sebuah beatmap dinominasi kembali sampai kamu memberikan izin atau veto dicabut oleh mediasi veto. Namun, mengajukan veto juga mengharuskan kamu mendiskusikan masalah ini dengan mapper dengan benar dan mencoba mencapai mufakat. Membahas masalah dengan Nominator yang awal akan bermanfaat dan dapat memberi kamu perspektif baru tentang masalah tersebut, tetapi kamu tidak diwajibkan untuk melakukannya.
```

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +**Tombol ini memungkinkan kamu untuk menominasi beatmap.** Untuk menominasi sebuah sebuah beatmap, mapset harus memiliki setidaknya 5 Hype dan tidak ada tanda Masalah atau Saran yang saat ini belum t
```suggestion
**Tombol ini memungkinkan kamu untuk menominasi beatmap.** Untuk menominasi sebuah beatmap, mapset harus memiliki setidaknya 5 Hype dan tidak ada tanda Masalah atau Saran yang saat ini belum terselesaikan. Sebelum memberikan nominasi, pastikan kamu puas dengan semua tingkat kesulitan, bahkan untuk mode permainan lainnya. Jika beatmap sebelumnya pernah diveto, kamu harus memastikan veto tersebut sudah diselesaikan sebelum meneruskan mapset tersebut. Ketika sebuah beatmap memiliki 2 nominasi, beatmap tersebut akan menuju ke bagian kualifikasi dan masuk ke antrian ranking.
```

2021-06-05 04:26 UTC, wowcake commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +**Ini memungkinkan kamu untuk mereset perkembangan dari sebuah beatmap dalam proses ranking.** Jika sebuah beatmap saat ini dinominasi atau dikualifikasi, kamu sebagai seorang nominator diberikan kem
```suggestion
**Ini memungkinkan kamu untuk mereset perkembangan dari sebuah beatmap dalam proses ranking.** Jika sebuah beatmap saat ini dinominasi atau dikualifikasi, kamu sebagai seorang nominator diberikan kemampuan untuk mereset nominasi pada beatmap dengan memposting sebuah isu menggunakan tanda Masalah. Jika sebuah beatmap dikualifikasi, beatmap itu hanya dapat didiskualifikasi oleh seorang full BN. Opsi ini biasanya digunakan ketika ada masalah besar atau masalah unrankable dalam beatmap yang harus ditangani sebelum mempertimbangkannya untuk masuk ke bagian ranking.
```

2021-06-05 07:34 UTC, mousesalt requested changes

2021-06-05 07:34 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/id.md
> +- [Peraturan Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators/Rules): Garis besar bagaimana cara melakukan berbagai tindakan, serta bagaimana cara untuk tidak melakukan sesuatu yang dapat
```suggestion
- [Peraturan Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators/Rules): Garis besar bagaimana cara melakukan berbagai tindakan, serta bagaimana cara untuk tidak melakukan sesuatu yang dapat melanggar ketentuan-ketentuan yang telah diberikan dalam situasi apa pun, jadi pastikan untuk membacanya dengan cermat! kamu selalu dapat bertanya kepada seorang anggota dari [Nomination Assessment Team](/wiki/The_Team/Nomination_Assessment_Team) *(NAT)* jika kamu tidak yakin tentang sesuatu, dan mereka akan membantu kamu dengan senang hati.
```

2021-06-28 13:26 UTC, wowcake approved these changes
looks good to me

2021-06-29 10:38 UTC, mousesalt approved these changes

2021-07-01 13:45 UTC, TPGPL approved these changes

2021-07-01 13:46 UTC, merged