[FR] Add "Modding/Mapping Assistance Team"
ppy/osu-wiki pull request #5539
Opened 2021-05-22 08:13 UTC by DoryanR

Proposal for the French translation of the wiki page `Mapping Assistance Team`.

2021-05-22 10:38 UTC, Ganondorfosu requested changes

2021-05-22 10:38 UTC, Ganondorfosu commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +La **Mapping Assistance Team** (***MAT***) était un groupe chargé d'évaluer la qualité des [beatmaps](/wiki/Beatmap) [en attente](/wiki/Beatmap/Category#pending) et de les recommander pour un futur [
```suggestion
La **Mapping Assistance Team** (***MAT***) était un groupe chargé d'évaluer la qualité des [beatmaps](/wiki/Beatmap) [en attente](/wiki/Beatmap/Category#pending) et de les recommander pour un futur [classement](/wiki/Beatmap/Category#ranked). Leurs recommandations étaient transmises à la [Beatmap Appreciation Team](/wiki/Modding/Beatmap_Appreciation_Team) (*BAT*) en plaçant une [proto-bulle](/wiki/Modding/Proto-bulle), et la BAT prenait alors la décision finale quant à l'entrée de la beatmap dans la catégorie classée.
```

2021-05-22 10:38 UTC, Ganondorfosu commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +Le MAT a été créé le 27 décembre 2009, les premiers membres ayant été choisis par les membres du BAT.
```suggestion
La MAT a été créée le 27 décembre 2009, les premiers membres ayant été choisis par les membres de la BAT.
```

2021-05-22 10:38 UTC, Ganondorfosu commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +Peu après, des candidatures ouvertes ont été organisées, permettant à tous les membres de la communauté générale de mapping et de modding de postuler pour un poste au sein du MAT. Le 26 février 2010,
```suggestion
Peu après, des candidatures ouvertes ont été organisées, permettant à tous les membres de la communauté générale de mapping et de modding de postuler pour un poste au sein de la MAT. Le 26 février 2010, le premier lot de nouveaux membres de la MAT a été ajouté à partir de ces candidatures, sur la base d'une évaluation collective des membres de BAT et de MAT existants. D'autres cycles de candidatures ont été organisés régulièrement pour rechercher de nouveaux membres, ainsi que pour fournir un retour d'informations aux candidats non retenus.
```

2021-05-22 10:38 UTC, Ganondorfosu commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +Le 4 octobre 2010, les membres du MAT ont obtenu la possibilité de placer des icônes full bubble et des bubble pop sur les beatmaps, ce qui a permis d'aligner leurs rôles et responsabilités sur ceux
```suggestion
Le 4 octobre 2010, les membres de la MAT ont obtenu la possibilité de placer des icônes full bubble et bubble pop sur les beatmaps, ce qui a permis d'aligner leurs rôles et responsabilités avec ceux de leurs collègues du BAT. Cependant, ils ne disposaient toujours pas d'outils de modération des forums ou des chats en jeu et se concentraient uniquement sur l'évaluation et la promotion des beatmaps.
```

2021-05-22 10:38 UTC, Ganondorfosu commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +Après une convergence progressive de l'expérience et des responsabilités entre les deux équipes, le 23 avril 2013, le MAT a été dissous, tous les membres actuels étant promus au BAT et recevant les o
```suggestion
Après une convergence progressive de l'expérience et des responsabilités entre les deux équipes, le 23 avril 2013, la MAT a été dissoute, tous ses membres ont été promus au rang de BAT et ont reçu les outils et responsabilités de modération associés.
```

2021-05-22 11:56 UTC, Ganondorfosu commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +Le 4 octobre 2010, les membres de la MAT ont obtenu la possibilité de placer des icônes full bubble et bubble pop sur les beatmaps, ce qui a permis d'aligner leurs rôles et responsabilités avec ceux
```suggestion
Le 4 octobre 2010, les membres de la MAT ont obtenu la possibilité de placer des icônes full bubble et bubble pop sur les beatmaps, ce qui a permis d'aligner leurs rôles et responsabilités avec ceux de leurs collègues de la BAT. Cependant, ils ne disposaient toujours pas d'outils de modération des forums ou des chats en jeu et se concentraient uniquement sur l'évaluation et la promotion des beatmaps.
```

2021-05-22 11:59 UTC, Ganondorfosu submitted a review, later dismissed

2021-05-25 13:24 UTC, TicClick requested changes

2021-05-25 13:24 UTC, TicClick commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +La **Mapping Assistance Team** (***MAT***) était un groupe chargé d'évaluer la qualité des [beatmaps](/wiki/Beatmap) [en attente](/wiki/Beatmap/Category#pending) et de les recommander pour un futur [
```suggestion
La **Mapping Assistance Team** (***MAT***) était un groupe chargé d'évaluer la qualité des [beatmaps](/wiki/Beatmap) [en attente](/wiki/Beatmap/Category#pending) et de les recommander pour un futur [classement](/wiki/Beatmap/Category#ranked). Leurs recommandations étaient transmises à la [Beatmap Appreciation Team](/wiki/Modding/Beatmap_Appreciation_Team) (*BAT*) en plaçant une [proto-bulle](/wiki/Modding/Proto-bubble), et la BAT prenait alors la décision finale quant à l'entrée de la beatmap dans la catégorie classée.
```

2021-05-26 19:19 UTC, Ganondorfosu commented on wiki/Modding/Mapping_Assistance_Team/fr.md
> +Peu après, des candidatures ouvertes ont été organisées, permettant à tous les membres de la communauté générale de mapping et de modding de postuler pour un poste au sein de la MAT. Le 26 février 20
```suggestion
Peu après, des candidatures ouvertes ont été organisées, permettant à tous les membres de la communauté générale de mapping et de modding de postuler pour un poste au sein de la MAT. Le 26 février 2010, le premier lot de nouveaux membres de la MAT a été ajouté à partir de ces candidatures, sur la base d'une évaluation collective des membres de la BAT et de la MAT actuels. D'autres cycles de candidatures ont été organisés régulièrement pour rechercher de nouveaux membres, ainsi que pour fournir un retour d'informations aux candidats non retenus.
```

2021-05-26 19:21 UTC, Ganondorfosu approved these changes

2021-05-31 22:15 UTC, TicClick approved these changes

2021-05-31 22:16 UTC, merged