[FR] Add translations for "Beatmap Spotlights" folder
ppy/osu-wiki pull request #5541
Opened 2021-05-22 11:44 UTC by DoryanR

Translation of the following wiki pages:

- `Beatmap_Spotlights/Seasons/2020_Autumn`
- `Beatmap_Spotlights/Seasons/2020_Summer`
- `Beatmap_Spotlights/Seasons/2021_Spring`
- `Beatmap_Spotlights/Seasons/2021_Winter`
- `Beatmap_Spotlights/Seasons`
- `Beatmap_Spotlights`

2021-05-24 17:59 UTC, Ganondorfosu requested changes

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +La saison actuelle est celle de l'hiver 2021.
```suggestion
La saison actuelle est celle du printemps 2021.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +Le projet Beatmap Spotlights est actuellement organisé en saisons prédéfinies. Chaque saison se compose d'un pool de beatmaps sélectionnés et d'une ligue saisonnière compétitive pour l'ensemble de la
```suggestion
Le projet Beatmap Spotlights est actuellement organisé en saisons prédéfinies. Chaque saison se compose d'un pool de beatmaps sélectionnées et d'une ligue saisonnière compétitive pour l'ensemble de la communauté.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +   - Chaque beatmap est sélectionné et verrouillé avant le début de la saison.
```suggestion
   - Chaque beatmap est sélectionnée et verrouillée avant le début de la saison.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +   - La tranche est attribuée en fonction de la position dans le classement. Les participants se verront attribuer la tranche la plus élevée pour laquelle ils sont éligibles.
```suggestion
   - La tranche est attribuée en fonction de la position dans le classement. Les participants se verront attribuer la tranche la plus élevée à laquelle ils sont éligibles.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +3. A la fin de chaque saison, le meilleur créateur d'une beatmap, tel que décidé par les curateurs, sera récompensé par un osu!supporter d'un mois.
```suggestion
3. À la fin de chaque saison, le meilleur créateur d'une beatmap, tel que décidé par les curateurs, sera récompensé par un osu!supporter d'un mois.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +| ![](img/badges/spring_2021/osu/ri_1.png) ![](img/badges/spring_2021/osu/ri_2.png) | Rhythm Incarnate | The best of the best |
```suggestion
| ![](img/badges/spring_2021/osu/ri_1.png) ![](img/badges/spring_2021/osu/ri_2.png) | Rhythm Incarnate | Le meilleur des meilleurs |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +4. Pour remplir le devoir de recommander d'excellentes beatmaps à l'ensemble de la communauté, les beatmaps curators doivent couvrir une répartition spécifique des difficultés Hard, Insane et Expert.
```suggestion
4. Pour remplir le devoir de recommander d'excellentes beatmaps à l'ensemble de la communauté, les curateurs des beatmaps doivent couvrir une répartition spécifique des difficultés Hard, Insane et Expert.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +   - 25% de toutes les beatmaps conservés doivent se situer dans le niveau de difficulté Hard.
```suggestion
   - 25% de toutes les beatmaps conservées doivent se situer dans le niveau de difficulté Hard.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +   - 45% de toutes les beatmaps conservés devraient se situer dans le niveau de difficulté Insane.
```suggestion
   - 45% de toutes les beatmaps conservées devraient se situer dans le niveau de difficulté Insane.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +5. Pour chaque saison, 20 beatmaps au minimum doivent être sélectionnés.
```suggestion
5. Pour chaque saison, 20 beatmaps au minimum doivent être sélectionnées.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +   - Toutes les beatmaps sélectionnés doivent être classés.
```suggestion
   - Toutes les beatmaps sélectionnées doivent être classées.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +| Lobby temporaire : Listes de lecture A | 9 octobre - 16 octobre 2020 |
```suggestion
| Lobby temporaire : Playlist A | 9 octobre - 16 octobre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +| Lobby temporaire : Liste de lecture D | 30 octobre - 6 novembre 2020 |
```suggestion
| Lobby temporaire : Playlist D | 30 octobre - 6 novembre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +| Lobby temporaire : Liste de lecture A | 13 novembre - 20 novembre 2020 |
```suggestion
| Lobby temporaire : Playlist A | 13 novembre - 20 novembre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +| Lobby temporaire : Liste de lecture B | 27 novembre - 4 décembre 2020 |
```suggestion
| Lobby temporaire : Playlist B | 27 novembre - 4 décembre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +| Lobby temporaire : Liste de lecture C | 4 décembre - 11 décembre 2020 |
```suggestion
| Lobby temporaire : Playlist C | 4 décembre - 11 décembre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +| Lobby temporaire : Liste de lecture D | 11 décembre - 29 décembre 2020 |
```suggestion
| Lobby temporaire : Playlist D | 11 décembre - 29 décembre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +2. La liste de lecture comprendra désormais des mods
```suggestion
2. La playlist comprendra désormais des mods
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +## Listes de lecture
```suggestion
## Playlists
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture A | 10 juillet - 12 juillet 2020 |
```suggestion
| Lobby temporaire : Playlist A | 10 juillet - 12 juillet 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture B | 17 juillet - 19 juillet 2020 |
```suggestion
| Lobby temporaire : Playlist B | 17 juillet - 19 juillet 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture C | 24 juillet - 26 juillet 2020 |
```suggestion
| Lobby temporaire : Playlist C | 24 juillet - 26 juillet 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture D | 31 juillet - 2 août 2020 |
```suggestion
| Lobby temporaire : Playlist D | 31 juillet - 2 août 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture C | 21 août - 23 août 2020 |
```suggestion
| Lobby temporaire : Playlist C | 21 août - 23 août 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture B | 14 août - 16 août 2020 |
```suggestion
| Lobby temporaire : Playlist B | 14 août - 16 août 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture A | 7 août - 9 août 2020 |
```suggestion
| Lobby temporaire : Playlist A | 7 août - 9 août 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture D | 28 août - 30 août 2020 |
```suggestion
| Lobby temporaire : Playlist D | 28 août - 30 août 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture A et B | 4 septembre - 6 septembre 2020 |
```suggestion
| Lobby temporaire : Playlists A et B | 4 septembre - 6 septembre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +| Lobby temporaire : Liste de lecture C et D | 11 septembre - 13 septembre 2020 |
```suggestion
| Lobby temporaire : Playlists C et D | 11 septembre - 13 septembre 2020 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +2. Chaque lobby temporaire multijoueur propose une liste de lecture prédéfinie de beatmaps.
```suggestion
2. Chaque lobby temporaire multijoueur propose une playlist prédéfinie de beatmaps.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +   - Chaque liste de lecture est un sous-ensemble de l'ensemble des beatmaps de la saison en cours.
```suggestion
   - Chaque playlist est un sous-ensemble de l'ensemble des beatmaps de la saison en cours.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +   - Chaque liste de lecture contient une répartition égale de beatmaps Hard, Insane et Expert.
```suggestion
   - Chaque playlist contient une répartition égale de beatmaps Hard, Insane et Expert.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +   - Chaque liste de lecture correspond à la lettre attribuée à chaque semaine. Par conséquent, chaque liste de lecture est rejouée 3 fois au cours d'une saison.
```suggestion
   - Chaque playlist correspond à la lettre attribuée à chaque semaine. Par conséquent, chaque playlist est rejouée 3 fois au cours d'une saison.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +   - Les classements des salles sont basés sur le système de score classé. Par conséquent, seuls les meilleurs résultats de chaque beatmap de la liste de lecture sont additionnés pour créer un classe
```suggestion
   - Les classements des salles sont basés sur le système de score classé. Par conséquent, seuls les meilleurs résultats de chaque beatmap de la playlist sont additionnés pour créer un classement hebdomadaire pour chaque utilisateur.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +   - Chaque beatmap d'une liste de lecture compte également pour le score du classement. Les difficultés plus difficiles ne donnent pas plus de points.
```suggestion
   - Chaque beatmap d'une playlist compte également pour le score du classement. Les difficultés plus difficiles ne donnent pas plus de points.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +### Liste de lecture A
```suggestion
### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +### Liste de lecture B
```suggestion
### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +### Liste de lecture C
```suggestion
### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +### Liste de lecture D
```suggestion
### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +*Remarque : Vous pouvez [télécharger toutes les listes de lecture du mode osu!](https://osu.ppy.sh/beatmaps/packs/1992) sous la forme d'un seul pack de beatmaps.*
```suggestion
*Remarque : Vous pouvez [télécharger toutes les playlists du mode osu!](https://osu.ppy.sh/beatmaps/packs/1992) sous la forme d'un seul pack de beatmaps.*
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +## Listes de lecture
```suggestion
## Playlists
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +*Remarque : Vous pouvez [télécharger toutes les listes de lecture du mode osu!taiko](https://osu.ppy.sh/beatmaps/packs/1993) sous la forme d'un seul pack de beatmaps.*
```suggestion
*Remarque : Vous pouvez [télécharger toutes les playlists du mode osu!taiko](https://osu.ppy.sh/beatmaps/packs/1993) sous la forme d'un seul pack de beatmaps.*
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +*Remarque : Vous pouvez [télécharger toutes les listes de lecture du mode osu!catch](https://osu.ppy.sh/beatmaps/packs/1994) sous la forme d'un seul pack de beatmaps.*
```suggestion
*Remarque : Vous pouvez [télécharger toutes les playlists du mode osu!catch](https://osu.ppy.sh/beatmaps/packs/1994) sous la forme d'un seul pack de beatmaps.*
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +*Remarque : Vous pouvez [télécharger toutes les listes de lecture du mode osu!taiko](https://osu.ppy.sh/beatmaps/packs/1995) sous la forme d'un seul pack de beatmaps.*
```suggestion
*Remarque : Vous pouvez [télécharger toutes les playlists du mode osu!taiko](https://osu.ppy.sh/beatmaps/packs/1995) sous la forme d'un seul pack de beatmaps.*
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2020_Summer/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture A | 3 mai - 10 mai 2021 |
```suggestion
| Lobby temporaire : Playlist A | 3 mai - 10 mai 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture B | 10 mai - 17 mai 2021 |
```suggestion
| Lobby temporaire : Playlist B | 10 mai - 17 mai 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture C | 17 mai - 24 mai 2021 |
```suggestion
| Lobby temporaire : Playlist C | 17 mai - 24 mai 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture A | 7 juin - 14 juin 2021 |
```suggestion
| Lobby temporaire : Playlist A | 7 juin - 14 juin 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture D | 24 mai - 31 mai 2021 |
```suggestion
| Lobby temporaire : Playlist D | 24 mai - 31 mai 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture B | 14 juin - 21 juin 2021 |
```suggestion
| Lobby temporaire : Playlist B | 14 juin - 21 juin 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture C | 21 juin - 28 juin 2021 |
```suggestion
| Lobby temporaire : Playlist C | 21 juin - 28 juin 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +| Lobby temporaire : Liste de lecture D | 28 juin - 5 juillet 2021 |
```suggestion
| Lobby temporaire : Playlist D | 28 juin - 5 juillet 2021 |
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +   - Il y aura une semaine d'interruption après laquelle les lobbies de chaque liste de lecture seront réouverts chaque semaine.
```suggestion
   - Il y aura une semaine d'interruption après laquelle les lobbies de chaque playlist seront réouverts chaque semaine.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +2. Chaque lobby temporaire multijoueur propose une liste de lecture prédéfinie de beatmaps.
```suggestion
2. Chaque lobby temporaire multijoueur propose une playlist prédéfinie de beatmaps.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +   - Chaque liste de lecture est un sous-ensemble de l'ensemble des beatmaps de la saison en cours.
```suggestion
   - Chaque playlist est un sous-ensemble de l'ensemble des beatmaps de la saison en cours.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +   - Chaque liste de lecture contient une répartition égale de beatmaps Hard, Insane et Expert.
```suggestion
   - Chaque playlist contient une répartition égale de beatmaps Hard, Insane et Expert.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +   - Chaque liste de lecture correspond à la lettre attribuée à chaque semaine. Par conséquent, chaque liste de lecture est rejouée une fois au cours d'une saison.
```suggestion
   - Chaque playlist correspond à la lettre attribuée à chaque semaine. Par conséquent, chaque playlist est rejouée une fois au cours d'une saison.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +   - Les classements des salles sont basés sur le système de score classé. Par conséquent, seuls les meilleurs résultats de chaque beatmap de la liste de lecture sont additionnés pour créer un classe
```suggestion
   - Les classements des salles sont basés sur le système de score classé. Par conséquent, seuls les meilleurs résultats de chaque beatmap de la playlist sont additionnés pour créer un classement hebdomadaire pour chaque utilisateur.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +   - Chaque beatmap d'une liste de lecture compte également pour le score du classement. Les difficultés plus difficiles ne donnent pas plus de points.
```suggestion
   - Chaque beatmap d'une playlist compte également pour le score du classement. Les difficultés plus difficiles ne donnent pas plus de points.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +## Listes de lecture
```suggestion
## Playlists
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +   - Il y aura une semaine d'interruption après laquelle les lobbies de chaque liste de lecture seront réouverts chaque semaine.
```suggestion
   - Il y aura une semaine d'interruption après laquelle les lobbies de chaque playlist seront réouverts chaque semaine.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +2. Chaque lobby temporaire multijoueur propose une liste de lecture prédéfinie de beatmaps.
```suggestion
2. Chaque lobby temporaire multijoueur propose une playlist prédéfinie de beatmaps.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +   - Chaque liste de lecture est un sous-ensemble de l'ensemble des beatmaps de la saison en cours.
```suggestion
   - Chaque playlist est un sous-ensemble de l'ensemble des beatmaps de la saison en cours.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +   - Chaque liste de lecture contient une répartition égale de beatmaps Hard, Insane et Expert.
```suggestion
   - Chaque playlist contient une répartition égale de beatmaps Hard, Insane et Expert.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +   - Chaque liste de lecture correspond à la lettre attribuée à chaque semaine. Par conséquent, chaque liste de lecture est rejouée une fois au cours d'une saison.
```suggestion
   - Chaque playlist correspond à la lettre attribuée à chaque semaine. Par conséquent, chaque playlist est rejouée une fois au cours d'une saison.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +   - Les classements des salles sont basés sur le système de score classé. Par conséquent, seuls les meilleurs résultats de chaque beatmap de la liste de lecture sont additionnés pour créer un classe
```suggestion
   - Les classements des salles sont basés sur le système de score classé. Par conséquent, seuls les meilleurs résultats de chaque beatmap de la playlist sont additionnés pour créer un classement hebdomadaire pour chaque utilisateur.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +   - Chaque beatmap d'une liste de lecture compte également pour le score du classement. Les difficultés plus difficiles ne donnent pas plus de points.
```suggestion
   - Chaque beatmap d'une playlist compte également pour le score du classement. Les difficultés plus difficiles ne donnent pas plus de points.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture A
```suggestion
#### Playlist A
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture B
```suggestion
#### Playlist B
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture C
```suggestion
#### Playlist C
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +#### Liste de lecture D
```suggestion
#### Playlist D
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +   - Chaque lettre représente la liste de lecture d'un lobby multijoueur hebdomadaire.
```suggestion
   - Chaque lettre représente la playlist d'un lobby multijoueur hebdomadaire.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +2. Les participants ne peuvent posséder qu'un seul score hebdomadaire classé par liste de lecture.
```suggestion
2. Les participants ne peuvent posséder qu'un seul score hebdomadaire classé par playlist.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +   - En rejouant une liste de lecture à une autre semaine, seul le meilleur score hebdomadaire classé comptera, écrasant le plus mauvais.
```suggestion
   - En rejouant une playlist à une autre semaine, seul le meilleur score hebdomadaire classé comptera, écrasant le plus mauvais.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +Le système de curation implique un processus de sélection par les curateurs des beatmaps mis en avant dans les Beatmap Spotlights pour chaque saison.
```suggestion
Le système de curation implique un processus de sélection par les curateurs des beatmaps mises en avant dans les Beatmap Spotlights pour chaque saison.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +1. Les beatmaps sont sélectionnés par les curateurs de leur mode de jeu respectif pour la durée d'une saison.
```suggestion
1. Les beatmaps sont sélectionnées par les curateurs de leur mode de jeu respectif pour la durée d'une saison.
```

2021-05-24 17:59 UTC, Ganondorfosu commented on wiki/Beatmap_Spotlights/fr.md
> +2. Les beatmaps sont sélectionnés en fonction de leur caractère unique et de leur excellence. Chaque beatmap sélectionné doit être un exemple de qualité de contenu en termes de gameplay, de design et
```suggestion
2. Les beatmaps sont sélectionnées en fonction de leur caractère unique et de leur excellence. Chaque beatmap sélectionnée doit être un exemple de qualité de contenu en termes de gameplay, de design et d'esthétique.
```

2021-05-24 20:34 UTC, Satsukel requested changes

2021-05-24 20:34 UTC, Satsukel commented on wiki/Beatmap_Spotlights/Seasons/2021_Spring/fr.md
> +1. Chaque semaine d'une saison, un seul lobby temporaire multijoueur est ouvert. Tout le monde peut y participer pendant toute la semaine.
```suggestion
1. Chaque semaine d'une saison, un seul lobby temporaire multijoueur est ouvert. Tout le monde peut y participer toute la semaine.
```

2021-05-24 20:34 UTC, Satsukel commented on wiki/Beatmap_Spotlights/Seasons/2021_Winter/fr.md
> +1. Chaque vendredi d'une saison, un seul lobby temporaire multijoueur est ouvert. Tout le monde peut y participer pendant toute la semaine.
```suggestion
1. Chaque vendredi d'une saison, un seul lobby temporaire multijoueur est ouvert. Tout le monde peut y participer toute la semaine.
```

2021-05-24 20:34 UTC, Satsukel commented on wiki/Beatmap_Spotlights/fr.md
> +   - 45% de toutes les beatmaps conservées devraient se situer dans le niveau de difficulté Insane.
```suggestion
   - 45% de toutes les beatmaps sélectionnées doivent se situer dans le niveau de difficulté Insane.
```

2021-05-24 20:34 UTC, Satsukel commented on wiki/Beatmap_Spotlights/fr.md
> +   - 25% de toutes les beatmaps conservées doivent se situer dans le niveau de difficulté Hard.
```suggestion
   - 25% de toutes les beatmaps sélectionnées doivent se situer dans le niveau de difficulté Hard.
```

2021-05-24 20:34 UTC, Satsukel commented on wiki/Beatmap_Spotlights/fr.md
> +   - Au moins 25 % des difficultés des beatmap sélectionnées doivent avoir été classées dans les 3 derniers mois précédant le début de la saison.
```suggestion
   - Au moins 25 % des difficultés des beatmaps sélectionnées doivent avoir été classées dans les 3 derniers mois précédant le début de la saison.
```

2021-05-24 20:34 UTC, Satsukel commented on wiki/Beatmap_Spotlights/fr.md
> +L'implémentation actuelle des Beatmap Spotlights est hautement expérimentale et peut changer à tout moment en fonction de la réaction des joueurs. Pour cette raison, il est important de recueillir au
```suggestion
L'implémentation actuelle des Beatmap Spotlights est hautement expérimentale et peut changer à tout moment en fonction de la réaction des joueurs. Pour cette raison, il est important de recueillir autant de commentaires et de critiques que possible pour améliorer continuellement la direction et la mise en œuvre de ce système. Les joueurs sont encouragés à laisser leurs impressions et leurs commentaires ici :
```

2021-05-24 20:34 UTC, Satsukel commented on wiki/Beatmap_Spotlights/fr.md
> +La direction du projet a changé plusieurs fois au cours de son histoire. ![][flag_US] [SapphireGhost](https://osu.ppy.sh/users/388602) a pris la tête du projet en mai 2012, suivi par ![][flag_US] [De
"renown" n'est pas dans le crochet dans la version anglaise mais la je savais pas comment tourner la phrase sans avoir à mettre "renom" dedans vu qu'il fallait la changer.
```suggestion
La direction du projet a changé plusieurs fois au cours de son histoire. ![][flag_US] [SapphireGhost](https://osu.ppy.sh/users/388602) a pris la tête du projet en mai 2012, suivi par ![][flag_US] [DeathXShinigami](https://osu.ppy.sh/users/49516) et ![][flag_US] [Makar](https://osu.ppy.sh/users/686389). ![][flag_DE] [Loctav](https://osu.ppy.sh/users/71366) et ![][flag_DE] [OnosakiHito](https://osu.ppy.sh/users/290128) ont repris le projet en décembre 2013. En mars 2015, le projet est passé de sa conception initiale de nomination et de vote à un système où [les membres de renom de la communauté sélectionnent à eux seuls une liste de beatmaps](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-season) qu'ils recommandent. En septembre 2016, le [système de sélection a été en grande partie annulé](https://osu.ppy.sh/home/news/2016-09-17-july-2016-ranking-charts-changes) et la [Quality Assurance Team](/wiki/Modding/Quality_Assurance_Team) a été chargée de sélectionner les beatmaps les plus remarquables.
```

2021-05-25 08:30 UTC, DoryanR commented on wiki/Beatmap_Spotlights/Seasons/2020_Autumn/fr.md
> +   - osu!taiko est incapable de présenter des mods en raison des limitations de lazer dans cette saison.
```suggestion
   - Aucun mod ne sera présent pour le mode osu!taiko en raison des limitations de osu!lazer dans cette saison.
```

2021-05-26 19:39 UTC, Ganondorfosu approved these changes

2021-06-09 14:40 UTC, DoryanR reviewed
Can be merge 👍

2021-06-13 21:58 UTC, TicClick approved these changes

2021-06-13 21:59 UTC, merged