[FR] Add "History of osu!" 2007 to 2011
ppy/osu-wiki pull request #5543
Opened 2021-05-22 12:14 UTC by Airwam

French translation of osu! wiki - History of osu! (2007 to 2011)

2021-05-22 12:25 UTC, DoryanR requested changes
Fix to pass the file verification check :

2021-05-22 12:25 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +## Décembre
Ajoute une ligne entre la ligne 91 et 92

2021-05-22 12:25 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +A la fin du mois de Juillet, le système de menus a été changé pour ajouter un peu de style au jeu. Une première implémentation des sliders a été réalisée, avec une balle orange non animée, et quelque
```suggestion
A la fin du mois de Juillet, le système de menus a été changé pour ajouter un peu de style au jeu. Une première implémentation des sliders a été réalisée, avec une balle orange non animée, et quelques courbes relativement moches. Le beat snapping a été ajouté a l'éditeur, ainsi qu'une timeline, et une interface d'édition plus robuste (similaire a celle visible dans [Composer](/wiki/Beatmap_Editor/Compose) aujourd'hui). 
```

2021-05-22 12:25 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées a l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le cu
```suggestion
Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées a l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le curseur ont été ajoutés, rendant les fonctionnalités de l'éditeur plus accessible qu'avant; les sliders ont été améliorés avec la présence de [slider ticks](/wiki/Beatmapping/Slider_tick); l'[empilement](/wiki/Mapping_Techniques/Stack) de [cercles](/wiki/Hit_object/Hit_circle) est présent; les scores locaux sont mieux supportés; et le format `.osu` a été revu et complètement refait, tout en incluant une conversion des anciens fichiers a ce nouveau format.
```

2021-05-22 12:25 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas ou la perfection était atteinte. Les mods [No video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_m
```suggestion
Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas ou la perfection était atteinte. Les mods [No video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_modifier/Hidden) (HD) ont étés introduits, les notes SH (S argenté) et SSH (SS argentés) également. Pour la première fois, les joueurs pouvaient modifier et assigner les sets d'échantillons normaux et doux suivant les sections. Les fichiers `.osz` peuvent maintenant être chargés avec un double-clic, ou en les glissant sur l'icône d'osu!.
```

2021-05-22 12:25 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +L'éditeur, le multijoueur, le storyboarding, les graphiques, et la console de chat ont tous reçu de nombreuses améliorations ce mois la. L'écran d'options a maintenant un nouveau modèle, et la [confi
```suggestion
L'éditeur, le multijoueur, le storyboarding, les graphiques, et la console de chat ont tous reçu de nombreuses améliorations ce mois la. L'écran d'options a maintenant un nouveau modèle, et la [configuration de touches](/wiki/Options/Keyboard_Bindings) ont été introduits.
```

2021-05-22 12:25 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Les records personnels en ligne ont été ajoutés au menu de sélection de musiques, remplissant une demande de longue date, qui demandait une optimisation assez conséquente de la base de données. Des a
```suggestion
Les records personnels en ligne ont été ajoutés au menu de sélection de musiques, remplissant une demande de longue date, qui demandait une optimisation assez conséquente de la base de données. Des améliorations graphiques ont été ajoutées a l'écran de résultat, et des éléments variés du skin par défaut ont été réalisés dans le but de les rendre plus propres et nets qu'avant. L'affichage du score des ticks de slider (10/30) a été implémenté. Des améliorations ont été vues dans la préparation des matchs multijoueurs, rendant possible le transfert du contrôle de la salle. De nombreuses nouvelles [commandes de chat](/wiki/Chat_Console#commands-list) ont été ajoutées pour les utilisateurs.
```

2021-05-22 12:30 UTC, Airwam commented on wiki/History_of_osu!/2007/fr.md
> +## Décembre
```suggestion
## Décembre

```

2021-05-22 12:51 UTC, DoryanR requested changes
Some elements to check and update links

(still need to check the links one last time, via Visual Studio Code)

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Ce qui suit contient certains des évènements majeurs de l'histoire d'osu!, et ce depuis début. Un grand merci a [Sinistro](https://osu.ppy.sh/users/5530) pour avoir aidé a compiler le contenu de 2007
```suggestion
Ce qui suit contient certains des évènements majeurs de l'histoire d'osu!, et ce depuis le début. Un grand merci a [Sinistro](https://osu.ppy.sh/users/5530) pour avoir aidé a compiler le contenu de 2007 et 2008. 
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +A la fin du mois de Juillet, le système de menus a été changé pour ajouter un peu de style au jeu. Une première implémentation des sliders a été réalisée, avec une balle orange non animée, et quelque
```suggestion
A la fin du mois de Juillet, le système de menus a été changé pour ajouter un peu de style au jeu. Une première implémentation des sliders a été réalisée, avec une balle orange non animée, et quelques courbes. Le beat snapping a été ajouté a l'éditeur, ainsi qu'une timeline, et une interface d'édition plus robuste (similaire a celle visible dans l'onglet [Compose](/wiki/Beatmap_Editor/Compose) aujourd'hui). 
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le gameplay a été amélioré avec les débuts du [combo fire](/wiki/Glossary/Combo_fire), de la barre de [Vie (ou HP)](/wiki/Beatmapping/Health), de la trainée du curseur, et des sliders plus beaux. A c
```suggestion
Le gameplay a été amélioré avec les débuts du [combo fire](/wiki/Glossary/Combo_fire), de la barre de [vie (ou HP)](/wiki/Beatmapping/Health), de la trainée du curseur, et des sliders plus beaux. A ce point la, osu! possède une humble collection d'environ 10 beatmaps, créés par l'équipe de test composée d'environ 5 personnes.
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +![](img/2007-09.jpg)
Ajoute un espace entre la ligne 45 et 46

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +L'écran de sélection de musiques a vu des améliorations avec le groupages des difficultés et un mouvement de scroll plus intuitif. Le set d'échantillons souples, les raccourcis clavier, et la recherc
```suggestion
L'écran de sélection de musiques a vu des améliorations avec le groupement des difficultés et un mouvement de scroll plus intuitif. Le set d'échantillons souples, les raccourcis clavier, et la recherche en jeu ont tous été ajoutés ce mois la. Les joueurs pouvait créer des [skins](/wiki/Skinning) globaux, mais aussi par beatmap pour la première fois, et les Tablet-PC ont été complètement supportés. 
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +`pUpdater`(`osume`) version 2 a été sortie, supportant des téléchargements optionnels. Cela incluait de rendre les premiers skins réalisés par les utilisateurs disponibles pour tous via l'updater. L'
```suggestion
`pUpdater`(`osume`) version 2 a été sortie, supportant des téléchargements optionnels. Cela incluait de rendre les premiers skins réalisés par les utilisateurs disponibles pour tous via l'updater. L'éditeur a vu l'ajout du [distance snap](/wiki/Beatmap_Editor/Distance_Snap), le support des signets, plusieurs types de courbes pour les sliders, couleur personnalisées, la possibilité de tester, le temps d'introduction, et bien plus.
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le [système de soumission de beatmaps](/wiki/Glossary#bss) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps
```suggestion
Le [système de soumission de beatmaps](/wiki/Glossary#bss) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps [En attente](/wiki/Beatmaps/Category#work-in-progress-et-en-attente) et [Classée](/wiki/Beatmaps/Category#classée) pour aider à l'organisation de la collection grandissante des maps soumises. Le chat en jeu a été ajouté grâce a un client [IRC](/wiki/Internet_Relay_Chat) (Internet Relay Chat) réalisé a partir de rien, et connecté a un serveur IRC standard (sans [Bancho](/wiki/Bancho_(server)));  le chat étendu était visible; les avatars et statistiques simples étaient affichés en jeu en utilisant une communication http; les contrôles audios ont aussi été ajoutés au menu principal, qui jouait une musique aléatoire au démarrage; les [replays](/wiki/Replay) pouvaient être regardés pour les score locaux et en ligne. Les joueurs pouvaient regarder d'autres joueurs (les données spectateurs étaient envoyées en brut via IRC).
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +# Histoire d'osu! 2007
```suggestion
# L'histoire d'osu! (2007)
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +# Histoire d'osu! 2008
```suggestion
# L'histoire d'osu! (2008)
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/game_modifier) ([Hard Rock](/wiki/HR), [Sudden Death](/wiki/SD), et [Double time](/wiki/DT)). L'expérience de jeu a été grandement a
```suggestion
Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/Game_modifier) ([Hard Rock](/wiki/HR), [Sudden Death](/wiki/Game_modifier/Sudden_Death), et [Double time](/wiki/Game_modifier/Double_time)). L'expérience de jeu a été grandement améliorée avec l'ajout d'images et sons de compte à rebours, des nombres et couleurs de combo personnalisées, des rangs de section O/X (Passé/Raté), d'un compte à rebours d'intro, couleur d'arrière plan scriptable, de la gestion du volume par section de timing et (sûrement le plus important) l'introduction du support des [Storyboard programmables](/wiki/Storyboard_Scripting). Un essai a été réalisé pour bouger osu! vers le framework XNAv2, mais peppy a décidé que la nouvelle version était inutile et réduisait les performances globales. XNA1.1 a été utilisé a partir de ce moment la, qui était adapté aux besoins d'osu! avec des milliers de lignes réécrites et des "hacks" pour faire d'osu! ce qu'il était. Un nouveau moteur de rendu pour le texte a également été implémenté, rendant possible l'utilisation de polices d'écritures plus nettes et de toutes tailles. Ce qui a rendu possible d'afficher plus d'information dans [l'éditeur de beatmaps](/wiki/Beatmap_Editor), et de rendre le jeu plus beau globalement.
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Peu après la sortie publique, les premiers [mods](/wiki/Game_modifier), [Easy](/wiki/Game_modifier/No_Fail) (EZ) et [No fail](/wiki/Game_modifier/No_Fail) (NF), ont été ajoutés, avec aussi les pauses
```suggestion
Peu après la sortie publique, les premiers [mods](/wiki/Game_modifier), [Easy](/wiki/Game_modifier/Easy) (EZ) et [No fail](/wiki/Game_modifier/No_Fail) (NF), ont été ajoutés, avec aussi les pauses (qui jusque la étaient ignorées et manquaient). Un grand nombre de changements ont rapidement fait qu'osu! ressemblait de plus en plus a un jeu de rythme légitime.
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Pour contrebalancer les nouveaux mods de février, les mods [Relax](/wiki/RL) (RX) et [Half Time](/wiki/HT) (HT) sont arrivés pour rendre la vie des joueurs plus simple ce mois-ci. Les utilisateurs so
```suggestion
Pour contrebalancer les nouveaux mods de février, les mods [Relax](/wiki/Game_modifier/Relax) (RX) et [Half Time](/wiki/Game_modifier/Half_time) (HT) sont arrivés pour rendre la vie des joueurs plus simple ce mois-ci. Les utilisateurs sont a présent capables de prendre des captures d'écrans, et d'importer ou exporter des [replays](/wiki/Replay). Les animations peuvent être [storyboardées](/wiki/Storyboards) pour la première fois, et le menu de sélection de skin a été ajouté. Les optimisations de performances ont vu une chute de 82% pour le chargement du menu de sélection des musiques (via un nouveau format pour la base de données de beatmaps locale). D'autres ajustements liés a la performance ont été réalisés, incluant l'introduction du limiteur de fps, et quelques autres options graphiques. Le projet [Bancho](/wiki/Glossary#bancho) a commencé le 24 mars 2008. L'idée était de créer un serveur pour la famille osu!, qui gérerait les communications entre les utilisateurs et enlèverait la dépendance a l'[IRC](/wiki/Internet_Relay_Chat).
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Sans blague, Bancho a été lancé en avril, et avec lui les panneaux d'utilisateurs du [Chat Étendu](/wiki/Chat_Console#extended-chat-console). Les utilisateurs sont maintenant capable de voir ce que l
```suggestion
Sans blague, Bancho a été lancé en avril, et avec lui les panneaux d'utilisateurs du [Chat Étendu](/wiki/Chat_Console#extended-chat-console). Les utilisateurs sont maintenant capable de voir ce que les autres utilisateurs font dans leur panneau d'utilisateur, et peuvent également interagir avec eux en cliquant pour les observer. Le système d'erreur de soumissions automatique a démarré, la compatibilité xfire a été implémentée, et le menu principal et l'interface de l'éditeur ont reçu un relooking (avec les nouvelles icônes par [LuigiHann](https://osu.ppy.sh/users/1079)). L'interface de la console de chat a vu l'ajout du bouton "Afficher le chat", l'onglet "tab completion", et les alertes de mentions de pseudos. L'écran des scores montre maintenant le nombre de points requis pour atteindre le prochain rang.
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Un nouveau statut classé a été ajouté, "![](/img/fire.gif) [Approuvée](/wiki/Approved)" pour les maps de grande qualités, mais qui excédaient les critères de classement de longueur, difficulté, ou au
```suggestion
Un nouveau statut classé a été ajouté, "![](/img/fire.gif) [Approuvée](/wiki/Beatmap/Category#approuvée)" pour les maps de grande qualités, mais qui excédaient les critères de classement de longueur, difficulté, ou autres d'une manière ou d'une autre. Les maps dans ce statut ne comptent pas pour les scores du joueurs, mais possèdent des classements, et se comportent comme une map ![](img/heart.gif) [Classée](/wiki/Beatmap/Category#classée).
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Une série de nouveau mods a été rendue publique ce mois-ci : [Flashlight](/wiki/FL), [Spun Out](/wiki/SO) et [Auto](/wiki/AT). Auto émule un joueur artificiel qui peut compléter (presque) n'importe q
```suggestion
Une série de nouveau mods a été rendue publique ce mois-ci : [Flashlight](/wiki/Game_modifier/Flashlight), [Spun Out](/wiki/Game_modifier/Spun_Out) et [Auto](/wiki/Game_modifier/Auto). Auto émule un joueur artificiel qui peut compléter (presque) n'importe quelle beatmap avec une [précision](/wiki/Accuracy) parfaite, et est aussi accessible depuis le mode de test de l'éditeur. Les limites de la création des beatmaps ont été poussées plus loin avec l'ajout de plus d'éléments personnalisables (incluant les [images de comboburst](/wiki/Glossary/comboburst), le sample du son du clap, la possibilité d'assigner des sons a des points individuels de sliders et des sections de timing en découlant). Le menu de sélection des musiques a aussi reçu une refonte. 
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Novembre a vu l'introduction d'un tout nouveau mode de jeu, Catch the Beat. Le support d'OpenGL a démarré, permettant donc a osu! de tourner sur la majorité des systèmes. D'autres nouvelles fonctionn
```suggestion
Novembre a vu l'introduction d'un tout nouveau mode de jeu, Catch the Beat. Le support d'OpenGL a démarré, permettant donc a osu! de tourner sur la majorité des systèmes. D'autres nouvelles fonctionnalités incluent le support de la liste d'amis en jeu, de canaux de chat privés, un nouveau tutoriel pour l'[offset wizard](/wiki/Options/Offset_Wizard) et osu!direct (une plateforme en jeu pour télécharger des beatmaps).
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Le dernier mois de 2008 a eu beaucoup en stock pour le développement d'osu!. Au deuxième noël d'osu!, la première version de l'éditeur de storyboards a été implémentée, rendant le storyboarding beauc
```suggestion
Le dernier mois de 2008 a eu beaucoup en stock pour le développement d'osu!. Au deuxième noël d'osu!, la première version de l'éditeur de storyboards a été implémentée, rendant le storyboarding beaucoup plus accessible aux utilisateurs. Un deuxième mode de jeu multijoueur a été ajouté : "Tag Play". C'était une mode coopératif ou les joueurs jouaient chacun leur tour sur une beatmap. Un autre ajout au multijoueur était la "Victoire sur l'accuracy". MSN et Yahoo ont été intégrés, et les utilisateurs pouvaient entièrement personnaliser leurs touches de jeu et les mots à notifications.
```

2021-05-22 12:51 UTC, DoryanR commented on wiki/History_of_osu!/2011/fr.md
> +Liens:
```suggestion
Liens :
```

2021-05-23 19:52 UTC, Ganondorfosu requested changes

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées a l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le cu
```suggestion
Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées a l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le curseur ont été ajoutés, rendant les fonctionnalités de l'éditeur plus accessibles qu'avant; les sliders ont été améliorés avec la présence de [slider ticks](/wiki/Beatmapping/Slider_tick); l'[empilement](/wiki/Mapping_Techniques/Stack) de [cercles](/wiki/Hit_object/Hit_circle) était présent; les scores locaux étaient mieux pris en charge; et le format `.osu` a été revu et complètement refait, tout en incluant une conversion des anciens fichiers à ce nouveau format.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Le gameplay a été amélioré avec les débuts du [combo fire](/wiki/Glossary/Combo_fire), de la barre de [Vie (ou HP)](/wiki/Beatmapping/Health), de la trainée du curseur, et des sliders plus beaux. A c
```suggestion
Le gameplay a été amélioré avec les débuts du [combo fire](/wiki/Glossary/Combo_fire), de la barre de [vie (ou HP)](/wiki/Beatmapping/Health), de la trainée du curseur, et des sliders plus beaux. À ce stade, osu! possède une humble collection d'environ 10 beatmaps, créées par l'équipe de test composée d'environ 5 personnes.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Le 17 septembre 2007 marque la "naissance" d'osu! pour le grand public. Les forums tels qu'on les connais on été établis, et hébergés sur le domaine de peppy (`ppy.sh`). L'attention du public a été g
```suggestion
Le 17 septembre 2007 marque la "naissance" d'osu! pour le grand public. Les forums tels que nous les connaissons aujourd'hui ont été établis, et hébergés sur le domaine de peppy (`ppy.sh`). L'attention du public a été gagnée via un article sur le site [bemanistyle](http://bemanistyle.com) qui a fait quelques intéressés dans les habitués de jeux de rythme.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +![](img/2007-09_05.jpg "Annonce sur un site de jeux-vidéos")
```suggestion
![](img/2007-09_05.jpg "Annonce sur un site de jeux-vidéo")
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Peu après la sortie publique, les premiers [mods](/wiki/Game_modifier), [Easy](/wiki/Game_modifier/No_Fail) (EZ) et [No fail](/wiki/Game_modifier/No_Fail) (NF), ont été ajoutés, avec aussi les pauses
```suggestion
Peu après la sortie publique, les premiers [mods](/wiki/Game_modifier), [Easy](/wiki/Game_modifier/Easy) (EZ) et [No fail](/wiki/Game_modifier/No_Fail) (NF), ainsi que les pauses (qui jusque-là étaient ignorées et manquaient) ont été ajoutés. Un grand nombre de changements ont rapidement fait qu'osu! ressemblait de plus en plus à un jeu de rythme légitime.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Le 1er octobre 2007 est le jour où les classement en ligne ont été disponibles publiquement. Cette date a aussi vu le lancement de la méthode de compression en `.osz`, ainsi que d'une base de données
```suggestion
Le 1er octobre 2007 est le jour où les classements en ligne ont été implémentés publiquement. Cette date a aussi vu le lancement de la méthode de compression en `.osz`, ainsi que d'une base de données de beatmaps en ligne accompagnée d'un premier système de soumission de beatmaps. Les classements en ligne ont été ajoutés à l'interface en jeu, mais également affichés sur le site.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas ou la perfection était atteinte. Les mods [No video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_m
```suggestion
Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas où la perfection était atteinte. Les mods [No video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_modifier/Hidden) (HD) ont été introduits, les notes SH (S argenté) et SSH (SS argenté) également. Pour la première fois, les joueurs pouvaient modifier et assigner les sets d'échantillons normaux et soft suivant les sections. Les fichiers `.osz` pouvaient maintenant être chargés avec un double-clic, ou en les glissant sur l'icône d'osu!.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +L'écran de sélection de musiques a vu des améliorations avec le groupages des difficultés et un mouvement de scroll plus intuitif. Le set d'échantillons souples, les raccourcis clavier, et la recherc
```suggestion
L'écran de sélection de musiques a vu des améliorations avec le groupement des difficultés et un mouvement de scroll plus intuitif. Le set d'échantillons soft, les raccourcis clavier, et la recherche en jeu ont tous été ajoutés ce mois-là. Les joueurs pouvaient créer des [skins](/wiki/Skinning) globaux, mais aussi par beatmap pour la première fois, et la prise en charge complète des Tablet-PC a été implémentée.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +`pUpdater`(`osume`) version 2 a été sortie, supportant des téléchargements optionnels. Cela incluait de rendre les premiers skins réalisés par les utilisateurs disponibles pour tous via l'updater. L'
```suggestion
La version 2 de `pUpdater`(`osume`) a été publiée, prenant en charge des téléchargements optionnels. Cela a permis de rendre les premiers skins réalisés par les utilisateurs disponibles pour tous via l'updater. L'éditeur a vu l'ajout du [distance snap](/wiki/Beatmap_Editor/Distance_Snap), le support des signets, plusieurs types de courbes pour les sliders, des couleurs personnalisées, la possibilité de tester la beatmap, le temps d'introduction, et bien plus.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Les musiques peuvent être éditées en les glissant dans la fenêtre osu!; les infos-bulles qui expliquent les boutons variés des menus d'osu! et de l'interface d'édition ont été ajoutés; beaucoup de no
```suggestion
Les musiques peuvent être éditées en les glissant dans la fenêtre d'osu!; les info-bulles qui expliquent les boutons variés des menus d'osu! et de l'interface d'édition ont été ajoutées; beaucoup de nouveau skins de qualité ont été soumis par les premiers skinners ([Holiday par LuigiHann](https://osu.ppy.sh/community/forums/topics/1139), [WindWaker par awp](https://osu.ppy.sh/community/forums/topics/761)); de nouvelles méthodes de tri ont été ajoutées au menu de sélection de musiques; peppy pouvait maintenant envoyer des annonces globales à tous les joueurs d'osu!; et des changements mineurs ont été apportés au gameplay.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +peppy est parti au Japon du 17 décembre 2007 au 20 janvier 2008. Il a réussi a se détacher de la programmation d'osu! pendant un mois entier, et il n'y a donc eu aucune mise à jour majeure (pendant q
```suggestion
peppy est parti au Japon du 17 décembre 2007 au 20 janvier 2008. Il a réussi à se détacher de la programmation d'osu! pendant un mois entier, et il n'y a donc eu aucune mise à jour majeure (pendant que la communauté restait stable pendant cette période).
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/game_modifier) ([Hard Rock](/wiki/HR), [Sudden Death](/wiki/SD), et [Double time](/wiki/DT)). L'expérience de jeu a été grandement a
```suggestion
Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/game_modifier) ([Hard Rock](/wiki/Hard_Rock), [Sudden Death](/wiki/Game_modifier/Sudden_Death), et [Double Time](/wiki/Game_modifier/Double_time)). L'expérience de jeu a été grandement améliorée avec l'ajout d'images et de sons de compte à rebours, des nombres et couleurs de combo personnalisées, des rangs de section O/X (Passé/Raté), d'un compte à rebours d'intro, couleur d'arrière plan scriptable, de la gestion du volume par section de timing et (sûrement le plus important) l'introduction du support des [storyboards programmables](/wiki/Storyboard_Scripting). Un essai a été réalisé pour bouger osu! vers le framework XNAv2, mais peppy a décidé que la nouvelle version était inutile et réduisait les performances globales. XNA1.1 a été utilisé à partir de ce moment-là, qui était adapté aux besoins d'osu! avec des milliers de lignes réécrites et des "hacks" pour faire d'osu! ce qu'il était. Un nouveau moteur de rendu pour le texte a également été implémenté, rendant possible l'utilisation de polices d'écriture plus nettes et de toutes tailles. Ce qui a permis d'afficher plus d'information dans [l'éditeur](/wiki/Beatmap_Editor), et de rendre le jeu plus beau globalement.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Sans blague, Bancho a été lancé en avril, et avec lui les panneaux d'utilisateurs du [Chat Étendu](/wiki/Chat_Console#extended-chat-console). Les utilisateurs sont maintenant capable de voir ce que l
```suggestion
Sans blague, Bancho a été lancé en avril, et avec lui les panneaux d'utilisateurs du [Chat Étendu](/wiki/Chat_Console#extended-chat-console). Les utilisateurs pouvaient maintenant voir ce que les autres utilisateurs faisaient dans leurs panneaux d'utilisateur, et pouvaient également interagir avec eux en cliquant pour les observer. Le système de soumission d'erreurs automatique a été ajouté, la compatibilité xfire a été implémentée, et le menu principal et l'interface de l'éditeur ont reçu un relooking (avec les nouvelles icônes par [LuigiHann](https://osu.ppy.sh/users/1079)). L'interface de la console de chat a vu l'ajout du bouton "Afficher le chat", l'onglet "tab completion", et les alertes de mentions de pseudos. L'écran des scores montrait maintenant le nombre de points requis pour atteindre le prochain rang.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Le mode [Taiko](/wiki/Game_mode/osu!taiko) a vu le jour ce mois-ci, avec un autre ajout majeur, le support des scripts en `.osb` pour le storyboarding. Les sliders contenant plusieurs parties et les
```suggestion
Le mode [Taiko](/wiki/Game_mode/osu!taiko) a vu le jour ce mois-ci, avec un autre ajout majeur, la prise en charge des scripts en `.osb` pour le storyboarding. Les sliders contenant plusieurs parties ainsi que les messages privés sont également devenus disponibles.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +L'éditeur, le multijoueur, le storyboarding, les graphiques, et la console de chat ont tous reçu de nombreuses améliorations ce mois la. L'écran d'options a maintenant un nouveau modèle, et la [confi
```suggestion
L'éditeur, le multijoueur, le storyboarding, les graphiques, et la console de chat ont tous reçu de nombreuses améliorations ce mois-là. L'écran d'options a maintenant un nouveau modèle, et la [configuration de touches](/wiki/Options/Keyboard_Bindings) a été introduite.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Une étape importante de l'histoire d'osu! a été atteinte avec l'ajout du mode de jeu [Multi (multijoueur)](/wiki/Multi). Les possibilités de skinning ont été agrandies pour a la fois le coté graphiqu
```suggestion
Une étape importante de l'histoire d'osu! a été atteinte avec l'ajout du mode de jeu [Multi (multijoueur)](/wiki/Multi). Les possibilités de skinning ont été agrandies pour à la fois le coté graphique et sonore. Finalement, le chat multi-canal a été possible pour la première fois.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Continuant sur la tendance de juillet, un joueur aura du mal a trouvé un aspect d'osu! qui n'a pas été amélioré ou optimisé durant ce mois. Dans toutes ces nouvelles additions, les tags ont été ajout
```suggestion
Continuant sur la tendance de juillet, un joueur aura du mal à trouver un aspect d'osu! qui n'a pas été amélioré ou optimisé durant ce mois. Parmi tous ces nouveaux ajouts, les tags ont été ajoutés aux beatmaps, et le support pour plusieurs écrans a été implémenté à un niveau expérimental. Une nouvelle méthode pour reprendre après une pause a été construite pour empêcher les joueurs d'abuser de la fonction de pause (qui demandait aux joueurs d'aligner leur curseur à l'endroit où il se situait avant la pause pour continuer).
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Les records personnels en ligne ont été ajoutés au menu de sélection de musiques, remplissant une demande de longue date, qui demandait une optimisation assez conséquente de la base de données. Des a
```suggestion
Les records personnels en ligne ont été ajoutés au menu de sélection de musiques, remplissant une demande de longue date, qui demandait une optimisation assez conséquente de la base de données. Des améliorations graphiques ont été ajoutées à l'écran de résultat, et des éléments variés du skin par défaut ont été réalisés dans le but de les rendre plus propres et nets qu'avant. L'affichage du score des slider ticks (10/30) a été ajouté. Des améliorations ont été vues dans la préparation des matchs multijoueurs, rendant possible le transfert du contrôle de la salle. De nombreuses nouvelles [commandes de chat](/wiki/Chat_Console#commands-list) ont été ajoutées pour les utilisateurs.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Des progrès ont été réalisés sur l'implémentation d'OpenGL et le nouveau mode de jeu ([Catch the Beat](/wiki/game_mode/osu!catch)), dans un environnement de test privé. Une partie d'osu! a été réécri
```suggestion
Des progrès ont été réalisés sur l'implémentation d'OpenGL et le nouveau mode de jeu ([Catch the Beat](/wiki/game_mode/osu!catch)), dans un environnement de test privé. Une partie d'osu! a été réécrite, totalisant plus de 4000 lignes de code complètement revues afin de rendre les modes de jeu plus modulaires pour que les modes futurs puissent être ajoutés plus simplement. À cause de ces changements, il n'y a pas eu de mise à jour publique en Octobre. 
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2008/fr.md
> +Suite aux complaintes de personnes avec un grand nombre de beatmaps a propos du temps de chargement d'osu!, peppy a passé de nombreux jours a optimiser tout ce qui était possible, résultant en une am
```suggestion
Suite aux plaintes de personnes ayant un grand nombre de beatmaps sur le temps de chargement d'osu!, peppy a passé de nombreux jours à optimiser tout ce qui était possible, résultant en une amélioration presque immesurable. Les chargements de plus d'une minute ont été réduits à quelques millisecondes.
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2009/fr.md
> +osu! passe sur iPhone grâce a un portage sur iPhone par nuudles. Le projet a eu son propre [sous-forum](https://osu.ppy.sh/community/forums/47)
```suggestion
osu! passe sur iPhone grâce à un portage sur iPhone par nuudles. Le projet a eu son propre [sous-forum](https://osu.ppy.sh/community/forums/47)
```

2021-05-23 19:52 UTC, Ganondorfosu commented on wiki/History_of_osu!/2011/fr.md
> +Le wiki osu! a été annoncé, permettant aux utilisateurs d'ajouter toute sortes d'informations a propos de tout ce qui est lié à osu!.
```suggestion
Le wiki osu! a été annoncé, permettant aux utilisateurs d'ajouter toutes sortes d'informations sur tout ce qui est lié à osu!.
```

2021-05-24 09:36 UTC, Airwam commented on wiki/History_of_osu!/2007/fr.md
> +![](img/2007-09.jpg)
```suggestion
![](img/2007-09.jpg)

```

2021-05-24 09:49 UTC, DoryanR requested changes
For the links (see to do it on the other files)

2021-05-24 09:49 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +osu! a débuté en tant que preuve de concept nommée "ouentest". La première version a été publiée le 1er Juillet 2007 à un petit groupe d'amis proches de [peppy](https://osu.ppy.sh/users/2) et contena
```suggestion
osu! a débuté en tant que preuve de concept nommée "ouentest". La première version a été publiée le 1er Juillet 2007 à un petit groupe d'amis proches de [peppy](https://osu.ppy.sh/users/2) et contenait un [éditeur de beatmaps](/wiki/Beatmap_Editor) très basique ainsi qu'un mode de jeu. L'éditeur pouvait seulement permettre la création de [beatmaps](/wiki/Beatmap) *très* simplistes sans fonction de recherche ou de [snapping](/wiki/Beatmapping/Snapping) disponibles, et il n'y avait ni sliders, ni spinners, seulement des cercles et des compteurs basiques de score/combo. La première version a pris environ 16 heures de programmation, et a été réalisée en *une seule nuit blanche*. `pUpdater` a été introduit (connu peu après sous le nom d'`osume`) pour prendre en charge les mises à jour à la dernière version.
```

2021-05-24 09:49 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le [système de soumission de beatmaps](/wiki/Glossary#bss) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps
```suggestion
Le [système de soumission de beatmaps](/wiki/Glossary#bss) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps [En attente](/wiki/Beatmap/Category#work-in-progress-et-en-attente) et [Classée](/wiki/Beatmap/Category#classée) pour aider à l'organisation de la collection grandissante des maps soumises. Le chat en jeu a été ajouté grâce a un client [IRC](/wiki/Internet_Relay_Chat) (Internet Relay Chat) réalisé a partir de rien, et connecté a un serveur IRC standard (sans [Bancho](/wiki/Bancho_(server)));  le chat étendu était visible; les avatars et statistiques simples étaient affichés en jeu en utilisant une communication http; les contrôles audios ont aussi été ajoutés au menu principal, qui jouait une musique aléatoire au démarrage; les [replays](/wiki/Replay) pouvaient être regardés pour les score locaux et en ligne. Les joueurs pouvaient regarder d'autres joueurs (les données spectateurs étaient envoyées en brut via IRC).
```

2021-05-24 09:49 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/Game_modifier) ([Hard Rock](/wiki/HR), [Sudden Death](/wiki/Game_modifier/Sudden_Death), et [Double time](/wiki/Game_modifier/Double
```suggestion
Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/Game_modifier) ([Hard Rock](/wiki/Game_modifier/Hard_Rock), [Sudden Death](/wiki/Game_modifier/Sudden_Death), et [Double time](/wiki/Game_modifier/Double_time)). L'expérience de jeu a été grandement améliorée avec l'ajout d'images et sons de compte à rebours, des nombres et couleurs de combo personnalisées, des rangs de section O/X (Passé/Raté), d'un compte à rebours d'intro, couleur d'arrière plan scriptable, de la gestion du volume par section de timing et (sûrement le plus important) l'introduction du support des [Storyboard programmables](/wiki/Storyboard_Scripting). Un essai a été réalisé pour bouger osu! vers le framework XNAv2, mais peppy a décidé que la nouvelle version était inutile et réduisait les performances globales. XNA1.1 a été utilisé a partir de ce moment la, qui était adapté aux besoins d'osu! avec des milliers de lignes réécrites et des "hacks" pour faire d'osu! ce qu'il était. Un nouveau moteur de rendu pour le texte a également été implémenté, rendant possible l'utilisation de polices d'écritures plus nettes et de toutes tailles. Ce qui a rendu possible d'afficher plus d'information dans [l'éditeur de beatmaps](/wiki/Beatmap_Editor), et de rendre le jeu plus beau globalement.
```

2021-05-24 16:31 UTC, Ganondorfosu commented on wiki/History_of_osu!/2007/fr.md
> +Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées a l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le cu
```suggestion
Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées à l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le curseur ont été ajoutés, rendant les fonctionnalités de l'éditeur plus accessibles qu'avant; les sliders ont été améliorés avec la présence de [slider ticks](/wiki/Beatmapping/Slider_tick); l'[empilement](/wiki/Mapping_Techniques/Stack) de [cercles](/wiki/Hit_object/Hit_circle) était présent; les scores locaux étaient mieux pris en charge; et le format `.osu` a été revu et complètement refait, tout en incluant une conversion des anciens fichiers à ce nouveau format.
```

2021-05-24 16:36 UTC, DoryanR requested changes

2021-05-24 16:36 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le [système de soumission de beatmaps](/wiki/Glossary#bss) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps
```suggestion
Le [système de soumission de beatmaps](/wiki/Submission) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps [En attente](/wiki/Beatmap/Category#work-in-progress-et-en-attente) et [Classée](/wiki/Beatmap/Category#classée) pour aider à l'organisation de la collection grandissante des maps soumises. Le chat en jeu a été ajouté grâce a un client [IRC](/wiki/Internet_Relay_Chat) (Internet Relay Chat) réalisé a partir de rien, et connecté a un serveur IRC standard (sans [Bancho](/wiki/Bancho_(server)));  le chat étendu était visible; les avatars et statistiques simples étaient affichés en jeu en utilisant une communication http; les contrôles audios ont aussi été ajoutés au menu principal, qui jouait une musique aléatoire au démarrage; les [replays](/wiki/Replay) pouvaient être regardés pour les score locaux et en ligne. Les joueurs pouvaient regarder d'autres joueurs (les données spectateurs étaient envoyées en brut via IRC).
```

2021-05-24 16:36 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Pour contrebalancer les nouveaux mods de février, les mods [Relax](/wiki/Game_modifier/Relax) (RX) et [Half Time](/wiki/Game_modifier/Half_time) (HT) sont arrivés pour rendre la vie des joueurs plus
```suggestion
Pour contrebalancer les nouveaux mods de février, les mods [Relax](/wiki/Game_modifier/Relax) (RX) et [Half Time](/wiki/Game_modifier/Half_time) (HT) sont arrivés pour rendre la vie des joueurs plus simple ce mois-ci. Les utilisateurs sont a présent capables de prendre des captures d'écrans, et d'importer ou exporter des [replays](/wiki/Replay). Les animations peuvent être [storyboardées](/wiki/Storyboards) pour la première fois, et le menu de sélection de skin a été ajouté. Les optimisations de performances ont vu une chute de 82% pour le chargement du menu de sélection des musiques (via un nouveau format pour la base de données de beatmaps locale). D'autres ajustements liés a la performance ont été réalisés, incluant l'introduction du limiteur de fps, et quelques autres options graphiques. Le projet [Bancho](/wiki/BanchoBot) a commencé le 24 mars 2008. L'idée était de créer un serveur pour la famille osu!, qui gérerait les communications entre les utilisateurs et enlèverait la dépendance a l'[IRC](/wiki/Internet_Relay_Chat).
```

2021-06-02 16:53 UTC, Airwam commented on wiki/History_of_osu!/2007/fr.md
> +Le 1er octobre 2007 est le jour où les classements en ligne ont été implémentés publiquement. Cette date a aussi vu le lancement de la méthode de compression en `.osz`, ainsi que d'une base de donnée
```suggestion
Le 6 octobre 2007 est le jour où les classements en ligne ont été implémentés publiquement. Cette date a aussi vu le lancement de la méthode de compression en `.osz`, ainsi que d'une base de données de beatmaps en ligne accompagnée d'un premier système de soumission de beatmaps. Les classements en ligne ont été ajoutés à l'interface en jeu, mais également affichés sur le site.
```

2021-06-03 14:21 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +![](img/2007-07_04.jpg "Cercles d'approches")
```suggestion
![](img/2007-07_04.jpg "Cercles")
```

2021-06-03 14:22 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +À la fin du mois de Juillet, le système de menus a été changé pour ajouter un peu de style au jeu. Une première implémentation des sliders a été réalisée avec une balle orange non animée et quelques
```suggestion
À la fin du mois de juillet, le système de menus a été changé pour ajouter un peu de style au jeu. Une première implémentation des sliders a été réalisée avec une balle orange non animée et quelques courbes. Le beat snapping a été ajouté à l'éditeur, ainsi qu'une timeline, et une interface d'édition plus robuste (similaire à celle visible dans l'onglet [Compose](/wiki/Beatmap_Editor/Compose) d'aujourd'hui). 
```

2021-06-03 14:23 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées à l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le cu
```suggestion
Le menu principal a été mis à jour avec un nouveau look, et beaucoup de fonctionnalités ont été ajoutées à l'éditeur, incluant le support du copier-coller. La barre de menu de Windows ainsi que le curseur ont été ajoutés, rendant les fonctionnalités de l'éditeur plus accessibles qu'avant ; les sliders ont été améliorés avec la présence des [sliders ticks](/wiki/Beatmapping/Slider_tick) ; l'[empilement](/wiki/Mapping_Techniques/Stack) de [cercles](/wiki/Hit_object/Hit_circle) était présent ; les scores locaux étaient mieux pris en charge ; et le format `.osu` a été revu et complètement refait, tout en incluant une conversion des anciens fichiers à ce nouveau format.
```

2021-06-03 14:24 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +![](img/2007-08_02.jpg "Évolution graphique des hits")
```suggestion
![](img/2007-08_02.jpg "Évolution graphique des frappes")
```

2021-06-03 14:25 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le 17 septembre 2007 marque la "naissance" d'osu! pour le grand public. Les forums tels que nous les connaissons aujourd'hui ont été établis, et hébergés sur le domaine de peppy (`ppy.sh`). L'attenti
```suggestion
Le 17 septembre 2007 marque la "naissance" d'osu! pour le grand public. Les forums ont été établis, et hébergés sur le domaine de peppy (`ppy.sh`). L'attention du public a été gagnée via un article sur le site [bemanistyle](http://bemanistyle.com) qui a fait quelques intéressés dans les habitués de jeux de rythme.
```

2021-06-03 14:26 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Peu après la sortie publique, les premiers [mods](/wiki/Game_modifier), [Easy](/wiki/Game_modifier/Easy) (EZ) et [No fail](/wiki/Game_modifier/No_Fail) (NF), ainsi que les pauses (qui jusque-là étaie
```suggestion
Peu après la sortie publique, les premiers [mods](/wiki/Game_modifier), [Easy](/wiki/Game_modifier/Easy) (EZ) et [No Fail](/wiki/Game_modifier/No_Fail) (NF), ainsi que les pauses (qui jusque-là étaient ignorées et manquaient) ont été ajoutés. Un grand nombre de changements ont rapidement fait qu'osu! ressemblait de plus en plus à un jeu de rythme légitime.
```

2021-06-03 14:27 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +![](img/2007-10_02.jpg "Menu de sélection de musiques dans le mode solo")
Met un espace entre la ligne 69 et 70

2021-06-03 14:28 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas où la perfection était atteinte. Les mods [No video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_m
```suggestion
Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas où la perfection était atteinte. Les mods [No Video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_modifier/Hidden) (HD) ont été introduits, les notes S argenté et SS argenté également. Pour la première fois, les joueurs pouvaient modifier et assigner les sets d'échantillons normal et soft suivant les sections. Les fichiers `.osz` pouvaient maintenant être chargés avec un double-clic, ou en les glissant sur l'icône d'osu!.
```

2021-06-03 14:30 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Le [système de soumission de beatmaps](/wiki/Submission) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps [E
```suggestion
Le [système de soumission de beatmaps](/wiki/Submission) (BSS) a été rendu public, autorisant les utilisateurs à facilement envoyer et partager leurs créations. Cela a introduit le statut des maps [En attente](/wiki/Beatmap/Category#work-in-progress-et-en-attente) et [Classée](/wiki/Beatmap/Category#classée) pour aider à l'organisation de la collection grandissante des maps soumises. Le chat en jeu a été ajouté grâce a un client [IRC](/wiki/Internet_Relay_Chat) (Internet Relay Chat) réalisé a partir de rien, et connecté a un serveur IRC standard (sans [Bancho](/wiki/Bancho_(server))) ; le chat étendu était visible ; les avatars et statistiques simples étaient affichés en jeu en utilisant une communication `http` ; les contrôles audios ont aussi été ajoutés au menu principal, qui jouait une musique aléatoire au démarrage ; les [replays](/wiki/Replay) pouvaient être regardés pour les score locaux et en ligne. Les joueurs pouvaient regarder d'autres joueurs (les données spectateurs étaient envoyées en brut via IRC).
```

2021-06-03 14:31 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +Les musiques peuvent être éditées en les glissant dans la fenêtre d'osu!; les info-bulles qui expliquent les boutons variés des menus d'osu! et de l'interface d'édition ont été ajoutées; beaucoup de
```suggestion
Les musiques peuvent être éditées en les glissant dans la fenêtre d'osu! ; les info-bulles qui expliquent les boutons variés des menus d'osu! et de l'interface d'édition ont été ajoutées ; beaucoup de nouveau skins de qualité ont été soumis par les premiers skinners ([Holiday par LuigiHann](https://osu.ppy.sh/community/forums/topics/1139), et [WindWaker par awp](https://osu.ppy.sh/community/forums/topics/761)) ; de nouvelles méthodes de tri ont été ajoutées au menu de sélection de musiques ; peppy pouvait maintenant envoyer des annonces globales à tous les joueurs d'osu! ; et des changements mineurs ont été apportés au gameplay.
```

2021-06-03 14:33 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/Game_modifier) ([Hard Rock](/wiki/Game_modifier/Hard_Rock), [Sudden Death](/wiki/Game_modifier/Sudden_Death), et [Double time](/wiki
```suggestion
Les joueurs ont eu de nouveaux défis sous la forme de [mods](/wiki/Game_modifier) ([Hard Rock](/wiki/Game_modifier/Hard_Rock), [Sudden Death](/wiki/Game_modifier/Sudden_Death), et [Double Time](/wiki/Game_modifier/Double_time)). L'expérience de jeu a été grandement améliorée avec l'ajout d'images et sons de compte à rebours, des nombres et couleurs de combo personnalisées, des rangs de section O/X (Passé/Raté), d'un compte à rebours d'intro, couleur d'arrière plan scriptable, de la gestion du volume par section de timing et (sûrement le plus important) l'introduction du support des [Storyboard programmables](/wiki/Storyboard_Scripting). Un essai a été réalisé pour déplacer osu! vers le framework XNAv2, mais peppy a décidé que la nouvelle version était inutile et réduisait les performances globales. XNA1.1 a été utilisé a partir de ce moment la, qui était adapté aux besoins d'osu! avec des milliers de lignes réécrites et des "hacks" pour faire d'osu! ce qu'il était. Un nouveau moteur de rendu pour le texte a également été implémenté, rendant possible l'utilisation de polices d'écritures plus nettes et de toutes tailles. Ce qui a rendu possible d'afficher plus d'information dans [l'éditeur de beatmaps](/wiki/Beatmap_Editor), et de rendre le jeu plus beau globalement.
```

2021-06-03 14:34 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Pour contrebalancer les nouveaux mods de février, les mods [Relax](/wiki/Game_modifier/Relax) (RX) et [Half Time](/wiki/Game_modifier/Half_time) (HT) sont arrivés pour rendre la vie des joueurs plus
```suggestion
Pour contrebalancer les nouveaux mods de février, les mods [Relax](/wiki/Game_modifier/Relax) (RX) et [Half Time](/wiki/Game_modifier/Half_time) (HT) sont arrivés pour rendre la vie des joueurs plus simple ce mois-ci. Les utilisateurs sont a présent capables de prendre des captures d'écrans, et d'importer ou exporter des [replays](/wiki/Replay). Les animations peuvent être [storyboardées](/wiki/Storyboards) pour la première fois, et le menu de sélection de skin a été ajouté. Les optimisations de performances ont vu une chute de 82% pour le chargement du menu de sélection des musiques (via un nouveau format pour la base de données de beatmaps locale). D'autres ajustements liés a la performance ont été réalisés, incluant l'introduction du limiteur de FPS, et quelques autres options graphiques. Le projet [Bancho](/wiki/Bancho_(server)) a commencé le 24 mars 2008. L'idée était de créer un serveur pour la famille d'osu!, qui gérerait les communications entre les utilisateurs et enlèverait la dépendance a l'[IRC](/wiki/Internet_Relay_Chat).
```

2021-06-03 14:36 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +L'éditeur, le multijoueur, le storyboarding, les graphiques, et la console de chat ont tous reçu de nombreuses améliorations ce mois-là. L'écran d'options a maintenant un nouveau modèle, et la [confi
```suggestion
L'éditeur, le multijoueur, le storyboarding, les graphiques, et la console de chat ont tous reçu de nombreuses améliorations ce mois-là. L'écran d'options a maintenant un nouveau modèle, et la [configuration des touches](/wiki/Options/Keyboard_Bindings) a été introduite.
```

2021-06-03 14:37 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Les records personnels en ligne ont été ajoutés au menu de sélection de musiques, remplissant une demande de longue date, qui demandait une optimisation assez conséquente de la base de données. Des a
```suggestion
Les records personnels en ligne ont été ajoutés au menu de sélection de musiques, remplissant une demande de longue date, qui demandait une optimisation assez conséquente de la base de données. Des améliorations graphiques ont été ajoutées à l'écran de résultat, et des éléments variés du skin par défaut ont été réalisés dans le but de les rendre plus propres et nets qu'avant. L'affichage du score des sliders ticks (10/30) a été ajouté. Des améliorations ont été vues dans la préparation des matchs multijoueurs, rendant possible le transfert du contrôle de la salle. De nombreuses nouvelles [commandes de chat](/wiki/Chat_Console#commands-list) ont été ajoutées pour les utilisateurs.
```

2021-06-03 14:42 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +*"Think big, and expect big."* — peppy
```suggestion
*"Think big, and expect big." (Voyez grand, et attendez-vous à ce que ce soit le cas.)* — peppy
```

2021-06-03 14:42 UTC, DoryanR commented on wiki/History_of_osu!/2009/fr.md
> +![](img/2009-01_14.jpg "Nouveau record!")
```suggestion
![](img/2009-01_14.jpg "Nouveau record !")
```

2021-06-03 14:42 UTC, DoryanR commented on wiki/History_of_osu!/2011/fr.md
> +Le wiki osu! a été annoncé, permettant aux utilisateurs d'ajouter toutes sortes d'informations sur tout ce qui est lié à osu!.
```suggestion
Le wiki d'osu! a été annoncé, permettant aux utilisateurs d'ajouter toutes sortes d'informations sur tout ce qui est lié à osu!.
```

2021-06-03 14:42 UTC, DoryanR commented on wiki/History_of_osu!/2011/fr.md
> +- [Projet osu!wiki](https://osu.ppy.sh/community/forums/topics/68479)
```suggestion
- [Projet osu! wiki](https://osu.ppy.sh/community/forums/topics/68479)
```

2021-06-17 07:49 UTC, geshii commented on wiki/History_of_osu!/2007/fr.md
> +Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas où la perfection était atteinte. Les mods [No Video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_m
normaux*?

2021-06-18 11:47 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2007/fr.md
> +Un nouvelle note, le SS, a été ajoutée au système de ranking, remplaçant les S dans les cas où la perfection était atteinte. Les mods [No Video](/wiki/Game_modifier/No_Video) et [Hidden](/wiki/Game_m
Je pense que "normal" est bon dans ce cas, car on parle du set "normal" et du set "soft"

2021-06-18 12:11 UTC, Ganondorf-1 requested changes

2021-06-18 12:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2008/fr.md
> +L'éditeur, le multijoueur, le storyboarding, les graphiques, et la console de chat ont tous reçu de nombreuses améliorations ce mois-là. L'écran d'options a maintenant un nouveau modèle, et la [confi
```suggestion
L'éditeur, le multijoueur, le storyboarding, les graphismes, et la console de chat ont tous reçu de nombreuses améliorations ce mois-ci. L'écran d'options a maintenant un nouveau modèle, et la [configuration des touches](/wiki/Options/Keyboard_Bindings) a été introduite.
```

2021-06-18 12:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2008/fr.md
> +Un nouveau statut classé a été ajouté, "![](/img/fire.gif) [Approuvée](/wiki/Beatmap/Category#approuvée)" pour les maps de grande qualités, mais qui excédaient les critères de classement de longueur,
```suggestion
Un nouveau statut classé a été ajouté, "![](/img/fire.gif) [Approuvée](/wiki/Beatmap/Category#approuvée)" pour les maps de grande qualités, mais qui excédaient les critères de classement de longueur, difficulté, ou autres d'une manière ou d'une autre. Les maps dans ce statut ne s'ajoutent pas aux scores du joueur, mais possèdent des classements, et se comportent comme une map ![](img/heart.gif) [Classée](/wiki/Beatmap/Category#classée).
```

2021-06-18 12:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2008/fr.md
> +Une série de nouveau mods a été rendue publique ce mois-ci : [Flashlight](/wiki/Game_modifier/Flashlight), [Spun Out](/wiki/Game_modifier/Spun_Out) et [Auto](/wiki/Game_modifier/Auto). Auto émule un
```suggestion
Une série de nouveau mods a été rendue publique ce mois-ci : [Flashlight](/wiki/Game_modifier/Flashlight), [Spun Out](/wiki/Game_modifier/Spun_Out) et [Auto](/wiki/Game_modifier/Auto). Auto émule un joueur artificiel qui peut compléter (presque) n'importe quelle beatmap avec une [précision](/wiki/Accuracy) parfaite, et est aussi accessible depuis le mode de test de l'éditeur. Les limites de la création des beatmaps ont été poussées plus loin avec l'ajout de plus d'éléments personnalisables (incluant les [images de comboburst](/wiki/Glossary/comboburst), l'échantillon sonore clap, la possibilité d'assigner des sons à des points individuels de sliders et des sections de timing en découlant). Le menu de sélection des musiques a aussi reçu une refonte. 
```

2021-06-18 12:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2008/fr.md
> +Novembre a vu l'introduction d'un tout nouveau mode de jeu, Catch the Beat. Le support d'OpenGL a démarré, permettant donc a osu! de tourner sur la majorité des systèmes. D'autres nouvelles fonctionn
```suggestion
Novembre a vu l'introduction d'un tout nouveau mode de jeu, Catch the Beat. Le support d'OpenGL a démarré, permettant donc à osu! de tourner sur la majorité des systèmes. D'autres nouvelles fonctionnalités incluent le support de la liste d'amis en jeu, de canaux de chat privés, un nouveau tutoriel pour l'[offset wizard](/wiki/Options/Offset_Wizard) et osu!direct (une plateforme en jeu pour télécharger des beatmaps).
```

2021-06-18 12:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2008/fr.md
> +Suite aux plaintes de personnes ayant un grand nombre de beatmaps sur le temps de chargement d'osu!, peppy a passé de nombreux jours à optimiser tout ce qui était possible, résultant en une améliorat
```suggestion
Suite aux plaintes de personnes ayant un grand nombre de beatmaps sur le temps de chargement d'osu!, peppy a passé de nombreux jours à optimiser tout ce qui était possible, résultant en une amélioration presque impossible à mesurer sur une échelle (au moins supérieure à 9000). Les chargements de plus d'une minute ont été réduits à quelques millisecondes.
```

2021-06-18 12:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2008/fr.md
> +Le dernier mois de 2008 a eu beaucoup en stock pour le développement d'osu!. Au deuxième noël d'osu!, la première version de l'éditeur de storyboards a été implémentée, rendant le storyboarding beauc
```suggestion
Le dernier mois de 2008 a eu beaucoup en stock pour le développement d'osu!. Au deuxième Noël d'osu!, la première version de l'éditeur de storyboards a été implémentée, rendant le storyboarding beaucoup plus accessible aux utilisateurs. Un deuxième mode de jeu multijoueur a été ajouté : "Tag Play". C'était un mode coopératif dans lequel les joueurs jouaient chacun leur tour sur une beatmap. Un autre ajout au multijoueur était la "Victoire sur accuracy". MSN et Yahoo ont été intégrés, et les utilisateurs pouvaient entièrement personnaliser leurs touches de jeu et les mots à notifications.
```

2021-06-22 13:01 UTC, geshii commented
@Airwam, tu peux regarder les changements qu'on a proposés ?

2021-06-22 15:58 UTC, geshii approved these changes
Good for me, ready to merge?

2021-06-22 17:34 UTC, DoryanR requested changes
After that it will be good

2021-06-22 17:34 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Le dernier mois de 2008 a eu beaucoup en stock pour le développement d'osu!. Au deuxième Noël d'osu!, la première version de l'éditeur de storyboards a été implémentée, rendant le storyboarding beauc
```suggestion
Le dernier mois de 2008 a eu beaucoup en stock pour le développement d'osu!. Au deuxième noël d'osu!, la première version de l'éditeur de storyboards a été implémentée, rendant le storyboarding beaucoup plus accessible aux utilisateurs. Un deuxième mode de jeu multijoueur a été ajouté : "Tag Play". C'était un mode coopératif dans lequel les joueurs jouaient chacun leur tour sur une beatmap. Un autre ajout au multijoueur était la "Victoire sur accuracy". MSN et Yahoo ont été intégrés, et les utilisateurs pouvaient entièrement personnaliser leurs touches de jeu et les mots à notifications.
```

2021-06-22 18:34 UTC, DoryanR commented
Il reste encore des choses à appliquer, je te laisse regarder sur les divers suggestions proposer depuis le début, ensuite ce sera bon pour moi

2021-06-22 20:46 UTC, Airwam commented on wiki/History_of_osu!/2007/fr.md
> +L'écran de sélection de musiques a vu des améliorations avec le groupement des difficultés et un mouvement de scroll plus intuitif. Le set d'échantillons soft, les raccourcis clavier, et la recherche
```suggestion
L'écran de sélection de musiques a vu des améliorations avec le groupement des difficultés et un mouvement de scroll plus intuitif. Le set d'échantillons soft, les raccourcis clavier, et la recherche en jeu ont tous été ajoutés ce mois-là. Les joueurs pouvaient créer des [skins](/wiki/Skinning) globaux, mais aussi par beatmap pour la première fois, et la prise en charge complète des Tablet-PC a été implémentée.

```

2021-06-23 05:00 UTC, DoryanR approved these changes

2021-06-24 05:31 UTC, geshii approved these changes

2021-06-25 20:32 UTC, DoryanR approved these changes
Can be merge

2021-06-25 21:37 UTC, TicClick approved these changes
2010

on a more serious note, we have #4871, which covers possible expansion

2021-06-25 21:38 UTC, merged