[FR] Update "Beatmapping/Circle size", update tags in "Combo"
ppy/osu-wiki pull request #5544
Opened 2021-05-22 12:19 UTC by DoryanR

Proposal to update the French translation of the wiki page `Circle size`.

Also:

- Update tags in `Combo`

2021-05-24 19:28 UTC, Satsukel requested changes

2021-05-24 19:28 UTC, Satsukel commented on wiki/Beatmapping/Circle_size/fr.md
> +Dans le mode osu!, la taille du cercle modifie la taille des cercles et des sliders frappés, les valeurs les plus élevées créant des objets plus petits. Les spinners ne sont pas affectés par ce param
J'ai gardé le "circle size" pour unifier je sais pas trop si vaut mieux le traduire ici pour le coup
```suggestion
Dans le mode osu!, le circle size modifie la taille des cercles et des sliders, les valeurs les plus élevées créant des objets plus petits. Les spinners ne sont pas affectés par ce paramètre. Le circle size est calculé à l'aide de la formule suivante :
```

2021-05-24 19:28 UTC, Satsukel commented on wiki/Beatmapping/Circle_size/fr.md
> +Dans osu!mania, le circle size fait référence au nombre de touches.
```suggestion
Dans le mode osu!mania, le circle size fait référence au nombre de touches.
```

2021-05-24 19:28 UTC, Satsukel commented on wiki/Beatmapping/Circle_size/fr.md
> +Il existe deux mods qui modifient le paramètre CS lorsqu'ils sont activés :
```suggestion
Il existe deux mods qui modifient le circle size lorsqu'ils sont activés :
```

2021-05-24 19:28 UTC, Satsukel commented on wiki/Beatmapping/Circle_size/fr.md
> +- [Easy](/wiki/Game_modifier/Easy): Réduit de moitié la valeur de CS.
```suggestion
- [Easy](/wiki/Game_modifier/Easy): Réduit de moitié la valeur du CS.
```

2021-05-24 19:28 UTC, Satsukel commented on wiki/Beatmapping/Circle_size/fr.md
> +- [Hard Rock](/wiki/Game_modifier/Hard_Rock): Multiplie la valeur CS par 1,3, avec un maximum de 10.
```suggestion
- [Hard Rock](/wiki/Game_modifier/Hard_Rock): Multiplie la valeur du CS par 1,3, avec un maximum de 10.
```

2021-05-24 19:34 UTC, Satsukel approved these changes

2021-05-25 13:42 UTC, TicClick approved these changes

2021-05-25 13:42 UTC, merged