[FR/EN] Add French articles for "Disambiguation" and fix errors in EN files
ppy/osu-wiki pull request #5552
Opened 2021-05-23 13:12 UTC by DoryanR

Translation of the following wiki pages:

- `Disambiguation/Combo`
- `Disambiguation/Fail`
- `Disambiguation/NC`
- `Disambiguation/NM`
- `Disambiguation/Offset`
- `Disambiguation/Rank`
- `Disambiguation/Version`
- `Disambiguation/osu!`

Update of the translations of the following wiki pages:

- `Disambiguation/Bancho`
- `Disambiguation/EZ`
- `Disambiguation/Easy`
- `Disambiguation/Mod`

Also:

- In `Disambiguation/NM` files : Change difficulty name for osu!catch
- In `Disambiguation/Version` files : Add `(Experimental)` for `Cutting Edge`

2021-05-24 14:27 UTC, Satsukel requested changes

2021-05-24 14:27 UTC, Satsukel commented on wiki/Disambiguation/Offset/fr.md
> +- Le [Online offset](/wiki/Beatmap/Online_offset), un changement de timing appliqué par un membre du [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) aux beatmaps classés avec un offset incorr
```suggestion
- Le [Online offset](/wiki/Beatmap/Online_offset), un changement de timing appliqué par un membre du [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) aux beatmaps classées avec un offset incorrect non hérité afin de l'ajuster.
```

2021-05-24 14:33 UTC, Satsukel submitted a review, later dismissed

2021-05-24 18:57 UTC, DoryanR commented on wiki/Disambiguation/Offset/fr.md
> +- Le [Décalage local ("hors ligne")](/wiki/Glossary#local-song-offset), un paramètre par beatmap qui décale les objets dans le temps pendant le jeu.
```suggestion
- Le [Décalage local ("hors ligne")](/wiki/Glossary/Local_song_offset), un paramètre par beatmap qui décale les objets dans le temps pendant le jeu.
```

2021-05-25 13:48 UTC, TicClick approved these changes

2021-05-25 13:48 UTC, merged

2021-05-25 13:48 UTC, TicClick commented
merged with the assumption that @Satsukel's dismissed review was an approval