Add KCC contest wiki pages
ppy/osu-wiki pull request #5562
Opened 2021-05-24 04:46 UTC by Garalulu

Added Korean Charting Contest 2021 & KCC Index Page. (EN / KR)

2021-05-24 17:30 UTC, TPGPL requested changes
`kr.md` files should be  renamed to `ko.md`

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +# KCC 2021
```suggestion
# Korean Charting Contest 2021
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +![KCC2021 Logo](img/banner.png)
```suggestion
![KCC2021 banner](img/banner.png)
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +The **Korean Charting Contest 2021** (***KCC2021***) is a osu!mania mapping contest for Koreans.  This edition was the first installment of the KCC.
```suggestion
The **Korean Charting Contest 2021** (***KCC2021***) is a osu!mania mapping contest for users from ![][flag_KR] South Korea.  It was the first installment of the Korean Charting Contest.
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +| Event | Timestamp (UTC +9) |
```suggestion
| Event | Timestamp (UTC+09) |
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +| Submitting Phase | 2021-02-08/2021-03-07 |
```suggestion
| Submission phase | 2021-02-08/2021-03-07 |
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +| Registration Phase, Songs Voting | 2021-02-01/2021-02-07 |
```suggestion
| Registration phase, song voting | 2021-02-01/2021-02-07 |
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +| Judging Phase | 2021-03-08/2021-03-21 |
```suggestion
| Judging phase | 2021-03-08/2021-03-21 |
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +| Results Announcement | 2021-03-22 |
```suggestion
| Results announcement | 2021-03-22 |
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- Submission must be in ``.osz`` format.
```suggestion
- Submission must be in `.osz` format.
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +![KCC2021 Vote Results](img/voteresult.jpg)
```suggestion
![KCC2021 voting results](img/voteresult.jpg)
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +## Judging Criteria
```suggestion
## Judging criteria
```
should be a part of `Ruleset`

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +| ![Bronze Crown](/wiki/shared/crown-bronze.png "3rd place") | 10,000 KRW |
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | 40,000 KRW, profile badge |
| ![Silver crown](/wiki/shared/crown-silver.png "2nd place") | 20,000 KRW |
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | 10,000 KRW |
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +![KCC2021 Badge](img/badge.png)
```suggestion
![KCC2021 badge](img/badge.png)
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +| Organizer | ![][flag_KR] [Garalulu](https://osu.ppy.sh/users/757783) |
```suggestion
| Organiser | ![][flag_KR] [Garalulu](https://osu.ppy.sh/users/757783) |
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- [Results Sheet](https://docs.google.com/spreadsheets/d/1O0Ygpning0te62S850M42oPo0lCYd1Ct8VeYnAWRcYE/edit?usp=sharing)
```suggestion
- [Results sheet](https://docs.google.com/spreadsheets/d/1O0Ygpning0te62S850M42oPo0lCYd1Ct8VeYnAWRcYE/edit?usp=sharing)
```

2021-05-24 17:30 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- [All Entries](https://lulu.s-ul.eu/D2M3x9LH)
```suggestion
- [Entries](https://lulu.s-ul.eu/D2M3x9LH)
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- Only Koreans can participate in this contest. If your profile flag is not showing that you're in Korea because of some reasons like foreign residence, you can still participate as long as you're ab
```suggestion
- Only Koreans can participate in this contest. If your profile flag is not showing that you're in ![][flag_KR] South Korea for reasons like foreign residence, you can still participate as long as you're able to verify that you are Korean.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- You should pick a song that you want to map when you register. one song for Instrumental / Vocal each. You can map one of the two songs selected after the vote ends.
```suggestion
- You should pick a song that you want to map when you register (one song for Instrumental / Vocal each). You can map one of those two songs after the voting ends.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- Submission must be loadable and readable by osu! client.
```suggestion
- The osu! client must be able to load and read your submission.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- No video, skin and storyboard are allowed. However, storyboard hitsounds are allowed.
```suggestion
- Videos, skins and storyboards are NOT allowed. However, storyboard hitsounds can be modified.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- Submission must be full comboed (1,000,000 score) by Auto mod.
```suggestion
- The Auto mod must be able to full combo (1,000,000 score) your submission.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- Submission must be finished by the contestant only. No collaboration is allowed.
```suggestion
- Submission must be finished by the contestant alone. No collaboration is allowed.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- One and only one difficulty is allowed. If multiple difficulties are submitted, only the one with the highest star difficulty will be accepted.
```suggestion
- Only one beatmap difficulty is allowed. If multiple difficulties are submitted, then the one with the highest star difficulty will be accepted.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- Only the following difficulty are allowed: Insane or Higher. Please check the Difficulty-specific Rule in the [ranking criteria](/wiki/Ranking_Criteria).
```suggestion
- Only the following difficulties are allowed: Insane or higher. Please check the difficulty-specific rules in the [ranking criteria](/wiki/Ranking_Criteria).
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- If you submit several maps, the last one would be your final entry.
```suggestion
- If you submit several maps, the last one will be your final entry.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- Submitting entries means understanding and agreeing the ruleset above.
```suggestion
- Submitting entries means understanding and agreement to the ruleset above.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/en.md
> +- **Creativity (25 pts):** How well does the submission show originality and uniqueness compared with the other submissions with reasonable respect to the playability?
```suggestion
- **Expertise (25 pts):** How well does the submission demonstrate techniques regarding structure, music representation, flow, hitsounding, etc.
- **Cohesion (25 pts):** How consistent is the submission regarding structure, music representation, flow, hitsounding etc especially between different sections.
- **Creativity (25 pts):** How well does the submission show originality and uniqueness compared with the other submissions with reasonable respect to the playability.
```

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/ko.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3위") | 10,000 KRW |
text in square brackets can be translated

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/ko.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3위") | ![][flag_CA] [arpia97](https://osu.ppy.sh/users/6363008) |
text in square brackets can be translated

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/ko.md
> +![KCC2021 voting results](img/voteresult.jpg)
text in square brackets can be translated

2021-05-26 01:22 UTC, TPGPL commented on wiki/Contests/KCC/1/ko.md
> +![KCC2021 banner](img/banner.png)
text in square brackets can be translated

2021-05-27 12:12 UTC, Walavouchey requested changes
Otherwise alright for the English part 👍

2021-05-27 12:12 UTC, Walavouchey commented on wiki/Contests/KCC/1/en.md
> +For each eligible submitted difficulty, the juding panel will award points based on the following criteria:
```suggestion
For each eligible submitted difficulty, the judging panel will award points based on the following criteria:
```

2021-05-27 12:12 UTC, Walavouchey commented on wiki/Contests/KCC/1/en.md
> +- **Judge's Impression (25 pts):** This is the part of the score left to the Judges’ personal preferences on the submission.
These are formed as questions, but don't have question marks, although I think they're more appropriate as statements.

```suggestion
- **Expertise (25 pts):** How well the submission demonstrates techniques regarding structure, music representation, flow, hitsounding, etc.
- **Cohesion (25 pts):** How consistent the submission is regarding structure, music representation, flow, hitsounding etc especially between different sections.
- **Creativity (25 pts):** How well the submission shows originality and uniqueness compared with the other submissions with reasonable respect to the playability.
- **Judge's Impression (25 pts):** This is the part of the score left to the Judges' personal preferences on the submission.
```

2021-05-27 23:50 UTC, TPGPL approved these changes

2021-05-27 23:56 UTC, merged