Clean up references to Glossary
ppy/osu-wiki pull request #5565
Opened 2021-05-24 15:15 UTC by DoryanR

resolve #4804

Fixed links to sub-sections of the Glossary, to the `Glossary` article, and other links that are invalid.

The work is not finished yet, I'd rather post to see if I'm going in the right direction before continuing further.

2021-05-24 15:32 UTC, TicClick requested changes
looks ok otherwise -- is there anything else that links to Glossary besides the articles you edited?

2021-05-24 15:32 UTC, TicClick commented on wiki/Beatmap/Category/zh.md
> +当一个谱面变为Graveyard后，它仍可以被“复活” (如 重新变回[Pending](#work-in-progress-和-pending) ）。这可以由使用 [谱面提交系统](/wiki/Beatmap_ranking_procedure) 更新谱面达成。
this should be a link to `/wiki/Submission`

2021-05-24 15:32 UTC, TicClick commented on wiki/Beatmap_Editor/Compose/en.md
> +**Compose** is the place where a [mapper](/wiki/Modding/Modder) spent most of the time mapping out his/her design with respect to timeline after setting the BPM and Timing Sections. This is also the
as we don't have an article about the mapper term (and it's unlikely that we need to), this should link to `/wiki/Beatmapping`, same for the translations of "Compose"

2021-05-24 15:32 UTC, TicClick commented on wiki/Beatmap_Editor/es.md
> +- [Design](Design) (Diseño): Aquí es donde el [storyboard](/wiki/Storyboards) es hecho. La mayoría de los [mappers](/wiki/Modding/Modder) solo usan el botón "Background Image/Video" aquí.
again, this should reference `/wiki/Beatmapping`

2021-05-24 15:34 UTC, TicClick commented
this also only resolves a part of #4804 -- I'd rather have several medium-sized pull requests to review (one for each checkbox item)

2021-05-24 15:37 UTC, DoryanR commented
> is there anything else that links to Glossary besides the articles you edited?

I have quite a few more articles to do, about 220 with links pointing to the Glossary.

> this also only resolves a part of #4804 -- I'd rather have several medium-sized pull requests to review (one for each checkbox item)

Ok, no problem

2021-05-24 22:01 UTC, TicClick requested changes

2021-05-25 18:48 UTC, TicClick requested changes
a few last bits and that'll be it

2021-05-25 18:48 UTC, TicClick commented on wiki/Modding/fr.md
> +Tout d'abord, téléchargez une map dans la partie [Pending Beatmap](/wiki/Beatmap) ou [Work In Progress/Help](/wiki/Beatmap/Category#work-in-progress-and-pending) du forum (et non les parties [Ranked]
```suggestion
Tout d'abord, téléchargez une map dans la partie [Pending Beatmap ou Work In Progress/Help](/wiki/Beatmap/Category#work-in-progress-and-pending) du forum (et non les parties [Ranked](/wiki/Beatmap/Category#ranked)/[Approved](/wiki/Beatmap/Category#approved) !). Vous pouvez choisir des maps au hasard ou ouvrir une modding queue dans la sous-partie **Modding Queue** en dessous de [Work In Progress/Help](/wiki/Beatmap/Category#work-in-progress-and-pending) et accepter des demandes de mods. Si vous avez l'intention d'ouvrir une modding queue, n'hésitez pas à jeter un coup d'oeil à certains d'entre eux pour vous donner une idée générale de leur fonctionnement.
```

2021-05-25 18:48 UTC, TicClick commented on wiki/Modding/zh.md
> +首先，从论坛上下载一个谱面，[Pending Beatmaps 里的或者](/wiki/Beatmap) [Work In Progress/Help 的都可以](/wiki/Beatmap/Category)(唯独不要下载 [Ranked/Approved Beatmaps](/wiki/Beatmap) 里的！因为那些是已经审核通过上架了的谱面)。你可以从之前两个页面中随机选一个谱面来看，或
```suggestion
首先，从论坛上下载一个谱面，[Pending Beatmaps 里的或者](/wiki/Beatmap/Category#work-in-progress-and-pending) [Work In Progress/Help 的都可以](/wiki/Beatmap/Category#work-in-progress-and-pending)(唯独不要下载 [Ranked/Approved Beatmaps](/wiki/Beatmap/Category#ranked) 里的！因为那些是已经审核通过上架了的谱面)。你可以从之前两个页面中随机选一个谱面来看，或者在 [Work In Progress/Help 里的](/wiki/Beatmap/Category#work-in-progress-and-pending) **Modding Queue** 页面开一个自己的 Modding queue（修图队列）然后接受他人的修图请求。如果你想开一个修图队列，读一读那个页面里的其他队列你就知道该怎么做了。
```

2021-05-25 18:50 UTC, TicClick approved these changes

2021-05-25 18:52 UTC, merged