[ID] Add Double Tapping
ppy/osu-wiki pull request #5572
Opened 2021-05-25 13:33 UTC by Fhoxydeo

2021-05-25 13:40 UTC, TicClick commented on wiki/Play_style/Double_tapping/id.md
> +stub: true
the original isn't a stub anymore

2021-05-27 20:46 UTC, ViaSnake requested changes

2021-05-27 20:46 UTC, ViaSnake commented on wiki/Play_style/Double_tapping/id.md
> +
```suggestion

```

2021-05-30 03:56 UTC, mousesalt commented on wiki/Play_style/Double_tapping/id.md
> +**Double tapping** adalah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) dimana pemain mengetuk circles, menggeser slider, dan memutar spinner dengan menekan kedua tombol pada keyboard mereka (`Z` d
```suggestion
**Double tapping** adalah sebuah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) di mana pemain mengetuk circle, menggeser slider, dan memutar spinner dengan menekan kedua tombol pada keyboard mereka (secara umum `Z` dan `X`). Gaya ini paling sering digunakan sebagai pengganti sementara gaya tapping [stack](/wiki/Mapping_Techniques/Stack) dan [stream](/wiki/Beatmap/Pattern/Stream) yang cepat dan terlalu sulit untuk sebagian pemain. Gaya ini dikenal paling tidak akurat.
```

2021-05-30 03:56 UTC, mousesalt commented on wiki/Play_style/Double_tapping/id.md
> +Double tapping biasanya menggantikan gaya tapping utama pemain karena mudah digunakan dan meningkatkan "kecepatan" (meskipun pemain sebenarnya tidak mengetuk lebih cepat). Cara untuk mendapatkan kece
```suggestion
Double tapping biasanya menggantikan gaya tapping utama pemain karena mudah digunakan dan meningkatkan "kecepatan" (meskipun pemain sebenarnya tidak mengetuk lebih cepat). Peningkatan kecepatan ini dicapai dengan mengambil keuntungan tumpang tindih dari hit window yang paling sering terjadi pada stack dan stream. Jadi, satu input tombol terhitung sebagai satu hit circle dalam stack, circle berikutnya juga akan terhitung sebagai hit karena hit window mereka sangat berdekatan sehingga saling tumpang tindih. Tetapi sebagai akibatnya, hampir tidak mungkin untuk mengontrol waktu tapping ini yang dapat mengurangi [akurasi](/wiki/Accuracy) pemain.
```

2021-05-30 03:56 UTC, mousesalt commented on wiki/Play_style/Double_tapping/id.md
> +Double tapping biasanya menggantikan gaya tapping utama pemain karena mudah digunakan dan meningkatkan "kecepatan" (meskipun pemain sebenarnya tidak mengetuk lebih cepat). Cara untuk mendapatkan kece
missing several phases on EN
`This increase in speed is achieved by taking advantage of the overlapping hit windows that occur most frequently in stacks and streams.`

2021-05-30 03:56 UTC, mousesalt commented on wiki/Play_style/Double_tapping/id.md
> +Argumen yang mendukung double tapping biasanya merujuk bahwa cara cepat untuk memungkinkan pemain mempelajari pergerakan beatmap yang muncul setelah pola yang bermasalah, sementara pemain yang menent
```suggestion
Argumen yang mendukung double tapping biasanya merujuk bahwa cara cepat untuk memungkinkan pemain mempelajari pergerakan beatmap yang muncul setelah pattern yang bermasalah, sementara pemain yang menentang double tapping berpendapat bahwa ini adalah cara mudah untuk melewati bagian sulit yang harus dipelajari.
```

2021-06-07 12:02 UTC, ZeroPyrozen requested changes

2021-06-07 12:02 UTC, ZeroPyrozen commented on wiki/Play_style/Double_tapping/id.md
> +---
add `- gaya bermain` stub if possible

2021-06-07 12:02 UTC, ZeroPyrozen commented on wiki/Play_style/Double_tapping/id.md
> +Double tapping biasanya menggantikan gaya tapping utama pemain karena mudah digunakan dan meningkatkan "kecepatan" (meskipun pemain sebenarnya tidak mengetuk lebih cepat). Peningkatan kecepatan ini d
```suggestion
Double tapping biasanya menggantikan gaya tapping utama pemain karena mudah digunakan dan meningkatkan "kecepatan" (meskipun pemain sebenarnya tidak mengetuk lebih cepat). Peningkatan kecepatan ini dicapai dengan mengambil keuntungan tumpang-tindih dari hit window yang paling sering terjadi pada stack dan stream. Jadi, satu input tombol terhitung sebagai satu hit circle dalam stack, circle berikutnya juga akan terhitung sebagai hit karena hit window mereka sangat berdekatan sehingga saling tumpang tindih. Tetapi sebagai akibatnya, hampir tidak mungkin untuk mengontrol waktu tapping ini yang dapat mengurangi [akurasi](/wiki/Accuracy) pemain.
```

2021-06-07 14:06 UTC, wowcake approved these changes
good to be merged now

2021-06-07 14:12 UTC, TicClick approved these changes

2021-06-07 14:12 UTC, merged