Add glossaries needed for the catch RC
ppy/osu-wiki pull request #5587
Opened 2021-05-26 14:56 UTC by Darius-Wattimena

2nd try as my old PR didn't rebase correctly

A PR that will add links to the catch RC will follow

2021-05-26 18:13 UTC, TicClick requested changes

2021-05-26 18:13 UTC, TicClick commented on wiki/Glossary/Antiflow/en.md
> +# Antiflow
I think this, along with `Snapping`, also covers osu! as a mode, so I would place that under `/wiki/Disambiguation/Antiflow` (I wish we also had `/wiki/Flow`!)

2021-05-31 23:26 UTC, TPGPL requested changes

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Edge_dash/en.md
> +An *edge dash* (also known as a *pixel dash*) is the term used in [osu!catch](/wiki/Game_mode/osu!catch) for a very large spacing between two [active objects](/wiki/Glossary/Active_object) where the
```suggestion
The **edge dash** (also known as a *pixel dash*) is a term used in [osu!catch](/wiki/Game_mode/osu!catch) for a very large spacing between two [active objects](/wiki/Glossary/Active_object) where the required [trigger distance](/wiki/Glossary/Trigger_distance) is not reached, and as such, a [hyperfruit](/wiki/Hit_object/Hyperfruit) is not generated to create a [hyperdash](/wiki/Glossary/Hyperdash). The first object must be caught with the edge of the plate in order to catch the second object at all.
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Edge_dash/en.md
> +# Edge Dash
```suggestion
# Edge dash
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Hyperdash/en.md
> +A *hyperdash* is the term used in [osu!catch](/wiki/Game_mode/osu!catch) for the movement which is done when a [hyperfruit](/wiki/Hit_object/Hyperfruit) is generated. When modding a beatmap people te
```suggestion
The **hyperdash** is a term used in [osu!catch](/wiki/Game_mode/osu!catch) for the movement which is done when a [hyperfruit](/wiki/Hit_object/Hyperfruit) is generated. While modding beatmaps, people tend to link the hyperfruit and the target [active object](/wiki/Glossary/Active_object) to define a hyperdash movement (e.g. `00:01:000 (1,2) -`  where 1 is the hyperfruit, and 2 the target active object).
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Snapping/en.md
> +The term *basic-snapped* is used for any [dash](/wiki/Glossary/Dash) or [hyperdash](/wiki/Glossary/Hyperdash) whose time between [active objects](/wiki/Glossary/Active_object) is at least twice the t
```suggestion
The term **basic-snapped** is used for any [dash](/wiki/Glossary/Dash) or [hyperdash](/wiki/Glossary/Hyperdash) whose time between [active objects](/wiki/Glossary/Active_object) is at least two times longer than the time required to allow dashes or hyperdashes, respectively. For example, a hyperdash between objects separated by 250 ms in a Platter classifies as a basic-snapped hyperdash.
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Snapping/en.md
> +The term *higher-snapped* is used for any [dash](/wiki/Glossary/Dash) or [hyperdash](/wiki/Glossary/Hyperdash) that doesn't meet the requirement to be a basic-snapped one (i.e. the time between the o
```suggestion
The term **higher-snapped** is used for any [dash](/wiki/Glossary/Dash) or [hyperdash](/wiki/Glossary/Hyperdash) that doesn't meet the requirement to be a basic-snapped one (i.e. the time between the objects is shorter than the threshold to be classified as basic).
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Trigger_distance/en.md
> +# Trigger Distance
```suggestion
# Trigger distance
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Trigger_distance/en.md
> +*Trigger distance* is the term used in [osu!catch](/wiki/Game_mode/osu!catch) for the minimal spacing needed to generate a [hyperfruit](/wiki/Hit_object/Hyperfruit) on a [fruit](/wiki/Hit_object/Frui
```suggestion
**Trigger distance** is a term used in [osu!catch](/wiki/Game_mode/osu!catch) for the minimal spacing needed to generate a [hyperfruit](/wiki/Hit_object/Hyperfruit) on a [fruit](/wiki/Hit_object/Fruit) or [drop](/wiki/Hit_object/Juice_stream#drop).
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Glossary/Walk/en.md
> +A *walk* is the term used in [osu!catch](/wiki/Game_mode/osu!catch) for the movement done between two objects when the player can catch both objects without pressing the dash key.
```suggestion
The **walk** is a term used in [osu!catch](/wiki/Game_mode/osu!catch) for the movement done between two objects when a player can catch both objects without pressing the dash key.
```

2021-05-31 23:26 UTC, TPGPL commented on wiki/Hit_object/Hyperfruit/en.md
> +A *hyperfruit* is an effect that can be generated on a [fruit](/wiki/Hit_object/Fruit) or [drop](/wiki/Hit_object/Juice_stream#drop). This effect will be generated when the next fruit or drop can't b
```suggestion
The **hyperfruit** is an effect that can be generated on a [fruit](/wiki/Hit_object/Fruit) or [drop](/wiki/Hit_object/Juice_stream#drop) when the next fruit or drop can't be caught with normal dashing. The movement that is created after catching the hyperfruit is called a [hyperdash](/wiki/Glossary/Hyperdash). This effect will also generate when the last [banana](/wiki/Hit_object/Banana) of a [spinner](/wiki/Hit_object/Spinner) can't be caught with a dash.
```

2021-07-05 17:42 UTC, TicClick commented
my note about `aniflow` and `snapping` not being osu!catch-specific still stands -- please move it to a better home, which, in my opinion, is `/wiki/Disambiguation/`

2021-07-06 12:14 UTC, Darius-Wattimena commented
The snapping thing is something used only in osu!catch as it is a term used to identify strong and weak snapping movements, making it unrelated to object snapping (e.g. 1/2 1/4). Anti-flow on the other hand does make sense to move to this folder. 

Anyway will make the needed changes in a couple of days once I wrapped up my thesis.

2021-07-19 20:14 UTC, TPGPL approved these changes

2021-07-19 20:26 UTC, merged