[FR] Add `Banana`, `Fruit`, `Hyperfruit`, update `Juice stream`
ppy/osu-wiki pull request #5591
Opened 2021-05-26 18:12 UTC by DoryanR

Translation of the following wiki pages:

- `Hit_object/Banana`
- `Hit_object/Fruit`
- `Hit_object/Hyperfruit`

Proposal to update the French translation of the wiki page `Juice stream`.

2021-05-26 19:51 UTC, Ganondorfosu requested changes

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Banana/fr.md
> +Les **bananes** sont des [objet](/wiki/Hit_object) bonus présents dans les [beatmaps](/wiki/Beatmap) du mode [osu!catch](/wiki/Game_mode/osu!catch). Les bananes sont générées lorsqu'un [spinner](/wik
```suggestion
Les **bananes** sont des [objets](/wiki/Hit_object) bonus présents dans les [beatmaps](/wiki/Beatmap) du mode [osu!catch](/wiki/Game_mode/osu!catch). Les bananes sont générées lorsqu'un [spinner](/wiki/Hit_object/Spinner) est placé dans l'éditeur. Contrairement à un spinner, les bananes n'ont pas besoin d'être attrapées puisque ce sont des objets optionnels.
```

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Fruit/fr.md
> +Les **fruits** sont de gros [objets](/wiki/Hit_object) colorés présents dans les [beatmaps](/wiki/Beatmap) du mode [osu!catch](/wiki/Game_mode/osu!catch). Un [hyperfruit](/wiki/Hit_object/Hyperfruit)
```suggestion
Les **fruits** sont de gros [objets](/wiki/Hit_object) colorés présents dans les [beatmaps](/wiki/Beatmap) du mode [osu!catch](/wiki/Game_mode/osu!catch). Un [hyperfruit](/wiki/Hit_object/Hyperfruit) sera généré sur un fruit une fois que le fruit suivant ou le [drop](/wiki/Hit_object/Juice_stream#drop) est impossible à attraper avec un dash normal.
```

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Fruit/fr.md
> +Si le joueur réussit à attraper un fruit, il gagne un [score](/wiki/Score), augmente le [combo]( /wiki/Glossary/Combo_(score_multiplier)) de 1, donne un coup de pouce à la [barre de santé](/wiki/Glos
```suggestion
Si le joueur réussit à attraper un fruit, il gagne du [score](/wiki/Score), augmente le [combo]( /wiki/Glossary/Combo_(score_multiplier)) de 1, donne un coup de pouce à la [barre de santé](/wiki/Glossary/Health_bar), et est traité comme un 300 dans l'écran des résultats. Si le joueur ne réussit pas à attraper un fruit, cela entraînera un [combobreak](/wiki/Glossary/Combobreak) et une perte de [santé](/wiki/Beatmapping/Health).
```

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Hyperfruit/fr.md
> +Un **hyperfruit** est un effet qui peut être généré sur un [fruit](/wiki/Hit_object/Fruit) ou un [drop](/wiki/Hit_object/Juice_stream#drop). Cet effet sera généré lorsque le prochain fruit ou le proc
```suggestion
Un **hyperfruit** est un effet qui peut être généré sur un [fruit](/wiki/Hit_object/Fruit) ou un [drop](/wiki/Hit_object/Juice_stream#drop). Cet effet sera généré lorsque le prochain fruit ou le prochain drop ne peut pas être attrapé avec un dash normal. Le mouvement créé après avoir attrapé l'hyperfruit est appelé un hyperdash. Cet effet est également généré lorsque la dernière [banane](/wiki/Hit_object/Banana) d'un [spinner](/wiki/Hit_object/Spinner) ne peut pas être attrapée avec un dash.
```

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Hyperfruit/fr.md
> +Pendant le jeu, cet effet se caractérise par un contour coloré sur l'hyperfruit.
```suggestion
Durant la partie, cet effet se caractérise par un contour coloré sur l'hyperfruit.
```

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Juice_stream/fr.md
> +Les **drop** sont des [objets](/wiki/Hit_object) de taille moyenne colorés présents dans les [beatmaps](/wiki/Beatmap) du mode [osu!catch](/wiki/Game_mode/osu!catch) . Les drop sont équivalentes aux
```suggestion
Les **drop** sont des [objets](/wiki/Hit_object) de taille moyenne colorés présents dans les [beatmaps](/wiki/Beatmap) du mode [osu!catch](/wiki/Game_mode/osu!catch) . Les drop sont équivalents aux sliders ticks dans le mode [osu!](/wiki/Game_Modes/osu!). Un [hyperfruit](/wiki/Hit_object/Hyperfruit) sera généré sur un drop une fois que le [fruit](/wiki/Hit_object/Fruit) ou le drop suivant est impossible à attraper par un dash normal.
```

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Juice_stream/fr.md
> +Si le joueur réussit à attraper un drop, il obtiendra un [score](/wiki/Score) de 100, augmentera le [combo](/wiki/Glossary/Combo_(score_multiplier)) de 1, donnera un petit coup de pouce à la [barre d
```suggestion
Si le joueur réussit à attraper un drop, il obtiendra du [score](/wiki/Score) de 100, augmentera le [combo](/wiki/Glossary/Combo_(score_multiplier)) de 1, donnera un petit coup de pouce à la [barre de santé](/wiki/Glossary/Health_bar), et sera traité comme un 100 dans l'écran des résultats. Si le joueur ne réussit pas à attraper un drop, cela entraînera un [combobreak](/wiki/Glossary/Combobreak) et une perte de [santé](/wiki/Beatmapping/Health).
```

2021-05-26 19:51 UTC, Ganondorfosu commented on wiki/Hit_object/Juice_stream/fr.md
> +Si vous réussissez à attraper un droplet, vous obtiendrez un [score](/wiki/Score) de 10, une petite augmentation de la [barre de santé](/wiki/Glossary/Health_bar) et un score de 50 dans l'écran des r
```suggestion
Si vous réussissez à attraper un droplet, vous obtiendrez du [score](/wiki/Score) de 10, une petite augmentation de la [barre de santé](/wiki/Glossary/Health_bar) et un score de 50 dans l'écran des résultats. Si le joueur ne parvient pas à attraper un droplet, il perd de la [santé](/wiki/Beatmapping/Santé) et conserve son [combo](/wiki/Glossary/Combo_(score_multiplier)).
```

2021-06-05 06:28 UTC, Ganondorf-1 requested changes

2021-06-05 06:28 UTC, Ganondorf-1 commented on wiki/Hit_object/Juice_stream/fr.md
> +Si le joueur réussit à attraper un drop, il obtiendra du [score](/wiki/Score) de 100, augmentera le [combo](/wiki/Glossary/Combo_(score_multiplier)) de 1, donnera un petit coup de pouce à la [barre d
```suggestion
Si le joueur réussit à attraper un drop, il obtiendra 100 points de [score](/wiki/Score), augmentera le [combo](/wiki/Glossary/Combo_(score_multiplier)) de 1, donnera un petit coup de pouce à la [barre de santé](/wiki/Glossary/Health_bar), et sera traité comme un 100 dans l'écran des résultats. Si le joueur ne réussit pas à attraper un drop, cela entraînera un [combobreak](/wiki/Glossary/Combobreak) et une perte de [santé](/wiki/Beatmapping/Health).
```

2021-06-05 06:28 UTC, Ganondorf-1 commented on wiki/Hit_object/Juice_stream/fr.md
> +Si vous réussissez à attraper un droplet, vous obtiendrez du [score](/wiki/Score) de 10, une petite augmentation de la [barre de santé](/wiki/Glossary/Health_bar) et un score de 50 dans l'écran des r
```suggestion
Si vous réussissez à attraper un droplet, vous obtiendrez 10 points de score [score](/wiki/Score), une petite augmentation de la [barre de santé](/wiki/Glossary/Health_bar) et un score de 50 dans l'écran des résultats. Si le joueur ne parvient pas à attraper un droplet, il perd de la [santé](/wiki/Beatmapping/Santé) et conserve son [combo](/wiki/Glossary/Combo_(score_multiplier)).
```

2021-06-09 14:40 UTC, DoryanR reviewed
Can be merge 👍

2021-06-13 21:56 UTC, TicClick approved these changes

2021-06-13 21:56 UTC, merged