[FR] Add "Featured Artists", "FA Showcase Beatmaps", and fix errors in others files
ppy/osu-wiki pull request #5606
Opened 2021-05-27 18:39 UTC by DoryanR

Proposal for the French translation of the wiki page `Featured Artists Showcase Beatmaps`.

Proposal to update the French translation of the wiki page `Featured Artists`.

Also:

- In `Featured_Artists/Featured_Artist_Showcase_Beatmaps`, for `en.md` and `id.md`, changed wrong dates and changed a link that did not redirect to the right place.

2021-06-02 07:24 UTC, AncuL001 commented
i don't know why HyuN's and Se-U-Ra's dates need to be changed into such. it should be visible from the date of the news link right?

2021-06-02 07:30 UTC, Nivalyx commented
yeah i agree unless it's way off dates shouldn't matter that much especially because on most cases the osu! website displays dates based on what time zone the user is currently in

![image](https://user-images.githubusercontent.com/36564236/120441508-d3cbb280-c3ae-11eb-978c-81175136708e.png)

2021-06-02 07:59 UTC, DoryanR commented
Normally I paid attention to this detail, I changed the language on the site to avoid errors. But normally the time difference between French and English is 1h30.

2021-06-02 08:04 UTC, Nivalyx commented
o i think you get it wrong; the dates that you're seeing are based on *the time zone you're currently in*, not what language/locale you're currently browsing the website in.

fwiw this article was authored by me (https://github.com/ppy/osu-wiki/pull/5245) who lives in gmt +7 so yeah certain differences caused by time zone lags are just imminent lol

2021-06-02 15:03 UTC, DoryanR commented
I put the dates back the way they were.

2021-06-05 06:41 UTC, Ganondorf-1 requested changes

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Cet article répertorie tous les beatmaps vitrines qui ont été créés par les membres de la Mappers' Guild au fil du temps.
```suggestion
Cet article répertorie toutes les beatmaps vitrines qui ont été créées par les membres de la Mappers' Guild au fil du temps.
```

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Dès sa création, la Mappers' Guild s'est fixé comme objectif principal de "créer des packs de beatmaps promotionnels pour les artistes associés à venir". En réalité, les six beatmaps réalisées pour l
```suggestion
Dès sa création, la Mappers' Guild s'est fixé comme objectif principal de "créer des packs de beatmaps promotionnels pour les artistes associés à venir". En réalité, les six beatmaps réalisées pour l'[annonce de l'artiste associé MOtOLOiD](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid) étaient également les toutes premières créations de la Guilde.
```

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Comme la Guilde elle-même fonctionnait à ses débuts sur la base d'une inscription fermée, l'accès aux contenus des artistes associéss à venir était souvent limité à une poignée de mappeurs qui étaien
```suggestion
Comme la Guilde elle-même fonctionnait à ses débuts sur la base d'une inscription fermée, l'accès aux contenus des artistes associés à venir était souvent limité à une poignée de mappeurs qui étaient principalement du mode de jeu [osu!](/wiki/Game_mode/osu!); cependant, le [passage de la Guilde à un système d'inscription ouvert et automatisé au début de 2019](/wiki/Mapping_and_Modding_Timeline#march.5 ) a progressivement permis à de plus en plus de créateurs de participer à la création de beatmaps vitrines pour les futurs artistes associés au fil du temps, quel que soit leur mode de jeu.
```

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/fr.md
> +Les ajouts récents à la bibliothèque des artistes associés sont sélectionnés indirectement par la communauté d'osu!. Si des mappers créent et classent des maps pour un artiste, l'[équipe d'osu!](/wik
```suggestion
Les ajouts récents à la bibliothèque des artistes associés sont sélectionnés indirectement par la communauté d'osu!. Si des mappeurs créent et classent des maps pour un artiste, l'[équipe d'osu!](/wiki/People/The_Team) contacte l'artiste pour discuter du programme d'artistes associés. Cependant, certains artistes sont parfois invités à devenir des artistes associés en fonction d'autres facteurs, tels que l'intérêt qu'ils devraient présenter pour le public du beatmapping d'osu!
```

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/fr.md
> +La plupart des chansons figurant dans le programme des artistes associés font l'objet d'une licence non exclusive pour osu!. Dans de rares cas, un artiste créera des morceaux exclusivement pour osu!,
```suggestion
La plupart des chansons figurant dans le programme des artistes associés font l'objet d'une licence non exclusive pour osu!. Dans de rares cas, un artiste créera des morceaux exclusivement pour osu!, qui seront étiquetés *osu! exclusive* sur leur liste d'artistes associés.
```

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/fr.md
> +Les nouveaux artistes associés sont annoncés chaque semaine sur le [fil d'actualités](https://osu.ppy.sh/home/news) d'osu!. La plupart des annonces comprennent une liste des chansons sous licence de
```suggestion
Les nouveaux artistes associés sont annoncés chaque semaine sur le [fil d'actualités](https://osu.ppy.sh/home/news) d'osu!. La plupart des annonces comprennent une liste des chansons sous licence de l'artiste et un lien vers sa page d'artiste associé, mais certaines annonces sont associées à des concours de mapping ou à des beatmaps créés par la [Mappers' Guild](/wiki/Mappers_Guild).
```

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/fr.md
> +Les mappers sont encouragés à créer des maps pour les pistes des artistes associés. Ces morceaux sont fournis avec des données de [timing](/wiki/Beatmap_Editor/Timing) et sont déjà autorisés à être u
```suggestion
Les mappeurs sont encouragés à créer des maps pour les pistes des artistes associés. Ces morceaux sont fournis avec des données de [timing](/wiki/Beatmap_Editor/Timing) et sont déjà autorisés à être utilisés sur osu!, ce qui permet aux utilisateurs de se lancer immédiatement dans la création de beatmap sans crainte. La version en cours de développement d'osu!, appelée [osu!lazer](https://github.com/ppy/osu/releases), mettra ces maps en évidence dans le jeu.
```

2021-06-05 06:41 UTC, Ganondorf-1 commented on wiki/Featured_Artists/fr.md
> +Tous les concours de mapping publiés sur la [liste des concours communautaires](https://osu.ppy.sh/community/contests), tels que le [Monthly Beatmapping Contest](/wiki/Contests/Monthly_Beatmapping_Co
```suggestion
Tous les concours de mapping publiés sur la [liste des concours communautaires](https://osu.ppy.sh/community/contests), tels que le [Monthly Beatmapping Contest](/wiki/Contests/Monthly_Beatmapping_Contest) et le [Mapping Olympiad](/wiki/Contests#osu!-mapping-olympiad), exigent des participants qu'ils mappent les chansons des artistes associés. Certains concours organisés par la communauté utilisent également ces chansons.
```

2021-06-08 21:51 UTC, Ganondorf-1 approved these changes

2021-06-09 14:40 UTC, DoryanR reviewed
Can be merge 👍

2021-06-13 21:55 UTC, TicClick approved these changes

2021-06-13 21:55 UTC, merged