[FR] Update "Game modifier" and "Summary"
ppy/osu-wiki pull request #5607
Opened 2021-05-27 19:34 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Game_modifier/Summary`
- `Game_modifier`

Also:

- In `Game_modifier` (`en.md`, `es.md`, `id.md`, `ko.md`, `tr.md`) : add `(Experimental)` after Cutting Edge version

2021-06-13 09:51 UTC, Ganondorf-1 requested changes

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/Summary/fr.md
> +| ![Hard Rock](/wiki/shared/mods/HR.png) | Hard Rock (HR) | • ![][osu!]: 1.12x ![][osu!taiko]: 1.06x • ![][osu!catch]: 1.12x • ![][osu!mania]: 1.00x | • ![][osu!] ![][osu!taiko] ![][osu!catch] ![][os
```suggestion
| ![Hard Rock](/wiki/shared/mods/HR.png) | Hard Rock (HR) | • ![][osu!]: 1.12x ![][osu!taiko]: 1.06x • ![][osu!catch]: 1.12x • ![][osu!mania]: 1.00x | • ![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania]: `Tout devient un peu plus compliqué.` |
```

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/Summary/fr.md
> +| ![Relax](/wiki/shared/mods/RL.png) | Relax (RL) | • ![][osu!] ![][osu!taiko] ![][osu!catch]: 0.00x | • ![][osu!]: `YVous n'avez pas besoin de cliquer. Vos doigts méritent une pause après toute cett
```suggestion
| ![Relax](/wiki/shared/mods/RL.png) | Relax (RL) | • ![][osu!] ![][osu!taiko] ![][osu!catch]: 0.00x | • ![][osu!]: `YVous n'avez pas besoin de cliquer. Vos doigts méritent une pause après toute cette agitation. ** LE SCORE RÉALISÉ NE SERA PAS COMPTABILISÉ **` • ![][osu!taiko]: `Détendez-vous ! Vous ne serez plus embêté par les spinners surprise, les drumrolls difficiles ou les katus inattendus. ** LE SCORE RÉALISÉ NE SERA PAS COMPTABILISÉ **` • ![][osu!catch]: `Utilisez la souris pour contrôler le personnage. ** LE SCORE RÉALISÉ NE SERA PAS COMPTABILISÉ **` |
```

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/Summary/fr.md
> +| ![Random](/wiki/shared/mods/RD.png) | Random (RD) | • ![][osu!mania]: 0.00x | • ![][osu!mania]: `Mettez un peut d'aléatoire pour pimenter votre partie.` |
```suggestion
| ![Random](/wiki/shared/mods/RD.png) | Random (RD) | • ![][osu!mania]: 0.00x | • ![][osu!mania]: `Mettez un peu d'aléatoire pour pimenter votre partie.` |
```

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/Summary/fr.md
> +*Remarque : Ce tableau n'affecte que les beatmaps convertis de osu! à osu!mania pendant le jeu, et non les beatmaps spécifiques à osu!mania. En tant que tel, le mod Co-op ne donne aucune pénalité sur
```suggestion
*Remarque : Ce tableau n'affecte que les beatmaps converties de osu! à osu!mania pendant le jeu, et non les beatmaps spécifiques à osu!mania. En tant que tel, le mod Co-op ne donne aucune pénalité sur les beatmaps spécifiques à osu!mania.*
```

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/fr.md
> +### Difficulté réduit
```suggestion
### Difficulté réduite
```

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/fr.md
> +Chacun des mods ci-dessous aura l'icône de son mode de jeu compatible (![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania]) à côté d'elle.
```suggestion
Chacun des mods ci-dessous aura l'icône de son mode de jeu compatible (![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania]) affiché sur le côté.
```

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/fr.md
> +### DDifficulté augmentée
```suggestion
### Difficulté augmentée
```

2021-06-13 09:51 UTC, Ganondorf-1 commented on wiki/Game_modifier/fr.md
> +*Note : Ces mods ont été utilisés et disponibles il y a quelque temps, mais sont maintenant indisponibles.*
```suggestion
*Note : Ces mods étaient utilisés et disponibles il y a quelque temps, mais sont maintenant indisponibles.*
```

2021-06-22 12:57 UTC, geshii approved these changes

2021-06-25 20:29 UTC, DoryanR commented
Can be merge

2021-06-25 20:58 UTC, TicClick approved these changes

2021-06-25 20:58 UTC, merged