[FR] Update "Hit object", add "Slider"
ppy/osu-wiki pull request #5611
Opened 2021-05-28 17:56 UTC by DoryanR

Proposal for the French translation of the wiki page `Slider`.

Proposal to update the French translation of the wiki page `Hit object`.

2021-06-05 06:52 UTC, Ganondorf-1 requested changes

2021-06-05 06:52 UTC, Ganondorf-1 commented on wiki/Hit_object/Slider/fr.md
> +Un *slider* est un [objet](/wiki/Hit_Objects) dans le mode de jeu [osu!](/wiki/Game_mode/osu!), qui consiste en un sliderhead, un sliderbody et un slidertail. Une fois que le cercle d'approche attein
```suggestion
Un *slider* est un [objet](/wiki/Hit_Objects) dans le mode de jeu [osu!](/wiki/Game_mode/osu!), qui consiste en un sliderhead, un sliderbody et un slidertail. Une fois que le cercle d'approche atteint le sliderhead, comme avec les [cercles](/wiki/Hit_object/Hit_circle), le joueur doit cliquer/taper sur le début du slider, puis, en maintenant le bouton enfoncé, suivre une boule mobile (appelée slider ball) le long de la piste jusqu'à ce que la slidertail soit atteinte. S'il y a une flèche inversée, le joueur doit suivre la slider ball sur le même chemin. Les sliders avec des flèches inversées sont appelés [reverse sliders](/wiki/Hit_object/Reverse_slider). La vitesse d'un slider est définie par la [slider velocity](/wiki/Hit_object/Slider_velocity) et le multiplicateur de slider velocity de la section de timing en cours.
```

2021-06-05 06:52 UTC, Ganondorf-1 commented on wiki/Hit_object/Slider/fr.md
> +Les slider ticks sont de petits cercles qui apparaissent à intervalles réguliers le long du sliderbody. Le joueur ne parvient pas à dégager complètement un slider si le curseur se trouve en dehors de
```suggestion
Les slider ticks sont de petits cercles qui apparaissent à intervalles réguliers le long du sliderbody. Le joueur ne parvient pas à dégager complètement un slider si le curseur se trouve en dehors de la portée de la slider ball (définie par le cercle autour de la boule) ou si le bouton de la souris n'est pas enfoncé alors que le slider ball passe au-dessus d'un slider tick. Le fait d'être en dehors de la portée de la slider ball ou de ne pas appuyer sur le bouton à tout autre moment n'entraînera aucune pénalité (bien que cela ne soit pas conseillé car cela pourrait facilement entraîner un sliderbreak). Le fait de passer au-dessus d'une slidertail ou d'un slider tick donne une petite augmentation de santé, généralement juste assez pour maintenir la barre de santé où elle est.
```

2021-06-05 06:52 UTC, Ganondorf-1 commented on wiki/Hit_object/Slider/fr.md
> +Vous êtes libre de déplacer/ajouter/supprimer les points de contrôle des sliders une fois que le slider est terminé. Vous pouvez supprimer les points de contrôle en faisant un clic droit après que le
```suggestion
Vous êtes libre de déplacer/ajouter/supprimer les points de contrôle des sliders une fois que le slider est terminé. Vous pouvez supprimer les points de contrôle en faisant un clic droit après que le slider ait été sélectionné, ou ajouter un point de contrôle en maintenant la touche `Ctrl` et en cliquant n'importe où à l'intérieur des sliders (double-cliquez ou ctrl + clic sur un slider point pour faire un point de contrôle rouge). Les sliders peuvent également être inversés en cliquant et en faisant glisser la slidertail dans la timeline.
```

2021-06-05 06:52 UTC, Ganondorf-1 commented on wiki/Hit_object/Slider/fr.md
> +La façon la plus efficace d'utiliser [Hitsounding](/wiki/Beatmapping/Hitsound)des sliders est de sélectionner chaque partie d'un slider en double-cliquant dessus dans la [timeline](/wiki/Beatmap_Edit
```suggestion
La façon la plus efficace d'utiliser le [Hitsounding](/wiki/Beatmapping/Hitsound) des sliders est de sélectionner chaque partie d'un slider en double-cliquant dessus dans la [timeline](/wiki/Beatmap_Editor/Timelines). Cela mettra l'élément en surbrillance en rouge et limitera les hitsounds à la partie sélectionnée. Si cette sélection n'est pas faite, les hitsounds s'appliqueront à l'ensemble du slider et seront déroutants pour les sliders qui couvrent plusieurs sons différents.
```

2021-06-05 06:52 UTC, Ganondorf-1 commented on wiki/Hit_object/fr.md
> +Les *objets* sont des éléments avec lesquels les joueurs peuvent interagir pendant qu'une [beatmap](/wiki/Beatmap) est joué. Chaque [mode de jeu](/wiki/Game_mode) possède son propre ensemble d'objets
```suggestion
Les *objets* sont des éléments avec lesquels les joueurs peuvent intéragir pendant qu'une [beatmap](/wiki/Beatmap) est jouée. Chaque [mode de jeu](/wiki/Game_mode) possède son propre ensemble d'objets qui modifie l'expérience de jeu. Pour un aperçu des objets de chaque mode de jeu, consultez le tableau suivant :
```

2021-06-05 06:52 UTC, Ganondorf-1 commented on wiki/Hit_object/fr.md
> +Dans le mode osu!, le prochain cercle ou slider à frapper est mis en évidence avec une luminosité légèrement accrue par rapport aux autres objets sur le terrain de jeu. Cependant, la mise en évidence
```suggestion
Dans le mode osu!, le prochain cercle ou slider à cliquer est mis en évidence avec une luminosité légèrement accrue par rapport aux autres objets sur le terrain de jeu. Cependant, la mise en évidence ne sera plus visible si l'[approach rate](/wiki/Beatmapping/Approach_rate) est trop élevé.
```

2021-06-08 21:22 UTC, Ganondorf-1 requested changes

2021-06-08 21:22 UTC, Ganondorf-1 commented on wiki/Hit_object/Slider/fr.md
> +Un *slider* est un [objet](/wiki/Hit_Objects) dans le mode de jeu [osu!](/wiki/Game_mode/osu!), qui consiste en un sliderhead, un sliderbody et un slidertail. Une fois que le cercle d'approche attein
```suggestion
Un *slider* est un [objet](/wiki/Hit_Objects) dans le mode de jeu [osu!](/wiki/Game_mode/osu!), qui consiste en un sliderhead, un sliderbody et une slidertail. Une fois que le cercle d'approche atteint le sliderhead, comme avec les [cercles](/wiki/Hit_object/Hit_circle), le joueur doit cliquer/taper sur le début du slider, puis, en maintenant le bouton enfoncé, suivre une boule mobile (appelée slider ball) le long de la piste jusqu'à ce que la slidertail soit atteinte. S'il y a une flèche inversée, le joueur doit suivre la slider ball sur le même chemin. Les sliders avec des flèches inversées sont appelés [reverse sliders](/wiki/Hit_object/Reverse_slider). La vitesse d'un slider est définie par la [slider velocity](/wiki/Hit_object/Slider_velocity) et le multiplicateur de slider velocity de la section de timing en cours.
```

2021-06-08 21:22 UTC, Ganondorf-1 commented on wiki/Hit_object/Slider/fr.md
> +Les sliders sont souvent associés à des sons longs ou tenus dans la musique, mais peuvent être utilisés n'importe où tant qu'il y a un rythme pour les soutenir. Les sliders sont utilisés pour rendre
```suggestion
Les sliders sont souvent associés à des sons longs ou tenus dans la musique, mais peuvent être utilisés n'importe où tant qu'il y a un rythme pour les soutenir. Les sliders sont utilisés pour rendre la lecture intuitive lorsque les chansons ont des changements de rythme, car les slidertails donnent un feedback mais sont jouées passivement. Les sliders sont également utilisés pour simplifier le rythme sur des difficultés plus faciles.
```

2021-06-13 10:12 UTC, Ganondorf-1 approved these changes

2021-06-13 21:49 UTC, TicClick approved these changes

2021-06-13 21:49 UTC, merged