[FR] Update "Installation", add "macOS"
ppy/osu-wiki pull request #5612
Opened 2021-05-28 18:55 UTC by DoryanR

Proposal for the French translation of the wiki page `Installation`.

Proposal to update the French translation of the wiki page `macOS`.

2021-06-04 18:10 UTC, geshii approved these changes

2021-06-05 01:24 UTC, TPGPL requested changes

2021-06-05 01:24 UTC, TPGPL commented on wiki/Installation/fr.md
> +- .NET framework 4+ (le programme d'installation devrait vous inviter à le télécharger, sinon, vous pouvez le trouver [ici](https://www.microsoft.com/en-us/download/details.aspx?id=48130)
```suggestion
- .NET framework 4+ (le programme d'installation devrait vous inviter à le télécharger, sinon, vous pouvez le trouver [ici](https://www.microsoft.com/fr-fr/download/details.aspx?id=48130))
```

2021-06-05 01:24 UTC, TPGPL commented on wiki/Installation/fr.md
> +- Nettoyez votre PC - Analysez-le avec un logiciel anti-virus, nettoyez le registre. Un bon programme pour un nettoyage général est [PrivaZer](https://privazer.com/fr/)<!-- PrivaZer est mieux que CCl
```suggestion
- Nettoyez votre PC - Analysez-le avec un logiciel anti-virus, nettoyez le registre. Un bon programme pour un nettoyage général est CCleaner. Analysez à la fois les fichiers de votre ordinateur et votre registre. L'installateur peut échouer s'il y a des entrées de registre d'une copie précédente d'osu! encore présentes sur votre système.
```

2021-06-05 01:25 UTC, TPGPL approved these changes

2021-06-05 01:26 UTC, merged