[FR] Update "Legal", "Privacy", add "Copyright", "Music Licensing", "Terms"
ppy/osu-wiki pull request #5620
Opened 2021-05-29 17:02 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Legal/Privacy`
- `Legal`

Translation of the following wiki pages:

- `Legal/Copyright`
- `Legal/Music_Licensing`
- `Legal/Terms`

2021-06-22 19:16 UTC, Satsukel requested changes

2021-06-22 19:16 UTC, Satsukel commented on wiki/Legal/Music_Licensing/fr.md
> +100% du contenu d'osu! (généralement connu sous le nom de "[beatmaps](/wiki/Beatmap)" ou de niveaux de jeu) est téléchargé par les utilisateurs. Bien que nous essayions de guider les utilisateurs pou
```suggestion
100% du contenu d'osu! (généralement connu sous le nom de "[beatmaps](/wiki/Beatmap)" ou de niveaux de jeu) est téléchargé par les utilisateurs. Bien que nous essayions de guider les utilisateurs pour qu'ils obtiennent correctement une autorisation, il y a souvent des cas de musique ou d'œuvres d'art téléchargées sans avoir obtenu correctement cette autorisation.
```

2021-06-22 19:16 UTC, Satsukel commented on wiki/Legal/Music_Licensing/fr.md
> +La licence musicale d'osu! peut être téléchargée gratuitement depuis la page [Artistes Associés](https://osu.ppy.sh/beatmaps/artists) dans des fichiers `.osz`, qui sont des modèles de beatmap. Un ape
```suggestion
La licence musicale d'osu! peut être téléchargée gratuitement depuis la page [Artistes Associés](https://osu.ppy.sh/beatmaps/artists) dans des fichiers `.osz`, qui sont des modèles de beatmap. Un aperçu d'une minute généré automatiquement de chaque morceau est disponible en streaming sur la page de l'artiste. Les chansons étant utilisées comme un catalogue permettant aux membres de la communauté de créer des beatmaps, il se peut que certaines d'entre elles ne soient pas encore utilisées comme contenu dans le jeu.
```

2021-06-26 20:36 UTC, DoryanR commented
@Satsukel As soon as you are available I let you do a reckeck

2021-06-27 20:02 UTC, Satsukel requested changes

2021-06-27 21:18 UTC, Satsukel approved these changes

2021-07-02 06:26 UTC, DoryanR commented
Can be merge 👍

2021-07-02 19:41 UTC, TPGPL approved these changes

2021-07-02 19:41 UTC, merged