Create id.md
ppy/osu-wiki pull request #5630
Opened 2021-06-01 14:36 UTC by LazyScriptKiddie

Add indonesian language for osu-wiki/wiki/Community_Mentorship_Program/

2021-06-01 14:43 UTC, LazyScriptKiddie commented
Sorry wrong format, forgot to change and accidentally pressed the button.

2021-06-08 03:04 UTC, ZeroPyrozen requested changes

2021-06-08 03:04 UTC, ZeroPyrozen commented on wiki/Community_Mentorship_Program/id.md
> +Program ini diorganisir melalui Discord dan dikelola dalam siklus musiman. Setiap siklus diumumkan melalui sebuah postingan forum dan siklus diberitahukan melalui laman berita.
```suggestion
Program ini diorganisasikan melalui Discord dan dikelola dalam siklus musiman. Setiap siklus diumumkan melalui sebuah postingan forum dan siklus diberitahukan melalui laman berita.
```

2021-06-08 03:48 UTC, ZeroPyrozen approved these changes

2021-06-13 22:07 UTC, TicClick approved these changes

2021-06-13 22:08 UTC, merged