[FR] Add "Account restrictions"
ppy/osu-wiki pull request #5640
Opened 2021-06-02 20:53 UTC by Ganondorf-1

French translation of osu! wiki - Account restrictions

2021-06-03 14:10 UTC, DoryanR requested changes

2021-06-03 14:10 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +Si vous pensez que vos mails ne sont pas lus ou traités correctement par notre équipe de support, veuillez nous envoyer un mail à [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh) contenant les inf
```suggestion
Si vous pensez que vos mails ne sont pas lus ou traités correctement par notre équipe de support, veuillez nous envoyer un mail à [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh) contenant les informations suivantes :
```

2021-06-03 14:10 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +- Un bref résumé des raisons pour lesquelles vous n'êtes pas satisfait du résultat de votre appel (Si possible)
```suggestion
- Un bref résumé des raisons pour lesquelles vous n'êtes pas satisfait du résultat de votre appel (si possible)
```

2021-06-03 14:10 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +Tous les mails envoyés à l'adresse de revue d'appels seront examinés par un tiers qui n'est pas impliqué dans les opérations quotidiennes de l'équipe de support et seront signalés pour une révision o
```suggestion
Tous les mails envoyés à l'adresse de review d'appels seront examinés par un tiers qui n'est pas impliqué dans les opérations quotidiennes de l'équipe de support et seront signalés pour une révision ou davantage de reviews.
```

2021-06-03 14:10 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +Veuillez comprendre que l'envoi d'un mail à cette adresse ne garantit qu'une deuxième revue ou la réponse initiale à votre appel, cela ne garantit pas un changement dans les résultats si vous avez en
```suggestion
Veuillez comprendre que l'envoi d'un email à cette adresse ne garantit qu'un second examen/une première réponse à votre appel, mais ne garantit pas un changement de résultat s'il s'avère que vous avez violé les attentes impliquées dans la procédure d'appel.
```

2021-06-03 14:10 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +**Nous ne répondrons qu'aux requêtes de revue d'appels envoyés à [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** N'essayez pas de contacter les membres de l'équipe osu! (ou les membres des équ
```suggestion
**Nous ne répondrons aux demandes d'examen d'appel ou d'enquête que par le biais d'emails envoyés à [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** N'essayez pas de contacter les membres de l'équipe d'osu! (ou les membres des équipes de bénévoles) via Twitter, Discord ou toute autre plateforme afin de contourner cette politique - ils ne peuvent pas vous aider.
```

2021-06-04 18:08 UTC, geshii commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +**Nous ne répondrons qu'aux requêtes de revue d'appels envoyés à [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** N'essayez pas de contacter les membres de l'équipe osu! (ou les membres des équ
envoyées**

2021-06-07 19:58 UTC, geshii approved these changes

2021-06-09 13:07 UTC, DoryanR commented
Before merge, I prefer to check one last time

2021-06-09 13:57 UTC, DoryanR requested changes

2021-06-09 13:57 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +- **Continuez à jouer !** Tant que votre compte est restreint et que vous avez un cooldown, vous êtes plus que bienvenu pour continuer à jouer (tant que vous jouez sur votre compte principal !). Les
```suggestion
- **Continuez à jouer !** Tant que votre compte est restreint et que vous avez un cooldown, vous êtes plus que bienvenue pour continuer à jouer (tant que vous jouez sur votre compte principal !). Les scores que vous réalisez pendant votre restriction seront bien pris en compte, et à moins que vos scores soient partiellement ou totalement supprimés, ils resteront lorsque la restriction sera levée.
```

2021-06-09 13:57 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +- **Vous ne créerez pas d'autre compte, que ça soit pour vous ou quelqu'un d'autre.**
```suggestion
- **Vous ne créerez pas d'autre compte, que ça soit pour vous ou pour quelqu'un d'autre.**
```

2021-06-09 13:57 UTC, DoryanR commented on wiki/Help_Centre/Account_Restrictions/fr.md
> +## Mes mails sont ignorés / Je ne pense pas que mon appel a été traité de façon juste
```suggestion
## Mes mails sont ignorés/Je ne pense pas que mon appel a été traité de façon juste
```

2021-06-10 04:18 UTC, DoryanR approved these changes

2021-06-13 21:53 UTC, TicClick approved these changes

2021-06-13 21:53 UTC, merged