[ID] Update `osu!talk`
ppy/osu-wiki pull request #5641
Opened 2021-06-03 01:12 UTC by ZeroPyrozen

Update osu!talk episodes, discussions, and specials for Indonesian translation.

2021-06-03 14:00 UTC, mousesalt requested changes

2021-06-03 14:00 UTC, mousesalt commented on wiki/osu!talk/id.md
> +- [Kanal resmi YouTube](https://www.youtube.com/user/osuacademy/videos)
```suggestion
- [Kanal YouTube resmi](https://www.youtube.com/user/osuacademy/videos)
```

2021-06-03 14:00 UTC, mousesalt commented on wiki/osu!talk/id.md
> +- [Kanal resmi YouTube](https://www.youtube.com/user/osuacademy/videos)
that was mean like to youtube's channel instead

2021-06-05 05:05 UTC, ZeroPyrozen commented on wiki/osu!talk/id.md
> +| 1 | Pengerjaan Ulang Staf | [Charles445](https://osu.ppy.sh/users/85000), [Ephemeral](https://osu.ppy.sh/users/102335), dan [OnosakiHito](https://osu.ppy.sh/users/290128) | [Tautan](https://www.you
I'm not sure about this one, other translated language translate most of the topic but few of them are leave as it is.

There should be original topic and alternate topic title columns like these example:

1. [Netflix - Do I need to translate episode titles for Korean timed text assets?](https://partnerhelp.netflixstudios.com/hc/en-us/articles/115000783548-Do-I-need-to-translate-episode-titles-for-Korean-timed-text-assets-)
2. [IMDb - Alternate titles (AKAs)](https://help.imdb.com/article/contribution/titles/alternate-titles-akas/GBFBWTQG2RLMHSUR?ref_=helpsect_pro_4_8#)
3. [List of Lucifer episodes](https://en.wikipedia.org/wiki/List_of_Lucifer_episodes) | [Lucifer (Fernsehserie)/Episodenliste](https://de.wikipedia.org/wiki/Lucifer_(Fernsehserie)/Episodenliste)

2021-06-05 07:48 UTC, mousesalt submitted a review, later dismissed

2021-06-06 04:01 UTC, AncuL001 approved these changes
the rest seems ok

2021-06-06 04:01 UTC, AncuL001 commented on wiki/osu!talk/id.md
> +| EP No. | Topik | Narasumber | Tautan |
```suggestion
| No. EP | Topik | Narasumber | Tautan |
```

2021-06-06 04:01 UTC, AncuL001 commented on wiki/osu!talk/id.md
> +| EP No. | Topik | Narasumber | Tautan |
```suggestion
| No. EP | Topik | Narasumber | Tautan |
```

2021-06-20 13:35 UTC, mousesalt approved these changes
this looks fine 👍 great

2021-06-25 21:29 UTC, TicClick approved these changes

2021-06-25 21:29 UTC, merged