[FR] Add `Mapping and Modding Timeline`, fix links in other file
ppy/osu-wiki pull request #5652
Opened 2021-06-05 17:26 UTC by DoryanR

Proposal for the French translation of the wiki page `Mapping and Modding Timeline`.

Also:

- In `en.md` and `id.md` : fix links and move a section to the right place.

Many links (even those outside the notes) are not accessible.

2021-06-06 03:54 UTC, AncuL001 commented
why not just use https://discord.com/ instead of https://discord.com/brand-new ? the latter has a risk of possibly be deleted while the homepage will always exist

2021-06-06 07:13 UTC, DoryanR commented on wiki/Mapping_and_Modding_Timeline/en.md
> +  - Its new structure was centered around [Discord](https://discord.com/brand-new) communication and seasonal cycles.
```suggestion
  - Its new structure was centered around [Discord](https://discord.com/) communication and seasonal cycles.
```

2021-06-06 07:13 UTC, DoryanR commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Sa nouvelle structure était centrée sur la communication par [Discord](https://discord.com/brand-new) et les cycles saisonniers.
```suggestion
  - Sa nouvelle structure était centrée sur la communication par [Discord](https://discord.com/) et les cycles saisonniers.
```

2021-06-06 07:13 UTC, DoryanR commented on wiki/Mapping_and_Modding_Timeline/id.md
> +  - Tidak seperti program Community Mentorship terdahulu, program Community Mentorship kali ini menggunakan [Discord](https://discord.com/brand-new) sebagai sarana komunikasi utama antar para mentor
```suggestion
  - Tidak seperti program Community Mentorship terdahulu, program Community Mentorship kali ini menggunakan [Discord](https://discord.com/) sebagai sarana komunikasi utama antar para mentor dan *mentee*-nya masing-masing.
```

2021-07-01 12:30 UTC, Satsukel requested changes
Je finirai le reste ce soir, j'ai corrigé pas mal de fautes d'accords et des petits bouts de phrases un peu bizarres

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Seule une des deux bubble d'une carte approuvée pouvait être placée par un membre du MAT.
Je pense qu'il est préférable de rester sur "beatmap" même s'il n'y a que "map" dans la version originale, à moins que l'on prenne aussi "map" comme abrévation de "beatmap"
```suggestion
  - Seule une des deux bubble d'une beatmap approuvée pouvait être placée par un membre du MAT.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Ce changement a été mis en œuvre parce que les beatmaps approuvés devenaient plus courants.
```suggestion
  - Ce changement a été mis en œuvre parce que les beatmaps approuvées devenaient plus courantes.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les BAT a acquis l'entière responsabilité des ajouts des MAT.
```suggestion
  - Les BAT ont acquis l'entière responsabilité des ajouts des MAT.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**1368 beatmaps** ont été classés en 2011. Il s'agit de la première baisse après 4 années de croissance consécutives.
```suggestion
**1368 beatmaps** ont été classées en 2011. Il s'agit de la première baisse après 4 années de croissance consécutives.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **21/08/2012 :** Les beatmaps de la catégorie [approuvée](/wiki/Beatmap/Category#approved) ont commencé à récompenser le score classé.
Je pense qu'on peut trouver mieux mais en tout cas ici la traduction est trop littérale
```suggestion
- **21/08/2012 :** Les beatmaps de la catégorie [approuvée](/wiki/Beatmap/Category#approved) ont commencé à faire gagner du score classé.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Le score classé n'est plus utilisé comme principale mesure de score, de sorte que les beatmaps approuvés ne peuvent plus être utilisés abusivement pour le classement des joueurs.
```suggestion
  - Le score classé n'est plus utilisé comme principale mesure de score, de sorte que les beatmaps approuvées ne peuvent plus être utilisées abusivement pour le classement des joueurs.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**1460 beatmaps** ont été classés en 2012.
```suggestion
**1460 beatmaps** ont été classées en 2012.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **23/04/2013 :** Le MAT a été démantelé.
Vu que y a "la MAT" juste après et que ça me semble plus logique de dire "la" vu que ça désigne une équipe.
```suggestion
- **23/04/2013 :** La MAT a été démantelée.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les BAT était également assez inactive à cette époque, un afflux important de nouveaux membres a donc permis de résoudre ce problème.
Ici "les BAT" sous-entends "les membres de la BAT" donc masculin.
```suggestion
  - Les BAT étaient également assez inactifs à cette époque, un afflux important de nouveaux membres a donc permis de résoudre ce problème.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **02/08/2013 :** Les premier BAT du mode osu!taiko ont été ajoutées, ce qui signifie une séparation des autorisations de mode de jeu dans le groupe.
```suggestion
- **02/08/2013 :** Les premiers BAT du mode osu!taiko ont été ajoutées, ce qui signifie une séparation des autorisations de mode de jeu dans le groupe.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **12/12/2013 :** Les beatmaps avec deux nominations ont commencé à être promus dans la catégorie [qualifiée](/wiki/Beatmap/Category#qualifiée) au lieu de la catégorie classée.
```suggestion
- **12/12/2013 :** Les beatmaps avec deux nominations ont commencées à être promues dans la catégorie [qualifiée](/wiki/Beatmap/Category#qualifiée) au lieu de la catégorie classée.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les beatmaps qualifiés pourraient être disqualifiés dans un délai d'une semaine, remplaçant ainsi la possibilité de déclasser un beatmap dans un délai d'une semaine.
```suggestion
  - Les beatmaps qualifiées pourraient être disqualifiées dans un délai d'une semaine, remplaçant ainsi la possibilité de déclasser une beatmap dans un délai d'une semaine. 
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**1327 beatmaps** ont été classés en 2013.
```suggestion
**1327 beatmaps** ont été classées en 2013.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **21/08/2014 :** La [Quality Assurance Team](/wiki/Modding/Quality_Assurance_Team) (*QAT*) se sépare des BAT actuelle.
```suggestion
- **21/08/2014 :** La [Quality Assurance Team](/wiki/Modding/Quality_Assurance_Team) (*QAT*) se sépare des BAT actuels.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les BAT (souvent appelé newBAT à cette époque) désigne les beatmaps pour le classement.
```suggestion
  - Les BAT (souvent appelé newBAT à cette époque) désigne les beatmaps à classer.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les QAT s'assure que les beatmaps qualifiés étaient de qualité suffisante. Les beatmaps qui ne répondaient pas aux normes de qualité étaient disqualifiés.
```suggestion
  - Les QAT s'assure que les beatmaps qualifiés étaient de qualité suffisante. Les beatmaps qui ne répondaient pas aux normes de qualité étaient disqualifiées.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Malgré les tentatives de présenter les disqualifications comme un changement positif pour la qualité des maps, la communauté les a perçues de manière négative. Cela était particulièrement évident
```suggestion
  - Malgré les tentatives de présenter les disqualifications comme un changement positif pour la qualité des maps, la communauté les a perçues de manière négative. Cela était particulièrement évident dans le cas de beatmaps controversées comme [disqualification on *Halozy - Genryuu Kaiko*](https://osu.ppy.sh/community/forums/posts/3591479)
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - L'accessibilité du public aux BAT a augmenté, ce qui était l'objectif du modding v2.
```suggestion
  - L'accessibilité du public aux BAT a augmentée, ce qui était l'objectif du modding v2.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les questions relatives aux beatmaps nominés/qualifiés ont été postées ici, ainsi que toute annonce relative aux systèmes de mapping/modding.
```suggestion
  - Les questions relatives aux beatmaps nominées/qualifiées ont été postées ici, ainsi que toute annonce relative aux systèmes de mapping/modding.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les utilisateurs ayant obtenu au moins 15 votes et dont l'activité de modding est calculée automatiquement seront promus au groupe par intermittence.
```suggestion
  - Les utilisateurs ayant obtenu au moins 15 votes et dont l'activité de modding est calculée automatiquement seraient promus au groupe par intermittence.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**1381 beatmaps** ont été classés en 2014.
```suggestion
**1381 beatmaps** ont été classées en 2014.
```

2021-07-01 12:30 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **01/02/2015 :** Les noms d'utilisateurs rouges ont été supprimés des BAT et les BAT a été renommé en [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) (*BN*).
```suggestion
- **01/02/2015 :** Les noms d'utilisateurs rouges ont été supprimés des BAT et les BAT ont été renommés en [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) (*BN*).
```

2021-07-01 18:51 UTC, Satsukel requested changes

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Les vétos pourraient être écrasés par les nominations des Beatmap Nominators qui n'ont pas été impliqués dans la beatmap.
```suggestion
  - Les vétos pouvaient être écrasés par les nominations des Beatmap Nominators qui n'ont pas été impliqués dans la beatmap.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**1720 beatmaps** ont été classés en 2016.
```suggestion
**1720 beatmaps** ont été classées en 2016.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +    - Les nominateurs de niveau 1 pourraient mettre des bubbles sur les maps.
```suggestion
    - Les nominateurs de niveau 1 pouvaient mettre des bubbles sur les maps.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +    - Les nominateurs de niveau 2 pourraient mettre des bubbles et qualifier les maps..
```suggestion
    - Les nominateurs de niveau 2 pouvaient mettre des bubbles et qualifier les maps..
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Auparavant, il fallait 3 nominations car on s'attendait à ce que les marathons aient plus de contenu à vérifier qu'une beatmap normal, mais ce n'est plus vrai.
```suggestion
  - Auparavant, il fallait 3 nominations car on s'attendait à ce que les marathons aient plus de contenu à vérifier qu'une beatmap normale, mais ce n'est plus vrai.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **10/09/2017 :** Le "[QAT Upheaval](https://osu.ppy.sh/community/forums/topics/635507)" a été mis en place. Il s'agissait d'une série de changements en réponse au mécontentement de la communauté de
```suggestion
- **10/09/2017 :** Le "[QAT Upheaval](https://osu.ppy.sh/community/forums/topics/635507)" a été mis en place. Il s'agissait d'une série de changements en réponse au mécontentement de la communauté de mapping sous la direction de l'[osu!team](/wiki/People/The_Team). Suite à ce changement, les QAT ont commencés à s'autogérer sans l'intervention de leurs supérieurs.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Beatmap Nominators were given purple titles on the forums.
```suggestion
  - Des titres violets ont été donnés aux Beatmap Nominators sur les forums.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Des badges de profil Beatmap Nominator et Quality Assurance Team ont été créés. Cette récompense et d'autres récompenses pour les Beatmap Nominator ont été prévues pour remotiver l'équipe actuell
```suggestion
  - Des badges de profil Beatmap Nominator et Quality Assurance Team ont été créés. Cette distinction et d'autres récompenses pour les Beatmap Nominator ont été prévues pour remotiver l'équipe actuellement insatisfaite.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Avec une direction moins autoritaire et plus d'utilisateurs capables de nommer des beatmaps après ces changements, les normes de mapping ont cessé d'être strictement contrôlées. Des beatmaps cont
```suggestion
  - Avec une direction moins autoritaire et plus d'utilisateurs capables de nommer des beatmaps après ces changements, les normes de mapping ont cessées d'être strictement contrôlées. Des beatmaps controversées qui n'auraient probablement pas été classées sous l'ancien système (par exemple *[FELT - Rendezvous](https://osu.ppy.sh/beatmapsets/725171#osu/1541573)*) ont atteint un statut classé.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Ce changement a été effectué parce que la tricherie aux BN test était devenue impossible à éviter.
```suggestion
  - Ce changement a été effectué parce que la tricherie aux BN test était devenue monnaie courante.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**1847 beatmaps** ont été classés en 2017.
```suggestion
**1847 beatmaps** ont été classées en 2017.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **24/03/2018 :** Le sous-forum Critères de classement a été rouvert pour les discussions publiques sur les propositions et l'UBKRC a été supprimé.
```suggestion
- **24/03/2018 :** Le sous-forum Critères de classement a été rouvert pour les discussions publiques des propositions et l'UBKRC a été supprimé.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **01/04/2018 :** La QAT a commencé à évaluer les demandes des BN en examinant les mods non anonymes, par opposition aux mods précédemment anonymes.
```suggestion
- **01/04/2018 :** La QAT a commencée à évaluer les demandes des BN en examinant les mods non anonymes, par opposition aux mods précédemment anonymes.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Grâce à ce changement, la QAT a déterminé que la partialité ne pouvait être évitée lors de l'évaluation des Beatmap Nominators.
```suggestion
  - Grâce à ce changement, la QAT a déterminée que la partialité ne pouvait être évitée lors de l'évaluation des Beatmap Nominators.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **22/05/2018 :** ![][flag_DE] [Mao](https://osu.ppy.sh/users/2204515) devient un [responsable QAT](/wiki/Modding/QAT_Leaders) après que ![][flag_DE] [Okoratu](https://osu.ppy.sh/users/1623405) s'es
```suggestion
- **22/05/2018 :** ![][flag_DE] [Mao](https://osu.ppy.sh/users/2204515) devient un [responsable QAT](/wiki/Modding/QAT_Leaders) après que ![][flag_DE] [Okoratu](https://osu.ppy.sh/users/1623405) se soit retiré.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Avant ce changement, toute carte dont le drain time était inférieur à 5 minutes nécessitait un écart de difficulté complet. Après ce changement, les exigences en matière d'écart de difficulté éta
```suggestion
  - Avant ce changement, toute map dont le drain time était inférieur à 5 minutes nécessitait un écart de difficulté complet. Après ce changement, les exigences en matière d'écart de difficulté étaient plus souples pour les beatmaps plus longues dont le drain time était inférieur à 5 minutes.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **12/12/2018 :** L'équipe d'osu! a pris une [position négative sur les commissions des beatmap](https://osu.ppy.sh/community/forums/topics/840838).
```suggestion
- **12/12/2018 :** L'équipe d'osu! a pris une [position négative sur les commissions des beatmaps](https://osu.ppy.sh/community/forums/topics/840838).
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Cette décision a été prise parce que la QAT n'avait pas été impliqué dans quoi que ce soit lié à l'assurance qualité depuis des années, mais un système devait exister pour maintenir les Beatmap N
```suggestion
  - Cette décision a été prise parce que la QAT n'avait pas été impliquée dans quoi que ce soit lié à l'assurance qualité depuis des années, mais un système devait exister pour maintenir les Beatmap Nominators et la communauté de mapping en général.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +    - Peu d'engagement de la QAT dans les cartes controversées.
```suggestion
    - Peu d'engagement de la QAT dans les maps controversées.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**2749 beatmaps** ont été classés en 2018. La croissance impressionnante de cette année peut être largement attribuée à l'abandon du rôle d'assurance qualité de la QAT et à une plus grande initiative
```suggestion
**2749 beatmaps** ont été classées en 2018. La croissance impressionnante de cette année peut être largement attribuée à l'abandon du rôle d'assurance qualité de la QAT et à une plus grande initiative des Beatmap Nominators.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Parallèlement à ce changement, les Beatmap Nominators peuvent opposer leur veto aux beatmaps qualifiés. Cette règle existait à l'origine parce que les Beatmap Nominators avaient besoin de 24 heur
```suggestion
  - Parallèlement à ce changement, les Beatmap Nominators peuvent opposer leur veto aux beatmaps qualifiées. Cette règle existait à l'origine parce que les Beatmap Nominators avaient besoin de 24 heures pour appliquer potentiellement des vetos aux maps avec une nomination.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +    - Grâce au site web, les utilisateurs pouvaient poser leur candidature à la BN à tout moment, contrairement au système précédent, basé sur des cycles. De ce fait, les Beatmap Nominators ont été a
```suggestion
    - Grâce au site web, les utilisateurs pouvaient poser leur candidature à la BN à tout moment, contrairement au système précédent, basé sur des cycles. De ce fait, les Beatmap Nominators ont été ajoutés par intermitences plutôt que par grandes vagues.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +    - Les signalements de beatmaps inappropriés et de comportements répréhensibles des BN/NAT sont passés d'un formulaire Google au site web des BN.
```suggestion
    - Les signalements de beatmaps inappropriées et de comportements répréhensibles des BN/NAT sont passés d'un formulaire Google au site web des BN.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +    - Les statistiques et les évaluations de l'activité et de la compétence du modding et des nominateurs des BN sont passées de Google Spreadsheets, douloureusement inefficaces, au site web des BN,
```suggestion
    - Les statistiques et les évaluations de l'activité et de la compétence du modding et des nominateurs des BN sont passées de Google Spreadsheets, douloureusement inefficaces, au site web des BN, ce qui a considérablement augmenté la productivité de la gestion des Beatmap Nominators.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +**3217 beatmaps** ont été classés en 2019.
```suggestion
**3217 beatmaps** ont été classées en 2019.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Elles avaient été prévues à l'origine lors du bouleversement de la QAT deux ans auparavant.
On parle des badges là non ? Je met "Ils" au cas où
```suggestion
  - Ils avaient été prévues à l'origine lors du bouleversement de la QAT deux ans auparavant.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Ce changement a été effectué pour tenir compte de l'activité d'assurance qualité dans les évaluations des Beatmap Nominator.
```suggestion
  - Ce changement a été effectué pour tenir compte de l'activité d'assurance qualité dans les évaluations des Beatmap Nominators.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **29/10/2020 :** La compétence du mode de jeu d'un Beatmap Nominator est devenue visible sur le site d'osu!.
```suggestion
- **29/10/2020 :** La compétence des modes de jeu des Beatmap Nominators sont devenues visibles sur le site d'osu!.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **30/11/2020 :** Les beatmaps hybrides ont été retravaillés pour nécessiter 2 nominations par mode de jeu.
```suggestion
- **30/11/2020 :** Les beatmaps hybrides ont été retravaillées pour nécessiter 2 nominations par mode de jeu.
```

2021-07-01 18:51 UTC, Satsukel commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **17/12/2020 :** La soumission et l'évaluation de l'examen du contenu inapproprié sont passées des discussions sur Discord aux votes à l'aveugle via le site web des [Beatmap Nominator](https://bn.m
```suggestion
- **17/12/2020 :** La soumission et l'évaluation de l'examen du contenu inapproprié sont passées des discussions sur Discord aux votes à l'aveugle via le site web des [Beatmap Nominators](https://bn.mappersguild.com/).
```

2021-07-01 20:32 UTC, TPGPL approved these changes

2021-07-01 20:33 UTC, merged