[ID] Add Dragging
ppy/osu-wiki pull request #5664
Opened 2021-06-07 11:36 UTC by Fhoxydeo

2021-06-07 11:56 UTC, ZeroPyrozen requested changes

2021-06-07 11:56 UTC, ZeroPyrozen commented on wiki/Play_style/Drag/id.md
> +**Drag** adalah istilah yang digunakan untuk mengambarkan tindakan menavigasi (atau "membidik") sebuah pena [tablet](/wiki/Gameplay/Input_device/Graphics_tablet) dengan menyentuhkan pena secara fisik
```suggestion
**Drag** adalah istilah yang digunakan untuk menggambarkan tindakan menavigasi (atau "membidik") sebuah pena [tablet](/wiki/Gameplay/Input_device/Graphics_tablet) dengan menyentuhkan pena secara fisik pada permukaan tablet dan "menyeret" ke lokasi yang diinginkan (berlawanan dengan [hovering](/wiki/Play_style/Hover)). Gaya ini digunakan oleh pemain dari semua tingkat keahlian dan mudah dipelajari.
```

2021-06-07 11:56 UTC, ZeroPyrozen commented on wiki/Play_style/Drag/id.md
> +---
add `- gaya bermain` stub if possible

2021-06-08 02:58 UTC, ZeroPyrozen submitted a review, later dismissed
All good 👍

2021-06-13 21:50 UTC, TicClick approved these changes

2021-06-13 21:50 UTC, merged