[FR] Add `Mapping Techniques/Rhythm`, `Sliders`, `Spinners`, `Unrankable`, improvement of EN files
ppy/osu-wiki pull request #5665
Opened 2021-06-07 17:01 UTC by DoryanR

Translation of the following wiki pages:

- `Mapping_Techniques/Rhythm`
- `Mapping_Techniques/Sliders`
- `Mapping_Techniques/Spinners`
- `Mapping_Techniques/Unrankable`

Also:

- In `Mapping_Techniques/Rhythm/en.md`: bold some elements, and fix typo.
- In `Mapping_Techniques/Sliders/en.md`: bold some elements, fix links, and fix typo.
- In `Mapping_Techniques/Spinners/en.md` : convert `_` > `*`, bold some elements.
- In `Mapping_Techniques/Unrankable/en.md`: convert `_` > `*`, bold some elements, and fix typo.

2021-06-13 12:56 UTC, Satsukel requested changes
Je finirai le reste plus tard ce soir, prends le temps de lire certains point de ma review parce qu'il y a des changements qui peuvent t'inspirer pour trouver la bonne forme de phrase  (normalement tu t'apercevras desquels je parle).

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Une certaine lecture à haute voix peut être requise, à moins que vous ne puissiez vraiment suivre la musique.
"Sightreading" faudrait surement l'ajouter à la liste des termes parce qu'il est assez répendu est un peu dur à traduire en français. J'ai supprimé la négation parce que globalement le message c'est "Si tu ne sais pas à quoi t'attendre il faut que tu saches vraiment bien suivre la musique"
```suggestion
Du sightreading peut être requis, à moins que vous puissiez vraiment bien suivre la musique.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Lorsque vous jouez une beatmap en utilisant cette technique, il peut être très difficile de jouer avec le modificateur de jeu Hidden.
Ici c'est la beatmap qui utilise la technique
```suggestion
Lorsque vous jouez une beatmap utilisant cette technique, il peut être très difficile de jouer avec le modificateur de jeu Hidden.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Le **sections de drainage** sont des sections dans une beatmap qui deviennent soudainement *plus lentes* ou *moins difficiles* dans le but de mieux correspondre à la chanson ou de faire baisser la ba
```suggestion
Les **sections de drainage** sont des sections dans une beatmap qui deviennent soudainement *plus lentes* ou *moins difficiles* dans le but de mieux correspondre à la chanson ou de faire baisser la barre de vie.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Les sections de drainage doivent être utilisées avec parcimonie et uniquement lorsque la chanson peut *y faire* allusion.
Je sais pas si ma tournure est la bonne mais je pense qu'il faut changer le "faire allusion"
```suggestion
Les sections de drainage doivent être utilisées avec parcimonie et uniquement lorsque la chanson peut *s'y prêter*.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Vous pouvez toutefois utiliser 3, 5 ou 6 rayons à la place (dans ce cas, veillez à ce que la mesure du degré reste égale pour chaque rayon).
J'ai essayé de remplacer degré par centimètre pour voir ce qui était mieux et je trouve que c'est mieux au pluriel même si c'est au singulier en anglais (mais il y a des fois ou des singuliers en anglais se traduisent par des pluriels en français et vice-versa il me semble)
Après je pense qu'il y a une meilleure façon d'écrire cette phrase que celle que je propose x)
```suggestion
Vous pouvez toutefois utiliser 3, 5 ou 6 rayons à la place (dans ce cas, veillez à ce que la mesure des degrés reste égale pour chaque rayon).
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +L'**aller-retour linéaires** est une variation des [battements aller-retour](#battements-aller-retour).
```suggestion
L'**aller-retour linéaire** est une variation des [battements aller-retour](#battements-aller-retour).
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Il est très important que le mappeur indique clairement la direction dans laquelle se dirige la propagation.
Je pense qu'il faut trouver autre chose que "propagation"
```suggestion
Il est très important que le mappeur indique clairement la direction dans laquelle se dirige l'espacement.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Le **spacing out** fait référence aux objets dans lesquels ils sont placés en termes de distance, et non de temps.
```suggestion
Le **spacing out** fait référence aux objets tels qu'ils sont placés en termes de distance, et non de temps.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Cependant, un patternmapping incorrect peut conduire à une map presque injouable.
Je chipote un peu là j'avoue, je trouvais juste que ça faisait juste un peu plus fluide comme ça donc à toi de voir :^)
```suggestion
Cependant, un patternmapping incorrect peut conduire à une map quasiment injouable.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Le **step-too-fars** utilise une trajectoire linéaire de cercles qui sont espacés d'un quart de temps.
Je pense que c'est au pluriel bien que ce ne soit pas clair sur le wiki anglais
```suggestion
Les **step-too-fars** utilisent une trajectoire linéaire de cercles qui sont espacés d'un quart de temps.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +La majorité des maps qui utilisent des streams sont les plus susceptibles d'être vues en utilisant des steams compressés.
Je suis pas sûr du sens de "To be seen" (peut-être "en fait" dans ce cas là ça donnerait "La majorité des maps qui utilisent des streams sont en fait plus susceptibles d'utiliser des streams compressés.") dans la traduction originale mais je pense qu'on a pas trop besoin de s'en soucier et je pense que ça ne change quasiment rien au sens de la phrase en l'ôtant. Désolé pour le commentaire un peu chargé xD
```suggestion
La majorité des maps qui utilisent des streams sont plus susceptibles d'utiliser des streams compressés.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +On parle de **streams discontinu** lorsqu'il y a un *jump* dans le stream, même si le temps entre les notes du jump est de la même longueur que le temps entre les notes du reste du steam.
```suggestion
On parle de **streams discontinus** lorsqu'il y a un *jump* dans le stream, même si le temps entre les notes du jump est de la même longueur que le temps entre les notes du reste du stream.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Le travail d'un deathstream est de faire échouer pratiquement les joueurs qui ne peuvent pas gérer les streams ordinaires.
```suggestion
Le but d'un deathstream est de pratiquement faire échouer les joueurs qui ne peuvent pas gérer les streams ordinaires.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Au lieu d'utiliser un stream orthodoxe, vous le remplacez par des sliders.
```suggestion
Au lieu d'utiliser un stream ordinaire, vous le remplacez par des sliders.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Un **triplet streams** utilise un ensemble de trois cercles qui doivent être frappés en succession rapide.
Pareil que pour les "step-too-fars"
```suggestion
Les **triplet streams** utilisent un ensemble de trois cercles qui doivent être frappés en succession rapide.
```

2021-06-13 12:56 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Ils peuvent l'être en une seule succession ou en plusieurs, selon ce que souhaite le mappeur.
```suggestion
Ils peuvent être en une seule succession ou en plusieurs, selon ce que souhaite le mappeur.
```

2021-06-13 13:29 UTC, DoryanR commented on wiki/Mapping_Techniques/Rhythm/en.md
>  They can some in a single succession or multiple depending on what the mapper wishes.
```suggestion
They can come in a single succession or multiple depending on what the mapper wishes.
```

2021-06-13 13:30 UTC, DoryanR commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Vous pouvez toutefois utiliser 3, 5 ou 6 rayons à la place (dans ce cas, veillez à ce que la mesure du degré reste égale pour chaque rayon).
```suggestion
Vous pouvez toutefois utiliser 3, 5 ou 6 rayons à la place (dans ce cas, veillez à ce que la mesure en degré reste égale pour chaque rayon).
```

2021-06-13 19:10 UTC, Satsukel requested changes

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Vous pouvez toutefois utiliser 3, 5 ou 6 rayons à la place (dans ce cas, veillez à ce que la mesure en degré reste égale pour chaque rayon).
Du coup est-ce qu'on dis spoke au lieu de rayon ? xD

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +### Aller-retour linéaires
```suggestion
### Linear Back and Forth
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +L'**aller-retour linéaire** est une variation des [battements aller-retour](#battements-aller-retour).
```suggestion
Le **linear back and forth** est une variation des [back and forth beats](#back-and-forth-beats ).
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +### Ralentissements des sliders
```suggestion
### Slider Slowdowns
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Les **ralentissements de sliders** ralentissent brusquement un slider en divisant temporairement par deux un point de timing hérité (les verts) pour compléter la note longue de la musique (ou de la v
```suggestion
Les **slider slowdowns** ralentissent brusquement un slider en divisant temporairement par deux un point de timing hérité (les verts) pour compléter la note longue de la musique (ou de la voix).
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +### Streams compressés
```suggestion
### Compressed Streams
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Les **streams compressés** utilisent des cercles qui ne sont séparés que par 3 espaces de grille (sur un niveau à 2 ou 3 grilles).
```suggestion
Les **compressed streams** utilisent des cercles qui ne sont séparés que par 3 espaces de grille (sur un niveau à 2 ou 3 grilles).
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +### Streams discontinus
```suggestion
### Discontinuous Streams
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +On parle de **streams discontinus** lorsqu'il y a un *jump* dans le stream, même si le temps entre les notes du jump est de la même longueur que le temps entre les notes du reste du stream.
```suggestion
On parle de **discontinuous streams** lorsqu'il y a un *jump* dans le stream, même si le temps entre les notes du jump est de la même longueur que le temps entre les notes du reste du stream.
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +### Streams à espacement variable
```suggestion
### Variable Spaced Streams
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Les **streams à espacement variable** utilisent des streams plus longs dont l'espacement est irrégulier (généralement croissant).
```suggestion
Les **variable spaced streams** utilisent des streams plus longs dont l'espacement est irrégulier (généralement croissant).
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +### Streams en zig-zag
```suggestion
### Zig-Zag Streams
```

2021-06-13 19:10 UTC, Satsukel commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Les **streams en zig-zag** sont des streams dont les objets sont placés de telle manière qu'ils forment une ligne très dentelée.
```suggestion
Les **zig-zag streams** sont des streams dont les objets sont placés de telle manière qu'ils forment une ligne très dentelée.
```

2021-06-13 19:13 UTC, DoryanR commented on wiki/Mapping_Techniques/Rhythm/fr.md
> +Vous pouvez toutefois utiliser 3, 5 ou 6 rayons à la place (dans ce cas, veillez à ce que la mesure en degré reste égale pour chaque rayon).
On peut laisser comme ça je pense

2021-06-13 19:17 UTC, DoryanR commented on wiki/Mapping_Techniques/Sliders/fr.md
> +## Élégant
```suggestion
## Esthétique
```

2021-06-14 06:39 UTC, DoryanR commented on wiki/Mapping_Techniques/Sliders/fr.md
> +### Cutting Sliders
```suggestion
### Crumpled sliders
```

2021-06-14 06:39 UTC, DoryanR commented on wiki/Mapping_Techniques/Sliders/fr.md
> +Les **Crumpled sliders** utilisent un slider avec de nombreux points de contrôle pour compresser le slider afin de créer une sorte d'effet froissé ou écrasé.
```suggestion
Les **crumpled sliders** utilisent un slider avec de nombreux points de contrôle pour compresser le slider afin de créer une sorte d'effet froissé ou écrasé.
```

2021-06-14 06:39 UTC, DoryanR commented on wiki/Mapping_Techniques/Sliders/fr.md
> +Les **Krisom-Krosses** se composent de deux [wave sliders.](#wave-sliders).
```suggestion
Les **krisom-krosses** se composent de deux [wave sliders](#wave-sliders).
```

2021-06-14 06:39 UTC, DoryanR commented on wiki/Mapping_Techniques/Sliders/fr.md
> +Un **Tick-Hitsounds** consiste en des slider ticks qui ont été remplacés par un son de hit standard (clap, whistle, finish - généralement superposé avec hit-normal/soft pour un son précis).
```suggestion
Un **tick-hitsounds** consiste en des slider ticks qui ont été remplacés par un son de hit standard (clap, whistle, finish - généralement superposé avec hit-normal/soft pour un son précis).
```

2021-06-15 20:49 UTC, Satsukel requested changes

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +La **note pré-spinner** est constituée d'un objet qui est placé directement avant un spinner.
```suggestion
La **pre-spinner note** est constituée d'un objet qui est placé juste avant un spinner.
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +Il s'agit de placer deux spinners dos à dos, généralement pour produire un hitsound pour le spinner suivante sans utiliser de cercle ou de [note pré-spinner](#note-pré-spinner).
ça me semblait mieux d'écrire ça plutôt que la traduction littérale de ce qui semble être une expression x)
```suggestion
Il s'agit de placer deux spinners l'un juste après l'autre, généralement pour produire un hitsound pour le spinner suivant sans utiliser de cercle ou de [pre-spinner note](#pre-spinner-note).
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +### Note post-spinner
```suggestion
### Post-Spinner Note
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +La **note post-spinner** est constituée d'un objet après un long spinner.
```suggestion
La **post-spinner note** est constituée d'un objet après un long spinner.
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +### Note pré-spinner
```suggestion
### Pre-Spinner Note
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +### Doubles spinner
```suggestion
### Double Spinners
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +### Spinner de fin
```suggestion
### End Spinner
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +Le **spinner de fin** est assez explicite.
```suggestion
Le **end spinner** est assez explicite.
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +### Spinners courts
```suggestion
### Short Spinners
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Spinners/fr.md
> +*À ne pas confondre avec un [Spinner Ninja](/wiki/Mapping_Techniques/Unrankable#ninja-spinners).*
```suggestion
*À ne pas confondre avec un [Ninja Spinner](/wiki/Mapping_Techniques/Unrankable#ninja-spinners).*
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Unrankable/fr.md
> +# Techniques de mapping sur l'Unranked
```suggestion
# Techniques de mapping inclassable
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Unrankable/fr.md
> +Un **Burai sliders** est un slider qui se chevauchent complètement sans laisser de place pour remarquer qu'ils se sont effectivement chevauchés, à l'exception de l'extrémité du slider.
```suggestion
Un **Burai sliders** est un slider qui se chevauche complètement sans laisser de place pour remarquer qu'il s'est effectivement chevauché, à l'exception de l'extrémité du slider.
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Unrankable/fr.md
> +*À ne pas confondre avec les [sliders courts et répétitifs](/wiki/Mapping_Techniques/Sliders#sliders-courts-et-répétitifs).*
```suggestion
*À ne pas confondre avec les [short repeating sliders](/wiki/Mapping_Techniques/Sliders#short-repeating-sliders).*
```

2021-06-15 20:49 UTC, Satsukel commented on wiki/Mapping_Techniques/Unrankable/fr.md
> +*À ne pas confondre avec les [spinners courts](/wiki/Mapping_Techniques/Spinners#spinners-courts).*
```suggestion
*À ne pas confondre avec les [short spinners](/wiki/Mapping_Techniques/Spinners#short-spinners).*
```

2021-06-16 05:29 UTC, Satsukel approved these changes

2021-06-17 07:29 UTC, geshii approved these changes
Good for me

2021-06-21 15:00 UTC, geshii submitted a review, later dismissed
I don't see anything else to change

2021-06-22 18:35 UTC, Satsukel approved these changes

2021-06-25 20:28 UTC, DoryanR commented
Can be merge

2021-06-25 20:56 UTC, TicClick requested changes
while I am okay with the changes (and the translation has also been checked -- thank you), please make slightly more detailed TODO comments before the merge: what exactly needs to be rewritten? what's missing, what could be improved?

2021-06-26 07:08 UTC, DoryanR commented on wiki/Mapping_Techniques/Rhythm/en.md
> +<!-- TODO: need to be rewrite, the article being very old -->
```suggestion
<!-- TODO: Needs to be rewritten, the article does not match with other articles (writing style, formatting).
Also check if the article matches with ASC. See #5729 for more informations -->
```

2021-06-26 07:08 UTC, DoryanR commented on wiki/Mapping_Techniques/Sliders/en.md
> +<!-- TODO: need to be rewrite, the article being very old -->
```suggestion
<!-- TODO: Needs to be rewritten, the article does not match with other articles (writing style, formatting).
Also check if the article matches with ASC. See #5729 for more informations -->
```

2021-06-26 07:08 UTC, DoryanR commented on wiki/Mapping_Techniques/Spinners/en.md
> +<!-- TODO: need to be rewrite, the article being very old -->
```suggestion
<!-- TODO: Needs to be rewritten, the article does not match with other articles (writing style, formatting).
Also check if the article matches with ASC. See #5729 for more informations -->
```

2021-06-26 07:08 UTC, DoryanR commented on wiki/Mapping_Techniques/Unrankable/en.md
> +<!-- TODO: need to be rewrite, the article being very old -->
```suggestion
<!-- TODO: Needs to be rewritten, the article does not match with other articles (writing style, formatting).
Also check if the article matches with ASC. See #5729 for more informations -->
```

2021-07-17 15:25 UTC, DoryanR commented
@TicClick If everything is good for you I think we can merge

2021-07-17 16:06 UTC, TicClick approved these changes
thanks, overlooked this. if I don't respond for a relatively long period of time (days), don't hesitate to ask me on Discord

2021-07-17 16:06 UTC, merged