[FR] osu!mapping
ppy/osu-wiki pull request #5698
Opened 2021-06-09 12:08 UTC by hugomah

French translation of osu! wiki - osu!mapping page

2021-06-09 14:38 UTC, DoryanR requested changes

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +---
Avant la ligne 10, ajoute ceci : 


`- tutoriel`
`- vidéos`

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +*A ne pas être confondue avec [Beatmapping](/wiki/Beatmapping).*
```suggestion
*A ne pas confondre avec [Beatmapping](/wiki/Beatmapping).*
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +**osu!mapping** est une série de vidéo hebdomadaire creé par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** a propos de l'écosystème du [mapping](/wiki/Beatmapping) et
```suggestion
**osu!mapping** est une série de vidéo hebdomadaire créé par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** a propos de l'écosystème du [mapping](/wiki/Beatmapping) et du [modding](/wiki/Modding). Ces vidéos peuvent être retrouvées sur [la chaîne youtube de pishifat](https://www.youtube.com/user/Pishifat). La grande majorité des gens connais ces vidéos sous le nom de "pishifat videos" ou "pishi videos".
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +La série est devenue tellement bien réputée dans la communauté osu! que c'est une ressource qui est généralement recommandé au nouveaux mappers.[L'équipe d'osu!](/wiki/People/The_Team) a récompensé p
```suggestion
La série est devenue tellement réputée dans la communauté osu! que c'est une ressource qui est généralement recommandé aux nouveaux mappeurs. [L'équipe d'osu!](/wiki/People/The_Team) à récompensé pishifat du badge [community contributors](/wiki/People/Community_Contributors) pour sa "performance exemplaire dans la construction et l'éducation autour du domaine du mapping" et pour remercier tout ses efforts investi dans ce projet.
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +La suite de vidéo hebdomadaire osu!mapping s'arrêta en Janvier 2019, mais il y a toujours des vidéos prévus qui compte être ajoutés dans la série.
```suggestion
La suite des vidéos hebdomadaire de l'osu!mapping s'arrêta en janvier 2019, mais il y a toujours des vidéos prévus qui compte être ajoutés dans la série.
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +- **[chaîne youtubel](https://www.youtube.com/user/Pishifat)**
```suggestion
- **[Chaîne YouTube](https://www.youtube.com/user/Pishifat)**
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +- [Patreon](https://www.patreon.com/pishifat) (currently closed)
```suggestion
- [Patreon](https://www.patreon.com/pishifat) (actuellement fermé)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +## Histoires
```suggestion
## Histoire
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +osu!mapping a débuté comme une réponse a un [post reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) demandant au mappers de créer des vidéos commentés sur le
```suggestion
l'osu!mapping a débuté comme une réponse a un [post reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) demandant au mappeurs de créer des vidéos commentés sur le mapping. Le 31 juillet 2016, pishifat posta sa première vidéo : [osu!mapping: concepts](https://www.youtube.com/watch?v=oL3az8FhlB4). Dans la vidéo, il explique comment il va faire ces vidéos comme cela à été demander sur reddit, mais il finit par décider de faire autrement car un commentaire direct de mapping serait indigeste et n'expliquerait donc pas bien aux nouveaux mappeurs l'immense variété des concept de mapping. A la place, il a choisi de commencer une série de vidéos ou chaque épisode se concentrerais sur un concept spécifique, expliquant son utilisation et importance dans sa globalité sans laisser de floues.
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +La série c'est concentré  au debut sur le coté tutoriel, mais a commendé a se diversifier après quelques mois pour inclure des discussions a propos de l'état du mapping et du modding, commentaires pe
```suggestion
La série s'est concentré  au début sur le coté tutoriel, mais a commencé a se diversifier après quelques mois pour inclure des discussions a propos de l'état du mapping et du modding, des commentaires personnels et des opinions, et des interviews. Il y a a aussi eu des projets de recherches présentés sous la forme de vidéos d'osu!mapping, notamment [une étude des influences des mappeurs](https://www.youtube.com/watch?v=TigwDc5iOcw).
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +
A partir d'ici, vaut mieux garder le titre originel des vidéos. Je suis sympa je vais te faire les suggestions qu'il faut pour corriger cela, comme c'est la première fois que tu contribue. Mais la prochaine fois, je dirait de garder les titres comme ça en anglais.

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +1. [notions](https://www.youtube.com/watch?v=oL3az8FhlB4)
```suggestion
1. [concepts](https://www.youtube.com/watch?v=oL3az8FhlB4)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +2. [accentuation des espacements](https://www.youtube.com/watch?v=rAYm50d6XMw)
```suggestion
2. [spacing emphasis](https://www.youtube.com/watch?v=rAYm50d6XMw)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +3. [espacement de base](https://www.youtube.com/watch?v=v1_HRo-lWWI)
```suggestion
3. [basic spacing](https://www.youtube.com/watch?v=v1_HRo-lWWI)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +4. [rythme de base](https://www.youtube.com/watch?v=3BC_I2ufqC8)
```suggestion
4. [basic rhythm](https://www.youtube.com/watch?v=3BC_I2ufqC8)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +5. [rythme irrégulier](https://www.youtube.com/watch?v=c7jYwSVjiSo)
```suggestion
5. [irregular rhythm](https://www.youtube.com/watch?v=c7jYwSVjiSo)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +6. [l'éditeur](https://www.youtube.com/watch?v=2k8s0gBg9yU)
```suggestion
6. [the editor](https://www.youtube.com/watch?v=2k8s0gBg9yU)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +7. [esthétique](https://www.youtube.com/watch?v=FCB5rLXqWKY)
```suggestion
7. [aesthetics](https://www.youtube.com/watch?v=FCB5rLXqWKY)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +12. [trucs](https://www.youtube.com/watch?v=nk8h1HVb8_A)
```suggestion
12. [gimmicks](https://www.youtube.com/watch?v=nk8h1HVb8_A)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +15. [amusant vs. bien](https://www.youtube.com/watch?v=C4v1QVJozGs)
```suggestion
15. [fun vs. good](https://www.youtube.com/watch?v=C4v1QVJozGs)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +25. [critique de base](https://www.youtube.com/watch?v=lh19LmL7Nvw)
```suggestion
25. [core criticism](https://www.youtube.com/watch?v=lh19LmL7Nvw)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +27. [sondage: meilleure de 2016](https://www.youtube.com/watch?v=jdpTmlvW6ow)
```suggestion
27. [best of 2016 poll](https://www.youtube.com/watch?v=jdpTmlvW6ow)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +28. [perspectives](https://www.youtube.com/watch?v=ZXakpTkXEC0)
```suggestion
28. [perspectives](https://www.youtube.com/watch?v=ZXakpTkXEC0)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +29. [plaintes](https://www.youtube.com/watch?v=5amKzp3IQRU)
```suggestion
29. [complaints](https://www.youtube.com/watch?v=5amKzp3IQRU)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +31. [mots a la mode](https://www.youtube.com/watch?v=bdaZ22it5Tw)
```suggestion
31. [buzzwords](https://www.youtube.com/watch?v=bdaZ22it5Tw)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +33. [critères de classement standard](https://www.youtube.com/watch?v=QEJBY3uwBTg)
```suggestion
33. [standard ranking criteria](https://www.youtube.com/watch?v=QEJBY3uwBTg)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +41. [efficacité de l'éditeur](https://www.youtube.com/watch?v=VD0HwSErWjw)
```suggestion
41. [editor efficiency](https://www.youtube.com/watch?v=VD0HwSErWjw)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +45. [lignes vertes](https://www.youtube.com/watch?v=J4OKPHZzJ1k)
```suggestion
45. [green lines](https://www.youtube.com/watch?v=J4OKPHZzJ1k)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +46. [collaborations](https://www.youtube.com/watch?v=Ly0u6n2qrOE)
```suggestion
46. [collabs](https://www.youtube.com/watch?v=Ly0u6n2qrOE)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +47. [décisions des nouveaux mappers](https://www.youtube.com/watch?v=7WSjFFyzGAk)
```suggestion
47. [new mapper decisions](https://www.youtube.com/watch?v=7WSjFFyzGAk)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +48. [réputation](https://www.youtube.com/watch?v=y3kkmH8UQRI)
```suggestion
48. [reputation](https://www.youtube.com/watch?v=y3kkmH8UQRI)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +52. [flux de maps](https://www.youtube.com/watch?v=l_0BC5kmXeI)
```suggestion
52. [workflow](https://www.youtube.com/watch?v=l_0BC5kmXeI)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +53. [une année](https://www.youtube.com/watch?v=c0bPx5L1vO0)
```suggestion
53. [one year](https://www.youtube.com/watch?v=c0bPx5L1vO0)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +54. [ancien éditeurs](https://www.youtube.com/watch?v=glvvgl21txc)
```suggestion
54. [old editors](https://www.youtube.com/watch?v=glvvgl21txc)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +60. [nostalgie](https://www.youtube.com/watch?v=hjcoIQhX_KI)
```suggestion
60. [nostalgia](https://www.youtube.com/watch?v=hjcoIQhX_KI)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +62. [copier d'autres mappers](https://www.youtube.com/watch?v=YjocANVGp2I)
```suggestion
62. [copying other mappers](https://www.youtube.com/watch?v=YjocANVGp2I)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +65. ["loved" -- a year later](https://www.youtube.com/watch?v=xMcW8VjkXvQ)
```suggestion
65. [loved -- a year later](https://www.youtube.com/watch?v=xMcW8VjkXvQ)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +67. [processus de ranking](https://www.youtube.com/watch?v=9Bp2e2upFcQ)
```suggestion
67. [ranking process](https://www.youtube.com/watch?v=9Bp2e2upFcQ)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +69. [imperfections de l'éditeur](https://www.youtube.com/watch?v=Q30GusNb28w)
```suggestion
69. [editor imperfections](https://www.youtube.com/watch?v=Q30GusNb28w)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +73. [variations sur lazer](https://www.youtube.com/watch?v=9S1N_F1bmEg)
```suggestion
73. [lazer variations](https://www.youtube.com/watch?v=9S1N_F1bmEg)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +76. [raisons derriere la musique](https://www.youtube.com/watch?v=EO9yWFSSL3Q)
```suggestion
76. [reasons behind music](https://www.youtube.com/watch?v=EO9yWFSSL3Q)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +81. [deaf](https://www.youtube.com/watch?v=58R7mGGWCkA)
```suggestion
81. [without audio](https://www.youtube.com/watch?v=58R7mGGWCkA)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +82. [conseils d'éditeur](https://www.youtube.com/watch?v=npkllaA0A_U)
```suggestion
82. [editor tips](https://www.youtube.com/watch?v=npkllaA0A_U)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +83. [hw & creativity](https://www.youtube.com/watch?v=8JLJ9zBAQms)
```suggestion
83. [hollow wings & creative maps](https://www.youtube.com/watch?v=8JLJ9zBAQms)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +87. [première map ranked](https://www.youtube.com/watch?v=El0PXv2em8A)
```suggestion
87. [first ranked map](https://www.youtube.com/watch?v=El0PXv2em8A)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +90. [discussions sur le modding](https://www.youtube.com/watch?v=0dwvDlU9SWQ)
```suggestion
90. [modding discussions](https://www.youtube.com/watch?v=0dwvDlU9SWQ)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +94. [en 5 minutes](https://www.youtube.com/watch?v=VZLlmaxUXto)
```suggestion
94. [in 5 minutes](https://www.youtube.com/watch?v=VZLlmaxUXto)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +95. [nouveautés mineur de l'éditeur](https://www.youtube.com/watch?v=TL-kIc_zNs0)
```suggestion
95. [minor editor update -- may 2018](https://www.youtube.com/watch?v=TL-kIc_zNs0)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +96. [RLC & following music](https://www.youtube.com/watch?v=8yh4btib9AQ)
```suggestion
96. [RLC & "following music"](https://www.youtube.com/watch?v=8yh4btib9AQ)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +101. [nouveaux mappers](https://www.youtube.com/watch?v=UjHVyBJudgg)
```suggestion
101. [new mappers](https://www.youtube.com/watch?v=UjHVyBJudgg)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +102. [accélérer le bpm](https://www.youtube.com/watch?v=BrO3GPy9mcY)
```suggestion
102. [accelerating bpm](https://www.youtube.com/watch?v=BrO3GPy9mcY)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +104. [2 ans](https://www.youtube.com/watch?v=UIPp9hZ0TuM)
```suggestion
104. [two years](https://www.youtube.com/watch?v=UIPp9hZ0TuM)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +107. [attentes](https://www.youtube.com/watch?v=qUpdmKDo7BQ)
```suggestion
107. [expectations](https://www.youtube.com/watch?v=qUpdmKDo7BQ)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +110. [ds origins](https://www.youtube.com/watch?v=JdAlJdAqeuo)
```suggestion
110. [DS origins](https://www.youtube.com/watch?v=JdAlJdAqeuo)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +114. [2 ans de "loved"](https://www.youtube.com/watch?v=oNnDSdoTI2Y)
```suggestion
114. [year 2 of "loved"](https://www.youtube.com/watch?v=oNnDSdoTI2Y)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +120. [ProfessionalBox & maps injouables](https://www.youtube.com/watch?v=pG0omZfzfpg)
```suggestion
120. [ProfessionalBox & "unplayable" maps](https://www.youtube.com/watch?v=pG0omZfzfpg)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +121. [évoluer des petite difficultés](https://www.youtube.com/watch?v=FAv5BsI3qLk)
```suggestion
121. [evolving low difficulties](https://www.youtube.com/watch?v=FAv5BsI3qLk)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +122. [apprendre taiko](https://www.youtube.com/watch?v=kM0bUdpptsY)
```suggestion
122. [learning taiko](https://www.youtube.com/watch?v=kM0bUdpptsY)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +123. [the BAT/QAT split](https://www.youtube.com/watch?v=zgKo04_xklY)
```suggestion
123. [BAT/QAT split](https://www.youtube.com/watch?v=zgKo04_xklY)
```

2021-06-09 14:38 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +124. [quelques pensées sur les mods](https://www.youtube.com/watch?v=58mUWF8U8HU)
```suggestion
124. [some thoughts on mods](https://www.youtube.com/watch?v=58mUWF8U8HU)
```

2021-06-09 15:10 UTC, hugomah reviewed
thanks DoryanR (1)

2021-06-09 15:16 UTC, hugomah reviewed
fixed

2021-06-09 15:22 UTC, hugomah commented on wiki/osu!mapping/fr.md
> +
ok

2021-06-09 15:23 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +---
J'aurais du préciser de les ajouter, **sans retirer ceux déjà présent.**

2021-06-09 15:50 UTC, hugomah reviewed
really fixed this time i hope

2021-06-09 15:50 UTC, hugomah commented on wiki/osu!mapping/fr.md
> +---
désolé, c'était pourtant plus intelligent

2021-06-09 15:50 UTC, hugomah commented on wiki/osu!mapping/fr.md
> +---
y'a un bouton commit all changes proposed ou je vais edit direct au lieu de commit changes a chaque request

2021-06-09 20:52 UTC, Ganondorf-1 requested changes

2021-06-09 20:52 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +l'osu!mapping a débuté comme une réponse a un [post reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) demandant au mappeurs de créer des vidéos commentés sur
```suggestion
L'osu!mapping a débuté en tant que réponse à un [post reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) demandant aux mappeurs de créer des vidéos commentées sur le mapping. Le 31 juillet 2016, pishifat posta sa première vidéo : [osu!mapping: concepts](https://www.youtube.com/watch?v=oL3az8FhlB4). Dans la vidéo, il explique comment il allait créer ces vidéos comme cela à été demandé sur Reddit, mais il finit par décider de faire autrement car un commentaire direct de mapping serait indigeste et n'expliquerait donc pas bien aux nouveaux mappeurs l'immense variété des concepts de mapping. À la place, il a choisi de commencer une série de vidéos dans laquelle chaque épisode se concentrerait sur un concept spécifique, expliquant son utilisation et son importance dans sa globalité sans laisser de flou.
```

2021-06-09 20:52 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +*A ne pas confondre avec [Beatmapping](/wiki/Beatmapping).*
```suggestion
*À ne pas confondre avec [Beatmapping](/wiki/Beatmapping).*
```

2021-06-09 20:52 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +**osu!mapping** est une série de vidéo hebdomadaire créé par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** a propos de l'écosystème du [mapping](/wiki/Beatmapping) et
```suggestion
**osu!mapping** est une série de vidéos hebdomadaires créée par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** a propos de l'écosystème du [mapping](/wiki/Beatmapping) et du [modding](/wiki/Modding). Ces vidéos peuvent être retrouvées sur [la chaîne youtube de pishifat](https://www.youtube.com/user/Pishifat). La grande majorité des gens connais ces vidéos sous le nom de "pishifat videos" ou "pishi videos".
```

2021-06-09 20:52 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +La série est devenue tellement réputée dans la communauté osu! que c'est une ressource qui est généralement recommandé aux nouveaux mappeurs. [L'équipe d'osu!](/wiki/People/The_Team) à récompensé pis
```suggestion
La série est devenue si réputée dans la communauté d'osu! qu'elle est devenue une ressource généralement recommandée aux nouveaux mappeurs. [L'équipe d'osu!](/wiki/People/The_Team) a récompensé pishifat du badge [community contributors](/wiki/People/Community_Contributors) pour sa "performance exemplaire dans la construction et l'éducation autour du domaine du mapping" en remerciement de ses efforts investis dans ce projet.
```

2021-06-09 20:52 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +La suite des vidéos hebdomadaire de l'osu!mapping s'arrêta en janvier 2019, mais il y a toujours des vidéos prévus qui compte être ajoutés dans la série.
```suggestion
La série de vidéos hebdomadaires de l'osu!mapping s'arrêta en janvier 2019, mais il est toujours prévu d'ajouter de nouvelles vidéos dans le futur.
```

2021-06-09 20:52 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +La série s'est concentré  au début sur le coté tutoriel, mais a commencé a se diversifier après quelques mois pour inclure des discussions a propos de l'état du mapping et du modding, des commentaire
```suggestion
La série s'est concentrée au début sur le côté tutoriel, mais a commencé à se diversifier après quelques mois pour inclure des discussions à propos de l'état du mapping et du modding, des commentaires personnels et des opinions, et des interviews. Il y a aussi eu des projets de recherche présentés sous la forme de vidéos d'osu!mapping, notamment [une étude sur l'influence des mappeurs](https://www.youtube.com/watch?v=TigwDc5iOcw).
```

2021-06-11 16:28 UTC, DoryanR requested changes

2021-06-11 16:28 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +*À ne pas confondre avec [Beatmapping](/wiki/Beatmapping).*
```suggestion
*À ne pas confondre avec : [Beatmapping](/wiki/Beatmapping).*
```

2021-06-11 16:28 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +**osu!mapping** est une série de vidéos hebdomadaires créée par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** a propos de l'écosystème du [mapping](/wiki/Beatmapping)
```suggestion
l'**osu!mapping** est une série de vidéos hebdomadaires créée par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** a propos de l'écosystème du [mapping](/wiki/Beatmapping) et du [modding](/wiki/Modding). Ces vidéos peuvent être retrouvées sur [la chaîne YouTube de pishifat](https://www.youtube.com/user/Pishifat). La grande majorité des gens connais ces vidéos sous le nom de "pishifat videos" ou "pishi videos".
```

2021-06-11 16:28 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +La série est devenue si réputée dans la communauté d'osu! qu'elle est devenue une ressource généralement recommandée aux nouveaux mappeurs. [L'équipe d'osu!](/wiki/People/The_Team) a récompensé pishi
```suggestion
La série est devenue si réputée dans la communauté d'osu! qu'elle est devenue une ressource généralement recommandée aux nouveaux mappeurs. [L'équipe d'osu!](/wiki/People/The_Team) a récompensé pishifat du badge [Community Contributors](/wiki/People/Community_Contributors) pour sa "performance exemplaire dans la construction et l'éducation autour du domaine du mapping" en remerciement de ses efforts investis dans ce projet.
```

2021-06-11 16:28 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +124. [quelques pensées sur les mods](https://www.youtube.com/watch?v=58mUWF8U8HU)
Tu n'a pas appliquer cette modification

2021-06-14 06:35 UTC, DoryanR requested changes

2021-06-14 06:35 UTC, DoryanR commented on wiki/osu!mapping/fr.md
> +La série s'est concentrée au début sur le côté tutoriel, mais a commencé à se diversifier après quelques mois pour inclure des discussions à propos de l'état du mapping et du modding, des commentaire
```suggestion

La série s'est concentrée au début sur le côté tutoriel, mais a commencé à se diversifier après quelques mois pour inclure des discussions à propos de l'état du mapping et du modding, des commentaires personnels et des opinions, et des interviews. Il y a aussi eu des projets de recherche présentés sous la forme de vidéos d'osu!mapping, notamment [une étude sur l'influence des mappeurs](https://www.youtube.com/watch?v=TigwDc5iOcw).
```

2021-06-18 17:22 UTC, DoryanR commented
@hugomah Need you to apply the proposed changes

2021-06-22 09:21 UTC, geshii commented
> 
> 
> @hugomah Need you to apply the proposed changes

He needs to rebase too

2021-07-03 15:38 UTC, TPGPL commented on wiki/osu!mapping/fr.md
> +<!-- TODO: this is not really concrete history -->
```suggestion
```

2021-07-03 15:51 UTC, TPGPL commented
@DoryanR applied the review posts, is there anything left to do with this PR?

2021-07-04 20:26 UTC, Ganondorf-1 requested changes
This review should be the last one

2021-07-04 20:26 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +l'**osu!mapping** est une série de vidéos hebdomadaires créée par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** a propos de l'écosystème du [mapping](/wiki/Beatmappin
```suggestion
l'**osu!mapping** est une série de vidéos hebdomadaires créée par ![](/wiki/shared/flag/US.gif) **[pishifat](https://osu.ppy.sh/users/3178418)** à propos de l'écosystème du [mapping](/wiki/Beatmapping) et du [modding](/wiki/Modding). Ces vidéos peuvent être retrouvées sur [la chaîne YouTube de pishifat](https://www.youtube.com/user/Pishifat). La grande majorité de la communauté connaît ces vidéos sous le nom de "pishifat videos" ou "pishi videos".
```

2021-07-04 20:26 UTC, Ganondorf-1 commented on wiki/osu!mapping/fr.md
> +L'osu!mapping a débuté en tant que réponse à un [post reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) demandant aux mappeurs de créer des vidéos commentées
```suggestion
L'osu!mapping a débuté en tant que réponse à un [post reddit](https://www.reddit.com/r/osugame/comments/4upysl/request_for_mappers_of_this_sub/) demandant aux mappeurs de créer des vidéos commentées sur le mapping. Le 31 juillet 2016, pishifat posta sa première vidéo : [osu!mapping: concepts](https://www.youtube.com/watch?v=oL3az8FhlB4). Dans la vidéo, il explique comment il allait créer ces vidéos comme cela a été demandé sur Reddit, mais il finit par décider de faire autrement car un commentaire direct de mapping serait indigeste et n'expliquerait donc pas bien aux nouveaux mappeurs l'immense variété des concepts de mapping. À la place, il a choisi de commencer une série de vidéos dans laquelle chaque épisode se concentrerait sur un concept spécifique, expliquant son utilisation et son importance dans sa globalité sans laisser de flou.
```

2021-07-06 00:46 UTC, TPGPL approved these changes

2021-07-06 00:46 UTC, merged