Update projects
ppy/osu-wiki pull request #5708
Opened 2021-06-14 16:05 UTC by Rekunan

originally was just planning on adding a couple projects, but then I wanted to add everything I could remember and here we are.

might need some fact and quality checking on what I've written up.

2021-06-14 16:10 UTC, TicClick commented
@RockRoller01 was cleaning up the layout/topmost TODO -- mentioning for awareness so that you two don't clash (I suppose it's better if @Rekunan's changes are merged first)

2021-06-14 16:59 UTC, RockRoller01 commented
@TicClick the top level todo is just a generic "add more" which I didnt really do, its what this issue does. The only part of it I did was to check every project and see if it still works/is active.

The main focus of my rework was to change the overall format, as the current format is just atrocious. Merging this before my rework should be totally fine, I just need to add the ones added in this PR.

2021-06-14 17:03 UTC, RockRoller01 requested changes
Crossing them out is not the way to go style wise, also only removing 4 while they are way more inactive/"dead" ones seems kinda random. 

Normally I would now suggest some other format/procedure, but concidering that I am very soon changing the whole format of this site its not worth it.

2021-06-14 17:03 UTC, RockRoller01 commented on wiki/Projects/en.md
> +- ~~[Graveyarded Beatmap Archiving](https://osu.ppy.sh/community/forums/topics/49310)—A forum thread to request deleted graveyarded beatmaps.~~ Closed as of May 3, 2019. If you have a **very urgent**
do not cross out

2021-06-14 17:03 UTC, RockRoller01 commented on wiki/Projects/en.md
> +- ~~[osu! Community Localisation Project](https://osu.ppy.sh/community/forums/topics/104342)—The osu! localisation project, localise your language into osu!.~~ Inactive, please use the [osu-wiki Gith
same

2021-06-14 17:03 UTC, RockRoller01 commented on wiki/Projects/en.md
> +  - ~~[Website](https://bloodcat.com/)~~
same

2021-06-14 17:03 UTC, RockRoller01 commented on wiki/Projects/en.md
> +  - ~~[GitHub](https://github.com/arogan-group/irc4osu)~~
same

2021-06-15 19:35 UTC, TPGPL requested changes

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +- osu-pps—A website that lists the most overweight maps in terms of PP by using a calculation similar to [ppv1](/wiki/Performance_points/ppv1), and sorts mappers by how many overweight maps they have
```suggestion
- osu-pps—A website that lists the most overweight maps in terms of [pp](/wiki/Performance_points) by using a calculation system similar to [ppv1](/wiki/Performance_points/ppv1), and sorts mappers by how many overweight maps they have or how many high-quality beatmaps they have according to other mappers' favorites.
```

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +- [PerformancePlus (PP+)](https://osu.ppy.sh/community/forums/topics/580994)—An unofficial osu!Standard ranking system featuring Player Rankings, both global and national, Global Score Rankings, each
```suggestion
- [PerformancePlus (PP+)](https://osu.ppy.sh/community/forums/topics/580994)—An unofficial osu! ranking system featuring global and national player rankings, global score rankings, rankings for 8 different (sub)skill categories, detailed player profiles, leaderboards for ranked beatmaps using the pp+ system, and bimonthly seasonal rankings.
```

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +- pupper.moe—Originally a spreadsheet, now a website for an opt-in US state ranking leaderboard for osu! with some states' discord servers being listed.
```suggestion
- pupper.moe—Originally a spreadsheet, now a website for opt-in US state ranking leaderboards for osu! with some states' Discord servers being listed.
```

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +- Aiess—Provides subscriptions for mapping-related events in osu! (e.g. ranks, qualifications, nominations, suggestions, newsposts, group changes, etc).
```suggestion
- Aiess—Provides subscriptions for mapping-related events in osu! (e.g. ranks, qualifications, nominations, suggestions, news posts, group changes, etc).
```

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +- hwchr's pick'em—A site which hosts pickems for many osu! tournaments with the option to request for a tournament.
```suggestion
- hwchr's pick'em—A site which hosts pickems for osu! tournaments with the option to request a pickem for a tournament.
```

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +- osu-trainer—A program that allows you to modify the difficulty of a beatmap very quickly and easily.
```suggestion
- osu-trainer—A program that allows you to modify the difficulty settings of a beatmap easily.
```

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +- osuStuff—A website for creating anime style avatars and for playing automatic osu! Battle Royale Tournaments
```suggestion
- osuStuff—A website for creating anime-themed avatars, and playing automatic osu! Battle Royale tournaments.
```

2021-06-15 19:35 UTC, TPGPL commented on wiki/Projects/en.md
> +  - [Git](https://git.cartooncraft.fr/shARPII/script-chan/)<!-- Unsure about naming so currently left as "Git" -->
```suggestion
  - [GitLab](https://git.cartooncraft.fr/shARPII/script-chan/)
```

2021-06-16 14:19 UTC, TPGPL approved these changes
seems okay for now

2021-06-16 14:19 UTC, merged