[EN] Add `Corgi Cup: June 2016` tournament article
ppy/osu-wiki pull request #5723
Opened 2021-06-19 15:33 UTC by Bazzadwarf

Adds the full Corgi Cup: June 2016 tournament article, also fixes a minor error in the Corgi Cup VI article.

- [ ] Waiting on a quick check by doomsday.

2021-06-19 22:31 UTC, Bazzadwarf commented
This is ready for a review now!

2021-06-20 23:44 UTC, TPGPL requested changes

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +| Co-Host | ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973), ![][flag_GB] [Doomsday](https://osu.ppy.sh/users/18983) |
```suggestion
| Co-host | ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973), ![][flag_GB] [Doomsday](https://osu.ppy.sh/users/18983) |
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +  - **[SawanoHiroyuki\[nZk\]:Gemie - x.U. (ETIA. Hardcore Bootleg Remix) (captin1) [Shinoa]](https://osu.ppy.sh/beatmapsets/331872#osu/735021)**
```suggestion
  - **[SawanoHiroyuki[nZk]:Gemie - x.U. (ETIA. Hardcore Bootleg Remix) (captin1) [Shinoa]](https://osu.ppy.sh/beatmapsets/331872#osu/735021)**  
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +  - [Dark PHOENiX - Stirring an Autumn Moon (_lolipop) [Crazy Moon]](https://osu.ppy.sh/beatmapsets/16650#osu/59693)
```suggestion
  - [Dark PHOENiX - Stirring an Autumn Moon (\_lolipop) [Crazy Moon]](https://osu.ppy.sh/beatmapsets/16650#osu/59693)
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +- This tournament is a 1v1, Head to head, Single Elimination tournament.
```suggestion
- This is a 1v1, head-to-head, single-elimination tournament.
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +- Hard Rock and Double Time mappools can be played with Hidden should the player want to.
```suggestion
- Hard Rock and Double Time mappools can be played with Hidden if the player wants to.
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +- Free mod can be any mod the player decides (including EZ + FL).
```suggestion
- Free Mod can be any mod the player decides (including EZ + FL).
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +- Each player is allowed one ban per match (Not Tiebreaker).
```suggestion
- Each player is allowed one ban per match. The tiebreaker cannot be banned.
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +| Hydria ![][flag_GB] | 2 | **4** | ![][flag_GB] rafalbrew | [#1](https://osu.ppy.sh/community/matches/25740307) |
```suggestion
| Hydria ![][flag_GB] | 2 | **4** | ![][flag_GB] **rafalbrew** | [#1](https://osu.ppy.sh/community/matches/25740307) |
```

2021-06-20 23:44 UTC, TPGPL commented on wiki/Tournaments/CC/1/en.md
> +| Sopison ![][flag_GB] | 0 | **4** | ![][flag_GB] djsettle | [#1](https://osu.ppy.sh/community/matches/25711194) |
```suggestion
| Sopison ![][flag_GB] | 0 | **4** | ![][flag_GB] **djsettle** | [#1](https://osu.ppy.sh/community/matches/25711194) |
```

2021-06-20 23:50 UTC, TPGPL approved these changes

2021-06-20 23:51 UTC, merged