[FR] Add `Modding/Beatmap Nominator Tiers`, `BADASS`, `NAT meetings`, `QAT Leaders`, `Quality Assurance Team`, Timestamp`, update `Modding` and `Kudosu`
ppy/osu-wiki pull request #5724
Opened 2021-06-19 18:46 UTC by DoryanR

Translation of the following wiki pages:

- `Modding/Beatmap_Nominator_Tiers`
- `Modding/Delegation_of_the_Beatmap_Approval_Deciding_Authorities_Submission_Squad`
- `Modding/NAT_meetings`
- `Modding/QAT_Leaders`
- `Modding/Quality_Assurance_Team`
- `Modding/Timestamp`

Update of the translations of the following wiki pages:

- `Modding/Kudosu`
- `Modding`

2021-06-19 22:51 UTC, Ganondorf-1 requested changes

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Beatmap_Nominator_Tiers/fr.md
> +Les **Beatmap Nominator Tiers** étaient une manière de séparer les [Beatmaps Nominators](/wiki/People/The_Team/Beatmap_Nominators) (*BN*) en niveaux supérieurs et inférieurs, imitant la [Mapping Assi
```suggestion
Les **Beatmap Nominator Tiers** étaient une manière de séparer les [Beatmaps Nominators](/wiki/People/The_Team/Beatmap_Nominators) (*BN*) en niveaux supérieurs et inférieurs, imitant la [Mapping Assistance Team](/wiki/Modding/Mapping_Assistance_Team) et la [Beatmap Appreciation Team](/wiki/Modding/Beatmap_Appreciation_Team). Le système a été utilisé entre avril 2017 et septembre 2017.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Beatmap_Nominator_Tiers/fr.md
> +Ce système a été mis en place en réponse au changement de fonction de la [Quality Assurance Team](/wiki/Modding/Quality_Assurance_Team) (*QAT*), qui est passée de l'assurance de la qualité des beatma
```suggestion
Ce système a été mis en place en réponse au changement de fonction de la [Quality Assurance Team](/wiki/Modding/Quality_Assurance_Team) (*QAT*), qui est passée de l'assurance de la qualité des beatmaps qualifiés à la gestion générale des BN. En donnant des autorisations de qualification aux seuls membres "les plus compétents" des BN, la QAT espérait que la qualité des beatmaps classées s'améliorerait.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Beatmap_Nominator_Tiers/fr.md
> +- Le Tier 1 BN peut placer la première nomination d'une map (ou la deuxième nomination pour les beatmaps [approuvés](/wiki/Beatmap/Category#approved)).
```suggestion
- Les BN Tier 1 pouvaient placer la première nomination d'une map (ou la deuxième nomination pour les beatmaps [approuvées](/wiki/Beatmap/Category#approved)).
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Beatmap_Nominator_Tiers/fr.md
> +- Le Tier 2 BN pourrait placer la première, deuxième ou troisième nomination d'une map.
```suggestion
- Les BN Tier 2 pouvaient placer la première, deuxième ou troisième nomination d'une map.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Beatmap_Nominator_Tiers/fr.md
> +Pour décider quels Beatmap Nominators appartiendraient à chaque niveau, tous les membres  BN ont reçu un [test BN](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Nominator_Test). Contrairement aux
```suggestion
Pour décider quels Beatmap Nominators appartiendraient à chaque niveau, tous les BN ont reçu un [test BN](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Nominator_Test). Contrairement aux tests BN précédents, celui-ci a été conçu pour identifier des problèmes généraux dans un mapset.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Beatmap_Nominator_Tiers/fr.md
> +## Test des Beatmap Nominator Tier
```suggestion
## Test des Beatmap Nominator Tiers
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Beatmap_Nominator_Tiers/fr.md
> +Les paliers des Beatmap Nominator étaient le prédécesseur de la distinction des [Full Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators#full-beatmap-nominators) et des [Probationary Beatma
```suggestion
Les paliers des Beatmap Nominators étaient le prédécesseur de la distinction des [Full Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators#full-beatmap-nominators) et des [Probationary Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators#probationary-beatmap-nominators) mis en place en septembre 2017. Leurs permissions étaient presque les mêmes, cependant un utilisateur ne pouvait pas rester dans le niveau inférieur (probation) pendant plus de 2 mois. Si un utilisateur n'était pas prêt pour le BN complet après 2 mois, il était entièrement retiré du groupe des BN.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Delegation_of_the_Beatmap_Approval_Deciding_Authorities_Submission_Squad/fr.md
> +Lors de la sélection des nouveaux membres, un groupe de responsables choisissait les candidats et les autres BAT donnaient leur avis. Tout utilisateur ayant reçu l'approbation d'au moins 3 membres du
```suggestion
Lors de la sélection des nouveaux membres, un groupe de responsables choisissait les candidats et les autres BAT donnaient leur avis. Tout utilisateur ayant reçu l'approbation d'au moins 3 membres de la BAT et du responsable des BAT, sans que personne ne le désapprouve, serait promu dans l'équipe.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/NAT_meetings/fr.md
> +Les **réunions de la NAT** sont des discussions organisées par la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (*NAT*) dans le canal `#modding` du [serveur Discord o
```suggestion
Les **réunions de la NAT** sont des discussions organisées par la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (*NAT*) dans le canal `#modding` du [serveur Discord osu!dev](/wiki/osu!dev_Discord_server). Les sujets de réunion concernent l'écosystème du [mapping](/wiki/Beatmapping) et du [modding](/wiki/Modding), y compris les problèmes, les solutions potentielles, les nouvelles idées et les rapports d'avancement. Bien que la plupart des contributeurs aux discussions soient des membres de la NAT ou des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators), tout le monde est autorisé à participer.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/NAT_meetings/fr.md
> +- 18/01/2020 : Évaluation de la demande - [Notes](https://docs.google.com/document/d/1Q2MdQKEcCTXS7hYoFgmm9pPW8vcz4Wc_qCphTp8Bmlw/edit?usp=sharing "Document Google : (#3) Application Evaluation"), [R
```suggestion
- 18/01/2020 : Évaluation de la candidature - [Notes](https://docs.google.com/document/d/1Q2MdQKEcCTXS7hYoFgmm9pPW8vcz4Wc_qCphTp8Bmlw/edit?usp=sharing "Document Google : (#3) Application Evaluation"), [Résumé](https://osu.ppy.sh/community/forums/topics/1012519)
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/NAT_meetings/fr.md
> +| Laisser les BN affecter l'application et/ou les évaluations actuelles des BN | Le champ d'application est trop large et une proposition écrite devrait être faite en premier lieu. |
```suggestion
| Laisser les BN affecter les candidatures et/ou les évaluations actuelles des BN | Le champ d'application est trop large et une proposition écrite devrait être faite en premier lieu. |
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/NAT_meetings/fr.md
> +| NAT leadership/turnover/démotion | Le champ d'application est trop large et une proposition écrite devrait être faite en premier lieu. |
```suggestion
| NAT leadership/turnover/demotion | Le champ d'application est trop large et une proposition écrite devrait être faite en premier lieu. |
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/QAT_Leaders/fr.md
> +Le vote pour les dirigeants de la QAT s'est fait par le biais d'un vote de tous les [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et des membres de le la QAT. Les résultats du vote,
```suggestion
Le vote pour les dirigeants de la QAT s'est fait par le biais d'un vote de tous les [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et des membres de le la QAT. Les résultats du vote, trouvés [ici](https://osu.ppy.sh/community/forums/topics/640679), ont promu [Okoratu](https://osu.ppy.sh/users/1623405) et [JBHyperion](https://osu.ppy.sh/users/4879508) comme les premiers leaders de la QAT. Leur responsabilité était de travailler avec l'équipe d'osu! pour maintenir les communautés de mapping et de modding.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/QAT_Leaders/fr.md
> +En 2020, il n'y avait plus besoin d'un poste officiel de leader de la QAT (éventuellement la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (*NAT*)). Le groupe est act
```suggestion
En 2020, il n'y avait plus besoin d'un poste officiel de leader de la QAT (qui est devenue la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (*NAT*)). Le groupe est actuellement auto-modéré.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Quality_Assurance_Team/fr.md
> +La **Quality Assurance Team (*QAT*)** était chargée de maintenir la qualité des beatmaps classés. Ses responsabilités s'étant progressivement déplacées de l'assurance qualité vers le maintien de la c
```suggestion
La **Quality Assurance Team (*QAT*)** était chargée de maintenir la qualité des beatmaps classées. Ses responsabilités s'étant progressivement déplacées de l'assurance qualité vers le maintien de la communauté de mapping, le groupe a été renommé [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (*NAT*).
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Quality_Assurance_Team/fr.md
> +Le QAT a été créé dans le cadre d'un essai manuel du [modding v2](/wiki/Beatmap_Discussion) visant à automatiser la promotion et le retrait des BAT. L'équipe examinait les beatmaps [qualifiés](/wiki/
```suggestion
La QAT a été créée dans le cadre d'un essai manuel du [modding v2](/wiki/Beatmap_Discussion) visant à automatiser la promotion et le retrait des BAT. L'équipe examinait les beatmaps [qualifiées](/wiki/Beatmap/Category#qualified) et disqualifiait celles qui ne répondaient pas aux [critères de classement](/wiki/Ranking_Criteria) ou aux normes de qualité personnelles de l'équipe.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Quality_Assurance_Team/fr.md
> +Les premiers [QAT Leaders](/wiki/Modding/QAT_Leaders) ont été créés en 2017 pour permettre la communication entre la QAT et les développeurs d'osu! après le départ de [Loctav](https://osu.ppy.sh/user
```suggestion
Les premiers [QAT Leaders](/wiki/Modding/QAT_Leaders) ont été établis en 2017 pour permettre la communication entre la QAT et les développeurs d'osu! après le départ de [Loctav](https://osu.ppy.sh/users/71366) de l'équipe.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Quality_Assurance_Team/fr.md
> +L'assurance qualité faisait toujours partie des responsabilités de l'équipe, mais elle devenait de moins en moins importante à mesure que les membres du BN assumaient la fonction principale de contrô
```suggestion
L'assurance qualité faisait toujours partie des responsabilités de l'équipe, mais elle devenait de moins en moins importante à mesure que les BN assumaient la fonction principale de contrôle de la qualité.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/Quality_Assurance_Team/fr.md
> +En 2019, il a été jugé que la QAT n'était plus en mesure d'assumer ses responsabilités initiales en matière d'assurance qualité, et le groupe a donc été rebaptisé Nomination Assessment Team.
```suggestion
En 2019, il a été jugé que la QAT n'était plus en mesure d'assumer ses responsabilités initiales en matière d'assurance qualité, et le groupe a donc été renommé en Nomination Assessment Team.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/fr.md
> +Le **modding** est l'acte de fournir des commentaires sur la [beatmap](/wiki/Beatmap) d'un autre utilisateur. Un utilisateur qui fait du modding est appelé un *modder*, et ses messages collectifs sur
```suggestion
Le **modding** est l'acte de fournir des commentaires sur la [beatmap](/wiki/Beatmap) d'un autre utilisateur. Un utilisateur qui fait du modding est appelé un *moddeur*, et ses messages collectifs sur la discussion d'une beatmap sont appelés un *mod*.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/fr.md
> +  Le créateur de chaque file d'attente en dicte les règles, contrôlant quels beatmaps sont viables pour recevoir des mods. Les files d'attente sont généralement ouvertes aux demandes de deux types de
```suggestion
  Le créateur de chaque file d'attente en dicte les règles, contrôlant quelles beatmaps sont viables pour recevoir des mods. Les files d'attente sont généralement ouvertes aux demandes de deux types de mods :
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/fr.md
> +- Il n'est **pas** recommandé d'effectuer des recherches dans la liste des beatmaps en attente pour trouver des beatmaps à modder, car la plupart des soumissions ne visent pas le statut classée, et l
```suggestion
- Il n'est **pas** recommandé d'effectuer des recherches dans la liste des beatmaps en attente pour trouver des beatmaps à modder, car la plupart des beatmaps publiées ne visent pas le statut classé, et leurs créateurs ne répondront donc potentiellement pas aux mods.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/fr.md
> +Pour modder un beatmap, commencez par télécharger la version la plus récente et ouvrez sa [page de discussion](/wiki/Beatmap_Discussion). Jouez à la [difficulté](/wiki/Beatmap/Difficulty) que vous so
```suggestion
Pour modder une beatmap, commencez par télécharger la version la plus récente et ouvrez sa [page de discussion](/wiki/Beatmap_Discussion). Jouez à la [difficulté](/wiki/Beatmap/Difficulty) que vous souhaitez modifier et gardez à l'esprit tout problème lié au gameplay. Lorsque vous avez terminé, ouvrez la difficulté dans l'éditeur et analysez-la à la recherche d'autres problèmes.
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/fr.md
> +Les mappeurs fournissent régulièrement des [kudosu](/wiki/Modding/Kudosu) aux messages des modder qu'ils considèrent comme utiles en cliquant sur le bouton de vote "like". Cette statistique est enreg
```suggestion
Les mappeurs fournissent régulièrement des [kudosu](/wiki/Modding/Kudosu) aux messages des moddeurs qu'ils considèrent comme utiles en cliquant sur le bouton de vote "like". Cette statistique est enregistrée sur le profil de l'utilisateur et est référencée lors de la demande d'adhésion aux [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators).
```

2021-06-19 22:51 UTC, Ganondorf-1 commented on wiki/Modding/fr.md
> +## Types de postes des modders
```suggestion
## Types de postes des moddeurs
```

2021-06-21 14:59 UTC, geshii requested changes

2021-06-21 14:59 UTC, geshii commented on wiki/Modding/fr.md
> +Les beatmaps qui visent la catégorie classée doivent impérativement respecter les [critères de classement](/wiki/Ranking_Criteria). Un certain nombre de messages de mods traitent des problèmes cités
```suggestion
Les beatmaps qui visant la catégorie classée doivent impérativement respecter les [critères de classement](/wiki/Ranking_Criteria). Un certain nombre de messages de mods traitent des problèmes cités directement dans ces critères.
```
C'est un changement mineur mais personnellement je trouve que ça rend mieux

2021-06-21 14:59 UTC, geshii commented on wiki/Modding/Kudosu/fr.md
> +Les **Kudosu** font partie d'un système de récompense en [modding](/wiki/Modding). Ce système permet de récompenser un joueur qui a apporté son aide sur la beatmap d'un autre joueur depuis les [discu
```suggestion
Les **Kudosu** font partie d'un système de récompense en [modding](/wiki/Modding). Ce système permet de récompenser un joueur qui a apporté son aide sur la beatmap d'un autre joueur depuis les [discussions de beatmap](/wiki/Beatmap_Discussion). Les Kudosu restants ainsi que le total des Kudosu obtenus sont visibles à partir du profil osu! d'un joueur.
```
Mettre la majuscule partout

2021-06-21 15:39 UTC, DoryanR commented on wiki/Modding/fr.md
> +Les beatmaps qui visent la catégorie classée doivent impérativement respecter les [critères de classement](/wiki/Ranking_Criteria). Un certain nombre de messages de mods traitent des problèmes cités
Bah la je trouve qu'il y a une faute d'orthographe, c'est bien comme c'est à mon avis

2021-06-21 16:01 UTC, geshii commented on wiki/Modding/fr.md
> +Les beatmaps qui visent la catégorie classée doivent impérativement respecter les [critères de classement](/wiki/Ranking_Criteria). Un certain nombre de messages de mods traitent des problèmes cités
j'ai oublié d'enlever le "qui" 😓

2021-06-21 17:46 UTC, DoryanR commented on wiki/Modding/Kudosu/fr.md
> +Dans le forum de modding, les kudosu sont échangeables contre des [étoiles de priorité](/wiki/Modding/Star_priority).
```suggestion
Dans le forum de modding, les Kudosu sont échangeables contre des [étoiles de priorité](/wiki/Modding/Star_priority).
```

2021-06-21 17:46 UTC, DoryanR commented on wiki/Modding/fr.md
> +Les beatmaps qui visent la catégorie classée doivent impérativement respecter les [critères de classement](/wiki/Ranking_Criteria). Un certain nombre de messages de mods traitent des problèmes cités
```suggestion
Les beatmaps visant la catégorie classée doivent impérativement respecter les [critères de classement](/wiki/Ranking_Criteria). Un certain nombre de messages de mods traitent des problèmes cités directement dans ces critères.
```

2021-06-22 18:33 UTC, Satsukel requested changes

2021-06-22 18:33 UTC, Satsukel commented on wiki/Modding/fr.md
> +Tous les messages de mods doivent traiter de la nature du problème, de sa raison d'être et de la manière de le résoudre. Voir le [Code de conduite pour le modding et le mapping](/wiki/Rules/Code_of_C
Je trouvais que "formater" faisait un peu trop informatique et je propose ça comme alternative au cas où
```suggestion
Tous les messages de mods doivent traiter de la nature du problème, de sa raison d'être et de la manière de le résoudre. Voir le [Code de conduite pour le modding et le mapping](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping#making-a-mod-post) pour plus de détails sur la mise en forme des messages de mod.
```

2021-06-22 18:33 UTC, Satsukel commented on wiki/Modding/fr.md
> +Proposer des méthodes alternatives de beatmapping est un autre type de post de mod courant. Si une partie d'une beatmap peut être acceptable dans sa forme actuelle, un moddeur peut expliquer comment
```suggestion
Proposer des méthodes alternatives de beatmapping est un autre type de post de mod courant. Si une partie d'une beatmap peut être acceptable dans sa forme actuelle, un moddeur peut expliquer comment l'améliorer encore en la concevant différemment.
```

2021-06-22 18:33 UTC, Satsukel commented on wiki/Modding/fr.md
> +Proposer des méthodes alternatives de beatmapping est un autre type de post de mod courant. Si une partie d'une beatmap peut être acceptable dans sa forme actuelle, un moddeur peut expliquer comment
Je propose ça comme alternative parce que la fin de la phrase me semble un peu bizarre.
```suggestion
Proposer des méthodes alternatives de beatmapping est un autre type de post de mod courant. Si une partie d'une beatmap peut être acceptable dans sa forme actuelle, un moddeur peut expliquer comment l'améliorer encore en la modifiant.
```

2021-06-23 07:33 UTC, Satsukel approved these changes

2021-06-25 20:27 UTC, DoryanR commented
Can be merge

2021-06-25 20:35 UTC, TicClick approved these changes

2021-06-25 20:35 UTC, merged