[FR] Add `Music theory/Beat`
ppy/osu-wiki pull request #5725
Opened 2021-06-19 19:25 UTC by DoryanR

Proposal for the French translation of the wiki page `Beat`.

2021-06-19 22:21 UTC, Ganondorf-1 requested changes

2021-06-19 22:21 UTC, Ganondorf-1 commented on wiki/Music_theory/Beat/fr.md
> +# Battement
```suggestion
# Beat
```

2021-06-19 22:21 UTC, Ganondorf-1 commented on wiki/Music_theory/Beat/fr.md
> +Un **battement** est une unité de temps répétitive en musique, en particulier le pouls de la musique sur lequel l'auditeur tape. Dans osu!, vous pouvez les comparer aux ticks blancs de la [timeline d
```suggestion
Un **beat** est une unité de temps répétitive en musique, en particulier le pouls de la musique sur lequel l'auditeur tape. Dans osu!, vous pouvez les comparer aux ticks blancs de la [timeline de l'éditeur](/wiki/Beatmap_Editor/Timelines) qui forment l'épine dorsale du rythme de la chanson.
```

2021-06-19 22:21 UTC, Ganondorf-1 commented on wiki/Music_theory/Beat/fr.md
> +![Capture d'écran en jeu de la timeline de l'éditeur](img/timeline.png "Tous les ticks blancs représentent un rythme dans la musique.")
```suggestion
![Capture d'écran en jeu de la timeline de l'éditeur](img/timeline.png "Chaque tick blanc représente un beat dans la musique.")
```

2021-06-20 18:33 UTC, Ganondorf-1 approved these changes

2021-06-21 14:52 UTC, geshii approved these changes

2021-06-22 17:54 UTC, Satsukel requested changes

2021-06-22 17:54 UTC, Satsukel commented on wiki/Music_theory/Beat/fr.md
> +Un **beat** est une unité de temps répétitive en musique, en particulier le pouls de la musique sur lequel l'auditeur tape. Dans osu!, vous pouvez les comparer aux ticks blancs de la [timeline de l'é
J'ai pas la version originale mais je pense que cette expression colle mieux.
```suggestion
Un **beat** est une unité de temps répétitive en musique, en particulier le pouls de la musique sur lequel l'auditeur tape. Dans osu!, vous pouvez les comparer aux ticks blancs de la [timeline de l'éditeur](/wiki/Beatmap_Editor/Timelines) qui forment la colonne vertébrale du rythme de la chanson.
```

2021-06-22 17:55 UTC, Satsukel commented on wiki/Music_theory/Beat/fr.md
> +Un **beat** est une unité de temps répétitive en musique, en particulier le pouls de la musique sur lequel l'auditeur tape. Dans osu!, vous pouvez les comparer aux ticks blancs de la [timeline de l'é
Je sais je chipote :^)

2021-06-23 07:33 UTC, Satsukel approved these changes

2021-06-24 05:35 UTC, geshii approved these changes

2021-06-25 20:27 UTC, DoryanR commented
Can be merge

2021-06-25 20:32 UTC, TicClick approved these changes

2021-06-25 20:32 UTC, merged