[FR] Update `Submission`
ppy/osu-wiki pull request #5727
Opened 2021-06-19 20:02 UTC by DoryanR

Proposal to update the French translation of the wiki page `Submission`.

2021-06-21 14:47 UTC, geshii requested changes

2021-06-21 14:47 UTC, geshii commented on wiki/Submission/fr.md
> +Les [beatmaps](/wiki/Beatmap) peuvent être envoyées sur le site web d'osu! via [l'éditeur du jeu](/wiki/Beatmap_Editor). Soumettre une beatmap lui permet de recevoir l'attention des autres utilisateu
```suggestion
Les [beatmaps](/wiki/Beatmap) peuvent être publiées sur le site web d'osu! via [l'éditeur du jeu](/wiki/Beatmap_Editor). Soumettre une beatmap lui permet de recevoir l'attention des autres utilisateurs et d'entrer potentiellement dans les catégories [Classée](/wiki/Beatmap/Category#ranked), ou [Loved](/wiki/Beatmap/Category#loved).
```

2021-06-21 14:47 UTC, geshii commented on wiki/Submission/fr.md
> +Les [beatmaps](/wiki/Beatmap) peuvent être envoyées sur le site web d'osu! via [l'éditeur du jeu](/wiki/Beatmap_Editor). Soumettre une beatmap lui permet de recevoir l'attention des autres utilisateu
> Classée  

On devrait pas plutôt mettre Ranked ? si on laisse Loved

2021-06-21 14:47 UTC, geshii commented on wiki/Submission/fr.md
> +![](img/bss_warning.png "Écran du système du Beatmap Submission System")
```suggestion
![](img/bss_warning.png "Écran du Beatmap Submission System")
```
Tu dit système deux fois :v

2021-06-21 14:47 UTC, geshii commented on wiki/Submission/fr.md
> +Si la beatmap qu'un utilisateur télécharge n'est pas déjà sur le site d'osu!, la fenêtre BSS indique combien de nouveaux téléchargements un utilisateur peut publier. Si la beatmap est nominé, la fenê
```suggestion
Si la beatmap qu'un utilisateur télécharge n'est pas déjà sur le site d'osu!, la fenêtre BSS indique combien de nouveaux téléchargements un utilisateur peut publier. Si la beatmap est nominée, la fenêtre prévient que la nomination sera réinitialisée par la mise à jour de la beatmap. Si le beatmap est dans le cimetière, la fenêtre prévient que la beatmap sera élevée à la catégorie en attente.
```

2021-06-21 14:47 UTC, geshii commented on wiki/Submission/fr.md
> +En cliquant sur le bouton `Télécharger un nouveau beatmap` ou `Mettre à jour une beatmap`, l'utilisateur aura le choix de télécharger son beatmap dans les catégories `Work in Progress/Help` ou `Pendi
```suggestion
En cliquant sur le bouton `Télécharger une nouvelle beatmap` ou `Mettre à jour une beatmap`, l'utilisateur aura le choix de télécharger sa beatmap dans les catégories `Work in Progress/Help` ou `Pending Beatmaps`. Les beatmaps WIP ne peuvent pas être nominées pour le classement, alors que les beatmaps en attente le peuvent.
```

2021-06-21 15:41 UTC, DoryanR commented on wiki/Submission/fr.md
> +Les [beatmaps](/wiki/Beatmap) peuvent être envoyées sur le site web d'osu! via [l'éditeur du jeu](/wiki/Beatmap_Editor). Soumettre une beatmap lui permet de recevoir l'attention des autres utilisateu
Non car le nom de la difficulté s'appelle bien comme ça, et que `Loved` n'est pas traduit en français

2021-06-22 17:47 UTC, Satsukel requested changes

2021-06-22 17:47 UTC, Satsukel commented on wiki/Submission/fr.md
> +Si la beatmap qu'un utilisateur télécharge n'est pas déjà sur le site d'osu!, la fenêtre BSS indique combien de nouveaux téléchargements un utilisateur peut publier. Si la beatmap est nominée, la fen
```suggestion
Si la beatmap qu'un utilisateur télécharge n'est pas déjà sur le site d'osu!, la fenêtre BSS indique combien de nouveaux téléchargements un utilisateur peut publier. Si la beatmap est nominée, la fenêtre prévient que la nomination sera réinitialisée par la mise à jour de la beatmap. Si la beatmap est dans le cimetière, la fenêtre prévient que la beatmap sera élevée à la catégorie en attente.
```

2021-06-22 17:47 UTC, Satsukel commented on wiki/Submission/fr.md
> +Les beatmaps ne seront pas soumis s'ils dépassent la taille du fichier en ligne ou la limite de difficulté. La taille limite des fichiers est de 5 Mo, plus 10 Mo supplémentaires pour chaque minute, e
```suggestion
Les beatmaps ne seront pas soumises si elles dépassent la taille du fichier en ligne ou la limite de difficulté. La taille limite des fichiers est de 5 Mo, plus 10 Mo supplémentaires pour chaque minute, et elle est plafonnée à 100 Mo. La limite de difficulté est actuellement de 128.
```

2021-06-23 07:32 UTC, Satsukel approved these changes

2021-06-25 20:27 UTC, DoryanR commented
Can be merge

2021-06-25 20:30 UTC, TicClick approved these changes

2021-06-25 20:30 UTC, merged