[FR] Update `Visual Settings`
ppy/osu-wiki pull request #5728
Opened 2021-06-19 20:13 UTC by DoryanR

Proposal to update the French translation of the wiki page `Visual Settings`.

2021-06-19 22:08 UTC, Ganondorf-1 requested changes

2021-06-19 22:08 UTC, Ganondorf-1 commented on wiki/Visual_Settings/fr.md
> +| `Ignorer les bruitages intégrés aux beatmaps  ` | Utilise les hitsounds du skin sélectionné par le joueur au lieu des hitsounds personnalisés de la beatmap, le cas échéant. | Cela nécessite une nou
```suggestion
| `Ignorer les bruitages intégrés aux beatmaps  ` | Utilise les hitsounds du skin sélectionné par le joueur au lieu des hitsounds personnalisés de la beatmap, le cas échéant. | Cela nécessite de recommencer la beatmap pour prendre effet. |
```

2021-06-19 22:08 UTC, Ganondorf-1 commented on wiki/Visual_Settings/fr.md
> +| `Désactiver la vidéo` | Ne pas lire la vidéo de fond. Cela ne supprime pas le storyboard. | Cette option nécessite une nouvelle tentative si elle est activée après le début du jeu. Cette option est
```suggestion
| `Désactiver la vidéo` | Ne pas lire la vidéo de fond. Cela ne retire pas le storyboard. | Cette option nécessite de recommencer la beatmap si elle est activée après le début de la partie. Cette option est désactivée s'il n'y a pas de vidéo de fond à jouer. |
```

2021-06-19 22:08 UTC, Ganondorf-1 commented on wiki/Visual_Settings/fr.md
> +Les **paramètres visuels** sont une superposition de personnalisation cachée située en bas du terrain de jeu. Il est possible d'y accéder lorsque la beatmaps est en cours de chargement ou lorsque le
```suggestion
Les **paramètres visuels** sont un menu de personnalisation caché situé en bas du terrain de jeu. Il est possible d'y accéder lorsque la beatmap est en cours de chargement ou lorsque le jeu est en pause. Lorsque le menu des paramètres visuels est affiché, la beatmap ne commencera pas et attendra que le curseur quitte le menu des paramètres visuels.
```

2021-06-19 22:08 UTC, Ganondorf-1 commented on wiki/Visual_Settings/fr.md
> +Il est également possible d'accéder à la superposition des paramètres visuels en mettant le jeu en pause. Toutefois, cette méthode ne fonctionne pas dans les matchs [multijoueurs](/wiki/Multi), car e
```suggestion
Il est également possible d'accéder au menu des paramètres visuels en mettant le jeu en pause. Toutefois, cette méthode ne fonctionne pas dans les matchs [multijoueurs](/wiki/Multi), car elle sera considérée comme une tentative de quitter le match et vous devrez quitter la salle.
```

2021-06-20 18:40 UTC, Ganondorf-1 requested changes

2021-06-20 18:40 UTC, Ganondorf-1 commented on wiki/Visual_Settings/fr.md
> +| `Ignorer le skin intégré` | Utilisez le skin sélectionnée par le joueur au lieu du skin incluse dans la beatmap. | Cela nécessite de recommencer la beatmap pour prendre effet. |
```suggestion
| `Ignorer le skin intégré` | Utilise le skin sélectionné par le joueur au lieu du skin inclus dans la beatmap. | Cela nécessite de recommencer la beatmap pour prendre effet. |
```

2021-06-20 18:40 UTC, Ganondorf-1 commented on wiki/Visual_Settings/fr.md
> +| `Assombrir l'arrière-plan :` | Assombrir le terrain de jeu (y compris les story-boards et/ou les vidéos de fond). | Pendant les pauses, le niveau de luminosité est réduit de 30% (max 0%) (ce compor
```suggestion
| `Assombrir l'arrière-plan :` | Assombrir le terrain de jeu (y compris les storyboards et/ou les vidéos de fond). | Pendant les pauses, le niveau de luminosité est réduit de 30% (max 0%) (ce comportement peut être désactivé dans les options). *Note : Les modifications de l'assombrissement d'arrière-plan sont sauvegardées par beatmap mais seront perdues après la fermeture d'osu!* |
```

2021-06-21 06:13 UTC, geshii requested changes

2021-06-21 06:13 UTC, geshii commented on wiki/Visual_Settings/fr.md
> +Les **paramètres visuels** sont un menu de personnalisation caché situé en bas du terrain de jeu. Il est possible d'y accéder lorsque la beatmap est en cours de chargement ou lorsque le jeu est en pa
> Les **paramètres visuels** sont un menu de personnalisation caché situé en bas du terrain de jeu.   

Je pense qu'on devrait réécrire cette phrase, le "sont un menu" je suis pas sûr.
Pourquoi pas "Les  paramètres visuels sont **des options de personnalisation cachées situées en bas du terrain de jeu**." ? Dites moi ce que vous en pensez

2021-06-21 06:13 UTC, geshii commented on wiki/Visual_Settings/fr.md
> +Il est également possible d'accéder au menu des paramètres visuels en mettant le jeu en pause. Toutefois, cette méthode ne fonctionne pas dans les matchs [multijoueurs](/wiki/Multi), car elle sera co
```suggestion
Il est également possible d'accéder au menu des paramètres visuels en mettant le jeu en pause. Toutefois, cette méthode ne fonctionne pas dans les matchs [multijoueurs](/wiki/Multi), car elle est considérée comme une tentative de quitter le match et vous devrez quitter la salle.
```

2021-06-21 07:37 UTC, DoryanR commented on wiki/Visual_Settings/fr.md
> +Les **paramètres visuels** sont un menu de personnalisation caché situé en bas du terrain de jeu. Il est possible d'y accéder lorsque la beatmap est en cours de chargement ou lorsque le jeu est en pa
```suggestion
Les **paramètres visuels** sont des options de personnalisation cachées situées en bas du terrain de jeu. Il est possible d'y accéder lorsque la beatmap est en cours de chargement ou lorsque le jeu est en pause. Lorsque le menu des paramètres visuels est affiché, la beatmap ne commencera pas et attendra que le curseur quitte le menu des paramètres visuels.
```

2021-06-21 14:39 UTC, geshii approved these changes
Tout est bon pour moi

2021-06-22 17:42 UTC, Satsukel requested changes
Juste pour harmoniser avec ce qui a déjà été fait dans d'autres articles, cad mettre à la 3eme personne du singulier quand c'est possible plutôt que infinitif, puis pluriel, puis singulier etc...

2021-06-22 17:42 UTC, Satsukel commented on wiki/Visual_Settings/fr.md
> +| `Assombrir l'arrière-plan :` | Assombrir le terrain de jeu (y compris les storyboards et/ou les vidéos de fond). | Pendant les pauses, le niveau de luminosité est réduit de 30% (max 0%) (ce comport
```suggestion
| `Assombrir l'arrière-plan :` | Assombrit le terrain de jeu (y compris les storyboards et/ou les vidéos de fond). | Pendant les pauses, le niveau de luminosité est réduit de 30% (max 0%) (ce comportement peut être désactivé dans les options). *Note : Les modifications de l'assombrissement d'arrière-plan sont sauvegardées par beatmap mais seront perdues après la fermeture d'osu!* |
```

2021-06-22 17:42 UTC, Satsukel commented on wiki/Visual_Settings/fr.md
> +| `Désactiver le storyboard` | Supprimez tous les éléments du storyboard. Cela n'affecte pas le [Kiai Time](/wiki/Kiai_time) et la vidéo de fond, le cas échéant. | Cette option est recommandée aux jo
```suggestion
| `Désactiver le storyboard` | Supprime tous les éléments du storyboard. Cela n'affecte pas le [Kiai Time](/wiki/Kiai_time) et la vidéo de fond, le cas échéant. | Cette option est recommandée aux joueurs ayant des problèmes d'épilepsie, lorsque la beatmap affiche un avertissement d'épilepsie. Cette option est désactivée s'il n'y a pas de storyboard à jouer. |
```

2021-06-23 07:32 UTC, Satsukel submitted a review, later dismissed

2021-06-25 20:26 UTC, DoryanR commented
Can be merge

2021-06-25 20:29 UTC, TicClick requested changes

2021-06-25 20:29 UTC, TicClick commented on wiki/Visual_Settings/fr.md
> +| `Ignorer les bruitages intégrés aux beatmaps  ` | Utilise les hitsounds du skin sélectionné par le joueur au lieu des hitsounds personnalisés de la beatmap, le cas échéant. | Cela nécessite de reco
```suggestion
| `Ignorer les bruitages intégrés aux beatmaps` | Utilise les hitsounds du skin sélectionné par le joueur au lieu des hitsounds personnalisés de la beatmap, le cas échéant. | Cela nécessite de recommencer la beatmap pour prendre effet. |
```

2021-06-25 20:29 UTC, TicClick approved these changes

2021-06-25 20:30 UTC, merged