[RU] Rewritten "Chat Console"
ppy/osu-wiki pull request #5730
Opened 2021-06-20 12:02 UTC by Ceotom

Rewriten and updated chat console article

2021-06-25 22:07 UTC, TicClick requested changes
я начал писать ревью, но где-то в начале пути понял, что ты переписываешь старый перевод вместо того, чтобы его обновить. хотя это дело само по себе хорошее, при нём нельзя убирать маркер `outdated: true`.

в общем, примени пока мои правки и либо верни маркер, либо сравни содержание с https://github.com/ppy/osu-wiki/blob/master/wiki/Chat_Console/en.md и сделай полноценный перевод.

я бы рекомендовал пойти по более быстрому пути, потому что оригинальную статью всё равно нужно будет переписывать, а время, потраченное на перевод, который потом будет наполовину (?) выброшен, тебе никто не вернёт (даже я)

2021-06-25 22:07 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +Все пользователи, которые вошли в osu! имеют панель пользователя, отображающуюся в расширенном окне чата. По умолчанию она отображает основную информацию (имя, общий рейтинг, ранк, точность, количест
```suggestion
В расширенном окне отображаются панели всех игроков, находящихся в сети. По умолчанию панель отображает основные сведения об игроке (имя, общий рейтинг, ранк, точность, количество игр и аватар, если он есть). Если навести на неё курсор, будут видны дополнительные данные (имя, ранк, аватар, если есть, время и часовой пояс, местоположение и страна, город (при согласии пользователя) и текущая активность).
```

2021-06-25 22:07 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +- `Все` - отображает всех. `Друзья` - отображает только Ваших друзей. `Рядом` - отображает игроков в ближайших городах от вашего. `Страна` - отображает игроков из Вашей страны.
так, в оригинале тут другое

2021-06-26 07:45 UTC, Ceotom commented on wiki/Chat_Console/ru.md
> +| **Зелёный** | Сообщение содержит Ваше имя пользователя или слово которое Вы добавили в список подсвечиваемых в чате слов. Копия сообщения так же появится в канале `#highlight`. |
В текущем переводе клиента написано `Список подсвечиваемых в чате слов (через пробел)`, может быть лучше оставить `список подсвечиваемых в чате слов`, чтобы никого не смутить?

2021-06-26 07:49 UTC, Ceotom commented on wiki/Chat_Console/ru.md
> +- `Все` - отображает всех. `Друзья` - отображает только Ваших друзей. `Рядом` - отображает игроков в ближайших городах от вашего. `Страна` - отображает игроков из Вашей страны.
Я знаю что в оригинале тут другое, было бы не плохо это видеть и в оригинальной статье.

2021-07-05 17:39 UTC, TicClick requested changes
как-то так

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| ![Игрок вошёл через IRC](img/Chat_Console-IRC.png "Игрок вошёл через IRC") | Тёмно-синий, без содержимого - Игрок не в игре, но вошёл через IRC клиент или статистика недоступна. |
вообще это хорошо бы переписать на безличные предложения, но я потом сам этим займусь вместе с переделкой статьи

```suggestion
| ![Игрок смотрит реплей](img/Chat_Console-Watching.png "Игрок смотрит реплей") | Светло-синий: игрок смотрит реплей или наблюдает за другим игроком. |
| ![Игрок редактирует карту](img/Chat_Console-Editing.png "Игрок редактирует карту") | Красный: игрок редактирует свою карту. |
| ![Игрок тестирует карту](img/Chat_Console-Testing.png "Игрок тестирует карту") | Фиолетовый: игрок тестирует карту в редакторе. |
| ![Игрок загружает карту](img/Chat_Console-Submitting.png "Игрок загружает карту") | Бирюзовый: игрок загружает на сервер новую версию своей карты. |
| ![Игрок проверяет чужую карту](img/Chat_Console-Modding.png "Игрок проверяет чужую карту") | Зелёный: игрок занимается [моддингом](/wiki/Modding) чужой карты. |
| ![Игрок находится в лобби](img/Chat_Console-Multiplayer.png "Игрок находится в лобби") | Коричневый: игрок находится в комнате мультиплеера, но не играет. |
| ![Игрок соревнуется в мультиплеере](img/Chat_Console-Multiplaying.png "Игрок соревнуется в мультиплеере") | Жёлтый: игрок соревнуется в мультиплеере. |
| ![Игрок отошёл от клавиатуры](img/Chat_Console-Afk.png "Игрок отошёл от клавиатуры") | Чёрный: игрок отошёл от клавиатуры (AFK). |
| ![Игрок вошёл через IRC](img/Chat_Console-IRC.png "Игрок вошёл через IRC") | Тёмно-синий, без статистики: игрок вошёл в чат через IRC-клиент, либо его статистика ещё не прогрузилась. |
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +Нажатие на панель пользователя открывает экран с опциями
```suggestion
Нажатие на панель пользователя открывает список возможных действий.
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +![Экран с опциями](img/Chat_Console-Userpaneloptions.jpg "Экран с опциями")
```suggestion
![Список действий, которые можно совершить с пользователем](img/Chat_Console-Userpaneloptions.jpg "Список действий, которые можно совершить с пользователем")
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +Нажмите на цифру или кликните на панель для выбора:
```suggestion
Кликните по пункту, чтобы его выбрать, или нажмите клавишу с соответствующей цифрой:
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +8. `Отмена`: Закрывает данный экран.
```suggestion
1. `Наблюдать за игрой`: если пользователь играет карту, вы можете посмотреть за его игрой. Ваш ник будет отображен в списке наблюдателей у этого игрока.
2. `Открыть профиль`: открывает профиль игрока в браузере.
3. `Начать разговор`: открывает вкладку чата с данным пользователем.
4. `Пригласить в мульти`: приглашает пользователя в комнату в мультиплеере, если вы там находитесь.
5. `Добавить (удалить) из друзей`: добавляет или удаляет пользователя из вашего списка друзей.
6. `Отправить жалобу...`: открывает форму для жалобы на поведение пользователя. Используйте этот пункт, чтобы сообщить о нарушении правил внутри игры. Пожаловаться на поведение вне игры можно из профиля игрока.
7. `Игнорировать`: скрывает сообщения данного пользователя в вашем окне чата.
8. `Отмена`: закрывает список действий.
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| Команда | Результат | Пример | Ответ BanchoBot'а |
```suggestion
| Команда | Результат | Пример | Ответ BanchoBot |
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| `/delfriend [пользователь]` | Удаляет `[пользователь]` из Вашего списка друзей. | `/delfriend Amigo` | You are no longer friends with Amigo. |
```suggestion
| `/addfriend [пользователь]` | Добавить `[пользователь]` в список друзей. | `/addfriend Amigo` | You are now friends with Amigo. |
| `/delfriend [пользователь]` | Удалить `[пользователь]` из списка друзей. | `/delfriend Amigo` | You are no longer friends with Amigo. |
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| `/clear` | Очищает историю чата. | `/clear` | (Очищает всё в данной вкладке) |
```suggestion
| `/away [сообщение]` | Настроить сообщение для автоответа другим пользователям. Оставьте `[сообщение]` пустым, чтобы выключить автоответчик. | `/away I am John Smith.` | You have been marked as being away: I am John Smith. When Amigo /msg John Where are you~? BanchoBot: I am John Smith. |
| `/bb` | Отправить сообщение лично BanchoBot, например, `!stats [пользователь]` | `/bb !stats Uan` | \[15/11/12\] Stats for [Uan](https://osu.ppy.sh/users/147623): Score: 47,323,299,680 (#1) Plays: 176293 (lv102) Accuracy: 98.95% |
| `/chat [пользователь]` | Открыть вкладку чата с пользователем. | `/chat Amigo` | (Открылась вкладка чата с Amigo) |
| `/clear` | Очистить историю чата. | `/clear` | (Стирает весь текст в открытой вкладке) |
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| `/me [действие]` | Выполняет действие от третьего лица. | `/me is at home` | * John is at home |
```suggestion
| `/ignore [пользователь][@chp]` | Скрывать все сообщения пользователя до перезапуска игры. Дописав после ника символ `@` и буквы `c`, `h` или `p`, вы можете скрыть сообщения в чате, упоминаниях или личной переписке соответственно. | `/ignore Amigo@chp` | BanchoBot: You will no longer hear Amigo {chat} {highlights} {PM} (Теперь все сообщения \[c\], все упоминания \[h\] и личные сообщения \[p\] от Amigo будут скрыты. |
| `/j [канал]` или `/join [канал]` | Зайти на канал | `/join #lobby` | (Открывается вкладка `#lobby`) |
| `/p` или `/part` | Покинуть открытый канал. | `/part` | Нет |
| `/unignore [пользователь]` | Перестать игнорировать сообщения от указанного пользователя. | `/unignore Amigo` | Теперь вы будете видеть сообщения от Amigo. |
| `/me [действие]` | Выполнить действие от третьего лица. | `/me is at home` | * John is at home |
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| `/invite [пользователь]` | Приглашает `[пользователь]` в мультиплеерную комнату по ссылке. | `/invite Nathanael` | Вы приглассили Nathanael в вашу комнату. |
```suggestion
| `/msg [пользователь] [сообщение]` | Отправить личное сообщение `[пользователь]`. | `/msg Amigo I am sick at home.` | (Во вкладке с Amigo) John: I am sick at home. |
| `/np` | Отправить в чат карту, которую вы играете, слушаете, или где смотрите реплей. | `/np` | (Во время игры) * John is playing [Peter Lambert - osu! tutorial \[Gameplay Basics\]](https://osu.ppy.sh/beatmapsets/3756#osu/22538) |
| `/reply` или `/r` | Ответить на последнее полученное личное сообщение. | `/r Do you know any good doctor?` | (Во вкладке с Amigo) \[Предыдущие сообщения\] John: I am sick at home. Amigo: Really? John: Do you know any good doctor? |
| `/savelog` | Сохранить историю чата в текстовый файл. | `/savelog` | (Создана папка `Chat` в директории с osu!, в которой будет сохранена история чата) |
| `/watch [пользователь]` | Начать наблюдение за игрой `[пользователь]`. | `/watch Amigo` | * Started spectating Amigo. (Когда Amigo начнёт играть имеющуюся у вас карту, вы сможете наблюдать за его действиями) |
| `/nopm` | Разрешить или запретить пользователям не из вашего списка друзей отправлять вам сообщения | `/nopm` | (В центре экрана появится сообщение о том, кто может с вами связываться). |
| `/invite [пользователь]` | Отправить `[пользователь]` ссылку-приглашение в мультиплеер. | `/invite Nathanael` | Вы пригласили Nathanael в вашу комнату. |
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +## /keys
уровень заголовка потерял
```suggestion
### /keys
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| Кнопки на клавиатуре | Результат |
```suggestion
| Сочетание клавиш | Действие |
```

2021-07-05 17:39 UTC, TicClick commented on wiki/Chat_Console/ru.md
> +| `Alt` + `0` - `9` | Перейти к соответствующей вкладке. |
```suggestion
| `Page Up` / `Page Down` | Пролистать окно чата (альтернатива — колесо мыши). |
| `Tab` | Дополнить ник пользователя по первым буквам или показать возможные варианты. |
| `F8` | Показать/скрыть окно чата. |
| `F9` | Показать/скрыть расширенное окно чата. |
| `Ctrl` + `C` / `V` | Скопировать текст, выделенный в окне отправки сообщения, или вставить его. |
| `Alt` + `0` - `9` | Перейти к вкладке под соответствующим номером. |
```

2021-07-06 02:50 UTC, Ceotom commented on wiki/Chat_Console/ru.md
> +- Пользователи без статистики на панели вошли в чат с помощью IRC клиента.
```suggestion
- Вкладки `Ник`, `Ранк` и остальные сортируют пользователей по определённым критериям.
- Вкладка `Карта мира` показывает, откуда пользователи по всему миру вышли в сеть.
- Чтобы переместиться по списку, используйте колесо мыши, или перетаскивайте белый прямоугольник справа.
- Если у пользователя нет статистики, он читает чат через IRC-клиент.
```

2021-07-07 16:58 UTC, TicClick approved these changes
looks good to me -- thank you for cleaning this stuff up

2021-07-07 17:17 UTC, TicClick approved these changes

2021-07-07 17:17 UTC, merged