[ZH] Create Chinese translation of Account in Help Centre
ppy/osu-wiki pull request #5759
Opened 2021-06-29 13:03 UTC by cdwcgt

one of subpage in help centre

2021-07-04 22:59 UTC, kj415j45 requested changes

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +与你的osu!帐号所相关的一些内容。阅读下列文章以适合你问题的解决方案。
```suggestion
与你的 osu! 帐号息息相关的一些问题。阅读下列内容以了解问题的解决方案。
```

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +**根据你使用的支付服务（Paypal 或 Xsolla），支付结果到达我们这里可能会有些许的延迟。**
```suggestion
**根据你使用的支付服务（PayPal 或 Xsolla），支付结果到达我们这里可能会有些许的延迟。**
```

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +请不要在你的邮件中附带成绩或者回放 —— 我们无法通过这些信息核实你是账号的拥有者。
```suggestion
请不要在你的邮件中附带成绩或者回放——我们无法通过这些信息核实你是账号的拥有者。
```

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +**这通常发生在你和我们的服务器之间存在网络问题时。**
```suggestion
**当你和我们的服务器之间存在网络问题时，该提示会频繁出现。**
```

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +一些VPN和代理服务器可能出于任何原因无法与osu!使用。
```suggestion
一些VPN和代理服务器可能出于某种原因无法在osu!使用。
```

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +我们为用户资料卡直接显示的曾用名提供免费恢复。发送改回用户名的请求到  [accounts@ppy.sh](mailto:accounts@ppy.sh) 即可。
```suggestion
我们为用户资料卡直接显示的曾用名提供免费恢复。发送改回用户名的请求到 [accounts@ppy.sh](mailto:accounts@ppy.sh) 即可。
```

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +I如果我们允许每个人创建多个账号，成绩排行榜将会变得几乎没有意义！
```suggestion
如果我们允许大家创建多个账号，成绩排行榜将会变得几乎没有意义！
```

2021-07-04 22:59 UTC, kj415j45 commented on wiki/Help_Centre/Account/zh.md
> +**如果你有 osu!supporter tag且未过期**，你可以在[谱面页面](https://osu.ppy.sh/beatmapsets)中查看你所有上传过成绩的谱面。点击`更多搜索选项`，然后在`玩过`过滤项中选择`玩过`。或者你也可以点击[这个链接](https://osu.ppy.sh/beatmapsets?played=played)直接访问过滤后的网页。
```suggestion
**如果你有 osu!supporter 且未过期**，你可以在[谱面页面](https://osu.ppy.sh/beatmapsets)中查看你所有上传过成绩的谱面。点击`更多搜索选项`，然后在`玩过`过滤项中选择`玩过`。或者你也可以点击[这个链接](https://osu.ppy.sh/beatmapsets?played=played)直接访问过滤后的网页。
```

2021-07-07 06:23 UTC, kj415j45 approved these changes

2021-07-08 14:26 UTC, TPGPL requested changes

2021-07-08 14:26 UTC, TPGPL commented on wiki/Help_Centre/Account/zh.md
> +对于获取network.log文件的说明，请参见[日志文件](/wiki/Help_Centre#log_files)。
```suggestion
对于获取network.log文件的说明，请参见[日志文件](/wiki/Help_Centre#日志文件)。
```

2021-07-08 14:26 UTC, TPGPL commented on wiki/Help_Centre/Account/zh.md
> +*关于删除帐号的更多消息，参见： [您的权利和控制](https://osu.ppy.sh/legal/Privacy#your-rights-and-control).*
```suggestion
*关于删除帐号的更多消息，参见： [您的权利和控制](/wiki/Legal/Privacy#your-rights-and-control).*
```

2021-07-08 14:26 UTC, TPGPL commented on wiki/Help_Centre/Account/zh.md
> +是的，任何用户可以发邮件至 [privacy@ppy.sh](mailto:privacy@ppy.sh) 请求删除帐号。请记住，删除您的帐户是**永久操作**，这意味着它无法撤消或撤消。删除你的帐号不意味着你可以创建一个新账户，拥有多个帐号违反[规章制度](/wiki/Rules#community-rules)。这意味着你将无法再使用osu!的在线功能。
```suggestion
是的，任何用户可以发邮件至 [privacy@ppy.sh](mailto:privacy@ppy.sh) 请求删除帐号。请记住，删除您的帐户是**永久操作**，这意味着它无法撤消或撤消。删除你的帐号不意味着你可以创建一个新账户，拥有多个帐号违反[规章制度](/wiki/Rules#社区规定)。这意味着你将无法再使用osu!的在线功能。
```

2021-07-08 14:27 UTC, TPGPL approved these changes

2021-07-08 14:28 UTC, merged