News post for 'osu!CenterStage - Idol 2021'
ppy/osu-wiki pull request #5775
Opened 2021-07-02 04:16 UTC by MjIsMaster

This is a news post for the auditions of osu!CenterStage (official successor to osu!idol)

2021-07-02 13:24 UTC, TPGPL requested changes

2021-07-02 13:24 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +A new chapter in the history of this competition, but the spirit is as strong as ever!
```suggestion
We are happy to announce the yearly idol contest is back and ready for action!

![](/wiki/shared/news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open/centerstagebanner.jpg)

A new chapter in the history of this competition, but the spirit is as strong as ever!
```

2021-07-02 13:24 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +### **What is osu!CenterStage?**
```suggestion
## What is osu!CenterStage?

```

2021-07-02 13:24 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +### **How does this work?**
```suggestion
## How does this work?

```

2021-07-02 13:24 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +### **Any Prizes?**
```suggestion
## Any prizes?

```

2021-07-02 13:24 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +For all relevant information you will need to know in entering this year's competition check out the [*official thread*](https://osu.ppy.sh/community/forums/topics/1359674). To get involved with the
```suggestion
For all relevant information you will need to know in entering this year's competition check out the [official thread](https://osu.ppy.sh/community/forums/topics/1359674). To get involved with the community and receiving important updates regarding this contest, join the official [Discord server](https://discord.gg/eBaDTYrvby).
```

2021-07-02 14:39 UTC, MjIsMaster reviewed
All suggestions have been committed.

2021-07-02 16:13 UTC, TPGPL requested changes

2021-07-02 16:13 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +We are happy to announce the yearly idol contest is back and ready for action!
```suggestion
We are happy to announce that the yearly idol contest is back and ready for action!
```

2021-07-02 16:13 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +A successor to the much beloved osu!idol competition which concluded in 2020. The format remains largely the same. Participants will sing through the various rounds set for them until a winner is dec
```suggestion
A successor to the much beloved osu!idol competition which concluded in 2020. The format remains largely the same. Participants will sing through the various rounds set for them until a winner is decided. A panel of judges will guide the direction of this contest by evaluating and critiquing the participants' performances.
```

2021-07-02 16:13 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +For the auditions, record yourself performing a 30-60 second sample of any song (with no BGM) then submit in your entry. It's as simple as that! July 21st will be the deadline so make haste and submi
```suggestion
For the auditions, record yourself performing a 30-60 second sample of any song (with no background music), then submit in your entry. It's as simple as that! July 21st will be the deadline, so make haste and submit in those wonderful entries!
```

2021-07-02 16:13 UTC, TPGPL commented on news/2021-07-02-osu!centerstage-idol-2021-auditions-now-open.md
> +For all relevant information you will need to know in entering this year's competition check out the [official thread](https://osu.ppy.sh/community/forums/topics/1359674). To get involved with the co
```suggestion
For all relevant information you will need to know before entering this year's competition, check out the [official thread](https://osu.ppy.sh/community/forums/topics/1359674). To get involved with the community and receive important updates regarding this contest, join the official [Discord server](https://discord.gg/eBaDTYrvby "Discord").
```

2021-07-02 17:10 UTC, MjIsMaster reviewed
Additional suggestions have been committed.

2021-07-03 14:59 UTC, TPGPL submitted a review, later dismissed
LGTM; if you plan to make any more changes on your local side, use `git fetch origin` and then `git reset --hard origin/osu!CenterStage`, so the commit history doesn't break

2021-07-04 17:21 UTC, MjIsMaster commented
Added a few words at the end of the post and fixed dates to match. Everything else remains the same

2021-07-31 08:52 UTC, roansong commented
I see the registration deadline is August 1st now on the forum post; I think this iteration of the news post isn't going to make it.

2021-08-23 17:23 UTC, TPGPL commented
@MjIsMaster is this news post still relevant or can the PR be closed safely?

2021-08-28 11:21 UTC, TPGPL commented
sadly it looks like the PR is outdated, so I will close it for now

2021-08-28 11:21 UTC, closed without merging