Some translations of wiki into Russian lang.
ppy/osu-wiki pull request #5787
Opened 2021-07-05 20:22 UTC by Loreos7

I am a noob at github, but i've submitted some translations to community.

2021-07-07 17:20 UTC, TicClick commented
я посмотрю в ближайшее время

2021-07-25 15:03 UTC, DoryanR requested changes
Fix to pass the file verification check

2021-07-25 15:03 UTC, DoryanR commented on wiki/Graveyard/ru.md
> +
```suggestion
# Заброшенная

**Заброшенная** (Graveyard или Грейвярд) - это статус для [карт](/wiki/Beatmap), которые были заброшены их создателями. Такие карты не идут в счет общего лимита по загрузкам на игрока. [Хост карты](/wiki/Beatmap/Beatmap_host) может "оживить" карту, обновив её. Для этого требуется свободный слот, и карте присваивается статус [В разработке (WIP)](/wiki/Beatmap/Category#work-in-progress-and-pending).

```

2021-08-12 22:28 UTC, TicClick requested changes
«ближайшее время» затянулось, но вот я здесь

2021-08-12 22:28 UTC, TicClick commented on wiki/Beatmap/Guest_difficulty/ru.md
> +Многие гостевые сложности появляются благодаря общению между создателями карт. Если что, гостевые сложности можно запросить на [форуме по моддингу](https://osu.ppy.sh/community/forums/60)<!-- TODO: s
```suggestion
Многие гостевые сложности появляются благодаря общению между создателями карт. Помимо этого, о них можно попросить на [форуме по моддингу](https://osu.ppy.sh/community/forums/60)<!-- TODO: should link to an article about queues, not the forum -->.
```

2021-08-12 22:28 UTC, TicClick commented on wiki/Graveyard/ru.md
> +---
это лишняя статья, поскольку у нас есть https://osu.ppy.sh/wiki/en/Beatmap/Category#graveyard. не переводи, я удалю потом.

2021-08-12 22:29 UTC, TicClick commented
тегни меня, когда всё применишь и пулл-реквест будет готов

2021-08-16 06:54 UTC, Loreos7 commented on wiki/Beatmap/Beatmap_collaborations/ru.md
> +*Чтобы узнать, как начать создавать такие сложности, см.: [Как начать редактировать совместно](/wiki/Guides/Collab_Information)*
Тогда стоит предложить это оригинальной статье, видимо там тоже не совсем "человечно".

2021-08-16 17:36 UTC, TicClick commented on wiki/Beatmap/Beatmap_collaborations/ru.md
> +*Чтобы узнать, как начать создавать такие сложности, см.: [Как начать редактировать совместно](/wiki/Guides/Collab_Information)*
«for ..., see ...» в оригинале более органично, но, может, там и правда нужно поправить некоторые моменты. посмотрю потом, примени пока мои правки (или откажи с причиной)

2021-09-09 20:36 UTC, TicClick approved these changes

2021-09-09 20:36 UTC, merged