Create german translation of Kudosu
ppy/osu-wiki pull request #5790
Opened 2021-07-06 15:55 UTC by Bloeckchengrafik

Just thought would be cool

2021-07-06 16:43 UTC, Bloeckchengrafik commented
fixed a grammar mistake

2021-07-21 19:24 UTC, TPGPL requested changes
also you should check this box to allow maintainers to edit your PRs

![image](https://user-images.githubusercontent.com/19843905/126547789-93933bb5-0245-400e-8f4e-6495b9d27e63.png)

2021-07-21 19:24 UTC, TPGPL commented on wiki/Modding/Kudosu/de.md
> +->
should be removed

L9 because its not available in the English article

2021-07-21 19:24 UTC, TPGPL commented on wiki/Modding/Kudosu/de.md
> +# Kudosu
```suggestion
---
stub: true
no_native_review: true
---

# Kudosu
```

2021-07-25 19:19 UTC, TPGPL approved these changes

2021-07-25 19:19 UTC, merged