Mentorship Summer 2021 Signups
ppy/osu-wiki pull request #5821
Opened 2021-07-11 18:18 UTC by yaspo

2021-07-12 00:03 UTC, TPGPL submitted a review, later dismissed
lgtm

2021-07-12 01:49 UTC, Joehuu requested changes
File needs to be moved to the `news` folder.

2021-07-12 07:54 UTC, Joehuu approved these changes

2021-07-15 16:23 UTC, Ephemeralis approved these changes

2021-07-15 16:24 UTC, merged