[TH] Getting your map modded
ppy/osu-wiki pull request #5823
Opened 2021-07-12 02:47 UTC by dumb-stuff

I delete some outdated stuff in there so it should ready to go

2021-07-12 12:08 UTC, TPGPL requested changes
The `outdated` marker means that the translation is outdated comparing to the [English version](https://osu.ppy.sh/wiki/en/Guides/Getting_Your_Map_Modded) of the article. Your PR didnt fix the problem, so the marker cannot be removed yet.

2021-07-14 08:22 UTC, dumb-stuff commented
> The `outdated` marker means that the translation is outdated comparing to the [English version](https://osu.ppy.sh/wiki/en/Guides/Getting_Your_Map_Modded) of the article. Your PR didnt fix the problem, so the marker cannot be removed yet.

I delete it now
I was first thought that outdate : false should be fine

2021-07-14 08:23 UTC, dumb-stuff commented
oh I see

2021-07-14 08:51 UTC, dumb-stuff commented
@TPGPL How about this commit now?

2021-07-14 15:02 UTC, TPGPL requested changes
looks like the translation is still outdated

L3 has different links than the English article, and it's missing the `Types of mods` header

2021-07-16 08:14 UTC, dumb-stuff commented
@TPGPL  How about it now?

2021-07-16 08:17 UTC, dumb-stuff reviewed
This should pretty much all of it.
Now just wait for thai beautifier to coome fix some readability that I can't see.
:D

2021-07-16 08:20 UTC, dumb-stuff reviewed
Fixed that damn remark lint D:

2021-07-16 12:08 UTC, HelloYeew requested changes

2021-07-16 12:08 UTC, HelloYeew commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +`#modreqs` เป็นช่องในแชท osu! ที่ผู้เล่นสามารถขอม็อดสำหรับบีทแมปได้โดยการเชื่อมโยงกับคำสั่ง `/np` พร้อมกับประเภทคำขอม็อด แม้ว่าจะไม่ใช่วิธีที่มีประสิทธิภาพมากที่สุดในการค้นหาคนวิจารณ์บีมแมพเแต่คนวิจา
```suggestion
`#modreqs` เป็นช่องแชทใน osu! ที่ผู้เล่นสามารถขอการวิจารณ์บีทแมพได้โดยการเชื่อมโยงกับคำสั่ง `/np` พร้อมกับประเภทคำขอในการวิจารณ์บีทแมพ แม้ว่าวิธีนี้จะไม่ใช่วิธีที่มีประสิทธิภาพมากที่สุดในการค้นหาคนวิจารณ์บีทแมพเแต่คนวิจารณ์บีทแมพเและ Beatmap Nominators มักจะมองหาบีทแมพที่ดีที่จะลิงก์ในช่องนี้
```
Fix typo and rearrange some word

2021-07-16 12:08 UTC, HelloYeew commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +`#modreqs` ไม่มีฟังก์ชันและฐานผู้ใช้แบบเดิม แต่ยังคงเป็นวิธีที่มีประโยชน์ในการรับม็อด ดังนั้นจึงคุ้มค่าที่จะลอง แม้ว่าในปัจจุบันจะมีคำขอม็อดปกติเป็นส่วนใหญ่ แต่ก็มักใช้สำหรับคำขอประเภทอื่นๆ ที่กล่าวถ
```suggestion
`#modreqs` ไม่มีฟังก์ชันและฐานผู้ใช้เหมือนเมื่อก่อน แต่ยังคงเป็นวิธีที่มีประโยชน์ในการรับวิจารณ์บีทแมพ ดังนั้นจึงคุ้มค่าที่จะลอง แม้ว่าในปัจจุบันจะมีคำขอม็อดปกติเป็นส่วนใหญ่ แต่ก็มักใช้สำหรับคำขอประเภทอื่นๆ ที่กล่าวถึง[ข้างต้น](#types-of-mods)
```
Add link

2021-07-16 12:08 UTC, HelloYeew commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +การถามผู้ใช้รายอื่นโดยตรงเป็นวิธีที่ดีในการรับการตรวจสอบ บีทแมพ ด้วย โดยทั่วไป ถ้าม็อดเดอร์ไม่มีคิวการตรวจสอบข้อบกพร่องบีทแมพ พวกเขาน่าจะมีข้อมูลการวิจารณ์บีทแมพอยู่ในส่วน "ฉัน!" ของโปรไฟล์ของพวกเขา
```suggestion
การถามผู้ใช้รายอื่นโดยตรงเป็นวิธีที่ดีในการรับการตรวจสอบบีทแมพด้วย โดยทั่วไปถ้าผู้วิจารณ์บีทแมพไม่มีคิวการตรวจสอบข้อบกพร่องบีทแมพ พวกเขาน่าจะมีข้อมูลการวิจารณ์บีทแมพอยู่ในส่วน "ฉัน!" ของโปรไฟล์ของพวกเขา หลังจากอ่านข้อมูลที่มีในนั้นแล้ว คุณสามารถส่งข้อความถึงพวกเขาในแชท osu! กับคำขอของคุณ ในขณะที่ผู้วิจารณ์เหล่านี้หาได้ยากกว่า แต่ก็ยังมีผู้วิจารณ์บางคนที่มีคิวส่วนตัวนอกแพลตฟอร์มและอื่น ๆ
```

2021-07-16 12:08 UTC, HelloYeew commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +Beatmap Nominator ทุกคนมีข้อมูลการตรวจสอบบีทแมพในเกี่ยวกับ "ฉัน!" ไม่ว่าจะมีคิวการตรวจสอบบีทแมพหรือไม่ก็ตาม การถาม Beatmap Nominator โดยตรงนั้นแทบจะเป็นสิ่งจำเป็นสำหรับการเสนอชื่อบีทแมปของคุณ
```suggestion
Beatmap Nominator ทุกคนมีข้อมูลการตรวจสอบบีทแมพในเกี่ยวกับ "ฉัน!" ไม่ว่าจะมีคิวการตรวจสอบบีทแมพหรือไม่ก็ตาม การถาม Beatmap Nominator โดยตรงนั้นแทบจะเป็นสิ่งจำเป็นสำหรับการเสนอชื่อบีทแมพของคุณ
```

2021-07-16 12:08 UTC, HelloYeew commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +อาจเป็นวิธีที่ง่ายที่สุดในการรับการวิจารณืบีมแมพ แม้ว่าจะมีระดับคุณภาพที่แตกต่างกัน คือการขอให้เพื่อนของคุณหาข้อบกพร่องของบีทแมปของคุณ คุณอาจต้องการถามเพื่อนที่อย่างน้อยมีประสบการณ์การทำบีทแมพเล็กน้อ
```suggestion
วิธีที่อาจเป็นวิธีที่ง่ายที่สุดในการรับการวิจารณ์บีทแมพแม้ว่าจะมีระดับคุณภาพที่แตกต่างกัน คือการขอให้เพื่อนของคุณหาข้อบกพร่องของบีทแมพของคุณ คุณอาจต้องการถามเพื่อนที่อย่างน้อยมีประสบการณ์การทำบีทแมพเล็กน้อยเพื่อให้ได้ผลลัพธ์ที่ดีที่สุด
```

2021-07-16 12:11 UTC, HelloYeew commented
From my review, needing more review from other native like Trigonoculus or other cuz it has a lot to improve.

2021-07-22 14:53 UTC, Trigonoculus requested changes
ถ้ามีสงสัยหรือคิดว่าตรงไหนอ่านผิด ๆ อีก สามารถถามผมได้ตลอดนะครับบ

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
>  เพื่อที่จะให้บีทแมพของคุณถูก[จัดอันดับ](/wiki/Beatmap/Category#ranked)นั้น บีทแมพของคุณจะต้องผ่าน[การวิจารณ์บีทแมพ](/wiki/Modding)ก่อน มีหลายทางที่คุณสามารถขอให้คนตรวจสอบได้ดังนี้
```suggestion
การที่ทำให้บีทแมพของคุณได้รับการ [mod](/wiki/Modding) เป็นขั้นตอนสำคัญใน[กระบวนการแรงค์](/wiki/Beatmap_ranking_procedure) โดยมีหลายวิธีที่จะทำภารกิจนี้ให้ได้
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +ก่อนที่จะค้นหาคนวิจารณ์บีทแมพ คุณต้องเข้าใจประเภทของการวิจารณ์บีทแมพประเภทต่างๆ ที่คุณสร้างได้ก่อน คำขอสองประเภทที่ใช้บ่อยที่สุดคือการขอวิจารณ์บีทแมพแบบปกติ (คำขอ NM) และการวิจารณ์บีทแมพของเขาเพื่อให
```suggestion
ก่อนที่จะค้นหาคนวิจารณ์บีทแมพ คุณต้องเข้าใจประเภทของการวิจารณ์บีทแมพประเภทต่าง ๆ ที่คุณสร้างได้ก่อน โดยคำขอสองประเภทที่ใช้บ่อยที่สุดคือ[การขอวิจารณ์บีทแมพแบบปกติ](/wiki/Modding/Normal_mod) (คำขอ NM) และ[การวิจารณ์บีทแมพคนอื่นเพื่อให้คน ๆ นั้นวิจารณ์บีทแมพของเรา](/wiki/Modding/Mod_for_mod) (คำขอ M4M) ทั้งนี้ ประเภทของคำขอไม่ได้มีเพียงเท่านี้ ยังมีประเภทคำขอวิจารณ์บีทแมพแบบอื่น ๆ อีกสองสามประเภทซึ่งส่วนใหญ่ใช้ใน `#modreqs`:
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +การโพสต์บีทแมพของคุณใน Modding Queues เป็นวิธีที่มีประสิทธิภาพมากที่สุดและใช้กันอย่างแพร่หลายที่สุดในการค้นหาผู้คนเพื่อวิจารณ์บีทแมพของคุณ Modding Queues คือ กระทู้ใน [ฟอรั่ม Modding Queues](https://
```suggestion
การโพสต์บีทแมพของคุณใน Modding Queues เป็นวิธีที่มีประสิทธิภาพมากที่สุดและใช้กันอย่างแพร่หลายที่สุดในการค้นหาผู้คนเพื่อวิจารณ์บีทแมพของคุณ Modding Queues คือกระทู้ใน[ฟอรั่ม Modding Queues](https://osu.ppy.sh/community/forums/60) ซึ่งอนุญาตให้ผู้สร้างกระทู้ค้นหาบีทแมพเพื่อวิจารณ์บีทแมพ และเพื่อให้ผู้อื่นค้นหาคนวิจารณ์บีทแมพเพื่อวิจารณ์บีทแมพได้อย่างง่ายดาย การใช้ฟอรัมเพื่อค้นหาคนวิจารณ์บีทแมพนั้นตรงไปตรงมาและมีประสิทธิภาพ—เพียงทำตามขั้นตอนด้านล่างเพื่อเริ่มต้น:
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +1. ไปที่ฟอรัม [Modding Queues](https://osu.ppy.sh/community/forums/60)
```suggestion
1. ไปที่ฟอรั่ม [Modding Queues](https://osu.ppy.sh/community/forums/60)
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +2. เรียกดูรายการคิวและค้นหาที่ยอมรับบีทแมพจากโหมดเกมที่คุณได้ทำบีทแมพไว้ ตรวจสอบให้แน่ใจว่ามีการทำเครื่องหมายเป็น "เปิด" ในชื่อหรือโพสต์เปิด
```suggestion
2. อ่านรายการคิว และค้นหาคิวที่ยอมรับบีทแมพจากโหมดเกมที่คุณได้ทำบีทแมพไว้ ตรวจสอบให้แน่ใจว่ามีการเขียนว่า "เปิด" ในชื่อหรือโพสต์เปิด
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +3. อ่านกฎของคิว หากคุณหรือบีทแมพของคุณไม่ตรงตามข้อกำหนดที่ระบุไว้ คุณจะต้องค้นหาคิวอื่นเพื่อโพสต์
```suggestion
3. อ่านกฏของคิว หากคุณหรือบีทแมพของคุณไม่ตรงตามข้อกำหนดที่ระบุไว้ คุณจะต้องค้นหาคิวอื่นเพื่อโพสต์
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +4. อ่านสิ่งที่เขาต้องการ ของ คนวิจารณ์บีทแมพ ที่ระบุไว้ในคิว (ถ้ามี) เนื่องจากอาจช่วยประหยัดเวลาทั้งคุณและผู้สร้างคิวได้มาก
```suggestion
4. อ่านสิ่งที่ผู้วิจารณ์แมปต้องการ ซึ่งจะระบุไว้ในคิว (ถ้ามี) เนื่องจากอาจช่วยประหยัดเวลาทั้งคุณและผู้สร้างคิวได้มาก
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +6. พิมพ์คำขอประเภทที่คุณต้องการพร้อมลิงก์ไปยังบีทแมพและข้อมูลอื่นๆที่คนวิจารณ์บีทแมพขอให้คุณระบุลงในกล่อง `ตอบกลับ`
```suggestion
6. พิมพ์คำขอประเภทที่คุณต้องการ พร้อมลิงก์บีทแมพของคุณและข้อมูลอื่น ๆ ที่คนวิจารณ์บีทแมพขอให้คุณระบุลงในกล่อง `ตอบกลับ`
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +7. คลิก `โพสต์` เมื่อคุณทำเสร็จแล้ว
```suggestion
7. คลิก `โพสต์` เมื่อคุณเสร็จแล้ว
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +โดยทั่วไปยอมรับให้โพสต์ในคิวการวิจารณ์บีทแมพสองสามรายการในแต่ละครั้ง ดังนั้นอย่าลังเลที่จะทำซ้ำขั้นตอนนี้หากจำเป็น หรือหากคุณต้องการเพิ่มโอกาสในการได้รับวิจารณ์บีทแมพ อย่างไรก็ตาม โปรดทราบว่าเพียงเพร
```suggestion
โดยทั่วไปแล้ว เป็นที่ยอมรับให้โพสต์ในคิวการวิจารณ์บีทแมพสองหรือสามรายการในแต่ละครั้ง ดังนั้นอย่าลังเลที่จะทำขั้นตอนนี้ซ้ำหากจำเป็น หรือหากคุณต้องการเพิ่มโอกาสในการได้รับการวิจารณ์บีทแมพ อย่างไรก็ตาม โปรดทราบว่าเพียงเพราะคุณโพสต์ในคิวการวิจารณ์บีทแมพ ไม่ได้หมายความว่าคนวิจารณ์บีทแมปจำเป็นจะต้องวิจารณ์บีทแมพของคุณ พวกเขาจะวิจารณ์บีทแมพหากเขาต้องการ
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +คุณควรหลีกเลี่ยงการโพสต์ในคิวของ Beatmap Nominator จนกว่าทักษะการสร้างบีทแมพของคุณจะอยู่ในระดับที่ใกล้เคียงที่จะจัดอันดับได้ (เว้นแต่พวกเขาจะระบุว่ากำลังมองหาผู้ทำบีทแมพมือใหม่) เนื่องจากพวกเขามักจะเ
```suggestion
คุณควรหลีกเลี่ยงการโพสต์ในคิวของ Beatmap Nominator จนกว่าทักษะการสร้างบีทแมพของคุณจะอยู่ในระดับที่ใกล้เคียงที่จะจัดอันดับได้ (เว้นแต่พวกเขาจะระบุว่ากำลังมองหาผู้ทำบีทแมพมือใหม่) เนื่องจากพวกเขามักจะเพิกเฉยต่อคำขอของคุณ ฉะนั้นคุณควรไปหาผู้วิจารณ์บีทแมพคนอื่น ๆ เพื่อวิจารณ์บีทแมพของคุณในตอนที่คุณกำลังเรียนรู้ในการสร้างบีทแมพดีกว่า
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +## ช่อง #modreqs
```suggestion
## #modreqs
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +*คำเตือน! อย่าส่งคำขอซ้ำๆในช่องนี้ คุณอาจจะโดนให้[เงียบ](wiki/Silence) ให้คุณทำการส่งคำขอและรออย่างน้อย 1 ชั่วโมงแล้วส่งใหม่*
```suggestion
*คำเตือน: อย่าส่งคำขอซ้ำ ๆ ในช่องนี้ คุณอาจจะโดนให้[เงียบ](wiki/Silence) ให้คุณทำการส่งคำขอประมาณชั่วโมงละครั้ง*
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +`#modreqs` เป็นช่องแชทใน osu! ที่ผู้เล่นสามารถขอการวิจารณ์บีทแมพได้โดยการเชื่อมโยงกับคำสั่ง `/np` พร้อมกับประเภทคำขอในการวิจารณ์บีทแมพ แม้ว่าวิธีนี้จะไม่ใช่วิธีที่มีประสิทธิภาพมากที่สุดในการค้นหาคนวิ
```suggestion
`#modreqs` เป็นช่องแชทใน osu! ที่ผู้เล่นสามารถขอการวิจารณ์บีทแมพได้โดยการเชื่อมโยงกับคำสั่ง `/np` พร้อมกับประเภทคำขอในการวิจารณ์บีทแมพ แม้ว่าวิธีนี้จะไม่ใช่วิธีที่มีประสิทธิภาพมากที่สุดในการค้นหาการวิจารณ์บีทแมพ คนวิจารณ์บีทแมพและ Beatmap Nominators มักจะมองหาบีทแมพที่ดีที่ถูกลิงก์ในช่องนี้
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +`#modreqs` ไม่มีฟังก์ชันและฐานผู้ใช้เหมือนเมื่อก่อน แต่ยังคงเป็นวิธีที่มีประโยชน์ในการรับวิจารณ์บีทแมพ ดังนั้นจึงคุ้มค่าที่จะลอง แม้ว่าในปัจจุบันจะมีคำขอม็อดปกติเป็นส่วนใหญ่ แต่ก็มักใช้สำหรับคำขอประเ
```suggestion
`#modreqs` ไม่ได้มีฟังก์ชันและฐานผู้ใช้เหมือนเมื่อก่อน แต่ยังคงเป็นวิธีที่มีประโยชน์ในการรับการวิจารณ์บีทแมพ ดังนั้นจึงคุ้มค่าที่จะลอง แม้ว่าในปัจจุบันจะมีคำขอ mod ปกติเป็นส่วนใหญ่ แต่ก็มักใช้สำหรับคำขอประเภทอื่น ๆ ที่กล่าวถึง[ข้างต้น](#types-of-mods)
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +การถามผู้ใช้รายอื่นโดยตรงเป็นวิธีที่ดีในการรับการตรวจสอบบีทแมพด้วย โดยทั่วไปถ้าผู้วิจารณ์บีทแมพไม่มีคิวการตรวจสอบข้อบกพร่องบีทแมพ พวกเขาน่าจะมีข้อมูลการวิจารณ์บีทแมพอยู่ในส่วน "ฉัน!" ของโปรไฟล์ของพวก
```suggestion
การถามผู้ใช้รายอื่นโดยตรงเป็นวิธีที่ดีในการรับการตรวจสอบบีทแมพด้วย โดยทั่วไปแล้ว หากผู้วิจารณ์บีทแมพไม่มีคิวการวิจารณ์บีทแมพ พวกเขามักจะมีข้อมูลการวิจารณ์บีทแมพอยู่ในส่วน "ฉัน!" ของโปรไฟล์ของเขา หลังจากอ่านข้อมูลที่มีในนั้นแล้ว คุณสามารถส่งข้อความถึงพวกเขาในแชท osu! กับคำขอของคุณ ในขณะที่ผู้วิจารณ์เหล่านี้หาได้ยาก แต่ก็ยังมีบ้าง โดยส่วนใหญ่แล้วจะมีคิวส่วนตัวนอกแพลตฟอร์มและอื่น ๆ
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +Beatmap Nominator ทุกคนมีข้อมูลการตรวจสอบบีทแมพในเกี่ยวกับ "ฉัน!" ไม่ว่าจะมีคิวการตรวจสอบบีทแมพหรือไม่ก็ตาม การถาม Beatmap Nominator โดยตรงนั้นแทบจะเป็นสิ่งจำเป็นสำหรับการเสนอชื่อบีทแมพของคุณ
```suggestion
Beatmap Nominator ทุกคนมีข้อมูลการตรวจสอบบีทแมพในเกี่ยวกับ "ฉัน!" ไม่ว่าจะมีคิวการตรวจสอบบีทแมพหรือไม่ก็ตาม การถาม Beatmap Nominator โดยตรงนั้น แทบจะเป็นสิ่งจำเป็นสำหรับการให้เขาวิจารณ์บีทแมพ และ/หรือ nominate แมปของคุณ
```

2021-07-22 14:53 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +วิธีที่อาจเป็นวิธีที่ง่ายที่สุดในการรับการวิจารณ์บีทแมพแม้ว่าจะมีระดับคุณภาพที่แตกต่างกัน คือการขอให้เพื่อนของคุณหาข้อบกพร่องของบีทแมพของคุณ คุณอาจต้องการถามเพื่อนที่อย่างน้อยมีประสบการณ์การทำบีทแมพเ
```suggestion
วิธีที่อาจเป็นวิธีที่ง่ายที่สุดในการรับการวิจารณ์บีทแมพ แม้ว่าจะมีระดับคุณภาพที่แตกต่างกัน คือการขอให้เพื่อนของคุณวิจารณ์บีทแมพของคุณ คุณอาจต้องการถามเพื่อนที่อย่างน้อยมีประสบการณ์การทำบีทแมพเล็กน้อยเพื่อให้ได้ผลลัพธ์ที่ดีที่สุด
```

2021-07-22 14:59 UTC, Trigonoculus commented
> From my review, needing more review from other native like Trigonoculus or other cuz it has a lot to improve.

@HelloYeew ครั้งหน้า tag ผมในนี้ได้เลยครับ จะได้จัดการเร็ว ๆ เพราะว่านี่ก็เพิ่งบังเอิญมาเห็นเพราะเลื่อนลิสของ PR

2021-07-23 07:08 UTC, dumb-stuff commented on wiki/Guides/Getting_Your_Map_Modded/th.md
>  เพื่อที่จะให้บีทแมพของคุณถูก[จัดอันดับ](/wiki/Beatmap/Category#ranked)นั้น บีทแมพของคุณจะต้องผ่าน[การวิจารณ์บีทแมพ](/wiki/Modding)ก่อน มีหลายทางที่คุณสามารถขอให้คนตรวจสอบได้ดังนี้
@Trigonoculus ผมควรต้องใช้ "การวิจารณ์บีทแมพ" ไม่ใช่หรอครับ?

2021-07-23 07:10 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
>  เพื่อที่จะให้บีทแมพของคุณถูก[จัดอันดับ](/wiki/Beatmap/Category#ranked)นั้น บีทแมพของคุณจะต้องผ่าน[การวิจารณ์บีทแมพ](/wiki/Modding)ก่อน มีหลายทางที่คุณสามารถขอให้คนตรวจสอบได้ดังนี้
อ๋อใช่ครับ ใช้แทนกันได้ครับบ เปลี่ยนให้แล้ว

2021-07-23 07:21 UTC, Trigonoculus commented
@dumb-stuff เวลาแก้แต่ละอัน รบกวนกดเป็น `Add suggestion to batch` ทีครับ มันจะได้ไม่อีเมลมาหาผมทุกครั้งเลย

![image](https://user-images.githubusercontent.com/20501245/126749385-3bffc350-2e0c-4fb0-980a-a1c7b877f1b8.png)

2021-07-23 07:36 UTC, dumb-stuff commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +Beatmap Nominator ทุกคนมีข้อมูลการตรวจสอบบีทแมพในเกี่ยวกับ "ฉัน!" ไม่ว่าจะมีคิวการตรวจสอบบีทแมพหรือไม่ก็ตาม การถาม Beatmap Nominator โดยตรงนั้นแทบจะเป็นสิ่งจำเป็นสำหรับการเสนอชื่อบีทแมพของคุณ
ลองเปลี่ยน Nominate เป็นภาษาไทยได้ไหมครับ?

2021-07-23 07:38 UTC, dumb-stuff commented
> @dumb-stuff เวลาแก้แต่ละอัน รบกวนกดเป็น `Add suggestion to batch` ทีครับ มันจะได้ไม่อีเมลมาหาผมทุกครั้งเลย
> 
> ![image](https://user-images.githubusercontent.com/20501245/126749385-3bffc350-2e0c-4fb0-980a-a1c7b877f1b8.png)

ขอโทษด้วยครับ!

2021-07-23 07:39 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +Beatmap Nominator ทุกคนมีข้อมูลการตรวจสอบบีทแมพในเกี่ยวกับ "ฉัน!" ไม่ว่าจะมีคิวการตรวจสอบบีทแมพหรือไม่ก็ตาม การถาม Beatmap Nominator โดยตรงนั้นแทบจะเป็นสิ่งจำเป็นสำหรับการเสนอชื่อบีทแมพของคุณ
@dumb-stuff แก้แล้วครับ

2021-07-23 08:01 UTC, dumb-stuff commented
@TPGPL help me unblock this pull requests please :D

2021-07-23 11:54 UTC, TPGPL requested changes

2021-07-23 11:54 UTC, TPGPL commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +`#modreqs` ไม่ได้มีฟังก์ชันและฐานผู้ใช้เหมือนเมื่อก่อน แต่ยังคงเป็นวิธีที่มีประโยชน์ในการรับการวิจารณ์บีทแมพ ดังนั้นจึงคุ้มค่าที่จะลอง แม้ว่าในปัจจุบันจะมีคำขอ mod ปกติเป็นส่วนใหญ่ แต่ก็มักใช้สำหรับค
```suggestion
`#modreqs` ไม่ได้มีฟังก์ชันและฐานผู้ใช้เหมือนเมื่อก่อน แต่ยังคงเป็นวิธีที่มีประโยชน์ในการรับการวิจารณ์บีทแมพ ดังนั้นจึงคุ้มค่าที่จะลอง แม้ว่าในปัจจุบันจะมีคำขอ mod ปกติเป็นส่วนใหญ่ แต่ก็มักใช้สำหรับคำขอประเภทอื่น ๆ ที่กล่าวถึง[ข้างต้น](#รูปแบบของการวิจารณ์บีทแมพ)
```

2021-07-23 11:54 UTC, TPGPL commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +## รูปแบบของการวิจารณ์บีทแมพ
this header is still outdated

for reference:

```md
## Types of mods

Before looking for mods, you must first understand the different types of mod requests you can make. The two most commonly used are [normal mod requests](/wiki/Modding/Normal_mod) (NM req) and [mod for mod requests](/wiki/Modding/Mod_for_mod) (M4M req). These are not the only request types, though. There are a few other mod request types which are mainly used in `#modreqs`:

- **Beatmap Nominator request (BN req):** Used only in Beatmap Nominator queues or in `#modreqs`, a BN request is used when you believe your beatmap cannot be improved by regular mods anymore, and requires a more experienced check from a [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators).
- **Metadata check (Meta check):** Fairly self-explanatory, the [modder](/wiki/Modding/Modder) will check if the metadata of your beatmap is correct. Metadata is often checked in regular mods too.
- **Hitsound check:** The modder will check your beatmap to make sure that your hitsounding represents the song correctly, is consistent, and is up to ranking standards.
```

2021-07-28 05:13 UTC, dumb-stuff commented
@Trigonoculus Help me fix some typo please 😄

2021-07-28 12:47 UTC, dumb-stuff reviewed
I translated that part that @TPGPL request :D

2021-07-29 18:12 UTC, TPGPL approved these changes
looks up-to-date now, gonna wait for a review from a native speaker

2021-07-30 08:01 UTC, Trigonoculus requested changes
typos

2021-08-03 01:54 UTC, dumb-stuff reviewed
Looks good so far lol

2021-08-03 01:57 UTC, dumb-stuff commented
![image](https://user-images.githubusercontent.com/59832159/127945566-40538760-5cf7-4630-bba9-34a63492b066.png)
?????????????

2021-08-03 01:59 UTC, kj415j45 commented
this would happened when you push commit(s) after review. It's usual, don't worried.

2021-08-04 04:30 UTC, Trigonoculus requested changes
@TPGPL fine to go after this change

2021-08-04 04:30 UTC, Trigonoculus commented on wiki/Guides/Getting_Your_Map_Modded/th.md
> +*คำเตือน: อย่าส่งคำขอซ้ำ ๆ ในช่องนี้ คุณอาจจะโดนให้[เงียบ](wiki/Silence) ให้คุณทำการส่งคำขอประมาณชั่วโมงละครั้ง*
```suggestion
*คำเตือน: อย่าส่งคำขอซ้ำ ๆ ในช่องนี้ คุณอาจจะโดนให้[เงียบ](/wiki/Silence) ให้คุณทำการส่งคำขอประมาณชั่วโมงละครั้ง*
```
missing `/`

2021-08-04 11:35 UTC, TPGPL approved these changes

2021-08-04 11:35 UTC, merged