[ID] Add `Play Style/Hybrid`
ppy/osu-wiki pull request #5833
Opened 2021-07-13 11:29 UTC by Fhoxydeo

2021-07-13 12:48 UTC, wowcake requested changes

2021-07-13 12:48 UTC, wowcake commented on wiki/Play_style/Hybrid/id.md
> +**Hybrid** adalah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) yang di mana pemain menekan circle, menggeser slider, dan memutar spinner dengan menggunakan kombinasi dari [*single-tapping*](/wiki/
```suggestion
**Hybrid** adalah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) yang di mana pemain menekan circle, menggeser slider, dan memutar spinner dengan menggunakan kombinasi dari [*single-tapping*](/wiki/Play_style/Single-tapping) dan [*alternating*](/wiki/Play_style/Alternating). gaya ini dapat ditemukan dari semua pemain tingkat kemahiran dan keterampilan yang dibutuhkan untuk menggunakannya dapat bervariasi dari berbagai beatmap dan variasi ke variasi.
```

2021-07-13 12:48 UTC, wowcake commented on wiki/Play_style/Hybrid/id.md
> +**Hybrid** adalah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) yang di mana pemain menekan circle, menggeser slider, dan memutar spinner dengan menggunakan kombinasi dari [*single-tapping*](/wiki/
since it's a combination, you should remove the "/atau"

2021-07-13 12:48 UTC, wowcake commented on wiki/Play_style/Hybrid/id.md
> +- Beberapa pemain hybrid menekan [*hit object*](/wiki/Hit_object) dengan menekan antara tombol mereka single-tap (`Z` dan `X` secara default) secara berkala di seluruh beatmap. Sementara juga alterna
```suggestion
- Beberapa pemain hybrid menekan [*hit object*](/wiki/Hit_object) dengan menekan antara tombol mereka single-tap (`Z` dan `X` secara default) secara berkala di seluruh beatmap. Sementara juga alternating pada [*stack*](/wiki/Mapping_Techniques/Stack) bila memungkinkan.
```

2021-07-13 12:48 UTC, wowcake commented on wiki/Play_style/Hybrid/id.md
> +- Beberapa pemain hybrid menekan [*hit object*](/wiki/Hit_object) dengan menekan antara tombol mereka single-tap (`Z` dan `X` secara default) secara berkala di seluruh beatmap. Sementara juga alterna
remember to remove pronoun if there's one in an untranslated/original term @_@

2021-07-15 04:43 UTC, ZeroPyrozen commented on wiki/Play_style/Hybrid/id.md
> +  -gaya bermain
```suggestion
  - gaya bermain
```

2021-07-15 04:51 UTC, ZeroPyrozen requested changes

2021-07-15 04:51 UTC, ZeroPyrozen commented on wiki/Play_style/Hybrid/id.md
> +**Hybrid** adalah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) yang di mana pemain menekan circle, menggeser slider, dan memutar spinner dengan menggunakan kombinasi dari [*single-tapping*](/wiki/
```suggestion
**Hybrid** adalah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) yang dimana pemain menekan circle, menggeser slider, dan memutar spinner dengan menggunakan kombinasi dari [*single-tapping*](/wiki/Play_style/Single-tapping) dan [*alternating*](/wiki/Play_style/Alternating). Gaya ini dapat ditemukan dari semua pemain tingkat kemahiran dan keterampilan yang dibutuhkan untuk menggunakannya dapat bervariasi dari berbagai beatmap dan variasi ke variasi.
```

2021-07-15 04:51 UTC, ZeroPyrozen commented on wiki/Play_style/Hybrid/id.md
> +  -gaya bermain
```suggestion
  - gaya bermain
```

2021-07-15 04:51 UTC, ZeroPyrozen commented on wiki/Play_style/Hybrid/id.md
> +- Beberapa pemain hybrid menekan [*hit object*](/wiki/Hit_object) dengan menekan antara tombol mereka single-tap (`Z` dan `X` secara default) secara berkala di seluruh beatmap. Sementara juga alterna
```suggestion
- Beberapa pemain hybrid menekan [*hit object*](/wiki/Hit_object) dengan menekan antara tombol mereka single-tap (`Z` dan `X` secara default) secara berkala pada beatmap. Sementara juga alternating pada [*stack*](/wiki/Mapping_Techniques/Stack) bila memungkinkan.
```

2021-07-15 04:51 UTC, ZeroPyrozen commented on wiki/Play_style/Hybrid/id.md
> +- Beberapa pemain hybrid menggunakan kombinasi dari alternating dan single-tapping tergantung pada kecepatan sebuah beatmap: beberapa kecepatan lebih mudah untuk detekan dengan singletapping daripada
```suggestion
- Beberapa pemain hybrid menggunakan kombinasi dari alternating dan single-tapping tergantung pada kecepatan sebuah beatmap: beberapa kecepatan lebih mudah untuk detekan dengan singletapping daripada alternating dan banyak pemain hybrid mengakomodasi untuk itu. Kecepatan dimana ini bervariasi dari pemain ke pemain.
```

2021-07-15 10:59 UTC, ZeroPyrozen approved these changes
All good 👍

2021-07-15 12:18 UTC, wowcake approved these changes
👍

2021-07-16 16:34 UTC, TPGPL approved these changes

2021-07-16 16:34 UTC, merged