Add `o!ET 2021` tournament article
ppy/osu-wiki pull request #5838
Opened 2021-07-15 11:57 UTC by fajar13k

- Add osu! European Tournament 2021 tournament article
- Tournament already ended

2021-07-15 18:14 UTC, TPGPL requested changes

2021-07-15 18:14 UTC, TPGPL commented on wiki/Tournaments/o!ET/2021/en.md
> +2. Only players from the Europe region may sign up to the tournament. Participants may find a list of European countries through [following link](https://en.wikipedia.org/wiki/List_of_European_countr
```suggestion
2. Only players from the Europe region may sign up to the tournament. Participants may find a list of European countries through [following link](https://en.wikipedia.org/wiki/List_of_European_countries_by_area "Wikipedia"). If they wish to enter the tournament while the flag of their profile page has isn't listed here, participants can contact the host through Discord DMs to discuss the matter.
```

2021-07-15 18:14 UTC, TPGPL commented on wiki/Tournaments/o!ET/2021/en.md
> +### Match procedures & Mappols format
```suggestion
### Match procedures & Mappools format
```

2021-07-15 19:24 UTC, Walavouchey requested changes
Bit of a writing pass. Tournament rules do seem to get very long-winded...

Additionally, please replace all occurrences of `’` (right single quotation mark) with `'` (apostrophe)

2021-07-15 19:24 UTC, Walavouchey commented on wiki/Tournaments/o!ET/2021/en.md
> +   - The Finals and the Grand Finals: Best-Of-13 (First to 7 points wins), 2 bans per team. Pool format: 8FM/5FO/5DT/3TB.
```suggestion
   - The Round of 16 and the Quarterfinals: Best of 9 (first to 5 points wins), 1 ban per team. Pool format: 5FM/3FO/3DT/3TB.
   - The Semifinals: Best of 11 (first to 6 points wins), 2 bans per team. Pool format: 7FM/4FO/4DT/3TB.
   - The Finals and the Grand Finals: Best of 13 (first to 7 points wins), 2 bans per team. Pool format: 8FM/5FO/5DT/3TB.
```

2021-07-15 19:24 UTC, Walavouchey commented on wiki/Tournaments/o!ET/2021/en.md
> +   - Each team can call for an abort one time per match.
```suggestion
8. Disconnections and aborts can only be made up to 30 seconds after a map’s start for a replay of that map. After 30 seconds, the map **will not** be aborted, and the team that wasn’t affected by the abort decides whether they wish to replay the map or not. Each team can call for an abort one time per match.
```

2021-07-16 13:08 UTC, TPGPL requested changes

2021-07-16 13:08 UTC, TPGPL approved these changes

2021-07-16 13:12 UTC, merged