[ID] Add `Play Style/Single-tapping`
ppy/osu-wiki pull request #5839
Opened 2021-07-15 14:20 UTC by Fhoxydeo

2021-07-18 05:37 UTC, hikikuman requested changes

2021-07-18 05:37 UTC, hikikuman commented on wiki/Play_style/Single-tapping/id.md
> +**Single-tapping** adalah gaya tapping untuk [osu!](/wiki/Game_mode/osu!) yang dimana pemain menekan circle, menggeser slider, dan memutar spinner dengan hanya menggunakan satu tombol di keyboard mer
```suggestion
**Single-tapping** adalah gaya tapping pada mode permainan [osu!](/wiki/Game_mode/osu!) yaitu pemain menekan circle, menggeser slider, dan memutar spinner dengan hanya menggunakan satu tombol di keyboard mereka (secara default adalah tombol `Z` atau `X`). Gaya ini merupakan gaya yang paling umum digunakan oleh para pemain dari semua tingkat kesulitan dan yang paling mudah untuk diadaptasi.
```

2021-07-18 05:37 UTC, hikikuman commented on wiki/Play_style/Single-tapping/id.md
> +Meski namanya single-tapping, sebagian besar pemain single-tap tidak selalu menekan dengan satu tombol.Sebagian besar lebih suka menekan semua secara singletap kecuali [*stream*](/wiki/Beatmap/Patter
```suggestion
Meski namanya single-tapping, sebagian besar pemain single-tap tidak selalu menekan hanya dengan satu tombol saja. Sebagian besar pemain lebih suka menekan semua secara single-tap kecuali [stream](/wiki/Beatmap/Pattern/Stream), [stack](/wiki/Mapping_Techniques/Stack), dan burst stream yang cepat. Dalam hal ini, para pemain akan lebih memilih untuk [alternate](/wiki/Play_style/Alternating) dan/atau [double tap](/wiki/Play_style/Double_tapping).
```
gaperlu dibuat garis miring, cmiiw.

2021-07-18 05:37 UTC, hikikuman commented on wiki/Play_style/Single-tapping/id.md
> +Argumen yang mendukung single-tapping biasanya berpendapat bahwa lebih mudah untuk konsisten karena -untuk semua tujuan dan maksud- hanya satu jari saja yang bermain. Dan biasanya inilah alasannya(sa
```suggestion
Argumen yang mendukung single-tapping biasanya berpendapat bahwa lebih mudah untuk konsisten karena -untuk semua tujuan dan maksud- hanya satu jari saja yang bermain. Dan biasanya inilah alasannya (sadar atau tidak) beberapa pemain baru menggunakan metode ini.
```

2021-07-18 05:37 UTC, hikikuman commented on wiki/Play_style/Single-tapping/id.md
> +Dengan cara yang sama, banyak pemain beranggapan bahwa single-tapping lebih lambat karena ada penundaan yang diperlukan sebelum Anda dapat menekan jari yang sama , sementara yang lain beranggapan den
```suggestion
Dengan cara yang sama, banyak pemain beranggapan bahwa single-tapping lebih lambat karena ada penundaan yang diperlukan sebelum kamu dapat menekan jari yang sama, sementara yang lain beranggapan dengan hanya menggunakan satu jari dapat menyebabkan pengguna kelelahan dalam waktu yang cukup cepat.
```

2021-07-19 10:22 UTC, Fhoxydeo commented on wiki/Play_style/Single-tapping/id.md
> +Meski namanya single-tapping, sebagian besar pemain single-tap tidak selalu menekan dengan satu tombol.Sebagian besar lebih suka menekan semua secara singletap kecuali [*stream*](/wiki/Beatmap/Patter
kalo ama niva kemarin dikasih garis miring

2021-07-19 14:59 UTC, mousesalt commented on wiki/Play_style/Single-tapping/id.md
> +**Single-tapping** adalah gaya tapping pada mode permainan [osu!](/wiki/Game_mode/osu!) yaitu pemain menekan circle, menggeser slider, dan memutar spinner dengan hanya menggunakan satu tombol di keyb
```suggestion
**Single-tapping** adalah gaya tapping pada mode permainan [osu!](/wiki/Game_mode/osu!) yaitu pemain menekan circle, menggeser slider, dan memutar spinner dengan hanya menggunakan satu tombol di keyboard mereka (secara default adalah tombol `Z` atau `X`). Gaya ini paling umum digunakan oleh para pemain dari semua tingkat kesulitan dan yang paling mudah untuk diadaptasi.
```

2021-07-19 14:59 UTC, mousesalt commented on wiki/Play_style/Single-tapping/id.md
> +**Single-tapping** adalah gaya tapping pada mode permainan [osu!](/wiki/Game_mode/osu!) yaitu pemain menekan circle, menggeser slider, dan memutar spinner dengan hanya menggunakan satu tombol di keyb
unused iteration

2021-07-19 14:59 UTC, mousesalt commented on wiki/Play_style/Single-tapping/id.md
> +Meski namanya single-tapping, sebagian besar pemain single-tap tidak selalu menekan dengan satu tombol.Sebagian besar lebih suka menekan semua secara singletap kecuali [*stream*](/wiki/Beatmap/Patter
```suggestion
Meski namanya single-tapping, sebagian besar pemain single-tap tidak selalu menekan dengan satu tombol. Sebagian besar pemain lebih suka menekan semua secara single-tap kecuali [*stream*](/wiki/Beatmap/Pattern/Stream), [*stack*](/wiki/Mapping_Techniques/Stack), dan *burst* yang cepat. Dalam hal ini, pemain akan sering memilih untuk melakukan [*alternate*](/wiki/Play_style/Alternating) dan/atau [*double tap*](/wiki/Play_style/Double_tapping).
```

2021-07-19 14:59 UTC, mousesalt commented on wiki/Play_style/Single-tapping/id.md
> +Argumen yang mendukung single-tapping biasanya berpendapat bahwa lebih mudah untuk konsisten karena -untuk semua tujuan dan maksud- hanya satu jari saja yang bermain. Dan biasanya inilah alasannya (s
```suggestion
Argumen yang mendukung single-tapping biasanya berpendapat bahwa lebih mudah konsisten karena—untuk semua tujuan dan maksud—hanya satu jari saja yang bermain. Dan biasanya inilah alasannya (sadar atau tidak) banyak pemain baru menggunakan metode ini.
```

2021-07-19 14:59 UTC, mousesalt commented on wiki/Play_style/Single-tapping/id.md
> +Argumen yang mendukung single-tapping biasanya berpendapat bahwa lebih mudah untuk konsisten karena -untuk semua tujuan dan maksud- hanya satu jari saja yang bermain. Dan biasanya inilah alasannya (s
reviewed, does think it a bit confused

2021-07-23 03:15 UTC, hikikuman approved these changes
👍

2021-07-25 05:51 UTC, mousesalt approved these changes

2021-07-27 03:13 UTC, wowcake approved these changes

2021-07-29 18:04 UTC, TPGPL approved these changes

2021-07-29 18:04 UTC, merged