[FR] Update `Game mode`
ppy/osu-wiki pull request #5844
Opened 2021-07-17 13:16 UTC by DoryanR

Proposal to update the French translation of the wiki page `Game mode`.

2021-07-17 18:23 UTC, DoryanR commented on wiki/Game_mode/fr.md
> +Le mode de jeu par défaut est osu!. Cependant, au démarrage, osu! s'ouvrira avec le mode de jeu qui a été sélectionné en dernier. Pour passer d'un mode de jeu à l'autre, le joueur peut soit cliquer s
```suggestion
Le mode de jeu par défaut est osu!. Cependant, au démarrage, osu! s'ouvrira avec le mode de jeu qui a été sélectionné en dernier. Pour passer d'un mode de jeu à l'autre, le joueur peut soit cliquer sur le bouton `Mode` en bas de l'écran de sélection des chansons, soit appuyer sur les touches `Ctrl` + `1`, `Ctrl` + `2`, `Ctrl` + `3`, ou `Ctrl` + `4` pour passer respectivement de osu! à osu!taiko, osu!catch, et osu!mania.
```

2021-07-17 21:37 UTC, Ganondorf-1 requested changes

2021-07-17 21:37 UTC, Ganondorf-1 commented on wiki/Game_mode/fr.md
> +Chaque mode de jeu a sa propre icône/symbole : ![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania] (osu!, osu!taiko, osu!catch, et osu!mania respectivement).
```suggestion
Chaque mode de jeu a sa propre icône : ![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania] (osu!, osu!taiko, osu!catch, et osu!mania respectivement).
```

2021-07-17 21:37 UTC, Ganondorf-1 commented on wiki/Game_mode/fr.md
> +Le mode de jeu par défaut est osu!. Cependant, au démarrage, osu! s'ouvrira avec le mode de jeu qui a été sélectionné en dernier. Pour passer d'un mode de jeu à l'autre, le joueur peut soit cliquer s
```suggestion
Le mode de jeu par défaut est osu!. Cependant, au démarrage, osu! s'ouvrira avec le mode de jeu qui a été sélectionné en dernier. Pour passer d'un mode de jeu à un autre, le joueur peut soit cliquer sur le bouton `Mode` en bas de l'écran de sélection de beatmaps, soit appuyer sur les touches `Ctrl` + `1`, `Ctrl` + `2`, `Ctrl` + `3`, ou `Ctrl` + `4` pour basculer entre les modes osu!, osu!taiko, osu!catch, et osu!mania respectivement.
```

2021-07-17 21:37 UTC, Ganondorf-1 commented on wiki/Game_mode/fr.md
> +*osu!* est le mode de jeu par défaut du client d'osu! et est basé sur le jeu vidéo rythmique original [iNiS'](https://fr.wikipedia.org/wiki/INiS "Wikipédia") *[Osu! Tatakae! Ouendan](https://fr.wikip
```suggestion
*osu!* est le mode de jeu par défaut du client d'osu! et est basé sur le jeu de rythme original *[Osu! Tatakae! Ouendan](https://fr.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan "Wikipédia")* par [iNiS](https://fr.wikipedia.org/wiki/INiS "Wikipédia"). Sur osu!, le joueur doit cliquer sur des cercles, tenir des sliders et faire tourner des spinners au rythme des chansons.
```

2021-07-17 21:37 UTC, Ganondorf-1 commented on wiki/Game_mode/fr.md
> +*osu!catch* est vaguement basé sur un mini-jeu à l'intérieur d'un simulateur [Beatmania](https://fr.wikipedia.org/wiki/Beatmania "Wikipédia"), qui lui-même est censé être basé sur le mode *EZ2CATCH*
```suggestion
*osu!catch* est vaguement basé sur un mini-jeu à l'intérieur d'un simulateur [Beatmania](https://fr.wikipedia.org/wiki/Beatmania "Wikipédia"), qui lui-même est censé être basé sur le mode *EZ2CATCH* de la série [EZ2DJ](https://en.wikipedia.org/wiki/EZ2DJ "Wikipédia (en anglais)"). Le mode de jeu consiste en des fruits de différentes variétés tombant du haut de l'écran et un "attrapeur" tenant une assiette pour attraper les fruits.
```

2021-07-17 21:37 UTC, Ganondorf-1 commented on wiki/Game_mode/fr.md
> +*osu!mania* est basé sur une variété de jeux de rythme de type tapis roulant (notamment [Dance Dance Revolution](https://fr.wikipedia.org/wiki/Dance_Dance_Revolution "Wikipédia") et Beatmania). Le mo
```suggestion
*osu!mania* est basé sur une variété de jeux de rythme à base de notes défilant sur l'écran (notamment [Dance Dance Revolution](https://fr.wikipedia.org/wiki/Dance_Dance_Revolution "Wikipédia") et Beatmania). Le mode de jeu a été principalement introduit et mis en œuvre par [woc2006](https://osu.ppy.sh/users/1105845), et est conçu pour imiter la sensation d'un vrai piano grâce à l'utilisation des touches du clavier.
```

2021-07-20 10:02 UTC, Ganondorf-1 approved these changes

2021-07-22 14:39 UTC, TPGPL approved these changes

2021-07-22 14:39 UTC, merged