[FR] Update `Game modifier/No Fail`
ppy/osu-wiki pull request #5848
Opened 2021-07-17 18:00 UTC by DoryanR

Proposal to update the French translation of the wiki page `No Fail`.

2021-07-17 21:17 UTC, Ganondorf-1 requested changes

2021-07-17 21:17 UTC, Ganondorf-1 commented on wiki/Game_modifier/No_Fail/fr.md
>  Le mod **No Fail** est un [modificateur de jeu](/wiki/Game_modifier) qui empêche le joueur d'échouer sur les [beatmaps](/wiki/Beatmap). L'activation du mod No Fail rend le joueur incapable d'échouer
```suggestion
Le mod **No Fail** est un [modificateur de jeu](/wiki/Game_modifier) qui empêche le joueur d'échouer sur les [beatmaps](/wiki/Beatmap). L'activation du mod No Fail rend le joueur incapable d'échouer sur une [beatmap](/wiki/Beatmap) même si la [barre de vie](/wiki/Glossary/Health_bar) tombe à zéro. Cependant, si le joueur n'a obtenu aucun point durant la partie, le score ne sera pas envoyé.
```

2021-07-17 21:17 UTC, Ganondorf-1 commented on wiki/Game_modifier/No_Fail/fr.md
> +À partir du 16 janvier 2021, le mod No Fail peut entraîner une certaine pénalité sur le nombre de [points de performance](/wiki/Performance_Points) qu'un joueur gagne en fonction du nombre de miss qu
```suggestion
Depuis le 16 janvier 2021, le mod No Fail peut entraîner une certaine pénalité sur le nombre de [points de performance](/wiki/Performance_Points) qu'un joueur gagne en fonction du nombre de miss qu'il obtient. À partir d'une valeur de base de 1,0x (100%), chaque miss diminuera le multiplicateur de gain de points de performance de -0,02x (0,5%) jusqu'à un maximum de 0,9x (90%). <!-- pp change newspost : https://osu.ppy.sh/home/news/2021-01-14-performance-points-updates -->
```

2021-07-20 09:57 UTC, Ganondorf-1 approved these changes

2021-07-22 14:46 UTC, TPGPL approved these changes

2021-07-22 14:48 UTC, merged