[FR] Update `Help centre`, add `Account` and `Beatmapping`
ppy/osu-wiki pull request #5850
Opened 2021-07-18 12:41 UTC by DoryanR

Proposal to update the French translation of the wiki page `Help centre`.

Translation of the following wiki pages:

- `Help_Centre/Account`
- `Help_Centre/Beatmapping`

2021-07-18 16:09 UTC, DoryanR commented on wiki/Help_Centre/fr.md
> +3. Tapez `release` dans la barre de recherche rapide. Vous accéderez ainsi à la version que votre client utilise.
```suggestion
3. Tapez `release` dans la barre de recherche rapide. Vous accéderez ainsi au canal de mises à jour que votre client utilise.
```

2021-07-18 16:09 UTC, DoryanR commented on wiki/Help_Centre/fr.md
> +5. Cliquez sur le bouton de redémarrage qui apparaît en bas de l'écran si vous avez apporté des modifications à la version du jeu pour les appliquer.
```suggestion
5. Cliquez sur le bouton de redémarrage qui apparaît en bas de l'écran si vous avez apporté des modifications au canal de mises à jour pour les appliquer.
```

2021-07-19 16:00 UTC, DoryanR commented on wiki/Help_Centre/Beatmapping/fr.md
> +*Page principale : [Help centre](/wiki/Help_Centre)*
```suggestion
*Page principale : [Centre d'aide](/wiki/Help_Centre)*
```

2021-07-21 23:45 UTC, Ganondorf-1 requested changes

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Si ce joueur **a** un jeu dans tous les modes de jeu, une [fonction non linéaire](https://www.desmos.com/calculator/b89siyv9j8 "Desmos graph") est utilisée pour calculer combien de temps supplémentai
```suggestion
Si ce joueur a joué au moins une partie parmi tous les modes de jeu, une [fonction non linéaire](https://www.desmos.com/calculator/b89siyv9j8 "Graphique Desmos") est utilisée pour calculer combien de temps supplémentaire est ajouté à ces 6 mois. Cela permet d'éviter que des personnes volent les noms d'utilisateur de joueurs actifs ou qui ont arrêté récemment.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Nous accordons des annulations gratuites pour l'ancien nom d'utilisateur direct d'un utilisateur. Il suffit de contacter [accounts@ppy.sh](mailto:accounts@ppy.sh) et de demander l'annulation de votre
```suggestion
Nous accordons aux utilisateurs de retourner gratuitement à leur précédent nom d'utilisateur. Il suffit de nous contacter à l'addresse [accounts@ppy.sh](mailto:accounts@ppy.sh) et de demander l'annulation de votre dernier changement de nom.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Les modifications de tout autre nom antérieur doivent être [achetées via le magasin](https://osu.ppy.sh/store/products/32).
```suggestion
Le retour à tout autre nom d'utilisateur antérieur doit être [acheté via le magasin](https://osu.ppy.sh/store/products/32).
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Si vous constatez que votre récent changement de nom a été annulé, c'est peut-être parce que le nom d'utilisateur que vous avez changé était abusif, inapproprié ou considéré comme offensant. Nous n'e
```suggestion
Si vous constatez que votre récent changement de nom a été annulé, c'est peut-être parce que le nom d'utilisateur que vous avez changé était abusif, inapproprié ou considéré comme offensant. Nous n'effectuerons pas le changement à nouveau même si vous le demandez, mais si vous l'avez acheté via l'osu!store, nous vous offrirons un changement gratuit pour le remplacer.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Votre profil affichera tous vos précédents changements de nom achetés, mais nous ne supprimons que de manière sélective ceux qui peuvent poser problème pour vous. Si l'un de vos anciens noms d'utilis
```suggestion
Votre profil affichera tous vos précédents noms d'utilisateur, mais nous ne supprimons que de manière sélective ceux qui peuvent poser problème pour vous. Si l'un de vos anciens noms d'utilisateur porte atteinte à votre vie privée (par exemple, s'il contient votre nom légal) ou peut mener à une atteinte à votre vie privée (via d'autres sites web), veuillez nous contacter via l'adresse [accounts@ppy.sh](mailto:accounts@ppy.sh) pour demander sa suppression.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +**Nous pouvons changer cela pour vous, mais seulement si vous vivez activement dans le pays vers lequel vous souhaitez changer.**
```suggestion
**Nous pouvons changer cela pour vous, mais seulement si vous vivez activement dans le pays pour lequel vous souhaitez changer.**
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Nous déterminons votre pays, tel qu'il apparaît sur votre page de profil, à partir de la région dans laquelle vous avez enregistré votre compte pour la première fois.
```suggestion
Nous déterminons votre pays, tel qu'il apparaît sur votre page de profil, à partir de la région dans laquelle vous avez créé votre compte.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +L'équipe d'assistance peut volontiers changer le pays de votre compte sur demande, **mais uniquement si vous vivez activement dans ce pays à ce moment-là**.
```suggestion
L'équipe du support peut volontiers changer le pays de votre compte sur demande, **mais uniquement si vous vivez activement dans ce pays à ce moment-là**.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +D'autres jeux rencontrent souvent ce problème avec ce que l'on appelle les "smurfs" - des comptes avec des temps de jeu et des totaux faibles qui gonflent les classements et empêchent les autres util
```suggestion
D'autres jeux rencontrent souvent ce problème avec ce que l'on appelle les "smurfs" - des comptes avec des temps de jeu faibles qui remplissent les classements et empêchent les autres utilisateurs de jouer de manière compétitive.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Chez osu!, nous sommes très opposés à ce que les utilisateurs aient plusieurs comptes, et nous appliquons une règle stricte : un seul compte par personne, pour toujours. Vous pouvez jouer sur le prem
```suggestion
Sur osu!, nous sommes très opposés à ce que les utilisateurs aient plusieurs comptes, et nous appliquons une règle stricte : un seul compte par personne, pour toujours. Vous pouvez jouer sur le premier compte que vous avez créé chez nous, et c'est tout !
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Si vous avez actuellement plus d'un compte, veuillez contacter [accounts@ppy.sh](mailto:accounts@ppy.sh) pour mettre les choses au point.
```suggestion
Si vous avez actuellement plus d'un compte, veuillez nous contacter à l'adresse [accounts@ppy.sh](mailto:accounts@ppy.sh) pour mettre les choses au point.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Nous envisageons des achats supplémentaires de 'remise à zéro du score' dans la boutique osu! pour les joueurs les plus acharnés qui ne souhaitent rien d'autre que la perfection dans leurs statistiqu
```suggestion
Nous envisageons des achats supplémentaires de 'remise à zéro du score' dans l'osu!store pour les joueurs les plus acharnés qui ne souhaitent rien d'autre que la perfection dans leurs statistiques, mais en l'état actuel des choses, nous ne pouvons pas effacer les statistiques d'un compte pour vous.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Si vous jouez depuis un lieu public, veillez à surveiller de près la sécurité de votre compte. Les ordinateurs partagés sont souvent des cibles de choix pour les logiciels malveillants..
```suggestion
Si vous jouez depuis un lieu public, veillez à surveiller de près la sécurité de votre compte. Les ordinateurs partagés sont souvent des cibles de choix pour les logiciels malveillants.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +### Puis-je obtenir une liste de toutes les cartes que j'ai jouées ou téléchargées ?
```suggestion
### Puis-je obtenir une liste de toutes les beatmaps que j'ai jouées ou téléchargées ?
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +**You can see all maps you've played on the website.**
```suggestion
**Vous pouvez voir toutes les beatmaps que vous avez jouées sur le site web.**
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +**Si vous avez un tag de supporter actif**, vous pouvez voir toutes les maps pour lesquelles vous avez soumis un score en allant sur la page [liste des beatmaps](https://osu.ppy.sh/beatmapsets), en c
```suggestion
**Si vous avez un tag de supporter actif**, vous pouvez voir toutes les maps sur lesquelles vous avez envoyé un score en allant sur la page [liste des beatmaps](https://osu.ppy.sh/beatmapsets), en cliquant sur `Plus de critères de recherche`, puis en sélectionnant le filtre `Jouée`. Vous pouvez également utiliser [ce lien](https://osu.ppy.sh/beatmapsets?played=played) pour accéder directement à la page filtrée.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Malheureusement, nous ne gardons pas de traces de toutes les maps qu'un utilisateur a téléchargées, il est donc impossible d'en obtenir une liste. Le plus proche que vous puissiez faire serait d'util
```suggestion
Malheureusement, nous ne gardons pas de traces de toutes les maps qu'un utilisateur a téléchargées, il est donc impossible d'en obtenir une liste. Le plus proche que vous puissiez faire serait d'utiliser le filtre susmentionné pour récupérer au moins les maps que vous avez déjà joué.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Pour télécharger votre beatmap, allez dans l'éditeur et aller dans `Fichier` > `Publier la beatmap...`.
```suggestion
Pour télécharger votre beatmap, allez dans l'éditeur et allez dans `Fichier` > `Publier la beatmap...`.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Votre beatmap pourra ainsi être téléchargé sur le site web. La mise à jour d'une map est le même processus que pour une map déjà téléchargée.
```suggestion
Votre beatmap pourra ainsi être téléchargée sur le site web. La mise à jour d'une map est le même processus que pour une map déjà téléchargée.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Chaque utilisateur a un nombre limité de map qu'il peut télécharger simultanément. Si vous laissez une map inactive pendant un mois (28 jours), sans la mettre à jour, elle sera envoyée au [Cimetière]
```suggestion
Chaque utilisateur a un nombre limité de maps qu'il peut télécharger simultanément. Si vous laissez une map inactive pendant un mois (28 jours), sans la mettre à jour, elle sera envoyée au [Cimetière](/wiki/Graveyard) des beatmaps. Pour faire revivre une beatmap du cimetière dans un statut En attente ou Work In Progress, mettez-la à jour.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +## L'éditeur me dit : "La beatmap que vous essayez de soumettre n'est pas la vôtre !"
Le message est traduit en français sur le jeu ?

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Si ce n'est pas le cas, changez-le manuellement pour chaque difficulté de votre beatmap, rechargez la beatmap, et vous devriez pouvoir la soumettre.
```suggestion
Si ce n'est pas le cas, changez-le manuellement pour chaque difficulté de votre beatmap, rechargez la beatmap, et vous devriez pouvoir la publier.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Si vous rencontrez toujours des problèmes ou si vous souhaitez plus d'informations à ce sujet, consultez la page [BSS issues](/wiki/Guides/BSS_Issues).
```suggestion
Si vous rencontrez toujours des problèmes ou si vous souhaitez plus d'informations à ce sujet, consultez la page [Problèmes avec le BSS](/wiki/Guides/BSS_Issues).
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +**L'équipe ne prend pas en compte les demandes de suppression manuelle des beatmaps téléchargés.**
```suggestion
**L'équipe ne prend pas en compte les demandes de suppression manuelle des beatmaps publiées.**
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Vous pouvez supprimer vous-même votre beatmap en attendant qu'il se désintègre dans le cimetière des beatmap, ce qu'il fera après un mois (28 jours) sans mise à jour.
```suggestion
Vous pouvez supprimer vous-même votre beatmap lorsqu'elle tombe dans le cimetière des beatmaps, ce qui se passera après un mois (28 jours) sans mise à jour.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Une fois que votre beatmap se trouve au cimetière, vous pouvez le supprimer vous-même en vous rendant sur la [page de discussion](/wiki/Beatmap_Discussion) de votre beatmap et en cliquant sur le bout
```suggestion
Une fois que votre beatmap se trouve au cimetière, vous pouvez la supprimer vous-même en vous rendant sur la [page de discussion](/wiki/Beatmap_Discussion) de votre beatmap et en cliquant sur le bouton `Supprimer` qui apparaît sur le côté droit de l'écran après avoir fait défiler la page.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +| [Site web](/wiki/Help_Centre/Website) | Blocage des utilisateurs, contact avec le support, apparence du site |
```suggestion
| [Site web](/wiki/Help_Centre/Website) | Blocage des utilisateurs, contacter le support, apparence du site |
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +8. Sélectionnez le fichier log requis (le représentant du service d'assistance vous indiquera lequel) et joignez-le à votre ticket d'assistance ou à votre message de forum.
```suggestion
8. Sélectionnez le fichier log requis (le membre de l'équipe du support vous indiquera lequel) et joignez-le à votre mail au support ou à votre message forum.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +**L'Observateur d'événements est un composant intégré de Windows qui peut être utilisé pour trouver des journaux de pannes lorsque osu! ne vous en fournit pas. Ces journaux d'incidents peuvent être u
```suggestion
**L'Observateur d'événements est un composant intégré de Windows qui peut être utilisé pour trouver des crash logs lorsqu'osu! ne vous en fournit pas. Ces logs peuvent être utilisés pour aider à déterminer la cause de votre problème.**
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +Lorsque vous avez des problèmes de plantage d'osu!, si osu! ne vous donne pas un journal de plantage, le seul endroit où vous pouvez en trouver un est l'Observateur d'événements.
```suggestion
Lorsque vous avez des problèmes de plantage d'osu!, si osu! ne vous donne pas de crash log, le seul endroit où vous pouvez en trouver un est l'Observateur d'événements.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +Si un membre de l'équipe d'assistance vous a demandé de trouver un journal de panne dans l'Observateur d'événements, voici comment procéder :
```suggestion
Si un membre de l'équipe du support vous a demandé de trouver un crash log dans l'Observateur d'événements, voici comment procéder :
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +1. Après que osu! ait planté, appuyez sur `Win` + `R` pour ouvrir une fenêtre Exécuter.
```suggestion
1. Après qu'osu! ait planté, appuyez sur `Win` + `R` pour ouvrir une fenêtre Exécuter.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +8. Copiez le texte qui s'y trouve et collez-le dans votre ticket d'assistance ou votre message de forum.
```suggestion
8. Copiez le texte qui s'y trouve et collez-le dans votre mail au support ou votre message forum.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +Lorsque vous êtes confrontés à des problèmes de performance dans osu!, la Frame Time Graph est un bon outil pour nous aider à diagnostiquer le problème et vous aider à trouver une solution.
```suggestion
Lorsque vous êtes confrontés à des problèmes de performance sur osu!, le Frame Time Graph est un bon outil pour nous aider à diagnostiquer le problème et vous aider à trouver une solution.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +**La Frame Time Graph est une fonctionnalité d'osu! qui peut nous aider à recueillir des informations plus utiles sur les problèmes de performance que vous pouvez rencontrer.**
```suggestion
**Le Frame Time Graph est une fonctionnalité d'osu! qui peut nous aider à recueillir des informations plus utiles sur les problèmes de performance que vous pouvez rencontrer.**
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +Si un membre de l'équipe d'assistance vous a demandé de prendre une vidéo ou une capture d'écran avec la Frame Time Graph, voici comment procéder :
```suggestion
Si un membre de l'équipe du support vous a demandé de prendre une vidéo ou une capture d'écran avec le Frame Time Graph, voici comment procéder :
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +4. Faites une capture d'écran en appuyant sur `Shift` + `F12`. Ceci téléchargera la capture d'écran sur les serveurs d'osu! et ouvrira la capture d'écran dans un onglet du navigateur web.
```suggestion
4. Faites une capture d'écran en appuyant sur `Shift` + `F12`. Cela publiera la capture d'écran sur les serveurs d'osu! et ouvrira la capture d'écran dans un onglet du navigateur web.
```

2021-07-21 23:45 UTC, Ganondorf-1 commented on wiki/Help_Centre/fr.md
> +5. Copiez et collez le lien fourni dans votre ticket d'assistance ou votre message de forum.
```suggestion
5. Copiez et collez le lien fourni dans votre mail au support ou votre message forum.
```

2021-07-22 07:59 UTC, DoryanR commented on wiki/Help_Centre/Beatmapping/fr.md
> +## L'éditeur me dit : "La beatmap que vous essayez de soumettre n'est pas la vôtre !"
Aucune idée, faudrait faire un test, mais je sais pas trop comment

2021-07-22 08:03 UTC, DoryanR commented on wiki/Help_Centre/Beatmapping/fr.md
> +## L'éditeur me dit : "La beatmap que vous essayez de soumettre n'est pas la vôtre !"
C'est bon j'ai trouver la bonne traduction du coup x)

2021-07-22 08:04 UTC, DoryanR commented on wiki/Help_Centre/Beatmapping/fr.md
> +## L'éditeur me dit : "La beatmap que vous essayez de soumettre n'est pas la vôtre !"
```suggestion
## L'éditeur me dit : "Vous n'êtes pas le propriétaire de la beatmap que vous essayez de publier !"
```

2021-07-26 04:48 UTC, Ganondorf-1 requested changes

2021-07-26 04:48 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Veillez à inclure tous les reçus que vous avez reçus au cours du processus (identifiants de transaction PayPal, reçus Xsolla, etc.) - ils nous aident beaucoup à retrouver ce qui est arrivé à votre pa
```suggestion
Veillez à inclure tous les reçus que vous avez pu avoir au cours du processus (identifiants de transaction PayPal, reçus Xsolla, etc.) - ils nous aident beaucoup à retrouver ce qui est arrivé à votre paiement !
```

2021-07-26 04:48 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Consultez *[Restrictions du compte](/wiki/Help_Centre/Account_Restrictions)* pour plus d'informations sur les restrictions de compte et la procédure d'appel.
```suggestion
Consultez *[Restrictions du compte](/wiki/Help_Centre/Account_Restrictions)* pour plus d'informations sur les restrictions de comptes et la procédure d'appel.
```

2021-07-26 04:48 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Nous accordons aux utilisateurs de retourner gratuitement à leur précédent nom d'utilisateur. Il suffit de nous contacter à l'addresse [accounts@ppy.sh](mailto:accounts@ppy.sh) et de demander l'annul
```suggestion
Nous accordons aux utilisateurs de retourner gratuitement à leur précédent nom d'utilisateur. Il suffit de nous contacter à l'adresse [accounts@ppy.sh](mailto:accounts@ppy.sh) et de demander l'annulation de votre dernier changement de nom.
```

2021-07-26 04:48 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +**Si vous avez un tag de supporter actif**, vous pouvez voir toutes les maps sur lesquelles vous avez envoyé un score en allant sur la page [liste des beatmaps](https://osu.ppy.sh/beatmapsets), en cl
```suggestion
**Si vous avez un tag de supporter actif**, vous pouvez voir toutes les maps sur lesquelles vous avez un score en allant sur la page [liste des beatmaps](https://osu.ppy.sh/beatmapsets), en cliquant sur `Plus de critères de recherche`, puis en sélectionnant le filtre `Jouée`. Vous pouvez également utiliser [ce lien](https://osu.ppy.sh/beatmapsets?played=played) pour accéder directement à la page filtrée.
```

2021-07-26 04:48 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +Malheureusement, nous ne gardons pas de traces de toutes les maps qu'un utilisateur a téléchargées, il est donc impossible d'en obtenir une liste. Le plus proche que vous puissiez faire serait d'util
```suggestion
Malheureusement, nous ne gardons pas de traces de toutes les maps qu'un utilisateur a téléchargées, il est donc impossible d'en obtenir une liste. Le mieux que vous puissiez faire serait d'utiliser le filtre susmentionné pour récupérer au moins les maps que vous avez déjà joué.
```

2021-07-26 04:48 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Chaque utilisateur a un nombre limité de maps qu'il peut télécharger simultanément. Si vous laissez une map inactive pendant un mois (28 jours), sans la mettre à jour, elle sera envoyée au [Cimetière
```suggestion
Chaque utilisateur a un nombre limité de maps qu'il peut publier simultanément. Si vous laissez une map inactive pendant un mois (28 jours), sans la mettre à jour, elle sera envoyée au [Cimetière](/wiki/Graveyard) des beatmaps. Pour faire revivre une beatmap du cimetière dans un statut En attente ou Work In Progress, mettez-la à jour.
```

2021-08-11 20:59 UTC, Ganondorf-1 requested changes

2021-08-11 20:59 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +## Comment télécharger/mettre à jour ma map ?
```suggestion
## Comment publier/mettre à jour ma map ?
```

2021-08-11 20:59 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +Pour télécharger votre beatmap, allez dans l'éditeur et allez dans `Fichier` > `Publier la beatmap...`.
```suggestion
Pour publier votre beatmap, allez dans l'éditeur et allez dans `Fichier` > `Publier la beatmap...`.
```

2021-08-11 20:59 UTC, Ganondorf-1 commented on wiki/Help_Centre/Beatmapping/fr.md
> +  - télécharger
```suggestion
  - publier
```

2021-08-15 16:34 UTC, Ganondorf-1 approved these changes

2021-08-15 20:00 UTC, TicClick approved these changes

2021-08-15 20:00 UTC, merged