[cs] Welcome
ppy/osu-wiki pull request #5855
Opened 2021-07-18 21:59 UTC by Ondra-D

Translated the welcome osu! wiki page to czech

2021-07-19 06:56 UTC, DoryanR commented
I think translating this page is not a good idea, as it plans to be deleted on #5506

2021-08-02 21:03 UTC, TPGPL requested changes

2021-08-02 21:03 UTC, TPGPL commented on wiki/Welcome/cs.md
> +
```suggestion
```

2021-08-02 21:03 UTC, TPGPL commented on wiki/Welcome/cs.md
> +## Common points of interest
needs to be translated

2021-08-02 21:03 UTC, TPGPL commented on wiki/Welcome/cs.md
> +  - ![osu!mania icon](/wiki/shared/mode/mania.png) [osu!mania](/wiki/Game_mode/osu!mania)
image alt-texts need to be translated

2021-08-02 21:03 UTC, TPGPL commented on wiki/Welcome/cs.md
> +  - ![osu!mania icon](/wiki/shared/mode/mania.png) [osu!mania](/wiki/Ranking_Criteria/osu!mania)
image alt-texts need to be translated

2021-08-03 13:07 UTC, TPGPL requested changes

2021-08-03 13:07 UTC, TPGPL commented on wiki/Welcome/cs.md
> +Beatmapping je proces, kdy tvůrce vytváří beatmapu. Tento proces zahrnuje: výběr hudby, načasování a mapování beatmapy a testování beatmapy. Může také zahrnovat: přidání videa, přidání [storyboardu](
```suggestion
Beatmapping je proces, kdy tvůrce vytváří beatmapu. Tento proces zahrnuje: výběr hudby, načasování a mapování beatmapy a testování beatmapy. Může také zahrnovat: přidání videa, přidání [storyboardu](/wiki/Storyboarding), a / nebo přidání [vlastního vzledu](/wiki/Skinning). To vše může tvůrce provést sám nebo s dalšími uživateli, někdy označovanými jako *storyboarders*, *skinners* a / nebo *guest creators*, podle toho, co dělají.
```

2021-08-03 13:07 UTC, TPGPL commented on wiki/Welcome/cs.md
> +*Main page: [Modding](/wiki/Modding)*
`Main page` needs to be translated

2021-08-03 18:43 UTC, TPGPL approved these changes

2021-08-03 18:43 UTC, merged