Add `Yaz's Summer Cup 2017` tournament article and other prerequisites
ppy/osu-wiki pull request #5856
Opened 2021-07-19 01:33 UTC by Bazzadwarf

The first out of four PR's for adding Yaz's Summer Cup to the wiki, it's a large one so be aware.

TODO's
- [ ] Fix's formatting inconsistencies 
- [ ] Check by yaz

2021-07-19 08:23 UTC, Walavouchey reviewed
writing is alright otherwise

2021-07-19 08:23 UTC, Walavouchey commented on wiki/Tournaments/YSC/2017/en.md
> +- If a player fails to show up after their match is due to start, a 10 minute timer will be started.
redundant (combined with below bullet point)

```suggestion
```

2021-07-19 08:23 UTC, Walavouchey commented on wiki/Tournaments/YSC/2017/en.md
> +- Any player that fails to show up after the 10 minute timer will forfeit the match and a default win will be awarded to the other player.
```suggestion
- Any player that fails to show up 10 minutes after a match is due to start will forfeit the match and a win by default will be awarded to the other player.
```

2021-07-19 08:23 UTC, Walavouchey commented on wiki/Tournaments/YSC/2017/en.md
> +- In groups, there will be one top, one high, one mid and one low seeded player per group, this will be drawn randomly.
```suggestion
- In groups, there will be one top, one high, one mid and one low seeded player per group, which will be drawn randomly.
```

2021-07-19 16:59 UTC, MilkyIQ commented on wiki/Tournaments/YSC/2017/en.md
> +#### Losers Bracker Round 4
do these intend to say "bracket"

2021-07-19 17:04 UTC, Bazzadwarf commented on wiki/Tournaments/YSC/2017/en.md
> +#### Losers Bracker Round 4
Yes

2021-07-19 17:06 UTC, MilkyIQ reviewed
a few grammar suggestions

2021-07-19 17:06 UTC, MilkyIQ commented on wiki/Tournaments/YSC/2017/en.md
> +- All staff members are allowed to sign up for the tournament. The only exception are the host, co-hosts, and mappool selectors/testers.
```suggestion
- All staff members are allowed to sign up for the tournament. The only exceptions are the host, co-hosts, and mappool selectors/testers.
```

2021-07-19 17:06 UTC, MilkyIQ commented on wiki/Tournaments/YSC/2017/en.md
> +- All players must treat staff and other participants with a high level of respect, any kind of mistreatment in a match or on the discord (this includes extreme toxicity, racism, homophobia) will res
```suggestion
- All players must treat staff and other participants with a high level of respect, any kind of mistreatment in a match or on the Discord server (this includes extreme toxicity, racism, homophobia) will result in a ban and will be blacklisted from participating in future installments of this tournament.
```

2021-07-19 17:06 UTC, MilkyIQ commented on wiki/Tournaments/YSC/2017/en.md
> +- Each stage will be held on a friday/saturday/sunday. Schedules and mappools will be released on the monday/tuesday before that stage is due to happen, to allow for reschedules.
```suggestion
- Each stage will be held on a Friday/Saturday/Sunday. Schedules and mappools will be released on the Monday/Tuesday before that stage is due to happen to allow for reschedules.
```
also consider removing pause-comma; nitpick

2021-07-19 22:53 UTC, Bazzadwarf commented
Got the ok from yaz, ready for review!

2021-07-19 23:45 UTC, TPGPL requested changes

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2021/en.md
> +The **Yaz's Summer Cup 2021** (***YSC 2021***) is a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973). It is the 4th installment of Yaz's Summe
```suggestion
The **Yaz's Summer Cup 2021** (***YSC 2021***) is a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973). It is the fourth instalment of Yaz's Summer Cup.
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2019/en.md
> +The **Yaz's Summer Cup 2019** (***YSC 2019***) was a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973). It was the 3rd installment of Yaz's Sum
```suggestion
The **Yaz's Summer Cup 2019** (***YSC 2019***) was a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973). It was the third instalment of Yaz's Summer Cup.
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2018/en.md
> +The **Yaz's Summer Cup 2018** (***YSC 2018***) was a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973). It was the 2nd installment of Yaz's Sum
```suggestion
The **Yaz's Summer Cup 2018** (***YSC 2018***) was a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973). It was the second instalment of Yaz's Summer Cup.
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +The **Yaz's Summer Cup 2017** (***YSC 2017***) was a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973) and sponsored by Ferocity Esports. It wa
```suggestion
The **Yaz's Summer Cup 2017** (***YSC 2017***) was a 1v1 double-elimination osu! tournament hosted by ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973) and sponsored by Ferocity Esports. It was the first instalment of Yaz's Summer Cup.
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +| *4th place* | $10, 1 month of osu!supporter tag |
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | $60, profile badge, 6 months of osu!supporter |
| ![Silver crown](/wiki/shared/crown-silver.png "2nd place") | $35, 4 months of osu!supporter |
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | $20, 2 months of osu!supporter |
| *4th place* | $10, 1 month of osu!supporter |
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +Yaz's Summer Cup 2017 was run by various community members by distributing the multitude of tasks into various fields of responsibility.
```suggestion
Yaz's Summer Cup 2017 was run by various community members.
```
can use this version, we deprecated the long one pretty much

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +### Group Stage
```suggestion
### Group stage
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +- Nomod
```suggestion
- NoMod
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +## Match Results
```suggestion
## Match results
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +### General Rules
```suggestion
### General rules
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +### Qualifiers and Group Stage
```suggestion
### Qualifiers and Group stage
```

2021-07-19 23:45 UTC, TPGPL commented on wiki/Tournaments/YSC/2017/en.md
> +### Knockout Stages
```suggestion
### Knockout stages
```

2021-07-20 14:23 UTC, TPGPL approved these changes

2021-07-20 14:24 UTC, merged