Update id.md
ppy/osu-wiki pull request #5857
Opened 2021-07-19 03:58 UTC by hikikuman

Fix some words and a typo:
- Jenis = Mode
- Kriteria Ranking = Ranking Criteria
- Mods = Mod
- Projek = Proyek
- Pengembang = Developer
- Tim Project Loved = Project Loved Team
- Kontributor Komuinitas = Kontributor Komunitas

2021-07-19 04:13 UTC, wowcake approved these changes
ready to be merged 👍

2021-07-21 04:41 UTC, ZeroPyrozen requested changes

2021-07-21 04:41 UTC, ZeroPyrozen commented on wiki/Main_Page/id.md
> +[Tim inti](/wiki/People/The_Team): [Developer](/wiki/People/The_Team/Developers) • [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team) • [Support Team](/wiki/People/The_Team/Suppor
```suggestion
[Team](/wiki/People/The_Team): [Developer](/wiki/People/The_Team/Developers) • [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team) • [Support Team](/wiki/People/The_Team/Support_Team) • [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) • [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators) • [osu! Alumni](/wiki/People/The_Team/osu!_Alumni) • [Project Loved Team](/wiki/People/The_Team/Project_Loved_Team)
```

2021-07-21 07:38 UTC, hikikuman commented on wiki/Main_Page/id.md
> +[Tim inti](/wiki/People/The_Team): [Developer](/wiki/People/The_Team/Developers) • [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team) • [Support Team](/wiki/People/The_Team/Suppor
di [wiki](https://osu.ppy.sh/wiki/id/People/The_Team)nya sih memang tulisannya "tim" aja, tapi justru kalo cuma "tim" atau "team", malah jadi ambigu aja karena terlalu luas. pada dasarnya, memang itu mereka bisa dibilang tim inti jadi menurutku lebih tepat tetep keep yang lama aja

2021-07-21 07:54 UTC, ZeroPyrozen approved these changes
👍

2021-08-02 20:05 UTC, TPGPL approved these changes

2021-08-02 20:05 UTC, merged