[FR/EN] Update `Keyboard Bindings`, `Offset Wizard`, update [EN] `Keyboard Bindings`
ppy/osu-wiki pull request #5874
Opened 2021-07-22 10:24 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Options/Keyboard_Bindings`
- `Options/Offset_Wizard`

Also, in `Options/Keyboard_Bindings/en.md`:

- Convert old name of game mode in thier actual name

2021-07-23 07:53 UTC, Ganondorf-1 requested changes

2021-07-23 07:53 UTC, Ganondorf-1 commented on wiki/Options/Keyboard_Bindings/fr.md
> +| Decrease Local Song Offset | `-` (minus) |
```suggestion
| Decrease Local Song Offset | `-` (moins) |
```

2021-07-23 07:53 UTC, Ganondorf-1 commented on wiki/Options/Keyboard_Bindings/fr.md
> +  - Lorsqu'il est utilisé, osu! se met en sourdine et cache la fenêtre de la barre d'outils.
```suggestion
  - Lorsqu'elle est utilisée, osu! se met en sourdine et cache la fenêtre de la barre d'outils.
```

2021-07-23 07:53 UTC, Ganondorf-1 commented on wiki/Options/Keyboard_Bindings/fr.md
> +- Explication de `Boss Key` : [Boss key](https://fr.wikipedia.org/wiki/Boss_key "Wikipédia")
```suggestion
- Explication de la `Boss Key` : [Boss key](https://fr.wikipedia.org/wiki/Boss_key "Wikipédia")
```

2021-07-23 07:53 UTC, Ganondorf-1 commented on wiki/Options/Keyboard_Bindings/fr.md
> +  - Pour désactiver le boss key, cliquez sur l'icône osu! dans la barre des tâches et le client s'ouvrira.
```suggestion
  - Pour désactiver la boss key, cliquez sur l'icône osu! dans la barre des tâches et le client s'ouvrira.  
```

2021-07-23 07:53 UTC, Ganondorf-1 commented on wiki/Options/Keyboard_Bindings/fr.md
> +**Attention :** ce bouton ne **vous confirme pas** si vous aviez vraiment voulu le faire !
```suggestion
**Attention :** ce bouton ne **vous demande pas** si vous aviez vraiment voulu le faire !
```

2021-07-23 07:54 UTC, DoryanR commented on wiki/Options/Keyboard_Bindings/fr.md
> +| Decrease Local Song Offset | `-` (minus) |
C'est pas traduit dans le jeu la fenêtre de configuration des touches, je dirait de laisser comme ça du coup

2021-08-20 22:25 UTC, TicClick commented
@Ganondorf-1 is this good to go?

2021-08-21 19:16 UTC, Imakuri requested changes
Suggestions concerning the grammar of the translation of wiki pages in French.

2021-08-21 19:16 UTC, Imakuri commented on wiki/Options/Offset_Wizard/fr.md
> +Sous l'affichage de la valeur de décalage universel se trouvent trois options qui modifient la vitesse du métronome. En activant l'option `BPM /2`, le temps entre les ticks du métronome sera doublé,
```suggestion
Sous l'affichage de la valeur de décalage universel se trouvent trois options qui modifient la vitesse du métronome. En activant l'option `BPM /2`, le temps entre les ticks du métronome sera doublé, ce qui le rendra plus lent. Cette option affiche également le paramètre `Battements sur contretemps`. En activant l'option `Battements sur contretemps`, le temps entre les ticks du métronome sera le même que pour `BPM /2`, mais sur un autre temps. Enfin, l'activation de l'option `BPM x2` divisera par deux le temps entre les ticks du métronome, le rendant plus rapide. Ces options sont utilisées pour ajuster le métronome, afin qu'il s'adapte mieux au morceau en cours de lecture.
```

2021-08-21 19:16 UTC, Imakuri commented on wiki/Options/Offset_Wizard/fr.md
> +Sous l'affichage de la valeur de décalage universel se trouvent trois options qui modifient la vitesse du métronome. En activant l'option `BPM /2`, le temps entre les ticks du métronome sera doublé,
Changements suggérés : une répétition du mot "option" à deux mots d’intervalle remplacé par "paramètre" et rectification d'un "tics" en "ticks"

2021-08-21 19:16 UTC, Imakuri commented on wiki/Options/Keyboard_Bindings/fr.md
> +- Vous pouvez également utiliser `Ctrl` + `+` pour augmenter la vitesse.
```suggestion
- Vous pouvez utiliser `Ctrl` + `+` pour augmenter la vitesse...
```

2021-08-21 19:16 UTC, Imakuri commented on wiki/Options/Keyboard_Bindings/fr.md
> +- Vous pouvez également utiliser `Ctrl` + `-` pour diminuer la vitesse.
```suggestion
- Et vous pouvez également utiliser `Ctrl` + `-` pour la diminuer.
```

2021-08-21 19:16 UTC, Imakuri commented on wiki/Options/Keyboard_Bindings/fr.md
> +- Vous pouvez également utiliser `Ctrl` + `-` pour diminuer la vitesse.
J'ai suggéré une modification ici car je trouvais que les phrases (qui étaient les mêmes à quelques détails près) faisaient trop rigides. J'ai donc pensé les faire un peu plus légères et "interactives" entre elles !

2021-08-21 19:16 UTC, Imakuri commented on wiki/Options/Offset_Wizard/fr.md
> +Pour accéder à l'assistant de décalage, ouvrez le menu [Options](/wiki/Options) et tapez `décalage` dans la recherche rapide. Cliquez ensuite sur le bouton `Démarrer l'assistant`.
```suggestion
Pour accéder à l'assistant de décalage, ouvrez le menu [Options](/wiki/Options) et tapez `décalage` dans la barre de recherche rapide. Cliquez ensuite sur le bouton `Démarrer l'assistant`.
```

2021-08-24 16:14 UTC, Ganondorf-1 approved these changes

2021-08-24 16:15 UTC, Ganondorf-1 commented
Sorry for my recent lack of activity, don't hesitate to ping me on Discord instead because I always check my mentions there.

2021-08-24 21:02 UTC, TicClick approved these changes

2021-08-24 21:03 UTC, merged