[ID] Add `Play Style/Tapping Style`
ppy/osu-wiki pull request #5875
Opened 2021-07-22 11:06 UTC by Fhoxydeo

2021-07-25 05:54 UTC, mousesalt requested changes

2021-07-25 05:54 UTC, mousesalt commented on wiki/Play_style/Tapping_style/id.md
> +*berbeda dengan [Play style](/wiki/Play_style).*
```suggestion
*Berbeda dengan [Play style](/wiki/Play_style).*
```

2021-07-25 05:54 UTC, mousesalt commented on wiki/Play_style/Tapping_style/id.md
> +**Tapping style** adalah istilah yang digunakan untuk menggambarkan metode pemain yang menekan tombol/mengirim input pada perangkat input seseorang untuk menekan [*hit object*](/wiki/Hit_objects) di
```suggestion
**Tapping style** adalah istilah yang digunakan untuk menggambarkan metode pemain yang menekan tombol/mengirim input pada sebuah perangkat input untuk menekan [*hit object*](/wiki/Hit_objects) di osu!. Gaya ketukan yang umum untuk [osu!](/wiki/Game_mode/osu!) adalah [*alternating*](/wiki/Play_style/Alternating), [*single-tap*](/wiki/Play_style/Single-tap), [*double tap*](/wiki/Play_style/Double_tapping), [*Hybrid*](/wiki/Play_style/Hybrid), dan [*tapx*](/wiki/Play_style/Tapx).
```

2021-07-25 05:54 UTC, mousesalt commented on wiki/Play_style/Tapping_style/id.md
> +**Tapping style** adalah istilah yang digunakan untuk menggambarkan metode pemain yang menekan tombol/mengirim input pada perangkat input seseorang untuk menekan [*hit object*](/wiki/Hit_objects) di
not a subject but a object

2021-07-31 04:25 UTC, wowcake approved these changes

2021-08-01 16:47 UTC, mousesalt approved these changes

2021-08-02 04:02 UTC, ZeroPyrozen approved these changes

2021-08-06 22:46 UTC, TPGPL approved these changes

2021-08-06 22:46 UTC, merged