[FR] Add `Glossary/Active object`, `Dash`, `Edge dash`, `Hyperdash` , `Snapping`, `Trigger distance`, `Walk`
ppy/osu-wiki pull request #5887
Opened 2021-07-25 11:01 UTC by DoryanR

Translation of the following wiki pages:

- `Glossary/Active_object`
- `Glossary/Dash`
- `Glossary/Edge_dash`
- `Glossary/Hyperdash`
- `Glossary/Snapping`
- `Glossary/Trigger_distance`
- `Glossary/Walk`

2021-07-26 04:57 UTC, Ganondorf-1 requested changes

2021-07-26 04:57 UTC, Ganondorf-1 commented on wiki/Glossary/Snapping/fr.md
> +Dans [osu!catch](/wiki/Game_mode/osu!catch), tous les [dash](/wiki/Glossary/Dash) et [hyperdash](/wiki/Glossary/Hyperdash) peuvent être classés en deux types de snapping différents : basic-snapped ou
```suggestion
Dans [osu!catch](/wiki/Game_mode/osu!catch), tous les [dashes](/wiki/Glossary/Dash) et [hyperdashes](/wiki/Glossary/Hyperdash) peuvent être classés en deux types de snapping différents : basic-snapped ou higher-snapped. 
```

2021-07-26 04:57 UTC, Ganondorf-1 commented on wiki/Glossary/Trigger_distance/fr.md
> +Le  **trigger distance** est un terme utilisé dans [osu!catch](/wiki/Game_mode/osu!catch) pour désigner l'espacement minimal nécessaire pour générer un [hyperfruit](/wiki/Hit_object/Hyperfruit) sur u
```suggestion
La  **trigger distance** est un terme utilisé dans [osu!catch](/wiki/Game_mode/osu!catch) pour désigner l'espacement minimum nécessaire pour générer un [hyperfruit](/wiki/Hit_object/Hyperfruit) sur un [fruit](/wiki/Hit_object/Fruit) ou un [drop](/wiki/Hit_object/Juice_stream#drop).
```

2021-08-11 21:43 UTC, Ganondorf-1 commented on wiki/Glossary/Trigger_distance/fr.md
> +La  **trigger distance** est un terme utilisé dans [osu!catch](/wiki/Game_mode/osu!catch) pour désigner l'espacement minimum nécessaire pour générer un [hyperfruit](/wiki/Hit_object/Hyperfruit) sur u
```suggestion
La **trigger distance** est un terme utilisé dans [osu!catch](/wiki/Game_mode/osu!catch) pour désigner l'espacement minimum nécessaire pour générer un [hyperfruit](/wiki/Hit_object/Hyperfruit) sur un [fruit](/wiki/Hit_object/Fruit) ou un [drop](/wiki/Hit_object/Juice_stream#drop).
```

2021-08-13 14:04 UTC, Ganondorf-1 approved these changes

2021-08-15 16:17 UTC, TicClick approved these changes

2021-08-15 16:17 UTC, merged