Add Time Lapse Mapping to `osu!academy`
ppy/osu-wiki pull request #5888
Opened 2021-07-25 12:50 UTC by saieeshb

Add Time Lapse Mapping and associated images, links and all such to osu!academy.

2021-07-25 15:01 UTC, DoryanR requested changes
Fix to pass the file verification check

2021-07-25 15:01 UTC, DoryanR commented on wiki/osu!academy/en.md
> +| ![](img/lapse-3.png) | [Episode 3](https://youtu.be/3OM8AgzIFAY "YouTube") | In this episode, we go over the  time lapse mapping of the Normal difficulty of [Miqz - Sound of my Dream!](https://osu.
```suggestion
| ![](img/lapse-3.png) | [Episode 3](https://youtu.be/3OM8AgzIFAY "YouTube") | In this episode, we go over the  time lapse mapping of the Normal difficulty of [Miqz - Sound of my Dream!](https://osu.ppy.sh/beatmapsets/245877#osu/632389) |
```

2021-07-25 15:01 UTC, DoryanR commented on wiki/osu!academy/en.md
> +| ![](img/lapse-4.png) | [Episode 4](https://youtu.be/NZ4oE_Xe51Q "YouTube") |In this episode, we visit the  time lapse mapping of the Easy difficulty of [Miqz - Sound of my Dream!](https://osu.ppy.s
```suggestion
| ![](img/lapse-4.png) | [Episode 4](https://youtu.be/NZ4oE_Xe51Q "YouTube") | In this episode, we visit the  time lapse mapping of the Easy difficulty of [Miqz - Sound of my Dream!](https://osu.ppy.sh/beatmapsets/245877#osu/643621) |
```

2021-07-25 15:01 UTC, DoryanR commented on wiki/osu!academy/en.md
> +| ![](img/lapse-8.png) | [Episode 8](https://youtu.be/UfWlpD3pocs "YouTube") |In this episode, [Chromoxx](https://osu.ppy.sh/users/1881639) goes over the time lapse mapping of the Kantan difficulty o
```suggestion
| ![](img/lapse-8.png) | [Episode 8](https://youtu.be/UfWlpD3pocs "YouTube") | In this episode, [Chromoxx](https://osu.ppy.sh/users/1881639) goes over the time lapse mapping of the Kantan difficulty of Circles in the taiko gamemode! |
```

2021-07-25 15:01 UTC, DoryanR commented on wiki/osu!academy/en.md
> +| ![](img/lapse-9.png) | [Episode 9](https://youtu.be/REpmCJEB9jY "YouTube") |In this episode, [Evening](https://osu.ppy.sh/users/2193881) covers the time lapse mapping of the 4K Insane difficulty of
```suggestion
| ![](img/lapse-9.png) | [Episode 9](https://youtu.be/REpmCJEB9jY "YouTube") | In this episode, [Evening](https://osu.ppy.sh/users/2193881) covers the time lapse mapping of the 4K Insane difficulty of LANGUAGE (KAYZO AND GAMMER REMIX) in the mania gamemode! |
```

2021-07-25 15:06 UTC, saieeshb commented
> Fix to pass the file verification check

Thank you! @DoryanR  I didn't realize missing spaces would break this.

2021-07-25 18:02 UTC, saieeshb commented
Will keep these in mind before pulling in the future. 👍

2021-07-25 18:25 UTC, TPGPL requested changes

2021-07-25 18:25 UTC, TPGPL commented on wiki/osu!academy/en.md
> +**[Time Lapse Mapping](https://www.youtube.com/playlist?list=PLmWVQsxi34bO7PAmjWZjVDi16pAy-GRBP "YouTube")** is a collection of videos made by [ztrot](https://osu.ppy.sh/users/6347) and a few other m
```suggestion
**[Time Lapse Mapping](https://www.youtube.com/playlist?list=PLmWVQsxi34bO7PAmjWZjVDi16pAy-GRBP "YouTube")** is a series of videos hosted by [ztrot](https://osu.ppy.sh/users/6347) and several mappers from different game modes, where they explain the process of creating beatmaps with a sped-up mapping session in the background.
```

2021-07-26 06:24 UTC, saieeshb commented
Is anything else needed?

2021-07-27 16:49 UTC, TPGPL approved these changes

2021-07-27 16:49 UTC, merged