[FR] Add `Medals/Unlock Requirements/Beatmap Challenge Packs`, `Beatmap Packs`, `Beatmap Spotlights`, `Dedication`, `Seasonal Spotlights`, `Skill`
ppy/osu-wiki pull request #5889
Opened 2021-07-26 05:52 UTC by Ganondorf-1

French translation of the `Medals\Unlock Requirements` folder

2021-07-26 05:55 UTC, Ganondorf-1 commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Never Give Up (osu!)/Time Everlasting (osu!taiko)/Supersonic (osu!catch)/Step Up (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star ratin
```suggestion
| Never Give Up (osu!)/Time Everlasting (osu!taiko)/Supersonic (osu!catch)/Step Up (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 7,00★ et 7,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulty-increase), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulty-reduction) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR requested changes

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Beatmap_challenge_packs/fr.md
> +# Conditions de déverrouillage des médailles Beatmap Challenge Packs
```suggestion
# Conditions de déverrouillage des médailles : Beatmap Challenge Packs 
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Beatmap_packs/fr.md
> +# Conditions de déverrouillage des médailles Beatmap Packs
```suggestion
# Conditions de déverrouillage des médailles : Beatmap Packs
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Beatmap_spotlights/fr.md
> +# Conditions de déverrouillage des médailles Beatmap Spotlights
```suggestion
# Conditions de déverrouillage des médailles : Beatmap Spotlights
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Dedication/fr.md
> +# Conditions de déverrouillage des médailles Dedication
```suggestion
# Conditions de déverrouillage des médailles : Dedication
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Mod_introduction/fr.md
> +# Conditions de déverrouillage des médailles Mod Introduction
```suggestion
# Conditions de déverrouillage des médailles : Mod Introduction
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| These Clarion Skies (osu!)/The Demon Within (osu!taiko)/It's Raining Fruit (osu!catch)/Ever Onwards (osu!mania) | Terminer une beatmap qualifiée, classée ou approuvée qui se situe dans un star rati
```suggestion
| These Clarion Skies (osu!)/The Demon Within (osu!taiko)/It's Raining Fruit (osu!catch)/Ever Onwards (osu!mania) | Terminer une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 5,00★ et 5,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Supremacy (osu!)/The Godfather (osu!taiko)/Dreamcatcher (osu!catch)/Extra Credit (osu!mania) | Terminer une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 7,00★ et 7
```suggestion
| Supremacy (osu!)/The Godfather (osu!taiko)/Dreamcatcher (osu!catch)/Extra Credit (osu!mania) | Terminer une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 7,00★ et 7,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Phantasm | Terminer une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 10,00★ et 10,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#diffi
```suggestion
| Phantasm | Terminer une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 10,00★ et 10,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu osu!. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Totality (osu!)/Keeping Time (osu!taiko)/Sweet And Sour (osu!catch)/Keystruck (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating e
```suggestion
| Totality (osu!)/Keeping Time (osu!taiko)/Sweet And Sour (osu!catch)/Keystruck (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 1,00★ et 1,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Business As Usual (osu!)/To Your Own Beat (osu!taiko)/Reaching The Core (osu!catch)/Keying In (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans
```suggestion
| Business As Usual (osu!)/To Your Own Beat (osu!taiko)/Reaching The Core (osu!catch)/Keying In (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 2,00★ et 2,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Building Steam (osu!)/Big Drums (osu!taiko)/Clean Platter (osu!catch)/Hyperflow (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating
```suggestion
| Building Steam (osu!)/Big Drums (osu!taiko)/Clean Platter (osu!catch)/Hyperflow (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 3,00★ et 3,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Moving Forward (osu!)/Adversity Overcome (osu!taiko)/Between The Rain (osu!catch)/Breakthrough (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans
```suggestion
| Moving Forward (osu!)/Adversity Overcome (osu!taiko)/Between The Rain (osu!catch)/Breakthrough (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 4,00★ et 4,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Paradigm Shift (osu!)/Demonslayer (osu!taiko)/Addicted (osu!catch)/Everything Extra (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star ra
```suggestion
| Paradigm Shift (osu!)/Demonslayer (osu!taiko)/Addicted (osu!catch)/Everything Extra (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 5,00★ et 5,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Anguish Quelled (osu!)/Rhythm's Call (osu!taiko)/Quickening (osu!catch)/Level Breaker (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star
```suggestion
| Anguish Quelled (osu!)/Rhythm's Call (osu!taiko)/Quickening (osu!catch)/Level Breaker (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 6,00★ et 6,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Never Give Up (osu!)/Time Everlasting (osu!taiko)/Supersonic (osu!catch)/Step Up (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star ratin
```suggestion
| Never Give Up (osu!)/Time Everlasting (osu!taiko)/Supersonic (osu!catch)/Step Up (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 7,00★ et 7,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Aberration (osu!)/The Drummer's Throne (osu!taiko)/Dashing Scarlet (osu!catch)/Behind The Veil (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans
```suggestion
| Aberration (osu!)/The Drummer's Throne (osu!taiko)/Dashing Scarlet (osu!catch)/Behind The Veil (osu!mania) | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 8,00★ et 8,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu correspondant. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Chosen | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 9,00★ et 9,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_
```suggestion
| Chosen | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 9,00★ et 9,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu osu!. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-26 13:34 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| Unfathomable | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 10,00★ et 10,99★ (après que tous les [mods augmentant la difficulté](/wi
```suggestion
| Unfathomable | Réaliser un full combo sur une beatmap qualifiée, classée ou approuvée qui se situe dans un star rating entre 10,00★ et 10,99★ (après que tous les [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée), s'il y en a, aient été pris en compte) dans le mode de jeu osu!. Toute utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) n'est pas autorisée. |
```

2021-07-29 20:51 UTC, Ganondorf-1 commented on wiki/Medals/Unlock_requirements/Beatmap_spotlights/fr.md
> +| August 2017 Spotlight | Terminez toutes les beatmaps regroupées dans l'un des beatmap packs Spotlights August 2017 ([osu!](https://osu.ppy.sh/beatmaps/packs/1265)/[osu!taiko](https://osu.ppy.sh/bea
```suggestion
| August 2017 Spotlight | Terminez toutes les beatmaps regroupées dans l'un des beatmap packs Spotlights August 2017 ([osu!](https://osu.ppy.sh/beatmaps/packs/1265)/[osu!taiko](https://osu.ppy.sh/beatmaps/packs/1264)/[osu!catch](https://osu.ppy.sh/beatmaps/packs/1267)/[osu!mania](https://osu.ppy.sh/beatmaps/packs/1268)). |
```

2021-07-29 20:51 UTC, Ganondorf-1 commented on wiki/Medals/Unlock_requirements/Beatmap_spotlights/fr.md
> +| March 2018 Spotlight | Terminez toutes les beatmaps regroupées dans l'un des beatmap packs Spotlights January/February 2017 ([osu!](https://osu.ppy.sh/beatmaps/packs/1405)/[osu!taiko](https://osu.p
```suggestion
| March 2018 Spotlight | Terminez toutes les beatmaps regroupées dans l'un des beatmap packs Spotlights January/February 2017 ([osu!](https://osu.ppy.sh/beatmaps/packs/1405)/[osu!taiko](https://osu.ppy.sh/beatmaps/packs/1407)/[osu!catch](https://osu.ppy.sh/beatmaps/packs/1408)). |
```

2021-07-30 13:40 UTC, DoryanR requested changes

2021-07-30 13:40 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Seasonal_spotlights/fr.md
> +| Summer 2018 Beatmap Spotlights | Terminez toutes les beatmaps regroupées dans l'un des beatmap packs Beatmap Spotlights: Summer 2018 ([osu!](https://osu.ppy.sh/beatmaps/packs/1508)/[osu!taiko](http
```suggestion
| Summer 2018 Beatmap Spotlights | Terminez toutes les beatmaps regroupées dans l'un des beatmap packs Seasonal Spotlights: Summer 2018 ([osu!](https://osu.ppy.sh/beatmaps/packs/1508)/[osu!taiko](https://osu.ppy.sh/beatmaps/packs/1509)/[osu!catch](https://osu.ppy.sh/beatmaps/packs/1510)/[osu!mania](https://osu.ppy.sh/beatmaps/packs/1511)). |
```

2021-07-30 13:40 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| 500 Combo | Atteindre 500 de combo sur une beatmap de n'importe quel mode de jeu. |
```suggestion
| 500 Combo | Atteindre un combo de 500 sur une beatmap de n'importe quel mode de jeu. |
```

2021-07-30 13:40 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| 750 Combo | Atteindre 750 de combo sur une beatmap de n'importe quel mode de jeu. |
```suggestion
| 750 Combo | Atteindre un combo de 750 sur une beatmap de n'importe quel mode de jeu. |
```

2021-07-30 13:40 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| 1000 Combo | Atteindre 1000 de combo sur une beatmap de n'importe quel mode de jeu. |
```suggestion
| 1000 Combo | Atteindre un combo de 1000 sur une beatmap de n'importe quel mode de jeu. |
```

2021-07-30 13:40 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Skill/fr.md
> +| 2000 Combo | Atteindre 2000 de combo sur une beatmap de n'importe quel mode de jeu. |
```suggestion
| 2000 Combo | Atteindre un combo 2000 sur une beatmap de n'importe quel mode de jeu. |
```

2021-08-06 17:20 UTC, DoryanR approved these changes

2021-08-06 20:48 UTC, TPGPL approved these changes

2021-08-06 20:49 UTC, merged