[EN/ID] Update `Users with unique titles`
ppy/osu-wiki pull request #5891
Opened 2021-07-26 10:26 UTC by hikikuman

Changed username (EN/ID):
- Stevie Blunder > im a fancy lad
- [224]Hyperw7 > CTB Rushia1
- andreymc > Amerom
- Remu > Punnies

Deleted from `By name` (EN/ID):
- Motion
- R-18/Petit
- Rocma
- T s u m i

Added to `By name` (EN/ID)
- Abstract-
- Berea
- CTB Rushia1
- DreStar
- Rells

Added to `Contributors` and `By name` (ID):
- Azer
- ChillierPear
- LeoFLT

2021-07-26 13:39 UTC, Nivalyx commented
oh fwiw whenever this article were to be updated the update usually comes for all languages tho (not just any specific language(s)) to avoid any possible discrepancy in the future :

---

![image](https://user-images.githubusercontent.com/36564236/126998167-27b21670-4e3f-4f1c-8f23-de2be659ea95.png)

2021-07-26 20:08 UTC, TPGPL requested changes
needs to be done in other translations as well

2021-07-27 17:03 UTC, hikikuman commented
Updated

2021-07-27 17:17 UTC, TPGPL approved these changes

2021-07-27 17:17 UTC, merged