Add files via upload
ppy/osu-wiki pull request #5900
Opened 2021-07-27 20:57 UTC by Dopaminos

2021-07-28 08:45 UTC, Dopaminos commented
for real, idk how to fix remark errors, help

2021-07-28 09:47 UTC, gagahpangeran commented
This one error is easy to fix.

```
 wiki/Help_Centre/Account_Restrictions/ru.md:104:1 - error remark-lint:no-heading-punctuation Don’t add a trailing `.` to headings

  104 ## Часто встречающиеся причины ограничения акккаунта и кулдауны.
```

The remaining errors are

```
error remark-lint:linebreak-style Expected linebreaks to be unix (`\n`), not windows (`\r\n`)
```

What editor did you use to edit that file?

2021-07-28 10:35 UTC, Dopaminos commented
I used Sublime Text 3, now i edit files at github directly

2021-07-28 11:24 UTC, TicClick commented
> I used Sublime Text 3, now i edit files at github directly. btw write me at osu site or discord to make me reply faster

see this answer by Steven K7FAQ: https://stackoverflow.com/a/58191795/1823304

2021-07-28 12:01 UTC, Dopaminos commented
updated, @TicClick можно ревью

2021-07-28 12:06 UTC, TicClick commented
will do when I'm done with my promise the other translator

2021-08-02 02:30 UTC, UristMcKobold requested changes

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +**Читерсво или передача аккаунта во время официального турнира или турнира со значком приведет к постоянной блокировке пользователя в любых будущих турнирах.** Этот бан нельзя аппелировать и если вы
```suggestion
**Использование читов или передача аккаунта во время официального турнира или турнира с наградой в виде значка в профиле приведёт к навечному бану пользователя в любых будущих турнирах.** Этот бан нельзя апеллировать, и если вы попытаетесь это сделать, ваше письмо будет проигнорировано, бан ни при каких условиях не будет снят или сокращён.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Некоторые игроки могут быть снова ограничены, если они начнут играть после того, как их апелляция будет принята. Это автоматизированный процесс, и ограничение снимут в течение 24 часов. Не стесняйтес
```suggestion
Некоторые игроки могут получить рестрикт, если они начнут играть после того, как их апелляция будет одобрена. Это автоматический процесс, и рестрикт снимут в течение 24 часов. Не стесняйтесь задавать вопросы в твиттере [@osusupport](https://twitter.com/osusupport) или письмах по адресу [accounts@ppy.sh](mailto:accounts@ppy.sh), если это случится с вами!
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +После некоторых нарушений ваш аккаунт может быть сброшен. Это будет сделано, чтобы удалить ваши рекорды, сделанные нечестно **во всех режимах игры**, а также и разблокированные медали и значки. **Кол
```suggestion
После некоторых нарушений ваш аккаунт откатят назад. Это делается для того, чтобы удалить ваши рекорды, сделанные нечестно **во всех режимах игры**, а также и разблокированные медали и значки. **Количество игр и время игры сброшено не будет.**
```
Как и в случае выше, rolled back — не совсем сброшен.

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +## Моя аппеляция была отклонена!
```suggestion
## Моя апелляция была отклонена!
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Есть несколько причин, из-за которых ваша аппеляция может быть отклонена.
```suggestion
Ваша апелляция может быть отклонена по нескольким причинам.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вы прислали её слишком рано.** Если кулдаун на вашем аккаунте всё ещё не прошел, ваша аппеляция будет отклонена. Если вы не уверены в сроке подачи аппеляции, ответьте на наше отклонительное письм
```suggestion
- **Вы прислали её слишком рано.** Если кулдаун на вашем аккаунте всё ещё не прошел, ваша апелляция будет отклонена. Если вы не уверены в сроке подачи апелляции, ответьте на наше письмо с отказом, и мы уточним дату.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Ваша апелляция была недостаточно существенной или неполной** Если ваша апелляция недостаточно охватывает четыре пункта, перечисленных выше, мы попросим вас написать более полную её версию. Это **
```suggestion
- **Ваша апелляция была недостаточно полной.** Если ваша апелляция не содержит четыре пункта, перечисленных выше, мы попросим вас написать более полную её версию. Это **не** сбрасывает вам кулдаун, и вы можете прислать новую апелляцию в любой момент! Однако если вы пытались солгать или скрыть серьёзные нарушения правил (в основном мульти-аккаунтинг или использование читов), ваша апелляция будет отклонена из-за недостоверности, а кулдаун будет сброшен до трех месяцев. Это ещё один шанс подумать о совершённых деяниях и убедиться, что вы ничего не забыли.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вы уклонялись от ограничения или играли на других аккаунтах.** Создание другого аккаунта для возможности играть онлайн во время ограничения вашего основного аккаунта воспринимается нами как попыт
```suggestion
- **Вы обходили рестрикт или играли на других аккаунтах.** Создание другого аккаунта для возможности играть онлайн во время рестрикта вашего основного аккаунта воспринимается нами как попытка избежать наказания и сбросит ваш кулдаун до трёх месяцев с момента создания нового аккаунта. Если вы будете обходить рестрикт слишком часто, ваша апелляция может быть навсегда отклонена. Если у вас всё ещё есть доступ к мульти-аккаунтам, или вы играете на них во время рестрикта, ваш кулдаун также может быть сброшен. Помните, что мульти-аккаунтинг запрещён [правилами](/wiki/Rules), и вы должны играть только на своём основном аккаунте. Если вы не уверены, какой аккаунт является вашим основным, напишите нам письмо, и мы дадим вам знать!
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вы продолжили нарушать правила во время того, как ваш аккаунт был ограничен.** Нет причин для того, чтобы снимать ограничения с человека, продолжающего нарушать правила после ограничения аккаунта
```suggestion
- **Вы продолжили нарушать правила после рестрикта.** Нет причин для того, чтобы снимать рестрикт с человека, продолжающего нарушать правила после него. Если вы продолжили их нарушать, кулдаун будет сброшен до вашего последнего нарушения. В случаях совсем серьёзного или продолжительного количества нарушений, ваша апелляция может быть навсегда отклонена.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Ваша история слишком ужасна.** Для экстремально-больших нарушителей, или игроков, чьи аккаунты были ограничены после недавно принятой аппеляции, мы можем установить, что ваша история слишком ужас
```suggestion
- **Ваша история слишком плоха.** Злостных нарушителей или игроков, чьи аккаунты были рестриктнуты после недавно принятой апелляции, мы можем посчитать, что сейчас их история слишком плоха, чтобы дать им возможность возвращаться в игру. Если это относится к вам, мы рекомендуем подождать в течение **долгого времени**, прежде чем подавать апелляцию снова, чтобы убедиться, что вы не будете нарушать никаких других правил в будущем.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +## Мои письма игнорируют / Я не думаю, что моя аппеляция была справедливо оценена
```suggestion
## Мои письма игнорируют / Я не думаю, что моя апелляция была справедливо разобрана
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если вы чувствуете, что ваши электронные письма не читаются или не рассматриваются должным образом нашей службой поддержки, отправьте нам полное письмо по адресу [appeal-review@ppy.sh](mailto:appeal-
```suggestion
Если вам кажется, что ваши электронные письма не читаются или не рассматриваются должным образом нашей службой поддержки, отправьте нам письмо по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh), содержащее следующую информацию:
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- Как долго ваш аккаунт был ограничен
```suggestion
- Как долго ваш аккаунт был в рестрикте
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- Основная причина вашего ограничения
```suggestion
- Основная причина вашего рестрикта
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- Все предыдущие аппеляции которые, по вашему мнению, были проигнорированы или несправедливо оценены
```suggestion
- Все предыдущие апелляции, которые были проигнорированы или несправедливо разобраны
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- Почему вам не нравится исход вашей аппеляции вкратце (если применимо)
```suggestion
- Краткое изложение причин, по которым вы не согласны с решением по вашей апелляции (если это к вам относится)
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Все письма, отправленные на электронный адрес для рассмотрения апелляции, будут изучены третьей стороной, которая не участвует в повседневных операциях службы поддержки, и помечены для проверки или д
```suggestion
Все письма, отправленные на этот электронный адрес, будут изучены третьей стороной, которая не участвует в рутине работы службы поддержки, и помечены для проверки или дальнейшего рассмотрения.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Просим вас понять, что письма, присланные вами на этот адрес лишь являются гарантом второго/исходного ответа на вашу аппеляцию и это не гарантирует снятия ограничений, если было установлено, что вы н
```suggestion
Просим вас учесть, что письма, присланные вами на этот адрес, лишь являются гарантом пересмотра или ответа на вашу апелляцию, но пересмотра решения может не быть, если будет установлено, что вы не соблюдаете наши условия в процессе апелляции.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +**Мы отвечаем на запросы по повторному рассмотрению ваших аппепляций с помощью письма, присланного на [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** Пожалуйста, не пытайтесь связаться с коман
```suggestion
**Мы отвечаем на запросы по повторному рассмотрению ваших апелляций только по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** Пожалуйста, не пытайтесь связаться с командой osu! (или с членами волонтёрских команд) через Twitter, Discord или любую другую платформу, чтобы обойти систему — они вам ничем не смогут помочь.
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +## Часто встречающиеся причины ограничения акккаунта и кулдауны
```suggestion
## Часто встречающиеся причины рестрикта аккаунта и кулдауны
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Причина ограничения | Длительность кулдауна | Последствия |
```suggestion
| Причина рестрикта | Длительность кулдауна | Последствия |
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Мульти-аккаунтинг | Перманентный для мульти-аккаунтов | Основной аккаунт не получит ограничений, возможен сайленс. |
```suggestion
| Мульти-аккаунтинг | Навсегда для мульти-аккаунтов | Основной аккаунт не получит ограничений, возможен сайленс. |
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Чрезмерный мульти-аккаунтинг | 3 месяца | Нужно написать аппеляцию, Годовой бан в турнирах. |
```suggestion
| Чрезмерный мульти-аккаунтинг | 3 месяца | Нужно написать апелляцию, годовой турнирный бан. |
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Передача аккаунта | 3 месяца | Нужно написать аппеляцию, Годовой бан в турнирах, Частичный сброс аккаунта. |
```suggestion
| Передача аккаунта | 3 месяца | Нужно написать апелляцию, годовой турнирный бан, частичный откат аккаунта. |
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Читерство | 3 месяца | Нужно написать аппеляцию, Годовой бан в турнирах, Полный сброс аккаунта. |
```suggestion
| Использование читов | 3 месяца | Нужно написать апелляцию, годовой бан в турнирах, полный сброс аккаунта. |
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Чрезмерные проступки | Варьируется | Нужно написать аппеляцию, Кулдаун зависит от вашей истории. |
```suggestion
| Чрезмерные проступки | По-разному | Нужно написать аппеляцию, кулдаун зависит от вашей истории. |
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Читерство или передача аккаунта для игры на турнире | 6 месяцев | Нужно написать аппеляцию, Частичный сброс аккаунта, Перманентый бан на турнирах. |
```suggestion
| Использование читов/передача аккаунта для турнира | 6 месяцев | Нужно написать апелляцию, частичный откат аккаунта, турнирный бан навсегда. |
```

2021-08-02 02:30 UTC, UristMcKobold commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Повторные нарушения | 6 месяцев | Нужно написать аппеляцию, Частичный сброс аккаунта, Годовой бан на турнирах за одно нарушение. |
```suggestion
| Повторные нарушения | 6 месяцев | Нужно написать апелляцию, частичный откат аккаунта, годовой турнирный бан за каждое нарушение. |
```

2021-08-02 08:34 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +# Ограничение аккаунта
Честно, мне очень не нравится слово "рестрикт" из-за его "грубости" и созвучия с реструктом. Табличка рестрикта переведена на русский? если да - дайте скрин, у менянет мультиакков, чтобы проверить

2021-08-02 08:41 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Ограничение это перерыв от сообщества для аккаунтов, на которых наблюдалось ненормальное, подозрительное или нарушающее правила игры поведение.
Я в гитхабе нуб и хотел бы поменять местами рестрикт и ограничение здесь.

2021-08-02 08:43 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- Есдли вы убеждены, что ваше ограничение было ошибочным - пожалуйста, свяжитесь с нами немедленно, чтобы мы могли поговорить о вашей проблеме.
)

2021-08-10 15:07 UTC, Ceotom commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Ограничение это перерыв от сообщества для аккаунтов, на которых наблюдалось ненормальное, подозрительное или нарушающее правила игры поведение.
> Я в гитхабе нуб и хотел бы поменять местами рестрикт и ограничение здесь.

Просто сделайте коммит, в котором поменяны два слова местами
```suggestion
Ограничение (рестрикт) — это временная приостановка возможности взаимодействовать с сообществом для аккаунтов, на которых наблюдалось аномальное, подозрительное или нарушающее правила игры поведение.
```
Ну или так
Плюс вы не все предложенные изменения посмотрели

2021-08-10 20:26 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Ограничение это перерыв от сообщества для аккаунтов, на которых наблюдалось ненормальное, подозрительное или нарушающее правила игры поведение.
у меня кухня погорела, щас ремонтом занят. как смогу - чекну

2021-08-14 18:11 UTC, TicClick commented
напиши, когда ты всё от Кобольда применишь (или во всём откажешь), чтобы я своё ревью написал

2021-08-14 18:30 UTC, Dopaminos commented
раздражает что нельзя всё принять одной кнопкой, а после применения обновляется страница. минуту

2021-08-14 20:34 UTC, Dopaminos commented
@TicClick

2021-08-15 19:59 UTC, TicClick requested changes
как-то так. много фраз построены очень громоздко и иногда коряво, никто так не общается ни в интернете, ни тем более в жизни, это практически прямой перевод. мысли всегда можно переписать по-русски с сохранением основной идеи.

и да, в русском языке [не надо везде писать «вы», «ваш» и прочие притяжательные местоимения](https://www.artlebedev.ru/kovodstvo/sections/165/#08) (последний пункт)

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если аккаунт получил рестрикт правомерно, мы попросим пользователя подождать, прежде чем подавать апелляцию. Это называется *кулдаундом*, его длительность зависит от совершённых вами нарушений.
```suggestion
Если рестрикт был заслуженным, перед подачей апелляции нужно подождать. Время ожидания также называется *кулдаундом*, и его длительность зависит от совершённых нарушений.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Продолжайте наслаждаться игрой!** Пока ваш аккаунт в рестрикте и у вас кулдаун, вы всё ещё можете продолжать играть (пока вы играете на своём основной аккаунте!). Результаты, достигнутые вами во
```suggestion
- **Продолжайте наслаждаться игрой!** Во время рестрикта по-прежнему можно играть со своего основного аккаунта. Если игровую статистику аккаунта не будут сбрасывать, то рекорды, поставленные во время рестрикта, останутся с вами.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Ведите себя хорошо.** Мы понимаем, что рестрикт вызывает негативные эмоции, но думайте об этом как о шансе немного отдохнуть от сообщества. Постарайтесь избежать взаимодействия с сообществом игры
```suggestion
- **Ведите себя хорошо.** Несмотря на то, что рестрикт вызывает негативные эмоции, отнеситесь к нему как к шансу отдохнуть. Постарайтесь не пересекаться с другими игроками хотя бы несколько дней (будь это Discord, соцсети или иные способы общения), чтобы «остыть» и переосмыслить своё поведение.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Убедитесь, что вы соблюдаете правила.** Долговременный рестрикт — это наказание за нарушение правил. Если вы продолжите нарушать правила во время рестрикта, кулдаун может быть сброшен на три меся
```suggestion
- **Убедитесь, что вы соблюдаете правила.** Долговременный рестрикт — это наказание за нарушение правил. Если вы продолжите нарушать правила во время рестрикта, кулдаун может быть сброшен на три месяца с момента последнего нарушения. Это включает в себя, например, использование читов, передача доступа к аккаунту третьим лицам или создание новых аккаунтов для обхода рестрикта.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Следуйте инструкциям службы поддержки.** Трёхмесячный кулдаун — это шанс отдохнуть и поразмыслить над своими действиями. Если вы попытаетесь подать апелляцию до истечения кулдауна, ваши письма бу
```suggestion
- **Следуйте инструкциям службы поддержки.** Трёхмесячный кулдаун — это шанс отдохнуть и поразмыслить над своими действиями. Апелляции, поданные до истечения кулдауна, будут проигнорированы. Если вы не знаете, когда закончится кулдаун, или когда можно будет подать апелляцию, или с какого аккаунта можно играть (или отправлять апелляцию), спросите по электронной почте.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Не стесняйтесь обращаться к нам, если у вас есть вопросы.** Пока вы не пытаетесь обойти наказание, мы с радостью ответим вам на любые вопросы по поводу рестрикта вашего аккаунта!
```suggestion
- **Не стесняйтесь обращаться при наличии вопросов.** Если вы не пытаетесь обойти рестрикт, то мы с радостью на них ответим.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Вы можете подать апелляцию, написав письмо на [accounts@ppy.sh](mailto:accounts@ppy.sh), в котором будет написан ваш никнейм. Убедитесь, что вы отправляете апелляцию с адреса электронной почты, привя
```suggestion
Напишите письмо на [accounts@ppy.sh](mailto:accounts@ppy.sh), где будет указан ваш никнейм. Отправьте апелляцию с адреса электронной почты, привязанного к вашему аккаунту, и ждите ответа в течение недели. Если никто не ответил, свяжитесь с нами в твиттере или по электронной почте — есть шанс, что ваше письмо потерялось.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +В апелляции мы желаем видеть следующее:
```suggestion
Что нужно указать в апелляции:
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Почему мы должны позволить вам вернуться.** В большинстве своём, этот пункт тесно связан со вторым. Мы лишь хотим убедиться, что вы не будете снова нарушать правила! Пожалуйста поймите, что чем б
```suggestion
- **История аккаунта.** Много деталей не нужно, упомяните все ваши нарушения основных правил (мульти-аккаунтинг, передача аккаунта, читерство или крупные сайленсы). Главное здесь — честность: не страшно, если вы ненамеренно пропустите какой-то сайленс или не вспомните лишний аккаунт. В историю также нужно включить все нарушения, совершённые во время рестрикта (если они были).
- **Причина нарушения правил.** Объяснение того, что привело вас к решению создать новые аккаунты, передать свой аккаунт третьему лицу, использовать читы, и так далее. Это поможет понять, насколько вы склонны снова нарушить правила. Если вы продолжали их нарушать во время рестрикта, то нужно написать почему.
- **С помощью чего вы это сделали.** В основном это относится к читерству: мы хотим знать, как вы нашли читы, откуда скачали их, и оставили ли у себя на компьютере.
- **Почему мы должны позволить вам вернуться.** В большинстве случаев этот пункт тесно связан со вторым. Мы хотим убедиться, что вы не будете снова нарушать правила! Обратите внимание, что чем больше было нарушений, тем больше ожидается аргументов в вашу пользу.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если мы решим позволить вам вернуться, мы потребуем, чтобы вы согласились с некоторыми условиями для снятия рестрикта с вашего аккаунта.
```suggestion
Потребуется, чтобы вы согласились с некоторыми условиями для снятия рестрикта с аккаунта:
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Любое серьёзное нарушение влечёт за собой немедленный рестрикт вашего аккаунта**. Это включает в себя крупные сайленсы.
```suggestion
- **Вы больше не будете нарушать правила.** Сюда также входят читерство и передачу аккаунта.
- **Вы больше не будете создавать новые аккаунты, будь они для вас или кого-либо ещё.**
- **Вы не должны связываться с другими аккаунтами.** Это включает в себя игру за общими компьютерами.
- **Любое серьёзное нарушение влечёт за собой немедленный рестрикт вашего аккаунта**. Это включает в себя крупные сайленсы.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Также, в течение одного года мы не будем изменять флаг вашего аккаунта.
```suggestion
Кроме того, в течение одного года нельзя будет изменять флаг аккаунта.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +В некоторых случаях, возвращающемуся по апелляции может быть отказано в участии в официальных турнирах и турнирах с наградой в виде значка в профиле, как в роли участника, так и в роли одного из орга
```suggestion
В некоторых случаях в условия снятия рестрикта входит отказ в участии в официальных турнирах и турнирах с наградой в виде значка в профиле, как в роли участника, так и в роли одного из организаторов турнира. Длительность такого ограничения составляет 1 год за нарушение (если у пользователя это уже вторая апелляция, бан длится 2 года). В письме со снятием рестрикта будет указан срок ограничения.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +**Использование читов или передача аккаунта во время официального турнира или турнира с наградой в виде значка в профиле приведёт к навечному бану пользователя в любых будущих турнирах.** Этот бан не
```suggestion
**Использование читов или передача аккаунта во время официального турнира или турнира с наградой в виде значка в профиле приведёт к навечному бану пользователя в любых будущих турнирах.** На такой бан нельзя подавать апелляцию (она будет проигнорирована), и он не будет снят или сокращён ни при каких условиях.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Некоторые игроки могут получить рестрикт, если они начнут играть после того, как их апелляция будет одобрена. Это автоматический процесс, и рестрикт снимут в течение 24 часов. Не стесняйтесь задавать
```suggestion
Иногда в рестрикт можно автоматически попасть уже после одобрения апелляции. В случае ошибки рестрикт будет снят в течение 24 часов. Если с вами случилось ровно это, не стесняйтесь писать в твиттер [@osusupport](https://twitter.com/osusupport) или письма по адресу [accounts@ppy.sh](mailto:accounts@ppy.sh).
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +После некоторых нарушений ваш аккаунт откатят назад. Это делается для того, чтобы удалить ваши рекорды, сделанные нечестно **во всех режимах игры**, а также и разблокированные медали и значки. **Коли
```suggestion
После некоторых нарушений статистику аккаунта могут сбросить (частично или полностью). Это делается для того, чтобы удалить нечестно полученные рекорды **во всех режимах игры**, а также разблокированные медали и значки. **Количество игр и время игры сброшено не будет.**
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Ваша апелляция может быть отклонена по нескольким причинам.
```suggestion
Апелляция может быть отклонена по нескольким причинам.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Ваша история слишком плоха.** Злостных нарушителей или игроков, чьи аккаунты были рестриктнуты после недавно принятой апелляции, мы можем посчитать, что сейчас их история слишком плоха, чтобы дат
```suggestion
- **Вы прислали её слишком рано.** Если кулдаун ещё не прошел, то апелляция будет отклонена. Если вы не уверены в сроке подачи апелляции, ответьте на письмо с отказом, и мы уточним дату.
- **Апелляция была недостаточно полной.** Вас попросят написать её заново, если упомянутые четыре пункта были плохо раскрыты; кулдаун при этом **не** сбрасывается. В то же время при попытке соглать или скрыть серьёзные нарушения правил (в основном мультиаккаунтинг или использование читов) апелляцию отклонят из-за недостоверности, а кулдаун будет сброшен до трех месяцев. Это ещё один шанс подумать о проступках и убедиться, что вы ничего не забыли.
- **Вы обходили рестрикт или играли на других аккаунтах.** Регистрация нового аккаунта для обхода рестрикта считается за попытку избежать наказания и сбрасывает кулдаун до трёх месяцев с момента регистрации аккаунта. При частых попытках обойти ограничения апелляцию могут отклонить навсегда. Если вы пользуетесь мультиаккаунтами или играете на них во время рестрикта, кулдаун также может быть сброшен. Помните, что мультиаккаунтинг запрещён [правилами](/wiki/Rules), и играть можно только на своём основном аккаунте. Если вы не знаете, какой именно из аккаунтов — основной, спросите об этом по электронной почте.
- **Вы продолжили нарушать правила после рестрикта.** Снимать рестрикт в этом случае бессмысленно. При повторных нарушениях кулдаун будет сброшен до последнего нарушения. В случаях серьёзных или многочисленных нарушений апелляцию могут отклонить навсегда.
- **У вас слишком много нарушений.** В подобных случаях мы можем посчитать, что вам пока не стоит возвращаться в игру. Чтобы показать, что в будущем вы не собираетесь нарушать правила, рекомендуется выждать **очень долгое время** перед следующей апелляцией.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +## Мои письма игнорируют / Я не думаю, что моя апелляция была справедливо разобрана
```suggestion
## Мои письма игнорируют / Мне кажется, что мою апелляцию не полностью рассмотрели
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если вам кажется, что ваши электронные письма не читаются или не рассматриваются должным образом нашей службой поддержки, отправьте нам письмо по адресу [appeal-review@ppy.sh](mailto:appeal-review@pp
```suggestion
Если вы считаете, что ваши обращения игнорируются или не рассматриваются должным образом, отправьте по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh) письмо со следующей информацией:
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- Краткое изложение причин, по которым вы не согласны с решением по вашей апелляции (если это к вам относится)
```suggestion
- Как долго ваш аккаунт был в рестрикте
- Основная причина рестрикта
- Все предыдущие апелляции, которые были проигнорированы или несправедливо разобраны
- Краткое изложение причин, по которым вы не согласны с решением по апелляции (в случае отказа)
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +**Мы отвечаем на запросы по повторному рассмотрению ваших апелляций только по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** Пожалуйста, не пытайтесь связаться с командой osu! (или с ч
```suggestion
Все письма, отправленные на этот адрес, будут изучены третьей стороной, которая не участвует в ежедневной работе службы поддержки, и помечены к пересмотру или дальнейшей проверке.

Учтите, что гарантируется только получение ответа и повторное рассмотрение ситуации и ничего больше. Решение не будет пересмотрено, если выяснится, что условия апелляции не были выполнены (соблюдение правил и остальные).

**Пересмотр апелляций принимается только по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** Пожалуйста, не пытайтесь связаться с командой osu! (или с добровольцами из других команд) через Twitter, Discord или любую другую платформу, чтобы обойти это ограничение, — они вам ничем не смогут помочь.
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +## Часто встречающиеся причины рестрикта аккаунта и кулдауны
```suggestion
## Наиболее частые причины рестрикта и кулдауны
```

2021-08-15 19:59 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Повторные нарушения | 6 месяцев | Нужно написать апелляцию, частичный откат аккаунта, годовой турнирный бан за каждое нарушение. |
```suggestion
| Ошибка автоматической системы | Без кулдауна | Если аккаунт был ограничен по ошибке, то ничего не случится. |
| Мульти-аккаунтинг | Навсегда для мульти-аккаунтов | Основной аккаунт не получит ограничений, но возможен сайленс. |
| Чрезмерный мульти-аккаунтинг | 3 месяца | Необходимость апелляции, годовой турнирный бан. |
| Передача аккаунта третьим лицам | 3 месяца | Необходимость апелляции, годовой турнирный бан, частичный сброс аккаунта. |
| Использование читов | 3 месяца | Необходимость апелляции, годовой турнирный бан, полный сброс аккаунта. |
| Серьёзные нарушения правил | По-разному | Нужно написать аппеляцию, длительность кулдауна зависит от нарушений. |
| Использование читов/передача аккаунта для турнира | 6 месяцев | Необходимость апелляции, частичный сброс аккаунта, турнирный бан навсегда. |
| Повторные нарушения | 6 месяцев | Необходимость апелляции, частичный сброс аккаунта, годовой турнирный бан за каждое нарушение. |
```

2021-08-15 20:24 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Подождите 24 часа.** Некоторые рестрикты могут быть результатом автоматического процесса. Поскольку мы проверяем новые случаи рестриктов ежедневно, пожалуйста, подождите 24 часа — если ваш рестри
вФАРИжщшоФУВАШЩРИоЩУВШригощшу

2021-08-15 20:25 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если ваш аккаунт попал в рестрикт за нарушение [правил](/wiki/Rules), то на вас накладывается безоговорочный трёхмесячный кулдаун, по истечению которого вы сможете написать апелляцию.
я запутываюсь какую речь использовать, формальную, или более т.с. "нежную" aetyheTAILUHGwguihoETIUOP

2021-08-15 20:27 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если ваш аккаунт попал в рестрикт за нарушение [правил](/wiki/Rules), то на вас накладывается безоговорочный трёхмесячный кулдаун, по истечению которого вы сможете написать апелляцию.
что такое «нежная речь»? тут две проблемы: куча выканья (и так понятно, что речь идёт про аккаунт того, к кому обращаются, это лишнее уточнение) и переусложнённая фраза

2021-08-15 20:28 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Продолжайте наслаждаться игрой!** Пока ваш аккаунт в рестрикте и у вас кулдаун, вы всё ещё можете продолжать играть (пока вы играете на своём основной аккаунте!). Результаты, достигнутые вами во
ROLL BACK И СБРОСИТЬ тут одно и то же AIKLEJURGHNLwetaujighnERTILOUGHNLTEliuhgj

2021-08-15 20:32 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +В некоторых случаях, возвращающемуся по апелляции может быть отказано в участии в официальных турнирах и турнирах с наградой в виде значка в профиле, как в роли участника, так и в роли одного из орга
я хз как изменить, но тут нужно "запрет на участие"

2021-08-15 20:34 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Повторные нарушения | 6 месяцев | Нужно написать апелляцию, частичный откат аккаунта, годовой турнирный бан за каждое нарушение. |
в 113 строке забыл  Необходимость апелляции

2021-08-15 20:36 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +В некоторых случаях, возвращающемуся по апелляции может быть отказано в участии в официальных турнирах и турнирах с наградой в виде значка в профиле, как в роли участника, так и в роли одного из орга
исправил

2021-08-15 20:36 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Почему мы должны позволить вам вернуться.** В большинстве своём, этот пункт тесно связан со вторым. Мы лишь хотим убедиться, что вы не будете снова нарушать правила! Пожалуйста поймите, что чем б
Я бы оставил "Почему вы нарушили правила", потому-что при составлении апелляции мне бы было приятней отвечать на вопрос, чем писать сочинение хз

2021-08-15 20:37 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +| Повторные нарушения | 6 месяцев | Нужно написать апелляцию, частичный откат аккаунта, годовой турнирный бан за каждое нарушение. |
поменял

2021-08-15 20:37 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Почему мы должны позволить вам вернуться.** В большинстве своём, этот пункт тесно связан со вторым. Мы лишь хотим убедиться, что вы не будете снова нарушать правила! Пожалуйста поймите, что чем б
а какая разница? что так, что так одно и то же нужно писать

2021-08-15 20:38 UTC, Dopaminos commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Почему мы должны позволить вам вернуться.** В большинстве своём, этот пункт тесно связан со вторым. Мы лишь хотим убедиться, что вы не будете снова нарушать правила! Пожалуйста поймите, что чем б
shrug

2021-08-15 20:38 UTC, Dopaminos commented
готово ig?

2021-08-15 20:40 UTC, Dopaminos commented
если ре-реквест был лишним - сорян, яж маппер, у бнов речек есть, привычка

2021-08-15 20:45 UTC, TicClick commented
не, всё нормально. я потом ещё раз посмотрю, может, пропустил что

2021-08-15 21:50 UTC, TicClick requested changes
последние штрихи

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- Если вы точно убеждены, что рестрикт был ошибочным, свяжитесь с нами как можно скорее для пересмотра ограничений.
```suggestion
- **Подождите 24 часа.** Иногда рестрикт выдаётся автоматически. Если это произошло по ошибке, то ограничение будет снято в течение 24 часов, так как новые случаи рестриктов проверяются ежедневно.
- **Свяжитесь со [службой поддержки по вопросам аккаунтов](/wiki/People/The_Team/Account_support_team).** Если аккаунт остался в рестрикте после 24 часов, напишите письмо на [accounts@ppy.sh](mailto:accounts@ppy.sh) **с электронной почты, привязанной к аккаунту**, чтобы выяснить подробности. Укажите в письме свой ник, а также все возможные причины, по которым аккаунт мог попасть в рестрикт. Чем больше подробностей, тем проще будет решить проблему.
- Если вы точно убеждены, что рестрикт был ошибочным, свяжитесь с нами как можно скорее для пересмотра ограничений.
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если аккаунт попал в рестрикт за нарушение [правил](/wiki/Rules), то перед отправки апелляции обязательно должно пройти как минимум три месяца.
```suggestion
Если аккаунт попал в рестрикт за нарушение [правил](/wiki/Rules), то перед отправкой апелляции обязательно должно пройти как минимум три месяца.
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Если вы недавно подавали апелляцию, и она была одобрена, а потом вы снова получили рестрикт после игры, не переживайте. Ошибочные рестрикты, выданные автоматически, будут сняты в течение 24 часов. Ес
```suggestion
Если у вас несколько аккаунтов, и основной из них не попал в рестрикт, им можно пользоваться дальше. Не используйте другие аккаунты, так как это может привести к дальнейшим санкциям.

Если вы недавно подавали апелляцию, и она была одобрена, а потом вы снова получили рестрикт после игры, не переживайте. Ошибочные рестрикты, выданные автоматически, будут сняты в течение 24 часов. Если требуется более быстрая реакция, отправьте нам письмо или твит.
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Это не ваш первый аккаунт.** Мульти-аккаунтинг запрещён правилами. Чаще всего с самого первого созданного аккаунта можно играть дальше, но все остальные аккаунты навсегда попадут в рестрикт. В ос
```suggestion
- **Это не ваш первый аккаунт.** Мульти-аккаунтинг запрещён правилами. Чаще всего с самого первого созданного аккаунта можно играть дальше, но все остальные аккаунты навсегда попадут в рестрикт. В особых случаях на первый аккаунт может быть наложен предупредительный сайленс, чтобы предостеречь от регистрации новых аккаунтов, а если он не поможет, то рестрикт. Если один из аккаунтов был ограничен, но у вас есть остальные, пожалуйста, не пользуйтесь ими и играйте только на первом аккаунте. Если вы потеряли доступ к первому аккаунту или не можете его активировать, свяжитесь с [accounts@ppy.sh](mailto:accounts@ppy.sh) для восстановления доступа.
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Вашим аккаунтом кто-то пользовался.** Правила также запрещают делить аккаунт с другими игроками. Если это происходит, то аккаунт ограничивают, а другой игрок либо получает длительный сайленс, либ
```suggestion
- **Вашим аккаунтом кто-то пользовался.** Правила запрещают делить аккаунт с другими игроками. Если это происходит, то аккаунт ограничивают, а другой игрок либо получает длительный сайленс, либо сам попадает в рестрикт. Если это было ненамеренным, свяжитесь с нами через [accounts@ppy.sh](mailto:accounts@ppy.sh) как можно скорее.
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +- **Убедитесь, что вы соблюдаете правила.** Долговременный рестрикт — это наказание за нарушение правил. Если вы продолжите нарушать правила во время рестрикта, кулдаун может быть сброшен на три меся
```suggestion
- **Убедитесь, что вы соблюдаете правила.** Долговременный рестрикт — это наказание за нарушение правил. Если вы продолжите нарушать правила во время рестрикта, кулдаун может быть сброшен на три месяца с момента последнего нарушения. Это включает в себя, например, использование читов, передачу доступа к аккаунту третьим лицам, или создание новых аккаунтов для обхода рестрикта.
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Напишите письмо на [accounts@ppy.sh](mailto:accounts@ppy.sh), где будет указан ваш никнейм. Отправьте апелляцию с адреса электронной почты, привязанного к вашему аккаунту, и ждите ответа в течение не
```suggestion
Напишите письмо на [accounts@ppy.sh](mailto:accounts@ppy.sh), где будет указан ваш никнейм. Отправьте апелляцию с адреса электронной почты, привязанного к вашему аккаунту, и ждите ответа в течение недели. Если никто не ответил, свяжитесь с нами в твиттере или по электронной почте: есть шанс, что ваше письмо потерялось.
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +Иногда в рестрикт можно автоматически попасть уже после одобрения апелляции. В случае ошибки рестрикт будет снят в течение 24 часов. Если с вами случилось ровно это, не стесняйтесь писать в твиттер [
```suggestion
Иногда в рестрикт можно автоматически попасть уже после одобрения апелляции. В случае ошибки рестрикт будет снят в течение 24 часов. Если с вами случилось ровно это, не стесняйтесь писать в твиттер [@osusupport](https://twitter.com/osusupport) или по адресу электронной почты [accounts@ppy.sh](mailto:accounts@ppy.sh).
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +После некоторых нарушений статистику аккаунта могут сбросить (частично или полностью). Это делается для того, чтобы удалить нечестно полученные рекорды **во всех режимах игры**, а также разблокирован
```suggestion
После некоторых нарушений статистику аккаунта могут частично или полностью сбросить. Это делается для того, чтобы удалить нечестно полученные рекорды **во всех режимах игры**, а также разблокированные медали и значки. **Число игр и время игры сброшено не будет.**
```

2021-08-15 21:50 UTC, TicClick commented on wiki/Help_Centre/Account_Restrictions/ru.md
> +**Пересмотр апелляций принимается только по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** Пожалуйста, не пытайтесь связаться с командой osu! (или с добровольцами из других команд) чер
```suggestion
**Пересмотр апелляций принимается только по адресу [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh).** Пожалуйста, не пытайтесь связаться с командой osu! (или членами других команд) через Twitter, Discord или любую другую платформу, чтобы обойти это ограничение, — они вам ничем не смогут помочь.
```

2021-08-16 11:08 UTC, Dopaminos commented
@TicClick

2021-08-16 17:31 UTC, TicClick approved these changes

2021-08-16 17:31 UTC, TicClick commented
возьми в следующий раз статью поменьше, чтобы не так много правок нужно было делать (ну или постарайся применить мои рекомендации, чтобы было более складно написано)

2021-08-16 17:31 UTC, merged

2021-08-16 17:57 UTC, Dopaminos commented
окей, у меня wip три статьи, лень доделывать пока