[ID]Update `Twitter`
ppy/osu-wiki pull request #5914
Opened 2021-07-30 07:48 UTC by ZeroPyrozen

Update Twitter article for Indonesian translation

2021-07-30 13:46 UTC, hikikuman commented on wiki/Twitter/id.md
> +osu! memiliki beberapa akun Twitter, masing-masing melayani tujuan tertentu. Sebagian besar memiliki lalu lintas sangat rendah tetapi akan membantu anda dalam mendapatkan informasi di luar lingkungan
```suggestion
osu! memiliki beberapa akun Twitter, masing-masing melayani tujuan tertentu. Sebagian besar memiliki lalu lintas sangat rendah tetapi akan membantu kamu dalam mendapatkan informasi di luar lingkungan osu!.
```

2021-07-30 13:46 UTC, hikikuman commented on wiki/Twitter/id.md
> +| ![Avatar osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport) | Membantu anda dengan masalah akun/komunitas. Dikelola oleh [account support team](/wiki/People/The_Team/
```suggestion
| ![Avatar osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport) | Membantu kamu terkait dengan masalah akun/komunitas. Dikelola oleh [account support team](/wiki/People/The_Team/Account_support_team). |
```

2021-07-30 13:46 UTC, hikikuman commented on wiki/Twitter/id.md
> +| ![Avatar osu!status](img/osustatus.jpg) | [@osustatus](https://twitter.com/osustatus) | Diperuntukkan untuk menyediakan pemberitahuan, dengan lalu lintas rendah, tentang masalah situs dan [Bancho](
```suggestion
| ![Avatar osu!status](img/osustatus.jpg) | [@osustatus](https://twitter.com/osustatus "Twitter") | Diperuntukkan untuk menyediakan pemberitahuan, dengan lalu lintas rendah, tentang masalah situs dan [Bancho](/wiki/Bancho_(server)). |
```

2021-07-30 13:46 UTC, hikikuman commented on wiki/Twitter/id.md
> +| ![Avatar osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport) | Membantu anda dengan masalah akun/komunitas. Dikelola oleh [account support team](/wiki/People/The_Team/
```suggestion
| ![Avatar osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport "Twitter") | Membantu anda dengan masalah akun/komunitas. Dikelola oleh [account support team](/wiki/People/The_Team/Account_support_team). |
```

2021-07-30 13:46 UTC, hikikuman commented on wiki/Twitter/id.md
>  | ![Avatar BanchoBoat](img/banchoboat.jpg) | [@banchoboat](https://twitter.com/banchoboat) | Bantuan komedi ketika ada yang salah. |
```suggestion
| ![Avatar BanchoBoat](img/banchoboat.jpg) | [@banchoboat](https://twitter.com/banchoboat "Twitter") | Bantuan komedi ketika ada yang salah. |
```

2021-07-30 14:06 UTC, hikikuman approved these changes

2021-07-30 14:32 UTC, mousesalt requested changes

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +osu! memiliki beberapa akun Twitter, masing-masing melayani tujuan tertentu. Sebagian besar memiliki lalu lintas sangat rendah tetapi akan membantu kamu dalam mendapatkan informasi di luar lingkungan
```suggestion
osu! memiliki beberapa akun Twitter, masing-masing akun melayani untuk tujuan tertentu. Sebagian besar akun memiliki lalu lintas yang sangat rendah tetapi akan membantu kamu dalam mendapatkan informasi di luar lingkungan osu!.
```

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| Avatar | Handle | Deskripsi |
```suggestion
| Avatar | Akun | Deskripsi |
```

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +osu! memiliki beberapa akun Twitter, masing-masing melayani tujuan tertentu. Sebagian besar memiliki lalu lintas sangat rendah tetapi akan membantu kamu dalam mendapatkan informasi di luar lingkungan
this may keep better wording with more detail explanation

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| Avatar | Handle | Deskripsi |
```suggestion
| Avatar | Akun | Deskripsi |
```

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| Avatar | Handle | Deskripsi |
don't really understand why `handle` there without translation, using kind detail help people to understand

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| ![Avatar osu!status](img/osustatus.jpg) | [@osustatus](https://twitter.com/osustatus "Twitter") | Diperuntukkan untuk menyediakan pemberitahuan, dengan lalu lintas rendah, tentang masalah situs dan
```suggestion
| ![Avatar osu!status](img/osustatus.jpg) | [@osustatus](https://twitter.com/osustatus "Twitter") | Diperuntukkan untuk penyediaan notifikasi dengan lalu lintas rendah tentang masalah situs dan [Bancho](/wiki/Bancho_(server)). |
```

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| ![Avatar osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport "Twitter") | Membantu kamu terkait masalah akun/komunitas. Dikelola oleh [account support team](/wiki/Peopl
```suggestion
| ![Avatar osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport "Twitter") | Diperuntukkan untuk mengatasi masalah mengenai akun maupun komunitas. Dikelola oleh [account support team](/wiki/People/The_Team/Account_support_team). |
```

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| ![Avatar osu!status](img/osustatus.jpg) | [@osustatus](https://twitter.com/osustatus "Twitter") | Diperuntukkan untuk menyediakan pemberitahuan, dengan lalu lintas rendah, tentang masalah situs dan
serving and service is different

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| ![Avatar osu! support](img/osusupport.jpg) | [@osusupport](https://twitter.com/osusupport "Twitter") | Membantu kamu terkait masalah akun/komunitas. Dikelola oleh [account support team](/wiki/Peopl
gonna be sticking consistently with previous wording as well to helping people understand

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| Avatar | Handle | Deskripsi |
```suggestion
| Avatar | Akun | Deskripsi |
```

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| ![Avatar Dean Herbert](img/ppy.jpg) | [@ppy](https://twitter.com/ppy "Twitter") | Akun pribadi [pembuat osu!](/wiki/People/peppy), yang berisi konten yang tidak selalu terkait osu!, namun masih mem
```suggestion
| ![Avatar Dean Herbert](img/ppy.jpg) | [@ppy](https://twitter.com/ppy "Twitter") | Akun Twitter pribadi [pembuat osu!](/wiki/People/peppy), yang mana berisi konten tidak selalu terkait osu!, namun masih membahas banyak hal terkait osu! juga. |
```

2021-07-30 14:32 UTC, mousesalt commented on wiki/Twitter/id.md
> +| ![Avatar Dean Herbert](img/ppy.jpg) | [@ppy](https://twitter.com/ppy "Twitter") | Akun pribadi [pembuat osu!](/wiki/People/peppy), yang berisi konten yang tidak selalu terkait osu!, namun masih mem
added detail information which account ppy have and remove double word in a sentence.

2021-07-30 17:25 UTC, mousesalt approved these changes
:+1:

2021-08-02 05:43 UTC, hikikuman approved these changes

2021-08-07 00:01 UTC, TPGPL approved these changes

2021-08-07 00:01 UTC, merged