[FR] Update `Community Contributors`, `People` and `Users with unique title`
ppy/osu-wiki pull request #5917
Opened 2021-07-30 17:13 UTC by DoryanR

Update of the translations of the following wiki pages:

- `People/Community_Contributors`
- `People/Users_with_unique_titles`
- `People`

2021-08-15 17:41 UTC, Ganondorf-1 requested changes

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +Les **contributeurs de la communauté** sont les personnes qui ont fournit des services à la communauté osu! à grands frais pour elles-mêmes - des outils et des fonctionnalités que beaucoup d'entre no
```suggestion
Les **contributeurs de la communauté** sont les utilisateurs ayant fourni des services à la communauté d'osu! à grands frais pour elles-mêmes - des outils et des fonctionnalités que beaucoup d'entre nous prennent pour acquis aujourd'hui. Ces utilisateurs reçoivent un badge pour indiquer qu'ils ont fait quelque chose de remarquable pour l'ensemble de la communauté.
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [nanashiRei](https://osu.ppy.sh/users/807630) | L'hébergement et la maintenance de l'un des plus anciens sites d'osu! [beatmap mirrors](https://osu.yas-online.net/). |
```suggestion
| ![][flag_DE] [nanashiRei](https://osu.ppy.sh/users/807630) | Hébergement et maintenance de l'un des plus anciens [sites miroirs de beatmaps](https://osu.yas-online.net/) d'osu!. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [RBRat3](https://osu.ppy.sh/users/307202) | Nombreuses (sans compter) contributions graphiques au client et à tout le reste. |
```suggestion
| ![][flag_US] [RBRat3](https://osu.ppy.sh/users/307202) | Nombre incalculable de contributions graphiques au client et à tout le reste. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_NL] [statementreply](https://osu.ppy.sh/users/126198) | Performances exceptionnelles dans les tests de correction de bugs et de fonctionnalités et dans le codage de nombreux utilitaires po
```suggestion
| ![][flag_NL] [statementreply](https://osu.ppy.sh/users/126198) | Performances exceptionnelles dans les tests de correction de bugs et de fonctionnalités ainsi que dans le codage de nombreux utilitaires pour les mappeurs et les moddeurs. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [Loctav](https://osu.ppy.sh/users/71366) | L'organisation de plusieurs grands tournois officiels (dont l'OWC). |
```suggestion
| ![][flag_DE] [Loctav](https://osu.ppy.sh/users/71366) | Organisation de plusieurs grands tournois officiels (dont l'OWC). |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [Blazevoir](https://osu.ppy.sh/users/120265) | Des antécédents fous en matière de modération (l'équivalent d'environ 6 membres du personnel) et la modération presque à elle seule de `#
```suggestion
| ![][flag_US] [Blazevoir](https://osu.ppy.sh/users/120265) | Antécédents fous en matière de modération (l'équivalent d'environ 6 membres du staff) et modération presque à elle seule du canal `#osu` pendant les heures de pointe (9k+ utilisateurs). |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [DeathxShinigami](https://osu.ppy.sh/users/49516) | Plus de 3 ans de travail silencieux à s'occuper inlassablement du [beatmap packing](https://osu.ppy.sh/beatmaps/packs) et plusieurs
```suggestion
| ![][flag_US] [DeathxShinigami](https://osu.ppy.sh/users/49516) | Plus de 3 ans de travail silencieux à s'occuper inlassablement du [beatmap packing](https://osu.ppy.sh/beatmaps/packs) et plusieurs années de gestion des beatmap charts. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_GR] [Sinistro](https://osu.ppy.sh/users/5530) | Être le premier gestionnaire de communauté et modérateur global, qui a placé la barre très haut pour les [GMT](/wiki/People/The_Team/Global_
```suggestion
| ![][flag_GR] [Sinistro](https://osu.ppy.sh/users/5530) | Premier gérant de communauté et modérateur global, qui a placé la barre très haut pour les [GMT](/wiki/People/The_Team/Global_Moderation_Team) à suivre. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [Ivalset](https://osu.ppy.sh/users/827) | Être le premier staff manager et BAT manager et former à lui seul une équipe de modération de beatmaps d'élite à partir de rien. |
```suggestion
| ![][flag_US] [Ivalset](https://osu.ppy.sh/users/827) | Premier staff manager et BAT manager et former à lui seul une équipe de modération de beatmaps d'élite à partir de rien. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_MX] [Repflez](https://osu.ppy.sh/users/201392) | Contribution exceptionnelle au osu! wiki |
```suggestion
| ![][flag_MX] [Repflez](https://osu.ppy.sh/users/201392) | Contribution exceptionnelle à l'osu! wiki |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_MY] [RaikireHiuduo](https://osu.ppy.sh/users/1570014) | Contribution exceptionnelle au osu! wiki |
```suggestion
| ![][flag_MY] [RaikireHiuduo](https://osu.ppy.sh/users/1570014) | Contribution exceptionnelle à l'osu! wiki |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [MoonShade](https://osu.ppy.sh/users/273649) | Développer des utilitaires de storyboarding révolutionnaires (SGL) |
```suggestion
| ![][flag_DE] [MoonShade](https://osu.ppy.sh/users/273649) | Développement d'utilitaires de storyboarding révolutionnaires (SGL) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_PL] [iys](https://osu.ppy.sh/users/322480) | Mikuia.tv - développement d'une boîte à outils pour les robots sur Twitch pour osu! |
```suggestion
| ![][flag_PL] [iys](https://osu.ppy.sh/users/322480) | Mikuia.tv - développement d'une boîte à outils pour les bots sur Twitch pour osu! |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [Tillerino](https://osu.ppy.sh/users/2070907) | Développement du robot de recommandation des beatmaps |
```suggestion
| ![][flag_DE] [Tillerino](https://osu.ppy.sh/users/2070907) | Développement du bot de recommandation de beatmaps |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +*Pour l'article du news, voir : [osu!weekly #53](https://osu.ppy.sh/home/news/2016-03-22-osuweekly-53)*
```suggestion
*Pour l'article de news, voir : [osu!weekly #53](https://osu.ppy.sh/home/news/2016-03-22-osuweekly-53)*
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418) | Des performances exemplaires en matière de construction et d'enseignement sur les beatmaps |
```suggestion
| ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418) | Performances exemplaires en matière de construction et d'enseignement sur les beatmaps |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [Okoratu](https://osu.ppy.sh/users/1623405) | Un leadership exceptionnel dans les affaires de gestion des beatmaps |
```suggestion
| ![][flag_DE] [Okoratu](https://osu.ppy.sh/users/1623405) | Leadership exceptionnel dans les affaires de gestion des beatmaps |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_HK] [IamKwaN](https://osu.ppy.sh/users/1856463) | Une présence de modération et une contribution globale remarquables |
```suggestion
| ![][flag_HK] [IamKwaN](https://osu.ppy.sh/users/1856463) | Présence de modération et contribution globale remarquables |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +*Pour l'article du news, voir : [Community Contributors: 2017](https://osu.ppy.sh/home/news/2017-12-24-community-contributors-2017)*
```suggestion
*Pour l'article de news, voir : [Community Contributors: 2017](https://osu.ppy.sh/home/news/2017-12-24-community-contributors-2017)*
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [OnosakiHito](https://osu.ppy.sh/users/290128) | Travail remarquable dans la formation de la première communauté osu!taiko, plusieurs années d'ancienneté dans le BAT/QAT. |
```suggestion
| ![][flag_DE] [OnosakiHito](https://osu.ppy.sh/users/290128) | Travail remarquable dans la formation de la première communauté d'osu!taiko, plusieurs années d'ancienneté dans la BAT/QAT. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [Garven](https://osu.ppy.sh/users/244216) | Des années de service dévoué au BAT/QAT, et une immense contribution à la refonte des critères de classement. |
```suggestion
| ![][flag_US] [Garven](https://osu.ppy.sh/users/244216) | Des années de service dévoué à la BAT/QAT, et une immense contribution à la refonte des critères de classement. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_NZ] [deadbeat](https://osu.ppy.sh/users/128370) | Une contribution exceptionnelle à d'innombrables projets médiatiques et tournois, ainsi qu'un mandat de longue durée au sein de la GMT. |
```suggestion
| ![][flag_NZ] [deadbeat](https://osu.ppy.sh/users/128370) | Contribution exceptionnelle à d'innombrables projets médiatiques et tournois, ainsi qu'un mandat de longue durée au sein de la GMT. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [Mao](https://osu.ppy.sh/users/2204515) | Des années de service dévoué au BAT/QAT, une présence majeure dans la refonte des critères de classement et la gestion du test Beatmap Nominat
```suggestion
| ![][flag_DE] [Mao](https://osu.ppy.sh/users/2204515) | Des années de service dévoué à la BAT/QAT, une présence majeure dans la refonte des critères de classement et la gestion du test Beatmap Nominator. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_CH] [Irreversible](https://osu.ppy.sh/users/1287964) | Une contribution dévouée au BAT/QAT pendant de nombreuses années. |
```suggestion
| ![][flag_CH] [Irreversible](https://osu.ppy.sh/users/1287964) | Une contribution dévouée à la BAT/QAT pendant de nombreuses années. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973) | Présence remarquable d'arbitres dans des dizaines de tournois communautaires |
```suggestion
| ![][flag_GB] [Yazzehh](https://osu.ppy.sh/users/7068973) | Présence remarquable à l'arbitrage de dizaines de tournois communautaires |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_CN] [kj415j45](https://osu.ppy.sh/users/9367540) | Contribution exceptionnelle et organisation du projet de localisation en chinois de osu!, osu! wiki, et osu!lazer |
```suggestion
| ![][flag_CN] [kj415j45](https://osu.ppy.sh/users/9367540) | Contribution exceptionnelle et organisation du projet de localisation en chinois d'osu!, osu! wiki, et osu!lazer |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [HappyStick](https://osu.ppy.sh/users/256802) | Organisation de la World Cup & Hôte de osu! Coffee Hour |
```suggestion
| ![][flag_US] [HappyStick](https://osu.ppy.sh/users/256802) | Organisation de la World Cup & hôte de la osu! Coffee Hour |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_AR] [juankristal](https://osu.ppy.sh/users/443656) | Contribution exceptionnelle à l'organisation de la World Cup  et aux tournois. |
```suggestion
| ![][flag_AR] [juankristal](https://osu.ppy.sh/users/443656) | Contribution exceptionnelle à l'organisation de la World Cup et aux tournois. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_CL] [WalterToro](https://osu.ppy.sh/users/5281416) | Contribution exceptionnelle en tant que membre de l'équipe GMT et du osu! wiki |
```suggestion
| ![][flag_CL] [WalterToro](https://osu.ppy.sh/users/5281416) | Contribution exceptionnelle en tant que membre de la GMT et de l'osu! wiki |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) | Chef d'équipe du Project Loved team |
```suggestion
| ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) | Chef d'équipe de la Project Loved Team |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [Zak](https://osu.ppy.sh/users/1375955) | Capitaine du projet Loved (osu!catch) |
```suggestion
| ![][flag_US] [Zak](https://osu.ppy.sh/users/1375955) | Capitaine du Project Loved (osu!catch) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [Backfire](https://osu.ppy.sh/users/263110) | Capitaine du projet Loved (osu!taiko) |
```suggestion
| ![][flag_US] [Backfire](https://osu.ppy.sh/users/263110) | Capitaine du Project Loved (osu!taiko) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [Tenshichan](https://osu.ppy.sh/users/1101600) | Capitaine du projet Loved (osu!catch) |
```suggestion
| ![][flag_DE] [Tenshichan](https://osu.ppy.sh/users/1101600) | Capitaine du Project Loved (osu!catch) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_PL] [Kamikaze](https://osu.ppy.sh/users/2124783) | Capitaine du projet Loved (osu!mania) |
```suggestion
| ![][flag_PL] [Kamikaze](https://osu.ppy.sh/users/2124783) | Capitaine du Project Loved (osu!mania) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_GB] [Pope Gadget](https://osu.ppy.sh/users/2288341) | Capitaine du projet Loved (osu!mania) |
```suggestion
| ![][flag_GB] [Pope Gadget](https://osu.ppy.sh/users/2288341) | Capitaine du Project Loved (osu!mania) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_SG] [hehe](https://osu.ppy.sh/users/2123087) | Contribution exceptionnelle au de mapping, aux événements et aux tournois. |
```suggestion
| ![][flag_SG] [hehe](https://osu.ppy.sh/users/2123087) | Contribution exceptionnelle au mapping, aux événements et aux tournois. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_US] [Noffy](https://osu.ppy.sh/users/1541323) | Contribution exceptionnelle au mapping, de modding et des métadonnées. |
```suggestion
| ![][flag_US] [Noffy](https://osu.ppy.sh/users/1541323) | Contribution exceptionnelle au mapping, au modding et aux métadonnées. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_GB] [Doomsday](https://osu.ppy.sh/users/18983) | Contribution exceptionnelle et inébranlable à la communauté osu! en général. |
```suggestion
| ![][flag_GB] [Doomsday](https://osu.ppy.sh/users/18983) | Contribution exceptionnelle et inébranlable à la communauté d'osu! en général. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_GB] [mangomizer](https://osu.ppy.sh/users/1893718) | Contribution exceptionnelle auxWorld Cups et aux événements communautaires |
```suggestion
| ![][flag_GB] [mangomizer](https://osu.ppy.sh/users/1893718) | Contribution exceptionnelle aux World Cups et aux événements communautaires |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [Lasse](https://osu.ppy.sh/users/896613) | Contribution exceptionnelle aux mapping et de modding |
```suggestion
| ![][flag_DE] [Lasse](https://osu.ppy.sh/users/896613) | Contribution exceptionnelle aux mapping et au modding |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ![][flag_DE] [RockRoller](https://osu.ppy.sh/users/8388854) | Contribution exceptionnelle à la scène du skinning et de modding d'osu! |
```suggestion
| ![][flag_DE] [RockRoller](https://osu.ppy.sh/users/8388854) | Contribution exceptionnelle à la scène de skinning et de modding d'osu! |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +Les titres d'utilisateurs sont généralement associés aux [groupes d'utilisateurs](/wiki/People/The_Team#user-groups), mais les utilisateurs listés ci-dessous ont reçu leur titre pour d'autres raisons
```suggestion
Les titres d'utilisateurs sont généralement associés aux [groupes d'utilisateurs](/wiki/People/The_Team#user-groups), mais les utilisateurs listés ci-dessous ont reçu leur titre pour d'autres raisons. La plupart des titres étaient des récompenses pour des contributions ou des réalisations, les autres étant des symboles de l'histoire emblématique ou amusante d'osu!.
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +Depuis 2020, l'activité des membres de la [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) en fav
```suggestion
Depuis 2020, l'activité des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et des membres de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) en faveur du système de classement est récompensée par le titre de **Elite Nominator**. Ce titre est attribué au début de chaque année pour les contributions apportées au cours de la précédente, et est retiré lorsque l'utilisateur quitte l'équipe.
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +Les gagnants du concours de mapping Aspire proposent une variante spéciale du titre Elite Mapper appelée **Elite Mapper : Aspire** comme prix.
```suggestion
Les gagnants du concours de mapping Aspire proposent une variante spéciale du titre Elite Mapper appelée **Elite Mapper : Aspirant** comme prix.
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +Les concours osu!remix attribuent le titre de **osu!mixer** comme prix de première place.
```suggestion
Les concours osu!remix attribuent le titre de **osu!mixer** comme premier prix.
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_NO] [-GN](https://osu.ppy.sh/users/895581) | Champion Above Champions | A marqué le premier FC NoMod sur [Shotgun Symphony+ [Impossibly Intense]](https://osu.ppy.sh/beatmapsets/7671#osu/32
```suggestion
| ![][flag_NO] [-GN](https://osu.ppy.sh/users/895581) | Champion Above Champions | A réalisé le premier FC NoMod sur [Shotgun Symphony+ [Impossibly Intense]](https://osu.ppy.sh/beatmapsets/7671#osu/32570) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_AU] [Jaye](https://osu.ppy.sh/users/4841352) | Drum Decimator | FC marqués sur toutes les cartes classées osu!taiko à partir du 3 novembre 2019. |
```suggestion
| ![][flag_AU] [Jaye](https://osu.ppy.sh/users/4841352) | Drum Decimator | A réalisé un FC sur toutes les beatmaps classées du mode osu!taiko le 3 novembre 2019. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_US] [xasuma](https://osu.ppy.sh/users/3172980) | The First Completionist | Joué à toutes les cartes Classée d'osu! en date du 27 avril 2019. |
```suggestion
| ![][flag_US] [xasuma](https://osu.ppy.sh/users/3172980) | The First Completionist | A réalisé un score sur toutes les beatmaps classés du mode osu! le 27 avril 2019. |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_DE] [Zetera](https://osu.ppy.sh/users/587737) | Medal Hunter | Gagne [The Hunt for the Girl in the Forest](https://osu.ppy.sh/community/forums/topics/662279) |
```suggestion
| ![][flag_DE] [Zetera](https://osu.ppy.sh/users/587737) | Medal Hunter | A gagné [The Hunt for the Girl in the Forest](https://osu.ppy.sh/community/forums/topics/662279) |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_CA] [Azer](https://osu.ppy.sh/users/2155578) | Organisateur du World Cup |
```suggestion
| ![][flag_CA] [Azer](https://osu.ppy.sh/users/2155578) | World Cup Organizer |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_US] [ChillierPear](https://osu.ppy.sh/users/9501251) | Organisateur du World Cup |
```suggestion
| ![][flag_US] [ChillierPear](https://osu.ppy.sh/users/9501251) | World Cup Organizer |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_BR] [LeoFLT](https://osu.ppy.sh/users/3668779) | Organisateur du World Cup |
```suggestion
| ![][flag_BR] [LeoFLT](https://osu.ppy.sh/users/3668779) | World Cup Organizer |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_NO] [MillhioreF](https://osu.ppy.sh/users/941094) | Testeur pro |
```suggestion
| ![][flag_NO] [MillhioreF](https://osu.ppy.sh/users/941094) | Pro Tester |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_NL] [statementreply](https://osu.ppy.sh/users/126198) | Testeur pro |
```suggestion
| ![][flag_NL] [statementreply](https://osu.ppy.sh/users/126198) | Pro Tester |
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/fr.md
>  # Personnes
```suggestion
# Utilisateurs
```

2021-08-15 17:41 UTC, Ganondorf-1 commented on wiki/People/fr.md
> +Page d'index pour les articles sur les personnes ou les groupes.
```suggestion
Page d'index pour les articles sur les utilisateurs ou les groupes.
```

2021-08-29 13:52 UTC, Ganondorf-1 requested changes

2021-08-29 13:52 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +Les **contributeurs de la communauté** sont les utilisateurs ayant fourni des services à la communauté d'osu! à grands frais pour elles-mêmes - des outils et des fonctionnalités que beaucoup d'entre
```suggestion
Les **contributeurs de la communauté** sont les utilisateurs ayant fourni des services à la communauté d'osu! à grands frais pour eux-mêmes - des outils et des fonctionnalités que beaucoup d'entre nous prennent pour acquis aujourd'hui. Ces utilisateurs reçoivent un badge pour indiquer qu'ils ont fait quelque chose de remarquable pour l'ensemble de la communauté.
```

2021-08-29 13:52 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +| ![][flag_US] [xasuma](https://osu.ppy.sh/users/3172980) | The First Completionist | A réalisé un score sur toutes les beatmaps classés du mode osu! le 27 avril 2019. |
```suggestion
| ![][flag_US] [xasuma](https://osu.ppy.sh/users/3172980) | The First Completionist | A réalisé un score sur toutes les beatmaps classées du mode osu! le 27 avril 2019. |
```

2021-08-31 12:05 UTC, Ganondorf-1 requested changes
Should be good to go once these changes are made

2021-08-31 12:05 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +Ces trois utilisateurs ont reçu le titre de **osu! Hall of Famer** pour avoir joué au jeu au plus haut niveau et contribué à l'époque où la communauté était encore jeune.
```suggestion
Ces trois utilisateurs ont reçu le titre **osu! Hall of Famer** pour avoir joué au jeu au plus haut niveau et contribué à l'époque où la communauté était encore jeune.
```

2021-08-31 12:05 UTC, Ganondorf-1 commented on wiki/People/Users_with_unique_titles/fr.md
> +Les storyboarders qui font preuve d'un talent exceptionnel en matière de storyboarding et qui impressionnent l'ensemble de la communauté reçoivent le titre de **Elite Storyboarder**.
```suggestion
Les storyboarders qui font preuve d'un talent exceptionnel en matière de storyboarding et qui impressionnent l'ensemble de la communauté reçoivent le titre **Elite Storyboarder**.
```

2021-09-02 21:42 UTC, TicClick approved these changes

2021-09-02 21:42 UTC, merged