[FR] Update `Developers`, `Global Moderation Team` and `Nomination Assessment Team`
ppy/osu-wiki pull request #5918
Opened 2021-07-30 18:34 UTC by DoryanR

Update of the translations of the following wiki pages:

- `People/The_Team/Developers`
- `People/The_Team/Global_Moderation_Team`
- `People/The_Team/Nomination_Assessment_Team`

2021-07-30 20:09 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +- **Modération :** Promouvoir la transparence entre la NAT et la communauté de mapping/modding, notamment en créant et en organisant des réunions.
```suggestion
- **Communication :** Promouvoir la transparence entre la NAT et la communauté de mapping/modding, notamment en créant et en organisant des réunions.
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +- **Structurel :** Documenter les sujets relatifs au processus de classement, modifier les règles et les directives relatives aux [critères de classement](/wiki/Ranking_Criteria), développer et maint
```suggestion
- **Structure :** Documenter les sujets relatifs au processus de classement, modifier les règles et les directives relatives aux [critères de classement](/wiki/Ranking_Criteria), développer et maintenir les outils et les sites web associés.
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Un membre de la NAT peut s'engager dans n'importe quelle tâche de la sous-catégorie de son choix, malgré la liste de ses responsabilités principales. Par exemple, si un membre du NAT donne la priorit
```suggestion
Un membre de la NAT peut s'engager dans n'importe quelle tâche de la sous-catégorie de son choix, malgré la liste de ses responsabilités principales. Par exemple, si un membre du NAT donne la priorité à la sous-catégorie `Structure`, il n'est pas responsable de toutes les tâches de cette sous-catégorie et il peut toujours aider aux tâches de toute autre sous-catégorie.
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +| ![][flag_GB] [hypercyte](https://osu.ppy.sh/users/9155377) | Bengali, un peu d'Arabe | Évaluation, Structurel, Modération, Modération |
```suggestion
| ![][flag_GB] [hypercyte](https://osu.ppy.sh/users/9155377) | Bengali, un peu d'Arabe | Évaluation, Structure, Modération, Modération |
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +| ![][flag_SE] [Naxess](https://osu.ppy.sh/users/8129817) | Suédois | Structurel, Modération |
```suggestion
| ![][flag_SE] [Naxess](https://osu.ppy.sh/users/8129817) | Suédois | Structure, Modération |
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +| ![][flag_US] [Noffy](https://osu.ppy.sh/users/1541323) |  | Évaluation, Structurel, Modération |
```suggestion
| ![][flag_US] [Noffy](https://osu.ppy.sh/users/1541323) |  | Évaluation, Structure, Modération |
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +| ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418) |  | Structurel |
```suggestion
| ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418) |  | Structure |
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +| ![][flag_BR] [Seto Kousuke](https://osu.ppy.sh/users/2857314) | Portugais | Évaluation, Structurel, Modération |
```suggestion
| ![][flag_BR] [Seto Kousuke](https://osu.ppy.sh/users/2857314) | Portugais | Évaluation, Structure, Modération |
```

2021-07-31 17:17 UTC, DoryanR commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +| ![][flag_NL] [Greaper](https://osu.ppy.sh/users/2369776) | Néerlandais | Évaluation, Structurel |
```suggestion
| ![][flag_NL] [Greaper](https://osu.ppy.sh/users/2369776) | Néerlandais | Évaluation, Structure |
```

2021-08-01 06:29 UTC, DoryanR commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +| ![][flag_PH] [Osu Tatakae Ouendan](https://osu.ppy.sh/users/594210) | Philippine | Modération du tchat |
```suggestion
| ![][flag_PH] [Osu Tatakae Ouendan](https://osu.ppy.sh/users/594210) | Philippin | Modération du tchat |
```

2021-08-01 06:29 UTC, DoryanR commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +| ![][flag_PH] [Nathanael](https://osu.ppy.sh/users/2295078) | Philippine | Modération du tchat, Modération du forum, Support technique |
```suggestion
| ![][flag_PH] [Nathanael](https://osu.ppy.sh/users/2295078) | Philippin | Modération du tchat, Modération du forum, Support technique |
```

2021-08-01 06:29 UTC, DoryanR commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +| ![][flag_KR] [ToGlette](https://osu.ppy.sh/users/1076236) | Coréen, Japonais, Philippine | Modération du tchat |
```suggestion
| ![][flag_KR] [ToGlette](https://osu.ppy.sh/users/1076236) | Coréen, Japonais, Philippin | Modération du tchat |
```

2021-08-01 06:29 UTC, DoryanR commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +| ![][flag_PH] [topecnz](https://osu.ppy.sh/users/2103927) | Philippine | Modération du tchat |
```suggestion
| ![][flag_PH] [topecnz](https://osu.ppy.sh/users/2103927) | Philippin | Modération du tchat |
```

2021-08-01 06:29 UTC, DoryanR commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
>  [flag_PH]: /wiki/shared/flag/PH.gif "Philippines"
```suggestion
[flag_PH]: /wiki/shared/flag/PH.gif "Philippine"
```

2021-08-11 21:27 UTC, Ganondorf-1 requested changes

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +***Remarque : pour signaler qu'un modérateur s'est mal comporté ou a enfreint le code de conduite des contributeurs, contactez l'[équipe d'assistance aux comptes](/wiki/People/The_Team/Account_suppor
```suggestion
***Remarque : pour signaler qu'un modérateur s'est mal comporté ou a enfreint le code de conduite des contributeurs, contactez l'[équipe de support aux comptes](/wiki/People/The_Team/Account_support_team#support@ppy.sh).***\
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +La Global Moderation Team est responsable du bien-être du tchat et du forum, et s'occupe des interactions au sein de la communauté. Vous pouvez vous adresser à elle pour toute question relative à la
```suggestion
La Global Moderation Team est responsable du bien-être du tchat et du forum, et s'occupe des interactions au sein de la communauté. Vous pouvez la solliciter pour toute question relative à la modération du jeu, ce qui inclut (mais ne se limite pas à) :
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +4. Soyez patient. Le GMT n'ajoute pas spontanément des membres qui aident depuis quelques jours seulement. Il faut du temps au GMT pour évaluer une personne - sa personnalité, ce qu'elle peut faire,
```suggestion
4. Soyez patient. La GMT n'ajoute pas spontanément des membres qui aident depuis quelques jours seulement. Il est nécessaire de donner du temps à la GMT afin d'évaluer une personne - sa personnalité, ce qu'elle peut faire, son activité, etc.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +En général, l'équipe observe les personnes pendant plusieurs semaines ou mois pour s'assurer qu'elles constituent un ajout valable à l'équipe. Veuillez être patient et ne pas en faire trop. N'hésitez
```suggestion
En général, l'équipe observe les utilisateurs pendant plusieurs semaines ou mois pour s'assurer que ceux-ci soient de bons candidats. Veuillez être patient et ne pas en faire trop. N'hésitez pas à demander à n'importe qui de l'équipe de GMT pour toute question concernant les règles, le signalement des utilisateurs, et tout autre problème.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +1. Ne demandez pas continuellement au GMT si vous êtes un candidat potentiel. Le GMT ne cherche pas à ajouter quelqu'un qui contribue comme un moyen d'arriver à ses fins. Un état d'esprit altruiste e
```suggestion
1. Ne demandez pas continuellement aux GMT si vous êtes un candidat potentiel. Les GMT ne cherchent pas à ajouter quelqu'un qui contribue comme un moyen d'arriver à ses fins. Un état d'esprit altruiste est essentiel.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +2. Ne signalez pas tout ce qui se passe dans le tchat. Il est important de savoir ce qui mérite d'être signalé et ce qui ne l'est pas.
```suggestion
2. Ne signalez pas tout ce qui se passe dans le tchat. Il est important de savoir ce qui mérite d'être signalé et ce qui ne le mérite pas.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +***Remarque : pour signaler qu'un membre de la NAT se comporte mal ou enfreint le code de conduite des contributeurs, contactez l'[équipe d'assistance aux comptes](/wiki/People/The_Team/Account_suppo
```suggestion
***Remarque : pour signaler qu'un membre de la NAT se comporte mal ou enfreint le code de conduite des contributeurs, contactez l'[équipe de support aux comptes](/wiki/People/The_Team/Account_support_team#support@ppy.sh).***
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +- **Évaluation :** Évaluer les compétences et l'activité des candidats et des Beatmap Nominator actuels. La plupart des membres du NAT sont responsables de la contribution à cette sous-catégorie.
```suggestion
- **Évaluation :** Évaluer les compétences et l'activité des candidats et des Beatmap Nominators actuels. La plupart des membres de la NAT sont responsables de la contribution à cette sous-catégorie.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +- **Modération :** Traiter les rapports des utilisateurs et évaluer le comportement inapproprié des Beatmap Nominators. Cette sous-catégorie est un effort conjoint entre le NAT et le GMT.
```suggestion
- **Modération :** Traiter les signalements des utilisateurs et évaluer le comportement inapproprié des Beatmap Nominators. Cette sous-catégorie est un effort conjoint entre la NAT et la GMT.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +En plus des capacités de modération, les NAT possèdent également la capacité de [nominer](/wiki/Beatmap_ranking_procedure#nominations), [qualifier](/wiki/Beatmap_ranking_procedure#qualification), et
```suggestion
En plus des droits de modération, les NAT possèdent également la capacité de [nominer](/wiki/Beatmap_ranking_procedure#nominations), [qualifier](/wiki/Beatmap_ranking_procedure#qualification), et [réinitialiser les nominations](/wiki/Beatmap_ranking_procedure#nomination-resets) sur les beatmaps. Dans ce domaine, ils sont considérés comme des [BN confirmés](/wiki/People/The_Team/Beatmap_Nominators#full-beatmap-nominators), et toutes les règles et attentes des BN, à part l'activité, s'appliquent aux membres des NAT. Les membres de la NAT ne sont pas censés nominer des beatmaps régulièrement comme le font les BN en raison de leurs responsabilités supplémentaires dans la communauté de modding et de mapping d'osu!.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Les membres du NAT qui contribuent principalement à la sous-catégorie `Évaluation` sont également responsables de modder au moins 3 beatmaps par mois. Cela garantit que le NAT est à jour avec la comm
```suggestion
Les membres de la NAT qui contribuent principalement à la sous-catégorie `Évaluation` sont également responsables de modder au moins 3 beatmaps par mois. Cela garantit que la NAT est à jour avec la communauté des moddeurs lors de l'évaluation des Beatmap Nominators. Les membres qui ne remplissent pas les conditions d'activité de modding recevront un avertissement. Si leur activité ne s'améliore pas au cours du mois suivant, ils seront retirés de la NAT. Les membres de la NAT travaillant sur d'autres projets liés au mapping peuvent être exemptés des exigences de modding au cas par cas.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Avant de rejoindre le NAT, un utilisateur doit être soit un membre à part entière des Beatmap Nominators, soit un ancien membre de la NAT et toujours impliqué dans la communauté. La plupart des candi
```suggestion
Avant de rejoindre la NAT, un utilisateur doit être soit un membre à part entière des Beatmap Nominators, soit un ancien membre de la NAT et toujours impliqué dans la communauté. La plupart des candidats à la NAT sont initialement considérés sur la base de leur engagement à aider la communauté de mapping et de modding, et une démonstration supplémentaire de leur capacité à contribuer aux quatre sous-catégories de responsabilités de la NAT est généralement la base de leur promotion.
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Comme la majorité des nouveaux membres de la NAT aideront à l'évaluation des BN, il est important que les candidats à la NAT soient très compétents pour évaluer les compétences des autres. Les BN tit
```suggestion
Comme la majorité des nouveaux membres de la NAT aideront à l'évaluation des BN, il est important que les candidats à la NAT soient très compétents pour évaluer les compétences des autres. Les BN confirmés ont la possibilité de faire des évaluations fictives en plus des évaluations réelles de la NAT, ce qui leur donne l'occasion de s'exercer. Un candidat à la NAT a de bien meilleures chances d'être promu si ses évaluations sont approfondies et aboutissent à des conclusions similaires à celles de la NAT (ou si elles sont étayées par des arguments).
```

2021-08-11 21:27 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Le NAT suit les candidats potentiels à la NAT sur de longues périodes, et se réunit occasionnellement pour décider si un candidat doit être promu, de la même manière que les évaluations des BN. Les B
```suggestion
La NAT suit les candidats potentiels à la NAT sur de longues périodes, et se réunit occasionnellement pour décider si un candidat doit être promu, de la même manière que les évaluations des BN. Les BN sont également autorisés à demander à rejoindre la NAT s'ils veulent recevoir un retour d'information et s'assurer que leur candidature est prise en compte. Cependant, en fonction de l'activité et des compétences de la NAT actuelle, il se peut qu'il n'y ait pas besoin de nouveaux membres. Les nouveaux NAT ne seront probablement promus que si l'un des membres actuels devient moins actif, ou s'il y a de nouvelles charges de travail nécessitant plus de membres, etc.
```

2021-08-15 17:00 UTC, Ganondorf-1 requested changes

2021-08-15 17:00 UTC, Ganondorf-1 commented on wiki/People/The_Team/Global_Moderation_Team/fr.md
> +[flag_PH]: /wiki/shared/flag/PH.gif "Philippine"
```suggestion
[flag_PH]: /wiki/shared/flag/PH.gif "Philippines"
```

2021-08-15 19:16 UTC, Ganondorf-1 commented on wiki/People/The_Team/Developers/fr.md
> +| User | Role |
```suggestion
| Nom | Rôle |
```

2021-08-15 19:18 UTC, Ganondorf-1 approved these changes

2021-08-16 18:17 UTC, TicClick approved these changes

2021-08-16 18:18 UTC, merged