[FR] Update `The Team`, `osu! Alumni`, `Support Team`
ppy/osu-wiki pull request #5921
Opened 2021-07-30 19:38 UTC by DoryanR

Update of the translations of the following wiki pages:

- `People/The_Team/Support_Team`
- `People/The_Team`
- `People/The_Team/osu!_Alumni`

2021-07-31 17:20 UTC, DoryanR commented on wiki/People/The_Team/Support_Team/fr.md
> +# Support Team
```suggestion
# Équipe du support
```

2021-07-31 17:20 UTC, DoryanR commented on wiki/People/The_Team/Support_Team/fr.md
> +La **Support Team**, également connue sous le nom de **Support Team Redux**, est composée de membres du personnel d'osu! qui se concentrent sur la modération de plusieurs sous-forums : [Development](
```suggestion
L'**Équipe du support**, également connue sous le nom de **Support Team Redux**, est composée de membres du personnel d'osu! qui se concentrent sur la modération de plusieurs sous-forums : [Development](https://osu.ppy.sh/community/forums/2), [Gameplay & Rankings](https://osu.ppy.sh/community/forums/13) (à l'exception de [Tournaments](https://osu.ppy.sh/community/forums/55) et [Mapping Techniques](https://osu.ppy.sh/community/forums/61)), [Skinning](https://osu.ppy.sh/community/forums/15), [Feature Requests](https://osu.ppy.sh/community/forums/4) et [Help](https://osu.ppy.sh/community/forums/5).
```

2021-07-31 17:20 UTC, DoryanR commented on wiki/People/The_Team/Support_Team/fr.md
> +La Support Team est responsable de :
```suggestion
L'Équipe du support est responsable de :
```

2021-07-31 17:20 UTC, DoryanR commented on wiki/People/The_Team/Support_Team/fr.md
> +*Remarque : Tous les membres de la Support Team parlent l'anglais en plus de la ou des langues énumérées ci-dessous, sauf indication contraire.*
```suggestion
*Remarque : Tous les membres de l'Équipe du support parlent l'anglais en plus de la ou des langues énumérées ci-dessous, sauf indication contraire.*
```

2021-07-31 17:20 UTC, DoryanR commented on wiki/People/The_Team/fr.md
> +| [Support Team](Support_Team) | Aide/Assistance aux demandes de fonctionnalités |
```suggestion
| [Équipe du support](Support_Team) | Aide/Assistance aux demandes de fonctionnalités |
```

2021-08-01 06:31 UTC, DoryanR commented on wiki/People/The_Team/Support_Team/fr.md
> +| ![][flag_PH] [Nathanael](https://osu.ppy.sh/users/2295078) | Philippine |
```suggestion
| ![][flag_PH] [Nathanael](https://osu.ppy.sh/users/2295078) | Philippin |
```

2021-08-01 06:31 UTC, DoryanR commented on wiki/People/The_Team/fr.md
>  [flag_PH]: /wiki/shared/flag/PH.gif "Philippines"
```suggestion
[flag_PH]: /wiki/shared/flag/PH.gif "Philippine"
```

2021-08-01 06:31 UTC, DoryanR commented on wiki/People/The_Team/osu!_Alumni/fr.md
>  [flag_PH]: /wiki/shared/flag/PH.gif "Philippines"
```suggestion
[flag_PH]: /wiki/shared/flag/PH.gif "Philippine"
```

2021-08-11 21:28 UTC, Ganondorf-1 commented on wiki/People/The_Team/Support_Team/fr.md
> +*Pour une équipe qui administre les comptes, voir : [Équipe d'assistance aux comptes](/wiki/People/The_Team/Account_support_team)*
```suggestion
*Pour une équipe qui administre les comptes, voir : [Équipe de support aux comptes](/wiki/People/The_Team/Account_support_team)*
```

2021-08-11 21:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Support_Team/fr.md
> +2. Organisation des fils de discussion dans [Feature Requests](https://osu.ppy.sh/community/forums/4) et [Help](https://osu.ppy.sh/community/forums/5), en les marquant comme *Resolved*, *Confirmed*,
```suggestion
2. Organiser des fils de discussion dans les sous-forums [Feature Requests](https://osu.ppy.sh/community/forums/4) et [Help](https://osu.ppy.sh/community/forums/5), en les marquant comme *Resolved*, *Confirmed*, *Invalid*, *Duplicate* et/ou *Added*.
```

2021-08-11 21:31 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_AU] [Zallius](https://osu.ppy.sh/users/55) | Espèces menacées d'extinction |
```suggestion
| ![][flag_AU] [Zallius](https://osu.ppy.sh/users/55) | Espèce en voie de disparition |
```

2021-08-11 21:31 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +En plus de ce qui précède, l'[équipe de soutien du compte](Account_support_team) est là pour aider à résoudre les problèmes hors de portée.
```suggestion
En plus de ce qui précède, l'[équipe de support aux comptes](Account_support_team) est là pour aider à résoudre les problèmes hors de portée.
```

2021-08-11 21:36 UTC, Ganondorf-1 commented on wiki/People/The_Team/osu!_Alumni/fr.md
> +| ![][flag_AU] [Oinari-sama](https://osu.ppy.sh/users/405508) | Modérateur de tchat, Équipe d'assistance |
```suggestion
| ![][flag_AU] [Oinari-sama](https://osu.ppy.sh/users/405508) | Modérateur de tchat, Équipe du support |
```

2021-08-11 21:36 UTC, Ganondorf-1 commented on wiki/People/The_Team/osu!_Alumni/fr.md
> +| ![][flag_CA] [Pawsu](https://osu.ppy.sh/users/2371454) | GMT, Équipe d'assistance |
```suggestion
| ![][flag_CA] [Pawsu](https://osu.ppy.sh/users/2371454) | GMT, Équipe du support |
```

2021-08-11 21:36 UTC, Ganondorf-1 commented on wiki/People/The_Team/osu!_Alumni/fr.md
> +| ![][flag_BE] [VeilStar](https://osu.ppy.sh/users/4255720) | GMT, Équipe d'assistance |
```suggestion
| ![][flag_BE] [VeilStar](https://osu.ppy.sh/users/4255720) | GMT, Équipe du support |
```

2021-08-11 21:37 UTC, Ganondorf-1 commented on wiki/People/The_Team/osu!_Alumni/fr.md
> +| ![][flag_FR] [XPJ38](https://osu.ppy.sh/users/273531) | Équipe d'assistance |
```suggestion
| ![][flag_FR] [XPJ38](https://osu.ppy.sh/users/273531) | Équipe du support |
```

2021-08-13 14:23 UTC, Ganondorf-1 requested changes

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_AU] [smoogipoo](https://osu.ppy.sh/users/1040328) | développeur d'osu!, amateur d'osu!mania, chasseur de bugs |
```suggestion
| ![][flag_AU] [smoogipoo](https://osu.ppy.sh/users/1040328) | Développeur d'osu!, amateur d'osu!mania, chasseur de bugs |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +Les groupes d'utilisateurs suivants sont constitués de membres de la communauté osu! qui contribuent à la maintenance d'osu!. La plupart de ces groupes d'utilisateurs peuvent être reconnus grâce aux
```suggestion
Les groupes d'utilisateurs suivants sont constitués de membres de la communauté d'osu! qui contribuent à la maintenance d'osu!. La plupart de ces groupes d'utilisateurs peuvent être reconnus grâce à leurs couleurs sur le forum, aux couleurs du tchat en jeu, aux titres des profils et/ou aux badges des profils.
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| [Nomination Assessment Team](Nomination_Assessment_Team) | Gère les Beatmap Nominators |
```suggestion
| [Nomination Assessment Team](Nomination_Assessment_Team) | Gérer les Beatmap Nominators |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| [osu! Alumni](osu!_Alumni) | Ceux qui sont connus pour leur contribution et qui sont partis depuis lors |
```suggestion
| [osu! Alumni](osu!_Alumni) | Connus pour leur contribution et qui sont partis depuis lors |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| [Project Loved Team](Project_Loved_Team) | Reconnaître les beatmaps les plus appréciés par la communauté |
```suggestion
| [Project Loved Team](Project_Loved_Team) | Reconnaître les beatmaps les plus appréciées par la communauté |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_NZ] [Echo](https://osu.ppy.sh/users/431) | développeur d'osu!, fournisseur de l'intégration IRC pour le chat en jeu, mainteneur du site. [Blog](http://blog.echo.sh/) |
```suggestion
| ![][flag_NZ] [Echo](https://osu.ppy.sh/users/431) | Développeur d'osu!, fournisseur de l'intégration IRC pour le chat en jeu, mainteneur du site. [Blog](http://blog.echo.sh/) |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_CA] [Nyquill](https://osu.ppy.sh/users/682935) | développeur d'osu!, Organisateur de la Mappers' Guild |
```suggestion
| ![][flag_CA] [Nyquill](https://osu.ppy.sh/users/682935) | Développeur d'osu!, Organisateur de la Mappers' Guild |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_US] [Sarumaru](https://osu.ppy.sh/users/9427) | Concepteur de concepts et d'illustrations originales de Pippi. [DeviantArt](https://sarumaru.deviantart.com/) |
```suggestion
| ![][flag_US] [Sarumaru](https://osu.ppy.sh/users/9427) | Créateur de concepts et d'illustrations originales de Pippi. [DeviantArt](https://sarumaru.deviantart.com/) |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/osu!_Alumni/fr.md
> +Les **osu! Alumni** sont ceux qui sont connus pour leurs contributions et qui sont partis depuis. Si les ressources étaient disponibles, nous érigerions une statue pour chaque membre sur la place de
```suggestion
Les **osu! Alumni** sont les utilisateurs qui sont connus pour leurs contributions et qui sont partis depuis. Si nous avions de quoi le faire, nous érigerions une statue pour chaque membre sur la place de la ville.
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/osu!_Alumni/fr.md
> +| ![][flag_DE] [Ezoda](https://osu.ppy.sh/users/1231180) | Équipe d'assistance |
```suggestion
| ![][flag_DE] [Ezoda](https://osu.ppy.sh/users/1231180) | Équipe du support |
```

2021-08-13 14:23 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_GR] [Sinistro](https://osu.ppy.sh/users/5530) | Gestionnaire et leader de communauté initiale, compte-rendu de réunion et contributeur de la FAQ |
```suggestion
| ![][flag_GR] [Sinistro](https://osu.ppy.sh/users/5530) | Gérant et leader de communauté initial, compte-rendu de réunion et contributeur de la FAQ |
```

2021-08-13 20:05 UTC, Ganondorf-1 requested changes

2021-08-13 20:05 UTC, Ganondorf-1 commented on wiki/People/The_Team/osu!_Alumni/fr.md
> +[flag_PH]: /wiki/shared/flag/PH.gif "Philippine"
```suggestion
[flag_PH]: /wiki/shared/flag/PH.gif "Philippines"
```

2021-08-13 20:05 UTC, Ganondorf-1 commented on wiki/People/The_Team/Support_Team/fr.md
> +[flag_PH]: /wiki/shared/flag/PH.gif "Philippine"
```suggestion
[flag_PH]: /wiki/shared/flag/PH.gif "Philippines"
```

2021-08-13 20:05 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +[flag_PH]: /wiki/shared/flag/PH.gif "Philippine"
```suggestion
[flag_PH]: /wiki/shared/flag/PH.gif "Philippines"
```

2021-08-15 16:45 UTC, Ganondorf-1 requested changes

2021-08-15 16:45 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_CN] [woc2006](https://osu.ppy.sh/users/1105845) | développeur d'osu!, développeur du mode osu!mania |
```suggestion
| ![][flag_CN] [woc2006](https://osu.ppy.sh/users/1105845) | Développeur d'osu!, développeur du mode osu!mania |
```

2021-08-15 16:45 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_CA] [mm201](https://osu.ppy.sh/users/30655) | développeur d'osu!, créateur des mm sliders |
```suggestion
| ![][flag_CA] [mm201](https://osu.ppy.sh/users/30655) | Développeur d'osu!, créateur des mm sliders |
```

2021-08-15 16:45 UTC, Ganondorf-1 commented on wiki/People/The_Team/fr.md
> +| ![][flag_NL] [Intermezzo](https://osu.ppy.sh/users/136842) | développeur d'osu!, fournisseur d'osz2 et de backend p2p |
```suggestion
| ![][flag_NL] [Intermezzo](https://osu.ppy.sh/users/136842) | Développeur d'osu!, fournisseur d'osz2 et de backend p2p |
```

2021-08-15 17:43 UTC, Ganondorf-1 approved these changes

2021-08-15 18:26 UTC, TicClick approved these changes

2021-08-15 18:26 UTC, merged