[FR] Update `Project Loved Team`
ppy/osu-wiki pull request #5929
Opened 2021-08-01 08:10 UTC by DoryanR

Proposal to update the French translation of the wiki page `Project Loved Team`.

2021-08-06 19:29 UTC, Satsukel requested changes

2021-08-06 19:29 UTC, Satsukel commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +Les modérateurs de contenu sont des membres de la [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team) et de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessm
Il me semble qu'on parle des beatmaps
```suggestion
Les modérateurs de contenu sont des membres de la [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team) et de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) qui participent à l'évaluation du contenu visuel et sonore des beatmaps qui seront soumises au vote.
```

2021-08-06 19:29 UTC, Satsukel commented on wiki/People/The_Team/Project_Loved_Team/fr.md
> +- Avant le 28 avril 2021, la [page de groupe Project Loved](https://osu.ppy.sh/groups/31) n'était pas publique et n'était utilisée qu'à des fins administratives. À partir de maintenant, elle est acce
```suggestion
- Avant le 28 avril 2021, la [page du groupe Project Loved](https://osu.ppy.sh/groups/31) n'était pas publique et n'était utilisée qu'à des fins administratives. À partir de maintenant, elle est accessible au public.
```

2021-08-10 07:53 UTC, Satsukel approved these changes

2021-08-12 14:04 UTC, TicClick approved these changes

2021-08-12 14:05 UTC, merged