[RU] Add Scaling BPM on the ranking criteria
ppy/osu-wiki pull request #5930
Opened 2021-08-01 09:22 UTC by h1gh0ffl1fe

Need native's comment

2021-08-15 17:20 UTC, h1gh0ffl1fe commented
Would like to get a review from native

2021-08-15 18:20 UTC, TicClick commented
on my way

2021-08-18 00:09 UTC, TicClick requested changes
- практически везде, где я предложил исправления, формулировки у тебя получились прямым переводом, не надо так.
- нужно решить, что делать с 1/2, 1/4 и так далее. я бы оставил просто так, в виде дробей, не нужно никаких дополнительных «ритмов» дописывать — на мой взгляд, и так понятно, что это размерность удара, если мы говорим про игровые объекты (а мы про них и говорим).

2021-08-18 00:09 UTC, TicClick commented on wiki/Ranking_Criteria/Scaling_BPM/ru.md
> +Несмотря на то, что этот гайд ориентирован на рекомендации для сложности Normal (osu!standard), он так же касается и других сложностей и игровых режимов. Например, сложности Easy (osu!standard) требу
```suggestion
Несмотря на выбранный пример, это руководство применимо ко всем режимам и уровням сложностей. Так, по критериям ранкинга для Easy необходимо оставлять паузу в четыре бита (4/1) после спиннеров. При 180 BPM пауза такой и должна быть, однако при 120 BPM достаточно уже трёх битов, а чем ближе к 90 BPM, тем более допустима пауза в два бита.
```

2021-09-14 15:57 UTC, TicClick commented
так что тут происходит? ты (когда-то) применишь, или мне можно прокликать и отредактировать, как я считаю нужным?

2021-09-15 13:34 UTC, h1gh0ffl1fe commented
Да, я применю

2021-11-19 19:46 UTC, TicClick commented
ну так что?

2022-01-07 20:50 UTC, TicClick approved these changes
(own suggestions applied, PR is being merged, feel free to send follow-up changes if necessary)

2022-01-07 20:51 UTC, merged