Conclude `Catch the Beat Indonesia Cup 2021`
ppy/osu-wiki pull request #5932
Opened 2021-08-02 06:38 UTC by Nivalyx

2021-08-02 13:07 UTC, TPGPL requested changes

2021-08-02 13:07 UTC, TPGPL commented on wiki/Tournaments/CIC/2021/en.md
> +![Profile badge](img/badge.png)
```suggestion
![](img/badge.png "CIC 2021 winner badge")
```

2021-08-02 13:07 UTC, TPGPL commented on wiki/Tournaments/CIC/2021/en.md
> +![Champion: dika312, 2nd place: CamXDanna, 3rd place: Nekuro](img/podium.png)
move the image after the `Participants` header and remove `## Podium`

2021-08-02 13:07 UTC, TPGPL commented on wiki/Tournaments/CIC/2021/en.md
> +![Champion: dika312, 2nd place: CamXDanna, 3rd place: Nekuro](img/podium.png)
```suggestion
## Podium

![Champion: dika312, 2nd place: CamXDanna, 3rd place: Nekuro](img/podium.png)
```

2021-08-02 13:07 UTC, TPGPL commented on wiki/Tournaments/CIC/2021/en.md
> +![Champion: dika312, 2nd place: CamXDanna, 3rd place: Nekuro](img/podium.png)
```suggestion
## Podium

![](img/podium.png "CIC 2021 podium")
```

2021-08-03 02:27 UTC, Nivalyx commented
ah, is moving the podium an absolute necessity? i prefer to keep it as is tho if you don't mind as i think it's more fitting to have the image in their own section...

also iirc the preceding iterations of the tournament have also featured the podium image on its own so yeah :

![image](https://user-images.githubusercontent.com/36564236/127947581-53aab542-86c9-40a5-aa5d-d13b8bd1a326.png)

((applied everything else otherwise))

2021-08-03 12:24 UTC, TPGPL commented
i guess its fine to have it in a seperate section then, but it still needs to be moved under `Participants`

2021-08-03 18:28 UTC, TPGPL approved these changes

2021-08-03 18:29 UTC, merged