[ZH] Abandoned_wasteland
ppy/osu-wiki pull request #5935
Opened 2021-08-02 23:54 UTC by eyang2020

Provides Mandarin Chinese translation of the Abandoned wasteland article.

2021-08-03 00:57 UTC, kj415j45 requested changes

2021-08-03 00:57 UTC, kj415j45 commented on wiki/Abandoned_wasteland/zh.md
> +被遗**弃的荒地**是一个私人的[子论坛](https://osu.ppy.sh/community/forums)，用于从公众视野中隐藏论坛和论坛主题｡ 此子论坛只有可以修改论坛的版主才能访问｡ 关于它的版主的说明是："把我们并不真正需要的东西放在这里｡"
`废弃的荒地`，或是`被遗弃的荒地`，请二选一地作为`abandoned wasteland`的译名。

2021-08-03 00:57 UTC, kj415j45 commented on wiki/Abandoned_wasteland/zh.md
> +论坛和主题被认为是"荒地"，当他们搬到这个论坛｡
不提供修改建议，请重新翻译这句话。

2021-08-03 01:46 UTC, eyang2020 commented on wiki/Abandoned_wasteland/zh.md
> +论坛和主题被认为是"荒地"，当他们搬到这个论坛｡
不好意识，这次写的可以吗？

2021-08-03 02:02 UTC, kj415j45 commented on wiki/Abandoned_wasteland/zh.md
> +如果一个论坛或话题在废弃的荒地，它被称为“wastelanded”。
```suggestion
当论坛或主题被移动到废弃的荒地时，称为“wastelanded”。
```

2021-08-03 02:02 UTC, kj415j45 commented on wiki/Abandoned_wasteland/zh.md
> +**Abandoned wasteland** (中文: 废弃的荒地) 是一个私人的[子论坛](https://osu.ppy.sh/community/forums)，用于从公众视野中隐藏论坛和论坛主题｡ 此子论坛只有可以修改论坛的[版主](https://github.com/ppy/osu-wiki/tree/master/wiki/People/The_Team/Global_Moder
```suggestion
**Abandoned wasteland** (中文: 废弃的荒地) 是一个私人的[子论坛](https://osu.ppy.sh/community/forums)，用于从公众视野中隐藏论坛和论坛主题｡ 此子论坛只有可以修改论坛的版主才能访问｡ 关于它的版主的说明是`把我们并不真正需要的东西放在这里`｡
```

2021-08-03 03:17 UTC, kj415j45 submitted a review, later dismissed

2021-08-08 12:08 UTC, cdwcgt requested changes

2021-08-08 12:08 UTC, cdwcgt commented on wiki/Abandoned_wasteland/zh.md
> +**Abandoned wasteland** (中文: 废弃的荒地) 是一个私人的[子论坛](https://osu.ppy.sh/community/forums)，用于从公众视野中隐藏论坛和论坛主题｡ 此子论坛只有可以修改论坛的版主才能访问｡ 关于它的版主的说明是`把我们并不真正需要的东西放在这里`｡
```suggestion
**Abandoned wasteland** (中文: 废弃的荒地) 是一个私人的[子论坛](https://osu.ppy.sh/community/forums)，用于从公众视野中隐藏论坛和论坛主题｡ 此子论坛只有可以修改论坛的版主才能访问｡ 版主给它的说明是`把我们并不真正需要的东西放在这里`｡
```

2021-08-08 12:08 UTC, cdwcgt commented on wiki/Abandoned_wasteland/zh.md
> +当论坛或主题被移动到废弃的荒地时，称为“wastelanded”。
```suggestion
当论坛或主题被移动到废弃的荒地时，它们被称为“wastelanded”。
```
因为这样感觉搞得这个动作叫 `wastelanded`

2021-08-09 00:33 UTC, kj415j45 commented on wiki/Abandoned_wasteland/zh.md
> +**Abandoned wasteland** (中文: 废弃的荒地) 是一个私人的[子论坛](https://osu.ppy.sh/community/forums)，用于从公众视野中隐藏论坛和论坛主题｡ 此子论坛只有可以修改论坛的版主才能访问｡ 版主给它的说明是`把我们并不真正需要的东西放在这里`｡
```suggestion
**Abandoned wasteland** (中文: 废弃的荒地) 是一个私密的[子论坛](https://osu.ppy.sh/community/forums)，用于从公众视野中隐藏论坛和论坛主题｡ 此子论坛只有可以修改论坛的版主才能访问｡ 版主给它的说明是`把我们并不真正需要的东西放在这里`｡
```

2021-08-10 23:58 UTC, kj415j45 submitted a review, later dismissed

2021-08-11 01:27 UTC, TPGPL approved these changes

2021-08-11 01:29 UTC, merged