[CS] Add `Installation`
ppy/osu-wiki pull request #5936
Opened 2021-08-03 00:38 UTC by Ondra-D

Translated the installation page to czech.

2021-08-12 18:35 UTC, TPGPL requested changes

2021-08-12 18:35 UTC, TPGPL commented on wiki/Installation/cs.md
> +- .NET framework 4+ (instalační program by vás měl vyzvat ke stažení, v opačném případě jej najdete [zde](https://www.microsoft.com/en-us/download/details.aspx?id=48130))
```suggestion
- .NET framework 4+ (instalační program by vás měl vyzvat ke stažení, v opačném případě jej najdete [zde](https://www.microsoft.com/cs-CZ/download/details.aspx?id=48130))
```

2021-08-12 18:35 UTC, TPGPL commented on wiki/Installation/cs.md
> +   - Pokud se potřebujete zaregistrovat, podívejte se na [Registrace](/wiki/Registrace).
```suggestion
   - Pokud se potřebujete zaregistrovat, podívejte se na [Registrace](/wiki/Registration).
```

2021-08-12 18:35 UTC, TPGPL commented on wiki/Installation/cs.md
> +Existují dva způsoby, jak přidat beatmapy, přes webovou stránku nebo přes osu! Direct (vyžaduje [osu! Supporter](/wiki/osu!Supporter)).
```suggestion
Existují dva způsoby, jak přidat beatmapy, přes webovou stránku nebo přes osu! Direct (vyžaduje [osu! Supporter](/wiki/osu!supporter)).
```

2021-08-12 18:35 UTC, TPGPL commented on wiki/Installation/cs.md
> +
```suggestion

```

2021-08-12 19:12 UTC, Ondra-D commented
you already fixed it

2021-08-17 23:30 UTC, TPGPL approved these changes

2021-08-17 23:31 UTC, merged