[FR] Add Skinning/Osu!mania
ppy/osu-wiki pull request #5939
Opened 2021-08-05 14:22 UTC by Satsukel

Added French translation of Skinning/Osu!mania wiki page and also corrected a typo in the original wiki page

2021-08-06 17:19 UTC, DoryanR requested changes

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Pour avoir plusieurs combobursts, utilisez: `comboburst-mania-{n}.png`.
```suggestion
- Pour avoir plusieurs combobursts, utilisez : `comboburst-mania-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note1-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note1-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note2-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note2-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-noteS-{n}.png`.
```suggestion
- Nom de l'animation : `mania-noteS-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +### hold notes
```suggestion
### Hold notes
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note1H-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note1H-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Par défaut, ceci est aussi le bout de la note.
```suggestion
- Par défaut, ceci est aussi la fin de la note.
```

Ça rend mieux comme ça je trouve, `le bout` ça rend bizarre

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Quand il est utilisé comme bout de note, cet élément est retourné par défaut en version 2.5+.
```suggestion
  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5+.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note2H-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note2H-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Par défaut, ceci est aussi le bout de la note.
```suggestion
- Par défaut, ceci est aussi la fin de la note.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Quand il est utilisé comme bout de note, cet élément est retourné par défaut en version 2.5+.
```suggestion
  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5+.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-noteSH-{n}.png`.
```suggestion
- Nom de l'animation : `mania-noteSH-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Par défaut, ceci est aussi le bout de la note.
```suggestion
- Par défaut, ceci est aussi la fin de la note.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Quand il est utilisé comme bout de note, cet élément est retourné par défaut en version 2.5+.
```suggestion
  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5+.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note1L-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note1L-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +#### Body
```suggestion
#### Corps
```

Voir si ça ce dit bien comme ça par contre, j'ai modifier vu que j'ai l'impression que c'est un oubli

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note2L-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note2L-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-noteSL-{n}.png`.
```suggestion
- Nom de l'animation : `mania-noteSL-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +#### Tail
```suggestion
#### Queue
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note1T-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note1T-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-note2T-{n}.png`.
```suggestion
- Nom de l'animation : `mania-note2T-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-noteST-{n}.png`.
```suggestion
- Nom de l'animation : `mania-noteST-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Si la largeur des colonnes diffèrent: la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```suggestion
  - Si la largeur des colonnes diffèrent : la plus petite est correctement mise à l'échelle et les autres sont compressées pour correspondre à sa hauteur.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +| Toutes | ![Non][false] | ![Non][false] | Normal | Bas droite | Hauteur max: 768px |
```suggestion
| Toutes | ![Non][false] | ![Non][false] | Normal | Bas droite | Hauteur max : 768px |
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +| Toutes | ![Non][false] | ![Non][false] | Normal | Bas droite | Hauteur max: 768px |
```suggestion
| Toutes | ![Non][false] | ![Non][false] | Normal | Bas droite | Hauteur max : 768px |
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-stage-bottom-{n}.png`.
```suggestion
- Nom de l'animation : `mania-stage-bottom-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Situé en bas (Ou en haut, si le stage est inversé) du/des stage(s).
```suggestion
- Situé en bas (ou en haut, si le stage est inversé) du/des stage(s).
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +| Toutes | ![Oui][true] | ![Non][false] | Multiplicatif | Bas | Hauteur max: 768px |
```suggestion
| Toutes | ![Oui][true] | ![Non][false] | Multiplicatif | Bas | Hauteur max : 768px |
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `mania-stage-light-{n}.png`.
```suggestion
- Nom de l'animation : `mania-stage-light-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Cet élément est la représentation graphique de la ligne de jugement.
```suggestion
- Cet élément est la représentation graphique de la judgement line.
```

Perso je crois pas le traduire ça, a voir ce qu'on fait plus tard. Pour le moment je suis tenté de ne pas le traduire

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - La ligne de jugement est tracée au centre de l'image.
```suggestion
  - La judgement line est tracée au centre de l'image.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Cet élément est déssiné sur toute la largeur du stage, et non pas pour des colonnes individuelles.
```suggestion
- Cet élément est dessiné sur toute la largeur du stage, et non pas pour des colonnes individuelles.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Cet élément est étiré pour correspondre à la largeur du stage(Il est possible d'utiliser des images moins large).
```suggestion
- Cet élément est étiré pour correspondre à la largeur du stage. (il est possible d'utiliser des images moins large)
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `lightingL-{n}.png`.
```suggestion
- Nom de l'animation : `lightingL-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Cet élément est positionné là où le centre de la ligne de jugement croise le centre d'une colonne.This element is positioned where the centre of the judgement line crosses the centre of a lane.
```suggestion
- Cet élément est positionné là où le centre de la judgement line croise le centre d'une colonne.
```

On a rien vu :p

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Notes:
```suggestion
Notes :
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Nom de l'animation: `lightingN-{n}.png`.
```suggestion
- Nom de l'animation : `lightingN-{n}.png`.
```

2021-08-06 17:19 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- Cet élément est positionné là où le centre de la ligne de jugement croise le centre d'une colonne.
```suggestion
- Cet élément est positionné là où le centre de la judgement line croise le centre d'une colonne.
```

2021-08-06 17:23 UTC, DoryanR requested changes
I forgot the fix for the remark

2021-08-06 17:23 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +---
```suggestion

---
```

2021-08-06 19:13 UTC, Satsukel commented on wiki/Skinning/osu!mania/fr.md
> +#### Tail
Y a le terme Tail note je crois du coup je suis pas certain de vouloir traduire ça

2021-08-06 20:08 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +#### Tail
Ouais justement j'étais pas sur si c'était fait exprès ou non, mais pas de soucis, on peut laisser comme ça

2021-08-07 15:31 UTC, DoryanR requested changes

2021-08-07 15:31 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +*Voir également : [Tutoriel de skinning pour le mode osu!mania](/wiki/Skinning_osu!mania_Tutorial)*
```suggestion
```

J'ai vérifier, l'article n'existe pas. Par contre ça a été retirer sur l'article en anglais, alors un reckeck pour être sur qu'on soit bien à jour avec la version anglaise est a faire avant de merge.

2021-08-07 15:31 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +Depuis la version 2.5+, les skinners peuvent personnaliser entièrement les notes et la scène du mode osu!mania en utilisant le fichier [skin.ini](/wiki/Skinning/skin.ini). Voici ce qu'osu! reconnaîtr
```suggestion
Depuis la version 2.5, les skinners peuvent personnaliser entièrement les notes et la scène du mode osu!mania en utilisant le fichier [skin.ini](/wiki/Skinning/skin.ini). Voici ce qu'osu! reconnaîtra si l'on choisit de ne pas utiliser le fichier `skin.ini` pour plus de personnalisation.
```

2021-08-07 15:31 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5+.
```suggestion
  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5.
```

2021-08-07 15:31 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5+.
```suggestion
  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5.
```

2021-08-07 15:31 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5+.
```suggestion
  - Quand il est utilisé comme fin de note, cet élément est retourné par défaut en version 2.5.
```

2021-08-08 07:33 UTC, Satsukel commented on wiki/Skinning/osu!mania/fr.md
> +
```suggestion
```

2021-08-08 08:57 UTC, DoryanR requested changes
After this we are good

2021-08-08 08:57 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +- La position est définie par le [skin.ini](/wiki/Skinning/skin.ini)
```suggestion
- La position est définie par le fichier [skin.ini](/wiki/Skinning/skin.ini)
```

2021-08-08 08:57 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +  - Utilisez la commande `LightPosition`.
```suggestion
  - Utilisez la commande `LightPosition` pour la modifier.
```

2021-08-08 08:57 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +| Toutes | ![Oui][true] | ![Non][false] | Additif | Centre | - |
```suggestion
| Toutes | ![Oui][true] | ![Non][false] | Supplément | Centre | - |
```

C'est un élément qui est optionnel si j'ai bien compris, donc je pense que ça rendra mieux de mettre ça comme ça.

2021-08-08 08:57 UTC, DoryanR commented on wiki/Skinning/osu!mania/fr.md
> +| Toutes | ![Oui][true] | ![Non][false] | Additif | Centre | - |
```suggestion
| Toutes | ![Oui][true] | ![Non][false] | Supplément | Centre | - |
```

2021-08-08 17:49 UTC, DoryanR approved these changes

2021-08-12 14:08 UTC, TicClick approved these changes

2021-08-12 14:08 UTC, merged