[FR] Add translations for `Staff_Logs`
ppy/osu-wiki pull request #5954
Opened 2021-08-12 01:50 UTC by reeceyang

french translations for staff log index page and all staff log entries from 2007 to 2021.

2021-08-16 18:38 UTC, DoryanR requested changes
Almost total rewriting of all the articles; I save the 3163 suggestions that would have been necessary, if I had not gone through the editor, from where the review on the whole article.
This rewriting was mandatory, because the article was not French, and did not correspond to our standards.

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2007/fr.md
> +-->
```suggestion
# Registre du personnel : 2007

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année. "Moderators" ont ensuite été renommés en "Beatmap Approval Team".*

- Ajout de [phill](https://osu.ppy.sh/users/53) : Moderators
- Ajout de [eyup](https://osu.ppy.sh/users/88) : Moderators
- Ajout de [Kylecito](https://osu.ppy.sh/users/488) : Moderators
- Ajout de [Loginer](https://osu.ppy.sh/users/819) : Moderators
- Ajout de [Extor](https://osu.ppy.sh/users/555) : Moderators
- Ajout de [awp](https://osu.ppy.sh/users/2650) : Moderators
- Ajout de [Echo](https://osu.ppy.sh/users/431) : Moderators
- Ajout de [Ivalset](https://osu.ppy.sh/users/827) : Moderators
- Ajout de [Hitoshirenu Shourai](https://osu.ppy.sh/users/602) : Moderators 
- Ajout de [Cecilthemos](https://osu.ppy.sh/users/2233) : Moderator
- Ajout de [Kharl](https://osu.ppy.sh/users/452) : Moderators
- Ajout de [EiJi](https://osu.ppy.sh/users/2024) : Moderators
- Ajout de [MaxwellDemon](https://osu.ppy.sh/users/4254) : Moderators

```

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2008/fr.md
> +- Ajouté [foulcoon](https://osu.ppy.sh/users/19883) à Beatmap Approval Team (2008-12-19) <!-- https://osu.ppy.sh/community/forums/posts/69884 -->
```suggestion
# Registre du personnel : 2008

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Janvier

- Ajout de [Zyid](https://osu.ppy.sh/users/2778) : Beatmap Approval Team (21/01/2008) 
- Ajout de [Rolled](https://osu.ppy.sh/users/5243) : Beatmap Approval Team (21/01/2008)
- Ajout de [Saturos](https://osu.ppy.sh/users/3781) : Beatmap Approval Team (21/01/2008) 
- Ajout de [chan](https://osu.ppy.sh/users/94) : Beatmap Approval Team (23/01/2008)
- Ajout de [Tapdancingmetroid](https://osu.ppy.sh/users/1733) : Beatmap Approval Team (25/01/2008)

## Février

- Transfert de [MaxwellDemon](https://osu.ppy.sh/users/4254) : Beatmap Approval Team > osu! Alumni (16/02/2008) 
- Ajout de [James](https://osu.ppy.sh/users/5728) : Beatmap Approval Team (21/02/2008)
- Ajout de [LuigiHann](https://osu.ppy.sh/users/1079) : Beatmap Approval Team (21/02/2008) 

## Mars

- Ajout de [mtmcl](https://osu.ppy.sh/users/5960) : Beatmap Approval Team (04/03/2008) 

## Avril

- Ajout de [Sinistro](https://osu.ppy.sh/users/5530) : Beatmap Approval Team (04/03/2008) 

## Juin

- Ajout de [MOOMANiBE](https://osu.ppy.sh/users/8950) : Beatmap Approval Team (10/06/2008) 
- Ajout de [Kai](https://osu.ppy.sh/users/4537) : Beatmap Approval Team (11/06/2008) 

## Juillet

- Ajout de [buraimaster1234](https://osu.ppy.sh/users/5772) : Beatmap Approval Team (01/07/2008) 
- Ajout de [Gemi](https://osu.ppy.sh/users/7365) : Beatmap Approval Team (01/07/2008)

## Août

- Ajout de [deepsea](https://osu.ppy.sh/users/7824) : Beatmap Approval Team (27/08/2008) 
- Ajout de [CheeseWarlock](https://osu.ppy.sh/users/9072) : Beatmap Approval Team (27/08/2008) 
- Ajout de [mattyu007](https://osu.ppy.sh/users/4934) : Beatmap Approval Team (28/08/2008) 
- Ajout de [Dakeryus](https://osu.ppy.sh/users/10441) : Beatmap Approval Team (31/08/2008) 

## Septembre 

- Ajout de [Mogsworth](https://osu.ppy.sh/users/4018) : Beatmap Approval Team (01/09/2008) 
- Ajout de [kingcobra52](https://osu.ppy.sh/users/9934) : Beatmap Approval Team (01/09/2008)
- Ajout de [Cyclone](https://osu.ppy.sh/users/18589) : Beatmap Approval Team (16/09/2008) 

## Octobre

- Ajout de [ash](https://osu.ppy.sh/users/11593) : Beatmap Approval Team (13/10/2008) 
- Retrait de [ash](https://osu.ppy.sh/users/11593) : Beatmap Approval Team (13/10/2008)
- Ajout de [Seibei](https://osu.ppy.sh/users/31537) : Beatmap Approval Team (28/10/2008) 
- Ajout de [m980](https://osu.ppy.sh/users/3288) : Beatmap Approval Team (28/10/2008)

## Novembre

- Ajout de [Zerostarry](https://osu.ppy.sh/users/3480) : Beatmap Approval Team (21/11/2008) 

## Décembre

- Transfert de [James](https://osu.ppy.sh/users/5728) : Beatmap Approval Team > osu! Alumni (01/12/2008) 
- Ajout de [foulcoon](https://osu.ppy.sh/users/19883) : Beatmap Approval Team (19/12/2008) 

```

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2009/fr.md
> +-->
```suggestion
# Registre du personnel : 2009

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Février

- Transfert de [Ivalset](https://osu.ppy.sh/users/827) : Beatmap Approval Team > BATmanager (04/02/2009) 
- Ajout de [Larto](https://osu.ppy.sh/users/12328) : Beatmap Approval Team (04/02/2009) 
- Ajout de [DawnII](https://osu.ppy.sh/users/8399) : Beatmap Approval Team (14/02/2009)

## Mars

- Ajout de [An64fan](https://osu.ppy.sh/users/38836) : Beatmap Approval Team (05/03/2009)
- Ajout de [RemmyX25](https://osu.ppy.sh/users/612) : Beatmap Approval Team (05/03/2009)
- Ajout de [Pasonia](https://osu.ppy.sh/users/43345) : Beatmap Approval Team (05/03/2009)
- Ajout de [vytalibus](https://osu.ppy.sh/users/10028) : Beatmap Approval Team (22/03/2009) 

## Avril

- Ajout de [Skyripper](https://osu.ppy.sh/users/31803) : Beatmap Approval Team (Moderation) (21/04/2009) 

## Mai

- Ajout de [Takuma](https://osu.ppy.sh/users/43677) : Beatmap Approval Team (31/05/2009) 
- Ajout de [Alace](https://osu.ppy.sh/users/25993) : Beatmap Approval Team (31/05/2009) 
## Juin

- Ajout de [strager](https://osu.ppy.sh/users/64678) : Beatmap Approval Team (12/06/2009) 
- Transfert de [An64fan](https://osu.ppy.sh/users/38836) : Beatmap Approval Team > osu! Alumni (15/06/2009) 
- Ajout de [Saturos-fangirl](https://osu.ppy.sh/users/11874) : Beatmap Approval Team (17/06/2009) 

## Juillet

- Ajout de [Starrodkirby86](https://osu.ppy.sh/users/410) : Beatmap Approval Team (08/07/2009) 

## Août

- Ajout de [ztrot](https://osu.ppy.sh/users/6347) : Beatmap Approval Team (21/08/2009) 
- Ajout de [mrtn](https://osu.ppy.sh/users/7013) : Beatmap Approval Team (21/08/2009)
- Ajout de [tieff](https://osu.ppy.sh/users/89619) : Beatmap Approval Team (21/08/2009)
- Transfert de [buraimaster1234](https://osu.ppy.sh/users/5772) : Beatmap Approval Team > osu! Alumni (24/08/2009) 

## Septembre

- Transfert de [Mogsworth](https://osu.ppy.sh/users/4018) : Beatmap Approval Team > osu! Alumni (30/09/2009) 

## Octobre

- Ajout de [JarJarJacob](https://osu.ppy.sh/users/25615) : Beatmap Approval Team (16/10/2009) 
- Ajout de [whymeman](https://osu.ppy.sh/users/51994) : Beatmap Approval Team (16/10/2009)
- Ajout de [minyeob](https://osu.ppy.sh/users/9207) : Beatmap Approval Team (16/10/2009)
- Ajout de [Mafiamaster](https://osu.ppy.sh/users/17695) : Beatmap Approval Team (16/10/2009)

## Novembre

- Transfert de [Pasonia](https://osu.ppy.sh/users/43345) : Beatmap Approval Team > BATmanager (10/11/2009) 
- Ajout de [Ephemeral](https://osu.ppy.sh/users/102335) : Beatmap Approval Team (30/11/2009) 
- Transfert de [mtmcl](https://osu.ppy.sh/users/5960) : osu! Alumni > Beatmap Approval Team (30/11/2009)

## Décembre

- Ajout de [abalee](https://osu.ppy.sh/users/13103) : Beatmap Approval Team (12/12/2009) 
- Ajout de [osuplayer111](https://osu.ppy.sh/users/33599) : Beatmap Approval Team (15/12/2009) 
- Ajout de [xxheroxx](https://osu.ppy.sh/users/25999) : Mapping Assistance Team (27/12/2009)
- Ajout de [Azure_Kyte](https://osu.ppy.sh/users/66296) : Mapping Assistance Team (27/12/2009)
- Ajout de [blissfulyoshi](https://osu.ppy.sh/users/20865) : Mapping Assistance Team (27/12/2009)
- Ajout de [Zekira](https://osu.ppy.sh/users/36749) : Mapping Assistance Team (27/12/2009)
- Ajout de [Alace](https://osu.ppy.sh/users/25993) : Mapping Assistance Team (27/12/2009)
- Ajout de [Derekku](https://osu.ppy.sh/users/91341) : Mapping Assistance Team (27/12/2009)
- Ajout de [MetalMario201](https://osu.ppy.sh/users/30655) : Mapping Assistance Team (27/12/2009)
- Ajout de [0_o](https://osu.ppy.sh/users/56708) : Mapping Assistance Team (27/12/2009)
- Ajout de [AgnesChan](https://osu.ppy.sh/users/136982) : Mapping Assistance Team (27/12/2009)
- Ajout de [Card N'FoRcE](https://osu.ppy.sh/users/3936) : Mapping Assistance Team (27/12/2009)
- Ajout de [Lybydose](https://osu.ppy.sh/users/64501) : Mapping Assistance Team (27/12/2009)
- Ajout de [Gens](https://osu.ppy.sh/users/23062) : Mapping Assistance Team (27/12/2009)
- Ajout de [Shulin](https://osu.ppy.sh/users/150488) : Mapping Assistance Team (27/12/2009)
- Ajout de [Shinxyn](https://osu.ppy.sh/users/13996) : Mapping Assistance Team (27/12/2009)
- Ajout de [Lesjuh](https://osu.ppy.sh/users/44308) : Mapping Assistance Team (27/12/2009)
- Ajout de [yaya](https://osu.ppy.sh/users/50163) : Mapping Assistance Team (27/12/2009)
- Ajout de [abalee](https://osu.ppy.sh/users/13103) : Mapping Assistance Team (27/12/2009)
- Ajout de [kioukiou](https://osu.ppy.sh/users/12248) : Mapping Assistance Team (27/12/2009)
- Ajout de [ignorethis](https://osu.ppy.sh/users/27343) : Mapping Assistance Team (27/12/2009)
- Ajout de [Lissette](https://osu.ppy.sh/users/19835) : Mapping Assistance Team (27/12/2009)
- Ajout de [Lizbeth](https://osu.ppy.sh/users/21970) : Mapping Assistance Team (27/12/2009)
- Ajout de [Dangaard](https://osu.ppy.sh/users/19488) : Mapping Assistance Team (27/12/2009)
- Ajout de [-SiN-](https://osu.ppy.sh/users/10560) : Mapping Assistance Team (27/12/2009)
- Transfert de [vytalibus](https://osu.ppy.sh/users/10028) : Beatmap Approval Team > osu! Alumni (31/12/2009)

```

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2010/fr.md
> +- Transféré [Doomsday](https://osu.ppy.sh/users/18983) de Mapping Assistance Team à Beatmap Approval Team (2010-12-23)
```suggestion
# Registre du personnel : 2010

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Janvier

- Transfert de [James](https://osu.ppy.sh/users/5728) : osu! Alumni > Beatmap Approval Team (25/01/2010)
- Transfert de [DawnII](https://osu.ppy.sh/users/8399) : osu! Alumni > Beatmap Approval Team (26/01/2010) 
- Transfert de [kingcobra52](https://osu.ppy.sh/users/9934) : osu! Alumni > Beatmap Approval Team (27/01/2010)
## Février

- Ajout de [yaya](https://osu.ppy.sh/users/50163) : Beatmap Approval Team (01/02/2010)
- Transfert de [Sinistro](https://osu.ppy.sh/users/5530) : Beatmap Approval Team > osu! Alumni (08/02/2010)
- Ajout de [DJPop](https://osu.ppy.sh/users/2363) : Mapping Assistance Team (26/02/2010)
- Ajout de [rust45](https://osu.ppy.sh/users/117369) : Mapping Assistance Team (26/02/2010)
- Ajout de [NoHitter](https://osu.ppy.sh/users/124455) : Mapping Assistance Team (26/02/2010)
- Ajout de [Breeze](https://osu.ppy.sh/users/77537) : Mapping Assistance Team (26/02/2010)
- Ajout de [MarioBros777](https://osu.ppy.sh/users/58197) : Mapping Assistance Team (26/02/2010)
- Ajout de [Sushi971](https://osu.ppy.sh/users/43108) : Mapping Assistance Team (26/02/2010)
- Ajout de [Real1](https://osu.ppy.sh/users/40998) : Mapping Assistance Team (26/02/2010)
- Ajout de [fartownik](https://osu.ppy.sh/users/56917) : Mapping Assistance Team (26/02/2010)
- Ajout de [Teara](https://osu.ppy.sh/users/123491) : Mapping Assistance Team (26/02/2010)
- Ajout de [VanMoNky](https://osu.ppy.sh/users/117865) : Mapping Assistance Team (26/02/2010)

## Avril

- Ajout de [xierbaliti](https://osu.ppy.sh/users/34044) : Mapping Assistance Team (06/04/2010)
- Ajout de [YGOkid8](https://osu.ppy.sh/users/69114) : Mapping Assistance Team (06/04/2010)
- Ajout de [Xgor](https://osu.ppy.sh/users/98661) : Mapping Assistance Team (06/04/2010)
- Ajout de [Matma Rex](https://osu.ppy.sh/users/83268) : Mapping Assistance Team (06/04/2010)
- Ajout de [yeahyeahyeahhh](https://osu.ppy.sh/users/58042) : Mapping Assistance Team (06/04/2010)
- Ajout de [Armin](https://osu.ppy.sh/users/105902) : Mapping Assistance Team (06/04/2010)
- Ajout de [orioncomet](https://osu.ppy.sh/users/104827) : Mapping Assistance Team (06/04/2010)

## Mai

- Transfert de [awp](https://osu.ppy.sh/users/2650) : Beatmap Approval Team > osu! Alumni (12/05/2010)
- Transfert de [Shinxyn](https://osu.ppy.sh/users/13996) : Mapping Assistance Team > Beatmap Approval Team (23/05/2010)
- Transfert de [Gens](https://osu.ppy.sh/users/23062) : Mapping Assistance Team > Beatmap Approval Team (23/05/2010)
- Transfert de [Lybydose](https://osu.ppy.sh/users/64501) : Mapping Assistance Team > Beatmap Approval Team (23/05/2010)
- Ajout de [Beuchi-chan](https://osu.ppy.sh/users/67192) : Global Mod Team (23/05/2010)
- Retrait de [Saturos-fangirl](https://osu.ppy.sh/users/11874) : Beatmap Approval Team (26/05/2010)

## Juin

- Transfert de [ztrot](https://osu.ppy.sh/users/6347) : Beatmap Approval Team > osu! Alumni (19/06/2010)
- Transfert de [Takuma](https://osu.ppy.sh/users/43677) : Beatmap Approval Team > osu! Alumni (24/06/2010)
- Transfert de [Rolled](https://osu.ppy.sh/users/5243) : osu! Alumni > Beatmap Approval Team (25/06/2010)
- Transfert de [Alace](https://osu.ppy.sh/users/25993) : osu! Alumni > Beatmap Approval Team (25/06/2010)
- Transfert de [ztrot](https://osu.ppy.sh/users/6347) : osu! Alumni > Beatmap Approval Team (25/06/2010)
- Transfert de [Mogsworth](https://osu.ppy.sh/users/4018) : osu! Alumni > Beatmap Approval Team (25/06/2010)

## Juillet

- Ajout de [mm201](https://osu.ppy.sh/users/30655) : Global Mod Team (20/07/2010)

## Août

- Transfert de [Takuma](https://osu.ppy.sh/users/43677) : osu! Alumni > Beatmap Approval Team (04/08/2010)

## Septembre

- Ajout de [Garven](https://osu.ppy.sh/users/244216) : Mapping Assistance Team (06/09/2010)
- Ajout de [Odaril](https://osu.ppy.sh/users/113005) : Mapping Assistance Team (06/09/2010)
- Ajout de [Mashley](https://osu.ppy.sh/users/41481) : Mapping Assistance Team (14/09/2010)
- Ajout de [Jarby](https://osu.ppy.sh/users/25615) : Mapping Assistance Team (22/09/2010)
- Transfert de [Zerostarry](https://osu.ppy.sh/users/3480) : osu! Alumni > Beatmap Approval Team (25/09/2010)
- Ajout de [Sakura Hana](https://osu.ppy.sh/users/289422) : Mapping Assistance Team (29/09/2010)

## Novembre

- Transfert de [Kharl](https://osu.ppy.sh/users/452) : osu! Alumni > Global Mod Team (23/11/2010)

## Décembre

- Ajout de [jericho2442](https://osu.ppy.sh/users/88904) : Mapping Assistance Team (03/12/2010)
- Transfert de [Card N'FoRcE](https://osu.ppy.sh/users/3936) : Mapping Assistance Team > Beatmap Approval Team (23/12/2010)
- Transfert de [Doomsday](https://osu.ppy.sh/users/18983) : Mapping Assistance Team > Beatmap Approval Team (23/12/2010)

```

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2011/fr.md
> +- Transféré [Mogsy](https://osu.ppy.sh/users/4018) de Beatmap Appreciation Team à osu! Alumni (2011-12-15) <!-- https://osu.ppy.sh/community/forums/posts/1197440 -->
```suggestion
# Registre du personnel : 2011

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Janvier

- Transfert de [Derekku](https://osu.ppy.sh/users/91341) : Mapping Assistance Team > Global Mod Team (07/01/2011)
- Ajout de [Colin Hou](https://osu.ppy.sh/users/196614) : Mapping Assistance Team (21/01/2011)
- Ajout à nouveau de [Jarby](https://osu.ppy.sh/users/25615) : Mapping Assistance Team (21/01/2011)
- Ajout de [Rukarioman](https://osu.ppy.sh/users/110372) : Mapping Assistance Team (21/01/2011)
- Ajout à nouveau de [arken1015](https://osu.ppy.sh/users/113646) : Mapping Assistance Team (25/01/2011)

## Février

- Ajout de [James2250](https://osu.ppy.sh/users/16978) : Beatmap Approval Team (20/02/2011)
- Transfert de [blissfulyoshi](https://osu.ppy.sh/users/20865) : Mapping Assistance Team > Beatmap Approval Team (20/02/2011)
- Transfert de [Derekku](https://osu.ppy.sh/users/91341) : Global Mod Team > Community Managers (20/02/2011)

## Mai

- Transfert de [Larto](https://osu.ppy.sh/users/12328) : Beatmap Approval Team > osu! Alumni (06/05/2011)
- Transfert de [Mafiamaster](https://osu.ppy.sh/users/17695) : Beatmap Approval Team > osu! Alumni (14/05/2011)
- Transfert de [Garven](https://osu.ppy.sh/users/244216) : Mapping Assistance Team > Beatmap Approval Team (20/05/2011)
- Transfert de [jericho2442](https://osu.ppy.sh/users/88904) : Mapping Assistance Team > Beatmap Approval Team (20/05/2011)
- Ajout de [Gonzvlo](https://osu.ppy.sh/users/237733) : Mapping Assistance Team (20/05/2011)

## Août

- Changement de nom : Beatmap Approval Team > Beatmap Appreciation Team (23/08/2011)

## Septembre

- Transfert de [mtmcl](https://osu.ppy.sh/users/5960) : Beatmap Appreciation Team > osu! Alumni (11/09/2011) 
- Ajout de [Krisom](https://osu.ppy.sh/users/99269) : Beatmap Appreciation Team (17/09/2011)
- Ajout de [RandomJibberish](https://osu.ppy.sh/users/157879) : Beatmap Appreciation Team (17/09/2011)
- Transfert de [Sakura Hana](https://osu.ppy.sh/users/289422) : Mapping Assistance Team > Beatmap Appreciation Team (17/09/2011)
- Ajout de [IceBeam](https://osu.ppy.sh/users/208440) : Mapping Assistance Team (29/09/2011)
- Ajout de [KuraiPettan](https://osu.ppy.sh/users/77089) : Mapping Assistance Team (29/09/2011)
- Ajout de [lolcubes](https://osu.ppy.sh/users/578401) : Mapping Assistance Team (29/09/2011)
- Ajout de [narakucrimson](https://osu.ppy.sh/users/287468) : Mapping Assistance Team (29/09/2011)
- Ajout de [NotShinta](https://osu.ppy.sh/users/162159) : Mapping Assistance Team (29/09/2011)
- Ajout de [Sallad4ever](https://osu.ppy.sh/users/185422) : Mapping Assistance Team (29/09/2011)
- Ajout de [SapphireGhost](https://osu.ppy.sh/users/388602) : Mapping Assistance Team (29/09/2011)

## Octobre

- Transfert de [Card N'FoRcE](https://osu.ppy.sh/users/3936) : Beatmap Appreciation Team > osu! Alumni (03/10/2011) 
- Transfert de [deepsea](https://osu.ppy.sh/users/7824) : Global Mod Team > osu! Alumni (10/10/2011) 

## Décembre

- Transfert de [Breeze](https://osu.ppy.sh/users/77537) : Mapping Assistance Team > Beatmap Appreciation Team (08/12/2011)
- Transfert de [Dangaard](https://osu.ppy.sh/users/19488) : Mapping Assistance Team > Beatmap Appreciation Team (08/12/2011)
- Transfert de [Gonzvlo](https://osu.ppy.sh/users/237733) : Mapping Assistance Team > Beatmap Appreciation Team (08/12/2011)
- Transfert de [IceBeam](https://osu.ppy.sh/users/208440) : Mapping Assistance Team > Beatmap Appreciation Team (08/12/2011)
- Transfert de [lolcubes](https://osu.ppy.sh/users/578401) : Mapping Assistance Team > Beatmap Appreciation Team (08/12/2011)
- Transfert de [narakucrimson](https://osu.ppy.sh/users/287468) : Mapping Assistance Team > Beatmap Appreciation Team (08/12/2011)
- Transfert de [Odaril](https://osu.ppy.sh/users/113005) : Mapping Assistance Team > Beatmap Appreciation Team (08/12/2011)
- Ajout de [Charles445](https://osu.ppy.sh/users/85000) : Mapping Assistance Team (08/12/2011)
- Ajout à nouveau de [Agnes](https://osu.ppy.sh/users/136982) : Mapping Assistance Team (08/12/2011)
- Transfert de [Mogsy](https://osu.ppy.sh/users/4018) : Beatmap Appreciation Team > osu! Alumni (15/12/2011) 

```

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2012/fr.md
> +- Ajouté [Pokie](https://osu.ppy.sh/users/207340) à Global Mod Team (2012-12-28) <!-- https://osu.ppy.sh/community/forums/posts/2014269 assuming gmt because he was already mat/bat and someone would'v
```suggestion
# Registre du personnel : 2012

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Janvier

- Ajout de [Aleks719](https://osu.ppy.sh/users/360176) : Mapping Assistance Team (01/01/2012)
- Ajout de [Ekaru](https://osu.ppy.sh/users/17938) : Mapping Assistance Team (01/01/2012)
- Ajout de [kanpakyin](https://osu.ppy.sh/users/394326) : Mapping Assistance Team (01/01/2012)
- Ajout de [Leorda](https://osu.ppy.sh/users/119134) : Mapping Assistance Team (01/01/2012)
- Ajout de [lovhin456](https://osu.ppy.sh/users/55096) : Mapping Assistance Team (01/01/2012)
- Ajout de [Suzully](https://osu.ppy.sh/users/431791) : Mapping Assistance Team (01/01/2012)
- Ajout de [wcx19911123](https://osu.ppy.sh/users/376831) : Mapping Assistance Team (01/01/2012)
- Ajout de [Armin](https://osu.ppy.sh/users/105902) : Mapping Assistance Team (02/01/2012) 
- Ajout de [DiamondCrash](https://osu.ppy.sh/users/123790) : Mapping Assistance Team (02/01/2012)
- Ajout de [Blue Dragon](https://osu.ppy.sh/users/19048) : Mapping Assistance Team (06/01/2012) 
- Ajout de [Faust](https://osu.ppy.sh/users/65152) : Mapping Assistance Team (06/01/2012)
- Ajout de [Kenezz](https://osu.ppy.sh/users/167050) : Mapping Assistance Team (06/01/2012)
- Ajout de [Kiddo-kun](https://osu.ppy.sh/users/104751) : Mapping Assistance Team (06/01/2012)
- Ajout de [NatsumeRin](https://osu.ppy.sh/users/151679) : Mapping Assistance Team (06/01/2012)
- Ajout de [Roddie](https://osu.ppy.sh/users/121337) : Mapping Assistance Team (06/01/2012)
- Ajout de [Shiirn](https://osu.ppy.sh/users/465126) : Mapping Assistance Team (06/01/2012)
- Ajout de [wmfchris](https://osu.ppy.sh/users/7401) : Mapping Assistance Team (06/01/2012)
- Transfert de [Loginer](https://osu.ppy.sh/users/819) : Beatmap Appreciation Team > osu! Alumni (16/01/2012) 

## Février

- Retrait de [NotShinta](https://osu.ppy.sh/users/162159) : Mapping Assistance Team (01/02/2012) 
- Retrait de [arken1015](https://osu.ppy.sh/users/113646) : Mapping Assistance Team (05/02/2012) 
- Retrait de [Ekaru](https://osu.ppy.sh/users/17938) : Mapping Assistance Team (21/02/2012) 

## Mars

- Retrait de [Faust](https://osu.ppy.sh/users/65152) : Mapping Assistance Team (01/03/2012) 
- Transfert de [Shiirn](https://osu.ppy.sh/users/465126) : Mapping Assistance Team > Beatmap Appreciation Team (20/03/2012)
- Transfert de [SapphireGhost](https://osu.ppy.sh/users/388602) : Mapping Assistance Team > Beatmap Appreciation Team (20/03/2012)
- Retrait de [Roddie](https://osu.ppy.sh/users/121337) : Mapping Assistance Team (30/03/2012) 

## Avril

- Transfert de [abalee](https://osu.ppy.sh/users/13103) : Beatmap Appreciation Team > osu! Alumni (09/04/2012) 

## Mai

- Transfert de [Andrea](https://osu.ppy.sh/users/33599) : Beatmap Appreciation Team > osu! Alumni (02/05/2012) 
- Transfert de [Gonzvlo](https://osu.ppy.sh/users/237733) : Beatmap Appreciation Team > osu! Alumni (12/05/2012) 
- Ajout à nouveau de [Roddie](https://osu.ppy.sh/users/121337) : Mapping Assistance Team (12/05/2012)
- Ajout de [Inamaru](https://osu.ppy.sh/users/76382) : Global Mod Team (12/05/2012)
- Ajout de [Kawayi Rika](https://osu.ppy.sh/users/596298) : Mapping Assistance Team (12/05/2012)
- Ajout de [those](https://osu.ppy.sh/users/557166) : Mapping Assistance Team (12/05/2012)
- Ajout de [Niva](https://osu.ppy.sh/users/197805) : Mapping Assistance Team (12/05/2012)
- Transfert de [Aleks719](https://osu.ppy.sh/users/360176) : Mapping Assistance Team > Beatmap Appreciation Team (12/05/2012)
- Transfert de [Charles445](https://osu.ppy.sh/users/85000) : Mapping Assistance Team > Beatmap Appreciation Team (12/05/2012)
- Transfert de [Kurai](https://osu.ppy.sh/users/77089) : Mapping Assistance Team > Beatmap Appreciation Team (12/05/2012)
- Ajout de [Elly-chan](https://osu.ppy.sh/users/660622) : Mapping Assistance Team (19/05/2012)
- Ajout de [Sync](https://osu.ppy.sh/users/806921) : Mapping Assistance Team (19/05/2012)
- Ajout de [LKs](https://osu.ppy.sh/users/150768) : Mapping Assistance Team (19/05/2012)
- Ajout de [Agnes](https://osu.ppy.sh/users/136982) : Beatmap Appreciation Team (19/05/2012)
- Ajout de [Suzully](https://osu.ppy.sh/users/431791) : Beatmap Appreciation Team (19/05/2012)
- Ajout de [wfmchris](https://osu.ppy.sh/users/7401) : Beatmap Appreciation Team (19/05/2012)
- Ajout à nouveau de [Shulin](https://osu.ppy.sh/users/150488) : Mapping Assistance Team (26/05/2012)
- Ajout de [Nymph](https://osu.ppy.sh/users/601990) : Mapping Assistance Team (12/05/2012)
- Ajout de [spboxer3](https://osu.ppy.sh/users/197974) : Mapping Assistance Team (12/05/2012)
- Ajout de [Miya](https://osu.ppy.sh/users/909167) : Mapping Assistance Team (12/05/2012)
- Ajout de [Blue Dragon](https://osu.ppy.sh/users/19048) : Beatmap Appreciation Team (19/05/2012)
- Retrait de [Lilac](https://osu.ppy.sh/users/58197) : Mapping Assistance Team (19/05/2012) 
- Ajout de [Loctav](https://osu.ppy.sh/users/71366) : Global Mod Team (20/05/2012)
- Ajout de [Galkan](https://osu.ppy.sh/users/169570) : Global Mod Team (20/05/2012)
- Ajout de [TicClick](https://osu.ppy.sh/users/672931) : Global Mod Team (20/05/2012)
- Transfert de [Odaril](https://osu.ppy.sh/users/113005) : Beatmap Appreciation Team > osu! Alumni (25/05/2012) 

## Juin

- Transfert de [Skyripper](https://osu.ppy.sh/users/31803) : osu! Alumni > Global Mod Team (02/06/2012)
- Ajout à nouveau de [Saturos-fangirl](https://osu.ppy.sh/users/11874) : Beatmap Appreciation Team (02/06/2012)
- Transfert de [Odaril](https://osu.ppy.sh/users/113005) : osu! Alumni > Beatmap Appreciation Team (26/06/2012) 

## Juillet

- Transfert de [jericho2442](https://osu.ppy.sh/users/88904) : Beatmap Appreciation Team > osu! Alumni (01/07/2012) 
- Retrait de [Rukarioman](https://osu.ppy.sh/users/110372) : Mapping Assistance Team (11/07/2012) 
- Transfert de [Agnes](https://osu.ppy.sh/users/136982) : Beatmap Appreciation Team > osu! Alumni (15/07/2012) 
- Retrait de [Roddie](https://osu.ppy.sh/users/121337) : Mapping Assistance Team (24/07/2012) 
- Ajout de [MMzz](https://osu.ppy.sh/users/128993) : Mapping Assistance Team (27/07/2012)

## Août

- Transfert de [Dangaard](https://osu.ppy.sh/users/19488) : Beatmap Appreciation Team > osu! Alumni (06/08/2012) 
- Ajout de [\[Delirium\]](https://osu.ppy.sh/users/519032) : Global Mod Team (10/08/2012) 
- Transfert de [Odaril](https://osu.ppy.sh/users/113005) : Beatmap Appreciation Team > osu! Alumni (12/08/2012) 
- Transfert de [Niva](https://osu.ppy.sh/users/197805) : Mapping Assistance Team > Beatmap Appreciation Team (13/08/2012)
- Transfert de [Sync](https://osu.ppy.sh/users/806921) : Mapping Assistance Team > Beatmap Appreciation Team (13/08/2012)
- Transfert de [Beuchi-chan](https://osu.ppy.sh/users/67192) : Global Mod Team > osu! Alumni (17/08/2012) 
- Ajout de [Lolicore Flandre](https://osu.ppy.sh/users/447818) : Global Mod Team (21/08/2012) 
- Retrait de [Blue Dragon](https://osu.ppy.sh/users/19048) : Beatmap Appreciation Team (23/08/2012) 
- Transfert de [narakucrimson](https://osu.ppy.sh/users/287468) : Beatmap Appreciation Team > osu! Alumni (24/08/2012) 
- Ajout de [Darksonic](https://osu.ppy.sh/users/570042) : Global Mod Team (26/08/2012) 

## Septembre

- Ajout à nouveau de [spboxer3](https://osu.ppy.sh/users/197974) : Mapping Assistance Team (01/09/2012)
- Ajout de [Loctav](https://osu.ppy.sh/users/71366) : Global Mod Team (01/09/2012)
- Ajout de [Byakugan249](https://osu.ppy.sh/users/660484) : Mapping Assistance Team (01/09/2012)
- Ajout de [Chewin](https://osu.ppy.sh/users/617323) : Mapping Assistance Team (01/09/2012)
- Transfert de [Armin](https://osu.ppy.sh/users/105902) : Mapping Assistance Team > Beatmap Appreciation Team (01/09/2012)
- Transfert de [NatsumeRin](https://osu.ppy.sh/users/151679) : Mapping Assistance Team > Beatmap Appreciation Team (01/09/2012)
- Ajout à nouveau de [Jarby](https://osu.ppy.sh/users/25615) : Mapping Assistance Team (29/09/2012)
- Transfert de [ [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2013/fr.md
> +- Ajouté [Byakugan249](https://osu.ppy.sh/users/660484) à Beatmap Appreciation Team (2013-12-29) <!-- https://osu.ppy.sh/community/forums/posts/2770364 -->
```suggestion
# Registre du personnel : 2013

*Remarque: L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Janvier

- Transfert de [Sushi](https://osu.ppy.sh/users/43108) : Mapping Assistance Team > Beatmap Appreciation Team (04/01/2013) 
- Transfert de [Agnes](https://osu.ppy.sh/users/136982) : osu! Alumni > Beatmap Appreciation Team (04/01/2013)
- Transfert de [jericho2442](https://osu.ppy.sh/users/88904) : osu! Alumni > Beatmap Appreciation Team (04/01/2013)
- Retrait de [Mara](https://osu.ppy.sh/users/194294) : Chat Moderators (13/01/2013) 
- Ajout de [Makar](https://osu.ppy.sh/users/686389) : Chat Moderators (23/01/2013) 
- Ajout de [matthewhln](https://osu.ppy.sh/users/291487) : Chat Moderators (24/01/2013) 
- Ajout à nouveau de [Faust](https://osu.ppy.sh/users/65152) : Mapping Assistance Team (24/01/2013)

## Février

- Transfert de [IceBeam](https://osu.ppy.sh/users/208440) : Beatmap Appreciation Team > osu! Alumni (07/02/2013) 
- Ajout de [Jacob](https://osu.ppy.sh/users/976963) : Mapping Assistance Team (07/02/2013)
- Ajout de [Pokie](https://osu.ppy.sh/users/207340) : Mapping Assistance Team (07/02/2013)
- Ajout de [Frostmourne](https://osu.ppy.sh/users/199669) : Mapping Assistance Team (07/02/2013)
- Ajout à nouveau de [Nymph](https://osu.ppy.sh/users/601990) : Mapping Assistance Team (16/02/2013)
- Ajout à nouveau de [xxheroxx](https://osu.ppy.sh/users/25999) : Mapping Assistance Team (16/02/2013)
- Ajout de [Gabe](https://osu.ppy.sh/users/654108) : Mapping Assistance Team (16/02/2013)
- Ajout de [popner](https://osu.ppy.sh/users/759860) : Mapping Assistance Team (16/02/2013)
- Transfert de [-kevincela-](https://osu.ppy.sh/users/266596) : Mapping Assistance Team > Beatmap Appreciation Team (16/02/2013)
- Transfert de [Colin Hou](https://osu.ppy.sh/users/196614) : Mapping Assistance Team > Beatmap Appreciation Team (16/02/2013)
- Transfert de [Kawayi Rika](https://osu.ppy.sh/users/596298) : Mapping Assistance Team > Beatmap Appreciation Team (16/02/2013)
- Transfert de [Scorpiour](https://osu.ppy.sh/users/867259) : Mapping Assistance Team > Beatmap Appreciation Team (16/02/2013)
- Ajout de [HeatKai](https://osu.ppy.sh/users/332555) : Chat Moderators 
- Ajout de [Saten](https://osu.ppy.sh/users/444506) : Chat Moderators (16/02/2013)
- Ajout de [ethox](https://osu.ppy.sh/users/441380) : Chat Moderators (16/02/2013)
- Ajout de [Pereira006](https://osu.ppy.sh/users/537344) : Chat Moderators (16/02/2013)
- Transfert de [Breeze](https://osu.ppy.sh/users/77537) : Beatmap Appreciation Team > osu! Alumni (17/02/2013)

## Mars

- Ajout de [Potofu](https://osu.ppy.sh/users/657404) : Chat Moderators (02/03/2013) 
- Ajout de [Mercurius](https://osu.ppy.sh/users/589550) : Chat Moderators (02/03/2013)
- Ajout de [Sakura](https://osu.ppy.sh/users/289422) : Global Mod Team (03/03/2013) 
- Transfert de [Andrea](https://osu.ppy.sh/users/33599) : Beatmap Appreciation Team > osu! Alumni (08/03/2013) 
- Transfert de [grumd](https://osu.ppy.sh/users/530913) : Mapping Assistance Team > Beatmap Appreciation Team (18/03/2013) 
- Ajout de [Wojjan](https://osu.ppy.sh/users/32856) : Chat Moderators (20/03/2013) 
- Ajout de [DeathxShinigami](https://osu.ppy.sh/users/49516) : Chat Moderators (21/03/2013) 
- Ajout de [theowest](https://osu.ppy.sh/users/60604) : Global Moderation Team (21/03/2013)
- Ajout de [Mr Color](https://osu.ppy.sh/users/116078) : Chat Moderators (24/03/2013)
- Retrait de [YGOkid8](https://osu.ppy.sh/users/69114) : Mapping Assistance Team (25/03/2013) 
- Ajout de [Kokatsu](https://osu.ppy.sh/users/1019859) : Chat Moderators (26/03/2013) 
- Ajout de [Mystyk](https://osu.ppy.sh/users/930165) : Chat Moderators (26/03/2013)
- Ajout de [Melophobia](https://osu.ppy.sh/users/1077845) : Chat Moderators (29/03/2013)

## Avril

- Ajout à nouveau de [Teara](https://osu.ppy.sh/users/123491) : Mapping Assistance Team (01/04/2013) 
- Ajout de [Nyquill](https://osu.ppy.sh/users/682935) : Mapping Assistance Team (01/04/2013)
- Ajout de [Makar](https://osu.ppy.sh/users/686389) : Mapping Assistance Team (01/04/2013)
- Ajout de [Kei](https://osu.ppy.sh/users/346677) : Mapping Assistance Team (01/04/2013)
- Ajout de [LunarSakuya](https://osu.ppy.sh/users/1027860) : Mapping Assistance Team (01/04/2013)
- Ajout de [Strawberry](https://osu.ppy.sh/users/519978) : Mapping Assistance Team (01/04/2013)
- Ajout de [Leader](https://osu.ppy.sh/users/631530) : Chat Moderators (03/04/2013)
- Ajout de [eveless](https://osu.ppy.sh/users/102976) : Chat Moderators (03/04/2013)
- Transfert de [Pokie](https://osu.ppy.sh/users/207340) : Mapping Assistance Team > Beatmap Appreciation Team (05/04/2013)
- Transfert de [Faust](https://osu.ppy.sh/users/65152) : Mapping Assistance Team > Beatmap Appreciation Team (05/04/2013)
- Transfert de [NoHitter](https://osu.ppy.sh/users/124455) : Mapping Assistance Team > Beatmap Appreciation Team (05/04/2013)
- Transfert de [mancuso\_JM\_](https://osu.ppy.sh/users/521568) : Mapping Assistance Team > Beatmap Appreciation Team (05/04/2013)
- Ajout de [chonicle](https://osu.ppy.sh/users/146538) : osu!mania Mapping Assistance Team (06/04/2013)
- Ajout de [Entozer](https://osu.ppy.sh/users/277044) : osu!mania Mapping Assistance Team (06/04/2013)
- Ajout de [Ballance](https://osu.ppy.sh/users/165946) : Chat Moderators (09/04/2013)
- Ajout de [XPJ38](https://osu.ppy.sh/users/273531) : Support Team (10/04/2013)
- Ajout de [Winshley](https://osu.ppy.sh/users/864895) : Support Team (11/04/2013)
- Ajout de [DeathxShinigami](https://osu.ppy.sh/users/49516) : Global Moderation Team (14/04/2013)
- Transfert de [James2250](https://osu.ppy.sh/users/16978) : Global Moderation Team (18/04/2013)
- Retrait de [Kiddo-kun](https://osu.ppy.sh/users/104751) : Mapping Assistance Team (21/04/2013) 
- Transfert de tous les membres : Mapping Assistance Team > Beatmap Appreciation Team (23/04/2013) 
- Transfert de [Kenezz](https://osu.ppy.sh/users/167050) Beatmap Appreciation Team : osu! Alumni (24/03/2013) 
- Ajout de [deadbeat](https://osu.ppy.sh/users/128370) : Support Team (25/04/2013) 
- Ajout de [MillhioreF](https://osu.ppy.sh/users/941094) : Support Team (25/04/2013)
- Ajout de [TheVileOne](https://osu.ppy.sh/users/278862) : Support Team (25/04/2013)
- Transfert de [Shiro](https://osu.ppy.sh/users/113005) : osu! Alumni > Beatmap Appreciation Team (26/04/2013) 
- Transfert de [ignorethis](https://osu.ppy.sh/users/27343) : Chat Moderators > osu! Alumni (30/04/2013)

## Mai

- Retrait de [LKs](https://osu.ppy.sh/users/150768) : Beatmap Appreciation Team (02/05/2013) 
- Ajout de [orioncomet](https://osu.ppy.sh/users/104827) : Beatmap Appreciation Team (04/05/2013) 
- Ajout de [ykcarrot](https://osu.ppy.sh/users/70730) : Beatmap Appreciation Team (04/05/2013)
- Transfert de [narakucrimson](https://osu.ppy.sh/users/287468) : Beatmap Appreciation Team > osu! Alumni (06/05/2013) 
- Ajout de [Miya](https://osu.ppy.sh/users/909167) : Beatmap Appreciation Team (08/05/2013) 
- Ajout de [xierbaliti](https://osu.ppy.sh/users/34044) : Beatmap Appreciation Team (11/05/2013)
- Ajout de [TicClick](https://osu.ppy.sh/users/672931) : Global Moderation Team (13/05/2013)
- Ajout de [HeatKai](https://osu.ppy.sh/users/332555) : Beatmap Appreciation Team (13/05/2013)
- Transfert de [Kurai](https://osu.ppy.sh/users/77089) : Beatmap Appreciation Team > BATmanager (13/05/2013) 
- Transfert de [Garven](https://osu.ppy.sh/users/244216) : Beatmap Appreciation Team > BATmanager (13/05/2013)
- Transfert de [NatsumeRin](https://osu.ppy.sh/users/151679) : Beatmap Appreciation Team > BATmanager (13/05/2013)
- Ajout de [fartownik](https://osu.ppy.sh/users/56917) : Beatmap Appreciation Team (14/05/2013) 
- Ajout de [NaomiMinette](https://osu.ppy.sh/users/120265) : Global Moderation Team (20/05/2013)
- Ajout de [DiamondCrash](https://osu.ppy.sh/users/123790) : Beatmap Appreciation Team (24/05/2013)

## Juin

- Ajout de [Saten](https://osu.ppy.sh/users/444506) : Global Moderatio [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2014/fr.md
> +- [xxdeathx](https://osu.ppy.sh/users/3034880)
```suggestion
# Registre du personnel : 2014

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Janvier

- Ajout de [[Shi-Ra]](https://osu.ppy.sh/users/2008489) : Beatmap Appreciation Team (01/01/2014)
- Ajout de [TKS](https://osu.ppy.sh/users/940878) : Beatmap Appreciation Team (04/01/2014)
- Ajout à nouveau de [Teara](https://osu.ppy.sh/users/123491) : Beatmap Appreciation Team (05/01/2014)
- Ajout de [shARPII](https://osu.ppy.sh/users/776257) : Chat Moderators (16/01/2014)
- Ajout de [Stickie](https://osu.ppy.sh/users/1248732) : Chat Moderators (16/01/2014)
- Retrait de [Gabe](https://osu.ppy.sh/users/654108) : Beatmap Appreciation Team (17/01/2014)
- Ajout de [Krah](https://osu.ppy.sh/users/1436748) : Beatmap Appreciation Team (20/01/2014)
- Ajout à nouveau de [dkun](https://osu.ppy.sh/users/154400) : Beatmap Appreciation Team (20/01/2014)
- Transfert de [Breeze](https://osu.ppy.sh/users/77537) : osu! Alumni (21/01/2014)
- Retrait de [HeatKai](https://osu.ppy.sh/users/332555) : Beatmap Appreciation Team (21/01/2014)
- Transfert de [jericho2442](https://osu.ppy.sh/users/88904) : osu! Alumni (21/01/2014)
- Transfert de [lolcubes](https://osu.ppy.sh/users/578401) : osu! Alumni (21/01/2014)
- Transfert de [MMzz](https://osu.ppy.sh/users/128993) : osu! Alumni (21/01/2014)
- Transfert de [Sync](https://osu.ppy.sh/users/806921) : osu! Alumni (21/01/2014)
- Transfert de [those](https://osu.ppy.sh/users/557166) : osu! Alumni (21/01/2014)
- Transfert de [YGOKid8](https://osu.ppy.sh/users/69114) : osu! Alumni (21/01/2014)
- Transfert de [Gabe](https://osu.ppy.sh/users/654108) : Beatmap Appreciation Team > osu! Alumni (21/01/2014)
- Ajout à nouveau de [YGOKid8](https://osu.ppy.sh/users/69114) : Beatmap Appreciation Team (23/01/2014)
- Transfert de [Sakura](https://osu.ppy.sh/users/289422) : osu! Alumni (24/01/2014)
- Transfert de [Kurai](https://osu.ppy.sh/users/77089) : Global Moderation Team (25/01/2014)
- Ajout de [HelloSCV](https://osu.ppy.sh/users/798743) : Beatmap Appreciation Team (27/01/2014)

## Février

- Ajout de [Gabe](https://osu.ppy.sh/users/654108) : Beatmap Appreciation Team (02/02/2014)
- Ajout à nouveau de [Blue Dragon](https://osu.ppy.sh/users/19048) : Beatmap Appreciation Team (03/02/2014)
- Ajout à nouveau de [Low](https://osu.ppy.sh/users/976963) : Beatmap Appreciation Team (03/02/2014)
- Transfert de [KSHR](https://osu.ppy.sh/users/409957) : Beatmap Appreciation Team (07/02/2014)
- Transfert de [Marcin](https://osu.ppy.sh/users/722665) : Global Moderation Team (07/02/2014)
- Ajout de [BeatofIke](https://osu.ppy.sh/users/1103522) : Beatmap Appreciation Team (07/02/2014)
- Ajout de [Zero\_\_wind](https://osu.ppy.sh/users/1822830) : Beatmap Appreciation Team (07/02/2014)
- Transfert de [kanpakyin](https://osu.ppy.sh/users/394326) : osu! Alumni (07/02/2014)
- Transfert de [lolcubes](https://osu.ppy.sh/users/578401) : Beatmap Appreciation Team (10/02/2014)
- Transfert de [Dangaard](https://osu.ppy.sh/users/19488) : osu! Alumni (15/02/2014)
- Transfert de [Flanster](https://osu.ppy.sh/users/447818) : osu! Alumni (15/02/2014)
- Ajout de [Kitokofox](https://osu.ppy.sh/users/1815420) : Chat Moderators (22/02/2014)
- Ajout de [Nathanael](https://osu.ppy.sh/users/2295078) : Support Team (23/02/2014)
- Ajout de [Loneight](https://osu.ppy.sh/users/663131) : Chat Moderators (23/02/2014)
- Transfert de [happy30](https://osu.ppy.sh/users/27767) : osu! Alumni (24/02/2014)
- Transfert de [KanaRin](https://osu.ppy.sh/users/310747) : osu! Alumni (24/02/2014)
- Transfert de [narakucrimson](https://osu.ppy.sh/users/287468) : osu! Alumni (24/02/2014)
- Transfert de [NatsumeRin](https://osu.ppy.sh/users/151679) : osu! Alumni (24/02/2014)
- Transfert de [Nymph](https://osu.ppy.sh/users/601990) : osu! Alumni (24/02/2014)
- Transfert de [wcx19911123](https://osu.ppy.sh/users/376831) : osu! Alumni (24/02/2014)
- Ajout de [mtmcl](https://osu.ppy.sh/users/5960) : osu! Alumni (24/02/2014)

## Mars

- Transfert de [Chewin](https://osu.ppy.sh/users/617323) : osu! Alumni > Beatmap Appreciation Team (06/03/2014)
- Retrait de [HelloSCV](https://osu.ppy.sh/users/798743) : Beatmap Appreciation Team (13/03/2014)
- Transfert de [ljqandylee](https://osu.ppy.sh/users/141469) : osu! Alumni (17/03/2014)
- Ajout de [h3k1ru](https://osu.ppy.sh/users/291211) : Chat Moderators (19/03/2014)
- Ajout de [Stefan](https://osu.ppy.sh/users/626907) : Chat Moderators (28/03/2014)
- Transfert de [blissfulyoshi](https://osu.ppy.sh/users/20865) : osu! Alumni (29/03/2014)
- Transfert de [lolcubes](https://osu.ppy.sh/users/578401) : osu! Alumni (29/03/2014)
- Transfert de [SapphireGhost](https://osu.ppy.sh/users/388602) : osu! Alumni (29/03/2014)
- Transfert de [Teara](https://osu.ppy.sh/users/123491) : osu! Alumni (29/03/2014)
- Retrait de [Low](https://osu.ppy.sh/users/976963) : Beatmap Appreciation Team (29/03/2014)
- Ajout de [ursa](https://osu.ppy.sh/users/321063) : Beatmap Appreciation Team (30/03/2014)

## Avril

- Transfert de [Kurai](https://osu.ppy.sh/users/77089) : Beatmap Appreciation Team (04/04/2014)
- Retrait de [UnitedWeSin](https://osu.ppy.sh/users/1778050) : Beatmap Appreciation Team (11/04/2014)
- Transfert de [Agnes](https://osu.ppy.sh/users/136982) : Beatmap Appreciation Team > osu! Alumni (15/04/2014)
- Transfert de [awp](https://osu.ppy.sh/users/2650) : osu! Alumni (15/04/2014)
- Transfert de [Makar](https://osu.ppy.sh/users/686389) : osu! Alumni (15/04/2014)
- Transfert de [La Cataline](https://osu.ppy.sh/users/301279) : osu! Alumni (15/04/2014)
- Transfert de [senaya](https://osu.ppy.sh/users/304103) : osu! Alumni (15/04/2014)
- Transfert de [Sushi](https://osu.ppy.sh/users/43108) : osu! Alumni (15/04/2014)
- Ajout de [Love](https://osu.ppy.sh/users/467487) : Beatmap Appreciation Team (21/04/2014)
- Ajout de [Xytox](https://osu.ppy.sh/users/2229274) : Chat Moderators (21/04/2014)
- Transfert de [Pokie](https://osu.ppy.sh/users/207340) : Global Moderation Team (22/04/2014)
- Transfert de [Darksonic](https://osu.ppy.sh/users/570042) : osu! Alumni (24/04/2014)

## Mai

- Ajout de [Asphyxia](https://osu.ppy.sh/users/1715720) : Beatmap Appreciation Team (03/05/2014)
- Transfert de [Leader](https://osu.ppy.sh/users/631530) : Beatmap Appreciation Team (03/05/2014)
- Transfert de [Andrea](https://osu.ppy.sh/users/33599) : Global Moderation Team (04/05/2014)
- Retrait de [Blue Dragon](https://osu.ppy.sh/users/19048) : Beatmap Appreciation Team (04/05/2014)
- Ajout de [Trust](https://osu.ppy.sh/users/1470352) : Beatmap Appreciation Team (04/05/2014)
- Ajout de [captin1](https://osu.ppy.sh/users/689997) : Beatmap Appreciation Team (04/05/2014)
- Ajout à nouveau de [kanpakyin](https://osu.ppy.sh/users/394326) : Beatmap Appreciation Team (04/05/2014)
- Ajout de [DakeDekaane](https://osu.ppy.sh/users/1425253) : Beatmap Appreciation Team (04/05/2014)
- Ajout de [Guy](https://osu.ppy.sh/users/91738) : Beatmap Appreciation Team (04/05/2014)
- Transfert de [Gabe](https://osu.ppy.sh/users/654108) : Global Moderation Team (05/05/2014)
- Ajout de [Atrue](https://osu.ppy.sh/users/1758523) : Beatmap Appreciation Team (06/05/2014)
- Ajout à nouveau de [Kenezz](https://osu.ppy.sh/users/167050) : Beatmap Appreciation Team (06/05/2014)
- Transfert de [Shiro](https://osu.ppy.sh/users/113005) : Beatmap Appreciation Team (08/05/2014)
- Transfert de [Byakugan249](https://osu.ppy.sh/users/660484) : osu! Alumni (11/05/2014)
- Transfert de [Strawberry](https://osu.ppy.sh/users/519978) : Beatmap Appreciation Team > osu! Alumni (11/05/2014)
- Retrait de [Krah](https://osu.ppy.sh/users/1436748) : Beatmap Appreciation Team (11/05/2014)
- Transfert de [MMzz](https://osu.ppy.sh/users/128993) : osu! Alumni : Beatmap Appreciation Team (15/05/2014)
- Ajout de [Cookie](https://osu.ppy.sh/users/4697926) : Chat Moderators (16/05/2014)
- Ajout de [Maeglwn](https://osu.ppy.sh/users/2440936) : Chat Moderators (16/05/2014)
- Ajout à nouveau de [Pereira006](https://osu.ppy.s [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2015/fr.md
> +- Transféré [Lust](https://osu.ppy.sh/users/2316951) de Quality Assurance Team à osu! Alumni (2015-12-22)
```suggestion
# Registre du personnel : 2015

*Remarque : L'histoire de quelques utilisateurs peut être incomplète pendant cette année.*

## Janvier

- Transfert de [Krisom](https://osu.ppy.sh/users/99269) : osu! Alumni (03/01/2015)
- Retrait de [Nemis](https://osu.ppy.sh/users/1635091) : Beatmap Appreciation Team (03/01/2015)
- Transfert de [NoHitter](https://osu.ppy.sh/users/124455) : osu! Alumni (03/01/2015)
- Transfert de [PROGUY](https://osu.ppy.sh/users/528181) : osu! Alumni (07/01/2015)
- Retrait de [ursa](https://osu.ppy.sh/users/321063) : Quality Assurance Team (14/01/2015)
- Transfert de [CLSW](https://osu.ppy.sh/users/531253) : Beatmap Appreciation Team > Quality Assurance Team (26/01/2015)
- Transfert de [Frostmourne](https://osu.ppy.sh/users/199669) : osu! Alumni > Global Moderation Team (27/01/2015)

### Nouveaux ajouts à la BAT

Tous les utilisateurs listés ci-dessous ont été ajoutés le 03/01/2015 :

- [[ S a k u r a ]](https://osu.ppy.sh/users/3653042)
- [Andrea](https://osu.ppy.sh/users/33599)
- [BeatofIke](https://osu.ppy.sh/users/1103522)
- [CloudSplash16](https://osu.ppy.sh/users/2099102)
- [[CSGA]Ar3sgice](https://osu.ppy.sh/users/989563)
- [DE-CADE](https://osu.ppy.sh/users/3734394)
- [Inyuschan](https://osu.ppy.sh/users/1721995)
- [Momochikun](https://osu.ppy.sh/users/2032824)
- [Okoratu](https://osu.ppy.sh/users/1623405)
- [OniJAM](https://osu.ppy.sh/users/961752)
- [Pereira006](https://osu.ppy.sh/users/537344)
- [Pho](https://osu.ppy.sh/users/3624692)
- [pieguy1372](https://osu.ppy.sh/users/107485)
- [Sonnyc](https://osu.ppy.sh/users/11771)
- [Xgor](https://osu.ppy.sh/users/98661)

## Février

- Transfert de [QHideaki13](https://osu.ppy.sh/users/733998) : osu! Alumni (01/02/2015)
- Transfert de [KSHR](https://osu.ppy.sh/users/409957) : osu! Alumni > Global Moderation Team (01/02/2015)
- Transfert de [-kevincela-](https://osu.ppy.sh/users/266596) : Beatmap Appreciation Team > osu! Alumni (05/02/2015)
- Transfert de [Kenezz](https://osu.ppy.sh/users/167050) : osu! Alumni (05/02/2015)
- Transfert de [Leader](https://osu.ppy.sh/users/631530) : Global Moderation Team (05/02/2015)
- Transfert de [narakucrimson](https://osu.ppy.sh/users/287468) : osu! Alumni (05/02/2015)
- Transfert de [Flanster](https://osu.ppy.sh/users/447818) : Chat Moderators > Global Moderation Team (11/02/2015)
- Retrait de [Wojjan](https://osu.ppy.sh/users/32856) : Forum Moderators et Chat Moderators (13/02/2015)
- Transfert de [Lust](https://osu.ppy.sh/users/2316951) : Beatmap Appreciation Team > Quality Assurance Team (16/02/2015)
- Transfert de [Shiro](https://osu.ppy.sh/users/113005) : Quality Assurance Team > Global Moderation Team (16/02/2015)
- Transfert de [Asphyxia](https://osu.ppy.sh/users/1715720) : Global Moderation Team > Quality Assurance Team (18/02/2015)
- Transfert de [Myxo](https://osu.ppy.sh/users/2202645) : Beatmap Appreciation Team > Quality Assurance Team (18/02/2015)
- Transfert de [Mystyk](https://osu.ppy.sh/users/930165) : Global Moderation Team (18/02/2015)
- Transfert de [IamKwaN](https://osu.ppy.sh/users/1856463) : Beatmap Appreciation Team > Quality Assurance Team (19/02/2015)
- Retrait de [AnataNoBaka](https://osu.ppy.sh/users/1769646) de Chat Moderators (22/02/2015)
- Transfert de [ethox](https://osu.ppy.sh/users/441380) : osu! Alumni (22/02/2015)
- Retrait de [Evil_Twilight](https://osu.ppy.sh/users/409347) : Chat Moderators (22/02/2015)
- Transfert de [Galkan](https://osu.ppy.sh/users/169570) : osu! Alumni (22/02/2015)
- Retrait de [Guy](https://osu.ppy.sh/users/91738) : Chat Moderators (22/02/2015)
- Transfert de [HeatKai](https://osu.ppy.sh/users/332555) : osu! Alumni (22/02/2015)
- Transfert de [KitokoFox](https://osu.ppy.sh/users/1815420) : osu! Alumni (22/02/2015)
- Transfert de [KRZY](https://osu.ppy.sh/users/114017) : osu! Alumni (22/02/2015)
- Retrait de [Loneight](https://osu.ppy.sh/users/663131) : Chat Moderators (22/02/2015)
- Transfert de [Zero__wind](https://osu.ppy.sh/users/1822830) : Beatmap Appreciation Team > osu! Alumni (22/02/2015)
- Transfert de [Darksonic](https://osu.ppy.sh/users/570042) : Global Moderation Team > osu! Alumni (22/02/2015)
- Transfert de [Derekku](https://osu.ppy.sh/users/91341) : osu! Alumni (22/02/2015)
- Transfert de [Leader](https://osu.ppy.sh/users/631530) : osu! Alumni (22/02/2015)
- Transfert de [Mystyk](https://osu.ppy.sh/users/930165) : Chat Moderators (22/02/2015)
- Transfert de [Pokie](https://osu.ppy.sh/users/207340) : osu! Alumni (22/02/2015)
- Transfert de [Where](https://osu.ppy.sh/users/549172) : osu! Alumni (22/02/2015)
- Transfert de [drum drum](https://osu.ppy.sh/users/4435526) : Global Moderation Team (22/02/2015)
- Transfert de [ToGlette](https://osu.ppy.sh/users/1076236) : Chat Moderators > Global Moderation Team (22/02/2015)
- Retrait de [Scorpiour](https://osu.ppy.sh/users/867259) : Global Moderation Team (28/02/2015)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 06/02/2015 :

- [Vhy](https://osu.ppy.sh/users/2083612)
- [tutuhaha](https://osu.ppy.sh/users/546991)
- [Starry-](https://osu.ppy.sh/users/2166199)
- [Sekai-nyan](https://osu.ppy.sh/users/700887)
- [scanter](https://osu.ppy.sh/users/1742622)
- [REDYUMiKA](https://osu.ppy.sh/users/3100145)
- [Priti](https://osu.ppy.sh/users/2198472)
- [No Dap](https://osu.ppy.sh/users/3044645)
- [neonat](https://osu.ppy.sh/users/1561995)
- [Nardoxyribonucleic](https://osu.ppy.sh/users/876419)
- [Mei](https://osu.ppy.sh/users/1482243)
- [Marirose](https://osu.ppy.sh/users/1899763)
- [LordRaika](https://osu.ppy.sh/users/3265023)
- [LexiaLovesU](https://osu.ppy.sh/users/1710462)
- [Kuo Kyoka](https://osu.ppy.sh/users/2596306)
- [Kodora](https://osu.ppy.sh/users/8596)
- [koreapenguin](https://osu.ppy.sh/users/1458069)
- [Kawaiwkyik](https://osu.ppy.sh/users/1367570)
- [Ichigaki](https://osu.ppy.sh/users/2403444)
- [HelloSCV](https://osu.ppy.sh/users/798743)
- [HabiHolic](https://osu.ppy.sh/users/1974436)
- [Gaia](https://osu.ppy.sh/users/2683648)
- [ExUsagi](https://osu.ppy.sh/users/10004749)
- [appleeaterx](https://osu.ppy.sh/users/2407160)

## Mars

- Transfert de [aabc271](https://osu.ppy.sh/users/155707) : osu! Alumni (02/03/2015)
- Transfert de [Gabe](https://osu.ppy.sh/users/654108) : osu! Alumni (02/03/2015)
- Transfert de [lolcubes](https://osu.ppy.sh/users/578401) : Quality Assurance Team (11/03/2015)
- Transfert de [Roxas](https://osu.ppy.sh/users/1041833) : osu! Alumni > Quality Assurance Team (11/03/2015)
- Ajout de [Fycho](https://osu.ppy.sh/users/1876867) : Chat Moderators (12/03/2015)
- Ajout de [VeilStar](https://osu.ppy.sh/users/4255720) : Support Team (28/03/2015)

### Nouveaux Beatmap Nominators 

Tous les utilisateurs listés ci-dessous ont été ajoutés le 03/03/2015 :

- [Static Noise Bird](https://osu.ppy.sh/users/826132)
- [Lally](https://osu.ppy.sh/users/1262490)
- [-Nya-](https://osu.ppy.sh/users/1293097)
- [Harbyter](https://osu.ppy.sh/users/1147679)
- [Alarido](https://osu.ppy.sh/users/1948827)
- [Yauxo](https://osu.ppy.sh/users/898306)
- [[AyanoTatemaya]](https://osu.ppy.sh/users/2760619)
- [shionelove](https://osu.ppy.sh/users/501551)
- [Genocide](https://osu.ppy.sh/users/6477309)
- [CelsiusLK](https://osu.ppy.sh/users/1409012)
- [ZZHBOY](https://osu.ppy.sh/users/1565739)
- [Gray Veyron](https://osu.ppy.sh/users/1886524)
- [\_S u w a k o\_](https://osu.ppy.sh/users/2786984)
- [sheela901](https://osu.ppy.sh/users/1138027)
- [[GraveChaos]](https://osu.ppy.sh/users/3009472)
- [[Shana Lesus]](https://osu.ppy.sh/users/2881789)
- [handsome](https://osu.ppy.sh/users/2123087)
- [Zan -](https://osu.ppy.sh/users/1411817)
- [Z3nx](https://osu.ppy.sh/users/2193881)
- [RuberusuScarlet](https://osu.ppy.sh/users/2534632)

## Avril

- Transfert de [TKS](https://osu.ppy.sh/users/940878) : Beatmap Appreciation Team > osu! Alumni (01/04/2015)
- Transfert de [Kawayi Rika](https://osu.ppy.sh/users/596298) : osu! Alumni (01/04/2015)
- Transfert de [QHideaki13](https://osu.ppy [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2016/fr.md
> +- [snowball112](https://osu.ppy.sh/users/2350722)
```suggestion
# Registre du personnel : 2016

## Janvier

- Ajout de [Nishiji](https://osu.ppy.sh/users/167629) : Global Moderation Team (03/01/2016)
- Transfert de [Nyquill](https://osu.ppy.sh/users/682935) : osu! Alumni > Global Moderation Team (03/01/2016)
- Transfert de [Irreversible](https://osu.ppy.sh/users/1287964) : Quality Assurance Team > osu! Alumni (25/01/2016)
- Transfert de [alacat](https://osu.ppy.sh/users/869782) : Quality Assurance Team > osu! Alumni (29/01/2016)

### Nouveaux Beatmap Nominators

- [Sey](https://osu.ppy.sh/users/553656) (20/01/2016)
- [- Magic Bomb -](https://osu.ppy.sh/users/3071175) (20/01/2016)
- [koliron](https://osu.ppy.sh/users/4632730) (20/01/2016)
- [-Kamikaze-](https://osu.ppy.sh/users/2124783) (21/01/2016)
- [Feerum](https://osu.ppy.sh/users/4815717) (21/01/2016)
- [newyams99](https://osu.ppy.sh/users/3701008) (23/01/2016)

## Février

- Transfert de [Irreversible](https://osu.ppy.sh/users/1287964) : osu! Alumni > Quality Assurance Team (20/02/2016)
- Transfert de [Galkan](https://osu.ppy.sh/users/169570) : osu! Alumni > Global Moderation Team (20/02/2016)
- Transfert de [Guy](https://osu.ppy.sh/users/91738) : Quality Assurance Team > osu! Alumni (25/02/2016)

## Mars

- Transfert de [Gamu](https://osu.ppy.sh/users/611174) : Quality Assurance Team > osu! Alumni (03/03/2016)
- Transfert de [Zero__wind](https://osu.ppy.sh/users/1822830) : osu! Alumni > Global Moderation Team (17/03/2016)
- Ajout de [Seijiro](https://osu.ppy.sh/users/2581696) : Global Moderation Team (17/03/2016)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 07/03/2016 :

- [Nozhomi](https://osu.ppy.sh/users/2716981)
- [Sonnyc](https://osu.ppy.sh/users/11771)
- [Regraz](https://osu.ppy.sh/users/3076909)
- [Bonsai](https://osu.ppy.sh/users/987334)
- [Kibbleru](https://osu.ppy.sh/users/3193504)
- [Squirrel](https://osu.ppy.sh/users/9623122)
- [Avishay](https://osu.ppy.sh/users/2597311)

## Mai

- Ajout de [Pittigbaasje](https://osu.ppy.sh/users/2167433) : Global Moderation Team (04/05/2016)
- Transfert de [Atrue](https://osu.ppy.sh/users/1758523) : Global Moderation Team > osu! Alumni (31/05/2016)
- Transfert de [Blazevoir](https://osu.ppy.sh/users/120265) : osu! Alumni (31/05/2016)
- Transfert de [Charles445](https://osu.ppy.sh/users/85000) : Quality Assurance Team > osu! Alumni (31/05/2016)
- Transfert de [Krah](https://osu.ppy.sh/users/1436748) : Global Moderation Team > osu! Alumni (31/05/2016)
- Transfert de [Spectator](https://osu.ppy.sh/users/702598) : Global Moderation Team > osu! Alumni (31/05/2016)
- Retrait de [Zak](https://osu.ppy.sh/users/1375955) : Global Moderation Team (31/05/2016)
- Transfert de [OnosakiHito](https://osu.ppy.sh/users/290128) : osu! Alumni > Global Moderation Team (31/05/2016)
- Transfert de [Starry-](https://osu.ppy.sh/users/2166199) : Quality Assurance Team > osu! Alumni (31/05/2016)

## Juin

- Ajout de [Dntm8kmeeatu](https://osu.ppy.sh/users/5428812) : Support Team (04/06/2016)
- Ajout de [Dntm8kmeeatu](https://osu.ppy.sh/users/5428812) : Global Moderation Team (07/06/2016)
- Ajout de [Elfin](https://osu.ppy.sh/users/1399551) : Global Moderation Team (08/06/2016)
- Ajout de [Shurelia](https://osu.ppy.sh/users/3807986) : Global Moderation Team (09/06/2016)
- Ajout de [Okorin](https://osu.ppy.sh/users/1623405) : Quality Assurance Team (24/06/2016)
- Transfert de [alacat](https://osu.ppy.sh/users/869782) : osu! Alumni > Quality Assurance Team (24/06/2016)
- Ajout de [JBHyperion](https://osu.ppy.sh/users/4879508) : Quality Assurance Team (24/06/2016)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 01/06/2016 :

- [Doyak](https://osu.ppy.sh/users/2046893)
- [Volta](https://osu.ppy.sh/users/4154071)
- [Nwolf](https://osu.ppy.sh/users/1910766)
- [[Sc4v4ng3r]](https://osu.ppy.sh/users/4838429)
- [Ascendance](https://osu.ppy.sh/users/2931883)
- [Fresh Chicken](https://osu.ppy.sh/users/3984370)
- [[ A v a l o n ]](https://osu.ppy.sh/users/4632359)
- [Nivrad00](https://osu.ppy.sh/users/1984634)
- [Rizqy](https://osu.ppy.sh/users/1411817)

## Juillet

- Transfert de [riffy](https://osu.ppy.sh/users/597957) : Quality Assurance Team > Global Moderation Team (02/07/2016)
- Transfert de [Feerum](https://osu.ppy.sh/users/4815717) : Beatmap Nominators > Quality Assurance Team (26/07/2016)
- Retrait de [XavierJones](https://osu.ppy.sh/users/495733) : Global Moderation Team (27/07/2016)

## Août

- Transfert de [OnosakiHito](https://osu.ppy.sh/users/290128) : Global Moderation Team > Quality Assurance Team (04/08/2016)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 22/08/2016 :

- [Lasse](https://osu.ppy.sh/users/896613)
- [Spaghetti](https://osu.ppy.sh/users/4761930)
- [Stjpa](https://osu.ppy.sh/users/2954693)
- [Len](https://osu.ppy.sh/users/1686145)
- [Ayyri](https://osu.ppy.sh/users/7182318)
- [Kagetsu](https://osu.ppy.sh/users/6203841)
- [Cryptic](https://osu.ppy.sh/users/3728904)
- [Strategas](https://osu.ppy.sh/users/2971837)
- [Electoz](https://osu.ppy.sh/users/6485263)
- [Kencho](https://osu.ppy.sh/users/3178411)
- [Seijiro](https://osu.ppy.sh/users/2581696)
- [pishifat](https://osu.ppy.sh/users/3178418)
- [Xexxar](https://osu.ppy.sh/users/2773526)
- [ezek](https://osu.ppy.sh/users/180241)
- [sahuang](https://osu.ppy.sh/users/5318910)
- [Zero__wind](https://osu.ppy.sh/users/1822830)
- [Pentori](https://osu.ppy.sh/users/7452237)
- [Sieg](https://osu.ppy.sh/users/1404615)

## Octobre

- Transfert de [MMzz](https://osu.ppy.sh/users/128993) : Quality Assurance Team > osu! Alumni (08/10/2016)
- Transfert de [pishifat](https://osu.ppy.sh/users/3178418) : Beatmap Nominators > Quality Assurance Team (18/10/2016)
- Transfert de [KSHR](https://osu.ppy.sh/users/409957) : Global Moderation Team > osu! Alumni (27/10/2016)
- Transfert de [ToGlette](https://osu.ppy.sh/users/1076236) : Global Moderation Team > osu! Alumni (27/10/2016)
- Transfert de [Uni](https://osu.ppy.sh/users/617106) : Global Moderation Team > osu! Alumni (27/10/2016)
- Ajout de [Chaos](https://osu.ppy.sh/users/2628870) : Global Moderation Team (27/10/2016)
- Ajout de [Kyubey](https://osu.ppy.sh/users/2195646) : Global Moderation Team (27/10/2016)
- Ajout de [Spkz](https://osu.ppy.sh/users/2964029) : Global Moderation Team (27/10/2016)
- Ajout de [Pawsu](https://osu.ppy.sh/users/2371454) : Support Team (27/10/2016)
- Ajout de [Zetera](https://osu.ppy.sh/users/587737) : Global Moderation Team (28/10/2016)

## Novembre

- Transfert de [riffy](https://osu.ppy.sh/users/597957) : Global Moderation Team > osu! Alumni (15/11/2016)
- Transfert de [Nishiji](https://osu.ppy.sh/users/167629) : Global Moderation Team > osu! Alumni (15/11/2016)
- Transfert de [-kevincela-](https://osu.ppy.sh/users/266596) : osu! Alumni > Global Moderation Team (15/11/2016)
- Transfert de [Gabe](https://osu.ppy.sh/users/654108) : osu! Alumni > Global Moderation Team (15/11/2016)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 04/11/2016 :

- [Absolute Zero](https://osu.ppy.sh/users/4847256)
- [-Sh1n1-](https://osu.ppy.sh/users/1957638)
- [DixonBlackwing](https://osu.ppy.sh/users/4335785)
- [juankristal](https://osu.ppy.sh/users/443656)
- [SanadaYukimura](https://osu.ppy.sh/users/2633753)
- [Protastic101](https://osu.ppy.sh/users/6712747)
- [Dellvangel](https://osu.ppy.sh/users/5186244)
- [Rivals\_7](https://osu.ppy.sh/users/4610379)
- [Critical\_Star](https://osu.ppy.sh/users/3793196)
- [Chromoxx](https://osu.ppy.sh/users/1881639)
- [snowball112](https://osu.ppy.sh/users/2350722)

```

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2017/fr.md
> +- [Monstrata](https://osu.ppy.sh/users/2706438) - la conduite moins que bonne pendant les périodes étendues (2017-12-19)
```suggestion
# Registre du personnel : 2017

## Janvier

- Transfert de [ToGlette](https://osu.ppy.sh/users/1076236) : osu! Alumni > Global Moderation Team (22/01/2017)
- Transfert de [Atrue](https://osu.ppy.sh/users/1758523) : osu! Alumni > Global Moderation Team (22/01/2017)
- Ajout de [n0ah](https://osu.ppy.sh/users/3086393) : Global Moderation Team (26/01/2017)
- Ajout de [heyronii](https://osu.ppy.sh/users/5642779) : Global Moderation Team (28/01/2017)
- Ajout de [ruexia](https://osu.ppy.sh/users/385069) : Global Moderation Team (29/01/2017)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 20/01/2017 :

- [riffy](https://osu.ppy.sh/users/597957)
- [Battle](https://osu.ppy.sh/users/4037545)
- [F D Flourite](https://osu.ppy.sh/users/2459589)
- [Garden](https://osu.ppy.sh/users/2849992)
- [Nao Tomori](https://osu.ppy.sh/users/5364763)
- [Naxess](https://osu.ppy.sh/users/8129817)

## Février

- Ajout de [Nardoxyribonucleic](https://osu.ppy.sh/users/876419) : Quality Assurance Team (20/02/2017)

## Mars

- Ajout de [S o h](https://osu.ppy.sh/users/2234772) : Global Moderation Team (29/03/2017)
- Transfert de [QHideaki13](https://osu.ppy.sh/users/733998) : Global Moderation Team > osu! Alumni (29/03/2017)

## Avril

- Transfert de [Uni](https://osu.ppy.sh/users/617106) : osu! Alumni > Global Moderation Team (03/04/2017)
- Transfert de [ErunamoJAZZ](https://osu.ppy.sh/users/1869764) : Global Moderation Team > osu! Alumni (03/04/2017)
- Transfert de [DakeDekaane](https://osu.ppy.sh/users/1425253) : Quality Assurance Team > osu! Alumni (27/04/2017)
- Transfert de [Myxo](https://osu.ppy.sh/users/2202645) : Quality Assurance Team > osu! Alumni (27/04/2017)
- Transfert de [Fycho](https://osu.ppy.sh/users/1876867) : Global Moderation Team et Quality Assurance Team > osu! Alumni (27/04/2017)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 25/04/2017 :

- [Arrival](https://osu.ppy.sh/users/1694000)
- [Benny-](https://osu.ppy.sh/users/4023183)
- [Jonawaga](https://osu.ppy.sh/users/3653035)
- [Julie](https://osu.ppy.sh/users/2420987)
- [Kin](https://osu.ppy.sh/users/480689)
- [Skylish](https://osu.ppy.sh/users/2845958)
- [Stefan](https://osu.ppy.sh/users/626907)
- [Surono](https://osu.ppy.sh/users/3611370)
- [thzz](https://osu.ppy.sh/users/1614839)

## Mai

- Ajout de [Cryptic](https://osu.ppy.sh/users/3728904) : Quality Assurance Team (02/05/2017)
- Transfert de [Doyak](https://osu.ppy.sh/users/2046893) : Beatmap Nominators > Quality Assurance Team (03/05/2017)
- Ajout de [WalterToro](https://osu.ppy.sh/users/5281416) : Global Moderation Team (03/05/2017)

## Juin

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 30/06/2017 :

- [-Mo-](https://osu.ppy.sh/users/2202163)
- [Delis](https://osu.ppy.sh/users/1603923)
- [Doormat](https://osu.ppy.sh/users/3230571)
- [Hobbes2](https://osu.ppy.sh/users/8157492)
- [Kurai](https://osu.ppy.sh/users/77089)
- [Mir](https://osu.ppy.sh/users/8688812)
- [Plaudible](https://osu.ppy.sh/users/7149815)
- [squirrelpascals](https://osu.ppy.sh/users/6151332)
- [Voli](https://osu.ppy.sh/users/2522275)

## Août

- Transfert de [alacat](https://osu.ppy.sh/users/869782) : Quality Assurance Team > osu! Alumni (20/08/2017)

## Septembre

- Ajout de [Lassikko](https://osu.ppy.sh/users/7253731) : Global Moderation Team (11/09/2017)
- Transfert de [Pereira006](https://osu.ppy.sh/users/537344) : Global Moderation Team > osu! Alumni (21/09/2017)
- Transfert de [Shockwave](https://osu.ppy.sh/users/251631) : Global Moderation Team > osu! Alumni (21/09/2017)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 21/09/2017 :

- [Asherz007](https://osu.ppy.sh/users/9014047)
- [Gabe](https://osu.ppy.sh/users/654108)
- [frukoyurdakul](https://osu.ppy.sh/users/7612550)
- [Taikocracy](https://osu.ppy.sh/users/6256027)
- [Weber](https://osu.ppy.sh/users/6410432)
- [Litharrale](https://osu.ppy.sh/users/3189995)
- [Electoz](https://osu.ppy.sh/users/6485263)
- [alienflybot](https://osu.ppy.sh/users/636114)
- [neonat](https://osu.ppy.sh/users/1561995)
- [xfraczynho](https://osu.ppy.sh/users/2192669)
- [Chromoxx](https://osu.ppy.sh/users/1881639)

## Octobre

- Transfert de [mancuso_JM_](https://osu.ppy.sh/users/521568) : osu! Alumni > Global Moderation Team (21/09/2017)
- Retrait de [Cryptic](https://osu.ppy.sh/users/3728904) : Quality Assurance Team (21/09/2017)
- Ajout de [Naxess](https://osu.ppy.sh/users/8129817) : Quality Assurance Team (05/10/2017)
- Ajout de [Raiden](https://osu.ppy.sh/users/2239480) : Quality Assurance Team (05/10/2017)
- Retrait de [IamKwaN](https://osu.ppy.sh/users/1856463) : Global Moderation Team (12/10/2017)
- Transfert de [n0ah](https://osu.ppy.sh/users/3086393) : Global Moderation Team > osu! Alumni (12/10/2017)
- Transfert de [Stefan](https://osu.ppy.sh/users/626907) : Global Moderation Team > osu! Alumni (12/10/2017)
- Transfert de [IamKwaN](https://osu.ppy.sh/users/1856463) : Quality Assurance Team > osu! Alumni (14/10/2017)
- Ajout de [Death](https://osu.ppy.sh/users/3242450) : Global Moderation Team et Support Team (20/10/2017)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 24/10/2017 :

- [celerih](https://osu.ppy.sh/users/4696296)
- [Cerulean Veyron](https://osu.ppy.sh/users/1886524)
- [Chewin](https://osu.ppy.sh/users/617323)
- [DeRandom Otaku](https://osu.ppy.sh/users/5156153)
- [Halfslashed](https://osu.ppy.sh/users/4598899)
- [MaridiuS](https://osu.ppy.sh/users/4496961)
- [Kisses](https://osu.ppy.sh/users/4276114)
- [Sinnoh](https://osu.ppy.sh/users/4236057)

## Décembre

- Ajout de [Protastic101](https://osu.ppy.sh/users/6712747) : Quality Assurance Team (11/12/2017)
- Transfert de [OnosakiHito](https://osu.ppy.sh/users/290128) : Quality Assurance Team > osu! Alumni (11/12/2017)
- Transfert de [Seijiro](https://osu.ppy.sh/users/2581696) : Global Moderation Team > osu! Alumni (17/12/2017)
- Transfert de [Loctav](https://osu.ppy.sh/users/71366) : osu! Alumni (17/12/2017)
- Transfert de [n0ah](https://osu.ppy.sh/users/3086393) : osu! Alumni > Global Moderation Team (26/12/2017)
- Ajout de [Edu](https://osu.ppy.sh/users/5618109) : Global Moderation Team (29/12/2017)
- Ajout de [Clobohne](https://osu.ppy.sh/users/499343) : Global Moderation Team (29/12/2017)
- Transfert de [Kurai](https://osu.ppy.sh/users/77089) : Beatmap Nominators > Quality Assurance Team (31/12/2017)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 11/12/2017 :

- [Aloda](https://osu.ppy.sh/users/1190127)
- [Garalulu](https://osu.ppy.sh/users/757783)
- [Hareimu](https://osu.ppy.sh/users/4138746)
- [Kamikaze](https://osu.ppy.sh/users/2124783)
- [Nokashi](https://osu.ppy.sh/users/5431196)
- [Sorcerer](https://osu.ppy.sh/users/1913190)
- [Tofu1222](https://osu.ppy.sh/users/6089608)

### Retrait : Beatmap Nominators

- [Monstrata](https://osu.ppy.sh/users/2706438) - un comportement peu glorieux sur de longues périodes de temps (19/12/2017)

```

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2018/fr.md
> +- Retiré [Backfire](https://osu.ppy.sh/users/263110) de Project Loved Team (2018-12-31)
```suggestion
# Registre du personnel 2018

## Janvier

- Transfert de [Feerum](https://osu.ppy.sh/users/4815717) : Quality Assurance Team > osu! Alumni (02/01/2018)
- Ajout de [Tommay](https://osu.ppy.sh/users/3132818) : Global Moderation Team (05/01/2018)
- Ajout de [stymlice](https://osu.ppy.sh/users/5122436) : Global Moderation Team (05/01/2018)
- Transfert de [Tasha](https://osu.ppy.sh/users/1031958) : Global Moderation Team > osu! Alumni (08/01/2018)
- Transfert de [spboxer3](https://osu.ppy.sh/users/197974) : osu! Alumni > Global Moderation Team (09/01/2018)
- Transfert de [Atrue](https://osu.ppy.sh/users/1758523) : Global Moderation Team > osu! Alumni (18/01/2018)
- Transfert de [Pittigbaasje](https://osu.ppy.sh/users/2167433) : Global Moderation Team > osu! Alumni (27/01/2018)
- Transfert de [Elfin](https://osu.ppy.sh/users/1399551) : Global Moderation Team > osu! Alumni (28/01/2018)
- Transfert de [Fycho](https://osu.ppy.sh/users/1876867) : osu! Alumni > Quality Assurance Team (29/01/2018)
- Transfert de [Myxo](https://osu.ppy.sh/users/2202645) : osu! Alumni > Quality Assurance Team (29/01/2018)

### Retrait : Beatmap Nominators

- [sheela](https://osu.ppy.sh/users/1138027) - démission (13/01/2018)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 29/01/2018 :

- [UndeadCapulet](https://osu.ppy.sh/users/2523533)
- [Noffy](https://osu.ppy.sh/users/1541323)
- [iYiyo](https://osu.ppy.sh/users/3919785)
- [Hailie](https://osu.ppy.sh/users/5226970)
- [Realazy](https://osu.ppy.sh/users/918297)
- [timemon](https://osu.ppy.sh/users/2072005)
- [AyanokoRin](https://osu.ppy.sh/users/5376866)
- [- Frontier -](https://osu.ppy.sh/users/4314710)
- [Sotarks](https://osu.ppy.sh/users/4452992)
- [dsco](https://osu.ppy.sh/users/4330511)
- [Namki](https://osu.ppy.sh/users/5248582)
- [Lanturn](https://osu.ppy.sh/users/1446665)
- [Nevo](https://osu.ppy.sh/users/7451883)
- [Bubblun](https://osu.ppy.sh/users/6191653)
- [mancuso_JM_](https://osu.ppy.sh/users/521568)
- [Wishkey](https://osu.ppy.sh/users/1101704)
- [TheKingHenry](https://osu.ppy.sh/users/5128277)
- [ailv](https://osu.ppy.sh/users/6933054)
- [ezek](https://osu.ppy.sh/users/180241)
- [pinataman](https://osu.ppy.sh/users/1235485)

## Février

- Transfert de [Blocko](https://osu.ppy.sh/users/4075092) : Quality Assurance Team > osu! Alumni (04/02/2018)
- Ajout de [Asherz007](https://osu.ppy.sh/users/9014047) : Quality Assurance Team (04/02/2018)
- Transfert de [Darksonic](https://osu.ppy.sh/users/570042) : osu! Alumni > Global Moderation Team (13/02/2018)
- Transfert de [Uni](https://osu.ppy.sh/users/617106) : Global Moderation Team > osu! Alumni (20/02/2018)
- Transfert de [[ Another ]](https://osu.ppy.sh/users/3416573) : Global Moderation Team > osu! Alumni (20/02/2018)
- Retrait de [Irreversible](https://osu.ppy.sh/users/1287964) : Quality Assurance Team (27/02/2018)

### Retrait : Beatmap Nominators

- [Litharrale](https://osu.ppy.sh/users/3189995) - démission (02/02/2018)
- [ailv](https://osu.ppy.sh/users/6933054) - nomination irresponsable (19/02/2018)
- [Halfsmashed](https://osu.ppy.sh/users/4847256) - démission (21/02/2018)
- [Wafu](https://osu.ppy.sh/users/888955) - démission (25/02/2018)
- [Voli](https://osu.ppy.sh/users/2522275) - démission (28/02/2018)

### Nouveaux Beatmap Nominators

- [Kuron-Kun](https://osu.ppy.sh/users/2697284) (06/02/2018)
- [ailv](https://osu.ppy.sh/users/6933054) (26/02/2018)

## Mars

- Ajout de [Lasse](https://osu.ppy.sh/users/896613) : Quality Assurance Team (01/03/2018)
- Transfert de [Stefan](https://osu.ppy.sh/users/626907) : osu! Alumni > Global Moderation Team (11/03/2018)
- Transfert de [Okoratu](https://osu.ppy.sh/users/1623405) : Quality Assurance Team > osu! Alumni et Beatmap Nominators (17/03/2018)
- Transfert de [shARPII](https://osu.ppy.sh/users/776257) : Global Moderation Team > osu! Alumni (17/03/2018)
- Ajout de [-Mo-](https://osu.ppy.sh/users/2202163) : Quality Assurance Team (22/03/2018)
- Transfert de [Gabe](https://osu.ppy.sh/users/654108) : Beatmap Nominators > Quality Assurance Team (22/03/2018)
- Ajout de [Lanturn](https://osu.ppy.sh/users/1446665) : Quality Assurance Team (22/03/2018)
- Ajout de [Mir](https://osu.ppy.sh/users/8688812) : Quality Assurance Team (22/03/2018)

### Retrait : Beatmap Nominators

- [Naotoshi](https://osu.ppy.sh/users/5364763) - démission (11/03/2018)
- [xfraczynho](https://osu.ppy.sh/users/2192669) - démission (19/03/2018)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 12/03/2018 :

- [Nepuri](https://osu.ppy.sh/users/6637817)
- [-Kazu-](https://osu.ppy.sh/users/920861)
- [Faputa](https://osu.ppy.sh/users/845733)
- [hikikochan](https://osu.ppy.sh/users/6512678)
- [Ascendance](https://osu.ppy.sh/users/2931883)
- [Sanyi](https://osu.ppy.sh/users/7496029)
- [JeirYagtama](https://osu.ppy.sh/users/7483452)
- [Arzenvald](https://osu.ppy.sh/users/3027421)

---

Tous les utilisateurs listés ci-dessous ont été ajoutés le 19/03/2018 :

- [AJamez](https://osu.ppy.sh/users/7890134)
- [error\_exe777](https://osu.ppy.sh/users/7975796)

## Avril

- Transfert de [Zetera](https://osu.ppy.sh/users/587737) : Global Moderation Team > osu! Alumni (06/04/2018)
- Ajout de [Aloda](https://osu.ppy.sh/users/1190127) : Quality Assurance Team (16/04/2018)

### Retrait : Beatmap Nominators

- [Sanyi](https://osu.ppy.sh/users/7496029) - démission (17/04/2018)
- [ezek](https://osu.ppy.sh/users/7496029) - démission (17/04/2018)
- Kisses - restriction du compte (22/04/2018)
- [Hareimu](https://osu.ppy.sh/users/4138746) - démission (24/04/2018)
- Sotarks - restriction du compte (30/04/2018)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 23/04/2018 :

- [Mirash](https://osu.ppy.sh/users/2841009)
- [Kyuukai](https://osu.ppy.sh/users/5337374)
- [Net0](https://osu.ppy.sh/users/5099768)
- [Ultima Fox](https://osu.ppy.sh/users/3198109)
- [Deramok](https://osu.ppy.sh/users/1428455)
- [hypercyte](https://osu.ppy.sh/users/9155377)
- [Smokeman](https://osu.ppy.sh/users/2140676)
- [Trynna](https://osu.ppy.sh/users/2652951)
- [Ryuusei Aika](https://osu.ppy.sh/users/7777875)
- [SnowNiNo\_](https://osu.ppy.sh/users/2506267)
- [kwk](https://osu.ppy.sh/users/365586)
- [Sonnyc](https://osu.ppy.sh/users/11771)
- [Lafayla](https://osu.ppy.sh/users/5312547)
- [bossandy](https://osu.ppy.sh/users/360437)
- [Andrea](https://osu.ppy.sh/users/33599)
- [Sieg](https://osu.ppy.sh/users/1404615)
- [Mordred](https://osu.ppy.sh/users/7265097)
- [Kalibe](https://osu.ppy.sh/users/3376777)
- [Nao Tomori](https://osu.ppy.sh/users/5364763)

## Mai

- Ajout de [Chaoslitz](https://osu.ppy.sh/users/3621552) : Quality Assurance Team (09/05/2018)
- Transfert de [Myxo](https://osu.ppy.sh/users/2202645) : Quality Assurance Team > osu! Alumni (09/05/2018)

### Retrait : Beatmap Nominators

- [Chromoxx](https://osu.ppy.sh/users/1881639) - démission (01/05/2018)
- [Chewin](https://osu.ppy.sh/users/617323) - manque d'activité (14/05/2018)
- [MBomb](https://osu.ppy.sh/users/3071175) - démission (20/05/2018)
- [SnowNiNo_](https://osu.ppy.sh/users/2506267) - manque d'approbation (24/05/2018)
- [Smokeman](https://osu.ppy.sh/users/2140676) - manque d'approbation (24/05/2018)
- [Kyuukai](https://osu.ppy.sh/users/5337374) - manque d'approbation (24/05/2018)
- [juankristal](https://osu.ppy.sh/users/443656) - manque d'activité (30/05/2018)
- [Nwolf](https://osu.ppy.sh/users/1910766) - manque d'activité (30/05/2018)
- [Arrival](https://osu.ppy.sh/users/1694000) - manque d'activité (30/05/2018)
- [Julie](https://osu.ppy.sh/users/2420987) - manque d'activité (30/05/2018)
- [Weber](https://osu.ppy.sh/users/6410432) - manque d'activité (30/05/2018)

## Juin

- Transfert de [Zetera](https://osu.ppy.sh/users/587737) : osu! Alumni > Global Moderation Team (04/06/2018)
- Ajout de [Okoratu](https://osu.ppy.sh/users/1623405) : Global Moderation Team (17/06/2018)
- Transfert de [Kura [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2019/fr.md
> +- Ajouté [Volta](https://osu.ppy.sh/users/4154071) à Probationary Beatmap Nominators (2019-12-28)
```suggestion
# Registre du personnel : 2019

## Janvier

- Ajout de [clayton](https://osu.ppy.sh/users/3666350) : Project Loved Team (26/01/2019)
- Transfert de [mancuso_JM_](https://osu.ppy.sh/users/521568) : Global Moderation Team > osu! Alumni (31/01/2019)

### Retrait : Beatmap Nominators

- [Trynna](https://osu.ppy.sh/users/2652951) - démission (04/01/2019)
- [Sandalphon](https://osu.ppy.sh/users/2633753) - démission (13/01/2019)
- [Natsu](https://osu.ppy.sh/users/1953876) - manque d'activité (22/01/2019)
- [DTM9 Nowa](https://osu.ppy.sh/users/5428909) - manque d'approbation (22/01/2019)
- [Net0](https://osu.ppy.sh/users/5099768) - comportement inapproprié (25/01/2019)
- [iYiyo](https://osu.ppy.sh/users/3919785) - démission (30/01/2019)

## Février

- Ajout de [Shoegazer](https://osu.ppy.sh/users/2520707) : Project Loved Team (13/02/2019)
- Retrait de [Yuii-](https://osu.ppy.sh/users/2935923) : Quality Assurance Team (16/02/2019)

### Retrait : Beatmap Nominators

- [Garden](https://osu.ppy.sh/users/2849992) - démission (03/02/2019)
- [Sonnyc](https://osu.ppy.sh/users/11771) - manque d'approbation (05/02/2019)

### Nouveaux Beatmap Nominators

Tous les utilisateurs listés ci-dessous ont été ajoutés le 16/02/2019 :

- [Nevo](https://osu.ppy.sh/users/7451883)
- [Hanasaka Yui](https://osu.ppy.sh/users/6443117)
- [Sparhten](https://osu.ppy.sh/users/7601720)
- [Hinsvar](https://osu.ppy.sh/users/1249323)
- [_Epreus](https://osu.ppy.sh/users/7342798)
- [Yugu](https://osu.ppy.sh/users/3161834)
- [Testo](https://osu.ppy.sh/users/5200881)
- [Zelq](https://osu.ppy.sh/users/8953955)
- [DTM9 Nowa](https://osu.ppy.sh/users/5428909)
- [NEVlR](https://osu.ppy.sh/users/8339126)
- [thicc bish](https://osu.ppy.sh/users/4696296)
- [Crissa](https://osu.ppy.sh/users/5405836)
- [Agatsu](https://osu.ppy.sh/users/5579871)
- [Bibbity Bill](https://osu.ppy.sh/users/4446810)
- [Cris-](https://osu.ppy.sh/users/6175280)
- [Serizawa Haruki](https://osu.ppy.sh/users/6642617)
- [Nikakis](https://osu.ppy.sh/users/4351739)
- [spoes](https://osu.ppy.sh/users/9505704)
- [Krfawy](https://osu.ppy.sh/users/1478292)
- [- Matha -](https://osu.ppy.sh/users/7354729)
- [Venix](https://osu.ppy.sh/users/5999631)
- [Error-](https://osu.ppy.sh/users/3378391)
- [eiri-](https://osu.ppy.sh/users/3388410)
- [Arf](https://osu.ppy.sh/users/3716999)
- [-GN Junior](https://osu.ppy.sh/users/3901754)
- [Greenshell](https://osu.ppy.sh/users/8693851)
- [Tyistiana](https://osu.ppy.sh/users/1421452)
- [komasy](https://osu.ppy.sh/users/1980256)
- [MBomb](https://osu.ppy.sh/users/3071175)
- [IDu5t](https://osu.ppy.sh/users/6053071)
- [chickenbible](https://osu.ppy.sh/users/2306637)
- [Leniane](https://osu.ppy.sh/users/7138602)
- [K a b i -](https://osu.ppy.sh/users/6209713)
- [KeppSado](https://osu.ppy.sh/users/11085809)
- [Yuii-](https://osu.ppy.sh/users/2935923)

## Mars

- Transfert de [Mir](https://osu.ppy.sh/users/8688812) : osu! Alumni > Quality Assurance Team (23/03/2019)

## Avril

- Transfert de [Fycho](https://osu.ppy.sh/users/1876867) : Quality Assurance Team > Global Moderation Team (10/04/2019)
- Transfert de [Ascendance](https://osu.ppy.sh/users/2931883) : Beatmap Nominators > Quality Assurance Team (10/04/2019)
- Transfert de [Gabe](https://osu.ppy.sh/users/654108) : Quality Assurance Team > Beatmap Nominators (10/04/2019)
- Transfert de [JBHyperion](https://osu.ppy.sh/users/4879508) : Quality Assurance Team > Global Moderation Team et Beatmap Nominators (10/04/2019)
- Transfert de [Kuron-kun](https://osu.ppy.sh/users/2697284) : Quality Assurance Team > Global Moderation Team (10/04/2019)
- Transfert de [p3n](https://osu.ppy.sh/users/123703) : Quality Assurance Team > Global Moderation Team (10/04/2019)
- Transfert de [Raiden](https://osu.ppy.sh/users/2239480) : Quality Assurance Team > Global Moderation Team et Beatmap Nominators (10/04/2019)
- Transfert de [Hobbes2](https://osu.ppy.sh/users/8157492) : Quality Assurance Team > osu! Alumni et Beatmap Nominators (10/04/2019)
- Transfert de [Lanturn](https://osu.ppy.sh/users/1446665) : Quality Assurance Team > osu! Alumni (10/04/2019)
- Transfert de [Protastic101](https://osu.ppy.sh/users/6712747) : Quality Assurance Team > osu! Alumni (10/04/2019)
- Transfert de [Regraz](https://osu.ppy.sh/users/3076909) : Quality Assurance Team > osu! Alumni et Beatmap Nominators (10/04/2019)
- Transfert de [Noffy](https://osu.ppy.sh/users/1541323) : Quality Assurance Team > osu! Alumni et Beatmap Nominators (18/04/2019)
- Retrait de [-Kazu-](https://osu.ppy.sh/users/920861) : Quality Assurance Team (20/04/2019)
- Transfert de [Loctav](https://osu.ppy.sh/users/71366) : osu! Alumni > Global Moderation Team (22/04/2019)
- Ajout de [Zeus-](https://osu.ppy.sh/users/5464437) : Global Moderation Team (22/04/2019)
- Ajout de [- Felix](https://osu.ppy.sh/users/8503985) : Global Moderation Team (22/04/2019)

### Retrait : Beatmap Nominators

- [MaridiuS](https://osu.ppy.sh/users/4496961) - démission (01/04/2019)
- [Namki](https://osu.ppy.sh/users/5248582) - manque de compétence (01/04/2019)
- [alienflybot](https://osu.ppy.sh/users/636114) - démission (12/04/2019)
- [Yales](https://osu.ppy.sh/users/2377881) - démission (16/04/2019)
- [wonjae](https://osu.ppy.sh/users/5032045) - démission (27/04/2019)
- [DMT9 Nowa](https://osu.ppy.sh/users/5428909) - démission (27/04/2019)
- [\_WWWWWW\_WWWWWW\_](https://osu.ppy.sh/users/1981781) - comportement inapproprié (30/04/2019)

## Mai

- **Quality Assurance Team devient Nomination Assessment Team** (06/05/2019)
- Transfert de [Faputa](https://osu.ppy.sh/users/845733) : Beatmap Nominators > Nomination Assessment Team (07/05/2019)
- Transfert de [ghm12](https://osu.ppy.sh/users/2594229) : Global Moderation Team > osu! Alumni (11/05/2019)
- Transfert de [ToGlette](https://osu.ppy.sh/users/1076236) : Global Moderation Team > osu! Alumni (11/05/2019)

### Nouveaux Beatmap Nominators

- [Unpredictable](https://osu.ppy.sh/users/7560872) (11/05/2019)
- [[ A v a l o n ]](https://osu.ppy.sh/users/4632359) (11/05/2019)
- [bite you death](https://osu.ppy.sh/users/6398464) (11/05/2019)
- [Nao Tomori](https://osu.ppy.sh/users/5364763) (11/05/2019)
- [Absolute Zero](https://osu.ppy.sh/users/4847256) (13/05/2019)
- [Dapuluous](https://osu.ppy.sh/users/8140944) (13/05/2019)
- [-Mikan](https://osu.ppy.sh/users/9063995) (15/05/2019)
- [wonjae](https://osu.ppy.sh/users/5032045) (17/05/2019)
- [Kqrth](https://osu.ppy.sh/users/4115718) (22/05/2019)
- [Nuvolina](https://osu.ppy.sh/users/10974170) (22/05/2019)
- [Halfslashed](https://osu.ppy.sh/users/4598899) (22/05/2019)
- [Mun](https://osu.ppy.sh/users/6699165) (29/05/2019)

### Retrait : Beatmap Nominators

- [Serizawa Haruki](https://osu.ppy.sh/users/6642617) - manque de compétence (02/05/2019)
- [chickenbible](https://osu.ppy.sh/users/2306637) - démission (09/05/2019)
- [Arf](https://osu.ppy.sh/users/3716999) - manque d'activité (14/05/2019)
- [-GN Junior](https://osu.ppy.sh/users/3901754) - manque de compétence (18/05/2019)
- [Kaitjuh](https://osu.ppy.sh/users/2225327) - démission (19/05/2019)
- [DoNotMess](https://osu.ppy.sh/users/1596318) - démission (28/05/2019)

## Juin

- Retrait de [clayton](https://osu.ppy.sh/users/3666350) : Project Loved Team (21/06/2019)
- Transfert de [Hinsvar](https://osu.ppy.sh/users/1249323) : Global Moderation Team > osu! Alumni (30/06/2019)

### Nouveaux Beatmap Nominators

- [Dored](https://osu.ppy.sh/users/10284894) (06/06/2019)
- [Peter](https://osu.ppy.sh/users/8623835) (20/06/2019)

### Retrait : Beatmap Nominators

- [Volta](https://osu.ppy.sh/users/4154071) - démission (01/06/2019)
- [Lafayla](https://osu.ppy.sh/users/5312547) - démission (03/06/2019)
- [Hobbes2](https://osu.ppy.sh/users/8157492) - démission (05/06/2019)
- [Electoz](https://osu.ppy.sh/users/6485263) - démission (06/06/2019)
- [Sotarks](https://osu.ppy.sh/users/4452992) - misconduct (11/06/2019)
- [Doormat](https://osu.ppy.sh/users/3230571) - manque d'activité (22/06/2019)
- [Yuii-](https:/ [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2020/fr.md
> +<!-- last update: 2021-01-01 02:00 UTC removed myxo de bn -->
```suggestion
# Registre du personnel : 2020

Les abréviations des groupes d'utilisateurs utilisées dans ce registre sont les suivantes :

- **BN :** [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators)
- **GMT :** [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team)
- **NAT :** [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team)

## Janvier

- 06/01/2020 : Ajout de [yaspo](https://osu.ppy.sh/users/4945926) : **NAT**
- 07/01/2020 : Transfert de [kanpakyin](https://osu.ppy.sh/users/394326) : **osu! Alumni** > **GMT**
- 26/01/2020 : Ajout de [Greaper](https://osu.ppy.sh/users/2369776) : **NAT**

### Beatmap Nominators

#### Ajouts

- 01/01/2020 : Ajout de [\_DUSK\_](https://osu.ppy.sh/users/6092181) : **Probationary BN**
- 06/01/2020 : Ajout de [Vulkin](https://osu.ppy.sh/users/4901066) : **Probationary BN**
- 06/01/2020 : Ajout de [Hoshikuz](https://osu.ppy.sh/users/9892196) : **Probationary BN**
- 07/01/2020 : Ajout de [Lacrima](https://osu.ppy.sh/users/4915649) : **Probationary BN**
- 10/01/2020 : Ajout de [incandescence](https://osu.ppy.sh/users/6256027) : **Probationary BN**
- 10/01/2020 : Ajout de [Voxa](https://osu.ppy.sh/users/9229539) : **Probationary BN**
- 13/01/2020 : Ajout de [celerih](https://osu.ppy.sh/users/4696296) : **Probationary BN**
- 16/01/2020 : Ajout de [Yales](https://osu.ppy.sh/users/2377881) : **Probationary BN**
- 19/01/2020 : Ajout de [SMOKELIND](https://osu.ppy.sh/users/9327302) : **Probationary BN**
- 20/01/2020 : Ajout de [Capu](https://osu.ppy.sh/users/2474015) : **Probationary BN**
- 26/01/2020 : Ajout de [Dapuluous](https://osu.ppy.sh/users/8140944) : **Probationary BN**
- 28/01/2020 : Ajout de [Stefan](https://osu.ppy.sh/users/626907) : **Probationary BN**
- 28/01/2020 : Ajout de [kanpakyin](https://osu.ppy.sh/users/394326) : **Probationary BN**

#### Transferts

- 03/01/2020 : Transfert de [Realazy](https://osu.ppy.sh/users/918297) : **Probationary BN** > **BN**
- 05/01/2020 : Transfert de [Kyousukee](https://osu.ppy.sh/users/8842107) : **Probationary BN** > **BN**
- 05/01/2020 : Transfert de [Kaitjuh](https://osu.ppy.sh/users/2225327) : **Probationary BN** > **BN**
- 05/01/2020 : Transfert de [Smokeman](https://osu.ppy.sh/users/2140676) : **Probationary BN** > **BN**
- 30/01/2020 : Transfert de [Mirash](https://osu.ppy.sh/users/2841009) : **Probationary BN** > **BN**

#### Retraits

- 03/01/2020 : Retrait de [Daletto](https://osu.ppy.sh/users/7592136) : **Probationary BN**
- 05/01/2020 : Retrait de [Nifty](https://osu.ppy.sh/users/4956097) : **Probationary BN**
- 06/01/2020 : Retrait de [yaspo](https://osu.ppy.sh/users/4945926) : **BN**
- 07/01/2020 : Retrait de [Du5t](https://osu.ppy.sh/users/6053071) : **BN**
- 17/01/2020 : Retrait de [Tailsdk](https://osu.ppy.sh/users/6751666) : **BN**
- 18/01/2020 : Retrait de [Asherz007](https://osu.ppy.sh/users/9014047) : **BN**
- 19/01/2020 : Retrait de [qoot8123](https://osu.ppy.sh/users/766371) : **BN**
- 25/01/2020 : Retrait de [Sanyi](https://osu.ppy.sh/users/7496029) : **BN**
- 26/01/2020 : Retrait de [Greaper](https://osu.ppy.sh/users/2369776) : **BN**
- 29/01/2020 : Retrait de [Critical_Star](https://osu.ppy.sh/users/3793196) : **BN**

## Février

### Beatmap Nominators

#### Ajouts

- 02/02/2020 : Ajout de [Gamelan4](https://osu.ppy.sh/users/9856910) : **Probationary BN**
- 02/02/2020 : Ajout de [Stack](https://osu.ppy.sh/users/6122935) : **Probationary BN**
- 09/02/2020 : Ajout de [Dubstek](https://osu.ppy.sh/users/9555243) : **Probationary BN**
- 14/02/2020 : Ajout de [UnluckyCroco](https://osu.ppy.sh/users/9461160) : **Probationary BN**
- 15/02/2020 : Ajout de [Amiichii](https://osu.ppy.sh/users/9228569) : **Probationary BN**
- 27/02/2020 : Ajout de [Affirmation](https://osu.ppy.sh/users/6186628) : **Probationary BN**

#### Transferts

- 02/02/2020 : Transfert de [\_DUSK\_](https://osu.ppy.sh/users/6092181) : **Probationary BN** > **BN**
- 02/02/2020 : Transfert de [frukoyurdakul](https://osu.ppy.sh/users/7612550) : **Probationary BN** > **BN**
- 02/02/2020 : Transfert de [Volta](https://osu.ppy.sh/users/4154071) : **Probationary BN** > **BN**
- 02/02/2020 : Transfert de [Sinnoh](https://osu.ppy.sh/users/4236057) : **Probationary BN** > **BN**
- 04/02/2020 : Transfert de [PokeSky](https://osu.ppy.sh/users/3617111) : **Probationary BN** > **BN**
- 08/02/2020 : Transfert de [Nikakis](https://osu.ppy.sh/users/4351739) : **BN** > **Probationary BN**
- 08/02/2020 : Transfert de [Gero](https://osu.ppy.sh/users/1467715) : **BN** > **Probationary BN**
- 08/02/2020 : Transfert de [Ryuusei Aika](https://osu.ppy.sh/users/7777875) : **BN** > **Probationary BN**
- 08/02/2020 : Transfert de [Sonnyc](https://osu.ppy.sh/users/11771) : **BN** : **Probationary BN**
- 08/02/2020 : Transfert de [wonjae](https://osu.ppy.sh/users/5032045) : **BN** : **Probationary BN**
- 12/02/2020 : Transfert de [celerih](https://osu.ppy.sh/users/4696296) : **Probationary BN** > **BN**
- 14/02/2020 : Transfert de [Vulkin](https://osu.ppy.sh/users/4901066) : **Probationary BN** > **BN**
- 15/02/2020 : Transfert de [Lacrima](https://osu.ppy.sh/users/4915649) : **Probationary BN** > **BN**
- 20/02/2020 : Transfert de [Voxa](https://osu.ppy.sh/users/9229539) : **Probationary BN** > **BN**
- 22/02/2020 : Transfert de [incandescence](https://osu.ppy.sh/users/6256027) : **Probationary BN** > **BN**
- 26/02/2020 : Transfert de [tasuke912](https://osu.ppy.sh/users/2774767) : **Probationary BN** > **BN**
- 28/02/2020 : Transfert de [Capu](https://osu.ppy.sh/users/2474015) : **Probationary BN** > **BN**
- 28/02/2020 : Transfert de [Yales](https://osu.ppy.sh/users/2377881) : **Probationary BN** > **BN**

#### Retraits

- 05/02/2020 : Retrait de [Rocma](https://osu.ppy.sh/users/566276) : **BN**
- 08/02/2020 : Retrait de [ailv](https://osu.ppy.sh/users/6933054) : **BN**
- 10/02/2020 : Retrait de [Kyousukee](https://osu.ppy.sh/users/8842107) : **BN**
- 12/02/2020 : Retrait de [Trynna](https://osu.ppy.sh/users/2652951) : **BN**
- 20/02/2020 : Retrait de [Genjuro](https://osu.ppy.sh/users/3196091) : **BN**
- 20/02/2020 : Retrait de [\_DUSK\_](https://osu.ppy.sh/users/6092181) : **BN**
- 23/02/2020 : Retrait de [MEGAtive](https://osu.ppy.sh/users/3094101) : **BN**
- 24/02/2020 : Retrait de [Mun](https://osu.ppy.sh/users/6699165) : **BN**

## Mars

- 09/03/2020 : Transfert de [ToGlette](https://osu.ppy.sh/users/1076236) : **osu! Alumni** > **GMT**
- 11/03/2020 : Transfert de [Fycho](https://osu.ppy.sh/users/1876867) : **GMT** > **osu! Alumni**
- 11/03/2020 : Transfert de [Laurakko](https://osu.ppy.sh/users/7253731) : **GMT** > **osu! Alumni**
- 16/03/2020 : Transfert de [Ascendance](https://osu.ppy.sh/users/2931883) : **NAT** > **osu! Alumni**
- 20/03/2020 : Ajout de [Tyistiana](https://osu.ppy.sh/users/1421452) : **NAT**

### Beatmap Nominators

#### Ajouts

- 06/03/2020 : Ajout de [Roger](https://osu.ppy.sh/users/1538223) : **Probationary BN**
- 07/03/2020 : Ajout de [Nao Tomori](https://osu.ppy.sh/users/5364763) : **Probationary BN**
- 09/03/2020 : Ajout de [MaridiuS](https://osu.ppy.sh/users/4496961) : **Probationary BN**
- 09/03/2020 : Ajout de [Daletto](https://osu.ppy.sh/users/7592136) : **Probationary BN**
- 17/03/2020 : Ajout de [BaAR_Vendel](https://osu.ppy.sh/users/8679346) : **Probationary BN**
- 22/03/2020 : Ajout de [wafer](https://osu.ppy.sh/users/9416836) : **Probationary BN**

#### Transferts

- 06/03/2020 : Transfert de [Gamelan4](https://osu.ppy.sh/users/9856910) : **Probationary BN** > **BN**
- 06/03/2020 : Transfert de [kanpakyin](https://osu.ppy.sh/users/394326) : **Probationary BN** > **BN**
- 06/03/2020 : Transfert de [Stefan](https://osu.ppy.sh/users/626907) : **Probationary BN** > **BN**
- 09/03/2020 : Transfert de [Stack](https://osu.ppy.sh/users/6122935) : **Probationary BN** > **BN**
- 19/03/2020 : Transfert de [Hoshikuz](https://osu.ppy.sh/users/9892196) : **Probationary BN** > **BN**
- 19/03/2020 : Transfert de [wonjae](https://osu.p [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/2021/fr.md
> +<!-- last update: 2021-07-22 07:00 UTC added leoflt, chillierpear, azer à gmt -->
```suggestion
# Registre du personnel : 2021

Les  abréviations des groupes d'utilisateurs utilisées dans ce registre sont les suivantes :

- **BN :** [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators)
- **GMT :** [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team)
- **NAT :** [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team)

## Janvier

- 31/01/2021 : Transfert de [ztrot](https://osu.ppy.sh/users/6347) : **osu! Alumni** > **GMT**

### Beatmap Nominators

#### Ajouts

- 05/01/2021 : Ajout de [Ulqui](https://osu.ppy.sh/users/1263669) : **Probationary BN**
- 05/01/2021 : Ajout de [Hivie](https://osu.ppy.sh/users/4007649) : **Probationary BN**
- 13/01/2021 : Ajout de [Dako](https://osu.ppy.sh/users/4007649) : **Probationary BN**
- 24/01/2021 : Ajout de [guden](https://osu.ppy.sh/users/11626065) : **Probationary BN**
- 25/01/2021 : Ajout de [rosario wknd](https://osu.ppy.sh/users/6341518) : **Probationary BN**
- 25/01/2021 : Ajout de [Myxo](https://osu.ppy.sh/users/2202645) : **Probationary BN**
- 27/01/2021 : Ajout de [Xahlt](https://osu.ppy.sh/users/13466351) : **Probationary BN**
- 31/01/2021 : Ajout de [deta5859](https://osu.ppy.sh/users/15275662) : **Probationary BN**

#### Transferts

- 10/01/2021 : Transfert de [autofanboy](https://osu.ppy.sh/users/636114) : **BN** > **Probationary BN**
- 15/01/2021 : Transfert de [Cynplytholowazy](https://osu.ppy.sh/users/3901754) : **Probationary BN** > **BN**
- 17/01/2021 : Transfert de [Arzenvald](https://osu.ppy.sh/users/3027421) : **Probationary BN** > **BN**
- 19/01/2021 : Transfert de [Gamelan4](https://osu.ppy.sh/users/9856910) : **Probationary BN** > **BN**
- 19/01/2021 : Transfert de [ikin5050](https://osu.ppy.sh/users/4007649) : **Probationary BN** > **BN**
- 19/01/2021 : Transfert de [PokeSky](https://osu.ppy.sh/users/3617111) : **BN** > **Probationary BN**
- 23/01/2021 : Transfert de [Benita](https://osu.ppy.sh/users/4023183) : **Probationary BN** > **BN**
- 24/01/2021 : Transfert de [UberFazz](https://osu.ppy.sh/users/8646059) : **Probationary BN** > **BN**
- 24/01/2021 : Transfert de [Nana Abe](https://osu.ppy.sh/users/6443117) : **Probationary BN** > **BN**
- 24/01/2021 : Transfert de [Shmiklak](https://osu.ppy.sh/users/5504231) : **Probationary BN** > **BN**
- 26/01/2021 : Transfert de [Eyenine](https://osu.ppy.sh/users/1259391) : **Probationary BN** > **BN**
- 29/01/2021 : Transfert de [Yugu](https://osu.ppy.sh/users/31618347) : **BN** > **Probationary BN**
- 29/01/2021 : Transfert de [Sonnyc](https://osu.ppy.sh/users/11771) : **BN** > **Probationary BN**
- 29/01/2021 : Transfert de [Dored](https://osu.ppy.sh/users/10284894) : **BN** > **Probationary BN**
- 30/01/2021 : Transfert de [Default Guy](https://osu.ppy.sh/users/7058457) : **Probationary BN** > **BN**

#### Retraits

- 07/01/2021 : Retrait de [JierYagtama](https://osu.ppy.sh/users/7483452) : **BN**
- 15/01/2021 : Retrait de [Greenshell](https://osu.ppy.sh/users/8693851) : **BN**
- 19/01/2021 : Retrait de [Rivals_7](https://osu.ppy.sh/users/4610379) : **BN**
- 23/01/2021 : Retrait de [-Joni-](https://osu.ppy.sh/users/9988837) : **Probationary BN**
- 24/01/2021 : Retrait de [Smokeman](https://osu.ppy.sh/users/2140676) : **BN**
- 24/01/2021 : Retrait de [Okoratu](https://osu.ppy.sh/users/1623405) : **BN**
- 27/01/2021 : Retrait de [Voxa](https://osu.ppy.sh/users/9229539) : **BN**

## Février

- 05/02/2021 : Transfert de [Niva](https://osu.ppy.sh/users/197805) : **osu! Alumni** > **GMT**
- 15/02/2021 : Transfert de [Tommay](https://osu.ppy.sh/users/3132818) : **GMT** > **osu! Alumni**
- 15/02/2021 : Transfert de [Kurai](https://osu.ppy.sh/users/77089) : **GMT** > **osu! Alumni**
- 15/02/2021 : Transfert de [Gabe](https://osu.ppy.sh/users/654108) : **GMT** > **osu! Alumni**
- 23/02/2021 : Ajout de [\[ryuu\]](https://osu.ppy.sh/users/5698467) : **GMT**
- 23/02/2021 : Ajout de [mrrrk](https://osu.ppy.sh/users/9936528) : **GMT**
- 23/02/2021 : Ajout de [Nukrid](https://osu.ppy.sh/users/2307484) : **GMT**
- 23/02/2021 : Ajout de [Petal](https://osu.ppy.sh/users/7354729) : **GMT**
- 23/02/2021 : Ajout de [Sies](https://osu.ppy.sh/users/6491991) : **GMT**
- 23/02/2021 : Ajout de [Trigonoculus](https://osu.ppy.sh/users/7627013) : **GMT**
- 23/02/2021 : Ajout de [Venix](https://osu.ppy.sh/users/5999631) : **GMT**
- 23/02/2021 : Ajout de [Civil oath](https://osu.ppy.sh/users/3216107) : **GMT**
- 23/02/2021 : Ajout de [Petit](https://osu.ppy.sh/users/4637369) : **GMT**
- 24/02/2021 : Ajout de [Coldrod](https://osu.ppy.sh/users/9065991) : **GMT**

### Beatmap Nominators

#### Ajouts

- 09/02/2021 : Ajout de [Smoke](https://osu.ppy.sh/users/10726630) : **Probationary BN**
- 10/02/2021 : Ajout de [Yasuho](https://osu.ppy.sh/users/8458835) : **Probationary BN**
- 15/02/2021 : Ajout de [NeKroMan4ik](https://osu.ppy.sh/users/11387664) : **Probationary BN**
- 15/02/2021 : Ajout de [Battle](https://osu.ppy.sh/users/4037545) : **Probationary BN**
- 26/02/2021 : Ajout de [Xinely](https://osu.ppy.sh/users/1521445) : **Probationary BN**

#### Transferts

- 01/02/2021 : Transfert de [Zer0-](https://osu.ppy.sh/users/4260033) : **Probationary BN** > **BN**
- 01/02/2021 : Transfert de [Morrighan](https://osu.ppy.sh/users/12042090) : **Probationary BN** > **BN**
- 17/02/2021 : Transfert de [autofanboy](https://osu.ppy.sh/users/636114) : **Probationary BN** > **BN**
- 21/02/2021 : Transfert de [Hivie](https://osu.ppy.sh/users/14102976) : **Probationary BN** > **BN**
- 21/02/2021 : Transfert de [Ulqui](https://osu.ppy.sh/users/1263669) : **Probationary BN** > **BN**
- 21/02/2021 : Transfert de [Luscent](https://osu.ppy.sh/users/2688581) : **BN** > **Probationary BN**

#### Retraits

- 13/02/2021 : Retrait de [Rocma](https://osu.ppy.sh/users/566276) : **BN**
- 16/02/2021 : Retrait de [Nao Tomori](https://osu.ppy.sh/users/5364763) : **BN**

## Mars

- 01/03/2021 : Ajout de [ThePooN](https://osu.ppy.sh/users/718454) : **Developers**
- 01/03/2021 : Transfert de [Lasse](https://osu.ppy.sh/users/896613) : **NAT** > **osu! Alumni**
- 06/03/2021 : Ajout de [Zelq](https://osu.ppy.sh/users/8953955) : **NAT**
- 07/03/2021 : Ajout de [Agatsu](https://osu.ppy.sh/users/5579871) : **NAT**
- 2021-03-19 : Ajout de [Nozhomi](https://osu.ppy.sh/users/2716981) : **GMT**

### Beatmap Nominators

#### Ajouts

- 01/03/2021 : Ajout de [Mir](https://osu.ppy.sh/users/8688812) : **Probationary BN**
- 01/03/2021 : Ajout de [Lasse](https://osu.ppy.sh/users/896613) : **BN**
- 12/03/2021 : Ajout de [Paran](https://osu.ppy.sh/users/13340203) : **Probationary BN**
- 14/03/2021 : Ajout de [Horiiizon](https://osu.ppy.sh/users/8071438) : **Probationary BN**
- 14/03/2021 : Ajout de [gevbiivi5](https://osu.ppy.sh/users/7140680) : **Probationary BN**
- 14/03/2021 : Ajout de [AJT](https://osu.ppy.sh/users/3181083) : **Probationary BN**
- 14/03/2021 : Ajout de [VINXIS](https://osu.ppy.sh/users/4323406) : **Probationary BN**
- 18/03/2021 : Ajout de [NyalettOwO x3](https://osu.ppy.sh/users/7592136) : **Probationary BN**
- 18/03/2021 : Ajout de [wonjae](https://osu.ppy.sh/users/5032045) : **Probationary BN**
- 23/03/2021 : Ajout de [-Aku](https://osu.ppy.sh/users/12315824) : **Probationary BN**
- 28/03/2021 : Ajout de [Komirin](https://osu.ppy.sh/users/4725379) : **Probationary BN**
- 28/03/2021 : Ajout de [AHHHHHHHHHHHHHH](https://osu.ppy.sh/users/8249608) : **Probationary BN**
- 30/03/2021 : Ajout de [Sylas](https://osu.ppy.sh/users/3906405) : **Probationary BN**
- 30/03/2021 : Ajout de [Kudosu](https://osu.ppy.sh/users/11038155) : **Probationary BN**

#### Transferts

- 05/03/2021 : Transfert de [Myxo](https://osu.ppy.sh/users/2202645) : **Probationary BN** > **BN**
- 07/03/2021 : Transfert de [PokeSky](https://osu.ppy.sh/users/3617111) : **Probationary BN** > **BN**
- 14/03/2021 : Transfert de [guden](https://osu.ppy.sh/users/11626065) : **Probationary BN** > **BN**
- 15/03/2021 : Transfert de [Dored](https://osu.ppy.sh/users/10284894) : **Probati [...]

2021-08-16 18:38 UTC, DoryanR commented on wiki/Staff_Log/fr.md
> +-->
```suggestion
---
tags:
  - promotion
  - retirement
  - retrait
---

# Registre du personnel

Les promotions et les retrait du personnel ont été enregistrés pour les rendre plus facile à retrouver pour la communauté.

- [2007](2007)
- [2008](2008)
- [2009](2009)
- [2010](2010)
- [2011](2011)
- [2012](2012)
- [2013](2013)
- [2014](2014)
- [2015](2015)
- [2016](2016)
- [2017](2017)
- [2018](2018)
- [2019](2019)
- [2020](2020)
- [2021](2021)

```

2021-08-16 20:38 UTC, reeceyang commented
@DoryanR 
> Almost total rewriting of all the articles; I save the 3163 suggestions that would have been necessary, if I had not gone through the editor, from where the review on the whole article.
> This rewriting was mandatory, because the article was not French, and did not correspond to our standards.

Hi, I'm so sorry that you had to go through and rewrite everything :( 
French isn't my first language and clearly my French skills aren't good enough to do translations. I'll refrain from contributing French translations in the future. 
Again, my apologies for creating additional unnecessary work for you. Is there anything I can do to make up for this?

2021-08-17 04:36 UTC, DoryanR commented
Don't worry, there's no problem.
Knowing that your native language is not French, I would advise you to make contributions in the language in which you feel most comfortable.
Nevertheless, I thank you for your contribution, my review may allow you to learn more about our language.
If you want to do something for me, you can approve the suggestions, so that we can move forward on this PR.
Once again, don't worry about the time spent to redo everything, this is the purpose of the review, and it is our job to improve the articles so that they are of good quality.

2021-08-17 16:49 UTC, DoryanR requested changes
After that it will be good

2021-08-17 16:49 UTC, DoryanR commented on wiki/Staff_Log/2014/fr.md
> +### Nouveaux ajouts à la BAT
```suggestion
### Nouveaux ajouts : BAT
```

2021-08-17 16:49 UTC, DoryanR commented on wiki/Staff_Log/2014/fr.md
> +### Nouveaux ajouts à la BAT
```suggestion
### Nouveaux ajouts : BAT
```

2021-08-17 16:49 UTC, DoryanR commented on wiki/Staff_Log/2014/fr.md
> +### Nouveaux ajouts à la BAT
```suggestion
### Nouveaux ajouts : BAT
```

2021-08-17 16:49 UTC, DoryanR commented on wiki/Staff_Log/2014/fr.md
> +Tous les utilisateurs listés ci-dessous ont été ajoutés le 2014-11-22 :
```suggestion
Tous les utilisateurs listés ci-dessous ont été ajoutés le 22/11/2014 :
```

2021-08-17 16:49 UTC, DoryanR commented on wiki/Staff_Log/2014/fr.md
> +### Nouveaux ajouts à la BAT
```suggestion
### Nouveaux ajouts : BAT
```

2021-08-17 16:49 UTC, DoryanR commented on wiki/Staff_Log/2015/fr.md
> +### Nouveaux ajouts à la BAT
```suggestion
### Nouveaux ajouts : BAT
```

2021-08-17 16:49 UTC, DoryanR commented on wiki/Staff_Log/2021/fr.md
> +- 2021-03-19 : Ajout de [Nozhomi](https://osu.ppy.sh/users/2716981) : **GMT**
```suggestion
- 19/03/2021 : Ajout de [Nozhomi](https://osu.ppy.sh/users/2716981) : **GMT**
```

2021-08-18 04:30 UTC, DoryanR approved these changes

2021-08-19 16:53 UTC, DoryanR requested changes
Adjustments to match with #5979

2021-08-19 16:53 UTC, DoryanR commented on wiki/Staff_Log/2021/fr.md
> +
```suggestion
- 23/07/2021 : Ajout de [Pachiru](https://osu.ppy.sh/users/2850983) : **Project Loved Team**
- 23/07/2021 : Transfert de [Feerum](https://osu.ppy.sh/users/4815717) : **NAT** > **osu! Alumni**
- 23/07/2021 : Ajout de [Davvy](https://osu.ppy.sh/users/10047413) : **GMT**
- 23/07/2021 : Ajout de [Maot](https://osu.ppy.sh/users/3914271) : **GMT**
- 28/07/2021 : Ajout de [Shoegazer](https://osu.ppy.sh/users/2520707) : **GMT**
- 29/07/2021 : Ajout de[Firika](https://osu.ppy.sh/users/9590557) : **GMT**
- 29/07/2021 : Ajout de [Kite](https://osu.ppy.sh/users/134572) : **GMT**
- 30/07/2021 : Ajout de [mangomizer](https://osu.ppy.sh/users/1893718) : **GMT**

```

2021-08-19 16:53 UTC, DoryanR commented on wiki/Staff_Log/2021/fr.md
> +
```suggestion
- 31/07/2021 : Ajout de [Idealism](https://osu.ppy.sh/users/3869519) : **Probationary BN**

```

2021-08-19 16:53 UTC, DoryanR commented on wiki/Staff_Log/2021/fr.md
> +
```suggestion
- 23/07/2021 : Transfert de [pimp](https://osu.ppy.sh/users/328615) : **BN** > **Probationary BN**
- 26/07/2021 : Transfert de [Icekalt](https://osu.ppy.sh/users/5410645) : **Probationary BN** > **BN**

```

2021-08-19 16:53 UTC, DoryanR commented on wiki/Staff_Log/2021/fr.md
> +
```suggestion
- 31/07/2021 : Retrait de [D3kuu](https://osu.ppy.sh/users/7807444) : **Probationary BN**

## Août

- 02/08/2021 : Retrait de [Nepuri](https://osu.ppy.sh/users/6637817) : **osu! Alumni**
- 16/08/2021 : Retrait de [Pope Gadget](https://osu.ppy.sh/users/2288341) : **Project Loved Team**

### Beatmap Nominators

#### Ajouts

- 05/08/2021 : Ajout de [Riana](https://osu.ppy.sh/users/1997633) : **Probationary BN**
- 06/08/2021 : Ajout de [Kyle Y](https://osu.ppy.sh/users/3565813) : **Probationary BN**
- 07/08/2021 : Ajout de [GIGACHAD](https://osu.ppy.sh/users/11081858) : **Probationary BN**
- 08/08/2021 : Ajout de [mnyui](https://osu.ppy.sh/users/14261540) : **Probationary BN**
- 11/08/2021 : Ajout de [Lacrima](https://osu.ppy.sh/users/4915649) : **Probationary BN**
- 11/08/2021 : Ajout de [FuJu](https://osu.ppy.sh/users/10773882) : **Probationary BN**
- 13/08/2021 : Ajout de [RandomeLoL](https://osu.ppy.sh/users/7080063) : **Probationary BN**
- 13/08/2021 : Ajout de [DarkistDeci](https://osu.ppy.sh/users/13360768) : **Probationary BN**

#### Transferts

- 03/08/2021 : Transfert de [zerokt](https://osu.ppy.sh/users/13776127) : **Probationary BN** > **BN**
- 03/08/2021 : Transfert de [Phob](https://osu.ppy.sh/users/6069462) : **Probationary BN** > **BN**
- 09/08/2021 : Transfert de [Logic Agent](https://osu.ppy.sh/users/6069462) : **Probationary BN** > **BN**
- 13/08/2021 : Transfert de [Murumoo](https://osu.ppy.sh/users/8001433) : **BN** > **Probationary BN**
- 13/08/2021 : Transfert de [yenmaster](https://osu.ppy.sh/users/12565402) : **Probationary BN** > **BN**
- 13/08/2021 : Transfert de [Chatie](https://osu.ppy.sh/users/6524765) : **Probationary BN** > **BN**

#### Retraits

- 03/08/2021 : Retrait de [My Angel RangE](https://osu.ppy.sh/users/6336713) : **BN**
- 06/08/2021 : Retrait de [Aakki](https://osu.ppy.sh/users/11077540) : **Probationary BN**
- 06/08/2021 : Retrait de [Gabdu09](https://osu.ppy.sh/users/8852605) : **Probationary BN**
- 13/08/2021 : Retrait de [Lirai](https://osu.ppy.sh/users/3734394) : **BN**
- 17/08/2021 : Retrait de [Default Guy](https://osu.ppy.sh/users/7058457) : **Probationary BN**
- 17/08/2021 : Retrait de [CallieCube](https://osu.ppy.sh/users/7535045) : **Probationary BN**

```

2021-08-20 16:13 UTC, DoryanR approved these changes

2021-08-20 17:55 UTC, TPGPL approved these changes

2021-08-20 17:55 UTC, merged