Update 'Game_mode'; Translate 'Beat', 'Beatmap/Authentic', 'Beatmap/Background', 'Beatmap/Beatmap_host', 'Beatmap/Break', 'Game_mode/osu!', 'Game_mode/osu!taiko', 'Game_mode/osu!mania', 'Game_mode/osu!catch'
ppy/osu-wiki pull request #5964
Opened 2021-08-15 13:10 UTC by Ceotom

TODO:
- Game_mode/osu!
- Game_mode/osu!catch
- Game_mode/osu!mania
- Game_mode/osu!taiko

2021-08-18 18:57 UTC, TicClick requested changes
так, я посмотрел `Game mode` и понял, что там какая-то дичь творится (и заодно тут же угадал автора всех этих бессмертных строк). твой перевод так себе, но статью нужно в принципе переделывать, поэтому я не буду ревьюить перевод, а потом перепишу всё в оригинале и здесь.

оставлять `Game mode` в этом пулл-реквесте или нет — твоё дело, оно всё равно будет переписано и переделано.

а вот по остальным файлам пройдись, пожалуйста

2021-08-19 05:46 UTC, Ceotom commented on wiki/Beatmap/Background/ru.md
> +Фоны отображаются на карточках в списке карт, на [экране выбора песни](/wiki/Interface#song-selection-screen) и во время игры.
Только если "карточки в списке песен" или "в списке песен рядом с названием"

2021-08-19 09:32 UTC, TicClick requested changes

2021-08-19 09:32 UTC, TicClick commented on wiki/Beatmap/Background/ru.md
> +Фоны отображаются на карточках в списке карт, на [экране выбора песни](/wiki/Interface#song-selection-screen) и во время игры.
тут речь, похоже, про поиск по сайту, но пусть пока будет первый вариант, `карточки в списке песен`

2021-08-19 09:32 UTC, TicClick commented on wiki/Beat/ru.md
> +**Доля** – это время, на которое можно разделить песню в зависимости от её [BPM](/wiki/Beatmapping/Beats_per_minute). В [картах](/wiki/Beatmap) с правильно подобранным тактом каждая доля будет соотве
хм, а что если так выкрутиться?
```suggestion
**Доля** (англ. *beat*) – это короткий отрезок времени, на которые можно поделить песню в зависимости от её [BPM](/wiki/Beatmapping/Beats_per_minute). В правильно затаймленных [картах](/wiki/Beatmap) каждая доля соответствует ноте из песни, а целая доля — это расстояние между двумя белыми линиями на [временной шкале](/wiki/Beatmap_Editor/Timelines).
```

2021-08-19 09:49 UTC, TicClick approved these changes

2021-08-19 09:49 UTC, merged