[EN] Complete MCNC wiki pages
ppy/osu-wiki pull request #5969
Opened 2021-08-16 16:08 UTC by xz1z1z1z1z

2021-08-16 18:48 UTC, Walavouchey requested changes
please note that the old [tournament template](https://github.com/ppy/osu-wiki/blob/master/wiki/Tournaments/Template/en.md) isn't consistent with current articles and is soon to be [replaced](https://github.com/ppy/osu-wiki/pull/5747)

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +The **osu!mania 4K Chinese National Cup 2021** (***MCNC 2021***) was a country-based osu!mania tournament hosted by the \[Crz\]Team. It was the third installment of the osu!mania 4K Chinese National
british spelling

```suggestion
The **osu!mania 4K Chinese National Cup 2021** (***MCNC 2021***) was a country-based osu!mania tournament hosted by the \[Crz\]Team. It was the third instalment of the osu!mania 4K Chinese National Cup.
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +- **[Statistics sheet](https://docs.google.com/spreadsheets/d/1xgxKNKoJNEQz_zlPUf-4fyxeBDpuhfkgqxXyOxaIkpU)**
```suggestion
- [Livestream](https://live.bilibili.com/2996250 "Bilibili")
- [Discord Server](https://discord.gg/uBHK5vq "Discord")
- [Challonge bracket](https://challonge.com/zh_CN/MCNC2021 "Challonge")
- **[Statistics sheet](https://docs.google.com/spreadsheets/d/1xgxKNKoJNEQz_zlPUf-4fyxeBDpuhfkgqxXyOxaIkpU "Google Sheets")**
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +**[Download the mappack here! (255 MB)](https://drive.google.com/file/d/1Fb0s3GTJzZ0v2LgCJLhtjphwpXXPYpkl/view?usp=sharing)**
```suggestion
**[Download the mappack here! (255 MB)](https://drive.google.com/file/d/1Fb0s3GTJzZ0v2LgCJLhtjphwpXXPYpkl/view?usp=sharing "Google Drive")**
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +| Group Stage week 2 | 2021-04-19/2021-04-25 |
```suggestion
| Group stage week 1 | 2021-04-12/2021-04-18 |
| Group stage week 2 | 2021-04-19/2021-04-25 |
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +**[Download the mappack here! (160 MB)](https://drive.google.com/file/d/1tj0Q6dEO1YGqvsXZQ5huJkZAckPSh4fS/view?usp=sharing)**
```suggestion
**[Download the mappack here! (160 MB)](https://drive.google.com/file/d/1tj0Q6dEO1YGqvsXZQ5huJkZAckPSh4fS/view?usp=sharing "Google Drive")**
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +**[Download the mappack here! (112 MB)](https://drive.google.com/file/d/12P98_uqoBN5qaqL6-4DSFtxyFwcrjtVo/view?usp=sharing)**
```suggestion
**[Download the mappack here! (112 MB)](https://drive.google.com/file/d/12P98_uqoBN5qaqL6-4DSFtxyFwcrjtVo/view?usp=sharing "Google Drive")**
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +**[Download the mappack here! (123 MB)](https://drive.google.com/file/d/1VDpFnjGwhyzIp0SvqUu6XEizSJ9FfGiD/view?usp=sharing)**
```suggestion
**[Download the mappack here! (123 MB)](https://drive.google.com/file/d/1VDpFnjGwhyzIp0SvqUu6XEizSJ9FfGiD/view?usp=sharing "Google Drive")**
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +**[Download the mappack here! (83 MB)](https://drive.google.com/file/d/13I8C26KAv3xVXBov1fRHuWR80Hskzi6T/view?usp=sharing)**
```suggestion
**[Download the mappack here! (83 MB)](https://drive.google.com/file/d/13I8C26KAv3xVXBov1fRHuWR80Hskzi6T/view?usp=sharing "Google Drive")**
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +**[Download the mappack here! (18 MB)](https://drive.google.com/file/d/1KYzdeiVoa11U0FYwjzqu-EKnDiA8DFr4/view?usp=sharing)**
```suggestion
**[Download the mappack here! (18 MB)](https://drive.google.com/file/d/1KYzdeiVoa11U0FYwjzqu-EKnDiA8DFr4/view?usp=sharing "Google Drive")**
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | CNY 800, 1 month of osu!supporter tag |
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | CNY 2,500, unique profile badge, 4 months of osu!supporter |
| ![Silver crown](/wiki/shared/crown-silver.png "2nd place") | CNY 1,500, 2 months of osu!supporter |
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | CNY 800, 1 month of osu!supporter |
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2020/en.md
> +![](img/172-80.png "MCNC 2020 badge")
also rename the file to `badge.png`

```suggestion
![](img/172-80.png "MCNC 2020 winner badge")
```

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +![MCNC 2021 winner badge](img/172-80.png)
rename file to `badge.png`

2021-08-16 18:48 UTC, Walavouchey commented on wiki/Tournaments/MCNC/2021/en.md
> +[flag_MO]: /wiki/shared/flag/MO.gif "Macau"
sorted

```suggestion
[flag_CN]: /wiki/shared/flag/CN.gif "China"
[flag_HK]: /wiki/shared/flag/HK.gif "Hong Kong"
[flag_MO]: /wiki/shared/flag/MO.gif "Macau"
[flag_MX]: /wiki/shared/flag/MX.gif "Mexico"
[flag_TW]: /wiki/shared/flag/TW.gif "Taiwan"
[flag_US]: /wiki/shared/flag/US.gif "United States"
```

2021-08-16 19:20 UTC, Bazzadwarf commented
The tournaments page table also needs updating to add the podiums for 2020 and 2021.

```
| Name | Start | End | ![Gold crown][GCrown] | ![Silver crown][SCrown] | ![Bronze crown][BCrown] |
| :-- | :-- | :-- | :-- | :-- | :-- |
| [osu!mania 4K Chinese National Cup 2019](MCNC/2019) | 2019-06-19 | 2019-08-12 | ![][flag_HK] [\[Crz\]Murasame](https://osu.ppy.sh/users/11563203) | ![][flag_TW] [\[Crz\]FolAH1217](https://osu.ppy.sh/users/6232458) | ![][flag_CN] [\[Crz\]Satori](https://osu.ppy.sh/users/7082178) |
| [osu!mania 4K Chinese National Cup 2020](MCNC/2020) | 2020-04-27 | 2020-06-28 | ![][flag_CN] [WLYMinato](https://osu.ppy.sh/users/12703319) | ![][flag_CN] [Kakuko](https://osu.ppy.sh/users/10413362) | ![][flag_CN] [\[Crz\]I-Night](https://osu.ppy.sh/users/8790619) |
| [osu!mania 4K Chinese National Cup 2021](MCNC/2021) | 2021-04-05 | 2021-06-06 | ![][flag_CN] [\[Crz\]sunnyxxy](https://osu.ppy.sh/users/10333739) | ![][flag_CN] [\[Crz\]Caicium](https://osu.ppy.sh/users/10702235) | ![][flag_CN] [yuwenhao1](https://osu.ppy.sh/users/14318312) |
``

2021-08-21 00:29 UTC, TPGPL requested changes

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +### Groups
```suggestion
## Groups
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +![MCNC 2021 bracket](img/bracket.jpg)
```suggestion
![](img/bracket.jpg "MCNC 2021 bracket")

## Podium

![](img/podium.jpg "MCNC 2021 podium")
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +  - [Camellia - Flamewall (Cut ver.) (\[Crz\]xz1z1z) \[AlexDunk's FINAL REBELLION (Cut Edit) \[1.05x Rate\]](https://osu.ppy.sh/beatmapsets/1462775#mania/3019256)
```suggestion
  - [Camellia - Flamewall (Cut ver.) (\[Crz\]xz1z1z) \[AlexDunk's FINAL REBELLION (Cut Edit) \[1.05x Rate\]\]](https://osu.ppy.sh/beatmapsets/1462775#mania/3019256)
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +  - [Camellia - NIGHTMARE CITY (\[Crz\]xz1z1z) \[NIGHTMARE\]](https://osu.ppy.sh/beatmapsets/1486342#mania/3047677)
```suggestion
  - **[Camellia - NIGHTMARE CITY (\[Crz\]xz1z1z) \[NIGHTMARE\]](https://osu.ppy.sh/beatmapsets/1486342#mania/3047677)**
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +  - [Camellia vs. lapix - Solvicious (Mameyodoufu Remix) (Dubstek) \[Cybernetic Extinction\]](https://osu.ppy.sh/beatmapsets/933845#mania/1949498)
```suggestion
  - **[Camellia vs. lapix - Solvicious (Mameyodoufu Remix) (Dubstek) \[Cybernetic Extinction\]](https://osu.ppy.sh/beatmapsets/933845#mania/1949498)**
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +  - [Hino Isuka - #be_fortunate (HowToPlayLN) \[#be_edited\]](https://osu.ppy.sh/beatmapsets/1099229#mania/2349916)
```suggestion
  - [Hino Isuka - #be\_fortunate (HowToPlayLN) \[#be\_edited\]](https://osu.ppy.sh/beatmapsets/1099229#mania/2349916)
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +  - [rejection - Signal (feat. Such) (Mameyodoufu Remix) (\[OSC\]Amagai) \[ Keen Perception \[Revised Again\]\]](https://osu.ppy.sh/beatmapsets/1404380#mania/2993544)
```suggestion
  - **[rejection - Signal (feat. Such) (Mameyodoufu Remix) (\[OSC\]Amagai) \[ Keen Perception \[Revised Again\]\]](https://osu.ppy.sh/beatmapsets/1404380#mania/2993544)**
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +  - [Kanone vs Yooh - Cold Inflaction (Extended Mix) (\[Crz\]xz1z1z) \[Cold But With You\]](https://osu.ppy.sh/beatmapsets/1274517#mania/2648242)
```suggestion
  - **[Kanone vs Yooh - Cold Inflaction (Extended Mix) (\[Crz\]xz1z1z) \[Cold But With You\]](https://osu.ppy.sh/beatmapsets/1274517#mania/2648242)**
```

2021-08-21 00:29 UTC, TPGPL commented on wiki/Tournaments/MCNC/2021/en.md
> +  - [Camellia - Dance with Silence (\[Crz\]xz1z1z) \[Silence\]](https://osu.ppy.sh/beatmapsets/1405229#mania/2934744)
```suggestion
  - **[Camellia - Dance with Silence (\[Crz\]xz1z1z) \[Silence\]](https://osu.ppy.sh/beatmapsets/1405229#mania/2934744)**
```

2021-08-21 01:03 UTC, TPGPL approved these changes

2021-08-21 01:03 UTC, merged