Update ja.md
ppy/osu-wiki pull request #5977
Opened 2021-08-18 18:39 UTC by mangomizer

Update JP Taiko RC to match EN, translation courtesy of TKS and KSHR!

2021-08-18 20:10 UTC, TPGPL requested changes

2021-08-18 20:10 UTC, TPGPL commented on wiki/Ranking_Criteria/osu!taiko/ja.md
> +難易度別のルール、ガイドラインはそれぞれの難易度ごとに適用されるもので、すべてのTaiko譜面全体に適用されるものではありません。リズムに関するルール、ガイドラインは「4/4拍子、BPM180程度の譜面」を基準に適用されますが、楽曲が極端に遅い、速い場合にはRanking CriteriaのScaling BPMにあるように、許容範囲が一部異なる場合があります。
missing a link to RC/Scaling_BPM

2021-08-18 20:25 UTC, mangomizer commented on wiki/Ranking_Criteria/osu!taiko/ja.md
> +これらのルールやガイドラインはRanking Criteriaのフォーラムで議論され決定されたものです。もし新しいルールやガイドラインが提案、合意に至った場合は本ページの内容も適宜更新されます。
Added

2021-08-18 20:26 UTC, mangomizer commented on wiki/Ranking_Criteria/osu!taiko/ja.md
> +難易度別のルール、ガイドラインはそれぞれの難易度ごとに適用されるもので、すべてのTaiko譜面全体に適用されるものではありません。リズムに関するルール、ガイドラインは「4/4拍子、BPM180程度の譜面」を基準に適用されますが、楽曲が極端に遅い、速い場合にはRanking CriteriaのScaling BPMにあるように、許容範囲が一部異なる場合があります。
Added

2021-08-18 20:26 UTC, mangomizer commented on wiki/Ranking_Criteria/osu!taiko/ja.md
> +osu!taiko Ranking Criteria(osu!taiko譜面のランク基準)はTaiko譜面を作成する際に従わなければならないルール、ガイドラインです。Taiko譜面をRankedさせるためにはこれらのルールに従う必要があります。いかなる場合でもルールに従わなければなりませんが、ガイドラインについては例外的な状況下において無視することが出来ます。ただし、その場合は何故ガイドラインを
I'll keep it unchanged (it's pretty unambiguous) + I don't want to question the TL work done by others.

2021-08-19 17:38 UTC, TPGPL approved these changes

2021-08-19 17:40 UTC, merged