[FR] Update `Main Page`
ppy/osu-wiki pull request #5983
Opened 2021-08-19 16:30 UTC by DoryanR

Proposal to update the French translation of the wiki page `Main Page`.

2021-08-24 16:26 UTC, Ganondorf-1 requested changes

2021-08-24 16:26 UTC, Ganondorf-1 commented on wiki/Main_Page/fr.md
> +Toutes les beatmaps d'osu! sont créés par l'imagination débordante de sa dynamique communauté. Vous avez toujours voulu partager votre musique préférée avec d'autres, mais n'avez jamais su comment fa
```suggestion
Toutes les beatmaps d'osu! sont créées par l'imagination débordante de sa dynamique communauté. Vous avez toujours voulu partager votre musique préférée avec d'autres, mais n'avez jamais su comment faire ? Familiarisez-vous avec l'éditeur intégré et les possibilités qu'il vous offre.
```

2021-08-24 16:26 UTC, Ganondorf-1 commented on wiki/Main_Page/fr.md
> +Le classement est le processus qui consiste à obtenir un classement pour uen beatmap, ce qui la rend plus populaire et plus reconnu. Découvrez ce qu'il faut faire pour emprunter cette voie et comment
```suggestion
Le classement est le processus qui consiste à obtenir un classement pour une beatmap, ce qui la rend plus populaire et plus reconnue. Découvrez ce qu'il faut faire pour emprunter cette voie et comment augmenter vos chances de réussite grâce aux reviews de votre beatmap, ainsi que les procédures de contrôle de qualité et le processus de classement.
```

2021-08-24 19:54 UTC, DoryanR commented on wiki/Main_Page/fr.md
> +Composants : [AiMod](/wiki/Beatmap_Editor/AiMod) • [Beat Snap Divisor](/wiki/Beatmap_Editor/Beat_Snap_Divisor) • [Distance snap](/wiki/Beatmap_Editor/Distance_Snap) • [Menu](/wiki/Beatmap_Editor/Menu
```suggestion
Composants : [AiMod](/wiki/Beatmap_Editor/AiMod) • [Beat Snap Divisor](/wiki/Beatmap_Editor/Beat_Snap_Divisor) • [Distance snap](/wiki/Beatmap_Editor/Distance_Snap) • [Menu](/wiki/Beatmap_Editor/Menu) • [SB load](/wiki/Beatmap_Editor/SB_Load) • [Timelines](/wiki/Beatmap_Editor/Timelines)
```

2021-08-31 12:20 UTC, Ganondorf-1 commented on wiki/Main_Page/fr.md
> +Lisez les procédures et règlements qui assurent la sécurité d'osu! et de sa communauté, depuis les licences musicales et les directives relatives aux médias jusqu'aux règles du tchat et des forums.
```suggestion
Lisez les procédures et règlements qui assurent la sécurité d'osu! et de sa communauté, des licences musicales et directives relatives aux médias jusqu'aux règles du tchat et des forums.
```

2021-09-03 09:38 UTC, Ganondorf-1 approved these changes

2021-09-03 14:37 UTC, TicClick approved these changes

2021-09-03 14:37 UTC, merged