[FR] Update `Contests`
ppy/osu-wiki pull request #5994
Opened 2021-08-21 09:42 UTC by DoryanR

Proposal to update the French translation of the wiki page `Contests`.

2021-08-21 10:02 UTC, Imakuri requested changes
Some corrections concerning the grammar.

2021-08-21 10:02 UTC, Imakuri commented on wiki/Contests/fr.md
> +[flag_BY]: /wiki/shared/flag/BY.gif "Bélarus"
```suggestion
[flag_BY]: /wiki/shared/flag/BY.gif "Biélorussie"
```

2021-08-21 10:10 UTC, DoryanR commented on wiki/Contests/fr.md
> +La **Newspaper Cup** est un concours de mapping similaire à la Pending Cup, mais qui met davantage l'accent sur les mappeurs débutants. Comme pour la Pending Cup, le concours est également organisé c
@Imakuri pour ici c'est pareil que pour [cette review](https://github.com/ppy/osu-wiki/pull/5994/files#r693333106) ?

2021-08-21 13:03 UTC, Imakuri commented on wiki/Contests/fr.md
> +La **Newspaper Cup** est un concours de mapping similaire à la Pending Cup, mais qui met davantage l'accent sur les mappeurs débutants. Comme pour la Pending Cup, le concours est également organisé c
Oui je pense que mettre "sinophone" serait plus censé en effet, c'est valable pour là aussi

2021-08-21 14:34 UTC, DoryanR commented on wiki/Contests/fr.md
> +La **Newspaper Cup** est un concours de mapping similaire à la Pending Cup, mais qui met davantage l'accent sur les mappeurs débutants. Comme pour la Pending Cup, le concours est également organisé c
```suggestion
La **Newspaper Cup** est un concours de mapping similaire à la Pending Cup, mais qui met davantage l'accent sur les mappeurs débutants. Comme pour la Pending Cup, le concours est également organisé chaque année par des membres éminents de la communauté sinophone de mapping et est passé d'un concours particulièrement destiné aux membres de la communauté sinophone à un concours d'envergure mondiale.
```

2021-08-24 16:45 UTC, Ganondorf-1 requested changes

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +Cette section est dédiée aux concours organisés par la communauté d'osu!
```suggestion
Cette section est dédiée aux concours organisés par la communauté d'osu!.
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +Le **Monthly Beatmapping Contest**, dans son concept initial, était un concours de mapping où les mappeurs participants s'affrontaient pour créer la plus remarquable beatmap avec un [niveau de diffic
```suggestion
Le **Monthly Beatmapping Contest**, dans son concept initial, était un concours de mapping où les mappeurs participants s'affrontaient pour créer la plus remarquable beatmap avec un [niveau de difficulté](/wiki/Beatmap/Difficulty#difficulty-levels) approprié à partir de Easy ou Normal en un mois.
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +Après une longue interruption, le Monthly Beatmapping Contest  a été relancé en janvier 2020 avec un tout nouveau calendrier, de nouvelles règles, une nouvelle procédure de vote et un nouveau système
```suggestion
Après une longue interruption, le Monthly Beatmapping Contest a été relancé en janvier 2020 avec un tout nouveau calendrier, de nouvelles règles, une nouvelle procédure de vote et un nouveau système de récompense. De nombreux aspects du concours ont été radicalement modifiés afin de rendre le concours plus attrayant et plus intéressant, dont voici quelques exemples :
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +Le **Community Mapping Contest** est un concours de mapping où les mappeurs participants sont libres de soumettre leur entrée pour n'importe quelle difficulté dans n'importe quel mode de jeu qu'ils d
```suggestion
Le **Community Mapping Contest** est un concours de mapping où les mappeurs participants sont libres de soumettre leur entrée pour n'importe quelle difficulté dans n'importe quel mode de jeu, après quoi toutes les entrées gagnantes, toutes difficultés et tous modes de jeu confondus, seront fusionnées en une seule beatmap.
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +| Numéro du concours | Musique | Mode de jeu | ![Couronne en or](/wiki/shared/crown-gold.png "Première place") | ![Couronne d'argent](/wiki/shared/crown-silver.png "Seconde place") | ![Couronne de br
```suggestion
| Numéro du concours | Musique | Mode de jeu | ![Couronne en or](/wiki/shared/crown-gold.png "Première place") | ![Couronne d'argent](/wiki/shared/crown-silver.png "Seconde place") | ![Couronne de bronze](/wiki/shared/crown-bronze.png "Troisième place") | Résultats |
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +À son lancement, le concours a été nommé "Best of", car le principe initial et les attentes du concours étaient d'encourager les membres de la communauté à voter pour ce qu'ils considéraient comme "t
```suggestion
À son lancement, le concours a été nommé "Best of", car le principe initial et les attentes du concours étaient d'encourager les membres de la communauté à voter pour ce qu'ils considéraient comme "the best beatmaps of the year" ; cependant, comme le nombre de joueurs a continué à croître au fil du temps, le concours se transformait inévitablement de plus en plus en un concours de popularité chaque année, ce qui a incité le concours à être relancé comme "Community Choice" en 2017.
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +| Numéro du concours | Musique remixée | ![Couronne en or][GCrown] | ![Couronne d'argent][SCrown] | ![Couronne de bronze][BCrown] | Results |
```suggestion
| Numéro du concours | Musique remixée | ![Couronne en or][GCrown] | ![Couronne d'argent][SCrown] | ![Couronne de bronze][BCrown] | Résultats |
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +The **Skinning Contest** is a skinning contest where artistic creators from all across the community compete to create the best skin in a limited time.
```suggestion
Le **Skinning Contest** est un concours de skinning dans lequel les créateurs artistiques de toute la communauté s'affrontent pour créer le meilleur skin en un temps limité. 
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +La **Pending Cup** est un concours de mapping organisé chaque année par des membres éminents de la communauté sinophone de mapping. musique et/ou catégories dans lesquelles les mappeurs de toute la c
```suggestion
La **Pending Cup** est un concours de mapping organisé chaque année par des membres éminents de la communauté sinophone de mapping. Chaque année, le concours présente jusqu'à trois musiques et/ou catégories dans lesquelles les mappeurs de toute la communauté sont libres de concourir et de soumettre leurs entrées.
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +² La catégorie  "Vocal" offre aux mappeurs le choix entre deux chansons différentes à mapper : nonoc - memento et DUSTCELL - DERO.
```suggestion
² La catégorie "Vocal" offre aux mappeurs le choix entre deux chansons différentes à mapper : nonoc - memento et DUSTCELL - DERO.
```

2021-08-24 16:45 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +| Numéro du concours | Musique | Mode de jeu | ![Couronne en or][GCrown] (Easy) | ![Couronne en or][GCrown] (Normal) | ![Couronne en or][GCrown] (Hard) | ![Couronne en or][GCrown] (Insane) | ![Couron
```suggestion
| Numéro du concours | Musique | Mode de jeu | ![Couronne en or][GCrown] (Easy) | ![Couronne en or][GCrown] (Normal) | ![Couronne en or][GCrown] (Hard) | ![Couronne en or][GCrown] (Insane) | ![Couronne en or][GCrown] (Extra) | Résultats |
```

2021-09-03 11:08 UTC, Ganondorf-1 requested changes

2021-09-03 11:08 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +Le *osu! Beatmap Blueprints Contest* est un concours unique organisé pour commémorer le lancement de [Beatmap Blueprints](https://osu.ppy.sh/store/products/9) dans le [osu!store](https://osu.ppy.sh/s
```suggestion
Le *osu! Beatmap Blueprints Contest* est un concours unique organisé pour commémorer le lancement de [Beatmap Blueprints](https://osu.ppy.sh/store/products/9) dans l'[osu!store](https://osu.ppy.sh/store/listing). Dans ce concours, les utilisateurs participants se sont affrontés pour créer le meilleur plan d'une beatmap sur n'importe quel support visuel en utilisant toutes les ressources fournies dans le pack de marchandises Beatmap Blueprints.
```

2021-09-03 11:08 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +**osu!idol** est un concours de chant où les participants de toute la communauté s'affrontent pour créer la meilleure reprise de musique (en solo ou avec un partenaire) à travers plusieurs étapes de
```suggestion
L'**osu!idol** est un concours de chant dans lequel les participants de toute la communauté s'affrontent pour créer la meilleure reprise de musique (en solo ou avec un partenaire) à travers plusieurs étapes de jugement et de vote communautaire. Le concours porte le nom de la franchise [Idols](https://fr.wikipedia.org/wiki/Idol_(franchise) "Wikipédia") et s'inspire principalement de divers concours de chant télévisés.
```

2021-09-03 11:08 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +Le **osu! Beatmapping World Championship** est un concours de mapping par équipe où les équipes participantes, composées de mappeurs d'un même pays, d'une même région, voire d'un même continent (dans
```suggestion
Le **osu! Beatmapping World Championship** est un concours de mapping par équipe dans lequel les équipes participantes, composées de mappeurs d'un même pays, d'une même région, voire d'un même continent (dans une certaine mesure), s'affrontent sur plusieurs musiques et étapes de mapping. Le concours est connu pour n'utiliser que des musiques disponibles dans la bibliothèque [Featured Artist](/wiki/Featured_Artists) pendant son déroulement.
```

2021-09-03 17:05 UTC, TPGPL requested changes

2021-09-03 17:05 UTC, TPGPL commented on wiki/Contests/fr.md
> +Le **Monthly Beatmapping Contest**, dans son concept initial, était un concours de mapping où les mappeurs participants s'affrontaient pour créer la beatmap la plus remarquable avec plusieurs [niveau
```suggestion
Le **Monthly Beatmapping Contest**, dans son concept initial, était un concours de mapping où les mappeurs participants s'affrontaient pour créer la beatmap la plus remarquable avec plusieurs [niveaux de difficulté](/wiki/Beatmap/Difficulty#niveaux-de-difficulté) en commençant à partir de Easy ou Normal en un mois.
```

2021-09-03 17:05 UTC, TPGPL commented on wiki/Contests/fr.md
> +L'**osu! Mapping Olympiad** est un concours de mapping qui se tient comme un successeur spirituel des anciens (avant 2020) Monthly Beatmapping Contests. Dans ce concours, les mappeurs participants so
```suggestion
L'**osu! Mapping Olympiad** est un concours de mapping qui se tient comme un successeur spirituel des anciens (avant 2020) Monthly Beatmapping Contests. Dans ce concours, les mappeurs participants sont chargés de créer soit une beatmap avec plusieurs [niveaux de difficulté](/wiki/Beatmap/Difficulty#niveaux-de-difficulté) en commençant à partir de Easy ou Normal, soit un certain nombre de difficultés pour n'importe quelle musique donnée dans chaque itération correspondante.
```

2021-09-03 17:05 UTC, TPGPL commented on wiki/Contests/fr.md
> +Le **Mapping With Rewards** est un concours de mapping dans lequel les mappeurs participants s'affrontent pour créer la meilleure beatmap (avec plusieurs [niveaux de difficulté](/wiki/Beatmap/Difficu
```suggestion
Le **Mapping With Rewards** est un concours de mapping dans lequel les mappeurs participants s'affrontent pour créer la meilleure beatmap (avec plusieurs [niveaux de difficulté](/wiki/Beatmap/Difficulty#niveaux-de-difficulté) en commençant à partir de Easy ou Normal) pour n'importe laquelle des musiques données dans chaque itération correspondante, sans délai strict.
```

2021-09-03 17:11 UTC, merged