[FR] Add `Contests/KCC/1`, `KCC`, `Aspire` and `A Labour of Love`, Update `Contests/FBC`
ppy/osu-wiki pull request #5996
Opened 2021-08-21 11:17 UTC by DoryanR

Translation of the following wiki pages:

- `Contests/A_Labour_of_Love_Contest`
- `Contests/Aspire`
- `Contests/KCC/1`
- `Contests/KCC`

Proposal to update the French translation of the wiki page `Contests/FBC`.

2021-08-23 20:15 UTC, Imakuri requested changes
Suggestions concerning the grammar and some points of the French language problems etc.

2021-08-23 20:15 UTC, Imakuri commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +| Nom de l'équipe | Remixeur(s) | Beatmapper(s) | Créateur(s) de storyboard/vidéo | Entrée |
```suggestion
| Nom de l'équipe | Remixeur(s) | Beatmapper(s) | Créateur(s) de storyboard/vidéo | Participation |
```

2021-08-23 20:15 UTC, Imakuri commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +| Nom de l'équipe | Remixeur(s) | Beatmapper(s) | Créateur(s) de storyboard/vidéo | Entrée |
J'ai vu il y a quelques jours que "entries" était beaucoup plus parlant avec la traduction "participation", je suggère donc ici de le changer, mais libre à toi. J'ai également traduit "entries" par "participation" sur mes traductions

2021-08-23 20:15 UTC, Imakuri commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +Si une équipe gagne dans plusieurs des catégories ci-dessus, elle sera récompensée par un badge de profil reflétant toutes les catégories pertinentes.
```suggestion
Si une équipe gagne dans plusieurs des catégories citées ci-dessus, elle sera récompensée par un badge de profil reflétant toutes les catégories pertinentes.
```

2021-08-23 20:15 UTC, Imakuri commented on wiki/Contests/FBC/fr.md
> +La **French Beatmapping Contest** (***FBC***) est un tournoi de mapping uniquement accessible aux personnes francophones. Dans chaque édition, les mappeurs doivent réaliser une difficulté de niveau I
```suggestion
Le **French Beatmapping Contest** (***FBC***) est un tournoi de mapping uniquement accessible aux personnes francophones. Dans chaque édition, les mappeurs doivent réaliser une difficulté de niveau Insane ou plus.
```

2021-08-23 20:15 UTC, Imakuri commented on wiki/Contests/FBC/fr.md
> +La **French Beatmapping Contest** (***FBC***) est un tournoi de mapping uniquement accessible aux personnes francophones. Dans chaque édition, les mappeurs doivent réaliser une difficulté de niveau I
Mettre "la" n'est pas logique, c'est UN concours (contest traduit en français = un concours), et même quand je l'organisais on le mettait au masculin.

2021-08-23 20:15 UTC, Imakuri commented on wiki/Contests/KCC/1/fr.md
> +Le **Korean Charting Contest 2021** (***KCC2021***) est un concours de mapping osu!mania pour les utilisateurs de ![][flag_KR] Corée du Sud. Il s'agit de la première édition du concours de mapping co
```suggestion
Le **Korean Charting Contest 2021** (***KCC2021***) est un concours de mapping osu!mania pour les utilisateurs venant de ![][flag_KR] Corée du Sud. Il s'agit de la première édition du concours de mapping coréen.
```

2021-08-23 20:15 UTC, Imakuri commented on wiki/Contests/KCC/1/fr.md
> +- Seuls les Coréens peuvent participer à ce concours. Si votre drapeau de profil n'indique pas que vous êtes en ![][flag_KR] Corée du Sud pour des raisons telles que la résidence à l'étranger, vous p
```suggestion
- Seuls les coréens peuvent participer à ce concours. Si votre drapeau de profil n'indique pas que vous êtes en ![][flag_KR] Corée du Sud pour des raisons telles que la résidence à l'étranger, vous pouvez quand même participer si vous êtes en mesure de vérifier que vous êtes coréen.
```

2021-08-24 06:32 UTC, DoryanR commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +Un concours à plusieurs niveaux lancé en novembre 2020 pour célébrer la beatmap [**Kuba Oms - My Love**](https://osu.ppy.sh/beatmapsets/163112).
L'article anglais n'est pas comme ça, donc j'hésite à faire la modif

2021-08-24 16:48 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +Un concours à plusieurs niveaux lancé en novembre 2020 pour célébrer la beatmap [**Kuba Oms - My Love**](https://osu.ppy.sh/beatmapsets/163112).
Je pense que tant qu'on garde la même information c'est bon, et je trouve qu'effectivement ça rendrait mieux comme ça

2021-09-03 10:37 UTC, Ganondorf-1 requested changes

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +- **Le nom et les membres de l'équipe doivent être confirmés par [ce formulaire](https://docs.google.com/forms/d/e/1FAIpQLScjtVsUWIArvf--pKA0RLiCdXuO1_wO2Va2ICjenEcz9ZqI5Q/viewform).** Si votre pays
```suggestion
- **Le nom et les membres de l'équipe doivent être confirmés via [ce formulaire](https://docs.google.com/forms/d/e/1FAIpQLScjtVsUWIArvf--pKA0RLiCdXuO1_wO2Va2ICjenEcz9ZqI5Q/viewform).** Si votre pays ne prend pas en charge les formulaires Google, [envoyez un message à pishifat](https://osu.ppy.sh/community/chat?sendto=3178418). Les équipes sont limitées à 5 membres.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +- **Les soumissions ne doivent pas être qualifiées avant la fin du vote communautaire.**
```suggestion
- **Les beatmaps ne doivent pas être dans la catégorie Qualifiée avant la fin du vote communautaire.**
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +### Panel des musiciens
```suggestion
### Panel de musiciens
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +### Panel de mapping
```suggestion
### Panel de mappeurs
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/Aspire/fr.md
> +**Aspire** est un [concours](/wiki/Contests) de [beatmapping](/wiki/Beatmapping)  où les mappeurs sont encouragés à ignorer complètement les [critères de classement](/wiki/Ranking_Criteria) et à expl
```suggestion
**Aspire** est un [concours](/wiki/Contests) de [beatmapping](/wiki/Beatmapping) dans lequel les mappeurs sont encouragés à ignorer complètement les [critères de classement](/wiki/Ranking_Criteria) et à explorer des mécanismes de jeu qui ne sont pas habituellement utilisés.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
> +Les trois premiers mappeurs d'un tournoi recevront chacun un titre de osu!supporter d'une durée qui peut varier en fonction des éditions. Cependant, le vainqueur de chaque édition recevra un badge pe
```suggestion
Les trois premiers mappeurs d'un tournoi recevront chacun un tag osu!supporter d'une durée qui peut varier en fonction des éditions. Cependant, le vainqueur de chaque édition recevra un badge personnalisé qui s'affichera sur son profil osu!.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  Depuis l'édition 2017, les musiques choisies ont une durée inférieure à 3 minutes et les difficultés en dessous du niveau Insane sont mappées par les organisateurs des tournois ou bien par des membre
```suggestion
Depuis l'édition 2017, les musiques choisies ont une durée inférieure à 3 minutes et les difficultés en dessous du niveau Insane sont mappées par les organisateurs des tournois ou par des membres de la communauté de mapping francophone.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
> +L'édition 2015 était la première édition à avoir réuni les 4 modes de jeu : osu!, osu!taiko, osu!catch, osu!mania. Malheureusement, en mode osu!catch et osu!mania, il n'y avait pas assez de participa
```suggestion
L'édition 2015 était la première édition à avoir réuni les 4 modes de jeu : osu!, osu!taiko, osu!catch, osu!mania. Malheureusement, dans les modes osu!catch et osu!mania, il n'y avait pas assez de participants pour récompenser les vainqueurs d'un badge.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +Le **Korean Charting Contest 2021** (***KCC2021***) est un concours de mapping osu!mania pour les utilisateurs venant de ![][flag_KR] Corée du Sud. Il s'agit de la première édition du concours de map
```suggestion
Le **Korean Charting Contest 2021** (***KCC2021***) est un concours de mapping osu!mania pour les utilisateurs venant de ![][flag_KR] Corée du Sud. Il s'agit de la première édition du Korean Charting Contest.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +| Phase d'inscription, vote par musique | 01/02/2021/07/02/2021 |
```suggestion
| Phase d'inscription, vote de musique | 01/02/2021 - 07/02/2021 |
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +| Phase de soumission | 08/02/2021/07/03/2021 |
```suggestion
| Phase de soumission | 08/02/2021 - 07/03/2021 |
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +| Phase de jugement | 08/03/2021/21/03/2021 |
```suggestion
| Phase de jugement | 08/03/2021 - 21/03/2021 |
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Seuls les coréens peuvent participer à ce concours. Si votre drapeau de profil n'indique pas que vous êtes en ![][flag_KR] Corée du Sud pour des raisons telles que la résidence à l'étranger, vous p
```suggestion
- Seuls les personnes coréennes peuvent participer à ce concours. Si votre drapeau de profil n'indique pas que vous êtes en ![][flag_KR] Corée du Sud pour des raisons telles que la résidence à l'étranger, vous pouvez quand même participer si vous êtes en mesure de prouver que vous êtes Coréen.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Vous devez choisir une musique que vous souhaitez mapper lors de votre inscription (une musique pour Instrumentale et une pour Vocal). Vous pouvez mapper une de ces deux musiques après la fin du vo
```suggestion
- Vous devez choisir une musique que vous souhaitez mapper lors de votre inscription (une musique pour la catégorie Instrumentale et une pour la catégorie Vocal). Vous pouvez mapper une de ces deux musiques après la fin du vote.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Le client d'osu! doit être capable de charger et de lire votre soumission.
```suggestion
- Le client d'osu! doit être capable de charger et de lire votre beatmap.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- La soumission doit être au format `.osz`.
```suggestion
- La beatmap doit être au format `.osz`.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Le titre, l'artiste, le MP3, la source, les balises et le fond ne doivent PAS être modifiés. Cependant, le point de prévisualisation peut être personnalisé.
```suggestion
- Le titre, l'artiste, le fichier MP3, la source, les tags et le fond ne doivent PAS être modifiés. Cependant, le point de prévisualisation peut être personnalisé.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- La soumission doit être de 4K ~ 9K.
```suggestion
- Le nombre de keys de la beatmap doit être entre 4K et 9K.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Le mod Auto doit être en mesure d'effectuer un full combo (score de 1 000 000) de votre soumission.
```suggestion
- Le mod Auto doit être en mesure d'effectuer un full combo (score de 1 000 000) sur votre beatmap.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- La soumission doit être terminée par le concurrent seul. Aucune collaboration n'est autorisée.
```suggestion
- La beatmap doit être terminée par le concurrent seul. Aucune collaboration n'est autorisée.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Les soumissions ne doivent pas être téléchargées sur le site d'osu! par le biais du Beatmap Submission System (BSS). Toutes les soumissions au concours sont anonymes pendant les phases de jugement
```suggestion
- Les beatmaps ne doivent pas être publiées sur le site d'osu! par le biais du Beatmap Submission System (BSS). Toutes les soumissions au concours doivent être anonymes pendant les phases de jugement afin d'éviter toute partialité.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Une seule difficulté de la beatmap est autorisée. Si plusieurs difficultés sont soumises, celle qui a le plus grand nombre d'étoiles sera acceptée.
```suggestion
- Une seule difficulté de la beatmap est autorisée. Si plusieurs difficultés sont soumises, celle qui a le plus grand nombre d'étoiles sera celle acceptée.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Seules les difficultés suivantes sont autorisées : Insane ou supérieure. Veuillez consulter les règles spécifiques aux difficultés dans les [critères de classement](/wiki/Ranking_Criteria).
```suggestion
- Seules les difficultés Insane ou plus sont autorisées. Veuillez consulter les règles spécifiques aux difficultés dans les [critères de classement](/wiki/Ranking_Criteria).
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Si vous soumettez plusieurs maps, la dernière sera votre dernière entrée.
```suggestion
- Si vous soumettez plusieurs maps, la dernière sera celle prise en compte.
```

2021-09-03 10:37 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- **Expertise (25 pts) :** La façon dont la soumission démontre des techniques concernant la structure, la représentation de la musique, le flox, les hitsounds, etc.
```suggestion
- **Expertise (25 pts) :** La façon dont la soumission démontre des techniques concernant la structure, la représentation de la musique, le flow, les hitsounds, etc.
```

2021-09-03 17:43 UTC, Ganondorf-1 requested changes
Should be good to go if these changes are made

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +    - **Gagnant :**  6 mois d'osu!supporter + badge de profil *Community Pick*.
```suggestion
    - **Gagnant :** 6 mois d'osu!supporter + badge de profil *Community Pick*.
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +    - **Gagnant :**  6 mois d'osu!supporter + badge de profil *Musicians' Pick*
```suggestion
    - **Gagnant :** 6 mois d'osu!supporter + badge de profil *Musicians' Pick*
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/A_Labour_of_Love_Contest/fr.md
> +    - **Gagnant :**  6 mois d'osu!supporter + badge de profil *Mappers' Pick*
```suggestion
    - **Gagnant :** 6 mois d'osu!supporter + badge de profil *Mappers' Pick*
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
> +L'édition 2015 était la première édition à avoir réuni les 4 modes de jeu : osu!, osu!taiko, osu!catch, osu!mania. Malheureusement, dans les modes osu!catch et osu!mania, il n'y avait pas assez de pa
```suggestion
L'édition 2015 était la première édition à avoir réuni les 4 modes de jeu : osu!, osu!taiko, osu!catch, osu!mania. Malheureusement, dans les modes osu!catch et osu!mania, il n'y avait pas suffisamment de participants pour récompenser les vainqueurs d'un badge.
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
> +Cette édition était la première édition qui utilise une musique de moins de 3 minutes. De plus, elle était la première à permettre au mapset vainqueur (hébergé par le vainqueur du tournoi) de conteni
```suggestion
Cette édition était la première édition à utiliser une musique de moins de 3 minutes. De plus, elle était la première à permettre au mapset vainqueur (hébergé par le vainqueur du tournoi) de contenir les difficultés des trois premiers mappeurs.
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
> +Cette édition était la première à proposer une musique d'un Featured Artist dans ce tournoi. De plus, c'était la première à voir deux joueurs être ex-aequo dans le classement.
```suggestion
Cette édition était la première à proposer une musique d'un Featured Artist dans ce tournoi. De plus, c'était la première à voir deux participants ex-aequo dans le classement.
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  | Place | Joueurs |
```suggestion
| Place | Mappeurs |
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  | Place | Joueurs |
```suggestion
| Place | Mappeurs |
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  | Place | Joueurs |
```suggestion
| Place | Mappeurs |
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  | Place | Joueurs |
```suggestion
| Place | Mappeurs |
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  | Place | Joueurs |
```suggestion
| Place | Mappeurs |
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  | Place | Joueurs |
```suggestion
| Place | Mappeurs |
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/FBC/fr.md
>  | Place | Joueurs |
```suggestion
| Place | Mappeurs |
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Seuls les personnes coréennes peuvent participer à ce concours. Si votre drapeau de profil n'indique pas que vous êtes en ![][flag_KR] Corée du Sud pour des raisons telles que la résidence à l'étra
```suggestion
- Seules les personnes coréennes peuvent participer à ce concours. Si votre drapeau de profil n'indique pas que vous êtes en ![][flag_KR] Corée du Sud pour des raisons telles que la résidence à l'étranger, vous pouvez quand même participer si vous êtes en mesure de prouver que vous êtes Coréen.
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Les vidéos, skins et storyboards ne sont PAS autorisés. Cependant, les sons des storyboards peuvent être modifiés.
```suggestion
- Les vidéos, skins et storyboards ne sont PAS autorisés. Cependant, les hitsounds des storyboards peuvent être modifiés.
```

2021-09-03 17:43 UTC, Ganondorf-1 commented on wiki/Contests/KCC/1/fr.md
> +- Une seule difficulté de la beatmap est autorisée. Si plusieurs difficultés sont soumises, celle qui a le plus grand nombre d'étoiles sera celle acceptée.
```suggestion
- Une seule difficulté est autorisée. Si plusieurs difficultés sont soumises, celle qui a le plus grand nombre d'étoiles sera celle acceptée.
```

2021-09-03 22:12 UTC, TicClick approved these changes

2021-09-03 22:12 UTC, merged