[RU] Add `Help Centre/Client`
ppy/osu-wiki pull request #6000
Opened 2021-08-22 00:21 UTC by TicClick

also testing the new identifiers

2021-08-23 19:14 UTC, GoodbyeShin reviewed
general feedback, suggestions

2021-08-23 20:50 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +**Чаще всего помогает сброс на настройки по умолчанию.**
да, задумался на полдороги

2021-08-23 20:50 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +Помимо этого, стоит проверить, нет ли на каком-то из устройств, подключённых к компьютеру, заевших или сломанных клавиш.
спасибо

2021-08-23 20:50 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +Когда все файлы формата `.osz`, бывшие в архиве, окажутся в директории `Songs`, нажмите `F5` на экране выбора песни, чтобы osu! их подгрузила.
I never

2021-08-23 20:50 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +Насовсем. Их не вернуть.
да, мне так больше нравится

2021-08-23 20:50 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +**С серверами osu! всё почти всегда в порядке. Чтобы убедиться, что в этот раз проблема именно в них, [проверьте статус серверов osu!](https://status.ppy.sh) и загляните в твиттер к [@osustatus](http
да тут какая-то хуйня, я переделал почти все заголовки с оригинальных вопросов на утверждения и вот тут наконец за это поплатился

2021-08-23 20:50 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +Разрыв картинки на мониторе — это противный, но безвредный эффект, вызванный тем, что у osu! и у вашего монитора — разные частоты развёртки.
я не пользуюсь автопереводом. здесь пропущено сказуемое, а значит, [тире нужно](http://new.gramota.ru/biblio/readingroom/rules/158-tire)

2021-08-24 18:44 UTC, UristMcKobold requested changes

2021-08-24 18:44 UTC, UristMcKobold commented on wiki/Help_Centre/Client/ru.md
> +**У серверов osu! редко бывают проблемы. Об инцидентах можно узнать на [странице состояния серверов](https://status.ppy.sh) и в твиттере [@osustatus](https://twitter.com/osustatus).**
```suggestion
**У серверов osu! иногда бывают проблемы. Об инцидентах можно узнать на [странице состояния серверов](https://status.ppy.sh) и в твиттере [@osustatus](https://twitter.com/osustatus).**
```
«Редко бывают проблемы» звучит немного не по смыслу оригинала, как будто «проблема может иметься, но у серверов они бывают редко, поэтому ищите причины в другом месте», а в оригинале смысл скорее в том, что «да, случаются проблемы время от времени».

2021-08-24 18:44 UTC, UristMcKobold commented on wiki/Help_Centre/Client/ru.md
> +Если сервера недоступны, не закрывайте osu!. Оставьте игру открытой, и она в течение примерно часа будет пытаться опубликовать ваш рекорд.
```suggestion
Если сервера недоступны, не закрывайте osu!. Оставьте игру открытой, и она в течение примерно часа будет пытаться отправить ваш рекорд на сервер.
```
Выбор слова смущает, до этого под этим явлением (как и в заголовке) было слово «отправка».

2021-08-24 18:44 UTC, UristMcKobold commented on wiki/Help_Centre/Client/ru.md
> +Помимо ограничения FPS, osu! можно перевести в оконный режим, или выбрать в настройках разрешение экрана без рамки. В этом случае за вертикальную синхронизацию будет отвечать операционная система.
```suggestion
Помимо ограничения FPS, osu! можно перевести в оконный режим или выбрать в настройках разрешение экрана без рамки. В этом случае за вертикальную синхронизацию будет отвечать операционная система.
```
Лишняя запятая какая-то. можно перевести/можно выбрать

2021-08-24 18:44 UTC, UristMcKobold commented on wiki/Help_Centre/Client/ru.md
> +К несчастью, все эти действия *чуть-чуть* увеличивают задержку ввода. Для большинства игроков это будет некритичным.
```suggestion
К несчастью, все эти действия *чуть-чуть* увеличивают задержку ввода. Для большинства игроков это будет некритично.
```
Звучит странно, для сравнения — _это будет грустным, это будет плохим, это будет маловажным_ против _это будет грустно, это будет плохо, это будет маловажно_.

2021-08-24 18:44 UTC, UristMcKobold commented on wiki/Help_Centre/Client/ru.md
> +В достаточно свежей версии панели управления NVidia есть настройка под названием `Вертикальный синхроимпульс`, где можно выбрать значение `Быстро`. Это также устранит разрыв картинки.
```suggestion
В достаточно свежей версии панели управления Nvidia есть настройка под названием `Вертикальный синхроимпульс`, где можно выбрать значение `Быстро`. Это также устранит разрыв картинки.
```
Распространённая ошибка!

2021-08-24 20:59 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +Рекомендуется начать с перезагрузки компьютера. Как ни странно, это помогает против многих проблем, в том числе и с osu!.
если бы

2021-08-24 20:59 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +Проверьте, что в настройках osu! в списке веток выбрана `стабильная` ветка.
да, я куда-то слово потерял, хотя помню, что его писал (фантомный перевод)

2021-08-24 20:59 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +**У серверов osu! редко бывают проблемы. Об инцидентах можно узнать на [странице состояния серверов](https://status.ppy.sh) и в твиттере [@osustatus](https://twitter.com/osustatus).**
смысл как раз в первоначальной фразе, по крайней мере, я так вывел из сочетания заголовка и этого параграфа

2021-08-24 20:59 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +**У серверов osu! редко бывают проблемы. Об инцидентах можно узнать на [странице состояния серверов](https://status.ppy.sh) и в твиттере [@osustatus](https://twitter.com/osustatus).**
ладно, уберу отсюда стремление к самозащите

2021-08-24 20:59 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +Помимо ограничения FPS, osu! можно перевести в оконный режим, или выбрать в настройках разрешение экрана без рамки. В этом случае за вертикальную синхронизацию будет отвечать операционная система.
да, похоже, я недоредактировал

2021-08-24 20:59 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +К несчастью, все эти действия *чуть-чуть* увеличивают задержку ввода. Для большинства игроков это будет некритичным.
всё правильно пишешь

2021-08-24 20:59 UTC, TicClick commented on wiki/Help_Centre/Client/ru.md
> +В достаточно свежей версии панели управления NVidia есть настройка под названием `Вертикальный синхроимпульс`, где можно выбрать значение `Быстро`. Это также устранит разрыв картинки.
она вообще [NVIDIA](https://images.nvidia.com/nvimages/aem-dam/Solutions/about-us/documents/NVIDIA.pdf), плюс я из оригинала взял. это надо массово менять

2021-08-24 21:29 UTC, UristMcKobold approved these changes

2021-08-24 21:50 UTC, TPGPL approved these changes

2021-08-24 21:50 UTC, merged