Add `UKCC1` tournament article and other `UKCC` prerequisites
ppy/osu-wiki pull request #6018
Opened 2021-08-25 23:11 UTC by Bazzadwarf

Since UKCC 10 is starting up soon my plans to get UKCC added has been bumped up a bit.

- [x] host fact check

2021-08-27 23:51 UTC, TPGPL requested changes

2021-08-27 23:51 UTC, TPGPL commented on wiki/Tournaments/UKCC/1/en.md
> +| Group Stage | 2016-07-02/2016-07-03 |
```suggestion
| Group stage | 2016-07-02/2016-07-03 |
```

2021-08-27 23:51 UTC, TPGPL commented on wiki/Tournaments/UKCC/1/en.md
> +  - **[Shimotsuki Haruka - Youka to Yumeutsutsu (Naitoshi) (Awakening)](https://osu.ppy.sh/beatmapsets/324587#osu/721158)**
```suggestion
  - **[Shimotsuki Haruka - Youka to Yumeutsutsu (Naitoshi) [Awakening]](https://osu.ppy.sh/beatmapsets/324587#osu/721158)**
```

2021-08-27 23:51 UTC, TPGPL commented on wiki/Tournaments/UKCC/1/en.md
> +## Match Results
```suggestion
## Match results
```

2021-08-27 23:51 UTC, TPGPL commented on wiki/Tournaments/UKCC/1/en.md
> +| helix ![][flag_GB] | 0 | **0** | ![][flag_GB] **Bubbleman** | *no score recorded* |
```suggestion
| helix ![][flag_GB] | -1 | **0** | ![][flag_GB] **Bubbleman** | *no score recorded* |
```

2021-08-27 23:51 UTC, TPGPL commented on wiki/Tournaments/UKCC/1/en.md
> +### Group Stage
```suggestion
### Group stage
```

2021-08-28 00:09 UTC, Bazzadwarf commented on wiki/Tournaments/UKCC/1/en.md
> +| **helix** ![][flag_GB] | **0** | 0 | ![][flag_GB] Pyrooo | *no score recorded* |
```suggestion
| **helix** ![][flag_GB] | **0** | -1 | ![][flag_GB] Pyrooo | *no score recorded* |
```

2021-08-28 00:11 UTC, Bazzadwarf commented on wiki/Tournaments/en.md
> +| [UK Community Cup 10](UKCC/10) | 2021-09-11 | 2021-10-31 | *tdb* | *tdb* | *tdb* |
holy crap I am blind

2021-08-28 01:10 UTC, TPGPL approved these changes

2021-08-28 01:10 UTC, merged