[ZH] Add `Downbeat`
ppy/osu-wiki pull request #6037
Opened 2021-09-01 05:32 UTC by YumeMuzi

2021-09-01 05:35 UTC, cdwcgt requested changes

2021-09-01 05:35 UTC, cdwcgt commented on wiki/Downbeat/zh.md
> +---
```suggestion
tags:
  - downbeats
  - first beat
  - 强拍
  - 第一拍
---
```

2021-09-01 05:39 UTC, cdwcgt submitted a review, later dismissed

2021-09-01 09:47 UTC, kj415j45 commented on wiki/Downbeat/zh.md
> +# 强拍
downbeat 在中文维基百科中的翻译为“下拍”，而 crusis 才是“强拍”[1]

[1] 维基百科编者. 拍 (音乐)[G/OL]. 维基百科, 2020(20201011)[2020-10-11]. https://zh.wikipedia.org/w/index.php?title=%E6%8B%8D_(%E9%9F%B3%E4%B9%90)&oldid=62318753.

2021-09-01 11:51 UTC, YumeMuzi commented on wiki/Downbeat/zh.md
> +# 强拍
中国大陆的语境中，几乎不可见区分“上下拍”的说法，而crusis在google上也没有对应词条。
但尽可能贴合原意，还是改了

2021-09-01 11:53 UTC, cdwcgt requested changes

2021-09-01 11:53 UTC, cdwcgt commented on wiki/Downbeat/zh.md
> +  - 强拍
```suggestion
  - 下拍
```
这里忘改了

2021-09-07 00:50 UTC, kj415j45 approved these changes

2021-09-07 01:06 UTC, TicClick approved these changes

2021-09-07 01:07 UTC, merged