[ZH] Add Mascots
ppy/osu-wiki pull request #6047
Opened 2021-09-02 14:21 UTC by YumeMuzi

2021-09-11 11:21 UTC, kj415j45 commented on wiki/Mascots/zh.md
> +Mani 和 Mari 是由 [xiemon](https://osu.ppy.sh/users/5203667) 设计，在 [Most Manic Art Contest](https://osu.ppy.sh/community/contests/80) 中脱颖而出，并于 2020 年 9 月 18 日成为 osu!mania 模式的官方吉祥物。Mani 和 Mari 是互相看不惯对方，但又
```suggestion
Mani 和 Mari 由 [xiemon](https://osu.ppy.sh/users/5203667) 设计，在 [Most Manic Art Contest](https://osu.ppy.sh/community/contests/80) 中脱颖而出，并于 2020 年 9 月 18 日成为 osu!mania 模式的官方吉祥物。Mani 和 Mari 是互相看不惯对方，但又不可否认地很相似的一对双胞胎。
```
第一句的层次感觉还是有些怪，可能需要调整语序？

2021-09-11 11:21 UTC, kj415j45 commented on wiki/Mascots/zh.md
> +Mani 是个特立独行的人，他总是渴望探索新花样和新事物。同时，他的妹妹 Mari（以前又被叫做 Maria）是一个传统、死板的理想主义者，同时也很喜欢成为聚光灯下的焦点。这对双胞胎的性格截然不同，很难相处。
```suggestion
Mani 是个特立独行的人，他总是渴望探索新花样和新事物。同时，他的妹妹 Mari（以前又被叫做 Maria）是一个传统、保守的理想主义者，也希望成为聚光灯下的焦点。因性格迥异，他们之间水火不相容。
```
“死板”感觉偏贬义了一些，“保守”较为中性。

2021-09-11 11:21 UTC, kj415j45 commented on wiki/Mascots/zh.md
> +一本木龍太（Ryūta Ippongi）曾是 osu!catch 模式中的接水果小人，于 2008 年加入 osu!，但于 2014 年被 [Yuzu](#-yuzu) 替代。他的艺术形象由 [iNiS 公司](https://en.wikipedia.org/wiki/INiS) 设计，并曾作为老版官方网页的一部分。同时，他也曾在 [病娇模拟器](https://yanderesimulato
```suggestion
一本木龍太（Ryūta Ippongi）曾是 osu!catch 模式中的接水果小人，于 2008 年加入 osu!，但于 2014 年被 [Yuzu](#-yuzu) 替代。他的艺术形象由 [iNiS 公司](https://en.wikipedia.org/wiki/INiS) 设计，并曾作为老版官方网页的一部分。他也曾在 [病娇模拟器](https://yanderesimulator.com) 中作为 NPC 出现。
```

2021-09-11 11:21 UTC, kj415j45 commented on wiki/Mascots/zh.md
> +> Don 是游戏 [太鼓达人](https://en.wikipedia.org/wiki/Taiko_no_Tatsujin) 系列的主角。他是一只有白色鼓边、红橙色鼓面、淡蓝色身体、四只脚的太鼓。Don 的梦想是把太鼓的美妙带给全世界。在他搬到和田屋三年之后，城镇中无人不晓他的名号。他食量惊人，经常花重金买许多好吃的，以至于和田屋有时候都负担不起他的消费。他的口癖是经常在句尾带上一句 "T
```suggestion
> Don 是游戏 [太鼓达人](https://zh.wikipedia.org/wiki/%E5%A4%AA%E9%BC%93%E4%B9%8B%E9%81%94%E4%BA%BA%E7%B3%BB%E5%88%97) 系列的主角。他是一只有白色鼓边、红橙色鼓面、淡蓝色身体、四只脚的太鼓。Don 的梦想是把太鼓的美妙带给全世界。在他搬到和田屋三年后，城镇中无人不晓他的名号。他食量惊人，经常花重金买许多好吃的，以至于和田屋有时候都负担不起他的消费。他的口癖是经常在句尾带上一句 "Ta-Don"，意为敲击鼓面的声音。
```

2021-09-15 04:59 UTC, YumeMuzi commented on wiki/Mascots/zh.md
> +Mani 和 Mari 是由 [xiemon](https://osu.ppy.sh/users/5203667) 设计，在 [Most Manic Art Contest](https://osu.ppy.sh/community/contests/80) 中脱颖而出，并于 2020 年 9 月 18 日成为 osu!mania 模式的官方吉祥物。Mani 和 Mari 是互相看不惯对方，但又
没想好改法 但确实有点怪 先按你说的改吧

2021-09-15 12:33 UTC, kj415j45 commented
pro tip: Switch to `Files changed` tab to use `Add suggestion to batch` feature. This would reduce your commit times and avoid unnecessary rebase:
![image](https://user-images.githubusercontent.com/18349191/133433622-6dad2ecf-1bab-4c0d-8e77-d46b027adf23.png)

2021-09-17 18:44 UTC, TPGPL commented on wiki/Mascots/zh.md
> +### ![osu! icon](/wiki/shared/mode/osu.png) pippi
the alt text ("osu! icon") needs to be translated

same for the images below

2021-09-17 19:14 UTC, TPGPL requested changes

2021-09-17 19:14 UTC, TPGPL commented on wiki/Mascots/zh.md
> +> Don 是游戏 [太鼓达人](https://zh.wikipedia.org/wiki/%E5%A4%AA%E9%BC%93%E4%B9%8B%E9%81%94%E4%BA%BA%E7%B3%BB%E5%88%97) 系列的主角。他是一只有白色鼓边、红橙色鼓面、淡蓝色身体、四只脚的太鼓。Don 的梦想是把太鼓的美妙带给全世界。在他搬到和田屋三年后，城镇中无人不晓他的名号。他食量惊人，经常花
```suggestion
> Don 是游戏 [太鼓达人](https://zh.wikipedia.org/wiki/太鼓之達人系列) 系列的主角。他是一只有白色鼓边、红橙色鼓面、淡蓝色身体、四只脚的太鼓。Don 的梦想是把太鼓的美妙带给全世界。在他搬到和田屋三年后，城镇中无人不晓他的名号。他食量惊人，经常花重金买许多好吃的，以至于和田屋有时候都负担不起他的消费。他的口癖是经常在句尾带上一句 "Ta-Don"，意为敲击鼓面的声音。
```

2021-09-17 19:14 UTC, TPGPL commented on wiki/Mascots/zh.md
> +### 一本木龙太
```suggestion
### Ryūta Ippongi
```

2021-09-23 16:36 UTC, TPGPL approved these changes

2021-09-23 16:37 UTC, TPGPL approved these changes

2021-09-23 16:38 UTC, merged