Rewrite `Reporting bad behaviour`
ppy/osu-wiki pull request #6051
Opened 2021-09-03 02:18 UTC by TicClick

- textual overview of everything
- no dialogue-like FAQ (everything is in regular style)
- the intro probably could be improved

also, any thoughts on renaming the article? I feel that something short but descriptive would work better, but at the same time we need to maintain the hierarchy of `Reporting ...` > `(Abuse, Cheating)`

2021-09-03 03:37 UTC, TicClick commented
additionally, image layout is wacky, but once we have infoboxes with zoom-in, it will be fixed.

2021-09-03 06:43 UTC, Walavouchey commented on wiki/Reporting_Bad_Behaviour/en.md
> +osu! has [a team of moderators](/wiki/People/The_Team/Global_Moderation_Team) who adhere to keeping the game and its ecosystem clean and safe. If you notice rule-breaking behaviour or inappropriate c
one team, group or organisation is still singular

```suggestion
osu! has [a team of moderators](/wiki/People/The_Team/Global_Moderation_Team) that adheres to keeping the game and its ecosystem clean and safe. If you notice rule-breaking behaviour or inappropriate content, report it using one of the methods described below. Alternatively, you may contact any of the moderators online directly if your report wasn't properly handled within a reasonable amount of time — do so only as the last resort.
```

2021-09-03 06:43 UTC, Walavouchey commented on wiki/Reporting_Bad_Behaviour/en.md
> +Accidental reports are ignored. Users that purposedly send invalid reports are [silenced](/wiki/Silence).
```suggestion
Accidental reports are ignored. Users who purposedly send invalid reports are [silenced](/wiki/Silence).
```

2021-09-03 06:43 UTC, Walavouchey commented on wiki/Reporting_Bad_Behaviour/en.md
> +2. In a row of buttons that appear in the top right corner of the post, click the button with warning sign.
```suggestion
2. In a row of buttons that appear in the top right corner of the post, click the button with a warning sign.
```

2021-09-03 14:32 UTC, Walavouchey commented on wiki/Reporting_Bad_Behaviour/en.md
> +osu! has [a team of moderators](/wiki/People/The_Team/Global_Moderation_Team) who adhere to keeping the game and its ecosystem clean and safe. If you notice rule-breaking behaviour or inappropriate c
hmm, just realised that it's ambiguous whether it's the "team" or the "moderators" doing the adhering, depending on where you put the emphasis while reading, so keep it or change it as you prefer.

2021-09-07 09:52 UTC, Ephemeralis requested changes
a few minor changes

2021-09-07 09:52 UTC, Ephemeralis commented on wiki/Reporting_Bad_Behaviour/en.md
> +Accidental reports are ignored. Users who purposedly send invalid reports are [silenced](/wiki/Silence).
```suggestion
Accidental reports are ignored. Users who deliberately send invalid reports can risk being [silenced](/wiki/Silence).
```

2021-09-07 09:52 UTC, Ephemeralis commented on wiki/Reporting_Bad_Behaviour/en.md
> +| Mildly offensive private messages | **None**: [ignore the user](/wiki/Chat_Console#commands-list) instead. For permanent effect, use the in-game ignore list located in [options](/wiki/Options). |
```suggestion
| Offensive private messages | **None**: [ignore the user](/wiki/Chat_Console#commands-list) instead. For permanent effect, use the in-game ignore list located in [options](/wiki/Options). |
```

2021-09-07 09:52 UTC, Ephemeralis commented on wiki/Reporting_Bad_Behaviour/en.md
> +Chat misbehaviour is the most common infringement. To report it, use the [`!report`](https://osu.ppy.sh/community/forums/topics/34843) command, preferably in the channel where infringement took place
```suggestion
Chat misbehaviour is the most common infringement. To report it, use the [`!report`](https://osu.ppy.sh/community/forums/topics/34843) command, preferably in the channel where infringement took place. Don't feel stressed: if your message starts with `!report` and a space, **it is only visible to moderators** and no one else in the chat. You can also use the report function via the in-game overlay as depicted below if you are still concerned.
```

2021-09-07 16:12 UTC, Ephemeralis approved these changes
looks good to me

2021-09-08 17:40 UTC, TPGPL approved these changes

2021-09-08 17:41 UTC, merged