Update/Cleanup `Mappers' Guild` and `Featured artist showcase beatmaps`
ppy/osu-wiki pull request #6064
Opened 2021-09-06 02:08 UTC by Nivalyx

Follow-up of [#6052](https://github.com/ppy/osu-wiki/pull/6052) :

- Add `Showcase beatmaps` sub-section to the `Mappers' Guild` article
- Add related images to the `Mappers' Guild` article
- Update the `Featured artist showcase beatmaps` article to include showcase beatmaps from August
- ...and other sorts of general cleanup to both articles

2021-09-06 20:15 UTC, TicClick requested changes
minor corrections, the texts read alright to my taste anyway

2021-09-06 20:15 UTC, TicClick commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/en.md
> +Members of the [Mappers' Guild](/wiki/Mappers_Guild) may occasionally create exclusive "showcase beatmaps" by using songs and other materials from osu!'s unreleased [featured artists](/wiki/Featured_
we've decided to throw the alt text away: #6060
```suggestion
Members of the [Mappers' Guild](/wiki/Mappers_Guild) may occasionally create exclusive "showcase beatmaps" by using songs and other materials from osu!'s unreleased [featured artists](/wiki/Featured_Artists). Upon the announcement of the corresponding featured artist, these beatmaps are highlighted in the [newspost](https://osu.ppy.sh/home/news) and are often promoted on the [@osugame Twitter](https://twitter.com/osugame) as well.
```

2021-09-06 20:15 UTC, TicClick commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/en.md
> +From its very beginning, the Mappers' Guild has been set into pace with "creating promotional beatmap packs for upcoming featured artists" <!-- https://osu.ppy.sh/community/forums/topics/875743 --> a
```suggestion
From its very beginning, the Mappers' Guild has been set into pace with "creating promotional beatmap packs for upcoming featured artists"<!-- https://osu.ppy.sh/community/forums/topics/875743 --> as one of its primary goals. This was reflected in the Guild's first ever major project, in where members of the Guild had prepared and ranked six beatmaps of [licensed MOtOLOiD songs](https://osu.ppy.sh/beatmaps/artists/19) long prior to the [corresponding artist's announcement](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid).
```

2021-09-06 20:15 UTC, TicClick commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/en.md
> +As the Guild itself was operating on a closed, application-based entry in its early days, access to upcoming featured artist contents were often restricted only to a handful of mappers who were predo
long links are poor style
```suggestion
As the Guild itself was operating on a closed, application-based entry in its early days, access to upcoming featured artist contents were often restricted only to a handful of mappers who were predominantly of the [osu!](/wiki/Game_mode/osu!) game mode]. However, as the Guild began to shift to an open and automated entry system [in early 2019](/wiki/Mapping_and_Modding_Timeline#march.5), more and more mappers were drawn into the creation of showcase beatmaps for future featured artists over time regardless of their game mode.
```

2021-09-06 20:15 UTC, TicClick commented on wiki/Mappers_Guild/en.md
> +Members of the Mappers' Guild may also participate in the creation of showcase beatmaps for future featured artist announcements. Upon the announcement of the corresponding featured artist, these bea
please remove alt text here as well
also, newspost -> news? sounds more fitting
```suggestion
Members of the Mappers' Guild may also participate in the creation of showcase beatmaps for future featured artist announcements. Upon the announcement of the corresponding featured artist, these beatmaps are highlighted in the [newspost](https://osu.ppy.sh/home/news) and are often promoted on the [@osugame Twitter](https://twitter.com/osugame) as well.
```

2021-09-07 01:42 UTC, Nivalyx commented
ah, ok, applied everything @TicClick 👍 

for that one suggestion i think both `news` and `news post` work just fine tho, so i decided to keep it as is. feel free to change it if you feel necessary tho :P

2021-09-07 02:42 UTC, TicClick approved these changes
nah it's minor

2021-09-07 02:42 UTC, merged