Add `UKCC7` tournament article
ppy/osu-wiki pull request #6083
Opened 2021-09-09 14:43 UTC by Bazzadwarf

Doing this one is slightly out of order, but since the file already existed from https://github.com/ppy/osu-wiki/pull/3266 I just went ahead and gave it a clean up to bring it in line with the current tournament wiki template and standards. Big thanks to @DMills94 for doing most of the busywork.

- [ ] Host fact check.

2021-09-09 15:03 UTC, Bazzadwarf commented
Ready for a review!

2021-09-10 00:37 UTC, TPGPL requested changes

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +**[Download the map pack here! (128.7MB)](https://mega.nz/#!S7p2QShR!ugelC74o3C1Xc3ECMHCb7EWzhvuZh75UuGs9_nznR44)**
```suggestion
**[Download the mappack here! (128.7MB)](https://mega.nz/#!S7p2QShR!ugelC74o3C1Xc3ECMHCb7EWzhvuZh75UuGs9_nznR44)**
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +**[Download the map pack here! (141.7MB)](https://mega.nz/#!37BHiSQa!_YCHsfzKe3AqxPboSBa2Uuyf0_chbWqYVTpd5QNj9WA)**
```suggestion
**[Download the mappack here! (141.7MB)](https://mega.nz/#!37BHiSQa!_YCHsfzKe3AqxPboSBa2Uuyf0_chbWqYVTpd5QNj9WA)**
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +**[Download the map pack here! (163.5MB)](https://mega.nz/#!qqA2nCSa!zCQWppNn47REZtWCPLk9aVguEF9rGuO9h6BwHQGVqUk)**
```suggestion
**[Download the mappack here! (163.5MB)](https://mega.nz/#!qqA2nCSa!zCQWppNn47REZtWCPLk9aVguEF9rGuO9h6BwHQGVqUk)**
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +**[Download the map pack here! (114.6MB)](https://mega.nz/#!OvQhmAiS!PT1qpuu5XGjnvX9Ra9w8flaEZsL_CCW47scekuARt7Y)**
```suggestion
**[Download the mappack here! (114.6MB)](https://mega.nz/#!OvQhmAiS!PT1qpuu5XGjnvX9Ra9w8flaEZsL_CCW47scekuARt7Y)**
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +**[Download the map pack here! (86.8MB)](https://mega.nz/#!f3ASAA7T!umH3bN99cnuYe1ZFsOiXauUBFQRrW0n-_Zr4V8gE9ZA)**
```suggestion
**[Download the mappack here! (86.8MB)](https://mega.nz/#!f3ASAA7T!umH3bN99cnuYe1ZFsOiXauUBFQRrW0n-_Zr4V8gE9ZA)**
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +**[Download the map pack here! (46.7MB)](https://mega.nz/#!T6RjDY7S!0PbquOystkS4v2-byiBC0b_KMEZA8lECFhMqjYKDm_A)**
```suggestion
**[Download the mappack here! (46.7MB)](https://mega.nz/#!T6RjDY7S!0PbquOystkS4v2-byiBC0b_KMEZA8lECFhMqjYKDm_A)**
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +![Schedules](img/schedule_no_number.png)
```suggestion
## Match schedule

![Match schedule](img/schedule_no_number.png)

## Match results
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +| Wario ![][flag_GB] | 2 | 5 | ![][flag_GB] **Ventus** | [#1](https://osu.ppy.sh/community/matches/55378053) |
```suggestion
| Wario ![][flag_GB] | 2 | **5** | ![][flag_GB] **Ventus** | [#1](https://osu.ppy.sh/community/matches/55378053) |
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +| majoreh ![][flag_GB] | 2 | **5** | ![][flag_GB] Zyphox | [#1](https://osu.ppy.sh/community/matches/55347021) |
```suggestion
| MoeYandere ![][flag_GB] | -1 | **0** | ![][flag_GB] **hlo** | *forfeit* |
| majoreh ![][flag_GB] | 2 | **5** | ![][flag_GB] **Zyphox** | [#1](https://osu.ppy.sh/community/matches/55347021) |
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +| Voss ![][flag_GB] | 2 | 5 | ![][flag_GB] **Kerantina** | [#1](https://osu.ppy.sh/community/matches/55376109) |
```suggestion
| Voss ![][flag_GB] | 2 | **5** | ![][flag_GB] **Kerantina** | [#1](https://osu.ppy.sh/community/matches/55376109) |
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +| -spoon- ![][flag_GB] | 4 | **5** | ![][flag_GB] Wario | [#1](https://osu.ppy.sh/community/matches/55061725) |
```suggestion
| -spoon- ![][flag_GB] | 4 | **5** | ![][flag_GB] **Wario** | [#1](https://osu.ppy.sh/community/matches/55061725) |
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +| Placing | Player | Total Score | Average Score |
```suggestion
| Placing | Player | Total score | Average score |
```

2021-09-10 00:37 UTC, TPGPL commented on wiki/Tournaments/UKCC/7/en.md
> +| Placing | Player | Total Score | Average Score |
```suggestion
| Placing | Player | Total score | Average score |
```

2021-09-10 01:39 UTC, Bazzadwarf commented on wiki/Tournaments/UKCC/7/en.md
> +![Schedules](img/schedule_no_number.png)
```suggestion
## Match results
```

2021-09-10 15:25 UTC, TPGPL approved these changes

2021-09-10 15:25 UTC, merged