Clean up: make "osu!team" a regular collocation
ppy/osu-wiki pull request #6086
Opened 2021-09-09 18:11 UTC by TicClick

part of #1698
thanks to everyone who helped with the translations. other occurences are in outdated articles, so they will eventually be fixed by future translators

2021-09-09 18:20 UTC, TicClick commented
style errors are in the article which will be removed by #4941 so I don't see any point in fixing it

2021-09-12 17:05 UTC, peppy submitted a review, later dismissed
seems fine

2021-09-12 17:50 UTC, Joehuu requested changes

2021-09-12 17:50 UTC, Joehuu commented on wiki/Beatmap/fr.md
> +Les artistes associés (Featured Artists) est un programme de l'[osu! team](/wiki/People/The_Team) visant à licencier la musique de différents artistes pour osu!, les rendant ainsi disponible au mappi
```suggestion
Les artistes associés (Featured Artists) est un programme de l'[osu! team](/wiki/People/The_Team) visant à licencier la musique de différents artistes pour osu!, les rendant ainsi disponible au mapping. La [liste des artistes associés](https://osu.ppy.sh/beatmaps/artists) du site internet présente chaque artiste impliqué et fournit des modèles pré-paramétrés pour le mapping.
```
```suggestion
Les artistes associés (Featured Artists) est un programme de l'[équipe du jeu](/wiki/People/The_Team) visant à licencier la musique de différents artistes pour osu!, les rendant ainsi disponible au mapping. La [liste des artistes associés](https://osu.ppy.sh/beatmaps/artists) du site internet présente chaque artiste impliqué et fournit des modèles pré-paramétrés pour le mapping.
```

2021-09-12 17:50 UTC, Joehuu commented on wiki/Beatmap/id.md
> +Featured Artist adalah program komunitas yang dibuat oleh [osu! team](/wiki/People/The_Team) yang berfokus pada pemberian lisensi musik dari berbagai artis untuk osu! dan membuatnya tersedia untuk ma
```suggestion
Featured Artist adalah program komunitas yang dibuat oleh [tim inti osu!](/wiki/People/The_Team) yang berfokus pada pemberian lisensi musik dari berbagai artis untuk osu! dan membuatnya tersedia untuk mapping. Situs web [daftar featured artist](https://osu.ppy.sh/beatmaps/artists) memamerkan setiap artis yang terlibat sekaligus menyediakan template untuk mapping.
```

2021-09-12 18:52 UTC, Joehuu approved these changes

2021-09-13 01:39 UTC, merged