[FR] Update `Beatmap/Category`, `Beatmap/Beatmap description`, `Beatmap/Difficulty` and `Beatmap/History of Loved`
ppy/osu-wiki pull request #6124
Opened 2021-09-17 18:16 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Beatmap/Category`
- `Beatmap/Beatmap description`
- `Beatmap/Difficulty`
- `Beatmap/History of Loved`

*Feel free to merge if the delay is too long for a review by a native.*

2021-09-23 08:35 UTC, Ganondorf-1 requested changes

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Beatmap_description/fr.md
> +- Une liste de toutes les [difficultés des invités](/wiki/Beatmap/Guest_difficulty) et de leurs créateurs.
```suggestion
- Une liste de toutes les [guest difficulties](/wiki/Beatmap/Guest_difficulty) et de leurs créateurs.
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Beatmap_description/fr.md
> +De nombreuses descriptions de beatmaps contiennent au moins une image (souvent un [GIF](https://fr.wikipedia.org/wiki/Graphics_Interchange_Format) animé) qui est utilisée pour exprimer et illustrer l
```suggestion
De nombreuses descriptions de beatmaps contiennent au moins une image (souvent un [GIF](https://fr.wikipedia.org/wiki/Graphics_Interchange_Format) animé) qui est utilisée pour exprimer et illustrer le créateur, la chanson et/ou la beatmap de manière voyante. Elles peuvent également servir de titre ou d'en-tête pour ajouter du style et de la qualité. Pour savoir comment ajouter une image, consultez la [section de l'article BBCode sur les images](/wiki/BBCode#image).
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Beatmap_description/fr.md
> +Une *section de difficultés* est une liste de toutes les difficultés invitées (souvent accompagnées de leurs icônes respectives) et de leurs créateurs, située dans la description de la beatmap. Elle
```suggestion
La *section de difficultés* est une liste de toutes les guest difficulties (souvent accompagnées de leurs icônes respectives) et de leurs créateurs, située dans la description de la beatmap. Elle est surtout utilisée pour créditer les mappeurs invités.
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Category/fr.md
>  Les [beatmaps](/wiki/Beatmap) soumises en ligne sont réparties en catégories en fonction de leurs activités récentes, de leurs [nomination](/wiki/Beatmap_ranking_procedure#qualification) et de leurs
```suggestion
Les [beatmaps](/wiki/Beatmap) soumises en ligne sont réparties en catégories en fonction de leurs activités récentes, de leurs [nominations](/wiki/Beatmap_ranking_procedure#qualification) et de leur popularité.
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Category/fr.md
> +Le cimetière est un endroit où résident les beatmaps abandonnées par leurs [hôtes](/wiki/Beatmap/Beatmap_host). Ces maps n'ont pas de classement, mais elles peuvent toujours être téléchargées et joué
```suggestion
Le cimetière est un endroit où résident les beatmaps abandonnées par leurs [hôtes](/wiki/Beatmap/Beatmap_host). Ces beatmaps n'ont pas de classement, mais elles peuvent toujours être téléchargées et jouées, et elles continuent à [contribuer aux statistiques de jeu](#statistiques-des-beatmaps-non-classées). Elles utilisent l'icône de point d'interrogation (![](/wiki/shared/status/graveyard.png)) dans l'[écran de sélection des beatmaps](/wiki/Interface#song-selection-screen).
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Category/fr.md
> +Une beatmap est automatiquement déplacé au cimetière depuis [Work In Progress et En attente](#work-in-progress-et-en-attente) lorsqu'il n'a pas été mis à jour depuis 4 semaines. L'auteur peut faire r
```suggestion
Une beatmap est automatiquement déplacée au cimetière depuis les catégories [Work In Progress et En attente](#work-in-progress-et-en-attente) lorsqu'elle n'a pas été mise à jour depuis 4 semaines. L'auteur peut faire revivre la beatmap (c'est-à-dire la ramener dans la catégorie [en attente](#work-in-progress-et-en-attente)) en la mettant à jour via le [système de soumission des beatmaps](/wiki/Submission). Une beatmap au cimetière ne compte pas dans la [limite totale de publications](/wiki/Help_Centre/Beatmapping#je-suis-un-osu!supporter-mais-je-n'ai-pas-10-emplacements-en-attente-!) d'un mappeur, mais la faire revivre nécessite un emplacement libre.
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Difficulty/fr.md
> +Dans certains cas, comme dans [AIMod](/wiki/Beatmap_Editor/AiMod), la difficulté est classée en six niveaux selon le classement en étoiles, comme suit :
```suggestion
Dans certains cas, comme dans [AIMod](/wiki/Beatmap_Editor/AiMod), la difficulté est classée en six niveaux selon le star rating, comme suit :
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/History_of_Loved/fr.md
>  La catégorie de beatmaps [Loved](/wiki/Beatmap/Category#loved) est actuellement gérée par le [Project Loved](/wiki/Project_Loved). Cependant, cela n'a pas toujours été le cas. Project Loved est le tr
```suggestion
La catégorie de beatmaps [Loved](/wiki/Beatmap/Category#loved) est actuellement gérée par le [Project Loved](/wiki/Project_Loved). Cependant, cela n'a pas toujours été le cas. Project Loved est le troisième système principal qui a promu les beatmaps à la catégorie Loved ; avant lui, il y avait d'autres méthodes pour le faire, ainsi que de longues périodes de stagnation pour la catégorie Loved.
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/History_of_Loved/fr.md
> +En décembre 2020, les efforts de développement du [site web officiel du projet Loved](https://loved.sh/) ont commencé, et peu de temps après il a été lancé, simplement comme une page d'administration
```suggestion
En décembre 2020, les efforts de développement du [site web officiel du Project Loved](https://loved.sh/) ont commencé, et celui-ci a été lancé peu de temps après simplement comme une page d'administration pour les coordinateurs au début. À la mi-2021, le site a été mis à la disposition du reste de l'équipe. Finalement, en août 2021, les formulaires et les spreadsheets Google utilisés pour les soumissions et la visualisation des beatmaps ont été complètement abandonnés et ont commencé à être hébergés sur le site web.
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Difficulty/fr.md
> +À partir du 27 juillet 2021, le site web d'osu! attribue automatiquement la couleur de l'indice de difficulté d'une beatmap en fonction de son classement en étoiles selon le spectre suivant :
```suggestion
À partir du 27 juillet 2021, le site web d'osu! attribue automatiquement la couleur de l'indice de difficulté d'une beatmap en fonction de son star rating selon le spectre suivant :
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Difficulty/fr.md
> +## Difficulté et classement en étoiles
```suggestion
## Difficulté et star rating
```

2021-09-23 08:35 UTC, Ganondorf-1 commented on wiki/Beatmap/Difficulty/fr.md
> +Notez que si les niveaux de difficulté prévus pour la plupart des beatmaps correspondent aux couleurs ou aux fourchettes de niveaux qui leur sont attribuées, certains peuvent s'en écarter sensiblemen
```suggestion
Notez que si les niveaux de difficulté prévus pour la plupart des beatmaps correspondent aux couleurs ou aux fourchettes de niveaux qui leur sont attribuées, certains peuvent s'en écarter sensiblement en raison de certains facteurs. C'est pourquoi les [critères de classement](/wiki/Ranking_Criteria) offrent des règles de base plus décisives pour déterminer le niveau de difficulté réel d'une beatmap, indépendamment de son star rating.
```

2021-10-01 19:30 UTC, TPGPL approved these changes

2021-10-01 19:30 UTC, merged