[FR] Update `Featured Artists/Featured Artists Showcase Beatmaps`
ppy/osu-wiki pull request #6126
Opened 2021-09-17 18:39 UTC by DoryanR

Proposal to update the French translation of the wiki page `Featured Artists/Featured Artists Showcase Beatmaps`.

2021-09-18 09:11 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Dès sa création, la Mappers' Guild s'est fixé comme objectif principal de "créer des packs de beatmaps promotionnels pour les artistes associés à venir". Cela s'est reflété dans le tout premier proje
```suggestion

Dès sa création, la Mappers' Guild s'est fixé comme objectif principal de "créer des packs de beatmaps promotionnels pour les artistes associés à venir". Cela s'est reflété dans le tout premier projet majeur de la Guilde, dans lequel les membres de la Guilde ont préparé et classé six beatmaps des [musiques MOtOLOiD sous licence](https://osu.ppy.sh/beatmaps/artists/19) bien avant [l'annonce de l'artiste correspondant](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid).
```

2021-09-18 09:58 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +  - (![][osu!]) [Release Hallucination - Ariadne](https://osu.ppy.sh/beatmapsets/1550194) hosted by ![][flag_PL] [Zelq](https://osu.ppy.sh/users/8953955)
```suggestion
  - (![][osu!]) [Release Hallucination - Ariadne](https://osu.ppy.sh/beatmapsets/1550194) hosted by ![][flag_PL] [Zelq](https://osu.ppy.sh/users/8953955)
  
```

2021-09-18 09:58 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
```suggestion
```

2021-09-19 08:28 UTC, Ganondorf-1 requested changes

2021-09-19 08:28 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Les membres de la [Mappers' Guild](/wiki/Mappers_Guild) peuvent occasionnellement créer des maps exclusives en utilisant les musiques et autres éléments des [artistes associés](/wiki/Featured_Artists
```suggestion
Les membres de la [Mappers' Guild](/wiki/Mappers_Guild) peuvent occasionnellement créer des maps exclusives en utilisant les musiques et autres éléments des [artistes associés](/wiki/Featured_Artists) inédits d'osu!. Dès l'annonce de l'artiste correspondant, ces maps sont mises en évidence dans les [newspost](https://osu.ppy.sh/home/news) et sont souvent promues sur le [compte Twitter @osugame](https://twitter.com/osugame).
```

2021-09-19 08:28 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Pour participer à la création des beatmaps de artistes associés, un membre de la Mappers' Guild doit soit accepter une [quête mystère à durée limitée](/wiki/Mappers_Guild#quests), soit être directeme
```suggestion
Pour participer à la création des beatmaps d'artistes associés, un membre de la Mappers' Guild doit soit accepter une [quête mystère à durée limitée](/wiki/Mappers_Guild#quests), soit être directement invité par ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418), soit avoir son paramètre `FA showcase mapper` activé dans le [site web de la Mappers' Guild](https://mappersguild.com/).
```

2021-09-19 08:28 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Dès sa création, la Mappers' Guild s'est fixé comme objectif principal de "créer des packs de beatmaps promotionnels pour les artistes associés à venir". Cela s'est reflété dans le tout premier proje
```suggestion
Dès sa création, la Mappers' Guild s'est fixée comme objectif principal de "créer des packs de beatmaps promotionnels pour les artistes associés à venir". Cela s'est reflété dans le tout premier projet majeur de la Guilde, dans lequel les membres de la Guilde ont préparé et classé six beatmaps des [musiques MOtOLOiD sous licence](https://osu.ppy.sh/beatmaps/artists/19) bien avant [l'annonce de l'artiste correspondant](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid).
```

2021-09-19 08:28 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
>  À partir de l'annonce de l'artiste associé [MYUKKE.](https://osu.ppy.sh/home/news/2020-12-05-new-featured-artist-myukke) en décembre 2020, les nouvelles annonces d'artistes vedettes ont parfois comme
```suggestion
À partir de l'annonce de l'artiste associé [MYUKKE.](https://osu.ppy.sh/home/news/2020-12-05-new-featured-artist-myukke) en décembre 2020, les nouvelles annonces d'artistes associés ont parfois commencé à présenter de courtes vidéos d'avant-première, souvent accompagnées d'une beatmap en guise de titre principal.
```

2021-09-23 08:50 UTC, Ganondorf-1 requested changes

2021-09-23 08:50 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +  - (![][osu!]) [technoplanet feat. chamo - Tepic Tepoch](https://osu.ppy.sh/beatmapsets/1551369) hosted by ![][flag_TR] [Entry](https://osu.ppy.sh/users/10213311)
```suggestion
  - (![][osu!]) [technoplanet feat. chamo - Tepic Tepoch](https://osu.ppy.sh/beatmapsets/1551369) organisé par ![][flag_TR] [Entry](https://osu.ppy.sh/users/10213311)
```

2021-09-23 08:50 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> + - (![][osu!catch]) [technoplanet - Intuition](https://osu.ppy.sh/beatmapsets/1553878) hosted by ![][flag_PH] [Jemzuu](https://osu.ppy.sh/users/7890134)
```suggestion
 - (![][osu!catch]) [technoplanet - Intuition](https://osu.ppy.sh/beatmapsets/1553878) organisé par ![][flag_PH] [Jemzuu](https://osu.ppy.sh/users/7890134)     
```

2021-09-23 08:50 UTC, Ganondorf-1 commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +  - (![][osu!]) [Release Hallucination - Ariadne](https://osu.ppy.sh/beatmapsets/1550194) hosted by ![][flag_PL] [Zelq](https://osu.ppy.sh/users/8953955)
```suggestion
  - (![][osu!]) [Release Hallucination - Ariadne](https://osu.ppy.sh/beatmapsets/1550194) organisé par ![][flag_PL] [Zelq](https://osu.ppy.sh/users/8953955)
```

2021-09-30 10:00 UTC, Ganondorf-1 submitted a review, later dismissed

2021-09-30 12:54 UTC, TPGPL requested changes

2021-09-30 12:54 UTC, TPGPL commented on wiki/Featured_Artists/Featured_Artist_Showcase_Beatmaps/fr.md
> +Pour participer à la création des beatmaps d'artistes associés, un membre de la Mappers' Guild doit soit accepter une [quête mystère à durée limitée](/wiki/Mappers_Guild#quests), soit être directemen
```suggestion
Pour participer à la création des beatmaps d'artistes associés, un membre de la Mappers' Guild doit soit accepter une [quête mystère à durée limitée](/wiki/Mappers_Guild#quêtes), soit être directement invité par ![][flag_US] [pishifat](https://osu.ppy.sh/users/3178418), soit avoir son paramètre `FA showcase mapper` activé dans le [site web de la Mappers' Guild](https://mappersguild.com/).
```

2021-09-30 13:01 UTC, TPGPL approved these changes

2021-09-30 13:01 UTC, merged