[FR] Update `Glossary/Changelog`, `Glossary/Choke` and `Glossary/Combo fire`
ppy/osu-wiki pull request #6132
Opened 2021-09-18 13:52 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Glossary/Changelog`
- `Glossary/Choke`
- `Glossary/Combo fire`

2021-09-19 09:03 UTC, Ganondorf-1 requested changes

2021-09-19 09:03 UTC, Ganondorf-1 commented on wiki/Glossary/Choke/fr.md
> +La caractéristique principale d'un choke est son caractère aléatoire et ses performances incohérentes. Cela exclut les miss réguliers ou spécifiques à un motif ou les [slider breaks](/wiki/Gameplay/S
```suggestion
La caractéristique principale d'un choke est son caractère aléatoire et ses performances incohérentes. Cela exclut les miss réguliers ou spécifiques à un pattern ou les [slider breaks](/wiki/Gameplay/Sliderbreak), qui sont généralement liés au niveau de compétence du joueur ou à la façon dont la beatmap est construite. Les chokes sont généralement causés par un stress mental excessif et une nervosité pendant la partie, ainsi que par une fatigue générale.
```

2021-09-19 09:03 UTC, Ganondorf-1 commented on wiki/Glossary/Choke/fr.md
> +La caractéristique principale d'un choke est son caractère aléatoire et ses performances incohérentes. Cela exclut les miss réguliers ou spécifiques à un motif ou les [slider breaks](/wiki/Gameplay/S
Pour le mot "pattern", il me semble qu'on l'avait laissé comme ça dans un autre article, et la plupart des joueurs utilisent ce terme pour désigner ces passages spécifiques donc à voir si c'est vraiment dérangeant de le laisser en anglais

2021-09-21 14:19 UTC, DoryanR commented on wiki/Glossary/Choke/fr.md
> +La caractéristique principale d'un choke est son caractère aléatoire et ses performances incohérentes. Cela exclut les miss réguliers ou spécifiques à un pattern ou les [slider breaks](/wiki/Gameplay
```suggestion
La caractéristique principale d'un choke est son caractère aléatoire et ses performances incohérentes. Cela exclut les miss réguliers ou spécifiques à un pattern ou les [slider breaks](/wiki/Gameplay/Slider_break), qui sont généralement liés au niveau de compétence du joueur ou à la façon dont la beatmap est construite. Les chokes sont généralement causés par un stress mental excessif et une nervosité pendant la partie, ainsi que par une fatigue générale.
```

2021-09-23 08:57 UTC, Ganondorf-1 requested changes

2021-09-23 08:57 UTC, Ganondorf-1 commented on wiki/Glossary/Choke/fr.md
> +La caractéristique principale d'un choke est son caractère aléatoire et ses performances incohérentes. Cela exclut les miss réguliers ou spécifiques à un pattern ou les [slider breaks](/wiki/Gameplay
```suggestion
La caractéristique principale d'un choke est son caractère aléatoire accompagné d'une performance qui n'est pas constante. Cela exclut les miss réguliers ou spécifiques à un pattern ou les [slider breaks](/wiki/Gameplay/Slider_break), qui sont généralement liés au niveau de compétence du joueur ou à la façon dont la beatmap est construite. Les chokes sont généralement causés par un stress mental excessif et une nervosité pendant la partie, ainsi que par une fatigue générale.
```

2021-09-23 08:57 UTC, Ganondorf-1 commented on wiki/Glossary/Choke/fr.md
> +La caractéristique principale d'un choke est son caractère aléatoire et ses performances incohérentes. Cela exclut les miss réguliers ou spécifiques à un pattern ou les [slider breaks](/wiki/Gameplay
Pas très sûr de comment j'ai reformulé ça

2021-09-23 08:57 UTC, Ganondorf-1 commented on wiki/Glossary/Combo_fire/fr.md
> +Le combo fire a été désactivé le 5 mars 2013 en raison de problèmes de performance.
```suggestion
Le combo fire a été désactivé le 5 mars 2013 en raison de problèmes de performances.
```

2021-10-02 17:28 UTC, TPGPL approved these changes

2021-10-02 17:29 UTC, merged