Update fr.md
ppy/osu-wiki pull request #6167
Opened 2021-09-26 15:43 UTC by Krystool

Small corrections.

2021-09-26 15:45 UTC, DoryanR requested changes
The rest is good otherwise

2021-09-26 15:45 UTC, DoryanR commented on wiki/Internet_Relay_Chat/fr.md
> +*Pour plus d'informations, lire : [Internet Relay Chat (Wikipédia)](https://fr.wikipedia.org/wiki/Internet_Relay_Chat)*
```suggestion
*Pour plus d'informations : [Internet Relay Chat (Wikipédia)](https://fr.wikipedia.org/wiki/Internet_Relay_Chat)*
```

2021-09-26 15:51 UTC, peppy commented
Please update your pull request title to imply what file/section you're changing.

2021-09-26 15:54 UTC, Krystool commented
> Please update your pull request title to imply what file/section you're changing.

Solved @peppy

2021-09-26 15:59 UTC, DoryanR approved these changes

2021-09-27 14:05 UTC, TicClick approved these changes

2021-09-27 14:05 UTC, merged