Update BN / NAT Listing
ppy/osu-wiki pull request #6172
Opened 2021-09-28 17:57 UTC by StixyOsu

Tried updating all BN / NAT listings, since a bunch of changes weren't updated yet. Included all languages except the korean one for BNs, since this one hasn't been updated in a while. Hope I did everything right, in case I didn't let me know lol. First time doing this but I play on doing this more often if possible :)

2021-10-02 08:35 UTC, hikikuman requested changes
can you also change `Stelar` to `Lita-` (https://osu.ppy.sh/users/15205070, he changed his name a long time ago). it's on mania full bn.

2021-10-02 15:21 UTC, StixyOsu commented
Done @hikikuman :)

2021-10-04 19:26 UTC, TicClick approved these changes

2021-10-04 19:37 UTC, TicClick approved these changes

2021-10-04 19:38 UTC, merged

2021-10-04 19:40 UTC, TicClick commented
thanks for the help.

> Hope I did everything right, in case I didn't let me know

automated checks have failed for your PR, please see their status next time:
- [the failure](https://github.com/ppy/osu-wiki/runs/3795417959)
- [my fix](https://github.com/ppy/osu-wiki/pull/6172/commits/2fb8935d989c99f32d731665aab08babab66d98f)
- [explanation](https://osu.ppy.sh/wiki/en/osu%21_wiki/Maintenance#ci-checks)