Create Forums Stub
ppy/osu-wiki pull request #6225
Opened 2021-10-14 04:16 UTC by Gamingzone123

create stub for forums article ()

Have hit a block to writing the article, i cant think of how to adhere to the change req even with suggestions (on hold until inspiration hits...)

anyone is free to contiue where i left off

contributes to issue #3150 
project: https://github.com/ppy/osu-wiki/projects/3

TODO: address change requests

2021-10-30 23:07 UTC, TicClick requested changes
most if not all points from my early review still stand

2021-10-30 23:07 UTC, TicClick commented on wiki/Forum/en.md
> +  - forum
the tags don't need to duplicate the article's title

2021-10-30 23:07 UTC, TicClick commented on wiki/Forum/en.md
> +The forums are a place where the [osu!](/wiki/Disambiguation/osu!) community can discuss a variety of topics.
that's still too short, mind adding a few more sentences?

2021-10-30 23:07 UTC, TicClick commented on wiki/Forum/en.md
> +Forum -> Category (e.g; osu!) -> Section (e.g; development) -> Subforums (e.g; completed projects) -> Individual threads
what I wrote in the review was just a comment with my idea, it shouldn't be put as-is into the article

2021-10-30 23:07 UTC, TicClick commented on wiki/Forum/en.md
> +One of ther main functions of the forums is to assist with [beatmap moderation](/wiki/Modding) where users get feedback and help to improve their beatmaps.
this is not true anymore for a few years at least, all modding takes place in beatmap discussions

2021-11-07 06:16 UTC, Gamingzone123 commented
Have hit a block with writing the article, on hold for now

2021-12-04 12:39 UTC, Walavouchey commented
superseded by https://github.com/ppy/osu-wiki/pull/6454

2021-12-04 21:05 UTC, closed without merging