[JA] Add 'Code of conduct for modding and mapping'
ppy/osu-wiki pull request #6229
Opened 2021-10-14 14:36 UTC by baar-vendel

Proposal for the Japanese translation of the wiki page `Code of conduct for modding and mapping`, asked by VINXIS in August

2021-10-30 22:34 UTC, TicClick commented
@peppy could you please proofread this before merge if you have time?

2021-10-31 03:08 UTC, peppy requested changes

2021-10-31 03:09 UTC, peppy commented
I had a pending review I forgot to submit here, sorry!

Mostly just terminology standardisation. Reads very well otherwise. I've made recommendations to use english terms in line with how we write them on other wiki pages and crowdin.

2021-10-31 06:40 UTC, baar-vendel commented on wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping/ja.md
> +  - もしあなたが新規Modderであれば、恥ずかしがらずそう公言しましょう。コミュニティーの経験豊富なメンバーが正しい方向に導いてくれます。誰もがかつては新人で、あなたと同じ立場でした。
```suggestion
  - もしあなたが新規Modderであれば、恥ずかしがらずそう公言しましょう。コミュニティの経験豊富なメンバーが正しい方向に導いてくれます。誰もがかつては新人で、あなたと同じ立場でした。
```

2021-10-31 11:10 UTC, baar-vendel commented on wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping/ja.md
> +# Code of conduct for modding and mapping
```suggestion
# ModdingとMappingにおける行動規範
```

2021-10-31 11:12 UTC, baar-vendel commented on wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping/ja.md
> +**Code of conduct for modding and mapping**とは、osu!の[Mapping](/wiki/Beatmapping)と[Modding](/wiki/Modding)のエコシステム全体に適用されるルールとガイドラインからなる行動規範のことで、[コミュニティルール](/wiki/Rules)と[ランキング基準](/wiki/Ranking_Criteria
```suggestion
**ModdingとMappingにおける行動規範**とは、osu!の[Mapping](/wiki/Beatmapping)と[Modding](/wiki/Modding)のエコシステム全体に適用されるルールとガイドラインからなる行動規範のことで、[コミュニティルール](/wiki/Rules)と[ランキング基準](/wiki/Ranking_Criteria)の延長線上にあります。スレッドでのMappingとModdingの議論が、建設的かつ前向きで生産的な環境で行われるようにするため、全員が同じ規範を保つ必要があります。ModdingとMappingのエコシステムに参加する以上は、当規範に従わなければなりません。これらの規則を破ると[アカウントにペナルティが課される](/wiki/Silence)可能性があります。
```

2021-10-31 11:15 UTC, baar-vendel commented
Thank you for the review! I changed everything you said, and also translated the title.

2021-10-31 11:24 UTC, baar-vendel commented
@TicClick Fixed the issues above. What should I do next?

2021-10-31 12:36 UTC, TicClick commented
@baar-vendel I planned to merge it after 2+ weeks w/o review, but now that it's been reviewed I guess peppy will take over and merge it himself

2021-10-31 13:08 UTC, peppy approved these changes

2021-10-31 13:08 UTC, merged