[DE] add German translation for disambiguation-osu
ppy/osu-wiki pull request #6291
Opened 2021-10-29 22:12 UTC by The-Last-Cookie

Adds the German translation for the whole article under `wiki/Disambiguation/osu!/`

I discovered the [osu wiki status page](https://clayton.cc/osu-wiki-status/en) and saw that the German translation for this article was completely missing.

2021-11-09 13:57 UTC, FamousPig requested changes

2021-11-09 20:28 UTC, The-Last-Cookie commented on wiki/Disambiguation/osu!/de.md
> +- Das Spiel und seine Gemeinschaft
I also use `Community` later in the other edits of mine. This seems fine to me.

2021-11-09 20:33 UTC, FamousPig approved these changes

2021-11-11 17:29 UTC, TicClick approved these changes

2021-11-11 17:30 UTC, merged