add German translation for disambiguation-version
ppy/osu-wiki pull request #6301
Opened 2021-10-30 13:07 UTC by The-Last-Cookie

Adds the German translation for the article at `wiki/Disambiguation/Version`.

I'm not sure if there's a German word for `release stream`. My best guess was `Veröffentlichungsart`. If anyone has a more fitting idea, go and suggest it!

2021-11-08 09:43 UTC, respektive requested changes

2021-11-08 09:43 UTC, respektive commented on wiki/Disambiguation/Version/de.md
> +**Version** kann unterschiedliche Bedeutungen haben:
Would change this to stay consistent with the other disambiguation translations
```suggestion
**Version** kann Folgendes bedeuten:
```

2021-11-08 09:43 UTC, respektive commented on wiki/Disambiguation/Version/de.md
> +- Die Versionsnummer oder das Veröffentlichungsdatum eines osu!-Clients
```suggestion
- Die Buildnummer oder das Builddatum eines osu!-Clients
```

2021-11-08 09:43 UTC, respektive commented on wiki/Disambiguation/Version/de.md
> +- Die Veröffentlichungsart eines osu!-Clients (`Stable`, `Stable (Fallback)`, `Beta`, oder `Cutting Edge (Experimental)`)
staying consistent with in-game translation
```suggestion
- Die Updatequelle eines osu!-Clients (`Stable`, `Stable (Fallback)`, `Beta`, oder `Cutting Edge (Experimental)`)
```

2021-11-09 13:53 UTC, FamousPig approved these changes

2021-11-11 17:31 UTC, TicClick approved these changes

2021-11-11 17:32 UTC, merged