[FR] Update `Storyboard`, `Storyboard/Scripting`, Add `Storyboard/Scripting/Audio`, `Cheat Sheet`, `Commands`, `Compound_Commands`, `General_Rules`, `Objects`, `osu!_File_Toggles`, `Shorthand`, `Variables`
ppy/osu-wiki pull request #6307
Opened 2021-10-31 10:03 UTC by DoryanR

Translation of the following wiki pages:

- `Storyboard/Scripting/Audio`
- `Storyboard/Scripting/Cheat Sheet`
- `Storyboard/Scripting/Commands`
- `Storyboard/Scripting/Compound_Commands`
- `Storyboard/Scripting/General_Rules`
- `Storyboard/Scripting/Objects`
- `Storyboard/Scripting/osu!_File_Toggles`
- `Storyboard/Scripting/Shorthand`
- `Storyboard/Scripting/Variables`

Update of the translations of the following wiki pages:

- `Storyboard`
- `Storyboard/Scripting`

*Feel free to merge if the delay is too long for a review by a native.*

2021-10-31 10:08 UTC, DoryanR commented on wiki/Storyboard/Scripting/Cheat_Sheet/fr.md
> +***shorthand3*** : Cette notation peut être utilisée lorsque les valeurs de début et de fin de l'événement sont les mêmes.
```suggestion
Veuillez noter l'espace vide dans le champ de l'heure de fin - il s'agit de l'heure **requise**.

***shorthand3*** : Cette notation peut être utilisée lorsque les valeurs de début et de fin de l'événement sont les mêmes.
```

2021-10-31 10:08 UTC, DoryanR commented on wiki/Storyboard/Scripting/Commands/fr.md
> +Dans certains cas particuliers, divers [shorthands] (/wiki/Storyboard/Scripting/Shorthand) peuvent être utilisés.
```suggestion
Dans certains cas particuliers, divers [shorthands](/wiki/Storyboard/Scripting/Shorthand) peuvent être utilisés.
```

2021-10-31 10:08 UTC, DoryanR commented on wiki/Storyboard/Scripting/Shorthand/fr.md
> +Pour vous faciliter la vie, il existe trois cas de **raccourcis** lors de l'écriture des [commandes du storyboard] (/wiki/Storyboard/Scripting/Commands).
```suggestion
Pour vous faciliter la vie, il existe trois cas de **raccourcis** lors de l'écriture des [commandes du storyboard](/wiki/Storyboard/Scripting/Commands).
```

2021-10-31 10:08 UTC, DoryanR commented on wiki/Storyboard/fr.md
> +Les storyboards sont stockés dans les dossiers beatmap sous forme de fichiers [`.osb`](/wiki/osu!_File_Formats/Osb_(file_format)) autonomes ou d'extensions de la section `[Events]` d'un fichier [`.os
```suggestion
Les storyboards sont stockés dans les dossiers beatmap sous forme de fichiers [`.osb`](/wiki/osu!_File_Formats/Osb_(file_format)) autonomes ou d'extensions de la section `[Events]` d'un fichier [`.osu`](/wiki/osu!_File_Formats/Osu_(file_format)). De ce fait, il est possible de créer des storyboards différents pour les difficultés au sein d'une [beatmap](/wiki/Beatmap).
```

2021-10-31 10:12 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
> +- `(layer)` est la **[couche] (/wiki/Storyboard/Scripting/General_Rules) sur laquelle l'objet apparaît.** Les valeurs valides sont :
```suggestion
- `(layer)` est la **[couche](/wiki/Storyboard/Scripting/General_Rules) sur laquelle l'objet apparaît.** Les valeurs valides sont :
```

2021-11-12 18:08 UTC, Ganondorf-1 requested changes

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/fr.md
> +![](img/Sbpassing.png "Cette scène est montrée pendant le jeu Walkie Talkie Man ; cependant, elle n'est montrée que lorsque vous obtenez un Elite Beat 300.")
```suggestion
![](img/Sbpassing.png "Cette scène est montrée lorsque vous jouez Walkie Talkie Man ; cependant, elle n'est montrée que lorsque vous obtenez un Elite Beat 300.")
```

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/fr.md
> +![](img/Sbfailing.png "Ceci s'affiche lorsque vous avez raté ou obtenu un 50 dans le combo précédemment joué.")
```suggestion
![](img/Sbfailing.png "Ceci s'affiche si vous avez manqué un objet ou obtenu un 50 dans le combo précédemment joué.")
```

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/fr.md
> +Un **storyboard** (SB) est un arrière-plan animé personnalisé qui accompagne une [beatmap](/wiki/Beatmap), souvent à des fins décoratives et parfois pour le jeu. Un storyboard peut être composé d'à p
```suggestion
Un **storyboard** (SB) est un arrière-plan animé personnalisé qui accompagne une [beatmap](/wiki/Beatmap), souvent à des fins décoratives et parfois pour le gameplay. Un storyboard peut être composé d'à peu près n'importe quoi, mais il s'agit généralement d'effets visuels conçus pour rendre une map plus esthétique et plus distinctive pour les utilisateurs. Les storyboards s'inspirent des fonds animés que l'on trouve dans [Osu! Tatakae! Ouendan](/wiki/Disambiguation/Ouendan). Comme leur inspiration, les storyboards sont capables de s'adapter aux performances du joueur pendant la partie et d'afficher des éléments différents en fonction de ses performances.
```

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/fr.md
> +Les storyboards sont stockés dans les dossiers beatmap sous forme de fichiers [`.osb`](/wiki/osu!_File_Formats/Osb_(file_format)) autonomes ou d'extensions de la section `[Events]` d'un fichier [`.os
```suggestion
Les storyboards sont stockés dans les dossiers beatmap sous forme de fichiers [`.osb`](/wiki/osu!_File_Formats/Osb_(file_format)) ou d'extensions de la section `[Events]` d'un fichier [`.osu`](/wiki/osu!_File_Formats/Osu_(file_format)). De ce fait, il est possible de créer des storyboards différents pour chaque difficulté au sein d'une [beatmap](/wiki/Beatmap).
```

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/Cheat_Sheet/fr.md
> +**startscale** :  le facteur d'échelle au début de l'animation. **endscale** : le facteur d'échelle à la fin de l'animation.
```suggestion
**startscale** : le facteur d'échelle au début de l'animation. **endscale** : le facteur d'échelle à la fin de l'animation.
```

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/Commands/fr.md
> +Par exemple, pour faire disparaître un objet en 1 seconde (en commençant 1 seconde après le début de la map), attendre 2 secondes à demi-transparence, puis faire disparaître l'objet en 1 seconde, nou
```suggestion
Par exemple, pour faire disparaître un objet en 1 seconde (en commençant 1 seconde après le début de la beatmap), attendre 2 secondes à demi-transparence, puis faire disparaître l'objet en 1 seconde, nous écririons quelque chose comme suit :
```

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/General_Rules/fr.md
> +- Par défaut, le fond de prévisualisation (le fond que vous voyez dans Song Select) spécifié pour la map est placé sous toutes les autres couches. Toutefois, si vous faites référence à ce même fichie
```suggestion
- Par défaut, le fond de prévisualisation (le fond que vous voyez dans Song Select) spécifié pour la beatmap est placé sous toutes les autres couches. Toutefois, si vous faites référence à ce même fichier en tant qu'objet dans votre storyboard, il disparaîtra immédiatement après le chargement de la beatmap.
```

2021-11-12 18:08 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/General_Rules/fr.md
> +  - Il est courant que le fond d'écran de votre map soit le premier objet spécifié (en temps et en sprite), et que vous utilisiez la commande "fade out" (éclaircissement) pour "présenter" votre fond
```suggestion
  - Il est courant que le fond d'écran de votre beatmap soit le premier objet spécifié (en temps et en sprite), et que vous utilisiez la commande "fade out" (éclaircissement) pour "présenter" votre fond au public.
```

2021-11-16 22:24 UTC, TicClick approved these changes

2021-11-16 22:25 UTC, merged