[FR] Update `Twitter`
ppy/osu-wiki pull request #6308
Opened 2021-10-31 10:43 UTC by DoryanR

Proposal to update the French translation of the wiki page `Twitter`.

2021-11-08 11:05 UTC, Biokax requested changes
Is seems better like that I think

2021-11-08 11:05 UTC, Biokax commented on wiki/Twitter/fr.md
> +osu! possède plusieurs comptes Twitter, chacun servant des objectifs spécifiques. La plupart ont un trafic très faible mais permettent de vous tenir informé en dehors de l'écosystème d'osu!.
osu! possède plusieurs comptes Twitter, **ayant chacun** des objectifs spécifiques. La plupart ont **une activité** très faible mais permettent de vous tenir informé en dehors de l'écosystème d'osu!.

2021-11-08 11:41 UTC, DoryanR commented on wiki/Twitter/fr.md
> +osu! possède plusieurs comptes Twitter, chacun servant des objectifs spécifiques. La plupart ont un trafic très faible mais permettent de vous tenir informé en dehors de l'écosystème d'osu!.
C'est possible d'utiliser l'outil de suggestion pour proposer des changements ? Cela serait plus simple pour moi d'appliquer les changements. Merci d'avance.

Sinon l'outil c'est l'icône avec un ± dans une petite feuille, juste au cas où.

2021-11-08 12:36 UTC, Biokax commented on wiki/Twitter/fr.md
> +osu! possède plusieurs comptes Twitter, chacun servant des objectifs spécifiques. La plupart ont un trafic très faible mais permettent de vous tenir informé en dehors de l'écosystème d'osu!.
```suggestion
osu! possède plusieurs comptes Twitter, ayant chacun des objectifs spécifiques. La plupart ont une activité très faible mais permettent de vous tenir informé en dehors de l'écosystème d'osu!.
```

2021-11-08 12:37 UTC, Biokax commented on wiki/Twitter/fr.md
> +osu! possède plusieurs comptes Twitter, chacun servant des objectifs spécifiques. La plupart ont un trafic très faible mais permettent de vous tenir informé en dehors de l'écosystème d'osu!.
Je n'avais pas trouvé le bon bouton, désolé

2021-11-11 17:08 UTC, TicClick approved these changes

2021-11-11 17:08 UTC, merged