[DE] Update `Main Page`
ppy/osu-wiki pull request #6315
Opened 2021-11-01 13:30 UTC by The-Last-Cookie

Proposal to update the translation of the wiki main page to the latest version.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) (I'm a native myself)

2021-11-09 13:46 UTC, FamousPig requested changes

2021-11-09 13:46 UTC, FamousPig commented on wiki/Main_Page/de.md
> +Als Wegweiser in die Welt des Rhythmus, des Beats und der Blitzlichter hat osu! viel zu präsentieren. Lerne das Spiel in all seinen Einstellungs- und Konfigurationsmöglichkeiten bis hin zu technische
```suggestion
Als Wegweiser in die Welt des Rhythmus, des Beats und der Blitzlichter hat osu! viel zu präsentieren. Lerne das Spiel in all seinen Einstellungs- und Konfigurationsmöglichkeiten bis hin zu technischen Details, wie z. B. den verschiedenen Dateiformaten, besser kennen.
```

2021-11-09 13:46 UTC, FamousPig commented on wiki/Main_Page/de.md
> +Alle Beatmaps in osu! werden von kreativen Teilnehmern seiner aktiven Community erstellt. Wolltest du schon immer deine Lieblingsmusik mit anderen teilen, aber nie gewusst wie? Mache dich vertraut mi
```suggestion
Alle Beatmaps in osu! werden von kreativen Teilnehmern seiner aktiven Community erstellt. Wolltest du schon immer deine Lieblingsmusik mit anderen teilen, hast aber nie gewusst wie? Mache dich vertraut mit dem eingebauten Editor und den Möglichkeiten, die dieser bietet.
```

2021-11-09 13:46 UTC, FamousPig commented on wiki/Main_Page/de.md
> +[Turniere](/wiki/Tournaments) • [Beatmap Spotlights](/wiki/Beatmap_Spotlights) • [Veranstaltungen](/wiki/Contests) • [Mentorenprogramm](/wiki/Community_Mentorship_Program)
```suggestion
[Turniere](/wiki/Tournaments) • [Beatmap Spotlights](/wiki/Beatmap_Spotlights) • [Wettbewerbe](/wiki/Contests) • [Mentorenprogramm](/wiki/Community_Mentorship_Program)
```

2021-11-09 13:46 UTC, FamousPig commented on wiki/Main_Page/de.md
> +osu! würde nicht ohne die Hilfe von vielen Menschen existieren, die in der Entwicklung, Wartung und des Community-Managements tätig sind. Ihrer Mühen, Zeit und Hingabe ist es zu verdanken, dass das S
```suggestion
osu! würde nicht ohne die Hilfe von vielen Menschen existieren, die in der Entwicklung, Wartung und im Community-Management tätig sind. Ihrer Mühen, Zeit und Hingabe ist es zu verdanken, dass das Spiel weiterentwickelt wird.
```

2021-11-09 20:24 UTC, FamousPig submitted a review, later dismissed

2021-11-10 03:30 UTC, ZeroPyrozen commented on wiki/Main_Page/de.md
> +
Remove this line

2021-11-11 02:14 UTC, ZeroPyrozen approved these changes

2021-11-11 17:20 UTC, TicClick approved these changes

2021-11-11 17:21 UTC, merged