[FR] Add `osu!_wiki`, `Maintenance`, `Maintenance/List_of_maintainers`, Update `Contribution_guide`, `Best_practices`, `GitHub_Desktop`, `GitHub_Web_Interface`
ppy/osu-wiki pull request #6322
Opened 2021-11-03 19:06 UTC by DoryanR

Translation of the following wiki pages:

- `osu!_wiki`
- `osu!_wiki/Maintenance`
- `osu!_wiki/Maintenance/List_of_maintainers`

Update of the translations of the following wiki pages:

- `osu!_wiki/Contribution_guide/Best_practices`
- `osu!_wiki/Contribution_guide`
- `osu!_wiki/Contribution_guide/GitHub_Desktop`
- `osu!_wiki/Contribution_guide/GitHub_Web_Interface`

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-03 19:09 UTC, DoryanR commented on wiki/osu!_wiki/Contribution_guide/GitHub_Desktop/fr.md
> +- Lorsque vos modifications sont en dehors de la branche `master`, vous pouvez [les synchroniser en toute sécurité] (/wiki/osu!_wiki/Contribution_guide/Best_practices#synchronisation-d'un-fork) sans
```suggestion
- Lorsque vos modifications sont en dehors de la branche `master`, vous pouvez [les synchroniser en toute sécurité](/wiki/osu!_wiki/Contribution_guide/Best_practices#synchronisation-d'un-fork) sans conflits de fusion.
```

2021-11-03 19:09 UTC, DoryanR commented on wiki/osu!_wiki/Maintenance/List_of_maintainers/fr.md
> +
```suggestion
```

2021-11-03 19:09 UTC, DoryanR commented on wiki/osu!_wiki/fr.md
> +- Les utilisateurs sont encouragés à améliorer les articles existants et à en créer de nouveaux, mais une connaissance de base de [GitHub] (https://github.com) est attendue, ce qui augmente le seuil
```suggestion
- Les utilisateurs sont encouragés à améliorer les articles existants et à en créer de nouveaux, mais une connaissance de base de [GitHub](https://github.com) est attendue, ce qui augmente le seuil nécessaire pour entrer.
```

2021-11-14 17:07 UTC, Ganondorf-1 requested changes

2021-11-14 17:07 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
> +Toutes les discussions qui concernent le wiki en général, son développement et les changements d'articles, ont lieu dans le canal `#osu-wiki` du serveur [osu!dev](/wiki/osu!dev_Discord_server). Pour
```suggestion
Toutes les discussions qui concernent le wiki en général, son développement et les changements d'articles, ont lieu dans le salon de discussion `#osu-wiki` du serveur [osu!dev](/wiki/osu!dev_Discord_server). Pour savoir comment vous pouvez aider le osu! wiki, consultez les articles suivants :
```

2021-11-14 17:07 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
> +Les [premières tentatives](https://osu.ppy.sh/community/forums/posts/1175876) de création d'une base de connaissances structurée remontent à 2011, lorsque [peppy](/wiki/People/peppy) a mis en place u
```suggestion
Les [premières tentatives](https://osu.ppy.sh/community/forums/posts/1175876) de création d'une base de connaissances structurée remontent à 2011, lorsque [peppy](/wiki/People/peppy) a mis en place une instance de [MediaWiki](https://fr.wikipedia.org/wiki/MediaWiki) pour toute personne désirant participer. Au fil des ans, la maintenance et l'exploitation de MediaWiki se sont avérées difficiles et pénibles, et le [26 août 2016](https://discord.com/channels/188630481301012481/218677502141399041/218678017659109376) peppy et une équipe de bénévoles ont commencé le processus de migration du osu! wiki vers GitHub, où il réside à ce jour. Le wiki a depuis été intégré au nouveau site web d'osu! et a reçu des mises à jour techniques et visuelles essentielles à une bonne expérience utilisateur.
```

2021-11-14 17:07 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
> +Des traductions en différentes langues sont disponibles pour certains articles. Elles sont réalisées par les membres de la communauté eux-mêmes, et le choix de la langue n'est limité que par la [list
```suggestion
Des traductions en différentes langues sont disponibles pour certains articles. Elles sont réalisées par les membres de la communauté eux-mêmes, et le choix de la langue n'est limité que par la [liste de langues](/wiki/Article_styling_criteria/Formatting#locales) prises en charge par le site lui-même.
```

2021-11-14 17:07 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
> +Les articles sont composés selon les [critères de style](/wiki/Article_styling_criteria) du osu! wiki, ce qui signifie qu'ils sont rédigés dans un langage neutre et suivent des règles communes de for
```suggestion
Les articles sont composés selon les [critères de mise en forme d'article](/wiki/Article_styling_criteria) du osu! wiki, ce qui signifie qu'ils sont rédigés dans un langage neutre et suivent des règles communes de formatage et de conception. Certains articles informatifs servent de liste de questions fréquemment posées (FAQ) sur le sujet et utilisent un langage informel. Les traductions suivent le principe de parité du contenu et respectent les mêmes règles de formatage.
```

2021-11-17 00:23 UTC, TicClick approved these changes

2021-11-17 00:25 UTC, merged