[FR] Add `Modding/Forum_modding`, `Bubble`
ppy/osu-wiki pull request #6328
Opened 2021-11-06 12:11 UTC by DoryanR

Translation of the following wiki pages:

- `Modding/Forum_modding`
- `Modding/Bubble`

2021-11-06 12:34 UTC, DoryanR commented on wiki/Modding/Bubble/fr.md
> +L'étape suivante de l'[ancien système de classement](/wiki/Modding/Forum_modding) après une [proto-bubble](( /wiki/Modding/Proto-bubble), une bubble régulière signifie qu'une [beatmap](/wiki/Beatmap)
```suggestion
L'étape suivante de l'[ancien système de classement](/wiki/Modding/Forum_modding) après une [proto-bubble](/wiki/Modding/Proto-bubble), une bubble régulière signifie qu'une [beatmap](/wiki/Beatmap) est prête à être classée du point de vue du moddeur. Les beatmaps avec une bubble étaient éventuellement vérifiées par un autre membre de la BAT ou d'un BN et [classée](/wiki/Beatmap/Category#classée) ou [approuvée](/wiki/Beatmap/Category#approuvée) tant que des modifications mineures de la map étaient nécessaires.
```

2021-11-06 12:34 UTC, DoryanR commented on wiki/Modding/Bubble/fr.md
> +Le 3 octobre 2010, la MAT a reçu l'autorisation d'utiliser l'icône de bubble, aux côtés de la BAT. Cela a essentiellement déprécié les [proto-bubbles] (/wiki/Modding/Proto-bubbles), et les deux équip
```suggestion
Le 3 octobre 2010, la MAT a reçu l'autorisation d'utiliser l'icône de bubble, aux côtés de la BAT. Cela a essentiellement déprécié les [proto-bubbles](/wiki/Modding/Proto-bubbles), et les deux équipes ont principalement utilisé des bubbles ordinaires depuis.
```

2021-11-06 12:34 UTC, DoryanR commented on wiki/Modding/Forum_modding/fr.md
> +Ensuite, le système de discussion des beatmap et le [code de conduite pour le modding et le mapping] (/wiki/Rules/Code_de_conduite_pour_le_modding_et_le_mapping#making-a-mod-post) ont été développés
```suggestion
Ensuite, le système de discussion des beatmap et le [code de conduite pour le modding et le mapping](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping#créer-un-mod-post) ont été développés et mis à disposition pour restructurer le modding et en faire une expérience plus agréable pour toutes les personnes impliquées :
```

2021-11-08 19:52 UTC, Biokax requested changes

2021-11-08 19:52 UTC, Biokax commented on wiki/Modding/Bubble/fr.md
> +Dans les deux cas, l'icône du fil de discussion de la beatmap était définie comme une popped bubble (![Icône de la Popped bubble](/wiki/shared/icon/bubble-pop.gif)). Si une bubble était éclatée manue
```suggestion
Dans les deux cas, l'icône du fil de discussion de la beatmap était définie comme une popped bubble (![Icône de la Popped bubble](/wiki/shared/icon/bubble-pop.gif)). Si une bubble était éclatée manuellement, il était supposé que les membre de la BAT ou de la MAT qui avait placé l'icône s'assurerait que les modifications nécessaires étaient apportées à la map avant qu'elle ne continue dans le processus de classement.
```
```suggestion
Dans les deux cas, l'icône du fil de discussion de la beatmap était définie comme une popped bubble (![Icône de la Popped bubble](/wiki/shared/icon/bubble-pop.gif)). Si une bubble était éclatée manuellement, il était supposé que les membres de la BAT ou de la MAT qui avait placé l'icône s'assureraient que les modifications nécessaires étaient apportées à la map avant qu'elle ne continue dans le processus de classement.
```

2021-11-08 19:52 UTC, Biokax commented on wiki/Modding/Forum_modding/fr.md
> +**Forum modding**, également connu sous le nom de *Modding v1*, est un nom familier du système de [modding](/wiki/Modding) et de classement basé sur le forum qui a été principalement utilisé jusqu'au
```suggestion
**Forum modding**, également connu sous le nom de *Modding v1*, est un nom familier du système de [modding](/wiki/Modding) et de classement basé sur le forum qui a été principalement utilisé jusqu'au [4 novembre 2017](https://osu.ppy.sh/community/forums/topics/650961?n=7), date à laquelle toutes les [beatmaps](/wiki/Beatmap) nouvelles et inactifs sont passés en [discussions d'une beatmap](/wiki/Beatmap_Discussion) par défaut.
```
```suggestion
**Forum modding**, également connu sous le nom de *Modding v1*, est un nom familier du système de [modding](/wiki/Modding) et de classement basé sur le forum qui a été principalement utilisé jusqu'au [4 novembre 2017](https://osu.ppy.sh/community/forums/topics/650961?n=7), date à laquelle toutes les [beatmaps](/wiki/Beatmap) nouvelles et inactives sont passées en [discussions d'une beatmap](/wiki/Beatmap_Discussion) par défaut.
```

2021-11-12 17:36 UTC, DoryanR commented
@Biokax can you recheck please ?

2021-11-12 19:54 UTC, Biokax requested changes

2021-11-12 19:54 UTC, Biokax commented on wiki/Modding/Forum_modding/fr.md
> +- ![](/wiki/shared/icon/bubble-pop.gif) **[Bubble pop](/wiki/Modding/Bubble#bubble-pop)** : la beatmap avait des problèmes qui l'empêchaient d'être classé après avoir reçu une bulle.
```suggestion
- ![](/wiki/shared/icon/bubble-pop.gif) **[Bubble pop](/wiki/Modding/Bubble#bubble-pop)** : la beatmap avait des problèmes qui l'empêchaient d'être classé après avoir reçu une bubble.
```

2021-11-26 16:24 UTC, TicClick approved these changes
merging with the assumption that one review was enough

2021-11-26 16:24 UTC, merged