[FR] Create `osu!stream`
ppy/osu-wiki pull request #6330
Opened 2021-11-06 22:08 UTC by geshii

o/, restarting #5744 
Sorry for being inactive for so long, had family issues and stuff to do so couldn't work on my PR

2021-11-08 11:27 UTC, Biokax requested changes

2021-11-08 11:27 UTC, Biokax commented on wiki/osu!stream/fr.md
> +osu!stream ne prend pas en charge les beatmaps classiques d'osu!. Au lieu de cela, les beatmaps sont créées par une équipe spéciale de mappeurs pour tirer parti des nouveaux éléments et respecter un
un niveau de normes plus strictes.

2021-11-08 11:27 UTC, Biokax commented on wiki/osu!stream/fr.md
> +- Appuyez sur le symbole osu! et vous devriez être dirigé vers le menu principal (ou le tutoriel si c'est la première fois)
not sure about this one
>et vous devriez être redirigé vers le menu principal

2021-11-08 11:27 UTC, Biokax commented on wiki/osu!stream/fr.md
> +Verrouillé par défaut et ne pouvant être déverrouillé qu'en terminant le mode Stream de la chanson avec un A ou mieux, le mode Expert est destiné aux joueurs qui veulent un plus grand défi. Dans ce m
Verrouillée par défaut et ne pouvant être déverrouillée

2021-11-12 17:33 UTC, geshii commented on wiki/osu!stream/fr.md
> +Verrouillé par défaut et ne pouvant être déverrouillé qu'en terminant le mode Stream de la chanson avec un A ou mieux, le mode Expert est destiné aux joueurs qui veulent un plus grand défi. Dans ce m
@Biokax tu peux directement request les changements au lieu de les suggérer stp :v ?

2021-11-12 19:50 UTC, Biokax requested changes

2021-11-12 19:50 UTC, Biokax commented on wiki/osu!stream/fr.md
> +- Appuyez sur le symbole osu! et vous devriez être dirigé vers le menu principal (ou le tutoriel si c'est la première fois)
```suggestion
- Appuyez sur le symbole osu! et vous devriez être redirigé vers le menu principal (ou le tutoriel si c'est la première fois)
```

2021-11-12 19:50 UTC, Biokax commented on wiki/osu!stream/fr.md
> +Verrouillé par défaut et ne pouvant être déverrouillé qu'en terminant le mode Stream de la chanson avec un A ou mieux, le mode Expert est destiné aux joueurs qui veulent un plus grand défi. Dans ce m
```suggestion
Verrouillée par défaut et ne pouvant être déverrouillée qu'en terminant le mode Stream de la chanson avec un A ou mieux, le mode Expert est destiné aux joueurs qui veulent un plus grand défi. Dans ce mode, le joueur dispose d'une barre de vie pleine et doit la conserver jusqu'à la fin de la chanson. Le fait de le terminer ne débloquera rien, si ce n'est le droit de se vanter.
```

2021-11-19 09:41 UTC, DoryanR requested changes
Pour que la PR puissent être merge, et pour ne pas refaire tout le boulot après, il faudrait que les modifications faites sur #6360 soit faite.
Après ça je ferais peut être un review si j'ai du temps.

2021-11-29 09:28 UTC, DoryanR commented
@geshii ou en est tu ? Si vraiment tu arrive pas à finir je peut m'occuper de finir au pire des cas.

2021-11-29 18:44 UTC, Biokax requested changes

2021-11-29 18:44 UTC, Biokax commented on wiki/osu!stream/fr.md
> +  - Il est conseillé de télécharger d'abord les packs qui ne coûtent pas d'argent. Les packs gratuits ont l'étiquette "FREE" au lieu de l'étiquette de coût "USD$".
```suggestion
  - Il est recommandé de télécharger d'abord les packs qui ne coûtent pas d'argent. Les packs gratuits ont l'étiquette "FREE" au lieu de l'étiquette de coût "USD$".
```

2021-11-29 18:44 UTC, Biokax commented on wiki/osu!stream/fr.md
> +  - Si le cercle a été relâché avant qu'il n'explose, le multiplicateur de combo sera remis à 0, mais le Hold circle n'entraînera pas un échec tant que le joueur aura celui-ci.
```suggestion
  - Si le cercle a été relâché avant qu'il n'explose, le multiplicateur de combo sera remis à 0, mais le Hold circle n'entraînera pas un miss à partir du moment où le joueur l'a touché.
```

2021-11-29 18:44 UTC, Biokax commented on wiki/osu!stream/fr.md
> +  - Si vous tapez dessus très, très tôt, l'objet va trembler. Techniquement, il ne se passe rien, si ce n'est que l'on peut voir que l'objet a été touché trop tôt.
```suggestion
  - Si vous tapez dessus trop tôt, l'objet va trembler, on parle ici d'un [Notelock](https://osu.ppy.sh/wiki/fr/Gameplay/Notelock). Techniquement, il ne se passe rien, si ce n'est que l'on peut voir que l'objet a été touché trop tôt.
```

2021-11-29 18:44 UTC, Biokax commented on wiki/osu!stream/fr.md
> +- Default. **Lifebar will not drain at all while playing**.
```suggestion
- Par défaut, **la barre de vie ne se vide pas tant que l'on joue**.
```

2021-11-29 18:46 UTC, Biokax commented on wiki/osu!stream/fr.md
> +- Un échec si l'on ne parvient pas à remplir le compteur indiqué de part et d'autre du spinner.
```suggestion
- Un miss si l'on ne parvient pas à remplir le compteur indiqué afin de valider le spinner.
```

2021-11-29 18:50 UTC, Biokax commented
certaines phrases manquent de sens, il faudrait encore au moins une review de plus par une autre personne pour voir si certaines de ces phrases ont été loupés.

2021-11-29 20:29 UTC, DoryanR requested changes
Sincerely there are too many things that need to be changed:

- I did say to check for conformity with #6360, which was done, but only halfway. A lot of things were not up to date with the PR, so I proposed the changes to make it so.
- It is necessary to update the links of the external links (Wikipedia in this case), it is a thing which is easily forgotten, but nevertheless essential.
- Think to reread you, because there are so many errors that could have been corrected with a complete rereading.

All these points will save you a lot of time during the review, in addition to the tips that are described in [the contribution guide](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_wiki/Contribution_guide/fr.md#auto-contr%C3%B4le)

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- **Le jugement des sliders dépend de la précision du tapotement initial**.
```suggestion
- **Le jugement des sliders dépend de la précision de la frappe initial**.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - Un 300 si vous réussissez à obtenir tous les ticks du slider et un tapotement initial précis.
```suggestion
  - Un 300 pour avoir réussi à obtenir tous les ticks du slider et une frappe initiale précise.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - Un 100 si au moins la moitié d'entre eux avec un tapotement initial considérable.
```suggestion
  - Un 100 si au moins la moitié des sliders parts ont été frappés par une frappe initiale assez précise.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - 50 si vous n'avez pas réussi à atteindre ne serait-ce qu'un seul des ticks ou le tapotement initial.
```suggestion
  - Un 50 pour avoir réussi à toucher ne serait-ce qu'un seul des ticks ou la frappe initiale.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Un miss si vous n'avez pas fait le curseur.
```suggestion
- Un miss si vous n'avez pas fait le slider.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Un spinner terminé avec succès.
```suggestion
- Des frappes sur un cercle.
- Le début, la fin et chaque hold tick d'un hold circle.
- Le début, la fin et chaque tick d'un slider.
- La réalisation d'un spinner.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Impossibilité de toucher simultanément les beats connectés. (En toucher un, et pas l'autre)
```suggestion
- Impossibilité de toucher simultanément les connected beats. (En toucher l'un, et pas l'autre)
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Manquer le début d'un slider ou le tic-tac d'un slider.
```suggestion
- Manquer le début d'un slider ou le tick d'un slider.
```

Ça je sais que c'est du Google Traduction, car ça m'a déjà sorti ça quand je cherchais une traduction pour ce terme.

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Impossible de remplir la jauge d'un spinner avec un statut clair.
```suggestion
- Impossible de remplir la jauge d'un spinner avec le statut clear.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +![](img/Os-Grade.jpg "Ecran des grades")
```suggestion
![](img/Os-Grade.jpg "Écran des grades")
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- S = Over 90% de précision
```suggestion
- S = Une précision de plus de 90 %
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- A = Over 80% de précision
```suggestion
- A = Une précision de plus de 80%
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- B = Over 70% de précision
```suggestion
- B = Une précision de plus de 70%
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- C = Over 60% de précision
```suggestion
- C = Une précision de plus de 60%
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- D = Le reste.
```suggestion
- D = Tout le reste
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +Contrairement à osu !, la barre de vie est différente dans osu!stream car elle est basée sur le mode de jeu.
```suggestion
Contrairement à osu!, la barre de vie est différente dans osu!stream car elle est basée sur le mode de jeu.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +En **Mode facile, la barre de vie est complètement supprimée**.
```suggestion
En **Mode Easy, la barre de vie est complètement supprimée**.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +![](img/Os-SUN.jpg "Exemple de Stream up! depuis une difficulté normale.")
```suggestion
![](img/Os-SUN.jpg "Exemple de Stream up! depuis une difficulté Normal.")
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +En **Mode Stream** cependant, le joueur reçoit **trois barres de vie et le joueur commence avec la deuxième barre de vie à moitié remplie au départ**. Le joueur (gagne/perd) la barre de vie par un me
```suggestion
En **Stream Mode**, le joueur dispose de trois barres de vie et le joueur commence avec la deuxième barre de vie à moitié remplie au départ. Les joueurs se déplacent entre ces barres de vie grâce aux systèmes **Stream Up!** et **Stream Down!**, qui s'activent lorsqu'ils remplissent la barre de vie ou la vident complètement. Après une annonce, le jeu passe au nouveau "flux" en changeant l'arrière-plan et en passant de manière transparente à une difficulté supérieure ou inférieure de la beatmap, ainsi qu'en changeant de barre de vie. Lorsqu'un Stream Down! se produit, le joueur bénéficie d'une invincibilité temporaire pendant que la barre de vie passe à celle correspondant à la difficulté inférieure.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Default. **Lifebar will not drain at all while playing**.
```suggestion
```

N'apparait pas dans la version anglaise, et je vois pas ce que ça fait la d'ailleurs

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +En **Mode Expert, une barre de vie complète est présente**.
```suggestion
En **Mode Expert, une seule barre de vie complète est utilisée à la place**.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +En termes d'obtention de vie pour la barre de vie, cela est expliqué comme ci-dessous.
```suggestion
Ce qui suit remplit la barre de vie :
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +
```suggestion
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - Compléter correctement la ou les bulles du Spinner et du Hold.
```suggestion
- Compléter les spinners et les Hold Bubbles.
- Frapper un osu!, gold good!, green good!, 300, ou un 100, 
  - Pour les cercles, les meilleurs jugements remplissent davantage la barre de vie. Le dernier cercle frappé d'une combinaison de couleurs donne plus de vie.
  - Pour les sliders, la barre de vie est remplie en fonction du nombre de parts réalisées, une fois le slider terminé.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +Le joueur perd de la vie :
```suggestion
Ce qui suit vide la barre de vie :
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Ne pas faire tourner le spinner.
```suggestion
- Recevoir un 50.
- Manquer un objet ou un slider.
- Ne pas rester dans le follow circle d'un slider.
- Ne pas tenir une Hold Bubble jusqu'à ce qu'elle explose.
- Ne pas faire tourner un spinner.
- Ne pas terminer un spinner avec le message "Clear".
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Par défaut. **La barre de vie ne se vide pas du tout pendant le jeu.
```suggestion
Contrairement aux autres versions d'osu!, la barre de vie ne se vide pas toute seule.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +### Pourquoi (insérer ici toute chanson protégée par le droit d'auteur) n'est-elle pas incluse ?
```suggestion
### Pourquoi (insérer ici toute musique protégée par le droit d'auteur) n'est-elle pas incluse ?
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +En raison de la difficulté d'obtenir une licence pour ladite chanson.
```suggestion
En raison de la difficulté d'obtenir une licence pour cette dernière.
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +Rendez-vous dans la section "Store" du jeu ou appuyez sur "Télécharger plus de chansons..." dans la section "Play".
```suggestion
Rendez-vous dans la section "Store" du jeu ou appuyez sur le bouton "Download more songs..." dans la section "Play".
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- [Post de Blog](https://blog.ppy.sh/osu-stream-2020-release/)
```suggestion
- [Billet de blog](https://blog.ppy.sh/osu-stream-2020-release/)
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +### Crédits?
```suggestion
### Crédits ?
```

2021-11-29 20:29 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +## Links
```suggestion
## Liens
```

2021-11-30 12:14 UTC, Biokax commented on wiki/osu!stream/fr.md
> +| **HitValue** | Number of misses \* 0 + Number of 50s \* 1 + Number of 100s * 2 + Number of 300s \* 4) |
Pourquoi être venu en anglais sur cette partie là ?

2021-11-30 12:28 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +| **HitValue** | Number of misses \* 0 + Number of 50s \* 1 + Number of 100s * 2 + Number of 300s \* 4) |
J'hésite à traduire les formules, surtout dans la première colonne vu que c'est une variable, au pire ce qui ce trouve entre parenthèses je sais pas trop non plus, j'ai pas envie d'altérer la formule en elle même.

2021-11-30 12:52 UTC, geshii commented on wiki/osu!stream/fr.md
> +| **HitValue** | Number of misses \* 0 + Number of 50s \* 1 + Number of 100s * 2 + Number of 300s \* 4) |
On peut laisser en français, ou en anglais. Je vois pas de problème majeur a faire de tel, donc comme vous voulez

2021-11-30 17:26 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +| **HitValue** | Number of misses \* 0 + Number of 50s \* 1 + Number of 100s * 2 + Number of 300s \* 4) |
Non je crois pas qu'il soit possible de simuler ça, doit bien y avoir un moyen mais je pense que c'est trop complexe, autant laisser comme ça pour le moment, au pire on modifiera en temps voulu

2021-11-30 17:40 UTC, DoryanR requested changes

2021-11-30 17:40 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - Pour les sliders, la barre de vie est remplie en fonction du nombre de parts réalisées, une fois le slider terminé.
```suggestion
Ce qui suit remplit la barre de vie : 

- Compléter les spinners et les Hold Bubbles.
- Frapper un osu!, gold good!, green good!, 300, ou un 100, 
  - Pour les cercles, les meilleurs jugements remplissent davantage la barre de vie. Le dernier cercle frappé d'une combinaison de couleurs donne plus de vie.
  - Pour les sliders, la barre de vie est remplie en fonction du nombre de parts réalisées, une fois le slider terminé.
```

2021-11-30 17:40 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - Si vous tapez dessus trop tôt, l'objet va trembler, on parle ici d'un [Notelock](https://osu.ppy.sh/wiki/fr/Gameplay/Notelock). Techniquement, il ne se passe rien, si ce n'est que l'on peut voir
```suggestion
  - Si vous tapez dessus trop tôt, l'objet va trembler, on parle ici d'un [Notelock](/wiki/Gameplay/Notelock). Techniquement, il ne se passe rien, si ce n'est que l'on peut voir que l'objet a été touché trop tôt.
```

2021-12-01 17:59 UTC, DoryanR approved these changes

2021-12-01 20:56 UTC, Ganondorf-1 requested changes

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Si vous êtes invité à saisir votre identifiant Apple et votre mot de passe, faites le.
```suggestion
  - Si vous êtes invité à saisir votre identifiant Apple et votre mot de passe, faites-le.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Il est suggéré de lire également la section "Ajouter des Beatmaps" pour obtenir le dernier pack de chansons gratuites. Le téléchargement actuel ne contient que 2 musiques.
```suggestion
  - Il est suggéré de lire également la section "Ajouter des beatmaps" pour obtenir le dernier pack de musiques gratuites. Le téléchargement actuel ne contient que 2 musiques.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +## Ajouter des Beatmaps
```suggestion
## Ajouter des beatmaps
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Appuyez sur le symbole d'osu! et vous devriez être redirigé vers le menu principal (ou le tutoriel si c'est la première fois)
```suggestion
- Appuyez sur le symbole d'osu! et vous devriez être redirigé vers le menu principal (ou le tutoriel si c'est la première fois).
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Sinon, allez dans "Play" et appuyez sur "Download more songs!"
```suggestion
  - Sinon, allez dans "Play" et appuyez sur "Download more songs!".
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Il est suggéré de lire également la section "Ajouter des Beatmaps" pour obtenir le dernier pack de chansons gratuites. Le téléchargement actuel ne contient que 2 musiques.
"Ajouter des beatmaps" est-il écrit en français ? Étant donné que les boutons mentionnés ci-dessous sont écrits en anglais, je doute

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Il est recommandé de télécharger d'abord les packs qui ne coûtent pas d'argent. Les packs gratuits ont l'étiquette "FREE" au lieu de l'étiquette de coût "USD$".
Je vois pas cette info sur l'article anglais, elle a été rajoutée ?

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Le timer circulaire est remplacé et déplacé vers le bas avec une petite ligne de bordure qui est colorée en fonction de la précision du jeu. \[Bottom(Long)\]
```suggestion
- Le timer circulaire est remplacé et déplacé vers le bas avec une petite ligne de bordure qui est colorée en fonction de la précision de la partie. \[Bottom(Long)\]
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- **Le timing moyen** est indiqué sur la page des notes.
```suggestion
- **Le timing moyen** est indiqué sur l'écran de résultat.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Les anciens enregistrements et replays ne peuvent pas être sauvegardés.
```suggestion
- Les anciens scores et replays ne peuvent pas être sauvegardés.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Les deux cercles transparents qui apparaissent dans le jeu ont été créés pour aider les débutants à savoir quand frapper les objets.
```suggestion
- Les deux cercles transparents qui apparaissent en jeu ont été créés pour aider les débutants à savoir quand toucher les objets.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Il indique la méthode suggérée pour aborder la conception de la beatmap avec perfection.
```suggestion
  - Cela indique la méthode suggérée pour aborder la conception de la beatmap avec perfection.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Les Hold circle demandent au joueur de maintenir le cercle jusqu'à ce qu'il "explose".
```suggestion
- Les Hold circles demandent au joueur de maintenir le cercle jusqu'à ce qu'il "explose".
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- La précision est déterminée par le début ou la fin du clic et le temps de maintien.
```suggestion
- La précision est déterminée selon le timing du joueur (touché tôt ou tard). Elle dépendra également de si le joueur l'a tenu jusqu'au bout ou non.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- La précision est déterminée par le début ou la fin du clic et le temps de maintien.
La deuxième phrase a peut-être besoin de rewording

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +Le mode Easy permet aux nouveaux joueur de s'habituer au gameplay d'osu!stream. Le jeu est considérablement plus lent pour que les nouveaux joueurs comprennent le déroulement et le timing des frappes
```suggestion
Le mode Easy permet aux nouveaux joueur de s'habituer au gameplay d'osu!stream. Le jeu est considérablement plus lent pour que les nouveaux joueurs comprennent le déroulement et le timing. Il n'y a pas de barre de vie et le mode Easy ne débloque pas le mode Expert.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +#### Easy
```suggestion
#### Mode Easy
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +Le mode Stream est un mode exclusif à osu!stream. Dans ce mode, les joueurs commencent avec une barre de vie "2nd" à moitié remplie et un réglage de difficulté normal. Le joueur doit ensuite la rempl
```suggestion
Le mode Stream est un mode exclusif à osu!stream. Dans ce mode, les joueurs commencent avec une "deuxième" barre de vie à moitié remplie et un réglage de difficulté normal. Le joueur doit ensuite la remplir complètement pour déclencher le mode "Stream Up!", qui augmente la difficulté (en ajoutant des objets et en passant à la difficulté Hard de la beatmap), mais qui reste nettement moins difficile que le mode Expert. Lorsque les joueurs entrent dans le mode "Stream Up!", une nouvelle barre de vie est émise et "Stream Down!" se déclenche si cette barre de vie est épuisée, ce qui ramène à la difficulté Normal ou Easy et à la barre de vie précédente.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +Notez que le joueur **doit obtenir au moins le rang A (>80% de précision) dans ce mode afin de débloquer le mode Expert de la chanson**. Une précision inférieure à 80 %, même en full-combo, ne compte
```suggestion
Notez que le joueur **doit obtenir au moins le rang A (>80% de précision) dans ce mode afin de débloquer le mode Expert de la musique**. Une précision inférieure à 80 %, même en full-combo, ne compte pas comme un rang A (elle sera comptée comme un rang B, comme d'habitude).
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +Le score donné par chaque note et la fin d'un slider est calculé avec la formule suivante :
```suggestion
Le score donné par chaque cercle et la fin d'un slider est calculé avec la formule suivante :
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +En outre, chaque tick de début, de fin et de répétition du slider rapporte 30 points et chaque tour d'un spinner rapporte 100 points.
```suggestion
En outre, chaque début, fin et répétition de slider rapporte 30 points et chaque tour d'un spinner rapporte 100 points.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Un cercle de 300, 100 ou 50 est attribué à partir d'une frappe normale, selon la précision de la frappe.
```suggestion
- Un score de 300, 100 ou 50 sera attribué selon la précision avec laquelle le joueur appuyé sur un cercle normal.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Un miss est donné si un cercle a été frappé trop tôt ou n'a pas été frappé du tout.
```suggestion
- Un miss est donné si un cercle a été touché trop tôt ou n'a pas été touché du tout.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Si vous tapez dessus trop tôt, l'objet va trembler, on parle ici d'un [Notelock](/wiki/Gameplay/Notelock). Techniquement, il ne se passe rien, si ce n'est que l'on peut voir que l'objet a été tou
```suggestion
  - Si vous le touchez trop tôt, l'objet va trembler, on parle ici d'un [Notelock](/wiki/Gameplay/Notelock). Techniquement, il ne se passe rien, si ce n'est que l'on peut voir que l'objet a été touché trop tôt.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Le jugement du hold circle dépend de la frappe initial et du temps de maintien avant l'explosion.
```suggestion
- Le jugement du hold circle dépend de la précision avec laquelle il a été touché et du temps de maintien avant l'explosion.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - 300 si c'est fait parfaitement.
```suggestion
  - 300 si réalisé parfaitement.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - 100 pour une prise initiale moins précise et une tenue correcte.
```suggestion
  - 100 pour avoir touché moins précisément et un maintien correct.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - 50 pour au moins le toucher.
```suggestion
  - 50 pour au moins l'avoir touché
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Le multiplicateur est remis à zéro si les cercles n'ont pas été tenus correctement et un miss pour ne pas être tenus du tout.
```suggestion
  - Le multiplicateur est remis à zéro si les cercles n'ont pas été tenus correctement et donnent un miss s'ils n'ont pas été tenus du tout.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- **Le jugement des sliders dépend de la précision de la frappe initial**.
```suggestion
- **Le jugement des sliders dépend de la précision avec laquelle le slider a été touché**.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Un 300 pour avoir réussi à obtenir tous les ticks du slider et une frappe initiale précise.
```suggestion
  - Un 300 pour avoir réussi à obtenir tous les ticks du slider et pour avoir touché le début du slider avec précision.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Un 100 si au moins la moitié des sliders parts ont été frappés par une frappe initiale assez précise.
```suggestion
  - Un 100 si au moins la moitié des parties du slider ont été obtenues tout en ayant touché le début du slider assez précisément.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Un 50 pour avoir réussi à toucher ne serait-ce qu'un seul des ticks ou la frappe initiale.
```suggestion
  - Un 50 pour avoir réussi à toucher ne serait-ce qu'un seul des ticks ou le début du slider.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- **Cliquer sur un slider trop tôt** n'est pas considéré comme un miss, mais **réinitialise le multiplicateur de score à 0**.
```suggestion
- **Toucher un slider trop tôt** n'est pas considéré comme un miss, mais **réinitialise le multiplicateur de score à 0**.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Un miss si vous n'avez pas fait le slider.
```suggestion
- Un miss si vous n'avez pas touché le slider du tout.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Des frappes sur un cercle.
```suggestion
- Toucher un cercle.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Manquer un hit circle.
```suggestion
- Manquer un cercle.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Impossibilité de toucher simultanément les connected beats. (En toucher l'un, et pas l'autre)
```suggestion
- Ne pas réussir à toucher simultanément les connected beats. (En toucher l'un, et pas l'autre)
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Manquer le début d'un slider ou le tick d'un slider.
```suggestion
- Manquer le début d'un slider ou un tick d'un slider.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Impossible de remplir la jauge d'un spinner avec le statut clear.
```suggestion
- Ne pas réussir à remplir la jauge d'un spinner avec le statut clear.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +### Life meter
```suggestion
### Barre de vie
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +En **Stream Mode**, le joueur dispose de trois barres de vie et le joueur commence avec la deuxième barre de vie à moitié remplie au départ. Les joueurs se déplacent entre ces barres de vie grâce aux
```suggestion
En **Stream Mode**, le joueur dispose de trois barres de vie et le joueur commence avec la deuxième barre de vie à moitié remplie au départ. Les joueurs se déplacent entre ces barres de vie grâce aux systèmes **Stream Up!** et **Stream Down!**, qui s'activent lorsqu'ils remplissent la barre de vie ou la vident complètement. Après une annonce, le jeu passe au nouveau "stream" en changeant l'arrière-plan et en passant de manière transparente à une difficulté supérieure ou inférieure de la beatmap, ainsi qu'en changeant de barre de vie. Lorsqu'un Stream Down! se produit, le joueur bénéficie d'une invincibilité temporaire pendant que la barre de vie passe à celle correspondant à la difficulté inférieure.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +- Frapper un osu!, gold good!, green good!, 300, ou un 100,
```suggestion
- Obtenir un osu!, gold good!, green good!, 300, ou un 100, 
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Pour les cercles, les meilleurs jugements remplissent davantage la barre de vie. Le dernier cercle frappé d'une combinaison de couleurs donne plus de vie.
```suggestion
  - Pour les cercles, les meilleurs jugements remplissent davantage la barre de vie. Le dernier cercle touché d'une combinaison de couleurs donne plus de vie.
```

2021-12-01 20:56 UTC, Ganondorf-1 commented on wiki/osu!stream/fr.md
> +  - Pour les sliders, la barre de vie est remplie en fonction du nombre de parts réalisées, une fois le slider terminé.
```suggestion
  - Pour les sliders, la barre de vie est remplie en fonction du nombre de parties touchées, une fois le slider terminé.
```

2021-12-04 10:59 UTC, DoryanR commented
Je vais refaire un dernier check aussi dans la journée, histoire d'être sur.

2021-12-04 17:51 UTC, DoryanR requested changes

2021-12-04 17:51 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +[osu!stream a été élaboré dans osu!monthly \#5 avec une interview.](https://osu.ppy.sh/community/forums/topics/59924)
```suggestion
[osu!stream a été élaboré dans osu!monthly \#5 après une interview](https://osu.ppy.sh/community/forums/topics/59924)
```

2021-12-04 17:51 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - Il est suggéré de lire également la section "Ajouter des Beatmaps" pour obtenir le dernier pack de chansons gratuites. Le téléchargement actuel ne contient que 2 musiques.
C'est la section de l'article que l'on évoque ici.

2021-12-04 17:51 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +- Allez sur [ce lien et téléchargez osu!stream](http://itunes.apple.com/us/app/osu!stream/id436952197?ls=1&mt=8)
```suggestion
- Allez sur [ce lien](http://itunes.apple.com/us/app/osu!stream/id436952197?ls=1&mt=8) et téléchargez osu!stream
```

2021-12-04 17:51 UTC, DoryanR commented on wiki/osu!stream/fr.md
> +  - Il est recommandé de télécharger d'abord les packs qui ne coûtent pas d'argent. Les packs gratuits ont l'étiquette "FREE" au lieu de l'étiquette de coût "USD$".
```suggestion
```

C'est quand j'ai du faire la remise en conformité par rapport à #6360, j'ai du oublier de supprimer cette ligne.

2021-12-07 17:06 UTC, DoryanR approved these changes

2021-12-07 17:32 UTC, Walavouchey commented
Should @Ganondorf-1's remaining changes be seen as resolved here?

2021-12-07 17:52 UTC, DoryanR commented
Yes, I think it's good.

2021-12-07 18:29 UTC, Walavouchey approved these changes

2021-12-07 18:30 UTC, merged