[DE] Add German translation for `wiki/wiki!-osu`
ppy/osu-wiki pull request #6340
Opened 2021-11-08 20:06 UTC by The-Last-Cookie

Proposal for adding a German translation for this article.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-11-08 21:17 UTC, FamousPig requested changes
I don't know if you need any special credentials to count as a "native reviewer", but I am a native german speaker.

2021-11-08 21:17 UTC, FamousPig commented on wiki/osu!_wiki/de.md
> +Obwohl das Wiki *wiki* im Namen trägt, erfüllt es nicht alle Kriterien des [Wiki-Konzepts](https://en.wikipedia.org/wiki/Wiki):
```suggestion
Obwohl das osu! wiki *wiki* im Namen trägt, erfüllt es nicht alle Kriterien des [Wiki-Konzepts](https://en.wikipedia.org/wiki/Wiki):
```

2021-11-08 21:17 UTC, FamousPig commented on wiki/osu!_wiki/de.md
> +Bitte beachte, dass dies nicht die Verwendung von "osu!" oder der Marke "ppy" in jedweder Software, Ressource, Werbung oder Promotion erlaubt, da diese durch das Markenrecht geschützt sind. Für mehr
```suggestion
Bitte beachte, dass dies nicht die Verwendung von "osu!" oder der Marke "ppy" in jedweder Software, Ressource, Werbung oder Promotion erlaubt, da diese durch das Markenrecht geschützt sind. Falls du eine Erlaubnis für die Benutzung dieser Begriffe benötigst, [kontaktiere uns](mailto:contact@ppy.sh) bitte.
```

2021-11-08 21:50 UTC, TicClick commented
> I don't know if you need any special credentials to count as a "native reviewer"

absolutely not -- if you are proficient, come and drop a line, or maybe several. yeah, that's it, probably several that come together!

2021-11-09 19:30 UTC, The-Last-Cookie commented on wiki/osu!_wiki/de.md
> +Das **osu! wiki** ist eine Sammlung an öffentlich zugänglichem Wissen, welche von [freiwilligen Mitwirkenden](https://github.com/ppy/osu-wiki/graphs/contributors) betrieben wird. Hier findet sich ein
Either you refer to `Sammlung` or you point to `Wissen`. In the first case, the sentence is grammatically correct as far as I can tell. In the latter case, `Wissen` in connection to `betrieben` does sound wrong to me. Though I can see your point. It isn't clear what the `welche` is refering to. I will use your suggestion with small changes to the rest of the sentence.

2021-11-09 19:37 UTC, The-Last-Cookie commented on wiki/osu!_wiki/de.md
> +Ein individueller Artikel beschreibt einen einzigen Ausdruck, ein Konzept oder gibt einen generellen Überblick über angrenzende Themen. Um den Begriff besser zu verstehen, wird das Thema in mehrere U
Yes, you are right. But the comma after `Ausdruck` isn't placed correctly. I will change that to `oder`, since that fits the English version.

2021-11-09 19:43 UTC, The-Last-Cookie commented on wiki/osu!_wiki/de.md
> +## Design
This part of the article describes how the wiki is meant to be designed. For me, it isn't quite clear what `model` means in this context and I found `Design` more fitting. I can still commit it though, I don't want to nitpick on it too much. Tell me what you think about it @FamousPig

2021-11-09 19:58 UTC, FamousPig commented on wiki/osu!_wiki/de.md
> +## Design
I suppose the terms are synonymous in this case. Probably fine to leave it.

2021-11-09 20:09 UTC, FamousPig commented on wiki/osu!_wiki/de.md
> +Das **osu! wiki** ist eine Sammlung an öffentlich zugänglichem Wissen, welche von [freiwilligen Mitwirkenden](https://github.com/ppy/osu-wiki/graphs/contributors) betrieben wird. Hier findet sich ein
~~`welches` as in `Das osu! wiki ... , welches`, no?~~

Nevermind, my mistake. Not sure why I misread this one.

2021-11-09 20:13 UTC, FamousPig approved these changes

2021-11-09 20:22 UTC, TicClick approved these changes
thanks

2021-11-09 20:24 UTC, merged