[FR] Add `Skinning/FAQ`, Update `Skinning/Interface`
ppy/osu-wiki pull request #6345
Opened 2021-11-09 20:01 UTC by DoryanR

Proposal for the French translation of the wiki page `FAQ`.

Proposal to update the French translation of the wiki page `Interface`.

2021-11-09 20:03 UTC, DoryanR commented on wiki/Skinning/Interface/fr.md
> +
```suggestion
```

2021-11-14 17:49 UTC, Ganondorf-1 requested changes

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Le skinning est un simple mécanisme de changement d'image qu'osu! chargera lors de la sélection d'un skin dans les options. Il est facile de créer un skin, mais il est un peu plus difficile de créer
```suggestion
Le skinning est un simple mécanisme de changement d'images qu'osu! chargera lors de la sélection d'un skin dans les options. Il est facile de créer un skin, mais il est un peu plus difficile de créer les ressources nécessaires.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +**Néanmoins, ne demandez jamais de skin sur les forums**. Le non-respect de cette règle entraînera le déplacement de votre fil de discussion vers wastelands.
```suggestion
**Néanmoins, ne demandez jamais de skin sur les forums**. Le non-respect de cette règle entraînera le déplacement de votre fil de discussion vers les wastelands.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Oui, vous pouvez utiliser des éléments de skinning provenant d'autres skins. Ces éléments sont appelés "skins mixtes" ou "skin mashups". Cependant, **vous n'êtes pas autorisé à les poster sur le sous
```suggestion
Oui, vous pouvez utiliser des éléments de skinning provenant d'autres skins. Ces éléments sont appelés "skins mixtes" ou "skin mashups". Cependant, **vous n'êtes pas autorisé à les poster sur le sous-forum skinning, avec ou sans permission**, mais vous pouvez les poster dans votre signature ou sur votre page d'utilisateur "moi!"
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Vous pouvez également quitter et rouvrir osu! ou lancer l'updater pour recharger le skin, mais il est généralement plus rapide d'utiliser la combinaison de quatre clés pour recharger le skin dans osu
```suggestion
Vous pouvez également quitter et rouvrir osu! ou lancer l'updater pour recharger le skin, mais il est généralement plus rapide d'utiliser la combinaison de quatre touches pour recharger le skin dans osu!
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Dans osu!, il y a plus de 200 éléments qui peuvent être skinnés (sans compter les images animées individuelles). Cependant, vous n'êtes pas obligé de les skinner tous. Vous pouvez simplement les supp
```suggestion
Dans osu!, il y a plus de 200 éléments qui peuvent être skinnés (sans compter les images animées individuelles). Cependant, vous n'êtes pas obligé de tous les skinner. Vous pouvez simplement les supprimer car osu! utilisera les images par défaut pour ceux que vous n'avez pas inclus.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +### Une skin éditée est-elle un skin mixte ?
```suggestion
### Un skin édité est-il un skin mixte ?
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Oui, vous pouvez avoir un thème de skin similaire à celui de quelqu'un d'autre qui l'a peut-être fait avant vous. Cependant, vous devez créer les actifs vous-même et, évidemment, ne pas copier les ac
```suggestion
Oui, vous pouvez avoir un thème de skin similaire à celui de quelqu'un d'autre qui l'a peut-être fait avant vous. Cependant, vous devez créer les éléments vous-même et, évidemment, ne pas copier les éléments de l'autre skin que vous essayez de refaire.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Tout d'abord, avant de partager votre skin, assurez-vous que vous avez supprimé les autres fichiers qui ne sont pas utilisés. Il peut s'agir d'images et de sons par défaut, de dossiers supplémentaire
```suggestion
Tout d'abord, avant de partager votre skin, assurez-vous que vous avez supprimé les autres fichiers qui ne sont pas utilisés. Il peut s'agir d'images et de sons par défaut, de dossiers supplémentaires, de fichiers non-image (à l'exception du fichier `skin.ini`). Une fois cette étape terminée, vous devrez exporter votre skin sous forme de fichier `.osk`. Avec ce fichier, vous pouvez le mettre en ligne et le poster dans le sous-forum skinning.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +6. Prenez le fichier `.osk` avec le nom de votre skin et téléchargez-le.
```suggestion
6. Prenez le fichier `.osk` avec le nom de votre skin et mettez-le en ligne.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +#### Où puis-je afficher mon skin mixte ?
```suggestion
#### Où puis-je poster mon skin mixte ?
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Vous pouvez utiliser votre page d'utilisateur moi!, votre signature, le [/r/osuskins subreddit](https://www.reddit.com/r/OsuSkins), ou tout autre endroit en dehors des forums d'osu!
```suggestion
Vous pouvez utiliser votre page d'utilisateur "moi!", votre signature, le [subreddit /r/osuskins](https://www.reddit.com/r/OsuSkins), ou tout autre endroit en dehors des forums d'osu!
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Oui, les remakes de skin ne sont pas considérés comme mixtes. Vous pouvez donc les poster, tant qu'aucun des actifs n'a été copié ou dupliqué à partir d'un autre skin (auquel cas, il serait considéré
```suggestion
Oui, les remakes de skin ne sont pas considérés comme mixtes. Vous pouvez donc les poster, tant qu'aucun des éléments n'a été copié ou dupliqué à partir d'un autre skin (auquel cas, il serait considéré comme mixte).
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Pour ajouter cet avertissement, il suffit de préfixer `[R15]` au titre de votre fil de discussion et d'écrire un avis en haut du post lui-même.
```suggestion
Pour ajouter cet avertissement, il suffit de préfixer `[R15]` au titre de votre post et d'écrire un avis en haut du post lui-même.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +- Découpez ou recadrez vos images autant que possible. Le client d'osu! rendra chaque pixel d'une image, ce qui entraînera une charge de travail plus importante !
```suggestion
- Découper ou recadrer vos images autant que possible. Le client d'osu! rendra chaque pixel d'une image, ce qui entraînera une charge de travail plus importante !
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +- Compressez les images chaque fois que possible. La compression supprime généralement les informations inutiles sur les pixels vides et réduit considérablement la taille des fichiers.
```suggestion
- Compresser les images chaque fois que possible. La compression supprime généralement les informations inutiles sur les pixels vides et réduit considérablement la taille des fichiers.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +1. Si elle joue trop vite, essayez de les allonger en doublant les images (ou en les divisant par deux, si elle est trop lente).
```suggestion
1. Si elle se joue trop vite, essayez de les allonger en doublant les images (ou en les divisant par deux, si elle est trop lente).
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +- Désactiver l'éclairage des frappes dans les [options](/wiki/Options).
```suggestion
- Désactiver les lueurs de fond dans les [options](/wiki/Options).
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Ajouter un fichier transparent pour ces noms de fichiers :
```suggestion
Ajoutez un fichier transparent pour ces noms de fichiers :
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +- Cet élément est positionné au centre et est configuré pour couvrir (remplir toute la largeur et la hauteur tout en gardant son rapport d'aspect, mais rogner tout ce qui est en dehors de la fenêtre
```suggestion
- Cet élément est positionné au centre et est configuré pour couvrir (remplir toute la largeur et la hauteur tout en gardant son aspect ratio, mais rogner tout ce qui est en dehors de la fenêtre du jeu).
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +- Cet élément est utilisé comme terrain de jeu si la beatmap n'a pas de fond.
```suggestion
- Cet élément est utilisé comme playfield si la beatmap n'a pas de fond.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/FAQ/fr.md
> +Les images seront ajustées par le jeu lui-même pour s'adapter à des résolutions dérivées de celles mentionnées ci-dessus. La plupart d'entre elles seront redimensionnées pour s'adapter au champ de je
```suggestion
Les images seront ajustées par le jeu lui-même pour s'adapter à des résolutions dérivées de celles mentionnées ci-dessus. La plupart d'entre elles seront redimensionnées pour s'adapter au playfield ou repositionnées sur des rapports d'aspect différents.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +## Terrain de jeu
```suggestion
## Playfield
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +- Lorsque le jeu est en pause, le champ de jeu sera obscurci et ce fichier se superposera en haut de celui-ci.
```suggestion
- Lorsque le jeu est en pause, le playfield sera obscurci et ce fichier se superposera en haut de celui-ci.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +- Select [osu!mania](/wiki/Game_mode/osu!mania) for this to be visible.
```suggestion
- Sélectionnez [osu!mania](/wiki/Game_mode/osu!mania) pour que cela soit visible.
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +  - Pause :  Centre
```suggestion
  - Pause : Centre
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +  - Pause :  Centre
```suggestion
  - Pause : Centre
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +  - Pause :  Centre
```suggestion
  - Pause : Centre
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +  - Pause :  Centre
```suggestion
  - Pause : Centre
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +  - Pause :  Centre
```suggestion
  - Pause : Centre
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +  - Pause :  Centre
```suggestion
  - Pause : Centre
```

2021-11-14 17:49 UTC, Ganondorf-1 commented on wiki/Skinning/Interface/fr.md
> +  - Pause :  Centre
```suggestion
  - Pause : Centre
```

2021-11-19 18:46 UTC, DoryanR commented
@Ganondorf-1 recheck please

2021-11-26 16:25 UTC, TicClick approved these changes
merging with the assumption that one review was enough

2021-11-26 16:26 UTC, merged