[FR] Add `Skinning/osu!`, `Skinning/osu!catch`
ppy/osu-wiki pull request #6354
Opened 2021-11-11 09:44 UTC by DoryanR

Translation of the following wiki pages:

- `Skinning/osu!`
- `Skinning/osu!catch`

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-14 19:07 UTC, Ganondorf-1 requested changes

2021-11-14 19:07 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
> +- Teinté en cyan, clignote en blanc lorsque des points bonus sont attribués.
```suggestion
- Teinté de cyan, clignote en blanc lorsque des points bonus sont attribués.
```

2021-11-14 19:07 UTC, Ganondorf-1 commented on wiki/Skinning/osu!catch/fr.md
> +- Ceci remplace `fruit-catcher-kiai.png` si un fruit ou un drop/droplet est manquée pendant le [kiai time](/wiki/Kiai_time).
```suggestion
- Ceci remplace `fruit-catcher-kiai.png` si un fruit ou un drop/droplet est manqué pendant le [kiai time](/wiki/Kiai_time).
```

2021-11-14 19:07 UTC, Ganondorf-1 commented on wiki/Skinning/osu!catch/fr.md
> +- Cet élément n'est pas utilisé dans l'écran de classement.
```suggestion
- Cet élément n'est pas utilisé dans l'écran de résultats.
```

2021-11-14 19:07 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
> +  - Ce taux est affecté par les modificateurs de mi-temps et de double temps/nightcore du jeu.
```suggestion
  - Ce taux est affecté par les mods Half Time et Double Time/Nightcore.
```

2021-11-14 19:07 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
> +  - Ce taux est affecté par les modificateurs half time et double time/nightcore du jeu.
```suggestion
  - Ce taux est affecté par les mods Half Time et Double Time/Nightcore.
```

2021-11-14 19:07 UTC, Ganondorf-1 commented on wiki/Skinning/osu!catch/fr.md
> +*Voir également : [Tutoriel de skinning  du mode osu!catch](/wiki/Skinning/Guides_and_important_threads)*
```suggestion
*Voir également : [Tutoriel de skinning du mode osu!catch](/wiki/Skinning/Guides_and_important_threads)*
```

2021-11-14 19:07 UTC, Ganondorf-1 commented on wiki/Skinning/osu!catch/fr.md
> +- `fruit-catcher-fail.png` remplacera ceci si un fruit ou un drop/droplet est manquée pendant le [kiai time](/wiki/Kiai_time).
```suggestion
- `fruit-catcher-fail.png` remplacera ceci si un fruit ou un drop/droplet est manqué pendant le [kiai time](/wiki/Kiai_time).
```

2021-11-19 18:46 UTC, DoryanR commented
@Ganondorf-1 recheck please

2021-11-26 16:26 UTC, TicClick approved these changes
merging with the assumption that one review was enough

2021-11-26 16:27 UTC, merged