[FR] Update `Skinning`, Add `Skinning/osu!taiko`, `Skinning/Sounds`
ppy/osu-wiki pull request #6355
Opened 2021-11-11 11:09 UTC by DoryanR

Proposal to update the French translation of the wiki page `Skinning`.

Translation of the following wiki pages:

- `Skinning/osu!taiko`
- `Skinning/Sounds`

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-11 11:11 UTC, DoryanR commented on wiki/Skinning/fr.md
> +## Sets de skinning
```suggestion
Le skinning est l'une des principales caractéristiques d'osu!. Il permet aux joueurs de s'inspirer des éléments de skin originaux pour créer leur propre skin !. Les skins peuvent être amusants, à thème, PRO, ou il peut être pratiquement impossible de jouer avec.

## Sets de skinning
```

2021-11-14 18:25 UTC, Ganondorf-1 requested changes

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque l'on passe au-dessus du bouton de retour.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton de retour.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué quand on survole des difficultés.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus survole des difficultés.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous survolez Back dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Back dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous passez la souris sur les graphiques dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus des graphiques dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous passez la souris sur Direct dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Direct dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous passez la souris sur Edit dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Edit dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous passez la souris sur Exit dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Exit dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous passez la souris sur Solo dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Solo dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous survolez Multiplayer dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Multiplayer dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsque vous passez la souris sur Options dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Options dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsqu'on passe la souris sur Play dans le menu principal.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Play dans le menu principal.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué quand on passe la souris sur Back dans le menu pause.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Back dans le menu pause.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsqu'on passe la souris sur Continue dans le menu pause.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Continue dans le menu pause.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué quand on passe la souris sur Retry dans le menu pause.
```suggestion
- Ce son est joué lorsque le curseur passe au-dessus du bouton Retry dans le menu pause.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsqu'un joueur révoque son signal de disponibilité.
```suggestion
- Ce son est joué lorsqu'un joueur n'est plus prêt à jouer.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué lorsqu'un joueur est prêt à commencer.
```suggestion
- Ce son est joué lorsqu'un joueur est prêt à jouer.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Il s'agit également du son de mise en valeur dans le  tchat.
```suggestion
- Il s'agit également du son des notifications dans le tchat.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Malgré ce qui précède, cela peut être skinné pour l'assistant de décalage et les bananes en osu!catch (le pitch augmente par banane attrapée).
```suggestion
- Malgré ce qui précède, cela peut être skinné pour l'assistant de décalage et les bananes en osu!catch (le pitch augmente à chaque banane attrapée).
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Échoue une map à n'importe quel moment.
```suggestion
- Échec d'une beatmap à n'importe quel moment.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Il n'est pas prévu qu'il dure plus longtemps que l'animation d'échec (environ 5 secondes).
```suggestion
- Ce son ne devrait pas durer plus longtemps que l'animation d'échec (environ 5 secondes).
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- A mi-chemin d'une pause avec un HP élevé restant.
```suggestion
- Ce son se joue à mi-chemin d'une pause avec plus de la moitié des HP.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- A mi-chemin d'une pause avec peu de HP restants.
```suggestion
- Ce son se joue à mi-chemin d'une pause avec moins de la moitié des HP.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Sur l'écran de classement après avoir passé une map
```suggestion
- Sur l'écran de résultats après avoir terminé une beatmap
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- L'utilisation d'une longue piste audio aura un impact sur les performances du client. Elle n'est pas censée dépasser quelques kilo-octets.
```suggestion
- L'utilisation d'une longue piste audio aura un impact sur les performances du client. Elle ne devrait pas dépasser quelques kilo-octets.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- S'éteint lorsque le client perd sa concentration.
```suggestion
- S'arrête si vous cliquez sur une autre fenêtre ou sur le bureau.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- L'utilisation d'une longue piste audio aura un impact sur les performances du client. Elle n'est pas censée dépasser quelques kilo-octets.
```suggestion
- L'utilisation d'une longue piste audio aura un impact sur les performances du client. Elle ne devrait pas dépasser quelques kilo-octets.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est mis en boucle.
```suggestion
- Ce son est joué en boucle.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/Sounds/fr.md
> +- Ce son est joué chaque fois que vous obtenez 1000 points de bonus pendant un spinner.
```suggestion
- Ce son est joué chaque fois que vous obtenez 1000 points bonus pendant un spinner.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/fr.md
> +**Pour les beatmaps uniquement**, si votre skin contient un seul élément des ensembles énumérés dans les critères de classement, il doit contenir tous les autres éléments de cet ensemble de skinning.
```suggestion
**Pour les beatmaps uniquement**, si votre skin contient un seul élément des ensembles énumérés dans les critères de classement, il doit contenir tous les autres éléments de cet ensemble de skinning. Ceci ne s'applique qu'aux skins des beatmaps, mais d'autres skinneurs peuvent vouloir prendre en compte ces listes également.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +Vous pouvez remplacer les parties du champ de jeu osu!taiko en créant un dossier appelé `taiko` dans votre dossier skin. Si cette approche est utilisée, l'utilisateur devra explicitement l'activer da
```suggestion
Vous pouvez remplacer les parties du playfield osu!taiko en créant un dossier appelé `taiko` dans votre dossier skin. Si cette approche est utilisée, l'utilisateur devra explicitement l'activer dans les [options](/wiki/Options) (activer le bouton `Utiliser le skin Taiko pour le mode Taiko`), sinon les éléments du skin par défaut seront utilisés.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +- Le status de modifiable sur une beatmap est suspecté d'être un bug.
```suggestion
- Le statut de "Skinnable sur une beatmap" semble être un bug.
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-14 18:25 UTC, Ganondorf-1 commented on wiki/Skinning/osu!taiko/fr.md
> +| Versions | Peut être animé | Modifiable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```suggestion
| Versions | Peut être animé | Skinnable sur une beatmap | Blend Mode | Origine | Taille de SD suggérée |
```

2021-11-19 18:46 UTC, DoryanR commented
@Ganondorf-1 recheck please

2021-11-26 16:27 UTC, TicClick approved these changes
merging with the assumption that one review was enough

2021-11-26 16:29 UTC, merged