[FR] Add `Skinning/skin.ini`
ppy/osu-wiki pull request #6367
Opened 2021-11-14 10:57 UTC by DoryanR

Proposal for the French translation of the wiki page `skin.ini`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-14 19:29 UTC, Ganondorf-1 requested changes

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- Les numéros des hit circle font partie des explosions de hitburst..
```suggestion
- Les numéros des hit circle font partie des explosions de hitburst.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - Doit être activé par l'utilisateur dans les [options](/wiki/Options) et être supporté par le skin dans le fichier [skin.ini](/wiki/Skinning/skin.ini).
```suggestion
  - Doit être activé par l'utilisateur dans les [options](/wiki/Options) et être pris en charge par le skin dans le fichier [skin.ini](/wiki/Skinning/skin.ini).
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- Modifie l'affichage du star ranting en mettant à l'échelle `star.png` au lieu de `star.png` partiellement élargi.
```suggestion
- Modifie l'affichage du star rating en mettant à l'échelle `star.png` au lieu de `star.png` partiellement élargi.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - Les combobursts  d'osu! ne sera plus utilisé pour osu!catch.
```suggestion
  - Les combobursts d'osu! ne sera plus utilisé pour osu!catch.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- Réduit le nombre de compteurs de combo et de coups.
```suggestion
- Rétrécit le compteur de combo et les hitbursts.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- **Ne l'utilisez jamais** pour distribuer des skins ! (si une nouvelle version de skin sort, un skin dont la version est réglée sur `latest` pourrait se casser).
```suggestion
- **Ne l'utilisez jamais** pour distribuer des skins ! (si une nouvelle version de skin sort, un skin dont la version est réglée sur `latest` pourrait ne pas fonctionner correctement).
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- Utilise toujours la dernière version supportée par le jeu.
```suggestion
- Utilisera toujours la dernière version prise en charge par le jeu.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +**Pas une version, mais toujours forcer [latest](#latest)**
```suggestion
**Pas une version, mais forcera toujours [latest](#latest)**
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +### 1's and 0's
```suggestion
### 1 et 0
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +Notez que Reisen, le sliderball, ne se retourne pas lorsque `0` est utilisé. Cependant, Reisen se retourne quand un `1` est utilisé. En fonction du sprite utilisé, vous obtiendrez soit une balle glis
```suggestion
Notez que Reisen, la sliderball, ne se retourne pas lorsque `0` est utilisé. Cependant, Reisen se retourne quand un `1` est utilisé. En fonction du sprite utilisé, vous obtiendrez soit une sliderball qui fait du moonwalk, soit une sliderball qui se retourne.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +When viewing these tables:
```suggestion
Concernant ces tableaux :
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +### Nombres et nombres entiers
```suggestion
### Nombres et entiers
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- *entier* signifient **uniquement** des nombres entiers (par exemple : `-13`, `-632`, `135` , `9`).
```suggestion
- *entier* signifie **uniquement** des nombres entiers (par exemple : `-13`, `-632`, `135` , `9`).
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - *positive integer* signifie **nombre entier positif** uniquement (par exemple `376`, `22`, ou `5`).
```suggestion
  - *entier positif* signifie **nombre entier positif** uniquement (par exemple `376`, `22`, ou `5`).
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- *nombres* signifie un nombre **entier** ou **décimal** (par exemple `1.5`, `4.295`, `2`, `3.0`).
```suggestion
- *nombre* signifie un nombre **entier** ou **décimal** (par exemple `1.5`, `4.295`, `2`, `3.0`).
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - Question : Quel est le préfixe utilisé pour les numéros des hitcircle ?
```suggestion
  - Question : Quel est le préfixe utilisé pour les numéros des hit circles ?
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - Question : De combien de pixels les numéros d'hitcircle doivent-ils se chevaucher ?
```suggestion
  - Question : De combien de pixels les numéros d'hit circle doivent-ils se chevaucher ?
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - en utilisant trop et les extras sont ignorés.
```suggestion
  - les touches en trop et les extras sont ignorés.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - pas assez et les valeurs manquantes utiliseront des valeurs par défaut.
```suggestion
  - ne pas utiliser assez de touches et les valeurs manquantes utiliseront des valeurs par défaut.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- **Chaque keycount  *doit* commencer une nouvelle section**, cela devrait ressembler à ceci (mais avec des commandes réelles) :
```suggestion
- **Chaque keycount *doit* commencer une nouvelle section**, cela devrait ressembler à ceci (mais avec des commandes réelles) :
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +    - `1` = s'affiche lorsqu'il est frappé sur une scène spécifique
```suggestion
    - `1` = s'affiche lorsqu'il est touché sur une scène spécifique
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +    - Chaque keycount  supérieur à 1 peut être divisé (ou fusionné, si le nombre est supérieur à 9).
```suggestion
    - Chaque keycount supérieur à 1 peut être divisé (ou fusionné, si le nombre est supérieur à 9).
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- Ajout de  `arrow-generic.png`, `arrow-warning.png` et `arrow-pause.png`.
```suggestion
- Ajout de `arrow-generic.png`, `arrow-warning.png` et `arrow-pause.png`.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +- Pour RGB, le format ressemble à ceci :  `R, G, B` où `R` est le rouge, `G` est le vert et `B` est le bleu.
```suggestion
- Pour RGB, le format ressemble à ceci : `R, G, B` où `R` est le rouge, `G` est le vert et `B` est le bleu.
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - Question : A quelle hauteur les hitbursts  doivent-ils apparaître ?
```suggestion
  - Question : A quelle hauteur les hitbursts doivent-ils apparaître ?
```

2021-11-14 19:29 UTC, Ganondorf-1 commented on wiki/Skinning/skin.ini/fr.md
> +  - Question : La  hold note tail de la colonne doit-elle être inversée lorsque la scène est inversée ?
```suggestion
  - Question : La hold note tail de la colonne doit-elle être inversée lorsque la scène est inversée ?
```

2021-11-19 18:46 UTC, DoryanR commented
@Ganondorf-1 recheck please

2021-11-26 16:28 UTC, TicClick approved these changes
merging with the assumption that one review was enough

2021-11-26 16:30 UTC, merged