[FR] Add `User_title`
ppy/osu-wiki pull request #6368
Opened 2021-11-14 11:05 UTC by DoryanR

Proposal for the French translation of the wiki page `User_title`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-14 11:06 UTC, DoryanR commented on wiki/User_title/fr.md
> +- Les titres des utilisateurs sont appelés "titres de rang" dans le code du jeu. Ce nom est un vestige de l'époque où osu! était construit sur [phpBB] (https://www.phpbb.com/).
```suggestion
- Les titres des utilisateurs sont appelés "titres de rang" dans le code du jeu. Ce nom est un vestige de l'époque où osu! était construit sur [phpBB](https://www.phpbb.com/).
```

2021-11-14 19:34 UTC, Ganondorf-1 requested changes

2021-11-14 19:34 UTC, Ganondorf-1 commented on wiki/User_title/fr.md
> +  - classement
```suggestion
  - grade
```

2021-11-14 19:34 UTC, Ganondorf-1 commented on wiki/User_title/fr.md
> +### Titres du nombre de messages
```suggestion
### Titres du nombre de posts
```

2021-11-14 19:34 UTC, Ganondorf-1 commented on wiki/User_title/fr.md
> +![Capture d'écran de la barre latérale du poste de Damnae sur l'ancien site web](img/star-shooter.png "Le titre \"Star Shooter\" se trouve au-dessus du nombre de messages de Damnae.")
```suggestion
![Capture d'écran de la barre latérale du poste de Damnae sur l'ancien site web](img/star-shooter.png "Le titre \"Star Shooter\" se trouve au-dessus du nombre de posts de Damnae.")
```

2021-11-14 19:34 UTC, Ganondorf-1 commented on wiki/User_title/fr.md
> +Sur les forums de [l'ancien site d'osu!](https://old.ppy.sh), les utilisateurs pouvaient obtenir des titres en atteignant certains seuils de nombre de messages, comme suit :
```suggestion
Sur les forums de [l'ancien site d'osu!](https://old.ppy.sh), les utilisateurs pouvaient obtenir des titres en atteignant certains seuils de nombre de posts, comme suit : 
```

2021-11-14 19:34 UTC, Ganondorf-1 commented on wiki/User_title/fr.md
> +| Titre du forum | Nombre total de messages |
```suggestion
| Titre du forum | Nombre total de posts |
```

2021-11-14 19:34 UTC, Ganondorf-1 commented on wiki/User_title/fr.md
> +- Les titres des utilisateurs sont appelés "titres de rang" dans le code du jeu. Ce nom est un vestige de l'époque où osu! était construit sur [phpBB](https://www.phpbb.com/).
```suggestion
- Les titres des utilisateurs sont appelés "rank titles" dans le code du jeu. Ce nom est un vestige de l'époque où osu! était construit sur [phpBB](https://www.phpbb.com/).
```

2021-11-19 18:46 UTC, DoryanR commented
@Ganondorf-1 recheck please

2021-11-26 16:29 UTC, TicClick approved these changes
merging with the assumption that one review was enough

2021-11-26 16:31 UTC, merged