[FR] Add `osu!_Community_Meetings`
ppy/osu-wiki pull request #6369
Opened 2021-11-14 11:15 UTC by DoryanR

Proposal for the French translation of the wiki page `osu!_Community_Meetings`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-14 19:42 UTC, Ganondorf-1 requested changes

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +Le prochain osu! community meeting est prévue pour le : **Le 28 novembre 2021 (dimanche 01:00 UTC)**. Les réunions ont généralement lieu toutes les deux semaines, les rappels étant annoncés sur le [T
```suggestion
Le prochain osu! community meeting est prévu pour le : **Le 28 novembre 2021 (dimanche 01:00 UTC)**. Les réunions ont généralement lieu toutes les deux semaines, les rappels étant annoncés sur le [compte Twitter de peppy](https://twitter.com/ppy) environ un jour avant.
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +Les **osu! community meetings** sont un groupe de discussion bimensuel organisé par l'[équipe d'osu!](/wiki/People/The_Team). L'objectif principal de ces réunions est de donner à chacun une chance de
```suggestion
Les **osu! community meetings** sont un groupe de discussion bimensuel organisé par l'[équipe d'osu!](/wiki/People/The_Team). L'objectif principal de ces meetings est de donner à chacun une chance de parler directement avec les développeurs et les personnes responsables de la gestion de la communauté pour soulever des questions à discuter ou à approfondir.
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +Les osu! community meetings sont actuellement organisées sur une scène Discord sur le Discord [osu!dev](https://discord.gg/ppy), et diffusées en simultané sur [la chaîne Twitch de peppy](https://www.
```suggestion
Les osu! community meetings sont actuellement organisées sur une scène Discord sur le Discord [osu!dev](https://discord.gg/ppy), et diffusés en simultané sur [la chaîne Twitch de peppy](https://www.twitch.tv/ppy). Chaque meeting dure environ une heure et a lieu un dimanche sur deux à 01:00 UTC. 
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +Le premier osu! community meeting a eu lieu le 19 septembre 2021. Toutes les réunions ont été et continueront d'être enregistrées sur YouTube, accompagnées d'un document de synthèse.
```suggestion
Le premier osu! community meeting a eu lieu le 19 septembre 2021. Tous les meetings ont été et continueront d'être enregistrées sur YouTube, accompagnées d'un document de synthèse.
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +| Réunion # | Lien | Résumé |
```suggestion
| Meeting n° | Lien | Résumé |
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +| 0 | [19 septembre 2021](https://youtu.be/-LjNll8VYTM) | [Notes de réunion](https://gist.github.com/peppy/08b38cbac56a8b1e88133853a6a8d2fb) |
```suggestion
| 0 | [19 septembre 2021](https://youtu.be/-LjNll8VYTM) | [Document de synthèse](https://gist.github.com/peppy/08b38cbac56a8b1e88133853a6a8d2fb) |
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +| 1 | [3 octobre 2021](https://youtu.be/D3OZCm6szVE) | [Notes de réunion](https://docs.google.com/document/d/1-miPFZySYlYbtPW4G0828taycO1gh7dZ4icfSJCr4uA) |
```suggestion
| 1 | [3 octobre 2021](https://youtu.be/D3OZCm6szVE) | [Document de synthèse](https://docs.google.com/document/d/1-miPFZySYlYbtPW4G0828taycO1gh7dZ4icfSJCr4uA) |
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +| 2 | [17 octobre 2021](https://youtu.be/nLT-fLeogrw) | [Notes de réunion](https://docs.google.com/document/d/1wEQjzku_4IzvcWRanu0GkvWiPvb-IB7WzwU7Eyojj2E) |
```suggestion
| 2 | [17 octobre 2021](https://youtu.be/nLT-fLeogrw) | [Document de synthèse](https://docs.google.com/document/d/1wEQjzku_4IzvcWRanu0GkvWiPvb-IB7WzwU7Eyojj2E) |
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +| 3 | [31 octobre 2021](https://youtu.be/omvZbC7zJUI) | [Notes de réunion](https://docs.google.com/document/d/1bhaMx--chdys8AbzSDOItbv710SVhsww2BYPzQg2rvw) |
```suggestion
| 3 | [31 octobre 2021](https://youtu.be/omvZbC7zJUI) | [Document de synthèse](https://docs.google.com/document/d/1bhaMx--chdys8AbzSDOItbv710SVhsww2BYPzQg2rvw) |
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +| 4 | [14 novembre 2021](https://youtu.be/rEWgTY-L95Y) | [Notes de réunion](https://docs.google.com/document/d/1rhrz0zaxQfVK1UnvrcEqj4UMagTD0bPNh8wby8I38IA) |
```suggestion
| 4 | [14 novembre 2021](https://youtu.be/rEWgTY-L95Y) | [Document de synthèse](https://docs.google.com/document/d/1rhrz0zaxQfVK1UnvrcEqj4UMagTD0bPNh8wby8I38IA) |
```

2021-11-14 19:42 UTC, Ganondorf-1 commented on wiki/osu!_Community_Meetings/fr.md
> +Nous avons l'intention de ne pas prendre plus de 5 minutes par question, donc comprenez que les questions auxquelles on a déjà répondu ou qui sont particulièrement génériques peuvent ne pas être choi
```suggestion
Nous avons l'intention de ne pas prendre plus de 5 minutes par question, comprenez donc que les questions auxquelles on a déjà répondu ou qui sont particulièrement génériques peuvent ne pas être choisies pour la discussion.
```

2021-11-19 18:46 UTC, DoryanR commented
@Ganondorf-1 recheck please

2021-11-26 17:25 UTC, TicClick approved these changes
merging with the assumption that one review was enough

2021-11-26 17:26 UTC, merged