[FR] Add `osu!_Program_Files/User_Configuration_File`, Update `osu!_Program_Files`
ppy/osu-wiki pull request #6382
Opened 2021-11-17 18:09 UTC by DoryanR

Proposal to update the French translation of the wiki page `osu!_Program_Files`.

Proposal for the French translation of the wiki page `User_Configuration_File`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-17 18:12 UTC, DoryanR commented on wiki/osu!_Program_Files/fr.md
> +*Pour les joueurs qui souhaitent télécharger leur replay sur YouTube, voir : [Osr2mp4 public release. Conversion automatique du fichier de replays en vidéo] (https://osu.ppy.sh/community/forums/topic
```suggestion
*Pour les joueurs qui souhaitent télécharger leur replay sur YouTube, voir : [Osr2mp4 public release. Conversion automatique du fichier de replays en vidéo](https://osu.ppy.sh/community/forums/topics/1104243)*
```

2021-11-17 18:12 UTC, DoryanR commented on wiki/osu!_Program_Files/fr.md
> +Le dossier Skins contient des skins créés par les utilisateurs, qui peuvent être utilisés pour personnaliser l'interface du jeu. Les joueurs peuvent télécharger des skins depuis le sous forum [Skinni
```suggestion
Le dossier Skins contient des skins créés par les utilisateurs, qui peuvent être utilisés pour personnaliser l'interface du jeu. Les joueurs peuvent télécharger des skins depuis le sous forum [Skinning](https://osu.ppy.sh/community/forums/15). Les joueurs peuvent installer les skins en double-cliquant sur le skin depuis un gestionnaire de fichiers. "osu! by peppy" est le seul skin sans son dossier et ne peut être supprimé.
```

2021-11-17 18:14 UTC, DoryanR commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyTaikoOuterLeft` | osu!taiko  tambour gauche jante|
```suggestion
| `keyTaikoOuterLeft` | osu!taiko  tambour gauche jante |
```

2021-11-24 16:30 UTC, Ganondorf-1 requested changes

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `ChatRemoveForeign` | 0 ou 1 | Filtrer les caractères accentuées et étrangers |
```suggestion
| `ChatRemoveForeign` | 0 ou 1 | Filtrer les caractères accentués et étrangers |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +The values for key binding options are the names of the keys.
```suggestion
Les valeurs attribuées aux options de keybinding sont le nom des touches
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyOsuLeft` | osu! click gauche |
```suggestion
| `keyOsuLeft` | osu! : clic gauche |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyOsuRight` | osu! click droit |
```suggestion
| `keyOsuRight` | osu! : clic droit |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyOsuSmoke` | osu! fumé |
```suggestion
| `keyOsuSmoke` | osu! : fumée |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyTaikoInnerLeft` | osu!taiko tambour gauche centre |
```suggestion
| `keyTaikoInnerLeft` | osu!taiko : tambour gauche centre |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyTaikoInnerRight` | osu!taiko centre tambour droit |
```suggestion
| `keyTaikoInnerRight` | osu!taiko : tambour droit centre |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyTaikoOuterLeft` | osu!taiko  tambour gauche jante |
```suggestion
| `keyTaikoOuterLeft` | osu!taiko : tambour gauche jante |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyTaikoOuterRight` | osu!taiko tambour droit jante |
```suggestion
| `keyTaikoOuterRight` | osu!taiko : tambour droit jante |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyFruitsLeft` | osu!catch déplacement à gauche |
```suggestion
| `keyFruitsLeft` | osu!catch : déplacement à gauche |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyFruitsRight` | osu!catch déplacement à droite |
```suggestion
| `keyFruitsRight` | osu!catch : déplacement à droite |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/User_Configuration_File/fr.md
> +| `keyAudioPause` | Pause de la lecture |
```suggestion
| `keyAudioPause` | Mettre la musique en pause |
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/fr.md
> +*Remarque : les replays étaient auparavant effectuées à un taux d'échantillonnage inférieur, mais elles sont désormais optimisées pour une meilleure expérience.*
```suggestion
*Remarque : les replays étaient auparavant effectuées à un taux d'échantillonnage inférieur, mais elles sont désormais optimisés pour une meilleure expérience.*
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/fr.md
> +Le dossier Replays contient les fichiers replay du joueur. Un fichier replay ne fonctionne pas si les beatmaps qui lui sont liés sont absents. Le replay contient également les données de résultats, e
```suggestion
Le dossier Replays contient les fichiers replay du joueur. Un fichier replay ne fonctionne pas si la beatmap qui lui est liée n'est pas présente dans le dossier Songs. Le replay contient également les données de résultats, et réanime le mouvement du curseur du joueur pendant le replay. Pour créer un replay, appuyez sur F2 à l'écran des résultats, ou cliquez sur le bouton 'Enregistrer le replay dans le dossier Replays' (en Solo uniquement).
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/fr.md
> +*Pour les joueurs qui souhaitent télécharger leur replay sur YouTube, voir : [Osr2mp4 public release. Conversion automatique du fichier de replays en vidéo](https://osu.ppy.sh/community/forums/topics
```suggestion
*Pour les joueurs qui souhaitent mettre en ligne leur replay sur YouTube, voir : [Osr2mp4 public release. Automatically convert replay file to video](https://osu.ppy.sh/community/forums/topics/1104243)*
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/fr.md
> +La structure du nom de fichier est `screenshot###`, où "###" est le nombre de captures d'écran.
```suggestion
La structure du nom de fichier est `screenshot###`, où "###" est le numéro de la capture d'écran.
```

2021-11-24 16:30 UTC, Ganondorf-1 commented on wiki/osu!_Program_Files/fr.md
> +Le composant principal. Cliquez dessus pour le démarrer (uniquement pour Windows). Les fichiers .exe peuvent être ouverts en toute sécurité si le joueur a utilisé le programme d'installation d'osu! t
```suggestion
Le composant principal. Cliquez dessus pour le démarrer (uniquement pour Windows). Les fichiers .exe peuvent être ouverts en toute sécurité si le joueur a utilisé le programme d'installation d'osu! téléchargé sur le site officiel pour installer osu!.
```

2021-11-28 18:13 UTC, TicClick approved these changes

2021-11-28 18:14 UTC, merged