[DE] Update articles in `Disambiguation`
ppy/osu-wiki pull request #6383
Opened 2021-11-17 19:20 UTC by The-Last-Cookie

As [commented here](https://github.com/ppy/osu-wiki/pull/6363#issuecomment-968287340), this is the follow-up PR to #6363  and #6364 . It changes the incorrect `Begriffserklärung` to the correct `Begriffsabgrenzung`.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-11-17 19:56 UTC, respektive requested changes
looks good otherwise

2021-11-17 19:56 UTC, respektive commented on wiki/Disambiguation/de.md
>  Ein normaler Artikel, mit einem ähnlichen Titel, muss die Kopfnote ["Für andere Bedeutungen"](/wiki/Article_styling_criteria/Formatting#for-other-uses) mit einem Link zur Seite für die Begriffserklär
```suggestion
Ein normaler Artikel, mit einem ähnlichen Titel, muss die Kopfnote ["Für andere Bedeutungen"](/wiki/Article_styling_criteria/Formatting#for-other-uses) mit einem Link zur Seite für die Begriffsabgrenzung haben.
```

2021-11-17 20:01 UTC, respektive approved these changes

2021-11-19 03:11 UTC, TicClick approved these changes

2021-11-19 03:12 UTC, merged