[DE] Update `Do you really want to ask peppy`
ppy/osu-wiki pull request #6385
Opened 2021-11-17 20:42 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-11-17 21:11 UTC, respektive requested changes

2021-11-17 21:11 UTC, respektive commented on wiki/Do_you_really_want_to_ask_peppy/de.md
> +Hallo. peppy versteht deinen Drang ihn persönlich zu kontaktieren, aber ich bitte dich zuerst zu verstehen, dass das **nicht** der Ort ist, an dem du ihn um Hilfe oder Unterstützung fragen solltest.
```suggestion
Hallo. peppy versteht deinen Drang ihn persönlich zu kontaktieren, aber er bittet dich zuerst zu verstehen, dass das **nicht** der Ort ist, an dem du ihn um Hilfe oder Unterstützung fragen solltest. Er hält Support für osu! und persönliche Nachrichten voneinander getrennt und findet auch, dass das Antworten auf private Forum-Nachrichten ziemlich schwer zu stemmen ist. Er bittet dich daher eine der folgenden Möglichkeiten zu wählen:
```

2021-11-17 21:37 UTC, respektive approved these changes

2021-11-19 03:14 UTC, TicClick approved these changes

2021-11-19 03:15 UTC, merged