[FR] Update `osu!academy`
ppy/osu-wiki pull request #6386
Opened 2021-11-17 21:04 UTC by DoryanR

Proposal to update the French translation of the wiki page `osu!academy`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-24 16:53 UTC, Ganondorf-1 requested changes

2021-11-24 16:53 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 22 | [Supporter and osu!direct](https://www.youtube.com/watch?v=ec0pLh4U8eY) | [ztrot](https://osu.ppy.sh/users/6347) présente les avantages de devenir un osu!supporter,, y compris osu!direct - une
```suggestion
| 22 | [Supporter and osu!direct](https://www.youtube.com/watch?v=ec0pLh4U8eY) | [ztrot](https://osu.ppy.sh/users/6347) présente les avantages de devenir un osu!supporter, y compris osu!direct - une superposition qui permet de télécharger des beatmaps dans le jeu. |
```

2021-11-24 16:53 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 27 | [Guest Mapping](https://www.youtube.com/watch?v=nXWA1Qh9bT8) | [ztrot](https://osu.ppy.sh/users/6347) couvre le concept de guest mapping et explique comment créer des beatmap collaborations av
```suggestion
| 27 | [Guest Mapping](https://www.youtube.com/watch?v=nXWA1Qh9bT8) | [ztrot](https://osu.ppy.sh/users/6347) couvre le concept de guest mapping et explique comment créer des beatmaps en collaboration avec d'autres utilisateurs. |
```

2021-11-24 16:53 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +**[Time Lapse Mapping](https://www.youtube.com/playlist?list=PLmWVQsxi34bO7PAmjWZjVDi16pAy-GRBP)** est une série de vidéos animées par [ztrot](https://osu.ppy.sh/users/6347) et plusieurs mappeurs de
```suggestion
**[Time Lapse Mapping](https://www.youtube.com/playlist?list=PLmWVQsxi34bO7PAmjWZjVDi16pAy-GRBP)** est une série de vidéos animées par [ztrot](https://osu.ppy.sh/users/6347) et plusieurs mappeurs de différents modes de jeu, dans lesquelles ils expliquent le processus de création d'une beatmap avec une session de mapping accélérée en arrière-plan.
```

2021-11-30 08:31 UTC, Ganondorf-1 requested changes

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 0 | [Lazer installer setup guide](https://www.youtube.com/watch?v=kO5ISAzRbPE) | [ztrot](https://osu.ppy.sh/users/6347) couvre le processus d'installation du client osu(lazer). |
```suggestion
| 0 | [Lazer installer setup guide](https://www.youtube.com/watch?v=kO5ISAzRbPE) | [ztrot](https://osu.ppy.sh/users/6347) couvre le processus d'installation du client osu!(lazer). |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 7-2 | [Timing Basics](https://www.youtube.com/watch?v=8nsbrOhLE9w) | [ztrot](https://osu.ppy.sh/users/6347) couvre la section Timing de l'éditeur, et explique comment timer correctement un beatmap.
```suggestion
| 7-2 | [Timing Basics](https://www.youtube.com/watch?v=8nsbrOhLE9w) | [ztrot](https://osu.ppy.sh/users/6347) couvre la section Timing de l'éditeur, et explique comment timer correctement une beatmap. |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 17 | [Chat Commands](https://www.youtube.com/watch?v=yWqRJZ5FX5Y) | [ztrot](https://osu.ppy.sh/users/6347) passe en revue toutes les commandes de Tchat disponibles dans osu!. |
```suggestion
| 17 | [Chat Commands](https://www.youtube.com/watch?v=yWqRJZ5FX5Y) | [ztrot](https://osu.ppy.sh/users/6347) passe en revue toutes les commandes de tchat disponibles dans osu!. |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 22 | [Supporter and osu!direct](https://www.youtube.com/watch?v=ec0pLh4U8eY) | [ztrot](https://osu.ppy.sh/users/6347) présente les avantages de devenir un osu!supporter, y compris osu!direct - une
```suggestion
| 22 | [Supporter and osu!direct](https://www.youtube.com/watch?v=ec0pLh4U8eY) | [ztrot](https://osu.ppy.sh/users/6347) présente les avantages de devenir un osu!supporter, y compris osu!direct - une fonctionnalité qui permet de télécharger des beatmaps dans le jeu. |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 23 | [Community Modding](https://www.youtube.com/watch?v=MxlB__wjt9A) | [ztrot](https://osu.ppy.sh/users/6347) et [Shiro](https://osu.ppy.sh/users/113005) expliquer le concept de modding communauta
```suggestion
| 23 | [Community Modding](https://www.youtube.com/watch?v=MxlB__wjt9A) | [ztrot](https://osu.ppy.sh/users/6347) et [Shiro](https://osu.ppy.sh/users/113005) expliquent le concept de modding communautaire, un effort de modding en équipe. |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 25 | *Vidéo retirée* | *N/A* |
```suggestion
| 25 | *Vidéo supprimée* | *N/A* |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 31 | [Guest mapping and contributions limits](https://www.youtube.com/watch?v=s2ZK4o8V5tI) | [ztrot](https://osu.ppy.sh/users/6347) présente les règles de classement et les lignes directrices conce
```suggestion
| 31 | [Guest mapping and contributions limits](https://www.youtube.com/watch?v=s2ZK4o8V5tI) | [ztrot](https://osu.ppy.sh/users/6347) présente les règles de classement et les lignes directrices concernant le guest mapping et les beatmaps en collaboration. |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 32 | [New Ranking System](https://www.youtube.com/watch?v=wa_hNegtBw0) | [ztrot](https://osu.ppy.sh/users/6347) passe en revue les principaux changements dans le processus de classement des beatmap
```suggestion
| 32 | [New Ranking System](https://www.youtube.com/watch?v=wa_hNegtBw0) | [ztrot](https://osu.ppy.sh/users/6347) passe en revue les principaux changements dans le processus de classement des beatmaps. |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 34 | [Reporting Bugs](https://www.youtube.com/watch?v=Opsfa2wR1RY) | [Tasha](https://osu.ppy.sh/users/1031958) passe en revue les versions disponibles dans osu!, et explique comment signaler les bu
```suggestion
| 34 | [Reporting Bugs](https://www.youtube.com/watch?v=Opsfa2wR1RY) | [Tasha](https://osu.ppy.sh/users/1031958) passe en revue les versions disponibles d'osu!, et explique comment signaler les bugs en utilisant le forum Help. |
```

2021-11-30 08:31 UTC, Ganondorf-1 commented on wiki/osu!academy/fr.md
> +| 1 | [Back and Fourth Patterns](https://www.youtube.com/watch?v=Ra_hrzkyIRs) | [ztrot](https://osu.ppy.sh/users/6347) couvre le placement et le timing des motifs Back et Fourth. |
```suggestion
| 1 | [Back and Fourth Patterns](https://www.youtube.com/watch?v=Ra_hrzkyIRs) | [ztrot](https://osu.ppy.sh/users/6347) couvre le placement et le timing des motifs Back and Fourth. |
```

2021-11-30 21:25 UTC, TicClick approved these changes

2021-11-30 21:25 UTC, merged