[FR] Update `osu!talk`
ppy/osu-wiki pull request #6396
Opened 2021-11-18 18:59 UTC by DoryanR

Proposal to update the French translation of the wiki page `osu!talk`.

2021-11-19 18:31 UTC, DoryanR commented on wiki/osu!talk/fr.md
> +- [Sujet original](https://osu.ppy.sh/community/forums/Sujets/225111)
```suggestion
- [Sujet original](https://osu.ppy.sh/community/forums/topics/225111)
```

2021-11-24 16:56 UTC, Ganondorf-1 requested changes

2021-11-24 16:56 UTC, Ganondorf-1 commented on wiki/osu!talk/fr.md
> +**osu!talk** est une série de podcasts animée par [ztrot](https://osu.ppy.sh/users/6347) avec [deadbeat](https://osu.ppy.sh/users/128370) comme co-animateur. Elle se concentre sur l'interview de dive
```suggestion
**osu!talk** est une série de podcasts animée par [ztrot](https://osu.ppy.sh/users/6347) avec [deadbeat](https://osu.ppy.sh/users/128370) comme co-animateur. Elle se concentre sur l'interview de divers utilisateurs de la communauté d'osu!. En plus de cela, il peut y avoir des discussions de groupe sur les différentes choses qui se passent dans la communauté, comme les changements dans l'[équipe d'osu!](/wiki/People/The_Team), ou des problèmes de longue durée souvent discutés, comme l'overmapping.
```

2021-11-24 16:56 UTC, Ganondorf-1 commented on wiki/osu!talk/fr.md
> +| 2 | Surmapping | [Kyonko Hizara](https://osu.ppy.sh/users/444868), [Loctav](https://osu.ppy.sh/users/71366), [MMzz](https://osu.ppy.sh/users/128993), et [OnosakiHito](https://osu.ppy.sh/users/29012
```suggestion
| 2 | Overmapping | [Kyonko Hizara](https://osu.ppy.sh/users/444868), [Loctav](https://osu.ppy.sh/users/71366), [MMzz](https://osu.ppy.sh/users/128993), et [OnosakiHito](https://osu.ppy.sh/users/290128) | [Lien](https://www.youtube.com/watch?v=RepSYE3hN3A) |
```

2021-11-24 16:56 UTC, Ganondorf-1 commented on wiki/osu!talk/fr.md
> +| 1 | Remaniement du personnel | [Charles445](https://osu.ppy.sh/users/85000), [Ephemeral](https://osu.ppy.sh/users/102335), et [OnosakiHito](https://osu.ppy.sh/users/290128) | [Lien](https://www.you
```suggestion
| 1 | Remaniement du staff | [Charles445](https://osu.ppy.sh/users/85000), [Ephemeral](https://osu.ppy.sh/users/102335), et [OnosakiHito](https://osu.ppy.sh/users/290128) | [Lien](https://www.youtube.com/watch?v=c10Jiq1xZus) |
```

2021-11-24 16:56 UTC, Ganondorf-1 commented on wiki/osu!talk/fr.md
> +| 7 | Difficultés des invités par rapport à l'ensemble des mappeurs | [Doomsday](https://osu.ppy.sh/users/18983), [shARPII](https://osu.ppy.sh/users/776257), et [WubWoofWolf](https://osu.ppy.sh/users
```suggestion
| 7 | Les guest difficulties par rapport à l'ensemble des mappeurs | [Doomsday](https://osu.ppy.sh/users/18983), [shARPII](https://osu.ppy.sh/users/776257), et [WubWoofWolf](https://osu.ppy.sh/users/39828) | [Lien](https://www.youtube.com/watch?v=OMsHFRS662k) |
```

2021-11-24 16:56 UTC, Ganondorf-1 commented on wiki/osu!talk/fr.md
> +| 25 | Règles créés par la communauté | [Shawdooow](https://osu.ppy.sh/users/7726082), [ColdVolcano](https://osu.ppy.sh/users/7492333), et [andy840119](https://osu.ppy.sh/users/1030492) | [Lien](http
```suggestion
| 25 | Règles créées par la communauté | [Shawdooow](https://osu.ppy.sh/users/7726082), [ColdVolcano](https://osu.ppy.sh/users/7492333), et [andy840119](https://osu.ppy.sh/users/1030492) | [Lien](https://www.youtube.com/watch?v=0nuLwWejdII) |
```

2021-11-28 18:22 UTC, TicClick approved these changes

2021-11-28 18:25 UTC, merged