[FR] Update `osu!tourney`, `Multiplayer_Usage`, `Setup`, `Skinning`, `Spectator_Usage`, `Tournament_Management_Commands`, Add `osu!lazer_tournament_client`
ppy/osu-wiki pull request #6399
Opened 2021-11-19 13:12 UTC by DoryanR

Update of the translations of the following wiki pages:

- `osu!tourney`
- `osu!tourney/Multiplayer_Usage`
- `osu!tourney/Setup`
- `osu!tourney/Skinning`
- `osu!tourney/Spectator_Usage`
- `osu!tourney/Tournament_Management_Commands`

Proposal for the French translation of the wiki page `osu!lazer_tournament_client`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-19 14:19 UTC, DoryanR commented on wiki/osu!tourney/Multiplayer_Usage/fr.md
> +## Création de match
```suggestion
# Utilisation de osu!tourney en multijoueur

## Création de match
```

2021-11-19 14:19 UTC, DoryanR commented on wiki/osu!tourney/Setup/fr.md
>  Pour ce faire, copiez `osu!.exe` dans un dossier vide et lancez-le. Une nouvelle installation d'osu! sera créée. C'est la seule installation qui sera modifiée.
```suggestion
Il est recommandé d'utiliser une **nouvelle installation d'osu!**. La base de données Songs peut être corrompue. Vous pouvez avoir plusieurs installations d'osu!, gardez-les juste dans des dossiers séparés.
Pour ce faire, copiez `osu!.exe` dans un dossier vide et lancez-le. Une nouvelle installation d'osu! sera créée. C'est la seule installation qui sera modifiée.
```

2021-11-19 14:19 UTC, DoryanR commented on wiki/osu!tourney/osu!lazer_tournament_client/fr.md
> +    - videos
```suggestion
- your-tournament
  - flags
  - mods
  - videos
```

2021-11-24 16:48 UTC, Ganondorf-1 requested changes

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Multiplayer_Usage/fr.md
> +Si la valeur est défini sur `Test Tourney`, le modèle apparaîtra comme `Test Tourney: (Nom de l'équipe 1) vs (Nom de l'équipe 2)`.
```suggestion
Si la valeur est définie sur `Test Tourney`, le modèle apparaîtra comme `Test Tourney: (Nom de l'équipe 1) vs (Nom de l'équipe 2)`.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Multiplayer_Usage/fr.md
>  Pas exemple, avec `TeamSize = 4`, les première, deuxième, troisième et quatrième positions appartiendront à l'équipe bleue, et les cinquième, sixième, septième et huitième positions appartiendront à
```suggestion
Par exemple, avec `TeamSize = 4`, les première, deuxième, troisième et quatrième positions appartiendront à l'équipe bleue, et les cinquième, sixième, septième et huitième positions appartiendront à l'équipe rouge. Avec `TeamSize = 3`, les première, deuxième et troisième positions appartiendront à l'équipe bleue et les quatrième, cinquième et sixième positions appartiendront à l'équipe rouge.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Setup/fr.md
> +Il est recommandé d'utiliser une **nouvelle installation d'osu!**. La base de données Songs peut être corrompue. Vous pouvez avoir plusieurs installations d'osu!, gardez-les juste dans des dossiers s
```suggestion
Il est recommandé d'utiliser une **nouvelle installation d'osu!**. La base de données Songs peut être corrompue. Vous pouvez avoir plusieurs installations d'osu!, gardez-les alors dans des dossiers séparés.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Setup/fr.md
> +- `acronym` : Une abréviation pour le tournois. Cela affecte le nom de la salle du tournoi, vérifiez l'[utilisation de osu!tourney en multijoueur](/wiki/osu!tourney/Multiplayer_Usage) pour plus d'inf
```suggestion
- `acronym` : Une abréviation pour le tournoi. Cela affecte le nom de la salle du tournoi, vérifiez l'[utilisation de osu!tourney en multijoueur](/wiki/osu!tourney/Multiplayer_Usage) pour plus d'informations.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Skinning/fr.md
> +Le client supporte plusieurs modifications pour que vous puissiez le customisez pour le tournoi. Pour ce faire, vous devrez créer la structure de fichier `/Skins/User/tournament` dans le dossier d'in
```suggestion
Le client prend en charge plusieurs modifications pour que vous puissiez le customisez pour le tournoi. Pour ce faire, vous devrez créer la structure de fichier `/Skins/User/tournament` dans le dossier d'installation du client. Les éléments du skin peuvent être placés dans le dossier et supportent les fichiers `.jpg` et `.png`.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Skinning/fr.md
> +Les éléments suivants peuvent être skinné :
```suggestion
Les éléments suivants peuvent être skinnés :
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Skinning/fr.md
> +- `background` - L'arrière-plan utilisée par le client. L'arrière-plan par défaut pour osu!tourney peut être trouvé [ici](https://s.ppy.sh/images/tournament/default.png).
```suggestion
- `background` - L'arrière-plan utilisé par le client. L'arrière-plan par défaut pour osu!tourney peut être trouvé [ici](https://s.ppy.sh/images/tournament/default.png).
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Skinning/fr.md
>  - `background-win1` (optionnel) - l'image qui sera affichée en fondue après que l'équipe bleue a gagnée, pendant que les résultats du match sont affichés.
```suggestion
- `background-win1` (optionnel) - l'image qui sera affichée en fondu si l'équipe bleue gagne, pendant que les résultats du match sont affichés.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Skinning/fr.md
>  - `background-win2` (optionnel) - l'image qui sera affichée en fondue après que l'équipe rouge a gagnée, pendant que les résultats du match sont affichés.
```suggestion
- `background-win2` (optionnel) - l'image qui sera affichée en fondu si l'équipe rouge gagne, pendant que les résultats du match sont affichés.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Spectator_Usage/fr.md
> +- `Panic` : Appuyez dessus quand quelque chose se passe mal, par exemple une fenêtre n'est pas spectateur d'un utilisateur ou une fenêtre a crashée. Cela réinitialisera toutes les instances d'osu!.
```suggestion
- `Panic` : Appuyez dessus quand quelque chose se passe mal, par exemple une fenêtre n'affiche pas le gameplay d'un joueur ou une fenêtre a crashé. Cela réinitialisera toutes les instances d'osu!.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +Les commandes de tchat suivantes sont faitesLes commandes de tchat suivantes sont fournies pour la gestion à distance des salles de tournoi multi-joueurs :
```suggestion
Les commandes de tchat suivantes sont fournies pour la gestion à distance des salles de tournoi multijoueurs :
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +- `!mp lock` - Verrouille la salle pour que les joueurs ne puissent pas changer d'équipe et de créneau.
```suggestion
- `!mp lock` - Verrouille la salle pour que les joueurs ne puissent pas changer d'équipe et d'emplacement.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +- `!mp size <size>` - Définit le nombre de créneaux disponibles (1 à 16) dans la pièce.
```suggestion
- `!mp size <size>` - Définit le nombre d'emplacements disponibles (1 à 16) dans la pièce.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +- `!mp move <username> <slot>` - Déplace un joueur dans la salle vers l'emplacement indexé 1 spécifié.
```suggestion
- `!mp move <username> <slot>` - Déplace un joueur présent dans la salle vers l'emplacement spécifié.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +- `!mp map <mapid> [<playmode>]` - Change la beatmap et le playmode de la salle.
```suggestion
- `!mp map <mapid> [<playmode>]` - Change la beatmap et le mode de jeu de la salle.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +- `!mp mods <mod> [<mod>] [<mod>] …` - Supprime tous les mods actuellement appliqués et applique ces mods à la pièce.
```suggestion
- `!mp mods <mod> [<mod>] [<mod>] …` - Supprime tous les mods actuellement appliqués et applique ces mods à la salle.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +Le host original d'une salle multijoueur peut aussi utiliser ces commandes. Si le host originel quitte, le host suivant n'héritera pas des commandes. Le host originel sera capable de réutiliser les c
```suggestion
Le créateur d'une salle multijoueur peut aussi utiliser ces commandes. Si le créateur quitte la salle, l'hôte suivant n'héritera pas des commandes. Le créateur de la salle pourra réutiliser les commandes s'il rejoint la salle à nouveau.
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/Tournament_Management_Commands/fr.md
> +Voici un exemple d'utilisation des commande :
```suggestion
Voici un exemple d'utilisation des commandes :
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/osu!lazer_tournament_client/fr.md
> +Les utilisateurs rencontrant des problèmes avec le client peuvent [créer un issues sur GitHub](https://github.com/ppy/osu/issues) ou envoyer un courriel à [tournaments@ppy.sh](mailto:tournaments@ppy.
```suggestion
Les utilisateurs rencontrant des problèmes avec le client peuvent [créer un issue sur GitHub](https://github.com/ppy/osu/issues) ou envoyer un courriel à [tournaments@ppy.sh](mailto:tournaments@ppy.sh).
```

2021-11-24 16:48 UTC, Ganondorf-1 commented on wiki/osu!tourney/osu!lazer_tournament_client/fr.md
> +Pour lancer le osu!lazer tournament client,, vous devez spécifier un argument de lancement à l'exécutable osu!lazer. Pour ce faire, créez un nouveau raccourci sur le bureau et définissez son emplacem
```suggestion
Pour lancer le osu!lazer tournament client, vous devez spécifier un argument de lancement à l'exécutable osu!lazer. Pour ce faire, créez un nouveau raccourci sur le bureau et définissez son emplacement à `%LOCALAPPDATA%/osulazer/osu !.exe --tournament`. Ce raccourci spécifique lancera osu!lazer en mode client de tournoi.
```

2021-11-28 18:15 UTC, TicClick approved these changes

2021-11-28 18:16 UTC, merged