[FR] Update `Help_Centre/Account`
ppy/osu-wiki pull request #6402
Opened 2021-11-19 20:28 UTC by DoryanR

Proposal to update the French translation of the wiki page `Help_Centre/Account`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-24 17:17 UTC, Ganondorf-1 requested changes

2021-11-24 17:17 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +L'interdiction de participer à un tournoi est, comme son nom l'indique, une interdiction de participer à tous les tournois officiels.
```suggestion
Un ban des tournois est, comme son nom l'indique, une interdiction de participer à tous les tournois officiels.
```

2021-11-24 17:17 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +### Qu'est-ce qu'un ban de tournoi ?
```suggestion
### Qu'est-ce qu'un ban des tournois ?
```

2021-11-24 17:17 UTC, Ganondorf-1 commented on wiki/Help_Centre/Account/fr.md
> +La plupart des bannissement de tournois ont une durée déterminée, allant de 3 mois à un an ou plus. Certains bannissements peuvent être permanents. Quelle que soit la durée du ban, touts les bans des
```suggestion
La plupart des bans des tournois ont une durée déterminée, allant de 3 mois à un an ou plus. Certains bannissements peuvent être permanents. Quelle que soit la durée du ban, tous les bans des tournois sont **irrévocables** et ne peuvent faire l'objet d'un appel comme les restrictions.
```

2021-11-28 17:55 UTC, TicClick approved these changes

2021-11-28 18:01 UTC, merged