[FR] Update `Mapping_and_Modding_Timeline`
ppy/osu-wiki pull request #6407
Opened 2021-11-20 14:13 UTC by DoryanR

Proposal to update the French translation of the wiki page `Mapping_and_Modding_Timeline`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-24 17:13 UTC, Ganondorf-1 requested changes

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Tous les candidats doivent se soumettre à l'application, mais les membres du groupe qui reviennent bénéficient d'un délai d'attente plus court et sont autorisés à fournir 1 à 2 mois d'activité de
```suggestion
  - Tous les candidats doivent se soumettre à la candidature, mais les membres du groupe qui reviennent bénéficient d'un délai d'attente plus court et sont autorisés à fournir 1 à 2 mois d'activité de modding au lieu de la norme précédente de 3 mois.
```

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **16/03/2021 :** Les Beatmap Nominators ont reçu un renouvellement automatique de leur adhésion à osu!supporter.
```suggestion
- **16/03/2021 :** Les Beatmap Nominators ont reçu un renouvellement automatique de leur tag osu!supporter.
```

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Ce changement a été effectué en réponse à un manque d'incitations pour les membres dévoués de la scène de mapping.
```suggestion
  - Ce changement a été effectué en réponse à un manque de récompense pour les membres dévoués de la scène de mapping.
```

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **08/04/2021 :** Une règle de critères de classement interdisant plusieurs beatmaps qualifiées pour la même musique a été supprimée.
```suggestion
- **08/04/2021 :** Une règle des critères de classement interdisant plusieurs beatmaps qualifiées pour la même musique a été supprimée.
```

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **12/05/2021 :** La Nomination Assessment Team a commencé un essai pour les nouvelles évaluations des Beatmap Nominator.
```suggestion
- **12/05/2021 :** La Nomination Assessment Team a commencé un essai pour les nouvelles évaluations des Beatmap Nominators.
```

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +  - Cela a permis aux créateurs de difficultés invités de résoudre les problèmes sur leurs beatmaps. Avant ce changement, seul l'hôte du mapset pouvait résoudre les problèmes, ce qui constituait une
```suggestion
  - Cela a permis aux créateurs de guest difficulties de résoudre les problèmes sur leurs beatmaps. Avant ce changement, seul l'hôte du mapset pouvait résoudre les problèmes, ce qui constituait une frustration majeure pour les mappeurs.
```

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **14/06/2021 :** La Global Moderation Team a commencé à accepter les candidatures d'utilisateurs axés sur le mapping afin de réduire les tensions croissantes entre la scène GMT et la scène de la ma
```suggestion
- **14/06/2021 :** La Global Moderation Team a commencé à accepter les candidatures d'utilisateurs axés sur le mapping afin de réduire les tensions croissantes entre la GMT et la scène de mapping/modding.
```

2021-11-24 17:13 UTC, Ganondorf-1 commented on wiki/Mapping_and_Modding_Timeline/fr.md
> +- **14/08/2021 :** osu!taiko a commencé un essai des évaluations des Beatmap Nominator en imitant l'essai d'osu! du 12/05/2021.
```suggestion
- **14/08/2021 :** osu!taiko a commencé un essai des évaluations des Beatmap Nominators en imitant l'essai d'osu! du 12/05/2021.
```

2021-11-28 18:23 UTC, TicClick approved these changes

2021-11-28 18:26 UTC, merged