[FR] Update `Mascots`
ppy/osu-wiki pull request #6409
Opened 2021-11-20 14:49 UTC by DoryanR

Proposal to update the French translation of the wiki page `Mascots`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-20 14:51 UTC, DoryanR commented on wiki/Mascots/fr.md
> +Conçues par [xiemon](https://osu.ppy.sh/users/5203667) après avoir été repérées lors du [Most Manic Art Contest] (https://osu.ppy.sh/community/contests/80) et annoncées comme les mascottes officielle
```suggestion
Conçues par [xiemon](https://osu.ppy.sh/users/5203667) après avoir été repérées lors du [Most Manic Art Contest](https://osu.ppy.sh/community/contests/80) et annoncées comme les mascottes officielles d'osu!mania le 18/09/2020, Mani et Mari sont des jumelles qui ne se supportent pas vraiment, mais qui se ressemblent plus qu'elles ne veulent l'admettre.
```

2021-11-24 17:02 UTC, Ganondorf-1 requested changes

2021-11-24 17:02 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +Conçue par [pyun](https://osu.ppy.sh/users/981534), Chirou est l'une des participantes au concours de création de mascotte d'osu!taiko. Elle est très stricte et exigeante, elle est perfectionniste et
```suggestion
Conçue par [pyun](https://osu.ppy.sh/users/981534), Chirou est l'une des participantes au concours de création de mascotte d'osu!taiko. Elle est très stricte et exigeante, elle est perfectionniste et n'aime pas faire des erreurs, surtout dans son travail avec osu!taiko. Mais au-delà de sa forte personnalité, si on arrive à toucher son point faible, elle peut être douce et mignonne. Elle a 14 ans, est née le 25 octobre et est de groupe sanguin AB. Elle mesure 149 centimètres et pèse 45 kilogrammes. Ses passe-temps sont la pratique du tambour, la chaleur de sa cape et la collecte de pierres précieuses ou de roches. Chirou a fait quelques apparitions dans les fanarts de différents utilisateurs.
```

2021-11-30 08:13 UTC, Ganondorf-1 requested changes

2021-11-30 08:13 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +*Pour les newspost, voir : [Meet Yuzu!](https://osu.ppy.sh/home/news/2014-06-21-meet-yuzu) et [Introducing Yuzu's New Look](https://osu.ppy.sh/home/news/2019-01-09-introducing-yuzu)*
```suggestion
*Pour les newsposts, voir : [Meet Yuzu!](https://osu.ppy.sh/home/news/2014-06-21-meet-yuzu) et [Introducing Yuzu's New Look](https://osu.ppy.sh/home/news/2019-01-09-introducing-yuzu)*
```

2021-11-30 08:13 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +Yuzu est la mascotte d'osu!catch qui a rejoint le 22/06/2014. Il est né le 10/04/2000, mesure 172 centimètres et pèse 65 kilogrammes. Son design actuel a été conçu par [Thievley](https://osu.ppy.sh/u
```suggestion
Yuzu est la mascotte d'osu!catch qui a rejoint le 22/06/2014. Il est né le 10/04/2000, mesure 172 centimètres et pèse 65 kilogrammes. Son design actuel a été conçu par [Thievley](https://osu.ppy.sh/users/4717672). Son design initial et les sprites de l'attrapeur ont été réalisés par [ztrot](https://osu.ppy.sh/users/6347). Daru a créé le graphisme du comboburst.
```

2021-11-30 08:13 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +> Il est le leader au sang chaud de l'équipe des pom-pom girls. Il a une bonne âme et aide ceux qui sont en détresse autour de lui en se levant et en se battant pour eux !
```suggestion
> Il est le leader au sang chaud du cheer squad. Il a une bonne âme et aide ceux qui sont en détresse autour de lui en se levant et en se battant pour eux !
```

2021-11-30 08:13 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +Agent J figure également dans le skin de [LuigiHann](https://osu.ppy.sh/users/1079), [Elite Beat osu! HD (1.0 Complete!)](https://osu.ppy.sh/community/forums/topics/190357).
```suggestion
L'agent J figure également dans le skin de [LuigiHann](https://osu.ppy.sh/users/1079), [Elite Beat osu! HD (1.0 Complete!)](https://osu.ppy.sh/community/forums/topics/190357).
```

2021-11-30 08:13 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +> Don est le protagoniste de la série [Taiko no Tatsujin](https://fr.wikipedia.org/wiki/Taiko_no_Tatsujin). Il est un tambour de taiko avec un bord blanc et quatre jambes, un visage rouge (qui semble
```suggestion
> Don est le protagoniste de la série [Taiko no Tatsujin](https://fr.wikipedia.org/wiki/Taiko_no_Tatsujin). Il est un tambour de taiko avec un bord blanc et quatre jambes, un visage rouge (qui semble être orange moly), et un corps bleu clair. Le rêve de Don est de partager la beauté du Taiko avec le monde entier. Trois ans ont passé depuis qu'il a emménagé dans la Wada House, et il est devenu assez populaire en ville. Il a un appétit monstrueux et fait parfois des achats coûteux à la Wada House, ce qui peut le conduire au pire. Il termine généralement ses phrases par "Ta-don", ce qui signifie "Ba-dum" en japonais.
```

2021-11-30 08:13 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +和田どん (Wada Don), également connu sous le nom de Don ou Don-chan, est l'une des mascottes d'osu!taiko qui a rejoint le groupe le 05/2008. Il mesure 48 centimètres et pèse plus de 100 kilogrammes. Il a
```suggestion
和田どん (Wada Don), également connu sous le nom de Don ou Don-chan, est l'une des mascottes d'osu!taiko qui a rejoint le groupe en mai 2008. Il mesure 48 centimètres et pèse plus de 100 kilogrammes. Il apparaît dans le skin d'osu!taiko. Son dessin a été conçu par Yukiko Yokoo (横尾有希子) et sa voix a été interprétée par Narahashi Miki (楢橋 美紀).
```

2021-11-30 08:13 UTC, Ganondorf-1 commented on wiki/Mascots/fr.md
> +Conçue par [JMC](https://osu.ppy.sh/users/774010), Aiko est l'une des participantes au concours de création de la mascotte d'osu!taiko. C'est une fille énergique et passionnée d'osu!taiko, même si el
```suggestion
Conçue par [JMC](https://osu.ppy.sh/users/774010), Aiko est l'une des participantes au concours de création de mascotte d'osu!taiko. C'est une fille énergique et passionnée d'osu!taiko, même si elle n'est pas la meilleure dans ce domaine ! Portant une paire de chaussures "Tabi" et une ribambelle d'accessoires en pippidon, la mascotte d'antan vit dans cette fille pleine d'entrain. Elle est assez petite, 154 centimètres, et est née le 06/04/1999.
```

2021-11-30 21:46 UTC, TicClick approved these changes

2021-11-30 21:46 UTC, merged