[FR] Update `Medals/Unlock_requirements/Dedication`, `Medals/Unlock_requirements`, `Medals/Legacy_Beatmap_Packs`, `Medals`
ppy/osu-wiki pull request #6410
Opened 2021-11-20 17:45 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Medals`
- `Medals/Legacy_Beatmap_Packs`
- `Medals/Unlock_requirements/Dedication`
- `Medals/Unlock_requirements`

Last PR from me while waiting for the rest of my PR to be merged (inactivity or not), because it starts to be too much in progress.
In any case a big part of the translation/update is done, there are still articles that are either in `need_cleanup`, `outdated` or with `TODO` that need an update on the English side.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-11-20 17:51 UTC, DoryanR commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +Les beatmap packs font partie intégrante de la communauté d'osu! depuis [leur première introduction] (https://osu.ppy.sh/community/forums/topics/1853) par ![][flag_US] [Saturos](https://osu.ppy.sh/us
```suggestion
Les beatmap packs font partie intégrante de la communauté d'osu! depuis [leur première introduction](https://osu.ppy.sh/community/forums/topics/1853) par ![][flag_US] [Saturos](https://osu.ppy.sh/users/3781) en 2008, où certains packs étaient liés à certaines [médailles](/wiki/Medals). Cependant, comme osu! et sa communauté ont continué à se développer au fil des ans, le méta-mapping a également subi un changement majeur par rapport à ses débuts et - en raison d'une énorme demande du public - [le 16 janvier 2016](https://osu.ppy.sh/home/news/2016-01-18-osuweekly-44) une révision majeure a été faite à de nombreux beatmap packs afin de les garder, dans leur ensemble, pertinents avec le temps.
```

2021-11-20 17:51 UTC, DoryanR commented on wiki/Medals/Unlock_requirements/Dedication/fr.md
> +| 4,000,000 Keys | Frapper un total de 4 000 000 keys dans osu!mania. | Is this the end of the rainbow? |
```suggestion
| 400,000 Keys | Frapper un total de 400 000 keys dans osu!mania. | Four hundred thousand and still not even close. |
| 4,000,000 Keys | Frapper un total de 4 000 000 keys dans osu!mania. | Is this the end of the rainbow? |

```

2021-11-20 17:51 UTC, DoryanR commented on wiki/Medals/fr.md
```suggestion
```

2021-11-20 17:51 UTC, DoryanR commented on wiki/Medals/fr.md
> +Les médailles **Beatmap Spotlights** sont des médailles attribuées après avoir terminé certains beatmap pack publiés dans le cadre des [Monthly Beatmap Spotlights] (https://osu.ppy.sh/home/news/2017-
```suggestion
Les médailles **Beatmap Spotlights** sont des médailles attribuées après avoir terminé certains beatmap pack publiés dans le cadre des [Monthly Beatmap Spotlights](https://osu.ppy.sh/home/news/2017-03-18-introducing-to-you-spotlights). Pour débloquer les médailles de cette catégorie, un joueur doit jouer toutes les maps *de l'un des quatre packs de mode de jeu* qui sont en compétition dans le classement Beatmap Spotlights correspondant. L'utilisation de [mods de réduction de la difficulté](/wiki/Game_modifier#difficulté-réduite) ou de [mods d'augmentation de la difficulté](/wiki/Game_modifier#difficulté-augmenté) est autorisée.
```

2021-11-20 17:51 UTC, DoryanR commented on wiki/Medals/fr.md
> +Les médailles **Seasonal Spotlights** sont des médailles attribuées après avoir terminé certains beatmap pack publiés dans le cadre de la campagne [Seasonal Spotlights] (https://osu.ppy.sh/home/news/
```suggestion
Les médailles **Seasonal Spotlights** sont des médailles attribuées après avoir terminé certains beatmap pack publiés dans le cadre de la campagne [Seasonal Spotlights](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018). Pour débloquer les médailles de cette catégorie, un joueur doit jouer toutes les maps *de l'un des quatre packs de mode de jeu* qui sont en compétition dans le tableau de classement des Seasonal Spotlights correspondants. L'utilisation de [mods de réduction de la difficulté](/wiki/Game_modifier#difficulté-réduite) ou de [mods d'augmentation de la difficulté](/wiki/Game_modifier#difficulté-augmenté) est autorisée.
```

2021-11-20 17:51 UTC, DoryanR commented on wiki/Medals/fr.md
> +Bien que les Seasonal Spotlights aient été supprimés au début de l'année 2020 en faveur du [système actuel des Beatmap Spotlights] (/wiki/Beatmap_Spotlights), toutes les médailles qui s'y rapportent
```suggestion
Bien que les Seasonal Spotlights aient été supprimés au début de l'année 2020 en faveur du [système actuel des Beatmap Spotlights](/wiki/Beatmap_Spotlights), toutes les médailles qui s'y rapportent peuvent encore être obtenues à ce jour.
```

2021-11-20 17:51 UTC, DoryanR commented on wiki/Medals/fr.md
> +Les médailles **Beatmap Challenge Packs**, ou encore appelées [*Skill Packs medals*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers-guild#pack-medal-updates)
```suggestion
Les médailles **Beatmap Challenge Packs**, ou encore appelées [*Skill Packs medals*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers-guild#pack-medal-updates), sont des médailles attribuées après avoir franchi le niveau de difficulté le plus élevé de toutes les beatmaps contenus dans certains [Theme Beatmap Packs](https://osu.ppy.sh/beatmaps/packs?type=theme) ou [Artist/Album Beatmap Packs](https://osu.ppy.sh/beatmaps/packs?type=artist) *sans [mods de réduction de la difficulté](/wiki/Game_modifier#difficulté-réduite) activés*. Ces beatmap pack sont spécialement conçus pour tester la compréhension de chaque joueur de divers aspects du jeu en fonction d'un niveau de compétence spécifique, par exemple dans une plage de [star ranting](/wiki/Beatmapping/Star_rating) ou de difficulté maximale.
```

2021-11-24 16:11 UTC, Ganondorf-1 requested changes

2021-11-24 16:11 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +¹ *[Loituma - Ievan Polkka](https://osu.ppy.sh/beatmapsets/2463) est un beatmap non classé. Il n'est pas nécessaire de jouer cette beatmap pour compléter le pack.*
```suggestion
¹ *[Loituma - Ievan Polkka](https://osu.ppy.sh/beatmapsets/2463) est une beatmap non classée. Il n'est pas nécessaire de jouer cette beatmap pour compléter le pack.*
```

2021-11-24 16:11 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- La beatmap [Loituma - Ievan Polkka](https://osu.ppy.sh/beatmapsets/2463), qui était inclus dans le Internet Pack (Volume 1), était connu pour avoir été poussé dans la catégorie [approuvé](/wiki/Bea
```suggestion
- La beatmap [Loituma - Ievan Polkka](https://osu.ppy.sh/beatmapsets/2463), qui était incluse dans le Internet Pack (Volume 1), était connue pour avoir été poussée dans la catégorie [approuvée](/wiki/Beatmap/Category#approuvée) alors qu'elle ne comportait qu'un seul spinner. Bien que la beatmap ait été [retirée de la liste des beatmaps approuvées peu de temps après](https://osu.ppy.sh/community/forums/posts/149328), ses restes sont néanmoins restés sur le Internet Pack (Volume 1).
```

2021-11-24 16:11 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Tous les beatmaps doivent être réalisés dans le mode de jeu [osu!](/wiki/Game_mode/osu!) pour obtenir le badge, sauf indication contraire. L'utilisation de [mods de réduction de la difficulté](/wiki/
```suggestion
Toutes les beatmaps doivent être jouées dans le mode de jeu [osu!](/wiki/Game_mode/osu!) pour obtenir le badge, sauf indication contraire. L'utilisation de [mods de réduction de la difficulté](/wiki/Game_modifier#difficulté-réduite) ou de [mods d'augmentation de la difficulté](/wiki/Game_modifier#difficulté-augmenté) est autorisée.
```

2021-11-24 16:11 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Les médailles **Skill** sont des médailles attribuées à la suite de divers accomplissements basés sur les compétences, que ce soit en atteignant certains jalons de [combo](/wiki/Beatmapping/Combo), e
```suggestion
Les médailles **Skill** sont des médailles attribuées à la suite de divers accomplissements basés sur les compétences, que ce soit en atteignant certains seuils de [combo](/wiki/Beatmapping/Combo), en atteignant certains rangs dans le [classement global des points de performance](https://osu.ppy.sh/rankings/osu/performance), ou en réalisant un clear ou un [full combo](/wiki/Full_combo) sur n'importe quel beatmap [qualifiée](/wiki/Beatmap/Category#qualifiée), [classée](/wiki/Beatmap/Category#classée), ou [approuvée](/wiki/Beatmap/Category#approuvée) dans certaines fourchettes de [star rating](/wiki/Beatmapping/Star_rating).
```

2021-11-24 16:11 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Les médailles **Beatmap Challenge Packs**, ou encore appelées [*Skill Packs medals*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers-guild#pack-medal-updates)
```suggestion
Les médailles **Beatmap Challenge Packs**, ou encore appelées [*Skill Packs medals*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers-guild#pack-medal-updates), sont des médailles attribuées après avoir franchi le niveau de difficulté le plus élevé de toutes les beatmaps contenues dans certains [Theme Beatmap Packs](https://osu.ppy.sh/beatmaps/packs?type=theme) ou [Artist/Album Beatmap Packs](https://osu.ppy.sh/beatmaps/packs?type=artist) *sans [mods de réduction de la difficulté](/wiki/Game_modifier#difficulté-réduite) activés*. Ces beatmap packs sont spécialement conçus pour tester la compréhension de chaque joueur de divers aspects du jeu en fonction d'un niveau de compétence spécifique, par exemple dans une fourchette de [star rating](/wiki/Beatmapping/Star_rating) ou de difficulté maximale.
```

2021-11-28 14:18 UTC, Ganondorf-1 requested changes
Que s'est-il passé ? Tous les "and" ont été traduits en "et" dans les noms des artistes et des chansons ; j'espère ne pas en avoir loupé

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [Horie Yui with UNSCetAL - Scramble](https://osu.ppy.sh/beatmapsets/2329)
```suggestion
- [Horie Yui with UNSCANDAL - Scramble](https://osu.ppy.sh/beatmapsets/2329)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [Akemi Keta - 1000% Sparking!](https://osu.ppy.sh/beatmapsets/9556)
```suggestion
- [Akemi Kanda - 1000% Sparking!](https://osu.ppy.sh/beatmapsets/9556)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [The Delgados - The Light Before We Let](https://osu.ppy.sh/beatmapsets/14694)
```suggestion
- [The Delgados - The Light Before We Land](https://osu.ppy.sh/beatmapsets/14694)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [WalnutFaceBret - C-O-C-A-I-N-E](https://osu.ppy.sh/beatmapsets/5823)
```suggestion
- [WalnutFaceBrand - C-O-C-A-I-N-E](https://osu.ppy.sh/beatmapsets/5823)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [The Lonely Islet - Shrooms](https://osu.ppy.sh/beatmapsets/8690)
```suggestion
- [The Lonely Island - Shrooms](https://osu.ppy.sh/beatmapsets/8690)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [The Lonely Islet (Feat. Justin Timberlake) - Motherlover](https://osu.ppy.sh/beatmapsets/15628)
```suggestion
- [The Lonely Island (Feat. Justin Timberlake) - Motherlover](https://osu.ppy.sh/beatmapsets/15628)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [BRetY - The Festival of Ghost 2](https://osu.ppy.sh/beatmapsets/3302)
```suggestion
- [BRANDY - The Festival of Ghost 2](https://osu.ppy.sh/beatmapsets/3302)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/Legacy_Beatmap_Packs/fr.md
> +- [Brety - Visual Dream](https://osu.ppy.sh/beatmapsets/4954)
```suggestion
- [Brandy - Visual Dream](https://osu.ppy.sh/beatmapsets/4954)
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Toutes les beatmaps doivent être jouées dans le mode de jeu [osu!](/wiki/Game_mode/osu!) pour obtenir le badge, sauf indication contraire. L'utilisation de [mods de réduction de la difficulté](/wiki/
```suggestion
Toutes les beatmaps doivent être jouées dans le mode de jeu [osu!](/wiki/Game_mode/osu!) pour obtenir le badge, sauf indication contraire. L'utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) ou de [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée) est autorisée.
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Il convient toutefois de noter que le contenu de tous les Packs Video Game Packs, Anime Packs, Internet! Packs et Rhythm Game Packs a été considérablement modifié depuis [leur première introduction e
```suggestion
Il convient toutefois de noter que le contenu de tous les packs Video Game Packs, Anime Packs, Internet! Packs et Rhythm Game Packs a été considérablement modifié depuis [leur première introduction en 2008](https://osu.ppy.sh/community/forums/topics/1853). Pour la liste de ces beatmaps packs dans leur état d'origine, voir [Anciens beatmaps packs](/wiki/Medals/Legacy_Beatmap_Packs).
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Les médailles **Skill** sont des médailles attribuées à la suite de divers accomplissements basés sur les compétences, que ce soit en atteignant certains seuils de [combo](/wiki/Beatmapping/Combo), e
```suggestion
Les médailles **Skill** sont des médailles attribuées à la suite de divers accomplissements basés sur les compétences, que ce soit en atteignant certains seuils de [combo](/wiki/Beatmapping/Combo), en atteignant certains rangs dans le [classement global des points de performance](https://osu.ppy.sh/rankings/osu/performance), ou en réalisant un clear ou un [full combo](/wiki/Full_combo) sur n'importe quelle beatmap [qualifiée](/wiki/Beatmap/Category#qualifiée), [classée](/wiki/Beatmap/Category#classée), ou [approuvée](/wiki/Beatmap/Category#approuvée) dans certaines fourchettes de [star rating](/wiki/Beatmapping/Star_rating).
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Les médailles **Beatmap Spotlights** sont des médailles attribuées après avoir terminé certains beatmap pack publiés dans le cadre des [Monthly Beatmap Spotlights](https://osu.ppy.sh/home/news/2017-0
```suggestion
Les médailles **Beatmap Spotlights** sont des médailles attribuées après avoir terminé certains beatmap packs publiés dans le cadre des [Monthly Beatmap Spotlights](https://osu.ppy.sh/home/news/2017-03-18-introducing-to-you-spotlights). Pour débloquer les médailles de cette catégorie, un joueur doit jouer toutes les maps *de l'un des quatre packs de mode de jeu* qui sont en compétition dans le classement Beatmap Spotlights correspondant. L'utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) ou de [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée) est autorisée.
```

2021-11-28 14:18 UTC, Ganondorf-1 commented on wiki/Medals/fr.md
> +Les médailles **Seasonal Spotlights** sont des médailles attribuées après avoir terminé certains beatmap pack publiés dans le cadre de la campagne [Seasonal Spotlights](https://osu.ppy.sh/home/news/2
```suggestion
Les médailles **Seasonal Spotlights** sont des médailles attribuées après avoir terminé certains beatmap packs publiés dans le cadre de la campagne [Seasonal Spotlights](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018). Pour débloquer les médailles de cette catégorie, un joueur doit jouer toutes les maps *de l'un des quatre packs de mode de jeu* qui sont en compétition dans le tableau de classement des Seasonal Spotlights correspondants. L'utilisation de [mods réduisant la difficulté](/wiki/Game_modifier#difficulté-réduite) ou de [mods augmentant la difficulté](/wiki/Game_modifier#difficulté-augmentée) est autorisée.
```

2021-11-28 18:36 UTC, TicClick approved these changes

2021-11-28 18:37 UTC, merged