[DE] Update `Internet_Relay_Chat`
ppy/osu-wiki pull request #6413
Opened 2021-11-20 21:30 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-11-20 21:50 UTC, respektive requested changes

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +*Für mehr Informationen, siehe: [Internet Relay Chat (Wikipedia)](https://en.wikipedia.org/wiki/Internet_Relay_Chat)*
```suggestion
*Für mehr Informationen, siehe: [Internet Relay Chat (Wikipedia)](https://de.wikipedia.org/wiki/Internet_Relay_Chat)*
```
would probably link to the german site here and remove the link in next line

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +[IRC](https://de.wikipedia.org/wiki/Internet_Relay_Chat) ist ein Protokoll der Anwendungsschicht, das das Chatten mit anderen Benutzern ermöglicht.
```suggestion
IRC ist ein Protokoll auf Anwendungsebene, das das Chatten mit anderen Benutzern ermöglicht.
```

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +*osu!Bancho* (manchmal abgekürzt einfach nur *Bancho*) bietet ein Gateway für dne Zugriff auf IRC (Chat im Spiel). Du kannst jeden modernen IRC-Client nutzen, um dich damit zu verbinden (scrolle heru
```suggestion
*osu!Bancho* (manchmal abgekürzt einfach nur *Bancho*) bietet ein Gateway für den Zugriff auf IRC (Chat im Spiel). Du kannst jeden modernen IRC-Client nutzen, um dich damit zu verbinden (scrolle herunter für eine Liste der populärsten Clients).
```

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +- Benutzername: dein osu! Benutzername. Ersetze Leerzeichen durch Unterstriche (z. B. `beppy master 1000` wird zu `beppy_master_1000`)
```suggestion
- Benutzername: dein osu! Benutzername. Ersetze Leerzeichen durch Unterstriche (z. B. wird `beppy master 1000` zu `beppy_master_1000`)
```

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +Normalerweise informieren dich viele IRC-Clients, sobald ein Benutzer einen Channel verlässt. Für Netzwerke wie osu!Bancho mit tausenden von Nutzern, die sich ständig ein- und ausloggen, können solch
```suggestion
Normalerweise informieren dich viele IRC-Clients, sobald ein Benutzer einen Channel verlässt. Für Netzwerke wie osu!Bancho mit tausenden von Nutzern, die sich ständig ein- und ausloggen, können solche Fluten an Nachrichten nervig werden. Im Folgenden findest du eine Liste gängiger IRC-Clients und wie du diese Nachrichten dort deaktivieren kannst:
```

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +osu!Bancho benutzt Klartext bei der Authentifizierung — stelle sicher, dass kein spezieller Authentifizierungsmodus ausgewählt ist in den Einstellungen deines IRC-Clients.
```suggestion
osu!Bancho benutzt Klartext bei der Authentifizierung — stelle sicher, dass in den Einstellungen deines IRC-Clients kein spezieller Authentifizierungsmodus ausgewählt ist.
```

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +2. Wenn dein Benutzername Leerzeichen enthält, ersetze diese bitte mit Unterstrichen (z. B. `Dieser Benutzername` wird zu `Dieser_Benutzername`).
```suggestion
2. Wenn dein Benutzername Leerzeichen enthält, ersetze diese bitte mit Unterstrichen (z. B. wird `Dieser Benutzername` zu `Dieser_Benutzername`).
```

2021-11-20 21:50 UTC, respektive commented on wiki/Internet_Relay_Chat/de.md
> +Benutzer, die über den osu!-Client verbunden sind, haben kein Präfix.
```suggestion
Benutzer, die über den osu!-Client oder die Website verbunden sind, haben kein Präfix.
```

2021-11-28 18:17 UTC, TicClick approved these changes

2021-11-28 18:18 UTC, merged