Finalise `UKCC10` tournament article
ppy/osu-wiki pull request #6426
Opened 2021-11-22 21:56 UTC by Bazzadwarf

Almost there...

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] Host sanity check

2021-12-07 23:35 UTC, Bazzadwarf commented
Should be good to go

2021-12-07 23:59 UTC, Walavouchey requested changes

2021-12-07 23:59 UTC, Walavouchey commented on wiki/Tournaments/UKCC/10/en.md
> +#### Loser Finals
I can only find one instance of "Loser Finals" and that's in [UKCC/7](https://github.com/ppy/osu-wiki/blob/master/wiki/Tournaments/UKCC/7/en.md) (go figure), the rest use "Losers Finals"

```suggestion
#### Losers Finals
```

2021-12-08 11:00 UTC, Walavouchey approved these changes

2021-12-08 11:01 UTC, merged