Add Glossary index and missing glossaries
ppy/osu-wiki pull request #6440
Opened 2021-11-26 02:15 UTC by daud-ahn

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-05 11:20 UTC, ZeroPyrozen requested changes

2021-12-05 11:20 UTC, ZeroPyrozen commented on wiki/Glossary/Hyperdash/id.md
> +**Hyperdash** adalah istilah yang digunakan di [osu!catch](/wiki/Game_mode/osu!catch) untuk gerakan yang dilakukan saat [hyperfruit](/wiki/Hit_object/Hyperfruit) dihasilkan. Saat *modding* sebuah bea
```suggestion
**Hyperdash** adalah istilah yang digunakan di [osu!catch](/wiki/Game_mode/osu!catch) untuk gerakan yang dilakukan saat [hyperfruit](/wiki/Hit_object/Hyperfruit) dihasilkan. Saat *modding* sebuah beatmap, orang-orang cenderung menautkan hyperfruit dan target [objek aktif](/wiki/Glossary/Active_object) untuk mendefinisikan gerakan hyperdash (misalnya `00:01:00 (1,2) -` di mana 1 adalah hyperfruit dan 2 objek aktif target).
```

2021-12-05 11:20 UTC, ZeroPyrozen commented on wiki/Glossary/Snapping/id.md
> +Di [osu!catch](/wiki/Game_mode/osu!catch) setiap [dash](/wiki/Glossary/Dash) dan [hyperdash](/wiki/Glossary/Hyperdash) dapat diklasifikasikan menjadi dua snapping yang berbeda, *basic-snapped* atau *
```suggestion
Di [osu!catch](/wiki/Game_mode/osu!catch) setiap [dash](/wiki/Glossary/Dash) dan [hyperdash](/wiki/Glossary/Hyperdash) dapat diklasifikasikan menjadi dua snapping yang berbeda yaitu, *basic-snapped* atau *higher-snapped*.
```

2021-12-05 11:20 UTC, ZeroPyrozen commented on wiki/Glossary/Snapping/id.md
> +| Kesulitan | Dash basic-snapped | Dash higher-snapped | Hyperdash basic-snapped | Hyperdash higher-snapped |
```suggestion
| Tingkat kesulitan | Dash basic-snapped | Dash higher-snapped | Hyperdash basic-snapped | Hyperdash higher-snapped |
```

2021-12-05 11:44 UTC, ZeroPyrozen approved these changes
All good 👍

2021-12-07 19:23 UTC, Walavouchey approved these changes

2021-12-07 19:24 UTC, merged