[ID] add `osu!_wiki` main page
ppy/osu-wiki pull request #6441
Opened 2021-11-26 12:21 UTC by daud-ahn

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-05 11:17 UTC, ZeroPyrozen requested changes

2021-12-05 11:17 UTC, ZeroPyrozen commented on wiki/osu!_wiki/id.md
> +[Upaya pertama](https://osu.ppy.sh/community/forums/posts/1175876) untuk membuat basis pengetahuan terstruktur dimulai pada tahun 2011, saat [peppy](/wiki/People/peppy) membuat instansi [MediaWiki](h
```suggestion
[Upaya pertama](https://osu.ppy.sh/community/forums/posts/1175876) untuk membuat basis pengetahuan terstruktur dimulai pada tahun 2011, saat [peppy](/wiki/People/peppy) membuat instansi [MediaWiki](https://en.wikipedia.org/wiki/MediaWiki) bagi siapa saja yang mau berpartisipasi. Selama bertahun-tahun, pemeliharaan dan pengoperasian MediaWiki telah terbukti sulit dan melelahkan, dan pada [26 Agustus 2016](https://discord.com/channels/188630481301012481/218677502141399041/218678017659109376) peppy dan tim sukarelawan memulai proses migrasi osu! wiki ke GitHub, di mana osu! wiki berada sampai hari ini. Sejak itu, wiki telah diintegrasikan ke dalam situs web osu! yang baru dan menerima pembaruan teknis dan visual yang penting untuk pengalaman pengguna yang baik.
```

2021-12-05 11:17 UTC, ZeroPyrozen commented on wiki/osu!_wiki/id.md
> +Pintu gerbang ke osu! wiki adalah [halaman utama](/wiki/Main_Page), yang dibagi menjadi beberapa kategori tingkat tinggi, masing-masing memiliki deskripsi umum dan mengandung daftar artikel penting.
```suggestion
Pintu gerbang ke osu! wiki adalah [halaman utama](/wiki/Main_Page), yang dibagi menjadi beberapa kategori tingkat tinggi, masing-masing memiliki deskripsi umum dan mengandung daftar artikel penting. Artikel yang tidak terdaftar di halaman utama, yang biasanya lebih spesifik, dapat dijangkau baik dari halaman lain menggunakan tautan dalam artikel atau melalui fitur pencarian situs web.
```

2021-12-05 11:17 UTC, ZeroPyrozen commented on wiki/osu!_wiki/id.md
> +Sebuah artikel menjelaskan satu istilah atau konsep dan memberikan gambaran umum tentang topik lain yang relevan. Agar lebih baik dalam menggambarkan sebuah subjek, artikel dibagi menjadi subbagian y
```suggestion
Sebuah artikel menjelaskan satu istilah atau konsep dan memberikan gambaran umum tentang topik lain yang relevan. Agar lebih baik dalam menggambarkan sebuah subjek, artikel dibagi menjadi sub-bagian yang mencakup bagian yang berbeda dari subjek tersebut. Artikel juga dapat mencakup tangkapan layar yang relevan atau penjelasan visual lainnya, atau tautan ke artikel lain tentang topik tersebut.
```

2021-12-05 11:17 UTC, ZeroPyrozen commented on wiki/osu!_wiki/id.md
> +Osu! wiki dibangun berdasarkan konsep aksesibilitas: pengeditan dan terjemahan dianjurkan dan dapat dilakukan oleh siapa saja yang mampu dan berpengetahuan. Data untuk artikel disimpan di [repositori
```suggestion
osu! wiki dibangun berdasarkan konsep aksesibilitas: pengeditan dan terjemahan dianjurkan dan dapat dilakukan oleh siapa saja yang mampu dan berpengetahuan. Data untuk artikel disimpan di [repositori GitHub](https://github.com/ppy/osu-wiki) dan diperbarui oleh kontributor melalui [*pull request*](/wiki/osu!_wiki/Contribution_guide), yang kemudian ditinjau dan di-*merge* oleh [pengelola wiki](/wiki/osu!_wiki/Maintenance/List_of_maintainers).
```

2021-12-05 11:17 UTC, ZeroPyrozen commented on wiki/osu!_wiki/id.md
> +Artikel disusun menurut [kriteria gaya artikel](/wiki/Article_styling_criteria) dari osu! wiki, yang berarti artikel ditulis dalam bahasa netral dan mengikuti aturan format dan desain umum. Beberapa
```suggestion
Artikel disusun menurut [kriteria gaya artikel](/wiki/Article_styling_criteria) dari osu! wiki, yang berarti artikel ditulis dalam bahasa netral dan mengikuti aturan format dan desain umum. Beberapa artikel informasi berfungsi sebagai daftar pertanyaan yang sering diajukan (*frequently asked question* (FAQ)) tentang topik tersebut dan menggunakan bahasa informal. Terjemahan mengikuti prinsip persamaan konten dan mematuhi aturan pemformatan yang sama.
```

2021-12-05 11:17 UTC, ZeroPyrozen commented on wiki/osu!_wiki/id.md
> +Sebagian besar konten di osu! wiki dilisensikan di bawah [CC-BY-NC 4.0](https://github.com/ppy/osu-wiki/blob/master/LICENCE.md). Ini berarti bahwa secara umum, materi wiki dapat digunakan secara non-
```suggestion
Sebagian besar konten di osu! wiki dilisensikan di bawah [CC-BY-NC 4.0](https://github.com/ppy/osu-wiki/blob/master/LICENCE.md). Ini berarti bahwa secara umum, materi wiki dapat digunakan secara non-komersial (lihat [ringkasan lisensi](https://tldrlegal.com/license/creative-commons-attribution-noncommercial-4.0-international-(cc-by-nc-4.0))). Beberapa konten mungkin dicakup oleh lisensi pihak ketiga yang berbeda, yang kemudian akan dikutip secara lokal dan menggantikan lisensi global.
```

2021-12-05 11:17 UTC, ZeroPyrozen commented on wiki/osu!_wiki/id.md
> +Harap dicatat bahwa ini tidak mencakup penggunaan "osu!" atau merek "ppy" dalam perangkat lunak, sumber daya, iklan, atau promosi apa pun, karena hal ini dilindungi oleh undang-undang merek dagang. J
```suggestion
Harap dicatat bahwa ini tidak mencakup penggunaan "osu!" atau merek "ppy" dalam perangkat lunak, sumber daya, iklan, atau promosi apa pun, karena hal ini dilindungi oleh undang-undang merek dagang. Jika kamu memerlukan izin untuk penggunaan persyaratan ini, silakan [hubungi kami](mailto:contact@ppy.sh).
```

2021-12-05 11:44 UTC, ZeroPyrozen approved these changes
All good 👍

2021-12-07 17:08 UTC, Walavouchey approved these changes

2021-12-07 17:10 UTC, merged