Add `Disambiguation/Score`; make individual articles of some `Score` sections
ppy/osu-wiki pull request #6442
Opened 2021-11-26 20:47 UTC by TicClick

part of #6431

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

cc @DoryanR for proof-reading French versions

2021-11-26 21:46 UTC, DoryanR requested changes
Nothing to say except that for the French side, I appreciate the initiative.

2021-11-26 21:46 UTC, DoryanR commented on wiki/Score/Total_score/fr.md
> +Le score total est la **somme de tous les scores sur des beatmaps classées et/ou approuvées, réussis ou non.**
```suggestion
Le score total est la **somme de tout les scores sur des beatmaps classées et/ou approuvées, réussis ou non.**
```

2021-11-26 21:46 UTC, DoryanR commented on wiki/Score/Total_score/fr.md
> +Le niveau d'un joueur est basé uniquement sur le **score total** du joueur. Le score requis pour passer un niveau est donné par la fonction suivante :
```suggestion
Le niveau d'un joueur est basé uniquement sur le **score total** du joueur. Le score requis pour passer un niveau est donné par la formule suivante : 
```

2021-11-26 21:46 UTC, DoryanR commented on wiki/Score/Total_score/fr.md
> +Notez qu'à cause de la technique d'arrondi utilisée par le jeu, les valeurs pour les niveaux supérieurs à 100 ne correspondent pas exactement à la formule. Cela est dû au fait que le jeu conserve une
```suggestion
Notez qu'à cause des arrondis par le jeu, les valeurs pour les niveaux supérieurs à 100 ne correspondent pas exactement à la formule. Cela est dû au fait que le jeu conserve une liste précalculée des différences de score entre chaque niveau, et que chaque élément de cette liste est arrondi à l'entier le plus proche. Par exemple, le 80e élément de la liste est `score(81) - score(80) = 128,927,482.36216`, arrondi à 128,927,482. Au niveau 100, l'erreur totale est de +1.629, ce qui explique pourquoi `score(100) = 26,931,190,828.629` ne correspond pas à 26,931,190,827 dans la deuxième partie de la formule.
```

2021-11-27 08:07 UTC, Joehuu requested changes

2021-11-27 08:07 UTC, Joehuu commented on wiki/Score/Ranked_score/fr.md
> +*Pour d'autres utilisations, voir : [Score (désambiguïsation)](/wiki/Disambiguation/Score).*
```suggestion
*Pour d'autres utilisations, voir [Score (désambiguïsation)](/wiki/Disambiguation/Score).*
```

2021-11-27 08:07 UTC, Joehuu commented on wiki/Score/Total_score/en.md
> +Then, the player plays again and gets 400k, only the total score increases by 400k.
```suggestion
If a player plays a ranked song for the first time and gets 500k, both ranked and total score increase by 500k. Then, the player plays again and gets 400k, only the total score increases by 400k.
```

2021-11-27 08:07 UTC, Joehuu commented on wiki/Score/Total_score/fr.md
> +*Pour d'autres utilisations, voir : [Score (désambiguïsation)](/wiki/Disambiguation/Score).*
```suggestion
*Pour d'autres utilisations, voir [Score (désambiguïsation)](/wiki/Disambiguation/Score).*
```

2021-11-27 08:07 UTC, Joehuu commented on wiki/Score/Total_score/fr.md
> +Ensuite, si le joueur rejoue la beatmap et qu'il obtient un score de 400k, seul le score total augmentera de 400k.
```suggestion
Si un joueur joue une beatmap classée pour la première fois et qu'il obtient 500k, les deux scores augmentent de 500k. Ensuite, si le joueur rejoue la beatmap et qu'il obtient un score de 400k, seul le score total augmentera de 400k.
```

2021-11-27 08:07 UTC, Joehuu commented on wiki/Score/fr.md
> +*Pour d'autres utilisations, voir : [Score (désambiguïsation)](/wiki/Disambiguation/Score).*
```suggestion
*Pour d'autres utilisations, voir [Score (désambiguïsation)](/wiki/Disambiguation/Score).*
```

2021-11-27 11:38 UTC, DoryanR approved these changes
Good for the French side

2021-11-27 16:32 UTC, TicClick commented on wiki/History_of_osu!/Online_rankings/osu!/fr.md
> +- [Ranked Score](/wiki/Score/ranked_score) (6 octobre 2007 - 24 juillet 2012)
```suggestion
- [Ranked Score](/wiki/Score/Ranked_score) (6 octobre 2007 - 24 juillet 2012)
```

2021-11-27 19:31 UTC, Joehuu submitted a review, later dismissed

2021-11-28 19:57 UTC, TPGPL requested changes

2021-11-28 19:57 UTC, TPGPL commented on wiki/Score/Ranked_score/en.md
> +The ranked score is the **total sum of the best scores for all ranked difficulties played online.**
```suggestion
The **ranked score** is the total sum of the best scores for all ranked difficulties played online.
```

2021-11-28 19:57 UTC, TPGPL commented on wiki/Score/Ranked_score/fr.md
> +Le score classé est la **somme des meilleurs scores sur toutes les beatmaps classées jouées en ligne.**
```suggestion
Le **score classé** est la somme des meilleurs scores sur toutes les beatmaps classées jouées en ligne.
```

2021-11-28 19:57 UTC, TPGPL commented on wiki/Score/Total_score/en.md
> +The total score is the **total sum of all scores on all beatmaps, including failed attempts.**
```suggestion
The **total score** is the total sum of all scores on all beatmaps, including failed attempts.
```

2021-11-29 04:30 UTC, Joehuu commented on wiki/Score/Total_score/fr.md
> +Le score total est la **somme de tout les scores sur des beatmaps classées et/ou approuvées, réussis ou non.**
Missed this.
```suggestion
Le **score total** est la somme de tout les scores sur des beatmaps classées et/ou approuvées, réussis ou non.
```

2021-11-29 04:38 UTC, TicClick commented on wiki/Score/Total_score/fr.md
> +Le score total est la **somme de tout les scores sur des beatmaps classées et/ou approuvées, réussis ou non.**
ah, thanks. should be done now

2021-11-29 04:42 UTC, Joehuu approved these changes

2021-11-29 04:44 UTC, merged