[ID] Add `Maintenance`  and `List_of_maintainers`
ppy/osu-wiki pull request #6443
Opened 2021-11-27 02:38 UTC by daud-ahn

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-11-27 15:07 UTC, ZeroPyrozen requested changes

2021-11-27 15:07 UTC, ZeroPyrozen commented on wiki/osu!_wiki/Maintenance/id.md
> +Beberapa fitur mungkin tidak berhubungan langsung dengan situs web osu!, tetapi mungkin berguna untuk berkontribusi atau pembenahan. Dalam kasus tersebut, fitur-fitur ini diimplementasikan oleh orang
```suggestion
Beberapa fitur mungkin tidak berhubungan langsung dengan situs web osu!, tetapi mungkin berguna untuk berkontribusi atau pembenahan. Dalam kasus tersebut, fitur-fitur ini diimplementasikan oleh orang yang mampu membuat hal tersebut dan **tidak** ditambahkan ke situs web secara langsung:
```

2021-11-27 15:07 UTC, ZeroPyrozen commented on wiki/osu!_wiki/Maintenance/id.md
> +Wiki bergantung pada masukan dari komunitas osu!. Anda dapat membantu pengelola dan kontributor lain dengan melakukan apa yang Anda bisa lakukan. Untuk informasi tentang cara melakukannya, baca [pand
```suggestion
Wiki bergantung pada masukan dari komunitas osu!. Kamu dapat membantu pengelola dan kontributor lain dengan melakukan apa yang kamu bisa lakukan. Untuk informasi tentang cara melakukannya, baca [panduan kontribusi](/wiki/osu!_wiki/Contribution_guide). Jika suatu saat kamu merasa perlu bantuan, mintalah bantuan di channel `#osu-wiki` di [server Discord osu!dev](/wiki/osu!dev_Discord_server).
```

2021-11-27 15:07 UTC, ZeroPyrozen commented on wiki/osu!_wiki/Maintenance/id.md
> +osu! wiki dibaca oleh orang-orang dari seluruh dunia. Untuk membantu komunitas lokal Anda dan menarik pemain, *mapper*, *modder*, dan pengembang baru yang luar biasa ke dalam game, Anda dapat menerje
```suggestion
osu! wiki dibaca oleh orang-orang dari seluruh dunia. Untuk membantu komunitas lokal kamu dan menarik pemain, *mapper*, *modder*, dan pengembang baru yang luar biasa ke dalam game, Kamu dapat menerjemahkan artikel bahasa Inggris, atau memperbarui terjemahan yang ada yang tertinggal. Periksa [daftar bahasa](/wiki/Article_styling_criteria/Formatting#locales) yang didukung oleh osu! wiki, dan pastikan terjemahanmu mengikuti prinsip [paritas konten](/wiki/Article_styling_criteria/Formatting#content-parity). Jika kamu seorang pembicara yang fasih dan penulis berpengalaman, ambil topik utama seperti artikel tentang [aturan](https://github.com/ppy/osu-wiki/tree/master/wiki/Rules) atau [kriteria ranking](https://github.com/ppy/osu-wiki/tree/master/wiki/Ranking_Criteria). Jika kamu baru memulai karir menulis kamu, pilih artikel kecil untuk menerima bantuan dan bimbingan dari pengulas dan penutur bahasa asli.
```

2021-11-27 15:07 UTC, ZeroPyrozen commented on wiki/osu!_wiki/Maintenance/id.md
> +Beberapa artikel dari osu! wiki belum lengkap dan mmeerlukan lebih banyak informasi. Artikel tersebut ditandai sebagai *rintisan*, yang berarti artikel tersebut cukup penting untuk ada sebagai halama
```suggestion
Beberapa artikel dari osu! wiki belum lengkap dan mmeerlukan lebih banyak informasi. Artikel tersebut ditandai sebagai *rintisan*, yang berarti artikel tersebut cukup penting untuk ada sebagai halaman individual, tetapi akan diselesaikan nanti. Jika Anda sudah familiar dengan topik artikel tersebut, berkontribusi dan bagilah pengetahuanmu.
```

2021-11-27 15:07 UTC, ZeroPyrozen commented on wiki/osu!_wiki/Maintenance/id.md
> +osu! adalah lingkungan yang selalu berubah: komunitas membuat beatmap baru, menemukan cara baru untuk mengekspresikan diri, dan melakukan hal baru lainnya. Jika peristiwa atau istilah tertentu tidak
```suggestion
osu! adalah lingkungan yang selalu berubah: komunitas membuat beatmap baru, menemukan cara baru untuk mengekspresikan diri, dan melakukan hal baru lainnya. Jika peristiwa atau istilah tertentu tidak tercakup, jangan ragu untuk menulis artikel tentangnya dan berkontribusi pada kumpulan pengetahuan global. Turnamen atau kontes baru? fitur baru osu!? Bagian yang tidak diketahui dari sebuah cerita? Manfaatkan keterampilan menulis kamu yang tajam dengan baik.
```

2021-11-27 15:07 UTC, ZeroPyrozen commented on wiki/osu!_wiki/Maintenance/id.md
> +Artikel yang ada juga perlu pemeliharaan. Jika Anda menemukan kesalahan faktual, atau ada detail yang hilang, atau jika Anda hanya ingin menulis ulang/memperluas artikel sesuai dengan apa yang ada, m
```suggestion
Artikel yang ada juga perlu pemeliharaan. Jika kamu menemukan kesalahan faktual, atau ada detail yang hilang, atau jika kamu hanya ingin menulis ulang/memperluas artikel sesuai dengan apa yang ada, majulah dan buat osu! wiki tempat yang lebih baik. Jika perubahan yang kamu rencanakan cukup besar atau signifikan, pastikan untuk membahasnya di saluran `#osu-wiki`, atau [buka *issue* baru](https://github.com/ppy/osu-wiki/issues/new).
```

2021-12-07 17:20 UTC, Walavouchey approved these changes

2021-12-07 17:21 UTC, merged