[ID] Add `Online Rankings`
ppy/osu-wiki pull request #6444
Opened 2021-11-27 02:54 UTC by daud-ahn

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-11-28 19:22 UTC, ZeroPyrozen requested changes

2021-11-28 19:22 UTC, ZeroPyrozen commented on wiki/History_of_osu!/Online_rankings/id.md
> +Versi awal osu! adalah pengalaman yang sebagian besar terisolasi, tanpa papan peringkat online untuk apa pun hingga [6 Oktober 2007](https://osu.ppy.sh/community/forums/topics/15?n=29), saat dukungan
```suggestion
Versi awal osu! hanya memiliki peringkat lokal saja namun pada [6 Oktober 2007](https://osu.ppy.sh/community/forums/topics/15?n=29) fitur peringkat online ditambahkan untuk mode permainan [osu!](/wiki/Game_mode/osu!). Sejak saat itu, semua [mode permainan](/wiki/Game_mode) sudah memiliki [peringkat online-nya](https://osu.ppy.sh/rankings/osu/performance) masing-masing.
```

2021-11-28 19:22 UTC, ZeroPyrozen commented on wiki/History_of_osu!/Online_rankings/id.md
> +Banyak pemain telah memegang peringkat #1 di setiap mode permainan di bawah sistem peringkat yang berbeda. Sistem saat ini yang digunakan oleh semua mode permainan untuk peringkat online adalah [ppv2
```suggestion
Banyak pemain telah memegang peringkat #1 di setiap mode permainan dengan sistem peringkat yang berbeda-beda. Sistem saat ini yang digunakan oleh semua mode permainan untuk peringkat online adalah [ppv2](/wiki/Performance_points/ppv2).
```

2021-12-01 00:06 UTC, ZeroPyrozen approved these changes
Looks good 👍

2021-12-03 15:13 UTC, TicClick approved these changes

2021-12-03 15:14 UTC, merged