Add UKCC8 tournament article
ppy/osu-wiki pull request #6445
Opened 2021-11-27 03:38 UTC by Bazzadwarf

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] Host sanity check

2021-12-07 23:36 UTC, Bazzadwarf commented
Should be good to go

2021-12-08 11:26 UTC, Walavouchey requested changes

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +  - One qualification rounds where 32 teams progress
```suggestion
  - One qualification round where 32 teams progress
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +  - Group stage where 16 team progress
```suggestion
  - Group stage where 16 teams progress
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +  - Double Elimination Bracket
```suggestion
  - Double-elimination bracket
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- To be able to participate, players must have an **![][flag_GB] United Kingdom or ![][flag_IE] Ireland flag or be able to provide proof of residency to the hosts.**
```suggestion
- To be able to participate, players must have a **![][flag_GB] United Kingdom or ![][flag_IE] Ireland flag or be able to provide proof of residency to the hosts**.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- Ranks will be taken during and when signups end. If your teams rank after signups end is under 1000, you will not be eligible to participate in the tournament.
```suggestion
- Ranks will be taken during and at the end of signups. If your team rank after signups end is under 1000, you will not be eligible to participate in the tournament.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- All players are to treat staff and other participants with a high level of respect. Any kind of mistreatment on the discord server or during matches (this includes homophobia, racism and toxicity)
```suggestion
- All players are to treat staff and other participants with a high level of respect. Any kind of mistreatment on the Discord server or during matches (this includes homophobia, racism and toxicity) will result in a **ban** and the offending player will be **blacklisted** from participating from future UKCC tournaments.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- Schedules for the next round are released on the Monday before a stage is due to happen and **all** matches will be scheduled for the weekend. You can reschedule for weekdays at the staffs discreti
```suggestion
- Schedules for the next round are released on the Monday before a stage is due to happen and **all** matches will be scheduled for the weekend. You can reschedule for weekdays at the staff's discretion.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- In order to reschedule, you must contact your opponents, agree on a time and be able to provide **proof** (by form of a screenshot/image) of the agreed reschedule to the Hosts.
```suggestion
- In order to reschedule, you must contact your opponents, agree on a time, and be able to provide **proof** (by form of a screenshot/image) of the agreed reschedule to the hosts.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- In effort to ensure as many matches take place as possible, reschedules are allowed up to **2 hour before your match is due to be played**. However, your opponent holds the right to **refuse a resc
```suggestion
- In effort to ensure that as many matches take place as possible, reschedules are allowed up to **2 hours before your match is due to be played**. However, your opponent holds the right to **refuse a reschedule if asked less than 12 hours from the scheduled time**.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- If it is impossible to find a time to reschedule to that suits both teams, both teams should talk to the Hosts (Bae- or Yazzehh) and we will attempt to sort something out.
```suggestion
- If it is impossible to find a time to reschedule to that suits both teams, both teams should talk to the hosts ([Bae-](https://osu.ppy.sh/users/6576972) or [Yazzehh](https://osu.ppy.sh/users/7068973)) who will attempt to sort something out.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- There will be no warmups in Qualification rounds. After this, warmup maps must be a submitted beatmap, and have a drain time of 4 minutes or less.
```suggestion
- There will be no warmups in Qualification rounds. After this, warmup maps must be submitted beatmaps, and have a drain time of 4 minutes or less.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +- For Freemod picks, teams must select any combination of the following mods: **Hidden, HardRock**.
```suggestion
- For FreeMod picks, teams must select any combination of **Hidden or HardRock**.
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +### Group Stage
```suggestion
### Group stage
```

2021-12-08 11:26 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +## Match Results
```suggestion
## Match results
```

2021-12-08 15:16 UTC, Walavouchey commented on wiki/Tournaments/UKCC/8/en.md
> +  - ["Cranky vs. MASAKI - ouroboros -twin stroke of the end- (celerih) [Flask's Expert]"](https://osu.ppy.sh/beatmapsets/1052054#osu/2226504)
?

```suggestion
  - [Cranky vs. MASAKI - ouroboros -twin stroke of the end- (celerih) [Flask's Expert]](https://osu.ppy.sh/beatmapsets/1052054#osu/2226504)
```

2021-12-08 15:47 UTC, Bazzadwarf commented on wiki/Tournaments/UKCC/8/en.md
> +  - ["Cranky vs. MASAKI - ouroboros -twin stroke of the end- (celerih) [Flask's Expert]"](https://osu.ppy.sh/beatmapsets/1052054#osu/2226504)
🤷

2021-12-08 15:52 UTC, Walavouchey approved these changes

2021-12-08 15:53 UTC, merged