[EN/ID] Update `2007`
ppy/osu-wiki pull request #6447
Opened 2021-11-27 04:50 UTC by daud-ahn

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-12 20:40 UTC, DoryanR commented
I think it would be interesting to include references in links redirecting directly to the bottom of the page, like in the [2014](https://github.com/ppy/osu-wiki/blob/master/wiki/History_of_osu!/2014/en.md) and [2015](https://github.com/ppy/osu-wiki/blob/master/wiki/History_of_osu!/2015/en.md) articles to stay consistent.

2021-12-14 02:44 UTC, daud-ahn commented
References found:  
ouentest: https://twitter.com/ppy/status/1141394137637249025?s=20
pUpdater and osume  https://osu.ppy.sh/community/forums/topics/4?n=1

2021-12-16 15:16 UTC, ZeroPyrozen requested changes

2021-12-16 15:16 UTC, ZeroPyrozen commented on wiki/History_of_osu!/2007/id.md
> +Berikut ini adalah beberapa peristiwa besar dalam sejarah osu! sejak awal berdirinya. Terima kasih khusus kepada [Sinistro](https://osu.ppy.sh/users/5530) karena telah membantu menyusun konten tahun
```suggestion
Berikut ini adalah beberapa peristiwa besar dalam sejarah osu! sejak awal berdirinya. Terima kasih khusus kepada [Sinistro](https://osu.ppy.sh/users/5530) karena telah membantu menyusun konten tahun 2007/2008.
```
```suggestion
Berikut ini adalah beberapa peristiwa besar yang terjadi di osu! selama tahun 2007. Terima kasih kepada [Sinistro](https://osu.ppy.sh/users/5530) atas bantuannya dalam menyusun sejarah osu! tahun 2007/2008.
```

2021-12-16 15:16 UTC, ZeroPyrozen commented on wiki/History_of_osu!/2007/id.md
> +osu! dimulai sebagai *proof-of-concept* bernama "ouentest"[[1]][r]. Versi pertama dirilis pada 1 Juli 2007 untuk sekelompok kecil teman dekat [peppy](https://osu.ppy.sh/users/2) dan memiliki sebuah [
```suggestion
osu! dimulai sebagai *proof-of-concept* bernama "ouentest"[[1]][r]. Versi pertama dirilis pada 1 Juli 2007 untuk sekelompok kecil teman dekat [peppy](https://osu.ppy.sh/users/2) dan memiliki sebuah [editor beatmap](/wiki/Beatmap_Editor) dan mode permainan yang sangat mendasar. Editor hanya dapat membuat [beatmap](/wiki/Beatmap) yang *sangat* sederhana tanpa fungsi *seeking* atau [*snapping*](/wiki/Beatmapping/Snapping) dan tidak ada slider atau spinner, hanya circle dan penghitung skor/kombo yang mendasar. Rilis pertama memakan waktu sekitar 16 jam waktu coding dan dilakukan dalam *single all-nighter*. `pUpdater` diperkenalkan (lekas dikenal sebagai `osume`)[[2]][r] untuk menangani pembaruan ke versi terbaru.
```
```suggestion
osu! dimulai sebagai *proof-of-concept* bernama "ouentest"[[1]][r]. Versi pertama dirilis pada tanggal 1 Juli 2007 untuk sekelompok kecil teman dekat [peppy](https://osu.ppy.sh/users/2) dan memiliki sebuah [editor beatmap](/wiki/Beatmap_Editor) dan mode permainan yang sangat mendasar. Editor hanya dapat membuat [beatmap](/wiki/Beatmap) yang *sangat* sederhana tanpa fungsi *seeking* atau [*snapping*](/wiki/Beatmapping/Snapping) dan tidak ada slider atau spinner, hanya circle dan penghitung skor/kombo yang mendasar. Rilis pertama memakan waktu sekitar 16 jam waktu coding dan dilakukan dalam *single all-nighter*. `pUpdater` diperkenalkan (lekas dikenal sebagai `osume`)[[2]][r] untuk menangani pembaruan ke versi terbaru.
```

2021-12-16 15:16 UTC, ZeroPyrozen commented on wiki/History_of_osu!/2007/id.md
> +Menu utama telah diperbarui dengan tampilan baru, dan editor menerima banyak fungsi baru, termasuk dukungan salin dan tempel (copy dan paste). Menu tab dan menu konteks (*context menu*) ditambahkan,
```suggestion
Menu utama telah diperbarui dengan tampilan baru, dan editor menerima banyak fungsi baru, termasuk dukungan salin dan tempel (copy dan paste). Menu tab dan menu konteks (*context menu*) ditambahkan, membuat fitur editor jauh lebih mudah diakses dibanding sebelumnya; slider lebih banyak mendapat dukungan, dengan ditambahkannya [slider tick](/wiki/Beatmapping/Slider_tick); diperkenalkannya [stacking](/wiki/Mapping_Techniques/Stack) [hit circles](/wiki/Hit_object/Hit_circle); dukungan lebih baik untuk skor terbaik lokal; dan format file `osu!` direvisi dan dirubah sepenuhnya, tetapi telah mencakup konversi file lama ke format baru.
```
```suggestion
Menu utama telah diperbarui dengan tampilan baru, dan editor menerima banyak fungsi baru, termasuk dukungan salin dan tempel (copy dan paste). Menu tab dan menu konteks (*context menu*) ditambahkan, membuat fitur editor jauh lebih mudah diakses dibanding sebelumnya; slider lebih banyak mendapat dukungan, dengan ditambahkannya [slider tick](/wiki/Beatmapping/Slider_tick); diperkenalkannya [stacking](/wiki/Mapping_Techniques/Stack) [hit circles](/wiki/Hit_object/Hit_circle); dukungan lebih baik untuk skor terbaik lokal; dan format berkas `osu!` direvisi dan dirubah sepenuhnya, tetapi telah mencakup konversi berkas lama ke format baru.
```

2021-12-17 03:16 UTC, ZeroPyrozen approved these changes
Looks good to me 👍

2021-12-17 07:44 UTC, Walavouchey requested changes

2021-12-17 07:44 UTC, Walavouchey commented on wiki/History_of_osu!/2007/en.md
> +September 17, 2007 was the "birth" of osu! as far as the public was concerned. The forums as we know them today were established, and hosted from peppy's home domain (`ppy.sh`). Attention was gained
```suggestion
September 17, 2007 was the "birth" of osu! as far as the public was concerned. The forums as we know them today were established, and hosted from peppy's home domain (`ppy.sh`). Attention was gained via a [news announcement](https://web.archive.org/web/20071221020801/http://www.bemanistyle.com/index.php?news_id=483) on [bemanistyle](http://bemanistyle.com) which drew quite a few interested people with previous rhythm game experience.
```

2021-12-22 09:33 UTC, Walavouchey commented
@daud-ahn are you going to apply the review or should we make the edits on the translation ourselves? just a small style issue, but this is good to go otherwise (cc @ZeroPyrozen)

2021-12-22 10:34 UTC, ZeroPyrozen commented
yes, it's good enough. Change line 47 of `id.md` to `osu! mulai mendapat perhatian saat disorot melalui [pengumuman berita](https://web.archive.org/web/20071221020801/http://www.bemanistyle.com/index.php?news_id=483) di forum [bemanistyle](http://www.bemanistyle.com), yang menarik beberapa orang yang memiliki pengalaman game ritme sebelumnya.` if change above applied

2021-12-22 19:08 UTC, Walavouchey commented on wiki/History_of_osu!/2007/id.md
> +Tanggal 17 September 2007 merupakan tanggal peluncuran osu! secara publik. Forum-forum yang kita kenal sekarang dibentuk pada saat itu dan dihosting menggunakan domain rumahan peppy (`ppy.sh`). osu!
```suggestion
Tanggal 17 September 2007 merupakan tanggal peluncuran osu! secara publik. Forum-forum yang kita kenal sekarang dibentuk pada saat itu dan dihosting menggunakan domain rumahan peppy (`ppy.sh`). osu! mulai mendapat perhatian saat disorot melalui [pengumuman berita](https://web.archive.org/web/20071221020801/http://www.bemanistyle.com/index.php?news_id=483) di forum [bemanistyle](http://www.bemanistyle.com), yang menarik beberapa orang yang memiliki pengalaman game ritme sebelumnya.
```

2021-12-22 19:09 UTC, Walavouchey approved these changes

2021-12-22 19:10 UTC, merged