Split `Score` into game mode-specific articles
ppy/osu-wiki pull request #6470
Opened 2021-11-30 07:15 UTC by TicClick

part of https://github.com/ppy/osu-wiki/issues/643. nothing meaningful is added/updated/fixed, this will be done in subsequent PRs

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) (@DoryanR)

2021-11-30 09:21 UTC, DoryanR commented
I'll go see tonight for the French part

2021-11-30 11:47 UTC, geshii commented
> I'll go see tonight for the French part. If it's just a copy/paste of the article it will be fine for now, but it will have to be updated, it's planned

It looks good for the French part I guess, I don't see anything to change

2021-11-30 17:33 UTC, DoryanR requested changes
Everything is good for the French side, just need to translate the headers

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!/fr.md
> +# osu! scoring system
```suggestion
# Système de notation d'osu!
```

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!/fr.md
> +## Object score
```suggestion
## Score de l'objet
```

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!catch/fr.md
> +# osu!catch scoring system
```suggestion
# Système de notation d'osu!catch
```

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!catch/fr.md
> +## Object score
```suggestion
## Score de l'objet
```

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!mania/fr.md
> +# osu!mania scoring system
```suggestion
# Système de notation d'osu!mania
```

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!mania/fr.md
> +## Scoring
```suggestion
## Notation
```

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!taiko/fr.md
> +# osu!taiko scoring system
```suggestion
# Système de notation d'osu!taiko
```

2021-11-30 17:33 UTC, DoryanR commented on wiki/Score/osu!taiko/fr.md
> +## Object score
```suggestion
## Score de l'objet
```

2021-11-30 17:36 UTC, DoryanR requested changes
I feel like there are headers missing in those places, right?

2021-11-30 17:36 UTC, DoryanR commented on wiki/Score/osu!mania/en.md
> +## Hit values
```suggestion
# osu!mania scoring system

## Hit values
```

2021-11-30 17:36 UTC, DoryanR commented on wiki/Score/osu!taiko/en.md
> +## Hit values
```suggestion
# osu!taiko scoring system

## Hit values
```

2021-11-30 18:06 UTC, geshii commented
> * wiki/Game_mode/osu!/id.md
> * wiki/Game_mode/osu!/tr.md
> * wiki/Game_mode/osu!catch/fr.md
>* wiki/Game_mode/osu!mania/es.md
> * wiki/Game_mode/osu!mania/fr.md
>* wiki/Game_mode/osu!taiko/fr.md
>
>If your changes DON'T NEED to be added to the translations, add SKIP_OUTDATED_CHECK anywhere in the description of your pull request.

Do we need to edit these files aswell?

2021-11-30 21:11 UTC, TicClick commented
yep, I have a local patch for French articles, will find someone for Indonesian/Turkish/Spanish

2021-11-30 23:43 UTC, TicClick commented
all done, with help of Zeus-, Sies, Doryan, and Darksonic

2021-12-01 00:48 UTC, TPGPL approved these changes

2021-12-01 00:48 UTC, merged