[DE] Update `osu!_File_Formats`
ppy/osu-wiki pull request #6474
Opened 2021-11-30 20:51 UTC by The-Last-Cookie

Updates the article to the latest version.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-01 14:28 UTC, respektive requested changes
looks good otherwise

2021-12-01 14:28 UTC, respektive commented on wiki/osu!_File_Formats/de.md
> +   - Gehe zu "Zum Editieren" und wähle die Beatmap, die du zu .osz konvertieren möchtest.
```suggestion
   - Gehe zu "Edit" und wähle die Beatmap, die du zu .osz konvertieren möchtest.
```
the button in the main menu is just called `Edit` even in german.

2021-12-04 17:25 UTC, Phippe requested changes
Looks good to me otherwise 👍

2021-12-04 17:25 UTC, Phippe commented on wiki/osu!_File_Formats/de.md
> +   - Wenn du die Beatmap vorher editiert hast, wird normalerweise alles bereits fertig zum Konvertieren nach .osz sein. Für Skins musst du die Dateien vorher kompillieren.
```suggestion
   - Wenn du die Beatmap vorher editiert hast, wird normalerweise alles bereits fertig zum Konvertieren nach .osz sein. Für Skins musst du die Dateien vorher kompilieren.
```

2021-12-04 17:25 UTC, Phippe commented on wiki/osu!_File_Formats/de.md
> +   - Wähle den Skin, den du möchtest im Skinselektionsmenü und klicke auf "Als .osk exportieren".
```suggestion
   - Wähle den Skin, den du möchtest, im Skinselektionsmenü und klicke auf "Als .osk exportieren".
```

2021-12-04 22:04 UTC, respektive commented on wiki/osu!_File_Formats/de.md
> +.osz/.osk Datei ist ein Dateierweiterung, die extra für osu!.exe zugeschnitten ist. Wenn eine .osz Datei geöffnet wird, wird die Datei von der osu!.exe extrahiert und zum "Songs" Ordner transferiert.
```suggestion
.osz/.osk Datei ist eine Dateierweiterung, die extra für osu!.exe zugeschnitten ist. Wenn eine .osz Datei geöffnet wird, wird die Datei von der osu!.exe extrahiert und zum "Songs" Ordner transferiert. Die .osk Datei wird hingegen zum "Skins" Ordner transferiert. Standardmäßig werden Beatmapdateien direkt von der offiziellen Webseite im .osz Dateiformat heruntergeladen. Wie man .osz/.osk Dateien erstellt, zählt als fundamentales Wissen eines Mappers/Skinners.
```

2021-12-05 12:12 UTC, respektive approved these changes
LGTM

2021-12-05 15:08 UTC, TicClick approved these changes

2021-12-05 15:09 UTC, merged