[ID] Update `Mapping and modding timeline`
ppy/osu-wiki pull request #6475
Opened 2021-11-30 22:51 UTC by Nivalyx

An update for the Indonesian translation of the `Mapping and modding timeline` (http://osu.ppy.sh/wiki/en/Mapping_and_Modding_Timeline) wiki article.

---

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-11-30 23:58 UTC, ZeroPyrozen requested changes

2021-11-30 23:58 UTC, ZeroPyrozen commented on wiki/Mapping_and_Modding_Timeline/id.md
> +Sistem mapping dan modding yang berlaku di dalam lingkungan osu! senantiasa berubah seiring waktu. Artikel **Sejarah mapping dan modding** di bawah ini ditujukan sebagai suatu bentuk napak tilas akan
```suggestion
Sistem mapping dan modding yang berlaku di dalam lingkungan osu! senantiasa berubah seiring waktu. Artikel **Sejarah mapping dan modding** di bawah ini ditujukan sebagai suatu bentuk tapak tilas akan berbagai perubahan yang terjadi dari masa ke masa dan sebagai pedoman bagi mereka yang ingin mencetuskan ide-ide baru untuk mengembangkan sistem mapping dan modding yang telah ada ke depannya.
```
Formal word.

2021-11-30 23:58 UTC, ZeroPyrozen commented on wiki/Mapping_and_Modding_Timeline/id.md
> +- **2018-12-12:** Tim inti osu! menyatakan bahwa [osu! secara resmi menjauhkan diri dari praktek komisi beatmap (*beatmap commission*)](https://osu.ppy.sh/community/forums/topics/840838) yang tidak b
```suggestion
- **2018-12-12:** Tim inti osu! menyatakan bahwa [osu! secara resmi menjauhkan diri dari praktik komisi beatmap (*beatmap commission*)](https://osu.ppy.sh/community/forums/topics/840838) yang tidak beritikad baik.
```
Formalise `praktek` into `praktik`

2021-12-01 14:28 UTC, Nivalyx commented
@ZeroPyrozen applied both, thanks for the check 👍 

(also changed all other instances of `praktek` throughout the article to `praktik`)

2021-12-01 15:21 UTC, ZeroPyrozen approved these changes
All good 👍

2021-12-01 15:44 UTC, TicClick approved these changes

2021-12-01 15:51 UTC, merged