[FR] Update `Inteface`
ppy/osu-wiki pull request #6488
Opened 2021-12-03 20:28 UTC by DoryanR

Proposal to update the French translation of the wiki page `Inteface`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-03 20:30 UTC, DoryanR commented on wiki/Interface/fr.md
> +9.  Le bouton "Je suis prêt !".
```suggestion
9. Le bouton "Je suis prêt !".
```

2021-12-08 09:25 UTC, Satsukel requested changes

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +L'[osu!cookie](/wiki/Glossary/Cookie) \[1\] pluse en fonction du [BPM](/wiki/Beatmapping/Beats_per_minute) de la musique en cours de lecture. On peut également voir plusieurs barres autour du logo qu
```suggestion
L'[osu!cookie](/wiki/Glossary/Cookie) \[1\] pulse en fonction du [BPM](/wiki/Beatmapping/Beats_per_minute) de la musique en cours de lecture. On peut également voir plusieurs barres autour du logo qui changent de taille en fonction du volume de la musique. Si aucun morceau n'est joué, le logo pulse par défaut à un rythme de 60 BPM. Les éléments du menu principal sont les suivants :
```

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +- \[6\] Sous le menu sont affichés des conseils utiles et aléatoires sur comment tirer le meilleur parti d'osu!, et parfois une bannière concernant un évènement en cours.
```suggestion
- \[6\] Sous le menu sont affichés divers conseils utiles sur comment tirer le meilleur parti d'osu!, et parfois une bannière concernant un évènement en cours.
```

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +- \[10\] En haut à droite se situe un jukebox qui joue les musiques que vous avez télécharger dans un ordre aléatoire. La partie la plus haute indique la musique en cours de lecture. Les boutons, de
```suggestion
- \[10\] En haut à droite se situe un jukebox qui joue les musiques que vous avez téléchargées dans un ordre aléatoire. La partie la plus haute indique la musique en cours de lecture. Les boutons, de gauche à droite, effectuent ces actions :
```

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +- \[10\] En haut à droite se situe un jukebox qui joue les musiques que vous avez télécharger dans un ordre aléatoire. La partie la plus haute indique la musique en cours de lecture. Les boutons, de
```suggestion
- \[10\] En haut à droite se situe un jukebox qui joue aléatoirement les musiques que vous avez téléchargées. La partie la plus haute indique la musique en cours de lecture. Les boutons, de gauche à droite, effectuent ces actions :
```
Sinon j'ai ça aussi pour fluidifier mais je suis pas sûr que ça soit aussi compréhensible que l'autre suggestion

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +  - Voir le nom de la musique. Cette option permet de rendre cet affichage permanent ou temporaire. Si son statut est permanent, il restera présent à l'écran jusqu'à ce qu'on change de menu. Si son s
```suggestion
  - Voir le nom de la musique. Cette option permet de rendre cet affichage permanent ou temporaire. Si son statut est permanent, il restera présent à l'écran jusqu'à ce qu'on change de menu. Si son statut est temporaire, il disparaîtra au bout de quelques secondes après le choix de la musique et restera caché jusqu'à ce que son statut soit changé ou qu'une autre musique soit jouée.
```

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +1. Votre rang dans la salle. Vous pouvez être soit l'hôte (si vous avez crée la salle ou si l'hôte précédent vous a donné ce rôle), soit un participant. Ce rang est également affiché à côté de votre
```suggestion
1. Votre rang dans la salle. Vous pouvez être soit l'hôte (si vous avez créé la salle ou si l'hôte précédent vous a donné ce rôle), soit un participant. Ce rang est également affiché à côté de votre nom.
```

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +7. Les [mods](/wiki/Game_modifier) que vous avez activé (voir \#12), ainsi que l'option pour les sélectionner. L'option intitulée "Mods libres" décide de si les joueurs peuvent choisir leurs propres
```suggestion
7. Les [mods](/wiki/Game_modifier) que vous avez activés (voir \#12), ainsi que l'option pour les sélectionner. L'option intitulée "Mods libres" décide de si les joueurs peuvent choisir leurs propres mods ou non. Si elle est activée, les joueurs peuvent choisir n'importe quelle combinaison de mods *sauf les mods altérant la vitesse de la beatmap, comme [Double Time](/wiki/Game_modifier/Double_Time) et [Half Time](/wiki/Game_modifier/Half_Time)*. Si elle est désactivée, l'hôte décide de quels mods seront utilisés. L'hôte peut choisir les mods altérant la vitesse de la beatmap peu importe si l'option "Mods libres" est activée ou non.
```

2021-12-08 09:25 UTC, Satsukel commented on wiki/Interface/fr.md
> +Mettez le curseur au dessus de l'icône d'un mod pour voir une description courte de son effet sur le gameplay. Cliquez sur celui-ci pour le sélectionner ou le désélectionner. Certains mods, comme le
```suggestion
Mettez le curseur au dessus de l'icône d'un mod pour voir une courte description de son effet sur le gameplay. Cliquez sur celui-ci pour le sélectionner ou le désélectionner. Certains mods, comme le mod [Double Time](/wiki/Game_modifier/Double_Time), ont plusieurs variations. Cliquez une nouvelle fois sur ce mod pour voir les différentes versions de celui-ci.
```
Je sais je chipote xD

2021-12-08 09:28 UTC, Satsukel approved these changes

2021-12-08 10:38 UTC, Walavouchey commented on wiki/Interface/fr.md
> +1. Votre rang dans la salle. Vous pouvez être soit l'hôte (si vous avez créé la salle ou si l'hôte précédent vous a donné ce rôle), soit un participant. Ce rang est également affiché à côté de votre
it seems like the english article is inconsistent with list style. looks like a simple fix for all translations, so it can be left another pr

2021-12-08 10:38 UTC, Walavouchey commented on wiki/Interface/fr.md
>  1. Votre profil. Il montre vos [PP](/wiki/Performance_points), votre rang global, votre score total, votre [précision](/wiki/Gameplay/Accuracy) globale, ainsi que votre niveau.
same here

2021-12-08 10:38 UTC, Walavouchey approved these changes

2021-12-08 10:39 UTC, merged

2021-12-08 10:43 UTC, Walavouchey commented on wiki/Interface/fr.md
> +1. Votre rang dans la salle. Vous pouvez être soit l'hôte (si vous avez créé la salle ou si l'hôte précédent vous a donné ce rôle), soit un participant. Ce rang est également affiché à côté de votre
has an issue already https://github.com/ppy/osu-wiki/issues/867