[FR] Add `osu!_wiki/Contribution_guide/GitHub_web-based_editor`
ppy/osu-wiki pull request #6494
Opened 2021-12-04 19:40 UTC by DoryanR

Proposal for the French translation of the wiki page `GitHub_web-based_editor`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-07 21:51 UTC, Satsukel requested changes

2021-12-07 21:51 UTC, Satsukel commented on wiki/osu!_wiki/Contribution_guide/GitHub_web-based_editor/fr.md
> +2. Modifiez le fichier si nécessaire. Les changements non commité sont **stockés dans votre navigateur**, et vous pouvez y retourner après avoir quitté `github.dev`.
Soit "commit" parce que théoriquement c'est un mot anglais donc pour moi il devrait pas y avoir à le conjuguer ou sinon "commités" si tu préfères ta version à toi de voir

2021-12-07 21:51 UTC, Satsukel commented on wiki/osu!_wiki/Contribution_guide/GitHub_web-based_editor/fr.md
> +2. Modifiez le fichier si nécessaire. Les changements non commité sont **stockés dans votre navigateur**, et vous pouvez y retourner après avoir quitté `github.dev`.
Tu vas peut-être avoir le reflexe de dire que pour "stockés" c'est pareil mais stocker est dans le dico donc ça passe :^)

2021-12-08 05:50 UTC, DoryanR commented on wiki/osu!_wiki/Contribution_guide/GitHub_web-based_editor/fr.md
> +2. Modifiez le fichier si nécessaire. Les changements non commité sont **stockés dans votre navigateur**, et vous pouvez y retourner après avoir quitté `github.dev`.
```suggestion
2. Modifiez le fichier si nécessaire. Les changements des commis qui n'ont pas été publier sont **stockés dans votre navigateur*, et vous pouvez y retourner après avoir quitté `github.dev`.
```

2021-12-08 08:38 UTC, Satsukel requested changes
Je corrige juste les fautes sur la nouvelle tournure de phrase et j'approuverai après

2021-12-08 08:38 UTC, Satsukel commented on wiki/osu!_wiki/Contribution_guide/GitHub_web-based_editor/fr.md
> +2. Modifiez le fichier si nécessaire. Les changements des commis qui n'ont pas été publier sont **stockés dans votre navigateur**, et vous pouvez y retourner après avoir quitté `github.dev`.
```suggestion
2. Modifiez le fichier si nécessaire. Les changements des commits qui n'ont pas été publiés sont **stockés dans votre navigateur**, et vous pouvez y retourner après avoir quitté `github.dev`.
```

2021-12-08 09:27 UTC, Satsukel approved these changes

2021-12-08 10:28 UTC, Walavouchey approved these changes

2021-12-08 10:29 UTC, merged