[ID] Update `Beatmapping/Star_rating` and `Beatmapping/Overall_difficulty`
ppy/osu-wiki pull request #6497
Opened 2021-12-05 11:38 UTC by ZeroPyrozen

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-06 21:57 UTC, ZeroPyrozen commented on wiki/Beatmapping/Overall_difficulty/id.md
> +Nilai OD yang paling tinggi memiliki waktu paling pendek untuk menyelesaikan [hit object](/wiki/Hit_object), baik secara umum maupun dalam mendapatkan skor yang tinggi. Besar dari hit window, berpusa
Would be better worded like this?
>Semakin tinggi nilai OD, semakin pendek jeda waktu untuk menekan [hit object](/wiki/Hit_object), baik secara umum maupun dalam mendapatkan skor yang tinggi.

2021-12-11 12:22 UTC, Walavouchey requested changes

2021-12-11 12:22 UTC, Walavouchey commented on wiki/Beatmapping/Star_rating/id.md
> +Pada lokasi yang lain, seperti [AIMod](/wiki/Beatmap_Editor/AiMod), tingkat kesulitan diklasifikasikan ke dalam enam rentang level berdasarkan star rating berikut ini:
this is wrong on the english article as well

```suggestion
Pada lokasi yang lain, seperti [AiMod](/wiki/Beatmap_Editor/AiMod), tingkat kesulitan diklasifikasikan ke dalam enam rentang level berdasarkan star rating berikut ini:
```

2021-12-11 15:23 UTC, Walavouchey approved these changes

2021-12-11 15:23 UTC, merged

2021-12-11 15:30 UTC, Walavouchey commented
the `SKIP_OUTDATED_CHECK` tag failed to disable the one ci check that failed. the french article was already correct