[FR] Update `People/Users_with_unique_titles`
ppy/osu-wiki pull request #6502
Opened 2021-12-05 21:05 UTC by DoryanR

Proposal to update the French translation of the wiki page `Users_with_unique_titles`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-05 21:08 UTC, DoryanR commented on wiki/People/Users_with_unique_titles/fr.md
```suggestion

Les gagnants de la [TWC 2021](/wiki/Tournaments/TWC/2021) avec le titre d'utilisateur **osu!taiko Champion** :

```

2021-12-07 21:39 UTC, Satsukel requested changes

2021-12-07 21:39 UTC, Satsukel commented on wiki/People/Users_with_unique_titles/fr.md
>  ### Les gagnants officiels du concours de mapping
```suggestion
### Gagnants officiels du concours de mapping
```
Vu que plus bas tu enlèves aussi "Les"

2021-12-08 08:35 UTC, Satsukel approved these changes

2021-12-08 10:52 UTC, Walavouchey approved these changes

2021-12-08 10:53 UTC, merged