[FR] Update `Beatmap/Guest_difficulty`
ppy/osu-wiki pull request #6504
Opened 2021-12-05 21:29 UTC by DoryanR

Proposal to update the French translation of the wiki page `Beatmap/Guest_difficulty`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-05 21:33 UTC, DoryanR commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Le propriétaire d'une difficulté d'invitée ne peut pas être modifiée si le beatmap est [qualifiée](wiki/Beatmap/Category#qualifiée), [classée](wiki/Beatmap/Category#classée), ou [loved](wiki/Beatmap/
```suggestion
Le propriétaire d'une difficulté d'invitée ne peut pas être modifiée si le beatmap est [qualifiée](/wiki/Beatmap/Category#qualifiée), [classée](/wiki/Beatmap/Category#classée), ou [loved](/wiki/Beatmap/Category#loved).

```

2021-12-05 21:33 UTC, DoryanR commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Sur la page de [discussion d'une beatmap](wiki/Beatmap_Discussion), l'hôte de la beatmap peut transférer la propriétaire des difficultés d'invitées à leurs mappeurs respectifs par le biais du bouton
```suggestion
Sur la page de [discussion d'une beatmap](/wiki/Beatmap_Discussion), l'hôte de la beatmap peut transférer la propriétaire des difficultés d'invitées à leurs mappeurs respectifs par le biais du bouton `Difficulty Owner`. Cela permet aux propriétaires des difficultés d'invitées de résoudre eux-mêmes les problèmes en suspens dans leurs difficultés.
```

2021-12-07 21:27 UTC, Satsukel requested changes
Yo, ça faisait un moment que j'avais pas review j'espère que t'es chaud :^)

2021-12-07 21:27 UTC, Satsukel commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Les difficultés d'invitées ne doivent pas être confondues avec les difficultés qui mettent en scène plusieurs mappeurs, qui sont plutôt connues sous le nom de *[collabs](/wiki/Beatmap/Beatmap_collabo
```suggestion
Les difficultés d'invités ne doivent pas être confondues avec les difficultés qui mettent en scène plusieurs mappeurs, qui sont plutôt connues sous le nom de *[collabs](/wiki/Beatmap/Beatmap_collaborations)*.
```

2021-12-07 21:27 UTC, Satsukel commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Sur la page de [discussion d'une beatmap](/wiki/Beatmap_Discussion), l'hôte de la beatmap peut transférer la propriétaire des difficultés d'invitées à leurs mappeurs respectifs par le biais du bouton
```suggestion
Sur la page de [discussion d'une beatmap](/wiki/Beatmap_Discussion), l'hôte de la beatmap peut transférer la propriété des difficultés d'invités à leurs mappeurs respectifs par le biais du bouton `Difficulty Owner`. Cela permet aux propriétaires des difficultés d'invités de résoudre eux-mêmes les problèmes en suspens dans leurs difficultés.
```

2021-12-07 21:27 UTC, Satsukel commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Le propriétaire d'une difficulté d'invitée ne peut pas être modifiée si le beatmap est [qualifiée](/wiki/Beatmap/Category#qualifiée), [classée](/wiki/Beatmap/Category#classée), ou [loved](/wiki/Beatm
```suggestion
Le propriétaire d'une difficulté d'invité ne peut pas être modifié si la beatmap est [qualifiée](/wiki/Beatmap/Category#qualifiée), [classée](/wiki/Beatmap/Category#classée), ou [loved](/wiki/Beatmap/Category#loved).
```

2021-12-07 21:30 UTC, Satsukel commented on wiki/Beatmap/Guest_difficulty/fr.md
> +Sur la page de [discussion d'une beatmap](/wiki/Beatmap_Discussion), l'hôte de la beatmap peut transférer la propriétaire des difficultés d'invitées à leurs mappeurs respectifs par le biais du bouton
Jsuis pas fan de "propriété" mais sur le coup il fallait bien mettre quelque chose pour corriger la faute

2021-12-08 08:34 UTC, Satsukel approved these changes

2021-12-08 10:54 UTC, Walavouchey approved these changes

2021-12-08 10:55 UTC, merged