Add `osu! South East Asia Tournament 5` wiki article
ppy/osu-wiki pull request #6508
Opened 2021-12-06 16:20 UTC by Nivalyx

wiki page for the currently ongoing [osu! South East Asia Tournament 5](http://osu.ppy.sh/community/forums/topics/1452561?n=1) (it's that time of the year again, yup)

please ignore the duplicate maps in the mappool btw; those aren't a mistake as the mappool is... *specifically intended* to be that way 🐇 

---

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2021-12-06 16:41 UTC, Walavouchey requested changes

2021-12-06 16:41 UTC, Walavouchey commented on wiki/Tournaments/oSEAT/5/en.md
> +The **osu! South East Asia Tournament 5** (***oSEAT5***) is a double-elimination 1v1 osu! tournament hosted by ![][flag_MY] [Its not Marvin](https://osu.ppy.sh/users/13600612), ![][flag_SG] [phox](ht
dead link, probably moved

```suggestion
The **osu! South East Asia Tournament 5** (***oSEAT5***) is a double-elimination 1v1 osu! tournament hosted by ![][flag_MY] [Its not Marvin](https://osu.ppy.sh/users/13600612), ![][flag_SG] [phox](https://osu.ppy.sh/users/772295), and ![][flag_FR] [Taevas](https://osu.ppy.sh/users/7276846). The tournament is open to all players from all ten [ASEAN member states](https://asean.org/about-asean/member-states/) (![][flag_BN] Brunei Darussalam, ![][flag_KH] Cambodia, ![][flag_ID] Indonesia, ![][flag_LA] Laos, ![][flag_MY] Malaysia, ![][flag_MM] Myanmar, ![][flag_PH] The Phillipines, ![][flag_SG] Singapore, ![][flag_TH] Thailand, and ![][flag_VN] Vietnam) regardless of rank. It is the 5th instalment of the osu! South East Asia Tournament.
```

2021-12-06 17:19 UTC, Walavouchey requested changes
may want to apply changes to the rulesets of the previous iterations as well

2021-12-06 17:19 UTC, Walavouchey commented on wiki/Tournaments/oSEAT/5/en.md
> +   - Players who ranked #97 or lower based on their accumulated Qualifier Points will be knocked out from the tournament.
table

2021-12-06 17:19 UTC, Walavouchey commented on wiki/Tournaments/oSEAT/5/en.md
> +   - Players who Win By Default.
```suggestion
   - Players who win by default.
```

2021-12-06 17:19 UTC, Walavouchey commented on wiki/Tournaments/oSEAT/5/en.md
> +   - If there are players who is disqualified from the tournament.
```suggestion
   - If there are players who are disqualified from the tournament.
```

2021-12-06 17:58 UTC, Nivalyx commented
@Walavouchey applied all, thanks for the check as always!

not sure about changing the rulesets of the previous iterations as you suggested tho as i feel like it's out of scope for this pr/it would be more proper to be done in a separate pr instead

2021-12-06 18:09 UTC, Walavouchey commented on wiki/Tournaments/oSEAT/5/en.md
> +| #81 - #96 | Lower Preliminary group bracket (as **Seed D** players) |
hmm... what do you think

```suggestion
| Qualifier ranking | Preliminary group bracket |
| :-: | :-- |
| #1 - #8 | Upper / **Seed A** |
| #9 - #16 | Upper / **Seed B** |
| #17 - #24 | Upper / **Seed C** |
| #25 - #32 | Upper / **Seed D**) |
| #33 - #48 | Lower / **Seed A** |
| #49 - #64 | Lower / **Seed B** |
| #65 - #80 | Lower / **Seed C** |
| #81 - #96 | Lower / **Seed D** |
```

2021-12-06 18:12 UTC, Walavouchey commented on wiki/Tournaments/oSEAT/5/en.md
> +oSEAT4 is run by various osu! community members predominantly hailing from various South East Asian countries.
hang on ya missed this

```suggestion
oSEAT5 is run by various osu! community members predominantly hailing from various South East Asian countries.
```

2021-12-06 18:38 UTC, Nivalyx commented on wiki/Tournaments/oSEAT/5/en.md
> +| #81 - #96 | Lower Preliminary group bracket (as **Seed D** players) |
looks better yeah, i'll go with this

2021-12-06 23:22 UTC, ZeroPyrozen commented on wiki/Tournaments/oSEAT/5/en.md
> +The **osu! South East Asia Tournament 5** (***oSEAT5***) is a double-elimination 1v1 osu! tournament hosted by ![][flag_MY] [Its not Marvin](https://osu.ppy.sh/users/13600612), ![][flag_SG] [phox](ht
```suggestion
The **osu! South East Asia Tournament 5** (***oSEAT5***) is a double-elimination 1v1 osu! tournament hosted by ![][flag_MY] [Its not Marvin](https://osu.ppy.sh/users/13600612), ![][flag_SG] [phox](https://osu.ppy.sh/users/772295), and ![][flag_FR] [Taevas](https://osu.ppy.sh/users/7276846). The tournament is open to all players from all ten [ASEAN member states](https://asean.org/asean/about-asean/member-states/) (![][flag_BN] Brunei Darussalam, ![][flag_KH] Cambodia, ![][flag_ID] Indonesia, ![][flag_LA] Laos, ![][flag_MY] Malaysia, ![][flag_MM] Myanmar, ![][flag_PH] Philippines, ![][flag_SG] Singapore, ![][flag_TH] Thailand, and ![][flag_VN] Vietnam) regardless of rank. It is the 5th instalment of the osu! South East Asia Tournament.
```

2021-12-06 23:22 UTC, ZeroPyrozen commented on wiki/Tournaments/oSEAT/5/en.md
> +¹ *Despite having the ![][flag_US] American flag on their profile, [\_Kolin](https://osu.ppy.sh/users/7249644) is eligible to participate in the tournament as they are in possession of a valid ![][fl
```suggestion
¹ *Despite having the ![][flag_US] American flag on their profile, [\_Kolin](https://osu.ppy.sh/users/7249644) is eligible to participate in the tournament as they are in possession of a valid ![][flag_PH] [Philippine passport](https://en.wikipedia.org/wiki/Philippine_passport).*
```

2021-12-06 23:22 UTC, ZeroPyrozen commented on wiki/Tournaments/oSEAT/5/en.md
> +² *Despite having the ![][flag_JP] Japanese flag on their profile, [ZHKPN](https://osu.ppy.sh/users/13042221) is eligible to participate in the tournament as they are a citizen of ![][flag_PH] The Ph
```suggestion
² *Despite having the ![][flag_JP] Japanese flag on their profile, [ZHKPN](https://osu.ppy.sh/users/13042221) is eligible to participate in the tournament as they are a citizen of ![][flag_PH] Philippines living abroad.*
```

2021-12-06 23:22 UTC, ZeroPyrozen commented on wiki/Tournaments/oSEAT/5/en.md
> +     - Have the flag of any of the ten [ASEAN member states](https://asean.org/asean/asean-member-states/) (![][flag_BN] Brunei Darussalam, ![][flag_KH] Cambodia, ![][flag_ID] Indonesia, ![][flag_LA]
```suggestion
     - Have the flag of any of the ten [ASEAN member states](https://asean.org/asean/asean-member-states/) (![][flag_BN] Brunei Darussalam, ![][flag_KH] Cambodia, ![][flag_ID] Indonesia, ![][flag_LA] Laos, ![][flag_MY] Malaysia, ![][flag_MM] Myanmar, ![][flag_PH] Philippines, ![][flag_SG] Singapore, ![][flag_TH] Thailand, or ![][flag_VN] Vietnam) displayed on their profile, ***or***
```

2021-12-06 23:25 UTC, ZeroPyrozen commented on wiki/Tournaments/oSEAT/5/en.md
> +The **osu! South East Asia Tournament 5** (***oSEAT5***) is a double-elimination 1v1 osu! tournament hosted by ![][flag_MY] [Its not Marvin](https://osu.ppy.sh/users/13600612), ![][flag_SG] [phox](ht
I'm not sure whether it's Philippines or Philippine

2021-12-07 05:02 UTC, Nivalyx commented
oh yeah true it should be `The Philippines` instead of `The Phillipines` whoops

fixed!

2021-12-08 10:58 UTC, Walavouchey approved these changes

2021-12-08 11:00 UTC, merged