[FR] Update `Community\Project_Loved`, `How_you_can_help!`, `Community_Mentorship_Program`, Add `Community`, `Forum`, `Feature_Requests`, `Help`, `Modding_Queues`, `Off-Topic`, `Video_series`
ppy/osu-wiki pull request #6524
Opened 2021-12-10 18:24 UTC by DoryanR

Translation of the following wiki pages:

- `Video_series`
- `Community\Forum\Feature_Requests`
- `Community\Forum`
- `Community\Forum\Help` 
- `Community\Forum\Modding_Queues`
- `Community\Forum\Off-Topic`
- `Community\Video_series`

Update of the translations of the following wiki pages:

- `Community\Community_Mentorship_Program`
- `Community\Project_Loved`
- `Community\How_you_can_help!`
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-10 20:51 UTC, DoryanR commented on wiki/Community/fr.md
> +- [Internet Relay Chat](/wiki/Community/Internet_Relay_Chat) (IRC)
```suggestion
## Places

- [Forum](/wiki/Community/Forum)
- [Internet Relay Chat](/wiki/Community/Internet_Relay_Chat) (IRC)
```

2021-12-12 16:56 UTC, Ganondorf-1 requested changes

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Forum/Help/fr.md
> +[**Help**](https://osu.ppy.sh/community/forums/5) est un forum où les joueurs peuvent recevoir une assistance technique de la part des membres de l'[Équipe du support](/wiki/People/The_Team/Support_T
```suggestion
[**Help**](https://osu.ppy.sh/community/forums/5) est un forum où les joueurs peuvent recevoir une assistance technique de la part des membres de l'[Équipe du support](/wiki/People/The_Team/Support_Team) ou des autres utilisateurs.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Forum/Modding_Queues/fr.md
> +[**Modding Queues**](https://osu.ppy.sh/community/forums/60) est un forum dédié aux demandes de [review des beatmaps](/wiki/Modding), ou mods. Il est constitué de fils de discussion, ou *queues*, app
```suggestion
[**Modding Queues**](https://osu.ppy.sh/community/forums/60) est un forum dédié aux demandes de [review des beatmaps](/wiki/Modding), ou de modding. Il est constitué de fils de discussion, ou *queues*, appartenant à différents moddeurs et mappeurs. Chaque file d'attente a des exigences et des limites individuelles pour l'obtention des mods, qui doivent être respectées par les visiteurs afin de recevoir un mod.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Forum/fr.md
> +Certains utilisateurs peuvent appartenir à un ou plusieurs groupes personnalisés, en fonction de leurs tâches communautaires, de leurs droits d'accès ou de leur activité passée. Une liste complète de
```suggestion
Certains utilisateurs peuvent appartenir à un ou plusieurs groupes personnalisés, en fonction de leurs tâches communautaires, de leurs droits d'accès ou de leur activité passée. Une liste complète des groupes d'utilisateurs se trouve sur la page [L'équipe § Groupes d'utilisateurs](/wiki/People/The_Team#groupes-d'utilisateurs).
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Forum/fr.md
> +*Voir également : [Reporting bad behaviour § Forum](/wiki/Reporting_Bad_Behaviour#forum)*
```suggestion
*Voir également : [Signaler un mauvais comportement § Forum](/wiki/Reporting_Bad_Behaviour#forum)*
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Forum/fr.md
> +- [Help](/wiki/Community/Forum/Help) : l'assistance technique de l'[Équipe du support](/wiki/People/The_Team/Support_Team) et des utilisateurs réguliers.
```suggestion
- [Help](/wiki/Community/Forum/Help) : l'assistance technique de l'[Équipe du support](/wiki/People/The_Team/Support_Team) et autres utilisateurs.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/How_you_can_help!/fr.md
> +- Suivez vos channels préférées dans le [tchat en jeu d'osu!](/wiki/Chat_Console), ou sur les forums.
```suggestion
- Suivez vos canaux de discussion préférés dans le [tchat en jeu d'osu!](/wiki/Chat_Console), ou sur les forums.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/How_you_can_help!/fr.md
> +- Suivez tous les nouveaux fils de discussion, lisez chacun d'entre eux et apportez votre aide quand vous le pouvez ; vous pouvez utiliser les icônes de unread pour vous assurer de rester à jour.
```suggestion
- Suivez tous les nouveaux fils de discussion, lisez chacun d'entre eux et apportez votre aide quand vous le pouvez ; vous pouvez utiliser les icônes "non lu" pour vous assurer de rester à jour.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/How_you_can_help!/fr.md
> +osu! dispose d'une équipe de reviewers qui vérifient si les [beatmaps](/wiki/Beatmap) sont prêts à être classés et joués par tous. Cependant, cela ne signifie pas que vous ne pouvez pas contribuer à
```suggestion
osu! dispose d'une équipe de reviewers qui vérifient si les [beatmaps](/wiki/Beatmap) sont prêtes à être classées et jouées par tous. Cependant, cela ne signifie pas que vous ne pouvez pas contribuer à ce secteur :
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/How_you_can_help!/fr.md
> +- Lisez le [Guide de modding](/wiki/Modding) et les [Critères de classement](/wiki/Ranking_Criteria) pour connaître les bases du modding technique et savoir ce qui rend un beatmap classable.
```suggestion
- Lisez le [Guide de modding](/wiki/Modding) et les [Critères de classement](/wiki/Ranking_Criteria) pour connaître les bases du modding technique et savoir ce qui rend une beatmap classable.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/How_you_can_help!/fr.md
> +- Aidez le projet [osu!lazer](https://github.com/ppy/osu). Il y a tellement de choses à implémenter dans la nouvelle version d'osu! et vous pouvez aider à les réaliser !
```suggestion
- Aider le projet [osu!lazer](https://github.com/ppy/osu). Il y a tellement de choses à implémenter dans la nouvelle version d'osu! et vous pouvez aider à les réaliser !
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
> +Les beatmaps sont déplacés vers la catégorie loved par un processus de nomination et de vote.
```suggestion
Les beatmaps sont déplacées vers la catégorie loved par un processus de nomination et de vote.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
>  Les membres de l'équipe du Project Loved appelés **capitaines** nomment régulièrement des beatmaps pour un mode de jeu spécifique. Ces ensembles proviennent presque toujours de propositions de la com
```suggestion
Les membres de l'équipe du Project Loved appelés **capitaines** nomment régulièrement des beatmaps pour un mode de jeu spécifique. Ces beatmapsets proviennent presque toujours de propositions de la communauté d'osu!.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
> +Pour soumettre un beatmap pour la catégorie loved, veuillez visiter la [page de soumission d'une beatmap](https://loved.sh/submit) du site web du Project Loved et remplir le formulaire. Une fois le f
```suggestion
Pour soumettre une beatmap pour la catégorie loved, veuillez visiter la [page de soumission de beatmap](https://loved.sh/submit) du site web du Project Loved et remplir le formulaire. Une fois le formulaire envoyé, vous pourrez voir votre proposition dans la liste de son mode de jeu respectif avec les autres. Vous trouverez ci-dessous les listes où ces propositions peuvent être consultées :
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
> +Les beatmaps nominés sont ensuite publiés sur le forum [Project Loved](https://osu.ppy.sh/community/forums/120), où les membres de la communauté peuvent voter s'ils souhaitent que la beatmap soit "lo
```suggestion
Les beatmaps nominées sont ensuite publiées sur le forum [Project Loved](https://osu.ppy.sh/community/forums/120), où les membres de la communauté peuvent voter s'ils souhaitent que la beatmap soit "loved" ou non. Les beatmaps qui atteignent un certain pourcentage de votes positifs à la fin du scrutin sont transférées dans la catégorie Loved.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
>  - Son créateur ne désapprouve pas le fait qu'elle soit prêté.
```suggestion
- Son créateur ne désapprouve pas le fait qu'elle soit loved.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
>  - Au moins une difficulté peut être jouable
```suggestion
- Au moins une difficulté peut être jouée jusqu'au bout sans échouer
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
> +Il n'existe pas de règles strictes régissant les beatmaps qu'un capitaine doit proposer pour la catégorie loved, mais en général, les beatmaps proposées sont très connues et appréciées par la communa
```suggestion
Il n'existe pas de règles strictes régissant les beatmaps qu'un capitaine doit proposer pour la catégorie loved, mais en général, les beatmaps proposées sont très connues et appréciées par la communauté (comme l'indique le titre "loved"). Parfois, un beatmapset sera également préféré s'il est nettement plus ancien que les autres ou s'il contient des difficultés avec des styles de mapping uniques et de haute qualité.
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Video_series/fr.md
> +# Série de vidéos communautaires
```suggestion
# Séries vidéo communautaires
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/fr.md
> +- [Série de vidéos](/wiki/Community/Video_series)
```suggestion
- [Séries vidéo](/wiki/Community/Video_series)
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/Project_Loved/fr.md
>  ## Déplacer une beatmap vers Loved
```suggestion
## Déplacer une beatmap vers la catégorie loved
```

2021-12-12 16:56 UTC, Ganondorf-1 commented on wiki/Community/fr.md
> +Cette page répertorie les moyens par lesquels les personnes de tout le site d'osu! peuvent entrer en contact les unes avec les autres. Si vous êtes à la recherche d'opportunités de contribution, mais
```suggestion
Cette page répertorie les moyens par lesquels les utilisateurs de tout le site d'osu! peuvent entrer en contact les uns avec les autres. Si vous êtes à la recherche d'opportunités de contribution, mais ne savez pas par où commencer, assurez-vous de lire [Comment vous pouvez aider !](/wiki/Community/How_you_can_help!).
```

2021-12-12 19:49 UTC, DoryanR commented on wiki/Community/Project_Loved/fr.md
>  Les membres de l'équipe du Project Loved appelés **capitaines** nomment régulièrement des beatmaps pour un mode de jeu spécifique. Ces ensembles proviennent presque toujours de propositions de la com
Beatmapsets est un mot qui ne doit plus servir désormais, je vais le remplacer par `beatmap`

2021-12-12 19:50 UTC, DoryanR commented on wiki/Community/Project_Loved/fr.md
>  Les membres de l'équipe du Project Loved appelés **capitaines** nomment régulièrement des beatmaps pour un mode de jeu spécifique. Ces ensembles proviennent presque toujours de propositions de la com
```suggestion
Les membres de l'équipe du Project Loved appelés **capitaines** nomment régulièrement des beatmaps pour un mode de jeu spécifique. Ces beatmaps proviennent presque toujours de propositions de la communauté d'osu!.
```

2021-12-12 19:51 UTC, DoryanR commented on wiki/Community/Project_Loved/fr.md
> +Il n'existe pas de règles strictes régissant les beatmaps qu'un capitaine doit proposer pour la catégorie loved, mais en général, les beatmaps proposées sont très connues et appréciées par la communa
```suggestion
Il n'existe pas de règles strictes régissant les beatmaps qu'un capitaine doit proposer pour la catégorie loved, mais en général, les beatmaps proposées sont très connues et appréciées par la communauté (comme l'indique le titre "loved"). Parfois, une beatmap sera également préféré s'il est nettement plus ancien que les autres ou s'il contient des difficultés avec des styles de mapping uniques et de haute qualité.
```

2021-12-14 23:33 UTC, Walavouchey approved these changes

2021-12-14 23:35 UTC, merged