[FR] Add `Guides\osu!mania_Mapping_Guide`
ppy/osu-wiki pull request #6535
Opened 2021-12-12 13:19 UTC by DoryanR

Proposal for the French translation of the wiki page `osu!mania_Mapping_Guide`.

Also:

- Addition of the French images
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-12 13:26 UTC, DoryanR commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Nous voudrions aussi vous montrer un petit programme qui peut être très utile pour trouver le bon BPM très rapidement. Il s'appelle ***MixMeister BPM Analyzer***. Ce programme vous montrera le BPM mo
```suggestion
Nous voudrions aussi vous montrer un petit programme qui peut être très utile pour trouver le bon BPM très rapidement. Il s'appelle ***MixMeister BPM Analyzer***. Ce programme vous montrera le BPM moyen de votre chanson. Il a juste un point faible. Il ne peut pas vous montrer plusieurs BPM. Il vous montrera le BPM moyen de tous les points de BPM de votre chanson. Pour le dire simplement : Il n'aide qu'avec un seul BPM. Vous pouvez le rechercher sur Google ou simplement cliquer [ici](https://dropbox.com/s/m4pjenvo4n65943/bpmanalyzer.zip?dl=0). N'essayez pas de l'utiliser pour timer toutes vos beatmaps. Vous n'apprendrez jamais à timer des musiques si vous laissez ce programme timer tout pour vous. Utilisez-le pour le comparer avec votre BPM pour vérifier si vous avez le bon !
```

2021-12-12 13:30 UTC, Walavouchey commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +![Éditeur d'osu!mania](img/Mania_Editor-FR.jpg "Éditeur d'osu!mania")
```suggestion
![Éditeur d'osu!mania](img/Mania_Editor-FR.png "Éditeur d'osu!mania")
```

2021-12-12 13:31 UTC, Walavouchey commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +![Éditeur d'osu!mania](img/Mania_Editor-FR.jpg "Éditeur d'osu!mania")
can be converted to jpg

2021-12-17 15:06 UTC, Satsukel requested changes
I don't have a lot of time at the moment but I'll try to review all your current PR. I didn't even have time to finish this one yet (might finish it later today tho). I wont have time to review until next week so I hope they wont be merged until then.

2021-12-17 21:35 UTC, Satsukel requested changes
ça devrait être bon après ça

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +**La difficulté "Hard"** : Dans la difficulté Hard, nous pouvons commencer à ajouter des motifs plus compliqués car le joueur doit avoir appris les bases de Easy et Normal. Nous pouvons commencer à a
```suggestion
**La difficulté "Hard"** : Dans la difficulté Hard, nous pouvons commencer à ajouter des motifs plus compliqués car le joueur doit avoir appris les bases de Easy et Normal. Nous pouvons commencer à ajouter de plus longues salves de 1/4 et des pattern stairs, nous pouvons également commencer à utiliser des chords de 3 notes pour les cymbales lourdes à la fin ou au début d'une partie. De même, en fonction du bpm et de la partie de votre beatmap, nous pouvons utiliser des jumpstreams courts mais assurez-vous qu'ils correspondent à la partie que vous mappez actuellement. Lorsque la musique devient plus trépidante et plus rapide, c'est le moment idéal pour ajouter un tel jumpstream. Vous pouvez également commencer à utiliser de courts pattern jack ici. Ce que vous devez éviter, ce sont les chord trills. Les chord trills ont une densité de pattern très élevée, ce qui peut entraîner un star ranting très élevé. Vous pouvez bien sûr utiliser de courts chord triples, mais ils ne devraient pas avoir un impact important sur le star ranting. Le kiai doit être la partie la plus dense de votre beatmap si possible. Aussi, vous pouvez essayer de combiner plus de LN et de patterns 1/4 de notes simples. Essayez de combiner différentes longueurs de patterns LN en même temps ! Cela peut donner à votre beatmap une sensation particulière en utilisant plus d'une LN en même temps. Mais fais très attention. Assurez-vous que chaque LN suit un son ! Ne les ajoutez pas "au hasard" dans votre musique juste parce que vous pensez que cela pourrait bien jouer. En fonction du BPM, il est également possible d'ajouter de courts patterns stairs 1/6 ou 1/8. Mais utilisez-les avec précaution. Ne les utilisez que si votre musique en offre suffisamment l'occasion. Les stairs 1/6 ne doivent pas être plus long qu'un 1/2 temps et le 1/8 pas plus long qu'un 1/4 temps ! Plus le bpm de votre chanson est bas, plus ces pattern stairs peuvent être longs.
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +**Les difficultés "Insane" et "Extreme"** : Maintenant, nous nous concentrons sur les difficultés Insane et Extreme. Encore une fois, nous augmentons la densité du pattern et commençons à utiliser de
Ce passage donne un peu mal au crane à certains moments je te conseille de le relire si jamais tu vois des choses qui vont pas niveau répétition mais franchement je vois pas comment faire plus clair sans répeter parfois x)
```suggestion
**Les difficultés "Insane" et "Extreme"** : Maintenant, nous nous concentrons sur les difficultés Insane et Extreme. Encore une fois, nous augmentons la densité des patterns et commençons à en utiliser des encore plus compliqués ! Vous pouvez maintenant utiliser toutes sortes de patterns et essayer de les combiner. De plus, vous pouvez maintenant utiliser des LN 1/8 ainsi que des chord trills ! Les difficultés Insane et Extreme sont surtout destinées aux joueurs plus expérimentés, donc vous devriez essayer de créer une difficulté vraiment agréable à jouer et toujours plus excitante. Essayez de combiner les jumpstreams avec les trills et le heavy chord mashing. Vous pouvez maintenant utiliser les chords à 3 notes pour faire plus que simplement souligner la fin d'une certaine partie de votre chanson. Mais n'oubliez pas : Si vous envisagez d'ajouter une autre difficulté, par exemple une difficulté supplémentaire, vous ne devez pas aller jusqu'aux limites ! Vous devez laisser un peu d'espace pour créer une difficulté encore plus difficile. Je ne peux pas vous dire grand-chose car dans une bonne répartition de difficulté vous devez simplement créer une difficulté plus difficile que la difficile. Si vous prévoyez d'ajouter une difficulté supplémentaire, vous pouvez aller jusqu'aux limites de la chanson. Vous pouvez utiliser des jumpstreams lourds avec des chordmashs lourds. Vous pouvez utiliser des chords de 3 notes dans des jumpstreams entre des chords de 2 notes. Vous devez essayer de repousser les limites de la musique. Mais prenez note de ce qui suit : Une ligne directrice dit que vous devez être capable de passer vos propres difficultés et nous sommes d'accord avec ce point. Si vous voulez vraiment créer une bonne difficulté insane/extreme jouable, vous devez savoir comment elles se jouent et pour cela vous devez être capable de les passer.
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Les Hitsounds sont importants dans tous les modes de jeu. Ils donnent un retour d'information lorsque vous appuyez sur une note, ce qui permet au joueur de savoir ce qu'il vient de frapper. De plus,
```suggestion
Les Hitsounds sont importants dans tous les modes de jeu. Ils donnent un retour d'information lorsque vous appuyez sur une note, ce qui permet au joueur de savoir ce qu'il vient de frapper. De plus, le fait d'avoir différents hitsounds dans votre beatmap peut lui donner une ambiance spéciale car la musique sonne différemment tout d'un coup, peut-être même mieux que sans hitsounds ! osu!mania propose deux façons différentes d'utiliser les hitsounds.
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Si vous voulez utiliser celle par défaut, vous n'avez pas vraiment besoin de changer grand-chose. Tout ce dont vous avez besoin est de décider quel jeu d'échantillons vous voulez utiliser par défaut.
```suggestion
Si vous voulez utiliser ceux par défaut, vous n'avez pas vraiment besoin de changer grand-chose. Tout ce dont vous avez besoin est de décider quel jeu d'échantillons vous voulez utiliser par défaut. Allez dans le panneau de configuration du timing et changez votre point de timing pour le jeu d'échantillons que vous voulez utiliser. osu!mania utilise généralement "soft" par défaut car le hit-normal n'est pas si fort.
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Vous pouvez toujours changer le sample set pour une partie entière en sélectionnant toutes les notes et en la changeant pour le sample set désirée ou vous pouvez ajouter un point hérité (ligne verte)
```suggestion
Vous pouvez toujours changer le sample set pour une partie entière en sélectionnant toutes les notes et en la changeant pour le sample set désiré ou vous pouvez ajouter un point hérité (ligne verte) et changer toute la partie pour le sample set sélectionné jusqu'au prochain point hérité. Il ne vous reste plus qu'à ajouter le son que vous souhaitez ! Vous pouvez choisir entre Finish, Whistle et Clap. Tous ces effets sonnent différemment lorsque vous changez de jeu d'échantillons. Essayez un peu et je suis sûr que vous trouverez l'effet parfait pour votre musique !
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Tous vos hitsounds du sample set 1 sont maintenant activés ! Si vous utilisez un autre sample set, choisissez le troisième point et choisissez le sample set que vous avez également choisie pour vos h
```suggestion
Tous vos hitsounds du sample set 1 sont maintenant activés ! Si vous utilisez un autre sample set, choisissez le troisième point et choisissez le sample set que vous avez également choisi pour vos hitsounds.
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Une fois que vous avez enfin vos hitsounds, n'oubliez pas d'activer "Lock Notes". De cette façon, aucune note ne pourra être déplacée lorsque vous ferez un mouvement sur votre beatmap. Le Hitsounding
```suggestion
Une fois que vous avez enfin vos hitsounds, n'oubliez pas d'activer "Lock Notes". De cette façon, aucune note ne pourra être déplacée pendant que vous modifiez votre beatmap. Le Hitsounding ne prend pas beaucoup de temps. Vous pouvez choisir une ou plusieurs notes en même temps, changer le jeu d'échantillons en haut à gauche de l'écran et ajouter l'effet sur le côté droit. Maintenant, toutes ces notes ont un hitsound !
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Le Slider Velocity agit un peu différemment dans osu!mania ; elle modifie la vitesse à laquelle les notes défilent vers le bas. Plus le Slider Velocity est élevée, plus les notes descendent vite, et
```suggestion
Le Slider Velocity agit un peu différemment dans osu!mania ; il modifie la vitesse à laquelle les notes défilent vers le bas. Plus le Slider Velocity est élevé, plus les notes descendent vite, et plus il est faible, plus les notes descendent lentement.
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Le style DCP/LCP met l'accent sur la pertinence musicale grâce à des techniques de mapping telles que la pertinence de la hauteur et la théorie du jack. (La théorie du jack consiste essentiellement à
```suggestion
Le style DCP/LCP met l'accent sur la pertinence musicale grâce à des techniques de mapping telles que la pertinence de la hauteur et la théorie du jack. (La théorie du jack consiste essentiellement à créer des jacks pour mettre en valeur un certain instrument, comme un crash de cymbale). Les beatmaps DCP/LCP sont plus appréciées par leurs mappeurs que par les joueurs car elles se concentrent principalement sur la pertinence musicale et pas tellement sur la jouabilité.
```

2021-12-17 21:35 UTC, Satsukel commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +Le style yolomania s'appuie plus sur le paternalisme qu'autre chose. Il s'attache davantage à créer de bons tableaux jouables pour le joueur et la communauté. Bien qu'il utilise toujours le concept d
```suggestion
Le style yolomania s'appuie plus sur le patterning qu'autre chose. Il s'attache davantage à créer de bonnes beatmaps jouables pour le joueur et la communauté. Bien qu'il utilise toujours le concept de pertinence de la hauteur, il n'est pas non plus très important.
```

2021-12-18 07:40 UTC, Satsukel submitted a review, later dismissed

2021-12-18 13:43 UTC, Walavouchey commented on wiki/Guides/osu!mania_Mapping_Guide/fr.md
> +| Timing Point : | Le point de synchronisation ou "ligne rouge" est là pour synchroniser votre chanson. Sans lui, vous ne pouvez pas commencer le mapping. Reportez-vous aux étapes ci-dessus pour [**t
```suggestion
| Timing Point : | Le point de synchronisation ou "ligne rouge" est là pour synchroniser votre chanson. Sans lui, vous ne pouvez pas commencer le mapping. Reportez-vous aux étapes ci-dessus pour [*timer*](#timing) votre chanson. |
```

2021-12-18 13:44 UTC, Walavouchey approved these changes

2021-12-18 13:45 UTC, merged