[FR] Add `Guides\osu!mania_modding_guide`
ppy/osu-wiki pull request #6537
Opened 2021-12-12 16:15 UTC by DoryanR

Proposal for the French translation of the wiki page `osu!mania_modding_guide`.

Also:

- Addition of the French images
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-20 22:56 UTC, Satsukel requested changes
J'ai fais la moitié pour l'instant, je continuerai surement demain

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +- **Train de la hype :** Les hypes sont utilisés comme un moyen de promouvoir les beatmaps et de signaler l'intérêt de voir la beatmap classée. Les hypes sont nécessaires pour qu'une beatmap soit qua
```suggestion
- **Train de la hype :** Les hypes sont utilisés comme un moyen de promouvoir les beatmaps et de signaler l'intérêt de voir la beatmap classée. Les hypes sont nécessaires pour qu'une beatmap soit qualifiée. En effet, pour qu'un Beatmap Nominator puisse nommer une beatmap, celle-ci doit atteindre au moins 5 hypes. Chaque utilisateur ne peut mettre en avant une beatmap qu'une seule fois, et les hypes sont distribués tous les 7 jours, jusqu'à un maximum de 10 hype.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +- **Général (Toutes les difficultés) :** Les messages postés ici seront affichés pour toutes les difficultés, ce qui est généralement réservé pour mentionner des choses qui affectent toutes les diffi
```suggestion
- **Général (Toutes les difficultés) :** Les messages postés ici seront affichés pour toutes les difficultés, ce qui est généralement réservé pour mentionner des choses qui affectent toutes les difficultés, comme des suggestions de points de synchronisation ou des métadonnées. La promotion d'une beatmap se fait également ici.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +- **Chronologie :** C'est ici que se fait l'essentiel du modding. Tous les problèmes/suggestions pour les sections ou les notes dans la difficulté choisie ci-dessus appartiennent ici. Il est nécessai
```suggestion
- **Chronologie :** C'est ici que se fait l'essentiel du modding. Tous les problèmes/suggestions pour les sections ou les notes dans la difficulté choisie ci-dessus se trouvent ici. Il est nécessaire de copier/coller un horodatage depuis l'éditeur vers la page de discussion avant de poster un message, afin que le mappeur sache de quelle section il s'agit.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +- **Hype! :** Visible uniquement dans la section Général (toutes difficultés) de la page de discussion du modding. Cela coûte 1 hype et augmente le hype de la beatmap de 1. Une beatmap doit avoir 5 h
```suggestion
- **Hype! :** Visible uniquement dans la section Général (toutes difficultés) de la page de discussion du modding. Cela coûte 1 hype et augmente la hype de la beatmap de 1. Une beatmap doit avoir 5 hype avant de pouvoir être vérifiée par les Beatmap Nominators.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Lorsqu'un message est marqué comme une **suggestion**, c'est pour des changements qui sont subjectifs et qui ne sont pas impossibles à classer. Des changements de patterns, des placements de notes sp
```suggestion
Lorsqu'un message est marqué comme une **suggestion**, c'est pour des changements qui sont subjectifs et qui ne sont pas impossibles à classer. Des changements de patterns, des placements de notes spécifiques, et d'autres changements qui pourraient améliorer la carte. Ceci est principalement utilisé si le moddeur trouve certains patterns inconfortables, ou trouve une note mal placée mais n'est pas sûr.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +**Avant de commencer** : Tous les points évoqués ci-dessous ne doivent pas nécessairement être couverts dans chaque mod. Si vous n'êtes pas sûr de quelque chose, comme les métadonnées ou le timing, l
```suggestion
**Avant de commencer** : Tous les points évoqués ci-dessous ne doivent pas nécessairement être couverts dans chaque mod. Si vous n'êtes pas sûr de quelque chose, comme les métadonnées ou le timing, laissez-le de côté. Cependant, il est bon de s'entraîner pour apprendre à couvrir tous les points ci-dessous, car il est nécessaire d'avoir de l'expérience dans tous les domaines pour devenir un Beatmap Nominator. Même si des erreurs sont commises, cela permet d'acquérir de l'expérience et d'apprendre.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Après avoir vérifié AiMod, **vérifier le  timing** d'une beatmap . Un timing correct est obligatoire pour qu'une beatmap soit classé, ainsi que pour des raisons de jouabilité générale.
```suggestion
Après avoir vérifié AiMod, **vérifier le  timing** d'une beatmap . Un timing correct est obligatoire pour qu'une beatmap soit classée, ainsi que pour des raisons de jouabilité générale.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Pour vérifier qu'une beatmap est correctement timer, il faut d'abord vérifier si le BPM est correct. La plupart du temps, ce n'est pas un problème, mais il est bon de le vérifier quand même. La meill
J'ai un peu modifié la phrase de base à la fin mais comme je suis pas fan de "diverger" (bien que je le préfère à "dériver") je préfère pas l'employer trop souvent
```suggestion
Pour vérifier qu'une beatmap est correctement timée, il faut d'abord vérifier si le BPM est correct. La plupart du temps, ce n'est pas un problème, mais il est bon de le vérifier quand même. La meilleure façon de le faire est de vérifier si les battements de la chanson se posent sur une ligne de battement blanche de façon constante et ne divergent pas en avance ou en retard. Augmenter le volume du hitsound et régler la vitesse de lecture de la beatmap plus lentement peut aider. Si les temps de la chanson divergent en avance, diminuez le bpm, dans le cas contraire, augmentez le bpm jusqu'à ce qu'ils correspondent.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +**La vérification des métadonnées de la beatmap** est importante pour le classement de la beatmap, mais à cause de sa maladresse, elle est souvent omise. Les métadonnées sont contenues dans l'onglet
Pas trouvé mieux pour rendre la phrase correcte
```suggestion
**La vérification des métadonnées de la beatmap** est importante pour le classement de la beatmap, mais comme il s'agit d'une tache ardue, elle est souvent omise. Les métadonnées sont contenues dans l'onglet `General` de la fenêtre `Song Setup`, qui inclut le titre de la chanson, l'artiste, etc.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Il est généralement ignoré en raison de l'effort requis pour trouver des sources **officielles** pour une preuve des métadonnées, l'un des principaux problèmes étant lorsque l'artiste et le titre son
```suggestion
Elle est généralement ignorée en raison de l'effort requis pour trouver des sources **officielles** pour une preuve des métadonnées, l'un des principaux problèmes étant lorsque l'artiste et le titre sont écrits dans une langue différente, comme le japonais, le coréen ou le russe. Il n'est pas nécessaire de comprendre d'autres langues pour cela, il suffit que les métadonnées soient exactement les mêmes que dans la source officielle sur Internet.
```

2021-12-20 22:56 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Bien que cette partie puisse être ignorée, la vérification des métadonnées et la publication d'un message à ce sujet peuvent être d'une grande aide pour le mappeur et les BN. Même si les métadonnées
```suggestion
Bien que cette partie puisse être ignorée, la vérification des métadonnées et la publication d'un message à ce sujet peuvent être d'une grande aide pour le mappeur et les BN. Même si les métadonnées sont déjà correctes, il est également utile d'indiquer les bonnes sources pour confirmation.
```

2021-12-21 12:36 UTC, Satsukel requested changes

2021-12-21 12:36 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Avoir une expérience de jeu dans osu!mania donnera un avantage pour cela. Au minimum, essayez d'être capable de jouer avec succès à la difficulté à modder, cependant **ce n'est pas obligatoire** ! Le
```suggestion
Avoir une expérience de jeu dans osu!mania donnera un avantage pour cela. Au minimum, essayez d'être capable de jouer avec succès la difficulté à modder, cependant **ce n'est pas obligatoire** ! Les mappeurs expérimentés savent souvent comment les patterns se "sentent", et peuvent donc les modder sans être en mesure de les jouer.
```

2021-12-21 12:36 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Il est important de respecter l'idée du mappeur derrière la beatmap. Un moddeur est là pour le peaufiner et signaler les problèmes, pas pour refaire la beatmap.
```suggestion
Il est important de respecter l'idée du mappeur derrière la beatmap. Un moddeur est là pour la peaufiner et signaler les problèmes, pas pour refaire la beatmap.
```

2021-12-21 12:36 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Une autre partie importante des beatmaps sont les hitsounds. Si la beatmap n'a pas de hitsounds et que le mappeur prévoit toujours d'en ajouter, la meilleure suggestion est de leur rappeler amicaleme
```suggestion
Une autre partie importante des beatmaps sont les hitsounds. Si la beatmap n'a pas de hitsounds et que le mappeur prévoit toujours d'en ajouter, la meilleure suggestion est de leur rappeler amicalement qu'ils sont nécessaires pour classer une beatmap.
```

2021-12-21 12:36 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Si la beatmap a des hitsounds, n'hésitez pas à les modifier. La première chose à faire est d'avoir une vue d'ensemble de l'idée du mappeur sur la façon dont la beatmap devrait être hitsoundé. osu!man
```suggestion
Si la beatmap a des hitsounds, n'hésitez pas à les modifier. La première chose à faire est d'avoir une vue d'ensemble de l'idée du mappeur sur la façon dont la beatmap devrait être hitsoundée. osu!mania a un avantage sur les autres modes de jeu car les types de hitsounds peuvent être affichés sur les notes. Pour ce faire, allez dans `Visualiser` dans le coin supérieur gauche et choisissez ensuite `Montrer le nom de l'échantillon`. Maintenant, tous les échantillons utilisés sont affichés sur les notes.
```

2021-12-21 12:36 UTC, Satsukel commented on wiki/Guides/osu!mania_modding_guide/fr.md
> +Ensuite, **vérifiez si les hitsounds sont suffisamment audibles**. Les beatmaps dont la difficulté est Hard ou inférieure doivent avoir des hitsounds audibles. Si l'étendue ne contient que des diffic
```suggestion
Ensuite, **vérifiez si les hitsounds sont suffisamment audibles**. Les beatmaps dont la difficulté est Hard ou inférieure doivent avoir des hitsounds audibles. Si le spread ne contient que des difficultés Insane ou supérieures, il est possible de n'y trouver que le son d'impact par défaut. Idéalement, réglez le même volume sur Musique que sur Effet dans les paramètres généraux de volume. Ensuite, écoutez la difficulté à un taux de lecture normal et voyez si les hitsounds sont audibles. Si ce n'est pas le cas, signalez un problème dans la section `Général (cette difficulté)` et informez le mappeur. De plus, trouvez le volume correct pour le mappeur et ajoutez-le à la suggestion. La façon la plus simple de le faire est d'aller dans Timing et d'appuyer sur le panneau de configuration de Timing (ou d'appuyer sur F6), et de sélectionner l'horodatage qui est le premier derrière le point de chronométrage actuel (par exemple, sélectionnez 00:43:392, si le son est calme à 00:43:495). A partir de là, allez dans Audio, et ajustez le volume jusqu'à ce que les sons soient suffisamment audibles, et proposez la nouvelle valeur au mappeur.
```

2021-12-21 13:35 UTC, Biokax approved these changes

2021-12-21 13:53 UTC, Walavouchey approved these changes

2021-12-21 13:54 UTC, merged