[FR] Add `News_Styling_Criteria`
ppy/osu-wiki pull request #6538
Opened 2021-12-12 20:08 UTC by DoryanR

Proposal for the French translation of the wiki page `News_Styling_Criteria`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-21 13:00 UTC, Satsukel requested changes

2021-12-21 13:00 UTC, Satsukel commented on wiki/News_Styling_Criteria/fr.md
> +La largeur de tous les cadres de contenu intégré doit être fixée à ``width: 100%``. Pour être inclus dans les articles en général, le contenu intégré doit pouvoir s'afficher en pleine largeur sans se
```suggestion
La largeur de tous les cadres de contenu intégré doit être fixée à ``width: 100%``. Pour être inclus dans les articles en général, le contenu intégré doit pouvoir s'afficher en pleine largeur sans problème ou sans être horrible.
```

2021-12-21 18:22 UTC, TicClick commented
while the initiative is good, I highly doubt we'll ever have news in any language other than English

2021-12-21 20:04 UTC, DoryanR commented
I am aware of this, but I have translated the article for information purposes. I will add a mention at the top of the article about this point.

2021-12-21 20:06 UTC, DoryanR commented on wiki/News_Styling_Criteria/fr.md
> +Les articles de news existent sur un système légèrement différent du wiki principal d'osu!, mais suivent des principes similaires. Leur rédaction implique une attention particulière à quelques caract
```suggestion
# Critères de style des news

*Pour les articles du wiki, voir : [Critères de mise en forme des articles](/wiki/Article_styling_criteria)*

**Attention : les articles de news sont disponible uniquement en Anglais, et une traduction de ces articles dans d'autres langues n'est pas prévu.**

Les articles de news existent sur un système légèrement différent du wiki principal d'osu!, mais suivent des principes similaires. Leur rédaction implique une attention particulière à quelques caractéristiques et formats clés, comme indiqué ci-dessous.
```

2021-12-21 21:19 UTC, Biokax requested changes

2021-12-21 21:19 UTC, Biokax commented on wiki/News_Styling_Criteria/fr.md
> +Les chaînes de titre d'article pour les noms de fichier sont le titre de l'article lui-même avec tous les espaces remplacés par des traits d'union (`-`), et tous les caractères supplémentaires tels q
le début de la phrase manque de sens, j'ai du mal à la comprendre

2021-12-21 21:19 UTC, Biokax commented on wiki/News_Styling_Criteria/fr.md
> +Les caractères gras sont réservés à la mise en évidence d'objets ou de phrases importants, qu'il s'agisse de joueurs, de scores ou de tout autre élément considéré contextuellement comme un point cent
```suggestion
Les caractères gras sont réservés à la mise en évidence d'objets ou de phrases importantes, qu'il s'agisse de joueurs, de scores ou de tout autre élément considéré contextuellement comme un point central de l'article en question.
```

2021-12-21 21:59 UTC, TicClick commented
> I am aware of this, but I have translated the article for information purposes. I will add a mention at the top of the article about this point.

why? my comment (which I don't find worth the reader's attention) was questioning the purpose of the translation instead

2021-12-21 22:04 UTC, Biokax commented
> while the initiative is good, I highly doubt we'll ever have news in any language other than English

in the translation its say that news need to be write in english, so I think its good

2021-12-22 05:57 UTC, Walavouchey commented
@TicClick Regardless of the fact that news are English-only, I agree that the criteria can be translated just for trivia/informational purposes, because these criteria articles are wiki articles just the same as any other article. Why would the news criteria be in the wiki if they can't be available in other languages?

The community meetings article is also translated even though they are only held in English, although I'm not sure if they have a similar note about this in the translations (probably should).

2021-12-22 08:07 UTC, DoryanR commented on wiki/News_Styling_Criteria/fr.md
> +Les chaînes de titre d'article pour les noms de fichier sont le titre de l'article lui-même avec tous les espaces remplacés par des traits d'union (`-`), et tous les caractères supplémentaires tels q
```suggestion
Les noms des fichier sont le titre de l'article lui-même avec tous les espaces remplacés par des traits d'union (`-`), et tous les caractères supplémentaires tels que les points (`.`), les points d'exclamation (`!`), les points d'interrogation (`?`), les virgules (`,`), les apostrophes (`'`), les guillemets (`"`), moins que (`<`), plus que (`>`), les deux-points (`:`), les barres obliques (`/`), les barres obliques (`\`), les barres verticales (`|`) et les astérisques (`*`) sont retirés.
```

2021-12-22 08:21 UTC, Biokax commented on wiki/News_Styling_Criteria/fr.md
> +Les noms des fichier sont le titre de l'article lui-même avec tous les espaces remplacés par des traits d'union (`-`), et tous les caractères supplémentaires tels que les points (`.`), les points d'e
```suggestion
Les noms des fichiers sont le titre de l'article lui-même avec tous les espaces remplacés par des traits d'union (`-`), et tous les caractères supplémentaires tels que les points (`.`), les points d'exclamation (`!`), les points d'interrogation (`?`), les virgules (`,`), les apostrophes (`'`), les guillemets (`"`), moins que (`<`), plus que (`>`), les deux-points (`:`), les barres obliques (`/`), les barres obliques (`\`), les barres verticales (`|`) et les astérisques (`*`) sont retirés.
```

2021-12-24 22:49 UTC, Satsukel approved these changes

2021-12-27 01:52 UTC, Walavouchey approved these changes

2021-12-27 01:53 UTC, merged