[FR] Update `Game_mode\osu!`
ppy/osu-wiki pull request #6544
Opened 2021-12-13 18:58 UTC by DoryanR

Proposal to update the French translation of the wiki page `Game_mode\osu!`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-13 19:00 UTC, DoryanR commented on wiki/Game_mode/osu!/fr.md
```suggestion
```

2021-12-13 19:00 UTC, DoryanR commented on wiki/Game_mode/osu!/fr.md
> +- Lorsqu'il est joué par [Auto] (/wiki/Game_modifier/Auto), le nom du joueur sera osu!
```suggestion
- Lorsqu'il est joué par [Auto](/wiki/Game_modifier/Auto), le nom du joueur sera osu!
```

2021-12-22 13:12 UTC, Biokax requested changes
Il y a pas mal de traduction littérales venant de l'anglais qui ne collent pas en français. D'autres reviews vont être nécessaires

2021-12-22 13:12 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +**Les éléments suivants réservent la vie dans la barre de vie :**
```suggestion
**Les éléments suivants ne diminuent pas la vie dans la barre de vie :**
```

2021-12-22 13:18 UTC, Biokax requested changes

2021-12-22 13:18 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +Il faut d'abord taper dessus au bon moment, mais cela ne s'arrête pas là. Une balle va commencer à se déplacer sur le chemin. Maintenez le bouton de la souris/du clavier (ou maintenez le stylo sur la
```suggestion
Il faut d'abord taper dessus au bon moment, mais cela ne s'arrête pas là. Une balle va commencer à se déplacer sur la trajectoire. Maintenez le bouton de la souris/du clavier (ou maintenez le stylo sur la tablette) et suivez la balle à l'intérieur du cercle orange épais qui l'entoure, au fur et à mesure de son déplacement. Le cercle extérieur orange, appelé follow circle, apparaîtra si vous tenez la slider ball, mais disparaîtra lorsque vous la relâcherez.
```

2021-12-22 13:18 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +Parfois, comme dans la capture d'écran ci-dessus, la balle peut inverser sa direction et le joueur doit la suivre jusqu'au début du chemin ou vice versa. Le repère visuel est une flèche située sur le
```suggestion
Parfois, comme dans la capture d'écran ci-dessus, la balle peut inverser sa direction et le joueur doit la suivre jusqu'au début de la trajectoire ou vice versa. Le repère visuel est une flèche située sur le cercle de départ ou d'arrivée de la trajectoire.
```

2021-12-29 13:33 UTC, Biokax requested changes

2021-12-29 13:33 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +Il faut d'abord taper dessus au bon moment, mais cela ne s'arrête pas là. Une balle va commencer à se déplacer sur la trajectoire. Maintenez le bouton de la souris/du clavier (ou maintenez le stylo s
```suggestion
Il faut d'abord appuyer dessus au bon moment, mais cela ne s'arrête pas là. Une balle va commencer à se déplacer sur la trajectoire. Maintenez le bouton de la souris/du clavier (ou maintenez le stylo sur la tablette) et suivez la balle à l'intérieur du cercle orange épais qui l'entoure, au fur et à mesure de son déplacement. Le cercle extérieur orange, appelé follow circle, apparaîtra si vous tenez la slider ball, mais disparaîtra lorsque vous la relâcherez.
```

2021-12-29 13:33 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +Maintenez le bouton de la souris/du clavier (ou le stylo sur la tablette). À partir de là, utilisez la souris (ou le stylo) et faites tourner le spinner dans un mouvement circulaire (dans un sens ou
```suggestion
Maintenez le bouton de la souris/du clavier (ou le stylet sur la tablette). À partir de là, utilisez la souris (ou le stylet) et faites tourner le spinner dans un mouvement circulaire (dans un sens ou dans l'autre) jusqu'à ce que le cercle du spinner s'élargisse complètement. Un avis *Clear* apparaîtra pour indiquer que le spinner est terminé. Si le spinner a été terminé prématurément, continuez à tourner pour obtenir un bonus de score et regagner un peu de vie.
```

2021-12-29 13:33 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +| Mouse | Keyboard | Tablet/Touchscreen |
```suggestion
| Souris | Clavier | Tablette/Écran tactile|
```
j'ai pas compris pourquoi c'est repassé en anglais

2021-12-29 13:33 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +## Notation
```suggestion
## Calcul du score
```
pourquoi avoir changé ?

2021-12-29 13:33 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +  - [Combo fire](/wiki/Glossary/Combo_fire) lorsque vous atteignez de nouvelles étapes de combo.
```suggestion
  - [Combo fire](/wiki/Glossary/Combo_fire) lorsque vous atteignez un nouveau palier de combo.
```

2021-12-29 13:33 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +      - Le timer est le cercle extérieur du spinner qui change de couleur. Le spinner s'arrête lorsque le cercle du spinner a complètement changer de couleur.
```suggestion
      - Le timer est le cercle extérieur du spinner qui change de couleur. Le spinner s'arrête lorsque le cercle du spinner a complètement changé de couleur.
```

2021-12-29 13:33 UTC, Biokax commented on wiki/Game_mode/osu!/fr.md
> +  - [Kenji Ninuma - DISCO PRINCE (peppy)](https://osu.ppy.sh/beatmapsets/1), ou `discoprince` ; qui a été apparemment mapper en une heure environ.
```suggestion
  - [Kenji Ninuma - DISCO PRINCE (peppy)](https://osu.ppy.sh/beatmapsets/1), ou `discoprince` ; qui a été apparemment mappé en environ une heure.
```

2021-12-29 14:53 UTC, DoryanR commented on wiki/Game_mode/osu!/fr.md
> +| Souris | Clavier | Tablette/Écran tactile|
```suggestion
| Souris | Clavier | Tablette/Écran tactile |
```

2022-01-05 04:41 UTC, Walavouchey commented on wiki/Game_mode/osu!/fr.md
>    - [Ni-Ni - 1,2,3,4, 007 \[Wipeout Series\] (MCXD)](https://osu.ppy.sh/beatmapsets/3) , ou `Ni-Ni - 1,2,3,4, 007 [Wipeout Series]`.
```suggestion
  - [Ni-Ni - 1,2,3,4, 007 \[Wipeout Series\] (MCXD)](https://osu.ppy.sh/beatmapsets/3), ou `Ni-Ni - 1,2,3,4, 007 [Wipeout Series]`.
```

2022-01-05 09:41 UTC, Ganondorf-1 requested changes

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Les cercles sont visibles sur l'écran inférieur, et l'histoire sur l'écran supérieur. Chaque étape est en fait une histoire indépendante sur une personne en difficulté. C'est là que le *Ouendan* (Équ
```suggestion
Les cercles sont visibles sur l'écran inférieur, et l'histoire sur l'écran supérieur. Chaque étape est en fait une histoire indépendante sur une personne en difficulté. C'est là que le *Ouendan* (Cheer Squad) entre en jeu. Grâce au pouvoir magique du cheerleading masculin, le joueur doit aider les personnes en difficulté.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- La possibilité de faire tourner la souris (ou le stylo pour les tablettes) sur les spinners.
```suggestion
- La possibilité de faire tourner la souris (ou le stylet pour les tablettes) sur les spinners.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Le timing des frappes sur l'objet apparu à l'écran.
```suggestion
- Le timing des clics sur les objets qui apparaissent à l'écran.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Ce sont quelques-unes des compétences essentielles pour devenir un *champion du rythme d'osu!*.
```suggestion
Ce sont quelques-unes des compétences essentielles pour devenir un *osu! rhythm champion*.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +La première étape pour commencer le voyage est d'apprendre les bases (et les théories) des objets pouvant être frappés (appelés *objets* à partir de maintenant).
```suggestion
La première étape pour commencer le voyage est d'apprendre les bases (et les théories) des objets que vous pouvez jouer (appelés *objets* à partir de maintenant).
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +#### Terrain de jeu
```suggestion
#### Playfield
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +La barre en haut à gauche est la barre de vie, qui diminue à un rythme régulier (selon les paramètres de difficulté de la beatmap), mais qui peut être reconstituée en tapant des notes au bon moment o
```suggestion
La barre en haut à gauche est la barre de vie, qui diminue à un rythme régulier (selon les paramètres de difficulté de la beatmap), mais qui peut être remplie en cliquant sur des notes au bon moment ou en faisant tourner les spinners. Un clic parfaitement synchronisé (un 300 ou un Geki) vous permettra de récupérer plus de vie qu'un clic mal synchronisé (50). Un objet manqué diminuera beaucoup la barre de vie.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Un cercle d'approche de couleur similaire, situé à l'extérieur du cercle, se rétrécit avec le temps. Tapez sur la note au moment exact où elle touche le bord blanc du cercle. Un burst de score appara
```suggestion
Un cercle d'approche de couleur similaire, situé à l'extérieur du cercle, se rétrécit avec le temps. Tapez sur la note au moment exact où elle touche le bord blanc du cercle. Un burst de score apparaîtra après avoir touché le cercle, montrant le score et les changements de vie en fonction du timing du clic par rapport au rythme. Le cercle disparaît après le burst du score.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Il faut d'abord appuyer dessus au bon moment, mais cela ne s'arrête pas là. Une balle va commencer à se déplacer sur la trajectoire. Maintenez le bouton de la souris/du clavier (ou maintenez le stylo
```suggestion
Il faut d'abord appuyer dessus au bon moment, mais cela ne s'arrête pas là. Une balle va commencer à se déplacer sur la trajectoire. Maintenez le bouton de la souris/du clavier (ou maintenez le stylet sur la tablette) et suivez la balle à l'intérieur du cercle orange épais qui l'entoure, au fur et à mesure de son déplacement. Le cercle extérieur orange, appelé follow circle, apparaîtra si vous tenez la slider ball, mais disparaîtra si vous la relâchez.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Maintenez le bouton de la souris/du clavier (ou le stylet sur la tablette). À partir de là, utilisez la souris (ou le stylet) et faites tourner le spinner dans un mouvement circulaire (dans un sens o
```suggestion
Maintenez le bouton de la souris/du clavier (ou le stylet sur la tablette). À partir de là, utilisez la souris (ou le stylet) et faites tourner le spinner dans un mouvement circulaire (dans un sens ou dans l'autre) jusqu'à ce que le cercle du spinner s'élargisse complètement. Un avis *Clear* apparaîtra pour indiquer que le spinner est terminé. Si le spinner a été terminé prématurément, continuez à tourner pour obtenir des bonus de score et regagner un peu plus de vie.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +La petite case située sous le spinner indique le nombre de tours par minute. Le chiffre à l'intérieur de cette case correspond au nombre de rotations possibles, si l'on continue à faire tourner le sp
```suggestion
La petite case située sous le spinner indique le nombre de tours par minute. Le chiffre à l'intérieur de cette case correspond au nombre de rotations possibles, si l'on continue à faire tourner le spinner à cette vitesse pendant une minute. Si le bouton de la souris ou du clavier a été relâché (ou si le stylet ne touche pas la tablette) au début de la rotation, le compteur s'arrête de lire la rotation.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +*Reportez-vous à la page [Play Styles sous osu!](/wiki/Play_style).*
```suggestion
*Voir la page [Style de jeu](/wiki/Play_style).*
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Les objets dans osu! acceptent n'importe quelle entrée du périphérique d'entrée, à condition que chaque objet ait été tapé à temps.
```suggestion
Les objets d'osu! acceptent n'importe quelle entrée du périphérique d'entrée, à condition que chaque objet ait été joué à temps.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Si le modificateur de jeu [Relax](/wiki/Game_modifier/Relax) a été utilisé, seul le curseur du jeu fonctionnera. Utilisez le curseur du jeu pour suivre les objets avec un tapotement automatique. Les
```suggestion
Si le modificateur de jeu [Relax](/wiki/Game_modifier/Relax) été utilisé, seul le curseur du jeu fonctionnera. Utilisez le curseur du jeu pour suivre les objets avec des clics automatiques. Les spinners doivent toujours être terminés.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Si le modificateur de jeu [Auto Pilot](/wiki/Game_modifier/Autopilot) a été utilisé, seule l'entrée du périphérique d'entrée fonctionnera. Ce dernier va frapper sur les objets avec un mouvement autom
```suggestion
Si le modificateur de jeu [Auto Pilot](/wiki/Game_modifier/Autopilot) été utilisé, seule l'entrée du périphérique d'entrée fonctionnera. Ce mod placera automatiquement le curseur sur les objets, le joueur doit quant à lui cliquer au bon moment. Les spinners suivront la vitesse du mod [Spun Out](/wiki/Game_modifier/Spun_Out).
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Le [jugement](/wiki/Gameplay/Judgement/osu!) détermine la valeur de base du score d'un objet (300, 100, 50 ou 0 en cas de miss). Pour les [cercles](/wiki/Hit_object/Hit_circle), les pressions de to
```suggestion
- Le [jugement](/wiki/Gameplay/Judgement/osu!) détermine la valeur de base du score d'un objet (300, 100, 50 ou 0 en cas de miss). Pour les [cercles](/wiki/Hit_object/Hit_circle), les pressions de touches bien synchronisées sont plus valorisées, à la fois en termes de score et de précision. Les [sliders](/wiki/Hit_object/Slider) et les [spinners](/wiki/Hit_object/Spinner) n'ont pas de hit windows mais ils briseront le combo s'ils sont miss ou mal clear. Obtenir un jugement plus élevé permet également de regagner de la [vie](/wiki/Beatmapping/Health).
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- La [précision](/wiki/Gameplay/Accuracy#osu!) dépend du jugement et montre la précision des coups. Les coups trop tôt ou trop tard sur les touches, ainsi que les miss, diminuent la précision globale
```suggestion
- La [précision](/wiki/Gameplay/Accuracy#osu!) dépend du jugement et montre la précision des clics. Les clics trop tôt ou trop tard sur les touches, ainsi que les miss, diminuent la précision globale.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) est un multiplicateur de score : clear un objet contribue davantage au score total lorsque le combo est élevé et vice versa. Le combo peut être [
```suggestion
- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) est un multiplicateur de score : jouer un objet contribue davantage au score total lorsque le combo est élevé et vice versa. Le combo peut être [cassé](/wiki/Glossary/Combobreak) par un miss ou un [slider break](/wiki/Gameplay/Slider_break).
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Lorsque le combo est maintenu, le score total augmente de façon exponentielle. Les objets situés plus près de la fin de la beatmap valent des ordres de grandeur plus élevés que ceux du début, ce qui
```suggestion
Lorsque le combo est maintenu, le score total augmente de façon exponentielle. Les objets situés plus près de la fin de la beatmap valent des ordres de grandeur plus élevés que ceux du début, ce qui signifie qu'un joueur perdra beaucoup plus de points potentiels sur eux en cas de clics au mauvais moment. Par conséquent, il est possible et très courant qu'un score avec une précision moindre ait un nombre de points plus élevé et batte un score avec une meilleure précision.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +Après avoir terminé une beatmap, le score se voit attribuer un [grade](/wiki/Gameplay/Grade#osu!), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté indiqu
```suggestion
Après avoir terminé une beatmap, le score se voit attribuer une [note](/wiki/Gameplay/Grade#osu!), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté indique une précision de 100 %, et tout le reste, de S à D, dépend de la quantité de 300, de 50 et de miss.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +*Reportez-vous à la page [Beatmapping](/wiki/Beatmapping) pour de plus amples informations.*
```suggestion
*Consultez la page [Beatmapping](/wiki/Beatmapping) pour de plus amples informations.*
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +![Effet de smoke dans osu!](/wiki/shared/osu_smoke.jpg "Utilisation du smoke")
```suggestion
![Effet de smoke dans osu!](/wiki/shared/osu_smoke.jpg "Utilisation de la smoke")
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- En fonction du niveau de difficulté et de la tolérance de temps, le fait de toucher l'objet *trop tôt* le fera vibrer fortement.
```suggestion
- En fonction du niveau de difficulté et de la tolérance du timing, le fait de toucher l'objet *trop tôt* le fera vibrer fortement.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Le fait de relâcher la sliderball sur une trajectoire vide sans ticks de slider cachés ou visibles n'entraîne pas de rupture de combo ni de score donné. Le jugement du slider vérifie seulement si l
```suggestion
- Le fait de relâcher la slider ball sur une trajectoire vide sans slider ticks cachés ou visibles n'entraîne pas de rupture de combo ni de score donné. Le jugement du slider vérifie seulement si le cercle de départ a été cliqué, si les slider ticks ont été collectés et si le cercle final a été complété avec succès ou non.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Si vous changez le sens de rotation au milieu d'un tour, le spinner ralentira (le nombre de tours par minute passera à 0 pour réinitialiser l'orientation du tour), puis tournera dans le bon sens. L
```suggestion
- Si vous changez le sens de rotation au milieu du spinner, le spinner ralentira (le nombre de tours par minute passera à 0 pour réinitialiser l'orientation), puis tournera dans le bon sens. La progression du spin ne sera pas perdue pendant la réorientation (elle ne changera pas), et continuera à augmenter lors du spin inverse.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- La fumée dure plus longtemps que le tracé du curseur par défaut dans le jeu. Appliquez les effets de fumée de manière éparse pour éviter que les anciens effets de fumée ne disparaissent trop rapide
```suggestion
- La smoke dure plus longtemps que le tracé du curseur par défaut dans le jeu. Appliquez les effets de smoke de manière éparse pour éviter que les anciens effets de smoke ne disparaissent trop rapidement.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Lorsqu'il est joué par [Auto](/wiki/Game_modifier/Auto), le nom du joueur sera osu!
```suggestion
- Lorsque le mod [Auto](/wiki/Game_modifier/Auto) est utilisé, le nom du joueur sera osu!
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Ancienne version d'osu! utilisée pour émuler certains éléments de la série *Ouendan* avant d'être retirée ou remplacée :
```suggestion
- L'ancienne version d'osu! émulait certains éléments de la série *Ouendan* avant d'être retirés ou remplacés :
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +  - [Combo fire](/wiki/Glossary/Combo_fire) lorsque vous atteignez un nouveau palier de combo.
```suggestion
  - Le [Combo fire](/wiki/Glossary/Combo_fire) lorsque vous atteignez un nouveau palier de combo.
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +- Les trois premières beatmaps classées le même jour (07 octobre 2007, 07/10/2007) lors de la mise en ligne du classement sont les suivants :
```suggestion
- Les trois premières beatmaps classées le même jour (07 octobre 2007, 07/10/2007) lors de la mise en ligne du classement sont les suivantes :
```

2022-01-05 09:41 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!/fr.md
> +  - [Kenji Ninuma - DISCO PRINCE (peppy)](https://osu.ppy.sh/beatmapsets/1), ou `discoprince` ; qui a été apparemment mappé en environ une heure.
```suggestion
  - [Kenji Ninuma - DISCO PRINCE (peppy)](https://osu.ppy.sh/beatmapsets/1), ou `discoprince` ; qui a apparemment été mappée en environ une heure.
```

2022-01-05 12:46 UTC, Biokax approved these changes

2022-01-05 12:46 UTC, Walavouchey approved these changes

2022-01-05 12:47 UTC, merged