[FR] Update `Game_mode\osu!catch`
ppy/osu-wiki pull request #6548
Opened 2021-12-14 19:31 UTC by DoryanR

Proposal to update the French translation of the wiki page `Game_mode\osu!catch`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-14 19:34 UTC, DoryanR commented on wiki/Game_mode/osu!catch/fr.md
```suggestion
```

2021-12-14 19:34 UTC, DoryanR commented on wiki/Game_mode/osu!catch/fr.md
> +![Logo d'osu!catch dans les modes spéciaux](/wiki/shared/Ctb_logo.jpg "Logo "Catch the Beat" en mode spécial")
```suggestion
![Logo d'osu!catch dans les modes spéciaux](/wiki/shared/Ctb_logo.jpg "Logo Catch the Beat en mode spécial")
```

2021-12-14 20:16 UTC, DoryanR commented on wiki/Game_mode/osu!catch/fr.md
> +# osu!catch (game mode)
```suggestion
# osu!catch (mode de jeu)
```

2021-12-17 17:29 UTC, DoryanR commented on wiki/Game_mode/osu!catch/fr.md
> +Vous pouvez aussi cliquer sur le bouton `Mode` et sélectionner `osu!le paramètre
```suggestion
Vous pouvez aussi cliquer sur le bouton `Mode` et sélectionner `osu!catch`
```

2021-12-30 05:39 UTC, Ganondorf-1 requested changes

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +### Les bases du jeu
```suggestion
### Les bases du gameplay
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +![Terrain de jeu d'osu!catch montrant la différence entre CS2 et CS7](/wiki/shared/Catch_Playfield_27.jpg "La différence du terrain de jeu d'osu!catch playfield basé sur le CS")
```suggestion
![Playfield d'osu!catch montrant la différence entre CS2 et CS7](/wiki/shared/Catch_Playfield_27.jpg "La différence de playfield d'osu!catch selon le CS")
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
>  #### Terrain de jeu
```suggestion
#### Playfield
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +La taille du zoom du terrain de jeu est basée sur les paramètres CS (Circle Size). Un CS plus faible signifie un zoom avant plus important et un espace plus petit, tandis qu'un CS plus élevé signifie
```suggestion
Le zoom du playfield est basé sur le paramètre CS (Circle Size). Un CS plus faible signifie un zoom avant plus important et un espace plus petit, tandis qu'un CS plus élevé signifie un zoom arrière plus important et un espace de mouvement plus grand.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Le catcher peut se déplacer de gauche à droite, les fruits tombant de haut en bas. Le catcher ne peut pas passer les murs de gauche et de droite du terrain de jeu.
```suggestion
Le catcher peut se déplacer de gauche à droite, les fruits tombant de haut en bas. Le catcher ne peut pas dépasser les murs de gauche et de droite du playfield.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Tous les fruits resteront sur l'assiette jusqu'à la fin de leur combo, après quoi ils rebondiront hors de l'assiette. Le timing et l'endroit où il tombe sur l'assiette n'ont pas d'importance ; un sco
```suggestion
Tous les fruits resteront sur l'assiette jusqu'à la fin de leur combo, après quoi ils rebondiront hors de l'assiette. Le timing et l'endroit où le fruit tombe sur l'assiette n'ont pas d'importance ; attraper le fruit donnera le score maximal tandis que manquer le fruit donnera un miss.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Pour attraper ces fruits, assurez-vous qu'ils tombent sur l'assiette et non en dehors. Les fruits collectés donneront toujours 300 points chacun, incrémenteront le combo de 1, et seront traités comme
```suggestion
Pour attraper ces fruits, assurez-vous qu'ils tombent sur l'assiette. Les fruits collectés donneront toujours 300 points chacun, augmenteront le combo de 1, et seront traités comme des 300 sur l'écran des résultats.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +#### Traînée des fruits
```suggestion
#### Chemin de fruits
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +![Traînée des fruits](/wiki/shared/Catch_trails.jpg "Traînée des fruits d'osu!catch")
```suggestion
![Chemin de fruits](/wiki/shared/Catch_trails.jpg "Chemin de fruits d'osu!catch")
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Une traînée de fruits contient deux fruits (début et fin), des droplets (chemin du slider), un juice drop (ticks du slider), et plus de fruits pour chaque point de la flèche avec un chemin de slider
```suggestion
Un chemin de fruits contient deux fruits (début et fin), des droplets (chemin du slider), des juice drops (slider ticks), et d'autres fruits pour chaque reverse arrow avec un chemin de slider inversé. Les droplets donnent 10 points chacun et sont traités comme des 50 sur l'écran des résultats. Les juice drops donnent 30 points chacun, augmentent le combo de 1, et sont traités comme des 100 sur l'écran des résultats.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Si vous ratez un juice drop, le combo sera annulé (car il s'agit d'un tick de slider), mais si vous ratez le droplet, le combo ne sera pas annulé. Cependant, les droplets manquées n'apparaîtront pas
```suggestion
Si vous manquez un juice drop, le combo sera réinitialisé (car il s'agit d'un slider tick), mais manquer un droplet ne réinitialisera pas le combo. Cependant, les droplets manqués n'apparaîtront pas sur l'écran de résultats local, mais seront affichées dans le classement du site web comme *Miss Droplet*, ce qui affecte notamment la précision (le droplet miss, qui est un 50) et le score (10 points pour chaque droplet manqué).
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Ici, les grosses bananes vont pleuvoir et rétrécir jusqu'à atteindre la taille d'une prise en tombant dans l'assiette (ou pas). Chaque banane collectée donne un score fixe de 1 100, indépendamment du
```suggestion
Ici, de grandes bananes vont pleuvoir et rétrécir jusqu'à ce qu'elles tombent dans l'assiette (ou pas). Chaque banane collectée donne un score fixe de 1100 points, indépendamment du mod et du multiplicateur de combo.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Les bananes peuvent être ignorées sans perte de santé. Cependant, cela peut coûter les points supplémentaires et la récupération de santé de la collecte des bananes. En particulier, le mod [Auto](/wi
```suggestion
Les bananes peuvent être ignorées sans perdre de vie. Cependant, cela peut coûter les points et la récupération de santé bonus que peuvent donner les bananes. En particulier, le mod [Auto](/wiki/Game_modifier/Auto) se surpasse pour attraper *toutes* les bananes sans faute.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Les hyperfruits sont des fruits spéciaux qui apparaissent pour aider le catcher à attraper le fruit suivant lorsque le dash normal est considéré comme impossible à attraper dans un temps imparti stri
```suggestion
Les hyperfruits sont des fruits spéciaux qui apparaissent pour aider le catcher à attraper le fruit suivant lorsque le dash normal ne suffit pas à l'attraper dans un temps imparti strict. Par défaut, tous les hyperfruits ont une couleur rouge caractéristique qui entoure l'hyperfruit lui-même.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +En ramassant l'hyperfruit, le catcher verra sa vitesse passer à *hyperdash* (juste assez rapide pour attraper le prochain fruit), brille en rouge et laisse une *afterimage* rouge temporaire au point
```suggestion
En ramassant l'hyperfruit, le catcher verra sa vitesse passer à *hyperdash* (juste assez rapide pour attraper le prochain fruit), brille en rouge et laisse une *image rémanente* rouge temporaire au point de collecte, jusqu'à ce que le prochain fruit ait été attrapé ou manqué, et le catcher redeviendra alors normal.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Le placement du curseur dans le jeu n'a pas d'importance lorsque vous jouez normalement. Si le mod [Relax](/wiki/Game_modifier/Relax) a été activé, le contrôle du catcher sera le curseur du jeu à la
```suggestion
Le placement du curseur dans le jeu n'a pas d'importance lorsque vous jouez normalement. Si le mod [Relax](/wiki/Game_modifier/Relax) a été activé, le contrôle du catcher sera le curseur du jeu à la place. Cependant, le score ne sera pas ajouté aux classements lorsque le mod Relax est activé (car cela va à l'encontre du seul défi de osu!catch : la vitesse fixe du catcher et le contrôle du plateau du catcher).
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Le [score dans osu!catch](/wiki/Gameplay/Score/osu!catch) est une somme pondérée de plusieurs composantes de la jouabilité. Il dépend des éléments suivants :
```suggestion
Le [score dans osu!catch](/wiki/Gameplay/Score/osu!catch) est une somme pondérée de plusieurs composantes du gameplay. Il dépend des éléments suivants :
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) est un multiplicateur de score : clear un objet contribue davantage au score total lorsque le combo est élevé et vice versa. Dans osu!catch, le c
```suggestion
- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) est un multiplicateur de score : attraper un objet contribue davantage au score total lorsque le combo est élevé et vice versa. Dans osu!catch, le combo peut être [cassé](/wiki/Glossary/Combobreak) en réalisant un miss sur un large fruit ou un drop, ce qui diminue également la [vie](/wiki/Beatmapping/Health).
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- La [précision](/wiki/Gameplay/Accuracy#osu!catch) indique combien d'objets ont été attrapés au total. Les petits droplets diminuent la précision lorsqu'elles sont miss, mais ne cassent pas le combo
```suggestion
- La [précision](/wiki/Gameplay/Accuracy#osu!catch) indique combien d'objets ont été attrapés au total. Les petits droplets diminuent la précision s'ils ne sont pas attrapés, mais ne cassent pas le combo.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +Après avoir terminé une beatmap, le score se voit attribuer un [grade](/wiki/Gameplay/Grade#osu!catch), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté i
```suggestion
Après avoir terminé une beatmap, le score se voit attribuer une [note](/wiki/Gameplay/Grade#osu!catch), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté indique une précision de 100 %, et tout le reste, de S à D, dépend de la quantité d'objets manqués.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- Le placement sur l'axe horizontal détermine le point de chute des fruits (cercle) ou des traînées des fruits (slider).
```suggestion
- Le placement sur l'axe horizontal détermine le point de chute des fruits (cercle) ou des chemins de fruits (slider).
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- L'apparence est basée sur le timing défini pour le clear, comme d'habitude.
```suggestion
- L'apparence est basée sur le timing défini pour jouer, comme d'habitude.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- La vitesse de la traînée de fruits est similaire à celle du sliderball.
```suggestion
- La vitesse du chemin de fruits est similaire à celle de la sliderball.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- Les spinners crée une pluie de bananes.
```suggestion
- Les spinners créent une pluie de bananes.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +**Note :** Les hyperfruits sont générés automatiquement.
```suggestion
**Remarque :** Les hyperfruits sont générés automatiquement.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- Le catcher peut être déplacé pendant n'importe quelle pause.
```suggestion
- Le catcher peut être déplacé pendant les breaks.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- Lorsqu'il est joué par [Auto](/wiki/Game_modifier/Auto), le nom du joueur sera *salad!*.
```suggestion
- Lorsque le mod [Auto](/wiki/Game_modifier/Auto) est activé, le nom du joueur sera *salad!*.
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- La première beatmap classée qui contient au moins une difficulté osu!catch est [Yousei Teikoku - Dare so Ka no Gekka (TV Size) (NatsumeRin), avec la difficulté osu!catch guest mappée par Uran](http
```suggestion
- La première beatmap classée qui contient au moins une difficulté osu!catch est [Yousei Teikoku - Dare so Ka no Gekka (TV Size) (NatsumeRin), avec la guest difficulty osu!catch mappée par Uran](https://osu.ppy.sh/beatmapsets/13676).
```

2021-12-30 05:39 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!catch/fr.md
> +- Le premier ranked d'une beatmap osu!catch est [Rita - Hajimari no Toki (Deif)](https://osu.ppy.sh/beatmapsets/91485).
```suggestion
- La première beatmap classée d'osu!catch est [Rita - Hajimari no Toki (Deif)](https://osu.ppy.sh/beatmapsets/91485).
```

2022-01-03 16:15 UTC, Biokax requested changes

2022-01-03 16:15 UTC, Biokax commented on wiki/Game_mode/osu!catch/fr.md
> +Tous les fruits resteront sur l'assiette jusqu'à la fin de leur combo, après quoi ils rebondiront hors de l'assiette. Le timing et l'endroit où le fruit tombe sur l'assiette n'ont pas d'importance ;
```suggestion
Tous les fruits resteront sur l'assiette jusqu'à la fin de leur combo, après quoi ils rebondiront hors de l'assiette. Le timing ainsi que l'endroit où le fruit tombe sur l'assiette n'ont pas d'importance ; attraper le fruit donnera le score maximal tandis que manquer le fruit donnera un miss.
```

2022-01-03 16:15 UTC, Biokax commented on wiki/Game_mode/osu!catch/fr.md
> +Le placement du curseur dans le jeu n'a pas d'importance lorsque vous jouez normalement. Si le mod [Relax](/wiki/Game_modifier/Relax) a été activé, le contrôle du catcher sera le curseur du jeu à la
```suggestion
Le placement du curseur dans le jeu n'a pas d'importance lorsque vous jouez normalement. Si le mod [Relax](/wiki/Game_modifier/Relax) a été activé, le contrôle du catcher sera le curseur du jeu à la place. Cependant, le score ne sera pas ajouté aux classements lorsque le mod Relax est activé (car cela va à l'encontre du seul défi d'osu!catch : la vitesse fixe du catcher et le contrôle du plateau du catcher).
```

2022-01-03 18:45 UTC, Biokax approved these changes

2022-01-04 07:55 UTC, Walavouchey approved these changes

2022-01-04 07:55 UTC, merged