[FR] Update `Game_mode\osu!mania`
ppy/osu-wiki pull request #6550
Opened 2021-12-14 20:13 UTC by DoryanR

Proposal to update the French translation of the wiki page `Game_mode\osu!mania`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-14 20:17 UTC, DoryanR commented on wiki/Game_mode/osu!mania/fr.md
>  # osu!mania
```suggestion
# osu!mania (mode de jeu)
```

2021-12-31 11:12 UTC, Ganondorf-1 requested changes

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
>  Les notes sont les cercles d'osu!mania. La note tombante doit être frappée sur la ligne de jugement, avec la touche correspondant à la bonne note. Plusieurs touches correspondant aux notes tombantes
```suggestion
Les notes sont les cercles d'osu!mania. La note tombante doit être appuyée sur la ligne de jugement, avec la touche correspondant à la bonne note. Plusieurs touches correspondant aux notes tombantes doivent être appuyées simultanément si les notes tombent simultanément.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Une explosion du score se fera quand une touche a été frappée au bon moment sur la ligne de jugement.
```suggestion
Une explosion du score se fera quand une touche a été appuyée au bon moment sur la ligne de jugement.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Les hold notes sont les sliders et les spinners d'osu!mania. Quand une hold note atteint la ligne de jugement, frappez la note qui démarre avec la touche correcte, tenez-la, et relâchez-la à la fin d
```suggestion
Les hold notes sont les sliders et les spinners d'osu!mania. Quand une hold note atteint la ligne de jugement, appuyez sur la note qui démarre avec la touche correcte, tenez-la, et relâchez-la à la fin de la hold note.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- le style *de Gauche à Droite* imite le placement des boutons de *Beatmania IIDX*, où la première colonne correspond à *key1*, puis la seconde colonne à la *key2* et ainsi de suite.
```suggestion
- le style *de Gauche à Droite* imite le placement des boutons de *Beatmania IIDX*, où la première colonne correspond à *key1*, puis la seconde colonne à *key2* et ainsi de suite.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +  - Cependant, l'option pour le sélectionner a été supprimée et le style actuel est basé sur le style "Symétrique". Pour des raisons légales, le style "de Droite à Gauche" est gardé ici.
```suggestion
  - Cependant, l'option pour le sélectionner a été supprimée et le style actuel est basé sur le style "Symétrique". Le style "de Droite à Gauche" est gardé ici.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +## Notation
```suggestion
## Scoring
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +1. Le score de base, qui est centré sur le [jugement](/wiki/Gameplay/Judgement/osu!mania). Le jugement détermine la valeur du score de base d'un objet (MAX, 300, 200, 100, 50, ou 0 en cas d'échec).
```suggestion
1. Le score de base, qui est centré sur le [jugement](/wiki/Gameplay/Judgement/osu!mania). Le jugement détermine la valeur du score de base d'un objet (MAX, 300, 200, 100, 50, ou 0 en cas de note manquée).
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +2. Le score de bonus, qui est basé sur le jugement et un multiplicateur de bonus flottant, qui augmente lorsqu'on obtient un MAX ou un 300, et diminue avec un 200 ou moins.
```suggestion
2. Le score bonus, qui est basé sur le jugement et un multiplicateur de bonus flottant, qui augmente lorsqu'on obtient un MAX ou un 300, et diminue avec un 200 ou moins.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- La [précision](/wiki/Gameplay/Accuracy#osu!mania) dépend du jugement et montre la précision des coups. Les appuis trop tôt ou trop tard sur les touches, ainsi que les miss, diminuent la précision g
```suggestion
- La [précision](/wiki/Gameplay/Accuracy#osu!mania) dépend du jugement et montre la précision avec laquelle le joueur a appuyé sur les touches. Appuyer trop tôt ou trop tard, ainsi que manquer les notes, diminuent la précision globale.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +Après avoir terminé une beatmap, le score se voit attribuer un [grade](/wiki/Gameplay/Grade#osu!mania), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté i
```suggestion
Après avoir terminé une beatmap, le score se voit attribuer une [note](/wiki/Gameplay/Grade#osu!mania), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté indique une précision de 100 %.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +*Référez-vous à la page de [Skinning d'osu!mania](/wiki/Skinning/osu!mania). pour des informations complètes*
```suggestion
*Référez-vous à la page [Skinning d'osu!mania](/wiki/Skinning/osu!mania). pour des informations complètes*
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- La mascotte d'osu!mania est [Mani & Mari](/wiki/Mascots#-mani-&-mari).
```suggestion
- Les mascottes d'osu!mania sont [Mani & Mari](/wiki/Mascots#-mani-&-mari).
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
>  - Lors de l'utilisation d'[Auto](/wiki/Game_modifier/Auto), le nom du joueur sera *osu!topus*.
```suggestion
- Lorsque le mod [Auto](/wiki/Game_modifier/Auto) est utilisé, le nom du joueur sera *osu!topus*.
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
> +- osu!mania est sorti le [8 October 2012 (08/10/2012), principalement implémenté par woc2006](https://osu.ppy.sh/community/forums/posts/1825880).
```suggestion
- osu!mania est sorti le [8 octobre 2012 (08/10/2012), principalement implémenté par woc2006](https://osu.ppy.sh/community/forums/posts/1825880).
```

2021-12-31 11:12 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!mania/fr.md
>  - L'ancien éditeur d'osu!mania *demandait* au mappeur de placer des cercles et des sliders dans un terrain de jeu d'osu!, où la scène sera retranscrite en notes propres basées sur la position des cer
```suggestion
- L'ancien éditeur d'osu!mania *demandait* au mappeur de placer des cercles et des sliders dans un playfield du mode osu!, où la scène sera retranscrite en notes propres basées sur la position des cercles et autres hit objects utilisés.
```

2022-01-03 16:36 UTC, Biokax requested changes

2022-01-03 16:36 UTC, Biokax commented on wiki/Game_mode/osu!mania/fr.md
> +![Configuration des touches par défaut dans osu!mania (Options-> Contrôles)](/wiki/shared/Mania_key_layouts.jpg "osu!mania key layout")
```suggestion
![Configuration des touches par défaut dans osu!mania (Options-> Contrôles)](/wiki/shared/Mania_key_layouts.jpg "Disposition des touches d'osu!mania")
```

2022-01-03 16:36 UTC, Biokax commented on wiki/Game_mode/osu!mania/fr.md
> +![Configuration des touches par défaut dans osu!mania (Co-Op)](/wiki/shared/Mania_key_layouts2.jpg "osu!mania key layout (Co-Op)")
```suggestion
![Configuration des touches par défaut dans osu!mania (Co-Op)](/wiki/shared/Mania_key_layouts2.jpg "Disposition des touches d'osu!mania (Co-Op)")
```

2022-01-03 18:45 UTC, Biokax approved these changes

2022-01-04 07:58 UTC, Walavouchey approved these changes

2022-01-04 07:58 UTC, merged