[FR] Update `Game_mode\osu!taiko`
ppy/osu-wiki pull request #6561
Opened 2021-12-17 17:21 UTC by DoryanR

Proposal to update the French translation of the wiki page `Game_mode\osu!taiko`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-29 12:41 UTC, Biokax requested changes

2021-12-29 12:41 UTC, Biokax commented on wiki/Game_mode/osu!taiko/fr.md
> +Les drumroll peuvent être ignorés sans pénalité de vie, car ils ne récupèrent pas du tout la barre de vie. Cependant, cela coûtera les éventuels points gagnés grâce au drumroll. Chaque coup réussi su
```suggestion
Les drumroll peuvent être ignorés sans pénalité de vie, car ils ne permettent pas de faire remonter la barre de vie. Cependant, cela coûtera les éventuels points gagnés grâce au drumroll. Chaque coup réussi sur le petit cercledonne un score statique de 300.
```

2022-01-03 08:57 UTC, Ganondorf-1 requested changes

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +### Les bases du jeu
```suggestion
### Les bases du gameplay
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
>  #### Terrain de jeu
```suggestion
#### Playfield
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +![Terrain de jeu d'osu!taiko](/wiki/shared/Taiko_playfield.jpg "Terrain de jeu d'osu!taiko")
```suggestion
![Playfield d'osu!taiko](/wiki/shared/Taiko_playfield.jpg "Playfield d'osu!taiko")
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- *Kiai Time* déclenche le *"Go-Go Time"*.
```suggestion
- Le *Kiai Time* déclenche le *"Go-Go Time"*.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +  - Les astuces de gameplay comme les ballons ou les chemins bifurqués ne sont pas implémentées (seulement les bases du jeu).
```suggestion
  - Certains éléments de gameplay comme les ballons ou les chemins bifurqués ne sont pas implémentés (seules les bases sont présentes).
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +  - Les beatmaps spécifique à osu!taiko a généralement son propre fond personnalisé, laissant la section supérieure vide.
```suggestion
  - Les beatmaps spécifiques à osu!taiko ont généralement leur propre fond personnalisé, laissant la section supérieure vide.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Pour les nouveaux venus dans le mode osu!taiko, l'écran est divisé en deux sections différentes : la section supérieure contient les éléments de jeu tandis que la section inférieure contient une imag
```suggestion
Pour les nouveaux venus dans le mode osu!taiko, l'écran est divisé en deux sections différentes : la section supérieure contient les éléments de jeu tandis que la section inférieure contient une image ou une vidéo pour la beatmap. Dans la partie supérieure, on trouve la barre de vie qui, contrairement aux autres modes de jeu, commence vide et doit être remplie au moins à moitié pour réussir la beatmap. Dans la partie supérieure centrale, sous la barre de vie, se trouve un tambour taiko sur le côté gauche et un tapis roulant qui transporte les objets de droite à gauche en passant par un double cercle blanc qui sert de cercle de jugement près du tambour taiko. Au-dessus du tambour taiko se trouve la mascotte taiko animée, qui réagit en fonction du jugement reçu et change la couleur du fond supérieur. Enfin, il y a le score habituel, la précision et le timer de la beatmap en haut à droite.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Veuillez noter que le drain de santé est désactivé dans osu!taiko, donc seuls les objets affecteront la barre de santé. Les combos ne sont pas interrompus lorsque vous jouez sur un terrain vide. Cont
```suggestion
Veuillez noter que le drain de santé est désactivé dans osu!taiko, donc seuls les objets affecteront la barre de santé. Le combo ne sera pas cassé si vous appuyez dans le vide. Contrairement à osu!, les combos sont célébrés tous les 50 coups consécutifs. Le score de base sera boosté après avoir obtenu un combo qui est un multiple de 10, mais s'arrête à 100 (limite maximale de combo pour le boost). Si le combo est cassé, le boost revient au score de base. Pendant le *Kiai Time*, chaque coup réussi donne au joueur 20% de points supplémentaires par rapport au score actuel. Le score obtenu lors d'un coup peut être vérifié sous la précision dans le coin supérieur droit en rouge.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Frappez le tambour intérieur (ou extérieur) de façon continue pour obtenir des points jusqu'à la fin du drumroll. Pour une note **LARGE**, frappez les deux boutons du tambour intérieur (ou extérieur)
```suggestion
Frappez le tambour intérieur (ou extérieur) de façon continue pour obtenir des points jusqu'à la fin du drumroll. Pour une note **LARGE**, frappez les deux boutons du tambour intérieur (ou extérieur) simultanément et sans interruption jusqu'à la fin. Notez que les coups du drumroll sont plafonnés et ne sont comptés que lorsqu'ils sont frappés sur les petits cercles, plutôt que de jouer le drumroll aussi vite que possible comme dans *Taiko no Tatsujin*.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Les drumroll peuvent être ignorés sans pénalité de vie, car ils ne permettent pas de faire remonter la barre de vie. Cependant, cela coûtera les éventuels points gagnés grâce au drumroll. Chaque coup
```suggestion
Les drumrolls peuvent être ignorés sans pénalité de vie, car ils ne permettent pas de faire remonter la barre de vie. Cependant, cela coûtera les éventuels points gagnés grâce au drumroll. Chaque coup réussi sur le petit cercle donne un score statique de 300.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Frappez le tambour intérieur et extérieur **dans l'ordre** (comme rouge, bleu, rouge, bleu, rouge, bleu, ...) jusqu'à ce que le compteur denden atteigne 0. La couleur de départ n'a pas d'importance (
```suggestion
Frappez le tambour intérieur et extérieur **dans l'ordre** (comme rouge, bleu, rouge, bleu, rouge, bleu, ...) jusqu'à ce que le compteur denden atteigne 0. La couleur de départ n'a pas d'importance (vous pouvez commencer par le bleu si vous le souhaitez), et ne pas le terminer entraînera une pénalité de vie mais pas de réinitialisation du combo. Frapper la même couleur ne décrémentera pas le compteur denden, jusqu'à ce qu'une couleur différente soit frappée à la place.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Il n'incrémente pas le compteur de combo, et ne récupère pas la barre de vie de quelque manière que ce soit. Chaque coup denden réussi ne donne qu'un score statique de 300, et l'achèvement du denden
```suggestion
Il n'incrémente pas le compteur de combo, et ne redonne pas de vie de quelque manière que ce soit. Chaque coup denden réussi ne donne qu'un score statique de 300, et terminer le denden donnera un score parfait (GREAT).
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +*Reportez-vous à la page [Styles de jeu sous osu!taiko](/wiki/Play_style).*
```suggestion
*Voir [Styles de jeu sous osu!taiko](/wiki/Play_style).*
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +| Type | Souris | clavier | TaTaCon |
```suggestion
| Type | Souris | Clavier | TaTaCon |
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +| Rouge | Click gauche (L) | `X`(L) / `C`(R) | Surface plane du tambour |
```suggestion
| Rouge | Clic gauche (L) | `X`(L) / `C`(R) | Surface plane du tambour |
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +| Bleu | Click droit (L) | `Z`(L) / `V`(R) | Surface extérieure du tambour |
```suggestion
| Bleu | Clic droit (L) | `Z`(L) / `V`(R) | Surface extérieure du tambour |
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Le placement du curseur dans le jeu n'a pas d'importance lors du jeu.
```suggestion
La position du curseur n'a pas d'importance dans ce mode de jeu.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Si le mod [Relax](/wiki/Game_modifier/Relax) a été utilisé, le jugement du score ne tient compte que du timing des coups (il rectifie automatiquement les coups de mauvaise couleur avec la bonne coule
```suggestion
Si le mod [Relax](/wiki/Game_modifier/Relax) été utilisé, le jugement du score ne tient compte que du timing des coups (il rectifie automatiquement les coups de mauvaise couleur avec la bonne couleur).
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +## Notation
```suggestion
## Scoring
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- Le [jugement](/wiki/Gameplay/Judgement/osu!taiko) détermine la valeur de base du score d'un objet (300, 100, ou 0 en cas de miss). La valeur des notes large et regular dépend du timing du coup, tan
```suggestion
- Le [jugement](/wiki/Gameplay/Judgement/osu!taiko) détermine la valeur de base du score d'un objet (300, 100, ou 0 en cas de miss). La valeur des notes normales et des grandes notes dépend du timing du coup, tandis que la valeur de base de tous les autres objets est constante.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- La [précision](/wiki/Gameplay/Accuracy#osu!taiko) dépend du jugement et montre la précision des coups. Les pressions de touche trop tôt ou trop tard, ainsi que les miss, diminuent la précision glob
```suggestion
- La [précision](/wiki/Gameplay/Accuracy#osu!taiko) dépend du jugement et montre la précision des coups. Les pressions de touche trop tôt ou trop tard, ainsi que les notes normales, diminuent la précision globale.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) est un multiplicateur de score : clear un objet touché contribue davantage au score total lorsque le combo est élevé et vice versa. Le combo peut
```suggestion
- Le [combo](/wiki/Gameplay/Combo_(score_multiplier)) est un multiplicateur de score : jouer un objet contribue davantage au score total lorsque le combo est élevé et vice versa. Le combo peut être [cassé](/wiki/Glossary/Combobreak) par un miss. Dans osu!taiko, le multiplicateur de score dérivé du combo est limité et n'affecte pas le score total autant qu'il le fait dans osu! ou osu!catch.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +En plus de donner des points, chaque objet remplit une petite partie de la [barre de vie](/wiki/Glossary/Health_bar), qui doit être remplie au moins à **50%** pour qu'un joueur puisse clear une beatm
```suggestion
En plus de donner des points, chaque objet remplit une petite partie de la [barre de vie](/wiki/Glossary/Health_bar), qui doit être remplie au moins à **50%** pour qu'un joueur puisse terminer une beatmap.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +Après avoir complété une beatmap, le score se voit attribuer un [grade](/wiki/Gameplay/Grade#osu!taiko), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté
```suggestion
Après avoir complété une beatmap, le score se voit attribuer une [note](/wiki/Gameplay/Grade#osu!taiko), une courte évaluation de la précision sous la forme d'une seule lettre. Un SS doré ou argenté indique une précision de 100 %, et tout le reste, de S à D, dépend de la quantité de 300, 100 et de notes manquées.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +  - Les grandes notes rouges ont besoin d'une finition sonore.
```suggestion
  - Les grandes notes rouges ont besoin d'un hitsound de type finish.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- Les notes bleues doivent avoir un son de sifflet/clap sur ce cercle,
```suggestion
- Les notes bleues doivent avoir un hitsound de type whistle/clap,
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +  - Les grandes notes bleues ont besoin d'une finition et d'un sifflet ensemble.
```suggestion
  - Les grandes notes bleues ont besoin de hitsounds de type whistle et finish en même temps.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- Les spinner représente un shaker.
```suggestion
- Les spinner représentent un shaker.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- Jouer sur un terrain de jeu vide n'entraîne pas de miss.
```suggestion
- Appuyer dans le vide n'entraîne pas de miss.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- Lorsqu'il est joué par [Auto](/wiki/Game_modifier/Auto), le nom du joueur sera *mekkadosu!*.
```suggestion
- Lorsque le mod [Auto](/wiki/Game_modifier/Auto) est utilisé, le nom du joueur sera *mekkadosu!*.
```

2022-01-03 08:57 UTC, Ganondorf-1 commented on wiki/Game_mode/osu!taiko/fr.md
> +- La première beatmap composée de beatmaps d'osu!taiko classée est [Mutsuhiko Izumi - Red Goose (lepidopodus)](https://osu.ppy.sh/beatmapsets/55920)
```suggestion
- La première beatmap classée composée uniquement de difficultés osu!taiko est [Mutsuhiko Izumi - Red Goose (lepidopodus)](https://osu.ppy.sh/beatmapsets/55920)
```

2022-01-03 17:45 UTC, Biokax approved these changes

2022-01-03 17:55 UTC, TicClick approved these changes

2022-01-03 17:56 UTC, merged