Add redirects and links to `Gameplay/{Grade,Judgement}` from other articles
ppy/osu-wiki pull request #6563
Opened 2021-12-17 17:37 UTC by TicClick

part of #6431

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

realistically speaking, I won't be able to get all translations reviewed, and maybe my Google Translate skills are enough for singling `judgement` out -- what do you think?

2021-12-17 17:40 UTC, DoryanR approved these changes
For the French side it's good.

2021-12-17 17:54 UTC, ZeroPyrozen requested changes

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Game_modifier/Hard_Rock/id.md
> +Pada [osu!mania](/wiki/Game_mode/osu!mania), hanya [pengaturan](/wiki/Gameplay/Judgement) kesulitan penilaian (OD) dan nilai AR yang ditingkatkan. Pengaturan kesulitan lainnya tetap tidak berubah. Po
```suggestion
Pada [osu!mania](/wiki/Game_mode/osu!mania), hanya [judgement](/wiki/Gameplay/Judgement) overall difficulty (OD) dan nilai AR yang ditingkatkan. Pengaturan kesulitan lainnya tetap tidak berubah. Posisi peletakkan note-note tidak terpengaruhi.
```

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Beatmapping/Health/id.md
> +- Sukses mengetuk hit circle ([mendapatkan nilai](/wiki/Gameplay/Judgement) lebih memberikan banyak health; hit circle terakhir di warna kombo memberikan tambahan health)
```suggestion
- Sukses mengetuk hit circle ([judgement](/wiki/Gameplay/Judgement) yang lebih baik memberikan banyak health; hit circle terakhir pada warna kombo memberikan tambahan health)
```

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Disambiguation/Rank/id.md
> +- Sebuah [peringkat](/wiki/Gameplay/Grade) berbentuk huruf
```suggestion
- Sebuah [grade](/wiki/Gameplay/Grade) berbentuk huruf
```
To avoid ambiguity between grade and leaderboard

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Game_modifier/Fade_In/id.md
> +Mod **Fade In** adalah sebuah [game modifier](/wiki/Game_modifier) untuk [osu!mania](/wiki/Game_mode/osu!mania) yang meningkatkan kesulitan pada sebuah [beatmap](/wiki/Beatmap) dengan cara menghilang
```suggestion
Mod **Fade In** adalah sebuah [game modifier](/wiki/Game_modifier) untuk [osu!mania](/wiki/Game_mode/osu!mania) yang meningkatkan kesulitan pada sebuah [beatmap](/wiki/Beatmap) dengan cara menghilangkan note-note ketika mereka mendekati bar [judgement](/wiki/Gameplay/Judgement). Itulah asal muasal namanya.
```

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Gameplay/Accuracy/id.md
> +Di osu!, akurasi dikalkulasi dengan menimbang [penilaian](/wiki/Gameplay/Judgement) yang diperoleh dari setiap hit objek berdasarkan nilainya dan dibagi dengan jumlah maksimum yang mungkin.
```suggestion
Di osu!, akurasi dikalkulasi dengan menimbang [judgement](/wiki/Gameplay/Judgement) yang diperoleh dari setiap hit objek berdasarkan nilainya dan dibagi dengan jumlah maksimum yang mungkin.
```

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Hit_object/Hit_circle/id.md
> +Di osu!taiko, hit circle muncul dari kanan ke kiri sebagai nada merah atau biru (Don atau Katu). Saat hit cirlce mendekat dan segaris dengan lingkaran [penilaian](/wiki/Gameplay/Judgement) putih, tom
```suggestion
Di osu!taiko, hit circle muncul dari kanan ke kiri sebagai nada merah atau biru (Don atau Katu). Saat hit cirlce mendekat dan segaris dengan lingkaran [judgement](/wiki/Gameplay/Judgement) putih, tombol yang benar harus ditekan untuk mendapatkan skor.
```

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Hit_object/Slider/id.md
> +Mappper juga dapat menyesuaikan jumlah tick pada slider beatmap mereka di bagian `Timing`. Lebih banyak tick membuat kombo naik lebih cepat (1x lebih banyak per tick) dan dengan demikian menawarkan p
```suggestion
Mappper juga dapat menyesuaikan jumlah tick pada slider beatmap mereka di bagian `Timing`. Lebih banyak tick membuat kombo naik lebih cepat (1x lebih banyak per tick) dan dengan demikian menawarkan peluang untuk skor yang lebih tinggi, tetapi pada saat yang sama memberikan lebih banyak peluang bagi pemain untuk gagal karena [judgement](/wiki/Gameplay/Judgement) menjadi lebih sulit.
```

2021-12-17 17:54 UTC, ZeroPyrozen commented on wiki/Katu/id.md
> +**Katu (激)**, *Katsu*, atau *Beat!*, merupakan sebuah indikator dalam [sistem penilaian osu!](/wiki/Gameplay/Judgement) yang akan muncul setiap kali seorang pemain berhasil mengenai seluruh objek yan
```suggestion
**Katu (激)**, *Katsu*, atau *Beat!*, merupakan sebuah indikator dalam [judgement](/wiki/Gameplay/Judgement) yang akan muncul setiap kali seorang pemain berhasil mengenai seluruh objek yang ada dalam suatu rangkaian combo dengan [akurasi](/wiki/Gameplay/Accuracy) yang baik namun tidak sempurna. Meskipun demikian, Katu tidak akan muncul apabila dalam suatu rangkaian combo terdapat 50 atau *miss* dari pemain.
```

2021-12-17 18:00 UTC, ZeroPyrozen reviewed
Indonesian translation looks good

2021-12-17 20:41 UTC, TicClick commented
also, I deliberately didn't change the `Game mode` articles, as the scoring section from them will be rewritten

2021-12-21 16:02 UTC, Walavouchey approved these changes

2021-12-21 16:03 UTC, merged