[DE] Add `Help_Centre\Account_Restrictions`
ppy/osu-wiki pull request #6564
Opened 2021-12-17 17:47 UTC by The-Last-Cookie

I'm not sure of the translation for `In some cases, an appeal returnee may be banned from official and badged tournaments, both as a competitor and member of the tournament's team.` (line 71). I'm not really fond of `Berufungsrückkehrer`, which is a suggestion by deepl.

By the way, I translated `appeal(ing)` with `Beschwerde (einreichen)`. `Cheating` was mostly used in its original form, sometimes in the form `Schummeln`. `Betrug` is used rarely because I think using it too much is very formal. I've used the words `Einschränkung` and `Sperrung` for `restriction` and `dauerhafte Sperrung` for `ban`.

**Also:**
Replaces a seemingly misplaced full stop with a comma in the English article. Can revert/change this if I'm wrong here.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-28 16:40 UTC, The-Last-Cookie commented
@respektive / @Phippe / @FamousPig do you want to review this?

2021-12-29 03:53 UTC, respektive requested changes
I added a suggestion for the translation you asked about.
Also i agree with the change on the english article but I'm not sure if it should go in a separate PR

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +- Wenn du überzeugt bist, dass deine Einschränkung ein Irrtum ist, dann kontaktiere uns bitte sofort, damit wir deinen Fall besprechen können.
```suggestion
- Wenn du der festen Überzeugung bist, dass deine Einschränkung ein Irrtum ist, dann kontaktiere uns bitte sofort, damit wir deinen Fall besprechen können.
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +Wenn deine Beschwerde zugelassen wurde und dein Account nach dem Spielen erneut eingeschränkt wird, gerate nicht in Panik! Automatisierte Systeme könnten dein Account fälschlicherweise gekennzeichnet
```suggestion
Wenn deine Beschwerde zugelassen wurde und dein Account nach dem Spielen erneut eingeschränkt wird, gerate nicht in Panik! Automatisierte Systeme könnten deinen Account fälschlicherweise gekennzeichnet haben, aber dein Account wird innerhalb von 24 Stunden wieder entsperrt, falls das der Fall sein sollte. Sende uns gerne eine E-Mail oder einen Tweet, um unsere Aufmerksamkeit zu gewinnen und schneller entsperrt zu werden!
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +- **Es ist nicht dein erster Account.** Multi-Accounting ist gegen die Regeln. Jeder andere Account neben dem ersten des Spielers wird dauerhaft gesperrt, aber ihr originaler wird in den meisten Fäll
```suggestion
- **Es ist nicht dein erster Account.** Multi-Accounting ist gegen die Regeln. Jeder andere Account neben dem ersten des Spielers wird dauerhaft gesperrt, aber der originale Account wird in den meisten Fällen unberührt bleiben und der Spieler wird dazu ermutigt, auf diesem weiter zu spielen. Wenn das Multi-Accounting häufig auftritt, wird der originale Account als Warnung stumm geschaltet und der Hauptaccount wird eingeschränkt, sollte das Verhalten dennoch anhalten. Wenn dein Account eingeschränkt ist und du andere besitzt, bitte greife nicht auf diese zu, sondern nutze ausschließlich den originalen Account. Wenn du Probleme beim Zugriff oder Verifizieren deines Accounts hast, sende uns bitte eine E-Mail an [accounts@ppy.sh](mailto:accounts@ppy.sh), damit wir dir helfen können, wieder Zugriff auf deinen Account zu bekommen.
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +- **Du hast jemandem erlaubt, auf deinem Account zu spielen.** Das Teilen von Accounts ist ebenso gegen die Regeln. Wenn du jemandem, Zugriff auf dein Account gibst, dann wird dieser eingeschränkt. D
```suggestion
- **Du hast jemandem erlaubt, auf deinem Account zu spielen.** Das Teilen von Accounts ist ebenso gegen die Regeln. Wenn du jemandem Zugriff auf dein Account gibst, dann wird dieser eingeschränkt. Der Account des Spielers, der deinen Account benutzt hat, wird wahrscheinlich stumm geschaltet oder gesperrt. Wenn das ausversehen passiert ist, lass uns das bitte sobald wie möglich durch eine E-Mail an [accounts@ppy.sh](mailto:accounts@ppy.sh) wissen.
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +- **Habe Spaß am Spiel!** Während dein Account eingeschränkt ist und du eine Auszeit hast, kannst du immer noch das Spiel spielen (solange du auf deinem originalen Account spielst!). Die Scores, die
```suggestion
- **Habe Spaß am Spiel!** Während dein Account eingeschränkt ist und du eine Auszeit hast, kannst du immer noch das Spiel spielen (solange du auf deinem originalen Account spielst!). Die Scores, die du erreichst werden eingereicht und bleiben dir erhalten nachdem die Einschränkung aufgehoben wurde, sofern dein Account nicht zurückgesetzt wird.
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +Du kannst durch eine E-Mail mit dem Nutzernamen deines Accounts an [accounts@ppy.sh](mailto:accounts@ppy.sh) eine Beschwerde einreichen. Stelle sicher, dass du die E-Mail von der E-Mail-Adresse aus s
```suggestion
Du kannst durch eine E-Mail mit dem Nutzernamen deines Accounts an [accounts@ppy.sh](mailto:accounts@ppy.sh) eine Beschwerde einreichen. Stelle sicher, dass du die E-Mail von der E-Mail-Adresse aus sendest, die mit deinem Account verknüpft ist. Erwarte eine Antwort innerhalb einer Woche nachdem du die Beschwerde eingereicht hast. Wenn du danach noch keine Antwort erhalten hast, dann kontaktiere uns bitte via Twitter oder E-Mail - es besteht die Möglichkeit, dass wir sie nicht erhalten haben.
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +- **Wie du die Möglichkeiten erhalten hast.** Das bezieht sich am meisten auf Cheaten - wir wollen wiseen, wie du an die benutzten Tools gelangt bist, wie du darauf gestoßen bist und ob sich die Tool
```suggestion
- **Wie du die Möglichkeiten erhalten hast.** Das bezieht sich am meisten auf Cheaten - wir wollen wissen, wie du an die benutzten Tools gelangt bist, wie du darauf gestoßen bist und ob sich die Tools noch auf deinem Computer befinden.
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +Wenn wir dich zurück lassen, dann musst du eine Einverständnis auf einige Bedingungen geben, bevor die Einschränkung aufgehoben wird.
```suggestion
Wenn wir uns entscheiden, dich wieder zuzulassen, werden wir verlangen, dass du einigen Bedingungen zustimmst, bevor wir dein Konto wieder freigeben.
```
I think this reads better

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +- **Jedes Fehlverhalten wird in einer sofortigen Einschränkung enden**. Das beinhaltet Stummschaltungen.
```suggestion
- **Jedes Fehlverhalten wird in einer sofortigen Einschränkung enden**. Dies beinhaltet schwerwiegende Stummschaltungen.
```
not just any silence will result in a restriction xd

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +In some cases, an appeal returnee may be banned from official and badged tournaments, both as a competitor and member of the tournament's team. Die Dauer der Sperrung ist 1 Jahr pro Verstoß (wenn der
```suggestion
In einigen Fällen kann ein wieder zugelassener Spieler von offiziellen und mit einem Abzeichen versehenen Turnieren ausgeschlossen werden, sowohl als Teilnehmer als auch als Mitglied des Organisationsteams.  Die Dauer der Sperrung ist 1 Jahr pro Verstoß (wenn der Nutzer zum zweiten Mal Beschwerde eingelegt hat, dauert die Sperrung 2 Jahre). Die E-mail zur Entsperrung wird die Dauer der Sperrung darlegen.
```
`wieder zugelassener Spieler` is the best i came up with for `appeal returnee`

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +| Multi-Account | Dauerhaft (Multis) | Hauptaccount wird uneingeschränkt bleiben, möglicherweise stummgeschalten. |
```suggestion
| Multi-Account | Dauerhaft (Multis) | Hauptaccount wird uneingeschränkt bleiben, möglicherweise stummgeschaltet. |
```

2021-12-29 03:53 UTC, respektive commented on wiki/Help_Centre/Account_Restrictions/de.md
> +| Cheaten/Teilen für ein Wettbewerb | 6 Monate | Beschwerdebedingungen treffen zu, entsprechende Rücksetzung, dauerhafte Sperrung von Wettbwerben |
```suggestion
| Cheaten/Teilen für einen Wettbewerb | 6 Monate | Beschwerdebedingungen treffen zu, entsprechende Rücksetzung, dauerhafte Sperrung von Wettbwerben |
```

2021-12-29 17:14 UTC, The-Last-Cookie commented
Thanks for the review 👍 
I've used `Wettbewerb` instead of `Turnier` in line 71 for consistency (`Turnier` would be used only here). Can revert that if you prefer the latter.

2021-12-30 14:42 UTC, respektive approved these changes
looks good to me

2021-12-30 15:50 UTC, TicClick approved these changes
I have temporarily reverted the typo fix to avoid batching it with the translation

2021-12-30 15:51 UTC, merged