[FR] Update `Gameplay\Combo_(score_multiplier)`, `Grade`, `Judgement`, `Judgement\osu!`, `osu!catch`, `osu!mania`, `osu!taiko`
ppy/osu-wiki pull request #6567
Opened 2021-12-17 19:18 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Gameplay\Combo_(score_multiplier)`
- `Gameplay\Grade`
- `Gameplay\Judgement`
- `Gameplay\Judgement\osu!`
- `Gameplay\Judgement\osu!catch`
- `Gameplay\Judgement\osu!mania`
- `Gameplay\Judgement\osu!taiko`
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-22 09:50 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit300.png "300")| 300 | Un score possible lorsque l'on touche un cercle précisément dans le temps, que l'on complète un slider et que l'on garde le slider sur chaqu
```suggestion
| ![](/wiki/shared/judgement/osu!/hit300.png "300") | 300 | Un score possible lorsque l'on touche un cercle précisément dans le temps, que l'on complète un slider et que l'on garde le slider sur chaque tick, ou que l'on complète un spinner avec le compteur de spinner plein. Un score de 300 apparaît par défaut dans un score bleu. Si vous n'obtenez que des scores de 300 dans une beatmap, vous obtiendrez la note SS ou SSH. |
```

2021-12-29 10:29 UTC, Ganondorf-1 requested changes

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit0.png "Miss") | Miss | Un score possible que l'on peut obtenir en ne touchant pas un cercle ou trop tôt (selon OD et AR, il peut *shake* à la place), en ne toucha
```suggestion
| ![](/wiki/shared/judgement/osu!/hit0.png "Miss") | Miss | Un score possible que l'on peut obtenir en ne touchant pas un cercle ou en le touchant beaucoup trop tôt (selon l'OD et l'AR, il peut *trembler* à la place), en ne touchant pas ou en ne tenant pas le slider au moins une fois, ou en terminant un spinner avec un faible remplissage du Spinner Metre. Un miss remet le combo en cours à 0 et empêche l'apparition d'un Katu ou d'un Geki à la fin du combo. |
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- 300, 100 ou 50 donnés d'un cercle normal, selon la précision avec laquelle le joueur tape dessus.
```suggestion
- Un 300, 100 ou 50 est donné par un cercle normal, selon la précision avec laquelle le joueur le touche.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Le jugement des sliders ne dépend pas de la précision du hit initiale.
```suggestion
- Le jugement des sliders ne dépend pas de la précision avec laquelle le début du slider a été touché.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un 300 donné si le joueur réussit à obtenir tous les ticks du slider, un 100 donné si le joueur en obtient au moins la moitié, et un 50 donné si le joueur parvient à collecter ne serait-ce qu'un se
```suggestion
- Un 300 est donné si le joueur réussit à obtenir tous les slider ticks, un 100 est donné si le joueur en obtient au moins la moitié, et un 50 est donné si le joueur parvient à collecter ne serait-ce qu'un seul des ticks.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Le fait de toucher un slider **trop tôt** n'entraîne pas un échec mais remet le multiplicateur de score à **0**.
```suggestion
- Le fait de toucher un slider **trop tôt** n'entraîne pas un miss mais remet le multiplicateur de score à **0**.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +  - Le fait de ne pas collecter les ticks du slider qu'ils soient affichés ou non, n'entraînera pas un échec, mais remettra le multiplicateur de score à **0**.
```suggestion
  - Le fait de ne pas collecter les slider ticks qu'ils soient affichés ou non, n'entraînera pas un miss, mais remettra le multiplicateur de score à **0**.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +  - Le fait de rater le slider end n'entraîne pas un échec mais n'augmente pas le multiplicateur de score.
```suggestion
  - Le fait de manquer le slider end n'entraîne pas un miss mais n'augmente pas le multiplicateur de score.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un miss est donné si le joueur ne récupère aucun des ticks du slider.
```suggestion
- Un miss est donné si le joueur ne récupère aucun slider tick.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un 300, 100 ou 50 donné en fonction du nombre de tours effectués par rapport à la longueur du spinner.
```suggestion
- Un 300, 100 ou 50 est donné en fonction du nombre de tours effectués par rapport à la longueur du spinner.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un miss si le joueur n'est pas en mesure d'élargir le cercle de rotation à une limite satisfaisante pour qu'un 50 soit donné.
```suggestion
- Un miss si le joueur ne joue pas suffisamment le spinner pour qu'un 50 soit donné.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!/fr.md
> +  - Comportement d'un skin v1 : Un miss si le joueur ne parvient pas à remplir le compteur affiché de part et d'autre du spinner à une limite satisfaisante pour qu'un 50 soit donné.
```suggestion
  - Comportement d'un skin v1 : Un miss est donné si le joueur ne parvient pas à remplir la jauge du spinner au moins à moitié.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +![](/wiki/shared/Catch_trails.jpg "Traîné des fruits d'osu!catch")
```suggestion
![](/wiki/shared/Catch_trails.jpg "Chemin des fruits")
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +| ![](img/catch-100.png "Juice Drop") | Juice Drops (Slider Tick) | Ces gros droplets signifient les ticks du slider, semblables aux points (ticks du slider) à l'intérieur des sliders. Il est obligat
```suggestion
| ![](img/catch-100.png "Juice Drop") | Juice Drops (Slider Tick) | Ces gros droplets sont semblables aux slider ticks à l'intérieur des sliders. Il est obligatoire de les attraper pour ne pas perdre le combo. Ils sont deux fois plus gros que les droplets (Slider Trails). 30 points sont donnés pour une capture réussie (affichés comme 100 en multijoueur et sur les résultats). |
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +| ![](img/catch-50.png "Droplet") | Droplets (Slider Trail) | Ces petits droplets sont des slider trails. Elles forment les traces du slider et sont plus petites que les juice drops. 10 pour chaque d
```suggestion
| ![](img/catch-50.png "Droplet") | Droplets (Slider Trail) | Ces petits droplets sont des slider trails. Ils forment le corps du slider et sont plus petits que les juice drops. 10 points sont donnés pour chaque droplets. La précision baisse s'ils ne sont pas attrapés mais cela ne réinitialise pas le combo (affichés comme 50 en multijoueur et sur les résultats). |
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +| (None) | Miss Droplets | Des droplets (Slider Trails) non capturés. N'apparaît pas sur l'écran des résultats mais sur le serveur. Le combo ne sera pas cassé mais la précision diminuera et le score
```suggestion
| (Aucune) | Miss Droplets | Des droplets (Slider Trails) non attrapés. N'apparaissent pas sur l'écran des résultats mais apparaissent côté serveur. Le combo ne sera pas réinitialisé mais la précision diminuera et le score d'un des 50 sera perdu. Ne sont pas considérés comme des miss. N'apparaîssent pas en multijoueur et sur les résultats, mais apparaissent comme *Droplet Miss* sur les classements du site web. |
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +| ![](img/catch-banana.png "Banana") | Bananas | L'équivalent du spinner. Les bananes deviennent de plus en plus petites au fur et à mesure qu'elles tombent vers le catcher. Il n'est pas obligatoire
```suggestion
| ![](img/catch-banana.png "Banana") | Bananas | L'équivalent du spinner. Les bananes deviennent de plus en plus petites au fur et à mesure qu'elles tombent vers le catcher. Il n'est pas obligatoire de les attraper. 1100 points sont donnés si attrapées. Les bananes se comportent comme un spinner réussi dans le mode osu! et donnent à la fois les 1000 points bonus et les 100 points des tours réalisés. |
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +| ![](img/catch-0.png "Miss") | Miss | Les juice drops et les fruits normales ne sont pas prises. Casse les combos. Donné lorsque l'on n'a pas réussi à attraper les Fruit/Juice Drops. Aucun score n'e
```suggestion
| ![](img/catch-0.png "Miss") | Miss | Un fruit ou un juice drop n'a pas été attrapé. Réinitialise le combo. Donné lorsque l'on n'a pas réussi à attraper les fruits/juice drops. Aucun score n'est donné et le combo est réinitialisé. Ceci ne peut être vu que sur l'écran des résultats. |
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +- Score complet lors de la collecte.
```suggestion
- Score entier lors de la collecte.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!catch/fr.md
> +- Rien ne se passe pour les bananes miss.
```suggestion
- Rien ne se passe si des bananes sont manquées.
```

2021-12-29 10:29 UTC, Ganondorf-1 commented on wiki/Gameplay/Judgement/osu!mania/fr.md
> +- Un miss est donné lorsqu'une note est mss ou qu'un hit a été fait trop tôt.
```suggestion
- Un miss est donné lorsqu'une note est manquée ou qu'un hit a été fait trop tôt.
```

2022-01-04 10:41 UTC, Biokax requested changes

2022-01-04 10:41 UTC, Biokax commented on wiki/Gameplay/Combo_(score_multiplier)/fr.md
> +- Un cercle a été manqué.
```suggestion
- Un cercle a été manqué (miss).
```

2022-01-04 10:41 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit300.png "300") | 300 | Un score possible lorsque l'on touche un cercle au bon moment, que l'on joue un slider entièrement et que l'on garde la sliderball sur chaq
```suggestion
| ![](/wiki/shared/judgement/osu!/hit300.png "300") | 300 | Un score possible lorsque l'on touche un cercle au bon moment, que l'on joue un slider entièrement et que l'on garde la sliderball sur chaque slidertick, ou que l'on termine un spinner avec la jauge du spinner remplie. Un score de 300 apparaît par défaut dans une couleur bleue. Si vous n'obtenez que des scores de 300 dans une beatmap, vous obtiendrez la note SS ou SSH. |
```

2022-01-04 10:41 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit100.png "100") | 100 | Un score possible que l'on peut obtenir en touchant un objet légèrement en retard ou en avance, en terminant un slider et en manquant un ce
```suggestion
| ![](/wiki/shared/judgement/osu!/hit100.png "100") | 100 | Un score possible que l'on peut obtenir en touchant un objet légèrement en retard ou en avance, en terminant un slider et en manquant un certain nombre de ticks, ou en terminant un spinner avec la jauge du spinner pratiquement remplie. Un score de 100 apparaît dans une couleur verte par défaut. Lorsque des joueurs très doués testent une beatmap et qu'ils obtiennent beaucoup de 100, cela peut signifier que la beatmap n'a pas un timing correct. |
```

2022-01-04 10:41 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit50.png "50") | 50 | Un score possible que l'on peut obtenir en touchant un cercle assez tôt ou assez tard, mais pas assez tôt ou assez tard pour provoquer un miss
```suggestion
| ![](/wiki/shared/judgement/osu!/hit50.png "50") | 50 | Un score possible que l'on peut obtenir en touchant un cercle assez tôt ou assez tard, mais pas assez tôt ou assez tard pour provoquer un miss, en terminant un slider et en manquant beaucoup de ticks, ou en terminant un spinner avec la jauge de spinner pratiquement vide. Un score de 50 apparaît par défaut dans une couleur orange. Obtenir un score de 50 dans un combo empêchera l'apparition d'un Katu ou d'un Geki à la fin du combo. |
```

2022-01-04 10:41 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit0.png "Miss") | Miss | Un score possible que l'on peut obtenir en ne touchant pas un cercle ou en le touchant beaucoup trop tôt (selon l'OD et l'AR, il peut *trem
```suggestion
| ![](/wiki/shared/judgement/osu!/hit0.png "Miss") | Miss | Un score possible que l'on peut obtenir en ne touchant pas un cercle ou en le touchant beaucoup trop tôt (selon l'OD et l'AR, il peut *trembler* à la place), en ne touchant pas ou en ne tenant pas le slider au moins une fois, ou en terminant un spinner avec une jauge trop peu remplie. Un miss remet le combo en cours à 0 et empêche l'apparition d'un Katu ou d'un Geki à la fin du combo. |
```

2022-01-04 10:41 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un miss si le joueur ne joue pas suffisamment le spinner pour qu'un 50 soit donné.
```suggestion
- Un miss si le joueur ne rempli pas suffisamment la jauge du spinner pour qu'un 50 soit donné.
```

2022-01-04 10:41 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!mania/fr.md
> +| ![](/wiki/shared/judgement/osu!mania/mania-hit300g.gif "Rainbow 300") | Rainbow 300 (MAX) | Frappe parfaite de la note ou le hold. Comparé au 300, l'obtention de cette note exige une précision abso
```suggestion
| ![](/wiki/shared/judgement/osu!mania/mania-hit300g.gif "Rainbow 300") | Rainbow 300 (MAX) | Frappe parfaite de la note ou du hold. Comparé au 300, l'obtention de cette note exige une précision absolue. Sinon, un 300 normal sera donné. Compléter la beatmap avec ce seul score donnera le score maximum de 1 000 000 (limite de 1 million de points). C'est l'équivalent de *Marvelous* en termes de DDR. |
```

2022-01-04 12:19 UTC, Biokax approved these changes

2022-01-04 12:45 UTC, TicClick approved these changes

2022-01-04 12:45 UTC, merged