[FR] Add `osu!stream\Song_List`
ppy/osu-wiki pull request #6571
Opened 2021-12-18 14:17 UTC by DoryanR

Proposal for the French translation of the wiki page `osu!stream\Song_List`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-29 18:47 UTC, Ganondorf-1 requested changes

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Dans le menu Store, vous pouvez faire défiler la liste de tous les packs de musique disponibles et prévisualiser les beatmaps qu'ils contiennent avant de les télécharger. En sélectionnant le bouton `
```suggestion
Dans le menu Store, vous pouvez faire défiler la liste de tous les packs de musiques disponibles et prévisualiser les beatmaps qu'ils contiennent avant de les télécharger. En sélectionnant le bouton `PREVIEW`, vous pourrez voir une courte démonstration de jeu des quatre difficultés dans une beatmap, de la difficulté la plus basse à la plus élevée [dans l'ordre correspondant du stream](/wiki/osu!stream#nouveau-système-de-gameplay).
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Tout comme les [featured artists](/wiki/Featured_Artists) qu'osu! possède aujourd'hui, toutes les musiques disponibles dans le jeu sont soit commandées soit sous licence avant leur sortie. Il est à n
```suggestion
Tout comme les [featured artists](/wiki/Featured_Artists) qu'osu! possède aujourd'hui, toutes les musiques disponibles dans le jeu sont soit commandées soit sous licence avant leur sortie. Il est à noter que les beatmaps d'osu!stream sont au format de fichier `.osf2` (au lieu de [`.osz`](/wiki/osu!_File_Formats/Osz_(file_format))) et ne sont donc pas compatibles avec le client d'osu!.
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +- [Profil de SkyMarshall](https://hafskjold.net/skymarshallarts/)
```suggestion
- [Site web de SkyMarshall](https://hafskjold.net/skymarshallarts/)
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Ce pack comprend quatre musique de l'extraordinaire Cranky.
```suggestion
Ce pack comprend quatre musiques de l'extraordinaire Cranky.
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Ce pack comprend quatre musique de style électronique interprétées par divers musiciens du monde entier.
```suggestion
Ce pack comprend quatre musiques de style électronique interprétées par divers musiciens du monde entier.
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Ce pack comprend quatre musiques/arrangements de compositions originales du projet Touhou par divers musiciens du monde entier.
```suggestion
Ce pack comprend quatre musiques/arrangements de compositions originales de Touhou Project par divers musiciens du monde entier. 
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Initialement, ce pack était inclus dans le lancement du jeu de base au prix de 1,99 USD$. Cependant, en raison de problèmes juridiques liés à la distribution de ressources liées au projet Touhou sur
```suggestion
Initialement, ce pack était inclus dans le lancement du jeu de base au prix de 1,99 USD$. Cependant, en raison de problèmes juridiques liés à la distribution de ressources liées à Touhou Project sur l'App Store en tant que contenu payant, ce pack a été retiré dans la [mise à jour v1.1](https://news.osustream.com/post/10624373514/osustream-v11-release). Ce pack a donc été réédité en tant que contenu gratuit dans la [mise à jour 2020](https://news.osustream.com/post/611013728007274496/osustream-2020-release).
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Ce pack comprend quatre musiques/arrangements de compositions originales du projet Touhou par divers musiciens du monde entier.
```suggestion
Ce pack comprend quatre musiques/arrangements de compositions originales de Touhou Project par divers musiciens du monde entier. 
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +Initialement, ce pack était inclus dans le lancement du jeu de base au prix de 1,99 USD$. Cependant, en raison de problèmes juridiques liés à la distribution de ressources liées au projet Touhou sur
```suggestion
Initialement, ce pack était inclus dans le lancement du jeu de base au prix de 1,99 USD$. Cependant, en raison de problèmes juridiques liés à la distribution de ressources liées à Touhou Project sur l'App Store en tant que contenu payant, ce pack a été retiré dans la [mise à jour v1.1](https://news.osustream.com/post/10624373514/osustream-v11-release). Ce pack a donc été réédité en tant que contenu gratuit dans la [mise à jour 2020](https://news.osustream.com/post/611013728007274496/osustream-2020-release).
```

2021-12-29 18:47 UTC, Ganondorf-1 commented on wiki/osu!stream/Song_List/fr.md
> +![L'écran de chargement de l'aperçu](img/Os-Demo_Load.jpg "L'écran de chargement de l'aperçu")
```suggestion
![L'écran de chargement](img/Os-Demo_Load.jpg "L'écran de chargement")
```

2022-01-04 08:06 UTC, Ganondorf-1 approved these changes

2022-01-04 08:10 UTC, Walavouchey approved these changes

2022-01-04 08:12 UTC, merged