[TH] Update `Twitter`
ppy/osu-wiki pull request #6580
Opened 2021-12-19 10:40 UTC by HelloYeew

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-26 07:04 UTC, timelessnesses requested changes

2021-12-26 07:04 UTC, timelessnesses commented on wiki/Twitter/th.md
> +
เขียนผิดที่โปรไฟล์ครับ

2021-12-26 09:56 UTC, HelloYeew commented on wiki/Twitter/th.md
> +
ขอบคุณฮะ

2022-01-06 02:59 UTC, TPGPL approved these changes

2022-01-06 03:01 UTC, merged