[FR] Update `Shortcut_key_reference`
ppy/osu-wiki pull request #6581
Opened 2021-12-19 14:06 UTC by DoryanR

Proposal to update the French translation of the wiki page `Shortcut_key_reference`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-28 12:57 UTC, Biokax requested changes

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Alt` + `F4` | Ferme le client (pas d'invite). Si vous êtes dans le gameplay, dans l'éditeur de beatmaps ou dans osu!direct, revient à la sélection des beatmaps ou au menu principal (pour osu!direc
```suggestion
| `Alt` + `F4` | Ferme le client (sans confirmation). Si vous êtes dans le gameplay, dans l'éditeur de beatmaps ou dans osu!direct, revient à la sélection des beatmaps ou au menu principal (pour osu!direct). |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Ctrl` + `Alt` + `Shift` + `S` | Recharge le skin actuel. Si vous appuyez sur cette touche pendant le jeu ou sur l'écran des résultats, elle sera exécutée après le retour à l'écran de sélection des
```suggestion
| `Ctrl` + `Alt` + `Shift` + `S` | Recharge le skin actuel. Si vous appuyez sur cette touche en jeu, ou sur l'écran des résultats, elle sera exécutée après le retour à l'écran de sélection des beatmaps. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +## Dans tout le jeu
```suggestion
## Général
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Shift` + `F12` | Prend une capture d'écran et téléchargez-la sur le serveur pour la partager. La capture d'écran sera également enregistrée localement. Cela ouvrira la capture d'écran sur votre na
```suggestion
| `Shift` + `F12` | Prend une capture d'écran et l'upload sur le serveur à des fins de partage. La capture d'écran sera également enregistrée localement. Cela ouvrira la capture d'écran sur votre navigateur web. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Insert` | C'est la [boss key](https://fr.wikipedia.org/wiki/Boss_key). Réduisez le client de jeu dans la zone de notification. Cela rendra également le jeu muet. |
```suggestion
| `Insert` | C'est la [boss key](https://fr.wikipedia.org/wiki/Boss_key). Réduit le client dans la zone de notification. Cela rendra également le jeu muet. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `F5` | Retraite les beatmaps (cela peut vous demander de continuer). |
```suggestion
| `F5` | Recharger les beatmaps (demande une confirmation). |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Q` | Affiche l'invite de sortie. |
```suggestion
| `Q` | Affiche le menu de sortie|
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Esc` | Affiche l'invite de sortie, lorsque le menu d'options et de lecture est fermé. |
```suggestion
| `Esc` | Affiche le menu de sortie, lorsque le menu d'options et de lecture est fermé. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Z` ou `F1` | Lit la musique précédente. |
```suggestion
| `Z` ou `F1` | Joue la musique précédente. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `F4` | Arrête la lecture (réinitialise l'heure actuelle). |
```suggestion
| `F4` | Arrête la lecture (réinitialise le temps). |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `J` ou `F6` | Ouvre le menu de saut vers. |
```suggestion
| `J` ou `F6` | Ouvre le menu de saut. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Esc` | Met le jeu en pause, ou revient à la sélection des beatmaps si vous regardez une rediffusion ou si le mode Auto ou Cinema est utilisé. |
```suggestion
| `Esc` | Met le jeu en pause, ou revient à la sélection des beatmaps si vous regardez une rediffusion ou si le mode Auto ou Cinéma est utilisé. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Shift` + `Tab` | Active/Désactive le masquage de l'interface du jeu. |
```suggestion
| `Shift` + `Tab` | Active/Désactive l'interface du jeu. |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `H` | Active/Désactive le masquage du tableau d'affichage et de l'interface du replay (lorsque vous regardez une replay ou que vous êtes spectateur). |
```suggestion
| `H` | Active/Désactive le tableau de score et l'interface du replay (lorsque vous regardez une replay ou que vous êtes spectateur). |
```

2021-12-28 12:57 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +### Compose
```suggestion
### Composition
```

2021-12-28 13:01 UTC, Biokax commented
A lot of things in that pr and others are like google translated, and that translated a lot a words like section titles that was good into something meanless. They are so much pr with problems that we don't have time to review all of the mess before merging with "no native". I think it will be better to focus on the quality of pr instead of quantity

2021-12-28 13:22 UTC, Walavouchey commented
If you think a translation pr has many problems and need more time to review it, then tell us by commenting on that pr.

2021-12-28 21:08 UTC, DoryanR commented on wiki/Shortcut_key_reference/fr.md
> +| `Q` | Affiche l'invite de sortie. |
| `Q` | Affiche le menu de sortie |

2022-01-04 12:16 UTC, Biokax requested changes

2022-01-04 12:16 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `R` | Active/Désactive l'ajout du Clap vers la sélection.. |
```suggestion
| `R` | Active/Désactive l'ajout du Clap vers la sélection. |
```

2022-01-04 12:16 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Shift` (tout en glissant dans la timeline) | Ignorez le snapping du diviseur de mesure. |
```suggestion
| `Shift` (tout en glissant dans la timeline) | Ignore le snapping du diviseur de mesure. |
```

2022-01-04 12:16 UTC, Biokax commented on wiki/Shortcut_key_reference/fr.md
> +| `Ctrl` + `V` | Colle le sprite à l'heure actuelle. *Remarque : les sprites collés n'apparaîtront pas dans la liste des calques tant que la beatmap n'aura pas été sauvegardé et rechargé. |
```suggestion
| `Ctrl` + `V` | Colle le sprite au temps actuel. *Remarque : les sprites collés n'apparaîtront pas dans la liste des calques tant que la beatmap n'aura pas été sauvegardé et rechargé. |
```

2022-01-04 12:48 UTC, TicClick commented
`master` merged in to resolve the conflict, the review is still up to date

2022-01-04 21:39 UTC, Walavouchey commented on wiki/Client/Keyboard_shortcuts/fr.md
> +| `Ctrl` tout en ajustant le slider velocity | Incrémente de 0.1. |
```suggestion
| `Ctrl` tout en ajustant le slider velocity | Incrémente de 0,1. |
```

2022-01-05 12:24 UTC, Biokax requested changes

2022-01-05 12:24 UTC, Biokax commented on wiki/Client/Keyboard_shortcuts/fr.md
> +Il existe de nombreux raccourcis dans osu! qui peuvent être utilisés dans le jeu ou en mode veille sur n'importe quel écran. Ils sont listés ci-dessous avec leurs fonctions.
```suggestion
Il existe de nombreux raccourcis dans osu! qui peuvent être utilisés en jeu ou depuis n'importe quel menu. Ils sont listés ci-dessous avec leurs fonctions.
```

2022-01-05 12:24 UTC, Biokax commented on wiki/Client/Keyboard_shortcuts/fr.md
> +| `Alt` + `F4` | Ferme le client (sans confirmation). Si vous êtes dans le gameplay, dans l'éditeur de beatmaps ou dans osu!direct, revient à la sélection des beatmaps ou au menu principal (pour osu!
```suggestion
| `Alt` + `F4` | Ferme le client (sans confirmation). Si vous êtes dans en jeu, dans l'éditeur de beatmaps ou dans osu!direct, revient à la sélection des beatmaps ou au menu principal (pour osu!direct). |
```

2022-01-05 12:24 UTC, Biokax commented on wiki/Client/Keyboard_shortcuts/fr.md
> +| `R` | Active/Désactive l'ajout du Clap vers la sélection.. |
```suggestion
| `R` | Active/Désactive l'ajout du Clap vers la sélection. |
```

2022-01-05 12:24 UTC, Biokax commented on wiki/Client/Keyboard_shortcuts/fr.md
> +| `Shift` (tout en glissant dans la timeline) | Ignorez le snapping du diviseur de mesure. |
```suggestion
| `Shift` (tout en glissant dans la timeline) | Ignore le snapping du diviseur de mesure. |
```

2022-01-05 12:24 UTC, Biokax commented on wiki/Client/Keyboard_shortcuts/fr.md
> +| `Ctrl` + `V` | Colle le sprite à l'heure actuelle. *Remarque : les sprites collés n'apparaîtront pas dans la liste des calques tant que la beatmap n'aura pas été sauvegardé et rechargé. |
```suggestion
| `Ctrl` + `V` | Colle le sprite à l'horodatage actuel. *Remarque : les sprites collés n'apparaîtront pas dans la liste des calques tant que la beatmap n'aura pas été sauvegardé et rechargé. |
```

2022-01-05 13:49 UTC, Biokax requested changes

2022-01-05 13:49 UTC, Biokax commented on wiki/Client/Keyboard_shortcuts/fr.md
> +| `Alt` + `F4` | Ferme le client (sans confirmation). Si vous êtes dans en jeu, dans l'éditeur de beatmaps ou dans osu!direct, revient à la sélection des beatmaps ou au menu principal (pour osu!direc
```suggestion
| `Alt` + `F4` | Ferme le client (sans confirmation). Si vous êtes en jeu, dans l'éditeur de beatmaps ou dans osu!direct, revient à la sélection des beatmaps ou au menu principal (pour osu!direct). |
```
oops j'ai oublié celui là, désolé

2022-01-05 13:51 UTC, Walavouchey approved these changes

2022-01-05 13:51 UTC, merged