[DE] Add German `People`, `People\peppy`, `People\The_Team\Account_support_team`; Update `People\The_Team\Support_Team` and `People\The_Team\Global_Moderation_Team`
ppy/osu-wiki pull request #6584
Opened 2021-12-19 19:09 UTC by The-Last-Cookie

The member lists in `People\The_Team\Global_Moderation_Team` were left untranslated because it is just too much work and I don't see sense in translating stuff which might be outdated already next month.

I unfortunately needed to add a TODO to `People\The_Team\Account_support_team` because some articles which were linked from this article aren't available yet.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2021-12-28 16:39 UTC, The-Last-Cookie commented
@respektive / @Phippe / @FamousPig do you want to review this?

2021-12-30 14:39 UTC, respektive requested changes

2021-12-30 14:39 UTC, respektive commented on wiki/People/The_Team/Account_support_team/de.md
> +- [Einschränkungen eines Bot-Accounts](/wiki/Bot_account).
```suggestion
- [Registrierungen von Bot-Accounts](/wiki/Bot_account).
```

2021-12-30 14:39 UTC, respektive commented on wiki/People/The_Team/Global_Moderation_Team/de.md
> +**Globales Moderationsteam** (früher auch bekannt als Globales Modteam, Administratoren oder “GreenBAT”), allgemein auch **GMT**, sind Mitglieder der osu!-Belegschaft, die in erster Linie für die Mod
```suggestion
**Globales Moderationsteam** (früher auch bekannt als Globales Modteam, Administratoren oder “GreenBAT”), allgemein auch **GMT**, sind Mitglieder der osu!-Belegschaft, die in erster Linie für die Moderation der Spieler sowie einschlägige Probleme im Team und in der gesamten Community zuständig sind. Sie sind anhand ihres Nutzertitels und ihrer Nutzerfarbe, die rot im Spiel und Zitrusgrün in den Foren ist, zu erkennen.
```

2021-12-30 14:39 UTC, respektive commented on wiki/People/The_Team/Global_Moderation_Team/de.md
> +- Moderation der Benutzerprofile (NSFW oder anderweitig anstößige Inhalte in Avataren, Profilbilder oder -details, ...)
```suggestion
- Moderation der Benutzerprofile (NSFW oder anderweitig anstößige Inhalte in Avataren, Profilbanner oder -details, ...)
```

2022-01-04 18:34 UTC, Walavouchey approved these changes

2022-01-04 18:36 UTC, merged