[FR] Update `Guides\Custom_Hitsound_Library`, `Custom_Sample_Overrides`, `Discord_Rich_Presence`, `Help_Centre\Installation_and_registration`, `Store`, `Website`, `History_of_osu!\2012`, `2013`
ppy/osu-wiki pull request #6587
Opened 2021-12-20 09:43 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Guides\Custom_Hitsound_Library`
- `Guides\Custom_Sample_Overrides`
- `Guides\Discord_Rich_Presence`
- `Help_Centre\Installation_and_registration`
- `Help_Centre\Store`
- `Help_Centre\Website`
- `History_of_osu!\2012`
- `History_of_osu!\2013`
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

*Feel free to merge if the delay is too long for a review by a native.*

2021-12-22 20:02 UTC, DoryanR commented on wiki/History_of_osu!/2007/fr.md
> +[r]: #références
```suggestion

[r]: #références

```

2021-12-29 12:17 UTC, Biokax requested changes

2021-12-29 12:17 UTC, Biokax commented on wiki/History_of_osu!/2007/fr.md
> +1. [peppy's Twitter post about the start of osu!](https://twitter.com/ppy/status/1141394137637249025?s=20)
```suggestion
1. [post Twitter de peppy sur le début d'osu!](https://twitter.com/ppy/status/1141394137637249025?s=20)
```

2021-12-29 12:17 UTC, Biokax commented on wiki/History_of_osu!/2007/fr.md
> +2. [pUpdater  (aka osume) forum post](https://osu.ppy.sh/community/forums/topics/4?n=1)
```suggestion
2. [pUpdater  (alias osume) post forum](https://osu.ppy.sh/community/forums/topics/4?n=1)
```

2021-12-29 12:17 UTC, Biokax commented on wiki/History_of_osu!/2012/fr.md
> +![](img/2012-10_03.jpg "Entrer dans le multijoueur sans la build b20121008 a cassé osu!mania")
```suggestion
![](img/2012-10_03.jpg "Accéder au multijoueur sans la build b20121008 a cassé osu!mania")
```

2021-12-30 12:29 UTC, Biokax requested changes

2021-12-30 12:29 UTC, Biokax commented on wiki/Guides/Discord_Rich_Presence/fr.md
>  - Commencez n'importe quelle partie multijoueur, rendez-vous sur votre Discord locale et cliquez sur cette icône : ![le bouton vert brillant devant le signe plus](img/shiny-green-button.jpg). Cela pe
```suggestion
- Commencez n'importe quelle partie multijoueur, rendez-vous sur votre Discord local et cliquez sur cette icône : ![le bouton vert brillant devant le signe plus](img/shiny-green-button.jpg). Cela peut prendre quelques secondes pour apparaître si vous venez juste de commencer une partie.
```

2021-12-30 22:34 UTC, Biokax approved these changes

2021-12-30 23:57 UTC, Walavouchey commented on wiki/History_of_osu!/2013/fr.md
> +Pour le mode Multi, les joueurs peuvent désormais utiliser le mod spécial (Relax/Autopilot/SpunOut/ManiaKeys) lorsque le Free Mod est activé par l'hôte. Du côté du skinning, les sprites par défaut du
```suggestion
Pour le mode Multi, les joueurs peuvent désormais utiliser le mod spécial (Relax/Autopilot/SpunOut/ManiaKeys) lorsque le FreeMod est activé par l'hôte. Du côté du skinning, les sprites par défaut du taiko en écran large (taiko `@2x`) ont été ajoutés. Les favoris A/B ont été complètement supprimés et remplacés par les Collections.
```

2021-12-30 23:58 UTC, Walavouchey approved these changes

2021-12-30 23:59 UTC, merged