Merge FAQ with main-menu banner support section
ppy/osu-wiki pull request #6633
Opened 2022-01-01 14:23 UTC by mangomizer

Crucial information on eligibility was in FAQ, which could be missed.

2022-01-01 14:24 UTC, mangomizer commented
Should clarify that I think certain sections on this article should be shuffled around because it doesn't seem very logical (why is the "how to requesting support" at the bottom of the page?

2022-01-01 18:53 UTC, Walavouchey requested changes

2022-01-01 18:53 UTC, Walavouchey commented on wiki/Tournaments/Official_support/en.md
> + Please do not submit a main menu banner with your original request — you will be asked and pointed to this section if you are authorized to make use of one.
Articles generally don't put spaces around em dashes. News posts have somewhat relaxed rules on writing style, which is why they do have spaces there by consensus, but no such thing has been decided for regular articles.

```suggestion
Please do not submit a main menu banner with your original request—you will be asked and pointed to this section if you are authorized to make use of one.
```

2022-01-01 18:53 UTC, Walavouchey commented on wiki/Tournaments/Official_support/en.md
> +- Assessment for a main-menu banner during major matches (generally quarterfinals and above), subject to availability and criteria (see the [relevant section](#Requesting-main-menu-banner-support) be
```suggestion
- Assessment for a main-menu banner during major matches (generally quarterfinals and above), subject to availability and criteria (see the [relevant section](#requesting-main-menu-banner-support) below)
```

2022-01-01 23:46 UTC, cl8n approved these changes
looks good to me, make sure nothing important links to `#main-menu-advertise` though (not sure if that was originally added on purpose for a link somewhere)

2022-01-02 00:41 UTC, Walavouchey approved these changes

2022-01-02 00:42 UTC, merged