[FR] Cleanup Contribution guide
ppy/osu-wiki pull request #6669
Opened 2022-01-06 12:39 UTC by Biokax

small Cleanup of contribution guide

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker]

2022-01-06 12:40 UTC, Biokax commented on wiki/osu!_wiki/Contribution_guide/fr.md
> +Vos modifications seront éventuellement vérifiées par l'un des [wiki maintainers](/wiki/osu!_wiki/Maintenance/List_of_maintainers), généralement après avoir été review par d'autres collaborateurs. Si
```suggestion
Vos modifications seront éventuellement vérifiées par l'un des [wiki maintainers](/wiki/osu!_wiki/Maintenance/List_of_maintainers), généralement après avoir été review par d'autres collaborateurs. Si rien ne se passe après un laps de temps raisonnable, demandez dans les commentaires de la pull request, ou dans le canal `#osu-wiki` du [serveur Discord osu!dev](/wiki/osu!dev_Discord_server). Vos modifications apparaîtront sur le osu! wiki peu de temps après la fusion (dans de rares cas, cela peut prendre jusqu'à cinq heures).
```

2022-01-06 18:58 UTC, Ganondorf-1 requested changes

2022-01-06 18:58 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Contribution_guide/GitHub_web-based_editor/fr.md
> +  - Pour vous aider à vous souvenir du contenu de votre travail, choisissez un nom descriptif. Par exemple, pour une traduction française de [Discussion de la beatmap](/wiki/Beatmap_discussion), vous
```suggestion
  - Pour vous aider à vous souvenir du contenu de votre travail, choisissez un nom descriptif. Par exemple, pour une traduction française de la page [Discussion de la beatmap](/wiki/Beatmap_discussion), vous pourriez utiliser `beatmap-discussion-FR`.
```

2022-01-06 18:58 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Contribution_guide/GitHub_web-based_editor/fr.md
> +Lorsque tout est prêt, utilisez [Guide de contribution au osu! wiki § Self-check](/wiki/osu!_wiki/Contribution_guide#self-check) pour relire vos modifications. Après cela, envoyez vos changements pou
```suggestion
Lorsque tout est prêt, utilisez le [Guide de contribution au osu! wiki § Self-check](/wiki/osu!_wiki/Contribution_guide#self-check) pour relire vos modifications. Après cela, envoyez vos changements pour révision en [ouvrant une pull request](/wiki/osu!_wiki/Contribution_guide#pull-request) au dépôt `ppy/osu-wiki`.
```

2022-01-06 18:58 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/List_of_maintainers/fr.md
> +Curateur, rédacteurs et approbateurs de tous les [news posts](https://osu.ppy.sh/home/news) qui apparaissent sur le site web.
```suggestion
Curateurs, rédacteurs et approbateurs de tous les [news posts](https://osu.ppy.sh/home/news) qui apparaissent sur le site web.
```

2022-01-06 22:17 UTC, Ganondorf-1 approved these changes

2022-01-07 01:11 UTC, TicClick approved these changes

2022-01-07 01:12 UTC, merged