[FR] Add `People\Tournament_Committee`
ppy/osu-wiki pull request #6688
Opened 2022-01-08 18:33 UTC by DoryanR

Proposal for the French translation of the wiki page `People\Tournament_Committee`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-08 18:35 UTC, DoryanR commented on wiki/People/Tournament_Committee/fr.md
> +Le panel a été annoncé pour la première fois au public le 22 juillet 2021 via le canal `#tournaments` du [serveur Discord osu!dev] (https://discord.com/invite/ppy) en réponse à la croissance rapide d
```suggestion
Le panel a été annoncé pour la première fois au public le 22 juillet 2021 via le canal `#tournaments` du [serveur Discord osu!dev](https://discord.com/invite/ppy) en réponse à la croissance rapide des tournois communautaires dans osu!.
```

2022-01-09 19:11 UTC, Biokax requested changes

2022-01-09 19:41 UTC, Ganondorf-1 requested changes

2022-01-09 19:41 UTC, Ganondorf-1 commented on wiki/People/Tournament_Committee/fr.md
> +- Le review régulier de la page [Support officiel des tournois](/wiki/Tournaments/Official_support) pour y apporter des modifications si nécessaire.
```suggestion
- Revoir régulièrement la page [Support officiel des tournois](/wiki/Tournaments/Official_support) pour y apporter des modifications si nécessaire.
```

2022-01-09 19:41 UTC, Ganondorf-1 commented on wiki/People/Tournament_Committee/fr.md
> +- La gestion des reports à partir du [formulaire des reports des tournois](https://pif.ephemeral.ink/tournament-reports)
```suggestion
- La gestion des signalements reçus sur le [formulaire de signalement des tournois](https://pif.ephemeral.ink/tournament-reports)
```

2022-01-09 19:41 UTC, Ganondorf-1 commented on wiki/People/Tournament_Committee/fr.md
> +Le panel a été annoncé pour la première fois au public le 22 juillet 2021 via le canal `#tournaments` du [serveur Discord osu!dev](https://discord.com/invite/ppy) en réponse à la croissance rapide de
```suggestion
Ce comité a été annoncé pour la première fois au public le 22 juillet 2021 via le canal `#tournaments` du [serveur Discord osu!dev](https://discord.com/invite/ppy) en réponse à la croissance rapide des tournois communautaires d'osu!.
```

2022-01-09 19:41 UTC, Ganondorf-1 commented on wiki/People/Tournament_Committee/fr.md
> +Vous pouvez aider le comité des tournois en continuant à organiser d'excellents tournois ! Si vous avez des problèmes ou des préoccupations concernant un aspect quelconque d'un tournoi communautaire,
```suggestion
Vous pouvez aider le comité des tournois en continuant à organiser d'excellents tournois ! Si vous avez des problèmes ou des préoccupations concernant un aspect quelconque d'un tournoi communautaire, nous vous encourageons à les porter à notre attention via le formulaire de signalement des tournois.
```

2022-01-09 19:41 UTC, Ganondorf-1 commented on wiki/People/Tournament_Committee/fr.md
> +Le **Comité des tournois** (*Tournament committee* en anglais) est un groupe d'organisateurs et d'assistants compétents et reconnus dans le domaine des tournois.
```suggestion
Le **Comité des tournois** (*Tournament Committee* en anglais) est un groupe d'organisateurs et d'assistants compétents et reconnus dans le domaine des tournois. 
```

2022-01-09 19:41 UTC, Ganondorf-1 commented on wiki/People/Tournament_Committee/fr.md
> +- L'observation générale des tournois et les conseillers de l'[équipe d'assistance aux comptes](/wiki/People/The_Team/Account_support_team) au cas par cas.
```suggestion
- L'observation générale des tournois ainsi que conseiller [l'équipe de support aux comptes](/wiki/People/The_Team/Account_support_team) au cas par cas.
```

2022-01-10 02:25 UTC, Walavouchey approved these changes

2022-01-10 02:26 UTC, merged