[FR] Cleanup `Gameplay\Grade`, `History_of_osu!\April_Fools`, `Online_rankings`, `Performance_troubleshooting`, `Reporting_bad_behaviour`, `Abuse`, `Handling_foul_play`
ppy/osu-wiki pull request #6710
Opened 2022-01-10 21:04 UTC by DoryanR

Cleanup of the following wiki pages:

- `Gameplay\Grade`
- `History_of_osu!\April_Fools`
- `History_of_osu!\Online_rankings`
- `Performance_troubleshooting`
- `Reporting_bad_behaviour\Abuse`
- `Reporting_bad_behaviour`
- `Reporting_bad_behaviour\Handling_foul_play`
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-11 11:19 UTC, Biokax requested changes

2022-01-11 11:19 UTC, Biokax commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +## Prouvez que je/ils ont triché ! Dites-nous comment vous le savez !
```suggestion
## Prouvez que j'ai/qu'ils ont triché(s) ! Dites-nous comment vous le savez !
```

2022-01-11 11:19 UTC, Biokax commented on wiki/Reporting_bad_behaviour/fr.md
>  osu! a [une équipe de modérateurs](/wiki/People/The_Team/Global_Moderation_Team) qui s'efforce de garder le jeu et son écosystème propres et sûrs. Si vous constatez un comportement contraire aux règl
```suggestion
osu! a [une équipe de modérateurs](/wiki/People/The_Team/Global_Moderation_Team) qui s'efforcent de garder le jeu et son écosystème propres et sûrs. Si vous constatez un comportement contraire aux règles ou un contenu inapproprié, signalez-le en utilisant l'une des méthodes décrites ci-dessous. Vous pouvez également contacter directement l'un des modérateurs en ligne si votre report n'a pas été traité correctement dans un délai raisonnable, mais uniquement en dernier recours.
```

2022-01-11 12:40 UTC, Ganondorf-1 requested changes

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
>  Pendant le jeu, tout ce qui s'affiche à l'écran s'arrête pendant une durée suffisamment longue pour nuire à l'expérience de jeu. Cela peut se produire plus d'une fois, de façon aléatoire ou à interva
```suggestion
Lorsque vous êtes en train de jouer, tout ce qui s'affiche à l'écran s'arrête pendant une durée suffisamment longue pour nuire à l'expérience de jeu. Cela peut se produire plus d'une fois, de façon aléatoire ou à intervalles réguliers. Lors du diagnostic ou du signalement, il peut être utile de :
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
>  - Comptez combien de fois cela se produit dans une session de jeu moyenne.
```suggestion
- Compter combien de fois cela se produit dans une session de jeu moyenne.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
> +- Essayer de fermer toute application qui affiche des superpositions en jeu (Discord, Steam, NVIDIA Shadowplay, etc.).
```suggestion
- Essayer de fermer toute application qui affiche des overlays en jeu (Discord, Steam, NVIDIA Shadowplay, etc.).
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
> +- Vous assurer que le [mode jeu](https://www.windowscentral.com/how-enable-disable-game-mode-windows-10) est activé. Cela permet à Windows de fournir des cœurs et des ressources dédiés à osu!
```suggestion
- Vous assurer que le [mode jeu](https://www.windowscentral.com/how-enable-disable-game-mode-windows-10) est activé. Cela permet à Windows de fournir des cœurs et des ressources dédiés à osu!.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
> +- Essayer de fermer toute application qui affiche des superpositions sur le jeu (Discord, Steam, NVIDIA Shadowplay, etc.).
```suggestion
- Essayer de fermer toute application qui affiche des overlays sur le jeu (Discord, Steam, NVIDIA Shadowplay, etc.).
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
> +osu! offre plusieurs choix de limiteurs de frame. Chacun d'entre eux présente des avantages et des inconvénients. Notez que quel que soit le réglage, osu! limitera la fréquence d'images dans les menu
```suggestion
osu! offre plusieurs choix de limiteurs d'images. Chacun d'entre eux présente des avantages et des inconvénients. Notez que quel que soit le réglage, osu! limitera la fréquence d'images dans les menus pour économiser l'utilisation CPU.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
> +Ce limiteur d'images vise à économiser l'énergie tout en offrant une expérience de jeu cohérente. Il fonctionnera à la fréquence de rafraîchissement du moniteur 2 fois inférieure et tentera de mainte
```suggestion
Ce limiteur d'images vise à économiser l'énergie tout en offrant une expérience de jeu constante. Il fonctionnera à la fréquence de rafraîchissement du moniteur 2 fois inférieure et tentera de maintenir un rythme d'images constant.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Performance_troubleshooting/fr.md
> +Ce limiteur de frame tente de maintenir un taux de frame 8 fois supérieure à votre taux de rafraîchissement, avec un maximum de 960 FPS. C'est le limiteur d'images que nous recommandons aux utilisate
```suggestion
Ce limiteur d'images tente de maintenir un taux d'images 8 fois supérieure à votre taux de rafraîchissement, avec un maximum de 960 FPS. C'est le limiteur d'images que nous recommandons aux utilisateurs qui ne veulent pas pousser leur CPU/GPU à l'extrême, tout en maintenant des niveaux élevés de performance résultant d'une faible latence d'entrée.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Abuse/fr.md
>  Ensuite, bloquez ou mettez en sourdine l'utilisateur en question en cliquant sur les trois points en haut à droite de son tweet (si vous utilisez le site web ou le client mobile). Consultez [le guide
```suggestion
Ensuite, bloquez ou masquez l'utilisateur en question en cliquant sur les trois points en haut à droite de son tweet (si vous utilisez le site web ou le client mobile). Consultez [le guide de Twitter sur le blocage des comptes](https://help.twitter.com/fr/using-twitter/blocking-and-unblocking-accounts) pour plus d'informations.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Abuse/fr.md
> +Sachez que la personne verra que vous l'avez bloquée si elle consulte votre profil Twitter. Si vous craignez que cela n'aggrave le problème ailleurs, mettez-la plutôt en sourdine. Cela supprimera ses
```suggestion
Sachez que la personne verra que vous l'avez bloquée si elle consulte votre profil Twitter. Si vous craignez que cela n'aggrave le problème ailleurs, masquez-la à la place. Cela supprimera ses tweets de votre timeline et vous empêchera de voir d'autres contenus de sa part, mais elle pourra toujours voir et commenter tous vos tweets.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
>  - Un mauvais comportement continu, quel que soit le nombre d'infractions qu'ils accumulent.
```suggestion
- Un mauvais comportement continu, quel que soit le nombre d'infractions qu'il accumule.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +# Traitement d'un acte malveillant
```suggestion
# Traitement d'un acte de tricherie
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +- Du piratage ou de la tricherie (voir ci-dessous).
```suggestion
- Du piratage ou de la triche (voir ci-dessous).
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
>  ## Qu'est-ce qui est considéré comme une tricherie ?
```suggestion
## Qu'est-ce qui est considéré comme de la triche ?
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +Il s'agit d'une règle "à un coup". Dès leur première infraction, les tricheurs seront soumis à des restrictions pour une durée indéterminée. L'[Équipe de support](/wiki/People/The_Team/Account_suppor
```suggestion
Il s'agit d'une règle "à un coup". Dès leur première infraction, les tricheurs seront restreints pour une durée indéterminée. L'[Équipe de support aux comptes](/wiki/People/The_Team/Account_support_team) peut décider de lever la restriction si l'appel est accepté.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +l'Équipe du support ne fournira aucune "preuve" concernant les restrictions, mais toutes sont placées avec une suspicion bien fondée. Il est extrêmement improbable que les utilisateurs normaux soient
```suggestion
L'équipe de support aux comptes ne fournira aucune "preuve" concernant les restrictions, mais toutes sont placées avec une suspicion bien fondée. Il est extrêmement improbable que les utilisateurs normaux soient visés par de telles actions.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +Désolé, mais si vous avez été restreint, l'Équipe du support est déjà sûre que vous trichez. Une vidéo ne sera d'aucune utilité, car même celle-ci peut être falsifiée.
```suggestion
Désolé, mais si vous avez été restreint, l'équipe du support est déjà sûre que vous trichez. Une vidéo ne sera d'aucune utilité, car même celle-ci peut être falsifiée.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
>  Sur le profil de l'utilisateur, un bouton `Signaler` apparaît lorsque vous cliquez sur les trois points à côté du bouton `Message`. Inscrivez toutes les informations qui peuvent prouver que l'utilisa
```suggestion
Sur le profil de l'utilisateur, un bouton `Signaler` apparaît lorsque vous cliquez sur les trois points à côté du bouton `envoyer un message`. Inscrivez toutes les informations qui peuvent prouver que l'utilisateur se comporte mal.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +l'Équipe du support attend des utilisateurs qu'ils fournissent un historique complet de leurs actions et qu'ils donnent les raisons pour lesquelles ils ne récidiveront pas à l'avenir.
```suggestion
L'équipe du support attend des utilisateurs qu'ils fournissent un historique complet de leurs actions et qu'ils donnent les raisons pour lesquelles ils ne récidiveront pas à l'avenir.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/fr.md
> +osu! a [une équipe de modérateurs](/wiki/People/The_Team/Global_Moderation_Team) qui s'efforcent de garder le jeu et son écosystème propres et sûrs. Si vous constatez un comportement contraire aux rè
```suggestion
osu! a [une équipe de modérateurs](/wiki/People/The_Team/Global_Moderation_Team) qui s'efforcent de garder le jeu et son écosystème propres et sûrs. Si vous constatez un comportement contraire aux règles ou un contenu inapproprié, signalez-le en utilisant l'une des méthodes décrites ci-dessous. Vous pouvez également contacter directement l'un des modérateurs en ligne si votre signalement n'a pas été traité correctement dans un délai raisonnable, mais uniquement en dernier recours.
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/fr.md
>  Les reports accidentels sont ignorés. Les utilisateurs qui envoient délibérément des reports non valides risquent d'être [réduits au silence](/wiki/Silence).
```suggestion
Les signalements accidentels sont ignorés. Les utilisateurs qui envoient délibérément des reports non valides risquent d'être [réduits au silence](/wiki/Silence).
```

2022-01-11 12:40 UTC, Ganondorf-1 commented on wiki/Reporting_bad_behaviour/fr.md
>  | Messages privés offensants | **Aucun** : [ignorez l'utilisateur](/wiki/Client/Interface/Chat_console#la-liste-des-commandes). Pour un effet permanent, utilisez la liste d'ignorés du jeu située dans
```suggestion
| Messages privés offensants | **Aucun** : [ignorez l'utilisateur](/wiki/Client/Interface/Chat_console#la-liste-des-commandes). Pour un effet permanent, utilisez la liste d'utilisateurs à ignorer du jeu située dans les [options](/wiki/Client/Options). |
```

2022-01-11 13:45 UTC, DoryanR commented on wiki/Gameplay/Grade/fr.md
> +  - s argenté
```suggestion
  - s argenté
  - notes
```

2022-01-11 13:48 UTC, DoryanR commented on wiki/Reporting_bad_behaviour/Handling_foul_play/fr.md
> +# Traitement d'un acte malveillant
J'avais du mal à trouver un titre cohérent avec l'article, c'est bien trouvé !

2022-01-11 14:49 UTC, Biokax approved these changes

2022-01-12 13:26 UTC, Walavouchey approved these changes

2022-01-12 13:27 UTC, merged