[FR] Cleanup `People\The_Team\Beatmap_Nominators\Beatmap_Nominator_Test`, `Beatmap_Veto`, `Becoming_a_Beatmap_Nominator`, `Expectations`, `General_Information`, `Rules`
ppy/osu-wiki pull request #6711
Opened 2022-01-10 22:11 UTC by Ganondorf-1

Cleanup of the Beatmap Nominators folder (excluding the `Beatmap Nominators` page.)

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-11 06:33 UTC, DoryanR submitted a review, later dismissed
👍

2022-01-11 08:00 UTC, Biokax requested changes

2022-01-11 08:00 UTC, Biokax commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/fr.md
> +Les BN non probatoires peuvent faire une "Quality Assurance" en vérifiant à tout moment les beatmaps qualifiées pour détecter des problèmes. La page de la Quality Assurance peut être trouvé [sur le s
```suggestion
Les BN non probatoires peuvent faire une "Quality Assurance" en vérifiant à tout moment les beatmaps qualifiées pour détecter des problèmes. La page de la Quality Assurance peut être trouvée [sur le site des BN](https://bn.mappersguild.com/qualityassurance).
```

2022-01-11 13:51 UTC, Biokax submitted a review, later dismissed

2022-01-11 14:00 UTC, DoryanR approved these changes

2022-01-12 08:27 UTC, cl8n commented on wiki/People/The_Team/Beatmap_Nominators/General_Information/fr.md
>  ![Bouton de réinitialisation de la nomination](img/reset_q-fr.png)
not caused by this PR but this really should be a single image like EN, so the figure/caption thing can display correctly

2022-01-12 08:27 UTC, cl8n approved these changes

2022-01-12 08:27 UTC, merged