[FR] Cleanup `Rules`, `Code_of_Conduct_for_Modding_and_Mapping`, `Content_Usage_Guidelines`, `Content_Voting_Process`, `Explicit_Content`, `Song_Content_Rules`, `Visual_Content_Considerations`
ppy/osu-wiki pull request #6718
Opened 2022-01-11 21:23 UTC by DoryanR

Cleanup of the following wiki pages:

- `Rules\Code_of_Conduct_for_Modding_and_Mapping`
- `Rules\Content_Usage_Guidelines`
- `Rules\Content_Voting_Process`
- `Rules\Explicit_Content`
- `Rules`
- `Rules\Song_Content_Rules`
- `Rules\Visual_Content_Considerations`
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-13 11:40 UTC, Biokax requested changes

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/Song_Content_Rules/fr.md
> +À l'exception des téléchargements inappropriés, tous les utilisateurs disposent d'un délai de **une mise en ligne* avant que des pénalités ne soient infligées en raison de la nature incertaine de cet
```suggestion
À l'exception des mises en ligne inappropriés, tous les utilisateurs disposent d'un délai de **mise en ligne* avant que des pénalités ne soient infligées en raison de la nature incertaine de cette décision. Une fois cette marge de manœuvre passée, les utilisateurs qui choisissent de continuer de mettre en ligne des pistes inappropriés se verront infliger un [silence](/wiki/Silence) de 42 heures ainsi que la suppression de leur mise en ligne.
```

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/Visual_Content_Considerations/fr.md
> +- La mise en ligne des beatmaps, **même ceux tagués comme [explicites](/wiki/Rules/Explicit_Content)**.
```suggestion
- la mise en ligne des beatmaps, **même celles taguées comme [explicites](/wiki/Rules/Explicit_Content)**.
```

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/Visual_Content_Considerations/fr.md
> +- Les détails du profil (avatars, images de couverture)
```suggestion
- les détails du profil (avatars, images de couverture)
```

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/Visual_Content_Considerations/fr.md
> +- Toute autre pièce jointe ou lien hypertexte (messages du forum, commentaires, messages de discussion sur une beatmap)
```suggestion
- toute autre pièce jointe ou lien hypertexte (messages du forum, commentaires, messages de discussion sur une beatmap)
```

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/Visual_Content_Considerations/fr.md
> +- **La violence excessive, le gore, le démembrement, la décapitation ou la mutilation.**
```suggestion
- **la violence excessive, le gore, le démembrement, la décapitation ou la mutilation.**
```

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/Visual_Content_Considerations/fr.md
> +- **l'Exhibition ou sollicitation à caractère sexuel**
```suggestion
- **l'exhibition ou sollicitation à caractère sexuel**
```

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/Visual_Content_Considerations/fr.md
> +*¹* : Cette règle peut faire l'objet d'exceptions en fonction de la nature de la drogue, de son usage et de sa sous-culture, notamment dans le cas de drogues faisant l'objet d'une décriminalisation e
```suggestion
*¹* : Cette règle peut faire l'objet d'exceptions en fonction de la nature de la drogue, de son usage et de sa sous-culture, notamment dans le cas de drogues faisant l'objet d'une décriminalisation et d'une réglementation rapides dans le monde entier, comme la marijuana. Les demandes d'exceptions spécifiques à cette règle doivent être faites en contactant l'[équipe de support aux comptes](/wiki/People/The_Team/Account_support_team) à l'adresse [support@ppy.sh](mailto:support@ppy.sh).
```

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/fr.md
> +4. **Ne soyez pas un con.** Si, à un moment donné, vous ne savez pas si vous enfreignez cette règle, c'est probablement le cas.
je sais même pas comment ça a pu passer lol

2022-01-13 11:40 UTC, Biokax commented on wiki/Rules/fr.md
>  1. **Assurez-vous d'avoir la permission d'utiliser tout contenu impliqué dans votre beatmap.** Cela inclut les chansons, les vidéos, les sons, les graphiques et tout autre contenu qui n'est pas votre
```suggestion
1. **Assurez-vous d'avoir la permission d'utiliser tout contenu impliqué dans votre beatmap.** Cela inclut les chansons, les vidéos, les sons, les graphiques et tout autre contenu qui n'est pas votre propre création. Si vous ne savez pas où trouver du contenu dont l'utilisation est gratuite, consultez notre bibliothèque [Featured Artist](https://osu.ppy.sh/beatmaps/artists) en pleine expansion, qui contient des musiques dont l'utilisation est autorisée à 100 % dans osu! et les [directives d'utilisation du contenu](Content_Usage_Guidelines) pour plus d'informations.
```

2022-01-13 13:58 UTC, DoryanR commented on wiki/Rules/fr.md
> +Si, après plusieurs infractions, vous continuez à enfreindre les règles, votre compte peut être [définitivement et irrévocablement restreint](/wiki/Help_Centre/Account_restrictions).
```suggestion
Si, après plusieurs infractions, vous continuez à enfreindre les règles, votre compte peut être [définitivement et irrévocablement restreint](/wiki/Help_centre/Account_restrictions).
```

2022-01-13 13:58 UTC, DoryanR commented on wiki/Rules/fr.md
> +Les comptes soumis à des restrictions ne peuvent pas jouer en ligne, mettre en ligne des scores, discuter avec d'autres utilisateurs et sont, à toutes fins utiles, "interdits" d'interaction avec la c
```suggestion
Les comptes soumis à des restrictions ne peuvent pas jouer en ligne, mettre en ligne des scores, discuter avec d'autres utilisateurs et sont, à toutes fins utiles, "interdits" d'interaction avec la communauté. Les restrictions pour violation des règles de la communauté ne peuvent être supprimées que sur appel auprès de l'équipe d'assistance après 3 mois ([d'autres conditions peuvent s'appliquer](/wiki/Help_centre/Account_restrictions#raisons-de-restriction-courantes-et-leurs-cooldowns)).
```

2022-01-15 07:15 UTC, Walavouchey approved these changes

2022-01-15 07:17 UTC, merged

2022-01-15 11:00 UTC, Biokax commented
La pr a été merge avant que @Ganondorf-1 n'ai eu le temps de la review, en plus il y a des termes offensants tel qu'un "~~connard~~" qui sont passés. Une ou plusieurs review vont être nécessaire pour corriger tout ça