[ZH] Update `Ranking Criteria`
ppy/osu-wiki pull request #6732
Opened 2022-01-14 20:15 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-19 04:58 UTC, RushFTK requested changes
review early parts of RC (zh)

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +**注意[摸图和作图行为准则](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping)、[八分拍歌曲测定](/wiki/Ranking_Criteria/Timing_Songs_With_8-Signatures)、[歌曲内容规定](/wiki/Rules/Song_Content_Rules)是 Ranking Criteria 的一部分，适
```suggestion
**注意[摸图和作图的行为准则](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping)、[八分拍歌曲Timing测定](/wiki/Ranking_Criteria/Timing_Songs_With_8-Signatures)和[歌曲内容规定](/wiki/Rules/Song_Content_Rules)是 Ranking Criteria 的一部分，适用于 osu! 中所有的游戏模式。**
```
"Timing"是一个在中文圈也较为常用的专业术语，可保留不翻。  
删去"和，的"个人认为会导致句子不通顺。

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +**Ranking Criteria** 列出了让[谱面](/wiki/Beatmap)通过[谱面ranking程序](/wiki/Beatmap_ranking_procedure)时须遵守的[规则和准则](#一般术语)
英文原文中存在`must`，为了强调遵守的重要性，建议保留原翻译中的词语"必须"

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +本文中规则和准则的改变会在 [Ranking Criteria 论坛](https://osu.ppy.sh/community/forums/87)中提出和讨论。参照 *[如何建议更改Ranking准则](https://osu.ppy.sh/community/forums/topics/720532)* 来提供贡献。注意，若在仅改变本文的语言、语法、组织，而不改变其原意的情况下则无需发帖至
```suggestion
可在 [Ranking Criteria 论坛](https://osu.ppy.sh/community/forums/87)中提出和讨论对本文的更正。并参照 *[如何建议更改Ranking准则](https://osu.ppy.sh/community/forums/topics/720532)* 来提供贡献。注意，若仅对本文中的遣词、语法、组句进行改变，而不改变其原意，则无需发帖至论坛。
```
原文仅包含`this document`。故删去第一句的"规则和准则"。  
rules 在后文被翻译成“规定”，作为专有名词，应保持一致性。  
我认为原文翻译尚可，如果必须更改，可以调整为中文语序。  
`organisation` 的翻译我也拿不太准，个人推断原文的含义是"如何组织句子"。

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +## 常规
原翻译使用`一般`我个人觉得更好，如果想让本文更加书面化，不知可否写成`一般性原则`或`通用`？

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- **两个物件不能出现在同一时间上。** 包括圆圈、滑条、转盘覆盖的全部时间段。osu!mania 模式除外。
原文使用`tick`，建议保留原翻译"时间点"更好。 
如果觉得`circle`翻译成圈不正规，可考虑翻译成"单点"。这个需要和中文维基翻译团队确认标准术语翻译。

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- **必须在包含快速、重复的闪烁图像，或视频、故事板内含有对比度、颜色、亮度的快速变化内容的谱面中开启光敏性癫痫警告。** 如果警告会影响谱面游玩，则必须在歌曲前增加足够的空白时间。3 HZ（或：1秒变化3帧） 以下的闪烁图像一般无须担心。如果有疑问，请开启警告并在摸图时讨论是否有必要开启它。
```suggestion
- **包含快速、重复的闪烁图像，或视频、故事板内含有对比度、颜色、亮度的快速变化内容的谱面，必须开启光敏性癫痫警告。** 如果警告会影响谱面游玩，则必须在歌曲前增加足够的空白时间。3 HZ（即：1秒闪烁3次） 以下的闪烁图像一般无须担心。如果有疑问，请开启警告并在摸图时讨论是否有必要开启它。
```
原文如下：  
> ... Strobing effects at 3 Hz (i.e. 3 flashes per second)  ...  

这里按照原文字面翻译即可，解释也可能造成歧义。    
另外，第一句话的脉冲图像可以考虑直接字面意思翻译，这里我拿不太准，等待其他reviewer的意见。

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- **谱面文件夹中不能有未使用文件或 0 字节的文件。** 0 字节的文件会影响文件夹中其他文件的正常上传。自动生成的 `thumbs.db` 文件除外。
```suggestion
- **谱面文件夹中不能有未使用文件或 0 字节的文件。** 0 字节的文件会影响文件夹中其他文件的正常上传。仅自动生成的 `thumbs.db` 文件除外。
```

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- **如果相同游戏模式下的难度包含相同的休息时间或相同的故事板，则它们的`休息段使用黑边填充背景`设定必须一致，**
这句话前面漏一条规定的翻译，原文如下：
> **Difficulty settings must not use more precision than is possible in the beatmap editor.**
可参考翻译如下：  
````
**难度的各项设定必须保证是在谱面编辑器手工设定时可复现的。** 
````
（这条规则主要限制诸如CS设个3.1415926这种可以改难度文件做到，但是在谱面编辑器中按住Shift设置也做不到的一些行为）

`Letterbox during breaks` 可以作为专有名词范畴，考虑到现在没有官方中文的谱面编辑器，这里建议保留原有名词，类似上面提到的这种专有名词保留问题全文还有很多，碍于时间关系这条review可能无法完整涉及，有时间我会继续摸完。

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- **如果谱面包含剧透内容，则请在谱面描述中标注剧透警告。**
```suggestion
- **如果谱面包含剧透内容，则必须在谱面描述中标注剧透警告。**
```
规定就是规定，使用"请"之类的环境更像是准则。

2022-01-19 04:58 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- **谱面使用的素材作者应列在谱面介绍内。** 参见[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)，谱面使用的素材只有获得素材创作者的授权才能在 osu! 内使用。他们的授权可能会详细说明允许谱师如何合规使用这些素材。如果极难追溯到素材的来源、创作者允许无授权转载、授权已展示在艺术家、曲名、谱面元数据参考区域时，则通常无需在谱面介绍内再次标注。
```suggestion
- **谱面使用素材的作者应列在谱面介绍内。** 参见[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)，谱面使用的素材只有获得素材创作者的授权才能在 osu! 内使用。他们的授权可能会详细说明允许谱师如何合规使用这些素材。如果极难追溯到素材的来源、创作者允许无授权转载、授权已展示在艺术家、曲名、谱面元数据参考区域时，则通常无需在谱面介绍内再次标注。
```

> Creators of the media used in a beatmap should be credited in the beatmap's description. Per the Content Usage Guidelines, media used in beatmaps should be permitted for use in osu!, and their licensing will likely detail how to credit their creators. Common reasons to omit credits from the description include exceeding difficulty in sourcing, creators' wishes to remain uncredited, and presence of credits in the artist, title, or source fields.

这后面我看着是在说明license包含有哪些内容的样子，我不太确定，可能en版又更新了。  
介于时间关系这条摸先到这里，其余的我会慢慢看继续摸完。其实整体翻译的质量还是很不错的，我自己肯定很难做到啦。

2022-01-21 10:00 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +- **如果相同游戏模式下的难度包含相同的休息时间或相同的故事板，则它们的`休息段使用黑边填充背景`设定必须一致，**
可能是翻译的时候漏掉了 感谢补充
而且 关于“专有名词”的翻译，我个人是感觉虽然守旧肯定是没问题的，但是已经过时而且有碍于玩家的交流。（现在玩家甚至简称为“黑边”）

2022-01-21 10:35 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +**Ranking Criteria** 列出了让[谱面](/wiki/Beatmap)通过[谱面ranking程序](/wiki/Beatmap_ranking_procedure)时须遵守的[规则和准则](#一般术语)
这里须就是必须的须，我只是让语序看起来更通顺一点

2022-01-21 10:40 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +- **两个物件不能出现在同一时间上。** 包括圆圈、滑条、转盘覆盖的全部时间段。osu!mania 模式除外。
使用圆圈是可行的，不会让他看起来不正规。
因为之前红线、绿线有特定翻译“非继承时间点”，如果这里用时间点会造成混淆。

2022-01-21 11:03 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +## 常规
我个人觉得一般太偏口语了，包括通用这个词。一般性原则太长了

2022-01-21 11:07 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +- **如果相同游戏模式下的难度包含相同的休息时间或相同的故事板，则它们的`休息段使用黑边填充背景`设定必须一致，**
已添加

2022-01-21 11:57 UTC, cdwcgt requested changes
RC大写
英文字母空格
还有点别的

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +**Ranking Criteria** 列出了让[谱面](/wiki/Beatmap)通过[谱面ranking程序](/wiki/Beatmap_ranking_procedure)时须遵守的[规则和准则](#一般术语)
```suggestion
**Ranking Criteria** 列出了让[谱面](/wiki/Beatmap)通过[谱面 Ranking 程序](/wiki/Beatmap_ranking_procedure)时须遵守的[规则和准则](#一般术语)
```

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +可在 [Ranking Criteria 论坛](https://osu.ppy.sh/community/forums/87)中提出和讨论对本文的更正。并参照 *[如何建议更改Ranking准则](https://osu.ppy.sh/community/forums/topics/720532)* 来提供贡献。注意，若仅对本文中的遣词、语法、组句进行改变，而不改变其原意，则无需发帖至论坛。
```suggestion
可在 [Ranking Criteria 论坛](https://osu.ppy.sh/community/forums/87)中提出和讨论对本文的更正。并参照 *[如何建议更改 Ranking 准则](https://osu.ppy.sh/community/forums/topics/720532)* 来提供贡献。注意，若仅对本文中的遣词、语法、组句进行改变，而不改变其原意，则无需发帖至论坛。
```

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +**注意[摸图和作图的行为准则](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping)、[八分拍歌曲Timing测定](/wiki/Ranking_Criteria/Timing_Songs_With_8-Signatures)和[歌曲内容规定](/wiki/Rules/Song_Content_Rules)是 Ranking Criteria
```suggestion
**注意[摸图和作图的行为准则](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping)、[八分拍歌曲 Timing 测定](/wiki/Ranking_Criteria/Timing_Songs_With_8-Signatures)和[歌曲内容规定](/wiki/Rules/Song_Content_Rules)是 Ranking Criteria 的一部分，适用于 osu! 中所有的游戏模式。**
```

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +- **准则（Guidelines）：** 在**例外情况**下可以违反准则。这些例外情况必须能够详细解释，说明违反准则的原因，以及不违反准则将如何影响谱面的整体质量。
规定使用了空格来表示强调 `规定就是 **规定**。`
但是准则这样做 统一一下？

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +- **谱面使用素材的作者应列在谱面介绍内。** 参见[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)，谱面使用的素材只有获得素材创作者的授权才能在 osu! 内使用。他们的授权可能会详细说明允许谱师如何合规使用这些素材。如果极难追溯到素材的来源、创作者允许无授权转载、授权已展示在艺术家、曲名、谱面元数据参考区域时，则通常无需在谱面介绍内再次标注。
```suggestion
- **谱面使用素材的作者应列在谱面介绍内。** 参见[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)，谱面使用的素材只有获得素材创作者的授权才能在 osu! 内使用。他们的授权可能会详细说明允许谱师如何合规使用这些素材。如果极难追溯到素材的来源、创作者允许无授权转载，或者授权已展示在艺术家、曲名、谱面元数据参考区域时，则通常无需在谱面介绍内再次标注。
```

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +- **每个难度必须遵循其模式的 ranking criteria 。** 参见 [osu!](osu!), [osu!taiko](osu!taiko), [osu!catch](osu!catch)，和 [osu!mania](osu!mania) 的 ranking criteria 获取更多信息。
```suggestion
- **每个难度必须遵循其模式的 Ranking Criteria 。** 参见 [osu!](osu!), [osu!taiko](osu!taiko), [osu!catch](osu!catch)，和 [osu!mania](osu!mania) 的 Ranking Criteria 获取更多信息。
```

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +- **带有日文元数据的歌曲必须使用[平文式罗马字](https://en.wikipedia.org/wiki/Hepburn_romanization#Features)罗马音化。** 如果作图者偏好罗马音的 Source，则也应用于该字段。对于非 Unicode 域，长元音如 `おう` 和 `うう` 应该写作罗马音 `ou` 和 `uu`，以避免长元音符号。
```suggestion
- **带有日文元数据的歌曲必须使用[平文式罗马字](https://zh.wikipedia.org/wiki/%E5%B9%B3%E6%96%87%E5%BC%8F%E7%BD%97%E9%A9%AC%E5%AD%97)罗马音化。** 如果作图者偏好罗马音的 Source，则也应用于该字段。对于非 Unicode 域，长元音如 `おう` 和 `うう` 应该写作罗马音 `ou` 和 `uu`，以避免长元音符号。
```
再不济这个也行（
https://baike.baidu.com/item/%E5%B9%B3%E6%96%87%E5%BC%8F%E7%BD%97%E9%A9%AC%E5%AD%97/4513631

2022-01-21 11:57 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +  - **osu!mania 谱面则使用了不同的难度分布规则和最低难度限制。参见：[osu!mania ranking criteria](/wiki/Ranking_Criteria/osu!mania).**
```suggestion
  - **osu!mania 谱面则使用了不同的难度分布规则和最低难度限制。参见：[osu!mania Ranking Criteria](/wiki/Ranking_Criteria/osu!mania).**
```

2022-01-21 11:58 UTC, cdwcgt commented on wiki/Ranking_Criteria/zh.md
> +- **谱面使用素材的作者应列在谱面介绍内。** 参见[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)，谱面使用的素材只有获得素材创作者的授权才能在 osu! 内使用。他们的授权可能会详细说明允许谱师如何合规使用这些素材。如果极难追溯到素材的来源、创作者允许无授权转载、授权已展示在艺术家、曲名、谱面元数据参考区域时，则通常无需在谱面介绍内再次标注。
我超 那没事了

2022-01-22 04:51 UTC, kj415j45 requested changes

2022-01-22 04:51 UTC, kj415j45 commented on wiki/Ranking_Criteria/zh.md
> +从描述中省略信用的常见原因包括寻找来源的难度过大、创作者希望保持无信用，以及艺术家、标题或来源字段中存在信用。
Credit 机翻？

2022-01-22 17:07 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +从描述中省略信用的常见原因包括寻找来源的难度过大、创作者希望保持无信用，以及艺术家、标题或来源字段中存在信用。
参考了机翻 但是没改掉这个 改一改

2022-01-22 17:10 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +- **带有日文元数据的歌曲必须使用[平文式罗马字](https://en.wikipedia.org/wiki/Hepburn_romanization#Features)罗马音化。** 如果作图者偏好罗马音的 Source，则也应用于该字段。对于非 Unicode 域，长元音如 `おう` 和 `うう` 应该写作罗马音 `ou` 和 `uu`，以避免长元音符号。
ok

2022-01-22 23:09 UTC, Walavouchey requested changes

2022-01-22 23:09 UTC, Walavouchey commented on wiki/Ranking_Criteria/zh.md
> +- **[故事板敲击音效](/wiki/Beatmapping/Hitsound#passive-hitsound)不能替换[主动打击音效](/wiki/Beatmapping/Hitsound#active-hitsound)。** 这会给玩家不准确的反馈。在其他情况下，可以但不鼓励使用故事板敲击音效。osu!mania 不受这一规定的约束。
```suggestion
- **[故事板敲击音效](/wiki/Beatmapping/Hitsound#storyboarded-hitsound)不能替换[主动打击音效](/wiki/Beatmapping/Hitsound#active-hitsound)。** 这会给玩家不准确的反馈。在其他情况下，可以但不鼓励使用故事板敲击音效。osu!mania 不受这一规定的约束。
```

2022-01-24 16:33 UTC, Walavouchey approved these changes

2022-01-24 16:34 UTC, merged

2022-01-24 16:34 UTC, cdwcgt approved these changes