[FR] Add `Ranking_Criteria\osu!catch`
ppy/osu-wiki pull request #6740
Opened 2022-01-15 20:27 UTC by DoryanR

Proposal to add the French translation of the wiki page `Ranking_Criteria\osu!catch`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-15 20:29 UTC, DoryanR commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +## Spécifique à une difficulté :
```suggestion
## Spécifique à une difficulté
```

2022-01-18 13:01 UTC, Biokax commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de quatre fois entre des [fruits](/wiki/Hit_objec
```suggestion
- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de quatre fois consécutifs entre des [fruits](/wiki/Hit_object/Fruit).**
```

2022-01-18 13:06 UTC, Biokax requested changes
I forgot this one

2022-01-18 13:06 UTC, Biokax commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dashs](/wiki/Glossary/Dash) et les [hyperdashes](/wiki/Glossary/Hyperdash) ne doivent pas être utilisés lorsque la destination du dash ou de l'hyperdash est située près du bord gauche ou dro
```suggestion
- **Les [dashs](/wiki/Glossary/Dash) et les [hyperdashes](/wiki/Glossary/Hyperdash) ne doivent pas être utilisés lorsque la destination du dash ou de l'hyperdash est située près du bord gauche ou droit du terrain de jeu.** Cela crée un mouvement inconfortable car le catcher est arrêté de force lorsqu'il atteint la limite du terrain de jeu (x:16 à gauche et x:496 à droite).
```

2022-01-18 16:45 UTC, DoryanR commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les sliderends étendus doivent être snapped en fonction de la structure rythmique de la musique.** Si la chanson utilise un rythme direct, il faut utiliser 1/4, 1/8 et 1/16. Si la chanson utilise
```suggestion
- **Les slider tails étendus doivent être snapped en fonction de la structure rythmique de la musique.** Si la chanson utilise un rythme direct, il faut utiliser 1/4, 1/8 et 1/16. Si la chanson utilise un rythme swing, il faut utiliser 1/6 ou 1/12. Si la chanson a un son dans un rythme différent de celui recommandé, le rythme réel est toujours prioritaire.
```

2022-01-19 10:42 UTC, Ganondorf-1 requested changes

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +Les règles et directives générales s'appliquent à tous les types de difficultés d'osu!catch. Les règles et directives relatives au rythme s'appliquent aux beatmaps d'environ 180 BPM avec des signatur
```suggestion
Les règles et directives générales s'appliquent à tous les types de difficultés d'osu!catch. Les règles et directives relatives au rythme s'appliquent aux beatmaps d'environ 180 BPM avec des signatures temporelles 4/4. Si votre musique est nettement plus rapide ou plus lente, certaines variables peuvent être différentes, comme indiqué dans [Mise à l'échelle du BPM sur les critères de classement](/wiki/Ranking_Criteria/Scaling_BPM).
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Chaque beatmap doit utiliser au moins deux [couleurs de combos](/wiki/Glossary/Combo_colour) personnalisées différentes, sauf si le skin par défaut est forcé.** Les couleurs des combos ne doivent
```suggestion
- **Chaque beatmap doit utiliser au moins deux [couleurs de combo](/wiki/Glossary/Combo_colour) personnalisées différentes, sauf si le skin par défaut est forcé.** Les couleurs de combo ne doivent en aucun cas se mélanger à l'arrière-plan/le storyboard/la vidéo de la beatmap. Ainsi, les objets sont toujours visibles pour le joueur et les couleurs de combos du skin personnalisé ne se mélangent pas accidentellement avec l'arrière-plan.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **N'utilisez pas les keysounds sans support de hitnormal.** Si les sons s'intègrent parfaitement à la musique, l'effet de rétroaction pour la touche des notes est minime.
```suggestion
- **N'utilisez pas les keysounds sans support de hitnormal.** Si les bruitages s'intègrent parfaitement à la musique, l'effet de rétroaction après avoir touché des notes est minime.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les slider tails étendus doivent être snapped en fonction de la structure rythmique de la musique.** Si la chanson utilise un rythme direct, il faut utiliser 1/4, 1/8 et 1/16. Si la chanson utili
```suggestion
- **Les slider tails étendus doivent être snapped en fonction de la structure rythmique de la musique.** Si la musique utilise un rythme direct, il faut utiliser 1/4, 1/8 et 1/16. Si la musique utilise un rythme swing, il faut utiliser 1/6 ou 1/12. Si la musique a un son dans un rythme différent de celui recommandé, le rythme réel est toujours prioritaire.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dashs](/wiki/Glossary/Dash) et les [hyperdashes](/wiki/Glossary/Hyperdash) ne doivent pas être utilisés lorsque la destination du dash ou de l'hyperdash est située près du bord gauche ou dro
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) et les [hyperdashes](/wiki/Glossary/Hyperdash) ne doivent pas être utilisés lorsque la destination du dash ou de l'hyperdash est située près du bord gauche ou droit du playfield.** Cela crée un mouvement inconfortable car le catcher est arrêté de force lorsqu'il atteint la limite du playfield (x:16 à gauche et x:496 à droite).
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **S'assurer que les [combos](/wiki/Beatmapping/Combo) n'atteignent pas des longueurs déraisonnables.** Les [fruits](/wiki/Hit_object/Fruit) attrapés s'empilent sur le plateau et peuvent potentielle
```suggestion
- **S'assurer que les [combos](/wiki/Beatmapping/Combo) n'atteignent pas des longueurs déraisonnables.** Les [fruits](/wiki/Hit_object/Fruit) attrapés s'empilent sur le plateau et peuvent potentiellement obstruer la vue du joueur. N'oubliez pas que les slider tails, les répétitions et les [spinners](/wiki/Hit_object/Spinner) [bananes](/wiki/Hit_object/Banana) comptent également comme des "fruits". De nouveaux combos doivent être placés régulièrement pour vider le plateau et éviter cela.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **L'[Overall Difficulty](/wiki/Beatmapping/Overall_difficulty) doit avoir la même valeur que l'[Approach Rate](/wiki/Beatmapping/Approach_rate).** Il s'agit simplement d'une valeur standardisée, ca
```suggestion
- **L'[Overall Difficulty](/wiki/Beatmapping/Overall_difficulty) doit avoir la même valeur que l'[Approach Rate](/wiki/Beatmapping/Approach_rate).** Il s'agit simplement d'une valeur standardisée, car l'Overall Difficulty n'affecte pas la jouabilité, pas plus que le nombre de [fruits](/wiki/Hit_object/Fruit) que possède un [spinner](/wiki/Hit_object/Spinner). L'Overall Difficulty n'affecte que le score maximum d'une difficulté.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Le slider tick rate doit être réglé en fonction de la chanson.** Par exemple, si votre chanson n'utilise que le 1/3 snapping, utiliser le tick rate 2 ou 4 ne serait pas approprié.
```suggestion
- **Le slider tick rate doit être réglé en fonction de la musique.** Par exemple, si votre musique n'utilise que le snapping 1/3, utiliser le tick rate 2 ou 4 ne serait pas approprié.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Utilisez le même  slider tick rate pour chaque difficulté.** Car il s'agit d'une propriété de la musique plutôt que du mapping. Cependant, les difficultés inférieures peuvent utiliser des tick ra
```suggestion
- **Utilisez le même slider tick rate pour chaque difficulté.** Car il s'agit d'une propriété de la musique plutôt que du mapping. Cependant, les difficultés inférieures peuvent utiliser des tick rates plus faibles pour réduire les exigences de précision pour les nouveaux joueurs, à condition qu'ils suivent toujours le rythme de la musique. Utiliser des tick rates élevés uniquement pour augmenter le score/le combo/la difficulté est insensé.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Évitez d'utiliser des [couleurs de combos](/wiki/Glossary/Combo_colour) avec une luminosité de ~50 ou moins.** Les couleurs sombres ont un impact sur la lisibilité des [fruits](/wiki/Hit_object/F
```suggestion
- **Évitez d'utiliser des [couleurs de combo](/wiki/Glossary/Combo_colour) avec une luminosité de ~50 ou moins.** Les couleurs sombres ont un impact sur la lisibilité des [fruits](/wiki/Hit_object/Fruit) avec une faible luminosité de fond.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Évitez d'utiliser des [couleurs de combos](/wiki/Glossary/Combo_colour) avec une luminosité de ~220 ou plus si le kiai time est utilisé.** Les couleurs claires créent des impulsions lumineuses pe
```suggestion
- **Évitez d'utiliser des [couleurs de combo](/wiki/Glossary/Combo_colour) avec une luminosité de ~220 ou plus si le kiai time est utilisé.** Les couleurs claires créent des impulsions lumineuses pendant le kiai time, ce qui peut être désagréable pour les yeux.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les catchers personnalisés doivent être inclus dans le format de skin v2.** Ceci est pour assurer un affichage correct sur tous les skins. Les noms de fichiers requis sont `fruit-catcher-idle.png
```suggestion
- **Les catchers personnalisés doivent être inclus dans le format de skin v2.** Ceci permet d'assurer un affichage correct sur tous les skins. Les noms de fichiers requis sont `fruit-catcher-idle.png`, `fruit-catcher-kiai.png` et `fruit-catcher-fail.png`.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les éléments du skin doivent avoir la même taille que leurs homologues skinnée par défaut.** Ceci afin qu'ils représentent correctement la hitbox et n'altèrent pas le gameplay. Les dimensions act
```suggestion
- **Les éléments du skin doivent avoir la même taille que ceux du skin par défaut.** Ceci leur permet de représenter correctement la hitbox et n'altèrent pas le gameplay. Les dimensions actuelles utilisées dans le skin par défaut sont 128x128 pixels pour les [fruits](/wiki/Hit_object/Fruit), 82x103 pour les [drops](/wiki/Hit_object/Juice_stream#drop) et 306x320 pour le catcher.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +Les règles et directives spécifiques à une difficulté ne s'appliquent qu'au niveau de difficulté pour lequel elles sont listées et ne *s'appliquent donc pas à **toutes** les difficultés d'osu!catch*.
```suggestion
Les règles et directives spécifiques à une difficulté ne s'appliquent qu'au niveau de difficulté pour lequel elles sont listées et ne *s'appliquent donc pas à **toutes** les difficultés d'osu!catch*. Les règles et directives relatives au rythme s'appliquent aux beatmaps d'environ 180 BPM. Si votre musique est nettement plus rapide ou plus lente, certaines variables peuvent être différentes, comme indiqué dans [Mise à l'échelle du BPM sur les critères de classement](/wiki/Ranking_Criteria/Scaling_BPM).
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dashs](/wiki/Glossary/Dash) et les [hyperdashes](/wiki/Glossary/Hyperdash) de toute sorte sont interdits.** Ceci afin de garantir une expérience de départ facile aux joueurs débutants. Pour
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) et les [hyperdashes](/wiki/Glossary/Hyperdash) de toute sorte sont interdits.** Ceci permet de garantir une expérience de départ facile aux joueurs débutants. Pour tester cela, il doit être possible d'atteindre un rang SS dans la difficulté sans utiliser la touche Dash.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Il faut laisser au moins 250 ms entre les cercles/slider et le début et la fin des [spinners](/wiki/Hit_object/Spinner).** Ceci afin de garantir la lisibilité.
```suggestion
- **Il faut laisser au moins 250 ms entre les cercles/sliders et le début et la fin des [spinners](/wiki/Hit_object/Spinner).** Ceci afin de garantir la lisibilité.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [Hyperdash](/wiki/Glossary/Hyperdash) de toute sorte sont interdits.** Ceci afin de garantir un niveau de difficulté raisonnable pour les joueurs novices.
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) de toute sorte sont interdits.** Ceci permet de garantir un niveau de difficulté raisonnable pour les joueurs novices.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dash](/wiki/Glossary/Dash) doivent avoir un écart d'au moins 125 ms entre leurs deux objets.**
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) doivent avoir un écart d'au moins 125 ms entre leurs deux objets.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dashs](/wiki/Glossary/Dash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de deux fois consécutifs entre des [fruits](/wiki/Hit_objec
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de deux fois consécutives entre des [fruits](/wiki/Hit_object/Fruit).**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dashs](/wiki/Glossary/Dash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) doivent toujours être suivis d'un [walk](/wiki/Glossary/Walk).**
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) doivent toujours être suivis d'un [walk](/wiki/Glossary/Walk).**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Il faut laisser au moins 250 ms entre les cercles/slider et le début et la fin des [spinners](/wiki/Hit_object/Spinner).** Ceci afin de garantir la lisibilité.
```suggestion
- **Il faut laisser au moins 250 ms entre les cercles/sliders et le début et la fin des [spinners](/wiki/Hit_object/Spinner).** Ceci afin de garantir la lisibilité.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Toutes les distances doivent indiquer clairement si le joueur doit [walk](/wiki/Glossary/Walk) ou [dash](/wiki/Glossary/Dash).** Ceci afin de s'assurer que les joueurs puissent facilement reconna
```suggestion
- **Toutes les distances doivent indiquer clairement si le joueur doit [walk](/wiki/Glossary/Walk) ou [dash](/wiki/Glossary/Dash).** Ceci afin de s'assurer que les joueurs puissent facilement reconnaître les patterns qui requièrent de dash.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dash](/wiki/Glossary/Dash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés consécutivement lorsque différents battements sont utilisés.** Pa
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés consécutivement lorsque différents battements sont utilisés.** Par exemple, un dash de 1/1 suivi d'un dash de 1/2.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dash](/wiki/Glossary/Dash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être suivis de pattern [antiflow](/wiki/Beatmapping/Antiflow).**
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être suivis de patterns [antiflow](/wiki/Beatmapping/Antiflow).**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **La densité des notes doit suivre un pattern principalement 1/1 et 1/2.** Les pattern 1/3 et/ou 1/4 doivent être utilisés avec parcimonie.
```suggestion
- **La densité des notes doit suivre un pattern principalement 1/1 et 1/2.** Les patterns 1/3 et/ou 1/4 doivent être utilisés avec parcimonie.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdash](/wiki/Glossary/Hyperdash) doivent avoir un écart d'au moins 125 ms entre leurs deux objets.**
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) doivent avoir un écart d'au moins 125 ms entre leurs deux objets.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashes](/wiki/Glossary/Hyperdash) ne peuvent pas être utilisés sur les [drop](/wiki/Hit_object/Juice_stream#drop) individuelles et/ou les répétitions de sliders.** La précision et le co
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) ne peuvent pas être utilisés sur les [drops](/wiki/Hit_object/Juice_stream#drop) individuels et/ou les répétitions de sliders.** La précision et le contrôle requis sont déraisonnables à ce niveau et peuvent créer une situation où le joueur ne parvient pas à lire la trajectoire du slider.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdash](/wiki/Glossary/Hyperdash) d'un rythme différent ne doivent pas être utilisés entre des [fruits](/wiki/Hit_object/Fruit) consécutifs.** Par exemple, un 1/2 hyperdash suivi d'un 1/4
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) d'un rythme différent ne doivent pas être utilisés entre des [fruits](/wiki/Hit_object/Fruit) consécutifs.** Par exemple, un 1/2 hyperdash suivi d'un 1/4 hyperdash.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdash](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de deux fois consécutifs entre des [fruits](/wiki/
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de deux fois consécutives entre des [fruits](/wiki/Hit_object/Fruit).**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dash](/wiki/Glossary/Dash) doivent avoir un écart d'au moins 62 ms entre leurs deux objets.**
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) doivent avoir un écart d'au moins 62 ms entre leurs deux objets.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dash](/wiki/Glossary/Dash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de quatre fois consécutifs entre des [fruits](/wiki/Hit_obje
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de quatre fois consécutives entre des [fruits](/wiki/Hit_object/Fruit).**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [dash](/wiki/Glossary/Dash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) peuvent être utilisés jusqu'à deux fois consécutifs entre des [fruits](/wiki/Hit_object/Frui
```suggestion
- **Les [dashes](/wiki/Glossary/Dash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) peuvent être utilisés jusqu'à deux fois consécutives entre des [fruits](/wiki/Hit_object/Fruit), à condition qu'il n'y ait pas de changement de direction entre eux.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash)  forts ne doivent pas être utilisés.** Pour les hyperdashs [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped), une limite de 1,5 fois la [trigg
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) forts ne doivent pas être utilisés.** Pour les hyperdashes [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped), une limite de 1,5 fois la [trigger distance](/wiki/Glossary/Trigger_distance) est recommandée. Pour les hyperdashes [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped), une limite de 1,3 fois la trigger distance est recommandée.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdash](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) peuvent être utilisés en conjonction avec des pattern [antiflow](/wiki/Beatmapping/A
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) peuvent être utilisés en conjonction avec des patterns [antiflow](/wiki/Beatmapping/Antiflow).** S'il est utilisé, l'espacement ne doit pas dépasser un distance snap de 1,2 fois la [trigger distance](/wiki/Glossary/Trigger_distance) lorsqu'il est suivi d'un [walk](/wiki/Glossary/Walk), ou de 1,1 fois la trigger distance lorsqu'il est suivi d'un [dash](/wiki/Glossary/Dash) basic-snapped.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être suivis de pattern [antiflow](/wiki/Beatmapping/Antiflow).** S
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être suivis de patterns [antiflow](/wiki/Beatmapping/Antiflow).** S'il est utilisé, l'espacement ne doit pas dépasser une distance snap de 1,1 fois la [trigger distance](/wiki/Glossary/Trigger_distance) et le mouvement après l'hyperdash doit être un [walk](/wiki/Glossary/Walk).
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **La densité des notes doit suivre un pattern principalement de 1/2 et/ou 1/3.** Les pattern 1/4 et/ou 1/6 doivent être utilisés avec parcimonie.
```suggestion
- **La densité des notes doit suivre un pattern principalement de 1/2 et/ou 1/3.** Les patterns 1/4 et/ou 1/6 doivent être utilisés avec parcimonie.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de quatre fois consécutifs entre des [fruits](/wi
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de quatre fois consécutives entre des [fruits](/wiki/Hit_object/Fruit).**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de deux fois dans un slider.** Le chemin du slide
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés plus de deux fois dans un slider.** Le chemin du slider doit être simple et facile à suivre.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être utilisés en conjonction avec des [dash](/wiki/Glossary/Dash)
```suggestion
- **Les [hyperdashe](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être utilisés en conjonction avec des [dashes](/wiki/Glossary/Dash) ou tout autre hyperdash.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdash](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être utilisés dans un slider.**
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être utilisés dans un slider.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashes](/wiki/Glossary/Hyperdash) ne doivent pas être utilisés sur les [drops](/wiki/Hit_object/Juice_stream#drop) individuelles et/ou les répétitions de sliders.**
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) ne doivent pas être utilisés sur les [drops](/wiki/Hit_object/Juice_stream#drop) individuels et/ou les répétitions de sliders.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés consécutivement lorsque des battements différents sont
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) ne doivent pas être utilisés consécutivement lorsque des battements différents sont utilisés.** Par exemple, un hyperdash 1/1 suivi d'un hyperdash 1/2.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être suivis de [antiflow](/wiki/Beatmapping/Antiflow) [dashes](/wi
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) qui sont [higher-snapped](/wiki/Gameplay/Dash_snapping#higher-snapped) ne doivent pas être suivis d'[antiflow](/wiki/Beatmapping/Antiflow) [dashes](/wiki/Glossary/Dash) avec un écart inférieur à 250ms.**
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdash](/wiki/Glossary/Hyperdash) ne doivent être utilisés que sur les [drops](/wiki/Hit_object/Juice_stream#drop) et/ou les répétitions de sliders lorsque le chemin du slider est simple
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) ne doivent être utilisés que sur les [drops](/wiki/Hit_object/Juice_stream#drop) et/ou les répétitions de sliders lorsque le chemin du slider est simple et facile à suivre.** Ceci afin d'éviter un mouvement chaotique ou déraisonnablement difficile du slider, car la transition vers et depuis des formes complexes de sliders avec hyperdashes est généralement inconfortable à jouer, et une pénalité majeure à la précision pour peu d'avantages.
```

2022-01-19 10:42 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
> +- **Les [hyperdashs](/wiki/Glossary/Hyperdash) de 1/8 et plus ne doivent pas être utilisés entre des paires d'objets consécutifs.**
```suggestion
- **Les [hyperdashes](/wiki/Glossary/Hyperdash) de 1/8 et plus ne doivent pas être utilisés entre des paires d'objets consécutifs.**
```

2022-01-19 11:56 UTC, Biokax approved these changes

2022-01-19 14:07 UTC, Walavouchey approved these changes

2022-01-19 14:10 UTC, merged