[FR] Update `Gameplay\Accuracy`
ppy/osu-wiki pull request #6755
Opened 2022-01-18 20:51 UTC by DoryanR

Proposal to update the French translation of the wiki page `Gameplay\Accuracy`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-19 11:06 UTC, Biokax requested changes

2022-01-19 11:06 UTC, Biokax commented on wiki/Gameplay/Accuracy/fr.md
>  Dans osu!, la précision est calculée en pondérant le [jugement](/wiki/Gameplay/Judgement) obtenu de chaque hit object et en le divisant par la valeur maximum qu'il est possible de réaliser.
```suggestion
Dans osu!, la précision est calculée en pondérant le [jugement](/wiki/Gameplay/Judgement) obtenu de chaque hit object et en le divisant par la valeur maximale qu'il est possible de réaliser.
```

2022-01-19 11:58 UTC, Biokax submitted a review, later dismissed

2022-01-19 21:17 UTC, DoryanR commented on wiki/Gameplay/Accuracy/fr.md
> +![[Précision = (nombre de fruits attrapés + nombre de drops attrapés + nombre de droplets attrapés) / (nombre de tout les fruits + nombre de tout les drops + nombre de tout les droplets)](img/accurac
```suggestion
![Précision = (nombre de fruits attrapés + nombre de drops attrapés + nombre de droplets attrapés) / (nombre de tout les fruits + nombre de tout les drops + nombre de tout les droplets)](img/accuracy_catch_updated.png "La formule de la précision pour osu!catch")
```
```suggestion
![[Précision = (nombre de fruits attrapés + nombre de drops attrapés + nombre de droplets attrapés) / (nombre de tout les fruits + nombre de tout les drops + nombre de tout les droplets)](img/accuracy_catch_updated.png "La formule de la précision pour osu!catch")
```

2022-01-20 12:21 UTC, Biokax requested changes

2022-01-20 12:21 UTC, Biokax commented on wiki/Gameplay/Accuracy/fr.md
> +![Précision = (nombre de fruits attrapés + nombre de drops attrapés + nombre de droplets attrapés) / (nombre de tout les fruits + nombre de tout les drops + nombre de tout les droplets)](img/accuracy
```suggestion
![Précision = (nombre de fruits attrapés + nombre de drops attrapés + nombre de droplets attrapés) / (nombre de tous les fruits + nombre de tout les drops + nombre de tous les droplets)](img/accuracy_catch_updated.png "La formule de la précision pour osu!catch")
```

2022-01-20 14:29 UTC, Biokax approved these changes

2022-01-20 19:14 UTC, Walavouchey approved these changes

2022-01-20 19:15 UTC, merged