add Chinese translation of `Medals`
ppy/osu-wiki pull request #6761
Opened 2022-01-19 11:01 UTC by cdwcgt

Co-Authored-By: Dead_Bush_Sanpai <46657591+DeadBushSanpai@users.noreply.github.com>

- [ ] Describe of `Hush-Hush`
- [ ] Need to check `Beatmap Challenge Packs`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-21 07:46 UTC, Kotoki1337 requested changes

2022-01-21 07:46 UTC, Kotoki1337 commented on wiki/Medals/zh.md
> +**奖章**，曾被称为 *成就*，是在用户个人资料页面中展示出来的一枚枚小型图案，可以体现玩家的游戏水准和技巧。目前，在如下八个分类下有共计**247**枚奖章：[曲包](#曲包)，[实力](#实力)，[毅力](#毅力)，[Mod 入门](#Mod-入门)，[隐藏](#隐藏)，[谱面聚光灯](#beatmap-spotlights)，[季节聚光灯](#seasonal-spotlights)，和
```suggestion
**奖章**，曾被称为 *成就*，是在用户个人资料页面中展示出来的一枚枚小型图案，可以体现玩家的游戏水准和技巧。目前，在如下八个分类下有共计**247**枚奖章：[曲包](#曲包)，[实力](#实力)，[毅力](#毅力)，[Mod 入门](#Mod-入门)，[隐藏](#隐藏)，[聚光灯谱面](#beatmap-spotlights)，[聚光灯季节](#seasonal-spotlights)，和[挑战谱面曲包](#挑战谱面曲包)。
```

我觉得这样听起来更顺一点，括号里的跳转记得改成和下文标题相同。

2022-01-21 07:46 UTC, Kotoki1337 commented on wiki/Medals/zh.md
> +**mod 入门**是在特定的[游戏模组（mod）](/wiki/Game_modifier)下通过[Qualified](/wiki/Beatmap/Category#qualified)，[Ranked](/wiki/Beatmap/Category#ranked)，或者 [Approved](/wiki/Beatmap/Category#approved)谱面获得。这些奖章是为了激励新玩家
```suggestion
**Mod 入门**是在特定的[游戏模组（Mod）](/wiki/Game_modifier)下通过 [Qualified](/wiki/Beatmap/Category#qualified)，[Ranked](/wiki/Beatmap/Category#ranked)，或者 [Approved](/wiki/Beatmap/Category#approved) 谱面获得。这些奖章是为了激励新玩家尝试并体验各种各样的 Mod 而设立的。但是请注意，如果玩家同时使用多个 Mods。则玩家**不会**获得*任何* Mod 奖章。
```

format i think?

2022-01-21 07:46 UTC, Kotoki1337 commented on wiki/Medals/zh.md
> +**隐藏奖章**通过*神秘*的方式来获得，不会具体告诉玩家获得奖章的方法(因此得名)。使用特殊方法通过谱面。但是仍有一些提示给那些想要收集全奖章的人，如下所示：
```suggestion
**隐藏奖章**通过*神秘*的方式来获得，不会具体告诉玩家获得奖章的方法（因此得名）。使用特殊方法通过谱面。但是仍有一些提示给那些想要收集全奖章的人，如下所示：
```
another format

2022-01-21 09:12 UTC, cdwcgt commented on wiki/Medals/zh.md
> +**奖章**，曾被称为 *成就*，是在用户个人资料页面中展示出来的一枚枚小型图案，可以体现玩家的游戏水准和技巧。目前，在如下八个分类下有共计**247**枚奖章：[曲包](#曲包)，[实力](#实力)，[毅力](#毅力)，[Mod 入门](#Mod-入门)，[隐藏](#隐藏)，[谱面聚光灯](#beatmap-spotlights)，[季节聚光灯](#seasonal-spotlights)，和
聚光灯季节是不是有点太怪了
我到可能更偏向于 `季节性` 的修饰而不是把他当作一个 `季节` 的名字
挑战同理 还不如直接叫挑战曲包

聚光灯谱面倒是觉得可以改

2022-01-21 09:17 UTC, Kotoki1337 commented on wiki/Medals/zh.md
> +**奖章**，曾被称为 *成就*，是在用户个人资料页面中展示出来的一枚枚小型图案，可以体现玩家的游戏水准和技巧。目前，在如下八个分类下有共计**247**枚奖章：[曲包](#曲包)，[实力](#实力)，[毅力](#毅力)，[Mod 入门](#Mod-入门)，[隐藏](#隐藏)，[谱面聚光灯](#beatmap-spotlights)，[季节聚光灯](#seasonal-spotlights)，和
我读了八百万次感觉聚光灯放后面太怪了，怎么读都读不顺。这个 Seasonal 确实有点不好处理，然后根据原文的 `Although the Seasonal Spotlights have been discontinued as of early 2020 in favour of the current Beatmap Spotlights system`，还需要跟新系统赛季做出对应区分，也许我们可以更进一步，使用 `季节性聚光灯曲包`，又可以和下面的 `挑战曲包`相适应，也从标题引出了该奖章需要完成曲包内谱面获得。What do you think?

2022-01-21 09:19 UTC, cdwcgt commented on wiki/Medals/zh.md
> +**隐藏奖章**通过*神秘*的方式来获得，不会具体告诉玩家获得奖章的方法(因此得名)。使用特殊方法通过谱面。但是仍有一些提示给那些想要收集全奖章的人，如下所示：
fix at 4b1db8cc4229d7c3be8f9266d14ea628e58d2400

2022-01-21 09:19 UTC, cdwcgt commented on wiki/Medals/zh.md
> +**mod 入门**是在特定的[游戏模组（mod）](/wiki/Game_modifier)下通过[Qualified](/wiki/Beatmap/Category#qualified)，[Ranked](/wiki/Beatmap/Category#ranked)，或者 [Approved](/wiki/Beatmap/Category#approved)谱面获得。这些奖章是为了激励新玩家
fix at 4b1db8cc4229d7c3be8f9266d14ea628e58d2400

2022-01-22 05:02 UTC, kj415j45 commented on wiki/Medals/zh.md
> +然而值得注意的是，所有 Video Game Packs, Anime Packs, Internet! Pack 和 Rhythm Game Packs 自 [2008 年首次推出](https://osu.ppy.sh/community/forums/topics/1853) 以来发生了巨大变化。 有关处于旧版的曲包的列表，请参见[旧版曲包](/wiki/Medals/Legacy_bea
```suggestion
然而值得注意的是，所有 Video Game Packs, Anime Packs, Internet! Pack 和 Rhythm Game Packs 自 [2008 年首次推出](https://osu.ppy.sh/community/forums/topics/1853) 以来已经发生了巨大变化。欲查看旧版曲包的列表，参见[旧版曲包](/wiki/Medals/Legacy_beatmap_packs)。
```

2022-01-22 05:02 UTC, kj415j45 commented on wiki/Medals/zh.md
> +**曲包奖章**在完成某些[主题曲包](https://osu.ppy.sh/beatmaps/packs?type=theme)或者[艺术家/专辑曲包](https://osu.ppy.sh/beatmaps/packs?type=artist)后获得。这些奖章通过完成曲包中每个谱面集的其中一个难度来获得。
```suggestion
**曲包奖章**在完成某些[主题曲包](https://osu.ppy.sh/beatmaps/packs?type=theme)或者[艺术家/专辑曲包](https://osu.ppy.sh/beatmaps/packs?type=artist)后获得。这些奖章通过完成曲包中每个谱面集的任意一个难度来获得。
```

2022-01-22 05:16 UTC, Kotoki1337 commented on wiki/Medals/zh.md
> +**奖章**，曾被称为 *成就*，是在用户个人资料页面中展示出来的一枚枚小型图案，可以体现玩家的游戏水准和技巧。目前，在如下八个分类下有共计**247**枚奖章：[曲包](#曲包)，[实力](#实力)，[毅力](#毅力)，[Mod 入门](#Mod-入门)，[隐藏](#隐藏)，[谱面聚光灯](#beatmap-spotlights)，[季节聚光灯](#seasonal-spotlights)，和
括号内容可以考虑写在下文的原文后

2022-02-06 02:14 UTC, kj415j45 requested changes

2022-02-06 02:14 UTC, kj415j45 commented on wiki/Medals/zh.md
> +**隐藏奖章**通过*神秘*的方式来获得，不会具体告诉玩家获得奖章的方法（因此得名）。使用特殊方法通过谱面。但是仍有一些提示给那些想要收集全奖章的人，如下所示：
```suggestion
**隐藏奖章**通过*神秘*的方式获得，不会告诉玩家如何获得奖章（因此得名）。取得方式从完成谱面并达成特殊要求，到使用一些非同寻常的 mod 组合都有。尽管如此，还是有一些提示给那些想要收集全奖章的人：
```

2022-02-06 02:14 UTC, kj415j45 commented on wiki/Medals/zh.md
> +因为这些奖章意图就是隐藏的，解锁方式并未告知。但我们[欢迎玩家们一起探索如何解锁这些奖章](https://osu.ppy.sh/home/news/2016-08-17-new-hush-hush-medals)。
```suggestion
由于这些奖章设计上就是隐藏成就，因此我们不会直接写明解锁方式。但我们[欢迎玩家们一起探索如何解锁这些奖章](https://osu.ppy.sh/home/news/2016-08-17-new-hush-hush-medals)。
```

2022-02-08 13:34 UTC, kj415j45 approved these changes

2022-02-08 13:34 UTC, kj415j45 commented on wiki/Medals/zh.md
> +虽然第一期聚光灯在 2018 年 4 月被[第二期聚光灯](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018)替代而不再发行，但时至今日，原有对应的奖章仍然可以获得。
```suggestion
虽然第一期聚光灯的奖章在 2018 年 4 月被[第二期聚光灯](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018)替代而不再发行，但时至今日仍可以获得对应的奖章。
```

2022-02-08 16:46 UTC, Walavouchey approved these changes

2022-02-08 16:47 UTC, merged