[FR] Update `Ranking_Criteria\osu!mania`
ppy/osu-wiki pull request #6770
Opened 2022-01-20 20:35 UTC by DoryanR

Proposal to update the French translation of the wiki page `Ranking_Criteria\osu!mania`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-20 20:37 UTC, DoryanR commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +Les propositions de règles ainsi que les suggestions sont discutées dans le [Sous-forum Ranking Criteria] (https://osu.ppy.sh/community/forums/87). Toute règle ayant fait l'objet d'une discussion et
```suggestion
Les propositions de règles ainsi que les suggestions sont discutées dans le [Sous-forum Ranking Criteria](https://osu.ppy.sh/community/forums/87). Toute règle ayant fait l'objet d'une discussion et d'un processus d'approbation par la communauté est listée ici car elle a été approuvée dans le fil de discussion correspondant.
```

2022-01-24 11:08 UTC, Ganondorf-1 requested changes

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Il convient de ne pas utiliser de snapping de note de 1/8 consécutif et plus.** Ceux-ci peuvent être trop exigeants physiquement pour les joueurs de ce niveau. Une exception à cette règle serait
```suggestion
- **Il convient de ne pas utiliser de snapping de note de 1/8 consécutif et plus.** Ceux-ci peuvent être trop exigeants physiquement pour les joueurs de ce niveau. Une exception à cette règle serait l'utilisation de 3 graces qui sont à des niveaux de snaps plus élevés (1/8, 1/12 et 1/16) car elles ne sont utilisées que pour accentuer les sons des graces.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Évitez d'utiliser des chords au milieu des streams1/6.** Toutefois, l'utilisation d'un chord au début ou à la fin d'un stream est acceptable.
```suggestion
- **Évitez d'utiliser des chords au milieu des streams 1/6.** Toutefois, l'utilisation d'un chord au début ou à la fin d'un stream est acceptable.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Les long notes doivent être hold pendant au moins 1/4 de temps.**
```suggestion
- **Les long notes doivent être tenues pendant au moins 1/4 de temps.**
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Évitez les chords de plus de 4 notes.** Cela inclut les longs pattern de notes qui impliquent des notes sur plus de quatre colonnes.
```suggestion
- **Évitez les chords de plus de 4 notes.** Cela inclut les longs patterns de notes qui impliquent des notes sur plus de quatre colonnes.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Évitez les anchors composés de trois notes ou plus.** Bien qu'elles soient faciles à lire pour les joueurs, les anchors plus longues sont éprouvantes.
```suggestion
- **Évitez les anchors composés de trois notes ou plus.** Bien qu'elles soient faciles à lire pour les joueurs, les anchors plus longs sont éprouvants.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Évitez les anchors composés de cinq notes ou plus.** Bien qu'elles soient faciles à lire pour les joueurs, les anchors plus longues sont éprouvantes.
```suggestion
- **Évitez les anchors composés de cinq notes ou plus.** Bien qu'elles soient faciles à lire pour les joueurs, les anchors plus longs sont éprouvants.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Évitez les anchors composés de cinq notes ou plus.** Bien qu'elles soient faciles à lire pour les joueurs, les anchors plus longues sont éprouvantes.
```suggestion
- **Évitez les anchors composés de cinq notes ou plus.** Bien qu'elles soient faciles à lire pour les joueurs, les anchors plus longs sont éprouvants.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Évitez d'utiliser des chords au milieu des 1/8.** La densité de ces pattern est souvent trop difficile pour les joueurs de ce niveau de compétence, surtout lorsqu'ils sont utilisés sur la difficu
```suggestion
- **Évitez d'utiliser des chords au milieu des 1/8.** La densité de ces patterns est souvent trop difficile pour les joueurs de ce niveau, surtout lorsqu'ils sont utilisés sur la difficulté la plus faible d'une beatmap. De plus, un placement inefficace des chords peut entraîner une utilisation incohérente des minijacks 1/4. L'utilisation d'un chord au début ou à la fin d'un stream est acceptable.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Les hands occasionnelles peuvent être utilisées dans les streams, à condition qu'elles soient séparées par au moins une mesure (4 temps).**
```suggestion
- **Les hands peuvent être utilisés occasionnellement dans les streams, à condition qu'ils soient séparés par au moins une mesure (4 temps).**
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Il n'est pas recommandé d'utiliser les split-jumptrills pour les temps de 2 ou plus qui mènent à un hand.** À moins qu'une beatmap n'utilise fréquemment des jacks ou d'autres patterns complexes,
```suggestion
- **Il n'est pas recommandé d'utiliser les split-jumptrills pour les temps de 2 ou plus qui mènent à un hand.** À moins qu'une beatmap n'utilise fréquemment des jacks ou d'autres patterns complexes, ce pattern est difficile à jouer. Si un hand est nécessaire, supprimez la note qui la précède et qui créerait le mini jack.
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Au milieu d'un long chord stream avec un chord chaque...**
```suggestion
- **Au milieu d'un long chord stream avec un chord à chaque...**
```

2022-01-24 11:08 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Évitez les chords de plus de 3 notes.** Cela inclut les longs pattern de notes qui impliquent des notes sur plus de trois colonnes.
```suggestion
- **Évitez les chords de plus de 3 notes.** Cela inclut les longs patterns de notes qui impliquent des notes sur plus de trois colonnes.
```

2022-01-24 12:45 UTC, Biokax requested changes

2022-01-24 12:45 UTC, Biokax commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Chaque note doit correspondre à un son présent dans la musique.** Il doit s'agir d'un son distinct, mais il peut aussi représenter de manière cohérente un son continu avec un début ou une fin ind
```suggestion
- **Chaque note doit correspondre à un son présent dans la musique.** Il doit s'agir d'un son distinct, mais il peut aussi représenter de manière cohérente un son continu avec un début ou une fin indiscernable. Des exceptions à des fins de simplification doivent être faites lorsqu'il suit la musique de manière tout à fait précise...
```

2022-01-24 13:24 UTC, Biokax commented on wiki/Ranking_Criteria/osu!mania/fr.md
> +- **Chaque note doit correspondre à un son présent dans la musique.** Il doit s'agir d'un son distinct, mais il peut aussi représenter de manière cohérente un son continu avec un début ou une fin ind
je ne suis pas totalement sûr pour celui là, mais ça semble déjà plus compréhensible

2022-01-24 16:42 UTC, Walavouchey approved these changes

2022-01-24 16:44 UTC, merged