[EN/RU] Update `COT/COT2022` for the Qualifiers
ppy/osu-wiki pull request #6780
Opened 2022-01-23 16:03 UTC by Kimitakari

Also fixed minor fixes

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-23 17:46 UTC, TicClick approved these changes
нормально

2022-01-24 01:33 UTC, Bazzadwarf requested changes
Fixes failing check due to incorrect list indentation.

2022-01-24 01:33 UTC, Bazzadwarf commented on wiki/Tournaments/COT/2022/en.md
> +2. [XX:me - Torikago (Mordred) \[Dakini's Insane\]](https://osu.ppy.sh/beatmapsets/764067#fruits/1624401)
```suggestion
- NoMod
  1. [Koinata Miho, Jougasaki Mika, Hayami Kanade - Twintail no Kaze (Spectator) \[Collab Overdose\]](https://osu.ppy.sh/beatmapsets/1328225#fruits/2751483)
  2. [BESTie - Excuse Me (Euny) \[ShadrEuny's Ex\]](https://osu.ppy.sh/beatmapsets/423925#fruits/915925)
- Hidden
  1. [A-One feat. Shihori - Magic Girl !! (Greaper) \[Deif's Rain\]](https://osu.ppy.sh/beatmapsets/1644488#fruits/3356804)
  2. [Jenny Rom - The Game of Love (E=MC2) Mix (ztrot) \[Insane\]](https://osu.ppy.sh/beatmapsets/14412#fruits/52741)
- HardRock
  1. [Lime - Chronomia (Rocma) \[Rain\]](https://osu.ppy.sh/beatmapsets/1471328#fruits/3207951)
  2. [Helblinde - Above the Clouds ([ Rizen ]) \[Timeless\]](https://osu.ppy.sh/beatmapsets/344252#fruits/785162)
- DoubleTime
  1. [ZUTOMAYO - Humanoid (Jemzuu) \[Imai Lisa & Du5t's Platter\]](https://osu.ppy.sh/beatmapsets/1052572#fruits/2241108)
  2. [XX:me - Torikago (Mordred) \[Dakini's Insane\]](https://osu.ppy.sh/beatmapsets/764067#fruits/1624401)
```

2022-01-24 01:33 UTC, Bazzadwarf commented on wiki/Tournaments/COT/2022/ru.md
> +2. [XX:me - Torikago (Mordred) \[Dakini's Insane\]](https://osu.ppy.sh/beatmapsets/764067#fruits/1624401)
```suggestion
- NoMod
  1. [Koinata Miho, Jougasaki Mika, Hayami Kanade - Twintail no Kaze (Spectator) \[Collab Overdose\]](https://osu.ppy.sh/beatmapsets/1328225#fruits/2751483)
  2. [BESTie - Excuse Me (Euny) \[ShadrEuny's Ex\]](https://osu.ppy.sh/beatmapsets/423925#fruits/915925)
- Hidden
  1. [A-One feat. Shihori - Magic Girl !! (Greaper) \[Deif's Rain\]](https://osu.ppy.sh/beatmapsets/1644488#fruits/3356804)
  2. [Jenny Rom - The Game of Love (E=MC2) Mix (ztrot) \[Insane\]](https://osu.ppy.sh/beatmapsets/14412#fruits/52741)
- HardRock
  1. [Lime - Chronomia (Rocma) \[Rain\]](https://osu.ppy.sh/beatmapsets/1471328#fruits/3207951)
  2. [Helblinde - Above the Clouds ([ Rizen ]) \[Timeless\]](https://osu.ppy.sh/beatmapsets/344252#fruits/785162)
- DoubleTime
  1. [ZUTOMAYO - Humanoid (Jemzuu) \[Imai Lisa & Du5t's Platter\]](https://osu.ppy.sh/beatmapsets/1052572#fruits/2241108)
  2. [XX:me - Torikago (Mordred) \[Dakini's Insane\]](https://osu.ppy.sh/beatmapsets/764067#fruits/1624401)
```

2022-01-24 01:37 UTC, Walavouchey approved these changes

2022-01-24 01:42 UTC, merged