[FR] Add `Ranking_Criteria`
ppy/osu-wiki pull request #6782
Opened 2022-01-23 17:30 UTC by DoryanR

Proposal to add the French translation of the wiki page `Ranking_Criteria`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-23 17:31 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **osu!pixel :** La plus petite dimension de l'onglet de conception. Apparaît dans le coin supérieur droit de l'écran de l'éditeur, par exemple "x : 104 ; y : 88`.
```suggestion
- **osu!pixel :** La plus petite dimension de l'onglet de conception. Apparaît dans le coin supérieur droit de l'écran de l'éditeur, par exemple "x : 104 ; y : 88`".
```

2022-01-23 17:32 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **osu!pixel :** La plus petite dimension de l'onglet de conception. Apparaît dans le coin supérieur droit de l'écran de l'éditeur, par exemple "x : 104 ; y : 88`".
```suggestion
- **osu!pixel :** La plus petite dimension de l'onglet de conception. Apparaît dans le coin supérieur droit de l'écran de l'éditeur, par exemple `x : 104 ; y : 88`.
```

2022-01-23 17:32 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **Lors du skinning des [éléments de jeu] (/wiki/Ranking_Criteria/Skin_Set_List), des ensembles complets d'éléments doivent être skinnée afin d'éviter les conflits entre les skins spécifiques à l'ut
```suggestion
- **Lors du skinning des [éléments de jeu](/wiki/Ranking_Criteria/Skin_Set_List), des ensembles complets d'éléments doivent être skinnée afin d'éviter les conflits entre les skins spécifiques à l'utilisateur et ceux spécifiques à la beatmap.** Lors du skinning d'un élément marqué comme facultatif, vous devez inclure tous les éléments requis du jeu respectif, mais vous êtes libre d'ignorer les autres éléments facultatifs à moins qu'ils ne soient regroupés avec l'élément que vous skinnez. Toutefois, si un élément de skinning obligatoire d'un ensemble n'est pas utilisé ou si le skin par défaut est forcé, il n'est pas nécessaire d'inclure cet élément.
```

2022-01-23 17:34 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **Les beatmaps doivent être parfaitement timé.** Cela signifie que le [BPM](/wiki/Beatmapping/Beats_par_minute) et l'[offset](/wiki/Beatmapping/Offset) sont exactement synchronisés avec la chanson.
```suggestion
- **Les beatmaps doivent être parfaitement timé.** Cela signifie que le [BPM](/wiki/Beatmapping/Beats_per_minute) et l'[offset](/wiki/Beatmapping/Offset) sont exactement synchronisés avec la chanson. Les beatmaps dont le BPM change constamment peuvent être impossibles à timer parfaitement et doivent être aussi précis que possible sans affecter négativement la jouabilité. Un timing complexe pendant les breaks ou les spinners est facultatif.
```

2022-01-23 17:34 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **Les [points de timing non hérités](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doivent être les mêmes dans toutes les difficultés d'une beatmap.** Chaque point doit avoir le
```suggestion
- **Les [points de timing non hérités](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doivent être les mêmes dans toutes les difficultés d'une beatmap.** Chaque point doit avoir le même [BPM](/wiki/Beatmapping/Beats_per_minute) et [offset](/wiki/Beatmapping/Offset) dans chaque difficulté.
```

2022-01-23 17:34 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +  - Être snapped par un changement temporaire du [BPM](/wiki/Beatmapping/Beats_par_minute).
```suggestion
  - Être snapped par un changement temporaire du [BPM](/wiki/Beatmapping/Beats_per_minute).
```

2022-01-23 17:34 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **Le fichier audio d'une musique ne doit pas être allongé artificiellement afin de respecter une limite de temps dans la section "beatmap" de ces critères.** Cela peut inclure (sans s'y limiter) la
```suggestion
- **Le fichier audio d'une musique ne doit pas être allongé artificiellement afin de respecter une limite de temps dans la section "beatmap" de ces critères.** Cela peut inclure (sans s'y limiter) la mise en boucle de sections du fichier audio, la réduction du [BPM](/wiki/Beatmapping/Beats_per_minute) de la musique ou d'une section de la musique, ou l'ajout de petites quantités de musique à la musique sans l'incorporer dans toute la musique. Cela ne s'applique pas aux [compilations de musiques](/wiki/Beatmapping/Song_compilation) ou aux fichiers audio dont la longueur est inférieure à la longueur minimale de la beatmap classée.
```

2022-01-26 06:14 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +**N'oubliez pas que le [code de conduite pour le modding et le mapping](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping), le guide sur le [timing des musiques avec des signatures en #/8](/wiki/Ra
```suggestion
**N'oubliez pas que le [code de conduite pour le modding et le mapping](/wiki/Rules/Code_of_Conduct_for_Modding_and_Mapping), ainsi que les [règles générales relatives au contenu des musiques](/wiki/Rules/Song_Content_Rules) font partie des critères de classement et s'appliquent à tous les modes de jeu.**
```

2022-01-26 06:14 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **Les [points de timing non hérités](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doivent être utilisés pour mapper avec précision les signatures temporelles de la musique.** Si
```suggestion
- **Les [points de timing non hérités](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doivent être utilisés pour mapper avec précision les signatures temporelles de la musique.** Si une signature temporelle incorrecte dure plus d'une mesure, un point de temps non hérité doit être ajouté sur le prochain downbeat pour réinitialiser la signature temporelle. Pour les signatures #/4 non supportées par l'éditeur, les réinitialisations du métronome ou l'édition du fichier `.osu` sont acceptables. Pour les autres signatures temporelles non prises en charge, reportez-vous à ce [tableau exemplaire](/wiki/shared/timing/Timing_signature_reference_chart.png), et consultez [ce guide](/wiki/Guides/Timing_Songs_With_8-Signatures) pour plus d'informations.
```

2022-02-03 16:51 UTC, Biokax requested changes
I just taked 2 hours to review this lol

2022-02-03 16:51 UTC, Biokax commented on wiki/Ranking_Criteria/fr.md
> +- **Les éléments skinnée ne peuvent pas dépasser les dimensions au point de chevaucher d'autres éléments de skinning qu'ils ne chevaucheraient pas normalement dans le skin par défaut.** Cela ne s'app
```suggestion
- **Les éléments skinnés ne peuvent pas dépasser les dimensions au point de chevaucher d'autres éléments de skinning qu'ils ne chevaucheraient pas normalement dans le skin par défaut.** Cela ne s'applique qu'aux parties visibles d'une image, qui pourraient fausser l'expérience de jeu en obstruant visuellement des éléments normalement visibles.
```

2022-02-03 20:00 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les [difficultés des invités](/wiki/Beatmap/Guest_difficulty), des créateurs, storyboarders, skinners et hitsounders doivent être ajoutés aux tags d'une beatmap.** Il s'agit de rendre à César ce
```suggestion
- **Les créateurs des [guest difficulties](/wiki/Beatmap/Guest_difficulty), storyboarders, skinners et hitsounders doivent être ajoutés aux tags d'une beatmap.** Il s'agit de rendre à César ce qui appartient à César et d'aider les autres à identifier les principaux contributeurs d'une beatmap. Les noms d'utilisateur contenant des caractères uniques séparés par des espaces doivent être remplacés par des underscores.
```

2022-02-03 20:00 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les [source de métadonnées primaire](/wiki/Beatmap/Primary_metadata_source) doivent être utilisées comme références pour les métadonnées.** Ne modifiez pas les métadonnées des sources primaires,
```suggestion
- **Les [sources de métadonnées primaire](/wiki/Beatmap/Primary_metadata_source) doivent être utilisées comme références pour les métadonnées.** Ne modifiez pas les métadonnées des sources primaires, sauf pour respecter les règles de formatage et de normalisation ci-dessous. Si aucune source n'est disponible, utilisez ce qui est le plus courant et le plus reconnaissable.
```

2022-02-03 20:02 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +  - Le terme `osu!` lui-même ne doit jamais être utilisé dans le champ source, sauf dans les cas où la piste a été spécifiquement créée pour osu! (également connu sous le nom *osu! original*), comme
```suggestion
  - Le terme `osu!` lui-même ne doit jamais être utilisé dans le champ source, sauf dans les cas où la piste a été spécifiquement créée pour osu! (également connu sous le nom *osu! original*), comme les musiques de tiebreaker de tournois commandées.
```

2022-02-03 20:03 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les tags doivent être liées à la beatmap et ne pas induire en erreur pour les résultats de recherche.** Les tags décrivant le style, la musique, le storyboard, la vidéo ou l'arrière-plan de la be
```suggestion
- **Les tags doivent être liés à la beatmap et ne pas induire en erreur pour les résultats de recherche.** Les tags décrivant le style, la musique, le storyboard, la vidéo ou l'arrière-plan de la beatmap sont considérées comme liés à la beatmap.
```

2022-02-03 20:04 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Si une musique est utilisée dans un programme de télévision, une série web ou une série en vidéo directe, comme une musique d'ouverture/fin/insertion, utilisez un marqueur `(TV Size)` à la fin du
```suggestion
- **Si une musique est utilisée dans un programme de télévision, une série web ou une série en vidéo directe, comme une musique d'ouverture/fin/insertion, utilisez un marqueur `(TV Size)` à la fin du titre actuel.** S'il y a un marqueur TV Size existant dans le titre, remplacez-le par `(TV Size)`.
```

2022-02-03 20:05 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les versions coupées non officielles des musiques doivent ajouter un marqueur `(Cut Ver.)` à la fin du titre courant.** Si un marqueur de longueur figure déjà dans le titre du morceau, `(Cut Ver.
```suggestion
- **Les versions coupées non officielles des musiques doivent ajouter un marqueur `(Cut Ver.)` à la fin du titre.** Si un marqueur de longueur figure déjà dans le titre du morceau, `(Cut Ver.)` le remplacera. Cela permet de distinguer les coupures non officielles d'une musique des versions complètes. Les musiques qui sont raccourcies d'une manière qui correspond presque à leur version officielle, et les musiques qui sont une boucle complète d'une piste en boucle ne seront pas considérées comme coupées.
```

2022-02-03 20:07 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Si une série applicable comme source contient des sous-séries, le tag le plus précis doit être utilisée comme source.** Si une musique a plusieurs sous-séries applicables, la série/franchise prin
```suggestion
- **Si une série applicable comme source contient des sous-séries, le tag le plus précis doit être utilisé comme source.** Si une musique a plusieurs sous-séries applicables, la série/franchise principale peut être utilisée à la place.
```

2022-02-03 20:09 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Si le créateur de la beatmap a remixé ou repris la musique, il est libre de lui donner un nom approprié pour signaler que cette musique est une version spéciale.** Dans ce cas, les chansons origi
```suggestion
- **Si le créateur de la beatmap a remixé ou repris la musique, il est libre de lui donner un nom approprié pour signaler que cette musique est une version spéciale.** Dans ce cas, les chansons originales doivent toujours être clairement indiquées dans le titre ou les tags afin que les joueurs puissent les rechercher.
```

2022-02-03 20:11 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Pour les musiques où le(s) compositeur(s) et le(s) chanteur(s) sont des personnes différentes, le(s) chanteur(s) peut(vent) être listé(s) après le(s) compositeur(s) ou le nom du cercle/groupe apr
```suggestion
- **Pour les musiques où les compositeurs et les chanteurs sont des personnes différentes, les chanteurs peuvent être listés après les compositeurs ou le nom du cercle/groupe après un indicateur `feat.`.**
```

2022-02-03 20:12 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Si la musique d'une beatmap a été réalisée par plusieurs artistes, ils peuvent être listés avec des virgules entre eux.** S'il y a trois artistes ou plus qui contribuent et qu'ils ne font pas par
```suggestion
- **Si la musique d'une beatmap a été réalisée par plusieurs artistes, ils peuvent être listés avec des virgules entre eux.** S'il y a trois artistes ou plus qui contribuent et qu'ils ne font pas partie d'un groupe officiellement étiqueté, `Various Artists` ou d'autres tags d'artistes descriptifs peuvent être utilisés à la place.
```

2022-02-03 20:13 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les [points de timing non hérités](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doivent être utilisés pour mapper avec précision les signatures temporelles de la musique.** Si
```suggestion
- **Les [points de timing non hérités](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doivent être utilisés pour mapper avec précision les signatures temporelles de la musique.** Si une signature temporelle incorrecte dure plus d'une mesure, un point de timing non hérité doit être ajouté sur le prochain downbeat pour réinitialiser la signature temporelle. Pour les signatures #/4 non prises en charge par l'éditeur, les réinitialisations du métronome ou l'édition du fichier `.osu` sont acceptables. Pour les autres signatures temporelles non prises en charge, reportez-vous à ce [tableau exemplaire](/wiki/shared/timing/Timing_signature_reference_chart.png), et consultez [ce guide](/wiki/Guides/Timing_Songs_With_8-Signatures) pour plus d'informations.
```

2022-02-03 20:13 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les beatmaps doivent être parfaitement timé.** Cela signifie que le [BPM](/wiki/Beatmapping/Beats_per_minute) et l'[offset](/wiki/Beatmapping/Offset) sont exactement synchronisés avec la chanson.
```suggestion
- **Les beatmaps doivent avoir un timing parfait.** Cela signifie que le [BPM](/wiki/Beatmapping/Beats_per_minute) et l'[offset](/wiki/Beatmapping/Offset) sont exactement synchronisés avec la musique. Les beatmaps dont le BPM change constamment peuvent être impossibles à timer parfaitement et doivent être aussi précis que possible sans affecter négativement la jouabilité. Un timing complexe pendant les breaks ou les spinners est facultatif.
```

2022-02-03 20:16 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les beatmaps doivent être hitsoundée.** Les hitnormal donnent un feedback au joueur, et les ajouts (whistles, claps, et finishes) accentuent les parties les plus importantes de la musique.
```suggestion
- **Les beatmaps doivent avoir des hitsounds.** Les hitnormal donnent un feedback au joueur, et les ajouts (whistles, claps, et finishes) accentuent les parties les plus importantes de la musique.
```

2022-02-03 20:20 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les [compilations de musiques](/wiki/Beatmapping/Song_compilation) doivent être mixées correctement et ne doivent pas comporter de coupures brusques ou de longs fondus entre les différentes musiq
```suggestion
- **Les [compilations de musiques](/wiki/Beatmapping/Song_compilation) doivent être mixées correctement et ne doivent pas comporter de coupures brusques ou de longs fondus entre les différentes musiques.** Les musiques utilisées pour la compilation doivent être similaires en termes de qualité audio, de volume et de durée. Ceci afin de garantir que les compilations offrent la même expérience de jeu que les autres beatmaps.
```

2022-02-03 20:20 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les [sons de jeu](/wiki/Skinning/Sounds#gameplay) à l'exception des [hitsounds actifs](/wiki/Beatmapping/Hitsound#hitsound-actif) doivent utiliser les formats de fichier `.mp3` ou `.ogg`.** Ces f
```suggestion
- **Les [sons de gameplay](/wiki/Skinning/Sounds#gameplay) à l'exception des [hitsounds actifs](/wiki/Beatmapping/Hitsound#hitsound-actif) doivent utiliser les formats de fichier `.mp3` ou `.ogg`.** Ces fichiers ont généralement de longues durées et les fichiers .wav sont inutilement volumineux en comparaison, mais les fichiers .wav doivent être utilisés lorsqu'ils permettent d'obtenir une taille de fichier plus petite.
```

2022-02-03 20:23 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Évitez de remplacer la finition des hits dans les jeux d'échantillons soft/normal par des échantillons de hits personnalisés fréquemment utilisés.** L'utilisation de ces finitions pour représente
```suggestion
- **Évitez de remplacer le hit finish des samplesets soft/normal par des samplesets personnalisés fréquemment utilisés.** L'utilisation de ces finish pour représenter des drums snare/bass ou la mélodie d'une musique peut sonner de façon désagréable pour toute personne désactivant les hitsounds des beatmaps. Il est recommandé de remplacer les hits whistle/clap parce que ces échantillons sont utilisés plus souvent. Les beatmaps osu!taiko sont exemptes de cette directive et ont leur propre directive d'échantillon de hitsound spécifique au mode.
```

2022-02-03 20:23 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Vous devez avoir un arrière-plan sur chaque difficulté de votre beatmap.** Des arrière-plan différents pour des difficultés différentes sont acceptables.
```suggestion
- **Vous devez avoir un arrière-plan sur chaque difficulté de votre beatmap.** Des arrière-plans différents pour des difficultés différentes sont acceptables.
```

2022-02-03 20:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Le [offset](/wiki/Beatmapping/Offset) d'une vidéo doit être correct s'il est timer avec la musique.** Un offset incorrect peut donner lieu à une représentation visuelle trompeuse de la chanson. S
```suggestion
- **L'[offset](/wiki/Beatmapping/Offset) d'une vidéo doit être correct s'il est en rythme avec la musique.** Un offset incorrect peut donner lieu à une représentation visuelle trompeuse de la chanson. Si la même vidéo apparaît dans plusieurs difficultés, elle doit toujours avoir le même offset.
```

2022-02-03 20:25 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Les [éléments de jeu](/wiki/Ranking_Criteria/Skin_Set_List) doivent être visibles.** Vous ne pouvez pas rendre invisible un élément qui nuirait à la jouabilité de la beatmap car cela rendrait la
```suggestion
- **Les [éléments de gameplay](/wiki/Ranking_Criteria/Skin_Set_List) doivent être visibles.** Vous ne pouvez pas rendre invisible un élément qui nuirait à la jouabilité de la beatmap car cela rendrait la beatmap peu intuitive ou même impossible à jouer (`cursormiddle.png` est une exception car il affecte le comportement de la traînée du curseur). Les éléments qui ne sont pas pertinents pour le gameplay ne peuvent être transparents que s'il y a une raison valable pour cela et si l'action elle-même ne nuit pas à l'utilisation des éléments de l'interface.
```

2022-02-03 20:26 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Lors du skinning des [éléments de jeu](/wiki/Ranking_Criteria/Skin_Set_List), des ensembles complets d'éléments doivent être skinnés afin d'éviter les conflits entre les skins spécifiques à l'uti
```suggestion
- **Lors du skinning des [éléments de gameplay](/wiki/Ranking_Criteria/Skin_Set_List), des ensembles complets d'éléments doivent être skinnés afin d'éviter les conflits entre les skins spécifiques à l'utilisateur et ceux spécifiques à la beatmap.** Lors du skinning d'un élément marqué comme facultatif, vous devez inclure tous les éléments requis de l'ensemble respectif, mais vous êtes libre d'ignorer les autres éléments facultatifs à moins qu'ils ne soient regroupés avec l'élément que vous skinnez. Toutefois, si un élément de skinning obligatoire d'un ensemble n'est pas utilisé ou si le skin par défaut est forcé, il n'est pas nécessaire d'inclure cet élément.
```

2022-02-03 20:28 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Rendered :** Se réfère souvent à un sprite à l'écran qui n'est pas complètement effacé.
```suggestion
- **Rendered :** Se réfère souvent à un sprite à l'écran qui n'a pas complètement disparu.
```

2022-02-03 20:32 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Pensez à laisser une bordure de transparence d'un pixel autour des images de storyboard des sprites tournés pour que l'interpolation fonctionne correctement.** osu! n'utilise pas l'anticrénelage
```suggestion
- **Pensez à laisser une bordure de transparence d'un pixel autour des images de storyboard des sprites retournés pour que l'interpolation fonctionne correctement.** osu! n'utilise pas l'anticrénelage autour des images, et en tant que tel, cela devient très visible si les bords sont visibles et que le sprite est retourné.
```

2022-02-03 20:36 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +  - **Suppression des sprites activés par les déclencheurs après utilisation.** Les déclencheurs s'activent dès leur première commande possible et restent actifs jusqu'à la fin de la difficulté, c'es
```suggestion
  - **Suppression des sprites activés par les déclencheurs après utilisation.** Les déclencheurs s'activent dès leur première commande possible et restent actifs jusqu'à la fin de la difficulté, c'est pourquoi il est préférable de les faire disparaître lorsqu'ils sont terminés.
```

2022-02-03 20:40 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +  - Les plus hautes difficultés de chaque mode de jeu avec un niveau de difficulté similaire, s'appliquant uniquement aux difficultés Insane et Extra (par exemple, les difficultés Insane d'un jeu ENH
```suggestion
  - Les plus hautes difficultés de chaque mode de jeu avec un niveau de difficulté similaire, s'appliquant uniquement aux difficultés Insane et Extra (par exemple, les difficultés Insane d'une beatmap ENHIIII ou les difficultés Extra d'une beatmap ENHIIXXX).
```

2022-02-03 21:12 UTC, Biokax approved these changes

2022-02-03 21:31 UTC, Walavouchey requested changes

2022-02-03 21:31 UTC, Walavouchey commented on wiki/Ranking_Criteria/fr.md
> +- **Les [hitsounds actifs](/wiki/Beatmapping/Hitsound#hitsound-actif) ne peuvent avoir un délai supérieur à 5 millisecondes.** "Le "Delay" prend en compte le pic d'un son plutôt que son introduction.
Still needs to be updated according to https://github.com/ppy/osu-wiki/pull/6828

2022-02-04 08:22 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **Les [hitsounds actifs](/wiki/Beatmapping/Hitsound#hitsound-actif) ne peuvent avoir un délai supérieur à 5 millisecondes.** "Le "Delay" prend en compte le pic d'un son plutôt que son introduction.
```suggestion
**Toutes les parties cliquées des objets doivent avoir au moins un hitsound qui à la fois...**
  - **...a un impact clair, dont le pic n'est pas retardé de plus de 5 millisecondes.** `normal-hitfinish.wav` du skin par défaut en est exempté.
  - **...utilise le format de fichier `.wav` ou `.ogg`.** `.mp3` ne doit pas être utilisé ici car il est retardé.
  - Cela garantit un retour audible instantané lorsque l'on clique sur des objets, en se synchronisant avec la musique d'une manière qui permet aux joueurs de déterminer s'ils cliquent tôt ou tard. osu!mania est exempté de cette règle en raison de ses objets simultanés.
```

2022-02-04 08:26 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +  - Cela garantit un retour audible instantané lorsque l'on clique sur des objets, en se synchronisant avec la musique d'une manière qui permet aux joueurs de déterminer s'ils cliquent tôt ou tard. o
```suggestion
- **Toutes les parties cliquées des objets doivent avoir au moins un hitsound qui à la fois...**
  - **...a un impact clair, dont le pic n'est pas retardé de plus de 5 millisecondes.** `normal-hitfinish.wav` du skin par défaut en est exempté.
  - **...utilise le format de fichier `.wav` ou `.ogg`.** `.mp3` ne doit pas être utilisé ici car il est retardé.
  - Cela garantit un retour audible instantané lorsque l'on clique sur des objets, en se synchronisant avec la musique d'une manière qui permet aux joueurs de déterminer s'ils cliquent tôt ou tard. osu!mania est exempté de cette règle en raison de ses objets simultanés.
```

2022-02-04 08:39 UTC, Biokax requested changes

2022-02-04 08:39 UTC, Biokax commented on wiki/Ranking_Criteria/fr.md
> +  - **...utilise le format de fichier `.wav` ou `.ogg`.** `.mp3` ne doit pas être utilisé ici car il est retardé.
```suggestion
  - **...utilise le format de fichier `.wav` ou `.ogg`.** Le `.mp3` ne doit pas être utilisé ici car il est retardé.
```

2022-02-04 09:33 UTC, Biokax submitted a review, later dismissed

2022-02-04 18:31 UTC, Walavouchey commented on wiki/Ranking_Criteria/fr.md
> +- **Les [storyboarded hitsounds](/wiki/Beatmapping/Hitsound#storyboarded-hitsound) ne peuvent pas être utilisés en remplacement des [hitsounds actifs](/wiki/Beatmapping/Hitsound#hitsound-actif).** Ce
```suggestion
- **Les [hitsounds storyboardés](/wiki/Beatmapping/Hitsound#hitsound-storyboardé) ne peuvent pas être utilisés en remplacement des [hitsounds actifs](/wiki/Beatmapping/Hitsound#hitsound-actif).** Ceux-ci donnent une forme inexacte de feedback au joueur. Les hitsounds storyboardés dans d'autres situations sont acceptables, mais découragés. osu!mania est exempt de cette règle.
```

2022-02-04 18:31 UTC, Walavouchey commented on wiki/Ranking_Criteria/fr.md
> +- **Le paramètre `Support écran large` doit être cohérent entre les difficultés storyboardées d'une beatmap,** à moins que des storyboards spécifiques aux difficultés ne soient conçus pour différents
this isn't translated in-game

```suggestion
- **Le paramètre `Widescreen Support` doit être cohérent entre les difficultés storyboardées d'une beatmap,** à moins que des storyboards spécifiques aux difficultés ne soient conçus pour différents rapports d'aspect.
```

2022-02-05 19:24 UTC, Walavouchey approved these changes

2022-02-05 19:25 UTC, Walavouchey commented
probably better to get this in instead of adding the new rc pr as a dependency

2022-02-05 19:26 UTC, merged