[FR] Add `Ranking_Criteria\Skin_Set_List`
ppy/osu-wiki pull request #6787
Opened 2022-01-24 20:57 UTC by DoryanR

Proposal to add the French translation of the wiki page `Ranking_Criteria\Skin_Set_List`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-05 13:34 UTC, Ganondorf-1 requested changes

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +Ce qui suit contient la liste des sets de skins qui peuvent être utiliser dans les skins spécifiques aux utilisateurs et aux beatmaps. Quand vous skinnez un élément dans un skin spécifique à une beat
```suggestion
Ce qui suit contient la liste des sets de skins qui peuvent être utilisés dans les skins spécifiques aux utilisateurs et aux beatmaps. Quand vous skinnez un élément de gameplay dans un skin spécifique à une beatmap, les sets d'éléments doivent être skinnés afin d'éviter les conflits entre le skin spécifique à l'utilisateur et le skin spécifique à la beatmap.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +Les noms des fichiers qui contiennent `(-n)` peuvent être animé. Par exemple, hitcircleoverlay(-n).png peut être skinnée comme étant une seule image (hitcircleoverlay.png), ou plusieurs images qui se
```suggestion
Les noms des fichiers qui contiennent `(-n)` peuvent être animés. Par exemple, hitcircleoverlay(-n).png peut être skinné comme étant une seule image (hitcircleoverlay.png), ou plusieurs images qui seront animées dans une boucle (hitcircleoverlay-0.png, hitcircleoverlay-1.png, hitcircleoverlay-2.png, etc.)
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +[Téléchargez le modèle de skins sets](https://assets.ppy.sh/media/wiki/BeatmapSkinTemplate.rar) pour une vue plus simple des tableaux.
```suggestion
[Téléchargez le modèle de skin sets](https://assets.ppy.sh/media/wiki/BeatmapSkinTemplate.rar) pour une vue plus simple des tableaux.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| cursormiddle.png | doit être facultatif en fonction de la conception du curseur | optionnel | - |
```suggestion
| cursormiddle.png | facultatif en fonction du curseur | optionnel | - |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderpoint10.png | doit être inclus avec sliderpoint30.png ; ne fonctionnera que si un skin spécifique à l'utilisateur supporte la version 1 du skin | optionnel | - |
```suggestion
| sliderpoint10.png | doit être inclus avec sliderpoint30.png ; ne fonctionnera que si le skin spécifique à l'utilisateur prend en charge le Skin V1 | optionnel | - |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderpoint30.png | doit être inclus avec sliderpoint10.png ; ne fonctionnera que si un skin spécifique à l'utilisateur supporte la version 1 du skin | optionnel | - |
```suggestion
| sliderpoint30.png | doit être inclus avec sliderpoint10.png ; ne fonctionnera que si le skin spécifique à l'utilisateur prend en charge le Skin V1 | optionnel | - |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| hitcircle.png | utilisé pour les slidercircles lorsqu'ils ne sont pas skinnés, ne sera pas utilisé pour les slidercircles si un skin spécifique à l'utilisateur les a skinnés. | requis | 118x118px (
```suggestion
| hitcircle.png | utilisé pour les slidercircles lorsqu'ils ne sont pas skinnés, ne sera pas utilisé pour les slidercircles si un skin spécifique à l'utilisateur les a skinnés | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| hitcircleoverlay(-n).png | utilisé pour les slidercircles lorsqu'ils ne sont pas skinnés, ne sera pas utilisé pour les slidercircles si un skin spécifique à l'utilisateur les a skinnés. | requis |
```suggestion
| hitcircleoverlay(-n).png | utilisé pour les slidercircles lorsqu'ils ne sont pas skinnés, ne sera pas utilisé pour les slidercircles si un skin spécifique à l'utilisateur les a skinnés | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderendcircle.png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur. | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```suggestion
| sliderendcircle.png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderendcircleoverlay(-n).png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur. | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```suggestion
| sliderendcircleoverlay(-n).png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderstartcircle.png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur. | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```suggestion
| sliderstartcircle.png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | requis | 118x118px (cercle) 128x128px (tout le ficher) |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderstartcircleoverlay(-n).png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur. | requis | 118x118px (cercle) / 128x128px (tout le ficher) |
```suggestion
| sliderstartcircleoverlay(-n).png | doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | requis | 118x118px (cercle) / 128x128px (tout le ficher) |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderb-nd.png | ne doit être utilisé que si le skin par défaut est imposé et qu'aucun sliderb personnalisé n'est utilisé. | optionnel | 118x118px |
```suggestion
| sliderb-nd.png | ne doit être utilisé que si le skin par défaut est imposé et qu'aucun sliderb personnalisé n'est utilisé | optionnel | 118x118px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderb-spec.png | ne doit être utilisé que si le skin par défaut est imposé et qu'aucun sliderb personnalisé n'est utilisé. | optionnel | 118x118px |
```suggestion
| sliderb-spec.png | ne doit être utilisé que si le skin par défaut est imposé et qu'aucun sliderb personnalisé n'est utilisé | optionnel | 118x118px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +En effet, le style de spinner de base aura la priorité sur le nouveau style si les deux styles sont présents. Le nouveau style de spinner ne fonctionnera que si le skin spécifique à l'utilisateur n'u
```suggestion
En effet, le style de spinner de base aura la priorité sur le nouveau style si les deux styles sont présents. Le nouveau style de spinner ne fonctionnera que si le skin spécifique à l'utilisateur n'utilise pas le style de spinner de base et prend en charge le Skin V2 ou plus, ou si le skin par défaut est forcé dans la beatmap.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| spinner-osu.png | ne fonctionnera que si un skin spécifique à l'utilisateur supporte la version 1 du skin | optionnel | - |
```suggestion
| spinner-osu.png | ne fonctionnera que si un skin spécifique à l'utilisateur prend en charge le Skin V1 | optionnel | - |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| spinner-rpm.png | doit être inclus si le set de numéro de score et le set de spinner sont skinnés. | optionnel | 280x56px |
```suggestion
| spinner-rpm.png | doit être inclus si le set des nombres du score et le set de spinner sont skinnés. | optionnel | 280x56px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| fruit-bananas.png | doit être conçu différemment des autres fruits | requis | 128x128px |
```suggestion
| fruit-bananas.png | doit avoir une apparence différente des autres fruits | requis | 128x128px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| fruit-bananas-overlay.png | doit être conçu différemment des autres fruits | requis | 128x128px |
```suggestion
| fruit-bananas-overlay.png | doit avoir une apparence différente des autres fruits | requis | 128x128px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| fruit-drop-overlay.png | doit être inclus pour garantir un affichage correct lorsqu'un skin spécifique à l'utilisateur l'a skinnée car le skin par défaut utilise une image transparente pour ce fich
```suggestion
| fruit-drop-overlay.png | doit être inclus pour garantir un affichage correct lorsqu'un skin spécifique à l'utilisateur l'a skinné car le skin par défaut utilise une image transparente pour ce fichier | requis | 82x103px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +Pour le catcher, la plaque doit être parfaitement centrée et avoir une largeur de 302px exactement. Bien que la plaque du skin par défaut ne soit pas centrée, elle peut être utilisée dans les skins s
```suggestion
Pour le catcher, l'assiette doit être parfaitement centrée et avoir une largeur de 302px exactement. Bien que l'assiette du skin par défaut ne soit pas centrée, elle peut être utilisée dans les skins spécifiques aux beatmaps.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +L'ensemble de ce skin set est pertinent pour le gameplay. Les overlaps ou les écarts entre les chiffres eux-mêmes sont définis par le skin spécifique de l'utilisateur et ne peuvent pas être influencé
```suggestion
L'ensemble de ce skin set est pertinent pour le gameplay. Les overlaps ou les écarts entre les chiffres eux-mêmes sont définis par le skin spécifique à l'utilisateur et ne peuvent pas être influencés dans la beatmap elle-même.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| inputoverlay-background.png | ne doit pas être skinnée dans les beatmaps sans difficultés osu! ou osu!catch | requis | 193x55px |
```suggestion
| inputoverlay-background.png | ne doit pas être skinné dans les beatmaps sans difficultés osu! ou osu!catch | requis | 193x55px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| inputoverlay-key.png | ne doit pas être skinnée dans les beatmaps sans difficultés osu! ou osu!catch | requis | max : 46x46px |
```suggestion
| inputoverlay-key.png | ne doit pas être skinné dans les beatmaps sans difficultés osu! ou osu!catch | requis | max : 46x46px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +L'ensemble de ce skin set est pertinent pour le gameplay. Ce skin set ne doit pas être skinnée si la beatmap n'utilise pas de compte à rebours.
```suggestion
L'ensemble de ce skin set est pertinent pour le gameplay. Ce skin set ne doit pas être skinné si la beatmap n'utilise pas de compte à rebours.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +L'ensemble de ce skin set n'est pas pertinent pour le gameplay. Ce skin set ne doit pas être skinnée si la beatmap ne contient pas de pause suffisamment longue pour que les indicateurs de section app
```suggestion
L'ensemble de ce skin set n'est pas pertinent pour le gameplay. Ce skin set ne doit pas être skinné si la beatmap ne contient pas de pause suffisamment longue pour que les indicateurs de section apparaissent.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +L'ensemble de ce skin set n'est pas pertinent pour le gameplay. Ce skin set ne doit pas être skinnée si la beatmap ne contient pas une pause suffisamment longue pour que les indicateurs de grades app
```suggestion
L'ensemble de ce skin set n'est pas pertinent pour le gameplay. Ce skin set ne doit pas être skinné si la beatmap ne contient pas une pause suffisamment longue pour que les indicateurs de grades apparaissent.
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| fail-background.png | si un arrière-plan est skinnée, l'autre doit l'être aussi, il est mis à l'échelle pour s'adapter à l'écran du joueur. | optionnel | max : 1920x1200px |
```suggestion
| fail-background.png | si un arrière-plan est skinné, l'autre doit l'être aussi, il est mis à l'échelle pour s'adapter à l'écran du joueur. | optionnel | max : 1920x1200px |
```

2022-02-05 13:34 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| pause-overlay.png | si un arrière plan est skinnée, l'autre doit l'être aussi. | optionnel | 1366x768px |
```suggestion
| pause-overlay.png | si un arrière plan est skinné, l'autre doit l'être aussi. | optionnel | 1366x768px |
```

2022-02-08 05:29 UTC, Walavouchey reviewed
Some of the notes have periods at the end and some don't, which doesn't look consistent atm. Would it be correct to remove them in all of the notes?

2022-02-08 06:52 UTC, DoryanR commented
Sure, no problem

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| cursor-smoke.png | - | optionnel | - |
```suggestion
| cursor.png | Doit toujours être inclus avec cursortrail.png | Requis | - |
| cursortrail.png | Doit toujours être inclus avec cursor.png | Requis | - |
| cursormiddle.png | Facultatif en fonction du curseur | Optionnel | - |
| cursor-smoke.png | - | Optionnel | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderpoint30.png | doit être inclus avec sliderpoint10.png ; ne fonctionnera que si le skin spécifique à l'utilisateur prend en charge le Skin V1 | optionnel | - |
```suggestion
| hit0(-n).png | Doit être clairement distingué de tous les autres hitbursts | Requis | - |
| hit50(-n).png | Doit être clairement distingué de tous les autres hitbursts | Requis | - |
| hit100(-n).png | Doit être clairement distingué de tous les autres hitbursts | Requis | - |
| hit100k(-n).png | Doit être clairement distingué de tous les autres hitbursts | Requis | - |
| hit300(-n).png | Doit être clairement distingué de tous les autres hitbursts | Requis | - |
| hit300g(-n).png | Doit être clairement distingué de tous les autres hitbursts | Requis | - |
| hit300k(-n).png | Doit être clairement distingué de tous les autres hitbursts | Requis | - |
| lighting.png | - | Optionnel | - |
| particle50.png | Doit être inclus avec toutes les autres particules ; ne fonctionnera que si des hitbursts personnalisés sont inclus | Optionnel | 7x7px |
| particle100.png | Doit être inclus avec toutes les autres particules ; ne fonctionnera que si des hitbursts personnalisés sont inclus | Optionnel | 7x7px |
| particle300.png | Doit être inclus avec toutes les autres particules ; ne fonctionnera que si des hitbursts personnalisés sont inclus | Optionnel | 7x7px |
| sliderpoint10.png | Doit être inclus avec sliderpoint30.png ; ne fonctionnera que si le skin spécifique à l'utilisateur prend en charge le Skin V1 | Optionnel | - |
| sliderpoint30.png | Doit être inclus avec sliderpoint10.png ; ne fonctionnera que si le skin spécifique à l'utilisateur prend en charge le Skin V1 | Optionnel | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| hitcircleselect.png | seulement vu dans l'éditeur | optionnel | 118x118px (cercle) 128x128px (tout le ficher) |
```suggestion
| approachcircle.png | - | Requis | 126x126px |
| followpoint.png | - | Requis | - |
| hitcircle.png | Utilisé pour les slidercircles lorsqu'ils ne sont pas skinnés, ne sera pas utilisé pour les slidercircles si un skin spécifique à l'utilisateur les a skinnés | Requis | 118x118px (cercle) 128x128px (tout le ficher) |
| hitcircleoverlay(-n).png | Utilisé pour les slidercircles lorsqu'ils ne sont pas skinnés, ne sera pas utilisé pour les slidercircles si un skin spécifique à l'utilisateur les a skinnés | Requis | 118x118px (cercle) 128x128px (tout le ficher) |
| reversearrow.png | Doit être orienté vers la droite | Requis | - |
| sliderendcircle.png | Doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | Requis | 118x118px (cercle) 128x128px (tout le ficher) |
| sliderendcircleoverlay(-n).png | Doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | Requis | 118x118px (cercle) 128x128px (tout le ficher) |
| sliderstartcircle.png | Doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | Requis | 118x118px (cercle) 128x128px (tout le ficher) |
| sliderstartcircleoverlay(-n).png | Doit toujours être inclus pour éviter tout conflit avec les skins spécifiques à l'utilisateur | Requis | 118x118px (cercle) / 128x128px (tout le ficher) |
| hitcircleselect.png | Seulement vu dans l'éditeur | Optionnel | 118x118px (cercle) 128x128px (tout le ficher) |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| sliderscorepoint.png | également utilisé dans osu!taiko | requis | - |
```suggestion
| sliderb(n).png | - | Requis | 118x118px |
| sliderb-nd.png | Ne doit être utilisé que si le skin par défaut est imposé et qu'aucun sliderb personnalisé n'est utilisé | Optionnel | 118x118px |
| sliderb-spec.png | Ne doit être utilisé que si le skin par défaut est imposé et qu'aucun sliderb personnalisé n'est utilisé | Optionnel | 118x118px |
| sliderfollowcircle(-n).png | - | Requis | 256x256px |
| sliderscorepoint.png | Également utilisé dans osu!taiko | Requis | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| default-9.png | - | requis | - |
```suggestion
| default-0.png | - | Requis | - |
| default-1.png | - | Requis | - |
| default-2.png | - | Requis | - |
| default-3.png | - | Requis | - |
| default-4.png | - | Requis | - |
| default-5.png | - | Requis | - |
| default-6.png | - | Requis | - |
| default-7.png | - | Requis | - |
| default-8.png | - | Requis | - |
| default-9.png | - | Requis | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| spinner-rpm.png | doit être inclus si le set des nombres du score et le set de spinner sont skinnés. | optionnel | 280x56px |
```suggestion
| spinner-background.png | Style de base du spinner | Requis | - |
| spinner-circle.png | Style de base du spinner | Requis | 666x666px |
| spinner-metre.png | Style de base du spinner | Requis | 1024x692px |
| spinner-bottom.png | Nouveau style de spinner | Requis | 667x667px |
| spinner-glow.png | Nouveau style de spinner | Requis | 852x852px |
| spinner-middle.png | Nouveau style de spinner | Requis | 689x689px |
| spinner-middle2.png | Nouveau style de spinner | Requis | 17x17px |
| spinner-top.png | Nouveau style de spinner | Requis | 667x667px |
| spinner-approachcircle.png | Utilisé par les deux sets | Requis | 384x384px |
| spinner-clear.png | - | Requis | - |
| spinner-spin.png | - | Requis | - |
| spinner-osu.png | Ne fonctionnera que si un skin spécifique à l'utilisateur prend en charge le Skin V1 | Optionnel | - |
| spinner-rpm.png | Doit être inclus si le set des nombres du score et le set de spinner sont skinnés | Optionnel | 280x56px |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| spinner-warning.png | - | requis | - |
```suggestion
| taikobigcircle.png | - | Requis | 118x118px |
| taikobigcircleoverlay(-n).png | - | Requis | 118x118px |
| taikohitcircle.png | - | Requis | 118x118px |
| taikohitcircleoverlay(-n).png | - | Requis | 118x118px |
| sliderscorepoint.png | Ne doit être utilisé que sur les beatmaps sans difficultés osu! (image partagée) | Requis | - |
| taiko-roll-middle.png | Est étiré pour remplir le rouleau | Requis | 1x118px (ligne) 1x128px (tout le ficher) |
| taiko-roll-end.png | La moitié droite d'un cercle | Requis | 59x118px (demi-cercle) 64x128px (tout le ficher) |
| spinner-warning.png | - | Requis | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| taiko-hit300k(-n).png | - | requis | - |
```suggestion
| taiko-hit0(-n).png | - | Requis | - |
| taiko-hit100(-n).png | - | Requis | - |
| taiko-hit100k(-n).png | - | Requis | - |
| taiko-hit300(-n).png | - | Requis | - |
| taiko-hit300k(-n).png | - | Requis | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| taiko-flower-group(-n).png | les combobursts dans osu!taiko | optionnel | - |
```suggestion
| pippidonclear(n).png | - | Requis | - |
| pippidonfail(n).png | - | Requis | - |
| pippidonidle(n).png | - | Requis | - |
| pippidonkiai(n).png | - | Requis | - |
| taiko-flower-group(-n).png | Les combobursts dans osu!taiko | Optionnel | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| fruit-drop-overlay.png | doit être inclus pour garantir un affichage correct lorsqu'un skin spécifique à l'utilisateur l'a skinné car le skin par défaut utilise une image transparente pour ce fichi
```suggestion
| fruit-apple.png | - | Requis | 128x128px |
| fruit-apple-overlay.png | - | Requis | 128x128px |
| fruit-grapes.png | - | Requis | 128x128px |
| fruit-grapes-overlay.png | - | Requis | 128x128px |
| fruit-orange.png | - | Requis | 128x128px |
| fruit-orange-overlay.png | - | Requis | 128x128px |
| fruit-pear.png | - | Requis | 128x128px |
| fruit-pear-overlay.png | - | Requis | 128x128px |
| fruit-bananas.png | Doit avoir une apparence différente des autres fruits | Requis | 128x128px |
| fruit-bananas-overlay.png | Doit avoir une apparence différente des autres fruits | Requis | 128x128px |
| fruit-drop.png | - | Requis | 82x103px |
| fruit-drop-overlay.png | Doit être inclus pour garantir un affichage correct lorsqu'un skin spécifique à l'utilisateur l'a skinné car le skin par défaut utilise une image transparente pour ce fichier | Requis | 82x103px |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| lighting.png | ne doit être utilisé que sur les beatmaps sans difficultés osu! (image partagée) | optionnel | - |
```suggestion
| fruit-catcher-fail(-n).png | Doit être orienté vers la droite | Requis | Minimum 302px de large |
| fruit-catcher-idle(-n).png | Doit être orienté vers la droite | Requis | Minimum 302px de large |
| fruit-catcher-kiai(-n).png | Doit être orienté vers la droite | Requis | Minimum 302px de large |
| lighting.png | Ne doit être utilisé que sur les beatmaps sans difficultés osu! (image partagée) | Optionnel | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| scorebar-marker.png | doit être inclus pour garantir l'affichage correct du ki et peut être un fichier vide. | requis | - |
```suggestion
| scorebar-bg.png | Doit être inclus avec scorebar-colour(-n).png | Requis | - |
| scorebar-colour(-n).png | Doit être inclus avec scorebar-bg.png | Requis | maximum 120px |
| scorebar-ki.png | - | Requis | - |
| scorebar-kidanger.png | - | Requis | - |
| scorebar-kidanger2.png | - | Requis | - |
| scorebar-marker.png | Doit être inclus pour garantir l'affichage correct du ki et peut être un fichier vide | Requis | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| score-x.png | peut être laissé de côté sur les beatmaps sans difficultés osu! | requis | - |
```suggestion
| score-0.png | - | Requis | - |
| score-1.png | - | Requis | - |
| score-2.png | - | Requis | - |
| score-3.png | - | Requis | - |
| score-4.png | - | Requis | - |
| score-5.png | - | Requis | - |
| score-6.png | - | Requis | - |
| score-7.png | - | Requis | - |
| score-8.png | - | Requis | - |
| score-9.png | - | Requis | - |
| score-comma.png | - | Requis | - |
| score-dot.png | - | Requis | - |
| score-percent.png | - | Requis | - |
| score-x.png | Peut être laissé de côté sur les beatmaps sans difficultés osu! | Requis | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| selection-mod-suddendeath.png | - | requis | - |
```suggestion
| selection-mod-autoplay.png | - | Requis | - |
| selection-mod-doubletime.png | - | Requis | - |
| selection-mod-easy.png | - | Requis | - |
| selection-mod-fadein.png | - | Requis | - |
| selection-mod-flashlight.png | - | Requis | - |
| selection-mod-halftime.png | - | Requis | - |
| selection-mod-hardrock.png | - | Requis | - |
| selection-mod-hidden.png | - | Requis | - |
| selection-mod-key1.png | - | Optionnel | - |
| selection-mod-key2.png | - | Optionnel | - |
| selection-mod-key3.png | - | Optionnel | - |
| selection-mod-key4.png | - | Optionnel | - |
| selection-mod-key5.png | - | Optionnel | - |
| selection-mod-key6.png | - | Optionnel | - |
| selection-mod-key7.png | - | Optionnel | - |
| selection-mod-key8.png | - | Optionnel | - |
| selection-mod-key9.png | - | Optionnel | - |
| selection-mod-keycoop.png | - | Requis | - |
| selection-mod-nightcore.png | - | Requis | - |
| selection-mod-nofail.png | - | Requis | - |
| selection-mod-perfect.png | - | Requis | - |
| selection-mod-random.png | - | Requis | - |
| selection-mod-relax.png | - | Requis | - |
| selection-mod-relax2.png | - | Requis | - |
| selection-mod-scorev2.png | - | Requis | - |
| selection-mod-spunout.png | - | Requis | - |
| selection-mod-suddendeath.png | - | Requis | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| star2.png | - | optionnel | - |
```suggestion
| comboburst-fruits(-n).png | Doit être orienté vers la droite, automatiquement retourné si montré sur le côté droit | Optionnel | Hauteur maximale : 768px |
| comboburst-mania(-n).png | Doit être orienté vers la droite, automatiquement retourné si montré sur le côté droit | Optionnel | Hauteur maximale : 768px |
| comboburst(-n).png | Doit être orienté vers la droite, automatiquement retourné si montré sur le côté droit | Optionnel | Hauteur maximale : 768px |
| menu-button-background.png | Utilisée pour le classement | Optionnel | Résolution minimale : 690x85px |
| multi-skipped.png | Multijoueur : montre qui a sauté l'intro | Optionnel | - |
| play-skip(-n).png | - | Optionnel | - |
| play-unranked.png | - | Optionnel | - |
| star2.png | - | Optionnel | - |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| inputoverlay-key.png | ne doit pas être skinné dans les beatmaps sans difficultés osu! ou osu!catch | requis | max : 46x46px |
```suggestion
| inputoverlay-background.png | Ne doit pas être skinné dans les beatmaps sans difficultés osu! ou osu!catch | Requis | 193x55px |
| inputoverlay-key.png | Ne doit pas être skinné dans les beatmaps sans difficultés osu! ou osu!catch | Requis | Max : 46x46px |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| scoreentry-x.png | - | requis | 10x14px |
```suggestion
| scoreentry-0.png | - | Requis | 11x14px |
| scoreentry-1.png | - | Requis | 11x14px |
| scoreentry-2.png | - | Requis | 11x14px |
| scoreentry-3.png | - | Requis | 11x14px |
| scoreentry-4.png | - | Requis | 11x14px |
| scoreentry-5.png | - | Requis | 11x14px |
| scoreentry-6.png | - | Requis | 11x14px |
| scoreentry-7.png | - | Requis | 11x14px |
| scoreentry-8.png | - | Requis | 11x14px |
| scoreentry-9.png | - | Requis | 11x14px |
| scoreentry-comma.png | - | Requis | 5x14px |
| scoreentry-dot.png | - | Requis | 5x14px |
| scoreentry-percent.png | - | Requis | 12x14px |
| scoreentry-x.png | - | Requis | 10x14px |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| go.png | - | requis | max : 1366x768px |
```suggestion
| ready.png | - | Requis | Max : 1366x768px |
| count1.png | - | Requis | Max : 1366x768px |
| count2.png | - | Requis | Max : 1366x768px |
| count3.png | - | Requis | Max : 1366x768px |
| go.png | - | Requis | Max : 1366x768px |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| section-pass.png | - | requis | hauteur maximale : 768px |
```suggestion
| section-fail.png | - | Requis | Hauteur maximale : 768px |
| section-pass.png | - | Requis | Hauteur maximale : 768px |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| ranking-xh-small.png | - | requis | 34x40px |
```suggestion
| ranking-a-small.png | - | Requis | 34x40px |
| ranking-b-small.png | - | Requis | 34x40px |
| ranking-c-small.png | - | Requis | 34x40px |
| ranking-d-small.png | - | Requis | 34x40px |
| ranking-s-small.png | - | Requis | 34x40px |
| ranking-sh-small.png | - | Requis | 34x40px |
| ranking-x-small.png | - | Requis | 34x40px |
| ranking-xh-small.png | - | Requis | 34x40px |
```

2022-02-08 17:36 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| pause-overlay.png | si un arrière plan est skinné, l'autre doit l'être aussi. | optionnel | 1366x768px |
```suggestion
| pause-back.png | - | Requis | - |
| pause-continue.png | - | Requis | - |
| pause-retry.png | - | Requis | - |
| fail-background.png | Si un arrière-plan est skinné, l'autre doit l'être aussi, il est mis à l'échelle pour s'adapter à l'écran du joueur | Optionnel | Max : 1920x1200px |
| pause-overlay.png | Si un arrière plan est skinné, l'autre doit l'être aussi | Optionnel | 1366x768px |
```

2022-02-08 18:03 UTC, Walavouchey approved these changes

2022-02-08 18:05 UTC, merged