[ZH] Update `Ranking_Criteria\osu!`
ppy/osu-wiki pull request #6806
Opened 2022-01-27 11:26 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-27 14:29 UTC, PercyDan54 commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **请勿在 hitnormal 音效较弱时使用[键盘音](/wiki/Beatmapping/Hitsound#keysound)。** 否则玩家不能获得足够的反馈。
```suggestion
- **请勿在 hitnormal 音效较弱时使用[打击音效](/wiki/Beatmapping/Hitsound#keysound)。** 否则玩家不能获得足够的反馈。
```

2022-01-27 14:29 UTC, PercyDan54 commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **请确保 osu! 难度的转谱不会破坏其他模式的星数或表现分系统。** 在某些情况下，部分 `.osu` 文件转换为其他模式的谱面时会错误地格式化，导致转谱显示出与实际难度不匹配的星数，游玩后也会获得与实际难度不匹配的表现分。
其他好像很多地方都是保留不翻

```suggestion
- **请确保 osu! 难度的转谱不会破坏其他模式的星数或pp系统。** 在某些情况下，部分 `.osu` 文件转换为其他模式的谱面时会错误地格式化，导致转谱显示出与实际难度不匹配的星数，游玩后也会获得与实际难度不匹配的 pp。
```

2022-01-27 15:39 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **请确保 osu! 难度的转谱不会破坏其他模式的星数或表现分系统。** 在某些情况下，部分 `.osu` 文件转换为其他模式的谱面时会错误地格式化，导致转谱显示出与实际难度不匹配的星数，游玩后也会获得与实际难度不匹配的表现分。
原文就是表现分，，，

2022-01-27 16:00 UTC, cdwcgt commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **请确保 osu! 难度的转谱不会破坏其他模式的星数或表现分系统。** 在某些情况下，部分 `.osu` 文件转换为其他模式的谱面时会错误地格式化，导致转谱显示出与实际难度不匹配的星数，游玩后也会获得与实际难度不匹配的表现分。
因为中文的 [Performance points](https://github.com/ppy/osu-wiki/blob/master/wiki/Performance_points/zh.md) 里面是用的 `pp` 而不是 `表现分`
所以还是改了吧
说实话这样很多文章都要统一

2022-01-27 17:40 UTC, Walavouchey commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **请确保 osu! 难度的转谱不会破坏其他模式的星数或表现分系统。** 在某些情况下，部分 `.osu` 文件转换为其他模式的谱面时会错误地格式化，导致转谱显示出与实际难度不匹配的星数，游玩后也会获得与实际难度不匹配的表现分。
lowercase is fine unless it's necessary due to the language

2022-01-27 17:56 UTC, Walavouchey commented
please only tick the relevant checklist item *after* you've applied reviews or when someone has approved the translation on github. the same goes for your other pull requests. i've unticked them for you again.

2022-01-27 18:19 UTC, cdwcgt requested changes
RC大写

2022-01-30 08:53 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!/zh.md
> +- **请确保 osu! 难度的转谱不会破坏其他模式的星数或表现分系统。** 在某些情况下，部分 `.osu` 文件转换为其他模式的谱面时会错误地格式化，导致转谱显示出与实际难度不匹配的星数，游玩后也会获得与实际难度不匹配的表现分。
ok lowercase `pp` applied

2022-02-04 18:02 UTC, merged