[ZH] Update `Ranking_Criteria\osu!taiko`
ppy/osu-wiki pull request #6808
Opened 2022-01-27 15:35 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-01-29 09:25 UTC, Gennadiyev requested changes
😃 Please avoid improvision in wiki pages.

Good work overall, thanks for you effort. Several critical issues are attached in the review, please check.

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **自创节奏 (Improvisation)：** 在歌曲的基础节拍内塞入更密集的音符来达到展示效果。请注意不要和塞爆 (overmapping) 相混淆。
请留意括号问题。Improvision 处使用有误。

请不要在原文档的基础上增加自己的理解。个人认为“自创节奏”非常 self-explanatory。

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **滑条、黄条：** 黄条中通常带有击打点，这些击打点通常间隔 1/4 拍（根据歌曲的 BPM 不同而变化）。如果 BPM 低于 125，击打点间隔会变成 1/8 拍。如果 BPM 高于 250，击打点间隔会变成 1/2 拍。如果滑条点倍率设为 3，击打点间隔变成 1/3 拍。玩家需要按照节拍击打黄条，颜色任意。
“颜色任意”一词不够严谨。

> 颜色任意 -> 使用“咚”、“咔”按键均可。

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +全局规定和准则适用于所有种类的 osu!taiko 难度。与节奏相关的规定和准则适用于歌曲为 4/4 拍，约 180 BPM 的谱面。如果歌曲明显快于或慢于 180 BPM，某些规则内限制的指标会不一样。更详细的说明请参考：[缩放 BPM](/wiki/Ranking_Criteria/Scaling_BPM)
好！修正了重要的翻译错误。

> `更详细的说明请参考：[缩放 BPM](/wiki/Ranking_Criteria/Scaling_BPM)` -> `详见 [缩放 BPM](/wiki/Ranking_Criteria/Scaling_BPM)`

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **每个音符必须明确地表现出音乐的内容，为游玩谱面起到画龙点睛的效果，亦或是展现谱师对于歌曲的理解和节奏创新。** 请不要以改变歌曲基础节奏的形式下创新节奏，或漏采、误采音，或是使用在歌曲的平静段落塞爆音符等与歌曲强度极不相关的强调手法。创新节奏必须以强调歌曲的现有节奏或合曲作为基准。否则，这会与节奏游戏的主要目的相矛盾。
1. 错字：  
  > 亦或是 -> 抑或是

2. `否则，这会与节奏游戏的主要目的相矛盾。` 建议修改。

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **`忽略第一拍小节线`的功能只能在当该红线的第一条小节线会影响玩家判断小节的开始时使用。请在红线(非继承时间点)密集的变速谱面内或使用红线修正 NC Mod 节拍器时善用这个功能。`**
似乎原来中文的翻译也有问题…

> **The `Omit first bar line` feature of an uninherited timing point must be used when a BPM change/metronome reset would hinder gameplay experience aesthetically by adding unnecessary bar lines.**

另外，这里请不要添加个人理解。

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **滑条点倍率应按歌曲节奏类型来设置。** 多数情况下，它应设置为 1。如果的歌曲主要是 1/3 节拍细分，那么此时应使用 3 倍滑条点倍率来让黄条的击打点贴合歌曲。
建议：

> `1/3 节拍细分` -> `三分拍`

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **避免在已含有互相重叠的 1/4 或更密集的音符段落突然改变滑条速度。** 一定要在谱面可读的基础上使用滑条速度平滑渐变的作图技巧。
不建议省略分数后的 `拍` 字。这与上文相矛盾，且阅读不通顺。

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +具体难度的规定和指南只适用于与它们在文中所列出位置相对应的难度，因此*不是**每个** osu!taiko 难度都适用*。节奏相关的指南适用于歌曲为 4/4 拍，约 180 BPM 的谱面。如果歌曲明显快于或慢于 180 BPM，某些规则内限制的指标会不一样。更详细的说明请参考：[缩放 BPM](/wiki/Ranking_Criteria/Scaling_BPM)
超链接处的翻译建议同上。

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- [判定严度 (OD)](/wiki/Beatmapping/Overall_difficulty) 应低于 4。
不应添加原文中不存在的超链接。

2022-01-29 09:25 UTC, Gennadiyev commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +如果此 Futsuu 难度是谱面的*最低难度*，则还应遵循以下规定：
`谱面集` 是术语，请不要改变。下同。这里使用 `谱面` 也与 osu! 本身的谱面结构逻辑不符。

可以使用 `谱面集的  *最低难度*`。

2022-01-30 09:04 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +**osu!taiko Ranking Criteria** 是一系列关于创建 osu!taiko 模式谱面的规定和准则。为了使 osu!taiko 模式谱面被 ranked，谱面必须遵循以下列出的标准。**规定在任何情况下都须遵守**，而在例外情况下可以违反准则。这些例外情况必须能够详细解释，说明违反准则的原因，以及不违反准则将如何影响谱面的整体质量。
1. 这个是根据 `wiki\Ranking_Criteria` 主页面为范本修改的，为了统一翻译此处便做出了修改。
2. 同上，也是根据他来修改的。

2022-01-30 09:06 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +具体难度的规定和指南只适用于与它们在文中所列出位置相对应的难度，因此*不是**每个** osu!taiko 难度都适用*。节奏相关的指南适用于歌曲为 4/4 拍，约 180 BPM 的谱面。如果歌曲明显快于或慢于 180 BPM，某些规则内限制的指标会不一样。更详细的说明请参考：[缩放 BPM](/wiki/Ranking_Criteria/Scaling_BPM)
同 wiki\Ranking_Criteria 。

2022-01-30 09:18 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **串、鱼蛋：** 一连串间隔是 1/4 拍，没有空隙的音符。
漏了“通常”。

2022-01-30 09:22 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- ![](/wiki/shared/diff/easy-t.png?20211215) Kantan (简单)
已修改

2022-01-30 09:24 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **转盘：** 要求玩家红蓝交替击打一定的次数的转动物件，需要击打次数显示在转盘的中心，且由谱面的判定严度 (OD) 和转盘的时间长度决定。
不应死磕原文。除了 ctb，其他三个 gamemode 的 OD 都是起到了限制判定的作用的。所以我认为翻译成这样没有问题。

2022-01-30 09:25 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **滑条点倍率应按歌曲节奏类型来设置。** 多数情况下，它应设置为 1。如果的歌曲主要是 1/3 节拍细分，那么此时应使用 3 倍滑条点倍率来让黄条的击打点贴合歌曲。
后加括号`（三分拍、六分拍）`以作区分。

2022-01-30 09:26 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **避免在已含有互相重叠的 1/4 或更密集的音符段落突然改变滑条速度。** 一定要在谱面可读的基础上使用滑条速度平滑渐变的作图技巧。
已修改

2022-01-30 09:27 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- [判定严度 (OD)](/wiki/Beatmapping/Overall_difficulty) 应低于 4。
已删除

2022-01-30 09:29 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +如果此 Futsuu 难度是谱面的*最低难度*，则还应遵循以下规定：
同 wiki\Ranking_Criteria 。

2022-01-30 09:37 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **滑条速度、滚动速度 (SV, Slider velocity)：** 决定了谱面（包括音符、黄条、小节线等等）的水平移动速度。基础滑条速度可在 Timing 面板设置，每一段落的滑条速度则通过继承时间节点(绿线)控制。
ok

2022-01-30 09:38 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **自创节奏 (Improvisation)：** 在歌曲的基础节拍内塞入更密集的音符来达到展示效果。请注意不要和塞爆 (overmapping) 相混淆。
已移除其后不必要的文字

2022-01-30 09:45 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **滑条速度、滚动速度 (SV, Slider velocity)：** 决定了谱面（包括音符、黄条、小节线等等）的水平移动速度。基础滑条速度可在 Timing 面板设置，每一段落的滑条速度则通过继承时间节点(绿线)控制。
已修改

2022-01-30 09:50 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **滑条、黄条：** 黄条中通常带有击打点，这些击打点通常间隔 1/4 拍（根据歌曲的 BPM 不同而变化）。如果 BPM 低于 125，击打点间隔会变成 1/8 拍。如果 BPM 高于 250，击打点间隔会变成 1/2 拍。如果滑条点倍率设为 3，击打点间隔变成 1/3 拍。玩家需要按照节拍击打黄条，颜色任意。
已修改

2022-01-30 09:51 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +全局规定和准则适用于所有种类的 osu!taiko 难度。与节奏相关的规定和准则适用于歌曲为 4/4 拍，约 180 BPM 的谱面。如果歌曲明显快于或慢于 180 BPM，某些规则内限制的指标会不一样。更详细的说明请参考：[缩放 BPM](/wiki/Ranking_Criteria/Scaling_BPM)
1. 好
2. 同 `wiki\Ranking_Criteria` 。

2022-01-30 10:07 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **`忽略第一拍小节线`的功能只能在当该红线的第一条小节线会影响玩家判断小节的开始时使用。请在红线(非继承时间点)密集的变速谱面内或使用红线修正 NC Mod 节拍器时善用这个功能。`**
重翻译可能会更加达意一点

2022-01-30 10:10 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!taiko/zh.md
> +- **每个音符必须明确地表现出音乐的内容，为游玩谱面起到画龙点睛的效果，亦或是展现谱师对于歌曲的理解和节奏创新。** 请不要以改变歌曲基础节奏的形式下创新节奏，或漏采、误采音，或是使用在歌曲的平静段落塞爆音符等与歌曲强度极不相关的强调手法。创新节奏必须以强调歌曲的现有节奏或合曲作为基准。否则，这会与节奏游戏的主要目的相矛盾。
修改和删除了

2022-02-01 10:01 UTC, Gennadiyev approved these changes
Good to go! I checked the `wiki\Ranking_Criteria`, sorry for making some dumb suggestions 😿 

Thanks again, and 🎆 Happy Chinese New Year of Tiger 🐯

2022-02-01 12:42 UTC, TicClick approved these changes

2022-02-01 12:43 UTC, merged