[FR] Adjustment of certain terms
ppy/osu-wiki pull request #6832
Opened 2022-02-02 10:09 UTC by DoryanR

Rectification of some terms throughout the wiki for the French articles, in order to have the same terms in all the articles, thus avoiding several terms that all mean the same thing.

The changes concerned by the PR :

`chanson` > `musique`
`chansons` > `musiques`
`map` > `beatmap`
`maps` > `beatmaps`
`mapset` > `beatmap`
`mapsets` > `beatmaps`

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-02 10:21 UTC, DoryanR reviewed
Self check

2022-02-02 10:21 UTC, DoryanR commented on wiki/Client/Beatmap_editor/Menu/fr.md
> +| Activer le live mapping (`Ctrl` + Tab) | Beatmaps osu!/osu!catch/osu!taiko : utilisez les touches osu!taiko pour saisir des cercles/fruit/taiko, tout en jouant le morceau dans l'éditeur. Les notes
```suggestion
| Activer le live mapping (`Ctrl` + Tab) | Beatmaps osu!/osu!catch/osu!taiko : utilisez les touches osu!taiko pour saisir des cercles/fruit/taiko, tout en jouant le morceau dans l'éditeur. Les notes sont placées selon l'emplacement du curseur. Différents sons en fonction de la touche osu!taiko sur laquelle vous avez appuyée. Beatmaps osu!mania : utilisez les touches osu!mania pour placer des cercles, tout en jouant un morceau dans l'éditeur. La note est placée selon la touche sur laquelle vous avez appuyée. Ne fonctionne pas pour les sliders/holds. |
```

2022-02-03 11:10 UTC, Biokax commented
not sure about `map > beatmap` and `maps > beatmaps` because some english files contains `map` and `maps`, that seem unnecessary

2022-02-03 21:01 UTC, DoryanR commented
Personally I don't understand the use of the term `map`, for me I don't see the difference between `beatmap` and `map`, and since often when you make reviews, you suggest me to change these terms, so I might as well unify the terms.

2022-02-03 21:07 UTC, Walavouchey commented
*map* and *beatmap* are the same thing, and they contain *difficulties*.

2022-02-03 21:17 UTC, Biokax commented
> _map_ and _beatmap_ are the same thing, and they contain _difficulties_.

If its the same thing it doesn't matter if the translation doesn't follow the exact english terms and replace all maps by beatmaps ?

2022-02-03 21:27 UTC, Walavouchey commented
no it doesn't matter

2022-02-15 16:45 UTC, Ganondorf-1 requested changes

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Client/Beatmap_editor/Song_Setup/fr.md
>  Ces champs doivent être remplis avant de créer une deuxième difficulté. Il s'agit principalement de s'assurer que les métadonnées seront cohérentes pour toutes les difficultés du beatmapset.
```suggestion
Ces champs doivent être remplis avant de créer une deuxième difficulté. Il s'agit principalement de s'assurer que les métadonnées seront cohérentes pour toutes les difficultés de la beatmap.
```

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Guides/Beginner's_Tutorial/fr.md
> +Vous pouvez commencer votre aventure avec ces beatmap :
```suggestion
Vous pouvez commencer votre aventure avec ces beatmaps :
```

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Client/Beatmap_editor/Distance_snap/fr.md
> +La façon la plus simple de s'assurer que l'espacement des battements est correct sur vos beatmap est d'utiliser la fonction Distance Snapping de l'éditeur, qui se trouve en haut à droite de l'éditeur
```suggestion
La façon la plus simple de s'assurer que l'espacement des battements est correct sur vos beatmaps est d'utiliser la fonction Distance Snapping de l'éditeur, qui se trouve en haut à droite de l'éditeur. La distance relative entre les notes peut être ajustée en utilisant 'Alt' et la molette de la souris. Cela permet de s'assurer que les temps qui sont proches sur la timeline le sont aussi sur le beatmap, et vice versa. Cela permet un jeu intuitif et un bon espacement des temps. Si vous vous en tenez à l'utilisation de Distance Snap pour tout le morceau, l'espacement correct des temps est garanti !
```

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Game_modifier/Auto/fr.md
> +Dans le mode [osu!taiko](/wiki/Game_mode/osu!taiko), le mod Auto tentera de jouer parfaitement, mais n'obtiendra pas toujours la note SS. Il manquera parfois un tick sur les drum rolls qui ne commenc
```suggestion
Dans le mode [osu!taiko](/wiki/Game_mode/osu!taiko), le mod Auto tentera de jouer parfaitement, mais n'obtiendra pas toujours la note SS. Il manquera parfois un tick sur les drum rolls qui ne commencent pas sur un temps entier ou un demi-ton et ne sera pas toujours capable de terminer les dendens sur les beatmaps dont la difficulté globale est très élevée.
```

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Client/Beatmap_editor/AiMod/fr.md
> +- **AiMod peut vous avertir de l'absence de problèmes**, comme le fait que les beatmaps nécessite deux difficultés du mode osu! sur une beatmap [marathon](/wiki/Beatmap/Marathon) et que l'option [kia
```suggestion
- **AiMod peut vous avertir de l'absence de problèmes**, comme le fait que les beatmaps nécessitent deux difficultés du mode osu! sur une beatmap [marathon](/wiki/Beatmap/Marathon) et que l'option [kiai time](/wiki/Gameplay/Kiai_time) soit activée pendant moins de 15 secondes.
```

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Guides/Timing_Songs_With_8-Signatures/fr.md
>  Afin de rendre ce tableau plus compréhensible et d'indiquer plus précisément ce que l'on entend par là, ce guide va maintenant expliquer un peu de théorie musicale pertinente derrière tout cela, et d
```suggestion
Afin de rendre ce tableau plus compréhensible et d'indiquer plus précisément ce que l'on entend par là, ce guide va maintenant expliquer un peu de théorie musicale pertinente derrière tout cela, et donner des exemples de la façon dont cela se traduit dans osu!. Pour cette raison, [trois beatmaps](https://assets.ppy.sh/media/wiki/TimeSignatures.rar) ont été préparées pour que vous puissiez les télécharger, et ils seront utilisés comme référence dans ce guide.
```

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Guides/Timing_Songs_With_8-Signatures/fr.md
> +Pour un exemple plus simple, regardez le beatmapset fourni de la musique *We Are The Champions* de Queen, qui est une musique purement en `6/8`. Lorsque vous regardez l'onglet timing de la difficulté
```suggestion
Pour un exemple plus simple, regardez la beatmap fournie de la musique *We Are The Champions* de Queen, qui est une musique purement en `6/8`. Lorsque vous regardez l'onglet timing de la difficulté `6/8`, vous pouvez voir que les petits ticks blancs entre les mesures correspondent exactement aux temps réels de la musique, et que tous les huitièmes de note ♪ sont mises en correspondance en utilisant le `1/3-BeatSnapDivisor`.
```

2022-02-15 16:45 UTC, Ganondorf-1 commented on wiki/Client/Beatmap_editor/AiMod/fr.md
>  | Plus de la moitié de la carte TV Size est constituée d'un kiai time. Envisagez de le réduire. |  |  |
```suggestion
| Plus de la moitié de la beatmap TV Size est constituée d'un kiai time. Envisagez de le réduire. |  |  |
```

2022-03-15 18:05 UTC, Walavouchey commented
Is this good to go @Ganondorf-1, @Biokax? I've applied the review

2022-03-15 18:26 UTC, Ganondorf-1 commented
I can't find any other problem so I think it is

2022-03-15 18:28 UTC, Walavouchey approved these changes

2022-03-15 18:31 UTC, merged