[FR] Update `Client\Interface`
ppy/osu-wiki pull request #6838
Opened 2022-02-05 13:41 UTC by DoryanR

Proposal to update the French translation of the wiki page `Client\Interface`.

Also:

- Change of all the images, because these last ones were not in conformity with the ASC (bad dimmensions compared to the origin, different contents, etc...)
- Add query string to update images
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-05 13:45 UTC, DoryanR commented on wiki/Client/Interface/fr.md
> +| `Favoris` | Seuls les beatmaps que vous avez mis en favoris sur le site seront affichés.
```suggestion
| `Favoris` | Seuls les beatmaps que vous avez mis en favoris sur le site seront affichés. |
```

2022-02-05 13:47 UTC, DoryanR commented on wiki/Client/Interface/fr.md
> +- \[1\] Le [cookie d'osu!](/wiki/Client/Interface/Cookie). En cliquant dessus, vous ouvrez le menu principal. Il pulse en fonction du [BPM](/wiki/Beatmapping/Beats_par_minute) de la musique et des ba
```suggestion
- \[1\] Le [cookie d'osu!](/wiki/Client/Interface/Cookie). En cliquant dessus, vous ouvrez le menu principal. Il pulse en fonction du [BPM](/wiki/Beatmapping/Beats_per_minute) de la musique et des barres s'étendent autour de lui pour visualiser le spectre audio. Si aucune musique n'est en cours de lecture, il pulse à un rythme lent de 60 BPM.
```

2022-02-15 13:35 UTC, Biokax requested changes

2022-02-15 13:35 UTC, Biokax commented on wiki/Client/Interface/fr.md
> +| `speed` | Sauvegarde de la vitesse de défilement d'osu!mania. Toujours 0 pour les cartes non jouées ou si l'option [`Se souvenir des vitesses de défilement sur chaque maps osu!mania`](/wiki/Client/
```suggestion
| `speed` | Sauvegarde de la vitesse de défilement d'osu!mania. Toujours 0 pour les maps non jouées ou si l'option [`Se souvenir des vitesses de défilement sur chaque maps osu!mania`](/wiki/Client/Options#gameplay) est désactivée. |
```

2022-02-15 13:35 UTC, Biokax commented on wiki/Client/Interface/fr.md
> +Cliquez sur l'icône de la bulle de texte pour appeler l'écran **accès rapide au web** pour la beatmap sélectionné :
```suggestion
Cliquez sur l'icône de la bulle de texte pour appeler l'écran **accès rapide au web** pour la beatmap sélectionnée :
```

2022-02-15 13:35 UTC, Biokax commented on wiki/Client/Interface/fr.md
> +| `Max Combo` | Le combo le plus long sur la beatmap que vous avez jouée. | Le combo le plus long sur toutes les beatmaps que vous avez joués. |
```suggestion
| `Max Combo` | Le combo le plus long sur la beatmap que vous avez jouée. | Le combo le plus long sur toutes les beatmaps que vous avez jouées. |
```

2022-02-15 13:35 UTC, Biokax commented on wiki/Client/Interface/fr.md
> +| [`Score total`](/wiki/Gameplay/Score/Total_score) | Non pris en compte, car il n'affecte pas votre position dans les classements en ligne. | Identique au score classé, mais il prend en compte tous
```suggestion
| [`Score total`](/wiki/Gameplay/Score/Total_score) | Non pris en compte, car il n'affecte pas votre position dans les classements en ligne. | Identique au score classé, mais il prend en compte tous les beatmaps disponibles sur le site web d'osu!, y compris les beatmaps sous-jouées ou échoués. Cela compte pour votre [niveau](/wiki/Gameplay/Score/Total_score#level). |
```

2022-03-16 18:24 UTC, Ganondorf-1 requested changes

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +| `Par note reçue` | Les beatmaps seront classées en fonction du [grade](/wiki/Gameplay/Grade) le plus élevé. |
```suggestion
| `Par note reçue` | Les beatmaps seront classées en fonction de la [note](/wiki/Gameplay/Grade) la plus élevée. |
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +Seuls les beatmaps qui correspondent aux critères de votre recherche seront affichés. Par défaut, toute recherche est effectuée sur la base des artistes, des titres, des créateurs et des balises du b
```suggestion
Seules les beatmaps qui correspondent aux critères de votre recherche seront affichées. Par défaut, toute recherche est effectuée sur la base des artistes, des titres, des créateurs et des tags de la beatmap.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +| `played` | Temps depuis le dernier jeu en jours |
```suggestion
| `played` | Temps depuis la dernière fois où les beatmaps ont été jouées (en jours) |
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Une case `Not Submitted` indique une beatmap qui n'a pas été téléchargée sur le site d'osu! en utilisant le [Beatmap Submission System](/wiki/Submission) ou qui a été supprimé par le mapper.
```suggestion
- Une case `Not Submitted` indique une beatmap qui n'a pas été publiée sur le site d'osu! en utilisant le [Beatmap Submission System](/wiki/Submission) ou qui a été supprimée par le mappeur.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Une case `Latest pending version` signifie que la beatmap a été téléchargé sur le site d'osu! mais n'est pas encore classé.
```suggestion
- Une case `Latest pending version` signifie que la beatmap a été publiée sur le site d'osu! mais n'est pas encore classée.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +  - Dans les classements publics (par exemple, Global, Amis, etc.), votre meilleur score sera affiché en bas, ainsi que votre rang dans le classement.
```suggestion
  - Dans les classements publics (par exemple, Global, Amis, etc.), votre meilleur score sera affiché en bas, ainsi que votre place dans le classement.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Une case `Aucun score enregistré` signifie qu'il n'y a pas de replays pour le paramètre de vue actuel (ceci est typiquement vu dans le paramètre de vue locale si vous venez de télécharger ou d'édit
```suggestion
- Une case `No records set!` signifie qu'il n'y a pas de replays pour le paramètre de vue actuel (ceci est typiquement vu dans le paramètre de vue locale si vous venez de télécharger ou d'éditer la beatmap).
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +Ce sont les paramètres d'affichage :
```suggestion
Voici les paramètres d'affichage :
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Appuyez sur `1` ou cliquez sur le `Infos beatmap/classement` pour afficher la page de la beatmap pour la difficulté sélectionnée dans votre navigateur.
```suggestion
- Appuyez sur `1` ou cliquez sur `Infos beatmap/classement` pour afficher la page de la beatmap pour la difficulté sélectionnée dans votre navigateur.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Appuyez sur `2` ou cliquez sur `Topic de la beatmap` pour afficher la page [modding](/wiki/Modding) de la beatmap.
```suggestion
- Appuyez sur `2` ou cliquez sur `Topic de la beatmap` pour afficher la page de [modding](/wiki/Modding) de la beatmap.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +La vignette des beatmaps affiche toutes les beatmaps disponibles. Les différents beatmaps peuvent avoir des cases de couleur différente :
```suggestion
La vignette des beatmaps affiche toutes les beatmaps disponibles. Les différentes beatmaps peuvent avoir des cases de couleur différente :
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +| **Orange** | Au moins une difficulté de la beatmap a été réalisée. |
```suggestion
| **Orange** | Au moins une difficulté de la beatmap a été jouée. |
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +Vous pouvez naviguer dans la liste des beatmaps en utilisant la molette de la souris, en utilisant les flèches haut et bas, en la faisant glisser tout en maintenant le bouton gauche de la souris ou e
```suggestion
Vous pouvez naviguer dans la liste des beatmaps en utilisant la molette de la souris, en utilisant les flèches haut et bas, en la faisant glisser tout en maintenant le bouton gauche de la souris ou en cliquant sur le bouton droit de la souris (connu sous le nom de défilement absolu), ce qui déplacera la barre de défilement sur la position Y de votre souris. Cliquez sur une beatmap pour la sélectionner, puis cliquez à nouveau, appuyez sur `Entrée` ou cliquez sur le cookie d'osu! dans le coin inférieur droit pour jouer la beatmap.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +Appuyez sur `Esc` ou cliquez sur le bouton `Back` pour revenir au menu principal.
```suggestion
Appuyez sur `Echap` ou cliquez sur le bouton `Back` pour revenir au menu principal.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +Cliquez sur le bouton `Mode` pour ouvrir une liste des modes de jeu disponibles dans osu!. Vous pouvez aussi appuyer sur `Ctrl` et `1` (osu!), `2` (osu!taiko), `3` (osu!catch), ou `4` (osu!mania) pou
```suggestion
Cliquez sur le bouton `Mode` pour ouvrir une liste des modes de jeu disponibles sur osu!. Vous pouvez aussi appuyer sur `Ctrl` et `1` (osu!), `2` (osu!taiko), `3` (osu!catch), ou `4` (osu!mania) pour changer de mode de jeu. Le passage d'un mode à l'autre entraîne également l'affichage de son [classement](/wiki/Ranking), comme on peut le constater en voyant le rang affiché changer.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +Cliquez sur le bouton `Random`  ou appuyez sur `F2` pour que le jeu fasse **défiler aléatoirement toutes vos beatmaps et en choisisse une.**
```suggestion
Cliquez sur le bouton `Random` ou appuyez sur `F2` pour que le jeu fasse **défiler aléatoirement toutes vos beatmaps et en choisisse une.**
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +*Note : Vous pouvez appuyer sur `Shift` + le bouton `Random` ou sur `F2` pour revenir à la beatmap que vous aviez choisi avant de randomiser votre sélection.*
```suggestion
*Remarque : Vous pouvez appuyer sur `Shift` + le bouton `Random` ou sur `F2` pour revenir à la beatmap que vous aviez choisi avant de randomiser votre sélection.*
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Appuyez sur `1` ou cliquez sur le bouton `Gérer les collections` pour faire apparaître le gestionnaire de collections—ici, vous pouvez gérer les collections pré-existantes, ainsi qu'ajouter ou supp
```suggestion
- Appuyez sur `1` ou cliquez sur le bouton `Gérer les collections` pour faire apparaître le gestionnaire de collections. Ici, vous pouvez gérer les collections pré-existantes, ainsi qu'ajouter ou supprimer la beatmap ou la difficulté actuellement sélectionnée dans ou depuis une collection.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +  - Notez que les beatmaps supprimés sont déplacés vers la corbeille.
```suggestion
  - Notez que les beatmaps supprimées sont déplacées vers la corbeille.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Appuyez sur `3` ou cliquez sur `Marquer la beatmap comme jouée` pour marquer une beatmap non joué comme joué (c'est-à-dire, changer la couleur de sa boîte de rose à orange).
```suggestion
- Appuyez sur `3` ou cliquez sur `Marquer la beatmap comme jouée` pour marquer une beatmap non jouée comme jouée (c'est-à-dire, changer la couleur de sa boîte de rose à orange).
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- Appuyez sur `5` ou cliquez sur `Éditer` pour ouvrir la beatmap sélectionné dans l'éditeur d'osu!.
```suggestion
- Appuyez sur `5` ou cliquez sur `Éditer` pour ouvrir la beatmap sélectionnée dans l'éditeur d'osu!.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- \[3\] `Ajouter aux favoris en ligne` : Inclue la beatmap dans votre liste de favoris, qui se trouve sur votre page de profil osu! dans la section `Beatmaps`.
```suggestion
- \[3\] `Ajouter aux favoris en ligne` : Inclut la beatmap dans votre liste de favoris, qui se trouve sur votre page de profil osu! dans la section `Beatmaps`.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +- \[4\] Tableau de classement local : Tous vos résultats sont stockés sur votre ordinateur. Pour les voir, allez dans l'[écran de sélection des beatmaps](#sélection-des-beatmaps) et sélectionnez `Cla
```suggestion
- \[4\] Tableau de classement local : Tous vos résultats sont stockés sur votre ordinateur. Pour les voir, allez dans l'[écran de sélection des beatmaps](#sélection-des-beatmaps) et sélectionnez `Classement local` dans le menu déroulant au-dessus du classement.
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +| `Général` | Votre position dans le classement de la beatmap. Notez que les scores avec des [mods](/wiki/Game_modifier) apparaissent également dans ce même classement. | Votre [rang global](/wiki/Ra
```suggestion
| `Général` | Votre position dans le classement de la beatmap. Notez que les scores avec des [mods](/wiki/Game_modifier) apparaissent également dans ce même classement. | Votre [rang global](/wiki/Ranking#classement-des-points-de-performance) par rapport à tous les joueurs dans le monde. |
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +| [`Score classée`](/wiki/Gameplay/Score/Ranked_score) | Votre [meilleur résultat](/wiki/Gameplay/Score/Ranked_score) sur la beatmap. | Le nombre de points obtenus grâce à toutes les beatmaps classée
```suggestion
| [`Score classé`](/wiki/Gameplay/Score/Ranked_score) | Votre [meilleur résultat](/wiki/Gameplay/Score/Ranked_score) sur la beatmap. | Le nombre de points obtenus grâce à toutes les beatmaps classées que vous avez jouées, chaque beatmap étant comptée exactement une fois. |
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +| [`Score total`](/wiki/Gameplay/Score/Total_score) | Non pris en compte, car il n'affecte pas votre position dans les classements en ligne. | Identique au score classé, mais il prend en compte tous
```suggestion
| [`Score total`](/wiki/Gameplay/Score/Total_score) | Non pris en compte, car il n'affecte pas votre position dans les classements en ligne. | Identique au score classé, mais il prend en compte toutes les beatmaps disponibles sur le site web d'osu!, y compris les beatmaps sous-jouées ou échouées. Cela compte pour votre [niveau](/wiki/Gameplay/Score/Total_score#level). |
```

2022-03-16 18:24 UTC, Ganondorf-1 commented on wiki/Client/Interface/fr.md
> +| [`Performance`](/wiki/Performance_points) | Le montant des [pp non pondérés](/wiki/Performance_points#pourquoi-n'ai-je-pas-gagné-la-totalité-des-pp-d'une-beatmap-que-j'ai-jouée-?) que vous recevrie
```suggestion
| [`Performance`](/wiki/Performance_points) | Le montant des [pp non pondérés](/wiki/Performance_points#pourquoi-n'ai-je-pas-gagné-la-totalité-des-pp-d'une-beatmap-que-j'ai-jouée-?) que vous recevriez pour la partie. | Votre nombre total de points de performance, et le nombre de pp du score réalisé. |
```

2022-03-19 10:05 UTC, Walavouchey approved these changes

2022-03-19 10:05 UTC, merged