[FR] Update `Article_styling_criteria\Formatting` and `Article_styling_criteria\Writing`
ppy/osu-wiki pull request #6846
Opened 2022-02-06 21:21 UTC by DoryanR

Update of the translations of the following wiki pages:

- `Article_styling_criteria\Formatting`
- `Article_styling_criteria\Writing`
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-16 12:12 UTC, Biokax approved these changes

2022-03-15 17:15 UTC, TicClick commented
please add changes from https://github.com/ppy/osu-wiki/pull/7022

2022-03-15 18:49 UTC, Walavouchey commented on wiki/Article_styling_criteria/Formatting/fr.md
> +—rrtyui
```suggestion
> profitez du jeu

-rrtyui
```

2022-03-16 17:56 UTC, Ganondorf-1 requested changes

2022-03-16 17:56 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Par exemple, lorsque l'on fait référence à des musique sous le format `{artist} - {title}`, toute la partie est une référence à l'œuvre et doit donc être mise en italique :
```suggestion
Par exemple, lorsque l'on fait référence à des musiques sous le format `{artist} - {title}`, toute la partie est une référence à l'œuvre et doit donc être mise en italique :
```

2022-03-16 17:56 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Formatting/fr.md
> +*cYsmix - triangles* est l'une des trois musique d'intro que l'on peut entendre au démarrage du jeu.
```suggestion
*cYsmix - triangles* est l'une des trois musiques d'intro que l'on peut entendre au démarrage du jeu.
```
```suggestion
*cYsmix - triangles* est l'une des trois musique d'intro que l'on peut entendre au démarrage du jeu.
```

2022-03-16 17:56 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Formatting/fr.md
> +*cYsmix - triangles* est l'une des trois musique d'intro que l'on peut entendre au démarrage du jeu.
```suggestion
*cYsmix - triangles* est l'une des trois musiques d'intro que l'on peut entendre au démarrage du jeu.
```

2022-03-16 17:56 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Les liens apparaissent dans une couleur différente, ce qui le met déjà en valeur et ne nécessite donc pas de mise en valeur supplémentaire :
```suggestion
Les liens apparaissent dans une couleur différente, ce qui le met déjà en valeur et ne nécessitent donc pas de mise en valeur supplémentaire :
```

2022-03-16 17:56 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Formatting/fr.md
> +[Camellia - OOPARTS](https://cametek.bandcamp.com/track/parts) est un exemple de musique officiellement créée spécifiquement pour osu!, autrement dit un *osu! original*, puisqu'elle a été spécifiquem
```suggestion
[Camellia - OOPARTS](https://cametek.bandcamp.com/track/parts) est un exemple de musique officiellement créée spécifiquement pour osu!, autrement dit un *osu! original*, puisqu'elle a été spécifiquement commandée pour le tiebreaker de l'osu! World Cup 2020.
```

2022-03-19 09:55 UTC, Walavouchey commented
@Ganondorf-1, @Biokax, I've applied the reviews, think this is good to go? The changes from #7022 can be added in a separate pr

2022-03-19 12:07 UTC, Ganondorf-1 approved these changes
Yes, I will make another PR as soon as possible

2022-03-19 12:08 UTC, Walavouchey approved these changes

2022-03-19 12:09 UTC, merged