[ZH] Update `Ranking_Criteria`
ppy/osu-wiki pull request #6848
Opened 2022-02-06 22:07 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-08 01:44 UTC, RushFTK submitted a review, later dismissed
all looks fine for me (as a chinese native speaker). while a few point may discussion.

2022-02-08 01:44 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +  - **最高难度以下的难度可以使用包含休息时间的总游戏时长来替代掉血时间，作为度量标准而达到规定阈值。** 这不包含掉血时间在 30 秒以下的难度。一般由该游戏模式的 [BN](/wiki/People/The_Team/Beatmap_Nominators) 和 [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) 成员来判断谱面中
```suggestion
  - **最高难度以下的难度可以使用包含休息时间的总游戏时长来替代掉血时间，作为度量标准而达到规定阈值。** 这不包含掉血时间在 30 秒以下的难度。一般由该游戏模式的 [谱面提名者](/wiki/People/The_Team/Beatmap_Nominators) (以下简称BN) 和 [提名评估团队](/wiki/People/The_Team/Nomination_Assessment_Team) (以下简称NAT) 成员来判断谱面中作为最低难度的 Hard 或者 Insane 谱面是否合格。
```

首次出现的专有名词缩写，建议保留原有全称。如果认为原有英文名称不恰当，可使用中文翻译表示。不过由于不常见，所以并不推荐。

2022-02-08 01:44 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +  - **最高难度以下的难度可以使用包含休息时间的总游戏时长来替代掉血时间，作为度量标准而达到规定阈值。** 这不包含掉血时间在 30 秒以下的难度。一般由该游戏模式的 [BN](/wiki/People/The_Team/Beatmap_Nominators) 和 [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) 成员来判断谱面中
这段我看了确实只有这一处出现，所以也许你不修改也可以。

2022-02-08 09:17 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +  - **最高难度以下的难度可以使用包含休息时间的总游戏时长来替代掉血时间，作为度量标准而达到规定阈值。** 这不包含掉血时间在 30 秒以下的难度。一般由该游戏模式的 [BN](/wiki/People/The_Team/Beatmap_Nominators) 和 [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) 成员来判断谱面中
因为中文社区内很少用全称，而且在目前没有专用的名词解释下，用缩写也可以
Abbreviations are often used to refer to them in the osu! Chinese community.

2022-02-10 17:11 UTC, TicClick commented
I've just submitted for review https://github.com/ppy/osu-wiki/pull/6870 with small improvements for the original article -- please make sure to apply changes from it **once it's finalized and merged**

2022-02-11 02:15 UTC, RushFTK requested changes
Others looks fine, but keep some terms like `tags` as it was or translate should be determined.
现在这个版本的翻译中，"标签"到底是主要使用中文，在首次使用中注释英文；或者主要使用英文，在首次使用中注释中文。

2022-02-16 07:41 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
> +- **[歌曲风格与语言](/wiki/Beatmap/Genre_and_language)也应加入 Tags 字段中。** 这是为了让玩家能在游戏内也能像在网站上一样搜索到它。使用 `instrumental` 作为语言标记纯音乐类歌曲。且不应在语言或曲风不清晰时使用这个标记。如果歌曲适用于多个语言或曲风，则都应填写。
用英文 Tags 吧 等会改

2022-02-16 07:42 UTC, YumeMuzi commented on wiki/Ranking_Criteria/zh.md
>  - **谱面必须测定出精准的时间轴。** 这意味着 [BPM](/wiki/Beatmapping/Beats_per_minute) 和[偏移量](/wiki/Beatmapping/Offset)需要完全贴合歌曲。无规律的变奏歌曲也许不可能完美地测定，那么则应在不影响谱面游玩的情况下尽量精确测定。如果打算采用休息段或者转盘覆盖变奏段，则这个段落的复杂节奏测定可以忽略掉。
#6870 已经得出结果，等会改

2022-02-16 13:29 UTC, RushFTK approved these changes
looks fine for a Chinese native speaker.

2022-02-17 12:05 UTC, Walavouchey commented
let's not balloon the scope too much for this pr. https://github.com/ppy/osu-wiki/pull/6873 may take a bit to get merged

2022-02-17 12:06 UTC, Walavouchey commented on wiki/Ranking_Criteria/zh.md
> +
excess line

```suggestion
```

2022-02-17 12:08 UTC, Walavouchey commented
@RushFTK sorry, mind taking one more look for latest change ([a055904](https://github.com/ppy/osu-wiki/pull/6848/commits/a055904996fb31808b1c9f695a21b848b0e0d600))?

2022-02-17 12:08 UTC, TicClick commented
fair, I didn't follow it closely

2022-02-17 12:33 UTC, RushFTK requested changes
No problem @Walavouchey , here is the review as requested.
in my opinion, the second review is necessary to change, while others are opinion.

2022-02-17 12:33 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +非常建议您使用 [Mapset Verifier (MV)](https://github.com/Naxesss/MapsetVerifier) 来帮助检查谱面是否符合以下这些规则。老旧的稳定版 (stable) 客户端内的 [AiMod](/wiki/Client/Beatmap_editor/AiMod) 工具已经过时且不再维护。同时，新版 lazer 客户端内的谱面检查工具仍在[开发中]
````suggestion
非常建议您使用 [Mapset Verifier (MV)](https://github.com/Naxesss/MapsetVerifier) 来帮助检查谱面是否符合本文所述的规则。传统客户端 (stable 版) 内的 [AiMod](/wiki/Client/Beatmap_editor/AiMod) 工具已经过时且不再维护。同时，新版客户端( lazer 版) 内的谱面检查工具仍在[开发中](https://github.com/ppy/osu/issues/12091#issuecomment-878760791)。
````

2022-02-17 12:33 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- 工具不能代替阅读此页面或人工检查的必要操作。
````suggestion
- 工具不能代替阅读此页面或人工检查的必要性。
````

2022-02-17 12:33 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- 工具能帮助你检查谱面，而不能代替你检查谱面。
````suggestion
- 工具是用于帮助你检查谱面，而不是代替你检查谱面。
````

2022-02-17 12:33 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- 工具不能代替阅读此页面或人工检查的必要操作。
"阅读此页"与词语"操作"不匹配。

2022-02-17 12:33 UTC, RushFTK commented on wiki/Ranking_Criteria/zh.md
> +- 工具能帮助你检查谱面，而不能代替你检查谱面。
原文含义毕竟是促使玩家自己审一遍铺面，主要强调谱师的主观用法而不是AiMod的性能。能其实还是能的（）

2022-02-17 12:42 UTC, RushFTK approved these changes
Looks fine for native speakers now.

2022-02-17 12:46 UTC, Walavouchey commented
it looks like all the rc articles have the same issue as in https://github.com/ppy/osu-wiki/pull/6851#discussion_r808927887. i'll update all of them in a separate pr

2022-02-17 12:46 UTC, Walavouchey approved these changes

2022-02-17 12:48 UTC, merged