[ZH] Update `Ranking_Criteria\osu!mania`
ppy/osu-wiki pull request #6859
Opened 2022-02-08 22:59 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-10 08:03 UTC, RushFTK commented
> **如果谱面的[掉血时间](/wiki/Gameplay/Drain_time)符合以下条件：**
原来drain time是掉血时间的意思（）这里直接意译为游玩时长是不是更好
我到时候摸一下，然后你最好找一个老前辈确认一下术语。

2022-02-10 15:31 UTC, YumeMuzi commented
> 



> > **如果谱面的[掉血时间](/wiki/Gameplay/Drain_time)符合以下条件：**
> 
> 原来drain time是掉血时间的意思（）这里直接意译为游玩时长是不是更好 我到时候摸一下，然后你最好找一个老前辈确认一下术语。
> 
> 比如
> 
> > 多押切换（双押切，三押切，四押切） (Chordstream (Jumpstream, Handstream, Quadstream))：** 混杂了不同多押的切换键型
> 
> 到后面你使用的翻译术语为"胶囊"，那前面是不是也叫"胶囊"?

drain time 暂时没有一个社区常用的词，游玩时长也可以 不过其他地方也得改 可以先留着

胶囊特指多K甚至专指7K的多押切。
It is a proper noun to describe the chordstream in 5-10 key mode especially 7K.

2022-02-15 02:02 UTC, RushFTK requested changes

2022-02-15 02:02 UTC, RushFTK commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **不同的长键尾之间至少需要间隔 1 拍。** 更密集的长键尾对于新手来说太难掌握。
```suggestion
- **每个长键之间至少需要间隔 1 拍。** 更密集的长键尾对于新手来说太难掌握。
```

2022-02-15 02:02 UTC, RushFTK commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **不同的长键尾之间至少需要间隔 1 拍。** 更密集的长键尾对于新手来说太难掌握。
或者说不同长键的头和尾之间。总之意味着不能出现类似面条图的交集。

2022-02-16 08:55 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **不同的长键尾之间至少需要间隔 1 拍。** 更密集的长键尾对于新手来说太难掌握。
It has been discussed with the reviewers to maintain the present translate.

2022-02-16 09:03 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **避免在连续的 1/8 切换键型内使用多押。** 这对于这个分段的玩家来说太难掌握。尤其是当 Insane 当做谱面的最低难度时。并且，不合理的多押可能会无意导致 1/4 子弹出现。允许在切换头尾放置多押。
mania内根本不用术语“连打”，与现存的玩家自制百科文件对比来看，此键型只应是切换。

2022-02-16 09:18 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **避免在长达 4 拍以上的复杂 1/8 切换内使用分离的楼梯键型。** 这种节奏类型的切换键型很难击打，只应在歌曲合适的时候使用。
keep

2022-02-16 09:24 UTC, RushFTK commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **避免在连续的 1/8 切换键型内使用多押。** 这对于这个分段的玩家来说太难掌握。尤其是当 Insane 当做谱面的最低难度时。并且，不合理的多押可能会无意导致 1/4 子弹出现。允许在切换头尾放置多押。
```suggestion
- **避免在连续的 1/8 切换键型内使用多押。** 这对于这个分段的玩家来说太难掌握。当 Insane 为谱面集的最低难度时，这点需要尤其注意。另外，不合理的多押可能会无心造成 1/4 的子弹键型。允许在切换键型的头、尾放置多押。
```

2022-02-16 09:25 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **若使用瞬时变速，则只能从其他速度突变为 1.0x。** 并且，瞬时变速只能在物件之间的空白段使用。
感觉我们俩的翻译都有点偏差，我等会重新翻一下

2022-02-16 09:26 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **当不需要标准化谱面滑条速度时，变速梗前后应给玩家留 1/4 拍或更长的反应时间；而需要标准化时，则需要留至少 1/2 拍。**
keep

2022-02-16 09:39 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **应谨慎使用裤衩切换键型。**
keep

2022-02-16 10:12 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **切换 (Stream)：** 不包含叠，同轨物件之间连续拥有至少相隔一拍的间距的一类键型。
keep，因为 叠 包含 子弹 所以使用更大范围的称呼。

2022-02-16 10:12 UTC, YumeMuzi commented on wiki/Ranking_Criteria/osu!mania/zh.md
> +- **连续的 1/4 切换键型至少应在乐句之后（通常是每 4 小节）留出一段很自然的 1/2 拍空白。** 否则，这对于这个分段的玩家来说太累。
等会改

2022-02-16 13:24 UTC, RushFTK approved these changes
looks fine for a native speaker.

2022-02-16 16:03 UTC, TicClick approved these changes

2022-02-16 16:04 UTC, merged