add Chinese translate of `Performance_troubleshooting`
ppy/osu-wiki pull request #6875
Opened 2022-02-11 13:47 UTC by cdwcgt

Co-Authored-By: Dead_Bush_Sanpai <46657591+DeadBushSanpai@users.noreply.github.com>

- [ ] Need `Power Saving` and `Optimal` be translate
- [ ] frame pacing????

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-21 13:26 UTC, Kotoki1337 commented on wiki/Performance_troubleshooting/zh.md
> +不幸的是吗，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，但也会提供你可以学习的特定术语（以及你可以做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
```suggestion
不幸的是，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，但也会提供你可以学习的特定术语（以及你可以做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
```

2022-02-21 13:26 UTC, Kotoki1337 commented on wiki/Performance_troubleshooting/zh.md
> +不幸的是吗，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，但也会提供你可以学习的特定术语（以及你可以做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
```suggestion
不幸的是，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，同时也会教你学习的特定术语（以及你能做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
```
做个建议，我读好几遍都不顺，你看着调整一下？

2022-02-21 13:26 UTC, Kotoki1337 commented on wiki/Performance_troubleshooting/zh.md
> +- 打开任务管理器并按 CPU 排序（在详细信息下）。查找低帧率时CPU使用率高的程序，例如由后台病毒或杀毒软件。你可以在使用 Auto 让 osu! 自动播放谱面时，窗口化 osu! 或使用第二块屏幕显示任务管理器来诊断问题。
```suggestion
- 打开任务管理器并按 CPU 排序（在详细信息下）。查找低帧率时 CPU 使用率高的程序，例如潜在的病毒或杀毒软件。你可以在使用 Auto 让 osu! 自动播放谱面时，窗口化 osu! 或使用第二块屏幕显示任务管理器来诊断问题。
```

2022-02-21 14:19 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +不幸的是吗，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，但也会提供你可以学习的特定术语（以及你可以做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
主要是 原句就是 `provides specific terms you can learn` 才写成 提供你可以学习的特定术语`
`同时也能让你学习故障排除所需要的特定术语` 比原文多 但是意思应该也是得当的

2022-02-21 14:20 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +在使用无限制前请优先使用此设置以减少渲染的帧数，从而降低[垃圾回收](https://zh.wikipedia.org/wiki/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6_(%E8%A8%88%E7%AE%97%E6%A9%9F%E7%A7%91%E5%AD%B8))所需要的性能（他可能会导致屏幕卡顿）。
有没有可能 能放俩
太烂了也真的恶

2022-02-21 14:21 UTC, Kotoki1337 commented on wiki/Performance_troubleshooting/zh.md
> +不幸的是吗，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，但也会提供你可以学习的特定术语（以及你可以做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
也成，润化润化就行，不然读着都不顺

2022-02-21 14:22 UTC, Kotoki1337 commented on wiki/Performance_troubleshooting/zh.md
> +在使用无限制前请优先使用此设置以减少渲染的帧数，从而降低[垃圾回收](https://zh.wikipedia.org/wiki/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6_(%E8%A8%88%E7%AE%97%E6%A9%9F%E7%A7%91%E5%AD%B8))所需要的性能（他可能会导致屏幕卡顿）。
是在不行就继续放着wikipedia

2022-02-21 14:23 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +不幸的是吗，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，但也会提供你可以学习的特定术语（以及你可以做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
那就是
```suggestion
不幸的是，由于运行设备的偏差，osu! 很难确保每个用户可以得到最佳性能。这个页面旨在帮助你自我诊断你遇到的性能问题，同时也能让你学习故障排除所需要的特定术语（以及你可以做的检查）来帮助我们在你寻求帮助时能为你提供帮助。
```
这个`吗`真的难绷 超

2022-02-22 07:05 UTC, kj415j45 requested changes

2022-02-22 07:05 UTC, kj415j45 commented on wiki/Performance_troubleshooting/zh.md
> +即便如此，如果发热和潜在的硬件过度工作不被视为问题，无限制设置可能是提供最稳定帧数的选项。
```suggestion
即便如此，如果发热和潜在的过度使用硬件不是问题，无限制设置可能是提供最稳定帧数的选项。
```

2022-02-22 07:08 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +osu! 会尽最大努力以合理的默认设置运行，并在你正在执行/运行某些会导致游戏性能下降的事情时主动提醒您。
'允许...的事情'感觉很怪
而且实际上只见过 osu！在笔记本未连接电源的情况下会提醒
所以用了'做...的事'

2022-02-22 07:10 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +谱面音频倒带或故障。基本上在游戏卡顿时可以在音频中听到。当报告或诊断此问题时，以下方法可能会提供帮助：
但是原文直译确实是故障
我倒倾向于
'音频听起来不正常'

2022-02-22 07:12 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +- 确保你启动了[游戏模式](https://support.xbox.com/zh-CN/help/games-apps/game-setup-and-play/use-game-mode-gaming-on-pc)<!-- 有没有更好的国内文章能贴啊 -->。它可以让 Windows 为 osu! 提供专用核心和资源。
改注释为这句吗？

2022-02-22 07:13 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +- 打开任务管理器并按 CPU 排序（在详细信息下）。查找低帧率时 CPU 使用率高的程序，例如由后台病毒或杀毒软件。你可以在使用 Auto 让 osu! 自动播放谱面时，窗口化 osu! 或使用第二块屏幕显示任务管理器来诊断问题。
后台病毒不好说
毕竟原文就有
虽然很怪 我是不建议删

2022-02-22 07:54 UTC, kj415j45 commented on wiki/Performance_troubleshooting/zh.md
> +- 确保你启动了[游戏模式](https://support.xbox.com/zh-CN/help/games-apps/game-setup-and-play/use-game-mode-gaming-on-pc)<!-- 有没有更好的国内文章能贴啊 -->。它可以让 Windows 为 osu! 提供专用核心和资源。
也行，不过这篇帮助文章是有错的 https://t.me/macroshit/16162

2022-02-22 07:56 UTC, kj415j45 commented on wiki/Performance_troubleshooting/zh.md
> +- 打开任务管理器并按 CPU 排序（在详细信息下）。查找低帧率时 CPU 使用率高的程序，例如由后台病毒或杀毒软件。你可以在使用 Auto 让 osu! 自动播放谱面时，窗口化 osu! 或使用第二块屏幕显示任务管理器来诊断问题。
原文断句应该是：
`background((virus or malware) scanner)`

2022-02-22 13:26 UTC, RushFTK commented on wiki/Performance_troubleshooting/zh.md
> +osu! 会尽最大努力以合理的默认设置运行，并在你正在执行/运行某些会导致游戏性能下降的事情时主动提醒您。
同意，更正意见中，`运行……的事情` 词语不匹配，建议使用`执行……的操作`或`做……的事`

2022-02-23 12:41 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +osu! 会尽最大努力以合理的默认设置运行，并在你正在执行/运行某些会导致游戏性能下降的事情时主动提醒您。
我就用 `做...的事` 了

2022-02-23 12:44 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +- 打开任务管理器并按 CPU 排序（在详细信息下）。查找低帧率时 CPU 使用率高的程序，例如由后台病毒或杀毒软件。你可以在使用 Auto 让 osu! 自动播放谱面时，窗口化 osu! 或使用第二块屏幕显示任务管理器来诊断问题。
ok

2022-02-23 12:46 UTC, cdwcgt commented on wiki/Performance_troubleshooting/zh.md
> +这个限制设置旨在节省电量，同时提供一致的游戏体验。 它将以 2 倍显示器刷新率运行并尝试保持一致的帧同步<!--frame pacing是啥啊-->。
那这样就行？

2022-02-28 06:54 UTC, kj415j45 approved these changes

2022-03-03 08:43 UTC, Walavouchey requested changes
missing translation of changes introduced in https://github.com/ppy/osu-wiki/pull/6766 

https://github.com/ppy/osu-wiki/blob/master/wiki/Performance_troubleshooting/en.md?plain=1#L7-L12

2022-03-03 23:40 UTC, kj415j45 approved these changes

2022-03-04 05:20 UTC, Walavouchey approved these changes

2022-03-04 05:23 UTC, merged