[EN/RU] Update `COT22` to Quarterfinals
ppy/osu-wiki pull request #6882
Opened 2022-02-14 17:50 UTC by Kimitakari

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-02-14 18:53 UTC, Walavouchey commented
i've pushed some changes to fix some formatting errors. take a look at the commits so you know for next time 👍

2022-02-14 19:02 UTC, TicClick requested changes

2022-02-14 19:02 UTC, TicClick commented on wiki/Tournaments/COT/2022/ru.md
> +### 1/8 раунда
аналогично во всех остальных местах
```suggestion
### 1/8 финала
```

2022-02-14 19:02 UTC, TicClick commented on wiki/Tournaments/COT/2022/ru.md
> +Суббота, 12 Февраля 2022:
в русском языке названия месяцев пишутся со строчной буквы

2022-02-14 19:03 UTC, TicClick commented on wiki/Tournaments/COT/2022/ru.md
> +Суббота, 12 Февраля 2022:
не только тут, но и в остальных разделах

2022-02-14 20:36 UTC, Kimitakari commented on wiki/Tournaments/COT/2022/ru.md
> +Суббота, 12 Февраля 2022:
Исправил

2022-02-14 22:06 UTC, TicClick commented
я посмотрел на перевод попристальнее, предлагаю такие варианты (терминологию брал с [википедии](https://en.wikipedia.org/wiki/Single-elimination_tournament#Nomenclature))
- qualifiers -> отборочный этап
- round of 16 -> 1/8 финала
- round of 24 -> 1/16 финала

2022-02-15 13:39 UTC, TicClick approved these changes

2022-02-15 13:45 UTC, merged