[ZH] Update `Beatmap\Difficulty`
ppy/osu-wiki pull request #6895
Opened 2022-02-18 07:10 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-22 07:19 UTC, kj415j45 commented on wiki/Beatmap/Difficulty/zh.md
> +难度内的击打物件在不同的游戏模式内可以组成不同样式的[排列](/wiki/Beatmap/Pattern)，它能反映难度的整体外观和给玩家的感觉。谱师可以通过调整繁多的[谱面难度设定](/wiki/Client/Beatmap_editor/Song_Setup#difficulty)或者玩家可以开启不同的[游戏模组 (Mods)](/wiki/Game_modifier) 来影响谱面的实际游玩
```suggestion
各模式下不同的击打物件所构成的[排列](/wiki/Beatmap/Pattern)，为难度的观感奠定基调。谱师可以通过调整多样的[谱面难度设定](/wiki/Client/Beatmap_editor/Song_Setup#difficulty)或者玩家可以开启不同的[游戏模组（Mods）](/wiki/Game_modifier) 来影响谱面的实际游玩难度。
```
4个不能算繁多吧 :thinking:

第一句还需要再斟酌一下，我这个译法肯定也不行。

2022-02-22 07:19 UTC, kj415j45 commented on wiki/Beatmap/Difficulty/zh.md
>  # 难度
```suggestion
# 难度（Difficulty）
```

2022-02-22 07:19 UTC, kj415j45 commented on wiki/Beatmap/Difficulty/zh.md
> +*请勿与[谱面](/wiki/Beatmap)相混淆。*
```suggestion
*请勿与[谱面（Beatmap）](/wiki/Beatmap)相混淆。*
```

2022-02-22 07:19 UTC, kj415j45 commented on wiki/Beatmap/Difficulty/zh.md
> +**难度**是以[`.osu` 后缀名](/wiki/osu!_File_Formats/Osu_(file_format))存储，用于区分一张谱面内不同的游戏难度等级的文本文件。它包含了为歌曲量身定制、测定好[时间轴](/wiki/Beatmapping/Timing_section)并用于特定[游戏模式](/wiki/Game_mode)的[击打物件](/wiki/Hit_object)。不
```suggestion
**难度**是以[`.osu` 后缀名](/wiki/osu!_File_Formats/Osu_(file_format))存储，用于区分一张谱面内不同的游戏难度等级的文本文件。它包含了为歌曲量身定制、测定好[时间轴](/wiki/Beatmapping/Timing_section)和用于特定[游戏模式](/wiki/Game_mode)的[击打物件](/wiki/Hit_object)。不同难度有不同的定位，对玩家的考验也不同。通常难度名和[谱面星级](/wiki/Beatmapping/Star_rating)就能提示玩家它的游玩难度有多高。
```

2022-02-22 07:19 UTC, kj415j45 commented on wiki/Beatmap/Difficulty/zh.md
> +在 [AIMod](/wiki/Client/Beatmap_editor/AiMod) 工具内或一些场合下，会按照以下谱面星级范围给难度赋予一个特定的标识：
```suggestion
在 [AiMod](/wiki/Client/Beatmap_editor/AiMod) 工具内或一些场合下，会按照以下谱面星级范围给难度赋予一个特定的标识：
```

2022-02-22 10:26 UTC, YumeMuzi commented on wiki/Beatmap/Difficulty/zh.md
> +难度内的击打物件在不同的游戏模式内可以组成不同样式的[排列](/wiki/Beatmap/Pattern)，它能反映难度的整体外观和给玩家的感觉。谱师可以通过调整繁多的[谱面难度设定](/wiki/Client/Beatmap_editor/Song_Setup#difficulty)或者玩家可以开启不同的[游戏模组 (Mods)](/wiki/Game_modifier) 来影响谱面的实际游玩
差不多拉 我觉得这句没啥问题 keep

2022-02-28 06:54 UTC, kj415j45 submitted a review, later dismissed

2022-02-28 09:27 UTC, RushFTK requested changes

2022-02-28 09:27 UTC, RushFTK commented on wiki/Beatmap/Difficulty/zh.md
> +**难度**是以[`.osu` 后缀名](/wiki/osu!_File_Formats/Osu_(file_format))存储，用于区分一张谱面内不同的游戏难度等级的文本文件。它包含了为歌曲量身定制、测定好[时间轴](/wiki/Beatmapping/Timing_section)和用于特定[游戏模式](/wiki/Game_mode)的[击打物件](/wiki/Hit_object)。不
```suggestion
谱面中的**难度**是一个以[`.osu` 后缀名]文本文件(/wiki/osu!_File_Formats/Osu_(file_format))存储的游戏关卡。它包含了为歌曲量身定制、测定好[时间轴](/wiki/Beatmapping/Timing_section)和用于特定[游戏模式](/wiki/Game_mode)的[击打物件](/wiki/Hit_object)。不同难度有不同的定位，对玩家的考验也不同。通常难度名和[谱面星级](/wiki/Beatmapping/Star_rating)足以显示难度所具有的挑战性。
```
**你必须进行修改**

难度不是一个文件，只是以文件的形式存储。

[关卡的中文维基](https://zh.wikipedia.org/wiki/%E9%97%9C%E5%8D%A1_(%E9%9B%BB%E5%AD%90%E9%81%8A%E6%88%B2))

> A beatmap's difficulty is a game level, which is stored as a text file with [the .osu extension](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_File_Formats/Osu_(file_format)). It consists of [hit objects](https://github.com/ppy/osu-wiki/blob/master/wiki/Hit_object) of a certain [game mode](https://github.com/ppy/osu-wiki/blob/master/wiki/Game_mode), which are set up accordingly to the [timing](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Timing_section) tailored to a specific song.

2022-02-28 09:27 UTC, RushFTK commented on wiki/Beatmap/Difficulty/zh.md
> +难度内的击打物件在不同的游戏模式内可以组成不同样式的[排列](/wiki/Beatmap/Pattern)，它能反映难度的整体外观和给玩家的感觉。谱师可以通过调整繁多的[谱面难度设定](/wiki/Client/Beatmap_editor/Song_Setup#difficulty)或者玩家可以开启不同的[游戏模组 (Mods)](/wiki/Game_modifier) 来影响谱面的实际游玩
```suggestion
据游戏模式、游玩难度、音乐的旋律及给人带来感觉的不同，难度中击打物件所组成的[排列](/wiki/Beatmap/Pattern)不尽相同。谱师可以通过调整多种[谱面难度设定](/wiki/Client/Beatmap_editor/Song_Setup#difficulty)或者玩家可以开启不同的[游戏模组 (Mods)](/wiki/Game_modifier) 来影响谱面的实际游玩难度。
```
"音乐的旋律及给人带来感觉"不知道直接用音调音色合适不合适，感觉你的翻译与原文有些出入。  
我也觉得4种也不叫繁多……主要原文也没有相应的含义。。。 
> A beatmap's difficulty is a game level, which is stored as a text file with [the .osu extension](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_File_Formats/Osu_(file_format)). It consists of [hit objects](https://github.com/ppy/osu-wiki/blob/master/wiki/Hit_object) of a certain [game mode](https://github.com/ppy/osu-wiki/blob/master/wiki/Game_mode), which are set up accordingly to the [timing](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Timing_section) tailored to a specific song. Difficulties have different aspects, which directly affect user experience. The difficulty name and [star rating](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Star_rating) usually give enough information to tell how challenging it is.

2022-02-28 09:27 UTC, RushFTK commented on wiki/Beatmap/Difficulty/zh.md
> +与排列不同的是，难度的[视觉组件](/wiki/Beatmap)通常能提供辅助层次的体验，在大多数情况下，也可以在[视觉设置](/wiki/Client/Interface/Visual_settings)页面关闭它们。某些谱面所含的特殊视觉组件（如：[故事板](/wiki/Storyboard)或者[谱面皮肤](/wiki/Skinning)）通常与谱面组成一个整体，而且大多数视觉组件在不同难
```suggestion
与排列不同的是，难度的[视觉组件](/wiki/Beatmap)通常能提供辅助层次的体验，在大多数情况下，也可以在[视觉设置](/wiki/Client/Interface/Visual_settings)页面关闭它们。大多数视觉组件（如：[kiai 时间](/wiki/Gameplay/Kiai_time)和 [combo 颜色](/wiki/Glossary/Combo_colour)）各难度相互独立，而有些视觉组件（如：[故事板](/wiki/Storyboard)或者[谱面皮肤](/wiki/Skinning)）是谱面所有难度共享的。
```

> While some of them, such as [storyboards](https://github.com/ppy/osu-wiki/blob/master/wiki/Storyboard) or [custom skins](https://github.com/ppy/osu-wiki/blob/master/wiki/Skinning), belong to the beatmap as a whole, most of the visual components may vary per difficulty (e.g., [kiai time](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Kiai_time) sections and [combo colours](https://github.com/ppy/osu-wiki/blob/master/wiki/Glossary/Combo_colour)).

2022-03-06 06:11 UTC, RushFTK approved these changes

2022-03-06 07:55 UTC, Walavouchey approved these changes

2022-03-06 07:56 UTC, merged