[ZH] Add `Beatmap\Genre_and_language`
ppy/osu-wiki pull request #6896
Opened 2022-02-18 09:51 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-18 14:47 UTC, Walavouchey requested changes

2022-02-18 14:47 UTC, Walavouchey commented on wiki/Beatmap/Genre_and_language/zh.md
> +tags:
the original tags need to be present as well

```suggestion
tags:
  - genres
  - languages
  - metadata
```

2022-03-01 01:51 UTC, RushFTK requested changes

2022-03-01 01:51 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +歌曲风格与语言不会影响游玩，但能在新版客户端 (lazer 版)内用于搜索。
```suggestion
除了能在新版客户端 (lazer 版)内用于搜索以外，歌曲风格与语言在客户端中没有任何实际功能。
```

原文主要强调对于stable客户端没有根据这两个属性进行任何程序化的实现，但是我也不知道怎么说比较好。   
不会影响游玩只是代表缺乏一部分影响游戏体验的功能。例如ID也不会影响游戏游玩，但也会再界面中进行展示，也可以用于定位和搜索其他玩家。

2022-03-01 01:51 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +谱面的歌曲风格与语言能通过在谱面详情处悬停光标，并点击铅笔按钮来修改。修改权限取决于玩家所在的[用户组](/wiki/People/The_Team#user-groups)和[谱面状态](/wiki/Beatmap/Category#present-categories)：
```suggestion
谱面的歌曲风格与语言能通过在谱面详情页面点击铅笔样式的图标来修改。修改权限取决于玩家所在的[用户组](/wiki/People/The_Team#user-groups)和[谱面状态](/wiki/Beatmap/Category#present-categories)：
```
>Genre and language can be changed on the website by clicking the pencil icon when hovering over a beatmap's details.
刚才确认了一下，事实上在搜索的浮窗中好像也不能修改了，所以直接意译吧。

2022-03-01 01:51 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +歌曲风格或语言标注为`未指定 (Unspecified)` 的谱面无法审核<!-- TODO: link -->通过。
```suggestion
歌曲风格或语言标注为`未指定 (Unspecified)` 的谱面无法被提名<!-- TODO: link -->。
```

上面既然用了提名，这里就仍然用提名吧。

2022-03-01 01:51 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +| 古典 (Classical) | 以先进的音乐理论为基础的，在古老西方文化背景下创作的庄重的歌曲。 |
```suggestion
| 古典 (Classical) | 以高等乐理为基础构建的庄重歌曲，其在古老西方文化背景下创作或自其启发灵感。 |
```
> Formal, structured around advanced musical theory, and having roots in old western culture or taking inspiration from it.

**你必须修正此条**

"先进的"是一个时序上的用词，他的反义词是落后的，事实上其他风格的音乐并不是落后的。 
而"高级"和"初级"是常用于区别某学科广度和深度之间区别的词语。
举例来说，`Advanced mathematics`一般翻译为高等数学而不是先进的数学，主要也是初高中学的初等数学也并不是落后的，实际上初等数学在实际生活中更加常用。  
剩下的是有几个词漏翻了，还有原文是主语省略的，也许找几个老手前辈确认比较好。

2022-03-01 01:51 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +| 嘻哈 (Hip Hop) | 通常伴随说唱 (rap)，节拍或低音有时采样于唱片的风格化节奏歌曲。（参见：[维基百科*嘻哈乐*](https://zh.wikipedia.org/wiki/%E5%98%BB%E5%93%88%E9%9F%B3%E6%A8%82)） |
```suggestion
| 嘻哈 (Hip Hop) | 通常伴随说唱 (rap)的风格化节奏歌曲，有时还夹杂着预录制的 beats 或 bass 采样。（参见：[维基百科*嘻哈乐*](https://zh.wikipedia.org/wiki/%E5%98%BB%E5%93%88%E9%9F%B3%E6%A8%82)） |
```
> "Stylised rhythmic music that commonly accompanies rapping," sometimes "sampling beats or bass lines from records" ([Hip hop music on Wikipedia](https://en.wikipedia.org/wiki/Hip_hop_music)).

beats or bass 咋翻译啊，我觉得我翻译的也不好，但是不能翻译为鼓点和贝斯吧（）
所以我建议不翻译……

2022-03-01 01:51 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +- 汉语 (Chinese)
```suggestion
- 华语 (Chinese)
```
*可以忽视的更正翻译*

~~周董说的是汉语吗~~。
而且感觉其他地区的中文歌曲也可以归为Chinese，例如马新那边的？

2022-03-06 06:15 UTC, YumeMuzi commented on wiki/Beatmap/Genre_and_language/zh.md
> +谱面的歌曲风格与语言能通过在谱面详情处悬停光标，并点击铅笔按钮来修改。修改权限取决于玩家所在的[用户组](/wiki/People/The_Team#user-groups)和[谱面状态](/wiki/Beatmap/Category#present-categories)：
需要悬停的呀 在你自己的谱面的来源那一块悬停才会出现铅笔图标。
your mouse must hover over the area around *source* then the pencil icon is shown.

2022-03-06 06:18 UTC, YumeMuzi commented on wiki/Beatmap/Genre_and_language/zh.md
> +- 汉语 (Chinese)
华语和汉语的概念基本相同，但华语主要在国际场合使用，国内使用频率*较少*（最常看到这个词的地方是在歌坛）。汉语国际国内都常用。

2022-03-06 06:19 UTC, YumeMuzi commented on wiki/Beatmap/Genre_and_language/zh.md
> +| 嘻哈 (Hip Hop) | 通常伴随说唱 (rap)，节拍或低音有时采样于唱片的风格化节奏歌曲。（参见：[维基百科*嘻哈乐*](https://zh.wikipedia.org/wiki/%E5%98%BB%E5%93%88%E9%9F%B3%E6%A8%82)） |
无所谓，这里甚至国内的音乐平台也基本上没弄懂，国内乐理知识的翻译和传播一团糟

2022-03-07 04:19 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +谱面的歌曲风格与语言能通过在谱面详情处悬停光标，并点击铅笔按钮来修改。修改权限取决于玩家所在的[用户组](/wiki/People/The_Team#user-groups)和[谱面状态](/wiki/Beatmap/Category#present-categories)：
ok

2022-03-07 04:19 UTC, RushFTK commented on wiki/Beatmap/Genre_and_language/zh.md
> +- 汉语 (Chinese)
ok

2022-03-07 04:19 UTC, RushFTK approved these changes

2022-03-07 07:15 UTC, Walavouchey approved these changes

2022-03-07 07:16 UTC, merged