[ZH] Update `Beatmap`
ppy/osu-wiki pull request #6899
Opened 2022-02-18 13:47 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-28 08:56 UTC, RushFTK requested changes
two of comments are fixing incorrect translation , others are just opinions.

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +- 以 MP3 或 Ogg 格式存储的歌曲。
```suggestion
- 所有难度所面向的，以 MP3 或 Ogg 格式存储的歌曲自身。
```

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +*注意：部分谱面的视觉或听觉效果可在[视觉设置](/wiki/Client/Interface/Visual_settings)叠加层内关闭。*
mark：需要确定overlay的常用翻译是什么。按字面意思翻译为叠加层也是可以接受的。

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +**难度**是以[`.osu` 后缀名](/wiki/osu!_File_Formats/Osu_(file_format))存储，包含了击打物件位置、音效、类似于 [kiai 时间](/wiki/Gameplay/Kiai_time)特殊效果的文件。它也包含一些像[谱面难度设定](/wiki/Client/Beatmap_editor/Song_Setup#difficulty)之类会影响游玩
```suggestion
**难度**是一个包含了击打物件位置、音效、诸如[kiai 时间](/wiki/Gameplay/Kiai_time)等特殊效果的文件，以[`.osu` 后缀名](/wiki/osu!_File_Formats/Osu_(file_format))来存储。它也包含一些像[难度设定](/wiki/Client/Beatmap_editor/Song_Setup#difficulty)之类会影响游玩的参数。谱面中的不同难度有不同的结构，有时候只能在一个[游戏模式](/wiki/Game_mode)下游玩。[谱面星级](/wiki/Beatmapping/Star_rating)系统用于可视化描述难度需要的实力水平。
```
**你必须修改这条。** 
 
`Difficulties of a beatmap ` 指**同一**谱面中的不同难度，谱面在定义中本身是集合。 
所有的游戏关卡均需翻译成"难度"。

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +谱师能把自己创作的谱面[提交](/wiki/Submission)至公共[谱面列表](https://osu.ppy.sh/beatmapsets)。同时每张谱面都属于[一个人](/wiki/Beatmap/Beatmap_host)。但谱面通常是多人合作：有些难度可能是由其他谱师[合作](/wiki/Beatmap/Beatmap_collaborations)或由其他谱师[单人制作](/wi
```suggestion
谱面作者（以下简称谱师）能把自己的作品[提交](/wiki/Submission)至公共[谱面列表](https://osu.ppy.sh/beatmapsets)。同时每张谱面都属于[一个人](/wiki/Beatmap/Beatmap_host)。但谱面通常是多人合作：有些难度可能是作者与其他谱师[合作](/wiki/Beatmap/Beatmap_collaborations)或由其他谱师[单独制作](/wiki/Beatmap/Guest_difficulty)。
```
其实可以不改，只是规范一下第一次出现的名词“谱师”的定义。

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +提交完成后，在谱面的网页上，谱师就获得了一块额外的能用于填写元数据的区域，比如谱面介绍、语言、歌曲风格、敏感内容提示。提交后的谱面还能够修改在开始游玩时显示在游玩区域上的[标题文本](/wiki/Beatmap/Title_text)，能通过寻求[审核评估团队](/wiki/People/The_Team/Nomination_Assessment_Team)成员的帮助来修改。
```suggestion
提交完成后，谱师就获得了一些可在谱面的网页修改的额外元数据字段，其包含谱面介绍、语言、歌曲风格、敏感内容提示等。在[审核评估团队](/wiki/People/The_Team/Nomination_Assessment_Team)成员的帮助下，谱师还能够修改在开始游玩时显示在游玩区域上的[标题文本](/wiki/Beatmap/Title_text)。
```

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +### 识别
```suggestion
### 标识符
```

Identification词性为名词。

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +有些谱面状态包含[提交规则](/wiki/Ranking_Criteria)，同时，变更为这种状态的谱面会获得[排行榜](#leaderboards)。谱面获得排行榜的主流方法是通过[谱面上架 (Ranking) 程序](/wiki/Beatmap_ranking_procedure)，另一种方法是让谱面进入[社区喜爱 (loved)](Category#loved)状态。
```suggestion
有些谱面状态包含[提交规则](/wiki/Ranking_Criteria)，同时，变更为这种状态的谱面会获得临时或永久的[排行榜](#leaderboards)。谱面获得排行榜的主流方法是通过[谱面上架 (Ranking) 程序](/wiki/Beatmap_ranking_procedure)，另一种方法是让谱面进入[社区喜爱 (loved)](Category#loved)状态。
```

>…… and enable the beatmaps to have transient or permanent [leaderboards](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/en.md#leaderboards). The most popular way of achieving that ……

指出这点其实想看你有意忽略这两个词语的原因。

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +能使用以下几种方法来下载谱面：
```suggestion
能使用以下几种方法来获取谱面：
```

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +所有模式的 osu! 玩家都会根据谱面成绩来[全球排名](/wiki/Performance_points)并[互相竞争](/wiki/Ranking)。osu! 拥有特定游戏模式的排行榜。普通玩家只能看到全球排行榜，而 [osu! 支持者](/wiki/osu!supporter)能看到其他排行榜
```suggestion
所有模式的 osu! 玩家都会根据谱面成绩来[全球排名](/wiki/Performance_points)并[互相竞争](/wiki/Ranking)。在 osu! 中，每个谱面均拥有独立的，不同种类的的排行榜。普通玩家只能看到全球排行榜，而 [osu! 支持者](/wiki/osu!supporter)能看到其他排行榜
```

**你必须修改这条。**  

>osu! has different types of beatmap-specific leaderboards,

这里主要强调不同谱面(其实原文甚至有误，个人认为应用difficults) 的排行榜相互独立。

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +- 好友排行榜。
```suggestion
- 显示玩家与好友间排名的好友排行榜。
```

>  Friend ranking that shows a player's position on the map compared to their friends.

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +- 国家/地区排行榜；
```suggestion
- 令拥有相同国/区旗玩家竞争的国家/地区专属排行榜；
```

> Country-specific ranking made of players bearing the same flag;

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +官方只提供全球排行榜前 500 名玩家的成绩[回放](/wiki/Gameplay/Replay)下载，玩家可以在线观看或者保存并显示在本地排行榜上。
```suggestion
对于每个难度，官方只提供全球排行榜前 500 名玩家成绩的[回放](/wiki/Gameplay/Replay)下载，玩家可以在线观看或者保存并显示在本地排行榜上。
```
> The top 500 scores on every difficulty of a beatmap provide [replays](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Replay), which can be watched online or saved for further display in a local leaderboard.

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +在早期建设时，社区就已出现多种多样的能展示独特和优秀的谱面（推图）的方法。其中一种就是收集一部分已上架 (Ranked) 谱面来举办季赛或月赛，顶流玩家依靠获得的总分来排名，靠前的玩家能获得 [osu! 支持者](/wiki/osu!supporter)作为奖品。
```suggestion
早期，社区就已出现多种方法展示独特和优秀的谱面（推图）。其中，也是最早被公式记录的一种方法就是收集一部分已上架 (Ranked) 谱面来举办月度或季度榜单，总分名列前茅的顶流玩家能获得 [osu! 支持者](/wiki/osu!supporter)作为奖品。
```

> One of the first documented approaches were monthly and seasonal charts consisting of a small subset of ranked beatmaps, where top players from leaderboards displaying total score across these maps would be awarded with [osu!supporter](https://github.com/ppy/osu-wiki/blob/master/wiki/osu!supporter).

有点翻译腔

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +osu! 社区经常举办不同的作图比赛来促进谱面创新和奖励优秀的谱师。作图比赛的规模通常可以小到仅由本地社区举办，或者大到全球参与，奖励极其丰厚。获胜的玩家通常能获得 [osu! 支持者](/wiki/osu!supporter)标签和独特的个人界面徽章。
```suggestion
osu! 社区经常举办不同的作图比赛来促进谱面创新和奖励优秀的谱师。这些作图比赛既有小到仅由本地社区举办的；也有全球参与，奖励极其丰厚的。优胜者通常能获得 [osu! 支持者](/wiki/osu!supporter)标签和独特的个人界面徽章。
```

2022-02-28 08:56 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +精选艺术家是 osu! 团队专注于为 osu! 提供，获得授权，可供作图的歌曲而推进的社区项目。[精选艺术家列表](https://osu.ppy.sh/beatmaps/artists)列出了所有参与的艺术家，并提供了预先准备好的谱面模板，可供作图使用。
```suggestion
精选艺术家是由 [osu! 团队](/wiki/People/The_Team)负责的社区项目。其专注于为 osu! 获取具有版权的歌曲以使其用于作图。[精选艺术家列表](https://osu.ppy.sh/beatmaps/artists)列出了所有涉及的艺术家，并提供预先准备好的谱面模板以便作图使用。
```

> Featured Artists is a community program by the [osu! team](https://github.com/ppy/osu-wiki/blob/master/wiki/People/The_Team) that focuses on licensing music by various artists for osu! and making it available for mapping. The website's [Featured Artist listing](https://osu.ppy.sh/beatmaps/artists) showcases each involved artist and provides pre-timed templates for mapping.

原翻译感觉读起来有些碎碎的，主语不太清楚。

2022-02-28 09:00 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +  - 谱面
你再难度页面的翻译中里加了英文标签，这里也把英文标签加上吧

2022-03-06 05:50 UTC, YumeMuzi commented on wiki/Beatmap/zh.md
> +- 以 MP3 或 Ogg 格式存储的歌曲。
你这也是翻译腔啊.....而且只需要提到歌曲文件就行了

2022-03-06 05:51 UTC, YumeMuzi commented on wiki/Beatmap/zh.md
> +*注意：部分谱面的视觉或听觉效果可在[视觉设置](/wiki/Client/Interface/Visual_settings)叠加层内关闭。*
这个是可行的

2022-03-06 05:55 UTC, YumeMuzi commented on wiki/Beatmap/zh.md
> +有些谱面状态包含[提交规则](/wiki/Ranking_Criteria)，同时，变更为这种状态的谱面会获得[排行榜](#leaderboards)。谱面获得排行榜的主流方法是通过[谱面上架 (Ranking) 程序](/wiki/Beatmap_ranking_procedure)，另一种方法是让谱面进入[社区喜爱 (loved)](Category#loved)状态。
我认为是原文的问题。“临时或永久的”已经包含了所有可能的状态。无需特意指出。
there is a contradiction, "transient or permanent" doesn't make any sense.

2022-03-06 05:59 UTC, YumeMuzi commented on wiki/Beatmap/zh.md
> +  - 谱面
这不是有吗
*mapset beatmapset* isn't here?

2022-03-06 06:01 UTC, YumeMuzi commented on wiki/Beatmap/zh.md
> +在早期建设时，社区就已出现多种多样的能展示独特和优秀的谱面（推图）的方法。其中一种就是收集一部分已上架 (Ranked) 谱面来举办季赛或月赛，顶流玩家依靠获得的总分来排名，靠前的玩家能获得 [osu! 支持者](/wiki/osu!supporter)作为奖品。
被公式记录的一种方法 是什么玩意

2022-03-06 06:12 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +*注意：部分谱面的视觉或听觉效果可在[视觉设置](/wiki/Client/Interface/Visual_settings)叠加层内关闭。*
ok

2022-03-06 06:12 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +  - 谱面
我瞎了

2022-03-06 06:13 UTC, RushFTK commented on wiki/Beatmap/zh.md
> +- 以 MP3 或 Ogg 格式存储的歌曲。
hmmm，先这样吧

2022-03-06 06:13 UTC, RushFTK approved these changes

2022-03-06 07:58 UTC, Walavouchey approved these changes

2022-03-06 08:00 UTC, merged