[ZH] Add `Guides\How_to_Time_Songs`
ppy/osu-wiki pull request #6933
Opened 2022-02-26 08:26 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-11 00:23 UTC, kj415j45 requested changes

2022-03-11 00:23 UTC, kj415j45 commented on wiki/Guides/How_to_Time_Songs/zh.md
> +如果你想飞图，那么请使用比特率处于 128 到 192 kbps 之间的歌曲文件（这确保了歌曲质量适中，也不会占据太多本地或云端的磁盘空间）。你可以通过右键歌曲文件，点击属性-详细信息来得知文件的比特率。如果你不知道如何压制文件降低比特率，请参见[音频编辑](/wiki/Guides/Audio_Editing)和[这个官方教学视频（跳转到 YouTube）](https://www.youtu
不应该使用“飞图”，因为没有任何上下文辅助解释这个黑话。

2022-03-11 00:23 UTC, kj415j45 commented on wiki/Guides/How_to_Time_Songs/zh.md
> +有个检查的小技巧，即跳到歌曲的中间部分或结尾部分听节拍器和歌曲节拍是否有偏差。同时，BPM 通常为一个整数。所以如果当前的 BPM 测得含有 0.1 或 0.01 这样的小数，
结尾漏句？

2022-03-11 00:23 UTC, kj415j45 commented on wiki/Guides/How_to_Time_Songs/zh.md
> +歌曲由许多重复的段落（小节）组成。这些重复的段落拥有相同的节奏构成方式（如动次打次）。你也可以参考[维基百科*拍子记号*](https://en.wikipedia.org/wiki/Time_signature)或者 [Alace 的讨论串](https://osu.ppy.sh/community/forums/topics/20998)获取更多信息。
使用中文的维基百科链接（如果有）

2022-03-11 00:23 UTC, kj415j45 commented on wiki/Guides/How_to_Time_Songs/zh.md
> +你只应该在测定复杂时间轴这一方面很有经验，或是谱面时间轴出现明显错误（比如你测得 175 BPM 而谱面为 150 BPM）时才能帮助别人测定。你需要知道自己在做什么。若你不能保证帮助修正后的结果更加准确，或可能对谱面上架没有帮助时，请不要急着去帮助他人。
> 你只应该在测定复杂时间轴这一方面很有经验，或是谱面时间轴出现明显错误（比如你测得 175 BPM 而谱面为 150 BPM）时才能帮助别人测定。

请重新翻译这一句。

2022-03-16 05:07 UTC, YumeMuzi commented on wiki/Guides/How_to_Time_Songs/zh.md
> +歌曲由许多重复的段落（小节）组成。这些重复的段落拥有相同的节奏构成方式（如动次打次）。你也可以参考[维基百科*拍子记号*](https://en.wikipedia.org/wiki/Time_signature)或者 [Alace 的讨论串](https://osu.ppy.sh/community/forums/topics/20998)获取更多信息。
中文维基不全。
Chinese Wikipedia leaves out a lot of things.

2022-03-16 05:09 UTC, YumeMuzi commented on wiki/Guides/How_to_Time_Songs/zh.md
> +如果你想飞图，那么请使用比特率处于 128 到 192 kbps 之间的歌曲文件（这确保了歌曲质量适中，也不会占据太多本地或云端的磁盘空间）。你可以通过右键歌曲文件，点击属性-详细信息来得知文件的比特率。如果你不知道如何压制文件降低比特率，请参见[音频编辑](/wiki/Guides/Audio_Editing)和[这个官方教学视频（跳转到 YouTube）](https://www.youtu
改成上架谱面算了

2022-03-16 05:16 UTC, YumeMuzi commented on wiki/Guides/How_to_Time_Songs/zh.md
> +有个检查的小技巧，即跳到歌曲的中间部分或结尾部分听节拍器和歌曲节拍是否有偏差。同时，BPM 通常为一个整数。所以如果当前的 BPM 测得含有 0.1 或 0.01 这样的小数，
加了

2022-03-16 05:26 UTC, YumeMuzi commented on wiki/Guides/How_to_Time_Songs/zh.md
> +你只应该在测定复杂时间轴这一方面很有经验，或是谱面时间轴出现明显错误（比如你测得 175 BPM 而谱面为 150 BPM）时才能帮助别人测定。你需要知道自己在做什么。若你不能保证帮助修正后的结果更加准确，或可能对谱面上架没有帮助时，请不要急着去帮助他人。
加上格式了

2022-03-17 01:06 UTC, kj415j45 submitted a review, later dismissed

2022-03-17 06:04 UTC, Walavouchey commented on wiki/Guides/How_to_Time_Songs/zh.md
> +第一条红线的偏移量 (offset) 即歌曲的第一拍与 .mp3 文件头部之间相隔的时间。参见：[维基百科*节奏*](https://zh.wikipedia.org/wiki/%E8%8A%82%E5%A5%8F)
```suggestion

第一条红线的偏移量 (offset) 即歌曲的第一拍与 .mp3 文件头部之间相隔的时间。参见：[维基百科*节奏*](https://zh.wikipedia.org/wiki/%E8%8A%82%E5%A5%8F)。
```

2022-03-17 11:51 UTC, merged