[FR] Update `Community/Forum/Off-Topic`
ppy/osu-wiki pull request #6939
Opened 2022-02-27 13:49 UTC by Corne2Plum3

Proposal to update the French translation of the wiki page  of `Community/Forum/Off-Topic`, which was recently updated by #6921.

* added the mention "abreviated by OT" at the beginning of the page.
* added the new parts of the page according to #6921.

It's my first contribution here, so maybe formatting and grammar is incorrect...

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-01 00:12 UTC, Bambinexx commented
I'll review stuff tomorrow, too tired for now

2022-03-01 11:26 UTC, Biokax requested changes

2022-03-01 11:26 UTC, Biokax commented on wiki/Community/Forum/Off-Topic/fr.md
> +Le forum de [General Discussions](https://osu.ppy.sh/community/forums/7) *(discussions générales)* à initialement contenu n'importe quelle sujet que les gens voulait en parler. Pendant que les jeux d
```suggestion
Le forum de [General Discussions](https://osu.ppy.sh/community/forums/7) *(discussions générales)* à initialement servie aux gens de pouvoir discuter de n'importe quelle sujet. Étant donné que les forums de jeux ont commencé à polluer le sous-forum, les personnes ont suggérés faire un sous-forum spécifique pour ces "fils auto-entretenus" [[1]][r]. Le 19 Février 2009, [peppy](/wiki/People/peppy) crée ce sous-forum suggéré : *Forum Games/Random* [[2]][r] [[3]][r].
```

2022-03-01 11:26 UTC, Biokax commented on wiki/Community/Forum/Off-Topic/fr.md
> +Le nouveau sous-forum a créé une distinction qui fait que *General Discussion* était utilisé pour les discussions sérieuses, pendant que *Forum Games/Random* était utilisé pour les discussions non-sé
```suggestion
Le nouveau sous-forum a créé une distinction qui fait que *General Discussion* était utilisé pour les discussions sérieuses, pendant que *Forum Games/Random* était utilisé pour les discussions non-sérieuses. Etant donné la nature de *Forum Games/Random*, les personnes interrompait parfois les sous-forum de jeux avec des conversations aléatoires. [[4]][r]. Le 2 Février 2010, *Forum Games/Random* a été renommé *Off-Topic* et le sous-forum *Forum Games* a été créé [[5]][r].
```

2022-03-01 11:26 UTC, Biokax commented on wiki/Community/Forum/Off-Topic/fr.md
> +Etant donnée la nature de OT, la majorité des fils et discussions étaient de qualité très pauvre. Les fils étaient rarement considérés bons, mais quand ces fils atteignaient ce niveau de qualité, les
```suggestion
Étant donnée la nature de OT, la majorité des fils et discussions étaient de très pauvre qualité. Les fils étaient rarement considérés bons, mais quand ces fils atteignaient ce niveau de qualité, les utilisateurs disaient qu'ils avaient atteint le Valhalla.
```

2022-03-01 11:26 UTC, Biokax commented on wiki/Community/Forum/Off-Topic/fr.md
> +L'**exil** est un concept de modération non-officiel introduit par [Ephemeral](https://osu.ppy.sh/users/102335) dans [the grand edict thread](https://osu.ppy.sh/community/forums/topics/604424) en rép
```suggestion
L'**exil** est un concept de modération non-officiel introduit par [Ephemeral](https://osu.ppy.sh/users/102335) dans [the grand edict thread](https://osu.ppy.sh/community/forums/topics/604424) en réponse aux personnes qui spammaient le sous-forum, notamment par la création de contenu embêtant. Le système d'exil est appliqué en supprimant n'importe quel fil, et même parfois des posts de la personne qui est exilée. Il sert d'indicateur quand une personne est sur le point d'être lourdement sanctionné par des moyens plus officielles par la modération.
```

2022-03-01 11:26 UTC, Biokax commented on wiki/Community/Forum/Off-Topic/fr.md
> +Depuis que le sous-forum Off-Topic est principalement composé des mêmes personnes qui discutent entre eux dans les fils, tout le monde se connaît. Ceux qui restent suffisamment longtemps pour être co
```suggestion
Depuis que le sous-forum Off-Topic est principalement composé des mêmes personnes qui discutent entre elles dans les fils, tout le monde se connaît. Ceux qui restent suffisamment longtemps pour être considérés comme utilisateur réguliers sont appelés "**denizens**" *("citoyens" en français)*. Ce terme a été utilisé pour la première fois par [Ephemeral](https://osu.ppy.sh/users/102335) sur [ce post](https://osu.ppy.sh/community/forums/posts/1607086), mais n'a pas été adopté par les utilisateurs réguliers qu'à partir de la populaire série de fils [OT!News](https://osu.ppy.sh/community/forums/topics/577518).
```

2022-03-02 17:26 UTC, Corne2Plum3 commented on wiki/Community/Forum/Off-Topic/fr.md
> +[**Off-Topic**](https://osu.ppy.sh/community/forums/52) (abrégé par ***OT***) est un forum destiné à permettre à la communauté d'avoir des conversations sans sujet particulier. Les fils de discussion
I'll put this modification as is.

2022-03-02 17:29 UTC, Corne2Plum3 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Le nouveau sous-forum a créé une distinction qui fait que *General Discussion* était utilisé pour les discussions sérieuses, pendant que *Forum Games/Random* était utilisé pour les discussions non-sé
Seems better than what I made

2022-03-02 17:30 UTC, Corne2Plum3 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Etant donnée la nature de OT, la majorité des fils et discussions étaient de qualité très pauvre. Les fils étaient rarement considérés bons, mais quand ces fils atteignaient ce niveau de qualité, les
ok

2022-03-03 12:10 UTC, Ganondorf-1 requested changes

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Depuis que le sous-forum Off-Topic est principalement composé des mêmes personnes qui discutent entre elles dans les fils, tout le monde se connaît. Ceux qui restent suffisamment longtemps pour être
```suggestion
Puisque que le sous-forum Off-Topic est principalement composé des mêmes utilisateurs qui discutent entre eux dans les fils, tout le monde se connaît. Ceux qui restent suffisamment longtemps pour être considérés comme utilisateurs réguliers sont appelés "**denizens**" *("citoyens" en français)*. Ce terme a été utilisé pour la première fois par [Ephemeral](https://osu.ppy.sh/users/102335) sur [ce post](https://osu.ppy.sh/community/forums/posts/1607086), mais n'a pas été adopté par les utilisateurs réguliers qu'à partir de la populaire série de fils [OT!News](https://osu.ppy.sh/community/forums/topics/577518).
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Le **lore d'Off-Topic** est un effort lancé par [abraker](https://osu.ppy.sh/users/4635891) et entretenu par les autres *denizens* pour créer un arc narratif des différents fils que les personnes ont
```suggestion
Le **lore d'Off-Topic** est un effort lancé par [abraker](https://osu.ppy.sh/users/4635891) et entretenu par les autres *denizens* pour créer un arc narratif des différents fils que les utilisateurs ont créé dans OT. Le meilleur de cet effort a été compilé dans le fil [OT!Chronicles](https://osu.ppy.sh/community/forums/posts/6230570), qui a créé une timeline de plusieurs fils de role-play improvisés dans OT.
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Le **déraillement de fil** est une occurrence commune dans le sous-forum Off-Topic à cause de sa nature "hors-sujet". Cela signifie que les fils crées avec un sujet en particulier ne peuvent pas forc
```suggestion
Le **déraillement de fil** est une occurrence commune dans le sous-forum Off-Topic à cause de sa nature "hors-sujet". Cela signifie que les fils créés avec un sujet en particulier peuvent ne pas forcément garder ce même sujet.
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Bien que la majorité des fils dans OT sont des bêtises ou d'autres contenus sans importance, il y a quelques fils notables que les personnes non familiers avec le sous-forum pourraient trouver intére
```suggestion
Bien que la majorité des fils dans OT sont des bêtises ou d'autres contenus sans importance, il y a quelques fils notables que les utilisateurs non familiers avec le sous-forum pourraient trouver intéressant.
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +OT court est un élément du lore d'OT qui imite de manière détaillé un procès. Cette organisation a été improvisé lors de sa création, et contre toute attente, est resté du début jusqu'à la fin sans p
```suggestion
OT court est un élément du lore d'OT qui imite de manière détaillée un procès. Son organisation a été improvisée lors de sa création, et contre toute attente, est restée du début jusqu'à la fin sans perdre d'intérêt ou sans être déraillée.
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Ce fil est une blague qui a été développé dans le lore d'OT. C'est un bon exemple de comment les *denizens* peuvent créer des fils-blagues à propos de chacun, et par la suite créer une narration à pa
```suggestion
Ce fil est une blague qui a été développée dans le lore d'OT. C'est un bon exemple de comment les *denizens* peuvent créer des fils-blagues à propos de chacun, et par la suite créer une narration à partir des interactions de ce fil. Il montre également la nature imprévisible de l'évolution des fils et comment des bêtises et des choses inattendues peuvent apparaître à partir de ces fils.
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +C'est l'un des fils de role-playing résultant du lore d'OT, qui a crée un  improvisé récit intéressant impliquant un méga-télétubbie divin qui fait des ravages dans OT et que les *denizens* essaient
```suggestion
C'est l'un des fils de role-playing résultant du lore d'OT, qui a créé un intéressant récit improvisé impliquant un méga-télétubby divin qui fait des ravages dans OT et que les *denizens* essaient de vaincre.
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +2. [L'annoncement de peppy du nouveau sous-forum](https://osu.ppy.sh/community/forums/posts/8814)
```suggestion
2. [L'annonce de peppy du nouveau sous-forum](https://osu.ppy.sh/community/forums/posts/8814)
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +5. [Réactions de personnes du changement du sous-forum Of-Topic](https://osu.ppy.sh/community/forums/posts/316732)
```suggestion
5. [Réactions d'utilisateurs au changement du sous-forum Off-Topic](https://osu.ppy.sh/community/forums/posts/316732)
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +7. [Archive du 17 août 2017 des règles officiels d'osu!](http://web.archive.org/web/20170817161329/http://osu.ppy.sh/help/wiki/Rules)
```suggestion
7. [Archive du 17 août 2017 des règles officielles d'osu!](http://web.archive.org/web/20170817161329/http://osu.ppy.sh/help/wiki/Rules)
```

2022-03-03 12:10 UTC, Ganondorf-1 commented on wiki/Community/Forum/Off-Topic/fr.md
> +[**Off-Topic**](https://osu.ppy.sh/community/forums/52) (abrégé par ***OT***) est un forum qui a pour but de à permettre à la communauté d'avoir des conversations sans sujet particulier. Les fils de
```suggestion
[**Off-Topic**](https://osu.ppy.sh/community/forums/52) (abrégé par ***OT***) est un forum qui a pour but de permettre à la communauté d'avoir des conversations sans sujet particulier. Les fils de discussion peuvent souvent être aléatoires, changer de sujet, et/ou avoir plusieurs sujets simultanément. Les sujets peuvent aller de la vie quotidienne aux opinions sur le jeu, en passant par le jeu de rôle, les blagues et le méta-contenu, les bêtises, ou tout ce qui se trouve entre les deux.
```

2022-03-03 19:22 UTC, Corne2Plum3 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Le terme a été utilisé pour la première fois par [Ephemeral](https://osu.ppy.sh/users/102335) dans le fil [ITT: We're Dirty](https://osu.ppy.sh/community/forums/topics/40298), et plusieurs fois par l
Je ne suis pas sûr à propos de cette suggestion parce que dans la version originale le mot '_people_' est utilisé et non '_users'_.

2022-03-03 20:02 UTC, Corne2Plum3 commented on wiki/Community/Forum/Off-Topic/fr.md
> +Le terme a été utilisé pour la première fois par [Ephemeral](https://osu.ppy.sh/users/102335) dans le fil [ITT: We're Dirty](https://osu.ppy.sh/community/forums/topics/40298), et plusieurs fois par l
Bon en fait tu suggère d'utiliser le mot "utilisateurs" au lieu de "personnes" dans beaucoup de suggestions. Par souci de cohérence, je vais quand même appliquer cette suggestion.

2022-03-03 21:54 UTC, Walavouchey approved these changes

2022-03-03 21:55 UTC, merged