[EN/RU] Update `COT22` to Finals
ppy/osu-wiki pull request #6943
Opened 2022-02-28 09:55 UTC by Kimitakari

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-02-28 10:08 UTC, Walavouchey requested changes

2022-02-28 10:08 UTC, Walavouchey commented on wiki/Tournaments/COT/2022/en.md
> +  1. [*namirin - Koishiteiku Planet (Absolute Zero) \[Team Russia's Overdose\]](https://osu.ppy.sh/beatmapsets/1045892#fruits/2186433)
```suggestion
  1. [\*namirin - Koishiteiku Planet (Absolute Zero) \[Team Russia's Overdose\]](https://osu.ppy.sh/beatmapsets/1045892#fruits/2186433)
```

2022-02-28 10:08 UTC, Walavouchey commented on wiki/Tournaments/COT/2022/ru.md
> +  1. [*namirin - Koishiteiku Planet (Absolute Zero) \[Team Russia's Overdose\]](https://osu.ppy.sh/beatmapsets/1045892#fruits/2186433)
```suggestion
  1. [\*namirin - Koishiteiku Planet (Absolute Zero) \[Team Russia's Overdose\]](https://osu.ppy.sh/beatmapsets/1045892#fruits/2186433)
```

2022-02-28 10:08 UTC, Walavouchey commented
@TicClick

2022-02-28 16:10 UTC, TicClick requested changes
looks good to me otherwise

2022-02-28 16:10 UTC, TicClick commented on wiki/Tournaments/COT/2022/ru.md
> +## Mappools
вижу копипасту, заголовки здесь и далее нужно перевести на русский

2022-03-01 00:19 UTC, TicClick approved these changes

2022-03-01 05:56 UTC, Walavouchey approved these changes

2022-03-01 05:56 UTC, merged