February and march (2022) staff log and 'the team' update
ppy/osu-wiki pull request #6977
Opened 2022-03-10 02:01 UTC by Blooshing

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-03-10 05:52 UTC, Walavouchey commented
force-pushed to clean out merge commits and renamed the first two commits

2022-03-10 08:37 UTC, Hiviexd requested changes

2022-03-10 08:37 UTC, Hiviexd commented on wiki/People/The_Team/Project_Loved_Team/en.md
> -- ![][flag_LT] [huu](https://osu.ppy.sh/users/6044237)
you forgot to add huu to Retired members section in Project Loved Team page, specifically under Coordinators

2022-03-15 20:12 UTC, Walavouchey approved these changes

2022-03-15 20:14 UTC, merged