[ZH] Add `Beatmap_ranking_procedure`
ppy/osu-wiki pull request #6979
Opened 2022-03-10 07:51 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-10 08:51 UTC, Walavouchey commented on wiki/Beatmap_ranking_procedure/zh.md
> +
missed a paragraph?

> Members of the BN and NAT occasionally [veto](https://github.com/ppy/osu-wiki/blob/master/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto) beatmaps they believe have quality issues that are unrelated to the Ranking Criteria.

2022-03-10 08:53 UTC, YumeMuzi commented on wiki/Beatmap_ranking_procedure/zh.md
> +
oops

2022-03-11 00:11 UTC, kj415j45 commented on wiki/Beatmap_ranking_procedure/zh.md
> +若经验不足的新谱师想要让自己的谱面质量达到上架标准，则通常需要大量的摸，有时候甚至需要推倒重来 (Remap)。
```suggestion
经验不足的新谱师想要让自己的谱面质量达到上架标准，往往需要大量的修改，有时候甚至需要推倒重来 (Remap)。
```

2022-03-11 00:11 UTC, kj415j45 commented on wiki/Beatmap_ranking_procedure/zh.md
> +[审核评估团队 (NAT)](/wiki/People/The_Team/Nomination_Assessment_Team) 成员也能提名谱面。但这不是他们的主要职责。
BN 和 NAT 的译法与之前的译法不一致（？）

2022-03-16 05:33 UTC, YumeMuzi commented on wiki/Beatmap_ranking_procedure/zh.md
> +[审核评估团队 (NAT)](/wiki/People/The_Team/Nomination_Assessment_Team) 成员也能提名谱面。但这不是他们的主要职责。
NAT 是对的 BN 漏了一个“成”字 加上了

2022-03-17 01:06 UTC, kj415j45 submitted a review, later dismissed

2022-03-17 06:08 UTC, Walavouchey requested changes

2022-03-17 06:08 UTC, Walavouchey commented on wiki/Beatmap_ranking_procedure/zh.md
> +
wrong line

```suggestion
```

2022-03-17 06:08 UTC, Walavouchey commented on wiki/Beatmap_ranking_procedure/zh.md
> +
```suggestion

当 BN 或者 NAT 成员认为谱面含有某些与上架标准 (Ranking Criteria) 无关的质量问题时，偶尔也会[否决 (veto)](/wiki/People/The_Team/Beatmap_Nominators/Beatmap_Veto) 谱面。

```

2022-03-17 11:48 UTC, Walavouchey approved these changes

2022-03-17 11:50 UTC, merged