[DE] Update `Hit_object`
ppy/osu-wiki pull request #6990
Opened 2022-03-12 09:51 UTC by respektive

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-12 14:56 UTC, The-Last-Cookie requested changes

2022-03-12 14:56 UTC, The-Last-Cookie commented on wiki/Hit_object/de.md
> +  - Hit Objekte
```suggestion
  - Hit-Objekte
```

2022-03-12 15:06 UTC, The-Last-Cookie approved these changes

2022-03-13 07:55 UTC, Walavouchey approved these changes

2022-03-13 07:56 UTC, merged