[ID] Update `Ranking Criteria/osu!mania`
ppy/osu-wiki pull request #6994
Opened 2022-03-12 14:54 UTC by mousesalt

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Updated from:
https://github.com/ppy/osu-wiki/pull/6924

2022-03-12 19:50 UTC, ZeroPyrozen requested changes

2022-03-12 19:50 UTC, ZeroPyrozen commented on wiki/Ranking_Criteria/osu!mania/id.md
> +- **Long note (LN) harus ditahan untuk setidaknya 1/12 dari sebuah beat.** Pelepasan timing lebih cepat menjadikan permainan dengan akurasi penuh tidak masuk akal.
```suggestion
- **Long note (LN) harus ditahan sekurang-kurangnya 1/12 dari sebuah ketukan.** Timing untuk melepas LN yang lebih cepat dari 1/12 ketukan membuat permainan tidak dapat dimainkan dengan akurasi penuh.
```

2022-03-13 18:26 UTC, ZeroPyrozen approved these changes

2022-03-13 23:46 UTC, TicClick approved these changes

2022-03-13 23:46 UTC, merged