[PT-BR] Translate osu!-wiki Main_Page
ppy/osu-wiki pull request #7010
Opened 2022-03-13 22:49 UTC by GranularBow8193

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-19 15:13 UTC, GranularBow8193 commented
@LeoFLT Pode verificar a tradução quando possível?

2022-03-24 00:12 UTC, LeoFLT requested changes
Looks good to me otherwise

2022-03-24 00:12 UTC, LeoFLT commented on wiki/Main_Page/pt-br.md
> +<div class="wiki-main-page__blurb">
```suggestion
<div class="wiki-main-page__blurb">
```

2022-03-24 00:12 UTC, LeoFLT commented on wiki/Main_Page/pt-br.md
> +Bem-vindo ao osu! wiki, uma base de conhecimento de código abeto que contém uma ampla gama de informação relacionada a osu!, um jogo de ritmo gratuito.
```suggestion
Bem-vindo ao osu! wiki, uma base de conhecimento de código abeto que contém uma ampla gama de informação relacionada a osu!, um jogo de ritmo gratuito.
```

2022-03-24 18:08 UTC, GranularBow8193 commented
> Looks good to me otherwise

Done, tell me if something is wrong.

2022-03-27 15:28 UTC, LeoFLT approved these changes

2022-03-27 15:31 UTC, TicClick approved these changes

2022-03-27 15:32 UTC, merged