[DE] Update `Help_centre/Account_restrictions`
ppy/osu-wiki pull request #7027
Opened 2022-03-16 12:06 UTC by respektive

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-16 15:13 UTC, The-Last-Cookie requested changes

2022-03-16 15:13 UTC, The-Last-Cookie commented on wiki/Help_centre/Account_restrictions/de.md
> +| Nachfolgende Verstöße | 6 Monate | Beschwerdebedingungen treffen zu, entsprechende Rücksetzung, Sperrung von Turnieren für ein Jahr pro Verstoß |
```suggestion
| Nachfolgende Verstöße (Cheaten) | 12 bis 24 Monate | Beschwerdebedingungen treffen zu, Rücksetzung, Sperrung von Turnieren für ein Jahr pro Verstoß |
```

2022-03-16 15:13 UTC, The-Last-Cookie commented on wiki/Help_centre/Account_restrictions/de.md
> +| Cheaten/Teilen für einen Turnier | 6 Monate | Beschwerdebedingungen treffen zu, entsprechende Rücksetzung, dauerhafte Sperrung von Turnieren |
```suggestion
| Cheaten/Teilen für einen Turnier | 12 Monate | Beschwerdebedingungen treffen zu, entsprechende Rücksetzung, dauerhafte Sperrung von Turnieren |
```

2022-03-16 15:30 UTC, respektive commented on wiki/Help_centre/Account_restrictions/de.md
> +Wenn dein Account aufgrund von [Regelbruch](/wiki/Rules) eingeschränkt wurde, musst du mindestens **drei Monate** warten, bis du wieder eine Beschwerde einlegen darfst. Diese Zeitspanne wird von uns
I will change it to `Auszeit`, should have looked what's being used in the article before lol

2022-03-17 05:44 UTC, Walavouchey approved these changes

2022-03-17 05:45 UTC, merged