[FR] add `history_of_osu/osu!wiki`
ppy/osu-wiki pull request #7060
Opened 2022-03-21 12:56 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-21 12:59 UTC, Biokax reviewed
attempt to fix CI failure

2022-03-21 12:59 UTC, Biokax commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 06-2017 | TPGPL est promu avec des accès en écriture sur le repository osu-wiki. La fonction de recherche pour le wiki osu! est implémentée.
```suggestion
| 06-2017 | TPGPL est promu avec des accès en écriture sur le repository osu-wiki. La fonction de recherche pour le wiki osu! est implémentée. |
```

2022-03-22 10:42 UTC, Ganondorf-1 requested changes

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +# L'histoire du osu! wiki
```suggestion
# L'histoire de l'osu! wiki
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +![](img/ow_MW.jpg "Screenshot de la page complète du osu! wiki en MediaWiki, prit le 17-02-2017")
```suggestion
![](img/ow_MW.jpg "Capture d'écran de la page complète de l'osu! wiki en MediaWiki, prise le 17 février 2017")
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| Date, Temps | Description |
```suggestion
| Date, Heure | Description |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 27/01/2013 T06:12Z | peppy a intégré le wiki osu! dans le design du site principal. [Lien vers le post de peppy](https://osu.ppy.sh/community/forums/topics/68479/start=124). |
```suggestion
| 27/01/2013 T06:12Z | peppy a intégré l'osu! wiki dans le design du site principal. [Lien vers le post de peppy](https://osu.ppy.sh/community/forums/topics/68479/start=124). |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 2014 | Le wiki osu! est devenu la source d'information principale d'osu!, remplaçant la plupart des copies web, tel que [L'équipe](/wiki/People/The_Team) ainsi que les [Règles](/wiki/Rules). Égalem
```suggestion
| 2014 | L'osu! wiki est devenu la source d'information principale d'osu!, remplaçant la plupart des copies web, telles que [L'équipe](/wiki/People/The_Team) ainsi que les [Règles](/wiki/Rules). Par ailleurs, l'osu! wiki possède maintenant 5 administrateurs (Loctav, deadbeat). |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 2015 | L'osu! wiki a reçus une traduction majeur des autres langues. Dellirium a été remplacé par Shiro en tant qu'un des administrateurs du osu! wiki. |
```suggestion
| 2015 | L'osu! wiki a reçu une traduction majeure des autres langues. Dellirium a été remplacé par Shiro en tant qu'un des administrateurs du osu! wiki. |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 22/02/2016 | Le wiki osu! a maintenant 8 administrateurs (Ukami and Galkan). |
```suggestion
| 22/02/2016 | L'osu! wiki a maintenant 8 administrateurs (Ukami et Galkan). |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 01/04/2016 | Le wiki osu! a maintenant 9 administrateurs (Nathanael). |
```suggestion
| 01/04/2016 | L'osu! wiki a maintenant 9 administrateurs (Nathanael). |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 30/08/2016 | Le wiki osu! fonctionnant sur MediaWiki a été déprécié en faveur de la version fonctionnant sur le repository Github. Le wiki actuel d'osu! va rester jusqu'à ce que la version Github s
```suggestion
| 30/08/2016 | L'osu! wiki fonctionnant sur MediaWiki a été déprécié en faveur de la version fonctionnant sur le repository GitHub. Le wiki actuel d'osu! va rester jusqu'à ce que la version GitHub soit prête à être déployée avec toutes les pages, ainsi que les images portées. |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 06/2017 | Le wiki osu! fonctionnant sur MediaWiki est officiellement déprécié. Le lien pointe maintenant vers la nouvelle interface osu-web utilisant les ressources du wiki osu! faites à partir du
```suggestion
| 06/2017 | L'osu! wiki fonctionnant sur MediaWiki est officiellement déprécié. Le lien pointe maintenant vers la nouvelle interface osu-web utilisant les ressources de l'osu! wiki faites à partir du repository GitHub. [Une backup temporaire de l'osu! wiki sans les fonctionnalités de MediaWiki peut-être trouvée ici.](https://osu.ppy.sh/old-wiki/Main_Page) |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +## repository GitHub (2016 - maintenant)
```suggestion
## Repository GitHub (2016 - maintenant)
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 09/2016 | La plupart des pages, excepté les images ont été déplacés dans le repository, avec des erreurs de syntaxe et de traduction non résolues découlant des différences linguistiques entre Markd
```suggestion
| 09/2016 | La plupart des pages, excepté les images, ont été déplacées dans le repository, avec des erreurs de syntaxe et de traduction non résolues découlant des différences linguistiques entre Markdown et MediaWiki. |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 01/2017 | osu!web supporte le wiki osu!, fait par nanaya. |
```suggestion
| 01/2017 | Grâce à nanaya, osu!web prend en charge l'osu! wiki. |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 26/01/2017 | Le wiki osu! a été mentionné dans le blog de ppy. |
```suggestion
| 26/01/2017 | L'osu! wiki a été mentionné dans le blog de ppy. |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 22/05/2017 | [Les archives osu!news sont maintenant stockées sur le wiki osu! (sous format texte uniquement)](https://github.com/ppy/osu-wiki/pull/252). |
```suggestion
| 22/05/2017 | [Les archives osu!news sont maintenant stockées sur l'osu! wiki (sous format texte uniquement)](https://github.com/ppy/osu-wiki/pull/252). |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 30/05/2017 | [La redirection de page est finalement implémentée dans le wiki osu!](https://github.com/ppy/osu-web/pull/1144) |
```suggestion
| 30/05/2017 | [La redirection de page est finalement implémentée dans l'osu! wiki](https://github.com/ppy/osu-web/pull/1144) |
```

2022-03-22 10:42 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 06/2017 | TPGPL est promu avec des accès en écriture sur le repository osu-wiki. La fonction de recherche pour le wiki osu! est implémentée. |
```suggestion
| 06/2017 | TPGPL est promu avec des accès en écriture sur le repository osu-wiki. La fonction de recherche pour l'osu! wiki est implémentée. |
```

2022-03-23 17:13 UTC, Ganondorf-1 requested changes

2022-03-23 17:13 UTC, Ganondorf-1 commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 2015 | L'osu! wiki a reçu une traduction majeure des autres langues. Dellirium a été remplacé par Shiro en tant qu'un des administrateurs du osu! wiki. |
```suggestion
| 2015 | L'osu! wiki a reçu une traduction majeure des autres langues. Dellirium a été remplacé par Shiro en tant qu'un des administrateurs de l'osu! wiki. |
```

2022-03-23 20:17 UTC, Ganondorf-1 submitted a review, later dismissed

2022-03-23 20:19 UTC, Walavouchey commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 30/05/2017 | [La redirection de page est finalement implémentée dans l'osu! wiki](https://github.com/ppy/osu-web/pull/1144) |
```suggestion
| 30/05/2017 | [La redirection de page est finalement implémentée dans l'osu! wiki.](https://github.com/ppy/osu-web/pull/1144) |
```

2022-03-23 20:20 UTC, Walavouchey commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 06/12/2011 | [osu! wiki est maintenant en ligne !](https://osu.ppy.sh/community/forums/topics/68525). |
```suggestion
| 06/12/2011 | [osu! wiki est maintenant en ligne !](https://osu.ppy.sh/community/forums/topics/68525) |
```

2022-03-23 20:27 UTC, Walavouchey approved these changes

2022-03-23 20:34 UTC, merged