[RU] Update `Project Loved Team`
ppy/osu-wiki pull request #7061
Opened 2022-03-21 13:51 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-26 21:49 UTC, UristMcKobold requested changes

2022-03-26 21:49 UTC, UristMcKobold commented on wiki/People/The_Team/Project_Loved_Team/ru.md
> +Команда Project Loved в основном состоит из *капитанов* для каждого [режима игры](/wiki/Game_mode). Капитаны отвечают за попадание карт в категорию Loved — считается, что у них достаточно хороший вку
```suggestion
Команда Project Loved в основном состоит из *капитанов* для каждого [режима игры](/wiki/Game_mode). Капитаны отвечают за попадание карт в категорию Loved — считается, что они обладают обширным опытом и знакомы с желаниями сообщества, чтобы выбирать достойные карты для номинации в эту категорию. Кроме того, они пишут короткие описания к картам, чтобы игроки могли с ними бегло ознакомиться при прочтении новостей.
```
«good sense» тут скорее подразумевает опыт и умение разбираться в картах, а не просто вкус. Плюс, они не оценивают номинированные карты, а сами их номинируют. А ещё пропустил момент, что они ПРЕДСТАВЛЯЮТ (act as representatives for the community) коммьюнити, когда выбирают карты.

2022-03-27 13:50 UTC, TicClick commented on wiki/People/The_Team/Project_Loved_Team/ru.md
> +Команда Project Loved в основном состоит из *капитанов* для каждого [режима игры](/wiki/Game_mode). Капитаны отвечают за попадание карт в категорию Loved — считается, что у них достаточно хороший вку
да, так лучше (но я замечу, что «опыт и умение разбираться» в итоге сводятся к нечётким критериям, которые люди и называют вкусом)

2022-03-28 22:54 UTC, Walavouchey approved these changes

2022-03-28 22:55 UTC, merged