Make audio requirements more lenient in the Ranking Criteria
ppy/osu-wiki pull request #7062
Opened 2022-03-21 15:12 UTC by Naxesss

This addresses a latent issue introduced when dropping the 128 kbps minimum, which we did that to prevent the need to up-encode for songs with no available source >= 128 kbps. To discourage people from using too low quality as a result of that change, we added "try to find the highest quality audio".

Since then, we have seen groups forcing mappers to change from 128 kbps to 192 kbps audio files quoting that rule, effectively raising the bar to 192 kbps, which is not supposed to be necessary. The benefit of this is sometimes negligible, and sometimes even detrimental when the suggested audio is badly encoded.

To fix this, we simply made 128 kbps a threshold after which further improvement is up to the mapper, as long the current audio sounds ok. We also cleaned up the structure of the rules a bit, making them easier to read than before.

- [ ] waiting for https://github.com/ppy/osu-wiki/pull/6873, as it will likely handle outdating sooner than this PR

2022-03-21 17:42 UTC, Walavouchey requested changes

2022-03-21 17:42 UTC, Walavouchey commented on wiki/Ranking_Criteria/en.md
> +  - **...use the .mp3 or .ogg file format.**
```suggestion
  - **...use the `.mp3` or `.ogg` file format.**
```

2022-03-22 04:42 UTC, peppy approved these changes

2022-03-22 04:49 UTC, Walavouchey approved these changes

2022-03-22 05:12 UTC, peppy approved these changes

2022-03-22 05:12 UTC, merged