[FR] Add `Wiki/Tournament_drawings`
ppy/osu-wiki pull request #7075
Opened 2022-03-23 17:02 UTC by Biokax

## Self-check

the last translation of english outdated article

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-23 17:03 UTC, Biokax commented
Since its based on an outdated article, does the screenshot needs to be translated too ?

2022-03-23 17:09 UTC, Walavouchey commented
the lazer tournament client doesn't have localisation if i'm not mistaken, but other than that i suppose there's no need to bother

2022-03-23 17:10 UTC, Biokax commented
> the lazer tournament client doesn't have localisation if i'm not mistaken, but other than that i suppose there's no need to bother

Lazer client have localisation based on crowdin if im not wrong, I will check it later

2022-03-23 17:14 UTC, Walavouchey commented
i said the "lazer tournament client". i checked in crowdin and there are no strings for the tournament client for what i can see

2022-03-24 22:45 UTC, Ganondorf-1 requested changes

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Les tournament drawings, sont maintenant prêt à être prévisualisés. Il est important de comprendre comment l'écran pour les tournament drawings fonctionne et agit avant de modifier d'avantage chacun
```suggestion
Les tournament drawings sont maintenant prêt à être prévisualisés. Il est important de comprendre comment l'écran des tournament drawings fonctionne et agit avant de modifier davantage chacun des fichiers.  
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +À partir du menu principal, appuyer sur `Ctrl + Shift + D` afin d'accéder à l'écran de dessins de tournois. L'écran suivant devrait apparaître :
```suggestion
À partir du menu principal, appuyez sur `Ctrl + Shift + D` afin d'accéder à l'écran des tournament drawings. L'écran suivant devrait apparaître :
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +![](img/main-screen.png "Le menu de dessins de tournois")
```suggestion
![](img/main-screen.png "Menu principal des tournament drawings")
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +  - Ceci va arrêter le procédé aléatoire, faisant ralentir le défilement des drapeaux, jusqu'à ce que qu'il s'arrête éventuellement sur le drapeau au centre de l'écran
```suggestion
  - Ceci va arrêter le procédé aléatoire, faisant ralentir le défilement des drapeaux, jusqu'à ce que qu'il s'arrête sur un drapeau au centre de l'écran.
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +  - Ce bouton doit rarement être utilisé. Il est destructif, et va réinitialiser les résultats du procédé de dessins.
```suggestion
  - Ce bouton doit rarement être utilisé. Il est destructif, et va réinitialiser les résultats du procédé.
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +L'écran des tournament drawings est utilisé pour diffuser en direct le tri des équipes en groupes qui s'affronteront lors des phases de groupes d'un tournoi. Il est uniquement disponible dans le clie
```suggestion
L'écran des tournament drawings est utilisé pour diffuser en direct le tirage des équipes en groupes qui s'affronteront lors des phases de groupes d'un tournoi. Il est uniquement disponible dans le client [osu! (lazer)](https://github.com/ppy/osu/releases).
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Ouvrez le fichier et observez le format - c'est là que sont stockés les résultats du processus de dessin, et ils doivent être importés dans d'autres outils d'aide à la gestion de tournois, tels que G
```suggestion
Ouvrez le fichier et observez le format - c'est là que sont stockés les résultats du processus de tirage, et ils doivent être importés dans d'autres outils d'aide à la gestion de tournois, tels que Google Spreadsheets.\
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Les propriétés suivantes sont des propriétés configurables au travers de ce fichier :
```suggestion
Les propriétés suivantes sont des propriétés configurables en utilisant ce fichier :
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +| Groups | Le nombre de groupe dans lequel on va trier les équipes. | Entre 1 et 8 (inclusif) | 8 |
```suggestion
| Groups | Le nombre de groupes dans lesquels les équipes seront triées. | Entre 1 et 8 (inclus) | 8 |
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +| TeamsPerGroup | Le nombre maximum d'équipes au sein d'un même groupe. | Entre 1 et 8 (inclusif) | 8 |
```suggestion
| TeamsPerGroup | Le nombre maximum d'équipes au sein d'un même groupe. | Entre 1 et 8 (inclus) | 8 |
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Le fichier `drawings.txt` fourni une méthode de spécification des équipes qui vont être triées en groupes sur des lignes séparées. Voici une ligne d'exemple :
```suggestion
Le fichier `drawings.txt` fournit une méthode de spécification des équipes qui vont être triées en groupes sur des lignes séparées. Voici une ligne d'exemple :
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Cette ligne possède trois sections séparées par une colonne (`:`) :
```suggestion
Cette ligne possède trois sections séparées par un double point (`:`) :
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +- Le nom du drapeau fait référence au nom du fichier qui fourni l'image du drapeau. Par défaut, osu! (lazer) fourni les drapeaux de pays en [Code Pays ISO 3166 Alpha-2](https://www.iso.org/iso-3166-c
```suggestion
- Le nom du drapeau fait référence au nom du fichier qui fournit l'image du drapeau. Par défaut, osu! (lazer) fournit les drapeaux de pays en [Code Pays ISO 3166 Alpha-2](https://www.iso.org/iso-3166-country-codes.html).
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +- L'acronyme de l'équipe est affiché dans les case de groupe.
```suggestion
- L'acronyme de l'équipe est affiché dans les cases de groupe.
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Il peut-être désirable de "seed" des équipes. Dans ce cas, de multiples fichiers `drawings.txt` peuvent-être "hotswapped" (remplacé à chaud) à l'aid du bouton de Rechargement depuis le panneau de con
```suggestion
Il peut être désirable de "seed" des équipes. Dans ce cas, de multiples fichiers `drawings.txt` peuvent être intervertis à l'aide du bouton Reload depuis le panneau de contrôle.
```

2022-03-24 22:45 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Pour définir un drapeau personnalisé, retournez dans le dossier osu! contenant le fichier `drawings.ini`, à l'intérieur vous trouverez le dossier `Flags`. Les images de drapeaux personnalisées peuven
```suggestion
Pour définir un drapeau personnalisé, retournez dans le dossier osu! contenant le fichier `drawings.ini`, à l'intérieur vous trouverez le dossier `Flags`. Les images de drapeaux personnalisées peuvent-être placées à l'intérieur du dossier Flags. Par exemple, si le fichier `my-flag-file.png` a été placé à l'intérieur de ce dossier, alors une ligne valide pouvant être ajoutée au fichier `drawings.txt` se présente sous la forme de :
```

2022-03-25 11:15 UTC, Ganondorf-1 requested changes

2022-03-25 11:15 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Cet écran est composé de deux sections - la partie principale se situant sur la gauche, avec la carte du monde en tant que fond d'écran, et la panneau de sélection des contrôles sur la droite. **Évit
```suggestion
Cet écran est composé de deux sections - la partie principale se situant sur la gauche, avec la carte du monde en tant que fond d'écran, et le panneau de sélection des contrôles sur la droite. **Évitez** de diffuser en direct ce panneau de contrôle.
```

2022-03-25 11:15 UTC, Ganondorf-1 commented on wiki/Tournament_drawings/fr.md
> +Pour définir un drapeau personnalisé, retournez dans le dossier osu! contenant le fichier `drawings.ini`, à l'intérieur vous trouverez le dossier `Flags`. Les images de drapeaux personnalisées peuven
```suggestion
Pour définir un drapeau personnalisé, retournez dans le dossier osu! contenant le fichier `drawings.ini`, vous y trouverez le dossier `Flags`. Les images de drapeaux personnalisées peuvent-être placées à l'intérieur du dossier Flags. Par exemple, si le fichier `my-flag-file.png` a été placé à l'intérieur de ce dossier, alors une ligne valide pouvant être ajoutée au fichier `drawings.txt` se présente sous la forme de :
```

2022-03-25 11:36 UTC, Biokax commented on wiki/Tournament_drawings/fr.md
> +La résolution pour une image de drapeau optimale est de 70x47 pixels (ou le même rapport d'aspect)
```suggestion
La résolution pour une image de drapeau optimale est de 70x47 pixels (ou le même rapport d'aspect).
```

2022-03-25 12:48 UTC, Ganondorf-1 approved these changes

2022-03-26 11:56 UTC, Biokax commented on wiki/Tournament_drawings/fr.md
> +## Questions?
```suggestion
## Questions ?
```

2022-03-26 21:13 UTC, Walavouchey approved these changes

2022-03-26 21:14 UTC, merged