[DE] Update `Tournaments`
ppy/osu-wiki pull request #7076
Opened 2022-03-23 19:31 UTC by respektive

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-24 21:42 UTC, The-Last-Cookie requested changes

2022-03-24 21:42 UTC, The-Last-Cookie commented on wiki/Tournaments/de.md
> +Dieser Bereich ist für osu! Turniere bestimmt. Turniere haben ihr eigenes Forum, das man [über diesen Link](https://osu.ppy.sh/community/forums/55) finden kann.
```suggestion
Dieser Bereich ist für osu!-Turniere bestimmt. Turniere haben ihr eigenes Forum, das man [über diesen Link](https://osu.ppy.sh/community/forums/55) finden kann.
```

2022-03-24 21:42 UTC, The-Last-Cookie commented on wiki/Tournaments/de.md
> +Offizielle Turniere, die vom osu! Team organisiert werden.
```suggestion
Offizielle Turniere, die vom osu!-Team organisiert werden.
```

2022-03-24 21:42 UTC, The-Last-Cookie commented on wiki/Tournaments/de.md
> +Der osu! World Cup ist ein länderbasiertes 4v4-Team-VS-Turnier mit Doppelausscheidungsregel. Es handelt sich um ein internationales Event, das in der Regel jährlich stattfindet, wobei die osu! Commun
```suggestion
Der osu! World Cup ist ein länderbasiertes 4v4-Team-VS-Turnier mit Doppelausscheidungsregel. Es handelt sich um ein internationales Event, das in der Regel jährlich stattfindet, wobei die osu!-Communities auf der ganzen Welt zusammenarbeiten, um ein Turnier mit kompetitivem Charakter zu veranstalten.
```

2022-03-24 21:42 UTC, The-Last-Cookie commented on wiki/Tournaments/de.md
> +Nicht offizielle Turniere/ Wettkämpfe, die von den Communities veranstaltet werden.
```suggestion
Nicht offizielle Turniere/Wettkämpfe, die von den Communities veranstaltet werden.
```

2022-03-24 22:52 UTC, The-Last-Cookie approved these changes

2022-03-28 23:17 UTC, Walavouchey commented on wiki/Tournaments/de.md
> +| CES League osu! Tournament 2](CES/CES2) | 2020-05-01 | 2020-08-16 | Woopak | MissClick324 | Thymue |
```suggestion
| [CES League osu! Tournament 2](CES/CES2) | 2020-05-01 | 2020-08-16 | Woopak | MissClick324 | Thymue |
```

2022-03-28 23:17 UTC, Walavouchey commented on wiki/Tournaments/de.md
> +| [Mania Beginner's Showdown](MBS/1) | 2019-06-15 | 2019-08-04 | ![][flag_SE] [Davvyforte](https://osu.ppy.sh/users/10047413) ( Oberliga), ![][flag_TH] [osu\_player420](https://osu.ppy.sh/users/13018
```suggestion
| [Mania Beginner's Showdown](MBS/1) | 2019-06-15 | 2019-08-04 | ![][flag_SE] [Davvyforte](https://osu.ppy.sh/users/10047413) (Oberliga), ![][flag_TH] [osu\_player420](https://osu.ppy.sh/users/13018880) (Unterliga) | ![][flag_DE] [Maou](https://osu.ppy.sh/users/3867109) (Oberliga), ![][flag_PH] [Wakeupat5](https://osu.ppy.sh/users/13311553) (Unterliga) | ![][flag_US] [Loopy542](https://osu.ppy.sh/users/5468461) (Oberliga), ![][flag_VE] [\_Vanslight\_](https://osu.ppy.sh/users/6031119) (Unterliga) |
```

2022-03-28 23:17 UTC, Walavouchey commented on wiki/Tournaments/de.md
> +| [Mania Beginner's Showdown 2](MBS/2) | 2020-05-09 | 2020-06-05 | ![][flag_PH] [Lazereed](https://osu.ppy.sh/users/12894120) ( Oberliga), ![][flag_MY] [Anamneses](https://osu.ppy.sh/users/16299729)
```suggestion
| [Mania Beginner's Showdown 2](MBS/2) | 2020-05-09 | 2020-06-05 | ![][flag_PH] [Lazereed](https://osu.ppy.sh/users/12894120) (Oberliga), ![][flag_MY] [Anamneses](https://osu.ppy.sh/users/16299729) (Unterliga) | ![][flag_FR] [Paturages](https://osu.ppy.sh/users/1375479) (Oberliga), ![][flag_SE] [Mestro](https://osu.ppy.sh/users/4798263) (Unterliga) | ![][flag_SG] [loli\_seale](https://osu.ppy.sh/users/5069913) (Oberliga), ![][flag_MX] [Ammy](https://osu.ppy.sh/users/4183406) (Unterliga) |
```

2022-03-28 23:24 UTC, Walavouchey approved these changes

2022-03-28 23:26 UTC, merged