[FR] Update `osu!_wiki` `Contribution_guide` `Contribution_guide/GitHub_Desktop`
ppy/osu-wiki pull request #7081
Opened 2022-03-24 13:06 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-25 11:30 UTC, Ganondorf-1 requested changes

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Contribution_guide/GitHub_Desktop/fr.md
> +3. Vous pouvez maintenant apporter vos modifications. Prenez un moment pour passer également en revue les [self-check](/wiki/osu!_wiki/Contribution_guide#self-check) aussi fidèlement que possible.
```suggestion
3. Vous pouvez maintenant apporter vos modifications. Prenez un moment pour passer également en revue le [self-check](/wiki/osu!_wiki/Contribution_guide#self-check) aussi fidèlement que possible.
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Contribution_guide/fr.md
>  # Guide de contribution au osu! wiki
```suggestion
# Guide de contribution de l'osu! wiki
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Contribution_guide/fr.md
>  Merci de votre intérêt à vouloir rendre le osu! wiki meilleur ! Cet article couvre le processus de contribution étape par étape. Si vous êtes familier avec GitHub, n'hésitez pas à suivre le feature-b
```suggestion
Merci de votre intérêt à vouloir rendre l'osu! wiki meilleur ! Cet article couvre le processus de contribution étape par étape. Si vous êtes familier avec GitHub, n'hésitez pas à suivre le feature-branch workflow pour proposer des changements et passez directement à la section concernant le [self-check](#self-check).
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Contribution_guide/fr.md
>  - **Le ton de la prestation** : les articles du osu! wiki, à de rares exceptions près, doivent être rédigés dans un registre neutre.
```suggestion
- **Le ton de la prestation** : les articles de l'osu! wiki, à de rares exceptions près, doivent être rédigés dans un registre neutre.
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Contribution_guide/fr.md
>  - **Toutes les images et autres fichiers non textuels** doivent être [inférieurs à 1 mégaoctet](/wiki/Article_styling_criteria/Formatting#taille-du-fichier). **Les captures d'écran** doivent utiliser
```suggestion
- **Toutes les images et autres fichiers non textuels** doivent être [inférieurs à 1 mégaoctet](/wiki/Article_styling_criteria/Formatting#taille-du-fichier). **Les captures d'écran** doivent utiliser le skin d'osu! par défaut et des [paramètres spécifiques](/wiki/Article_styling_criteria/Formatting#captures-d'écran-de-gameplay), y compris les dimensions maximales de 1280×720.
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
>  Le **osu! wiki** est une base de données de connaissances open-source écrite et maintenue par des [contributeurs volontaires](https://github.com/ppy/osu-wiki/graphs/contributors). Il contient un larg
```suggestion
L'**osu! wiki** est une base de données de connaissances open-source écrite et maintenue par des [contributeurs volontaires](https://github.com/ppy/osu-wiki/graphs/contributors). Il contient un large éventail d'informations sur des sujets liés à osu!, à sa communauté et à des activités et concepts connexes. Le wiki sert de source officielle d'information et est considéré comme une documentation de l'histoire d'osu!.
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
> +- L'amélioration des articles existants ainsi que la création de nouveaux sont encouragés, mais une connaissance de base de [GitHub](https://github.com) nécessaire afin de contribuer, ce qui augmente
```suggestion
- L'amélioration des articles existants ainsi que la création de nouveaux sont encouragés, mais une connaissance de base de [GitHub](https://github.com) est nécessaire afin de contribuer, ce qui augmente le seuil nécessaire pour entrer. L'osu! wiki fournit toutefois un [guide de contribution](/wiki/osu!_wiki/Contribution_guide) afin d'aider les nouveaux contributeurs à commencer.
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
> +- Tous les changements apportés au osu! wiki sont pré-modérés et font l'objet d'un processus d'examen, au cours duquel le contributeur doit collaborer avec les reviewers et répondre aux commentaires.
```suggestion
- Tous les changements apportés à l'osu! wiki sont pré-modérés et font l'objet d'un processus d'examen, au cours duquel le contributeur doit collaborer avec les reviewers et répondre aux commentaires.
```

2022-03-25 11:30 UTC, Ganondorf-1 commented on wiki/osu!_wiki/fr.md
>  Bien que son nom contienne le suffixe *wiki*, le osu! wiki ne répond pas entièrement au [concept de wiki](https://fr.wikipedia.org/wiki/Wiki) :
```suggestion
Bien que son nom contienne le suffixe *wiki*, l'osu! wiki ne répond pas entièrement au [concept de wiki](https://fr.wikipedia.org/wiki/Wiki) :
```

2022-03-27 19:22 UTC, Ganondorf-1 approved these changes

2022-03-28 12:31 UTC, TicClick approved these changes

2022-03-28 12:32 UTC, merged