[ZH] Update `People\The_Team\Beatmap_Nominators`
ppy/osu-wiki pull request #7087
Opened 2022-03-25 08:30 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-04-06 06:32 UTC, RushFTK requested changes

2022-04-06 06:32 UTC, RushFTK commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +**谱面审核成员** 全称为 Beatmap Nominators (***BN***)，是负责[谱面审核流程](/wiki/Beatmap_ranking_procedure)的一群玩家。他们在论坛和[谱面讨论区](/wiki/Beatmap_discussion)标记为紫色用户名。
此外，考虑到英文原文使用"Members of the Beatmap Nominators"，称BN为谱面审核**团队**是否更合适一些呢？这个也是可选的。

2022-04-06 06:32 UTC, RushFTK commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +除了平常的摸图和上架谱面之外，正式成员还负责下架某些已发现问题的，处于过审 (Qualified) 状态的谱面。如果他们想要加入审核评估团队 (NAT)，也可以提交相应的评估申请。
```suggestion
除了平常的摸图和上架谱面之外，正式成员还负责下架某些已发现问题的，处于过审 (Qualified) 状态的谱面。如果他们有意在未来加入审核评估团队 (NAT)，也可临时承担甄选BN申请的工作。
```
**你必须修改这条。**

> Full Beatmap Nominators may also participate in occasional Beatmap Nominator application assessment if they are interested in joining the Nomination Assessment Team in the future.

原文的意思是承担一部分NAT的工作，也就是去审BN申请这一工作，如果说提交相应的评估申请，更像是填写一个加入NAT的表格，我认为这里的翻译会造成含义的偏差。

2022-04-06 06:32 UTC, RushFTK commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +见习期能够用来帮助 NAT 监督或关注新 BN 的行为。见习成员的主要职责是打好 BN 的基础，并学习将谱面推至上架周期。谱面若要上架 (Ranked)，则提名者中必须有至少一位正式成员。因此，见习成员不能提名已被其他相同游戏模式的见习成员提名过的谱面。
```suggestion
设立见习期的目的，是用来帮助 NAT 关注新的或者待定的 BN 的行为。见习成员的主要职责是在实际推送铺面上架流程中打好作为 BN 的基本功。谱面若要上架 (Ranked)，则提名者中必须有至少一位正式成员。因此，见习成员不能提名已被其他相同游戏模式的见习成员提名过的谱面。
```
> Probation is used to monitor new or concerning Beatmap Nominators more closely. The main role for probationary Beatmap Nominators is to establish a foundation as a Beatmap Nominator through exclusively promoting beatmaps in the ranking process. At least one full nominator must be involved in the ranking process for each game mode of a beatmap, so probationary members cannot give the final nomination to a beatmap which has only received nominations from other probationary members for their game mode.

1. 第一句，首先英文原文只有一个monitor，所以译文非必要时用一个词就够了。其次不是新BN才是见习的，还有那些记大过的BN，我不确定concerning 翻译成待定还是记过比较好。
2. 第二句，through，所以这两个不是并列学习的内容，而是通过手段学习一个内容。

2022-04-06 06:32 UTC, RushFTK commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +如果 BN 因为犯下错误被降级成见习成员，随后他们再次犯下了类似的错误，则会被开除。比如，某位 BN 因为不良行为而被降级成见习成员，无论他们是否因度过见习期而返回正式成员，只要再犯，就会被直接开除。
```suggestion
因犯错而被降级为见习成员的BN，同季度中二犯同种错误将会导致其被开除。比如，某位 BN 因为不良行为而被降级成见习成员，无论他们是否因度过见习期而返回正式成员，只要再犯，就会被直接开除。
```

**你必须修改这条。**

> When a Beatmap Nominator is placed on probation, they cannot be placed on probation again for the same reason. For example, if a Beatmap Nominator is placed on probation for poor behaviour, they will be removed from the Beatmap Nominators if they exhibit the same poor behaviour again, even if they are a full Beatmap Nominator during the second infringement.

你可以对比一下缺了哪些信息，自行调整语序。

2022-04-18 08:30 UTC, Walavouchey commented
@RushFTK should the changes here be applied?

2022-04-18 09:02 UTC, RushFTK commented
@Walavouchey nope, some of them must be fixed, so i will wait him response.

2022-04-18 09:07 UTC, RushFTK commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +如果 BN 因为犯下错误被降级成见习成员，随后他们再次犯下了类似的错误，则会被开除。比如，某位 BN 因为不良行为而被降级成见习成员，无论他们是否因度过见习期而返回正式成员，只要再犯，就会被直接开除。
现在看这里我好像搞错了。。。（）

2022-04-19 16:02 UTC, YumeMuzi commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +**谱面审核成员** 全称为 Beatmap Nominators (***BN***)，是负责[谱面审核流程](/wiki/Beatmap_ranking_procedure)的一群玩家。他们在论坛和[谱面讨论区](/wiki/Beatmap_discussion)标记为紫色用户名。
你这个应该是指BNG(Group)，~~当然英文原文也很容易弄混这两个概念~~，还是保留吧
keep

2022-04-19 16:03 UTC, YumeMuzi commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +如果 BN 因为犯下错误被降级成见习成员，随后他们再次犯下了类似的错误，则会被开除。比如，某位 BN 因为不良行为而被降级成见习成员，无论他们是否因度过见习期而返回正式成员，只要再犯，就会被直接开除。
wtf

2022-04-19 16:08 UTC, YumeMuzi commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +如果 BN 因为犯下错误被降级成见习成员，随后他们再次犯下了类似的错误，则会被开除。比如，某位 BN 因为不良行为而被降级成见习成员，无论他们是否因度过见习期而返回正式成员，只要再犯，就会被直接开除。
这里意思是，不管BN因为什么内在原因，只要再次犯相同类型的严重错误，不管是在PBN还是恢复正式BN，都会被下狗。
regardless of BN intentions or status (full/prob), if they make the same type of serious mistake again, they will be resigned.

2022-04-19 16:11 UTC, YumeMuzi commented
also, do I need to update the BN list of changes during this PR period?

2022-04-20 01:52 UTC, RushFTK approved these changes
fine for me in translation part.

2022-04-21 17:54 UTC, Walavouchey approved these changes

2022-04-21 17:56 UTC, merged