[DE] Add `Play_style/Hybrid`, `Play_style/Single-tapping`, `Play_style/Tapping_style` and `Play_style/Tapx`
ppy/osu-wiki pull request #7104
Opened 2022-03-28 15:05 UTC by The-Last-Cookie

- [ ] Requires #7094 
    - There is a link to a header in `Play_style`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-03-28 23:10 UTC, respektive requested changes

2022-03-28 23:10 UTC, respektive commented on wiki/Play_style/Hybrid/de.md
> +- Einige Hybridspieler benutzen eine Kombination aus Alternating und Single-Tapping, abhängig von der Geschwindigkeit der Beatmap: manche Geschwindigkeiten sind einfacher zum Single-tappen als zum Al
```suggestion
- Einige Hybridspieler benutzen eine Kombination aus Alternating und Single-Tapping, abhängig von der Geschwindigkeit der Beatmap: manche Geschwindigkeiten sind einfacher zum Single-tappen als zum Alternieren und viele Hybridspieler passen sich daran an. Die Geschwindigkeiten bei denen das auftritt, sind von Spieler zu Spieler unterschiedlich.
```

2022-03-28 23:10 UTC, respektive commented on wiki/Play_style/Single-tapping/de.md
> +  - Tastatur
```suggestion
  - Tastatur
  - tippen
```

2022-03-28 23:10 UTC, respektive commented on wiki/Play_style/Single-tapping/de.md
> +**Single-tapping** ist ein Tippstil für [osu!](/wiki/Game_mode/osu!), bei dem Spieler nur eine Taste auf ihrer Tastatur (standardmäßig `Z` oder `X`) benutzen, um Circles zu klicken, Slider zu verschi
```suggestion
**Single-tapping** ist ein Tippstil für [osu!](/wiki/Game_mode/osu!), bei dem Spieler nur eine Taste auf ihrer Tastatur (standardmäßig `Z` oder `X`) benutzen, um Circles zu klicken, Slider zu verschieben und Spinner zu spinnen. Diese Spielweise ist bei Spielern aller Fähigkeitslevel zu finden und ist die einfachste zu Lernen.
```

2022-03-28 23:10 UTC, respektive commented on wiki/Play_style/Tapping_style/de.md
> +  - Tastatur
```suggestion
  - Tastatur
  - tippen
```

2022-03-28 23:10 UTC, respektive commented on wiki/Play_style/Tapx/de.md
> +  - play style
```suggestion
  - play style
  - tippen
```

2022-03-28 23:10 UTC, respektive commented on wiki/Play_style/Tapx/de.md
> +**Tapx** ist ein Tippstil für [Nur-Tablet](/wiki/Play_style#nur-tablet)-Spieler in [osu!](/wiki/Game_mode/osu!), bei dem Spieler durch das Drücken eines Tablet-Stifts auf ein Tablet Circles klicken,
```suggestion
**Tapx** ist ein Tippstil für [Nur-Tablet](/wiki/Play_style#nur-tablet)-Spieler in [osu!](/wiki/Game_mode/osu!), bei dem Spieler durch das Drücken eines Tablet-Stifts auf ein Tablet Circles klicken, Slider verschieben und Spinner spinnen. Zusätzlich gibt es eine zweite Taste auf der Tastatur/dem Tablet, welche bei [Streams](/wiki/Beatmap/Pattern/Stream) und [Stacks](/wiki/Mapping_techniques/Stack) zur Unterstützung dient. Diese Methode ist ziemlich schwierig für die meisten Spieler und ist nicht wirklich populär unter Tablet-Spielern.
```

2022-03-28 23:10 UTC, respektive commented on wiki/Play_style/Tapx/de.md
> +Tapx hat normalerweise keine Vor- und Nachteile im Vergleich zu anderen Tippstile für Tablets, da es weniger ein vorteilhafter Tippstil und mehr eine Notwendigkeit für Nur-Tablet-Spieler ist.
```suggestion
Tapx hat normalerweise keine Vor- und Nachteile im Vergleich zu anderen Tippstilen für Tablets, da es weniger ein vorteilhafter Tippstil und mehr eine Notwendigkeit für Nur-Tablet-Spieler ist.
```

2022-03-29 22:12 UTC, respektive approved these changes

2022-03-29 23:11 UTC, Walavouchey approved these changes

2022-03-29 23:11 UTC, merged