[KO] Add Flashlight
ppy/osu-wiki pull request #7176
Opened 2022-04-13 15:30 UTC by Sightread-osu

Can be merged if there's nothing I forgot to translate c:
* Made new account because I forgot the previous account password and email (Ge-n-z)

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-04-13 16:08 UTC, The-Last-Cookie commented on wiki/Game_modifier/Flashlight/ko.md
> +태그:
```suggestion
tags:
```
These **must not** be translated. The tags in itself can be translated though. See [here](https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#tagging-articles) for more information.

2022-04-13 21:55 UTC, libneko requested changes
추가적으로 `FL`이라고 적힌 부분이 아닌 이상 `플래시라이트`로 통일해주셨으면 합니다.

그리고 `Hidden mod`의 경우엔 `히든 모드`로 번역을 했기 때문에
`Flashlight mod`의 경우는 `플래시라이트 모드`로 번역을 해서 통일을 해야할 것 같네요.

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +- 설명: `마우스 주변의 제한된 부분만 보입니다.`
원본에서는 "마우스"에 한정되어 있지 않기 때문에 이부분은 수정 필요합니다 (실제로 태고나, 매니아, 캐치는 마우스 기준이 아님)

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +- 플라 모드를 사용할 수 있는 osu! 장르: ![][osu!] ![][osu!taiko] ![][osu!catch] ![][osu!mania]
히든 문서도 포함해서 바꿔야 하는 내용이긴 합니다. 최근 대부분의 문서들을 되도록이면 원본을 따라가는 쪽으로 수정을 하고 있기 때문에 `사용할 수 있는 모드` 정도로 수정하는걸 권장합니다.

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +[osu!](/wiki/Game_mode/osu!)에서는 커서 주변에 환한 원, 즉 노트가 보이는 가시 영역이 플레이 필드에 표시됩니다. 이 가시 영역의 크기는 플레이어의 현재 콤보에 따라 달라집니다.
`주변에 환한 원 (즉, 가시 영역)` 혹은 `주변의 환한 원 (즉, 노트가 보이는 영역)` 으로 변경하는걸 추천드립니다.

원본에 맞추는 것도 있지만, "가시"랑 "노트가 보이는"이 중복이라 좀 길게 표현되는 감이 있습니다.

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +하단의 이미지 모두는 마치 플레이어의 커서에 가상의 손전등이 비춰지는 것 처럼 보입니다:
언급하고 있는건 하단의 이미지가 아닌 위에서 설명한 내용들이 가상의 손전등이 비치는 것처럼 보이게 한다는 것이기 때문에 이 해석은 잘못되었다고 생각합니다.

그리고 맞춤법 수정 필요합니다: `것 처럼` -> `것처럼`

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +플라를 히든 모드와 같이 걸 경우 플라의 가시 영역의 크기는 중요하지 않다는 것을 기억해주세요. 커서를 히트 오브젝트의 등장 타이밍에 신경쓰지 않는 동안 히트 오브젝트가 희미해집니다.
중간에 `시야가 제한되어`를 추가하는쪽이 원본에는 더 가깝다고 생각되네요.

맞춤법:
`기억해주세요` -> `기억해 주세요`
`신경쓰지` -> `신경 쓰지`

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +[osu!taiko](/wiki/Game_mode/osu!taiko)에서는 가시 영역의 위치가 히트 영역에 있습니다. osu!와 비슷하게 100 콤보, 200콤보일 때 가시 영역이 줄어들며 콤보가 깨지면 원래 크기로 돌아옵니다.
`200콤보`는 다른곳과 다르게 띄어쓰기가 안되어있네요.

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +히든 모드와 함께 사용할 경우 노트가 가시 영역에 보이기 전에 완전히 보이지 않게 되기 때문에 플라의 가시 영역은 쓸모가 없게 됩니다. 따라서 비트맵 전체를 외워야 합니다.
`노트가 가시 영역에 보이기 전에 완전히 보이지 않게 되기 때문에...`은 문장으로써는 상당히 어색한 느낌이 있습니다.
차라리 `노트가 가시 영역에 들어와도 완전히 보이지 않기 때문에...`가 더 낫지 않을까 싶습니다.

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +When paired with the Hidden mod, the fruits are momentarily visible if the catcher is *directly under* the fruits. That is, up until the player reaches 100x combo, at which point the fruits become co
미번역이네요. 아래는 급하게 번역한 내용이므로 적당히 수정해주시면 될 듯 합니다.

`히든 모드와 함께 사용할 경우 캐쳐가 과일 *바로 아래*에 있다면 과일이 순간적으로 보이게 됩니다. 이것은 즉, 100콤보에 도달하기 전, 가시 영역에 들어와도 보이지 않는 시점이 존재한다는 것입니다. 따라서 osu! 및 osu!taiko와 같이 비트맵 전체를 외워야 합니다.`

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +In [osu!mania](/wiki/Game_mode/osu!mania), the visible area is restricted to a relatively thin horizontal bar at the centre of the track whilst everything else is obstructed from view. In that sense,
아래쪽에 번역된 라인이 있는데 미번역된 라인이 아직 그대로 살아있네요.

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +[osu!mania](/wiki/Game_mode/osu!mania)에서는 가시 영역이 트랙 중앙에 얇은 가로로 제한되어 있으며, 그 외의 구역은 보이지 않습니다. 이러한 점에서 플라 모드는 히든과 (페이드 인)(/wiki/Game_modifier/Fade_In) 모드가 합쳐진 느낌입니다. 또한, 가시 구역 크기의 변화가 없습니다.
`구역` -> `영역`
`(페이드 인)(/wiki/Game_modifier/Fade_In)` -> `[페이드 인](/wiki/Game_modifier/Fade_In)`

단어 일관성 및 링크 오류
그리고 추가적으로 `변화가` -> `변화는`이 더 낫지 않을까 싶긴 합니다만...

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +- The Flashlight mod was originally subjected to heavy controversy regarding the implementation in 2010 for being the easiest mod to hack on; subsequently forcing the mod to be unranked until a patch
마찬가지로 아래쪽에 번역된 라인 있는데 미번역된 라인 그대로 남아있습니다.

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +가시 영역의 크기는 100 콤보, 200 콤보일 때 더 작아집니다. 만약 플레이어의 콤보가 깨진다면 가시 영역의 크기는 처음 크기로 돌아옵니다. 추가적으로, [슬라이더](/wiki/Hit_object/Slider)의 경우 가시 영역이 슬라이더가 끝날 때 까지 더 어두워집니다.
`때 까지` -> `때까지`

단순 맞춤법 오류입니다

2022-04-13 21:55 UTC, libneko commented on wiki/Game_modifier/Flashlight/ko.md
> +- 플라는 2010년 구현 당시, 쉽게 해킹하거나 악용할 수 있는 모드로 큰 논란이 있었습니다. 그 후 플라의 취약점 보완 패치가 이루어질 때 까지 플라 사용이 불가능했습니다.
`때 까지` -> `때까지`

2022-04-14 00:27 UTC, Sightread-osu commented
작년에 모드들 번역할 때에는 번역 검수해주신 분이 아무도 없었는데 오탈자나 오역 지적해주셔서 감사합니당🥺

2022-04-14 12:27 UTC, libneko commented
혹시 수정한거 커밋이 안된 상황인가요? Resolve는 되어있는데 변화가 없네요.

2022-04-14 15:20 UTC, Sightread-osu commented
출근하면서 잠깐 확인한거라 급하다고 생각되지 않아서 주말 오전에 수정하겠습니다~

2022-04-21 18:02 UTC, Walavouchey commented
please only resolve conversations after you've pushed the changes

2022-04-24 05:44 UTC, Sightread-osu commented
한동안 확인하지 못했네요. 위 수정 요청 사항들 보니 어중간한 실력으로 번역 기여를 하기에는 한참 부족하다는 것을 알게 되었습니다. 깃허브는 거의 사용하지 않아 추후에 생기는 추가 수정 사항이 있을 때 확인을 못할 확률이 크다고 생각되어 미래에 있을 다른 기여자분에게 맡기겠습니다. 도와주셔서 감사하고 영어 실력이 충분히 향상되면 다시 돌아오겠습니다 :)

2022-04-24 05:44 UTC, closed without merging