Update ru.md
ppy/osu-wiki pull request #7179
Opened 2022-04-13 22:09 UTC by Ldashy1

Подогнана часть текста с целью улучшения её общей читабельности и понимания основ ранкинга [Edited a part of the text to improve its readability and understanding of the basics of ranking]

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-04-13 23:07 UTC, TicClick requested changes
мне понравилось, за исключением тире не к месту

2022-04-13 23:07 UTC, TicClick commented on wiki/Ranking_Criteria/ru.md
> +- **[Владелец карты](/wiki/Beatmap/Beatmap_host) и [гостевые мапперы](/wiki/Beatmap/Guest_difficulty) могут редактировать свои собственные сложности так, как они этого пожелают.** Если владелец карты
тут двусмысленность получается, потому что сложност**и** — тоже «они»

2022-04-13 23:07 UTC, TicClick commented on wiki/Ranking_Criteria/ru.md
> +- **Названия [гостевых сложностей](/wiki/Beatmap/Guest_difficulty), указывающие на их авторов, должны быть согласованы между несколькими картами.** Использование различных форм никнейма затрудняет по
«тем самым» не нужно обособлять
```suggestion
- **Названия [гостевых сложностей](/wiki/Beatmap/Guest_difficulty), указывающие на их авторов, должны быть согласованы между несколькими картами.** Использование различных форм никнейма затрудняет понимание того, кто создал сложность, и тем самым вводит игроков в заблуждение.
```

2022-04-13 23:07 UTC, TicClick commented on wiki/Ranking_Criteria/ru.md
> +- **Исполнители песни должны иметь отношение к реально существующим людям.** Если установить авторство не удаётся — необходимо указать в качестве исполнителя `Unknown Artist`. Программа или вымышленн
здесь нигде не нужны тире, только запятые

2022-04-13 23:07 UTC, TicClick commented on wiki/Ranking_Criteria/ru.md
> +- **Если официальной романизации имени исполнителя не существует — оно должно быть романизовано в том порядке, в каком оно записано в юникодном поле Artist.**
лишнее тире

2022-04-13 23:07 UTC, TicClick commented on wiki/Ranking_Criteria/ru.md
> +- **Размеры фонового видео не должны превышать 1280 пикселей в ширину и 720 пикселей в высоту,** чтобы оно не было излишне большим. Кроме того, следует избегать масштабирования видео с более низким р
громоздко, но суть лучше передаёт, можешь чуть другую формулировку придумать?

2022-04-13 23:07 UTC, TicClick commented on wiki/Ranking_Criteria/ru.md
> +- **Элементы скина с прозрачностью должны быть в формате `.png`.** Если прозрачных областей нет — можно использовать любой подходящий формат, который занимает мало места и распознаётся в osu!.
тире лишнее, остальное ок
```suggestion
- **Элементы скина с прозрачностью должны быть в формате `.png`.** Если прозрачных областей нет, можно использовать любой подходящий формат, который занимает мало места и распознаётся в osu!.
```

2022-04-13 23:07 UTC, TicClick commented on wiki/Ranking_Criteria/ru.md
> +- **Следите, чтобы сториборд не приводил к просадкам производительности, и чтобы при игре с ним не происходило резких изменений FPS, которые могут ухудшить впечатление от игры.** Чтобы выявить возмож
здесь предполагается, что тестирование — это в принципе длящийся процесс, и протестировать нужно более одного раза, значит, без «про-»

2022-04-14 19:38 UTC, Ldashy1 commented on wiki/Ranking_Criteria/ru.md
> +- Инструменты существуют, чтобы **помогать** вам, а не **заменять** вас.
исправил

2022-04-14 19:38 UTC, Ldashy1 commented on wiki/Ranking_Criteria/ru.md
> +- **Правила:** если что-то помечено как правила — это нельзя нарушать **ни в коем случае.**
исправил

2022-04-14 19:46 UTC, TicClick commented
напиши, когда всё применишь (или иным способом адресуешь), чтобы я ещё раз посмотрел

2022-04-14 19:49 UTC, Ldashy1 commented on wiki/Ranking_Criteria/ru.md
> +- **Размеры фонового видео не должны превышать 1280 пикселей в ширину и 720 пикселей в высоту,** чтобы оно не было излишне большим. Кроме того, следует избегать масштабирования видео с более низким р
поменял на "следует избегать искусственного увеличения разрешения"

2022-04-14 19:56 UTC, Ldashy1 commented
@TicClick посмотри ещё раз, вдруг я что-то упустил

2022-04-14 20:05 UTC, TicClick approved these changes
спасибо. будешь ещё переводить что-нибудь?

2022-04-14 20:06 UTC, merged

2022-04-14 20:25 UTC, Ldashy1 commented
> спасибо. будешь ещё переводить что-нибудь?

пока думаю над этим, нужно будет пройтись по русской вики в поиске каких-нибудь смысловых недочетов и недостающих фрагментов перевода

2022-04-14 20:29 UTC, TicClick commented
у нас их полно, потому что я вычитывал и переводил далеко не все статьи (равно как и полно отсутствующих переводов). подробнее см. [[1]](https://osu.ppy.sh/community/forums/topics/566978?n=1) [[2]](https://clayton.cc/osu-wiki-status/ru)