[ES] Update in `osu!supporter`
ppy/osu-wiki pull request #7197
Opened 2022-04-17 19:23 UTC by ImMock

Updated to the english version

Waiting for review

2022-04-17 19:28 UTC, Repflez requested changes

2022-04-17 19:28 UTC, Repflez commented on wiki/osu!supporter/es.md
> +Adicionalmente, los usuarios con osu!supporter tienen límites de descarga de beatmaps poco estrictos.
```diff
-poco estrictos.
+menos estrictos.
```

2022-04-17 19:33 UTC, ImMock commented on wiki/osu!supporter/es.md
> +Adicionalmente, los usuarios con osu!supporter tienen límites de descarga de beatmaps poco estrictos.
All done

2022-04-17 19:35 UTC, Repflez approved these changes

2022-04-17 19:42 UTC, Walavouchey submitted a review, later dismissed

2022-04-17 19:42 UTC, Walavouchey commented on wiki/osu!supporter/es.md
> +- Descargas automáticas de beatmaps mientras juegas en una sala [multijugador](/wiki/Gameplay/Multiplayer) o te encuentras [espectando](/wiki/Gameplay/Spectating) a otro usuario, como una [configurac
missed one bullet point here

2022-04-17 19:49 UTC, ImMock commented on wiki/osu!supporter/es.md
> +- Descargas automáticas de beatmaps mientras juegas en una sala [multijugador](/wiki/Gameplay/Multiplayer) o te encuentras [espectando](/wiki/Gameplay/Spectating) a otro usuario, como una [configurac
Added the missing bullet point

2022-04-20 22:58 UTC, Repflez approved these changes

2022-04-20 23:00 UTC, merged