[FR] Add `Help_centre\Tournament_bans`
ppy/osu-wiki pull request #7200
Opened 2022-04-18 15:41 UTC by DoryanR

Proposal to add the French translation of the wiki page `Tournament_bans`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-04-19 12:28 UTC, Biokax requested changes

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +Un bannissement des tournois est très rarement prononcées en tant que telles, mais en général, les joueurs qui retournent dans un appel pour une [restriction de compte](/wiki/Help_centre/Account_rest
```suggestion
Un bannissement des tournois est très rarement prononcé en tant que tel, mais en général, les joueurs qui retournent dans un appel pour une [restriction de compte](/wiki/Help_centre/Account_restrictions) sont soumis a une durée d'au moins 1 an.
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +En raison de l'importance des enjeux d'un tournoi, les bannissements des tournois sont traiter avec le plus grand sérieux, il n'y a donc pas d'indulgence comme pour les restriction de compte.
```suggestion
En raison de l'importance des enjeux d'un tournoi, les bannissements des tournois sont traités avec le plus grand sérieux, il n'y a donc pas d'indulgence comme pour les restriction de compte.
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +Toute violation sévère des [règles de la communauté](/wiki/Rules) qui ont lieu lors d'un [tournois officiellement supporté](/wiki/Tournaments/Official_support) est souvent la cause d'un bannissement
```suggestion
Toute violation sévère des [règles de la communauté](/wiki/Rules) qui a lieu lors d'un [tournoi officiellement supporté](/wiki/Tournaments/Official_support) est souvent la cause d'un bannissement d'un tournoi, même si cela n'aurait eu pour conséquence une infraction en dehors du cadre de la compétition.
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +Tous les utilisateurs retournant dans le jeu après une procédure de restriction dans le cadre des conditions d'appel standard sont également soumis à un [bannissement temporaire des tournois d'une du
```suggestion
Tous les utilisateurs retournant dans le jeu après une procédure de restriction dans le cadre des conditions d'appel standard sont également soumis à un [bannissement temporaire des tournois d'une duré de 1 an](/wiki/Help_centre/Account_restrictions#common-restriction-reasons-and-cooldowns), qui peut-être prolongé à la discrétion de [l'Équipe de support aux comptes](/wiki/People/The_Team/Account_support_team).
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +Toute utilisation d'un logiciel tiers de triche ou toute autres méthodes pour gagner un avantages déloyal vis a vis des autres participants dans un tournois officiellement supporté résultera en un ba
```suggestion
Toute utilisation d'un logiciel tiers de triche ou toute autres méthodes pour gagner un avantages déloyal vis a vis des autres participants dans un tournoi officiellement supporté résultera en un bannissement permanent. Dans certaines situations, des cas d'abus particulièrement excessifs peuvent également donner lieu à une telle sanction.
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +- Organiser des campagnes ciblé d'insulte envers les participants ou des organisateurs bien en dehors de la limite de la critique
```suggestion
- Organiser des campagnes ciblées d'insulte envers les participants ou des organisateurs bien en dehors de la limite de la critique
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +Dans des cas particuliers, [l'Équipe de support aux comptes](/wiki/People/The_Team/Account_support_team) peut étudier des cas individuel dans leurs discrétion et retirer ou réappliquer des sanctions
```suggestion
Dans des cas particuliers, [l'Équipe de support aux comptes](/wiki/People/The_Team/Account_support_team) peut étudier des cas individuel dans leurs discrétion et retirer ou réappliquer des sanctions appropriée pour être sûr que cela reste cohérent avec les situations passés.
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +Les informations concernant votre status de bannissement des tournois peut être communiquer aux organisateurs des tournois avant de postuler, qu'il soit officiel ou non
```suggestion
Les informations concernant votre status de bannissement des tournois peut être communiqué aux organisateurs des tournois avant de postuler, qu'il soit officiel ou non
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Un mauvaise conduite d'un joueur lors d'un tournois officiellement supporté | 1 ou 2 an(s) |  |
```suggestion
| Une mauvaise conduite d'un joueur lors d'un tournois officiellement supporté | 1 ou 2 an(s) |  |
```

2022-04-19 12:28 UTC, Biokax commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Un retour dans les conditions standard d'appels | 1 ou 2 an(s) | Peut être prolongé a la discrétion de l'Équipe de support aux comptes |
```suggestion
| Un retour dans les conditions standard d'appels | 1 ou 2 an(s) | Peut-être prolongé a la discrétion de l'Équipe de support aux comptes |
```

2022-04-20 19:14 UTC, Ganondorf-1 requested changes

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +## Qu'est t'il possible de faire en cas de bannissement d'un tournoi ?
```suggestion
## Que puis-je faire en cas de bannissement des tournois ?
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +Dans des cas particuliers, [l'Équipe de support aux comptes](/wiki/People/The_Team/Account_support_team) peut étudier des cas individuel dans leurs discrétion et retirer ou réappliquer des sanctions
```suggestion
Dans des cas particuliers, [l'Équipe de support aux comptes](/wiki/People/The_Team/Account_support_team) peut étudier des cas individuels à leur discrétion et retirer ou réappliquer des sanctions appropriées pour être sûr que cela reste cohérent avec les situations passées.
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +Vous pouvez continuer à jouer dans les tournois communautaire qui ne requiert pas de support officiel ou requiert une vérification à la discrétion des personnes qui organisent ce genre d'événements.
```suggestion
Vous pouvez continuer à jouer dans les tournois communautaires qui n'ont pas de support officiel ou de screening à la discrétion des organisateurs de ce genre d'événements.
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +Les informations concernant votre status de bannissement des tournois peut être communiqué aux organisateurs des tournois avant de postuler, qu'il soit officiel ou non
```suggestion
Les informations concernant votre statut de bannissement des tournois peuvent être communiquées aux organisateurs des tournois sur demande, que le tournoi soit officiel ou non.
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +## Raisons communes de bannissement d'un tournoi et durée
```suggestion
## Raisons communes de bannissement des tournois et durées
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Raisons du bannissement du tournoi | Durée | Commentaire |
```suggestion
| Raison du bannissement des tournois | Durée | Commentaire |
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Une mauvaise conduite d'un joueur lors d'un tournois officiellement supporté | 1 ou 2 an(s) |  |
```suggestion
| Mauvaise conduite d'un joueur lors d'un tournoi officiellement supporté | 1 ou 2 ans |  |
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Un retour dans les conditions standard d'appels | 1 ou 2 an(s) | Peut-être prolongé a la discrétion de l'Équipe de support aux comptes |
```suggestion
| Retour dans les conditions standards d'appel | 1 ou 2 ans | Peut-être prolongé à la discrétion de l'Équipe de support aux comptes |
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Une utilisation de plusieurs comptes ou partage de compte lors d'un tournois officiellement supporté | Permanent | Engendre également une restriction |
```suggestion
| Utilisation de plusieurs comptes ou partage de compte lors d'un tournoi officiellement supporté | Permanent | Engendre également une restriction |
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Une utilisation d'un logiciel tiers ou de tout utilitaire de triche durant les tournois officiellement supporté | Permanent | Engendre également une restriction |
```suggestion
| Utilisation d'un logiciel tiers ou de tout utilitaire de triche lors d'un tournoi officiellement supporté | Permanent | Engendre également une restriction |
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Une utilisation d'informations de tournois privé/confidentiel pour gagner ou conférer un avantage déloyal | Permanent | Peut causer également une restriction |
```suggestion
| Utilisation d'informations de tournois privées/confidentielles pour gagner ou conférer un avantage déloyal | Permanent | Peut également causer une restriction |
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +| Un abus sévère ou harcèlement vis a vis d'un organisateur/personnel/participants du tournois | Permanent | Peut causer également une restriction |
```suggestion
| Abus sévère ou harcèlement envers des organisateurs/staff/participants du tournoi | Permanent | Peut également causer une restriction |
```

2022-04-20 19:14 UTC, Ganondorf-1 commented on wiki/Help_centre/Tournament_bans/fr.md
> +Un bannissement des tournois empêche un joueur de s'impliquer dans les tournois officiels, à tous les niveaux. Cela inclus le jeu et la modération/gestion, ou tout autres types d'assistances.
```suggestion
Un bannissement des tournois empêche un joueur de s'impliquer dans les tournois officiels, à tous les niveaux. Cela inclut le jeu et la modération/gestion, ou tout autre type d'assistance.
```

2022-04-22 06:55 UTC, Walavouchey approved these changes

2022-04-22 06:57 UTC, merged