[ES] Add `Skinning/FAQ`
ppy/osu-wiki pull request #7203
Opened 2022-04-18 22:32 UTC by ImMock

Translation for the spanish language, ready for review

2022-04-20 23:12 UTC, Repflez requested changes

2022-04-20 23:12 UTC, Repflez commented on wiki/Skinning/FAQ/es.md
> +Skinning es un simple mecanismo de cambio de imágenes que osu! cargara después de seleccionar una skin en las opciones. Montar una skin es fácil, pero crear los archivos para esta, es un poco más dif
```suggestion
Skinning es un simple mecanismo de cambio de imágenes que osu! cargará después de seleccionar una skin en las opciones. Montar una skin es fácil, pero crear los archivos para esta, es un poco más difícil de lograr.
```

2022-04-20 23:12 UTC, Repflez commented on wiki/Skinning/FAQ/es.md
> +**Sin embargo, por favor, nunca solicites una skin en ningún lugar de los foros.** El incumplimiento de esta regla hará que tu hilo sea trasladado a los terrenos baldíos.
```suggestion
**Sin embargo, por favor, nunca solicites una skin en ningún lugar de los foros.** El incumplimiento de esta regla hará que tu hilo sea trasladado al olvido.
```

Abandoned Wasteland is a name here, no need to translate it directly.

2022-04-20 23:12 UTC, Repflez commented on wiki/Skinning/FAQ/es.md
> +En primer lugar, no preguntes esto en los foros; de lo contrario, lo más probable es que tu hilo sea trasladado a los terrenos baldíos. En segundo lugar, es mejor que le pidas a esa persona la skin q
```suggestion
En primer lugar, no preguntes esto en los foros; de lo contrario, lo más probable es que tu hilo sea trasladado al olvido. En segundo lugar, es mejor que le pidas a esa persona la skin que está utilizando. Puede que te la den, pero no siempre será el caso.
```

Same as above

2022-04-20 23:12 UTC, Repflez commented on wiki/Skinning/FAQ/es.md
> +Primero, revisa los archivos listados para verificar que el archivo que desees animar pueda ser animado. Si es posible, entonces podrás comenzar la animación. Para poder hacer esto, necesitaras que c
```suggestion
Primero, revisa los archivos listados para verificar que el archivo que desees animar pueda ser animado. Si es posible, entonces podrás comenzar la animación. Para poder hacer esto, necesitarás que cada fotograma este en imágenes separadas. Cuando cuentes con esto, nombre cada archivo, seguido de un guion (`-`), entonces una cuenta de índice (comenzando de 0). Repite esto por el resto de fotogramas.
```

2022-04-20 23:12 UTC, Repflez commented on wiki/Skinning/FAQ/es.md
> +- Desactivar e; `Hit Lighting` en las [opciones](/wiki/Client/Options).
```suggestion
- Desactivar el `Hit Lighting` en las [opciones](/wiki/Client/Options).
```

2022-04-22 06:47 UTC, Walavouchey approved these changes

2022-04-22 06:49 UTC, merged