[ES] Add `Formatting`
ppy/osu-wiki pull request #7206
Opened 2022-04-20 00:37 UTC by ImMock

Ready for review

2022-04-21 13:07 UTC, SrIzan10 submitted a review, later dismissed
seems fine for me!

2022-04-21 13:24 UTC, Walavouchey requested changes

2022-04-21 13:24 UTC, Walavouchey commented on wiki/Article_styling_criteria/Formatting/es.md
> +TODOS los encabezados deberán usar el formato de oración.
probably doesn't need to be in capital

```suggestion
Todos los encabezados deberán usar el formato de oración.
```

2022-04-22 06:37 UTC, Walavouchey approved these changes

2022-04-22 06:41 UTC, merged