[PT-BR] Add `Beatmap_description`
ppy/osu-wiki pull request #7217
Opened 2022-04-22 17:31 UTC by GranularBow8193

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-04-23 16:28 UTC, Walavouchey commented
if you have someone else who can review this, tell them to comment here on github. otherwise leave the box unticked ty

2022-04-23 19:16 UTC, GranularBow8193 commented
@LeoFLT Can you review the pull requests that are open? My goal is to translate all wiki posts into PT-BR, so I would appreciate your help :)

2022-04-23 21:08 UTC, LeoFLT requested changes
Looks good to me otherwise

2022-04-23 21:08 UTC, LeoFLT commented on wiki/Beatmap/Beatmap_description/pt-br.md
> +**A descrição de Beatmap**  é uma área pequena embaixo da página do [beatmap](/wiki/Beatmap) que dá aos jogadores uma informação sobre o beatmap usando o [BBCode](/wiki/BBCode). Ele normalmente desta
```suggestion
**A descrição de Beatmap** é uma área pequena embaixo da página do [beatmap](/wiki/Beatmap) que dá aos jogadores uma informação sobre o beatmap usando o [BBCode](/wiki/BBCode). Ele normalmente destaca fatos sobre o criador do beatmap que ele acha suficientemente importantes, ou é usado para divulgar outros projetos de mapeamento.
```

2022-04-24 07:34 UTC, Walavouchey approved these changes

2022-04-24 07:37 UTC, merged