[FR] Update `Beatmap_Spotlights`
ppy/osu-wiki pull request #7226
Opened 2022-04-23 09:56 UTC by DoryanR

Proposal to update the French translation of the wiki page `Beatmap_Spotlights`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-04-24 07:32 UTC, Ganondorf-1 requested changes

2022-04-24 07:32 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +   - Pour les 3 dernières semaines, chaque playlist durera 1 semaine au lieu de 1.
```suggestion
   - Pour les 3 dernières semaines, chaque playlist durera 1 semaine au lieu de 2.
```

2022-04-24 07:32 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
>     - Les curateurs peuvent sélectionner plusieurs beatmaps d'un même ensemble de beatmaps.
```suggestion
   - Les curateurs peuvent sélectionner plusieurs difficultés d'une même beatmap.
```

2022-04-25 12:12 UTC, Ganondorf-1 requested changes

2022-04-25 12:12 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
>  3. Ces beatmaps servent de recommandations à l'ensemble de la communauté d'osu!
```suggestion
3. Ces beatmaps servent de recommandations à l'ensemble de la communauté d'osu!.
```

2022-04-25 12:12 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +   - 12 beatmaps sélectionnées doivent être dans le niveau de difficulté Expert.
```suggestion
   - 12 beatmaps sélectionnées doivent se situer dans le niveau de difficulté Expert.
```

2022-04-25 16:23 UTC, Ganondorf-1 approved these changes

2022-04-25 20:55 UTC, Walavouchey approved these changes

2022-04-25 20:57 UTC, merged