[ID] Add "Ranking criteria/osu!catch"
ppy/osu-wiki pull request #7227
Opened 2022-04-23 12:52 UTC by mousesalt

new translation Indonesia for ranking criteria osu!catch here.
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-13 17:25 UTC, hikikuman requested changes

2022-05-13 17:25 UTC, hikikuman commented on wiki/Ranking_Criteria/osu!catch/id.md
> +**Ranking criteria osu!catch** menjabarkan [aturan dan pedoman](/wiki/Ranking_Criteria#general-terms) spesifik untuk [beatmaps](/wiki/Beatmap) [osu!catch](/wiki/Game_mode/osu!catch)  yang wajib diiku
```suggestion
**Ranking criteria osu!catch** menjabarkan [aturan dan pedoman](/wiki/Ranking_Criteria#general-terms) spesifik untuk [beatmap](/wiki/Beatmap) [osu!catch](/wiki/Game_mode/osu!catch) yang wajib diikuti untuk tahapan dari [Prosedur ranking beatmap](/wiki/Beatmap_ranking_procedure).
```

2022-05-13 17:25 UTC, hikikuman commented on wiki/Ranking_Criteria/osu!catch/id.md
> +Keseluruhan aturan dan pedoman yang berlaku untuk setiap jenis kesulitan osu!catch. Aturan dan pedoman ritme berlaku untuk beatmap sekitar 180 BPM dengan 4/4 time signature. Jika lagu secara drastis
```suggestion
Keseluruhan aturan dan pedoman berlaku untuk setiap jenis tingkat kesulitan osu!catch. Aturan dan pedoman ritme berlaku untuk beatmap sekitar 180 BPM dengan 4/4 time signature. Jika lagu secara drastis lebih cepat atau lebih lambat, beberapa variabel mungkin berbeda, seperti yang dijelaskan dalam [Penskalaan BPM di ranking criteria](/wiki/Ranking_Criteria/Scaling_BPM).
```

2022-05-13 17:25 UTC, hikikuman commented on wiki/Ranking_Criteria/osu!catch/id.md
> +- **Pastikan [kombo](/wiki/Beatmapping/Combo) tidak mencapai panjang yang tidak masuk akal.** Menangkap [fruit](/wiki/Hit_object/Fruit) akan menumpuk di piring dan berpotensi menghalangi pandangan pe
```suggestion
- **Pastikan [kombo](/wiki/Beatmapping/Combo) tidak mencapai panjang yang tidak masuk akal.** Menangkap [fruit](/wiki/Hit_object/Fruit) akan menumpuk di piring dan berpotensi menghalangi pandangan pemain. Ingatlah bahwa slider tail, repeat dan [spinner](/wiki/Hit_object/Spinner) [banana](/wiki/Hit_object/Banana) juga dihitung sebagai "fruit". Kombo baru harus ditempatkan secara teratur untuk membersihkan piring dan menghindari hal ini terjadi.
```
kayanya ini harusnya ditulis banana juga sih. kalo mau keep, artinya "fruit" juga harus jadi "buah". gimana?

2022-05-13 17:25 UTC, hikikuman commented on wiki/Ranking_Criteria/osu!catch/id.md
> +- **[Hyperdash](/wiki/Gameplay/Hyperdash) yang [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) tidak boleh digunakan lebih dari dua kali antara [fruits](/wiki/Hit_object/Fruit) secara ber
```suggestion
- **[Hyperdash](/wiki/Gameplay/Hyperdash) yang [basic-snapped](/wiki/Gameplay/Dash_snapping#basic-snapped) tidak boleh digunakan lebih dari dua kali antara [fruit](/wiki/Hit_object/Fruit) secara berturut-turut.**
```

2022-05-13 17:25 UTC, hikikuman commented on wiki/Ranking_Criteria/osu!catch/id.md
> +- **[Kombo](/wiki/Beatmapping/Combo) tidak boleh melebihi 10 objek termasuk slider tail dan pengulangan.** [Spinners](/wiki/Hit_object/Spinner) adalah pengecualian.
```suggestion
- **[Kombo](/wiki/Beatmapping/Combo) tidak boleh melebihi 10 objek termasuk slider tail dan pengulangan.** [Spinner](/wiki/Hit_object/Spinner) adalah pengecualian.
```

2022-05-13 17:25 UTC, hikikuman commented on wiki/Ranking_Criteria/osu!catch/id.md
> +- **[Combos](/wiki/Beatmapping/Combo) tidak boleh melebihi 16 objek termasuk tail slider dan pengulangan.** [Spinner](/wiki/Hit_object/Spinner) adalah pengecualian.
```suggestion
- **[Kombo](/wiki/Beatmapping/Combo) tidak boleh melebihi 16 objek termasuk tail slider dan pengulangan.** [Spinner](/wiki/Hit_object/Spinner) adalah pengecualian.
```

2022-05-14 16:35 UTC, Walavouchey approved these changes

2022-05-14 16:37 UTC, merged