[DE] Add `Help_centre/Tournament_bans`; update `Help_centre/Account`
ppy/osu-wiki pull request #7267
Opened 2022-05-02 16:18 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-02 18:13 UTC, respektive requested changes

2022-05-02 18:13 UTC, respektive commented on wiki/Help_centre/Tournament_bans/de.md
> +- der Versuch, durch einen weiteren Account eine Stummschaltung oder ein Verstoß zu umgehen
```suggestion
- der Versuch, durch einen weiteren Account eine Stummschaltung oder einen Verstoß zu umgehen
```

2022-05-03 14:29 UTC, The-Last-Cookie commented on wiki/Help_centre/Tournament_bans/de.md
> +Du darfst weiter in Turnieren von der Community spielen, die keine offizielle Unterstützung anfordern oder eine Überprüfung bei der Bewertung der Veranstalter von solchen Events benötigen.
I've read this sentence more in the way of that the organisers of these community tournaments need to be checked, such as whether their judgement is fair, but you're probably right.

2022-05-03 14:39 UTC, respektive commented on wiki/Help_centre/Tournament_bans/de.md
> +Du darfst weiter in Turnieren von der Community spielen, die keine offizielle Unterstützung anfordern oder eine Überprüfung bei der Bewertung der Veranstalter von solchen Events benötigen.
The screening process is for checking players, yeah.

2022-05-03 14:39 UTC, respektive approved these changes

2022-05-06 19:35 UTC, Walavouchey approved these changes

2022-05-06 19:37 UTC, merged