[FR] Update `osu!tourney` `osu!tourney/setup`
ppy/osu-wiki pull request #7269
Opened 2022-05-02 17:33 UTC by Biokax

## Self-check

update of the osu!tourney default and setup pages

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-02 20:25 UTC, DoryanR requested changes

2022-05-02 20:25 UTC, DoryanR commented on wiki/osu!_tournament_client/osu!tourney/Setup/fr.md
> +- `Aspect` : Le rapport d'aspect des affichages du champ de jeu.
```suggestion
- `Aspect` : Le rapport d'aspect des affichages du terrain de jeu.
```

2022-05-02 21:12 UTC, DoryanR submitted a review, later dismissed

2022-05-04 10:38 UTC, DoryanR approved these changes

2022-05-04 14:31 UTC, Walavouchey approved these changes

2022-05-04 14:34 UTC, merged