Staff log fr
ppy/osu-wiki pull request #7271
Opened 2022-05-02 19:02 UTC by Biokax

## Self-check
- [ ] Format all dates from **YYYY-MM-DD** to **DD-MM-YYYY** left (bottom of the file)
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-02 20:14 UTC, DoryanR approved these changes

2022-05-03 03:11 UTC, Ganondorf-1 requested changes

2022-05-03 03:11 UTC, Ganondorf-1 commented on wiki/Staff_Log/2021/fr.md
>  Les  abréviations des groupes d'utilisateurs utilisées dans ce registre sont les suivantes :
```suggestion
Les abréviations des groupes d'utilisateurs utilisées dans ce registre sont les suivantes :
```

2022-05-04 14:14 UTC, Biokax commented on wiki/Staff_Log/fr.md
> +- [2022](2022)
```suggestion
- [2022](2022)

```

2022-05-07 17:57 UTC, DoryanR approved these changes

2022-05-09 07:11 UTC, Walavouchey approved these changes

2022-05-09 07:12 UTC, merged