[FR] Update `Ranking_Criteria` `Ranking_Criteria/osu!mania` `Ranking_Criteria/osu!taiko` `Ranking_Criteria/osu!catch`
ppy/osu-wiki pull request #7277
Opened 2022-05-03 18:34 UTC by Biokax

Update of Ranking criteria related articles

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-04 06:04 UTC, DoryanR requested changes

2022-05-04 06:04 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +  - **...ne pas être encodé vers le haut à partir d'un débit binaire inférieur.**
```suggestion
  - **...ne pas être encodé trop haut à partir d'un débit binaire inférieur.**
```

2022-05-04 06:04 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- **Le fichier audio et les fichiers hitsound d'une beatmap ne doivent pas présenter de distorsions sonores audibles et injustifiées**, comme des coupures, des étouffements ou des grésillements qui n
```suggestion
- **Le fichier audio et les fichiers hitsound d'une beatmap ne doivent pas présenter de distorsions sonores audibles et injustifiées**, comme des coupures, des étouffements ou des grésillements qui ne sont manifestement pas voulus par l'artiste ou qui ne font pas partie de l'identité de la musique. La meilleure façon de le déterminer est d'écouter l'audio, plutôt que d'utiliser un logiciel.
```

2022-05-05 08:32 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +- Soyez critique à l'égard de ce qu'ils soulignent et ne les suivez pas aveuglément.
Ta oublier d'appliquer cette modif, c'est voulu ?

2022-05-05 11:55 UTC, Biokax commented on wiki/Ranking_Criteria/fr.md
> +- Soyez critique à l'égard de ce qu'ils soulignent et ne les suivez pas aveuglément.
> Ta oublier d'appliquer cette modif, c'est voulu ?

mes commentaires étaient en "Pending" j'avais pas fait attention du coup ils ne se sont pas envoyés.
Je disais que c'était "signalent" à la place

2022-05-05 13:26 UTC, DoryanR approved these changes

2022-05-05 13:47 UTC, Ganondorf-1 requested changes

2022-05-05 13:47 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Le [slider tick rate](/wiki/Beatmapping/Slider_tick_rate) ne doit pas être modifié par le fichier `.osu`.** La plupart des valeurs personnalisées donnent lieu à des unsnapped slider ticks, mais l
```suggestion
- **Le [slider tick rate](/wiki/Beatmapping/Slider_tick_rate) ne doit pas être modifié par le fichier `.osu`.** La plupart des valeurs personnalisées donnent lieu à des unsnapped slider ticks, mais les tick rates 0,5, 1,333 et 1,5 ont une utilité pratique et ne peuvent être appliqués que lorsqu'ils ne donnent pas lieu à des unsnapped slider ticks.
```

2022-05-05 13:47 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +  - **Les difficultés inférieures à la difficulté la plus élevée peuvent combiner les temps de pause avec les drain time pour atteindre les seuils ci-dessus.** Cela ne s'applique pas aux difficultés
```suggestion
  - **Les difficultés inférieures à la difficulté la plus élevée peuvent combiner les temps de pause avec les drain time pour atteindre les seuils ci-dessus.** Cela ne s'applique pas aux difficultés dont le drain time est inférieur à 30 secondes. Si la difficulté la plus basse de la beatmap est Hard ou Insane, l'appréciation de l'adéquation des éléments de gameplay est du ressort des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) pour les modes de jeu correspondants.
```

2022-05-05 13:47 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +[AiMod](/wiki/Client/Beatmap_editor/AiMod) AiMod signalera ces problèmes, ainsi que de rares faux positifs. Les faux positifs se produisent principalement sur les extrémités des slider ends et les re
```suggestion
[AiMod](/wiki/Client/Beatmap_editor/AiMod) signalera ces problèmes, ainsi que de rares faux positifs. Les faux positifs se produisent principalement sur les extrémités des slider ends et les reverse sliders, et doivent être vérifiés manuellement ou avec d'autres outils. Les objets d'une section musicale nécessitant des diviseurs de temps non pris en charge (par exemple 1/11) peuvent soit :
```

2022-05-06 19:24 UTC, Ganondorf-1 requested changes

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Il ne doit pas y avoir d'images obscènes dans [l'arrière-plan](/wiki/Beatmap/Background)/le storyboard/le contenu vidéo.** Cela inclut la nudité, la quasi-nudité, les références sexuelles, la vio
```suggestion
- **Il ne doit pas y avoir d'images obscènes dans l'[arrière-plan](/wiki/Beatmap/Background)/le storyboard/le contenu vidéo.** Cela inclut la nudité, la quasi-nudité, les références sexuelles, la violence, la toxicomanie, etc. Voir les [règles générales relatives au contenu des musiques](/wiki/Rules/Visual_Content_Considerations) pour des règles plus détaillées.
```

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
>  - **Les [pauses](/wiki/Beatmap/Break) doivent être insérés avec les restrictions de l'[éditeur de beatmap](/wiki/Client/Beatmap_editor).**
```suggestion
- **Les [pauses](/wiki/Beatmap/Break) doivent être insérées avec les restrictions de l'[éditeur de beatmap](/wiki/Client/Beatmap_editor).**
```

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
>  - **Les créateurs des médias utilisés dans une beatmap doivent être crédités dans la description de la beatmap.** Selon les [Directives d'utilisation du contenu](/wiki/Rules/Content_Usage_Guidelines)
```suggestion
- **Les créateurs des médias utilisés dans une beatmap doivent être crédités dans la description de la beatmap.** Selon les [Directives d'utilisation du contenu](/wiki/Rules/Content_Usage_Guidelines), les médias utilisés dans les beatmaps devraient être autorisés dans osu!, et leur licence détaillera probablement la manière de créditer leurs créateurs. Les raisons courantes d'omettre les crédits dans la description sont les suivantes : difficulté excessive à trouver des sources, souhait des créateurs de ne pas être crédités et présence de crédits dans les champs artiste, titre ou source.
```

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +  - **Les difficultés inférieures à la difficulté la plus élevée peuvent combiner les temps de pause avec les drain time pour atteindre les seuils ci-dessus.** Cela ne s'applique pas aux difficultés
```suggestion
  - **Les difficultés inférieures à la difficulté la plus élevée peuvent combiner les temps de pause avec les drain times pour atteindre les seuils ci-dessus.** Cela ne s'applique pas aux difficultés dont le drain time est inférieur à 30 secondes. Si la difficulté la plus basse de la beatmap est Hard ou Insane, l'appréciation de l'adéquation des éléments de gameplay est du ressort des [Beatmap Nominators](/wiki/People/The_Team/Beatmap_Nominators) et de la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) pour les modes de jeu correspondants.
```

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
>  - **Évitez les noms de difficultés comportant des éléments descriptifs qui ne sont pas clairement liés à un créateur d'une [difficulté invité](/wiki/Beatmap/Guest_difficulty) ou à un niveau de diffic
```suggestion
- **Évitez les noms de difficultés comportant des éléments descriptifs qui ne sont pas clairement liés à un créateur d'une [guest difficulty](/wiki/Beatmap/Guest_difficulty) ou à un niveau de difficulté.** (e.g. Beatmap Creator's Tragic Love Extra)
```

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
>  - **Un objet qui est mal snapped parce qu'il passe ou se termine légèrement avant un nouveau [point de timing non hérité](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doit voir so
```suggestion
- **Un objet qui est mal snapped parce qu'il passe ou se termine légèrement avant un nouveau [point de timing non hérité](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) doit voir son tail snapped dans la nouvelle section de timing.** Pour les spinners et les long notes d'osu!mania, cela peut être réalisé en faisant glisser l'extrémité de l'objet dans la timeline. Pour les sliders, cela peut être réalisé en manipulant la slider velocity ou en éditant le fichier `.osu`.
```

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!catch/fr.md
>  - **Votre beatmap doit être théoriquement possible à SS.** Cela signifie qu'il doit être possible d'attraper absolument tous les [fruits](/wiki/Hit_object/Fruit), les [drop](/wiki/Hit_object/Juice_st
```suggestion
- **Votre beatmap doit être théoriquement possible à SS.** Cela signifie qu'il doit être possible d'attraper absolument tous les [fruits](/wiki/Hit_object/Fruit), les [drops](/wiki/Hit_object/Juice_stream#drop) et les [droplets](/wiki/Hit_object/Juice_stream#droplet).
```

2022-05-06 19:24 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/osu!taiko/fr.md
>  - **La manipulation du slider velocity est autorisée**, mais le slider velocity ne doit être modifié que pour les sections de la musique ayant des rythmes différents et ne doit pas être radicalement
```suggestion
- **La manipulation de la slider velocity est autorisée**, mais la slider velocity ne doit être modifiée que pour les sections de la musique ayant des rythmes différents et ne doit pas être radicalement variable.
```

2022-05-06 19:34 UTC, Biokax commented on wiki/Ranking_Criteria/fr.md
> +- Soyez critique à l'égard de ce qu'ils soulignent et ne les suivez pas aveuglément.
```suggestion
- Soyez critique à l'égard de ce qu'ils signalent et ne les suivez pas aveuglément.
```

2022-05-06 19:44 UTC, Ganondorf-1 approved these changes

2022-05-07 17:58 UTC, DoryanR approved these changes

2022-05-07 17:58 UTC, Walavouchey approved these changes

2022-05-07 17:58 UTC, merged