[FR] Update `Play_style`
ppy/osu-wiki pull request #7286
Opened 2022-05-05 11:27 UTC by Biokax

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-05 11:48 UTC, DoryanR approved these changes

2022-05-07 17:04 UTC, Walavouchey requested changes

2022-05-07 17:04 UTC, Walavouchey commented on wiki/Play_style/fr.md
> +Ce style de jeu était considéré comme une blague par la plupart des joueurs jusqu'en mai 2013, lorsque le joueur canadien ![](/wiki/shared/flag/CA.gif "Canada") [Azer](https://osu.ppy.sh/users/215557
the flags should be reference-style links, which needs to be changed in the english article as well

```suggestion
Ce style de jeu était considéré comme une blague par la plupart des joueurs jusqu'en mai 2013, lorsque le joueur canadien ![](/wiki/shared/flag/CA.gif "Canada") [Azer](https://osu.ppy.sh/users/2155578) a commencé à obtenir les meilleurs scores sur des beatmaps très respectées comme [Hatsune Miku - With a Dance Number (val0108)](https://osu.ppy.sh/beatmapsets/29691) et [The Quick Brown Fox - The Big Black (Blue Dragon)](https://osu.ppy.sh/beatmapsets/41823) en jouant avec deux souris.
```

2022-05-07 17:47 UTC, Walavouchey approved these changes

2022-05-07 17:52 UTC, Walavouchey approved these changes

2022-05-07 17:52 UTC, merged