[FR] Update `Game_modifier\Hard_Rock`
ppy/osu-wiki pull request #7294
Opened 2022-05-07 18:00 UTC by DoryanR

Proposal to update the French translation of the wiki page `Game_modifier\Hard_Rock`.

2022-05-07 19:13 UTC, Biokax requested changes

2022-05-07 19:13 UTC, Biokax commented on wiki/Game_modifier/Hard_Rock/fr.md
> +Dans le mode [osu!mania](/wiki/Game_mode/osu!mania), l'HP drain est augmenté de 40% tandis que la timing window sont environ 29% plus strictes. Bien que la valeur AR soit affichée comme augmentée, ce
```suggestion
Dans le mode [osu!mania](/wiki/Game_mode/osu!mania), l'HP drain est augmenté de 40% tandis que la timing window est environ 29% plus strictes. Bien que la valeur AR soit affichée comme augmentée, cela n'affecte pas le gameplay.
```

2022-05-07 19:22 UTC, Ganondorf-1 requested changes

2022-05-07 19:22 UTC, Ganondorf-1 commented on wiki/Game_modifier/Hard_Rock/fr.md
> +Le mod **Hard Rock** est un [modificateur de jeu](/wiki/Game_modifier) qui vise à augmenter la difficulté de la plupart (sinon de tous) les aspects d'une [beatmap](/wiki/Beatmap). Généralement il att
```suggestion
Le mod **Hard Rock** est un [modificateur de jeu](/wiki/Game_modifier) qui vise à augmenter la difficulté de la plupart des aspects d'une [beatmap](/wiki/Beatmap). Il atteint généralement cet objectif en augmentant le [circle size (CS)](/wiki/Beatmap_Editor/Song_Setup#circle-size) de 30%, l'[approach rate (AR)](/wiki/Beatmapping/Approach_rate) de 40%, le [health drain (HP)](/wiki/Beatmapping/Health_drain) de 40% et l'[overall difficulty (OD)](/wiki/Beatmap_Editor/Song_Setup#overall-difficulty) de 40%, bien que les détails varient pour chaque mode de jeu.
```

2022-05-07 19:22 UTC, Ganondorf-1 commented on wiki/Game_modifier/Hard_Rock/fr.md
>  *Avis : L'utilisation de ce mod dans osu!mania entraînera un jeu non classé.*
```suggestion
*Remarque : L'utilisation de ce mod dans le mode de jeu osu!mania ne permet pas de jouer une partie classée.*
```

2022-05-07 19:22 UTC, Ganondorf-1 commented on wiki/Game_modifier/Hard_Rock/fr.md
> +Dans le mode [osu!mania](/wiki/Game_mode/osu!mania), l'HP drain est augmenté de 40% tandis que la timing window sont environ 29% plus strictes. Bien que la valeur AR soit affichée comme augmentée, ce
```suggestion
Dans le mode [osu!mania](/wiki/Game_mode/osu!mania), l'HP drain est augmenté de 40% tandis que la fenêtre de timing est environ 29% plus stricte. Bien que la valeur AR soit affichée comme augmentée, cela n'affecte pas le gameplay.
```

2022-05-07 19:22 UTC, Ganondorf-1 commented on wiki/Game_modifier/Hard_Rock/fr.md
> +Pour calculer la timing window après l'application de HR, la [timing window originale](/wiki/Beatmapping/Overall_difficulty) doit être divisée par 1,4. La timing window du Rainbow 300 (MAX) est fixe,
```suggestion
Pour calculer la fenêtre de timing après l'application du HR, la [fenêtre de timing originale](/wiki/Beatmapping/Overall_difficulty) doit être divisée par 1,4. La fenêtre de timing du Rainbow 300 (MAX) est fixe, quel que soit l'OD, ce qui signifie que la fenêtre de timing d'un MAX avec HR sera toujours de ±11,43 ms.
```

2022-05-08 16:02 UTC, Ganondorf-1 approved these changes

2022-05-09 22:17 UTC, Walavouchey approved these changes

2022-05-09 22:19 UTC, merged