[DE] Add `Tournaments/Official_support`
ppy/osu-wiki pull request #7298
Opened 2022-05-07 20:34 UTC by The-Last-Cookie

As an aside note, this article is not listed in the [wiki language status page](https://clayton.cc/osu-wiki-status/de) under the `missing articles` section. I guess it's hidden, so that not every tournament article is shown, which would otherwise make the list **extremely long**.

Translation notes:
- `screening process` --> `Screening-Verfahren`
    - `Prüfverfahren` may also be possible
- `staff` --> `Personal`/`Mitarbeiter`
    - This might conflict with `osu! staff` because that is translated as `osu!-Belegschaft`. Would be nice getting a second opinion on it.
- `qualifiers` --> `Qualifikationsspiele`/`-runden`
- Not sure about `host` --> `Gastgeber`. I've used this once in line 145.
- Unsure about the difference between `öfter` and `öfters` (line 176). [Here](https://www.korrekturen.de/forum.pl/md/read/id/115096/sbj/oefters-oder-oefter/) is something that I could find on this topic
    - Might need to change the section identifier too
- `judges` --> `Kampfrichter` (line 184)
- `competitive integrity` --> `Wettbewerbsintegrität`. A bit unsure if this conflicts with `contest` --> `Wettbewerb`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-09 22:06 UTC, respektive requested changes

2022-05-10 10:34 UTC, The-Last-Cookie commented
Thank you a lot for the review 👍

2022-05-10 14:18 UTC, respektive submitted a review, later dismissed

2022-05-10 22:03 UTC, cl8n approved these changes

2022-05-10 22:03 UTC, merged

2022-05-11 01:55 UTC, cl8n commented
> As an aside note, this article is not listed in the [wiki language status page](https://clayton.cc/osu-wiki-status/de)

fixed this, it will show official support & countries that participated in osu tournaments now.