[FR] Update `Music_theory\Time_signature`
ppy/osu-wiki pull request #7302
Opened 2022-05-08 09:06 UTC by DoryanR

Proposal to update the French translation of the wiki page `Music_theory\Time_signature`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-08 09:37 UTC, Biokax requested changes

2022-05-08 09:37 UTC, Biokax commented on wiki/Music_theory/Time_signature/fr.md
>    - sheet music
```suggestion
  - sheet music
  - partition
```

2022-05-08 09:37 UTC, Biokax commented on wiki/Music_theory/Time_signature/fr.md
> +Une **signature temporelle** est un terme musical définissant le nombre de [temps](/wiki/Beat) dans une [mesure](/wiki/Music_theory/Measure) d'une musique (le chiffre du haut), et quelle note indique
```suggestion
Une **signature temporelle** est un terme musical définissant le nombre de [temps](/wiki/Beat) dans une [mesure](/wiki/Music_theory/Measure) d'une musique (le chiffre du haut), et quelle note indique un seul temps (le chiffre du bas). Pour une signature temporelle de 4/4 (alias "common time"), 4 notes de 1/4 (*noires* ou *quarts de note*) tiennent dans une mesure, tandis qu'une signature temporelle de 3/4 (alias "valse" ou "trois-quart-de-temps") signifie que 3 notes de 1/4 tiennent dans une mesure.
```

2022-05-08 16:42 UTC, Ganondorf-1 requested changes

2022-05-08 16:42 UTC, Ganondorf-1 commented on wiki/Music_theory/Time_signature/fr.md
> +[l'éditeur d'osu!](/wiki/Client/Beatmap_editor) propose plusieurs signatures temporelles pour le [mapping](/wiki/Beatmapping), qui peuvent être sélectionnées dans le [menu Timing](/wiki/Client/Beatma
```suggestion
L'[éditeur d'osu!](/wiki/Client/Beatmap_editor) propose plusieurs signatures temporelles pour le [mapping](/wiki/Beatmapping), qui peuvent être sélectionnées dans le [menu Timing](/wiki/Client/Beatmap_editor/Timing). Il s'agit notamment de 3/4, 4/4, 5/4, 6/4 et 7/4.
```

2022-05-08 18:06 UTC, DoryanR commented on wiki/Music_theory/Time_signature/fr.md
> +  - partition
```suggestion
```

2022-05-08 18:51 UTC, Ganondorf-1 approved these changes

2022-05-09 22:25 UTC, Walavouchey approved these changes

2022-05-09 22:27 UTC, merged