[FR] Update `Skin_set`
ppy/osu-wiki pull request #7307
Opened 2022-05-09 08:42 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-09 08:53 UTC, DoryanR requested changes

2022-05-09 08:53 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +L'ensemble de ce set de skin est pertinant pour le jeu.
```suggestion
L'ensemble de ce skin set est pertinent pour le gameplay.
```

2022-05-09 08:53 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +| Nom du fichier | Notes | Achèvement du set | Tailles recommandées pour les skins SD |
```suggestion
| Nom du fichier | Notes | Pertinence de l'ajout | Tailles recommandées pour les skins SD |
```

2022-05-09 10:07 UTC, DoryanR approved these changes

2022-05-09 22:21 UTC, Walavouchey commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +### Set des lumières
the setting in-game is translated as "Lueurs de fond"

2022-05-10 07:16 UTC, Biokax commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +### Set des lumières
```suggestion
### Lueurs de fond
```

2022-05-10 08:16 UTC, DoryanR commented on wiki/Ranking_Criteria/Skin_Set_List/fr.md
> +### Lueurs de fond
```suggestion
### Set des lueurs de fond
```

Restons cohérent avec le reste de la page au niveau des titres

2022-05-10 10:03 UTC, DoryanR approved these changes

2022-05-11 15:18 UTC, Walavouchey approved these changes

2022-05-11 17:21 UTC, merged