[FR] Update `Beatmapping\Overall_difficulty`
ppy/osu-wiki pull request #7312
Opened 2022-05-09 16:55 UTC by DoryanR

Proposal to update the French translation of the wiki page `Beatmapping\Overall_difficulty`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [x] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-09 17:39 UTC, Ganondorf-1 requested changes

2022-05-09 17:39 UTC, Ganondorf-1 commented on wiki/Beatmapping/Overall_difficulty/fr.md
> +Par exemple, la fenêtre de hit d'un Great dans osu!taiko à OD 5 est de ±34,5 ms, au lieu des ±35 ms que donne le tableau. Dans osu!mania, la fenêtre de hit d'un MAX est de ±16,5 ms, et non de ±16 ms
```suggestion
Par exemple, la fenêtre de timing d'un Great dans osu!taiko à OD 5 est de ±34,5 ms, au lieu des ±35 ms que donne le tableau. Dans osu!mania, la fenêtre de hit d'un MAX est de ±16,5 ms, et non de ±16 ms comme le suggère le tableau.
```

2022-05-12 12:50 UTC, Biokax approved these changes

2022-05-12 19:40 UTC, Walavouchey approved these changes

2022-05-12 19:42 UTC, merged