[FR] Cleanup `Client\Interface\Chat_console`
ppy/osu-wiki pull request #7318
Opened 2022-05-11 15:26 UTC by DoryanR

Proposal for cleanup the French translation of the wiki page `Client\Interface\Chat_console`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [x] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-11 18:17 UTC, Ganondorf-1 requested changes

2022-05-11 18:17 UTC, Ganondorf-1 commented on wiki/Client/Interface/Chat_console/fr.md
> +Sur la plupart des écrans vous pouvez cliquer sur `F9` ou sur `Online Users` pour afficher la console de tchat étendue. En plus de la console de tchat, le tchat étendu superpose une liste de panneaux
```suggestion
Sur la plupart des écrans, vous pouvez appuyer sur `F9` ou cliquer sur `Online Users` pour afficher la console de tchat étendue. En plus de la console de tchat, le tchat étendu superpose une liste de panneaux dans les deux tiers restants de l'écran, affichant des informations sur les utilisateurs actuellement connectés à osu!.
```

2022-05-11 18:17 UTC, Ganondorf-1 commented on wiki/Client/Interface/Chat_console/fr.md
> +- Cliquez sur un onglet pour trier les panels d'utilisateurs en fonction de cet attribut.
```suggestion
- Cliquez sur un onglet pour trier les panneaux d'utilisateurs en fonction de cet attribut.
```

2022-05-11 18:17 UTC, Ganondorf-1 commented on wiki/Client/Interface/Chat_console/fr.md
> +| ![Le joueur est Afk](img/Chat_Console-Afk.png "Le joueur est Afk") | Noir - Inactif ou éloigné du clavier (away from keyboard) (afk). |
```suggestion
| ![Le joueur est Afk](img/Chat_Console-Afk.png "Le joueur est Afk") | Noir - Inactif (away from keyboard) (afk). |
```

2022-05-11 18:17 UTC, Ganondorf-1 commented on wiki/Client/Interface/Chat_console/fr.md
> +| ![Le joueur est connecté via IRC](img/Chat_Console-IRC.png "Le joueur est connecté via IRC") | Bleu foncé sans contenu - Le joueur n'est pas dans le jeu, mais s'est connecté à un client IRC ou les
```suggestion
| ![Le joueur est connecté via IRC](img/Chat_Console-IRC.png "Le joueur est connecté via IRC") | Bleu foncé sans contenu - Le joueur n'a pas le jeu ouvert, mais s'est connecté à un client IRC ou les statistiques ne sont pas disponibles. |
```

2022-05-11 18:17 UTC, Ganondorf-1 commented on wiki/Client/Interface/Chat_console/fr.md
> +1. `Observer le joueur` : Si l'utilisateur joue une beatmap et que vous l'avez, vous pouvez observer pendant qu'il joue. Votre nom figurera dans sa liste de spectateurs.
```suggestion
1. `Observer le joueur` : Si l'utilisateur joue une beatmap et que vous l'avez, vous pouvez l'observer pendant qu'il joue. Votre nom figurera dans sa liste de spectateurs.
```

2022-05-11 18:17 UTC, Ganondorf-1 commented on wiki/Client/Interface/Chat_console/fr.md
> +4. `Inviter à rejoindre la salle` : (Si vous êtes dans une salle multijoueur) Demandez à l'utilisateur de venir dans votre salle.
```suggestion
4. `Inviter à rejoindre la salle` : (Si vous êtes dans une salle multijoueur) Demande à l'utilisateur de venir dans votre salle.
```

2022-05-11 18:17 UTC, Ganondorf-1 commented on wiki/Client/Interface/Chat_console/fr.md
> +- Les onglets répertorient les salons actuellement disponibles. Il suffit de cliquer sur un onglet pour accéder à ce salon. Cliquez sur le bouton "+" jaune pour afficher une liste de nouveaux salons
```suggestion
- Les onglets répertorient les canaux actuellement disponibles. Il suffit de cliquer sur un onglet pour accéder à ce canal. Cliquez sur le bouton "+" jaune pour afficher une liste de nouveaux canaux à rejoindre.
```

2022-05-12 17:16 UTC, DoryanR commented on wiki/Client/Interface/Chat_console/fr.md
> +| `/reply` ou `/r` | Répondre au dernier message privé reçu. | `/r Connais tu un bon médecin ?` | (Dans l'onglet d'Amigo) \[Commentaires précédents\] John: Je suis malade à la maison. Amigo: Really?
```suggestion
| `/reply` ou `/r` | Répondre au dernier message privé reçu. | `/r Connais tu un bon médecin ?` | (Dans l'onglet d'Amigo) \[Commentaires précédents\] John: Je suis malade à la maison. Amigo: Vraiment ? John: Connais tu un bon médecin ? |
```

2022-05-14 09:24 UTC, Biokax requested changes

2022-05-14 09:24 UTC, Biokax commented on wiki/Client/Interface/Chat_console/fr.md
> +| `/away [message]` | Défini un message d'absence à envoyer aux utilisateurs vous envoyant un message privé. Laissez le champ vide pour annuler. | `/away I am John Smith.` | You have been marked as b
```suggestion
| `/away [message]` | Défini un message d'absence à envoyer aux utilisateurs vous envoyant un message privé. Laissez le champ vide pour annuler. | `/away Je suis John Smith.` | You have been marked as being away: I am John Smith. Quand Amigo /msg John Où es-tu~ ? BanchoBot : Je suis John Smith. |
```

2022-05-14 09:39 UTC, Biokax submitted a review, later dismissed

2022-05-14 17:15 UTC, Walavouchey commented on wiki/Client/Interface/Chat_console/fr.md
> +![Options du panneau de l'utilisateur](img/Chat_Console-Userpaneloptions.jpg "Options du panneau de l'utilisateur")
forgot one line below this image

> Press the number or click the bar to activate:

2022-05-14 17:16 UTC, DoryanR commented on wiki/Client/Interface/Chat_console/fr.md
> +
```suggestion
![Options du panneau de l'utilisateur](img/Chat_Console-Userpaneloptions.jpg "Options du panneau de l'utilisateur")

Appuyez sur le numéro ou cliquez sur la barre pour l'activer :

```

2022-05-14 17:18 UTC, Walavouchey approved these changes

2022-05-14 17:21 UTC, merged