[FR] Convert `chat` > `tchat` across the wiki
ppy/osu-wiki pull request #7319
Opened 2022-05-11 15:43 UTC by DoryanR

Conversion of the term `chat` to `tchat` throughout the wiki for French articles.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-11 16:37 UTC, Walavouchey commented on wiki/Gameplay/Replay/fr.md
> +Il est toujours possible d'accéder à la [console de tchat](/wiki/Client/Interface/Chat_console) (`F8`)/[console de tchat étendue](/wiki/Client/Interface/Chat_console#la-console-de-tchat-étendue) (`F9
you've changed this link but haven't changed the heading in the chat console article

2022-05-11 16:38 UTC, Walavouchey commented on wiki/History_of_osu!/2015/fr.md
> +Les tchat Moderators ont été officiellement fusionnés dans la Global Moderation Team (GMT) le 20 août 2015 [[24,25]][r].
casing?

2022-05-11 16:41 UTC, Walavouchey commented on wiki/Registration/fr.md
> +Si vous avez besoin d’une aide supplémentaire dans le jeu, vous pouvez demander dans le canal [Internet Relay tchat](/wiki/Community/Internet_Relay_Chat) (IRC) `#help` en ouvrant la console de tchat
```suggestion
Si vous avez besoin d’une aide supplémentaire dans le jeu, vous pouvez demander dans le canal [Internet Relay Chat](/wiki/Community/Internet_Relay_Chat) (IRC) `#help` en ouvrant la console de tchat (pressez `F8` ou `F9` en jeu) puis tapez `/join help`. Vous pourrez également poser votre question dans le [sous-forum Help](https://osu.ppy.sh/community/forums/5).
```

2022-05-11 16:50 UTC, Walavouchey commented on wiki/History_of_osu!/2008/fr.md
> +Sans blague, Bancho a été lancé en avril, et avec lui les panneaux d'utilisateurs du [tchat Étendu](/wiki/Client/Interface/Chat_console#la-console-de-tchat-étendue). Les utilisateurs pouvaient mainte
casing? x2

also `Show Chat` isn't even translated in-game

2022-05-11 16:50 UTC, Walavouchey commented on wiki/People/The_Team/Language_Surveillance_Division/fr.md
>  Après une [restructuration du personnel](https://osu.ppy.sh/community/forums/topics/123510) en 2013, la Language Surveillance Division a été rebaptisée **Chat Moderators** et a reçu sa propre liste d
"Chat Moderators" was changed to "tchat Moderators" elsewhere. if you automated this pr, it somehow didn't catch this one

2022-05-11 16:54 UTC, DoryanR commented on wiki/History_of_osu!/2008/fr.md
> +Sans blague, Bancho a été lancé en avril, et avec lui les panneaux d'utilisateurs du [tchat Étendu](/wiki/Client/Interface/Chat_console#la-console-de-tchat-étendue). Les utilisateurs pouvaient mainte
```suggestion
Sans blague, Bancho a été lancé en avril, et avec lui les panneaux d'utilisateurs du [Tchat étendu](/wiki/Client/Interface/Chat_console#la-console-de-tchat-étendue). Les utilisateurs pouvaient maintenant voir ce que les autres utilisateurs faisaient dans leurs panneaux d'utilisateur, et pouvaient également interagir avec eux en cliquant pour les observer. Le système d'envoi de rapports d'erreurs automatique a été ajouté, la compatibilité xfire a été implémentée, et le menu principal et l'interface de l'éditeur ont reçu un relooking (avec les nouvelles icônes par [LuigiHann](https://osu.ppy.sh/users/1079)). L'interface de la console de tchat a vu l'ajout du bouton `Afficher le tchat`, l'onglet `tab completion`, et les alertes de mentions de pseudos. L'écran des scores montrait maintenant le nombre de points requis pour atteindre le prochain rang.
```

2022-05-11 16:54 UTC, DoryanR commented on wiki/History_of_osu!/2015/fr.md
> +Les tchat Moderators ont été officiellement fusionnés dans la Global Moderation Team (GMT) le 20 août 2015 [[24,25]][r].
```suggestion
Les Chat Moderators ont été officiellement fusionnés dans la Global Moderation Team (GMT) le 20 août 2015 [[24,25]][r].
```

2022-05-11 16:54 UTC, DoryanR commented on wiki/People/The_Team/Language_Surveillance_Division/fr.md
> +![](img/chat-moderator-profile.png "Page de profil d'un tchat moderator en 2013")
```suggestion
![](img/chat-moderator-profile.png "Page de profil d'un Chat moderator en 2013")
```

2022-05-11 17:25 UTC, DoryanR commented on wiki/People/The_Team/Language_Surveillance_Division/fr.md
> +![](img/chat-moderator-profile.png "Page de profil d'un Chat moderator en 2013")
```suggestion
![](img/chat-moderator-profile.png "Page de profil d'un chat moderator en 2013")
```

2022-05-12 15:34 UTC, Ganondorf-1 commented on wiki/Client/Options/Keyboard_bindings/fr.md
> +| Toggle tchat | `F8` |
```suggestion
| Toggle Chat | `F8` |
```

2022-05-12 15:35 UTC, Ganondorf-1 commented on wiki/Gameplay/Spectating/fr.md
> +**Spectateur** (abrégé en "spec") est un terme utilisé pour décrire le fait de regarder un autre joueur jouer une [beatmap](/wiki/Beatmap) en temps réel (avec un délai d'environ 500ms). Pour observer
```suggestion
**Spectateur** (abrégé en "spec") est un terme utilisé pour décrire le fait de regarder un autre joueur jouer une [beatmap](/wiki/Beatmap) en temps réel (avec un délai d'environ 500ms). Pour observer, ouvrez le tchat étendu et cliquez sur un panneau utilisateur gris.
```

2022-05-14 09:18 UTC, Biokax requested changes

2022-05-14 09:18 UTC, Biokax commented on wiki/Article_styling_criteria/Writing/fr.md
> +- `osu! tchat`
```suggestion
- `osu! tchat`
- `osu! chat`
```

2022-05-14 09:18 UTC, Biokax commented on wiki/Article_styling_criteria/Writing/fr.md
> +- `osu! tchat`
garder le tag en anglais comme toujours

2022-05-14 09:39 UTC, Biokax approved these changes

2022-05-14 17:09 UTC, Walavouchey approved these changes

2022-05-14 17:11 UTC, merged