[FR] Add `Countries_that_participated_in_osu!_tournaments`
ppy/osu-wiki pull request #7323
Opened 2022-05-12 12:01 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-12 15:57 UTC, Ganondorf-1 requested changes

2022-05-12 15:57 UTC, Ganondorf-1 commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +| 5 | ![][flag_TW] Taiwan | 1 | 1 | 1 |
```suggestion
| 5 | ![][flag_TW] Taïwan | 1 | 1 | 1 |
```

2022-05-12 15:57 UTC, Ganondorf-1 commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +| ![][flag_TW] Taiwan | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] |
```suggestion
| ![][flag_TW] Taïwan | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] | ![][true] |
```

2022-05-12 15:57 UTC, Ganondorf-1 commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +[flag_TW]: /wiki/shared/flag/TW.gif "Taiwan"
```suggestion
[flag_TW]: /wiki/shared/flag/TW.gif "Taïwan"
```

2022-05-12 15:57 UTC, Ganondorf-1 commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +### ![][osu!] osu! World Cup
À partir d'ici, il serait pratique d'avoir les listes des pays triées par ordre alphabétique

2022-05-12 16:34 UTC, DoryanR commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +### ![][osu!] classement osu!
```suggestion
### ![][osu!] Classement osu!
```

2022-05-12 16:34 UTC, DoryanR commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +### ![][osu!taiko] classement osu!taiko
```suggestion
### ![][osu!taiko] Classement osu!taiko
```

2022-05-12 16:34 UTC, DoryanR commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +### ![][osu!catch] classement osu!catch
```suggestion
### ![][osu!catch] Classement osu!catch
```

2022-05-13 04:43 UTC, DoryanR requested changes

2022-05-13 04:43 UTC, DoryanR commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/fr.md
> +Cet article établit une liste de pays ayant déjà participé dans des tournois officiels [osu!](/wiki/Game_mode/osu!), [osu!taiko](/wiki/Game_mode/osu!taiko), [osu!catch](/wiki/Game_mode/osu!catch), et
```suggestion
Cet article établit une liste de pays ayant déjà participé dans des tournois officiels des modes [osu!](/wiki/Game_mode/osu!), [osu!taiko](/wiki/Game_mode/osu!taiko), [osu!catch](/wiki/Game_mode/osu!catch), et [osu!mania](/wiki/Game_mode/osu!mania). Il fournit également le classement des équipes ayant atteint le top 3.
```

2022-05-13 07:53 UTC, DoryanR approved these changes

2022-05-14 08:29 UTC, Walavouchey approved these changes

2022-05-14 08:31 UTC, merged