[FR] Add `Tournaments\Official_support`
ppy/osu-wiki pull request #7333
Opened 2022-05-14 14:37 UTC by DoryanR

Proposal to add the French translation of the wiki page `Tournaments\Official_support`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-19 13:00 UTC, Ganondorf-1 requested changes

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +L'équipe [d'osu!](/wiki/People/The_Team) gère un programme dans le cadre duquel elle peut choisir de fournir un support supplémentaire aux tournois gérés par la communauté qui respectent un certain n
```suggestion
L'[équipe d'osu!](/wiki/People/The_Team) gère un programme dans le cadre duquel elle peut choisir de fournir un support supplémentaire aux tournois gérés par la communauté qui respectent un certain nombre de critères et d'attentes, à sa discrétion.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +- Toutes les personnes inscrites doivent être contrôlées par l'équipe d'assistance aux comptes avant le début du jeu**²**. Voir [screening du tournoi](#tournament-screening) pour plus de détails.
```suggestion
- Tous les joueurs inscrits doivent être contrôlés par l'équipe de support aux comptes avant le début du tournoi**²**. Voir [screening du tournoi](#tournament-screening) pour plus de détails.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +- Si un utilisateur satisfait aux critères d'inscription (s'il y en a), le tournoi ne doit pas empêcher ceux qui passent l'examen de participer sans que de nombreuses preuves soient présentées publiq
```suggestion
- Si un utilisateur répond aux critères d'inscription (s'il y en a), le tournoi ne doit pas empêcher ceux qui passent le screening de participer sans que de nombreuses preuves soient présentées publiquement contre eux et sans l'approbation de l'équipe de support aux comptes.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +- Un arbitre dédié doit être présent lors de chaque match. Les joueurs ne peuvent pas "s'auto-arbitrer".
```suggestion
- Un arbitre dédié doit être présent lors de chaque match. Les joueurs ne peuvent pas s'auto-arbitrer.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Les utilisateurs sous le coup d'un ban des tournois active sont censés révéler leur statut de ban de tournoi à tout tournoi supporté officiellement auquel ils ont l'intention de participer. Ils peuve
```suggestion
Les utilisateurs sous le coup d'un ban des tournois active sont censés révéler leur statut de ban de tournoi à tout tournoi supporté officiellement auquel ils ont l'intention de participer. Ils peuvent être engagés en tant qu'[assistants](#what-is-considered-staff) à la discrétion de l'hôte, mais nous encourageons une réflexion approfondie sur de tels choix car ces individus ont déjà enfreint les règles une fois (ou plus). Ils ne peuvent pas agir en tant que [staff](#what-is-considered-staff) À MOINS que l'hôte ne demande une exemption pour eux lorsqu'il envoie sa demande initiale de support. L'équipe de support aux comptes évaluera ensuite ces demandes au cas par cas en tenant compte de l'historique de l'utilisateur.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +À la discrétion de l'équipe d'assistance aux comptes, les joueurs fautifs peuvent se voir imposer un ban des tournois temporaire ou permanente en fonction de la gravité de leur comportement. Les réci
```suggestion
À la discrétion de l'équipe de support aux comptes, les joueurs fautifs peuvent se voir imposer un ban des tournois temporaire ou permanent en fonction de la gravité de leur comportement. Les récidivistes risquent de se voir infliger un ban des tournois permanent ou une restriction.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +### Projection du tournoi
```suggestion
### Screening du tournoi
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +L'accès au processus de filtrage constitue une part importante du support officiel d'un tournoi. Semblable aux "contrôles de sécurité" auxquels sont soumis tous les joueurs de la World Cup, le filtra
```suggestion
L'accès au processus de screening constitue une part importante du support officiel d'un tournoi. Semblable aux "contrôles de sécurité" auxquels sont soumis tous les joueurs de la World Cup, le screening permet d'éviter que des utilisateurs ayant récemment commis de graves infractions ou ayant été bannis des tournois ne perturbent le tournoi.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Une fois la sélection terminée, l'équipe d'assistance aux comptes fournira une liste de tous les utilisateurs qui ont échoué à la sélection et qui ne sont pas considérés comme éligibles pour le tourn
```suggestion
Une fois le screening terminé, l'équipe de support aux comptes fournira une liste de tous les utilisateurs qui n'ont pas passé le screening et qui ne sont pas considérés comme éligibles pour le tournoi, sans fournir de raison spécifique. Les utilisateurs qui ne sont pas satisfaits du résultat du screening doivent être invités à consulter [accounts@ppy.sh](mailto:accounts@ppy.sh) par e-mail.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +**Le fait d'autoriser des utilisateurs qui n'ont pas réussi à passer les contrôles à participer à votre tournoi entraînera le retrait immédiat du support et le refus de toute demande d'assistance ult
```suggestion
**Le fait d'autoriser des utilisateurs qui n'ont pas réussi à passer le screening à participer à votre tournoi entraînera le retrait immédiat du support et le refus de toute demande de support ultérieure.**
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Les tournois bénéficiant d'un support officiel qui répondent aux [attentes ci-dessus](#attentes) peuvent demander des badges de profil après leur achèvement. **Les badges ne seront jamais approuvés a
```suggestion
Les tournois bénéficiant d'un support officiel qui répondent aux [attentes ci-dessus](#attentes) peuvent demander des badges de profil une fois terminés. **Les badges ne seront jamais approuvés avant la fin du tournoi.**
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Les tournois communautaires de longue durée peuvent bénéficier d'une bannière dans le menu principal du jeu. C'est à l'équipe d'osu! de décider si votre tournoi peut être annoncé dans le jeu, car il
```suggestion
Les tournois communautaires de longue durée peuvent bénéficier d'une bannière dans le menu principal du jeu. C'est à l'équipe d'osu! de décider si votre tournoi peut recevoir une publicité en jeu, car il y a de nombreux facteurs à prendre en compte. Les conditions minimales pour demander une publicité en jeu sont les suivantes :
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +### Qu'est-ce qui est considéré comme du "personnel" en ce qui concerne la gestion des tournois ? {#ce-qui-est-considéré-personnel}
```suggestion
### Qu'est-ce qui est considéré comme du "staff" en ce qui concerne la gestion des tournois ? {#ce-qui-est-considéré-staff}
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Si un utilisateur a accès à des informations qui pourraient influencer le résultat du tournoi/concours, il est considéré comme faisant partie du personnel. Pour clarifier, nous considérons que les or
```suggestion
Si un utilisateur a accès à des informations qui pourraient influencer le résultat du tournoi/concours, il est considéré comme faisant partie du staff. Pour clarifier, nous considérons que les organisateurs, les arbitres, les sélectionneurs de mappools, les testeurs de mappools, les créateurs de beatmaps sur mesure, les juges, ou toute autre forme de poste de direction directement impliqué dans la maintenance et le fonctionnement du tournoi/concours font partie de son staff. Cette liste n'est pas exhaustive - si vous avez des doutes, veuillez contacter [tournaments@ppy.sh](mailto:tournaments@ppy.sh).
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Les commentateurs, les streamers et les graphistes sont désignés comme des **aides** et peuvent participer librement aux tournois/concours pour autant qu'ils ne soient pas directement impliqués dans
```suggestion
Les commentateurs, les streamers et les graphistes sont désignés comme des **assistants** et peuvent participer librement aux tournois/concours pour autant qu'ils ne soient pas directement impliqués dans un aspect organisationnel du tournoi/concours.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Nous avons connu des cas où des organisateurs peu scrupuleux ont organisé des tournois de manière spécifique (c'est-à-dire en choisissant des cartes qu'ils connaissent bien, en ajustant les têtes de
```suggestion
Nous avons connu des cas où des organisateurs peu scrupuleux ont organisé des tournois de manière spécifique (c'est-à-dire en choisissant des beatmaps qu'ils connaissent bien, en ajustant les seedings/brackets, etc.) afin de récolter des badges de profil pour eux-mêmes et leurs amis.) Bien que nous comprenions que la plupart des groupes n'agissent pas de la sorte, nous devons appliquer cette restriction pour que les choses restent équitables pour tous.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +### Un joueur qui a été éliminé du jeu dans mon tournoi peut-il rejoindre le staff après coup et ne pas causer de problèmes ? {#joueur-membre-du-personnel}
```suggestion
### Un joueur qui a été éliminé de mon tournoi peut-il rejoindre le staff après coup et ne pas causer de problèmes ? {#joueur-membre-du-staff}
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Non. Les joueurs qui ont été éliminés du tournoi/concours ne peuvent pas être recrutés en tant que personnel ou aider à l'organisation, à la seule exception de la mise en place de replays pour les sh
```suggestion
Non. Les joueurs qui ont été éliminés du tournoi/concours ne peuvent pas être recrutés en tant que staff ou aider à l'organisation, à la seule exception de la mise en place de replays pour les showcases mappool. Ils peuvent toutefois être recrutés en tant qu'assistants.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Une personne inscrite qui a passé la sélection mais qui n'a été programmée pour aucun match **ET** qui n'a participé à aucune partie (y compris les qualifications) n'est pas encore considérée comme u
```suggestion
Un joueur inscrit qui a passé le screening mais qui n'a été programmé pour aucun match **ET** qui n'a participé à aucune partie (y compris les qualifications) n'est pas encore considéré comme un joueur/participant du tournoi, et peut donc encore être enrôlé comme staff.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +### Si un utilisateur n'a pas encore joué de match, peut-il rejoindre le staff ? {#pas-de-participation-personnel}
```suggestion
### Si un utilisateur n'a pas encore joué de match, peut-il rejoindre le staff ? {#pas-de-participation-staff}
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +### Que dois-je faire si un joueur de mon tournoi est restreint ? {#restriction-des-joueurs}
```suggestion
### Que dois-je faire si un joueur de mon tournoi se fait restreindre ? {#restriction-des-joueurs}
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Dans l'éventualité peu probable qu'un joueur soit restreint au cours du tournoi, il se peut que vous deviez rejouer certains matchs dans lesquels il était impliqué afin de préserver l'intégrité compé
```suggestion
Dans l'éventualité peu probable qu'un joueur soit restreint au cours du tournoi, il se peut que vous deviez rejouer certains matchs dans lesquels il était impliqué afin de préserver l'intégrité compétitive du tournoi. Les organisateurs de tournois doivent contacter l'équipe de support aux comptes pour recevoir des informations et des conseils sur ces cas (rares, espérons-le).
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Inonder le jeu de badges de profil dilue le prestige du prix pour tous les autres. Nous ne voulons pas que les badges de profil soient quelque chose que les gens "récoltent" dans quelques séries de t
```suggestion
Inonder le jeu de badges de profil dilue le prestige du prix pour tous les autres. Nous ne voulons pas que les badges de profil soient quelque chose que les gens "farment" dans quelques séries de tournois réguliers et récurrents.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Pour les concours de beatmap, oui, il suffit de suivre les mêmes règles que ci-dessus. Nous vous recommandons vivement d'utiliser le programme [Featured Artists](https://osu.ppy.sh/beatmaps/artists)
```suggestion
Pour les concours de beatmaps, oui, il suffit de suivre les mêmes règles que ci-dessus. Nous vous recommandons vivement d'utiliser les musiques des [Featured Artists](https://osu.ppy.sh/beatmaps/artists) pour ces concours et nous accorderons de manière flagrante un traitement préférentiel à ceux qui le font.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Pour les autres concours, envoyez-nous un courriel et demandez personnellement. Nous essaierons de trouver une solution.
```suggestion
Pour les autres concours, envoyez-nous un e-mail et demandez personnellement. Nous essaierons de trouver une solution.
```

2022-05-19 13:00 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Cet article a été mis à jour le 9 janvier 2022. Pour toute question ou clarification, veuillez consulter le canal `#tournaments` sur le serveur Discord [osu!dev](https://discord.com/invite/ppy) ou en
```suggestion
Cet article a été mis à jour le 9 janvier 2022. Pour toute question ou clarification, veuillez consulter le canal `#tournaments` sur le serveur Discord [osu!dev](https://discord.com/invite/ppy) ou envoyer un e-mail à [tournaments@ppy.sh](mailto:tournaments@ppy.sh).
```

2022-05-24 18:18 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Non. Les joueurs qui ont été éliminés du tournoi/concours ne peuvent pas être recrutés en tant que staff ou aider à l'organisation, à la seule exception de la mise en place de replays pour les showca
```suggestion
Non. Les joueurs qui ont été éliminés du tournoi/concours ne peuvent pas être recrutés en tant que staff ou aider à l'organisation, à la seule exception de la mise en place de replays pour les showcases de mappool. Ils peuvent toutefois être recrutés en tant qu'assistants.
```

2022-05-25 11:47 UTC, Biokax approved these changes

2022-05-25 11:56 UTC, Walavouchey commented on wiki/Tournaments/Official_support/fr.md
> +User3,1234567
```suggestion
Utilisateur1,1234567
Utilisateur2,1234567
Utilisateur3,1234567
```

2022-05-25 11:56 UTC, Walavouchey commented on wiki/Tournaments/Official_support/fr.md
> +User4,Team2,1234567
```suggestion
Utiliateur1,Équipe1,1234567
Utiliateur2,Équipe1,1234567
Utiliateur3,Équipe2,1234567
Utiliateur4,Équipe2,1234567
```

2022-05-25 15:11 UTC, Walavouchey approved these changes

2022-05-25 15:33 UTC, merged