[FR] Update `Storyboard\Scripting`
ppy/osu-wiki pull request #7335
Opened 2022-05-14 15:06 UTC by DoryanR

Proposal to update the French translation of the wiki page `Storyboard\Scripting`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-14 15:11 UTC, DoryanR commented on wiki/Storyboard/Scripting/fr.md
> +Le script est une alternative courante à [l'éditeur de storyboard du client](/wiki/Client/Beatmap_editor/Design) lorsque la précision ou la complexité sont requises. Avec un éditeur de texte tel que
```suggestion
Le script est une alternative courante à [l'éditeur de storyboard du client](/wiki/Client/Beatmap_editor/Design) lorsque la précision ou la complexité sont requises. Avec un éditeur de texte tel que [Notepad](https://fr.wikipedia.org/wiki/Bloc-notes_(Windows) "\"Windows Notepad\" sur Wikipédia"), [Notepad++](https://www.notepad-plus-plus.org/) ou [Visual Studio Code](https://code.visualstudio.com/), les storyboarders peuvent modifier les valeurs exactes des [objets](Objects) et des [commandes](Commands) au lieu d'utiliser les contrôles à l'écran. De nombreux scénaristes utilisent également la [programmation](https://fr.wikipedia.org/wiki/Programmation_informatique "\"Programmation informatique\" sur Wikipédia") pour créer des fichiers de scénarimage qui seraient difficiles à créer manuellement.
```

2022-05-15 19:50 UTC, Ganondorf-1 requested changes

2022-05-15 19:50 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/fr.md
> +Le script est une alternative courante à [l'éditeur de storyboard du client](/wiki/Client/Beatmap_editor/Design) lorsque la précision ou la complexité sont requises. Avec un éditeur de texte tel que
```suggestion
Le scripting est une alternative courante à [l'éditeur de storyboard du client](/wiki/Client/Beatmap_editor/Design) lorsque la précision ou la complexité sont requises. Avec un éditeur de texte tel que [Notepad](https://fr.wikipedia.org/wiki/Bloc-notes_(Windows) "\"Windows Notepad\" sur Wikipédia"), [Notepad++](https://www.notepad-plus-plus.org/) ou [Visual Studio Code](https://code.visualstudio.com/), les storyboarders peuvent modifier les valeurs exactes des [objets](Objects) et des [commandes](Commands) au lieu d'utiliser les contrôles à l'écran. De nombreux storyboarders utilisent également la [programmation](https://fr.wikipedia.org/wiki/Programmation_informatique "\"Programmation informatique\" sur Wikipédia") pour créer des fichiers de storyboard qui seraient difficiles à créer manuellement.
```

2022-05-15 19:50 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/fr.md
>  # Scénarisation d'un storyboard
```suggestion
# Scripting des storyboards
```

2022-05-15 19:50 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/fr.md
> +**La scénarisation d'un storyboard** est le processus d'édition des [storyboards](/wiki/Storyboard) d'osu! via leurs fichiers [`.osb`](/wiki/Client/File_formats/Osb_(file_format)) et [`.osu`](/wiki/C
```suggestion
**Le scripting des storyboards** est le processus d'édition des [storyboards](/wiki/Storyboard) d'osu! via leurs fichiers [`.osb`](/wiki/Client/File_formats/Osb_(file_format)) et [`.osu`](/wiki/Client/File_formats/Osu_(file_format)). Ces fichiers définissent les images et les effets que le [client](/wiki/Client) rend dans les animations de fond pendant la partie.
```

2022-05-15 19:50 UTC, Ganondorf-1 commented on wiki/Storyboard/Scripting/fr.md
> +Divers outils ont été créés par la communauté pour abstraire et développer la scénarisation d'un storyboard, comme le [storybrew](https://github.com/Damnae/storybrew "GitHub repository") de ![][flag_
```suggestion
Divers outils ont été créés par la communauté pour abstraire et développer le scripting des storyboards, comme [storybrew](https://github.com/Damnae/storybrew "GitHub repository") par ![][flag_FR] [Damnae](https://osu.ppy.sh/users/989377).
```

2022-05-17 11:25 UTC, Biokax approved these changes

2022-05-21 00:00 UTC, Walavouchey approved these changes

2022-05-21 00:02 UTC, merged