[FR] Add `Community\osu!_Talk_Event\Overcoming_Obstacles`
ppy/osu-wiki pull request #7389
Opened 2022-05-26 09:41 UTC by DoryanR

Proposal to add the French translation of the wiki page `Community\osu!_Talk_Event\Overcoming_Obstacles`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-26 09:44 UTC, DoryanR commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +## Links
```suggestion
## Liens
```

2022-05-26 09:48 UTC, Walavouchey commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +Les conférences ont également été diffusées en direct sur [la chaîne Twitch de l'Université d'Ossétie du Sud](https://twitch.tv/osuuniversity) et des enregistrements de chaque conférence sont disponi
> l'Université d'Ossétie du Sud

?

2022-05-26 09:50 UTC, DoryanR commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +Les conférences ont également été diffusées en direct sur [la chaîne Twitch de l'Université d'Ossétie du Sud](https://twitch.tv/osuuniversity) et des enregistrements de chaque conférence sont disponi
```suggestion
Les conférences ont également été diffusées en direct sur [la chaîne Twitch de osu! University](https://twitch.tv/osuuniversity) et des enregistrements de chaque conférence sont disponibles sur [la chaîne YouTube de osu! University](https://www.youtube.com/c/osuuniversity).
```

2022-05-26 09:58 UTC, Walavouchey commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- Les histoires partagées ne doivent pas nécessairement concerner l'université d'Ottawa, mais comme il s'agit d'un événement lié à l'université, il est recommandé aux speakers d'essayer de relier leu
here too

2022-05-26 11:21 UTC, DoryanR commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- Les histoires partagées ne doivent pas nécessairement concerner l'université d'Ottawa, mais comme il s'agit d'un événement lié à l'université, il est recommandé aux speakers d'essayer de relier leu
```suggestion
- Les histoires partagées ne doivent pas nécessairement concerner osu! University, mais comme il s'agit d'un événement lié à l'université, il est recommandé aux speakers d'essayer de relier leur histoire ou la leçon qu'elle contient à l'université d'Ottawa d'une manière ou d'une autre.
```

2022-05-26 11:32 UTC, Walavouchey commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- Les histoires partagées ne doivent pas nécessairement concerner osu! University, mais comme il s'agit d'un événement lié à l'université, il est recommandé aux speakers d'essayer de relier leur hist
```suggestion
- Les histoires partagées ne doivent pas nécessairement concerner osu!, mais comme il s'agit d'un événement lié à osu!, il est recommandé aux speakers d'essayer de relier leur histoire ou la leçon qu'elle contient à osu! d'une manière ou d'une autre.
```

2022-05-26 11:33 UTC, Walavouchey commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- Les histoires partagées ne doivent pas nécessairement concerner osu! University, mais comme il s'agit d'un événement lié à l'université, il est recommandé aux speakers d'essayer de relier leur hist
where did these even come from... ?

2022-05-26 19:25 UTC, Ganondorf-1 requested changes

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +Les intervenants ont tenu leurs discours dans un salon Stage sur le [serveur Discord osu!dev](/wiki/Community/osu!dev_Discord_server). Pendant l'événement, des salons de discussion ont été ouverts da
```suggestion
Les intervenants ont tenu leurs discours dans un salon Étape sur le [serveur Discord osu!dev](/wiki/Community/osu!dev_Discord_server). Pendant l'événement, des fils de discussion ont été ouverts dans le salon `#community-meetings` pour en discuter.
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +Pour participer en tant que speaker à une prochaine itération de l'événement, ou recommander quelqu'un qui serait apte à donner une conférence, remplissez le [formulaire de nomination d'un speaker](h
```suggestion
Pour participer en tant qu'intervenant à une prochaine itération de l'événement, ou recommander quelqu'un qui serait apte à donner une conférence, remplissez le [formulaire de nomination des intervenants](https://forms.gle/HCD6ac8JwURGh8zx8).
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- **Le speaker utilisera le salon Scène Discord** dans le [serveur Discord osu!dev](https://discord.gg/ppy) pour faire leur exposé.
```suggestion
- **L'intervenant utilisera le salon Étape de Discord** dans le [serveur Discord osu!dev](https://discord.gg/ppy) pour faire leur conférence.
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- **Les interventions dureront moins de 18 minutes.** Il s'agit de la durée maximale autorisée, et non d'un objectif à atteindre - même un exposé de trois minutes peut avoir un impact considérable.
```suggestion
- **Les conférences dureront moins de 18 minutes.** Il s'agit de la durée maximale autorisée, et non d'un objectif à atteindre - même une conférence de trois minutes peut avoir un impact considérable.
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- Les histoires partagées ne doivent pas nécessairement concerner osu!, mais comme il s'agit d'un événement lié à osu!, il est recommandé aux speakers d'essayer de relier leur histoire ou la leçon qu
```suggestion
- Les histoires partagées ne doivent pas nécessairement concerner osu!, mais comme il s'agit d'un événement lié à osu!, il est recommandé aux intervenants d'essayer de relier leur histoire ou la leçon qu'elle contient à osu! d'une manière ou d'une autre.
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +- [Chaîne YouTube de osu! University](https://www.youtube.com/c/osuuniversity)
```suggestion
- [Chaîne YouTube d'osu! University](https://www.youtube.com/c/osuuniversity)
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +
```suggestion
- [Formulaire de nomination des intervenants](https://forms.gle/HCD6ac8JwURGh8zx8)
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +| Heure (UTC) | Speaker | Titre | Vidéo |
```suggestion
| Heure (UTC) | Intervenant | Titre | Vidéo |
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +| Heure (UTC) | Speaker | Titre | Vidéo |
```suggestion
| Heure (UTC) | Intervenant | Titre | Vidéo |
```

2022-05-26 19:25 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +| Heure (UTC) | Speaker | Titre | Vidéo |
```suggestion
| Heure (UTC) | Intervenant | Titre | Vidéo |
```

2022-05-27 08:17 UTC, DoryanR commented on wiki/Community/osu!_Talk_Event/Overcoming_Obstacles/fr.md
> +## Programme
```suggestion
- [Formulaire de nomination des intervenants](https://forms.gle/HCD6ac8JwURGh8zx8)

## Programme
```

2022-05-31 08:00 UTC, Biokax approved these changes

2022-06-04 01:50 UTC, cl8n approved these changes

2022-06-04 01:51 UTC, merged