[FR] Add `Community\osu!_Talk_Event`
ppy/osu-wiki pull request #7390
Opened 2022-05-26 09:46 UTC by DoryanR

Proposal to add the French translation of the wiki page `Community\osu!_Talk_Event`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-05-26 09:51 UTC, DoryanR commented on wiki/Community/osu!_Talk_Event/fr.md
> +Les conférences sont également diffusées en continu sur [la chaîne Twitch de l'Université d'Ossétie du Sud](https://twitch.tv/osuuniversity) et des enregistrements de chaque conférence sont disponibl
```suggestion
Les conférences sont également diffusées en continu sur [la chaîne Twitch de osu! University](https://twitch.tv/osuuniversity) et des enregistrements de chaque conférence sont disponibles sur [la chaîne YouTube de osu! University](https://www.youtube.com/c/osuuniversity).
```

2022-05-26 19:30 UTC, Ganondorf-1 requested changes

2022-05-26 19:30 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/fr.md
> +Pour participer en tant que speaker à l'une de ces conférences, ou recommander quelqu'un qui serait apte à donner une conférence, remplissez le [formulaire de nomination d'un speaker](https://forms.g
```suggestion
Pour participer en tant qu'intervenant à l'une de ces conférences, ou recommander quelqu'un qui serait apte à donner une conférence, remplissez le [formulaire de nomination des intervenants](https://forms.gle/HCD6ac8JwURGh8zx8).
```

2022-05-26 19:30 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/fr.md
> +- [Chaîne YouTube osu! University](https://www.youtube.com/c/osuuniversity)
```suggestion
- [Chaîne YouTube d'osu! University](https://www.youtube.com/c/osuuniversity)
```

2022-05-26 19:30 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/fr.md
> +- [Chaîne Twitch osu! University](https://twitch.tv/osuuniversity)
```suggestion
- [Chaîne Twitch d'osu! University](https://twitch.tv/osuuniversity)
```

2022-05-26 19:30 UTC, Ganondorf-1 commented on wiki/Community/osu!_Talk_Event/fr.md
> +![Bannière de osu! Talk](img/banner.png)
```suggestion
![Bannière de de l'osu! Talk](img/banner.png)
```

2022-05-31 07:54 UTC, Biokax approved these changes

2022-06-04 02:17 UTC, cl8n approved these changes

2022-06-04 02:18 UTC, merged