[FR] Add `Beatmap_Spotlights/Seasons/2022_Spring`
ppy/osu-wiki pull request #7420
Opened 2022-06-01 11:40 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] Update from https://github.com/ppy/osu-wiki/pull/7454
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-02 18:26 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Début de la saison | 22 Mai 2022 |
```suggestion
| Début de la saison | 22 mai 2022 |
```

2022-06-02 18:27 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Playlist lobby : Playlist B | 5 Juin 5 - 19 Juin 2022 |
```suggestion
| Playlist lobby : Playlist B | 5 juin - 19 juin 2022 |
```

2022-06-02 18:28 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Playlist lobby : Playlist A | 3 Juillet - 10 Juillet 2022 |
```suggestion
| Playlist lobby : Playlist A | 3 juillet - 10 juillet 2022 |
```

2022-06-02 18:28 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Playlist lobby : Playlist B | 10 Juillet - 17 Juillet 2022 |
```suggestion
| Playlist lobby : Playlist B | 10 juillet - 17 juillet 2022 |
```

2022-06-02 18:28 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Playlist lobby : Playlist C | 17 Juillet - 24 Juillet 2022 |
```suggestion
| Playlist lobby : Playlist C | 17 juillet - 24 juillet 2022 |
```

2022-06-02 18:28 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Conclusion de la saison | 24 Juillet 2022 |
```suggestion
| Conclusion de la saison | 24 juillet 2022 |
```

2022-06-04 17:57 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Événement | Temps |
Si c'est comme ça sur les autres articles on les changera, je trouve ça quand même mieux de parler de dates plutôt que de "temps" quand il s'agit... bah, de dates

2022-06-04 19:24 UTC, DoryanR commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +| Événement | Temps |
Ouais bizarre ça, je vais m'occuper de faire la modif quand la PR sera merge si personne n'est dessus

2022-06-04 19:27 UTC, DoryanR requested changes

2022-06-04 19:27 UTC, DoryanR commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +2. Chaque lobby playlist fournit une playlist de beatmaps prédéfinies.
```suggestion
2. Chaque playlist lobby fournit une playlist de beatmaps prédéfinies.
```

2022-06-04 19:27 UTC, DoryanR commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +   - Le score individuel d'une beatmap est basé sur le système de score du client osu! (lazer).
```suggestion
   - Le score individuel d'une beatmap est basé sur le système de score du client osu!(lazer).
```

2022-06-05 09:09 UTC, Biokax commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +2. Chaque lobby playlist fournit une playlist de beatmaps prédéfinies.
hmmm, j'hésite vraiment sur celui là

2022-06-05 16:11 UTC, DoryanR commented
Just a note to say that it will be necessary to update the PR in relation to #7454.

2022-06-07 10:14 UTC, DoryanR commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +- [Annabel - little voice (Niva) \[Niva's Hard\]](https://osu.ppy.sh/beatmapsets/1619033#osu/3343181), suggested by [Nowaie](https://osu.ppy.sh/users/5428909)
```suggestion
- [Annabel - little voice (Niva) \[Niva's Hard\]](https://osu.ppy.sh/beatmapsets/1619033#osu/3343181), suggested by [Nowaie](https://osu.ppy.sh/users/5428909)
```

Tu n'a pas traduit les textes lors de l'update

2022-06-07 11:08 UTC, Biokax commented on wiki/Beatmap_Spotlights/Seasons/2022_Spring/fr.md
> +- [Annabel - little voice (Niva) \[Niva's Hard\]](https://osu.ppy.sh/beatmapsets/1619033#osu/3343181), suggested by [Nowaie](https://osu.ppy.sh/users/5428909)
j'ai oublié de ctrl s ptdr

2022-06-07 15:13 UTC, DoryanR approved these changes

2022-06-08 15:07 UTC, Walavouchey approved these changes

2022-06-08 15:13 UTC, merged