[FR] Update  `People/The_Team/Beatmap_Nominators/Rules`
ppy/osu-wiki pull request #7421
Opened 2022-06-01 11:56 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-02 18:49 UTC, Ganondorf-1 requested changes

2022-06-02 18:49 UTC, Ganondorf-1 commented on wiki/People/The_Team/Beatmap_Nominators/Rules/fr.md
> +- Les Beatmap Nominators doivent rester en dessous d'un nombre maximum de nominations dans une période de 90 jours, avec pour chaque mode de jeu sa propre limitation de nomination. Surpasser cette li
```suggestion
- Les Beatmap Nominators doivent rester en dessous d'un nombre maximum de nominations dans une période de 90 jours, avec pour chaque mode de jeu sa propre limite de nominations. Dépasser cette limite entraînera un avertissement, puis une exclusion s'ils n'arrivent pas à gérer leur activité en conséquence.
```

2022-06-04 17:54 UTC, Ganondorf-1 approved these changes

2022-06-04 19:23 UTC, DoryanR approved these changes

2022-06-04 21:47 UTC, Walavouchey approved these changes

2022-06-04 21:49 UTC, merged