[ID] Update `Bot account`
ppy/osu-wiki pull request #7425
Opened 2022-06-02 03:19 UTC by ZeroPyrozen

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-02 05:31 UTC, hikikuman requested changes
`*channel*` diganti jadi `kanal` gimana?

2022-06-02 05:31 UTC, hikikuman commented on wiki/Bot_account/id.md
> +**Akun bot** merupakan sebuah akun osu! khusus yang dijalankan oleh layanan otomatis dan bukan orang sungguhan. Jika dilihat di situs web, akun-akun ini memiliki lencana berlabel putih dan bertuliska
```suggestion
**Akun bot** merupakan sebuah akun osu! khusus yang dijalankan secara otomatis, bukan dijalankan oleh orang sungguhan. Jika dilihat di situs web, akun-akun ini memiliki lencana berlabel putih dan bertuliskan `BOT` dan hanya bagian `me!` yang terlihat di profil mereka. Akun bot paling sering digunakan untuk meng-*host* "bot obrolan" yang menawarkan berbagai fungsi kepada komunitas melalui kanal lobi [multiplayer](/wiki/Gameplay/Multiplayer) atau pesan pribadi.
```

2022-06-02 05:31 UTC, hikikuman commented on wiki/Bot_account/id.md
>  Jika bot kamu memenuhi kriteria yang tertera di atas, kamu dapat melakukan pengajuan pembuatan akun bot untuk bot tersebut.
```suggestion
Jika bot kamu memenuhi kriteria yang tertera di atas, kamu dapat melakukan pengajuan pembuatan akun bot.
```

2022-06-02 05:31 UTC, hikikuman commented on wiki/Bot_account/id.md
>  Silakan mengirim email ke [accounts@ppy.sh](mailto:accounts@ppy.sh) dengan judul `Bot Account Request`. Email ini harus dikirim dari alamat email yang tersambung dengan akun osu! kamu.
```suggestion
Silakan kirim email ke [accounts@ppy.sh](mailto:accounts@ppy.sh) dengan judul `Bot Account Request`. Email ini harus dikirim dari alamat email yang tersambung dengan akun osu! kamu.
```

2022-06-02 07:00 UTC, mousesalt commented on wiki/Bot_account/id.md
>  - Bot tidak mengirim pesan apa pun di *channel* publik
```suggestion
- Bot tidak mengirim pesan apa pun di kanal publik
```

2022-06-03 12:24 UTC, mousesalt approved these changes

2022-06-03 12:40 UTC, TicClick approved these changes

2022-06-03 12:42 UTC, merged