[RU] Add `Ranking criteria/osu!catch` and related articles with the o!c terminology
ppy/osu-wiki pull request #7430
Opened 2022-06-02 16:58 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes are reviewed by an osu!catch player

2022-06-04 19:56 UTC, Kewbey commented on wiki/Gameplay/Edge_dash/ru.md
> +**Пиксельный дэш** (англ. *pixel dash*, также *edge dash*) — термин [osu!catch](/wiki/Game_mode/osu!catch), обозначающий достаточно большое расстояние между [активными объектами](/wiki/Glossary/Activ
«первый фрукт придётся собрать» — я бы «собрать» на «поймать» заменил, раз уж в предложении про «ловить» говорится.

2022-06-04 19:56 UTC, Kewbey commented on wiki/Hit_object/Hyperfruit/ru.md
> +Во время игры действие гиперфрукта показывается с помощью красного свечения вокруг фрукта или ловца.
«показывается с помощью» → «показывается в виде»? Раз уж показывается, то вид лучше звучит.

2022-06-04 20:28 UTC, Kewbey approved these changes

2022-06-04 20:47 UTC, Walavouchey approved these changes

2022-06-04 20:48 UTC, TicClick commented
this isn't ready yet!

2022-06-05 08:10 UTC, Kimitakari commented on wiki/Gameplay/Edge_dash/ru.md
> +# Пиксельный дэш
```suggestion
# Пиксель дэш
```

2022-06-05 08:12 UTC, Kimitakari requested changes
Terminology changes and more.

2022-06-05 08:12 UTC, Kimitakari commented on wiki/Gameplay/Edge_dash/ru.md
> +**Пиксельный дэш** (англ. *pixel dash*, также *edge dash*) — термин [osu!catch](/wiki/Game_mode/osu!catch), обозначающий достаточно большое расстояние между [активными объектами](/wiki/Glossary/Activ
```suggestion
**Пиксель дэш** (англ. *pixel dash*, также *edge dash*) — термин [osu!catch](/wiki/Game_mode/osu!catch), обозначающий достаточно большое расстояние между [активными объектами](/wiki/Glossary/Active_object), которое меньше [порогового значения](/wiki/Glossary/Trigger_distance) для появления [гиперфрукта](/wiki/Hit_object/Hyperfruit). Таким образом, игрок будет вынужден ловить второй фрукт без помощи [гипердэша](/wiki/Gameplay/Hyperdash); чтобы успеть это сделать, первый фрукт придётся поймать самым краем тарелки, из-за чего паттерн и получил своё название.
```

2022-06-05 08:13 UTC, Kimitakari commented on wiki/Gameplay/Walk/ru.md
> +# Переход
```suggestion
# Волк
```

2022-06-05 08:14 UTC, Kimitakari commented on wiki/Gameplay/Walk/ru.md
> +**Переход** (англ. *walk*) — движение в [osu!catch](/wiki/Game_mode/osu!catch) от одного фрукта к другому, когда игрок может поймать оба объекта, не пользуясь клавишей, активирующей дэш.
```suggestion
**Волк** или переход (англ. *walk*) — движение в [osu!catch](/wiki/Game_mode/osu!catch) от одного фрукта к другому, когда игрок может поймать оба объекта, не пользуясь клавишей, активирующей дэш.
```

2022-06-05 08:15 UTC, Kimitakari commented on wiki/Gameplay/Walk/ru.md
> +**Переход** (англ. *walk*) — движение в [osu!catch](/wiki/Game_mode/osu!catch) от одного фрукта к другому, когда игрок может поймать оба объекта, не пользуясь клавишей, активирующей дэш.
Можно эти слова воедино вставить через скобку, но не знаю хорошая ли идея или нет.

2022-06-05 08:42 UTC, Kimitakari requested changes

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +***Примечание: эта статья — продолжение [общих критериев ранкинга](/wiki/Ranking_Criteria).***
```suggestion
***Примечание: эта статья является продолжение [общих критериев ранкинга](/wiki/Ranking_Criteria).***
```

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +- **После [быстрого](/wiki/Gameplay/Dash_snapping#быстрый-дэш) [дэша](/wiki/Gameplay/Dash) всегда должен идти [переход](/wiki/Gameplay/Walk).**
```suggestion
- **После [быстрого](/wiki/Gameplay/Dash_snapping#быстрый-дэш) [дэша](/wiki/Gameplay/Dash) всегда должен идти [волк](/wiki/Gameplay/Walk).**
```

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +- **[Пиксельные дэши](/wiki/Gameplay/Edge_dash) запрещены:** они требуют точно выверенного тайминга, чего нельзя ожидать от менее опытных игроков.
```suggestion
- **[Пиксель дэши](/wiki/Gameplay/Edge_dash) запрещены:** они требуют точно выверенного тайминга, чего нельзя ожидать от менее опытных игроков.
```

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +- **По внешнему виду паттернов должно быть понятно, как их поймать: с помощью [перехода](/wiki/Gameplay/Walk) или [дэша](/wiki/Gameplay/Dash).** Так игроки лучше научатся узнавать паттерны, где требу
```suggestion
- **По внешнему виду паттернов должно быть понятно, как их поймать: с помощью [волка](/wiki/Gameplay/Walk) или [дэша](/wiki/Gameplay/Dash).** Так игроки лучше научатся узнавать паттерны, где требуется дэш.
```

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +- **[Пиксельные дэши](/wiki/Gameplay/Edge_dash) запрещены:** они требуют точно выверенного тайминга, чего нельзя ожидать от менее опытных игроков.
```suggestion
- **[Пиксель дэши](/wiki/Gameplay/Edge_dash) запрещены:** они требуют точно выверенного тайминга, чего нельзя ожидать от менее опытных игроков.
```

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +- **Используйте только одиночные [пиксельные дэши](/wiki/Gameplay/Edge_dash), не сочетая их с другими [дэшами](/wiki/Gameplay/Dash) или [гипердэшами](/wiki/Gameplay/Hyperdash).**
```suggestion
- **Используйте только одиночные [пиксель дэши](/wiki/Gameplay/Edge_dash), не сочетая их с другими [дэшами](/wiki/Gameplay/Dash) или [гипердэшами](/wiki/Gameplay/Hyperdash).**
```

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +- **Используйте [гипердэши](/wiki/Gameplay/Hyperdash) вместе с [дропами](/wiki/Hit_object/Juice_stream#drop) или повторами слайдеров, только если слайдер легко проходится.** Это необходимо, чтобы изб
```suggestion
- **Используйте [гипердэши](/wiki/Gameplay/Hyperdash) вместе с [дропами](/wiki/Hit_object/Juice_stream#drop) или повторами слайдеров, только если слайдер легко проходится.** Это необходимо, чтобы избежать хаотичного или излишне сложного движения по слайдеру: ловить дропы на слайдерах сложной формы при включённом гипердэше обычно неприятны, точность при этом ощутимо падает, а взамен игрок получает почти ничего.
```

2022-06-05 08:42 UTC, Kimitakari commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +- **Используйте [пиксельный дэш](/wiki/Gameplay/Edge_dash) не более чем на трёх объектах подряд, а также не ставьте его после [гипердэша](/wiki/Gameplay/Hyperdash).**
```suggestion
- **Используйте [пиксель дэш](/wiki/Gameplay/Edge_dash) не более чем на трёх объектах подряд, а также не ставьте его после [гипердэша](/wiki/Gameplay/Hyperdash).**
```

2022-06-06 19:34 UTC, TicClick commented on wiki/Ranking_Criteria/osu!catch/ru.md
> +***Примечание: эта статья — продолжение [общих критериев ранкинга](/wiki/Ranking_Criteria).***
не, мне так больше нравится

2022-06-06 19:34 UTC, TicClick commented on wiki/Gameplay/Walk/ru.md
> +**Переход** (англ. *walk*) — движение в [osu!catch](/wiki/Game_mode/osu!catch) от одного фрукта к другому, когда игрок может поймать оба объекта, не пользуясь клавишей, активирующей дэш.
да нормально

2022-06-06 19:53 UTC, Walavouchey approved these changes

2022-06-06 19:54 UTC, merged