Use wikilink checker externally
ppy/osu-wiki pull request #7442
Opened 2022-06-04 12:03 UTC by Walavouchey

Supersedes https://github.com/ppy/osu-wiki/pull/7288, part of https://github.com/ppy/osu-wiki/issues/6233

[Walavouchey/osu-wiki-tools](https://github.com/Walavouchey/osu-wiki-tools) is put into a [pip package](https://pypi.org/project/osu-wiki-tools/) and imported when running CI, as [suggested](https://github.com/ppy/osu-wiki/pull/7288#issuecomment-1122044268) by @cl8n

Not much in the actual script used has changed since the other PR, apart from [updating it to use the new `outdated_translation` tag](https://github.com/Walavouchey/osu-wiki-tools/commit/dd668e3ea5e42d1f4ab1bfb4ac4e50cc00c07de6)

The commits for each version are tagged in the osu-wiki-tools repo, and further updates will simply require a version bump here

## Testing

[Test branch](https://github.com/Walavouchey/osu-wiki/pull/23) | [Error output](https://github.com/Walavouchey/osu-wiki/runs/6737733550?check_suite_focus=true) | [Pass output](https://github.com/Walavouchey/osu-wiki/runs/6737749573?check_suite_focus=true)

2022-06-04 15:38 UTC, TicClick requested changes

2022-06-04 15:38 UTC, TicClick commented on .github/workflows/continuous-integration.yml
> +
you have installed it on the line 63 already
```suggestion
          pip install osu-wiki-tools

```

2022-06-04 15:38 UTC, TicClick commented on .github/workflows/continuous-integration.yml
> +          find-broken-wikilinks --target $ARTICLES
it looks like all the scripts from the package are added to `PATH`. I feel like making a small CLI module that would proxy the arguments and run necessary scripts is better for clarity and usability. something like that (in addition to the way the scripts are invoked right now):

```python
wikitools-cli check-links --target ... --some-other-flag=...
```

please keep in mind that it's not a requirement for the PR to be merged, but something to do to the tools collection anyway, separately

2022-06-05 22:58 UTC, TicClick approved these changes
I approve of the change, but again, I took part in this, so I'd like someone else to cast their vote (and maybe look at the code if they will)

2022-06-06 05:45 UTC, peppy approved these changes

2022-06-06 05:45 UTC, merged