Add highlighting for buttons and menu texts in `Performance_troubleshooting`
ppy/osu-wiki pull request #7444
Opened 2022-06-04 15:17 UTC by The-Last-Cookie

According to the [ASC § Keyboard keys](https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#keyboard-keys) and [ASC § Button and menu text](https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#button-and-menu-text).

Unfortunately, I didn't find all the button texts in the Chinese file, so I'm unsure if there are more texts that need to be highlighted.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-06-04 15:27 UTC, TicClick commented
> Unfortunately, I didn't find all the button texts in the Chinese file, so I'm unsure if there are more texts that need to be highlighted.

I think there might be, and it's just translated

2022-06-04 15:49 UTC, Kotoki1337 requested changes
not miss a lot in the Chinese file, as you can see some of the button texts have been highlighted before. according to the changes you made in English, you also need to highlight all of the `无限制` in the text. They are [L10](https://github.com/ppy/osu-wiki/blob/132b064b3cea758c55fc9d5a8c12169132a35b7f/wiki/Performance_troubleshooting/zh.md?plain=1#L10), [L83](https://github.com/ppy/osu-wiki/blob/132b064b3cea758c55fc9d5a8c12169132a35b7f/wiki/Performance_troubleshooting/zh.md?plain=1#L83), [L95](https://github.com/ppy/osu-wiki/blob/132b064b3cea758c55fc9d5a8c12169132a35b7f/wiki/Performance_troubleshooting/zh.md?plain=1#L95). just using `Ctrl + F` things, you should be able deal them.

2022-06-04 15:49 UTC, Kotoki1337 commented on wiki/Performance_troubleshooting/zh.md
> +- 检查在游戏设置中打开`Audio compatibility mode`（音频兼容性模式）是否有帮助。
```suggestion
- 检查在游戏设置中打开 `Audio compatibility mode`（音频兼容性模式）是否有帮助。
```

2022-06-04 17:28 UTC, The-Last-Cookie commented
Is it okay like this or are spaces required for the highlights added in [`eccca5c`](https://github.com/ppy/osu-wiki/pull/7444/commits/eccca5c025235f45da14564f1a7c4264502fc46f) too?

2022-06-04 17:32 UTC, Kotoki1337 commented
> Is it okay like this or are spaces required for the highlights added in [`eccca5c`](https://github.com/ppy/osu-wiki/pull/7444/commits/eccca5c025235f45da14564f1a7c4264502fc46f) too?

it's not really require, if it's me i will add. currently we dont have explicit criteria for this, usually needed between the Chinese and English

2022-06-05 22:34 UTC, TicClick approved these changes

2022-06-05 22:35 UTC, merged