[FR] Update `Beatmap_Spotlights`
ppy/osu-wiki pull request #7452
Opened 2022-06-05 08:47 UTC by DoryanR

Proposal to update the French translation of the wiki page ``Beatmap_Spotlights`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-06 14:39 UTC, DoryanR commented on wiki/Beatmap_Spotlights/fr.md
> +Le **Beatmap Spotlights** (ou simplement *Spotlights*, anciennement *Ranking Charts*.) est un programme récurrent de recommandation et de mise en avant des [beatmaps](/wiki/Beatmap) pour leur design
```suggestion
Le **Beatmap Spotlights** (ou simplement *Spotlights*, anciennement *Ranking Charts*.) est un programme récurrent de recommandation et de mise en avant des [beatmaps](/wiki/Beatmap) pour leur design et leur gameplay excellents et uniques. Il est accompagné d'une [ligue saisonnière](#saisons-spotlights), où les joueurs s'affrontent sur ces beatmaps pour gagner des [badges](#récompenses).
```

2022-06-07 12:31 UTC, Biokax submitted a review, later dismissed

2022-06-08 15:18 UTC, Walavouchey requested changes

2022-06-08 15:18 UTC, Walavouchey commented on wiki/Beatmap_Spotlights/fr.md
> +| ![](img/badges/spring_2022/osu/ri_1.png) ![](img/badges/spring_2022/osu/ri_2.png) | Rhythm Incarnate | The best of the best |
```suggestion
| ![](img/badges/spring_2022/osu/ri_1.png) ![](img/badges/spring_2022/osu/ri_2.png) | Rhythm Incarnate | Les meilleurs des meilleurs |
```

2022-06-08 15:18 UTC, Walavouchey commented on wiki/Beatmap_Spotlights/fr.md
> +Le **Beatmap Spotlights** (ou simplement *Spotlights*, anciennement *Ranking Charts*.) est un programme récurrent de recommandation et de mise en avant des [beatmaps](/wiki/Beatmap) pour leur design
?

```suggestion
Le **Beatmap Spotlights** (ou simplement *Spotlights*, anciennement *Ranking Charts*) est un programme récurrent de recommandation et de mise en avant des [beatmaps](/wiki/Beatmap) pour leur design et leur gameplay excellents et uniques. Il est accompagné d'une [ligue saisonnière](#saisons-spotlights), où les joueurs s'affrontent sur ces beatmaps pour gagner des [badges](#récompenses).
```

2022-06-08 15:34 UTC, Walavouchey approved these changes

2022-06-08 15:38 UTC, merged