[DE] Add `Performance_troubleshooting`
ppy/osu-wiki pull request #7453
Opened 2022-06-05 12:31 UTC by The-Last-Cookie

There are some translations left over because I wasn't sure about a good interlingual rendition (see the various comments):
- `spike frame`
- `frame pacing`
- `frame times`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-05 15:06 UTC, FamousPig requested changes
Can't immediately think of good translations for the untranslated terms. Maybe they don't even have/need proper translations, they are quite technical after all...

2022-06-05 19:19 UTC, respektive requested changes
I'm fine with leaving the untranslated terms in english as they're quite technical terms. You will probably have an easier time searching online for the english terms as well, rather than any translation we come up with.

2022-06-05 19:19 UTC, respektive commented on wiki/Performance_troubleshooting/de.md
> +Es gibt eine spürbare Verzögerung zwischen dem Tippen auf der Tastatur, dem Bewegen der Maus oder des Tablet-Stifts und eine daraus resultierende Aktion auf dem Bildschirm. Beim Diagnostizieren oder
```suggestion
Es gibt eine spürbare Verzögerung zwischen dem Tippen auf der Tastatur, dem Bewegen der Maus oder des Tablet-Stifts und einer daraus resultierenden Aktion auf dem Bildschirm. Beim Diagnostizieren oder Melden kann Folgendes helfen:
```

2022-06-05 19:19 UTC, respektive commented on wiki/Performance_troubleshooting/de.md
> +- Sorge dafür, dass osu! exklusiv im Vollbildmodus läuft. Der randlose oder Fenstermodus können bis zu ein Frame an Verzögerung hinzufügen.
Should also be `einem Frame` I believe.

2022-06-05 19:19 UTC, respektive commented on wiki/Performance_troubleshooting/de.md
> +Allgemein wird das nicht für Bildschirm mit 60 Hz empfohlen. Es kann bei Wiederholungsraten ab 120 Hz nützlich sein, aber mit GSync- und FreeSync-Bildschirmen ist die Anforderung aufgehoben, VSync zu
```suggestion
Allgemein wird das nicht für Bildschirme mit 60 Hz empfohlen. Es kann bei Wiederholungsraten ab 120 Hz nützlich sein, aber mit GSync- und FreeSync-Bildschirmen ist die Anforderung aufgehoben, VSync zur Verhinderung von Screen Tearing zu benutzen.
```

2022-06-05 19:19 UTC, respektive commented on wiki/Performance_troubleshooting/de.md
> +Selbst wenn die Wärmeentwicklung und eine mögliche Überlastung der Hardware kein Problem darstellen, ist `Unbegrenzt` möglicherweise die Option, die dir die stabilsten Frame-Times<!--translate?--> bi
I think `Nichts desto trotz` is fine.

2022-06-05 19:19 UTC, respektive commented on wiki/Performance_troubleshooting/de.md
> +6. Speichere die Konfigurationsdatei (wenn du osu! nach nicht im zweiten Schritt geschlossen hast, tue dies bitte vor dem Speichern).
```suggestion
6. Speichere die Konfigurationsdatei (wenn du osu! noch nicht im zweiten Schritt geschlossen hast, tue dies bitte vor dem Speichern).
```

2022-06-06 10:03 UTC, The-Last-Cookie commented on wiki/Performance_troubleshooting/de.md
> +Dieses FPS-Limit zielt darauf ab, Strom zu sparen und gleichzeitig ein gleichmäßiges Spielerlebnis zu bieten. Es läuft mit 2-facher Bildwiederholungsrate und versucht, ein einheitliches Frame Pacing<
```suggestion
Dieses FPS-Limit zielt darauf ab, Strom zu sparen und gleichzeitig ein gleichmäßiges Spielerlebnis zu bieten. Es läuft mit 2-facher Bildwiederholungsrate und versucht, ein einheitliches Frame-Pacing beizubehalten.
```

2022-06-06 10:09 UTC, FamousPig commented on wiki/Performance_troubleshooting/de.md
> +Während des Spielens hält alles lange genug an, wodurch das Spielerlebnis beeinträchtigt wird. Das kann mehr als einmal auftreten, nach dem Zufallsprinzip oder in gleichmäßigen Abständen. Beim Diagno
Sounds fine
```suggestion
Während des Spielens hält alles lange genug an, sodass das Spielerlebnis beeinträchtigt wird. Das kann mehr als einmal auftreten, nach dem Zufallsprinzip oder in gleichmäßigen Abständen. Beim Diagnostizieren oder Melden kann Folgendes helfen:
```

2022-06-06 10:11 UTC, The-Last-Cookie commented on wiki/Performance_troubleshooting/de.md
> +- Öffne den Task-Manager und ordne die Liste (unter Details) nach CPU. Schaue nach hohen CPU-Auslastungen, sobald spikes<!--translate--> auftreten, zum Beispiel durch einen Viren- oder Malware-Scanne
I kinda prefer this version here over just `Spikes` but a bit unsure because there's `Spike Frame` further below.

2022-06-06 10:11 UTC, The-Last-Cookie commented on wiki/Performance_troubleshooting/de.md
> +Es kann gegenüber `Unbegrenzt` bevorzugt werden, um die Anzahl der gerenderten Frames zu reduzieren, was wiederum den Overhead durch die [Garbage Collection](https://de.wikipedia.org/wiki/Garbage_Col
```suggestion
Es kann gegenüber `Unbegrenzt` bevorzugt werden, um die Anzahl der gerenderten Frames zu reduzieren, was wiederum den Overhead durch die [Garbage Collection](https://de.wikipedia.org/wiki/Garbage_Collection) reduziert (dies kann in Spike-Frames resultieren).
```
or
```suggestion
Es kann gegenüber `Unbegrenzt` bevorzugt werden, um die Anzahl der gerenderten Frames zu reduzieren, was wiederum den Overhead durch die [Garbage Collection](https://de.wikipedia.org/wiki/Garbage_Collection) reduziert (dies kann in niedrigen Bildraten resultieren).
```

2022-06-06 10:14 UTC, FamousPig commented on wiki/Performance_troubleshooting/de.md
> +Es kann gegenüber `Unbegrenzt` bevorzugt werden, um die Anzahl der gerenderten Frames zu reduzieren, was wiederum den Overhead durch die [Garbage Collection](https://de.wikipedia.org/wiki/Garbage_Col
https://github.com/ppy/osu-wiki/blob/46a3225687f9b50781268751c302c2a7277f4bfe/wiki/Performance_troubleshooting/en.md?plain=1#L83

Original line says spike frames so 1

2022-06-06 10:18 UTC, The-Last-Cookie commented on wiki/Performance_troubleshooting/de.md
> +- Öffne den Task-Manager und ordne die Liste (unter Details) nach CPU. Schaue nach hohen CPU-Auslastungen, sobald spikes<!--translate--> auftreten, zum Beispiel durch einen Viren- oder Malware-Scanne
Using `Spikes` here to be consistent throughout the article.
```suggestion
- Öffne den Task-Manager und ordne die Liste (unter Details) nach CPU. Schaue nach hohen CPU-Auslastungen, sobald Spikes auftreten, zum Beispiel durch einen Viren- oder Malware-Scanner im Hintergrund. Du kannst osu! im Fenstermodus laufen lassen oder den Task-Manager auf einem zweiten Bildschirm platzieren, um das zu diagnostizieren, während du selbst spielst oder eine Beatmap mit der Mod Auto ausführst.
```

2022-06-06 10:36 UTC, FamousPig commented on wiki/Performance_troubleshooting/de.md
> +- Öffne den Task-Manager und ordne die Liste (unter Details) nach CPU. Schaue nach hohen CPU-Auslastungen, sobald spikes<!--translate--> auftreten, zum Beispiel durch einen Viren- oder Malware-Scanne
Occurence 1:
https://github.com/ppy/osu-wiki/blob/46a3225687f9b50781268751c302c2a7277f4bfe/wiki/Performance_troubleshooting/en.md?plain=1#L35

Occurence 2(this):
https://github.com/ppy/osu-wiki/blob/46a3225687f9b50781268751c302c2a7277f4bfe/wiki/Performance_troubleshooting/en.md?plain=1#L61

"Spikes" and low frame rate are 2 different things

2022-06-06 11:13 UTC, The-Last-Cookie commented on wiki/Performance_troubleshooting/de.md
> +- Öffne den Task-Manager und ordne die Liste (unter Details) nach CPU. Schaue nach hohen CPU-Auslastungen, sobald Spikes auftreten, zum Beispiel durch einen Viren- oder Malware-Scanner im Hintergrund
```suggestion
- Öffne den Task-Manager und ordne die Liste (unter Details) nach CPU. Schaue nach hohen CPU-Auslastungen während Perioden mit niedriger Bildrate, zum Beispiel durch einen Viren- oder Malware-Scanner im Hintergrund. Du kannst osu! im Fenstermodus laufen lassen oder den Task-Manager auf einem zweiten Bildschirm platzieren, um das zu diagnostizieren, während du selbst spielst oder eine Beatmap mit der Mod Auto ausführst.
```

2022-06-06 11:13 UTC, The-Last-Cookie commented on wiki/Performance_troubleshooting/de.md
> +### Spike frame<!--not sure on translation, maybe stottern or Leistungseinbußen?-->
```suggestion
### Spike-Frame
```

2022-06-06 11:13 UTC, The-Last-Cookie commented on wiki/Performance_troubleshooting/de.md
> +- Öffne den Task-Manager und ordne die Liste (unter Details) nach CPU. Schaue nach hohen CPU-Auslastungen, sobald spikes<!--translate--> auftreten, zum Beispiel durch einen Viren- oder Malware-Scanne
Oh, thanks! I thought the two texts to be the same, hence why I copied it over 👀

2022-06-06 11:48 UTC, FamousPig approved these changes

2022-06-06 19:17 UTC, respektive approved these changes

2022-06-06 19:45 UTC, TicClick approved these changes

2022-06-06 19:47 UTC, merged