[FR] Update `Article_styling_criteria\Writing`
ppy/osu-wiki pull request #7473
Opened 2022-06-08 17:17 UTC by DoryanR

Proposal to update the French translation of the wiki page `Article_styling_criteria\Writing`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-10 07:08 UTC, Biokax requested changes

2022-06-10 07:08 UTC, Biokax commented on wiki/Article_styling_criteria/Writing/fr.md
> +> plz profiter du jeu
```suggestion
> svp profitez du jeu
```

2022-06-11 17:40 UTC, Ganondorf-1 requested changes

2022-06-11 17:40 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Writing/fr.md
> +Lorsque vous citez le texte de quelqu'un, précisez la personne citée après la [citation en block](/wiki/Article_styling_criteria/Formatting#citations-en-bloc) avec un tiret (`-`). Si la citation orig
```suggestion
Lorsque vous citez le texte de quelqu'un, précisez la personne citée après la [citation en bloc](/wiki/Article_styling_criteria/Formatting#citations-en-bloc) avec un tiret (`-`). Si la citation originale provient d'une source non anglophone, précisez-la entre parenthèses.
```

2022-06-12 19:46 UTC, Ganondorf-1 approved these changes

2022-06-16 23:18 UTC, cl8n approved these changes

2022-06-16 23:19 UTC, cl8n approved these changes

2022-06-16 23:21 UTC, merged