[FR] Add `Beatmapping\Mapping_techniques\Flow`
ppy/osu-wiki pull request #7485
Opened 2022-06-10 18:19 UTC by DoryanR

Proposal to add the French translation of the wiki page `Beatmapping\Mapping_techniques\Flow`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-10 19:46 UTC, Biokax requested changes

2022-06-10 19:46 UTC, Biokax commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +La répétition est une autre forme de mouvement naturel. Les patterns comportant des mouvements répétés similaires qui ne diffèrent que légèrement, tels que les [sauts](/wiki/Beatmap/Pattern/Jump) bac
```suggestion
La répétition est une autre forme de mouvement naturel. Les patterns comportant des mouvements répétés similaires qui ne diffèrent que légèrement, tels que les [jumps](/wiki/Beatmap/Pattern/Jump) aller-retour ou une série de slider pairs, sont confortables à jouer car la succession de mouvement suis un chemin familiers, ce qui les rend faciles à prévoir. Les patterns répétés peuvent devenir de plus en plus confortables tout au long d'une beatmap pour la même raison.
```

2022-06-10 19:46 UTC, Biokax commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +## See also
```suggestion
## Voir également
```

2022-06-10 19:46 UTC, Biokax commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +[^circular-flow]: Pour les joueurs utilisant une souris, un mouvement circulaire appliqué dans la même direction pendant trop longtemps est considéré comme trop répétitif et inconfortable en raison d
```suggestion
[^circular-flow]: Pour les joueurs utilisant une souris, un mouvement circulaire appliqué dans la même direction pendant trop longtemps est considéré comme trop répétitif et inconfortable en raison de la dérive de la souris (également appelé mouse drift en anglais).
```

2022-06-11 17:45 UTC, Ganondorf-1 requested changes

2022-06-11 17:45 UTC, Ganondorf-1 commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +**Flow** est un concept de mapping qui décrit les schémas de mouvement naturels et intuitifs du curseur d'un joueur pendant le gameplay. Le flow, ou son absence, est lié au mode de jeu [osu!](/wiki/G
```suggestion
Le **flow** est un concept de mapping qui décrit les schémas de mouvement naturels et intuitifs du curseur d'un joueur pendant le gameplay. Le flow, ou son absence, est lié au mode de jeu [osu!](/wiki/Game_mode/osu!) en raison de son champ de jeu bidimensionnel. En utilisant la grande variété de [patterns](/wiki/Beatmap/Pattern) et de formes de sliders possibles dans les beatmaps d'osu!, les mappeurs sont en mesure de diriger le curseur du joueur sur le terrain de jeu de différentes manières, ce qui produit des effets différents sur l'expérience de jeu.
```

2022-06-11 17:45 UTC, Ganondorf-1 commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +Le flow est considérée comme un sujet **subjectif** et souvent controversé en raison de la façon dont les différents mappeurs et joueurs conçoivent ou perçoivent le mouvement. Certains aspects du flo
```suggestion
Le flow est considéré comme un sujet **subjectif** et souvent controversé en raison de la façon dont les différents mappeurs et joueurs conçoivent ou perçoivent le mouvement. Certains aspects du flow peuvent avoir un impact sur la jouabilité à différents degrés selon le [périphérique d'entrée](/wiki/Gameplay/Input_device) du joueur, tel que la [tablette graphique](/wiki/Gameplay/Input_device/Graphics_tablet) ou la [souris](/wiki/Gameplay/Input_device/Mouse), ou les compétences ou l'expérience acquises par le joueur.
```

2022-06-11 17:45 UTC, Ganondorf-1 commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +Si les préférences en matière de mouvement varient d'une personne à l'autre, il existe quelques idées qui donnent le sentiment et l'impression de flow sur une majorité de patterns ou de beatmaps enti
```suggestion
Si les préférences en matière de mouvement varient d'une personne à l'autre, il existe quelques idées qui donnent le sentiment et l'impression de flow sur une majorité de patterns ou de beatmaps entières.
```

2022-06-11 17:45 UTC, Ganondorf-1 commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +La répétition est une autre forme de mouvement naturel. Les patterns comportant des mouvements répétés similaires qui ne diffèrent que légèrement, tels que les [jumps](/wiki/Beatmap/Pattern/Jump) all
```suggestion
La répétition est une autre forme de mouvement naturel. Les patterns comportant des mouvements répétés similaires qui ne diffèrent que légèrement, tels que les [jumps](/wiki/Beatmap/Pattern/Jump) aller-retour ou une série de sliders pairs, sont confortables à jouer car la succession de mouvement suit un chemin familier, ce qui les rend faciles à prévoir. Les patterns répétés peuvent devenir de plus en plus confortables tout au long d'une beatmap pour la même raison.
```

2022-06-11 17:45 UTC, Ganondorf-1 commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +Pour donner à une beatmap un aspect plus naturel, les mappeurs peuvent utiliser des sliders de formes différentes qui renforcent la direction suggérée du mouvement. Puisque les sliders body n'ont pas
```suggestion
Pour donner à une beatmap un aspect plus naturel, les mappeurs peuvent utiliser des sliders de formes différentes qui renforcent la direction suggérée du mouvement. Puisque les slider bodies n'ont pas besoin d'être suivis parfaitement, parce que le curseur doit seulement atteindre les [slider ticks](/wiki/Beatmapping/Slider_tick), ils peuvent être ajustés et pliés de nombreuses façons sans affecter le mouvement nécessaire pour les franchir. Cela permet aux formes de sliders de compléter une trajectoire de mouvement existante, ou d'aider le joueur à choisir une nouvelle trajectoire de mouvement.
```

2022-06-11 17:45 UTC, Ganondorf-1 commented on wiki/Beatmapping/Mapping_techniques/Flow/fr.md
> +- [Mapping Analysis #1 - Flow](https://osu.ppy.sh/home/news/2013-09-15-mapping-analysis-1-flow), un new post par ![][flag_FR] [Shiro](https://osu.ppy.sh/users/113005)
```suggestion
- [Mapping Analysis #1 - Flow](https://osu.ppy.sh/home/news/2013-09-15-mapping-analysis-1-flow), un news post par ![][flag_FR] [Shiro](https://osu.ppy.sh/users/113005)
```

2022-06-12 20:04 UTC, Ganondorf-1 approved these changes

2022-06-13 00:47 UTC, cl8n approved these changes

2022-06-13 00:48 UTC, merged