[FR] Cleanup `Gameplay\Replay`
ppy/osu-wiki pull request #7486
Opened 2022-06-10 19:37 UTC by DoryanR

Proposal for cleanup the French translation of the wiki page `Gameplay\Replay`.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-13 18:01 UTC, Ganondorf-1 requested changes

2022-06-17 10:29 UTC, Walavouchey commented on wiki/Gameplay/Replay/fr.md
> +En regardant le replay, le drain de santé fonctionnera comme d'habitude, pas de mouvement du curseur, et *pas de miss* (donc 100.00% de précision) jusqu'au moment où le temps de `Preview Gameplay` a
```suggestion
En regardant le replay, le drain de santé fonctionnera comme d'habitude, pas de mouvement du curseur, et *pas de miss* (donc 100,00% de précision) jusqu'au moment où le temps de `Preview Gameplay` a été réglé sur run, où les hit bursts commenceront à fonctionner.
```

2022-06-23 18:07 UTC, Ganondorf-1 requested changes

2022-06-23 18:07 UTC, Ganondorf-1 commented on wiki/Gameplay/Replay/fr.md
> +Lorsque vous regardez un replay depuis le classement (excluant les replays exporté), le nombre affiché à côté dans le compteur de "Replays regardés par les autres" sur le profil du joueur du replay a
```suggestion
Lorsque vous regardez un replay depuis le classement (excluant les replays exportés), le nombre affiché à côté dans le compteur de "Replays regardés par les autres" sur le profil du joueur du replay augmentera de 1.
```

2022-07-04 13:42 UTC, Biokax submitted a review, later dismissed

2022-07-12 21:44 UTC, cl8n approved these changes

2022-07-12 21:45 UTC, merged