[FR] Update `Modding/Kudosu`
ppy/osu-wiki pull request #7495
Opened 2022-06-13 11:03 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-13 11:30 UTC, Ganondorf-1 requested changes

2022-06-13 11:30 UTC, Ganondorf-1 commented on wiki/Modding/Kudosu/fr.md
> +Le kudosu est attribué aux posts de modding qui ont aidé et apporté des suggestions utiles pour la map. Si un mappeur trouve qu'un post de modding est utile et montre un problème valide, il peut cliq
```suggestion
Le kudosu est attribué aux posts de modding qui ont aidé et apporté des suggestions utiles pour la beatmap. Si un mappeur trouve qu'un post de modding est utile et montre un problème valide, il peut cliquer sur le bouton de pouce en l'air et récompenser d'un kudosu l'utilisateur ayant fait le post de modding.
```

2022-06-13 11:30 UTC, Ganondorf-1 commented on wiki/Modding/Kudosu/fr.md
> +De nos jours, le kudosu est utilisé dans l'évaluation de la capicité d'un utilisateur à [devenir](/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator) un [Beatmap Nominator](/wiki/P
```suggestion
De nos jours, le kudosu est utilisé dans l'évaluation de la capacité d'un utilisateur à [devenir](/wiki/People/The_Team/Beatmap_Nominators/Becoming_a_Beatmap_Nominator) un [Beatmap Nominator](/wiki/People/The_Team/Beatmap_Nominators). Un utilisateur doit avoir 200 kudosu dans le mode osu! ou 150 kudosu dans les modes osu!taiko, osu!catch ou osu!mania pour faire une demande.
```

2022-06-13 12:48 UTC, DoryanR approved these changes

2022-06-16 22:33 UTC, cl8n approved these changes

2022-06-16 22:36 UTC, merged