[ZH] Update `Help_centre` and `Help_centre/Account_restrictions`
ppy/osu-wiki pull request #7497
Opened 2022-06-13 16:38 UTC by Kotoki1337

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-14 15:36 UTC, kj415j45 commented on wiki/Help_centre/Account_restrictions/zh.md
> +账号被限制后，将无法与社区进行互动，直到限制解除为止。账号被限制的玩家仍然可以继续游玩，下载谱面并上传成绩，但账号的个人信息不会被他人可见。
```suggestion
账号被限制后，将无法与社区进行互动，直到限制解除为止。账号被限制的玩家仍然可以继续游玩，下载谱面并上传成绩，但账号的个人信息变为不可见。
```

2022-06-14 16:20 UTC, Kotoki1337 commented on wiki/Help_centre/Account_restrictions/zh.md
> +账号被限制后，将无法与社区进行互动，直到限制解除为止。账号被限制的玩家仍然可以继续游玩，下载谱面并上传成绩，但账号的个人信息不会被他人可见。
读起来舒服一点

```suggestion
账号被限制后，将无法与社区进行互动，直到限制解除为止。账号被限制的玩家仍然可以继续游玩，下载谱面并上传成绩，但账号的个人信息会变为不可见。
```

2022-06-16 23:08 UTC, cl8n requested changes

2022-06-16 23:08 UTC, cl8n commented on wiki/Help_centre/Account_restrictions/zh.md
> +**我们只会对发送至 [appeal-review@ppy.sh](mailto:appeal-review@ppy.sh) 的复审或调查请求进行答复。**不要试图通过推特，Discord，QQ 等方式联系开发人员（以及 GMT、NAT 等志愿者团队）来绕过这个政策——他们帮不了您。
should probably specifically mention Twitter as in EN as that's where some people on these volunteer teams have accounts

2022-06-16 23:08 UTC, cl8n commented on wiki/Help_centre/Account_restrictions/zh.md
>  一些玩家会在解除限制并游玩以后立刻被再度限制。这是由机器人完成的，且一般会在 24 小时以内被解除。如果您遇到了这种情况，请迅速通过在推特上通知 [@osusupport](https://twitter.com/osusupport) 或发邮件的方式说明问题。
in EN it also mentions email as an option in the last sentence

2022-06-17 02:38 UTC, cl8n approved these changes

2022-06-17 02:40 UTC, merged