[FR] Update `History_of_osu!`
ppy/osu-wiki pull request #7529
Opened 2022-06-18 19:08 UTC by DoryanR

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-23 18:11 UTC, Ganondorf-1 requested changes

2022-06-23 18:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/fr.md
> +- [2012](/wiki/History_of_osu!/2012) - Cinq ans d'osu!, d'osu!mania, de support pour écran large et de paramètres visuels
```suggestion
- [2012](/wiki/History_of_osu!/2012) - Cinq ans d'osu!, osu!mania, support pour écran large et paramètres visuels
```

2022-06-23 18:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/fr.md
> +- [2013](/wiki/History_of_osu!/2013) - Refonte de l'interface utilisateur, skins HD, prise en charge améliorée des écrans larges, éditeur osu!mania, collections en jeu, introduction du moddingV2, Dis
```suggestion
- [2013](/wiki/History_of_osu!/2013) - Refonte de l'interface utilisateur, skins HD, prise en charge améliorée des écrans larges, éditeur osu!mania, collections en jeu, introduction du moddingV2, Disqus, osu!api, overlays de précision, Comic Fiesta 2013, téléchargements illimités et osu!cuttingedge (réservé aux osu!supporters)
```

2022-06-23 18:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/fr.md
> +- [2015](/wiki/History_of_osu!/2015) - jizz (refonte de osu!web), osu!weekly, et osu!coins
```suggestion
- [2015](/wiki/History_of_osu!/2015) - jizz (refonte d'osu!web), osu!weekly, et osu!coins
```

2022-06-23 18:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/fr.md
> +- [2016](/wiki/History_of_osu!/2016) - scorev2, l'annonce d'une nouvelle version open-source "lazer" d'osu! (précédemment connue sous le nom de "osu!lazer"), et une refonte de l'osu! wiki
```suggestion
- [2016](/wiki/History_of_osu!/2016) - scorev2, annonce d'une nouvelle version open-source "lazer" d'osu! (précédemment connue sous le nom de "osu!lazer"), et une refonte de l'osu! wiki
```

2022-06-23 18:11 UTC, Ganondorf-1 commented on wiki/History_of_osu!/fr.md
> +Les archives de l'histoire d'osu!, tout dans l'osu! wiki
```suggestion
Les archives de l'histoire d'osu!, tout dans l'osu! wiki.
```

2022-07-01 18:22 UTC, Ganondorf-1 approved these changes

2022-07-03 18:59 UTC, cl8n submitted a review, later dismissed

2022-07-03 19:11 UTC, cl8n approved these changes

2022-07-03 19:12 UTC, merged