[FR] Update `Ranking_Criteria`
ppy/osu-wiki pull request #7535
Opened 2022-06-19 14:40 UTC by DoryanR

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] The changes have been approved on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-19 14:46 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +[^dimensions-maximales]: Les arrière-plans qui sont également utilisés comme images de storyboard peuvent suivre [la règle des images de storyboard pour les dimensions maximales](/wiki/Ranking_Criter
```suggestion
[^dimensions-maximales]: Les arrière-plans qui sont également utilisés comme images de storyboard peuvent suivre [la règle des images de storyboard pour les dimensions maximales](/wiki/Ranking_Criteria#règles.7) à la place.

```

2022-06-23 18:15 UTC, Ganondorf-1 requested changes

2022-06-23 18:15 UTC, Ganondorf-1 commented on wiki/Ranking_Criteria/fr.md
> +- **Si le média applicable au champ source contient des sous-séries, l'étiquette la plus précise doit être utilisée comme source.** Si une musique a plusieurs sous-séries applicables, la source princ
```suggestion
- **Si le média applicable au champ source contient des sous-séries, le label le plus précis doit être utilisé comme source.** Si une musique a plusieurs sous-séries applicables, la source principale du média peut être utilisée à la place.
```

2022-06-28 23:16 UTC, cl8n commented
seems missing changes from https://github.com/ppy/osu-wiki/pull/7503/files#diff-d83e7a1fb8077f937a9a91827c6cb673767a7ebb721e3482bdc146a80802b3d2 (even though this is in the tree)

also, under L128 there are sub-bullets in EN that are missing here. not related to your changes but I think that should be updated before removing `outdated` tag

2022-07-03 19:50 UTC, cl8n commented on wiki/Ranking_Criteria/fr.md
> +[^dimensions-maximales]: Les arrière-plans qui sont également utilisés comme images de storyboard peuvent suivre [la règle des images de storyboard pour les dimensions maximales](/wiki/Ranking_Criter
also, the identifier here (e.g. `[^personnage-voix-acteur]`) should *not* be translated, we'll prob add that to ASC soon

2022-07-10 08:36 UTC, DoryanR commented on wiki/Ranking_Criteria/fr.md
> +  - `ё` doit être romanisé en `yo`, cependant, utilisez `o` si le caractère vient après `ж`, `ч`, `ш`, ou `щ``.
```suggestion
  - `ё` doit être romanisé en `yo`, cependant, utilisez `o` si le caractère vient après `ж`, `ч`, `ш`, ou `щ`.
```

2022-07-11 12:31 UTC, Biokax approved these changes

2022-07-12 21:35 UTC, cl8n approved these changes

2022-07-12 21:36 UTC, merged