translated Game_mode and Game_mode osu! to Russian
ppy/osu-wiki pull request #7556
Opened 2022-06-23 15:28 UTC by l43yrnt

[Game_mode osu!.md](https://github.com/ppy/osu-wiki/files/8968675/Game_mode.osu.md)
[Game_mode.md](https://github.com/ppy/osu-wiki/files/8968676/Game_mode.md)

2022-06-23 18:59 UTC, TPGPL requested changes

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/osu!/ru.md
> +![Gameplay example of Osu! Tatakae! Ouendan in Nintendo DS](/wiki/shared/Ouendan.jpg "Пример геймплея Osu! Tatakae! Ouendan на Nintendo DS")
```suggestion
![Пример геймплея Osu! Tatakae! Ouendan на Nintendo DS](/wiki/shared/Ouendan.jpg "Пример геймплея Osu! Tatakae! Ouendan на Nintendo DS")
```

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/ru.md
> +![Mode selection interface](/wiki/shared/Interface_mode.png "Mode selection interface")
need to translate tooltip & alt-text

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/ru.md
> +*osu!taiko* имитирует процесс игры на настоящем барабане, где игроки используют клавиатуру или ударную установку что бы попадать по разноцветным кругам на одном конвейере. Режим основан на *[Taiko no
```suggestion
*osu!taiko* имитирует процесс игры на настоящем барабане, где игроки используют клавиатуру или ударную установку что бы попадать по разноцветным кругам на одном конвейере. Режим основан на *[Taiko no Tatsujin](https://ru.wikipedia.org/wiki/Taiko_no_Tatsujin)*, серии игр основаной [Bandai Namco Entertainment](https://ru.wikipedia.org/wiki/Bandai_Namco_Entertainment). Маскот osu!taiko - [Mocha](/wiki/Mascots#mocha), зелёноволосая девушка в кимоно, держащая барабанные палочки.
```

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/ru.md
> +![Геймплей osu!mania](/wiki/shared/mania-gameplay.jpg "osu!mania gameplay")
```suggestion
![Геймплей osu!mania](/wiki/shared/mania-gameplay.jpg "геймплей osu!mania")
```

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/ru.md
> +![Gameplay of osu!catch](/wiki/shared/catch-gameplay.jpg "osu!catch gameplay")
```suggestion
![Геймплей osu!catch](/wiki/shared/catch-gameplay.jpg "геймплей osu!catch")
```

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/ru.md
> +![Gameplay of osu!taiko](/wiki/shared/taiko-gameplay.jpg "osu!taiko gameplay")
```suggestion
![Геймплей osu!taiko](/wiki/shared/taiko-gameplay.jpg "геймплей osu!taiko")
```

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/ru.md
> +![Gameplay of osu!](/wiki/shared/osu-gameplay.jpg "osu! gameplay")
```suggestion
![Геймплей osu!](/wiki/shared/osu-gameplay.jpg "геймплей osu!")
```

2022-06-23 18:59 UTC, TPGPL commented on wiki/Game_mode/ru.md
> +*osu!mania* режим ритм-игры с вертикальной прокруткой (VSRG), разработанный как симулятор пианино. Режим в основном был [представлен и реализован](https://osu.ppy.sh/community/forums/topics/100751) и
```suggestion
*osu!mania* режим ритм-игры с вертикальной прокруткой (VSRG), разработанный как симулятор пианино. Режим в основном был [представлен и реализован](https://osu.ppy.sh/community/forums/topics/100751) игроком [woc2006](https://osu.ppy.sh/users/1105845), и основан на разнообразных ритм-играх конвейерного типа (а именно [Dance Dance Revolution](https://ru.wikipedia.org/wiki/Dance_Dance_Revolution) и [Beatmania](https://ru.wikipedia.org/wiki/Beatmania)). Маскоты osu!mania - близнецы [Mani and Mari](/wiki/Mascots#mani-&-mari), как с фиолетовыми, так и со светло-фиолетовыми волосами.
```

2022-06-25 18:18 UTC, Ldashy1 requested changes
так как я уже переводил статью про режимы игры, упрощу задачу, предложив свой вариант перевода некоторых кусков в этой статье, прошу внести изменения.

2022-06-25 18:18 UTC, Ldashy1 commented on wiki/Game_mode/ru.md
> +![Интерфейс выбора мода](/wiki/shared/Interface_mode.png "Интерфейс выбора мода")
такой перевод будет более правильным

```suggestion
![Интерфейс выбора режима](/wiki/shared/Interface_mode.png "Интерфейс выбора режима")
```

2022-06-25 18:18 UTC, Ldashy1 commented on wiki/Game_mode/ru.md
> +- `Ctrl` + `4` для osu!mania
```suggestion
- `Ctrl` + `1` для выбора osu!
- `Ctrl` + `2` для выбора osu!taiko
- `Ctrl` + `3` для выбора osu!catch
- `Ctrl` + `4` для выбора osu!mania
```

2022-06-27 17:13 UTC, Ldashy1 requested changes
Так как твой перевод страницы про osu! выглядит уж слишком машинным, я решил поисправлять некоторые ошибки, но пришлось переводить всю статью с самого начала, чтобы во всем разобраться. Хоть я и не закомментил свои изменения, но прошу тебя, постарайся разобраться с ошибками в своем тексте и понять, почему он выглядит столь не читабельным, чтобы больше не допускать подобных ошибок.

2022-06-27 17:13 UTC, Ldashy1 commented on wiki/Game_mode/osu!/ru.md
> +![Геймплей osu!](/wiki/shared/osu-gameplay.jpg "osu! Интерфейс")
```suggestion
![Геймплей osu!](/wiki/shared/osu-gameplay.jpg "Интерфейс osu!")
```

2022-06-27 17:13 UTC, Ldashy1 commented on wiki/Game_mode/osu!/ru.md
> +*Туториал: [new beginnings (в комплекте с osu!)](https://osu.ppy.sh/beatmapsets/1011011).*
```suggestion
*Туториал: [new beginnings (входит в osu!)](https://osu.ppy.sh/beatmapsets/1011011).*
```

2022-06-29 09:06 UTC, l43yrnt commented on wiki/Game_mode/osu!/ru.md
> +- Когда играет [Auto](/wiki/Game_modifier/Auto), имя игрока будет osu!.
[Auto](/wiki/Игровой модификатор/Auto) не менял, так как это убивает ссылку

2022-07-02 17:19 UTC, Ldashy1 submitted a review, later dismissed

2022-07-02 19:12 UTC, TicClick commented
загляну в ближайшие несколько дней

2022-07-11 23:30 UTC, TicClick requested changes
первая часть ревью (`Game mode` посмотрю потом)

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +*Обратитесь к [Странице стилей игры в osu!](/wiki/Play_style).*
```suggestion
*См. также: [Стили игры § osu!](/wiki/Play_style#osu!).*
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +По умолчанию для osu! используются следующие элементы управления:
```suggestion
## Управление

Настройки управления по умолчанию:
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +| Левый клик(M1) / Правый клик(M2) | `Z`(K1) / `X`(K2) | Касание экрана(M1) |
```suggestion
| Левая кнопка (M1) / Правая кнопка (M2) | `Z` (K1) / `X` (K2) | Касание экрана (M1) |
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +Хит-объекты в osu! примут любой ввод от устройства ввода, при условии, что каждый хит-объект был вовремя нажат.
более понятное и естественное предложение
```suggestion
Игровые объекты в osu! можно проходить с любого устройства, главное — нажимать на них вовремя.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +Если был применен игровой модификатор [Relax](/wiki/Game_modifier/Relax), то управлять можно будет только внутриигровым курсором. Используйте внутриигровой курсор, чтобы наводиться на хит-обьекты, а
```suggestion
При включённом моде [Relax](/wiki/Game_modifier/Relax) можно управлять только курсором (нажатия будут происходить автоматически). Спиннеры по-прежнему придётся раскручивать вручную.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +Если был применен игровой модификатор [Auto Pilot](/wiki/Game_modifier/Autopilot), то работать будет только ввод с устройства ввода. Вовремя нажимайте на хит-объекты, пока курсор будут перемещаться а
```suggestion
При включённом моде [Autopilot](/wiki/Game_modifier/Autopilot) можно управлять только нажатиями (курсор будут перемещаться автоматически). Спиннеры будут раскручиваться со скоростью мода [Spun Out](/wiki/Game_modifier/Spun_Out).
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +[Очки в osu!](/wiki/Gameplay/Score/osu!) представляет собой взвешенную сумму нескольких компонентов игрового процесса. Подсчет очков зависит от следующего:
```suggestion
Число [игровых очков в osu!](/wiki/Gameplay/Score/osu!) — взвешенная сумма нескольких игровых компонентов. На подсчёт очков влияют следующие вещи:
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- [Оценка (Judgement)] (/wiki/Gameplay/Judgement/osu!) определяет базовое значение очков объекта попадания (300, 100, 50 или 0 в случае промаха). Для [хит-кругов](/wiki/Hit_object/Hit_circle), своевр
```suggestion
- [Оценка (*англ.* judgement)] (/wiki/Gameplay/Judgement/osu!) определяет базовую «стоимость» игрового объекта (300, 100, 50 или 0 в случае промаха). В случае [нот](/wiki/Hit_object/Hit_circle) своевременные нажатия клавиш ценятся в разы больше как по количеству очков, так и по точности. У [слайдеров](/wiki/Hit_object/Slider) и [спиннеров](/wiki/Hit_object/Spinner) нет окон попадания, но они будут прерывать комбо, если их пропустить или не пройти должным образом. Получение более высокой оценки также дает бо́льшую прибавку к [здоровью](/wiki/Gameplay/Health).
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- [Точность (Accuracy)](/wiki/Gameplay/Accuracy#osu!) зависит от оценки и показывает, насколько точны попадания. Позднее или раннее нажатие клавиш, а также промахи снижают общую точность.
```suggestion
- [Точность (*англ.* accuracy)](/wiki/Gameplay/Accuracy#osu!) зависит от оценки и показывает, насколько своевременны попадания. Поздние или ранние нажатия клавиш, а также промахи снижают общую точность.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- [Комбо (Combo)](/wiki/Gameplay/Combo_(score_multiplier)) является множителем очков: очистка объекта, в которого попали, дает больше очков, если комбо большое, и наоборот. Комбо может быть [прервано
- здесь можно без английского термина
- к сожалению (или счастью), все русские говорят «слайдербрейк»
```suggestion
- [Комбо](/wiki/Gameplay/Combo_(score_multiplier)) является множителем очков: при большом комбо объекты приносят больше очков, и наоборот. Комбо может быть [прервано](/wiki/Gameplay/Judgement/Combobreak) промахом или [слайдербрейком](/wiki/Gameplay/Judgement/Slider_break).
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +После прохождения карты результату присваивается [оценка](/wiki/Gameplay/Grade#osu!) — краткая характеристика точности в виде одной буквы. Золотой или серебряный SS означает стопроцентную точность, а
```suggestion
После прохождения карты результату присваивается [оценка](/wiki/Gameplay/Grade#osu!) — краткая характеристика точности в виде одной буквы. Золотая или серебряная SS означает стопроцентную точность, а все остальные, от S до D, зависят от числа 300, 50 и промахов.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +*Для более подробной информации, обратитесь к [Странице про скиннинг osu!](/wiki/Skinning/osu!).*
```suggestion
*Подробнее см. [Скиннинг § osu!](/wiki/Skinning/osu!).*
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +![Настройки смоука в osu!](/wiki/shared/osu_smoke_set.jpg "Смоук в настройках управления")
```suggestion
![Эффект дыма в osu!](/wiki/shared/osu_smoke.jpg "Использование дыма ")

![Настройка дыма в osu!](/wiki/shared/osu_smoke_set.jpg "Клавиша активации дыма в настройках управления")
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- В зависимости от настройки сложности и допустимого времени, слишком раннее нажатие на объект попадания приведет к сильной тряске хит-обьекта.
```suggestion
- В зависимости от настроек сложности и окна попадания, слишком раннее нажатие на ноту заставит её трястись.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- Отпускание мяча-слайдера на пустой дорожке слайдера без скрытых или видимых тиков слайдера не приведет ни к прерыванию комбо, ни к начислению очков. Оценка слайдера проверяет только то, был ли нажа
```suggestion
- Отпускание мяча на пустом слайдере без слайдертиков не приведёт ни к прерыванию комбо, ни к начислению очков. Слайдер проверяет только нажатие на его начало, сбор слайдертиков и успешное прохождение его конца.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- Изменение направления вращения в середине вращения заставит спиннер замедлиться (количество вращений в минуту уменьшится до 0, чтобы сбросить ориентацию вращения), а затем вращаться в правильном на
слишком много ненужных уточнений
```suggestion
- Смена направления во время вращения заставит спиннер замедлиться (число вращений в минуту уменьшится до 0), а затем вращаться в новом направлении. Прогресс вращения не будет потерян во время переориентации и продолжит увеличиваться при обратном вращении.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- Отсутствие вращения спиннера вокруг центра **не** будет считаться правильным вращением.
можно проще
```suggestion
- Вращение спиннера не по кругу **не** засчитывается.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- Дым длится дольше, чем стандартный внутриигровой след курсора. Применяйте эффекты дыма реже, чтобы старые эффекты дыма не исчезали слишком быстро.
мне кажется, так получше
```suggestion
- Дым на игровом поле сохраняется дольше, чем стандартный след от игрового курсора. Если вы не хотите, чтобы дым быстро пропадал, рисуйте им реже.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- Когда в игре установлен мод [Auto](/wiki/Game_modifier/Auto), в качестве имени игрока будет отображаться osu!
```suggestion
- При активации мода [Auto](/wiki/Game_modifier/Auto) вместо ника игрока будет написано osu!.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +- Старая версия osu! использовалась для эмуляции некоторых элементов из серии *Ouendan*, прежде чем была удалена или заменена:
```suggestion
- Старые версии osu! содержали аналоги некоторых элементов из серии *Ouendan*, прежде чем те были удалены или заменены:
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +  - [Combo fire](/wiki/Gameplay/Combo_fire) при достижении новых показателей комбо.
```suggestion
  - [Комбо-пламя](/wiki/Gameplay/Combo_fire) при достижении новых показателей комбо.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +      - Таймером является внешний круг спиннера, который меняет цвет. Вращение завершается, когда цвет круга таймера полностью изменится.
разные корявости
```suggestion
  - Первый стандартный скин, использующий версию скина v1 и называвшийся *osu!default by peppy*, выглядел почти идентично интерфейсу *Ouendan*.
    - Он был заменен более красивым скином по умолчанию, использующим версию скина v2.
  - Самым заметным отличием между скинами v1 и v2 является спиннер.
    - В скине v1 шкала прогресса спиннера постепенно заполнялась снизу вверх, как в играх серии *Ouendan*.
      - Для обратного отсчёта служил круг внутри спиннера, который сходится к его центру. Вращение завершалось, когда круг таймера достигал центра спиннера.
    - В скине v2 круг спиннера медленно увеличивается до полного размера и в конце будет светиться.
      - Для обратного отсчёта служит внешний круг спиннера, который меняет цвет. Вращение завершается, когда цвет внешнего круга полностью изменится.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +  - [Brandy - Love Fighter (FFFanatic)](https://osu.ppy.sh/beatmapsets/16), или `Brandy - Love Fighter`.
```suggestion
- Первыми тремя картами, ранкнутыми в тот же день, когда была запущена онлайн-таблица рекордов (7 октября 2007 года), были:
  - [Kenji Ninuma - DISCO PRINCE (peppy)](https://osu.ppy.sh/beatmapsets/1), или `discoprince`, которая, по всей видимости, была замапана примерно за час.
  - [Ni-Ni - 1,2,3,4, 007 \[Wipeout Series\] (MCXD)](https://osu.ppy.sh/beatmapsets/3) , или `Ni-Ni - 1,2,3,4, 007 [Wipeout Series]`.
  - [Brandy - Love Fighter (FFFanatic)](https://osu.ppy.sh/beatmapsets/16), или `Brandy - Love Fighter`.
```

2022-07-11 23:30 UTC, TicClick commented on wiki/Game_mode/osu!/ru.md
> +  - Однако загрузка непосредственно из списка карт сайта osu! соответствует текущему установленному формату именования.
```suggestion
- Примечательно, что папки со старыми картами имеют свою собственную систему именования (названия папок можно найти только в *древних* сборниках карт) и не строго следуют текущему установленному формату `{BeatmapSetID} {ArtistName} - {BeatmapName}`.
  - Тем не менее, папки карт, скачанных с веб-сайта osu!, имеют современный формат именования.
```

2022-07-30 22:28 UTC, TicClick approved these changes

2022-07-30 22:29 UTC, merged

2022-07-30 22:30 UTC, TicClick commented
на будущее: делай все правки в [отдельной ветке](https://osu.ppy.sh/wiki/ru/osu%21_wiki/Contribution_guide/Best_practices#%D0%B2%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%BA), не в `master`