[FR] Update `History_of_osu!\osu!_wiki`
ppy/osu-wiki pull request #7557
Opened 2022-06-23 18:36 UTC by Ganondorf-1

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-23 18:48 UTC, DoryanR requested changes

2022-06-23 18:48 UTC, DoryanR commented on wiki/History_of_osu!/osu!_wiki/fr.md
> +| 07/02/2018 | [La prise en charge de mots clés d'articles a été implémentée](https://github.com/ppy/osu-web/pull/2331) pour permettre de meilleurs résultats de recherche pour les articles de wiki. |
```suggestion
| 07/02/2018 | [La prise en charge de mots clés d'articles a été implémentée](https://github.com/ppy/osu-web/pull/2331) pour permettre de meilleurs résultats de recherche pour les articles du wiki. |
```

2022-06-23 19:36 UTC, TPGPL requested changes

2022-06-25 05:44 UTC, DoryanR approved these changes

2022-06-27 09:28 UTC, cl8n approved these changes

2022-06-27 09:34 UTC, merged