[RU] Add a `Community/Forum` page
ppy/osu-wiki pull request #7568
Opened 2022-06-26 21:44 UTC by Ldashy1

> ### Информация для тех, кто проверяет данный перевод

> _В случае появления каких-то проблем грамматики, читаемости, понимаемости и корректности перевода (а они по-любому будут), **настоятельно рекомендую** воспользоваться функцией предложения изменений (suggestions), чтобы я смог легко, быстро и безболезненно вносить правки в файлы перевода._

> _Также вы можете оставлять свои замечания по поводу существующих ошибок, чтобы в дальнейшем их наблюдалось намного меньше, **но рекомендую прикрепить их с своему предложению в качестве коммента** (я все равно буду читать их, несмотря на то, что мне будет больно это делать)._

2022-07-01 17:08 UTC, l43yrnt commented on wiki/Community/Forum/Modding_Queues/ru.md
> +Каждый режим игры имеет свой собственный подфорум для очередей, при этом osu! занимает основной раздел форума:
```suggestion
Каждый режим игры имеет свой собственный подфорум для очередей, при этом osu! занимает основной раздел на форуме:
```

2022-07-01 17:10 UTC, l43yrnt commented on wiki/Community/Forum/Modding_Queues/ru.md
> +- Число карт, которые могут быть приняты в данном раунде
```suggestion
- Число карт, которые могут быть приняты в данном раунде;
```

2022-07-01 17:20 UTC, l43yrnt commented on wiki/Community/Forum/ru.md
> +[**Форумы** osu!](https://osu.ppy.sh/community/forums) — это место для бесед, где сообщения группируются по темам и быстрый ответ не ожидается. Обсуждения легко найти, они вечно хранятся и могут быть
```suggestion
[**Форумы** osu!](https://osu.ppy.sh/community/forums) — это место для бесед, где сообщения группируются по темам и на них не ожидается быстрый ответ. Обсуждения легко найти, они вечно хранятся и могут быть просмотрены в любое время, что отличает их от почти мгновенных сообщений в [чате osu!](/wiki/Community/Internet_Relay_Chat). Таким образом, сообщения на форуме длиннее, содержат больше информации и обычно предоставляют больше подробностей, чем сообщения в чате.
```

2022-07-01 17:25 UTC, l43yrnt commented on wiki/Community/Forum/ru.md
> +[Модераторы](/wiki/People/The_Team/Global_Moderation_Team) — это пользователи, которые поддерживают форум в чистоте и порядке, а также отвечают на относящиеся к этому вопросы. Модераторы могут редакт
```suggestion
[Модераторы](/wiki/People/The_Team/Global_Moderation_Team) — это пользователи, которые поддерживают форум в чистоте и порядке, а также отвечают на относящиеся к нему вопросы. Модераторы могут редактировать или удалять неуместные посты или топики, закреплять темы и перемещать их между различными форумами, а также временно лишать нарушителей возможности оставлять посты, накладывая на них [Сайленс](/wiki/Silence).
```

2022-07-11 23:31 UTC, TicClick commented
забегу на неделе

2022-07-31 15:26 UTC, TicClick requested changes
основное замечание к переводу: очень много предложений, которые звучат нехарактерно для русского языка. они либо имеют неестественную структуру или обороты, либо чересчур усложнены.

если ты планируешь и дальше переводить вики, тебе нужно либо чаще видеть предложения, написанные грамотным русским языком (читать больше книжек, газет или журналов), либо научиться применять знания на практике. не бойся переписывать предложения и использовать другие синтаксические конструкции, которыми пользуются остальные [живые человеческие особи](https://m.media-amazon.com/images/M/MV5BMWE5NTRmMDctMDBlZC00N2JmLWFmYzUtMDEwMTU2MmUyZTY5XkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_UY317_CR22,0,214,317_AL_.jpg) в этой планетной системе.

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +Некоторые пользователи могут принадлежать к одной или нескольким группам пользователей, основываясь на своих задачах в сообществе, правах доступа или прошлой активности. Полный список групп пользоват
так предложение менее перегружено
```suggestion
Некоторые пользователи, в зависимости от своих общественных ролей, прав доступа или прошлой деятельности, могут состоять в отдельным группам. Полный список групп можно найти здесь: [Команда § Группы пользователей](/wiki/People/The_Team#группы-пользователей).
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +Вдобавок к значкам группы пользователей, получаемым за членство в группе, пользователи могут получить [пользовательские заголовки](/wiki/User_title), отображаемые под аватаром в каждом их посте.
```suggestion
Помимо значков, показывающих принадлежность к различным группам, пользователи могут иметь [титулы](/wiki/User_title), отображаемые под аватаром в каждом сообщении.
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +*См. также: [Донесение о неподобающем поведении § Форум](/wiki/Reporting_bad_behaviour#форум)*
```suggestion
*См. также: [Жалобы на плохое поведение § Форум](/wiki/Reporting_bad_behaviour#форум)*
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +[Модераторы](/wiki/People/The_Team/Global_Moderation_Team) — это пользователи, которые поддерживают форум в чистоте и порядке, а также отвечают на относящиеся к нему вопросы. Модераторы могут редакти
```suggestion
[Модераторы](/wiki/People/The_Team/Global_Moderation_Team) — это пользователи, которые поддерживают форум в чистоте и порядке, а также отвечают на относящиеся к нему вопросы. Модераторы могут редактировать или удалять неуместные посты или топики, закреплять темы и перемещать их в другие форумы, а также временно лишать нарушителей возможности общаться, выдавая им [сайленс](/wiki/Silence).
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +Некоторые форумы имеют различные цели, которые не ограничиваются обсуждением. Следовательно, они содержат дополнительные правила и/или технические возможности.
ужасное предложение
```suggestion
Некоторые форумы предназначены не только для общения и, как следствие, имеют дополнительные правила и/или технические возможности.
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/Feature_Requests/ru.md
> +# Запросы на добавление функций
не надо переводить названия форумов в заголовках страниц (ни здесь, ни в остальных статьях)
```suggestion
# Feature Requests
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/Help/ru.md
> +# Помощь
```suggestion
# Help
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/Modding_Queues/ru.md
> +# Очереди на моддинг
```suggestion
# Modding Queues
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +- [Заброшенная пустошь](/wiki/Community/Forum/Abandoned_Wasteland): хранилище для бесполезных топиков.
как я уже упоминал, лучше оставлять оригинальное название
```suggestion
- [Help](/wiki/Community/Forum/Help) (помощь): техподдержка от [команды поддержки](/wiki/People/The_Team/Support_Team) и обычных пользователей.
- [Feature Requests](/wiki/Community/Forum/Feature_Requests): предложения по развитию osu!.
- [Modding Queues](/wiki/Community/Forum/Modding_Queues): ревью карт от других мапперов и моддеров.
- [Off-Topic](/wiki/Community/Forum/Off-Topic): место для не совсем логичных обсуждений.
- [Abandoned Wasteland](/wiki/Community/Forum/Abandoned_Wasteland): хранилище для бесполезных тем.
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +Кроме того, существуют и другие форумы, подобные Заброшенной пустоши, которые обслуживают технические или управленческие цели и поэтому скрыты от посторонних глаз.
```suggestion
Помимо вышеперечисленного, на сайте существует ряд форумов, аналогичных Abandoned Wasteland. Они служат техническим или административным целям и потому скрыты от посторонних глаз.
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +- Интеграцию с [Beatmap Submission System](/wiki/Submission)
```suggestion
- Интеграцию с [системой публикации карт](/wiki/Submission)
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +- Форумы [Помощь](/wiki/Community/Forum/Help) и [Запросы на добавление функций](/wiki/Community/Forum/Feature_Requests)
```suggestion
- Форумы [Help](/wiki/Community/Forum/Help) и [Feature Requests](/wiki/Community/Forum/Feature_Requests)
```

2022-07-31 15:26 UTC, TicClick commented on wiki/Community/Forum/ru.md
> +После запуска нового сайта osu! phpBB был постепенно заменен на пользовательский движок форума, который используется и по сей день.
```suggestion
После запуска нового сайта osu! phpBB был постепенно заменен на самописный форумный движок, который используется и по сей день.
```

2022-08-03 14:39 UTC, Ldashy1 commented on wiki/Community/Forum/Off-Topic/ru.md
> +**Неделя старых аватаров** была ежегодным событием в честь наступающего Нового Года. Каждый год, 28 декабря, люди меняли свой аватар на один из своих старых на одну неделю. Это напоминало завсегдатая
да, ты прав, как я не задумался об этом)))

2022-08-03 14:43 UTC, Ldashy1 commented on wiki/Community/Forum/Off-Topic/ru.md
> +9 июня 2017 года [Ephemeral](https://osu.ppy.sh/users/102335) ввел несколько иную версию традиции в [Правила оффтопа](https://osu.ppy.sh/community/forums/topics/604424), потребовав от людей размещать
ауч, как-то мне неловко за себя стало) странно, что на английском языке это помечается как "очистка", а не обновление, ведь обновление лучше и понятнее звучит.

2022-08-03 14:44 UTC, Ldashy1 commented on wiki/Community/Forum/Off-Topic/ru.md
> +### Житель
проглядел этот термин, прошу прощения)

2022-08-03 14:45 UTC, Ldashy1 commented on wiki/Community/Forum/Off-Topic/ru.md
> +Поскольку подфорум Off-Topic состоит в основном из одних и тех же завсегдатаев, общающихся между собой в тредах, каждый знаком друг с другом. Тех, кто остается здесь достаточно долго, чтобы считаться
я кстати задумывался о таком варианте, но меня судя по всему не туда повернуло)

2022-08-03 14:48 UTC, Ldashy1 commented on wiki/Community/Forum/Off-Topic/ru.md
> +**Удаление от темы** — частое явление в Оффтопе, поскольку он по своей природе является "оффтопом". Это означает, что тред, созданный с учетом определенной темы, не может оставаться в рамках этой тем
тут даже спорить не буду, звучит намного лучше)

2022-08-03 14:59 UTC, Ldashy1 commented on wiki/Community/Forum/ru.md
> +  - подфорум
буду знать.

2022-08-03 21:02 UTC, TicClick reviewed
(Russian) added fixups and fixed mishaps

2022-08-03 21:04 UTC, TicClick approved these changes

2022-08-03 21:04 UTC, merged