[FR] Add `Profile_badge`
ppy/osu-wiki pull request #7579
Opened 2022-06-30 19:59 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-06-30 20:19 UTC, Ganondorf-1 requested changes

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +# Badge de Profil
```suggestion
# Badge de profil
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +*Pour les règles concernant l'utilisation de badges en guise de récompense de tournois, voir: [Support aux tournois officiels § Badges de profil](/wiki/Tournaments/Official_support#profile-badges)*
```suggestion
*Pour les règles concernant l'utilisation de badges en guise de récompenses de tournois, voir : [Support officiel aux tournois § Badges de profil](/wiki/Tournaments/Official_support#profile-badges)*
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +![Capture d'ecran des badges de HappyStick sur le site web](img/HappyStick.png "Les badges de profil s'affichent sous l'avatar et le nom d'utilisateur sur le site web.")
```suggestion
![Capture d'écran des badges de HappyStick sur le site web](img/HappyStick.png "Les badges de profil s'affichent sous l'avatar et le nom d'utilisateur sur le site web.")
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +**Badges de profil** (communément appelés *badges*.) sont de petits graphiques sur les pages de profil de l'utilisateur attribués pour diverses réalisations. Ils sont couvent donnés sous forme de réc
```suggestion
Les **badges de profil** (communément appelés *badges*) sont de petits éléments graphiques sur les pages de profil de l'utilisateur attribués pour diverses réalisations. Ils sont souvent donnés sous forme de récompenses de [tournois](/wiki/Tournaments) et [concours](/wiki/Contests), mais ont d'autres utilisations, comme des récompenses pour des [Contributeurs de la communauté](/wiki/People/Community_Contributors), les [Beatmap Spotlights](/wiki/Beatmap_Spotlights#rewards), et une adhésion prolongée à un groupe.
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +## Classement du tournois
```suggestion
## Seeding des tournois
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +*Page principal: [Classement pondéré par badges](/wiki/Tournaments/Badge-weighted_seeding)*
```suggestion
*Page principale : [Badge-weighted seeding](/wiki/Tournaments/Badge-weighted_seeding)*
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +Dans le [client](/wiki/Client) et sur le site web, les badges sont simplement décoratifs. Cependant, à cause des récompenses de [tournois](/wiki/Tournaments) sous forme de badges montrant le niveau d
```suggestion
Dans le [client](/wiki/Client) et sur le site web, les badges sont simplement décoratifs. Cependant, à cause des récompenses de [tournois](/wiki/Tournaments) sous forme de badges montrant le niveau des joueurs, plusieurs tournois ont adopté une méthode de [seeding](https://en.wikipedia.org/wiki/Seed_(sports)) qui prend en compte le nombre de badges qu'a le joueur, communément appelé [Badge-weighted seeding](/wiki/Tournaments/Badge-weighted_seeding) (BWS).
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +![Capture d'écran des badges de Uan sur l'ancien site web](img/Uan.png "Sur l'ancien site web, les badges de profiles s'empilait sous le nom d'utilisateur et son titre")
```suggestion
![Capture d'écran des badges de Uan sur l'ancien site web](img/Uan.png "Sur l'ancien site web, les badges de profil s'empilaient sous le nom d'utilisateur et son titre")
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +[flag_PL]: /wiki/shared/flag/PL.gif "Poland"
```suggestion
[flag_PL]: /wiki/shared/flag/PL.gif "Pologne"
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +[flag_US]: /wiki/shared/flag/US.gif "United States"
```suggestion
[flag_US]: /wiki/shared/flag/US.gif "États-Unis"
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +- Les deux premiers badges ont été attribué à ![][flag_PL] [niedzwiedz1124](https://osu.ppy.sh/users/9610) et ![][flag_PL] [White Wolf](https://osu.ppy.sh/users/39828) le 6 Septembre, 2009, pour avoi
```suggestion
- Les deux premiers badges ont été attribués à ![][flag_PL] [niedzwiedz1124](https://osu.ppy.sh/users/9610) et à ![][flag_PL] [White Wolf](https://osu.ppy.sh/users/39828) le 6 septembre 2009, pour avoir [gagné *le Tag Tournament*](https://osu.ppy.sh/community/forums/topics/17169).
```

2022-06-30 20:19 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +Un effet secondaire de cette méthode de mise en page était que la hauteur par défaut, non étendue, des pages des utilisateurs pouvait être augmentée en gagnant plus de badges.  Bien qu'involontaire,
```suggestion
Un effet secondaire de cette méthode de mise en page était que la hauteur par défaut, non étendue, des pages des utilisateurs pouvait être augmentée en gagnant plus de badges. Bien qu'involontaire, cette méthode est devenue une blague récurrente dans la communauté des tournois.<!-- More example userpages beyond Toy would be nice, else "running gag" doesn't have a source. -clayton --> ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) a montré cela dans [un Tweet populaire](https://twitter.com/droombs/status/1036050610687074304), exposant son record du plus grand nombre de badges gagnés au moment de la publication de l'article.
```

2022-07-01 07:56 UTC, Walavouchey commented on wiki/Community/Profile_badge/fr.md
> +::: Boite à info
```suggestion
::: Infobox
```

2022-07-01 07:56 UTC, Walavouchey commented on wiki/Community/Profile_badge/fr.md
> +![](https://assets.ppy.sh/profile-badges/tagwinner.png "Badge de première place du tournoi Tag")
```suggestion
![](https://assets.ppy.sh/profile-badges/tagwinner.png "Badge de première place du Tag Tournament")
```

2022-07-01 07:56 UTC, Walavouchey commented on wiki/Community/Profile_badge/fr.md
> +Un effet secondaire de cette méthode de mise en page était que la hauteur par défaut, non étendue, des pages des utilisateurs pouvait être augmentée en gagnant plus de badges. Bien qu'involontaire, c
```suggestion
Un effet secondaire de cette méthode de mise en page était que la hauteur par défaut, non étendue, des pages des utilisateurs pouvait être augmentée en gagnant plus de badges. Bien qu'involontaire, cette méthode est devenue une blague récurrente dans la communauté des tournois. ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) a montré cela dans [un Tweet populaire](https://twitter.com/droombs/status/1036050610687074304), exposant son record du plus grand nombre de badges gagnés au moment de la publication de l'article.
```

2022-07-01 09:18 UTC, Pisapou commented on wiki/Community/Profile_badge/fr.md
> +Un effet secondaire de cette méthode de mise en page était que la hauteur par défaut, non étendue, des pages des utilisateurs pouvait être augmentée en gagnant plus de badges. Bien qu'involontaire, c
```suggestion
Un effet secondaire de cette méthode de mise en page était que la hauteur par défaut, non étendue, des pages des utilisateurs pouvait être augmentée en gagnant plus de badges. Bien qu'involontaire, cette méthode est devenue une blague récurrente dans la communauté des tournois. ![][flag_US] [Toy](https://osu.ppy.sh/users/2757689) a montré cela dans [un Tweet populaire](https://twitter.com/droombs/status/1036050610687074304), exposant son record du plus grand nombre de badges gagnés au moment de la publication de l'article.

```

2022-07-01 18:26 UTC, Ganondorf-1 requested changes

2022-07-01 18:26 UTC, Ganondorf-1 commented on wiki/Community/Profile_badge/fr.md
> +- Les deux premiers badges ont été attribués à ![][flag_PL] [niedzwiedz1124](https://osu.ppy.sh/users/9610) et à ![][flag_PL] [White Wolf](https://osu.ppy.sh/users/39828) le 6 septembre 2009, pour av
```suggestion
- Les deux premiers badges ont été attribués à ![][flag_PL] [niedzwiedz1124](https://osu.ppy.sh/users/9610) et à ![][flag_PL] [White Wolf](https://osu.ppy.sh/users/39828) le 6 septembre 2009, pour avoir [gagné le *Tag Tournament*](https://osu.ppy.sh/community/forums/topics/17169).

```

2022-07-04 13:55 UTC, Biokax submitted a review, later dismissed

2022-07-08 04:05 UTC, cl8n approved these changes

2022-07-08 04:07 UTC, merged