[FR] Update storyboard section
ppy/osu-wiki pull request #7585
Opened 2022-07-01 09:00 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Just updating all files by adding tables for values like in english version.

2022-07-05 13:48 UTC, Y0hananas commented on wiki/Storyboard/Scripting/Audio/fr.md
> +- `<time>` est l'heure à laquelle le son doit commencer à être joué.
```suggestion
- `<time>` est le moment auquel le son doit commencer à être joué.

```

2022-07-05 13:52 UTC, Y0hananas commented on wiki/Storyboard/Scripting/Audio/fr.md
> +Par exemple, pour jouer un (courte !) fichier musicale lorsque le joueur obtient une bonne fin sur la beatmap (par exemple, fin dans l'état Pass), puis jouer un effet sonore d'explosion dans le cadre
```suggestion
Par exemple, pour jouer un fichier musical (court !) lorsque le joueur obtient une bonne fin sur la beatmap (par exemple, fin dans l'état Pass), puis jouer un effet sonore d'explosion dans le cadre de la scène :

```

2022-07-05 20:23 UTC, Pisapou commented
> We have a Trello for the french translation, the next time pick a file that is not under work by someone else https://trello.com/b/im2TIIdN/suivi-des-traductions-de-losu-wiki For talking about the translation we use the #traduction of the osu! french discord https://discord.gg/vfrHNQZ

@DoryanR Je n'avais pas la connaissance du trello et m'excuse donc d'avoir traduis cette section alors que tu le comptais faire. J'espère que ça te dérange pas trop :x

2022-07-10 08:09 UTC, DoryanR commented
> > We have a Trello for the french translation, the next time pick a file that is not under work by someone else https://trello.com/b/im2TIIdN/suivi-des-traductions-de-losu-wiki For talking about the translation we use the #traduction of the osu! french discord https://discord.gg/vfrHNQZ
> 
> @DoryanR Je n'avais pas la connaissance du trello et m'excuse donc d'avoir traduis cette section alors que tu le comptais faire. J'espère que ça te dérange pas trop :x

Ça va, si tu n'était pas au courant je peut pas t'en vouloir, maintenant que tu sais, évite au maximum, ça risque de créer des conflits pour rien après.

2022-07-10 08:22 UTC, DoryanR requested changes

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Audio/fr.md
> +
```suggestion
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Audio/fr.md
> +- `<layer_num>` est une valeur *numérique* correspondant à la couche sur laquelle vous voulez que le son soit :
```suggestion
- `<layer_num>` est une valeur *numérique* correspondant à la couche sur laquelle vous voulez que le son soit. Les valeurs valides sont énumérées ci-dessous.
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Audio/fr.md
> +  - 3 - Premier plan
```suggestion
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Audio/fr.md
> +Les valeurs valides pour les couches sont:
```suggestion
Les valeurs valides pour les couches sont :
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Audio/fr.md
> +
```suggestion

```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Cheat_Sheet/fr.md
> +| Valeur | Layer |
```suggestion
| Valeur | Couche |
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Cheat_Sheet/fr.md
> +| Valeur | Origin |
```suggestion
| Valeur | Origine |
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Cheat_Sheet/fr.md
> +| Event type | Description |
```suggestion
| Type d'événement | Description |
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Cheat_Sheet/fr.md
> +| Easing | Description |
```suggestion
| Assouplissement | Description |
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Commands/fr.md
>  - `(easing)` indique si la commande doit "accélérer". Voir [Easing Functions Cheat Sheet](http://easings.net). Les valeurs valides sont :
```suggestion
- `(easing)` indique si la commande doit "accélérer". Voir [Easing Functions Cheat Sheet](http://easings.net). Les valeurs valides sont énumérées ci-dessous.
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Commands/fr.md
> +Les valeurs valides pour le easing sont :
```suggestion
Les valeurs valides pour l'assouplissement sont :
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
>  - `(layer)` est la **[couche](/wiki/Storyboard/Scripting/General_Rules) sur laquelle l'objet apparaît.** Les valeurs valides sont :
```suggestion
- `(layer)` est la **[couche](/wiki/Storyboard/Scripting/General_Rules) sur laquelle l'objet apparaît.** Les valeurs valides sont énumérées ci-dessous.
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
>  - `(origin)` est l'endroit de **l'image où osu! doit considérer que l'origine de l'image (coordonnée) se trouve.** Cela affecte les valeurs (x) et (y), ainsi que plusieurs autres comportements spécif
```suggestion
- `(origin)` est l'endroit de **l'image où osu! doit considérer que l'origine de l'image (coordonnée) se trouve.** Cela affecte les valeurs (x) et (y), ainsi que plusieurs autres comportements spécifiques à la commande. Par exemple, si vous choisissez (origin) = Haut-Gauche, les valeurs (x) et (y) détermineront l'emplacement du coin supérieur gauche de l'image à l'écran. Les valeurs valides sont énumérées ci-dessous (notez l'orthographe "Centre" et non "Center"). 
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
> +Les valeurs valides pour le layer sont:
```suggestion
Les valeurs valides pour les couches sont :
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
> +Les valeurs valides pour l'origin sont:
```suggestion
Les valeurs valides pour l'origine sont:
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
> +| Valeur | Layer |
```suggestion
| Valeur | Couche |
```

2022-07-10 08:22 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
> +| Valeur | Origin |
```suggestion
| Valeur | Origine |
```

2022-07-10 08:46 UTC, Pisapou commented
> > > We have a Trello for the french translation, the next time pick a file that is not under work by someone else https://trello.com/b/im2TIIdN/suivi-des-traductions-de-losu-wiki For talking about the translation we use the #traduction of the osu! french discord https://discord.gg/vfrHNQZ
> > 
> > 
> > @DoryanR Je n'avais pas la connaissance du trello et m'excuse donc d'avoir traduis cette section alors que tu le comptais faire. J'espère que ça te dérange pas trop :x
> 
> Ça va, si tu n'était pas au courant je peut pas t'en vouloir, maintenant que tu sais, évite au maximum, ça risque de créer des conflits pour rien après.

oui bien sûr, encore désolé

2022-07-10 17:55 UTC, DoryanR commented on wiki/Storyboard/Scripting/Audio/fr.md
> +# Échantillons audio d'un storyboard
Same problems as on the other PR, you have to change the line type from `CTRL` to `LF`, and also add a line at the end of the document.

2022-07-11 10:51 UTC, DoryanR requested changes

2022-07-11 10:51 UTC, DoryanR commented on wiki/Storyboard/Scripting/Commands/fr.md
> +| 0 | Linéaire : pas d'easing |
```suggestion
| 0 | Linéaire : pas d'assouplissement |
```

2022-07-11 10:51 UTC, DoryanR commented on wiki/Storyboard/Scripting/Commands/fr.md
> +| 1 | Easing Out: les changements sont rapides au début, mais ralentissent vers la fin |
```suggestion
| 1 | Easing Out : les changements sont rapides au début, mais ralentissent vers la fin |
```

2022-07-11 10:51 UTC, DoryanR commented on wiki/Storyboard/Scripting/Commands/fr.md
> +| 2 | Easing In: les changements se produisent lentement au début, mais s'accélèrent vers la fin |
```suggestion
| 2 | Easing In : les changements se produisent lentement au début, mais s'accélèrent vers la fin |
```

2022-07-11 10:51 UTC, DoryanR commented on wiki/Storyboard/Scripting/Objects/fr.md
> +- `(origin)` est l'endroit de **l'image où osu! doit considérer que l'origine de l'image (coordonnée) se trouve.** Cela affecte les valeurs (x) et (y), ainsi que plusieurs autres comportements spécif
```suggestion
- `(origin)` est l'endroit de **l'image où osu! doit considérer que l'origine de l'image (coordonnée) se trouve.** Cela affecte les valeurs (x) et (y), ainsi que plusieurs autres comportements spécifiques à la commande. Par exemple, si vous choisissez (origin) = Haut-Gauche, les valeurs (x) et (y) détermineront l'emplacement du coin supérieur gauche de l'image à l'écran. Les valeurs valides sont énumérées ci-dessous. 
```
Pas utile à garder

2022-07-12 10:36 UTC, DoryanR submitted a review, later dismissed

2022-07-12 23:00 UTC, cl8n approved these changes

2022-07-12 23:03 UTC, merged