[FR] add `Tournaments/Badge-weighted_seeding`
ppy/osu-wiki pull request #7586
Opened 2022-07-01 10:58 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-01 11:04 UTC, Pisapou commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +**Badge-weighted seeding** (***BWS***) est un [seeding](https://en.wikipedia.org/wiki/Seed_(sports)) de [tournois](/wiki/Tournaments) et un système de restrictions qui prend en compte tous les [Badge
```suggestion
Le **Badge-weighted seeding** (***BWS***) est un [seeding](https://en.wikipedia.org/wiki/Seed_(sports)) de [tournois](/wiki/Tournaments) et un système de restrictions qui prend en compte tous les [Badges de Profil](/wiki/Community/Profile_badge) de chaque joueur pour qu'ils comptent autant que leur [rang global](/wiki/Ranking#performance-points-ranking). Conçu à l'origine par ![][flag_US] [DigitalHypno](https://osu.ppy.sh/users/4384207), l'objectif de ce système était de "répartir plus précisément les joueurs et d'appliquer les restrictions de rang en fonction des badges de tournoi des joueurs",[^hippo-cup-bws] par rapport à la méthode de classement plus standard qui utilise directement le classement global des joueurs.

```

2022-07-01 11:04 UTC, Pisapou commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +Le principe de la BWS est que les joueurs se voient attribuer un meilleur classement s'ils ont gagné des badges pour avoir participé à des tournois dans le passé. De cette façon, les joueurs ne reste
```suggestion
Le principe du BWS est que les joueurs se voient attribuer un meilleur classement s'ils ont gagné des badges pour avoir participé à des tournois dans le passé. De cette façon, les joueurs ne resteront pas indéfiniment au même rang s'ils sont performants en tournois, par rapport à d'autres joueurs de même rang.[^digitalhypno-discord-1][^digitalhypno-discord-2] Dans un ensemble de tournois qui utilisent tous le BWS, on s'attend à ce que les joueurs qui commencent à des rangs similaires tendent vers des têtes de série BWS qui reflètent mieux leur probabilité de gagner des matchs contre des joueurs de même rang.[^digitalhypno-discord-3][^digitalhypno-discord-4]

```

2022-07-01 11:04 UTC, Pisapou commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +La méthode originale et la plus courante pour calculer les seeds des joueurs dans la BWS est la fonction de décroissance bornée suivante :
```suggestion
La méthode originale et la plus courante pour calculer les seeds des joueurs avec le BWS est la fonction de décroissance bornée suivante :

```

2022-07-01 11:04 UTC, Pisapou commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +- `badge_count` (≥ 0): Nombre de badges sur le profil du joueur qui ont été gagnés en tant que prix pour des tournois précédents du même [Modes de jeu](/wiki/Game_mode)
```suggestion
- `badge_count` (≥ 0): Nombre de badges sur le profil du joueur qui ont été gagnés en tant que prix pour des tournois précédents du même [modes de jeu](/wiki/Game_mode)

```

2022-07-01 11:04 UTC, Pisapou commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +- `global_rank` (≥ 1): [Classement des points de performance](/wiki/Ranking#performance-points-ranking) du joueur sur le classement global correspondant au [Modes de jeu](/wiki/Game_mode) du tournois
```suggestion
- `global_rank` (≥ 1): [Classement des points de performance](/wiki/Ranking#performance-points-ranking) du joueur sur le classement global correspondant au même [modes de jeu](/wiki/Game_mode) du tournois.

```

2022-07-01 11:04 UTC, Pisapou commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +Certains tournois varient leur mise en œuvre de la BWS en utilisant une fonction différente,[^brtt-bws] mais toutes partagent les mêmes propriétés décrites ci-dessus.
```suggestion
Certains tournois varient leur mise en œuvre du BWS en utilisant une fonction différente,[^brtt-bws] mais toutes partagent les mêmes propriétés décrites ci-dessus.

```

2022-07-01 11:04 UTC, Pisapou commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +- Les BWS ne peuvent être mises à jour que lorsque les joueurs reçoivent des badges, et les badges ne sont généralement attribués qu'en tant que prix de première place à la fin des tournois. Ainsi, l
```suggestion
- Les BWS ne peuvent être mises à jour que lorsque les joueurs reçoivent des badges, et les badges ne sont généralement attribués qu'en tant que prix de première place à la fin des tournois. Ainsi, le processus d'établissement des joueurs dans des seeds réprentatives de leur niveau peut être très lent.

```

2022-07-02 18:27 UTC, cl8n commented
please leave the second task unchecked until another french speaker reviews the PR

2022-07-05 11:27 UTC, Biokax requested changes

2022-07-05 11:27 UTC, Biokax commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +  - tournament seeding
```suggestion
  - tournament seeding
  - système de pondération des badges
  - restriction de rang
  - rang restreint
  - seed de tournoi
  - seeding de tournoi
```

2022-07-05 13:43 UTC, Y0hananas commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +Le **Badge-weighted seeding** (***BWS***) est un [seeding](https://en.wikipedia.org/wiki/Seed_(sports)) de [tournois](/wiki/Tournaments) et un système de restrictions qui prend en compte tous les [Ba
```suggestion
Le **Badge-weighted seeding** (***BWS***) est un [seeding](https://en.wikipedia.org/wiki/Seed_(sports)) de [tournois](/wiki/Tournaments) et un système de restrictions qui prend en compte tous les [Badges de Profil](/wiki/Community/Profile_badge) de chaque joueur pour qu'ils comptent autant que leur [rang global](/wiki/Ranking#performance-points-ranking). Conçu à l'origine par ![][flag_US] [DigitalHypno](https://osu.ppy.sh/users/4384207), l'objectif de ce système était de "répartir plus précisément les joueurs et d'appliquer les restrictions de rang en fonction de leurs badges de tournoi",[^hippo-cup-bws] par rapport à la méthode de classement plus standard qui utilise directement leur classement global.

```

2022-07-05 13:43 UTC, Y0hananas commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +Le principe du BWS est que les joueurs se voient attribuer un meilleur classement s'ils ont gagné des badges pour avoir participé à des tournois dans le passé. De cette façon, les joueurs ne resteron
```suggestion
Le principe du BWS est que les joueurs se voient attribuer un meilleur classement s'ils ont gagné des badges pour avoir participé à des tournois dans le passé. De cette façon, les joueurs ne resteront pas indéfiniment au même rang s'ils sont performants en tournois par rapport à d'autres joueurs de même rang.[^digitalhypno-discord-1][^digitalhypno-discord-2] Dans un ensemble de tournois qui utilisent tous le BWS, on s'attend à ce que les joueurs qui commencent à des rangs similaires tendent vers des têtes de série BWS qui reflètent mieux leur probabilité de gagner des matchs contre des joueurs de même rang.[^digitalhypno-discord-3][^digitalhypno-discord-4]

```

2022-07-05 13:43 UTC, Y0hananas commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +- `global_rank` (≥ 1): [Classement des points de performance](/wiki/Ranking#performance-points-ranking) du joueur sur le classement global correspondant au même [modes de jeu](/wiki/Game_mode) du tou
```suggestion
- `global_rank` (≥ 1): [Classement des points de performance](/wiki/Ranking#performance-points-ranking) du joueur sur le classement global correspondant au même [modes de jeu](/wiki/Game_mode) du tournoi.

```

2022-07-05 13:43 UTC, Y0hananas commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +- Les seed du BWS sont toujours inférieures ou égales aux `global_rank`. Ils sont égaux si le joueur n'a pas de badges.
```suggestion
- Les seeds du BWS sont toujours inférieures ou égales aux `global_rank`. Ils sont égaux si le joueur n'a pas de badges.

```

2022-07-05 13:43 UTC, Y0hananas commented on wiki/Tournaments/Badge-weighted_seeding/fr.md
> +- Les BWS ne peuvent être mises à jour que lorsque les joueurs reçoivent des badges, et les badges ne sont généralement attribués qu'en tant que prix de première place à la fin des tournois. Ainsi, l
```suggestion
- Les BWS ne peuvent être mises à jour que lorsque les joueurs reçoivent des badges, et les badges ne sont généralement attribués qu'en tant que prix de première place à la fin des tournois. Ainsi, le processus d'établissement des joueurs dans des seeds représentatives de leur niveau peut être très lent.

```

2022-07-08 05:22 UTC, cl8n approved these changes

2022-07-08 05:23 UTC, merged