[FR] Add "Featured Artist playlists"
ppy/osu-wiki pull request #7604
Opened 2022-07-05 12:06 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-05 12:08 UTC, Pisapou commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +Tous les mois, de nouvelles **playlists d'Artistes Associés** sont publiés sur [osu!(lazer)](https://github.com/ppy/osu/releases) mettant en valeurs les créations d' [Artistes Associés](/wiki/Feature
```suggestion
Tous les mois, de nouvelles **playlists d'Artistes Associés** sont publiés sur [osu!(lazer)](https://github.com/ppy/osu/releases) mettant en valeurs les créations d'[Artistes Associés](/wiki/Featured_Artists) dans tous les [modes de jeu](/wiki/Game_mode). Les playlists ne sont pas soumises à un format strict, ainsi, les paramètres, les sélections de beatmaps, et les critères d'attribution des prix varient chaque mois.

```

2022-07-05 12:08 UTC, Pisapou commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +Les meilleurs joueurs de chaque playlist de Featured Artist sont récompensés par des badges de profil spécifiques au mode. Les critères exacts pour les meilleurs joueurs varient selon la liste de lec
```suggestion
Les meilleurs joueurs de chaque playlist d'Artiste Associé sont récompensés par des badges de profil spécifiques au mode. Les critères exacts pour les meilleurs joueurs varient selon la liste de lecture.

```

2022-07-05 13:14 UTC, Y0hananas commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +Tous les mois, de nouvelles **playlists d'Artistes Associés** sont publiés sur [osu!(lazer)](https://github.com/ppy/osu/releases) mettant en valeurs les créations d'[Artistes Associés](/wiki/Featured
```suggestion
Tous les mois, de nouvelles **playlists d'Artistes Associés** sont publiées sur [osu!(lazer)](https://github.com/ppy/osu/releases) mettant en valeur les créations d'[Artistes Associés](/wiki/Featured_Artists) dans tous les [modes de jeu](/wiki/Game_mode). Les playlists ne sont pas soumises à un format strict, ainsi, les paramètres, les sélections de beatmaps et les critères d'attribution des prix varient chaque mois.

```

2022-07-05 13:14 UTC, Y0hananas commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [Hidden (HD)](/wiki/Game_modifier/Hidden) mod requis
```suggestion
- [Hidden (HD)](/wiki/Game_modifier/Hidden) mode requis

```

2022-07-05 13:14 UTC, Y0hananas commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) mods libres
```suggestion
- [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) modes libres

```

2022-07-05 13:14 UTC, Y0hananas commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [Hidden (HD)](/wiki/Game_modifier/Hidden), [Hard Rock (HR)](/wiki/Game_modifier/Hard_Rock), [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) mods libres
```suggestion
- [Hidden (HD)](/wiki/Game_modifier/Hidden), [Hard Rock (HR)](/wiki/Game_modifier/Hard_Rock), [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) modes libres

```

2022-07-06 11:47 UTC, Biokax requested changes

2022-07-06 11:47 UTC, Biokax commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +Les meilleurs joueurs de chaque playlist d'Artiste Associé sont récompensés par des badges de profil spécifiques au mode. Les critères exacts pour les meilleurs joueurs varient selon la liste de lect
```suggestion
Les meilleurs joueurs de chaque playlist d'Artiste Associé sont récompensés par des badges de profil spécifiques au mode. Les critères exacts pour les meilleurs joueurs varient selon la playlist.

```

2022-07-06 11:47 UTC, Biokax commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [Hidden (HD)](/wiki/Game_modifier/Hidden) mode requis
```suggestion
- [Hidden (HD)](/wiki/Game_modifier/Hidden) mod requis

```

2022-07-06 11:47 UTC, Biokax commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [Hidden (HD)](/wiki/Game_modifier/Hidden), [Hard Rock (HR)](/wiki/Game_modifier/Hard_Rock), [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) modes libres
```suggestion
- [Hidden (HD)](/wiki/Game_modifier/Hidden), [Hard Rock (HR)](/wiki/Game_modifier/Hard_Rock), [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) options mods libres

```

2022-07-06 11:47 UTC, Biokax commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) modes libres
```suggestion
- [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) options modes libres

```

2022-07-06 11:48 UTC, Biokax commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) modes libres
j'ai un doute sur celui là car freemod n'a pas l'air traduis sur les autres pages

2022-07-10 08:06 UTC, DoryanR requested changes
In this PR I have the impression that there is a [problem with the formatting of the lines](https://github.com/ppy/osu-wiki/runs/7263466364?check_suite_focus=true) (changing them from (`\r\n`) to (`\n`) in your editor).

For the other errors I have made the necessary corrections normally.

2022-07-10 09:10 UTC, DoryanR commented
Personally I was putting `Featured Artists` everywhere, because it seemed right to leave it like that, so I think we can leave it like that (since on the site, it was left like that too)

![brave_Sml93MGArT](https://user-images.githubusercontent.com/55928127/178138561-01b5745d-1d3d-403f-a95c-04a45b3ca4be.png)

As for this article, I'll take care of making the change, I remember translating it at the time.

2022-07-10 14:42 UTC, DoryanR requested changes
To fix the rest of the CI errors :

2022-07-10 14:42 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +
```suggestion
```

2022-07-10 14:42 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +
```suggestion
```

2022-07-10 14:42 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +
```suggestion
```

2022-07-11 10:46 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [Hidden (HD)](/wiki/Game_modifier/Hidden) mod requis
```suggestion
- Mod [Hidden (HD)](/wiki/Game_modifier/Hidden) requis
```

2022-07-11 10:47 UTC, DoryanR commented on wiki/Featured_Artists/Featured_Artist_playlists/fr.md
> +- [Hidden (HD)](/wiki/Game_modifier/Hidden), [Hard Rock (HR)](/wiki/Game_modifier/Hard_Rock), [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) options mods lib
```suggestion
- Options des mods [Hidden (HD)](/wiki/Game_modifier/Hidden), [Hard Rock (HR)](/wiki/Game_modifier/Hard_Rock), [No Fail (NF)](/wiki/Game_modifier/No_Fail) et [Mirror (MR)](/wiki/Game_modifier/Mirror) libres
```

2022-07-12 10:37 UTC, DoryanR submitted a review, later dismissed

2022-07-12 11:41 UTC, Biokax submitted a review, later dismissed

2022-07-12 22:46 UTC, cl8n approved these changes

2022-07-12 22:47 UTC, merged

2022-07-12 22:47 UTC, cl8n commented
when applying suggestions, try to name the commit something more descriptive of the changes made