[FR] Update `Gameplay` section (`/Score`,`/Judgment/osu!`,`/Score/ScoreV1/osu!`)
ppy/osu-wiki pull request #7605
Opened 2022-07-05 13:32 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-05 14:44 UTC, Y0hananas commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un cercle peut prednre les valeurs 300, 100, ou 50 selon la précision du timing du joueur lorsqu'il clique dessus. Les intervalles de temps utilisés pour déterminer le résultat concret d'un cercle
```suggestion
- Un cercle peut prendre les valeurs 300, 100, ou 50 selon la précision du timing du joueur lorsqu'il clique dessus. Les intervalles de temps utilisés pour déterminer le résultat concret d'un cercle sont appelés *fenêtres de succès*, et sont influencés par l'[overall difficulty](/wiki/Beatmap/Overall_difficulty#osu!) de la beatmap.
```

2022-07-05 14:44 UTC, Y0hananas commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Si le [ScoreV2](/wiki/Gameplay/Game_modifier/ScoreV2) est actif, la précision à laquel le joueur touche le début du slider est également prise en compte dans le jugement de l'ensemble du slider:
```suggestion
- Si le [ScoreV2](/wiki/Gameplay/Game_modifier/ScoreV2) est actif, la précision avec laquelle le joueur touche le début du slider est également prise en compte dans le jugement de l'ensemble du slider:
```

2022-07-05 14:44 UTC, Y0hananas commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépent de l[overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critèr
```suggestion
Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépend de l[overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critères de jugement pour un spinner dans son ensemble sont les suivants:
```

2022-07-05 14:44 UTC, Y0hananas commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +Chaque slider dans son ensemble produit un jugement de 50, 100 ou 300, basé sur la proportion de parties de slider touchées (à savoir, le début du slider, la fin du slider, les tics du slider et les
```suggestion
Chaque slider dans son ensemble produit un jugement de 50, 100 ou 300, basé sur la proportion de parties de slider touchées (à savoir le début du slider, la fin du slider, les tics du slider et les répétitions du slider). Ce jugement est converti en une valeur de score en utilisant la même méthode que celle utilisée pour les cercles.
```

2022-07-05 14:44 UTC, Y0hananas commented on wiki/Gameplay/Score/fr.md
> +Le score attribué à un joueur après avoir réussi complété une [beatmap](/wiki/Beatmap) est déterminé par les [jugements](/wiki/Gameplay/Judgement) que le joueur a reçus pour chaque [objet](/wiki/Game
```suggestion
Le score attribué à un joueur après avoir complété une [beatmap](/wiki/Beatmap) est déterminé par les [jugements](/wiki/Gameplay/Judgement) que le joueur a reçus pour chaque [objet](/wiki/Gameplay/Hit_object). Le système de notation est divisé en deux versions majeures actuellement utilisées.
```

2022-07-05 14:44 UTC, Y0hananas commented on wiki/Gameplay/Score/fr.md
> +Outre l'amélioration de la standardisation, ScoreV2 est également une solution de contournement pour un problème de [dépassement d'entier](https://en.wikipedia.org/wiki/Integer_overflow) qui peut sur
```suggestion
Outre l'amélioration de la standardisation, ScoreV2 est également une solution de contournement pour un problème de [dépassement d'entier](https://en.wikipedia.org/wiki/Integer_overflow) qui peut survenir sur des beatmaps longues et à forte intensité de combos. Le score total étant stocké sous la forme d'un nombre entier de 32 bits et ScoreV1 pouvant théoriquement donner un nombre illimité de points, le dépassement de la valeur maximale représentable de 2 147 483 647 points entraînerait l'apparition de valeurs négatives dans le compteur de score (ce qui est visuellement perçu comme un décompte à rebours). Dans la pratique, ScoreV2 est automatiquement activé pour les scores définis sur de longues beatmaps qui, autrement, auraient un score maximum supérieur à la limite des nombres entiers de 32 bits.
```

2022-07-05 14:44 UTC, Y0hananas commented on wiki/Gameplay/Score/fr.md
> +ScoreV2 n'est pas activé par défaut dans le gameplay. En partie seul, il peut être activé à l'aide du modificateur de jeu non-ranked [ScoreV2](/wiki/Game_modifier/ScoreV2) , et en [multijoueur](/wiki
```suggestion
ScoreV2 n'est pas activé par défaut dans le gameplay. En partie seule, il peut être activé à l'aide du modificateur de jeu non classé [ScoreV2](/wiki/Game_modifier/ScoreV2) , et en [multijoueur](/wiki/Gameplay/Multiplayer), ScoreV2 peut être défini comme une condition de victoire pendant la configuration du match.
```

2022-07-05 14:48 UTC, Pisapou commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépent de l[overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critèr
```suggestion
Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépent de l'[overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critères de jugement pour une spinner dans son ensemble sont les suivants:
```

2022-07-05 14:49 UTC, Pisapou commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un cercle peut prednre les valeurs 300, 100, ou 50 selon la précision du timing du joueur lorsqu'il clique dessus. Les intervalles de temps utilisés pour déterminer le résultat concret d'un cercle
```suggestion
- Un cercle peut prendre les valeurs 300, 100, ou 50 selon la précision du timing du joueur lorsqu'il clique dessus. Les intervalles de temps utilisés pour déterminer le résultat concret d'un cercle sont appelés *fenêtres de succès*, et sont influencés par l'[overall difficulty](/wiki/Beatmap/Overall_difficulty#osu!) de la beatmap.
```

2022-07-05 14:51 UTC, Pisapou commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépend de l[overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critèr
```suggestion
Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépend de l'[overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critères de jugement pour un spinner dans son ensemble sont les suivants:
```

2022-07-10 07:47 UTC, DoryanR requested changes

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit300.png "300") | 300 | Le meilleur résultat possible pour un objet touché. Si vous ne faites que des 300 dans une beatmap, vous obtiendrez la [note](/wiki/Gamepla
```suggestion
| ![](/wiki/shared/judgement/osu!/hit300.png "300") | 300 | Le meilleur résultat possible pour un objet. Si vous ne faites que des 300 dans une beatmap, vous obtiendrez la [note](/wiki/Gameplay/Grade) SS ou le SSH. Généralement indiqué par une couleur bleue. |
```

Je me met pas `touché` dans `objet touché` habituellement, car je trouve ça assez moche, et comme c'est comme ça sur tout les articles, autant uniformiser le tout.

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit300g.png "Geki") | 300 (激) Geki | Une variante du 300. Originaire de [Osu! Tatakae! Ouendan!](https://en.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan), appelées Elite
```suggestion
| ![](/wiki/shared/judgement/osu!/hit300g.png "Geki") | 300 (激) Geki | Une variante du 300. Originaire de [Osu! Tatakae! Ouendan!](https://fr.wikipedia.org/wiki/Osu!_Tatakae!_Ōendan), appelées Elite Beat! dans [Elite Beat Agents](https://fr.wikipedia.org/wiki/Elite_Beat_Agents). Accordé lorsque vous obtenez un 300 sur le dernier élément d'un combo dans lequel le joueur n'a obtenu que des 300. Obtenir un Geki accordera un bonus de vie considérable en plus de l'augmentation de vie standard pour un 300. |
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit300k.png "300 Katu") | 300 (喝) Katu ou Katsu | Une variante du 300. Originaire de [Osu! Tatakae! Ouendan!](https://en.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan), a
```suggestion
| ![](/wiki/shared/judgement/osu!/hit300k.png "300 Katu") | 300 (喝) Katu ou Katsu | Une variante du 300. Originaire de [Osu! Tatakae! Ouendan!](https://fr.wikipedia.org/wiki/Osu!_Tatakae!_Ōendan), appelées Beat! dans [Elite Beat Agents](https://fr.wikipedia.org/wiki/Elite_Beat_Agents). Accordé lorsque vous obtenez un 300 sur le dernier élément d'un combo dans lequel le joueur a obtenu au moins un 100, mais pas de 50 ou de miss. Obtenir un Katu donnera un petit bonus de vie en plus de l'augmentation de vie standard pour un 300. |
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit100.png "100") | 100 | Le deuxième meilleur résultat possible pour un objet touché. Il est généralement indiqué par une couleur verte. |
```suggestion
| ![](/wiki/shared/judgement/osu!/hit100.png "100") | 100 | Le deuxième meilleur résultat possible pour un objet. Il est généralement indiqué par une couleur verte. |
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit100k.png "100 Katu") | 100 (喝) Katu ou Katsu | Une variante du 100. Originaire de [Osu! Tatakae! Ouendan!](https://en.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan), a
```suggestion
| ![](/wiki/shared/judgement/osu!/hit100k.png "100 Katu") | 100 (喝) Katu ou Katsu | Une variante du 100. Originaire de [Osu! Tatakae! Ouendan!](https://fr.wikipedia.org/wiki/Osu!_Tatakae!_Ōendan), appelées Beat! dans [Elite Beat Agents](https://fr.wikipedia.org/wiki/Elite_Beat_Agents). Accordé lorsque vous obtenez un 100 sur le dernier élément d'un combo dans lequel le joueur a obtenu au moins un 100, mais pas de 50 ou de raté. Obtenir un Katu donnera un petit bonus de vie en plus de l'augmentation de vie standard pour un 100. |
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit50.png "50") | 50 | Le troisième meilleur résultat possible pour un objet touché, le dernier avant un échec. Il est généralement indiqué par une couleur orange. U
```suggestion
| ![](/wiki/shared/judgement/osu!/hit50.png "50") | 50 | Le troisième meilleur résultat possible pour un objet, le dernier avant un miss. Il est généralement indiqué par une couleur orange. Un score de 50 empêche l'apparition d'un Katu ou d'un Geki à la fin du combo. |
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit0.png "Miss") | Miss | Le pire résultat possible pour un objet touché. Un échec remet le combo en cours à 0 et empêche l'apparition d'un Katu ou d'un Geki à la fi
```suggestion
| ![](/wiki/shared/judgement/osu!/hit0.png "Miss") | Miss | Le pire résultat possible pour un objet. Un miss remet le combo en cours à 0 et empêche l'apparition d'un Katu ou d'un Geki à la fin du combo. |
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un cercle peut prendre les valeurs 300, 100, ou 50 selon la précision du timing du joueur lorsqu'il clique dessus. Les intervalles de temps utilisés pour déterminer le résultat concret d'un cercle
```suggestion
- Un cercle peut prendre les valeurs 300, 100, ou 50 selon la précision du timing du joueur lorsqu'il clique dessus. Les intervalles de temps utilisés pour déterminer le résultat concret d'un cercle sont appelés *hit windows*, et sont influencés par [l'overall difficulty](/wiki/Beatmap/Overall_difficulty#osu!) de la beatmap.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Un cercle est considéré comme raté quand:
```suggestion
- Un cercle est considéré comme miss quand :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +  - Le cercle est touché avant le début de la fenêtre de succès du 50 et ne déclenche pas un [notelock](/wiki/Gameplay/Judgement/Notelock).
```suggestion
  - Le cercle est touché avant le début de la hit window du 50 et ne déclenche pas un [notelock](/wiki/Gameplay/Judgement/Notelock).
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +  - Le cercle n'est pas touché et la fenêtre de succès du 50 est passée.
```suggestion
  - Le cercle n'est pas touché et la hit window du 50 est passée.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- 300: Le joueur a réussi à toucher toutes les parties du slider.
```suggestion
- 300 : Le joueur a réussi à toucher toutes les parties du slider.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- 100: Le joueur a au moins touché la moitié des parties du slider.
```suggestion
- 100 : Le joueur a au moins touché la moitié des parties du slider.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- 50: Le joueur a réussi à toucher au moins une des parties du slider.
```suggestion
- 50 : Le joueur a réussi à toucher au moins une des parties du slider.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Miss: Le joueur n'a touché aucune des parties du slider.
```suggestion
- Miss : Le joueur n'a touché aucune des parties du slider.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Si le [ScoreV2](/wiki/Gameplay/Game_modifier/ScoreV2) est actif, la précision avec laquelle le joueur touche le début du slider est également prise en compte dans le jugement de l'ensemble du slide
```suggestion
- Si le [ScoreV2](/wiki/Gameplay/Game_modifier/ScoreV2) est actif, la précision avec laquelle le joueur touche le début du slider est également prise en compte dans le jugement de l'ensemble du slider :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Les parties du slider ont également une influence supplémentaire sur le [combo](/wiki/Gameplay/Combo_(score_multiplier)) actuel:
```suggestion
Les parties du slider ont également une influence supplémentaire sur le [combo](/wiki/Gameplay/Combo_(score_multiplier)) actuel :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépend de l'[overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critè
```suggestion
Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépend de [l'overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critères de jugement pour un spinner dans son ensemble sont les suivants :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- 300: Le joueur a réussi à effectuer le nombre de tours requis pour la complétion, ou plus.
```suggestion
- 300 : Le joueur a réussi à effectuer le nombre de tours requis pour la complétion, ou plus.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- 100: Le joueur a effectué un tour de moins que le nombre requis.
```suggestion
- 100 : Le joueur a effectué un tour de moins que le nombre requis.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- 50: Le joueur a effectué au moins 25% des tours requis.
```suggestion
- 50 : Le joueur a effectué au moins 25% des tours requis.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Miss: Le joueur n'a pas atteint le minimum de 25% de tours requis.
```suggestion
- Miss : Le joueur n'a pas atteint le minimum de 25% de tours requis.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +L'algorithme de jugement du spinner a été modifié de manière significative dans le [20190510.2 Cutting Edge release](https://osu.ppy.sh/home/changelog/cuttingedge/20190510.2). Avant ce changement, il
```suggestion
L'algorithme de jugement du spinner a été modifié de manière significative dans le build [20190510.2 Cutting Edge release](https://osu.ppy.sh/home/changelog/cuttingedge/20190510.2). Avant ce changement, il était beaucoup plus difficile d'obtenir des jugements sans erreur, car la différence entre un 50 et un 100, ainsi qu'entre un 100 et un 300, était égale à la moitié d'un tour. Certaines beatmaps comportaient même des spinners qui ne pouvaient jamais être jugés avec un 300, car ils étaient trop courts pour être complétés entièrement.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +*Voir aussi: [système de jugement de osu!](/wiki/Gameplay/Judgement/osu!)*
```suggestion
*Voir également : [système de jugement d'osu!](/wiki/Gameplay/Judgement/osu!)*
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +Chaque cercle de réussite se voit attribuer une valeur numérique en points selon la formule ci-dessous :
```suggestion
Chaque cercle se voit attribuer une valeur numérique en points selon la formule ci-dessous :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +où:
```suggestion
Où :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +- Le *difficulty multiplier* est une valeur spécifique au beatmap en cours de lecture. Voir la [section ci-dessous](#difficulty-multiplier) pour la formule exacte pour le calculer.
```suggestion
- Le *difficulty multiplier* est une valeur spécifique de la beatmap en cours de lecture. Voir la [section ci-dessous](#multiplicateur-de-difficulté) pour la formule exacte pour le calculer.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +Notez que les modes (comme Hard Rock ou Easy, qui changent la taille des cercles par exemple) n'affectent pas le multiplicateur de difficulté, car les valeurs originales des variables sont toujours u
```suggestion
Notez que les mods (comme Hard Rock ou Easy, qui changent la taille des cercles par exemple) n'affectent pas le multiplicateur de difficulté, car les valeurs originales des variables sont toujours utilisées dans la formule ci-dessus, quels que soient les modes activés.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +Chaque slider dans son ensemble produit un jugement de 50, 100 ou 300, basé sur la proportion de parties de slider touchées (à savoir le début du slider, la fin du slider, les tics du slider et les r
```suggestion
Chaque slider dans son ensemble produit un jugement de 50, 100 ou 300, basé sur la proportion des parties du slider touché (à savoir le début du slider, la fin du slider, les ticks du slider et les répétitions du slider). Ce jugement est converti en une valeur de score en utilisant la même méthode que celle utilisée pour les cercles.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
>  *Pour d'autres utilisations, voir [Score (désambiguïsation)](/wiki/Disambiguation/Score).*\
```suggestion
*Pour d'autres utilisations, voir [Score (désambiguïsation)](/wiki/Disambiguation/Score).*
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
> +ScoreV1 est le nom familier du système de score original, par défaut, dans osu !. Bien qu'il soit généralement désigné par un seul nom, l'algorithme lui-même varie beaucoup en fonction du [mode de je
```suggestion
Le ScoreV1 est le nom familier du système de score original, par défaut, dans osu!. Bien qu'il soit généralement désigné par un seul nom, l'algorithme lui-même varie beaucoup en fonction du [mode de jeu](/wiki/Game_mode) actif :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
> +- osu! et osu!catch utilisent un multiplicateur de score strictement basé sur les combos, appliqué sur les valeurs de score pour chaque objet touché.
```suggestion
- osu! et osu!catch utilisent un multiplicateur de score strictement basé sur les combos, appliqué sur les valeurs de score pour chaque objet.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
> +- osu!taiko suit grosso modo le système de notation de *Taiko no Tatsujin* avec un petit score constant affecté d'un bonus de combo.
```suggestion
- osu!taiko suit la logique du système de notation de *Taiko no Tatsujin* avec un petit score constant affecté d'un bonus de combo.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
> +Pour une description détaillée du fonctionnement de ScoreV1 dans chaque mode de jeu, voir:
```suggestion
Pour une description détaillée du fonctionnement de ScoreV1 dans chaque mode de jeu, voir :
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
> +ScoreV2 est une nouvelle version du système de score. L'idée principale est de standardiser les systèmes de score de tous les modes de jeu, de telle sorte qu'un score parfait rapporte 1 000 000 de po
```suggestion
ScoreV2 est une nouvelle version du système de score. L'idée principale est de standardiser les systèmes de score de tous les modes de jeu, de telle sorte qu'un score parfait rapporte 1 000 000 de points avec un modificateur de score de 1,00x, avec des gains de score supplémentaires grâce aux bonus de spinner pour osu!, aux roulements de tambour pour osu!taiko, et aux bananes pour osu!catch. Cela implique un écart par rapport aux valeurs de score originales de chaque objet, et un changement vers un système plus centré sur les proportions et la mise à l'échelle vers le plafond de 1 million.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
> +Outre l'amélioration de la standardisation, ScoreV2 est également une solution de contournement pour un problème de [dépassement d'entier](https://en.wikipedia.org/wiki/Integer_overflow) qui peut sur
```suggestion
Outre l'amélioration de la standardisation, ScoreV2 est également une solution de contournement pour un problème de [dépassement d'entier](https://fr.wikipedia.org/wiki/Dépassement_d'entier) qui peut survenir sur des beatmaps longues et à forte intensité de combos. Le score total étant stocké sous la forme d'un nombre entier de 32 bits et ScoreV1 pouvant théoriquement donner un nombre illimité de points, le dépassement de la valeur maximale représentable de 2 147 483 647 points entraînerait l'apparition de valeurs négatives dans le compteur de score (ce qui est visuellement perçu comme un décompte à rebours). Dans la pratique, ScoreV2 est automatiquement activé pour les scores définis sur de longues beatmaps qui, autrement, auraient un score maximum supérieur à la limite des nombres entiers de 32 bits.
```

2022-07-10 07:47 UTC, DoryanR commented on wiki/Gameplay/Score/fr.md
> +ScoreV2 n'est pas activé par défaut dans le gameplay. En partie seule, il peut être activé à l'aide du modificateur de jeu non classé [ScoreV2](/wiki/Game_modifier/ScoreV2) , et en [multijoueur](/wik
```suggestion
ScoreV2 n'est pas activé par défaut dans le gameplay. En partie seule, il peut être activé à l'aide du modificateur de jeu UNRANKED [ScoreV2](/wiki/Game_modifier/ScoreV2), et en [multijoueur](/wiki/Gameplay/Multiplayer), ScoreV2 peut être défini comme une condition de victoire pendant la configuration du match.
```

2022-07-10 18:58 UTC, DoryanR requested changes

2022-07-10 18:58 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +### Cercles :
```suggestion
### Cercles
```

2022-07-10 18:58 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +# ScoreV1 (osu!)
Add a line a the end of file

2022-07-11 10:44 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépend de [l'overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-and-spinners) de la beatmap. Les critè
```suggestion
Chaque spinner a un nombre déterminé de tours nécessaires pour le compléter. Ce nombre dépend de [l'overall difficulty](/wiki/Beatmap/Overall_difficulty#sliders-et-spinners) de la beatmap. Les critères de jugement pour un spinner dans son ensemble sont les suivants :
```

2022-07-12 10:49 UTC, DoryanR requested changes

2022-07-12 10:49 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit300.png "300") | 300 | Le meilleur résultat possible pour un objet touché. Si vous ne faites que des 300 dans une beatmap, vous obtiendrez la [note](/wiki/Gamepla
```suggestion
| ![](/wiki/shared/judgement/osu!/hit300.png "300") | 300 | Le meilleur résultat possible pour un objet touché. Si vous ne faites que des 300 dans une beatmap, vous obtiendrez la [note](/wiki/Gameplay/Grade) SS ou SSH. Généralement indiqué par une couleur bleue. |
```

2022-07-12 10:49 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +| ![](/wiki/shared/judgement/osu!/hit100k.png "100 Katu") | 100 (喝) Katu ou Katsu | Une variante du 100. Originaire de [Osu! Tatakae! Ouendan!](https://fr.wikipedia.org/wiki/Osu!_Tatakae!_Ōendan), ap
```suggestion
| ![](/wiki/shared/judgement/osu!/hit100k.png "100 Katu") | 100 (喝) Katu ou Katsu | Une variante du 100. Originaire de [Osu! Tatakae! Ouendan!](https://fr.wikipedia.org/wiki/Osu!_Tatakae!_Ōendan), appelées Beat! dans [Elite Beat Agents](https://fr.wikipedia.org/wiki/Elite_Beat_Agents). Accordé lorsque vous obtenez un 100 sur le dernier élément d'un combo dans lequel le joueur a obtenu au moins un 100, mais pas de 50 ou un miss. Obtenir un Katu donnera un petit bonus de vie en plus de l'augmentation de vie standard pour un 100. |
```

2022-07-12 10:49 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +- La *hit value* est la valeur numérique d'un jugement d'un cercle (50, 100, or 300).
```suggestion
- Le *hit value* est la valeur numérique d'un jugement d'un cercle (50, 100, or 300).
```

2022-07-12 10:49 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +- Le *difficulty multiplier* est une valeur spécifique de la beatmap en cours de lecture. Voir la [section ci-dessous](#multiplicateur-de-difficulté) pour la formule exacte pour le calculer.
```suggestion
- Le *difficulty multiplier* est une valeur spécifique de la beatmap en cours. Voir la [section ci-dessous](#multiplicateur-de-difficulté) pour la formule exacte pour le calculer.
```

2022-07-12 10:49 UTC, DoryanR commented on wiki/Gameplay/Score/ScoreV1/osu!/fr.md
> +Le **multiplicateur de difficulté** correspond à une ancienne version du star rating pour la beatmap en cours de lecture. Il peut être calculé à l'aide de la formule suivante :
```suggestion
Le **multiplicateur de difficulté** correspond à une ancienne version du star rating pour la beatmap en cours. Il peut être calculé à l'aide de la formule suivante :
```

2022-07-12 14:51 UTC, DoryanR approved these changes

2022-07-12 22:14 UTC, cl8n approved these changes

2022-07-12 22:16 UTC, merged