Update zh.md
ppy/osu-wiki pull request #7613
Opened 2022-07-06 23:51 UTC by FlyingFish23

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-07 12:55 UTC, heipizhu4 reviewed
Mostly good, please avoid translationese. “请避免翻译腔”。这句话或更长可以省略，因为最小值已经涵盖了意思。

2022-07-07 12:55 UTC, heipizhu4 commented on wiki/Rules/zh.md
> +严重违反规定时的封禁时间最小值通常为42小时或更长，这类行为通常是违规图片以及骚扰其他玩家。
```suggestion
严重违反规定时的最短封禁时间通常为42小时，这类行为通常是违规图片以及骚扰其他玩家。
```

2022-07-08 10:52 UTC, YumeMuzi commented on wiki/Rules/zh.md
> +严重违反规定时的封禁时间最小值通常为42小时或更长，这类行为通常是违规图片以及骚扰其他玩家。
改成 严重违反规定时，封禁时间通常最短为42小时 语句会通顺很多

2022-07-09 05:21 UTC, FlyingFish23 commented on wiki/Rules/zh.md
> +严重违反规定时的封禁时间最小值通常为42小时或更长，这类行为通常是违规图片以及骚扰其他玩家。
tbh I haven't changed anything but 48 to 42. all the rest is exact from before.

2022-07-11 06:43 UTC, RushFTK requested changes
seemed i forgot to submit changes?

2022-07-27 13:42 UTC, TPGPL commented
@FlyingFish23 are you planning to continue working on #7613 and #7612 at any time?

2022-09-20 23:14 UTC, closed without merging