Add teams to `triangles Beatmapping Contest`
ppy/osu-wiki pull request #7648
Opened 2022-07-14 20:58 UTC by pishifat

final update before judging!!!

2022-07-14 22:58 UTC, TPGPL commented on wiki/Contests/triangles_Beatmapping_Contest/en.md
> +| Goofy ahh Meysters | ![][flag_MY] [Slyk](https://osu.ppy.sh/users/7798305), ![][flag_MY] [Shocola](https://osu.ppy.sh/users/6781232) | ![][flag_MY] [Slyk](https://osu.ppy.sh/users/7798305), ![][fla
slyk is twice here

2022-07-14 23:01 UTC, TPGPL requested changes

2022-07-14 23:01 UTC, TPGPL commented on wiki/Contests/triangles_Beatmapping_Contest/en.md
> +| South American Mappers | ![][flag_MX] [funny](https://osu.ppy.sh/users/8473573), ![][flag_ES] [Elinor](https://osu.ppy.sh/users/5419324), ![][flag_SG] [hehe](https://osu.ppy.sh/users/2123087), ![][
MX flag needs to be imported

2022-07-15 03:48 UTC, peppy approved these changes

2022-07-15 03:49 UTC, merged