Add `Expert Global Taiko Showdown 2022` wiki article
ppy/osu-wiki pull request #7649
Opened 2022-07-15 16:58 UTC by fajar13k

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

## Description

- Initial article for upcoming Expert Global Taiko Showdown
- Still draft, but open for review

2022-07-15 17:49 UTC, Blooshing requested changes

2022-07-15 17:49 UTC, Blooshing commented on wiki/Tournaments/GTS/EGTS_2022/en.md
> +3. If one of the player's coming late, the maximum time the match can be postponed is **10 minutes**.
```suggestion
3. If one of the players is late, the maximum time the match can be postponed is **10 minutes**.
```

2022-07-15 17:49 UTC, Blooshing commented on wiki/Tournaments/GTS/EGTS_2022/en.md
> +4. Any players are allowed to sign up since there are no rank limits applied.
```suggestion
4. Any player is allowed to sign up due to no rank limit.
```

2022-07-16 00:22 UTC, TPGPL requested changes

2022-07-16 00:22 UTC, TPGPL commented on wiki/Tournaments/GTS/EGTS_2022/en.md
> +The **Expert Global Taiko Showdown 2022** (***EGTS 2022***) is a worldwide double-elimination osu!taiko tournament hosted by ::{ flag=FR }:: [\_yosh](https://osu.ppy.sh/users/7157133), ::{ flag=FR }:
```suggestion
The **Expert Global Taiko Showdown 2022** (***EGTS 2022***) is a worldwide double-elimination osu!taiko tournament hosted by ::{ flag=FR }:: [\_yosh](https://osu.ppy.sh/users/7157133), ::{ flag=FR }:: [Arrival](https://osu.ppy.sh/users/1694000), and ::{ flag=FR }:: [Kasumi-sama](https://osu.ppy.sh/users/6177263). The tournament is targeted for the top osu!taiko players, with no rank limits. It is the third instalment of the Expert Global Taiko Showdown and part of the Global Taiko Showdown series.
```

2022-07-16 00:22 UTC, TPGPL commented on wiki/Tournaments/GTS/EGTS_2022/en.md
> + *Each mappools will be announced every 7 days (usually Sunday) before the next stage's match timeline.*
```suggestion
 *Every mappool will be announced 7 days (usually Sunday) before the next stage's match timeline.*
```

2022-07-16 13:38 UTC, TPGPL approved these changes

2022-07-16 13:39 UTC, merged