Updated Outdated French Translation for MWC 2014
ppy/osu-wiki pull request #7654
Opened 2022-07-16 12:44 UTC by Soetch

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-24 18:25 UTC, Ganondorf-1 requested changes
I will check this again later because it might need another review. 
Looks like stuff was missing or still outdated.

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_TW] | **Taiwan** | **[CrazyStar](https://osu.ppy.sh/users/680008)**, [GH\_CHAIKA](https://osu.ppy.sh/users/2462317), [sille123](https://osu.ppy.sh/users/1626359), [y85782122](https://osu.p
```suggestion
| ![][flag_TW] | **Taïwan** | **[CrazyStar](https://osu.ppy.sh/users/680008)**, [GH\_CHAIKA](https://osu.ppy.sh/users/2462317), [sille123](https://osu.ppy.sh/users/1626359), [y85782122](https://osu.ppy.sh/users/2287176) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_TW] Taiwan | ![][flag_ID] Indonésie | ![][flag_NZ] Nouvelle Zélande | ![][flag_CL] Chili |
```suggestion
| ![][flag_TW] Taïwan | ![][flag_ID] Indonésie | ![][flag_NZ] Nouvelle-Zélande | ![][flag_CL] Chili |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Malaisie** ![][flag_MY] | **5** | 1 | ![][flag_TW] Taiwan | [#1](https://osu.ppy.sh/community/matches/8905453) |
```suggestion
| **Malaisie** ![][flag_MY] | **5** | 1 | ![][flag_TW] Taïwan | [#1](https://osu.ppy.sh/community/matches/8905453) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Taiwan** ![][flag_TW] | **5** | 0 | ![][flag_NO] Norvège | [#1](https://osu.ppy.sh/community/matches/8746528) |
```suggestion
| **Taïwan** ![][flag_TW] | **5** | 0 | ![][flag_NO] Norvège | [#1](https://osu.ppy.sh/community/matches/8746528) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Taiwan** ![][flag_TW] | **4** | 2 | ![][flag_DE] Allemagne | [#1](https://osu.ppy.sh/community/matches/8430093) |
```suggestion
| **Taïwan** ![][flag_TW] | **4** | 2 | ![][flag_DE] Allemagne | [#1](https://osu.ppy.sh/community/matches/8430093) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Taiwan ![][flag_TW] | 3 | **4** | ![][flag_PH] **Philippines** | [#1](https://osu.ppy.sh/community/matches/8430762) |
```suggestion
| Taïwan ![][flag_TW] | 3 | **4** | ![][flag_PH] **Philippines** | [#1](https://osu.ppy.sh/community/matches/8430762) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Argentine ![][flag_AR] | 0 | **4** | ![][flag_TW] **Taiwan** | [#1](https://osu.ppy.sh/community/matches/8434391) |
```suggestion
| Argentine ![][flag_AR] | 0 | **4** | ![][flag_TW] **Taïwan** | [#1](https://osu.ppy.sh/community/matches/8434391) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Espagne ![][flag_ES] | 1 | **4** | ![][flag_TW] **Taiwan** | [#1](https://osu.ppy.sh/community/matches/8458504) |
```suggestion
| Espagne ![][flag_ES] | 1 | **4** | ![][flag_TW] **Taïwan** | [#1](https://osu.ppy.sh/community/matches/8458504) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +[flag_TW]: /wiki/shared/flag/TW.gif "Taiwan"
```suggestion
[flag_TW]: /wiki/shared/flag/TW.gif "Taïwan"
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_PL] | **Polande** | **[-Kamikaze-](https://osu.ppy.sh/users/2124783)**, [Hudonom](https://osu.ppy.sh/users/1654221), [Modren](https://osu.ppy.sh/users/1828621), [Tidek](https://osu.ppy.sh/
```suggestion
| ![][flag_PL] | **Pologne** | **[-Kamikaze-](https://osu.ppy.sh/users/2124783)**, [Hudonom](https://osu.ppy.sh/users/1654221), [Modren](https://osu.ppy.sh/users/1828621), [Tidek](https://osu.ppy.sh/users/743282) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_PL] | **Polande** | **[Modren](https://osu.ppy.sh/users/1828621)**, [Hudonom](https://osu.ppy.sh/users/1654221), [-Kamikaze-](https://osu.ppy.sh/users/2124783), [Tear](https://osu.ppy.sh/u
```suggestion
| ![][flag_PL] | **Pologne** | **[Modren](https://osu.ppy.sh/users/1828621)**, [Hudonom](https://osu.ppy.sh/users/1654221), [-Kamikaze-](https://osu.ppy.sh/users/2124783), [Tear](https://osu.ppy.sh/users/1340650) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_AR] Argentine | ![][flag_CZ] Tchéquie | ![][flag_RU] Russie | ![][flag_PL] Polande |
```suggestion
| ![][flag_AR] Argentine | ![][flag_CZ] Tchéquie | ![][flag_RU] Russie | ![][flag_PL] Pologne |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_PH] Philippines | ![][flag_PL] Polande | ![][flag_PT] Portugal | ![][flag_NO] Norvège |
```suggestion
| ![][flag_PH] Philippines | ![][flag_PL] Pologne | ![][flag_PT] Portugal | ![][flag_NO] Norvège |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Polande ![][flag_PL] | 0 | **6** | ![][flag_MY] **Malaisie** | [#1](https://osu.ppy.sh/community/matches/9193332) |
```suggestion
| Pologne ![][flag_PL] | 0 | **6** | ![][flag_MY] **Malaisie** | [#1](https://osu.ppy.sh/community/matches/9193332) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Philippines** ![][flag_PH] | **6** | 0 | ![][flag_PL] Polande | [#1](https://osu.ppy.sh/community/matches/9049440) |
```suggestion
| **Philippines** ![][flag_PH] | **6** | 0 | ![][flag_PL] Pologne | [#1](https://osu.ppy.sh/community/matches/9049440) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Royaume-Uni ![][flag_GB] | 3 | **5** | ![][flag_PL] **Polande** | [#1](https://osu.ppy.sh/community/matches/8908074) |
```suggestion
| Royaume-Uni ![][flag_GB] | 3 | **5** | ![][flag_PL] **Pologne** | [#1](https://osu.ppy.sh/community/matches/8908074) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Allemagne ![][flag_DE] | 1 | **5** | ![][flag_PL] **Polande** | [#1](https://osu.ppy.sh/community/matches/8751265) |
```suggestion
| Allemagne ![][flag_DE] | 1 | **5** | ![][flag_PL] **Pologne** | [#1](https://osu.ppy.sh/community/matches/8751265) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Polande** ![][flag_PL] | **4** | 0 | ![][flag_NO] Norvège | [#1](https://osu.ppy.sh/community/matches/8431527) |
```suggestion
| **Pologne** ![][flag_PL] | **4** | 0 | ![][flag_NO] Norvège | [#1](https://osu.ppy.sh/community/matches/8431527) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Polande** ![][flag_PL] | **4** | 3 | ![][flag_CA] Canada | [#1](https://osu.ppy.sh/community/matches/8434796) |
```suggestion
| **Pologne** ![][flag_PL] | **4** | 3 | ![][flag_CA] Canada | [#1](https://osu.ppy.sh/community/matches/8434796) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Polande** ![][flag_PL] | **4** | 0 | ![][flag_CL] Chili | *win by default* |
```suggestion
| **Pologne** ![][flag_PL] | **4** | 0 | ![][flag_CL] Chili | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Polande** ![][flag_PL] | **4** | 2 | ![][flag_FR] France | [#1](https://osu.ppy.sh/community/matches/8459894) |
```suggestion
| **Pologne** ![][flag_PL] | **4** | 2 | ![][flag_FR] France | [#1](https://osu.ppy.sh/community/matches/8459894) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Chili** ![][flag_CL] | **5** | 0 | ![][flag_PL] Polande | [#1](https://osu.ppy.sh/community/matches/8777543) |
```suggestion
| **Chili** ![][flag_CL] | **5** | 0 | ![][flag_PL] Pologne | [#1](https://osu.ppy.sh/community/matches/8777543) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Polande** ![][flag_PL] | **4** | 2 | ![][flag_RU] Russie | [#1](https://osu.ppy.sh/community/matches/8573871) |
```suggestion
| **Pologne** ![][flag_PL] | **4** | 2 | ![][flag_RU] Russie | [#1](https://osu.ppy.sh/community/matches/8573871) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Polande ![][flag_PL] | 0 | **4** | ![][flag_CN] **China** | [#1](https://osu.ppy.sh/community/matches/8585840) |
```suggestion
| Pologne ![][flag_PL] | 0 | **4** | ![][flag_CN] **China** | [#1](https://osu.ppy.sh/community/matches/8585840) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Polande ![][flag_PL] | 0 | **4** | ![][flag_HK] **Hong Kong** | [#1](https://osu.ppy.sh/community/matches/8586727) |
```suggestion
| Pologne ![][flag_PL] | 0 | **4** | ![][flag_HK] **Hong Kong** | [#1](https://osu.ppy.sh/community/matches/8586727) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +   2. Les paramètres de la salle sont les suivants : osu!mania ; Équipe VS ; victoire sur score. Le nom de la salle doit suivre cette nomenclature : "MWC 2014: ÉquipeBlue vs ÉquipeRed"
```suggestion
   2. Les paramètres de la salle sont les suivants : osu!mania ; Team VS ; victoire sur score. Le nom de la salle doit suivre cette nomenclature : "MWC 2014: ÉquipeBleue vs ÉquipeRouge"
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +[flag_PL]: /wiki/shared/flag/PL.gif "Polande"
```suggestion
[flag_PL]: /wiki/shared/flag/PL.gif "Pologne"
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_NZ] | **Nouvelle Zélande** | **[Mudkips](https://osu.ppy.sh/users/2502706)**, [Crono76](https://osu.ppy.sh/users/4249989), [ksy64320](https://osu.ppy.sh/users/2068663) |
```suggestion
| ![][flag_NZ] | **Nouvelle-Zélande** | **[Mudkips](https://osu.ppy.sh/users/2502706)**, [Crono76](https://osu.ppy.sh/users/4249989), [ksy64320](https://osu.ppy.sh/users/2068663) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Russie** ![][flag_RU] | **4** | 3 | ![][flag_NZ] Nouvelle Zélande | [#1](https://osu.ppy.sh/community/matches/8429172) |
```suggestion
| **Russie** ![][flag_RU] | **4** | 3 | ![][flag_NZ] Nouvelle-Zélande | [#1](https://osu.ppy.sh/community/matches/8429172) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Japon** ![][flag_JP] | **4** | 0 | ![][flag_NZ] Nouvelle Zélande | [#1](https://osu.ppy.sh/community/matches/8429927) |
```suggestion
| **Japon** ![][flag_JP] | **4** | 0 | ![][flag_NZ] Nouvelle-Zélande | [#1](https://osu.ppy.sh/community/matches/8429927) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Nouvelle Zélande ![][flag_NZ] | 0 | **4** | ![][flag_MY] **Malaisie** | [#1](https://osu.ppy.sh/community/matches/8454627) |
```suggestion
| Nouvelle-Zélande ![][flag_NZ] | 0 | **4** | ![][flag_MY] **Malaisie** | [#1](https://osu.ppy.sh/community/matches/8454627) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Nouvelle Zélande ![][flag_NZ] | 1 | **4** | ![][flag_GB] **Royaume-Uni** | [#1](https://osu.ppy.sh/community/matches/8455468) |
```suggestion
| Nouvelle-Zélande ![][flag_NZ] | 1 | **4** | ![][flag_GB] **Royaume-Uni** | [#1](https://osu.ppy.sh/community/matches/8455468) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Philippines** ![][flag_PH] | **5** | 0 | ![][flag_CA] Canada | *win by default* |
```suggestion
| **Philippines** ![][flag_PH] | **5** | 0 | ![][flag_CA] Canada | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Japon** ![][flag_JP] | **5** | 0 | ![][flag_US] États-Unis | *win by default* |
```suggestion
| **Japon** ![][flag_JP] | **5** | 0 | ![][flag_US] États-Unis | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_AU] **Australie** | *win by default* |
```suggestion
| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_AU] **Australie** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Canada ![][flag_CA] | 0 | **4** | ![][flag_FR] **France** | *win by default* |
```suggestion
| Canada ![][flag_CA] | 0 | **4** | ![][flag_FR] **France** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_KR] **Corée du Sud** | *win by default* |
```suggestion
| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_KR] **Corée du Sud** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Chili ![][flag_CL] | 0 | **4** | ![][flag_FR] **France** | *win by default* |
```suggestion
| Chili ![][flag_CL] | 0 | **4** | ![][flag_FR] **France** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Indonésie ![][flag_ID] | 0 | **4** | ![][flag_US] **États-Unis** | *win by default* |
```suggestion
| Indonésie ![][flag_ID] | 0 | **4** | ![][flag_US] **États-Unis** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Chili ![][flag_CL] | 0 | **4** | ![][flag_NO] **Norvège** | *win by default* |
```suggestion
| Chili ![][flag_CL] | 0 | **4** | ![][flag_NO] **Norvège** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_ID] **Indonésie** | *win by default* |
```suggestion
| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_ID] **Indonésie** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Canada ![][flag_CA] | 0 | **4** | ![][flag_NO] **Norvège** | *win by default* |
```suggestion
| Canada ![][flag_CA] | 0 | **4** | ![][flag_NO] **Norvège** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Canada** ![][flag_CA] | **4** | 0 | ![][flag_CL] Chili | *win by default* |
```suggestion
| **Canada** ![][flag_CA] | **4** | 0 | ![][flag_CL] Chili | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_US] **États-Unis** | *win by default* |
```suggestion
| Tchéquie ![][flag_CZ] | 0 | **4** | ![][flag_US] **États-Unis** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Hong Kong ![][flag_HK] | 0 | **5** | ![][flag_TH] **Thaïlande** | *win by default* |
```suggestion
| Hong Kong ![][flag_HK] | 0 | **5** | ![][flag_TH] **Thaïlande** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Portugal ![][flag_PT] | 0 | **4** | ![][flag_FR] **France** | *win by default* |
```suggestion
| Portugal ![][flag_PT] | 0 | **4** | ![][flag_FR] **France** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Portugal ![][flag_PT] | 0 | **4** | ![][flag_CL] **Chili** | *win by default* |
```suggestion
| Portugal ![][flag_PT] | 0 | **4** | ![][flag_CL] **Chili** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Philippines ![][flag_PH] | 0 | **4** | ![][flag_MY] **Malaisie** | *win by default* |
```suggestion
| Philippines ![][flag_PH] | 0 | **4** | ![][flag_MY] **Malaisie** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Corée du Sud ![][flag_KR] | 0 | **4** | ![][flag_TH] **Thaïlande** | *win by default* |
```suggestion
| Corée du Sud ![][flag_KR] | 0 | **4** | ![][flag_TH] **Thaïlande** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Australie** ![][flag_AU] | **4** | 0 | ![][flag_PH] Philippines | *win by default* |
```suggestion
| **Australie** ![][flag_AU] | **4** | 0 | ![][flag_PH] Philippines | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Philippines ![][flag_PH] | 0 | **4** | ![][flag_US] **États-Unis** | *win by default* |
```suggestion
| Philippines ![][flag_PH] | 0 | **4** | ![][flag_US] **États-Unis** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Norvège ![][flag_NO] | 0 | **4** | ![][flag_TH] **Thaïlande** | *win by default* |
```suggestion
| Norvège ![][flag_NO] | 0 | **4** | ![][flag_TH] **Thaïlande** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Philippines ![][flag_PH] | 0 | **4** | ![][flag_DE] **Allemagne** | *win by default* |
```suggestion
| Philippines ![][flag_PH] | 0 | **4** | ![][flag_DE] **Allemagne** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Portugal ![][flag_PT] | 0 | **4** | ![][flag_JP] **Japon** | *win by default* |
```suggestion
| Portugal ![][flag_PT] | 0 | **4** | ![][flag_JP] **Japon** | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Corée du Sud** ![][flag_KR] | **4** | 0 | ![][flag_NO] Norvège | *win by default* |
```suggestion
| **Corée du Sud** ![][flag_KR] | **4** | 0 | ![][flag_NO] Norvège | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Indonésie** ![][flag_ID] | **4** | 0 | ![][flag_PT] Portugal | *win by default* |
```suggestion
| **Indonésie** ![][flag_ID] | **4** | 0 | ![][flag_PT] Portugal | *victoire par défaut* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Sélection des beatmaps | ![][flag_RU] [\[Shi-Ra\]](https://osu.ppy.sh/users/2008489), ![][flag_CL] [Agka](https://osu.ppy.sh/users/64811) |
```suggestion
| Sélectionneur de beatmaps | ![][flag_RU] [\[Shi-Ra\]](https://osu.ppy.sh/users/2008489), ![][flag_CL] [Agka](https://osu.ppy.sh/users/64811) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Retransmission des matchs | ![][flag_PL] [Marcin](https://osu.ppy.sh/users/722665), ![][flag_AU] [peppy](https://osu.ppy.sh/users/2), ![][flag_FR] [shARPII](https://osu.ppy.sh/users/776257) |
```suggestion
| Streamers | ![][flag_PL] [Marcin](https://osu.ppy.sh/users/722665), ![][flag_AU] [peppy](https://osu.ppy.sh/users/2), ![][flag_FR] [shARPII](https://osu.ppy.sh/users/776257) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Commentaires | ![][flag_RU] [\[Shi-Ra\]](https://osu.ppy.sh/users/2008489), ![][flag_US] [Charles445](https://osu.ppy.sh/users/85000), ![][flag_FR] [Mr Color](https://osu.ppy.sh/users/116078), ![][
```suggestion
| Commentateurs | ![][flag_RU] [\[Shi-Ra\]](https://osu.ppy.sh/users/2008489), ![][flag_US] [Charles445](https://osu.ppy.sh/users/85000), ![][flag_FR] [Mr Color](https://osu.ppy.sh/users/116078), ![][flag_IT] [Roxas](https://osu.ppy.sh/users/1041833), ![][flag_US] [ztrot](https://osu.ppy.sh/users/6347) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
>  - [osu!mania 2014 sur Twitch](https://www.twitch.tv/osulive)
```suggestion
- [Livestream](https://www.twitch.tv/osulive)
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +![](img/brackets-4K.jpg "MWC 2014 Bracket 4K")
```suggestion
![](img/brackets-4K.jpg "Bracket 4K de la MWC 2014")
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +![](img/brackets-7K.jpg "MWC 2014 Bracket 7K")
```suggestion
![](img/brackets-7K.jpg "Bracket 7K de la MWC")
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_NL] | **Pays-Bas** | *retired* |
```suggestion
| ![][flag_NL] | **Pays-Bas** | *abandon* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![][flag_ES] | **Espagne** | *disbanded* |
```suggestion
| ![][flag_ES] | **Espagne** | *dissoute* |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Places | Bracket 4K | Bracket 7K |
```suggestion
| Classement | Bracket 4K | Bracket 7K |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![Gold crown](/wiki/shared/crown-gold.png "1ère place") | ![][flag_KR] **Corée du Sud** (**[ideu-](https://osu.ppy.sh/users/137227)**, [Abcdullah](https://osu.ppy.sh/users/4140104), [FaL3C\_ChoBo](
```suggestion
| ![Couronne en or](/wiki/shared/crown-gold.png "1ère place") | ![][flag_KR] **Corée du Sud** (**[ideu-](https://osu.ppy.sh/users/137227)**, [Abcdullah](https://osu.ppy.sh/users/4140104), [FaL3C\_ChoBo](https://osu.ppy.sh/users/1218632), [jhlee0133](https://osu.ppy.sh/users/140148)) | ![][flag_KR] **Corée du Sud** (**[ideu-](https://osu.ppy.sh/users/137227)**, [Abcdullah](https://osu.ppy.sh/users/4140104), [jhlee0133](https://osu.ppy.sh/users/140148), [WindyS](https://osu.ppy.sh/users/1190879)) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![Silver crown](/wiki/shared/crown-silver.png "2ème place") | ![][flag_PH] **Philippines** (**[Tokiiwa](https://osu.ppy.sh/users/4029511)**, [Ainyan](https://osu.ppy.sh/users/3770641), [arcwinolivi
```suggestion
| ![Couronne d'argent](/wiki/shared/crown-silver.png "2ème place") | ![][flag_PH] **Philippines** (**[Tokiiwa](https://osu.ppy.sh/users/4029511)**, [Ainyan](https://osu.ppy.sh/users/3770641), [arcwinolivirus](https://osu.ppy.sh/users/2039089)) | ![][flag_TH] **Thaïlande** (**[lostcool](https://osu.ppy.sh/users/766374)**, [Mystical Faith](https://osu.ppy.sh/users/4280188), [Popo\[Mikoto\]](https://osu.ppy.sh/users/445236)) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3ème place") | ![][flag_MY] **Malaisie** (**[Gon](https://osu.ppy.sh/users/583765)**, [\_Sylveon\_](https://osu.ppy.sh/users/3936677), [LongGone](http
```suggestion
| ![Couronne de bronze](/wiki/shared/crown-bronze.png "3ème place") | ![][flag_MY] **Malaisie** (**[Gon](https://osu.ppy.sh/users/583765)**, [\_Sylveon\_](https://osu.ppy.sh/users/3936677), [LongGone](https://osu.ppy.sh/users/35882), [ZYuan](https://osu.ppy.sh/users/3337688)) | ![][flag_MY] **Malaisie** (**[Gon](https://osu.ppy.sh/users/583765)**, [\_Sylveon\_](https://osu.ppy.sh/users/3936677), [LongGone](https://osu.ppy.sh/users/35882)) |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +#### Semi-finales
```suggestion
#### Demi-finales
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +#### Semi-finales
```suggestion
#### Demi-finales
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +#### Phase de groupe
```suggestion
#### Phase de groupes
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +#### Phase de groupe
```suggestion
#### Phase de groupes
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +#### Phase de groupe
```suggestion
#### Phase de groupes
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Place | Prix |
```suggestion
| Classement | Prix |
```

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
>  | Phase de poules (7K) | 16-17 Août 2014 |
etc. for dates below

2022-07-24 18:25 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +[flag_NL]: /wiki/shared/flag/NL.gif "Pays-bas"
```suggestion
[flag_NL]: /wiki/shared/flag/NL.gif "Pays-Bas"
```

2022-07-24 18:40 UTC, Soetch commented
> I will check this again later because it might need another review. 
> Looks like stuff was missing or still outdated.

Thanks a lot, I'll be merging your changes soon.
This is a PR I've done really fast and I'm sure it has a lot of typo and things, I'm sorry for that.

2022-08-03 19:22 UTC, TPGPL commented
fixed conflicts, should be ready to review now

2022-08-03 19:31 UTC, Ganondorf-1 requested changes

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ::{ flag=RU }:: | **Russie** | **[Daleenie](https://osu.ppy.sh/users/1540597)**, [Kiviman](https://osu.ppy.sh/users/2790640) |
```suggestion
| ::{ flag=RU }:: | **Fédération de Russie** | **[Daleenie](https://osu.ppy.sh/users/1540597)**, [Kiviman](https://osu.ppy.sh/users/2790640) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ::{ flag=RU }:: | **Russie** | **[Daleenie](https://osu.ppy.sh/users/1540597)**, [Kiviman](https://osu.ppy.sh/users/2790640) |
```suggestion
| ::{ flag=RU }:: | **Fédération de Russie** | **[Daleenie](https://osu.ppy.sh/users/1540597)**, [Kiviman](https://osu.ppy.sh/users/2790640) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ::{ flag=AR }:: Argentine | ::{ flag=CZ }:: Tchéquie | ::{ flag=RU }:: Russie | ::{ flag=PL }:: Pologne |
```suggestion
| ::{ flag=AR }:: Argentine | ::{ flag=CZ }:: Tchéquie | ::{ flag=RU }:: Fédération de Russie | ::{ flag=PL }:: Pologne |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| ::{ flag=DE }:: Allemagne | ::{ flag=RU }:: Russie | ::{ flag=JP }:: Japon | ::{ flag=GB }:: Royaume-Uni |
```suggestion
| ::{ flag=DE }:: Allemagne | ::{ flag=RU }:: Fédération de Russie | ::{ flag=JP }:: Japon | ::{ flag=GB }:: Royaume-Uni |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Russie ::{ flag=RU }:: | 0 | **5** | ::{ flag=KR }:: **Corée du Sud** | [#1](https://osu.ppy.sh/community/matches/8744011) |
```suggestion
| Fédération de Russie ::{ flag=RU }:: | 0 | **5** | ::{ flag=KR }:: **Corée du Sud** | [#1](https://osu.ppy.sh/community/matches/8744011) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Russie** ::{ flag=RU }:: | **4** | 3 | ::{ flag=NZ }:: Nouvelle-Zélande | [#1](https://osu.ppy.sh/community/matches/8429172) |
```suggestion
| **Fédération de Russie** ::{ flag=RU }:: | **4** | 3 | ::{ flag=NZ }:: Nouvelle-Zélande | [#1](https://osu.ppy.sh/community/matches/8429172) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=MY }:: **Malaisie** | [#1](https://osu.ppy.sh/community/matches/8429937) |
```suggestion
| Fédération de Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=MY }:: **Malaisie** | [#1](https://osu.ppy.sh/community/matches/8429937) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=JP }:: **Japon** | [#1](https://osu.ppy.sh/community/matches/8454720) |
```suggestion
| Fédération de Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=JP }:: **Japon** | [#1](https://osu.ppy.sh/community/matches/8454720) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=GB }:: **Royaume-Uni** | [#1](https://osu.ppy.sh/community/matches/8456621) |
```suggestion
| Fédération de Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=GB }:: **Royaume-Uni** | [#1](https://osu.ppy.sh/community/matches/8456621) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Japon** ::{ flag=JP }:: | **5** | 0 | ::{ flag=RU }:: Russie | [#1](https://osu.ppy.sh/community/matches/8772820) |
```suggestion
| **Japon** ::{ flag=JP }:: | **5** | 0 | ::{ flag=RU }:: Fédération de Russie | [#1](https://osu.ppy.sh/community/matches/8772820) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Pologne** ::{ flag=PL }:: | **4** | 2 | ::{ flag=RU }:: Russie | [#1](https://osu.ppy.sh/community/matches/8573871) |
```suggestion
| **Pologne** ::{ flag=PL }:: | **4** | 2 | ::{ flag=RU }:: Fédération de Russie | [#1](https://osu.ppy.sh/community/matches/8573871) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=CN }:: **China** | [#1](https://osu.ppy.sh/community/matches/8584000) |
```suggestion
| Fédération de Russie ::{ flag=RU }:: | 0 | **4** | ::{ flag=CN }:: **China** | [#1](https://osu.ppy.sh/community/matches/8584000) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +| **Hong Kong** ::{ flag=HK }:: | **4** | 1 | ::{ flag=RU }:: Russie | [#1](https://osu.ppy.sh/community/matches/8585131) |
```suggestion
| **Hong Kong** ::{ flag=HK }:: | **4** | 1 | ::{ flag=RU }:: Fédération de Russie | [#1](https://osu.ppy.sh/community/matches/8585131) |
```

2022-08-03 19:31 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
>     - 9 durant les phases de Poules
```suggestion
   - 9 durant les phases de poules.
```

2022-08-03 20:18 UTC, Ganondorf-1 requested changes

2022-08-03 20:18 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
>  1. Une salle multijoueurs sera créée par un arbitre 20 minutes avant le début du match. Les équipes sont tenues de se rassembler durant cette période.
```suggestion
1. Une salle multijoueur sera créée par un arbitre 20 minutes avant le début du match. Les équipes sont tenues de se rassembler durant cette période.
```

2022-08-03 20:18 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
>     - 11 durant les huitièmes et quarts de finales
```suggestion
   - 11 durant les huitièmes et quarts de finales.
```

2022-08-03 20:42 UTC, Ganondorf-1 requested changes
Missed this, should be good otherwise

2022-08-03 20:42 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2014/fr.md
> +6. La catégorie FreeMod sera joué avec le mode FreeMod activé. Chaque joueur pourra choisir [Hidden](/wiki/Game_modifier/Hidden), [Flashlight](/wiki/Game_modifier/Flashlight) ou [FadeIn](/wiki/Game_m
```suggestion
6. La catégorie FreeMod sera jouée avec les mods libres activés. Chaque joueur pourra choisir [Hidden](/wiki/Game_modifier/Hidden), [Flashlight](/wiki/Game_modifier/Flashlight) ou [FadeIn](/wiki/Game_modifier/Fade_In) ou aucun mod.
```

2022-08-03 20:42 UTC, TPGPL approved these changes

2022-08-03 20:48 UTC, merged