[FR] Updated `OWC/2014`.
ppy/osu-wiki pull request #7656
Opened 2022-07-16 13:54 UTC by Soetch

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-29 09:14 UTC, Pisapou commented on wiki/Tournaments/OWC/2014/fr.md
> +  1. **[Dark PHOENiX - The Primal Scene of Japon the Girl Saw (sjoy) \[Extra\]](https://osu.ppy.sh/beatmapsets/121635#osu/311573)**
```suggestion
  1. **[Dark PHOENiX - The Primal Scene of Japan the Girl Saw (sjoy) \[Extra\]](https://osu.ppy.sh/beatmapsets/121635#osu/311573)**
```

2022-07-29 09:14 UTC, Pisapou commented on wiki/Tournaments/OWC/2014/fr.md
> +[flag_FI]: /wiki/shared/flag/FI.gif "Finlandee"
```suggestion
[flag_FI]: /wiki/shared/flag/FI.gif "Finlande"
```

2022-08-03 16:51 UTC, TPGPL commented
heavily updated the translation, should be ready to review now

2022-08-03 19:11 UTC, Ganondorf-1 requested changes

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +7. The FreeMod bracket will have FreeMod activated. Every individual player can pick Hidden, HardRock, Flashlight or no mod at all.
```suggestion
7. Le bracket Freemod activera les mods libres. Chaque joueur peut choisir de jouer avec Hidden, HardRock, Flashlight, ou aucun mod.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +8. Players may select more than one mode.
```suggestion
8. Les joueurs peuvent sélectionner autant de mods qu'ils le souhaitent.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +9. When playing a FreeMod map, at least 2 players of each team must have minimum one mode activated.
```suggestion
9. Lorsqu'une beatmap FreeMod est jouée, au moins 2 joueurs de chaque équipe doivent avoir 1 mod d'activé.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +10. The tiebreaker will be played under FreeMod conditions.
```suggestion
10. Le tiebreaker sera joué avec les mods libres.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +11. When playing the tiebreaker, no one needs to have a mode activated.
```suggestion
11. Aucun joueur n'est obligé d'utiliser des mods pour jouer le tiebreaker.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +12. The size of the NoMod bracket will be 6 in all stages.
```suggestion
12. Le bracket NoMod contiendra 6 beatmaps dans tous les mappools.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +13. The size of the mod-specific brackets will be 3 in all stages.
```suggestion
13. Les brackets avec mods contiendront 3 beatmaps dans tous les mappools.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +5. Les capitaines sont responsables de la disponibilité de leurs équipes. Les équipes sont assez grande pour permettre à chaque équipe d'avoir au moins trois joueurs pour chaque match. Si des équipes
```suggestion
5. Les capitaines sont responsables de la disponibilité de leurs équipes. Les équipes sont assez grandes pour permettre à chaque équipe d'avoir au moins trois joueurs pour chaque match. Si des équipes ne peuvent pas fournir trois joueurs pour un match, l'équipe sera considérée comme ayant déclaré forfait pour ce match.
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Brézil ::{ flag=BR }:: | 0 | **4** | ::{ flag=JP }:: **Japon** | [#1](https://osu.ppy.sh/community/matches/10349350) |
```suggestion
| Brésil ::{ flag=BR }:: | 0 | **4** | ::{ flag=JP }:: **Japon** | [#1](https://osu.ppy.sh/community/matches/10349350) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Pays-Bass** ::{ flag=NL }:: | **4** | 2 | ::{ flag=PL }:: Polande | [#1](https://osu.ppy.sh/community/matches/10353347) |
```suggestion
| **Pays-Bas** ::{ flag=NL }:: | **4** | 2 | ::{ flag=PL }:: Pologne | [#1](https://osu.ppy.sh/community/matches/10353347) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Norvège ::{ flag=NO }:: | 1 | **4** | ::{ flag=TW }:: **Taiwan** | [#1](https://osu.ppy.sh/community/matches/10348348) |
```suggestion
| Norvège ::{ flag=NO }:: | 1 | **4** | ::{ flag=TW }:: **Taïwan** | [#1](https://osu.ppy.sh/community/matches/10348348) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Malaisie ::{ flag=MY }:: | 2 | **4** | ::{ flag=RU }:: **Russie** | [#1](https://osu.ppy.sh/community/matches/10350512) |
```suggestion
| Malaisie ::{ flag=MY }:: | 2 | **4** | ::{ flag=RU }:: **Fédération de Russie** | [#1](https://osu.ppy.sh/community/matches/10350512) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Indonésie** ::{ flag=ID }:: | **4** | 0 | ::{ flag=CL }:: Chili | *win by default* |
```suggestion
| **Indonésie** ::{ flag=ID }:: | **4** | 0 | ::{ flag=CL }:: Chili | *victoire par défaut* |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Suède ::{ flag=SE }:: | 1 | **4** | ::{ flag=TW }:: **Taiwan** | [#1](https://osu.ppy.sh/community/matches/10353334) |
```suggestion
| Suède ::{ flag=SE }:: | 1 | **4** | ::{ flag=TW }:: **Taïwan** | [#1](https://osu.ppy.sh/community/matches/10353334) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Lituanie ::{ flag=LT }:: | 2 | **4** | ::{ flag=TW }:: **Taiwan** | [#1](https://osu.ppy.sh/community/matches/10315808) |
```suggestion
| Lituanie ::{ flag=LT }:: | 2 | **4** | ::{ flag=TW }:: **Taïwan** | [#1](https://osu.ppy.sh/community/matches/10315808) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Hong Kong ::{ flag=HK }:: | 0 | **4** | ::{ flag=NL }:: **Pays-Bass** | [#1](https://osu.ppy.sh/community/matches/10317030) |
```suggestion
| Hong Kong ::{ flag=HK }:: | 0 | **4** | ::{ flag=NL }:: **Pays-Bas** | [#1](https://osu.ppy.sh/community/matches/10317030) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Danemark ::{ flag=DK }:: | 1 | **4** | ::{ flag=RU }:: **Russie** | [#1](https://osu.ppy.sh/community/matches/10318251) |
```suggestion
| Danemark ::{ flag=DK }:: | 1 | **4** | ::{ flag=RU }:: **Fédération de Russie** | [#1](https://osu.ppy.sh/community/matches/10318251) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Hong Kong ::{ flag=HK }:: | 0 | **4** | ::{ flag=PL }:: **Polande** | [#1](https://osu.ppy.sh/community/matches/10319710) |
```suggestion
| Hong Kong ::{ flag=HK }:: | 0 | **4** | ::{ flag=PL }:: **Pologne** | [#1](https://osu.ppy.sh/community/matches/10319710) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Canada ::{ flag=CA }:: | 0 | **4** | ::{ flag=PL }:: **Polande** | [#1](https://osu.ppy.sh/community/matches/10328588) |
```suggestion
| Canada ::{ flag=CA }:: | 0 | **4** | ::{ flag=PL }:: **Pologne** | [#1](https://osu.ppy.sh/community/matches/10328588) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Canada ::{ flag=CA }:: | 2 | **4** | ::{ flag=NL }:: **Pays-Bass** | [#1](https://osu.ppy.sh/community/matches/10330997) |
```suggestion
| Canada ::{ flag=CA }:: | 2 | **4** | ::{ flag=NL }:: **Pays-Bas** | [#1](https://osu.ppy.sh/community/matches/10330997) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Ukraine** ::{ flag=UA }:: | **4** | 2 | ::{ flag=BR }:: Brézil | [#1](https://osu.ppy.sh/community/matches/10331007) |
```suggestion
| **Ukraine** ::{ flag=UA }:: | **4** | 2 | ::{ flag=BR }:: Brésil | [#1](https://osu.ppy.sh/community/matches/10331007) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Mexique ::{ flag=MX }:: | 0 | **4** | ::{ flag=BR }:: **Brézil** | [#1](https://osu.ppy.sh/community/matches/10332927) |
```suggestion
| Mexique ::{ flag=MX }:: | 0 | **4** | ::{ flag=BR }:: **Brésil** | [#1](https://osu.ppy.sh/community/matches/10332927) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Polande** ::{ flag=PL }:: | **5** | 1 | ::{ flag=FR }:: France | [#1](https://osu.ppy.sh/community/matches/10517306) |
```suggestion
| **Pologne** ::{ flag=PL }:: | **5** | 1 | ::{ flag=FR }:: France | [#1](https://osu.ppy.sh/community/matches/10517306) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Australie ::{ flag=AU }:: | 2 | **5** | ::{ flag=NL }:: **Pays-Bass** | [#1](https://osu.ppy.sh/community/matches/10508932) |
```suggestion
| Australie ::{ flag=AU }:: | 2 | **5** | ::{ flag=NL }:: **Pays-Bas** | [#1](https://osu.ppy.sh/community/matches/10508932) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Ukraine** ::{ flag=UA }:: | **5** | 1 | ::{ flag=TW }:: Taiwan | [#1](https://osu.ppy.sh/community/matches/10509978) |
```suggestion
| **Ukraine** ::{ flag=UA }:: | **5** | 1 | ::{ flag=TW }:: Taïwan | [#1](https://osu.ppy.sh/community/matches/10509978) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Allemagne** ::{ flag=DE }:: | **5** | 3 | ::{ flag=RU }:: Russie | [#1](https://osu.ppy.sh/community/matches/10518861) |
```suggestion
| **Allemagne** ::{ flag=DE }:: | **5** | 3 | ::{ flag=RU }:: Fédération de Russie | [#1](https://osu.ppy.sh/community/matches/10518861) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Polande** ::{ flag=PL }:: | **5** | 2 | ::{ flag=KR }:: Corée du Sud | [#1](https://osu.ppy.sh/community/matches/10669681) |
```suggestion
| **Pologne** ::{ flag=PL }:: | **5** | 2 | ::{ flag=KR }:: Corée du Sud | [#1](https://osu.ppy.sh/community/matches/10669681) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Allemagne** ::{ flag=DE }:: | **5** | 4 | ::{ flag=NL }:: Pays-Bass | [#1](https://osu.ppy.sh/community/matches/10671115) |
```suggestion
| **Allemagne** ::{ flag=DE }:: | **5** | 4 | ::{ flag=NL }:: Pays-Bas | [#1](https://osu.ppy.sh/community/matches/10671115) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Russie** ::{ flag=RU }:: | **5** | 1 | ::{ flag=AU }:: Australie | [#1](https://osu.ppy.sh/community/matches/10635177) |
```suggestion
| **Fédération de Russie** ::{ flag=RU }:: | **5** | 1 | ::{ flag=AU }:: Australie | [#1](https://osu.ppy.sh/community/matches/10635177) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| **Taiwan** ::{ flag=TW }:: | **5** | 2 | ::{ flag=GB }:: Royaume-Uni | [#1](https://osu.ppy.sh/community/matches/10636683) |
```suggestion
| **Taïwan** ::{ flag=TW }:: | **5** | 2 | ::{ flag=GB }:: Royaume-Uni | [#1](https://osu.ppy.sh/community/matches/10636683) |
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Samedi, 13 Decembre 2014:
```suggestion
Samedi 13 décembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Samedi, 6 Decembre 2014:
```suggestion
Samedi 6 décembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Samedi, 29 Novembre 2014:
```suggestion
Samedi 29 novembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Dimanche, 30 Novembre 2014:
```suggestion
Dimanche 30 novembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Samedi, 22 Novembre 2014:
```suggestion
Samedi 22 novembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Dimanche, 23 Novembre 2014:
```suggestion
Dimanche 23 novembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Dimanche, 16 Novembre 2014:
```suggestion
Dimanche 16 novembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Samedi, 8 Novembre 2014:
```suggestion
Samedi 8 novembre 2014 :
```

2022-08-03 19:11 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +Dimanche, 9 Novembre 2014:
```suggestion
Dimanche 9 novembre 2014 :
```

2022-08-03 20:36 UTC, Ganondorf-1 requested changes
Should be good to go once this is applied

2022-08-03 20:36 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +| Lien du match ::{ flag=AR }:: | 0 | **5** | ::{ flag=JP }:: **Japon** | [#1](https://osu.ppy.sh/community/matches/10638992) |
```suggestion
| Argentine ::{ flag=AR }:: | 0 | **5** | ::{ flag=JP }:: **Japon** | [#1](https://osu.ppy.sh/community/matches/10638992) |
```

2022-08-03 20:36 UTC, Ganondorf-1 commented on wiki/Tournaments/OWC/2014/fr.md
> +2. Chaque mappool contient 5 brackets : NoMod, HardRock, Hidden, DoubleTime et FreeMod
```suggestion
2. Chaque mappool contient 5 brackets : NoMod, HardRock, Hidden, DoubleTime et FreeMod.
```

2022-08-03 20:42 UTC, TPGPL approved these changes

2022-08-03 20:43 UTC, merged