[FR] Updated Translation Tags from Outdated.
ppy/osu-wiki pull request #7657
Opened 2022-07-16 14:04 UTC by Soetch

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-16 19:30 UTC, DoryanR commented
Hi, for me there is not only the tags which are to be added, several incoherence this is between the French and English version, it misses whole sections.

If I should give you an advice, I would tell you to take the english file, copy it entirely, and replace the content of the french file by the one you just copied, and you re-translate.

This will be the easiest way for tournament articles.

- [ ] Please do not merge until the article is really updated.

2022-07-16 19:31 UTC, Soetch commented
> Hi, for me there is not only the tags which are to be added, several incoherence this is between the French and English version, it misses whole sections.
> 
> If I should give you an advice, I would tell you to take the english file, copy it entirely, and replace the content of the french file by the one you just copied, and you re-translate.
> 
> This will be the easiest way for tournament articles.
> 
>     * [ ]  Please do not merge until the article is really updated.

Gosh, I'm working on it then.

2022-07-16 19:44 UTC, Soetch commented
> Hi, for me there is not only the tags which are to be added, several incoherence this is between the French and English version, it misses whole sections.
> 
> If I should give you an advice, I would tell you to take the english file, copy it entirely, and replace the content of the french file by the one you just copied, and you re-translate.
> 
> This will be the easiest way for tournament articles.
> 
>     * [ ]  Please do not merge until the article is really updated.

The article is updated, the "groups" section and podium was missing. Sorry for making you losing time like this.

2022-08-02 18:58 UTC, TPGPL commented
updated the translation to be up-to-date information-wise, should be ready to review now

2022-08-02 20:16 UTC, Ganondorf-1 requested changes

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +| ![Couronne en argent](/wiki/shared/crown-silver.png "2ème place") | 80 $ par membre de l'équipe, pins et objets osu! exclusifs, un badge sur le profil |
```suggestion
| ![Couronne d'argent](/wiki/shared/crown-silver.png "2ème place") | 80 $ par membre de l'équipe, un badge de profil unique, de la marchandise exclusive d'osu! |
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +![MWC 4K 2017 Logo](img/logo.jpg)
```suggestion
![Logo de la MWC 4K 2017](img/logo.jpg)
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
>  La **osu!mania 4K World Cup 2017** (***MWC 4K 2017***) est un tournoi d'osu!mania entre pays organisé par [l'équipe osu!](/wiki/People/The_Team). Il s'agit de la quatrième édition de la osu!mania Wor
```suggestion
L'**osu!mania 4K World Cup 2017** (***MWC 4K 2017***) est un tournoi d'osu!mania 4 par pays organisé par [l'équipe osu!](/wiki/People/The_Team). Il s'agit de la quatrième édition de l'osu!mania 4K World Cup.
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +| ![Couronne en or](/wiki/shared/crown-gold.png "1ère place") | 150 $ par membre de l'équipe, pins et objets osu! exclusifs, un badge sur le profil, et le titre « osu!mania Champion » pendant un an |
```suggestion
| ![Couronne en or](/wiki/shared/crown-gold.png "1ère place") | 150 $ par membre de l'équipe, un badge de profil unique, de la marchandise exclusive d'osu!, le titre "osu!mania Champion" pendant un an |
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +| ![Couronne en bronze](/wiki/shared/crown-bronze.png "3ème place") | 40 $ par membre de l'équipe, pins et objets osu! exclusifs, un badge sur le profil |
```suggestion
| ![Couronne de bronze](/wiki/shared/crown-bronze.png "3ème place") | 40 $ par membre de l'équipe, un badge de profil unique, de la marchandise exclusive d'osu! |
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +![](img/badge.jpg "MWC 4K 2017 winner badge") ![](img/badge2.jpg "MWC 4K 2017 2nd place badge") ![](img/badge3.jpg "MWC 4K 2017 3rd place badge")
```suggestion
![](img/badge.jpg "Badge des gagnants de la MWC 4K 2017") ![](img/badge2.jpg "Badge de la 2ème place de la MWC 4K 2017") ![](img/badge3.jpg "Badge de la 3ème place de la MWC 4K 2017")
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +L'osu!mania 4K World Cup 2017 était organisée par plusieurs membres de la communauté
```suggestion
L'osu!mania 4K World Cup 2017 était organisée par divers membres de la communauté.
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
>  - **[Statistiques générales, groupes et plus!](https://docs.google.com/spreadsheets/d/1qAbKpW3yCJ5U2qUoUoIob6qsmNW08LenxeL0FptdjxA/pubhtml)**
```suggestion
- **[Statistiques générales, groupes et plus !](https://docs.google.com/spreadsheets/d/1qAbKpW3yCJ5U2qUoUoIob6qsmNW08LenxeL0FptdjxA/pubhtml)**
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
>  - [Topic de discussion](https://osu.ppy.sh/community/forums/topics/615787)
```suggestion
- [Fil de discussion](https://osu.ppy.sh/community/forums/topics/615787)
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +![](img/bracket.jpg "MWC 4K 2017 bracket")
```suggestion
![](img/bracket.jpg "Bracket de la MWC 4K 2017")
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +![](img/podium.jpg "MWC 4K 2017 podium")
```suggestion
![](img/podium.jpg "Podium de la MWC 4K 2017")
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Samedi, 9 Septembre 2017:
```suggestion
Samedi 9 septembre 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Dimanche, 10 Septembre 2017:
```suggestion
Dimanche 10 septembre 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Samedi, 2 Septembre 2017:
```suggestion
Samedi 2 septembre 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Dimanche, 3 Septembre 2017:
```suggestion
Dimanche 3 septembre 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Samedi, 26 Août 2017:
```suggestion
Samedi 26 août 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Dimanche, 27 Août 2017:
```suggestion
Dimanche 27 août 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Dimanche, 20 Août 2017:
```suggestion
Dimanche 20 août 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Samedi, 12 Août 2017:
```suggestion
Samedi 12 août 2017 :
```

2022-08-02 20:16 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +Dimanche, 13 Août 2017:
```suggestion
Dimanche 13 août 2017 :
```

2022-08-03 09:37 UTC, Ganondorf-1 requested changes

2022-08-03 09:37 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +L'**osu!mania 4K World Cup 2017** (***MWC 4K 2017***) est un tournoi d'osu!mania 4 par pays organisé par [l'équipe osu!](/wiki/People/The_Team). Il s'agit de la quatrième édition de l'osu!mania 4K Wo
```suggestion
L'**osu!mania 4K World Cup 2017** (***MWC 4K 2017***) est un tournoi d'osu!mania 4K par pays organisé par [l'équipe osu!](/wiki/People/The_Team). Il s'agit de la quatrième édition de l'osu!mania 4K World Cup.
```

2022-08-03 09:37 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +| **A** | ::{ flag=BR }:: Brésil | ::{ flag=PL }:: Polognee | ::{ flag=PH }:: Philippines | ::{ flag=VE }:: Venezuela |
```suggestion
| **A** | ::{ flag=BR }:: Brésil | ::{ flag=PL }:: Pologne | ::{ flag=PH }:: Philippines | ::{ flag=VE }:: Venezuela |
```

2022-08-03 09:37 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +| **C** | ::{ flag=CN }:: Chine | ::{ flag=FR }:: France | ::{ flag=AU }:: Australie | ::{ flag=TW }:: Taiwan |
```suggestion
| **C** | ::{ flag=CN }:: Chine | ::{ flag=FR }:: France | ::{ flag=AU }:: Australie | ::{ flag=TW }:: Taïwan |
```

2022-08-03 09:37 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +| **E** | ::{ flag=KR }:: Corée du Sud | ::{ flag=SE }:: Suède | ::{ flag=RU }:: Russian Federation | ::{ flag=FI }:: Finland |
```suggestion
| **E** | ::{ flag=KR }:: Corée du Sud | ::{ flag=SE }:: Suède | ::{ flag=RU }:: Fédération de Russie | ::{ flag=FI }:: Finlande |
```

2022-08-03 09:37 UTC, Ganondorf-1 commented on wiki/Tournaments/MWC/2017_4K/fr.md
> +| **F** | ::{ flag=ID }:: Indonesie | ::{ flag=IT }:: Italie | ::{ flag=ES }:: Espagne | ::{ flag=NZ }:: Nouvelle-Zélande |
```suggestion
| **F** | ::{ flag=ID }:: Indonésie | ::{ flag=IT }:: Italie | ::{ flag=ES }:: Espagne | ::{ flag=NZ }:: Nouvelle-Zélande |
```

2022-08-03 14:46 UTC, Ganondorf-1 approved these changes

2022-08-03 16:00 UTC, TPGPL approved these changes

2022-08-03 16:14 UTC, merged