[FR] Removed Outdated Tag.
ppy/osu-wiki pull request #7659
Opened 2022-07-16 16:28 UTC by Soetch

I did the verification with the en.md version, and nothing is outdated.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-16 19:39 UTC, DoryanR commented
I'm not sure how you checked the article, but there are some glaring differences:

Example here, with the table which is not the same

![Code_y8T6HCNKL1](https://user-images.githubusercontent.com/55928127/179369663-a91013e2-9aa0-4462-9c2f-355cb453d6fd.png)

Or this more subtle formatting difference

![Code_ZQoDjZzgSR](https://user-images.githubusercontent.com/55928127/179369599-5911f711-d9fb-4cd5-aa15-130845ec3a09.png)

For me the article is not at all up to date, and needs further checking.

- [ ] Please don't merge while waiting for a real update of the article.

2022-07-16 20:03 UTC, Soetch commented
Is it better now ? I see no more differences, I updated the badge and the table, with other minor changes. Sorry for making this much errors, I'll try working at another thing on this project, ahah.

2022-08-02 15:50 UTC, TPGPL requested changes
match results are using outdated formatting + they are missing at least 18 lines

2022-08-02 18:00 UTC, TPGPL approved these changes
brought formatting up-to-date

2022-08-02 18:13 UTC, Ganondorf-1 requested changes

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
>  | ![Couronne en argent](/wiki/shared/crown-silver.png "2ème place") | Une bannière d'équipe exclusive |
```suggestion
| ![Couronne d'argent](/wiki/shared/crown-silver.png "2ème place") | Une bannière d'équipe exclusive |
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
>  | ![Couronne en bronze](/wiki/shared/crown-bronze.png "3ème place") | Une bannière d'équipe exclusive |
```suggestion
| ![Couronne de bronze](/wiki/shared/crown-bronze.png "3ème place") | Une bannière d'équipe exclusive |
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +![](img/badge.png "Badge du vainqueur de l'AGTS 2019")
```suggestion
![](img/badge.png "Badge des gagnants de l'AGTS 2019")
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +| Editeur du Wiki | ::{ flag=ID }:: [fajar13k](https://osu.ppy.sh/users/7100002) |
```suggestion
| Éditeur du Wiki | ::{ flag=ID }:: [fajar13k](https://osu.ppy.sh/users/7100002) |
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +- [Serveur Discord de l'GTS](https://discord.gg/3mGC3HB)
```suggestion
- [Serveur Discord du GTS](https://discord.gg/3mGC3HB)
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +| ![Couronne d'or](/wiki/shared/crown-gold.png "1ère place") | ::{ flag=JP }:: Japon |
```suggestion
| ![Couronne en or](/wiki/shared/crown-gold.png "1ère place") | ::{ flag=JP }:: Japon |
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Samedi, 14 Septembre 2019:
```suggestion
Samedi 14 septembre 2019 :
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Samedi, 7 Septembre 2019:
```suggestion
Samedi 7 septembre 2019 :
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Dimanche, 8 Septembre 2019:
```suggestion
Dimanche 8 septembre 2019 :
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Samedi, 31 Aout 2019:
```suggestion
Samedi 31 août 2019 :
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Dimanche, 1 Septembre 2019:
```suggestion
Dimanche 1 septembre 2019 :
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Samedi, 24 Aout 2019:
```suggestion
Samedi 24 août 2019 :
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Dimanche, 25 Aout 2019:
```suggestion
Dimanche 25 août 2019 : 
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Samedi, 17 Aout 2019:
```suggestion
Samedi 17 août 2019 :
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +Dimanche, 18 Aout 2019:
```suggestion
Dimanche 18 août 2019 : 
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
>  - [Thread de discussion](https://osu.ppy.sh/community/forums/topics/931003)
```suggestion
- [Fil de discussion](https://osu.ppy.sh/community/forums/topics/931003)
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
>  ## Liste des beatmaps
```suggestion
## Mappools
```

2022-08-02 18:13 UTC, Ganondorf-1 commented on wiki/Tournaments/GTS/AGTS_2019/fr.md
> +| ![Couronne d'argent](/wiki/shared/crown-silver.png "2nde place") | ::{ flag=CA }:: Canada |
```suggestion
| ![Couronne d'argent](/wiki/shared/crown-silver.png "2ème place") | ::{ flag=CA }:: Canada |
```

2022-08-02 19:44 UTC, Ganondorf-1 approved these changes

2022-08-02 20:15 UTC, TPGPL approved these changes

2022-08-02 20:16 UTC, merged