Use new flag style across the wiki
ppy/osu-wiki pull request #7681
Opened 2022-07-21 18:43 UTC by TPGPL

Updates the flag style across the wiki to the new syntax, and also updates the ASC and tournament template

PR uses the following regexes (two first commits exclude the `./wiki/Article_styling_criteria` folder as it needed to be fixed separately):

- `d589ad6694926ff81cac892687fadf1d50af83b9`
  - `\n(\[flag_(__|[A-Z]{2})\]: /wiki/shared/flag/(__|[A-Z]{2}).gif( ".[^"]*")?\n){1,}` -> blank
- `2301d6e44e98d91d26b27a0112c7de5e8ffac12a` and `b8caf2331ff7130fefd5254c1346a2545cd0bf43`
  - `!\[\]\[flag_([A-Z]{2}|__)\]` -> `::{ flag=$1 }::`
- `15956b590fd4dfcf6eb3f5d05d455966d441675c`
  - `\[flag` to find broken flags, fixed manually
- `3777a78ba83a57e65cc715539096d1ba3f1ed74e`
  -  `\/flag` to find weird flag syntaxes
  - `!\[\]\(/wiki/shared/flag/([A-Z]{2})\.gif\)` -> `::{ flag=$1 }::`
  - `!\[\]\[([A-Z]{2}|__)\]` -> `::{ flag=$1 }::`, references removed manually

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-07-21 22:29 UTC, cl8n commented
RockRoller said he would split #7601 but ig i review this one instead..? should probably have coordinated this better

2022-07-22 00:25 UTC, cl8n requested changes

2022-07-22 03:52 UTC, cl8n commented
ended up rebasing whole thing so that each automated change is correct on its own and doesn't rely on later manual fixes. the final diff is same as before

2022-07-22 03:53 UTC, cl8n approved these changes

2022-07-25 14:28 UTC, peppy approved these changes

2022-07-25 14:59 UTC, merged