[FR] Update `People/Community_Contributors`
ppy/osu-wiki pull request #7695
Opened 2022-07-24 20:30 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-24 20:30 UTC, Pisapou commented on wiki/People/Community_Contributors/fr.md
> +| ::{ flag=FR }:: [Kasumi-sama](https://osu.ppy.sh/users/6177263) | Contribution exceptionnelle à la scène des tournois de la communauté osu!taiko |
```suggestion
| ::{ flag=FR }:: [Kasumi-sama](https://osu.ppy.sh/users/6177263) | Contribution exceptionnelle aux tournois de la communauté osu!taiko |
```

2022-07-24 20:33 UTC, Soetch reviewed
Good translation after some trouble finding the good word between "exceptionnelle" and "remarquable".

2022-07-24 20:33 UTC, Ganondorf-1 requested changes

2022-07-24 20:33 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ::{ flag=SE }:: [Walavouchey](https://osu.ppy.sh/users/5773079) | Contribution exceptionnelle au projet wiki d'osu! |
```suggestion
| ::{ flag=SE }:: [Walavouchey](https://osu.ppy.sh/users/5773079) | Contribution exceptionnelle au projet osu! wiki |
```

2022-07-24 20:33 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ::{ flag=RU }:: [StanR](https://osu.ppy.sh/users/7217455) | Contribution exceptionnelle au développement et à la maintenance des points de performance d'osu!|
```suggestion
| ::{ flag=RU }:: [StanR](https://osu.ppy.sh/users/7217455) | Contribution exceptionnelle au développement et à la maintenance des points de performance d'osu! |
```

2022-07-24 20:33 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ::{ flag=ID }:: [Niva](https://osu.ppy.sh/users/197805) | Contribution exceptionnelle au projet wiki d'osu! |
```suggestion
| ::{ flag=ID }:: [Niva](https://osu.ppy.sh/users/197805) | Contribution exceptionnelle au projet osu! wiki |
```

2022-07-24 20:33 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ::{ flag=LT }:: [huu](https://osu.ppy.sh/users/6044237) | Contribution exceptionnelle à la gestion et à l'organisation de Project Loved |
```suggestion
| ::{ flag=LT }:: [huu](https://osu.ppy.sh/users/6044237) | Contribution exceptionnelle à la gestion et à l'organisation du Project Loved |
```

2022-07-24 20:33 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +| ::{ flag=NL }:: [cavoeboy](https://osu.ppy.sh/users/7361815) | Contribution exceptionnelle aux évènements osu! IRL et aux tournois |
```suggestion
| ::{ flag=NL }:: [cavoeboy](https://osu.ppy.sh/users/7361815) | Contribution exceptionnelle aux évènements IRL d'osu! et aux tournois |
```

2022-07-25 07:42 UTC, Pisapou commented on wiki/People/Community_Contributors/fr.md
> +| ::{ flag=NL }:: [cavoeboy](https://osu.ppy.sh/users/7361815) | Contribution exceptionnelle aux évènements IRL d'osu! et aux tournois |
```suggestion
| ::{ flag=NL }:: [cavoeboy](https://osu.ppy.sh/users/7361815) | Contribution exceptionnelle aux évènements IRL d'osu! et aux tournois |

```

2022-07-25 08:25 UTC, Ganondorf-1 requested changes

2022-07-25 08:25 UTC, Ganondorf-1 commented on wiki/People/Community_Contributors/fr.md
> +*Pour l'article du news, voir : [Community Contributors: 2021](https://osu.ppy.sh/home/news/2022-06-30-community-contributors-2021)*
```suggestion
*Pour l'article de news, voir : [Community Contributors: 2021](https://osu.ppy.sh/home/news/2022-06-30-community-contributors-2021)*
```

2022-07-25 09:05 UTC, Ganondorf-1 approved these changes

2022-07-25 13:29 UTC, TPGPL approved these changes

2022-07-25 13:36 UTC, merged