[FR] Update `Tournaments/Official_support`
ppy/osu-wiki pull request #7696
Opened 2022-07-24 20:42 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-24 20:44 UTC, Pisapou commented on wiki/Tournaments/Official_support/fr.md
> +- Toutes les images de bannières seront traitées en tant que `2x`, ce qui signifie qu'elles seront exportées à une échelle de 50% dans une image `1x`. Concevez vos images de manière à ce qu'elles soi
```suggestion
- Toutes les images de bannières seront traitées comme des `2x`, ce qui signifie qu'elles seront exportées à une échelle de 50% en une image `1x`. Concevez vos images de manière à ce qu'elles soient lisibles à la moitié de leur taille. Les utilisateurs verront l'une ou l'autre image en fonction de la résolution qu'ils ont choisie pour leur client.
```

2022-07-24 20:50 UTC, Ganondorf-1 requested changes

2022-07-24 20:50 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +- La hauteur doit toujours être de **180px**. Les autres valeurs NE conviennent PAS.
```suggestion
- La hauteur doit toujours être de **180px**. Les autres valeurs ne conviennent PAS.
```

2022-07-25 08:20 UTC, Ganondorf-1 approved these changes

2022-07-25 11:43 UTC, TPGPL approved these changes

2022-07-25 11:43 UTC, merged