[ZH] Update `Osu_(file_format)`
ppy/osu-wiki pull request #7703
Opened 2022-07-26 09:11 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-27 06:57 UTC, cdwcgt requested changes

2022-07-27 06:57 UTC, cdwcgt commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +与 osu!catch 类似，osu!mania 不使用物件的 `y` 值。而 `x` 则用于区分物件所处的键位。参见：[长键部分](#长键（仅 osu!mania）)。
```suggestion
与 osu!catch 类似，osu!mania 不使用物件的 `y` 值。而 `x` 则用于区分物件所处的键位。参见：[长键部分](#长键（仅-osu!mania）)。
```

2022-07-27 06:57 UTC, cdwcgt commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +also there is no info about how they convert to other game modes from an osu! beatmap -->
```suggestion
```
May be it can be deleted

2022-07-27 06:57 UTC, cdwcgt commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +`Video` 也可写作 `1`。
```suggestion
`Video` 可用  `1`  代替。
```
感觉这里的1应该是说程序保存时可以为1
而不是作为一种优化语法
并且原文为 `replaced with`

2022-07-27 06:57 UTC, cdwcgt commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +**`.osu`** 是一种简单易懂的，用于存储 osu! 谱面难度信息的文件格式。
```suggestion
**`.osu`** 是一种人类可读的，用于存储 osu! 谱面难度信息的文件格式。
```
human-readable file
[人类可读](https://zh.wikipedia.org/zh-hans/%E4%BA%BA%E7%B1%BB%E5%8F%AF%E8%AF%BB%E4%BB%8B%E8%B4%A8)
应是区别于[Machine-readable data](https://en.wikipedia.org/wiki/Machine-readable_data)（机器可读）的二进制文件
而不意味着简单易懂

2022-07-27 09:51 UTC, YumeMuzi commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +**`.osu`** 是一种简单易懂的，用于存储 osu! 谱面难度信息的文件格式。
这里我认为逐词逐句翻译非常不恰当，在中文语境中，human-readable 本身就有便于人类理解这层含义

2022-07-27 09:52 UTC, YumeMuzi commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +`Video` 也可写作 `1`。
break 你没提啊

2022-07-27 09:53 UTC, YumeMuzi commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +also there is no info about how they convert to other game modes from an osu! beatmap -->
维持原样可以吧？没什么影响

2022-07-27 09:54 UTC, YumeMuzi commented on wiki/Client/File_formats/Osu_(file_format)/zh.md
> +`Video` 也可写作 `1`。
solved

2022-07-27 10:21 UTC, cdwcgt approved these changes

2022-08-02 11:07 UTC, TicClick approved these changes

2022-08-02 11:08 UTC, merged