Changes in `osu! Philippines: CONQuest PH 2022` Newspost
ppy/osu-wiki pull request #7704
Opened 2022-07-26 14:54 UTC by topecnz

- [x] Prizes
- [ ] Wiki https://github.com/ppy/osu-wiki/pull/7702

2022-07-26 15:02 UTC, Soetch approved these changes

2022-07-26 15:47 UTC, TPGPL requested changes

2022-07-26 15:47 UTC, TPGPL commented on news/2022-07-21-osu-philippines-conquest-ph-2022.md
>  ### July 23, 2022 (Day 1)
can probably replace lines 25-39 with something like:

```md
*Note: The prizes are awarded for each day of the tournament.*

| Placing | Prizes |
| :-: | :-- |
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | Unique profile badge, osu!merch, 14 months of osu!supporter |
| ![Silver crown](/wiki/shared/crown-silver.png "2nd place") | osu!merch, 4 months of osu!supporter |
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | osu!merch, 2 months of osu!supporter |
```

2022-07-26 15:47 UTC, TPGPL commented on news/2022-07-21-osu-philippines-conquest-ph-2022.md
> +For more information about the tournament proper, refer [here](/wiki/Tournaments/oPQS/1).
```suggestion
For more information about the tournament, refer to [this wiki article](/wiki/Tournaments/oPQS/1).
```

2022-07-26 15:51 UTC, topecnz commented on news/2022-07-21-osu-philippines-conquest-ph-2022.md
>  ### July 23, 2022 (Day 1)
Looks good tbh.

2022-07-26 15:57 UTC, TPGPL approved these changes

2022-07-27 02:50 UTC, peppy approved these changes

2022-07-27 02:50 UTC, merged