[ZH] Update `Performance points`
ppy/osu-wiki pull request #7711
Opened 2022-07-27 21:36 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-08 09:39 UTC, kj415j45 requested changes

2022-08-08 09:39 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +权重系统是一个简单的公式，用于计算玩家的总表现分。这个公式能够降低玩家的最好表现成绩榜上，比较靠后的成绩对总表现分的影响力。上述公式如下：
```suggestion
权重系统是一个用于计算玩家的总表现分的简单公式。这个公式能够降低玩家成绩榜上比较靠后的成绩对总表现分的影响。公式如下：
```

2022-08-08 09:39 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +在 [osu!](/wiki/Game_mode/osu!) 游戏模式中，含有较多的较远[跳](/wiki/Beatmap/Pattern/Jump)排列的谱面常被称为跳图，通常能在其上获得较多的表现分。同样地，在 [osu!catch](/wiki/Game_mode/osu!catch) 游戏模式中，含有较多的红果跳排列的谱面也能获得较多的表现分。[osu!taiko](/wiki/Game
```suggestion
在 [osu!](/wiki/Game_mode/osu!) 游戏模式中，含有较多的长距离[跳](/wiki/Beatmap/Pattern/Jump)排列的谱面常被称为跳图，通常能在其上获得较多的表现分。同样地，在 [osu!catch](/wiki/Game_mode/osu!catch) 中，含有较多的红果跳排列的谱面也能获得较多的表现分。[osu!taiko](/wiki/Game_mode/osu!taiko) 和 [osu!mania](/wiki/Game_mode/osu!mania) 则没有精准 (Aim) 指标。
```

2022-08-08 09:39 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +短时间内出现大量物件的谱面，它的速度指标会很高。速度越高，谱面难度越高，也就能提供更多的表现分。
```suggestion
短时间内出现大量物件的谱面，它的速度指标会较高。而该值越高，代表谱面难度越高，也就能提供更多的表现分。
```

2022-08-08 09:39 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +因此，诸如 [Double Time](/wiki/Game_modifier/Double_Time) 或 [Half Time](/wiki/Game_modifier/Half_Time) 这些影响谱面物件密度的模组，会显著改变谱面的速度指标，从而影响谱面的表现分。
```suggestion
如 [Double Time](/wiki/Game_modifier/Double_Time) 或 [Half Time](/wiki/Game_modifier/Half_Time) 模组会影响谱面物件密度，从而显著改变谱面的速度指标，进而影响谱面的表现分。
```

2022-08-08 09:39 UTC, kj415j45 commented on wiki/Performance_points/zh.md
> +非常瞎眼的，高准确率的成绩，算法会给予其较高的表现分。因此，一个[全连](/wiki/Full_combo)，但是准确率仅为 80% 的成绩，它的含金量甚至只有准确率 95% 的成绩的 2/3。因为算法十分看重玩家的准确率，所以当玩家开启 Hidden、Hard Rock、Flashlight 这些模组，并打出高准确率的成绩时，能获得可观的表现分。
```suggestion
高准确率的成绩，算法会给予其较高的表现分。而一个[全连](/wiki/Full_combo)，但是准确率仅为 80% 的成绩，它的精确表现分甚至只有准确率 95% 的成绩的 2/3。因为算法十分看重玩家的准确率，所以当玩家开启 Hidden、Hard Rock、Flashlight 这些模组，并打出高准确率的成绩时，能获得可观的表现分。
```
`impressive` 译为 `非常瞎眼的`，有点太接地气，但中文似乎也没有短而好的表述方式。

2022-08-08 10:33 UTC, YumeMuzi commented on wiki/Performance_points/zh.md
> +非常瞎眼的，高准确率的成绩，算法会给予其较高的表现分。因此，一个[全连](/wiki/Full_combo)，但是准确率仅为 80% 的成绩，它的含金量甚至只有准确率 95% 的成绩的 2/3。因为算法十分看重玩家的准确率，所以当玩家开启 Hidden、Hard Rock、Flashlight 这些模组，并打出高准确率的成绩时，能获得可观的表现分。
先按你说的改吧

2022-08-10 17:16 UTC, TPGPL approved these changes

2022-08-10 17:17 UTC, merged