Add `Catch French Intermediate Cup 3` wiki article
ppy/osu-wiki pull request #7722
Opened 2022-07-29 10:48 UTC by fajar13k

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

## Description

- Wiki article for already ended [Catch French Beginner 6](https://osu.ppy.sh/community/forums/topics/1443016)

2022-07-29 15:50 UTC, TPGPL requested changes
apply the changes from `en` to `fr` as well

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/de.md
> +| [Catch French Beginner 6](CFB/6) | 13.11.2021 | 19.12.2021 | ::{ flag=FR }:: [JunkoAndHiro](https://osu.ppy.sh/users/14004732) | ::{ flag=FR }:: [iron-wish](https://osu.ppy.sh/users/12264606) | ::{
```suggestion
| [Catch French Beginner 6](CFB/6) | 13.11.2021 | 19.12.2021 | ::{ flag=FR }:: [JunkoAndHiro](https://osu.ppy.sh/users/14004732) | ::{ flag=FR }:: [iron-wish](https://osu.ppy.sh/users/12264606) | ::{ flag=FR }:: [\_\_\_\_\_\_\_\_\_\_\_\_](https://osu.ppy.sh/users/6973354) |
```

amazing username for markdown

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/en.md
> +| [Catch French Beginner 6](CFB/6) | 2021-11-13 | 2021-12-19 | ::{ flag=FR }:: [JunkoAndHiro](https://osu.ppy.sh/users/14004732) | ::{ flag=FR }:: [iron-wish](https://osu.ppy.sh/users/12264606) | ::{
```suggestion
| [Catch French Beginner 6](CFB/6) | 2021-11-13 | 2021-12-19 | ::{ flag=FR }:: [JunkoAndHiro](https://osu.ppy.sh/users/14004732) | ::{ flag=FR }:: [iron-wish](https://osu.ppy.sh/users/12264606) | ::{ flag=FR }:: [\_\_\_\_\_\_\_\_\_\_\_\_](https://osu.ppy.sh/users/6973354) |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| High | ::{ flag=FR }:: [\_\___________](https://osu.ppy.sh/users/6973354), ::{ flag=FR }:: [Issuko](https://osu.ppy.sh/users/11447466), ::{ flag=FR }:: [Mimir](https://osu.ppy.sh/users/7382734), ::
```suggestion
| High | ::{ flag=FR }:: [\_\_\_\_\_\_\_\_\_\_\_\_](https://osu.ppy.sh/users/6973354), ::{ flag=FR }:: [Issuko](https://osu.ppy.sh/users/11447466), ::{ flag=FR }:: [Mimir](https://osu.ppy.sh/users/7382734), ::{ flag=FR }:: [Utopsia](https://osu.ppy.sh/users/11080305) |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | ::{ flag=FR }:: [\_\___________](https://osu.ppy.sh/users/6973354) |
```suggestion
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | ::{ flag=FR }:: [\_\_\_\_\_\_\_\_\_\_\_\_](https://osu.ppy.sh/users/6973354) |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| **iron-wish** ::{ flag=FR }:: | **7** | 5 | ::{ flag=FR }:: \_\___________ | [#1](https://osu.ppy.sh/community/matches/95389445) |
```suggestion
| **iron-wish** ::{ flag=FR }:: | **7** | 5 | ::{ flag=FR }:: \_\_\_\_\_\_\_\_\_\_\_\_ | [#1](https://osu.ppy.sh/community/matches/95389445) |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| **\_\___________** ::{ flag=FR }:: | **6** | 2 | ::{ flag=FR }:: RexyChann | [#1](https://osu.ppy.sh/community/matches/95152065) |
```suggestion
| **\_\_\_\_\_\_\_\_\_\_\_\_** ::{ flag=FR }:: | **6** | 2 | ::{ flag=FR }:: RexyChann | [#1](https://osu.ppy.sh/community/matches/95152065) |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| Mimir ::{ flag=FR }:: | 2 | **6** | ::{ flag=FR }:: **\_\___________** | [#1](https://osu.ppy.sh/community/matches/94812153) |
```suggestion
| Mimir ::{ flag=FR }:: | 2 | **6** | ::{ flag=FR }:: **\_\_\_\_\_\_\_\_\_\_\_\_** | [#1](https://osu.ppy.sh/community/matches/94812153) |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| Kuzuyo ::{ flag=BE } | -1 | **0** | ::{ flag=FR }:: **\_\___________** | *win by default* |
```suggestion
| Issuko ::{ flag=FR }:: | 2 | **6** | ::{ flag=FR }:: **\_\_\_\_\_\_\_\_\_\_\_\_** | [#1](https://osu.ppy.sh/community/matches/94864020) |
| MRkayle ::{ flag=FR }:: | 2 | **6** | ::{ flag=FR }:: **Utopsia** | [#1](https://osu.ppy.sh/community/matches/94866270) |
| Kuzuyo ::{ flag=BE } | -1 | **0** | ::{ flag=FR }:: **\_\_\_\_\_\_\_\_\_\_\_\_** | *win by default* |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| MissFlufly ::{ flag=FR }:: | 0 | **5** | ::{ flag=FR }:: **\_\___________** | [#1](https://osu.ppy.sh/community/matches/94510041) |
```suggestion
| MissFlufly ::{ flag=FR }:: | 0 | **5** | ::{ flag=FR }:: **\_\_\_\_\_\_\_\_\_\_\_\_** | [#1](https://osu.ppy.sh/community/matches/94510041) |
```

2022-07-29 15:50 UTC, TPGPL commented on wiki/Tournaments/CFB/6/en.md
> +| \_\___________ ::{ flag=FR }:: | -1 | **0** | ::{ flag=FR }:: **leeiplo** | *win by default* |
```suggestion
| \_\_\_\_\_\_\_\_\_\_\_\_ ::{ flag=FR }:: | -1 | **0** | ::{ flag=FR }:: **leeiplo** | *win by default* |
```

2022-07-30 11:08 UTC, fajar13k commented
Requesting help from french friends (if you guys are free whenever) 🙏 @Soetch @Ganondorf-1

2022-07-30 11:18 UTC, Soetch commented
> Requesting help from french friends (if you guys are free whenever) 🙏 @Soetch @Ganondorf-1

Looking into this :)

2022-07-30 11:22 UTC, Soetch submitted a review, later dismissed
All good !

- [x]  (translations only) The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-07-31 15:05 UTC, TPGPL approved these changes

2022-07-31 15:10 UTC, merged