[DE] Add `osu!tourney/Spectator_usage`, `osu!tourney/Troubleshooting` and `osu!tourney`
ppy/osu-wiki pull request #7725
Opened 2022-07-29 14:07 UTC by The-Last-Cookie

This is part of a series that aims to add all articles under `osu!_tournament_client`.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-03 05:14 UTC, Pasi4K5 requested changes

2022-08-03 05:14 UTC, Pasi4K5 commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/de.md
> +- Überprüfe, dass du in osu! eingeloggt bist und dass die Checkboxen `Benutzername speichern` und `Passwort speichern` gesetzt sind.
```suggestion
- Stelle sicher, dass du in osu! eingeloggt bist und dass die Checkboxen `Benutzername speichern` und `Passwort speichern` gesetzt sind.
```

2022-08-03 05:14 UTC, Pasi4K5 commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/de.md
> +Die Auflösung des oberen Teils von osu!tourney kann in der Datei `tournament.cfg` angepasst werden, aber standardmäßig ist sie `1280 x 720`. Überprüfe, dass die Auflösung deines Monitors größer als d
```suggestion
Die Auflösung des oberen Teils von osu!tourney kann in der Datei `tournament.cfg` angepasst werden, aber standardmäßig ist sie `1280 x 720`. Stelle sicher, dass die Auflösung deines Monitors größer als dieser Wert ist. Siehe die [Einrichtungsanleitung](/wiki/osu!tourney/Setup) für Informationen darüber, wie sich die Auflösung ändern lässt.
```

2022-08-03 05:14 UTC, Pasi4K5 commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/de.md
> +Vergesse nicht, den Ausschnitt einzustellen, um das schwarze Bedienfeld aus dem Stream zu entfernen!
```suggestion
Vergiss nicht, den Ausschnitt einzustellen, um das schwarze Bedienfeld aus dem Stream zu entfernen!
```

2022-08-03 14:00 UTC, FamousPig requested changes

2022-08-03 14:00 UTC, FamousPig commented on wiki/osu!_tournament_client/osu!tourney/Spectator_usage/de.md
> +- `Annotation text`: Der Text, um eine Anmerkung anzuzeigen.
```suggestion
- `Annotation text`: Der Text, der als Anmerkung angezeigt wird.
```

2022-08-03 14:00 UTC, FamousPig commented on wiki/osu!_tournament_client/osu!tourney/Spectator_usage/de.md
> +![Wenn ein Raum korrekt erstellt wurde, wird dies anstatt der Anweisungen aufgelistet](img/Osutourneyroomlist.png)
```suggestion
![Wenn ein Raum korrekt erstellt wurde, wird dieser anstelle der Anweisungen aufgelistet](img/Osutourneyroomlist.png)
```

2022-08-03 14:00 UTC, FamousPig commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/de.md
> +Es kann passieren, dass dein Raum inkorrekt benannt wurde oder du das falsche Akronym in der Datei `tournament.cfg` benutzt hast.
```suggestion
Es ist möglich, dass dein Raum inkorrekt benannt wurde oder du das falsche Akronym in der Datei `tournament.cfg` benutzt hast.
```

to me, `kann passieren` signifies something happening outside of the readers control, whereas incorrect naming is very much human error.

2022-08-03 14:00 UTC, FamousPig commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/de.md
> +Sende eine E-Mail an [tournaments@ppy.sh](mailto:tournaments@ppy.sh), sofern du ein Problem hast, das hier nicht in der Liste ist. Stelle sicher, dass die E-Mail beschreibend ist und stelle wenn mögl
```suggestion
Sende eine E-Mail an [tournaments@ppy.sh](mailto:tournaments@ppy.sh), sofern du ein Problem hast, das hier nicht aufgelistet ist. Stelle sicher, dass die E-Mail beschreibend ist und stelle wenn möglich Screenshots zur Verfügung.
```

Unrelated to suggestion:

I keep wondering whether we should make a note here that email communication should be happening in english where possible. I assume the people on the other end of these addresses don't necessarily speak german.

2022-08-04 22:28 UTC, The-Last-Cookie commented
> I keep wondering whether we should make a note here that email communication should be happening in english where possible. I assume the people on the other end of these addresses don't necessarily speak german.

You are definitely not alone with this idea. For now, I think it should be fine because team members and moderators will answer with an approproate e-mail that they don't speak the respective language. Ideally, they could link to other members of the community which in fact speak that language. Some team wiki pages list people and the languages they speak as far as I know.

Nevertheless, we can have a discussion about this with other contributors. If we decide to use this consequently for all articles, I would like to see a rule being added to the ASC.

2022-08-13 14:08 UTC, FamousPig approved these changes
Just double checked and everything looks good to go from my perspective. If we decide to add the note discussed above, it would be better to do it  in one fell swoop across all articles.

2022-08-13 15:10 UTC, TPGPL approved these changes

2022-08-13 15:13 UTC, merged