[DE] Add `Guides/BSS_Issues`
ppy/osu-wiki pull request #7733
Opened 2022-07-31 13:11 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-03 04:49 UTC, Pasi4K5 commented on wiki/Guides/BSS_Issues/de.md
> +4. Gebe deinen Benutzernamen bei `Creator` an. (Wenn dein Name Leerzeichen enthält, dann nutze Leerzeichen.)
```suggestion
4. Gib deinen Benutzernamen bei `Creator` an. (Wenn dein Name Leerzeichen enthält, dann nutze Leerzeichen.)
```

2022-08-03 04:50 UTC, Pasi4K5 commented on wiki/Guides/BSS_Issues/de.md
> +7. Überprüfe, dass der Name des Beatmap-Ordners nicht mit einer Zahlenfolge beginnt.
```suggestion
7. Stelle sicher, dass der Name des Beatmap-Ordners nicht mit einer Zahlenfolge beginnt.
```

2022-08-03 04:54 UTC, Pasi4K5 commented on wiki/Guides/BSS_Issues/de.md
> +7. Gebe irgendetwas anderes als Nutzername bei `Creator` ein, aber nutze nicht deinen Benutzernamen.
```suggestion
7. Gib irgendetwas als Nutzernamen bei `Creator` ein, aber nutze nicht deinen Benutzernamen.
```

2022-08-03 04:56 UTC, Pasi4K5 commented on wiki/Guides/BSS_Issues/de.md
> +11. Nenne die `.zip`-Datei um zu `.osz`.
```suggestion
11. Benenne die `.zip`-Datei zu `.osz` um.
```

2022-08-03 14:24 UTC, FamousPig requested changes

2022-08-03 14:24 UTC, FamousPig commented on wiki/Guides/BSS_Issues/de.md
> +   - Du kannst es leicht erreichen, indem du `Datei` und dann `Songs-Ordner öffnen` im [Beatmap-Editor](/wiki/Client/Beatmap_editor) anklickst.
```suggestion
   - Du kannst ihn leicht erreichen, indem du `Datei` und dann `Songs-Ordner öffnen` im [Beatmap-Editor](/wiki/Client/Beatmap_editor) anklickst.
```

Alternatively `Das kannst du leicht erreichen`, if that is what you were going for.

2022-08-04 22:14 UTC, The-Last-Cookie commented on wiki/Guides/BSS_Issues/de.md
> +4. Gebe deinen Benutzernamen bei `Creator` an. (Wenn dein Name Leerzeichen enthält, dann nutze Leerzeichen.)
eh, mit dem Imperativ habe ich es irgendwie lol

2022-08-05 00:53 UTC, TicClick approved these changes

2022-08-05 00:55 UTC, merged