[RU] Add `Gameplay/Game modifier` articles (title page + `10k`/`Auto`/`Autopilot`/`Cinema`/`Co-op`)
ppy/osu-wiki pull request #7741
Opened 2022-08-01 14:07 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-01 16:56 UTC, Loreos7 submitted a review, later dismissed

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +*Примечание: реплей со включённым автопрохождением не будет сохранён в локальную таблицу рекордов.*
```suggestion
*Примечание: игра с автопрохождением не будет учтена системой рейтинга и не будет сохранена в локальную таблицу рекордов.*
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +Этот мод работает так же, как режим просмотра [реплеев](/wiki/Gameplay/Replay): при его включении будет доступно комментирование карты, а также возможность ускорить или замедлить прохождение. За искл
```suggestion
Этот мод работает так же, как режим просмотра [реплеев](/wiki/Gameplay/Replay): при его включении будет доступно комментирование карты, а также возможность ускорить или замедлить прохождение. За исключением некоторых ситуаций, мод Auto всегда получает ранг SS.
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +В [osu!](/wiki/Game_mode/osu!) авто крутит спиннеры против часовой стрелки, с максимальной скоростью 477 оборотов в минуту.
```suggestion
В [osu!](/wiki/Game_mode/osu!) мод Auto крутит спиннеры против часовой стрелки, с максимальной скоростью 477 оборотов в минуту.
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +В [osu!taiko](/wiki/Game_mode/osu!taiko) авто постарается идеально пройти карту, но не всегда сможет получить SS. Иногда он пропускает один из тиков на драмроллах, которые начинаются не на целом или
```suggestion
В [osu!taiko](/wiki/Game_mode/osu!taiko) мод Auto постарается идеально пройти карту, но не всегда сможет получить SS. Иногда он пропускает один из тиков на драмроллах, которые начинаются не на целом или половинном бите, а также не всегда может пройти дендены, если у карты очень высокий показатель OD.
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +В [osu!catch](/wiki/Game_mode/osu!catch) авто будет ловить *абсолютно все бананы* на спиннерах, двигаясь при этом со скоростью, недоступной игроку.
```suggestion
В [osu!catch](/wiki/Game_mode/osu!catch) мод Auto будет ловить *абсолютно все бананы* на спиннерах, двигаясь при этом со скоростью, недоступной игроку.
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +В [osu!mania](/wiki/Game_mode/osu!mania) авто постарается идельно пройти карту, но может пропустить близко поставленные друг к другу ноты.
```suggestion
В [osu!mania](/wiki/Game_mode/osu!mania) мод Auto постарается идеально пройти карту, но сможет пропустить близко стоящие друг к другу ноты.
```
Соблюдение совершенной формы глаголов сложного предложения.

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +*Эта статья — про мод, включающий автонаведение. Про мод, который всё делает за игрока, см. [Auto (мод)](/wiki/Game_modifier/Auto).*
```suggestion
*Эта статья — про мод, включающий автонаводку. Про мод, который всё делает за игрока, см. [Auto (мод)](/wiki/Game_modifier/Auto).*
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +*Примечание: при активации Autopilot ваш рекорд не засчитается, а реплей не будет сохранён в локальную таблицу рекордов.*
```suggestion
*Примечание: игра с Autopilot не будет учтена системой рейтинга и не будет сохранена в локальную таблицу рекордов.*
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +Активация автопилота также скрывает игровой интерфейс, — [число очков](/wiki/Gameplay/Score), [комбо](/wiki/Beatmapping/Combo), — и промахи. Интерфейс можно вернуть нажатием `Shift` + `Tab`.
```suggestion
Активация автопилота также скрывает игровой интерфейс, — [число очков](/wiki/Gameplay/Score), [комбо](/wiki/Beatmapping/Combo), и промахи. Интерфейс можно вернуть нажатием `Shift` + `Tab`.
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/ru.md
> +![Экран выбора модов](img/mod-selection-screen.jpg "Сравнение экранов выбора модов в osu! (слева вверху), osu!taiko (справа вверху), osu!catch (слева внизу) и osu!mania (справа внизу)")
```suggestion
![Экран выбора модов](img/mod-selection-screen.jpg "Сравнение экранов выбора модов в osu! (слева сверху), osu!taiko (справа сверху), osu!catch (слева снизу) и osu!mania (справа снизу)")
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/ru.md
> +Моды при выборе разделены на три категории: снижающие сложность, повышающие сложность, а  также особые моды. В зависимости от категории, мод может снижать, увеличивать или обнулять [множитель игровых
```suggestion
Моды на экране выбора разделены на три категории: снижающие сложность, повышающие сложность, а  также особые моды. В зависимости от категории, мод может снижать, увеличивать или обнулять [множитель игровых очков](/wiki/Game_modifier/Score_multiplier). Когда одновременно выбраны несколько модов, их множители очков **перемножаются** (напр., `1.06x * 1.12x = 1.1872x`).
```

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/ru.md
> +### Понижение сложности
```suggestion
### Снижение сложности
```
Не знаю, какой вариант будет лучше, нов wordstat, по крайней мере, чаще употребляется "снижение".

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/ru.md
> +### Увеличение сложности
Вот тут уже не знаю, что будет лучше. В принципе сложность можно и повысить.

2022-08-01 16:56 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/ru.md
> +В [турнирных](/wiki/Tournaments) матчах **FreeMod** (***FM***) означает свободу выбора любых модов или их комбинаций. В некоторых турнилах есть отдельные правила, разъясняющие, какие моды в каких ком
```suggestion
В [турнирных](/wiki/Tournaments) матчах **FreeMod** (***FM***) означает свободу выбора любых модов или их комбинаций. В некоторых турнирах есть отдельные правила, разъясняющие, какие моды в каких комбинациях допускается выбирать, и можно ли играть без модов вообще, если указан режим FreeMod.
```

2022-08-01 21:31 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +В [osu!mania](/wiki/Game_mode/osu!mania) авто постарается идельно пройти карту, но может пропустить близко поставленные друг к другу ноты.
пропустить ноты — это не его цель, так что «может»

2022-08-01 21:31 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +*Примечание: реплей со включённым автопрохождением не будет сохранён в локальную таблицу рекордов.*
«система рейтинга» — это как?

2022-08-01 21:31 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +Активация автопилота также скрывает игровой интерфейс, — [число очков](/wiki/Gameplay/Score), [комбо](/wiki/Beatmapping/Combo), — и промахи. Интерфейс можно вернуть нажатием `Shift` + `Tab`.
не, тут обособление с помощью тире должно быть с обеих сторон. скорее всего, я запятые неправильно поставил, так как тут нет придаточного предложения

2022-08-01 21:31 UTC, TicClick commented on wiki/Gameplay/Game_modifier/ru.md
> +![Экран выбора модов](img/mod-selection-screen.jpg "Сравнение экранов выбора модов в osu! (слева вверху), osu!taiko (справа вверху), osu!catch (слева внизу) и osu!mania (справа внизу)")
первый раз встречаю такое написание, звучит сомнительно

2022-08-01 21:31 UTC, TicClick commented on wiki/Gameplay/Game_modifier/ru.md
> +### Увеличение сложности
повышение тогда уж

2022-08-01 21:31 UTC, TicClick commented on wiki/Gameplay/Game_modifier/ru.md
> +### Понижение сложности
с повышением вместе лучше смотрится понижение, а статистика употребления не так важна

2022-08-01 21:31 UTC, TicClick commented on wiki/Gameplay/Game_modifier/ru.md
> +### Увеличение сложности
```suggestion
### Повышение сложности
```

2022-08-01 21:32 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +*Эта статья — про мод, включающий автонаведение. Про мод, который всё делает за игрока, см. [Auto (мод)](/wiki/Game_modifier/Auto).*
мой вариант более естественно звучит и описывает скорее процесс, чем результат (у тебя вышел результат, как по мне)

2022-08-01 21:33 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +*Примечание: реплей со включённым автопрохождением не будет сохранён в локальную таблицу рекордов.*
ладно, приму пока, может, когда-нибудь отредактирую, раз уж другую такую же правку принял

2022-08-01 21:46 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +*Эта статья — про мод, всё делающий за игрока. Про мод, включающий только автонаведение, см. [Autopilot (мод)](/wiki/Game_modifier/Autopilot).*
не, в русской версии другой текст: https://osu.ppy.sh/wiki/ru/Article_styling_criteria/Formatting#%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82-%D1%81%D1%82%D0%B0%D1%82%D1%8C%D0%B8

2022-08-01 22:07 UTC, TPGPL requested changes

2022-08-01 22:07 UTC, TPGPL commented on wiki/Gameplay/Game_modifier/ru.md
> +- Updates to this article should be accompanied with appropriate updates to /Summary -->
```suggestion
```

2022-08-01 22:42 UTC, TicClick commented on wiki/Gameplay/Game_modifier/10K/ru.md
> +stub: true
the original page is a stub so no

2022-08-02 05:57 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +*Примечание: реплей со включённым автопрохождением не будет сохранён в локальную таблицу рекордов.*
Ну ppv2, это же система рейтинга?)

2022-08-02 06:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +Активация автопилота также скрывает игровой интерфейс, — [число очков](/wiki/Gameplay/Score), [комбо](/wiki/Beatmapping/Combo), — и промахи. Интерфейс можно вернуть нажатием `Shift` + `Tab`.
Правило звучит так: перед приложением тире ставится, если перед ним можно вставить слова "а именно", "то есть".
Про обособление с двух сторон тут ни слова. Тем более это конец предложения

2022-08-02 10:49 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Auto/ru.md
> +*Примечание: реплей со включённым автопрохождением не будет сохранён в локальную таблицу рекордов.*
тогда лучше «ранкинга», это чаще употребляемое слово

2022-08-02 10:56 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +Активация автопилота также скрывает игровой интерфейс, — [число очков](/wiki/Gameplay/Score), [комбо](/wiki/Beatmapping/Combo), — и промахи. Интерфейс можно вернуть нажатием `Shift` + `Tab`.
если ты хочешь сказать, что вторая часть предложения — это пояснение к первой, то второе тире ты убрал правильно, но тогда и запятую перед «и» в перечислении тоже нужно было убрать.

я это предложение написал (и прочитал, соответственно) так, что к интерфейсу относятся только число очков и комбо, а промахи — уже нет. таким образом, я использовал [правило 174 отсюда](http://new.gramota.ru/biblio/readingroom/rules/158-tire#174) (третья его часть, *стоящая в середине предложения группа однородных членов*), но зачем-то налепил лишние запятые.

2022-08-02 13:01 UTC, TicClick commented on wiki/Gameplay/Game_modifier/ru.md
> +![Экран выбора модов](img/mod-selection-screen.jpg "Сравнение экранов выбора модов в osu! (слева вверху), osu!taiko (справа вверху), osu!catch (слева внизу) и osu!mania (справа внизу)")
посоветовался кое с кем, пусть будет так

2022-08-02 13:12 UTC, TPGPL approved these changes

2022-08-02 13:13 UTC, merged

2022-08-03 07:21 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
> +Активация автопилота также скрывает игровой интерфейс, — [число очков](/wiki/Gameplay/Score), [комбо](/wiki/Beatmapping/Combo), — и промахи. Интерфейс можно вернуть нажатием `Shift` + `Tab`.
Я посчитал, что к интерфейсу относятся и промахи тоже. Сейчас проверил, оказывается нет. Тогда вариант с двумя обособлениями верный, конечно