[FR] Update `Mapping and Modding Timeline`
ppy/osu-wiki pull request #7751
Opened 2022-08-02 20:26 UTC by Ganondorf-1

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-07 15:37 UTC, Biokax requested changes

2022-08-07 15:37 UTC, Biokax commented on wiki/History_of_osu!/Mapping_and_Modding_Timeline/fr.md
> +- **12/10/2021 :** Les anciens Beatmap Nominators, qui ont démissionné en de bons termes dans la dernière année, peuvent maintenant devenir des membres à part entière dès leur réadhésion sans passer
```suggestion
- **12/10/2021 :** Les anciens Beatmap Nominators, qui ont démissionné en bons termes au cours de l'année, peuvent maintenant devenir des membres à part entière dès leur réadhésion sans passer par la probation.
```

2022-08-10 15:14 UTC, Biokax approved these changes

2022-08-10 15:24 UTC, TicClick approved these changes

2022-08-10 15:26 UTC, merged