[RU] Add pages in `Beatmaps`
ppy/osu-wiki pull request #7766
Opened 2022-08-04 02:54 UTC by coreylombardo

Still getting used to the ASC, не судите строго...

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-04 14:38 UTC, TPGPL submitted a review, later dismissed

2022-08-04 14:38 UTC, TPGPL commented on wiki/Beatmap/Approach_rate/ru.md
> +<!-- TODO: a chart would be nice for comparing speeds/values with mods -->
```suggestion
```

2022-08-04 14:38 UTC, TPGPL commented on wiki/Beatmap/Countdown/ru.md
> +<!--TODO: Insert lots of links-->
```suggestion
```

2022-08-04 14:38 UTC, TPGPL commented on wiki/Beatmap/HP_drain_rate/ru.md
> +Значения HP варьируются от 0 до 10, где 10 — самое строгое наказание, а 0 — самое мягкое.<!-- TODO: quantify what the value actually means -->
```suggestion
Значения HP варьируются от 0 до 10, где 10 — самое строгое наказание, а 0 — самое мягкое.
```

2022-08-04 14:38 UTC, TPGPL commented on wiki/Beatmap/Hype/ru.md
> +На карте необходимо набрать не менее 5 хайпов, или одну целую зелёную полосу, чтобы она была допущена к номинации<!-- TODO: link me -->, которая является одним из этапов в процессе ранкинга.
```suggestion
На карте необходимо набрать не менее 5 хайпов, или одну целую зелёную полосу, чтобы она была допущена к номинации, которая является одним из этапов в процессе ранкинга.
```

2022-08-04 14:38 UTC, TPGPL commented on wiki/Beatmap/Hype/ru.md
> +<!-- TODO: images of the beatmap page and the modding page -->
```suggestion
```

2022-08-04 14:38 UTC, TPGPL commented on wiki/Beatmap/Marathon/ru.md
> +<!-- TODO: Add links and stuff -->
```suggestion
```

2022-08-04 14:38 UTC, TPGPL commented on wiki/Beatmap/Pattern/ru.md
remove L13-L14

2022-08-05 01:33 UTC, TicClick requested changes

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Countdown/ru.md
> +**Обратный отсчёт** может появиться в начале [карты](/wiki/Beatmap). Это полезно для песен, которые начинаются быстро и/или внезапно, но большинству карт он не нужен. Обратный отсчёт можно включить и
```suggestion
**Обратный отсчёт** (англ. *countdown*) можно добавить в начало [карты](/wiki/Beatmap). Он пригодится для песен, которые начинаются быстро и/или внезапно, но большинству карт не понадобится. Обратный отсчёт можно включить или выключить в [настройках песни](/wiki/Client/Beatmap_editor/Song_Setup) на вкладке «Design», но в режиме [osu!taiko](/wiki/Game_mode/osu!taiko) его использовать нельзя.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Countdown/ru.md
> +При включении анимацией обратного отсчёта можно управлять с помощью кнопок `Countdown Speed` (`Half`, `Normal`, `Double`) и кнопки `Countdown Offset`. Кнопки `Countdown Speed` уменьшают вдвое, удваив
```suggestion
При включении анимацией обратного отсчёта можно управлять с помощью кнопок `Countdown Speed` (`Half`, `Normal`, `Double`) и `Countdown Offset`. Кнопки `Countdown Speed` меняют скорость анимации, замедляя или ускоряя её вдвое, а также возвращая ей обычную скорость. Кнопка `Countdown Offset` отвечает за сдвиг отсчёта относительно первой [ноты](/wiki/Hit_object), который измеряется в [ударах в минуту](/wiki/Beatmapping/Beats_per_minute). Например, анимация обратного отсчёта с оффсетом 2 начинается на 2 удара раньше, чем обычно. Если в карте есть интро, то при нажатии на кнопку «Skip» произойдёт переход сразу к обратному отсчёту.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Countdown/ru.md
> +Изменение анимации обратного отсчёта поддерживается [скиннингом](/wiki/Skinning/Interface#countdown).
```suggestion
Оформление анимации обратного отсчёта можно настроить через [скиннинг](/wiki/Skinning/Interface#countdown).
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Drain_time/ru.md
> +**Игровое время** (жарг. дрейн-тайм, от англ. drain time, «время утечки») относится к общей продолжительности [карты](/wiki/Beatmap), которая требует от игрока активности. Она начинается с первого [о
```suggestion
**Игровое время** (англ. *drain time*, жарг. *дрейн*) — это суммарная длительность участков [карты](/wiki/Beatmap), где от игрока требуется активность. Оно начинается с первого [объекта](/wiki/Hit_object), заканчивается на последнем объекте и не учитывает [перерывы](/wiki/Beatmap/Break). Английский термин *drain time* и его буквальный перевод отсылают к [соответствующей игровой механике](/wiki/Beatmapping/Health_drain) в [osu!](/wiki/Game_mode/osu!) и [osu!catch](/wiki/Game_mode/osu!catch), согласно которой уровень здоровья игрока постепенно падает при прохождении карты.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Drain_time/ru.md
> +Карты с очень длительным игровым временем обычно называют *[марафонами](/wiki/Beatmap/Marathon)*, поскольку для их прохождения требуется выносливость, превышающая норму.
```suggestion
Карты с очень длительным игровым временем обычно называют *[марафонами](/wiki/Beatmap/Marathon)*, поскольку для их прохождения требуется исключительная выносливость.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Drain_time/ru.md
> +Страница информации карты на веб-сайте рассчитывает игровое время (обозначено как `длительность потери HP`), основываясь только на времени начала объектов, поэтому если последним объектом карты являе
иногда полезно перефразировать, чтобы фраза лучше читалась
```suggestion
Веб-сайт osu! показывает игровое время карты (обозначено как `длительность потери HP`), вычисленное только по моментам появления объектов. Таким образом, если в конце карты поставлен [слайдер](/wiki/Hit_object/Slider) или [спиннер](/wiki/Hit_object/Spinner), игровое время будет отображаться неправильно.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/HP_drain_rate/ru.md
> +*Для регулирования уровня HP см. [Критерии ранкинга](/wiki/Ranking_Criteria)*
```suggestion
*Подробнее о здоровье как игровой механике: см. [Здоровье](/wiki/Gameplay/Health)*\
*Подробнее о правилах, связанных со скоростью убывания HP: см. [Критерии ранкинга](/wiki/Ranking_Criteria)*
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/HP_drain_rate/ru.md
> +**HP drain rate** (жарг. HP, рус. Скорость утечки здоровья) — один из параметров сложности [карты](/wiki/Beatmap), который определяет, сколько [здоровья](/wiki/Gameplay/Health) пассивно теряется из-з
```suggestion
**HP drain rate** (сокр. *HP*, *ХП*, жарг. *дрейн*) — один из параметров сложности [карты](/wiki/Beatmap), который определяет скорость [пассивного расхода](/wiki/Beatmapping/Health_drain) [здоровья](/wiki/Gameplay/Health). Он также влияет на то, насколько сильно игрок наказывается за пропущенные ноты, и сколько здоровья восстанавливается при точном попадании по [объектам](/wiki/Hit_object).
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/HP_drain_rate/ru.md
> +Значения HP варьируются от 0 до 10, где 10 — самое строгое наказание, а 0 — самое мягкое.
```suggestion
Значения HP варьируются от 0 до 10, где 10 — самая высокая скорость расхода здоровья, а 0 — самая низкая.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/HP_drain_rate/ru.md
> +## Игровые модификаторы
```suggestion
## Моды
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/HP_drain_rate/ru.md
> +Есть четыре игровых модификатора (мода), которые при включении изменяют HP:
```suggestion
На HP влияют четыре мода:
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/HP_drain_rate/ru.md
> +- [Hard Rock](/wiki/Game_modifier/Hard_Rock): Умножает значение HP на 1,4, максимум до 10.
```suggestion
- [Easy](/wiki/Game_modifier/Easy): уменьшает значение HP вдвое.
- [Hard Rock](/wiki/Game_modifier/Hard_Rock): умножает значение HP на 1,4, максимум до 10.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/HP_drain_rate/ru.md
> +- [Half Time](/wiki/Game_modifier/Half_Time): Значение HP не меняется, хотя из-за замедления карты на 25%, здоровье утекает на 25% медленнее.
```suggestion
- [Double Time](/wiki/Game_modifier/Double_Time): значение HP не меняется, но из-за ускорения карты на 50% здоровье расходуется на 50% быстрее.
- [Half Time](/wiki/Game_modifier/Half_Time): значение HP не меняется, но из-за замедления карты на 25% здоровье расходуется на 25% медленнее.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Hype/ru.md
> +Каждая [карта](/wiki/Beatmap) на [рассмотрении](/wiki/Beatmap/Category#work-in-progress-и-pending) имеет свой раздел для [обсуждения](/wiki/Beatmap_discussion), где пользователи могут публиковать спе
eventually we'll have to translate all categories' names but hopefully not today
```suggestion
Каждая [карта](/wiki/Beatmap) в категории [Pending](/wiki/Beatmap/Category#work-in-progress-и-pending) имеет свой раздел для [обсуждения](/wiki/Beatmap_discussion), где пользователи могут публиковать специальные посты на вкладке `Общее (все сложности)` с помощью функции `Хайпануть!`. Это приблизительно отражает количество людей, желающих увидеть эту карту [ранкнутой](/wiki/Beatmap/Category#ranked), и помогает продвинуть её на следующий этап процесса ранкинга.
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Hype/ru.md
> +## Требование к ранкингу
```suggestion
## Требование для ранкинга
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Hype/ru.md
> +На карте необходимо набрать не менее 5 хайпов, или одну целую зелёную полосу, чтобы она была допущена к номинации, которая является одним из этапов в процессе ранкинга.
```suggestion
Чтобы карту в теории могли номинировать и продвинуть дальше по процедуре ранкинга, она должна иметь не менее 5 хайпов (одну целую зелёную полоску).
```

2022-08-05 01:33 UTC, TicClick commented on wiki/Beatmap/Hype/ru.md
> +Пользователи начинают с 10 хайпов, которые расходуются при использовании на картах. Хайпы восстанавливаются по-одному каждую неделю.
мне кажется, так получше будет, что думаешь?
```suggestion
У каждого пользователя есть 10 одноразовых хайпов. За одну неделю восстанавливается один хайп.
```

2022-08-05 12:56 UTC, TicClick approved these changes

2022-08-05 13:01 UTC, merged