Update en.md
ppy/osu-wiki pull request #7774
Opened 2022-08-04 17:53 UTC by WindowsMeosu

## Self-check

- [ 

- [x]  The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-04 18:16 UTC, WindowsMeosu commented
requested files changed

2022-08-20 00:20 UTC, cl8n commented
was this closed on accident? seems like good info for this page

2022-08-30 13:25 UTC, WindowsMeosu commented
> was this closed on accident? seems like good info for this page

I can reopen this if you or anyone wants and the reason I closed was because I lost hope in this since [checks ](https://github.com/ppy/osu-wiki/pull/7774/checks)kept failing and just decided it wasn't worth it.

2022-08-31 08:56 UTC, Walavouchey commented
no need to lose hope over the checks, if nothing else they can be fixed by a maintainer before merging anyway

2022-08-31 23:29 UTC, wowcake requested changes
other than those reviews, looks good enough

2022-08-31 23:29 UTC, wowcake commented on wiki/Gameplay/Score/Ranked_score/id.md
>  **Skor ranked** (*ranked score*) merupakan jumlah seluruh skor terbaik yang ditorehkan pada seluruh tingkat kesulitan beatmap-beatmap Ranked yang dimainkan secara *online*.
```suggestion
**Skor ranked** (*ranked score*) adalah kumpulan dari jumlah seluruh skor terbaik dari seluruh tingkat-tingkat kesulitan beatmap Ranked yang dimainkan secara *online*.
```

2022-08-31 23:29 UTC, wowcake commented on wiki/Gameplay/Score/Ranked_score/id.md
> +Sebelum ppv1 dan ppv2, peringkat ditentukan oleh jumlah skor peringkat yang dimiliki seseorang. Pemain peringkat #1 akan sering berubah karena betapa kecilnya osu! pada saat itu dan kurangnya map. Ra
```suggestion
Sebelum ppv1 dan ppv2, peringkat ditentukan oleh jumlah skor ranked yang dimiliki oleh pemain. Pemain peringkat #1 akan sering berganti karena betapa kecilnya osu! pada dulunya dan juga kekurangan map. Skor ranked telah sepenuhnya digantikan oleh ppv1 pada 24 Juli 2012, yang kemudian digantikan oleh ppv2 pada 27 Januari 2014.
```

2022-08-31 23:29 UTC, wowcake commented on wiki/Gameplay/Score/Ranked_score/id.md
> +## Beatmap yang disetujui
```suggestion
## Approved Beatmap
```

2022-08-31 23:29 UTC, wowcake commented on wiki/Gameplay/Score/Ranked_score/id.md
> +## Beatmap yang disetujui
no need to translate this one

2022-08-31 23:29 UTC, wowcake commented on wiki/Gameplay/Score/Ranked_score/id.md
> +Approved adalah kategori untuk beatmap yang memberikan skor yang sangat besar (misalnya Marathon). Beatmap yang disetujui tidak memberikan ranked score namun memberikan Total Score dan pp. Atau, Love
```suggestion
*Approved Beatmap* adalah kategori untuk beatmap yang memberikan skor yang sangat banyak (misalnya Marathon). Approved Beatmap tidak memberikan skor ranked, namun memberikan Total Score dan pp. Juga, Loved map adalah map yang tidak memberikan pp namun memberikan Ranked dan Total score.
```

2022-09-01 00:15 UTC, WindowsMeosu commented on wiki/Gameplay/Score/Ranked_score/id.md
> +Sebelum ppv1 dan ppv2, peringkat ditentukan oleh jumlah skor peringkat yang dimiliki seseorang. Pemain peringkat #1 akan sering berubah karena betapa kecilnya osu! pada saat itu dan kurangnya map. Ra
commited

2022-09-01 00:16 UTC, WindowsMeosu commented on wiki/Gameplay/Score/Ranked_score/id.md
> +## Beatmap yang disetujui
guess I'll commit anyways~

2022-09-01 00:19 UTC, WindowsMeosu commented on wiki/Gameplay/Score/Ranked_score/id.md
>  **Skor ranked** (*ranked score*) merupakan jumlah seluruh skor terbaik yang ditorehkan pada seluruh tingkat kesulitan beatmap-beatmap Ranked yang dimainkan secara *online*.
commited!

2022-09-01 00:19 UTC, WindowsMeosu commented on wiki/Gameplay/Score/Ranked_score/id.md
> +Approved adalah kategori untuk beatmap yang memberikan skor yang sangat besar (misalnya Marathon). Beatmap yang disetujui tidak memberikan ranked score namun memberikan Total Score dan pp. Atau, Love
commited~

thanks again

2022-09-03 18:39 UTC, WindowsMeosu commented
appears I ain't getting nothing done and my laziness is starting to prevent me from working on this so I'm just gonna close since I'm probably not gonna get anything done atm.

2022-09-03 18:50 UTC, Walavouchey commented
if you want, you can leave the pr open so that we can fix any remaining issues ourselves before merging. the only reason nothing has happened is that maintainers haven't taken a look at this yet.

2022-09-16 23:35 UTC, closed without merging

2022-09-16 23:37 UTC, WindowsMeosu commented
gonna rework this :3