[RU] Update `Beatmap/Overall difficulty`
ppy/osu-wiki pull request #7786
Opened 2022-08-05 13:32 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-07 10:07 UTC, Loreos7 approved these changes

2022-08-07 10:25 UTC, coreylombardo requested changes

2022-08-07 10:25 UTC, coreylombardo commented on wiki/Beatmap/Overall_difficulty/ru.md
> +**Overall difficulty** (***OD***, рус. *ОД*, *общая сложность*) — одна из настроек сложности, которая определяет, насколько трудно получить высокую [точность](/wiki/Gameplay/Accuracy) на [карте](/wik
```suggestion
**Overall difficulty** (***OD***, рус. *ОД*, *общая сложность*) — одна из настроек сложности, которая определяет, насколько трудно получить высокую [точность](/wiki/Gameplay/Accuracy) на [карте](/wiki/Beatmap). Значение OD может меняться от 0 до 10: чем оно выше, тем больше усилий нужно приложить. Поскольку от точности нажатий зависит уровень [здоровья](/wiki/Gameplay/Health) игрока, общая сложность также влияет на сложность прохождения карты в целом.
```

2022-08-07 10:25 UTC, coreylombardo commented on wiki/Beatmap/Overall_difficulty/ru.md
> +Чем выше значение OD, тем меньше размер окна попадания у [игровых объектов](/wiki/Hit_object) — как для нажатия в целом, так и для бо̀льшего числа [очков](/wiki/Gameplay/Score). Максимально допустимо
```suggestion
Чем выше значение OD, тем меньше размер окна попадания у [игровых объектов](/wiki/Hit_object) — как для нажатия в целом, так и для большего числа [очков](/wiki/Gameplay/Score). Максимально допустимое расхождение в osu! и osu!mania указано в таблицах ниже (отсчитывается от момента идеального попадания).
```
Тут знак ударения лишний, так как нет варианта "большЕго".

2022-08-08 22:27 UTC, Joehuu approved these changes

2022-08-08 22:29 UTC, merged