[RU] Add `osu! tournament client` and all `osu!tourney` articles
ppy/osu-wiki pull request #7787
Opened 2022-08-05 17:23 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-23 13:04 UTC, Loreos7 requested changes

2022-08-23 13:04 UTC, Loreos7 commented on wiki/osu!_tournament_client/ru.md
> +- Проверьте, что в поле `Current IPC source` указан путь к инсталляции osu!tourney, которую вы планируете использовать.
```suggestion
- Проверьте, что в поле `Current IPC source` указан путь к установке osu!tourney, которую вы планируете использовать.
```

2022-08-23 13:04 UTC, Loreos7 commented on wiki/osu!_tournament_client/ru.md
> +Значки модов должны иметь расширение `.jpg` или `.png`. Их разрешение может быть любым — клиент постарается уместить значки на панели карты. Для справки, при разрешении экрана 1920x1080 панель карты
```suggestion
Значки модов должны иметь расширение `.jpg` или `.png`. Их разрешение может быть любым — клиент постарается уместить значки на панели карты. Для справки: при разрешении экрана 1920x1080 панель карты имеет размер 563x60.
```

2022-08-23 13:04 UTC, Loreos7 commented on wiki/osu!_tournament_client/ru.md
> +- Соотношение сторон: 16:9, например, 1280x720 или 1920x1080;
```suggestion
- Соотношение сторон: 16:9, например: 1280x720 или 1920x1080;
```

2022-08-24 08:39 UTC, TicClick commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +*Примечание: для использования osu!tourney нужно быть [саппортером](/wiki/osu!supporter).*
да, ты всё верно думаешь, у меня после нескольких прочтений уже глаз замылился

2022-08-24 08:39 UTC, TicClick commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +Рекомендуется использовать **отдельную инсталляцию osu!**, поскольку база данных о картах может повредиться. Иметь несколько копий osu! разрешено — достаточно держать их в разных папках. Для создания
здесь и далее: спорное изменение, потому что, как по мне, «инсталляция» — достаточно распространённый термин. нужно собрать мнения

2022-08-24 08:39 UTC, TicClick commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +Закройте osu! и создайте в её папке пустой файл `tournament.cfg`. Запустите игру — откроется клиент osu!tourney.
не уверен ни в той, ни в той постановке знака препинания, честно говоря, а в справочник лезть лень. может, перепишем?

2022-08-24 08:39 UTC, TicClick commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/ru.md
> +## Клиент не стримит действия игроков
в оригинале `My client is not spectating!`. я не пользовался никогда osu!tourney и не представляю, что там происходит, тут два варианта:
- комната не отслеживается клиентом
- клиент не показывает, что делают игроки (мой вариант)

или ты про то, что по «стримит» непонятно, что именно я хотел сказать?

2022-08-24 08:39 UTC, TicClick commented on wiki/osu!_tournament_client/ru.md
> +- Соотношение сторон: 16:9, например, 1280x720 или 1920x1080;
тут точно не нужно двоеточие

2022-08-24 08:39 UTC, TicClick commented on wiki/osu!_tournament_client/osu!tourney/Multiplayer_usage/ru.md
> +Вместо `Team Name 1` и `Team Name 2` можно указывать любые названия команд, главное — чтобы каждое из них было **заключено в круглые скобки `()`**.
тире в твоём варианте точно не нужно, максимум – запятая на его месте

2022-08-24 08:45 UTC, Loreos7 commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +Закройте osu! и создайте в её папке пустой файл `tournament.cfg`. Запустите игру — откроется клиент osu!tourney.
```suggestion
Закройте osu! и создайте в её папке пустой файл `tournament.cfg`. При запуске игры откроется клиент osu!tourney.
```

2022-08-24 08:46 UTC, Loreos7 commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/ru.md
> +## Клиент не стримит действия игроков
Да, не очень понятно. По мне так тут речь про режим зрителя, который упоминался ранее. 
```suggestion
## Режим зрителя не работает!
```

2022-08-29 00:30 UTC, UristMcKobold approved these changes

2022-08-29 00:30 UTC, UristMcKobold commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +Рекомендуется использовать **отдельную инсталляцию osu!**, поскольку база данных о картах может повредиться. Иметь несколько копий osu! разрешено — достаточно держать их в разных папках. Для создания
Термин «инсталляция» по контексту больше подходит, я согласен с Тиком.

2022-08-29 00:30 UTC, UristMcKobold commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +Рекомендуется использовать **отдельную инсталляцию osu!**, поскольку база данных о картах может повредиться. Иметь несколько копий osu! разрешено — достаточно держать их в разных папках. Для создания
```suggestion
Рекомендуется использовать **отдельную инсталляцию osu!**, поскольку база данных карт может повредиться. Иметь несколько копий osu! разрешено — достаточно держать их в разных папках. Для создания новой инсталляции скопируйте файл `osu!.exe` в пустую папку и запустите его — игра сделает всё остальное. Далее в руководстве речь пойдёт именно об этой копии osu!.
```
Не уверен, что значит «база данных о картах».

2022-08-29 00:30 UTC, UristMcKobold commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +- `BufferTimeoutTime`: как долго клиент будет ожидать буферизации данных от игрока, прежде чем продолжит без него стримить.
```suggestion
- `BufferTimeoutTime`: как долго клиент будет ожидать буферизации данных от игрока, прежде чем продолжит стримить без него.
```

2022-08-29 01:42 UTC, TicClick commented on wiki/osu!_tournament_client/osu!tourney/Setup/ru.md
> +Рекомендуется использовать **отдельную инсталляцию osu!**, поскольку база данных о картах может повредиться. Иметь несколько копий osu! разрешено — достаточно держать их в разных папках. Для создания
`osu!.db` это

2022-08-29 01:46 UTC, TicClick commented
я всё-таки решил оставить вариант с «инсталляцией»

2022-08-29 03:45 UTC, Walavouchey approved these changes

2022-08-29 03:46 UTC, merged