[ZH] Update `Client/Keyboard_shortcuts`
ppy/osu-wiki pull request #7810
Opened 2022-08-09 06:11 UTC by QTPC

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-09 12:30 UTC, Pisapou commented
Apply this for all your pr
- Don’t check the "changes are reviewed by a fluent speaker" until someone on GitHub reviewed this pr.

2022-08-09 12:46 UTC, QTPC commented
> Apply this for all your pr
> 
> * Don’t check the "changes are reviewed by a fluent speaker" until someone on GitHub reviewed this pr.

ok

2022-08-12 04:08 UTC, cdwcgt requested changes

2022-08-12 04:08 UTC, cdwcgt commented on wiki/Client/Keyboard_shortcuts/zh.md
```suggestion
| `Ctrl` + `←/→` | 将所选物件向左或向右移动一列。（仅适用于 osu!mania） |
| `Ctrl` + `↑/↓` | 将所选物件向上或向下移动 1 个节拍细分。（仅适用于 osu!mania） |

```
1 个节拍细分不怎么好，可以考虑下改为更通顺的说法

2022-08-12 04:08 UTC, cdwcgt commented on wiki/Client/Keyboard_shortcuts/zh.md
> +| 在调整滑条速度时 `Ctrl` | 按住以0.1调整。 |
```suggestion
| 在调整 BPM 和偏移量时按住 `Shift` | 以 5 为单位调整。 |
| 在调整BPM时按住 `Ctrl` | 以 0.25 为单位。 |
| 在调整偏移量时按住 `Ctrl` | 以 1 为单位调整。 |
| 在调整滑条速度时按住 `Ctrl` | 以 0.1 为单位调整。 |
```
可能这段的英语也需要更改

2022-08-13 04:34 UTC, cdwcgt commented
不用一直更新分支
也就是通过 `Update Branch` 合并 master 分支，不然会留下很多垃圾提交信息
只需要在准备好的时候让负责wiki的志愿者做就可以了

我晚上有空的时候会再看一遍

@QTPC

2022-08-16 05:43 UTC, cdwcgt requested changes
除了这个就没问题了
I will approve after this fix

2022-08-16 05:43 UTC, cdwcgt commented on wiki/Client/Keyboard_shortcuts/zh.md
>  | 快捷键 | Mod |
```suggestion
| 快捷键 | 模组 |
```
漏了

2022-08-16 05:46 UTC, QTPC commented on wiki/Client/Keyboard_shortcuts/zh.md
>  | 快捷键 | Mod |
修改了

2022-08-16 05:46 UTC, cdwcgt approved these changes

2022-08-16 05:48 UTC, cdwcgt commented
内容是没问题了
但是提交记录可能需要rebase
剩下交给维护者就行了

The content of the article is ok, but it may need to be rebased

2022-08-18 19:09 UTC, TicClick approved these changes
it's alright -- the number of commits is relatively small, besides, we add a merge commit anyway prior to merging a branch into `master`, so it's not a big deal

2022-08-18 19:13 UTC, merged