[UK]BBCode
ppy/osu-wiki pull request #7812
Opened 2022-08-09 16:36 UTC by Aniterin

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-10 20:36 UTC, endeshnik requested changes

2022-08-10 20:36 UTC, endeshnik commented on wiki/BBCode/uk.md
> +При натисканні на кнопку форматування без виділення тексту, буде створена пара тегів навколо курсора в редакторі. При натисканні на кнопку з виділеним текстом теги будуть створені навколо вибраного т
```suggestion
При натисканні на кнопку форматування без виділення тексту буде створена пара тегів навколо курсора в редакторі. При натисканні на кнопку з виділеним текстом теги будуть створені навколо вибраного тексту.
```

2022-08-10 20:36 UTC, endeshnik commented on wiki/BBCode/uk.md
> +Користувачі, які хочуть використовувати разом різні теги можуть накладати їх один поверх іншого, Але, порядок накладання **повинен бути в рамках дозволенного**. При неправильному використанні це може
```suggestion
Користувачі, які хочуть використовувати різні теги разом, можуть накладати їх один поверх іншого, Але, порядок накладання **повинен бути в рамках дозволенного**. При неправильному використанні це може відмінити форматування.  
```

2022-08-10 20:36 UTC, endeshnik commented on wiki/BBCode/uk.md
> +Тег `[color]` використовується для змінення кольору тексту. Тег використовує [HEX code](https://en.wikipedia.org/wiki/Web_colors#Hex_triplet) формат для визначення кольору, також можна використовуват
```suggestion
Тег `[color]` використовується для змінення кольору тексту. Тег використовує [HEX code](https://en.wikipedia.org/wiki/Web_colors#Hex_triplet) формат для визначення кольору, також можна використовувати НТМL кольори, такі як "red" або "green". Щоб вказати НТМL колір, замініть `HEXCODE` на ім'я НТМL кольору
```

2022-08-10 20:36 UTC, endeshnik commented on wiki/BBCode/uk.md
> +Тег `[quote]` використовується для оформлення довгих цитат (a.k.a. "block quotes") за допомогою відступів, кольору, жирності, та відокремлення (за допомогою рожевої вертикальної лінії) тексту. Вміст
```suggestion
Тег `[quote]` використовується для оформлення довгих цитат (a.k.a. "block quotes") за допомогою відступів, кольору, жирності та відокремлення (за допомогою рожевої вертикальної лінії) тексту. Вміст цитати розміщений між відкриваючими і закриваючими тегами, а автор цитати записується `NAME` (проте вказувати аргумент не обов'язково).
```

2022-08-10 20:36 UTC, endeshnik commented on wiki/BBCode/uk.md
> +*Зауважте: ID користувача, це цифри після `/users/` в посиланні на профіль.*
```suggestion
*Зауважте: ID користувача - це цифри після `/users/` в посиланні на профіль.*
```

2022-08-10 20:36 UTC, endeshnik commented on wiki/BBCode/uk.md
> +Тег *Heading (v2)* це застарілий тег, який який форматував текст в химерний, рожевий, підкреслений заголовок. Тег працював тільки в форумах карт і з'являвся тільки після публікації. В тега не було вл
```suggestion
Тег *Heading (v2)* є застарілим тегом, який який форматував текст в химерний, рожевий, підкреслений заголовок. Тег працював тільки в форумах карт і з'являвся тільки після публікації. В тега не було власної кнопки і він був записаний за допомогою лапок
```

2022-08-10 23:55 UTC, TPGPL commented on wiki/BBCode/uk.md
> +Кнопка на панелі форматування ![Bold button](img/bold.png "Bold")
seems like you forgot to translate tooltips and alt-texts for those icons (same below)

2022-08-13 15:42 UTC, TPGPL commented on wiki/BBCode/uk.md
> +Кнопка на панелі форматування ![Жирний шрифт](img/bold.png "Bold")
tooltips are still not translated

for ref:

`![alt-text](link "tooltip")`

2022-08-18 19:00 UTC, TicClick requested changes
this has to be all, highlight me on Discord once you have fixed it

2022-08-18 19:00 UTC, TicClick commented on wiki/BBCode/uk.md
> +![Quote reply button](img/quotereply.png)
aaand there's another tooltip without translation

2022-08-29 16:40 UTC, TicClick approved these changes

2022-08-29 16:42 UTC, merged