[UK] Add `Beatmap`
ppy/osu-wiki pull request #7816
Opened 2022-08-09 16:51 UTC by Aniterin

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-10 21:11 UTC, endeshnik requested changes
change мапи to карти

2022-08-10 21:11 UTC, endeshnik commented on wiki/Beatmap/uk.md
> +- Глобальна таблиця, який поширюється на всіх гравців які пройшли мапу;
```suggestion
- Глобальна таблиця, яка поширюється на гравців які пройшли мапу;
```

2022-08-10 21:11 UTC, endeshnik commented on wiki/Beatmap/uk.md
> +- Глобальна таблиця, який поширюється на всіх гравців які пройшли мапу із [ігровими модифікаторами](/wiki/Game_modifier);
```suggestion
- Глобальна таблиця, яка поширюється на гравців які пройшли мапу з [ігровими модифікаторами](/wiki/Game_modifier);
```

2022-08-10 21:19 UTC, Aniterin commented
**Don't merge this yet, i will change some mistakes pointed by endeshnik**

2022-08-18 19:10 UTC, TicClick commented
please fix broken links -- see https://github.com/ppy/osu-wiki/runs/7782457163?check_suite_focus=true

2022-08-24 07:41 UTC, cl8n approved these changes

2022-08-24 07:43 UTC, merged