Mozes
ppy/osu-wiki pull request #7818
Opened 2022-08-10 08:18 UTC by RadekMojzis

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-24 22:30 UTC, TPGPL requested changes

2022-08-24 22:30 UTC, TPGPL commented on wiki/Gameplay/Choke/cs.md
> +V [osu!](/wiki/Game_mode/osu!) a [osu!catch](/wiki/Game_mode/osu!catch) může být rozdíl mezi chokem (nebo reverse chokem) a plným kombem poměrně drastický. Je to z toho důvodu, že objekty blízko konc
```suggestion
Termín používaný, když se hráči skoro podaří udržet plné kombo když hraje [beatmapu](/wiki/Beatmap), ale kombo přeruší blízko konce mapy. **Obrácený choke** potom referuje na situaci, kdy hráč přeruší kombo blízko začátku mapy a následně si jej udrží až do konce. V [osu!](/wiki/Game_mode/osu!) a [osu!catch](/wiki/Game_mode/osu!catch) může být rozdíl mezi chokem (nebo reverse chokem) a plným kombem poměrně drastický. Je to z toho důvodu, že objekty blízko konce mají vysokou váhu kvůli akumulovanému kombu.
```

2022-08-24 22:30 UTC, TPGPL commented on wiki/Gameplay/Choke/cs.md
> +Klíčovými vlastnostmi choku jsou náhoda a nekonzistentní výkon. Přerušení komba na specifickém obtížném vzoru (paterně) může být zaviněno nedostatečnými dovednostmi hráče, nebo způsobem jakým byla be
missing a link

for ref:

`The key characteristic of a choke is its randomness and inconsistent performance. This excludes regular or pattern-specific misses or [slider breaks](/wiki/Gameplay/Judgement/Slider_break), which are usually tied to a player's skill level, or how the beatmap is constructed. Chokes are typically caused by excessive mental stress and nervousness during gameplay, as well as overall fatigue.`

2022-09-27 08:30 UTC, TicClick requested changes

2022-09-27 08:30 UTC, TicClick commented on wiki/Gameplay/Choke/cs.md
> +Termín používaný, když se hráči skoro podaří udržet plné kombo když hraje [beatmapu](/wiki/Beatmap), ale [kombo přeruší](/wiki/Gameplay/Judgement/Combobreak) blízko konce mapy. **Obrácený choke** pot
the third sentence is missing a mention of total score:

> ```md
> In [osu!](/wiki/Game_mode/osu!) and [osu!catch](/wiki/Game_mode/osu!catch), the difference in [total score](/wiki/Gameplay/Score) between regular and reverse chokes may be drastic
> ```

2022-09-29 19:57 UTC, TPGPL commented
converting to draft since there has been no activity for a long time

2022-11-25 19:55 UTC, closed without merging