[FR] Update `Client\interface\Multiplayer`
ppy/osu-wiki pull request #7830
Opened 2022-08-11 17:39 UTC by Biokax

This is a fully retranslated version of Multiplayer so its better to review this as a new file instead of an update.

This is also the final PR before getting 0 on [clayton.cc](https://clayton.cc/osu-wiki-status/fr) for french language (pog moment)

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-12 20:01 UTC, Ganondorf-1 requested changes

2022-08-14 11:49 UTC, Ganondorf-1 requested changes

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +1. Cliquez sur le button `Play` ou appuyez sur `P`.
```suggestion
1. Cliquez sur le bouton `Play` ou appuyez sur `P`.
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Tous`/`osu!`/`osu!taiko`/`osu!catch`/ `osu!mania` | Montre uniquement les salle avec le [mode de jeu](/wiki/Game_mode) sélectionné ou pour tous les modes de jeu. |
```suggestion
| `Tous`/`osu!`/`osu!taiko`/`osu!catch`/ `osu!mania` | Montre uniquement les salles avec le [mode de jeu](/wiki/Game_mode) sélectionné ou pour tous les modes de jeu. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Salles dont je poss. les maps uniq.` | Montre uniquement les salles si le joueur possède la [beatmap](/wiki/Beatmap) actuellement jouée. |
```suggestion
| `Salles dont je poss. les maps uniq.` | Montre uniquement les salles dont le joueur possède la [beatmap](/wiki/Beatmap) actuellement jouée. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +*Remarque : un tag actif [osu!supporter](/wiki/osu!supporter) est requis pour entrer dans le lobby lorsque vous utilisez le canal de mise à jour `Cutting Edge (Expérimental)`.*
```suggestion
*Remarque : un tag actif [osu!supporter](/wiki/osu!supporter) est requis pour entrer dans le lobby lorsque le canal de mise à jour `Cutting Edge (Expérimental)` est utilisé.*
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Recherche` | Recherche une beatmap spécifique en train d'être jouée ou le nom de l'hôte en utilisant la barre de recherche. Lorsque vous utilisez la recherche, tous les filtres seront temporaireme
```suggestion
| `Recherche` | Recherche une beatmap spécifique en train d'être jouée ou le nom de l'hôte en utilisant la barre de recherche. Lorsque la recherche est utilisée, tous les filtres seront temporairement ignorés excepté `Afficher salles occupées`. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Afficher salles verrouillées` | Montre les salles qui requièrent un mot de passe pour rejoindre. |
```suggestion
| `Afficher salles verrouillées` | Montre les salles qui requièrent un mot de passe pour les rejoindre. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Afficher salles occupées` | Montre les salles qui sont actuellement en train de jouer une beatmap. Il est encore possible de les rejoindre s'il reste des places disponibles. Il y a un indicateur a
```suggestion
| `Afficher salles occupées` | Montre les salles qui sont actuellement en train de jouer une beatmap. Il est encore possible de les rejoindre s'il reste des places disponibles. Il y a un indicateur avec un titre grisé avec `(en cours)` ajouté, jusqu'à ce que la salle termine la partie. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +Les trois boutons au-dessus la [console de tchat](/wiki/Client/Interface/Chat_console) fournissent les principales options de navigation de cet écran :
```suggestion
Les trois boutons au-dessus de la [console de tchat](/wiki/Client/Interface/Chat_console) fournissent les principales options de navigation de cet écran : 
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Max Players` | Le nombre total de joueurs (incluant l'hôte) autorisés à rejoindre la salle. Une plage de 2 à 16 joueurs peut être sélectionné, avec une valeur par défaut de 8. Ceci peut être ajust
```suggestion
| `Max Players` | Le nombre total de joueurs (incluant l'hôte) autorisés à rejoindre la salle. Une plage de 2 à 16 joueurs peut être sélectionnée, avec une valeur par défaut de 8. Ceci peut être ajusté plus tard en verrouillant/déverrouillant des emplacements de joueurs. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +La partie en haut à gauche indique si le joueur est l'hôte de la partie ou un joueur normal. Au milieu, il y a une boite de joueur contenant des informations sur les [points de performance](/wiki/Per
```suggestion
La partie en haut à gauche indique si le joueur est l'hôte de la partie ou un joueur normal. Au milieu, il y a une boîte de joueur contenant des informations sur les [points de performance](/wiki/Performance_points/Total_performance_points), la [précision générale](/wiki/Gameplay/Accuracy), le [niveau](/wiki/Gameplay/Score/Total_score#level), le [rang](/wiki/Ranking#performance-points-ranking) ainsi que le [mode de jeu](/wiki/Game_mode). Sur la droite, il y a un bouton pour mettre en pause la musique actuellement sélectionnée.
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +### La liste des joueurs actuels
```suggestion
### La liste des joueurs présents
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +![](img/multi-host-map-change-fr.jpg "La carte de beatmap quand l'hôte est en train de changer les musiques")
```suggestion
![](img/multi-host-map-change-fr.jpg "La carte de beatmap quand l'hôte est en train de changer la beatmap")
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +Si le joueur ne possède pas la beatmap, un des status suivant sera affiché :
```suggestion
Si le joueur ne possède pas la beatmap, un des statuts suivants sera affiché :
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Team VS` | S'affronter les un contre les autres en équipe (Rouge et Bleu) pour remporter la partie. |
```suggestion
| `Team VS` | S'affronter les uns contre les autres en équipe (Rouge et Bleu) pour remporter la partie. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Start Game!` | Commence la partie. Ce bouton apparaît uniquement pour l'hôte du match lorsque tous les joueurs sont prêts. |
```suggestion
| `Start Game!` | Commence la partie. Ce bouton apparaît uniquement pour l'hôte de la salle lorsque tous les joueurs sont prêts. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Force Start Game! ({prêts}/{total})` | Démarre la partie même si tous les joueurs ne sont pas prêts. Ce bouton apparaît uniquement pour l'hôte de la partie lorsque quelques joueurs sont prêts. Le
```suggestion
| `Force Start Game! ({prêts}/{total})` | Démarre la partie même si tous les joueurs ne sont pas prêts. Ce bouton apparaît uniquement pour l'hôte de la salle lorsque quelques joueurs sont prêts. Le nombre de joueurs prêts comparé à celui du nombre total de joueurs est montré entre parenthèses. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +Pendant que la partie est en train de démarrer, déplacer le curseur vers le bas de l'écran ouvrira le menu de paramètres visuels. Voir la page du [menu de paramètres visuels](/wiki/Client/Interface/V
```suggestion
Lorsque que la partie est en train de démarrer, déplacer le curseur vers le bas de l'écran ouvrira le menu de paramètres visuels. Voir la page du [menu de paramètres visuels](/wiki/Client/Interface/Visual_settings) pour plus d'informations. 
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +En partie Team VS, avoir échoué à la fin de la beatmap fera en sorte que le score ne contribuera pas au score de l'équipe.
```suggestion
En partie Team VS, avoir échoué à la fin de la beatmap ne permettra pas au score réalisé de contribuer au score total de l'équipe.
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| ![](img/Playerbox/Multi_PB_SKIP.jpg "Skipped") | Skipped | La requête d'un joueur de passer l'introduction d'une beatmap s'il y en a une. L'introduction sera passée une fois que tous les joueurs on
```suggestion
| ![](img/Playerbox/Multi_PB_SKIP.jpg "Skipped") | Skipped | La requête d'un joueur pour passer l'introduction d'une beatmap s'il y en a une. L'introduction sera passée une fois que tous les joueurs ont souhaité la passer. |
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +Une flèche verte indiquera quel joueur est actuellement en train de jouer, et leur pseudo sera indiqué en bas à droite. Des flèches d'avertissement indiquent quand c'est au tour du joueur et les proc
```suggestion
Une flèche verte indiquera quel joueur est actuellement en train de jouer, et son pseudo sera indiqué en bas à droite. Des flèches d'avertissement indiquent quand c'est au tour du joueur et les prochains objets seront colorés. Le joueur peut définir une couleur de combo qui lui sera dédiée dans la partie [Couleur](#tag-colour) de la section de configuration de la salle dans le lobby de la partie.
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +Si un joueur quitte pendant le match, le jeu jouera automatiquement sa partie pour lui.
```suggestion
Si un joueur quitte pendant la beatmap, le jeu jouera automatiquement sa partie pour lui.
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +![](img/legacy-multi-lobby.jpg "Capture d'écran du lobby principal lorsqu'osu!mania était sortie pour la première fois (8 octobre 2012), mais n'était pas encore jouable en multijoueur")
```suggestion
![](img/legacy-multi-lobby.jpg "Capture d'écran du lobby principal lorsqu'osu!mania était sorti pour la première fois (8 octobre 2012), mais n'était pas encore jouable en multijoueur")
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +- La version initiale du multijoueur a été implémentée le 3 juin 2008 dans la version publique d'osu! b335
```suggestion
- La version initiale du multijoueur a été implémentée le 3 juin 2008 dans la version publique d'osu! b335.
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +![](img/multi-teamvs-results.jpg "Écran des résultats Team VS")
```suggestion
![](img/multi-teamvs-results.jpg "Écran de résultats Team VS")
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +L'équipe gagnante est annoncée en haut de l'écran des résultats.
```suggestion
L'équipe gagnante est annoncée en haut de l'écran de résultats.
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +![](img/multi-coop-results.jpg "Écran des résultats Tag co-op")
```suggestion
![](img/multi-coop-results.jpg "Écran de résultats Tag co-op")
```

2022-08-14 11:49 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +![](img/multi-tagteam-results.jpg "Écran des résultats Tag-team VS")
```suggestion
![](img/multi-tagteam-results.jpg "Écran de résultats Tag-team VS")
```

2022-08-14 14:16 UTC, Ganondorf-1 requested changes

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +L'[osu!academy](/wiki/Community/Video_series/osu!academy) couvre cette partie du client dans un format vidéo dans l'[épisode 6](https://www.youtube.com/watch?v=QPTLyG7O8ak), ainsi que les [panneaux d
```suggestion
L'[osu!academy](/wiki/Community/Video_series/osu!academy) couvre cette partie du client dans un format vidéo dans l'[épisode 6](https://www.youtube.com/watch?v=QPTLyG7O8ak), ainsi que les [panneaux d'utilisateurs en ligne](/wiki/Client/Interface/Chat_console#la-console-de-tchat-étendue).
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Salle au hasard` | Rejoindre une salle disponible de manière *aléatoire* basée sur le [rang dans le classement des points de performance](/wiki/Ranking#performance-points-ranking) actuel du joueur
```suggestion
| `Salle au hasard` | Rejoindre une salle disponible de manière *aléatoire* basée sur le [rang dans le classement des points de performance](/wiki/Ranking#classement-des-points-de-performance) actuel du joueur. |
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +La partie en haut à gauche indique si le joueur est l'hôte de la partie ou un joueur normal. Au milieu, il y a une boîte de joueur contenant des informations sur les [points de performance](/wiki/Per
```suggestion
La partie en haut à gauche indique si le joueur est l'hôte de la partie ou un joueur normal. Au milieu, il y a une boîte de joueur contenant des informations sur les [points de performance](/wiki/Performance_points/Total_performance_points), la [précision générale](/wiki/Gameplay/Accuracy), le [niveau](/wiki/Gameplay/Score/Total_score#niveau), le [rang](/wiki/Ranking#classement-des-points-de-performance) ainsi que le [mode de jeu](/wiki/Game_mode). Sur la droite, il y a un bouton pour mettre en pause la musique actuellement sélectionnée.
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| `Ranked` / `Approved` / `Pending` / `Graveyard` | La [catégorie de beatmap](/wiki/Beatmap/Category). Cliquer sur la carte de beatmap ouvrira la page de la beatmap depuis le site web où elle pourra
```suggestion
| `Ranked` / `Approved` / `Pending` / `Graveyard` | La [catégorie de beatmap](/wiki/Beatmap/Category). Cliquer sur la carte de beatmap ouvrira la page de la beatmap depuis le site web où elle pourra être [téléchargée](/wiki/Beatmap#télécharger-les-beatmaps). |
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +Malgré le fait qu'il n'y ait pas d'[écran de résultats étendu](/wiki/Client/Interface#extended-results-screen) sous l'écran de résultats comme en jouant en solo, les scores réalisés en partie multijo
```suggestion
Malgré le fait qu'il n'y ait pas d'[écran de résultats étendu](/wiki/Client/Interface#écran-de-résultats-étendu) sous l'écran de résultats comme en jouant en solo, les scores réalisés en partie multijoueur (avec l'exception des parties en `Tag co-op` et `Tag-team VS`) vont quand même apparaître sur les classements en ligne s'ils sont suffisamment bons. Le résultat n'apparaîtra pas sur le classement local.
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +| ![](img/Playerbox/Multi_PB_F.jpg "Échoué") | Échoué | Le joueur a atteint 0 PV et a [échoué](#health). |
```suggestion
| ![](img/Playerbox/Multi_PB_F.jpg "Échoué") | Échoué | Le joueur a atteint 0 PV et a [échoué](#santé). |
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +Une flèche verte indiquera quel joueur est actuellement en train de jouer, et son pseudo sera indiqué en bas à droite. Des flèches d'avertissement indiquent quand c'est au tour du joueur et les proch
```suggestion
Une flèche verte indiquera quel joueur est actuellement en train de jouer, et son pseudo sera indiqué en bas à droite. Des flèches d'avertissement indiquent quand c'est au tour du joueur et les prochains objets seront colorés. Le joueur peut définir une couleur de combo qui lui sera dédiée dans la partie [Couleur](#couleur-de-tag) de la section de configuration de la salle dans le lobby de la partie.
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +L'écran de résultats de `Tag-team VS` est identique à [celui de `Team VS`](#team-vs-results-screen).
```suggestion
L'écran de résultats de `Tag-team VS` est identique à [celui de `Team VS`](#écran-de-résultats-team-vs).
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +##### Résultats {#team-vs-results-screen}
```suggestion
##### Résultats {#écran-de-résultats-team-vs}
```

2022-08-14 14:16 UTC, Ganondorf-1 commented on wiki/Client/Interface/Multiplayer/fr.md
> +### Historique de le salle
```suggestion
### Historique de la salle
```

2022-08-14 15:36 UTC, Ganondorf-1 approved these changes

2022-08-14 15:42 UTC, TicClick approved these changes

2022-08-14 15:43 UTC, merged