Add Aetherian's Summer Singles 2 tournament article
ppy/osu-wiki pull request #7832
Opened 2022-08-11 23:12 UTC by AetherianFI

Wrote the tournament article for Aetherian's Summer Singles 2 that ended a few weeks ago. My first time contributing anything here so please say if I need to fix something :3

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-08-12 20:28 UTC, Walavouchey requested changes

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/en.md
> +- [Aetherian's Summer Singles 2](/wiki/Tournaments/AESS/2/en.md)
put the first iteration above this one, but don't link it

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/en.md
> +<!-- List the tournaments available in the directory chronologically -->
```suggestion
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +The **Aetherian's Summer Singles 2** (***AESS2***) was a 1v1 double-elimination tournament hosted by ![](https://s.ppy.sh/images/flags/fi.gif) [Aetherian](https://osu.ppy.sh/users/6263040). It was th
this is how you do flags

```suggestion
The **Aetherian's Summer Singles 2** (***AESS2***) was a 1v1 double-elimination tournament hosted by ::{ flag=FI }:: [Aetherian](https://osu.ppy.sh/users/6263040). It was the second instalment of the Aetherian's Summer Singles.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | 6 months of osu!support, profile banner |
```suggestion
| ![Gold crown](/wiki/shared/crown-gold.png "1st place") | 12 months of osu!supporter, profile banner, profile badge |
| ![Silver crown](/wiki/shared/crown-silver.png "2nd place") | 9 months of osu!supporter, profile banner |
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | 6 months of osu!supporter, profile banner |
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +| *7th-8th place* | 1 month of osu!supporter |
```suggestion
| *5th–6th place* | 2 months of osu!supporter |
| *7th–8th place* | 1 month of osu!supporter |
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +| Custom Mapper | ![](https://s.ppy.sh/images/flags/au.gif) [VP757](https://osu.ppy.sh/users/9451871), ![](https://s.ppy.sh/images/flags/us.gif) [Kurashina Asuka](https://osu.ppy.sh/users/7476493) |
```suggestion
| Mappool tester | ![](https://s.ppy.sh/images/flags/id.gif) [Crezz](https://osu.ppy.sh/users/7108275), ![](https://s.ppy.sh/images/flags/kr.gif) [Nopekjk](https://osu.ppy.sh/users/4585186), ![](https://s.ppy.sh/images/flags/no.gif) [Naigo](https://osu.ppy.sh/users/10640486), ![](https://s.ppy.sh/images/flags/ua.gif) [dench](https://osu.ppy.sh/users/10073635), ![](https://s.ppy.sh/images/flags/pl.gif) [Mastasz](https://osu.ppy.sh/users/1876565), ![](https://s.ppy.sh/images/flags/fi.gif) [Eliaasi](https://osu.ppy.sh/users/9690571), ![](https://s.ppy.sh/images/flags/my.gif) [Zeph2003](https://osu.ppy.sh/users/10343292), ![](https://s.ppy.sh/images/flags/se.gif) [scylla](https://osu.ppy.sh/users/9405745), ![](https://s.ppy.sh/images/flags/fi.gif) [Haadez](https://osu.ppy.sh/users/8925266), ![](https://s.ppy.sh/images/flags/de.gif) [criller](https://osu.ppy.sh/users/8116659), ![](https://s.ppy.sh/images/flags/ru.gif) [gamer228666](https://osu.ppy.sh/users/5981005), ![](https://s.ppy.sh/images/flags/pl.gif) [HEDAYO](https://osu.ppy.sh/users/9323821) |
| Custom mapper | ![](https://s.ppy.sh/images/flags/au.gif) [VP757](https://osu.ppy.sh/users/9451871), ![](https://s.ppy.sh/images/flags/us.gif) [Kurashina Asuka](https://osu.ppy.sh/users/7476493) |
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +| Graphics | ![](https://s.ppy.sh/images/flags/ca.gif) [Zyoulou](https://osu.ppy.sh/users/8668722), ![](https://s.ppy.sh/images/flags/fi.gif) [shdewz](https://osu.ppy.sh/users/10000899) |
```suggestion
| Graphic designer | ![](https://s.ppy.sh/images/flags/ca.gif) [Zyoulou](https://osu.ppy.sh/users/8668722), ![](https://s.ppy.sh/images/flags/fi.gif) [shdewz](https://osu.ppy.sh/users/10000899) |
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +| 25-32 | ![](https://s.ppy.sh/images/flags/uk.gif) [Mahmood](https://osu.ppy.sh/users/7627844), ![](https://s.ppy.sh/images/flags/se.gif) [TOnyrino](https://osu.ppy.sh/users/7338010), ![](https://s.
```suggestion
| 1–8 | ![](https://s.ppy.sh/images/flags/hk.gif) [mcy4](https://osu.ppy.sh/users/2165650), ![](https://s.ppy.sh/images/flags/kr.gif) [[Karcher]](https://osu.ppy.sh/users/11443437), ![](https://s.ppy.sh/images/flags/ro.gif) [SatonoDiamond](https://osu.ppy.sh/users/12366071), ![](https://s.ppy.sh/images/flags/us.gif) [Swiq_](https://osu.ppy.sh/users/11269055), ![](https://s.ppy.sh/images/flags/pl.gif) [maliszewski](https://osu.ppy.sh/users/12408961), ![](https://s.ppy.sh/images/flags/us.gif) [WillCookie](https://osu.ppy.sh/users/6404488), ![](https://s.ppy.sh/images/flags/us.gif) [Jacob3](https://osu.ppy.sh/users/13628898), ![](https://s.ppy.sh/images/flags/us.gif) [Jakson](https://osu.ppy.sh/users/8788058) |
| 9–16 | ![](https://s.ppy.sh/images/flags/us.gif) [Venpris](https://osu.ppy.sh/users/8861593), ![](https://s.ppy.sh/images/flags/us.gif) [-Koda](https://osu.ppy.sh/users/12260184), ![](https://s.ppy.sh/images/flags/de.gif) [rundyyy](https://osu.ppy.sh/users/10917620), ![](https://s.ppy.sh/images/flags/ca.gif) [noncycle](https://osu.ppy.sh/users/12701607), ![](https://s.ppy.sh/images/flags/je.gif) [rudj](https://osu.ppy.sh/users/11592896), ![](https://s.ppy.sh/images/flags/us.gif) [EzChock](https://osu.ppy.sh/users/9276293), ![](https://s.ppy.sh/images/flags/us.gif) [BoshyMan741](https://osu.ppy.sh/users/4830687), ![](https://s.ppy.sh/images/flags/us.gif) [DarkScrap](https://osu.ppy.sh/users/13241562) |
| 17–24 | ![](https://s.ppy.sh/images/flags/cl.gif) [Danidesu](https://osu.ppy.sh/users/2748187), ![](https://s.ppy.sh/images/flags/il.gif) [Galog](https://osu.ppy.sh/users/7799629), ![](https://s.ppy.sh/images/flags/pl.gif) [gnahus](https://osu.ppy.sh/users/12779141), ![](https://s.ppy.sh/images/flags/nz.gif) [Saiyku](https://osu.ppy.sh/users/13767572), ![](https://s.ppy.sh/images/flags/de.gif) [aahoff](https://osu.ppy.sh/users/11371245), ![](https://s.ppy.sh/images/flags/sg.gif) [200201envenho](https://osu.ppy.sh/users/8152145), ![](https://s.ppy.sh/images/flags/id.gif) [-Reuto-](https://osu.ppy.sh/users/10717635), ![](https://s.ppy.sh/images/flags/sg.gif) [GSBlank](https://osu.ppy.sh/users/2312106) |
| 25–32 | ![](https://s.ppy.sh/images/flags/uk.gif) [Mahmood](https://osu.ppy.sh/users/7627844), ![](https://s.ppy.sh/images/flags/se.gif) [TOnyrino](https://osu.ppy.sh/users/7338010), ![](https://s.ppy.sh/images/flags/de.gif) [Tim Kackner](https://osu.ppy.sh/users/14385814), ![](https://s.ppy.sh/images/flags/ro.gif) [Kehest](https://osu.ppy.sh/users/6145000), ![](https://s.ppy.sh/images/flags/us.gif) [Olympia](https://osu.ppy.sh/users/5357992), ![](https://s.ppy.sh/images/flags/fi.gif) [Nev-](https://osu.ppy.sh/users/11836334), ![](https://s.ppy.sh/images/flags/us.gif) [Gabey](https://osu.ppy.sh/users/12904237), ![](https://s.ppy.sh/images/flags/us.gif) [Raoul](https://osu.ppy.sh/users/9924405) |
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +See the [Spreadsheet](https://docs.google.com/spreadsheets/d/1ESDw34gBfnDWwUrXEPZNxsi4MN89p156aIYP4RYbuYs/edit#gid=0) for a list of all participants.
```suggestion
See [this spreadsheet](https://docs.google.com/spreadsheets/d/1ESDw34gBfnDWwUrXEPZNxsi4MN89p156aIYP4RYbuYs/edit#gid=0) for a list of all participants.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +
```suggestion
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +2022-07-23/2022-07-24
did the match take place across two days?

have a look at [an example](https://osu.ppy.sh/wiki/en/Tournaments/OWC/2021#match-results) for the date formatting here

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- This tournament is a 1v1 double-elimination osu!standard tournament.
it's officially just the "osu!" game mode

```suggestion
- This tournament is a 1v1 double-elimination osu! tournament.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- All players have to treat staff members and all other players wiith high level of respect. Any kind of mistreatment can results into a being banned from the tournament.
```suggestion
- All players have to treat staff members and all other players with a high level of respect. Any kind of mistreatment may result in being banned from the tournament.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- Every player is required to join the tournament discord server.
```suggestion
- Every player is required to join the tournament Discord server.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +    - Grand Final: 6xNM, 4xHD, 4xHR, 4xDT, 1xTB
```suggestion

| Stage | Maps |
| :-- | :-- |
| Qualifiers | 4 NM, 2 HD, 2 HR, 2 DT |
| Round of 32 | 5 NM, 3 HD, 3 HR, 3 DT, 1 TB |
| Round of 16 | 5 NM, 3 HD, 3 HR, 3 DT, 1 TB |
| Quarterfinals | 6 NM, 4 HD, 4 HR, 4 DT, 1 TB |
| Semifinals | 6 NM, 4 HD, 4 HR, 4 DT, 1 TB |
| Finals | 6 NM, 4 HD, 4 HR, 4 DT, 1 TB |
| Grand Final | 6 NM, 4 HD, 4 HR, 4 DT, 1 TB |

```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> + - Every mappool will be a slightly harder than the previous one. Star Rating goal for Grand Finals mappool is 8.0*
```suggestion
 - Every mappool will be slightly harder than the previous one. Maps in the Grand Finals mappool will have 8 stars.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- Qualifier mappool consists of 4xNM, 2xHD, 2xHR & 2x DT maps.
```suggestion
- The Qualifier mappool consists of 4 NM, 2 HD, 2 HR, and 2 DT maps.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- Qualifier mappool will be played in following order NM -> DT.
```suggestion
- The Qualifier mappool will be played in following order: NM -> DT.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- Mappool will be played once only.
```suggestion
- The mappool will be played once only.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- If players disconnects during a map they can replay it after all other maps have been played and other players have left the lobby.
```suggestion
- If a player disconnects during a map they can replay it after all other maps have been played and all other players have left the lobby.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- Players will be seeded following this pattern: Seed 1 VS Seed 32, Seed 2 VS Seed 31, ...
```suggestion
- Players will be matched against each other in the pattern of *seed 1 vs. seed 32*, *seed 2 vs. seed 31*, etc.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- All matches will use NF and Score V2.
it's like the third time this is mentioned

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- Players have 10 minute grace period to join the lobby after an agreed time. If 10 minutes pass and player is still not in the lobby, the other player wins the match.
```suggestion
- Players have a 10-minute grace period to join the lobby after an agreed time. If 10 minutes pass and a player is still not in the lobby, the other player wins the match.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- Players are allowed to pick 1 map for warm up. Maximum length for warm up is 4 minutes. Warm ups have to be in good taste.
```suggestion
- Players are allowed to pick 1 map for warmup, with a maximum length of 4 minutes. Warmups have to be in good taste.
```

2022-08-12 20:28 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +- After warm ups both players will use !roll command to decide pick and ban order. Winner of the roll can decide pick or ban order, the loser of the roll will decide the remaining order.
```suggestion
- After warmups both players will use the `!roll` command to decide pick and ban order. The winner of the roll can decide pick or ban order, and the loser of the roll will decide the remaining order.
```

2022-08-12 20:46 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +![AESS2 logo](img/mainbanner.png)
rename the file

```suggestion
![AESS2 logo](img/banner.png)
```

2022-08-12 20:48 UTC, AetherianFI commented on wiki/Tournaments/AESS/2/en.md
> +![AESS2 logo](img/mainbanner.png)
fixed

2022-08-12 21:27 UTC, Walavouchey commented on wiki/Tournaments/AESS/2/en.md
> +| **Swiq_** | **0** | -1 | Jakson | ***forfeit*** |
no need to bold "*forfeit*"

2022-08-13 14:32 UTC, AetherianFI commented
![image](https://user-images.githubusercontent.com/72926305/184498773-baa3121d-114c-4078-97f7-39686663573c.png)
Am I supposed to do something when this happens?

2022-08-13 15:03 UTC, TPGPL requested changes

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +| WillCookie | 1 | **7** | **Swiq_** | [#1](https://osu.ppy.sh/community/matches/102321669) |
```suggestion
| WillCookie | 1 | **7** | **Swiq\_** | [#1](https://osu.ppy.sh/community/matches/102321669) |
```

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +| Swiq_ | 0 | **7** | **mcy4** | [#1](https://osu.ppy.sh/community/matches/102341595) |
```suggestion
| Swiq\_ | 0 | **7** | **mcy4** | [#1](https://osu.ppy.sh/community/matches/102341595) |
```

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +Friday, July 8, 2022
```suggestion
Friday, July 8, 2022:
```

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +| **Swiq_** | **0** | -1 | Jakson | *forfeit* |
```suggestion
| **Swiq\_** | **0** | -1 | Jakson | *forfeit* |
```

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +| **Swiq_** | **6** | 2 | GSBlank | [#1](https://osu.ppy.sh/community/matches/102161740) |
```suggestion
| **Swiq\_** | **6** | 2 | GSBlank | [#1](https://osu.ppy.sh/community/matches/102161740) |
```

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +| **Swiq_** | 0 | **-1** | rudj | *forfeit* |
```suggestion
| **Swiq\_** | 0 | **-1** | rudj | *forfeit* |
```

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +| **Swiq_** | **5** | 3 | Em_Rald | [#1](https://osu.ppy.sh/community/matches/101581530) |
```suggestion
| **Swiq\_** | **5** | 3 | Em\_Rald | [#1](https://osu.ppy.sh/community/matches/101581530) |
```

2022-08-13 15:03 UTC, TPGPL commented on wiki/Tournaments/AESS/2/en.md
> +| Em_Rald | 3 | **5** | **Saiyku** | [#1](https://osu.ppy.sh/community/matches/101779305) |
```suggestion
| Em\_Rald | 3 | **5** | **Saiyku** | [#1](https://osu.ppy.sh/community/matches/101779305) |
```

2022-08-13 16:39 UTC, TPGPL approved these changes
next time please use feature branches for contributions, not your `master` branch

2022-08-13 16:39 UTC, merged

2022-08-13 16:40 UTC, AetherianFI commented
> next time please use feature branches for contributions, not your `master` branch

oh my mb, i never use github so i dont have good idea how everything works here lol