[ZH/others] Spotlights `2022_Summer`
ppy/osu-wiki pull request #7834
Opened 2022-08-12 02:47 UTC by Kotoki1337

- Create `zh.md` for `2022_Summer`
- Update index page for all language

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-18 09:23 UTC, cl8n commented
was this reviewed off-platform?

2022-08-18 09:27 UTC, Kotoki1337 commented
> was this reviewed off-platform?

no, sorry, idk when i wrongly checked the check box, this is not reviewed

2022-08-18 12:43 UTC, kj415j45 requested changes

2022-08-18 12:43 UTC, kj415j45 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/zh.md
> +1. 赛季每 2 周将开放一个课题模式大厅，每大厅在整个开放期间都可参加。
```suggestion
1. 赛季开始后每 2 周将开放一个课题模式大厅，每个大厅在其开放期间都可参加。
```

2022-08-18 12:43 UTC, kj415j45 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/zh.md
> +   - 在第一轮课题结束后，每周将重新开放一个课题。
```suggestion
   - 在第一轮课题结束后，频率降低为每 1 周重新开放一个课题。
```

2022-08-18 12:43 UTC, kj415j45 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/zh.md
> +   - 每个课题与每两周分配的字母相对应。每个课题会在下个周期复刻一次。
读起来很怪

2022-08-18 12:56 UTC, Kotoki1337 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/zh.md
> +   - 每个课题与每两周分配的字母相对应。每个课题会在下个周期复刻一次。
```suggestion
   - 课题与每周分配的字母相对应。所以每个课题在一个赛季中都有一次复刻机会。
```

2022-08-19 01:48 UTC, heipizhu4 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/zh.md
> +   - 每个课题与每两周分配的字母相对应。每个课题会在下个周期复刻一次。
```suggestion
   - 每个课题与每两周分配的字母相对应。每个课题会在下个周期复现一次。
```

2022-08-19 05:37 UTC, Kotoki1337 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/zh.md
> +   - 每个课题与每两周分配的字母相对应。每个课题会在下个周期复刻一次。
主要是很多游戏都在用 `复刻` 这个词，代表某个动作或者活动重新返场进行，`复现` 也不错，我个人更倾向 `复刻`。但这里其实替换的是 `replayed`，和上文的 `opened again` 差不多，我有在想要不要把所有课题返场一周的操作统称为 `复刻`，或者继续和上文一样统一为类似 `reopened` 的译文：
```suggestion
   - 课题与每周分配的字母相对应。所以每个课题在一个赛季中都会重新开放一次。
```

2022-08-21 19:50 UTC, kj415j45 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/zh.md
> +   - 每个课题与每两周分配的字母相对应。每个课题会在下个周期复刻一次。
```suggestion
   - 每个课题均与一个字母相对应。意味着课题会在赛季内复刻一次。
```

2022-08-22 16:35 UTC, kj415j45 approved these changes

2022-08-24 22:24 UTC, TPGPL approved these changes

2022-08-24 22:26 UTC, merged