[FR ] Add `Beatmap_Spotlights/Seasons/2022_Summer`
ppy/osu-wiki pull request #7835
Opened 2022-08-12 12:37 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-12 17:30 UTC, Ganondorf-1 requested changes

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +  - Seasonal Spotlights
```suggestion
  - Seasonal Spotlights
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +# Saison 7 des Beatmap Spotlights (été 2022)
```suggestion
# Saison 7 des Beatmap Spotlights (Été 2022)
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Début de la saison | 11 Août 2022 |
```suggestion
| Début de la saison | 11 août 2022 |
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Playlist lobby : Playlist A | 11 Août - 25 Août 2022 |
```suggestion
| Playlist lobby : Playlist A | 11 août - 25 août 2022 |
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Playlist lobby : Playlist B | 25 Août - 8 Septembre 2022 |
```suggestion
| Playlist lobby : Playlist B | 25 août - 8 septembre 2022 |
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Playlist lobby : Playlist C | 8 Septembre - 22 Septembre 2022 |
```suggestion
| Playlist lobby : Playlist C | 8 septembre - 22 septembre 2022 |
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Playlist lobby : Playlist A | 22 Septembre - 29 Septembre 2022 |
```suggestion
| Playlist lobby : Playlist A | 22 septembre - 29 septembre 2022 |
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Playlist lobby : Playlist B | 29 Septembre - 6 Octobre 2022 |
```suggestion
| Playlist lobby : Playlist B | 29 septembre - 6 octobre 2022 |
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Playlist lobby : Playlist C | 6 Octobre - 13 Octobre 2022 |
```suggestion
| Playlist lobby : Playlist C | 6 octobre - 13 octobre 2022 |
```

2022-08-12 17:30 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +| Conclusion de la saison | 13 Octobre 2022 |
```suggestion
| Conclusion de la saison | 13 octobre 2022 |
```

2022-08-12 18:36 UTC, Ganondorf-1 requested changes

2022-08-12 18:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Seasons/2022_Summer/fr.md
> +- [Mastermind(xi+nora2r) - Dreadnought (PyaKura) \[\[7K\] Hyperspace\]](https://osu.ppy.sh/beatmapsets/361643#mania/794499), picked as a result of popular vote amongst Curators
```suggestion
- [Mastermind(xi+nora2r) - Dreadnought (PyaKura) \[\[7K\] Hyperspace\]](https://osu.ppy.sh/beatmapsets/361643#mania/794499), choisi suite à un vote populaire parmi les curateurs
```

2022-08-12 20:10 UTC, Ganondorf-1 approved these changes

2022-08-14 15:43 UTC, TicClick approved these changes

2022-08-14 15:47 UTC, merged