[RU] Add `osu! wiki`
ppy/osu-wiki pull request #7838
Opened 2022-08-12 19:56 UTC by Ldashy1

> ### Информация тех, кто проверяет данный перевод

> _В случае появления каких-то проблем грамматики, читаемости, понятности и корректности перевода (а они по-любому будут), **настоятельно рекомендую** воспользоваться функцией предложения изменений (suggestions), чтобы я смог легко, быстро и безболезненно вносить правки в файлы перевода._

> _Также, вы можете оставлять свои замечания по поводу существующих ошибок, чтобы в дальнейшем их наблюдалось намного меньше, **но рекомендую прикрепить их с своему предложению** (я все равно буду читать их, несмотря на то, что мне будет больно это делать)._

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-13 11:47 UTC, Loreos7 commented on wiki/osu!_wiki/ru.md
> +osu! wiki построена на принципе доступности: правки и переводы поощряются и могут осуществляться любым способным и знающим человеком. Данные для статей хранятся в [репозитории GitHub](https://github.
```suggestion
osu! wiki построена на принципе доступности: правки и переводы поощряются и могут осуществляться любым способным и знающим человеком. Данные для статей хранятся в [репозитории GitHub](https://github.com/ppy/osu-wiki) и обновляются участниками путём [создания пулл-реквестов](/wiki/osu!_wiki/Contribution_guide), которые затем проверяются и отправляются в релиз [администраторами вики](/wiki/osu!_wiki/Maintenance/List_of_maintainers).
```

2022-08-14 19:05 UTC, LacticWhale commented
#7827

2022-08-14 19:14 UTC, Loreos7 commented
> #7827

Быстро посмотрел, там очень много ошибок

2022-08-14 22:38 UTC, LacticWhale commented
Хорошо! В следующий раз попробую перевести лучше.

2022-08-16 17:16 UTC, TicClick requested changes
неплохо, существенных замечаний относительно мало

2022-08-16 17:16 UTC, TicClick commented on wiki/osu!_wiki/ru.md
> +Статьи оформляются с использованием формата [GitHub-flavoured Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/). Кроме того, движок сайта поддерживает
- «пользовательские функции» означало бы, что редакторы могут самостоятельно что-то реализовывать, что есть неправда
- front matter здесь — это служебная информация: https://osu.ppy.sh/wiki/ru/Article_styling_criteria/Formatting#%D0%BC%D0%B5%D1%82%D0%B0%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5
```suggestion
Для оформления статей используется [GitHub-flavoured Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/). Кроме того, в движке веб-сайта реализована дополнительные функции, критичные для вики: перенаправления, метаданные статей, дополнительные возможности разметки.
```

2022-08-16 17:16 UTC, TicClick commented on wiki/osu!_wiki/ru.md
> +Статьи составляются в соответствии с [критериями оформления статей](/wiki/Article_styling_criteria) osu! wiki, они написаны нейтральным языком и следуют общим правилам форматирования и оформления. Не
```suggestion
Статьи составлены в соответствии с [критериями оформления](/wiki/Article_styling_criteria) osu! wiki: они написаны нейтральным языком и следуют общим правилам форматирования и оформления. Некоторые справочные статьи являются списками часто задаваемых вопросов (FAQ) и используют неформальный тон. Переводы выполняются по принципу равенства содержания и следуют общим правилам форматирования.
```

2022-08-16 17:16 UTC, TicClick commented on wiki/osu!_wiki/ru.md
> +Несмотря на наличие суффикса *wiki* в названии, osu! wiki не полностью удовлетворяет [концепции Wiki](https://en.wikipedia.org/wiki/Wiki):
```suggestion
Несмотря на наличие суффикса *wiki* в названии, osu! wiki не полностью удовлетворяет [концепции Wiki](https://ru.wikipedia.org/wiki/Вики):
```

2022-08-16 17:16 UTC, TicClick commented on wiki/osu!_wiki/ru.md
> +- Улучшение существующих статей и создание новых поощряется, но для внесения вклада необходимы базовые знания [GitHub](https://github.com), что повышает порог вхождения. Однако существует специальное
мне кажется, так лучше. если нет, резкое начало предложения с «Однако» точно нужно переделать
```suggestion
- Улучшение существующих статей и создание новых поощряется, но для этого необходимы базовые знания [GitHub](https://github.com), что повышает порог вхождения. Чтобы новым участникам было легче приступить к работе, на вики есть отдельное [руководство по работе с ней](wiki/osu!_wiki/Contribution_guide).
```

2022-08-16 17:16 UTC, TicClick commented on wiki/osu!_wiki/ru.md
> +- Все изменения в osu! wiki предварительно модерируются и подвергаются рецензированию, в ходе которого участник должен сотрудничать с рецензентами и отвечать на их отзывы.
```suggestion
- Все изменения в osu! wiki проходят премодерацию и ревью, в ходе которого автор правок должен взаимодействовать с ревьюерами и исправлять их замечания.
```

2022-08-16 17:16 UTC, TicClick commented on wiki/osu!_wiki/ru.md
> +Большинство материалов в osu! wiki распространяются на условиях лицензии [CC-BY-NC 4.0](https://github.com/ppy/osu-wiki/blob/master/LICENCE.md). Это означает, что использование материалов вики разреш
```suggestion
Большинство материалов в osu! wiki распространяются на условиях лицензии [CC-BY-NC 4.0](https://github.com/ppy/osu-wiki/blob/master/LICENCE.md). Это означает, что использование материалов вики разрешено в некоммерческих целях (см. [краткое содержание лицензии](https://tldrlegal.com/license/creative-commons-attribution-noncommercial-4.0-international-(cc-by-nc-4.0)])). Некоторые материалы могут быть защищены различными сторонними лицензиями, которые в таких случаях находятся рядом с материалом и имеют приоритет над глобальной лицензией.
```

2022-08-16 17:16 UTC, TicClick commented on wiki/osu!_wiki/ru.md
> +Обратите внимание, что это не распространяется на использование брендов "osu!" или "ppy" в любом программном обеспечении, ресурсах, рекламе или промоушене, поскольку они защищены законом о товарных з
```suggestion
Обратите внимание, что это не распространяется на использование брендов "osu!" или "ppy" в любом программном обеспечении, ресурсах, рекламе или продвижении, поскольку они защищены законом о товарных знаках. Если вам требуется разрешение на использование этих терминов, пожалуйста, [свяжитесь с нами](mailto:contact@ppy.sh).
```

2022-08-16 17:19 UTC, TicClick commented
ну и да, исправь ошибки, на которые указывают проверки (по ссылке `Details` напротив пункта с красным крестиком должны быть все подробности)

2022-08-18 19:16 UTC, TicClick approved these changes

2022-08-18 19:18 UTC, merged