[FR] Update `Skinning/History`  `Skinning/Osu!`
ppy/osu-wiki pull request #7869
Opened 2022-08-19 11:48 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-19 12:00 UTC, Pisapou commented on wiki/Skinning/osu!/fr.md
> +- Cet élément animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```suggestion
- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```

2022-08-19 12:00 UTC, Pisapou commented on wiki/Skinning/osu!/fr.md
> +- Cet élément animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```suggestion
- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```

2022-08-19 12:00 UTC, Pisapou commented on wiki/Skinning/osu!/fr.md
> +- Cet élément animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```suggestion
- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```

2022-08-21 17:22 UTC, Ganondorf-1 requested changes

2022-08-21 17:22 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
> +- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```suggestion
- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History).
```

2022-08-21 17:22 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
> +- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```suggestion
- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History).
```

2022-08-21 17:22 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
> +- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History)
```suggestion
- Cet élément était animable dans le passé. Pour plus de détails, voir [l'histoire du skinning](/wiki/Skinning/History).
```

2022-08-24 10:06 UTC, Ganondorf-1 approved these changes

2022-08-24 23:51 UTC, cl8n commented
I kept `outdated_translation` but removed `outdated_since` from osu skinning cuz it doesn't seem to match anything useful. there's at least a few more parts that don't match en still

2022-08-24 23:51 UTC, cl8n approved these changes

2022-08-24 23:51 UTC, merged