[DE] Add `Ranking_Criteria/Difficulty_naming`
ppy/osu-wiki pull request #7870
Opened 2022-08-19 13:01 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-19 14:19 UTC, FamousPig requested changes
Looks good apart from a couple of nitpicks.

2022-08-19 14:19 UTC, FamousPig commented on wiki/Ranking_Criteria/Difficulty_naming/de.md
> +Mit der Benennung von Schwierigkeitsstufen wird Spielern mitgeteilt, wie schwierig eine Beatmap ist. Dieser Artikel listet allgemeine Konventionen sowie andere Alternativen auf, die sich im Laufe der
```suggestion
Mit der Benennung von Schwierigkeitsstufen wird Spielern mitgeteilt, wie schwierig eine Beatmap ist. Dieser Artikel listet allgemeine Konventionen sowie andere Alternativen auf, die sich im Laufe der Jahre angesammelt haben. Solange die Namen der Schwierigkeitsstufen jedoch beschreibend sind und die Anforderungen klar angeben, darfst du jede beliebige Art von Schema verwenden.
```
Nit

2022-08-19 14:19 UTC, FamousPig commented on wiki/Ranking_Criteria/Difficulty_naming/de.md
> +Beatmapsets von Songs, die von anderen Rhythmusspielen stammen, übernehmen oft das Benennungsschema des Spiels. Die Verwendung dieser Namen ist für jeden Song akzeptabel. Einige der üblichen Benennun
```suggestion
Beatmapsets von Songs, die von anderen Rhythmusspielen stammen, übernehmen oft das Benennungsschema des Spiels. Die Verwendung dieser Namen ist für jeden Song akzeptabel. Einige der üblichen Benennungsschemata, die ihren Weg nach osu! gefunden haben, werden hier aufgelistet:
```
Sounds weird

2022-08-20 14:51 UTC, FamousPig approved these changes

2022-08-21 01:45 UTC, TPGPL approved these changes

2022-08-21 01:47 UTC, merged