[ZH] Update `Community_Contributors`
ppy/osu-wiki pull request #7889
Opened 2022-08-24 09:37 UTC by QTPC

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-26 09:16 UTC, Kotoki1337 requested changes

2022-08-26 09:16 UTC, Kotoki1337 commented on wiki/People/Community_Contributors/zh.md
> +| ::{ flag=NL }:: [cavoeboy](https://osu.ppy.sh/users/7361815) | 对osu! 现实活动和锦标赛领域的杰出贡献 |
```suggestion
| ::{ flag=NZ }:: [Technocoder](https://osu.ppy.sh/users/10338558) | 对 macOS 技术支持的杰出贡献 |
| ::{ flag=LT }:: [huu](https://osu.ppy.sh/users/6044237) | 对 Project loved 管理和组织的杰出贡献 |
| ::{ flag=NL }:: [OliBomby](https://osu.ppy.sh/users/6573093) | 对通过开发实用程序对 osu! 作图领域的杰出贡献 |
| ::{ flag=TR }:: [frukoyurdakul](https://osu.ppy.sh/users/7612550) | 对通过开发实用程序对 osu!taiko 作图领域的杰出贡献 |
| ::{ flag=BR }:: [LeoFLT](https://osu.ppy.sh/users/3668779) | 对 osu! 锦标赛领域和世界杯的杰出贡献 |
| ::{ flag=US }:: [ChillierPear](https://osu.ppy.sh/users/9501251) | 对 osu! 锦标赛领域和世界杯的杰出贡献 |
| ::{ flag=NL }:: [cavoeboy](https://osu.ppy.sh/users/7361815) | 对 osu! 现实活动和锦标赛领域的杰出贡献 |
```

format

2022-08-26 13:59 UTC, Kotoki1337 requested changes

2022-08-26 13:59 UTC, Kotoki1337 commented on wiki/People/Community_Contributors/zh.md
> +### June
```suggestion
### 六月
```

2022-08-27 07:45 UTC, Kotoki1337 approved these changes
lgtm

2022-08-29 16:17 UTC, TicClick approved these changes

2022-08-29 16:19 UTC, merged