[ZH] Create stub `Background`
ppy/osu-wiki pull request #7892
Opened 2022-08-24 10:12 UTC by QTPC

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-25 06:24 UTC, RushFTK requested changes
Some of review **must be** fixed.

2022-08-25 06:24 UTC, RushFTK commented on wiki/Beatmap/Background/zh.md
> +*关于背景的规定，详见：[审核标准](/wiki/Ranking_Criteria)*
```suggestion
*关于背景的规定，请参阅：[谱面上架标准](/wiki/Ranking_Criteria)*
```
与[相关条目](https://github.com/ppy/osu-wiki/blob/master/wiki/Ranking_Criteria/zh.md)的翻译保持一致。

2022-08-25 06:24 UTC, RushFTK commented on wiki/Beatmap/Background/zh.md
> +**背景** (***BG***) 图片和视频能被添加在 [谱面](/wiki/Beatmap) 之中。当以 "背景" 或 "bg" 称呼时，通常是指背景图片。
```suggestion
**背景** (***BG***) 图片和视频能被添加在 [谱面](/wiki/Beatmap) 之中。仅写作 "背景" 或 "bg" 时，往往指的是背景图片。
```

*only*具有明显意义，翻译不应省去

2022-08-25 06:24 UTC, RushFTK commented on wiki/Beatmap/Background/zh.md
> +背景会在谱面卡片，[歌曲选择界面](/wiki/Client/Interface#选歌界面) 以及游戏中显示。
```suggestion
背景会在谱面信息卡，[歌曲选择界面](/wiki/Client/Interface#选歌界面) 以及游戏中显示。
```

我不清楚*beatmap cards*在哪里出现应该翻译成什么，所以这个review是可选的。

2022-08-29 09:36 UTC, RushFTK approved these changes

2022-08-30 11:28 UTC, Kotoki1337 requested changes

2022-08-30 11:28 UTC, Kotoki1337 commented on wiki/Beatmap/Background/zh.md
> +**背景** (***BG***) 图片和视频能被添加在 [谱面](/wiki/Beatmap) 之中。仅写作 "背景" 或 "bg" 时，往往指的是背景图片。
```suggestion
**背景**（***BG***）图片和视频能被添加在 [谱面](/wiki/Beatmap) 之中。仅写作“背景”或“bg”时，往往指的是背景图片。
```
使用中文标点符号。

2022-09-02 12:12 UTC, TicClick approved these changes

2022-09-02 12:14 UTC, merged