[DE] Add `Client/Interface/Health_bar`, `Gameplay/Pass`, `Gameplay/Combo_milestone` and `Gameplay/Combo_fire`
ppy/osu-wiki pull request #7899
Opened 2022-08-25 13:03 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-25 16:14 UTC, FamousPig requested changes

2022-08-25 16:14 UTC, FamousPig commented on wiki/Client/Interface/Health_bar/de.md
> +In [osu!](/wiki/Game_mode/osu!) und [osu!catch](/wiki/Game_mode/osu!catch) besteht ein Spieler die aktuelle [Beatmap](/wiki/Beatmap), wenn die Lebensleiste komplett leer ist (unter der Annahme, dass
```suggestion
In [osu!](/wiki/Game_mode/osu!) und [osu!catch](/wiki/Game_mode/osu!catch) scheitert ein Spieler an der aktuellen [Beatmap](/wiki/Beatmap), wenn die Lebensleiste komplett leer ist (unter der Annahme, dass keine speziellen Spielmodifikationen aktiviert sind).
```

2022-08-27 11:52 UTC, FamousPig approved these changes

2022-08-29 16:28 UTC, TicClick approved these changes

2022-08-29 16:33 UTC, merged