[ES] Add several `File Formats` articles
ppy/osu-wiki pull request #7905
Opened 2022-08-26 04:16 UTC by TheMoonLoop

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Note: In two of the translations a friend via Discord (OnlyFosi_#3360) helped me, so I wanted to give him credit too

2022-08-26 04:26 UTC, fosiXD commented
¡Me encanta! Sigue así, eres un gran contribuidor. :)

2022-08-26 04:29 UTC, fosiXD submitted a review, later dismissed
Están bastante bien hechos. Algunas correcciones han de ser hechas, pero todo está bien trabajado.

2022-08-26 17:16 UTC, TheMoonLoop commented
There's a error in task `find broken wikilinks`

2022-09-10 07:25 UTC, TheMoonLoop commented
I really don't know what's wrong in here, plz help

2022-09-10 10:25 UTC, The-Last-Cookie commented
> Not a directory: 'wiki/Client/Options/en.md/en.md'

Looking at the link explains why this error occurs.

`/wiki/Client/Options/en.md#updates` in the `osr` article is not a valid link.

Internal wiki links may not have a language indication, due to *osu-web* being responsible for that. When referencing other articles, you mention the link without specifying any language. osu-web will take care of showing an article in a certain language as soon as a user requests a wiki page.

So, in this case the link should instead be `/wiki/Client/Options#updates`. See [the ASC about internal links](https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#internal-links) for more information.

In any way, there's also a rule called [content parity](https://osu.ppy.sh/wiki/en/Article_styling_criteria/Writing#content-parity). The link you have added in this article is not present in the English original. Thus, I'm pretty sure this link should be **removed**. You may want to ask a maintainer about that.

2022-09-10 10:25 UTC, Ganondorf-1 commented on wiki/Client/File_formats/Osr_(file_format)/es.md
> +| TargetPractice | 8388608 (23) | solo si [osu!cuttingedge](/wiki/Client/Options/en.md#updates) esta seleccionado |
I think this link is the problem

2022-09-10 12:26 UTC, agatemosu requested changes

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- 3: Spinner
```suggestion
Los tipos de objetos de golpeo se almacenan en un número entero de 8 bits donde cada bit es una marca con un significado especial. El tipo de objeto base viene dado por los bits 0, 1, 3 y 7 (de menos a más significativo):

- 0: Círculo de golpeo
- 1: Deslizador
- 3: Ruleta
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- **`hitSample` (Lista separada por dos puntos):** Información sobre qué muestras se reproducen cuando se golpea el objeto. Está estrechamente relacionado con `hitSound`. Si no está escrito, por defe
```suggestion
## Objetos de golpeo

*Sintaxis de los objetos de golpeo:* `x,y,time,type,hitSound,objectParams,hitSample`

- **`x` (Integer)** y **`y` (Integer):** Posición de los [osu! pixels](/wiki/Client/Beatmap_editor/osu!_pixel) del objeto.
- **`time` (Integer):** Tiempo cuando el objeto debe ser golpeado en milisegundos desde el inicio del audio.
- **`type` (Integer):** Indicadores de bits que indican el tipo de objeto. Ver [la sección de tipo](#tipo).
- **`hitSound` (Integer):** Indicadores de bits que indican el sonido de impacto aplicado al objeto.
- **`objectParams` (Lista separada por comas):** Parámetros adicionales específicos del tipo de objeto.
- **`hitSample` (Lista separada por dos puntos):** Información sobre qué muestras se reproducen cuando se golpea el objeto. Está estrechamente relacionado con `hitSound`; ver [la sección de hitsounds](#hitsounds). Si no está escrito, por defecto es `0:0:0:0:`.
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- Los Spinners se convierten en notas denden.
```suggestion
Los objetos de osu!taiko solo usan `time` para determinar cómo se colocan en el campo de juego, por lo que `x` e `y` se ignoran. Del mismo modo, la única parte significativa de las Sliders curvas es `lenght`; `curveType` y `curvePoints` solo son relevantes cuando se abre el mapa en el editor. Se ignoran los colores combinados y los nuevos combos, y se utilizan hitsounds específicos del modo.

- Los círculos de golpeo con whistle o clap se convierten en kats, y otros círculos se convierten en dons. Agregar el sonido final cambia estos a sus grandes variantes.
- Los deslizadores se convierten en redobles de tambor.
- Las ruletas se convierten en notas denden.
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- **`endTime` (Integer):** Hora de finalización de la espera, en milisegundos desde el comienzo del audio del beatmap.
```suggestion
*Sintaxis de las notas largas:* `x,y,tiempo,tipo,hitSound,endTime:hitSample`

- **`endTime` (Integer):** Hora de finalización de las notas largas, en milisegundos desde el comienzo del audio del beatmap.
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +Los círculos de visita no tienen `objectParams` adicionales.
```suggestion
- Skin, con el `index` eliminado
- Recursos por defecto, con el `index` eliminado

Cuando se proporciona `filename` no se reproducirán sonidos adicionales y en su lugar se reproducirá este archivo en el directorio del beatmap.

### Círculos de golpeo

Los círculos de golpeo no tienen `objectParams` adicionales.
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- **`effects` (Integer):** Indicadores de bits que le dan al punto de tiempo efectos adicionales.
```suggestion
- **`time` (Integer):** Hora de inicio de la sección de tiempo en milisegundos desde el comienzo del audio del beatmap. El final de la sección de tiempo es el tiempo del siguiente punto de tiempo (o nunca, si este es el último punto de tiempo).
- **`beatLength` (Decimal):** Esta propiedad tiene dos significados:
  - Para puntos de tiempo no heredados, la duración de un beat en milisegundos.
  - Para los puntos de tiempo heredados, un multiplicador de velocidad del control deslizante inverso negativo como porcentaje. Por ejemplo, `-50` haría que todos los Sliders en esta sección de tiempo fueran el doble de rápidos que `SliderMultiplier`.
- **`meter` (Integer):** Cantidad de beats en un compás. Los puntos de tiempo heredados ignoran esta propiedad.
- **`sampleSet` (Integer):** Conjunto de muestra predeterminado para objetos de golpe (0 = beatmap predeterminado, 1 = normal, 2 = soft, 3 = drum).
- **`sampleIndex` (Integer):** Índice de muestra personalizado para objetos de golpeo. `0` indica los sonidos de éxito predeterminados de osu!
- **`volume` (Integer):** Porcentaje de volumen para los objetos de golpeo.
- **`uninherited` (0 or 1):** Si el punto de tiempo se hereda o no.
- **`effects` (Integer):** Indicadores de bits que le dan al punto de tiempo efectos adicionales. Ver [la sección de efectos](#efectos).
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +## Metadata
```suggestion
| `BeatDivisor` | Integer | [Divisor de beat](/wiki/Client/Beatmap_editor/Beat_Snap_Divisor) |
| `GridSize` | Integer | [Tamaño de la cuadrícula](/wiki/Beatmapping/Grid_snapping) |
| `TimelineZoom` | Decimal | Factor de escala para la [línea de tiempo del objeto](/wiki/Client/Beatmap_editor/Compose#top-left-(hit-objects-timeline)) |

## Metadatos
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `CountdownOffset` | Integer | Tiempo en beats que la cuenta regresiva comienza antes del primer objeto golpeado | 0 |
```suggestion
| `OverlayPosition` | String | Dibuja el orden de las superposiciones de círculos de golpeo en comparación con los números de golpeo (`NoChange` = usar configuracion de skin, `Below` = dibujar superposiciones debajo de los números, `Above` = dibujar superposiciones encima de los números) | NoChange |
| `SkinPreference` | String | Skin preferida durante el juego |  |
| `EpilepsyWarning` | 0 or 1 | Si se debe mostrar o no una advertencia sobre colores intermitentes al comienzo del mapa | 0 |
| `CountdownOffset` | Integer | Tiempo en beats que la cuenta regresiva comienza antes del primer objeto de golpeao | 0 |
```

2022-09-10 12:26 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `StackLeniency` | Decimal | Multiplicador para el umbral en el tiempo en el que los objetos golpeados que están colocados muy juntos se apilan (0–1) | 0.7 |
```suggestion
| `Countdown` | Integer | Velocidad del contador antes del primer objeto de golpeo (`0` = sin countdown, `1` = normal, `2` = mitad, `3` = doble) | 1 |
| `SampleSet` | String | Conjunto de muestra que se usará si los puntos de tiempo no lo anulan (`Normal`, `Soft`, `Drum`) | Normal |
| `StackLeniency` | Decimal | Multiplicador para el umbral en el tiempo en el que los objetos de golpeo que están colocados muy juntos se apilan (0–1) | 0.7 |
```

2022-09-10 17:16 UTC, TheMoonLoop commented
wa-
oh well, tysm to all of you, I will be seeing and reviewing everything u guys put and I will correct it
thanks again

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +La primera línea del archivo especifica la version del archivo. Por ejemplo, `osu file format v14` es la ultima version.
```suggestion
La primera línea del archivo especifica la versión del archivo. Por ejemplo, `osu file format v14` es la última versión.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `Countdown` | Integer | Velocidad del contador antes del primer objeto de golpeo (`0` = sin countdown, `1` = normal, `2` = mitad, `3` = doble) | 1 |
```suggestion
| `Countdown` | Integer | Velocidad del contador antes del primer objeto de golpeo (`0` = sin cuenta atras, `1` = normal, `2` = mitad, `3` = doble) | 1 |
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `ArtistUnicode` | String | Artista de la cancion |
```suggestion
| `TitleUnicode` | String | Título de la canción |
| `Artist` | String | Artista de la canción romanizada |
| `ArtistUnicode` | String | Artista de la canción |
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- **`eventParams` (Lista separada por comas):** Parametros extra que especifican el tipo de evento.
```suggestion
- **`eventParams` (Lista separada por comas):** Parámetros extra que especifican el tipo de evento.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +Cada beatmap debe contener su propia dificultad especáfica de storyboard, ya sea en conjunto con el storyboard externo o por sí mismo.
```suggestion
*Para información sobre la sintaxis del storyboard, ver [Comandos del storyboard](/wiki/Storyboard/Scripting).*

Los storyboards pueden definirse con un archivo opcional aparte con la extensión `.osb`. Storyboard externos son compartidos entre todas las dificultades de un beatmap.

Cada beatmap debe contener su propia dificultad específica de storyboard, ya sea en conjunto con el storyboard externo o por sí mismo.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +  - Para los puntos de tiempo heredados, un multiplicador de velocidad del control deslizante inverso negativo como porcentaje. Por ejemplo, `-50` haría que todos los Sliders en esta sección de tiemp
```suggestion
  - Para los puntos de tiempo heredados, un multiplicador de velocidad del control deslizante inverso negativo como porcentaje. Por ejemplo, `-50` haría que todos los deslizadores en esta sección de tiempo fueran el doble de rápidos que `SliderMultiplier`.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +Se hereda el segundo punto de tiempo a los 12 segundos, cambiando la velocidad del Slider a 4x y la muestra configurada en batería.
```suggestion
Se hereda el segundo punto de tiempo a los 12 segundos, cambiando la velocidad del deslizador a 4x y la muestra configurada en batería.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `SliderBorder` | Color del borde del Slider |
```suggestion
| `SliderTrackOverride` | Color de la pista del deslizador aditivo |
| `SliderBorder` | Color del borde del deslizador |
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- 7: Nota larga de osu!Mania
```suggestion
- 7: Nota larga de osu!mania
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +En todos los modos (excepto en osu!mania), la propiedad de skin `LayeredHitSounds` obliga a que se incluya el sonido normal independientemente de la configuración del bit 0. Está habilitado por defec
```suggestion
En todos los modos (excepto en osu!mania), la propiedad de la skin `LayeredHitSounds` obliga a que se incluya el sonido normal independientemente de la configuración del bit 0. Está habilitado por defecto.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +Si el `lenght` del deslizador es más larga que la curva definida, el control deslizante se extenderá hasta alcanzar la longitud objetivo:
```suggestion
Si el `lenght` del deslizador es más larga que la curva definida, el control deslizante se extenderá hasta alcanzar la longitud objetiva:
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +*Aviso: el `lenght` del deslizador se puede utilizar para determinar el tiempo que lleva completar el deslizador . `length / (SliderMultiplier * 100 * SV) * beatLength` indica cuántos milisegundos se
```suggestion
*Aviso: el `lenght` del deslizador se puede utilizar para determinar el tiempo que lleva completar el deslizador. `length / (SliderMultiplier * 100 * SV) * beatLength` indica cuántos milisegundos se tarda en completar una diapositiva del deslizador (donde `SV` es el multiplicador de velocidad del deslizador dado por el punto de tiempo heredado efectivo, o `1` si hay es ninguno).*
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +Además de los sonidos de los bordes, los deslizadores también emiten un sonido continuo cada vez que el jugador se encuentra dentro del alcance del círculo de seguimiento del Slider. El archivo de so
```suggestion
#### Hitsounds del deslizador

Además de los sonidos de los bordes, los deslizadores también emiten un sonido continuo cada vez que el jugador se encuentra dentro del alcance del círculo de seguimiento del deslizador. El archivo de sonido se reproduce en bucle mientras está activo.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +Los objetos de osu!taiko solo usan `time` para determinar cómo se colocan en el campo de juego, por lo que `x` e `y` se ignoran. Del mismo modo, la única parte significativa de las Sliders curvas es
```suggestion
Los objetos de golpeo de osu!taiko solo usan `time` para determinar cómo se colocan en el campo de juego, por lo que `x` e `y` se ignoran. Del mismo modo, la única parte significativa de los deslizadores curvos es `lenght`; `curveType` y `curvePoints` solo son relevantes cuando se abre el mapa en el editor. Se ignoran los colores combinados y los nuevos combos, y se utilizan hitsounds específicos del modo.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +La pantalla de osu!catch solo usa el eje x, por lo que `y` no es relevante. Las Sliders curvas pueden utilizar el espacio vertical para lograr una aceleración horizontal cuando se aplanan en un campo
```suggestion
La pantalla de osu!catch solo usa el eje x, por lo que `y` no es relevante. Los deslizadores curvos pueden utilizar el espacio vertical para lograr una aceleración horizontal cuando se aplanan en un campo de juego unidimensional.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +### osu!manía
```suggestion
### osu!mania
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- Los deslizadores y las ruletas no se utilizan en osu!mania. En cambio pasan a ser notas largas.
```suggestion
- Los deslizadores y las ruletas no se utilizan en osu!mania.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- A los 12,6 segundos
```suggestion
- A los 12.6 segundos
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- Con un sonido de whistle al principio y un sonido de whistle jugando con set soft al final.
```suggestion
- Con un sonido de whistle al principio y un sonido de whistle jugando con set soft al final
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- A los 11,2 segundos
```suggestion
- A los 11.2 segundos
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `AudioLeadIn` | Integer | Milisegundos de silencio antes de que el audio empiece. | 0 |
```suggestion
| `AudioFilename` | String | Localización del audio en la carpeta local |  |
| `AudioLeadIn` | Integer | Milisegundos de silencio antes de que el audio empiece | 0 |
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `SliderTickRate` | Decimal | Cantidad de ticks del slider por ritmo |
```suggestion
| `SliderMultiplier` | Decimal | Velocidad base del deslizador en cientos de [osu! pixels](/wiki/Client/Beatmap_editor/osu!_pixel) por ritmo |
| `SliderTickRate` | Decimal | Cantidad de ticks del deslizador por ritmo |
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- Los círculos de golpeo con whistle o clap se convierten en kats, y otros círculos se convierten en dons. Agregar el sonido final cambia estos a sus grandes variantes.
```suggestion
- Los círculos de golpeo con whistle o clap se convierten en kats, y otros círculos de golpeo se convierten en dons. Agregar el sonido final cambia estos a sus grandes variantes.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +De forma similar a osu!catch, los objetos hit de osu!mania no usan `y`. `x` se usa para determinar la columna; consulte la [sección de Notas largas](#notas-largas-(solo-osu!mania)).
```suggestion
De forma similar a osu!catch, los objetos de golpeo de osu!mania no usan `y`. `x` se usa para determinar la columna; consulte la [sección de Notas largas](#notas-largas-(solo-osu!mania)).
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- **`sampleIndex` (Integer):** Índice de muestra personalizado para objetos de golpeo. `0` indica los sonidos de éxito predeterminados de osu!
```suggestion
- **`sampleSet` (Integer):** Conjunto de muestra predeterminado para objetos de golpeo (0 = beatmap predeterminado, 1 = normal, 2 = soft, 3 = drum).
- **`sampleIndex` (Integer):** Índice de muestra personalizado para objetos de golpeo. `0` indica los sonidos de éxito predeterminados de osu!.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- **`hitSound` (Integer):** Indicadores de bits que indican el sonido de impacto aplicado al objeto.
```suggestion
- **`hitSound` (Integer):** Indicadores de bits que indican el sonido de golpeo aplicado al objeto.
```

2022-09-10 19:55 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +Los tipos de objetos de golpeo se almacenan en un número entero de 8 bits donde cada bit es una marca con un significado especial. El tipo de objeto base viene dado por los bits 0, 1, 3 y 7 (de menos
```suggestion
Los tipos de objetos de golpeo se almacenan en un número entero de 8 bits donde cada bit es una marca con un significado especial. El tipo de objeto de golpeo base viene dado por los bits 0, 1, 3 y 7 (de menos a más significativo):
```

2022-09-10 22:03 UTC, agatemosu requested changes

2022-09-10 22:03 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +*Sintaxis de las notas largas:* `x,y,tiempo,tipo,hitSound,endTime:hitSample`
```suggestion
*Sintaxis de las notas largas:* `x,y,time,type,hitSound,endTime:hitSample`
```

2022-09-11 08:27 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +
```suggestion

```

2022-09-11 08:28 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +
```suggestion

```

2022-09-11 10:07 UTC, agatemosu commented on wiki/Client/File_formats/Osr_(file_format)/es.md
> +**Informacion adicional de mod:**
```suggestion
| Short | Cantidad de 300s |
| Short | Cantidad de 100s en standard, 150s en Taiko, 100s en CTB y 100s en mania |
| Short | Cantidad de 50s en standard, frutas pequeñas en CTB y 50s en mania |
| Short | Cantidad de Gekis en standard y los Max 300s en mania |
| Short | Cantidad de Katus en standard y 200s en mania |
| Short | Cantidad de fallos |
| Integer | Puntuación total mostrada en la pantalla final |
| Short | Mejor combo mostrado en la pantalla final |
| Byte | Perfect/Full combo (1 = sin fallos, sin deslizadores rotos y sin deslizadores terminados antes) |
| Integer | Mods usados. Ver abajo para una lista de los valores de los mods. |
| String | Barra de vida: pares u/v separados por comas, donde u es el tiempo en milisegundos en la canción y v es un valor de punto float de 0 - 1 que representa la cantidad de vida que tienes en el momento dado (0 = la barra de vida está vacía, 1 = la barra de vida está llena) |
| Long | Marca de tiempo ([Windows ticks](https://docs.microsoft.com/es-es/dotnet/api/system.datetime.ticks)) |
| Integer | Longitud en bytes de datos de reproducción comprimidos |
| Byte Array | Datos de reproducción comprimidos |
| Long | ID de puntaje en línea |
| Double | Información adicional de mod. Solo presente si [Target Practice](/wiki/Gameplay/Game_modifier/Target_Practice) está activado. |

**Información adicional de mod:**
```

2022-09-11 17:23 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- Con un sonido de whistle al principio y un sonido de whistle jugando con set soft al final
```suggestion
- Con un sonido de whistle al principio y un sonido de whistle jugando con set soft al final

```

2022-09-11 17:23 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +- **`uninherited` (0 or 1):** Si el punto de tiempo se hereda o no.
```suggestion
- **`uninherited` (0 o 1):** Si el punto de tiempo se hereda o no.
```

2022-09-11 17:23 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +| `SamplesMatchPlaybackRate` | 0 or 1 | Si las muestras de sonido cambiarán o no la velocidad al jugar con mods que cambian de velocidad | 0 |
```suggestion
| `LetterboxInBreaks` | 0 o 1 | Si los descansos tienen o no un efecto de pantalla ancha | 0 |
| `StoryFireInFront` | 0 o 1 | *Obsoleto* | 1 |
| `UseSkinSprites` | 0 o 1 | Si el storyboard puede usar o no las imágenes del usuario | 0 |
| `AlwaysShowPlayfield` | 0 o 1 | *Obsoleto* | 0 |
| `OverlayPosition` | String | Dibuja el orden de las superposiciones de círculos de golpeo en comparación con los números de golpeo (`NoChange` = usar configuracion de skin, `Below` = dibujar superposiciones debajo de los números, `Above` = dibujar superposiciones encima de los números) | NoChange |
| `SkinPreference` | String | Skin preferida durante el juego |  |
| `EpilepsyWarning` | 0 o 1 | Si se debe mostrar o no una advertencia sobre colores intermitentes al comienzo del mapa | 0 |
| `CountdownOffset` | Integer | Tiempo en ritmos que la cuenta regresiva comienza antes del primer objeto de golpeo | 0 |
| `SpecialStyle` | 0 o 1 | Si se usa o no el diseño de teclas de estilo "N+1" para osu!mania | 0 |
| `WidescreenStoryboard` | 0 o 1 | Si el storyboard permite o no la visualización en pantalla ancha | 0 |
| `SamplesMatchPlaybackRate` | 0 o 1 | Si las muestras de sonido cambiarán o no la velocidad al jugar con mods que cambian de velocidad | 0 |
```

2022-09-11 17:23 UTC, agatemosu commented on wiki/Client/File_formats/Osu_(file_format)/es.md
> +## General
```suggestion
## General

```

2022-09-11 17:23 UTC, agatemosu commented on wiki/Client/File_formats/Osr_(file_format)/es.md
> +| w | Long | Tiempo en minisegundos desde la accion anterior. |
```suggestion
**Información adicional de mod:**

| Mod | Información guardada |
| :-- | :-- |
| Target Practice | Precisión total de todos los golpes. Divide esto por el número de círculos de goleo en el mapa para encontrar la precisión mostrada en juego. |

Lo restante contiene información sobre el movimiento del ratón y las presiones de tecla en una cadena [LZMA](https://es.wikipedia.org/wiki/LZMA).

Cuando se descomprime, el texto contiene datos separados por comas. Cada pieza denota una acción, representada por 4 números en la forma: `w | x | y | z.`

| Parte | Tipo de dato | Descripción |
| :-- | :-- | :-- |
| w | Long | Tiempo en milisegundos desde la acción anterior. |
```

2022-09-11 17:23 UTC, agatemosu commented on wiki/Client/File_formats/Osr_(file_format)/es.md
> +| String | Varía | Tiene tres partes; un solo byte que será 0x00, que indica que las dos partes siguientes no están presentes, ó 0x0b (11 decimal), que indica que las dos partes siguientes están pres
```suggestion
| String | Varía | Tiene tres partes; un solo byte que será 0x00, que indica que las dos partes siguientes no están presentes, o 0x0b (11 decimal), que indica que las dos partes siguientes están presentes. Si es 0x0b, habrá un ULEB128, que representa la longitud en bytes de la siguiente cadena, y luego la cadena en sí, codificada en UTF-8. Ver [UTF-8](http://es.wikipedia.org/wiki/UTF-8) para más información. |
```

2022-09-11 18:39 UTC, agatemosu approved these changes

2022-09-11 18:39 UTC, agatemosu commented on wiki/Client/File_formats/Osr_(file_format)/es.md
> +| LEB128 | Varía | Un entero de longitud variable. Ver [LEB128](https://en.wikipedia.org/wiki/LEB128) para mas información. |
```suggestion
| LEB128 | Varía | Un entero de longitud variable. Ver [LEB128](https://en.wikipedia.org/wiki/LEB128) para más información. |
```

2022-09-11 18:39 UTC, agatemosu commented on wiki/Client/File_formats/Osr_(file_format)/es.md
> +| Target Practice | Precisión total de todos los golpes. Divide esto por el número de círculos de goleo en el mapa para encontrar la precisión mostrada en juego. |
```suggestion
| Target Practice | Precisión total de todos los golpes. Divide esto por el número de círculos de golpeo en el mapa para encontrar la precisión mostrada en juego. |
```

2022-09-11 18:41 UTC, agatemosu approved these changes

2022-09-13 03:37 UTC, AdamiYama approved these changes
Un grande! <3

2022-09-13 10:17 UTC, SrIzan10 approved these changes
seems legit

2022-09-13 11:28 UTC, TicClick approved these changes

2022-09-13 11:30 UTC, TicClick commented
a good example of collaboration and mutual help, thank you all for involvement

2022-09-13 11:30 UTC, merged