[DE] Add `osu_wiki/Maintenance/List_of_maintainers`
ppy/osu-wiki pull request #7928
Opened 2022-08-30 19:54 UTC by The-Last-Cookie

Terminology:

- `issue tracker` --> `Issue-Tracker`
- `pull request` --> `Pull Request` and `Änderungsvorschlag`
- `merge` --> `zusammenführen`
- `repository` is actually [in the Duden](https://www.duden.de/rechtschreibung/Repository)

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-08-30 20:35 UTC, The-Last-Cookie commented on wiki/osu!_wiki/Maintenance/List_of_maintainers/de.md
> +Wenn du Hilfe bei der Erstellung eines Beitrags benötigst oder möchtest, dass dein Pull Request überprüft wird, dann sende eine Nachricht im Kanal `#osu-wiki` des [osu!dev Discord-Servers](/wiki/Comm
```suggestion
Wenn du Hilfe bei der Erstellung eines Beitrags benötigst oder möchtest, dass dein Pull Request überprüft wird, dann sende eine Nachricht im Kanal `#osu-wiki` des [osu!dev Discord-Servers](/wiki/Community/osu!dev_Discord_server) und ein Verantwortlicher oder ein anderer Beteiligter wird dir antworten. Es wird empfohlen, auf Englisch zu schreiben, da alle Betreuer Englisch können.
```
For now, the last phrase is on parity with the English text. However, I think it sounds better for readers this way.

2022-08-31 17:02 UTC, FamousPig requested changes

2022-09-03 21:49 UTC, The-Last-Cookie commented
After some reconsideration, I've changed the usage of `pull request` to only a one-time mention. See [`d6d07a5`](https://github.com/ppy/osu-wiki/pull/7928/commits/d6d07a54fa1af35569b57fbee27a8e6b283bbe8a) for details.

> Feels to me like `Pull Request` should be feminine, since `Anfrage/Bitte` is as well.

I don't really agree with you here, since you could also translate pull request with `Antrag`. As a side note, I've used `Antrag` in the current version for more word variety. Compare with [Duden, chapter `Bedeutungen`, point 2](https://www.duden.de/rechtschreibung/Antrag).

2022-09-08 14:09 UTC, FamousPig commented
> > Feels to me like `Pull Request` should be feminine, since `Anfrage/Bitte` is as well.
> 
> I don't really agree with you here, since you could also translate pull request with `Antrag`. As a side note, I've used `Antrag` in the current version for more word variety. Compare with [Duden, chapter `Bedeutungen`, point 2](https://www.duden.de/rechtschreibung/Antrag).

Right, didn't think of `Antrag`, makes sense. Also looked up other uses and everyone seems to treat it as masculine.

2022-09-08 14:09 UTC, FamousPig approved these changes

2022-09-09 14:25 UTC, TicClick approved these changes

2022-09-09 14:34 UTC, merged