[KO] Add `Article_styling_criteria`
ppy/osu-wiki pull request #7930
Opened 2022-08-30 23:18 UTC by sylphi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-07 01:59 UTC, CivilWiki requested changes
Suggested my opinions to change some translatation on this wiki page.

2022-09-07 01:59 UTC, CivilWiki commented on wiki/Article_styling_criteria/ko.md
> +# 문서 스타일링 기준
Styling 자체가 명사이며, 디자인 혹은 스타일이란 뜻을 가지고 있으므로, 스타일로 수정해도 좋으나, "스타일링" 이라는 단어가 한국어 위키에서의 표준 형식이라면 수정하지 않으셔도 좋습니다.

2022-09-07 01:59 UTC, CivilWiki commented on wiki/Article_styling_criteria/ko.md
> +문서 스타일링 기준 (ASC)은 모든 문서의 명확성, 포맷, 레이아웃의 일관성을 보장하기 위한 osu!wiki의 필수적인 스타일링 기준입니다. 이는 올바른 문법, 정확한 맞춤법, 정확한 정보를 보장하는 데 도움을 줍니다.
Clarity을 "명확성" 으로 직역을 한데 비해, formatting과 layout은 문자 그대로 사용하신 부분이 마음에 걸렸습니다.
Formatting을 형식, layout을 구성으로 수정하는 것에 대해 어떻게 생각하시나요?

2022-09-07 01:59 UTC, CivilWiki commented on wiki/Article_styling_criteria/ko.md
> +이 문서는 주로 검증 지원을 제공하고, 수년에 걸쳐 형성된 기여자들을 위한 표준을 나타내는 도구입니다. 위키는 리뷰를 통한 공동 작업이기에, 모든 내용을 읽거나 암기할 필요는 없습니다. 기여를 하기 원하신다면, [기여 가이드](/wiki/osu!_wiki/Contribution_guide)를 읽어보시기 바랍니다.
line 9와 line 15와는 다른 "~를 읽어보시기 바랍니다."의 형식을 하나로 통일하면 좋을 듯 싶습니다.

2022-09-07 01:59 UTC, CivilWiki commented on wiki/Article_styling_criteria/ko.md
> +- [포맷](Formatting): Markdown 및 기타 포맷 규칙을 포함합니다
line 11의 리뷰와 동일.

2022-09-07 02:50 UTC, CivilWiki commented
looks like all good!

2022-09-07 02:51 UTC, CivilWiki approved these changes
looks like all good for now.

2022-09-09 14:26 UTC, TicClick approved these changes

2022-09-09 14:43 UTC, merged