update skinning osu
ppy/osu-wiki pull request #7937
Opened 2022-09-01 11:55 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] No EN diff, so does everything feat correctly en.md

2022-09-04 19:45 UTC, Ganondorf-1 requested changes

2022-09-04 19:45 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
>  - Cet élément s'estompe avant d'être frappé et s'étend lorsqu'il est frappé ou manqué.
```suggestion
- Cet élément s'estompe avant d'être touché et s'étend lorsqu'il est touché ou manqué.
```

2022-09-04 19:58 UTC, Ganondorf-1 approved these changes

2022-09-07 08:22 UTC, Biokax approved these changes

2022-09-07 13:41 UTC, TicClick approved these changes

2022-09-07 13:48 UTC, merged