[DE] Add `Maintenance`
ppy/osu-wiki pull request #7956
Opened 2022-09-06 12:21 UTC by The-Last-Cookie

This PR proposes (together with #7928) to use the following terminology:

- `pull request` --> `Änderungsvorschlag`, `Änderungsanfrage` and `Änderungsantrag`
- `merge` --> `zusammenführen` and `fusionieren`
- `fork` - `Verzweigung`
- `branch` - `Branch`, *perhaps* `Ast` (in any case this should not be too similar to `Abzweigung`)
- `contributor` --> `Mitwirkender` and `Beteiligter`

Additionally, I'm currently working on translating the articles in `osu!_wiki/Contibution_guide`. These will come in later PRs.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-08 14:57 UTC, FamousPig requested changes

2022-09-08 14:57 UTC, FamousPig commented on wiki/osu!_wiki/Maintenance/de.md
> +Die CI-Checks laufen automatisch bei jedem Commit eines regelmäßigen Mitwirkenden. Damit die Änderungsanfrage fusioniert wird, wird von den Mitwirkenden erwartet, dass sie alle Fehler beheben, die vo
```suggestion
Die CI-Checks laufen automatisch bei jedem Commit eines regelmäßigen Mitwirkenden. Damit die Änderungsanfrage akzeptiert wird, wird von den Mitwirkenden erwartet, dass sie alle Fehler beheben, die von der CI aufgezeigt werden. Um den [Status der Überprüfungen](img/ci-status.png) zu sehen, mache das Folgende:
```
```suggestion
Die CI-Checks laufen automatisch bei jedem Commit eines regelmäßigen Mitwirkenden. Damit die Änderungsanfrage zusammengeführt wird, wird von den Mitwirkenden erwartet, dass sie alle Fehler beheben, die von der CI aufgezeigt werden. Um den [Status der Überprüfungen](img/ci-status.png) zu sehen, mache das Folgende:
```
```suggestion
Die CI-Checks laufen automatisch bei jedem Commit eines regelmäßigen Mitwirkenden. Damit die Änderungsanfrage in den `master`-Branch aufgenommen wird, wird von den Mitwirkenden erwartet, dass sie alle Fehler beheben, die von der CI aufgezeigt werden. Um den [Status der Überprüfungen](img/ci-status.png) zu sehen, mache das Folgende:
```

2022-09-08 14:57 UTC, FamousPig commented on wiki/osu!_wiki/Maintenance/de.md
> +Verantwortliche führen eine finale Überprüfung von Änderungsvorschlägen durch und fusionieren diese. Wenn du bei einem Beitrag Hilfe benötigst, frage einen Betreuer im Kanal `#osu-wiki`.
```suggestion
Verantwortliche führen eine finale Überprüfung von Änderungsvorschlägen durch und mergen diese. Wenn du bei einem Beitrag Hilfe benötigst, frage einen Betreuer im Kanal `#osu-wiki`.
```
```suggestion
Verantwortliche führen eine finale Überprüfung von Änderungsvorschlägen durch und führen diese mit dem Master-Branch zusammen. Wenn du bei einem Beitrag Hilfe benötigst, frage einen Betreuer im Kanal `#osu-wiki`.
```
```suggestion
Verantwortliche führen eine finale Überprüfung von Änderungsvorschlägen durch und akzeptieren diese. Wenn du bei einem Beitrag Hilfe benötigst, frage einen Betreuer im Kanal `#osu-wiki`.
```
```suggestion
Verantwortliche führen eine finale Überprüfung von Änderungsvorschlägen durch und wenden diese an. Wenn du bei einem Beitrag Hilfe benötigst, frage einen Betreuer im Kanal `#osu-wiki`.
```
Really don't like `fusioniert`. It feels way too exotic in this context.

2022-09-08 14:57 UTC, FamousPig commented on wiki/osu!_wiki/Maintenance/de.md
> +Eine der Hauptmerkmale jedes Wikis ist *Vernetzung*, was bedeutet, dass Artikel auf verwandte Seiten verweisen, um dem Leser zu helfen, im Fluss zu bleiben. Füge für die Verbindung von Artikeln Links
```suggestion
Eines der Hauptmerkmale jedes Wikis ist *Vernetzung*, was bedeutet, dass Artikel auf verwandte Seiten verweisen, um dem Leser zu helfen, im Fluss zu bleiben. Füge für die Verbindung von Artikeln Links zu den genannten Begriffen hinzu, bei denen es für ein besseres Verständnis des Themas wichtig ist. Verweise bei Bedarf auf einzelne Abschnitte von Artikeln und nutze [Begriffsabgrenzungsseiten](/wiki/Article_styling_criteria/Formatting#artikel-für-die-begriffsabgrenzung) für mehrdeutige Begriffe.
```

2022-09-08 14:57 UTC, FamousPig commented on wiki/osu!_wiki/Maintenance/de.md
> +Das osu!-Wiki wird von Menschen aus der ganzen Welt gelesen. Um deiner lokalen Community zu helfen und neue, großartige Spieler, Mapper, Modder und Entwickler in das Spiel zu locken, kannst du englis
```suggestion
Das osu!-Wiki wird von Menschen aus der ganzen Welt gelesen. Um deiner lokalen Community zu helfen und neue, großartige Spieler, Mapper, Modder und Entwickler in das Spiel zu locken, kannst du englische Artikel übersetzen oder existierende Übersetzungen aktualisieren, die in Rückstand geraten sind. Siehe dir die [Liste an Sprachen](/wiki/Article_styling_criteria/Formatting#locales) an, die vom osu!-Wiki unterstützt werden und stelle sicher, dass deine Übersetzung dem Prinzip der [Inhaltsparität](/wiki/Article_styling_criteria/Writing#inhaltsparität) folgt. Wenn du eine Sprache fließend sprechen kannst und ein erfahrener Schriftsteller bist, greife Schlüsselthemen auf wie Artikel über die [Regeln](https://github.com/ppy/osu-wiki/tree/master/wiki/Rules) oder die [Ranking-Kriterien](https://github.com/ppy/osu-wiki/tree/master/wiki/Ranking_Criteria). Falls du noch am Anfang mit deiner Schriftstellerkarriere stehst, dann wähle einen kleinen Artikel aus, um Hilfe und Betreuung von aktiven Rezensenten zu erhalten.
```

`Kritiker` seems a little harsh.  Not a huge deal though.

2022-09-09 11:33 UTC, The-Last-Cookie commented
> Really don't like `fusioniert`. It feels way too exotic in this context.

Sure, I originally had this idea from the French wiki as they use the verb `fusionner`.

Another thing that I want to mention is that I used `Issue anlegst` instead of `Issue erstellst` in the last paragraph to have more word variety.

2022-09-09 13:25 UTC, FamousPig approved these changes

2022-09-09 14:05 UTC, merged