Create es.md
ppy/osu-wiki pull request #7957
Opened 2022-09-06 19:11 UTC by Ekkusu

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-09 19:35 UTC, agatemosu requested changes

2022-09-09 19:35 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +El **Notelock**, o **nota de bloqueo**, es un término informal para la mecánica del juego [osu!](/wiki/Game_mode/osu!), el cual puede evitar que un jugador elimine un objeto golpeado. Esto pasa si **
```suggestion
El **Notelock**, o **nota de bloqueo**, es un término informal para la mecánica del juego [osu!](/wiki/Game_mode/osu!), el cual puede evitar que un jugador elimine un objeto de golpeoo. Esto pasa si **dos** condiciones se cumplen al mismo tiempo:
```

2022-09-09 19:35 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +1. La [ventana de tiempo](/wiki/Beatmapping/Overall_difficulty#timing) de dos objetos de golpeo se superpone.
```suggestion
1. Las [ventanas de tiempo](/wiki/Beatmapping/Overall_difficulty#timing) de dos objetos de golpeo se superponen.
```

2022-09-09 19:35 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +En este caso, se dice que el segundo objeto está *bloqueado* ante el primero, lo que hace que osu! ignore los golpeos del jugador hasta que haya pasado la ventana de tiempo del primer objeto. El Note
```suggestion
En este caso, se dice que el segundo objeto está *bloqueado* ante el primero, lo que hace que osu! ignore los golpes del jugador hasta que haya pasado la ventana de golpeo del primer objeto. El Notelock solo es un problema si el jugador no puede volver al objeto anterior e interactuar con el correctamente, así se quita el bloqueo. En ese caso, una nota bloqueada puede causar un fallo en cascada, forzando al jugador a fallar más y más objetos posteriores, hasta quedar sin [salud](/wiki/Gameplay/Health) y fallar el mapa.
```

2022-09-09 19:35 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +Cuando ocurra el Notelock, el circulo golpeado se sacudirá. Esto no sucede con deslizadores o ruletas.
```suggestion
Cuando se produce el notelock, el circulo golpeado se sacudirá. Esto no sucede con deslizadores o ruletas.
```

2022-09-09 19:35 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +El notelock es parte del sistema de la ventana de tempo de osu!, y sucede cuando la ventana de tiempo de dos objetos se superpone. Esto ocurre con mayor frecuencia en mapas con valores bajos de [OD](
```suggestion
El notelock es parte del sistema de la ventana de tempo de osu!, y sucede cuando la ventana de tiempo de dos objetos se superponen. Esto ocurre con mayor frecuencia en mapas con valores bajos de [OD](/wiki/Beatmapping/Overall_difficulty) o valores altos de [BPM](/wiki/Beatmapping/Beats_per_minute), ya que en estos casos son más frecuentes la superposición en la ventana de tiempo.
```

2022-09-10 10:27 UTC, agatemosu commented on wiki/Como se Juega/Juicio/Bloqueo de notas/es.md
> +tags:
```suggestion
tags:
```

2022-09-10 10:30 UTC, agatemosu commented
You don't have to translate the file path

2022-09-11 18:58 UTC, Ekkusu commented
> You don't have to translate the file path

Not again T_T, that's a bug I don't know how to fix. Do you happen to know how to do it so you don't have to redo the code with a new push request (and close this one)?

2022-09-11 18:59 UTC, Ekkusu commented on wiki/Como se Juega/Juicio/Bloqueo de notas/es.md
> +tags:
Oh, esto es muy útil, muchas gracias

2022-09-11 19:12 UTC, Walavouchey commented
did it for you

have a look at [this part of the contribution guide](https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#applying-reviews), you can apply reviews in batches automatically from the "files changed" tab, without having to edit the file manually

2022-09-11 19:26 UTC, Ekkusu commented
> did it for you
> 
> have a look at [this part of the contribution guide](https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#applying-reviews), you can apply reviews in batches automatically from the "files changed" tab, without having to edit the file manually

Thank you very much, I'll make sure to use it next time 👍  (and prevent the file location from being changed again)

2022-09-16 17:28 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +En este caso, se dice que el segundo objeto está *bloqueado* ante el primero, lo que hace que osu! ignore los golpes del jugador hasta que haya pasado la ventana de golpeo del primer objeto. El Notel
```suggestion
En este caso, se dice que el segundo objeto está *bloqueado* ante el primero, lo que hace que osu! ignore los golpes del jugador hasta que haya pasado la ventana de golpeo del primer objeto. El Notelock solo es un problema si el jugador no puede volver al objeto anterior e interactuar con él correctamente, así se quita el bloqueo. En ese caso, una nota bloqueada puede causar un fallo en cascada, forzando al jugador a fallar más y más objetos posteriores, hasta quedar sin [salud](/wiki/Gameplay/Health) y fallar el mapa.
```

2022-09-16 17:28 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +Cuando se produce el notelock, el circulo golpeado se sacudirá. Esto no sucede con deslizadores o ruletas.
```suggestion
Cuando se produce el notelock, el círculo de golpeo se sacudirá. Esto no sucede con deslizadores o ruletas.
```

2022-09-16 17:28 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +El notelock es parte del sistema de la ventana de tempo de osu!, y sucede cuando la ventana de tiempo de dos objetos se superponen. Esto ocurre con mayor frecuencia en mapas con valores bajos de [OD]
```suggestion
El Notelock es parte del sistema de la ventana de tempo de osu!, y sucede cuando la ventana de tiempo de dos objetos se superponen. Esto ocurre con mayor frecuencia en mapas con valores bajos de [OD](/wiki/Beatmapping/Overall_difficulty) o valores altos de [BPM](/wiki/Beatmapping/Beats_per_minute), ya que en estos casos son más frecuentes la superposición en la ventana de tiempo.
```

2022-09-16 17:28 UTC, agatemosu commented on wiki/Gameplay/Judgement/Notelock/es.md
> +Dado que regularmente los objetos en los mapas de osu! están destinados a borrarse en orden cronológico, el rechazo de golpes causados por el notelock, generalmente juega un papel positivos como:
```suggestion
Dado que regularmente los objetos en los mapas de osu! están destinados a borrarse en orden cronológico, el rechazo de golpes causados por el notelock, generalmente juega un papel positivo como:
```

2022-09-17 05:32 UTC, agatemosu submitted a review, later dismissed

2022-09-19 19:33 UTC, TPGPL approved these changes

2022-09-19 19:33 UTC, merged