Add `o!BAM 2` Tournament
ppy/osu-wiki pull request #7960
Opened 2022-09-07 12:48 UTC by Laphii1206

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-09-07 14:42 UTC, fajar13k commented on wiki/Tournaments/o!BAM/2/en.md
> +The **osu! Battle Archive Malaysia 2** (***o!BAM2***) is a double-elimination 2v2 osu! tournament hosted by ::{ flag=MY }:: [LouisZpro](https://osu.ppy.sh/users/6231292) and ::{ flag=MY }:: [Tzero](h
```suggestion
The **osu! Battle Archive Malaysia 2** (***o!BAM2***) is a double-elimination 2v2 osu! tournament hosted by ::{ flag=MY }:: [LouisZpro](https://osu.ppy.sh/users/6231292) and ::{ flag=MY }:: [Tzero](https://osu.ppy.sh/users/6088976). The tournament is open to teams of two with a ::{ flag=MY }:: Malaysian player as their captain. Second player is only allowed from the ten [ASEAN member states](https://asean.org/about-asean/member-states/) (::{ flag=BN }:: Brunei Darussalam, ::{ flag=KH }:: Cambodia, ::{ flag=ID }:: Indonesia, ::{ flag=LA }:: Laos, ::{ flag=MY }:: Malaysia, ::{ flag=MM }:: Myanmar, ::{ flag=PH }:: The Philippines, ::{ flag=SG }:: Singapore, ::{ flag=TH }:: Thailand, and ::{ flag=VN }:: Vietnam) regardless of rank. Despite the change in format from its previous iterations, the tournament is formally regarded as the second instalment of the osu! Battle Archive Malaysia.
```

2022-09-07 14:42 UTC, fajar13k commented on wiki/Tournaments/o!BAM/2/en.md
> +The osu! Battle Archive Malaysia 2 was run by various community members.
```suggestion
The osu! Battle Archive Malaysia 2 is run by various community members.
```

2022-09-07 14:42 UTC, fajar13k commented on wiki/Tournaments/o!BAM/2/en.md
> +#### Qualifier
```suggestion
#### Qualifiers
```
Since you use Qualifiers in the timeline above

2022-09-07 14:42 UTC, fajar13k commented on wiki/Tournaments/o!BAM/2/en.md
> +### General
```suggestion
### General rules
```
Maybe just for consistency

2022-09-07 14:42 UTC, fajar13k commented on wiki/Tournaments/o!BAM/2/en.md
> +| Live drawings | 2022-09-20 ({22:00 UTC+8}) |
```suggestion
| Live drawings | 2022-09-20 (22:00 UTC+8) |
```

2022-09-08 01:49 UTC, TPGPL requested changes

2022-09-08 01:49 UTC, TPGPL commented on wiki/Tournaments/o!BAM/2/en.md
> +The **osu! Battle Archive Malaysia 2022** (***o!BAM2***) is a double-elimination 2v2 osu! tournament hosted by ::{ flag=MY }:: [LouisZpro](https://osu.ppy.sh/users/6231292) and ::{ flag=MY }:: [Tzero
```suggestion
The **osu! Battle Archive Malaysia 2022** (***o!BAM2***) is a double-elimination 2v2 osu! tournament hosted by ::{ flag=MY }:: [LouisZpro](https://osu.ppy.sh/users/6231292) and ::{ flag=MY }:: [Tzero](https://osu.ppy.sh/users/6088976). The tournament is open to teams of two with a ::{ flag=MY }:: Malaysian player as their captain, and the second player coming from one of the ten [ASEAN member states](https://asean.org/about-asean/member-states/) (::{ flag=BN }:: Brunei Darussalam, ::{ flag=KH }:: Cambodia, ::{ flag=ID }:: Indonesia, ::{ flag=LA }:: Laos, ::{ flag=MY }:: Malaysia, ::{ flag=MM }:: Myanmar, ::{ flag=PH }:: The Philippines, ::{ flag=SG }:: Singapore, ::{ flag=TH }:: Thailand, and ::{ flag=VN }:: Vietnam) regardless of rank. Despite the change in format from its previous iterations, the tournament is formally regarded as the second instalment of the osu! Battle Archive Malaysia.
```

2022-09-08 22:59 UTC, TPGPL approved these changes

2022-09-08 23:02 UTC, merged