Update `Featured Artist showcase beatmaps`
ppy/osu-wiki pull request #7967
Opened 2022-09-08 19:37 UTC by pishifat

manymaps

2022-09-08 22:57 UTC, TPGPL requested changes

2022-09-08 22:57 UTC, TPGPL commented on wiki/Featured_Artists/Featured_Artist_showcase_beatmaps/en.md
> +  - (![][osu!]) [Soleily feat. SUNRaiSE - Rise Above](https://osu.ppy.sh/beatmapsets/1767895#osu/3618854) hosted by ::{ flag=HU }:: [Nytrocide_](https://osu.ppy.sh/users/11327918)
```suggestion
  - (![][osu!]) [Soleily feat. SUNRaiSE - Rise Above](https://osu.ppy.sh/beatmapsets/1767895#osu/3618854) hosted by ::{ flag=HU }:: [Nytrocide\_](https://osu.ppy.sh/users/11327918)
```

2022-09-08 22:57 UTC, TPGPL commented on wiki/Featured_Artists/Featured_Artist_showcase_beatmaps/en.md
> +  - (![][osu!]) [Mitsukiyo - Kimi to Boku no Sekai (feat. *namirin)](https://osu.ppy.sh/beatmapsets/1806117#osu/3703875) hosted by ::{ flag=PH }:: [Amateurre](https://osu.ppy.sh/users/7326908)
```suggestion
  - (![][osu!]) [Mitsukiyo - Kimi to Boku no Sekai (feat. \*namirin)](https://osu.ppy.sh/beatmapsets/1806117#osu/3703875) hosted by ::{ flag=PH }:: [Amateurre](https://osu.ppy.sh/users/7326908)
```

2022-09-09 04:44 UTC, peppy approved these changes

2022-09-09 04:44 UTC, merged