Add menu tips article
ppy/osu-wiki pull request #7975
Opened 2022-09-09 21:42 UTC by Walavouchey

closes https://github.com/ppy/osu-wiki/issues/7971

not entirely sure if "menu tips" is encompassing enough but it sounds fairly ok to me, and they're mostly about menus (client navigation and shortcuts) anyway

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-09-13 11:41 UTC, TicClick commented
somehow an article full of large lists alone doesn't look right to me. I mean, I don't have anything against it (it's informative, scratches an itch, etc, etc), but it could be a few lines on the `Client` article pointing to locations of the tips as well...

while I don't have any suggestions for its core design, because well, lists, how about you add some minimal formatting (for example, `Hot`+`Key`+`Combinations`) and links to other articles where appropriate to add more value to it?

2022-09-14 04:02 UTC, peppy commented
Yeah, I'm not sure of the value provided. For stable it's probably fine because I don't foresee the tips changing, but for lazer, it might be just as beneficial to link to the code file with the tips present (so they don't have to be updated in multiple places)?

2022-09-14 12:31 UTC, Walavouchey commented
if it's about value, then the suggestions ticclick provided would be the answer. perhaps we could even add illustrative gifs for better presentability.

the reason this is put in an article in the first place is to have an accessible, searchable source of information. sure, this could be a stub article that links to the lazer source and tells people to check the stable localisation files, but then we wouldn't have much of an article.

also, it's not like the same thing would make sense for other articles with duplicate and manually updated information; much of the information on the wiki is a secondary source anyway, requiring updates as time passes (pp, medals, community articles, all other lists, etc, not to mention new info regarding lazer). the wiki is not static, at least for as long as the game and the community evolve.

2022-09-24 12:51 UTC, Walavouchey reviewed
some of these are very outdated, maybe they should be updated in-game?

2022-09-24 12:51 UTC, Walavouchey commented on wiki/Client/Menu_tips/en.md
> +- If your game or mouse feels laggy, try toggling the `Framerate Limit` in [Options](/wiki/Client/Options) or using `Fullscreen mode`/`Letterboxing`! It might just help!
nowadays called "Frame limiter"

2022-09-24 12:51 UTC, Walavouchey commented on wiki/Client/Menu_tips/en.md
> +- You can search for [specific conditions](/wiki/Client/Interface#search) at song select, like "ar>8 od=9". Supported keywords are: `ar`, `od`, `hp`, `cs`, `bpm`, `length` and `drain` (time in second
there are way more filters supported according to https://osu.ppy.sh/wiki/en/Client/Interface#search

2022-09-24 12:51 UTC, Walavouchey commented on wiki/Client/Menu_tips/en.md
> +- Timing is important! Α wrongly timed beatmap is frustrating to map and play. If you need timing assistance, post your beatmap in the Timing Help thread of the [Modding Queues forum](https://osu.ppy
what is this "Timing Help" thread

2022-09-26 14:10 UTC, TicClick requested changes
suggestions mostly

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- The fastest way to find a beatmap is to simply type part of its title/artist/creator directly into the song select screen.
has useful tips on search syntax
```suggestion
- The fastest way to find a beatmap is to simply type part of its title/artist/creator directly into the [song select screen](/wiki/Client/Interface#song-select).
```

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- Don't ignore [unranked](/wiki/Beatmap/Category) maps. If you find some you like and leave constructive comments, there is a much higher chance of them being [ranked](/wiki/Beatmap_ranking_procedure
```suggestion
- Don't ignore [unranked](/wiki/Beatmap/Category) maps. If you find some you like and leave [constructive comments](/wiki/Modding), there is a much higher chance of them being [ranked](/wiki/Beatmap_ranking_procedure)!
```

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- You can search for [specific conditions](/wiki/Client/Interface#search) at song select, like "ar>8 od=9". Supported keywords are: `ar`, `od`, `hp`, `cs`, `bpm`, `length` and `drain` (time in second
```suggestion
- You can search for [specific conditions](/wiki/Client/Interface#search) at song select, like `ar>8 od=9`. Supported keywords are: `ar`, `od`, `hp`, `cs`, `bpm`, `length` and `drain` (time in seconds).
```

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- Right-clicking on objects in the playfield or timeline will remove them. Right-clicking on an empty spot of the playfield will make the next object or any selected objects the start of a new [combo
```suggestion
- Right-clicking on objects in the playfield or [timeline](/wiki/Client/Beatmap_editor/Timelines#hit-objects) will remove them. Right-clicking on an empty spot of the playfield will make the next object or any selected objects the start of a new [combo](/wiki/Beatmapping/Combo).
```

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- Timing is important! Α wrongly timed beatmap is frustrating to map and play. If you need timing assistance, post your beatmap in the Timing Help thread of the [Modding Queues forum](https://osu.ppy
```suggestion
- Timing is important! Α wrongly timed beatmap is frustrating to map and play. If you need timing assistance, post your beatmap in the [Timing Help thread](https://osu.ppy.sh/community/forums/topics/13795) of the [Modding Queues forum](https://osu.ppy.sh/community/forums/60) or ask for a timing check in `#modreqs`.
```

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- Settings like HP drain, Circle Size, and Approach Rate can be adjusted in the `Difficulty` tab of `Song Setup` (`F4`).
may be worth it to link respective pages here (HP/CS/AR/Song setup)

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- Try reading the site's wiki, asking a question in `#modhelp`, or posting on the Beatmap Help forum if you need additional mapping information!
```suggestion
- Try reading the site's wiki, asking a question in `#modhelp`, or posting on the [Beatmap Help forum](https://osu.ppy.sh/community/forums/56) if you need additional mapping information!
```

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- When your beatmap is ready for feedback, you can upload it through the Beatmap Submission System! Look for the `Upload Beatmap` option under the `File` dropdown menu.
```suggestion
- When your beatmap is ready for feedback, you can upload it through the [Beatmap Submission System](/wiki/Beatmapping/Beatmap_submission)! Look for the `Upload Beatmap` option under the `File` dropdown menu.
```

2022-09-26 14:10 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- Check out the Featured Artist listing if you're looking for new pre-timed songs to map!
```suggestion
- Check out the [Featured Artist listing](https://osu.ppy.sh/beatmaps/artists) if you're looking for new pre-timed songs to map!
```

2022-09-26 14:11 UTC, TicClick commented on wiki/Client/Menu_tips/en.md
> +- If your game or mouse feels laggy, try toggling the `Framerate Limit` in [Options](/wiki/Client/Options) or using `Fullscreen mode`/`Letterboxing`! It might just help!
may be worth a footnote here

2022-09-26 19:57 UTC, TicClick approved these changes

2022-09-27 09:12 UTC, merged