[DE] Add `Approach_Rate`
ppy/osu-wiki pull request #7979
Opened 2022-09-10 13:13 UTC by Warpezz

(This is my first time using Github so apologies for any mistakes I've made in the whole Pull Req process)

This is a draft for the German translation of the approach rate wiki page.

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-11 11:19 UTC, The-Last-Cookie commented
Hello! Is this ready for review? There is a TODO at the end of the file.

2022-09-11 13:55 UTC, Warpezz commented
> Hello! Is this ready for review? There is a TODO at the end of the file.

yes i think it should be now

2022-09-13 20:31 UTC, The-Last-Cookie requested changes
In case you are learning German, I wanted to let you know that I really appreciate your effort. More so with wiki articles. Translation is sometimes challenging, even for me.

One thing that I noticed is that you used your `master`. Please use a feature branch for that. For information about GitHub, see [best practices § making edits](https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#making-edits)

2022-09-13 20:31 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +- AR > 5: `erscheinen = 800ms - 500ms * (AR - 5) / 5`
```suggestion
- AR > 5: `Zeitspanne zum Einblenden = 800 ms - 500 ms * (AR - 5) / 5`
```

2022-09-13 20:31 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +## Mod Beeinflussungen
```suggestion
## Mod-Effekte
```
or
```suggestion
## Effekte durch Mods
```

2022-09-13 20:31 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +- [Hard Rock](/wiki/Game_modifier/Hard_Rock): Multipliziert die AR mit 1.4 (maximal 10).
```suggestion
- [Hard Rock](/wiki/Game_modifier/Hard_Rock): Multipliziert die AR mit 1,4 (maximal 10).
```

2022-09-13 20:31 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +- [Double Time](/wiki/Game_modifier/Double_Time): Die AR wird nicht beeinflusst, aber wegen der 50% Erhöhung der Geschwindigkeit bleiben Objekte 33% weniger lange sichtbar.
```suggestion
- [Double Time](/wiki/Game_modifier/Double_Time): Die AR wird nicht beeinflusst, aber wegen der Geschwindigkeitserhöhung um 50 % bleiben Hit-Objekte 33 % weniger lange sichtbar.
```
Only a minor nitpick: [The percent sign is written with a space in this case in German](https://www.typolexikon.de/prozentzeichen/)

2022-09-13 20:31 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +- [Half Time](/wiki/Game_modifier/Half_Time): Die AR ist nicht beeinflusst, aber wegen des 25% Rückgangs der Geschwindigkeit bleiben die Objekte für eine um 33% längere Zeit sichtbar.
```suggestion
- [Half Time](/wiki/Game_modifier/Half_Time): Die AR ist nicht beeinflusst, aber wegen der Geschwindigkeitsreduzierung um 25 % bleiben Hit-Objekte für eine um 33 % längere Zeit sichtbar.
```

2022-09-13 20:31 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +Obwohl die "Half Time" und "Double Time" Mods keinen Einfluss auf das AR haben, bewirkt die Änderung der Geschwindigkeit einen offensichtlichen Unterschied in der AR. HT/DT ARs sind häufig bezeichnet
```suggestion
Obwohl die Mods "Half Time" und "Double Time" keinen Einfluss auf die AR haben, bewirkt die Änderung der Geschwindigkeit einen scheinbaren Unterschied im AR-Wert. ARs mit HT/DT werden häufig gemäß ihrer wahrgenommenen Werte bezeichnet. Zum Beispiel darf "AR8+DT" auch als "AR9.6" geschrieben werden.
```
Is a bit easier to read in my opinion.

2022-09-13 20:31 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +Approach-Rate ist sichtbar wenn die Beatmap-Informationen von [osu!taiko](/wiki/Game_mode/osu!taiko) oder [osu!mania](/wiki/Game_mode/osu!mania) angeizeigt werden, aber es hat keinen Einfluss auf das
```suggestion
Die AR ist sichtbar, wenn Beatmap-Informationen von [osu!taiko](/wiki/Game_mode/osu!taiko) oder [osu!mania](/wiki/Game_mode/osu!mania) angezeigt werden, aber es hat keinen Einfluss auf das Gameplay. Die Scrollgeschwindigkeit (Bildlaufgeschwindigkeit) in jedem Spielmodus wird durch andere Faktoren bestimmt.
```

2022-09-16 18:25 UTC, The-Last-Cookie requested changes
Every article in the wiki needs to have *one* blank line after the last paragraph. In Visual Studio Code for example, this looks like this (you can choose any editor you like though):

![line](https://user-images.githubusercontent.com/50201659/190706576-fcb8303e-086e-424b-a5c6-16a1a79ea877.JPG)

Otherwise, this article is looking good!

2022-09-16 18:25 UTC, The-Last-Cookie commented on wiki/Beatmap/Approach_rate/de.md
> +
```suggestion
```

2022-09-16 19:03 UTC, Warpezz commented
Thank you lastcookie my saviour

2022-09-17 17:07 UTC, The-Last-Cookie approved these changes

2022-09-19 01:28 UTC, TPGPL approved these changes

2022-09-19 01:30 UTC, merged