[RU] Add game modifier articles: `Double_Time`, `Easy`, `Fade_In`, `Fade_Out`, `Flashlight`
ppy/osu-wiki pull request #7994
Opened 2022-09-12 15:14 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-12 15:36 UTC, TicClick commented
буду благодарен, если кто-нибудь достанет русские описания модов из клиента (я знаю, что некоторые из них переведены)

2022-09-14 14:38 UTC, Loreos7 commented
дам ревью вечером

2022-09-14 22:29 UTC, Loreos7 requested changes

2022-09-14 22:29 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +Easy действует в [osu!mania](/wiki/Game_mode/osu!mania) почти так же, как и в osu!taiko, с той разницей, что игрок *получает* две дополнительные жизни, а скорость слайдеров и число активных клавиш не
```suggestion
Easy действует в [osu!mania](/wiki/Game_mode/osu!mania) почти так же, как и в osu!taiko, с той разницей, что игрок *получает* две дополнительные жизни, а скорость удерживаемых нот и число активных клавиш не изменяются.
```
http://pianobook.ru/2018/05/31/11-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%BE%D0%B5-%D0%BD%D0%B0%D0%B6%D0%B0%D1%82%D0%B8%D0%B5-%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D1%88-%D0%BB%D0%B5%D0%B3%D0%B0%D1%82%D0%BE-%D1%81/

2022-09-14 22:29 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +- Когда игрок расходует всё здоровье, анимация его восстановления в реплее не показывается. Вместо этого игра просто продолжается дальше, как при включённом моде [No Fail](/wiki/Game_modifier/No_Fail
Реплей -> запись ?

2022-09-14 22:29 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Fade_In/ru.md
> +*Эта статья — про мод, снижающий область видимости. О моде, убирающем круги вокруг нот, см. [Hidden (мод)](/wiki/Game_modifier/Hidden). О моде, затемняющем игровое поле, см. [Flashlight (мод)](/wiki/
```suggestion
*Эта статья — про мод, снижающий область видимости. О моде, убирающем вспомогательные окружности, см. [Hidden (мод)](/wiki/Game_modifier/Hidden). О моде, затемняющем игровое поле, см. [Flashlight (мод)](/wiki/Game_modifier/Flashlight).*
```

2022-09-14 22:29 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Fade_Out/ru.md
> +**Fade Out** (рус. *постепенное пропадание*) — ранее доступный [игровой модификатор](/wiki/Game_modifier) в [osu!mania](/wiki/Game_mode/osu!mania), отчасти похожий на мод [Fade In](/wiki/Game_modifie
```suggestion
**Fade Out** (рус. *постепенное исчезновение*) — ранее доступный [игровой модификатор](/wiki/Game_modifier) в [osu!mania](/wiki/Game_mode/osu!mania), отчасти похожий на мод [Fade In](/wiki/Game_modifier/Fade_In). При включении Fade Out ноты постепенно *пропадали* перед нажатием. Позднее этот мод был заменен на [Hidden](/wiki/Game_modifier/Hidden).
```

2022-09-14 22:29 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Flashlight/ru.md
> +- Описание: `Restricted view area`
```suggestion
- Описание: `Игровое поле погружается во тьму`
```

2022-09-14 22:29 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Flashlight/ru.md
> +Flashlight считается многими самым сложным модом в osu!: чтобы поставить на карте рекорд, её нужно сначала полностью запомнить.
```suggestion
Flashlight считается многими самым сложным модом в osu!: чтобы поставить на карте рекорд, её нужно сначала выучить.
```

2022-09-15 11:11 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Double_Time/ru.md
> +Включение Double Time в [osu!taiko](/wiki/Game_mode/osu!taiko) значительно усложняет игру из-за её высоких требований к точности, а также из-за слайдертиков, расположенных на барабанных дробях. Таким
во-первых, то, что игра усложняет игру, это плохо. во-вторых, смысл оригинала не в том, что Double Time увеличивает требования к точности, а в том, что в тайко и так сложно играть из-за других hit window. например, при OD=5 в стандарте ширина окна 50 мс, а в тайко — уже 35 (это примерно как стандарт с OD=8): https://osu.ppy.sh/wiki/en/Beatmap/Overall_difficulty

2022-09-15 11:11 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +Easy действует в [osu!mania](/wiki/Game_mode/osu!mania) почти так же, как и в osu!taiko, с той разницей, что игрок *получает* две дополнительные жизни, а скорость слайдеров и число активных клавиш не
мимо:
- https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Game_modifier/Easy/en.md?plain=1#L66
- https://osu.ppy.sh/wiki/en/Gameplay/Hit_object/Slider/Slider_velocity

2022-09-15 11:11 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +В [osu!](/wiki/Game_mode/osu!) при включении Easy вдвое снижаются [размер кругов (CS)](/wiki/Client/Beatmap_editor/Song_Setup#circle-size), [скорость появления нот (AR)](/wiki/Beatmapping/Approach_ra
пока не могу согласиться, мне кажется, что с расходом вариант лучше. @UristMcKobold?

2022-09-15 11:11 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +- Когда игрок расходует всё здоровье, анимация его восстановления в реплее не показывается. Вместо этого игра просто продолжается дальше, как при включённом моде [No Fail](/wiki/Game_modifier/No_Fail
по-моему, у нас так нигде не переведено (по крайней мере, пока), так что оставлю на лучшие времена

2022-09-15 11:11 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Fade_In/ru.md
> +*Эта статья — про мод, снижающий область видимости. О моде, убирающем круги вокруг нот, см. [Hidden (мод)](/wiki/Game_modifier/Hidden). О моде, затемняющем игровое поле, см. [Flashlight (мод)](/wiki/
[мне лично было бы] вообще непонятно, что за окружности такие. другое дело, что моя формулировка тоже не фонтан, но ей я больше симпатизирую (и не потому, что сам её придумал)

2022-09-15 15:11 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +- Когда игрок расходует всё здоровье, анимация его восстановления в реплее не показывается. Вместо этого игра просто продолжается дальше, как при включённом моде [No Fail](/wiki/Game_modifier/No_Fail
![image](https://user-images.githubusercontent.com/86934170/190440782-52e78d15-3f6e-437b-b998-037b38c91045.png)
![image](https://user-images.githubusercontent.com/86934170/190440832-a0550a08-7dac-4f50-80a8-b0ec563d7269.png)

2022-09-15 15:13 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +В [osu!](/wiki/Game_mode/osu!) при включении Easy вдвое снижаются [размер кругов (CS)](/wiki/Client/Beatmap_editor/Song_Setup#circle-size), [скорость появления нот (AR)](/wiki/Beatmapping/Approach_ra
![image](https://user-images.githubusercontent.com/86934170/190441156-97a4e459-5802-4544-9756-c959ac2661d4.png)

2022-09-15 15:15 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Fade_In/ru.md
> +*Эта статья — про мод, снижающий область видимости. О моде, убирающем круги вокруг нот, см. [Hidden (мод)](/wiki/Game_modifier/Hidden). О моде, затемняющем игровое поле, см. [Flashlight (мод)](/wiki/
А мне кажется довольно интуитивно полагать, что вспомогательные окружности - те, что помогают что-то сделать. Нажать ноту - единственный вывод из контекста игры

2022-09-15 15:25 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Fade_In/ru.md
> +*Эта статья — про мод, снижающий область видимости. О моде, убирающем круги вокруг нот, см. [Hidden (мод)](/wiki/Game_modifier/Hidden). О моде, затемняющем игровое поле, см. [Flashlight (мод)](/wiki/
если ты видишь скриншот перед глазами (или играешь), да, возможно. из контекста примечания в статье (а не самой игры) ничего про природу аппроачей не следует

касательно круга и окружности: я знаю разницу, но в обиходе её выделяют только там, где она имеет значение. если уж придираться, то это кольца, потому как у них есть вполне конкретная толщина (чего нет у окружности)

2022-09-15 15:30 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +В [osu!](/wiki/Game_mode/osu!) при включении Easy вдвое снижаются [размер кругов (CS)](/wiki/Client/Beatmap_editor/Song_Setup#circle-size), [скорость появления нот (AR)](/wiki/Beatmapping/Approach_ra
точность — это overall difficulty, которая на самом деле ещё и на спиннеры влияет?

2022-09-17 09:10 UTC, Moltanicaa commented on wiki/Gameplay/Game_modifier/Double_Time/ru.md
> +- Описание: `ВЖЖЖЖЖЖЖЖЖЖЖ`
А не планируется ли вообще каким-либо образом изменять вот это вот недоразумение с описанием мода на русском?

2022-09-17 09:13 UTC, Moltanicaa commented on wiki/Gameplay/Game_modifier/Double_Time/ru.md
> +- Название "Double Time" является фактически неверным, поскольку скорость песни увеличивается не в два раза (200%), а лишь в полтора (150%).
Насколько я понимаю, это статья для стейбла, но здесь можно было бы добавить, что в osu!lazer можно изменить скорость ускорения на 200%

2022-09-17 09:14 UTC, Moltanicaa commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +  - ![][osu!mania]: `Упрощает игру. Ноты менее требовательны к точности, а HP тратится медленней.`
МедленнеЕ*

2022-09-17 09:26 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Double_Time/ru.md
> +- Описание: `ВЖЖЖЖЖЖЖЖЖЖЖ`
> 
Пока существует стейбл, то и прикреплять перевод нужно оттуда. С выходом лазера перепишем

2022-09-17 09:27 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +  - ![][osu!mania]: `Упрощает игру. Ноты менее требовательны к точности, а HP тратится медленней.`
> 

![image](https://user-images.githubusercontent.com/86934170/190849981-f8d785b7-d7d0-4c46-a35e-7f0773864005.png)

2022-09-18 16:26 UTC, MegaMixYT requested changes

2022-09-18 16:49 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Autopilot/ru.md
>  - Описание: `Курсор двигается сам, просто следуйте ритму. **НЕ НА РАНК**`
> 

![image](https://user-images.githubusercontent.com/86934170/190918709-3a8b68f4-87c1-45db-9de5-e06db5bb9629.png)

2022-09-19 14:11 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Double_Time/ru.md
> +- Название "Double Time" является фактически неверным, поскольку скорость песни увеличивается не в два раза (200%), а лишь в полтора (150%).
звучит как работа для редактора оригинальной статьи!

2022-09-19 14:39 UTC, UristMcKobold commented on wiki/Gameplay/Game_modifier/Easy/ru.md
> +В [osu!](/wiki/Game_mode/osu!) при включении Easy вдвое снижаются [размер кругов (CS)](/wiki/Client/Beatmap_editor/Song_Setup#circle-size), [скорость появления нот (AR)](/wiki/Beatmapping/Approach_ra
«расход» звучит более формально, но «потеря» имеет больший смысл, так как ты не расходуешь ХП на что-либо, а теряешь его, когда плохо играешь.

2022-09-19 14:42 UTC, UristMcKobold commented on wiki/Gameplay/Game_modifier/Fade_In/ru.md
> +*Эта статья — про мод, снижающий область видимости. О моде, убирающем круги вокруг нот, см. [Hidden (мод)](/wiki/Game_modifier/Hidden). О моде, затемняющем игровое поле, см. [Flashlight (мод)](/wiki/
Я тоже не очень понимаю «вспомогательные окружности», очень замудренная лексика для гайда по осу. Когда я объясняю, всегда говорю «круги», проблем не возникало.

2022-09-19 15:06 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Fade_In/ru.md
> +*Эта статья — про мод, снижающий область видимости. О моде, убирающем круги вокруг нот, см. [Hidden (мод)](/wiki/Game_modifier/Hidden). О моде, затемняющем игровое поле, см. [Flashlight (мод)](/wiki/
Имхо, на мой взгляд примитивно, но для статьи пусть будет так, хорошо.

2022-09-24 02:31 UTC, Walavouchey approved these changes

2022-09-24 02:35 UTC, merged