[RU] Update `Medals` article translation
ppy/osu-wiki pull request #8000
Opened 2022-09-14 16:51 UTC by MegaMixYT

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-14 17:01 UTC, Pisapou commented on wiki/Medals/ru.md
>  ---
```suggestion
```

2022-09-14 17:01 UTC, Pisapou commented on wiki/Medals/ru.md
>  ---
```suggestion
```

2022-09-14 17:01 UTC, Pisapou commented on wiki/Medals/ru.md
>  no_native_review: true
```suggestion
```

2022-09-14 17:01 UTC, Pisapou commented on wiki/Medals/ru.md
```suggestion
```

2022-09-14 17:04 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали группы **Beatmap Packs** могут быть получены за **прохождение до конца хотя бы одной из сложностей на каждой карте** из [Тематических Сборок](https://osu.ppy.sh/beatmaps/packs?type=theme) или
```suggestion
Медали группы **Beatmap Packs** могут быть получены за **прохождение до конца хотя бы одной из сложностей на каждой карте** из [Тематических Сборок](https://osu.ppy.sh/beatmaps/packs?type=theme) или [Сборок Исполнителей/Альбомов](https://osu.ppy.sh/beatmaps/packs?type=artist).
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали, ранее известные как *достижения*, — значки в профиле игрока, показывающие, что пользователь достиг необычной цели. В данный момент, существует 280 медалей для получения, разделённых на 8 груп
```suggestion
**Медали**, ранее известные как *достижения*, — значки в профиле игрока, показывающие, что пользователь достиг необычной цели. В данный момент, существует **280** медалей для получения, разделённых на 8 групп: [Beatmap Packs](#beatmap-packs), [Skill](#skill), [Dedication](#dedication), [Mod Introduction](#mod-introduction), [Hush-Hush](#hush-hush), [Beatmap Spotlights](#beatmap-spotlights), [Seasonal Spotlights](#seasonal-spotlights), и [Beatmap Challenge Packs](#beatmap-challenge-packs).
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали группы **Beatmap Packs** могут быть получены за **прохождение до конца хотя бы одной из сложностей на каждой карте** из [Тематических Сборок](https://osu.ppy.sh/beatmaps/packs?type=theme) или
Don't seems to be exactly same as english (`These medals can be obtained by clearing every beatmap all the way through at least once in any difficulty within the corresponding beatmap pack.` removed ?). You have to stay as much as you can close to the en.md

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Все карты должны быть пройдены в режиме игры [osu!](/wiki/Game_mode/osu!) для получения значка, если не указано обратное. Использование [упрощающих модов](/wiki/Game_modifier#difficulty-reduction) ил
```suggestion
Все карты должны быть пройдены в режиме игры [osu!](/wiki/Game_mode/osu!) для получения значка, если не указано обратное. Использование [понижение сложности](/wiki/Game_modifier#difficulty-reduction) или [повышение сложности](/wiki/Game_modifier#difficulty-increase), как и использование [Spun Out](/wiki/Game_modifier/Spun_Out) разрешено.
```

-> refering to `https://osu.ppy.sh/wiki/ru/Gameplay/Game_modifier`

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали группы **Mod Introduction** могут быть получены за прохождение любой [Квалифицированной](/wiki/Beatmap/Category#qualified), [Рейтинговой](/wiki/Beatmap/Category#ranked) или [Одобренной](/wiki/
```suggestion
Медали группы **Mod Introduction** могут быть получены за прохождение любой [Qualified](/wiki/Beatmap/Category#qualified), [Ranked](/wiki/Beatmap/Category#ranked) или [Approved](/wiki/Beatmap/Category#approved) карты с их соответствующим [игровой модификатор (модом)](/wiki/Game_modifier). Эти медали направлены на то, чтобы стимулировать новых игроков попробовать каждый мод и изучить что может предложить игра. Однако, стоит заметить что если игрок будет играть с несколькими модами одновременно, игрок **не** сможет получить *какую-либо* из медалей группы **Mod Introductions** за эту игру.
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Все медали группы **Mod Introduction** могут быть разблокированы в любом [игровом режиме](/wiki/Game_mode) если не указано обратное.
```suggestion
Все медали группы Mod Introduction могут быть разблокированы в любом [режимы игры](/wiki/Game_mode) если не указано обратное.
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали данного типа являются "секретными", присуждаясь за выполнение очень специфичных действий, о которых игроку не сообщают напрямую (отсюда и название). Эти шаги могут быть чем угодно, от прохожде
```suggestion
**Hush-Hush mедали** являются "секретными", присуждаясь за выполнение очень специфичных действий, о которых игроку не сообщают напрямую (отсюда и название). Эти шаги могут быть чем угодно, от прохождения карты при особых условиях до получения скора с необычной комбинацией модов. Несмотря на их скрытный характер, есть подсказки, которые помогут всем любопытным охотникам за медалями в их достижении:
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +- "*Флаерные текста*"<!-- https://twitter.com/ephemeralis/status/1068054191602638850 --> медалей (если присутствуют), которые можно посмотреть, наведя на соответствующие карточки.
```suggestion
- *Флаерные текста*<!-- https://twitter.com/ephemeralis/status/1068054191602638850 --> медалей (если присутствуют), которые можно посмотреть, наведя на соответствующие карточки.
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +- [Упрощающие моды](/wiki/Game_modifier#difficulty-reduction)
```suggestion
- [понижение сложности](/wiki/Game_modifier#difficulty-reduction)
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +- [Усложняющие моды](/wiki/Game_modifier#difficulty-increase)
```suggestion
- [повышение сложности](/wiki/Game_modifier#difficulty-increase)
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали группы **Seasonal Spotlights medals** выдаются за прохождение определённых паков карт выпущенных как часть [Seasonal Spotlights](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summ
```suggestion
Медали группы **Seasonal Spotlights** выдаются за прохождение определённых паков карт выпущенных как часть [Seasonal Spotlights](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018). Чтобы разблокировать медали в этой категории, игроку нужно поиграть во все карты *в любом из четырёх паков режимов игры* в соответствующем Seasonal Spotlights чарте. Следующие моды разрешены для использования:
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +- [Упрощающие моды](/wiki/Game_modifier#difficulty-reduction)
```suggestion
- [понижение сложности](/wiki/Game_modifier#difficulty-reduction)
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +- [Усложняющие моды](/wiki/Game_modifier#difficulty-increase)
```suggestion
- [повышение сложности](/wiki/Game_modifier#difficulty-increase)
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали группы **Beatmap Challenge Packs**, или альтернативно группа [*Skill Packs*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers-guild#skill-packs) выдаютс
```suggestion
Медали группы **Beatmap Challenge Packs**, или альтернативно группа [*Skill Packs*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers-guild#skill-packs) выдаются за прохождение самых высоких сложностей существующих во всех картах представленных в определённых [Theme Beatmap Packs](https://osu.ppy.sh/beatmaps/packs?type=theme) или Artist/Album Beatmap Packs](https://osu.ppy.sh/beatmaps/packs?type=artist) *без использования каких либо [понижение сложности](/wiki/Game_modifier#difficulty-reduction) или [oсобые моды](/wiki/Game_modifier#special) модов*. Эти сборки карт специально подобраны для теста понимания каждым игроком различных игровых аспектов на определённом уровне навыков, например в рамках определённого [star rating](/wiki/Beatmapping/Star_rating) или предела сложности.
```

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +Медали группы **Skill** присуждаются за достижения, основанные на различных навыках, будь это получение определённого [комбо](/wiki/Beatmapping/Combo), достижение определённого ранга в [глобальной та
```suggestion
Медали группы **Skill** присуждаются за достижения, основанные на различных навыках, будь это получение определённого [combo](/wiki/Beatmapping/Combo), достижение определённого ранга в [глобальной таблице лидеров по очкам производительности](https://osu.ppy.sh/rankings/osu/performance), прохождение или [full combo](/wiki/Gameplay/Full_combo) на любой [Qualified](/wiki/Beatmap/Category#qualified), [Ranked](/wiki/Beatmap/Category#ranked) или [Approved](/wiki/Beatmap/Category#approved) карте в определённом диапазоне [star rating](/wiki/Beatmapping/Star_rating).
```
-> refering to (https://osu.ppy.sh/wiki/ru/Beatmap/Category), categories don't seems to be translated.
    -> also technical stuff like combo / full combo / star rating don't have to be translated (i guess ? see french translation)

2022-09-14 17:53 UTC, Pisapou commented on wiki/Medals/ru.md
> +*См. также: [Модификатор игры](/wiki/Game_modifier)*
```suggestion
*См. также: [игровой модификатор](/wiki/Game_modifier)*
```

2022-09-14 23:07 UTC, MegaMixYT commented
Uhh, just did something related to reviewers and I'm not sure what exactly 😥

2022-09-19 19:32 UTC, TicClick commented
running slightly behind my schedules, will take a look in a day or two -- please bear with me

2022-09-23 17:01 UTC, TicClick requested changes
в начале вроде было неплохо, но потом посредственно. тебе нужно сделать упор на короткие, ёмкие предложения (при этом по-прежнему полные, а не обрубленные — это важно). перевод должен читаться естественно, как будто бы его написал настоящий, живой человек — ты же ведь для этого переводишь?

2022-09-23 17:01 UTC, TicClick commented on wiki/Medals/Unlock_requirements/Beatmap_challenge_packs/ru.md
> +| Camellia II | Пройти все карты укомплектованные в сборку карт [Camellia Challenges Pack](https://osu.ppy.sh/beatmaps/packs/2053). Все карты в этой сборке имеют самую высокую сложность классифициров
```suggestion
| Camellia II | Пройти все карты из подборки [Camellia Challenges Pack](https://osu.ppy.sh/beatmaps/packs/2053). У каждой карты оттуда есть наивысшая сложность уровня `Expert` или выше. |
```

2022-09-23 17:16 UTC, minusQuantumNeko commented on wiki/Medals/ru.md
> +Медали группы **Beatmap Packs** могут быть получены за **прохождение до конца хотя бы одной из сложностей на каждой карте** из [Тематических Сборок](https://osu.ppy.sh/beatmaps/packs?type=theme) или
@TicClick Артист это всё же немножко другое, поэтому я бы всё таки использовал слово "исполнитель"!

```suggestion
Медали группы **Beatmap Packs** могут быть получены за **прохождение до конца хотя бы одной сложности на каждой карте** в подборках по [определённой тематике](https://osu.ppy.sh/beatmaps/packs?type=theme) или конкретному [исполнителю или альбому](https://osu.ppy.sh/beatmaps/packs?type=artist).
```

2022-09-23 17:20 UTC, TicClick commented on wiki/Medals/ru.md
> +Медали группы **Beatmap Packs** могут быть получены за **прохождение до конца хотя бы одной из сложностей на каждой карте** из [Тематических Сборок](https://osu.ppy.sh/beatmaps/packs?type=theme) или
да, ты всё правильно говоришь, я задумался просто. исполнитель, конечно.

2022-09-23 17:52 UTC, minusQuantumNeko commented on wiki/Medals/ru.md
> +Медали группы **Skill** присуждаются за достижения, основанные на различных навыках, будь это получение определённого [комбо](/wiki/Beatmapping/Combo), достижение определённого ранга в [глобальной та
Согласен, "число звёзд" звучит намного приятнее

2022-09-23 18:10 UTC, minusQuantumNeko commented on wiki/Medals/ru.md
> +*См. также: [Модификатор игры](/wiki/Game_modifier)*
@TicClick Я считаю что лучше использовать одинаковый перевод с тем что находиться на данной странице вики, поэтому предлагаю сделать так:

```suggestion
*См. также: [Игровой модификатор](/wiki/Game_modifier)*
```

2022-09-23 19:26 UTC, TicClick approved these changes
for future PRs, please 1) make a separate branch for every translation, and b) batch your commits where possible, while keeping their descriptions meaningful instead of `Update ru.m`: https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#making-edits

2022-09-23 19:26 UTC, merged