[UK] Update `BBCode`
ppy/osu-wiki pull request #8008
Opened 2022-09-15 08:48 UTC by Aniterin

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-15 15:05 UTC, Pisapou commented on wiki/BBCode/uk.md
> +
```suggestion
```

2022-09-15 15:05 UTC, Pisapou commented on wiki/BBCode/uk.md
> +Якщо було вказано тільки ID користувача, то треба вписати текст між тегами, він не буде відображений, замість нього буде відображено ім'я користувача. Якщо ви вкажете ім'я користувача, то після зміни
```suggestion
Якщо було вказано тільки ID користувача, то треба вписати текст між тегами, він не буде відображений, замість нього буде відображено ім'я користувача. Якщо ви вкажете ім'я користувача, то після зміни ім'я посилання перестає працювати.
```

2022-09-15 15:05 UTC, Pisapou commented on wiki/BBCode/uk.md
> +Тег `[list]` використовується для вставки одного із двох типів списків по всьому сайту, використовуючи (`[*]`) ви створюєте новий елемент в списку. По замовчуванню це створить простий дотований текст
```suggestion
Тег `[list]` використовується для вставки одного із двох типів списків по всьому сайту, використовуючи (`[*]`) ви створюєте новий елемент в списку (показано вище). По замовчуванню це створить простий дотований текст.
```

2022-09-15 15:05 UTC, Pisapou commented on wiki/BBCode/uk.md
> +Якщо `TYPE` вказаний(не важливо що саме ви напишете), буде створено нумарований список.
```suggestion
Якщо `TYPE` вказаний (не важливо що саме ви напишете), буде створено нумарований список.
```

2022-09-18 15:01 UTC, MegaMixYT requested changes

2022-09-24 12:36 UTC, Walavouchey approved these changes
i approve

2022-09-24 12:38 UTC, merged