[RU] Add `osu! wiki/Maintenance` and `List of maintainers`
ppy/osu-wiki pull request #8012
Opened 2022-09-15 10:59 UTC by TicClick

the original page needs updates and some reshuffling but I wanted to get the translation out first

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-17 10:01 UTC, Loreos7 requested changes

2022-09-19 14:05 UTC, TicClick commented on wiki/osu!_wiki/Maintenance/ru.md
> +- `needs native review`: перевод должен проверить человек, хорошо знающий язык (этот тег также ставится на переводы, влитые без подобного ревью);
«были применены» тут криво звучит, «были добавлены» тогда уж
но вообще, этот пункт будет потом удалён, так что разницы нет

2022-09-19 14:05 UTC, TicClick commented on wiki/osu!_wiki/Maintenance/ru.md
> +Помните, что новые перенаправления должны быть а) краткими и б) пригодными к быстрому использованию.
да можно и без них

2022-09-19 14:08 UTC, TicClick commented on wiki/osu!_wiki/Maintenance/ru.md
> +Если вам нужна помощь в расшифровке автоматически найденных ошибок, обращайтесь на канал `#osu-wiki`.
применю, но вообще принято и так, и так про чат-каналы говорить, насколько я знаю

2022-09-19 14:10 UTC, TicClick commented on wiki/osu!_wiki/Maintenance/ru.md
> +Перевод могут влить и без ревью, если за две недели его никто не проверил.
выбрал «добавить»

2022-09-24 02:30 UTC, Walavouchey approved these changes

2022-09-24 02:31 UTC, merged