[FR] Update `BBCode`
ppy/osu-wiki pull request #8021
Opened 2022-09-18 08:23 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-18 08:25 UTC, Pisapou commented
Sorry, the commit is nammed `update skinning osu` but it is an update of `BBCode`. Don't know what went through my head

2022-09-24 16:35 UTC, Biokax requested changes

2022-09-24 16:35 UTC, Biokax commented on wiki/BBCode/fr.md
> +Lorsque vous spécifiez des utilisateurs par le biais de leur identifiant, un texte de remplacement est nécessaire entre les balises ouverte et fermée. En procédant ainsi, le nom de l'utilisateur s'af
```suggestion
Lorsque vous spécifiez des utilisateurs par le biais de leur identifiant, un texte de remplacement est nécessaire entre les balises ouvertes et fermées. En procédant ainsi, le nom de l'utilisateur s'affichera sur la page actuelle à la place du texte de remplacement. Lorsque vous spécifiez des utilisateurs uniquement par leur nom d'utilisateur, le lien ne fonctionnera plus s'ils changent leur nom d'utilisateur.
```

2022-09-24 18:59 UTC, Biokax approved these changes

2022-09-26 20:02 UTC, TicClick approved these changes

2022-09-26 20:04 UTC, merged