[DE] Add `Rules/Contributor_Code_of_Conduct`
ppy/osu-wiki pull request #8028
Opened 2022-09-19 15:39 UTC by The-Last-Cookie

## Translation notes

- `community leader` --> `Führungspersönlichkeit` or `Community-Leiter`
- Not sure how the last two external links should be written (i.e. `Contributor Covenant` and `Mozillas code of conduct enforcement ladder`)

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-22 15:46 UTC, The-Last-Cookie commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +Führungspersönlichkeiten der Community werden sich an diese Richtlinien für die Auswirkungen auf die Community richten, um die Konsequenzen jedes Handelns zu bestimmen, das sie als Verstoß gegen dies
```suggestion
Die Führungspersönlichkeiten der Community werden sich an diese Richtlinien für die Auswirkungen auf die Community richten, um die Konsequenzen jedes Handelns zu bestimmen, das sie als Verstoß gegen diesen Verhaltenskodex ansehen:
```

2022-09-22 15:46 UTC, The-Last-Cookie commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +## Zuschreibung
Alternatives:
- Nennung
- Erwähnung
- Danksagung
- Quellen
- `osu!stream` article uses just *Credits*

I'm open to other translations.

2022-09-28 13:44 UTC, The-Last-Cookie commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +Wir als Mitglieder, Mitwirkende und Führungskräfte versprechen, die Teilnahme an unserer Community für jeden eine Erfahrung ohne Belästigung zu machen, unabhängig des Alters, der Körpergröße, von sic
```suggestion
Wir als Mitglieder, Mitwirkende und Führungskräfte versprechen, die Teilnahme an unserer Community für jeden eine Erfahrung ohne Belästigung zu machen, unabhängig des Alters, der Körpergröße, von sichtbaren oder unsichtbaren Behinderungen, der ethnischen Herkunft, der Geschlechtsmerkmale, der Geschlechtsidentität und des Ausdrucks, des Erfahrungsniveaus, des Bildungsstandes, des sozioökonomischen Status, der Nationalität, des persönlichen Aussehens, der Rasse, der Religion oder der sexuellen Identität und Orientierung.
```

2022-09-28 13:44 UTC, The-Last-Cookie commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +- private Informationen von anderen veröffentlichen, wie zum Beispiel eine physische oder E-Mail-Adresse, ohne das explizite Einverständnis der Person
```suggestion
- private Informationen von anderen veröffentlichen, wie zum Beispiel eine physische oder eine E-Mail-Adresse, ohne das explizite Einverständnis der Person
```

2022-09-28 13:44 UTC, The-Last-Cookie commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +## Zuschreibung
```suggestion
## Quellen
```

2022-09-28 13:44 UTC, The-Last-Cookie commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +Die Richtlinien für die Auswirkungen auf die Community sind aus [Mozillas code of conduct enforcement ladder](https://github.com/mozilla/diversity) inspiriert.
```suggestion
Die Richtlinien für die Auswirkungen auf die Community sind aus [Mozillas Verhaltenskodex (Englisch)](https://github.com/mozilla/diversity) inspiriert.
```

2022-10-01 14:11 UTC, FamousPig requested changes

2022-10-01 14:11 UTC, FamousPig commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +**Konsequenz**: Eine Warnung mit Konsequenzen für anhaltendes Verhalten. Keine Interaktion für einen bestimmten Zeitraum mit den involvierten Personen, einschließlich unaufgeforderte Interaktionen mi
```suggestion
**Konsequenz**: Eine Warnung mit Konsequenzen für anhaltendes Verhalten. Keine Interaktion für einen bestimmten Zeitraum mit den involvierten Personen, einschließlich unaufgeforderter Interaktionen mit denen, die den Verhaltenskodex durchsetzen. Das beinhaltet die Vermeidung von Interaktionen an Community-Orten sowie in externen Kanälen wie Social-Media. Ein Verstoß gegen diese Bedingungen kann zu einer vorübergehenden oder dauerhaften Sperre führen.
```

2022-10-01 14:11 UTC, FamousPig commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +**Auswirkungen auf die Community**: Das Vormachen von Verstößen gegen die Community-Standards, einschließlich anhaltend unangemessenes Verhalten, Belästigung von Einzelpersonen oder Aggression oder H
```suggestion
**Auswirkungen auf die Community**: Das Vormachen von anhaltenden Verstößen gegen die Community-Standards, einschließlich anhaltend unangemessenem Verhalten, Belästigung von Einzelpersonen oder Aggression oder Herabwürdigung gegen Personengruppen.
```

2022-10-01 14:11 UTC, FamousPig commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +Dieser Verhaltenskodex wurde aus dem [Contributor Covenant](https://www.contributor-covenant.org) adaptiert, verfügbar unter <https://www.contributor-covenant.org/version/2/0/code_of_conduct.html>.
```suggestion
Dieser Verhaltenskodex wurde aus der [Vereinbarung über den Verhaltenskodex für Mitwirkende](https://www.contributor-covenant.org) adaptiert, verfügbar unter <https://www.contributor-covenant.org/de/version/2/0/code_of_conduct>.
```

Might as well link the official translation imo
https://www.contributor-covenant.org/de/version/2/0/code_of_conduct

2022-10-01 14:11 UTC, FamousPig commented on wiki/Rules/Contributor_Code_of_Conduct/de.md
> +Für Antworten auf häufige Fragen über den Verhaltenskodex, siehe das FAQ unter <https://www.contributor-covenant.org/faq>. Übersetzungen sind erhältlich unter <https://www.contributor-covenant.org/tr
```suggestion
Für Antworten auf häufige Fragen über den Verhaltenskodex, siehe das FAQ unter <https://www.contributor-covenant.org/faq>. Andere Übersetzungen sind erhältlich unter <https://www.contributor-covenant.org/translations>.
```

In line with above suggestion

2022-10-03 13:37 UTC, FamousPig approved these changes

2022-10-03 16:29 UTC, TicClick approved these changes

2022-10-03 16:38 UTC, merged