[VN] Add `Registration`
ppy/osu-wiki pull request #8035
Opened 2022-09-20 05:29 UTC by ltln

There are some phrases that are not translated in-game so I keep it original.

## Self-check

- [x ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-20 13:44 UTC, TranT3011 requested changes

2022-09-20 13:44 UTC, TranT3011 commented on wiki/Registration/vi.md
> +   - Về ô username, bạn có thể đặt username tối đa 15 ký tự; bao gồm các ký tự (`a-z`, `A-Z`, `0-9`), gạch dưới (`_`), ngoặc vuông, (`[` and `]`), gạch ngang (`-`), và dấu cách (` `).
```suggestion
   - Về ô username, bạn có thể đặt tối đa 15 ký tự; bao gồm các ký tự (`a-z`, `A-Z`, `0-9`), gạch dưới (`_`), ngoặc vuông, (`[` and `]`), gạch ngang (`-`), và dấu cách (` `)
```
repeating the word sounds weird to me

2022-09-20 13:44 UTC, TranT3011 commented on wiki/Registration/vi.md
> +   - Về ô password, hãy dùng mật khẩu dài ít nhất 8 ký tự.
```suggestion
   - Về ô password, hãy đặt ít nhất 8 ký tự.
```
make it sound more natrual

2022-09-20 13:44 UTC, TranT3011 commented on wiki/Registration/vi.md
> +Đừng quên đọc thật thật là kỹ [nội quy](/wiki/Rules)!
```suggestion
Đừng quên đọc [nội quy](/wiki/Rules) thật là kỹ !
```
same as 12

2022-09-20 14:49 UTC, TranT3011 submitted a review, later dismissed
im vnese (https://osu.ppy.sh/users/19233714)
the translation is good
dont know how to make this approval sound better lol

2022-09-21 04:44 UTC, TranT3011 approved these changes
a

2022-09-21 15:24 UTC, TPGPL approved these changes

2022-09-21 15:24 UTC, merged