Add `GBC 2022 Autumn` tournament page
ppy/osu-wiki pull request #8036
Opened 2022-09-21 02:41 UTC by RushFTK

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-09-21 03:09 UTC, RushFTK commented
All CI fix commit could be rebase into ones. thanks for help.

2022-09-21 15:30 UTC, TPGPL requested changes

2022-09-21 15:30 UTC, TPGPL commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +*this might change depending on the number of incoming registrations.*
```suggestion
*The schedule might change depending on the number of incoming registrations.*
```

2022-09-21 15:30 UTC, TPGPL commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| :-----: | :----- |
```suggestion
| :-: | :-- |
```

2022-09-21 15:30 UTC, TPGPL commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| 5-8th place | *TBA* CNY |
```suggestion
| *4th place* | *TBA* CNY |
| *5-8th place* | *TBA* CNY |
```

2022-09-22 01:14 UTC, TPGPL approved these changes

2022-09-22 01:18 UTC, merged