[DE] Add `Community/User_title`
ppy/osu-wiki pull request #8042
Opened 2022-09-23 12:11 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-28 13:56 UTC, The-Last-Cookie commented on wiki/Community/User_title/de.md
> +Diese Titel waren nur auf der Seitenleiste in Forenbeiträgen sichtbar (nicht auf dem Profil der Nutzer) und wurden nicht angezeigt, wenn ein anderer benutzerdefinierter Titel bereits eingestellt war.
```suggestion
Diese Titel waren nur auf der Seitenleiste in Forenbeiträgen sichtbar (nicht auf dem Profil des Nutzers) und wurden nicht angezeigt, wenn ein anderer benutzerdefinierter Titel bereits eingestellt war.
```

2022-10-01 14:41 UTC, FamousPig requested changes

2022-10-01 14:41 UTC, FamousPig commented on wiki/Community/User_title/de.md
> +Die Farbe des Nutzertitels ist dieselbe wie die Farbe des Nutzers, die in der Regel ebenfalls durch die Gruppenmitgliedschaft festgelegt wird. Wenn der Nutzer keine Farbe eingestellt hat, ist der Tit
```suggestion
Die Farbe des Nutzertitels ist dieselbe wie die Farbe des Nutzers, die in der Regel ebenfalls durch die Gruppenmitgliedschaft festgelegt wird. Wenn für den Nutzer keine Farbe festgelegt ist, ist der Titel weiß.
```
Don't think users get to set the color themselves.

2022-10-03 13:38 UTC, FamousPig approved these changes

2022-10-03 16:28 UTC, TicClick approved these changes

2022-10-03 16:36 UTC, merged