[DE] Add `Gameplay/Game_modifier/Flashlight`
ppy/osu-wiki pull request #8043
Opened 2022-09-23 14:17 UTC by The-Last-Cookie

## Notes

There are three distinct terms that sound pretty similar. My proposal is to translate them as follows:
- `score multiplier` - `Score-Multiplikator` (changes when activating/deactivating difficulty changing mods)
- `combo (score multiplier)` - `Punktemultiplikator` (Combo value itself)
- `combo multiplier effect` - `Multiplikatoreffekt` (see #8029)

This will need changes in the following articles (if approved, that is):
- [ ] Adjust `Client/Interface` and `Gameplay/Game_modifier`

### Other notes

- not sure on `hitting area` --> `Trefferbereich`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-01 15:03 UTC, FamousPig requested changes

2022-10-01 15:03 UTC, FamousPig commented on wiki/Gameplay/Game_modifier/Flashlight/de.md
> +Wenn die Mod Hidden ebenfalls aktiviert ist, sind die Fruits vorübergehend sichtbar, sofern sich der Catcher *direkt unter* den Fruits befindet. Das gilt solange, bis der Spieler eine 100er Combo err
```suggestion
Wenn die Mod Hidden ebenfalls aktiviert ist, sind die Fruits vorübergehend sichtbar, sofern sich der Catcher *direkt unter* den Fruits befindet. Das gilt solange, bis der Spieler eine 100er Combo erreicht. Danach sind die Fruits vollständig unsichtbar, wenn sie den sichtbaren Bereich erreichen. Ähnlich wie in osu! und osu!taiko erfordert das auch das vollständige Auswendiglernen der Beatmap.
```

2022-10-01 15:04 UTC, FamousPig commented
`Trefferbereich` sounds fine to me 🤷

2022-10-03 13:42 UTC, FamousPig approved these changes

2022-10-03 16:23 UTC, TicClick approved these changes

2022-10-03 16:29 UTC, merged