[RU] Add `Unlock Requirements`
ppy/osu-wiki pull request #8053
Opened 2022-09-24 21:50 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-24 21:53 UTC, minusQuantumNeko commented
I messed up `Mod Introductions` commit name, don't know if anything can be done about it

2022-09-24 22:08 UTC, TicClick commented
it's not worth it if it's only a single commit in a chain of edits. I'll maybe fix that before merge if I remember

2022-09-25 09:33 UTC, Pisapou commented on wiki/Medals/Unlock_requirements/Seasonal_spotlights/ru.md
> +| Название медали	 | Условие |
```suggestion
| Название медали | Условие |
```

2022-09-26 13:54 UTC, TicClick requested changes

2022-09-26 13:54 UTC, TicClick commented on wiki/Medals/Unlock_requirements/ru.md
> +Индексная страница со всеми статьями касательно условий получения медалей. Hush-Hush медали не включены по понятным причинам.
```suggestion
Индексная страница, где перечислены все условия получения медалей. Медали категории Hush-Hush по понятным причинам сюда не входят.
```

2022-09-26 16:36 UTC, minusQuantumNeko commented on wiki/Medals/Unlock_requirements/Dedication/ru.md
> +| 50,000 Plays | Достичь в общем 50,000 игр в режиме osu!. | You're here forever. |
По поводу "достичь в общем" согласен, твой вариант лучше, но как на меня "5000" выглядит *приятнее* чем "5'000", поэтому предлагаю сделать так:

```suggestion
| 5,000 Plays | Набрать 5000 игр в режиме osu!. | There's a lot more where that came from. |
| 15,000 Plays | Набрать 15000 игр в режиме osu!. | Must.. click.. circles.. |
| 25,000 Plays | Набрать 25000 игр в режиме osu!. | There's no going back. |
| 50,000 Plays | Набрать 50000 игр в режиме osu!. | You're here forever. |
```

2022-09-26 16:45 UTC, minusQuantumNeko commented on wiki/Medals/Unlock_requirements/Dedication/ru.md
> +| 4,000,000 Keys | Нажать в общем 4,000,000 клавиш в режиме osu!mania. | Is this the end of the rainbow? |
Не совсем согласен с формулировкой условия, под нажатиями имеется ввиду попадание по ноте/клавише в ритм, а не просто спам кнопками в любой момент. 

```suggestion
| 40,000 Keys | Совершить 40000 нажатий клавиш в режиме osu!mania. | Just the start of the rainbow. |
| 400,000 Keys | Совершить 400000 нажатий клавиш в режиме osu!mania. | Four hundred thousand and still not even close. |
| 4,000,000 Keys | Совершить 4000000 нажатий клавиш в режиме osu!mania. | Is this the end of the rainbow? |
```

2022-09-26 16:48 UTC, TicClick commented on wiki/Medals/Unlock_requirements/Dedication/ru.md
> +| 50,000 Plays | Достичь в общем 50,000 игр в режиме osu!. | You're here forever. |
годится

2022-09-26 16:50 UTC, TicClick commented on wiki/Medals/Unlock_requirements/Dedication/ru.md
> +| 4,000,000 Keys | Нажать в общем 4,000,000 клавиш в режиме osu!mania. | Is this the end of the rainbow? |
да, я тоже про это подумал, но не знаю, как в мании объекты называются (для меня key — это дорожка на игровом поле). может, лучше тогда `NNN раз попасть по клавишам в режиме osu!mania`?

2022-09-26 19:18 UTC, TicClick approved these changes

2022-09-26 19:21 UTC, merged