[FR] Update `Client`
ppy/osu-wiki pull request #8065
Opened 2022-09-27 15:13 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-27 15:17 UTC, Ganondorf-1 requested changes

2022-09-27 15:17 UTC, Ganondorf-1 commented on wiki/Client/fr.md
> +- [Conseils du menu](Menu_tips)
```suggestion
- [Astuces du menu](Menu_tips)
```

2022-09-27 18:26 UTC, Ganondorf-1 approved these changes

2022-09-29 18:41 UTC, TicClick approved these changes

2022-09-29 18:45 UTC, merged