[RU] Add game modifier articles: `Half Time`, `Hard Rock`, `Hidden`, `Mirror`, and `Nightcore`
ppy/osu-wiki pull request #8081
Opened 2022-09-29 13:37 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-30 20:41 UTC, Moltanicaa commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +**Hidden** (букв. *скрытый*, жарг. *хидден*) — [игровой модификатор](/wiki/Game_modifier), который усложняет карту, убирая круги вокруг нот и заставляя [объекты](/wiki/Hit_object) пропадать после поя
Может быть убирая "приближающиеся" круги?

2022-09-30 20:42 UTC, Moltanicaa commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +Считается, что, в отличие от osu!, к Hidden в тайко привыкнуть сложнее, поскольку приходится запоминать цвет ынот.
Ынот

2022-10-01 10:12 UTC, Loreos7 requested changes

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +В [osu!taiko](/wiki/Game_mode/osu!taiko) ноты пропадают примерно в середине экрана, что заставляет игроков запоминать их тайминг и цвет. Слайдеры и спиннеры, тем не менее, всё время остаются видимыми
```suggestion
В [osu!taiko](/wiki/Game_mode/osu!taiko) ноты пропадают примерно посредине экрана, что заставляет игроков запоминать их тайминг и цвет. Слайдеры и спиннеры, тем не менее, всё время остаются видимыми (у спиннеров исчезает кольцо, показывающее, когда они закончатся).
```

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +В [osu!catch](/wiki/Game_mode/osu!catch) Hidden приводит к тому, что фрукты пропадают примерно в середине экрана.
```suggestion
В [osu!catch](/wiki/Game_mode/osu!catch) Hidden приводит к тому, что фрукты пропадают примерно посредине экрана.
```

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +- По умолчанию в [osu!](/wiki/Game_mode/osu!) вокруг самого первого [объекта](/wiki/Hit_object) на карте виден [вспомогательный круг](/wiki/Hit_object/Approach_circle), помогающий игроку войти в ритм
Так что, оставляем "круг", а не "окружность"?

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Mirror/ru.md
> +<!-- TODO:
```suggestion

```

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Mirror/ru.md
> +- [ ] add images -->
```suggestion

```

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Mirror/ru.md
> +---
```suggestion
  - мирор
```

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Mirror/ru.md
> +
```suggestion
  - зеркало
```

2022-10-01 10:12 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Nightcore/ru.md
> +- Название Nightcore связано с одноимённым подвидом музыки, где все песни ускорены на 10–30%, а их вокальные партии звучат более высоко.
```suggestion
- Название Nightcore связано с одноимённым подвидом музыки, где все песни ускорены на 10–30%, а их вокальные партии выше по тональности.
```

2022-10-01 10:18 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Hard_Rock/ru.md
> +Число нажатий, необходимое для прохождения спиннеров, увеличивается за счёт повышения OD. Таким образом, с Hard Rock можно набрать больше очков, чем с [Hidden](/wiki/Game_modifier/Hidden). Тем не мен
зачем? мы же не говорим «нажимать за ноту»

2022-10-01 10:18 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +Считается, что, в отличие от osu!, к Hidden в тайко привыкнуть сложнее, поскольку приходится запоминать цвет ынот.
бля!

2022-10-01 10:19 UTC, Loreos7 requested changes

2022-10-01 10:19 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Half_Time/ru.md
> +- Описание: `Less zoom.`
```suggestion
- Описание: `Все тако-о-ое ме-е-едленное.`
```
![image](https://user-images.githubusercontent.com/86934170/193404461-7aec4c27-9241-4641-88f6-1510378f4843.png)

2022-10-01 10:19 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hard_Rock/ru.md
> +- Описание: `Everything just got a bit harder...`
```suggestion
- Описание: `Жить и играть становится сложней.`
```
![image](https://user-images.githubusercontent.com/86934170/193404524-f5a31a0e-f131-41fe-8ba9-a8000789271f.png)

2022-10-01 10:19 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +  - ![][osu!]: `Play with no approach circles and fading notes for a slight score advantage.`
```suggestion
  - ![][osu!]: `Нот не существует, Нео.`
```
![image](https://user-images.githubusercontent.com/86934170/193404546-85c376f3-a509-452b-9dc8-eb2eeda1ed0c.png)

2022-10-01 10:19 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +  - ![][osu!taiko]: `The notes fade out before you hit them!`
```suggestion
  - ![][osu!taiko]: `Ноты исчезают прямо перед ударом.`
```
![image](https://user-images.githubusercontent.com/86934170/193404573-925945d9-d8d7-480d-9e6c-2b1e46662903.png)

2022-10-01 10:19 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +  - ![][osu!catch] `Play with no approach circles and fading notes for a slight score advantage.`
```suggestion
  - ![][osu!catch] `Нот не существует, Нео.`
```

2022-10-01 10:19 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +  - ![][osu!mania]: `The notes fade out before you hit them!`
```suggestion
  - ![][osu!mania]: `Перед клавишами возникает полоска тьмы, в которой скрываются ноты.`
```
![image](https://user-images.githubusercontent.com/86934170/193404624-ae998652-6781-477f-8678-fb252db65179.png)

2022-10-01 10:19 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Nightcore/ru.md
> +- Описание: `uguuuuuuuu`
```suggestion
- Описание: `ТЫЦ ТЫЦ ТЫЦ ТЫЦ`
```
![image](https://user-images.githubusercontent.com/86934170/193404675-c1ba0e84-39b3-46e9-b30b-21fe86c2f62b.png)

2022-10-01 10:28 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +- По умолчанию в [osu!](/wiki/Game_mode/osu!) вокруг самого первого [объекта](/wiki/Hit_object) на карте виден [вспомогательный круг](/wiki/Hit_object/Approach_circle), помогающий игроку войти в ритм
хочется найти удачный термин и пользоваться только им, да проблема в том, что пользуются все в основном калькой, точный вариант слишком громоздкий, а неточный — неточный. мне не хочется пока с этим возиться, в итоге конкретно сейчас получился какой-то компромисс. можем потом выбрать ещё раз. здесь можно и про окружность сказать, да.

2022-10-01 10:33 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +**Hidden** (букв. *скрытый*, жарг. *хидден*) — [игровой модификатор](/wiki/Game_modifier), который усложняет карту, убирая круги вокруг нот и заставляя [объекты](/wiki/Hit_object) пропадать после поя
сходящиеся тогда уж

2022-10-01 11:40 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hard_Rock/ru.md
> +Число нажатий, необходимое для прохождения спиннеров, увеличивается за счёт повышения OD. Таким образом, с Hard Rock можно набрать больше очков, чем с [Hidden](/wiki/Game_modifier/Hidden). Тем не мен
На спиннер не нажимают, а выбивают каты и доны за время его действия

2022-10-01 11:41 UTC, Loreos7 commented on wiki/Gameplay/Game_modifier/Hidden/ru.md
> +- По умолчанию в [osu!](/wiki/Game_mode/osu!) вокруг самого первого [объекта](/wiki/Hit_object) на карте виден [вспомогательный круг](/wiki/Hit_object/Approach_circle), помогающий игроку войти в ритм
Хочется согласованности, согласен. В будущем оставим выбор тебе.

2022-10-01 21:53 UTC, TicClick commented on wiki/Gameplay/Game_modifier/Hard_Rock/ru.md
> +Число нажатий, необходимое для прохождения спиннеров, увеличивается за счёт повышения OD. Таким образом, с Hard Rock можно набрать больше очков, чем с [Hidden](/wiki/Game_modifier/Hidden). Тем не мен
тогда лучше «нажатие во время спиннера», чтобы было достаточно обтекаемо

2022-10-01 22:09 UTC, Walavouchey approved these changes

2022-10-01 22:10 UTC, merged