[FR] Update `Skinning/osu!`
ppy/osu-wiki pull request #8083
Opened 2022-09-29 15:51 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-30 14:08 UTC, Ganondorf-1 requested changes

2022-09-30 14:08 UTC, Ganondorf-1 commented on wiki/Skinning/osu!/fr.md
> +La visibilité des superpositions des sliders dépend des éléments cercles du slider:
```suggestion
La visibilité des overlays des sliders dépend des éléments cercles du slider:
```

2022-10-01 18:26 UTC, Ganondorf-1 approved these changes

2022-10-01 21:51 UTC, TicClick approved these changes

2022-10-01 21:53 UTC, merged