[FR] Add `osu! originals`
ppy/osu-wiki pull request #8089
Opened 2022-09-30 13:38 UTC by Ganondorf-1

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-30 16:00 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [James Landino - Reaction feat. Slyleaf](https://osu.ppy.sh/beatmaps/artists/tracks?artist=James%20Landino&query=Reaction%20feat.%20Slyleaf) | Partie de [osu! James Landino Collection EP](https://f
```suggestion
| [James Landino - Reaction feat. Slyleaf](https://osu.ppy.sh/beatmaps/artists/tracks?artist=James%20Landino&query=Reaction%20feat.%20Slyleaf) | Fait partie de [osu! James Landino Collection EP](https://fanlink.to/osulandino) |
```

2022-09-30 16:00 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [James Landino - Shiba Island](https://osu.ppy.sh/beatmaps/artists/tracks?artist=James%20Landino&query=Shiba%Island) | Partie de [osu! James Landino Collection EP](https://fanlink.to/osulandino) |
```suggestion
| [James Landino - Shiba Island](https://osu.ppy.sh/beatmaps/artists/tracks?artist=James%20Landino&query=Shiba%Island) | Fait partie de [osu! James Landino Collection EP](https://fanlink.to/osulandino) |
```

2022-09-30 16:00 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [James Landino - Spellbound](https://osu.ppy.sh/beatmaps/artists/tracks?artist=James%20Landino&query=Spellbound) | Partie de [osu! James Landino Collection EP](https://fanlink.to/osulandino) |
```suggestion
| [James Landino - Spellbound](https://osu.ppy.sh/beatmaps/artists/tracks?artist=James%20Landino&query=Spellbound) | Fait partie de [osu! James Landino Collection EP](https://fanlink.to/osulandino) |
```

2022-09-30 16:00 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [kiraku - connection](https://osu.ppy.sh/beatmaps/artists/tracks?artist=kiraku&query=connection) | Présentée dans [Monthly Beatmapping Contest: October 2020](https://osu.ppy.sh/home/news/2020-10-06
```suggestion
| [kiraku - connection](https://osu.ppy.sh/beatmaps/artists/tracks?artist=kiraku&query=connection) | Présentée dans le [Monthly Beatmapping Contest: October 2020](https://osu.ppy.sh/home/news/2020-10-06-monthly-beatmapping-contest-october) |
```

2022-09-30 16:00 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [yuki. - Nadeshiko Sensation](https://soundcloud.com/yuki_0126/nadeshiko-sensation) | Présentée dans [Community Mapping Contest #1](https://osu.ppy.sh/home/news/2016-09-28-community-mapping-contest
```suggestion
| [yuki. - Nadeshiko Sensation](https://soundcloud.com/yuki_0126/nadeshiko-sensation) | Présentée dans le [Community Mapping Contest #1](https://osu.ppy.sh/home/news/2016-09-28-community-mapping-contest-1-yuki-nadeshiko) |
```

2022-10-01 18:08 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [nekodex - aureole](https://soundcloud.com/nekodex/aureole)[^fa-catalogue] | Thème d'osu! lors de l'hiver/Noël en 2017 |
```suggestion
| [nekodex - aureole](https://soundcloud.com/nekodex/aureole)[^fa-catalogue] | Thème d'osu! lors de l'hiver/Noël 2017 |
```

2022-10-01 18:08 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [nekodex - carol of the circles](https://soundcloud.com/nekodex/carol-of-the-circles)[^fa-catalogue] | Thème d'osu! lors de l'hiver/Noël en 2019 |
```suggestion
| [nekodex - carol of the circles](https://soundcloud.com/nekodex/carol-of-the-circles)[^fa-catalogue] | Thème d'osu! lors de l'hiver/Noël 2019 |
```

2022-10-01 18:08 UTC, Pisapou commented on wiki/osu!_originals/fr.md
> +| [nekodex - Little Drummer Girl](https://soundcloud.com/nekodex/carol-of-the-circles)[^fa-catalogue] | Thème d'osu! lors de l'hiver/Noël en 2020 |
```suggestion
| [nekodex - Little Drummer Girl](https://soundcloud.com/nekodex/carol-of-the-circles)[^fa-catalogue] | Thème d'osu! lors de l'hiver/Noël 2020 |
```

2022-10-01 18:34 UTC, Pisapou submitted a review, later dismissed

2022-10-01 19:41 UTC, Walavouchey requested changes

2022-10-01 19:41 UTC, Walavouchey commented on wiki/osu!_originals/fr.md
> +### Official tournament releases
a

2022-10-01 19:41 UTC, Walavouchey commented on wiki/osu!_originals/fr.md
> +### Community-run tournament releases
b

2022-10-01 19:41 UTC, Walavouchey commented on wiki/osu!_originals/fr.md
> +Toutes les osu! originals qui ont été autorisées à l'utilisation par le jeu peuvent être utilisées sur osu! à des conditions non exclusives conformément à la [politique de licence musicale d'osu!](/w
> les osu! originals qui ont été autorisées à l'utilisation par le jeu peuvent être utilisées sur osu!

> les osu! originals qui n'ont pas été autorisées à l'utilisation peuvent nécessiter une autorisation d'utilisation

lolwat

i mean, yes, this is technically correct, but can't it be expressed in a better way? perhaps using the word "licence"?

2022-10-01 19:41 UTC, Walavouchey commented on wiki/osu!_originals/fr.md
> +Les **osu! originals** sont des musiques spécifiquement faites pour (ou ont fait leur première apparition sur) osu! ou d'autres événements en rapport avec osu! tels que les tournois, les concours, et
```suggestion
Les **osu! originals** sont des musiques spécifiquement faites pour (ou ont fait leur première apparition sur) osu! ou d'autres événements en rapport avec osu! tels que les tournois, les concours, et les annonces de [Featured Artists](/wiki/Featured_Artists). Bien que les osu! originals ne soient pas toutes sous licence officielle et dans la [liste des Featured Artists](https://osu.ppy.sh/beatmaps/artists), les musiques qui le sont sont généralement distinguées par le label `ORIGINAL` sur les pages de leurs artistes respectifs.
```

2022-10-09 22:24 UTC, TicClick commented
please apply https://github.com/ppy/osu-wiki/pull/8169 as well

2022-10-10 17:37 UTC, Walavouchey approved these changes

2022-10-10 17:40 UTC, merged