[ZH] Add `osu! music licensing`
ppy/osu-wiki pull request #8090
Opened 2022-09-30 15:30 UTC by FlyingFish23

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-09-30 19:12 UTC, TicClick commented
please only check the second item if there is a review from a native (or fluent) speaker, which is posted here, on GitHub

2022-10-01 08:58 UTC, FlyingFish23 commented
> please only check the second item if there is a review from a native (or fluent) speaker, which is posted here, on GitHub
Got it, thanks

2022-10-01 08:59 UTC, FlyingFish23 commented
> please only check the second item if there is a review from a native (or fluent) speaker, which is posted here, on GitHub

Got it, thanks.

2022-10-10 06:33 UTC, heipizhu4 reviewed
One point to discuss and an extra space to delete.

2022-10-15 06:10 UTC, YumeMuzi requested changes
Please fix these paragraphs for more fluent, precise, and comprehensible.

2022-10-15 06:10 UTC, YumeMuzi commented on wiki/Legal/Music_licensing/zh.md
> +osu! 获得的全部音乐使用权均不是独家的，osu! 可使用的音乐，其他平台也可以在取得著作权人许可的情况下使用（我们始终相信，好音乐不应该被限制在 osu! 这一个平台里）。考虑到使用的性质，我们通常愿意购买歌曲的永久使用权（用户希望自己创作的谱面能够永久可用）。版税会在协商之后一次性付清。
```suggestion
osu! 不会买断歌曲的使用权。这些歌曲既可以在 osu! 内使用，也可以在取得著作权人许可后，在其他平台内使用（我们始终相信，好音乐不应被限制在 osu! 这一个平台里）。考虑到使用的性质（玩家希望自己创作的谱面能够永久可用），我们通常会购买歌曲的永久使用权。版税会在协商之后一次性付清。
```

2022-10-15 06:10 UTC, YumeMuzi commented on wiki/Legal/Music_licensing/zh.md
> +如果你想就你的内容在 osu! 内被使用所应取得的相关许可进行协商，请使用上面的电子邮件地址联系我们，并附带你的作品样览。我们会决定你的曲目适不适合作为 osu! 的内容，并且就版税问题与你达成统一。
```suggestion
如果你对于加入 osu! 精选艺术家感兴趣，请使用上面的电子邮件地址联系我们，并附带你的作品样览。我们会决定你的曲目是否适合作为 osu! 的内容，并会与你洽谈版税相关事宜。
```

2022-10-15 06:10 UTC, YumeMuzi commented on wiki/Legal/Music_licensing/zh.md
> +是这些艺术家们的作品才帮助 osu! 走到今天，而为了表示我们的支持，我们从用户手中收取到的捐赠资金结余均会投入到音乐版税当中。我们正在努力联系相关的著作权人们（包括以前内容和新内容的相关著作权人）来获取引用作品的版权且告知我们的[精选艺术家](/wiki/Featured_Artists)项目。
```suggestion
是这些艺术家们的作品才帮助 osu! 走到今天，为了表示我们的支持，我们从玩家手中收取到的捐赠资金结余均会投入到音乐版税当中。我们正在努力联系相关的著作权人（包括以前内容和新内容的相关著作权人）来获取被使用内容的版权，并且向他们推荐我们的[精选艺术家](/wiki/Featured_Artists)项目。
```

2022-10-15 11:47 UTC, FlyingFish23 commented on wiki/Legal/Music_licensing/zh.md
> +提交谱面是，谱面的制作者均会被推荐遵照我们的[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)来向谱面中元素的相关著作权人取得使用许可。
this article is for copyright holders/artists. some of them may not know what is "谱师", i think “谱面的制作者" would be more intuitive for them to understand.

2022-10-15 11:55 UTC, FlyingFish23 commented on wiki/Legal/Music_licensing/zh.md
> +osu! 获得的全部音乐使用权均不是独家的，osu! 可使用的音乐，其他平台也可以在取得著作权人许可的情况下使用（我们始终相信，好音乐不应该被限制在 osu! 这一个平台里）。考虑到使用的性质，我们通常愿意购买歌曲的永久使用权（用户希望自己创作的谱面能够永久可用）。版税会在协商之后一次性付清。
i don't think "买断" can't express the meaning of "独家". for example, i can "买断" a software and use it for a lifetime, but others can still purchase the same software. "买断" means one-time purchase, and “独家" means "only one can use". a better way for this sentence can be "osu! 不会购买歌曲的独家使用权".

2022-10-15 14:21 UTC, YumeMuzi commented on wiki/Legal/Music_licensing/zh.md
> +osu! 获得的全部音乐使用权均不是独家的，osu! 可使用的音乐，其他平台也可以在取得著作权人许可的情况下使用（我们始终相信，好音乐不应该被限制在 osu! 这一个平台里）。考虑到使用的性质，我们通常愿意购买歌曲的永久使用权（用户希望自己创作的谱面能够永久可用）。版税会在协商之后一次性付清。
ok

2022-10-15 14:21 UTC, YumeMuzi commented on wiki/Legal/Music_licensing/zh.md
> +提交谱面是，谱面的制作者均会被推荐遵照我们的[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)来向谱面中元素的相关著作权人取得使用许可。
ok

2022-10-15 14:25 UTC, YumeMuzi commented on wiki/Legal/Music_licensing/zh.md
> +osu! 获得的全部音乐使用权均不是独家的，osu! 可使用的音乐，其他平台也可以在取得著作权人许可的情况下使用（我们始终相信，好音乐不应该被限制在 osu! 这一个平台里）。考虑到使用的性质，我们通常愿意购买歌曲的永久使用权（用户希望自己创作的谱面能够永久可用）。版税会在协商之后一次性付清。
Please update the rest of this suggested change

2022-10-15 14:26 UTC, YumeMuzi commented on wiki/Legal/Music_licensing/zh.md
> +提交谱面是，谱面的制作者均会被推荐遵照我们的[内容使用准则](/wiki/Rules/Content_Usage_Guidelines)来向谱面中元素的相关著作权人取得使用许可。
Please update the rest of this suggested change, Most importantly, there is a typo in this sentence

2022-10-23 23:52 UTC, TicClick commented
@YumeMuzi could you please give it another review and see if it reads well enough?

2022-10-27 09:18 UTC, heipizhu4 approved these changes
It's all done. Let's get it merged.

2022-10-27 10:11 UTC, TicClick approved these changes

2022-10-27 10:14 UTC, merged