[FR] Update `Bancho`
ppy/osu-wiki pull request #8099
Opened 2022-10-02 12:34 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-02 12:38 UTC, Walavouchey commented on wiki/Bancho_(server)/fr.md
> +**Bancho** (ou *osu!Bancho*) est le nom de code du serveur qui gère les interactions en temps réel entre les joueurs utilisant des versions stables d'osu!:
```suggestion
**Bancho** (ou *osu!Bancho*) est le nom de code du serveur qui gère les interactions en temps réel entre les joueurs utilisant des versions stables d'osu! :
```

2022-10-02 12:38 UTC, Walavouchey commented on wiki/Bancho_(server)/fr.md
> +- [Système de Multijoueur](/wiki/Client/Interface/Multiplayer) et [gestion de tournois](/wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands)
```suggestion
- [Système de multijoueur](/wiki/Client/Interface/Multiplayer) et [gestion de tournois](/wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands)
```

2022-10-02 16:26 UTC, Pisapou commented on wiki/Bancho_(server)/fr.md
> +
```suggestion
```

2022-10-04 17:51 UTC, Ganondorf-1 requested changes

2022-10-04 17:51 UTC, Ganondorf-1 commented on wiki/Bancho_(server)/fr.md
> +- Système de chat, [présence en ligne](/wiki/Client/Interface/Chat_console#la-console-de-tchat-étendue), et [passerelle IRC](/wiki/Community/Internet_Relay_Chat)
```suggestion
- Système de tchat, [présence en ligne](/wiki/Client/Interface/Chat_console#la-console-de-tchat-étendue), et [passerelle IRC](/wiki/Community/Internet_Relay_Chat)
```

2022-10-04 17:51 UTC, Ganondorf-1 commented on wiki/Bancho_(server)/fr.md
> +Durant les périodes de maintenance, Bancho est parfois redémarré. Ceci est relayé à tous les utilisateurs en ligne par un système d'annonces dans le jeu, ainsi que par des messages d'avertissement pé
```suggestion
Durant les périodes de maintenance, Bancho est parfois redémarré. Ceci est relayé à tous les utilisateurs en ligne par un système d'annonces dans le jeu, ainsi que par des messages d'avertissement périodiques dans le tchat avec un compte à rebours. Les redémarrages de Bancho n'affectent que le tchat et le multijoueur, car toutes les autres fonctionnalités sont gérées par des API différentes [^score-upload-ref].
```

2022-10-06 20:46 UTC, Ganondorf-1 approved these changes

2022-10-07 12:33 UTC, TicClick approved these changes

2022-10-07 12:34 UTC, merged