[FR] Update `Main_Page`
ppy/osu-wiki pull request #8113
Opened 2022-10-03 15:55 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-03 16:36 UTC, Ganondorf-1 requested changes

2022-10-03 16:36 UTC, Ganondorf-1 commented on wiki/Main_Page/fr.md
> +Lieux d'échanges: [Forum](/wiki/Community/Forum) • [IRC](/wiki/Community/Internet_Relay_Chat)
```suggestion
Lieux d'échanges : [Forum](/wiki/Community/Forum) • [IRC](/wiki/Community/Internet_Relay_Chat)
```

2022-10-03 16:45 UTC, Ganondorf-1 submitted a review, later dismissed

2022-10-04 14:41 UTC, TicClick approved these changes

2022-10-04 14:42 UTC, TicClick approved these changes

2022-10-04 15:00 UTC, merged