[FR] Update `Contests`
ppy/osu-wiki pull request #8139
Opened 2022-10-05 18:02 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-05 18:05 UTC, Walavouchey commented on wiki/Contests/fr.md
> +| [#32 (15th Anniversary Art Contest)](https://osu.ppy.sh/home/news/2022-08-15-15-anniversary-art-contest) | Les mascottes d'osu! qui explorent une partie de l'histoire d'osu! | ::{ flag=ID }:: [Drea
there's one other theme that's translated, maybe all of them should be?

2022-10-05 18:06 UTC, Walavouchey commented on wiki/Contests/fr.md
> +| [#2](https://osu.ppy.sh/community/forums/topics/1639586) | ::{ flag=AR }:: [Axer](https://osu.ppy.sh/users/7299864) | ::{ flag=TH }:: [Ph0eNiiXZ](https://osu.ppy.sh/users/9463721) | ::{ flag=SG }::
guess this was missed in the english version

```suggestion
| [#1](https://osu.ppy.sh/community/forums/topics/1624880) | ::{ flag=NL }:: [Boaz](https://osu.ppy.sh/users/13302996) | ::{ flag=JP }:: [_Rise](https://osu.ppy.sh/users/5217107) | ::{ flag=CL }:: [Metsaller](https://osu.ppy.sh/users/4364791) | ::{ flag=FI }:: [Antti](https://osu.ppy.sh/users/13281473) | [#1](https://docs.google.com/spreadsheets/d/1aR1GjF8diyjFhK_k_uOkU40zIKjaQbXhVbGDGmq5pdg/edit?usp=sharing) |
| [#2](https://osu.ppy.sh/community/forums/topics/1639586) | ::{ flag=AR }:: [Axer](https://osu.ppy.sh/users/7299864) | ::{ flag=TH }:: [Ph0eNiiXZ](https://osu.ppy.sh/users/9463721) | ::{ flag=SG }:: [\_gt](https://osu.ppy.sh/users/8301957) | ::{ flag=US }:: [Vixlowo](https://osu.ppy.sh/users/20295114) | [#1](https://docs.google.com/spreadsheets/d/1ps3bOL2JlzwPEh0gVTLHnp7E48stwqHMH6-ljDSBJQs/edit?usp=sharing) |
```

2022-10-06 20:51 UTC, Ganondorf-1 requested changes

2022-10-06 20:51 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +| [#26 (Winter 2020)](https://osu.ppy.sh/home/news/2020-09-11-winter-sports-2020-fanart-contest) | Sport d'Hiver | ::{ flag=US }:: [Tofumang](https://osu.ppy.sh/users/4817223) | ::{ flag=ID }:: [Chee
```suggestion
| [#26 (Winter 2020)](https://osu.ppy.sh/home/news/2020-09-11-winter-sports-2020-fanart-contest) | Sports d'Hiver | ::{ flag=US }:: [Tofumang](https://osu.ppy.sh/users/4817223) | ::{ flag=ID }:: [CheekyIfa](https://osu.ppy.sh/users/14406940) | ::{ flag=RU }:: [Dem4eg-](https://osu.ppy.sh/users/7206818) | [#1](https://osu.ppy.sh/home/news/2020-12-02-winter-2020-arrives) |
```

2022-10-06 20:51 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +**Mapping to Pander: Taiko** est une série de concours de mapping osu!taiko avec deux caractéristiques principales : il n'y a qu'un seul juge par itération, et les participants peuvent map n'importe
```suggestion
**Mapping to Pander: Taiko** est une série de concours de mapping osu!taiko avec deux caractéristiques principales : il n'y a qu'un seul juge par itération, et les participants peuvent mapper n'importe quelle musique.
```

2022-10-06 20:51 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +Le but de ce concours est simple : les participants doivent créer une map qui plaise le plus au juge choisi pour le concours. Le juge ne recevra aucun critère ; il lui appartiendra de noter et de cla
```suggestion
Le but de ce concours est simple : les participants doivent créer une map qui plaise le plus au juge choisi pour le concours. Le juge ne recevra aucun critère ; il lui appartiendra de noter et de classer les beatmaps, soit en établissant ses propres critères, soit en classant les beatmaps de la meilleure à la pire.
```

2022-10-06 20:51 UTC, Ganondorf-1 commented on wiki/Contests/fr.md
> +| Numéro du concours | Juge | ![Couronne en or][GCrown] | ![Couronne en argent][SCrown] | ![Couronne en bronze][BCrown] | Resultats |
```suggestion
| Numéro du concours | Juge | ![Couronne en or][GCrown] | ![Couronne d'argent][SCrown] | ![Couronne de bronze][BCrown] | Résultats |
```

2022-10-15 19:32 UTC, Ganondorf-1 approved these changes

2022-10-16 17:29 UTC, TicClick approved these changes

2022-10-16 17:32 UTC, merged