[FR] Update `Article_styling_criteria/Formatting` and `Article_styling_criteria/Writing`
ppy/osu-wiki pull request #8149
Opened 2022-10-06 15:21 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-06 20:57 UTC, Ganondorf-1 requested changes

2022-10-06 20:57 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Formatting/fr.md
> +La première version de l'osu!api a été mise à disposition le 2 juillet 2013.[^api-first-usage] Elle avait été saluée par la critique des utilisateurs.[^api-praise] Une nouvelle version de l'API, publ
```suggestion
La première version de l'osu!api a été mise à disposition le 2 juillet 2013.[^api-first-usage] Elle avait été saluée par la critique des utilisateurs.[^api-praise] Une nouvelle version de l'API, publiée plusieurs années plus tard, contient beaucoup plus de capacités.[^api-v2-2020] Le versionnage des points de terminaison est courant parmi les API web.[^web-api]
```

2022-10-08 10:15 UTC, Ganondorf-1 approved these changes

2022-10-14 23:22 UTC, TicClick approved these changes

2022-10-14 23:24 UTC, merged