[DE] Add game modifiers `10K`, `Auto` and `Autopilot`
ppy/osu-wiki pull request #8150
Opened 2022-10-06 15:42 UTC by The-Last-Cookie

After the related terminology was adjusted and approved in #8043 and #8079, now it is time to translate the missing game modifier articles. This PR is part 1 of the coming PR series.

## Translation notes

- `hold bar` --> `Leiste`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-06 16:58 UTC, The-Last-Cookie commented on wiki/Gameplay/Game_modifier/Auto/de.md
> +- Score-Multiplikator: 1,00 x
Now that I think about it, in my opinion, it's better to not put a space between the number and the x. The article `Co-op mod` has a table with numerous multipliers and I think putting a space everywhere makes the table less readable.

On the contrary, where I do think it to make sense is in the description of dimensions with the so called `Malkreuz` (e.g. `1920 × 1080`).

Very nitpicky, I know, but I wanted to mention it.

2022-10-06 18:11 UTC, Walavouchey commented
it's "hold note" and not "hold bar", if that's relevant in any way.

2022-10-08 10:31 UTC, The-Last-Cookie commented on wiki/Gameplay/Game_modifier/Auto/de.md
> +- Score-Multiplikator: 1,00 x
```suggestion
- Score-Multiplikator: 1,00x
```

2022-10-08 10:31 UTC, The-Last-Cookie commented on wiki/Gameplay/Game_modifier/Auto/de.md
> +In [osu!mania](/wiki/Game_mode/osu!mania) wird die Mod Auto versuchen, einen perfekten Durchlauf zu erzielen, aber verfehlt möglicherweise dicht aneinander gedrängte Noten (z. B. mehrere Tastendrücke
```suggestion
In [osu!mania](/wiki/Game_mode/osu!mania) wird die Mod Auto versuchen, einen perfekten Durchlauf zu erzielen, aber verfehlt möglicherweise dicht aneinanderliegende Noten (z. B. mehrere Tastendrücke nah beieinander auf einer Hold-Note).
```

2022-10-08 10:31 UTC, The-Last-Cookie commented on wiki/Gameplay/Game_modifier/Auto/de.md
> +- After watching an Auto replay, the mod will deselect itself and the user will be forced to reselect the mod if they wish to watch the replay again. This will happen whether or not the replay is wat
```suggestion
- Nachdem ein Replay mit der Mod Auto angesehen wurde, wird die Mod automatisch deaktiviert und der Nutzer wird gezwungen, die Mod erneut anzuwählen, wenn er das Replay noch einmal anschauen möchte. Dies geschieht unabhängig davon, ob das Replay bis zum Ende angesehen wird oder nicht.
```

2022-10-08 10:31 UTC, The-Last-Cookie commented on wiki/Gameplay/Game_modifier/Autopilot/de.md
> +- Score-Multiplikator: 0,00 x
```suggestion
- Score-Multiplikator: 0,00x
```

2022-10-08 10:32 UTC, The-Last-Cookie commented on wiki/Gameplay/Game_modifier/Auto/de.md
> +- Beim Zuschauen eines Replays mit der Mod Auto ist der in der Rangleiste angezeigte Nutzername "osu!".
```suggestion
- Beim Zuschauen eines Replays mit der Mod Auto ist der in der Rangliste angezeigte Nutzername "osu!".
```

2022-10-08 10:38 UTC, The-Last-Cookie commented
> it's "hold note" and not "hold bar", if that's relevant in any way.

Thanks, I adjusted this in the self-review above.

2022-10-22 21:28 UTC, FamousPig requested changes
Looks good apart from a minor point (+ the unresolved todo item)

2022-10-22 21:28 UTC, FamousPig commented on wiki/Gameplay/Game_modifier/Auto/de.md
> +- Beim Zuschauen eines Replays mit der Mod Auto ist der in der Rangliste angezeigte Nutzername "osu!".
```suggestion
- Beim Anschauen eines Replays mit der Mod Auto ist der in der Rangliste angezeigte Nutzername "osu!".
```

`Zuschauen` to me means watching something live. Watching a replay live sounds weird to me. Not a huge deal though.

2022-12-21 18:48 UTC, TicClick approved these changes

2022-12-21 18:51 UTC, merged