[FR] Update `Brand_identity_guidelines`
ppy/osu-wiki pull request #8153
Opened 2022-10-06 20:41 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-06 21:13 UTC, Ganondorf-1 requested changes

2022-10-06 21:13 UTC, Ganondorf-1 commented on wiki/Brand_identity_guidelines/fr.md
> +![](img/usage-single-colour.png "Logo osu! en une seule couleur")
```suggestion
![](img/usage-single-colour.png "Logo d'osu! en une seule couleur")
```

2022-10-06 21:13 UTC, Ganondorf-1 commented on wiki/Brand_identity_guidelines/fr.md
> +![](img/usage-full-colour.png "Logo osu! en couleur")
```suggestion
![](img/usage-full-colour.png "Logo d'osu! en couleur")
```

2022-10-06 21:13 UTC, Ganondorf-1 commented on wiki/Brand_identity_guidelines/fr.md
> +![](img/clear-space-area.png "Exemple de marges autour du logo osu!")
```suggestion
![](img/clear-space-area.png "Exemple de marges autour du logo d'osu!")
```

2022-10-14 21:11 UTC, Ganondorf-1 approved these changes

2022-10-14 23:07 UTC, TicClick approved these changes

2022-10-14 23:11 UTC, merged