[FR] Update `Beatmap/Approach_rate`
ppy/osu-wiki pull request #8156
Opened 2022-10-07 19:57 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-07 19:58 UTC, Pisapou commented on wiki/Beatmap/Approach_rate/fr.md
> +Dans [osu!taiko](/wiki/Game_mode/osu!taiko) et [osu!mania](/wiki/Game_mode/osu!mania), le réglage de l'approach rate n'a aucun effet. La vitesse de défilement dans les deux modes est contrôlée par le
```suggestion
Dans [osu!taiko](/wiki/Game_mode/osu!taiko) et [osu!mania](/wiki/Game_mode/osu!mania), le réglage de l'approach rate n'a aucun effet. La vitesse de défilement dans les deux modes est contrôlée par le [slider velocity](/wiki/Gameplay/Hit_object/Slider/Slider_velocity), qui dépend du [BPM](/wiki/Music_theory/Tempo) et du multiplicateur de slider velocity. De plus, dans osu!mania, elle peut être personnalisé [par le joueur lui-même](/wiki/Game_mode/osu!mania#changement-de-vitesse).
```

2022-10-08 10:08 UTC, Ganondorf-1 requested changes

2022-10-08 10:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Approach_rate/fr.md
> +Alors que les mods Half Time *(HT)* et Double Time *(DT)* ne modifient pas la valeur de l'AR, la différence de vitesse y entraîne un changement notable. Les AR de HT/DT sont généralement désignés en
```suggestion
Bien que les mods Half Time *(HT)* et Double Time *(DT)* ne modifient pas la valeur de l'AR, la différence de vitesse y entraîne un changement notable. Les AR de HT/DT sont généralement désignés en fonction de leur valeur perçue. Par exemple, "AR 8 + DT" peut également être écrit "AR 9.6".
```

2022-10-08 10:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Approach_rate/fr.md
>    - reading
Maybe we should add `temps d'approche` here ? It's the French translation of `Approach time` on the stable client

2022-10-08 10:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Approach_rate/fr.md
> +Dans [osu!taiko](/wiki/Game_mode/osu!taiko) et [osu!mania](/wiki/Game_mode/osu!mania), le réglage de l'approach rate n'a aucun effet. La vitesse de défilement dans les deux modes est contrôlée par le
```suggestion
Dans [osu!taiko](/wiki/Game_mode/osu!taiko) et [osu!mania](/wiki/Game_mode/osu!mania), le réglage de l'approach rate n'a aucun effet. La vitesse de défilement dans les deux modes est contrôlée par le [slider velocity](/wiki/Gameplay/Hit_object/Slider/Slider_velocity), qui dépend du [BPM](/wiki/Music_theory/Tempo) et du multiplicateur de slider velocity. De plus, dans osu!mania, elle peut être personnalisée [par le joueur lui-même](/wiki/Game_mode/osu!mania#changement-de-vitesse).
```

2022-10-08 10:32 UTC, Ganondorf-1 approved these changes

2022-10-09 22:30 UTC, TicClick approved these changes

2022-10-09 22:34 UTC, merged