[EN/ZH] Update `GBC 2022 Autumn`
ppy/osu-wiki pull request #8179
Opened 2022-10-10 09:36 UTC by RushFTK

Ask for high priority since qualifier will be start soon, sorry for trouble.

- Add Chinese translation.
- Update rules.
- Add schedule & Mapppools for qualifier.

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-10 09:39 UTC, yobrevelc approved these changes
reviewed

2022-10-10 09:59 UTC, yobrevelc submitted a review, later dismissed
reviewed

2022-10-10 15:46 UTC, TPGPL requested changes

2022-10-10 15:46 UTC, TPGPL commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Statistician & Wiki Editor | ::{ flag=CN }:: [\[GB\]Rush\_FTK](https://osu.ppy.sh/users/3046856), ::{ flag=CN }:: [\[GB\]Yuria](https://osu.ppy.sh/users/13092888), ::{ flag=CN }:: [\[GB\]yobrevelc]
```suggestion
| Statistician & Wiki editor | ::{ flag=CN }:: [\[GB\]Rush\_FTK](https://osu.ppy.sh/users/3046856), ::{ flag=CN }:: [\[GB\]Yuria](https://osu.ppy.sh/users/13092888), ::{ flag=CN }:: [\[GB\]yobrevelc](https://osu.ppy.sh/users/14128407), ::{ flag=CN }:: [\[GB\]Natro](https://osu.ppy.sh/users/27233308) |
```

2022-10-10 18:09 UTC, Walavouchey requested changes

2022-10-10 18:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
>  3. Following the Regular stage, a single elimination stage will be played, called `Play-offs`. This means that the winner continues with their runs, and the losing team will be eliminated from the to
```suggestion
3. Following the Regular stage, a single-elimination stage will be played, called *Playoffs*. This means that the winner continues with their runs, and the losing team will be eliminated from the tournament, except in the bronze match.
```

2022-10-10 18:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
>     - This means that teams with a record of `3-X` will advance to the next stage, while teams with a record of `X-3` will be eliminated.
```suggestion
   - This means that teams with a record of 3-X will advance to the next stage, while teams with a record of X-3 will be eliminated.
```

2022-10-10 18:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
>     - Teams with a record `3-0` or `0-3` needn't play round 4, as they are already advanced or get eliminated.
```suggestion
   - Also, teams with a record of 2-2 will have the chance to advance by ranking in the top 16.
   - Teams with a record 3-0 or 0-3 need not play round 4, as they have already advanced or gotten eliminated.
```

2022-10-10 18:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
>  1. There will be five separate mappools, *this might change depending on the number of incoming registrations.*.
```suggestion
1. There will be five separate mappools. *This might change depending on the number of incoming registrations.*
```

2022-10-10 18:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Qualifiers use separate mappool.
```suggestion
   - Qualifiers will use a separate mappool.
```

2022-10-10 18:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
>  5. Possible mod choices for the FreeMod bracket are NoFail, Hidden, FadeIn, Flashlight, and Mirror.
```suggestion
5. Possible mod choices for the FreeMod bracket are No Fail, Hidden, Fade In, Flashlight, and Mirror.
```

2022-10-11 01:04 UTC, RushFTK commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| Statistician & Wiki Editor | ::{ flag=CN }:: [\[GB\]Rush\_FTK](https://osu.ppy.sh/users/3046856), ::{ flag=CN }:: [\[GB\]Yuria](https://osu.ppy.sh/users/13092888), ::{ flag=CN }:: [\[GB\]yobrevelc]
Same with TGPGL's suggestion already committed.

2022-10-11 01:32 UTC, yobrevelc submitted a review, later dismissed

2022-10-11 11:17 UTC, TicClick submitted a review, later dismissed
I'm fine with the changes, but not familiar with the tournament jargon. will merge at evening/night if no one else does, assuming it's high priority

2022-10-11 12:10 UTC, RushFTK commented
Just update the prize part, nothing other changed.

2022-10-11 17:42 UTC, TicClick approved these changes

2022-10-11 17:46 UTC, merged