[FR] Update `Beatmap/Break`, `Beatmap/Online_offset`, and `Beatmap/Overall_difficulty`
ppy/osu-wiki pull request #8185
Opened 2022-10-10 18:41 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-12 13:08 UTC, Ganondorf-1 requested changes

2022-10-12 13:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Online_offset/fr.md
> +L'**online offset** est un décalage qui peut être appliqué à une [beatmap](/wiki/Beatmap) après son [classement](/wiki/Beatmap/Category#classée) initial. C'est généralement le cas lorsqu'une beatmap
```suggestion
L'**online offset** est un décalage qui peut être appliqué à une [beatmap](/wiki/Beatmap) après son [classement](/wiki/Beatmap/Category#classée) initial. C'est généralement le cas lorsqu'une beatmap a besoin de petits changements de timing pour s'aligner correctement avec la musique. Les valeurs d'online offset sont appliquées en plus des valeurs de l'[offset universel](/wiki/Client/Options/Universal_offset) et de l'[offset local](/wiki/Glossary/Local_song_offset) d'un joueur.
```

2022-10-12 13:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Online_offset/fr.md
> +![](img/beatmap-management-panel.jpg "Panneau de gestion de Beatmap, ancien site web")
```suggestion
![](img/beatmap-management-panel.jpg "Panneau de gestion de beatmap, ancien site web")
```

2022-10-12 13:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Online_offset/fr.md
> +![](img/beatmap-management-panel-new.png "Panneau de gestion de Beatmap, nouveau site web")
```suggestion
![](img/beatmap-management-panel-new.png "Panneau de gestion de beatmap, nouveau site web")
```

2022-10-12 13:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Online_offset/fr.md
> +L'online offset a été mise en place en septembre 2008[^changelog-add] pour la [Beatmap Appreciation Team](/wiki/Modding/Beatmap_Appreciation_Team) afin de permettre de corriger le timing d'une beatma
```suggestion
L'online offset a été mis en place en septembre 2008[^changelog-add] pour la [Beatmap Appreciation Team](/wiki/Modding/Beatmap_Appreciation_Team) afin de permettre de corriger le timing d'une beatmap sans avoir à la déclasser. Au fil du temps, il a été accessible aux membres de différentes équipes supervisant le processus de classement, comme la [Quality Assurance Team](/wiki/Modding/Quality_Assurance_Team) (QAT), la [Nomination Assessment Team](/wiki/People/The_Team/Nomination_Assessment_Team) (NAT) et la [Global Moderation Team](/wiki/People/The_Team/Global_Moderation_Team) en raison de permissions de groupe similaires.
```

2022-10-12 13:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Online_offset/fr.md
> +[^changelog-add]: [Forum de discussion par peppy (16/09/2008)](https://osu.ppy.sh/community/forums/posts/50194)
```suggestion
[^changelog-add]: [Post sur le forum par peppy (16/09/2008)](https://osu.ppy.sh/community/forums/posts/50194)
```

2022-10-12 13:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Overall_difficulty/fr.md
> +![](/wiki/shared/ODTable.png "Comparaison des fenêtres de hit pour différentes combinaisons d'OD et de modificateurs de jeu. Pour les mods Half Time et Double Time, les valeurs d'OD indiquées ne sont
```suggestion
![](/wiki/shared/ODTable.png "Comparaison des fenêtres de timing pour différentes combinaisons d'OD et de modificateurs de jeu. Pour les mods Half Time et Double Time, les valeurs d'OD indiquées ne sont valables que pour les 300, et seraient différentes pour les 100 et 50.")
```

2022-10-12 13:08 UTC, Ganondorf-1 commented on wiki/Beatmap/Overall_difficulty/fr.md
>    - fenêtre de hit
```suggestion
  - fenêtre de timing
```

2022-10-14 21:15 UTC, Ganondorf-1 approved these changes

2022-10-14 23:07 UTC, TicClick approved these changes

2022-10-14 23:08 UTC, merged