Update `Bancho(server)` and `BanchoBot`
ppy/osu-wiki pull request #8186
Opened 2022-10-10 21:31 UTC by LuiselprraYT

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-11 17:59 UTC, agatemosu commented on wiki/BanchoBot/es.md
> +`!help` Muestra una lista de todos los comandos de BanchoBot disponibles. Ejemplo de enviar este comando se muestra abajo:
```suggestion
`!help` Muestra una lista de todos los comandos de BanchoBot disponibles. A continuación se muestra un ejemplo de envío de este comando:
```

2022-10-11 17:59 UTC, agatemosu commented on wiki/BanchoBot/es.md
> +*Nota: El comando `!request` ya no es admitido por BanchoBot.*
```suggestion
*Aviso: El comando `!request` ya no es admitido por BanchoBot.*
```

2022-10-11 17:59 UTC, agatemosu commented on wiki/BanchoBot/es.md
> +`!stats` muestra las estadísticas y el estado del usuario introducido. El resultado dependerá del [modo de juego](/wiki/Game_mode) que haya jugado, aunque BanchoBot no mostrará que modo de juego prov
```suggestion
`!stats` muestra las estadísticas del juego del usuario ingresado y su estado actual. El resultado dependerá del [modo de juego](/wiki/Game_mode) que jugó por última vez el usuario ingresado, aunque BanchoBot no mostrará de qué modo de juego provienen las estadísticas. Si se le pide que muestre las estadísticas de un usuario que nunca ha jugado osu!, BanchoBot responderá con `User not found`, incluso si el usuario existe. A continuación se muestra un ejemplo de envío de este comando:
```

2022-10-11 17:59 UTC, agatemosu commented on wiki/BanchoBot/es.md
> +Ejemplos de enviar este comando se muestran abajo:
```suggestion
`!roll` escribe un número aleatorio del 1 al número seleccionado. Si no se especifica el número o se proporciona un argumento, el número máximo será 100. A continuación se muestran ejemplos de envío de este comando:
```

2022-10-11 17:59 UTC, agatemosu commented on wiki/BanchoBot/es.md
> +En total son 7 estados que se pueden mostrar por el comando `!stats`: Editing, Idle, Lobby, Modding, Multiplayer, Multiplaying y Playing. Ejemplo de enviar este comando de un usuario con un estado di
```suggestion
Hay un total de 7 estados que se pueden mostrar con el comando `!stats`: Editing, Idle, Lobby, Modding, Multiplayer, Multiplaying y Playing. A continuación se muestra un ejemplo de envío de este comando para un usuario con un estado disponible:
```

2022-10-11 18:03 UTC, agatemosu commented on wiki/BanchoBot/es.md
>  ```
@TicClick Can you edit this? I can't create a review
![image](https://user-images.githubusercontent.com/58957468/195165984-dbabb06c-4747-44e2-8136-0a6477fa1542.png)

2022-10-11 18:24 UTC, agatemosu commented on wiki/Bancho_(server)/es.md
> +*Para otros usos, vea [Bancho (desambiguación)](/wiki/Disambiguation/Bancho).*
```suggestion
*Para otros usos, véase [Bancho (desambiguación)](/wiki/Disambiguation/Bancho).*
```

2022-10-11 18:24 UTC, agatemosu commented on wiki/Bancho_(server)/es.md
> +[^score-upload-ref]: [Tweet de @osustatus (2019-07-30)](https://twitter.com/osustatus/status/1156092746685243392)
```suggestion
[^score-upload-ref]: [Tuit de @osustatus (2019-07-30)](https://twitter.com/osustatus/status/1156092746685243392)
```
https://dle.rae.es/tuit

2022-10-11 18:24 UTC, agatemosu commented on wiki/Bancho_(server)/es.md
> +En caso de mala conexión a Bancho, osu! avisa al jugador mostrando una cadena rota en la parte de abajo a la derecha de la pantalla.
```suggestion
En caso de mala conexión a Bancho, osu! avisa al jugador mostrando un icono de una cadena rota en la esquina inferior derecha de la pantalla.
```

2022-10-11 18:26 UTC, agatemosu requested changes

2022-10-11 18:26 UTC, agatemosu commented on wiki/BanchoBot/es.md
>  ```
Esto debería verse así:

\```
!faq \<entrada>
\```

\```
!faq list
\```

2022-10-13 03:49 UTC, LuiselprraYT commented on wiki/BanchoBot/es.md
> +BanchoBot (algunas veces llamado *Bancho*) es un bot de chat online creado para osu! que ayuda a la gente en el chat mostrando determinada información (Por ejemplo, conteo de jugadas, reintentos, etc
Would'nt it be better to leave "Conteo de jugadas" to match profile page?

2022-10-13 05:15 UTC, agatemosu commented on wiki/BanchoBot/es.md
> +BanchoBot (algunas veces llamado *Bancho*) es un bot de chat online creado para osu! que ayuda a la gente en el chat mostrando determinada información (Por ejemplo, conteo de jugadas, reintentos, etc
In the profile page it says "Play Count" not "Total Plays"

2022-11-12 01:55 UTC, TPGPL approved these changes

2022-11-12 01:55 UTC, merged