[FR] Add `Community/Discord_servers` and it subpage
ppy/osu-wiki pull request #8195
Opened 2022-10-12 06:36 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-12 13:25 UTC, Ganondorf-1 requested changes

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/fr.md
> +Page d'index pour tous les articles concernant les serveurs communautaires [Discord](https://discord.com/).
```suggestion
Page d'index pour tous les articles concernant les serveurs communautaires sur [Discord](https://discord.com/).
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +![Logo du serveur](img/logo.png "Le logo du serveur Discord des Chasseurs de Médailles, conçu par Tanza3D")
```suggestion
![Logo du serveur](img/logo.png "Le logo du serveur Discord Medal Hunters, conçu par Tanza3D")
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +| Lien alternatif d'invitation | <https://discord.gg/8qpNTs6> |
```suggestion
| Lien d'invitation alternatif | <https://discord.gg/8qpNTs6> |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +*Attention : Bien que nous vous encouragions à travailler ensemble pour trouver les médailles Hush-Hush, vous pouvez également les trouver par vous-même. Sachez que le serveur contient des solutions
```suggestion
*Attention : Bien que nous vous encouragions à travailler ensemble pour trouver les médailles Hush-Hush, vous êtes également encouragés à les trouver par vous-même. Sachez que le serveur contient des solutions pour les médailles Hush-Hush*.
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +Un grand nombre de chasseurs de médailles travaillent ensemble afin de trouver des solutions pour chaque nouvelle médaille Hush-Hush ajoutée au jeu. Chaque fois que de nouvelles médailles sont publié
```suggestion
Un grand nombre de chasseurs de médailles travaillent ensemble afin de trouver des solutions pour chaque nouvelle médaille Hush-Hush ajoutée au jeu. Chaque fois que de nouvelles médailles sont ajoutées, elles sont annoncées par l'un des membres du staff du serveur, des fils de discussion sont créés pour chaque médaille et les joueurs travaillent ensemble pour trouver des solutions.
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +| Role | Utilisateur (Identifiant Discord) |
```suggestion
| Rôle | Utilisateur (Identifiant Discord) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +| Community manager et administrateurs du serveur | ::{ flag=UA }:: [MegaMix_Craft](https://osu.ppy.sh/users/18152711) (MegaMix_Craft#1151), ::{ flag=GB }:: [chromb](https://osu.ppy.sh/users/10238680
```suggestion
| Community managers et administrateurs du serveur | ::{ flag=UA }:: [MegaMix_Craft](https://osu.ppy.sh/users/18152711) (MegaMix_Craft#1151), ::{ flag=GB }:: [chromb](https://osu.ppy.sh/users/10238680) (chromb#4528), ::{ flag=CA }:: [Remyria](https://osu.ppy.sh/users/1699875) (Remyria#0001) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +## Verification
```suggestion
## Vérification
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +Tout le monde peut envoyer des messages dans le serveur par défaut, mais en s'authentifiant avec un compte osu! à l'aide du bot Osekai Authenticator, les membres sont autorisés à envoyer des images e
```suggestion
Tout le monde peut envoyer des messages dans le serveur par défaut, mais en s'authentifiant avec un compte osu! à l'aide du bot Osekai Authenticator, les membres sont autorisés à envoyer des images et obtiennent un pourcentage de réussite des médailles automatiquement ajouté à côté de leur pseudo.
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +![Pseudo avec pourcentage d'achèvement de la médaille](img/medals_percentage.png "Les pseudonymes sont automatiquement modifiés pour indiquer le nombre de médailles obtenues par chaque utilisateur.")
```suggestion
![Pseudo avec pourcentage de réussite des médilles](img/medals_percentage.png "Les pseudonymes sont automatiquement modifiés pour indiquer le nombre de médailles obtenues par chaque utilisateur.")
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +![Logo du serveur](img/logo.png "Le logo du serveur Discord de la osu! University, conçu by joiechii")
```suggestion
![Logo du serveur](img/logo.png "Le logo du serveur Discord de l'osu! University, conçu by joiechii")
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| Chaîne Youtube | [osu! University](https://www.youtube.com/c/osuUniversity) |
```suggestion
| Chaîne YouTube | [osu! University](https://www.youtube.com/c/osuUniversity) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| Role | Utilisateur (Identifiant Discord) |
```suggestion
| Rôle | Utilisateur (Identifiant Discord) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 09-08-2021/13-08-2021 | Semaine d'interview de top player (contrôle des nerfs) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zCEiwKnHwliUGbtjE4hI0MG) |
```suggestion
| 09/08/2021 - 13/08/2021 | Semaine d'interview de top player (contrôle du stress) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zCEiwKnHwliUGbtjE4hI0MG) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 30-08-2021/03-09-2021 | Semaine d'interview de top player (blocage mental) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zD4GdoGOympAkhhSIytKect) |
```suggestion
| 30/08/2021 - 03/09/2021 | Semaine d'interview de top player (mindblock) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zD4GdoGOympAkhhSIytKect) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 27-09-2021/01-10-2021 | Semaine d'interview de top player (haute AR) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zDGmnvGdJJLGei0iLvmvtZg) |
```suggestion
| 27/09/2021 - 01/10/2021 | Semaine d'interview de top player (AR élevé) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zDGmnvGdJJLGei0iLvmvtZg) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 11-10-2021/15-10-2021 | Semaine d'interview de top player (stratégie de tournois) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zBFW_YpeW_F_lDQRO2J9IOl) |
```suggestion
| 11/10/2021 - 15/10/2021 | Semaine d'interview de top player (stratégie en tournoi) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zBFW_YpeW_F_lDQRO2J9IOl) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 01-02-2022/01-03-2022 | Étude sur l'endurance | [Document d'information](https://docs.google.com/document/d/14yY4_9E6q8kbOwPGtvWG7z5MCQsQGrX168hAOZFAK_M/edit), [document de résultats](https://docs.
```suggestion
| 01/02/2022 - 01/03/2022 | Étude sur l'endurance | [Document d'informations](https://docs.google.com/document/d/14yY4_9E6q8kbOwPGtvWG7z5MCQsQGrX168hAOZFAK_M/edit), [document de résultats](https://docs.google.com/document/d/1aJmRXZTFCR2FirXQHC5f-TTYUCimpBPWGBg-bZPb_YE/edit), [vidéo de discussion des résultats](https://www.youtube.com/watch?v=BINGyy43T4U) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 20-02-2022 | [osu! community meeting](/wiki/Community/osu!_community_meetings) #11 | [VOD YouTube](https://www.youtube.com/watch?v=d66pU5lsHvE), [article de résumé](https://osu.ppy.sh/home/news/202
```suggestion
| 20/02/2022 | [osu! community meeting](/wiki/Community/osu!_community_meetings) #11 | [VOD YouTube](https://www.youtube.com/watch?v=d66pU5lsHvE), [article récapitulatif](https://osu.ppy.sh/home/news/2022-03-07-community-meetings-recap) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 20-05-2022/22-05-2022 | [osu! Talk Event: Overcoming Obstacles](/wiki/Community/osu!_Talk_Event/Overcoming_Obstacles) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zC5_Go2es
```suggestion
| 20/05/2022 - 22/05/2022 | [osu! Talk Event: Overcoming Obstacles](/wiki/Community/osu!_Talk_Event/Overcoming_Obstacles) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zC5_Go2esnB7_64Egv5HmSL) |
```

2022-10-12 13:25 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 01-10-2022/31-10-2022 | osu! Improvement Month | [Post du forum](https://osu.ppy.sh/community/forums/topics/1649135), [playlist des interviews des top players](https://www.youtube.com/playlist?list
```suggestion
| 01/10/2022 - 31/10/2022 | osu! Improvement Month | [Post du forum](https://osu.ppy.sh/community/forums/topics/1649135), [playlist des interviews des top players](https://www.youtube.com/playlist?list=PL_QhgSQeB2zDRSd-xm9lQrkmGY2wJTXvH) |
```

2022-10-14 21:18 UTC, Ganondorf-1 requested changes

2022-10-14 21:18 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/fr.md
> +**osu! Medal Hunters** est le serveur [Discord](https://discord.com) principal utilisé par la communauté des chasseurs de médailles, où les gens discutent des [médailles](/wiki/Medals) et de leurs [s
```suggestion
**osu! Medal Hunters** est le serveur [Discord](https://discord.com) principal utilisé par la communauté des chasseurs de médailles, où les joueurs discutent des [médailles](/wiki/Medals) et de leurs [solutions](/wiki/Medals/Unlock_requirements).
```

2022-10-14 21:18 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 30/08/2021 - 03/09/2021 | Semaine d'interview de top player (mondblock) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zD4GdoGOympAkhhSIytKect) |
```suggestion
| 30/08/2021 - 03/09/2021 | Semaine d'interview de top player (mindblock) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zD4GdoGOympAkhhSIytKect) |
```

2022-10-14 21:18 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 11/10/2021 - 15/10/2021 | Semaine d'interview de top player (stratégie en tournois) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zBFW_YpeW_F_lDQRO2J9IOl) |
```suggestion
| 11/10/2021 - 15/10/2021 | Semaine d'interview de top player (stratégie en tournoi) | [Playlist YouTube](https://www.youtube.com/playlist?list=PL_QhgSQeB2zBFW_YpeW_F_lDQRO2J9IOl) |
```

2022-10-14 21:18 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +| 08/10/2022 - 30/10/2022 | Tournois King of the Hill | [Post du forum](https://osu.ppy.sh/community/forums/topics/1649138) |
```suggestion
| 08/10/2022 - 30/10/2022 | Tournoi King of the Hill | [Post du forum](https://osu.ppy.sh/community/forums/topics/1649138) |
```

2022-10-15 16:52 UTC, Ganondorf-1 requested changes

2022-10-15 16:52 UTC, Ganondorf-1 commented on wiki/Community/Discord_servers/osu!_University/fr.md
> +**osu! University** est un serveur communautaire [Discord](https://discord.com) axé sur les discussions relatives à l'amélioration, principalement dans le mode de jeu [osu!](/wiki/Game_mode/osu!). Il
```suggestion
**osu! University** est un serveur [Discord](https://discord.com) communautaire axé sur les discussions relatives à l'amélioration, principalement dans le mode de jeu [osu!](/wiki/Game_mode/osu!). Il accueille régulièrement divers événements tels que des interviews de joueurs de haut niveau, des [tournois](/wiki/Tournaments) et des études sur l'amélioration. Il est également connu pour ses services de coaching payants.
```

2022-10-15 18:57 UTC, Ganondorf-1 approved these changes

2022-10-15 22:01 UTC, TicClick approved these changes

2022-10-15 22:04 UTC, merged