[RU] Add `Discord Servers` and `osu! Medal Hunters` articles
ppy/osu-wiki pull request #8214
Opened 2022-10-15 20:37 UTC by minusQuantumNeko

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-20 21:54 UTC, TicClick requested changes

2022-10-20 21:54 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +![Server logo](img/logo.png "Лого Discord-сервера osu! Medal Hunters, созданная Tanza3D")
```suggestion
![Server logo](img/logo.png "Логотип Discord-сервера osu! Medal Hunters, созданный Tanza3D")
```

2022-10-20 21:54 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +*Примечание: В то время как работа вместе для нахождения медалей группы Hush-Hush поощряется, их самостоятельное нахождение также поощрено. Имейте в виду, что на сервере имеются их решения.*
```suggestion
*Примечание: хотя медали Hush-Hush рассчитаны на совместное разгадывание, их также можно открывать и в одиночку. Имейте в виду, что на сервере имеются их решения.*
```

2022-10-20 21:54 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +**osu! Medal Hunters** является основным [Discord](https://discord.com)-сервером используемым сообществом охотников за медалями, где люди обсуждают [медали](/wiki/Medals) и [их решения](/wiki/Medals/
```suggestion
**osu! Medal Hunters** — основной [Discord](https://discord.com)-сервер сообщества охотников за медалями, где игроки обсуждают [медали](/wiki/Medals) и [их решения](/wiki/Medals/Unlock_requirements).
```

2022-10-20 21:54 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +| Менеджер сообщества & администратор сервера | ::{ flag=UA }:: [MegaMix_Craft](https://osu.ppy.sh/users/18152711) (MegaMix_Craft#1151), ::{ flag=GB }:: [chromb](https://osu.ppy.sh/users/10238680) (c
```suggestion
| Менеджер сообщества и администратор сервера | ::{ flag=UA }:: [MegaMix_Craft](https://osu.ppy.sh/users/18152711) (MegaMix_Craft#1151), ::{ flag=GB }:: [chromb](https://osu.ppy.sh/users/10238680) (chromb#4528), ::{ flag=CA }:: [Remyria](https://osu.ppy.sh/users/1699875) (Remyria#0001) |
```

2022-10-20 21:54 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +Кто угодно может отправлять сообщения на сервер по умолчанию, но авторизовавшись с помощью аккаунта osu! используя бота Osekai Authenticator, участники получают возможность отправлять картинки и полу
```suggestion
Все пользователи по умолчанию могут общаться на сервере. Если вы подтвердите свой аккаунт osu! через бота Osekai Authenticator, то сможете отправлять изображения, а около вашего ника будет показан процент открытия всех медалей, обновляемый автоматически.
```

2022-10-21 06:44 UTC, minusQuantumNeko commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +*Примечание: В то время как работа вместе для нахождения медалей группы Hush-Hush поощряется, их самостоятельное нахождение также поощрено. Имейте в виду, что на сервере имеются их решения.*
@TicClick Не совсем согласен с формулировкой, Hush-Hush медали [не рассчитаны именно на совместное разгадывание](https://osu.ppy.sh/home/news/2016-08-17-new-hush-hush-medals).

2022-10-21 07:56 UTC, minusQuantumNeko commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +![Никнейм с процентом полученных медалей](img/medals_percentage.png "Никнеймы автоматически модифицируются чтобы показать как много медалей получил каждый пользователь.")
А почему нельзя оставить "никнейм"? Одно и то же по сути

2022-10-21 07:56 UTC, minusQuantumNeko commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +![Аутентификационное сообщение от бота Osekai Authenticator](img/authentication_example.png "При присоединении к серверу, Osekai Authenticator отправит приватное сообщение аутентификации.")
Я всё-таки считаю что "присоединение к серверу" будет более правильно, как минимум потому что [в самом дискорде так](https://imgur.com/a/OlsSPGX)

2022-10-21 19:53 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +*Примечание: В то время как работа вместе для нахождения медалей группы Hush-Hush поощряется, их самостоятельное нахождение также поощрено. Имейте в виду, что на сервере имеются их решения.*
исправил, как тебе теперь?

2022-10-21 19:54 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +![Аутентификационное сообщение от бота Osekai Authenticator](img/authentication_example.png "При присоединении к серверу, Osekai Authenticator отправит приватное сообщение аутентификации.")
пожалуй. обновил предложение

2022-10-21 19:54 UTC, TicClick commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +![Никнейм с процентом полученных медалей](img/medals_percentage.png "Никнеймы автоматически модифицируются чтобы показать как много медалей получил каждый пользователь.")
мне не принципиально, предлагаю то, как сам пишу. главное, чтобы остальная формулировка осталась

2022-10-21 20:34 UTC, minusQuantumNeko commented on wiki/Community/Discord_servers/osu!_Medal_Hunters/ru.md
> +*Примечание: В то время как работа вместе для нахождения медалей группы Hush-Hush поощряется, их самостоятельное нахождение также поощрено. Имейте в виду, что на сервере имеются их решения.*
Теперь всё отлично

2022-10-21 22:06 UTC, TicClick approved these changes

2022-10-21 22:07 UTC, merged