[FR] Update `Beatmap_Spotlights` and add `Beatmap_Spotlights/Chart_Assembly_Team`
ppy/osu-wiki pull request #8243
Opened 2022-10-21 20:07 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-22 11:36 UTC, Ganondorf-1 requested changes

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Chart_Assembly_Team/fr.md
> +La **Chart Assembly Team** (souvent appelée ***CAT***) était un groupe d'utilisateurs dévoués formé en août 2011[^cat-birth] et responsable de la compilation de beatmaps mensuels et thématiques pour
```suggestion
La **Chart Assembly Team** (souvent appelée ***CAT***) était un groupe d'utilisateurs dévoués formé en août 2011[^cat-birth] et responsable de la compilation de beatmaps mensuelles et thématiques pour les Ranking Charts (renommés par la suite en [Beatmap Spotlights](/wiki/Beatmap_Spotlights)). Initialement composée des membres de la [Beatmap Appreciation Team](/wiki/Modding/Beatmap_Appreciation_Team) et de la [Mapping Assistance Team](/wiki/Modding/Mapping_Assistance_Team), elle a été élargie à un ensemble de joueurs et de mappeurs renommés afin d'accroître la diversité.
```

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Chart_Assembly_Team/fr.md
> +Over time, there have been several attempts to revitalise the team and increase quality of the Ranking Charts, including two application rounds in 2013[^cat-recruitment-2013] and 2014[^cat-recruitmen
```suggestion
```

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Chart_Assembly_Team/fr.md
> +
```suggestion
```

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Chart_Assembly_Team/fr.md
> +Le 18 mars 2015, la CAT a été dissoute[^cat-death] en raison de la refonte complète des Ranking Charts, qui comprenait la sélection des maps par la communauté.
```suggestion
Le 18 mars 2015, la CAT a été dissoute[^cat-death] en raison de la refonte complète des Ranking Charts, qui comprenait la sélection des beatmaps par la communauté.
```

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Chart_Assembly_Team/fr.md
> +[^cat-death]: [News post par Loctav (19/03/2015) "February 2015 Monthly Ranking Charts - New Season!"](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-season)
```suggestion
[^cat-death]: [Article de news par Loctav (19/03/2015) "February 2015 Monthly Ranking Charts - New Season!"](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-season)
```

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +Nommé à l'origine "Ranking Charts" et lancé en octobre 2009[^charts-09-oct] [^charts-09-nov] par ::{ flag=AU }:: [peppy](https://osu.ppy.sh/users/2) et ::{ flag=US }:: [Cyclone](https://osu.ppy.sh/us
```suggestion
Nommé à l'origine "Ranking Charts" et lancé en octobre 2009[^charts-09-oct] [^charts-09-nov] par ::{ flag=AU }:: [peppy](https://osu.ppy.sh/users/2) et ::{ flag=US }:: [Cyclone](https://osu.ppy.sh/users/18589), le projet visait à mettre en avant les meilleures beatmaps d'un mois ou d'une année[^charts-10-jan] en laissant la [Beatmap Appreciation Team](/wiki/Modding/Beatmap_Appreciation_Team) et la [Mapping Assistance Team](/wiki/Modding/Mapping_Assistance_Team) nommer et voter pour les candidats les plus appropriés. En septembre 2011, des charts pour osu!taiko et osu!catch sont apparus [^charts-11-per-mode].
```

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +En janvier 2014, le navigateur charts a été ajouté au client osu!,[^charts-in-osu-14-jan] et en juin 2014, plusieurs joueurs renommés ont été recrutés dans la [Chart Assembly Team](/wiki/Beatmap_Spot
```suggestion
En janvier 2014, le navigateur charts a été ajouté au client osu!,[^charts-in-osu-14-jan] et en juin 2014, plusieurs joueurs renommés ont été recrutés dans la [Chart Assembly Team](/wiki/Beatmap_Spotlights/Chart_Assembly_Team).[^charts-cat-recruitment-14-jun] En mars 2015, le projet a changé de son design originel de nomination et de vote en ayant des membres renommés de la communauté qui sélectionnent seuls une liste de sets de beatmaps qu'ils recommandent.[^charts-curated-15-mar] En septembre 2016, le système de sélection a été en grande partie inversé[^charts-reverted-16-sep] et a mis la [Quality Assurance Team](/wiki/Modding/Quality_Assurance_Team) en charge de la sélection des beatmaps les plus remarquables.
```

2022-10-22 11:36 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +Renommé Beatmap Spotlights en mars 2017,[^charts-renamed-into-spotlights] le système lui-même est resté globalement cohérent tout en ajoutant des récompenses supplémentaires comme des médailles et en
```suggestion
Renommé Beatmap Spotlights en mars 2017,[^charts-renamed-into-spotlights] le système lui-même a globalement continué de fonctionner de la même manière tout en ajoutant des récompenses supplémentaires comme des médailles et en améliorant encore la présentation des Beatmap Spotlights. Lors d'une refonte interne de la Quality Assurance Team, la responsabilité du projet a été réattribuée à ::{ flag=HU }:: [Kurokami](https://osu.ppy.sh/users/260933) et a réimplanté une équipe de sélection basée sur la communauté. En novembre 2018, la fréquence des Spotlights a été modifiée pour devenir un cycle de publication saisonnier.[^spotlights-seasonal] En mars 2020, ::{ flag=DE }:: [Loctav](https://osu.ppy.sh/users/71366) a repris la direction du projet avec Kurokami, en lui donnant une nouvelle forme et en constituant une nouvelle équipe de curateurs osu!.[^spotlights-reworked-20-june]
```

2022-10-24 10:58 UTC, Ganondorf-1 requested changes

2022-10-24 10:58 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +1. Les beatmaps sont sélectionnées par les curateurs de leur modes de jeu respectif pour la durée d'une saison.
```suggestion
1. Les beatmaps sont sélectionnées par les curateurs de leur mode de jeu respectif pour la durée d'une saison.
```

2022-10-24 10:58 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/Chart_Assembly_Team/fr.md
> +[^cat-death]: [Article de news par Loctav (19/03/2015) "February 2015 Monthly Ranking Charts - New Season!"](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-season)
```suggestion
[^cat-death]: [Article de news par Loctav (19/03/2015) "February 2015 Monthly Ranking Charts - New Season!"](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-season)

```

2022-11-02 13:43 UTC, Ganondorf-1 requested changes
Can be merged once this is applied

2022-11-02 13:43 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +[^charts-curated-15-mar]: [News post par Loctav (18/03/2015) "February 2015 Monthly Ranking Charts - New Season!"](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-sea
```suggestion
[^charts-curated-15-mar]: [Article de news par Loctav (18/03/2015) "February 2015 Monthly Ranking Charts - New Season!"](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-season)
```

2022-11-02 13:43 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +[^charts-reverted-16-sep]: [News post par OnosakiHito (17/09/2016) "July 2016 Ranking Charts - Changes"](https://osu.ppy.sh/home/news/2016-09-17-july-2016-ranking-charts-changes)
```suggestion
[^charts-reverted-16-sep]: [Article de news par OnosakiHito (17/09/2016) "July 2016 Ranking Charts - Changes"](https://osu.ppy.sh/home/news/2016-09-17-july-2016-ranking-charts-changes)
```

2022-11-02 13:43 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +[^charts-renamed-into-spotlights]: [News post par OnosakiHito (18/03/2017) "Introducing to you: Spotlights"](https://osu.ppy.sh/home/news/2017-03-18-introducing-to-you-spotlights)
```suggestion
[^charts-renamed-into-spotlights]: [Article de news par OnosakiHito (18/03/2017) "Introducing to you: Spotlights"](https://osu.ppy.sh/home/news/2017-03-18-introducing-to-you-spotlights)
```

2022-11-02 13:43 UTC, Ganondorf-1 commented on wiki/Beatmap_Spotlights/fr.md
> +[^spotlights-seasonal]: [News post par Kurokami (01/11/2018) "Seasonal Spotlights: Summer 2018"](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018)
```suggestion
[^spotlights-seasonal]: [Article de news par Kurokami (01/11/2018) "Seasonal Spotlights: Summer 2018"](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018)
```

2022-11-02 15:19 UTC, TicClick approved these changes

2022-11-02 15:21 UTC, merged