[ZH/others] Beatmap_Spotlights
ppy/osu-wiki pull request #8256
Opened 2022-10-25 08:48 UTC by Kotoki1337

- `Beatmap_Spotlights/Seasons` is all up-to-date but I don't know why they have outdated tags.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-10-29 11:14 UTC, YumeMuzi requested changes
Not sure you should continue to modify the rest paragraph

2022-10-29 11:14 UTC, YumeMuzi commented on wiki/Beatmap_Spotlights/zh.md
>  3. 最终所选的谱面可作为对整个 osu! 社区的推荐，并使用唯一的 *Spotlights* 标签标记。
```suggestion
3. 选定的谱面会推荐到整个 osu! 社区，并标上独一无二的 *Spotlights* 标签。
```

2022-10-29 11:14 UTC, YumeMuzi commented on wiki/Beatmap_Spotlights/zh.md
> +该项目最初由 ::{ flag=US }:: [Cyclone](https://osu.ppy.sh/users/18589) 和 ::{ flag=AU }:: [peppy](https://osu.ppy.sh/users/2) 在 2009 年 10 月[^charts-09-oct] [^charts-09-nov]提出，原名 “Ranking Charts”。该项目旨在让 [BAT
```suggestion
该项目最初由 ::{ flag=US }:: [Cyclone](https://osu.ppy.sh/users/18589) 和 ::{ flag=AU }:: [peppy](https://osu.ppy.sh/users/2) 在 2009 年 10 月[^charts-09-oct] [^charts-09-nov]提出，原名 “Ranking Charts”。该项目旨在让 [BAT](/wiki/Modding/Beatmap_Appreciation_Team) 和 [MAT](/wiki/Modding/Mapping_Assistance_Team) 提名并投票选出展示为期一个月或一年[^charts-10-jan]的最佳谱面。2011 年 9 月, osu!taiko 和 osu!catch 也启动了类似的项目[^charts-11-per-mode]。
```

2022-10-29 11:14 UTC, YumeMuzi commented on wiki/Beatmap_Spotlights/zh.md
> +在 2017 年 3 月改名为 [Beatmap Spotlights](https://osu.ppy.sh/home/news/2017-03-18-introducing-to-you-spotlights)[^charts-renamed-into-spotlights]。该系统本身保持了基本的连贯性，同时增加了诸如成就之类的奖励，并进一步增强了 Beatmap Spotlights 的
```suggestion
在 2017 年 3 月改名为 [Beatmap Spotlights](https://osu.ppy.sh/home/news/2017-03-18-introducing-to-you-spotlights)[^charts-renamed-into-spotlights]。该系统本身保持了基本的连贯性，同时增加了诸如成就之类的奖励，并进一步增强了 Beatmap Spotlights 的显示效果。在 QAT 休整期间， ::{ flag=HU }:: [Kurokami](https://osu.ppy.sh/users/260933) 重新任职为该项目的负责人，并重组了一个基于社区的谱面选择团队。2018 年 11 月，月赛的频率更改为季节性[^spotlights-seasonal]。2020 年 3 月，::{ flag=DE }:: [Loctav](https://osu.ppy.sh/users/71366) 和 Kurokami 重任项目负责人、重新设计项目结构、并新建了名为 osu! 策展人的团队[^spotlights-reworked-20-june]。
```

2022-10-29 11:14 UTC, YumeMuzi commented on wiki/Beatmap_Spotlights/zh.md
> +2014 年 1 月，月赛浏览器被添加到 osu! 客户端当中[^charts-in-osu-14-jan]，随后的 2014 年 6 月，几位著名玩家被招募进入了 [CAT](/wiki/Beatmap_Spotlights/Chart_Assembly_Team)[^charts-cat-recruitment-14-jun]。从 2015 年 3 月开始，该项目从最初的提名和投票转变为让[
```suggestion
2014 年 1 月，月赛浏览器被添加到 osu! 客户端当中[^charts-in-osu-14-jan]，随后的同年 6 月，几位著名玩家被招募进入了 [CAT](/wiki/Beatmap_Spotlights/Chart_Assembly_Team)[^charts-cat-recruitment-14-jun]。从 2015 年 3 月开始，该项目从最初的提名和投票，转变为让[知名社区成员逐个选择他们推荐的谱面](https://osu.ppy.sh/home/news/2015-03-18-february-2015-monthly-ranking-charts-new-season)[^charts-curated-15-mar]。在 2016 年 9 月，提名系统已大体恢复[^charts-reverted-16-sep]。此时，[QAT](/wiki/Modding/Quality_Assurance_Team) 将负责选择最值得关注的谱面。
```

2022-10-31 13:33 UTC, YumeMuzi commented on wiki/Beatmap_Spotlights/zh.md
> +   - 在所有谱面中，应有 12 张谱面在 Expert 难度内。
```suggestion
   - 所有谱面中，应至少包含 6 个 Hard 难度。
   - 所有谱面中，应至少包含 9 个 Insane 难度。
   - 所有谱面中，应至少包含 12 个 Expert 难度。
```

2022-10-31 17:45 UTC, TicClick requested changes

2022-10-31 17:45 UTC, TicClick commented on wiki/Beatmap_Spotlights/zh.md
> +[^spotlights-reworked-20-june]: [Forum thread by Loctav (2020-07-06) "Beatmap Spotlights (Summer 2020) - Discussion Thread"](https://osu.ppy.sh/community/forums/topics/1101170)
references need to be translated, too (except for the thread and article titles). example: https://github.com/ppy/osu-wiki/pull/8265

2022-11-11 17:35 UTC, YumeMuzi approved these changes
seems fine

2022-11-11 19:50 UTC, TicClick approved these changes

2022-11-11 19:51 UTC, merged