Update drafting result & Regular Stage 1 schedule for `GBC 2022 Autumn`
ppy/osu-wiki pull request #8258
Opened 2022-10-26 12:07 UTC by RushFTK

## Self-check

Also fixed some mirror logic issue for pages.

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2022-10-26 14:16 UTC, Walavouchey requested changes

2022-10-26 14:16 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| # | Teams | Members |
```suggestion
| # | Team | Members |
```

2022-10-26 14:16 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +| --: | :-: | :-- |
```suggestion
| :-: | :-- | :-- |
```

2022-10-26 14:16 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/en.md
> +   - Each player could only request to rematch **one beatmap** in a match with this rule. This rule should not be abused, referee has right to deny the request if he think it is abused.
```suggestion
   - Each player may only request to rematch **one beatmap** in a match with this rule. This rule should not be abused; the referee has the right to deny the request at their own discretion.
```

2022-10-26 14:16 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2022_Autumn/zh.md
> +| --: | :-: | :-- |
```suggestion
| :-: | :-- | :-- |
```

2022-10-26 14:56 UTC, yobrevelc approved these changes

2022-10-26 14:57 UTC, EdwardTsui approved these changes
Approved

2022-10-27 02:21 UTC, Walavouchey approved these changes

2022-10-27 02:22 UTC, merged