Add 'MCNC4K2022' article
ppy/osu-wiki pull request #8290
Opened 2022-11-03 11:45 UTC by xz1z1z1z1z

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-11-03 12:26 UTC, fajar13k reviewed
Some piece

2022-11-03 12:26 UTC, fajar13k commented on wiki/Tournaments/MCNC/4K2022/en.md
> +### Qualifiers
```suggestion
### Qualifiers
```
Inconsistent naming, if we're sticking with Line 20, then change it to Qualifier stage,
If we're sticking to Qualifiers, change the Line 20 one.

2022-11-16 07:06 UTC, RushFTK requested changes
Suggestion for fix CI issues

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Registration phase | 2022-05-15/2022-06-12
```suggestion
| Registration phase | 2022-05-15/2022-06-12 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Qualifiers | 2022-06-26/2022-07-03
```suggestion
| Qualifiers | 2022-06-26/2022-07-03 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Round of 64 | 2022-07-09/2022-07-10
```suggestion
| Round of 64 | 2022-07-09/2022-07-10 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Round of 32 | 2022-07-16/2022-07-17
```suggestion
| Round of 32 | 2022-07-16/2022-07-17 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Round of 16 | 2022-07-23/2022-07-24
```suggestion
| Round of 16 | 2022-07-23/2022-07-24 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Quarterfinals | 2022-07-30/2022-07-31
```suggestion
| Quarterfinals | 2022-07-30/2022-07-31 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Semifinals | 2022-08-06/2022-08-07
```suggestion
| Semifinals | 2022-08-06/2022-08-07 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Finals | 2022-08-13/2022-08-14
```suggestion
| Finals | 2022-08-13/2022-08-14 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| Grand Finals | 2022-08-20/2022-08-21
```suggestion
| Grand Finals | 2022-08-20/2022-08-21 |
```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +
```suggestion

### Qualifier instructions

```

2022-11-16 07:06 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +
这些可以直接修正后面的github报错

2022-11-18 01:43 UTC, RushFTK requested changes
Try fix github CIs

2022-11-18 01:43 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +3. If player need to make a temporary change after decide the game time. Rescheduling can only be considered with the consent of both players, and the scheduled time must be every Thursday before.
```suggestion
3. If player need to make a temporary change after decide the game time. Rescheduling can only be considered with the consent of both players, and the scheduled time must be every Thursday before.

```

2022-11-18 01:43 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +### Mappool instructions
```suggestion
### Mappool instructions

```

2022-11-18 01:43 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +### Scheduling instructions
```suggestion
### Scheduling instructions

```

2022-11-18 01:43 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +  2. [Camellia - Dans la mer de son (Toaph Daddy) \[Diabolos x1.1\]](https://osu.ppy.sh/beatmapsets/1443348#mania/2968916) https://osu.ppy.sh/beatmapsets/1338625#mania/2772922)
```suggestion
  2. [Camellia - Dans la mer de son (Toaph Daddy) \[Diabolos x1.1\]](https://osu.ppy.sh/beatmapsets/1443348#mania/2968916)
```

2022-11-18 01:43 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +  4. [ F-777 - Ultra Violet (chxu) \[Hyperbolic x1.05\]](https://osu.ppy.sh/beatmapsets/1687224#mania/3448235)
```suggestion
  4. [F-777 - Ultra Violet (chxu) \[Hyperbolic x1.05\]](https://osu.ppy.sh/beatmapsets/1687224#mania/3448235)
```
我实在看不出来这里为啥会报错，只能蒙一个了

2022-11-18 01:43 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +| **Kuiiiiteeee** | **6** | 1 | \[Crz\]Riko | [#1](https://osu.ppy.sh/community/matches/102470373) |
```suggestion
| **Kuiiiiteeee** | **6** | 1 | \[Crz\]Riko | [#1](https://osu.ppy.sh/community/matches/102470373) |
```

2022-11-21 06:44 UTC, RushFTK commented on wiki/Tournaments/MCNC/4K2022/en.md
> +
```suggestion
3. If player need to make a temporary change after decide the game time. Rescheduling can only be considered with the consent of both players, and the scheduled time must be every Thursday before.
```
我吐了，我刚才看了看其他的文件确认了一下，现在md文件最后一行又不用留空白行了，还得把635行删掉。。。

2022-11-21 06:59 UTC, xz1z1z1z1z commented on wiki/Tournaments/MCNC/4K2022/en.md
> +
Done

2022-11-21 07:05 UTC, RushFTK commented
注意现在的PR报错， 文件本身应该没问题了
```

Error: You have edited some original articles (en.md), but did not outdate their translations:
* wiki/Tournaments/de.md
* wiki/Tournaments/fr.md

If your changes DON'T NEED to be added to the translations, add SKIP_OUTDATED_CHECK anywhere in the description of your pull request.
Otherwise, add the following to each article's front matter (https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#front-matter):

---
outdated_since: edb1fdc556e783ed74a[27](https://github.com/ppy/osu-wiki/actions/runs/3512155485/jobs/5883577228#step:13:28)8b8f5c6ca44161ba995
outdated_translation: true
---
Error: Process completed with exit code 1.
```

2022-11-26 00:50 UTC, TPGPL approved these changes

2022-11-26 00:50 UTC, merged