[ID] Add `Forum`
ppy/osu-wiki pull request #8319
Opened 2022-11-10 03:58 UTC by Nivalyx

Indonesian translation for the `Forum` (http://osu.ppy.sh/wiki/en/Community/Forum) wiki article.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-11-10 07:47 UTC, hikikuman requested changes
it might be good to add `forum` and `sub-forum` to the tags in id.md and change the Language Specific link from https://osu.ppy.sh/community/forums#forum-23 to https://osu.ppy.sh/community/forums/23

2022-11-10 07:47 UTC, hikikuman commented on wiki/Community/Forum/id.md
> +Masing-masing forum mengandung berbagai macam **topik** (atau yang juga dikenal sebagai *utas*) serta kategori spesifik di dalamnya yang disebut dengan **sub-forum**. Hampir seluruh forum mewajibkan
```suggestion
Masing-masing forum mengandung berbagai macam **topik** (atau yang juga dikenal sebagai *utas*) serta kategori spesifik di dalamnya yang disebut dengan **sub-forum**. Hampir seluruh forum mewajibkan penggunaan bahasa Inggris, namun terdapat juga [forum khusus bahasa tertentu](https://osu.ppy.sh/community/forums#forum-23) bagi komunitas lokal dengan basis pengguna yang aktif.
```

2022-11-10 07:47 UTC, hikikuman commented on wiki/Community/Forum/id.md
> +- [Modding Queues](/wiki/Community/Forum/Modding_Queues): forum untuk mengajukan kajian beatmap dari mapper dan modder lain.
```suggestion
- [Modding Queues](/wiki/Community/Forum/Modding_Queues): forum untuk mengajukan umpan balik (*feedback*) beatmap dari mapper dan modder lain.
```
Penggunaan kata `kajian` terlalu sulit dicerna dan kurang umum di dunia mapping/modding, gimana kalo pake `umpan balik` sebagai gantinya? Soalnya biasanya kita pakai kata `feedback` sebagai kaitan aktivitas modding sebuah beatmap.

2022-11-10 07:47 UTC, hikikuman commented on wiki/Community/Forum/id.md
> +Di samping itu, terdapat juga beberapa forum rahasia seperti Abandoned Wasteland lainnya yang ditujukan untuk keperluan teknis atau manajemen.
```suggestion
Di samping itu, terdapat juga beberapa forum rahasia yang sama seperti Abandoned Wasteland, yang ditujukan untuk keperluan teknis atau manajemen.
```

2022-11-10 07:47 UTC, hikikuman commented on wiki/Community/Forum/id.md
> +[**Forum osu!**](https://osu.ppy.sh/community/forums) merupakan sarana percakapan di mana seluruh pesan yang masuk dikelompokkan berdasarkan subjeknya masing-masing. Tidak seperti [osu! chat](/wiki/C
```suggestion
[**Forum osu!**](https://osu.ppy.sh/community/forums) merupakan sarana percakapan di mana seluruh pesan yang masuk dikelompokkan berdasarkan subjeknya masing-masing. Tidak seperti [chat osu!](/wiki/Community/Internet_Relay_Chat) yang berlangsung secara instan, diskusi pada forum bersifat permanen serta dapat dicari dan dibaca ulang kapan saja. Oleh karenanya, pesan forum yang ada pada umumnya lebih panjang, lebih kaya akan informasi, dan lebih rinci dibanding pesan *chat* biasa.
```
Biar sama formatnya dengan yang lain kaya `osu! forum` > `forum osu!`, `osu! website` > `web osu!`, dll.

2022-11-10 19:42 UTC, Nivalyx commented
`forum` is quite literally the title of the article already so i don't think it should be added to the tags tho

fixed everything else, should be ready for recheck/approval i suppose @hikikuman 🦉

2022-11-11 01:58 UTC, hikikuman submitted a review, later dismissed
Alright, then good to go👍

2022-11-11 04:20 UTC, Walavouchey commented on wiki/Community/Forum/id.md
> +  - sub-forum
copy the new tag to the other ones

2022-11-11 04:26 UTC, Nivalyx commented
@Walavouchey done 👍

2022-11-11 04:29 UTC, Walavouchey approved these changes

2022-11-11 04:30 UTC, merged