[FR] Update `Contests`
ppy/osu-wiki pull request #8335
Opened 2022-11-12 16:33 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-11-21 17:57 UTC, Biokax requested changes

2022-11-21 17:57 UTC, Biokax commented on wiki/Contests/fr.md
> +| [#20 (A Most Manic Art Contest)](https://osu.ppy.sh/home/news/2019-09-06-a-most-manic-contest) | Design de Mascotte osu!mania | ::{ flag=US }:: [Tofumang](https://osu.ppy.sh/users/4817223) | ::{ fl
```suggestion
| [#20 (A Most Manic Art Contest)](https://osu.ppy.sh/home/news/2019-09-06-a-most-manic-contest) | Design de la Mascotte osu!mania | ::{ flag=US }:: [Tofumang](https://osu.ppy.sh/users/4817223) | ::{ flag=SG }:: [Hecatia](https://osu.ppy.sh/users/8244635) | ::{ flag=HK }:: [crystalsuicune](https://osu.ppy.sh/users/9974) | [#1](https://osu.ppy.sh/home/news/2019-10-21-most-manic-art-contest-voting-results) |
```

2022-11-21 18:01 UTC, Biokax approved these changes

2022-11-29 16:45 UTC, TicClick approved these changes

2022-11-29 17:04 UTC, merged