[JA] Update `Main_Page`
ppy/osu-wiki pull request #8353
Opened 2022-11-18 08:17 UTC by yuzupon1133

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-11-18 08:22 UTC, Walavouchey requested changes

2022-11-18 08:22 UTC, Walavouchey commented on wiki/Main_Page/ja.md
> +[API](/wiki/osu!api) • [ボットアカウント](/wiki/Bot_account) • [ブランド アイデンティティ ガイドライン](/wiki/Brand_identity_guidelines) • [osu!の開発者向けディスコードサーバー](/wiki/Community/osu!dev_Discord_server)
"osu!dev" is the name of the server, so it shouldn't be modified

2022-11-19 03:21 UTC, peppy approved these changes

2022-11-20 10:41 UTC, Walavouchey approved these changes

2022-11-20 10:51 UTC, merged