[ZH] Add `Community\Profile_badge` and `Tournaments\Official_tournament_support`
ppy/osu-wiki pull request #8355
Opened 2022-11-18 17:07 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-11-26 15:22 UTC, FlyingFish23 requested changes
翻译总体上来讲没有出错，但是可阅读性上还可以提高一下，感觉很多地方不太符合中文的语序，是完全按照英文来翻的。表意没有问题，但是阅读上相对比较费力。
然后`发送电子邮箱`和`Users under an active tournament ban are expected to disclose their tournament ban status to any officially supported tournament they intend to help with. `这两句真的离谱了...

2022-11-26 15:22 UTC, FlyingFish23 commented on wiki/Tournaments/Official_support/zh.md
> +文章最后于 2022年1月9日 更新。如果有任何疑问或需要解答问题，请在 [osu!dev Discord 服务器](https://discord.com/invite/ppy)的 `#tournaments` 咨询，或是发送电子邮箱至 [tournaments@ppy.sh](mailto:tournaments@ppy.sh)。
```suggestion
文章最后于 2022年1月9日 更新。如果有任何疑问或需要问题解答，请在 [osu!dev Discord 服务器](https://discord.com/invite/ppy)的 `#tournaments` 咨询，或是发送邮件至 [tournaments@ppy.sh](mailto:tournaments@ppy.sh)。
```
下次用机翻记得认真检查一下吧...

2022-11-26 15:22 UTC, FlyingFish23 commented on wiki/Tournaments/Official_support/zh.md
> +- 锦标赛需要由*经验丰富、值得信赖的工作人员团队*[^experience] 举办，**或者**，锦标赛系列*至少举办过一届无奖品的比赛*。
```suggestion
- 锦标赛需要由*经验丰富、值得信赖的工作人员团队*[^experience] 举办，**或者**，系列锦标赛*至少举办过一届无奖品的比赛*。
```
系列这个词放在后面有一点奇怪，这个也可以讨论

2022-11-26 15:22 UTC, FlyingFish23 commented on wiki/Tournaments/Official_support/zh.md
> +  - 锦标赛系列的前几届比赛（如果有）
```suggestion
  - 系列锦标赛的前几届比赛（如果有）
```
同上，可以讨论

2022-11-26 15:22 UTC, FlyingFish23 commented on wiki/Tournaments/Official_support/zh.md
> +如果玩家被官方禁止参与任何官方锦标赛，并且他们向打算帮助，受官方支持的锦标赛申请帮助，也可以按照锦标赛主办的决定，计入锦标赛的[助手](#what-is-considered-staff)。但我们建议主办仔细考虑这些申请，因为他们已经违反过锦标赛的相关规则。这些受限的玩家不得担任[工作人员](#what-is-considered-staff)，**除非**主办在发出官方支持申请时，在申请内提出
```suggestion
正处于禁赛状态下的玩家，在作为受官方支持赛事的助手之前，需要向赛事主办方表明自己目前正在被禁赛的情况。这类玩家按照锦标赛主办的决定，可以计入锦标赛的[助手](#what-is-considered-staff)。但我们建议主办仔细考虑这些申请，因为他们已经违反过锦标赛的相关规则。这些受限的玩家不得担任[工作人员](#what-is-considered-staff)，**除非**主办在发出官方支持申请时，在申请内提出豁免请求。账号支持团队将根据账号历史评估他们能否担任工作人员。
```
我尽力在不篡改你的语言风格下帮助你了，但是这真的离谱了...

2022-11-26 15:22 UTC, FlyingFish23 commented on wiki/Tournaments/Official_support/zh.md
> +官方支持的锦标赛有一个主要部分是筛查玩家的过程。与世界杯所有参赛选手的“安全检查”类似，筛查 (Screen) 选手能避免最近严重违反锦标赛规定或禁赛的玩家扰乱锦标赛。
```suggestion
官方支持的锦标赛有一个主要部分是筛查玩家。与世界杯所有参赛选手的“安全检查”类似，筛查 (Screen) 选手能避免最近严重违反锦标赛规定或禁赛的玩家扰乱锦标赛。
```
感觉`的过程`在这里没有必要，这个可以讨论

2022-12-22 09:10 UTC, YumeMuzi commented on wiki/Tournaments/Official_support/zh.md
> +如果玩家被官方禁止参与任何官方锦标赛，并且他们向打算帮助，受官方支持的锦标赛申请帮助，也可以按照锦标赛主办的决定，计入锦标赛的[助手](#what-is-considered-staff)。但我们建议主办仔细考虑这些申请，因为他们已经违反过锦标赛的相关规则。这些受限的玩家不得担任[工作人员](#what-is-considered-staff)，**除非**主办在发出官方支持申请时，在申请内提出
就漏了一句吧，说离谱也太偏了

2022-12-22 09:11 UTC, YumeMuzi commented on wiki/Tournaments/Official_support/zh.md
> +文章最后于 2022年1月9日 更新。如果有任何疑问或需要解答问题，请在 [osu!dev Discord 服务器](https://discord.com/invite/ppy)的 `#tournaments` 咨询，或是发送电子邮箱至 [tournaments@ppy.sh](mailto:tournaments@ppy.sh)。
需要问题解答是？

2022-12-22 12:16 UTC, FlyingFish23 commented on wiki/Tournaments/Official_support/zh.md
> +文章最后于 2022年1月9日 更新。如果有任何疑问或需要解答问题，请在 [osu!dev Discord 服务器](https://discord.com/invite/ppy)的 `#tournaments` 咨询，或是发送电子邮箱至 [tournaments@ppy.sh](mailto:tournaments@ppy.sh)。
发送邮件是为了获得问题的解答，而不是去解答问题对吧

2022-12-28 12:39 UTC, TicClick approved these changes

2022-12-28 12:43 UTC, merged