[ZH] Add `Score`
ppy/osu-wiki pull request #8387
Opened 2022-11-25 18:18 UTC by FlyingFish23

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

麻烦reviewer在提出修改建议的时候给个理由哦
please leave a reason for me to check when suggesting changes! thanks~
然后鸡蛋里挑骨头，为了改而改的就别提了，我会直接resolve的
please, don't try to pick bones from an egg, or suggest changes just because you can. I'll just ignore and resolve them
我是学文的，你觉得我遣词造句有问题可以拿新华字典解释或者拿相关guideline来怼我，别无中生有哈

2022-11-28 03:48 UTC, kj415j45 requested changes

2022-11-28 03:48 UTC, kj415j45 commented on wiki/Gameplay/Score/zh.md
> +玩家成功完成一张[谱面](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap)所获得的分数，是由玩家在每个[打击物件](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Hit_object) (Hit Object) 上所取得的[判定](https://github.
链接应使用相对路径

2022-11-28 03:48 UTC, kj415j45 commented on wiki/Gameplay/Score/zh.md
> +除了更好的标准化外，ScoreV2 也是对长谱面连击数较多而导致产生[整数溢出](https://zh.wikipedia.org/wiki/整数溢出)问题的解决方案。因为游戏的总分会被存储为一个 32 位的整数，而 ScoreV1 理论上能给出的分数是无限的，这就会导致分数值超过 32 位整数的理论极限 2,147,483,647，从而让分数计算器倒转产生负数分值（视觉上会体现为分数开始慢慢减
```suggestion
除了更好的标准化外，ScoreV2 也是对长谱面连击数较多而导致产生[整数溢出](https://zh.wikipedia.org/wiki/整数溢出)问题的解决方案。因为游戏的总分会被存储为一个 32 位的整数，而 ScoreV1 理论上能给出的分数是无限的，这就会导致分数值超过 32 位整数的理论极限 2,147,483,647，从而让分数计算器倒转产生负数分值（看上去就像是分数开始慢慢减少）。实际上，理论最高分超过该限制的长谱面取得的成绩会自动使用 ScoreV2 计分。
```

2022-11-28 05:35 UTC, FlyingFish23 commented on wiki/Gameplay/Score/zh.md
> +玩家成功完成一张[谱面](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap)所获得的分数，是由玩家在每个[打击物件](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Hit_object) (Hit Object) 上所取得的[判定](https://github.
是指把这些GitHub链接换成/wiki/beatmap这种链接形式嘛
其实我也不太清楚怎么就搞成了这种GitHub链接，你不指出来我还没看到🤣
```suggestion
玩家成功完成一张[谱面](/wiki/Beatmap)所获得的分数，是由玩家在每个[打击物件](/wiki/Gameplay/Hit_object) (Hit Object) 上所取得的[判定](/wiki/Gameplay/Judgement)来决定的。目前正在使用的分数系统可以分成两个大版本。
```

2022-11-28 05:41 UTC, FlyingFish23 commented on wiki/Gameplay/Score/zh.md
> +除了更好的标准化外，ScoreV2 也是对长谱面连击数较多而导致产生[整数溢出](https://zh.wikipedia.org/wiki/整数溢出)问题的解决方案。因为游戏的总分会被存储为一个 32 位的整数，而 ScoreV1 理论上能给出的分数是无限的，这就会导致分数值超过 32 位整数的理论极限 2,147,483,647，从而让分数计算器倒转产生负数分值（视觉上会体现为分数开始慢慢减
`看上去...`和`超过该限制`我感觉改的没问题，但是后面这里的话...英文原文是`In practice`，我感觉还是译成`在实践中`，词典对于Practice的第一释义也是`实践`
<img width="337" alt="截屏2022-11-28 13 37 58" src="https://user-images.githubusercontent.com/89104935/204202041-c9e04f99-50d8-40b1-8c17-2dacc0304dc9.png">
`实际上`主要相对`Actually`这个单词吧👀
```suggestion
除了更好的标准化外，ScoreV2 也是对长谱面连击数较多而导致产生[整数溢出](https://zh.wikipedia.org/wiki/整数溢出)问题的解决方案。因为游戏的总分会被存储为一个 32 位的整数，而 ScoreV1 理论上能给出的分数是无限的，这就会导致分数值超过 32 位整数的理论极限 2,147,483,647，从而让分数计算器倒转产生负数分值（看上去就像是分数开始慢慢减少）。在实践中，理论最高分超过该限制的长地图取得的成绩会自动使用 ScoreV2 计分。
```

2022-11-28 08:46 UTC, FlyingFish23 commented on wiki/Gameplay/Score/zh.md
> +除了更好的标准化外，ScoreV2 也是对长谱面连击数较多而导致产生[整数溢出](https://zh.wikipedia.org/wiki/整数溢出)问题的解决方案。因为游戏的总分会被存储为一个 32 位的整数，而 ScoreV1 理论上能给出的分数是无限的，这就会导致分数值超过 32 位整数的理论极限 2,147,483,647，从而让分数计算器倒转产生负数分值（视觉上会体现为分数开始慢慢减
对不起，我承认我眼睛有问题，我刚看到In practice的释义是实际上🥲

2022-11-29 03:30 UTC, kj415j45 commented on wiki/Gameplay/Score/zh.md
> +玩家成功完成一张[谱面](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap)所获得的分数，是由玩家在每个[打击物件](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Hit_object) (Hit Object) 上所取得的[判定](https://github.
对，是这样改

2022-11-29 07:20 UTC, FlyingFish23 commented on wiki/Gameplay/Score/zh.md
> +玩家成功完成一张[谱面](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap)所获得的分数，是由玩家在每个[打击物件](https://github.com/ppy/osu-wiki/blob/master/wiki/Gameplay/Hit_object) (Hit Object) 上所取得的[判定](https://github.
👌🏿改好了

2022-12-04 12:41 UTC, merged