Add `4 Digit osu!mania World Cup 2023` article
ppy/osu-wiki pull request #8422
Opened 2022-12-03 02:42 UTC by fajar13k

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

## Description

- Initial article for upcoming [4 Digit osu!mania World Cup 2023](https://osu.ppy.sh/community/forums/topics/1671710)

2022-12-06 15:21 UTC, TicClick requested changes
in addition to that, I have to admit a lot of rules are VERY verbose here -- my gut feeling is that they can be at least halved without loss of meaning. not sure if it's something that needs to be addressed — may require massive rewrite and tinkering with the wording while I understand you aren't the one who wrote the rules — but worth noting regardless.

2022-12-06 15:21 UTC, TicClick commented on wiki/Tournaments/4DM/2023/en.md
> +   5. Player must not appear on the list linked [here](https://docs.google.com/spreadsheets/d/1udZFfvt3it7Hk_k4J89k-UMzY1gfELaBN_oxw53CUOA/edit#gid=757705500). (There may be possibility to appeal the
```suggestion
   5. Player must not appear on the [Skillbans list](https://docs.google.com/spreadsheets/d/1udZFfvt3it7Hk_k4J89k-UMzY1gfELaBN_oxw53CUOA/edit#gid=757705500). (There may be possibility to appeal their placement on this list. More information on this is given in the [screening phase](#screening-phase) section)
```

2022-12-06 15:21 UTC, TicClick commented on wiki/Tournaments/4DM/2023/en.md
> +1. As player will read in the [prizes](#prizes) section, 4DM2023 plans to award the players on top 3 finishing teams with a **unique profile badge**. In order to make this happen, this tournament mus
(I added "the" somewhere but diff won't show it)
```suggestion
1. As player will read in the [prizes](#prizes) section, 4DM2023 plans to award the players on top 3 finishing teams with a **unique profile badge**. In order to make this happen, this tournament must meet the requirement of sending osu! staff a list of every player who signs up for this tournament in order for them to be screened for past or current violations of the osu! community rules. If players would like to read more about the screening process and profile badges, it is available through the following [article](/wiki/osu!tourney/Prizes#profile-badges). If in this screening, osu! staff finds that player have violated the osu! community rules in the past 12 months, then we as host sadly will have to deny their registration as eligible to participate in 4DM2023. All players found in violation after the screening will be given time to appeal their stance, and if osu! staff changes their mind on a player's eligibility and notifies a host of this, then they will still be eligible for participation in 4DM2023!
```

2022-12-06 15:21 UTC, TicClick commented on wiki/Tournaments/4DM/2023/en.md
> +2. Furthermore, there will be a **Skill Based Restriction System** developed and maintained by ::{ flag=TH }:: [HowToPlayLN](https://osu.ppy.sh/users/10879600), ::{ flag=FR }:: [Paturages](https://os
```suggestion
2. Furthermore, there will be a **skill-based restriction system** developed and maintained by ::{ flag=TH }:: [HowToPlayLN](https://osu.ppy.sh/users/10879600), ::{ flag=FR }:: [Paturages](https://osu.ppy.sh/users/1375479), and ::{ flag=SG }:: [Polytetral](https://osu.ppy.sh/users/8612061) in order to keep 4DM2023 fair to all players and as free of malicious sandbagging as possible. To read more about the general scope of this system, please visit the following [article](https://4digitmwc.github.io/skillban-articles/). To see who has been shown to be too skilled for the tournament by this system, visit the [Skillbans list](https://docs.google.com/spreadsheets/d/1udZFfvt3it7Hk_k4J89k-UMzY1gfELaBN_oxw53CUOA/edit#gid=757705500).
```

2022-12-06 15:21 UTC, TicClick commented on wiki/Tournaments/4DM/2023/en.md
> +NOTE: Staff will attempt to closely follow the rules of the most recent 4K osu!mania World Cup whose wiki page is hyperlinked [here](/wiki/Tournaments/MWC/2022_4K) if you would like to read it.
```suggestion
NOTE: Staff will attempt to closely follow the rules of [the most recent 4K osu!mania World Cup](/wiki/Tournaments/MWC/2022_4K).
```

2022-12-06 17:54 UTC, TicClick submitted a review, later dismissed
passing to @Walavouchey for a second look

2022-12-17 23:24 UTC, fajar13k commented
Bumping this again if review is coming or I might just rewrite it with my usual style

2022-12-18 01:05 UTC, Walavouchey requested changes
posting partial review to prevent delay, may finish it with a bit more time, but i'd appreciate if you'd take a look at the last part yourself.

2022-12-26 15:05 UTC, aceticke requested changes
Should fix the errors that came up in the checks.

2022-12-26 15:05 UTC, aceticke commented on wiki/Tournaments/4DM/2023/en.md
> +1. The planned *unique profile badge* prize depends on 4DM2023's eligibility for [official tournament support](https://osu.ppy.sh/wiki/en/Tournaments/Official_support). Players will be [screened](htt
```suggestion
1. The planned *unique profile badge* prize depends on 4DM2023's eligibility for [official tournament support](/wiki/en/Tournaments/Official_support). Players will be [screened](/wiki/en/Tournaments/Official_support#tournament-screening) by osu! staff and players found to be ineligible for tournament play will be denied entry. Consult [accounts@ppy.sh](mailto:accounts@ppy.sh) for appeals; if a failed screening result is retracted and notified of to a host, the player will still be eligible for participation in the tournament.
```

2022-12-26 15:05 UTC, aceticke commented on wiki/Tournaments/4DM/2023/en.md
> +  - This list of players shown on the sheet is subject to change until it has been sent to osu! staff for review. Any player appearing on this list may not sign up for 4DM2023, but there will be an a
```suggestion

  - This list of players shown on the sheet is subject to change until it has been sent to osu! staff for review. Any player appearing on this list may not sign up for 4DM2023, but there will be an appeal system. Players shown as **true** on both the ranked and tournament columns may not appeal their restriction to sign. However if they are only **true** for one or the other, they may message log.\#7606 via Discord with a request to appeal their restriction, which will be reviewed by tournament staff. For questions, refer to 4DM's `#questions` channel in the Discord server.
```

2022-12-28 08:33 UTC, Walavouchey requested changes

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +15. Failed scores do not count toward a team's total score, however a score which fails and then revives will still count. (Use NoFail if you believe you are in jeopardy of failing a map!)
```suggestion
15. Failed scores do not count towards a team's total score, however a score which fails and then revives will still count. (Use No Fail if you believe you are in jeopardy of failing a map!)
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +17. If a team cannot gather 3 members into the match lobby by 10 minutes after the match’s scheduled start time, the opposing team will be declared a win by default. If neither team can gather 3 memb
```suggestion
17. If a team cannot gather 3 members into the match lobby by 10 minutes after the match's scheduled start time, the opposing team will be declared to win by default. If neither team can gather 3 members into the match lobby by 10 minutes after the match's scheduled start time, the team with the higher seed out of qualifiers will be declared to win by default.
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +19. For additional rules left out of this section of the forum, please see the [Additional Rules](#additional-rules) section below. As well, feel free to ask a host about any questions regarding rule
```suggestion
19. For additional rules left out of this section of the forum, please see the [Additional rules](#additional-rules) section below. As well, feel free to ask a host about any questions regarding rules or the tournament in general!
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +2. Please note that while the organizers will try to schedule all matches for the best possible time for both teams, timezone conflicts may force some matches to occur in the early mornings or late n
```suggestion
2. Please note that while the organisers will try to schedule all matches for the best possible time for both teams, timezone conflicts may force some matches to occur in the early mornings or late nights.
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +5. If no commentators are available to commentate the match but broadcasters are available to broadcast the match, the match will still be broadcasted but without commentary. Please note that organiz
```suggestion
5. If no commentators are available to commentate the match but broadcasters are available to broadcast the match, the match will still be broadcasted but without commentary. Please note that organisers will try to broadcast every match possible.
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +6. Rescheduled matches will be prioritized under non-rescheduled matches in terms of being broadcasted.
```suggestion
6. Rescheduled matches will be prioritised under non-rescheduled matches in terms of being broadcasted.
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +8. If one player on a team has their account restricted while still participating in the tournament for reasons of believed cheating, multi accounting, or anything else, this player's entire team sha
```suggestion
8. If one player on a team has their account restricted while still participating in the tournament for reasons of believed cheating, multi-accounting, or anything else, this player's entire team shall be disqualified from the tournament with no exceptions. Depending on the case, the team most recently defeated in a match by the newly disqualified team may be allowed to advance in this disqualified team's place. If this happens, the result of this former match will be voided.
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +9. Repeated and excessive toxic behavior toward any staff member, player, or spectator either in match multiplayer chatroom, the official discord server, or the official twitch channel chatroom is st
```suggestion
9. Repeated and excessive toxic behavior toward any staff member, player, or spectator either in match multiplayer chatroom, the official discord server, or the official twitch channel chatroom is strictly prohibited and will lead to, in successive order with host's discretion to skip certain steps:
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +   3. Timeout of player wherever necessary for a subjective amount of time (Players on timeout during tournament match will be disallowed to play during their match and must be swapped out for other
```suggestion
   3. Timeout of player wherever necessary for a subjective amount of time (disallowing them from playing in tournament matches)
```

2022-12-28 08:33 UTC, Walavouchey commented on wiki/Tournaments/4DM/2023/en.md
> +   4. Official ban from the tournament as well as a ban from the official Discord server and Twitch channel
```suggestion
   4. Ban from the tournament as well as a ban from the official Discord server and Twitch channel
```

2022-12-28 08:43 UTC, Walavouchey approved these changes

2022-12-28 08:46 UTC, merged