[FR] Update `People/The_Team`, `Beatmap_Spotlights` and Add `People/The_Team/Beatmap_Spotlight_Curators`
ppy/osu-wiki pull request #8426
Opened 2022-12-04 11:59 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-04 12:29 UTC, Ganondorf-1 approved these changes

2022-12-08 16:14 UTC, TicClick approved these changes

2022-12-08 18:08 UTC, TicClick requested changes

2022-12-08 18:08 UTC, TicClick commented on wiki/People/The_Team/fr.md
> +| ::{ flag=CA }:: [VINXIS](https://osu.ppy.sh/users/4323406) | Modération et conseiller communautaire |
please check ALL roles with the original page https://github.com/ppy/osu-wiki/blob/master/wiki/People/The_Team/en.md: VINXIS' and Naxess' roless should be mapping/modding scene advisor, not moderation: https://github.com/ppy/osu-wiki/blob/master/wiki/People/The_Team/en.md

2022-12-13 18:11 UTC, TicClick approved these changes

2022-12-13 18:15 UTC, merged