Add "Beatmap Spotlight Curators" Article indonesia language.
ppy/osu-wiki pull request #8443
Opened 2022-12-07 09:13 UTC by maxuskazuma

right now indonesia version doesn't have this new page being updated, so we need to have new one.

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +**Beatmap Spotlight Curators** (***BSC***) adalah grup yang membantu memilih map berkualitas tinggi untuk setiap season dari [Beatmap Spotlights](/wiki/Beatmap_Spotlights).
```suggestion
**Beatmap Spotlight Curators** (***BSC***) adalah sebuah grup yang membantu memilih map-map berkualitas tinggi untuk setiap musim dari [Beatmap Spotlights](/wiki/Beatmap_Spotlights).
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Pada umumnya, kurator baru disarankan oleh anggota tim dari setiap game mode untuk memenuhi kriteria tertentu. Sugesti tersebut dievaluasi oleh Manajer projek, pemimpin team, dan anggota kurator send
```suggestion
Pada umumnya, menjadi seorang kurator baru perlu disarankan oleh anggota tim dari setiap mode permainan untuk memenuhi kriteria tertentu. Saran tersebut akan dievaluasi oleh Manajer projek, pemimpin tim, dan anggota kurator sendiri.
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Selain itu, mungkin juga akan dibuka pendaftaran untuk beberapa gamemode yang diumumkan untuk musim tertentu.
```suggestion
Selain itu, kemungkinan pendaftaran akan dibuka untuk beberapa mode permainan yang diumumkan untuk musim tertentu.
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Semua pendaftar akan dinilai berdasarkan keahlian sebagai pemain, mapper, modder, dan tournament mappool selector untuk masing-masing game mode. Pendaftar tidak perlu untuk ahli di semua bidang ini u
```suggestion
Semua pendaftar akan dinilai berdasarkan keahlian-keahlian yang dimiliki sebagai pemain, mapper, modder, dan tournament mappool selector untuk masing-masing mode permainan. Pendaftar tidak perlu menjadi ahli di semua bidang ini untuk bisa dipilih, tapi mempunyai pengalaman yang luas membantu. Tujuannya adalah untuk memiliki anggota kurator dengan campuran dari berbagai jenis skill level, pengalaman, dan keahlian. Akan tetapi, jumlah kurator pada saat ini dibuat kecil dan terbatas karena proyek masih berkembang.
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Proyek Beatmap Spotlights dijalankan oleh berbagai anggota komunitas di semua mode game, dipimpin oleh pimpinan proyek khusus. [Halaman Grup Beatmap Spotlight Curators](https://osu.ppy.sh/groups/48)
```suggestion
Proyek Beatmap Spotlights dijalankan oleh berbagai anggota komunitas di semua mode permainan yang dipimpin oleh pimpinan proyek khusus. [Halaman Grup Beatmap Spotlight Curators](https://osu.ppy.sh/groups/48) mencantumkan nama semua anggota.
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +| Role | Members |
```suggestion
| Peran | Anggota |
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Tim kurator khusus mengumpulkan setiap rilis Beatmap Spotlights. Pemimpin tim ditandai dengan huruf tebal.
```suggestion
Tim kurator khusus berdedikasi mengumpulkan setiap rilis dari Beatmap Spotlights. Pemimpin tim ditandai dengan huruf tebal.
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### osu! curators
```suggestion
### kurator osu!
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### osu!taiko curators
```suggestion
### kurator osu!taiko
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### osu!catch curators
```suggestion
### kurator osu!catch
```

2022-12-07 11:29 UTC, mousesalt commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### osu!mania curators
```suggestion
### kurator osu!mania
```

2022-12-08 04:03 UTC, mousesalt approved these changes
approved

2022-12-08 04:13 UTC, mousesalt approved these changes
second attempt

2022-12-08 08:18 UTC, ZeroPyrozen requested changes

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Tim kurator khusus berdedikasi mengumpulkan setiap rilis dari Beatmap Spotlights. Pemimpin tim ditandai dengan huruf tebal.
```suggestion
Tim kurator khusus disusun untuk setiap rilis Beatmap Spotlights. Pemimpin tim ditandai dengan huruf tebal.
```

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### kurator osu!
```suggestion
### Kurator osu!
```

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### kurator osu!taiko
```suggestion
### Kurator osu!taiko
```

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### kurator osu!catch
```suggestion
### Kurator osu!catch
```

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +### kurator osu!mania
```suggestion
### Kurator osu!mania
```

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Pada umumnya, menjadi seorang kurator baru perlu disarankan oleh anggota tim dari setiap mode permainan untuk memenuhi kriteria tertentu. Saran tersebut akan dievaluasi oleh Manajer projek, pemimpin
```suggestion
Pada umumnya, kurator baru direkrut berdasarkan rekomendasi yang diberikan oleh anggota tim dari setiap mode permainan untuk memenuhi kriteria tertentu. Rekomendasi tersebut akan dievaluasi oleh manajer proyek, pemimpin tim, dan anggota kurator itu sendiri.
```

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Selain itu, kemungkinan pendaftaran akan dibuka untuk beberapa mode permainan yang diumumkan untuk musim tertentu.
```suggestion
Selain itu, pendaftaran dapat dibuka untuk beberapa mode permainan yang diumumkan untuk musim tertentu.
```

2022-12-08 08:18 UTC, ZeroPyrozen commented on wiki/People/The_Team/Beatmap_Spotlight_Curators/id.md
> +Semua pendaftar akan dinilai berdasarkan keahlian-keahlian yang dimiliki sebagai pemain, mapper, modder, dan tournament mappool selector untuk masing-masing mode permainan. Pendaftar tidak perlu menj
```suggestion
Semua pendaftar akan dinilai berdasarkan keahlian-keahlian yang dimiliki sebagai pemain, mapper, modder, dan tournament mappool selector untuk masing-masing mode permainan. Pendaftar tidak perlu menjadi ahli di semua bidang ini untuk bisa dipilih, tetapi mempunyai pengalaman yang luas dapat membantu. Tujuannya adalah untuk memiliki anggota kurator dengan campuran dari berbagai jenis skill level, pengalaman, dan keahlian. Akan tetapi, jumlah kurator pada saat ini dibuat kecil dan terbatas karena proyek yang masih berkembang.
```

2022-12-10 13:38 UTC, ZeroPyrozen submitted a review, later dismissed

2022-12-11 10:25 UTC, mousesalt submitted a review, later dismissed

2022-12-13 18:29 UTC, TicClick approved these changes
I've combined your changes into 3 commits instead of 27, but please follow these best practices in your future PRs:
- make [commits with meaningful descriptions](https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#making-edits);
- for a single logically scoped change, such as applying a review, make a single commit (`Apply review from <someone>` or so), as opposed to 10 small commits titled `Update Path/To/Article/en.md`

2022-12-13 18:32 UTC, merged