[FR] Update `Disambiguation/Offset`
ppy/osu-wiki pull request #8448
Opened 2022-12-09 18:21 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-24 11:16 UTC, Ganondorf-1 requested changes

2022-12-24 11:16 UTC, Ganondorf-1 commented on wiki/Disambiguation/Offset/fr.md
> +- Un "offset" de beatmap est la quantité de temps entre le début du fichier audio et le premier [downbeat](/wiki/Music_theory/Downbeat) de la musique, mesurée en millisecondes.
```suggestion
- Un "offset" de beatmap est le temps entre le début du fichier audio et le premier [downbeat](/wiki/Music_theory/Downbeat) de la musique, mesuré en millisecondes.
```

2022-12-24 11:16 UTC, Ganondorf-1 commented on wiki/Disambiguation/Offset/fr.md
> +- [Online offset](/wiki/Beatmap/Online_offset) : changement de temps appliqué par un member de la [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) aux beatmaps classées avec un offset incorrec
```suggestion
- [Online offset](/wiki/Beatmap/Online_offset) : changement de temps appliqué par un membre de la [NAT](/wiki/People/The_Team/Nomination_Assessment_Team) aux beatmaps classées avec un offset incorrect non hérité afin de l'ajuster.
```

2022-12-24 11:19 UTC, Ganondorf-1 commented on wiki/Disambiguation/Offset/fr.md
> +- Un [point de timing non hérité](/wiki/Client/Beatmap_editor/Timing#uninherited-timing-point) ("ligne rouge"), le début d'une nouvelle [section de timing](/wiki/Beatmapping/Timing_section). Les poin
```suggestion
- Un [point de timing non hérité](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités) ("ligne rouge"), le début d'une nouvelle [section de timing](/wiki/Beatmapping/Timing_section). Les points de timing se trouvent à un décalage par rapport au début du fichier audio, mais le point de timing lui-même est aussi parfois appelé "offset".
```

2022-12-28 13:33 UTC, TicClick approved these changes

2022-12-28 13:35 UTC, merged