[FR] Add `Help_centre/Upgrading_to_lazer`
ppy/osu-wiki pull request #8481
Opened 2022-12-16 19:37 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-17 07:58 UTC, Walavouchey commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +"lazer " est un nom de code et sera éventuellement abandonné lorsqu'il deviendra la version principale du jeu. Dans le reste de ce document, osu!(lazer) sera appelé "lazer" et osu!(stable) sera appel
are these smart quotes (`"` and `"`) already a thing in other translations? the english versions always use `"`

```suggestion
"lazer" est un nom de code et sera éventuellement abandonné lorsqu'il deviendra la version principale du jeu. Dans le reste de ce document, osu!(lazer) sera appelé "lazer" et osu!(stable) sera appelé "stable" pour plus de simplicité.
```

2022-12-17 07:58 UTC, Walavouchey commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +| Windows 8.0 et moins | ![Yes][true] | ![No][false] |
etc

```suggestion
| Windows 8.0 et moins | ![Oui][true] | ![Non][false] |
```

2022-12-18 18:14 UTC, Pisapou commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +| Chat en temps réel | ![ParPartiellementtial][partial][^stable-chat] | ![Oui][true] |
```suggestion
| Chat en temps réel | ![Partiellementtial][partial][^stable-chat] | ![Oui][true] |
```

2022-12-18 18:14 UTC, Pisapou commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +| Chat en temps réel | ![ParPartiellementtial][partial][^stable-chat] | ![Oui][true] |
```suggestion
| Chat en temps réel | ![Partiellement][partial][^stable-chat] | ![Oui][true] |
```

2022-12-24 12:08 UTC, Ganondorf-1 requested changes

2022-12-24 12:08 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +#### Comment accéder à mon dossier songs ?
```suggestion
#### Comment accéder à mon dossier Songs ?
```

2022-12-24 12:08 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +Il n'y a pas de dossier songs dans lazer! Cela nous permet de faire des choses sympas comme ne pas avoir à presser `F5` lors de la sélection des beatmaps pour les rafraîchir (parce que les beatmaps s
```suggestion
Il n'y a pas de dossier Songs dans lazer ! Cela nous permet de faire des choses sympas comme ne pas avoir à presser `F5` lors de la sélection des beatmaps pour les rafraîchir (parce que les beatmaps sont toujours dans un bon état) et réduire l'espace disque utilisé par les beatmaps de 20-40%. Vous pouvez en savoir plus sur [la façon dont lazer stocke les fichiers](/wiki/Client/Release_stream/Lazer/File_storage).
```

2022-12-24 12:08 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +Si vous devez apporter des modifications à une beatmap, veuillez utiliser l'éditeur. À l'avenir, nous introduirons un mode dans l'éditeur qui rendra le dossier d'un beatmap temporairement accessible
```suggestion
Si vous devez apporter des modifications à une beatmap, veuillez utiliser l'éditeur. À l'avenir, nous introduirons un mode dans l'éditeur qui rendra le dossier d'une beatmap temporairement accessible pour une édition externe. Cela vous permettra d'utiliser des outils externes sur une beatmap pendant le processus de création.
```

2022-12-24 12:08 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +[^wine]: En utilisant du vin.
```suggestion
[^wine]: En utilisant Wine.
```

2022-12-24 12:08 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +[^coming-soon]: A venir prochainement.
```suggestion
[^coming-soon]: À venir prochainement.
```

2022-12-24 12:08 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +[^normalisation]: Cela permet d'amener les combo colours personnalisée de beatmap au même niveau de luminosité.
```suggestion
[^normalisation]: Cela permet d'amener les combo colours personnalisées de beatmap au même niveau de luminosité.
```

2022-12-24 12:08 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +[^direct-supporter]: Uniquement via osu!direct, réservé aux osu!supporter.
```suggestion
[^direct-supporter]: Uniquement via osu!direct, réservé aux osu!supporters.
```

2022-12-31 17:54 UTC, The-Last-Cookie commented
Please don't forget to apply the changes from #8548.

2023-01-01 12:12 UTC, Pisapou commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +| Préréglages de mods | ![Non][false] | ![Oui][true] |
```suggestion
| Ajustement de la difficulté de mods | ![Non][false] | ![Oui][true][^difficulty-adjust] |
| Préréglages de mods | ![Non][false] | ![Oui][true] |
```

2023-01-01 12:12 UTC, Pisapou commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +Si vous êtes curieux de savoir comment cela affecte la latence d'entrée et de tester votre propre perception, veuillez exécuter le "certificateur de latence" intégré en bas des paramètres.
```suggestion
Si vous êtes curieux de savoir comment cela affecte la latence d'entrée et de tester votre propre perception, veuillez exécuter le "certificateur de latence" intégré en bas des paramètres.

Vous pouvez également [lire ce document technique] (https://github.com/ppy/osu/wiki/Latency-and-unlimited-frame-rates) qui explique la voie que nous empruntons et le raisonnement qu'elle implique.
```

2023-01-01 12:12 UTC, Pisapou commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +Lazer prend en compte l'entrée à 1000 Hz indépendamment du limiteur de FPS, c'est pourquoi le réglage maximal du limiteur s'arrêtera également à 1000 FPS.
```suggestion
Lazer prend en compte l'entrée à 1 000 Hz indépendamment du limiteur de FPS, c'est pourquoi le réglage maximal du limiteur s'arrêtera également à 1 000 FPS.
```

2023-01-01 12:12 UTC, Pisapou commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +Le système d'exploitation continuera à prendre en compte à un taux plus élevé, bien que les avantages s'avèrent être négligeables. Le rafraîchissement à des taux aussi élevés peut avoir des surcharge
```suggestion
Le système d'exploitation continuera à prendre en compte à un taux plus élevé, bien que les avantages s'avèrent être négligeables. Le rafraîchissement à des taux aussi élevés peut avoir des surcharges imprévues, et nous recommandons de limiter les périphériques à 1 000 Hz pour la stabilité du système.
```

2023-01-01 12:12 UTC, Pisapou commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +[^queue-modes]: Activez cette option pour permettre à n'importe qui dans un lobby de mettre en file d'attente de nouvelles beatmaps, alias "rotation de l'hôte".
```suggestion
[^queue-modes]: Activez cette option pour permettre à n'importe qui dans un lobby de mettre en file d'attente de nouvelles beatmaps, alias "rotation de l'hôte".
[^difficulty-adjust]: Changez le CS/AR/OD/HP d'une beatmap directement depuis la sélection des beatmaps.
```

2023-01-01 12:18 UTC, Ganondorf-1 requested changes

2023-01-01 12:18 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +| Ajustement de la difficulté de mods | ![Non][false] | ![Oui][true][^difficulty-adjust] |
```suggestion
| Ajustement de la difficulté des mods | ![Non][false] | ![Oui][true][^difficulty-adjust] |
```

2023-01-01 12:18 UTC, Ganondorf-1 commented on wiki/Help_centre/Upgrading_to_lazer/fr.md
> +Vous pouvez également [lire ce document technique] (https://github.com/ppy/osu/wiki/Latency-and-unlimited-frame-rates) qui explique la voie que nous empruntons et le raisonnement qu'elle implique.
```suggestion
Vous pouvez également [lire ce document technique](https://github.com/ppy/osu/wiki/Latency-and-unlimited-frame-rates) qui explique la voie que nous empruntons et le raisonnement qu'elle implique.
```

2023-01-07 10:53 UTC, The-Last-Cookie commented
And there's another one: #8576

2023-01-09 13:24 UTC, TicClick approved these changes

2023-01-09 13:27 UTC, merged