[FR] Add `Client/Release_Stream/Lazer/File_Storage`
ppy/osu-wiki pull request #8482
Opened 2022-12-17 00:02 UTC by ItsShamed

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-18 18:24 UTC, Pisapou requested changes

2022-12-18 18:24 UTC, Pisapou commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +Sur les plateformes PC, le stockage de fichiers peut aussi être bougé dans son entièreté vers une autre emplacement, en appuyant sur le bouton `Changer l'emplacement du dossier...`
```suggestion
Sur les ordinateurs, le stockage de fichiers peut aussi être bougé dans son entièreté vers une autre emplacement, en appuyant sur le bouton `Changer l'emplacement du dossier...` dans les paramètres du client.
```

2022-12-18 18:24 UTC, Pisapou commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +Pour le moment, la procédure correcte pour manuellement modifier les skins ou les beatmaps en dehors des fonctions disponibles en jeu est d'exporter l'élément en question, le changer, et ensuite le r
```suggestion
Pour le moment, la procédure correcte pour manuellement modifier les skins ou les beatmaps en dehors des fonctions disponibles en jeu est d'exporter l'élément en question, les changer, et ensuite les réimporter de nouveau avec les changements désirés.
```

2022-12-18 18:24 UTC, Pisapou commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +### Avec des liens physiques
```suggestion
### Par des liens physiques
```

2022-12-18 18:27 UTC, Pisapou commented
Par ailleurs, n'hésite pas à rejoindre la serveur discord osu! French (https://discord.com/invite/vfrHNQZ) si tu comptes t'impliquer dans la traduction du wiki!

2022-12-18 18:46 UTC, Pisapou requested changes

2022-12-18 18:46 UTC, Pisapou commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +Pour faire simple, deux fichiers liés physiquement sont simplement deux noms différents pour le même fragment d'espace sur le disque dur. Cela veut dire qu'une fois que la migration se termine via de
```suggestion
Pour faire simple, deux fichiers liés physiquement sont simplement deux noms différents pour le même fragment d'espace sur le disque dur. Cela veut dire qu'une fois que la migration se termine via des liens physiques, les répertoires `Songs` (sur stable) et `files` (sur lazer) vont tous les deux contenir des fichiers qui pointent vers des données partagées sur le disque. Supprimer des fichiers sur une installation ne va pas affecter l'autre. Changer les fichiers entraînera la séparation des fichiers, et n'affectera donc pas non plus l'autre installation, tant qu'osu! est habitué à faire ces changements.
```

2022-12-18 18:46 UTC, Pisapou commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +À noter que si l'utilisation du disque est vérifié depuis la fenêtre `Propriétés` dans l'Explorateur ou quelconque autre méthode similaire, il semblerait que les dossiers `Songs` et `files` utilisent
```suggestion
À noter que si l'utilisation du disque est vérifiée depuis la fenêtre `Propriétés` dans l'Explorateur ou d'une quelconque autre méthode similaire, il semblerait que les dossiers `Songs` et `files` utilisent de l'espace disque, ce qui pourrait induire en erreur les utilisateurs à penser que les données sont stockées deux fois. C'est un artéfact de la détermination de taille, et les vraies données stockées sur le disque ne sont **pas** dupliquées. Cela peut être vérifié en comparant la valeur totale de l'espace disponible sur le disque entier avant et après la migration.
```

2022-12-24 12:20 UTC, Ganondorf-1 requested changes

2022-12-24 12:20 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +Sur les ordinateurs, le stockage de fichiers peut aussi être bougé dans son entièreté vers une autre emplacement, en appuyant sur le bouton `Changer l'emplacement du dossier...` dans les paramètres d
```suggestion
Sur les ordinateurs, le stockage de fichiers peut aussi être déplacé dans son entièreté vers un autre emplacement, en appuyant sur le bouton `Changer l'emplacement du dossier...` dans les paramètres du client.
```

2022-12-24 12:20 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +Pour le moment, la procédure correcte pour manuellement modifier les skins ou les beatmaps en dehors des fonctions disponibles en jeu est d'exporter l'élément en question, le changer, et ensuite le r
```suggestion
Pour le moment, la procédure correcte pour manuellement modifier les skins ou les beatmaps en dehors des fonctions disponibles en jeu est d'exporter l'élément en question, le changer, et ensuite le réimporter avec les changements désirés.
```

2022-12-24 12:20 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +Un lien physique est conceptuellement semblable à un *raccourci* dû au fait que c'est une méthode qui permet à un utilisateur d'avoir le même fichier à différents emplacements sur leur système de fic
```suggestion
Un lien physique est conceptuellement semblable à un *raccourci* dû au fait que c'est une méthode qui permet à un utilisateur d'avoir le même fichier à différents emplacements sur son système de fichiers. Cependant, alors que les raccourcis ne sont que de simples fichiers qui pointent vers un fichier différent (et requièrent ainsi un espace additionnel), les liens physiques fonctionnent à un niveau plus profond, au niveau du système de fichiers en lui-même.
```

2022-12-24 12:20 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +À noter que si l'utilisation du disque est vérifiée depuis la fenêtre `Propriétés` dans l'Explorateur ou d'une quelconque autre méthode similaire, il semblerait que les dossiers `Songs` et `files` ut
```suggestion
À noter que si l'utilisation du disque est vérifiée depuis la fenêtre `Propriétés` dans l'Explorateur ou d'une quelconque autre méthode similaire, il semblera que les dossiers `Songs` et `files` utilisent de l'espace disque, ce qui pourrait induire en erreur les utilisateurs à penser que les données sont stockées deux fois. C'est un artéfact de la détermination de taille de fichier, et les vraies données stockées sur le disque ne sont **pas** dupliquées. Cela peut être vérifié en comparant la valeur totale de l'espace disponible sur le disque entier avant et après la migration.
```

2022-12-28 12:51 UTC, TicClick approved these changes

2022-12-28 12:52 UTC, merged