[ES] Update `Article_styling_criteria/Formatting`
ppy/osu-wiki pull request #8487
Opened 2022-12-17 20:09 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-21 19:15 UTC, TicClick commented
I have a strong suspicion that `zh-hk.md` was meant to be `zh-tw.md`: https://github.com/ppy/osu-wiki/pull/282

2022-12-30 00:39 UTC, juankristal requested changes
Small review becuase I think most of my issues with the translation here are pretty much sorted out in this wikipedia article: https://es.wikipedia.org/wiki/Wikipedia:Estructura_de_un_art%C3%ADculo#Gu%C3%ADas_de_navegaci%C3%B3n

2022-12-30 00:39 UTC, juankristal commented on wiki/Article_styling_criteria/Formatting/es.md
> +A veces, las traducciones se agregan a la wiki sin la revisión de otros hablantes nativos del idioma. En este caso, se agrega la marca `no_native_review` para que los futuros traductores sepan que es
Deberia ser una `etiqueta` no una `marca`, no?

Ademas, `para que los futuros traductores sepan que es posible que deba verificarse nuevamente` => `la cual indica a futuros traductores que el articulo puede necesitar ser verificado nuevamente`

2022-12-30 00:39 UTC, juankristal commented on wiki/Article_styling_criteria/Formatting/es.md
> +Los títulos de los artículos deben ser singulares y usar mayúsculas y minúsculas. Véase el [artículo de Convenciones de títulos de Wikipedia](https://es.wikipedia.org/wiki/Wikipedia:Convenciones_de_t
`Véase las [Convenciones de títulos de Wikipedia](https://es.wikipedia.org/wiki/Wikipedia:Convenciones_de_títulos) para obtener más detalles`

2022-12-30 00:39 UTC, juankristal commented on wiki/Article_styling_criteria/Formatting/es.md
> +## Notas de sombrero
Nunca escuche el termino. Me parece que es una traduccion literal de hatnote y no lo que una hatnote realmente es, que es mas cercano a un encabezado si se quiere.

Buscando en internet encontre [Guias de navegacion](https://es.wikipedia.org/wiki/Wikipedia:Estructura_de_un_art%C3%ADculo#Gu%C3%ADas_de_navegaci%C3%B3n) y otras cosas interesantes en general para la [estructura de un articulo](https://es.wikipedia.org/wiki/Wikipedia:Estructura_de_un_art%C3%ADculo).

Usaria este enlace de wikipedia para usar mejores nombres a estos sectores del articulo en lugar de usar lo que sugiere google translate.

2023-01-29 00:17 UTC, juankristal approved these changes

2023-01-29 00:17 UTC, juankristal commented
Ideally use better commit messages so its easier to track the changes done, making review a bit easier.

2023-01-29 00:18 UTC, merged