Update `Global Moderation Team` + `Nomination Assessment Team` listings.
ppy/osu-wiki pull request #8489
Opened 2022-12-19 04:54 UTC by Blooshing

#indonesian did not have FAMoss listed on the page as all moderators regardless of focus get listed to. This also updates the NAT - will need translators to redo the meta info for their respective language.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-19 21:22 UTC, aceticke requested changes
Staff Log needs updating, I've done this for you here https://github.com/aceticke/osu-wiki/blob/affad5862304ffa6ab61671e455a204cf2e42b15/wiki/People/The_Team/Staff_Log/2022/en.md

2022-12-19 21:56 UTC, Walavouchey commented
separate pr was opened for that https://github.com/ppy/osu-wiki/pull/8492

2022-12-19 22:04 UTC, Walavouchey commented
hmm with the update to the staff log, the other listings will need to be updated as well to account for the new moves/additions/removals

2022-12-20 04:41 UTC, aceticke requested changes
fvrex is a mania bn not standard so this will need to be fixed

2022-12-20 04:41 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/en.md
> +| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | German |
```suggestion
| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | German |
| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  |
```

2022-12-20 04:44 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/es.md
> +| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  |
```suggestion
```

2022-12-20 04:44 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/es.md
> +| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | Alemán |
```suggestion
| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | Alemán |
| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  |
```

2022-12-20 04:45 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/fr.md
> +| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  |
```suggestion
```

2022-12-20 04:47 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/pt-br.md
> +| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | Alemão |
```suggestion
| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | Alemão |
| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  
```

2022-12-20 04:48 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/th.md
> +| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | เยอรมัน |
```suggestion
| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | เยอรมัน |
| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  |
```

2022-12-20 04:49 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/tr.md
> +| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | Almanca |
```suggestion
| ::{ flag=DE }:: [Feerum](https://osu.ppy.sh/users/4815717) | Almanca |
| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  |
```

2022-12-20 04:49 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +| ::{ flag=AU }:: [fvrex](https://osu.ppy.sh/users/11863699) |  |
```suggestion
```

2022-12-20 05:21 UTC, aceticke requested changes
One last thing to fix

2022-12-20 05:26 UTC, aceticke approved these changes
Looks good

2022-12-22 12:09 UTC, TicClick approved these changes
should be good to go. I don't see significant merit in updating the NAT page translations with English placeholders but I guess that'll do until they are localized

2022-12-22 12:11 UTC, merged