[ES] Add `Mascots/Gallery`
ppy/osu-wiki pull request #8504
Opened 2022-12-23 15:17 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-31 23:58 UTC, juankristal commented on wiki/Mascots/Gallery/es.md
> +- [Fan Art 8: Christmas](https://osu.ppy.sh/community/contests/36)
Should be "Navidad"

2022-12-31 23:59 UTC, juankristal requested changes
Titles should be translated. Only pointed out a few but there are many still in english.

2022-12-31 23:59 UTC, juankristal commented on wiki/Mascots/Gallery/es.md
> +- [Fan Art 6: osu!taiko mascot](https://osu.ppy.sh/community/contests/2)
"Mascota de osu!taiko" or something along those lines

2023-01-01 00:09 UTC, agatemosu commented on wiki/Mascots/Gallery/es.md
> +- [Fan Art 6: osu!taiko mascot](https://osu.ppy.sh/community/contests/2)
No lo traduje porque el título del concurso está en inglés aunque tenga la página en español

2023-01-10 17:03 UTC, juankristal approved these changes

2023-01-10 19:33 UTC, merged