[ZH] Add ` Upgrading_to_lazer`
ppy/osu-wiki pull request #8510
Opened 2022-12-24 20:58 UTC by YumeMuzi

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-29 03:24 UTC, cdwcgt requested changes

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +### 已上线系统
```suggestion
### 线上系统
```
？
在线系统应该也行

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 更新官网有新更新的谱面  | ![部分支持][partial][^map-only]  | ![支持][true][^all-files] |
Online用线上或者在线？
而且原文是with，应该是说用官网修改来更新谱面

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 缩放物件 | ![不支持][false] | ![支持][true]  |
```suggestion
| 调整物件大小 | ![不支持][false] | ![支持][true]  |
```
stable是支持比例缩放的，但是lazer支持非比例(?)缩放。
![image](https://user-images.githubusercontent.com/34775378/209898530-c6d5018a-e5d2-43b3-92ab-f013e034608e.png)

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +只要还有玩家使用它，稳定版将继续维护，最坏情况来说，它将仍旧维护几年。
```suggestion
只要还有玩家使用它，稳定版将继续维护。最坏情况来说，它将仍旧维护几年。
```
最坏情况我可能会选择至少

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +目前，谱面、皮肤、分数、游戏回放和收藏夹都可以导入激光版。注意，**设置不能导入**，所以你需要从头开始配置它。
```suggestion
目前，谱面、皮肤、分数、游戏回放和收藏夹都可以导入激光版。注意，**设置还不能导入**，所以你需要从头开始配置它。
```
或者 `暂时` `暂且` 都行

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +### 表现
```suggestion
### 性能
```

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +我们认为，游戏帧率没理由在某个阈值之上运行。激光版采用了各种新技术，确保在不需要高帧率的情况下实现最低延迟。这将继续改进，并且我们还有一些改进亟待实施。
```suggestion
我们认为，游戏帧率没理由在高帧率上运行。激光版采用了各种新技术，确保在不需要高帧率的情况下实现最低延迟。这将继续改进，并且我们还有一些改进亟待实施。
```

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +我们很可能已经注意到这些点，并跟踪它们，准备在将来修改！请搜索[问题跟踪页](https://github.com/ppy/osu/issues)和[讨论页](https://github.com/ppy/osu/discussions)。如果你找不到任何符合你遇到的情况的讨论串，可以随时[展开讨论](https://github.com/ppy/osu/discussions/new)。
这样翻译也可以，但是github对于issues是有官方翻译的，叫做 `议题`
可改可不改吧

2022-12-29 03:24 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +- 支持者可以在课题模式中创建持续时间更长的课题
![image](https://user-images.githubusercontent.com/34775378/209899209-8c82e7bf-e252-428a-be9d-93768a4bc3b0.png)

2022-12-31 17:54 UTC, The-Last-Cookie commented
Please don't forget to apply the changes from #8548.

2023-01-13 14:18 UTC, YumeMuzi commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +- 支持者可以在课题模式中创建持续时间更长的课题
歌单模式 和 课题模式 一直在打架，支持一下课题模式把谢谢了

2023-01-13 14:18 UTC, YumeMuzi commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +我们很可能已经注意到这些点，并跟踪它们，准备在将来修改！请搜索[问题跟踪页](https://github.com/ppy/osu/issues)和[讨论页](https://github.com/ppy/osu/discussions)。如果你找不到任何符合你遇到的情况的讨论串，可以随时[展开讨论](https://github.com/ppy/osu/discussions/new)。
wtf

2023-01-13 14:19 UTC, YumeMuzi commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 更新官网有新更新的谱面  | ![部分支持][partial][^map-only]  | ![支持][true][^all-files] |
想了想，感觉我的翻译有歧义，改了

2023-01-13 14:20 UTC, YumeMuzi commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +我们认为，游戏帧率没理由在某个阈值之上运行。激光版采用了各种新技术，确保在不需要高帧率的情况下实现最低延迟。这将继续改进，并且我们还有一些改进亟待实施。
ppy 的意思应该指的是 没必要在特别高的帧率上（无限制 / unlimited）运行，不是不给高帧率

2023-01-14 08:14 UTC, TTsdzb commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +尽管我们会尽量多地保留成绩，但我们**不保证能永久保留成绩**。在任何时间点，我们可能会删除一小部分或是全部分数，来确保游戏平衡。
```suggestion
尽管我们会尽量多地保留成绩，但我们**不保证能永久保留成绩**。我们随时可能会删除一小部分或是全部分数，来确保游戏平衡。 
```

2023-01-14 08:19 UTC, TTsdzb commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +虽然在大多数现代硬件上，激光版的性能优于稳定版。但每个玩家有不同的硬件配置，总会出现少数反转情况。在我们的短期计划中，我们将让游戏支持 DirectX（在稳定版中称为“兼容模式”）和 Vulkan，它们在硬件层面的驱动支持上，比 OpenGL 更好。一旦实现，在因特尔集成芯片组等硬件上的游戏性能将大幅改善。
```suggestion
虽然在大多数现代硬件上，激光版的性能优于稳定版。但每个玩家有不同的硬件配置，总会出现少数反转情况。在我们的短期计划中，我们将让游戏支持 DirectX（在稳定版中称为“兼容模式”）和 Vulkan，它们在硬件层面的驱动支持上，比 OpenGL 更好。一旦实现，在英特尔集成芯片组等硬件上的游戏性能将大幅改善。
```
虽然也有“因特尔”这种说法，但是官方翻译是“英特尔”。

2023-01-14 08:22 UTC, TTsdzb commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +我们很可能已经注意到这些点，并跟踪它们，准备在将来修改！请搜索[问题跟踪页](https://github.com/ppy/osu/issues)和[讨论页](https://github.com/ppy/osu/discussions)。如果你找不到任何符合你遇到的情况的讨论串，可以随时[展开讨论](https://github.com/ppy/osu/discussions/new)。
```suggestion
我们很可能已经注意到这些点，并跟踪它们，准备在将来修改！请在[问题跟踪页](https://github.com/ppy/osu/issues)和[讨论页](https://github.com/ppy/osu/discussions)中搜索。如果你找不到任何符合你遇到的情况的讨论串，可以随时[展开讨论](https://github.com/ppy/osu/discussions/new)。
```

2023-01-14 08:28 UTC, TTsdzb commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +最后，不像之前的迭代，这一次我们投入了大量时间精力，确保代码库在未来也能提供服务。我们已经做了很多基础工作，允许新功能以极快的速度上线。这包括了新的用户界面 (UI) 组件，新的游戏皮肤制作方式，并记住现在激光版还有通过添加全新的游戏规则（游戏模式）并在其上加载和游玩所有现有谱面的功能！
```suggestion
最后，不像之前的迭代，这一次我们投入了大量时间精力，确保代码库在未来也能提供服务。我们已经做了很多基础工作，允许新功能以极快的速度上线。这包括了新的用户界面 (UI) 组件，新的游戏皮肤制作方式，而且别忘了现在激光版还有通过添加全新的游戏规则（游戏模式）并在其上加载和游玩所有现有谱面的功能！
```
这么翻总感觉怪怪的……
考虑原文 `and let's not forget` 是想表强调，应该可以翻译成“而且最重要的是”

2023-01-15 06:22 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +最后，不像之前的迭代，这一次我们投入了大量时间精力，确保代码库在未来也能提供服务。我们已经做了很多基础工作，允许新功能以极快的速度上线。这包括了新的用户界面 (UI) 组件，新的游戏皮肤制作方式，并记住现在激光版还有通过添加全新的游戏规则（游戏模式）并在其上加载和游玩所有现有谱面的功能！
`还有通过` --> `还可以通过`

这样读起来不是更顺畅

2023-01-15 07:20 UTC, TTsdzb commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +最后，不像之前的迭代，这一次我们投入了大量时间精力，确保代码库在未来也能提供服务。我们已经做了很多基础工作，允许新功能以极快的速度上线。这包括了新的用户界面 (UI) 组件，新的游戏皮肤制作方式，并记住现在激光版还有通过添加全新的游戏规则（游戏模式）并在其上加载和游玩所有现有谱面的功能！
> `还有通过` --> `还可以通过`
> 
> 这样读起来不是更顺畅

确实是这样的

不过我觉得应该直接删掉 `通过`？最后有 `的功能` 了

```diff
- 现在激光版还有通过添加全新的游戏规则（游戏模式）并在其上加载和游玩所有现有谱面的功能
+ 现在激光版还可以通过添加全新的游戏规则（游戏模式）并在其上加载和游玩所有现有谱面的功能
+ 现在激光版还有添加全新的游戏规则（游戏模式）并在其上加载和游玩所有现有谱面的功能
```

2023-01-17 03:14 UTC, TheInterestingSoul commented
你自己在游戏内翻译成`lazer`，又在这里翻译成`激光版`，别人从`进一步了解lazer`点进去就有译名上的冲突
![Screenshot_20230117_111202_mark via](https://user-images.githubusercontent.com/41455159/212801764-5c49e02c-3c4d-4099-a87c-5bb37b807dcb.png)

2023-01-17 03:22 UTC, TheInterestingSoul commented
游戏内保留`lzaer`不动的字符串太多了，建议不要翻译为`激光版`。

`lazer`又不像Minecraft中的`Bedrock Edition（基岩版）`一样具有明显的象征这个游戏。而且商品名称翻译带来的迷因效应是很严重的（参见可口可乐换成现名前的翻译：蝌蚪嚼蜡。这种译法虽然保留的“音”特征更多，但是后果你懂的），谨慎翻译

2023-01-17 03:38 UTC, TTsdzb commented
> 游戏内保留`lzaer`不动的字符串太多了，建议不要翻译为`激光版`。
> 
> `lazer`又不像Minecraft中的`Bedrock Edition（基岩版）`一样具有明显的象征这个游戏。而且商品名称翻译带来的迷因效应是很严重的（参见可口可乐换成现名前的翻译：蝌蚪嚼蜡。这种译法虽然保留的“音”特征更多，但是后果你懂的），谨慎翻译

赞同

之前就觉得怪怪的但是讲不出理由(+_+)

2023-01-18 06:30 UTC, YumeMuzi commented
> 游戏内保留`lzaer`不动的字符串太多了，建议不要翻译为`激光版`。
> 
> `lazer`又不像Minecraft中的`Bedrock Edition（基岩版）`一样具有明显的象征性：对一个人说“基岩”，只要他不学地理或考古，他第一个想到的就会是Minecraft。而且商品名称翻译带来的迷因效应是很严重的（参见可口可乐换成现名前的翻译：蝌蚪嚼蜡。这种译法虽然保留的“音”特征更多，但是作为一款饮料，后果你懂的），谨慎翻译
> 
> 再退一步讲，反正lazer都会取代stable，到时候这个代号就没了。

也行，到时候只在文章开头保留 lazer (激光版) 这个表述

2023-01-18 07:37 UTC, YumeMuzi commented
> 游戏内保留`lzaer`不动的字符串太多了，建议不要翻译为`激光版`。
> 
> `lazer`又不像Minecraft中的`Bedrock Edition（基岩版）`一样具有明显的象征性：对一个人说“基岩”，只要他不学地理或考古，他第一个想到的就会是Minecraft。而且商品名称翻译带来的迷因效应是很严重的（参见可口可乐换成现名前的翻译：蝌蚪嚼蜡。这种译法虽然保留的“音”特征更多，但是作为一款饮料，后果你懂的），谨慎翻译
> 
> 再退一步讲，反正lazer都会取代stable，到时候这个代号就没了。

反驳，就拿我自己为例，我并不清楚基岩版和 java 版的区别。
其次，Coca-Cola `蝌蝌啃蜡` 明显是音译，激光版很明显是意译，类似的 `雷泽版` 才是音译。这个作为例子使用不恰当。
再者，在过去的 stable client 里，有前辈已经把 stable 作为`稳定版`译出。如果把和它对应的 lazer 独立出来不翻译，也不合适。

2023-01-18 07:38 UTC, YumeMuzi commented
> 你自己在游戏内翻译成`lazer`，又在这里翻译成`激光版`，别人从`进一步了解lazer`点进去就有译名上的冲突 ![Screenshot_20230117_111202_mark via](https://user-images.githubusercontent.com/41455159/212801764-5c49e02c-3c4d-4099-a87c-5bb37b807dcb.png)

直接修改 crowdin 就行了

2023-01-18 10:59 UTC, cdwcgt commented
https://discord.com/channels/188630481301012481/218677502141399041/1065222614903177246

lazer字符串不应该被翻译

2023-01-18 11:01 UTC, YumeMuzi commented
> https://discord.com/channels/188630481301012481/218677502141399041/1065222614903177246
> 
> lazer字符串不应该被翻译

ppy win. reworking

2023-01-18 11:25 UTC, cdwcgt requested changes

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +osu!(lazer)（也称为 osu!lazer ）是游戏的下一个大更新。这凝结了几年以来精心幕后工作的结晶，并重构了游戏。
```suggestion
osu!(lazer) 是游戏的下一个大更新。这凝结了几年以来精心幕后工作的结晶，并重构了游戏。
```
干脆就不要了吧

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +"lazer" 是这个版本的代号。当它成为游戏的主要版本时，最终将删除掉这个代号。为方便起见，本文以下部分将 osu!(lazer) 简称为 "lazer"，osu!(stable) 简称为 "稳定版"。
https://discord.com/channels/188630481301012481/218677502141399041/1065224635446202408
在直接引用名字时不应翻译

```suggestion
"lazer" 是这个版本的代号。当它成为游戏的主要版本时，最终将删除掉这个代号。为方便起见，本文以下部分将 osu!(lazer) 简称为 "lazer"，osu!(stable) 简称为 "stable"。
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +下面的表格是 lazer **当前版本**与稳定版功能的对比表。注意这是一个不断变化的目标——最终目标是随着时间推移，实现所有玩家关心的功能。
```suggestion
下面的表格是 lazer **当前版本**与 stable 功能的对比表。注意这是一个不断变化的目标——最终目标是随着时间推移，实现所有玩家关心的功能。
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 功能 | 稳定版 | lazer |
```suggestion
| 功能 | stable | lazer |
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 功能 | 稳定版 | lazer |
```suggestion
| 功能 | stable | lazer |
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 功能 | 稳定版  | lazer |
```suggestion
| 功能 | stable | lazer |
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 功能  | 稳定版  | lazer |
```suggestion
| 功能  | stable | lazer |
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| 功能 | 稳定版 | lazer |
```suggestion
| 功能 | stable | lazer |
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +你能在[这里](https://github.com/ppy/osu#running-osu)下载到游戏。在不久的将来，你能从稳定版切换到 lazer（在`更新通道 (更新版本)` 设置里切换），并在 osu! 官网上找到下载链接！
感觉游戏这个定义太笼统了?

```suggestion
你能在[这里](https://github.com/ppy/osu#running-osu)下载到该版本。在不久的将来，你能从稳定版切换到 lazer（在`更新通道 (更新版本)` 设置里切换），并在 osu! 官网上找到下载链接！
```


```suggestion
你能在[这里](https://github.com/ppy/osu#running-osu)下载到 lazer。在不久的将来，你能从稳定版切换到 lazer（在`更新通道 (更新版本)` 设置里切换），并在 osu! 官网上找到下载链接！
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
>  只要还有玩家使用它，稳定版将继续维护。最坏情况来说，它将仍旧维护几年。
```suggestion
只要还有玩家使用它，稳定版将继续维护。最坏情况来说，它仍将维护几年。
```
感觉更通顺

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +目前，谱面、皮肤、分数、游戏回放和收藏夹都可以导入 lazer 。注意，**设置还不能导入**，所以你需要从头开始配置它。
```suggestion
目前，谱面、皮肤、分数、游戏回放和收藏夹都可以导入到 lazer。注意，**设置还不能导入**，所以你需要从头开始配置它。
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +如果稳定版和 lazer 安装在同一张磁盘上， lazer 会使用[硬链接](/wiki/Client/Release_stream/Lazer/File_storage#via-hard-links)来避免占用额外的磁盘空间。
```suggestion
如果稳定版和 lazer 安装在同一张磁盘上，lazer 会使用[硬链接](/wiki/Client/Release_stream/Lazer/File_storage#via-hard-links)来避免占用额外的磁盘空间。
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +可以。 lazer 总会独立于稳定版安装。除非你删除了某一个版本，否则两个版本都将可用。
```suggestion
可以。lazer 总会独立于稳定版安装。除非你删除了某一个版本，否则两个版本都将可用。
```

2023-01-18 11:25 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +不管游戏帧率如何， lazer 的输入都是 1000 HZ，所以游戏的最大帧率也限制为 1000 FPS。
```suggestion
不管游戏帧率如何，lazer 的输入采样频率都是 1000 HZ，所以游戏的最大帧率也限制为 1000 FPS。
```

2023-01-18 11:30 UTC, YumeMuzi commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +osu!(lazer)（也称为 osu!lazer ）是游戏的下一个大更新。这凝结了几年以来精心幕后工作的结晶，并重构了游戏。
outdated

2023-01-18 11:31 UTC, cdwcgt approved these changes

2023-01-18 15:47 UTC, TheInterestingSoul requested changes
133-137行的错译还没修好……

2023-01-18 16:13 UTC, cdwcgt requested changes
笑死了 这算我的
是我没找到

2023-01-18 16:13 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +也就是说，现在只能从 lazer 导出个人的分数和谱面，并手动导入进稳定版中。
```suggestion
#### 我能从 lazer 向 stable 导入数据吗？

不能。这个功能还没有完全支持。

也就是说，现在只能从 lazer 导出个人的分数和谱面，并手动导入进 stable 中。
```

2023-01-18 16:37 UTC, TheInterestingSoul commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +也就是说，现在只能从 lazer 导出个人的分数和谱面，并手动导入进稳定版中。
咱不是说这个......我的意思是，这个译文与原文完全相悖，“不会支持”翻译成了“未完全支持”，习语“that said”也译错了，应该是“即便如此”，而不是什么“也就是说”

我上面的review就说了啊，不知道怎么会被标记成outdated给折叠了

2023-01-27 09:15 UTC, TTsdzb requested changes

2023-01-27 09:15 UTC, TTsdzb commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +不能。这个功能还没有完全支持。
```suggestion
不能。这个功能不会被支持。
```

原文 `This will not be supported.` ，而**不是** `This has not been supported yet.`
@TheInterestingSoul 之前提到了这个问题。

2023-01-27 09:15 UTC, TTsdzb commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +也就是说，现在只能从 lazer 导出个人的分数和谱面，并手动导入进 stable 中。
```suggestion
即便如此，现在可以从 lazer 手动导出单独的分数和谱面，并手动导入进 stable 中。
```

2023-01-27 11:36 UTC, cdwcgt requested changes

2023-01-27 11:36 UTC, cdwcgt commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +也就是说，现在只能从 lazer 导出个人的分数和谱面，并手动导入进 stable 中。
```suggestion
即便如此，现在也可以从 lazer 手动导出单独的分数和谱面，并手动导入进 stable 中。
```

2023-01-27 13:06 UTC, TheInterestingSoul approved these changes

2023-01-27 13:06 UTC, TheInterestingSoul commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +不能。这个功能还没有完全支持。
我是说嘛，提醒了两次都不改，也没有人答应我一声，一度怀疑我是不是连初中句子都译错了……

2023-01-27 13:55 UTC, cdwcgt approved these changes
我是没问题了

i'm ok

2023-01-27 13:57 UTC, TTsdzb approved these changes

2023-01-28 15:43 UTC, TicClick approved these changes

2023-01-28 19:06 UTC, TicClick approved these changes

2023-01-28 19:08 UTC, merged