[FR] Update `Nomination Assessment Team`
ppy/osu-wiki pull request #8515
Opened 2022-12-25 18:40 UTC by Ganondorf-1

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-25 19:10 UTC, Pisapou requested changes

2022-12-25 19:10 UTC, Pisapou commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +- **La communication :** Promouvoir la transparence et maintenir de bonnes relations avec non seulement le reste de la communauté de mapping/modding, mais également au sein de la NAT elle-même. Cela
```suggestion
- **La communication :** Promouvoir la transparence et maintenir de bonnes relations avec non seulement le reste de la communauté de mapping/modding, mais également au sein de la NAT elle-même. Cela inclut, sans s'y limiter, la publication d'annonces, la participation aux discussions sur les propositions, la pose de questions et l'apport de réponses dans le cadre de sondages, et la mise à jour des [critères de classement](/wiki/Ranking_Criteria) ainsi que d'autres documents.
```

2022-12-25 19:10 UTC, Pisapou commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Les conseillers s'assurent que les BN et les autres membres de la communauté de mapping/modding restent informés et se sentent entendus, en plus de maintenir les composants nécessaires au bon fonctio
```suggestion
Les conseillers s'assurent que les BN et les autres membres de la communauté de mapping/modding restent informés et se sentent entendus, en plus de maintenir les composantes nécessaires au bon fonctionnement de la scène de mapping/modding. Les conseillers sont généralement composés d'évaluateurs expérimentés qui préfèrent se concentrer sur les questions de gestion concernant la scène de mapping/modding.
```

2022-12-25 19:10 UTC, Pisapou commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Diviser la NAT en deux groupes est nécessaire pour l'organisation globale et la productivité du groupe, permettant une attribution plus rationnelle des tâches. La délégation de tâches permet aux memb
```suggestion
Diviser la NAT en deux groupes est nécessaire pour l'organisation globale et la productivité du groupe, permettant une répartition plus rationnelle des tâches. La délégation de tâches permet aux membres de la NAT de ne pas être surchargés tout en évitant une diffusion des responsabilités.
```

2022-12-25 19:10 UTC, Pisapou commented on wiki/People/The_Team/Nomination_Assessment_Team/fr.md
> +Le NAT garde un œil sur les candidats potentiels à la NAT sur de longues périodes et se réunit occasionnellement pour décider si un candidat doit être promu, de la même manière que les évaluations du
```suggestion
Le NAT garde un œil sur les candidats potentiels à la NAT sur de longues périodes et se réunit occasionnellement pour décider si un candidat doit être promu, de la même manière que les évaluations de BN. Les BN sont également autorisés à demander à rejoindre la NAT s'ils souhaitent recevoir un retour et s'assurer qu'ils sont pris en compte. Cependant, selon l'activité et les compétences des membres actuels de la NAT, il se peut qu'il n'y ait pas besoin de nouveaux membres. Des nouveaux membres ne seront probablement promus que lorsque l'un des membres actuels réduit son activité ou s'il y a de nouvelles charges de travail nécessitant plus de membres, etc.
```

2023-01-09 12:36 UTC, TicClick approved these changes

2023-01-09 12:37 UTC, merged