[PT-BR] Update `ScoreV1`
ppy/osu-wiki pull request #8519
Opened 2022-12-26 03:18 UTC by GranularBow8193

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-01 14:10 UTC, LeoFLT requested changes
OK otherwise

2023-01-01 14:10 UTC, LeoFLT commented on wiki/Gameplay/Score/ScoreV1/osu!/pt-br.md
> +*See also: [Julgamento dos hit objects do osu!](/wiki/Gameplay/Judgement/osu!)*
```suggestion
*Veja também: [Julgamento dos hit objects do osu!](/wiki/Gameplay/Judgement/osu!)*
```

2023-01-01 14:10 UTC, LeoFLT commented on wiki/Gameplay/Score/ScoreV1/osu!/pt-br.md
> +As regras para pontuação de cada tipo de objeto individualmente está descrito abaixo.
```suggestion
As regras para pontuação de cada tipo de objeto estão descritas individualmente abaixo.
```
Concordância nominal de gênero e número

2023-01-03 23:37 UTC, LeoFLT commented
Precisa de um `SKIP_WIKILINK_CHECK` na descrição, pelas mesmas razões que eu toquei no #8524. Note também que você tem que clickar na caixa de revisado por um nativo, ou o PR vai ficar marcado como incompleto (task-list-completed vai ficar em progresso até todas as checkboxes serem preenchidas)

2023-01-09 13:47 UTC, TicClick commented
in your future PRs, instead of silencing the check please fix the issue mentioned if you can:

```
wiki/Gameplay/Score/ScoreV1/osu!/pt-br.md:19:98: #difficulty-multiplier
Note: There is no heading or tag with identifier "difficulty-multiplier" in "/wiki/Gameplay/Score/ScoreV1/osu!/pt-br.md"
Suggestions:
	line 9: hit-circles
	line 22: multiplicador-de-dificuldade
	line 30: sliders
	line 39: spinners

- O *Multiplicador de dificuldade* é o valor específico ao beatmap jogado. Veja a [seção abaixo](#difficulty-multiplier) para a fórmula exata para computá-la.
```

as per suggestion, the solution was: [`8ccc7ca` (#8519)](https://github.com/ppy/osu-wiki/pull/8519/commits/8ccc7ca0fa20377f179327eab37b4a72bf07f282)

2023-01-09 13:47 UTC, TicClick approved these changes

2023-01-09 13:53 UTC, TicClick approved these changes

2023-01-09 13:58 UTC, merged