[RU] Add `Upgrade to lazer`
ppy/osu-wiki pull request #8537
Opened 2022-12-29 11:48 UTC by Loreos7

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Нужна дополнительная помощь в переводе ответа на вопрос "Будут ли когда-нибудь старые скины изменять меню выбора песни и экран с результатами?" и формулировки концовки ответа на "Что будет дальше?"

2022-12-30 00:21 UTC, TicClick requested changes
пока что так, потом напишу ревью на оставшееся. если там будет много правок, а я чувствую, что их будет очень много, можно я их сам сделаю, а ты потом допилишь статью до нужного вида, чтобы мы пришли к соглашению? так проще и быстрее будет

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Мобильная поддержка | ![No][false] | ![Yes][true] |
ну или «поддержка мобильных устройств», но никак не то, что ты написал
```suggestion
| Работа на мобильных устройствах | ![No][false] | ![Yes][true] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Встроенный драйвер для планшета | ![No][false] | ![Yes][true] |
нуууууууу вообще да, но речь же именно про настройку области, как мне кажется..

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Внутриигровой скин / Изменение элементов интерфейса | ![No][false] | ![Yes][true] |
In-game skin / UI layout editing = In-game skin editing + In-game UI layout editing. скины всегда были внутриигровыми, лол, где ж их ещё применять.
```suggestion
| Внутриигровой редактор скинов и интерфейса | ![No][false] | ![Yes][true] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +### Игра и скин
gameplay в значении «игровой процесс», как это ни печально, лучше всего передаётся словом «геймплей»... (но тогда нужно поменять скин на скиннинг, ну или какой-нибудь аналог)

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Пресеты модов | ![No][false] | ![Yes][true] |
это про готовые настройки модов? думаю, тут можно перевести без слова пресет (если нет — ладно)

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Показать скрытый интерфейс удержанием клавиши | ![No][false] | ![Yes][true][^hold-for-hud] |
громоздно как-то, плюс у тебя везде в таблице идут возможности/концепции (настройка, моды, отображение), а тут хуяк! — и действие (показать). нехорошо. про что это вообще, кстати? модная замена shift+tab?

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Калибровка сдвига трека относительно карты | ![Partial][partial][^offset-calibration-stable] | ![Yes][true][^offset-calibration-lazer] |
оффсет есть оффсет, так уж получилось. сам термин расшифровывает отдельная статья (неплохо бы, кстати, здесь ссылки потом проставить)
```suggestion
| Калибровка оффсета по результату игры | ![Partial][partial][^offset-calibration-stable] | ![Yes][true][^offset-calibration-lazer] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Выдвигающиеся / Задвигающиеся слайдеры | ![No][false] | ![Yes][true][^can-disable] |
```suggestion
| Выдвигающиеся / задвигающиеся слайдеры | ![No][false] | ![Yes][true][^can-disable] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Облегчённая версия "note lock" | ![No][false] | ![Yes][true][^note-lock] |
тоже кандидат на ссылку и замену на нотлок: https://osu.ppy.sh/wiki/ru/Gameplay/Judgement/Notelock

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Дольная окраска нот режима osu!mania | ![No][false] | ![Yes][true] |
оно от снаппинга зависит, что ли? (я просто в манию не играю)
```suggestion
| Дольная окраска нот в osu!mania | ![No][false] | ![Yes][true] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +### Онлайн-взаимодействие
а то как-то странно
```suggestion
### Онлайн
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Вики / Новости / Список изменений / Рейтинги | ![No][false] | ![Yes][true][^online-content] |
```suggestion
| Вики / новости / список изменений / ранкинги | ![No][false] | ![Yes][true][^online-content] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Таймеры обратного отсчёта | ![Partial][partial][^countdown-timers-stable] | ![Yes][true][^countdown-timers-lazer] |
```suggestion
| Таймер обратного отсчёта | ![Partial][partial][^countdown-timers-stable] | ![Yes][true][^countdown-timers-lazer] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Режим прохождения карты по секциям | ![Yes][true] | ![No][false] |
опять-таки это известный термин
```suggestion
| Tag co-op | ![Yes][true] | ![No][false] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Плейлисты (сеты из карт с собственными таблицами рекордов) | ![No][false] | ![Yes][true] |
```suggestion
| Плейлисты (подборки карт, имеющие собственные таблицы рекордов) | ![No][false] | ![Yes][true] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Обновление карт в реальном времени | ![Partial][partial][^map-only] | ![Yes][true][^all-files] |
```suggestion
| Обновление карт до последней опубликованной версии | ![Partial][partial][^map-only] | ![Yes][true][^all-files] |
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Изменение размеров паттернов | ![No][false] | ![Yes][true] |
может, лучше «масштабирование»?

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Кроссплатформенность | ![Yes][true] | ![Partial][partial][^incompatibilities] |
мне кажется, тут имеется в виду что-то другое, например, поддержка всех прошлых версий `.osu` — тогда это будет **обратной совместимостью**, а не кроссплатформенностью

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +## Переход в lazer
```suggestion
## Переход на lazer
```

2022-12-30 00:21 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Мне не нравятся новые механики игры. Я хочу играть так, как это было в stable.
```suggestion
#### Мне не нравится новый геймплей. Как сделать, чтобы было как в stable?
```

2022-12-30 02:05 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +osu!(lazer) – это следующее глобальное обновление игры: кульминация нескольких лет скрупулёзной работы "за кулисами" по разработке игры заново, с нуля.
Тогда лучше поставить ;
Раз в первой части про обновление, а во второй про кульминацию.

2022-12-30 12:43 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Конечной целью этого проекта является обновление, которое полностью заместит существующую стабильную версию, однако пока что ещё есть работа, которую нужно проделать, чтобы это стало реальностью. В к
```suggestion
Конечная цель этого проекта — выпуск обновления, которое полностью заменит текущую стабильную версию, однако перед этим всё ещё нужно доделать необходимую работу. В конечном счёте именно **игроки** будут решать, когда случится переход; поддержка предыдущей версии не прекратится до тех пор, пока большинство игроков не перейдут на новую.
```

2022-12-30 12:43 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Калибровка сдвига трека относительно карты | ![Partial][partial][^offset-calibration-stable] | ![Yes][true][^offset-calibration-lazer] |
Ладно, наверное стоит оставить оффсет, хотя где-то внутри себя я очень сильно сопротивляюсь. Во всяком случае, чтобы начать использовать это слово, нужно перевести статью с определением.

2022-12-30 12:43 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Вики / Новости / Список изменений / Рейтинги | ![No][false] | ![Yes][true][^online-content] |
```suggestion
| Вики / новости / список изменений / рейтинги | ![No][false] | ![Yes][true][^online-content] |
```

2022-12-31 17:51 UTC, The-Last-Cookie commented
Please don't forget to apply the changes from #8548, in case this still needs to be done.

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +### Игра и скин
давай тогда игровой процесс вместо игры, что уж

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Конечной целью этого проекта является обновление, которое полностью заместит существующую стабильную версию, однако пока что ещё есть работа, которую нужно проделать, чтобы это стало реальностью. В к
получше, но «перед этим всё ещё» — излишне, «доделать необходимую» — опять-таки излишне, попробуй ещё

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Пресеты модов | ![No][false] | ![Yes][true] |
я не знаю, что тут имеется в виду, честно говоря, можешь скриншот дать?

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Калибровка сдвига трека относительно карты | ![Partial][partial][^offset-calibration-stable] | ![Yes][true][^offset-calibration-lazer] |
я тебя понимаю

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +### Онлайн-взаимодействие
посмотрел второй раз, и вроде не так уж плохо. может, просто слово длинным чересчур показалось

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Вики / Новости / Список изменений / Рейтинги | ![No][false] | ![Yes][true][^online-content] |
я это предложил по названию страницы на вики, если уж на сайте «рейтинги», ладно, пускай будут рейтинги

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Режим прохождения карты по секциям | ![Yes][true] | ![No][false] |
блин, а есть что поудобоваримее? кмк, этот термин поэтому и оставался без перевода достаточно долгое время. и да, что за секции, если в tag роли по комбо разделяются? *совместное прохождение* тогда уж

2023-01-05 03:24 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Обновление карт в реальном времени | ![Partial][partial][^map-only] | ![Yes][true][^all-files] |
обновление карты в стабильном клиенте обновит только `.osu`, в лазере — вообще всё (не нужно удалять и перекачивать карту, если маппер аудио поменял, например, или хс обновил)

2023-01-05 03:25 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +osu!(lazer) – это следующее глобальное обновление игры: кульминация нескольких лет скрупулёзной работы "за кулисами" по разработке игры заново, с нуля.
точку с запятой здесь не стоит по этой же причине использовать

2023-01-05 03:25 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Конечной целью этого проекта является обновление, которое полностью заместит существующую стабильную версию, однако пока что ещё есть работа, которую нужно проделать, чтобы это стало реальностью. В к
ответил в другом комментарии

2023-01-05 18:11 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Пресеты модов | ![No][false] | ![Yes][true] |
![image](https://user-images.githubusercontent.com/86934170/210850734-023a96f9-2202-4170-93b9-0007650d8ed5.png)

2023-01-05 18:21 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Обновление карт в реальном времени | ![Partial][partial][^map-only] | ![Yes][true][^all-files] |
Всё, я понял
Тогда тут вообще лучше отбросить уточнение "with online changes". Просто "Обновление карт". Все равно там под значениями в таблице есть всплывающая штука, которая поясняет, что конкретно обновляется

2023-01-05 18:26 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Вики / Новости / Список изменений / Рейтинги | ![No][false] | ![Yes][true][^online-content] |
так страница на вики про ранкинг **карт**, а не игроков. Карты проходят процедуру ранкинга, я с этим согласен. Но что касается игроков по всему миру - у них есть определенный **рейтинг**. В неоднозначностях даже написано
![image](https://user-images.githubusercontent.com/86934170/210853479-ff5d3bdd-dfab-4843-9859-ac6e5278a27b.png)

2023-01-05 18:28 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Вики / Новости / Список изменений / Рейтинги | ![No][false] | ![Yes][true][^online-content] |
Я не уточнил, наверное. В таблице вот про эту функцию лазера. 
![image](https://user-images.githubusercontent.com/86934170/210853660-ef2f6b5d-20d6-46bc-9274-64b72c867fd4.png)
![image](https://user-images.githubusercontent.com/86934170/210853692-1e8894a5-47e6-4f3a-a1a1-3967b7eba020.png)

2023-01-05 18:31 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Режим прохождения карты по секциям | ![Yes][true] | ![No][false] |
Небольшой оффтоп: 
Head-to-head  - Каждый сам за себя
Team VS - Противостояние команд

2023-01-05 18:32 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Режим прохождения карты по секциям | ![Yes][true] | ![No][false] |
![image](https://user-images.githubusercontent.com/86934170/210854487-2c8c1319-aa6d-40af-913c-82f082f0d528.png)
![image](https://user-images.githubusercontent.com/86934170/210854521-7d98a2e5-4f93-4008-b631-e274b539bd23.png)

2023-01-05 19:08 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Конечной целью этого проекта является обновление, которое полностью заместит существующую стабильную версию, однако пока что ещё есть работа, которую нужно проделать, чтобы это стало реальностью. В к
Однако перед этим ещё предстоит поработать

2023-01-07 10:49 UTC, The-Last-Cookie commented
And there's another one: #8576

2023-01-09 15:11 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Пресеты модов | ![No][false] | ![Yes][true] |
а, ок. я думал, это про подкручивание скорости даблтайма и подобные вещи

2023-01-09 15:13 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Конечной целью этого проекта является обновление, которое полностью заместит существующую стабильную версию, однако пока что ещё есть работа, которую нужно проделать, чтобы это стало реальностью. В к
годится, хороший вариант

2023-01-09 15:15 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Режим прохождения карты по секциям | ![Yes][true] | ![No][false] |
честно говоря, я уже забыл, что происходит в tag team vs... там так же, как в обычном tag co-op, но есть разделение по командам? нужно будет попозже придумать вариант

2023-01-09 15:15 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Обновление карт в реальном времени | ![Partial][partial][^map-only] | ![Yes][true][^all-files] |
да, так будет лучше

2023-01-09 15:16 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Обновление карт в реальном времени | ![Partial][partial][^map-only] | ![Yes][true][^all-files] |
```suggestion
| Полное обновление карт | ![Partial][partial][^map-only] | ![Yes][true][^all-files] |
```

2023-01-09 16:28 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Режим прохождения карты по секциям | ![Yes][true] | ![No][false] |
Да, когда две команды совместно проходят карту

2023-01-14 00:36 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Что может быть острее cutting–edge?
вариант, обыгрывающий cutting edge, как в оригинале
```suggestion
А что ещё находится на острие прогресса?
```

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Мне нравится классический режим, где можно набрать очень много очков
#### Мне нравится классический режим _подсчёта_, где можно набрать очень много очков

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Мы постараемся это реализовать и вместе с тем не замедлить разработку других возможностей. Скины заработают, но потом.
Полностью утерян смысл оригинала. Пересмотри перевод

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Как сделать, чтобы в меню тоже использовался курсор из скина?
В меню? А настройки - это тоже меню? А экран результатов? Разве здесь не проще оставить вариант "курсор из скина по всей игре"? 
![image](https://user-images.githubusercontent.com/86934170/212473151-03de0675-11e2-4e53-9e17-bb02ecc4dc19.png)

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +В этом нет смысла: выше какого-то числа FPS разницы уже не видно. Lazer использует новые подходы, которые позволяют достичь быстрого отклика и не требуют высокой частоты отрисовки экрана. Дальше буде
... и не требуют высокой частоты отрисовки _кадров_.

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Lazer опрашивает устройства ввода с частотой 1000 раз в секунду вне зависимости от FPS, поэтому и число FPS ограничено 1000.
Частота не может быть измерена в "разах". Есть четкая единица измерения, принятая по всему миру - Герцы. Я против того, чтобы она была заменена на "разы".
... поэтому и _максимальное_ число FPS ограничено _до_ 1000.

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Если вы хотите проверить, как это влияет на задержку ввода, а также испытать своё восприятие, запустите тест задержки (latency certifier), открыв в настройках раздел `Отладка`.
Промах: 
![image](https://user-images.githubusercontent.com/86934170/212473405-3a94d0bd-61fe-49c5-a92c-3fe655911ad5.png)
![image](https://user-images.githubusercontent.com/86934170/212473435-37156c1b-1631-44e7-93ee-00e0adc0e105.png)
Все таки "верификатор задержки"

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Если устройства ввода опрашиваются с частотой 1000 Hz, как это скажется на моей мыши с частотой 8000 Hz?
... на моей _мышке_ с частотой 8000 Hz?

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Операционная система будет опрашивать устройство намного чаще, но это даст незначительные преимущества и может привести к непредвиденным нагрузкам. Мы рекомендуем ограничить частоту устройств ввода 1
Раз речь в вопросе про мышку, то стоит написать: 
Мы рекомендуем ограничить частоту _опроса мышки_ до 1000 Hz для поддержки стабильности системы.

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### В lazer нет нужной мне функции! / Мне не нравится какое-то изменение / Я нашёл баг, куда пожаловаться?
Мне не нравится какое-то изменение.
Точки нет
Кстати изменение этого предложения мне не нравится. Хуже читается

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Что может быть острее cutting–edge?
Если бы я читал, то вообще бы не понял, к чему тут "острие прогресса". Смысл то в том, что здесь используются оригинальные названия: lazer — cutting-edge. Второе из них нельзя переводить, иначе сам смысл обыгровки теряется.

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Почему lazer так долго в стадии разработки?
Почему lazer так долго _разрабатывается_?

2023-01-14 13:34 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Некоторые фильтры на странице поиска карт по-прежнему доступны только саппортерам.
Тут нужно оставить критерии сортировки. Фильтры - плохой вариант, в русском языке в таком контексте он не используется. Это слово, скорее, для прикладных вещей, нежели подобных. 
![image](https://user-images.githubusercontent.com/86934170/212474288-01cf7f39-91ea-436c-9382-a7030b013fdb.png)

2023-01-14 14:02 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Почему lazer так долго в стадии разработки?
Я думаю, что тут тоже теряется смысл, если не упомнянуть хоть что-нибудь про "основной клиент"
![image](https://user-images.githubusercontent.com/86934170/212475765-0cc56431-1ef1-48ba-ab17-967a9bf2f8e1.png)

2023-01-14 14:14 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Некоторые фильтры на странице поиска карт по-прежнему доступны только саппортерам.
Забудь про то, что сверху. Я исправлю на сайте, а твой вариант в этой строчке верный.

2023-01-14 22:29 UTC, TicClick requested changes

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Что может быть острее cutting–edge?
если без перевода оставить, обыгрывания тем более нет, так как просто используются термины без перевода. ладно, давай оставим оригинал, так хоть ясно будет.

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Некоторые фильтры на странице поиска карт по-прежнему доступны только саппортерам.
ты только не торопись, потому что
- при поиске используются именно **фильтры**, контролирующие результаты поиска. они на твоём скриншоте наверху (там, где статус прохождения, и всё, что выше и не попало в кадр)
- когда ты уже смотришь выдачу (то, что поиск вернул), её порядок можно изменить, пользуясь **критериями сортировки**. они на твоём скриншоте наверху, играют роль заголовков в таблице с результатами поиска.
- то, что написано на скриншоте справа от пиппи, относится к **фильтрам** (критерии, по которым ты ищешь)

но да, перевод нужно исправить (а в `Upgrading to lazer` — оставить мой вариант)

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Мы постараемся это реализовать и вместе с тем не замедлить разработку других возможностей. Скины заработают, но потом.
как тебе такой вариант (по следам обсуждения в дискорде)?
```suggestion
Мы постараемся это реализовать и вместе с тем не сломать новую, уже добавленную функциональность. Скины заработают, но потом.
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Как сделать, чтобы в меню тоже использовался курсор из скина?
да, настройки — это меню, экран результатов — уже нет, да. как насчёт такого?
```suggestion
#### Как сделать, чтобы курсор из скина использовался везде?
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +В этом нет смысла: выше какого-то числа FPS разницы уже не видно. Lazer использует новые подходы, которые позволяют достичь быстрого отклика и не требуют высокой частоты отрисовки экрана. Дальше буде
задумался, видимо. держи:
```suggestion
В этом нет смысла: выше какого-то числа FPS разницы уже не видно. Lazer использует новые подходы, которые позволяют достичь быстрого отклика и не требуют высокой частоты отрисовки кадров. Дальше будет только лучше, так как мы планируем добавить ещё пару улучшений.
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Мне нравится классический режим, где можно набрать очень много очков
да, допиши подсчёт, пожалуйста
```suggestion
#### Мне нравится классический режим подсчёта, где можно набрать очень много очков
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +| Режим прохождения карты по секциям | ![Yes][true] | ![No][false] |
отлично, давай тогда здесь поменяем
```suggestion
| Совместное прохождение карты | ![Yes][true] | ![No][false] |
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Lazer опрашивает устройства ввода с частотой 1000 раз в секунду вне зависимости от FPS, поэтому и число FPS ограничено 1000.
ты перечитай: 1000 **раз в секунду** — это и есть 1000 [герц](https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D1%80%D1%86_(%D0%B5%D0%B4%D0%B8%D0%BD%D0%B8%D1%86%D0%B0_%D0%B8%D0%B7%D0%BC%D0%B5%D1%80%D0%B5%D0%BD%D0%B8%D1%8F)). если тебе нравится именно единица измерения — ок, используй её
```suggestion
Lazer опрашивает устройства ввода с частотой 1000 Гц вне зависимости от FPS, поэтому и максимальное число FPS ограничено 1000.
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Если вы хотите проверить, как это влияет на задержку ввода, а также испытать своё восприятие, запустите тест задержки (latency certifier), открыв в настройках раздел `Отладка`.
«верификатор» по-простому, по-русски, — это и есть то, что тестирует, проверяет или подтверждает правдивость чего-л. если ты против слова «тест», давай поменяем на проверку, но пожалуйста, нужно избавиться от верификатора
```suggestion
Если вы хотите оценить, как это влияет на задержку ввода, а также испытать своё восприятие, запустите проверку задержки (latency certifier), открыв в настройках раздел `Отладка`.
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Если устройства ввода опрашиваются с частотой 1000 Hz, как это скажется на моей мыши с частотой 8000 Hz?
мне не критично ¯\\\_(ツ)_/¯ это и мышь, и мышка
```suggestion
#### Если устройства ввода опрашиваются с частотой 1000 Hz, как это скажется на моей мышке с частотой 8000 Hz?
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Операционная система будет опрашивать устройство намного чаще, но это даст незначительные преимущества и может привести к непредвиденным нагрузкам. Мы рекомендуем ограничить частоту устройств ввода 1
да, так лучше
```suggestion
Операционная система будет опрашивать устройство намного чаще, но это даст незначительные преимущества и может привести к непредвиденным нагрузкам. Мы рекомендуем ограничить частоту опроса мышки 1000 Гц для поддержки стабильности системы.
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### Почему lazer так долго в стадии разработки?
хм, мне казалось, я написал именно, что он «разрабатывается»... нужно назад вернуть

```suggestion
#### Почему lazer так долго разрабатывается?
```

(кстати, он Д**и**н)

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +#### В lazer нет нужной мне функции! / Мне не нравится какое-то изменение / Я нашёл баг, куда пожаловаться?
```suggestion
#### В lazer нет нужной мне функции! / Что-то изменилось, и мне это не нравится. / Куда сообщать о найденных багах?
```

2023-01-14 22:29 UTC, TicClick commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Скорее всего, мы уже знаем и планируем это исправить — поищите в [списке известных проблем](https://github.com/ppy/osu/issues) и [на странице обсуждений](https://github.com/ppy/osu/discussions). Если
вслед за новым вариантом заголовка
```suggestion
Скорее всего, мы уже об этом знаем и планируем это исправить — поищите в [списке известных проблем](https://github.com/ppy/osu/issues) и [на странице обсуждений](https://github.com/ppy/osu/discussions). Если там нет ничего, похожего на вашу проблему, смело создавайте [новое обсуждение](https://github.com/ppy/osu/discussions/new).
```

2023-01-15 13:08 UTC, Loreos7 commented on wiki/Help_centre/Upgrading_to_lazer/ru.md
> +Мы постараемся это реализовать и вместе с тем не замедлить разработку других возможностей. Скины заработают, но потом.
Да, неплохо

2023-01-15 16:20 UTC, TicClick approved these changes

2023-01-15 16:22 UTC, merged