[PT-BR] Add `Upgrading to lazer`
ppy/osu-wiki pull request #8541
Opened 2022-12-30 02:47 UTC by Utor220

## Self-check 

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2022-12-31 17:49 UTC, The-Last-Cookie commented
Please don't forget to apply the changes from #8548.

2023-01-01 09:33 UTC, Utor220 reviewed
Applied changes from #8548

2023-01-01 13:47 UTC, LeoFLT requested changes
lgtm otherwise

2023-01-01 13:47 UTC, LeoFLT commented on wiki/Help_centre/Upgrading_to_lazer/pt-br.md
> +O objetivo final é que esta versão seja lançada como uma atualização que irá substituir completamente a versão estável existente do jogo, mas ainda há algum trabalho a ser feito antes que isso seja p
```suggestion
O objetivo final é que esta versão seja lançada como uma atualização que irá substituir completamente a versão estável existente do jogo, mas ainda há algum trabalho a ser feito antes que isso seja possível. No fim das contas, **os jogadores** irão ditar quando isso acontecerá e nós iremos continuar a dar suporte para a versão anterior até que os jogadores tenham migrado.
```
Leve pleonasmo

2023-01-01 13:47 UTC, LeoFLT commented on wiki/Help_centre/Upgrading_to_lazer/pt-br.md
> +| colorização das notas baseado em timing no osu!mania  | ![No][false] | ![Yes][true] |
```suggestion
| colorização das notas baseado em timing no osu!mania | ![No][false] | ![Yes][true] |
```
Extra space

2023-01-02 02:23 UTC, Utor220 commented on wiki/Help_centre/Upgrading_to_lazer/pt-br.md
> +O objetivo final é que esta versão seja lançada como uma atualização que irá substituir completamente a versão estável existente do jogo, mas ainda há algum trabalho a ser feito antes que isso seja p
Pronto, já mudei isso!

2023-01-02 02:23 UTC, Utor220 commented on wiki/Help_centre/Upgrading_to_lazer/pt-br.md
> +| colorização das notas baseado em timing no osu!mania  | ![No][false] | ![Yes][true] |
Resolvido também!

2023-01-02 02:41 UTC, LeoFLT approved these changes

2023-01-07 10:49 UTC, The-Last-Cookie commented
And there's another one: #8576

2023-01-09 13:54 UTC, LeoFLT commented
Translation for the new bit from #8576:

*Aviso: Nós ainda estamos fazendo ajustes ao equilíbrio do jogo e mecânicas. Por enquanto, **scores feitas no lazer não devem ser consideradas permanentes**.*

2023-01-09 14:08 UTC, merged