[DE] Add mapping and modding hub discord server articles
ppy/osu-wiki pull request #8555
Opened 2023-01-01 15:47 UTC by The-Last-Cookie

While reviewing, keep in mind that these articles are very similar in their structure and also have the same phrases most of the times. Thus, I often copied parts over with minimal changes.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-02 09:36 UTC, IceDynamix requested changes

2023-01-02 09:36 UTC, IceDynamix commented on wiki/Community/Discord_servers/osu!taiko_Modding_&_Mapping_Hub/de.md
> +In order to gain access to the channels, users must verify their identity with their osu! accounts using [AxerBot](https://osu.ppy.sh/community/forums/topics/1604925).
forgot to remove this paragraph

2023-01-02 13:42 UTC, The-Last-Cookie commented on wiki/Community/Discord_servers/osu!taiko_Modding_&_Mapping_Hub/de.md
> +In order to gain access to the channels, users must verify their identity with their osu! accounts using [AxerBot](https://osu.ppy.sh/community/forums/topics/1604925).
thanks for spotting :+1:

2023-01-09 13:13 UTC, TicClick approved these changes

2023-01-09 13:18 UTC, merged