[ES] Add/Update some `People` articles
ppy/osu-wiki pull request #8556
Opened 2023-01-01 21:33 UTC by agatemosu

From #8505 for better review

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-02 14:34 UTC, juankristal requested changes
Left some things to recheck, mostly standardizing the usage of "Colaboradores" over "Contribuidores"

2023-01-02 14:34 UTC, juankristal commented on wiki/People/The_Team/Developers/es.md
> +*Para obtener información detallada sobre las contribuciones al proyecto de osu!web, véase: [Contribuidores del repositorio `osu-web`](https://github.com/ppy/osu-web/graphs/contributors)*
Usaria "colaboradores" en lugar de "contribuidores"

2023-01-02 14:34 UTC, juankristal commented on wiki/People/The_Team/Developers/es.md
> +*Para obtener información detallada sobre las contribuciones al proyecto de osu!framework, véase: [Contribuidores del repositorio `osu-framework`](https://github.com/ppy/osu-framework/graphs/contribu
Usaria "colaboradores" en lugar de "contribuidores"

2023-01-02 14:34 UTC, juankristal commented on wiki/People/The_Team/Developers/es.md
> +*Para obtener información detallada sobre las contribuciones al proyecto de osu!, véase: [Contribuidores del repositorio `osu`](https://github.com/ppy/osu/graphs/contributors)*
Usaria "colaboradores" en lugar de "contribuidores"

2023-01-02 14:34 UTC, juankristal commented on wiki/People/The_Team/Developers/es.md
>  ### Contribuidores
Usaria "colaboradores" en lugar de "contribuidores"

2023-01-02 14:34 UTC, juankristal commented on wiki/People/The_Team/Developers/es.md
> +Los desarrolladores de osu! mantienen el juego y el sitio web funcionando corrigiendo errores y agregando nuevas funciones. La mayoría de ellos son empleados de ppy Pty Ltd, la empresa propietaria de
Creo que "funcionalidades" es mas acorde que "funciones".

2023-01-02 14:34 UTC, juankristal commented on wiki/People/Community_Contributors/es.md
> +Los **colaboradores de la comunidad** son las personas que se han encargado de brindar servicio a la comunidad de osu! a un gran costo para ellos mismos: herramientas y características que muchos de
Cambiaria el wording de esto a algo como:

"Los colaboradores de la comunidad son aquellas personas que han sobresalido en su trabajo brindando servicios a la comunidad de osu! o bien creando herramientas o funcionalidades que muchos de nosotros damos por sentado hoy"

2023-01-02 14:34 UTC, juankristal commented on wiki/People/Performance_Points_Committee/es.md
> +El panel de osu!mania se formó el 22 de abril de 2022 en respuesta a [otra encuesta de la comunidad sobre los puntos de rendimiento y la calificación por estrellas en osu!taiko y osu!mania](https://o
Tecnicamente ya no es al principio de este año. Evitaria referenciar al tiempo para evitar updates a futuro

2023-01-02 14:38 UTC, agatemosu commented on wiki/People/Performance_Points_Committee/es.md
> +El panel de osu!mania se formó el 22 de abril de 2022 en respuesta a [otra encuesta de la comunidad sobre los puntos de rendimiento y la calificación por estrellas en osu!taiko y osu!mania](https://o
Se refiere al año mencionado anteriormente

2023-01-02 14:49 UTC, juankristal commented on wiki/People/Performance_Points_Committee/es.md
> +El panel de osu!mania se formó el 22 de abril de 2022 en respuesta a [otra encuesta de la comunidad sobre los puntos de rendimiento y la calificación por estrellas en osu!taiko y osu!mania](https://o
Ah claro, tenes razón. Mala mia.

2023-01-02 15:04 UTC, agatemosu commented
¿Sería mejor cambiar todos los usos de `colaborar`/`colaboración`/`colaborador` por `contribuir`/`contribución`/`contribuyente o contribuidor` o así está bien?

2023-01-02 15:27 UTC, juankristal commented
Creeria que usar colaborador y sus variantes es mas apropiado. Contribuyentes entiendo que refiere a obligaciones cuando colaboración refiere a motivaciones o voluntariados (que es el caso de los Community Contributors de osu)

2023-01-03 16:35 UTC, agatemosu commented
Pondré `contribuir`, si busco `colaborar` en el DLE, me aparece `contribuir` como la definición que busco

2023-01-09 13:56 UTC, juankristal commented
Esto ya estaría listo? No entendí si ibas a hacer una revisión adicional o no considerando el último comentario.

2023-01-09 16:45 UTC, agatemosu commented
Primero lo cambié y después lo pregunté, no estaba segura de si esa palabra estaría mal

2023-01-09 17:13 UTC, juankristal commented
Mientras sea consistente ambas opciones me parecen válidas. Si preferís mantener contribuir está bien. Es para saber a la hora de hacer el re-review

2023-01-09 17:33 UTC, agatemosu commented
Vale pues sí, en todo el artículo usé contribuir

2023-01-09 18:57 UTC, agatemosu commented
Vale pues sí, en todo el artículo usé contribuir

________________________________
From: Juan Ignacio Kristal ***@***.***>
Sent: Monday, January 9, 2023 6:13:18 PM
To: ppy/osu-wiki ***@***.***>
Cc: Ana ***@***.***>; Author ***@***.***>
Subject: Re: [ppy/osu-wiki] [ES] Add/Update some `People` articles (PR #8556)


Mientras sea consistente ambas opciones me parecen válidas. Si preferís mantener contribuir está bien. Es para saber a la hora de hacer el re-review

—
Reply to this email directly, view it on GitHub<https://github.com/ppy/osu-wiki/pull/8556#issuecomment-1375971450>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOBZ5HHNUNMN7FZZKUSJGYLWRRBK5ANCNFSM6AAAAAATOKNRPM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-09 18:57 UTC, juankristal approved these changes

2023-01-09 18:58 UTC, merged