Move list of wiki maintainers to `People`
ppy/osu-wiki pull request #8588
Opened 2023-01-08 17:42 UTC by Walavouchey

had this on the to-do list for a while

updated title in languages i was confident i wouldn't run into grammar shenanigans

`people` and not `people/the_team` to follow pattern of no user group

2023-01-08 17:53 UTC, RockRoller01 requested changes
Current TL is grammatically wrong, but that doesn't matter much as the chosen Noun is meh. The article itself uses "Betreuer", tho maybe "Instandthalter" would be better, but I leave that to the people that are more familiar with the german TL

2023-01-08 17:53 UTC, RockRoller01 commented on wiki/Main_Page/de.md
> +[Community-Mitwirkende](/wiki/People/Community_Contributors) • [Benutzer mit einzigartigen Titeln](/wiki/People/Users_with_unique_titles) • [Turnierkomitee](/wiki/People/Tournament_Committee) • [Perf
```suggestion
[Community-Mitwirkende](/wiki/People/Community_Contributors) • [Benutzer mit einzigartigen Titeln](/wiki/People/Users_with_unique_titles) • [Turnierkomitee](/wiki/People/Tournament_Committee) • [Performance-Punkte-Komitee](/wiki/People/Performance_Points_Committee) • [Betreuer des osu!-Wikis](/wiki/people/osu!_wiki_maintainers)
```

2023-01-08 17:53 UTC, RockRoller01 commented on wiki/People/de.md
> +- [Verantwortlichen des osu!-Wikis](osu!_wiki_maintainers)
```suggestion
- [Betreuer des osu!-Wikis](osu!_wiki_maintainers)
```

2023-01-08 17:53 UTC, RockRoller01 commented on wiki/People/osu!_wiki_maintainers/de.md
> +# Verantwortlichen des osu!-Wikis
```suggestion
# Betreuer des osu!-Wikis
```

2023-01-08 19:06 UTC, The-Last-Cookie commented
`Betreuer` sounds fine to me.

The word `Instandhalter` was never used as far as I know.

All wiki articles use both `Betreuer` and `Verantwortlicher` for the translation of maintainer to have some word variety. Maybe `Leiter` is a good alternative too? :thinking:

Regardless of this, the changes that @RockRoller01 proposes can be merged into the branch in my opinion.

2023-01-08 21:12 UTC, TicClick approved these changes
tentative approval from me -- not sure how many changes you want to apply to the translations right now; I included mine, the rest (merge or not yet) is up to you

2023-01-09 06:28 UTC, Walavouchey commented
i indeed wasn't intending on updating all of them myself, just the ones that seemed feasible to do quickly (and i only changed the titles)

2023-01-09 06:29 UTC, merged