[FR] Update `Tournaments/Official_support`
ppy/osu-wiki pull request #8599
Opened 2023-01-11 07:34 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-15 17:01 UTC, Ganondorf-1 requested changes

2023-01-15 17:01 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +  - L'utilisation de bots est autorisée lors des matchs de la phase de qualification, à condition qu'ils soit supervisée par un membre du staff.
```suggestion
  - L'utilisation de bots est autorisée lors des matchs de la phase de qualification, à condition qu'ils soient supervisés par un membre du staff.
```

2023-01-15 18:33 UTC, Ganondorf-1 approved these changes

2023-01-16 01:00 UTC, TicClick approved these changes

2023-01-16 01:04 UTC, merged