[JA] Add Beatmap related pages and resolve some pages' errors
ppy/osu-wiki pull request #8604
Opened 2023-01-12 08:42 UTC by JackTriton0901

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

## Changes

Add `ja.md` for :
- `Beatmap/Beatmap collaborations`
- `Beatmap/Beatmap host`
- `Beatmap/Genre and Language`
- `Beatmap/Guest difficulty`
- `Beatmap/Hype`
- `Beatmap/Marathon`
- `Game mode/osu!taiko`
- `Modding/Kudosu`
- `Modding/Mod for mod`
- `Modding/Mod request`
- `Modding/Modder`
- `Modding/Normal mod`
- `Modding/Timestamp`
- `Ranking Criteria/Difficulty Naming`
- `Ranking Criteria/Scaling BPM`
- `Skinning/Skinner`
- `Skinning/osu!taiko`

Delete duplicated information for `Bit rate` 

Resolve markdown error of `Skinning`
______
Where can I find Japanese reviewer

2023-01-12 09:25 UTC, JackTriton0901 commented
Fixed some files

2023-01-12 15:36 UTC, JackTriton0901 commented
Changed all `\r\n` to `\n` for `Modding/Kudosu`.

2023-01-13 08:15 UTC, JackTriton0901 commented
Checked on github.dev, `Kudosu` page’s `\r\n` is replaced to `\n`.

2023-01-13 19:32 UTC, Walavouchey commented
in the future, please make separate pull requests for related pages. if you intend on getting this reviewed, then grouping everything into one pr will only make it take a while.

don't worry about the line ending errors for now - they can be fixed before merging.

2023-01-16 00:40 UTC, TicClick commented
this definitely needs splitting into several small, at least thematic if not per-article pull requests. one more thing, please don't merge the `master` branch into yours, a maintainer will do that when necessary

2023-01-19 05:17 UTC, JackTriton0901 commented
To fix the link error on `Game mode/osu!taiko`, I have to edit `Gameplay/Grade`.
I'll do this on different pull request.

2023-01-20 08:52 UTC, peppy submitted a review, later dismissed

2023-01-20 08:52 UTC, peppy commented
I've done a prelim check of the translation and it's fine.

2023-01-20 23:40 UTC, TicClick requested changes
minor notes, fix this and I'll merge

2023-01-20 23:40 UTC, TicClick commented on wiki/Beatmap/Beatmap_host/ja.md
> +**ビートマップホスト** は[ビートマップ](/wiki/Beatmap)のマネージャーであり投稿者のことである。ビートマップのほとんどの難易度を作成し[ゲスト難易度](/wiki/Beatmap/Guest_difficulty)の管理も行う。[beatmap ranking procedure](/wiki/Beatmap_ranking_procedure)を進行させるために[Mod](
"beatmap ranking procedure" needs to be translated -- it's a regular phrase, not a term

2023-01-20 23:40 UTC, TicClick commented on wiki/Beatmap/Genre_and_language/ja.md
> +![A screenshot of genre, language, and tags on a beatmap page](img/beatmap-info.png "ビートマップページに掲載されているジャンルと言語")
image tooltip needs to be translated

2023-01-20 23:40 UTC, TicClick commented on wiki/Beatmap/Genre_and_language/ja.md
> +![The available filters on the beatmap listing](img/beatmap-listing.png?1)
image tooltip needs to be translated

2023-01-21 00:00 UTC, JackTriton0901 commented on wiki/Beatmap/Beatmap_host/ja.md
> +**ビートマップホスト** は[ビートマップ](/wiki/Beatmap)のマネージャーであり投稿者のことである。ビートマップのほとんどの難易度を作成し[ゲスト難易度](/wiki/Beatmap/Guest_difficulty)の管理も行う。[beatmap ranking procedure](/wiki/Beatmap_ranking_procedure)を進行させるために[Mod](
translated to ビートマップのランクをさせるために

2023-01-21 00:01 UTC, JackTriton0901 commented on wiki/Beatmap/Genre_and_language/ja.md
> +![A screenshot of genre, language, and tags on a beatmap page](img/beatmap-info.png "ビートマップページに掲載されているジャンルと言語")
translated to ビートマップページに掲載されているジャンルと言語

2023-01-21 00:01 UTC, JackTriton0901 commented on wiki/Beatmap/Genre_and_language/ja.md
> +![The available filters on the beatmap listing](img/beatmap-listing.png?1)
translated to ビートマップリストのフィルター

2023-01-21 14:19 UTC, peppy approved these changes

2023-01-21 23:46 UTC, TicClick approved these changes

2023-01-21 23:48 UTC, merged