Create the discussion for task management in `The_Team`
ppy/osu-wiki pull request #8606
Opened 2023-01-13 02:55 UTC by Blooshing

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-13 16:36 UTC, Walavouchey requested changes

2023-01-13 16:36 UTC, Walavouchey commented on wiki/People/The_Team/Global_Moderation_Team/en.md
> +| ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578) |  | Tournament management{^task-Azer] |
```suggestion
| ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578) |  | Tournament management[^task-Azer] |
```

2023-01-13 16:36 UTC, Walavouchey commented on wiki/People/The_Team/Global_Moderation_Team/en.md
> +[^task-Azer]: Is a part of the GMT but they are not held to the same responsibilities.
taking from https://discord.com/channels/188630481301012481/218677502141399041/932333129664962560

```suggestion
[^task-Azer]: While not actually being part of the GMT itself, Azer is in the user group by technicality due to needing GMT-level permissions as a World Cup organiser.
```

2023-01-13 23:34 UTC, LeoFLT commented on wiki/People/The_Team/Global_Moderation_Team/en.md
> +[^task-Azer]: While not actually being part of the GMT itself, Azer is in the user group by technicality due to needing GMT-level permissions as a World Cup organiser.
```suggestion
[^task-Azer]: While not actually being part of the GMT itself, Azer is in the user group by technicality due to needing GMT-level permissions as a World Cup organiser.

```

2023-01-14 10:53 UTC, Walavouchey approved these changes

2023-01-14 10:53 UTC, merged