[FR] Add `People/The_Team/Nomination_Assessment_Team/SEV_rating`
ppy/osu-wiki pull request #8613
Opened 2023-01-14 21:27 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-15 18:29 UTC, Ganondorf-1 requested changes

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +Se trouve ci-dessous des exemples de notes SEV et la manière dont elles sont grossièrement interprétées par les évaluateurs :
```suggestion
Se trouvent ci-dessous des exemples de notes SEV et la manière dont elles sont grossièrement interprétées par les évaluateurs :
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +| 1/1 | Il y a eu un problème qui aurait pu être résolu si les BNx avaient été plus attentifs. |
```suggestion
| 1/1 | Il y a eu un problème qui aurait pu être résolu si les BNs avaient été plus attentifs. |
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +| 2/0 | Un problème flagrant dans les paramètres de la carte, comme les métadonnées, a en quelque sorte été oublié. |
```suggestion
| 2/0 | Un problème flagrant dans les paramètres de la beatmap, comme les métadonnées, a d'une manière ou d'une autre été manqué. |
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +| 2/1 | Un problème flagrant dans la jouabilité de la carte, comme l'absence de hitsounding, a été manqué. |
```suggestion
| 2/1 | Un problème flagrant dans la jouabilité de la beatmap, comme l'absence de hitsounding, a été manqué. |
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +| 2/2 | Un problème si grave qu'il est difficile de ne pas le repérer, comme de objets concurrents, a été manqué. |
```suggestion
| 2/2 | Un problème si grave qu'il est difficile de ne pas le repérer, comme des objets concurrents, a été manqué. |
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +Voici une liste exhaustive des raisons pour lesquelles des nominations ont été remises à zéro, avec leur note SEV respective. Ces raisons sont basées sur les statistiques de toutes les évaluations SE
```suggestion
Voici une liste exhaustive des raisons pour lesquelles des nominations ont été réinitialisées, avec leur note SEV respective. Ces raisons sont basées sur les statistiques de toutes les évaluations SEV établies dans le mode de jeu osu! entre février 2020 et avril 2021, avec des pourcentages pour montrer la fréquence des problèmes.
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +Cette liste ne couvre pas toutes les raisons possibles de réinitialisation, et le NAT peut évaluer différemment les réinitialisations pour les mêmes raisons énumérées, en fonction du contexte spécifi
```suggestion
Cette liste ne couvre pas toutes les raisons possibles de réinitialisation, et la NAT peut évaluer différemment les réinitialisations pour les mêmes raisons énumérées, en fonction du contexte spécifique.
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +Les réinitialisations de métadonnées n'ont *jamais* une gravité supérieure à 0, car elles n'affectent pas le jeu.
```suggestion
Les réinitialisations dues à des problèmes de métadonnées n'ont *jamais* une gravité supérieure à 0, car ils n'affectent pas le gameplay.
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +## Évidence et sévérité
```suggestion
## Évidence et gravité
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **0/0:** (70%)
```suggestion
- **0/0 :** (70%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Ajout de tags pour un nouvel Featured Artist
```suggestion
  - Ajout de tags pour un nouveau Featured Artist
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Ajout de tags plus descriptives mais non requises par les critères de classement
```suggestion
  - Ajout de tags plus descriptifs mais non requis par les critères de classement
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/0:** (23%)
```suggestion
- **1/0 :** (23%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Petites erreurs de romanisation et de capitalisation
```suggestion
  - Petites erreurs de romanisation et de majuscules
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **2/0:** (5%)
```suggestion
- **2/0 :** (5%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Mappeurs de guest difficulty manquant dans les tags
```suggestion
  - Mappeurs de guest difficulty manquants dans les tags
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +Les réinitialisations dues à des problèmes de mapping ont rarement 2 d'évidence, car elles nécessitent une bonne connaissance du mapping/modding pour être identifiées facilement.
```suggestion
Les réinitialisations dues à des problèmes de mapping ont rarement 2 d'évidence, car ils nécessitent une bonne connaissance du mapping/modding pour être identifiés facilement.
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **0/0:** (46%)
```suggestion
- **0/0 :** (46%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/1:** (28%)
```suggestion
- **1/1 :** (28%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Erreurs de mapping courantes qui ont un impact négatif notable sur la map
```suggestion
  - Erreurs de mapping courantes qui ont un impact négatif notable sur la beatmap
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Des pics de difficulté injustifiés (comme s'ils ne correspondaient pas à la chanson).
```suggestion
    - Des pics de difficulté injustifiés (ils ne correspondent pas à la musique).
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/2:** (14%)
```suggestion
- **1/2 :** (14%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Overmapper d'une manière qui est mal introduite/exécutée
```suggestion
    - Mapper trop d'éléments d'une manière qui est mal introduite/exécutée
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Ajustement du point d'aperçu/temps des kiai
```suggestion
  - Ajustement du point d'aperçu/des kiai
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **0/0:** (20%)
```suggestion
- **0/0 :** (20%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Mapping d'un grand stream sur plusieurs layers et sons distincts
```suggestion
    - Mapping d'un grand stream sur plusieurs plans sonores et plusieurs sons distincts
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Pour un timing simple, < 6 ms off
```suggestion
    - Pour un timing simple, décalage de < 6 ms
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Pour un timing complexe, < 10 ms off
```suggestion
    - Pour un timing complexe, décalage de < 10 ms
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/1:** (49%)
```suggestion
- **1/1 :** (49%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Pour un timing simple, ~6-12 ms off
```suggestion
    - Pour un timing simple, décalage d'environ 6-12 ms
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Pour un timing complexe, ~10+ ms off
```suggestion
    - Pour un timing complexe, décalage d'environ 10+ ms
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +Les réinitialisations liées aux fichiers beatmap n'ont presque jamais une gravité supérieure à 0, car elles n'affectent généralement pas la jouabilité. Une exception est l'utilisation de hitsounds da
```suggestion
Les réinitialisations liées aux fichiers beatmap n'ont presque jamais une gravité supérieure à 0, car ils n'affectent généralement pas la jouabilité. Une exception est l'utilisation de hitsounds dans le storyboard pour remplacer les hitsounds actifs.
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **0/0:** (64%)
```suggestion
- **0/0 :** (64%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/0:** (19%)
```suggestion
- **1/0 :** (19%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **2/0:** (6%)
```suggestion
- **2/0 :** (6%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **0/0:** (11%)
```suggestion
- **0/0 :** (11%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Fin de sliders légèrement unsnapped que des outils ne peuvent pas détecter
```suggestion
  - Fin de slider légèrement unsnapped que les outils ne peuvent pas détecter
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/0:** (21%)
```suggestion
- **1/0 :** (21%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Fin de sliders légèrement unsnapped que des outils pourraient aider à trouver
```suggestion
    - Fin de slider légèrement unsnapped que les outils pourraient aider à trouver
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/1:** (42%)
```suggestion
- **1/1 :** (42%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/2:** (8%)
```suggestion
- **1/2 :** (8%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +    - Des snappings ratés qui provoquent toujours des 100, parfois des 50, ou même des note locks
```suggestion
    - Des snappings ratés qui provoquent toujours des 100, parfois des 50, ou même des notelocks
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **0/0:** (73%)
```suggestion
- **0/0 :** (73%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/0:** (14%)
```suggestion
- **1/0 :** (14%)
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +  - Mauvais hitsounding, par exemple l'utilisation de claps/snares/cymbales injustifiés sur chaque temps ou autre.
```suggestion
  - Mauvais hitsounding, par exemple l'utilisation de claps/snares/cymbals injustifiée sur chaque temps ou autre.
```

2023-01-15 18:29 UTC, Ganondorf-1 commented on wiki/People/The_Team/Nomination_Assessment_Team/SEV_rating/fr.md
> +- **1/1:** (6%)
```suggestion
- **1/1 :** (6%)
```

2023-01-28 19:02 UTC, TicClick approved these changes

2023-01-28 19:04 UTC, merged