Update `The_People` Listings
ppy/osu-wiki pull request #8617
Opened 2023-01-15 01:26 UTC by Blooshing

NEW YEAR NEW STAFF LOG

(>‿◠)✌

(っ＾▿＾)۶🍸🌟🍺٩(˘◡˘ )

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-15 04:24 UTC, aceticke requested changes

2023-01-15 04:24 UTC, aceticke commented on wiki/People/The_Team/Beatmap_Nominators/en.md
> +| ::{ flag=ID }:: [-Keitaro](https://osu.ppy.sh/users/3378391) | Indonesian |
```suggestion
```

-Keitaro is a Full Beatmap Nominator, apply for all languages

2023-01-15 04:24 UTC, aceticke commented on wiki/People/The_Team/Staff_Log/2023/en.md
> +- 2023-01-14: Removed [Quenlla](https://osu.ppy.sh/users/4725379) from **NAT** to **osu! Alumni**
```suggestion
- 2023-01-14: Moved [Quenlla](https://osu.ppy.sh/users/4725379) from **NAT** to **osu! Alumni**
```

2023-01-15 04:24 UTC, aceticke commented on wiki/People/The_Team/Staff_Log/2023/en.md
> +- 2023-01-09: Added [-Keitaro](https://osu.ppy.sh/users/3378391) to **Probationary BN**
```suggestion
- 2023-01-09: Added [-Keitaro](https://osu.ppy.sh/users/3378391) to **BN**
```

2023-01-15 04:27 UTC, aceticke commented on wiki/People/The_Team/Staff_Log/2023/en.md
> +-->
```suggestion
-->

```
new line to fix error

2023-01-15 04:28 UTC, aceticke commented on wiki/People/The_Team/Staff_Log/2022/en.md
> +
```suggestion
```
nuke this to fix error

2023-01-16 21:52 UTC, TicClick approved these changes

2023-01-16 21:55 UTC, merged