[ZH]Translated `Explicit_Content`
ppy/osu-wiki pull request #8628
Opened 2023-01-16 11:21 UTC by Sunnyboy971

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-18 09:05 UTC, YumeMuzi requested changes
seems fine.
但这些文章的其他段落可能也需要修改对应的用词（谱面介绍、少儿不宜等）。需要注意。

2023-01-18 09:05 UTC, YumeMuzi commented on wiki/Beatmap/Countdown/zh.md
> +倒计时动画可以通过[皮肤](/wiki/Skinning/Interface#countdown)修改。
```suggestion
倒计时动画可以通过[自定义皮肤](/wiki/Skinning/Interface#countdown)修改。
```

2023-01-18 09:05 UTC, YumeMuzi commented on wiki/Beatmap/Countdown/zh.md
> +在一张[谱面](/wiki/Beatmap)开头，可能会出现**倒计时**。这对于突然迅速开始的歌曲很有用，但大多数谱面不需要启用它。除了 [osu!taiko](/wiki/Game_mode/osu!taiko) 谱面，可以在[song setup](/wiki/Client/Beatmap_editor/Song_Setup)菜单的`Design`标签页下开启或关闭倒计时。
```suggestion
在一张[谱面](/wiki/Beatmap)开头，可能会出现**倒计时**。这对于突然迅速开始的歌曲很有用，但除了 [osu!taiko](/wiki/Game_mode/osu!taiko) 谱面之外，不需要在大多数谱面中使用它。可以在[歌曲设置 (Song Setup)](/wiki/Client/Beatmap_editor/Song_Setup)菜单的 `设计 (Design)` 标签页下开启或关闭倒计时。
```

2023-01-18 09:05 UTC, YumeMuzi commented on wiki/Rules/Explicit_Content/zh.md
> +# 少儿不宜内容
推荐将 `少儿不宜` 改为 `不良内容`。（按中文语境来说这游戏大多数玩家都是未成年吧，，）

2023-01-18 09:05 UTC, YumeMuzi commented on wiki/Rules/Explicit_Content/zh.md
> +如果想要辨别某些内容是否应该被标记为少儿不宜，你可以看看主流音频流媒体服务是否在其平台上将其列为少儿不宜。访问[Spotify](https://www.spotify.com)是一个很好的开始。
```suggestion
如果想要辨别某些内容是否应该被标记为少儿不宜，你可以看看主流音频流媒体服务是否在其平台上将其列为少儿不宜。访问 [Spotify](https://www.spotify.com) 是一个很好的开始。
```
加空格

2023-01-18 09:05 UTC, YumeMuzi commented on wiki/Beatmap/Beatmap_description/zh.md
> +- 所有 [Guest 难度](/wiki/Beatmap/Guest_difficulty)及其制作者的列表
```suggestion
- 所有[客串难度](/wiki/Beatmap/Guest_difficulty)及其制作者的列表
```

2023-01-18 09:49 UTC, Sunnyboy971 commented on wiki/Rules/Explicit_Content/zh.md
> +# 少儿不宜内容
我一开始翻译这篇文章的时候是按照 Lazer 版上的说法来的。确实比较奇怪...;)

2023-01-27 04:55 UTC, YumeMuzi approved these changes

2023-01-28 03:02 UTC, YumeMuzi approved these changes

2023-01-28 03:07 UTC, YumeMuzi commented
only [osu! wiki maintainers]'(https://osu.ppy.sh/wiki/en/People/osu%21_wiki_maintainers) approved could make the PR merged, be careful!

2023-01-28 03:12 UTC, Sunnyboy971 commented
Maybe a native reviewer's approval is needed for them to ensure the translation's quality...
So I'm used to request reviews after commits :smile_cat:

2023-01-28 15:48 UTC, TicClick commented
an explicit approval shows that someone has actually read through the new changes, so thank you. for really minor changes it is not necessary, but anything else kind of requires a new look.

2023-01-28 15:49 UTC, TicClick submitted a review, later dismissed

2023-01-28 15:51 UTC, TicClick approved these changes

2023-01-28 15:52 UTC, merged