[FR] Update `osu!_wiki/Maintenance`
ppy/osu-wiki pull request #8631
Opened 2023-01-16 17:19 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-19 17:27 UTC, Ganondorf-1 requested changes

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +Si vous avez besoin d'aide pour décrypter les erreurs de vérification des CI, ou pour résoudre des problèmes, demandez dans le salon de discussion `#osu-wiki` sur Discord.
```suggestion
Si vous avez besoin d'aide pour décrypter les messages d'erreur des CI checks, ou pour résoudre des problèmes, demandez dans le salon de discussion `#osu-wiki` sur Discord.
```

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +#### Contourner une CI checks
```suggestion
#### Contourner une CI check
```

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +Les CI checks empêchent normalement les pull requests contenant des erreurs d'être fusionnées. Cependant, en cas de fausses erreurs ou de découverte de bugs dans les vérifications, il est toujours po
```suggestion
Les CI checks empêchent normalement les pull requests contenant des erreurs d'être merged. Cependant, en cas de fausses erreurs ou de découverte de bugs dans les vérifications, il est toujours possible de les contourner par sécurité. Il existe quelques situations dans lesquelles il est acceptable de contourner intentionnellement une CI check, comme indiqué ci-dessous. Contactez un [maintainer](/wiki/People/osu!_wiki_maintainers) si vous devez contourner une CI check pour une raison non mentionnée ici.
```

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +| 2 | Markdown | [remark](https://github.com/remarkjs/remark) via [`scripts/ci/run_remark.sh`](https://github.com/ppy/osu-wiki/blob/master/scripts/ci/run_remark.sh) | Vérifie si la syntaxe Markdown e
```suggestion
| 2 | Markdown | [remark](https://github.com/remarkjs/remark) via [`scripts/ci/run_remark.sh`](https://github.com/ppy/osu-wiki/blob/master/scripts/ci/run_remark.sh) | Vérifie si la syntaxe Markdown est correcte et cohérente dans les articles du wiki et les articles de news. | Ajouter `<!-- lint ignore rule-name -->` au-dessus de la ligne incriminée, où `rule-name` est la règle à ignorer. |
```

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +| 4 | Liens wiki cassés | La commande `check-links` de [`osu-wiki-tools`](https://github.com/Walavouchey/osu-wiki-tools) | Vérifie si les [liens wiki](/wiki/Article_styling_criteria/Formatting#liens-
```suggestion
| 4 | Liens wiki cassés | La commande `check-links` de [`osu-wiki-tools`](https://github.com/Walavouchey/osu-wiki-tools) | Vérifie si les [liens wiki](/wiki/Article_styling_criteria/Formatting#liens-wiki) internes pointent vers un article du wiki, un article de news (pour les liens d'articles de news), ou une section de celui-ci. | Ajouter `SKIP_WIKILINK_CHECK` n'importe où dans la description de la pull request. |
```

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +- [osu-wiki-tools](https://github.com/Walavouchey/osu-wiki-tools): un utilitaire Python pour les vérifications automatisées (liens cassés, articles périmés) utilisé en CI
```suggestion
- [osu-wiki-tools](https://github.com/Walavouchey/osu-wiki-tools) : un utilitaire Python pour les vérifications automatisées (liens cassés, articles obsolètes) utilisé en CI
```

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +- [scissors](https://github.com/TicClick/scissors): un utilitaire Rust pour vérifier les incompatibilités de nom d'utilisateur et de drapeau de pays dans les liens d'utilisateur
```suggestion
- [scissors](https://github.com/TicClick/scissors) : un utilitaire Rust pour vérifier les incompatibilités de nom d'utilisateur et de drapeau de pays dans les liens d'utilisateurs
```

2023-01-19 17:27 UTC, Ganondorf-1 commented on wiki/osu!_wiki/Maintenance/fr.md
> +Une traduction peut être fusionnée sans native review s'il s'est écoulé plus d'une semaines depuis sa date de création.
```suggestion
Une traduction peut être merged sans review d'un traducteur natif s'il s'est écoulé plus d'une semaine depuis la date de création de la Pull Request.
```

2023-01-28 18:56 UTC, TicClick approved these changes

2023-01-28 18:58 UTC, merged