[DE] Retranslate `Guides/Getting_your_map_modded`
ppy/osu-wiki pull request #8635
Opened 2023-01-17 12:56 UTC by The-Last-Cookie

The overall structure and also the phrases weren't the same as in the English original. To remove the need of adding a `outdated_translation` tag, I retranslated the article.

## Notes

- I have translated `Modding queue` with `Modding-Warteschlange`. The French wiki does this translation and so my decision was to do it as well.
- Not sure on the translation of `Beatmap Nominators`. I believe we once decided to keep the original group name (for every group, for example also Mapper's Guild), and in some cases it actually sounds okay-ish, but there were cases where I found it weird to keep the English name. Thus, I've decided to translate it into the German equivalent `Beatmap-Nominator(en)`.
- `rankable` --> `rankbar` (is there something better 🤔 )

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-17 13:48 UTC, respektive requested changes

2023-01-17 13:48 UTC, respektive commented on wiki/Guides/Getting_Your_Map_Modded/de.md
> +- **Anfrage eines Beatmap-Nominators (BN req):** Wird nur in Warteschlangen von Beatmap-Nominatoren oder in `#modreqs` verwendet. Eine BN-Anfrage wird genutzt, wenn du glaubst, dass deine Beatmap nic
```suggestion
- **Anfrage eines Beatmap-Nominators (BN req):** Wird nur in Warteschlangen von Beatmap-Nominatoren oder in `#modreqs` verwendet. Eine BN-Anfrage wird genutzt, wenn du glaubst, dass deine Beatmap durch reguläre Mods nicht weiter verbessert werden kann und eine gründlichere Prüfung durch einen [Beatmap-Nominator](/wiki/People/The_Team/Beatmap_Nominators) erfordert.
```

2023-01-17 13:48 UTC, respektive commented on wiki/Guides/Getting_Your_Map_Modded/de.md
> +Es sollte angemerkt werden, dass du es vermeiden solltest, in den Warteschlangen von Beatmap-Nominatoren Beiträge zu verfassen, bis dein Mapping ein nahezu rankbares Level erreicht hat (es sei denn,
I think `rankbar` is fine, can't think of anything better.

2023-01-17 13:48 UTC, respektive commented on wiki/Guides/Getting_Your_Map_Modded/de.md
> +`#modreqs` hat nicht dieselbe Funktionalität und Nutzerbasis, die es in der Vergangenheit hatte, aber es ist immer noch eine nützliche Methode, Mods zu erhalten, es ist also einen Versuch wert. Obwoh
```suggestion
`#modreqs` hat nicht dieselbe Funktionalität und Nutzerbasis, die es in der Vergangenheit hatte, aber es ist immer noch eine nützliche Methode, Mods zu erhalten, es ist also einen Versuch wert. Obwohl es heutzutage hauptsächlich normale Mod-Anfragen gibt, wird der Kanal auch häufig für die anderen [oben genannten Anfragearten](#mod-arten) verwendet.
```

2023-01-17 14:35 UTC, respektive approved these changes

2023-01-18 20:00 UTC, TicClick approved these changes

2023-01-18 20:02 UTC, merged