[IT] Add `BBCode`
ppy/osu-wiki pull request #8668
Opened 2023-01-21 21:51 UTC by Sclafus

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-21 22:15 UTC, GYGY88 requested changes

2023-01-21 22:15 UTC, GYGY88 commented on wiki/BBCode/it.md
> +### Instazione (v2)
Intestazione typo

2023-01-21 22:28 UTC, GYGY88 approved these changes

2023-01-28 01:57 UTC, marcostudios commented on wiki/BBCode/it.md
> +
Reminder to remove double lines 

```suggestion
```

2023-02-02 13:59 UTC, TicClick approved these changes

2023-02-02 14:38 UTC, merged