[ZH] Add `Gameplay/Play_style` (including subpages) and `Gameplay/Grade`
ppy/osu-wiki pull request #8675
Opened 2023-01-22 15:28 UTC by Andy-K-Sparklight

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
---
Translated all pages under `Gameplay/Play_style`. Including the index page itself.
此合并请求包含 `Gameplay/Play_style` 本页以及其下所有子页面的中文翻译。

There are some terms that I failed to find corresponding official translation. I've chosen the best ones I can think of. If there are any better ones, feel free to point out.
有些术语没有找到官方译名，故选择了个人认为最合适的译法，如有疏漏或改进建议请不吝指出！

These terms are: **Tapx**（暂译**纯板+**）, **Alternating**（暂译**切键**）, **Double tapping**（暂译**双键**）, **Single tapping**（暂译**单键**）, **Hover**（暂译**悬笔定位**）, **Drag**（暂译**拖笔定位**）, **Tapping style**（暂译**指法**）.

Names of some games (like Para Para Paradise) have no suitable translation in the context. They are kept as-is.
有些游戏的名字找不到任何适合语境的翻译，亦无资料可考，故保留了原文。

2023-01-23 11:34 UTC, Sunnyboy971 requested changes
总体上还是很不错的，翻译得很传神。
一些地方的语言表达与标点使用还可以改善。

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Grade/zh.md
> +玩家能获得的所有评价是 **D, C, B, A, S** 和 **SS**，从最差到最好排序。**银 S** 和 **银 SS** 需要打开 [Hidden](/wiki/Game_modifier/Hidden), [Flashlight](/wiki/Game_modifier/Flashlight) 或 [Fade In](/wiki/Game_modifier/Fade_In) 模组才
```suggestion
玩家能获得的所有评价是 **D**、 **C**、 **B**、 **A**、 **S** 和 **SS**，从最差到最好排序。**银 S** 和 **银 SS** 需要打开 [Hidden](/wiki/Game_modifier/Hidden)、 [Flashlight](/wiki/Game_modifier/Flashlight) 或 [Fade In](/wiki/Game_modifier/Fade_In) 模组才能获得。
```
这里建议把所有评级分开加粗，使用中文标点。

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/Hybrid/zh.md
> +**混合指法（Hybrid）** 是 [osu!](/wiki/Game_mode/osu!) 模式中的一种指法。在这种指法中，玩家混合使用 [单键指法（Single-tapping）](/wiki/Play_style/Single-tapping) 和 [切键指法（Alternating）](/wiki/Play_style/Alternating) 来点击圆圈，拖动滑条和旋转转盘。这种指法
```suggestion
**混合指法（Hybrid）** 是 [osu!](/wiki/Game_mode/osu!) 模式中的一种指法。在这种指法中，玩家混合使用 [单键指法（Single-tapping）](/wiki/Play_style/Single-tapping) 和 [切键指法（Alternating）](/wiki/Play_style/Alternating) 来点击圆圈、拖动滑条和旋转转盘。这种指法在各种水准的玩家中都有应用。此外，使用这种指法所需要的技巧和经验也因谱面风格而异。
```

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/Single-tapping/zh.md
> +  - 游戏风格
```suggestion
  - 游戏风格
  - 玩法
```
统一标签，以便搜索阅读。

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/Single-tapping/zh.md
> +**单键指法（Single-tapping）** 是 [osu!](/wiki/Game_mode/osu!) 模式中的一种指法。在这种指法中，玩家只用一个键（默认是 `Z` 或者 `X`）点击圆圈，拖动滑条和旋转转盘。这种指法在各种水准的玩家中都很常用，而且也是最容易学习和适应的。
```suggestion
**单键指法（Single-tapping）** 是 [osu!](/wiki/Game_mode/osu!) 模式中的一种指法。在这种指法中，玩家只用一个键（默认是 `Z` 或者 `X`）点击圆圈、拖动滑条和旋转转盘。这种指法在各种水准的玩家中都很常用，而且也是最容易学习和适应的。
```

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +这种玩法一般被认为是最难的一种方法。也正因此，成绩排行榜上名列前茅的纯鼠玩家会备受社区的尊敬。
```suggestion
这种玩法一般被认为是最难的。也正因此，成绩排行榜上名列前茅的纯鼠玩家会备受社区的尊敬。
```

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +也称作*单鼠*。纯鼠玩家通过（一个）鼠标来移动游戏光标，并且只用鼠标的左右键点击圆圈，拖动滑条和转动转盘。
```suggestion
也称作*单鼠*。纯鼠玩家通过一个鼠标来移动游戏光标，并且只用鼠标的左右键点击圆圈、拖动滑条和转动转盘。
```
这里可以去掉括号，与下文的“双鼠”有所区分。

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +这种方法曾经被很多玩家认为仅仅能用来博人一笑，但在 2013 年 5 月，一位加拿大 ::{ flag=CA }:: 玩家 [Azer](https://osu.ppy.sh/users/2155578) 通过双鼠在很多高质量的谱面（比如 [Hatsune Miku - With a Dance Number (val0108)](https://osu.ppy.sh/beatmapsets/2
```suggestion
这种方法曾经被很多玩家认为仅仅能用来博人一笑，但在 2013 年 5 月，一位加拿大玩家 ::{ flag=CA }:: [Azer](https://osu.ppy.sh/users/2155578) 通过双鼠在很多高质量的谱面（比如 [Hatsune Miku - With a Dance Number (val0108)](https://osu.ppy.sh/beatmapsets/29691) 和 [The Quick Brown Fox - The Big Black (Blue Dragon)](https://osu.ppy.sh/beatmapsets/41823)）中取得了很高的分数，证明了这种方法打图的可行性。
```
将国旗放在玩家昵称前，以契合原文在网站上的外观。

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +当手指或笔按下的那一刻，系统会立刻将光标移到触摸点，同时向游戏发送一个点击信号。这样，玩家只需要触摸物件**本身**就可以点击圆圈，拖动滑条和转动转盘。
```suggestion
当手指或笔按下的那一刻，系统会立刻将光标移到触摸点，同时向游戏发送一个点击信号。这样，玩家只需要触摸物件**本身**就可以点击圆圈、拖动滑条和转动转盘。
```

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +- **游戏控制器**：在太鼓达人中，游戏控制器也是一种可供选择的玩法。玩家使用控制器上不同的按钮打击正确颜色的圆圈。
```suggestion
- **游戏控制器**：在太鼓达人的大量游戏主机变种（包括 Taiko Drum Master ）中，游戏控制器也是一种可供选择的玩法。玩家使用控制器上不同的按钮打击正确颜色的圆圈。
```

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +玩家使用左右箭头按键控制小人的移动，按住左 `Shift` 可以加快移动速度。
```suggestion
玩家使用左右箭头按键控制小人的移动，按住`左 Shift` 可以加快移动速度。
```
建议将左/右直接引用，分别代表两个 Shift 键。

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +方便起见，修改键位也是可以的，比如有的玩家就喜欢用 `A` 和 `D` 控制，并用右 `Shift` 加速。
```suggestion
方便起见，修改键位也是可以的，比如有的玩家就喜欢用 `A` 和 `D` 控制，并用`右 Shift` 加速。
```

2023-01-23 11:34 UTC, Sunnyboy971 commented on wiki/Gameplay/Play_style/zh.md
> +### 游戏控制器
```suggestion
### 街机控制器
```

2023-01-23 13:42 UTC, Sunnyboy971 approved these changes

2023-01-23 20:19 UTC, Walavouchey commented
in the future, please apply reviews in batches from the "files changed" tab, as explained [here](https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#applying-reviews). this reduces commit spam.

2023-01-23 20:23 UTC, Walavouchey approved these changes

2023-01-23 20:24 UTC, merged

2023-01-27 08:06 UTC, YumeMuzi commented
完球，这里面的术语和社区流行的说法基本对不上

考虑 new PR 了