refactor on Tournaments/zh.md, update some data
ppy/osu-wiki pull request #8685
Opened 2023-01-23 20:29 UTC by untitledunrevised

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-23 21:22 UTC, Walavouchey commented
hi please refrain from updating the branch yourself as it will be done right before merging anyway. it only creates unnecessary merge commits in between actual changes.

![image](https://user-images.githubusercontent.com/36758269/214152612-5f780444-16a5-4fac-b81f-b8914841ebb3.png)

2023-01-27 04:53 UTC, YumeMuzi requested changes

2023-01-27 04:53 UTC, YumeMuzi commented on wiki/Tournaments/zh.md
> +请访问[官方锦标赛支持页面](https://osu.ppy.sh/wiki/en/Tournaments/Official_support)，详细了解如何为您的锦标赛申请官方支持（徽章、筛选流程等）。
```suggestion
请访问[官方锦标赛支持页面](/wiki/Tournaments/Official_support)，详细了解如何为您的锦标赛申请官方支持（徽章、筛选流程等）。
```

2023-01-27 04:53 UTC, YumeMuzi commented on wiki/Tournaments/zh.md
> +| [GB Cup 2022 Autumn](GBC/GBC_2022_Autumn) | 2022-10-15 | 2022-12-18 | 无所谓绿皮龙会出手的 | BMS精灵 | 	俄亥俄州立大学躁狂播放器 |
```suggestion
| [GB Cup 2022 Autumn](GBC/GBC_2022_Autumn) | 2022-10-15 | 2022-12-18 | 无所谓绿皮龙会出手的 | BMS精灵 | 俄亥俄州立大学躁狂播放器 |
```

2023-01-27 04:53 UTC, YumeMuzi commented on wiki/Tournaments/zh.md
> +| [osu! 世界杯 2021](OWC/2022) | 2022-10-15 | 2022-11-27 | ::{ flag=US }:: 美国 | ::{ flag=KR }:: 韩国 | ::{ flag=DE }:: 德国 |
```suggestion
| [osu! 世界杯 2022](OWC/2022) | 2022-10-15 | 2022-11-27 | ::{ flag=US }:: 美国 | ::{ flag=KR }:: 韩国 | ::{ flag=DE }:: 德国 |
```

2023-01-29 17:13 UTC, RushFTK commented on wiki/Tournaments/zh.md
> +| [GB Cup 2022 Autumn](GBC/GBC_2022_Autumn) | 2022-10-15 | 2022-12-18 | 无所谓绿皮龙会出手的 | BMS精灵 | 	俄亥俄州立大学躁狂播放器 |
这比赛冠军怎么是这三个队。。。

2023-02-07 13:57 UTC, YumeMuzi commented on wiki/Tournaments/zh.md
> +
```suggestion

#### Yuyuko's Hidden Cup

| 名称 | 开始时间 | 结束时间 | ![冠军][GCrown] | ![亚军][SCrown] | ![季军][BCrown] |
| :-- | :-- | :-- | :-- | :-- | :-- |
| Yuyuko's Hidden Cup Season 1 | 2022-05-17 | 2022-07-04 | 都怪幽神 | HD怎么打 | 队名叫有新意的名字 / 请在此处填写队名 |
| [Yuyuko's Hidden Cup Season 2](YHC/2) | 2022-11-26 | 2023-02-05 | 懒人三项 | 老年娱乐 | 已经结束啦 |

```

2023-02-07 14:04 UTC, YumeMuzi requested changes

2023-02-07 14:04 UTC, YumeMuzi commented on wiki/Tournaments/en.md
> +| [GB Cup 2022 Autumn](GBC/GBC_2022_Autumn) | 2022-10-15 | 2022-12-18 | 猫猫面馆 | 黎曼猜想 | 均衡教派 |
plz keep de/fr.md in sync or just add an `outdated_wiki` mark following https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#front-matter

2023-02-10 05:05 UTC, YumeMuzi approved these changes

2023-02-12 01:18 UTC, TicClick approved these changes

2023-02-12 01:19 UTC, merged