Updated ''Main Page''
ppy/osu-wiki pull request #8696
Opened 2023-01-25 18:06 UTC by marcostudios

Saw that the main page of the wiki wasn't updated

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-26 18:20 UTC, Sclafus submitted a review, later dismissed

2023-01-28 15:42 UTC, TicClick requested changes

2023-01-28 15:42 UTC, TicClick commented on wiki/Main_Page/it.md
> -layout: main_page
don't remove `layout: main_page` -- this will likely break it.

2023-01-28 15:42 UTC, TicClick commented on wiki/Main_Page/it.md
> +[Collaboratri della Comunità](/wiki/People/Community_Contributors) • [Utenti con titoli unici](/wiki/People/Users_with_unique_titles) • [Comitato Tornei](/wiki/People/Tournament_Committee) • [Comitat
this line is missing the osu! wiki maintainers reference -- please make sure no changes from https://osu.wiki/status/diff-it-wiki-Main_Page are left behind, and that the updated translation has everything the original main page does: https://github.com/ppy/osu-wiki/blob/master/wiki/Main_Page/en.md

2023-01-28 18:01 UTC, Sclafus requested changes

2023-01-28 18:01 UTC, Sclafus commented on wiki/Main_Page/it.md
> +[Collaboratori della Comunità](/wiki/People/Community_Contributors) • [Utenti con titoli unici](/wiki/People/Users_with_unique_titles) • [Comitato Tornei](/wiki/People/Tournament_Committee) • [Comita
```suggestion
[Collaboratori della Comunità](/wiki/People/Community_Contributors) • [Utenti con titoli unici](/wiki/People/Users_with_unique_titles) • [Comitato Tornei](/wiki/People/Tournament_Committee) • [Comitato Punti Performance](/wiki/People/Performance_Points_Committee) • [Manutentori della osu! wiki](/wiki/People/osu!_wiki_maintainers)
```

2023-01-28 19:04 UTC, TicClick approved these changes

2023-01-28 19:06 UTC, merged