[ZH] Update `BN`, `NAT`, and `becoming_a_BN`
ppy/osu-wiki pull request #8700
Opened 2023-01-27 07:25 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-27 08:00 UTC, Sunnyboy971 requested changes

2023-01-27 08:00 UTC, Sunnyboy971 commented on wiki/People/The_Team/Beatmap_Nominators/zh.md
> +如果 BN 因为犯下错误被降级成见习成员，在大约一年内，他们再次犯下了类似的错误，则会被开除。比如，某位 BN 因为不良行为而被降级成见习成员，无论他们是否度过见习期而成功返回正式成员小组，只要在一年内再犯，就会被直接开除。
```suggestion
在 BN 因为犯下错误被降级成见习成员后，如果他们在大约一年内再次犯下了类似的错误，则会被开除。比如，某位 BN 因为不良行为而被降级成见习成员，无论他们是否度过见习期而成功返回正式成员小组，只要在一年内再犯，就会被直接开除。
```
个人觉得这句话的语序调一下会更好。

2023-01-27 10:57 UTC, Sunnyboy971 approved these changes

2023-01-28 19:14 UTC, TicClick approved these changes

2023-01-28 19:16 UTC, merged