[IT] Translated `Do you really want to ask peppy`
ppy/osu-wiki pull request #8706
Opened 2023-01-27 18:43 UTC by marcostudios

There are some things like ban follow-up that I tried to translate the best way I could

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-28 14:48 UTC, Sclafus requested changes

2023-01-28 14:48 UTC, Sclafus commented on wiki/Do_you_really_want_to_ask_peppy/it.md
> +Ciao! peppy comprende il tuo bisogno di contattarlo personalmente, ma lui chiede che innanzitutto tu capisca che questo **non è** il posto dove vuoi chiedergli aiuto o assistenza. Lui tiene il suppor
```suggestion
Ciao! peppy comprende il tuo bisogno di contattarlo personalmente, ma lui chiede che innanzitutto tu capisca che questo **non è** il posto adatto per chiedere aiuto o assistenza. Lui gestisce i messaggi di supporto di osu! separati rispetto a i messaggi personali e inoltre ritiene che sia abbastanza difficile stare dietro ai PM sul forum. Quindi ti chiede che tu segua una delle seguenti opzioni:
```

2023-01-28 14:48 UTC, Sclafus commented on wiki/Do_you_really_want_to_ask_peppy/it.md
> +La maggiorparte dei problemi tecnici possono essere risolti cercando o postando nel [forum Help](https://osu.ppy.sh/community/forums/5). Ci sono molti altri che possono aiutarti con i tuoi problemi,
```suggestion
La maggiorparte dei problemi tecnici possono essere risolti cercando o postando nel [forum Help](https://osu.ppy.sh/community/forums/5). Ci sono molti altri che possono aiutarti con i tuoi problemi, affinché tu possa trovare una soluzione più velocemente rispetto a contattarlo direttamente.
```

2023-02-08 09:20 UTC, Sclafus approved these changes

2023-02-08 13:42 UTC, TicClick approved these changes

2023-02-08 14:32 UTC, merged