Add `Indonesia Convert Cup Open 2022` wiki article
ppy/osu-wiki pull request #8714
Opened 2023-01-29 07:47 UTC by Nivalyx

requested by [Constantine](http://osu.ppy.sh/users/3221898) and [Urabe Mikoto](http://osu.ppy.sh/users/1272422) via pm

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-01-29 16:31 UTC, TicClick requested changes

2023-01-29 16:31 UTC, TicClick commented on wiki/Tournaments/de.md
> +| [Indonesia Convert Cup Open 2022](ICC/2022) | 2022-10-10 | 2022-11-27 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) |
date format is different

2023-01-29 16:31 UTC, TicClick commented on wiki/Tournaments/fr.md
> +| [Indonesia Convert Cup Open 2022](ICC/2022) | 2022-10-10 | 2022-11-27 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) |
date format is different

2023-01-29 16:31 UTC, TicClick commented
(other than that I see no issues with the ruleset and the article in general)

2023-01-29 18:58 UTC, Walavouchey requested changes
just going to quickly skim this one (seems very good writing-wise)

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/ICC/2022/en.md
> +The **Indonesia Convert Cup 2022** (***ICC 2022***) was a double-elimination 1v1 osu!catch tournament hosted by ::{ flag=ID }:: [Urabe Mikoto](https://osu.ppy.sh/users/1272422) in which all the beatm
```suggestion
The **Indonesia Convert Cup Open 2022** (***ICCO 2022***) was a double-elimination 1v1 osu!catch tournament hosted by ::{ flag=ID }:: [Urabe Mikoto](https://osu.ppy.sh/users/1272422) in which all the beatmaps were osu! converts. Despite its name, the tournament was open to all players from all ten [ASEAN member states](https://asean.org/about-asean/member-states/) as well as ::{ flag=TL }:: Timor-Leste, ::{ flag=NZ }:: New Zealand, and ::{ flag=AU }:: Australia with 3,000 play count or more in the osu!catch game mode to their name. It was regarded as the third instalment of the Indonesia Convert Cup tournament series.
```

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/ICC/2022/en.md
> +| Seed No. | Player | Avg. Map Rank |
```suggestion
| Seed no. | Player | Avg. map rank |
```

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/ICC/2022/en.md
> +![](img/podium.jpg "ICCO 2022 podium")
```suggestion
![ICCO 2022 podium](img/podium.jpg "ICCO 2022 podium")
```

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/ICC/2022/en.md
> +2. In the lobby, all players will have to consecutively play all of the nine Qualifier beatmaps in the order of NM1 -> NM2 -> HD1 -> HD2 -> HR1 -> HR2 -> DT1 -> DT2.
i count 8 in that list

```suggestion
2. In the lobby, all players will have to consecutively play all of the eight Qualifier beatmaps in the order of NM1 -> NM2 -> HD1 -> HD2 -> HR1 -> HR2 -> DT1 -> DT2.
```

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/ICC/2022/en.md
> +4. Players **are not allowed** to join in (or register for) more than one Qualifier lobby.
```suggestion
4. Players **are not allowed** to join (or register for) more than one Qualifier lobby.
```

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/ICC/2022/en.md
> +4. **There will be no dedicated FreeMod picks in the tournament.** However, when playing a map from the HardRock or Double Time pool, Hidden can be used optionally on top of the corresponding mod by
```suggestion
4. **There will be no dedicated FreeMod picks in the tournament.** However, when playing a map from the HardRock or DoubleTime pool, Hidden can be used optionally on top of the corresponding mod by any player.
```

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/de.md
> +| [Indonesia Convert Cup Open 2022](ICC/2022) | 2022-10-10 | 2022-11-27 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) |
```suggestion
| [Indonesia Convert Cup Open 2022](ICC/2022) | 10.10.2022 | 27.11.2022 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) | ::{ flag=ID }:: [Chroneko](https://osu.ppy.sh/users/5472877) |
```

2023-01-29 18:58 UTC, Walavouchey commented on wiki/Tournaments/fr.md
> +| [Indonesia Convert Cup Open 2022](ICC/2022) | 2022-10-10 | 2022-11-27 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) |
```suggestion
| [Indonesia Convert Cup Open 2022](ICC/2022) | 10/10/2022 | 27/11/2022 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) | ::{ flag=ID }:: [Chroneko](https://osu.ppy.sh/users/5472877) |
```

2023-01-30 01:28 UTC, TicClick approved these changes

2023-01-30 01:29 UTC, Walavouchey requested changes

2023-01-30 01:29 UTC, Walavouchey commented on wiki/Tournaments/fr.md
> +| [Indonesia Convert Cup Open 2022](ICC/2022) | 10/10/2022 | 17/11/2022 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) |
```suggestion
| [Indonesia Convert Cup Open 2022](ICC/2022) | 10/10/2022 | 27/11/2022 | ::{ flag=ID }:: [Netamaru](https://osu.ppy.sh/users/1830361) | ::{ flag=CA }:: [Henrick](https://osu.ppy.sh/users/8840982) | ::{ flag=ID }:: [Chroneko](https://osu.ppy.sh/users/5472877) |
```

2023-01-30 01:30 UTC, Walavouchey approved these changes

2023-01-30 01:32 UTC, merged