[IT] Add `Medals`
ppy/osu-wiki pull request #8720
Opened 2023-01-29 13:35 UTC by arancinosbarazzino

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-01-29 14:22 UTC, Sclafus requested changes

2023-01-29 14:22 UTC, Sclafus commented on wiki/Medals/it.md
> +- I loro *testi a comparsa*<!-- https://twitter.com/ephemeralis/status/1068054191602638850 --> delle medaglie (se ci sono), visibile passando sopra l'emblema con il cursore.
```suggestion
- I loro *testi a comparsa*<!-- https://twitter.com/ephemeralis/status/1068054191602638850 --> (se ci sono), visibili passando sopra l'emblema con il cursore.
```

2023-01-29 14:22 UTC, Sclafus commented on wiki/Medals/it.md
> +Siccome le medaglie Hush-Hush sono fatte per essere obiettivi segreti, i requisiti per sbloccarle non sono vengono direttamente detti al pubblico; ad ogni modo, i giocatori possono [collaborare per c
```suggestion
Siccome le medaglie Hush-Hush sono fatte per essere obiettivi segreti, i requisiti per sbloccarle non sono vengono direttamente rivelati al pubblico; ad ogni modo, i giocatori possono [collaborare per capire insieme un modo per ottenere tutte le medaglie Hush-Hush qui](https://osu.ppy.sh/home/news/2016-08-17-new-hush-hush-medals).
```

2023-01-29 14:22 UTC, Sclafus commented on wiki/Medals/it.md
> +le **medaglie Spotlights Stagionali** sono medaglie ottenute completando determinati pacchetti beatmap rilasciati come parte degli [Spotlights Stagionali](https://osu.ppy.sh/home/news/2018-11-01-beat
```suggestion
Le **medaglie Spotlights Stagionali** sono medaglie ottenute completando determinati pacchetti beatmap rilasciati come parte degli [Spotlights Stagionali](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-summer-2018). Per sbloccare le medaglie in questa categoria, un giocatore deve giocare tutte le mappe *in qualunque pacchetto delle 4 modalità di gioco* che fanno parte del corrispondente schema di classificazione degli Spotlights Stagionali. È possibile utilizzare le seguenti mods:
```

2023-01-29 14:22 UTC, Sclafus commented on wiki/Medals/it.md
> +le **medaglie dei Pacchetti Sfida Beatmap**, o alternativamente conosciute come [*medaglie Pacchetti Abilità*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers
```suggestion
Le **medaglie dei Pacchetti Sfida Beatmap**, o altrimenti conosciute come [*medaglie Pacchetti Abilità*](https://osu.ppy.sh/home/news/2020-11-20-featured-artist-beatmap-updates-from-the-mappers-guild#skill-packs), sono medaglie ottenute al completamento della difficoltà più alta presente in tutte le beatmap presenti in alcuni [Pacchetti Beatmap a Tema](https://osu.ppy.sh/beatmaps/packs?type=theme) o [Pacchetti Beatmap Artista/Album](https://osu.ppy.sh/beatmaps/packs?type=artist) *senza alcuna mod che [riduca la difficoltà](/wiki/Game_modifier#difficulty-reduction) o [speciali](/wiki/Game_modifier#special) abilitate*. Questi pacchetti beatmap sono curati appositamente per mettere alla prova le abilità di ogni giocatore in vari aspetti del gioco riguardanti diversi livelli di abilità, ad esempio all'interno di una particolare gamma di [difficoltà](/wiki/Beatmapping/Star_rating) o con una difficoltà massima.
```

2023-01-29 14:22 UTC, Sclafus commented on wiki/Medals/it.md
> +tutte le beatmap nel pacchetto devono essere completate nella modalità di gioco [osu!](/wiki/Game_mode/osu!) per poter ottenere la medaglia, a meno che diversamente specificato.
```suggestion
Tutte le beatmap nel pacchetto devono essere completate nella modalità di gioco [osu!](/wiki/Game_mode/osu!) per poter ottenere la medaglia, a meno che diversamente specificato.
```

2023-01-29 14:26 UTC, Sclafus approved these changes

2023-02-02 09:15 UTC, TicClick commented
please include changes from https://github.com/ppy/osu-wiki/pull/8735 as well (it's a small one)

2023-02-04 09:57 UTC, Sclafus approved these changes
The newly added part is also good

2023-02-05 00:04 UTC, TicClick approved these changes

2023-02-05 00:05 UTC, merged