Add Toromaru - Uncharted Sky (MWC 7K Semifinals Rice 6) to `osu! originals`
ppy/osu-wiki pull request #8727
Opened 2023-01-29 18:10 UTC by Walavouchey

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) @juankristal @Pisapou quick look maybe (mostly copy-paste)

idk if there are abbreviations for mappool slots of other modes like there are for osu! (NM1 etc.)

2023-01-30 12:48 UTC, juankristal commented
In mania we use RC (for Rice), HB (for Hybrids), LN (for Long Notes) as abbreviations. Not sure if the terminology was officially supported but nowadays the MWC pages uses Rice/Hybrid/Long Note categories so its probably fine to use the abbreviations too

2023-01-30 12:49 UTC, juankristal requested changes

2023-01-30 12:49 UTC, juankristal commented on wiki/osu!_originals/es.md
> +| Toromaru - Uncharted Sky[^fa] | [#1](https://osu.ppy.sh/beatmapsets/1931471) | Rice 6 de semifinales |
Would use "Semifinales RC6" to use both the abbreviation suggested in the main comment and having it consistent with previous translations from OWC.

2023-01-30 16:41 UTC, Pisapou approved these changes
French is ok. Just change to "RC6 des demi-finales" if juankristal's changeis applied

2023-01-31 01:47 UTC, TicClick approved these changes

2023-01-31 01:49 UTC, merged