[ES] Add `Changelog`
ppy/osu-wiki pull request #8740
Opened 2023-01-31 21:50 UTC by LuiselprraYT

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-02-01 14:24 UTC, agatemosu requested changes

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +
```suggestion
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +El **[registro de cambios](https://osu.ppy.sh/home/changelog)** es una página donde él [equipo de desarrollo de osu!](/wiki/People/The_Team/Developers) detallan sus mejoras, adiciones, y correcciones
```suggestion
El **[registro de cambios](https://osu.ppy.sh/home/changelog)** es una página donde el [equipo de desarrollo de osu!](/wiki/People/The_Team/Developers) detallan sus mejoras, adiciones y correcciones de errores día a día al juego. Todos los cambios de versiones anteriores se registran aquí con fines de archivo.
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +Los registros de cambios para el sitio web y osu!(lazer)son generados automáticamente basado en versiones de GitHub de esos proyectos, mientras que el resto se mantienen manualmente.
```suggestion
Los registros de cambios para el sitio web y osu!(lazer) se generan automáticamente en función de las versiones de GitHub de esos proyectos, mientras que el resto se mantiene manualmente.
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +
```suggestion
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +El registro de cambios fue creado por peppy el 11 de septiembre de 2007 en un hilo del foro llamado "[Official Development Changelog](https://osu.ppy.sh/community/forums/topics/15)", donde él listaba
```suggestion
El registro de cambios fue creado por peppy el 11 de septiembre de 2007 en un hilo del foro dedicado titulado «[Official Development Changelog](https://osu.ppy.sh/community/forums/topics/15)», donde enumeraba cambios notables y correcciones de errores y, a veces, compartía información sobre próximos planes.
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +![](img/changelog-osume-2013.png "Registro de cambios en el osu! updater (2013)")
```suggestion
![](img/changelog-osume-2013.png "Registro de cambios en el actualizador de osu! (2013)")
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +En octubre, 2007, una versión web del registro de cambio [se hizo disponible](https://osu.ppy.sh/community/forums/posts/2499) tanto a través del sitio web y el osu! updater.
```suggestion
En octubre de 2007, una versión web del registro de cambios [estuvo disponible](https://osu.ppy.sh/community/forums/posts/2499) tanto a través del sitio web como del actualizador de osu!.
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +En octubre 25, 2009, el registro de cambios [se hizo disponible vía fuente RSS](https://osu.ppy.sh/community/forums/topics/19137).
```suggestion
El 25 de octubre de 2009, el registro de cambios [estuvo disponible a través de una fuente RSS](https://osu.ppy.sh/community/forums/topics/19137).
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +## Ver también
```suggestion
## Véase también
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +En octubre 28, 2015, una gráfica con la distribución de versiones de osu! a través de la base de jugadores [se añadió al registro de cambios](https://web.archive.org/web/20151103161516/http://osu.ppy
```suggestion
El 28 de octubre de 2015, [se agregó al registro de cambios](https://web.archive.org/web/20151103161516/http://osu.ppy.sh:80/p/changelog) un gráfico con la distribución de versiones de osu! en la base de jugadores, lo que hizo que las estadísticas estuvieran abiertas al público en general. Al mismo tiempo, se hizo posible filtrar el registro de cambios por canales de actualizaciones.
```

2023-02-01 14:24 UTC, agatemosu commented on wiki/Changelog/es.md
> +Además de los cambios listados en el sitio web, [el blog de peppy](https://blog.ppy.sh/) puede considerarse una forma de registro de cambio. A lo largo de los años, ha acumulado una amplia colección
```suggestion
Además de los cambios enumerados en el sitio web, el [blog de peppy](https://blog.ppy.sh/) también puede considerarse una forma de registro de cambios. A lo largo de los años, ha acumulado una gran colección de publicaciones centradas en osu!, su desarrollo y su ecosistema, incluidos los próximos planes y notas de reuniones de desarrolladores.
```

2023-02-04 23:21 UTC, agatemosu approved these changes

2023-02-12 01:20 UTC, TicClick approved these changes

2023-02-12 01:21 UTC, merged