[IT] Updated `Community Contributors`
ppy/osu-wiki pull request #8741
Opened 2023-01-31 21:54 UTC by marcostudios

There are some wording that needs to be discussed with other italian translators, but for the most part it should be fine.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-02-03 13:08 UTC, Sclafus requested changes
Incomplete review, will do the rest this evening

2023-02-03 13:08 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +Non devono essere confusi con gli [osu! Alumni](/wiki/People/The_Team/osu!_Alumni) che erano membri del team di osu! che si sono ritirati, Il badge per i Collaboratori della Comunità sono dati a libe
Is `liberi professionisti` actually the word that we are looking for?

2023-02-03 13:08 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=US }:: [akrolsmir](https://osu.ppy.sh/users/576800) | Sviluppa e mantiene [AIBat](https://osu.ppy.sh/community/forums/topics/55305), il più popolare strumento di modding delle beatmap di t
```suggestion
| ::{ flag=US }:: [akrolsmir](https://osu.ppy.sh/users/576800) | Sviluppa e mantiene [AIBat](https://osu.ppy.sh/community/forums/topics/55305), il più popolare strumento di modding delle beatmap di terze parti. |
```

2023-02-03 13:08 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=DE }:: [Loctav](https://osu.ppy.sh/users/71366) | Ha organizzato molti tornei ufficiali di maggiore importanza (incluso l'OWC). |
```suggestion
| ::{ flag=DE }:: [Loctav](https://osu.ppy.sh/users/71366) | Ha organizzato molti tornei ufficiali di grande rilevanza (incluso l'OWC). |
```

2023-02-03 13:08 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=NL }:: [statementreply](https://osu.ppy.sh/users/126198) | Performance straordinaria nei bugfix o test delle funzionalità e ha programmato numerose utilities per i mapper e modders. |
```suggestion
| ::{ flag=NL }:: [statementreply](https://osu.ppy.sh/users/126198) | Ha contribuito a risolvere numerosissimi bug e a provare delle funzionalità. Inoltre, ha creato numerosi strumenti per mapper e modders. |
```

2023-02-04 09:56 UTC, Sclafus requested changes

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=PL }:: [Piotrekol](https://osu.ppy.sh/users/304520) | Sviluppa e mantiene [osu!stats](http://osustats.ppy.sh/) e un numero imprecisato di utilities utili per fare beatmaps, moddare e gioca
```suggestion
| ::{ flag=PL }:: [Piotrekol](https://osu.ppy.sh/users/304520) | Sviluppa e mantiene [osu!stats](http://osustats.ppy.sh/) e un numero imprecisato di strumenti per creare, moddare e giocare beatmaps in generale. |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=US }:: [DeathxShinigami](https://osu.ppy.sh/users/49516) | Più di 3 anni di lavoro silenzioso e instancabile nel creare [pacchetti beatmaps](https://osu.ppy.sh/p/packlist) e diversi anni n
```suggestion
| ::{ flag=US }:: [DeathxShinigami](https://osu.ppy.sh/users/49516) | Più di 3 anni di duro lavoro silenzioso per creare [pacchetti beatmaps](https://osu.ppy.sh/p/packlist) e gestire i grafici |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=NO }:: [MillhioreF](https://osu.ppy.sh/users/941094) | Performance straordinaria nei bugfix o test delle funzionalità e nel gestire le richieste di supporto dagli utenti. |
```suggestion
| ::{ flag=NO }:: [MillhioreF](https://osu.ppy.sh/users/941094) | Ha contribuito a risolvere numerosissimi bug e a provare delle funzionalità. Inoltre, ha gestito numerose richieste di supporto da parte degli utenti. |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=US }:: [LuigiHann](https://osu.ppy.sh/users/1079) | Anni su anni di servizio, incluso il creare la skin per le beatmap originale, creare [storyboard](/wiki/Storyboard) avanzati come un'ope
```suggestion
| ::{ flag=US }:: [LuigiHann](https://osu.ppy.sh/users/1079) | Anni ed anni di servizio. In particolare, ha creato skin per le beatmap originali, creato [storyboard](/wiki/Storyboard) avanzati, comparabili  a vere opere d'arte e ha motivato il team. |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=DE }:: [MoonShade](https://osu.ppy.sh/users/273649) | Ha sviluppato utities rivoluzionarie per fare le storyboard (SGL) |
```suggestion
| ::{ flag=DE }:: [MoonShade](https://osu.ppy.sh/users/273649) | Ha sviluppato strumenti rivoluzionari per creare le storyboard (SGL) |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=DE }:: [Tillerino](https://osu.ppy.sh/users/2070907) | Sviluppo del bot che raccomanda beatmap |
```suggestion
| ::{ flag=DE }:: [Tillerino](https://osu.ppy.sh/users/2070907) | Sviluppo del bot che consiglia beatmap |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=US }:: [pishifat](https://osu.ppy.sh/users/3178418) | Performance esemplare nella costruzione e insegnamento sulle beatmaps |
```suggestion
| ::{ flag=US }:: [pishifat](https://osu.ppy.sh/users/3178418) | Performance esemplare per la creazione e l'insegnamento delle beatmaps |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=ES }:: [Trosk-](https://osu.ppy.sh/users/3469385) | Contributo eccezionale agli affari della community |
```suggestion
| ::{ flag=ES }:: [Trosk-](https://osu.ppy.sh/users/3469385) | Contributo eccezionale alla comunità |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=PL }:: [Marcin](https://osu.ppy.sh/users/722665) | Eccezionale contributi to negli affari della comunità, organizzazione e moderazione |
```suggestion
| ::{ flag=PL }:: [Marcin](https://osu.ppy.sh/users/722665) | Eccezionale contributi alla community, in particolare sull'organizzazione e moderazione |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=DE }:: [OnosakiHito](https://osu.ppy.sh/users/290128) | Lavoro eccezionale nel formare l'iniziale commuinity di osu!taiko, svariati anni di presenza come BAT/QAT |
```suggestion
| ::{ flag=DE }:: [OnosakiHito](https://osu.ppy.sh/users/290128) | Lavoro eccezionale nel formare l'iniziale comunità di osu!taiko, svariati anni di presenza come BAT/QAT |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=CA }:: [Nyquill](https://osu.ppy.sh/users/682935) | Eccezionale contributo alla community (osu!weekly) |
```suggestion
| ::{ flag=CA }:: [Nyquill](https://osu.ppy.sh/users/682935) | Eccezionale contributo alla comunità (osu!weekly) |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=US }:: [Derekku](https://osu.ppy.sh/users/91341) | Gestione e moderazione durante i primi anni della community |
```suggestion
| ::{ flag=US }:: [Derekku](https://osu.ppy.sh/users/91341) | Gestione e moderazione durante i primi anni della comunità |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=FR }:: [Shiro](https://osu.ppy.sh/users/113005) | Contributo eccezionale alla moderazione, organizzazione e la gestione |
```suggestion
| ::{ flag=FR }:: [Shiro](https://osu.ppy.sh/users/113005) | Contributo eccezionale nella moderazione, organizzazione e la gestione della comunità |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=ES }:: [Deif](https://osu.ppy.sh/users/318565) | Eccezionali contributi alla community di osu!catch, alla rielaborazione dei criteri di classificazione e ai  tornei |
```suggestion
| ::{ flag=ES }:: [Deif](https://osu.ppy.sh/users/318565) | Eccezionali contributi alla comunità di osu!catch, tra cui la rielaborazione dei criteri di classificazione e tornei |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=CN }:: [huoyaoyuan](https://osu.ppy.sh/users/2428732) | Eccezionali contributi al progetto osu!(lazer) project |
```suggestion
| ::{ flag=CN }:: [huoyaoyuan](https://osu.ppy.sh/users/2428732) | Eccezionali contributi al progetto osu!(lazer) |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=CA }:: [VINXIS](https://osu.ppy.sh/users/4323406) | Eccezionali contributi agli affari della comunità, eventi e tornei |
```suggestion
| ::{ flag=CA }:: [VINXIS](https://osu.ppy.sh/users/4323406) | Eccezionali contributi alla comunità, eventi e tornei |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=GB }:: [-Mo-](https://osu.ppy.sh/users/2202163) | Eccezionali contributi agli affati sulla gestione e leadership |
```suggestion
| ::{ flag=GB }:: [-Mo-](https://osu.ppy.sh/users/2202163) | Eccezionali contributi sulla gestione e leadership |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=DE }:: [Junihuhn](https://osu.ppy.sh/users/4182339) | Eccezionali contributi alla osu! World Cup & e tornei |
```suggestion
| ::{ flag=DE }:: [Junihuhn](https://osu.ppy.sh/users/4182339) | Eccezionali contributi alla osu! World Cup e tornei |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=RU }:: [Kobold84](https://osu.ppy.sh/users/3227533) | Eccezionali contributi to community moderation |
```suggestion
| ::{ flag=RU }:: [Kobold84](https://osu.ppy.sh/users/3227533) | Eccezionali contributi nella moderazione della comunità |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=US }:: [Joehu](https://osu.ppy.sh/users/8549835) | Eccezionali contributi ai progetti opensource di osu! |
```suggestion
| ::{ flag=US }:: [Joehu](https://osu.ppy.sh/users/8549835) | Eccezionali contributi ai progetti open source di osu! |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=PL }:: [spaceman_atlas](https://osu.ppy.sh/users/3035836) | Eccezionali contributi allo sviluppo di osu! development attraverso molti progetti |
```suggestion
| ::{ flag=PL }:: [spaceman_atlas](https://osu.ppy.sh/users/3035836) | Eccezionali contributi allo sviluppo di osu! attraverso molti progetti |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=AU }:: [MBmasher](https://osu.ppy.sh/users/4498616) | Eccezionali contributi to sviluppo dei punti performance di osu! e rivitalizzazione della mod Flashlight |
```suggestion
| ::{ flag=AU }:: [MBmasher](https://osu.ppy.sh/users/4498616) | Eccezionali contributi allo sviluppo dei punti performance di osu! e ha dato nuova vita alla mod Flashlight |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=NL }:: [OliBomby](https://osu.ppy.sh/users/6573093) | Eccezionali contributi alla scena mapping di osu! attraverso sviluppo di utility |
```suggestion
| ::{ flag=NL }:: [OliBomby](https://osu.ppy.sh/users/6573093) | Eccezionali contributi alla scena mapping di osu! attraverso sviluppo di strumenti |
```

2023-02-04 09:56 UTC, Sclafus commented on wiki/People/Community_Contributors/it.md
> +| ::{ flag=TR }:: [frukoyurdakul](https://osu.ppy.sh/users/7612550) | Eccezionali contributi alla scena mapping di osu!taiko attraverso sviluppo di utility |
```suggestion
| ::{ flag=TR }:: [frukoyurdakul](https://osu.ppy.sh/users/7612550) | Eccezionali contributi alla scena mapping di osu!taiko attraverso sviluppo di strumenti |
```

2023-02-08 09:21 UTC, Sclafus approved these changes

2023-02-08 13:42 UTC, TicClick approved these changes

2023-02-08 13:49 UTC, merged