[JA] Update `Rules`
ppy/osu-wiki pull request #8746
Opened 2023-02-01 17:01 UTC by Yukinyaaa

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

Requires at least one native Japanese reviewer, I think.

2023-02-01 17:16 UTC, Yukinyaaa commented
uh, the Japanese article did not exist😅

2023-02-03 05:16 UTC, peppy requested changes

2023-02-03 05:16 UTC, peppy commented on wiki/Rules/ja.md
> +1. **ビートマップに含まれるコンテンツを使用する権利があることを確認してください。** これには曲、ビデオ、効果音、画像、及び自分で作成したものではないその他のコンテンツが含まれす。無料で使用できる楽曲がわからない場合は、[注目アーティスト](https://osu.ppy.sh/beatmaps/artists)から利用可能なトラックを見つけてください。全てのコンテンツはosu!で使用でき
```suggestion
1. **ビートマップに含まれるコンテンツを使用する権利があることを確認してください。** これには曲、ビデオ、効果音、画像、及び自分で作成したものではないその他のコンテンツが含まれます。無料で使用できる楽曲がわからない場合は、[注目アーティスト](https://osu.ppy.sh/beatmaps/artists)から利用可能なトラックを見つけてください。全てのコンテンツはosu!で使用できるようにライセンスされています。
```

Wrong in original text, but worth fixing.

2023-02-04 05:19 UTC, peppy approved these changes

2023-02-04 05:19 UTC, merged