[FR] Update `Users with unique titles`
ppy/osu-wiki pull request #8768
Opened 2023-02-06 09:57 UTC by Ganondorf-1

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-02-07 15:50 UTC, Pisapou submitted a review, later dismissed

2023-02-11 10:01 UTC, Walavouchey submitted a review, later dismissed

2023-02-11 10:06 UTC, osuShiro requested changes

2023-02-11 10:06 UTC, osuShiro commented on wiki/People/Users_with_unique_titles/fr.md
>  Les titres d'utilisateurs sont généralement associés aux [groupes d'utilisateurs](/wiki/People/The_Team#groupes-d'utilisateurs), mais les utilisateurs listés ci-dessous ont reçu leur titre pour d'aut
```suggestion
Les titres d'utilisateurs sont généralement associés aux [groupes d'utilisateurs](/wiki/People/The_Team#groupes-d'utilisateurs), mais les utilisateurs listés ci-dessous ont reçu leur titre pour d'autres raisons. La plupart des titres étaient des récompenses pour des contributions ou des exploits, les autres étant des symboles de l'histoire emblématique ou amusante d'osu!.
```

2023-03-09 07:33 UTC, Biokax approved these changes

2023-03-09 17:34 UTC, osuShiro approved these changes

2023-03-09 17:45 UTC, merged

2023-03-09 18:24 UTC, agatemosu commented
#8823 is missing