[EN/ZH] Add `Yuyuko's Hidden Cup Season 2` and Update `tournaments`
ppy/osu-wiki pull request #8771
Opened 2023-02-07 11:06 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-02-09 02:15 UTC, TPGPL commented
pretty sure wiki doesn't support `.svg` files like that, you should convert them to `.jpg` and add some background as it may not be well visible on the site

2023-02-09 02:28 UTC, TPGPL requested changes
apply the changes to ZH where possible as well

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +![YHC S2 Banner](img/banner.jpg)
```suggestion
![YHC S2 banner](img/banner.jpg) 
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +The **Yuyuko's Hidden Cup Season 2** (***YHC S2***) was a team-based 3v3 double-elimination osu! gamemode tournament hosted by ::{ flag=CN }:: [SIyuyuko](https://osu.ppy.sh/users/9794030). It was the
```suggestion
The **Yuyuko's Hidden Cup Season 2** (***YHC S2***) was a team-based 3v3 double-elimination osu! tournament hosted by ::{ flag=CN }:: [SIyuyuko](https://osu.ppy.sh/users/9794030). It was the 2nd instalment of the Yuyuko's Hidden Cup.
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +| Elimination stage 2 | 2023-1-18/2023-2-5 |
```suggestion
| Group stage | 2022-12-28/2023-01-08 |
| Elimination stage 1 | 2023-01-11/2023-01-15 |
| Elimination stage 2 | 2023-01-18/2023-02-05 |
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +<!-- for team/country-based tournaments -->
```suggestion
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +| Team Code | Team Name | Members |
```suggestion
| Team code | Team name | Members |
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Elimination Stage 2 (Round 3)
```suggestion
### Elimination stage 2 (Round 3)
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- HD
```suggestion
- Hidden
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- NM
```suggestion
- NoMod
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- DT
```suggestion
- DoubleTime
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- FM
```suggestion
- FreeMod
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- TB
```suggestion
- Tiebreaker
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +  1. [**DystopiaGround - AugoEidEs (jonathanlfj) [Angelic]**](https://osu.ppy.sh/beatmapsets/136969#osu/342543)
```suggestion
  1. **[DystopiaGround - AugoEidEs (jonathanlfj) [Angelic]](https://osu.ppy.sh/beatmapsets/136969#osu/342543)**
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +  2. [Soleily feat. SUNRaiSE - Rise Above (Nytrocide_) [-Sylvari's Insane]](https://osu.ppy.sh/beatmapsets/1767895#osu/3661739)
```suggestion
  2. [Soleily feat. SUNRaiSE - Rise Above (Nytrocide\_) [-Sylvari's Insane]](https://osu.ppy.sh/beatmapsets/1767895#osu/3661739)
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Elimination Stage 1 (Round 2)
```suggestion
### Elimination stage 1 (Round 2)
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- HD
```suggestion
- Hidden
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- NM
```suggestion
- NoMod
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- DT
```suggestion
- DoubleTime
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- FM
```suggestion
- FreeMod
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- TB
```suggestion
- Tiebreaker
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +  1. [**earthmind - Another Heaven (Kalibe) [Sakura]**](https://osu.ppy.sh/beatmapsets/571626#osu/1308941)
```suggestion
  1. **[earthmind - Another Heaven (Kalibe) [Sakura]](https://osu.ppy.sh/beatmapsets/571626#osu/1308941)**
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Group Stage (Round 1)
```suggestion
### Group stage (Round 1)
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- HD
```suggestion
- Hidden
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- NM
```suggestion
- NoMod
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- DT
```suggestion
- DoubleTime
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- FM
```suggestion
- FreeMod
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +- TB
```suggestion
- Tiebreaker
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +  1. [**Marika - Truth and Light (ponbot) [gazimal’s Insane]**](https://osu.ppy.sh/beatmapsets/1594534#osu/3256904)
```suggestion
  1. **[Marika - Truth and Light (ponbot) [gazimal’s Insane]](https://osu.ppy.sh/beatmapsets/1594534#osu/3256904)**
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Elimination Stage 2 (Round 3)
```suggestion
### Elimination stage 2 (Round 3)
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +| 老年娱乐 ::{ flag=CN }:: | 2 | **7** | ::{ flag=CN }:: **懒人三项** | [#106652243](https://osu.ppy.sh/community/matches/106652243) |
```suggestion
| 已经结束啦 ::{ flag=CN }:: | 2 | **7** | ::{ flag=CN }:: **老年娱乐** | [#1](https://osu.ppy.sh/community/matches/106494978) |
| 主播教我HD刷170 ::{ flag=CN }:: | 2 | **7** | ::{ flag=CN }:: **懒人三项** | [#1](https://osu.ppy.sh/community/matches/106474264) |
| 已经结束啦 ::{ flag=CN }:: | 2 | **7** | ::{ flag=CN }:: **懒人三项** | [#1](https://osu.ppy.sh/community/matches/106647542) |
| 老年娱乐 ::{ flag=CN }:: | 2 | **7** | ::{ flag=CN }:: **懒人三项** | [#1](https://osu.ppy.sh/community/matches/106652243) |
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Elimination Stage 1 (Round 2)
```suggestion
### Elimination stage 1 (Round 2)
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +| 东雪莲后援会 ::{ flag=CN }:: | 1 | **6** | ::{ flag=CN }:: **懒人三项** | [#106288941](https://osu.ppy.sh/community/matches/106288941) |
```suggestion
| 主播教我HD刷170 ::{ flag=CN }:: | 2 | **6** | ::{ flag=CN }:: **已经结束啦** | [#1](https://osu.ppy.sh/community/matches/106265442) |
| **老年娱乐**::{ flag=CN }:: | **6** | 1 | ::{ flag=CN }:: 东雪莲后援会 | [#1](https://osu.ppy.sh/community/matches/106245589) |
| **主播教我HD刷170** ::{ flag=CN }:: | **6** | 1 | ::{ flag=CN }:: 无所谓 帕老师会出手 | [#1](https://osu.ppy.sh/community/matches/106267609) |
| 东雪莲后援会 ::{ flag=CN }:: | 1 | **6** | ::{ flag=CN }:: **懒人三项** | [#1](https://osu.ppy.sh/community/matches/106288941) |
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Group Stage (Round 1)
```suggestion
### Group stage (Round 1)
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +| **东雪莲后援会** ::{ flag=CN }:: | **5** | 1 | ::{ flag=CN }:: 无所谓 帕老师会出手 | [#106089411](https://osu.ppy.sh/community/matches/106089411) |
```suggestion
| 无所谓 帕老师会出手 ::{ flag=CN}:: | 1 | **5** | ::{ flag=CN }:: **主播教我HD刷170** | [#1](https://osu.ppy.sh/community/matches/105951662) |
| **主播教我HD刷170** ::{ flag=CN }:: | **5** | 2 | ::{ flag=CN }:: 东雪莲后援会 | [#1](https://osu.ppy.sh/community/matches/105992915) |
| **东雪莲后援会** ::{ flag=CN }:: | **5** | 1 | ::{ flag=CN }:: 无所谓 帕老师会出手 | [#1](https://osu.ppy.sh/community/matches/106089411) |
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +| 懒人三项 ::{ flag=CN }:: | 4 | **5** | ::{ flag=CN }:: 老年娱乐 | [#106113040](https://osu.ppy.sh/community/matches/106113040) |
```suggestion
| **老年娱乐** ::{ flag=CN }:: | **5** | 1 | ::{ flag=CN }:: 已经结束啦 | [#1](https://osu.ppy.sh/community/matches/105975299) |
| **已经结束啦** ::{ flag=CN }:: | **5** | 1 | ::{ flag=CN }:: 懒人三项 | [#1](https://osu.ppy.sh/community/matches/105990432) |
| **懒人三项** ::{ flag=CN }:: | 4 | **5** | ::{ flag=CN }:: 老年娱乐 | [#1](https://osu.ppy.sh/community/matches/106113040) |
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Tournament Registration
```suggestion
### Tournament registration
```

2023-02-09 02:28 UTC, TPGPL commented on wiki/Tournaments/YHC/2/en.md
> +### Team-up Information
```suggestion
### Team-up information
```

2023-02-09 17:54 UTC, YumeMuzi commented
> pretty sure wiki doesn't support `.svg` files like that, you should convert them to `.jpg` and add some background as it may not be well visible on the site

ok i'll replace these svg files tmr

2023-02-10 05:40 UTC, YumeMuzi commented
should I wait for #8685 to be merged? we edited the same file but in different paragraphs.

2023-02-10 13:06 UTC, TPGPL commented
doesn't matter i think, both can be merged in whatever order

2023-02-10 15:52 UTC, TPGPL approved these changes

2023-02-10 15:53 UTC, merged