osu! pixel Wiki Spanish version
ppy/osu-wiki pull request #8786
Opened 2023-02-11 00:32 UTC by abbytec

-Abby-

## Self-check

- [ X ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ X ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-02-12 09:40 UTC, agatemosu commented
To mark the self-check do it after sending the PR

2023-02-12 09:46 UTC, agatemosu requested changes

2023-02-12 09:46 UTC, agatemosu commented on wiki/Client/Beatmap_editor/osu!_pixel/es.md
> +<!-- TODO: needs links -->
```suggestion
```

2023-02-12 09:46 UTC, agatemosu commented on wiki/Client/Beatmap_editor/osu!_pixel/es.md
> +  - coordinate system
```suggestion
  - coordinate system
  - sistema de coordenadas
```

2023-02-12 09:46 UTC, agatemosu commented on wiki/Client/Beatmap_editor/osu!_pixel/es.md
> +Los **osupixels** son uno de los sistemas de coordenadas principales de osu! y aplican a todas las coordenadas de storyboards y [hit objects](/wiki/Hit_object). El tamaño de un osu!pixel cambia depen
```suggestion
Los **osupixels** son uno de los principales sistemas de coordenadas de osu! y aplican a todas las ubicaciones de los [objetos](/wiki/Hit_object) y las coordenadas de los storyboards. El tamaño de un osu!pixel cambia dependiendo de la resolucion seleccionada actualmente, pero es quivalente a un pixel cuando osu! se está ejecutando en resolución 640x480. Esta escala asegura una experiencia juego justa para todos los jugadores.
```

2023-02-12 09:46 UTC, agatemosu commented on wiki/Client/Beatmap_editor/osu!_pixel/es.md
> +El escalado se alplica al sistema de coodenadas principal, que es utilizado para [osu! gameplay](/wiki/Gameplay). En constraste, las texturas son escaladas de manera que un [texture pixel](https://es
```suggestion
El escalado se aplica al sistema de coordenadas principal que se utiliza para el [juego de osu!](/wiki/Gameplay). Por el contrario, las texturas se escalan de manera que un [téxel](https://es.wikipedia.org/wiki/Texel_(gráficos)) corresponde a un píxel de pantalla con una resolución de 1024x768.
```

2023-03-24 14:47 UTC, TicClick approved these changes

2023-03-24 15:06 UTC, merged