Added entry for OTMT
ppy/osu-wiki pull request #8809
Opened 2023-02-15 16:41 UTC by cdhsausageboy

## Self-check

- [ x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-02-15 17:04 UTC, Walavouchey requested changes
- replace `’` with `'`
- don't capitalise "tiebreaker" in the middle of sentences

will check more thoroughly a bit later

2023-02-15 17:15 UTC, Walavouchey commented
![image](https://user-images.githubusercontent.com/36758269/219102579-ec89c66e-edec-4c88-b847-44ec642adea9.png)


<https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#making-edits>

![image](https://user-images.githubusercontent.com/36758269/219102478-8d12b5bd-9a1f-428b-8ffe-b7754d707502.png)

we'll squash the commits for you before merging (hence `state:needs rebase` label), but in the future, try to condense the amount of commits. this can easily be done on the github website by creating a new branch and copying the final changes to it.

2023-02-15 17:35 UTC, cdhsausageboy commented on wiki/Tournaments/OTMT/2022/en.md
> +🎵 **= Custom song**
done.

2023-02-15 17:35 UTC, cdhsausageboy commented on wiki/Tournaments/OTMT/en.md
> +- [OTMT 2022](2022)
done.

2023-02-15 17:47 UTC, cdhsausageboy commented on wiki/Tournaments/OTMT/2022/en.md
> +| Grand Finals | 2022-11-27 |
done.

2023-02-15 17:51 UTC, cdhsausageboy commented on wiki/Tournaments/OTMT/2022/en.md
> +| *4th place* | RM56 (~13USD), 1 month osu Supporter Tag, Custom IRIS Voice Line |
changed the first two points. custom iris voice line refers to a victory voice line customised to the winner of the tournament narrated by our mascot iris.

2023-03-15 19:01 UTC, Walavouchey commented
squashed 100+ commits

2023-03-15 19:01 UTC, Walavouchey submitted a review, later dismissed

2023-03-15 19:07 UTC, Walavouchey submitted a review, later dismissed

2023-03-15 19:08 UTC, Walavouchey submitted a review, later dismissed

2023-03-15 19:10 UTC, Walavouchey commented
please check my commits to see what changes were required. in particular, make sure to follow the [tournament template](https://github.com/ppy/osu-wiki/blob/master/wiki/Tournaments/TEMPLATE.md)

2023-03-15 20:20 UTC, Walavouchey approved these changes

2023-03-15 20:21 UTC, merged