Add TWC 2023 - Registrations Now Open news post
ppy/osu-wiki pull request #8810
Opened 2023-02-15 19:07 UTC by LeoFLT

PRing this a few hours ahead of schedule for reviewing.

## To-do before merging

- [ ] create tournament listing for TWC 2023 (it should have the id = 37)
- [x] create forum thread (set as private until the post is live)
- [x] create Open Collective event

2023-02-15 19:19 UTC, Walavouchey requested changes
otherwise ok

2023-02-15 19:19 UTC, Walavouchey commented on news/2023/2023-02-16-osu-taiko-world-cup-2023-registrations-now-open.md
> +Bring along your favorite percussion instrument as we once again drum to the beat. The osu!taiko World Cup is back for its 13th instalment!
```suggestion
Bring along your favourite percussion instrument as we once again drum to the beat. The osu!taiko World Cup is back for its 13th instalment!
```

2023-02-15 19:19 UTC, Walavouchey commented on news/2023/2023-02-16-osu-taiko-world-cup-2023-registrations-now-open.md
> +The TWC has a reputation among its managers as a testing grounds of sorts as far as the official tournaments go, and this year couldn't be any different – we are bringing back the 3 versus 3 format,
```suggestion
The TWC has a reputation among its managers as being a testing ground of sorts as far as the official tournaments go, and this year couldn't be any different – we are bringing back the 3 vs. 3 format, which made its last appearance in 2017, in the hopes that it'd shake things up a bit (looking at you, Japan). This relatively small change impacts many rules, so make sure to get up to speed by reading the [wiki article](/wiki/Tournaments/TWC/2023#ruleset).
```

2023-02-15 19:19 UTC, Walavouchey commented on news/2023/2023-02-16-osu-taiko-world-cup-2023-registrations-now-open.md
> +If you're still not familiar with Open Collective, it is a platform that allows us to coordinate the finances of the World Cups in a transparent way, and also allows users to help support the tournam
```suggestion
If you're still not familiar with Open Collective, it is a platform that allows us to coordinate the finances of the World Cups in a transparent way, and also allows users to help support the tournament in greater amounts outside of purchasing profile banners or subscribing to the osu!live Twitch channel. You can do any one (or all) of these things if you want and they'll still go towards the tournament!
```

2023-02-15 19:19 UTC, Walavouchey commented on news/2023/2023-02-16-osu-taiko-world-cup-2023-registrations-now-open.md
> +For more details, refer to the [osu!taiko World Cup 2023 wiki article](/wiki/Tournaments/TWC/2023). You can discuss this event in the [official discussion thread](https://osu.ppy.sh/community/forums/
```suggestion
For more details, refer to the [osu!taiko World Cup 2023 wiki article](/wiki/Tournaments/TWC/2023). You can discuss this event in the [official discussion thread](https://osu.ppy.sh/community/forums/topics/1722224) or at the public [osu! community server](https://discord.gg/0Vxo9AsejDkGlk3H).
```

2023-02-15 19:19 UTC, Walavouchey commented on news/2023/2023-02-16-osu-taiko-world-cup-2023-registrations-now-open.md
> +The osu!taiko World Cup 2023 offers a $2,000 prize pool, along with limited edition merch! The prize pool may increase further from **[community donations](https://opencollective.com/osu-tournaments/
```suggestion
The osu!taiko World Cup 2023 offers a $2,000 prize pool, along with limited-edition merch! The prize pool may increase further from **[community donations](https://opencollective.com/osu-tournaments/events/osu-taiko-world-cup-2023-13130e56)**!
```

2023-02-15 19:47 UTC, Walavouchey submitted a review, later dismissed

2023-02-16 00:04 UTC, Walavouchey approved these changes

2023-02-16 00:23 UTC, Ephemeralis approved these changes

2023-02-16 00:55 UTC, merged