[FR] Update `Article_styling_criteria/Formatting`
ppy/osu-wiki pull request #8831
Opened 2023-02-22 15:34 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-01 10:23 UTC, Biokax submitted a review, later dismissed

2023-03-02 06:38 UTC, Ganondorf-1 requested changes

2023-03-02 06:38 UTC, Ganondorf-1 commented on wiki/Article_styling_criteria/Formatting/fr.md
> +Seuls les niveaux de titre 4 et 5 sont autorisés dans une infobox. Ceux-ci n'apparaissent pas dans la table des matières et tout ce qui est inférieur est trop grand. Toute [erreur de CI checks](/wiki
```suggestion
Seuls les niveaux de titre 4 et 5 sont autorisés dans une infobox. Ceux-ci n'apparaissent pas dans la table des matières et tout ce qui est inférieur est trop grand. Toute [erreur de CI check](/wiki/osu!_wiki/Maintenance#ci-checks) peut avoir besoin d'être contournée pour cette raison.
```

2023-03-03 08:45 UTC, Ganondorf-1 approved these changes

2023-03-03 15:06 UTC, TicClick approved these changes

2023-03-03 15:19 UTC, merged