[FR] Update `Tournaments/Official support`
ppy/osu-wiki pull request #8833
Opened 2023-02-22 15:53 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-01 10:32 UTC, Biokax commented on wiki/Tournaments/Official_support/fr.md
> +Seuls les joueurs qui participent au tournoi **ou** qui seraient des remplaçants probables pour une équipe constituée au cours du tournoi devraient être envoyés en screening. Par exemple, dans le cas
Je pense que pour le "système d'essais" on peut préciser que ça correspond à "tryout" en anglais car dans tous les tournois on utilise ce terme

2023-03-01 15:11 UTC, Pisapou commented on wiki/Tournaments/Official_support/fr.md
> +Seuls les joueurs qui participent au tournoi **ou** qui seraient des remplaçants probables pour une équipe constituée au cours du tournoi devraient être envoyés en screening. Par exemple, dans le cas
ah peut-être je sais pas, je vais attendre un review de ganon pour les terme ou l'on est pas sûr si il faut traduire ou pas

2023-03-02 06:55 UTC, Ganondorf-1 requested changes

2023-03-02 06:55 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +- Le tournoi doit se conformer à toutes les [attentes](#attentes) des tournois officiellement soutenus.
```suggestion
- Le tournoi doit se conformer à toutes les [attentes](#attentes) des tournois bénéficiant de support officiel.
```

2023-03-02 06:55 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +- Tous les matchs multijoueur relatifs au tournoi doivent être créés avec la commande `!mp make`, afin qu'ils n'expirent pas. Les résultats doivent être enregistrés et rendus publics sur le post orig
```suggestion
- Tous les matchs multijoueur relatifs au tournoi doivent être créés avec la commande `!mp make`, afin qu'ils n'expirent pas. Les résultats doivent être enregistrés et rendus publics sur le post original du forum du tournoi ou sur une source extérieure dans le post du forum dans un format clair et accessible.
```

2023-03-02 06:55 UTC, Ganondorf-1 commented on wiki/Tournaments/Official_support/fr.md
> +Seuls les joueurs qui participent au tournoi **ou** qui seraient des remplaçants probables pour une équipe constituée au cours du tournoi devraient être envoyés en screening. Par exemple, dans le cas
```suggestion
Seuls les joueurs qui participent au tournoi **ou** qui seraient de potentiels remplaçants pour une équipe constituée au cours du tournoi devraient être envoyés pour passer le screening. Par exemple, dans le cas d'un tournoi national utilisant un système de tryouts, les organisateurs sont encouragés à n'envoyer que les joueurs dont la participation au tournoi a été déterminée suite aux tryouts, ainsi que plusieurs remplaçants pour chaque équipe au cas où ils devraient participer. Pour savoir quels joueurs sont inscrits au screening à un tournoi, contactez le [Comité des tournois](/wiki/People/Tournament_Committee).
```

2023-03-02 08:27 UTC, Biokax commented on wiki/Tournaments/Official_support/fr.md
> +Seuls les joueurs qui participent au tournoi **ou** qui seraient des remplaçants probables pour une équipe constituée au cours du tournoi devraient être envoyés en screening. Par exemple, dans le cas
ce serait mieux de préciser le sens de tryout dans cette phrase tu ne penses pas ?

2023-03-03 08:48 UTC, Ganondorf-1 approved these changes

2023-03-03 15:05 UTC, TicClick approved these changes

2023-03-03 15:15 UTC, merged