[FR] Update `Client/Release stream/Lazer/File storage`
ppy/osu-wiki pull request #8834
Opened 2023-02-22 15:57 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-01 10:37 UTC, Biokax commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +#### Supported systems
```suggestion
#### Systèmes supportés
```

2023-03-01 10:37 UTC, Biokax commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +#### Supported systems
petit oubli

2023-03-02 06:57 UTC, Ganondorf-1 requested changes

2023-03-02 06:57 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +#### Systèmes supportés
```suggestion
#### Systèmes pris en charge
```

2023-03-02 06:57 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +- **Windows**: Le lecteur doit être formaté en NTFS.
```suggestion
- **Windows** : Le lecteur doit être formaté en NTFS.
```

2023-03-02 06:57 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +- **macOS**: Le système de fichiers doit prendre en charge les liens physiques.
```suggestion
- **macOS** : Le système de fichiers doit prendre en charge les liens physiques.
```

2023-03-02 06:57 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/File_storage/fr.md
> +- **Linux**: Le système de fichiers doit prendre en charge les liens physiques.
```suggestion
- **Linux** : Le système de fichiers doit prendre en charge les liens physiques.
```

2023-03-03 08:50 UTC, Ganondorf-1 approved these changes

2023-03-03 15:05 UTC, TicClick approved these changes

2023-03-03 15:14 UTC, merged