[FR] Update `Help centre/Account restrictions`
ppy/osu-wiki pull request #8835
Opened 2023-02-22 16:01 UTC by Pisapou

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-01 10:42 UTC, Biokax commented on wiki/Help_centre/Account_restrictions/fr.md
> +Les retours d'appel dans les conditions standard ci-dessus sont également interdits de tournois officiels, à la fois en tant que joueur et membre de l'équipe du tournoi. La durée de ce bannissement e
```suggestion
Les retours d'appel dans les conditions standard ci-dessus sont également interdits de tournois officiels et badgés, à la fois en tant que joueur et membre de l'équipe du tournoi. La durée de ce bannissement est d'un an par restriction (si l'utilisateur en est à sa deuxième restriction, le bannissement durera 2 ans). L'équipe de support aux comptes clarifiera la durée de ce bannissement.
```

2023-03-01 10:42 UTC, Biokax commented on wiki/Help_centre/Account_restrictions/fr.md
> +Les retours d'appel dans les conditions standard ci-dessus sont également interdits de tournois officiels, à la fois en tant que joueur et membre de l'équipe du tournoi. La durée de ce bannissement e
il manquait un bout

2023-03-01 15:20 UTC, Biokax approved these changes

2023-03-02 07:02 UTC, Ganondorf-1 requested changes

2023-03-02 07:02 UTC, Ganondorf-1 commented on wiki/Help_centre/Account_restrictions/fr.md
> +Les retours d'appel dans les conditions standard ci-dessus sont également interdits de tournois officiels et badgés, à la fois en tant que joueur et membre de l'équipe du tournoi. La durée de ce bann
```suggestion
Les utilisateurs qui sortent d'une restriction dans les conditions standard ci-dessus sont également interdits de participer aux tournois officiels et badgés, à la fois en tant que joueur et membre de l'équipe du tournoi. La durée de ce bannissement est d'un an par restriction (si l'utilisateur en est à sa deuxième restriction, le bannissement durera 2 ans). L'équipe de support aux comptes clarifiera la durée de ce bannissement.
```

2023-03-02 07:02 UTC, Ganondorf-1 commented on wiki/Help_centre/Account_restrictions/fr.md
>  **Tricher ou partager son compte durant un tournoi officiel mènera à un bannissement permanent de l'utilisateur.** Vous ne pouvez pas faire appel quant à ce bannissement (votre mail sera ignoré si vo
```suggestion
**Tricher ou partager son compte durant un tournoi officiel mènera à un bannissement permanent de l'utilisateur.** Vous ne pouvez pas faire appel quant à ce bannissement (votre mail sera ignoré si vous essayez) et il ne sera en aucun cas supprimé, réduit ou levé.
```

2023-03-02 07:02 UTC, Ganondorf-1 commented on wiki/Help_centre/Account_restrictions/fr.md
> +- La ppossibilité de participer à des salles multijoueurs
```suggestion
- La possibilité de participer à des salles multijoueurs
```

2023-03-03 08:53 UTC, Ganondorf-1 approved these changes

2023-03-03 15:11 UTC, merged