[FR] Update `osu!supporter`
ppy/osu-wiki pull request #8837
Opened 2023-02-22 16:20 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-01 10:52 UTC, Biokax submitted a review, later dismissed

2023-03-02 07:07 UTC, Ganondorf-1 requested changes

2023-03-02 07:07 UTC, Ganondorf-1 commented on wiki/osu!supporter/fr.md
> +- `{nom_d'utilisateur} a soutenu osu! - merci pour votre générosité !` si c'est la première fois que l'utilisateur reçoit un osu!supporter ou l'offre à quelqu'un d'autre.
```suggestion
- `{nom_d'utilisateur} a soutenu osu! - merci pour votre générosité !` si c'est la première fois que l'utilisateur achète un tag osu!supporter ou l'offre à quelqu'un d'autre.
```

2023-03-03 08:54 UTC, Ganondorf-1 approved these changes

2023-03-03 15:04 UTC, TicClick approved these changes

2023-03-03 15:09 UTC, merged