Use new footnote syntax in `History of osu!/2014`
ppy/osu-wiki pull request #8876
Opened 2023-03-02 21:34 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-03-02 21:42 UTC, Walavouchey requested changes

2023-03-02 21:42 UTC, Walavouchey commented on wiki/History_of_osu!/2014/en.md
> +[^bat]: [osu! newspost by Ephemeral (21 August 2014) - "Restructuring of the BAT"](https://osu.ppy.sh/home/news/2014-08-21-restructuring-of-the-bat)
should conform the formatting according to the examples in the asc https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#citations

2023-03-02 21:42 UTC, Walavouchey commented on wiki/History_of_osu!/2014/en.md
> +On 1 March 2014 the performance points system redesign by Tom94 in months prior was ready to be set live for [osu!taiko](/wiki/Game_mode/osu!taiko), [osu!catch](/wiki/Game_mode/osu!catch), and [osu!m
```suggestion
On 1 March 2014 the performance points system redesign by Tom94 in months prior was ready to be set live for [osu!taiko](/wiki/Game_mode/osu!taiko), [osu!catch](/wiki/Game_mode/osu!catch), and [osu!mania](/wiki/Game_mode/osu!mania) as the official ranking system for those modes, along with a reminder that the current system was not yet 100% finished, and further feedback from players was still needed.[^all-game-modes]
```

2023-03-02 21:42 UTC, Walavouchey commented on wiki/History_of_osu!/2014/en.md
> +As [skinning](/wiki/Skinning) elements expanded, the element, `playfield.jpg` was deprecated and replaced with a new generic one that is not modifiable. `playfield.jpg` was an element that allowed sk
```suggestion
As [skinning](/wiki/Skinning) elements expanded, the element, `playfield.jpg` was deprecated and replaced with a new generic one that is not modifiable. `playfield.jpg` was an element that allowed skinners to use any image as the default background of a beatmap if one was not supplied. This functionality was later brought in the form of `menu-background.jpg`, which changed both the main screen and default playfield backgrounds.[^change-background][^skinning]<!--date needed-->
```

2023-03-03 14:31 UTC, The-Last-Cookie commented on wiki/History_of_osu!/2014/en.md
> +[^ranking-maintenance]: [osu! newspost by peppy (2014-01-20) "Performance Ranking Maintenance"](https://osu.ppy.sh/home/news/2014-01-20-performance-ranking-maintenance)
I've outdated the translations to make the contributors aware of these lines specifically.

2023-03-03 15:02 UTC, TicClick approved these changes

2023-03-03 15:22 UTC, merged