[DE] Update `osu! wiki/Maintenance`
ppy/osu-wiki pull request #8907
Opened 2023-03-07 21:51 UTC by The-Last-Cookie

## Translation notes

- not sure if my translation of line 102 is correct. The line in combination of with the three bullet points below seems odd to me. Maybe I'm just too tired. I or someone else should take a second look with a fresh mind.
- `Markdown "rule" remark lint rule` was not easy to translate. I've settled for `Lint-Regel "Regel" von remark für Markdown`. If that sounds too chunky, I could change it to `Markdown-Lint-Regel "Regel" von remark`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-08 19:24 UTC, respektive requested changes

2023-03-08 19:24 UTC, respektive commented on wiki/osu!_wiki/Maintenance/de.md
> +##### Lint-Regel [`no-heading-punctuation`](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-heading-punctuation) von remark für Markdown
seems fine to me

2023-03-08 19:24 UTC, respektive commented on wiki/osu!_wiki/Maintenance/de.md
> +Titel sind im Allgemeinen keine vollständigen Sätze. Dadurch treten Satzzeichen am Ende von Überschriften normalerweise nicht auf und sind auch nicht erlaubt. Satzzeichen am Ende des Titels werden je
```suggestion
Titel sind im Allgemeinen keine vollständigen Sätze. Dadurch treten Satzzeichen am Ende von Überschriften normalerweise nicht auf und sind auch nicht erlaubt. Satzzeichen am Ende des Titels werden jedoch manchmal gebraucht, wenn sie beispielsweise in Songtiteln oder Künstlernamen enthalten sind.
```

2023-03-08 19:24 UTC, respektive commented on wiki/osu!_wiki/Maintenance/de.md
> +- [scissors](https://github.com/TicClick/scissors): ein Rust-Tool zur Überprüfung von Unstimmigkeiten zwischen Benutzernamen und Länderkennzeichen in Benutzerlinks
```suggestion
- [scissors](https://github.com/TicClick/scissors): ein Rust-Tool zur Überprüfung von Unstimmigkeiten zwischen Benutzernamen und Länderflaggen in Benutzerlinks
```

2023-03-13 12:19 UTC, The-Last-Cookie commented
Thank you 👍

2023-03-13 13:18 UTC, respektive approved these changes

2023-03-13 14:16 UTC, TicClick approved these changes

2023-03-13 14:23 UTC, merged