[ID] Update `Client` translation, create `Release stream` and `How to search for and download beatmaps ` (placeholder) translations.
ppy/osu-wiki pull request #8927
Opened 2023-03-11 06:04 UTC by FazlyMR

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-16 05:04 UTC, wowcake requested changes

2023-03-16 05:04 UTC, wowcake commented on wiki/Client/Release_stream/id.md
> +osu! memiliki beberapa **versi rilis**, atau versi klien permainan, yang mendapatkan pembaruan dengan jumlah yang berbeda-beda. Agar dapat menangani masalah-masalah secara dini, fitur dan perubahan-p
```suggestion
osu! memiliki beberapa **versi rilis**, atau versi klien permainan, yang mendapatkan pembaruan dengan jumlah yang berbeda-beda. Agar dapat menangani masalah-masalah secara dini, fitur dan perubahan-perubahan baru akan ditambahkan terlebih dahulu di dalam versi-versi *preview* (pratinjau) untuk dicoba sebelum akhirnya ditambahkan ke dalam versi stable.
```

2023-03-17 15:09 UTC, Nivalyx commented on wiki/Client/Release_stream/id.md
> +| Beta | Menerima pembaruan setelah Cutting Edge; tidak mendapat fitur baru |
```suggestion
| Beta | Menerima pembaruan setelah Cutting Edge; tidak lagi memperoleh fitur baru |
```

2023-03-17 15:09 UTC, Nivalyx commented on wiki/Client/Release_stream/id.md
> +| Cutting Edge | Mendapat pembaruan terbaru; tidak mendapat fitur baru |
```suggestion
| Cutting Edge | Menerima pembaruan paling pertama; tidak lagi memperoleh fitur baru |
```

2023-03-23 14:52 UTC, FazlyMR commented on wiki/Client/Release_stream/id.md
> +osu! memiliki beberapa **versi rilis**, atau versi klien permainan, yang mendapatkan pembaruan dengan jumlah yang berbeda-beda. Agar dapat menangani masalah-masalah secara dini, fitur dan perubahan-p
This one is nicer to read for sure.

2023-03-24 07:23 UTC, Nivalyx approved these changes

2023-03-24 14:43 UTC, merged