[DE] Update `Gameplay/Kiai time`
ppy/osu-wiki pull request #8963
Opened 2023-03-14 23:49 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-15 20:16 UTC, respektive requested changes

2023-03-15 20:16 UTC, respektive commented on wiki/Gameplay/Kiai_time/de.md
> +Obwohl die Kiai-Zeit keinen Einfluss auf die Spielmechanik von osu!, osu!catch oder osu!mania hat, bringt sie in [osu!taiko](/wiki/Game_mode/osu!taiko) 20 % mehr [Score](/wiki/Gameplay/Score).
```suggestion
Während die Kiai-Zeit keinen Einfluss auf die Spielmechanik von osu!, osu!catch oder osu!mania hat, bringt sie in [osu!taiko](/wiki/Game_mode/osu!taiko) 20 % mehr [Score](/wiki/Gameplay/Score).
```

2023-03-17 18:10 UTC, respektive approved these changes

2023-03-18 02:41 UTC, TicClick approved these changes

2023-03-18 13:24 UTC, merged