[FR] Add `Release stream` and `Lazer release stream`
ppy/osu-wiki pull request #8970
Opened 2023-03-17 20:17 UTC by Ganondorf-1

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-17 20:55 UTC, Pisapou requested changes

2023-03-17 20:55 UTC, Pisapou commented on wiki/Client/Release_stream/fr.md
> +osu! dispose de plusieurs **canaux de mise à jour**. Ces canaux de mise à jour sont les différentes versions du jeu, qui reçoivent des mises à jour à des rythmes différents. Afin de détecter rapideme
```suggestion
osu! dispose de plusieurs **canaux de mise à jour**. Ces canaux de mise à jour sont les différentes versions du jeu, qui reçoivent des mises à jour à des rythmes différents. Afin de détecter rapidement les problèmes potentiels, les nouvelles fonctionnalités et les modifications sont intégrées dans des versions de test avant d'être intégrées au client stable.
```

2023-03-17 20:55 UTC, Pisapou commented on wiki/Client/Release_stream/fr.md
> +| Stable | Version actuelle du client ; [ne reçoit plus de nouvelles fonctionnalités](https://fr.wikipedia.org/wiki/Feature_freeze) ; reçoit les mises à jour après la version Beta. |
```suggestion
| Stable | Version actuelle du client, la plus utilisée ; [ne reçoit plus de nouvelles fonctionnalités](https://fr.wikipedia.org/wiki/Feature_freeze) ; reçoit les mises à jour après la version Beta. |
```

2023-03-17 20:55 UTC, Pisapou commented on wiki/Client/Release_stream/fr.md
> +| [Lazer](Lazer) | Client du jeu réécrit ; avec le développement le plus actif et [beaucoup de différences et de nouvelles fonctionnalités](/wiki/Client/Release_stream/Lazer/Feature_comparison). |
```suggestion
| [Lazer](Lazer) | Client du jeu réécrit ; le plus actif en matière de développement avec [de nombreuses différences et de nouvelles fonctionnalités](/wiki/Client/Release_stream/Lazer/Feature_comparison). |
```

2023-03-26 01:25 UTC, TicClick approved these changes

2023-03-26 01:26 UTC, merged