[ZH] Add `Client/Beatmap_editor`
ppy/osu-wiki pull request #8982
Opened 2023-03-19 01:50 UTC by Sunnyboy971

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-24 06:20 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/zh.md
> +- Song setup
可以改成中文 (英文) 的方式，保留原文的同时将翻译的优先级提前，下文同理

2023-03-24 06:20 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/zh.md
> +- Song setup
包括副标题也是一样

2023-03-24 06:23 UTC, YumeMuzi requested changes
改掉那些comment就差不多了

2023-03-25 18:17 UTC, YumeMuzi approved these changes
seems great

2023-03-25 19:23 UTC, TicClick approved these changes

2023-03-25 19:25 UTC, merged