Create fr.md
ppy/osu-wiki pull request #8986
Opened 2023-03-19 22:28 UTC by bxnn

French translation of osu!wiki - Skinning Contest #1

2023-03-20 09:44 UTC, Ganondorf-1 requested changes

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +![Skinning Contest #1 banner](img/banner.jpg)
```suggestion
![Bannière du Skinning Contest #1](img/banner.jpg)
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +Le **Skinning Contest #1** était un concours de skinning ouvert à tous organisé par [skinship](https://skinship.xyz), une des plus grandes communautés de skinning d'osu!. C'était le premier concours
```suggestion
Le **Skinning Contest #1** était un concours de skinning ouvert à tous organisé par [skinship](https://skinship.xyz), une des plus grandes communautés de skinning d'osu!. C'était le premier concours de skinning officiel, et la première itération des Skinning Contests organisés par skinship.
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| Annonce | 08-03-2021 |
```suggestion
| Annonce | 08/03/2021 |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| Phase d'envoi | 08-03-2021/08-04-2021 |
```suggestion
| Phase d'envoi | 08/03/2021 - 08/04/2021 |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| Phase de vote | 29-04-2021/13-05-2021 |
```suggestion
| Phase de vote | 29/04/2021 - 13/05/2021 |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| Résultats | 27-05-2021 |
```suggestion
| Résultats | 27/05/2021 |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ![Gold crown](/wiki/shared/crown-gold.png "1ère place") | 6 mois d'osu!supporter, un badge de profil unique |
```suggestion
| ![Couronne en or](/wiki/shared/crown-gold.png "1ère place") | 6 mois d'osu!supporter, un badge de profil unique |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ![Silver crown](/wiki/shared/crown-silver.png "2nde place") | 4 mois d'osu!supporter, un badge de profil unique |
```suggestion
| ![Couronne d'argent](/wiki/shared/crown-silver.png "2nde place") | 4 mois d'osu!supporter, un badge de profil unique |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ![Bronze crown](/wiki/shared/crown-bronze.png "3ème place") | 2 mois d'osu!supporter, un badge de profil unique |
```suggestion
| ![Couronne de bronze](/wiki/shared/crown-bronze.png "3ème place") | 2 mois d'osu!supporter, un badge de profil unique |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +## Planning du Concours
```suggestion
## Planning du concours
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ::{ flag=DE }:: [RockRoller](https://osu.ppy.sh/users/8388854) | Planning du concours, screening des entrées , preparation du showcase |
```suggestion
| ::{ flag=DE }:: [RockRoller](https://osu.ppy.sh/users/8388854) | Planning du concours, screening des entrées, préparation du showcase |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ::{ flag=GB }:: [tetsui](https://osu.ppy.sh/users/10974678) | Planning du concours, preparation du showcase |
```suggestion
| ::{ flag=GB }:: [tetsui](https://osu.ppy.sh/users/10974678) | Planning du concours, préparation du showcase |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ::{ flag=PL }:: [watterino](https://osu.ppy.sh/users/3512261) | Monteur vidéo, preparation du showcase |
```suggestion
| ::{ flag=PL }:: [watterino](https://osu.ppy.sh/users/3512261) | Monteur vidéo, préparation du showcase |
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- [Article de Vote](https://osu.ppy.sh/home/news/2021-04-29-skinning-contest-voting-open)
```suggestion
- [Article des votes](https://osu.ppy.sh/home/news/2021-04-29-skinning-contest-voting-open)
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- [Thread de discussion](https://osu.ppy.sh/community/forums/topics/1266342)
```suggestion
- [Fil de discussion](https://osu.ppy.sh/community/forums/topics/1266342)
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- [Site Officiel](https://skinship.xyz)
```suggestion
- [Site officiel](https://skinship.xyz)
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- [Thread d'envoi des entrées](https://osu.ppy.sh/community/forums/topics/1266324)
```suggestion
- [Post forum des entrées au concours](https://osu.ppy.sh/community/forums/topics/1266324)
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- Les entrées ne doivent pas contenir du contenu inaproprié, malveillant ou épileptique, et doivent suivre les [règles de la communauté osu!](/wiki/Rules).
```suggestion
- Les entrées ne doivent pas contenir de contenu inaproprié, malveillant ou épileptique, et doivent suivre les [règles de la communauté d'osu!](/wiki/Rules).
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- Tous les assets doivent être crées par vous, ou après demande et crédit de l'auteur. Cela inclut, mais ne se limite pas à:
```suggestion
- Tous les assets doivent être créés par vous-même, ou utilisés après demande et crédit de l'auteur. Cela inclut, mais ne se limite pas à :
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +  - oeuvres (ex: oeuvres d'animes)
```suggestion
  - œuvres (ex : œuvres d'animes)
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- La plupart des menus in-game et au moins un mode de jeu doivent être skinnés. En d'autres termes, en plus des élémets de gameplay, les éléments suivants ne doivent pas être laissés par défaut:
```suggestion
- La plupart des menus en jeu et au moins un mode de jeu doivent être skinnés. En d'autres termes, en plus des éléments de gameplay, les éléments suivants ne doivent pas être laissés par défaut :
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +  - Panneau de ranking
```suggestion
  - Écran de résultats
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +  - Selection de map (pas forcément la sélection de mode)
```suggestion
  - Sélection de beatmap (pas forcément la sélection de mode)
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +  - Icônes de mods
```suggestion
  - Icônes des mods
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +  - Le main menu est optionnel, mais fortement recommandé
```suggestion
  - Le menu principal est optionnel, mais fortement recommandé
```

2023-03-20 09:44 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +- Chaque entrée doit être accompagnée d'un thread sur le forum pour participer au concours.
```suggestion
- Chaque entrée doit être accompagnée d'un post sur le forum pour participer au concours.
```

2023-03-20 09:48 UTC, Ganondorf-1 requested changes

2023-03-20 09:48 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| Phase d'envoi | 08/03/2021/08/04/2021 |
```suggestion
| Phase d'envoi | 08/03/2021 - 08/04/2021 |
```

2023-03-20 09:48 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| Phase de vote | 29/04/2021/13/05/2021 |
```suggestion
| Phase de vote | 29/04/2021 - 13/05/2021 |
```

2023-03-20 09:48 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ![Courrone d'Or](/wiki/shared/crown-gold.png "1ère place") | 6 mois d'osu!supporter, un badge de profil unique |
```suggestion
| ![Couronne d'or](/wiki/shared/crown-gold.png "1ère place") | 6 mois d'osu!supporter, un badge de profil unique |
```

2023-03-20 09:48 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ![Courrone d'Argent](/wiki/shared/crown-silver.png "2nde place") | 4 mois d'osu!supporter, un badge de profil unique |
```suggestion
| ![Couronne d'argent](/wiki/shared/crown-silver.png "2nde place") | 4 mois d'osu!supporter, un badge de profil unique |
```

2023-03-20 09:48 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +| ![Couronne de Bronze](/wiki/shared/crown-bronze.png "3ème place") | 2 mois d'osu!supporter, un badge de profil unique |
```suggestion
| ![Couronne de bronze](/wiki/shared/crown-bronze.png "3ème place") | 2 mois d'osu!supporter, un badge de profil unique |
```

2023-03-20 09:48 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +*Pour les resultats complets, se référer à la [page du concours](https://osu.ppy.sh/community/contests/126).*
```suggestion
*Pour les résultats complets, se référer à la [page du concours](https://osu.ppy.sh/community/contests/126).*
```

2023-03-30 20:02 UTC, Ganondorf-1 requested changes

2023-03-30 20:02 UTC, Ganondorf-1 commented on wiki/Contests/Skinning_Contest/1/fr.md
> +![](img/badge-winner.png "Badge du gagnant Skinning Contest #1 ") ![](img/badge-2nd.png "Badge de deuxième place du Skinning Contest #1") ![](img/badge-3rd.png "Badge de Troisième place du Skinning C
```suggestion
![](img/badge-winner.png "Badge du gagnant Skinning Contest #1 ") ![](img/badge-2nd.png "Badge de deuxième place du Skinning Contest #1") ![](img/badge-3rd.png "Badge de troisième place du Skinning Contest #1")
```

2023-04-22 13:03 UTC, TicClick approved these changes
(combined 19 commits into 3)

2023-04-22 13:04 UTC, merged