[FR] Add Timing
ppy/osu-wiki pull request #8989
Opened 2023-03-20 14:52 UTC by bxnn

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-22 12:04 UTC, Pisapou requested changes

2023-03-22 12:04 UTC, Pisapou commented on wiki/Beatmapping/Timing/fr.md
> +[The ranking criteria](/wiki/Ranking_Criteria#timing) have a section dedicated to timing, which explains the respective rules for beatmaps [going for Ranked](/wiki/Beatmap_ranking_procedure).
```suggestion
[Les critères de classement](/wiki/Ranking_Criteria#timing) ont une section dédiée au timing, qui explique les règles respectives pour les beatmaps [visant à être Ranked](/wiki/Beatmap_ranking_procedure).
```

2023-03-22 12:04 UTC, Pisapou commented on wiki/Beatmapping/Timing/fr.md
> +## See also
```suggestion
## Voir aussi
```

2023-03-22 12:04 UTC, Pisapou commented on wiki/Beatmapping/Timing/fr.md
> +- *[osu!academy Episode 7-2 - Timing Basics](https://www.youtube.com/watch?v=8nsbrOhLE9w)*, an episode of the [osu!academy](/wiki/Community/Video_series/osu!academy) YouTube series
```suggestion
- *[osu!academy Episode 7-2 - Timing Basics](https://www.youtube.com/watch?v=8nsbrOhLE9w)*, un épisode de la série [osu!academy](/wiki/Community/Video_series/osu!academy) sur YouTube
```

2023-03-22 12:04 UTC, Pisapou commented on wiki/Beatmapping/Timing/fr.md
> +- *[osu!mapping: timing](https://www.youtube.com/watch?v=xauZuMPgiQw)*, an episode of the [osu!mapping](/wiki/Community/Video_series/osu!mapping) YouTube series
```suggestion
- *[osu!mapping: timing](https://www.youtube.com/watch?v=xauZuMPgiQw)*, un épisode de la série [osu!mapping](/wiki/Community/Video_series/osu!mapping) sur YouTube
```

2023-03-22 13:34 UTC, Ganondorf-1 requested changes

2023-03-22 13:34 UTC, Ganondorf-1 commented on wiki/Beatmapping/Timing/fr.md
> +De plus, le timing d'une beatmap contrôle les fonctionnalités suivantes:
```suggestion
De plus, le timing d'une beatmap contrôle les fonctionnalités suivantes :
```

2023-03-22 13:34 UTC, Ganondorf-1 commented on wiki/Beatmapping/Timing/fr.md
> +- Les pistes de batterie ajoutés avec le mod [Nightcore](/wiki/Gameplay/Game_modifier/Nightcore)
```suggestion
- Les pistes de batterie ajoutées avec le mod [Nightcore](/wiki/Gameplay/Game_modifier/Nightcore)
```

2023-03-22 13:34 UTC, Ganondorf-1 commented on wiki/Beatmapping/Timing/fr.md
> +La temps écoulé entre le début du fichier audio et le premier downbeat, aussi appelé "offset", est typiquement la place du premier [point de timing non hérité](/wiki/Client/Beatmap_editor/Timing#poin
```suggestion
La temps écoulé entre le début du fichier audio et le premier downbeat, aussi appelé "offset", est typiquement la place du premier [point de timing non hérité](/wiki/Client/Beatmap_editor/Timing#points-de-timing-non-hérités), le point de départ utilisé par osu! pour calculer la position des autres beats. Un de ces points de timing est souvent suffisant pour les chansons produites digitalement ou peu éditées, n'ayant pas de changement de BPM ni de changement de signature temporelle, ou de réinitialisation du metronome.
```

2023-03-22 13:34 UTC, Ganondorf-1 commented on wiki/Beatmapping/Timing/fr.md
> +Les musique jouées sans métronome peuvent contenir des incohérences de timing, des changements de tempo arbitraires, et des décalages aléatoires de notes, soit en raison d'une expression musicale dyn
```suggestion
Les musiques jouées sans métronome peuvent contenir des incohérences de timing, des changements de tempo arbitraires, et des décalages aléatoires de notes, soit en raison d'une expression musicale dynamique intentionnelle, soit en raison d'une erreur humaine. Ces éléments doivent être pris en compte lors du timing d'une beatmap pour ce genre de musique. Cependant, trouver le timing pour ce genre de musique n'est pas de tout repos — il est donc recommandé de les éviter à moins d'avoir beaucoup d'expérience et de patience.
```

2023-03-22 13:34 UTC, Ganondorf-1 commented on wiki/Beatmapping/Timing/fr.md
> +Pour les musiques à un ou plusieurs BPM jouées avec un métronome, de petites erreurs de timing (par exemple une note jouée quelques secondes d'avance ou de retard) peuvent être ignorées si la beatmap
```suggestion
Pour les musiques à un ou plusieurs BPM jouées avec un métronome, de petites erreurs de timing (par exemple une note jouée quelques secondes en avance ou en retard) peuvent être ignorées si la beatmap reste jouable avec un timing simple. Alternativement, le fichier audio peut être modifié directement avec un logiciel comme [Audacity](https://www.audacityteam.org/) pour quantifier les notes et corriger les erreurs de timing.
```

2023-03-22 13:36 UTC, Ganondorf-1 commented on wiki/Beatmapping/Timing/fr.md
> +Le timing est généralement considéré comme l'une des compétences de mapping les plus difficiles à maîtriser, car il nécessite beaucoup de patience et un bon sens du rythme. Il n'est pas rare de deman
```suggestion
Le timing est généralement considéré comme l'une des compétences de mapping les plus difficiles à maîtriser, car il nécessite beaucoup de patience et un bon sens du rythme. Il n'est pas rare de demander de l'aide à d'autres mappeurs et [moddeurs](/wiki/Modding), soit personnellement, soit dans les canaux publics de [tchat](/wiki/Client/Interface/Chat_console) et les [forums](/wiki/Community/Forum). L'un des fils de discussion consacrés à ce problème, "[Unable to find the BPM/offset of your map ? Post here](https://osu.ppy.sh/community/forums/topics/13795)", contient plus de 5 000 réponses collectées sur une période de 13 ans.
```

2023-03-29 19:30 UTC, Ganondorf-1 commented on wiki/Music_theory/fr.md
> +# Théorie Musicale
```suggestion
# Théorie musicale
```

2023-03-29 19:34 UTC, Ganondorf-1 commented on wiki/Music_theory/fr.md
> +Osu! est un jeu de rythme, les beatmaps sont donc normalement créées pour s'adapter à la musique plutôt qu'au BPM. Dans cette courte rédaction je discuterais de la théorie musicale et comment elle s'
```suggestion
osu! est un jeu de rythme, les beatmaps sont donc normalement créées pour s'adapter à la musique plutôt qu'au BPM. Dans cette courte rédaction, je discuterai de la théorie musicale et comment elle s'applique à une beatmap osu!, ainsi que d'expliquer pourquoi certaines choses sonnent mal (du moins pour moi). En aucun cas, les sujets abordés ne peuvent être considérés comme des «lignes directrices». Pensez que c'est une théorie à la place. La plupart du temps, ils s'appliquent à certaines parties des musiques, mais il existe de nombreuses exceptions. Tout ce que je dirais ici est une opinion personnelle basée sur mes 12 ans d'expérience dans un orchestre harmonique ou pris directement de Wikipédia. On ne peut pas l’appliquer à toutes les formes de musique, en particulier celles d’avant-garde et la plupart des musiques de Touhou (donc, la moitié des musiques d'osu! ?).
```

2023-03-29 19:34 UTC, Ganondorf-1 commented on wiki/Music_theory/fr.md
> +![Théorie Musicale](img/MusicTheory1.png "Théorie Musicale")
```suggestion
![Théorie musicale](img/MusicTheory1.png "Théorie musicale")
```

2023-04-26 20:49 UTC, TicClick approved these changes

2023-04-26 20:51 UTC, merged