[IT] Add `osu! tournament client/osu!tourney/Tournament management commands`
ppy/osu-wiki pull request #9010
Opened 2023-03-23 13:52 UTC by zSmoxKe

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-25 15:11 UTC, Sclafus requested changes

2023-03-25 15:11 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/it.md
> +  - Questa stanza è speciale in quanto non viene chiusa quando tutti i giocatori hanno lasciato la stanza ed è protetta da una password che impedisce ai giocatori di entrare nella stanza stessa.
```suggestion
  - Questa stanza è speciale in quanto non viene chiusa quando tutti i giocatori hanno lasciato la stanza ed è protetta da una password che impedisce ai giocatori di entrarci autonomamente.
```

2023-03-25 15:11 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/it.md
> +- `!mp set <modalità_squadre> [<Condizione_di_vittoria>] [<dimensione>]` - Imposta varie proprietà della stanza.
```suggestion
- `!mp set <modalità_squadre> [<condizione_di_vittoria>] [<dimensione>]` - Imposta varie proprietà della stanza.
```

2023-03-25 15:11 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/it.md
> +  - `Condizione_di_vittoria` - 0: Score, 1: Accuracy, 2: Combo, 3: Score V2
```suggestion
  - `condizione_di_vittoria` - 0: Score, 1: Accuracy, 2: Combo, 3: Score V2
```

2023-03-25 15:11 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/it.md
> +- `!mp move <nomeutente> <slot>` - Sposta un giocatore all'interno della stanza nello slot con indice 1 specificato.
```suggestion
- `!mp move <nomeutente> <slot>` - Sposta un giocatore all'interno della stanza nello slot specificato.
```

2023-03-25 15:11 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/it.md
> +- `!mp clearhost` - Cancella l'host della stanza.
```suggestion
- `!mp clearhost` - Rimuove l'host della stanza.
```

2023-03-25 15:11 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Tournament_management_commands/it.md
> +  - `time` è 30s di default.
```suggestion
  - `tempo` è 30s di default.
```

2023-03-25 21:36 UTC, Sclafus approved these changes

2023-03-26 01:24 UTC, TicClick approved these changes

2023-03-26 01:24 UTC, merged