[IT] Added `osu!_tournament_client/osu!tourney/Troubleshooting`
ppy/osu-wiki pull request #9011
Opened 2023-03-23 15:32 UTC by zSmoxKe

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-25 15:01 UTC, Sclafus requested changes

2023-03-25 15:01 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Troubleshooting/it.md
> +Invia un'e-mail a [tournaments@ppy.sh](mailto:tournaments@ppy.sh) se hai un problema che non è elencato qui. Assicurati di essere descrittivo e di fornire schermate, se possibile.
```suggestion
Invia un'e-mail a [tournaments@ppy.sh](mailto:tournaments@ppy.sh) se hai un problema che non è elencato qui. Assicurati di essere descrittivo e di fornire schermate, se possibile.

```

2023-03-25 21:39 UTC, Sclafus approved these changes

2023-03-26 01:19 UTC, TicClick approved these changes

2023-03-26 01:20 UTC, merged