[IT] Add `osu!_tournament_client/osu!tourney`
ppy/osu-wiki pull request #9026
Opened 2023-03-25 16:02 UTC by zSmoxKe

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-25 21:35 UTC, Sclafus requested changes

2023-03-25 21:35 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/it.md
> +**osu!tourney** è il client multi-spettatore per la versione Stable di osu!, utilizzato per visualizzare e trasmettere in streaming tutti i giocatori in una stanza multigiocatore contemporaneamente.
```suggestion
**osu!tourney** è il client multi-spettatore per la versione stabile di osu!, utilizzato per guardare e trasmettere in streaming tutti i giocatori di una stanza multigiocatore contemporaneamente.
```

2023-03-25 22:09 UTC, Sclafus approved these changes

2023-03-26 01:19 UTC, TicClick approved these changes

2023-03-26 01:21 UTC, merged