[FR] Add `Pattern/osu!mania/Anchor`, `Chord`, `Hold note`
ppy/osu-wiki pull request #9041
Opened 2023-03-27 17:42 UTC by Ganondorf-1

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-27 17:57 UTC, Pisapou requested changes

2023-03-27 17:57 UTC, Pisapou commented on wiki/Beatmap/Pattern/osu!mania/Anchor/fr.md
> +Les **anchors** sont des patterns qui apparaissent le plus souvent lors des [streams](/wiki/Beatmap/Pattern/osu!mania/Stream) ou des [chordjacks](/wiki/Beatmap/Pattern/osu!mania/Jack#chordjack). Il s
```suggestion
Les **anchors** sont des patterns qui apparaissent le plus souvent lors des [streams](/wiki/Beatmap/Pattern/osu!mania/Stream) ou des [chordjacks](/wiki/Beatmap/Pattern/osu!mania/Jack#chordjack). Il s'agit d'une concentration élevée de notes qui apparaissent consécutivement dans une colonne avec le même intervalle de snapping, généralement 1/2. Le nom *anchor* est le mot anglais pour *ancre*. Ce nom vient du mouvement de main créé par le pattern, dans lequel le doigt est essentiellement ancré à une touche spécifique en raison des pressions consécutives et intermittentes.
```

2023-03-27 17:57 UTC, Pisapou commented on wiki/Beatmap/Pattern/osu!mania/Anchor/fr.md
> +![](img/anchor-within-jumpstreams.png "Un anchor durant les jumpstreams, surligné en bleu.")
```suggestion
![](img/anchor-within-jumpstreams.png "Un anchor durant des jumpstreams, surligné en bleu.")
```

2023-03-27 17:57 UTC, Pisapou commented on wiki/Beatmap/Pattern/osu!mania/Anchor/fr.md
> +![](img/anchor-within-chordjacks.png "Un anchor durant les chordjacks, surligné en bleu.")
```suggestion
![](img/anchor-within-chordjacks.png "Un anchor durant des chordjacks, surligné en bleu.")
```

2023-03-27 17:57 UTC, Pisapou commented on wiki/Beatmap/Pattern/osu!mania/Chord/fr.md
> +Ce terme vient de *Dance Dance Revolution* et autres jeux similaires où effectuer les doubles nécessite que le joueur saute littéralement entre les flèches sur le tapis de danse.
```suggestion
Ce terme vient de *Dance Dance Revolution* et d'autres jeux similaires dans lesquels les doubles nécessitent que le joueur saute littéralement entre les flèches sur le tapis de danse.
```

2023-03-27 17:57 UTC, Pisapou commented on wiki/Beatmap/Pattern/osu!mania/Hold_note/fr.md
> +Les **hold notes** (aussi connues sous le nom de **long notes**) sont des notes qui doivent être tenues puis relâchées. Elles sont souvent appelés "noodles" ou "LNs" et sont utilisées pour représente
```suggestion
Les **hold notes** (aussi connues sous le nom de **long notes**) sont des notes qu'il faut maintenir puis relâcher. Elles sont souvent appelés "noodles" ou "LNs" (pour Long Notes) et sont utilisées pour représenter des sons prolongés dans la musique.
```

2023-03-29 19:18 UTC, TicClick approved these changes

2023-03-29 19:20 UTC, merged