[FR] Add  `Client/Release stream/Lazer/Feature comparison`
ppy/osu-wiki pull request #9050
Opened 2023-03-28 15:05 UTC by Pisapou

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-03-28 18:51 UTC, Ganondorf-1 requested changes

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +#### Les ajustements du débit audio affectent les fenêtres de jugement dans osu!mania
```suggestion
#### Les ajustements de la vitesse des beatmaps affectent les fenêtres de jugement dans osu!mania
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Sur stable, osu!mania annule les modifications apportées aux fenêtres de jugement par l'utilisation du mod DT/HT.
```suggestion
Sur stable, osu!mania annule les modifications apportées aux fenêtres de jugement par l'utilisation des mods DT/HT.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +| Rupture de la rétrocompatibilité | Oui |
```suggestion
| Casse la rétrocompatibilité | Oui |
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +| Support du retour au mod classique | Non |
```suggestion
| Effet annulé par le mod Classic | Non |
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +| Rupture de la rétrocompatibilité | Non |
```suggestion
| Casse la rétrocompatibilité | Non |
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +| Support du retour au mod classique | Non |
```suggestion
| Effet annulé par le mod Classic | Non |
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +La notation sur lazer a été simplifiée, le principal avantage étant qu'il n'est pas nécessaire de faire un replay pour recalculer. Deux systèmes interchangeables ont été ajoutés : *standardisé* et *c
```suggestion
Le score sur lazer a été simplifié, le principal avantage étant qu'il n'est pas nécessaire de faire un replay pour le recalculer. Deux systèmes interchangeables ont été ajoutés : *standardisé* et *classique*. Le score standardisé limite le score à un maximum de 1 000 000 de points + des bonus et les multiplicateurs de score, tandis que le score classique est similaire au score standardisé, mais s'échelonne quadratiquement en fonction du nombre d'objets dans une beatmap. Ces options peuvent être sélectionnées dans les paramètres, et tous les endroits où les scores sont affichés dans le jeu sont modifiés en conséquence.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +### Scores, points de performance et classements
```suggestion
### Score, points de performance et classements
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Il y a également des différences dans le score de chaque objet touché et de chaque jugement l'un par rapport à l'autre.
```suggestion
Il y a également des différences dans le score de chaque objet et de chaque jugement l'un par rapport à l'autre.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Les fonctionnalités qui dépendent du score, comme le [classement par score](/wiki/Ranking#classement-par-score) et les [niveaux](/wiki/Gameplay/Score/Total_score#niveau), doivent faire l'objet de dis
```suggestion
Les fonctionnalités qui dépendent du score, comme le [classement par score](/wiki/Ranking#classement-par-score) et les [niveaux](/wiki/Gameplay/Score/Total_score#niveau), doivent faire l'objet de discussions plus approfondies sur la façon dont elles seront affectées.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Les médailles ne sont pas attribuées. Cette fonctionnalité sera activée après la mise en œuvre des mesures anti-triche et nécessitera des réfléxions plus approfondi en ce qui concerne la modification
```suggestion
Les médailles ne sont pas attribuées. Cette fonctionnalité sera activée après la mise en œuvre des mesures anti-triche et nécessitera des réflexions plus approfondies en ce qui concerne la modification de la difficulté de certaines médailles en raison d'autres changements dans le gameplay.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +### Multijoueurs
```suggestion
### Multijoueur
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Cette implémentation est prévu, mais aucun travail n'a encore été entamé à ce sujet.
```suggestion
Cette implémentation est prévue, mais aucun travail n'a encore été entamé à ce sujet.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Sur stable, les backgrounds de beatmap et les storyboards remplissent la hauteur de l'écran. Sur lazer, les backgrounds remplissent la largeur de l'écran, tandis que les storyboards remplissent toujo
```suggestion
Sur stable, les arrière-plans et storyboards des beatmaps remplissent la hauteur de l'écran. Sur lazer, les arrière-plans remplissent la largeur de l'écran, tandis que les storyboards remplissent toujours la hauteur.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Cette différence entraîne des incohérences dans les modes de remplissage lorsqu'un storyboard est superposé à un background de beatmap existant.
```suggestion
Cette différence entraîne des incohérences dans les modes de remplissage lorsqu'un storyboard est superposé à un arrière-plan de beatmap existant.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +Il s'agit de fonctionnalités qui devraient revenir à un moment donné, mais qui ne l'ont pas fait en raison de leur faible priorité.
```suggestion
Il s'agit de fonctionnalités qui devraient revenir à un moment donné, mais qui ne le sont pas en raison de leur faible priorité.
```

2023-03-28 18:51 UTC, Ganondorf-1 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +- Composantes non-skinnable
```suggestion
- Composantes non-skinnables
```

2023-03-29 15:38 UTC, Pisapou commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +| Effet annulé par le mod Classic| Non |
```suggestion
| Effet annulé par le mod Classic | Non |
```

2023-04-09 11:16 UTC, Pisapou commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +  - Rewind F2
aucun idée, et c'est pour ça que je l'ai laissé en anglais :x

2023-04-16 09:33 UTC, Walavouchey commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +  - Rewind F2
"rewind f2" means you can press shift + f2 to select the previous random selection

2023-04-16 10:02 UTC, Biokax commented on wiki/Client/Release_stream/Lazer/Feature_comparison/fr.md
> +  - Rewind F2
```suggestion
  - Retour en arrière pour la touche F2
```
@Pisapou je propose de le traduire de cette manière

2023-05-04 20:56 UTC, Walavouchey approved these changes

2023-05-04 20:59 UTC, merged