[ZH] Update `Account restrictions`
ppy/osu-wiki pull request #9075
Opened 2023-04-04 03:09 UTC by FlyingFish23

## Self-check

- [x ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-05 03:23 UTC, Sunnyboy971 approved these changes

2023-04-06 12:38 UTC, TicClick requested changes
line 50 should also be edited according to https://osu.wiki/status/diff-zh-wiki-Help_centre-Account_restrictions

2023-04-28 11:56 UTC, YumeMuzi commented
there are some lines you missed, see: #9248

2023-05-04 21:16 UTC, Walavouchey commented
superseded by https://github.com/ppy/osu-wiki/pull/9248

2023-05-04 21:16 UTC, closed without merging