[ES] Add `Announcement_messages`
ppy/osu-wiki pull request #9089
Opened 2023-04-06 18:31 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-08 08:07 UTC, agatemosu requested changes

2023-04-08 08:07 UTC, agatemosu commented on wiki/Announcement_messages/es.md
> +- Tu nombre de usuario de osu!
```suggestion
- Su nombre de usuario de osu!
```

2023-04-08 08:07 UTC, agatemosu commented on wiki/Announcement_messages/es.md
> +Para enviar y responder mensajes de anuncios a través del sitio web, debes ser miembro del [Global Moderation Team](/wiki/People/Global_Moderation_Team), el [Nomination Assessment Team](/wiki/People/
```suggestion
Para enviar y responder mensajes de anuncios a través del sitio web, debe ser miembro del [Global Moderation Team](/wiki/People/Global_Moderation_Team), el [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team), o del [grupo de usuarios](/wiki/People/User_group) de anuncios. Sin embargo, solo los miembros del grupo de usuarios de anuncios pueden enviar anuncios de chat a través de la [osu! API v2](https://docs.ppy.sh).
```

2023-04-08 08:07 UTC, agatemosu commented on wiki/Announcement_messages/es.md
> +Para enviar un anuncio de chat, abra la [página de chat](https://osu.ppy.sh/community/chat) desde sus notificaciones de chat y haga clic en el botón `create announcement`. Ingrese el nombre del canal
```suggestion
Para enviar un anuncio de chat, abra la [página de chat](https://osu.ppy.sh/community/chat) desde sus notificaciones de chat y haga clic en el botón `crear anuncio`. Ingrese el nombre del canal, descripción[^note-desc], lista de destinatarios, y su mensaje. Finalmente, haga clic en el botón `crear` para enviar el anuncio.
```

2023-04-08 08:07 UTC, agatemosu commented on wiki/Announcement_messages/es.md
> +- El ID del grupo de usuarios de anuncios es 47, no tiene una insignia de grupo ni un color exclusivo, y su lista de usuarios es privada.
```suggestion
- La ID del grupo de usuarios de anuncios es 47, no tiene una insignia de grupo ni un color exclusivo, y su lista de usuarios es privada.
```

2023-04-08 08:10 UTC, agatemosu commented on wiki/Announcement_messages/es.md
> +---
```suggestion
---
tags:
  - announce
  - announce usergroup
  - announce user group
  - anuncio
  - grupo de usuarios de anuncios
---
```

2023-04-08 08:10 UTC, agatemosu commented on wiki/Announcement_messages/es.md
> +---
```suggestion
  - announce user group
  - anuncio
  - grupo de usuarios de anuncios
---
```

2023-05-06 21:18 UTC, TPGPL approved these changes

2023-05-06 21:19 UTC, merged