[ES] Correct terminology in `Beatmap/Category`
ppy/osu-wiki pull request #9093
Opened 2023-04-06 18:39 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-08 07:59 UTC, agatemosu requested changes
"beatmap" does not translate

2023-04-08 08:16 UTC, UnknownOsu commented
Why? The vast majority refer to "beatmaps" as "maps", as far as Spanish is concerned.

2023-04-22 23:58 UTC, TPGPL submitted a review, later dismissed

2023-04-23 00:02 UTC, TPGPL approved these changes

2023-04-23 00:04 UTC, merged