[ES] Add `Beatmap/Genre_and_language`
ppy/osu-wiki pull request #9094
Opened 2023-04-06 18:41 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-08 08:41 UTC, agatemosu requested changes

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +[Mapas](/wiki/Beatmap) enviados al sitio web tienen campos de **género** e **idioma** para ayudar a clasificar las canciones. Se consideran parte de los [metadatos](/wiki/Client/Beatmap_editor/Song_S
```suggestion
Los [beatmaps](/wiki/Beatmap) enviados al sitio web tienen campos de **género** e **idioma** para ayudar a clasificar las canciones. Se consideran parte de los [metadatos](/wiki/Client/Beatmap_editor/Song_Setup#song-and-map-metadata) de un beatmap.
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +## Lista de mapas
```suggestion
## Listado de beatmaps
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +![Los filtros disponibles en la lista de mapas](img/beatmap-listing-ES.png?1)
```suggestion
![Los filtros disponibles en el listado de beatmaps](img/beatmap-listing-ES.png)
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +La [lista de mapas](https://osu.ppy.sh/beatmapsets) tiene filtros disponibles para el género y el idioma en el menú desplegable `Más opciones de búsqueda`.
```suggestion
El [listado de beatmaps](https://osu.ppy.sh/beatmapsets) tiene filtros disponibles para el género y el idioma en el menú desplegable `Más opciones de búsqueda`.
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +## Cambiar el género y el idioma de un mapa
```suggestion
## Cambiar el género y el idioma de un beatmap
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +El género y el idioma se pueden cambiar en el sitio web haciendo clic en el ícono del lápiz al pasar el mouse sobre los detalles de un mapa. La capacidad para hacerlo está determinada por el [grupo d
```suggestion
El género y el idioma se pueden cambiar en el sitio web haciendo clic en el ícono del lápiz al pasar el ratón sobre los detalles de un beatmap. La capacidad para hacerlo está determinada por el [grupo del usuarios](/wiki/People/osu!_team#user-groups) y la [categoría](/wiki/Beatmap/Category#present-categories) del beatmap:
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +- Los propietarios de los conjuntos de mapas están permitidos cuando el mapa está en la categoría [WIP](/wiki/Beatmap/Category#work-in-progress-and-pending), [Pendiente](/wiki/Beatmap/Category#work-i
```suggestion
- Los propietarios de los conjuntos de mapas están permitidos cuando el mapa está en la categoría [Trabajo en progreso](/wiki/Beatmap/Category#work-in-progress-and-pending), [Pendiente](/wiki/Beatmap/Category#work-in-progress-and-pending), o [Abandonado](/wiki/Beatmap/Category#graveyard), y no tiene ninguna [nominación](/wiki/Beatmap_ranking_procedure#nominations).
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +- Los [Beatmap Nominators](/wiki/People/Beatmap_Nominators) están permitidos cuando el mapa está en la categoría [Calificado](/wiki/Beatmap/Category#qualified), WIP, o Pendiente.
```suggestion
- Los [Beatmap Nominators](/wiki/People/Beatmap_Nominators) están permitidos cuando el beatmap está en la categoría [Calificado](/wiki/Beatmap/Category#calificado), Trabajo en progreso, o Pendiente.
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +- Los miembros del [Equipo de Project Loved](/wiki/People/Project_Loved_Team) están permitidos cuando el mapa está en la categoría [Amado](/wiki/Beatmap/Category#loved).
```suggestion
- Los miembros del [Project Loved Team](/wiki/People/Project_Loved_Team) están permitidos cuando el beatmap está en la categoría [Amado](/wiki/Beatmap/Category#amado).
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +- Los miembros del [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) y [Global Moderation Team](/wiki/People/Global_Moderation_Team) están permitidos en todas las categorías.
```suggestion
- Los miembros del [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) y del [Global Moderation Team](/wiki/People/Global_Moderation_Team) están permitidos en todas las categorías.
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +Un mapa no puede ser [nominado](/wiki/Beatmap_ranking_procedure#nominations) si tiene el género o idioma `No especificado`.
```suggestion
Un beatmap no puede ser [nominado](/wiki/Beatmap_ranking_procedure#nominations) si tiene el género o idioma `No especificado`.
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +| Videojuego | Hecha para o popularizada por un videojuego. Esto también se usa para arreglos y remixes de esas canciones. |
```suggestion
| Videojuego | Hecha para o popularizada por un videojuego. Esto también se usa para arreglos y remezclas de esas canciones. |
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +| Rock | Centrándose principalmente en guitarras, batería y bajo, típicamente "construido sobre una base de ritmos simples no sincopados" y caracterizado por "actuaciones en vivo y un enfoque en tema
```suggestion
| Rock | Centrándose principalmente en guitarras, batería y bajo, típicamente «construido sobre una base de ritmos simples no sincopados» y caracterizado por «actuaciones en vivo y un enfoque en temas serios y progresivos». ([*Rock* en Wikipedia](https://es.wikipedia.org/wiki/Rock#Características)). |
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +| Novedad | Cómica o inusual. En osu!, esta categoría incluye principalmente canciones como YouTube Poops, Niconico MADs y música meme. |
```suggestion
| Novedad | Cómica o inusual. En osu!, esta categoría incluye principalmente canciones como YouTube Poops, Niconico MAD y música meme. |
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +| Hip Hop | "Música rítmica estilizada que comúnmente acompaña al rap", a veces "muestreo de ritmos o líneas de bajo de discos". ([*Música Hip hop* en Wikipedia](https://es.wikipedia.org/wiki/Hip_hop
```suggestion
| Hip Hop | «Música rítmica estilizada que comúnmente acompaña al rap», a veces «muestreo de ritmos o líneas de bajo de discos». ([*Hip hop* en Wikipedia](https://es.wikipedia.org/wiki/Hip_hop)). |
```

2023-04-08 08:41 UTC, agatemosu commented on wiki/Beatmap/Genre_and_language/es.md
> +- Otro (incluyendo canciones con múltiples idiomas destacados)
```suggestion
- Otro (incluyendo canciones con múltiples idiomas prominentes)
```

2023-04-22 23:48 UTC, TPGPL submitted a review, later dismissed

2023-04-22 23:55 UTC, TPGPL approved these changes

2023-04-22 23:57 UTC, merged