[ES] Add `Beatmap/Lead-in_time`
ppy/osu-wiki pull request #9096
Opened 2023-04-06 18:45 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-08 10:18 UTC, agatemosu requested changes

2023-04-08 10:18 UTC, agatemosu commented on wiki/Beatmap/Lead-in_time/es.md
> +La **entrada** es la cantidad de tiempo que da el juego para que los jugadores reaccionen antes del primer [objeto de golpeo](/wiki/Gameplay/Hit_object) de un [mapa](/wiki/Beatmap). Este puede ser pe
```suggestion
La **entrada** es la cantidad de tiempo que da el juego para que los jugadores reaccionen antes del primer [objeto](/wiki/Gameplay/Hit_object) de un [beatmap](/wiki/Beatmap). Este puede ser personalizado por los [mappers](/wiki/Beatmapping) editando el campo `AudioLeadIn` en el [archivo `.osu` ](/wiki/Client/File_formats/Osu_(file_format)) en una [dificultad del beatmap](/wiki/Beatmap/Difficulty), que contiene la duración de la entrada en milisegundos.
```

2023-04-08 10:18 UTC, agatemosu commented on wiki/Beatmap/Lead-in_time/es.md
> +El tiempo de entrada mínimo utilizado automáticamente por osu! es de 1,8 segundos. Con la [velocidad de aproximación](/wiki/Beatmap/Approach_rate) más baja de 0, esta es la cantidad de tiempo que un
```suggestion
El tiempo de entrada mínimo utilizado automáticamente por osu! es de 1.8 segundos. Con la [velocidad de aproximación](/wiki/Beatmap/Approach_rate) más baja de 0, esta es la cantidad de tiempo que un objeto es visible antes de que necesite ser golpeado. Cualquier [storyboard](/wiki/Storyboard) o video que se reproduzca antes del primer objeto puede extender el tiempo de entrada.
```

2023-04-08 10:18 UTC, agatemosu commented on wiki/Beatmap/Lead-in_time/es.md
> +Los [criterios de clasificación](/wiki/Ranking_Criteria#general) requieren el uso de una entrada personalizada en caso de que el mapa contenga una advertencia de epilepsia que cubra los primeros obje
```suggestion
El uso de una entrada personalizada es requerida para los [criterios de clasificación](/wiki/Ranking_Criteria#general) en caso de que el beatmap contenga un aviso de epilepsia que cubra los primeros objetos.
```

2023-04-22 23:38 UTC, TPGPL approved these changes

2023-04-22 23:43 UTC, TPGPL approved these changes

2023-04-22 23:47 UTC, merged