[ES] Translation update `People/osu!_team`
ppy/osu-wiki pull request #9111
Opened 2023-04-06 19:10 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-08 08:17 UTC, agatemosu requested changes

2023-04-08 08:17 UTC, agatemosu commented on wiki/People/osu!_team/es.md
> +| ::{ flag=US }:: [HappyStick](https://osu.ppy.sh/users/256802) | Anfitrión del osu! Coffee Hour, transmisor de la World Cup, organizador de torneos |
```suggestion
| ::{ flag=US }:: [HappyStick](https://osu.ppy.sh/users/256802) | Anfitrión de la osu! Coffee Hour, transmisor de la World Cup, organizador de torneos |
```

Hour es hora, hora está en femenino

2023-04-08 09:14 UTC, agatemosu requested changes
Change in line 16 and 18 "El Equipo" and "equipo de osu!" by "osu! team"

2023-05-10 18:13 UTC, TicClick submitted a review, later dismissed

2023-05-10 18:19 UTC, TicClick approved these changes

2023-05-10 18:19 UTC, merged