[ES] Word correction `Rules`
ppy/osu-wiki pull request #9117
Opened 2023-04-08 17:43 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-08 19:00 UTC, agatemosu requested changes

2023-04-08 19:00 UTC, agatemosu commented on wiki/Rules/es.md
> +Estas reglas aplican estrictamente a los mapas que sean enviados a través del [Sistema de Envío de Mapas](/wiki/Beatmapping/Beatmap_submission) dentro del juego. Estos hilos/discusiones son creados a
```suggestion
Estas reglas aplican estrictamente a los beatmaps que sean enviados a través del [Sistema de Envío de Beatmaps](/wiki/Beatmapping/Beatmap_submission) dentro del juego. Estos hilos/discusiones son creados a través del cliente de osu! cuando un mapa es enviado a través del [editor](/wiki/Client/Beatmap_editor).
```

2023-04-08 19:00 UTC, agatemosu commented on wiki/Rules/es.md
> +2. **Mantén el tema en las [discusiones de mapas](/wiki/Beatmap_discussion).** Estos hilos/discusiones son acerca del mapa en cuestión y de nada más. Si tienes algún problema con algo que no esté dir
```suggestion
2. **Mantén el tema en las [discusiones de beatmaps](/wiki/Beatmap_discussion).** Estos hilos/discusiones son acerca del beatmap en cuestión y de nada más. Si tienes algún problema con algo que no esté directamente relacionado con el beatmap, publícalo en el foro apropiado.
```

2023-04-08 19:00 UTC, agatemosu commented on wiki/Rules/es.md
> +- La eliminación de cualquier contenido infractor de tu página de usuario, perfil o mapas subidos.
```suggestion
- La eliminación de cualquier contenido infractor de tu página de usuario, perfil o beatmaps subidos.
```

2023-04-08 19:00 UTC, agatemosu commented on wiki/Rules/es.md
> +1. **Asegúrate de que tienes permiso de usar cualquier tipo de contenido involucrado en tu mapa.** Esto incluye canciones, vídeos, sonidos de golpeo, arte gráfico y cualquier otro contenido que no se
```suggestion
1. **Asegúrate de que tienes permiso de usar cualquier tipo de contenido involucrado en tu beatmap.** Esto incluye canciones, vídeos, hitsounds, arte gráfico y cualquier otro contenido que no sea de tu propia creación. Si no estás seguro de dónde encontrar contenido que sea de uso libre, dale un vistazo a nuestra librería en crecimiento de pistas de [Artistas Destacados](https://osu.ppy.sh/beatmaps/artists/) 100% licenciadas para su uso en osu! y a las [Directrices del Uso de Contenido](Content_Usage_Guidelines) para más información.
```

2023-04-22 23:21 UTC, TPGPL approved these changes

2023-04-22 23:21 UTC, merged