[ES] Translation update `Help_centre/Account_restrictions`
ppy/osu-wiki pull request #9122
Opened 2023-04-08 22:13 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-09 11:13 UTC, agatemosu requested changes

2023-04-09 11:13 UTC, agatemosu commented on wiki/Help_centre/Account_restrictions/es.md
> +Cuando una cuenta es restringida, es incapaz de interactuar con la comunidad hasta que la restricción sea levantada. Los jugadores restringidos pueden seguir jugando el juego, descargar mapas y subir
```suggestion
Cuando una cuenta es restringida, es incapaz de interactuar con la comunidad hasta que la restricción sea levantada. Los jugadores restringidos pueden seguir jugando el juego, descargar beatmaps y subir puntuaciones, pero su perfil será invisible para los demás.
```

2023-04-09 19:55 UTC, agatemosu requested changes

2023-04-09 19:55 UTC, agatemosu commented on wiki/Help_centre/Account_restrictions/es.md
> +Si su cuenta original no está restringida, puede iniciar sesión con ella y seguir jugando normalmente, pero asegúrate de no iniciar sesión con tus multicuentas en adelante, ya que hacerlo puede dar l
```suggestion
Si su cuenta original no está restringida, puede iniciar sesión con ella y seguir jugando normalmente, pero asegúrese de no iniciar sesión con sus multicuentas en adelante, ya que hacerlo puede dar lugar a un castigo mayor.
```

2023-04-09 19:55 UTC, agatemosu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **¡Sigue disfrutando del juego!** Mientras tu cuenta está restringida y en cooldown, eres más que bienvenido a seguir jugando el juego (¡siempre y cuando juegues en tu cuenta original!). Las puntua
```suggestion
- **¡Sigue disfrutando del juego!** Mientras su cuenta está restringida y en cooldown, eres más que bienvenido a seguir jugando el juego (¡siempre y cuando juegues en tu cuenta original!). Las puntuaciones que consigas mientras estás restringido serán subidas, a no ser que la cuenta sea revertida, ellas seguirán después de que la restricción sea levantada.
```

2023-04-09 19:55 UTC, agatemosu commented on wiki/Help_centre/Account_restrictions/es.md
> +Puedes apelar enviando un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh) incluyendo el nombre de su cuenta. Asegúrese de enviar el correo desde la dirección de correo asociada a su cuenta. Despué
```suggestion
Puedes apelar enviando un correo a [accounts@ppy.sh](mailto:accounts@ppy.sh) incluyendo el nombre de su cuenta. Asegúrese de enviar el correo desde la dirección de correo asociada a su cuenta. Después de que envíe su apelación, espere una respuesta en un plazo de una semana. Si no has recibido una para ese entonces, por favor contáctenos vía correo o twitter, hay una posibilidad de que no la hayamos recibido
```

2023-04-09 19:55 UTC, agatemosu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **Cómo conseguiste los medios para hacerlo.** Esto aplica principalmente al hacer trampas - queremos saber dónde conseguiste la herramienta que usaste, cómo la encontraste, y si sigue o no presente
```suggestion
- **Cómo conseguiste los medios para hacerlo.** Esto aplica principalmente al hacer trampas, queremos saber dónde conseguiste la herramienta que usaste, cómo la encontraste, y si sigue o no presente en su computadora.
```

2023-04-09 19:58 UTC, agatemosu requested changes

2023-04-09 19:58 UTC, agatemosu commented on wiki/Help_centre/Account_restrictions/es.md
> +- **Esperar 24 horas.** Algunas restricciones son resultado de procesos automatizados. Como revisamos cada nueva restricción diariamente, por favor espere 24 horas - si ha sido restringido erróneamen
```suggestion
- **Esperar 24 horas.** Algunas restricciones son resultado de procesos automatizados. Como revisamos cada nueva restricción diariamente, por favor espere 24 horas, si ha sido restringido erróneamente, probablemente la restricción será levantada en ese tiempo.
```

2023-04-09 19:58 UTC, agatemosu commented on wiki/Help_centre/Account_restrictions/es.md
> +| Razón de restricción | Duración del Tiempo de Espera | Notas de apelación |
```suggestion
| Razón de restricción | Duración del tiempo de espera | Notas de apelación |
```

2023-05-06 21:41 UTC, TPGPL submitted a review, later dismissed
translation is outdated, please apply https://github.com/ppy/osu-wiki/pull/9200

2023-05-10 17:34 UTC, merged