[FR] Update `BBCode`
ppy/osu-wiki pull request #9136
Opened 2023-04-11 13:11 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- (TicClick) skipped: Add #9164 changes
- (TicClick) skipped: Add #9263 changes
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-14 12:35 UTC, Pisapou requested changes

2023-04-14 12:35 UTC, Pisapou commented on wiki/BBCode/fr.md
> +La balise `[c]` permet de mettre en évidence du texte en ligne dans une police monospace. Sur le site d'osu!, le texte sera formaté avec une boîte grise autour de lui. contrairement aux [blocs de cod
```suggestion
La balise `[c]` permet de mettre en évidence du texte en ligne dans une police monospace. Sur le site d'osu!, le texte sera formaté avec une boîte grise autour de lui. Contrairement aux [blocs de codes](#bloc-de-codes), la balise ne peut être placée que sur une seule ligne.
```

2023-04-14 12:35 UTC, Pisapou commented on wiki/BBCode/fr.md
> +Dans les forums d'osu!, il est utilisé afin de pouvoir mettre des accents, par exemple sur les raccourcis clavier ou les descriptions de boutons.
```suggestion
Dans les forums d'osu!, il est utilisé afin de mettre en avant, par exemple des raccourcis clavier ou des descriptions de boutons.
```

2023-04-30 12:00 UTC, The-Last-Cookie commented on wiki/BBCode/fr.md
> +
Changes from #9263:
```suggestion

Toolbar button: ![Imagemap button](img/imagemap.png "Imagemap")

```

2023-05-03 10:58 UTC, The-Last-Cookie commented
If you want to add a localised version for `editor.jpg`, keep in mind translating the new `Help` string in the toolbar via Crowdin.

2023-06-09 18:46 UTC, TicClick approved these changes
marking as outdated due to https://github.com/ppy/osu-wiki/pull/9164 and merging as-is -- it's been well over a month since the PR was posted

2023-06-09 18:49 UTC, merged