[FR] Update `group-info`
ppy/osu-wiki pull request #9137
Opened 2023-04-11 14:30 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-14 12:36 UTC, Pisapou requested changes

2023-04-14 12:36 UTC, Pisapou commented on meta/group-info/fr.yaml
> +    skinning: modération de la communauté de skinning
```suggestion
    skinning: modération de la communauté skinning
```

2023-04-16 10:23 UTC, Ganondorf-1 commented on meta/group-info/fr.yaml
> +    evaluation: evaluation
```suggestion
    evaluation: évaluation
```

2023-04-18 21:38 UTC, TicClick approved these changes

2023-04-18 21:40 UTC, merged