Italian translation
ppy/osu-wiki pull request #9138
Opened 2023-04-11 15:48 UTC by MisakiSakura3

Italian translation of the file Bot_account

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-15 16:47 UTC, Sclafus requested changes

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +Un **account bot** è un tipo speciale di osu! account gestito da un servizio automatizzato invece che da una persona reale. Sul sito Web hanno un badge di gruppo bianco con l'etichetta "BOT" ed è vis
```suggestion
Un **account bot** è un account speciale che viene gestito da un servizio automatizzato invece che da una persona reale. Sul sito Web hanno un badge bianco con l'etichetta "BOT" ed è visibile solo la sezione "io!" del loro profilo. Gli account bot sono più comunemente usati per ospitare "chat bot" che offrono varie funzionalità alla community attraverso lobby [multiplayer](/wiki/Client/Interface/Multiplayer) o messaggi privati.
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +Gli account bot possono essere creati solo tramite un [processo di richiesta](#creating-a-bot-account). Un tentativo di creare un account bot registrandosi normalmente è considerato multi-account ed
```suggestion
Gli account bot possono essere creati esclusivamente su [richiesta](#creazione-di-un-account-bot). Un tentativo di creare un account bot registrandosi normalmente è considerato multi-account ed è contrario alle [regole della community](/wiki/Rules#regole-della-community).
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +La differenza principale tra gli account personali e gli account bot è nei limiti di velocità che si applicano a loro quando si inviano messaggi [chat](/wiki/Client/Interface/Chat_console). Gli accou
```suggestion
La differenza principale tra gli account personali e gli account bot è nei limiti di velocità che si applicano a loro quando si inviano messaggi in [chat](/wiki/Client/Interface/Chat_console). Gli account bot hanno limiti meno stringenti per consentire ai loro servizi di interagire con più utenti senza il rischio che l'account venga [silenziato](/wiki/Silence):
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +Questi limiti di velocità si applicano solo ai messaggi privati, `#multiplayer` e `#spectator`. Gli account bot non sono autorizzati a inviare messaggi in altri canali, né messaggi privati non richie
```suggestion
Questi limiti si applicano solo ai messaggi privati, `#multiplayer` e `#spectator`. Gli account bot non sono autorizzati a inviare messaggi in altri canali, né messaggi privati non richiesti.
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +Se stai cercando di avviare un bot di chat, inizia con l'eseguirlo sul tuo osu! conto e assicurati di rispettare i limiti di tariffa del conto personale sopra elencati. Man mano che il tuo servizio c
```suggestion
Se stai cercando di avviare un chat bot, puoi iniziare usando il tuo account di osu!, assicurandoti di rispettare i limiti del account personale sopra elencati. Man mano che il tuo servizio cresce, potrebbe esserci l'opportunità di richiedere un account bot al team di supporto dell'account.
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +- Il bot viene utilizzato da almeno 50 utenti unici ogni mese
```suggestion
- Il bot viene utilizzato da almeno 50 utenti univoci ogni mese
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +- Il bot rispetta i limiti tariffari del conto personale
```suggestion
- Il bot rispetta i limiti del account personale
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +- Il bot è utile a un vasto pubblico nell'osu! Comunità
```suggestion
- Il bot è utile ad un vasto pubblico nella community di osu!
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +Invia un'e-mail a [accounts@ppy.sh](mailto:accounts@ppy.sh) con oggetto `Richiesta account bot`. Questo deve essere inviato dall'indirizzo email allegato al tuo osu! account.
```suggestion
Invia un'e-mail a [accounts@ppy.sh](mailto:accounts@ppy.sh) con oggetto `Bot Account Request`. La mail deve essere    inviato dall'indirizzo email collegato al tuo account di osu!.
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +- Il tuo osu! nome utente (dove hai eseguito il bot)
```suggestion
- Il tuo  nome utente su osu! (dove hai eseguito il bot)
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +- Un collegamento al codice sorgente e alla documentazione
```suggestion
- Un link al codice sorgente e alla documentazione
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +Il [team di assistenza account](/wiki/People/Account_support_team) esaminerà la tua richiesta. Se la tua richiesta viene respinta, ti faranno sapere il motivo. Se la tua richiesta viene approvata, cr
```suggestion
Il [team di assistenza account](/wiki/People/Account_support_team) esaminerà la tua richiesta. Se la tua richiesta viene respinta, ti faranno sapere il motivo. Se la tua richiesta viene approvata, creeranno l'account bot per te e ti forniranno istruzioni su come usarlo.
```

2023-04-15 16:47 UTC, Sclafus commented on wiki/Bot_account/it.md
> +- Alcuni account personali sono nel gruppo dei bot di chat perché i proprietari non volevano o non richiedevano di avere un account bot separato per il loro servizio, ad esempio ::{ flag=DE }:: [Till
```suggestion
- Alcuni account personali sono nel gruppo dei bot di chat perché i proprietari non volevano o non richiedevano di avere un account bot separato per il loro servizio, ad esempio ::{ flag=DE }:: [Tillerino](https://osu.ppy.sh/users/2070907) e ::{ flag=FR }:: [ThePooN](https://osu.ppy.sh/users/718454). Questa soluzione non è più offerta ai nuovi bot che entrano nel gruppo. Gli verrà sempre assegnato un account esclusivo.
```

2023-04-22 13:10 UTC, TicClick approved these changes

2023-04-22 13:10 UTC, merged