[ES] Translation update `Beatmap/Difficulty`
ppy/osu-wiki pull request #9140
Opened 2023-04-11 18:37 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-12 15:30 UTC, agatemosu requested changes

2023-04-12 15:30 UTC, agatemosu commented on wiki/Beatmap/Difficulty/es.md
> +*No debe confundirse con [Mapa](/wiki/Beatmap).*
```suggestion
*No debe confundirse con [Beatmap](/wiki/Beatmap).*
```

2023-04-12 15:30 UTC, agatemosu commented on wiki/Beatmap/Difficulty/es.md
>  ---
```suggestion
  - dificultades
  - nombre de la dificultad
  - calificación por estrellas
  - estrellas
---
```

2023-04-22 23:31 UTC, TPGPL approved these changes

2023-04-22 23:31 UTC, merged