[ES] Clean up `Slider` and `Beatmap`
ppy/osu-wiki pull request #9144
Opened 2023-04-12 19:44 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-18 21:34 UTC, TicClick requested changes

2023-04-18 21:34 UTC, TicClick commented on wiki/Gameplay/Hit_object/Slider/es.md
> -no_native_review: true
this was set on your own translation, I think it should take another user's review to get it removed

2023-04-20 20:32 UTC, MChecaH requested changes

2023-04-20 20:32 UTC, MChecaH commented on wiki/Gameplay/Hit_object/Slider/es.md
> +Un *slider* es un [objeto](/wiki/Gameplay/Hit_object) en [osu!](/wiki/Game_mode/osu!), que consta de un sliderhead, un sliderbody y un slidertail. Una vez que el círculo de aproximación alcanza el bo
```suggestion
Un *slider* es un [objeto](/wiki/Gameplay/Hit_object) en [osu!](/wiki/Game_mode/osu!), que consta de un sliderhead, un sliderbody y un slidertail. Una vez que el círculo de aproximación alcanza el borde del sliderhead, como con los [círclulos](/wiki/Gameplay/Hit_object/Hit_circle), el jugador debe hacer clic/tocar el comienzo del slider y luego, manteniendo presionado el botón, seguir una bola en movimiento (llamada bola del slider) a lo largo de la pista hasta que se alcance el slidertail. Si hay una flecha inversa, el jugador debe seguir la bola del slider hacia atrás por el mismo camino. Los sliders con flechas invertidas se denominan [sliders inversos](/wiki/Gameplay/Hit_object/Slider/Reverse_slider). La velocidad de un slider se define por su [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity) y el multiplicador de velocidad del slider de la sección de tiempo actual.
```

It's important keeping the gerund as you're following the ball *while* you're holding the button. Not just pressing it and releasing it.

2023-04-20 20:32 UTC, MChecaH commented on wiki/Gameplay/Hit_object/Slider/es.md
> +Los sliders a menudo se asignan a sonidos largos o sostenidos en la música, pero se pueden usar en cualquier lugar siempre que haya un ritmo que los apoye. Los sliders se utilizan para hacer que la l
```suggestion
Los sliders a menudo se asignan a sonidos largos o sostenidos en la música, pero se pueden usar en cualquier lugar siempre que haya un ritmo que los apoye. Los sliders se utilizan para hacer que la lectura sea intuitiva cuando las canciones tienen cambios de ritmo, ya que los slidertail dan feedback pero se reproducen de forma pasiva. Los sliders también se utilizan para simplificar el ritmo en las dificultades más fáciles.
```

**L**

2023-04-20 20:47 UTC, agatemosu commented on wiki/Gameplay/Hit_object/Slider/es.md
> +Los sliders a menudo se asignan a sonidos largos o sostenidos en la música, pero se pueden usar en cualquier lugar siempre que haya un ritmo que los apoye. Los sliders se utilizan para hacer que la l
L tu :rage:

2023-04-22 13:52 UTC, TicClick approved these changes

2023-04-22 13:55 UTC, merged