[FR] Update `Skin`
ppy/osu-wiki pull request #9161
Opened 2023-04-16 09:24 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-16 10:29 UTC, Ganondorf-1 requested changes

2023-04-16 10:29 UTC, Ganondorf-1 commented on wiki/Skin/fr.md
> +Les skins peuvent être utilisés pour optimiser le gameplay, car beaucoup d'entre eux cachent certains détails visuels ou offrent des éléments de gameplay axés sur un certain [playstyle](/wiki/Gamepla
```suggestion
Les skins peuvent être utilisés pour optimiser le gameplay, car beaucoup d'entre eux cachent certains détails visuels ou offrent des éléments de gameplay axés sur un certain [style de jeu](/wiki/Gameplay/Play_style), comme des combinaisons spécifiques de [mods](/wiki/Gameplay/Game_modifier). En outre, certains skins proposent des menus personnalisés, qui représentent généralement des personnages d'anime et de jeux divers, ou qui sont basés sur certains styles de design, tels que le minimalisme ou la techno.
```

2023-04-16 10:29 UTC, Ganondorf-1 commented on wiki/Skin/fr.md
> +## Comment utiliser un skin personalisé
```suggestion
## Comment utiliser un skin personnalisé
```

2023-04-16 10:29 UTC, Ganondorf-1 commented on wiki/Skin/fr.md
> +Les skins peuvent être soit [créés à partir de rien](/wiki/Skinning), soit téléchargés en tant que [fichier `.osk`](/wiki/Client/File_formats/Osk_(file_format)) et importés dans le jeu. Pour importer
```suggestion
Les skins peuvent être soit [créés à partir de rien](/wiki/Skinning), soit téléchargés en tant que [fichier `.osk`](/wiki/Client/File_formats/Osk_(file_format)) et importés dans le jeu. Pour importer un fichier `.osk`, il suffit de de l'ouvrir avec osu!, ou de le glisser-déposer dans le jeu. Si le fichier téléchargé est au format `.zip` ou `.rar`, extrayez-le. Le dossier résultant qui contient le fichier `skin.ini` peut alors être déplacé dans le dossier `Skins` de votre installation d'osu!.
```

2023-04-16 10:29 UTC, Ganondorf-1 commented on wiki/Skin/fr.md
> +- [Collection de skins pour joueurs professionnels Circle People](https://circle-people.com/skins/)
```suggestion
- [Collection de skins des joueurs professionnels sur Circle People](https://circle-people.com/skins/)
```

2023-04-18 21:35 UTC, TicClick approved these changes

2023-04-18 21:36 UTC, merged