[ZH] Update `Main_Page`
ppy/osu-wiki pull request #9168
Opened 2023-04-17 14:11 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-17 15:34 UTC, Sunnyboy971 requested changes
Seems fine.

2023-04-19 01:32 UTC, Sunnyboy971 approved these changes

2023-04-19 09:40 UTC, TicClick approved these changes

2023-04-19 09:43 UTC, TicClick approved these changes

2023-04-19 09:48 UTC, merged