[FR] Update `History_of_osu!/2014`
ppy/osu-wiki pull request #9175
Opened 2023-04-18 12:15 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-04 07:56 UTC, Ganondorf-1 requested changes

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^ranking-maintenance]: [osu! newspost par peppy (20/01/2014) "Performance Ranking Maintenance"](https://osu.ppy.sh/home/news/2014-01-20-performance-ranking-maintenance)
```suggestion
[^ranking-maintenance]: [Article de news par peppy (20/01/2014) "Performance Ranking Maintenance"](https://osu.ppy.sh/home/news/2014-01-20-performance-ranking-maintenance)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^new-perf-ranking]: [osu! newspost par Tom94 (26/01/2014) "New Performance Ranking"](https://osu.ppy.sh/home/news/2014-01-26-new-performance-ranking)
```suggestion
[^new-perf-ranking]: [Article de news par Tom94 (26/01/2014) "New Performance Ranking"](https://osu.ppy.sh/home/news/2014-01-26-new-performance-ranking)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
>  [^pp-article]: [osu! wiki article "Performance points"](/wiki/Performance_points)
```suggestion
[^pp-article]: [Article de l'osu! wiki "Points de performance"](/wiki/Performance_points)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^all-game-modes]: [osu! newspost par Tom94 (01/03/2014) "Performance ranking for all gamemodes"](https://osu.ppy.sh/home/news/2014-03-01-performance-ranking-for-all-gamemodes)
```suggestion
[^all-game-modes]: [Article de news par Tom94 (01/03/2014) "Performance ranking for all gamemodes"](https://osu.ppy.sh/home/news/2014-03-01-performance-ranking-for-all-gamemodes)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^change-background]: [osu! forum comment (Resolved Issues) par Pawsu (20/12/2015) "[resolved] How to change all beatmap backgrounds")](https://osu.ppy.sh/community/forums/topics/397827?start=4749640
```suggestion
[^change-background]: [Commentaire sur le forum (Resolved Issues) par Pawsu (20/12/2015) "[resolved] How to change all beatmap backgrounds")](https://osu.ppy.sh/community/forums/topics/397827?start=4749640)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
>  [^skinning]: [osu! wiki article "Skinning history"](/wiki/Skinning/History)
```suggestion
[^skinning]: [Article de l'osu! wiki "L'histoire du skinning"](/wiki/Skinning/History)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^fanart]: [osu! newspost par LuigiHann (03/04/2014) "osu! Monthly Fanart Contest #1 - Ends this week!"](https://osu.ppy.sh/home/news/2014-04-03-osu-monthly-fanart-contest-1-ends-this-week)
```suggestion
[^fanart]: [Article de news par LuigiHann (03/04/2014) "osu! Monthly Fanart Contest #1 - Ends this week!"](https://osu.ppy.sh/home/news/2014-04-03-osu-monthly-fanart-contest-1-ends-this-week)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^fanart-results]: [osu! newspost par LuigiHann (21/05/2014) "First Official osu! Fanart Contest Results!"](https://osu.ppy.sh/home/news/2014-05-21-first-official-osu-fanart-contest-results)
```suggestion
[^fanart-results]: [Article de news par LuigiHann (21/05/2014) "First Official osu! Fanart Contest Results!"](https://osu.ppy.sh/home/news/2014-05-21-first-official-osu-fanart-contest-results)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^download]: [osu! newspost par peppy (18/06/2014) "Download restrictions removed"](https://osu.ppy.sh/home/news/2014-06-18-download-restrictions-removed)
```suggestion
[^download]: [Article de news par peppy (18/06/2014) "Download restrictions removed"](https://osu.ppy.sh/home/news/2014-06-18-download-restrictions-removed)
```

2023-05-04 07:56 UTC, Ganondorf-1 commented on wiki/History_of_osu!/2014/fr.md
> +[^bat]: [osu! newspost par Ephemeral (21/08/2014) "Restructuring of the BAT"](https://osu.ppy.sh/home/news/2014-08-21-restructuring-of-the-bat)
```suggestion
[^bat]: [Article de news par Ephemeral (21/08/2014) "Restructuring of the BAT"](https://osu.ppy.sh/home/news/2014-08-21-restructuring-of-the-bat)
```

2023-05-15 13:35 UTC, TicClick approved these changes

2023-05-15 13:55 UTC, merged