[ZH] Add `Guides/Beginner's Tutorial`
ppy/osu-wiki pull request #9190
Opened 2023-04-20 10:50 UTC by Sunnyboy971

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-20 17:58 UTC, YumeMuzi requested changes
plz fix some translation errors

2023-04-20 17:58 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +欢迎来到 osu! 新手教程。 osu! 世界有时是极具竞争性的。不管你是想寻找提升职业生涯高度的力量，想在 osu! 中更有竞争力，还是只想让自己更加享受游戏，这篇教程都是为你量身定做的！这个教程涵盖了你在 osu! 世界中从启航到远走高飞的一切事情。
```suggestion
欢迎来到 osu! 新手教程。 osu! 世界时常风起云涌。不管你是想寻找提升职业生涯高度的动力；想在 osu! 中更有竞争力；还是只想沉浸在游戏之中，这篇教程都是为你量身定做的！它涵盖了你在 osu! 世界中，从初出茅庐到得心应手的一切需要知道的事情。
```

远走高飞是贬义，表示这里不好我润了

2023-04-20 17:58 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +如果你坚持使用鼠标，建议你用有线鼠标以确保稳定性，因为无线鼠标会断连、卡顿。尽管如此，任何鼠标都可能正常工作；有人甚至用的是一元店里的鼠标！长时间使用同一个鼠标也有利于进步，因此试试买一个能让你用很长时间的鼠标吧！使用鼠标游玩往往擅长：
```suggestion
如果你坚持使用鼠标，建议你用有线鼠标以确保稳定性，因为无线鼠标会断连、卡顿。尽管如此，一般来说任何鼠标都能在游戏中正常工作，有人甚至用的是一元店里的鼠标！长时间使用同一个鼠标也有利于进步，因此试试买一个能让你用很长时间的鼠标吧！使用鼠标游玩的玩家往往擅长：
```

缺少主语，需要补齐来确保上下文通顺

2023-04-20 17:58 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +如果你想要使用数位板，你应该尝试在数位板上圈定一个你能舒适游玩的区域。如果想要买一个用来玩 osu! 的数位板，你应该浏览一下[数位板购买](/wiki/Guides/Tablet_Purchase)指南。除此之外，多买些笔吧，因为你不会知道什么时候需要换笔。笔往往很快会磨损，尤其在高强度游玩期间。尽管你可以直接使用数位板点击圆圈，大多数玩家更倾向于使用键盘点击，这种方法我们稍后会提及。使用数位
```suggestion
如果你想要使用数位板，你应该尝试在数位板上圈定一个你能舒适游玩的区域。如果想要买一个用来玩 osu! 的数位板，你应该浏览一下[数位板购买](/wiki/Guides/Tablet_Purchase)指南。除此之外，笔尖通常会磨损，尤其是在高强度游玩期间会很快地磨损。以防你不知道什么时候需要换笔尖，多准备些吧。尽管你可以直接使用数位板点击圆圈，但是大多数玩家更倾向于使用键盘点击，这种方法我们稍后会提及。使用数位板游玩的玩家往往擅长：
```

nib是笔尖啊哥

2023-04-20 18:29 UTC, YumeMuzi requested changes
There are quite a few issues too, please revise them.

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +使用鼠标游玩往往会遇到如下困难：
```suggestion
使用鼠标游玩的玩家可能难以击打以下排列：
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +使用数位板游玩往往会遇到如下困难：
```suggestion
使用数位板游玩的玩家可能难以击打以下排列：
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +尽管这种方式很少见，也有相当一部分玩家使用。按触摸屏的力度不应过大，也不要用灵敏度太高的触摸屏，最好用延迟比较低的。这应该会延长屏幕的寿命。使用触摸屏游玩往往擅长：
```suggestion
尽管这种游玩方式很少见，但它也有相当一部分玩家使用。最好使用延迟比较低的触摸屏。但注意，按触摸屏的力度不应过大，也不要用灵敏度太高的触摸屏。按照这么做，应该会延长屏幕的寿命。使用触摸屏游玩的玩家往往擅长：
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +使用触摸屏游玩往往会遇到如下困难：
```suggestion
使用触摸屏游玩的玩家可能难以击打以下排列：
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +对于鼠标、数位板或任何其他输入设备，你也可以用键盘（默认是 `Z` 和 `X`）打击圆圈。这样做的好处是可以把物理动作分散到两只手上，而不是用瞄准设备点击，从而让你更容易打击更快部分的音符。需要一段时间来适应这种方式，但如果你已经决定使用键盘打击圆圈，还是尽早习惯为好。
```suggestion
除了鼠标、数位板或任何其他输入设备，你也可以用键盘（默认是 `Z` 和 `X`）打击圆圈。这样做的好处是可以把物理动作分散到两只手上，而不需要用瞄准设备点击，从而让你更容易打击部分更密集的音符。通常玩家们需要一段时间来适应这种方式。但如果你已经决定使用键盘打击圆圈，还是尽早上手为好。
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +音乐有节拍和节奏。当你开始打一张图（或是游玩之前），可以注意歌曲听起来的感觉，这样就可以很好地了解打击圆圈时跟随的韵律。与音乐紧密相处会帮助你获时间把控更加，协调度更好。
```suggestion
### 准确度与节奏感

游玩 osu! 时，像其他音游中一样，节奏感是很重要的因素之一。从这种意义上来讲，如果你听过很多音乐，注意到节奏应该相当容易。玩家注意准确度与节奏感的目标，是尽可能在正确的时间精确地打击音符。

游戏中的每个物件都有一个缩圈，是一个慢慢靠近打击圈的圆环。当这个圆环碰到打击圈时，是时候点击了！留意它们，会帮助你辨别出音符在整拍上还是半拍上，以及在下一个音符之前是否需要等待一小段时间。

音乐以节拍和节奏为主体。当你开始打一张图（或是游玩之前），可以注意歌曲听起来的感觉，这样就可以很好地了解打击圆圈时跟随的韵律。跟上音乐的节拍能更好地帮助你找到节奏感，协调身体。
```

原文是 Timing，但我认为这里用通用的 `节奏感` 更加通俗易懂。

one of the most 不能翻译成最...之一，中文没有这种表述方式。

最后一句不知道是什么意思。重新翻译了原文。

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +在像 osu! 这样的“指向+点击”游戏中，瞄准也是一个重要因素。如果光标没有移动到正确位置，在正确时间打击音符是没有意义的。在这种情况下，提升这项技能最有效的方式就是玩游戏。这项技能也有助于玩更难的图，因为在这些图中，音符间的间距很可能会变得越来越大，让你要移动的距离更大，从更远的距离处点击音符。
```suggestion
在像 osu! 这样的“移动+点击”游戏中，瞄准也是一个重要因素。如果光标没有移动到正确位置，即使在正确时机打击音符，也是没有意义的。在这种情况下，提升这项技能最有效的方式就是多练。这项技能也有助于玩更难的图，因为在这些图中，音符间的间距很可能会变得越来越大，从而导致你需要移动更大、更远的距离后才能点击音符。
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +一种不玩 osu! 的情况下练习瞄准的最佳方法是用你选择的输入设备使用电脑。不要害怕练习。如果你使用鼠标，就试试点击电脑上的文件图标；也可以用你的数位板画些什么。由此获得的协调度会助你在未来创造奇迹！
```suggestion
一种在不碰 osu! 的情况下练习瞄准的最佳方法，是使用你在游戏中使用的输入设备来日常使用电脑。不要害怕练习。如果你使用鼠标，就试试点击电脑上的文件图标；也可以用你的数位板画些什么。由此获得的协调技巧会助你在未来创造奇迹！
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +另一个重要的话题：osu! 是一款拥有无限上升难度曲线的游戏，意味着没有“赢得”游戏一说。相应地，你会专注于持续提升自我。不要反复玩一张图，当你的能力远远超出目前谱面难度所需时，你最终需要游玩别的谱面。
```suggestion
另一个重要的话题：osu! 的难度曲线是无限上升的。这意味着没有“赢得”游戏一说。相应地，你应该专注于持续提升自我。不要反复玩一张图，当你的能力远远超出目前谱面难度所需时，你最终需要游玩别的谱面。
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +提升的最佳方法是挑战自己。超越自己的边界去探索是适应更顽固难度的唯一方式。与玩许多可以 FC 甚至得 SS 的图相比，玩玩让你多次 miss 的图最终会让你获得更多的游玩经验。MMORPG 中也是如此，敌人越难打，你获得的经验就会更多。
```suggestion
提升的最佳方法是挑战自己。超越自己的边界去探索，是适应更困难难度的唯一方式。与游玩许多可以 FC 甚至得 SS 的图相比，尝试让你多次 miss 的图最终会让你获得更多的游玩经验。MMORPG 中也是如此，敌人越难打，你获得的经验就会更多。
```

2023-04-20 18:29 UTC, YumeMuzi commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +不要害怕练习总会让你由于一个或另一个原因 miss 的东西。你需要寻找挑战，看看需要怎么做才能达成挑战目标。你需要更快按按钮吗？你的需要更好的计时吗？你需要更准确地移向音符吗？这些都是你可以问自己的问题。这会帮助你更快找到答案，让你的经历都更加值得。
```suggestion
不要害怕练习一些由于某个原因，总会让你 miss 的东西。你需要挑战自己，看看需要怎么做才能达成挑战目标。你需要更快按键吗？你需要增进自己的节奏感吗？你需要提升自己的移动能力吗？这些都可以是你问自己的问题，从而帮助你更快找到答案，让你做出的所有努力更加值得。
```

你是大佐吗

2023-04-20 18:39 UTC, OnyxAje commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +请调整全局偏移量，直到你感到满意为止。设置正确的偏移量值会帮助你提高整体准确度！
将全局偏移量调整到你认为合适的数值为止，这能够提高你的整体准确度！

2023-04-21 02:15 UTC, Sunnyboy971 commented on wiki/Guides/Beginner's_Tutorial/zh.md
> +不要害怕练习总会让你由于一个或另一个原因 miss 的东西。你需要寻找挑战，看看需要怎么做才能达成挑战目标。你需要更快按按钮吗？你的需要更好的计时吗？你需要更准确地移向音符吗？这些都是你可以问自己的问题。这会帮助你更快找到答案，让你的经历都更加值得。
?

2023-04-22 08:25 UTC, YumeMuzi approved these changes

2023-04-22 14:08 UTC, TicClick approved these changes

2023-04-22 14:09 UTC, merged