Fixed Taiko #1, fixed Mania #1, and fixed CTB #1 username
ppy/osu-wiki pull request #9192
Opened 2023-04-20 17:07 UTC by BlueChinchompa

Fixed Taiko #1, fixed Mania #1, and fixed CTB #1 username

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-20 17:16 UTC, aceticke requested changes

2023-04-20 17:16 UTC, aceticke commented on wiki/History_of_osu!/Online_rankings/en.md
> +As of October 4, 2021, on the [osu!taiko performance rankings](https://osu.ppy.sh/rankings/taiko/performance) the rank #1 player is ::{ flag=JP }:: [shinchikuhome](https://osu.ppy.sh/users/3174184/ta
```suggestion
As of October 4, 2022, on the [osu!taiko performance rankings](https://osu.ppy.sh/rankings/taiko/performance) the rank #1 player is ::{ flag=JP }:: [shinchikuhome](https://osu.ppy.sh/users/3174184/taiko).
```

2023-04-20 21:50 UTC, WindowsMeosu reviewed
can't see any other changes that need corrections other than the capital name

2023-04-20 21:50 UTC, WindowsMeosu commented on wiki/History_of_osu!/Online_rankings/en.md
> +As of April 13, 2023, on the [osu!mania performance rankings](https://osu.ppy.sh/rankings/mania/performance) the rank #1 player is ::{ flag=KR }:: [Dressurf](https://osu.ppy.sh/users/758406/mania).
minor correction ("dressurf" doesn't start with a capital)
```suggestion
As of April 13, 2023, on the [osu!mania performance rankings](https://osu.ppy.sh/rankings/mania/performance) the rank #1 player is ::{ flag=KR }:: [dressurf](https://osu.ppy.sh/users/758406/mania).
```

2023-04-22 13:55 UTC, TicClick approved these changes
while this is correct, I think we should have proper history instead of updating a single line for the non-standard modes

2023-04-22 14:03 UTC, TicClick approved these changes

2023-04-22 14:05 UTC, TicClick approved these changes

2023-04-22 14:07 UTC, merged