Patch be
ppy/osu-wiki pull request #9207
Opened 2023-04-22 16:25 UTC by Sunnyboy971

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-23 10:33 UTC, YumeMuzi requested changes
精灵 -> 精灵图

2023-04-23 10:33 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/Design/zh.md
> +点击 "Browse..." 按钮来搜索要使用的精灵。你可以在精灵库窗口中点击缩略图来复制精灵。
```suggestion
#### 精灵图库 (Sprite Library)

![所使用精灵图的视觉表现。](img/SE_SL.jpg "所使用精灵图的视觉表现。")

点击 "Browse..." 按钮来搜索要使用的精灵图。你可以在精灵图库窗口中点击缩略图来复制精灵图。
```

2023-04-23 10:33 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/Design/zh.md
> +**分别显示不同图层下故事板对象的列表。**点击 “Sprite Library” 来添加故事板元素。可以将新精灵（故事板对象）拖放到对应图层以分配之。新精灵默认位于“前景”图层。点击精灵名会显示并跳转到精灵的位置及时间帧。复制的精灵使用的名称与原精灵相同。使用 `Delete` 键或顶部菜单的编辑 -> 删除来删除精灵。
```suggestion
**分别显示不同图层下故事板对象的列表。**点击 “Sprite Library” 来添加故事板元素。可以将新精灵图（故事板对象）拖放到对应图层以分配之。新精灵图默认位于“前景”图层。点击精灵名会显示并跳转到精灵图的位置及时间帧。复制的精灵图使用的名称与原精灵图相同。使用 `Delete` 键或顶部菜单的编辑 -> 删除来删除精灵图。
```

2023-04-23 10:33 UTC, YumeMuzi commented on wiki/Client/Beatmap_editor/Design/zh.md
> +| 色块模式 | 强制为精灵上色。可以通过在终点使用不同的颜色来逐步改变元素的颜色。“永久效果”，这是基本解释。 |
```suggestion
| 色块模式 | 强制为精灵图上色。可以通过在终点使用与起点不同的颜色，来逐步改变元素的颜色，“永久效果”。这是基本解释。 |
```

2023-04-25 13:06 UTC, TicClick approved these changes

2023-04-25 14:00 UTC, merged