Add New Featured Artist: 7_7 news post
ppy/osu-wiki pull request #9212
Opened 2023-04-23 12:15 UTC by Ephemeralis

7️⃣

2023-04-23 13:05 UTC, peppy approved these changes

2023-04-23 13:08 UTC, MChecaH requested changes
Keeping consistency with the Discord server's name changes.

2023-04-23 13:08 UTC, MChecaH commented on news/2023/2023-04-23-new-featured-artist-7-7.md
> +If you're struggling to map something by **7\_7** (or any of our other Featured Artists), check out the `#featured-artists` channel in the [osu!dev Discord Server](https://discord.gg/ppy).
```suggestion
If you're struggling to map something by **7\_7** (or any of our other Featured Artists), check out the `#featured-artists` channel in the [osu! Discord Server](https://discord.gg/ppy).
```

`dev` should be removed as to stay consistent with the name change + [wiki article changes.](https://osu.ppy.sh/wiki/en/Community/osu%21_Discord_server).

2023-04-23 13:08 UTC, MChecaH commented on news/2023/2023-04-23-new-featured-artist-7-7.md
> +That's all for this week! Head to `#featured-artists` in the osu!dev server for some quick mapping advice, and track the [@osugame Twitter](https://twitter.com/osugame) if you want to know who's join
```suggestion
That's all for this week! Head to `#featured-artists` in the osu! server for some quick mapping advice, and track the [@osugame Twitter](https://twitter.com/osugame) if you want to know who's joining our Featured Artist library next week.
```

Same as Line 17.

2023-04-23 13:48 UTC, Walavouchey requested changes

2023-04-23 13:48 UTC, Walavouchey commented on news/2023/2023-04-23-new-featured-artist-7-7.md
> +**25** of those songs are ready for mapping from [**7\_7**'s Featured Artist listing](https://osu.ppy.sh/beatmaps/artists/356), including the [osu!original](/wiki/osu!_originals) *7\_7 feat. kasane v
```suggestion
**25** of those songs are ready for mapping from [**7\_7**'s Featured Artist listing](https://osu.ppy.sh/beatmaps/artists/356), including the [osu! original](/wiki/osu!_originals) *7\_7 feat. kasane vavzed - 7D* that debuted in the Grand Finals pool of [TWC 2023](/wiki/Tournaments/TWC/2023) (which happened a few minutes ago, by the way).
```

2023-04-23 13:48 UTC, Walavouchey commented on news/2023/2023-04-23-new-featured-artist-7-7.md
> +Play through [this brand new osu!taiko map](https://osu.ppy.sh/beatmapsets/1980743#taiko/4113017) mapped by the artist!
```suggestion
Play through [this brand-new osu!taiko map](https://osu.ppy.sh/beatmapsets/1980743#taiko/4113017) mapped by the artist!
```

2023-04-23 13:49 UTC, Walavouchey commented on news/2023/2023-04-23-new-featured-artist-7-7.md
> +title: "New Featured Artist: 7\_7"
escaping is not supported here

```suggestion
title: "New Featured Artist: 7_7"
```

2023-04-23 13:54 UTC, Walavouchey approved these changes

2023-04-24 00:14 UTC, pishifat approved these changes

2023-04-24 00:28 UTC, merged