[ES] Add `History_of_osu!/2017`
ppy/osu-wiki pull request #9222
Opened 2023-04-23 18:55 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

I will continue with the remaining ones later, so feel free to skip that section if someone was planning to translate it.

2023-04-24 19:11 UTC, agatemosu requested changes

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [Programa de tutoría comunitaria otoño 2017 inscripciones abiertas](https://osu.ppy.sh/home/news/2017-07-18-community-mentorship-program-fall-2017-signups-now-open)
```suggestion
- [osu!mania 4K World Cup 2017 - Registrations now open!](https://osu.ppy.sh/home/news/2017-07-10-osumania-4k-world-cup-2017-registrations-now-open)
- [Mocha in Summer Fanart Contest Voting Open](https://osu.ppy.sh/home/news/2017-07-11-mocha-in-summer-fanart-contest-voting-open)
- [osu!catch World Cup 2017 - Results](https://osu.ppy.sh/home/news/2017-07-14-osucatch-world-cup-2017-results)
- [Community Mentorship Program Fall 2017 Signups Now Open](https://osu.ppy.sh/home/news/2017-07-18-community-mentorship-program-fall-2017-signups-now-open)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[Wisp X](https://osu.ppy.sh/beatmaps/artists/16) y [OISHII](https://osu.ppy.sh/beatmaps/artists/17) fueron anunciados como nuevos artistas destacados. Se abren las audiciones para osu!idol 2017. La o
```suggestion
[Wisp X](https://osu.ppy.sh/beatmaps/artists/16) y [OISHII](https://osu.ppy.sh/beatmaps/artists/17) fueron anunciados como nuevos artistas destacados. Se abren las audiciones para osu!idol 2017. La osu! Coffee Hour se presentó como un pódcast. Se abrió una revisión para el nuevo aspecto de [Yuzu](/wiki/Mascots#yuzu) como un concurso de arte de fans.
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [Nuevo artista destacado: OISHII](https://osu.ppy.sh/home/news/2017-08-30-new-featured-artist-oishii)
```suggestion
- [w Featured Artist: Wisp X](https://osu.ppy.sh/home/news/2017-08-10-new-featured-artist-wisp-x)
- [osu!idol 2017 Auditions Now Open](https://osu.ppy.sh/home/news/2017-08-14-osu-idol-2017-auditions-now-open)
- [Introducing the osu! Coffee Hour](https://osu.ppy.sh/home/news/2017-08-15-introducing-the-osu-coffee-hour)
- [Yuzu's New Look Contest](https://osu.ppy.sh/home/news/2017-08-21-yuzus-new-look-contest)
- [New Featured Artist: OISHII](https://osu.ppy.sh/home/news/2017-08-30-new-featured-artist-oishii)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[\*namirin](https://osu.ppy.sh/beatmaps/artists/18) fue anunciada como otra artista destacada. Mapeo con recompensas regresa con recompensas vinculadas a canciones seleccionadas. La osu!mania 4K Worl
```suggestion
[\*namirin](https://osu.ppy.sh/beatmaps/artists/18) fue anunciada como otra artista destacada. Mapping with rewards regresa con recompensas vinculadas a canciones seleccionadas. La osu!mania 4K World Cup concluyó con Corea del Sur tomando el primer lugar de Estados Unidos. Se abrió la votación por el nuevo aspecto de Yuzu.
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [Ya está abierta la votación para el nuevo look de Yuzu](https://osu.ppy.sh/home/news/2017-09-29-yuzus-new-look-voting-now-open)
```suggestion
- [New Featured Artist: \*namirin](https://osu.ppy.sh/home/news/2017-09-10-new-featured-artist-namirin)
- [Mapping With Rewards Returns](https://osu.ppy.sh/home/news/2017-09-23-mapping-with-rewards-returns)
- [osu!mania 4K World Cup - Results](https://osu.ppy.sh/home/news/2017-09-26-osu-mania-4k-world-cup-results)
- [Yuzu's New Look Voting Now Open](https://osu.ppy.sh/home/news/2017-09-29-yuzus-new-look-voting-now-open)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [Halloween desciende](https://osu.ppy.sh/home/news/2017-10-31-halloween-descends)
```suggestion
- [Halloween 2017 Fanart Contest](https://osu.ppy.sh/home/news/2017-10-09-halloween-fanart-contest)
- [osu! World Cup 2017: Registrations now open!](https://osu.ppy.sh/home/news/2017-10-13-osu-world-cup-2017-registrations-now-open)
- [Halloween 2017 Fanart Voting Now Open](https://osu.ppy.sh/home/news/2017-10-24-halloween-2017-fanart-voting-now-open)
- [Halloween Descends](https://osu.ppy.sh/home/news/2017-10-31-halloween-descends)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Se abrió otro concurso de fanart de Halloween. Se abren las inscripciones para la osu! World Cup 2017. Unos días antes de Halloween, se abrió el concurso de fanart para Halloween. En Halloween, se re
```suggestion
Se abrió otro concurso de arte de fans de Halloween. Se abren las inscripciones para la osu! World Cup 2017. Unos días antes de Halloween, se abrió el concurso de arte de fans para Halloween. En Halloween, se revelaron los resultados del concurso de arte de fans.
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19) fue anunciado como otro artista destacado. peppy abrió un hilo en el foro para centralizar sus pensamientos sobre las pantallas táctiles; junto con
```suggestion
[MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19) fue anunciado como otro artista destacado. peppy abrió un hilo en el foro para centralizar sus pensamientos sobre las pantallas táctiles; junto con algunas respuestas a las soluciones propuestas con frecuencia. El canal `#osu-performance` en el servidor de Discord osu!dev se abrió para permitir una discusión abierta. Se abrió el concurso de arte de fans de invierno de 2017.
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [Concurso de Fanart de Invierno 2017](https://osu.ppy.sh/home/news/2017-11-26-winter-2017-fanart-contest)
```suggestion
- [New Featured Artist: MOtOLOiD](https://osu.ppy.sh/home/news/2017-11-07-new-featured-artist-motoloid)
- [osu!, touchscreens and you](https://osu.ppy.sh/community/forums/topics/665986)
- [Winter 2017 Fanart Contest](https://osu.ppy.sh/home/news/2017-11-26-winter-2017-fanart-contest)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [¡y así termina el 2017!](https://www.youtube.com/watch?v=5x7VnC1R0Do)
```suggestion
- [Winter is Here!](https://osu.ppy.sh/home/news/2017-12-14-winter-is-here)
- [osu! World Cup 2017 Concludes](https://osu.ppy.sh/home/news/2017-12-21-owc-2017-concludes)
- [Community Contributors: 2017](https://osu.ppy.sh/home/news/2017-12-24-community-contributors-2017)
- [osu!status on Twitter](https://twitter.com/osustatus/status/945098179183181824)
- [and so 2017 comes to an end!](https://www.youtube.com/watch?v=5x7VnC1R0Do)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Se publicaron los resultados del concurso de fanart de invierno de 2017, premiando a [Leissss](https://osu.ppy.sh/users/4750716) con la mayor cantidad de votos. La OWC 2017 concluyó con la victoria d
```suggestion
Se publicaron los resultados del concurso de arte de fans de invierno de 2017, premiando a [Leissss](https://osu.ppy.sh/users/4750716) con la mayor cantidad de votos. La OWC 2017 concluyó con la victoria de Polonia. Gracias a LiquidPL, la vergonzoza página de descarga de la osu!web se rehizo. El día antes de Navidad, se anunció otro puñado de contribuidores de la comunidad. Todos los jugadores recibieron el estado de osu!supporter temporalmente con fines de prueba, lo que casualmente sucedió en Nochebuena. peppy finaliza el año con un vídeo, dando a 2017 una revisión del año con respecto a la versión [lazer](/wiki/Client/Release_stream/Lazer) de osu!.
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Links:
```suggestion
Enlaces:
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [Versión 0.0.3 · ppy/osu](https://github.com/ppy/osu/releases/tag/v0.0.3)
```suggestion
- [New Featured Artist: Ben Briggs](https://osu.ppy.sh/home/news/2017-02-08-new-featured-artist-ben-briggs)
- [Release 0.0.3 · ppy/osu](https://github.com/ppy/osu/releases/tag/v0.0.3)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +- [Aspire regresa para 2017](https://osu.ppy.sh/home/news/2017-01-21-aspire-returns-for-2017)
```suggestion
- [Happy New Year!](https://osu.ppy.sh/home/news/2017-01-01-happy-new-year)
- [New Featured Artists: S3RL and nanobii](https://osu.ppy.sh/home/news/2017-01-09-new-featured-artists-s3rl-and-nanobii)
- [Aspire Returns For 2017](https://osu.ppy.sh/home/news/2017-01-21-aspire-returns-for-2017)
```

2023-04-24 19:11 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[Ephemeral](https://osu.ppy.sh/users/102335) publicó una noticia sobre el nuevo año para asegurar que sucederán muchas cosas importantes en 2017. [S3RL](https://osu.ppy.sh/beatmaps/artists/9) y [nano
```suggestion
[Ephemeral](https://osu.ppy.sh/users/102335) publicó una noticia sobre el nuevo año para asegurar que sucederán muchas cosas importantes en 2017. [S3RL](https://osu.ppy.sh/beatmaps/artists/9) y [nanobii](https://osu.ppy.sh/beatmaps/artists/10) fueron anunciados como nuevos artistas destacados de osu!. [cYsmix](https://osu.ppy.sh/beatmaps/artists/2), [yuki.](https://osu.ppy.sh/beatmaps/artists/4) y [Helblinde](https://osu.ppy.sh/beatmaps/artists/5) lanzaron cada uno un nuevo álbum dando a osu! 26 nuevas canciones para beatmapear. Aspire regresa para 2017.
```

2023-06-09 19:16 UTC, TicClick commented
@UnknownOsu please address agatemosu's review

2023-06-09 23:33 UTC, UnknownOsu commented on wiki/History_of_osu!/2017/es.md
> +[Ephemeral](https://osu.ppy.sh/users/102335) publicó una noticia sobre el nuevo año para asegurar que sucederán muchas cosas importantes en 2017. [S3RL](https://osu.ppy.sh/beatmaps/artists/9) y [nano
Está raro decir "beatmapear", la gran mayoría dice "mapear" al momento de querer crear un mapa. 

No he escuchado a nadie decir "voy a beatmapear esta canción". Lo otro me parece bien.

```suggestion
[Ephemeral](https://osu.ppy.sh/users/102335) publicó una noticia sobre el nuevo año para asegurar que sucederán muchas cosas importantes en 2017. [S3RL](https://osu.ppy.sh/beatmaps/artists/9) y [nanobii](https://osu.ppy.sh/beatmaps/artists/10) fueron anunciados como nuevos artistas destacados de osu!. [cYsmix](https://osu.ppy.sh/beatmaps/artists/2), [yuki.](https://osu.ppy.sh/beatmaps/artists/4) y [Helblinde](https://osu.ppy.sh/beatmaps/artists/5) lanzaron cada uno un nuevo álbum dando a osu! 26 nuevas canciones para mapear. Aspire regresa para 2017.
```

2023-06-10 15:34 UTC, TicClick approved these changes
I assume everything else is taken care of

2023-06-10 15:37 UTC, UnknownOsu commented
I forgot that

2023-06-10 15:38 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[Wisp X](https://osu.ppy.sh/beatmaps/artists/16) y [OISHII](https://osu.ppy.sh/beatmaps/artists/17) fueron anunciados como nuevos artistas destacados. Se abren las audiciones para osu!idol 2017. La o
and this?

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Ha comenzado el Monthly Beatmapping Contest que gira en torno a osu!catch. [LukHash](https://osu.ppy.sh/beatmaps/artists/12) fue anunciado como otro artista destacado. La votación de Aspire 2017 ha c
```suggestion
Ha comenzado el Monthly Beatmapping Contest que gira en torno a osu!catch. [LukHash](https://osu.ppy.sh/beatmaps/artists/12) fue anunciado como otro artista destacado. La votación de Aspire 2017 ha comenzado. Se anunció que Destacados coexistiría con el Gráfico de clasificación. Se abrió el noveno concurso de arte de fans con temática de primavera.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +El Monthly Beatmapping Contest \#13 concluyó con [RyoKazuka](https://osu.ppy.sh/users/6258586) obteniendo el primer lugar. Apsire 2017: la etapa uno concluyó con [ProfessionalBox](https://osu.ppy.sh/
```suggestion
El Monthly Beatmapping Contest \#13 concluyó con [RyoKazuka](https://osu.ppy.sh/users/6258586) obteniendo el primer lugar. Apsire 2017: la etapa uno concluyó con [ProfessionalBox](https://osu.ppy.sh/users/3250792) ocupando el primer lugar. Se abrió la votación para el concurso de arte de fans de primavera. Se publicó el n.º 100(?) de osu!weekly. La osu!taiko World Cup 2017 concluyó con la victoria de Japón contra Taiwán. Antes de que terminara abril, los votos del concurso de arte de fans de primavera estaban listos, lo que permitió que [Evaine](https://osu.ppy.sh/users/7295733) obtuviera el primer lugar.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Se abrieron las inscripciones para la osu!catch World Cup 2017. [Kuba Oms](https://osu.ppy.sh/beatmaps/artists/13) apareció como otro artista de osu!. osu! anunció que estaría en la Anime Expo 2017.
```suggestion
Se abrieron las inscripciones para la osu!catch World Cup 2017. [Kuba Oms](https://osu.ppy.sh/beatmaps/artists/13) apareció como otro artista de osu!. osu! anunció que estaría en la Anime Expo 2017. En casi más de un año, se anunció la mascota de osu!taiko. [Mocha](/wiki/Mascots#mocha) ha entrado en escena con [pippi](/wiki/Mascots#pippi), [Yuzu](/wiki/Mascots#yuzu), y [María](/wiki/Mascots#mani-&-mari). Por último, [Rin / Function Phantom](https://osu.ppy.sh/beatmaps/artists/14) fue anunciado como parte de los artistas destacados de osu!. Se abrió la votación para los concursos de mapping de osu!mania y osu!catch.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +El equipo de osu! participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, la imagen del menú principal/campo de juego se cambió a cuatro imágenes genéricas, pero nuevas.
```suggestion
El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15/6/2017, la imagen del menú principal/campo de juego se cambió a cuatro imágenes genéricas, pero nuevas. La imagen del campo de juego cambia cuando se cambia la canción actual. Se ha agregado a las [opciones](/wiki/Client/Options) el soporte para habilitar o deshabilitar los fondos de temporada durante todo el año o verlos a veces. En algún momento alrededor de este mes, dentro del [servidor de Discord osu!](/wiki/Community/osu!_Discord_server), se discutió que osu!weekly había muerto. A partir de este momento, cada publicación de noticias oficial y de la comunidad se publicará de forma independiente cuando esté lista, en lugar de esperar cada semana. Comenzó el concurso de arte de fans de Mocha en verano.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Se abren las inscripciones para la osu!mania 4K World Cup. Se abrió la votación para el concurso de fanart de Mocha en Verano. La osu!catch World Cup 2017 concluyó con Corea del Sur tomando el primer
```suggestion
Se abren las inscripciones para la osu!mania 4K World Cup. Se abrió la votación para el concurso de arte de fans de Mocha en Verano. La osu!catch World Cup 2017 concluyó con Corea del Sur tomando el primer lugar de China. Se abrieron las inscripciones para el Community Mentorship Program Fall 2017. El último día de julio, el concurso de arte de fans de Mocha en verano concluyó con [2Su](https://osu.ppy.sh/users/6598966) obteniendo el primer lugar.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[Wisp X](https://osu.ppy.sh/beatmaps/artists/16) y [OISHII](https://osu.ppy.sh/beatmaps/artists/17) fueron anunciados como nuevos artistas destacados. Se abren las audiciones para osu!idol 2017. La o
```suggestion
[Wisp X](https://osu.ppy.sh/beatmaps/artists/16) y [OISHII](https://osu.ppy.sh/beatmaps/artists/17) fueron anunciados como nuevos artistas destacados. Se abren las audiciones para osu!idol 2017. La osu! Coffee Hour se presentó como un pódcast. Se abrió una revisión para el nuevo aspecto de [Yuzu](/wiki/Mascots#yuzu) como un concurso de arte de fans.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Se abrió otro concurso de fanart de Halloween. Se abren las inscripciones para la osu! World Cup 2017. Unos días antes de Halloween, se abrió el concurso de fanart para Halloween. En Halloween, se re
```suggestion
Se abrió otro concurso de arte de fans de Halloween. Se abren las inscripciones para la osu! World Cup 2017. Unos días antes de Halloween, se abrió el concurso de arte de fans para Halloween. En Halloween, se revelaron los resultados del concurso de arte de fans.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19) fue anunciado como otro artista destacado. peppy abrió un hilo en el foro para centralizar sus pensamientos sobre las pantallas táctiles; junto con
```suggestion
[MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19) fue anunciado como otro artista destacado. peppy abrió un hilo en el foro para centralizar sus pensamientos sobre las pantallas táctiles; junto con algunas respuestas a las soluciones propuestas con frecuencia. El canal `#osu-performance` en el [servidor de Discord osu!](/wiki/Community/osu!_Discord_server) se abrió para permitir una discusión abierta. Se abrió el Winter 2017 Fanart Contest.
```

2023-06-10 21:45 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +Se publicaron los resultados del concurso de fanart de invierno de 2017, premiando a [Leissss](https://osu.ppy.sh/users/4750716) con la mayor cantidad de votos. La OWC 2017 concluyó con la victoria d
```suggestion
Se publicaron los resultados del Winter 2017 Fanart Contest, premiando a [Leissss](https://osu.ppy.sh/users/4750716) con la mayor cantidad de votos. La OWC 2017 concluyó con la victoria de Polonia. Gracias a LiquidPL, la vergonzoza página de descarga de la osu!web se rehizo. El día antes de Navidad, se anunció otro puñado de contribuidores de la comunidad. Todos los jugadores recibieron el estado de osu!supporter temporalmente con fines de prueba, lo que casualmente sucedió en Nochebuena. peppy finaliza el año con un video, dando a 2017 una revisión del año con respecto a la versión [lazer](/wiki/Client/Release_stream/Lazer) de osu!.
```

2023-06-10 22:23 UTC, UnknownOsu commented on wiki/History_of_osu!/2017/es.md
> +El Monthly Beatmapping Contest \#13 concluyó con [RyoKazuka](https://osu.ppy.sh/users/6258586) obteniendo el primer lugar. Apsire 2017: la etapa uno concluyó con [ProfessionalBox](https://osu.ppy.sh/
No creo que se refiera a un _problema_, sino a una edición

2023-06-11 09:12 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +El Monthly Beatmapping Contest \#13 concluyó con [RyoKazuka](https://osu.ppy.sh/users/6258586) obteniendo el primer lugar. Apsire 2017: la etapa uno concluyó con [ProfessionalBox](https://osu.ppy.sh/
Pues prefiero fanart que fan art

2023-06-11 15:27 UTC, UnknownOsu commented on wiki/History_of_osu!/2017/es.md
> +El Monthly Beatmapping Contest \#13 concluyó con [RyoKazuka](https://osu.ppy.sh/users/6258586) obteniendo el primer lugar. Apsire 2017: la etapa uno concluyó con [ProfessionalBox](https://osu.ppy.sh/
Ok

2023-06-11 17:29 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, las imágenes del menú principal/campo de juego se cambiaron a cuatro imágenes genéricas, pero nuevas.
```suggestion
El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, las imágenes del menú principal/campo de juego se cambiaron a cuatro imágenes genéricas, pero nuevas. La imagen del campo de juego cambia cuando se cambia la canción actual. Se ha agregado a las [opciones](/wiki/Client/Options) el soporte para habilitar o deshabilitar los fondos de temporada durante todo el año o verlos a veces. En algún momento alrededor de este mes, dentro del [servidor de Discord osu!](/wiki/Community/osu!_Discord_server), se discutió que osu!weekly había muerto. A partir de este momento, cada publicación de noticias oficial y de la comunidad se publicará de forma independiente cuando esté lista, en lugar de esperar cada semana. Comenzó el concurso de fanart de Mocha en verano.
```

2023-06-11 17:29 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +[MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19) fue anunciado como otro artista destacado. peppy abrió un hilo en el foro para centralizar sus pensamientos sobre las pantallas táctiles; junto con
```suggestion
[MOtOLOiD](https://osu.ppy.sh/beatmaps/artists/19) fue anunciado como otro artista destacado. peppy abrió un hilo en el foro para centralizar sus pensamientos sobre las pantallas táctiles; junto con algunas respuestas a las soluciones propuestas con frecuencia. El canal `#osu-performance` en el [servidor de Discord osu!](/wiki/Community/osu!_Discord_server) se abrió para permitir una discusión abierta. Se abrió el Winter 2017 Fanart Contest.
```

2023-06-11 17:52 UTC, UnknownOsu commented on wiki/History_of_osu!/2017/es.md
> +El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, las imágenes del menú principal/campo de juego se cambiaron a cuatro imágenes genéricas, pero nuevas.
¿No te parece que esté "de"? Yo lo veo bien

2023-06-11 18:05 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, las imágenes del menú principal/campo de juego se cambiaron a cuatro imágenes genéricas, pero nuevas.
No, porque es el nombre

2023-06-11 18:16 UTC, UnknownOsu commented on wiki/History_of_osu!/2017/es.md
> +El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, las imágenes del menú principal/campo de juego se cambiaron a cuatro imágenes genéricas, pero nuevas.
Bueno, yo veo el nombre bien (osu!). Pero entiendo a lo que te refieres. 

Creo que es mejor especificar de quién es el Discord; por ejemplo, queda mejor decir "Me quiero unir al servidor de Discord de osu!" en lugar de decir "Me quiero unir al servidor de Discord osu!". Así se puede saber de qué servidor se está hablando.

2023-06-11 19:35 UTC, agatemosu commented on wiki/History_of_osu!/2017/es.md
> +El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, las imágenes del menú principal/campo de juego se cambiaron a cuatro imágenes genéricas, pero nuevas.
No puede ser porque antes se llamaba `osu!dev` y no tenía sentido llamarlo `de osu!dev` así que ahora tampoco debería

2023-06-11 19:59 UTC, UnknownOsu commented on wiki/History_of_osu!/2017/es.md
> +El osu! team participa en la Anime Expo por los próximos 10 años de osu!. El 15 de junio de 2017, las imágenes del menú principal/campo de juego se cambiaron a cuatro imágenes genéricas, pero nuevas.
Pues sí, en ese caso no se vería bien. Diría que en este sí, creo que dependiendo del nombre del servidor se puede considerar usar una preposición o no.

Sigue sin convencerme del todo que no esté `de`, pero tampoco es que cambie todo el significado de lo que se quiere dar a entender.

2023-06-12 09:04 UTC, Walavouchey approved these changes

2023-06-12 09:17 UTC, merged