[ZH] Update `Silence`
ppy/osu-wiki pull request #9234
Opened 2023-04-25 16:16 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-26 12:07 UTC, Sunnyboy971 requested changes

2023-04-26 12:07 UTC, Sunnyboy971 commented on wiki/Silence/zh.md
> +![](img/silence-ingame.png "Silence warning in the chat")
```suggestion
![](img/silence-ingame.png "聊天页面的禁言警告")
```

2023-04-27 00:29 UTC, Sunnyboy971 approved these changes

2023-04-27 12:09 UTC, TicClick approved these changes

2023-04-27 12:11 UTC, merged