[ZH] Update `Account restrictions`
ppy/osu-wiki pull request #9248
Opened 2023-04-28 11:54 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-04-29 02:45 UTC, Sunnyboy971 requested changes

2023-04-29 02:45 UTC, Sunnyboy971 commented on wiki/Help_centre/Account_restrictions/zh.md
> +根据上述标准条款，即使申诉通过，账号也会禁止以参赛者或者管理员，参加或举办正式、含有主页奖牌的锦标赛。禁赛将会从违规日期往后计算一年（如果用户多次申诉，则禁赛时长将会延长至两年）。解封邮件将标明禁赛的时长。
这句话不是太通顺

2023-05-01 01:06 UTC, Sunnyboy971 approved these changes

2023-05-04 21:14 UTC, Walavouchey approved these changes

2023-05-04 21:18 UTC, merged