[ZH] Update `osu!catch RC` and Add `Spinner trap`
ppy/osu-wiki pull request #9277
Opened 2023-05-02 22:33 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-03 02:46 UTC, Sunnyboy971 requested changes

2023-05-03 02:46 UTC, Sunnyboy971 commented on wiki/Gameplay/Spinner_trap/zh.md
> +# 滑条陷阱
```suggestion
# 转盘陷阱
```

原意是“转盘”，是不是有习惯用法？

2023-05-03 04:41 UTC, Sunnyboy971 approved these changes

2023-05-04 21:26 UTC, Walavouchey approved these changes

2023-05-04 21:30 UTC, merged