[ZH] Add `Bubble` and `Proto-bubble`
ppy/osu-wiki pull request #9279
Opened 2023-05-03 00:52 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-03 02:54 UTC, Sunnyboy971 requested changes

2023-05-03 02:54 UTC, Sunnyboy971 commented on wiki/Modding/Bubble/zh.md
> +在[旧版审核流程](/wiki/Modding/Forum_modding)中，[原型泡泡](/wiki/Modding/Proto-bubble)系统被取代后，如果摸图团队给予了一个普通泡泡，则表示他们认为谱面已经准备好上架了。最终，另一个BAT 或者 BN 会检查被泡过的谱面。如果需要的话，他们会稍微修改谱面，即可将谱面推至[上架](/wiki/Beatmap/Category#上架-(ra
```suggestion
在[旧版审核流程](/wiki/Modding/Forum_modding)中，[原型泡泡](/wiki/Modding/Proto-bubble)系统被取代后，如果摸图团队给予了一个普通泡泡，则表示他们认为谱面已经准备好上架了。最终，另一个 BAT 或者 BN 会检查被泡过的谱面。如果需要的话，他们会稍微修改谱面，即可将谱面推至[上架](/wiki/Beatmap/Category#上架-(ranked))或者[达标](/wiki/Beatmap/Category#达标-(approved))状态。
```

2023-05-03 04:40 UTC, Sunnyboy971 approved these changes

2023-05-04 21:31 UTC, Walavouchey approved these changes

2023-05-04 21:35 UTC, merged