[ZH] Add `Lazer/Feature comparison`
ppy/osu-wiki pull request #9290
Opened 2023-05-04 10:08 UTC by Sunnyboy971

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-05 03:38 UTC, YumeMuzi requested changes
There are many long and difficult sentences in the article that need to be carefully translated.

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +当你看到滑条的时候，这很有道理。但这也增加了计算游玩的复杂度（也潜在地增加了回放中的错误，尤其是 OD 值与滑条速度较高时）。
```suggestion
玩家在看到滑条后能理解怎么去击打。但这也增加了计算游玩的复杂度（也潜在地增加了回放中的错误，尤其是判定严度 (OD) 与滑条速度 (SV) 较高时）。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +此举背后的理由很简单：不这样做，启用`渐出滑条`时，如果玩家点击滑条头迟了，就会很难看出来。你会让圆圈停在原地，延迟渐出过程吗？如果这样做，圆圈该怎么跟上滑条球的实际位置呢？相反，如果不延迟渐出过程，你会让滑条头圆圈与滑条本身分开吗（请别这么做）？
```suggestion
这个改变背后的理由很简单：如果不这样做，当玩家较晚点击滑条头时，启用`渐出滑条`设置时，从视觉上来考虑，会很麻烦。比如，较晚点击时，在滑条头原处留个圆圈，推迟滑条头缩回的时机？如果按照这样做，那么滑条头该怎么样跟上滑条球的实际位置？除此之外，难道还能暂不缩回滑条，让滑条头与滑条主体分离吗？不要考虑太多。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 滑条尾不会增加连击数，也不会导致 miss
```suggestion
#### 滑条尾不会计入连击数，也不会导致失误 (miss)
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +滑条尾的行为一度很怪异，漏掉它不会导致断连（也不会导致 MISS 判定）。这意味着 S 评价的游玩（需要无 MISS 判定）尽管漏了几个滑条尾，也看起来像是全连了。关于是否应称此类游玩为全连的争论随之而来。
```suggestion
滑条尾的行为一度很怪异，漏掉它不会导致断连（也不会导致 MISS 判定）。这意味着 S 评价的游玩（需要无 MISS 判定）尽管漏了几个滑条尾，也看起来像是全连了。随之而来的是大量的关于是否应该将这种成绩纳入全连的争论。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 漏掉滑条头会导致 miss
```suggestion
#### 漏掉滑条头会导致失误 (miss)
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +在 lazer 中，不点击滑条头会对整个滑条给出 MISS 判定。在此之后，仍然可以从滑条点与折返中获得连击数、分数与准确度，但从滑条尾只能获得分数与准确度。
```suggestion
在 lazer 中，错过滑条头，整个滑条会获得 MISS 判定。在此之后，你仍然可以从滑条点与折返中获得连击数、分数与准确度，从滑条尾上获得分数与准确度。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 滑条尾未被打击时不播放音效
```suggestion
#### 漏掉滑条尾时不播放音效
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 无法击打与 swell 重叠的音符
```suggestion
#### 无法击打与转盘覆盖区域重叠的音符
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +一些机关图利用了与 swell 重叠的音符。
```suggestion
一些技巧 (gimmick) 图含有与转盘覆盖区域重叠的音符。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 不会阻止乱打滑条
```suggestion
#### 不需要按照鼓点击打黄条
```

这里需要改一下翻译，原文很难直译

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +在稳定版中，滑条不能击打得太快，也不能太慢。像在 ScoreV2 模组中一样，已经去除了这样的限制。
```suggestion
在稳定版中，黄条不能击打得太快或太慢。像在 ScoreV2 模组中一样，lazer 已经去除了这样的限制。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +这可能会导致回放中的判定不准与难度增加。
```suggestion
这可能会导致回放中的判定不准，并且会增加实际难度。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 会对长按音符的头和尾进行判定
```suggestion
#### 长按音符的头尾都有判定
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 长按音符点得分，也会导致断连
```suggestion
#### 长按音符中的点会提供分数或者导致断连
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +在稳定版中，在长按音符体中松开按键会立刻导致断连，但现在只会在漏掉音符点时断连。
```suggestion
在稳定版中，按住长按音符后，松开按键会立刻导致断连。但现在只会在漏掉长按音符中的点时断连。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +当需要用另一个手指按住按键时，这点更改允许使用手腕，从而允许 cheesing （即 “manipulating”）。
```suggestion
这允许玩家在一根手指按住按键，同时需要用另一根手指点击时，通过手腕的发力来提起手指并同时按下两个按键 (cheesing，或者 manipulating)。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 限制极限滚动速度
```suggestion
#### 限制极限滚动速度 (SV)
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +一些含有 SV 机关（比如物件传送与停滞）的谱面可能看起来与预期不符，但除此之外都是可玩的。
```suggestion
一些含有变速梗（比如物件瞬移与停滞）的谱面可能看起来与预期不符，但除此之外的谱面都是可玩的。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +无论整体难度如何，这个窗口期过去恒为 ±16 毫秒。
```suggestion
无论整体难度 (OD) 设为多少，之前这个判定固定为 ±16 毫秒。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### Flashlight 模组没有梯度
```suggestion
#### Flashlight 模组可视区域周围没有渐变
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +### 分数、表现分和排行榜
```suggestion
### 分数、表现分 (pp) 和排行榜
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +lazer 的计分系统被简化了，主要好在无需回放来重新计算得分。增加了两套可互换的系统：*标准化*和*经典*。标准化计分将得分限制为最高 1,000,000 分 + 附加分 + 得分乘数，而经典计分类似于标准化，但与谱面中的物件数平方成正比。可以在设置中进行选择，游戏内的分数显示区域也会相应改变。
```suggestion
lazer 中使用了简化过的计分系统。这套系统的主要优点是不需要播放一遍回放后才能计算分数。这套计分系统有两个可更换的计分方式：标准和经典。标准计分则将基础分数限制为 1000000 分乘以分数倍率 + 奖励分。经典计分和标准类似，但是它的分数是根据谱面中已经击打物件的数量来平方缩放过的。这两个计分方式可以在设置中切换，并且会影响游戏中所有分数显示。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +不会颁发奖牌。这个功能会在实现防作弊措施后被启用，也要进一步考虑由于其他游玩方面的改变导致的难度变化。
```suggestion
lazer 中不会得到奖章（成就）。将来会在防作弊实装后启用这个功能，并且，我们也要进一步考虑由于其他游玩方面的改变，可能导致的难度变化。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +已经计划加入此功能，但还没有开始在其上工作。
```suggestion
已经计划加入此功能，但还没有开始在这个项目中工作。
```

2023-05-05 03:38 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +- [Niconico](https://en.wikipedia.org/wiki/Niconico) 式的滚动回放评论
```suggestion
- [Niconico](https://en.wikipedia.org/wiki/Niconico) 式的滚动回放评论（弹幕）
```

2023-05-05 04:14 UTC, Sunnyboy971 commented
Thank you for your careful review! ❤️

2023-05-05 05:59 UTC, YumeMuzi commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +一些冒险性质的谱面利用了稳定版客户端中允许使用不寻常滑条机制的漏洞，小到作为不可见圆圈使用的零长度滑条，大到跨屏幕拉伸与压缩的滑条。
```suggestion
一些 Aspire 谱面利用了稳定版客户端中允许使用不寻常滑条机制的漏洞，小到作为不可见圆圈使用的零长度滑条，大到跨屏幕拉伸与压缩的滑条。
```
这里忘记提了 aspire 国内暂且没有翻译，就不直译了

2023-05-07 00:50 UTC, kj415j45 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +  - 对 Windows 8.1+、 macOS、 Linux、 iOS 与 Android 的本地支持
```suggestion
  - 对 Windows 8.1+、 macOS、 Linux、 iOS 与 Android 的原生支持
```

2023-05-07 00:50 UTC, kj415j45 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 即使不点击，滑条头也会沿路径缩回
```suggestion
#### 即使不点击，滑条头也会沿路径移动
```

2023-05-07 00:50 UTC, kj415j45 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +这个改变背后的理由很简单：如果不这样做，当玩家较晚点击滑条头时，启用`渐出滑条`设置时，从视觉上来考虑，会很麻烦。比如，较晚点击时，在滑条头原处留个圆圈，推迟滑条头缩回的时机？如果按照这样做，那么滑条头该怎么样跟上滑条球的实际位置？除此之外，难道还能暂不缩回滑条，让滑条头与滑条主体分离吗？不要考虑太多。
```suggestion
这个改变背后的理由很简单：如果不这样做，启用`渐出滑条`设置时，一旦玩家操作滞后就会难以辨识此时应击打的位置：假如在滑条头初始位置留下圆圈，延后滑条渐出，此时该如何让滑条头跟上实际的滑条球位置呢？换句话说，假如不延后滑条渐出，此时让滑条头与滑条球分离会更好吗？
```

2023-05-07 00:50 UTC, kj415j45 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +对于对 Aspire 谱面的兼容性，还需要进一步讨论与考虑。比如，不可见圆圈未来可能成为一个得到适当支持的特性。
```suggestion
对于对 Aspire 谱面的兼容性，还需要进一步讨论与考虑。比如，不可见圆圈未来可能成为一个得到正确支持的特性。
```

2023-05-07 00:50 UTC, kj415j45 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 长按音符的头尾都有判定
```suggestion
#### 长按物件的头尾都有判定
```

2023-05-07 00:50 UTC, kj415j45 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +#### 长按音符中的点会提供分数或者导致断连
```suggestion
#### 长按物件中的点会提供分数或者导致断连
```

2023-05-07 00:50 UTC, kj415j45 commented on wiki/Client/Release_stream/Lazer/Feature_comparison/zh.md
> +玩家在看到滑条后能理解怎么去击打。但这也增加了计算游玩的复杂度（也潜在地增加了回放中的错误，尤其是判定严度 (OD) 与滑条速度 (SV) 较高时）。
```suggestion
玩家在看到滑条后能理解怎么去击打。但这也增加了计算游玩的复杂度（也潜在地增加了回放中的错误，尤其是整体难度 (OD) 与滑条速度 (SV) 较高时）。
```

2023-05-07 01:53 UTC, kj415j45 approved these changes
LGTM

2023-05-07 17:32 UTC, TicClick approved these changes

2023-05-07 17:33 UTC, merged