[FR] Update  `osu!dev_Discord_server`
ppy/osu-wiki pull request #9291
Opened 2023-05-04 12:07 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-05 00:05 UTC, Sitoria commented on wiki/Community/osu!_Discord_server/fr.md
>  Le lien d'invitation permanent est <https://discord.gg/ppy>.
need blank line
```suggestion
Le lien d'invitation permanent est <https://discord.gg/ppy>.

```

2023-05-05 00:05 UTC, Sitoria commented
topic name will be `Community/osu!_Discord_Server` cuz `osu!dev discord server` repo is renamed to `osu! Discord Server`

2023-05-05 00:08 UTC, Sitoria commented on wiki/Community/osu!_Discord_server/fr.md
```suggestion
```
seems got error cuz 2 blank line appears - delete one?

2023-05-06 13:20 UTC, Ganondorf-1 requested changes

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
>  # Serveur Discord osu!dev
```suggestion
# Serveur Discord osu!
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +Le serveur Discord **osu!** anciennement appelé **osu!dev**, est le serveur [Discord](https://discordapp.com) officiel pour le développement. Le serveur fonctionne comme un centre de discussion et de
```suggestion
Le serveur Discord **osu!**, anciennement appelé **osu!dev**, est le serveur [Discord](https://discordapp.com) officiel pour le développement. Le serveur fonctionne comme un centre de discussion et de travail sur sur les projets open source et communautaires d'osu!. C'est l'endroit principal pour contribuer au développement d'osu! et entrer en contact avec [l'équipe d'osu!](/wiki/People/osu!_team).
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#welcome` | Information serveur |
```suggestion
| `#welcome` | Informations sur le serveur |
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#github-feed` | Flux d'événements pour divers [ppy GitHub repositories](https://github.com/ppy) |
```suggestion
| `#github-feed` | Flux d'événements pour divers [repositories GitHub ppy](https://github.com/ppy) |
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `Meetings` (Salon de conférence) | [réunions communautaire d'osu!](/wiki/Community/osu!_community_meetings) et réunions sur l'état du développement |
```suggestion
| `Meetings` (Salon de conférence) | [osu! community meetings](/wiki/Community/osu!_community_meetings) et réunions sur l'état du développement |
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#difficulty-taiko` | Calcul du star rating et des points de performances pour [osu!taiko](/wiki/Game_mode/osu!taiko)  |
```suggestion
| `#difficulty-taiko` | Calcul du star rating et des points de performance pour [osu!taiko](/wiki/Game_mode/osu!taiko)  |
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#difficulty-catch` | Calcul du star rating et des points de performances pour [osu!catch](/wiki/Game_mode/osu!catch) |
```suggestion
| `#difficulty-catch` | Calcul du star rating et des points de performance pour [osu!catch](/wiki/Game_mode/osu!catch) |
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#difficulty-mania` | Calcul du star rating et des points de performances pour [osu!mania](/wiki/Game_mode/osu!mania) |
```suggestion
| `#difficulty-mania` | Calcul du star rating et des points de performance pour [osu!mania](/wiki/Game_mode/osu!mania) |
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#featured-artists` | création de beatmaps, de projets ou de playlists des [Featured Artist](/wiki/People/Featured_Artists) |
```suggestion
| `#featured-artists` | Création de beatmaps, de projets ou de playlists des [Featured Artists](/wiki/People/Featured_Artists) |
```

2023-05-06 13:20 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#tournaments` | [Tournaments](/wiki/Tournaments) and [official tournament support](/wiki/Tournaments/Official_support) |
```suggestion
| `#tournaments` | [Tournois](/wiki/Tournaments) et le [support officiel aux tournois](/wiki/Tournaments/Official_support) |
```

2023-05-10 10:53 UTC, Ganondorf-1 requested changes

2023-05-10 10:53 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +| `#general` | Discussion générale et dépannage liés à l'osu! |
```suggestion
| `#general` | Discussion générale et dépannage liés à osu! |
```

2023-05-10 10:53 UTC, Ganondorf-1 commented on wiki/Community/osu!_Discord_server/fr.md
> +Le serveur Discord **osu!**, anciennement appelé **osu!dev**, est le serveur [Discord](https://discordapp.com) officiel pour le développement. Le serveur fonctionne comme un centre de discussion et d
```suggestion
Le serveur Discord **osu!**, anciennement appelé **osu!dev**, est le serveur [Discord](https://discordapp.com) officiel pour le développement. Le serveur fonctionne comme un centre de discussion et de travail sur les projets open source et communautaires d'osu!. C'est l'endroit principal pour contribuer au développement d'osu! et entrer en contact avec [l'équipe d'osu!](/wiki/People/osu!_team).
```

2023-05-10 17:16 UTC, merged