Reword confusing metadata rule in `Ranking criteria`
ppy/osu-wiki pull request #9313
Opened 2023-05-07 19:26 UTC by Walavouchey

as [noted on discord](https://discord.com/channels/188630481301012481/218677502141399041/1104822463491231774)

2023-05-08 17:45 UTC, Darius-Wattimena commented on wiki/Ranking_Criteria/en.md
> +- **If a symbol is used to group part of a title, the group including the surrounding symbols must be surrounded by a space before and after.** For example, `Song★Title★` becomes `Song ★Title★`.
This sounds rather confusing to read without any commas
```suggestion
- **If a symbol is used to group part of a title, the group, including the surrounding symbols, must be surrounded by a space before and after.** For example, `Song★Title★` becomes `Song ★Title★`.
```

Alternatively, you could rewrite it like this to make it even shorter.
```suggestion
- **Symbols used to group a part of the title must include surrounding spaces.** For example, `Song★Title★` becomes `Song ★Title★`.
```

2023-05-08 21:49 UTC, aceticke requested changes

2023-05-08 21:49 UTC, aceticke commented on wiki/Ranking_Criteria/en.md
> +- **Symbols used to group a part of the title must include surrounding spaces.** For example, `Song★Title★` becomes `Song ★Title★`.
```suggestion
- **Symbols used to group part of a title must include surrounding spaces.** For example, `Song★Title★` becomes `Song ★Title★`.
```

wala's originally wording for this part seemed fine, not sure why "the" is used when it's not referring to anything in particular

2023-05-14 20:54 UTC, TicClick approved these changes

2023-05-14 20:55 UTC, merged