Update `GB Cup 2023 Spring` Wiki Articles
ppy/osu-wiki pull request #9342
Opened 2023-05-10 14:43 UTC by HanHan3z

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-10 19:09 UTC, Walavouchey requested changes

2023-05-10 19:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Spring/en.md
> +4. Top 8 players of final ranking will get into the winner bracket, top 9-24 players will get into the loser bracket.
```suggestion
4. The top 8 will play in the winners' bracket, while the top 9–24 will play in the losers' bracket.
```

2023-05-10 19:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Spring/en.md
> +5. If there is a tie in final ranking, the player that have lower sum of ranks in every round will get higher final ranking.
```suggestion
5. In case of a tie in the rankings, the player with a lower sum of ranks in every round will take the higher rank.
```

2023-05-10 19:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Spring/en.md
> +6. In the playoff stage, players need to win 6 beatmaps in QuarterFinals and SemiFinals to win, 7 beatmaps in Finals and Grand Finals to win.
```suggestion
6. In the playoff stage, players need to win 6 beatmaps in order to win a match during Quarterfinals and Semifinals, and 7 beatmaps in the Finals and Grand Finals.
```

2023-05-10 19:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Spring/en.md
> +   - Finals and Grand Finals have 15 maps with 7RC, 3HB, 4LN and 1TB, winner of 13.
the win conditions are already specified above

```suggestion

| Stage | Beatmaps |
| :-- | :-- |
| Quarterfinals & Semifinals | 6 RC, 3 HB, 3 LN, and 1 TB |
| Finals & Grand Finals | 7 RC, 3 HB, 4 LN, and 1 TB |

```

2023-05-10 19:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Spring/en.md
>  2. There will be four separate mappools for each playoff round, with a varying number of beatmaps of different types.
```suggestion
2. There will be four separate mappools for each playoff round, with a varying number of beatmaps of different types:
```

2023-05-10 19:09 UTC, Walavouchey commented on wiki/Tournaments/GBC/GBC_2023_Spring/en.md
>     - Each mappool has one tiebreaker.
no longer needed

```suggestion
```

2023-05-11 01:20 UTC, yobrevelc submitted a review, later dismissed

2023-05-11 16:51 UTC, yobrevelc commented on wiki/Tournaments/GBC/GBC_2023_Spring/zh.md
> +| 决赛 & 总决赛 | 7 RC, 3 HB, 4 LN, and 1 TB |
fixed

2023-05-14 02:38 UTC, yobrevelc submitted a review, later dismissed

2023-05-14 16:20 UTC, Walavouchey submitted a review, later dismissed

2023-05-14 16:26 UTC, Walavouchey approved these changes

2023-05-14 16:27 UTC, merged