[ZH] Add `Maintenance`, Update `ASC` and sub articles
ppy/osu-wiki pull request #9395
Opened 2023-05-16 18:00 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-17 02:11 UTC, CloneWith requested changes
Great work. Thank you! ❤️

2023-05-17 12:37 UTC, CloneWith submitted a review, later dismissed

2023-06-09 19:59 UTC, TicClick commented
another tiny update from https://github.com/ppy/osu-wiki/pull/9515 and I'd say, merge this right in

2023-06-09 20:07 UTC, YumeMuzi commented
> another tiny update from #9515 and I'd say, merge this right in

updated

2023-06-09 21:14 UTC, TicClick approved these changes

2023-06-09 21:17 UTC, merged