Update `Project Loved` articles
ppy/osu-wiki pull request #9405
Opened 2023-05-17 23:26 UTC by Hiviexd

- guideline rewords that were discussed a while ago
- added more info to the team page
- removed detail about colored names because it's incorrect, user colors are not set to project loved team members

2023-05-17 23:49 UTC, aceticke approved these changes
yeah

2023-05-18 03:36 UTC, Walavouchey requested changes

2023-05-18 03:36 UTC, Walavouchey commented on wiki/People/Project_Loved_Team/en.md
> +Most new team members are selected through an application process held for specific roles in the Project Loved Team to fill empty positions or to assist with workload. The respective application form
```suggestion
Most new team members are selected through an application process held for specific roles in the Project Loved Team to fill empty positions or to assist with workload. Application forms are announced in Project Loved [news posts](https://osu.ppy.sh/home/news), and successful applicants are announced to the public in the subsequent month's post.
```

2023-05-18 03:36 UTC, Walavouchey commented on wiki/People/Project_Loved_Team/en.md
> +Some team additions may be added manually on a case-by-case basis in order to fill in positions that require certain skills or permissions. (e.g. the content moderator position, which is exclusive to
```suggestion
Some team additions may be added manually on a case-by-case basis in order to fill in positions that require certain skills or permissions. (e.g. the content moderator position, which is exclusive to [Global Moderation Team](/wiki/People/Global_Moderation_Team) and [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) members)
```

2023-05-18 03:36 UTC, Walavouchey commented on wiki/People/Project_Loved_Team/en.md
> +- As of April 28th, 2023, team members are awarded badges based on the length of their tenure in the team. The badges range from 1 year to 5 years.
```suggestion
- As of 28 April 2023, team members are awarded badges based on the length of their tenure in the team. The badges range from 1 year to 5 years.
```

2023-05-18 03:36 UTC, Walavouchey commented on wiki/People/Project_Loved_Team/en.md
>    - Until the 16th of April, 2021, the only people that had been in the group were ::{ flag=US }:: [clayton](https://osu.ppy.sh/users/3666350), ::{ flag=LT }:: [huu](https://osu.ppy.sh/users/6044237)
```suggestion
- Prior to the 28 April 2021, the [Project Loved group page](https://osu.ppy.sh/groups/31) was not public and used only for administrative purposes. As of now, it is publicly available.
  - Until the 16 April 2021, the only people that had been in the group were ::{ flag=US }:: [clayton](https://osu.ppy.sh/users/3666350), ::{ flag=LT }:: [huu](https://osu.ppy.sh/users/6044237), ::{ flag=SG }:: [Shoegazer](https://osu.ppy.sh/users/2520707), and ::{ flag=US }:: [Toy](https://osu.ppy.sh/users/2757689). Now, all of the Project Loved Team belongs to the group.
```

2023-05-18 12:44 UTC, Hiviexd commented on wiki/Community/Project_Loved/en.md
> +- **Every person involved in the beatmap must not disapprove of it being Loved.** This includes guest difficulty creators, hitsounders, skinners, and storyboarders. If one of the users involved in th
i went with the vague route to include other contributions like sb, hs, etc

2023-05-19 05:06 UTC, Walavouchey commented on wiki/Community/Project_Loved/en.md
> +- **Every person involved in the beatmap must not disapprove of it being Loved.** This includes guest difficulty creators, hitsounders, skinners, and storyboarders. If one of the users involved in th
hmm, ok then

```suggestion
- **Every person involved in the beatmap must not disapprove of it being Loved.** This includes guest difficulty creators, hitsounders, skinners, and storyboarders. If any user involved in the beatmap explicitly disagrees with their contribution being Loved, then it is to be removed from the beatmap after its nomination.
```

2023-05-19 05:08 UTC, Walavouchey approved these changes

2023-05-19 05:10 UTC, merged