[ZH] Add `Disambiguation` and subarticles
ppy/osu-wiki pull request #9408
Opened 2023-05-18 02:20 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-18 13:15 UTC, YumeMuzi requested changes

2023-05-18 13:15 UTC, YumeMuzi commented on wiki/Disambiguation/Combo/zh.md
> +- 一小[串](/wiki/Beatmapping/Combo)共用相同[颜色](/wiki/Beatmapping/Combo_colour)的打击物件。
```suggestion
- 一组[连击](/wiki/Beatmapping/Combo)，这里面的物件共用相同的[连击颜色](/wiki/Beatmapping/Combo_colour)。
```

2023-05-18 13:15 UTC, YumeMuzi commented on wiki/Disambiguation/NC/zh.md
> +- [创建新串 (New combo)](/wiki/Beatmapping/New_combo)
```suggestion
- [新连击 (New combo)](/wiki/Beatmapping/New_combo)
```

2023-05-18 13:15 UTC, YumeMuzi commented on wiki/Disambiguation/Snapping/zh.md
> +- [Dash snapping](/wiki/Gameplay/Dash_snapping)，[osu!catch](/wiki/Game_mode/osu!catch) 术语，描述了玩家接住下一个大果所需的移动。
```suggestion
- [白果跳对齐](/wiki/Gameplay/Dash_snapping)，[osu!catch](/wiki/Game_mode/osu!catch) 术语，描述了玩家接住下一个大果所需的移动。
```

2023-05-20 14:51 UTC, Walavouchey approved these changes

2023-05-20 14:52 UTC, merged