[ES] Add several `Gameplay Modifiers` articles
ppy/osu-wiki pull request #9418
Opened 2023-05-20 06:02 UTC by TheMoonLoop

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-20 07:06 UTC, TheMoonLoop commented
I'm very sorry for so many commits, i'm trying to get all the errors solved

2023-05-20 07:31 UTC, TheMoonLoop commented
It's ok now

2023-05-20 11:22 UTC, agatemosu requested changes

2023-05-20 11:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +
```suggestion
```

2023-05-20 11:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_Out/es.md
> +
```suggestion
```

2023-05-20 11:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +
```suggestion
```

2023-05-20 11:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Video/es.md
> +
```suggestion
```

2023-05-21 02:09 UTC, fosiXD commented
No publicar; pendiente de revisión. Para más información contactar con TheMoonLoop.

Do not publish; pending for revision. For further information contact TheMoonLoop.

2023-05-21 07:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +![10K mod icon](/wiki/shared/mods/10K.png "Icono del mod 10K")
```suggestion
![Icono del mod 10K](/wiki/shared/mods/10K.png "Icono del mod 10K")
```

2023-05-21 07:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de los mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-21 07:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +*No confundir con [xK (mod)](/wiki/Gameplay/Game_modifier/xK).*
```suggestion
*No debe confundirse con [xK (mod)](/wiki/Gameplay/Game_modifier/xK).*
```

2023-05-21 07:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +El mod **10K** era un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que permitía al jugador usar 10 teclas para un solo campo de juego en beatmaps *
```suggestion
El mod **10K** era un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que permitía al jugador usar 10 teclas para un solo campo de juego en [beatmaps](/wiki/Beatmap) *convertidos* de osu!mania. Funciona exactamente igual que el resto de los mods [xK](/wiki/Gameplay/Game_modifier/xK) y, por lo tanto, no era clasificable.
```

2023-05-21 09:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +![Jugabilidad entre Auto y Cine](/wiki/Gameplay/Game_modifier/Cinema/img/CM-comparison.jpg "Comparación del mod Auto (izquierda) con el mod Cine (derecha)")
```suggestion
![Jugabilidad de Auto vs. Cinema](/wiki/Gameplay/Game_modifier/Cinema/img/CM-comparison.jpg "Comparación del mod Auto (izquierda) con el mod Cinema (derecha)")
```

2023-05-21 09:29 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +En [osu!taiko](/wiki/Game_mode/osu!taiko), el mod Auto intentará un juego perfecto, pero no siempre obtendrá una calificación SS. Ocasionalmente, se perderá un tic en los redobles de batería que no c
```suggestion
En [osu!taiko](/wiki/Game_mode/osu!taiko), el mod Auto intentará un juego perfecto, pero no siempre obtendrá un grado SS. Ocasionalmente, se perderá una marca en los redobles de tambor que no comiencen en un tiempo completo o en medio tiempo y no siempre podrá completar dendens en mapas con una dificultad general muy alta.
```

2023-05-21 09:31 UTC, agatemosu commented
Can't commit revisions in batch?

2023-05-21 09:34 UTC, TheMoonLoop commented
> Can't you batch apply revisions and push them in a single commit?

I really don't know how to do that

2023-05-21 09:37 UTC, agatemosu commented
> > Can't you batch apply revisions and push them in a single commit?
> 
> I really don't know how to do that

On the web you can better apply the suggestions

2023-05-21 09:39 UTC, TheMoonLoop commented
> > > Can't you batch apply revisions and push them in a single commit?
> > 
> > 
> > I really don't know how to do that
> 
> On the web you can better apply the suggestions

...I'm on the web qwq

2023-05-21 10:13 UTC, agatemosu commented
> > > > Can't you batch apply revisions and push them in a single commit?
> > > 
> > > 
> > > I really don't know how to do that
> > 
> > On the web you can better apply the suggestions
> 
> ...I'm on the web qwq

doesn't it look like that? https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes

2023-05-21 10:17 UTC, TheMoonLoop commented
> > > > > Can't you batch apply revisions and push them in a single commit?
> > > > 
> > > > 
> > > > I really don't know how to do that
> > > 
> > > 
> > > On the web you can better apply the suggestions
> > 
> > 
> > ...I'm on the web qwq
> 
> doesn't it look like that? https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes

I just click on commit changes so...

2023-05-21 12:51 UTC, agatemosu commented
Can you apply/respond the missing reviews?

2023-05-21 13:11 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta los BPM y AR. Como resultado, solo vale un multiplicador de 1.06x (a diferencia
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta los PPM y el AR. Como resultado, solo vale un multiplicador de 1.06x (a diferencia del multiplicador de 1.12x para cualquier otr mod).
```

2023-05-21 13:11 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +- El nombre "Double Time" podría etiquetarse como un nombre inapropiado, ya que el mod DT en realidad no aumenta la velocidad de un mapa de ritmos dos veces (200%); acelera los mapas de ritmos en 1,5
```suggestion
- El nombre «Double Time» podría etiquetarse como un nombre inapropiado, ya que el mod DT en realidad no aumenta la velocidad de un beatmap dos veces (200 %); acelera los mapas de ritmos en 1.5x (150 %).
```

2023-05-21 13:11 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-05-21 13:11 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +![Valores modificados](/wiki/Gameplay/Game_modifier/Double_Time/img/GM_DT.jpg "Captura de los valores del mapa de ritmos cambiados por el mod Double Time")
```suggestion
![Valores modificados](/wiki/Gameplay/Game_modifier/Double_Time/img/GM_DT.jpg "Captura de los valores del beatmap cambiados por el mod Double Time")
```

2023-05-21 20:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +El mod **Auto** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que permite a los jugadores ver una reproducción perfecta del beatmap seleccionado.
```suggestion
El mod **Auto** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que permite a los jugadores ver una repetición perfecta del beatmap seleccionado.
```

2023-05-21 20:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +El mod funciona exactamente como una [repetición](/wiki/Gameplay/Replay), con las opciones para usar la velocidad de reproducción de 0.5x/1.0x/2.0x y los comentarios en el beatmap para verse y hacers
```suggestion
El mod funciona exactamente como una [repetición](/wiki/Gameplay/Replay), con las opciones para usar la velocidad de reproducción de 0.5x/1.0x/2.0x y los comentarios en el beatmap para verse y hacerse como de costumbre. El mod Auto siempre obtendrá un grado SS, con la excepción de algunos casos especiales.
```

2023-05-21 20:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +En [osu!taiko](/wiki/Game_mode/osu!taiko), el mod Auto intentará un juego perfecto, pero no siempre obtendrá un grado SS. Ocasionalmente, se perderá una marca en los redobles de tambor que no comienc
```suggestion
En [osu!taiko](/wiki/Game_mode/osu!taiko), el mod Auto intentará un juego perfecto, pero no siempre obtendrá un grado SS. Ocasionalmente, se perderá un golpe en los redobles de tambor que no comiencen en un tiempo completo o en medio tiempo y no siempre podrá completar dendens en mapas con una dificultad general muy alta.
```

2023-05-21 20:24 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Autopilot/es.md
> +Además, el valor de giros por minuto (Spins Per Minute o SPM) realizado por el mod Autopilot es similar a los giros por minuto realizados por el mod [Spun Out](/wiki/Gameplay/Game_modifier/Spun_Out),
```suggestion
Además, el valor de giros por minuto (SPM) realizado por el mod Autopilot es similar a los giros por minuto realizados por el mod [Spun Out](/wiki/Gameplay/Game_modifier/Spun_Out), por lo que el jugador no puede aumentar el SPM girando la ruleta con su cursor.
```
In others you have not put it

2023-05-21 20:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +Debido a que el mod Cinema es una variación del mod Auto, los hitsounds causados por los objetos aún se escucharán. Aunque los elementos de la repetición y la pantalla de resultados se desactivarán j
```suggestion
Debido a que el mod Cinema es una variación del mod Auto, los hitsounds causados por los objetos aún se escucharán. Aunque los elementos de la repetición y la pantalla de resultados se desactivarán junto con la atenuación del fondo configurada en 0 %.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +*Para una lista completa de los mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +*Para una lista completa de los mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Autopilot/es.md
> +*Para una lista completa de los mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +*Para una lista completa de los mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +*Para una lista completa de los mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_Out/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +*Para una lista completa de los mods, ver: [Modificadores del juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificadores del juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +*Ver también: [NC (desambiguación)](/wiki/Disambiguation/NC), [Double Time (mod)](/wiki/Gameplay/Game_modifier/Double_Time)*\
```suggestion
*Véase también: [NC (desambiguación)](/wiki/Disambiguation/NC), [Double Time (mod)](/wiki/Gameplay/Game_modifier/Double_Time)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +![NC mod icon](/wiki/shared/mods/NC.png "Icono del mod ightcore (NC)")
```suggestion
![Icono del mod NC](/wiki/shared/mods/NC.png "Icono del mod Nightcore (NC)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Fail/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Video/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Perfect/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Random/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Relax/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/ScoreV2/es.md
> +*Para una lista completa de los mods, ver: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/xK/es.md
> +![1K mod icon](/wiki/shared/mods/1K.png "Icono del mod 1K") ![2K mod icon](/wiki/shared/mods/2K.png "Icono del mod 2K") ![3K mod icon](/wiki/shared/mods/3K.png "Icono del mod 3K") ![4K mod icon](/wik
```suggestion
![Icono del mod 1K](/wiki/shared/mods/1K.png "Icono del mod 1K") ![Icono del mod 2K](/wiki/shared/mods/2K.png "Icono del mod 2K") ![Icono del mod 3K](/wiki/shared/mods/3K.png "Icono del mod 3K") ![Icono del mod 4K](/wiki/shared/mods/4K.png "Icono del mod 4K") ![Icono del mod 5K](/wiki/shared/mods/5K.png "Icono del mod 5K") ![Icono del mod 6K](/wiki/shared/mods/6K.png "Icono del mod 6K") ![Icono del mod 7K](/wiki/shared/mods/7K.png "Icono del mod 7K") ![Icono del mod 8K](/wiki/shared/mods/8K.png "Icono del mod 8K") ![Icono del mod 9K](/wiki/shared/mods/9K.png "Icono del mod 9K")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +![FI mod icon](/wiki/shared/mods/FI.png "Icono del mod Fade In (FI)")
```suggestion
![Icono del mod FI](/wiki/shared/mods/FI.png "Icono del mod Fade In (FI)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_Out/es.md
> +![FO mod icon](/wiki/shared/mods/FO.png "Icono del mod Fade Out (FO)")
```suggestion
![Icono del mod FO](/wiki/shared/mods/FO.png "Icono del mod Fade Out (FO)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +![FL mod icon](/wiki/shared/mods/FL.png "Icono del mod Flashlight (FL)")
```suggestion
![Icono del mod FL](/wiki/shared/mods/FL.png "Icono del mod Flashlight (FL)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +![HT mod icon](/wiki/shared/mods/HT.png "Icono del mod Half Time (HT)")
```suggestion
![Icono del mod HT](/wiki/shared/mods/HT.png "Icono del mod Half Time (HT)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +![HD mod icon](/wiki/shared/mods/HD.png "Icono del mod Hidden (HD)")
```suggestion
![Icono del mod HD](/wiki/shared/mods/HD.png "Icono del mod Hidden (HD)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +![MR mod icon](/wiki/shared/mods/MR.png "Mirror (MR) mod icon")
```suggestion
![Icono del mod MR](/wiki/shared/mods/MR.png "Icono del mod Mirror (MR)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Fail/es.md
> +![NF mod icon](/wiki/shared/mods/NF.png "Icono del mod No Fail (NF)")
```suggestion
![Icono del mod NF](/wiki/shared/mods/NF.png "Icono del mod No Fail (NF)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Video/es.md
> +![NV mod icon](/wiki/shared/mods/NV.png "Icono del mod No Video (NV)")
```suggestion
![Icono del mod NV](/wiki/shared/mods/NV.png "Icono del mod No Video (NV)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Perfect/es.md
> +![PF mod icon](/wiki/shared/mods/PF.png "Perfect (PF) mod icon")
```suggestion
![Icono del mod PF](/wiki/shared/mods/PF.png "Icono del mod Perfect (PF)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Random/es.md
> +![RD mod icon](/wiki/shared/mods/RD.png "Icono del mod Random (RD)")
```suggestion
![Icono del mod RD](/wiki/shared/mods/RD.png "Icono del mod Random (RD)")
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +Debido a este aumento mucho mayor en la dificultad en comparación con otros [modos de juego](/wiki/Game_mode), el mod Hard Rock vale un multiplicador de 1,12x en comparación con 1,06x en todos los de
```suggestion
Debido a este aumento mucho mayor en la dificultad en comparación con otros [modos de juego](/wiki/Game_mode), el mod Hard Rock vale un multiplicador de 1.12x en comparación con 1.06x en todos los demás modos de juego.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +Para calcular las ventanas de tiempo después de aplicar HR, la [ventana de tiempo original](/wiki/Beatmap/Overall_difficulty) debe dividirse entre 1,4. La ventana de tiempo de Rainbow 300 (MAX) es fi
```suggestion
Para calcular las ventanas de tiempo después de aplicar HR, la [ventana de tiempo original](/wiki/Beatmap/Overall_difficulty) debe dividirse entre 1.4. La ventana de tiempo de Rainbow 300 (MAX) es fija independientemente del OD, lo que significa que la ventana de tiempo de un MAX con FC siempre será de ±11.43 ms.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Spun_Out/es.md
> +El mod **Spun Out** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo ayudar a los jugadores de [osu!](/wiki/Game_mode/osu!) a girar con éxito las ruletas en un [beat
```suggestion
El mod **Spun Out** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo ayudar a los jugadores de [osu!](/wiki/Game_mode/osu!) a girar con éxito las ruletas en un [beatmap](/wiki/Beatmap). El mod borrará todos los botones giratorios del beatmap a exactamente 286.48 giros por minuto (SPM) en el sentido de las agujas del reloj, que es 3/5 de los 477.26 SPM de Auto.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +Cuando se combina con el mod Hidden, el área visible de la "linterna" se convierte en un punto discutible porque las notas son técnicamente "invisibles" porque las notas se desvanecen por completo al
```suggestion
Cuando se combina con el mod Hidden, el área visible de la "linterna" se convierte en un punto discutible porque las notas son técnicamente "invisibles" porque las notas se desvanecen por completo al llegar al área visible. Esto también requiere la memorización completa del beatmap.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +Cuando se combina con el mod Hidden, las frutas son momentáneamente visibles si el receptor está *directamente debajo* de las frutas. Es decir, hasta que el jugador alcanza el combo 100x, momento en
```suggestion
Cuando se combina con el mod Hidden, las frutas son momentáneamente visibles si el receptor está *directamente debajo* de las frutas. Es decir, hasta que el jugador alcanza el combo 100x, momento en el que las frutas se vuelven completamente invisibles cuando las frutas alcanzan el área visible. Al igual que osu! y osu!taiko, esto también requiere la memorización completa del beatmap.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +- Si se pasa un mapa de ritmos con una calificación S o SS con el mod Hidden habilitado, el mapa de ritmos otorgará la variante plateada del grado en su lugar.
```suggestion
- Si se pasa un beatmap con un rango S o SS con el mod Hidden habilitado, el beatmap otorgará la variante plateada del grado en su lugar.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +El mod **Nightcore** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que funciona exactamente de la misma manera que su variante, Double Time, pero también aumenta el tono y agrega una pis
```suggestion
El mod **Nightcore** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que funciona exactamente de la misma manera que su variante, Double Time, pero también aumenta el tono y agrega una pista de batería al fondo que — en compás de 4/4 — va en el orden de un bombo en los tiempos 1 y 3, aplaude en los tiempos 2 y 4, y choca en el tiempo 1 cada 4 compases.
```
```suggestion
El mod **Nightcore** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que funciona exactamente de la misma manera que su variante, Double Time, pero también aumenta el tono y agrega una pista de batería al fondo que —en compás de 4/4— va en el orden de un bombo en los tiempos 1 y 3, aplaude en los tiempos 2 y 4, y choca en el tiempo 1 cada 4 compases.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Perfect/es.md
> +Cualquiera de los siguientes actos **provocará** que el mod Perfect reinicie el mapa de ritmos:
```suggestion
Cualquiera de los siguientes actos **provocará** que el mod Perfect reinicie el beatmap:
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Perfect/es.md
> +Cualquiera de los siguientes actos **no hará que** el mod Perfect reinicie el mapa de ritmos:
```suggestion
Cualquiera de los siguientes actos **no hará que** el mod Perfect reinicie el beatmap:
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Relax/es.md
> +En [osu!](/wiki/Game_mode/osu!), habilitar el modo Relax solo requiere que el jugador desplace el cursor sobre [golpear objetos](/wiki/Gameplay/Hit_object); todos los objetos golpeados serán tocados
```suggestion
En [osu!](/wiki/Game_mode/osu!), habilitar el modo Relax solo requiere que el jugador desplace el cursor sobre [golpear objetos](/wiki/Gameplay/Hit_object); todos los objetos golpeados serán tocados automáticamente por osu!. El mod hace que sea imposible fallar en el beatmap en todos los modos de juego.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +Para ser más específicos, el mod Sudden Death solo fallará en el mapa de ritmos si sucede algo de lo siguiente:
```suggestion
Para ser más específicos, el mod Sudden Death solo fallará en el beatmap si sucede algo de lo siguiente:
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +El mod de Sudden Death **no** fallará en el mapa de ritmos si sucede algo de lo siguiente:
```suggestion
El mod de Sudden Death **no** fallará en el beatmap si sucede algo de lo siguiente:
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +A diferencia de la variante [Perfect](/wiki/Gameplay/Game_modifier/Perfect) del mod Sudden Death, el mapa de ritmos no volverá a intentarlo automáticamente. En cambio, el jugador se quedará con una p
```suggestion
A diferencia de la variante [Perfect](/wiki/Gameplay/Game_modifier/Perfect) del mod Sudden Death, el beatmap no volverá a intentarlo automáticamente. En cambio, el jugador se quedará con una pantalla de falla normal al fallar.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +- Cuando se juega con el mod Sudden Death habilitado en osu!, hay casos raros en los que el jugador puede sobrevivir de un drenaje de barra de vida completo por romper el combo. Si el jugador logró p
```suggestion
- Cuando se juega con el mod Sudden Death habilitado en osu!, hay casos raros en los que el jugador puede sobrevivir de un drenaje de barra de vida completo por romper el combo. Si el jugador logró preservar al menos una pizca de salud haciendo que un control deslizante se active en un margen de tiempo muy corto justo después de que se rompió el combo y antes de que la barra de vida se agote por completo, el jugador puede continuar jugando el beatmap tal como está y no se impondrá una gran figura de pérdida.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +- El nombre «Double Time» podría etiquetarse como un nombre inapropiado, ya que el mod DT en realidad no aumenta la velocidad de un beatmap dos veces (200 %); acelera los mapas de ritmos en 1.5x (150
```suggestion
- El nombre «Double Time» podría etiquetarse como un nombre inapropiado, ya que el mod DT en realidad no aumenta la velocidad de un beatmap dos veces (200 %); acelera los beatmaps en 1.5x (150 %).
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +Sin embargo, vale la pena mencionar que muchos jugadores no consideran que el uso del mod sea útil para disminuir la dificultad relativa de los mapas de ritmos, especialmente los de alta intensidad.
```suggestion
Sin embargo, vale la pena mencionar que muchos jugadores no consideran que el uso del mod sea útil para disminuir la dificultad relativa de los beatmaps, especialmente los de alta intensidad. El argumento para esto es que la velocidad de aproximación reducida crea una situación complicada y difícil de leer en la que la velocidad real del beatmap no se refleja muy bien visualmente (como se muestra arriba).
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +En los mapas de ritmos con una dificultad general alta, los jugadores experimentados usan el mod Hidden para aumentar la puntuación en lugar del mod [Hard Rock (HR)](/wiki/Gameplay/Game_modifier/Hard
```suggestion
En los beatmaps con una dificultad general alta, los jugadores experimentados usan el mod Hidden para aumentar la puntuación en lugar del mod [Hard Rock (HR)](/wiki/Gameplay/Game_modifier/Hard_Rock) porque HR ocasionalmente hace que la ventana de tiempo sea demasiado pequeña.
```

2023-05-22 18:59 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +El razonamiento detrás de esto es que muchos mapas de ritmos de osu!mania están mapeados por creadores de mano derecha dominante y, por lo tanto, muchos de los patrones de mapas de ritmos están hecho
```suggestion
El razonamiento detrás de esto es que muchos beatmaps de osu!mania están mapeados por creadores de mano derecha dominante y, por lo tanto, muchos de los patrones de beatmaps están hechos para que sean más cómodos para los jugadores de osu!mania de mano derecha dominante. Por lo tanto, muchos jugadores que dominan la mano izquierda, particularmente los de mayor rango, sienten que la ubicación de la nota reflejada causada por el mod permite que su mano izquierda se utilice de manera más efectiva.
```

2023-05-24 02:13 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta los PPM y el AR. Como resultado, solo vale un multiplicador de 1.06x (a diferen
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta los PPM y el AR. Como resultado, solo vale un multiplicador de 1.06x (a diferencia del multiplicador de 1.12x para cualquier otro mod).
```

2023-05-24 02:13 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +- Cuando el mod Double Time está habilitado, los valores `Duración`, `BPM` y `Objetos` se colorean en rojo claro con los nuevos valores. (En la foto de abajo).
```suggestion
- Cuando el mod Double Time está habilitado, los valores `Duración`, `BPM` y `Objetos` se colorean en rojo claro con los nuevos valores. (Representado a continuación.)
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En todos los [modos de juego](/wiki/Game_mode) exceptuando [osu!taiko](/wiki/Game_mode/osu!taiko), el mod otorgará al jugador dos "vidas" adicionales durante una partida si la [barra de vida](/wiki/C
```suggestion
En todos los [modos de juego](/wiki/Game_mode)z exceptuando [osu!taiko](/wiki/Game_mode/osu!taiko), el mod otorgará al jugador dos «vidas» adicionales durante una partida si la [barra de vida](/wiki/Client/Interface/Health_bar) cae a cero. En el caso de que esto suceda, el juego se detendrá para rellenar lentamente la barra de vida hasta aproximadamente el 80 % y eliminar una «vida» del recuento de vidas del jugador. No se reproducirá ningún sonido durante este efecto.
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +Este evento de recarga se le indicará al jugador con el sonido listo (`readysound.wav`). Una vez que se haya terminado de rellenar la barra de vida, se volverá a señalar al jugador pero con el sonido
```suggestion
Este evento de recarga se le indicará al jugador con el sonido listo (`readysound.wav`). Una vez que se haya terminado de rellenar la barra de vida, se volverá a señalar al jugador pero con el sonido «go» (`gosound.wav`). Después de lo cual, el beatmap reanudará la reproducción y permitirá que el jugador continúe. Si al jugador no le quedan vidas y la barra de vida se ha reducido a cero, el juego fallará como normalmente hace.
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En [osu!](/wiki/Game_mode/osu!), el mod disminuye el [tamaño del círculo (CS)](/wiki/Client/Beatmap_editor/Song_Setup#circle-size), [tasa de aproximación (AR)](/wiki/Beatmap/Approach_rate), [dificult
```suggestion
En [osu!](/wiki/Game_mode/osu!), el mod disminuye el [tamaño del círculo (CS)](/wiki/Client/Beatmap_editor/Song_Setup#circle-size), la [tasa de aproximación (AR)](/wiki/Beatmap/Approach_rate), la [dificultad general (OD)](/wiki/Client/Beatmap_editor/Song_Setup#overall-difficulty) y el [drenaje de salud](/wiki/Client/Beatmap_editor/Song_Setup#hp-drain-rate) (HP) a la mitad.
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +![EZ gameplay](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-osu.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod habilitado (derecha) en osu!")
```suggestion
![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-osu.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod habilitado (derecha) en osu!")
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +*Nota: Los puntos mencionados anteriormente se desarrollan en "[Let's talk Easy Mod](https://osu.ppy.sh/community/forums/topics/56606)"*
```suggestion
*Nota: Los puntos mencionados anteriormente se desarrollan en «[Let's talk Easy Mod](https://osu.ppy.sh/community/forums/topics/56606)»*
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +*Nota: La cantidad de visitas que se requieren para terminar un [spinner](/wiki/Gameplay/Hit_object/Spinner) se reduce al valor de la OD.*
```suggestion
*Nota: La cantidad de golpes que se requieren para terminar un [spinner](/wiki/Gameplay/Hit_object/Spinner) se reduce al valor de la OD.*
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +A diferencia de otros modos de juego, usar el mod en osu!taiko reduce el requisito de puntuación de notas para ganar salud, haciendo que la barra de vida se llene mucho más rápido en lugar de agregar
```suggestion
A diferencia de otros modos de juego, usar el mod en osu!taiko reduce el requisito de puntuación de notas para ganar salud, haciendo que la barra de vida se llene mucho más rápido en lugar de agregar dos «vidas» adicionales, ya que es imposible fallar en medio de una canción en taiko.
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), los efectos son los mismos que en osu! con algunos paralelos y ajustes: todas las frutas caen más lentamente (aumento de AR), la cámara se "acerca" (aumento
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), los efectos son los mismos que en osu! con algunos paralelos y ajustes: todas las frutas caen más lentamente (aumento de AR), la cámara se «acerca» (aumento de CS), y se otorgan las dos «vidas» adicionales.
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- En el [multijugador](/wiki/Client/Interface/Multiplayer), el efecto de "vidas" no funcionará en [Tag Co-op or Tag Team Vs.](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs)
```suggestion
- En el [multijugador](/wiki/Client/Interface/Multiplayer), el efecto de «vidas» no funcionará en [Tag Co-op o Tag Team Vs.](/wiki/Client/Interface/Multiplayer#tag-co-op-/-tag-team-vs)
```

2023-05-24 02:25 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- El mod cancelará el mod [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock), y viceversa.
```suggestion
- El mod cancelará el mod [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock) y viceversa.
```

2023-05-27 12:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Al ver una repetición en la que se usa una vida extra, la animación de recarga de salud se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gamepl
```suggestion
- Al ver una repetición en la que se usa una vida extra, la animación de recarga de HP se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/Game_modifier/No_Fail) activado.
```

2023-05-27 12:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En todos los [modos de juego](/wiki/Game_mode)z exceptuando [osu!taiko](/wiki/Game_mode/osu!taiko), el mod otorgará al jugador dos «vidas» adicionales durante una partida si la [barra de vida](/wiki/
```suggestion
En todos los [modos de juego](/wiki/Game_mode) exceptuando [osu!taiko](/wiki/Game_mode/osu!taiko), el mod otorgará al jugador dos «vidas» adicionales durante una partida si la [barra de vida](/wiki/Client/Interface/Health_bar) cae a cero. En el caso de que esto suceda, el juego se detendrá para rellenar lentamente la barra de vida hasta aproximadamente el 80 % y eliminar una «vida» del recuento de vidas del jugador. No se reproducirá ningún sonido durante este efecto.
```

2023-05-27 12:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En [osu!mania](/wiki/Game_mode/osu!mania), los efectos son los mismos que en osu!taiko, excepto por el hecho de que las dos vidas adicionales *son* otorgadas al jugador, y que la velocidad y el las t
```suggestion
En [osu!mania](/wiki/Game_mode/osu!mania), los efectos son los mismos que en osu!taiko, excepto por el hecho de que se otorgan dos vidas adicionales al jugador, y que la velocidad del slider y el recuento de teclas predeterminado seguirán siendo los mismos.
```

2023-05-27 12:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En [osu!taiko](/wiki/Game_mode/osu!taiko), el mod reduce la [velocidad](/wiki/Gameplay/Hit_object/Slider/Slider_velocity), la dificultad general (OD) y el drenaje de HP a la mitad.
```suggestion
En [osu!taiko](/wiki/Game_mode/osu!taiko), el mod reduce la [velocidad del slider](/wiki/Gameplay/Hit_object/Slider/Slider_velocity), la dificultad general (OD) y el drenaje de HP a la mitad.
```

2023-05-27 12:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-06-03 08:05 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Al ver una repetición en la que se usa una vida extra, la animación de recarga de HP se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/
```suggestion
- Al ver una repetición en la que se usa una vida extra, la animación de recarga de salud se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/Game_modifier/No_Fail) activado.
```

2023-06-03 08:05 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +![EZ gameplay](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-catch.jpg "Comparación entre una partida normal (izquierda) frente a una partida con el mod activado (derecha) en osu!catch")
```suggestion
![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-catch.jpg "Comparación entre una partida normal (izquierda) frente a una partida con el mod activado (derecha) en osu!catch")
```

2023-06-03 08:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_Out/es.md
> +*No confundir con [Fade In (mod)](/wiki/Gameplay/Game_modifier/Fade_In) o [Hidden (mod)](/wiki/Gameplay/Game_modifier/Hidden).*
```suggestion
*No debe confundirse con [Fade In (mod)](/wiki/Gameplay/Game_modifier/Fade_In) o [Hidden (mod)](/wiki/Gameplay/Game_modifier/Hidden).*
```

2023-06-03 08:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +*No confundir con [Hidden (mod)](/wiki/Gameplay/Game_modifier/Hidden).*
```suggestion
*No debe confundirse con [Hidden (mod)](/wiki/Gameplay/Game_modifier/Hidden).*
```

2023-06-03 08:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +*No confundir con [Hidden (mod)](/wiki/Gameplay/Game_modifier/Hidden) o [Flashlight (mod)](/wiki/Gameplay/Game_modifier/Flashlight).*
```suggestion
*No debe confundirse con [Hidden (mod)](/wiki/Gameplay/Game_modifier/Hidden) o [Flashlight (mod)](/wiki/Gameplay/Game_modifier/Flashlight).*
```

2023-06-03 08:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/ScoreV2/es.md
> +*No confundir con [Score](/wiki/Gameplay/Score) o [ScoreV1](/wiki/Gameplay/Score/ScoreV1).*
```suggestion
*No debe confundirse con [Score](/wiki/Gameplay/Score) o [ScoreV1](/wiki/Gameplay/Score/ScoreV1).*
```

2023-06-03 08:09 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +*No confundir con [Fade In (mod)](/wiki/Gameplay/Game_modifier/Fade_In) o [Flashlight (mod)](/wiki/Gameplay/Game_modifier/Flashlight).*
```suggestion
*No debe confundirse con [Fade In (mod)](/wiki/Gameplay/Game_modifier/Fade_In) o [Flashlight (mod)](/wiki/Gameplay/Game_modifier/Flashlight).*
```

2023-06-04 18:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Al ver una repetición en la que se usa una vida extra, la animación de recarga de salud se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gamepl
This?

2023-06-04 19:05 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Al ver una repetición en la que se usa una vida extra, la animación de recarga de salud se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gamepl
```suggestion
- Al ver una repetición en la que se usa una vida extra, la animación de recarga de HP se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/Game_modifier/No_Fail) activado.
```

2023-06-04 20:02 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/xK/es.md
> +La siguiente tabla explica cómo se aplicará el multiplicador de puntuación en todas las modificaciones xK:
```suggestion
La siguiente tabla explica cómo se aplicará el multiplicador de puntuación en todos los mods xK:
```

2023-06-11 09:30 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +El mod **Fade In** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que aumenta la dificultad de [beatmaps](/wiki/Beatmap) haciendo que las notas
```suggestion
El mod **Fade In** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que aumenta la dificultad de los [beatmaps](/wiki/Beatmap) haciendo que las notas desaparezcan y luego aparezcan gradualmente a medida que se acercan a la barra de [juicio](/wiki/Gameplay/Judgement). De ahí el nombre.
```

2023-06-11 09:30 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +El tamaño de desvanecimiento solo se detiene cuando se alcanza un hito combinado de 500x (momento en el que cubre aproximadamente el 70% del campo de juego). Si un combo se interrumpe en algún moment
```suggestion
El tamaño de desvanecimiento solo se detiene cuando se alcanza un hito de combo de 500x (momento en el que cubre aproximadamente el 70 % del campo de juego). Si un combo se interrumpe en algún momento, el tamaño de desvanecimiento volverá a ser 0x el tamaño del combo (que es aproximadamente el 20 % del campo de juego).
```

2023-06-11 09:30 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +![Comparaciones de gameplay con FI](/wiki/Gameplay/Game_modifier/Fade_In/img/FI-combo-comparison-mania.jpg "Jugabilidad con el mod Fade In en combo 89x (arriba a la izquierda), en combo 332x (arriba-
```suggestion
![Comparaciones de jugabilidad con FI](/wiki/Gameplay/Game_modifier/Fade_In/img/FI-combo-comparison-mania.jpg "Jugabilidad con el mod Fade In en combo 89x (arriba a la izquierda), en combo 332x (arriba-centro), en combo 513x (arriba a la derecha /abajo a la izquierda), y en combo 900x (abajo a la derecha) en osu!mania")
```

2023-06-11 09:30 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-06-11 09:30 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +- Tecla de atajo predeterminada: `F`
```suggestion
- Tecla de acceso directo predeterminada: `F`
```

2023-06-11 09:30 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_Out/es.md
> +- Tecla de método abreviado predeterminada: `F` `F` o `Shift`+`F`
```suggestion
- Tecla de acceso directo predeterminada: `F` `F` o `Shift`+`F`
```

2023-06-11 09:30 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +- Descripción: `uguuuuuuuuu`
```suggestion
- Descripción: `uguuuuuuuu`
```

2023-06-11 09:33 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Perfect/es.md
> +- Tecla de método abreviado predeterminada: `S` `S` o `Shift`+`S`
```suggestion
- Tecla de acceso directo predeterminada: `S` `S` o `Shift`+`S`
```

2023-06-11 09:33 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Relax/es.md
> +- Tecla de atajo predeterminada: `Z`
```suggestion
- Tecla de acceso directo predeterminada: `Z`
```

2023-06-11 09:33 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Spun_Out/es.md
> +- Tecla de atajo predeterminada: `C`
```suggestion
- Tecla de acceso directo predeterminada: `C`
```

2023-06-11 09:33 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/xK/es.md
> +- Tecla de método abreviado predeterminada: `Z` (cada clic o pulsación de tecla pasa de 4K a 9K, luego vuelve a 1K hasta 3K antes de desactivarse)
```suggestion
- Tecla de acceso directo predeterminada: `Z` (cada clic o pulsación de tecla pasa de 4K a 9K, luego vuelve a 1K hasta 3K antes de desactivarse)
```

2023-06-20 22:11 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +A pesar de usar solo un eje, el tamaño más grande de las frutas y la velocidad de caída más lenta pueden hacer que se agrupen, creando los mismos problemas comunes con dificultad que en osu!.
```suggestion
A pesar de usar solo un eje, el tamaño más grande de las frutas y la velocidad de caída más lenta pueden hacer que se agrupen, creando los mismos problemas comunes con la dificultad que en osu!.
```

2023-06-20 22:20 UTC, agatemosu reviewed
https://github.com/ppy/osu-wiki/pull/9535

2023-06-20 22:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +El [multiplicador de puntuación](/wiki/Gameplay/Game_modifier/Score_multiplier) permanece igual que con el modo Double Time habilitado, y el beatmap en sí no se ve afectado más allá de lo que hará el
```suggestion
El [multiplicador de puntuación](/wiki/Gameplay/Game_modifier/Mod_multiplier) permanece igual que con el modo Double Time habilitado, y el beatmap en sí no se ve afectado más allá de lo que hará el modo Double Time.
```

2023-07-04 18:31 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +En [osu!taiko](/wiki/Game_mode/osu!taiko), el margen de acierto se reduce considerablemente cuando se habilita el mod Double Time debido a la dificultad general ya estricta de osu!taiko junto con los
```suggestion
En [osu!taiko](/wiki/Game_mode/osu!taiko), la tolerancia de acierto se reduce considerablemente cuando se habilita el mod Double Time debido a la dificultad general ya estricta de osu!taiko junto con los golpes de los sliders considerablemente más difíciles de golpear. Debido a esto, el mod Double Time es ampliamente considerado como el mod más difícil en osu!taiko y rara vez se usa.
```

2023-07-04 18:31 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +Aunque este mod aumenta en gran medida la blandura del hyperdash, hacer que las frutas requieran hyperdashes que son casi imposibles de atrapar en algunos casos.
```suggestion
Aunque este mod aumenta en gran medida la tolerancia del hyperdash, hacer que las frutas requieran hyperdashes que son casi imposibles de atrapar en algunos casos.
```

2023-07-04 18:42 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +![Comparaciones de jugabilidad con FI](/wiki/Gameplay/Game_modifier/Fade_In/img/FI-combo-comparison-mania.jpg "Jugabilidad con el mod Fade In en combo 89x (arriba a la izquierda), en combo 332x (arri
```suggestion
![Comparaciones de jugabilidad con FI](/wiki/Gameplay/Game_modifier/Fade_In/img/FI-combo-comparison-mania.jpg "Jugabilidad con el mod Fade In en combo 89x (arriba a la izquierda), en combo 332x (arriba centro), en combo 513x (arriba a la derecha/abajo a la izquierda), y en combo 900x (abajo a la derecha) en osu!mania")
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +En [osu!mania](/wiki/Game_mode/osu!mania), el área visible está restringida a una barra horizontal relativamente delgada en el centro de la pista, mientras que todo lo demás está obstruido a la vista
```suggestion
En [osu!mania](/wiki/Game_mode/osu!mania), el área visible está restringida a una barra horizontal relativamente delgada en el centro de la pista, mientras que todo lo demás está obstruido a la vista. En ese sentido, el mod Flashlight podría considerarse como el mod Hidden y el mod [Fade In](/wiki/Gameplay/Game_modifier/Fade_In) combinados. (Es decir, sin los tamaños cambiantes del área visible.)
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +- Si se pasa un beatmap con una calificación S o SS con el mod Flashlight habilitado, el beatmap otorgará la variante plateada del grado en su lugar.
```suggestion
- Si se pasa un beatmap con un grado S o SS con el mod Flashlight activado, el beatmap otorgará la variante plateada del grado en su lugar.
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Autopilot/es.md
> +El mod **Autopilot** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para el modo de juego [osu!](/wiki/Game_mode/osu!) que tomará el control del movimiento del cursor y se moverá sistemát
```suggestion
El mod **Autopilot** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para el modo de juego [osu!](/wiki/Game_mode/osu!) que tomará el control del movimiento del cursor y se moverá sistemáticamente a el centro exacto del próximo [objeto](/wiki/Gameplay/Hit_object), dejando el toque al jugador. Durante una partida con el mod Autopilot activado, el jugador no podrá mover el cursor, a menos que esté en la pantalla de pausa.
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +- Cuando el mod Double Time está habilitado, los valores `Duración`, `BPM` y `Objetos` se colorean en rojo claro con los nuevos valores. (Representado a continuación.)
```suggestion
- Cuando el mod Double Time está activado, los valores `Duración`, `BPM` y `Objetos` se colorean en rojo claro con los nuevos valores. (Representado a continuación.)
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-osu.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod habilitado (derecha) en osu!")
```suggestion
![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-osu.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod activado (derecha) en osu!")
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_In/es.md
> +- Si se pasa un beatmap con un grado S o SS con el modo Fade In habilitado, dicho beatmap otorgará la variante plateada de ese grado en su lugar.
```suggestion
- Si se pasa un beatmap con un grado S o SS con el modo Fade In activado, dicho beatmap otorgará la variante plateada de ese grado en su lugar.
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +- El mod Flashlight fue originalmente objeto de una gran controversia con respecto a la implementación en 2010 por ser el mod más fácil de hackear; posteriormente obligando a que el mod no se clasifi
```suggestion
- El mod Flashlight fue originalmente objeto de una gran controversia con respecto a la implementación en 2010 por ser el mod más fácil de jaquear; posteriormente obligando a que el mod no se clasificara hasta que se implementara un parche para cubrir la brecha de implementación del mod Flashlight.
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +![HD gameplay osu!](/wiki/Gameplay/Game_modifier/Hidden/img/HD-osu.jpg "¡Juego de osu! con el mod Hidden habilitado")
```suggestion
![Jugabilidad de HD en osu!](/wiki/Gameplay/Game_modifier/Hidden/img/HD-osu.jpg "Jugabilidad de osu! con el mod Hidden activado")
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +- Si se pasa un beatmap con un rango S o SS con el mod Hidden habilitado, el beatmap otorgará la variante plateada del grado en su lugar.
```suggestion
- Si se pasa un beatmap con un grado S o SS con el mod Hidden activado, el beatmap otorgará la variante plateada del grado en su lugar.
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +El [multiplicador de puntuación](/wiki/Gameplay/Game_modifier/Mod_multiplier) permanece igual que con el modo Double Time habilitado, y el beatmap en sí no se ve afectado más allá de lo que hará el m
```suggestion
El [multiplicador de puntuación](/wiki/Gameplay/Game_modifier/Mod_multiplier) permanece igual que con el modo Double Time activado, y el beatmap en sí no se ve afectado más allá de lo que hará el modo Double Time.
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Relax/es.md
> +En [osu!](/wiki/Game_mode/osu!), habilitar el modo Relax solo requiere que el jugador desplace el cursor sobre [golpear objetos](/wiki/Gameplay/Hit_object); todos los objetos golpeados serán tocados
```suggestion
En [osu!](/wiki/Game_mode/osu!), activar el mod Relax solo requiere que el jugador desplace el cursor sobre [objetos](/wiki/Gameplay/Hit_object); todos los objetos serán tocados automáticamente por osu!. El mod hace que sea imposible fallar en el beatmap en todos los modos de juego.
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/ScoreV2/es.md
> +*Nota: Habilitar el mod ScoreV2 resultará en una partida sin clasificación.*\
```suggestion
*Nota: Activar el mod ScoreV2 resultará en una partida sin clasificación.*\
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +- Omitir una nota con el mod Sudden Death habilitado dará como resultado que aparezca una figura extra grande en [osu!](/wiki/Game_mode/osu!).
```suggestion
- Omitir una nota con el mod Sudden Death activado dará como resultado que aparezca una figura extra grande en [osu!](/wiki/Game_mode/osu!).
```

2023-07-04 19:15 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +- Cuando se juega con el mod Sudden Death habilitado en osu!, hay casos raros en los que el jugador puede sobrevivir de un drenaje de barra de vida completo por romper el combo. Si el jugador logró p
```suggestion
- Cuando se juega con el mod Sudden Death activado en osu!, hay casos raros en los que el jugador puede sobrevivir de un drenaje de barra de vida completo por romper el combo. Si el jugador logró preservar al menos una pizca de salud haciendo que un control deslizante se active en un margen de tiempo muy corto justo después de que se rompió el combo y antes de que la barra de vida se agote por completo, el jugador puede continuar jugando el beatmap tal como está y no se impondrá una gran figura de pérdida.
```

2023-07-04 19:19 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Relax/es.md
> +Junto con esto, el modo Relax también brindará un tiempo más indulgente para recolectar los ticks del control deslizante durante los redobles de tambor, mientras que los dendens se pueden borrar con
```suggestion
Junto con esto, el modo Relax también brindará un tiempo más tolerante para recolectar las marcas del sldier durante los redobles de tambor, mientras que los dendens se pueden borrar con cualquier secuencia de colores en lugar de alternar la secuencia de colores. La mascota animada también será eliminada.
```

2023-07-04 19:19 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +El mod **Sudden Death** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que hace que los jugadores fallen en un [beatmap](/wiki/Beatmap) al perder un [objeto de impacto](/wiki/Gameplay/Hit
```suggestion
El mod **Sudden Death** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que hace que los jugadores fallen en un [beatmap](/wiki/Beatmap) al perder un [objeto de impacto](/wiki/Gameplay/Hit_object) o fallando al recolectar una marca del slider. Esto es útil para los jugadores que buscan un [combo completo (FC)](/wiki/Gameplay/Full_combo). Sin embargo, existe cierto debate sobre si el uso del mod Sudden Death o el hecho de volver a intentarlo en el primer [combobreak](/wiki/Gameplay/Judgement/Combobreak) es útil o dañino para los jugadores que quieren mejorar rápidamente.
```

2023-07-04 19:19 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +- No se pudo recopilar una marca de control deslizante (solo modo de juego osu!)
```suggestion
- No se pudo recopilar una marca del slider (solo modo de juego osu!)
```

2023-07-04 19:19 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +- No retener/recoger en la ruta del control deslizante vacío
```suggestion
- No retener/recoger en la ruta del slider vacío
```

2023-07-04 19:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +En [osu!taiko](/wiki/Game_mode/osu!taiko), la canción y BPM ralentizados hacen que las notas se vuelvan muy densas debido a la disminución del AR. Sin embargo, debido a la forma en que se calculan lo
```suggestion
En [osu!taiko](/wiki/Game_mode/osu!taiko), la canción y PPM ralentizados hacen que las notas se vuelvan muy densas debido a la disminución del AR. Sin embargo, debido a la forma en que se calculan los dendens en osu!taiko, ahora requieren más golpes para despejarse y hacen que otorguen un **valor total más alto que sin el mod** porque los hits de los dendens no se ven afectados por el [multiplicador de puntuacion](/wiki/Gameplay/Game_modifier/Mod_multiplier).
```

2023-07-04 19:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), el BPM y la velocidad del receptor son ralentizados por el mismo factor como en otros modos. Todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [drops](/w
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), el PPM y la velocidad del receptor son ralentizados por el mismo factor como en otros modos. Todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [drops](/wiki/Gameplay/Hit_object/Juice_stream#gota), [droplets](/wiki/Gameplay/Hit_object/Juice_stream#gotita) y [bananas](/wiki/Gameplay/Hit_object/Banana) quedan intactos.
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +![Changed values](/wiki/Gameplay/Game_modifier/Half_Time/img/GM_HT.jpg "Screenshot of beatmap values being changed by the Half Time mod")
```suggestion
![Valores cambiados](/wiki/Gameplay/Game_modifier/Half_Time/img/GM_HT.jpg "Captura de pantalla de los valores del beatmap cambiados por el mod Half Time")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +![HR gameplay](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-osu.jpg "Comparación de una play regular (izquierda) vs una play que tiene el mod Hard Rock activado (derecha) en osu!")
```suggestion
![Jugabilidad de HR](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-osu.jpg "Comparación de una jugada regular (izquierda) vs una jugada que tiene el mod Hard Rock activado (derecha) en osu!")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +![HR gameplay catch](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-catch.jpg "Comparacion de una play regular (izquierda) vs una play que tiene el mod Hard Rock activado (derecha) en osu!c
```suggestion
![Jugabilidad de HR en catch](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-catch.jpg "Comparacion de una jugada regular (izquierda) contra una jugada que tiene el mod Hard Rock activado (derecha) en osu!catch")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +![HD gameplay taiko](/wiki/Gameplay/Game_modifier/Hidden/img/HD-taiko.jpg "Gameplay de osu!taiko con el modo Hidden activado")
```suggestion
![Jugabilidad de HD en taiko](/wiki/Gameplay/Game_modifier/Hidden/img/HD-taiko.jpg "Jugabilidad de osu!taiko con el modo Hidden activado")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +![HD gameplay catch](/wiki/Gameplay/Game_modifier/Hidden/img/HD-catch.jpg "Juego de osu!catch con el mod Hidden activado")
```suggestion
![Jugabilidad de HD en catch](/wiki/Gameplay/Game_modifier/Hidden/img/HD-catch.jpg "Jugabilidad de osu!catch con el mod Hidden activado")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +![HD gameplay mania](/wiki/Gameplay/Game_modifier/Hidden/img/HD-combo-comparison-mania.jpg "Gameplay con el mod Hidden en combo 91x (arriba a la izquierda), en combo 326x (arriba-centro), en combo 51
```suggestion
![Jugabilidad de HD en mania](/wiki/Gameplay/Game_modifier/Hidden/img/HD-combo-comparison-mania.jpg "Jugabilidad con el mod Hidden en combo 91x (arriba a la izquierda), en combo 326x (arriba-centro), en combo 516x (arriba a la derecha/ abajo a la izquierda), y en combo 900x (abajo a la derecha) en osu!mania")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +![Juego MR](/wiki/Gameplay/Game_modifier/Mirror/img/MR-comparison-mania.jpg "Comparación entre un gameplay normal (izquierda) y un gameplay con el modo Mirror activado (derecha) en osu!mania")
```suggestion
![Jugabilidad de MR](/wiki/Gameplay/Game_modifier/Mirror/img/MR-comparison-mania.jpg "Comparación entre una jugada normal (izquierda) y una jugada con el mod Mirror activado (derecha) en osu!mania")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Random/es.md
> +![RD gameplay mania](/wiki/Gameplay/Game_modifier/Random/img/RD-comparison-mania.jpg "Comparacion entre una play normal (izquierda) vs una play con el mod Random activado (derecha) en osu!mania")
```suggestion
![Jugabilidad de RD en mania](/wiki/Gameplay/Game_modifier/Random/img/RD-comparison-mania.jpg "Comparacion entre una jugada normal (izquierda) contra una jugada con el mod Random activado (derecha) en osu!mania")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +![TP Gameplay](img/TP-gameplay.jpg "Gameplay de osu! con el mod Target Practice activado")
```suggestion
![Jugabilidad de TP](img/TP-gameplay.jpg "Jugabilidad de osu! con el mod Target Practice activado")
```

2023-07-04 19:26 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +*Nota: Usando este mod en osu!mania resultará en una play sin clasificar.*
```suggestion
*Nota: Usando este mod en osu!mania resultará en una jugada sin clasificar.*
```

2023-07-04 19:34 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Video/es.md
> +La funcionalidad del mod se reemplazó con una opción en la [configuración visual](/wiki/Client/Interface/Visual_settings) y, por lo tanto, el ícono y su mod ya no se usan.
```suggestion
La funcionalidad del mod se reemplazó con una opción en la [configuración visual](/wiki/Client/Interface/Visual_settings) y, por lo tanto, el icono y su mod ya no se usan.
```

2023-07-04 19:41 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Video/es.md
> +El mod **No Video** era un [modificador de juego](/wiki/Gameplay/Game_modifier) que permitía a los jugadores desactivar el video de fondo de un [beatmap](/wiki/Beatmap). Esto se usó para ayudar a mej
```suggestion
El mod **No Video** era un [modificador de juego](/wiki/Gameplay/Game_modifier) que permitía a los jugadores desactivar el vídeo de fondo de un [beatmap](/wiki/Beatmap). Esto se usó para ayudar a mejorar la velocidad de fotogramas y el rendimiento del juego.
```

2023-07-04 19:41 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Video/es.md
> +*Nota: este mod ya no está disponible para su uso.*
```suggestion
*Nota: Este mod ya no está disponible para su uso.*
```

2023-07-04 19:41 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +*Nota: este mod ya no está disponible para su uso.*
```suggestion
*Nota: Este mod ya no está disponible para su uso.*
```

2023-07-04 19:41 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +*Nota: el mod Co-op no penaliza los beatmaps específicos de osu!mania.*
```suggestion
*Nota: El mod Co-op no penaliza los beatmaps específicos de osu!mania.*
```

2023-07-04 19:41 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Fade_Out/es.md
> +*Nota: este mod ya no está disponible para su uso.*
```suggestion
*Nota: Este mod ya no está disponible para su uso.*
```

2023-07-04 19:41 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +*Nota: el mod Target Practice solo es accesible en la version `Cutting Edge` del juego.*
```suggestion
*Nota: El mod Target Practice solo es accesible en la version `Cutting Edge` del juego.*
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Al ver una repetición en la que se usa una vida extra, la animación de recarga de HP se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/
```suggestion
- Al ver una repetición en la que se usa una vida extra, la animación de recarga de salud se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/Game_modifier/No_Fail) activado.
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +![Jugabilidad de HR](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-osu.jpg "Comparación de una jugada regular (izquierda) vs una jugada que tiene el mod Hard Rock activado (derecha) en osu
```suggestion
![Jugabilidad de HR](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-osu.jpg "Comparación de una partida regular (izquierda) contra una partida que tiene el mod Hard Rock activado (derecha) en osu!")
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +![Jugabilidad de Auto vs. Cinema](/wiki/Gameplay/Game_modifier/Cinema/img/CM-comparison.jpg "Comparación del mod Auto (izquierda) con el mod Cinema (derecha)")
```suggestion
![Jugabilidad de Auto contra Cinema](/wiki/Gameplay/Game_modifier/Cinema/img/CM-comparison.jpg "Comparación del mod Auto (izquierda) con el mod Cinema (derecha)")
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +*Nota: Activar el mod Auto hará que la jugada no se clasifique y no se guardará en las tablas de clasificación locales.*
```suggestion
*Aviso: Activar el mod Auto hará que la partida no se clasifique y no se guardará en las tablas de clasificación locales.*
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +En [osu!mania](/wiki/Game_mode/osu!mania), el mod Auto intentará una jugada perfecta, pero es posible que no detecte objetos en la misma columna que se superponen o se colocan a menos de 1 ms de dist
```suggestion
En [osu!mania](/wiki/Game_mode/osu!mania), el mod Auto intentará una partida perfecta, pero es posible que no detecte objetos en la misma columna que se superponen o se colocan a menos de 1 ms de distancia entre sí.
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Autopilot/es.md
> +*Aviso: Activar el mod Autopilot hará que la jugada no se clasifique y no se guardará en las tablas de clasificación locales.*
```suggestion
*Aviso: Activar el mod Autopilot hará que la partida no se clasifique y no se guardará en las tablas de clasificación locales.*
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +*Nota: Activar el mod Cinema resultará en una jugada sin clasificar.*
```suggestion
*Nota: Activar el mod Cinema resultará en una partida sin clasificar.*
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +El mod **Cinema** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo permitir a los jugadores simplemente relajarse y ver el vídeo o los storyboards de un beatmap sin
```suggestion
El mod **Cinema** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo permitir a los jugadores simplemente relajarse y ver el vídeo o los storyboards de un beatmap sin la aparición de ningún [objeto](/wiki/Gameplay/Hit_object). Esto resultará en una partida usando el mod [Auto](/wiki/Gameplay/Game_modifier/Auto), pero **solo se mostrarán el fondo y el storyboard**.
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +![Jugabilidad de FL en osu!](/wiki/Gameplay/Game_modifier/Flashlight/img/FL-comparison-osu.jpg "Comparación entre una jugada con el mod Flashlight activado en combo 13x (arriba centro), combo 100x (a
```suggestion
![Jugabilidad de FL en osu!](/wiki/Gameplay/Game_modifier/Flashlight/img/FL-comparison-osu.jpg "Comparación entre una partida con el mod Flashlight activado en combo 13x (arriba centro), combo 100x (abajo a la izquierda) y combo 200x (abajo a la derecha)")
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +![Jugabilidad de HR en catch](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-catch.jpg "Comparacion de una jugada regular (izquierda) contra una jugada que tiene el mod Hard Rock activado (
```suggestion
![Jugabilidad de HR en catch](/wiki/Gameplay/Game_modifier/Hard_Rock/img/HR-comparison-catch.jpg "Comparacion de una partida regular (izquierda) contra una partida que tiene el mod Hard Rock activado (derecha) en osu!catch")
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +![Jugabilidad de MR](/wiki/Gameplay/Game_modifier/Mirror/img/MR-comparison-mania.jpg "Comparación entre una jugada normal (izquierda) y una jugada con el mod Mirror activado (derecha) en osu!mania")
```suggestion
![Jugabilidad de MR](/wiki/Gameplay/Game_modifier/Mirror/img/MR-comparison-mania.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod Mirror activado (derecha) en osu!mania")
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Random/es.md
> +![Jugabilidad de RD en mania](/wiki/Gameplay/Game_modifier/Random/img/RD-comparison-mania.jpg "Comparacion entre una jugada normal (izquierda) contra una jugada con el mod Random activado (derecha) e
```suggestion
![Jugabilidad de RD en mania](/wiki/Gameplay/Game_modifier/Random/img/RD-comparison-mania.jpg "Comparacion entre una partida normal (izquierda) contra una partida con el mod Random activado (derecha) en osu!mania")
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Relax/es.md
> +*Aviso: Activar el modo Relax hará que la jugada no se clasifique y no se guardará en las tablas de clasificación locales.*
```suggestion
*Aviso: Activar el modo Relax hará que la partida no se clasifique y no se guardará en las tablas de clasificación locales.*
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +*Nota: Activar el mod Target Practice resultará en una jugada sin clasificar.*
```suggestion
*Nota: Activar el mod Target Practice resultará en una partida sin clasificar.*
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +Durante una jugada con el mod Target Practice activado, a los jugadores se les presentará un conjunto de "objetivos" que aumentan lentamente en tamaño y brillo. Luego se espera que el jugador toque o
```suggestion
Durante una partida con el mod Target Practice activado, a los jugadores se les presentará un conjunto de "objetivos" que aumentan lentamente en tamaño y brillo. Luego se espera que el jugador toque o haga clic en los objetivos cuando estén en su máximo brillo y tamaño y sea el momento adecuado. Se reproducirá un metrónomo consistente en el fondo para indicar a los jugadores cuándo deben tocar el objetivo.
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +- Al fallar una jugada con el mod Target Practice activado, el jugador será llevado a la pantalla de clasificación, en lugar de a una pantalla de falla.
```suggestion
- Al fallar una partida con el mod Target Practice activado, el jugador será llevado a la pantalla de clasificación, en lugar de a una pantalla de fallado.
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +- El mod Target Practice usará los [combo colors](/wiki/Beatmapping/Combo_colour) que están marcados en la carpeta [skin.ini](/wiki/Skinning/skin.ini) actual del jugador.
```suggestion
- El mod Target Practice usará los [colores de combo](/wiki/Beatmapping/Combo_colour) que están marcados en la carpeta [skin.ini](/wiki/Skinning/skin.ini) actual del jugador.
```

2023-07-13 11:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +*Nota: Usando este mod en osu!mania resultará en una jugada sin clasificar.*
```suggestion
*Nota: Usando este mod en osu!mania resultará en una partida sin clasificar.*
```

2023-07-13 12:04 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +![Comparación del juego con Co-op en un beatmap de osu!mania específico](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-mania-specific-beatmap.jpg "Comparación entre un gameplay normal (izquier
```suggestion
![Comparación del juego con Co-op en un beatmap de osu!mania específico](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-mania-specific-beatmap.jpg "Comparación entre una partida normal (izquierda) contra otra partida con el mod Co-op activado (derecha) en un beatmap específico de osu!mania")
```

2023-07-13 12:05 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +![Comparación del juego con Co-op en un beatmap de osu!mania convertido](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-converted-beatmap.jpg "Comparación entre un gameplay normal (izquierda) y
```suggestion
![Comparación del juego con Co-op en un beatmap de osu!mania convertido](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-converted-beatmap.jpg "Comparación entre una partida normal (izquierda) y otra con el mod Co-op activado (derecha) en un beatmap de osu!mania convertido")
```

2023-07-21 19:56 UTC, agatemosu requested changes

2023-07-21 19:56 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-07-21 19:58 UTC, agatemosu requested changes

2023-07-21 19:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-07-21 19:58 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/ScoreV2/es.md
> +*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*
```suggestion
*Para una lista completa de mods, véase: [Modificador de juego](/wiki/Gameplay/Game_modifier)*\
```

2023-07-30 09:10 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Random/es.md
> +El mod **Random** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que apunta a los jugadores a una interesante y divertida experiencia al hacer
```suggestion
El mod **Random** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que apunta a los jugadores a una interesante y divertida experiencia al hacer aleatoria la posicion de las teclas cada que se juega el beatmap. El mod Random no cambiara la longitud de las notas.
```

2023-07-30 09:10 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Random/es.md
> +![Jugabilidad de RD en mania](/wiki/Gameplay/Game_modifier/Random/img/RD-comparison-mania.jpg "Comparacion entre una partida normal (izquierda) contra una partida con el mod Random activado (derecha)
```suggestion
![Jugabilidad de RD en mania](/wiki/Gameplay/Game_modifier/Random/img/RD-comparison-mania.jpg "Comparación entre una partida normal (izquierda) contra una partida con el mod Random activado (derecha) en osu!mania")
```

2023-07-30 09:11 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Spun_Out/es.md
> +El mod **Spun Out** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo ayudar a los jugadores de [osu!](/wiki/Game_mode/osu!) a girar con éxito las ruletas en un [beat
```suggestion
El mod **Spun Out** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo ayudar a los jugadores de [osu!](/wiki/Game_mode/osu!) a girar con éxito los spinners en un [beatmap](/wiki/Beatmap). El mod borrará todos los botones giratorios del beatmap a exactamente 286.48 giros por minuto (SPM) en el sentido de las agujas del reloj, que es 3/5 de los 477.26 SPM de Auto.
```

2023-07-30 09:11 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Spun_Out/es.md
> +Los giradores se desactivarán y el jugador no podrá girar para aumentar el valor de SPM.
```suggestion
Los spinners se desactivarán y el jugador no podrá girar para aumentar el valor de SPM.
```

2023-07-30 09:12 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Spun_Out/es.md
> +El mod **Spun Out** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo ayudar a los jugadores de [osu!](/wiki/Game_mode/osu!) a girar con éxito las ruletas en un [beat
```suggestion
El mod **Spun Out** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que tiene como objetivo ayudar a los jugadores de [osu!](/wiki/Game_mode/osu!) a girar con éxito los spinners en un [beatmap](/wiki/Beatmap). El mod completará todos los spinners del beatmap a exactamente 286.48 giros por minuto (SPM) en el sentido de las agujas del reloj, que es 3/5 de los 477.26 SPM de Auto.
```

2023-07-30 09:16 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +![Comparación del juego con Co-op en un beatmap de osu!mania específico](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-mania-specific-beatmap.jpg "Comparación entre una partida normal (izquier
me olvidé de este
```suggestion
![Comparación del juego con Co-op en un beatmap específico de osu!mania](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-mania-specific-beatmap.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod Co-op activado (derecha) en un beatmap específico de osu!mania")
```

2023-07-30 09:16 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +![Comparación del juego con Co-op en un beatmap convertido de osu!mania](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-converted-beatmap.jpg "Comparación entre una partida normal (izquierda) y
```suggestion
![Comparación del juego con Co-op en un beatmap convertido a osu!mania](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-converted-beatmap.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod Co-op activado (derecha) en un beatmap convertido a osu!mania")
```

2023-07-30 09:17 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +[osu!mania]: /wiki/shared/mode/mania.png "osu!manía"
LO SABÍA AJAJAJ
```suggestion
[osu!mania]: /wiki/shared/mode/mania.png "osu!mania"
```

2023-07-30 09:19 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +El mod **Hidden** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que aumenta la dificultad de los beatmaps al eliminar los círculos de aproximación y hacer que los [objetos de impacto](/w
```suggestion
El mod **Hidden** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que aumenta la dificultad de los beatmaps al eliminar los círculos de aproximación y hacer que los [objetos](/wiki/Gameplay/Hit_object) desaparezcan después que aparece en la pantalla.
```

2023-07-30 09:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +El mod **Target Practice** es un [modificador de juego](/wiki/Gameplay/Game_modifier) experimental que elimina todos los [objetos de impacto](/wiki/Gameplay/Hit_object) asignados y los reemplaza con
```suggestion
El mod **Target Practice** es un [modificador de juego](/wiki/Gameplay/Game_modifier) experimental que elimina todos los [objetos](/wiki/Gameplay/Hit_object) asignados y los reemplaza con un conjunto simplificado y consistente de «objetivos».
```

2023-07-30 09:20 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +Durante una partida con el mod Target Practice activado, a los jugadores se les presentará un conjunto de "objetivos" que aumentan lentamente en tamaño y brillo. Luego se espera que el jugador toque
```suggestion
Durante una partida con el mod Target Practice activado, a los jugadores se les presentará un conjunto de «objetivos» que aumentan lentamente en tamaño y brillo. Luego se espera que el jugador toque o haga clic en los objetivos cuando estén en su máximo brillo y tamaño y sea el momento adecuado. Se reproducirá un metrónomo consistente en el fondo para indicar a los jugadores cuándo deben tocar el objetivo.
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Flashlight/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Nightcore/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Perfect/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/ScoreV2/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Sudden_Death/es.md
> +### Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:22 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Target_Practice/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-07-30 09:32 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Fail/es.md
> +El mod **No Fail** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que previene al jugador de perder en [beatmaps](/wiki/Beatmap). Activando el mod No Fail hace al jugador incapaz de perde
```suggestion
El mod **No Fail** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que previene al jugador de perder en [beatmaps](/wiki/Beatmap). Activando el mod No Fail hace al jugador incapaz de perder en un [beatmap](/wiki/Beatmap) incluso si la [barra de vida](/wiki/Client/Interface/Health_bar) termina en cero. Aunque, si el jugador no hizo ninguna puntuación durante el beatmap, el juego *fallara* en su lugar.
```

2023-07-30 09:32 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Fail/es.md
> +A partir del 16 de enero del 2021, el mod No Fail incurrirá en una cierta multa en el monto de [puntos de rendimiento](/wiki/Performance_points) que el jugador gana del juego dependiendo de cuantos f
```suggestion
A partir del 16 de enero de 2021, el mod No Fail incurrirá en una cierta multa en la cantidad de [puntos de rendimiento](/wiki/Performance_points) que el jugador ganará de la jugada dependiendo de cuantos fallos obtuvo. Iniciando de un valor base de 1.0x (100 %), cada fallo disminuirá el multiplicador de puntos de rendimiento en un -0.02x (0.5 %) hasta un máximo de 0.9x (90 %). 
```

2023-07-30 09:36 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Al ver una repetición en la que se usa una vida extra, la animación de recarga de HP se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/
```suggestion
- Al ver una repetición en la que se usa una vida extra, la animación de recarga de dalud se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/Game_modifier/No_Fail) activado.
```

2023-07-30 09:36 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Al ver una repetición en la que se usa una vida extra, la animación de recarga de HP se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/
```suggestion
- Al ver una repetición en la que se usa una vida extra, la animación de recarga de salud se ignorará y la repetición continuará como si el jugador estuviera jugando con el mod [No Fail](/wiki/Gameplay/Game_modifier/No_Fail) activado.
```

2023-07-30 09:40 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +El mod **Mirror** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que intenta ayudar a los jugadores zurdos a jugar [beatmaps](/wiki/Beatmap) qu
```suggestion
El mod **Mirror** es un [modificador de juego](/wiki/Gameplay/Game_modifier) para [osu!mania](/wiki/Game_mode/osu!mania) que intenta ayudar a los jugadores zurdos a jugar [beatmaps](/wiki/Beatmap) que fueron mapeados originalmente con patrones para diestros en mente. El mod logra esto al reflejar las notas a través del eje *y* que corre por la mitad del teclado de osu!mania, es decir, «refleja» las notas. Específicamente, la duplicación de notas es la siguiente:
```

2023-07-30 09:40 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +- El mod Mirror se agregó en septiembre de 2019, en respuesta a una [solicitud de función](https://osu.ppy.sh/community/forums/topics/956618) del usuario [Kamuy](https://osu.ppy.sh/usuarios/7439226).
```suggestion
- El mod Mirror se agregó en septiembre de 2019, en respuesta a una [solicitud de función](https://osu.ppy.sh/community/forums/topics/956618) del usuario [Kamuy](https://osu.ppy.sh/users/7439226).
```

2023-07-30 09:40 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Mirror/es.md
> +- El mod Mirror es el único mod de juego en la categoría "Especial" que no afecta la cantidad de [puntos de rendimiento (pp)](/wiki/Performance_points) ni [puntuación](/wiki/Gameplay/Score) que gana
```suggestion
- El mod Mirror es el único mod de juego en la categoría «Especial» que no afecta la cantidad de [puntos de rendimiento (pp)](/wiki/Performance_points) ni [puntuación](/wiki/Gameplay/Score) que gana un jugador, sin dejar de ser clasificable.
```

2023-08-03 16:49 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- Descripcion: `Menos velocidad.`
```suggestion
- Descripción: `Menos velocidad.`
```

2023-08-03 16:49 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +*Nota: El metodo usado para ralentizar la cancion podria causar que el sonido suene raro o robotico.*
```suggestion
*Nota: El metodo usado para ralentizar la canción podria causar que el sonido suene raro o robotico.*
```

2023-08-03 16:50 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +El mod **Half Time** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que ralentiza el la velocidad general del [beatmap](/wiki/Beatmap) (BPM) a un 75 % del original, incrementa la longitud
```suggestion
El mod **Half Time** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que ralentiza el la velocidad general del [beatmap](/wiki/Beatmap) (PPM) a un 75 % del original, incrementa la longitud de la cancion en un 33 %, y disminuye la [velocidad de aproximacion (AR)](/wiki/Beatmap/Approach_rate), la [dificultad general (OD)](/wiki/Beatmap/Overall_difficulty), y la [vida (HP)](/wiki/Gameplay/Health) por un pequeña cantidad.
```

2023-08-03 16:51 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +Como resultado, usando Half Time resultara en un incremento de la puntuacion del maximo posible en mapas con muy pocos combos y largos dendens. Este efecto sera aun mayor cuando [Hard Rock](/wiki/Gam
```suggestion
Como resultado, usar Half Time resultara en un incremento de la puntuacion del máximo posible en mapas con muy pocos combos y largos dendens. Este efecto sera aun mayor cuando [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock) este activado simultaneamente.
```

2023-08-03 16:52 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- El valor de los `Objetos` seguira coloreado de un azul ligero aun cuando ningun cambio en el valor fuera hecho.
```suggestion
- El valor `Objetos` seguira coloreado de un azul ligero aun cuando ningun cambio en el valor fuera hecho.
```

2023-08-03 16:53 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- Tipo: Reduccion de dificultad
```suggestion
- Tipo: Reducción de dificultad
```

2023-08-03 16:53 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- Abreviacion: HT
```suggestion
- Abreviatura: HT
```

2023-08-03 17:03 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- Cuando el mod Half Time esta activiado, los valores de `Longitud`, `BPM`, y `Objetos` seran coloreados de un azul ligero con los nuevos valores (imagen abajo).
```suggestion
- Cuando el mod Half Time esta activiado, los valores `Longitud`, `BPM`, y `Objetos` se colorearán en azul claro con los nuevos valores. (En la foto de abajo).
```

2023-08-03 17:03 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- El valor de los `Objetos` seguira coloreado de un azul ligero aun cuando ningun cambio en el valor fuera hecho.
```suggestion
- El valor de los `Objetos` seguirá siendo de color azul claro aunque no se realice ningún cambio en el valor.
```

2023-08-03 17:03 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- Los valores del `AR`, `OD`, y `HP` tendran un triángulo en superíndice junto a sus valores que indica una pequeña disminución en sus valores (imagen abajo).
```suggestion
- Los valores `AR`, `OD`, y `HP` tendrán un triángulo en superíndice junto a sus valores que indica una pequeña disminución en sus valores. (En la foto de abajo).
```

2023-08-03 17:03 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +- El nombre «Half Time» podría etiquetarse como un nombre inapropiado, ya que el mod HT en realidad no disminuye la velocidad de un beatmap 0.5 veces (50 %); disminuye la velocidad de los beatmaps en
```suggestion
- El nombre «Half Time» podría etiquetarse como un nombre inapropiado, ya que el mod HT en realidad no reduce la velocidad de un beatmap 0.5 veces (50 %); disminuye la velocidad de los beatmaps en 0.75x (75 %).
```

2023-08-03 19:18 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +- Abreviación: HR
```suggestion
- Abreviatura: HR
```

2023-08-03 19:18 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hidden/es.md
> +- Abreviación: HD
```suggestion
- Abreviatura: HD
```

2023-08-03 19:18 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/No_Fail/es.md
> +- Abreviación: NF
```suggestion
- Abreviatura: NF
```

2023-08-03 19:18 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Random/es.md
> +- Abreviación: RD
```suggestion
- Abreviatura: RD
```

2023-08-03 19:18 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +- Abreviación: EZ
```suggestion
- Abreviatura: EZ
```

2023-08-08 10:02 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), el mod Auto irá más allá de la perfección y usará una velocidad ilimitada para atrapar *todas las bananas* en un spinner, a pesar de que tal hazaña es impos
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), el mod Auto irá más allá de la perfección y usará una velocidad ilimitada para atrapar *todos los plátanos* en un spinner, a pesar de que tal hazaña es imposible para un jugador humano.
```

2023-08-08 10:02 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +En [osu!mania](/wiki/Game_mode/osu!mania), el mod Auto intentará una partida perfecta, pero es posible que no detecte objetos en la misma columna que se superponen o se colocan a menos de 1 ms de dis
```suggestion
En [osu!mania](/wiki/Game_mode/osu!mania), el mod Auto intentará una partida perfecta, pero es posible que no detecte objetos en la misma columna que se superponen o se colocan a menos de 1 ms de distancia entre sí.
```

2023-08-08 14:50 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta los PPM y el AR. Como resultado, solo vale un multiplicador de 1.06x (a diferen
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta las PPM y el AR. Como resultado, solo vale un multiplicador de 1.06x (a diferencia del multiplicador de 1.12x para cualquier otro mod).
```

2023-08-08 14:50 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), el PPM y la velocidad del receptor se reducen por el mismo factor que en otros modos. Todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gam
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), las PPM y la velocidad del receptor se reducen por el mismo factor que en otros modos. Todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota), [gotitas](/wiki/Gameplay/Hit_object/Juice_stream#gotita) y [plátanos](/wiki/Gameplay/Hit_object/Banana) quedan intactos.
```

2023-08-08 14:51 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +En [osu!taiko](/wiki/Game_mode/osu!taiko), la canción y PPM ralentizados hacen que las notas se vuelvan muy densas debido a la disminución del AR. Sin embargo, debido a la forma en que se calculan lo
```suggestion
En [osu!taiko](/wiki/Game_mode/osu!taiko), la canción y las PPM ralentizados hacen que las notas se vuelvan muy densas debido a la disminución del AR. Sin embargo, debido a la forma en que se calculan los dendens en osu!taiko, se necesitan más golpes para eliminarlos y hacen que otorguen un **valor total más alto que sin el mod**, porque los golpes de los dendens no se ven afectados por el [multiplicador de puntuación](/wiki/Gameplay/Game_modifier/Mod_multiplier).
```

2023-08-08 14:51 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Half_Time/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), el PPM y la velocidad del receptor se reducen por el mismo factor que en otros modos. Todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gam
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), las PPM y la velocidad del receptor se reducen por el mismo factor que en otros modos. Todas las [frutas](/wiki/Gameplay/Hit_object/Fruit), [gotas](/wiki/Gameplay/Hit_object/Juice_stream#gota), [gotitas](/wiki/Gameplay/Hit_object/Juice_stream#gotita) y [plátanos](/wiki/Gameplay/Hit_object/Banana) quedan intactos.
```

2023-08-08 14:51 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta los PPM y el AR. Como resultado, solo vale un multiplicador de 1.06x (a diferen
```suggestion
En [osu!catch](/wiki/Game_mode/osu!catch), no hay dificultad general para aumentar. Por lo tanto, este mod solo aumenta las PPM y el AR. Como resultado, solo vale un multiplicador de 1.06x (a diferencia del multiplicador de 1.12x para cualquier otro mod).
```

2023-08-08 15:31 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En todos los [modos de juego](/wiki/Game_mode) exceptuando [osu!taiko](/wiki/Game_mode/osu!taiko), el mod otorgará al jugador dos «vidas» adicionales durante una partida si la [barra de vida](/wiki/C
```suggestion
En todos los [modos de juego](/wiki/Game_mode), exceptuando [osu!taiko](/wiki/Game_mode/osu!taiko), el mod otorgará al jugador dos «vidas» adicionales durante una partida si la [barra de vida](/wiki/Client/Interface/Health_bar) cae a cero. En el caso de que esto suceda, el juego se detendrá para rellenar lentamente la barra de vida hasta aproximadamente el 80 % y eliminar una «vida» del recuento de vidas del jugador. No se reproducirá ningún sonido durante este efecto.
```

2023-08-08 15:31 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +En [osu!](/wiki/Game_mode/osu!), el mod disminuye el [tamaño de los círculos (CS)](/wiki/Client/Beatmap_editor/Song_setup#circle-size), la [tasa de aproximación (AR)](/wiki/Beatmap/Approach_rate), la
```suggestion
En [osu!](/wiki/Game_mode/osu!), el mod disminuye el [tamaño de los círculos (CS)](/wiki/Beatmap/Circle_size), la [tasa de aproximación (AR)](/wiki/Beatmap/Approach_rate), la [dificultad general (OD)](/wiki/Beatmap/Overall_difficulty) y el [drenaje de HP (HP)](/wiki/Beatmap/HP_drain_rate) a la mitad.
```

2023-08-08 18:18 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Hard_Rock/es.md
> +El mod **Hard Rock** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que apunta a aumentar la dificultad sobre varios aspectos de un [beatmap](/wiki/Beatmap). Generalmente, logra su objeti
```suggestion
El mod **Hard Rock** es un [modificador de juego](/wiki/Gameplay/Game_modifier) que apunta a aumentar la dificultad sobre varios aspectos de un [beatmap](/wiki/Beatmap). Generalmente, logra su objetivo aumento él [tamaño del círculo (CS)](/wiki/Beatmap/Circle_size) en un 30 %, la [tasa de aproximación (AR)](/wiki/Beatmap/Approach_rate) en un 40 %, el [drenaje de HP (HP)](/wiki/Beatmap/HP_drain_rate) en un 40 % y la [dificultad general (OD)](/wiki/Beatmap/Overall_difficulty) en un 40 %, aunque los detalles varían según cada modo de juego.
```

2023-08-08 18:34 UTC, agatemosu commented
¿Puedes abrir un PR con solo los mods 10K, Auto, Autopilot, Cinema, Co-op, Double Time, Easy?

2023-08-09 20:35 UTC, TheMoonLoop commented
> ¿Puedes abrir un PR con solo los mods 10K, Auto, Autopilot, Cinema, Co-op, Double Time y Easy?

No uso mucho GitHub, pero veré que puedo hacer 👍

2023-08-09 20:36 UTC, agatemosu commented
me refiero a copiar cada archivo en una nueva rama

2023-09-20 13:32 UTC, TicClick commented
what's the status of this PR? are you going to work on it any further, or...?

2023-09-20 20:10 UTC, TheMoonLoop commented
> what's the status of this PR? are you going to work on it any further, or...?

currently another person is working in the files, checking grammar I think
im also in communication with this person, also waiting for his instructions to move further

2023-10-19 21:15 UTC, TicClick approved these changes

2023-10-19 21:15 UTC, merged