[DE] Add `History of osu!/Online rankings`
ppy/osu-wiki pull request #9456
Opened 2023-05-27 16:46 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-29 17:05 UTC, respektive requested changes

2023-05-29 17:05 UTC, respektive commented on wiki/History_of_osu!/Online_rankings/de.md
> +Seit dem 19. Juli 2021 ist ::{ flag=AU }:: [mrekk](https://osu.ppy.sh/users/7562902/osu) auf Platz 1 der [osu! Performance-Rangliste](https://osu.ppy.sh/rankings/osu/performance).
He's been #1 for longer, this is just the date this line got updated i guess.
```suggestion
Mit Stand vom 19. Juli 2021 ist ::{ flag=AU }:: [mrekk](https://osu.ppy.sh/users/7562902/osu) auf Platz 1 der [osu! Performance-Rangliste](https://osu.ppy.sh/rankings/osu/performance).
```

2023-05-29 17:05 UTC, respektive commented on wiki/History_of_osu!/Online_rankings/de.md
> +Seit dem 4. Oktober 2022 ist ::{ flag=JP }:: [shinchikuhome](https://osu.ppy.sh/users/3174184/taiko) auf Platz 1 der [osu!taiko Performance-Rangliste](https://osu.ppy.sh/rankings/taiko/performance).
```suggestion
Mit Stand vom 4. Oktober 2022 ist ::{ flag=JP }:: [shinchikuhome](https://osu.ppy.sh/users/3174184/taiko) auf Platz 1 der [osu!taiko Performance-Rangliste](https://osu.ppy.sh/rankings/taiko/performance).
```

2023-05-29 17:05 UTC, respektive commented on wiki/History_of_osu!/Online_rankings/de.md
> +Seit dem 7. Juni 2021 ist ::{ flag=KR }:: [YesMyDarknesss](https://osu.ppy.sh/users/4158549/fruits) auf Platz 1 der [osu!catch Performance-Rangliste](https://osu.ppy.sh/rankings/fruits/performance).
```suggestion
Mit Stand vom 7. Juni 2021 ist ::{ flag=KR }:: [YesMyDarknesss](https://osu.ppy.sh/users/4158549/fruits) auf Platz 1 der [osu!catch Performance-Rangliste](https://osu.ppy.sh/rankings/fruits/performance).
```

2023-05-29 17:05 UTC, respektive commented on wiki/History_of_osu!/Online_rankings/de.md
> +Seit dem 13. April 2023 ist ::{ flag=KR }:: [dressurf](https://osu.ppy.sh/users/758406/mania) auf Platz 1 der [osu!mania Performance-Rangliste](https://osu.ppy.sh/rankings/mania/performance).
```suggestion
Mit Stand vom 13. April 2023 ist ::{ flag=KR }:: [dressurf](https://osu.ppy.sh/users/758406/mania) auf Platz 1 der [osu!mania Performance-Rangliste](https://osu.ppy.sh/rankings/mania/performance).
```

2023-06-01 13:49 UTC, The-Last-Cookie commented
@respektive I dug a bit through the internet and you're right. mrekk got the 1st place on 8th April, 2021:

- [Reddit thread 1](https://www.reddit.com/r/osugame/comments/mmkaag/mrekk_is_now_1_surpassing_whitecat/)
- [Reddit thread 2](https://www.reddit.com/r/osugame/comments/mmkf3p/mrekk_becoming_1_means_a_lot_of_things_the/)
- [tweet from mrekk](https://twitter.com/mrekkosu/status/1380024575136722944)

2023-06-01 16:09 UTC, respektive approved these changes

2023-06-09 15:04 UTC, merged