[FR] Fix no native `Community/cavoe's_osu!_event` `Community/cavoe's_osu!_event/2023`
ppy/osu-wiki pull request #9466
Opened 2023-05-30 08:26 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-05-30 17:53 UTC, Ganondorf-1 requested changes

2023-05-30 17:53 UTC, Ganondorf-1 commented on wiki/Community/cavoe's_osu!_event/2023/fr.md
>  ![bannière COE 2023](img/banner.png)
```suggestion
![Bannière COE 2023](img/banner.png)
```

2023-05-30 17:53 UTC, Ganondorf-1 commented on wiki/Community/cavoe's_osu!_event/2023/fr.md
> +**cavoe's osu! event 2023** (***COE 2023***) est une convention osu! qui sera organisée prochainement à **Brabanthallen in 's-Hertogenbosch (Den Bosch), au Pays-bas**. Il s'agit de la cinquième éditi
```suggestion
**cavoe's osu! event 2023** (***COE 2023***) est une convention osu! qui sera organisée prochainement au **Brabanthallen à 's-Hertogenbosch (Den Bosch), aux Pays-bas**. Il s'agit de la cinquième édition du cavoe's osu! event.
```

2023-05-30 17:53 UTC, Ganondorf-1 commented on wiki/Community/cavoe's_osu!_event/fr.md
> +En tant qu'événement appelé sobrement "osu! event" et avec uniquement 35 personnes pour une durée de 3 jours, COE a commencé en 2017 comme un "meetup national néerlandais avec quelques visiteurs d'au
```suggestion
En tant qu'événement appelé sobrement "osu! event" et avec uniquement 35 personnes pour une durée de 3 jours, le COE a commencé en 2017 comme un "meetup national néerlandais avec quelques visiteurs d'autres pays" au café De Hangar à Eindhoven.
```

2023-05-30 17:53 UTC, Ganondorf-1 commented on wiki/Community/cavoe's_osu!_event/fr.md
> +L'itération 2018 s'est développée jusqu'à devenir notoire avec plus de 300 participants et une durée de 10 jours, mettant en vedette des joueurs de premier plan tels que ::{ flag=KR }:: [Chocomint](h
```suggestion
L'itération 2018 s'est développée jusqu'à devenir notoire avec plus de 300 participants et une durée de 10 jours, mettant en vedette des joueurs de premier plan tels que ::{ flag=KR }:: [chocomint](https://osu.ppy.sh/users/124493) (auparavant Cookiezi), ::{ flag=US }:: [BTMC](https://osu.ppy.sh/users/3171691) (auparavant BeasttrollMC), et ::{ flag=PL }:: [WubWoofWolf](https://osu.ppy.sh/users/39828).
```

2023-05-30 17:53 UTC, Ganondorf-1 commented on wiki/Community/cavoe's_osu!_event/fr.md
> +COE 2019 a déplacé ses opérations à Brabanthallen à 's-Hertogenbosch (alias Den Bosch). Dans un lieu plus grand, doté notamment d'une grande scène. La convention a accueilli plus de 500 personnes et
```suggestion
Le COE 2019 a déplacé ses opérations au Brabanthallen à 's-Hertogenbosch (alias Den Bosch). Dans un lieu plus grand, doté notamment d'une grande scène. La convention a accueilli plus de 500 personnes et a proposé davantage de stands VR, d'événements scéniques et une zone VIP dédiée.
```

2023-06-03 14:32 UTC, Ganondorf-1 approved these changes

2023-06-04 11:55 UTC, TicClick approved these changes

2023-06-04 11:56 UTC, merged