[FR] Fix no native `Beatmap/Play_time` `  Beatmap/Stack_leniency` `Disambiguation/Timing` `Spinner_trap` `Music_theory/Layer` `People/User_group`
ppy/osu-wiki pull request #9471
Opened 2023-05-31 08:17 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-06-03 14:47 UTC, Ganondorf-1 requested changes

2023-06-03 14:47 UTC, Ganondorf-1 commented on wiki/Music_theory/Layer/fr.md
> +Une **musical layer** (ou couche musicale) est une partie d'une musique qui contient des éléments avec un aspect commun entre eux. Une part importante du [beatmapping](/wiki/Beatmapping) dans chaque
```suggestion
Une **musical layer** (ou couche musicale) est une partie d'une musique qui contient des éléments avec un aspect commun entre eux. Une part importante du [beatmapping](/wiki/Beatmapping) dans chaque [mode de jeu](/wiki/Game_mode) consiste à suivre différents types de couches (telles que les percussions, les voix et les motifs sonores) de manière cohérente) et à passer de l'un à l'autre à des fins d'accentuation et de contraste.
```

2023-06-03 14:47 UTC, Ganondorf-1 commented on wiki/Music_theory/Layer/fr.md
> +En plus de couches existantes, les mappers peuvent disposer les [objets](/wiki/Gameplay/Hit_object) de manière à créer une nouvelle couche. Cette approche est souvent appelé [overmapping](/wiki/Beatm
```suggestion
En plus de couches existantes, les mappeurs peuvent disposer les [objets](/wiki/Gameplay/Hit_object) de manière à créer une nouvelle couche. Cette approche est souvent appelé [overmapping](/wiki/Beatmapping/Overmapping) et est utilisée dans le but de rendre la beatmap plus intéressante grâce à de nouvelles opportunités rythmiques, qui ne sont généralement pas présentes dans la musique. Cependant, un placement incohérent ou excessif des notes peut empêcher les joueurs de suivre l'intention du mappeur et gâcher la relation entre la beatmap la chanson ou ses caractéristiques principales.
```

2023-06-13 11:03 UTC, Ganondorf-1 requested changes

2023-06-13 11:17 UTC, Ganondorf-1 approved these changes

2023-06-14 11:19 UTC, TicClick approved these changes

2023-06-14 11:24 UTC, merged