[FR] Fix no native in `Announcement_messages` `Beatmap/Beatmap_collaborations` `Beatmap/Difficulty_spread` `Beatmap/Lead-in_time` `Beatmap_Spotlights/Seasons/2023_Spring` `Beatmap_Spotlights`
ppy/osu-wiki pull request #9472
Opened 2023-05-31 09:49 UTC by Biokax

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] In order to review `Wiki/BeatmapSpotlight` only review changes from https://github.com/ppy/osu-wiki/commit/133c0037fa19bd698e47aa6b930bb521d3bb266d

2023-06-12 11:51 UTC, Ganondorf-1 requested changes

2023-06-12 11:51 UTC, Ganondorf-1 commented on wiki/Announcement_messages/fr.md
> +Un **message d'annonce** est un type de message spécial destiné à envoyer des messages plus longs et formatés à plusieurs utilisateurs à la fois. Les principales différences entre les messages d'anno
```suggestion
Un **message d'annonce** est un type de message spécial destiné à envoyer des messages plus longs et formatés à plusieurs utilisateurs à la fois. Les principales différences entre les messages d'annonce et les messages de tchat ordinaires sont les suivantes :
```

2023-06-12 11:51 UTC, Ganondorf-1 commented on wiki/Announcement_messages/fr.md
> +Pour envoyer une annonce de tchat, ouvrez la [page de tchat](https://osu.ppy.sh/community/chat) à partir de vos notifications de tchat et cliquez sur le bouton `create announcement`. Saisissez le nom
```suggestion
Pour envoyer une annonce de tchat, ouvrez la [page de tchat](https://osu.ppy.sh/community/chat) à partir de vos notifications de tchat et cliquez sur le bouton `créer une annonce`. Saisissez le nom du canal, la description[^note-desc], la liste des destinataires et votre message. Enfin, cliquez sur le bouton `créer` pour envoyer l'annonce. 
```

2023-06-12 11:51 UTC, Ganondorf-1 commented on wiki/Beatmap/Beatmap_collaborations/fr.md
> +Les collaborations de beatmap ont généralement le mot "Collab" ou plusieurs noms d'utilisateurs attachés à leur nom de difficulté ou dans la [description de beatmap](/wiki/Beatmap/Beatmap_description
```suggestion
Les collaborations de beatmap ont généralement le mot "Collab" ou plusieurs noms d'utilisateurs attachés à leur nom de difficulté ou dans la [description de beatmap](/wiki/Beatmap/Beatmap_description), bien que ça ne soit pas une exigence stricte des [critères de classement](/wiki/Ranking_Criteria). Il arrive souvent que des collaborateurs fréquents inventent des amalgames de leurs noms d'utilisateur[^name-example] et les utilisent de manière cohérente tout au long de leur carrière de mapping.
```

2023-06-12 11:51 UTC, Ganondorf-1 commented on wiki/Beatmap/Beatmap_collaborations/fr.md
> +Le processus de mapping commence généralement avec l'[hôte d'une beatmap](/wiki/Beatmap/Beatmap_host) qui divise un modèle de beatmap pre-[timé](/wiki/Beatmapping/Timing) en plusieurs parties en les
```suggestion
Le processus de mapping commence généralement avec l'[hôte d'une beatmap](/wiki/Beatmap/Beatmap_host) qui divise un modèle de beatmap pré-[timé](/wiki/Beatmapping/Timing) en plusieurs parties en les marquant sur la [timeline](/wiki/Client/Beatmap_editor/Timelines) à l'aide de signets en fonction de la structure musicale de la musique. Les segments relativement longs, tels que les couplets, sont généralement divisés toutes les 4 ou 8 [mesures](/wiki/Music_theory/Measure). Ces parties sont ensuite attribuées à chaque collaborateur selon une répartition convenue, par exemple par segments pairs ou impairs dans le cas des deux mappeurs.
```

2023-06-14 12:46 UTC, Walavouchey submitted a review, later dismissed

2023-06-14 12:59 UTC, Walavouchey approved these changes

2023-06-14 13:02 UTC, merged