[ZH] Review no_native_review articles (except `FAQ`)
ppy/osu-wiki pull request #9482
Opened 2023-06-02 03:21 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-06-02 13:15 UTC, YumeMuzi requested changes

2023-06-02 13:15 UTC, YumeMuzi commented on wiki/Gameplay/Score/ScoreV1/osu!/zh.md
> +`难度倍率 = 四舍五入((掉血速度 + 圆圈大小 + 整体难度 + Clamp(打击物件总数 / 以秒计的掉血速度 * 8, 0, 16)) / 38 * 5)`
```suggestion
`难度倍率 = Round((掉血速度 + 圆圈大小 + 整体难度 + Clamp(打击物件总数 / 以秒计的掉血速度 * 8, 0, 16)) / 38 * 5)`
```
代码方法不可翻译。

2023-06-02 13:23 UTC, CloneWith commented on wiki/People/Nomination_Assessment_Team/SEV_rating/zh.md
> +| 1 | 有经验的人可以看出 | 需要一定的知识/经验/注意力来发现。工具或普通的玩家通常都无法察觉，例如测定时间轴 (Timing) 问题和歌曲元数据问题。 |
1. `知识...注意力` 是按照原文意思更改(?)
2. `通常` 的语序调换，可能会比较好
3. `测定时间轴` 按照制图过程的名词更改
4. `元数据` 认为可以不翻译出英文原文

以上四点修改，个人觉得还是有一些争议

2023-06-09 20:22 UTC, YumeMuzi approved these changes

2023-06-10 10:04 UTC, Walavouchey requested changes
some "，" are changed to "、" and vice versa. which one should it be?

2023-06-10 10:17 UTC, CloneWith commented
> some "，" are changed to "、" and vice versa. which one should it be?

We prefer to use `、` when it contains the meaning of "and / or". So I have modified most of them to match the structure of the sentence. And the remaining ones are kept intentionally.

2023-06-10 10:19 UTC, Walavouchey approved these changes
i'm losing my mind. why are there two commas in chinese.

2023-06-10 10:24 UTC, merged