update `Medals` to account for new categories
ppy/osu-wiki pull request #9487
Opened 2023-06-03 22:23 UTC by chromb

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-06-03 22:24 UTC, chromb commented
This is definitely not ready to merge for now, looking for more feedback on how exactly `Medals` should now be written, along with whether `Medal unlock requirements` should have some pages merged.

2023-06-04 05:15 UTC, Walavouchey requested changes
the skill and dedication medal unlock requirement pages need to be merged, same for the beatmap spotlight and seasonal medal pages

2023-06-04 05:15 UTC, Walavouchey commented on wiki/Medals/en.md
> +**Medals**, previously known as *achievements*, are badges on a user's profile which indicate certain goals that have been achieved by the user. Currently, there are **300** medals available to be un
```suggestion
**Medals**, previously known as *achievements*, are badges on a user's profile which indicate certain goals that have been achieved by the user. Currently, there are **300** medals available to be unlocked across seven different categories in total: [Beatmap Packs](#beatmap-packs), [Skill & Dedication](#skill-&-dedication), [Mod Introduction](#mod-introduction), [Hush-Hush](#hush-hush), [Hush-Hush (Expert)](#hush-hush-(expert)),[Beatmap Spotlights](#beatmap-spotlights), and [Beatmap Challenge Packs](#beatmap-challenge-packs).
```

2023-06-04 05:17 UTC, Walavouchey commented on wiki/Medals/en.md
> +**Expert Hush-Hush** medals are a harder set of Hush-Hush medals, with the unique condition that [**difficulty reduction mods**](/wiki/Gameplay/Game_modifier#difficulty-reduction) are not allowed to
```suggestion
**Expert Hush-Hush** medals are a harder set of Hush-Hush medals, with the unique condition that [difficulty reduction mods](/wiki/Gameplay/Game_modifier#difficulty-reduction) are not allowed to be used.
```

2023-06-04 05:20 UTC, Walavouchey commented on wiki/Medals/en.md
>  **Seasonal Spotlights medals** are medals awarded upon completion of certain beatmap packs released as part of the [Seasonal Spotlights](https://osu.ppy.sh/home/news/2018-11-01-beatmap-spotlights-sum
this needs to be reworded since there's no distinction anymore. they're all called "Beatmap Spotlights" medals

2023-06-04 05:33 UTC, Walavouchey commented on wiki/Medals/en.md
>  **Dedication medals** are medals awarded upon reaching certain play count milestones in the osu! game mode, or by reaching total hit count milestones in osu!taiko, osu!catch, and osu!mania.
the wording needs to make clear that these are the same category of medals

2023-07-05 17:30 UTC, closed without merging