[ZH] Add `Game_mode/osu!` and update `FAQ`
ppy/osu-wiki pull request #9539
Opened 2023-06-15 12:36 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-06-16 18:34 UTC, YumeMuzi requested changes

2023-06-16 18:34 UTC, YumeMuzi commented on wiki/FAQ/zh.md
> +  - 然而，如果通过重玩已 SS 的上架难度获得了新的最高分（转盘加分更多，或者是通过游戏模组）但获得了 S 等级，则 SS 总数会减少一 (1)，S 总数会增加一 (1)。
不需要加括号来解释吧，原文有的吗？即使原文有这里应该也可以直接用数词替代

2023-06-16 18:34 UTC, YumeMuzi commented on wiki/FAQ/zh.md
> +在谱面游玩失败后，按 `F1` 可以回放当前失败的游玩过程。当屏幕变暗，中央出现 osu!logo 时回放结束，且不会显示游戏结束屏幕。如果要再次观看回放，按下自定义的默认抑音符/波浪号键 (\`/~)（可以在设置侧边栏中更改；在*按键设置*中的**Quick Retry (hold briefly)**）或按下 `Ctrl`+`R` 一段时间来重看回放。
加一个快速重试

2023-06-16 18:34 UTC, YumeMuzi commented on wiki/Game_mode/osu!/zh.md
> +- 在线排行榜启用当天（2007 年 10 月 7 日，2007-10-07），最先上架的三张谱面是：
```suggestion
- 在线排行榜启用当天（2007 年 10 月 7 日），最先上架的三张谱面是：
```

2023-06-16 18:34 UTC, YumeMuzi commented on wiki/Game_mode/osu!/zh.md
> +- 玩 *DS* 时（尤其是高难度关卡），完成转盘是刮坏触摸屏（或者屏幕保护膜）的最佳办法。在 osu! 中，转盘已经得到优化，完成它不会这么麻烦。转盘每分钟可实现的最高转数是 477 转，也是 [Auto](/wiki/Gameplay/Game_modifier/Auto) 模组游玩时的旋转速度，而 [Spun Out](/wiki/Gameplay/Game_modifier/Spun_O
```suggestion
- 玩 *DS* 时（尤其是高难度关卡），完成转盘很容易刮坏触摸屏（或者屏幕保护膜）。osu! 的转盘已经优化，完成它不会这么麻烦。转盘每分钟可实现的最高转数是 477 转，也是 [Auto](/wiki/Gameplay/Game_modifier/Auto) 模组游玩时的旋转速度，而 [Spun Out](/wiki/Gameplay/Game_modifier/Spun_Out) 模组的旋转速度较低，是每分钟 287 转。
```

2023-06-16 23:15 UTC, CloneWith commented on wiki/FAQ/zh.md
> +  - 然而，如果通过重玩已 SS 的上架难度获得了新的最高分（转盘加分更多，或者是通过游戏模组）但获得了 S 等级，则 SS 总数会减少一 (1)，S 总数会增加一 (1)。
[原文](https://github.com/ppy/osu-wiki/blob/master/wiki/FAQ/en.md?plain=1#L378-L380)

我也不明白为什么用这种方式表达，很奇怪🤣

2023-06-18 09:02 UTC, YumeMuzi approved these changes

2023-06-28 18:38 UTC, TPGPL approved these changes

2023-06-28 18:40 UTC, merged