[ES] Add all `Medals/Unlock_requirements`
ppy/osu-wiki pull request #9575
Opened 2023-06-23 23:03 UTC by UnknownOsu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### All the requirements of the medals that appear in these articles and the article that directs to these articles:
- `Medals/Unlock_requirements/Beatmap_challenge_packs`
- `Medals/Unlock_requirements/Beatmap_packs`
- `Medals/Unlock_requirements/Beatmap_spotlights`
- `Medals/Unlock_requirements/Dedication`
- `Medals/Unlock_requirements/Mod_introduction`
- `Medals/Unlock_requirements/Seasonal_spotlights`
- `Medals/Unlock_requirements/Skill`
- `Medals/Unlock_requirements`

2023-06-25 12:18 UTC, agatemosu requested changes
La descripción de la medalla no está traducida en la página web así que debería quedar en inglés

2023-06-26 17:33 UTC, UnknownOsu commented
> La descripción de la medalla no está traducida en la página web así que debería quedar en inglés

Lo pensé, pero me parece mejor que esté traducido en el artículo. 

No ayuda de mucho que los 2 estén en inglés, puede que haya algún curioso en querer saber lo que significa y piense que en la wiki puede encontrar el significado. Sé que puede usar el traductor, pero siento que queda mejor traducido.

Creo que no pasa nada por traducirlos, no rompe el significado de nada ni queda tan mal

2023-06-26 19:07 UTC, agatemosu commented
Los otros idiomas no las traducen tampoco

2023-06-26 19:33 UTC, UnknownOsu commented
> Los otros idiomas no las traducen tampoco

Vi que en `zh-tw` lo hicieron, pero pusieron el original al lado de la traducción, aunque supongo que es normal en un idioma similar a ese.

Si no te termina de convencer, lo cambio. Aunque a mí no me parece mal tenerlo traducido

2023-08-11 21:50 UTC, TicClick approved these changes
merging (no native review for one week or longer)

2023-08-11 21:52 UTC, merged