[ES] Update `Mascots`
ppy/osu-wiki pull request #9581
Opened 2023-06-25 11:38 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] #9565

2023-06-26 18:25 UTC, UnknownOsu requested changes

2023-06-26 18:25 UTC, UnknownOsu commented on wiki/Mascots/es.md
> +Diseñada por [pyun](https://osu.ppy.sh/users/981534), Chirou fue una de las entradas en el concurso de diseño de mascotas para osu!taiko. Es muy estricta y exigente, perfeccionista y no le gusta come
```suggestion
Diseñada por [pyun](https://osu.ppy.sh/users/981534), Chirou fue una de las candidatas en el concurso de diseño de mascotas para osu!taiko. Es muy estricta y exigente, perfeccionista y no le gusta cometer errores, especialmente en sus golpes en osu!taiko. Pero más allá de su perspectiva fuerte, si llegas a su punto débil, puede ser esponjosa y linda. Tiene 14 años, nació el 25 de octubre con sangre tipo AB. Ella también mide 4 pies y 11 pulgadas y pesa 100 libras. Sus pasatiempos incluyen tocar la batería, mantenerse caliente en su capa y coleccionar gemas o rocas. Chirou ha hecho algunas apariciones en varias presentaciones de fanart de usuarios.
```

2023-06-26 18:25 UTC, UnknownOsu commented on wiki/Mascots/es.md
> +Diseñado por [Lemia-Chan](https://osu.ppy.sh/users/8506749), Taikonator, también conocido como Taikonator 3000, fue una de las entradas en el concurso de diseño de mascotas para osu!taiko. Ganó atrac
```suggestion
Diseñado por [Lemia-Chan](https://osu.ppy.sh/users/8506749), Taikonator, también conocido como Taikonator 3000, fue uno de los candidatos en el concurso de diseño de mascotas para osu!taiko. Ganó atracción como un chiste y popularidad por razones desconocidas. Sus orígenes siguen siendo un misterio; a pesar de esto, es mucho más único que los demás diseños de mascota para osu!taiko y ha aparecido muchas veces en fanarts de varios usuarios.
```

2023-06-26 18:25 UTC, UnknownOsu commented on wiki/Mascots/es.md
> +Diseñada por [crystalsuicine](https://osu.ppy.sh/users/9974), Tama fue una de las entradas más jóvenes en el concurso de diseño de mascotas para osu!taiko con solo 15 años de edad y tiene una gran pa
```suggestion
Diseñada por [crystalsuicine](https://osu.ppy.sh/users/9974), Tama fue una de las candidatas más jóvenes en el concurso de diseño de mascotas para osu!taiko con solo 15 años de edad y tiene una gran pasión por tocar el tambor. Y las tormentas eléctricas. Y especialmente los festivales, donde se arrebata cualquier takoyaki que se encuentra. Siempre lista para cualquier desafío, Tama oculta un pasado misterioso detrás de su comportamiento juvenil.
```

2023-07-18 18:04 UTC, TicClick approved these changes
merging (no native review for one week or longer)

2023-07-18 18:04 UTC, TicClick approved these changes

2023-07-18 18:14 UTC, merged