Reorganise information in lazer-related articles
ppy/osu-wiki pull request #9590
Opened 2023-06-28 12:22 UTC by Walavouchey

closes https://github.com/ppy/osu-wiki/issues/9300

suggestions welcome

2023-06-28 13:44 UTC, TicClick requested changes

2023-06-28 14:12 UTC, Walavouchey commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/en.md
> +# Gameplay differences in osu!(lazer)
as an article name that sounds not very descriptive

2023-06-28 14:14 UTC, Walavouchey commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/en.md
they look like this on the website and it's intentional

![image](https://github.com/ppy/osu-wiki/assets/36758269/f999a8dc-d1bc-4c5b-bbf8-13ff01ebfc73)

2023-06-28 14:15 UTC, Walavouchey commented on wiki/Help_centre/Upgrading_to_lazer/en.md
> +[^difficulty-adjust]: Change CS/AR/OD/HP of a beatmap directly from song select via the Difficulty Adjust mod.
nope
![image](https://github.com/ppy/osu-wiki/assets/36758269/d96dfa36-2f58-4f4a-be8e-1cb19a11d729)

2023-06-28 14:18 UTC, Walavouchey commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/en.md
> +There are also some differences in how much score each hit object and each judgement is responsible for relative to each other.
```suggestion
There are also some differences in how much hit objects and judgements contribute to a score relative to each other.
```

2023-06-28 14:19 UTC, CloneWith commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/en.md
yep I understood that :heart

2023-06-28 17:59 UTC, peppy reviewed
Looks mostly fine

2023-06-28 17:59 UTC, peppy commented on wiki/Help_centre/Upgrading_to_lazer/en.md
> +| Skinnable pause menu | ![Yes][true] | ![No][false] |
I mean this is kinda covered by the "gameplay only" clause above. Not sure listing here does much other than spam the list.

2023-06-29 04:38 UTC, peppy commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/en.md
> +There are also some differences in how much score each hit object and each judgement is responsible for relative to each other.
I'm not actually sure what this refers to specifically. Maybe worth elaborating on if it's to remain?

2023-07-02 12:56 UTC, TicClick approved these changes

2023-07-02 13:16 UTC, Walavouchey commented on wiki/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)/en.md
> +There are also some differences in how much score each hit object and each judgement is responsible for relative to each other.
this is something on my list to investigate shortly (will report about it against `ppy/osu`, as i mentioned in the meeting), so i'll elaborate in another pass

2023-07-07 10:46 UTC, Ephemeralis approved these changes

2023-07-07 10:47 UTC, merged