[IT] Update `Guides/How_to_use_the_Offset_Wizard`
ppy/osu-wiki pull request #9597
Opened 2023-06-29 11:21 UTC by githacki

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-06-29 13:06 UTC, Sclafus requested changes
As discussed, `Offset Wizard` -> `Taratura Guidata dell'Offset`

2023-06-29 13:06 UTC, Sclafus commented on wiki/Guides/How_to_use_the_Offset_Wizard/it.md
> +# Come usare l'Offset Wizard
```suggestion
# Come usare la Taratura Guidata dell'Offset 
```

2023-06-29 13:06 UTC, Sclafus commented on wiki/Guides/How_to_use_the_Offset_Wizard/it.md
> +L'Offset Wizard verrà quindi aperto, riproducendo la musica precedentemente giocata in osu!, mentre delle barre verdi scorrono sullo schermo e un metronomo tiene il ritmo.
```suggestion
La procedura di taratura guidata dell'offset inizierà, riproducendo un brano precedentemente riprodotto, mentre delle barre verdi verticali scorreranno sullo schermo orizzontalmente. Si potrà udire anche un metronomo, per tenere il ritmo.
```

2023-06-29 13:06 UTC, Sclafus commented on wiki/Guides/How_to_use_the_Offset_Wizard/it.md
> +## Calibrare l'offset universale
```suggestion
## Tarare l'offset universale
```

2023-06-29 13:06 UTC, Sclafus commented on wiki/Guides/How_to_use_the_Offset_Wizard/it.md
> +4. Una volta calibrato l'offset universale con successo, premi il pulsante `Indietro` in basso a sinistra dello schermo per uscire dall'Offset Wizard.
```suggestion
4. Una volta calibrato l'offset universale con successo, premi il pulsante `Indietro` in basso a sinistra dello schermo per uscire dalla procedura di Taratura Guidata dell'Offset.
```

2023-06-29 13:45 UTC, Sclafus approved these changes

2023-07-13 11:23 UTC, Walavouchey commented
force-pushed to remove accidental commits at the end

2023-07-13 11:23 UTC, Walavouchey approved these changes

2023-07-13 11:25 UTC, merged