[IT] Update `osu!_tournament_client/osu!tourney/Setup`
ppy/osu-wiki pull request #9603
Opened 2023-06-30 11:49 UTC by zSmoxKe

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-06-30 11:51 UTC, Sclafus requested changes

2023-06-30 11:51 UTC, Sclafus commented on wiki/osu!_tournament_client/osu!tourney/Setup/it.md
> +  - L'"area di streaming" del client non include il pannello di controllo. In generale, il pannello di controllo è più grande di 200 px rispetto all'altezza del client, quindi, ad esempio, una risolu
```suggestion
  - "L'area di streaming" del client non include il pannello di controllo. In generale, il pannello di controllo è più grande di 200 px rispetto all'altezza del client, quindi, ad esempio, una risoluzione di 1440p sarebbe consigliabile per lo streaming di un torneo a 1080p.
```

2023-06-30 11:52 UTC, Sclafus approved these changes

2023-07-02 12:58 UTC, TicClick approved these changes

2023-07-02 13:00 UTC, merged