[ZH] Add several articles in `Beatmap`
ppy/osu-wiki pull request #9604
Opened 2023-06-30 16:22 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-03 15:24 UTC, YumeMuzi commented on wiki/Beatmap/Approach_rate/zh.md
> +打击物件在屏幕上保持可见的时间间隔范围为从 AR0 的 1800 毫秒到 AR10 的 450 毫秒。对于 AR5 以下，AR 水平间相差 120 毫秒，AR5 以上则相差 150 毫秒。
```suggestion
打击物件在屏幕上保持可见的时间间隔范围为从 AR0 的 1800 毫秒到 AR10 的 450 毫秒。对于 AR5 以下，AR 整数值之间相差 120 毫秒，AR5 以上则相差 150 毫秒。
```

2023-07-03 15:25 UTC, YumeMuzi commented on wiki/Beatmap/Guest_difficulty/zh.md
> +不要将客串难度与以多位作图者为特征的难度混淆，后者被称作[合作难度](/wiki/Beatmap/Beatmap_collaborations)。
```suggestion
不要将客串难度与含有多位谱师特征的难度相混淆，后者被称作[合作难度](/wiki/Beatmap/Beatmap_collaborations)。
```

2023-07-03 15:26 UTC, YumeMuzi commented on wiki/Beatmap/Hype/zh.md
> +  - 队列
hype本身也得加吧

2023-07-03 15:27 UTC, YumeMuzi commented on wiki/Beatmap/Overall_difficulty/zh.md
> +# 总体难度 (Overall difficulty)
判定严度（判定严格度）

2023-07-03 15:28 UTC, YumeMuzi commented on wiki/Beatmap/Primary_metadata_source/zh.md
> +旨在进入[上架 (Ranked)](/wiki/Beatmap/Category#上架-(ranked)) 状态的谱面需要使用来自主要源的元数据。对于谱面元数据相关的更多规定与准则，参见[谱面上架标准 (RC)](/wiki/Ranking_criteria#metadata)。
```suggestion
即将进入[上架 (Ranked)](/wiki/Beatmap/Category#上架-(ranked)) 状态的谱面需要使用来自主要源的元数据。对于谱面元数据相关的更多规定与准则，参见[谱面上架标准 (RC)](/wiki/Ranking_criteria#metadata)。
```

2023-07-03 15:29 UTC, YumeMuzi commented on wiki/Beatmap/Stack_leniency/zh.md
> +# 堆叠严度
堆叠度就可以了，记得加上sl作为tag

2023-07-03 15:30 UTC, YumeMuzi commented on wiki/Beatmap/Star_rating/zh.md
> +# 星数评价
```suggestion
# 星数
```

tags写上星级、难度星级、难度

2023-07-03 15:32 UTC, YumeMuzi commented on wiki/Beatmap/Star_rating/zh.md
> +请注意，尽管大多数谱面的设计的难度等级与给出的颜色或等级区间相符，也有一些谱面出于一定原因有明显的偏差。这就是[谱面上架标准 (RC)](/wiki/Ranking_criteria) 提供更多决定性的基本规则，以确定谱面的实际难度等级和分布，而不管其星数评价的原因。
```suggestion
请注意，尽管大多数谱面设计的难度等级与给出的颜色或等级区间相符，也有一些谱面出于一定原因有明显的偏差。这就是为什么谱面的实际难度等级和分布位置的标准，是由[谱面上架标准 (RC)](/wiki/Ranking_criteria) 的基本规则决定，而不由谱面的星数直接决定。
```

2023-07-03 15:33 UTC, YumeMuzi commented on wiki/Beatmap/Title_text/zh.md
> +| 键 | 描述 | 默认值 |
```suggestion
| 参数 | 描述 | 默认值 |
```

key怎么是键呢

2023-07-03 15:36 UTC, YumeMuzi requested changes
本来想改一点点，但是越改越多，，翻译腔太浓了。可以适当改写原文，一对一肯定不是最好的方案。尝试理解文意并自己说出来，会事半功倍。

2023-07-03 15:37 UTC, CloneWith commented on wiki/Beatmap/Title_text/zh.md
> +| 键 | 描述 | 默认值 |
这里是想到了类似于注册表里的`键值`概念。不过`参数`一词确实更好

2023-07-11 17:15 UTC, YumeMuzi requested changes

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Approach_rate/zh.md
> +尽管 Half Time 与 Double Time 不改变 AR 值，但速度的不同也会使 AR 值看上去改变了一般。HT 或 DT 下的 AR 值通常指其感知值。比如，“AR 8 + DT”也可以写作“AR 9.6”。
```suggestion
尽管 Half Time 与 Double Time 不改变 AR 值，但曲速的不同也会使 AR 值看上去像被改变了一样。HT 或 DT 下的 AR 值通常指其感知值。比如，“AR 8 + DT”也可以写作“AR 9.6”。
```

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Beatmap_collaborations/zh.md
> +**谱面合作** (***collabs***) 是带有多人所作[客串难度](/wiki/Beatmap/Guest_difficulty)的单个[难度](/wiki/Beatmap/Difficulty)或[谱面](/wiki/Beatmap)。虽然 *collab* 一词通常指谱面，但也可以指多人参与创建的任何其他东西，比如[故事板](/wiki/Storyboard)或歌曲。
```suggestion
**谱面合作** (***collabs***) 是带有多人所作[客串难度](/wiki/Beatmap/Guest_difficulty)的单个[难度](/wiki/Beatmap/Difficulty)或[谱面](/wiki/Beatmap)。虽然 *collab* 一词通常指谱面，但也可以指多人合作创建的其他任何东西，比如[故事板](/wiki/Storyboard)或歌曲。
```

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Beatmap_collaborations/zh.md
> +[^name-example]: 比如，[Vass\_Bass](https://osu.ppy.sh/users/188248) 制作的 [masazi - mayday B](https://osu.ppy.sh/beatmapsets/74277#osu/233068) 中，有一个与 [Reiji-RJ](https://osu.ppy.sh/users/305389) 的合作难度，名字是
```suggestion
[^name-example]: 比如，[Vass\_Bass](https://osu.ppy.sh/users/188248) 制作的 [masazi - mayday B](https://osu.ppy.sh/beatmapsets/74277#osu/233068) 中，有一个与 [Reiji-RJ](https://osu.ppy.sh/users/305389) 的合作难度。因此，客串难度的作者名字写作 “Vass-RJ”。
```

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Beatmap_collaborations/zh.md
> +作图者通常依赖已完成的部分来让游玩中的过渡尽可能顺滑，但也存在所谓的*盲作 (blind collabs)*，比如所有者 ::{ flag=DE }:: [Mao](https://osu.ppy.sh/users/2204515) 的 [Mitose Noriko - Unreal Player](https://osu.ppy.sh/beatmapsets/828563#osu/173595
```suggestion
谱师通常会参考谱面已完成的部分，来让过渡段在游玩时尽可能顺滑，但也存在所谓的*双盲合作 (blind collabs)*，比如谱面主 ::{ flag=DE }:: [Mao](https://osu.ppy.sh/users/2204515) 的这张谱面：[Mitose Noriko - Unreal Player](https://osu.ppy.sh/beatmapsets/828563#osu/1735958)。在合作过程中，谱师只能在谱面完成后才能看到他人的部分。在这种情况下，一般统筹合作的人会在每节末尾放置打击物件，以此指示其他谱师继续作图的位置。
```

全文中一堆作图者都需要改成谱师

host暂且翻译成谱面主或者谱面拥有者

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Beatmap_host/zh.md
> +# 谱面所有者
修改意见同上，可以加谱面主tag或者直接改成这个

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Break/zh.md
> +# 休息时段
优先使用休息时间

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Difficulty_spread/zh.md
> +tags:
需要加 spread，本身国内交流的时候也有这种用法，没这种tag会舍本逐末

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Marathon/zh.md
> +马拉松图的定义后来改变为包含 5 分钟[掉血时间](/wiki/Beatmap/Drain_time)的图，允许[自定义难度命名](/wiki/Ranking_criteria/Difficulty_naming)。直到 2019 年引入更宽松的分布规则前，一直在使用此规则。
```suggestion
马拉松图的定义后来改变为至少包含 5 分钟[掉血时间](/wiki/Beatmap/Drain_time)的谱面，并且允许[自定义难度命名](/wiki/Ranking_criteria/Difficulty_naming)。直到 2019 年引入更宽松的难度分布规则前，此规则一直被使用。
```

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Stack_leniency/zh.md
> +![然而在游玩时，游戏会为玩家把物件斜向错开。](img/stacking-playtest.jpg "游玩时的堆叠打击物件")
```suggestion
![然而在游玩界面，为了便于玩家读图，游戏会把物件斜向排开。](img/stacking-playtest.jpg "游玩界面的堆叠打击物件")
```

2023-07-11 17:15 UTC, YumeMuzi commented on wiki/Beatmap/Stack_leniency/zh.md
> +![编辑时堆叠打击物件会让它们于顶部互相重叠。](img/stacking-editor.jpg "编辑时堆叠打击物件")
```suggestion
![编辑界面的堆叠打击物件会完全重叠。](img/stacking-editor.jpg "编辑界面的堆叠打击物件")
```

2023-07-13 11:32 UTC, Walavouchey approved these changes

2023-07-13 11:39 UTC, merged