[ES] Review `Client/Installation`
ppy/osu-wiki pull request #9621
Opened 2023-07-03 15:11 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-03 20:32 UTC, UnknownOsu requested changes

2023-07-03 20:32 UTC, UnknownOsu commented on wiki/Client/Installation/es.md
> +*Nota: Debes tener una etiqueta osu!supporter y una conexión a Internet para usar osu!direct.*
```suggestion
*Nota: Debes tener una etiqueta de osu!supporter y una conexión a internet para usar osu!direct.*
```

2023-07-03 20:32 UTC, UnknownOsu commented on wiki/Client/Installation/es.md
> +3. Dependiendo de cómo el desollador haya empaquetado su skin, es posible que debas hacer cosas diferentes.
```suggestion
3. Dependiendo de cómo el creador haya empaquetado su skin, es posible que debas hacer cosas diferentes.
```

2023-07-03 20:32 UTC, UnknownOsu commented on wiki/Client/Installation/es.md
> +     2. osu! procesará la skin y lo seleccionará automáticamente para ti.
```suggestion
     2. osu! procesará la skin y la seleccionará automáticamente para ti.
```

2023-07-03 20:33 UTC, UnknownOsu commented on wiki/Client/Installation/es.md
> +3. Dependiendo de cómo el desollador haya empaquetado su skin, es posible que debas hacer cosas diferentes.
También puede ser que se deje en su forma original, a tu criterio.

2023-07-13 11:16 UTC, Walavouchey approved these changes

2023-07-13 11:18 UTC, merged