[IT] Update `Main_page`
ppy/osu-wiki pull request #9627
Opened 2023-07-04 11:26 UTC by Sclafus

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-04 11:34 UTC, arancinosbarazzino requested changes

2023-07-04 11:34 UTC, arancinosbarazzino commented on wiki/Main_page/it.md
> +[Projects](/wiki/Community/Projects) • [Guilda dei Mapper](/wiki/Community/Mappers_Guild) • [Progetto Amata](/wiki/Community/Project_Loved) • [Meeting della community di osu!](/wiki/Community/osu!_co
```suggestion
[Projects](/wiki/Community/Projects) • [Gilda dei Mapper](/wiki/Community/Mappers_Guild) • [Progetto Amata](/wiki/Community/Project_Loved) • [Meeting della community di osu!](/wiki/Community/osu!_community_meetings) • [osu!academy](/wiki/Community/Video_series/osu!academy) • [osu!mapping](/wiki/Community/Video_series/osu!mapping) • [osu!monthly](/wiki/Community/osu!monthly) • [osu!talk](/wiki/Community/Video_series/osu!talk)
```

2023-07-04 11:34 UTC, arancinosbarazzino commented on wiki/Main_page/it.md
> +Fai la tua parte: [Come e in cosa aiutare](/wiki/Community/How_you_can_help!) • [Segnala comportamenti scorretti](/wiki/Reporting_bad_behaviour) • [Segnala abuso](/wiki/Reporting_bad_behaviour/Abuse)
```suggestion
Fai la tua parte: [Come e in cosa aiutare](/wiki/Community/How_you_can_help!) • [Segnala comportamenti scorretti](/wiki/Reporting_bad_behaviour) • [Segnala abuso](/wiki/Reporting_bad_behaviour/Abuse) • [Segnala i cheater](/wiki/Reporting_bad_behaviour/Handling_foul_play)
```

2023-07-04 11:34 UTC, arancinosbarazzino commented on wiki/Main_page/it.md
> +[Storia di osu!](/wiki/History_of_osu!) • [Storia del Classifiche Online](/wiki/History_of_osu!/Online_rankings) • [Storia della wiki di osu!](/wiki/History_of_osu!/osu!_wiki) • [Timeline del mapping
```suggestion
[Storia di osu!](/wiki/History_of_osu!) • [Storia delle Classifiche Online](/wiki/History_of_osu!/Online_rankings) • [Storia della wiki di osu!](/wiki/History_of_osu!/osu!_wiki) • [Timeline del mapping e del modding](/wiki/History_of_osu!/Mapping_and_modding_timeline) • [Pesci d'aprile](/wiki/History_of_osu!/April_Fools)
```

2023-07-04 11:35 UTC, arancinosbarazzino approved these changes

2023-07-12 10:07 UTC, marcostudios approved these changes

2023-07-13 11:51 UTC, Walavouchey approved these changes

2023-07-13 11:58 UTC, merged