[IT] Update `People/Support_Team`
ppy/osu-wiki pull request #9646
Opened 2023-07-09 20:31 UTC by Sclafus

This PR also adds `meta/group-info` for the italian language.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-12 08:38 UTC, Nakkeraru requested changes

2023-07-12 08:38 UTC, Nakkeraru commented on meta/group-info/it.yaml
> +    chat: moderatione della chat
```suggestion
    chat: moderazione della chat
```

2023-07-12 08:38 UTC, Nakkeraru commented on meta/group-info/it.yaml
> +    forum: moderatione del forum
```suggestion
    forum: moderazione del forum
```

2023-07-12 08:38 UTC, Nakkeraru commented on wiki/People/Support_Team/it.md
> +2. Oraganizzare le discussioni in [Richieste di Funzionalità](https://osu.ppy.sh/community/forums/4) e [Aiuto](https://osu.ppy.sh/community/forums/5) e contrassegnarle come *Risolte*, *Confermate*, *
```suggestion
2. Organizzare le discussioni in [Richieste di Funzionalità](https://osu.ppy.sh/community/forums/4) e [Aiuto](https://osu.ppy.sh/community/forums/5) e contrassegnarle come *Risolte*, *Confermate*, *Non Valide*, *Duplicate* e/o *Aggiunte*.
```

2023-07-12 11:25 UTC, Nakkeraru approved these changes

2023-07-13 11:55 UTC, Walavouchey approved these changes

2023-07-13 12:07 UTC, merged