Add `Centurions` article
ppy/osu-wiki pull request #9653
Opened 2023-07-11 11:18 UTC by Hiviexd

making the centurion table was as painful as it looks

2023-07-11 13:42 UTC, Walavouchey commented on wiki/People/Centurions/en.md
> +- The Centurion [beatmap packs](/wiki/Beatmap/Packs): for each 100 Ranked beatmaps, the mapper will be granted the opportunity to select 10 beatmaps to be included in a beatmap pack, which will be av
```suggestion
- The Centurion [beatmap packs](/wiki/Beatmap/Packs): for each 100 Ranked beatmaps, the mapper will be granted the opportunity to select 10 beatmaps to be included in a beatmap pack, which will be available for download in the [theme category](https://osu.ppy.sh/beatmaps/packs?type=theme) of the beatmap pack listing.
```

2023-07-11 13:48 UTC, Hiviexd commented on wiki/People/Centurions/en.md
> +![Centurion badge](img/centurion.png "Centurion Mapper (100+ Beatmaps Ranked)")
i wanted to match the tooltip

![](https://nats.are-la.me/61a2TgJ.png)

2023-07-11 14:00 UTC, Walavouchey commented on wiki/People/Centurions/en.md
> +![Centurion badge](img/centurion.png "Centurion Mapper (100+ Beatmaps Ranked)")
it's not done like that anywhere else in the wiki

2023-07-11 14:21 UTC, Walavouchey approved these changes

2023-07-11 14:45 UTC, Ephemeralis requested changes

2023-07-12 03:54 UTC, peppy approved these changes

2023-07-12 03:54 UTC, merged