[DE] Update various articles
ppy/osu-wiki pull request #9663
Opened 2023-07-12 11:12 UTC by The-Last-Cookie

Articles:

- `osu! tournament client/Setup`
- `Ranking criteria/osu!taiko`
- `Main page`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-12 14:47 UTC, respektive requested changes

2023-07-12 14:47 UTC, respektive commented on wiki/Ranking_criteria/osu!taiko/de.md
> +- **Finisher-Notes für 1/4-Patterns in dieser Schwierigkeitsstufe dürfen nur am Ende des Patterns platziert werden und müssen die entgegengesetzte Farbe als die vorhergehende Note haben.** Andere Pla
```suggestion
- **Finisher-Notes für 1/4-Patterns in dieser Schwierigkeitsstufe dürfen nur am Ende des Patterns platziert werden und müssen die entgegengesetzte Farbe der vorhergehenden Note haben.** Andere Platzierungen können die Lesbarkeit für das Zielpublikum zu stark beeinträchtigen.
```

2023-07-13 16:24 UTC, respektive approved these changes

2023-07-17 13:08 UTC, The-Last-Cookie commented on wiki/Main_page/de.md
> +[Community-Mitwirkende](/wiki/People/Community_Contributors) • [Benutzergruppe](/wiki/People/User_group) • [Benutzer mit einzigartigen Titeln](/wiki/People/Users_with_unique_titles) • [Centurions](/w
```suggestion
[Community-Mitwirkende](/wiki/People/Community_Contributors) • [Elite Nominators](/wiki/People/Elite_Nominators) • [Benutzergruppe](/wiki/People/User_group) • [Benutzer mit einzigartigen Titeln](/wiki/People/Users_with_unique_titles) • [Centurions](/wiki/People/Centurions) • [Turnierkomitee](/wiki/People/Tournament_Committee) • [Performance-Punkte-Komitee](/wiki/People/Performance_Points_Committee) • [Betreuer des osu!-Wikis](/wiki/People/osu!_wiki_maintainers)
```

2023-07-18 18:07 UTC, TicClick approved these changes

2023-07-18 18:16 UTC, merged