[ZH] Add `Beatmap/Packs`
ppy/osu-wiki pull request #9666
Opened 2023-07-12 15:23 UTC by CloneWith

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-16 13:42 UTC, Sitoria commented
PR approved

2023-07-25 08:53 UTC, YumeMuzi requested changes

2023-07-25 08:53 UTC, YumeMuzi commented on wiki/Beatmap/Packs/zh.md
> +  - 曲包
```suggestion
  - 曲包
  - 谱面包
```

2023-07-25 08:53 UTC, YumeMuzi commented on wiki/Beatmap/Packs/zh.md
> +| **A** | 艺术家/专辑 | 来自特定艺术家或专辑的歌曲 |
```suggestion
| **A** | 艺术家/专辑 | 谱面内的歌曲来自特定艺术家或他们的专辑 |
```

2023-07-25 08:53 UTC, YumeMuzi commented on wiki/Beatmap/Packs/zh.md
> +如果想要批量下载曲包而非一个个下载它们，你可以使用 Torrent 工具，从以下站点下载：
```suggestion
### 用种子下载

如果你想要批量下载曲包，而非一个个下载它们，可以使用种子工具，并从以下站点下载：
```

2023-07-25 08:53 UTC, YumeMuzi commented on wiki/Beatmap/Packs/zh.md
> +  - [glukki](https://osu.ppy.sh/users/14285150) 的 [Resilio Sync 上的 Torrent 文件](https://link.resilio.com/#f=osu%21%20Beatmap%20Packs&sz=19E2&t=1&s=JHR4G3EUWCAOAKJT6HITFDGMENTSXU7U&i=CASDYUCU4VP4JUMPRY
Torrent 改成种子

2023-07-26 03:38 UTC, YumeMuzi approved these changes

2023-07-29 15:02 UTC, TicClick approved these changes

2023-07-29 15:05 UTC, merged