[IT] Update `Mascots`
ppy/osu-wiki pull request #9671
Opened 2023-07-13 10:24 UTC by Nakkeraru

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-13 14:24 UTC, Sclafus requested changes

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +Disegnata da [pyun](https://osu.ppy.sh/users/981534), Chirou era una delle partecipanti del design contest delle mascotte di osu!taiko. É molto severa e esigente, una perfezionista che non ama commet
```suggestion
Disegnata da [pyun](https://osu.ppy.sh/users/981534), Chirou era una delle partecipanti del design contest delle mascotte di osu!taiko. È molto severa e esigente, una perfezionista che non ama commettere errori soprattutto mentre gioca ad osu!taiko. Ma al di là del suo aspetto severo, se riesci a raggiungere il suo lato dolce, può essere gentile e premurosa. Ha 14 anni, nata il 25 Ottobre, gruppo sanguigno AB. È alta 150cm e pesa 45Kg. I suoi hobby includono esercitarsi a suonare la batteria, stare al caldo con la sua coperta e collezionare gemme o rocce. Chirou è apparsa in diverse fanart create dagli utenti.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +pippi, stilizzata con una "p" minuscola, è la mascotte della modalità di gioco osu! dal 2008-07. È anche conosciuta come pippidon in osu!taiko e appare in [Yandere Simulator](https://yanderesimulator
```suggestion
pippi, stilizzata con una "p" minuscola, è la mascotte della modalità di gioco osu! dal 2008-07. È anche conosciuta come pippidon in osu!taiko e appare in [Yandere Simulator](https://yanderesimulator.com) come un NPC. La concept art iniziale è stata creata da [Sarumaru](https://osu.ppy.sh/users/9427), la grafica è stata creata da [crystalsuicune](https://osu.ppy.sh/users/9974), e il disegno attuale è stato progetto da [Daru](https://osu.ppy.sh/users/32480).
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +Mani è un po' un ribelle, sempre alla ricerca di nuovi stili e cose da esplorare, mentre sua sorella Mari (precedentemente conosciuta come Maria) è una classica perfezionista, rigida con una predilez
```suggestion
Mani è un po' un ribelle, sempre alla ricerca di nuovi stili e cose da esplorare, mentre sua sorella Mari (precedentemente conosciuta come Maria) è una classica perfezionista, rigida e le piace stare al centro dell'attenzione. Vanno d'accordo come l'olio e l'acqua.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +Mocha é la mascotte di osu!taiko. Inizialmente é stata disegnata durante il [sesto concorso di fantart](https://osu.ppy.sh/community/contests/2) da [Crowie](https://osu.ppy.sh/users/6894067), che si
```suggestion
Mocha è la mascotte di osu!taiko. Inizialmente è stata disegnata durante il [sesto concorso di fantart](https://osu.ppy.sh/community/contests/2) da [Crowie](https://osu.ppy.sh/users/6894067), che si è classificato 21esimo.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +## Cameo
```suggestion
## Camei
```
Not really sure about it

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +>Leader appassionato della squadra delle cheerleader. Ha un'anima generosa, aiuta chi é in difficoltá confortandoli e lottando per loro.
```suggestion
>Leader della squadra delle cheerleader. Ha un'anima generosa, aiuta chi è in difficoltà confortandoli e lottando per loro.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +一本木龍太 (Ryūta Ippongi) ha raccolto frutta in osu!catch dal 2008 fino al 2014, dove poi é stato sostituito da [Yuzu](#yuzu). É stato creato dalla [iNiS Corporation](https://en.wikipedia.org/wiki/INiS)
```suggestion
一本木龍太 (Ryūta Ippongi) ha raccolto frutta in osu!catch dal 2008 fino al 2014, dove poi è stato sostituito da [Yuzu](#yuzu). È stato creato dalla [iNiS Corporation](https://en.wikipedia.org/wiki/INiS) e faceva parte del vecchio sito web. Compare anche in [Yandere Simulator](https://yanderesimulator.com) come un NPC.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +Agente J, conosciuto anche come BA-2 (Beat Agent-2) o J, é stata una delle mascotte di osu! dal 2008, per poi ritirarsi nel 2014, E'stato creato dalla iNiS Corporation e faceva parte del vecchio sito
```suggestion
Agente J, conosciuto anche come BA-2 (Beat Agent-2) o J, è stata una delle mascotte di osu! dal 2008 fino al 2014. È stato creato dalla iNiS Corporation e faceva parte del vecchio sito web.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +> Don é il protagonista della serie [Taiko no Tatsujin](https://en.wikipedia.org/wiki/Taiko_no_Tatsujin). Ë un tamburo taiko con il bordo bianco e quattro gambe, un viso rosso (che sembra di un aranc
```suggestion
> Don è il protagonista della serie [Taiko no Tatsujin](https://en.wikipedia.org/wiki/Taiko_no_Tatsujin). È un tamburo taiko con il bordo bianco e quattro gambe, un viso rosso (che sembra di un arancione acceso), e un corpo blu chiaro. Il sogno di Don è condividere la bellezza di Taiko con il resto del mondo. Sono passati 3 anni da quando si è trasferito nelle Wada House, ed è diventato abbastanza popolare nella cittadina. Ha un appetito mostruoso, e alcune volte fa spese costose nella Wada House, il che può portare al peggio. Molto spesso finisce le sue frasi con "Ta-don", che significa "Ba-dum" in Giapponese.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +和田どん (Wada Don), conosciuto anche come Don o Don-chan, é stata una della mascotte di osu!taiko da Maggio 2008. É alto 48cm e pesa piú di 100kg. Compare nella skin di osu!taiko. Il suo disegno é stato
```suggestion
和田どん (Wada Don), conosciuto anche come Don o Don-chan, è stata una della mascotte di osu!taiko da Maggio 2008. È alto 48cm e pesa più di 100kg. Compare nella skin di osu!taiko. Il suo disegno è stato fatto da Yukiko Yokoo (横尾有希子) e gli è stata data una voce da Narahashi Miki (楢橋 美紀).
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +Disegnata da [JMC](https://osu.ppy.sh/users/774010), Aiko era una delle partecipanti del design contest delle mascotte di osu!taiko. É una ragazza energica con una passione per osu!taiko, anche se no
```suggestion
Disegnata da [JMC](https://osu.ppy.sh/users/774010), Aiko era una delle partecipanti del design contest delle mascotte di osu!taiko. È una ragazza energica con una passione per osu!taiko, anche se non è la migliore! Indossando un paio di "Tabi" eleganti e una serie di accessori di Pippidon, la mascotte del passato vive in questa ragazza piena d'energia. È piuttosto bassa, con soli 154cm di altezza, ed è nata il 6 aprile 1999.
```

2023-07-13 14:24 UTC, Sclafus commented on wiki/Mascots/it.md
> +Disegnata da [\[ Glitch \]](https://osu.ppy.sh/users/3781400), Alisa era una delle partecipanti del design contest delle mascotte di osu!taiko. Gioca ad osu!taiko fin da bambina. Adora suonare canzon
```suggestion
Disegnata da [\[ Glitch \]](https://osu.ppy.sh/users/3781400), Alisa era una delle partecipanti del design contest delle mascotte di osu!taiko. Gioca ad osu!taiko fin da bambina. Adora suonare melodie per gli altri e ama la musica. Quando non sta dormendo o mangiando, gioca ad osu!taiko oppure a qualche videogioco retró per divertimento!
```

2023-07-15 08:50 UTC, Sclafus approved these changes

2023-07-18 17:44 UTC, TicClick approved these changes

2023-07-18 17:48 UTC, merged