[ES] Update `osu! originals`
ppy/osu-wiki pull request #9674
Opened 2023-07-13 14:05 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-16 20:41 UTC, Repflez requested changes

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [Mapping With Rewards (Sep. 2015)](https://blog.ppy.sh/post/129936251068/mapping-with-rewards-sep-2015)*
```suggestion
*Para la publicación de la noticia, véase: [Mapping With Rewards (Sep. 2015)](https://blog.ppy.sh/post/129936251068/mapping-with-rewards-sep-2015)*
```
Previous was correct.

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [New Featured Artist: happy30](https://osu.ppy.sh/home/news/2022-11-02-new-featured-artist-happy30)*
```suggestion
*Para la publicación de la noticia, véase: [New Featured Artist: happy30](https://osu.ppy.sh/home/news/2022-11-02-new-featured-artist-happy30)*
```
Previous was correct.

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [New Featured Artist: James Landino](https://osu.ppy.sh/home/news/2019-05-31-new-featured-artist-james-landino)*
```suggestion
*Para la publicación de la noticia, véase: [New Featured Artist: James Landino](https://osu.ppy.sh/home/news/2019-05-31-new-featured-artist-james-landino)*
```
Previous was correct.

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [New Featured Artist: kiraku](https://osu.ppy.sh/home/news/2020-09-26-new-featured-artist-kiraku)*
```suggestion
*Para la publicación de la noticia, véase: [New Featured Artist: kiraku](https://osu.ppy.sh/home/news/2020-09-26-new-featured-artist-kiraku)*
```
Previous was correct.

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [New Featured Artist: Kitazawa Kyouhei](https://osu.ppy.sh/home/news/2021-05-15-new-featured-artist-kitazawa-kyouhei)*
```suggestion
*Para la publicación de la noticia, véase: [New Featured Artist: Kitazawa Kyouhei](https://osu.ppy.sh/home/news/2021-05-15-new-featured-artist-kitazawa-kyouhei)*
```
Previous was correct.

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [New Featured Artist: ZxNX](https://osu.ppy.sh/home/news/2022-07-30-new-featured-artist-zxnx)*
```suggestion
*Para la publicación de la noticia, véase: [New Featured Artist: ZxNX](https://osu.ppy.sh/home/news/2022-07-30-new-featured-artist-zxnx)*
```
Previous was correct.

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [Community Mapping Contest #1 - yuki. (Nadeshiko Sensation)](https://osu.ppy.sh/home/news/2016-09-28-community-mapping-contest-1-yuki-nadeshiko)*
```suggestion
*Para la publicación de la noticia, véase: [Community Mapping Contest #1 - yuki. (Nadeshiko Sensation)](https://osu.ppy.sh/home/news/2016-09-28-community-mapping-contest-1-yuki-nadeshiko)*
```
Previous was correct.

2023-07-16 20:41 UTC, Repflez commented on wiki/osu!_originals/es.md
> +*Para la publicación de noticia, véase: [New Featured Artist: Rabbit House](https://osu.ppy.sh/home/news/2022-02-23-new-featured-artist-rabbit-house)*
```suggestion
*Para la publicación de la noticia, véase: [New Featured Artist: Rabbit House](https://osu.ppy.sh/home/news/2022-02-23-new-featured-artist-rabbit-house)*
```
Previous was correct.

2023-07-17 04:57 UTC, Repflez approved these changes
LGTM

2023-07-17 19:29 UTC, Walavouchey approved these changes

2023-07-17 19:30 UTC, merged