[IT] Update `People/osu!_team`
ppy/osu-wiki pull request #9684
Opened 2023-07-15 09:25 UTC by Sclafus

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-15 15:43 UTC, Nakkeraru requested changes

2023-07-15 15:43 UTC, Nakkeraru commented on wiki/People/osu!_team/it.md
> +| ::{ flag=US }:: [pishifat](https://osu.ppy.sh/users/3178418) | Consigliere della scena Modding e mapping, organizzatore della Guilda dei Mapper, ricercatore degli Artisti in Primo Piano |
```suggestion
| ::{ flag=US }:: [pishifat](https://osu.ppy.sh/users/3178418) | Consigliere della scena Modding e mapping, organizzatore della Gilda dei Mapper, ricercatore degli Artisti in Primo Piano |
```

2023-07-15 15:43 UTC, Nakkeraru commented on wiki/People/osu!_team/it.md
> +| ::{ flag=CA }:: [Nyquill](https://osu.ppy.sh/users/682935) | Sviluppatore di osu!, organizzatore della Guilda dei Mapper |
```suggestion
| ::{ flag=CA }:: [Nyquill](https://osu.ppy.sh/users/682935) | Sviluppatore di osu!, organizzatore della Gilda dei Mapper |
```

2023-07-15 15:45 UTC, Nakkeraru approved these changes

2023-07-18 17:47 UTC, TicClick approved these changes

2023-07-18 17:51 UTC, merged