[IT] Update `Mascots/Gallery`
ppy/osu-wiki pull request #9688
Opened 2023-07-15 16:51 UTC by Nakkeraru

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-15 16:57 UTC, Sclafus requested changes

2023-07-15 16:57 UTC, Sclafus commented on wiki/Mascots/Gallery/it.md
> +![Comboburst predefiniti della prima versione della skin di osu! ](img/pippi-original-comboburst.png "Comboburst predefiniti della prima versione della skin di osu!")
```suggestion
![Comboburst predefiniti della prima versione della skin di osu!](img/pippi-original-comboburst.png "Comboburst predefiniti della prima versione della skin di osu!")
```

2023-07-15 16:57 UTC, Sclafus commented on wiki/Mascots/Gallery/it.md
> +![Vecchia immagine di errore 404 del vecchio sito web](img/pippi-original-website-404.jpg "Vecchia immagine di errore 404 del vecchio sito web")
```suggestion
![Immagine di errore 404 del vecchio sito web](img/pippi-original-website-404.jpg "Immagine di errore 404 del vecchio sito web")
```

2023-07-15 16:57 UTC, Sclafus commented on wiki/Mascots/Gallery/it.md
> +![pippi illustrata da Daru](img/pippi-original-installer.jpg "pippi illustrata da Daru (una volta si trovava nel vecchio installer di osu!)")
```suggestion
![pippi illustrata da Daru](img/pippi-original-installer.jpg "pippi illustrata da Daru (una volta si trovava nell'installer di osu!)")
```

2023-07-15 16:58 UTC, Sclafus requested changes

2023-07-15 16:58 UTC, Sclafus commented on wiki/Mascots/Gallery/it.md
> +- [Fan Art 6: mascotte osu!taiko ](https://osu.ppy.sh/community/contests/2)
```suggestion
- [Fan Art 6: mascotte osu!taiko](https://osu.ppy.sh/community/contests/2)
```

2023-07-15 17:02 UTC, Sclafus approved these changes

2023-07-18 17:50 UTC, TicClick approved these changes

2023-07-18 17:56 UTC, merged