[IT] Added Multiple Stubs
ppy/osu-wiki pull request #9692
Opened 2023-07-15 19:50 UTC by Sclafus

This PR adds the following articles:
- `Bit_rate`
- `Gameplay/Dash`
- `Gameplay/Full_combo`
- `Gameplay/Hit_object/Slider/Slider_tick`
- `Gameplay/Hit_object/Slider/Reverse_slider`
- `Gameplay/Walk`
- `Gameplay/Pass`
- `History_of_osu!/Online_rankings`
- `History_of_osu!/Online_rankings/osu!`
- `History_of_osu!/Online_rankings/osu!taiko`
- `History_of_osu!/Online_rankings/osu!mania`
- `History_of_osu!/Online_rankings/osu!catch`
- `History_of_osu!/2009`
- `Modding/Mod_request`
- `Modding/Modder`
- `Modding/Normal_mod`
- `Modding/Kudosu`
- `Modding/Mod_for_mod`
- `Modding/Proto-bubble`
- `Modding/Star_priority`
- `Performance_points/ppv2`
- `Skinning/Skinner`
- `upppy`

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-15 20:23 UTC, Nakkeraru requested changes

2023-07-15 20:23 UTC, Nakkeraru commented on wiki/Modding/Normal_mod/it.md
> +*See also: [NM (disambiguazione)](/wiki/Disambiguation/NM).*
```suggestion
*Vedi anche: [NM (disambiguazione)](/wiki/Disambiguation/NM).*
```

2023-07-15 20:25 UTC, Nakkeraru requested changes

2023-07-15 20:25 UTC, Nakkeraru commented on wiki/Modding/Normal_mod/it.md
> +# Normal mod
```suggestion
# Mod normale
```

2023-07-15 20:44 UTC, marcostudios approved these changes

2023-07-15 20:44 UTC, marcostudios commented on wiki/Gameplay/Pass/it.md
> +Un **pass** descrive il completamento di una [beatmap](/wiki/Beatmap) o di una certa sezione di una beatmap senza l'utilizzo di [mods](/wiki/Gameplay/Game_modifier) che prevengo il fail (e.g. [No Fai
```suggestion
Un **pass** descrive il completamento di una [beatmap](/wiki/Beatmap) o di una certa sezione di una beatmap senza l'utilizzo di [mods](/wiki/Gameplay/Game_modifier) che prevengono il fail (e.g. [No Fail](/wiki/Gameplay/Game_modifier/No_Fail)), o arrivare ad una pausa con più del 50% di [vita](/wiki/Gameplay/Health). Nel caso di raggiungimento di una pausa, un indicatore acustico indica che il giocatore ha superato la sezione precedente.
```

2023-07-15 20:45 UTC, Nakkeraru approved these changes

2023-07-15 23:30 UTC, GYGY88 requested changes

2023-07-15 23:30 UTC, GYGY88 commented on wiki/History_of_osu!/Online_rankings/it.md
> +Numerosi giocatori hanno occupato il primo posto in ogni modalità di gioco con diversi sistemi di classifica. Il sistema attuale utilizzato da tutte le modalità di gioco per le classifiche online è [
```suggestion
Numerosi giocatori hanno raggiunto il primo posto in ogni modalità di gioco con diversi sistemi di classifica. Il sistema attuale utilizzato da tutte le modalità di gioco per le classifiche online è [ppv2](/wiki/Performance_points/ppv2).
```

2023-07-15 23:30 UTC, GYGY88 commented on wiki/Modding/Kudosu/it.md
> +**Kudosu** è un sistema di ricompense per il [modding](/wiki/Modding). Assegna punti per le risposte corrette dei mod nelle [discussioni delle beatmap](/wiki/Beatmap_discussion). I punti accumulati p
```suggestion
**Kudosu** è un sistema di ricompense per il [modding](/wiki/Modding). Assegna punti per le mod risolte nelle [discussioni delle beatmap](/wiki/Beatmap_discussion). I punti accumulati possono essere visualizzati nella pagina del profilo di un utente.
```

2023-07-15 23:30 UTC, GYGY88 commented on wiki/Modding/Modder/it.md
> +Un **modder** è un utente che aiuta altri creatori di beatmap a migliorare le loro [beatmap](/wiki/Beatmap) attraverso il [modding](/wiki/Modding). Risposte corrette in una [discussione della beatmap
```suggestion
Un **modder** è un utente che aiuta altri creatori di beatmap a migliorare le loro [beatmap](/wiki/Beatmap) attraverso il [modding](/wiki/Modding). Mod utili in una [discussione della beatmap](/wiki/Beatmap_discussion) conferiscono al modder [Kudosu!](/wiki/Modding/Kudosu) che può essere visualizzato nella pagina del profilo dell'utente.
```

2023-07-15 23:30 UTC, GYGY88 commented on wiki/Modding/Star_priority/it.md
> +   - La star priority di una mappa è determinata dal numero di messaggi dei mod che hanno ottenuto kudosu nel [thread della beatmap](/wiki/Modding/Forum_modding), la somma delle stelle kudosu che il
```suggestion
   - La star priority di una mappa è determinata dal numero di messaggi delle mod che hanno ottenuto kudosu nel [thread della beatmap](/wiki/Modding/Forum_modding), la somma delle stelle kudosu che il set di mappe ha ricevuto.
```

2023-07-15 23:40 UTC, GYGY88 approved these changes

2023-07-18 17:55 UTC, TicClick approved these changes

2023-07-18 18:03 UTC, merged