[ZH] Add `Centurions`
ppy/osu-wiki pull request #9694
Opened 2023-07-16 02:57 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-19 13:53 UTC, CloneWith requested changes

2023-07-19 13:53 UTC, CloneWith commented on wiki/People/Centurions/zh.md
> +- 百夫长[谱面包](/wiki/Beatmap/Packs)：对于玩家上架的每 100 张谱面，谱师可以选择其中 10 张谱面放入谱面包中。这个谱面包可以这些[谱面包列表](https://osu.ppy.sh/beatmaps/packs)的[主题分类](https://osu.ppy.sh/beatmaps/packs?type=theme)中找到并下载。
```suggestion
- 百夫长[谱面包](/wiki/Beatmap/Packs)：对于玩家上架的每 100 张谱面，谱师可以选择其中 10 张谱面放入谱面包中。这个谱面包可以在[谱面包列表](https://osu.ppy.sh/beatmaps/packs)的[主题分类](https://osu.ppy.sh/beatmaps/packs?type=theme)中找到并下载。
```

2023-07-26 03:10 UTC, CloneWith approved these changes

2023-07-29 15:04 UTC, TicClick approved these changes

2023-07-29 15:07 UTC, merged