[ZH] Update `User title`
ppy/osu-wiki pull request #9695
Opened 2023-07-16 03:24 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-27 09:05 UTC, CloneWith requested changes

2023-07-27 09:05 UTC, CloneWith commented on wiki/Community/User_title/zh.md
> +![Ephemeral 的个人主页截图](img/dev.png?1 "在 Ephemeral 的主页上方可以看到 \"osu!team\" 头衔")
这里漏了 [原文第 13 行](https://github.com/ppy/osu-wiki/blob/master/wiki/Community/User_title/en.md?plain=1#L13)

2023-07-29 09:47 UTC, CloneWith approved these changes

2023-07-29 14:50 UTC, TicClick approved these changes

2023-07-29 14:51 UTC, merged