[IT] Added `Client/File_Formats/*`
ppy/osu-wiki pull request #9701
Opened 2023-07-16 11:12 UTC by massimoty

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-16 13:05 UTC, Sclafus reviewed
Added the CI requested changes

2023-07-16 13:05 UTC, Sclafus commented on wiki/Client/File_formats/osr_(file_format)/it.md
> +| Byte | Modalità di gioco del replay (0 = osu!Standard, 1 = Taiko, 2 = Catch the Beat, 3 = osu!mania).
```suggestion
| Byte | Modalità di gioco del replay (0 = osu!Standard, 1 = Taiko, 2 = Catch the Beat, 3 = osu!mania). |
```

2023-07-16 13:05 UTC, Sclafus commented on wiki/Client/File_formats/osr_(file_format)/it.md
> +| Breve | Numero di missioni
```suggestion
| Breve | Numero di missioni | 
```

2023-07-16 13:05 UTC, Sclafus commented on wiki/Client/File_formats/osr_(file_format)/it.md
> +| Byte | Combo perfetta/piena (1 = nessun errore, nessuna interruzione del cursore e nessun cursore finito in anticipo).
```suggestion
| Byte | Combo perfetta/piena (1 = nessun errore, nessuna interruzione del cursore e nessun cursore finito in anticipo). |
```

2023-07-16 13:05 UTC, Sclafus commented on wiki/Client/File_formats/osr_(file_format)/it.md
> +| Stringa | Grafico a barre della vita: coppie separate da virgole u/v, dove u è il tempo in millisecondi della canzone e v è un valore in virgola mobile da 0 a 1 che rappresenta la quantità di vita
```suggestion
| Stringa | Grafico a barre della vita: coppie separate da virgole u/v, dove u è il tempo in millisecondi della canzone e v è un valore in virgola mobile da 0 a 1 che rappresenta la quantità di vita che si ha in quel momento (0 = la barra della vita è vuota, 1= la barra della vita è piena). |
```

2023-07-16 13:05 UTC, Sclafus commented on wiki/Client/File_formats/osr_(file_format)/it.md
> +
```suggestion
```

2023-07-16 13:05 UTC, Sclafus commented on wiki/Client/File_formats/osr_(file_format)/it.md
> +| Mod | Informazioni memorizzate
```suggestion
| Mod | Informazioni memorizzate |
```

2023-07-18 17:44 UTC, githacki requested changes
Fix [`remark-lint:table-pipes`](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-table-pipes#readme) warning

2023-07-18 18:06 UTC, githacki commented on wiki/Client/File_formats/osr_(file_format)/it.md
> +| Breve | Numero di missioni |
```suggestion
| Breve | Numero di missioni |
```

2023-07-18 18:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +| Sezione | Descrizione | Tipo di contenuto
```suggestion
| Sezione | Descrizione | Tipo di contenuto |
```

2023-07-18 18:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +| Opzione | Tipo di valore | Descrizione | Valore predefinito
```suggestion
| Opzione | Tipo di valore | Descrizione | Valore predefinito |
```

2023-07-18 18:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +| `Mode` | Integer | Game mode (`0` = osu!, `1` = osu!taiko, `2` = osu!catch, `3` = osu!mania) | 0
```suggestion
| `Mode` | Integer | Game mode (`0` = osu!, `1` = osu!taiko, `2` = osu!catch, `3` = osu!mania) | 0 |
```

2023-07-18 18:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +| `OverlayPosition` | Stringa | Sorteggia l'ordine di sovrapposizione dei cerchi colpiti rispetto ai numeri colpiti (`NoChange` = usa l'impostazione della skin, `Below` = sorteggia le sovrapposizioni
```suggestion
| `OverlayPosition` | Stringa | Sorteggia l'ordine di sovrapposizione dei cerchi colpiti rispetto ai numeri colpiti (`NoChange` = usa l'impostazione della skin, `Below` = sorteggia le sovrapposizioni sotto i numeri, `Above` = sorteggia le sovrapposizioni sopra i numeri) | NoChange |
```

2023-07-18 18:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +| Opzione | Tipo di valore | Descrizione
```suggestion
| Opzione | Tipo di valore | Descrizione |
```

2023-07-18 18:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +| Opzione | Tipo di valore | Descrizione
```suggestion
| Opzione | Tipo di valore | Descrizione |
```

2023-07-18 18:08 UTC, githacki requested changes
Fix [`remark-lint:table-pipes`](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-table-pipes#readme) warning

2023-07-20 11:07 UTC, githacki requested changes
Fix [`remark-lint:no-undefined-references`](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-undefined-references#readme) warning

2023-07-20 11:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +### Trattenute (solo osu!mania)
```suggestion
### Note lunghe (solo osu!mania)
```

2023-07-20 11:07 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +Analogamente a osu!catch, gli oggetti colpiti in osu!mania non usano `y`. Per determinare la colonna si usa `x`; si veda la sezione [Holds] (#holds-(osu!mania-only)).
```suggestion
Analogamente a osu!catch, gli oggetti colpiti in osu!mania non usano `y`. Per determinare la colonna si usa `x`; si veda la sezione [Note lunghe] (#note-lunghe-(solo-osu!mania)).
```

2023-07-20 19:18 UTC, githacki requested changes
Further CI error fix

2023-07-20 19:18 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +Analogamente a osu!catch, gli oggetti colpiti in osu!mania non usano `y`. Per determinare la colonna si usa `x`; si veda la sezione [Note lunghe] (#note-lunghe-(solo-osu!mania)).
```suggestion
Analogamente a osu!catch, gli oggetti colpiti in osu!mania non usano `y`. Per determinare la colonna si usa `x`; si veda la sezione [Note lunghe](#note-lunghe-(solo-osu!mania)).
```

2023-07-21 08:51 UTC, Sclafus commented
Please fix it on your own @massimoty there's too much stuff that is wrong D:

2023-07-29 10:01 UTC, githacki requested changes
As per the [Italian osu! wiki contributors' glossary](https://github.com/osu-italy/osu-wiki#glossary):
- Hit samples -> Campioni audio
- Cursore -> Slider
- Keep data types untranslated
- Timing points -> Punti di tempo
- Timing section -> Sezione temporale
- Kiai time -> Sezione kiai

Please, continue the translation from line 158 on, being mindful of the aforementioned changes and the wording of the review comments sent so far.

2023-09-10 10:10 UTC, githacki requested changes
Apply #9846

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +
```suggestion
| 2 | Segna l'inizio di una nuova combo |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +I bit rimanenti sono utilizzati per distinguere le nuove combo e per saltare i colori delle combo (comunemente chiamato "colour hax"):
```suggestion
| 3 | Segna l'oggetto come spinner  |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +
```suggestion
| 4, 5, 6 | Un integer a 3 bit che specifica quanti colori della combo saltare, una pratica alla quale ci si riferisce con "colour hax". Rilevante solo se l'oggetto inizia una nuova combo |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +- 2: Nuova combo
```suggestion
| 7 | Segna l'oggetto come nota lunga di osu!mania |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +- 4-6: un intero a 3 bit che specifica quanti colori della combo saltare, se questo oggetto inizia una nuova combo.
```suggestion
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +- 0: Normale
```suggestion
| 0 | Normal |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +- 1: Fischio
```suggestion
| 1 | Whistle |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +- 2: Fine
```suggestion
| 2 | Finish |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +- 3: Battito di mani
```suggestion
| 3 | Clap |
```

2023-09-10 10:10 UTC, githacki commented on wiki/Client/File_formats/osu_(file_format)/it.md
> +
```suggestion

| Bit index | Meaning |
| :-- | :-- |
```

2023-09-20 13:55 UTC, TicClick commented
it's been 2 months since the PR was open -- is there anything left to do to get it merged in?

2023-09-20 18:04 UTC, githacki commented
> it's been 2 months since the PR was open -- is there anything left to do to get it merged in?

yes, there is, i had requested @massimoty to fix last 200 lines but he hasn't. atp i guess i'll just send a review for those last lines in these days and approval when it will be ready for merge

2023-12-23 22:25 UTC, Sclafus commented
I think this may be closed, we will address it in another PR.

2023-12-27 11:00 UTC, closed without merging