[ES] Clean up `Beatmapping`
ppy/osu-wiki pull request #9705
Opened 2023-07-16 15:01 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-26 14:53 UTC, UnknownOsu requested changes

2023-07-26 14:53 UTC, UnknownOsu commented on wiki/Beatmapping/es.md
>  Como osu! Es un juego basado en el ritmo, la canción/música que elijas mapear debe tener un ritmo obvio y constante.
```suggestion
Como osu! es un juego basado en el ritmo, la canción/música que elijas mapear debe tener un ritmo obvio y constante.
```

2023-07-26 14:53 UTC, UnknownOsu commented on wiki/Beatmapping/es.md
> +(Alternativamente, puedes moverun archivo de audio en la carpeta `Songs`.)
```suggestion
(Alternativamente, puedes mover un archivo de audio en la carpeta `Songs`).
```

2023-07-26 14:53 UTC, UnknownOsu commented on wiki/Beatmapping/es.md
>  Deberas completar esta información antes de crear otra [dificultad](/wiki/Beatmap/Difficulty).
```suggestion
Deberás completar esta información antes de crear otra [dificultad](/wiki/Beatmap/Difficulty).
```

2023-07-26 14:53 UTC, UnknownOsu commented on wiki/Beatmapping/es.md
>  Dependiendo de lo que hagas, puedes usar la pestaña de diseño mucho o nada en absoluto, si llegas a hacer [SBS](/wiki/Storyboard/Scripting) (secuencias de comandos del guión gráfico).
```suggestion
Dependiendo de lo que hagas, puedes usar la pestaña de diseño mucho o nada en absoluto, si llegas a hacer [SBS](/wiki/Storyboard/Scripting) (secuencias de comandos del storyboard).
```

2023-07-29 14:45 UTC, TicClick approved these changes

2023-07-29 14:46 UTC, merged