[ES] Clean up ´Gameplay/Hit object´
ppy/osu-wiki pull request #9707
Opened 2023-07-16 15:35 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-26 15:04 UTC, UnknownOsu requested changes

2023-07-26 15:04 UTC, UnknownOsu commented on wiki/Gameplay/Hit_object/es.md
> +Desde el punto de vista de la programación, las notas largas en osu!mania no son el equivalente a los sliders de osu!, aunque han sido agrupados juntos para la simplificación de la tabla. Otros eleme
```suggestion
Desde el punto de vista de la programación, las notas largas en osu!mania no son el equivalente a los deslizadores de osu!, aunque han sido agrupados juntos para la simplificación de la tabla. Otros elementos con los que no se interactúan durante el juego, como la barra de salud o las estrellas del kiai, se consideran mejoras del juego o parte de la interfaz del usuario.
```

2023-07-26 15:04 UTC, UnknownOsu commented on wiki/Gameplay/Hit_object/es.md
> +En osu!, el siguiente círculo o slider que se toca, se resalta con un brillo ligeramente mayor en comparación de los otros objetos en el campo de juego. Sin embargo, el resaltado ya no será más visib
```suggestion
En osu!, el siguiente círculo o deslizador que se toca, se resalta con un brillo ligeramente mayor en comparación de los otros objetos en el campo de juego. Sin embargo, el resaltado ya no será más visible cuando la [velocidad de aproximación](/wiki/Beatmap/Approach_rate) sea demasiado alta.
```

2023-07-26 15:04 UTC, UnknownOsu commented on wiki/Gameplay/Hit_object/es.md
> +Desde el punto de vista de la programación, las notas largas en osu!mania no son el equivalente a los sliders de osu!, aunque han sido agrupados juntos para la simplificación de la tabla. Otros eleme
Diría que es mejor que se quede como `deslizador(es)`, en la gran mayoría de artículos se muestra así. Pero como prefieras

2023-07-29 14:42 UTC, TicClick approved these changes

2023-07-29 14:43 UTC, merged