[ES] Update `Do you really want to ask peppy`
ppy/osu-wiki pull request #9708
Opened 2023-07-16 15:48 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-26 15:47 UTC, UnknownOsu requested changes

2023-07-26 15:47 UTC, UnknownOsu commented on wiki/Do_you_really_want_to_ask_peppy/es.md
> +¡Buenos días! peppy entiende tu necesidad de querer contactarlo personalmente, pero te pide que primero entiendas que este **no** es el lugar donde quieres pedirle ayuda o soporte. Él mantiene el sop
```suggestion
¡Buenos días! peppy entiende tu necesidad de querer contactarlo personalmente, pero te pide que primero entiendas que este **no** es el lugar donde quieres pedirle ayuda o soporte. Él mantiene el soporte de osu! independiente de los mensajes personales y también le resulta bastante difícil responder a los MP. Por lo tanto, te pide que hagas una de las siguientes opciones:
```

2023-07-26 15:47 UTC, UnknownOsu commented on wiki/Do_you_really_want_to_ask_peppy/es.md
> +¡Buenos días! peppy entiende tu necesidad de querer contactarlo personalmente, pero te pide que primero entiendas que este **no** es el lugar donde quieres pedirle ayuda o soporte. Él mantiene el sop
Creo que queda mejor así

2023-07-29 14:39 UTC, TicClick approved these changes

2023-07-29 14:42 UTC, merged