[ES] Add QAT articles
ppy/osu-wiki pull request #9709
Opened 2023-07-16 16:22 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-26 15:47 UTC, UnknownOsu requested changes

2023-07-26 15:47 UTC, UnknownOsu commented on wiki/People/Quality_Assurance_Team/es.md
> +## History
```suggestion
## Historia
```

2023-07-26 15:47 UTC, UnknownOsu commented on wiki/People/Quality_Assurance_Team/es.md
> +La reputación del QAT entre los mappers y jugadores fue mayormente negativa en respuesta a la frecuente descalificación de mapas que los usuarios creían que iban a clasificarse. Los jugadores estaban
```suggestion
La reputación del QAT entre los mappers y jugadores fue mayormente negativa en respuesta a la frecuente descalificación de mapas que los usuarios creían que iban a clasificarse. Los jugadores estaban en su mayoría disgustados con la pérdida de [puntos de rendimiento](/wiki/Performance_points) y los mappers no estaban de acuerdo con la aplicación de los estándares de calidad restrictivos por parte del QAT.
```

2023-07-26 17:01 UTC, agatemosu commented on wiki/People/Quality_Assurance_Team/es.md
> +La reputación del QAT entre los mappers y jugadores fue mayormente negativa en respuesta a la frecuente descalificación de mapas que los usuarios creían que iban a clasificarse. Los jugadores estaban
xd

2023-07-29 15:09 UTC, TicClick approved these changes

2023-07-29 15:12 UTC, merged