[ES] Update `Internet Relay Chat`
ppy/osu-wiki pull request #9712
Opened 2023-07-16 17:30 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-26 16:15 UTC, UnknownOsu requested changes

2023-07-26 16:15 UTC, UnknownOsu commented on wiki/Community/Internet_Relay_Chat/es.md
> +*Advertencia: Tu contraseña de IRC es diferente a la contraseña de tu cuenta. **No lo compartas con otros**.*
```suggestion
*Advertencia: Tu contraseña de IRC es diferente a la contraseña de tu cuenta. **No la compartas con otros**.*
```

2023-07-26 16:15 UTC, UnknownOsu commented on wiki/Community/Internet_Relay_Chat/es.md
> +| [mIRC](https://www.mirc.com/) | Ve a mIRC Options (`Tools` -> `Options` o `Alt` + `O`), selecciona `IRC`, haz clic en el botón `Events...` y selecciona `Hide` para uniones y partes |
```suggestion
| [mIRC](https://www.mirc.com/) | Ve a mIRC Options (`Tools` -> `Options` o `Alt` + `O`), selecciona `IRC`, haz clic en el botón `Events...` y selecciona `Hide` para uniones y partidas |
```

2023-07-26 16:58 UTC, agatemosu commented on wiki/Community/Internet_Relay_Chat/es.md
> +| [mIRC](https://www.mirc.com/) | Ve a mIRC Options (`Tools` -> `Options` o `Alt` + `O`), selecciona `IRC`, haz clic en el botón `Events...` y selecciona `Hide` para uniones y partes |
Es un parte https://datatracker.ietf.org/doc/html/rfc1459#section-4.2.2

2023-07-26 17:01 UTC, UnknownOsu commented on wiki/Community/Internet_Relay_Chat/es.md
> +| [mIRC](https://www.mirc.com/) | Ve a mIRC Options (`Tools` -> `Options` o `Alt` + `O`), selecciona `IRC`, haz clic en el botón `Events...` y selecciona `Hide` para uniones y partes |
Creo que se refiere a un mensaje de partida, como si estuviera dejando el canal

2023-07-29 14:54 UTC, TicClick approved these changes

2023-07-29 14:55 UTC, merged