[ES] Update `Beatmap Nominators`
ppy/osu-wiki pull request #9713
Opened 2023-07-16 18:33 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-26 10:06 UTC, agatemosu commented on wiki/People/Beatmap_Nominators/Expectations/es.md
> +*Véase también: [Reglas para los Beatmap Nominator](/wiki/People/Beatmap_Nominators/Rules)*
```suggestion
*Véase también: [Reglas para los Beatmap Nominators](/wiki/People/Beatmap_Nominators/Rules)*
```

2023-07-26 10:17 UTC, agatemosu commented on wiki/People/Beatmap_Nominators/es.md
> +*Véase también: [Reglas para los Beatmap Nominators](Rules), [Expectativas de los Beatmap Nominators](Expectations), [Información general para los Beatmap Nominators](General_Information) y [Converti
```suggestion
*Véase también: [Reglas para los Beatmap Nominators](Rules), [Expectativas de los Beatmap Nominators](Expectations), [Información general de los Beatmap Nominators](General_Information) y [Convertirse en Beatmap Nominator](Becoming_a_Beatmap_Nominator)*
```

2023-07-26 10:22 UTC, agatemosu commented on wiki/People/Beatmap_Nominators/es.md
> +Los nuevos miembros de Beatmap Nominators comienzan con un período de prueba de un mes. Si sus nominaciones y conducta son satisfactorios, serán promovidos a Beatmap Nominators completos luego de una
```suggestion
Los nuevos miembros de Beatmap Nominators comienzan con un período de prueba de un mes. Si sus nominaciones y conducta son satisfactorios, serán promovidos a Beatmap Nominators completos luego de una [evaluación](/wiki/People/Nomination_Assessment_Team/Evaluations) positiva. De lo contrario, permanecerán en período de prueba por otro mes o serán eliminados de Beatmap Nominators.
```

2023-07-26 16:37 UTC, UnknownOsu requested changes

2023-07-26 16:37 UTC, UnknownOsu commented on wiki/People/Beatmap_Nominators/es.md
> +Las tablas a continuación indican los modos de juego en donde cada Beatmap Nominator es formalmente calificado para nominar. *Nota: Todos los Beatmap Nominators hablan inglés en adición a a los idiom
```suggestion
Las tablas a continuación indican los modos de juego en donde cada Beatmap Nominator es formalmente calificado para nominar. *Nota: Todos los Beatmap Nominators hablan inglés en adición a los idiomas listados debajo a menos que se especifique otra cosa.*
```

2023-07-26 16:40 UTC, UnknownOsu commented
No me deja solicitar el cambio, pero en el artículo `Beatmap_Nominators/Expectations` en la línea 14 hay una doble `s` en `clasificado`

2023-07-29 14:57 UTC, TicClick approved these changes

2023-07-29 14:58 UTC, merged