[IT] Update `Tournaments/OWC/2013`
ppy/osu-wiki pull request #9718
Opened 2023-07-16 21:53 UTC by Sclafus

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-16 22:04 UTC, marcostudios reviewed
Domani controllo con calma se non lo fa qualcuno prima

2023-07-16 22:04 UTC, marcostudios commented on wiki/Tournaments/OWC/2013/it.md
> +1. La osu! World Cup è un torneo a squadre 4v4 basato sul paese.
```suggestion
1. La osu! World Cup è un torneo a squadre 4v4 tra nazioni.
```

Non so se è la migliore traduzione per questo però il senso di questa frase è quello

2023-07-16 22:09 UTC, Sclafus commented on wiki/Tournaments/OWC/2013/it.md
> +| ![Corona d'oro](/wiki/shared/crown-gold.png "1° posto") | 6 mesi di osu!supporter, badge per il profilo, trofeo OWC, [osu!tablet](https://osu.ppy.sh/community/forums/topics/169139) | ![Corona d'arg
```suggestion
| ![Corona d'oro](/wiki/shared/crown-gold.png "1° posto") | 6 mesi di osu!supporter, badge per il profilo, trofeo OWC, [osu!tablet](https://osu.ppy.sh/community/forums/topics/169139) | ![Corona d'argento](/wiki/shared/crown-silver.png "2° posto") |
```

2023-07-16 22:09 UTC, Sclafus commented on wiki/Tournaments/OWC/2013/it.md
> +
```suggestion
```

2023-07-19 07:23 UTC, Nakkeraru requested changes

2023-07-19 07:23 UTC, Nakkeraru commented on wiki/Tournaments/OWC/2013/it.md
> +| ![Corona di bronzo](/wiki/shared/crown-bronze.png "Terzo posto") | ::{ flag=PL }:: **Polonioa** (**[fartownik](https://osu.ppy.sh/users/56917)**, [AmaiHachimitsu](https://osu.ppy.sh/users/844815),
```suggestion
| ![Corona di bronzo](/wiki/shared/crown-bronze.png "Terzo posto") | ::{ flag=PL }:: **Polonia** (**[fartownik](https://osu.ppy.sh/users/56917)**, [AmaiHachimitsu](https://osu.ppy.sh/users/844815), [Beniek](https://osu.ppy.sh/users/1649633), [Niko](https://osu.ppy.sh/users/175141), [Piotrekol](https://osu.ppy.sh/users/304520), [rEdo](https://osu.ppy.sh/users/49329), [worst fl player](http://osu.ppy.sh/users/613592), [WubWoofWolf](https://osu.ppy.sh/users/39828)) |
```

2023-07-19 07:29 UTC, Nakkeraru requested changes

2023-07-19 07:29 UTC, Nakkeraru commented on wiki/Tournaments/OWC/2013/it.md
> +| ::{ flag=FI }:: | Finlandiaia | **[Soarezi](http://osu.ppy.sh/users/2097622)**, [ethox](https://osu.ppy.sh/users/441380), [fabbbyyy v2](https://osu.ppy.sh/users/1637452), [Juzaa](https://osu.ppy.sh
```suggestion
| ::{ flag=FI }:: | Finlandia | **[Soarezi](http://osu.ppy.sh/users/2097622)**, [ethox](https://osu.ppy.sh/users/441380), [fabbbyyy v2](https://osu.ppy.sh/users/1637452), [Juzaa](https://osu.ppy.sh/users/620661), [Souko](https://osu.ppy.sh/users/417431), [Subbie](https://osu.ppy.sh/users/1590138) |
```

2023-07-19 07:29 UTC, Nakkeraru commented on wiki/Tournaments/OWC/2013/it.md
> +| ::{ flag=KR }:: Corea del Sud | ::{ flag=LV }:: Lettonia | ::{ flag=FI }:: Finlandiaia | ::{ flag=EE }:: Estonia |
```suggestion
| ::{ flag=KR }:: Corea del Sud | ::{ flag=LV }:: Lettonia | ::{ flag=FI }:: Finlandia | ::{ flag=EE }:: Estonia |
```

2023-07-19 07:29 UTC, Nakkeraru commented on wiki/Tournaments/OWC/2013/it.md
> +| ![Corona di bronzo](/wiki/shared/crown-bronze.png "Terzo posto") | ::{ flag=PL }:: **Polonioa** (**[fartownik](https://osu.ppy.sh/users/56917)**, [AmaiHachimitsu](https://osu.ppy.sh/users/844815),
```suggestion
| ![Corona di bronzo](/wiki/shared/crown-bronze.png "Terzo posto") | ::{ flag=PL }:: **Polonia** (**[fartownik](https://osu.ppy.sh/users/56917)**, [AmaiHachimitsu](https://osu.ppy.sh/users/844815), [Beniek](https://osu.ppy.sh/users/1649633), [Niko](https://osu.ppy.sh/users/175141), [Piotrekol](https://osu.ppy.sh/users/304520), [rEdo](https://osu.ppy.sh/users/49329), [worst fl player](http://osu.ppy.sh/users/613592), [WubWoofWolf](https://osu.ppy.sh/users/39828)) |
```

2023-07-19 15:55 UTC, Sclafus commented on wiki/Tournaments/OWC/2013/it.md
> +| ![Corona di bronzo](/wiki/shared/crown-bronze.png "Terzo posto") | ::{ flag=PL }:: **Polonioa** (**[fartownik](https://osu.ppy.sh/users/56917)**, [AmaiHachimitsu](https://osu.ppy.sh/users/844815),
Duplicated comment

2023-07-19 16:25 UTC, marcostudios approved these changes

2023-07-19 16:25 UTC, marcostudios commented on wiki/Tournaments/OWC/2013/it.md
> +6. È consentito l'uso [Impostazioni visive](/wiki/Client/Interface/Visual_settings).
```suggestion
6. È consentito l'uso di [Impostazioni visive](/wiki/Client/Interface/Visual_settings).
```

2023-07-23 14:56 UTC, TicClick approved these changes

2023-07-23 14:58 UTC, merged