[IT] Add `Performance_troubleshooting`
ppy/osu-wiki pull request #9732
Opened 2023-07-18 23:11 UTC by marcostudios

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-19 16:40 UTC, Nakkeraru requested changes

2023-07-19 16:40 UTC, Nakkeraru commented on wiki/Performance_troubleshooting/it.md
> +Questo limitatore frame si basa su un meccanismo di sincronia verticale fornito dal driver. Garantisce che non ci sia lo screen tearing, ma aggiunge 1-2 frame di latenza a causa della necessità di fr
```suggestion
Questo limitatore frame si basa su un meccanismo di sincronia verticale fornito dal driver. Garantisce che non ci sia lo screen tearing, ma aggiunge 1-2 frame di latenza a causa della necessità di frame di buffering prima.
```

2023-07-20 08:02 UTC, Nakkeraru requested changes

2023-07-20 08:02 UTC, Nakkeraru commented on wiki/Performance_troubleshooting/it.md
> +- Apri il task manager e ordina la lista (sotto Dettagli) per CPU. Controlla eventuali alti utilizzi di CPU quando avvengono i cali, per esempio da un virus in background o uno scanner di malaware. P
```suggestion
- Apri il task manager e ordina la lista (sotto Dettagli) per CPU. Controlla eventuali alti utilizzi di CPU quando avvengono i cali, per esempio da un virus in background o uno scanner di malware. Puoi anche eseguire osu! in finestra o lasciare il task manager su un secondo display per diagnosticare questa cosa mentre giochi o vedi una mappa in autoplay.
```

2023-07-21 06:51 UTC, Nakkeraru approved these changes

2023-07-22 15:05 UTC, TicClick approved these changes

2023-07-22 15:09 UTC, merged