Add Vietnam language
ppy/osu-wiki pull request #9737
Opened 2023-07-21 03:40 UTC by khthch

I'm add in wiki/Help_centre

If anything have problem,I will check.Thank you!

2023-07-21 03:58 UTC, Sitoria commented
Title will be [VI] Add `Help centre`

2023-07-21 12:54 UTC, agatemosu requested changes

2023-07-22 07:05 UTC, khthch commented on wiki/Help_centre/vi.md
> +tags:
Sure.Hope I didn't do it wrong.

2023-07-22 08:15 UTC, MineTurtlee requested changes
Suggestion:
add no_native_review: true
[Reference here](https://github.com/MineTurtlee/osu-wiki/blob/master/wiki/Modding/Bubble/vi.md)

2023-07-22 08:43 UTC, agatemosu commented
that's added by a mantainer after two weeks if it doesn't get a native revies

2023-07-22 09:55 UTC, MineTurtlee commented
> I'm add in wiki/Help_centre
> 
> If anything have problem,I will check.Thank you!

[x] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
^^ Great, That's good!! ^^

2023-07-22 10:53 UTC, agatemosu commented
You don't need to master merges, a maintainer will do it

2023-07-24 08:11 UTC, Sitoria commented
> > I'm add in wiki/Help_centre
> > If anything have problem,I will check.Thank you!
> 
> [x] The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) ^^ Great, That's good!! ^^

addition) this is wrong,

when you open PR, you will see this `Self-Check Section`.

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

first one is `Self-Check`, see [this wiki page](https://osu.ppy.sh/wiki/vi/osu%21_wiki/Contribution_guide#t%E1%BB%B1-ki%E1%BB%83m-tra), check your md file and [x] 'd first one.
second one is for `This PR is reviewed by native person and approved.` ask your friend or VN users for grammer or sentence correctly smth **Review**. if native user think its done, then user *approved* this PR. then you can [x] 'd it second box.

(plus, you dont need to up-to-date your branch :p )

second box is checked, then wiki maintainers will approved your translation and merged it to wiki folder. if not, it will merged with `no_native_review` + `stale merge` . no matter to wiki translations, but wiki translation quality is guaranteed by other VN users.

hope you enjoy translating :>

2023-08-02 16:46 UTC, TicClick approved these changes
merging (no native review for one week or longer)

2023-08-02 16:52 UTC, merged