Add `Contribute to osu!'s News Content` news post
ppy/osu-wiki pull request #9739
Opened 2023-07-21 16:21 UTC by 0x84f

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-02 16:22 UTC, Blooshing requested changes
leaving these changes here to for more consistency for formal writing.

2023-08-02 16:22 UTC, Blooshing commented on news/2023/2023-07-08-writing-callout.md
> +Tournament hosts can now reach out to the [tournament committee](/wiki/People/Tournament_Committee) through email if they wish for their tournaments to be advertised, and after their review and discu
```Suggestion
Tournament hosts can now reach out to the [tournament committee](/wiki/People/Tournament_Committee) through email if they wish for their tournaments to be advertised, and after their review and discussion with the wiki and news team in the ``osu-news`` channel they will inform you with the final decision.
```

2023-08-02 16:22 UTC, Blooshing commented on news/2023/2023-07-08-writing-callout.md
> +- A good knowledge of the English language & its grammar
```Suggestion
- A good knowledge of the English language and its grammar
```

2023-08-02 16:22 UTC, Blooshing commented on news/2023/2023-07-08-writing-callout.md
> +After last years' efforts to spice up the front page with a variety of news posts via the [content call forum post](https://osu.ppy.sh/community/forums/topics/1605337), which led up to [osu!monthly](
```Suggestion
After last years' efforts to spice up the front page with a variety of news posts via the [content call forum post](https://osu.ppy.sh/community/forums/topics/1605337), which led up to [osu!monthly](/wiki/Community/osu!monthly) making a comeback for its [3rd season](/wiki/Community/osu!monthly#season-3-(2022–2023)) and a series of news posts by [0x84f](https://osu.ppy.sh/users/7944724), we wanted to spread the word further and make contributing more accessible to the community.
```

2023-08-03 13:45 UTC, 0x84f commented on news/2023/2023-07-08-writing-callout.md
> +If you are keen on sharing your writing with the community, the process is incredibly simple! Again, you can join the official Discord and share your drafts in the ``osu-news`` channel, where the wik
```suggestion
If you are keen on sharing your writing with the community, the process is incredibly simple! Again, you can join the official Discord and share your drafts in the ``osu-news`` channel, where the wiki and news contributors can evaluate your work, give feedback and help you with the process of pushing your work to the front page!
```

2023-08-21 10:53 UTC, merged