[IT] Added `Gameplay/Hit_object`
ppy/osu-wiki pull request #9750
Opened 2023-07-23 15:21 UTC by massimoty

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-23 15:53 UTC, Sclafus requested changes

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +Le *note* sono elementi con cui il player puo interagire durante il gioco di una [beatmap](/wiki/Beatmap). Ogni [game mode](/wiki/Game_mode) ha il suo set unico di note che cambia la esperienza di gi
```suggestion
Le *note* sono elementi con cui il giocatore può interagire durante una [beatmap](/wiki/Beatmap). Ogni [modalità di gioco](/wiki/Game_mode) ha il suo set unico di note che cambia l'esperienza di gioco. Per una panoramica sulle note di ciascuna modalità di gioco, guarda la seguente tabella:
```

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +<!-- TODO: should also have articles for each hit object -->
```suggestion
```

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +<!-- TODO: other games modes? =( -->
```suggestion
```

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +
```suggestion
```

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +
```suggestion
```

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +Dal punto di vista della programmazione, le note lunghe in osu!mania non sono uguali agli slider su osu!, anche se in questa tabella sono stati raggruppati insieme per semplificare. Altri elementi co
```suggestion
Dal punto di vista della programmazione, le note lunghe in osu!mania non sono uguali agli slider su osu!, anche se in questa tabella sono stati raggruppate insieme per semplificare. Altri elementi con cui non si interagisce durante il gioco, come la barra della salute o le stelle kiai, sono considerati elementi che migliorano il gioco o parte dell'interfaccia utente.
```

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +<!-- TODO: Add links to other articles when they're available -->
```suggestion
```

2023-07-23 15:53 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +In osu!, la prossima nota o slider viene evidenziata con una luminosità leggermente maggiore rispetto alle altre note sul campo di gioco. Tuttavia, l'evidenziazione non sarà più visibile quando la [v
```suggestion
In osu!, la prossima nota o slider viene evidenziata con una luminosità leggermente più altra rispetto alle altre sul campo di gioco. Tuttavia, l'evidenziazione non sarà più visibile quando la [velocità di avvicinamento](/wiki/Beatmap/Approach_rate) è troppo alta.
```

2023-07-23 20:35 UTC, Sclafus approved these changes

2023-07-23 21:08 UTC, Sclafus requested changes
CI fix

2023-07-23 21:08 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +# Note
```suggestion

# Note
```

2023-07-23 21:08 UTC, Sclafus commented on wiki/Gameplay/Hit_object/it.md
> +
```suggestion
```

2023-07-23 21:11 UTC, Sclafus approved these changes

2023-07-25 21:24 UTC, TicClick approved these changes

2023-07-25 21:26 UTC, merged