[IT] Update `Client/Installation/macOS`
ppy/osu-wiki pull request #9755
Opened 2023-07-23 23:07 UTC by githacki

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-24 06:58 UTC, Nakkeraru requested changes

2023-07-24 06:58 UTC, Nakkeraru commented on wiki/Client/Installation/macOS/it.md
> +Se hai difficoltà ad aprire osu!, i seguenti step potrebbero aiutarti:
```suggestion
Se hai difficoltà ad aprire osu!, i seguenti passaggi potrebbero aiutarti:
```

2023-07-24 09:56 UTC, Nakkeraru approved these changes

2023-07-29 15:06 UTC, TicClick approved these changes

2023-07-29 15:08 UTC, merged