[DE] Add `Storyboard/Scripting/Objects`
ppy/osu-wiki pull request #9757
Opened 2023-07-24 10:26 UTC by The-Last-Cookie

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-24 10:29 UTC, The-Last-Cookie commented on wiki/Storyboard/Scripting/Objects/de.md
> +Um eine Instanz von einem Sprite (ein Standbild) oder einer Animation aufzurufen, benutze dazu eine Zeile im Abschnitt `[Events]` in einer .osb- oder .osu-Datei.
Reads a bit weird to me in hindsight, should I turn this around?

2023-07-24 10:29 UTC, The-Last-Cookie commented on wiki/Storyboard/Scripting/Objects/de.md
> +| 0 | Background |
Not so very sure if these should be translated, as they are used in the example image above. If I understand this correctly, you can use both the words as well as the corresponding numerical values for the storyboard commands.

2023-07-24 18:03 UTC, respektive requested changes

2023-07-29 15:01 UTC, TicClick approved these changes

2023-07-29 15:03 UTC, merged