Update `Featured Artists`
ppy/osu-wiki pull request #9759
Opened 2023-07-24 21:13 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] Outdate translations (`SKIP_OUTDATED_CHECK`)

2023-07-24 22:44 UTC, aceticke requested changes

2023-07-24 22:44 UTC, aceticke commented on wiki/People/Featured_Artists/en.md
> +Featured Artists with osu! accounts are given the cyan [user title](/wiki/Community/User_title) and [user group](/wiki/People/User_group) badge that reads `FA` to show their involvement.
```suggestion
Featured Artists with osu! accounts are given the Featured Artist group which can be identified by it's cyan [user title](/wiki/Community/User_title) and [user group](/wiki/People/User_group) badge that reads `FA` to show their involvement.
```
better wording

2023-07-25 08:32 UTC, peppy commented on wiki/People/Featured_Artists/en.md
> +Featured Artists with osu! accounts are given the cyan [user title](/wiki/Community/User_title) and [user group](/wiki/People/User_group) badge that reads `FA` to show their involvement.
its

2023-07-25 16:11 UTC, aceticke commented on wiki/People/Featured_Artists/en.md
> +Featured Artists with osu! accounts are given the cyan [user title](/wiki/Community/User_title) and [user group](/wiki/People/User_group) badge that reads `FA` to show their involvement.
fixed

2023-07-25 16:32 UTC, Walavouchey commented on wiki/People/Featured_Artists/en.md
> +Featured Artists with osu! accounts are given the **Featured Artist** group, which can be identified by a cyan [user title](/wiki/Community/User_title) and [user group](/wiki/People/User_group) badge
maybe better like this

```suggestion
Featured Artists with osu! account can be identified by a cyan "Featured Artist" [user title](/wiki/Community/User_title), and [user group](/wiki/People/User_group) badge that reads `FA` to show their involvement.
```

2023-07-26 15:10 UTC, merged