[RU] Translate 'Gameplay/Game_modifier/No_Fail'
ppy/osu-wiki pull request #9760
Opened 2023-07-24 22:17 UTC by IlyaDityatyev

24 line: caption text taken from the game
29 line: last sentence in bracket instead of a new sentence. Wrote like this because of the meaning of the sentence

2023-07-24 22:31 UTC, Rainbowtaves requested changes

2023-07-24 22:31 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/No_Fail/ru.md
> +**No Fail** мод это [игровой модификатор](/wiki/Gameplay/Game_modifier) защищающий игрока от поражения на [картах](/wiki/Beatmap). Включение No Fail мода делает игрока защищенным от поражения на [кар
`**No Fail** мод это [игровой модификатор](/wiki/Gameplay/Game_modifier)`
Слово "мод" в этом месте лишнее, достаточно просто "No Fail - это игровой модификатор..."
То же самое касается и следующего предложения: `Включение No Fail мода... `

2023-07-24 22:31 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/No_Fail/ru.md
> +С 16 Января 2021 года, No Fail мод может повлечь уменьшение [очков производительности (PP)](/wiki/Performance_points) за прохождение карты, в зависимости от того, сколько промахов совершает игрок. На
То же самое, слово "мод" лишнее. Название месяца начинается со строчной буквы.

2023-07-24 22:31 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/No_Fail/ru.md
> +- Аббревиатура: NF / НФ
Аббревиатура, написанная кириллицей, выглядит неуместной

2023-07-25 17:09 UTC, Rainbowtaves approved these changes

2023-07-25 21:39 UTC, TicClick approved these changes
неплохо, пара замечаний:
- при создании пулл-реквеста ты нечаянно (?) стёр галочки, связанные с самопроверкой перевода, так лучше не делать
- обрати внимание на a1774507768913b9b7ef4faa6ac695580b129a5b — я расставил знаки препинания, сделал часть предложений и фраз более естественными, а также использовал такие же формулировки, как в уже готовых переводах вроде https://github.com/IlyaDityatyev/osu-wiki/blob/master/wiki/Gameplay/Game_modifier/Flashlight/ru.md ради общности

2023-07-25 21:39 UTC, merged

2023-07-25 21:40 UTC, TicClick commented
а, да, и делай в следующий раз для перевода отдельную ветку вместо `master`: https://osu.ppy.sh/wiki/ru/osu%21_wiki/Contribution_guide/Best_practices#%D0%B2%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%BA

2023-07-26 06:10 UTC, IlyaDityatyev commented
> * при создании пулл-реквеста ты нечаянно (?) стёр галочки, связанные с самопроверкой перевода, так лучше не делать

Привет. Подскажи, пожалуйста, что за галочки? Не помню таких, может не заметил...

А в остальном, замечания принял, теперь есть ориентир того, что ожидают от локализации на другие языки, слишком уж дословный перевод у меня получился, дальше будет лучше :)