[ZH] Update `Upgrading to lazer`
ppy/osu-wiki pull request #9764
Opened 2023-07-25 09:35 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-27 09:22 UTC, CloneWith requested changes

2023-07-27 09:22 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
>  | 精准的表现分 (pp) 显示 | ![部分支持][partial][^online]  | ![支持][true]  |
56、57 两行的顺序似乎与原文不同，可调换一下

2023-07-27 09:22 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
> +| osu!mania、osu! 基于时间轴给物件上色 | ![不支持][false]  | ![支持][true]  |
下面缺失了两行 回放控制和弹幕

2023-07-27 09:22 UTC, CloneWith commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
表格里一些文字末尾带两个空格的，感觉有些奇怪，是规范问题吗？

2023-07-29 00:57 UTC, YumeMuzi commented on wiki/Help_centre/Upgrading_to_lazer/zh.md
两个空格是之前翻译的问题吧，，按照规范，`|` 前后只能有1个空格

2023-07-29 09:46 UTC, CloneWith approved these changes

2023-07-29 14:46 UTC, TicClick approved these changes

2023-07-29 14:47 UTC, TicClick approved these changes

2023-07-29 14:48 UTC, merged