[RU] Add `Gameplay/Game modifier/Sudden Death`
ppy/osu-wiki pull request #9771
Opened 2023-07-26 18:32 UTC by IlyaDityatyev

Фулл комбо, комбо брейк - устойчивые выражения, часто встречаются в русскоязычном коммьюнити, оставил такое написание переведя на русскую раскладку
/
Добавил ссылку на спиннер (строка 37)
/
Добавил ссылку на слайдер-тик (строка 42)
/
Переформулировал строку 44 с сохранением смысла
/
Необходимое использование местоимения "он" в строке 51

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-26 18:41 UTC, Rainbowtaves requested changes

2023-07-26 18:41 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +**Sudden Death** - [игровой модификатор](/wiki/Gameplay/Game_modifier), не позволяющий пройти [карту](/wiki/Beatmap), если игрок промахнулся по [ноте](/wiki/Gameplay/Hit_object), или не провёл курсор
Лишний союз "и" (`...не провёл курсором все слайдер-тики и с зажатой клавишей.`)
Уточнение "скилл" в конце строки лишнее

2023-07-26 18:41 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +Для большей точности... Sudden Death мод засчитает поражение в карте, если:
Для чего стоит многоточие после слова "точности"?

2023-07-26 18:41 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +- Не попал в [конец слайдера](/wiki/Gameplay/Hit_object/Slider/Slidertail) (слайдербрейк (СБ))
Лишнее упоминание термина слайдербрейк и его аббревиатуры

2023-07-26 19:38 UTC, IlyaDityatyev commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +Для большей точности... Sudden Death мод засчитает поражение в карте, если:
При постановке запятой, смысл предложения не однозначный становится:
1. Либо имеется ввиду "Мод делает то и то для большей точности"
2. Либо "Стоит уточнить, мод засчитает поражение, если" - кстати, как вариант, заменить предложение на такую формулировку

2023-07-26 19:42 UTC, IlyaDityatyev commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +- Не попал в [конец слайдера](/wiki/Gameplay/Hit_object/Slider/Slidertail) (слайдербрейк (СБ))
Взято с оригинала. Стоит убрать, или может, добавить "т.е." после открытия скобки?

2023-07-26 19:47 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +Для большей точности... Sudden Death мод засчитает поражение в карте, если:
Вместо многоточия в качестве уточнения можно использовать двоеточие (`:`)

2023-07-26 19:50 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +- Не попал в [конец слайдера](/wiki/Gameplay/Hit_object/Slider/Slidertail) (слайдербрейк (СБ))
Если взято с оригинала - тогда имеет смысл сохранять значение, данное в оригинале. 
Можно написать как `(например, слайдербрейк)`

2023-07-26 20:56 UTC, Rainbowtaves requested changes

2023-07-26 20:56 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +- Не попал в [конец слайдера](/wiki/Gameplay/Hit_object/Slider/Slidertail) (т.е. [слайдербрейкнул (СБшнул)](/wiki/Gameplay/Judgement/Slider_break))
Рекомендую отказаться от употребления жаргонизмов `... (СБшнул)` в этой части текста.

2023-07-27 13:14 UTC, IlyaDityatyev commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +- Не попал в [конец слайдера](/wiki/Gameplay/Hit_object/Slider/Slidertail) (т.е. [слайдербрейкнул (СБшнул)](/wiki/Gameplay/Judgement/Slider_break))
Будет приемлимо, если я уберу только то, что во вторых скобках находится: "(СБшнул)"?

2023-07-27 16:52 UTC, Rainbowtaves commented on wiki/Gameplay/Game_modifier/Sudden_Death/ru.md
> +- Не попал в [конец слайдера](/wiki/Gameplay/Hit_object/Slider/Slidertail) (т.е. [слайдербрейкнул (СБшнул)](/wiki/Gameplay/Judgement/Slider_break))
В целом у меня к тексту претензий больше нет, так что думаю да. Жду коммит.

2023-07-27 18:05 UTC, Rainbowtaves approved these changes

2023-07-28 16:16 UTC, TicClick approved these changes
привёл перевод в порядок, в целом неплохо, но нужно меньше громоздкости — не бойся переформулировывать предложения.

маленькое замечание: в тексте пулл-реквеста не нужно подробно писать, что ты сделал (это и так будет заметно), — это имеет смысл только при масштабных изменениях, либо там, где за ними может быть сложно уследить

2023-07-28 16:16 UTC, merged