Add The-First-osu!-Manga-osu!-Combat-Championship
ppy/osu-wiki pull request #9773
Opened 2023-07-27 08:36 UTC by Vortex100K

The-First-osu!-Manga-osu!-Combat-Championship News Post

2023-08-03 14:11 UTC, 0x84f requested changes
just my thoughts but i think this news post might need more work

2023-08-03 14:24 UTC, Vortex100K commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +Prepare for action-packed episodes each lasting as long as the animes you love!
This makes it seem as if it's referring to just one which it is not it's referring to all the usual anime released

2023-08-03 14:26 UTC, Vortex100K commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +## Curious to know who will grace the series with their presence? We are thrilled to feature some of your favorite top players! including
Makes it stand out so the viewer realises that this sentence is more important then the others

2023-08-03 14:31 UTC, Vortex100K commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +**Calling all osu! enthusiasts!**
Then what should i do instead? To start off the article?

2023-08-03 15:05 UTC, 0x84f commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +**Calling all osu! enthusiasts!**
the start from line 13 is completely fine

2023-08-09 19:36 UTC, Walavouchey requested changes
only doing a pass on formatting for today

2023-08-09 19:36 UTC, Walavouchey commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +<p align="center">
i'm not sure why this should be a table. the design style of the list doesn't seem bad, but there are still concerns that should be addressable if you have the project files:

- it's still about double the height necessary. there should be at least another column
- the text is centre-aligned within the columns while the profile pills are left-aligned, making it look lopsided
- commas should have a space after them (as it is with "Polishing, 3D" for xootynator)
- "GFX DESIGNER" is randomly in all caps, and "GFX" already exists
- you have "Storyteller" and "Story", what's the difference?
- what's the transparency in the image for?

2023-08-09 19:36 UTC, Walavouchey commented on wiki/shared/news/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship/newbaselist.png
this text has too low contrast against the news page background

![image](https://github.com/ppy/osu-wiki/assets/36758269/a5b46c62-e6de-4781-9202-b159471812cd)

![image](https://github.com/ppy/osu-wiki/assets/36758269/b7edae11-1b83-40fb-81f0-ddcead7742a6)

2023-08-09 19:36 UTC, Walavouchey commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +</p>
images are done like this

```suggestion
![](/wiki/shared/news/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship/OCCTEMremakemin.png)
```

2023-08-09 19:36 UTC, Walavouchey commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +</p>
```suggestion
![](/wiki/shared/news/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship/newbaselist.png)
```

2023-08-09 19:36 UTC, Walavouchey commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +## Curious to know who will grace the series with their presence? We are thrilled to feature some of your favorite top players! including
the standard is not to misuse headings like this. adding a horizontal line (`---`) right before this line would be more appropriate here

2023-08-09 19:36 UTC, Walavouchey commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> + Join us as we delve into the captivating storyline that follows the path of WhiteCat, a skilled player, immersing themselves in a once-in-a-lifetime combat-style tournament where participants battle
```suggestion
Join us as we delve into the captivating storyline that follows the path of WhiteCat, a skilled player, immersing themselves in a once-in-a-lifetime combat-style tournament where participants battle it out for the ultimate goal: attaining the prestigious rank 1 title and having any wish granted. Get ready to experience exhilarating action sequences, intense rivalries, and delve deeper into our unique spin on the world of osu!.
```

2023-08-09 19:36 UTC, Walavouchey commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +The OCC animated series will faithfully follow the manga, capturing the essence and excitement of a traditional anime experience.
paragraphs need to be separated by blank lines

```suggestion
But that's not all! We have an exciting announcement for all anime enthusiasts out there. The OCC manga will be transformed into an **animated series**, and we have just started on episode 1's production!

Prepare for action-packed episodes each lasting as long as the anime you love! The OCC animated series will faithfully follow the manga, capturing the essence and excitement of a traditional anime experience.
```

2023-08-11 22:19 UTC, 0x84f commented on news/2023/2023-07-24-The-First-osu!-Manga-osu!-Combat-Championship.md
> +<p align="center">
The height was the main reason that was off-putting for me, the rest I agree with

2023-08-18 21:17 UTC, Walavouchey commented
drafting as the direction here seems off as [explained on discord](https://discord.com/channels/188630481301012481/1003689172420276246/1139237961364426832)

2023-08-18 21:22 UTC, closed without merging