[ZH] Update `Users with unique titles`
ppy/osu-wiki pull request #9784
Opened 2023-07-29 02:00 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-07-30 02:22 UTC, CloneWith requested changes

2023-07-30 02:22 UTC, CloneWith commented on wiki/People/Users_with_unique_titles/zh.md
> +Since 2020, members of the [Beatmap Nominators](/wiki/People/Beatmap_Nominators) and [Nomination Assessment Team](/wiki/People/Nomination_Assessment_Team) with an exceptional display towards supporti
这行是多出来的原文

2023-07-30 06:04 UTC, CloneWith approved these changes

2023-07-31 16:32 UTC, TicClick approved these changes

2023-07-31 16:37 UTC, merged