[ES] Update `TWC 2015`
ppy/osu-wiki pull request #9806
Opened 2023-08-01 08:22 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-03 18:45 UTC, UnknownOsu requested changes

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +5. Si no hay personal o árbitro disponible, el partido se aplazará.
```suggestion
5. Si no hay personal o árbitro disponible, el partido será pospuesto.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +10. Si asisten menos jugadores del mínimo requerido, el tiempo máximo que se puede posponer la partida es de 10 minutos.
```suggestion
10. Si asisten menos jugadores del mínimo requerido, el tiempo máximo que se puede posponer el partido es de 10 minutos.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +9. Los mapas no se pueden reutilizar en la misma partida a menos que la partida haya sido anulada.
```suggestion
9. Los mapas no se pueden reutilizar en el mismo partido a menos que el partido haya sido anulado.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +13. En la fase de grupos, «Ganar por defecto» se considerará como ganar por 4:0, +1.0 de diferencia de puntuación.
```suggestion
13. En la fase de grupos, «Ganó por default» se considerará como ganar por 4:0, +1.0 de diferencia de puntuación.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +6. Los seleccionadores del mapset no podrán participar como jugadores en este torneo.
```suggestion
6. Los selectores de mapas no podrán participar como jugadores en este torneo.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +### Instrucciones de fases
```suggestion
### Instrucciones de las fases
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +   2. Tener mayor `{(el número de mapas ganados) | (el número de mapas derrotados)}`.
```suggestion
   2. Tener mayor `{(el número de mapas ganados) | (el número de mapas perdidos)}`.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +5. Las siguientes fases son de doble eliminación. Esto significa que el ganador pasa a la siguiente fase y el equipo perdedor pasa al cuadro de perdedores.
```suggestion
5. Las siguientes fases son de doble eliminación. Esto significa que el ganador pasa a la siguiente fase y el equipo perdedor pasa al bracket de perdedores.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +   - En la fase de grupos, es necesario ganar 4 mapas para ganar un partido. (Al mejor de 7)
```suggestion
   - En la fase de grupos, necesitas ganar 4 mapas para ganar un partido. (Al mejor de 7)
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +3. Cada capitán puede prohibir que se seleccionen dos beatmaps del grupo. Estos beatmaps no podrán ser elegidos por ningún equipo en toda la partida.
```suggestion
3. Cada capitán puede prohibir que se seleccionen dos beatmaps del grupo. Estos beatmaps no podrán ser elegidos por ningún equipo en toda el partido.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +4. La selección de beatmaps se alternará entre cada capitán seleccionando un beatmap de la Dieciseisavos de final de mapas.
```suggestion
4. La selección de beatmaps se alternará entre cada capitán seleccionando un beatmap del map pool.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +   - El ganador del `!roll` empezará a elegir el primer beatmap de la partida.
```suggestion
   - El ganador del `!roll` empieza a elegir el primer beatmap del partido.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +   - El perdedor del `!roll` empieza a prohibir dos beatmaps.
```suggestion
   - El perdedor del `!roll` empieza a banear dos beatmaps.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +### Instrucciones de la mappool
```suggestion
### Instrucciones del mappool
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +1. Habrá 1 mappool para la fase de grupos, 1 mappool para los dieciseisavos de final, 1 mappool para los cuartos de final, 1 mappool para las semifinales y 1 mappool para las finales (la semana 1 y l
```suggestion
1. Habrá 1 mappool para la fase de grupos, 1 mappool para los dieciseisavos de final, 1 mappool para los cuartos de final, 1 mappool para las semifinales y 1 mappool para las finales (la semana 1 y la semana 2 usan el mismo mappool).
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +2. Cada mappool consta de 5 grupos: NoMod, [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [HardRock](/wiki/Gameplay/Game_modifier/Hard_Rock), [DoubleTime](/wiki/Gameplay/Game_modifier/Double_Time) y
```suggestion
2. Cada mappool consta de 5 brackets: NoMod, [Hidden](/wiki/Gameplay/Game_modifier/Hidden), [HardRock](/wiki/Gameplay/Game_modifier/Hard_Rock), [DoubleTime](/wiki/Gameplay/Game_modifier/Double_Time) y FreeMod.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +7. El bracket de FreeMod se jugará con FreeMod activado. Cada jugador puede elegir entre Hidden, HardRock o ningún modo.
```suggestion
7. El bracket de FreeMod se jugará con FreeMod activado. Cada jugador puede elegir entre Hidden, HardRock o ningún mod.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +1. Cada etapa se celebrará en **un único fin de semana**.
```suggestion
1. Cada etapa se llevará a cabo en **un solo fin de semana**.
```

2023-08-03 18:45 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +2. Los partidos de la fase de grupos podrán solaparse.
```suggestion
2. Los partidos de la fase de grupos pueden coincidir.
```

2023-08-03 19:20 UTC, agatemosu commented on wiki/Tournaments/TWC/2015/es.md
> +| Estadístico | ::{ flag=PL }:: [Marcin](https://osu.ppy.sh/users/722665) |
pero está hablando de una persona

2023-08-03 19:21 UTC, agatemosu commented on wiki/Tournaments/TWC/2015/es.md
> +| Selector de la mappool | ::{ flag=DE }:: [OnosakiHito](https://osu.ppy.sh/users/290128) |
es femenino porque la traducción literal es "piscina de mapas"

2023-08-03 19:22 UTC, agatemosu commented on wiki/Tournaments/TWC/2015/es.md
> +- [Directo](https://www.twitch.tv/osulive)
juraría que lo había cambiado xd

2023-08-03 19:23 UTC, agatemosu commented on wiki/Tournaments/TWC/2015/es.md
> +**[¡Descarga el mappack aquí! (103 MB)](https://www.mediafire.com/download/z5uccj5aai47335/TWC_2015_Finals.rar)**
ahora que lo veo no sé por qué no lo he traducido

2023-08-03 19:24 UTC, agatemosu commented on wiki/Tournaments/TWC/2015/es.md
> +## Set de reglas
está mal así?

2023-08-03 19:36 UTC, UnknownOsu commented on wiki/Tournaments/TWC/2015/es.md
> +| Selector de la mappool | ::{ flag=DE }:: [OnosakiHito](https://osu.ppy.sh/users/290128) |
Ya, pero nadie le dice así, está raro. Si estuviera traducido al español, estaría bien, para mí suena raro "la mappool".

Estoy seguro que un sinónimo a eso también podría ser "grupo de mapas", entonces quedaría `Selector del mappol (grupo de mapas)`

2023-08-11 21:56 UTC, TicClick approved these changes

2023-08-11 21:59 UTC, merged