[ES] Update `AGTS 2019`
ppy/osu-wiki pull request #9807
Opened 2023-08-01 10:07 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-03 20:34 UTC, UnknownOsu requested changes

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +6. A cada equipo se le permite un calentamiento, pero debe ser inferior a 4 minutos. Todo el mundo está permitido en la sala durante los calentamientos.
```suggestion
6. A cada equipo se le permite un calentamiento, pero debe ser inferior a 4 minutos. Todo el mundo puede entrar en la sala durante el calentamiento.
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +7. Cada capitán tiene que prohibir **un beatmap** para ser seleccionado del grupo (aparte del desempate). Estos beatmaps no podrán ser elegidos por ningún equipo en todo el partido.
```suggestion
7. Cada capitán tiene que banear **un beatmap** para ser seleccionado del mappool (aparte del desempate). Estos beatmaps no podrán ser elegidos por ningún equipo en todo el partido.
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +9. El equipo con **la tirada más alta prohibe al segundo y elige primero**. El equipo con **la tirada más baja prohibe al primero y elige segundo**.
```suggestion
9. El equipo con **la tirada más alta banea segundo y elige primero**. El equipo con **la tirada más baja banea primero y elige segundo**.
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +10. La selección del beatmap alternará entonces entre cada capitán seleccionando un beatmap de la piscina de mapas.
```suggestion
10. La selección del beatmap alternará entonces entre cada capitán seleccionando un beatmap del mappool.
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +4. En primer lugar, se celebrarán 2 combates de battle royale 3 contra 3 con un mappool de 12 mapas (2 NM,HR,HD,DT,FM,EX). (EX = mapas más difíciles) Los mapas se eligen al azar con un generador de n
```suggestion
4. En primer lugar, se llevarán a cabo 2 partidos de battle royale 3 contra 3 con un mappool de 12 mapas (2 NM,HR,HD,DT,FM,EX). (EX = mapas más difíciles) Los mapas se eligen al azar con un generador de nombres aleatorios a través de la rueda giratoria.
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +5. También se celebrará un partido 4 contra 4 con las siguientes reglas:
```suggestion
5. También se realizará un partido 4 contra 4 con las siguientes reglas:
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +   - Mappool de 5 NM, HR, HD, DT, FM, EX, y 1 TB (mismas reglas para mods que los partidos normales).
```suggestion
   - Mappool de 5 NM, HR, HD, DT, FM, EX, y 1 TB (mismas reglas para los mods que para los partidos normales).
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +   - El intercambio de jugadores durante una partida está permitido sin limitaciones.
```suggestion
   - El intercambio de jugadores durante un partido está permitido sin limitaciones.
```

2023-08-03 20:34 UTC, UnknownOsu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +   - Mismas reglas que en una partida normal para las desconexiones.
```suggestion
   - Mismas reglas que en un partido normal para las desconexiones.
```

2023-08-03 20:35 UTC, agatemosu commented on wiki/Tournaments/GTS/AGTS_2019/es.md
> +| ![Corona de oro](/wiki/shared/crown-gold.png "Primer lugar") | Insignia de perfil única, pancarta exclusiva del equipo |
AJAKAJS si

2023-08-11 21:57 UTC, TicClick approved these changes

2023-08-11 22:00 UTC, merged