Add SVSE2 tournament page
ppy/osu-wiki pull request #9818
Opened 2023-08-02 18:10 UTC by WalterToro

## Self-check

- [*] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-08-02 18:38 UTC, TicClick requested changes

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +Teams with their name crossed out are eliminated.
```suggestion
Teams with emboldened names advance to finals.
Teams with names crossed out are eliminated.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +Teams with their name crossed out are eliminated.
```suggestion
Teams with italicised names are on last chance situation.
Teams with names crossed out are eliminated.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +Teams with their name crossed out are eliminated.
```suggestion
Teams with italicised names are on last chance situation.
Teams with names crossed out are eliminated.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +Teams with their name on italics are on last chance situation.
```suggestion
Teams with italicised names are on last chance situation
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +1. SV: Summer Exhibition 2 is a **team tournament**, played on the osu!mania game mode.
```suggestion
1. SV: Summer Exhibition 2 is an osu!mania **team tournament**.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +2. Teams will select one player to play each map and each player will play two different maps from the mappool.
this reads convoluted, any chance you could rephrase/simplify it?

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +  - Players cant change what maps are they going to play after this.
```suggestion
3. When joining the lobby, the teams will tell the referee what maps each player will be playing.
  - From this point, players can't change selected maps.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +  - They get 2 "Last Chance" flags, these flags are given by being on the bottom half of the leaderboard each week.
```suggestion
  - They get 2 "Last Chance" flags, which are given to the teams in the bottom half of the leaderboard each week.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +  - Teams outside of top 4 that dont get eliminated by the end of week 4 are survivors and get a small prize.
```suggestion
  - Teams outside of top 4 not eliminated by the end of week 4 are considered survivors and get a small prize.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +  - These A and B players cant be swapped for the entire stage.
```suggestion
  - These A and B players can't be swapped for the entire stage.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +6. Each team must use `!roll` command at the start of every set in `#multiplayer`.
```suggestion
6. Each team must use the `!roll` command at the start of every set in `#multiplayer`.
```

2023-08-02 18:38 UTC, TicClick commented on wiki/Tournaments/SVSE/2/en.md
> +7. There wont be bans in this stage.
```suggestion
7. There will be no bans in this stage.
```

2023-08-02 20:28 UTC, agatemosu commented
Identation should be 3 i think

2023-08-02 20:42 UTC, WalterToro commented
> Identation should be 3 i think

Thank you!

2023-08-03 13:52 UTC, TicClick approved these changes

2023-08-03 14:25 UTC, merged