[IT] Add `Community/Video_series/*`
ppy/osu-wiki pull request #9887
Opened 2023-08-13 14:21 UTC by Sclafus

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-13 14:27 UTC, Sclafus commented
Apparently, `Community/Video_series/osu!academy/it.md` was added on accident in a completely unrelated PR https://github.com/ppy/osu-wiki/commit/d28a253fac4de3a59006dd90aa13dd5f81cca9bd#diff-9e148f401f263d5e761765ee6cf4e3af8eefbc7e84d68a3547c657373f4f1532
Sorry!

2023-08-13 20:24 UTC, Nakkeraru requested changes

2023-08-13 20:24 UTC, Nakkeraru commented on wiki/Community/Video_series/osu!academy/it.md
> +| 28 | [Fondamenti del Forum](https://www.youtube.com/watch?v=PEZFOM8NKtw) | [ztrot](https://osu.ppy.sh/users/6347) illustra i forum di osu! e presenta le regole vigenti. |
```suggestion
| 28 | [Fondamenti del Forum](https://www.youtube.com/watch?v=PEZFOM8NKtw) | [ztrot](https://osu.ppy.sh/users/6347) illustra i forum di osu! e presenta le regole in vigore. |
```

2023-08-16 12:59 UTC, Nakkeraru approved these changes

2023-08-17 12:58 UTC, TicClick approved these changes, later dismissed

2023-08-17 12:58 UTC, TicClick approved these changes

2023-08-17 13:00 UTC, merged