[RU] Add `Beatmapping/Beat snapping`
ppy/osu-wiki pull request #9889
Opened 2023-08-13 16:49 UTC by TicClick

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-30 21:44 UTC, UristMcKobold requested changes

2023-08-30 21:44 UTC, UristMcKobold commented on wiki/Beatmapping/Beat_snapping/ru.md
> +Хотя редактор и поддерживает популярные музыкальные размеры нот, ритм некоторых песен может быть написан весьма неординарным способом. В таких случаях мапперу понадобится вручную поделить длину доли
```suggestion
Хоть редактор и поддерживает популярные размеры такта, ритм некоторых песен может быть весьма неординарным. В таких случаях мапперу понадобится вручную поделить длину доли на несколько равных частей и рассчитать, куда именно ставить ноты.[^unsupported-bsd]
```
«музыкальные» не надо, поскольку сам термин относится только к музыкальности. А «размеры нот» я впервые слышу.

2023-08-31 17:43 UTC, TicClick commented on wiki/Beatmapping/Beat_snapping/ru.md
> +Хотя редактор и поддерживает популярные музыкальные размеры нот, ритм некоторых песен может быть написан весьма неординарным способом. В таких случаях мапперу понадобится вручную поделить длину доли
а вот и нет, такт — это measure (сколько у тебя нот какого размера умещается в повторяющийся кусок), а я хочу сказать (и ты вместе со мной) про то, на сколько частей ноту можно разбить (1/2...1/16)

по поводу второго пункта: размер ноты — это её длина относительно полной доли, разве нет?

2023-08-31 17:47 UTC, TicClick commented on wiki/Beatmapping/Beat_snapping/ru.md
> +Хотя редактор и поддерживает популярные музыкальные размеры нот, ритм некоторых песен может быть написан весьма неординарным способом. В таких случаях мапперу понадобится вручную поделить длину доли
```suggestion
Хоть редактор и поддерживает популярные размеры нот, ритм некоторых песен может быть весьма неординарным. В таких случаях мапперу понадобится вручную поделить длину доли на несколько равных частей и рассчитать, куда именно ставить ноты.[^unsupported-bsd]
```

2023-08-31 18:20 UTC, Walavouchey approved these changes

2023-08-31 18:46 UTC, merged