[JA] Add `Ranking Criteria/osu!catch`
ppy/osu-wiki pull request #9895
Opened 2023-08-14 08:50 UTC by Usakitsu

per the catch meeting the community held a couple months back, we wanted the ranking criteria translated into more of the popular languages. i had it reviewed by -rei, mentai, and resona (non-natives) and by amulet-pp, a japanese native catch mapper all not through github (on discord instead). i think it should be good to go but anyone is welcome to add their suggestions on wording or grammar

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-20 03:19 UTC, peppy requested changes

2023-08-20 05:23 UTC, Usakitsu commented on wiki/Ranking_criteria/osu!catch/ja.md
> +osu!catch ranking criteria(osu!catch譜面のランク基準)はosu!catch譜面を作成する際に従わなければならない[ルール、ガイドライン](/wiki/Ranking_criteria#general-terms)です。osu!catch譜面をRankedさせるためにはこれらのルールに従う必要があります。いかなる場合でもルールに従わなければなりませんが、ガイドラ
i think i copied this over when i was just starting out and looking at the japanese version of the taiko ranking criteria for inspiration, i thought this was the way it was wanted but now going back and seeing the outdated tag thats probably not the case lol. i've now rewritten it to match back the original

2023-08-20 05:24 UTC, Usakitsu commented on wiki/Ranking_criteria/osu!catch/ja.md
> +- **全てのサークルとスライダーは曲の特徴的な音に合わせてください。** 通常は明瞭な音ですが、始まりと終わりの区別がつかない連続音を表すこともあります。
i don't think so? its supposed to be representing "This is usually a distinct sound, but can also represent a continuous sound with an indistinguishable start or end." but correct me if im wrong

2023-08-20 05:41 UTC, Usakitsu commented on wiki/Ranking_criteria/osu!catch/ja.md
> +難易度別のルールとガイドラインは、それぞれの難易度レベルにのみ適用されます。**したがって、それらはすべてのosu!catch難易度に適用されるわけではありません。** リズムに関連するルールとガイドラインは4/4拍子でBPM 180程度の曲に基づいています。曲が大幅に速い、または遅い場合は、[Ranking CriteriaにおけるBPMのスケーリング](/wiki/Ranking_crite
i just copied it over from the first time this appeared without realizing 4/4 wasn't mentioned, has been fixed

2023-08-20 05:42 UTC, Usakitsu commented on wiki/Ranking_criteria/osu!catch/ja.md
> +難易度別のルールとガイドラインは、それぞれの難易度レベルにのみ適用されます。**したがって、それらはすべてのosu!catch難易度に適用されるわけではありません。** リズムに関連するルールとガイドラインは4/4拍子でBPM 180程度の曲に基づいています。曲が大幅に速い、または遅い場合は、[Ranking CriteriaにおけるBPMのスケーリング](/wiki/Ranking_crite
applied

2023-08-21 08:31 UTC, peppy approved these changes
Seems good 👍

2023-08-22 11:23 UTC, merged