Added Spanish translations for osu!catch and osu!taiko pages.
ppy/osu-wiki pull request #9916
Opened 2023-08-17 03:00 UTC by virasakd

The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
 (translations only) The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
 
I have translated these two documents, "osu!catch" and "osu!taiko," into Spanish.

2023-08-17 10:01 UTC, githacki requested changes
Fix remark

2023-08-17 14:16 UTC, agatemosu reviewed
Part 1

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- La velocidad de la pista de frutas es similar a la velocidad de las bolas de deslizamiento.
```suggestion
- La velocidad de la corriente de jugo es similar a la velocidad de las bolas del slider.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- Spinner crea una lluvia de plátano.
```suggestion
- El spinner crea una lluvia de plátanos.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +**Notas:** Los hiperfructos se generan automáticamente.
```suggestion
**Nota:** Las hiperfrutas se generan automáticamente.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +## Trivia
```suggestion
## Curiosidades
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- [Auto]( / wiki / Gameplay / Game_modifier / Auto) siempre recogerá todas las bananas.
```suggestion
- [Auto](/wiki/Gameplay/Game_modifier/Auto) siempre recogerá todos los plátanos.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- Si `Hit-error` está habilitado, siempre utilizará `Color`.
```suggestion
- Si `Hit-error` está habilitado, siempre utilizará `Colour`.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- El atrapador puede moverse alrededor durante cualquier pausa.
```suggestion
- El catcher puede moverse alrededor durante cualquier pausa.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- El catcher tiene una animación de Miss, mucho como osu!Animación de Miss Taiko Pippidon.
```suggestion
- El catcher tiene una animación de fallo, muy parecida a la animación de fallo de pippidon en osu!taiko.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- El primer catcher por defecto fue una versión chibificada de Ryuuta Ippongi (de la serie [ouendan] (https://en.wikipedia.org/wiki/Osu!¡Tataque!_Ouendan)) hasta 2014, que fue reemplazado por el catc
```suggestion
- El primer catcher por defecto fue una versión chibificada de Ryuuta Ippongi (de la [serie ouendan](https://es.wikipedia.org/wiki/Osu!_Tatakae!_Ouendan)) hasta 2014, que fue reemplazado por el catcher y mascota actual, [Yuzu](/wiki/Mascots#yuzu)
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- Cuando se juega por [Auto] (/wiki/Gameplay / Game_modifier/Auto), el nombre del jugador será *salad!*.
```suggestion
- Cuando se juega con [Auto](/wiki/Gameplay/Game_modifier/Auto), el nombre del jugador será *salad!*.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +![osu!catch logo en los modos especiales](/wiki/shared/Ctb_logo.jpg "Catch the Beat en modo especial")
```suggestion
![Logo de osu!catch en modo especial](/wiki/shared/Ctb_logo.jpg "Logo de Catch the Beat en modo especial")
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- Hasta el 10 de abril de 2012 (2012-04-10), los mapas de osu!catch no podían ser clasificados ni incluidos en mapas clasificados. Sin embargo, esto ha cambiado ahora, y los creadores de mapas pueden
```suggestion
- Hasta el 10 de abril de 2012 (10/4/2012), los mapas de osu!catch no podían ser clasificados ni incluidos en mapas clasificados. Sin embargo, esto ha cambiado ahora, y los creadores de mapas pueden hacer dificultades específicas de osu!catch, siempre que cumplan con las directrices. Estas directrices son en gran medida un trabajo en curso, pero a medida que los mapas de osu!catch sean clasificados y reciban comentarios de los jugadores, las directrices evolucionarán para ser tan exhaustivas y completas como las directrices generales de osu!.
```

2023-08-17 14:16 UTC, agatemosu commented on wiki/Game_mode/osu!catch/es.md
> +- ¡Primer clasificado OSU!catch-only beatmap es [Río de Janeiro - Córdoba](https://osu.ppy.sh/beatmapsets/91485).
```suggestion
- El primer beatmap clasificado solo de osu!catch es [Rita - Hajimari no Toki (Deif)](https://osu.ppy.sh/beatmapsets/91485).
```

2023-08-18 19:08 UTC, agatemosu reviewed
Part 2

2023-08-18 19:08 UTC, agatemosu commented on wiki/Game_mode/osu!taiko/es.md
> +![El logo de osu!taiko en los modos especiales.](img/Taiko_logo.jpg "Logo de Taiko en el Modo Especial.")
```suggestion
![Logo de osu!taiko en modo especial](img/Taiko_logo.jpg "Logo de Taiko en modo especial")
```

2023-08-18 19:08 UTC, agatemosu commented on wiki/Game_mode/osu!taiko/es.md
> +- El primer beatmap clasificado que contiene al menos un osu!la dificultad de taiko es [Taiko no Tatsujin - Saitama2000 (Kharl)](https://osu.ppy.sh/beatmapsets/210)
```suggestion
- El primer beatmap clasificado que contiene al menos una dificultad de osu!taiko es [Taiko no Tatsujin - Saitama2000 (Kharl)](https://osu.ppy.sh/beatmapsets/210)
```

2023-08-18 19:08 UTC, agatemosu commented on wiki/Game_mode/osu!taiko/es.md
> +- ¡Primer clasificado OSU!beatmap es [Mutsuhiko Izumi - Red Goose (lepidopodus)](https://osu.ppy.sh/beatmapsets/55920)
```suggestion
- El primer beatmap clasificado de osu!taiko es [Mutsuhiko Izumi - Red Goose (lepidopodus)](https://osu.ppy.sh/beatmapsets/55920)
```

2023-08-18 19:08 UTC, agatemosu commented on wiki/Game_mode/osu!taiko/es.md
> +- La opción `Usar skin Taiko para modo Taiko` en la barra lateral de Opciones en la sección de skins utilizará los elementos de la carpeta `taiko` cuando juegue en *osu!taiko*, independientemente de
```suggestion
- La opción `Utilizar la skin de Taiko para Taiko` en la barra lateral de opciones en la sección de skins utilizará los elementos de la carpeta `taiko` cuando juegue en *osu!taiko*, independientemente de los elementos taiko de la skin actual. La carpeta usada para mantener la skin *[Taiko por LuiginHann](https://osu.ppy.sh/community/forums/topics/41319)*, que se puede descargar desde el ahora desaprobado `osume.exe` (un archivo para actualizar osu! para cuando sea necesario actualizar) en la pestaña `Skin`.
```

2023-10-23 03:51 UTC, cl8n commented
see above

2023-10-23 03:51 UTC, closed without merging