Add `osu! Malaysia @ AniManGaki 2023` news post
ppy/osu-wiki pull request #9928
Opened 2023-08-18 20:19 UTC by Hiviexd

PRing on behalf of [Jerry](https://osu.ppy.sh/users/605973)

2023-08-18 20:37 UTC, 0x84f approved these changes
short and straight to the point, I think it's fine

2023-08-18 21:12 UTC, Walavouchey requested changes

2023-08-18 21:12 UTC, Walavouchey commented on news/2023/2023-08-22-osu-malaysia-animangaki.md
> +The event will be happening at the Mines International Exhibition & Convention Centre Malaysia (*MIECC*) from 25th to 27th August 2023, providing an opportunity for osu! players all around the countr
https://miecc.mines.com.my/about/

.. although whether "mines" is capitalised seems inconsistent between sources <.<

```suggestion
The event will be happening at the MINES International Exhibition & Convention Centre (*MIECC*) in Malaysia from 25 to 27 August 2023, providing an opportunity for osu! players all around the country to meet up and mingle!
```

2023-08-18 21:12 UTC, Walavouchey commented on news/2023/2023-08-22-osu-malaysia-animangaki.md
> +- **Sunday, 2:00PM:** osu!
```suggestion
| Game mode | Timestamp (UTC+08) |
| :-- | :-- |
| osu!catch | Friday, 25 August 2023 (15:00) |
| osu!taiko | Saturday, 26 August 2023 (12:00) |
| osu!mania | Saturday, 26 August 2023 (15:00) |
| osu! | Sunday, 27 August 2023 (14:00) |
```

2023-08-18 21:12 UTC, Walavouchey commented on news/2023/2023-08-22-osu-malaysia-animangaki.md
> +The main highlight of the event includes the final bracket stages of the **osu! Malaysian LAN Tournament** for all four game modes, with each of the top 4 competing live at the following times (UTC+8
```suggestion
The main highlight of the event includes the final bracket stages of the **osu! Malaysian LAN Tournament** for all four game modes, with each of the top 4 competing live at the following times:
```

2023-08-18 21:12 UTC, Walavouchey commented on news/2023/2023-08-22-osu-malaysia-animangaki.md
> +For all the latest news on the booth happenings throughout the event, do visit the official [o!MY@AMG2023 Discord Server](https://discord.gg/ZKKWb8jK2B) or follow [@osumalaysia on Twitter](https://tw
```suggestion
For all the latest news on the booth happenings throughout the event, do visit the official [osu! Malaysia @ AMG2023 Discord server](https://discord.gg/ZKKWb8jK2B) or follow [@osumalaysia on Twitter](https://twitter.com/osumalaysia).
```

2023-08-18 21:12 UTC, Walavouchey commented on news/2023/2023-08-22-osu-malaysia-animangaki.md
> +## LAN Tournament
```suggestion
## LAN tournament
```

2023-08-18 21:12 UTC, Walavouchey commented on news/2023/2023-08-22-osu-malaysia-animangaki.md
> +## Booth Activities
```suggestion
## Booth activities
```

2023-08-19 07:54 UTC, peppy approved these changes

2023-08-19 07:56 UTC, merged