[ES] Fix typo in `Tournament Committee`
ppy/osu-wiki pull request #9947
Opened 2023-08-20 21:32 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-20 22:38 UTC, TicClick requested changes

2023-08-20 22:38 UTC, TicClick commented on wiki/People/Tournament_Committee/es.md
> -no_native_review: true
not sure if you should remove that from the article you wrote yourself -- https://github.com/ppy/osu-wiki/pull/9624

2023-08-21 04:01 UTC, TheMoonLoop approved these changes
👍

2023-08-22 23:45 UTC, TicClick approved these changes

2023-08-22 23:47 UTC, merged