Update and clean up `Community Contributors`
ppy/osu-wiki pull request #9949
Opened 2023-08-20 22:35 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-23 19:51 UTC, UnknownOsu requested changes

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
>  | ::{ flag=US }:: [Blazevoir](https://osu.ppy.sh/users/120265) | Historial de moderación insano (equivalente a aproximadamente 6 miembros del personal) y casi moderando solo `#osu` durante horas pico
```suggestion
| ::{ flag=US }:: [Blazevoir](https://osu.ppy.sh/users/120265) | Historial de moderación insano (equivalente a aproximadamente 6 miembros del personal) y moderando casi sin ayuda `#osu` durante horas pico (+9k usuarios). |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
> +| ::{ flag=BG }:: [Flanster](https://osu.ppy.sh/users/447818) | Presencia excepcional de moderación (10k+ asesinatos) |
```suggestion
| ::{ flag=BG }:: [Flanster](https://osu.ppy.sh/users/447818) | Presencia excepcional en la moderación (10k+ víctimas) |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
> +| ::{ flag=BG }:: [Flanster](https://osu.ppy.sh/users/447818) | Presencia excepcional de moderación (10k+ asesinatos) |
Creo que queda mejor `víctimas` que `asesinatos`, está raro con el contexto del juego

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
> +| ::{ flag=PH }:: [Nathanael](https://osu.ppy.sh/users/2295078) | Presencia excepcional de moderación (10k+ asesinatos) |
```suggestion
| ::{ flag=PH }:: [Nathanael](https://osu.ppy.sh/users/2295078) | Presencia excepcional en la moderación (10k+ víctimas) |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
> +| ::{ flag=SE }:: [Saten](https://osu.ppy.sh/users/444506) | Presencia excepcional y compromiso de moderación (30k+ asesinatos) |
```suggestion
| ::{ flag=SE }:: [Saten](https://osu.ppy.sh/users/444506) | Presencia excepcional y compromiso en la moderación (30k+ víctimas) |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
>  | ::{ flag=HK }:: [IamKwaN](https://osu.ppy.sh/users/1856463) | Presencia excepcional de moderación y contribución general |
```suggestion
| ::{ flag=HK }:: [IamKwaN](https://osu.ppy.sh/users/1856463) | Presencia excepcional en la moderación y contribución general |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
>  | ::{ flag=DE }:: [Nwolf](https://osu.ppy.sh/users/1910766) | Cientos de horas de estadísticas y análisis de torneos de la World Cup |
```suggestion
| ::{ flag=DE }:: [Nwolf](https://osu.ppy.sh/users/1910766) | Cientos de horas de estadísticas y análisis de los torneos de la World Cup |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
> +| ::{ flag=DE }:: [Tom94](https://osu.ppy.sh/users/1857058) | ¡La mente maestra detrás de innumerables mejoras a osu!, desde pp, reescritura del motor de gráficos, calificación por estrellas y más! |
```suggestion
| ::{ flag=DE }:: [Tom94](https://osu.ppy.sh/users/1857058) | ¡La mente maestra detrás de innumerables mejoras a osu!, desde pp, reescritura del motor gráfico, calificación por estrellas y más! |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
>  | ::{ flag=DE }:: [jorolf](https://osu.ppy.sh/users/7004641) | Excelente contribución al proyecto osu!(lazer) y creación de numerosas herramientas de medios |
```suggestion
| ::{ flag=DE }:: [jorolf](https://osu.ppy.sh/users/7004641) | Excelente contribución al proyecto osu!(lazer) y creación de numerosas herramientas multimedia |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
>  | ::{ flag=AR }:: [juankristal](https://osu.ppy.sh/users/443656) | Excelente contribución a la organización y torneos de la World Cup |
```suggestion
| ::{ flag=AR }:: [juankristal](https://osu.ppy.sh/users/443656) | Excelente contribución a la organización de la World Cup y torneos |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
>  | ::{ flag=DE }:: [Junihuhn](https://osu.ppy.sh/users/4182339) | Excelente contribución a los osu! World Cups y escena de torneos |
```suggestion
| ::{ flag=DE }:: [Junihuhn](https://osu.ppy.sh/users/4182339) | Excelente contribución a las osu! World Cups y escena de torneos |
```

2023-08-23 19:51 UTC, UnknownOsu commented on wiki/People/Community_Contributors/es.md
> +[^redesign-reasons]: [Mensajes de Discord messages por Walavouchey y RBRat3 (12/8/2023) en #osu-wiki en osu!](https://discord.com/channels/188630481301012481/218677502141399041/1139836832381673524)
```suggestion
[^redesign-reasons]: [Mensajes de Discord de Walavouchey y RBRat3 (12/8/2023) en #osu-wiki en osu!](https://discord.com/channels/188630481301012481/218677502141399041/1139836832381673524)
```

2023-08-23 19:53 UTC, UnknownOsu commented
En la línea `173` dice `Excelente contribución e inquebrantable a la comunidad de osu!`. Creo que es mejor si se quita la `e`

2023-08-30 13:32 UTC, TicClick approved these changes

2023-08-30 14:10 UTC, merged