[ES] Add `10K`, `Auto`, `Autopilot`, `Cinema`, Co-op`, `Double Time` and `Easy`
ppy/osu-wiki pull request #9951
Opened 2023-08-21 03:18 UTC by TheMoonLoop

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-21 03:46 UTC, agatemosu requested changes

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Autopilot/es.md
> +El mod Autopilot también deshabilita la interfaz del juego, ocultando así la [puntuación](/wiki/Gameplay/Score), el [combo](/wiki/Beatmapping/Combo) y los fallos, aunque esto se puede volver a habili
```suggestion
El mod Autopilot también deshabilita la interfaz del juego, ocultando así la [puntuación](/wiki/Gameplay/Score), el [combo](/wiki/Beatmapping/Combo) y los fallos, aunque esto se puede volver a habilitar presionando `Mayús` + `Tab`.
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +- Tecla de acceso directo predeterminada: `V` `V` o `Shift`+`V` (o mantenga presionada `Ctrl`+`Shift` al seleccionar un [beatmap](/wiki/Beatmap))
```suggestion
- Tecla de acceso directo predeterminada: `V` `V` o `Shift` + `V` (o mantén presionado `Ctrl` + `Shift` al seleccionar un [beatmap](/wiki/Beatmap))
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +- El mod Co-op se introdujo el 5 de marzo de 2015
```suggestion
- El mod Co-op se introdujo el 5 de marzo de 2015.
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-catch.jpg "Comparación entre una partida normal (izquierda) frente a una partida con el mod activado (derecha) en osu!catch")
```suggestion
![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-catch.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod activado (derecha) en osu!catch")
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-osu.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod activado (derecha) en osu!")
```suggestion
![Jugabilidad de EZ](/wiki/Gameplay/Game_modifier/Easy/img/EZ-comparison-osu.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod activado (derecha) en osu!")
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +![Comparación del juego con Co-op en un beatmap convertido a osu!mania](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-converted-beatmap.jpg "Comparación entre una partida normal (izquierda) y
```suggestion
![Comparación del juego con Co-op en un beatmap convertido a osu!mania](/wiki/Gameplay/Game_modifier/Co-op/img/CP-comparison-converted-beatmap.jpg "Comparación entre una partida normal (izquierda) y una partida con el mod Co-op activado (derecha) en un beatmap convertido de osu!mania")
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +![Jugabilidad de Auto contra Cinema](/wiki/Gameplay/Game_modifier/Cinema/img/CM-comparison.jpg "Comparación del mod Auto (izquierda) con el mod Cinema (derecha)")
```suggestion
![Jugabilidad de Auto contra Cinema](/wiki/Gameplay/Game_modifier/Cinema/img/CM-comparison.jpg "Comparación del mod Auto (izquierda) contra el mod Cinema (derecha)")
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/10K/es.md
> +  - game modifier
```suggestion
  - game modifier
  - modificador de juego
  - modificador del juego
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Auto/es.md
> +  - game modifier
```suggestion
  - game modifier
  - partida automática
  - modificador de juego
  - modificador del juego
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Autopilot/es.md
> +  - game modifiers
```suggestion
  - game modifiers
  - modificador de juego
  - modificador del juego
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Cinema/es.md
> +  - game modifier
```suggestion
  - game modifier
  - modificador de juego
  - modificador del juego
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Co-op/es.md
> +  - playing with a friend
```suggestion
  - game modifier
  - playing with a friend
  - modificador de juego
  - modificador del juego
  - jugar con un amigo
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Double_Time/es.md
> +  - game modifier
```suggestion
  - game modifier
  - modificador de juego
  - modificador del juego
```

2023-08-21 03:46 UTC, agatemosu commented on wiki/Gameplay/Game_modifier/Easy/es.md
> +  - game modifier
```suggestion
  - game modifier
  - modificador de juego
  - modificador del juego
```

2023-08-21 04:09 UTC, agatemosu approved these changes

2023-08-22 23:44 UTC, TicClick approved these changes

2023-08-22 23:45 UTC, merged