[ES] Add `Beatmap search`
ppy/osu-wiki pull request #9957
Opened 2023-08-22 00:04 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-23 20:16 UTC, UnknownOsu requested changes

2023-08-23 20:16 UTC, UnknownOsu commented on wiki/Beatmap_search/es.md
> +| `speed` | Velocidad de desplazamiento de osu!manía guardada. La velocidad de desplazamiento siempre es 0 para mapas no jugados o si la opción [`Recordar la velocidad de desplazamiento de cada mapa
```suggestion
| `speed` | Velocidad de desplazamiento de osu!mania guardada. La velocidad de desplazamiento siempre es 0 para mapas no jugados o si la opción [`Recordar la velocidad de desplazamiento de cada mapa en osu!mania`](/wiki/Client/Options#juego) está desactivada. |
```

2023-08-23 20:17 UTC, agatemosu commented on wiki/Beatmap_search/es.md
> +| `speed` | Velocidad de desplazamiento de osu!manía guardada. La velocidad de desplazamiento siempre es 0 para mapas no jugados o si la opción [`Recordar la velocidad de desplazamiento de cada mapa
gboard :rage:

2023-08-28 20:55 UTC, TicClick approved these changes

2023-08-28 20:57 UTC, merged