[EN/ZH] Add `Yuyuko's Hidden Cup Season 3` and Update `tournaments`
ppy/osu-wiki pull request #9963
Opened 2023-08-22 18:33 UTC by YumeMuzi

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

2023-08-22 23:26 UTC, agatemosu commented on wiki/Tournaments/YHC/en.md
> +- [Yuyuko's Hidden Cup Season 3](3)
here is missing the first tournament (without an article)

2023-09-20 20:42 UTC, TicClick requested changes
mostly minor corrections, please apply them and we're done

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +| ![Gold crown](/wiki/shared/crown-bronze.png "3rd place") | USD 2 per player |
```suggestion
| ![Silver crown](/wiki/shared/crown-silver.png "2nd place") | USD 3.4 per player |
| ![Bronze crown](/wiki/shared/crown-bronze.png "3rd place") | USD 2 per player |
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +| *the MVP of the tournament* | 1 month of osu!supporter |
think it's better to expand an acronym on its first occurrence for clarity
```suggestion
| *the most valuable person of the tournament (MVP)* | 1 month of osu!supporter |
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +| *the Coach of winner team* | 1 month of osu!supporter |
```suggestion
| *the coach of winner team* | 1 month of osu!supporter |
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +5. The default match schedules for each round will be announced by the tournament managers in the information (main) sheet, on Sunday before the last matches take place. the captain could have a disc
(if I caught your intention correctly)
```suggestion
5. The default match schedules for each round will be announced by the tournament managers in the information (main) sheet, on Sunday before the last matches take place. The captain may have a discussion with the opponent and confirm the match time before Saturday 00:00 on the same week.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +6. Use of the Visual Settings to alter background dim or disable beatmap elements like storyboards and skins are allowed.
alternatively, simply Visual Settings
```suggestion
6. Use of the Visual Settings panel to alter background dim or disable beatmap elements like storyboards and skins is allowed.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +8. Exchanging players between games is allowed without limitations.
"exchanging" makes it sound like the teams exchange between themselves (at least to me)
```suggestion
8. Replacing players between games is allowed without limitations.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +    - Player point-of-view live stream snippets (commonly referred to as "clips" or "VODs"). The entirety of the play, along with the results screen must be clearly visible along with the affected pl
```suggestion
    - Player point-of-view live stream snippets (commonly referred to as "clips" or "VODs"). The entirety of the play, along with the results screen, must be clearly visible along with the affected player's score.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +14. The multiplayer chatrooms underlie the [osu! community rules](/wiki/Rules). All chat rules apply to the multiplayer chatrooms where the matches will take place.
```suggestion
14. The multiplayer chatrooms abide by the [osu! community rules](/wiki/Rules). All chat rules apply to the multiplayer chatrooms where the matches will take place.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +    - Breaking the chat rules may result in a silence. Silenced players cannot participate in multiplayer matches and must be exchanged for the duration of the punishment.
```suggestion
    - Breaking the chat rules may result in a silence. Silenced players cannot participate in multiplayer matches and must be replaced for the duration of the punishment.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +   - The team flag and team name should comply with [osu! community rules](/wiki/Rules). sexualized, trolling, insulting, derogatory, personal, and political attack team name or team flag is not allo
```suggestion
   - The team flag and team name should comply with [osu! community rules](/wiki/Rules). Sexualized, trolling, insulting, derogatory, personally and/or politically offensive team names and flags are not allowed.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +     - The team will receive a verbal warning from the referee
```suggestion
     - The team will receive a verbal warning from the referee.
```

2023-09-20 20:42 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +5. Captains and Coaches are responsible for their team's availability.
```suggestion
5. Captains and coaches are responsible for their team's availability.
```

2023-09-20 21:04 UTC, TicClick commented on wiki/Tournaments/YHC/3/en.md
> +| ![Gold crown](/wiki/shared/crown-bronze.png "3rd place") | USD 2 per player |
btw same issue is in the translation

2023-09-22 19:32 UTC, YumeMuzi commented on wiki/Tournaments/YHC/3/en.md
> +| ![Gold crown](/wiki/shared/crown-bronze.png "3rd place") | USD 2 per player |
fix it soon

2023-09-22 22:37 UTC, TicClick submitted a review, later dismissed
should be good to go

2023-09-22 22:46 UTC, TicClick commented
(for clarity, I withdrew my approval because I didn't see any Chinese reviewers -- the English article is fine IMO)

2023-09-23 13:57 UTC, cdwcgt requested changes
just checked text, should be no problem except the following content.

Consider adding a note that the article timeline defaults to UTC+8?

2023-09-23 13:57 UTC, cdwcgt commented on wiki/Tournaments/YHC/3/zh.md
> +**第三届幽幽杯** (***YHC S3***) 是基于 osu! 主模式，娱乐为主的多人 (4v4) 打图游玩锦标赛，主办是 ::{ flag=CN }:: [SIyuyuko](https://osu.ppy.sh/users/9794030)。这是该系列赛的第二届比赛。
```suggestion
**第三届幽幽杯** (***YHC S3***) 是基于 osu! 主模式，娱乐为主的多人 (4v4) 打图游玩锦标赛，主办是 ::{ flag=CN }:: [SIyuyuko](https://osu.ppy.sh/users/9794030)。这是该系列赛的第三届比赛。
```

2023-09-23 13:57 UTC, cdwcgt commented on wiki/Tournaments/YHC/3/zh.md
> +    - 如果有刷屏等等的行为，选手将会被禁言。他们无法进入比赛房间。只能派上其他选手替代他的位置。
```suggestion
    - 如果有刷屏等等违反社区规定的行为，选手将会被禁言。他们无法进入比赛房间。只能派上其他选手替代他的位置。
```

https://osu.ppy.sh/wiki/en/Silence
不知道有没有必要加上链接，总之挂在这里

2023-09-23 13:57 UTC, cdwcgt commented on wiki/Tournaments/YHC/3/zh.md
> +    - 禁止某位选手上一张图。
```suggestion
    - 禁止某位选手游玩某一张图。
```

2023-09-23 18:45 UTC, YumeMuzi commented on wiki/Tournaments/YHC/3/zh.md
> +    - 如果有刷屏等等的行为，选手将会被禁言。他们无法进入比赛房间。只能派上其他选手替代他的位置。
无所谓 no matter

2023-09-23 18:51 UTC, YumeMuzi commented
> (for clarity, I withdrew my approval because I didn't see any Chinese reviewers -- the English article is fine IMO)

Now we should be able to merge, and thank you for checking the English article

2023-09-23 23:04 UTC, TicClick approved these changes

2023-09-24 09:14 UTC, merged