[ES] Clean `Formatting`
ppy/osu-wiki pull request #9965
Opened 2023-08-23 00:46 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-23 10:52 UTC, YumeMuzi commented on wiki/Article_styling_criteria/Formatting/es.md
> +Solo se permiten niveles de encabezamiento 4 y 5 dentro de una caja de información. Estos no aparecen en la tabla de contenidos y cualquier valor inferior es demasiado grande. Es posible que sea nece
```suggestion
Solo se permiten niveles de encabezamiento 4 y 5 dentro de una caja de información. Estos no aparecen en la tabla de contenidos y cualquier valor inferior es demasiado grande. Es posible que sea necesario omitir cualquier [error de comprobación de IC](/wiki/osu!_wiki/Maintenance#comprobaciones-de-ic) debido a esto.
```

2023-10-13 05:45 UTC, UnknownOsu requested changes

2023-10-13 05:45 UTC, UnknownOsu commented on wiki/Article_styling_criteria/Formatting/es.md
> +*Véase también: [Notas al pie](#notas-al-pie)
```suggestion
*Véase también: [Notas al pie](#notas-al-pie)*
```

2023-10-13 05:45 UTC, UnknownOsu commented on wiki/Article_styling_criteria/Formatting/es.md
> +Al vincular a un perfil de usuario, se debe utilizar el número identificador del usuario. Usa el nuevo sitio web (`https://osu.ppy.sh/users/{username}`) para obtener el ID del usuario.
```suggestion
Al vincular a un perfil de usuario, se debe utilizar el número identificador del usuario. Usa el nuevo sitio web (`https://osu.ppy.sh/users/{nombre de usuario}`) para obtener el ID del usuario.
```

2023-10-13 05:45 UTC, agatemosu commented on wiki/Article_styling_criteria/Formatting/es.md
> +*Véase también: [Notas al pie](#notas-al-pie)
ty

2023-10-13 05:48 UTC, UnknownOsu commented
Además, hay algunos cambios que no me dejó hacer:
Línea `148`: Falta un punto después de `inglés`
Línea `901`: Creo que puedes cambiar `Las pausas temáticas` por `Los cortes temáticos`, ya que cambiaste también los demás

2023-10-13 06:02 UTC, agatemosu commented
lo he cambiado por pausa porque acabo de buscar y vi que corte es más para literatura y pausa en conversaciones

2023-10-13 16:11 UTC, TicClick approved these changes

2023-10-13 16:31 UTC, merged