[ES] Add `Tournaments`
ppy/osu-wiki pull request #9969
Opened 2023-08-24 00:43 UTC by agatemosu

I hope it was replaced well

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-31 00:49 UTC, UnknownOsu requested changes

2023-08-31 00:49 UTC, UnknownOsu commented on wiki/Tournaments/es.md
> +| [Continental Global Taiko Showdown 2019](GTS/CGTS_2019) | 2/11/2019 | 2/2/2020 | Asia (Global), ::{ flag=JP }:: [uone](https://osu.ppy.sh/users/5321719) (Asia), ::{ flag=GB }:: [goheegy](https://os
```suggestion
| [Continental Global Taiko Showdown 2019](GTS/CGTS_2019) | 2/11/2019 | 2/2/2020 | Asia (Global), ::{ flag=JP }:: [uone](https://osu.ppy.sh/users/5321719) (Asia), ::{ flag=GB }:: [goheegy](https://osu.ppy.sh/users/8057655) (Europa), ::{ flag=CA }:: [janitoreihil](https://osu.ppy.sh/users/3307897) (Norteamérica), ::{ flag=SG }:: [Blerargh](https://osu.ppy.sh/users/7609510) (Oceanía/SEA), ::{ flag=CL }:: [Ulqui](https://osu.ppy.sh/users/1263669) (Sudamérica) | Europa (Global), ::{ flag=JP }:: [iceOC](https://osu.ppy.sh/users/5482401) (Asia), ::{ flag=ES }:: [AlvaroYL](https://osu.ppy.sh/users/6333166) (Europa), ::{ flag=CA }:: [vladyushko](https://osu.ppy.sh/users/4908773) (Norteamérica), ::{ flag=SG }:: [Element118](https://osu.ppy.sh/users/2283992) (Oceanía/SEA), ::{ flag=BR }:: [HiroK](https://osu.ppy.sh/users/4050738) (Sudamérica) | Norteamérica (Global), ::{ flag=JP }:: [asuasu\_yura](https://osu.ppy.sh/users/2875968) (Asia), ::{ flag=IT }:: [Ikkun](https://osu.ppy.sh/users/1059945) (Europa), ::{ flag=US }:: [cheese salad](https://osu.ppy.sh/users/6349821) (Norteamérica), ::{ flag=PH }:: [Pochacco](https://osu.ppy.sh/users/2927742) (Oceanía/SEA), ::{ flag=BR }:: [Ppus](https://osu.ppy.sh/users/5918857) (Sudamérica) |
```

2023-08-31 00:49 UTC, UnknownOsu commented on wiki/Tournaments/es.md
> +| [Intermediate Global Taiko Showdown 2020](GTS/IGTS_2020) | 6/6/2020 | 19/7/2020 | ::{ flag=US }:: Unites States A | ::{ flag=JP }:: Japón A | ::{ flag=SG }:: Singapur |
```suggestion
| [Intermediate Global Taiko Showdown 2020](GTS/IGTS_2020) | 6/6/2020 | 19/7/2020 | ::{ flag=US }:: Estados Unidos A | ::{ flag=JP }:: Japón A | ::{ flag=SG }:: Singapur |
```

2023-08-31 00:49 UTC, UnknownOsu commented on wiki/Tournaments/es.md
> +| [Continental Global Taiko Showdown 2021](GTS/CGTS_2021) | 6/2/2021 | 17/4/2021 | Asia | Europe | North America |
```suggestion
| [Continental Global Taiko Showdown 2021](GTS/CGTS_2021) | 6/2/2021 | 17/4/2021 | Asia | Europa | Norteamérica |
```

2023-08-31 00:49 UTC, UnknownOsu commented on wiki/Tournaments/es.md
> +| [Mania Beginner's Showdown](MBS/1) | 15/6/2019 | 4/8/2019 | ::{ flag=SE }:: [Davvyforte](https://osu.ppy.sh/users/10047413) (High division), ::{ flag=TH }:: [osu\_player420](https://osu.ppy.sh/user
```suggestion
| [Mania Beginner's Showdown](MBS/1) | 15/6/2019 | 4/8/2019 | ::{ flag=SE }:: [Davvyforte](https://osu.ppy.sh/users/10047413) (Alta división), ::{ flag=TH }:: [osu\_player420](https://osu.ppy.sh/users/13018880) (Baja división) | ::{ flag=DE }:: [Maou](https://osu.ppy.sh/users/3867109) (Alta división), ::{ flag=PH }:: [Wakeupat5](https://osu.ppy.sh/users/13311553) (Baja división) | ::{ flag=US }:: [Loopy542](https://osu.ppy.sh/users/5468461) (Alta división), ::{ flag=VE }:: [\_Vanslight\_](https://osu.ppy.sh/users/6031119) (Baja división) |
```

2023-10-09 16:18 UTC, TicClick approved these changes

2023-10-09 16:30 UTC, merged