[ES] Fix Russia and Romania names in `Countries that participated in osu! tournaments`
ppy/osu-wiki pull request #9970
Opened 2023-08-24 02:53 UTC by agatemosu

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-26 18:04 UTC, UnknownOsu requested changes

2023-08-26 18:06 UTC, agatemosu commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/es.md
> +*Nota: No se tienen en cuenta los equipos mixtos (p ej. Argentina-Columbia).*
Colombia in English is written Colombia, so it refers to something else, but I don't know what

2023-08-26 18:10 UTC, UnknownOsu commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/es.md
> +*Nota: No se tienen en cuenta los equipos mixtos (p ej. Argentina-Columbia).*
También se puede de esa manera por su pronunciación, estoy seguro que se refiere a Colombia

2023-08-27 02:54 UTC, agatemosu commented on wiki/Tournaments/Countries_that_participated_in_osu!_tournaments/es.md
> +*Nota: No se tienen en cuenta los equipos mixtos (p ej. Argentina-Columbia).*
tienes razón (cwc 2013)

2023-08-28 21:04 UTC, TicClick approved these changes

2023-08-28 21:08 UTC, merged