Update `Silence`'s e.g. and etc.
ppy/osu-wiki pull request #9989
Opened 2023-08-30 17:19 UTC by agatemosu

- EN: add etc. to "edit profile details", typo (e.g, -> e.g.), and remove . before parenthesis
- DE: etc. -> usw.
- ES: review
- ID: change to abbreviation (dan lain sebagainya/dan lain-lain -> ddl.)

I don't know a better title

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-08-30 18:28 UTC, DoryanR approved these changes
OK for the French file

2023-08-30 19:19 UTC, Nivalyx commented
@agatemosu "dan lain-lain" in indonesian is `dll.` not `ddl.`

2023-08-30 20:50 UTC, agatemosu commented
> @agatemosu "dan lain-lain" in indonesian is `dll.` not `ddl.`

sorry flr my typo xd

2023-09-05 14:19 UTC, CloneWith approved these changes
Chinese translation seems ok 👍

2023-09-05 14:44 UTC, The-Last-Cookie requested changes
Both `etc.` and `usw.` are fine for German, though there are no commas placed before them in enumerations (see ["Zeichensetzung am Ende von Aufzählungen" on duden.de](https://www.duden.de/sprachwissen/sprachratgeber/Zeichensetzung-am-Ende-von-Aufzahlungen)).

2023-09-05 14:44 UTC, The-Last-Cookie commented on wiki/Silence/de.md
> +- Profildetails bearbeiten (z. B. der Avatar, die Sektion "ich!", usw.)
```suggestion
- Profildetails bearbeiten (z. B. der Avatar, die Sektion "ich!" usw.)
```

2023-09-05 14:44 UTC, The-Last-Cookie commented on wiki/Silence/de.md
> +- Unangemessene Inhalte über andere Wege hochladen oder bereitstellen (z. B. Profilavatare, Einreichungen von Beatmaps, Profildetails, Banner, usw.).
```suggestion
- Unangemessene Inhalte über andere Wege hochladen oder bereitstellen (z. B. Profilavatare, Einreichungen von Beatmaps, Profildetails, Banner usw.).
```

2023-09-06 14:57 UTC, Walavouchey approved these changes

2023-09-06 14:59 UTC, agatemosu commented
thanks for the title

2023-09-06 15:08 UTC, merged