[FR] Update `Judgement/osu!catch` and `Judgement/osu!taiko`
ppy/osu-wiki pull request #9993
Opened 2023-09-01 16:16 UTC by DoryanR

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-01 16:20 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!taiko/fr.md
> +Les petites et les notes larges sont jugées par un GREAT, un OK ou un MISS en fonction de la précision avec laquelle elles sont hit. Hit une note avant la fenêtre MISS n'a aucun effet, et ne pas frap
```suggestion
Les petites et les notes larges sont jugées par un GREAT, un OK ou un MISS en fonction de la précision avec laquelle elles sont hit. Hit une note avant la fenêtre MISS n'a aucun effet, et ne pas frapper une note entraînera un MISS une fois la fenêtre MEH passée. Le fait de hit la mauvaise touche pour la couleur de la note entraînera également un MISS.
```

@Walavouchey does the MEH judgement exist on osu!taiko? I'm not sure, as there's no mention of it in the tables.

2023-09-13 14:40 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!taiko/fr.md
> +La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit max
Je pense qu'il faudrait rajouter le terme "overall difficulty" entre parenthèses car il n'est pas traduit dans l'article fr et ça a plus de sens pour son abréviation OD.

2023-09-13 14:40 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!taiko/fr.md
> +L'erreur de hit est arrondie et les valeurs maximales d'erreur de hit sont arrondie à l'entier le plus proche, ce qui signifie que pour les GREAT et les OK, les fenêtres peuvent être jusqu'à 1,5 ms p
```suggestion
L'erreur de hit est arrondie et les valeurs maximales d'erreur de hit sont arrondies à l'entier le plus proche, ce qui signifie que pour les GREAT et les OK, les fenêtres peuvent être jusqu'à 1,5 ms plus courtes des deux côtés, tandis que les fenêtres de miss peuvent être jusqu'à 0,5 ms plus courtes ou plus large des deux côtés, par rapport à ce que les formules suggèrent.
```

2023-09-13 14:40 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!taiko/fr.md
> +Un hit trop rapide ou trop lent empêchera la collecte des ticks. Les limites sont environ de hit deux fois plus vite que les ticks apparaissent et de hit plus lentement que tout les 5 ticks.
```suggestion
Un hit trop rapide ou trop lent empêchera la collecte des ticks. Les limites des hits sont à peu près deux fois plus rapides que l'apparition des ticks, et plus lentes que tous les 5 ticks.
```

2023-09-13 15:07 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!taiko/fr.md
> +La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit max
```suggestion
La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) (overall difficulty) de la beatmap. Un hit est considéré à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit maximum`, ce qui signifie que la valeur indiquée est égale à la moitié de la largeur de la fenêtre. La fenêtre MISS compare par exception `erreur de hit ≤ erreur de hit maximum` à la place.
```

2023-09-19 16:58 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!taiko/fr.md
> +La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) (overall difficulty) de la beatmap. Un hit est considéré à l'intérieur d'une fenêtre de hit si `erreur de hi
```suggestion
La fenêtre de hit dépend de la [overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit maximum`, ce qui signifie que la valeur indiquée est égale à la moitié de la largeur de la fenêtre. La fenêtre MISS compare par exception `erreur de hit ≤ erreur de hit maximum` à la place.
```

2023-09-20 09:38 UTC, Biokax requested changes

2023-09-20 09:38 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!taiko/fr.md
> +La fenêtre de hit dépend de la [overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit max
```suggestion
La fenêtre de hit dépend de l'[overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit maximum`, ce qui signifie que la valeur indiquée est égale à la moitié de la largeur de la fenêtre. La fenêtre MISS compare par exception `erreur de hit ≤ erreur de hit maximum` à la place.
```

2023-09-21 00:32 UTC, cl8n approved these changes

2023-09-21 00:34 UTC, merged