[FR] Update `Judgement/osu!`
ppy/osu-wiki pull request #9994
Opened 2023-09-01 16:21 UTC by DoryanR

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

2023-09-13 14:56 UTC, Biokax requested changes

2023-09-13 14:56 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreu
comme pour la pr sur judgement/taiko, voir pour rajouter "overall difficulty" pour rester cohérent avec la page associée

2023-09-13 14:56 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Les [sliders](/wiki/Gameplay/Hit_object/Slider) sont constitués de plusieurs parties : la [slider head](/wiki/Gameplay/Hit_object/Slider/Sliderhead), la [slider tail](/wiki/Gameplay/Hit_object/Slider
```suggestion
Les [sliders](/wiki/Gameplay/Hit_object/Slider) sont constitués de plusieurs parties : le [slider head](/wiki/Gameplay/Hit_object/Slider/Sliderhead), le [slider tail](/wiki/Gameplay/Hit_object/Slider/Slidertail), les [sliders ticks](/wiki/Gameplay/Hit_object/Slider/Slider_tick), et les [sliders repeats](/wiki/Gameplay/Hit_object/Slider/Reverse_slider). Le slider dans son ensemble est jugé en fonction du nombre de parties que le joueur a hit, comme indiqué ci-dessous :
```

2023-09-13 14:56 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +Il suffit que la slider head soit touchée dans la fenêtre de hit de la MEH pour que le hit soit réussi. Cependant, si [ScoreV2](/wiki/Gameplay/Game_modifier/ScoreV2) est actif, la précision de la sli
```suggestion
Il suffit que le slider head soit touché dans la fenêtre de hit de la MEH pour que le hit soit réussi. Cependant, si [ScoreV2](/wiki/Gameplay/Game_modifier/ScoreV2) est actif, la précision du slider head est également prise en compte, le jugement reçu pour l'ensemble du slider étant limité au maximum à celui reçu pour le slider head.
```

2023-09-13 14:56 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Hit la slider head trop tôt (avant la fenêtre MEH), miss un slider tick, ou un repeat n'entraîne pas un MISS, mais causera un [combo break](/wiki/Gameplay/Judgement/Combobreak). Les autres parties
```suggestion
- Hit le slider head trop tôt (avant la fenêtre MEH), miss un slider tick, ou un repeat n'entraîne pas un MISS, mais causera un [combo break](/wiki/Gameplay/Judgement/Combobreak). Les autres parties du slider peuvent toujours être hit si une touche est maintenue enfoncée. C'est ce qu'on appelle familièrement un [slider break](/wiki/Gameplay/Judgement/Slider_break).
```

2023-09-13 14:56 UTC, Biokax commented on wiki/Gameplay/Judgement/osu!/fr.md
> +- Le fait que les spinners soient trop courts peut les avoir empêchés d'être complètement clear.
```suggestion
- Le fait que les spinners soient trop courts a pu les empêcher d'être complètement clear.
```

2023-09-13 15:10 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreu
```suggestion
La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) (overall difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit maximale`, ce qui signifie que la valeur indiquée est égale à la moitié de la largeur de la fenêtre de hit.
```

2023-09-19 16:57 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +La fenêtre de hit dépend de la [difficulté globale (OD)](/wiki/Beatmap/Overall_difficulty) (overall difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `
```suggestion
La fenêtre de hit dépend de la [overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit maximale`, ce qui signifie que la valeur indiquée est égale à la moitié de la largeur de la fenêtre de hit.
```

2023-09-20 09:57 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +La fenêtre de hit dépend de la [overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreu
```suggestion
La fenêtre de hit dépend de l'[overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit maximale`, ce qui signifie que la valeur indiquée est égale à la moitié de la largeur de la fenêtre de hit.
```

2023-09-20 17:51 UTC, DoryanR commented on wiki/Gameplay/Judgement/osu!/fr.md
> +La fenêtre de hit dépend de l'[overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur
```suggestion
La fenêtre de hit dépend de [l'overall difficulty (OD)](/wiki/Beatmap/Overall_difficulty) de la beatmap. Un hit est considéré comme étant à l'intérieur d'une fenêtre de hit si `erreur de hit < erreur de hit maximale`, ce qui signifie que la valeur indiquée est égale à la moitié de la largeur de la fenêtre de hit.
```

2023-09-21 00:22 UTC, cl8n approved these changes

2023-09-21 00:24 UTC, merged